### ISSUE TITLE
Control Rust version with rust-toolchain file

### ISSUE THREAD

**Issue by RalfJung** [travis-ci/travis-ci#10002]
Our project has a `rust-toolchain` file which tells rustup which exact nightly version to use. Unfortunately, Travis downloads and install the `nightly` Rust channel before rustup notices that we really need `nightly-2018-08-14`, so Rust is downloaded and installed twice. This is not only a waste of bandwidth, it currently also makes the builds noticeably slower.

I tried fixing this by setting `TRAVIS_RUST_VERSION` in `before_install`, but that already seems to be too late.

Could Travis' automatic Rust setup somehow become smarter and take the `rust-toolchain` file into account? Or, alternatively, is there some way to run my own code before the automatic Rust setup so that I can tweak the `TRAVIS_RUST_VERSION` env var?

**Comment by BanzaiMan** [comment]
You can set this with `rust`, which is passed on to `--default-toolchain=` argument for `rustup`. For example:

```yaml
language: rust
rust:
  - nightly-2018-08-14
```

yields:

```sh-session
$ rustc --version
rustc 1.30.0-nightly (d5a448b3f 2018-08-13)
```

https://travis-ci.org/BanzaiMan/travis_production_test/builds/434887302#L448

**Comment by BanzaiMan** [comment]
Also, see https://docs.travis-ci.com/user/languages/rust#choosing-a-rust-version. Perhaps we can give more details in the docs.

**Comment by RalfJung** [comment]
Unfortunately, putting the version into `.travis.yml` is not a solution. That would mean we have to keep the version in two places (one place for travis and one where rustup and/or shell scripts can access it), which is bound to lead to problems.

**Comment by BanzaiMan** [comment]
Indeed. I think we should read the content of that file during at run time.

**Comment by BanzaiMan** [comment]
https://github.com/rust-lang-nursery/rustup.rs#the-toolchain-file

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
