### ISSUE TITLE
git clone of public repo fails in travis install

### ISSUE THREAD

**Issue by lzkelley** [travis-ci/travis-ci#10007]
I'm trying to clone a repo which includes test data to use during the travis build.  In the `install:` section I have,

    - git clone https://github.com/astrocats/testcat.git

which is a public repository.  I'm still [getting authorization errors](https://travis-ci.org/astrocatalogs/astrocats/jobs/416522254), however:

```
Cloning into 'testcat'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/astrocats/testcat.git/'
The command "git clone https://github.com/astrocats/testcat.git" failed and exited with 128 during .
```

But the command `git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG` works fine!

**Comment by iriberri** [comment]
Hi @lzkelley!
It looks like https://github.com/astrocats/testcat gives a 404 in GitHub - do you know if the project was renamed or if there might be a typo there?

**Comment by lzkelley** [comment]
Hi @iriberri ... ugh, I don't know how I could possibly have missed this.  I really wish there was a way to delete an opened issue.  Sorry!  (And thanks!)
