### ISSUE TITLE
Docker containers are working differently

### ISSUE THREAD

**Issue by miolae** [travis-ci/travis-ci#10000]
Hi all! I need a bit help with Travis.

I have a repo on github with branch "travis". In that branch I've added docker containers and `.travis.yml` config file. Everything works fine at my home computer (win 10 pro) and on my server (ubuntu 16.04). But when I push changes to github (and Travis getting them) I see the error: `SQLSTATE[HY000] [1045] Access denied for user 'billing_test'@'172.18.0.3' (using password: YES)`

Why so?

Repo: [miolae/yii2-billing](https://github.com/miolae/yii2-billing/tree/travis)

**Comment by joepvd** [comment]
We see that your builds are green again. We assume that this means you have resolved this issue.

If not, please reopen, and include a link to a build log you'd like us to have a look at.

**Comment by miolae** [comment]
I'm sorry I didn't close this issue. There was a mistake in my docker config I couldn't find for some weeks.
