### ISSUE TITLE
make julia-maintainers team public

### ISSUE THREAD

**Issue by simonbyrne** [travis-ci/travis-ci#10003]
It seems that other users can't contact us via @travis-ci/julia-maintainers because the team is private. Could this be made public?

**Comment by simonbyrne** [comment]
Ah, there's no option to make it generally public (beyond the org): that is annoying.

**Comment by BanzaiMan** [comment]
Is there anything to do here?

**Comment by simonbyrne** [comment]
Unfortunately not. I guess I will have to revert the documentation back. Thanks anyway.
