### ISSUE TITLE
Erlang 20.3.8.5 

### ISSUE THREAD

**Issue by bryanhuntesl** [travis-ci/travis-ci#10001]
There are a couple of bugs fixed in this version vs 20.3 - specifically 20.3 breaks the gen_rpc Erlang application. 

Any chance of getting it installed and available for builds.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/travis-erlang-builder/builds/432034764

**Comment by bryanhuntesl** [comment]
Thank you
