### ISSUE TITLE
Debug build not setting correct build status after exiting

### ISSUE THREAD

**Issue by donofriov** [travis-ci/travis-ci#10009]
### Description

From what I understand Debug build is supposed to set the build status back to whatever the last build status was after you exit. If I have a failed build, then run debug build and then exit, I will see a failed build again. The issue is with cancelled builds.

### Steps to reproduce
1. Have a failed build.
2. Click restart build.
3. Click cancel build.
4. Click debug build.
5. Exit debug build.

### Actual result:
Build status is now successful.

### Expected Result
Build status should be set to whatever the previous build status was. In the `steps to reproduce` example, I would expect the build status to be set back to failed.

**Comment by BanzaiMan** [comment]
Hello, thanks for opening this issue.

This is an interesting edge case; when you restart and cancel a previously failing job, we reset the job's status. I am not sure if I agree with the expected result, though; it should be "an error" to indicate the unknown state.

**Comment by donofriov** [comment]
@BanzaiMan thanks for the response. I think an "error state" would make sense as well, I just don't think it should be set back to successful.

**Comment by DrTorte** [comment]
Hello,

I've made sure this is being tracked internally. In the meanwhile, we're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
