### ISSUE TITLE
Issues with Deploying to Heroku via Travis-CI

### ISSUE THREAD

**Issue by andrico1234** [travis-ci/travis-ci#10018]
I keep getting this error when deploying with Heorku and have been getting it with several different repos that I'm trying to deploy to Heroku after running their build through travis. 

```
No stash entries found.
API request failed.
Message: Invalid credentials provided.
Reference: 
failed to deploy
``` 

I don't get any more information than that .I tried updating my Heroku API key but that didn't seem to work. I've used the `travis setup heroku` command as well as creating the build step manually, but I still get the same error. Here's what the deploy section of my .travis.yml file looks like

```
deploy:
  provider: heroku
  api_key:
    secure: g3gj25vI58r48P63E...
  app: heroku-travis-test-01
  on:
    repo: andrico1234/heroku-travis-test
```

Is this a common issue?

Edited: Adding Travis' install dependencies stack trace
```
2.71s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Fetching: dpl-1.10.0.gem (100%)
Successfully installed dpl-1.10.0
1 gem installed
dpl.1
Installing deploy dependencies
Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.15.2.gem (100%)
Successfully installed faraday-0.15.2
Fetching: rendezvous-0.1.2.gem (100%)
Successfully installed rendezvous-0.1.2
Fetching: netrc-0.11.0.gem (100%)
Successfully installed netrc-0.11.0
Fetching: dpl-heroku-1.10.0.gem (100%)
Successfully installed dpl-heroku-1.10.0
5 gems installed
```

**Comment by iriberri** [comment]
Hi @andrico1234! I think the issue here might be in the encryption of the API key.

Could you try running the setup command as:

`travis setup heroku --org -r <repo_slug>`, if your project is running in travis-ci.org

or 

`travis setup heroku --pro -r <repo_slug>`, if your project is running in travis-ci.com

and let us know if this helps?

If your project is open source and is built in travis-ci.com, I think the Travis CLI might be encrypting it against .org instead.

**Comment by rugleb** [comment]
I have this issue too.

@iriberri Try use --org, but witthot result.

**Comment by iriberri** [comment]
@rugleb would you like to let us know more details about your case here? If this is a private repo and you'd prefer not to share this publicly, please let us know at support@travis-ci.com. Thanks!

**Comment by rugleb** [comment]
@iriberri yes, I would like to describe my problem.

I apologize in advance for my English.
I have been using `Heroku` for a long time, but I'm new to `Travis`. 
Now I'm developing a new application ([github](https://github.com/rugleb/raog-cafe)) on Laravel (PHP) and decided to try using `Travis` with the ability to deploy on `Heroku`.

It seems to me that I quickly figured out the setup of the `Travis CI` and everything works the way I expect. BUT. When I added the [deploy](https://github.com/rugleb/raog-cafe/blob/84cf5bcefccb267873c21423e4b65f4a3c3a4815/.travis.yml#L23) function to the `.travis.yml`, as described in [this article](https://docs.travis-ci.com/user/deployment/heroku/), build is broke.

I spent half a day looking for a solution to the problem, but all the articles and recommendations led to the same thing: ` travis encrypt $(heroku auth:token) --add deploy.api_key` or use other similar commands. Everything **did not work**.

However, if I set my `HEROKU API KEY` from [Heroku account](https://dashboard.heroku.com/account) directly without encryption in `deploy` section, then everything ended with success! Example:
```
deploy:
  provider: heroku
  api_key:
    secure: 77f8c0e7-01e0-****
  app: raog-cafe
```
And **this work**!
But with command like ` travis encrypt $(heroku auth:token) --add deploy.api_key`:
```
deploy:
  provider: heroku
  api_key:
    secure: 2scX2GPTG7/C8G****
  app: raog-cafe
```
This **does not work**!

I use `Heroku CLI`, `travis` from `gem` and `Ubuntu 18`. My Heroku deploy section:
![screenshot from 2018-08-28 20-59-33](https://user-images.githubusercontent.com/26823697/44741284-4bd16380-ab05-11e8-9983-e92626a45c7c.png)

![image](https://user-images.githubusercontent.com/26823697/44741238-280e1d80-ab05-11e8-8787-bda88ec359c5.png)
I really hope for your help! Thank you in advance!

**Comment by iriberri** [comment]
Thanks for the thorough description, @rugleb! :)

I checked and I see that even though this project is open source, it's running in travis-ci.com, so you'd need to use `--pro` instead of `--org`. I understand how this can be confusing, hope we can avoid this soon when the merge of the two platforms is ready!

Could you try the following instead?

`travis encrypt <paste_your_token_here> --add deploy.api_key --pro -r rugleb/raog-cafe`

This is:
* Pasting your Heroku token directly in the command, just in case what `heroku auth:token` is returning is not the same token you're using in the .travis.yml directly. I don't think this is the issue, but well, just to try!
* Add the `--pro` flag - which will use travis-ci.com API's to encrypt your token. I think this is indeed the issue here.
* Add the `-r <repo_name>` argument to the travis encrypt command. This is not needed by default, but it can happen when working with forks of repos (which doesn't seem to be the case) that travis encrypt runs against the original repo instead of the fork, or vice versa, and then decryption doesn't work.

Please let me know how it goes! :)

**Comment by rugleb** [comment]
Thank you for your sympathy and help, @iriberri! 

Strangely enough, but I solved the problem a couple of hours after I wrote the last message here.
I found that in my `Github` account I connected 2 Travis services: `travis-ci.com` and `travis-ci.org`. After that I looked at each site and found that on the `org` domain everything was going well, but on `pro`, bad. Then I tried again to use the flag ` --pro` for encryption of the key and the situation was exactly the opposite. It's strange that I did not notice it before, apparently the night had an effect.
But now I understand everything and feel confident in `travis-ci`.

I hope my mistakes (inattention) and your comments will help someone else.

**Comment by iriberri** [comment]
@rugleb awesome -happy to hear this helped! What you explain makes sense! :-) I'd recommend deactivating the project from travis-ci.org if you've finally moved to travis-ci.com, to avoid any issues in general.

**Comment by goldtreefrog** [comment]
The --pro flag did it for me too. For lazy readers, here is how to get your Heroku API key if you are using travis-ci.com instead of travis-ci.org. Just do this:

  travis encrypt $(heroku auth:token) --add deploy.api_key --pro

Bingo!

**Comment by hoverlover** [comment]
This really should be updated in the docs [here](https://docs.travis-ci.com/user/deployment/heroku/).  It would save people so much time.

**Comment by nicbuitr** [comment]
For some reason `heroku auth:token` was returning a wrong token for me, even after making sure that I was logged in to heroku on the command line.

After trying all the solutions posted, what worked for me was:

- Go to [Heroku Account](https://dashboard.heroku.com/account)
- Manually copy the API Key and then paste it into command line:
  - For the ones hosted at [travis-ci.com](https://travis-ci.com):
    - `travis encrypt pasteAPIKeyHere --add deploy.api_key --pro`
  - For the ones hosted at [travis-ci.org](https://travis-ci.org):
    - `travis encrypt pasteAPIKeyHere --add deploy.api_key --org`

Hope this helps.

**Comment by nicbuitr** [comment]
For some reason `heroku auth:token` was returning a wrong token for me, even after making sure that I was logged in to heroku on the command line.

After trying all the solutions posted, what worked for me was:

- Go to [Heroku Account](https://dashboard.heroku.com/account)
- Manually copy the API Key and then paste it into command line:
  - For the ones hosted at [travis-ci.com](https://travis-ci.com):
    - `travis encrypt pasteAPIKeyHere --add deploy.api_key --pro`
  - For the ones hosted at [travis-ci.org](https://travis-ci.org):
    - `travis encrypt pasteAPIKeyHere --add deploy.api_key --org`

Hope this helps.
