### ISSUE TITLE
Deploy keeps failing

### ISSUE THREAD

**Issue by caesarleroux** [travis-ci/travis-ci#10014]
So I found different pieces of documentation and pieced together a set of scripts that let me run a build task with `make` on the Travis CI server and when I tried to deploy the built product to my GitHub pages site using my encrypted GitHub token (`echo GH_TOKEN=mytoken | travis encrypt --add`) the deploy continuously fails. I tried this with multiple tokens and it did not work. Please help me, I am at my wits end! Repos that are concerned by this issue:

- https://github.com/caesarleroux/atomic
- https://github.com/caesarleroux/TigersLair

**Comment by iriberri** [comment]
Hi @caesarleroux - could you please share a link to one of the failing builds? Thanks!

**Comment by caesarleroux** [comment]
@iriberri Thanks for taking so long, GitHub is not what it used to be. Resolved the issue by myself.
