### ISSUE TITLE
PostgreSQL 10 APT packages disallowed

### ISSUE THREAD

**Issue by chosak** [travis-ci/travis-ci#10012]
Starting today, when using [the recommended Postgres 10 setup](https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version) on Trusty:

```
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
```

I see [install failures](https://api.travis-ci.org/v3/job/417268598/log.txt) with this message:

> Installing APT Packages (BETA)
Disallowing packages: postgresql-10, postgresql-client-10
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process

This worked as recently as yesterday, and we haven't changed anything else in our `.travis.yml`. Has something changed on the Travis/Trusty side around this?

I notice that `postgresql-10` and `postgresql-client-10` aren't included in [the list of approved Trusty packages](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty); were they before?

I see an [older request](https://github.com/travis-ci/apt-package-whitelist/issues/4254) trying to add `postgresql-10` to the package whitelist which seems to have failed due to a missing APT source. The PG APT repo does seem to be in the [source whitelist](https://github.com/travis-ci/apt-source-whitelist/blob/73adbe9900f33e9fd71c20401a16664a3959d4bd/ubuntu.json#L377), but was added to that list (April 3rd) after the older request was processed (January 6th).

I've submitted two new issues (https://github.com/travis-ci/apt-package-whitelist/issues/4314, https://github.com/travis-ci/apt-package-whitelist/issues/4315) to try to whitelist these packages again.

**Comment by BanzaiMan** [comment]
It appears to me that the error is not so much the failure to install the pacakge, but the installation is now detecting the use of port 5432 and [using a new port (5433)](https://travis-ci.org/cfpb/cfgov-refresh/jobs/417268598#L482). So, if you try to connect to the well-known port 5432, your attempts will fail.

You'll need to change the port for the PostgreSQL 10 installation, and restart it. I explained the process in https://travis-ci.community/t/trusty-sudo-postgresql-listening-on-port-5433-cant-resolve-why/712/4?u=banzaiman

I'm closing this optimistically.
