### ISSUE TITLE
No builds for this repository. A prior build is still executing.

### ISSUE THREAD

**Issue by picestcode** [travis-ci/travis-ci#10010]
For my repository https://travis-ci.org/picestcode/Fishmetica.jl, Travis shows "No builds for this repository". Under Requests, it indicates that " A prior build is still executing." If I sign in again, I can see that the build is passing.  The issue may be similar to closed #3991, #3996, #4040, #4094,  #6951. Seems I need some help from the Travis team.

**Comment by iriberri** [comment]
Hi @picestcode - thanks for reporting this and sorry for the troubles.

I've been investigating further about the code running behind this "A prior build is still executing." error message, and it seems that our code is not correctly taking into account the case where no previous build has run for the given branch associated to the cron job.

My recommendation to sort this out as soon as possible would be to trigger an initial build on your branch. After that, I believe the crons should start behaving as expected. It's possible to trigger a build on a branch directly from Travis CI with our "trigger build" option (https://blog.travis-ci.com/2017-08-24-trigger-custom-build).

Would you like to give this a try and let us know how it goes?

**Comment by BanzaiMan** [comment]
I think it's working now. Closing.
