### ISSUE TITLE
macOS 10.13 images can't load third-party kernel extensions (osxfuse suddenly broken and unusable)

### ISSUE THREAD

**Issue by jmmv** [travis-ci/travis-ci#10017]
I have a build that installs osxfuse by running the following commands:

```
brew update
brew cask install osxfuse
sudo /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse
```

Unfortunately, the last command (`load_osxfuse`, which is required for FUSE to function without a reboot) has started failing suddenly, consistently, and my Mac builds are broken because the FUSE kernel extension is not being loaded. Nothing has changed on my codebase at all and the latest successful build I have is from July 26th. Something must have changed since then in the Travis Mac environment to cause this to fail.

I've ran `dmesg` on the failed builds after the call to `load_osxfuse` and I see things like this:

```
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
[... repeated many, many times ...]
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: hdiutil(4497) System Policy: deny(5) file-read-metadata /Volumes/VMware Shared Folders
Sandbox: hdiutil(4497) System Policy: deny(5) file-read-metadata /Volumes/VMware Shared Folders
Sandbox: hdiutil(4498) System Policy: deny(5) file-read-metadata /Volumes/VMware Shared Folders
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: diskimages-helpe(4501) System Policy: deny(5) file-read-metadata /Volumes/VMware Shared Folders
Sandbox: mdworker(2077) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2077) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
considerRebuildOfPrelinkedKernel com.vmware.kext.vmmemctl triggered rebuild
hfs: mounted FUSE for macOS on device disk1
Sandbox: coreservicesd(103) deny(1) nvram-get BSD Name
Sandbox: mdworker(2077) deny(1) system-fsctl 4a0e
Sandbox: TMHelperAgent(4515) System Policy: deny(5) file-read-metadata /Volumes/VMware Shared Folders
Sandbox: TMHelperAgent(4515) System Policy: deny(5) file-read-metadata /Volumes/VMware Shared Folders
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
[... repeated many, many times ...]
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
hfs: unmount initiated on FUSE for macOS on device disk1
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: installer(4525) System Policy: deny(1) file-read-data /dev/disk0s3
Sandbox: installer(4525) System Policy: deny(1) file-read-data /dev/disk0s3
Sandbox: installer(4525) System Policy: deny(1) file-read-data /dev/disk0s3
Sandbox: installer(4525) System Policy: deny(1) file-read-data /dev/disk0s3
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
Sandbox: mdworker(2333) deny(1) system-fsctl 4a0e
```

I have found https://github.com/osxfuse/osxfuse/issues/358 on the OSXFUSE issue tracker, which I think might be related, but I'm not sure yet.

Troubleshooting this without direct access to the Mac environment configured by Travis is very hard, so I'd appreciate someone that does have such access taking a look.

**Comment by mjm** [comment]
Hi @jmmv!

Does your .travis.yml file specify an `osx_image` to use? If not, then it will use our default image, which [changed from `xcode8.3` to `xcode9.4` on July 31](https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce).

The `xcode9.4` image runs on macOS 10.13, while the `xcode8.3` image runs on macOS 10.12. In macOS 10.13, Apple started requiring users to explicitly allow third-party kernel extensions before it will load them. You can find out more about this in [this tech note from Apple](https://developer.apple.com/library/archive/technotes/tn2459/_index.html).

We don't currently have an answer for working around this while using our macOS 10.13-based images. You can likely fix your build by explicitly requesting a macOS 10.12 image by including `osx_image: xcode8.3` in your .travis.yml file.

**Comment by jmmv** [comment]
Yup, thanks, that was it!

I was about to close this bug... but thought that maybe you could keep it around with a more accurate title until there is a known solution for the kernel extensions issue? I suppose I'm not the only one having problems with OSXFUSE (or other extensions) and it'd be great to have a tracking bug somewhere.

**Comment by mjm** [comment]
Sure, let's keep it around for tracking that!

**Comment by jmmv** [comment]
I'm wondering if the problems that we found here are caused by SIP, and if disabling SIP would let this work. If so, I discovered last week that SIP can be disabled partially (better than disabling it fully), so maybe we'd try it somehow? Running `csrutil enable --without kext` should do the trick, but that has to be run from recovery mode (i.e. when preparing the image).

**Comment by taralx** [comment]
According to that same technical note, the command is `spctl kext-consent`, from recovery.

**Comment by mcafaro** [comment]
Also interested in this capability on newer macOS versions.

**Comment by gaul** [comment]
Is there some reason this bug is closed?  This is still an issue and there is no workaround.  Apple no longer supports macOS 10.12 so eventually we will need some way forward.
