### ISSUE TITLE
dist: xenial with/without group: travis_latest launches Trusty

### ISSUE THREAD

**Issue by achimnol** [travis-ci/travis-ci#10024]
https://travis-ci.org/achimnol/aiotools/jobs/419947489
![image](https://user-images.githubusercontent.com/555156/44563691-4e952700-a79a-11e8-8510-a750ea598760.png)

It seems to have recognized the configuration correctly but the actual environment is Trusty.
I'd like to know if I missed something or it might be a potential bug/issue.

**Comment by BanzaiMan** [comment]
This should not be a problem any longer.
