### ISSUE TITLE
[skip-ci] and [ci-skip] still trigger build...

### ISSUE THREAD

**Issue by thathurtabit** [travis-ci/travis-ci#10027]
Both [skip-ci] and [ci-skip] still trigger Travis build...

I presume I'm missing something? Thanks all.

**Comment by dilawar** [comment]
I use [skip ci] (without `-`). Just try it once. Docs also suggest the same https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

**Comment by thathurtabit** [comment]
Totally my bad then. Is it worth including the hyphenated command for idiots like myself?

**Comment by BanzaiMan** [comment]
Hello, there. Expanding what is allowed to trigger this condition seems a bad idea to me. For the foreseeable future, please use the white space. Thank you!
