### ISSUE TITLE
Inaccurate documentation about OS X and JDK versions

### ISSUE THREAD

**Issue by mernst** [travis-ci/travis-ci#10022]
The documentation [JDK and OS X](https://docs.travis-ci.com/user/reference/osx/#jdk-and-os-x) says that the default OS X image `xcode9.4` uses JDK 1.8.0_112-b16.  However, [this log](https://travis-ci.org/codespecs/test-daikon-staging-macosx/builds/419320059) uses the default image and [xcode 9.4.1](https://travis-ci.org/codespecs/test-daikon-staging-macosx/builds/419320059#L16) but [JDK 10](https://travis-ci.org/codespecs/test-daikon-staging-macosx/builds/419320059#L79).
**Request**: Could you please update the documentation, or change the xcode9.4 image?

I tried using the
```
jdk:
  - openjdk8
```
block in my `.travis.yml`, but [the build](https://travis-ci.org/codespecs/test-daikon-staging-macosx/builds/419420579) still used JDK 10.
**Request**:  If this doesn't work on OS X, please update [the documentation](https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks) to say that explicitly.

Finally, I put
```
osx_image: xcode9.3
```
in my `.travis.yml` file, and this gave me JDK 8.

**Comment by iriberri** [comment]
Hi @mernst - thanks a lot for bringing this to our attention.

I have moved this report to our documentation repo at https://github.com/travis-ci/docs-travis-ci-com/issues/1997

We'll follow-up the conversation there!

Thanks again.
