### ISSUE TITLE
PyPI upload failed.

### ISSUE THREAD

**Issue by chfw** [travis-ci/travis-ci#10025]
Hey,

I am experimenting travis upload to pypi and am using test.pypi.org at the moment. However, travis simply says "PyPI upload failed." How could I find out what went wrong myself? Any hints will be helpful.

travis log:
https://travis-ci.org/pyexcel/pyexcel/jobs/419875590

travis config:
https://github.com/pyexcel/pyexcel/blob/dev/.travis.yml

Thanks

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/10056#issuecomment-423784601. I think `twine` is printing that message, and I don't know why. I'm closing this as a duplicate.
