### ISSUE TITLE
Consistency - "Ran for" and "Total time" - possibly mixed up on build summary page?

### ISSUE THREAD

**Issue by jameswilddev** [travis-ci/travis-ci#10038]
Right of the upper middle when viewing a [build summary page](https://travis-ci.org/jameswilddev/vnhtml/builds/420783750), "ran for" appears to be the time span between the commit and the last job completing, while "total time" appears to be the amount of time spent processing jobs; the difference being, that if Travis CI couldn't start the jobs immediately, "ran for" will include that time, while "total time" will not.

![_a](https://user-images.githubusercontent.com/3138458/44631511-10982e80-a965-11e8-842e-63fdc9745857.png)

On a [job summary page](https://travis-ci.org/jameswilddev/vnhtml/jobs/420783751), on the other hand, "ran for" is the amount of time spent processing jobs.

![_b](https://user-images.githubusercontent.com/3138458/44631527-38879200-a965-11e8-8186-d0324d927a05.png)

Thanks again for this simply wonderful service :)

**Comment by BanzaiMan** [comment]
"Ran for" means the clock time the lapsed from the start to finish of a build. "Total time" is the sum of all jobs' execution time. If there is a delay in starting a job within a build for one reason or another, there should be a huge discrepancy.

I hope that makes sense.

If you have suggestions on how to make these ideas more succinct, however, we would like to hear them!

Thank you!
