### ISSUE TITLE
Travis build failing with s3.rb:56:in `chdir': No such file or directory @ dir_chdir - public (Errno::ENOENT)

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis-ci#10032]
I am trying to push a file to s3, below is my code.. any suggestions are open
======
sudo: required
language: python
script:
  - make travis-ci
deploy:
  - provider: s3
    on:
        branch: master
    region: us-west-2
    local_dir: public
    bucket: vijeshec2cfn
    skip_cleanup: true
    acl: public_read
    access_key_id: xxxxxx (not including keys)
    secret_access_key: 
      secure: xxxxx (not including keys)

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

Also, if your `public` directory is created during the build, ensure that the `skip_cleanup` option is set. https://docs.travis-ci.com/user/deployment/s3/

**Comment by BanzaiMan** [comment]
Closing due to lack of information.

**Comment by j0k3r** [comment]
For people getting here from Google, if you got that error it might be because you misconfigured the `local_dir` option.
Be sure the `local_dir` directory exist before the deploy. Otherwise you'll got that error.

**Comment by idosius** [comment]
I had the same issue although `local_dir` was set. Looks like what solved it for me was adding `skip_cleanup: true`

**Comment by mister-x-ops** [comment]
in addition to the previous comment
I added to the deploy section `skip_cleanup: true` or `cleanup: false` for a newer version of DPL
