### ISSUE TITLE
OS X uses wrong JDK

### ISSUE THREAD

**Issue by pauldraper** [travis-ci/travis-ci#10030]
OS X images have the incorrect JDK installed.

https://docs.travis-ci.com/user/reference/osx/#os-x-version

There should be JDK 8 installed on every image except xcode10, but in fact there is JDK 10 installed on every image.

Edit: except xcode6.4 and xcode7.3.

**Comment by cotsog** [comment]
Hello and sorry for the delay of our reply.

Here's the result of running `java -version` on every image we currently have:

- xcode6.4: 1.8.0_45
- xcode7.3: 1.8.0_92
- xcode8: 1.8.0_92
- xcode8.3: 1.8.0_112
- xcode9: 1.8.0_112
- xcode9.1: 1.8.0_112
- xcode9.2: 1.8.0_112
- xcode9.3: 1.8.0_112
- xcode9.4: 10.0.1
- xcode10: 10.0.2
- xcode10.1: 11.0.1

See this build for reference: https://travis-ci.org/cotsog/travis_ci_prod_regular/builds/452215701

This is what we document to the page you have linked i.e. https://docs.travis-ci.com/user/reference/osx/#os-x-version

Could you give us more details about the incorrect JDK versions you mention? Do you have a sample build showing this?

Thanks!

**Comment by BanzaiMan** [comment]
See https://travis-ci.community/t/jdk10-is-used-instead-of-openjdk8-on-mac-os-x/661

I don't think we can provide Java 8 on newer Mac images.
