### ISSUE TITLE
Maven Surefire Report XSD requires a fix

### ISSUE THREAD

**Issue by Tibor17** [travis-ci/travis-ci#10033]
I want to inform you that XML Reports of Surefire are not valid against XSD
https://github.com/apache/maven-surefire/blob/master/maven-surefire-plugin/src/site/resources/xsd/surefire-test-report.xsd

This should be fixed in Maven Surefire.
If you use this XML and visualize the reports, pls adapt to the fix.
https://issues.apache.org/jira/browse/SUREFIRE-1559

**Comment by Tibor17** [comment]
Is somebody interested?

**Comment by BanzaiMan** [comment]
Hello, there.

When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by BanzaiMan** [comment]
Closing because there is no further input from the OP.
