### ISSUE TITLE
Travis reporting install of package x version n, but actually using version m < n

### ISSUE THREAD

**Issue by piccolbo** [travis-ci/travis-ci#10049]
Concerning build https://travis-ci.org/piccolbo/altair_recipes/jobs/422135128, it fails with the following error

```
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/altair_recipes-0.2.2-py3.6.egg/altair_recipes/signatures.py:17: in Recipe
    data = param(converter=to_dataframe)
E   TypeError: attrib() got an unexpected keyword argument 'converter'
```
The name of this argument changed recently, `converter` being the new and recommended one.  So I checked that travis is installing the correct version.  Logs indicate so:

```

Installed /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/python_dateutil-2.7.3-py3.6.egg
Searching for attrs>=18.1.0
Reading https://pypi.python.org/simple/attrs/
Downloading https://files.pythonhosted.org/packages/41/59/cedf87e91ed541be7957c501a92102f9cc6363c623a7666d69d51c78ac5b/attrs-18.1.0-py2.py3-none-any.whl#sha256=4b90b09eeeb9b88c35bc642cbac057e45a5fd85367b985bd2809c62b7b939265
Best match: attrs 18.1.0
Processing attrs-18.1.0-py2.py3-none-any.whl
Installing attrs-18.1.0-py2.py3-none-any.whl to /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages
writing requirements to /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/attrs-18.1.0-py3.6.egg/EGG-INFO/requires.txt
Adding attrs 18.1.0 to easy-install.pth file
Installed /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/attrs-18.1.0-py3.6.egg
```

This is the man page for attrs, specifically the function in question: http://www.attrs.org/en/stable/api.html#attr.ib

Shows the first version where `converter` arg is accepted at 17.4.0. Travis installed 18.1.0, as per setup.py. 

Being new to all of this, I thought operator error was highly likely. But someone else reported it in the jsonschema project: https://github.com/Julian/jsonschema/issues/449 They found a workaround there.
Thanks!

**Comment by BanzaiMan** [comment]
So, https://travis-ci.org/piccolbo/altair_recipes/builds/422175570 fixed the build? It seems that `make install-dev` (https://github.com/piccolbo/altair_recipes/commit/c25661068cbeee377c9a7c3f604477427f5fd7aa#diff-354f30a63fb0907d4ad57269548329e3R14) fixed it, right?

**Comment by piccolbo** [comment]
The problem is no longer important to me, that's not the same as fixed. It's up to you guys to decide how important it is to go to the bottom of this. As you observed my builds complete now. Thanks!
