### ISSUE TITLE
Error on stage

### ISSUE THREAD

**Issue by codeselfceo** [travis-ci/travis-ci#10040]
Hi everyone!

Can someone see the error in this code?

The first 2 stages run correctly, but when it goes to "deploying" stage, it does not work on Travis.

Thanks in advance!!

<img width="363" alt="screen shot 2018-08-26 at 22 13 41" src="https://user-images.githubusercontent.com/37206636/44640177-62e54980-a97d-11e8-9ad3-7f5797beeeae.png">

**Comment by Legogris** [comment]
@codeselfceo  It would help if you also included the build log including any error messages and warnings.

**Comment by BanzaiMan** [comment]
I'm closing this since there is no further input from the OP.
