### ISSUE TITLE
Travis not picking up PRs from github

### ISSUE THREAD

**Issue by dylandechant** [travis-ci/travis-ci#10050]
we are using Travis on a lot of our repositories, and all but one are fine.

Travis used to run on this repo, there was a PR today (first in a month or so), and travis (or github) just hangs
<img width="817" alt="screen shot 2018-08-29 at 11 39 56 am" src="https://user-images.githubusercontent.com/5204375/44802055-4fee9700-ab80-11e8-8549-3bb1d5ac62d0.png">

and in travis i see no movement and nothing even queued.

I'd be more than happy to DM the repo to whoever picks up this ticket.

Thanks!

**Comment by DrTorte** [comment]
Hey there - I'd suggest sending this in to support@travis-ci.com for us to investigate. If that's not an option you can DM me and I'll see what we can do about it.

**Comment by BanzaiMan** [comment]
I'm closing this, as it doesn't seem public for further troubleshooting.
