### ISSUE TITLE
rake failed error confusing when .travis.yml file isn’t valid

### ISSUE THREAD

**Issue by aral** [travis-ci/travis-ci#1005]
I switched my .travis.yml file to tabs from spaces and started getting rake‐related errors (even though it was a node project).

Took me a while to realise that the it was the yml file causing the problem (fixed after going back to using spaces—yuck!)

In any case, a note on this somewhere in the docs or a better error message would be nice. Thanks! :)

**Comment by robotail** [comment]
Tnks so much!! helped a lot
