### ISSUE TITLE
Please add clang-7 repo from apt.llvm.org

### ISSUE THREAD

**Issue by rhalbersma** [travis-ci/travis-ci#10069]
LLVM updated its repo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" to point to the nightly build of the clang-8 release.

The previous tip-of-trunk snapshot now resides in "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main". 

However, Travis does not whitelist this yet, so we can't run this without sudo support.

**Comment by rhalbersma** [comment]
The pending PR [#392](https://github.com/travis-ci/apt-source-safelist/pull/392) will resolve this request.

**Comment by BanzaiMan** [comment]
This should be available now.
