### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by double-beep** [travis-ci/travis-ci#10061]
Hello,

I am getting an error when trying to open a file named fasmg **that exists**:
```
/home/travis/.travis/job_stages: line 78: ./fasmg: No such file or directory
```
I tried to open it without chmod and:
```
./fasmg: Permission denied
```
An `ls -la` command showed:
```
total 552
drwxrwxr-x 12 travis travis   4096 Aug 29 16:34 .
drwxrwxr-x 10 travis travis   4096 Aug 29 16:33 ..
-rw-rw-r--  1 travis travis   6002 Aug 29 16:34 appveyor.yml
drwxrwxr-x  3 travis travis   4096 Aug 29 16:34 arm
drwxrwxr-x  2 travis travis   4096 Aug 29 16:34 docs
-rw-rw-r--  1 travis travis   2412 Aug 29 16:34 download.vbs
drwxrwxr-x  6 travis travis   4096 Aug 29 16:34 examples
-rwxrw-r--  1 travis travis  52343 Aug 18 22:52 fasmg
-rw-rw-r--  1 travis travis  53760 Aug 18 22:52 fasmg.exe
-rw-rw-r--  1 travis travis 343437 Aug 18 20:52 fasmg.zip
drwxrwxr-x  8 travis travis   4096 Aug 29 16:34 .git
-rw-rw-r--  1 travis travis   1496 Jul 11 15:41 license.txt
drwxrwxr-x  2 travis travis   4096 Aug 29 16:34 LinuxOS_binaries
drwxrwxr-x  2 travis travis   4096 Aug 29 16:34 MacOS_binaries
-rw-rw-r--  1 travis travis  17818 Aug 29 16:34 make.bat
-rw-rw-r--  1 travis travis   1530 Aug 29 16:34 makefile
drwxrwxr-x  2 travis travis   4096 Aug 29 16:34 Matefinder_binaries
-rw-rw-r--  1 travis travis  10862 Aug 29 16:34 README.md
-rw-rw-r--  1 travis travis   1074 Dec 17  2017 readme.txt
drwxrwxr-x  6 travis travis   4096 Aug 29 16:34 source
-rw-rw-r--  1 travis travis    354 Aug 29 16:34 .travis.yml
drwxrwxr-x  2 travis travis   4096 Aug 29 16:34 WindowsOS_binaries
drwxrwxr-x  3 travis travis   4096 Aug 29 16:34 x86
```
and as you can see fasmg exists.

[chmod](https://travis-ci.com/double-beep/asmFish/builds/83256691)
[no chmod](https://travis-ci.com/double-beep/asmFish/builds/83253604)
[ls -la](https://travis-ci.com/double-beep/asmFish/builds/83254667)
content of `.travis.yml`
```
sudo: true
dist: trusty
cache: ccache
os: linux

script:
  - git clone --branch=travis https://github.com/double-beep/asmFish.git C:/Projects/asmFish
  - cd C:/Projects/asmFish/
  - wget --no-check-certificate flatassembler.net/fasmg.zip
  - unzip -o fasmg.zip
  - ls -la
  - chmod 755 fasmg
  - ls -la
  - ./fasmg "x86/fish.asm" "asmfish"
```

Hope this helps!

Any idea about that?

**Comment by BanzaiMan** [comment]
I don't think the file exists in the directory you think. https://github.com/double-beep/asmFish/blob/3beaeabfed12ce69d96679ceaa22211d8918f9e7/.travis.yml#L10

You are cloning the git repo to `C:\Projects\asmFish`, but this directory is not accessible as `C:\Projects\asmFish` on a UNIX file system; `\a` is an escape sequence for the visual bell, and unless you specify it as such, your subsequent `cd` would fail. (Thus, your build remains in the same directory, where `fasmg` does not exist.)

I suggest not using a Windows path.

**Comment by double-beep** [comment]
Hello @BanzaiMan 

Could you please take a look to the last build? I did not use `cd`

**Comment by BanzaiMan** [comment]
Which build should I look?

**Comment by double-beep** [comment]
Hope https://travis-ci.com/double-beep/asmFish/builds/84280663#L462 helps!

**Comment by double-beep** [comment]
Hi @BanzaiMan, thanks for your help.
I decided to assemble linux executables to AppVeyor, and MacOS with ARM(v8) to travis.

If you can explain me what's wrong with travis-linux, it would be very much appreciated.

**Comment by BanzaiMan** [comment]
There appears to be something wrong with the file and/or the file name.

I get the error message on a fresh Ubuntu image.

```sh-session
foo@6dc69ba0010a:~$ git clone https://github.com/double-beep/asmFish.git
Cloning into 'asmFish'...
remote: Counting objects: 12493, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 12493 (delta 10), reused 0 (delta 0), pack-reused 12475
Receiving objects: 100% (12493/12493), 99.44 MiB | 5.74 MiB/s, done.
Resolving deltas: 100% (7831/7831), done.
Checking connectivity... done.
foo@6dc69ba0010a:~$ cd asmFish/
foo@6dc69ba0010a:~/asmFish$ git checkout travis
Branch travis set up to track remote branch travis from origin.
Switched to a new branch 'travis'
foo@6dc69ba0010a:~/asmFish$ ./fasmg
-su: ./fasmg: No such file or directory
```

**Comment by BanzaiMan** [comment]
How did you get this file? Does it work anywhere?

**Comment by double-beep** [comment]
In AppVeyor as tested, it is working fine. In my pc it doesn't work.

**Comment by BanzaiMan** [comment]
Let us know if you need additional help. From here, it looks like an issue with your file.
