### ISSUE TITLE
`\r` (aka ^M) produced by travis on posix (it's a windows specific thing)

### ISSUE THREAD

**Issue by timotheecour** [travis-ci/travis-ci#10067]
`curl https://api.travis-ci.org/v3/job/422915784/log.txt | less` shows ^M characters:
which is a `\r` , a windows specific thing, it shouldn't be produced on travis logs (which is processed on posix)

![image](https://user-images.githubusercontent.com/2194784/44941363-c0e4a900-ad50-11e8-83aa-0fb2960e1bb4.png)

(that log came from https://github.com/nim-lang/Nim/issues/8824#issuecomment-417589340)
originally reported here https://github.com/nim-lang/Nim/issues/8828 but looks like a travis bug

**Comment by timotheecour** [comment]
ping

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
