### ISSUE TITLE
how do I access travis logs for a github PR using travis cmd line?

### ISSUE THREAD

**Issue by timotheecour** [travis-ci/travis-ci#10064]
```
brew install travis
cd myrepo
# I'm in a branch that corresponds to a github PR
travis show
# shows info for latest job, not the job that corresponds to my PR

travis open -p
web view: https://travis-ci.org/nim-lang/Nim
# likewise, this shows job for latest merged PR, not job that corresponds to my PR
```

**EDIT**
I found I could do : `travis history --limit 100 | grep 'PR #8795'` 
which shows me:
```
#8736 started:   devel (PR #8795) _
#8707 failed:    devel (PR #8795) _
#8674 failed:    devel (PR #8795) fixup for bootstrap
#8672 failed:    devel (PR #8795) removed workaround with `substr` in stackTraceAux; the corruption does not seem to happen anymore
```
so I guess I could use that and pipe to a shell prog that extracts the 1st build `8736` ... is that the best way?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
