### ISSUE TITLE
Cassandra service not starting on java10

### ISSUE THREAD

**Issue by Ranjansingh41** [travis-ci/travis-ci#10078]
I installed java10 on my machine but i am not able to Cassandra services

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by biancawilk** [comment]
@Ranjansingh41 I'm going to close this issue, please reopen if needed.
