### ISSUE TITLE
Remove repo that was transfered to an other user

### ISSUE THREAD

**Issue by mgrenier** [travis-ci/travis-ci#10073]
How do I remove a repo from my travis-ci account that was transfered to an other user ?

The repo in question is `icetee/remote-ftp`, orginally `mgrenier/remote-ftp`.

**Comment by iriberri** [comment]
Hi @mgrenier - since this is a specific account issue, please send us an email to support@travis-ci.com and we'll be glad to help you with this :)

Thank you!
