### ISSUE TITLE
trying to ouput color code in node-js based console ouput in travis

### ISSUE THREAD

**Issue by asturur** [travis-ci/travis-ci#10074]
Hi,
i'm trying to replicate what i see in my console locally:

<img width="610" alt="screen shot 2018-09-02 at 12 39 26 pm" src="https://user-images.githubusercontent.com/1194048/44955055-3feef400-aead-11e8-9dc0-01f648cd44c7.png">

In travis output, but all i see is this:

<img width="812" alt="screen shot 2018-09-02 at 12 40 27 pm" src="https://user-images.githubusercontent.com/1194048/44955064-6876ee00-aead-11e8-84db-9777057fefbf.png">

https://travis-ci.org/fabricjs/fabric.js/jobs/423572545

I wan wondering if this is not possible at all, or if i just picked up the wrong color codes.

I m using this library for the color code:
https://github.com/jbnicolai/ansi-256-colors

Can someone help?

**Comment by BanzaiMan** [comment]
I believe this is a variant of #9500.
