### ISSUE TITLE
Ability to mark an build as "unstable" (have a more sophisticated configuration available how to deal with failures in a staged build)

### ISSUE THREAD

**Issue by TheSnoozer** [travis-ci/travis-ci#10075]
In my build scripts I heavily rely on [build stages](https://docs.travis-ci.com/user/build-stages/) and I think its a really great feature.
For simplicity assume we have two build stages `test` and `deploy`(similar to the [`How to define Build Stages` example](https://docs.travis-ci.com/user/build-stages/#how-to-define-build-stages)). In some cases it might be helpful to say we don't want to have the entire build marked as `failed` if for example the `deploy` stage failed. In such a case the build rather should be marked as `unstable`.

In other words I think it would be helpful to have a more sophisticated configuration available how to deal with failures in a staged build. This would also include if any follow up executed if an error happened.

Possibilities:
- fail and stop (don't run any follow up stages and mark the build as failed)
- fail and continue (run any follow up stages and mark the build as failed)
- unstable and stop (don't run any follow up stages and mark the build as unstable)
- unstable and continue (run any follow up stages and mark the build as unstable)
- ignore (run any follow up stages and mark the build as success)

Opinions?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
