### ISSUE TITLE
R: --no-manual is repeating many times

### ISSUE THREAD

**Issue by schloerke** [travis-ci/travis-ci#10089]
@jeroen and @jimhester

Low priority as things are working, but it is odd behavior.

Execution: https://travis-ci.org/rstudio/sassr/jobs/425308894#L1106
Line:
```
R CMD check "${PKG_TARBALL}" --as-cran --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual; CHECK_RET=$?
```

Again... it works, just odd.

\-Barret

**Comment by jimhester** [comment]
Yeah I agree it is strange, even weirder is the only place we add it is at 

https://github.com/travis-ci/travis-build/blob/3af56667b3221448763e79a73007b94a38bb9612/lib/travis/build/script/r.rb#L168

And that code should not even be running for your builds, as the default value of `latex` is `true`.

**Comment by jimhester** [comment]
I think the use of `>>` to append and replace was the root of the issue, I sent https://github.com/travis-ci/travis-build/pull/1478 to just use a normal assignment.
