### ISSUE TITLE
Polyglot maven build files are not automatically detected

### ISSUE THREAD

**Issue by headius** [travis-ci/travis-ci#10084]
[Polyglot Maven](https://github.com/takari/polyglot-maven) allows writing Maven pom files in a variety of other languages. Unfortunately, these other pom file formats do not trigger auto-detection of a maven build.

As an example, here's a build of one of my projects. After converting my poms to YAML and removing build.xml, Travis continues to try to build with ant: https://travis-ci.org/jruby/jcodings/builds/425117704

I was able to fix this by specifying a custom script step, but I believe Travis should be able to detect these other pom file formats (or the presence of the [.mvn configuration directory and/or the extensions.xml](https://github.com/jruby/jcodings/tree/java9/.mvn)): https://travis-ci.org/jruby/jcodings/builds/425119616

At the very least, it shouldn't try to run ant when there's obviously no build.xml present. Maven is still the most widely used build tool for Java projects.

**Comment by BanzaiMan** [comment]
The logic for choosing what commands to run for `language: java` is this: 

https://github.com/travis-ci/travis-build/blob/dc1da76419ef473e6162e83c3808b69e953679c0/lib/travis/build/script/shared/jvm.rb#L38-L54

```ruby
        def script
          sh.if '-f gradlew' do
            sh.cmd './gradlew check'
          end
          sh.elif '-f build.gradle' do
            sh.cmd 'gradle check'
          end
          sh.elif '-f mvnw' do
            sh.cmd './mvnw test -B'
          end
          sh.elif '-f pom.xml' do
            sh.cmd 'mvn test -B'
          end
          sh.else do
            sh.cmd 'ant test'
          end
        end
```

Is the use of the `.mvn` directory a recent convention?

**Comment by headius** [comment]
The .mvn dir has been around for some time, to do per-project settings. The polyglot stuff is many years old and builds off the .mvn extensions config.

**Comment by BanzaiMan** [comment]
@headius What are good mvn project layouts we should watch out for?

Just `.mvn` and (or?) `pom.yml`?

**Comment by headius** [comment]
Well .mvn indicates that it's maven and there's potentially plugins configured, which then opens up .yml and friends. I wouldn't say you should try to look for all possible pom extensions, since more have been added to the polyglot support over time, but .mvn is a pretty strong indicator that it's a Maven project.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
