### ISSUE TITLE
Hold for approval 

### ISSUE THREAD

**Issue by W3Meyrick** [travis-ci/travis-ci#10085]
Hi, 

I'm looking to use Travis to deploy Terraform and have come up against a challenge that I'd like some guidance to solve please :) 

I have jobs to achieve the following: 
1. terraform fmt (and some other lint tests) 
2. terraform plan 
3. terraform apply 

Is there a way of requiring a hold between 2 and 3 that requires a manual approval or, even better, a hold that waits on the pull request review? 

CircleCI have a feature detailed here which helps describe what I'm looking for: [https://circleci.com/docs/2.0/workflows/]

```
type: approval
requires:
- plan
```

Thanks,
Luke

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
