### ISSUE TITLE
Travis build successful but github pages build fails

### ISSUE THREAD

**Issue by FlorianWanders** [travis-ci/travis-ci#10082]
I am new to Travis so this might not be the right place to ask, but after having spent several hours searching stackoverflow and issues by others I decided to post. I want to use Travis to be able to use [jekyll-scholar](https://github.com/inukshuk/jekyll-scholar) on a personal github page. 

My Travis build succeeds: 

![travis](https://user-images.githubusercontent.com/11775327/45063664-595f8e00-b0af-11e8-8717-12a807b31981.PNG)

But github takes issue with it, even though I included a .nojekyll file in `./script/cibuild` : 

![checkfail](https://user-images.githubusercontent.com/11775327/45063705-9af03900-b0af-11e8-9e90-24f6e23b9495.PNG)

The error seems to come from a { % cite % } tag from [jekyll-scholar](https://github.com/inukshuk/jekyll-scholar), but should not cause any problems due to the `.nojekyll` file included in the `_site` folder. Indeed, when I check on github, I see properly rendered html tags in the [source code](https://github.com/FlorianWanders/florianwanders.github.io/blob/gh-pages/2018/08/01/SICSS.html). 

The repository in question is https://github.com/FlorianWanders/florianwanders.github.io. My `./script/cibuild` contains: 

	#!/usr/bin/env bash
	set -o pipefail && xcodebuild [flags] | xcpretty # halt script on error

	bundle exec jekyll build
	touch ./_site/.nojekyll # this file tells gh-pages that there is no need to build

And my `.travis.yml` contains: 

	language: ruby
	rvm:
	- 2.3.6

	before_script:
	 - chmod +x ./script/cibuild # or do this locally and commit

	# Assume bundler is being used, therefore
	# the `install` step will run `bundle install` by default.
	script: ./script/cibuild

	# branch whitelist, only for GitHub Pages
	branches:
	  only:
	  - master

	env:
	  global:
	  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

	sudo: false # route your build to the container-based infrastructure for a faster build

	cache: bundler

	deploy:
	  provider: pages
	  skip_cleanup: true
	  keep-history: true
	  local_dir: _site/  # deploy this directory containing final build
	  github_token: $secret # Set in travis-ci.org dashboard
	  on:
		branch: master

	notifications:
	  email: false

**Comment by BanzaiMan** [comment]
Hello, there.

 Am I correct to understand that the status you are concerned with comes from `jekyll-scholar`?

As far as I can see, your build is configured correctly and we run the build accordingly. The `jekyll-scholar`'s check is alien to Travis CI, so it is quite difficult to give you any more advice than "Please consult the tool's documentation".

**Comment by FlorianWanders** [comment]
Hi and thanks for your quick reply! You are right, the error comes from `jekyll-scholar`. 

Might I ask you for some help in understanding Travis CI better? I thought that when using Travis CI and including a `.nojekyll` file in the `_site` folder, this would render the locally-built html files in the `_site` folder, thereby bypassing github's limitation on external plugins compared to when only using github pages. I guess I mixed up something here? Or, perhaps I should ask: is this something I can use Travis for?
