### ISSUE TITLE
Multiple maven run at once freezes

### ISSUE THREAD

**Issue by VratislavHais** [travis-ci/travis-ci#10083]
Hello,

since your update travis has a problem with running `nohup mvn exec:exec > /dev/null 2> /dev/null &` multiple times. If I run it just once it'll pass. This was not a problem before and even in your docker image (node_js | travisci/ci-garnet:packer-1512502276-986baf0) everything works as it should. All the dependencies for maven are successfully installed before running this command.

[failed job](https://travis-ci.org/VratislavHais/infispector/jobs/424641644)
[last successful job](https://travis-ci.org/VratislavHais/infispector/builds/312932402) (yeah, it have been a while)
[project](https://github.com/VratislavHais/infispector)

btw the maven command should create a dummy infinispan node (in this case four times) and connect it with another active infinispan node.

If you require some more specific information I'll do my best to provide them. 

Thank you in advance.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
