### ISSUE TITLE
Travis is unable to download snapshot artifacts from Sonatype

### ISSUE THREAD

**Issue by headius** [travis-ci/travis-ci#10086]
There appears to be a problem with the certificate chain for Sonatype artifacts when downloaded from Travis.

Here is an example build that attempts to use snapshots (which work properly on my local system with a standard OpenJDK 9 build): https://travis-ci.org/jruby/bytelist/builds/425119540

The ultimate error is `sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`.

These snapshot repositories are used by thousands of open source projects, so I suspect the problem exists on the client (Travis) end.

**Comment by headius** [comment]
This may be due to OpenJDK9 not having the proper cacerts! On another build (jruby) I switched from openjdk9 back to oraclejdk9.

But I think openjdk9 should work!

**Comment by denis-yuen** [comment]
Agreed, but for now I noticed (and used) the workaround from https://www.deps.co/guides/travis-ci-latest-java/

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
