### ISSUE TITLE
Make adding CruiseControl feeds easier

### ISSUE THREAD

**Issue by felixfbecker** [travis-ci/travis-ci#10091]
The CCMenu integration is a true productivity booster.
However, adding each repository you care about manually is cumbersome and involves a lot of copy+pasting.

The CC protocol has support for having multiple projects in a single feed afaik. Would it be possible to expose a single feed for a user and org with all repositories as projects? So only one feed would need to be added.

CCMenu also supports adding projects with a custom link handler by simply prefixing the feed URL with `ccmenu+`, like ccmenu+https://api.travis-ci.org/repositories/erikdoe/ccmenu/cc.xml. Could Travis embed a button for repos?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
