### ISSUE TITLE
Option to skip push build if there is a matching pull request build

### ISSUE THREAD

**Issue by lbergelson** [travis-ci/travis-ci#10093]
We would like to be able to skip push builds if there is an associated PR build, while still doing push builds on branches that have not yet been pull requested.  Each of our builds takes a lot of resources, and since we ultimately only care that the merged branch passes, we don't want to waste time and bandwidth on builds that are essentially redundant.  We don't want to disable push builds entirely since they're vary useful for testing branches before they're ready to be pull requested.  

We're currently putting together a hackey solution that queries the github api to and then aborts the build quickly if there is a matching PR.  This isn't ideal though because it still spends a minute or two of vm time spinning up each node before it can do the check. It's also may cause some confusion because it will always report success for the push builds even though they're really a deliberate skip.

**Comment by DrTorte** [comment]
Hey there,

Thanks again for this suggestion. As mentioned in https://github.com/travis-ci/travis-ci/issues/10094 just now, I'd suggest posting this over at https://travis-ci.community for our product team to take a look. 😄
