### ISSUE TITLE
Unable to login with Github

### ISSUE THREAD

**Issue by Towerism** [travis-ci/travis-ci#10099]
On travis-ci.org, Clicking Sign In with GitHub goes through OAuth but I get kicked back to sign in screen with no error message. I tried revoking OAuth and re-authorizing but no dice. I can log in just fine on travis-ci.com

**Comment by DrTorte** [comment]
Thanks for letting us know. We're seeing this to and are investigating. Thanks!

**Comment by DrTorte** [comment]
Hey everyone, 

Looks like we've got it resolved. If you run into it again, please let us know over at support@travis-ci.com. Thanks!
