### ISSUE TITLE
fetching raw log doesn't support http range

### ISSUE THREAD

**Issue by brianjmurrell** [travis-ci/travis-ci#10095]
If I try to fetch a raw log from, say, https://api.travis-ci.org/v3/job/425871856/log.txt with a `Range: ` HTTP header, the range requested is ignored.

It would be most useful to support the `Range: ` header so that one didn't have to fetch the whole log every time if one has already fetched it previously.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by brianjmurrell** [comment]
Are bug reports no longer being accepted in GitHub issues?

You will NOT get me having to put up with the Internet's worst tool -- forums -- to report bugs.
