### ISSUE TITLE
Non-descriptive error in filter.rb

### ISSUE THREAD

**Issue by tathougies** [travis-ci/travis-ci#10097]
I've been trying to run a build of beam-postgres [here](https://travis-ci.org/tathougies/beam/jobs/425831389), but it continues to fail with an error in `filter.rb`. This file is not part of my code, which makes me think it's something to do with Travis.

Any pointers? I've tried googling, but have been unable to find any other user with similar issues.

**Comment by cotsog** [comment]
@tathougies Could you try to run your builds on the sudo-enabled infrastructure to see if it helps? Here's what you need to add to your .travis.yml file:

```yaml
sudo: required
```

**Comment by tathougies** [comment]
I did just that, but I get the same error:

https://travis-ci.org/tathougies/beam/jobs/426865224

**Comment by cotsog** [comment]
Could you try to add the following to your .travis.yml file:

```yaml
filter_secrets: false
```

This is only meant to be a test so you can remove it from your configuration right after the build is done i.e. to continue using our secret filtering feature.

**Comment by tathougies** [comment]
still fails: https://travis-ci.org/tathougies/beam/jobs/427836777

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
