### ISSUE TITLE
Ability to customize travis status messages

### ISSUE THREAD

**Issue by lbergelson** [travis-ci/travis-ci#10094]
We'd like to be able to customize the status message that is returned from a build.  It would be extremely useful to be able to include additional information in the message, like test failure counts, or links to artifacts we uploaded somewhere.   

We can do something like this with the github api ourselves, but it requires that we expose a github token to the build which is awkward and prevents us from using it on builds from forks.  A built in command available that doesn't require us to expose a token would be useful.  

I imagine it could be something like:
```
after_failure:
- set_custom_status "There were ${failures} test failures, please see the test log at ${log_location}"
```

(We have similar issues with the need to provide keys to upload artifacts as well...  A built in to host build artifacts and reports would be really useful)

**Comment by DrTorte** [comment]
Hey there,

Thanks for suggesting this! For any feature requests or product feedback, I'd suggest you head on over to the [Travis CI Community Forum](https://travis-ci.community). Our Product team is currently watching there rather actively.

Thanks and all the best!

**Comment by lbergelson** [comment]
Ah, thanks, didn't realize this was the wrong place to post.
