### ISSUE TITLE
Travi CI web page loads CPU 100%

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#10096]
When I have http://travis-ci.org tab active in Firefox one of my CPU cores is constantly fully loaded (100%).

If I switch to some another tab CPU load drops to ~0%.

Expected result: when TraviCI web site tab is active in Firefox CPU should not be 100% loaded.

My OS is Debian 9 (Stretch).

**Comment by igagis** [comment]
This seems to happen only when there are active builds, i.e. there are some "spinners" animation on the page

**Comment by BanzaiMan** [comment]
Hello, there. Thanks for opening this issue. I'm closing this as a duplicate of https://github.com/travis-ci/travis-ci/issues/9276.
