### ISSUE TITLE
Cannot activate new repo

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#10101]
When I try to activate https://travis-ci.org/HaxeFoundation/crypto, it says `Oh no!
There was an error while trying to activate the repository.`.

From the console, I can see an error as follows:
```
POST https://api.travis-ci.org/repo/20978017/activate 500 (Internal Server Error)
```

**Comment by andyli** [comment]
Somehow it works now.

**Comment by dasabhisek** [comment]
I am getting HTTP 404 error with below response message

> {"file":"not found"}*

While fetching the repo details using the api, it fetch the details successfully.
