### ISSUE TITLE
Not able to login to Travis CI for some reason.

### ISSUE THREAD

**Issue by arnavb** [travis-ci/travis-ci#10100]
I'm trying to log into Travis CI, but it isn't working. Here's what I'm doing.

1. Navigating to https://travis-ci.org/.
2. Clicking the "Sign in with Github" button in the top right corner.

However, when I click this button, I get redirected to a URL that looks like:

https://api.travis-ci.org/auth/handshake?code={SOME CODE I ASSUME IS AN ACCESS TOKEN}&state={SOME WEIRD GIBBERISH}https%3A%2F%2Ftravis-ci.org%2F

After this, I am redirected back to the original page without any sign-in.

**Comment by alechp** [comment]
I was having this issue as well. The issue tracker showed this was solve 20:11UCT but noticed I wasn't able to login until 20:45UCT

**Comment by arnavb** [comment]
> The issue tracker showed this was solve

Where?

**Comment by alechp** [comment]
@arnavb https://www.traviscistatus.com/

<img width="355" alt="screen shot 2018-09-10 at 2 11 51 pm" src="https://user-images.githubusercontent.com/3058939/45324629-88d52700-b503-11e8-8f99-1db73573e806.png">

**Comment by arnavb** [comment]
Hmmm, this problem is still not resolved for me, however.

**Comment by DrTorte** [comment]
Hey all,

This has indeed reappeared. We're watching and investigating and will let you know soon as we have updates.

**Comment by DrTorte** [comment]
Hey everyone,

We're working through this and you should be able to login again and sync should be working once more. I'll leave this issue open if anything else pops up!

**Comment by edmorley** [comment]
Hi! GitHub pull request status still aren't updating (eg https://github.com/neutrinojs/neutrino/pull/1087). Is this expected?

**Comment by DrTorte** [comment]
@edmorley Yeah, there's still work to be done and quite a queue to work through. We'll keep you all posted. :)

**Comment by DrTorte** [comment]
Looks like it's been solved, but we're still keeping an eye on it.

**Comment by edmorley** [comment]
The PR status have now all updated - many thanks!

**Comment by arnavb** [comment]
Ok, thanks Travis team! Now that this issue is solved, I will close it.

**Comment by talron10** [comment]
Happening now too, same issue?

**Comment by b3by** [comment]
Expired access token?

**Comment by talron10** [comment]
yeah

**Comment by talron10** [comment]
just checked, its working now :)

Don’t know if it was your magic, but thanks!

**Comment by ntambellini13** [comment]
happening now as well
