### ISSUE TITLE
apt-get issue during Docker build

### ISSUE THREAD

**Issue by liddellj** [travis-ci/travis-ci#10104]
We are seeing an issue issuing an `apt-get update` command during a Docker build that I am unable to reproduce locally. Here is the first half of our Dockerfile:
```
FROM nvidia/cuda:7.5-devel

RUN apt-get update
RUN apt-get install apt-transport-https -y
RUN sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
RUN apt-get update
RUN apt-get install dotnet-sdk-2.0.0 -y
```

The issue occurs on the third line, `RUN apt-get update`. The error is:
```
W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

I'm not sure if this is a Travis issue or an NVIDIA issue, so I have cross-posted here: https://github.com/NVIDIA/nvidia-docker/issues/813

**Comment by cotsog** [comment]
@liddellj Thanks for the report and we are sorry for the troubles.

Do you have a link to a failing build containing this error? If it's private, please send it over to support [at] travis-ci [dot] com.

Also, can you reproduce the issue **outside** your Docker container?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
