### ISSUE TITLE
PostgreSQL server terminated abnormally during the test

### ISSUE THREAD

**Issue by y-yagi** [travis-ci/travis-ci#10107]
Recently, PostgreSQL server abnormally terminated during test execution of rails/rails repository. 

https://travis-ci.org/rails/rails/jobs/427502723#L2940-L2942 
https://travis-ci.org/rails/rails/jobs/427496382#L2921-L2923 
https://travis-ci.org/rails/rails/jobs/427470858#L2921-L2923 
https://travis-ci.org/rails/rails/jobs/427451232#L2921-L2923 

If such an error occurs, what is considered to be the cause? 
Is it possible to see the log of PostgreSQL server? 

In addition, we recently changed the setting to use MySQL 5.7 on Travis CI, and this error occurs.
https://github.com/rails/rails/pull/33608/commits/cd8be30d74c9a0352b2f31a9628027bda4447c09

**Comment by BanzaiMan** [comment]
Hmm. One obvious possibility is running out of memory, but without the logs it is hard to say. Seeing that your build is running with `sudo`, adding the following might give you some insight:

```yaml
after_failure:
  - sudo cat /var/log/postgresql/postgresql-*-main.log
```

**Comment by y-yagi** [comment]
It was because the `ramfs` was full. 
https://travis-ci.org/rails/rails/jobs/427960998#L7614 

Since it seems that this problem does not occur if it is container-based infrastructure, I will adjust it to be container-based or extend `ramfs` to deal with it. Thank you!
