### ISSUE TITLE
npmERR! Cannot find module '../pack.js' only on Node 6

### ISSUE THREAD

**Issue by LeonardoGentile** [travis-ci/travis-ci#10106]
Hello,
my build is failing only on Node 6 but it works correctly on node 8, See here: https://travis-ci.org/LeonardoGentile/mobx-router5/builds/425988734

Log
```
npmWARNprepare removing existing node_modules/ before installation
npmERR!code MODULE_NOT_FOUND
npmERR! Cannot find module '../pack.js'
npmERR! A complete log of this run can be found in:
npmERR!     /home/travis/.npm/_logs/2018-09-08T02_10_00_295Z-debug.log
The command "eval npm ci  " failed. Retrying, 2 of 3.
/home/travis/.travis/job_stages: line 266: ./node_modules/.bin/npm: No such file or directory
The command "eval npm ci  " failed. Retrying, 3 of 3.
/home/travis/.travis/job_stages: line 266: ./node_modules/.bin/npm: No such file or directory
The command "eval npm ci  " failed 3 times.
The command "npm ci " failed and exited with 127 during .

```

What is weird is that I can fix this problem by going to: "More Options / Cache " then "Delete all repository caches".

To me this is seems a Travis problem, not a build misconfiguration, unless I'm missing something.

Thanks 👋

**Comment by BanzaiMan** [comment]
If the build problem disappears if the cache is not present, then the cache is configured wrong. You are caching `node_modules`, but I reckon that, when your build succeeds and uploads the cache, it does not contain `node_modules/.bin/npm` that `npm ci` requires. I don't know enough about the `npm ci` to guess why this happens, though.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
