### ISSUE TITLE
maven timeout repository.apache.org snapshot and releases

### ISSUE THREAD

**Issue by ham1** [travis-ci/travis-ci#10108]
We often get the following timeout on our maven builds, this had never happened locally but happens about 50% of the time on Travis.

E.g. https://travis-ci.org/Frameworkium/frameworkium-core/builds/427598283

First noticed on the 6th September https://travis-ci.org/Frameworkium/frameworkium-core/builds/425253801
```
[INFO] Downloading from sonatype: https://oss.sonatype.org/content/repositories/releases/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
[INFO] Downloading from sonatype-apache: https://repository.apache.org/releases/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
[INFO] Downloaded from sonatype: https://oss.sonatype.org/content/repositories/releases/org/seleniumhq/selenium/selenium-java/maven-metadata.xml (3.4 kB at 4.3 kB/s)
[WARNING] Could not transfer metadata org.seleniumhq.selenium:selenium-java/maven-metadata.xml from/to sonatype-apache (https://repository.apache.org/releases/): Connect to repository.apache.org:443 [repository.apache.org/207.244.88.140] failed: Connection timed out (Connection timed out)
[WARNING] Could not transfer metadata org.seleniumhq.selenium:selenium-java/maven-metadata.xml from/to apache-snapshots (https://repository.apache.org/snapshots/): Connect to repository.apache.org:443 [repository.apache.org/207.244.88.140] failed: Connection timed out (Connection timed out)
```

**Comment by ham1** [comment]
Is there anything I can do to help debug this? It doesn't seem to be an Apache issue as their status page says things are ok.

**Comment by ham1** [comment]
It happened once today locally after I removed my `~/.m2` directory and downloaded everything again; towards the end it timed out, only after I changed my IP address did it work again.
Maybe maven central have increased the aggressiveness of their blocking? Is anyone else seeing this with maven projects on travis?

**Comment by Nadahar** [comment]
We're having the exact same issue.

**Comment by stefanocke** [comment]
Same issue for my build. I had success with:
`script: "mvn clean install -P !standard-with-extra-repos"`

This switches off any "extra-repos" besides central, including apache-snapshots and apache-releases.

**Comment by Naramsim** [comment]
We have it too.

Since we download a lot of artifact, the build gets really slow.

```
[WARNING] repository metadata for: 'artifact org.antlr:antlr4-runtime' could not be retrieved from repository: sonatype-apache due to an error: Connect to repository.apache.org:443 [repository.apache.org/207.244.88.140] failed: Connection timed out (Connection timed out)
```

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
