### ISSUE TITLE
GitHub Releases Uploading broken

### ISSUE THREAD

**Issue by lorenzo** [travis-ci/travis-ci#10109]
Hey I have tried several combinations for enabling travis to do Github releases in my repo. This is the history of jobs where I have tried different options:

https://travis-ci.org/seatgeek/docker-build-cacher/builds

Things I have tried so far:

1. 
```
travis setup releases
```

2.
```
travis setup releases --pro
```
3. 
Manually creating a GitHub token and adding it to the `api_key` using an env var.

4.
Repeating the above 3 times

What am I missing?

**Comment by BanzaiMan** [comment]
Hello, there. Sorry to hear about your troubles.

The methods 1 and 3 should work (not 2, because you are running on .org, and `--pro` would point to a wrong API endpoint). Perhaps try giving more explicit commands:

```
travis encrypt --org -r seatgeek/docker-build-cacher
```

And provide your token on STDIN, followed by CTRL-D.

**Comment by lorenzo** [comment]
thanks, I'll try that

**Comment by lorenzo** [comment]
@BanzaiMan I did not work: https://travis-ci.org/seatgeek/docker-build-cacher/jobs/427670236

I created a token in GitHub with no extra special permissions, copied the token and did:

```sh
echo [my_token] | travis encrypt --org -r seatgeek/docker-build-cacher
```

Then pasted it here: https://github.com/seatgeek/docker-build-cacher/blob/master/.travis.yml#L69

But it did not have a different outcome to what I've done so far

**Comment by BanzaiMan** [comment]
What scope does this token have? As explained in https://docs.travis-ci.com/user/deployment/releases#authenticating-with-an-oauth-token, it needs `public_repo` or `repo`.

**Comment by lorenzo** [comment]
I ran it again to make sure. Created another token with repo permissions. Still the same result.

**Comment by BanzaiMan** [comment]
[This key](https://github.com/seatgeek/docker-build-cacher/blob/7e846441de4680114f631141d4ccc68c04ea2298/.travis.yml#L22) does not seem encrypted correctly with your seatgeek/docker-build-cacher repo on .org.

**Comment by lorenzo** [comment]
Ok, that maybe explains things. I did not write it like that, but was how the setup tool did it for me. I’ll remove that and try again. Thanks for your patience!

**Comment by lorenzo** [comment]
That was the problem. Do you need any information from me in how this happened? Not sure you want to make the Travis CLI do anything different in these cases

**Comment by BanzaiMan** [comment]
Ah, I understand now. The CLI tool, with `travis encrypt`, is writing the deployment configuration at the [top level](https://github.com/seatgeek/docker-build-cacher/blob/7e846441de4680114f631141d4ccc68c04ea2298/.travis.yml#L64-L72), but you are overriding this configuration in [`matrix.include`](https://github.com/seatgeek/docker-build-cacher/blob/7e846441de4680114f631141d4ccc68c04ea2298/.travis.yml#L19-L28).

This should be explained more clearly.

**Comment by lorenzo** [comment]
yeah, I think the CLI should have warned me that I had declared the already and this would conflict.

**Comment by DrTorte** [comment]
Hey there @lorenzo, seems like you got all this all working so I'll go ahead and close this issue. If I'm mistaken, please let us know and we'll reopen it. Thanks! :)

**Comment by lorenzo** [comment]
I did, but I think n the cli tool is still doing the wrong thing sometimes. Up to you if you want to consider this not a problem :)

**Comment by DrTorte** [comment]
It's something I'm noting down for CLI improvement for sure. :)
