### ISSUE TITLE
distribution of xenial with sudo:false silently ignored and trusty used instead.

### ISSUE THREAD

**Issue by cjw296** [travis-ci/travis-ci#10110]
Here's the config: https://travis-ci.org/Simplistix/testfixtures/jobs/427676308/config

Here's the job log: https://travis-ci.org/Simplistix/testfixtures/jobs/427676308

It's frustrating that a container-compatible build of Xenial still isn't available.
It's more frustrating that asking for it is silently ignored and Trusty is used instead.

There are a *lot* of open source projects looking to test against Python 3, and until both parts of this are resolved, they have to use `sudo: false` and put way more load on your infrastructure than they want to.

Any ETA on a fix?!

**Comment by BanzaiMan** [comment]
Please specify `sudo: required` for the time being.

**Comment by cjw296** [comment]
@BanzaiMan - the drive to support Windows is cute, but that's not your core market. Maybe get the team to have a look at a scalable way to allow the bulk of your users to test on a current version of the Linux distribution you've chose?

**Comment by BanzaiMan** [comment]
@cjw296 Thanks for the feedback. Indeed, we will be moving away from `sudo: false` in the near future, as maintaining two separate sets of build images is impractical and we are concentrating our efforts on getting the GCE image stable. You can find more information about this in our blog: https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures.

**Comment by cjw296** [comment]
Then let's just close this bug as "won't fix", Travis has previously intoned that `sudo: false` was the preferred way forward given the lower resources required and lower latency to spin up the instance.
