### ISSUE TITLE
No command ' mvn' found

### ISSUE THREAD

**Issue by chupman** [travis-ci/travis-ci#10111]
Our builds started failing to locate maven today. I reran builds on old commits that were passing previously and they now fail due to being unable to locate maven.
```
No command ' mvn' found, did you mean:
 Command 'mvn' from package 'maven2' (universe)
 Command 'mvn' from package 'maven' (universe)
 mvn: command not found
```

Here's the first occurance of mvn not found in the [failed build](https://travis-ci.org/JanusGraph/janusgraph/jobs/427773772#L477)

After a little bit of digging, The only difference I could find between the passing build and the failing one was the addition of the line below, but I can't think of a reason the associated operation would cause this error
```
Setting APT mirror in /etc/apt/sources.list: http://us-central1.gce.archive.ubuntu.com/ubuntu/
```

Also, I wasn't able to find a solution in it, but my issue seems similar to #8900

**Comment by BanzaiMan** [comment]
Notice that the command that is noted is " mvn", not "mvn". There appears to be a argument processing problem somewhere.

I also note that you are nesting two bash functions `travis_retry` and `travis_wait`. I don't know if these two will work together, especially with a long argument list like yours.

**Comment by chupman** [comment]
I actually didn't catch the space. I'll try to troubleshoot some more and try to reproduce with a fresh project. 

I really appreciate the help and the great platform you guys provide. I hope Florence doesn't cause you too much trouble.

**Comment by chupman** [comment]
Looks like something must have changed with the way whitespace is cleaned/backslashes are processed for multiline. 
I just have to make sure that that there are backslash newlines before the initial commands after travis_retry or travis_wait.

Updating:
```
travis_retry travis_wait \
          mvn install --projects janusgraph-${MODULE} --also-make \
          -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version ${INSTALL_ARGS};
```
To:
```
travis_retry travis_wait mvn install --projects janusgraph-${MODULE} --also-make \
          -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version ${INSTALL_ARGS};
```
Resolved the issue. Thanks again for the help troubleshooting and identifying the problem.
