### ISSUE TITLE
Travis CI Unable to Find executable_path for chrome webdriver using Python

### ISSUE THREAD

**Issue by danielkim107** [travis-ci/travis-ci#10118]
Hi, I just started using Travis-CI, and I have two issues that I'm facing on Travis-CI.

1. I'm currently working on building tests through Selenium using Chromedriver, but whenever I try testing them on Travis CI, it doesn't work. Here's my info regarding my `.travis.yml` and my `test.py` files:

`test.py`

from selenium.webdriver.chrome.webdriver import WebDriver
...
self.webdriver = Webdriver(executable_path=os.path.abspath('chromedriver'))

`.travis.yml`

dist: trusty

sudo: required

language: python

services:
  - mysql
  - redis-server

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - sudo apt-get install -y gdal-bin python-gdal

cache: pip

python:
  - '3.6.2'

install:
  - pip install codecov
  - pip install -r requirements-dev.txt
  - wget http://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.2/bin/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

before_script:
  - flake8
  - pycodestyle --config=setup.cfg

script:
  - coverage run --source=. manage.py test --settings=main.settings_test -v 3 --noinput

I keep getting this error:
`OSError: [Errno 8] Exec format error`

I can alternatively make the Webdriver's executable_path to be `/home/travis/virtualenv/python3.6.2/bin/chromedriver` and it works, but for testing purposes locally and on Travis-CI, I want to use the `os.path.abspath` method.

2. If I do use the brute forcing method of simply using the actual filepath and run the test, my tests seems to be not finding any elements on the website (http://localhost:8000/login) for my server. It works perfectly on the local server. Being new to using Travis-CI, do I have to add something to my `settings_test.py` or `.travis.yml` to make it work? I tried printing the current_url after entering the localhost's login page, and it seems to enter the page, but it's not finding any elements.

Thank you for the help in advance.

**Comment by danielkim107** [comment]
And this is the error I'm getting for #2

`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"name","selector":"username"}
  (Session info: chrome=69.0.3497.92)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.4.0-101-generic x86_64)`

**Comment by BanzaiMan** [comment]
Sorry to hear about the problems you're having. Could you reformat the description above, so that it is easier to read (e.g., use YAML formatting for YAML file)?

Also, when reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by danielkim107** [comment]
Sounds good!
