### ISSUE TITLE
Get status of deployment step

### ISSUE THREAD

**Issue by kanekotic** [travis-ci/travis-ci#10119]
I have a few open source packages that I have automated deployments on branches, and i need to know if deployment actually went through or not. I understand is stated on the documentation that `deploy` and `after_deploy` does not cause the build to fail (not sure why but that is already on other issues).
Due to this, I am trying to get a workaround and need to get somehow the exit code of the `deploy` step. Is this possible? if so how can I do it?

PS.
I have tried without luck the next option
```
after_deploy:
  - if [[ $? != 0 ]]; then travis_terminate 1; fi
```

I have done some debug builds echoing `$?` is always `1` independently if it has been deployed correctly or not ([expected pass build](https://travis-ci.org/kanekotic/dynamo-cli/builds/428929604) and [expected fail build](https://travis-ci.org/kanekotic/dynamo-cli/builds/428930041)). It would be good status codes reflect the reality of other steps, or if they pass be compliant with bash [convention](http://www.tldp.org/LDP/abs/html/exit-status.html)

**Comment by kanekotic** [comment]
I have tried without luck the next option
```
after_deploy:
  - if [[ $? != 0 ]]; then travis_terminate 1; fi
```

I have done some debug builds echoing `$?` is always `1` independently if it has been deployed correctly or not ([expected pass build](https://travis-ci.org/kanekotic/dynamo-cli/builds/428929604) and [expected fail build](https://travis-ci.org/kanekotic/dynamo-cli/builds/428930041)). It would be good status codes reflect the reality of other steps, or if they pass be compliant with bash [convention](http://www.tldp.org/LDP/abs/html/exit-status.html)

**Comment by kanekotic** [comment]
any ideas?

**Comment by BanzaiMan** [comment]
The short answer is that `$?` does not reflect the exit status of the deployment, and you are checking the status of something else. It is unclear to me what that something is, but that is the gist of this problem.

This should be more generally addressed by https://github.com/travis-ci/travis-ci/issues/1574.

**Comment by medikoo** [comment]
It's very valid request.

How can we learn whether deploy failed or not in `after_deploy` script?

Is there any bulletproof way?
