### ISSUE TITLE
How do I build Pascal programs?

### ISSUE THREAD

**Issue by 0x4B776F6B4353** [travis-ci/travis-ci#10120]
I've found this apt
[Launchpad](https://launchpad.net/ubuntu/+source/fpc)
Which provides buildtools for Pascal.
Can I use it in Travis?

**Comment by DrTorte** [comment]
Hey there,

There's nothing officially supported, but if you do a custom install step and write out the script for testing, there's nothing actively stopping it from working. I don't have any easy-to-test Pascal projects on hand to try against, though.

When setting up the .yml, you can also set language to `minimal` or `generic`.
