### ISSUE TITLE
How do I add notifications for only my cron build?

### ISSUE THREAD

**Issue by taylorjacklespriggs** [travis-ci/travis-ci#10129]
Is there a way to enable notifications conditional on the build type being cron? I only want notifications on my daily build.

**Comment by BanzaiMan** [comment]
At the moment, notifications are not build-type-aware, meaning all builds will fire notifications.

One thing you can try is to receive a webhook (https://docs.travis-ci.com/user/notifications#configuring-webhook-notifications) and act on it (and fire further notifications) based on the build type.

**Comment by taylorjacklespriggs** [comment]
Thank you @BanzaiMan , I suspected that I might have to implement a webhook to get this working.
FYI @pfhayes
