### ISSUE TITLE
Build doesn't start when committing to github, no request in "request" view

### ISSUE THREAD

**Issue by sebastianhaberey** [travis-ci/travis-ci#10122]
First off, I just realized you guys live a couple streets down the block from my home 😄  Thanks for providing Travis, I really like it so far!

The only thing is: when I commit to [my git repository](https://github.com/sebastianhaberey/ctax) the builds don't start. There is no corresponding request in Travis' request view. I can start them manually via "Trigger Build" and everything is fine. 

I might have screwed up because in the middle of the initial setup I somehow ended up on travis-ci.com without realizing it and clicked my way through the registering process again. Only then I realized I had two accounts now, and the repositories were transferred to the .com - account. I tried to revert that as good as possible, not sure I succeeded.

**Comment by BanzaiMan** [comment]
Looks like webhook was invalid. I've re-created it for you. It should work now. Unfortunately, the past commits are lost. :-(

**Comment by sebastianhaberey** [comment]
Nice, looks good now, thanks a lot. Never mind about the commits!

**Comment by DomDomHaas** [comment]
I'm having the same problem on https://github.com/EnviDat/envidat_frontend
@BanzaiMan  Cloud you have a look?

**Comment by BanzaiMan** [comment]
@DomDomHaas Both https://travis-ci.com/EnviDat/envidat_frontend nor https://travis-ci.org/EnviDat/envidat_frontend say they are not active. Please check the configuration.
