### ISSUE TITLE
RethinkDB addon fails

### ISSUE THREAD

**Issue by loeffel-io** [travis-ci/travis-ci#10121]
<img width="777" alt="bildschirmfoto 2018-09-15 um 14 52 51" src="https://user-images.githubusercontent.com/12670730/45586415-5a868b80-b8f7-11e8-81bb-66c320e6103e.png">

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by loeffel-io** [comment]
Hey @BanzaiMan, 

I thought this screenshot should be enough.
Email sent.

**Comment by meatballhat** [comment]
@loeffel-io I reopened this because I believe it's specific to the rethinkdb addon, FYI

**Comment by loeffel-io** [comment]
Fixed! Thank you so much
