### ISSUE TITLE
ipa generation failed

### ISSUE THREAD

**Issue by vtkumaresan** [travis-ci/travis-ci#10125]
I'm generating iPa in travis server but its failing. Local system working fine.

Here is the below log,

```
xcodebuild[3942:13367] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/ClanHQ_2018-09-17_09-04-39.731.xcdistributionlogs'.
2018-09-17 09:04:42.354 xcodebuild[3942:13367] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7f98e12930d0>: Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value., NSFilePath=/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/ipatool-json-filepath-jL9A7u}
error: exportArchive: The data couldn’t be read because it isn’t in the correct format.
Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value., NSFilePath=/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/ipatool-json-filepath-jL9A7u}
```

Please suggest a solution.

**Comment by DrTorte** [comment]
Hey there,

Sorry to hear about the issue you're running into! I'd suggest emailing in to support@travis-ci.com with a link to the repo and the build log so we can investigate directly. Thanks!

**Comment by vtkumaresan** [comment]
Hi @DrTorte, I'd already but didn't get proper response,

```
I'm not quite sure what is at play here. Googling for the error message you have is pointing to missing or duplicated entries in a plist file.

To have a better understanding of your situation, could you tell me what Xcode version you are using locally? In your build, you are using Xcode 9.4.1. Is this the right version?

Please let me know and we will continue from there.
```

I checked the plist validation with plutil cmd. everything seems to be ok.

**Comment by asalom** [comment]
Are there any other errors?

**Comment by vtkumaresan** [comment]
Got this message at beginning,

`Fix WWDRCA Certificate
Unable to delete certificate matching "0950B6CD3D2F37EA246A1AAA20DFAADBD6FE1F75"security: AppleWWDRCA.cer: already in /Library/Keychains/System.keychain`

**Comment by vtkumaresan** [comment]
So tried to remove the expired certificate but it returns permission error.
`security delete-certificate -c "Apple Worldwide Developer Relations Certification Authority" /Library/Keychains/System.keychain
`

**Comment by vtkumaresan** [comment]
solved issue temp by disabling 'compileBitcode' as false.
strange issue happening in travis. please fix it.

**Comment by asalom** [comment]
This doesn’t look like a Travis issue at all. Make sure you’re signing the
app correctly. Could you try the same thing in a machine that doesn’t have
pre installed certificates and provisioning profiles? I think you’ll
encounter the same problem

**Comment by vtkumaresan** [comment]
Hmm. Yes, I'd freshly in my system. 
Let me check new machine...

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
