### ISSUE TITLE
Script execution after success

### ISSUE THREAD

**Issue by csonorajr** [travis-ci/travis-ci#10128]
Hi! I'm trying to run an shell script after a test is complete to push some scripts to New Relic, but travis is not executing it. Do you have any docs or an example on how to do this? Thanks!

**Comment by BanzaiMan** [comment]
Hello, there.

When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!
