### ISSUE TITLE
Unable to locate package crystal-nightly

### ISSUE THREAD

**Issue by vladfaust** [travis-ci/travis-ci#10126]
[Build ](https://travis-ci.org/vladfaust/core/builds/429356493)fails with `E: Unable to locate package crystal-nightly`. 

[`.travis.yml`](https://github.com/vladfaust/core/blob/master/.travis.yml):

```yaml
language: crystal
crystal: nightly
```

/cc @jhass @matiasgarciaisaia @waj @will

**Comment by loeffel-io** [comment]
Same for `rethinkdb` since saturday.. unbelievable

**Comment by BanzaiMan** [comment]
A likely explanation is that the APT update failed for some reason. (The build log unfortunately does not show it, but that is the most reasonable explanation.)

**Comment by loeffel-io** [comment]
My build log tells me `sudo: travis_apt_get_update: command not found`

**Comment by loeffel-io** [comment]
#10121

**Comment by meatballhat** [comment]
fwiw, I'm not able to connect to https://nightly.crystal-lang.org/apt, failing with:

```
E: Failed to fetch https://nightly.crystal-lang.org/apt/dists/crystal/main/binary-amd64/Packages  Failed to connect to nightly.crystal-lang.org port 443: Connection timed out
E: Failed to fetch https://nightly.crystal-lang.org/apt/dists/crystal/main/binary-i386/Packages  Failed to connect to nightly.crystal-lang.org port 443: Connection timed out
```

**Comment by meatballhat** [comment]
Related (?) issue from many months ago at https://github.com/crystal-lang/crystal/issues/5836

**Comment by Blacksmoke16** [comment]
@jhass @matiasgarciaisaia @waj @will any update on this?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
