### ISSUE TITLE
dpkg-deb: error: archive has premature member 'control.tar.xz' before 'control.tar.gz', giving up

### ISSUE THREAD

**Issue by bczoma** [travis-ci/travis-ci#10132]
https://github.com/travis-ci/travis-ci/issues/9361 has re-surfaced, had to apply the workaround described there. Less than 24 hours ago this was not the case. Wondering if https://github.com/diffblue/cbmc/pull/2717 has had an effect.

**Comment by DrTorte** [comment]
Hey there,

Thanks for letting us know! Do you happen to have a build log you could link to where this occurred? If it's for a private project, I'd suggest emailing it in to support@travis-ci.com so we can investigate. Thanks!

**Comment by bczoma** [comment]
Thanks @DrTorte - it is in public domain: https://travis-ci.org/SolaceDev/solace-kubernetes-quickstart/builds/430567496

**Comment by RochesterinNYC** [comment]
I started experiencing this error with `archive has premature member 'control.tar.xz' before 'control.tar.gz'` as well in trying to locally build a Docker image that uses the usual method to install the `gcloud` SDK:

```
RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update -y && apt-get install google-cloud-sdk -y
```

This was previously just working yesterday with no changes in the `Dockerfile`. Something must be misconfigured or misbuilt on the `gcloud` SDK package end.

**Comment by BanzaiMan** [comment]
See #9361.

**Comment by carmat88** [comment]
Hello Folks! I was about to follow up in the thread I've opened a while ago, but since it's closed I didn't want to re-open given that this one is active for the time being. I second the bczoma's post. Issue seems to have re-surfaced. In our case it's happening while installing `google-cloud-sdk` via `apt` of course. Here is one build log:

- https://travis-ci.org/kubenow/image/jobs/430932961

Workaround described did work in our case as well.

Hope it could help!

Cheers!

**Comment by tautschnig** [comment]
We fixed this via https://github.com/diffblue/cbmc/pull/2986 - which also includes a link to the bug report filed to the Google Cloud SDK team.

**Comment by bczoma** [comment]
Verified fix with successful run after removing my workaround.

This can be closed now, thank you!

**Comment by raysuelzer** [comment]
This bug is back.

**Comment by matks** [comment]
This fix worked for me https://github.com/EC-CUBE/eccube-2_13/pull/311/files

**Comment by martin-displayr** [comment]
This bug is back.
