### ISSUE TITLE
"osx_image": "xcode10.0" is using wrong osx image

### ISSUE THREAD

**Issue by wongzigii** [travis-ci/travis-ci#10131]
> export PATH=/Applications/Xcode-9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode-9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode-9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/usr/bin:/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/usr/local/bin:/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin:/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/bin:/Applications/Xcode-9.4.1.app/Contents/Developer/usr/bin:/Applications/Xcode-9.4.1.app/Contents/Developer/usr/local/bin:/Users/travis/.rvm/gems/ruby-2.4.3/bin:/Users/travis/.rvm/gems/ruby-2.4.3@global/bin:/Users/travis/.rvm/rubies/ruby-2.4.3/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/Users/travis/.nvm/versions/node/v6.14.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

Using `"osx_image": "xcode10"` instead of `"osx_image": "xcode10.0"`  will do the trick and I think they are equal implicitly.

**Comment by BanzaiMan** [comment]
For consistency with the past versions, please use `xcode10`. Thanks.
