### ISSUE TITLE
Google Cloud Datastore deploy does not actually deploy.

### ISSUE THREAD

**Issue by JamieSinn** [travis-ci/travis-ci#10136]
I have a project that is supposed to be deploying HTML files to GCS - Travis thinks that it's working but the GCS bucket shows that no files have been changed.

https://travis-ci.com/OTRobotics/otr-scouting-web/builds/85360228

https://i.imgur.com/cQFbIFw.png

Could this be related to the OpenSSL deprecation of Digest::Digest?

**Comment by BanzaiMan** [comment]
Closing this in favor of https://github.com/travis-ci/dpl/issues/792
