### ISSUE TITLE
Elasticsearch 6 as travis service?

### ISSUE THREAD

**Issue by 3lnc** [travis-ci/travis-ci#10134]
AFAIK, now `services: elasticsearch` provides ES 5.5, while 6.x is in GA from November 2017.

Am I missing way to run it or it just wasn't update for a long time? If latter is the case, [documentation on this](https://docs.travis-ci.com/user/database-setup/#elasticsearch) could be updated too.

Thanks.

**Comment by 3lnc** [comment]
@BanzaiMan any updates on this? Maybe I can help in any way?

**Comment by DrTorte** [comment]
Hey there @3lnc,

I'd suggest opening a thread on the forum where we're more active these days, and will be able to get your information the right place easier. You can find it at [https://travis-ci.community](https://travis-ci.community). Thanks!

**Comment by IT-Cru** [comment]
@DrTorte : Please provide deeper link for us, where we can find more infos for this issue on travis-ci.community. When I do a search for 'elastic' or 'elasticsearch' I find nothing.
