### ISSUE TITLE
Leading whitespace being removed from logs, breaking formatting

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#10133]
Hi!

It looks like there been a change to how job log output is shown in the log viewer, which means leading whitespace in each line is being removed, when it wasn't before. This breaks the layout of log output, making it harder to read.

eg:
https://travis-ci.org/mozilla/treeherder/jobs/430084979#L702

The whitespace exists when looking at the raw log:
https://api.travis-ci.org/v3/job/430562297/log.txt

...and this issue seems to occur even on much older jobs that I believe looked fine at the time:
https://travis-ci.org/mozilla/treeherder/jobs/419748761

...so I'm presuming it's a UI regression rather than a log ingestion/processing issue?

![screenshot_2018-09-19 job 23864 3 - mozilla treeherder - travis ci 1](https://user-images.githubusercontent.com/501702/45761873-07794500-bc25-11e8-90ee-8b6d2f02e7e1.png)

**Comment by backspace** [comment]
Here’s a comparison, for posterity:

![image](https://user-images.githubusercontent.com/43280/45762807-d08b3b00-bbf4-11e8-86fa-90f0d5cd71b6.png)

I’ve reverted the commit that broke this. We’ll have to find another way to fix the intended bug without breaking the layout for you. Thanks for the report!

**Comment by edmorley** [comment]
Many thanks for the revert and quick turnaround :-)
