### ISSUE TITLE
repository not known to https://api.travis-ci.org/

### ISSUE THREAD

**Issue by tillias** [travis-ci/travis-ci#10137]
Hi guys.

I have following git repo: https://github.com/tillias/url-shortener
When I try to run "travis encrypt ..." I have following error:

> Detected repository as tillias/url-shortener, is this correct? |yes| yes
> repository not known to https://api.travis-ci.org/: tillias/url-shortener

In my .git/config:

> [travis]
> 	slug = tillias/url-shortener

Why I get this nasty error? I can explicit access my build here https://travis-ci.com/tillias/url-shortener as well as github badge/icon shows build status

**Comment by tillias** [comment]
Also when I call https://api.travis-ci.org/repos/tillias/url-shortener/key manually -- there is {"file":"not found"}

**Comment by tillias** [comment]
Thanks, that is it. Not sure why but it also asks me for --pro during login.

**Comment by davidgfolch** [comment]
travis encrypt --pro <yourkey>

**Comment by JokerQyou** [comment]
It's been over two years since travis [officially announced the migration from `.org` to `.com`](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps), and users are still expected to pass `--com` manually everytime? Is there any subcommands to change the endpoint permanently?

**Comment by jtbayly** [comment]
I was recently pushed by Travis to migrate to .com, and I didn't see any instructions on the necessity of updating all of my travis cli commands. 👎

**Comment by malthejorgensen** [comment]
I had an old entry in `.git/config` that wasn't listed by `git remote -v`:

```
[travis]
	slug = <incorrect org>/example-repo
```

Fixing that, fixed the error for me.
