### ISSUE TITLE
Specifiy what hardware/cloud provider to use

### ISSUE THREAD

**Issue by travisdowns** [travis-ci/travis-ci#10145]
About one third of my jobs end up running on AMD Zen hardware (apparently on Packet). Is there any way to specifically request this hardware and/or packet.net based servers?

I ask because I have some AVX2 specific code and the Intel machines that I get most of the time are IvyBridge-era and don't support AVX2, but the AMD machine supports it just fine.

**Comment by BanzaiMan** [comment]
This is not possible at present time, but we might be able to work with you to make this a reality. Please email us at support@travis-ci.com for further inquiry.

I'm closing this in the mean time.
