### ISSUE TITLE
Packages not found when building netstandard2.0 project

### ISSUE THREAD

**Issue by dhowe** [travis-ci/travis-ci#10146]
Hi, so I recently migrated my C# library (called dialogic) to netstandard2.0 from netcoreapp2.0

Everything builds/runs correctly on my system, however my [build now fails on travis](https://api.travis-ci.org/v3/job/432128241/log.txt). Here is [my local log](https://gist.github.com/dhowe/063c66bb6db13b26620788d029ef0753), running what should be the same commands...

Apparently some packages which should be in .NET standard are not found:

`The type or namespace name 'Thread' does not exist in the namespace 'System.Threading' (are you missing an assembly reference?) 
`

any help would be great as I'm sort of out of ideas at the moment

@joshua-anderson @akoeplinger @nterry

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
