### ISSUE TITLE
PHP builds are broken

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#10147]
See https://travis-ci.org/symfony/polyfill/jobs/432505181 (and some other jobs of the same build).

The installation of PHP fails with errors saying that some commands don't exist.

**Comment by stof** [comment]
Looking at which jobs are failing, it looks like things are working fine only when PHP is already pre-installed.

**Comment by BanzaiMan** [comment]
For some reason only on this build we are not fetching the archives from S3. On [the build before](https://travis-ci.org/symfony/polyfill/builds/432498927) and [after](https://travis-ci.org/symfony/polyfill/builds/432515880) we do.

**Comment by stof** [comment]
that's not the first time that I see such failures (and indeed, restarting the job often makes it work). It would be great to have this working fine each time (when you are a contributor and not a maintainer, such failure means you cannot get the CI status at all, as only maintainers can restart the job).

**Comment by BanzaiMan** [comment]
> that's not the first time that I see such failures (and indeed, restarting the job often makes it work).

Do you have other data points to share?

**Comment by stof** [comment]
Well, not non-restarted builds

**Comment by stof** [comment]
another one where I know this happened is https://travis-ci.org/doctrine/doctrine2/builds/430955996. One of the jobs of the "Test" stage had to be restarted due to this PHP installation issue. I don't remember which job it was, but you could identify it by looking at the time where the jobs ran (but then, not sure whether it helps you when the job had been restarted already)

**Comment by joepvd** [comment]
Thanks for the report. We have located and removed the cause of this error.

**Comment by BanzaiMan** [comment]
Let us know if you see further problems. Thanks.
