### ISSUE TITLE
Travis not exporting the encrypted variables properly since 2 days

### ISSUE THREAD

**Issue by dbjpanda** [travis-ci/travis-ci#10140]
REPO: https://github.com/dbjpanda/encryption_bug_test
Encrypted variables : `travis encrypt MASTER_MYSQL_USER=travis MASTER_MYSQL_PASSWORD=travistest MASTER_MYSQL_ROOT_PASSWORD=helloworld MASTER_ADMIN_PASS=pass`
Error: https://travis-ci.com/dbjpanda/encryption_bug_test/builds/85475351#L371

You can see in the line 371, It is not exporting the variables. I tried it many times. Before two days it was working properly.

**Comment by iriberri** [comment]
Hi @dbjpanda - thanks for opening the issue and for keeping us posted. Happy to hear you could sort this out.

What you mention seems to be an issue about encrypting the env vars against the wrong infrastructure, so I'd recommend using:

`travis setup heroku --org -r <repo_slug>`, if your project is running in travis-ci.org

or 

`travis setup heroku --pro -r <repo_slug>`, if your project is running in travis-ci.com

and let us know if this helps?

If your project is open source and is built in travis-ci.com, I think the Travis CLI might be encrypting it against .org instead.

There are further details at https://github.com/travis-ci/travis-ci/issues/10018#issuecomment-417254113 that you or other folks stumbling upon this issue might find helpful.

Don't hesitate to reopen this if you still see any problems!

**Comment by dbjpanda** [comment]
@iriberri Well I have added the repo to travis-ci.com and encrypt my key like        
`travis encrypt KEY=VALUE --pro` then it says `repository not known to https://api.travis-ci.org/ `.
It means we need that repo travis-ci.org . Key encryption of public repo can not be handled properly by travis-ci.com.

**Comment by dbjpanda** [comment]
It seems like if we have a public repo then we need to pass --org, and if we have a private repo then we need to pass --prp . Travis client is unable to detect it automatically. However when I passed --org it worked. Thanks @iriberri
