### ISSUE TITLE
Make :language a matrix key?

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#1014]
The following suggestion was sent to the mailinglist by William Fulton and I think it'd make sense to make :language a matrix key ... which I believe should give this flexibility with little other changes required, no?

+++

I havn't had much success in getting the matrix of versions working for our needs. I am configuring swig which is a bit unusual as it can supports nearly all of the languages Travis does. SWIG is compiled via a C++ compiler, but as it generates wrappers of C/C++ code for multiple different scripting languages, we would like runtime tests for Java, Perl, Python, Ruby, PHP etc etc. Ideally I would like to test each language individually so that the resulting Build Matrix would look something like:

```
Job     Duration     Finished     Compiler     Python     Jdk       Ruby     Env
8.1     xxx          xxx          gcc          2.7        -         -        SWIGLANG=python
8.2     xxx          xxx          gcc          3.3        -         -        SWIGLANG=python
8.3     xxx          xxx          gcc          -          openjdk6  -        SWIGLANG=java
8.4     xxx          xxx          gcc          -          openjdk7  -        SWIGLANG=java
8.5     xxx          xxx          gcc          -          -         1.8.7    SWIGLANG=ruby
8.6     xxx          xxx          gcc          -          -         1.9.3    SWIGLANG=ruby
```

From my experiments, I can't get any control over the version of the script languages. For example this simple .travis.yml file only provides Python 2.7 (the default) and not 3.3 in all 4 rows of the matrix:

```
language: cpp
compiler:
  - gcc
  - clang
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get install libboost-dev -qq
script: ./autogen.sh && ./configure && make -s && make -k check-python-test-suite
```

Is there any easy way to control the versions of the different scripting languages for a C++ project? The only thing that seems might work is to 'sudo apt-get install xxx' where xxx is the requisite language. If this is the only sensible way to proceed, I'd like to piggy back off whatever Travis uses for the language versions supported. Is there a list/mapping of the debian package names for all the language versions supported by Travis at any given time?

**Comment by joshk** [comment]
I'm closing this issue as it has become stale and is unlikely to be completed in the next 3-6 months
