### ISSUE TITLE
Waiting for status to be reported

### ISSUE THREAD

**Issue by hajimehoshi** [travis-ci/travis-ci#10144]
Hi all,

A PR in my repository didn't kick building on the Travis CI for long time. Could you take a look?

https://github.com/hajimehoshi/ebiten/pull/684

Thanks!

**Comment by BanzaiMan** [comment]
Sorry for the troubles. It appears that the webhook was invalid for some reason. I've re-created it for this repository. It should work now. Please close and re-open the PR, or push a new commit to the PR.

Thanks!

**Comment by hajimehoshi** [comment]
Looks like building started by reopening the PR. Thank you for taking care of this!
