### ISSUE TITLE
curl request to api.github.com randomly produces either 200 or 403 status

### ISSUE THREAD

**Issue by posidron** [travis-ci/travis-ci#10142]
Hi,

I have this line in a script:
```
LATEST_VERSION=$(curl -vLs --retry 5 https://api.github.com/repos/docker/docker-credential-helpers/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')
```

Locally it returns 100% of the time a 200 status but running in Travis the chances are like flipping a coin. I can not identify the reason.

I have attached the verbose logs of the command from two runs at Travis CI

[run1.txt](https://github.com/travis-ci/travis-ci/files/2405604/run1.txt)
[run2.txt](https://github.com/travis-ci/travis-ci/files/2405603/run2.txt)

The original log at Travis: https://travis-ci.org/MozillaSecurity/orion/builds/431486933

**Comment by BanzaiMan** [comment]
This is most likely due to the API rate limiting. Our builds often share the IP address, and anonymous API requests to GitHub are limited to 5000 requests per hour.

If it is important that the API calls succeed, I suggest using an API token for it.

**Comment by posidron** [comment]
```
< X-RateLimit-Limit: 60
< X-RateLimit-Remaining: 0
```

Gnah overlooked that. Makes totally sense. Thank you!
