### ISSUE TITLE
Conditional stages/jobs based on presence of secure environmental variables

### ISSUE THREAD

**Issue by liujoshua** [travis-ci/travis-ci#10157]
Hello,

I'd like detect availability of credentials stored as encrypted variables as conditions for running stages/jobs.

I'm using `env(TRAVIS_SECURE_ENV_VARS) IS true` and it does not appear to work. Is this variable available when evaluating the build configuration?

Thanks.

**Comment by liujoshua** [comment]
Looks like this works: `env(secure_var) IS present`

**Comment by BanzaiMan** [comment]
Good to hear. Can this be closed, then?

**Comment by liujoshua** [comment]
I solved my issue. However, is the fact that `env(TRAVIS_SECURE_ENV_VARS) IS true` does not work a bug? Or is it working as expected?

**Comment by BanzaiMan** [comment]
Do you have a build log URL to share?

**Comment by liujoshua** [comment]
https://travis-ci.org/Sage-Bionetworks/mPower-2-Android/builds/442866877?utm_source=github_status&utm_medium=notification

**Comment by BanzaiMan** [comment]
There might be some competing `if`s at play here. While there is an `env() IS present` on https://github.com/Sage-Bionetworks/mPower-2-Android/blob/3d35d3780b009b4176b9b2b46999cebcfe3ebc96/.travis.yml#L35, I also see one that does not filter on the presence of this env var on https://github.com/Sage-Bionetworks/mPower-2-Android/blob/3d35d3780b009b4176b9b2b46999cebcfe3ebc96/.travis.yml#L57-L70, which is **exactly** what https://travis-ci.org/Sage-Bionetworks/mPower-2-Android/jobs/442866879 is.

I will note that the first `firebase-test` job is not selected, so I am guessing that `if: env() IS present` is effective for that job, and for that job only.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
