### ISSUE TITLE
[macos request] macOS 10.14?

### ISSUE THREAD

**Issue by jjgod** [travis-ci/travis-ci#10155]
Will it be possible to run Xcode 10 with macOS 10.14 to test?

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. We are looking at providing it, but no ETA at the moment. Thank you for your patience.

**Comment by mjm** [comment]
Hi @jjgod! Thanks for getting in touch!

I don't have an ETA for you yet on being able to use macOS 10.14 Mojave for Travis builds. We are still in the early stages of investigating Mojave for our images, so it'll probably be some time before we release an image that runs Mojave. New macOS versions generally are more work and present more technical challenges than new Xcode versions.

I would expect that we'll release a later Xcode 10.x image with macOS 10.14 Mojave.

**Comment by d12frosted** [comment]
Thanks for the heads up! Looking forward Mojave one Travis. Actually, would be really nice to have it sooner than later.

Cheers.

**Comment by mjm** [comment]
It’s a priority for us to be able to support Mojave in the near term. It will require a significant upgrade to our virtualization infrastructure to be able to run it: Mojave isn’t supported on the VMware version we are already running.

We’re working to make that happen in the next couple of weeks, after which we will be in a position to try to build new images that run Mojave.

**Comment by gnzlbg** [comment]
@mjm thank you for the update!

**Comment by DrTorte** [comment]
Hello,

As we're no longer supporting GitHub issues but this issue remains open, I'm creating a copy of this on the forum. [Please see this link](https://travis-ci.community/t/issue-macos-request-macos-10-14-migrated-from-github-issues/1155).

Thanks and happy building!
