### ISSUE TITLE
Cache folder fails "<folder> is not yet cached"

### ISSUE THREAD

**Issue by vfdev-5** [travis-ci/travis-ci#10156]
Hi, 

I'm trying to cache a folder where conda is installed similar to [this example](https://travis-ci.org/gpincheiraa/travis-cache-webpack), but in the stage where I need to use the cached folder I got:
```
Setting up build cache
$ export CASHER_DIR=${TRAVIS_HOME}/.casher
0.03s$ Installing caching utilities
0.00s
23.39sattempting to download cache archive
fetching master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--python-2.7.tgz
found cache
0.00s
6.50sadding /home/travis/build/[secure]/tests_auto_deploy/.miniconda to cache
creating directory /home/travis/build/[secure]/tests_auto_deploy/.miniconda
miniconda is not yet cached
```
What am I doing wrong ?

[Here](https://travis-ci.org/vfdev-5/tests_auto_deploy/builds/433975140) is failed build.

Thanks.

**Comment by BanzaiMan** [comment]
Thanks for the report. Looks like there is a bug in the caching logic.

**Comment by BanzaiMan** [comment]
Probably a variation of #9814.
