### ISSUE TITLE
Waiting for status to be reported

### ISSUE THREAD

**Issue by thinkerou** [travis-ci/travis-ci#10153]
when I push one pull request, the status of travis-ci is `Waiting for status to be reported`, please see here: https://github.com/gin-gonic/gin/pull/1569

I have searched the issue using `Waiting for status to be reported` with google, see: https://www.google.com.hk/search?q=travis+Waiting+for+status+to+be+reported&oq=travis+Waiting+for+status+to+be+reported&aqs=chrome..69i57.3700j0j4&sourceid=chrome&ie=UTF-8
and read top10 and I can't fix the issue.

thanks!

**Comment by BanzaiMan** [comment]
Hello, there. https://travis-ci.org/gin-gonic/gin/requests shows that your PR contains an error in `.travis.yml`.

**Comment by thinkerou** [comment]
@BanzaiMan thanks a lot, I fixed it after it's run ok.
