### ISSUE TITLE
Erlang/OTP 21.1 is released, travis-erlang-builder needs to run.

### ISSUE THREAD

**Issue by getong** [travis-ci/travis-ci#10154]

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-nightly-builder/commit/fbf3e7a4138ec787a731e155b9c604b7fb16be23

https://travis-ci.org/travis-ci/travis-nightly-builder/jobs/433460065

https://travis-ci.org/travis-ci/travis-erlang-builder/builds/433461436

**Comment by BanzaiMan** [comment]
Thanks for the ping. It will be available when the archives are created upon successful compilations in the build indicated above.
