### ISSUE TITLE
Build timeout

### ISSUE THREAD

**Issue by sgermanserrano** [travis-ci/travis-ci#10159]
Hi, 

I added a script with a customised travis_wait to keep the log updating while a background job is running. This works fine when building in trusty but gives a timeout when doing the same in xenial. 

Could you please see log below:
[link](https://travis-ci.org/CPFL/Autoware/builds/434541634)

I would expect jobs [1212.1](https://travis-ci.org/CPFL/Autoware/jobs/434541635) and [1212.3](https://travis-ci.org/CPFL/Autoware/jobs/434541637) to behave in the same manner.

Thanks

**Comment by BanzaiMan** [comment]
Sorry, but we cannot provide support for your custom functions. If you are interested, we can enable the debug feature so you can troubleshoot. Thanks.

**Comment by sgermanserrano** [comment]
Hi, thanks for the reply. I had the same issue when running the default travis_wait function, is there a way to enable more verbosity when using travis_wait?

Thanks

**Comment by BanzaiMan** [comment]
There is not. Sorry.

**Comment by sgermanserrano** [comment]
Thanks for the quick reply. How would the debug feature work?

**Comment by DrTorte** [comment]
Hello,

Sorry about the delayed reply - If you'd like to get the Debug feature enabled, just shoot an email to support@travis-ci.com and we'll be glad to set it up for you. It'll allow you to SSH into a build and run things manually until you can get them working.

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
