### ISSUE TITLE
SonarCloud integration fails on Java 11

### ISSUE THREAD

**Issue by triceo** [travis-ci/travis-ci#10164]
[See the buid.](https://travis-ci.org/RoboZonky/robozonky/jobs/435300869)

This is most likely caused by an old version of ASM being included in the Sonar codebase. This version does not support Java 11 bytecode, which my project produces.

    [ERROR] Unable to create symbol table for : /home/travis/build/RoboZonky/robozonky/robozonky-integration-zonkoid/src/main/java/com/github/robozonky/integrations/zonkoid/Util.java
    java.lang.IllegalArgumentException: Unsupported class file major version 55
	    at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
  	    at org.objectweb.asm.ClassReader.<init>(ClassReader.java:148)
	    at org.objectweb.asm.ClassReader.<init>(ClassReader.java:136)
	    at org.sonar.java.resolve.BytecodeCompleter.loadClass(BytecodeCompleter.java:242)

**Comment by BanzaiMan** [comment]
Hello, there.

Could you report the issue to SonarSource? Thanks.

**Comment by triceo** [comment]
@BanzaiMan There is apparently an entire release that focuses on Java 11 compatibility:

https://jira.sonarsource.com/browse/SONARJAVA/fixforversion/14558/?selectedTab=com.atlassian.jira.plugins.jira-development-integration-plugin:release-report-tabpanel

(Scheduled to be released 3 days ago. :-))

**Comment by triceo** [comment]
@BanzaiMan Version 5.8, one which should already support Java 11, has been released.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
