### ISSUE TITLE
output truncation and subsequent build failure

### ISSUE THREAD

**Issue by grondo** [travis-ci/travis-ci#10161]
Travis-CI builds are suddenly failing for us with a confusing pattern. The output of the build is truncated at some point during the tests, and then the `after_failure` commands are called as if something failed, but post-processing steps in `after_failure` do not give any indication of what, if anything failed. The exit status of the `script` doesn't seem to show up in the travis log.

https://travis-ci.org/flux-framework/flux-core/builds/434742658

In one case we saw errors packaging up ~/.ccache directory for the travis cache that indicates perhaps the  build is still running:
https://travis-ci.org/flux-framework/flux-core/jobs/434742660#L8910

I've tried rebuilding older commits that succeeded previously and they now fail in similar manner.

As an experiment I tried redirecting all output to a file in the build and only emitting the output if the build fails -- and in this case, all builders succeed:

https://travis-ci.org/grondo/flux-core/builds/434850091

So this seems to have something to do with the volume of output. The issue appears to have been introduced today, because all these builds worked before this afternoon local time (PDT).

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
