### ISSUE TITLE
Cannot use tlmgr to install LaTeX package

### ISSUE THREAD

**Issue by duckmayr** [travis-ci/travis-ci#10166]
This is related to the auto-closed issue #7875

I am using Travis CI for R package development. When I moved to PDF vignettes, my OSX builds failed with the following error:

    LaTeX Error: File `framed.sty' not found.

(see https://travis-ci.org/duckmayr/RcppDist/jobs/435533012)

Following [this guide](https://docs.travis-ci.com/user/languages/r/), I added the following to my `.travis.yml`

    before_install:
      - tlmgr install framed

However, I then received this error:

    $ tlmgr install framed
    You don't have permission to change the installation in any way,
    specifically, the directory /usr/local/texlive/2018basic/tlpkg/ is not writable.
    Please run this program as administrator, or contact your local admin.
    tlmgr: An error has occurred. See above messages. Exiting.

(see https://travis-ci.org/duckmayr/RcppDist/jobs/435540815)

**Comment by BanzaiMan** [comment]
Try `sudo tlmgr install X`.

**Comment by duckmayr** [comment]
@BanzaiMan Thanks! That got me most of the way there. It fixed the issue on Mac builds (once I added one more LaTeX package I needed), but then my Linux builds complained. So, I just made the command conditional on `$OSTYPE`. For anyone else having this issue, the complete fix that worked for me was 

```
before_install:
  - if [[ "$OSTYPE" != "linux-gnu" ]]; then sudo tlmgr install framed titling; fi
```

**Comment by jinyanghuang** [comment]
doesn't work for me

**Comment by Direct-A** [comment]
> doesn't work for me

it also doesn't work for me, and I have changed wsl to version 2, it still doesn't work
