### ISSUE TITLE
macOS: Have to add "rvm get stable" or build fails without error

### ISSUE THREAD

**Issue by RalfJung** [travis-ci/travis-ci#10165]
We have to add `rvm get stable` to the `before_script` of our `.travis.yml`, or else the build just fails at the following step without even showing an error message:
```
$ # test that the rustc_tests binary compiles
cd rustc_tests &&
cargo build --release &&
cd ..
```
Note that I have no idea what `rvm get stable` does (I do not even know what `rvm` is), the command was already in the CI file when I joined the project and has been cargo-culted since then.

You can see this live at https://github.com/solson/miri/pull/465, the failing build is at https://travis-ci.org/solson/miri/jobs/435551633.

A comment indicates this might be related to https://github.com/travis-ci/travis-ci/issues/6307, but that issue has been closed years ago.

**Comment by BanzaiMan** [comment]
Hello, there.

Another explanation here is that you are setting the `errexit` option: https://github.com/solson/miri/blob/5adc8d9712c91a2fca4403aa4f3aa03011f5d583/.travis.yml#L34 and anything that exits with nonzero will halt your job.

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/common-build-problems/#my-build-fails-unexpectedly

**Comment by RalfJung** [comment]
Well but why would anything have a non-zero exit code without saying what is happening? Also shouldn't travis say "the command XXX failed" if it has non-zero exit code?

We set that `-e` because if one of the commands fails, we don't want Travis to go on with the next, which I have seen Travis do (to my great surprise). I have no idea under which circumstances that behavior even makes sense, but it certainly does not for us.

**Comment by BanzaiMan** [comment]
> Well but why would anything have a non-zero exit code without saying what is happening? Also shouldn't travis say "the command XXX failed" if it has non-zero exit code?


No. That message ("the command X failed") comes from our ability to observe the command's exit status and report the failure. If the build terminates prematurely, there is no opportunity to report that.

> We set that `-e` because if one of the commands fails, we don't want Travis to go on with the next, which I have seen Travis do (to my great surprise). I have no idea under which circumstances that behavior even makes sense, but it certainly does not for us.

That is certainly a valid issue. There is a long-standing issue about that: https://github.com/travis-ci/travis-ci/issues/1066 (Personally, I agree with you; this would be a good change to stop build after the first failure in `script`.)

**Comment by RalfJung** [comment]
> No. That message ("the command X failed") comes from our ability to observe the command's exit status and report the failure. If the build terminates prematurely, there is no opportunity to report that.

Okay, so `set -e` results in the build terminating before your processing can print a nicer error?

That still doesn't explain though why either `cd` or `cargo` fail here without printing any error -- and why `rvm get stable` changes that.

**Comment by BanzaiMan** [comment]
I believe that RVM wraps `cd` to its own purposes. There may be a bug with the version pre-installed on our Mac image and you'd need to update RVM.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
