### ISSUE TITLE
Google Cloud SDK installation fails with tar: write error

### ISSUE THREAD

**Issue by meltsufin** [travis-ci/travis-ci#10169]
Everything used to work until today.
Here's the line in the pre-install section which is causing the failure:
```bash
if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
```

**Comment by BanzaiMan** [comment]
Hello, there.

When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by meltsufin** [comment]
Here you go: https://travis-ci.org/spring-cloud/spring-cloud-gcp/builds/435742974

Thanks!

**Comment by BanzaiMan** [comment]
If you restart the previously failing builds, does that fail again? If you restart the previous passing one, does it fail?

What is curious here is that [the last passing build](https://travis-ci.org/spring-cloud/spring-cloud-gcp/builds/432682085#L431) as well as [the first failing build](https://travis-ci.org/spring-cloud/spring-cloud-gcp/builds/434622304) had the cache and skipped installing Google Cloud SDK.

The first failing build above did not show `tar: write error`. The first one to error this way is https://travis-ci.org/spring-cloud/spring-cloud-gcp/builds/434762114#L457, which shows that the cache was somehow lost, and now installing Google Cloud SDK is having problems.

It is not clear to me why, however. I have been unable to reproduce it. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/436215863#L7094

**Comment by meltsufin** [comment]
The issue seems to have gone away on its own. I'm not sure if anything changed in Cloud SDK or in Travis to cause this.

**Comment by srfrnk** [comment]
Anyone know how to get that magic for my build?
https://travis-ci.org/DAVFoundation/ride-hailing-api/builds/442049115
