### ISSUE TITLE
Job exceeded maximum time limit

### ISSUE THREAD

**Issue by sgermanserrano** [travis-ci/travis-ci#10168]
Hi, 

I working on the [Autoware](https://github.com/CPFL/Autoware) repo, which has a Travis CI time limit of 100mins. I hit the maximum time limit of 50mins when testing developments on my [fork](https://travis-ci.org/sgermanserrano/Autoware). Would it be possible to get the time limit increased?

Thanks

**Comment by BanzaiMan** [comment]
Sorry for the delay. We are happy to take a look at it on a case-by-case basis. Please send email to support@travis-ci.com.

In the meantime, I'm closing this issue.
