### ISSUE TITLE
Flaky builds due to OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "read init-p: connection reset by peer": unknown

### ISSUE THREAD

**Issue by jab** [travis-ci/travis-ci#10163]
Every few days or so my one of my daily cron-triggered jobs fails without any changes since the previous successful build. The most recent example is https://travis-ci.org/jab/bidict/jobs/435257512, output pasted here:
```
Worker information
hostname: f8743cdc-64a1-40c9-8e82-ff0eb130d42f@1.production-1-worker-org-04-packet
version: v4.1.2 https://github.com/travis-ci/worker/tree/91246b057ccd93649046771f29221f839c19a7d3
instance: 0387fdd travisci/ci-garnet:packer-1512502276-986baf0 (via amqp)
startup: 1.306470713s
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "read init-p: connection reset by peer": unknown
```

Some kind of ephemeral (but not infrequent) networking issue?

As long as this keeps happening, is there any way I can protect against this? Long ago I prepended every single network-dependent command in my build with a `travis_retry`, which mitigated Travis network issues in the past, but that doesn't help here as the worker seems to never get as far as even starting my build.

Thanks for any help!

![screen shot 2018-09-30 at 14 41 25](https://user-images.githubusercontent.com/64992/46261259-20a0b200-c4bf-11e8-9400-857a512a1c10.png)

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
