### ISSUE TITLE
Heroku-toolbelt installation fails

### ISSUE THREAD

**Issue by aptgetinstallme** [travis-ci/travis-ci#10167]
Hi,

I have an issue with heroku-toolbelt installation in my builds:
`$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install heroku-toolbelt
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 heroku-toolbelt : Depends: heroku (= 3.99.4) but 7.16.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.
apt-get install failed`

I've been using the same configuration for a long time, Heroku deployments had been working as a charm until it broke yesterday.

Can you please look into this issue?

Kind regards,
Inessa

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by aptgetinstallme** [comment]
Thanks. Yes, it's a private repo, but anyway, I can post here that I was doing heroku-toolbelt installation with apt:
```
apt:
  sources:
    - heroku
  packages:
    - heroku-toolbelt
```
which caused the conflict. So I've removed this block from my yml configuration.

**Comment by BanzaiMan** [comment]
@aptgetinstallme Happy to hear that.
