### ISSUE TITLE
Protected branches and GitHub commit status deprecation 

### ISSUE THREAD

**Issue by offa** [travis-ci/travis-ci#10175]
According to your [recent announcement](https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories) I have to update my protected branch settings to use the new status check. But neither _Travis CI - Pull Request_ nor _Travis CI - Branch_ is available there – all I have is the now deprecated _continuous-integration/travis-ci_.

![travis](https://user-images.githubusercontent.com/8887756/46410722-59cc6280-c709-11e8-936b-915eaa198509.png)
(_Settings -> Branches -> Protected Branch_)

![travis2](https://user-images.githubusercontent.com/8887756/46410980-132b3800-c70a-11e8-9fc9-8a60dd00cc1b.png)
(_Settings -> Integration & services_)

My projects fall into the category [_Existing Open Source Repositories on travis-ci.org_](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg). 

I set up the Travis Github App. Unfortunately this didn't show up the new status checks. I can't migrate my projects to travis.com as they are on the legacy travis.org:

> The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org. This feature will be available shortly. Please read our docs on open source migration to learn more. 

In total I have following Travis apps set up here at Github now (Settings --> Applications):

- **Installed Github Apps:** Travis CI
- **Authorized OAuth Apps:** Travis CI for Open Source and Travis CI

I probably missed something really important at this point …

**Comment by acnagy** [comment]
Hey @offa! So sorry that blog post was unclear - if you _already_ use GitHub Apps and Protected Branches, then you need to use the new checks. Repositories that currently only use legacy service hooks (e.g. `.org` repos that have not been migrated) will not be affected by this change. Once we do have GitHub Apps for `.org` repos with history (coming 🔜, I swear), then you'll need to switch over your protected branches.

**Comment by offa** [comment]
I see! Perfect, thanks for the clarification @acnagy.

**Comment by charliegn** [comment]
@acnagy – I'm having the same problem and my repos do not fall under the .org category.

Actually you can use all of the same screenshots the @offa supplied for my scenario, but 1 of the 6 repos that were already setup with Travis before this official deprecation.  In other words, I have successfully updated 5 of my repos off of the old endpoint onto the new preferred ones.  However one of the repos first needed to be added to the Travis CI GitHub app 'Repository access' configuration, which I've done.  When I went back to that repo's protected branch setup, it wasn't showing the new **Travis CI - Branch** and **Travis CI - Pull Request** options, just the deprecated `continuous-integration/travis-ci` option.  

What am I missing when adding another repo to the Repository access configuration for the Travis CI GitHub app?
