### ISSUE TITLE
Cannot reproduce a build error locally.

### ISSUE THREAD

**Issue by MichalCz** [travis-ci/travis-ci#10177]
Hi,

I'm running automated testing of my open source project in travis-ci [scramjet](https://github.com/signicode/scramjet).  I'm really thankful for your policy of free builds for projects like mine and I really like your environment. 🥇 

Now, after the release of the last worker I started getting errors from the node.js worker on a single test case (I'll remove that for now so the build can pass and I'll be able to release a new version).

Here's the failing build: [Job #349](https://travis-ci.org/signicode/scramjet-core/builds/436115027).

And here's the same test run on my development machine in travis-ci/ci-node docker container: [MichalCz/travis-local-build.log](https://gist.github.com/MichalCz/6a4c774e69fda24ab8ef7775ae2b07ac).

The issue appears on a single test, here's the failure in travis:

```log
✗ async-test/test_err
     ✗ fail(test timed out after 5000ms)
     Error: test timed out after 5000ms
    at Test.assert [as _assert] (/home/travis/build/signicode/scramjet-core/node_modules/tape/lib/test.js:224:54)
    at Test.bound [as _assert] (/home/travis/build/signicode/scramjet-core/node_modules/tape/lib/test.js:76:32)
    at Test.fail (/home/travis/build/signicode/scramjet-core/node_modules/tape/lib/test.js:317:10)
    at Test.bound [as fail] (/home/travis/build/signicode/scramjet-core/node_modules/tape/lib/test.js:76:32)
    at Timeout._onTimeout (/home/travis/build/signicode/scramjet-core/node_modules/tape/lib/test.js:138:14)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

While on local machine in docker image:

```log
✓ data-stream/test_fromx/iteratorMap
     ✓ equal(Test some elements...)
     ✓ equal(Test some elements...)
     ✓ equal(Test some elements...)
     ✓ equal(Should have all elements)
```

The error appears to happen in the following test [async-test.js:65 in scramjet repo](https://github.com/signicode/scramjet-core/blob/v4.16.12/test/v1/async-test.js#L65). In this test I'm emitting an error on purpose so it is caught by the listener. This works well everywhere except travis-ci builds.

Now is there a way in which I could more closely reproduce the latest version of the node.js worker and somehow make the failure to occur in my dev environment? My current steps to reproduce are:

```bash
docker run -it travisci/ci-nodejs:packer-1494866191 /bin/bash
su -l travis
git clone --depth=50 --branch=master https://github.com/signicode/scramjet-core.git signicode/scramjet-core
nvm install 8
export PATH=./node_modules/.bin:$PATH
cd signicode/scramjet-core/
git checkout -qf 77a56e0a075fbc7a8be5bf75ad566110112e0c25
npm ci
npm test
```

**Comment by BanzaiMan** [comment]
Could you try reproducing the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)? Or we can enable the [debug feature](https://docs.travis-ci.com/user/running-build-in-debug-mode/#enabling-debug-mode) for your repo.

**Comment by BanzaiMan** [comment]
It appears to be passing now. https://travis-ci.org/signicode/scramjet-core/builds/447073387
