### ISSUE TITLE
[Request] Improve Travis API documentation

### ISSUE THREAD

**Issue by AllanWang** [travis-ci/travis-ci#10171]
Would it be possible to add nullability info for optional parameters?

Would it also be possible to list the String output options for parameters that are essentially enums?

Eg Builds states, which I believe are undocumented beyond the fact that its a String: https://developer.travis-ci.com/resource/build#Build

Currently, I am simply using intuition and tests, though there may situations that I don't for-see.

For my use case, I am trying to write a better Travis chrome extension (wip code [here](https://github.com/AllanWang/Travis-Tracker))

**Comment by tmonseigne** [comment]
And some quickly tutorial as an hello world for cpp for example

**Comment by BanzaiMan** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks!
