### ISSUE TITLE
deploying to dokku from travis

### ISSUE THREAD

**Issue by tansaku** [travis-ci/travis-ci#10174]
We're trying deploy to dokku from travis.  We're been following these tutorials:

http://blog.abarbanell.de/linux/2017/09/09/deploy-from-travis-to-dokku/

https://github.com/dwyl/learn-travis/blob/master/encrypted-ssh-keys-deployment.md

and have been making some success, but are now stuck on a permission denied issue.  We've reviewed all the keys and they seem like they are correct.

from https://travis-ci.org/AgileVentures/LocalSupport/builds/436388611

```
gent pid 20377
Identity added: ./deploy_key (./deploy_key)
# agileventures-playground.westeurope.cloudapp.azure.com SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
# agileventures-playground.westeurope.cloudapp.azure.com SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
Warning: Permanently added the ECDSA host key for IP address '104.40.243.49' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Script failed with status 128
```

Here's our current deploy script 

https://github.com/AgileVentures/LocalSupport/blob/configure_travis_to_push_to_dokku/scripts/deploy.sh

```
#!/bin/bash
openssl aes-256-cbc -K $encrypted_a6fc752c6b5a_key -iv $encrypted_a6fc752c6b5a_iv -in deploy_key.enc -out ./deploy_key -d
eval "$(ssh-agent -s)"
chmod 600 ./deploy_key
echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
ssh-add ./deploy_key
ssh-keyscan agileventures-playground.westeurope.cloudapp.azure.com >> ~/.ssh/known_hosts
git remote add develop dokku@agileventures-playground.westeurope.cloudapp.azure.com:harrowcn-develop
git config --global push.default simple
git push develop configure_travis_to_push_to_dokku:master
```

and the relevant part of our current .travis.yml

https://github.com/AgileVentures/LocalSupport/blob/configure_travis_to_push_to_dokku/.travis.yml

```
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: configure_travis_to_push_to_dokku
run: bundle exec rake vcr_billy_caches:reset
```

any help on what we might be doing wrong or how to effectively debug would be very much appreciated :-)

**Comment by mattwr18** [comment]
I added this line to the deploy.sh script 
`ssh -v -i ./deploy_key root@104.40.243.49 pwd` to further debug and now getting this in the build ouput:
```
Agent pid 20370
Identity added: ./deploy_key (./deploy_key)
# agileventures-playground.westeurope.cloudapp.azure.com SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
# agileventures-playground.westeurope.cloudapp.azure.com SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/travis/.ssh/config
debug1: /home/travis/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 104.40.243.49 [104.40.243.49] port 22.
debug1: Connection established.
debug1: identity file ./deploy_key type -1
debug1: identity file ./deploy_key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.4 pat OpenSSH* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha1-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-sha1-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1The authenticity of host '104.40.243.49 (104.40.243.49)' can't be established.
ECDSA key fingerprint is 3a:89:59:e6:d8:01:69:bc:5d:5b:18:cd:b2:20:ab:df.
Are you sure you want to continue connecting (yes/no)? : Server host key: ECDSA 3a:89:59:e6:d8:01:69:bc:5d:5b:18:cd:b2:20:ab:df
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
I found this post on SO: 
https://unix.stackexchange.com/questions/33271/how-to-avoid-ssh-asking-permission
I tried moving the call to ssh into the box below the `ssh-keyscan` call, which gave the above error.

**Comment by mattwr18** [comment]
Following advice from the above SO post, I prepended the ssh into the box with this `ssh -o StrictHostKeyChecking=no` and got this error... time to ssh into the build? 
```
Agent pid 20377
Identity added: ./deploy_key (./deploy_key)
# agileventures-playground.westeurope.cloudapp.azure.com SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
# agileventures-playground.westeurope.cloudapp.azure.com SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/travis/.ssh/config
debug1: /home/travis/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 104.40.243.49 [104.40.243.49] port 22.
debug1: Connection established.
debug1: identity file ./deploy_key type -1
debug1: identity file ./deploy_key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.4 pat OpenSSH* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha1-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-sha1-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 3a:89:59:e6:d8:01:69:bc:5d:5b:18:cd:b2:20:ab:df
Warning: Permanently added '104.40.243.49' (ECDSA) to the list of known hosts.
debug1: ssh_ecdsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: ./deploy_key
debug1: Authentications that can continue: publickey
debug1: Trying private key: ./deploy_key
debug1: key_parse_private2: missing begin marker
debug1: read PEM private key done: type RSA
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
Permission denied (publickey).
Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by mattwr18** [comment]
Getting this ouput from the Dokku box auth logs when trying to ssh in from the travis build

`Disconnected from 125.65.42.179 port 58952 [preauth]`

**Comment by mattwr18** [comment]
This is what my `deploy.sh` looks like:
```
#!/bin/bash
openssl aes-256-cbc -K $encrypted_a6fc752c6b5a_key -iv $encrypted_a6fc752c6b5a_iv -in deploy_key.enc -out ./deploy_key -d
eval "$(ssh-agent -s)"
chmod 600 ./deploy_key
echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
ssh-add ./deploy_key
ssh-keyscan agileventures-playground.westeurope.cloudapp.azure.com >> ~/.ssh/known_hosts
ssh -o StrictHostKeyChecking=no -v -i ./deploy_key root@104.40.243.49 pwd
git remote add develop dokku@agileventures-playground.westeurope.cloudapp.azure.com:harrowcn-develop
git config --global push.default simple
git push develop configure_travis_to_push_to_dokku:master
```

**Comment by mattwr18** [comment]
Following the advice from this SO post about the issue above, I changed the LogLevel to DEBUG3
https://superuser.com/questions/1259625/unable-to-login-to-host-via-ssh-just-see-connection-closed-in-authlog

Seems to have only give this output after trying the above commands 

```
Oct 11 22:16:02 DokkuVM sshd[617]: Connection closed by 52.54.31.11 port 56194 [preauth]
Oct 11 22:16:11 DokkuVM sshd[626]: Received disconnect from 61.184.247.3 port 43399:11:  [preauth]
Oct 11 22:16:11 DokkuVM sshd[626]: Disconnected from 61.184.247.3 port 43399 [preauth]
```

**Comment by tansaku** [comment]
We've ssh'd into the travis build box, and can successfully ssh to our deployment box with the deploy_key - in verbose mode we see that key accepted by the server:

```
ssh -v -i ./deploy_key agileventures@agileventures-playground.westeurope.cloudapp.azure.com
```

```
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: ./deploy_key
debug1: Server accepts key: pkalg ssh-rsa blen 535
debug1: Authentication succeeded (publickey).
Authenticated to agileventures-playground.westeurope.cloudapp.azure.com ([104.40.243.49]:22).
```

however when we try to push up over git via ssh the same key appears to be rejected:

```
GIT_SSH_COMMAND="ssh -v -i ./deploy_key" git push develop configure_travis_to_push_to_dokku:master
```
```
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: ./deploy_key
debug1: Authentications that can continue: publickey
debug1: Trying private key: ./deploy_key
debug1: key_parse_private2: missing begin marker
debug1: read PEM private key done: type RSA
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
Permission denied (publickey).
fatal: Could not read from remote repository.
```
and I think we've now at least partially fixed this, as this indicated to us that we needed to give the dokku permissions for that deploy key as well as ssh permissions - actually ssh login permissions not needed, but that's how we'd started ...

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by tansaku** [comment]
thanks @DrTorte - we did manage to solve it. 

Very sorry to hear that you're moving away from github and to a community forum.

I've always thought that travis giving support in github issues was one of the key ways in which you stood out from competing services ...

**Comment by DrTorte** [comment]
Thanks for the feedback - though we do like answering questions publicly when possible rather than privately (such as via threads or what have you) , GitHub issues lend themselves very much to binary yes/no threads rather than conversations. There's also the difficulty of knowing what we've been active with, where we've responded, and where we haven't.

We intend to be more active on the Forum, so hopefully, you'll give it a shot and find it to your liking! 😄

**Comment by tansaku** [comment]
@DrTorte interesting - our team finds that github issues are great for conversations, and have great awareness for where one has been active or not.

Various other services use forums and we find them rather difficult.  It's the github issue support that makes you stand out from the competition, I do hope you reconsider and switch back to github issue support as soon as possible.

**Comment by ohld** [comment]
Any update? What is the easiest way to deploy to dokku after a commit in GitHub repo's master branch?

**Comment by mattwr18** [comment]
we have this repo that we were doing automated deploys... you can check it out as a starting point, maybe @ohld 
https://github.com/AgileVentures/LocalSupport/blob/develop/.travis.yml
https://github.com/AgileVentures/LocalSupport/blob/develop/scripts/deploy.sh
