### ISSUE TITLE
[skip travis] : issue 5302 : Why was this closed and locked?

### ISSUE THREAD

**Issue by solvingj** [travis-ci/travis-ci#10178]
Maybe I'm missing something, but this issue was locked and closed and I could not find any notes about the resolution:

https://github.com/travis-ci/travis-ci/issues/5032

Won't Do?
Done?

Any information

**Comment by meatballhat** [comment]
@solvingj Hello!  This is now implemented.  Sorry about the lack of communication on the issue :heart: https://changelog.travis-ci.com/skip-travis-ci-builds-with-skip-travis-in-commit-message-74620

**Comment by solvingj** [comment]
Amazing, thanks!
