### ISSUE TITLE
Xenial image lacks kiex

### ISSUE THREAD

**Issue by cytadela8** [travis-ci/travis-ci#10170]
Job causing problem: https://travis-ci.org/aeternity/elixir-node/jobs/435810525#L487

Elixir is not installed properly on xenial. As indicated by the build log the problem seems to be that kiex is not available.

I think all relevant information about this issue should be available in the build log. First problem seems to appear at line 488.

**Comment by cytadela8** [comment]
Is there some workaround for this issue or it should get fixed soon? Our checks can't run on Travis due to this problem.

**Comment by cytadela8** [comment]
It's been 7 days since I reported this issue. Is there some chance to solve this in near feature?

**Comment by BanzaiMan** [comment]
Sorry, not at the moment.

**Comment by cytadela8** [comment]
So Elixir is no longer supported by Travis?

**Comment by BanzaiMan** [comment]
It is not supported on Xenial yet.

**Comment by cytadela8** [comment]
On which distribution is it supported?

**Comment by BanzaiMan** [comment]
If you haven't done so, please take a look at our documentation. https://docs.travis-ci.com/user/languages/elixir

**Comment by cytadela8** [comment]
I looked at it before. Does the cryptic box on the top mean it's supported on Precise and Trusty?

**Comment by BanzaiMan** [comment]
Elixir now works on Xenial. https://travis-ci.org/BanzaiMan/travis_production_test/builds/452210018#L425

**Comment by thepiwo** [comment]
@cytadela8 @grzegorz225 could you check if this resolves our issues?

**Comment by cytadela8** [comment]
I restarted the old job and it now succeeds. Thanks for the information and your help @BanzaiMan!
