### ISSUE TITLE
Python 3.4 unavailable on Xenial

### ISSUE THREAD

**Issue by pckroon** [travis-ci/travis-ci#10185]
Hello world,

I'm trying to have Travis run tests using Python 3.4, but the last few days I'm consistently running into the following error. Restarting the job does not help.
```bash
$ curl -sSf -o python-3.4.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.4 archive. The archive may not exist. Please consider a different version.
```
Here's links to two example runs:
https://travis-ci.org/marrink-lab/vermouth-martinize/jobs/437188405
https://travis-ci.org/marrink-lab/vermouth-martinize/jobs/437266586

The full yaml file, which *used* to work, can be found here:
https://github.com/marrink-lab/vermouth-martinize/blob/master/.travis.yml
https://travis-ci.org/marrink-lab/vermouth-martinize/builds/434789013

**Comment by BanzaiMan** [comment]
There was no 3.4 archives for Xenial. I've copied 3.4.8 archives to that name, so you should be able to proceed now. Please restart the failing builds.

**Comment by pckroon** [comment]
Hi! Thanks for the quick response. It can find the package now, but it gives a new error regarding virtualenvs:
```bash
$ source ~/virtualenv/python3.4/bin/activate
/home/travis/.travis/job_stages: line 98: /home/travis/virtualenv/python3.4/bin/activate: No such file or directory
The command "source ~/virtualenv/python3.4/bin/activate" failed and exited with 1 during .
```

Jobs:
https://travis-ci.org/marrink-lab/vermouth-martinize/jobs/437188405
https://travis-ci.org/marrink-lab/vermouth-martinize/jobs/437266586

**Comment by BanzaiMan** [comment]
Sorry about the troubles. https://travis-ci.org/travis-ci/cpython-builder/jobs/438007594 should fix this issue better.

**Comment by jab** [comment]
Thanks @BanzaiMan, that seems to have done the trick 👍

**Comment by pckroon** [comment]
Thanks a million. It also fixed it for me. Nice work!
