### ISSUE TITLE
Why is "hvr-ghc" a disallowed source?

### ISSUE THREAD

**Issue by peti** [travis-ci/travis-ci#10180]
https://github.com/opensuse-haskell/configuration/blob/master/.travis.yml suddenly fails with an error, saying:

~~~
Adding APT Sources
Disallowing sources: hvr-ghc
~~~

This is very surprising; the `hvr-ghc` repository is used by virtually all Haskell builds on Travis. Is there a particular reason why it has been banned?

And furthermore, is there anything I can do to "unban" that repo?

**Comment by BanzaiMan** [comment]
Sorry about the issue. This appears to have been resolved. https://travis-ci.org/opensuse-haskell/configuration/builds/445169795 Please let us know if the issue persists.
