### ISSUE TITLE
Github waiting forever on "Waiting for status to be reported"

### ISSUE THREAD

**Issue by vinh-thai** [travis-ci/travis-ci#10183]
<img width="797" alt="screen shot 2018-10-05 at 10 16 22 am" src="https://user-images.githubusercontent.com/39891184/46511160-164e3180-c88c-11e8-973a-2b3476359118.png">

Looks like this is happening for a bunch of build for us, build success but no status reported to github causing them to wait forever. Could someone help to look into this?

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!
