### ISSUE TITLE
git produces SSL error on some valid certificates

### ISSUE THREAD

**Issue by ozars** [travis-ci/travis-ci#10189]
git produces certificate verification error for valid certificates over HTTPS connection.

From: https://travis-ci.com/ozars/travis-test-ca/builds/86947875

Configuration:
```json
{
  "os": "linux",
  "dist": "trusty",
  "group": "stable",
  "script": [
    "git clone https://gnunet.org/git/libmicrohttpd.git/"
  ],
  "language": "ruby"
}
```

Result:
```shell
[...]
$ git clone https://gnunet.org/git/libmicrohttpd.git/
Cloning into 'libmicrohttpd'...
fatal: unable to access 'https://gnunet.org/git/libmicrohttpd.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
[...]
```

This is the SSL report for gnunet.org:
https://www.ssllabs.com/ssltest/analyze.html?d=gnunet.org

Possible workarounds for now:
- [Upgrading to xenial](https://travis-ci.com/ozars/travis-test-ca/builds/87043412): Setting `dist: xenial` in `.travis.yml`
- [Disabling SSL verification](https://travis-ci.com/ozars/travis-test-ca/builds/87045353): `git -c http.sslVerify=false ...`

I tried updating bunch of packages (gnutls, git, libcurl3-gnutls etc.) selectively through apt, but I couldn't get it to work on trusty.

Edit: Just realized that this is possible duplicate of #8955, which seems closed due to being stale.

**Comment by BanzaiMan** [comment]
If your remote server requires TLS 1.2, Xenial and later is the only reasonable option.

**Comment by ozars** [comment]
FWIW, this issue happens if remote server sends certificate chains out-of-order, so it's likely to affect other TLS versions as well. gnunet.org isn't configured as TLS 1.2 only for example. (A bit more context: git package on trusty depends on libcurl3-gnutls package, which depends on libgnutls26 package, which turns out to have this long-standing issue with processing out-of-order certificate chains.)

A backported patch on ubuntu upstream probably doesn't worth the effort, as trusty reaches EOL soon (April 2019). I guess I will go with moving all my tests to xenial. Thanks.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
