### ISSUE TITLE
The fact that travis does not allow removing cancelled builds may have consequences for users

### ISSUE THREAD

**Issue by radekg** [travis-ci/travis-ci#10182]
Hi there, I was looking at this old issue: https://github.com/travis-ci/travis-ci/issues/877
Happy to see that the ability to clear logs was added but I think there may be cases when this isn't really sufficient.

Please have a look at this:
- https://github.com/radekg/terraform-provisioner-ansible/commit/e708727f2882e2cc23dd52784355f431abe133b5
- parent is: https://github.com/radekg/terraform-provisioner-ansible/commit/89337560d8c1163b221404a20a3007792156d3af

The thing is, https://github.com/radekg/terraform-provisioner-ansible/commit/e708727f2882e2cc23dd52784355f431abe133b5 is a result of rebase of a previous commit and a new commit. The previous commit is not visible in the history, as I wanted it not to be. Not a biggie in this case. But, check the build history on travis-ci.org:

- https://travis-ci.org/radekg/terraform-provisioner-ansible/builds/437389153 refers to a build for a commit that was rebased

The problem is: Travis shows a link to the commit which I wanted to hide => https://github.com/radekg/terraform-provisioner-ansible/commit/44d2e241a0deefff0ea921987c44bb75f99d2a9e.

In this case, it was just my fat fingers. This, however, could be more critical information.

Please reconsider adding an option to remove / hide build from publicly available listing.

**Edit**
Please, at least, consider removing the active link to the commit for non-owners.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
