### ISSUE TITLE
Slow dependency fetching from aptitude [linux sudo]

### ISSUE THREAD

**Issue by SergioRAgostinho** [travis-ci/travis-ci#10186]
Hey,

So I'm a maintainer for the [Point Cloud Library](https://github.com/PointCloudLibrary/pcl). We recently started observing build time-outs again. A simple build which usually lasts 15 minutes, ramped up to 40 with nothing actually added to it. The full builds which would take close to 1h are now all timing out.

A typical build job: https://travis-ci.org/PointCloudLibrary/pcl/builds/437498708
The atypical culprit: https://travis-ci.org/PointCloudLibrary/pcl/builds/437497204

I originally assumed this was a single incident and restarted the job but it exhibited the same behavior again. The build itself is taking one minute, fetching the aptitude dependencies is taking more than half an hour whereas before it was little more than 10minutes.

While we’re on the timeout topic, I have to try: would Travis be willing to lifting our timeout restrictions? Or just raise it to 2h? Pretty please.

Thank you,
Sérgio

**Comment by eserte** [comment]
I also see the slowness. My workaround is to reduce the quietness in the `apt-get` calls from `-qq` to `-q`.

**Comment by SergioRAgostinho** [comment]
This incident report seems to describe an equivalent situation 
https://www.traviscistatus.com/incidents/j7t8wd3c6qny

**Comment by shlomif** [comment]
I am getting it here - https://travis-ci.org/shlomif/perl-begin .

**Comment by BanzaiMan** [comment]
Please subscribe to this issue https://www.traviscistatus.com/incidents/k35bqcmm5274

I'm closing this issue, as the status page above gets all the relevant updates. Thanks.
