### ISSUE TITLE
$TRAVIS_COMMIT_MESSAGE does not match custom commit message when triggering custom build

### ISSUE THREAD

**Issue by maxnorth** [travis-ci/travis-ci#10184]
When triggering a custom build via the dashboard 'More Options > Trigger build' feature, if I specify a custom commit message for the build it does not use this value for the $TRAVIS_COMMIT_MESSAGE environment variable, it uses the commit message for the last pushed commit of the specified branch.

**Comment by BanzaiMan** [comment]
Duplicate of #8641.
