### ISSUE TITLE
OSX build fails without error message

### ISSUE THREAD

**Issue by jmatsushita** [travis-ci/travis-ci#10199]
Hi there,

The deploy stage of my build fails at various random points when I restart it for instance:
 - https://travis-ci.org/iilab/mobile/jobs/438506170

I imagine it might be a silent out of memory problem but it would be great if you could confirm or spot another problem.

Cheers,

Jun

**Comment by BanzaiMan** [comment]
Do you know which of [this long string of commands](https://github.com/iilab/mobile/blob/77d60237c41093b68b365b6cf2e669d942594941/.travis.yml#L26-L37) is failing? Does it fail consistently at the same spot?

Would you like to have the debug feature enabled for this repository to troubleshoot further?

**Comment by jmatsushita** [comment]
This isn’t relevant anymore but I’ll reopen if I bump into it again.
