### ISSUE TITLE
dashboard doesn't make it easy to star repos

### ISSUE THREAD

**Issue by jsoref** [travis-ci/travis-ci#10191]
https://travis-ci.org/dashboard

> Starred repositories
> ☆ You can keep track of your favorite repositories here once you start starring!

*Active repositories* | Recent builds
-| -

project / repo | DEFAULT BRANCH | LAST BUILD | COMMIT | FINISHED
-| - | - | - | -
☆ perl6 / doc | master passed | #7653 passed | 6836deb | about 9 hours ago
... (a bunch of perl repos, I'm a member of other orgs, and have hundreds of other forked projects)

Active repositories | *Recent builds*
-| -

📚 | ? | project / repo | commit | pr / commit | time / status
-| - | - | - | - | -
📚 | ∞ | PowerDNS / pdns | travis: complain about dangling symlinks / master | #13968 started /  54d119f  | 22 min 54 sec / still running
📚 | ❗| PowerDNS / pdns | configure: enable-dnstap / master | #13967 errored /  c1d35f0 | 1 hr 47 sec / 7 minutes ago
📚 | ✅ | PowerDNS / pdns | Update readme for debian 9 /  master | #13944 passed / fb5648b | 49 min 52 sec / about 16 hours ago
...

Expected results:
1. I should be able to star a repo from the Recent builds view
2. I should be able to search/filter in both Active repositories and Recent builds (so that I can star)

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
