### ISSUE TITLE
Travis API v3 Build Ignores Environment Variables

### ISSUE THREAD

**Issue by imann24** [travis-ci/travis-ci#10192]
I'm trying to submit an API v3 request to run a build in Travis Enterprise. However, the request ignores the environment variable I specify. Is this an issue with my request body format? The documentation suggests this format should succeed: https://docs.travis-ci.com/user/triggering-builds/#customizing-the-build-configuration

```bash
export REPO_BRANCH=xxxxxxx
export ENV_VAR_VALUE=xxxxxxx

BODY="{
  \"request\": {
    \"branch\":\"$REPO_BRANCH\"
  },
  \"config\": {
    \"merge_mode\":\"deep_merge\",
    \"env\": {
       \"global\":[\"ENV_VAR_NAME=$ENV_VAR_VALUE\"]
    }
  }
}"

curl -v -s -X POST \
   -H "Content-Type: application/json" \
   -H "Accept: application/json" \
   -H "Travis-API-Version: 3" \
   -H "Authorization: token xxxxx" \
   -d "$BODY" \
   https://api.travis-ci.com/repo/orgname%2Freponame/requests
```

**Comment by BanzaiMan** [comment]
For enterprise support issues, please email us at enterprise@travis-ci.com. There are some crucial details that might be missing, so we should take this issue to support ticket.

Thank you.
