### ISSUE TITLE
Travis queue much slower for private repos

### ISSUE THREAD

**Issue by AllanWang** [travis-ci/travis-ci#10196]
Lately, Travis has been quite slow for all of my builds. However, I've noticed that if I restart both a private and public repo, the public one will start running after a minute, while the private one is stuck (queued for 10 minutes now). Both are using `travis-ci.com`.

Is this expected behaviour? What is causing all the builds to be slower than before? It used to take a few seconds to launch each build from the queue, and it looks like there are no project backlogs.

**Comment by BanzaiMan** [comment]
Your `McGill-ECSE429` repo shares the queue with your classmates, so your particular job is waiting for its turn. I hope this makes sense.

**Comment by AllanWang** [comment]
Oh so queues are also per organization? Thanks!

**Comment by BanzaiMan** [comment]
I've increased the bandwidth for the `McGill-ECSE429` organization for the next few hours, so hopefully your assignments can be finished in a timely manner.
