### ISSUE TITLE
timeout on `apt-get install` 

### ISSUE THREAD

**Issue by dilawar** [travis-ci/travis-ci#10208]
I've been facing this issue for couple of days now. The build timeouts when running 
`sudo python-scipy python-networkx python-tk python-matplotlib -qq`
Detailed log is here: https://api.travis-ci.org/v3/job/438960257/log.txt

**Comment by BanzaiMan** [comment]
See https://www.traviscistatus.com/incidents/tm5zr8swzqmq

This should be resolved now.

**Comment by BanzaiMan** [comment]
Thanks for the information. Please subscribe to the new issue. https://www.traviscistatus.com/incidents/k35bqcmm5274

**Comment by colincadams** [comment]
this seems to be recurring again ([log]), but there isn't an open incident. Is this failure automatically monitored?

[log]: https://api.travis-ci.org/v3/job/502107653/log.txt
