### ISSUE TITLE
Feature-Request: Pass the origin's Repository Settings alongside Pull Requests

### ISSUE THREAD

**Issue by duanehutchins** [travis-ci/travis-ci#10207]
The issue: Cannot accurately test Pull Requests from outside repositories when the Travis-CI tests require secure environment variables.

Proposal: If the origin of the PR has environment variables in its Repository Settings, include those variables for the Travis-CI tests.

Example: 
* I created commit https://github.com/duanehutchins/heroku-buildpack-python/commit/f7680abc266ef8797b7cb1c8aecef319e69b0b0e
* Travis-CI includes the environment variables from my repo's Repository Settings: https://travis-ci.com/duanehutchins/heroku-buildpack-python/settings
* That commit passes CI: https://travis-ci.com/duanehutchins/heroku-buildpack-python/builds/87256182
* Same commit is used in PR: https://github.com/heroku/heroku-buildpack-python/pull/766
* Travis-CI does not include the environment variables from my repo's Repository Settings
* PR (same commit) fails CI because of missing environment variables: https://travis-ci.org/heroku/heroku-buildpack-python/jobs/438849455#L561

If Travis-CI included my repo's Repository Settings when testing PR originating from my repo, then that PR would have passed CI.

To distinguish something, PR-Target envs still won't be included because the PR can expose the secure envs.  I'm only proposing that we include PR-Origin envs because the Origin of the PR will control the code which is being tested through CI.

This maintains security because the origin of the PR is aware (or should be aware) of the Travis-CI tests prior to sending the PR.

Alternatively, if the commit has already passed CI (as in the example above), then skip CI tests on PR.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by duanehutchins** [comment]
Thanks. Copied to here: https://travis-ci.community/t/pass-the-pr-origins-repository-settings-alongside-github-pull-request/1347
