### ISSUE TITLE
Travis reports "Expected - Waiting for status to be reported" even after build succeeds

### ISSUE THREAD

**Issue by austinbes** [travis-ci/travis-ci#10203]
I'm seeing the following on every pull request in a private repo that I'm managing:

![travis_blocked](https://user-images.githubusercontent.com/16393328/46628132-d8eedb80-caf9-11e8-9318-34eacaa95a97.png)

The build (as you can see above) is passing. It's been in this state for about 3 days.

What steps can I take to troubleshoot this? Is there any more information I can provide?

**Comment by BanzaiMan** [comment]
Hello, there. I've written #10204 with a more direct explanation.
