### ISSUE TITLE
Travis CI reports "Expected - Waiting for status to be reported" on the GitHub Status API, but the status never arrives

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#10204]
# Symptom

Your repository stopped receiving status updates. In your PR, you see something like this:

![46544692-94c6c580-c8c4-11e8-9d8c-d667e32f3cba](https://user-images.githubusercontent.com/25666/46628906-1c067a00-cb0d-11e8-8f1d-e6bfbcdd5567.png)

# Explanation

As part of our gradual migration to the Travis CI GitHub App, that now uses GitHub Checks to report build statuses, we kept posting both GitHub Checks as well as the old commit statuses for some time to not break repositories using the commit statuses in their protected branches settings and give time to do the change to use the new Checks instead.

[As of October 4th](https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories), those repositories on [travis-ci.com](https://travis-ci.com) which are managed by GitHub Apps no longer receive updates to the GitHub Commit Status API. Instead, Build Statuses will be posted to the GitHub Check Runs API.

# Remedy

To fix this issue, update your repositories using protected branches to require GitHub Checks as follows:

1. Go to the repository’s Branch Settings page (https://github.com/OWNER/REPO/settings/branches).
1. In the "Branch Protection Settings" section, click "Edit" for a protected branch
1. Scroll down to the second box, "Require status checks to pass before merging." Select either "Travis CI - Pull Request" or "Travis CI - Branch" or both. (Note: "continuous-integration/travis-ci" is the Status API event which is deprecated)
1. Save your changes

**Comment by BanzaiMan** [comment]
See also: https://github.com/travis-ci/travis-ci/issues/9618.

**Comment by DrTorte** [comment]
Thread on the forum is here: https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

Closing issue, in favour of forum topic. :)
