### ISSUE TITLE
skipping brew update on R builds

### ISSUE THREAD

**Issue by smsaladi** [travis-ci/travis-ci#10206]
I'd like to skip `brew update` on my R builds. I think it's unnecessary for my purposes, and it takes a long time. However, I'm not sure exactly where to specify this...

Looking in the build file, it looks like the `brew update` might be baked in (though my understanding may be incorrect).

https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb#L120-L124

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
