### ISSUE TITLE
Please close issue #9618

### ISSUE THREAD

**Issue by levrik** [travis-ci/travis-ci#10214]
Can you please close this issue?
Since you locked it to collaborators I cannot close it and I would like to get rid of this issue from my open issues list on GitHub 🙂

**Comment by BanzaiMan** [comment]
Sorry, but that issue is not resolved.

**Comment by levrik** [comment]
@BanzaiMan 

![image](https://user-images.githubusercontent.com/9491603/46745973-5b200100-ccae-11e8-9723-bd49a67c3d12.png)
It's literally written on that ticket that it's resolved. Besides that the Status API isn't used anymore.
You posted a link to a blog entry which states that the Status API isn't used anymore starting on October 4th.
So, again. Why can't this be closed?
