### ISSUE TITLE
Mono msbuild downgraded from 15.6.0.0 to 15.1.8.0

### ISSUE THREAD

**Issue by guryanovev** [travis-ci/travis-ci#10219]
Few days ago our build (language: csharp, dotnet: 2) start failing with the message:

> Version 2.WHATEVER_FROM_YML of the .NET Core SDK requires at least version 15.3.0 of MSBuild. The current available version of MSBuild is 15.1.8.0. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.

And about a week ago it worked. We realized the msbuild version is 15.1.8.0 right now but few days ago it was 15.6.0.0. It looks like mono has been updated while msbuild downgraded:

**Now, failing**:

 * Mono JIT compiler version 5.16.0.179
 * Microsoft (R) Build Engine version 15.1.8.0

**A week ago, passing**:

 * Mono JIT compiler version 5.14.0.177
 * Microsoft (R) Build Engine version 15.6.0.0

Is it possible new mono 5.16 comes with old msbuild 15.1? I tried changing dotnet version but it seems to have no effect.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
