### ISSUE TITLE
Multiple PRs from today report "continuous-integration/travis-ci Expected — Waiting for status to be reported "

### ISSUE THREAD

**Issue by jeremychinquistdrunomicscom** [travis-ci/travis-ci#10215]
Good day,

Yesterday we completed https://github.com/BurdaMagazinOrg/burda-ms-web/pull/55 and wanted to merge this. The Travis build has somehow been re-triggered but it was green 15 minutes ago. **The message "continuous-integration/travis-ci Expected — Waiting for status to be reported" does not go away.**

To test, we also created https://github.com/BurdaMagazinOrg/burda-ms-web/pull/56 and this is reporting the same thing.

Communication between Github / Travis was working yesterday. Can someone take a look at this? 

Thank you.

**Comment by BanzaiMan** [comment]
If your PR requires a commit status API to post to a protected branch, please read #10204 and [this blog post](https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories).

**Comment by jeremychinquistdrunomicscom** [comment]
Thank you. We followed the blog post and will accept that. Closing the ticket.
