### ISSUE TITLE
Detect default merge commit message and allow skipping building such a commit

### ISSUE THREAD

**Issue by dabit1gamma** [travis-ci/travis-ci#10216]
I'm having some troubles when I want to skip ci. For example, if I commit changes and the message has [ci skip] but when I try to push git requires me to make a pull then git will create a merge commit message which does not have [ci skip] so TravisCI is going to be triggered. What can I do in that cases?

**Comment by BanzaiMan** [comment]
When you merge PR on GitHub's web UI, you have a chance to edit the commit title and the message. Add the command then.

![testing_pr_builds_by_banzaiman_ _pull_request__70_ _banzaiman_travis_production_test](https://user-images.githubusercontent.com/25666/46734881-7f55f080-cc62-11e8-8629-b2094484b5af.png)

**Comment by BanzaiMan** [comment]
I suggest editing the commit after the merge, then. You have to inject the `[skip ci]` command somehow.

**Comment by dabit1gamma** [comment]
Thanks for the suggestion but it is a expensive task.. should be an easier solution

**Comment by BanzaiMan** [comment]
I'm sorry that you feel that way, but the commit message that you are setting (by default or not) lacks the command to instruct Travis to skip running.

**Comment by BanzaiMan** [comment]
Is it fair to say that you want Travis CI to automatically detect merge commit message in a certain form and skip it?

**Comment by dabit1gamma** [comment]
Exactly. Actually I'm using TravisCI to make continuous translation. And to complete the whole process I need that Weblate (backoffice to translating) commit and push to git. The problem is that sometimes it make a commit for merging after the commit message where has a key in order to skip a lot of unnecessary tasks.

**Comment by BanzaiMan** [comment]
This would require some not insignificant amount of work, so it will take some amount of time to prioritize, assess, and implement if we choose to implement this feature. In the mean time, I suggest you continue to explicitly instruct Travis CI to skip the build.

**Comment by dabit1gamma** [comment]
thanks @BanzaiMan !
