### ISSUE TITLE
No POM in project directory

### ISSUE THREAD

**Issue by fincardona** [travis-ci/travis-ci#10217]
Hello,

I have a build that takes longer than 10 minutes without producing any output so I'm trying to increase the waiting time by following these instructions: [https://docs.travis-ci.com/user/common-build-problems/#my-builds-are-timing-out](url) but I obtain the following error:

`[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/travis/build/fincardona/ScanningTools.py). Please verify you invoked Maven from the correct directory. -> [Help 1]`

I tried also to follow the suggestions of `[Help 1]` at link [https://cwiki.apache.org//confluence/display/MAVEN/MissingProjectException](url)
but I can't find where my `pom.xml` file is.

That's the link to my project: https://github.com/fincardona/ScanningTools.py
Thanks a lot

**Comment by BanzaiMan** [comment]
Is this still an issue? https://travis-ci.com/fincardona/ScanningTools.py/builds/89156950 passed.
