### ISSUE TITLE
Builds Hanging on Booting or Finding Network Availability

### ISSUE THREAD

**Issue by pr1ntr** [travis-ci/travis-ci#10228]
https://travis-ci.com/wildlifela/leaderboard-core

Seems like the internet availability is intermittent at best. not sure whats up.

**Comment by BanzaiMan** [comment]
Hello, there. Thanks for the report. We have opened https://www.traviscistatus.com/incidents/zmw37lfzk3p3 to keep track of this issue. Please subscribe to it, as we will post any update there.

In the meantime, I will close this issue.

**Comment by pr1ntr** [comment]
ty
