### ISSUE TITLE
Travis CI build does not start

### ISSUE THREAD

**Issue by shamrose** [travis-ci/travis-ci#10220]
Hello,
My Travis CI builds do not start. I had pushed my code to GitHub yesterday and the Travis CI shows "No builds for this repository". I have enabled the Travis CI on my Github repositories. Can anyone help me resolve the issue? 
Thanks in advance

**Comment by cotsog** [comment]
Could you tell us what's the name of your repository and if it's open source or private?

Could you also look into your build requests? This page is available in the "More options" menu. See below:


![screen shot 2018-10-10 at 12 54 42](https://user-images.githubusercontent.com/149366/46763478-ed70d680-cca7-11e8-92da-3d2b8337597c.png)

Thanks!

**Comment by cotsog** [comment]
Everything looks good on our side. Could you try to push a new commit so we can inspect our logs?

**Comment by LucaPaterlini** [comment]
can you please point to a guide on how to store the compiled executable on s3 in differnt folders depending of the different  jobs?

**Comment by shamrose** [comment]
> Everything looks good on our side. Could you try to push a new commit so we can inspect our logs?

@cotsog, My build is working fine now! I have one more repository that have the same issues. Is there any specific reason as to why the build is not working for the repositories?
Links for the repository is https://travis-ci.com/uno-isqa-4900/activity3-shamrose

Thank you so much!

**Comment by cotsog** [comment]
@shamrose It should be the same with this other repo. Just push a new commit and it should trigger a build. Please re-open this issue if it's not the case. Thanks!
