### ISSUE TITLE
guide on how to set up a development environment

### ISSUE THREAD

**Issue by DasBlub** [travis-ci/travis-ci#1022]
as discussed with @joshk it'd be really nice to have a guide on how to set up a local development environment so that people can actually contribute something back to travis!
that'd guide at least needs the following information:
* requirements for compiling & running travis (software, hardware, environment(s))
* steps to get the source code (which repositories are required, where does one need to put them)
* steps to compile the code
* steps to start up travis
* a nice reminder to contribute back to travis using pull requests :)

without such a guide there's too high a barrier for people to get a development environment running and they won't contribute back to travis

**Comment by BanzaiMan** [comment]
We have split up travis-ci/travis-ci into many smaller applications. I think it is safe to say that this issue has become stale. I am closing this.
