### ISSUE TITLE
retrieve executable files after the build

### ISSUE THREAD

**Issue by LucaPaterlini** [travis-ci/travis-ci#10223]
can you please point to a guide on how to store the compiled executable on s3 in different folders depending on the different jobs?

**Comment by LucaPaterlini** [comment]
https://travis-ci.org/LucaPaterlini/dash/jobs/439997392
now the dependencies do not get installed,

**Comment by LucaPaterlini** [comment]
Installing deploy dependencies
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.15.3
Successfully installed public_suffix-3.0.3
Successfully installed addressable-2.5.2
Successfully installed sawyer-0.8.1
Successfully installed octokit-4.6.2
Successfully installed mime-types-2.99.3
Successfully installed dpl-releases-1.10.3
8 gems installed
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/authorizations.rb:125:in `scopes': Access token required (ArgumentError)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.10.3/lib/dpl/provider/releases.rb:85:in `check_auth'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.3/lib/dpl/provider.rb:184:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.3/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.3/lib/dpl/provider.rb:183:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.3/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.3/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.3/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'

**Comment by BanzaiMan** [comment]
There are a few deployment provider that can do this https://docs.travis-ci.com/user/deployment/, or you can use `artifacts` https://docs.travis-ci.com/user/uploading-artifacts/

**Comment by BanzaiMan** [comment]
As for your error, you need to provide GitHub token with appropriate scope, as indicated in the error message. https://travis-ci.org/LucaPaterlini/dash/jobs/439997392#L2563

**Comment by LucaPaterlini** [comment]
hello, can you please explain what do you mean with excepting? i have no special character and I have hadded GU and GP in settings with my email and GP with password (in password format) with no" at the begin and at the end and with no special characters

**Comment by BanzaiMan** [comment]
Ah, I see. Looks like we introduced a hard requirement about using API token instead of username+password a while back (4.5 years ago, as far as I can tell). It is surprising (and also encouraging) that no one has reported this issue until now.

At any rate, could you try using an API token instead?

Thanks.

**Comment by LucaPaterlini** [comment]
https://travis-ci.org/LucaPaterlini/dash/jobs/440149011
https://github.com/LucaPaterlini/dash/releases

build marked as successful, nothing received on GitHub

**Comment by BanzaiMan** [comment]
Is there anything in [`/src/dashd`](https://github.com/LucaPaterlini/dash/blob/fee5567393182cdf5e8bdef8b0f99d92d523c229/.travis.yml#L16)?

**Comment by LucaPaterlini** [comment]
its the supposed compile file, how can I get the list of files generated by the build?
what is the base path to refer the compiled files?

**Comment by LucaPaterlini** [comment]
https://github.com/LucaPaterlini/dash/tree/master/src 
this is the folder where the file is going to be created after the build 
its name is dashd
so I am not getting what I am missing about the path and what is the working directory of the script

**Comment by BanzaiMan** [comment]
`/src/dashd` is an absolute path, and probably does not exist and I suspect your deployment is not uploading any file. What you probably want is `src/dashd`, assuming that your build doesn't change working directory during the build.

**Comment by LucaPaterlini** [comment]
src/dashd is what I have tested in the latest build 

https://travis-ci.org/LucaPaterlini/dash/builds/440185098

**Comment by LucaPaterlini** [comment]
https://travis-ci.org/LucaPaterlini/dash/builds/441296117

In this buildi am searching for the file and those are not there. I am not understaning why. The make as been done successfully and the skip clean is set to true

**Comment by BanzaiMan** [comment]
Are you sure that the file exists before the deployment?

**Comment by LucaPaterlini** [comment]
How can I be sure, I am Getting more. And more. Confused. I have seen make executed. Can you explain what to do?

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/customizing-the-build/#the-build-lifecycle Use `before_deploy` to check.

I also advise against putting the GitHub API token in the build log (via Settings); please revoke the one shown in the build logs for security.

**Comment by LucaPaterlini** [comment]
https://travis-ci.org/LucaPaterlini/dash/jobs/441409995

so even if I have seen the make complete successfully, the files have not being
created, I have done as you have suggested with the before_deploy label

**Comment by BanzaiMan** [comment]
https://travis-ci.org/LucaPaterlini/dash/jobs/441409995#L2537 Don't you want to look at `ls src` instead?

**Comment by iriberri** [comment]
Hi @LucaPaterlini - thanks for your patience and sorry for the hassle.

I created a version of the Releases deployment provider that will add some extra output in the log about the files to be uploaded: https://github.com/travis-ci/dpl/commit/195d7e8407dc21bfc09c7c36c713bc89bfedf4fe

To try this, could you please use the following deploy section in your .travis.yml:

```
deploy:
  provider: releases
  edge:
    branch: ci-releases_debug
  api_key: $OT
  file: "build/dashcore-$HOST/dashd"
  skip_cleanup: true
```

and share a resulting build with us?

Thank you!

**Comment by LucaPaterlini** [comment]
those are the results

https://travis-ci.org/LucaPaterlini/dash/jobs/441560120

**Comment by LucaPaterlini** [comment]
https://travis-ci.org/LucaPaterlini/dash/jobs/441580964#L2495
as shown here the compiled files are there,
now the missing part remains getting those on the github release

**Comment by BanzaiMan** [comment]
Is this what you want? https://github.com/LucaPaterlini/dash/releases/tag/untagged-99b23c4536c54496b193

**Comment by LucaPaterlini** [comment]
yes thanks for your answers

**Comment by BanzaiMan** [comment]
I suggest revoking [this GutHub token](https://travis-ci.org/LucaPaterlini/dash/jobs/441580964#L490), generating a new one and keeping it hidden.

**Comment by LucaPaterlini** [comment]
tk for the suggestion, I will on completion, now I am tring to upload the entire folder but I am not getting any resoult or error

**Comment by iriberri** [comment]
@LucaPaterlini to avoid that the dashd file for each deployment overwrites itself you'd need to rename it for each job. You can do this in the before deploy section and although I haven't tried it the following, or similar, should help:


```
before_deploy:
-  mv build/dashcore-$HOST/dashd build/dashcore-$HOST/dashd-$HOST

deploy:
  provider: releases
  api_key: $OT
  file: "build/dashcore-$HOST/src/dashd-$HOST"
  skip_cleanup: true
```

Let us know how it goes!
