### ISSUE TITLE
ENH: Provide `conda` and `conda-build`

### ISSUE THREAD

**Issue by pitrou** [travis-ci/travis-ci#10225]
In the Python community, particularly in data analysis / science orientated fields, `conda` has seen a great deal of success. This in no small part due to how it is able to easily install commonly used packages like the SciPy Stack ( http://www.scipy.org/stackspec.html ) on any platform. It is even given attention PyPA ( http://python-packaging-user-guide.readthedocs.org/en/latest/science/?highlight=conda#the-conda-cross-platform-package-manager ). As a consequence, many projects install conda as part of the build process. In order to speed up build times across the board and provide some better functionality, it would be nice to provide `conda` out of the box.

A possible way to do that is to provide a [miniconda](https://conda.io/miniconda.html) install. AppVeyor for example even provides [several versions](https://www.appveyor.com/docs/windows-images-software/#miniconda). So does Azure Pipelines on their [Linux](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md), [Windows](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md) and [macOS](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-Readme.md) hosted images.

(re-opened from #4883 which was closed by a bot)

**Comment by DrTorte** [comment]
Hello,

As we're no longer supporting GitHub issues but this issue remains open, I'm creating a copy of this on the forum. [Please see this link](https://travis-ci.community/t/enh-provide-conda-and-conda-build-10225-migrated-from-issues/1130).

Thanks and happy building!
