### ISSUE TITLE
Travis CI C# support fails after upgrade to new version of Mono

### ISSUE THREAD

**Issue by uxmal** [travis-ci/travis-ci#10221]
The CI builds for https://github.com/uxmal/reko started failing today. The error is:

/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(3066,5): error MSB4018: The "GenerateResource" task failed unexpectedly. [/home/travis/build/uxmal/reko/src/UserInterfaces/WindowsForms/WindowsForms.csproj]
(see line 3165 of https://travis-ci.org/uxmal/reko/builds/439845093)

The last successful build had the following Mono runtime:
```
Mono JIT compiler version 5.14.0.177 (tarball Mon Aug  6 09:14:27 UTC 2018)
```
The failing builds have the following runtime version
```
Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 10:27:11 UTC 2018)
```
@joshua-anderson @akoeplinger @nterry

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
