### ISSUE TITLE
build fails when .vscode is added to .gitignore

### ISSUE THREAD

**Issue by jperelshteyn** [travis-ci/travis-ci#10227]
Build failed with:
`fatal: not in a git directory`
when I added the following line to .gitignore file:
`.vscode/`
After commenting it out:
`# .vscode/`
build succeeded

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by BanzaiMan** [comment]
Is this a build running on Windows? If so, please close this issue and open a new topic in https://travis-ci.community/c/windows

If not, please indicate build log URLs that exhibits this behavior.

Thanks.

**Comment by jperelshteyn** [comment]
This is for a private repo. So I am closing the issue and sending the details through email.
