### ISSUE TITLE
PR failed the build on Travis CI but didn't get a failed build linked to it

### ISSUE THREAD

**Issue by zeux** [travis-ci/travis-ci#10235]
This PR:

https://github.com/zeux/pugixml/pull/235

Had a build automatically triggered on Travis CI which failed:

https://travis-ci.org/zeux/pugixml/builds/440812205

However, the failed build didn't get reflected in the PR status - PR says "All checks have passed" and only mentions 3 checks, even though there should be 4 (2 codecov, 1 travis, 1 appveyor - travis check should've failed).

**Comment by BanzaiMan** [comment]
Hello, there.

I looked at the logs, and it appears that our integration with GitHub at the time when https://travis-ci.org/zeux/pugixml/builds/440812205 ran was broken. The data have since been synchronized and reconciled.

**Comment by zeux** [comment]
Thanks!

**Comment by BanzaiMan** [comment]
I think that when we migrate to .com and have all repositories use GitHub Apps, this sort of auth issues will be less frequent.
