### ISSUE TITLE
Windows builds consistently running out of space

### ISSUE THREAD

**Issue by joshuef** [travis-ci/travis-ci#10239]
Hey gang,

I'm trying to test out the windows CI functionality, and after a wee glitch with python paths / nodejs, now I'm consistently seeing:

`ENOSPC: no space left on device`

This isn't an issue with linux/osx builds, so I'd be surprised if windows was significantly larger... not sure what's going on.

Reference builds:

https://travis-ci.org/joshuef/safe_browser/jobs/441430411

**Comment by BanzaiMan** [comment]
As described in the blog post, please open an issue at https://travis-ci.community/c/windows for Windows-related issues.

**Comment by BanzaiMan** [comment]
Your issue is already noted in https://travis-ci.community/t/build-non-deterministically-fails-with-there-is-not-enough-space-on-the-disk/350

**Comment by joshuef** [comment]
Ah, apologies. That's not so clear from the blogpost (just had a re-read also). May I suggest adding something explicit to the post for 'filing Windows Issues' or some such.

Thanks for the swift response/details 👍  though. Keep up the good work!
