### ISSUE TITLE
Build stalls on Windows for some projects

### ISSUE THREAD

**Issue by gkalpak** [travis-ci/travis-ci#10231]
I tried out `os: windows` (:tada: :100: 👌) on some of my projects.

🙂 For most of the projects, the jobs run fine.
🙁 But for two projects, [this][1] and [that][2], the jobs never go part the "Worker information" step (and timeout after 10mins).

This is the whole output for all Windows jobs of those two projects:

```
Worker information
hostname: 8919714d-449f-4e78-a75f-71dcb1796c25@1.production-1-worker-org-gce-lq0q
version: v4.4.0 https://github.com/travis-ci/worker/tree/80d1a9bbc1de0f176c56230ce9cc27f45ff1eb27
instance: travis-job-fbd9b74c-8b8a-44a3-bc87-efdf91c59808 travis-ci-onion-1803-containers-1539283311-7f6c426 (via amqp)
startup: 12.144394705s
```

Notes:
- I tried restarting the builds and jobs several times, to no avail.
- I tried pushing more commits (to create new builds), same result.
- I am using the exact same `.travis.yml` in other projects (e.g. [this][1]) and the Windows jobs run fine.

[1]: https://travis-ci.org/gkalpak/ng-cla-check
[2]: https://travis-ci.org/gkalpak/ng-pr-merge
[3]: https://travis-ci.org/gkalpak/aliases

**Comment by gkalpak** [comment]
Actually, I just realized one thing that the two failing projects have in common (and the passing ones don't have) is that they (the failing ones) have environment variables set in TravisCI settings.

Apparently, having an env var there causes the Windows builds to crash 😞

**Comment by BanzaiMan** [comment]
Hello, there. Please use https://travis-ci.community/c/windows for Windows support. Thanks. I'm closing this.

**Comment by gkalpak** [comment]
Ooops, sorry, missed that. Thx for pointing out.

**Comment by BanzaiMan** [comment]
No worries. Thanks for testing Windows on Travis CI!
