### ISSUE TITLE
Failed to run jdk10 on travis.

### ISSUE THREAD

**Issue by chickenlj** [travis-ci/travis-ci#10249]
https://github.com/apache/incubator-dubbo/blob/bfa179580358efdf3abb9aa89e78cdc2c8d05ed8/.travis.yml#L5

Setting APT mirror in /etc/apt/sources.list: http://archive.ubuntu.com/ubuntu/
$ export JAVA_HOME=${TRAVIS_HOME}/oraclejdk10
$ bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk
install-jdk.sh 2018-10-16
Variables:
  feature = 10
  license = BCL
       os = linux-x64
      url = http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz
   status = 302
  archive = /home/travis/.cache/install-jdk/jdk-10.0.2_linux-x64_bin.tar.gz
Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz...
**The command "bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk" failed and exited with 8 during .**
Your build has been stopped.

**Comment by ripcurlx** [comment]
We experience the same issue since yesterday 😞. Worked before without any problems.

**Comment by micheljung** [comment]
This happens and will probably continue to happen every few weeks/months. Might be worth automating a solution

**Comment by axel1200** [comment]
Same for me

**Comment by BanzaiMan** [comment]
`install-jdk.sh` has been updated to the latest version. Could you restart your builds?

**Comment by seize-the-dave** [comment]
It's still not working.  Version number looks fine, but it's just not downloading. 

See https://travis-ci.org/jscep/jscep/jobs/442596882

**Comment by silvez-dh** [comment]
Still happening:

> Setting APT mirror in /etc/apt/sources.list: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
$ export JAVA_HOME=${TRAVIS_HOME}/oraclejdk10
$ bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk
install-jdk.sh 2018-10-16
Variables:
  feature = 10
  license = BCL
       os = linux-x64
      url = http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz
   status = 302
  archive = /home/travis/.cache/install-jdk/jdk-10.0.2_linux-x64_bin.tar.gz
Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz...
The command "bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk" failed and exited with 8 during .
Your build has been stopped.

**Comment by BanzaiMan** [comment]
Sorry about that. We'll take a deeper look shortly.

**Comment by BanzaiMan** [comment]
I'll take further discussion to https://travis-ci.community/t/help-with-oraclejdk10-build-on-linux/398 (to encourage all of you to check out the community site. 😉)

**Comment by lukehutch** [comment]
It looks like both JDK 9 and JDK 10 have been superseded as temporary "stop-gap" releases on the way to JDK 11 LTS, and they're not coming back. Probably that won't happen with JDK 12+ now that things have stabilized a lot.
