### ISSUE TITLE
run-checks.sh Permission Denied

### ISSUE THREAD

**Issue by Geraldcdx** [travis-ci/travis-ci#10244]
```sh-session
$ ./gradlew assemble
Welcome to Gradle 4.8.1!
Here are the highlights of this release:
 - Dependency locking
 - Maven Publish and Ivy Publish plugins improved and marked stable
 - Incremental annotation processing enhancements
 - APIs to configure tasks at creation time
For more details see https://docs.gradle.org/4.8.1/release-notes.html
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.8.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
> Task :compileJava
> Task :copyStylesheets
> Task :asciidoctor
io/console on JRuby shells out to stty for most operations
> Task :deployOfflineDocs
> Task :processResources
> Task :classes
> Task :jar
> Task :startScripts
> Task :distTar
> Task :distZip
> Task :shadowJar
> Task :startShadowScripts
> Task :shadowDistTar
> Task :shadowDistZip
> Task :assemble
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 27s
13 actionable tasks: 13 executed
0.00s$ ./config/travis/run-checks.sh && travis_retry ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidoctor copyDummySearchPage
/home/travis/.travis/job_stages: line 104: ./config/travis/run-checks.sh: Permission denied
```

Hi! I can't seem to get rid of this error at all, would appreciate if there is some link or some commands you could point me to :)

**Comment by BanzaiMan** [comment]
Please double check `./config/travis/run-checks.sh` has the execute permission.

**Comment by Geraldcdx** [comment]
@BanzaiMan 
`#!/bin/sh
# Runs all check-* scripts, and returns a non-zero exit code if any of them fail.

dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd) &&
ret=0 &&
for checkscript in "$dir"/check-*; do
    if ! "$checkscript"; then
        ret=1
    fi
done
exit $ret`

Sorry im quite new to the script, what do i add?

**Comment by BanzaiMan** [comment]
@Geraldcdx Are you familiar with the concept of executable scripts? On your local development machine, you'd run

    chmod +x config/travis/run-checks.sh

and commit that file.

If you are taking a class somewhere, I suggest getting help from someone with whom you can talk directly, perhaps your instructor, a classmate, or a tutor. You will learn much quickly than going back and forth here.

**Comment by Geraldcdx** [comment]
The command below works for me! @BanzaiMan Thanks so much
`git update-index --chmod +x config/travis/run-checks.sh`

**Comment by BanzaiMan** [comment]
@Geraldcdx Great to hear. I'm closing this now.
