### ISSUE TITLE
push to repository does not trigger a build

### ISSUE THREAD

**Issue by vladak** [travis-ci/travis-ci#10243]
Since couple of months ago push to our (public) repository https://github.com/devnull-cz/unix-linux-prog-in-c does not trigger Travis build anymore. I tried to follow 
https://blog.travis-ci.com/2014-05-12-why-is-my-build-not-running however there is nothing new in 
https://travis-ci.org/devnull-cz/unix-linux-prog-in-c-src/requests , `travis lint` does not find any major problems, Travis is enabled in repository settings etc. It just looks as if Github was not doing any API requests to Travis. Is there a way how to debug this further ?

**Comment by vladak** [comment]
There is one discrepancy - if I list the repositories in https://travis-ci.org/organizations/devnull-cz/repositories , the repo is listed under 'Legacy Services Integration' while https://github.com/devnull-cz/unix-linux-prog-in-c/settings/installations shows empty 'Services' section and Travis is only listed in 'Installed GitHub Apps' section.

If I created new repo afresh https://github.com/devnull-cz/test and it got enabled on travis-ci.com (not org) and there the builds are triggered just fine.

When I tried to display https://github.com/devnull-cz repositories on https://travis-ci.com/organizations/devnull-cz/repositories it says the following for https://github.com/devnull-cz/unix-linux-prog-in-c (but not for https://github.com/devnull-cz/test)
> The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org. 
so I wonder if https://github.com/devnull-cz/unix-linux-prog-in-c became a viction of this transition.

**Comment by BanzaiMan** [comment]
The repository's webhook was stale. I've reset it. Please try pushing a new commit. https://travis-ci.org/devnull-cz/unix-linux-prog-in-c should get a new build.

**Comment by vladak** [comment]
Works now, thanks. 

Is there a way how at least some amount of observation from the outside could be added to either Github or Travis ?
