### ISSUE TITLE
Can't upload artifacts to GitHub from Windows

### ISSUE THREAD

**Issue by dmerejkowsky** [travis-ci/travis-ci#10241]
Example here: https://travis-ci.org/SuperTanker/ruplacer/jobs/441707116

```
if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then c/python37/python.exe gen_artifacts.py --version $TRAVIS_TAG --platform windows ; fi
Python script OK
...

$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl

The command "rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl" failed and exited with 127 during .
Your build has been stopped.
    Finished release [optimized] target(s) in 0.16s
/c/Users/travis/.travis/job_stages: line 164: rvm: command not found
```

**Comment by BanzaiMan** [comment]
As indicated in the blog, please redirect your Windows-related issues to https://travis-ci.community/c/windows. In particular, your issue has been reported as https://travis-ci.community/t/rvm-command-not-found-when-deploy-to-github-release/367.

**Comment by dmerejkowsky** [comment]
Woops, sorry. I'll be watching the issue on travis-community then.
