### ISSUE TITLE
No public key available for my repository

### ISSUE THREAD

**Issue by imperva-admin** [travis-ci/travis-ci#10252]
Just linked a project from github (https://github.com/imperva/shcf4j), when accessing to https://api.travis-ci.org/repos/imperva/shcf4j/key the result JSON is:
{"file":"not found"}

Please advice.

**Comment by BanzaiMan** [comment]
How are you sending this API request? I get:

```sh-session
$ curl https://api.travis-ci.org/repos/imperva/shcf4j/key
{"key":"-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArNBunxpXvojmYHbeq6dU\nXOWN0kO3wcte+at38oJ3v6OUWUfjlANVN2QRfjXDyn4/wwLXIWYKXm8QSzX2T2PR\n4v1WN9Y8ww1lfinz6NSg7nk4vUMaLqGxuImjxLBG3Nu6ILxDI8gfsd02g1pJNe54\nxbdGmC5OYue9RD3sqEiIZsie0GUrga3aSky8pvWos6NCKMvseVrihjWrvKSf6Njv\nEzhJNsq8dmi+jAlCRXrP4r/xHEarEBWdp4SPDCzgOKyLRlqFO1nNqT/othS8ucJp\nzLfY6QOCbjgb2mr8IWzB0B7QF5kbuYfuiTdx6W5T5/pNEA/bNKw7Guh4ZnRYEUkg\nb61y87cMl6dtxu6h+vA52z0M7TsxvInyAbKg4Kh1pmC42UUBVUj4R53OXeDJnhaR\nbiglY/Xag0L3FVIqF6VOT2ENEsjl+jOf2Whi/k0KRL/fc3BytO+HySzEInnnE9Jp\nPZQ2oicr1QpDp70PjNwYFQp5f0rpTR1s0dFJkRnMkdo9w1mmBdtRvxJLpfg2ZAnT\nTOYxZlxgctlB5zhxxcHv60J6VX09UyKXzx4bcVI1VwwOJoU6w8HFyMSw81IhW5Fs\nZs+YVGbnPqAwIuAC3mQ9ST8IQLmgxM8dYqMWXpxoj0dyZMm3HhOIt06xynLsFpwz\nY8zE8CM3DScysAkiPbWUUlECAwEAAQ==\n-----END PUBLIC KEY-----\n","fingerprint":"7e:34:96:68:b6:f8:c2:ba:36:07:18:88:43:80:08:37"}
```

with V3, you can use the API explorer: https://developer.travis-ci.org/explore/repo/imperva%2Fshcf4j/key_pair/generated

**Comment by imperva-admin** [comment]
I used the travis-cli tool (installed with brew, tool version is: 1.8.9). The "travis encrypt" command didn't work, the error was the a text representation of the above JSON. I used the debug flag to check the CLI API requests and then saw the called URL (https://api.travis-ci.org/repos/imperva/shcf4j/key).

As a work around I use the "travis pubkey --debug" command, which showed another API call:

$ travis pubkey --debug
** Timeout::Error: execution expired
** GET "repos/imperva/shcf4j"
**   took 0.17 seconds
** GET "repos/21601470/key"
**   took 0.21 seconds

This action stored the key in a local cache, afterwards the "travis encrypt" started to work.

**Comment by BanzaiMan** [comment]
I see. Do you happen to have the exact output from `travis encrypt` when it initially failed?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
