### ISSUE TITLE
CI builds stuck on 'Waiting for status to be reported'

### ISSUE THREAD

**Issue by IoannisCleary** [travis-ci/travis-ci#10256]
CI checks passed but PR is still waiting for status to be reported back.

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Also, please read #10204 and this blog post: https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

Thank you!
