### ISSUE TITLE
macOS error while installing Bioconductor packages

### ISSUE THREAD

**Issue by llrs** [travis-ci/travis-ci#10253]
I got an [error in macOS](https://travis-ci.org/llrs/BioCor/jobs/442569854) related to Bioconductor packages. While on the linux machine it build correctly. The errors reads:
```r
Error: `pkgs` 'GenomeInfoDbData', 'GO.db' are not installed
Execution halted
```
I think that it is related to not using BiocManager to install packages on the devel branch of bioconductor. But in the linux it worked and the same warning is also there. 

Any tip @jeroen and @jimhester ? BTW Thanks for your continuous support

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there. You can find the R Category here: [https://travis-ci.community/c/languages/r](https://travis-ci.community/c/languages/r)

Thanks and happy building!
