### ISSUE TITLE
Deploy fails on failing to find a remote; but it's looking for the wrong remote!

### ISSUE THREAD

**Issue by kaushalmodi** [travis-ci/travis-ci#10264]
Here is the error:

```
Preparing deploy
remote: Not Found
fatal: repository 'https://github.com/nim-lang/Nim/' not found
Current tag is: 
```

Log link: https://travis-ci.org/kaushalmodi/nightlies/builds/443384317#L816

`.travis.yml`: https://github.com/kaushalmodi/nightlies/blob/d911bf2e81690b9283738cb7c4eaa395580d0adf/.travis.yml

---

Why is it looking for https://github.com/nim-lang/Nim/ as remote instead of https://github.com/kaushalmodi/nightlies/?

**Comment by BanzaiMan** [comment]
Hello.

You are in a wrong directory. https://github.com/kaushalmodi/nightlies/blob/d911bf2e81690b9283738cb7c4eaa395580d0adf/.travis.yml#L75

GitHub Releases interacts with the current directory's git configuration, and since you are in one, it is used, instead of your repo's.

This might merit a mention in the docs.

**Comment by kaushalmodi** [comment]
@BanzaiMan Thanks. I arrived to the same conclusion in https://github.com/kaushalmodi/nightlies/commit/e7037405132dd6cd075f0dcd7503c70568b74e0d but after a lot of hair pulling.

Mention in docs would be nice.

_**Unrelated**: I am still working on polishing that .travis.yml (It's become a project in itself! And currently scratching my head why this job failed.. the log shows no error._

**Comment by DrTorte** [comment]
Opened a PR to make sure we get this into our docs. :) https://github.com/travis-ci/docs-travis-ci-com/pull/2152

I'll be closing this issue now, but if there is something else you'd like to discuss about this or other matters, we'll be glad to greet you over at the [Travis CI Community Forum!](https://travis-ci.community). Thanks and happy building! 😸
