### ISSUE TITLE
continuous-integration/travis-ci Expected — Waiting for status to be reported

### ISSUE THREAD

**Issue by johngeorgewright** [travis-ci/travis-ci#10261]
Hi, since the migration to GitHub "checks", one of our repositories looks unhappy. It still has an old build status which is continuously "Waiting for status to be reported" 😞. Anything I can do to get around this?

![screen shot 2018-10-18 at 10 23 28](https://user-images.githubusercontent.com/1423566/47144719-038e2080-d2c0-11e8-9385-c6c1689ad4f8.png)

**Comment by BanzaiMan** [comment]
Please read #10204 and the blog post it points to.
