### ISSUE TITLE
Stuck on "Syncing from Github"

### ISSUE THREAD

**Issue by priley86** [travis-ci/travis-ci#10260]
Hi - I would like to report this issue for my account: priley86 (Patrick Riley).

It seems several others have previously reported this. It just spins...

**Comment by cotsog** [comment]
I've proceeded with unblocking the sync process that was stuck for your account and I was able to sync it successfully afterward. Could you confirm that you can now see your organizations and repos [on your profile page](https://travis-ci.org/profile)?

**Comment by priley86** [comment]
Hi - yes, the issue is resolved now. Thanks!
