### ISSUE TITLE
Night PHP build does not have Xdebug installed

### ISSUE THREAD

**Issue by dbudwin** [travis-ci/travis-ci#10267]
I was getting the following error when running my unit tests:

```
PHPUnit 7.4.1 by Sebastian Bergmann and contributors.
Error:         No code coverage driver is available
```

After doing some research, that error likely means that PHP does not have Xdebug installed.  [Reading through the Travis CI docs](https://docs.travis-ci.com/user/languages/php/#choosing-php-versions-to-test-against) I saw the following comment: "Travis CI provides several PHP versions, all of which include XDebug and PHPUnit."

The output of `php --version` for the nightly build (as of submitting this issue) says:

```
$ php --version
PHP 7.4.0-dev (cli) (built: Sep  5 2018 06:15:07) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.4.0-dev, Copyright (c) 1999-2018, by Zend Technologies
```

Whereas for PHP version 7.1 I get the following output for `php --version`:

```
$ php --version
PHP 7.1.11 (cli) (built: Oct 26 2017 16:25:55) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

Note, how the nightly doesn't mention Xdebug where 7.1 does?  I believe this is the bug and the nightly PHP should have Xdebug installed.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
