### ISSUE TITLE
Add Travis Stage in Notification

### ISSUE THREAD

**Issue by blacelle** [travis-ci/travis-ci#10265]
Relatively recently, the stage has been added as an environment variable.

It is possible to know the name of current stage (typically the last failing or succeeding step) when a notification is sent?

**Comment by BanzaiMan** [comment]
Hello, there.

Notifications are a build-level concern; it tells you if the build (not a job in a build, or a stage in a build) has passed or failed. As such, they do not know anything about build stage. They will be sent *at the end of the build*. (If you allow certain jobs to fail, the notifications may fire early, but only when the result of the build has been determined.)

**Comment by blacelle** [comment]
Too bad. Thanks for you feedback
