### ISSUE TITLE
Sporadic invalid certificate chain error on macOS 10.10 XCode 6.4

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#10277]
Seeing a sporadic error on macOS 10.10 XCode 6.4 images where it sometimes runs into a certificate problem. Restarting normally fixes the issue. Nevertheless would be nice if that wasn't needed. Included a snippet of an example error message below.

```
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Download from https://build.travis-ci.org/filter/redirect_io.rb failed. Trying https://build.travis-ci.com/filter/redirect_io.rb ...
ruby: No such file or directory -- /Users/travis/filter.rb (LoadError)
```

ref: https://travis-ci.org/conda-forge/bloscpack-feedstock/jobs/444430542

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
