### ISSUE TITLE
Elm 0.19 project freezes with elm-test

### ISSUE THREAD

**Issue by AllanWang** [travis-ci/travis-ci#10274]
Build: https://travis-ci.org/AllanWang/Travis-Tracker/jobs/444248523

I can install the project locally with just npm install. In travis, everything seems to work, except for the test command freezes. Is there any idea what is going on, or if there is a prompt required to run the command?

![image](https://user-images.githubusercontent.com/6251823/47262534-add09880-d4b8-11e8-9db3-b965cdb09c49.png)

**Comment by reiner-dolp** [comment]
Did you see:
- https://github.com/rtfeldman/node-test-runner/issues/295
- https://github.com/elm/compiler/issues/1473

**Comment by AllanWang** [comment]
Thanks. I will take a look. I also messaged the slack channel and this is a known issue for a while, so I'm closing this for now.
