### ISSUE TITLE
How can I upgrade Python to the latest 2 version?  (2.7.15)

### ISSUE THREAD

**Issue by lipis** [travis-ci/travis-ci#10273]
https://docs.travis-ci.com/user/languages/python/#travis-ci-uses-isolated-virtualenvs

At the moment there is only 2.7.6 is available.. :(

**Comment by BanzaiMan** [comment]
Try:

```yaml
python: 2.7.15
```

**Comment by lipis** [comment]
It doesn't seem to work.. https://github.com/gae-init/gae-init/pull/969

**Comment by BanzaiMan** [comment]
Sorry; you are using `language: node_js`, so `python` is not effective. If you need a fewer version of Python, you either have to switch to `language: python` (and `python: 2.7.15` becomes effective), or you'll have to manage your own Python run time via `pyenv`.
