### ISSUE TITLE
Script build with ftp

### ISSUE THREAD

**Issue by gautamkrishnar** [travis-ci/travis-ci#10270]
I am using script build to deploy my application to 00webhost. 
Please see the script: https://github.com/gautamkrishnar/Be-Like-Bill/blob/production/deploy.sh
Travis.yml: https://github.com/gautamkrishnar/Be-Like-Bill/blob/production/.travis.yml

I am not able to upload the files via ftp even though i am using the correct commands. Not sure this is due to the travis firewall configuration. If yes how can i upload files using ftp. I know that it is possible using curl. Is it the only option?

Sample build log: https://travis-ci.org/gautamkrishnar/Be-Like-Bill/builds/443766951

**Comment by BanzaiMan** [comment]
Please read 
https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci

**Comment by gautamkrishnar** [comment]
Thanks for the clarification @BanzaiMan
