### ISSUE TITLE
Is it possible to perform Flutter Tests in the Windows Build Environment?

### ISSUE THREAD

**Issue by Andrious** [travis-ci/travis-ci#10279]
Hello you two!
Good of you to help out, being that Dart for Travis-CI is not officially supported.

Please, it's been a long day, and admittedly I'm just too tired to do a little 'research' and figure out
how to make this Travis thingy work. :)

Currently, this is all my .travis.yml file consists of:
  language: dart

I suspect I have to indicate further somehow that I simply want it to run whatever is in the test directory as, right now, I get this error:
https://travis-ci.org/AndriousSolutions/mvc_pattern/jobs/444517539

I did make some of an effort and looked at a past issue: 
https://github.com/travis-ci/travis-ci/issues/9678

Wow! What is all that in his .travis.yml file?!

**Comment by Gleydar** [comment]
Hey Hey, 
I hope I can help you out a little! What we found, was that `language: dart` means _Dart_ and Dart exclusivly. If you want to use anything from Flutters lib (like downloading your dependencies from a Flutter dependency file), you need to download Flutters SDK. You can do that using a `before_script` like this:
`
before_script:
    - git clone https://github.com/flutter/flutter.git--depth 1`
This will download Flutters SDK and allow you to use all the tools aviable.

**Comment by Andrious** [comment]
@Gleydar  Thanks Konstantin. Appreciate your insight on this. That is an impressive script. Too bad I don't understand it.

Yes, I soon realized I needed Flutter, and in my research, came upon Yegor Jbanov's article, [Test Flutter apps on Travis](https://medium.com/flutter-io/test-flutter-apps-on-travis-3fd5142ecd8c)

Now the travis.yml file he offers uses the Linux build environment. I was hoping to use the Windows environment. I gather the [ Dart Support in the Windows](https://travis-ci.community/t/dart-support-on-windows/450) environment is limited, but I suspect I will be able to simply run the tests: 
`        - ../flutter/bin/flutter test`

Haven't got a clue how that would look like, of course, as I am a complete newbie to this stuff. Trying to get through the documentation, but it will take time.

**Comment by BanzaiMan** [comment]
@Andrious Please edit the issue title to reflect the problem at hand. Thanks.

**Comment by Andrious** [comment]
> @Andrious Please edit the issue title to reflect the problem at hand. Thanks.

Sure thing.  How do I do that? :)

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
