### ISSUE TITLE
Build logs not displaying

### ISSUE THREAD

**Issue by MineRobber9000** [travis-ci/travis-ci#10276]
I'm working on a project that uses travis-ci.com, and I can't access the build log.

In the JavaScript console, I see this error:
![screenshot 2018-10-21 at 11 34 57 am](https://user-images.githubusercontent.com/12676241/47268965-5ddbeb00-d525-11e8-86bd-844efb257a45.png)

This doesn't seem to happen with travis-ci.org. It appears to be an error getting an SSH key.

The repo is at https://travis-ci.com/MineRobber9000/ips.py.

**Comment by BanzaiMan** [comment]
Do you still see this?

**Comment by MineRobber9000** [comment]
No, it appears to be fixed.
