### ISSUE TITLE
OpenJDK 8 is unavailable on Mac images

### ISSUE THREAD

**Issue by dmitry-timofeev** [travis-ci/travis-ci#10289]
Travis fails to download the OpenJDK 8 image, resulting in the build failure:

```
Installing openjdk8
$ curl -sLf https://build.travis-ci.com/files/install-jdk.sh >~/bin/install-jdk.sh
$ export JAVA_HOME=~/jdk
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/Users/travis/jdk" --workspace "/Users/travis/.cache/install-jdk" --feature "8" --license "GPL"
install-jdk.sh 2018-10-17
Expected feature release number in range of 9 to 12, but got: 8
The command "~/bin/install-jdk.sh --target "/Users/travis/jdk" --workspace "/Users/travis/.cache/install-jdk" --feature "8" --license "GPL"" failed and exited with 3 during .
Your build has been stopped.
```

Job log: https://travis-ci.com/exonum/exonum-java-binding/jobs/153574043

**Comment by dhalperi** [comment]
Looks like #10290

**Comment by leizhiyuan** [comment]
https://travis-ci.org/alipay/sofa-rpc/jobs/445292518 

it seems that openjdk6 also has a problem.

**Comment by dmitry-timofeev** [comment]
Thanks, it works now!

**Comment by michaelahlers** [comment]
Also running into this (see [failing build](https://travis-ci.com/michaelahlers/b2-scala/jobs/226147211)).

**Comment by Mixermachine** [comment]
@dmitry-timofeev 
Hy Dmitry
currently openJDK8 can't be used on Ubuntu Bionic and MacOS.
It prints the same error as if one tries to install the OracleJDK8 on the system.

Example:
for Ubuntu Bionic: https://travis-ci.com/Mixermachine/base-test/jobs/231203499
for MacOS: https://travis-ci.com/Mixermachine/base-test/jobs/231210940

Can you have a look at it :)?

**Comment by Zialus** [comment]
Any updates on this?

**Comment by ChameleonTartu** [comment]
Hi guys. I bumped with the same issue. I cannot make it work on macos even it works in xenial. Any solution? Is there any other distribution I can use instead?
