### ISSUE TITLE
Update gimme version for non-Golang environments

### ISSUE THREAD

**Issue by bzz** [travis-ci/travis-ci#10287]
[Container-based](https://docs.travis-ci.com/user/reference/overview/#container-based) builds with `language: scala` the [travis-ci/gimme](https://github.com/travis-ci/gimme) `gimme version` returns `v1.2.0`, which is quite old and e.g does not support `.x` suffixes (added in [1.5](https://github.com/travis-ci/gimme/blob/master/CHANGELOG.md#150---2018-05-29)).

Builds with `language: go` it has `gimme version` of `v1.5.3`.

Thus builds \w both Scala and Golang need to always `curl` the latest gimme in every job.

It would nice to have gimme version updated, to avoid extra network call to Github.

**Comment by BanzaiMan** [comment]
Note that we will be moving to VM-based infrastructure. Containers are unlikely to receive significant updates.

> Thus builds \w both Scala and Golang need to always curl the latest gimme in every job.

You can get `gimme` that `travis-build` hosts with:

    curl -O https://build.travis-ci.org/files/gimme # or build.travis-ci.com
