### ISSUE TITLE
ideal R package exceeding time limit

### ISSUE THREAD

**Issue by federicomarini** [travis-ci/travis-ci#10286]
I have an issue in getting my R package, ideal (https://travis-ci.org/federicomarini/ideal), passing the CI tests on Travis.

Main reason, simply put: the package has a number of dependencies, and to build these, I am hitting the 50 min build time limit. I did not increase the number of dependencies, but the cache probably went out of date.

What is the recommended way of solving this issue? 

cc'ing @jeroen and @jimhester

**Comment by jimhester** [comment]
The 50 minute build limit is a hard cap on any build, there is no way to increase it. For CRAN dependencies you can install binary versions of the packages with `r_binary_packages()`, see https://docs.travis-ci.com/user/languages/r/#additional-dependency-fields. **note** you will need to set `sudo: required` to use the binary packages.

**Comment by federicomarini** [comment]
Ok, it is worth a try.
Having dplyr and stringr (i.e. two pkgs that take some building time) among the imports, I put them as `r_binary_packages`.
If I got you right, with `sudo: required` I lose the possibility to cache the packages? (Would still be a lesser problem than having the pkg not built on Travis)
Thanks for chiming in!
Federico

**Comment by jimhester** [comment]
Travis now supports the package cache even with `sudo:required`, so you shouldn't lose anything really.

**Comment by federicomarini** [comment]
Excellent. I will add a couple more to guarantee the speedup, plus the cache will be set to on again.
Thanks for providing the excellent workaround!
