### ISSUE TITLE
Travis CI not triggered for a given repository

### ISSUE THREAD

**Issue by klemenoslaj** [travis-ci/travis-ci#10284]
## Problem
I want to see a success or a failure of a pull request in my repository, but I am not able to get Travis up to date with my GitHub repository.
As well on a pull request I do not see Travis at the bottom any longer, only a base GitHub merge functionality.

## What I tried
I tried to manually synchronize with my GitHub account. There was no failure, but no effect on this problem either.

## Additional info
Repository: https://github.com/klemenoslaj/ng-action-outlet
Pull request: https://github.com/klemenoslaj/ng-action-outlet/pull/5

**Comment by vmalloc** [comment]
Travis still seems to not be triggered correctly (For example https://github.com/getslash/mailboxer) - even though GitHub reports all systems operational now...

**Comment by vmalloc** [comment]
Sorry - I stand corrected. It seems to trigger fine now.

**Comment by klemenoslaj** [comment]
@iamjohnnym you are absolutely correct, it works now. Sorry for reporting it at the wrong place.
