### ISSUE TITLE
R: devtools 2.0 breaks builds w/ older versions of R

### ISSUE THREAD

**Issue by yutannihilation** [travis-ci/travis-ci#10285]
Some packages are not available for the older version of R and now `devtools::install_deps()` complains about it. The warnings are converted to errors and `warning_are_errors: false` doesn't affect here, so builds fail. For example: 

```
$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
covr         (3.2.0        -> 3.2.1       ) [CRAN]
data.table   (1.11.4       -> 1.11.8      ) [CRAN]
dplyr        (0.7.6        -> 0.7.7       ) [CRAN]
evaluate     (0.11         -> 0.12        ) [CRAN]
fansi        (0.3.0        -> 0.4.0       ) [CRAN]
microbenc... (1.4-4        -> 1.4-6       ) [CRAN]
mime         (0.5          -> 0.6         ) [CRAN]
ps           (1.1.0        -> 1.2.0       ) [CRAN]
tinytex      (0.6          -> 0.8         ) [CRAN]
rlang        (b70d83efa... -> d773ee9f0...) [GitHub]
Skipping 1 packages not available: dbplyr
Installing 10 packages: covr, data.table, dbplyr, dplyr, evaluate, fansi, microbenchmark, mime, ps, tinytex
Installing packages into ‘/home/travis/R/Library’
(as ‘lib’ is unspecified)
Error: (converted from warning) package ‘dbplyr’ is not available (for R version 3.1.3)
Execution halted
```
(https://travis-ci.org/tidyverse/dplyr/jobs/444743736#L1233-L1249)

I'm not sure how to fix this properly. It may not be a good idea to ignore the lack of packages, but one might want to be torelant about packages in `Suggests`. Maybe add an option to `install_deps()` to suppress the warnings and use it?

For a workaround, we can install the older devtools by `r_github_packages`: https://github.com/tidyverse/ggplot2/pull/2957/files

cc @jeroen and @jimhester

**Comment by jimhester** [comment]
Set the envvar `R_REMOTES_NO_ERRORS_FROM_WARNINGS=true` to disable converting warnings to errors when installing packages, see https://github.com/r-lib/remotes#environment-variables for details.

**Comment by yutannihilation** [comment]
Sorry, I wasn't aware of it. Thanks!
