### ISSUE TITLE
Cannot sign in github, "Your browser did something unexpected".

### ISSUE THREAD

**Issue by zhbhun** [travis-ci/travis-ci#10282]
![_013](https://user-images.githubusercontent.com/1996891/47275134-46f9cf00-d5df-11e8-8b11-c422a448adbc.jpg)
![_011](https://user-images.githubusercontent.com/1996891/47275131-42cdb180-d5df-11e8-964b-ebea34e6d1da.jpg)
![_010](https://user-images.githubusercontent.com/1996891/47275129-38abb300-d5df-11e8-89bb-a0adeb357c9b.jpg)
![_012](https://user-images.githubusercontent.com/1996891/47275132-45300b80-d5df-11e8-9d5e-e96d83d429f2.jpg)

**Comment by qasimjaved** [comment]
this is still happening to me when ever i try to log out.
I am getting error 'Your browser did something unexpected. Please contact us if the problem persists.'

![Uploading Screenshot from 2020-04-18 15-02-27.png…]()

**Comment by Poofikate** [comment]
I had the same problem.
I solved the problem by disabling all browser extensions.
using the exception method, I found the culprit (in my case, Referer Control)

**Comment by anthonytranDev** [comment]
Had the same issue, was using the Private Internet Access VPN extension which was on

**Comment by DenisCor** [comment]
no VPN , no extensions and still getting this error only in chrome..

**Comment by evilPaprika** [comment]
> no VPN , no extensions and still getting this error only in chrome..

I had same issue. I cleared site data, and logged in just fine.

**Comment by MulunehA** [comment]
open  using incognito mode with extension disabled or try another browser.

**Comment by weezycode** [comment]
Go to Chrome settings -> Advanced settings and restore default settings.
I had the same issue knowing that all extensions were disabled and even with reinstalling Chrome I still had the same issue but restoring settings saved me.

**Comment by snowman** [comment]
same with *ALL* extensions disabled, still not work

and I can't comment, so I delete all local storages and cookies in GitHub *only* with `Localstorage/Sessionstorage & Cookie Manager` and re-login, now it works

**Comment by miguelh3000** [comment]
> I had the same problem. I solved the problem by disabling all browser extensions. using the exception method, I found the culprit (in my case, Referer Control)

Thanks! I am using Firefox and the extension that was giving me this error was "Bitdefender Anti-Tracker". Once I added the website into the Bitdefender's ignore list, the GitHub website worked again.

**Comment by trusktr** [comment]
I have the same problem on a brand new fresh MacBook Pro M4 in Safari, nothing installed (literally nothing, just logged into fresh desktop, opened Safari, unable to log into GitHub).

I don't know what the solution is yet. Seems to me like GitHub is broken, or something somewhere in the network is hacked.

EDIT: It was a GitHub outage in my case. GitHub support has fixed the issue.

**Comment by chenxzlyd8** [comment]
1、Press F12, open the Developer tools，Developer tools->Application->Storage->Clear Site data.   it work.
2、Press Ctrl + F5, it may be work

**Comment by c0el** [comment]
Disabling all browser extensions does indeed fix the problem. Brave browser.
