### ISSUE TITLE
update docker version on xenial

### ISSUE THREAD

**Issue by ericLemanissier** [travis-ci/travis-ci#10296]
currently, xenial VM's are running docker 18.03, but it blocks the use of statx, which ends up making Qt compilation fail (https://bugreports.qt.io/browse/QTBUG-64490 and http://code.qt.io/cgit/qt/qtbase.git/tree/dist/changes-5.10.0#n502)
This problem should be solved by updating docker to 18.04 https://github.com/moby/moby/pull/36417#issuecomment-370782801

The problem does not happen on trusty VMs because the kernel is 4.4.0

**Comment by BanzaiMan** [comment]
It should have 18.06 now. https://travis-ci.org/travis-ci/travis-build/jobs/452101668#L33-L51

**Comment by 3nids** [comment]
I am experiencing a similar issue when using curent Docker (18.06) on Xenial dist on Travis.

Getting errors as: `clang: error: no such file or directory: 'src/native/moc_qgsnative.cpp'
` (see https://travis-ci.org/qgis/QGIS/jobs/537595617#L8058)

The docker is based on Disco (Qt 5.12).

Any idea how to solve this?
What is strange is that on older docker (when using Trusty as Travis dist), it seems to work as expected (even with Qt 5.11 on a Cosmic Docker)
