### ISSUE TITLE
Travis CI Appears to be using an Ubuntu image for a Debian build

### ISSUE THREAD

**Issue by laughingbiscuit** [travis-ci/travis-ci#10298]
I am seeing a strange behaviour where Travis CI uses Ubuntu images instead of Debian images...

Locally:

```bash
$ docker run -it debian:stretch uname -a

Linux cca6aea0eebf 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u3 (2018-08-19) x86_64 GNU/Linux
```

On Travis CI:
```bash
$ docker run -it debian:stretch uname -a

Linux 50da2fcf2251 4.4.0-101-generic #124~14.04.1-Ubuntu SMP Fri Nov 10 19:05:36 UTC 2017 x86_64 GNU/Linux
```

Steps to reproduce:
https://travis-ci.org/laughingbiscuit/travis-weirdness/builds/447521531#L453

Any ideas why this is?

Please note, I am using a node-js environment as my project runs cucumber-js tests against a docker container.

**Comment by BanzaiMan** [comment]
Closing in favor of https://travis-ci.community/t/travis-ci-appears-to-use-an-ubuntu-docker-image-for-debian-stretch/540.
