### ISSUE TITLE
Incorrect branch for Pull Request

### ISSUE THREAD

**Issue by yura3d** [travis-ci/travis-ci#10293]
Hello!
Please, can anybody explain for me why Travis CI clones the base (master) branch for Pull Request, that was created for other branch?
![image](https://user-images.githubusercontent.com/10958696/47493815-e249a900-d858-11e8-916b-8cbd4d765a76.png)
Thank you for your help.

**Comment by BanzaiMan** [comment]
For PR builds, we first clone the base branch, then check out the merge commit. You can see `git fetch origin +refs/pull/377/merge`.

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!
