### ISSUE TITLE
builds hang forever

### ISSUE THREAD

**Issue by lzl124631x** [travis-ci/travis-ci#10297]
Today the builds hang forever.  What is going on?
![image](https://user-images.githubusercontent.com/5824517/47614340-cc580600-da5b-11e8-98cd-7d5590366f4c.png)

**Comment by jvarho** [comment]
https://www.traviscistatus.com/

Claims status is fine, but the counts of active builds have all suspiciously flat lines for the past couple of hours.

**Comment by Havunen** [comment]
Isn't it considered down time if server is up, but nothing happens? :smile:

**Comment by MikeGitb** [comment]
Mine are stuck too. Is github the preferred mechanism to notify travis about such problems or is there another channel to contact them?

**Comment by bravo-kernel** [comment]
Under investigation by Travis as can be seen on the status page.

![image](https://user-images.githubusercontent.com/230500/47615027-95a8dc80-daa9-11e8-804d-57491e2fe7f1.png)

**Comment by BanzaiMan** [comment]
Please subscribe to the status updates. https://www.traviscistatus.com/incidents/7k1r5btfg45m?u=0s8091nynzj8
