### ISSUE TITLE
OracleJDK 8 install issue on Xenial

### ISSUE THREAD

**Issue by sfraint** [travis-ci/travis-ci#10290]
Travis fails to setup OracleJDK 8 on Xenial, resulting in build failure:
```
Installing oraclejdk8
$ curl -sLf https://build.travis-ci.org/files/install-jdk.sh >~/bin/install-jdk.sh
$ export JAVA_HOME=~/jdk
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/jdk" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
install-jdk.sh 2018-10-17
Expected feature release number in range of 9 to 12, but got: 8
```

For a travis.yml like:
```
dist: xenial

jdk:
  - oraclejdk8

...
```

Example build failure: https://travis-ci.org/batfish/batfish/jobs/445184648

**Comment by dhalperi** [comment]
Looks a lot like #10289

**Comment by joepvd** [comment]
`oraclejdk8` is not preinstalled on Xenial anymore, and cannot be retrieved from Oracle itself anymore. We'd suggest using either openjdk, or the currently supported Oracle JDK.

**Comment by mprins** [comment]
this is simply not true: 
> and cannot be retrieved from Oracle itself anymore. We'd suggest using either openjdk, or the currently supported Oracle JDK.

see https://www.oracle.com/technetwork/java/javase/downloads/index.html#JDK8 and https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
All the java 8 downloads are there

**Comment by DrTorte** [comment]
Hello,

There is a thread relating to this on the Forum. [Please see this link.](https://travis-ci.community/t/oracle-jdk-11-and-10-are-pre-installed-not-the-openjdk-builds/785/4) Closing this issue to continue conversation there. Thanks!
