### ISSUE TITLE
CC and CXX overriding issue when using multiple languages in a single yaml file

### ISSUE THREAD

**Issue by lekshmideepu** [travis-ci/travis-ci#10292]
I have a similar issue as mentioned in #9615 
I understand that language settings override user defined ones. In my case, language is set to "Python". But I also included 2 more cpp builds for clang and gcc. As described [here](https://docs.travis-ci.com/user/languages/c/#GCC-on-Linux), I tried to set the MATRIX_EVAL option, but didn't succeed.
Any help would be very much appreciated.
Sample GCC build is [here](https://travis-ci.org/lekshmideepu/nest-simulator/jobs/445667531#L960)
As it is overriding, it shows GCC as [4.8.4](https://travis-ci.org/lekshmideepu/nest-simulator/jobs/445667531#L1161)

**Comment by lekshmideepu** [comment]
With [this](https://travis-ci.org/nest/nest-simulator/jobs/446037505#L1132) check under the install section, it seems to work fine. But I still would like to know why the MATRIX_EVAL given in your docs doesn't work as expected.

**Comment by BanzaiMan** [comment]
`MATRIX_EVAL` is just an environment variable. It does not do anything special by itself.

In the build you indicate initially, you see that [`CXX` and `CC` are exported](https://travis-ci.org/lekshmideepu/nest-simulator/jobs/445667531#L965-L966) from your language choice `cpp` (despite the language value displayed on that page, it is `cpp`; you can see this in https://travis-ci.org/nest/nest-simulator/jobs/446037505/config).

In the document, you see this at the end:

```yaml
before_install:
    - eval "${MATRIX_EVAL}"
```

This is what effect the change of setting `CC` and `CXX` to the values desired. In other words, this is a common shortcut among the 4 jobs that set `CC` and `CXX` to different values.

**Comment by lekshmideepu** [comment]
Right. I expected that this [line](https://github.com/lekshmideepu/nest-simulator/blob/gcc8-clang7-travis/.travis.yml#L239) 
`- eval "${MATRIX_EVAL}"
`  would set back the values of CC and CXX to the desired ones. But it is not. That is the reason why I had to give an extra export [line](https://github.com/lekshmideepu/nest-simulator/blob/gcc8-clang7-travis/.travis.yml#L270-L271) under the install section.

**Comment by BanzaiMan** [comment]
You are overriding `before_install` in these `matrix.include` jobs. https://github.com/lekshmideepu/nest-simulator/blob/2ce799d87245e64b28c481dd95482302589f9929/.travis.yml#L170-L190 So that `eval` command is not executed. The logs should confirm this.

**Comment by lekshmideepu** [comment]
Thanks for the clarification.

As shown [here](https://travis-ci.org/lekshmideepu/nest-simulator/jobs/446645515#L989-L992), it is working fine now.  Earlier I had added the `- eval "${MATRIX_EVAL}"`  under the main begin_install section. Now it is added under the `below_install` section of the include [jobs](https://github.com/lekshmideepu/nest-simulator/blob/gcc8-clang7-travis/.travis.yml#L67-L114).
