### ISSUE TITLE
more precise control of cron jobs

### ISSUE THREAD

**Issue by wizardforcel** [travis-ci/travis-ci#10305]
Do you plan to support crontab format (`* * * * *`) for cron jobs?

In addition, my forum account is in pending. I didn't recieve an email nor find where to send another one.

**Comment by pamil** [comment]
I'm missing the ability to schedule a build at a given time daily.

**Comment by nashid** [comment]
This issue will greatly improve the functionality of the Travis cronjob, any update for this missing feature?

**Comment by BanzaiMan** [comment]
Moved this to https://travis-ci.community/t/add-ability-to-specify-what-time-of-day-a-cron-job-is-executed/880

**Comment by joehorsnell** [comment]
This is related to #8705.
