### ISSUE TITLE
Ability to leave a optional comment

### ISSUE THREAD

**Issue by veera83372** [travis-ci/travis-ci#10306]
Hey,

Would it make sense to have ability leave a message (optional) while cancelling a job?
It gives you the power sharing information at build place, so that I don't to move around project management tool and build tool for knowing status of a job.

**Comment by BanzaiMan** [comment]
There is no ability to do that at the moment. I encourage you to open a feature request at https://travis-ci.community/c/product/feature-requests

Thanks.
