### ISSUE TITLE
Go build for 1.6.x with OS OSX fails

### ISSUE THREAD

**Issue by jasdel** [travis-ci/travis-ci#10309]
Our builds for Go 1.6.x on the OSX os fails with the error: 

```
$ GIMME_OUTPUT="$(gimme 1.6.x | tee -a ${TRAVIS_HOME}/.bashrc)" && eval "$GIMME_OUTPUT"
/Users/travis/bin/gimme: line 357:  1883 Segmentation fault: 11  GOROOT="${1}" "${1}/bin/go" version >&/dev/null
I don't have any idea what to do with '1.6.4'.
  (using download type 'auto')
```

https://travis-ci.org/aws/aws-sdk-go/jobs/449609433#L75

It looks like travis is unable to get  `Go 1.6.3` or Go 1.5 for the OSX os.

**Comment by DrTorte** [comment]
Hello,

As we're no longer supporting GitHub issues but this issue remains open, I'm creating a copy of this on the forum. [Please see this link](https://travis-ci.community/t/go-build-for-1-6-x-with-os-osx-fails-migrated-from-github/1099).

Thanks and happy building!
