### ISSUE TITLE
OSX builds with brewfiles fail on `travis-build version: dbd564c26`

### ISSUE THREAD

**Issue by R1dO** [travis-ci/travis-ci#10301]
Hi
When running builds for osx using the Homebrew.brewfile route all builds that run on 
`travis-build version: dbd564c26` fail on the Homebrew phase.

The reported error is visible in build log snippet below:
```
...
Installing Homebrew Packages
$ rvm $brew_ruby do brew bundle --verbose --file=Brewfile.travis
Ruby ruby-2.3.4 is not installed.
...
```

Things were still ok at `travis-build version: 495c0af19`.

**Comment by R1dO** [comment]
Sorry for not including the URL.

You can find it at: https://travis-ci.org/R1dO/OpenXcom/jobs/448589772

Thank you for looking into this

**Comment by BanzaiMan** [comment]
Thanks for alerting us. I'll take the discussion to https://travis-ci.community/t/homebrew-packages-failed-to-install/570. Thanks again.
