### ISSUE TITLE
please add TRAVIS_JOB_NAME environment variable

### ISSUE THREAD

**Issue by wfjm** [travis-ci/travis-ci#10304]
Jobs can be given a name in `.travis.yml`, very useful for getting self-explanatory build lists.
The `TRAVIS_JOB_` environment variables give access to several attributes of a job, however there is no `TRAVIS_JOB_NAME` environment variable, see [https://docs.travis-ci.com/user/environment-variables](documentation).

I'd truly appreciate if  `TRAVIS_JOB_NAME` is added. I missed it when I wrote a deploy-like script.

**Comment by ocefpaf** [comment]
Indeed that would be very useful. It would eliminate the need for some convoluted `if`s in mu deploy script b/c I could just use the job name.

**Comment by BanzaiMan** [comment]
Closed by https://github.com/travis-ci/travis-build/pull/1590
