### ISSUE TITLE
Misconfigured git on the Mac workers

### ISSUE THREAD

**Issue by fabiopelosin** [travis-ci/travis-ci#1034]
Git appears not to have been completely configured in some mac workers.

The error is:

```
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
```

See https://travis-ci.org/CocoaPods/CocoaPods/jobs/6139280#L183.

Curiously, the [sister build](https://travis-ci.org/CocoaPods/CocoaPods/jobs/6139279) is not failing.

**Comment by Turbo87** [comment]
@henrikhodne has this been remove again? or is it only set on the Mac VMs? and if so: why?
