### ISSUE TITLE
Javascript: No output has been received in the last 10m0s

### ISSUE THREAD

**Issue by XuhengLi** [travis-ci/travis-ci#10351]
I use Jasmine and Karma as testing framework to test my program and all of the testing cases passed. But after receiving the message that 'TOTAL: 4 SUCCESS', it seems that the test program did not exit automatically and after a while, I receive 'No output has been received in the last 10m0s'.

Build details can be found [here](https://travis-ci.com/XuhengLi/WLTT/builds/89979028)

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting new issues that are created here. We're looking forward to seeing you there. If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
