### ISSUE TITLE
"Cannot assign requested address" when connecting to ::1

### ISSUE THREAD

**Issue by ProgVal** [travis-ci/travis-ci#10350]
hi,

With a `.travis.yml` set to:

```
language: python     
python:              
    - "3.5"          
install:             
    - python3 test.py
```

and `test.py`:

```
import socket                                         
                                                      
s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
s.connect(('::1', 1234))                              
```

As [can be seen here](https://travis-ci.org/ProgVal/test_travis/builds/459477861), I'm getting this error on Travis:

> [Errno 99] Cannot assign requested address

The expected behavior is:

> [Errno 111] Connection refused

(Note: this is a duplicate of https://github.com/travis-ci/travis-ci/issues/8711 , which got closed)

**Comment by BanzaiMan** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks!

**Comment by graingert** [comment]
https://travis-ci.community/t/issue-cannot-assign-requested-address-when-connecting-to-1/1098/4
