### ISSUE TITLE
Build not marked as successful if last job is allow_fail but cancelled

### ISSUE THREAD

**Issue by jonhoo** [travis-ci/travis-ci#10356]
In https://travis-ci.org/jonhoo/rust-imap/builds/459508822, I have multiple build stages, and the very last job is marked `allow_fail`. However, when I cancel it, the whole build is marked as cancelled, instead of successful. This seems erroneous. This _may_ be an interaction with `fast_finish`, because the build is not immediately marked successful before that last job starts (which is after all required jobs have completed successfully). This was originally reported in https://github.com/travis-ci/travis-ci/issues/9677, and the two issues may or may not be related.

NOTE: I couldn't post this issue in the [Travis CI Community](https://travis-ci.community) as I apparently don't have permission to post as a new user.

**Comment by mkurz** [comment]
+1 Same here. This should definitely be fixed.

**Comment by BanzaiMan** [comment]
@jonhoo Sorry for the issue with the Community site. I looked into it, but I don't see you as a user at all, let alone your post. What did you do, and what did you see when you signed up and tried to post?

**Comment by jonhoo** [comment]
@BanzaiMan I just signed up as [`jonhoo`](https://travis-ci.community/u/jonhoo/activity). When I go to [Discussion & Feedback](https://travis-ci.community/c/product), the "New Topic" button is grayed out and cannot be pressed. I received a "Greeings" message from the `discobot`, which read, in part:

> For safety reasons, we temporarily limit what new users can do. You’ll gain new abilities (and badges) as we get to know you.

Which I assume is what causes this. It's probably a perfectly reasonable policy to not allow new users to immediately create new posts, but it does make it hard for the community to replace GitHub issues :)

**Comment by jonhoo** [comment]
Posted there as https://travis-ci.community/t/work-out-kinks-in-interactions-between-stages-allow-fail-and-fast-finish/1090

**Comment by BanzaiMan** [comment]
We'll work on reorganizing the categories. :-)

In the meantime, I'm closing this issue.
