### ISSUE TITLE
How to run the docker using bash instead of sh?

### ISSUE THREAD

**Issue by yjjnls** [travis-ci/travis-ci#10354]
If I use a docker in travis, it will use /bin/sh to run the docker (sudo -E docker run --rm -v "/home/travis/build/xxx:/home/xxx" -e CONAN_DOCKER_IMAGE="xxx" -e xxx /bin/sh -c "xxx"), but some command such as source is not support in sh. So I want to start the docker with bash and how?

**Comment by BanzaiMan** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by yjjnls** [comment]
solution: https://travis-ci.community/t/how-to-run-the-docker-using-bash-instead-of-sh/1082/6
