### ISSUE TITLE
Unable to install dotnet-sdk-2.1 now (working before)

### ISSUE THREAD

**Issue by Sarodh** [travis-ci/travis-ci#10359]
Previously, it has been able to find and install the dotnet-sdk-2.1 package. @joshua-ander @akoeplinger @nterrya

> Installing .NET Core
> $ export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
> $ export DOTNET_CLI_TELEMETRY_OPTOUT=1
> 36.58s0.57sE: Unable to locate package dotnet-sdk-2.1
> E: Couldn't find any package by glob 'dotnet-sdk-2.1'
> E: Couldn't find any package by regex 'dotnet-sdk-2.1'
> The command "sudo apt-get install -qq dotnet-sdk-2.1" failed and exited with 100 during .

**Comment by BanzaiMan** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks!

**Comment by BanzaiMan** [comment]
https://travis-ci.community/t/error-today-when-running-net-core-builds/1148
