### ISSUE TITLE
Travis-CI Unable to locate package azure-cli

### ISSUE THREAD

**Issue by carmat88** [travis-ci/travis-ci#10361]
Hello Folks!

We've decided to open an issue instead of posting something in the new community platform because this is not the first time that we are experiencing such glitch, so we thought to report it here. The glitch is the following:

```
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/trusty/InRelease  Connection timed out after 10001 milliseconds
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Connection timed out after 10002 milliseconds
W: Failed to fetch https://download.docker.com/linux/ubuntu/dists/trusty/InRelease  Connection timed out after 10001 milliseconds
W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease  Connection timed out after 10001 milliseconds
W: Failed to fetch https://packages.cloud.google.com/apt/dists/cloud-sdk-trusty/InRelease  Connection timed out after 10000 milliseconds
W: Failed to fetch https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/dists/trusty/InRelease  Connection timed out after 10001 milliseconds
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package azure-cli
The command "sudo apt-get update && sudo apt-get install azure-cli" failed and exited with 100 during .
```

Today after trying to fix something unrelated to what this issue is about, we've got stuck with the CI not being able (all of the sudden) to install the `azure-cli` package anymore. Rather strange for the following two reasons:

1. If we spin up an Ubuntu Trusty as a VM in one of our Openstack providers and follow [these instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#install-step-1) to install the `azure-cli`, then no error about locating the package are returned and installation succeeds;

2. This morning we were able to run the CI and installing such package. Here are a couple of builds showing it: [example-1](https://travis-ci.org/kubenow/image/builds/463313799) , [example-2 ](https://travis-ci.org/kubenow/image/builds/463331173), [example-3](https://travis-ci.org/kubenow/image/builds/463360878).

All other buildings after the latter examples are failing. At first we though that the reason was that Azure might have changed something, like regularly it does about the GPG key for ubuntu; this was in fact the case (though back in May 2018). You can see from the above links that we've changed the GPG key from `52E16F86FEE04B979B07E28DB02C46DF417A0893` to `BC528686B50D79E339D3721CEB3E94ADBE1229CF`.

The former though actually worked up until today; however for the sake of consistency we have update the `.travis.yaml` with the newest GPG key. Nevertheless, in the past this has happened with others apt packages as well. We regret to not have reported it each time, but it seems that sometimes apt packages/repositories are not reachable and/or not found from within the CI environment. But by spawning (at the same time) a VM in a cloud provider of our choice (running same Ubuntu version, trusty) and executing the same line of code we were then able to install such apt packages. So far when such glitch was occurring, we've pretty much just waited until the CI was running successfully again, by not changing one single line in the `.travis.yam`l, just clicking on the `restart-build` button.

What do you think? Are we missing something? Any insights on your end? Thank you for checking!

Cheers.

**Comment by luna-travisci** [comment]
As the comment above mentions, we are no longer providing support/allowing tickets here. I would recommend reaching out to us via support@travis-ci.com for assistance with this. Please include everything you've shared here in the email. Cheers!
