### ISSUE TITLE
Build fails due to MongoDB connection timeout

### ISSUE THREAD

**Issue by bartoszwalacik** [travis-ci/travis-ci#10367]
I'm reporting the problem here because my build started to fail without any changes in the project code, so it looks like a problem with Travis runtime.

My build uses MongoDB to run integration tests:

```
services:
  - mongodb
```

and since 2018-12-08, every time the build is run it fails because integration tests can't connect to MongoDB:

```
com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=travis-job-b0d8719f-570a-4f48-88a2-1d864ae48787:33492, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
```

see
https://travis-ci.org/javers/javers/builds/463952979

**Comment by Sutassa** [comment]
ในวันที่ อา. 9 ธ.ค. 2018 16:05 close-issue-app[bot] <
notifications@github.com เขียนว่า:
