### ISSUE TITLE
OSX Python versions specified don't exist

### ISSUE THREAD

**Issue by Dekken** [travis-ci/travis-ci#10409]
[This](https://docs.travis-ci.com/user/languages/python/) documentation is either wrong or just plain inadequate.

The only python version is 3.7, which is IMO hella buggy

Image version: xcode10.1

**Comment by Dekken** [comment]
no

**Comment by Dekken** [comment]
I'll just email you instead how about that?

**Comment by BanzaiMan** [comment]
We do not support `language: python` on the Mac.

**Comment by Dekken** [comment]
seems pretty arbitrary
