### ISSUE TITLE
localhost resolves to 127.0.1.1 instead of 127.0.0.1 on bionic

### ISSUE THREAD

**Issue by marten-seemann** [travis-ci/travis-ci#10458]
`/etc/hosts` has the following entries:
```
127.0.1.1 localhost localhost ip4-loopback 
127.0.0.1 localhost nettuno travis vagrant travis-job-xxxx
```
This means that `localhost` is always resolved to `127.0.1.1` instead of `127.0.0.1`.

**Comment by nicolas-grekas** [comment]
`sudo sed -i 's/127\.0\.1\.1 localhost/127.0.0.1 localhost/' /etc/hosts` fixes it
