### ISSUE TITLE
Travis OSX build failure due to "brew install .." raising errors

### ISSUE THREAD

**Issue by wdoekes** [travis-ci/travis-ci#10482]
Good morning.

I see OSX build failures due to Homebrew troubles:
https://travis-ci.org/SIPp/sipp/jobs/601344113
https://travis-ci.org/SIPp/sipp/jobs/602919042

```
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative': /usr/local/Homebrew/Library/Homebrew/global.rb:110: syntax error, unexpected keyword_rescue, expecting keyword_end (SyntaxError)
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
The command "if [ "$TRAVIS_OS_NAME" = osx ]; then brew install gsl; fi" failed and exited with 1 during .
```

I added:
https://github.com/SIPp/sipp/commit/d1f19060fc8f1cc44eeeb624772bed19d5d8fa7e
and that appears to fix things:
https://travis-ci.org/SIPp/sipp/jobs/604871866

Something you may want to know..

**Comment by wdoekes** [comment]
Not doing that right now. Take it or leave it ;-)

**Comment by flying-sheep** [comment]
It’s a bot, I doubt any human working at travis reads this

**Comment by wdoekes** [comment]
Yes, but I could hardly sign up to the travis-ci community and say that I won't be following up on this _there_ could I? That would defeat my not spending the effort.

Why are _you_ here? :-P

**Comment by flying-sheep** [comment]
Because I’m annoyed that they don’t reply to lesser-used tags (R) on the community board and wondered what happens if you open an issue here (this was the last one)
