### ISSUE TITLE
Call to virNetworkCreate failed

### ISSUE THREAD

**Issue by jansouza** [travis-ci/travis-ci#10549]
TASK [Create molecule instance(s)] *********************************************

failed: [localhost] (item=rhel7) => {"ansible_loop_var": "item", "changed": false, "cmd": ["/usr/bin/vagrant", "up", "--no-provision"], "item": {"box": "centos/7", "cpus": 1, "memory": 256, "name": "rhel7"}, "msg": "Failed to start the VM: See log file '/home/travis/.cache/molecule/ansible-apache-httpd/default/vagrant-rhel7.err'", "rc": 1, "stderr": "### 2021-03-31 22:57:34 ###\n### 2021-03-31 22:57:42 ###\n### 2021-03-31 22:57:42 ###\nError while activating network: Call to virNetworkCreate failed: Unable to open /dev/net/tun, is tun module loaded?: No such device.\n", "stderr_lines": ["### 2021-03-31 22:57:34 ###", "### 2021-03-31 22:57:42 ###", "### 2021-03-31 22:57:42 ###", "Error while activating network: Call to virNetworkCreate failed: Unable to open /dev/net/tun, is tun module loaded?: No such device."]}

failed: [localhost] (item=rhel8) => {"ansible_loop_var": "item", "changed": false, "cmd": ["/usr/bin/vagrant", "up", "--no-provision"], "item": {"box": "centos/8", "cpus": 1, "memory": 256, "name": "rhel8"}, "msg": "Failed to start the VM: See log file '/home/travis/.cache/molecule/ansible-apache-httpd/default/vagrant-rhel8.err'", "rc": 1, "stderr": "### 2021-03-31 22:57:37 ###\n### 2021-03-31 22:57:54 ###\n### 2021-03-31 22:57:54 ###\nError while activating network: Call to virNetworkCreate failed: Unable to open /dev/net/tun, is tun module loaded?: No such device.\n", "stderr_lines": ["### 2021-03-31 22:57:37 ###", "### 2021-03-31 22:57:54 ###", "### 2021-03-31 22:57:54 ###", "Error while activating network: Call to virNetworkCreate failed: Unable to open /dev/net/tun, is tun module loaded?: No such device."]}

**Comment by Nomake** [comment]
ในวันที่ พฤ. 1 เม.ย. 2021 06:08 น. close-issue-app[bot] <
***@***.***> เขียนว่า:

**Comment by Nomake** [comment]
ในวันที่ พฤ. 1 เม.ย. 2021 06:08 น. close-issue-app[bot] <
***@***.***> เขียนว่า:
