### ISSUE TITLE
Grunt should be installed globally to prevent warning

### ISSUE THREAD

**Issue by seriema** [travis-ci/travis-ci#1064]
As can be seen on line 241 in [my build](https://travis-ci.org/seriema/jquery.combine/builds/6564340) Grunt-cli should be installed globally with -g.

I can see two ways of solving this:
1  Grunt-cli should be available on Travis-CI already
2  Grunt-cli can be installed with -g flag for every build

1 would remove the requirement of having grunt-cli as devDependency, which is how Grunt is expected to work (I think?).

I brought this up in the #travis chat and `henrikhodne` said:

> "seriema: Hmm, could you please open an issue on our issue tracker? We'd be happy to preinstall this, just want to double-check that this won't break things."

**Comment by BanzaiMan** [comment]
As explained in https://github.com/travis-ci/travis-ci/issues/3231, `grunt-cli` is available now for the pre-installed Node.js runtimes, but not on ones that are installed on-demand.
