### ISSUE TITLE
Fold `script` section

### ISSUE THREAD

**Issue by arr2036** [travis-ci/travis-ci#1065]
Travis log output is split by various subsections, so say you have multiple apt-get install lines in your before_install section

```yaml
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtalloc-dev libssl-dev
  - sudo apt-get install -qq gdb
  - sudo apt-get install -qq build-essential autoconf dh-make debhelper devscripts fakeroot lintian pbuilder quilt
  - sudo apt-get install -qq -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" libmysqlclient-dev
  - sudo apt-get install -qq libkrb5-dev libgdbm-dev libhiredis-dev libldap2-dev libpam0g-dev libpcap-dev libperl-dev
  - sudo apt-get install -qq libpq-dev libreadline-dev libsnmp-dev libiodbc2-dev libyubikey-dev libykclient-dev firebird-dev
  - sudo apt-get install -qq  freetds-dev python-dev ruby-dev
```

You get:

![Screen Shot 2013-04-23 at 12 57 20](https://f.cloud.github.com/assets/791758/415541/f500c212-ac36-11e2-8c5c-9ebeb82defda.png)

With the log output expandable from each before_install command.

Unfortunately if you split out the script section in the same way:

```yaml
script:
  - ./configure -C --prefix=$HOME/travis
  - make -j8
  - make travis-test
```

You don't get script.1, script.2, script.3.

With C there's tons of (normally) irrelevant text produced by the config script as it customises the build to the environment. Unless the configure script actually errors out, there's no real need to show its output, and it just becomes an annoyance to scroll past.

Would it be possible to split the script output by command, and only expand output for the command that errored? It'd let us get to the part of the log where the command errored much quicker.

With FreeRADIUS (the FOSS project I contribute to), ``./configure`` produces 1,229 lines of output, whereas the actual build process which is where the majority of the errors occur, only produces 274.

**Comment by ksamdev** [comment]
I support the idea of folding successful script steps. Unfold only failing steps. Otherwise it becomes very annoying to scroll over many lines of output of successful tests especially in case there are 2+ test cases.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by drtrigon** [comment]
Having an option that allows to fold `script` would be very useful. That would allow to switch on folding if needed. E.g. 1 of my project could profit from it but the others not.
