### ISSUE TITLE
Repositories not syncing

### ISSUE THREAD

**Issue by brianpmarks** [travis-ci/travis-ci#1082]
My profile page says "Please wait while we sync from Github" but won't complete. Worked fine earlier in the day. I created a new repo and that's when it seemed to stop working. I've tried logging in and out and also revoking access but no luck.

Any ideas? Thanks

**Comment by vramyanaidu** [comment]
I just created account in Travis CI and tried to sync the repo, but throwing the error like"Sorry, it seems like we couldn't find any repositories you have access to on GitHub". I have logged out and logged back in as suggested and tried to sync, issue remains the same. please anybody help.
