### ISSUE TITLE
schedule jobs for builds with 'allowed failures' last

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#1092]
this was raised by @lsmith77 in https://github.com/travis-ci/travis-hub/issues/22

I think this has merit so I am moving it here.

**Comment by wagenet** [comment]
Presumably there is no action here? I would love to have my allowed failure jobs happen at the end of a build.

**Comment by BanzaiMan** [comment]
There is some possible variation due to multiple threads, but this should now work for the most part.

Let us know if you see egregious divergence from the described behavior.
