### ISSUE TITLE
TestFlight deployment after successful build

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#1098]
In order to deploy to [Testflight](testflightapp.com) (or anywhere else that's similar, like [HockeyApp](http://hockeyapp.net/), we need to be able to codesign on the VMs, which requires installation of certificates in the keychain.

Once we have that, the deployment itself should be fairly trivial.

**Comment by BanzaiMan** [comment]
Unfortunately, this has become stale. If anyone wishes to take @darrarski's ideas and turn it into a `dpl` provider, we are happy to work with you.

For now, I'm going to close this.
