### ISSUE TITLE
Cannot load FUSE kernel module

### ISSUE THREAD

**Issue by mpartel** [travis-ci/travis-ci#1100]
I'd like to test [bindfs](https://travis-ci.org/mpartel/bindfs) under Travis, but I'm unable to load the FUSE kernel module.

```
$ sudo modprobe fuse
FATAL: Could not load /lib/modules/2.6.32-042stab061.2/modules.dep: No such file or directory
```

My [.travis.yml](https://github.com/mpartel/bindfs/blob/travis/.travis.yml).
#811 may be related, although [using FUSE should be possible under OpenVZ](http://openvz.org/FUSE)

**Comment by vi** [comment]
+1 for the FUSE support.

The only workaround I can think up immediately is using UML (user mode Linux).

**Comment by probonopd** [comment]
Would be interested in using UML (user mode Linux) too - if anyone can post an example that would be great.

**Comment by vi** [comment]
Implemented the UML workaround, tested it on my project: https://travis-ci.org/vi/execfuse/builds/47789978

See the details on [the StackOverflow answer](http://stackoverflow.com/a/28070347/266720).

**Comment by probonopd** [comment]
Thank you, vi.

**Comment by akiradeveloper** [comment]
please support fuse.
UML workaround doesn't work for me somehow.

**Comment by vi** [comment]
@akiradeveloper, What does not work for you for UML workaround? Can you post a link to the build? For using other functions (like networking), UML needs to be configured additionally.

**Comment by joshk** [comment]
We are working on an improvement which will allow for Fuse support. I believe we are aiming for 2-3 months time.

**Comment by jbenet** [comment]
@joshk that's great to hear! thank you for all the hard work on this :) :heart:

**Comment by akiradeveloper** [comment]
After a fight to the death, UML workaround started to work. @vi thanks. I needed to add mem= option for UML (I run ruby from UML and then run Nimrod application from there)

But, still not working in OSX. Is fuse natively supported in OSX environment? I mean is fuse able to work UML hack like I do for  Linux.

This is my project. Thanks to Travis. It's a fuse binding for Nimrod language.
https://github.com/akiradeveloper/nim-fuse

**Comment by probonopd** [comment]
Possibly this is of interest as a workaround, too:
https://github.com/jpetazzo/sekexe/issues/4#issuecomment-76245814

**Comment by fourier** [comment]
Please add the FUSE support so those who use tup as a build system can use it here and not maintain 2 build systems (tup and something supported)

**Comment by joshk** [comment]
We are looking at adding FUSE support in our new setup, but no ETA.

**Comment by roidrage** [comment]
Just an update that this is now possible to run on our new Trusty/Precise stack: https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta

Example (thanks @mpl!):

```yaml
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
```

From https://github.com/mpl/camlistore/blob/e8cc5316aeab58bc012e6031554ed148b3f66b18/.travis.yml
