### ISSUE TITLE
Add Notification Center support to the web app

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#1109]
It would be cool to offer an option to turn on Notification Center support for when repos which are listed in the 'your repos' tab start of finish.

http://www.fngtps.com/2012/how-to-add-notification-center-notifications-to-your-web-app/

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by kumar303** [comment]
Man, this would be really helpful. CircleCI [supports it](https://circleci.com/docs/1.0/web-notifications/) and it comes in really handy.
