### ISSUE TITLE
Timeout or exceeding log size

### ISSUE THREAD

**Issue by maxbaeumle** [travis-ci/travis-ci#1113]
The builds of our repository either time out (when building without verbosity): 
https://travis-ci.org/timelapseplus/TimelapsePlus-Firmware/builds/7149232

or exceed the log limit of 4 Mb (when building with verbosity to prevent the timeout):
https://travis-ci.org/timelapseplus/TimelapsePlus-Firmware/builds/7158043

@joshk suggested in the Campfire chat room to create a wrapper script that builds without verbosity while it outputs a  pseudo character in an one minute interval, so that the build does not time out. I don't know if that is even possible (while Homebrew is running).

Please advise.

**Comment by Croydon** [comment]
@henrikhodne I don't understand why this was closed. All of the discussions here were about workarounds and this seems to be still a problem if I'm interpreting my situation right.

**Comment by Wetitpig** [comment]
How to use the script?
