### ISSUE TITLE
Support for Loop-Devices

### ISSUE THREAD

**Issue by jhbruhn** [travis-ci/travis-ci#1119]
I'm having to add files to a FAT12 floppy-image during my build but Travis-CI tells me, that mount files as a loopdevice is not possible:

```
mount: Could not find any loop device. Maybe this kernel does not know
       about the loop device? (If so, recompile or `modprobe loop'.
```

Here's the Project that's failing: https://travis-ci.org/bigteddy97/RolfOS
It seems to be a problem with the kernel so that's pretty deep in the VMs, any chance for a change?

**Comment by maxonthegit** [comment]
I know this is closed as this feature is unsupported: I just wanted to add two tiny bits of additional information.
* Someone seems to have succeeded in using nested virtualization to overcome this limit: see [here](https://github.com/travis-ci/travis-ci/issues/932#issuecomment-17707267).
* `libguestfs` seemed a promising alternative to `losetup` for creating disk images, but `virt-make-fs` still fails when attempting to perform kernel detection ([example](https://travis-ci.org/maxonthegit/netkit/builds/68471301#L9392)).

**Comment by warsaw** [comment]
The last comment in this thread is over a year old.  Is there any news on allowing loop mounts in Travis?
