### ISSUE TITLE
Meteor Support in Travis

### ISSUE THREAD

**Issue by arunoda** [travis-ci/travis-ci#1137]
Currently there is no [meteor](http://meteor.com) support in Travis.
It may be due the lack of a testing framework for meteor.

I've created a [testing framework for meteor](http://arunoda.github.io/laika/) called Laika - http://arunoda.github.io/laika/

It will be super useful if you guys can include meteor/meteorite binary in travis build environment.
So we could start using travis for meteor.

**Comment by zimme** [comment]
So now that Meteor is stable, any thoughts on pre installing it?

Hopefully it will result in us not needing `sudo: required` in our setups any more. Also the runtime for the tests will be lowered.
