### ISSUE TITLE
Prioritizing branches and repositories

### ISSUE THREAD

**Issue by roidrage** [travis-ci/travis-ci#1155]
We've gotten feature requests from customers to allow prioritizing some branches over others, and also to be able to prioritize some repositories over others in their accounts.

For branches, there could be a list of branches that should always be run first and before any other branches, e.g. master and production.

For repositories, a similar list could be kept, e.g. in a project that should be run with a higher priority than a second one, the .travis.yml could contain a setting specifying that.

**Comment by Fryguy** [comment]
:+1:

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by anderson-dan-w** [comment]
It's been 3 years, any plans to reconsider? I assume no, due to lack of update, but thought I'd bump it back to consciousness - this would really help.

**Comment by arshdeeptinna** [comment]
👍
