### ISSUE TITLE
Travis was building for a transfered repo

### ISSUE THREAD

**Issue by nschonni** [travis-ci/travis-ci#1173]
I think this was caused because the GitHub transfer still leaves the person as a repo admin, giving Travis access through the old hook, but unaware of the new Org/owner. No idea of how to test for it, but here is how I came across this issue:
- https://travis-ci.org/davidfowl/JabbR was moved into an organization https://travis-ci.org/JabbR/JabbR over 2 months ago. 
- I noticed today that the build badge was pointing to the old repo and asked the owner to setup the hook for the new organization. 
- When visiting https://travis-ci.org/JabbR/JabbR before the hook was setup for the new organization, Travis gave the "no repo found" message. 
- After the new hook was enabled, I found that almost 300 builds had been running for this moved repo, and the hooks now displayed on all the PRs that occurred after the move

**Comment by jpsim** [comment]
I renamed my repo (from 'sourcekitten' to 'SourceKitten') and now Travis can no longer find it. Are there certain steps I can follow to fix this?

See https://github.com/jpsim/SourceKitten, https://travis-ci.org/jpsim/sourcekitten and https://travis-ci.org/jpsim/SourceKitten. /cc @henrikhodne

**Comment by metaraine** [comment]
@jpsim Cloning the repo into a new folder worked for me. Opened a new issue: #3264
