### ISSUE TITLE
Add an option for composer to include a GitHub oauth token in the configuration

### ISSUE THREAD

**Issue by asm89** [travis-ci/travis-ci#1182]
I discussed with @joshk. It would be nice to have an option in the `.travis.yml` file where you can add an encrypted GitHub oauth token for composer to use. This will make it easier to setup dependencies between private repositories when using composer.

**Comment by PowerKiKi** [comment]
@joshk could you please clarify whether this still requires to setup our own token (via `.travis.yml`, or web interface), or if this is a global settings for all Tavis CI machines and hence we have nothing to do at all ?

I've seen some API rate limit errors recently and can't figure out how to set up things the _right way_.
