### ISSUE TITLE
Build notifications are sent to the wrong email address

### ISSUE THREAD

**Issue by wiseman** [travis-ci/travis-ci#1194]
My github account is a member of two organizations.  My email notifications are set up as follows:

![screen shot 2013-06-27 at 10 29 00 am](https://f.cloud.github.com/assets/52466/717543/4f210b30-df4f-11e2-84cc-b277c2233d43.png)

Travis sends email notifications for repositories in the open-air-data organization to the wrong email; it sends them to the email listed for the MorseProject organization.

**Comment by schoenwaldnils** [comment]
Any update on this issue?
