### ISSUE TITLE
Timing issue in Build#previous_state

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#1213]
The `Build#previous_state` attribute is set on create, at which point the actual "previous" build may not be finished yet.

This is most visible with notifications, and can be seen like this:

1. Create a build for a repository that would make a branch go from failing or non-existing to passing (this should send an email notification)
2. Create another build that also passes.

The last build shouldn't send a notification, but still does, since `previous_state` is either nil or `:failed`.

The easiest way to fix this is probably to not store `previous_state` in the database, but to look it up every time it's used. A quick grep says it's only used for notifications.

**Comment by joshk** [comment]
Closing this issue as it has become stale
