### ISSUE TITLE
Make git tarball strategy support submodules

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#1221]
Currently the tarball strategy (see travis-ci/travis-build#118) does not support submodules.

I tried a few things in order to get it to work (basically `git init && git submodule update --init`), but I couldn't get it to work.

I'm not sure exactly how to do this, so if anyone knows git well, feel free to comment.

**Comment by Croydon** [comment]
I would really like to have a very similar feature since it could speed up the whole build process a lot. 

Instead of getting everything as a tarball, including the main repo, I would like to get only the submodules as tarballs and then there should be a way how to implement that? :)
