### ISSUE TITLE
Autolink the build logs

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#1224]
If there's a URL in the build log, we should automatically add an `<a>` tag for it.

This allows us to, amongst other things, link users to the YAML spec or a "YAML FAQ" when we print the YAML parse error (see #1223).

If you view the log in a terminal, chances are the terminal emulator already has this functionality, so this is purely a thing we need to do in travis-web.

**Comment by nojvek** [comment]
vscode which uses xterm.js does this and it's really handy. I'm surprised travis doesn't do simple regex matching and formatting. Why is it hard to implement it?
