### ISSUE TITLE
Xdebug extension not loaded.

### ISSUE THREAD

**Issue by clubdeuce** [travis-ci/travis-ci#1236]
See my jobs [here](https://travis-ci.org/dlozupone/wp-mvc-base/jobs/8940764).

**Comment by theofidry** [comment]
Hi, got this issue for [this build](https://travis-ci.org/hautelook/AliceBundle/jobs/76179633) :(

**Comment by BanzaiMan** [comment]
@theofidry PHP nightly build does not have xdebug enabled. This is documented in http://docs.travis-ci.com/user/languages/php/#PHP-nightly-builds.

**Comment by theofidry** [comment]
Erf, my bad, I was sure to have seen the opposite -_-. Thanks @BanzaiMan
