### ISSUE TITLE
Travis hook doesn't work if the repo doesn't have `master` branch

### ISSUE THREAD

**Issue by Maks3w** [travis-ci/travis-ci#1250]
I've created a repo with only `gh-pages` branch but the hook does not work until I created a master branch and pushed some fake commit.

Seems that Travis has a harcode requirement for to have a branch called `master`

**Comment by abitrolly** [comment]
Travis hardcoded to ignore `gh-pages`.

Solution:
```
branches:
  only:
  - gh-pages
  - /.*/
```
https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches
