### ISSUE TITLE
UI message if a single job build is also an 'allowed failure'

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#1252]
I noticed, and fixed, a bug today where single job builds where not being marked as finished, even through the job was.

But it occured to me that fixing this issue, although trivial, actually meant it might be confusing in the UI due to the way we show builds with only one job. Because the job is an allowed failure, it will always be marked as passing even through you may see failures in the log.

There are two possible ways to fix this, either show a message (info or warning) above the log to say that this job has been marked as an allowed failure, or to change the show build view to show the build matrix even though there is only one job.

Happy to hear other suggestions.

**Comment by BanzaiMan** [comment]
Closing this in favor of #3168.
