### ISSUE TITLE
Web hook notification sends wrong Authorization header

### ISSUE THREAD

**Issue by jarib** [travis-ci/travis-ci#1262]
I've had a setup with authorized web hook notifications for https://github.com/holderdeord/hdo-site working for quite some time, but the checksum sent from Travis appears to be incorrect since 2013-07-15 17:47:10 UTC. The last successfully authenticated web hook request happened at 2013-07-13 15:26:45 UTC. 

The repo in question is under a GitHub organization where I've used my private user token for the Travis build (I'm not aware of any other way of doing this). Not sure if that matters, but it has been working for several months.

I've verified that the the Authorization header sent from Travis does not match what the documentation at http://about.travis-ci.org/docs/user/notifications/#Authorization suggest, and the code I'm using in the receiving service (which is unchanged):

``` ruby
Digest::SHA256.hexdigest("holderdeord/hdo-site#{token}")
```

**Comment by crunis** [comment]
Any news about this ? the current system with the Travis Token is pretty annoying : 

- In our company we have several Github admins that activate repos in Travis, so the token could be any of them
- It forces us to maintain the tokens together with the code that has to verify the notification.

**Comment by mkubenka** [comment]
Looks like this is broken again.

**Comment by larsbergstrom** [comment]
We're seeing problems with it having recently broken on Servo, too: https://github.com/servo/servo/issues/12739#issuecomment-237901398

**Comment by BanzaiMan** [comment]
I think we should open a new issue rather than tacking on a 3-year-old one.

**Comment by larsbergstrom** [comment]
@BanzaiMan Opened #6435 per your request.

**Comment by BanzaiMan** [comment]
@larsbergstrom Thank you!
