### ISSUE TITLE
Add a unique constraint to logs.job_id

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#1289]
There shouldn't ever be a case where multiple logs in the database have the same log_id? `job.rb` even `has_one :log`.

We should probably add a constraint to it, since there's quite a chance for race conditions otherwise.

**Comment by joshk** [comment]
Current count is 43.

Is this still something you think we should do @henrikhodne ?

**Comment by BanzaiMan** [comment]
The current count is 503.
