### ISSUE TITLE
gtest support

### ISSUE THREAD

**Issue by abumq** [travis-ci/travis-ci#1294]
We need to support gtest for C++ applications as we are unable to build unit tests on travis-ci

If anyone had done in the past, it would be awesome if someone can lend me before-install script for it

**Comment by topilski** [comment]
Hi all, this solution only for debian based system, what about RedHats and MacOSX?

**Comment by BanzaiMan** [comment]
@topilski We do not support RHEL/Fedora/CentOS out of the box. For OS X, I suspect you can find a Homebrew package for it.
