### ISSUE TITLE
Support multiple different deployment providers

### ISSUE THREAD

**Issue by moschlar** [travis-ci/travis-ci#1298]
Personally, I like to deploy the same application to both Openshift and Heroku.

Solution is probably similar to #1272 .

**Comment by AmitAronovitch** [comment]
@rkh @Aaron1011 re: once/multiple:  Actually, I believe before/after deploy should support a list, with separate item for each provider.

Use case: You want to deploy a Python project both to `pages`, and to `pypi`. These deployments are unrelated and have different `on:` conditions (deploy to PyPI only on tag/release, wheres doc updates should represent master head - note that on tags you probably run both). 

In this case the `before_deploy` conditions are also unrelated: e.g. for docs you might wish to run some doc-generation command, whereas for pypi you might want to cleanup the `dist/` directory.

Also, as byproduct, seems like it would also provide some solution to problem reported elsewhere: #6166
