### ISSUE TITLE
listening on sockets (doesn't work)

### ISSUE THREAD

**Issue by ducin** [travis-ci/travis-ci#1304]
Is there a possibility to create a socket and listen on it inside travis-ci? I've got a simple python game, where server and client communicate via standard sockets. I'm trying to use 12345 and it fails: https://travis-ci.org/tkoomzaaskz/noughts-and-crosses/jobs/9839474

Both server and client are run as threads of a test script (test is run with nosetests). This is my server output:

```
Connection closed
Unexpected error occurred [Errno -2] Name or service not known
```

And this is the client output:

```
Noughts and crosses, v1.0
Connecting to testing-worker-linux-5-2-14958-linux-1 12345
Connection closed
Unexpected error occurred [Errno -2] Name or service not known
```

Seems like the server is not allowed to open a socket on a given port and the client is not able to bind to it. Why is this "service not known"? Is there any range of allowed sockets on travis?

PS

this is the server code that fails (https://github.com/tkoomzaaskz/noughts-and-crosses/blob/master/nac/server.py):

```
    s = socket.socket()
    try:
        s.bind((config.HOST, int(args[-1]) if args else config.PORT))
        s.listen(5)
```

**Comment by mkoohafkan** [comment]
I am having issues with socket connections when testing an R package. My tests are unable to open a socket connection on Travis. I have tried `localhost`, `127.0.0.1` and `0.0.0.0`, with ports `1234` and `6011`, on Travis with `sudo: required` and `sudo: false` .  @craigcitro and @jimhester, is this perhaps related to the R testing environment specifically?

**Comment by jimhester** [comment]
There is nothing about `lang: r` that does anything with sockets, so this is not an R-travis specific issue.

**Comment by Excodibur** [comment]
Is there actually some news on this issue by now? I got the same issue when trying to start a mock-server as part of the integration tests:

```javascript
{"message":"Mock server running on localhost:502","level":"info"}
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: listen EACCES: permission denied 0.0.0.0:502
```

**Comment by Excodibur** [comment]
Ignore my request. It turns out that using a port in that low port-range is a bad idea if not being root. With port 10502 creating a socket actually works.
