### ISSUE TITLE
Support Lua

### ISSUE THREAD

**Issue by daurnimator** [travis-ci/travis-ci#1307]
Native lua support in travis would be great!

At the moment you can get by with the C language and a couple of apt-gets, but native support is of course going to be better. 
An example of such a simple script can be found over at https://github.com/daurnimator/luatz/blob/master/.travis.yml

I (or others) can help with most knowledge you may need regarding the lua ecosystem: what do you need?

**Comment by daurnimator** [comment]
I came across this project today, which I hope travis might make available as a lua template: https://github.com/moteus/lua-travis-example/tree/master/.travis

At least the `.travis` folder...

**Comment by jcsandrix** [comment]
Can this be reopened?

The current "best" travis solution is this project: https://github.com/mpeterv/hererocks

**Comment by greatwolf** [comment]
I'd also like to chime in and ask for direct lua build support on travis.
