### ISSUE TITLE
Restricting branches also stops building pull-requests.

### ISSUE THREAD

**Issue by alloy** [travis-ci/travis-ci#1316]
I have [a repo](https://github.com/alloy/trunk.cocoapods.org-test) where I create branches and for each branch create a PR that would merge those branches into the `master` branch.

I only want Travis to build the PRs, not the branches. I _do_ however want Travis to always build the master branch.
### What I expected

To be able to use:

``` yaml
branches:
  only:
    - master
```

The [documentation](http://about.travis-ci.org/docs/user/build-configuration/#Specify-branches-to-build) regarding this doesn’t explicitly mention anything regarding pull-requests, so I had hoped that the target-branch of a PR would be used to identify that the PR requires a build.

[Here’s](https://github.com/alloy/trunk.cocoapods.org-test/commit/9cb5e5a8c0b24d881d1845aa7eda0b17773ab1d1) the `.travis.yml` change and [the PR](https://github.com/alloy/trunk.cocoapods.org-test/pull/24).
### What actually happened

Alas, my assumptions turned out to **not** be valid. Travis simply stopped building PRs altogether. (As can be seen in [the Travis pull-requests list](https://travis-ci.org/alloy/trunk.cocoapods.org-test/pull_requests) there was no build for that PR.)

It is interesting to note that @joshk said that this is how it _should_ work (on IRC).

**Comment by yads** [comment]
@joshk we're seeing this issue now on our builds. This used to work up until about a day ago. The relevant `branches` content of our config file:

```
branches:
  only:
    - master
    - /^release-.*$/
    - /^rel(-|\/).*$/
    - /^mvf\/.*$/
    - /^rel\/.*$/
```

We've also ran the linter and it reports no issues.

**Comment by BanzaiMan** [comment]
@yads Could you open a new ticket? If it's happening now, it's most likely a different bug/issue.
