### ISSUE TITLE
Conditional notification templates for different build states

### ISSUE THREAD

**Issue by josegonzalez** [travis-ci/travis-ci#1332]
It would be useful to have different notification templates depending upon the build state.

For example, my successful builds would include a link to uploaded artifacts - in this case, android apks - while failed builds would have a link to failure logs and other types of artifacts.

I'd also like to include cake emoji in successful builds :)

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
