### ISSUE TITLE
sqlite in travis vm has database corruption bug with concurrent writes, not in OS X locally

### ISSUE THREAD

**Issue by garysweaver** [travis-ci/travis-ci#1334]
Even though this is a sqlite bug, I think it is likely to have been fixed because the version that is provided via homebrew and various linux packages is from 2011.

So failures can be seen in:
https://travis-ci.org/garysweaver/otw/jobs/10210357
https://travis-ci.org/garysweaver/otw/jobs/10209642

Project here (just have to have ruby, then bundle install and rake):
https://github.com/garysweaver/otw

Tests fine locally in OS X with:
```
$ sqlite3 -version
3.7.7 2011-06-25 16:35:41 8f8b373eed7052e6e93c1805fc1effcf1db09366
```

but fails in TravisCI (not sure which distro/version of Linux- just see "x86_64-linux") with:
```
3.7.9 2011-11-01 00:52:41 c7c6050ef060877ebe77b41d959e9df13f8c9b5e
```

I'm using the fork gem in Ruby (Rails uses it also- fairly well-used I guess) to create multiple processes to all attempt to hit Rails 4.0.0 controllers at the same time in Ruby 2.0.0-p247 and insert into the same sqlite (file based) DB around the same time. It works fine locally even though I can see that the journalling file is being recreated a lot.

In the TravisCI tests though, when being tested concurrently, it starts to work and then quickly fails with "SQLite3::CorruptException: database disk image is malformed" or "SQLite3::NotADatabaseException: file is encrypted or is not a database".

Should I be attempting to update sqlite during the build to see if that fixes? What would be the suggested way to do that? Thanks!

**Comment by roidrage** [comment]
Closing this issue for the time being, as there haven't been any further updates on this.
