### ISSUE TITLE
Travis Log TTY Issues

### ISSUE THREAD

**Issue by jfelchner** [travis-ci/travis-ci#1337]
I'm not sure exactly how to go about fixing this so I'm going to lay out the details here and let smarter people than me on the Travis team take a stab.

I maintain ruby-progressbar, which is a pretty popular library.  One popular gem that uses ruby-progressbar is fuubar, which I am a co-maintainer of.  In case you don't know, fuubar is a progress formatter for RSpec.

Since many people use fuubar as their primary progress formatter, I'd like to get it compatible with Travis.  Unfortunately, when run on Travis, users get output like this:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/6688873/log.txt

This causes the log to hit the (perfectly reasonable) 4MB limit and the build fails.

I added support to ruby-progressbar in v1.2.0 which will detect if the output of the bar is going to a TTY and if it isn't, it only outputs the bar at the end of the run rather than after every progress update.

Any redirection of the output of ruby-progressbar to a file now behaves correctly.

This should solve the problem, however it seems that the way Travis handles the the log output must make ruby-progressbar seem as though it's running in a TTY environment.

Any ideas?

**Comment by kenorb** [comment]
Not sure what's the issue, but this [Python code of progress bar](http://stackoverflow.com/a/3160819/55075) [worked])(https://travis-ci.org/kenorb/travis-test/builds/119308690) for me, the same with `pv`.

![ci build](https://cloud.githubusercontent.com/assets/266306/14118390/286d473c-f5e1-11e5-8688-411c846ad663.gif)
