### ISSUE TITLE
Support custom virtual machine snapshots

### ISSUE THREAD

**Issue by krlmlr** [travis-ci/travis-ci#1338]
It is possible to install any kind of software in your builder virtual machines. However, this has to be done for every build. For [some execution environments](http://yihui.name/en/2013/04/travis-ci-general-purpose/) this takes a lot of time.

Is there any chance that custom VM snapshots will be supported? They could be taken after the `install` stage (perhaps as "incremental" snapshots) and used if and only if the "parent" VM image, and of course the `install` section of the `.travis.yml` file, haven't changed. Also, this feature could be disabled by default and enabled only with a configuration setting. A storage limit could be placed on the snapshots, and snapshots could be reused by projects with identical `install` sections.

Sorry if this has popped up before.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
