### ISSUE TITLE
sudo resets PATH to a secure default

### ISSUE THREAD

**Issue by roidrage** [travis-ci/travis-ci#1350]
In our current configuration, sudo overrides the $PATH, which contains all of the commands useful for a build.

There's an option in the /etc/sudoers file for this, called secure_path.

Is there any reason we should keep it in there?

Notable workaround to remove the default and make sudo commands use the full $PATH: `sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers`

**Comment by BanzaiMan** [comment]
GVM is no longer in use.

**Comment by wagner-certat** [comment]
I'm using this workaround now: `sudo sed -i '/^Defaults\tsecure_path.*$/ d' /etc/sudoers`

**Comment by Unitech** [comment]
```
script:
  - sudo env "PATH=$PATH" npm test
```
