### ISSUE TITLE
Terminal output - support nested folding

### ISSUE THREAD

**Issue by vojtajina** [travis-ci/travis-ci#1352]
This should work:

``` bash
echo -e "travis_fold:start:parent\r"
echo -e "travis_fold:start:child\r"
echo -e "travis_fold:end:child\r"
echo -e "travis_fold:end:parent\r"
```

Related to #1015

**Comment by kernc** [comment]
It [doesn't work](https://travis-ci.org/zidarsk8/orange3/jobs/119569914#L313) (doesn't unfold in either browser) when two `travis_fold:start` calls are consecutive:
```text
travis_fold:start:33722472496
travis_fold:start:10888229928255
...
```

**Comment by backspace** [comment]
@LaurentGoderre said:
> Something to be mindful about every fold must have a unique name within a single build. If more than one fold has the same name, they will be merged into one with unpredictable results.

Yes, this was a longstanding bug. I have since deployed [this fix](https://github.com/travis-ci/travis-web/pull/727) so multiple folds can have the same name and the log should still render properly. Nested folds are not supported, however.
