### ISSUE TITLE
util-linux compilation issue, xmalloc error

### ISSUE THREAD

**Issue by errge** [travis-ci/travis-ci#1357]
I get this during an innocent looking util-linux rebuilding:

bash: xmalloc: ../bash/locale.c:73: cannot allocate 2 bytes (0 bytes allocated)

The same stuff works on my desktop in i386/amd64 mode in minimal lxc sandboxes/chroots too.  So this seems to be something specific to openvz + 2.6.32 or I don't know what.  Google is not helpful, brings some OpenVZ results, but no solutions/workarounds.

The failing build is this one: https://s3.amazonaws.com/archive.travis-ci.org/jobs/10582378/log.txt

Any ideas?  Any way I can help you to debug this?

**Comment by udarav2807** [comment]
> I found a workaround, nevermind.

Can I know the work around?
I was cross compiling bash for armv7l huawei router, small but a hobby project. I am stuck on this error.
`bash: xmalloc: locale.c:90: cannot allocate 12 bytes`
