### ISSUE TITLE
Add branch history view

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#1363]
From doing on-site support with a customer: They would like a history view on a per branch basis. This is currently possible via `travis history -b branch-name`, but quite slow for them, as this command loads all builds and filters them on the client side and they have a crazy amount of branches and API is slow.

It would make sense to add the filter in the `find_builds` service, so it can be used via the API, which would also speed up the command line client.

**Comment by DanTup** [comment]
I don't know if it's the same request, but I currently have badges in my readme that are scoped to a branch, like this:

[![Linux & Mac build status](https://img.shields.io/travis/Dart-Code/Dart-Code/master.svg?label=mac+%26+linux)](https://travis-ci.org/Dart-Code/Dart-Code)

However the link doesn't go to a specific branch, it just shows the last build ("current") which is really confusing. It'd be nice if we could put `branches/master` on the end, even if it just redirects.
