### ISSUE TITLE
§ character in travis.yml global envs causes build to stall

### ISSUE THREAD

**Issue by sandfox** [travis-ci/travis-ci#1376]
After speaking with @joshk on IRC he said I raise this with you guys. It's not actually problem for us at the moment as the offending character was in there by mistake but Josh said you'd be interested in know why this happens.

See this gist for more info:: https://gist.github.com/sandfox/611f6d54139515d1b8f4
(the gist is a slightly abbreviated version of our actual travis.yml).

We're running on travis-pro if thats makes a difference somehow. Let me know if you need anything else from us.

**Comment by Vdragon** [comment]
It seems that I'm affected by this issue too, I have a after_script command `java -jar "Java 程式設計世界哈囉！(Hello Java world!).jar"` to run the built java archive, but [the build fails](https://travis-ci.org/Vdragon/Hello_Java_world_/builds/46959469).

*Please assume it UTF-8*

**Comment by Vdragon** [comment]
Is it sane to rename this issue as "build fails when .travis.yml contains non-ASCII characters" or should I file a separate issue?

**Comment by tilsche** [comment]
I just ran into the same issue with unicode branch names. Is there any progress on this issue?

**Comment by BanzaiMan** [comment]
It *might* be a good idea to use the idea used in https://github.com/travis-ci/travis-build/pull/936 to set some `$TRAVIS_*` values which may contain non-ASCII characters. There is some risk in doing so, when the GitHub payload and `git` command output may differ.

**Comment by g1itch** [comment]
So is there still no way to use non-ASCII characters in `.travis.yml`? After 5 years?
