### ISSUE TITLE
Update gcc

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#1379]
See travis-ci/travis-core#195.

In summary: Upgrade the gcc version to something that supports `-std=c++11`, for example 4.7.2.

From the original issue, it looks like this would do it:

```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get -qq update
sudo apt-get -qq install g++-4.7
```

However, that would install the binary as `gcc-4.7`.

**Comment by BanzaiMan** [comment]
I'm going to close this now, as we've shipped Trusty support.
