### ISSUE TITLE
Truncated description of jobs with many env-vars 

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#1384]
There is no easy way to see the settings of some jobs here https://travis-ci.org/dbsrgits/dbix-class/builds/10738520. A wrap-text style for the ENV column would be more approproate.

**Comment by ribasushi** [comment]
@saltinejustine @BanzaiMan Any word on this issue? I get that this is a UI-design vs usability issue (the css rule for wrapping itself is trivial). Can someone rule on this so the bug doesn't languish open?

**Comment by joshk** [comment]
We have some big changes in the works which will work towards addressing this issue, and others. 

I'm sorry but we don't have an ETA to share at the moment.

**Comment by ribasushi** [comment]
Please consider this issue when solving https://github.com/travis-ci/travis-ci/issues/3386. Thank you!

**Comment by ribasushi** [comment]
Um... this issue seems to have been closed without a resolution?

For example the only way I can read the full description of [`build 2259.12`](https://travis-ci.org/dbsrgits/dbix-class/builds/69641999) is by zooming out to 33%, at which point the font becomes unreadable...

**Comment by saltinejustine** [comment]
Hey @ribasushi. If you hover over a row you can see a longer version of the env var, or if it's still cut off you can click on the job you can read the full description in the log.

The job list is a summary of that information. We consider this issue resolved.
