### ISSUE TITLE
security: remove need for admin permissions over repos

### ISSUE THREAD

**Issue by travis-tahoe** [travis-ci/travis-ci#1390]
As mentioned at the end of http://about.travis-ci.org/blog/2012-09-04-pull-requests-just-got-even-more-awesome/, Travis-CI needs admin permissions for the repo it is reporting on. This seems like excess authority -- there's no reason why Travis should be able to modify the repo or change any of its settings.

It may be that this is the best that can be done with GitHub's current access control model, in which case GitHub should be encouraged to separate out the permissions that are actually required for build status tracking.

**Comment by VadzimBelski-ScienceSoft** [comment]
Hi, looks like we need access to repository itself from travis

http://docs.travis-ci.com/user/private-dependencies/

Its pretty described here.

**Comment by jaredbeck** [comment]
I just tried again, after giving up on this back in February 2014, and the permissions (for a public repo) seemed much more reasonable this time around.  The only write access I noticed was to webhooks.

Big :heart: to @roidrage  @rkh @henrikhodne what a fantastic tool!  The ability to easily test multiple rubies has inspired me to target multiple rubies with the lib I'm working on .. funny how that works :)  Make it easy for devs to do the right thing and it happens.  Job well done.

**Comment by NeoLegends** [comment]
I'm still seeing write access to code being asked for when I recently enabled travis CI on one of our repos using the new integration. Do you have any updates on how the permissions-reducing has come forward?

**Comment by LucasForster** [comment]
On the frontpage it says "We are moving to our new community forum: Travis CI Community!" (Whatever may be wrong with GitHub...). There, [a more recent discussion](https://travis-ci.community/t/is-there-a-plan-to-stop-travis-requesting-read-write-access-on-travis-ci-com-login/1364) states that a coming up switch to "integration via GitHub Apps" would introduce more granular permissions.

I totally agree with the people there complaining that everyone is led to travis-ci.com while only the (deprecated?) .org version has this permission issue fixed at the moment.

Would be nice to hear a little more details in this manner to make a more future proof decision.

Thanks
