### ISSUE TITLE
Custom maven script not executed, always fallbacks to default one

### ISSUE THREAD

**Issue by milanaleksic** [travis-ci/travis-ci#1400]
I have set up my .travis.yml on location https://github.com/milanaleksic/baobab/blob/develop/.travis.yml like this:

```
language: java
script: "mvn --debug clean compile"
jdk:
  - oraclejdk7
```

but as far as I can see travis always execute default _mvn install -DskipTests=true -B_, example:
https://travis-ci.org/milanaleksic/baobab/builds/11015705

**Comment by jsotuyod** [comment]
This issue just saved me. The doc for overriding the default build step is completely misleading, sending you to a link were `script:` is overriden, and not `install`.

If the docs were be updated it would be awesome.
