### ISSUE TITLE
UI breaks with very long branch names

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#1403]
From our awesome friend @madrobby

The user interface kinda breaks down if you have commits in branches with very-long-names-that-are-only-separeated-with-dashes. The table in the middle becomes too wide and I can't see committers and durations any more.

We have a branch called "242-projects-can-be-deleted-even-if-they-have-expenses-or-invoices", if you want to test with something.

I suggest to add "word-wrap: break-word" to the "commit" column.

cc/@drogus

**Comment by saltinejustine** [comment]
We fixed this in the UI with a simple fade overflow. Closing this.
