### ISSUE TITLE
When placing computer to sleep, build says it has never finished

### ISSUE THREAD

**Issue by Joshua-Anderson** [travis-ci/travis-ci#1415]
Hello, on windows 7 and chrome (and probably chrome on other os's and possibly other browsers, I haven't checked yet) if you open up a unfinished build in chrome and then put your computer to sleep, strange things start to happen. Until you hit the refresh button on the browser, it thinks your build is still running (I got mine to say build had been running for 40 minutes :) )  and it shows build status as incomplete, even if the build console shows that it has finished and returned with 0. I was using a nodejs build but I doubt that it is specific to that language, as this appears to be a frontend problem only. Thanks for the great work on travis ci!

**Comment by joshk** [comment]
Closing this issue as it's gone stale.

Thank you for creating it!
