### ISSUE TITLE
Provide Docker in CI Environment (and free your CI horizon)

### ISSUE THREAD

**Issue by gildegoma** [travis-ci/travis-ci#1418]
I know that such feature request is not realistic *right now*, but things are going so fast (especially when we speak about Docker). According to [DOCKER 1.0 Roadmap (August 2013)](http://blog.docker.io/2013/08/getting-to-docker-1-0/), Docker inside OpenVZ container will certainly work "one day" :tada: 

> Once we’ve made these [stabilizing] changes, the core of Docker will change much less frequently, and will be easier to test against different platforms. By the same token, it will become significantly easier to build plug-ins to extend functionality (e.g. adding orchestration and security). Similarly, it should make it easier for us to extend Docker to support other container formats (e.g. BSD Jails, Solaris Zones, **OpenVZ** )

I propose to use this issue to confirm user interests and track progress of its possible implementation... 

See also related feature requests:
* #1370 (Support of custom VM images)
* #1273 (Request for LXC containers on travis-ci)
* #1196 (Travis CI still runs with linux kernel 2.6.x)

**Comment by joshk** [comment]
This is currently in beta, and will be GA in a couple of weeks. I'm going to close this issue for now.
