### ISSUE TITLE
Provide KVM virtualization in CI Environment

### ISSUE THREAD

**Issue by gildegoma** [travis-ci/travis-ci#1419]
Having linux kernel KVM capability on top of current OpenVZ container sounds pretty cool and possible. To name a few, it would allow following CI usage:

* Continuous Integration for DevOps, for instance with Vagrant via [vagrant-kvm](https://github.com/adrahon/vagrant-kvm) plugin. Note that such use case could be superseded by running Docker (see #1418)
* More performant Android emulator, thanks to [Intel HAXM](http://software.intel.com/en-us/articles/intel-hardware-accelerated-execution-manager). See #1395.
* Run tests on some QEMU/KVM images (could also somehow address #1370 ?)

Note: I have no experience so far with KVM-virtualization on top of OpenVZ paravirtualization. I just ran a first attempt [here](https://travis-ci.org/gildegoma/travis-ci-inspector/builds/11230285#L2557) and deduced that `kvm` kernel modules are probably not installed/exposed in the OpenVZ host.  Feebacks are more than welcome!

**Comment by joshk** [comment]
We have some special sauce in the works, which should be announced in a couple of weeks.

I'm going to close this issue for now.

**Comment by JolandaVerhoef** [comment]
@joshk It's been a couple of weeks. Any news? :)

**Comment by BanzaiMan** [comment]
@JolandaVerhoef It's *really* close, we promise! We've had a few vacations (yay!) and lagging a bit. Thanks for your patience!

**Comment by davedoesdev** [comment]
Is `kvm` going to be available using `sudo: 9000` / `sudo: required` ?

**Comment by joshk** [comment]
We are working on the full story of what we will be offering on .org and .com, as well as what is possible within each of them.

If you need a full hypervisor environment, please use :
```yaml
sudo: required
services:
  - docker
```

**Comment by davedoesdev** [comment]
@joshkk thanks. Is kvm available in the full hypervisor environment?

**Comment by davedoesdev** [comment]
The full hypervisor environment is pretty good though - having bind and loop mounts available is really cool.

**Comment by joshk** [comment]
I am not 100% sure you can use KVM within the full hypervisor, feel free to play around and check though.

**Comment by dr03lf** [comment]
Hi @joshk @BanzaiMan are there any news on this issue? 
I tried to use
```
sudo: required
services:
  - docker
```
but still no kvm/HAXM support. Or do I've missed something?

**Comment by joshk** [comment]
Hi @dr03lf 

The config should give you a full hypervisor, which is essentially the same as using KVM.

**Comment by dr03lf** [comment]
Thanks for your response @joshk . Does this mean, the CPU has support for the `vmx` flag? 

I played around and haven't seen any virtualisation support on a CPU level. https://travis-ci.org/dr03lf/fun_with_travis/builds/85735911#L837

**Comment by joshk** [comment]
@dr03lf could you explain your use case further? I don't think you can use KVM within this Hypervisor, as that would be virt within virt.

Do you need to use KVM within the VM? Or can you just use the VM itself?

**Comment by dr03lf** [comment]
Ok, thanks. I want to get hardware acceleration for the Android emulator. Therefore I need a cpu that hast support for the `vmx` flag. 
Basically yes, I want to run a VM in a VM. I think with KVM as a hypervisor it is possible. (http://kashyapc.com/2012/01/14/nested-virtualization-with-kvm-intel/)

**Comment by joshk** [comment]
KVM is not the underlying hypervisor, at least from what I know.

I'm sorry but I don't think this is doable at the moment.

**Comment by dr03lf** [comment]
It isn't? https://travis-ci.org/dr03lf/fun_with_travis/builds/85735911#L421

Ok, thank you anyway. Will it be possible a some point?

**Comment by joshk** [comment]
We are using Google Compute Engine under the hood. We don't have the ability to change any of the low level settings. It is good to see they are using KVM, or at least reporting KVM.

**Comment by barbeau** [comment]
Just to ellaborate on the Android use case further - executing Android unit tests on Travis requires a running Android emulator.  Without hardware acceleration, spinning up an emulator is really slow.  As a result, the current avg Travis build time for Android projects including unit tests is around 10 min:
https://travis-ci.org/barbeau/android-maps-utils/builds/83987420

If hardware acceleration is available on Travis, in theory this should reduce the time required to spin up the emulator and as a result shorten Travis build times.

**Comment by niltonvasques** [comment]
:+1:

**Comment by gregriggins36** [comment]
+1

**Comment by BanzaiMan** [comment]
Instead of commenting with +1, please subscribe to the issue.

**Comment by BanzaiMan** [comment]
If we have updates, we will share them here.
