### ISSUE TITLE
Cache downloaded Maven artifacts

### ISSUE THREAD

**Issue by electrum** [travis-ci/travis-ci#1441]
The build time for Java projects using Maven is often dominated by the time required to download all of the dependencies and plugins from Maven central. For example, this simple project took 3.5 minutes to perform the download: https://travis-ci.org/airlift/stackfold

A relatively straight forward solution is to setup a local repository manager (such as http://www.sonatype.org/nexus/) and configure that as a mirror for Maven central. Nexus performs lazy caching of artifacts. Staleness issues can be avoid by configuring it to always check for snapshot updates. Released artifacts are immutable and thus can be cached forever.

**Comment by FagnerMartinsBrack** [comment]
@gildegoma 

Does maven caching prevents one from using sudo? What if I want to use apt-get to install a missing package in Travis (needs `sudo: required`) and use maven with cache at the same time?

**Comment by gildegoma** [comment]
@FagnerMartinsBrack 

On the container based infrastructure, you need to use the apt addons. See http://docs.travis-ci.com/user/apt/.

**Comment by BanzaiMan** [comment]
I don't think there is anything to do here. If you can use the containers and its caching mechanism, you can specify

```yaml
cache:
  directories:
    - $HOME/.m2
```

**Comment by regisd** [comment]
@BanzaiMan I'm sorry to disagree: The cache is build-matrix dependent, and also depends on pull request or branch.
Hence, the first compilation for a pull request needs to download everything again, which causes excessive load on the central repo, causing #10055 
Having your own repository manager near the build VM is definitely a best practice https://twitter.com/sonatypeDev/status/1036734093529047040

**Comment by BanzaiMan** [comment]
> Hence, the first compilation for a pull request needs to download everything again

This sounds wrong to me. PR builds should look for caches from their respective base branch, and failing that, from the default branch. Do you have a build log to show this behavior?

**Comment by regisd** [comment]
@BanzaiMan Apologies, you are right, the cache is restored on a PR.
