### ISSUE TITLE
Environment variables truncated at first whitespace

### ISSUE THREAD

**Issue by alekstorm** [travis-ci/travis-ci#1444]
A config section like:

```
env:
  global:
    NOSE_ARGS: slow and not network
```

Is executed in the shell as:

```
export NOSE_ARGS=slow
```

This is very surprising; I expected values in the `env` section to be automatically enclosed in quotes and have any internal quotes escaped. Is there something preventing this from being done?

The workaround is to manually enclose the value in quotes, which is not intuitive to novice bash programmers and looks quite ugly in YAML:

```
NOSE_ARGS: "'slow and not network'"
```

**Comment by iwasrobbed** [comment]
This is happening when I try and build w/ a matrix and multiple env variables. I've tried 5 different permutations of wrapping it in quotes, using the weird `'"` quotes shown above, using colons, using equal signs, etc. 

- Equal signs w/ quotes still truncates at the first space
- Colons don't work anymore
- Works fine when I export and echo locally

```
env:
  matrix:
    - WORKSPACE='folder/project.xcworkspace' SCHEME='Scheme Name Here'
    - WORKSPACE='otherfolder/project.xcworkspace' SCHEME='Scheme Name Here'
```
