### ISSUE TITLE
xcodebuild + homebrew missing

### ISSUE THREAD

**Issue by AliSoftware** [travis-ci/travis-ci#1461]
Builds were passing fine before, but as I commited a small change in my README.md today, Travis can't build anymore, it seems like the Travis VM is missing both Xcode and Homebrew:

> ```
> $ xcodebuild -version -sdk
> /home/travis/build.sh: line 126: xcodebuild: command not found
> $ brew update
> /home/travis/build.sh: line 141: brew: command not found
> ```

See [travis log here](https://travis-ci.org/AliSoftware/OHHTTPStubs/builds/11822007)
See [my `.travis.yml` file here](https://raw.github.com/AliSoftware/OHHTTPStubs/master/.travis.yml)

What seems strange to me is that is seems like Travis even ignores my `.travis.yml` file as it seems to execute a build-in `build.sh` instead, and try to launch `xcodebuild` whereas my `.travis.yml` asks to execute `xctool` instead…

Previous builds (like [this one](https://travis-ci.org/AliSoftware/OHHTTPStubs/builds/11640494) worked fine before (and as I only changed a typo in my `README.md` it should build exactly as before)

Thx

**Comment by nacho4d** [comment]
I am having similar issues now.  Eventhough I am setting osx , linux image is being used? I am in an enterprise installation. I hope this is solved soon.

    language: objective-c
    osx_image: xcode8.2
    script:
      - uname -a

> $ uname -a
> Linux testing-gce-d84822a8-58de-458b-8ab8-9153d5db0261 4.4.0-62-generic #83~14.04.1-Ubuntu SMP Wed Jan 18 18:10:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> The command "uname -a" exited with 0.

**Comment by BanzaiMan** [comment]
@nacho4d After 3.5 years, your issue is most definitely different from this issue. Please open a new issue, along with the complete configuration and the URL to the build log that shows your problem. Thank you.
