### ISSUE TITLE
Feature Request: automatically create (and push) Git tag after successful build

### ISSUE THREAD

**Issue by wireframe** [travis-ci/travis-ci#1476]
I'm able to (kindof) accomplish this via .travis.yaml `after_success`, but it's clunky to say the least and seems like a prime candidate for some kind of support built right into travis.

example work around:

``` yml
after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG
```

**Comment by mgk** [comment]
Any thoughts to re-opening this? I have used the manual method (thanks @wireframe). While workable, it is clunky and can easily cause an infinite build loop, as has been discussed.

Security note: the ` > /dev/null 2>&1` part of the the `git push` command is important. Without it your GH token can be exposed in the downloaded build log even though it is a hidden environment variable.

**Comment by danielbodart** [comment]
Any chance this can be reopened? Seems a bit crazy to have Git Releases as a deploy stage that requires a Git Tag but no built in way to create the tag. 

As Git Releases already has your token and is calling the GitHub API, you could very easily have a optional create tag flag and just call the tag API first before the release.

**Comment by stardust85** [comment]
Please re-open this. Maybe this is a good candidate for an item on bountysource ;) People willing for this can bid for a pull request fixing this...

**Comment by alxndrsn** [comment]
:+1: this would be great

**Comment by pbek** [comment]
This would be really great!

**Comment by roidrage** [comment]
Sorry, but this feature isn't on our immediate roadmap.

We'll update this ticket when we reconsider that in the future.
