### ISSUE TITLE
Improve auto sync to be more resilient to failure

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#1478]
Last night we ran into some issues with flakey Redis connectivity which effected auto sync for users.

If we get an error, for any reason, including redis connectivity, we flush out the users oauth token.

On a side note, we should look into how to inform users of this as well, as it affects our ability to process build requests and update commit statuses on GitHub.

**Comment by BanzaiMan** [comment]
We have made many improvements on sync in recent months. I'm closing this.
