### ISSUE TITLE
Filter out secure env variables from logs

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#1487]
When using secure env vars, they can be exposed by various scripts, for example as a debug output. 

We were thinking about filtering logs at some point, but it was never implemented.

The simplest implementation could take all the secure env variables and replace them with something else, for example `$ENV_NAME`. So if there is an ouput like:

```
Password used for logging in is foo-bar-baz.
```

and the password is stored in env named `FOO_PASSWORD`, the log output would be the following:

```
Password used for logging in is $FOO_PASSWORD.
```

Or maybe just:

```
Password used for logging in is FOO_PASSWORD.
```

**Comment by liddellj** [comment]
I think this is a serious issue. I followed the example in the Travis documentation for pushing a Docker image to a registry (http://docs.travis-ci.com/user/docker/) - and I can now see my docker credentials in plain text on my build logs for the `docker login` command - disappointing considering I was following an example from the official docs...

**Comment by BanzaiMan** [comment]
@liddellj Sorry to hear about your problem. How did the information leak? When I use the same commands, I get:

https://travis-ci.org/BanzaiMan/travis_production_test/builds/79313490#L39-L40
```sh-session
$ docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
Error response from daemon: Wrong login/password, please try again
The command "docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"" exited with 1.
```

**Comment by liddellj** [comment]
When issuing the `docker login` command from `.travis.yml` it appeared as in your example. However, I later refactored the same command to be triggered from within a make target (still using the environment variables). In that case - the environment variables were expanded when the command was executed and they were shown in plain text in the build log. I can't link to an example because I have since deleted all the build logs (and changed the password of course).

I now realise that the secure display of environment variables is restricted to commands directly executed from .travis.yml - but this seems like an easy trap to fall into when refactoring build scripts.

**Comment by danydev** [comment]
@BanzaiMan Same problem here, I didn't realize at fist that secure env are not so secure (i.e. plain text is printed on the logs) when used on a bash script or similar.
Do you think to reopen the case or have fixed it somehow?

**Comment by illume** [comment]
I just got bitten by this. Whilst filtering is good, also allowing people to inject the 'secure' env vars only in certain sections could help. So you could do your business with just the command that requires it. This would limit the chances of leakage somewhat.

**Comment by Novex** [comment]
I included a `printenv` command while debugging a travis script and got bitten by this too.

It would be very nice if secure variables were masked in log output by default.

**Comment by BanzaiMan** [comment]
Hello, everyone.

We have implemented a log filter to obfuscate secrets now. Please read https://blog.travis-ci.com/2017-05-08-security-advisory.

We believe this can be closed now. If you see issues, please get in touch with us at support@travis-ci.com with details.

Thank you.
