### ISSUE TITLE
very low entropy, gpg key creation takes very long

### ISSUE THREAD

**Issue by adrelanos** [travis-ci/travis-ci#1494]
Travis CI's systems have very low entropy. Creating a gpg key usually takes only seconds on modern systems. Takes about 9 minutes on Travis CI's systems.

Solving #1495 could also solve this one.

Github Repository:
https://github.com/adrelanos/gpg-key-creation-test

Build Log:
https://api.travis-ci.org/jobs/12215464/log.txt?deansi=true

Travis Links:
https://travis-ci.org/adrelanos/gpg-key-creation-test

**Comment by nakedible-p** [comment]
@BanzaiMan "next week" was in august - any news on this?

**Comment by BanzaiMan** [comment]
Sorry about the lack of updates. I have talked to our infrastructure service providers, and so far I have not been able to come to a reasonable solution regarding `haveged` or another solution.

**Comment by nakedible-p** [comment]
FWIW, what we do in our travis builds these days is:
```
 - sudo cp -a /dev/urandom /dev/random
```
This solves the issue for us as urandom does not block and is good enough for CI, and no software will know the difference unless they specifically go looking for major/minor device numbers or something.

**Comment by phax** [comment]
For pure Java build, the following does the trick for me:
```
before_script:
# should be empty
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
```

**Comment by phax** [comment]
For me, the following solution for Java projects did the trick:
```
before_script:
 - "export JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
 - "export MAVEN_OPTS=-Djava.security.egd=file:/dev/./urandom"
```
