### ISSUE TITLE
Encrypted environment settings not working

### ISSUE THREAD

**Issue by azul** [travis-ci/travis-ci#1500]
I can't get encrypted configuration values to work in .travis.yml
here's the change to travis.yml and the test that is failing:
https://github.com/leapcode/leap_web/pull/97/files
and here's the build: https://travis-ci.org/leapcode/leap_web/builds/12405833

I created the secret: ... line with "travis encrypt SOMEVAR=secretvalue"
--debug shows that it is using the leapcode/leap_web repo - which should be fine.
Any ideas why this is failing?
First thing that surprised me is that running the same travis encrypt command 
over and over again i get different values. I would have assumed that they are 
deterministic.

**Comment by binodluitel** [comment]
https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions
