### ISSUE TITLE
Collect ecosystem-wide compatibility statistics

### ISSUE THREAD

**Issue by michaelklishin** [travis-ci/travis-ci#151]
Since we track builds against JRuby, I think we should collect a list of JRuby-compatible libraries. Criteria I have in mind is "80% build success on JRuby". If we can provide a full list of libraries, I think this will be a unique resource for the JRuby community. I guess we can periodically publish it over at jruby.org.

CC: @svenfuchs @ifesdjeen

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
