### ISSUE TITLE
Caching solution (Maven,Ruby,Apt,Http)

### ISSUE THREAD

**Issue by smarek** [travis-ci/travis-ci#1510]
Hello,

First, let me thank you for this wonderful service.
Second, let me describe possible caching solution, as I see it.

This is possible duplicate for already opened #1441, #1401, #834, #876. 

Provide via configuration caches for services:
- Ruby Gems
- Maven Artifacts
- Debian packages (APT)
- Custom HTTP_URL/FILE (caching verified by md5, etag, if-modified-since, ...)
- more?

Every cache should be optional, configurable for worker VM template.
It would be probably good idea to add special type of VM, to hold these cache services (one virtual machine, one caching service), in same way now it does with worker VMs

Thing that bothers me now the most is I work with Android projects, and for each build iteration I need to download 3-5 packages with Android SDK, build tools, Gradle tools, ... And I'd really love to see this downloads in matter of seconds instead of waiting 30minutes if the remote server is currently overloaded.

Thanks in advance

**Comment by venediktov** [comment]
I tried solution suggested by txomon , but it's still downloading boost libraries by wget 

https://github.com/venediktov/CRUD/blob/master/.travis.yml

Can someone take a look and help us figure out how to stop downloading and building external libraries 
after it's done for the first time ?
