### ISSUE TITLE
Allow cloning using https URLs with the GitHub OAuth token

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#1524]
GitHub allows cloning repositories using an OAuth token in https URLs as such:

```
 $ git clone https://$GH_TOKEN@github.com/owner/repo.git
```

Any reason why we don't do this? This could help clean up having to use deploy keys on travis-ci.com.

**Comment by jameswald** [comment]
Another reason one may not want to clone with the token as part of the URL:

> Warning: Tokens have read/write access and should be treated like passwords. If you enter your token into the clone URL when cloning or adding a remote, Git writes it to your .git/config file in plain text, which is a security risk.

https://help.github.com/articles/git-automation-with-oauth-tokens/

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-scheduler/pull/53 and https://github.com/travis-ci/travis-build/pull/804.

**Comment by rkh** [comment]
@BanzaiMan do we have an internal issue for this? I'd like to get some more insight.

I think we could default to this once we have integrations fully implemented (as we could generate a throw away access token for a single repo per build).

**Comment by BanzaiMan** [comment]
@rkh I've pinged you on the internal issue. Maybe you missed it.
