### ISSUE TITLE
Allow issue links to be configurable (github vs. some other tracker).

### ISSUE THREAD

**Issue by denishaskin** [travis-ci/travis-ci#1529]
We use Pivotal Tracker, not Github, for our issues (it is a public project, though).  Travis assumes #nnnn in a commit log points to Github.

Make this configurable so that a project can specify an alternate issue tracker.

For example, see https://travis-ci.org/camsys/oneclick/builds/12827999

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
