### ISSUE TITLE
Profile sync gets stuck when user has access to lots of repositories

### ISSUE THREAD

**Issue by patrys** [travis-ci/travis-ci#1530]
My GitHub account ([patrys](https://github.com/patrys/)) has access to around 20k repositories. It seems Travis gets stuck trying to import these. Syncing them all seems rather unpractical. It would be better to only sync repos that belong to me directly and let me enter other repositories by hand (then only sync one on demand).

**Comment by BanzaiMan** [comment]
I believe we've fixed this with recent updates to sync mechanism. I know we have a user with 40K+ repositories and we can sync it.
