### ISSUE TITLE
Make pip use wheels for common packages

### ISSUE THREAD

**Issue by patrys** [travis-ci/travis-ci#1531]
Python packages like Pillow and pycrypto takes a long time to download and compile. Travis could tell pip to use a shared wheel directory and fetch packages from there effectively reducing some builds from minutes to seconds.

**Comment by blueyed** [comment]
Looking at e.g. `lxml` it's not trivial to provide wheels.

See the discussion at https://bugs.launchpad.net/lxml/+bug/1176147.

It would have to be statically linked, and that appears to fail when tried with `pip wheel --build-option '--static-deps' lxml`:

    ...
    gcc -DHAVE_CONFIG_H -DEXEEXT=\"\" -I. -I.. -I../lib  -I../intl -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1   -g -O2 -c progname.c
    In file included from progname.c:26:0:
    ./stdio.h:1010:1: error: ‘gets’ undeclared here (not in a function)
     _GL_WARN_ON_USE (gets, "gets is a security hole - use fgets instead");
     ^
    Makefile:914: recipe for target 'progname.o' failed
    ...

For lxml, using `CFLAGS=-O0 pip install lxml` appears to be the best
alternative currently, and its maybe a good idea to `export` it for all binary
installs.

**Comment by davedash** [comment]
So after spending a lot of time experimenting with wheels - they are best used in the exact same platform that they were generated.

Meaning, if you are on Ubuntu 12.04 you should run lxml from 12.04.  I'm not sure if this would be as easy to do in Travis as I originally hoped.... but it maybe.

**Comment by patrys** [comment]
Wouldn't it give enough boost even if wheels were not shared between build hosts? I feel that even a local cache would mean that each dependency would only be built once per version per worker.

**Comment by blueyed** [comment]
> Plus, our current cache solution solves this issue already.

For reference: http://docs.travis-ci.com/user/caching/

I've just added it to a project: https://github.com/yourlabs/django-autocomplete-light/pull/366/files

**Comment by blueyed** [comment]
Another reference, injecting `travis_retry` and wheelhouse caching into tox: https://github.com/yourlabs/django-autocomplete-light/blob/master/.travis.yml

**Comment by alex** [comment]
Now that pip automatically builds and caches wheels, if you turn on travis caching for `$HOME/.cache/pip`, this just works. I think it's fair to close this. /cc @dstufft

**Comment by thedrow** [comment]
@alex This issue should be closed when Travis will upgrade their pip version.

**Comment by BanzaiMan** [comment]
Build env update still needs to be scheduled. Meantime, is it permissible (or feasible) to force `pip` update on every Python build?
