### ISSUE TITLE
Unresponsive Script blocks Firefox browser (on Mac)

### ISSUE THREAD

**Issue by petervandenabeele** [travis-ci/travis-ci#1535]
An unresponsive script is reported on app.js:20 and this essentially blocks my entire Firefox on Mac browser until I confirm "Stop Script". See screen shot.

![screen shot 2013-10-22 at 13 37 30](https://f.cloud.github.com/assets/55656/1380710/9d62d2ea-3b0e-11e3-9458-4d3501504515.png)

I had never seen this before, started on 2013-10-22 around 13:35 CEST (11:35 UTC).

**Comment by ophchu** [comment]
I see it almost all the time.
Actually it happens for me on both, Chrome and Firefox and stuck my browser over and over.
Very annoying and actually prevent me from doing my job :(

Ubuntu 15.10, Firefox 45.0, Chrome something.
Please help!
