### ISSUE TITLE
Case Sensitivity in Travis-CI username and repo url's

### ISSUE THREAD

**Issue by Joshua-Anderson** [travis-ci/travis-ci#1545]
I have noticed an weird thing in travis-ci repo/username paths.
Github doesn't care at all about the case of a username or repo. However, when you try and find a travis-ci repo page, you have to get the case right. If you don't, you get a very unintuitive error : `The respository at <respository with wrong case> was not found` When getting this error, It has made me think that travis is having an issue with my repo, not that I miscapitalized it.

Is there any technical reasons that you have to have a case sensitive path?

Keep up the great work with Travis CI!

**Comment by jnothman** [comment]
> URLs are case sensitive and GitHub is doing it wrong :)

Perhaps. But it does leave the user in a confusing mess when, say, coveralls integration doesn't work because Travis got told it was somerepository (because of being registered before a name change) and Coveralls got told it was SomeReposiTory

**Comment by mkk-fullscreen** [comment]
URLs became case sensitive again about a month ago. Can we get them to be case insensitive again? My alias for opening travis based on `pwd` has broken.
