### ISSUE TITLE
Add support for testing R code to travis

### ISSUE THREAD

**Issue by craigcitro** [travis-ci/travis-ci#1549]
hi all,

i'd like to find out what it would take to make [R](http://r-project.org) a first-class citizen for travis. i recently created a [repo](http://github.com/craigcitro/r-travis) with some terribly lowbrow scripts for testing out R on travis -- we're still working through details to streamline how we'd like things to work, but it definitely seems like there's interest. 

i've got a bunch of questions:
- is there any sort of "official" process for adding a new language?
- should I start by converting everything to a chef cookbook and sending you a pull request [here](https://github.com/travis-ci/travis-cookbooks)?
- clearly i'll ultimately need to send PRs for a cookbook and some docs; are there other  bits i'm not thinking of?
- is there a CLA?
- the readme for travis-cookbooks points to travis-boxes, which has a giant DEPRECATED note at the top; is there a replacement?

thanks!

**Comment by craigcitro** [comment]
@joshk or @roidrage any thoughts?

**Comment by eddelbuettel** [comment]
It's time. Otherwise people may just defect to [CircleCI](https://circleci.com/) which from what I have been told allows deployment of custom Docker containers.   Which would a cheap(er) way for us to test R code.

Travis is great as is, and used pretty widely by R folks.  Making Travis easier and better can only help...

**Comment by joshk** [comment]
@craigcitro thanks for taking the time in Dec to write up your last comment. As this was Xmas time this kinda fell into the abyss of time-off.

I would recommend getting started with travis-build and we can comment on a PR there and help where possible. Any start is a good start.

Sorry but we can't use Docker images yet. This is on our roadmap, but no ETA sorry.

**Comment by craigcitro** [comment]
@joshk cool, sounds good. i've got a good chunk of a travis-build PR in the works, i'll send that out soon and go from there. 

i'll be excited to simplify when docker images are available, but converting the existing code is definitely the fastest path forward anyway.

don't sweat the x-mas abyss: any time i had to work got eaten by 2yo & 5yo both getting sick. `;)`

**Comment by joshk** [comment]
Awesome! We look forward to getting this merged in and live!

Have an awesome week!
