### ISSUE TITLE
Restart build button missing after signin

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#1585]
When I sign out and back in the "restart build" button is missing. When I reload the page the button shows up.

**Comment by eric-wieser** [comment]
I've been hit by that multiple times this week at https://travis-ci.org/github/pygae/clifford

**Comment by lorengordon** [comment]
This has been happening to me a lot recently. I have to clear all the travis-ci cookies and log back in, then it starts working again.

**Comment by dbrudner** [comment]
This has been happening to me too. I followed @lorengordon's steps and they fixed the issue 👍
