### ISSUE TITLE
RSA fingerprint missing for github.com

### ISSUE THREAD

**Issue by cburgmer** [travis-ci/travis-ci#1588]
When installing a Node module via npm from Github, I see the following output on the Travis console:

```
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?
```

The build fails after 10 minutes with the following message:

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

Excerpt from package.json:

```
"dependencies": {
    "cssom": "git+ssh://git@github.com:cburgmer/CSSOM.git#787dc0c55b5"
}
```

The affected run: https://travis-ci.org/cburgmer/rasterizeHTML.js/builds/13443693

Wild stab in the dark: Github disabling old IP addresses? https://github.com/blog/1675-disabling-old-ip-addresses

**Comment by jongear** [comment]
Can confirm this is still happening 

https://travis-ci.com/jongear/minidrone-ble/jobs/170325754#L147-L151
