### ISSUE TITLE
Enabled repository doesn't get built

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#1589]
I've setup on of my (forked) repository to sync with Travis. However, in my build status the repository doesn't show up. 
As there is no link to the repository on the travis side I'm also missing a frontend for validating the status, e.g. "syncing from github" or similar.

**Comment by qiu8310** [comment]
Happened on me, and I can't figure out what's wrong.

You can see https://travis-ci.org/qiu8310/smart-npm.

I have already pushed my repo after enable travis.
