### ISSUE TITLE
Tag builds fail if there is a branch with the same name as the tag

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#1590]
Since tags are treated as branches and we pass `--branch=branchname` to the `git clone` call, the checkout fails if the tagged commit is not included in the branch with the same name.

Here's an example for how to reproduce:
- Create a branch `v1.0.0` to develop for the 1.0.0 release. Push this branch.
- Merge the branch into master, add a commit that bumps some internal version number or changelog. Tag this commit `v1.0.0` and push it.

We will then clone repository, but only the `v1.0.0` branch, which does not include the commit tagged `v1.0.0`, causing the `git checkout` to fail.

**Comment by BanzaiMan** [comment]
With https://softwareengineering.stackexchange.com/a/230440/24816, I tend to think that tagging with the same name as a branch name is just a bad idea with git in general, and we should not encourage it by working around it. The problems are expected.

I'm closing this.
