### ISSUE TITLE
Travis pull request stuck at 'Created'

### ISSUE THREAD

**Issue by jhersh** [travis-ci/travis-ci#1595]
First, thanks for a great service!

I own this repo, which has been running great with Travis: https://github.com/splinesoft/SSDataSources

Today I received this pull request: https://github.com/splinesoft/SSDataSources/pull/16

Travis created this build to test the pull request: https://travis-ci.org/splinesoft/SSDataSources/builds/13606622

But the Travis build is stuck at "Created". I've created pull requests in this repo before and Travis has never had issues building; is there something going on because this pull request was created by a different user?

**Comment by lolgear** [comment]
@jhersh maybe commit to this issue could start build? Let's try.
