### ISSUE TITLE
Default Objective-C Build Broken?

### ISSUE THREAD

**Issue by jjgod** [travis-ci/travis-ci#1601]
Hi, I'm trying to setup Travis CI for a simple OS X project: https://github.com/jjgod/TextEditPlus

The project builds fine locally with command:

```
xcodebuild -scheme TextEdit -configuration Release build
```

Also `xcodebuild -list` command shows:

```
Information about project "TextEdit":
Targets:
    TextEdit

Build Configurations:
    Debug
    Release

If no build configuration is specified and -scheme is not passed then "Release" is used.

Schemes:
    TextEdit
```

However when it runs on the CI I got:

https://travis-ci.org/jjgod/TextEditPlus/builds/13776119

```
xcodebuild: error: The project 'TextEdit' does not contain a scheme named 'TextEdit'.
```

What did I miss here? Why couldn't xcodebuild use `TextEdit` scheme when `xcodebuild -list` already shows that?

**Comment by DanielAsher** [comment]
:+1:

**Comment by jaredsburrows** [comment]
@jjgod @henrikhodne Thank you for posting this!
