### ISSUE TITLE
Sucess determination should not wait for after_script

### ISSUE THREAD

**Issue by JeroenDeDauw** [travis-ci/travis-ci#1606]
(This is a re-post of the second point in #1587)

Anything run after after_success, after_failure or after_script is not relevant to determining if a task succeeded, so should also not be waited upon.

In one project of mine the tests take 1 min to run. The code coverage generation (which runs in after_script) however takes 5 minutes. It is really silly to have to wait that extra time to get a success indicator on a pull request.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by JeroenDeDauw** [comment]
IMO that is a weird way to use an issue tracker. If you have no plans to implement a feature request, then why not simply leave it unassigned to any milestone? How will you keep track of it when you close it?

**Comment by joshk** [comment]
@JeroenDeDauw Thanks for the feedback.

In regards to this particular issue, this feature request is actually not possible for us to implement with our current setup. As nice as it would be, it would require massive changes which we are not considering at this time.

Leaving issues open when we do not plan to tackle them creates noise in our issue tracker, and doesn't really add any value to how we use GitHub issues.

Managing our ever growing GitHub issues list is hard, mostly in terms of making sure our awesome users feel listened to, and also having an issues list which isn't mostly noise.
