### ISSUE TITLE
API Request: Allow /repos to fetch a specific, arbitrary group of slugs

### ISSUE THREAD

**Issue by mjm** [travis-ci/travis-ci#1610]
For CI monitoring applications, it would be nice to be able to take any number of arbitrary repositories and fetch their status all at once. For instance, similar to how `/repos?slug=rails/rails` gives the details for that one repo, `/repos?slugs[]=rails/rails&slugs[]=travis-ci/travis-ci` could give the details for multiple repos.

**Comment by joshk** [comment]
Closing this as the issue has gone stale.

Thank you for creating this.
