### ISSUE TITLE
Add ENV var for branch name where PR came from

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#1633]
A customer asked for us to export the branch name where the PR came from as they use it in their tests to clone another repo which uses the same branch name structure.

eg. `TRAVIS_PULL_REQUEST_SOURCE_BRANCH_NAME` (name is a little long) :)

**Comment by tony-spataro-rs** [comment]
For workflows that produce an integration-test artifact when building a pull request, this feature would be super useful to help me choose a reasonable name for the test artifact. Please consider adding this, as the effort seems to small and the benefit large.

**Comment by bpinto** [comment]
I have started testing travis for our organisation builds but I am missing this. Not sure if there is an workaround? But we need this in order to create docker images per PR in order to automatically create staging environments.

**Comment by brianguertin** [comment]
@bpinto My workaround for now is:
```
git fetch --tags
git fetch --unshallow
BRANCH=`git rev-parse --abbrev-ref HEAD`
```

**Comment by bpinto** [comment]
Thanks @brianguertin

**Comment by bpinto** [comment]
I couldn't get it to work @brianguertin 

The output of `git rev-parse --abbrev-ref HEAD` was HEAD. =/

**Comment by brianguertin** [comment]
@bpinto I don't know what to say, it works flawlessly for me both locally and on Travis CI.

**Comment by derekstavis** [comment]
So here we go. I have wrote a bash script workaround based on GitHub API.

You can check it here:  https://gist.github.com/derekstavis/0526ac13cfecb5d6ffe5

**Comment by fotinakis** [comment]
Hey Travis CI devs—this tiny feature would really help, can anyone take this on or give direction?

For [Percy.io](https://percy.io) CI integration, we rely on knowing the PR's origin branch name so we can do a visual comparison of the branch vs. master—we simply can't integrate fully with Travis CI without this environment variable.

**Comment by breerly** [comment]
I've written a blog post with a workaround for this issue - https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/

Also created a issue shown above, #5731

**Comment by fotinakis** [comment]
@joshk @BanzaiMan @henrikhodne Hey Travis CI friends, any chance we can get some insider info of if this is on the roadmap?

**Comment by bestdan** [comment]
+1

**Comment by breerly** [comment]
+1

**Comment by wipatrick** [comment]
+1

**Comment by BanzaiMan** [comment]
We will update this issue when we have something to share. In the meantime, please use the "Subscribe" feature to keep abreast of this.

Thank you.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/848 resolves this issue. The name for this environment variable is currently `TRAVIS_PULL_REQUEST_BRANCH`. (The PR also adds `TRAVIS_PULL_REQUEST_SHA`, which points to the HEAD of the PR branch.)

**Comment by BanzaiMan** [comment]
This has been deployed. The documentation will be updated shortly. https://github.com/travis-ci/docs-travis-ci-com/pull/742
