### ISSUE TITLE
Add support for syscall clone()

### ISSUE THREAD

**Issue by ronalchn** [travis-ci/travis-ci#1666]
I am trying to run a sandbox which calls clone() on this line (https://github.com/bblackham/moe-cms/blob/master/isolate/isolate.c#L1328), but it results in "Operation not permitted" as shown here (https://travis-ci.org/NZOI/nztrain/jobs/14407597#L469).

Is this system call (http://linux.die.net/man/2/clone) not implemented?

**Comment by alban** [comment]
Is CAP_SYS_ADMIN also restricted on the [standard virtualized environment](http://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), or only on the container-based one?

I also get the error:
```
clone(child_stack=0, flags=CLONE_NEWNS|0x2c000000|SIGCHLD) = -1 EPERM (Operation not permitted)
```
and I wonder if I mistakenly use the wrong kind of virtualized environment.
