### ISSUE TITLE
flyway/flyway was working up to 12 days ago, broken now. No changes.

### ISSUE THREAD

**Issue by axelfontaine** [travis-ci/travis-ci#1689]
Something changed in the travis environment in the past 12 days, that causes all flyway/flyway builds to fail on the flyway-maven-largetest module.

It fails when trying to invoke a freshly downloaded copy of maven 2.2.1 as part of a test. This worked great until 12 days ago. This code has not been changed and now it breaks, both on the main repo and all the forks.

I've added a bit of tracer code, but so far I haven't been able to find the cause.

Any help appreciated.

Cheers
Axel

**Comment by lschuetze** [comment]
@gildegoma Did you managed to make a PR against travis-cookbooks? The workaround is not useful if you want to run the build in a containerized environment because there is no sudo available.

**Comment by gildegoma** [comment]
@lschuetze Thanks to ping back this problem, which is indeed totally annoying for the container-based environment.

I created https://github.com/travis-ci/travis-cookbooks/pull/475 to refund this overdue :hourglass_flowing_sand:.

**Comment by strubell** [comment]
@gildegoma is this fix in the current running Travis? I am still unable to set MAVEN_OPTS without using the `sudo rm /etc/mavenrc` workaround, and thus with the new containerized environment.

**Comment by BanzaiMan** [comment]
@strubell Sorry, that has not been deployed yet. Please open a separate ticket, so that we can affect the change on the fly right now. Thanks.

**Comment by strubell** [comment]
@BanzaiMan thanks, see issue #4613
