### ISSUE TITLE
Travis sending multiple build status notification emails

### ISSUE THREAD

**Issue by sferik** [travis-ci/travis-ci#1696]
You can read the incident report here: https://github.com/lostisland/faraday/commit/09202e298ab8a3f3a5d03a378dc600b431fd6993#commitcomment-4732907

I can confirm I started experiencing this issue this morning.

**Comment by mislav** [comment]
I'm getting 7 emails per build lately. Same symptoms: each email reports different completion times. It's the faraday repo where fast finishing is enabled.

**Comment by parkr** [comment]
@jaybe-jekyll Notified me of multiple reporting in `#jekyll` on IRC. We have disabled IRC notifications until this is resolved. Anything I can do to help? If someone can point me to the notification code, I'd be happy to take a look. Thanks!

**Comment by nazar-pc** [comment]
Still happens, seems to be caused by `allowed_failures` option, probably when combined with `fast_finish`. Sends exactly as many emails as there are allowed builds (changed 2 to 4 recently and started getting 4 emails).

**Comment by MaxLap** [comment]
I also have the issue on my repository: https://travis-ci.org/MaxLap/activerecord_where_assoc

The number of build notifications I get when fail / still failing / fixed is: 1 + the number of builds that are allowed to fail.

This only happens when fast_finish is activated. Disabling it makes it send only one email.

I tested by adding a build allowed to fail, and that incremented from 3 to 4 notifications.

**Comment by tlyu** [comment]
I am also seeing this when both `allow_failures` and `fast_finish` are turned on. I have two required builds and four allowed to fail. I get one notification when the first required build finishes successfully, another when the second required build finishes successfully, then a third when the last failure-allowed job finishes with an error.

https://travis-ci.org/tlyu/tor/builds/347045248

resulting IRC notifications (times are in UTC):
```
23:46 <travis-ci> tlyu/tor travis-partials f0a3dee - Taylor Yu: allow partial 
                  failures for rust in travis
23:46 <travis-ci> Build #799 passed. Details: 
                  https://travis-ci.org/tlyu/tor/builds/347045248
23:49 <travis-ci> tlyu/tor travis-partials f0a3dee - Taylor Yu: allow partial 
                  failures for rust in travis
23:49 <travis-ci> Build #799 passed. Details: 
                  https://travis-ci.org/tlyu/tor/builds/347045248
23:51 <travis-ci> tlyu/tor travis-partials f0a3dee - Taylor Yu: allow partial 
                  failures for rust in travis
23:51 <travis-ci> Build #799 passed. Details: 
                  https://travis-ci.org/tlyu/tor/builds/347045248
```

Also the branches and build history summary icons show success as soon as the first required build finishes successfully.  Would you like me to open a separate issue about that, or should they be considered to be symptoms of the same underlying issue?

**Comment by deivid-rodriguez** [comment]
I'm having a similar issue in https://github.com/activeadmin/activeadmin. I get about 4 duplicate notifications for my own branches...

**Comment by PowerKiKi** [comment]
For a similar but recent issue, see also https://travis-ci.community/t/issue-receiving-duplicated-status-email-notifications/4267

**Comment by yaalaa** [comment]
It's still happening wild to me. `fast_finish` & `allow_failures` are useful but I don't like getting 7 notifications with the same content.

**Comment by aantron** [comment]
Can also confirm. I am also using `fast_finish` and `allow_failures`. This really ought to be reopened and fixed.

The behavior I would like is:

- One email on success/failure of the main rows (already have this).
- Only if the main rows succeeded, one email from each allow_failures row whose status changed since the last build.

**Comment by aantron** [comment]
Here's a Travis forum post about this: https://travis-ci.community/t/receiving-too-many-emails/4888

**Comment by jasonvarga** [comment]
Could this be reopened?

**Comment by aantron** [comment]
@jasonvarga I think Travis uses the forum for bug tracking now. Either way, there hasn't been visible progress, and this remains an issue.
