### ISSUE TITLE
PHP 5.4.22 has xdebug on by default

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#1697]
It seems PHP 5.4.22 has xdebug on by default, as reported by a .com customer.

`/home/travis/.phpenv/versions/5.4.22/etc/conf.d/xdebug.ini`  contains

```
;zend_extension="/home/travis/.phpenv/versions/5.4.22/lib/php/extensions/no-debug-zts-20100525/xdebug.so"
;html_errors=on
```

This is causing a segfault in his tests. Turning it off fixes the segfault.

@loicfrering, any ideas?

**Comment by thedavidmeister** [comment]
`phpenv config-rm xdebug.ini` works for me, saved ~40% on our build times!
