### ISSUE TITLE
Travis provided libzmq3 does not have C++ bindings

### ISSUE THREAD

**Issue by cmouse** [travis-ci/travis-ci#1715]
Can you please add C++ bindings for libzmq3-dev? Also, installing libzmq-dev installs both libzmq-dev and libzmq3-dev, which causes conflict and fails to install.

**Comment by rgbkrk** [comment]
We have a bunch of packages that rely on libzmq3-dev, it would be quite wonderful if this was preinstalled so we could use it for container based builds.

**Comment by Joeasaurus** [comment]
If removing the repository is the workaround, could someone please point me to the docs that explain : how to remove repositories when using the docker-based instances? sudo access is not available there.

**Comment by pjanuario** [comment]
I am finding a similar problem, my builds aren't working anymore. Any help would be good.
https://github.com/travis-ci/travis-ci/issues/5242
