### ISSUE TITLE
TRAVIS_COMMIT_RANGE empty

### ISSUE THREAD

**Issue by nijel** [travis-ci/travis-ci#1719]
I wanted to use TRAVIS_COMMIT_RANGE for some checks on commits in pull requests, but this variable is empty in our builds.

You can see example here (I've added env command to print all environment there):

https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/14913442

**Comment by sjackman** [comment]
:+1:

**Comment by lord2800** [comment]
Would also love to see this working.

**Comment by jcorbin** [comment]
Any word on when / if this will ever be fixed?
