### ISSUE TITLE
Invalid locale on OS X Build Environment

### ISSUE THREAD

**Issue by rivera-ernesto** [travis-ci/travis-ci#1735]
The current OS X locale:

```
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Whether other Travis [environments](http://about.travis-ci.org/docs/user/ci-environment/):

> Environment variables #
> 
> CI=true
> TRAVIS=true
> DEBIAN_FRONTEND=noninteractive
> HAS_JOSH_K_SEAL_OF_APPROVAL=true
> USER=travis (do not depend on this value)
> HOME=/home/travis (do not depend on this value)
> LANG=en_US.UTF-8
> LC_ALL=en_US.UTF-8
> RAILS_ENV=test
> RACK_ENV=test
> MERB_ENV=test
> JRUBY_OPTS="--server -Dcext.enabled=false -Xcompile.invokedynamic=false"

This [breaks](https://github.com/CocoaPods/CocoaPods/issues/1538#issuecomment-30108784) some tools resulting in failing Travis [builds](https://travis-ci.org/rivera-ernesto/CocoaLumberjack/builds/15261437).

Would it be possible to configure the OS X environments with en_US.UTF-8 as well?

For now a `export LANG=en_US.UTF-8` step in `before_install` fixes it.

**Comment by revolt666** [comment]
I still get this warning

**Comment by rivera-ernesto** [comment]
I went back to the fix described in the issue description long time ago. I think it's just safe to keep it.

**Comment by cguzmanceti** [comment]
I have this issue, but i see that my `LC_CTYPE` env variable it was set to *utf-8* (it should be noted that it is written in lowercase). Change it to uppercase and my problem disappears!

**Comment by Dudi00** [comment]
So I've just install OS X Server and I'm still getting this warrning, even if my locale looks like fine

`LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=`

`CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m`

**Comment by AnneTheAgile** [comment]
I am getting the warning as well, cocoapods 1.1.1 , osx 10.12.1 $ echo $LANG # result= en_US.UTF-8.
@henrikhodne do we need to open a new ticket? I saw that a Travis ticket closed its ticket in favor of this; https://github.com/travis-ci/travis-ci/issues/2193

**Comment by DG12** [comment]
I have this problem although it doesn't abort

echo $LANG
en_US.UTF-8

pod --version
WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:
export LANG=en_US.UTF-8
1.5.3

echo $?
0
set
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.iwunqGM5UA/Render
BASH=/bin/bash
BASH_ARGC=()
BASH_ARGV=()
BASH_LINENO=()
BASH_REMATCH=([0]="n")
BASH_SOURCE=()
BASH_VERSINFO=([0]="3" [1]="2" [2]="57" [3]="1" [4]="release" [5]="x86_64-apple-darwin18")
BASH_VERSION='3.2.57(1)-release'
BLOCKSIZE=1k
COLUMNS=140
DIRSTACK=()
DISPLAY=/private/tmp/com.apple.launchd.IolQiyOf6v/org.macosforge.xquartz:0
EUID=501
EXINIT='set showmode ignorecase ruler tabstop=4 mesg verbose exrc'
GREP_COLOR=34
GREP_OPTIONS='--color -d skip'
GROUPS=()
HISTFILE=/Volumes/DATA/dgerman/.bash_history
HISTFILESIZE=1000
HISTIGNORE=ls:lt:w:df:du:vil:taill
HISTORYymd_hms=.bash_hist.190105_120826
HISTSIZE=1000
HISTTIMEFORMAT='%F %T '
HOME=/Volumes/DATA/dgerman
HOSTNAME=smacpro
HOSTTYPE=x86_64
IFS=$' \t\n'
LANG=en_US.UTF-8
LC_ALL=C
LESS='-X --LONG-PROMPT -P file:%f\ %Pb%\ \ \ \ \ \ \ \ help,forward,back,quit, / (search)'
LINES=36
LOGNAME=dgerman
MACHTYPE=x86_64-apple-darwin18
MAILCHECK=60
OPTERR=1
OPTIND=1
OSTYPE=darwin18
PAGER=less
PATH=/opt/local/bin:/opt/local/sbin:/Volumes/DATA/dgerman/.bin:/Library/Developer/CommandLineTools/usr/bin:/usr/local/bin:/usr/bin:/bin:/   +usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/opt/X11/bin:/usr/libexec:/Volumes/DATA/dgerman/.gem/ruby/2.3.0/bin
PIPESTATUS=([0]="0")
PPID=60623
PROMPT_COMMAND=update_terminal_cwd
PS1='$(split_pwd) > '
PS2=' + '
PS4='+ '
PWD=/Volumes/DATA/dgerman
RWS=Real-World-Systems.com
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:histexpand:history:interactive-comments:monitor:vi
SHELL_SESSION_DID_HISTORY_CHECK=1
SHELL_SESSION_DID_INIT=1
SHELL_SESSION_DIR=/Volumes/DATA/dgerman/.bash_sessions
SHELL_SESSION_FILE=/Volumes/DATA/dgerman/.bash_sessions/2828D7BA-88DF-4DE4-96DA-5F6F142F0CCA.session
SHELL_SESSION_HISTFILE=/Volumes/DATA/dgerman/.bash_sessions/2828D7BA-88DF-4DE4-96DA-5F6F142F0CCA.history
SHELL_SESSION_HISTFILE_NEW=/Volumes/DATA/dgerman/.bash_sessions/2828D7BA-88DF-4DE4-96DA-5F6F142F0CCA.historynew
SHELL_SESSION_HISTFILE_SHARED=/Volumes/DATA/dgerman/.bash_history
SHELL_SESSION_TIMESTAMP_FILE=/Volumes/DATA/dgerman/.bash_sessions/_expiration_check_timestamp
SHLVL=1
SSH_AGENT_PID=60641
SSH_AUTH_SOCK=/var/folders/rr/jvwb6c9j2h18lzc28kzws_940000gn/T//ssh-rqDngB6oklap/agent.60640
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=421.1
TERM_SESSION_ID=2828D7BA-88DF-4DE4-96DA-5F6F142F0CCA
TIMEFORMAT=' %1R wall time; %U user; %S sys; %P%% '
TMPDIR=/var/folders/rr/jvwb6c9j2h18lzc28kzws_940000gn/T/
UID=501
USER=dgerman
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0

uname -ap
Darwin smacpro 18.2.0 Darwin Kernel Version 18.2.0: Fri Dec 14 18:43:36 PST 2018;
root:xnu-4903.240.10~4/RELEASE_X86_64 x86_64 i386

Mac OS Mojave 10.14.3 Beta(18D32a)

csrutil status
System Integrity Protection status: disabled.

cat newprocess

echo $LANG: $LANG
echo $$:$$

./newprocess
$LANG: en_US.UTF-8
$$:68400
