### ISSUE TITLE
Being able to set custom GOPATHs more easily

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#1741]
**_Note**_: In this issue, when I say `$GOPATH` I mean a single-path `$GOPATH` unless otherwise noted (I'm aware that you can have multiple paths, like `$PATH`, but I'll ignore that for now).

Though I don't think it's the most common way to do it, it's perfectly valid for the package path for a Go project to be different than `github.com/owner_name/name`, and it is also valid for the root of the package not to be the "root" of the package. For example, the GitHub repository could have this structure:

```
.
|-- src
|   `-- travis-ci.org
|       `-- goapi
|           |-- client.go
|           `-- repository.go
`-- .travis.yml
```

This would mean that we could do something like `export GOPATH=$TRAVIS_BUILD_DIR`.

It could also look like this:

```
.
|-- travis-ci.org
|   `-- goapi
|       |-- client.go
|       `-- repository.go
`-- .travis.yml
```

In this case, we would need to put the repository in `$GOPATH/src`.

I think common for all these repositories is that they should be checked out in the `GOPATH` or some subdir of it, so maybe we could have something like this in .travis.yml:

``` YAML
go:
  install_to: $GOPATH/src
```

We may not need first-class .travis.yml support for this, but we should definitely document how to override where in the GOPATH the repository is installed somehow. Right now we don't even document that we do move the repository into the `GOPATH` like this.

**Comment by BanzaiMan** [comment]
Closing, as it's become stale.
