### ISSUE TITLE
Figure out FPM solution for HHVM

### ISSUE THREAD

**Issue by ptarjan** [travis-ci/travis-ci#1747]
The docs describe how to use the fpm version of php. HHVM also has fastcgi support https://github.com/facebook/hhvm/wiki/FastCGI so with some shim scripts we can probably make them feel the same.

For example: https://github.com/ptarjan/phpbb/blob/master/travis/setup-webserver.sh

**Comment by BanzaiMan** [comment]
Closing this as it's become stale.
