### ISSUE TITLE
Support for ALSA's snd-dummy driver?

### ISSUE THREAD

**Issue by drewish** [travis-ci/travis-ci#1754]
I'm trying to have Travis run tests for a [node extension](https://github.com/drewish/node-midi) that uses the ALSA sequencer. I'd hoped that this would do the trick:

```
language: node_js
node_js:
  - "0.10"
before_install:
 - sudo apt-get install libasound2-dev alsa-utils alsa-oss
```

But that dies during the module's initialization:

```
> node test/virtual-loopback-test-automated.js
ALSA lib seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
RtMidiOut::initialize: error creating ALSA sequencer client object.
terminate called after throwing an instance of 'RtError'
  what():  RtMidiOut::initialize: error creating ALSA sequencer client object.
Aborted
```

I discovered that ALSA has a [dummy driver](http://www.alsa-project.org/main/index.php/Matrix:Module-dummy) and I'd hoped I'd be able to load that module:

```
before_install:
 - sudo apt-get install libasound2-dev alsa-utils alsa-oss
 - sudo modprobe snd-dummy
```

But `modprobe` doesn't seem to be allowed in the virtualization environment:

```
$ sudo modprobe snd-dummy
FATAL: Could not load /lib/modules/2.6.32-042stab079.5/modules.dep: No such file or directory
The command "sudo modprobe snd-dummy" failed and exited with 1 during before_install.
Your build has been stopped.
```

Any suggestions? Any chance that module be enabled by default?

**Comment by MartinDelille** [comment]
@joshk Is there any evolution about this issue in future travis architecture?

**Comment by k3it** [comment]
seems to be getting closer to getting the dummy driver loaded see https://travis-ci.org/k3it/qsorder/builds/112413931
(see lsmod output)
May be this is working now on the new platform travis is using?
still getting an error from alsa though.  
yml file for the above build is here:
https://github.com/k3it/qsorder/blob/c16c6f3479ebd3bf34b3b41258f95974dc0ad24f/.travis.yml

**Comment by probonopd** [comment]
Has anyone ever succeeded using a dummy sound device on Travis CI?

**Comment by k3it** [comment]
yes, it works fine for me
https://travis-ci.org/k3it/qsorder/builds/387564727
https://github.com/k3it/qsorder/blob/master/.travis.yml
