### ISSUE TITLE
Support for compiling and running 32bit code

### ISSUE THREAD

**Issue by jacob-carlborg** [travis-ci/travis-ci#1760]
It would be nice if the virtual machines came with support for compiling and running 32bit code. I guess this means the following packages need to be installed by default:

* gcc-multilib
* ia32-libs

See also: https://github.com/travis-ci/travis-ci/issues/730#issuecomment-30753087

**Comment by andyli** [comment]
ia32-libs can be installed if you install libgd2-xpm at the same time. See [here](https://bugs.launchpad.net/ubuntu/+source/graphviz/+bug/1100900).
i.e. This works for me: `sudo apt-get install libgd2-xpm ia32-libs ia32-libs-multiarch -qq`

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
