### ISSUE TITLE
HHVM PHP needs PEAR and Pyrus

### ISSUE THREAD

**Issue by philsturgeon** [travis-ci/travis-ci#1763]
Further to the issues in #1749, the HHVM PHP builds also need pear and pyrus utilities installed. 

Pyrus fails: https://travis-ci.org/thephpleague/fractal/jobs/15611581

PEAR fails: https://travis-ci.org/thephpleague/fractal/jobs/15612179

Trying to compile PHP Code Sniffer manually instead of installing via PEAR or Pyrus threw all sorts of other errors:  https://travis-ci.org/thephpleague/fractal/jobs/15612757 Including some of the issues in #1749 and potentially more.

**Comment by BanzaiMan** [comment]
Closing as it's become stale.
