### ISSUE TITLE
Python language builds don't work on OS X

### ISSUE THREAD

**Issue by alex** [travis-ci/travis-ci#1765]
Here's an example of what happens:

``` console
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.4
$ source ~/virtualenv/python2.7/bin/activate
/Users/travis/build.sh: line 133: /Users/travis/virtualenv/python2.7/bin/activate: No such file or directory

The command "source ~/virtualenv/python2.7/bin/activate" failed and exited with 1 during setup.

Your build has been stopped.
```

(Example job: https://travis-ci.org/pyca/cryptography/jobs/15715157)

This appears to be because the empty virtualenv that's usually there on Linux doesn't exist.

**Comment by ulope** [comment]
How is this closed? 
Just because you can hack it with a mile long matrix.include incantation doesn't mean that this issue is fixed in any way.
