### ISSUE TITLE
Unable to sign in to Travis-CI.org via GitHub

### ISSUE THREAD

**Issue by mislav** [travis-ci/travis-ci#1766]
In both latest Safari and Chrome (stable) on Mac, I can't sign in to Travis for the past several days at least. "Sign in with GitHub" takes me through the regular OAuth flow but  after that, the UI continues to display everything as if I'm not signed in as before.

I've used a HTTP proxy to sniff on the related traffic and it all looks good up to and including this point:

```
POST /github/hub HTTP/1.1
Host: travis-ci.org

(REDACTED FORM DATA)

HTTP/1.1 200 OK
Content-Length: 515
Connection: keep-alive

<script>
var storage = localStorage;
storage.setItem('travis.token', "REDACTED");
storage.setItem('travis.user',  "{\"id\":1264,\"name\":\"Mislav Marohni\\u0107\",\"login\":\"mislav\",\"email\":\"mislav.marohnic@gmail.com\",\"gravatar_id\":\"8f93a872e399bc1353cc8d4e791d5401\",\"locale\":null,\"is_syncing\":false,\"synced_at\":\"2013-12-18T19:46:07Z\",\"correct_scopes\":false,\"created_at\":\"2011-07-28T01:56:27Z\",\"token\":\"REDACTED\"}");
window.location = "/github/hub";
</script>
```

I do get redirected to `/github/hub` (where I started at) after all is done, and based on that I'm guessing that this code does get executed in my browser, but I'm not signed in. I inspected `localStorage` in the browser and it contains neither keys for `travis.token` nor `travis.user`.

**Comment by benlindsay** [comment]
This looks old and supposedly fixed, but I'm running into this exact problem years later. I can't access any of my Travis stuff because it never recognizes me signing in and goes straight back to the authorization page after ostensibly signing in. Anything I can do to get around this?

**Comment by itsaphel** [comment]
@benlindsay experiencing the same issue. Was working 30 mins ago, granted access for an organisation, and now it is broken. No other changes made in that period to Travis' access, on Travis' website, or on GitHub. Only granting access for another organisation. This was done in the GitHub settings, as redirected by travis-ci.com

I *cannot* log into travis-ci.com. I *can* log into travis-ci.org. The access grant was for *travis-ci.com*.

**Comment by shardy613** [comment]
For those showing up in 2018: https://www.traviscistatus.com/

They are aware, and working on it.
