### ISSUE TITLE
Compile OpenSSL to be FIPS compatible?

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#1777]
A customer asks: "you are using OpenSSL 1.0.1; any chance you would be willing to compile it to be FIPS compatible? It will default to false so no one will be impacted unless they explicitly set OpenSSL.fips_mode = true"

**Comment by junaruga** [comment]
@BanzaiMan 

I am trying to install OpenSSL with FIPS mode to `ruby` repository with Travis CI following above steps.
But I got an error "FIPS mode not supported" when building OpenSSL.
Do you know what's wrong?

https://travis-ci.org/junaruga/ruby/jobs/451543911

```
./Configure \
    --prefix=$OPENSSL_DIR \
    fips \
    --with-fipsdir=$OPENSSL_FIPS_DIR \
    linux-x86_64
 ...
FIPS mode not supported
```

The modification is this.
https://github.com/junaruga/ruby/commit/60983868a0c002b67bfced427714b454531fa504

> You could probably cache OpenSSL with FIPS for your own use

My cache setting in `.travis.yml` looks okay?
Thanks!

**Comment by junaruga** [comment]
Sorry OpenSSL 1.1.1 might change or stop the workflow to build with fips mode.
https://github.com/openssl/openssl/commit/b53338cbf8822dd774f9e4057307f347d2b63ff0

**Comment by junaruga** [comment]
> Sorry OpenSSL 1.1.1 might change or stop the workflow to build with fips mode.
> openssl/openssl@b53338c

Reported now.
https://github.com/openssl/openssl/issues/7582

**Comment by junaruga** [comment]
I just show the success build case with OpenSSL 1.0.2p, as a reference.
https://github.com/ruby/ruby/pull/2007
