### ISSUE TITLE
Make the status of a repository dependent on the last created build, not the last finished

### ISSUE THREAD

**Issue by Aaron1011** [travis-ci/travis-ci#1781]
Currently, whatever build has finished last is used to determine the status of a repository. If someone submits a failing pull request, or an earlier build is restarted, the repository can be marked as failed, even though the most recent build is actually passing.

**Comment by JamesMGreene** [comment]
:+1:

I ran into this today with [JamesMGreene/qunit-assert-step](https://travis-ci.org/JamesMGreene/qunit-assert-step/). [Build #4](https://travis-ci.org/JamesMGreene/qunit-assert-step/builds/46735425) passed but [Build #3](https://travis-ci.org/JamesMGreene/qunit-assert-step/builds/46735338) (both on the `master` branch) finished after it with an error, so the `master` branch's status badge was "error".

I ended up rerunning [Build #4](https://travis-ci.org/JamesMGreene/qunit-assert-step/builds/46735425) to fix the badge.

**Comment by sampablokuper** [comment]
@BanzaiMan I believe you are correct in thinking this issue is a duplicate of #483 (and it should be closed as such).
