### ISSUE TITLE
Successful build shows "build failing" image

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#1786]
Example here: https://travis-ci.org/andig/volkszaehler.org/builds/16000347
Latest build was successfully run on non-master branch (master branch doesn't build as it doesn't have a travis.yml).
It's not a client-side caching issue as same wrong "build failing" image appears on different browser after signing in with github.

**Comment by kounkou** [comment]
Hi everyone, I am taking the opportunity to ask here if you could help me solve the same issue on my project please : https://travis-ci.org/kounkou/loba
My build is pass, but the travis icon is undefined.

Jacques
