### ISSUE TITLE
Make "on" option available for all addons?

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#1788]
From a pro customer:

> Would be nice if you could skip the saucelabs addon for steps that don't need it when you create parallel jobs.

**Comment by andyli** [comment]
It is quite an important feature.
Currently when multiple parallel builds start at the same time, all of them will connect to SauceLabs, reaching the max active tunnels limit:
```
Starting Sauce Connect
Waiting for Sauce Connect readyfile
04 Mar 05:33:32 - Sauce Connect 4.3.6, build 1628 8a5c837
04 Mar 05:33:32 - Using CA certificate bundle /etc/ssl/certs/ca-certificates.crt.
04 Mar 05:33:32 - Starting up; pid 7131
04 Mar 05:33:32 - Command line arguments: sc-4.3.6-linux//bin/sc -i 2771.4 -f sauce-connect-ready-24287 -l /home/travis/sauce-connect.log
04 Mar 05:33:32 - Using no proxy for connecting to Sauce Labs REST API.
04 Mar 05:33:32 - Resolving saucelabs.com to 162.222.73.28 took 6 ms.
04 Mar 05:33:32 - Started scproxy on port 48241.
04 Mar 05:33:32 - Please wait for 'you may start your tests' to start your tests.
04 Mar 05:33:32 - Starting secure remote tunnel VM...
04 Mar 05:33:35 - POST https://saucelabs.com/rest/v1/haxe/tunnels: HTTP response code indicated failure.
04 Mar 05:33:35 - Response: {"error": "Too many active tunnels: 5; allowed: 5"}.
04 Mar 05:33:35 - Error creating tunnel.
04 Mar 05:33:35 - Sauce Connect could not establish a connection.
04 Mar 05:33:35 - Please check your firewall and proxy settings.
04 Mar 05:33:35 - You can also use sc --doctor to launch Sauce Connect in diagnostic mode.
04 Mar 05:33:35 - Cleaning up.
04 Mar 05:33:35 - Goodbye.
```

**Comment by hugomarcotte** [comment]
Same problem here where only one worker actually need to connect to sauce lab but since the sauce_connect addon is true all are connecting. Anybody found a solution around that problem?

**Comment by RomanGotsiy** [comment]
+1
Same problem here

**Comment by RomanGotsiy** [comment]
> How would that look like in the .travis.yml?
@roidrage the following syntax would be fine:

```yml
matrix:
  include:
    - env: JOB=unit
    - env: JOB=e2e
      addons:
        sauce_connect: true
```

**Comment by hugomarcotte** [comment]
@RomanGotsiy we found a work-around by writing a script that start sauce connect manually, run our tests and then stop sauce connect manually. The script runs based on an ENV variable defined on the worker. 

This https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/sauce_connect/templates/sauce_connect.sh is what we used to start/stop sauce connect.

Hope this helps

**Comment by RomanGotsiy** [comment]
@hugomarcotte thank you. I was thinking about this solution. Actually this problem is not so critical for me so I can wait for the feature.
Anyway, it would be great to have this feature without workarounds.

**Comment by tarajane** [comment]
+1

**Comment by BanzaiMan** [comment]
There is a bit of a problem here. Adding the `if` condition to the addons is not hard. However, the conditions that are most useful can be hard to work with.

The checks that relies on environment variables (i.e., practically all) are dependent on these values being set, but some addons (for example, MariaDB) gets executed _before_ they are defined:

1. addon runs
1. `sudo` optionally disabled
1. environment variables defined with `export` statements

Deployment runs after everything else, and therefore is not subject to this concern.

Some addons can be probably moved so they run *after* the `export`s, but not all.

**Comment by BanzaiMan** [comment]
We may be able to export *some* environment variables (built-in ones) early, so that some addons may be able to use them.
