### ISSUE TITLE
virtual machine copy of travis box

### ISSUE THREAD

**Issue by mcr** [travis-ci/travis-ci#1801]
It would be helpful if I could boot up exactly the virtual machine that my tests will
run on in order to diagnose system depend (in particular, debian/ubuntu version specific library issues) faults.
A reference image on EC2 (or some other public openstack) would be ideal.

**Comment by mcr** [comment]
Hi, so with Trusty now available, and docker, is there any FAQ on how to get the same environment as Travis, so that I can debug the problems that only show up in Travis?

**Comment by BanzaiMan** [comment]
@mcr Did you look at the documentation site? If so, how can we improve it so you could have found it? https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally
