### ISSUE TITLE
Add support for Neo4j 2.0.0

### ISSUE THREAD

**Issue by bruth** [travis-ci/travis-ci#1803]
Version 2.0.0 [was released](http://blog.neo4j.org/2013/12/neo4j-20-ga-graphs-for-everyone.html) December 11th.

(Re-opened from https://github.com/travis-ci/travis-cookbooks/issues/255)

**Comment by aseemk** [comment]
+1 for being able to specify Neo4j version. =)

If it helps others, here's how I test across multiple versions of Neo4j for the Node.js driver:

https://github.com/thingdom/node-neo4j/blob/master/.travis.yml

/ht @wfreeman

**Comment by haio** [comment]
@aseemk Great help

**Comment by aseemk** [comment]
I've found myself copy-pasting the code to install Neo4j manually across multiple apps now. So just chiming in that it'd still be great to see native support for Neo4j versions in Travis. =) Thanks guys!

**Comment by RedCraig** [comment]
@aseemk - Thanks for the neo4j install snippet!
Since neo4j 2.2 or so I've had to create a default user and set it's password (there may be a way around having to do this for testing?) before running tests against the neo4j fresh install:
```bash
#!/usr/bin/env bash
# create the user
curl -X GET http://localhost:7474/user/neo4j --user neo4j:neo4j -H Accept:application/json -H Content-Type:application/json
# set it's password to 'pass'
curl -X POST http://localhost:7474/user/neo4j/password --user neo4j:neo4j -H Accept:application/json -H Content-Type:application/json -d "{\"password\": \"pass\"}"
```

To not bother escaping the curl commands I put then in a separate shell script (which has the executable flag), and call the script from `.travis.yml`
before_script:
```yaml
before_script:
- <steps to install Neo4j locally>
- ./configure_neo4j_default_user.sh
```

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/packer-templates/issues/410 addresses this for Trusty. (It is not likely to happen for Precise at this time.)

**Comment by BanzaiMan** [comment]
You can get Neo4j 3.2.0 with https://github.com/travis-ci/travis-ci/issues/7801#issuecomment-303496945.

The next build image update on Trusty should have 3.x.

As I mentioned before, updates are unlikely for Precise.
