### ISSUE TITLE
Allow per-job status images

### ISSUE THREAD

**Issue by Aaron1011** [travis-ci/travis-ci#1809]
Job status images would be available for each job in a build matrix. The images could be similar to the current ones for builds, but would say 'job' instead of 'build'. Similar to the way 'branch=master' can be used with the status image URLs to select a particular branch, something like 'job=name' could be used to select a job.

In order to keep track of the "same" job across builds, a name could be given to a job with a specific configuration. This could be done through the web interface, on in the `.travis.yml`. 

Here's the IRC conversation between me and @HashNuke, for reference:

```
<Aaron1011> HashNuke_: Going back to your earlier idea about per-job status badges
<Aaron1011> I see two challenges in implementing it
<Aaron1011> First, a good way to identify the same job across builds
<HashNuke_> yes, I understand that part is difficult.
<Aaron1011> Second, what to do if the .travis.yml is changed so that a job has a different configuration
<HashNuke_> I would gladly switch from env-based matrix to some other method if the build badges were available for it.
<Aaron1011> HashNuke_: I think the current build/job model is here to stay, at least for a while
<Aaron1011> Would you mind creating an issue describing how you see the feature working?
<Aaron1011> https://github.com/travis-ci/travis-ci/issues/new
<HashNuke_> I dont have a clear solution to that too. If I come across something, I'll file an issue with the suggestion.
<HashNuke_> Aaron1011: Right now I have an idea to overcome the limitation. Use different branch name instead of the env.
<Aaron1011> HashNuke_: Yeah, you could do that. I still think the per-job status images could be a cool feature
<Aaron1011> The other thing I thought of is what the image would actually look like
<Aaron1011> It could be the job number, and the state
<HashNuke_> Aaron1011: no. tha wont be readable for other people not involved in the project. (like the users of the project).
<Aaron1011> Or it could actually include the job config/environment variables. However, it would be expensive to have to do it on-the-fly
<HashNuke_> Aaron1011: So let the travis config mention the name for the env var group.
<Aaron1011> HashNuke_: That's a great idea!
<HashNuke_> Aaron1011: And then use the name in the badge. If the group name is "jruby1.6", then "jruby1.6:passing"
<Aaron1011> The main problem is that currently, Travis just selects from a pre-defined image: build passing, build failing, build errored, or build unknown
<Aaron1011> A new image would have to be generated for every single job
<HashNuke_> Ah... I see the problem.
<Aaron1011> on every single build, on every repo :)
<HashNuke_> Aaron1011: Or just display the build status. Let the user use the group name on his/her readme on his own.
<Aaron1011> HashNuke_: That would probably be better. Otherwise, Travis would have to host several gigabytes of images :)
<HashNuke_> So in my readme, I would just type in "Jruby 1.6" and include the image which would only say "passing" or "failing".
<HashNuke_> That way the current simplicity can be maintained.
<Aaron1011> HashNuke_: That sounds good
<Aaron1011> However, I'm not sure about giving names to jobs
<HashNuke_> (simplicity in reference to having very finite amt of images and serving those instead of generating them for each repo)
<Aaron1011> The build matrix is expanded at Travis to create the list of jobs
<Aaron1011> It might be better to name them in the web interface
<HashNuke_> Aaron1011: anything that works.
```

**Comment by bjfish** [comment]
I've created a small web app to create a badge for matrix builds as described here:
https://github.com/bjfish/travis-matrix-badges

**Comment by gracjan** [comment]
@bjfish: Nice!

**Comment by feliwir** [comment]
I would very appreciate such a feature aswell, since i am having a C++ project that gets compiled with Clang & GCC on Linux and Mac. It would be very useful to retrieve a status image for each produced job, so they can be embedded into the ReadMe.md of my repo (so i can see immediatly which job failed)

**Comment by djMax** [comment]
+1 - open source multiplatform project really would benefit from displaying each platform's status so the right people get visual feedback

**Comment by juju4** [comment]
:+1: 
Typical example would be per-platform/environment build state
example: https://github.com/saucelabs-ansible/pip
done with http://shields.io/ (manually I believe)

**Comment by Yangqing** [comment]
I stumbled upon this and it is something that we also would love to have. For example, our library, https://github.com/caffe2/caffe2 , is an open-source deep learning library that targets Linux, Mac, iOS and Android at the same time (we have Windows too but that is on appveyor right now).

It would be great to show individual build status, instead of having to set up a custom jenkins server to do so.

**Comment by deepfire** [comment]
The Haskell world sees yearly major releases of its flagship compiler -- the GHC.  And, of course, the extremely fine-grained library ecosystem is not uniformly ported to the relevant two-three releases (say, `8.0.2`, 7.10.3` and `7.8.4`).

Having separate results would allow more test coverage, without fear of excess red button all-or-nothing messaging.

**Comment by chivee** [comment]
thanks for  @bjfish ,  that works for me.

**Comment by devnoname120** [comment]
I can confirm that currently it's awkward for multi-platform, because in one of my projects the badge is for Linux, Mac, and other platforms.
Nobody knows which platform is broken.
