### ISSUE TITLE
Display relative position in the build queue

### ISSUE THREAD

**Issue by sferik** [travis-ci/travis-ci#1815]
Earlier versions of the Travis CI web client displayed the entire build queue on the home page. I believe it was removed for performance reasons, which was a good reason to remove it.

That said, this feature was occasionally useful. I have a proposal that I believe will restore the relevant information without significantly degrading client-side performance.

Here is my [user story](http://en.wikipedia.org/wiki/User_story):

> As a software developer debugging an issue (specifically, an issue that is difficult or impossible to reproduce outside the Travis CI environment), I want to know how far down my job is in the queue, so that I can get a :coffee: if I know it’s going to be a while.

I have an idea for how to display that information without dramatically impacting front-end performance:

![screen shot 2014-01-02 at 6 08 48 pm](https://f.cloud.github.com/assets/10308/1834052/6db654ea-73d5-11e3-8187-5f9cc5507ef9.png)

In this proposal, the “behind 5 builds” text would update every time the build changes its position in the queue, until the build state changes to “Started”, at which point it can cease polling for updates.

Unlike the global queue on the homepage, this indication of queue position is context-dependent and [hidden until useful](http://goeunchoi.com/2013/hidden-until-useful/).

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
