### ISSUE TITLE
Feature Request: Pre-install Nomad-cli on OS X Build Machines

### ISSUE THREAD

**Issue by hpogosyan** [travis-ci/travis-ci#1817]
Nomad
================================
*Source: http://nomad-cli.com*

After a short discussion with @joshk in the Campfire chatroom. He suggested that I request this feature for the OS X (OBJ-C) build machines. 

Seems like the most useful tool would be:
* Cupertino

          ios profiles:download:all --type distribution -u$USERNAME -p$PASSWORD

*Which would download your Distribution Profile*

Then you can embed that distribution profile in your xcrun script ensuring that you have your **LATEST** Provisioning Profile within your distribution.

**Comment by henrikhodne** [comment]
It looks like nomad got removed from our latest Xcode 6.1.1 image. Sorry about that, it'll be back again in the next update.

**Comment by AndrewDryga** [comment]
Also I think there are no nomad-cli on xcode6.4 image

**Comment by henrikhodne** [comment]
nomad-cli is part of our list of gems that get preinstalled, so it should be included in any new image. It's also included in our `xcode6.4`, `xcode7.3` and `xcode8` images.
