### ISSUE TITLE
Build errors for failing Deployment Tasks

### ISSUE THREAD

**Issue by tkowark** [travis-ci/travis-ci#1836]
We've included some rake tasks to be executed after our app is deployed to Heroku on successful builds. However, for example in https://travis-ci.org/tkowark/hpi-hiwi-portal/builds/16420927 the "rake db:seed" fails but still the overall build passed.

Is this desired behaviour? If so, is there any way to rollback the deployment if any of the rake tasks fails?

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to pursue this specifically. We do have more immediate plans to revamp our deployment support as a whole though, which will take this into account.

Should we have more updates at some point, we'll make sure to update this ticket.
