### ISSUE TITLE
Timeout when generating code-coverage in phpunit

### ISSUE THREAD

**Issue by splitbrain** [travis-ci/travis-ci#1837]
When I add --coverage-clover=coverage.clover to my phpunit command, the generation of the coverage report fails with the following error:

```
Generating code coverage report in Clover XML format ...PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/travis/.phpenv/versions/5.5.7/share/pyrus/.pear/php/PHP/Token.php on line 432
```

This puzzles me for several reasons:
- generating the report takes only about 3 seconds on my local machine which actually seems to be slower than the test server (judging from the time the test suite needs)
- command line PHP does not have a timeout usually, so this seems to be setup deliberately on Travis-CI?
- it seems noone else is having this kind of problem as I couldn't find any similar reports when googling
- my bootstrap.php file for phpunit explicitly calls `set_time_limit(0);`

Is there a way to fix this on my side?

Full build log at https://travis-ci.org/splitbrain/dokuwiki/jobs/16522833

**Comment by Incognito** [comment]
I have this issue with phpunit 4.3.5 on PHP 5.4.40 when my suite has one 'F' and I try to generate --coverage-xml.

**Comment by michaeltricht** [comment]
@Incognito What do you mean upgrading my error levels?
I'm facing this issue on PHP 5.4.45 and PHPUnit 3.7.28

**Comment by Incognito** [comment]
I regret I was so vague when I posted that...

I believe the error went away when I silenced PHP errors from being E_ALL.
