### ISSUE TITLE
Help: Add "travis" user to "audio" group

### ISSUE THREAD

**Issue by larsoner** [travis-ci/travis-ci#1839]
I need my user to be a member of the "audio" group in order to access the sound server started by jackd2. I have tried adding the user to the audio group, but trying to make it take effect using the normal tricks of `su - $USER` and `newgrp audio` (in `before_install`) each cause the build to halt at the command line.

Is there a way to run Travis-CI giving the user permissions?

The only workaround I can think of is to run our software as superuser, which does not seem ideal.

**Comment by k3it** [comment]
@Eric89GXL your solution worked thank you. Took more builds than I'm willing to admit to get a "dummy" alsa card working :)  I had to re-activate virtual env also https://travis-ci.org/k3it/qsorder/builds/112510608#L283  . I wonder if there is a more elegant way of doing this, especially when testing for different python releases.
