### ISSUE TITLE
{"error":"Travis encountered an error, sorry :("}

### ISSUE THREAD

**Issue by lpabon** [travis-ci/travis-ci#1862]
I tried to sign in using my github account, and once I accepted the permissions for travis-ci.org I received the error:

{"error":"Travis encountered an error, sorry :("}.

Now every time I try to sign in I get the same error.

I can repeat the process by going to my Github->Settings->Applications and revoking the access to the authorized application "Travis CI".  I then try to sign in again, and again I get the error.

**Comment by jaenmedina** [comment]
I'm getting this same error (Travis encountered an error, sorry :() when I try to use the API to restart a job. I also get the following headers:
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Server: nginx
Date: Sun, 13 Dec 2015 19:30:08 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Status: 500 Internal Server Error
Via: 1.1 vegur

**Comment by sqlboy** [comment]
Im seeing this right now. :(

**Comment by rlech** [comment]
I have the same issue again when trying to login into travis ci

**Comment by meganchen1996** [comment]
Same, I'm having this issue right now. Deleted my cookies, thinking maybe I had a bad github token. Tried in incognito mode on Chrome bc why not, but still has the unresolved github token error

**Comment by DatenMetzgerX** [comment]
I get the exact same error message. First, my travis builds got no longer started for pull requests... then i removed and added travis from the authorized applications... and now this error

**Comment by rehrumesh** [comment]
I also get the same error

**Comment by BanzaiMan** [comment]
GitHub is currently having a DNS issue, so you cannot get authenticated through them. Sorry. https://twitter.com/githubstatus/status/789433336083001344 This is unrelated to the issue at hand. Please try again when the GitHub's issue is resolved.

I am locking this issue.
