### ISSUE TITLE
Error when signing in from github

### ISSUE THREAD

**Issue by andrewzwicky** [travis-ci/travis-ci#1863]
Similar to issues [#1127](https://github.com/travis-ci/travis-ci/issues/1127), [#1567](https://github.com/travis-ci/travis-ci/issues/1567), and [#963](https://github.com/travis-ci/travis-ci/issues/963) I cannot log in via github.  I do see the access screen that shows what travis will have access to, but then a plain text error shows up:  `{"error":"Travis encountered an error, sorry :("}`.  If I refresh the page, i get `could not resolve github token`.  I do not think I have ever tried to log in to travis with this username before, and I haven't changed my github username, so I'm not sure how related those other issues are.  Using google chrome on windows 7.  Let me know if you need any more information, or want to close this issue and re-open another issue.

Thanks.

**Comment by rehrumesh** [comment]
I also get the same error in mac (safari and firefox)

**Comment by BanzaiMan** [comment]
GitHub is currently having a DNS issue, so you cannot get authenticated through them. Sorry. https://twitter.com/githubstatus/status/789433336083001344

**Comment by BanzaiMan** [comment]
I'm locking this.
