### ISSUE TITLE
Show colored whitespace

### ISSUE THREAD

**Issue by fernandoacorreia** [travis-ci/travis-ci#1873]
It would be useful if the logs could show colored (reverse) whitespace, like this:

![http://i.imgur.com/g8cH7sh.png](http://i.imgur.com/g8cH7sh.png)

Currently, this color is not visible as can be seen in [this build](https://travis-ci.org/mohiva/play-silhouette/builds/17354586#L82).

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
