### ISSUE TITLE
Add a ci include tag

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis-ci#1880]
My work cycle is:

Create a branch to hack a bunch of changes in[call it hackSomechange].
Commit frequently
When done, create a new branch, featureSomefeature and squash/cherry pick commits into it

As such, I want to blacklist all branches beginning with the word hack - BUT there are times when I want to run the build cycle to see if it works.  So the inverse of adding [ci skip] to the comment, from http://docs.travis-ci.com/user/how-to-skip-a-build/ would be useful for blacklisted branches.  IE something like [ci run]

**Comment by zilinc** [comment]
Good to find this old discussion. So are there any ways of doing it after 3+ years? My use case is easy to explain: I have a feature branch where the new feature is not covered by the test suite so I excluded it from CI. But very occasionally I do touch the code which is within reach of the tests so I want to invoke CI. Thanks.
