### ISSUE TITLE
Request for API, data dump, or reports for build time, success data

### ISSUE THREAD

**Issue by garysweaver** [travis-ci/travis-ci#1883]
Even though there would be outliers in the data for projects that build/test differently depending on the environment, for many projects, it could be useful to see metrics related to the build time for successful builds (and perhaps failed builds) between ruby 1.9.3, 2.0.0, 2.1.0, JRuby 1.7.9 in 1.9 mode, etc. These numbers vary significantly between sets of builds (because of the many factors involved- outgoing calls for gems blocked/delayed, etc., what else is being processed/built, etc.), however when looked at across all projects and over time, perhaps there is information on which environments build faster, or on how some external change may have coincided with failed builds, etc. which might be useful to the community as a whole.

Since past information on builds is kept, is there a way to access this information for build data in a more reportable format, possibly either via an API or a partial DB dump file that could be periodically updated? Or would you be willing to provide such metrics in graphs (in addition to the more recent status graphs on http://status.travis-ci.com/, but perhaps on another site)?

I think there is enough information about builds now that it could be helpful.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
