### ISSUE TITLE
Can not access file through symlink?

### ISSUE THREAD

**Issue by c9s** [travis-ci/travis-ci#1898]
I have a `tests` link to parent `tests` directory. but it seems tests/bootstrap can not be accessed?

https://travis-ci.org/c9s/Pux/jobs/17766060#L523

**Comment by chris-fa** [comment]
@c92 Could you try to remember please 😭

**Comment by BanzaiMan** [comment]
@chris-fa If you are having a similar issue, please open a separate issue along with the build log URL that shows the problem, and we'll take a look.

**Comment by chris-fa** [comment]
@BanzaiMan solved it, turns out i was starting `php -S` on the wrong document root. close please.
