### ISSUE TITLE
wrong github status message on github's pull request

### ISSUE THREAD

**Issue by garbas** [travis-ci/travis-ci#1910]
when creating a pull request from a branch (on the same repository) travis will trigger 2 jobs. one for the branch and one for the pull request.

we only run complete suite of tests on pull requests and master branch. for other tests we only run quick style check and unittests (which are quick).

now what happens is that status on pull request is linked to the branch travis job, not pull request one.

somebody else also has this problem?

**Comment by BanzaiMan** [comment]
We report 2 builds to GitHub now.
