### ISSUE TITLE
Build Failures: capybara -- `require': cannot load such file -- nokogiri (LoadError)

### ISSUE THREAD

**Issue by huangsam** [travis-ci/travis-ci#1919]
![image](https://f.cloud.github.com/assets/515617/2052448/2403a4e6-8a97-11e3-973f-2967651c4357.png)

I'm not sure how to resolve this one. I've been trying to update my Gemfile to use different versions of capybara and so far nothing has been working to resolve this issue for my Travis-CI builds. Any ideas?

**Comment by hypolyte** [comment]
I'm using ruby 2.3.3 on my project and nokogiri 1.6.8.rc2.The build failed on Gitlab ci.The error message is: `require': cannot load such file -- nokogiri (LoadError).
could someone helps?Thanks!

**Comment by BanzaiMan** [comment]
@hypolyte You'll need to ask Gitlab for support.

**Comment by hypolyte** [comment]
That's what I'm doing!

**Comment by BanzaiMan** [comment]
@hypolyte Sorry, but this is GitHub.
