### ISSUE TITLE
Status images broken for repository names that include a dot

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#192]
See https://secure.travis-ci.org/rubygems/rubygems.org.png

That's a rails routing issue.

@qrush pointed us to https://github.com/rubygems/rubygems.org/blob/master/config/routes.rb#L11 and https://github.com/rubygems/rubygems.org/blob/master/app/models/rubygem.rb#L2-4

@dmathieu, assigning this to you because i seem to remember you've worked on the status images, if you don't want the ticket just find someone else :)

**Comment by dibley1973** [comment]
Is this broken again? I ask as I have dots in my repo name and my build status is "UNKNOWN".

https://travis-ci.com/dibley1973/Dibware.Salon

**Comment by dmathieu** [comment]
@dibley1973 you're commenting on an issue from 2011. If this is indeed broken again, it's very unlikely to be for the same reason.

**Comment by dibley1973** [comment]
No worries. It did start working after a few builds, so maybe it was just a bit delayed for some reason. Was working for me again last time I checked. Thanks for the response.
