### ISSUE TITLE
Repository owner does not seem to always be synced

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#1940]
Out of all repositories created in 2014, only about 5% have the `owner_id` set:

```
=> SELECT COUNT(owner_id)::float/COUNT(*)::float*100 FROM repositories WHERE created_at > '2014-01-01';
     ?column?     
------------------
 4.95135163913697
(1 row)
```

I tried looking at our code to see where the owner is synced, but I was unable to find it. Some of the repositories have them set, so we must be syncing this information somewhere, but I can't seem to find out where.

Any insight in what might be going wrong here?

**Comment by joshk** [comment]
Closing this as the issue has become stale and because GitHub Sync has undergone massive improvements lately.
