### ISSUE TITLE
Travis CI Explore Page

### ISSUE THREAD

**Issue by whatasunnyday** [travis-ci/travis-ci#1941]
<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/travisci">@travisci</a> i would love to be able to browse failed builds of different projects by language to help fix issues in FOSS. is it possible?</p>&mdash; Sunny Juneja (@SunnyRJuneja) <a href="https://twitter.com/SunnyRJuneja/statuses/430961261971382272">February 5, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script><blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/SunnyRJuneja">@SunnyRJuneja</a> not currently, but that’s a great idea!</p>&mdash; Travis CI (@travisci) <a href="https://twitter.com/travisci/statuses/430961358629511168">February 5, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Hey everyone! Some wonderful folks on IRC said I should come here to discuss this further. I've spent a lot of time on snooping around github and looking at travis builds to see if a project has any broken specs so I can help fix (my new years resolution is to become active in OSS). I was thinking that this process would be easier if Travis just listed builds that were broken. 

@joshk  recommended I post a wire frame of what I was thinking..
![explore](https://f.cloud.github.com/assets/1108341/2094933/8b20c74c-8ed6-11e3-82b0-68dfb7ed1f48.png)

This is admittedly very simple and there is plenty of place for more work. What do you guys think is missing? I'm under the feeling that there could be more filtering options because its still easy to get lost in the sea of libraries. 

What other use cases do you think the explore page has?

joshk also mentioned that a better fit for this might be an external application like codetriage which I think is a great idea. 

Available for editing here:
https://gomockingbird.com/mockingbird/#5cmt7ej/mBiAW

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
