### ISSUE TITLE
travis_wait() function for long-running tasks

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#1962]
A process in the build may be **expected** to run for a long time without output. For this, we might consider providing a bash function such as this:

``` bash
travis_wait() {
  local cmd="$@"
  local log_file=travis_wait_$$.log
  $cmd &
  while true; do
    ps -p$! 2>&1 >/dev/null
    if [ $? = 0 ]; then
      echo "still running: $cmd"; sleep 15
    else
      echo "$cmd finished"
      cat $log_file
      break
    fi
  done
}
```

This function sends a command to the background, checks the status and writes to STDOUT every 15 seconds. When the command finishes, the function dumps the command's output.

**Comment by Carlgo11** [comment]
So this was merged? Can you send a usage string?

**Comment by BanzaiMan** [comment]
`travis_wait do_cmd` or `travis_wait 30 do_cmd`.

**Comment by Carlgo11** [comment]
Okay thanks :)
