### ISSUE TITLE
Connection refused in bundle install

### ISSUE THREAD

**Issue by dkubb** [travis-ci/travis-ci#197]
With two projects I'm seeing an error "Connection refused" when doing a bundle install:

http://travis-ci.org/#!/dkubb/veritas-optimizer/builds/61221
http://travis-ci.org/#!/dkubb/veritas-sql-generator/builds/61202

Now, it would be one thing if this was one time, but I've seen this consistently with JRuby. The builds seem to very regularly fail with that error on JRuby, so I wondered if maybe it was a sign of something deeper going on.

**Comment by simonykq** [comment]
@michaelfairley  We had a jruby application built on travis and it seem that I had a similar issue. The build randomly failed at some gem when running bundle install with the following error:
```
Gem::RemoteFetcher::FetchError: Errno::ECONNREFUSED: Connection refused - Connection refused (https://rubygems.org/gems/coderay-1.1.0.gem)
An error occurred while installing coderay (1.1.0), and Bundler cannot continue.
```
Could you confirm with me what the current workaround on this?


Many thanks!
