### ISSUE TITLE
Build status image cached by GitHub

### ISSUE THREAD

**Issue by hotpxl** [travis-ci/travis-ci#1970]
I added the build status image to `README` as instructed. But GitHub is caching the image. I have already used `https`, the problem persists.

Now even when I'm failing, Github shows passing, which loses the meaning of showing the image.

**Comment by monolithed** [comment]
Have the same problem

![1432917544791](https://cloud.githubusercontent.com/assets/803674/7887533/7082fc98-063a-11e5-9924-1b5f5e5c1129.png)

**Comment by eustas** [comment]
Badges are broken again: https://github.com/google/brotli
Navigating to image address leads to  "Not Found" camo page.

**Comment by shearn89** [comment]
Same as @eustas - just started using Travis on shearn89/toughen and the image in the README link is broken.
