### ISSUE TITLE
"g++: internal compiler error: Killed (program cc1plus)" not reproducible on Precise VM

### ISSUE THREAD

**Issue by KayEss** [travis-ci/travis-ci#1972]
I've been trying some C++ projects on Travis, but have a problem with g++ (clang works fine).

In all three projects I've put up so far I get a consistent g++ crash in one file. I've set up a couple of Precise VMs (both 32 and 64 bit) and can't reproduce the problem there.

I'm not entirely sure what I can do to resolve this -- is there anything non-standard in the environment that might help me track this down?
- https://travis-ci.org/KayEss/fost-base-dev/jobs/18963298
- https://travis-ci.org/KayEss/fost-hello/jobs/18921192
- https://travis-ci.org/KayEss/fost-hello/jobs/18921192

As you can see between the second two and the first, I tried to remove a diagnostic suppression that gcc wasn't understanding, but that had no effect. I'm kind of at a dead end right now.

**Comment by chrisdembia** [comment]
We have this issue as well; https://github.com/opensim-org/opensim-core/issues/455.

**Comment by kashefy** [comment]
I keep running into this also on my project [kashefy/elm#60](https://github.com/kashefy/elm/issues/60).
I thought adding "--param ggc-min-expand=3 --param ggc-min-heapsize=5120" to CXX_FLAGS would help by triggering garbage collection more often, but I don't think it did. Triggering it more frequently slowd down the proces so much the build ends up timing out.

**Comment by msmummy** [comment]
Having the same problem, tried g++-4.8, g++4.9

**Comment by kadasaikumar** [comment]
Please take look at the memory details before running the process. 
$ free -k
$ free -m to check the ram and swap details.

if you have enough space for to run the program then it wouldn't happen.
Please increase your swap space.

**Comment by greg7mdp** [comment]
you could try passing the following flags to gcc:

-save-temps  -ftrack-macro-expansion=0

**Comment by denji** [comment]
+ https://gcc.gnu.org/ml/gcc/2017-04/msg00026.html
