### ISSUE TITLE
How to Change Email Address

### ISSUE THREAD

**Issue by scalatest-travis** [travis-ci/travis-ci#1977]
Hi, 

May I know how can I change my email address in profile?

Thanks.

**Comment by ssbarnea** [comment]
The current implementation is really broken because the github email address from the profile is public and many users, including me are keeping it empty or putting an invalid address there.

**Comment by BanzaiMan** [comment]
@ssbarnea Could you elaborate on what you think is broken? You don't have to have an email address publicly visible on GitHub in order to receive email notification from Travis CI. As long as there is one on record, it will be synced and you will receive notification at that address.

**Comment by tmyrden** [comment]
@BanzaiMan I currently have 3 emails on file with GitHub. Travis pulls my primary email and doesn't give me the option to change it in the dashboard (https://magnum.travis-ci.com/profile/info). Seems like the only way to change my email on Travis is to change my GitHub primary email.

What I'd like to see is one of the two following options:
1. Have a dropdown on the Travis profile page that allows me to select from any of my GitHub emails.
2. Have a text field that lets me set my email to whatever I want.

**Comment by Lelith** [comment]
+1 for this, i have a private address which is primary and i have a company address which i want to have NOT as primary. so my private account gets spammed by travis (when i say spammed, i mean it literaly, all mails get automaticly sorted to spam because of the HUGE amount of mails travis is sending to me)

**Comment by joshk** [comment]
@tmyrden agree, those two ideas are great!

We are working on some big changes right now that are UI related, and once these have been deployed we can look into this further.

@Lelith we use the email address found in the Git commit info, so if you change it on your dev machine then we will send email to a different address. We understand this isn't perfect, and are working on big changes to notification settings.

**Comment by dbkaplun** [comment]
+1

**Comment by kkelleey** [comment]
+1

**Comment by IamGianluca** [comment]
Same issue here. It will be good if Travis could recognise the email address set as primary in GitHub, or at least let you set it.

**Comment by mapleoin** [comment]
It looks like travis is using the last email added to github. Would be great to have a way to change this as there's no way to change the order of the emails on github's side (and I have 8 of them there).

**Comment by henning** [comment]
+1 
I want to chose completely freely where I want my build mesages sent to!

**Comment by sobolews** [comment]
+1
I'd like to be able to send emails to a different address, or at least turn them off.

**Comment by carueda** [comment]
+1 (and why is this entry closed?)  Various solutions are proposed here ... but at least please send the notifications to the *primary* Github email address.  Thanks.

**Comment by BanzaiMan** [comment]
Please read https://docs.travis-ci.com/user/notifications/#How-is-the-build-email-receiver-determined%3F.

To disable email notification:

```yaml
notifications:
  email: false
```

If you want to send notification to a different address, configure `git` to use it.

We have plans to move notification configuration to Settings page, but there is no ETA to share.

**Comment by carueda** [comment]
Thanks for the quick response!

**Comment by michaelthorne** [comment]
+1 for a settings page. This drives me insane! :feelsgood:
