### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.0:shade

### ISSUE THREAD

**Issue by claussni** [travis-ci/travis-ci#1981]
TravisCI refuses to execute the Maven Shade plugin. I'm not sure if there is an issue. On my machine it works though. 

Here is what Maven says: 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.0:shade (default) on project fcrepo-migration: Execution default of goal org.apache.maven.plugins:maven-shade-plugin:2.0:shade failed: A required class was missing while executing org.apache.maven.plugins:maven-shade-plugin:2.0:shade: org/sonatype/aether/version/VersionConstraint
```

Here is the failed build:
https://travis-ci.org/slub/qucosa-fcrepo-migration/builds/19169365

**Comment by SaidJunior** [comment]
Can you tell me @claussni how did you make to update the shade plugin .. i'm stack with that a little !

**Comment by claussni** [comment]
You probably missed the commit linked above: https://github.com/qucosa/qucosa-fcrepo-migration/commit/9dd5f8a55661ac4e5b36c278f0bffcf8e11271f6

**Comment by liuzhanqi** [comment]
I encounter the same error and your solution works! Thanks a lot.
