### ISSUE TITLE
No distributions at all found for mysql-connector-python==1.1.6

### ISSUE THREAD

**Issue by robberphex** [travis-ci/travis-ci#1987]
I just test CI, and I use [mysql-connector-python 1.1.6](https://pypi.python.org/pypi/mysql-connector-python/)

but, I get the fail.
like this:https://travis-ci.org/RobberPhex/Django-SimplePastebin/jobs/19390378

**Comment by bl4ckmesa** [comment]
FYI the pip syntax is weird here in my opinion.  The whole command should look like this:
`> pip install mysql-connector-python --allow-external mysql-connector-python`

**Comment by martin1988** [comment]
awesome!

**Comment by juliusakula** [comment]
if `pip install mysql-connector-python --allow-external mysql-connector-python` doesn't work (and I agree that syntax is weird), try cloning the source and adding to your python path via setup.py http://stackoverflow.com/a/34027037/3100494
