### ISSUE TITLE
Where can I debug the deploy/after-deploy steps

### ISSUE THREAD

**Issue by AdrienLemaire** [travis-ci/travis-ci#1991]
Hi Travis,

I'm trying to set Continuous Deployment on Heroku via Travis for [CoinsManager](http://www.coinsmanager.com/) in [this PR](https://github.com/CoinsManager/CoinsManager/pull/44).
Travis [tests pass](https://travis-ci.org/CoinsManager/CoinsManager/builds/19467071), but I do not see any new activity in my heroku application, nor any logs to report what has been attempted by Travis on Travis side.

How can I debug and fix my deployment settings?
Thank you for your support

**Comment by harishvc** [comment]
I had to add "-" before "secure" .  
``` 
  api_key:
     - secure:  long-secure-hash
```

**Comment by fjmva** [comment]
This was very helpful! I was almost losing my mind. thanks @Fandekasp
