### ISSUE TITLE
Add URL endpoint for branch that redirects to latest build on that branch

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#1996]
So users can link to a branch from status images.

**Comment by cvrebert** [comment]
:+1:

**Comment by lukmdo** [comment]
+1 that would be neat to have

**Comment by rkh** [comment]
`/v3/repo/{repository.id}/branch/{branch.name}` should give you what you want. This currently only works with repository.id, but we should be rolling out a repository.slug based version the next days.

Note that this is part of our unreleased v3 API and JSON payload and URIs might change.

**Comment by shivamdixit** [comment]
@rkh Is there any way through which I can access the current build status of a branch? Redirecting to latest build might land us to a PR build, whose status is not necessary the status of the repo. For ex: Even if the latest PR build failed, still the travis badge displays "Build passing" because of last merge build passed.
I just want behavior similar to that of travis badge. Any help?

**Comment by kenorb** [comment]
@rkh Any progress on that? The mentioned API URL only returns JSON format, what about the landing page as requested in the title? So the branch images can point to the right URLs?

**Comment by FezVrasta** [comment]
Still no way to have `/:owner/:repo/builds/latest/:branch`?

**Comment by kenorb** [comment]
Related: #5024

**Comment by jgebal** [comment]
I'm also interested in having that feature

**Comment by gorn** [comment]
I apologize if I do not understand something, but why this issue is closed, when the bug is not fixed. Or is it "WONTFIX" status?

**Comment by mbdevpl** [comment]
Possibly related to: https://github.com/travis-ci/travis-ci/issues/1363 which is a request to have a page with build history for a single branch. Such "branch history" page could be an end-point alternative to "latest build on a branch" page.

However, the last update there, from 2014, says:

> no one else showed interest, it is implemented in the CLI, closing for now

I'd be interested in having that feature - could be very useful for build status tables where not only images show build status of each branch, but also links lead to most recent build page (or history of builds for that branch).

I'm also puzzled if this is wonfix or not...

**Comment by jgebal** [comment]
+1

**Comment by gorn** [comment]
+1

**Comment by joker234** [comment]
Would love to have that too.

**Comment by rgerkin** [comment]
This exists in readthedocs, requires.io, coveralls.io, etc.  It should exist in Travis.

**Comment by Quuxplusone** [comment]
Yes, please.

**Comment by Krinkle** [comment]
Vote for the feature at https://travis-ci.community/t/landing-page-for-specific-branch/6710. (Thanks @DracoBlue via https://github.com/travis-ci/travis-ci/issues/5024).
