### ISSUE TITLE
PyPI deployment upload_docs not reading upload_dir directive

### ISSUE THREAD

**Issue by mdshw5** [travis-ci/travis-ci#2011]
The PyPI deployment seems to always run `setup.py upload_docs`, looking for docs under `build/docs`, which does not exist in my project structure. I've set an alternative path in my `setup.cfg`:

``` ini
[upload_docs]
upload-dir = docs/_build/html
```

However, this is not recognized during PyPI deployment. Here is an example of this failure in a project: https://travis-ci.org/mdshw5/pyfaidx/jobs/19814283#L439. This failure prevents successful deployment.

**Comment by BanzaiMan** [comment]
The PR has been merged. If you wish to test this, use `edge: true`. Thanks.

**Comment by phantomas1234** [comment]
+1 for enabling `upload_docs: no`. I don't care for uploading docs to pypi because I use RTD.

**Comment by yoavram** [comment]
But this should probably be [in the docs](http://docs.travis-ci.com/user/deployment/pypi/#stq=&stp=0).
