### ISSUE TITLE
Feature Request: Reduce setup time for parallelized builds

### ISSUE THREAD

**Issue by comjf** [travis-ci/travis-ci#2012]
Problem: We parallelize 4 times right now and will only do so more often. The setup phase of the travis run takes a good amount of time. (Downloading the 1.3GB repository from github, installing dependencies, gems, setting up rake tasks, etc). This is wasted time on all 4 of our boxes when it could happen just on one.

Could we think about a solution where we run these setup sets once, then parallelize off of that base image? With something like docker this would be easier, but I'm not sure how your backend infrastructure is setup. I know this might be a long term feature request, but I think it would be beneficial for both parties.

Thank you,
James Flowers

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
