### ISSUE TITLE
Rails server fails to start, just get rails usage message

### ISSUE THREAD

**Issue by deiga** [travis-ci/travis-ci#2017]
Here's an example build https://travis-ci.org/deiga/new-Roydon/jobs/19934208
I have this line in my `before_script`: `- rails server -d -e test` and it has worked before and currently works in my other rails project.

The message I get

```
Usage:
  rails new APP_PATH [options]
...
```

**Comment by programminghack** [comment]
Try changing the privileges of the folder of your project, I happened to me as well and I made everything until I realized that folder privileges were only writing

**Comment by kpedroza** [comment]
cd to your project, then, run rails server
