### ISSUE TITLE
Provide PHP extension ssh2

### ISSUE THREAD

**Issue by h4cc** [travis-ci/travis-ci#2023]
Please add the PHP extension ssh2:
http://pecl.php.net/package/ssh2

This is currently needed to install the extension:

```
before_script:
  - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
  - pecl install -f ssh2-beta < .noninteractive
```

**Comment by cirpo** [comment]
Up!
it's the second time that pecl website is down and it's 25 min that I'm waiting for the builds...

thank you very much

**Comment by yurevichcv** [comment]
:+1:

**Comment by cirpo** [comment]
any news? :)

**Comment by sergeyklay** [comment]
:+1:

**Comment by BanzaiMan** [comment]
How long does it take to build it?
