### ISSUE TITLE
Syntax errors in .travis.yml should not be treated like a missing .travis.yml

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#2025]
Especially when disabling builds without a .travis.yml, this leads to a very confusing situation.

**Comment by arjenvanderende** [comment]
Just fell victim to this bug. :cry:

**Comment by jeremeamia** [comment]
Just ran into this as well. :cry:

**Comment by cjmurphy42** [comment]
+1... just had the same issue

**Comment by OrkoHunter** [comment]
+1 facing same issue
