### ISSUE TITLE
Back navigation after Sign-In coming from a PR/Commit not working

### ISSUE THREAD

**Issue by mrackwitz** [travis-ci/travis-ci#2028]
Back navigation is also still screwed up when coming from a pull-request / commit from GitHub and you have to sign up. This is very annoying while code review and you want to go back to the pull-request e.g. because you want to write a comment, what should be fixed. Instead you are jailed on the last build.
(See #563)

**Comment by roidrage** [comment]
I just tried this again, and this seems to work as expected now, so I'm closing this issue.
