### ISSUE TITLE
Update build environment with CMake 2.8.8 or later

### ISSUE THREAD

**Issue by rhyolight** [travis-ci/travis-ci#2030]
We are having [cmake problems](https://travis-ci.org/numenta/nupic.core/jobs/19944336#L92), which [seem to be caused](https://groups.google.com/forum/#!topic/travis-ci/zkBfY9b6GPY) by using features of cmake that were added in 2.8.8. My feature request is to update cmake within build boxes to use the [latest version of cmake](http://www.cmake.org/cmake/resources/software.html#latest).

**Comment by BanzaiMan** [comment]
Closing this, as we've shipped Trusty support.
