### ISSUE TITLE
Pre-process travis.yml with ERB

### ISSUE THREAD

**Issue by wr0ngway** [travis-ci/travis-ci#2037]
Pre-processing the travis.yml with ERB would allow much more flexibility without sacrificing simplicity in the basic use case

Something like:
YAML::load(ERB.new(travis_yml_string).result)
Where the ERB context has access to the data from the git notification.

It seems like there are a number of use cases where this could help:
* Having a common travis.yml across repos by reading its contents from a (gist) url (#306, #1131)
* Toggling build behavior based on the commit (e.g. do something different for PRs or topic branches - #1302)

There are possible security problems with this - both for travis executing the code, and client private repo's getting exposed by rogue ERB, but they can be mitigated.

**Comment by nysthee** [comment]
It would be a great asset if one could specify behaviour depending on branches (with a given prefix: feature/, bug/ for example).

**Comment by joshk** [comment]
Thanks for all the suggestions. I am going to close this issue as preprocessing using ERB is a security concern.

Thanks  a bundle.

Josh
