### ISSUE TITLE
Enable caching on OS X (TravisPro)

### ISSUE THREAD

**Issue by johanneswuerbach** [travis-ci/travis-ci#2041]
Today caching isn't available on OS X workers on travis pro and our builds are installing cocoapods and all pods on every build (takes around 3 minutes).

Having the linux worker caching also os x would be awesome.

**Comment by mislav** [comment]
@henrikhodne Caching is now available for opensource repos as well, but it only seems enabled on "linux" builds. On "osx" builds for the same repo there seems to be no attempt from Travis to restore or update a cache during build. Is this a technical limitation right now?

**Comment by BanzaiMan** [comment]
@mislav It's a separate issue. Could you open a new issue, please?

**Comment by mislav** [comment]
OK https://github.com/travis-ci/travis-ci/issues/4011
