### ISSUE TITLE
Provide ninja-build for C build environment

### ISSUE THREAD

**Issue by baruch** [travis-ci/travis-ci#2043]
I'm using ninja-build for my project (libxcoro) and it fails to install from the Ubuntu repository, probably it's an older Ubuntu with no ninja-build in the repository. Is it possible to add ninja-build alongside scons for the C environment?

**Comment by dagar** [comment]
+1 ninja-build

**Comment by konserw** [comment]
+1

**Comment by jingleyang** [comment]
+1 
ninja is used for building chromium. Could you consider support it?

**Comment by NiklasRosenstein** [comment]
I've solved it this way:

```
install:
  - mkdir .tmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .tmp/ninja-linux.zip
  - unzip .tmp/ninja-linux.zip -d .tmp
before_script:
  - export PATH=$PATH:$PWD/.tmp
```
