### ISSUE TITLE
Ubuntu 14.04 LTS - Trusty Tahr

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#2046]
The next version of Ubuntu LTS–14.04 Trusty Tahr–is [scheduled](https://wiki.ubuntu.com/TrustyTahr/ReleaseSchedule) to be released April 17. I think we should aim to update to 14.04 after it's released.

This means we get to take advantage of all the new versions in the Ubuntu package repositories (the 12.04 versions are starting to get more and more outdated), but it also has the potential to break quite a bit.

Opening this so we can start tracking when and how to do the update.

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/trusty-ci-environment
