### ISSUE TITLE
Add RethinkDB to supported datastores

### ISSUE THREAD

**Issue by oremj** [travis-ci/travis-ci#2048]
http://www.rethinkdb.com/

**Comment by hueniverse** [comment]
Any reason why rethinkdb is not officially supported?

**Comment by jalcine** [comment]
PR travis-ci/apt-source-whitelist#91 handles this being in Travis by default.

**Comment by hueniverse** [comment]
Just add:

```yaml
addons:
  rethinkdb: "2.3"
```
