### ISSUE TITLE
Build caching should happen at the very end of the build or be more customizable

### ISSUE THREAD

**Issue by xaka** [travis-ci/travis-ci#2059]
Hello there,

It looks build caching happens right after `script` hook, but before `after_success`, `after_failure` and `after_script`, which leads to a problem of not caching entities that are being created during those stages (mostly `after_success`).

In my case travis is configured to do testing and deploying. I guess it's wise to do nothing  related to deploying if testing has failed, otherwise i run additional commands that retrieve stuff, required for deploying, from external sources that i'd like to cache. I do all of that as part of `after_success` hook and nothing gets cached. As a workaround i had to move everything to `before_script` hook, but it leads to a longer testing results, especially if those are failing.

I do understand the reasons behind doing a build caching right after `script`, but there should be either an option to move caching one step further or run it one more time when build completes.

I think travis needs a clear separation between testing and deploying stages, something like dependable tasks in jenkins or bamboo, and each stage would have its own cache.

**Comment by BanzaiMan** [comment]
We have added the [`before_cache` phase](http://docs.travis-ci.com/user/caching/#before_cache-phase) as well.
