### ISSUE TITLE
Cancel all builds in queue

### ISSUE THREAD

**Issue by gnutix** [travis-ci/travis-ci#2071]
I'd very much like a small button next to the "Queue (42)" allowing to skip every builds at once. It's very painful currently to click on each of them and skip them, as the flash messages stack up.

**Comment by danoli3** [comment]
+1 to this. I just don't want to overload travis sometimes when older commits have been superseded or will be. If there is a stack of 20 in a queue and I know the next push is all we care about, be great to kill all and save travis the processing

**Comment by roidrage** [comment]
I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
