### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by jdalton** [travis-ci/travis-ci#2076]
npm [recently introduced](http://fredkschott.com/post/2014/02/npm-no-longer-defaults-to-tildes/) the ability to specify the caret/circumflex (^) for dependency versions. Travis-CI would need to update its version of `npm` to support them too.

**Comment by fastest963** [comment]
It looks like some builds still run with an older version of npm:
https://travis-ci.org/fastest963/ChainLoading/jobs/50597218

I originally opened https://github.com/isaacs/node-tap/issues/115 but apparently the only recorse is to update npm.

**Comment by pbrianmackey** [comment]
@fastest963  That worked for me!  Thank you!!
