### ISSUE TITLE
Travis-CI is not picking up latest commits to a PR

### ISSUE THREAD

**Issue by certik** [travis-ci/travis-ci#2099]
In this PR:

https://github.com/sympy/sympy/pull/7272/commits

you can see that the latest commit that was tested on Travis is df7ce8ba54b10263231e5f405a98fe76c32307c8, which was pushed in 4 days ago (the corresponding build is https://travis-ci.org/sympy/sympy/builds/21171452). The latest commit 7605807566d36cead21562e970d35b9cb6f92c13 was pushed in a day ago, but Travis didn't pick it up at all.

Any ideas what is going on?

**Comment by mulondo** [comment]
hey I also have a similar issue with my travis, at first, it was working very well, detecting the PR, but now it nologer detects them, it still runs the old ones. I dont know how to solve this

**Comment by BanzaiMan** [comment]
@mulondo It is most likely a completely different issue after 4 years. Please open a new issue with details. Thanks.
