### ISSUE TITLE
Please include runkit extension for PHP

### ISSUE THREAD

**Issue by nijel** [travis-ci/travis-ci#2107]
Would it be possible to include runkit extension for PHP? It is quite useful for testing as it allows to mocking PHP internal functions with custom code.

It can be found here:

https://github.com/zenovich/runkit

**Comment by marekyggdrasil** [comment]
Just for the record, don't use

```
before_script:
  - pecl install https://github.com/downloads/zenovich/runkit/runkit-1.0.3.tgz
```

As link may be dead, instead just use

```
before_script:
  - pecl install runkit
```
