### ISSUE TITLE
Whitelist prevents tagged builds

### ISSUE THREAD

**Issue by Joshua-Anderson** [travis-ci/travis-ci#2111]
Right now if you use a branch whitelist like below, travis-ci won't build tags anymore, which seems logical to me. However, if you do use a whitelist there is no way for you to add tagged builds to the whitelist if you want to.

This `.travis.yml` will block all tagged builds.

```
branches:
  only:
    - master
```

It would be really cool if you could possibly do this:

```
branches:
  only:
    - master
    - tags
```

As always, thanks for your great work on Travis CI.

**Comment by wilzbach** [comment]
Hey, this is still a valid issue. I don't think that automatically closing old issues just because they are old helps anyone.
