### ISSUE TITLE
Ability to specify Xcode versions for Objective-C builds

### ISSUE THREAD

**Issue by maschall** [travis-ci/travis-ci#2113]
Often it is not possible for a project to update to the latest Xcode right away, it would be great if we could specify which version of Xcode could be used for a build.

Additionally, I think it would be useful to make it apart of the build matrix for projects like xctool and Cocoapods, because those projects often have to work with many versions of Xcode.

**Comment by roidrage** [comment]
Xcode versions, depending on their availability, can now indeed be selected via the .travis.yml.

I'm closing this issue for the time being.
