### ISSUE TITLE
Running the build locally

### ISSUE THREAD

**Issue by maschall** [travis-ci/travis-ci#2114]
This may go against the business model, but as a developer I would love the ability to run a build locally on my machine.  This would allow developers to test the results without pushing code and also be able to keep testing code if for whatever reason travis-ci service goes down.

Obviously the developer would need all the tools (i.e. for objective-c I would need xctool, Xcode, Cocoapods...) to build it.

**Comment by fulldecent** [comment]
*Here's my problem: over half the commits in my repo are "fix CI", "need to run CI test".*

To be clear, I am looking for a bash script, that I can run locally which takes the current working directory, or the latest commit in my Git, sets up the virtual machine, then does everything exactly like it is done on Travis... you know, repeatability.

Also discussed and complained about here http://stackoverflow.com/a/24936720/300224

**Comment by Joshua-Anderson** [comment]
@fulldecent [travis-build](https://github.com/travis-ci/travis-build) (the program that generates the build script) had a command line interface you can use to generate build scripts. The README of travis build has instructions you can use.

**Comment by jantman** [comment]
Also, if you're using the containerized Travis infrastructure, you can even run the builds [in the same Docker image that Travis uses](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image)

**Comment by BanzaiMan** [comment]
As pointed out, the docker images are available, and the debug instructions are also live.

This is not complete, but I think it is good enough for many situations.

I'm closing this now.

**Comment by fulldecent** [comment]
I now have a complete solution to reproduce Travis builds locally:

https://stackoverflow.com/a/49019950/300224

Only took 3 years to figure out!

**Comment by BenMorel** [comment]
This is nice for containerized Travis builds, but what about VMs running on GCE (using `sudo: required`)?

I need to install extra software (MySQL 8), and my Travis build fails starting the new `mysqld`. I need to get into the machine to troubleshoot.

Is there a place we can download Travis VM images from?

**Comment by rcowsill** [comment]
In case anyone's looking for [Troubleshooting Locally in a Docker Image](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image) linked above, it got removed from docs-travis-ci-com in [#1a71d87](https://github.com/travis-ci/docs-travis-ci-com/commit/1a71d878e9650cf13f829af940889c382f555fcd).
