### ISSUE TITLE
add option to color irc text red/green on passing/failure

### ISSUE THREAD

**Issue by matthiaskrgr** [travis-ci/travis-ci#2115]
It might be useful to have irc notification text colored green if the build passed and red if the build failed. This will make it easier to notice in case there is a lot of traffic in the channel.

This would only work if travis is configured to not post notices I think.

**Comment by Callek** [comment]
And the actual need of the issue (color pass/fail different colors) is made possible in issue #1332

**Comment by luzpaz** [comment]
sorry to re-open this ticket. is there an example of a working red/green text for pass/fail builds ?
