### ISSUE TITLE
Handle deleted branches

### ISSUE THREAD

**Issue by Celelibi** [travis-ci/travis-ci#2117]
I sometime rebase a branch and use a "nonce" branch to make one push per commit and then delete it. So that every commit will get built on travis.

If it happen that the builds didn't start when I delete the branch, the build will fail, while the commits are still reachable from other branches.

Maybe downloading a zip of the wanted commit instead of cloning the repository would be better?

**Comment by Faunsce** [comment]
There is still no way to handle non-existent branches polluting your repositories page on github manually w/o contacting support.
