### ISSUE TITLE
add maglev support

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#212]
We are currently running the [Sinatra CI against maglev](http://ci.rkh.im/job/sinatra-maglev/?). Should be as easy as `rvm install maglev`. If there are any issues, I'm sure @timfel would be willing to help.

@michaelklishin: ping

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
