### ISSUE TITLE
MongoDB does not start up on Docker containers

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#2125]
For some reason the mongodb service does not start on Docker containers with `sudo service mongodb start`

![image](https://cloud.githubusercontent.com/assets/2208/2559103/715c330c-b76a-11e3-8b0e-85082f934877.png)

The logs look like this: https://gist.github.com/svenfuchs/48e93185c9db2e0f85a7, which does not seem to contain an error. It just says that signalProcessingThread gets a signal 15 and then exits.

When I run `sudo /usr/bin/mongod --dbpath /var/lib/mongodb/` otoh then it seems to start up fine:

```
travis@4fb0ed8b13a9:~$ sudo /usr/bin/mongod --dbpath /var/lib/mongodb/
Sat Mar 29 17:51:21.218 [initandlisten] MongoDB starting : pid=523 port=27017 dbpath=/var/lib/mongodb/ 64-bit host=4fb0ed8b13a9
Sat Mar 29 17:51:21.218 [initandlisten] db version v2.4.9
Sat Mar 29 17:51:21.218 [initandlisten] git version: 52fe0d21959e32a5bdbecdc62057db386e4e029c
Sat Mar 29 17:51:21.218 [initandlisten] build info: Linux ip-10-2-29-40 2.6.21.7-2.ec2.v1.2.fc8xen #1 SMP Fri Nov 20 17:48:28 EST 2009 x86_64 BOOST_LIB_VERSION=1_49
Sat Mar 29 17:51:21.218 [initandlisten] allocator: tcmalloc
Sat Mar 29 17:51:21.218 [initandlisten] options: { dbpath: "/var/lib/mongodb/" }
Sat Mar 29 17:51:21.235 [initandlisten] journal dir=/var/lib/mongodb/journal
Sat Mar 29 17:51:21.235 [initandlisten] recover : no journal files present, no recovery needed
Sat Mar 29 17:51:21.235 [initandlisten] preallocating a journal file /var/lib/mongodb/journal/prealloc.1
Sat Mar 29 17:51:39.367 [initandlisten] preallocating a journal file /var/lib/mongodb/journal/prealloc.2
Sat Mar 29 17:51:57.212 [websvr] admin web console waiting for connections on port 28017
Sat Mar 29 17:51:57.212 [initandlisten] waiting for connections on port 27017
```

Any pointers?

cc @joshk

**Comment by parkr** [comment]
@svenfuchs Just bitten by this on dotcom. Any fixes?

**Comment by tayzlor** [comment]
experiencing this same issue - see https://travis-ci.org/Capgemini/angular-cart-demo/builds/97076469

**Comment by BanzaiMan** [comment]
MongoDB should start on all Linux infrastructures. https://travis-ci.org/BanzaiMan/travis_production_test/builds/195690368

I'm closing this.
