### ISSUE TITLE
Notifications for PRs

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2128]
Currently, some notifiers (e.g., HipChat, IRC, Campfire) do not send notification for Pull Request build results. We may consider this a configurable option.

**Comment by aseemk** [comment]
+1 to being able to disable PR notifications to Slack. Thanks!

**Comment by joshk** [comment]
@aseemk we are working on it :)

**Comment by aseemk** [comment]
Sweet, thanks guys!

**Comment by nicolasmccurdy** [comment]
@drogus :+1:

**Comment by ebarendt** [comment]
@joshk any word on this? It's been months and even a rejected PR for Slack.

**Comment by joshk** [comment]
I'm sorry for the delay.

We have just finished the new settings page, and are currently working on tidying up some other other screens within the UI. Afterwards we will start scoping out this work.

**Comment by matthuhiggins** [comment]
Is there some way to use the $TRAVIS_PULL_REQUEST variable to disable notifications on pull requests?

**Comment by olivierlacan** [comment]
We do get notifications on PR builds for Slack but it's apparently impossible to disable them. PR build failures are pretty noisy for our team. Would be nice to limit them to master only.

**Comment by joshk** [comment]
Hi @olivierlacan 

Due to the delay on our side to work on the notifications UI, we are looking into two options to fix this.

Either removing PR notifications for Slack for the time being, or adding the config to the Slack integrations page config.

I'll update this issue soon with our decision.

**Comment by aertmann** [comment]
@joshk: Hey did you guys reach a decision or do you have an idea when you will? Currently awaiting this decision since it will mean we will remove the notifications or add them to more repositories.

Personally hope you remove the PR notifications in the meantime and introduce them in a configurable way for all channels, not just Slack.

**Comment by BanzaiMan** [comment]
@aertmann The current plan is to add the opt-out option to Slack (which is live now on .org; delaying a bit on .com) and leave the option there to Hipchat until such time that the web UI is ready to handle notifications.

I am sorry to say that we do not have ETA when the web UI would have it, however.

**Comment by aertmann** [comment]
@BanzaiMan: Perfect, thanks a lot :) Guess you'll add it to https://docs.travis-ci.com/user/notifications/#Slack-notifications when it's available on travis-ci.com as well?

FYI: to disable it use the configuration setting ``on_pull_requests: false`` inside ``slack:``

**Comment by BanzaiMan** [comment]
The opt-out feature is now available on .com as well. The documentation has been updated as well.

I'm closing this now.

**Comment by aertmann** [comment]
:+1:

**Comment by aseemk** [comment]
The documentation says `on_build_requests: false`, but https://github.com/travis-ci/travis-ci/issues/2128#issuecomment-161178416 says `on_pull_requests: false`. Is the documentation right?

**Comment by BanzaiMan** [comment]
@aseemk Ooops. Sorry. It is `on_pull_requests`. I'll fix the docs shortly.

**Comment by aseemk** [comment]
No problem. Thanks for the great work!

**Comment by ross-nordstrom** [comment]
Late to the party -- is there a way to specify in the notification template that it's a PR?

Here's the template I currently use:
```
    - '%{repository}#%{build_number} %{result}: %{message} in %{duration} - (%{branch} - %{commit} by %{author})'
```

I'd like the `{branch}` part to:
* On branch builds - Say the `branch` name
* On PR builds - Say `PR` or `PR#<id>`

**Comment by ezyang** [comment]
I am a bit confused about this closed issue: https://docs.travis-ci.com/user/notifications/#IRC-notification seems to imply that IRC does not support PR notification. Are the docs out of date?

**Comment by karenetheridge** [comment]
Would it be possible to add a `on_pull_requests: true` option for the `email` category?

**Comment by Suor** [comment]
So may I send a email to a pull request author? It doesn't look like this use case is solved.

**Comment by winniengo** [comment]
@ross-nordstrom I tried creating two notifications... for branches `type: push; on_pull_requests: false` and PR's `type: pull_request` which seem to fire notifications accordingly. However the `pull_request_number` and `pull_request_url` never populated.
