### ISSUE TITLE
Enable Caching for Pull Requests

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#2130]
Currently caches are not stored for pull requests. This works fine for shortlived PRs, but is far from ideal for long running PRs.

We could enable PR caching by adding the PR number to the cache slug, for instance. Additionally, we could limit it to PRs from the same repository, though I don't think that will make much of a difference, at least for the time being, as we only support caching for private repositories.

**Comment by BanzaiMan** [comment]
I think we have this feature.
