### ISSUE TITLE
Display queue length on status page

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#2134]
[From IRC](https://botbot.me/freenode/travis/msg/12826011/):

> hey guys, it would be awesome to have something on a status page about how long the current backlog is on a new VM. average waits by hour and day of week would be killer in helping people work on build-intensive things outside peak hours :)

I *think* this could just be the average value for `started_at - queued_at` for jobs. That wouldn't include the time spent in the "QoS queue", only the time it takes from a job being queued to actually starting.

**Comment by joshk** [comment]
Closing this as it has become stale

**Comment by 6a68** [comment]
@joshk Is this issue stale because there's some UI that provides queue visibility? If there is, I'm afraid I'm having trouble finding it. Any thoughts? If this isn't implemented, could it be reopened?

**Comment by wking** [comment]
Old issue, but https://www.traviscistatus.com/ now shows backlog graphs for some worker categories.

**Comment by timtamimi** [comment]
Hi folks, should this ticket be revisited/reopened? It would be immensely helpful if there was some way to get an indication of how long a build is likely to sit in the queue.

**Comment by blakenan-bellese** [comment]
+1 on expected queue wait time
