### ISSUE TITLE
Support for Phabricator

### ISSUE THREAD

**Issue by roidrage** [travis-ci/travis-ci#2143]
A customer asked if we can support [Phabricator](http://phabricator.org), Facebook's code review tool.

**Comment by zerodiff** [comment]
@mdesanti did make an extension of ArcanistConfiguration or something else? I'm interested in doing essentially the same thing, and I'd appreciate more details if don't mind.

In any case, I also think it would be nice if Travis could look at other git repos outside of GitHub for other integrations.

**Comment by zerodiff** [comment]
As an FYI, here is an example of a [Phabricator integration](https://github.com/zerodiff/traphic) where we push topic branches (diffs) to GitHub for Travis-CI. During the build, we also update commit branch status (build started/succeeded/failed). The Travis web hooks handle some of what we want, but not all.

On a related note, it would be good if PHP was actually installed as a default utility. I can get around this on Linux, but on the OSX images, it's a bit trickier.

**Comment by mdesanti** [comment]
@zerodiff amazing! I will try it out and let you know if it worked. Sorry for my delay in replying to this issue!

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by mprobst** [comment]
FYI we'd be interested in this too, we're using Phabricator for several projects (e.g. https://github.com/angular/ts2dart, https://github.com/angular/sickle, etc).

**Comment by sheki** [comment]
Can we open this ? We are interested too.

**Comment by haleybash-optimizely** [comment]
Would be interested in this as well!

**Comment by perezd** [comment]
I'm interested in this as well.

**Comment by jverkoey** [comment]
Interested in this as well.

**Comment by perlow** [comment]
CircleCi has this feature.

**Comment by appsforartists** [comment]
This is probably achievable now, if the webhooks can be configured correctly.  I just tried [Using CircleCI with Phabricator](https://circleci.com/docs/phabricator/), a workflow which posts changes to GitHub and Phabricator at the same time.

As you can see, [travis tested the staged tag automatically](https://travis-ci.org/material-motion/material-motion-js).  When CircleCI completes a build, it sends the results to this webhook:

http://{ phabricator install }/harbormaster/hook/circleci/

If Travis posted a similar result there, it should be able to integrate with Phabricator without major changes to the Travis pipeline.

See also these issues:

- https://secure.phabricator.com/T9456
- https://secure.phabricator.com/T12011

**Comment by appsforartists** [comment]
Looks like this is the JSON payload posted to that webhook:

https://circleci.com/docs/api/#build

```json
{
  "payload": {
    "vcs_url" : "https://github.com/circleci/mongofinil",
    "build_url" : "https://circleci.com/gh/circleci/mongofinil/22",
    "build_num" : 22,
    "branch" : "master",
    ...
  }
}
```
