### ISSUE TITLE
OS X App Code Signing Fails Randomly

### ISSUE THREAD

**Issue by bradya** [travis-ci/travis-ci#2149]
At Slack, we're using Travis to automatically build and sign our Mac app to distribute to testers.

This works great, when it actually works. It works about 50% of the time.

Our build process at its core consists of two commands that we run in a shell script:

```
xcodebuild clean archive -archivePath "Products/Slack.xcarchive"

xcodebuild -verbose -exportArchive -exportFormat app -archivePath "Products/Slack.xcarchive" -exportPath "Products/Slack.app" -exportSigningIdentity "Developer ID Application: Tiny Speck"
```

The second xcodebuild command (which signs the app with our Developer ID) sometimes fails with the following error message:

```
error: Code signing operation failed
** EXPORT FAILED **
```

When it works, we get the following success message:

```
Moving exported product to '/Users/travis/build/tinyspeck/slack-macgap/Products/Slack.app'
** EXPORT SUCCEEDED **
```

This happens randomly, and will succeed sometimes and fail sometimes with just a simple version number increment (to trigger a travis build).

I've tried specifying -verbose when performing the xcodebuild, but I haven't been able to get an actual error message.

My guess is one of the Mac build machines is improperly configured, and it fails when the app builds on that machine.

**Comment by HrishiPol** [comment]
Hi..
I am also getting the same error.
It was working fine till few days ago and then suddenly it started throwing Code Sign operation failed: export Failed.
I am using Bot to build and create .ipa and then upload it to HockeyApp using script.
Could you please let me know what can be done in this case as i am really not getting what to do.
It is just creating archive file now.
Previously it was creating 2 files, .ipa and .archive.
Please help.

**Comment by abhishek789** [comment]
Hi..
I am also getting the same error.
It was working fine till few days ago and then suddenly it started throwing Code Sign operation failed: export Failed.
I am using Bot to build and create .ipa and then upload it to HockeyApp using script.
Could you please let me know what can be done in this case as i am really not getting what to do.
It is just creating archive file now.
Previously it was creating 2 files, .ipa and .archive.
Please help.

**Comment by jamesgmorgan** [comment]
@johanneswuerbach - works for me on a similar prob - thanks!

**Comment by lifuzu** [comment]
+1
Thanks for your solution, @johanneswuerbach !
