### ISSUE TITLE
Support Windows and OS X

### ISSUE THREAD

**Issue by steveklabnik** [travis-ci/travis-ci#216]
This will have to be done in steps, so I might break this issue down as support gets closer. Eventually, I'd like to make it such that the yaml file has something like:

    os:
      :windowsxp
      :osx
      :linux

Or whatever. So you can build on multiple operating systems as well as just Linux.

This has some interesting issues:

1) licensing
2) availablility
3) combinatorial explosion of rubies and platforms

**Comment by roidrage** [comment]
I'm closing this issue as we do have Mac support available. As for Windows, we do have ideas on it, and once we know more, we'll update this ticket.
