### ISSUE TITLE
Redis service fails to start on Docker containers

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#2166]
The Redis package that we currently install uses an init file like this:

```
root@089fae39196f:~# cat /etc/init/redis-server.conf
# redis-server - Redis Datastore Server
#
# Redis is a key value in memory persistent datastore

#start on (local-filesystems and runlevel [2345])
stop on runlevel [016]
respawn
expect fork
limit nofile 20000 65000
pre-start script
mkdir -p /var/run/redis
chown redis:redis /var/run/redis
end script
exec start-stop-daemon --start --chuid redis:redis --pidfile /var/run/redis/redis.pid --umask 007 --exec /usr/bin/redis-server -- /etc/redis/redis.conf
``` 

The `limit nofile` stanza fails on Docker containers (apparently ulimit can't be changed unless when run in `-privileged` model https://github.com/dotcloud/docker/issues/1900#issuecomment-24707682). 

Can this be removed?

**Comment by sendalot** [comment]
Can't get out of below error. Anyone found a solution?  Thanks.

[root@puppetmaster hw]# docker run -it nigel1 /bin/bash 
/usr/sbin/apache2ctl: 87: ulimit: error setting limit (Operation not permitted)
Setting ulimit failed. See README.Debian for more information.
Usage: /usr/sbin/apache2 [-D name] [-d directory] [-f file]
                         [-C "directive"] [-c "directive"]
                         [-k start|restart|graceful|graceful-stop|stop]
                         [-v] [-V] [-h] [-l] [-L] [-t] [-T] [-S] [-X]
Options:
  -D name            : define a name for use in <IfDefine name> directives
  -d directory       : specify an alternate initial ServerRoot
  -f file            : specify an alternate ServerConfigFile
  -C "directive"     : process directive before reading config files
  -c "directive"     : process directive after reading config files
  -e level           : show startup errors of level (see LogLevel)
  -E file            : log startup errors to file
  -v                 : show version number
  -V                 : show compile settings
  -h                 : list available command line options (this page)
  -l                 : list compiled in modules
  -L                 : list available configuration directives
  -t -D DUMP_VHOSTS  : show parsed vhost settings
  -t -D DUMP_RUN_CFG : show parsed run settings
  -S                 : a synonym for -t -D DUMP_VHOSTS -D DUMP_RUN_CFG
  -t -D DUMP_MODULES : show all loaded modules 
  -M                 : a synonym for -t -D DUMP_MODULES
  -t                 : run syntax check for config files
  -T                 : start without DocumentRoot(s) check
  -X                 : debug mode (only one worker, do not detach)
Action '/bin/bash' failed.
The Apache error log may have more information.
[root@puppetmaster hw]#

**Comment by BanzaiMan** [comment]
@sendalot Is that happening on Travis?

**Comment by sendalot** [comment]
What is Travis? Sorry I'm new to docker and ubuntu. This is a Dockerfile from pluralsight course. Docker is running on Oracle Linux(CentOS).

**Comment by roidrage** [comment]
Closing this issue, as this seems to work as expected now.
