### ISSUE TITLE
gvm is slow; add option to skip & manage Go manually

### ISSUE THREAD

**Issue by mislav** [travis-ci/travis-ci#2167]
I want to use Go 1.2.1, so I specify that in my `travis.yml` and gvm handles it well. However, since v1.2.1 is not available on the system, gvm needs to download and compile the source code. The whole process takes up 4–5 minutes of the whole build time, whereas tests run in less than 1.5 minutes.

Even if I switch to the default Go version on Travis (1.0.3) which is preinstalled, [the setup process still takes ~4 minutes](https://travis-ci.org/github/hub/builds/23057832) because of (I'm guessing) `gvm get + gvm update`, during which the whole Go repo is cloned using hg. This whole process seems needless, since the Go version was available all along.

I already use S3 to cache some of my dependencies, so I was thinking of installing the Go version that I need manually and restoring it from cache in subsequent builds. However, it doesn't seem that I can skip the current gvm process by editing my `travis.yml`. The `before_install` task still runs after the gvm has completed.

/cc @joshk @meatballhat @henrikhodne 
https://github.com/travis-ci/travis-build/blob/100c2fa2/lib/travis/build/script/go.rb#L28-L39

**Comment by meatballhat** [comment]
I think we're in decent shape now with the switch to using `gimme`.  Please yell if not and I'll reopen :smiley_cat:
