### ISSUE TITLE
Install `appledoc` on the OS X boxes

### ISSUE THREAD

**Issue by wearhere** [travis-ci/travis-ci#2183]
Appledoc used to be installed on the 10.8 boxes, but is not installed on the 10.9 boxes, as shown by [this error](https://travis-ci.org/inkling/Subliminal/jobs/23183609#L113).

It would be extremely useful if Appledoc were installed on the 10.9 boxes, because it cannot be installed using `brew`: Appledoc uses Garbage Collection, which is not supported in Xcode 5.1 (tomaz/appledoc/issues/435).

**Comment by pbrobst23** [comment]
http://docs.travis-ci.com/user/osx-ci-environment/

I don't see appledoc listed, has it been removed?

Falling back to the curl command has it working for me.

**Comment by Cocoanetics** [comment]
@henrikhodne Is Appledoc part of the xcode7 image?
