### ISSUE TITLE
matrix builds appears to not work for iOS

### ISSUE THREAD

**Issue by stig** [travis-ci/travis-ci#2184]
Here's a few examples where it _appears_ to pass, but it doesn't actually build the software, let alone run its tests:
- https://travis-ci.org/stig/json-framework/builds/23183696
- https://travis-ci.org/stig/json-framework/builds/23181404

Here's a build showing that simply specifying the `xcode_scheme` and `xcode_sdk` configs works:
- https://travis-ci.org/stig/json-framework/builds/23162713

Here's my earliest attempt at using a matrix - it didn't work at all:
- https://travis-ci.org/stig/json-framework/builds/23151377

Let me know if there's anything I can do to provide more information.

**Comment by vintagexav** [comment]
@ypresto I would recommend forcing the destination in your script to fix the problem.
Just add the following argument in your xctool script command line:
`-destination 'platform=iOS Simulator,name=iPhone 5,OS=8.1'`

**Comment by stig** [comment]
@vintagexav I don't see how that could work for matrix builds that cross-builds on OS X and ios?

**Comment by stig** [comment]
FWIW, I have now managed to solve this--finally! :-)

Here's the commit that fixes it:
https://github.com/stig/json-framework/commit/ceaa84a3d4b23fbb8ca3451dbb494601e8df3e26
