### ISSUE TITLE
Documentation for using capybara-webkit with xvfb is missing or out of date

### ISSUE THREAD

**Issue by monfresh** [travis-ci/travis-ci#2190]
Hi,

I've been trying to get my specs to run on Travis for the past few hours, but with no luck so far. I'm using capybara-webkit in a Rails 3.2.17 app, and all the tests pass locally. The only `.travis.yml` config that actually starts xvfb and runs the specs for me is this, which incidentally is not mentioned anywhere in the Travis docs. I found it on stackoverflow and coderwall.

``` yml
script: xvfb-run bundle exec rspec spec
```

None of the `before_install` commands referenced in the [Travis documentation](http://docs.travis-ci.com/user/gui-and-headless-browsers/) worked for me. I tried various combinations of this:

```
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
```

and this:

```
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
```

with and without the `script:`, and xvfb would fail to start in all cases.

With only the `script:` command, xvfb seems to start (at least it doesn't complain that it hasn't started), but once the specs start running, all the tests that use JS fail with a `Capybara::ElementNotFound` error. Setting `Capybara.default_wait_time = 30` didn't help.

Here is the repo: https://travis-ci.org/codeforamerica/ohana-web-search

Any thoughts or suggestions would be greatly appreciated. Thanks!

**Comment by moeabdol** [comment]
Thank you @monfresh this worked for me :+1:
All Javascript enabled tests passed on Travis-CI
A minor caveat though, I get this warning 

WARNING: The next major version of capybara-webkit will require at least version 5.0 of Qt. You're using version 4.8.1.

Any idea how I can eliminate this and using Qt 5 on travis. Thanks :)

**Comment by gemfarmer** [comment]
@moeabdol I am also getting this error. Did you resolve this?

**Comment by moeabdol** [comment]
@gemfarmer I still get the warning; however, all I can think of is that this is probably a minor configuration in travis.yml telling travis ci to use QT version 5 instead of the current version 4.

**Comment by gemfarmer** [comment]
@moeabdol It is interesting. I was able to install `qt5` and reinstall `capybara-webkit` with new symlinks, but Travis was still yelling at me until I updated my rails version. Go figure. Thanks for your help.
