### ISSUE TITLE
Proposal: travis-build integration testing (via Vagrant)

### ISSUE THREAD

**Issue by maxlinc** [travis-ci/travis-ci#2191]
I've got a proposal for how to test scripts generated via travis-build on realistic worker environments.  This should help for developing adding Windows support.

If you want to jump right in, I created a [gist](https://gist.github.com/maxlinc/11051223) of how the final setup might work.
### Proposal

The truth is most of this is made possible by the awesome work @mitchellh has done on vagrant.  My proposal is just a Vagrantfile that takes advantage of the new [Vagrant Cloud]() and [Boxes 2.0](https://www.vagrantup.com/blog/feature-preview-vagrant-1-5-boxes-2-0.html) features.

The way it works is by creating a Vagrantfile that defines three machines using three boxes:
- travis-ci/travis-worker-linux
- travis-ci/travis-worker-windows
- travis-ci/travis-worker-osx

These images can take advantage of the Vagrant cloud for discoverability, multi-provider support, and updates.  We can generate build scripts by running travis-build on the host machine, and then using vagrant execute the scripts on the guests for each OS.

See below for more details on the workflow.
### Benefits
- Run generated scripts in realistic travis-worker environments (on all platforms)
  - Workers environments are discoverable, updatable
  - Worker environments can be made available on multiple virtualization platforms so contributors have their choice of local VMs or cloud machines
  - Depend on images, not the travis-cookbooks/travis-images scripts, so we can "automate the second time we do it" for windows beta images
- Does not require the full travis stack - in fact you probably don't even need the full travis worker, just the necessary pieces for a particular script (e.g. rvm)

I like the continuous delivery recommendation to "automate the second time".  I think we should manually build a Windows image first, because:
- It will help the travis-cookbooks/travis-images projects discover what needs to be automated and what's _difficult_ to automate on Windows
- It will make a beta image available for travis-build and travis-worker to start testing now, even before the chef/chocolatey/whatever automation is solved
### Workflow

This will let you take the output of travis-build, and send it via vagrant (via ssh->bash for Linux, or winrm->powershell for Windows) to execute on a worker.

The details for adding and updating VMs is below.  We can build updated VMs from travis-images, and then pull them into travis-build for integration testing.
#### Add the VM the first time

``` shell
$ vagrant box add travis-ci/travis-worker-linux
==> box: Loading metadata for box 'travis-ci/travis-worker-linux'
    box: URL: https://vagrantcloud.com/travis-ci/travis-worker-linux

This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) virtualbox
2) vmware_desktop
3) rackspace
4) azure
5) hyperv

Enter your choice: 3
==> box: Adding box 'travis-ci/travis-worker-linux' (v1.0.0) for provider: rackspace
    box: Download: https://vagrantcloud.com/chef/travis-ci/travis-worker-linux/version/1/provider/rackspace.box
```

We'd probably just start off with a few providers, but if travis-images moves switches to [packer](http://www.packer.io/) at some point, then it'll be easy to create "identical machine images for multiple platforms".
#### Updating the VM

The Vagrant VMs are also updatable, so contributors to the travis-build project can be notified and get updates when new travis-worker images become available.

``` shell
vince@hashicorp: $ vagrant box update travis-ci/travis-worker-linux
==> web: Checking for updates to 'travis-ci/travis-worker-linux':
    web: Version constraints: >= 0
    web: Provider: rackspace
==> web: Updating 'travis-ci/travis-worker-linux' with provider 'rackspace' from version
==> web: '1.0.0' to '1.0.1'...
==> web: Loading metadata for box 'https://vagrantcloud.com/travis-ci/travis-worker-linux'
==> web: Adding box 'travis-ci/travis-worker-linux' (v1.0.1) for provider: virtualbox
    web: Download: https://vagrantcloud.com/travis-ci/travis-worker-linux/version/2/provider/rackspace.box
==> web: Successfully added box 'travis-ci/travis-worker-linux' (v1.0.1) for 'rackspace'!
```
#### Running tests

Vagrant lets you send to a shell.  SSH is obviously supported to run bash, but he `vagrant-next` branch has been making progress for WinRM support cmd or powershell.  I've successfully spiked using vagrant-rackspace/winrm/powershell from OSX with the `vagrant-next` branch.

So all we need to do is have travis build print a script for the desired platform, and then use Vagrant to send it to the target machine.  You can do this by putting a shell provisioner on each machine:

```
 config.vm.define "windows" do |windows|
    windows.vm.provision "shell", :inline => `travis run --print --target windows`
    # ...
end
```

But you could also just do it from the command line (which gives you more flexibility to run travis build for different projects).

```
$ vagrant ssh linux -c `travis run --print`
$ vagrant ssh windows -c `travis run --print --target windows`
$ vagrant ssh osx -c `travis run --print --target osx`
```

Alternatively, you could also have the tests delivered to the travis-worker normally.  The reason I'm a fan of just letting vagrant handle the shell is that it'll let us start testing PowerShell on Windows even before the travis-worker is fully working on Windows.  If you have a Windows machine with python installed, then you probably don't need the full travis worker to test a generated python build script.
### Next steps

If that sounds good, how can we move forward?
#### Linux images

It should be possible to create, publish, and start testing with travis-ci/travis-worker-linux images.
#### OSX images

It might be possible to create travis-worker-osx images already as well, but there are fewer virtualization choices and possible more concerns about redistribution/licensing of customized OSX images.  Although I'd like pre-built images (and the update mechanism that goes with it), it might be necessary to just spin up a vanilla OSX image and run the cookbooks :\
#### Windows images

I don't think Windows support is there yet, but there may be enough experimental Windows support for some contributors to start playing around with images.
##### Developing on Windows?

If you're running Windows locally, hyperv is probably your best bet.  Microsoft has a beta image available, but you probably can't redistribute customized travis-worker-windows image.  So an image may be possible, but not sharable....
##### Developing on something else?

If you're running something else locally, there's a few options:
- vagrant-windows is probably the most complete and secure option, but there are no public images available.  You'll need to build your own image with your own windows license.
  - You can also use Windows with Rackspace, AWS or other cloud providers if you install SSH and RSync on the Windows machines (usually via cygwin).  This is hacky, but may be less painful than buying a Windows license and your own Virtualbox images.
- I have a working spike of vagrant-rackspace using Windows/WinRM, but there isn't an official release.  The WinRM support I used is in the `vagrant-next` branch of vagrant.
  - There is a vagrant-azure provider, but it's WIP and may not be usable yet.

Thoughts?

**Comment by gggeek** [comment]
+1

**Comment by activars** [comment]
+1

**Comment by farridav** [comment]
:+1:

**Comment by bmcorser** [comment]
![holly](http://upload.wikimedia.org/wikipedia/en/0/01/HollyRed.jpg)
alright dave

**Comment by miguelamartin** [comment]
:+1:

**Comment by fpapadopou** [comment]
:+1:  Would be nice to have

**Comment by stereobooster** [comment]
Looking for the way to run Travis-CI builds in VM (using Vagrant). 
Ideally it will build standalone tool or travis CLI plugin which will be able:
 - generate `Vagrantfile`/`Cheffile` based on `.travis.yml`
 - bootup and provision VM
 - run all matrix tests inside VM. There is `travis-build`, but [wwtd](grosser/wwtd) looks simpler

Side note: there is [otto](hashicorp/otto) which partially do the same: generates `Vagrantfile` behind the scene, bootup and provision VM.

**Comment by Joshua-Anderson** [comment]
@stereobooster The travis-ci docker images used by container builds are public: https://quay.io/organization/travisci

You can also use `travis compile` to generate build scripts which can then be used with the docker containers.

**Comment by jasonrhaas** [comment]
+1 for this

**Comment by richrdkng** [comment]
+1

**Comment by BanzaiMan** [comment]
I'm closing this for now for a few reasons:

* We are adding more and more tests for `travis-build`'s build artifacts; for example, we ensure that the the resultant shell scripts are syntactically correct (https://github.com/travis-ci/travis-build/blob/4183c514869940c14fd28d27e87db594db063b2a/.travis.yml#L31-L40). This does not prevent runtime errors due to unexpected values in variables, but it is far better than we had a few years ago.
* We test our web app with Docker (https://github.com/travis-ci/travis-build/blob/4183c514869940c14fd28d27e87db594db063b2a/.travis.yml#L27) to respond to *some* payloads. (Obviously, we should do more.)
* We have extended documentation to run Docker images locally https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally
* Debug build is live (for private repos, and a handful of public ones with the feature enabled). https://docs.travis-ci.com/user/running-build-in-debug-mode/
