### ISSUE TITLE
Provide support for building a repository when an upstream repo changes

### ISSUE THREAD

**Issue by alex** [travis-ci/travis-ci#2208]
This would mean `.travis.yml` would have some section like:

``` yaml
dependencies:
  - upstream/repo
```

And then whenever something landed in `upstream/repo` a build on my repo would be triggered.

This would be very useful for verifying that new development versions don't break their dependents.

**Comment by fragsalat** [comment]
Any news here? #249 is closed and I couldn't find any news about this?

**Comment by BanzaiMan** [comment]
@fragsalat This is on the road map, but we have no updates to share at this time.

**Comment by fragsalat** [comment]
Thx for the fast response :)

Is the roadmap public?
