### ISSUE TITLE
Can't connect to localhost:25 on travis VM, even though port is listening

### ISSUE THREAD

**Issue by vmalloc** [travis-ci/travis-ci#2209]
Ran into this: https://travis-ci.org/vmalloc/mailboxer/builds/23809295 (scroll to bottom of the log). haproxy is listening on 0.0.0.0:25, but an attempt to connect to it locally fails with 'connection refused'.

I would have investigated further if I had access to one of your images, but from what I can gather it seems like iptables or something similar is running which blocks the connection attempt - I see no other reasonable explanation.

Thanks in advance.

**Comment by evilaliv3** [comment]
@roidrage is is possible that since few days port 3000 has this issue as well?

**Comment by joepvd** [comment]
@evilaliv3 Not that we are aware of. Please open a new issue with a link to the build log on travis-ci.com or .org. Thanks!
