### ISSUE TITLE
Update cmake to 2.8.12

### ISSUE THREAD

**Issue by kylog** [travis-ci/travis-ci#2212]
This will prevent time/network costly workarounds to download and build a newer version of cmake.

**Comment by sapek** [comment]
@BanzaiMan, `ppa:smspillaz/cmake-2.8.12` has cmake 2.8.12. but it is not in [white-listed sources](https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json)

**Comment by sapek** [comment]
Opened travis-ci/apt-source-whitelist#118.
