### ISSUE TITLE
How to deploy a task when try using parallel_tests to speed up on Travis?

### ISSUE THREAD

**Issue by vfa-danhnt** [travis-ci/travis-ci#2216]
I am a newbie with TravisCI.
I am trying to deploy an RoR project on TravisCI.
I tried speed up to build with parallel_test gem: .travis.yml
  ...
matrix:
- "NUM_GROUPS=2 GROUP=1"
- "NUM_GROUPS=2 GROUP=2"

script: "bundle exec parallel_test spec/ -n $NUM_GROUPS --only-group $GROUP --group-by filesize --type rspec"

When i tried to build. It's builded successfull.
But when i am trying to setup auto deploy after build successfull, it has problem.

![screen shot 2014-04-29 at 6 29 27 pm](https://cloud.githubusercontent.com/assets/7287018/2828296/91b77a8c-cf91-11e3-9f46-47e7dc858a35.png)

I would like to deploy my task after build success both sub tasks.
Have any idea for about that?
Please help me.
Thank you so much.

**Comment by cyberhck** [comment]
@BanzaiMan , do we have this feature now? I can't find that anywhere.

**Comment by elamperti** [comment]
@cyberhck you may find [build stages](https://docs.travis-ci.com/user/build-stages) useful
