### ISSUE TITLE
Something Causes ssh-add to Prompt

### ISSUE THREAD

**Issue by 0xcaff** [travis-ci/travis-ci#2248]
When running `ssh-add` on a travis-ci build, it asks for a passphrase even if there is no passphrase on the private key. Running this deployment script  on my machine (Ubuntu 14.04) works, `ssh-add` does not ask for a passphrase.

[You can see the build here](https://travis-ci.org/caffinatedmonkey/uofw/builds/24219632)

[Here is a gist with the deploy keys.](https://gist.github.com/caffinatedmonkey/26e5882ab1157194bc36)

**Comment by jsvgoncalves** [comment]
@caffinatedmonkey I'm having the exact same problem, did you get to fix it?

**Comment by caffinatedmonkey** [comment]
I ended up using HTTP Auth instead of SSH. [Here's my implementation.](https://github.com/uofw/uofw/blob/master/.travis.yml#L57)

**Comment by jsvgoncalves** [comment]
@caffinatedmonkey thanks

**Comment by marco-c** [comment]
I was using an SSH key to push to the github-pages branch of a repo. It's asking for a passphrase when using an ED25519 key, it isn't when using an RSA key.
