### ISSUE TITLE
Change mysql values - e.g. max_allowed_packet

### ISSUE THREAD

**Issue by lsolesen** [travis-ci/travis-ci#2250]
We run tests for a Drupal Panopoly Distribution on Travis. However, randomly we experience Mysql Server Gone Away errors. It is probably due to the Mysql settings being too low.

https://drupal.org/node/2231631

Is there any way to change the mysql max_allowed_packet size or other mysql settings on Travis?

**Comment by ZurabWeb** [comment]
@mattab I think you need to `sudo service mysql restart` not `reload`.
