### ISSUE TITLE
Avatars are not loaded on the website if Gravatar is blocked

### ISSUE THREAD

**Issue by devnoname120** [travis-ci/travis-ci#2255]
### Abstract

Some anti-tracking extensions like Ghostery block Gravatar.
A side effect is that avatars are not loaded on the Travis-CI website.
### Solution

There was the same issue on Github, yet they fixed it by having all avatars passing through their server (proxy).
I think it should be done the same way in Travis-CI.
### Steps to reproduce the issue:
- Launch [Mozilla Firefox](http://mozilla.org/en-US/firefox/new/)
- Install [Ghostery](https://addons.mozilla.org/en-US/firefox/addon/ghostery/)
- In the options of this add-on, enable the blocking of Gravatar
- Go to a profile page on Travis-CI website
- The avatar is broken

![Broken avatar on travis-ci.org](http://image.noelshack.com/fichiers/2014/18/1399159711-capture.png)

**Comment by apjanke** [comment]
I ran in to this myself this week using Travis on Firefox 42 with Ghostery installed. I was able to find this issue by Googling, and re-enabling Gravatar in Ghostery is not a problem for me, so I've got a workaround.

But some users may not be willing to re-enable it. And the site degrades poorly when gravatar is blocked: the substitute text for the avatar (is that just the `alt` text?) overlaps the user's displayed name, causing a readability problem. Could something be done to make this degrade more gracefully?

<img width="653" alt="screen shot 2015-12-07 at 4 57 51 pm" src="https://cloud.githubusercontent.com/assets/2618447/11641007/d2055582-9d03-11e5-8d15-973ae9b20109.png">
