### ISSUE TITLE
Github organisation does not show up in the profile view and sync does not work.

### ISSUE THREAD

**Issue by tisto** [travis-ci/travis-ci#2306]
I am owner of the "collective" organisation on github:

https://github.com/collective/

Though, the organisation does not show up properly in my profile (github username "tisto"):

https://travis-ci.org/profile/collective

Two other organisations (zopefoundation, plone) show up just fine.

When I access the profile page directly I can push the sync button:

https://travis-ci.org/profile/collective

![travis_ci_-_free_hosted_continuous_integration_platform_for_the_open_source_community_-_2014-05-13_09 18 33](https://cloud.githubusercontent.com/assets/632105/2954263/d490a65c-da6e-11e3-8a14-1540e59a4c39.png)

Though, nothing really happens and I always see the message:

"Sorry, it seems like we couldn't find any repositories you have access to on GitHub."

**Comment by tisto** [comment]
@gwicke You can work around that issue by manually setting the travis hook on your github repo. Though it would be nice if that could somehow be fixed...

**Comment by gwicke** [comment]
@tisto, this is what we are currently doing, and it works for the most part. 

The one thing that is still not working is requesting a re-run for a test. I can do so for my private repos, but not for the org ones. Others in the org who refreshed their repo list before we hit 1200 *can* re-run tests.

**Comment by ncalexan** [comment]
I'm seeing this as well.  I'm a member (with push rights to many repositories) of the Mozilla organization, but I don't see Mozilla in my Travis Profile's Organization list.  Mozilla has 1155 repositories right now.

What does "manually setting the travis hook" mean?  I am trying to retrigger a build for a PR (https://travis-ci.org/mozilla/firefox-ios/builds/52353172) that I both pushed (to my local repo) and have the rights to merge to the mozilla/firefox-ios repo.  We have configured .travis.yml in that repo.  What else can I do here?

Or am I missing some other right, or some other configuration?

**Comment by tisto** [comment]
@ncalexan To enable travis for your repo, go to the repository URL, then click "Settings" -> "Webhooks & Services", "Add Service": "Travis CI" and add your token.

**Comment by joshk** [comment]
It is recommended not to use the services page. Email support and we can look into the issue.

**Comment by tisto** [comment]
email send...thx!
