### ISSUE TITLE
PHP runtime is not yet available on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2313]
No version of PHP is available via `phpenv` on OS X workers.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/25122676

**Comment by jkuchar** [comment]
Any news here?

**Comment by kiler129** [comment]
...or some guide how to install PHP during build process only for OS X?

**Comment by Arcanemagus** [comment]
@kiler129 [Here](https://github.com/AtomLinter/linter-php/blob/v1.2.0/.travis.yml) is what I currently have setup for testing the `linter-php` Atom package. Looks like it needs a bit of touch up, but it still works well enough :wink:.

**Comment by kiler129** [comment]
@Arcanemagus I developed more complex solution after fighting with the OS X build process ;)

If any of you are interested I shared it in separate repo: https://github.com/kiler129/TravisCI-OSX-PHP

**Comment by nijel** [comment]
Just to add another approach, here is how I did it for phpMyAdmin: https://github.com/phpmyadmin/phpmyadmin/commit/9ecda4175b6c19c781cf23254da151bfa15eb81a#diff-354f30a63fb0907d4ad57269548329e3 (MariaDB installation is based on hints in #4810).

**Comment by emirb** [comment]
Any news on this? This thread is 3+ years old.

**Comment by andig** [comment]
You can use homebrew to add php to your osx builds

**Comment by Saibamen** [comment]
Status?

**Comment by andig** [comment]
Really no need for it. Homebrew is your friend.

**Comment by DrTorte** [comment]
Hello everyone,

At this time we have no plans to implement support for PHP in macOS. We don't actively support it through Homebrew either, but if it works, we have no plans or intent to prevent it from doing so.

As always, if this changes we'll be sure to announce it. Thanks everyone!
