### ISSUE TITLE
Perl runtime is not yet available on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2314]
No version of Perl is available via `perlbrew` on OS X workers.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/25122994

**Comment by zmughal** [comment]
If this does go through, it would be good to get in contact with this project that helps easily test under many versions of Perl: <https://github.com/travis-perl/helpers>.

**Comment by BanzaiMan** [comment]
Closing for now, as support based on Perlbrew is unlikely to be worked on soon.
