### ISSUE TITLE
Erlang and Elixir runtime is not yet available on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2315]
No release of Erlang is available via `kerl` on OS X workers.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/25123213

**Comment by c-rack** [comment]
Is there any foreseeable chance to support Erlang on OS X?

I tried to install `kerl` on the `before_install` step, but it seems that `kerl update releases` is invoked before the `before_install` step, so no luck with that.

**Comment by BanzaiMan** [comment]
I'm curious to know if Erlang VM behaves significantly differently on OS X from how it does on Linux.

**Comment by c-rack** [comment]
Maybe not the Erlang VM itself behaves significantly differently,
but when it comes to Erlang NIFs, the operating system does matter:
http://www.erlang.org/doc/tutorial/nif.html

And that's why testing Erlang on OS X is a good idea IMHO,
at least for projects using NIFs.
