### ISSUE TITLE
Non-Java JVM languages are not yet available on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2316]
This affects Groovy, Clojure and Scala.

**Comment by JLLeitschuh** [comment]
+1 For oraclejdk8 support on OSX. JavaFX can't do cross platform builds so I was hoping to have Travis's OSX OS build it for us

**Comment by stelfrich** [comment]
+1 for the same reasons as @JLLeitschuh!

**Comment by BanzaiMan** [comment]
For a known version of Oracle JDK, you can do something like:

```yaml
before_install:
  - "wget --no-cookies --no-check-certificate --header \"Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie\" http://download.oracle.com/otn-pub/java/jdk/8u66-b17/jdk-8u66-macosx-x64.dmg"
  - hdiutil mount jdk-8u66-macosx-x64.dmg
  - sudo installer -pkg /Volumes/JDK\ 8\ Update\ 66/JDK\ 8\ Update\ 66.pkg -target LocalSystem
```

**Comment by JLLeitschuh** [comment]
@BanzaiMan
How can you do this if you want to use a build matrix? I want to build both OSX and Linux
For Linux the java switcher works fine

**Comment by BanzaiMan** [comment]
@JLLeitschuh Check for `$TRAVIS_OS_NAME` value or the presence of the `hdiutil` command, and execute the above. It is probably easier if you put this logic in a script to execute it.

**Comment by JLLeitschuh** [comment]
@BanzaiMan Is there a way to cache the download so that it doesn't need to be required for each build??

**Comment by lbergelson** [comment]
Any timeline for resolving this?  Just making the OSX builds not explode when specifying a jvm would be a big boon because we could include them in a matrix and manually install the right jdk.   I can currently get either the linux builds in the matrix to work OR the mac ones.  It's easy enough (if slow) to install jdk8 on the mac ones, but it would be nice nice if I could still specify a jvm for the linux ones.

**Comment by gallandarakhneorg** [comment]
+1 For oraclejdk8 support on OSX.

**Comment by BanzaiMan** [comment]
@gallandarakhneorg If you need Java 8 on OS X, use a recent Xcode image.

**Comment by JLLeitschuh** [comment]
Really?! This is added now?!

**Comment by gallandarakhneorg** [comment]
It's working perfectly in my case. See my [configuration file](https://github.com/gallandarakhneorg/afc/blob/master/.travis.yml).

**Comment by jaredsburrows** [comment]
@gallandarakhneorg Thanks for posting that!

**Comment by tresf** [comment]
@gallandarakhneorg from your post, it appears `osx_image: xcode8` will fix this problem.  Should the website be updated and then this issue can be closed out?

**Comment by jaredsburrows** [comment]
Both: 
```
osx_image: 
  - xcode8
```
and
```
osx_image: xcode8
```
are both valid YAML

**Comment by JLLeitschuh** [comment]
It would be great if this could be added to the travis documentation:
Probably here:
https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version

**Comment by stephanmg** [comment]
Can one specify osx_image only for the OS osx?
Travis CI detectes otherwise for both Linux and OSX an XCode Language Project.

**Comment by gallandarakhneorg** [comment]
The configuration that does not detect Xcode for Linux is:
```
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode
```

**Comment by stephanmg** [comment]
Thanks @gallandarakhneorg.

However if I use xcode8, I still don't get Java 8.
Is this supposed?

Best

**Comment by jaredsburrows** [comment]
@stephanmg I get java8 using "xcode8":
```
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      env: ANDROID_HOME=/usr/local/opt/android-sdk
      osx_image: xcode8
```
See: https://github.com/jaredsburrows/android-glide-giphy-example/blob/master/.travis.yml#L8

Android setting Java8 for Android:
https://github.com/jaredsburrows/android-glide-giphy-example/blob/master/build.gradle#L54

**Comment by stephanmg** [comment]
Ok @jamesalmond I give this build matrix a shot,
previously I used:
```
os: 
   - linux
   - osx

osx_image: xcode8
```

But this seems wrong.

**Comment by stephanmg** [comment]
Is there any chance that the build time may be increased for our project @BanzaiMan.
My OSX build times out at ~44 min, maybe 5 more minutes would be sufficient.
