### ISSUE TITLE
Switching JDK via `jdk_switcher` is not yet available on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2317]
Not specifying `jdk` key in `.travis.yml` should be OK.

**Comment by advayDev1** [comment]
We use the following to achieve that effect: https://github.com/j2objc-contrib/j2objc-gradle/blob/master/install-osx-jdk7.sh

**Comment by rhwood** [comment]
Even if a functional jdk_switcher is not available on OS X, can we at least provide a dummy version that spits out something like: ```jdk_switcher NOT switching JDK``` followed by the JDK version that is being used?
