### ISSUE TITLE
Go runtime is not yet available on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2318]
Go is not available via `gvm`.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/25123892

**Comment by rzab** [comment]
Welp, I've managed to have GVM and Go (with clang on OSX) working on multi-os with cgo-compiled code. Apple shipped version of gcc (4.2.1 released 8 years ago) does not cut it, too old.
The line doing the trick: `test x$TRAVIS_OS_NAME = xosx && export CC=clang`. My full .travis.yml:
https://github.com/ostrost/ostent/blob/ea51939b17d4f2bbd73cf2df3049643d0baa065f/.travis.yml

**Comment by meatballhat** [comment]
`language: go` works on OSX now that we've switched to `gimme` yay

**Comment by meatballhat** [comment]
@nathany :heart: :metal:

**Comment by nathany** [comment]
Is this possible?

```
sudo: false
language: go

go:
  - 1.4.1

os:
  - linux
  - osx
```

Seems to only test on Linux.

**Comment by BanzaiMan** [comment]
Yes, it does. `sudo: false` and OS X builds don't mix at the moment.

**Comment by nathany** [comment]
I remove `sudo: false` but it still only tests on Linux.

**Comment by meatballhat** [comment]
@nathany is this for either a private repo or a public repo for which multi-os builds have already been enabled?

**Comment by nathany** [comment]
this is a private repo. I also have a public repo with multi-os builds enabled that I'd like to set this up for.

**Comment by meatballhat** [comment]
@nathany would you be able to email the private repo name (support@travis-ci.org)?  unless you're OK with pasting it here, of course.

**Comment by nathany** [comment]
will do.

**Comment by nathany** [comment]
Even just using OSX by itself isn't working for me (on a public repo that had multi-os builds enabled before). https://github.com/go-fsnotify/fsnotify/pull/60/files

**Comment by meatballhat** [comment]
Looks like the multi-os flag got lost along the way for fsnotify.  I've
just re-enabled.  Try a push? :smiley_cat:

**Comment by nathany** [comment]
Thanks. :-) It works, and it's running containers in Linux and still testing on Mac.

**Comment by meatballhat** [comment]
:scream:

**Comment by jingweno** [comment]
I tried to set up OSX build as well: https://github.com/github/hub/pull/804. But the OSX worker takes a while to start which adds up substantial time. I assume this is because the number of OSX workers is limited in beta.

**Comment by nathany** [comment]
Yah, pretty slow, esp. compared to Linux containers (`sudo: false`).

**Comment by joshk** [comment]
The Mac setup uses full VMs, which take time to provision and start. Containers are light weight and use a copy on write file system, and take next to no time to start.

**Comment by nathany** [comment]
True enough. Though Travis CI still manages to be 30 seconds slower than Circle CI for an equivalent OS X build. (I believe both are beta right now)

https://travis-ci.org/go-fsnotify/fsnotify/builds/49980370

https://circleci.com/gh/go-fsnotify/fsnotify/103
