### ISSUE TITLE
Multi-OS support status

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2320]
The following configurations are not currently supported

Mac:

1. Node.js #2311
1. Python #2312
1. PHP #2313
1. Perl #2314
1. Erlang #2315
1. Non-Java JVM languages #2316
1. Multiple Java versions #2317
1. Go #2318
1. Haskell #2319
1. Android

Linux:

1. Swift (see #4053)
1. Objective-C (currently routed to the Mac queue; might be possible with a cross-compiler)

**Comment by yuchi** [comment]
Is there any update on this? We have a lot of cross-platform code (iOS and Android) that we’d like to set automated tests for.

Installing the Android SDK on an OS X machine could take too much time and get caught by the overall timeout.

**Comment by joshk** [comment]
Hi Yuchi

Have you tried installing the SDK ondemand? Do you have a build for us to look at?

Thanks

**Comment by yuchi** [comment]
Actually not. I’ll build one ASAP and get back here with info.

**Comment by joshk** [comment]
Thank you, that would be very helpful.

**Comment by yuchi** [comment]
Ok, let’s see if this works: https://github.com/yuchi/ti-cross-ci-experiments

Before running the actual tests I execute [this setup script](https://github.com/yuchi/ti-cross-ci-experiments/blob/master/test/set_up_android.sh) which calls [embarkmobile/android-sdk-installer](https://github.com/embarkmobile/android-sdk-installer).

**Comment by yuchi** [comment]
The installer is pretty fast. Currently it hangs on launching the emulator. We’ll work on it.

Anyway, the multi-os/multi-lang environment loos promising.

**Comment by carllerche** [comment]
It would be nice to have Rust support as well!

**Comment by dham** [comment]
The blog post is still indicating that new requests for multi-OS are not being accepted, but the post appears to be from a year and a half ago. Is this still the case?

**Comment by joshk** [comment]
Multi OS is enabled by default.

I am closing this issue as we have full documentation on the feature.

**Comment by yuchi** [comment]
:tada:

**Comment by whit537** [comment]
Nice! :clap:

**Comment by dham** [comment]
Note that the online documentation at https://docs.travis-ci.com/user/multi-os/ implies that multi-os support is something which has to be explicitly activated for a repository:

"In the repository for which the multi-OS feature is enabled..."

**Comment by joshk** [comment]
Thanks for finding that @dham!

Updated!

**Comment by davidchall** [comment]
@joshk That sentence is also found here: https://docs.travis-ci.com/user/workers/os-x-infrastructure/

**Comment by plaindocs** [comment]
Thanks @davidchall !
