### ISSUE TITLE
repository not known

### ISSUE THREAD

**Issue by mikedugan** [travis-ci/travis-ci#2334]
repository not known to https://api.travis-ci.org/: neatif/neatif-app

I also tried using it with an uppercase "n", to the same result. I get this any time I try to run travis encrypt or travis pubkey. The repository exists and is already being tested on travis-ci.org

**Comment by arielkirkwood** [comment]
I found this GitHub issue while trying to resolve an issue with encrypting my Code Climate repo token. I couldn't find any other pages listing a solution for that, so apologies if this is off-topic, but one way to fix this problem is to edit the file at `.git/config`:
```
[travis]
	slug = <user/org>/<repo>
```
make sure `slug` matches the case-sensitive URL structure you see in Travis.

**Comment by BanzaiMan** [comment]
@arielkirkwood Good one. Thanks!

**Comment by jdalton** [comment]
I'm running into the same issue with 
```bash
repository not known to https://api.travis-ci.org/: lodash-archive/lodash-node
```

**Comment by riquellopes** [comment]
@arielkirkwood Thanks!

**Comment by nolanlawson** [comment]
@arielkirkwood Thank you! It would be awesome if the `travis` command let you fix that. I accidentally set the wrong slug name, and then it took me awhile to figure out how to correct it. :stuck_out_tongue:

**Comment by rightlag** [comment]
Late response, but I wanted to add it here in case anyone is having the same issue:

If you have a Travis Pro account, there is a `--pro` flag for Travis CLI that indicates to use `travis-ci.com` as the host for making requests to the API.

While I was trying to use `travis encrypt` without the `--pro` flag, I realized that it was using `travis-ci.org` as the host, thus resulting in the error:

    repository not known to https://api.travis-ci.org/: <user/org>/<repo>

**Comment by harveyslash** [comment]
It doesn't solve it for me : 
this is my repo Beatest-Edumock/magna

**Comment by harveyslash** [comment]
The issue was with the repo being registered in the .com domain instead of the .org. 
I think some indication to specify org vs com in the UI would be helpful

**Comment by hugovk** [comment]
@arielkirkwood's tip (https://github.com/travis-ci/travis-ci/issues/2334#issuecomment-72932432) fixed it for me, in that I had to delete the trailing slash from the slug:


```diff
[travis]
-    slug = <user/org>/<repo>/
+    slug = <user/org>/<repo>
```

**Comment by chrisdugne** [comment]
> @arielkirkwood Thank you! It would be awesome if the `travis` command let you fix that. I accidentally set the wrong slug name, and then it took me awhile to figure out how to correct it. 😛

actually you can update your travis slug with `-R` option:

```
travis open -R <user/org>/<repo>
```
