### ISSUE TITLE
inotify not delivering IN_DELETE or IN_DELETE_SELF when run on travis-ci

### ISSUE THREAD

**Issue by ridiculousfish** [travis-ci/travis-ci#2342]
My [tests are failing on travis-ci](https://travis-ci.org/fish-shell/fish-shell/jobs/25304252) because an inotify file descriptor watching for file deletion does not become readable. The tests pass on locally-run Linux boxes.

More details on the test: the program creates a file, creates a non-blocking inotify fd, adds a watch for the file to be deleted, then deletes the file. It then waits up to a second for the fd to become readable, indicating the filesystem event. In the failing case, the fd does not become readable, meaning that we do not receive deletion events.

Here is a [mostly-reduced test case](https://gist.github.com/ridiculousfish/a0955206c50cab4bf473). When run locally, this reports "inotify seems OK", but on travis-ci it reports that inotify is busted.

**Comment by akfullfo** [comment]
I'm also seeing this problem.  Tests that are expecting IN_MOVE_SELF work fine on base O/S (Ubuntu 14.04.1 LTS) but fail on Travis-CI -- the event never appears.  I guess as I need my project to work inside a containers I'll  see about a work-around using IN_ATTRIB and checking for inode change or file-missing on the path.  This feels like a simfs bug.

**Comment by joshk** [comment]
Closing this as it has become stale.

**Comment by purpleidea** [comment]
I'm experiencing some issues that might be caused by poorly performing, or rather non-performing inotify events when running on travis. I have many logs. Who can look into this?

**Comment by purpleidea** [comment]
Some investigation is showing that this might be related to the fact that travis probably uses NFS, and NFS doesn't offer inotify! Someone mentioned a beta container platform that might allow this to work. Any ideas? https://lists.fedorahosted.org/pipermail/cockpit-devel/2015-August/000323.html

**Comment by purpleidea** [comment]
@joshk Can you reopen please?

**Comment by floam** [comment]
I was curious so I [forked the test case repo](https://travis-ci.org/floam/travis-inotify-test). It seems to be fixed based on the Travis logs. I didn't even have to try `dict: trusty` like I first assumed.
