### ISSUE TITLE
Cannot restart MySQL

### ISSUE THREAD

**Issue by geerlingguy** [travis-ci/travis-ci#2353]
I'm using Travis CI for Ansible playbook testing, and can't figure out a way to stop/start or restart the MySQL service through Travis, either using Ansible or using a simple shell command in my travis configuration `script` section.

None of the following work:

```
service mysql restart
service mysql stop && service mysql start
/etc/init.d/mysql restart
```

Here's an example build that errored out; when I tried stopping, then starting MySQL, it timed out and errored after 10 minutes when waiting for mysql to start again.

I noticed [MySQL is pre-installed](http://docs.travis-ci.com/user/database-setup/#MySQL), but I'm not able to figure out (yet) why it won't let me restart. Is the root password/account set to 'root' for username, and '' for password, as in the default installation?

**Comment by grooverdan** [comment]
FYI: the correct method only requires the removal of the log files https://dev.mysql.com/doc/refman/5.5/en/innodb-data-log-reconfiguration.html
