### ISSUE TITLE
Mapping "The Build Environment" to Windows

### ISSUE THREAD

**Issue by maxlinc** [travis-ci/travis-ci#2379]
(Related to https://github.com/travis-ci/travis-ci/issues/2104)

I'm trying to take the current [Build Environment](http://docs.travis-ci.com/user/ci-environment/) documentation and see what is applicable on Windows. This is obviously a moving target, and my goal isn't necessarily to keep this up to date as much as it's to get an initial ideal of what does and doesn't make sense on Windows.

This might be better as a wiki or some other collaborative document, but since I didn't didn't see a wiki enabled I created [a gist](https://gist.github.com/maxlinc/d259963f0e6e7f5806e5) and this issue. The gist has the full breakdown and my thoughts.

tl;dr: here's what I think might be a MVP environment for Windows

Note: this is only for running builds. I'm not sure what software is needed for communicating with other parts of travis.
# Windows MVP
## Version control
- [x] git
- [x] mercurial
- [x] subversion

(No PR yet, but I've already got Chef working for these!)

Team Foundation Version Control may be desirable, but I don't think it should be part of the MVP.
## Compilers

I'd say just:
- [ ] Microsoft Visual Studio Express
- [ ] Go
## Networking Tools
- [ ] Latest PowerShell (for file upload/download and creating SSL certs)
- [ ] Tentatively OpenSSL
## Runtimes
- [ ] Ruby
- [ ] OpenJDK
- [ ] Python
- [ ] Node.js
- [ ] Go

I'm not sure about version switchers for Ruby, OpenJDK, or Node.js. Installing and using go tools should work, but some workarounds need to be ported for Go builds.
## Data stores

Not sure anything should be part of an MVP.
## Messaging

Ditto.
## Headless browser tools
- [ ] PhantomJS
## Environment variables

Look okay (except for HOME)
## Libraries

Tentatively:
- [ ] ImageMagick
- [ ] OpenSSL

**Comment by retep998** [comment]
Rust has an installer for Windows and is currently transitioning to using an .msi installer (rust-lang/rust#21118) so installing it should be trivial.
However many Rust projects depend on building C/C++ bits and since Rust doesn't yet support MSVC, it would likely require installing MinGW, or even a full MSYS2 environment.

**Comment by DarthGandalf** [comment]
MinGW and/or Cygwin would be good to have, not only Visual Studio

**Comment by jasonwilliams200OK** [comment]
> Compilers

* https://github.com/microsoft/clang
* https://github.com/microsoft/llvm
* MinGW
* Microsoft Visual Studio 2015 Express for Desktop + Microsoft Visual Studio 2015 Community version (full featured version for OSS projects)

> Tentatively OpenSSL

:+1: https://github.com/microsoft/openssl

> Runtimes

Perl pretty please! :smile:

**Comment by LegalizeAdulthood** [comment]
@jasonwilliams200OK AFAIK, the Community edition replaces the Express editions.

**Comment by jasonwilliams200OK** [comment]
@LegalizeAdulthood, https://www.visualstudio.com/downloads/download-visual-studio-vs (expand Visual Studio 2015 node and you will find Express for Desktop). Express versions are bit lighter than Community, as they are more focused for Desktop/Web/WindowsApps.

**Comment by retep998** [comment]
Honestly the only reason someone would have to get express instead of community is because they can't satisfy the no-enterprise rule on the community edition. The lightweight argument can be nullified by just disabling features you don't want when installing community edition.

**Comment by LegalizeAdulthood** [comment]
Community Edition includes MFC and ATL while Express does not.  This is a significant difference for C++ programmers.

**Comment by steelbrain** [comment]
Bump, would love to have travis support Windows

**Comment by LegalizeAdulthood** [comment]
FWIW, I find most people are simply using appveyor to get CI support for Windows on open source projects.  Until travis supports Windows, that is a viable alternative.

**Comment by jasonwilliams200OK** [comment]
Travis CI and AppVeyor are indeed doing great jobs all over the GitHub. If they merge into one enterprise, it will streamline many setups.

**Comment by rogersachan** [comment]
I think we should aim lower than Express at the minute and maybe consider the Visual C++ Build Tools and .NET Framework/Core (the only two Windows exclusives) since they both have command line interfaces and are much easier to start out with and target.

**Comment by LegalizeAdulthood** [comment]
The command-line tools are a good choice, but mostly what is needed here is action, not tool choosing.  For instance, this ticket was opened June, 2014 and my comment about AppVeyor was made 11 months ago.
