### ISSUE TITLE
TRAVIS_OS_NAME variable is not valued

### ISSUE THREAD

**Issue by alexander-zimmermann** [travis-ci/travis-ci#2384]
Despite the closed issue #2205, at least for me the `TRAVIS_OS_NAME` is not valued. See https://travis-ci.org/flowgrind/flowgrind/jobs/26745800

**Comment by BanzaiMan** [comment]
https://travis-ci.org/drogus/test-project-1/jobs/46730793#L79 shows this is fixed. I'm closing this optimistically. If you are still seeing problems, do let us know.

**Comment by dvarrazzo** [comment]
AFAICS `$TRAVIS_OS_NAME` is not populated for osx but it is for linux: see https://travis-ci.org/psycopg/psycopg2-wheels/builds/200624876 - look for configure_postgres.sh in the logs.

**Comment by BanzaiMan** [comment]
@dvarrazzo It should be there. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/200788134#L78 I am not sure why your job is failing, though.
