### ISSUE TITLE
Handle Ant's JUnit XML formatted output from test/spec runs

### ISSUE THREAD

**Issue by ndbroadbent** [travis-ci/travis-ci#239]
Ant's JUnit XML format is a standard output for almost every test framework, and can be read by many continuous integration systems, such as Hudson or Atlassian Bamboo:

* [ci_reporter](https://github.com/nicksieger/ci_reporter) (Ruby / Rails)
* [NodeUnit](https://github.com/caolan/nodeunit) (Node.js)
* [Jasmine](https://github.com/larrymyers/jasmine-reporters) (Javascript)
* [Clojure.test](http://richhickey.github.com/clojure/clojure.test-api.html#clojure.test.junit/with-junit-output) (Clojure)
* ['PyUnit'](http://docs.python.org/library/unittest.html) (Python)
* [SimpleTest](http://www.simpletest.org/en/overview.html#features) (PHP)

We could start by handling the **[ci_reporter](https://github.com/nicksieger/ci_reporter)** gem, since a lot of projects on Travis CI are Ruby / Rails. `ci_reporter` provides formatters for Test::Unit, RSpec and Cucumber. If we assume that some projects will be configured to use `ci_reporter`, then we could just test for the presence of the XML output at the end of the test run, and handle it if it exists.
Alternatively, we could detect the presence of a ruby test framework and inject `ci_reporter` into the project's Gemfile before running the test suite. This idea is possibly related to [the issue about generating a Gemfile](https://github.com/travis-ci/travis-ci/issues/205), since they will both automatically alter the project's environment.

This would allow us to store / notify which tests passed / failed, and include backtraces for each error, etc.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
