### ISSUE TITLE
PostGIS/GDAL installation conflicts

### ISSUE THREAD

**Issue by dracos** [travis-ci/travis-ci#2401]
Recently our repositories using PostGIS databases started failing on Travis though no/ only unrelated code had changed, e.g. https://travis-ci.org/mysociety/mapit/jobs/26853202

We eventually tracked it down to the fact that the default build environment has both pgdg and ubuntugis-stable sources, and if you e.g. try and install `python-gdal`, this will uninstall the preinstalled `postgresql-9.1-postgis-2.1` and `libgdal1` (as that package is from pgdg and based upon GDAL 1.9) in order to install `python-gdal` and `libgdal1h` (from ubuntugis-stable and based upon GDAL 1.10). The eventual simplest solution we came up with was to remove the ubuntugis-stable APT sources file, as you can see here:
https://github.com/mysociety/mapit/commit/3aeb2f0ba831fb4e7364f80c1a2ff986a1dd8159#diff-354f30a63fb0907d4ad57269548329e3R15

The builds now run successfully again, with the preinstalled PostGIS 2.1 and python-gdal installing from pgdg, using the same GDAL as the installed postgresql-9.1-postgis-2.1. Hope that's helpful information.

[Aside: ubuntugis-stable does include postgresql-9.1-postgis-2.0, but trying installing that instead still gave 2.1 errors from postgres, so it seems that it would take a reinstallation of postgres or similar to properly remove any reference of the preinstalled PostGIS 2.1 from the system.]

**Comment by m-kuhn** [comment]
For reference, that's how I switched to postgis from ubuntugis-unstable:

https://github.com/m-kuhn/QGIS/blob/2d0af644f905d6166c9173425ccfdd3c9a114501/.travis.yml#L18-L35

**Comment by mlavin** [comment]
This work around to remove `/etc/apt/sources.list.d/ubuntugis-stable-source.list` require using `sudo`. Is there a work around which works in the container based infrastructure?

**Comment by dracos** [comment]
I would try installing <a href="https://github.com/dezhin/pygdal">pygdal</a> with pip and not installing the python-gdal package at all. Haven't yet tried it myself, but am hopeful.

**Comment by mlavin** [comment]
I'm seeing this as a more general problem for any Python package which requires installing `libgdal-dev` to build. For my project I'm trying to install [`fiona`][0] in a Django project which also talks to Postgres/PostGIS. As you noted it will uninstall PostGIS because of the conflicting packages.

[0]: https://pypi.python.org/pypi/Fiona

**Comment by dracos** [comment]
Yeah :( Like I said in my comment back in 2014, I see no need for the Ubuntu PPA to be included by Travis any more as pgdg includes GDAL 1.9; perhaps a new ticket needs to be opened asking for it to be removed.

**Comment by mlavin** [comment]
Yes I'll create a new issue and setup a repository to reproduce. Sorry to hijack this old issue.

**Comment by dracos** [comment]
In case it's helpful to you, here's a PR to remove the ubuntugis-stable from the cookbook: https://github.com/travis-ci/travis-cookbooks/pull/500
