### ISSUE TITLE
Support for detecting pushes of refs/[blah] instead of just refs/heads

### ISSUE THREAD

**Issue by austenmc** [travis-ci/travis-ci#2404]
It would be great to add support for triggering builds on pushes to refs/custom-name-here/... branches instead of just supporting heads and pull requests.

Use case: I want to use github+phabricator+travis for repo, review and CI. I don't want to dirty my repo w/ pull requests. I just want to 'git push origin HEAD:refs/ci/[...]' and have Travis build that branch.

**Comment by roidrage** [comment]
I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
