### ISSUE TITLE
Add UI element for RemoveLog service

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2416]
In a job page, add "Remove Log" button. API endpoint is `/jobs/:id/log`, using the HTTP method PATCH. (See travis-ci/travis-api#122.)

![travis_ci_-_free_hosted_continuous_integration_platform_for_the_open_source_community](https://cloud.githubusercontent.com/assets/25666/3247659/8f250282-f186-11e3-9d14-d291da5ca2e0.png)

**Comment by BanzaiMan** [comment]
We shipped this.

**Comment by enumag** [comment]
@BanzaiMan Was this removed? I can't find the button anywhere.
