### ISSUE TITLE
Let me Travis-enable organization repos that I have admin priveliges in

### ISSUE THREAD

**Issue by elight** [travis-ci/travis-ci#242]
/organization/repositories [GET] gives us most of what we'll need here.  We only want repos where we have the "admin" permission.

**Comment by renaud** [comment]
+1 @stuartpb for setting memebership to public
![screen shot 2015-03-09 at 12 21 04 pm](https://cloud.githubusercontent.com/assets/75369/6554010/193889e4-c657-11e4-935c-da9cc2fba7ed.PNG)

**Comment by chfw** [comment]
travis automatically detected my repos which were transferred to an oragnisation and all its build history have been kept and transferred. Cool! and Thanks for your hard work.
