### ISSUE TITLE
GCC compiler with OSX

### ISSUE THREAD

**Issue by bchretien** [travis-ci/travis-ci#2423]
Hi,

We are in the process of testing [one of our CMake-enabled C++ projects](https://github.com/roboptim/roboptim-core) in the `osx` environment. We currently use two compilers in the `linux` environment: `gcc` and `clang`, and we would like to do the same thing in `osx`. Hence, our `.travis.yml` file contains:

``` yaml
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
```

When we check our environment variables in the log, we can indeed see:

``` text
Using worker: saucelabs-mac.worker.travis-ci.org:travis-mac_osx-11
...
$ export CXX=g++
$ export CC=gcc
...
$ gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1

Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)

Target: x86_64-apple-darwin13.1.0

Thread model: posix
...
TRAVIS_OS_NAME=osx
```

And when running `cmake` as we do for Linux (for instance when installing Eigen):

``` text
-- The C compiler identification is Clang 5.1.0
-- The CXX compiler identification is Clang 5.1.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
```

`clang` is indeed being used instead, which was confirmed by a clang-specific error we fixed recently (cf. [this g++ log file](https://travis-ci.org/roboptim/roboptim-core/jobs/27413676) vs [this clang++ log file](https://travis-ci.org/roboptim/roboptim-core/jobs/27413678) with the same `clang` error):

``` text
In file included from /Users/travis/build/roboptim/roboptim-core/include/roboptim/core/differentiable-function.hh:251:
/Users/travis/build/roboptim/roboptim-core/include/roboptim/core/differentiable-function.hxx:54:27: error: implicit conversion changes signedness: 'jacobian_t::Index' (aka 'int') to 'const unsigned int' [-Werror,-Wsign-conversion]
              (triplet_t (i, idx, it.value ()));
               ~~~~~~~~~  ^
/Users/travis/build/roboptim/roboptim-core/include/roboptim/core/differentiable-function.hxx:54:30: error: implicit conversion changes signedness: 'const jacobian_t::Index' (aka 'const int') to 'const unsigned int' [-Werror,-Wsign-conversion]
              (triplet_t (i, idx, it.value ()));
               ~~~~~~~~~     ^~~
2 errors generated.
```

Are we missing something here? Is there any extra step that needs to be taken in order to force the use of gcc?

**Comment by larsbrinkhoff** [comment]
@henrikhodne https://docs.travis-ci.com/user/osx-ci-environment/ Doesn't mention gcc-4.8.

**Comment by AraHaan** [comment]
Please install g++-6 for the projects that use C++ 14~17, besides it has some bug fixes and some performance fixes as well.
