### ISSUE TITLE
Consider installing boost libraries on OS X workers 

### ISSUE THREAD

**Issue by traversaro** [travis-ci/travis-ci#2433]
On Ubuntu workers for C++ projects that depend on a few boost libraries it easy to get the necessary boost dependencies. Using `apt-get` it is possible to install only a specific boost library (for example [boost filesystem](http://packages.ubuntu.com/search?keywords=libboost-filesystem-dev) or [boost regex](http://packages.ubuntu.com/search?keywords=libboost-regex-dev) ) with little overhead on the overall build.

On OS X `brew` only permits the installation of all the boost libraries together, resulting in the download of a 462 megabytes package.

**Comment by francesco-romano** [comment]
It seems that OS X workers have boost installed at version 1.55_02.
Is this true for every worker? Can this issue be closed?

**Comment by jaredsburrows** [comment]
+1

**Comment by solarce** [comment]
boost should definitely be present in all of our images now. If you find one without it, please make note of the `osx_image:` named involved and include a link to the relevant build, and we'll take a look.

Thanks!

**Comment by jaredsburrows** [comment]
@solarce So we can keep our existing `.travis.yml` files the same, no changes are needed?

**Comment by solarce** [comment]
You shouldn't need to make any changes, which Xcode versions are you normally using?

**Comment by jaredsburrows** [comment]
I am using: `xcode7.3`, see here: https://github.com/jaredsburrows/ios-gradle-objc-app-template/blob/master/.travis.yml#L3. 

If no changes are necessary, that's great!
