### ISSUE TITLE
The directory cache is marked as updated even when the file content is the same

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#2435]
This is related to Travis Pro (there is no build cache on .org)

I'm using the directory cache on the ``vendor`` folder to speed up the Composer installation: it will only need to update the dependencies compared to the previous build instead of having to install everything from scratch.
This works great, but the cache is stored again for each push because of a change detected in the autoloader generated by Composer. By default, it uses a random name for the class to avoid name clashes, so this was expected. However, after forcing the name suffix in composer, the file is still marked as being updated even though the content is the same. I suspect that the cache system only checks the mtime of the file, even when it is regenerated with the same content.
As I don't know how the cache system is implemented, I cannot know whether storing a new version of the cache will be more or less expensive than doing a comparison on the file content for modified files. But this should probably be evaluated as this will be a common case for PHP projects using composer.

**Comment by gonzaloserrano** [comment]
Hi guys, same issue trying to cache the composer's vendor/ directory, i tried the approach of just executing composer if the md5 of the composer.lock file has changed but without much luck actually.

**Comment by stof** [comment]
@gonzaloserrano what I ended up doing is actually putting the composer cache folder in the travis cache (``$HOME/.composer/cache``) and then using the ``--prefer-dist`` option for composer (meaning it would download archives rather than cloning the repo, and so using its cache)

**Comment by gonzaloserrano** [comment]
Interesting approach @stof, will try tomorrow. Thanks!

**Comment by gunnarlium** [comment]
You could also just delete those files as the last step:

```YAML
script:
  - rm -v ./vendor/autoload.php ./vendor/composer/!(installed.json)
```

**Comment by joshdifabio** [comment]
> @gonzaloserrano what I ended up doing is actually putting the composer cache folder in the travis cache ($HOME/.composer/cache) and then using the --prefer-dist option for composer (meaning it would download archives rather than cloning the repo, and so using its cache)

This still isn't ideal, as Composer changes the modification time of files in `$HOME/.composer/cache` whenever it copies them to `vendor`, which means Travis always packs & uploads the cache after every build even if `$HOME/.composer/cache` is cached and not `vendor`. This adds a lot of time to our Travis builds as we have some very large dependencies.

**Comment by naderman** [comment]
This is no longer an issue for Composer with the change to composer merged 3 weeks ago.

**Comment by stof** [comment]
Except that the composer version used on Travis is older than that currently

**Comment by gholts** [comment]
So theoretically... this issue will be resolved the next time Travis updates Composer on the build machines?

**Comment by Maks3w** [comment]
Actually cache still been invalidated due the package index download

**Comment by gholts** [comment]
Okay.

**Comment by BanzaiMan** [comment]
The caching utility now uses md5 checksums for file change detection.

**Comment by Maks3w** [comment]
@BanzaiMan I still see cache invalidation even when there is no changes.

https://travis-ci.org/Maks3w/FR3DLdapBundle/jobs/70739649#L114
https://travis-ci.org/Maks3w/FR3DLdapBundle/jobs/70739649#L243

The main problem now is it's not possible to know what file or files trigger the cache invalidation as before (https://travis-ci.org/Maks3w/FR3DLdapBundle/jobs/65525321#L241)

**Comment by joshdifabio** [comment]
> The caching utility now uses md5 checksums for file change detection.

Brilliant, thanks!

> The main problem now is it's not possible to know what file or files trigger the cache invalidation as before (https://travis-ci.org/Maks3w/FR3DLdapBundle/jobs/65525321#L241)

I agree that it's extremely helpful to know what has change; is there a technical reason not to display the names of the changed files?

**Comment by BanzaiMan** [comment]
The current dilemma I'm facing right now is that the output can be substantial in some cases (say, the initial maven install). So much so that it can push the log size over the 4 MB limit, resulting in a build error. For this reason, the utility is not printing any file information.

I understand that this is a problem.

Possible solutions:

1. Truncate the list of changed files to a reasonable length (for example, 20 lines or so)
1. Dump the content to a known location, and instruct the user to `cat` it
1. The combination of the above

I think I would go with the last.

**Comment by Maks3w** [comment]
1. at least display 5 files locations will give a hint about what is happening

Also may some paths can be abreviated like /home/travis/ to just HOME

**Comment by joshdifabio** [comment]
> Possible solutions:

> 1. Truncate the list of changed files to a reasonable length (for example, 20 lines or so)
> 2. Dump the content to a known location, and instruct the user to cat it
> 3. The combination of the above

> I think I would go with the last.

Sounds perfect to me :)

**Comment by BanzaiMan** [comment]
Hello there. I pushed this change, and I would like you to test. Could you add:

```yaml
cache:
  edge: true
  # rest of cache directives
```

and see if that works for you?

**Comment by Maks3w** [comment]
For me it's ok.

First run (cache cold) didn't display any file changed in the list

Second run (cache warm) display:

```
store build cache
change detected:
/home/travis/.composer/cache/repo/https---packagist.org/packages.json
/home/travis/.composer/cache/repo/https---packagist.org/p-provider-latest.json
/home/travis/.composer/cache/repo/https---packagist.org/provider-fr3d$ldap-bundle.json
```
which is ok for me

**Comment by BanzaiMan** [comment]
Thanks for testing. I'll deployed it to production.

**Comment by joshdifabio** [comment]
> Thanks for testing. I'll deployed it to production.

Brilliant, thank you!
