### ISSUE TITLE
Please consider registering the 'travis-ci' IRC bot on irc.oftc.net

### ISSUE THREAD

**Issue by isislovecruft** [travis-ci/travis-ci#2453]
The `travis-ci` IRC notification bot isn't currently registered with NickServ on the OFTC IRC network (`irc.oftc.net:66[6|9]7`). This makes it impossible to ask ChanServ to add it to the access list of a channel.

For example, if `travis-ci` were registered, then someone could do:
 `/msg ChanServ ACCESS #channel ADD travis-ci MEMBER`
for a moderated (`+mn`) channel, which would allow the bot to be autovoiced. This would allow the bot to still join the channel and deliver the notification without allowing spammers to make the channel unusable (we've been having a pretty horrible wave of trolls in the Tor development channels on OFTC).

**Comment by fpietrosanti** [comment]
@isislovecruft can you provide an example to integrate travis irc notifications?
