### ISSUE TITLE
Duplicate builds when pushing tags?

### ISSUE THREAD

**Issue by mar10** [travis-ci/travis-ci#2456]
Hi,

experimenting with a new release workflow I do a 'git push --follow-tags' to push a new release after bump. Does this trigger two build (one always failing?)
Seems both reference the same commit hash.

https://travis-ci.org/mar10/jquery-ui-contextmenu/builds

![image](https://cloud.githubusercontent.com/assets/41663/3382008/dfae20f4-fc2f-11e3-9866-b17adf18f300.png)

p.s.
My script also pushes a prerelease bump (e.g. '1.4.3-0') directly after the first push, but I pass '[ci skip]' with the message. And the commit hash of this one does not appear in the build list, so I guess that works.

**Comment by dholdaway** [comment]
Was this resolved or do you have a solution to stop it from happening

**Comment by mar10** [comment]
I think it is still pending #1532

**Comment by tommilligan** [comment]
I'd like to bump this also - I thought my configuration wasn't working properly (#7556), as my master branch & tagged commits were shown as not deploying in the master branch build logs. Turns out they were being deployed, but from the entirely separate duplicate build!

I can see that the tags and branch name are being treated as two separate triggers, but having two builds & two logs to check for one commit under one environment seems odd.

**Comment by tdmalone** [comment]
For others finding this, see the simple workaround idea posted at https://github.com/travis-ci/travis-ci/issues/1532#issuecomment-40115887 (assuming your tags are consistently named)

**Comment by llorllale** [comment]
@tdmalone that seems only relevant for people who do **not** want to build the tag?

**Comment by tdmalone** [comment]
@llorllale Yes that’s true. I thought that was
the point - that if you’re building the branch, you don’t need to build the tag as well?

I should note the regex I linked to in the comment above needs a + after the [0-9] if one wants it to work for more than single digit version numbers.

**Comment by Juanlu001** [comment]
I don't understand the reference to #1532, since I want to build *only* the tag (and not the commit), not disable the build of the tag.

**Comment by jonhoo** [comment]
I'm with @Juanlu001 here. The proposed resolution of #1532 from @BanzaiMan is https://github.com/travis-ci/travis-ci/issues/1532#issuecomment-335561271, which just says to add
```yaml
if: tag IS blank
```
to `.travis.yml`. While that *does* prevent a double-build, it will *only* build the commit on master, and *not* add build status to the tag. That seems like an unfortunate outcome. Specifically, the goal (well, my goal anyway), is that only a single build gets run, but both the tag and the commit on master that it points to are associated with the build status. And if only one can get associated with the build, then that would be the tag, not the commit on master (but note that other, non-tagged, commits to `master` should still get builds). But maybe this warrants opening up a new issue?
