### ISSUE TITLE
Document how to use encrypted api keys for github release deployment

### ISSUE THREAD

**Issue by Yogu** [travis-ci/travis-ci#2457]
There's a [documentation page for github release deployment](http://docs.travis-ci.com/user/deployment/releases/), but it does not describe how to use encrypted api keys. And there's a [documentation page about encrypting environment variables](http://docs.travis-ci.com/user/encryption-keys/). But I can't find out how to combine these two. The format given in an [old issue comment](https://github.com/travis-ci/travis-ci/issues/1648#issuecomment-38137061) does not work, it results in "401 - Bad credentials".

How to you encrypt the API key?

**Comment by a19i23** [comment]
This also worked for me. This was the only way that it did indeed work for me.
