### ISSUE TITLE
"Log is too long to be displayed" doesn't show up on Safari in OS X Yosemite

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#2458]
A customer reported that the "This log is too long to be displayed. Please reduce the verbosity of your build or download the the raw log." warning doesn't show up at the bottom of a log for them on Safari on OS X Yosemite. Same applies to Chrome on OS X Yosemite.

Given that this is still beta software, it might also be a bug in Safari/OS X Yosemite, but we should probably investigate before OS X Yosemite is released in the fall.

**Comment by roidrage** [comment]
Looks like this is now working based on https://travis-ci.org/BanzaiMan/travis_production_test/builds/28498936?

**Comment by flaminggenius** [comment]
This is still happening on windows server 2016 windows 10 desktop prints lines 2000-10000 then stops and says the error msg but the logs are empty
