### ISSUE TITLE
env values in .travis.yml should not need to be escaped

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2477]
## PROBLEM

In `.travis.yml`, the user can define environment variables, either via `env:`, or via language-specific key-value pair such as `xcode_scheme:`. Currently, the values are passed verbatim to the bash `export` statement:

```
export VAR=FOO
```

so that if the user wants the value to contain special characters such as spaces and parentheses, they need to be escaped, or they will see confusing error message that the build script has syntax error:

``` sh-session
/Users/travis/build.sh: line 159: syntax error near unexpected token `('
```

The right hand side of YAML's key-value pair statement is considered a string by default, and the value should be properly assigned to the component desired (be it environment variable via `env` directly, or via special directives such as `xcode_scheme`) without the need for escaping.
## CAVEAT

Note that there are `.travis.yml` in the wild that escaping is already done, and the change in behavior will most likely break them.

**Comment by bcipolli** [comment]
A large part of my password, which contained `&`, was just exposed by Travis-CI because of this escaping issue. I chose to make the password not viewable, but the export command contained an error (everything after `&`), and the error printed.

That sucks! Would love to see this fixed.

**Comment by andrefreitas** [comment]
+1, having problems here too
