### ISSUE TITLE
Provide PHP nightly builds

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#2480]
the PHP environment allows to use HHVM nightly builds. It would be great if PHP nightly builds could be available in a similar way. This would make it easier for libraries to test their code on new versions of PHP before the release is done (at which point it is too late to report breakage to PHP)

**Comment by euskadi31** [comment]
:+1:

**Comment by BanzaiMan** [comment]
I'm thinking that http://snaps.php.net/ is supposed to host such snapshot builds, but it is down. I opened https://bugs.php.net/bug.php?id=69042 to see if we can get any traction on this from them.

**Comment by padraic** [comment]
:+1:

**Comment by BanzaiMan** [comment]
Please, no :+1:'s. I'll have to lock this thread and/or delete comments.

**Comment by BanzaiMan** [comment]
While we figure out how feasible this is, you can add:

```
before_install:
  - pushd $HOME; git clone https://github.com/php/php-src.git; pushd php-src; ./buildconf -f; ./configure --prefix=$HOME/.phpenv/versions/7 && make && make install; phpenv global 7; popd; popd
```

You don't need the `sudo` privilege to do this. It takes 7 minutes or so on the containers, and about 10 on the standard VMs.

**Comment by joshk** [comment]
@BanzaiMan maybe we can do something similar to Travis Rubies and build a new version on each commit to php-src?

**Comment by BanzaiMan** [comment]
@joshk That's also an option. I've also asked php.net guys if they can find a suitable host, to which `php/php-src` will deploy after a successful build.

**Comment by padraic** [comment]
I added this to Mockery runs - masquerading in a separate 5.3.3 target with Composer support included. You'd also need to add openssl to compilation to support https requests (not needed by Mockery). There's a few debug echo calls just to check PHP7 is indeed the actual php binary called.

```yaml
before_install:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.3.3" ]]; then pushd $HOME; git clone https://github.com/php/php-src.git; pushd php-src; ./buildconf -f; ./configure --with-curl --prefix=$HOME/.phpenv/versions/7 && make && make install; phpenv global 7; popd; popd; php --version; echo Travis PHP Version is $TRAVIS_PHP_VERSION; wget http://getcomposer.org/composer.phar; mkdir $PWD/phar; mv composer.phar $PWD/phar/composer; chmod +x $PWD/phar/composer; export PATH=$PWD/phar:$PATH; fi
```

**Comment by BanzaiMan** [comment]
php.net has declined to host the archive. I am looking into hosting our own archive.

**Comment by datibbaw** [comment]
@BanzaiMan Btw, instead of cloning all of the project's history, it's advisable to make a shallow clone instead:

    git clone --depth 1 https://github.com/php/php-src.git

**Comment by BanzaiMan** [comment]
By the way, php-build's of `master` definition didn't seem to work: https://travis-ci.org/BanzaiMan/travis_production_test/builds/51172496#L102

Did I do something wrong?

**Comment by BanzaiMan** [comment]
@datibbaw Thanks for the suggestion. That saves about 30 seconds.

**Comment by BanzaiMan** [comment]
Paging @loicfrering: can we use php-build to download the binary archive we create (and put on S3) and install it in a directory that phpenv can find? (Otherwise, I reckon it'll be a hack on travis-build to make this happen.)

**Comment by stof** [comment]
@BanzaiMan try to build PHP without XDebug. Most errors are coming from XDebug and it is possible that it has not yet been migrated to PHP7

@derickr what are the XDebug plans for PHP7 ?

**Comment by BanzaiMan** [comment]
@stof How do you do that with php-build? The definition comes from php-build, no? https://github.com/CHH/php-build/blob/396b34f16557dadbc6761d78e8546e965f74ac9a/share/php-build/definitions/master#L3

**Comment by stof** [comment]
Well, I'm not sure that the master definition has been tried again after PHP master became the dev version of PHP 7. You probably need to remove the line you linked (until Xdebug is compatible)

**Comment by stof** [comment]
@BanzaiMan I opened an issue in the Xdebug issue tracker about the PHP 7 support. You might want to subscribe to updates on it (with the ``Monitor`` button): http://bugs.xdebug.org/view.php?id=1109

**Comment by derickr** [comment]
I'd love to get support for Xdebug for PHP 7, but it's going to be quite an effort ... weeks, if not months.

**Comment by stof** [comment]
@BanzaiMan I submitted a PR to php-build to disable Xdebug in the PHP7 build for now.

**Comment by fezfez** [comment]
Xdebug build fail because of this commit : https://github.com/php/php-src/commit/f4cfaf36e23ca47da3e352e1c60909104c059647#diff-ef5bf53d1412b50f85d125ca4fe84741

**Comment by stof** [comment]
@fezfez of course it does. This is one of the first commits of the switch to the new version of the Zend engine. This is exactly why Xdebug has a huge work to upgrade

**Comment by BanzaiMan** [comment]
All right. I've implemented the parts to deliver PHP 7 "nightly" support to production (both .com and .org). The archive is still not quite "nightly" yet (I'm working on that), but it should be pretty recent (right now, it's about an hour old, but it can drift until periodic builds are set up).

To use this, simply add:

```yaml
language: php

php:
  - 7
```

The PHP 7 archive contains PHPUnit and composer, but no extensions are added and xdebug is not available.

I'm closing this now.

**Comment by GrahamCampbell** [comment]
@BanzaiMan Would "7.0" not be better here? Would be more forwards compatable, because we will need 7.1, 7.2, etc, in the future.

**Comment by BanzaiMan** [comment]
Hmm. Good point. I suppose `nightly` is a more apt name to keep using it past the PHP 7 release.

**Comment by GrahamCampbell** [comment]
Hmmm, I'd prefer it if we just called it "7.0". That would be totally consistant. That would mean people using "7.0" would be using 7.0-dev all the way up to 7.0.0, followed by 7.0.1, etc.

**Comment by BanzaiMan** [comment]
The archive contains whatever php/php-src has when the archive is built. It is not necessarily tied to a version number. This is an exception to the rule, so consistency doesn't seem a good argument.

**Comment by GrahamCampbell** [comment]
What I was suggesting is that in the future, this could seamlessly become a way to get 7.0.x stable tags.

**Comment by GrahamCampbell** [comment]
Since that's essentially what people are wanting from this, even though that's not the way you're dealing with it under the hood for now.

**Comment by jbrooksuk** [comment]
I'm in agreement with @GrahamCampbell here. We need versioning on it.

**Comment by nikic** [comment]
I think `nightly` and `7.0` should both exist - the latter being an alias of the former for now and switched to use release builds once php 7.0 becomes stable.

Also, thanks a lot for this! Will make compatibility testing much easier :)

**Comment by BanzaiMan** [comment]
I'm leaning towards having both. `nightly` to point to the archive we build. `7` and `7.0` will be aliases to `nightly` now, but will be removed once there is an official PHP 7 release on the Travis CI images. (There will likely be a small window in which `7` points to a nightly, but it's a small price to pay for this nightly stuff.)

**Comment by BanzaiMan** [comment]
That is, the aliases will be removed, but `7.0` should continue to function.

**Comment by Danack** [comment]
Thanks for adding this. Please could you also enabled zlib in the build (--with-zlib) ? It seems to be disabled currently.

```
$ pear package
The extension 'zlib' couldn't be found.
Please make sure your version of PHP was built with 'zlib' support.
```

**Comment by BanzaiMan** [comment]
@Danack Please open a separate ticket.

**Comment by BanzaiMan** [comment]
Nightly has been documented. http://docs.travis-ci.com/user/languages/php/#PHP-nightly-builds
