### ISSUE TITLE
Don't run 'pod install' if 'Pods' folder found

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#2484]
#1202 reminded me of this.

If the 'Pods' folder is found, that generally means that the CocoaPods are vendored into the repository and 'pod install' shouldn't be run (it looks like it might even fail in that case?).

Maybe the test for whether we should automatically run 'pod install' should be 'if Podfile found but not Pods'?

**Comment by ypresto** [comment]
Our build does not run “pod install” even if there is no xcworkspace directory.
We enabled "cache: cocoapods" in .travis.yml and failed build adds cached Pods directory.
Is this problem related to this issue ticket?

Build log: https://magnum.travis-ci.com/maychannel-dev/iOS/builds/8501379
