### ISSUE TITLE
Dependent builds

### ISSUE THREAD

**Issue by dkubb** [travis-ci/travis-ci#249]
An awesome feature to have would be a way to specify project dependencies (or better yet infer them from the Gemfile/gemspec), so that when a project builds successfully, all it's dependents' (that travis knows about) are built too.

This is a feature we use in the DataMapper CI, where anytime dm-core passes, it executes a build for every other dependent gem.

**Comment by kbrock** [comment]
This reminds me a little of [automatic publishing github pages](https://evansosenko.com/posts/automatic-publishing-github-pages-travis-ci/) - the difference being that it would just trigger a build in another repo. 

Would it be possible to leverage a technique like this?

**Comment by nicolasmccurdy** [comment]
:+1: for dependent builds.

**Comment by doctorrustynelson** [comment]
+1

**Comment by BanzaiMan** [comment]
This is on our road map. If you want to be notified of progress when it happens, please subscribe, not :+1:.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
