### ISSUE TITLE
Paginate repos list on the accounts page

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#2497]
There are organizations with 1000+ repositories. When going to the accounts page the UI would download all of them at once, taking a very long time.

Can we paginate that list?

**Comment by BanzaiMan** [comment]
Search has been added.

@drogus Are we planning to add pagination?

**Comment by joshk** [comment]
@BanzaiMan what search are you referring to?

**Comment by BanzaiMan** [comment]
@joshk I meant the "Search all repositories" field. I don't think that is scoped by access, so I guess that's different.

**Comment by joshk** [comment]
Yep, this issue is about the accounts/profile page.

Going to close this as it has become stale.
