### ISSUE TITLE
Option to force uploading build artefact on GitHub Releases provider, even if it already exists

### ISSUE THREAD

**Issue by BrianAdams** [travis-ci/travis-ci#2503]
If the file being uploaded to a particular release already exists the system will skip uploading the file.  It would be nice to have an option to force re-uploading the file. This is useful in the case someone forces there checkins to move an existing tag to a new commit with the intention that the build process would then replace the old build artifacts with the updated ones.

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/deployment/releases the `overwrite` option is available.
