### ISSUE TITLE
Request: Setting to have Travis automatically cancel an old PR request on a new commit to the same PR

### ISSUE THREAD

**Issue by Fryguy** [travis-ci/travis-ci#2505]
In our repository, our tests take a LOOOONG time to run.  Many contributors create a PR, and then iteratively push commits as review happens.  On every push, Travis queues up a build for their PR.  This even happens if they force push and the commit is no longer available.  Since Travis runs the queued requests in order, it is essentially running a LOT of build that have been superceded and thus are no longer necessary.  I find myself having to manually cancel old queued up builds, just so they don't get executed, otherwise they hold up the rest of the queue for basically no reason.

So, the request is to have a setting where old requests for the same PR are canceled automatically when a new commit is detected.  I'm suggesting a setting, because there may(?) be people who want the old builds to run.  I would think this setting would help Travis on the hosting side as well, because it's that many builds it won't have to run.

**Comment by grosser** [comment]
try this :)
https://github.com/grosser/travis_dedup
(all the other discussions got closed)

**Comment by Fryguy** [comment]
@grosser Thanks!  I actually added something very similar to our team bot,  but couldn't update the other discussion.   Check it out: https://github.com/ManageIQ/miq_bot/blob/master/app/workers/travis_build_killer.rb#L19-L34

**Comment by grosser** [comment]
yours looks smarter, but stupid is good enough for me now :)
modified it to be a github webhook http://travis-dedup.herokuapp.com/github?repo=your_org/your_repo&token=YOUR_ACCESS_TOKEN&pro=true
