### ISSUE TITLE
Command exited with with 247

### ISSUE THREAD

**Issue by sbesson** [travis-ci/travis-ci#2507]
Since the last couple of weeks, a fraction of our builds are failing intermittently with the following output:

```
Using worker: worker-linux-11-2.bb.travis-ci.org:travis-linux-14

travis_fold:start:git.1
$ git clone --depth=50 --branch=auto-close git://github.com/joshmoore/openmicroscopy.git joshmoore/openmicroscopy
Cloning into 'joshmoore/openmicroscopy'...
...
testng-init:
:: Apache Ivy 2.3.0 - 20130110142753 :: http://ant.apache.org/ivy/ ::
:: loading settings :: file = /home/travis/build/joshmoore/openmicroscopy/etc/ivysettings.xml
	conflict on /home/travis/build/joshmoore/openmicroscopy/components/blitz/target/libs/test/perf4j.jar in [test]: 0.9.16 won
	conflict on /home/travis/build/joshmoore/openmicroscopy/components/blitz/target/libs/test/ice.jar in [test]: 3.4.2 won

lifecycle.test-compile:
Copying 9 files to /home/travis/build/joshmoore/openmicroscopy/components/blitz/target/test-classes
Compiling 128 source files to /home/travis/build/joshmoore/openmicroscopy/components/blitz/target/test-classes

[31;1mThe command "./components/tools/travis-build $BUILD" exited with 247.

Done. Your build exited with 1.
```

One of the main issues is that it this failure is hard to reproduce  and usually a restart of the build fixes it. How can we get more information about the origin of this failure? Or is this already reported?

/cc @joshmoore @simleo

**Comment by joshmoore** [comment]
Note: our regular 247 build issues have now turned to 137s for one branch:
 * https://github.com/openmicroscopy/openmicroscopy/pull/3374
 * https://s3.amazonaws.com/archive.travis-ci.org/jobs/48023989/log.txt
 * see also: https://github.com/travis-ci/travis-ci/issues/2882

**Comment by mtbc** [comment]
Another example at https://travis-ci.org/openmicroscopy/openmicroscopy/builds/48367116.

**Comment by mperrin** [comment]
Was there every any resolution of this issue? We have recently started encountering this problem in some of our jobs, for instance https://travis-ci.org/mperrin/poppy/jobs/76359626

**Comment by sbesson** [comment]
@mperrin: in our case, we successfully migrated to using Travis containers (https://github.com/openmicroscopy/openmicroscopy/pull/3945) and this migration was sufficient to stop the intermittent failures described in this issue. Hope this helps.
