### ISSUE TITLE
coverity addon problem with path

### ISSUE THREAD

**Issue by KonstantinKuklin** [travis-ci/travis-ci#2508]
I tried to configure travis with coverity addon(https://scan.coverity.com/travis_ci), but it didn't work for me.
To prepare C/C++ project for analyzing need to run commands, it is autoget.sh and configure with options in my case.
The problem is when I tried run configure with options contain path to folder, I got error. It is didn't find the path.
But it is working good outside the coverity addon.

Build: https://travis-ci.org/KonstantinKuklin/HandlerSocket-Plugin-for-MySQL/builds/29529828
Bug: 618 line of log
configure command work fine in 294 line with the same options.

**Comment by roidrage** [comment]
I'm closing this issue, as there haven't been any further updates on this. If this should continue to be an issue, the best folks to talk to would be the Coverity team.
