### ISSUE TITLE
GitHub Releases tag_name not well formed

### ISSUE THREAD

**Issue by gustavohenke** [travis-ci/travis-ci#2510]
I've just pushed a tag to my repo, [and the deployment to GitHub Releases](https://travis-ci.org/injoin/frontkit/builds/29566788) failed with the following strange error:

```
Error summary:
  resource: Release
  code: missing_field
  field: tag_name
  resource: Release
  code: custom
  field: tag_name
  message: tag_name is not well-formed
  resource: Release
  code: custom
  message: Published releases must have a valid tag // See: https://developer.github.com/v3/repos/releases/#create-a-release
```

It's interesting that [about a week ago](https://travis-ci.org/injoin/frontkit/builds/28750697) I were able to successfully upload release files by using almost the same deploy configuration. The only difference is that I added `all_branches: true`, as suggested in #1675.

Can anyone point me to the right direction, please?
Thanks in advance!

**Comment by BanzaiMan** [comment]
I think this is resolved.
