### ISSUE TITLE
Notifications are not sent for restarted builds that change from failed to succeeded

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#2511]
A customer noticed that when a build fails, it's restarted and then it passes, we will not send notification, because we base our logic on the last build status.

I'm not sure if this can be easily changed and what should be the most proper behaviour, but it's surely something to discuss and if we decide not to change current behaviour I think we should mention it in docs.

**Comment by zommerfelds** [comment]
Any updates on this? This bug makes us have to manually check the Travis page every time we need to rebuild.

**Comment by envygeeks** [comment]
This is still an issue.

**Comment by envygeeks** [comment]
This is still an issue
