### ISSUE TITLE
Hard to get travis to send mail to a google group

### ISSUE THREAD

**Issue by sameb** [travis-ci/travis-ci#2513]
Travis sends email from notifications@travis-ci.org, which apparently is a Google Group.  Because of that, I can't add it as a member to another google group (our project dev list).  I would like to add it as a member (that doesn't receive email) so that I can set the privileges as "only members can post".

Please consider changing the email to come from another address (e.g, noreply@travis-ci.org), or perhaps adding an option to let the user change it if you don't want to blanket change it for all repositories.  Or make notifications@ not a group.

**Comment by joshk** [comment]
Just as an update, I have changed builds@travis-ci.com (and .org) to being a user and not a user group. I don't know if this will help, but please let me know.
