### ISSUE TITLE
Can't see my github organizations

### ISSUE THREAD

**Issue by andrewhavens** [travis-ci/travis-ci#2519]
I have a few open source projects grouped under GitHub organizations. I'm trying to add Travis CI to one of the repos in one of those organizations. However, the "accounts" page only shows my personal repos, not any of my organizations.

**Comment by olivierlacan** [comment]
Just making a note here for people like me who can't figure this out: only organizations for which I have a publicized membership wills how up on Travis upon sync. 

- [Publicizing membership in a GitHub Organization](https://help.github.com/articles/publicizing-or-concealing-organization-membership/)

**Comment by joshk** [comment]
@olivierlacan publicizing the membership should not be needed, can you give me some more info on what this was needed?

**Comment by olivierlacan** [comment]
@joshk I tried repeatedly syncing to no avail. It wasn't before I publicized my membership to the org that contained the repo I wanted to start builds for that the organization appeared in the sidebar.

**Comment by joshk** [comment]
Ok, I know the issue then, and it is not really related to publicizing memberships, we need to update the scopes we ask for. I'll put that on the high priority list for this week.

Thanks a bundle

**Comment by stringertheory** [comment]
Having the same "You are not currently a member of any organization" problem here.

**Comment by kostya-ten** [comment]
update

**Comment by drogus** [comment]
If you have that problem, you may need to review permissions for third party API access on GitHub. Settings for Travis CI should be at https://github.com/settings/connections/applications/f244293c729d5066cf27

**Comment by drogus** [comment]
Another problem that could cause this is lack of proper permissions. Currently we won't show an organisation on profile page if you only have pull permission for the org.

**Comment by alastairparagas** [comment]
I encountered this same bug and fixed it by going back to my Travis CI dashboard (at travis-ci.org). I then proceeded to add a new repository under "My Repositories" and it finally populated my organizations and repos from such organizations.

**Comment by liubin** [comment]
@alastairparagas Thanks, I resolved this as above.

After create a new repo at GitHub.com and Sync it in travis-ci.org, the origanizations are listed up.

**Comment by tiandavis** [comment]
Same bug. Only worked for me by following @olivierlacan Publisizing Membership in a GitHub Organization tip: https://help.github.com/articles/publicizing-or-hiding-organization-membership/

Then [sync] in Travis-CI and boom I can see my organization's repos.

**Comment by jcoffland** [comment]
Same thing here.  I publicized my membership to orgs but I don't think it worked right away.  However, after a couple of minutes a resyncs my orgs appeared.  I did not change any permissions.  This was a new sign-up.  Publicizing memberships may not have done anything but it did begin to work shortly after that.

**Comment by clintonjnelson** [comment]
Same here. For me, publicizing/sync worked immediately... and I'm nearly positive that the Travis repos count went up by 1.

**Comment by F1LT3R** [comment]
I think I tried everything suggested above, but I am unable to see any organizations I am listed in, public or otherwise, with or without syncing.

Does anyone have any other suggestions?

**Comment by ktarplee** [comment]
I'm having the same issue.  I made my membership in the organization public but from Travis-CI perspective I am still not part of any organization.  My I suggest this issue be reopened?  Is their a newer ticket on this same issue?

**Comment by roidrage** [comment]
@ktarplee Can you check whether the organization has whitelisted Travis CI as an OAuth application? See https://github.com/blog/1941-organization-approved-applications for details.

**Comment by ktarplee** [comment]
I think these images from GitHub show that TravisCI has access but I could be wrong.

![access2_image](https://cloud.githubusercontent.com/assets/3164343/9407612/031b352c-47d9-11e5-90c8-efb8901d3dc7.jpg)

![access_image](https://cloud.githubusercontent.com/assets/3164343/9407614/0919385c-47d9-11e5-9f16-131c7ee6b647.jpg)

**Comment by BanzaiMan** [comment]
@ktarplee Are you still having problems? Is this for .org or for .com?

**Comment by ktarplee** [comment]
Yes this is still an issue.

I removed the restrictions on the third party access and still no luck. Private repos within an organization just do not show up in travis-ci.

I don't understand your question about .org or .com?

**Comment by joshk** [comment]
@ktarplee are you using travis-ci.org or travis-ci.com?

**Comment by ktarplee** [comment]
I am using travis-ci.org.  The organization I am trying to access is a non-profit university.

**Comment by joshk** [comment]
@ktarplee what is the github name of the org you can not see?

**Comment by joshk** [comment]
ok, i think i know what the issue is. The Org has no open source repos, so we are not syncing the Org yet.

**Comment by ktarplee** [comment]
AndersonUniversity

When I make my repo public it works but I want to make the repo private to use as a class project.  We might make it public eventually but initially I think it would be best to keep private.  Do I need to have at least one public repo and then the private repos will show?  Are private repos even allowed in this context?

**Comment by joshk** [comment]
If you are wanting to test a private repo you need to use travis-ci.com, only public repos can we tested on travis-ci.org.

**Comment by ktarplee** [comment]
OK.  Thanks for clarifying this for me.

**Comment by elvijsuntals** [comment]
Had a headache with this one. Takeways:

1) Make your membership public
2) Don't mix up travis-ci.**org** with travis-ci.**com**

**Comment by joshk** [comment]
Hmmm, that is odd, that shouldn't be needed.

When I am back from GitHub Universe I will look into this further.

**Comment by 100stacks** [comment]
Thanks to all for this thread...I ran into similar issues:

- For me, I am a member of a few organizations and it appears *Travis CI* third-party GitHub authorization requested *Travis CI Pro* authorization to my public organization's repository.  So, I had to deny access to Travis CI Pro.  It might be an issue of the one organization being private and the other public.
- Then follow the suggestion from @olivierlacan to make my membership public in the public organization.  GitHub defaults to private teams/membership for organizations...which is a good thing.
- Then push an update.
- If you maintain third-party authorization to *Travis CI* and *Travis CI Pro* for the public organization, it defaults to *Travis CI Pro* and your public repo won't sync, even if your build status markdown link points to the `.org` site.

BTW, thank you *Travis CI* for providing a great service to open source! :+1: 

---

![screen shot 2015-10-30 at 8 36 29 pm](https://cloud.githubusercontent.com/assets/10120600/10861162/6e5b607a-7f45-11e5-9614-999538d445cf.png)

**Comment by jeffbondlink** [comment]
This is still the case, there should be a huge banner on the .org site stating that you can see your private repo's on travis-ci.com.  But this thread was very helpful.

**Comment by jgeorgeson** [comment]
I just ran into this today. I didn't have the com/org issue, but I did have to publicize my organizational membership to get Travis to see it.

**Comment by gaieges** [comment]
Had this problem today.  Got the spinner icon to 'sync from github' that would spin endlessly.  I tried all the above to no avail, the solution was to revoke access to github from travis, and then re-login.

**Comment by berryhill** [comment]
same issue here.

**Comment by alihesari** [comment]
@drogus Your solution saved my time. It's a true answer. Thank you.

**Comment by minexew** [comment]
@elvijsuntals only after reading your comment I realized there was a difference between public repository and public membership

**Comment by jufemaiz** [comment]
Still having issues seeing my organizations when they are not made public 👎

**Comment by GaganBhat** [comment]
Ok, so my organization is public, but the repository is private. What do I do now? The organization doesn't show up in .com, and the repository doesn't show up in .org

**Comment by asmsuechan** [comment]
FYI

integration link of public repositories (travis.org): https://github.com/settings/connections/applications/f244293c729d5066cf27

integration link of private repositories (travis.com): https://github.com/settings/connections/applications/88c5b97de2dbfc50f3ac

**Comment by ChristophWenk** [comment]
So, I have tried the above mentioned solutions but none worked for me.
I want to run a build for a private repository with Travis.com. 
I am a outside collaborator for a private repository that belongs to an organization. The organization is added and accepted under Profile --> Settings --> Applications --> Authorized OAuth Apps --> Travis CI.
I think it might be related to my collaborator status because the organization is not listed as a badge on my profile as well, only under Settings --> Organizations. Could this cause problems or is that supposed to work?

**Comment by MarSoft** [comment]
@ChristophWenk, if you are *collaborator* for the repo then you are not allowed to setup webhooks for it - and hence you cannot allow Travis to do that. IIRC, only *admins* or *owners* of the repo can do that.

**Comment by Guthers** [comment]
So I had the same issue, the sync followed by a hard page refresh worked (after allowing access), bit strange that this is required however.

**Comment by earonesty** [comment]
i have this issue.   i think what happend was that my org name *changed*.   After that, I cant see any new repos.   I tried revoking-and re-authorizing travis, and it didn't help.   

github user: earonesty, organization name: atakamallc

**Comment by GBeushausen** [comment]
I also have this issue. I have an organization which i already made public and a public repository belonging to this organization. And in travis-ci.org it says i'm not a member of any organization. Of course i granted Travis access to that organization.

**Comment by nikolas7892** [comment]
+1

**Comment by chrisallenlane** [comment]
FWIW, I did the following moments ago:

- Made public my membership in my group (of which I am the owner)
- Granted Travis permissions on my repositories once again, to get out of "legacy" mode
- Informed Travis that I was part of my organization by clicking the "Review and add" link beneath the "Missing an Organization?" text on the `account/repositories` page

With that done, I still was unable to add the repository to Travis. The configuration screen would only show repositories from my personal account. It would not display repositories from my organization.

However - I then simply went back to the page at which my project's build should be available, and it worked. So, this process seems a bit buggy and confusing, but it appears to work if you massage it properly.

**Comment by Ingo-FP-Angel** [comment]
I'm also not able to see my organizations on travis-ci.org.

Username is "Ingo-FP-Angel", organizations are "WeAreFairphone" and "FP-Angels-HH", membership is public, repos are public.
Third-party access is granted to my account at https://github.com/settings/connections/applications/f244293c729d5066cf27 and also to the organizations.

Are there any other requirements that are so obvious they are not mentioned explicitly anywhere?

**Comment by kmova** [comment]
Hitting the same issue again today.  I see that Travis has access to my organization and I am the owner.

**Comment by BanzaiMan** [comment]
https://travis-ci.community/t/travis-doesnt-report-back-and-all-organization-repos-are-gone/7772/6?u=banzaiman
