### ISSUE TITLE
Move "Sync Now" button into sidebar

### ISSUE THREAD

**Issue by andrewhavens** [travis-ci/travis-ci#2520]
As mentioned in #2519, I had an issue where not all of my GitHub "Accounts" were appearing in the sidebar of the profile page. I'm guessing the cause of this was due to lack of OAuth permissions and stale data. The problem was easily solved by clicking the sync button.

However, it was not obvious to me that clicking that button would perform that action. This is a design/user experience issue that could easily be solved. The design of the "Last Synced, Sync Now" box makes it look like a search box. At first glance, I thought it was a search box, so I tried typing into it...then I read the content and realized that it was a status message. It also appears within the page of a single account. So I didn't click it because I assumed it would only refresh the repos that were in that account.

My suggestion is that the sync button is moved into the sidebar, just above the "Accounts" tab, so that it is clear that the action would apply to all of the accounts, not just the account you are viewing.

**Comment by roidrage** [comment]
We've rolled out a revamped profile page recently, where we changed the layout and look of this particular bit:

![mathias meyer - profile - travis ci 2015-07-23 18-06-05](https://cloud.githubusercontent.com/assets/5373/8855447/7f534c18-3165-11e5-8e9d-fb989b7aed7e.jpg)

Based on that, I'm closing this issue.
