### ISSUE TITLE
php.ini in hhvm environment

### ISSUE THREAD

**Issue by danmichaelo** [travis-ci/travis-ci#2523]
I'm using the one-line [from the php docs](http://docs.travis-ci.com/user/languages/php/) to set my timezone. It works great with all environments except `hhvm`. From [job 29823606](https://travis-ci.org/scriptotek/php-oai-client/jobs/29823606):

``` bash
$ echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
/home/travis/build.sh: line 201: /home/travis/.phpenv/versions/hhvm/etc/conf.d/travis.ini: No such file or directory
```

**Comment by shadowhand** [comment]
This still doesn't work with custom .ini files:

```
$ phpenv config-add .travis.php.ini
cp: cannot create regular file `/home/travis/.phpenv/versions/hhvm/etc/conf.d': No such file or directory
The command "phpenv config-add .travis.php.ini" failed and exited with 1 during .
```

**Comment by fruitl00p** [comment]
Still not working btw... ? https://travis-ci.org/fruitl00p/php-mt940/jobs/71725978 thanks!
