### ISSUE TITLE
Run apt-get update automatically

### ISSUE THREAD

**Issue by Mikaela** [travis-ci/travis-ci#2529]
I am not sure if anyone else has noticed this, but at `#travis` at freenode there have sometimes been questions with apt failing to install something with 404 errors and which was solved by adding `sudo apt-get update` to `.travis.yml` before using apt.

Could some of the following be done for future?
- Add this to FAQ.
- Run `sudo apt-get update` automatically if `sudo apt-get install` or `sudo aptitude install` or something similar is requested in `.travis-yml`.

PS. I hope that this comes to correct place. The chanel topic lists only this issue tracker in `/topic`. I also hope I didn't open a duplicate.

**Comment by dbarnett** [comment]
Dumb question: If the package database is out of date for everyone, would it not be better to periodically update the VM images instead of having every build update the package database? Or is the problem of out-of-date package databases coming from the cloud provider and not something the Travis team has any control over?

**Comment by Mikaela** [comment]
It is out of date for everyone, but updating the VMs might not help so much as it's always possible that packages are added/removed/updated in the repository and the same errors happen unless `apt-get update` is performed until the VM is updated again.

But as all builds install same packages again and again, maybe Travis could run `apt-cacher-ng` or something to have faster package downloads?

**Comment by joshk** [comment]
We are looking at providing an Apt caching instance in each zone we run in, but we don't have an ETA on this yet sorry.
