### ISSUE TITLE
Erlang cookbooks take too long to run

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2531]
Currently, we are using `kerl` to manage multiple OTP releases. `kerl` builds Erlang from source, and it can take a long time to install all 14 versions `travis-cookbooks` currently installs. (It is not clear how many builds ran on `R14B02`, say, in the last N months, and thus its usefulness.)

We can either:

1. Drop older versions
2. Consider using binary distribution from https://www.erlang-solutions.com/downloads/download-erlang-otp on the fly (which would require some work)

**Comment by tuncer** [comment]
rebar supports R13B03 or newer (see #2757).

How often and when does building Erlang from source happen?

**Comment by zkessin** [comment]
I would not be shocked to find a lot of projects are testing against R14 and 15 out of Inertia

**Comment by tuncer** [comment]
Actually, it's a feature of rebar that it works with R13B03.

**Comment by BanzaiMan** [comment]
You can now install older OTP Releases on demand. Cookbooks use binary packages, too.
