### ISSUE TITLE
Sqwiggle notifications not working

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#2537]
We have been notified that Sqwiggle notifications currently do not seem to be working.

According to our [code](https://github.com/travis-ci/travis-tasks/blob/master/lib/travis/addons/sqwiggle/task.rb#L48) as well as [Sqwiggle's docs](https://www.sqwiggle.com/docs/endpoints/messages) we should be posting a `room_id`.

According to the user who reported the issue we'd need to use a `stream_id`:

> This works: curl -X POST -d "text=test&stream_id=travis" -u cli_xxxxxxxxxxxxxx:X https://api.sqwiggle.com/messages
> This does not work: curl -X POST -d "text=test&room_id=travis" -u cli_xxxxxxxxxxxxxx:X https://api.sqwiggle.com/messages

**Comment by joshk** [comment]
Is this still an issue?

**Comment by joepvd** [comment]
Closing. See: https://github.com/travis-ci/travis-tasks/pull/66.
