### ISSUE TITLE
IRC templates break when using ${commit_message} for merge commits

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#2539]
Customer reports that using `${commit_mesage}` generally works fine, but everything after it is cut off for merge commits. I'd suspect it's related to how we handle newlines.

Template used was: `"%{commit} (%{commit_message}) by %{author}: %{message}"`.

**Comment by mykmelez** [comment]
I'm experiencing this problem over in https://github.com/mozilla/j2me.js, where our template is `"%{repository_slug} - %{commit_message} - %{result} - %{build_url}"`.

A non-merge commit is processed correctly:

> 11:09:29 AM - travis-ci: mykmelez/j2me.js - point to new name of IRC channel - passed - http://travis-ci.org/mykmelez/j2me.js/builds/50675214

But a merge commit is missing everything after the commit message:

> 11:10:54 AM - travis-ci: mozilla/j2me.js - Merge pull request #1098 from mykmelez/change-irc-channel

**Comment by joshk** [comment]
I have added support for `commit_subject`, please try this out and let us know how it works out.

**Comment by mykmelez** [comment]
> I have added support for commit_subject, please try this out and let us know how it works out.

Thanks, it works great!

>10:16:45 AM - travis-ci: mykmelez/j2me.js - use commit_subject so IRC notices are correct for merge commits - passed - http://travis-ci.org/mykmelez/j2me.js/builds/51864927
>…
>10:53:38 AM - travis-ci: mozilla/j2me.js - Merge pull request #1145 from mykmelez/use-commit-subject - passed - http://travis-ci.org/mozilla/j2me.js/builds/51869914

**Comment by joshk** [comment]
Huzzah!
