### ISSUE TITLE
Opt-out of emails link in email footer

### ISSUE THREAD

**Issue by parndt** [travis-ci/travis-ci#254]
Not everyone wants to receive email notifications from projects they contributed to, we should have an opt-out of emails from Travis link at the footer of each email.

Interestingly this would also help to comply with "unsolicited email" laws ( e.g. here in NZ we have an [Act of Parliament about this](http://www.dia.govt.nz/Services-Anti-Spam-Index#three). )

**Comment by Nerdmaster** [comment]
Commercial or not, I'm reporting every email from Travis as spam from this point forward.  This has been going on far too long to keep claiming it's "on the roadmap" or "in development".  There should be nothing all that tricky about filtering emails via a blacklist of users who are sick of the endless spam.

And I think the fact that you email people who don't want your emails with a message talking about travis pro makes it real hard to claim it's not a violation of the CAN-SPAM act.  You operate a commercial service and you send me emails related to that service.  STOP.

**Comment by joshk** [comment]
Hi @Nerdmaster 

I am sorry for the delay it has taken us to add such a feature. I can completely understand your frustration and annoyance that this is taking so long.

The team discussed the feature a couple of weeks ago and are committed to adding this. We are working on finishing some UI changes which require a raft of API changes to. Once this is completed we are looking at changing how notifications are defined, and how users can unsubscribe from emails. 

The feature itself itself is fairly complicated as it requires API changes, UI, and notification logic. 

Until this is ready I would be more than happy to talk to the team about a stop gap solution of filtering out your email from all build status emails sent. 

If this is something you would like, please email support and link to this issue.

Have a great day,

Josh

**Comment by Monkeyboy2805** [comment]
@/all This is still open???

**Comment by bogdanap** [comment]
There is now an unsubscribe link in all our outgoing emails.
