### ISSUE TITLE
'gem install' for 1.9.3 unexpectedly installs prerelease version of the gem's dependencies

### ISSUE THREAD

**Issue by doudou** [travis-ci/travis-ci#2546]
My build needs to install the 'autobuild' gem. Since I don't use bundler, I do

```
gem install autobuild
```

However, this installs the version 2.0.2.b2 of utilrb, one of autobuild's dependencies, even though I never specified I wanted prerelease version of gems. I tried various ways to disable prerelease (namely, giving --no-prerelease on the command line and in the gem: and install: fields in ~/.gemrc) but did not succeed. The gem documentation indeed says that --[no-]prerelease is only for the required gem.

I worked around it by installing utilrb manually -- which works like a charm.

I yanked the 2.0.2.b* gem versions, but it still tries to install them (a cache issue, I guess)

**Comment by BanzaiMan** [comment]
I think this was an issue with RubyGems.

With RubyGems 2.4.5: https://travis-ci.org/BanzaiMan/travis_production_test/builds/126029756
With RubyGems 2.2.2: https://travis-ci.org/BanzaiMan/travis_production_test/builds/126030858 (still fails)
