### ISSUE TITLE
Have a way to cancel a build if a newer commit happens

### ISSUE THREAD

**Issue by toolforger** [travis-ci/travis-ci#2548]
We (SymPy) have a use case that some of us tend to fire off a series of commits, never to notice that each and every of these commits causes a Travis build. Later, we tend to find that a lot of irrelevant commits have been tested but the latest and most interesting commit is still in the work queue; also, this wastes travis.org resources and we'd like to avoid that.
We're aware of [skip ci] but that does not cover the use case: we want to cancel builds that were already queued (no way to insert that [skip ci] tag into GitHub) but have become irrelevant.
We're also aware that one can always manually cancel builds, which covers the case of diligent developers but does not cover the sloppy ones who simply fire off the commits and aren't aware, don't care or are too distracted to realize that they just tied up considerable testing resources.

I toyed with making the build script check for newer commits, and fail if it found there's a newer commit. I dropped that approach for several reasons:
- Test builds become nonrepeatable (a repeat will now always fail once a newer commit happens).
- The only way to cancel a build from the script is to return a nonzero status, which will cause the test to show up as "failed" (red markers). SymPy welcomes new contributors and GSoC participants, which means we'd burden people already taxed with learning technical details with yet another one, and one that may make them panic as well.
- Also, I found it somewhat difficult to reliably detect that a newer commit on the same branch exists. This may be due to my inexperience with git, or with Travis, or with the way Travis pulls clones from the repository (the latter being something that may change without notice so I'm unsure whether this might not add maintenance load to SymPy).
- If a test should be run anyway (because maybe the user wants to see which in a series of commits caused a failure), he can't do that on Travis, not even by rescheduling the test (it will fail due to newer commits).

I'm not 100% sure what the best way to approach this request is. I can imagine different approaches:
a) Add an option to the project's Travis configuration files that specifically handles this case. Make sure that a rescheduled test does not do the check.
b) Let the projects control that from their build scripts.
b1) Provide more information to scripts: are there newer commits on the same branch (this may amount to a documentation snippet that tells people how to script that, and makes Travis CI contributors aware that they should make sure that this information isn't obscured by specifics of Travis CI's git clone/checkout machinery)? Is this a rescheduled run or the first one? (Possibly other info.)
b2) Give scripts an option to return a "cancelled without pass/fail conclusion", showing up as a grey marker just like the cancels from the web interface do.

**Comment by jakirkham** [comment]
Given https://github.com/travis-ci/travis-ci/issues/964 was closed should this or it be reopened. We would really love to have this for conda-forge and I think it would be a great help.

**Comment by BanzaiMan** [comment]
@jakirkham Sorry, but we do not have plans to implement this in the near future.
