### ISSUE TITLE
travis-ci should host a local npm mirror for node.js projects

### ISSUE THREAD

**Issue by tjwebb** [travis-ci/travis-ci#2554]
For the following reasons: 
1. it would reduce travis-ci bandwidth usages, lowering costs
2. it would reduce average time needed per test run, increasing VM availability and thus lowering costs and improving user experience.
3. For node.js projects, nondeterministic failure is often due to failures involving network connection to npm registry
4. It's the right thing to do, given that travis-ci is an automated service that increases load on the npm registry.

In sum, I think that the world is a better place with this feature than without it, and I think that Travis CI and its customers would benefit.

**Comment by avdg** [comment]
Not a real solution (as it must be done at repo level), but it can speed up builds:

Simply add this to your travis.yml file
```
sudo: false
cache:
  directories:
    - node_modules
```

This will use the container-based infrastructure to gain access to the cache feature, this with few restrictions (disallow the use of sudo, setuid and setgid executables)
See here: http://docs.travis-ci.com/user/workers/container-based-infrastructure/.

Although this is a temporal solution, I really would love a solution on infrastructure level. A good solution could speed up builds, save bandwidth, reduce resources and reduce costs without cutting too much in delivering good service (apart from maintaining the cache maybe?).

**Comment by roidrage** [comment]
I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
