### ISSUE TITLE
Chrome browser not captured for karma tests.

### ISSUE THREAD

**Issue by justinmanley** [travis-ci/travis-ci#2555]
Hi!

My last few travis-ci builds have failed because of issues related to karma tests running in Chrome.

I first received this error message ([build 30615143](https://travis-ci.org/manleyjster/Leaflet.Illustrate/builds/30615143)):
```bash
ERROR [launcher]: Cannot start Chrome
	Can not find the binary google-chrome
	Please set env variable CHROME_BIN
```
After doing some research, I added the lines 
```
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
- sudo apt-get update -qq
- sudo apt-get install -qq google-chrome-stable
```
to my `.travis.yml` file under `before_install` (thanks to [issue #2370](https://github.com/travis-ci/travis-ci/issues/2370)).

My next travis-ci build gave the error messages:
```
INFO [launcher]: Starting browser Chrome
WARN [launcher]: Chrome have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start Chrome again (1/2).
WARN [launcher]: Chrome have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start Chrome again (2/2).
WARN [launcher]: Chrome have not captured in 60000 ms, killing.
ERROR [launcher]: Chrome failed 2 times (timeout). Giving up.
```
The build log can be perused here: [https://travis-ci.org/manleyjster/Leaflet.Illustrate/builds/30615630](https://travis-ci.org/manleyjster/Leaflet.Illustrate/builds/30615630).

Any idea what's causing it?

**Comment by voronianski** [comment]
+1 the same for me

I have setup in `karma.conf.js`:

```javascript
customLaunchers: {
      Chrome_travis_ci: {
           base: 'Chrome',
           flags: ['--no-sandbox']
       }
},
...

if (process.env.TRAVIS) {
      cfg.browsers = ['Chrome_travis_ci'];
}

config.set(cfg);
```

**Comment by n1k0** [comment]
Same problem, for what it's worth.

**Comment by BanzaiMan** [comment]
Sorry, is this an issue with the tools or Travis? We are happy to spin up a debug VM for anyone who's interested in deeper investigation.

**Comment by n1k0** [comment]
> Sorry, is this an issue with the tools or Travis?

I don't have a clue. I'm just seeing startup failures with the default chromium version installed on Travis, though it could totally be misinstantiated by tooling, Karma in my case (though it works locally, so not entirely sure.)

> We are happy to spin up a debug VM for anyone who's interested in deeper investigation.

If you have a link with proper instructions how to setup it and start investigating, I could happily do that :)

**Comment by BanzaiMan** [comment]
@n1k0 For a debug VM, please email support@travis-ci.com. Thanks!

**Comment by voronianski** [comment]
@n1k0 @BanzaiMan I've managed to run my karma tests in Chrome on travis,

take a look on config - https://github.com/voronianski/soundcloud-audio.js/blob/master/karma.conf.js#L58
and `.yml` file - https://github.com/voronianski/soundcloud-audio.js/blob/master/.travis.yml#L4

This should help!

**Comment by n1k0** [comment]
@voronianski will give it a shot, thanks!

**Comment by BanzaiMan** [comment]
@voronianski Sounds like this is something we should document. Could you write a PR for https://github.com/travis-ci/docs-travis-ci-com/? Thank you!!

**Comment by voronianski** [comment]
@BanzaiMan yep I will write a PR!

@n1k0 :wink:

**Comment by joepvd** [comment]
Closing. PRs continue to be welcome at https://github.com/travis-ci/docs-travis-ci-com.

**Comment by Altiano** [comment]
@justinmanley why would we be using phantomjs instead of chrome?
I think chrome is better?
