### ISSUE TITLE
curl: (1) Protocol sftp not supported or disabled in libcurl

### ISSUE THREAD

**Issue by kleag** [travis-ci/travis-ci#2556]
Hi,

I'm trying to upload the packages generated by buy my build step to gna.org. This site accepts only password-less  sftp uploads. Unfortunately, when running:

``` bash
$  curl --ftp-create-dirs -T /home/travis/build/aymara/lima/build/lima_common-prefix/src/lima_common-build/limacommon-1.0.0-Linux.deb sftp://kleag@download.gna.org/upload/aymara-lima/
```

travis-ci produces the following error
`curl: (1) Protocol sftp not supported or disabled in libcurl`

This seems to be related to the following Debian/Ubuntu bug:
https://bugs.launchpad.net/ubuntu/+source/curl/+bug/311029

I could apply the following solution to my builds but it would be probably better to solve it at the travis-ci level while waiting for it to be solved  upstream:
http://zeroset.mnim.org/2013/03/14/sftp-support-for-curl-in-ubuntu-12-10-quantal-quetzal-and-later/

**Comment by jonycheung** [comment]
Spent some time to set up using the instructions - https://docs.travis-ci.com/user/deployment/custom/ and ran into this issue here. It would be great to just remove this or replace with an alternative.

**Comment by tfelix** [comment]
Sorry to respond to such an old topic but I also suggest to update the official docs (at best with an working alternative) as this issue is not fixed. I also followed the above mentioned documentation and ran into: 

```curl: (1) Protocol sftp not supported or disabled in libcurl```

Sadly I need to deploy via FTP or SFTP and since FTP seems impossible SFTP is the only way to go. I maybe try to install a client apk or something. But I have to test this if this would work.

**Comment by BanzaiMan** [comment]
Please try `sftp` instead.

**Comment by redtide** [comment]
> Please try `sftp` instead.

I lost an entire afternoon to setup this and in the end I come to this because you haven't updated the docs... FWIW that sucks.

**Comment by bts-ncollins** [comment]
I too have wasted 4 hours on this. Update the docs for goodness sake.
I have to deploy by SFTP so if this is the case, I can't use your service.

I want my time back.

**Comment by juana9095** [comment]
Cómo los puedo utilizar
