### ISSUE TITLE
Problem with switching default branch on GitHub

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#2562]
One of the customers reported that this steps break tests on Travis CI:

1. Create repository in github with master branch
2. Create new branch and upload to github
3. Switch the Default Branch on Github to the new branch you created
4. Delete the master branch by git push origin :master
5. Create a new branch master, and push it to github git push origin master
6. Travis Broken

I have this sitting in my todo list, but I've never got to it, nor I tried to reproduce, so I figured out it's better to paste it here.

**Comment by joepvd** [comment]
Closing issue. Please reopen if the problem would resurface.
