### ISSUE TITLE
Large build matrix tanks website performance and "cancel build" option

### ISSUE THREAD

**Issue by hamiltont** [travis-ci/travis-ci#2567]
I recently setup a non-trivial project with a very large build matrix (~115 jobs)

Loading build details completely slows down the website, and the "cancel build" option tends to only cancel about 45 jobs at a time and so must be clicked 2-3 times sequentially

I know your standard use case is more like 10-15 jobs per build, but I figured I would still report these performance difficulties in case you guys were not aware of them

**Comment by joepvd** [comment]
Closing. Please reopen a new issue if this would resurface.
