### ISSUE TITLE
Documentation says emails only happen on status change, but emails are sent every build

### ISSUE THREAD

**Issue by gsingh93** [travis-ci/travis-ci#2576]
The documentation [here](http://docs.travis-ci.com/user/notifications/#Email-notifications) says that by default emails are sent either when the build is failing or when the build status changes. I have project where the build was passing and I wasn't getting any emails. Then the build failed when the compiler was updated and I got an email. After I updated the code to comply with the new compiler, the build passed and I got an email. Now, I get an email every night saying the build passed. Not sure if this is a bug, or I'm understanding something wrong.

**Comment by gsingh93** [comment]
Any update on this?

**Comment by joshk** [comment]
Hi @gsingh93 

Could you confirm, are you just restarting old builds, or pushing new commits?

**Comment by gsingh93** [comment]
I get an email when I push a commit and a build happens, but I also get an email everyday when I don't push a commit because rust-ci is restarting old builds. I believe the current email setting doesn't distinguish between these two cases?

This is necessary when writing Rust projects currently because the language is changing and your code might break without you pushing a commit. So while CI is a useful tool, you really don't need a status update everyday, just when things break.
