### ISSUE TITLE
Feature Request: allow using environment variables and wildcards in release file names

### ISSUE THREAD

**Issue by snowch** [travis-ci/travis-ci#2577]
I have a build where the file names of the artifacts created are dynamically generated by the build script.

It would be great if you could use wildcards in the deploy.file attribute:

    script: ./myscript.sh
    deploy:
      provider: releases
      api_key:
        secure: XXXX
      file: ./myfile_*.deb
      on:
        tags: true
        all_branches: true

or, environment variables exported from the build script:

    script: ./myscript.sh
    deploy:
      provider: releases
      api_key:
        secure: XXXX
      file: ${RELEASED_PACKAGE_FILENAME}
      on:
        tags: true
        all_branches: true

**Comment by gboddin** [comment]
To this date I tried it all :

 filename*.deb
 filename_$TRAVIS_TAG_all.deb

But :

https://travis-ci.org/gboddin/kibana-4-deb/builds/73510994

Does someone knows the proper way to deal with this ??? I'm becoming insane ...

**Comment by gboddin** [comment]
Didn't see the file_glob :) Testing ...

**Comment by kikitux** [comment]
this help me too.. would be nice close this issue since is not an issue

**Comment by joepvd** [comment]
Closing.

**Comment by banks** [comment]
I see this has been closed a while but FYI I got here from googling the same issue.

Great that `file_glob:` works, but it's still not mentioned in the releases docs...

**Comment by sivakumar-kailasam** [comment]
I got here just like @banks did, this needs to make its way to the docs

**Comment by derTobsch** [comment]
same for me. Please add this to the docs.
