### ISSUE TITLE
Add API endpoint for IP subnets

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#2580]
This seems to be a frequent support request: Someone wants to open up their firewall so something can be accessed from the Travis CI workers, and needs the subnets that we use for that.

Since the subnets *could* change in the future, I think it would be a good idea to have a canonical location where these are documented. One place could be docs.travis-ci.com, but I think the API would be better, as it would be easily machine-readable (maybe both would be a good idea too).

Any thoughts on where the best place would be? And is there a reason not to do this that anyone can think of?

**Comment by pkallos** [comment]
:+1:

**Comment by henrikhodne** [comment]
The IP addresses are now documented here: https://docs.travis-ci.com/user/ip-addresses/
