### ISSUE TITLE
Status images should show the result of the last build of the default branch

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2581]
Currently, if there is a completed build from a non-default branch, that is returned instead.

I am not sure if this is the behavior most users expect.

https://twitter.com/skimbrel/status/493518114106392576

**Comment by dmcgillen** [comment]
Does this issue include the fact that, not only is the non-default branch returned when I open the main page (travis-ci.com), but Travis says that that branch IS master (until I click build history, at which point it shows that it isn't). That is really confusing.

**Comment by BanzaiMan** [comment]
@dmcgillen That feels like a separate issue to me. Could you open a new issue with relevant links (I reckon the same issue manifests on .org, so the links there would be preferred)? Thanks.

**Comment by BanzaiMan** [comment]
I believe this is the case now.
