### ISSUE TITLE
CakePHP migration to new beta env

### ISSUE THREAD

**Issue by lorenzo** [travis-ci/travis-ci#2599]
This issue is meant to track communication regarding the migration of the cakephp account to the new beta environment.

Please comment whenever you think you are ready to initiate the migration so we can fix the travis.yml file.

**Comment by roidrage** [comment]
As there haven't any further updates on this, I'm closing this issue.

**Comment by lorenzo** [comment]
Funny that we never got notification for this event when we were asked to open this ticket :P

**Comment by joshk** [comment]
I'm sorry, that is my fault.

If you could use a port other than 80 then moving to the new setup is completely possible.

Happy to help where I can.

**Comment by lorenzo** [comment]
Don't worry, we managed doing the transition with no problems already.

**Comment by joshk** [comment]
Ahhhhh, super awesome!

You all rock!
