### ISSUE TITLE
Installing dependencies for cloudfiles deploy takes ~8 minutes

### ISSUE THREAD

**Issue by matthew-brett** [travis-ci/travis-ci#2612]
I have got great use from your Rackspace deploy feature, but I have noticed that the step "Installing deploy dependencies" takes at least ~8 minutes, which seems very long.  For example, for a build here:

https://travis-ci.org/matthew-brett/markupsafe-wheels/jobs/31506679

the whole build time was 10 minutes of which the vast majority was installing the deploy dependencies.  Other longer builds can easily fit within the regulation 50 minutes, apart from the deploy step which times them out.

Is there any way of speeding up this step?

Thanks for the very useful feature.

**Comment by rgbkrk** [comment]
I'm going to see if shifting this over to using `rack` will be useful, since it's a single go binary.
