### ISSUE TITLE
perl version specifiers incorrectly parsed as floats ( - 0.20 reads as 0.2 )

### ISSUE THREAD

**Issue by kentfredric** [travis-ci/travis-ci#2615]
This looks like #2591 , except for perl, and except is still happening.

My understanding of the very scant YAML spec is YAML **doesn't** dictate that `0.20` should be read as a float, only that it is unquoted string data that is the consuming codes responsibility to interpret.

However, that appears to be not what happens here: https://travis-ci.org/SineSwiper/Dist-Zilla-TravisCI/jobs/31494088 

The code in question that triggered this uses: 

``` yaml
language: perl
perl:
   - 5.20
....
```

As you can see, is unquoted.

Most people have avoided this problem simply by quoting it, but having to quote it suggests a bug in either Travis's handling of the data, or in the YAML library itself.

Attached is an example of how Perl's YAML implementation decodes floats, noting that the way it decodes them is as a string, preserving the trailing `0`

``` perl
use strict;
use warnings;

use YAML;
use Data::Dump qw( pp );

my $YAML = <<'EOF';

---
version: 0.50
EOF

my $struct = {
  float  => { version => 0.50  },
  string => { version => '0.50' },
  yaml   => Load( $YAML ),
};

print pp($struct);
print "\n";
```

``` perl
{
  float  => { version => 0.5 },
  string => { version => "0.50" },
  yaml   => { version => "0.50" },
}
```

**Comment by kentfredric** [comment]
Q) I'm not 100% sure this is fixed yet.

There's still a bit of information leak in the "matrix" representation of these values, that suggests the parse-as-string stuff still hasn't been done.

https://travis-ci.org/Perl-Toolchain-Gang/YAML-Tiny/jobs/54724217

This build has `- 5.20` in its matrix list.

And although:

- it does use the right version of perl to test
- and tests work

The presentation of the string is wrong in the respective matrix line:

https://travis-ci.org/Perl-Toolchain-Gang/YAML-Tiny/builds/54724216

Still shows as `perl 5.2`

And subsequently, we are _still_ working around this bug by quoting the numbers.

**Comment by BanzaiMan** [comment]
@kentfredric That is a new issue, reported as #3525.
