### ISSUE TITLE
Job output is not printed in the page

### ISSUE THREAD

**Issue by angoca** [travis-ci/travis-ci#2621]
This morning everything was working fine, but this afternoon, there was something in the site, and I cannot see the output of my jobs. It looks like the CSS is wrong, or something similar.

![image](https://cloud.githubusercontent.com/assets/294317/3799339/582a0c50-1bed-11e4-9094-be0f14449740.png)

**Comment by joepvd** [comment]
Closing. Please create a new issue if this would resurface.
