### ISSUE TITLE
Watching repositories

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#2632]
There are several feature requests along the lines of "allow adding the commit author to the list of email recipients".

Instead of adding this to the .travis.yml, I think we should switch these notification settings to be user-specific. More exactly, I think we should make it so that a user can watch a repository if they wish to receive build notifications for it.

**Comment by larsbrinkhoff** [comment]
I'd like to be able to watch any public repository in my Travis CI dashboard.

**Comment by BanzaiMan** [comment]
This is now possible with the Dashboard. https://blog.travis-ci.com/2017-02-28-introducing-dashboard

**Comment by joshk** [comment]
@BanzaiMan well, you can't add any public repository to your Travis CI Dashboard, but I think it is fine to close this issue :)
