### ISSUE TITLE
Android emulator intermittently fails to start (wait_for_emulator returns `1`)

### ISSUE THREAD

**Issue by barbeau** [travis-ci/travis-ci#2634]
As suggested by the [Travis Android docs](http://docs.travis-ci.com/user/languages/android/#How-to-Create-and-Start-an-Emulator), I'm using the [`wait_for_emulator`](https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/blob/master/wait_for_emulator) script in several open-source Android projects.

I'm seeing intermittent failures (i.e., sometimes this script exits with `1`) when executing builds on Travis.  When it fails, often I can simply re-start the same build, and then it will succeed.  Failure rate seems to be around 50% over the last few weeks.  Previously, it was much lower (I'd say closer to 5%).

Here's an example of a build that failed the first two times, but succeeded on the third attempt:
https://travis-ci.org/CUTR-at-USF/OpenTripPlanner-for-Android/builds/31721255

Here's an example of a build that succeeded the first time, but failed on the second attempt - I've left it in the failed state so you can see an example of a failure:
https://travis-ci.org/CUTR-at-USF/OpenTripPlanner-for-Android/builds/31665854

The `gradlew connectedCheck` (i.e., building the project and running the tests) seems to succeed even if the `wait_for_emulator` script fails - so, the entire build is marked as a failure because the `wait_for_emulator` script returned `1`.

Given that running the emulator "isn't fully supported by Travis", is this expected behavior?

**Comment by BanzaiMan** [comment]
@barbeau Sounds like it's running out of memory. (And probably unrelated to this issue.)

Closing this now.

**Comment by spyhunter99** [comment]
I've been having a similar issue with osmdroid. We typically get a 20% chance of a false failure. Sometimes it's command shell unresponsive, other times it looks to be some strange android related thing. On pretty much very commit, someone has to monitor the build status and click restart on all on the failed jobs (build matrix) until they pass. I've verified that the failures are not code related but are avd related. I don't have this kind of problem on my local machine, even with clean (new) avds. Not sure what can be done but it's annoying

**Comment by barbeau** [comment]
@spyhunter99 Have you tried using `travis_wait`?

https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

I'm currently experimenting with this:
https://travis-ci.org/OneBusAway/onebusaway-android/builds/183263286

I haven't seen this exact issue again, but I'm having a number of other issues that are preventing Travis Android builds w/ Google APIs - more at https://github.com/travis-ci/travis-ci/issues/6122#issuecomment-263713701.  

Still trying to figure out what actually works... :(

**Comment by barbeau** [comment]
@spyhunter99 Alright, looks like I've sorted out the other issues, and I'm back to this same problem again:
https://travis-ci.org/OneBusAway/onebusaway-android/builds/183741711

Have you found a solution yet?

**Comment by spyhunter99** [comment]
@barbeau build timeouts from no output? No because I am using travis_wait

Config is here:
https://github.com/osmdroid/osmdroid/blob/master/.travis.yml

I've had a 20% probability of failure since we started it. I'm not really complaining since it's free and pretty good for free. I only have these failures with android builds. Non android projects builds just fine, reliably (well as reliable as the code is).
