### ISSUE TITLE
Add multiple jobs per repository

### ISSUE THREAD

**Issue by crunis** [travis-ci/travis-ci#2646]
In big projects, it would be useful to be able to create multiple jobs that test different parts of the project or simply that are more or less exhaustive, so we have small jobs that can run quick tests for PR feedback and other bigger jobs that can be run once a day and have a bigger code coverage. 

The ability to run test periodically has already been requested in another feature request. 

Great tool ! Keep the good work !

**Comment by stof** [comment]
@roidrage I discovered an even better way to do this thanks to an undocumented behavior of the matrix configuration: it allows to overwrite the config of build steps (even changing the VM being used). Can you tell me whether it is something which can continue to work in the future or just a side-effect of an implementation detail for which you don't want to preserve compatibility in the future ?
See the change done in https://github.com/qa-tools/qa-tools/pull/125 for the way it works, or https://github.com/Elgg/Elgg/blob/4cf881a071fa5fd73cd6a84e820413845b9a208d/.travis.yml for another usage (which is where I discovered it)

**Comment by stof** [comment]
Note that I find undocumented feature awesome. It allows to have different job configurations very easily and avoids having lots of unnecessary commands in the build output (which is the drawback of my previous workaround based on commands wrapped in environment variable checks)

**Comment by thedrow** [comment]
@stof Oh wow this is awesome.
Are you sure it's working as you expect it to?

**Comment by thedrow** [comment]
I just checked and it seems like it works.
I think we should document this.

**Comment by stof** [comment]
@thedrow yes, currently it works. However, given it is not documented, I suspect it is a side-effect of the current implementation and may not work anymore in the future. This is why I'm asking @roidrage whether the Travis team would consider making this feature official

**Comment by joshk** [comment]
I will look into this further.

This is partially expected, and not expected. The syntax is likely to change though, and it is possible we may limit this current syntax once we move to a changed syntax/api.

Thanks for updating this issue though. Please do not promote this just yet as we need to evaluate if this will be support longterm.

**Comment by stof** [comment]
@joshk I suggest reopening the issue to keep track of progress on this

**Comment by stof** [comment]
@joshk any plan to reopen this issue to track the progress ?

**Comment by joshk** [comment]
Hi @stof, I will not reopen this issue at the moment until I have had time to talk to the team and figure out where it sits in our roadmap.

**Comment by stof** [comment]
@joshk any news ?

**Comment by brunoric** [comment]
+1 for the feature (and for the workaround do not be removed in the meantime).

**Comment by pietv** [comment]
Due to the 50 minute limit on MacOSX, multiple jobs feature is very welcome!

**Comment by esmail** [comment]
@pietv, you might want to check out the ["Parallelizing your builds across virtual machines"](https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines) appraoch. According to [the docs](https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts): `There is no timeout for a build; a build will run as long as all the jobs do as long as each job does not timeout.`

**Comment by pietv** [comment]
@esmail thanks! yep, solved it along those lines: 

```
env:
  global:
    - ECM_BRANCH=develop
    - EPM_BRANCH=develop
  matrix:
    - SKIP_STACK=true
    - SKIP_PACKAGES=true
```
So no longer really a problem!

**Comment by keithy** [comment]
I don't get it, this is a no-brainer!

I have a bash script, I want to test it in a bash setup.
I also have a set of db containers, I need to test those in a docker environment.
I also have a set of php packages, I need to test those in a php environment.
etc etc.

So, I need separate test setups for each of perhaps 15 scenarios. So .travis.yml .travis.2.yml .travis.3.yml would do this perfectly. Or .travis.bash.yml .travis.php.yaml etc etc.

Hacking the matrix to acheive simple functionality seems too much work.
