### ISSUE TITLE
Using local wildcard subdomains

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#2647]
The doc explains how to register custom local domains in the hosts file through the config: http://docs.travis-ci.com/user/hosts/

But the hosts file does not support wildcard domains, which is needed to test application where you attribute a subdomain per user (well, we could as well determine all custom subdomains used by the testsuite and list them here, but this is not maintainable).

Would you consider allowing wildcards [using dnsmasq](http://www.leaseweblabs.com/2013/08/wildcard-dns-ubuntu-hosts-file-using-dnsmasq/) (or whatever else you want), or should I do such setup in my own travis.yml config at the beginning of the build ?
Note that [dnsmasq is also usable on OSX](http://passingcuriosity.com/2013/dnsmasq-dev-osx/)

**Comment by stof** [comment]
@roidrage the solution I provided previously requires the usage of sudo, making it unusable on the new docker-based infrastructure.
Would you reconsider adding support for this feature in the hosts addon ?

**Comment by allenwq** [comment]
+1 Should be a pretty useful feature. 

@stof Do you have any workaround now ?

**Comment by stof** [comment]
@allenwq I'm still using the solution I gave above. the requirement is fine for me currently, as the project needing this also needs sudo for other reasons anyway (and the new sudo-enabled stack is better than the legacy one)
