### ISSUE TITLE
[INSTALLATION GUIDE UPDATE]

### ISSUE THREAD

**Issue by DerekTBrown** [travis-ci/travis-ci#2648]
Fedora users need to install the CLI tool using sudo ("sudo gem install travis"), otherwise they will get a "command not found" error.  Any way someone could add that to the install directions?

Cheers,

Derek Brown
Fedora Ambassador

**Comment by bong0** [comment]
I also ran into this today getting this error:

```
Building native extensions.  This could take a while...
ERROR:  Error installing travis:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/user/.gem/ruby/gems/ffi-1.9.6 for inspection.
Results logged to /home/user/.gem/ruby/extensions/x86_64-linux/ffi-1.9.6/gem_make.out
```

Runing the following command fixes it.
`sudo yum install rubygem-ffi` followed by `gem install travis -v the_current_version --no-rdoc --no-ri`

Would be nice to have that in the wiki!
