### ISSUE TITLE
Support pre-installed SciPy on Python

### ISSUE THREAD

**Issue by pelegm** [travis-ci/travis-ci#2650]
Many Python packages depend on SciPy so it would be helpful to have a recent SciPy installed for each supported Python platform. It can be installed manually using a quite simple process (as I've described in #2638), but it takes about 15 minutes, and it is not easy to guess the requirements without referring to this ticket.

**Comment by cancan101** [comment]
It seems like people are using miniconda (see [here](https://gist.github.com/dan-blanchard/7045057) and [here](https://github.com/Lasagne/Lasagne/blob/master/.travis.yml)) as a workaround. This is not ideal as miniconda creates its own virtualenv.

**Comment by nirum** [comment]
Seconded, would love to see better scientific python support

**Comment by AndreaCensi** [comment]
Hi, I was wondering if the miniconda workaround is still the preferred way of installing Numpy and Scipy.

Basically if you do any kind of scientific computing using Python, you are going to use Numpy and Scipy. 
Why not have them in the default image?

Note also that it is very tricky to install them using ``pip`` from sources.

**Comment by johnyf** [comment]
Another workaround is to use `apt` and allow system-wide site-packages, as [described here](http://stackoverflow.com/a/17254588/1959808).

**Comment by Samreay** [comment]
Has there been any development on this issue? Whether it be a scientific-python distribution we can access, or is the current fix still to use work arounds?

**Comment by peterjc** [comment]
Nowadays there are pre-compiled binary wheels for NumPy and SciPy available via pip, which work nicely with TravisCI, e.g.

```
pip install --only-binary=numpy,scipy numpy scipy
```

If you leave out the ``--only-binary=numpy,scipy`` bit there is a chance pip would end up trying to compile things (and fail or take ages).

**Comment by thorade** [comment]
@peterjc When I copy&paste your pip install command I get `no such option: --only-binary` from Travis. Did I miss anything?

PS: This is my first day as Travis user & the very first line of code I wrote into the .travis.yml file was for installing scipy, leading me here...

**Comment by dstufft** [comment]
@thorade You probably need to first do ``pip install --upgrade pip setuptools wheel``.

**Comment by BanzaiMan** [comment]
Closing this now. Perhaps we can also document https://github.com/travis-ci/travis-ci/issues/2650#issuecomment-252285413.
