### ISSUE TITLE
TRAVIS_COMMIT (and COMMIT_RANGE) bug for pull requests

### ISSUE THREAD

**Issue by hamiltont** [travis-ci/travis-ci#2666]
This bug can basically be summed up as "if you're going to use the github automerge commit in `TRAVIS_COMMIT_RANGE` or `TRAVIS_COMMIT`, then you need to update these when starting each worker because the SHA of the automerge commit can change during a build". This only affects pull requests. 

I just found this bug on [this build](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/32439965). You can see where jobs suddenly all turn green, which is not normal for us at the moment. Clicking into any job below 15 will show you the git errors caused by this bug. 

Here is a detailed breakdown of what's happening: 

* Open pull request 90. This triggers build `5`, uses auto-merge commit `cd9fec6`. The `TRAVIS_COMMIT_RANGE` is `5c627b7...cd9fec6`
* During build `5`, add commits to PR 90. Github generates a new auto-merge commit `d3f5fe0`, and commit `cd9fec6` is lost forever
* Jobs on build `5` continue to run, and travis will fetch the updated auto-merge commit of `d3f5fe0`. However, `TRAVIS_COMMIT_RANGE` will still refer to the old auto-merge of `5c627b7...cd9fec6`. Attempting to use this range will cause git problems, as the clone for this worker's clone has no commit `cd9fec6`

Interestingly, the original merge commit appears to still exist on Github (proved by clicking the `Commit cd9fec6` link that Travis adds to the build description), but I don't know how long this holds true (e.g. forever, 5 days, 1 day?). 

Travis clearly already adds that specific merge commit to the build metadata, so to fix this you could either:
* have Travis get that specific commit object from github instead of the general merge commit
* Update the `TRAVIS_COMMIT` and `TRAVIS_COMMIT_RANGE` when starting each worker to ensure that they reflect the merge commit that you actually downloaded instead of the one that existed at the start of the build

In other threads I advocated for the `TRAVIS_COMMIT_RANGE` to include the github automerge commit by default. I now think that was a poor choice, because that automerge commit will never make it into the history of the project and is therefore an unreliable SHA for long-term use. A better solution would be only include the standard commits in the pull request, and leave the merge commit on FETCH_HEAD for anyone interested.

**Comment by joepvd** [comment]
Fixed with https://github.com/travis-ci/travis-core/pull/383. Closing.

**Comment by kbrock** [comment]
Thank you
