### ISSUE TITLE
Cancelled vs. errored builds

### ISSUE THREAD

**Issue by kkaefer** [travis-ci/travis-ci#2670]
Currently, Travis differentiates between (manually) cancelled and errored builds. However, they share the same color so it's difficult on the overview to distinguish the two. Changing the color (or shades of grey) of either build outcome would be nice.

**Comment by roidrage** [comment]
I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
