### ISSUE TITLE
Java: maven-surefire-plugin is running junit.extensions.RepeatedTest

### ISSUE THREAD

**Issue by schildbach** [travis-ci/travis-ci#2675]
If you look at this build log: https://api.travis-ci.org/jobs/32802336/log.txt?deansi=true

Near the bottom, it is running
`Running junit.extensions.RepeatedTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.006 sec <<< FAILURE!
initializationError(junit.extensions.RepeatedTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.Exception: Test class should have exactly one public zero-argument constructor
    at org.junit.runners.BlockJUnit4ClassRunner.validateZeroArgConstructor(BlockJUnit4ClassRunner.java:147)
    at org.junit.runners.BlockJUnit4ClassRunner.validateConstructor(BlockJUnit4ClassRunner.java:124)
`
which understandably fails. On a local Ubuntu 14.04, it doesn't do that. It only runs the tests that come from the project (com.google.bitcoin.*).

I'm using openjdk6 both on Travis and locally. This is the failed build:

https://travis-ci.org/schildbach/bitcoinj/builds/32802335

**Comment by mikehearn** [comment]
I'm seeing this too (same project). It's weird that only we seem to encounter this problem and it appears flaky. Seems SureFire sometimes identifies this internal class as being a test (presumably because it ends in the string "Test") and sometimes it doesn't.

**Comment by mikehearn** [comment]
BTW doing a "mvn clean" fixes it. Not sure what's going on there.
