### ISSUE TITLE
Heroku deploy fails via travis-ci but succeeds normally

### ISSUE THREAD

**Issue by i8ramin** [travis-ci/travis-ci#2679]
Having a hard time figuring out why my deploys are failing when triggered via travis-ci, but have no problems when deploying manually using the command line (git push production.)

The deployment seems to fail due to a Sprocket error, but no such error occurs when I deploy manually. I've included the output logs of both builds and also my project's .travis.yml file here:

https://gist.github.com/i8ramin/c4c8040082366cc628c1

Any help/info would be greatly appreciated.

**Comment by Maethorin** [comment]
Dunno if this Issue is the best place, but Im having the same problem with heroku deploy from travis-ci.

This is the first time Im trying to deploy to heroku.

My deploy works normally with git push. The deploy part of .travis.yml

    deploy:
      provider: heroku
      api_key:
        secure: pxJW+wuB3rwi+koLYDm1EYKiy7Z3UzN2rvtRsBQE4qsgSya0i07nyV... (very long line)

The lines of the deploy part of build console log in travis with the error:

    Installing deploy dependencies
    Fetching: excon-0.49.0.gem (100%)
    Successfully installed excon-0.49.0
    Fetching: multi_json-1.11.3.gem (100%)
    Successfully installed multi_json-1.11.3
    Fetching: heroku-api-0.4.2.gem (100%)
    Successfully installed heroku-api-0.4.2
    3 gems installed
    Fetching: rendezvous-0.1.2.gem (100%)
    Successfully installed rendezvous-0.1.2
    1 gem installed
    dpl.2
    Preparing deploy
    authenticated as maethorin@gmail.com
    checking for app 'pivocram'
    found app 'pivocram'
    Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
    warning: CRLF will be replaced by LF in node_modules/karma/node_modules/dom-serialize/node_modules/void-elements/.gitattributes.
    The file will have its original line endings in your working directory.
    warning: CRLF will be replaced by LF in node_modules/karma/node_modules/dom-serialize/node_modules/void-elements/.npmignore.
    The file will have its original line endings in your working directory.
    warning: CRLF will be replaced by LF in node_modules/karma/node_modules/dom-serialize/node_modules/void-elements/.travis.yml.
    The file will have its original line endings in your working directory.
    warning: CRLF will be replaced by LF in node_modules/karma/node_modules/dom-serialize/node_modules/void-elements/LICENSE.
    The file will have its original line endings in your working directory.
    warning: CRLF will be replaced by LF in node_modules/karma/node_modules/dom-serialize/node_modules/void-elements/README.md.
    The file will have its original line endings in your working directory.
    warning: CRLF will be replaced by LF in node_modules/karma/node_modules/dom-serialize/node_modules/void-elements/pre-publish.js.
    The file will have its original line endings in your working directory.
    warning: CRLF will be replaced by LF in node_modules/karma/node_modules/dom-serialize/node_modules/void-elements/test/index.js.
    The file will have its original line endings in your working directory.
    warning: CRLF will be replaced by LF in node_modules/karma/node_modules/expand-braces/node_modules/braces/node_modules/expand-range/node_modules/repeat-string/.gitattributes.
    The file will have its original line endings in your working directory.
    warning: CRLF will be replaced by LF in node_modules/karma/node_modules/expand-braces/node_modules/braces/node_modules/expand-range/node_modules/repeat-string/.jshintrc.
    The file will have its original line endings in your working directory.
    warning: CRLF will be replaced by LF in node_modules/karma/node_modules/expand-braces/node_modules/braces/node_modules/expand-range/node_modules/repeat-string/.npmignore.
    The file will have its original line endings in your working directory.
    Saved working directory and index state WIP on (no branch): 5c29a8d CSS colors and heroku deploy in Travis
    HEAD is now at 5c29a8d CSS colors and heroku deploy in Travis
    Deploying application
    creating application archive
    uploading application archive
    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>FA08442667E36817</RequestId><HostId>HKlQdM0wqeQilGs2X7E7PC0UgtHs3VTztmTaayaaY3V44qy1m49MFevd+a/WvPg41ERjAwGDFgs=</HostId></Error>triggering new deployment

After this point, the build spent 10 minutos to finish with error:

    No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
    The build has been terminated

Any ideas?

**Comment by BanzaiMan** [comment]
@Maethorin Is this still an issue for you? Whatever is ailing your deployment, I suspect it is a different one.

Please open a new issue, along with the build log URL that shows the problem.

I'm closing this now, since whatever was here before is most likely not relevant any longer.
