### ISSUE TITLE
Pushing notes should not trigger a build

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#2680]
Pushing to `ref/notes/*` seems to trigger a build currently. This looks quite weird

See https://travis-ci.org/doctrine/DoctrineBundle/builds/32889140 and https://travis-ci.org/doctrine/DoctrineBundle/requests

I know it is possible to avoid this by requiring a .travis.yml file (I just activated this flag for the repo now), but it looks confusing

**Comment by southpolesteve** [comment]
Hi! I found this issue when trying to find a way to trigger travis builds by pushing notes. It seems that what I want is explicitly not supported? Do you know of any way to make this work? To be clear, I want to have notes trigger a build on travis.
