### ISSUE TITLE
Add IBM's J9 JVM to available JVMs

### ISSUE THREAD

**Issue by headius** [travis-ci/travis-ci#2682]
We have a number of users on IBM platforms using the J9 JVM. It would be great to get J9 available as an option on Travis.

I believe it's possible to download J9 for free, but there's some account and registration hoops to jump through.

**Comment by BanzaiMan** [comment]
Sorry about dropping the ball. We can look into this for the June update.

**Comment by gtlchan** [comment]
is there anything I can do to make this happen sooner? @BanzaiMan

**Comment by BanzaiMan** [comment]
@gtlchan Thanks for the offer. The build image is created with Chef. Specifically, you can look at https://github.com/travis-ci/travis-cookbooks/tree/master/ci_environment/java and add a recipe that does the work. If you can get started, that'll be great. If not, I'll ping you and those involved to address it.

Does that sound good?

**Comment by gtlchan** [comment]
Hiro,  can we have a call to chat?




Regards,



George (G.T.) Chan
WW Quality Assurance Owner - JTC
Certified SAP Technology Consultant, SAP NetWeaver 2004-SAP Web AS for DB2


                                                                                      
                                                                                      
                                                                                      
                                                                                      
                                                                                      
                                                                                      
 Phone: 1-905-413-3325 | Phone: 1-416-716-3345                                  IBM   
 E-mail: georgec@ca.ibm.com                                                           
 Find IBM Java Team on: Twitter:                                    8200 Warden Ave   
 http://twitter.com/ibm_jtc YouTube:                            Markham, ON L6G 1C7   
 http://www.youtube.com/user/ibmjtc                                          Canada   
                                                                                      
                                                                                      
                                                                                      








From:	Hiro Asari <notifications@github.com>
To:	travis-ci/travis-ci <travis-ci@noreply.github.com>
Cc:	George T Chan/Toronto/IBM@IBMCA
Date:	04/14/2015 07:43 AM
Subject:	Re: [travis-ci] Add IBM's J9 JVM to available JVMs (#2682)



@gtlchan Thanks for the offer. The build image is created with Chef.
Specifically, you can look at
https://github.com/travis-ci/travis-cookbooks/tree/master/ci_environment/java
 and add a recipe that does the work. If you can get started, that'll be
great. If not, I'll ping you and those involved to address it.


Does that sound good?


?
Reply to this email directly or view it on GitHub.

**Comment by beikov** [comment]
Since there is still no support for the IBM JDK, I decided to try make it work myself.
The approach I would take is to put the download link into an environment variable, download the binary, install it and the run my build with it.
Would you say that this is a good approach or should I do something else?
Is this even allowed from a legal point of view? I didn't find any restrictions on this regard in the license agreement so I assume not, but I guess you already looked into that?

**Comment by candrews** [comment]
There appears to still be no way to download the IBM JDK from Travis (it's still behind a requirement to submit a form including IBM credentials), and Travis still doesn't have support for the IBM JDK included. Are there any updates from IBM or Travis on how to make progress on this issue?

Thanks!

**Comment by DanHeidinga** [comment]
The IBM JDK is now available on Docker Hub: https://hub.docker.com/_/ibmjava/
I've put together a (trivial) example that shows how to use the docker images to compile and run a Helloworld java project at: https://github.com/DanHeidinga/IBM-J9-DockerImage-For-TravisCI

Alternatively, take a look at the Docker file [1] and you can directly pull the IBM JDK from the same place the docker build is pulling from.

[1] https://github.com/ibmruntimes/ci.docker/blob/1f0549ef043eb91ce252dfdd4355cfc890f2ab84/ibmjava/8-sdk/x86_64/ubuntu/Dockerfile

**Comment by headius** [comment]
@DanHeidinga 💯  Super great! Now if I could get a build on OS X I could do day-to-day testing on J9 :-)

**Comment by DanHeidinga** [comment]
You're the second person in as many days to mention that....

**Comment by headius** [comment]
@DanHeidinga I added J9 to invokebinder here and it is looking good in Travis:

https://github.com/headius/invokebinder/commit/bce738d8236e720a6904a0fbd247f6d80154fcde
https://travis-ci.org/headius/invokebinder/jobs/163221569

Tried to get jnr-* in there but I need an image with make etc.

For my pure-Java projects this approach works for now, but I hope Travis spins a new image soon that includes your J9 image. Thank you!

**Comment by headius** [comment]
I am a docker newb but I have a question: would it make sense to take the Travis image, add ibmjava:8-sdk, and use the resulting image? I have no idea how docker handles caching and overlap...obviously fetching a full travis + J9 image every time would not fly.

**Comment by chandrams** [comment]
We will be adding official support for IBM Java on Travis. Link mentioned above https://github.com/travis-ci/travis-cookbooks/tree/master/ci_environment/java does not exist now. Found this cookbook - https://github.com/travis-ci/travis-cookbooks/tree/master/cookbooks/travis_java, is this the right location to add the recipe?

**Comment by chandrams** [comment]
@BanzaiMan - Do you have any inputs to my above comment? Thanks.

**Comment by BanzaiMan** [comment]
@chandrams Hello. Could you send email to support@travis-ci.com to discuss this further? Thank you!

**Comment by chtompki** [comment]
@BanzaiMan - Speaking for the Apache Commons Project's community, we have definite interest in lending assistance in this effort if needed. We're interested in both ibmjava 1.8 and ibmjava 1.9, and with the [ibmjava Dockerfile](https://github.com/ibmruntimes/ci.docker/blob/e02f7b4f675d11cf0684053503626da8e2275c65/ibmjava/8/sdk/x86_64/ubuntu/Dockerfile), there seem to be mechanics to avoid the authentication problems for the download.

That said, that doesn't address the concern about disk space utilization. So, let me know if I can help out, or if you guys have decided to forgo the implementation.

Cheers.

**Comment by chandrams** [comment]
@chtompki - We are working on making IBM Java8 and IBM Java9 available on Travis CI, will be creating a pull request soon. Thanks.

**Comment by ameyjadiye** [comment]
Hi @chandrams , were you able to solve Ibm java8 issue, I have solved it at some extent and able to download ibm sdk via ```wget``` however facing some issue while installing it in travis

raised issue here https://github.com/travis-ci/travis-ci/issues/8186, see if you can solve it.

**Comment by chandrams** [comment]
@ameyjadiye - I have created a PR to install IBM Java8 & 9, awaiting review from Travis CI

@BanzaiMan - Can you get someone to review this. Thanks.

**Comment by ameyjadiye** [comment]
Awesome! Thanks @chandrams , linking your PR here for reference.

https://github.com/travis-ci/travis-cookbooks/pull/874

**Comment by marschall** [comment]
J9 is now open source https://adoptopenjdk.net/releases.html?variant=openjdk9-openj9

**Comment by bogdanap** [comment]
IBM Java8 is now available for testing for `sudo: required` builds using `group: edge` and `jdk: ibmjava8`.
Assuming everything works as expected, it will be included in our next Trusty stable image update.

**Comment by chandrams** [comment]
Thanks @bogdanap for merging the changes

**Comment by chandrams** [comment]
Tested it here using the matrix it works fine - https://travis-ci.org/chandrams/myproj/builds/286945151

I have included the recipe for making IBM Java8 available, have removed the recipe for IBM Java9 will add it once we have a latest build

**Comment by chandrams** [comment]
@bogdanap, I would like to update the Travis Docs as well, is this the docs repo that needs to be updated?
https://github.com/travis-ci/docs-travis-ci-com

**Comment by mprins** [comment]
It seems a though the jdk_switcher is not setting JAVA_HOME properly at the moment for IBM java, see for example: https://travis-ci.org/mprins/super-duper-waddle/jobs/339047870#L423 (GH project: https://github.com/mprins/super-duper-waddle) 

@chandrams I noticed that your build lists `/usr/lib/jvm/java-8-ibm-amd64` as JAVA_HOME while travis sets `/usr/lib/jvm/java-8-ibm`

**Comment by mprins** [comment]
I tried listing the `/usr/lib/jvm` directory, but the ibm jvm seems to be missing (see: https://travis-ci.org/mprins/super-duper-waddle/builds/339093167#L455)

**Comment by mprins** [comment]
reading https://github.com/travis-ci/packer-templates/pull/527 I realize imb java is not actually available atm

**Comment by chandrams** [comment]
@mprins - Yes, it is still not included in the travis trusty image

**Comment by Pr0methean** [comment]
This should be more feasible now that the AdoptOpenJDK builds of OpenJ9 are available.
