### ISSUE TITLE
Travis not properly showing some colored output

### ISSUE THREAD

**Issue by hamiltont** [travis-ci/travis-ci#2692]
When I run [this job](https://travis-ci.org/hamiltont/FrameworkBenchmarks/jobs/33214793) (using this [color_demo.py](https://gist.github.com/hamiltont/9d0bf2ab3a716a31d642)), I see this on Travis-CI: 

![color on travis](http://i.imgur.com/LuYRMaK.png)

However, on my local console I see this: 

![color on console](http://i.imgur.com/Zr69jHO.png)

Is this expected behavior? Note that not only does the background get cleared to black, but the foreground color as well.

**Comment by vanrein** [comment]
My build script makes good use of colours in its output.  Just ANSI colour codes.  GitLab likes them, but Travis CI does not.  Can you tell me how to enable colour output from scripts?
