### ISSUE TITLE
MySQL fails with use of LOAD

### ISSUE THREAD

**Issue by quasiben** [travis-ci/travis-ci#2693]
I'm trying to test out MySQL's built-in LOAD csv functionality: https://travis-ci.org/quasiben/TravisTesting/builds/33241563#L252 

It appears that either `local-infile` is set to 0 somewhere or it has been properly enabled.  I tried modifying `/etc/mysql/my.cnf` but that was met with a permission denied: https://travis-ci.org/quasiben/TravisTesting/builds/33245229#L200

Perhaps this is knowingly disabled for security purposes

**Comment by aepyornis** [comment]
In case anyone else encounters this problem while working on a rails or ruby project, the only way I could get travis to pass a test that calls  "LOAD DATA LOCAL INFILE" was to change mysql2's configuration by adding this line to database.yml:

``` yml
local_infile: true
```
