### ISSUE TITLE
Android: Cannot override the default Gradle task trigger

### ISSUE THREAD

**Issue by martinrevert** [travis-ci/travis-ci#2697]
By default, Travis trigger './gradlew build connectedCheck' which is fine if you already have configured tests, but sometimes, on early stages of Android projects you only need to fire an "assemble" Gradle command to check if the basics builds ok. 
I can do this on local, but on Travis i found I can't override the default behavior.

When I try:

<code>
script:
 ./gradle assembleDebug
</code>

The default behavior overrides the execution and trigger the 'connectedCheck' command which at this stage fails because obviously there are no tests configured yet.

How can I fire only an "assemble" Gradle command from mi Travis .yml?

This is a job with the error:
https://travis-ci.org/martinrevert/aRGENTeaM/jobs/33370392

This is my Travis yml:
https://github.com/martinrevert/aRGENTeaM/blob/travis-master/.travis.yml

Thanks in advance,
Martin

**Comment by IgorGanapolsky** [comment]
What about `./gradlew assemble test`.  Would that work on Travis-ci?
