### ISSUE TITLE
IRC notifications: don't join and leave all the time

### ISSUE THREAD

**Issue by Nowaker** [travis-ci/travis-ci#2699]
> 01:13:22 \* Now talking in #virtkick
> 01:13:22 \* Topic is 'VirtKick - cloud made easy | https://virtkick.io/ | https://demo.virtkick.io/'
> 01:13:22 \* Set by Nowaker on Wed Aug 20 18:41:03 2014
> 01:29:54 -!- travis-ci [~travis-ci@ec2-54-198-251-155.compute-1.amazonaws.com] has joined #virtkick
> 01:29:54 < travis-ci> [travis-ci] passed: virtkick/virtkick-prototype e6ad81e build notifications on 
>                       IRC
> 01:29:54 -!- travis-ci [~travis-ci@ec2-54-198-251-155.compute-1.amazonaws.com] has left #virtkick []

That's happening all the time. I myself used `/ignore` to filter out joins and leaves, but it's very annoying for those who didn't. Please stay on the channel - at least for 48 hours.

**Comment by JoshDreamland** [comment]
Agreed; could you please reopen this? I also just learned the hard way that my options are having no enforcement for channel bans or having the bot flood the room with join/parts.
