### ISSUE TITLE
No loop device?

### ISSUE THREAD

**Issue by reiven** [travis-ci/travis-ci#2700]
Hi! i'm trying to test my proyect but it relies on Tomb ()
But that dependency tries to use loopdevices and is giving me this error:

```
tomb forge a.key --unsecure-dev-mode --tomb-pwd password --no-color -f
losetup: Could not find any loop device. Maybe this kernel does not know
about the loop device? (If so, recompile or `modprobe loop'.)
tomb [W] Loop mount of volumes is not supported on this machine, this error
tomb [W] often occurs on VPS and kernels that don't provide the loop module.
tomb [W] It is impossible to use Tomb on this machine at this conditions.
tomb [E] Operation aborted.
```

It will be possible to have a loop device on the Travis environment?

Thanks

**Comment by maxonthegit** [comment]
No *true* workarounds that I am aware of: only two tiny bits of additional information.
* Someone seems to have succeeded in using nested virtualization to overcome this limit: see [here](https://github.com/travis-ci/travis-ci/issues/932#issuecomment-17707267).
* `libguestfs` seemed a promising alternative to `losetup` for creating disk images, but `virt-make-fs` still fails when attempting to perform kernel detection ([example](https://travis-ci.org/maxonthegit/netkit/builds/68471301#L9392)).
