### ISSUE TITLE
Unable to use OSX (10.7+ ) GUI unit tests.

### ISSUE THREAD

**Issue by trevorlinton** [travis-ci/travis-ci#2702]
I'm unsure if this is a bug or not supported, my build succeeds but the tests seem to stall.  I've manually tested all of the code on 8 different macosx environments and haven't had issues, i'm curious if there's something i'm missing.  Does travis-ci not support a full GUI environment for unit tests? None of the mouse/keyboard tests seem to actually run. 

You can view the tests here: https://github.com/trueinteractions/tint2/tree/master/test
The repository here: https://github.com/trueinteractions/tint2/
The output from travis-ci here: https://travis-ci.org/trueinteractions/tint2/builds/33464861

One thing I noticed in the logs is it states "Starting iOS Simulator".  Is the objective-c support for travis-ci limited to just iOS?  That could explain a lot.

**Comment by BanzaiMan** [comment]
Sorry for the long silence.

As you are aware, we have moved passed 10.7 now. If you have issues with more recent builds, please open a new ticket.
