### ISSUE TITLE
Node cookbook inconsistency

### ISSUE THREAD

**Issue by jdalton** [travis-ci/travis-ci#2707]
In the .travis.yml if you specify `- node_js: "0.10"` it will currently 

``` bash
nvm install 0.10
Now using node v0.10.31
```

but if you do:

```
nvm use 0.10
```

It will install node v0.10.29

``` bash
Now using node v0.10.29
```

**Comment by BanzaiMan** [comment]
I don't think this is an issue any longer.

If you still see the problem, do let us know with the build log URL. (Do keep in mind that the latest images may not have Node.js 0.10 pre-installed.)

Thanks.
