### ISSUE TITLE
Misleading partial interpretation of language

### ISSUE THREAD

**Issue by th0114nd** [travis-ci/travis-ci#2708]
I was having trouble with getting the build to work, and after a bunch of frustration I realized it was a casing error on the language: erlang vs Erlang. However, it looks as though travis is able to work partway with Erlang as the language, enough to recognize the default otp_release is R14B04 even though that wasn't a version in my .travis.yml, as per the erlang build script: https://github.com/travis-ci/travis-build/blob/d7497cb7463c27356617af360af29ccecce37f7b/lib/travis/build/script/erlang.rb#L5

Here is the passing version: https://travis-ci.org/th0114nd/travis-failure/builds/33542545
and the failing version: https://travis-ci.org/th0114nd/travis-failure/builds/33542696

I think that the correct behavior would be either to a) reject "Erlang" as a language outright with a message indicating that it doesn't exist, or b) accepting "Erlang" as synonymous to "erlang" and carrying on appropriately. Being able to start trying to activate otp and so on is misleading and unhelpful.

**Comment by BanzaiMan** [comment]
Language name is now case-insensitive.
