### ISSUE TITLE
fatal: destination path 'xxxx' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by PeterDaveHello** [travis-ci/travis-ci#2715]
I got this problem for a while, not 100% probability to occure, maybe 50%, is possible to fix it?

Thanks!!

https://travis-ci.org/cdnjs/cdnjs/builds/33241830

> Using worker: worker-linux-12-1.bb.travis-ci.org:travis-linux-7
> $ git clone --depth=1 --branch=master git://github.com/cdnjs/cdnjs.git cdnjs/cdnjs
> Cloning into 'cdnjs/cdnjs'...
> remote: Counting objects: 141433, done.
> remote: Compressing objects: 100% (96977/96977), done.
> remote: Total 141433 (delta 41382), reused 137759 (delta 41054)
> Receiving objects: 100% (141433/141433), 304.73 MiB | 21.66 MiB/s, done.
> Resolving deltas: 100% (41382/41382), done.
> Checking connectivity... done.
> /home/travis/build.sh: line 175:  1307 Killed                  git clone --depth=1 --branch=master git://github.com/cdnjs/cdnjs.git cdnjs/cdnjs
> 
> The command "eval git clone --depth=1 --branch=master git://github.com/cdnjs/cdnjs.git cdnjs/cdnjs" failed. Retrying, 2 of 3.
> 
> fatal: destination path 'cdnjs/cdnjs' already exists and is not an empty directory.
> 
> The command "eval git clone --depth=1 --branch=master git://github.com/cdnjs/cdnjs.git cdnjs/cdnjs" failed. Retrying, 3 of 3.
> 
> fatal: destination path 'cdnjs/cdnjs' already exists and is not an empty directory.
> 
> The command "eval git clone --depth=1 --branch=master git://github.com/cdnjs/cdnjs.git cdnjs/cdnjs" failed 3 times.
> 
> The command "git clone --depth=1 --branch=master git://github.com/cdnjs/cdnjs.git cdnjs/cdnjs" failed and exited with 128 during .
> 
> Your build has been stopped.

**Comment by hitotch** [comment]
I had same issue. I could resolve it.

Resolution: Run your SmartGit/HG with Administrator mode.
(Right click SmartGit, and Run as Admnistrator)

**Comment by fenollp** [comment]
Same issue happening pretty frequently here: https://travis-ci.org/erldocs/other.erldocs.com/builds/68541854

Note: repo is pretty big (~100MB) and unpacked it's like 6GB. Someone working on this?

**Comment by fenollp** [comment]
Actually this other project is failing to build too (just today btw) https://travis-ci.org/2600hz/kazoo/jobs/68560133

**Comment by BanzaiMan** [comment]
@fenollp That last one is probably unrelated. https://travis-ci.org/2600hz/kazoo/jobs/68560133#L71 says the branch (or a tag) you're trying to build does not exist. This seems to be true. https://github.com/2600hz/kazoo/branches

**Comment by PeterDaveHello** [comment]
Hi there, do we have any updates?
Still have this problem:
https://travis-ci.org/cdnjs/cdnjs/jobs/71764606

**Comment by joshk** [comment]
Hi @PeterDaveHello 

This error is interesting as I see two issues.

1. No Space Left On Device : indicates the clone is so big that we can't seem to clone it all. How big is the repo?

2. When there is a git clone error, we should remove the current cloned dir (if one exists) before trying again. @BanzaiMan can you add this to the backlog?

Thanks a bundle

Josh

**Comment by PeterDaveHello** [comment]
Hi Josh,

The repo size is about 600MB, after checked-out files, is about 13GB!

Tanks!
Peter

**Comment by joshk** [comment]
Ahhhhhhhhh, ok, so there lies the real issue, I guess the disk size on the VM is not large enough.

I don't have a great solution for this right now but to use `sudo: required` for now. I have something in the works as an even bigger improvement, but it isn't ready for node projects yet sorry.

**Comment by PeterDaveHello** [comment]
np, thanks for your reply

**Comment by PeterDaveHello** [comment]
Hi @joshk , I forgot that sparse-checkout may help, I opened this issue: https://github.com/travis-ci/travis-ci/issues/5286 , hope you can take a look at it, thanks!

**Comment by joshk** [comment]
@PeterDaveHello could you link me to a recent build? I wonder if running your build on our new GCE based setup will help solve this issue.

**Comment by PeterDaveHello** [comment]
@joshk here: https://travis-ci.org/cdnjs/cdnjs/builds/71764605, I'll trigger a new build and see what we got.

**Comment by PeterDaveHello** [comment]
New build started: https://travis-ci.org/cdnjs/cdnjs/builds/98235976

**Comment by joshk** [comment]
That is not running on the new GCE setup

**Comment by PeterDaveHello** [comment]
Oops, let me try it ...

**Comment by PeterDaveHello** [comment]
@joshk https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future
> travis-ci.org:
> 
> All Legacy Precise and Trusty builds run on GCE, except certain users who've specifically opted into still running on Blue Box

Do I need to do something to enable it?

**Comment by joshk** [comment]
Your build is running on the container stack, you need to use `sudo: required`

**Comment by PeterDaveHello** [comment]
https://travis-ci.org/cdnjs/cdnjs/builds/98237544 :sparkles:

**Comment by PeterDaveHello** [comment]
hmmm ... same same, all failed. @joshk

**Comment by boxi13** [comment]
Hi

**Comment by joshk** [comment]
@PeterDaveHello I will need to talk to @solarce and @meatballhat to see how much disk space the GCE based VMs have. I wonder if the version of git we have installed on the host affects its ability to checkout the code? The error messages look very much like there just isn't enough space on disk to check everything out.

**Comment by PeterDaveHello** [comment]
@joshk yep, I think there is only disk space issue now, do you need me to use an old version of git to test if it can clone with success? I still wonder if sparse-checkout can be support in future :smile:

**Comment by aheficent** [comment]
Did anyone find a solution here? In my case, only two of ten builds succeeded.

**Comment by BanzaiMan** [comment]
@aheficent There were issues with GitHub earlier today. Perhaps they affected your builds? Do you still see them now?

**Comment by aheficent** [comment]
@BanzaiMan Yes, I am facing this Issue right now. The errored command is: 
git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
The build does not always fail, sometimes it works. The same build.

**Comment by BanzaiMan** [comment]
@aheficent The last build in https://travis-ci.org/OCA/maintainer-quality-tools/builds was 10 days ago.

**Comment by aheficent** [comment]
Sorry @BanzaiMan I misled you. The build is here: https://travis-ci.org/Eficent/eficent-odoo-addons/jobs/147962626

**Comment by BanzaiMan** [comment]
@aheficent Looks like you are caching `$HOME`. https://travis-ci.org/Eficent/eficent-odoo-addons/jobs/147962626#L186 If it includes `${HOME}/maintainer-quality-tools`, your build will fail with the `git` command. This is not related to this issue at all.

**Comment by aheficent** [comment]
@BanzaiMan all right. I did not realize of this, sorry. Thanks a lot.

**Comment by peterjp80** [comment]
I'm having the same issue.  First deployment worked like a charm, now all I get is:

**Warning: fatal: destination path '.' already exists and is not an empty directory. Used
 --force, continuing.**   

Then I get "Done, but with warnings" and files were not deployed to my github repo.

**Comment by BanzaiMan** [comment]
@peterjp80 I don't think this issue has anything to do with deployment.

**Comment by peterjp80** [comment]
@BanzaiMan What makes you say that?  In the meantime, I switched over to gulp and gulp-gh-pages and that's working flawlessly.

**Comment by BanzaiMan** [comment]
@peterjp80 Because this issue is about failure to clone the `git` repository. Your error is happening way beyond that.

**Comment by peterjp80** [comment]
@BonzaiMan Sorry man, I just realized this is the wrong thread! I call "deployment" running the "git_deploy" grunt task from the grunt-git-deploy package and I was getting the same error as the title of this thread. This has nothing to do with Travis CI. Sorry again for the confusion.

**Comment by PeterDaveHello** [comment]
For the too huge repo, I am trying to implement this feature in travis-ci/travis-build#882, please feel free to give me your suggestion, thanks!

**Comment by jobs2gr** [comment]
i just renamed old directory

**Comment by Ma-XX-oN** [comment]
I attempted to use the following command:

`git clone  https://github.com/jelera/vim-javascript-syntax.git ~/.vim/bundle/vim-javascript-syntax`

But I kept getting the error message:

> fatal: destination path '/home/username/.vim/bundle/vim-javascript-syntax' already exists and is not an empty directory.

However, it didn't exist, and if I created an empty directory there, it would succeed.

**Comment by ARCHANAMISHRA1677** [comment]
fatal: destination path 'clobhub' already exists and is not an empty directory.
how to fix it ?????

**Comment by steveb86** [comment]
C:\Users\steve> git clone https://github.com/flutter/flutter.git
fatal: destination path 'flutter' already exists and is not an empty directory.

**Comment by osunkoyadavid** [comment]
Pls help me, when i run flutter create app on node command prompt, it gives this error
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to set up Flutter, run the following command:
       git clone -b beta https://github.com/flutter/flutter.git
What should i do, I really want to learn flutter

**Comment by osunkoyadavid** [comment]
Someone help me please

**Comment by osunkoyadavid** [comment]
plssssssssss
