### ISSUE TITLE
Timeouts when running SauceLabs on TravisCI

### ISSUE THREAD

**Issue by SevInf** [travis-ci/travis-ci#2718]
Hi. 
We are running our tests from TravisCI on SauceLabs, using SauceConnect and we are experiencing a lot of timeout errors. In fact, almost every builds ends with timeout error.

Example build: 
https://travis-ci.org/bem/bem-components/jobs/33261787 
It fails with timeout on `moveTo` command. Same build in Sauce console: 
https://saucelabs.com/tests/234a699039184227b3df347afd6108ef

As you can see, request was actually performed by the server, but no response was received by client. 
We are using Node.JS library https://github.com/admc/wd to talk with SauceLabs. It has option to retry timed out requests, but if we enable it, some of the commands will be executed twice. `travis_retry` script does not help either – sooner or later one of the commands will fail anyway.

This issue occurring only on TravisCI, we never reproduced it locally. 
Can you please give use some advice, what can we do in this situation?

**Comment by roidrage** [comment]
I'm closing this issues for now as there haven't been any further updates recently.
