### ISSUE TITLE
No output has been received in the last 10 minutes

### ISSUE THREAD

**Issue by jluttine** [travis-ci/travis-ci#2726]
I get the following error nowadays:

"No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated"

This has been happening for a few days and did not happen before. I haven't change anything in my code, just some ReST doc files. Complete log:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/33701092/log.txt

My two builds stop at different times, suggesting that the problem is not in the package that was being installed during the stop failure. The log of the other build:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/33701093/log.txt

I have tried restarting the job several times but it doesn't help. What could be wrong? Is the problem in Travis-CI or somewhere else? Everything works on my own computer.

**Comment by mmoayyed** [comment]
We have travis publish snapshots to sonatype. For very large projects the build simply times out:
https://travis-ci.org/apereo/cas/builds/135048315

There is no way to configure this?
