### ISSUE TITLE
Support configurable job timeouts

### ISSUE THREAD

**Issue by mmoayyed** [travis-ci/travis-ci#2736]
The docs note:

> Because it is very common to see test suites or before scripts to hang up, Travis CI has hard time limits. If a script or test suite takes longer to run, the job will be forcefully terminated and you will see a message about this in your build log. With our current timeouts, a job will be terminated if it's still running after 50 minutes (120 minutes on travis-ci.com), or if there hasn't been any log output in 10 minutes.

It would be great, if:
- the 50 minute timeout value was increased to lets say 90 minutes perhaps
- better if the timeout value could be configurable per projects

We have scripts that execute after the build that along with the build execution itself could take longer than 50 minutes to generate. An example might be generating javadocs for the entire project (which is comprised of many many maven modules) and pushing them docs to gh-pages of github.

**Comment by evoskuil** [comment]
Hi @joshk This is getting quite burdensome. Is it still not possible to buy more time for a public repo?

**Comment by bitemyapp** [comment]
@roidrage @joshk this is causing problems for the Haskell Platform build, do we need to migrate elsewhere or is there a story for coping with this? Like to avoid changing CI systems if possible.

**Comment by joshk** [comment]
Hey @bitemyapp and @evoskuil 

Please email support, cc me in the email, and we can talk about options. (we have options)

Have a great weekend

**Comment by bitemyapp** [comment]
@joshk I emailed @roidrage - I'll fwd to you too.

**Comment by cybertk** [comment]
+1

**Comment by krivit** [comment]
I've been hitting time limits when trying to test R packages with `r_check_revdep: true`: the package in question (statnet/ergm) has more than 20 reverse-dependencies/suggests, and I don't know whether all 20 of them can be installed, built, and checked in the allotted time.

Perhaps this could be resolved by adding a boolean configuration option (e.g., `no_timelimit`) that, if set,
1. Removes time limits from the job.
2. Disallows that job to run concurrently with other jobs for that project or user. That is, when queued, it waits for all other jobs for that project or user to finish before starting, and prevents other jobs from starting before it finishes.

This would discourage frivolous use of `no_timelimit` and limit its impact, while allowing it to be used sporadically to, say, check if a particular package would break any others if submitted to CRAN.
