### ISSUE TITLE
"Accounts" wedged at "Please wait while we synchronize your data from GitHub"

### ISSUE THREAD

**Issue by djmitche** [travis-ci/travis-ci#2742]
I was having trouble getting my org's (buildbot) repo list to synchronize from Github.  When I clicked "Sync Now", it would refresh the page, but still said last sync'd yesterday.  And the new repos didn't appear.

After a few tries, it's now wedged permanently on the "Please wait" message.  Logging out and back in doesn't help.  And it's been doing so for a few hours now.

I imagine that this is just a state-synchronization issue of some sort, where the "done synchronizing" message got lost?  Anyway, (a) please fix for my account and (b) please fix underlying bug.

**Comment by grzegorzgg** [comment]
I have the same issue.
Please help solve the problem issue.

**Comment by joshk** [comment]
@grzegorzgg please email support and we can look into it
