### ISSUE TITLE
[API] The repos endpoint should not take PRs into account for the last build status

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#2747]
when giving the last build status of a repo, the `/repos` endpoint should only look at builds for code which is actually in the repo. Currently, if the last build triggered is for a PR, it will use this status. this means that a submitted PR breaking the tests will now mark the repo as failing, even though the broken code is not merged

See https://gist.github.com/stof/50b09b01dd30bc4e3f8d for the data returned by https://api.travis-ci.org/repos.json?owner_name=Behat currently. the Behat/docs and Behat/MinkZombieDriver repos are affected by this issue in this example

**Comment by BanzaiMan** [comment]
We are working on API revision, and I don't think this is not relevant at this time. May I close this?

**Comment by stof** [comment]
Well, if the endpoint disappears, feel free to close it. If the new API has a similar endpoint, please take such case into account.
It may even be fixed already. I haven't checked recently
