### ISSUE TITLE
GitHub's "Revert" button and extra builds

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2749]
When a user clicks on the "Revert" button on a PR, a new branch `revert-NNNN-BRANCH` is created. We build this, but since there is a new PR created based on this action, maybe we don't need to build this `revert` branch.

**Comment by BanzaiMan** [comment]
@joshk What do you think?

**Comment by joshk** [comment]
closing this as it has become stale.

**Comment by BanzaiMan** [comment]
@joshk There is a valid PR, and the issue is still valid, though.

**Comment by joshk** [comment]
@BanzaiMan issue is valid, you are right, but this is also old.

That said, I did not see your PR, sorry. We can move the conversation there if you prefer?

**Comment by BanzaiMan** [comment]
Ugh. It was just a feature branch. Sorry. I'll open a PR based on it.
