### ISSUE TITLE
Include more request information to the webhook payload

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#2751]
ATM the [webhook payload](http://docs.travis-ci.com/user/notifications/#Webhooks-Delivery-Format)  misses information such as the fields `pull_request` and `tag` from the request (http://docs.travis-ci.com/api/#requests)

**Comment by carlad** [comment]
This issue has been resolved.
Updates to webhook payload include:
state
commit_id
pull_request
pull_request_number
pull_request_title
tag_name

**Comment by fh** [comment]
@carlad Thank you so much! :+1:

**Comment by svenfuchs** [comment]
@carlad @tyranja :heart: :heart: :heart:

**Comment by till** [comment]
@svenfuchs @carlad — is this deployed for magnum?

**Comment by BanzaiMan** [comment]
@till Yes, it is.

**Comment by till** [comment]
Thanks!

**Comment by carlad** [comment]
Our pleasure :-)
