### ISSUE TITLE
Support additional notification variables around pull request builds.

### ISSUE THREAD

**Issue by grahamc** [travis-ci/travis-ci#2753]
Notifications to my Hipchat rooms are formatted as such:

```
'%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Diff</a>)'
```

This results in notifications as so:

```
foo/bar#76 (feature/webhook - 4254e8f : Ed): The build was fixed. (Details/Diff)
```

However, if `feature/webhook` is currently in PR against develop, it sends an additional notification simulating the merge of the branch into develop. That notifications is confusingly identified as being the build status of develop:

```
Clarify/backend#77 (develop - 62a28f8 : Ed): The build passed. (Details/Diff)
```

 Is there a way to identify in this second message that it is simulating the merging of the PR?

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-ci/issues/2984

**Comment by gscott** [comment]
I'm new to this old issue.  I'm reading the webhook payload for a pull request and I can't see where the equivalent of `$TRAVIS_PULL_REQUEST_BRANCH` can be found -- only the target branch the pull request (i.e., `$TRAVIS_BRANCH`)    Is it there?
