### ISSUE TITLE
Consider adding older Erlang OTP Releases 

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2757]
Rebar supports older versions of Erlang than are currently available on Travis.

The main obstacle is the build time that each Erlang runtime adds to the worker provisioning. We should look for ways to shorten this, so that we can add them.

This is originated in https://github.com/rebar/rebar/pull/295.

**Comment by tuncer** [comment]
Any progress on providing R13B03?

**Comment by BanzaiMan** [comment]
I'm thinking we'll pre-build Erlang (and probably other language runtimes) and use those during the build image provisioning to overcome this. Erlang still takes way too long to compile, but this should ease the pain.

**Comment by BanzaiMan** [comment]
The on-demand installation of OTP Release has been deployed. I've so far added R14B, R13B03, R13B04. R14B01 build fails with segmentation fault (https://travis-ci.org/travis-ci/travis-erlang-builder/builds/69906407), and I am not sure how to fix it.

These old releases are not going to be pre-installed going forward.

Closing this.
