### ISSUE TITLE
Crash: 'phpenv: command not found'

### ISSUE THREAD

**Issue by keradus** [travis-ci/travis-ci#2759]
Crash! `phpenv: command not found`
Please see failures at https://travis-ci.org/fabpot/PHP-CS-Fixer/builds/34418244 for PHP 5.5 and 5.6

``` console
$ phpenv global 5.5
/home/travis/build.sh: line 41: phpenv: command not found
The command "phpenv global 5.5" failed and exited with 127 during .
```

**Comment by BrunoDeBarros** [comment]
Just found this after looking up details on the problem. I've had this happen to me a number of times today alone (we've had a lot of commits today, so there's been a big number of builds):

https://travis-ci.org/pancakeapp/translations/builds/59208715
https://travis-ci.org/pancakeapp/translations/builds/59208284
https://travis-ci.org/pancakeapp/translations/builds/59208164
https://travis-ci.org/pancakeapp/translations/builds/59208070
https://travis-ci.org/pancakeapp/translations/builds/59207333

It's not reproducible and doesn't seem to have any reason for happening at all. I don't expect this issue will be reopened, but I wanted to provide more info; it might be useful to know that it does happen quite a bit.

It doesn't really matter - I can just rerun the test and the problem goes away. But so far zero of my failed tests had anything to do with anything being wrong with the code (I've had three different travis-side issues with running builds so far).

**Comment by gsf** [comment]
Seeing this issue in our builds today as well:

https://travis-ci.org/CityOfPhiladelphia/phila.gov/builds/59408050
https://travis-ci.org/CityOfPhiladelphia/phila.gov/builds/59409466

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/3726 for the current issue.
