### ISSUE TITLE
New account can't find repositories

### ISSUE THREAD

**Issue by erichaase** [travis-ci/travis-ci#2765]
I'm getting the following:

Sorry, it seems like we couldn't find any repositories you have access to on GitHub

I've tried signing in and signing out. I've also tried revoking travis' access from GitHub and reauthorized but no luck.

Please advice.

**Comment by SerafimArts** [comment]
Didn't work again...
> Last synchronized from GitHub: less than a minute ago

Repo: https://github.com/SourcesRU/Config
Travis: https://travis-ci.org/SourcesRU/Config 
> The repository at SourcesRU/Config was not found.

**Comment by BanzaiMan** [comment]
@SerafimArts Could you publicize your org membership and try again?

**Comment by SerafimArts** [comment]
Hmmm... Yep, it works!

Sry, my bad =)

**Comment by JosephKellyCSC** [comment]
For some reason I keep freezing at 39% when Syncing (Pulling current branch)

**Comment by geryoung** [comment]
it works for me, thanks @rkh !

**Comment by KinkoX120** [comment]
Fart.

**Comment by scento** [comment]
I'm having the same issue, Travis is continually "Syncing from Github". I already tried to log in and publicize my organization memberships.

**Comment by bzick** [comment]
"Syncing from Github" too

**Comment by diogolundberg** [comment]
@rkh @BanzaiMan 
I removed the Travis-CI access to test some configurations and now i can't have my organization back.

https://travis-ci.org/profile/diogolundberg

And i lost my access to

https://travis-ci.org/DataViva/dataviva-site

![syncing](https://cloud.githubusercontent.com/assets/4092969/13384865/dd398138-de78-11e5-9317-16101d3eb3c8.png)

**Comment by Superdominik** [comment]
I'm having the same issue. I've just created my account a few hours ago. I saw my repository once, didn't click the button, then switched to another page, came back and then the repository didn't show anymore and it was continually syncing.

**Comment by viswanathamsantosh** [comment]
same issue! Syncing from Github from the past 1 day.

**Comment by konstantinyakovskyiteamdev** [comment]
The same issue for me. "Sorry, it seems like we couldn't find any repositories you have access to on GitHub"

**Comment by Garethderioth** [comment]
#5672 I'm having the same problem with my new account.

**Comment by Tzeejay** [comment]
@rkh I was able to get my repo info on travis-ci.org. Logged out of travis-ci.com and back in but the same story :/

Weird

**Comment by christ776** [comment]
Same here. It says "The repository at Christian De Martino/CDMSegmentedControl was not found." https://travis-ci.org/Christian%20De%20Martino/CDMSegmentedControl when I click on the build failed bagde on my GitHub repo.

**Comment by christ776** [comment]
Ok, here's what I've discovered.

The travis URL was pre-populated with my full name instead of my GitHub username. By making the change I was able to get it to work.

**Comment by brotenet** [comment]
I'm having the same issue, Travis is continually "Syncing from Github".
