### ISSUE TITLE
Fail fast builds

### ISSUE THREAD

**Issue by shaiguitar** [travis-ci/travis-ci#2776]
We have an internal tool that uses travisCI. It's been working great. We get notified when a build goes green or red. Mostly this is sufficient. But it would be very helpful if there would be some mechanism to   tell if any unit(s) in the entire build have failed. Thus we could use this mechanism to detect  that the whole build is red, even though only one unit has failed and the whole thing is still building.

Then we could implement a "fail fast" notification in our own internal tooling. 

The way to accomplish this could vary and isn't important in my mind at this point, although using something like a hook or callback that gets pushed to once a unit fails seems might work. The payload could have some information as to what unit failed, or some other related stats.

**Comment by roidrage** [comment]
I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
