### ISSUE TITLE
Binary cross-compilers and cross-compiled libraries

### ISSUE THREAD

**Issue by luke-jr** [travis-ci/travis-ci#2790]
It would be convenient if there was a way to have Travis easily install cross-compilers and cross-compiled libraries. I don't know any sane way to do this on Ubuntu, but it's fairly simple on Gentoo: just crossdev -t i686-pc-mingw32 then i686-pc-mingw32-emerge libwhatever; this can be trivially set up to build binary packages that can be reused/shared between builds.

**Comment by roidrage** [comment]
I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by doug65536** [comment]
What? None of that stuff is correct. To install and use cross compilers on linux, just install these with the `apt-get`:

`mingw-w64`
`binutils-mingw-w64`
`mingw-w64-tools`

Then to build 64 bit windows binaries, compile with:
`x86_64-w64-mingw32-g++`   etc... It's just a prefix.

and to build 32 bit windows binaries:
`i686-w64-mingw32-g++`   etc... It's just a prefix.

Which actually works fine in my .travis.yml. Problem is, the ancient distribution of used on travis. Seriously version 12? Come on! The package manager's version of mingw doesn't even recognize `-std=c++11`.

@roidrage Any way to make it use a ppa that has newer packages, or something?
