### ISSUE TITLE
Prioritize real commits over pull requests

### ISSUE THREAD

**Issue by chancancode** [travis-ci/travis-ci#2801]
Hello! I'm representing Rails for this feature request.

First of all, thank you for letting us run our tests on your infrastructure! :heart:

One of the problems we have lately is that we get a lot of pull request on our repository which causes a lot of CI runs (some of them aren't even necessary, because people forgets to put [ci skip] sometimes). This blocks the CI queue and causes the CI runs for "real" commits to be delayed for hours and makes it difficult to identify and fix problems on master in a timely manner.

It would be great if Travis can distinguish between PRs and "real" commits and be smarter about what gets run when :smile: Perhaps it could always prioritize commits over PRs, or perhaps it could "just" expose an option to never run PRs unless manually triggered.

Let me know what you think! :smile:

cc @BanzaiMan @rafaelfranca @matthewd @senny

**Comment by Fryguy** [comment]
Similarly I mentioned in #3169 that I'd like the opposite feature, that is to prioritize PRs over merges/branches.   I assume if this were made an option one could choose which would prioritize over the other.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by joehorsnell** [comment]
Linking to #2566, which is also related.
