### ISSUE TITLE
Badge for nonexistent repos

### ISSUE THREAD

**Issue by jpadilla** [travis-ci/travis-ci#2823]
Reopening here, originally in https://github.com/travis-ci/travis-api/issues/135.
Regarding discussion in https://github.com/gcollazo/ember-cli-addon-search/issues/1.

I think nonexistent repos should still return a badge if requesting one instead of JSON.

If you request `https://api.travis-ci.org/jpadilla/nonexistent.svg?branch=master` you'll get:

``` json
{"file":"not found"}
```

The client is expecting an SVG(or png) when requesting this URL not JSON. Are there any design decisions for this to work like this this? I'm willing to work on implementing this.

**Comment by brycekahle** [comment]
This is no longer the behavior. An inaccessible/unknown badge is now returned for invalid repos. Issue can be closed.

**Comment by BanzaiMan** [comment]
@brycekahle Thanks for the ping.
