### ISSUE TITLE
Go builds should use `go get -t`

### ISSUE THREAD

**Issue by rakyll** [travis-ci/travis-ci#2826]
Builds don't seem to get the test dependencies and Travis can't build our perfectly fine repo [1].

Use `go get -t -v ./...` instead to get dependencies.

[1]  https://travis-ci.org/GoogleCloudPlatform/gcloud-golang/jobs/36706987

**Comment by hiro4bbh** [comment]
As of 9 June 2018, it seems to use `go test` instead of `go test -t` (with default `.travis.yml` setting).
Is this any regression? I can't find out what has changed as following the commits.
