### ISSUE TITLE
iOS tests are failing with Xcode 6 (Timed out waiting 120 seconds for simulator to boot)

### ISSUE THREAD

**Issue by 0xced** [travis-ci/travis-ci#2829]
See https://travis-ci.org/0xced/XCDYouTubeKit/builds/36785363 for example. Here is the relevant log:

> Testing failed:
> Test target XCDYouTubeKit iOS Tests encountered an error (Timed out waiting 120 seconds for simulator to boot, current state is 1. If you believe this error represents a bug, please attach the log file at /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/com.apple.dt.XCTest-status/Session-2014-10-01_09:11:50-GCvpwG.log)
> *\* TEST FAILED **

The OS X tests passed without any problem.

**Comment by gardner** [comment]
Relevant SO: http://stackoverflow.com/questions/788277/iphone-strange-error-when-testing-on-simulator

**Comment by mike-loo** [comment]
Answered similar question on SO:
http://stackoverflow.com/questions/25380365/timeout-when-running-xcodebuild-tests-under-xcode-6-via-ssh

**Comment by levigroker** [comment]
@henrikhodne Could you please share the details of your solution? I have yet to find one which works on Yosemite with Xcode 6. Many thanks!

**Comment by rajohns08** [comment]
I'm seeing this 120s timeout issue when running:

```
xcodebuild -project JudgecardXSwift.xcodeproj -scheme JudgecardXSwift -sdk iphonesimulator build test
```

**Comment by mgetzbw** [comment]
this bug appears to have returned for xcode 8/ios10

**Comment by szymont** [comment]
@mgetzbw I have the same problem on my CI using Xcode 8/iOS 10

**Comment by mgetzbw** [comment]
@szymont have you tried adding a `sleep 5` to `after_success`? that seems to fix it for the most part

**Comment by szymont** [comment]
@mgetzbw No, but setting env variable `FASTLANE_EXPLICIT_OPEN_SIMULATOR=1` helped in my case.
