### ISSUE TITLE
Expose success/fail of deploy stages to after_deploy stage

### ISSUE THREAD

**Issue by oldgandhi** [travis-ci/travis-ci#2831]
We're using the Heroku deployment feature. Sometimes we will have a passing build that fails during the deployment stage (for legit reasons). We have a few commands we want to run during the after_deploy stage but only when the deploy(s) was successful. Can you please expose a way that allows us to evaluate the success of each defined deployment. Perhaps through the anvil exit status?

```
nothing added to commit but untracked files present (use "git add" to track)
Dropped refs/stash@{0} ([redacted])
deploy failed, anvil build error: exited 1
failed to deploy
```

Alternately allow each deploy provider define an after_deploy that is only run when that specific provider succeeds in deployment.

**Comment by BanzaiMan** [comment]
It seems to me that the current behavior is that the job halts immediately and is marked an error if deployment exits with nozero.

**Comment by medikoo** [comment]
It's very valid request, can we have that reopened?
