### ISSUE TITLE
Avatars broken

### ISSUE THREAD

**Issue by roidrage** [travis-ci/travis-ci#2837]
Due to this change our user avatars are currently not working properly: https://developer.github.com/changes/2014-09-05-removing-gravatar-id/

Could we, as a workaround, until the sync is fixed to synchronize the avatar_url, calculate the Gravatar ID in the API for the time being, instead of relying on that field?

**Comment by cog-piisang** [comment]
So, it seems this has been forgotten...

**Comment by roidrage** [comment]
There's a workaround deployed that should show you a valid Gravatar, but I agree that the full fix hasn't been finished yet.

**Comment by derTobsch** [comment]
*push*

**Comment by BanzaiMan** [comment]
I don't think this is an issue any longer.
