### ISSUE TITLE
Upgraded npm (2.0.0) has intermittent failures when doing npm upgrade / install.

### ISSUE THREAD

**Issue by adeneui** [travis-ci/travis-ci#2838]
Since the upgrade of OS X buildbots we've been seeing intermittent failures in npm upgrade / install. The old npm version (1.4) does not have a problem, but the currently installed version (2.0.0) is subject to https://github.com/npm/npm/issues/6309. The recommended fix is to migrate to 2.1.1

Example failure:

```
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.10.32
npm ERR! npm  v2.0.0
npm ERR! path /Users/travis/.npm/edcb04d4-pm-source-map-0-1-34-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! EEXIST, open '/Users/travis/.npm/edcb04d4-pm-source-map-0-1-34-package-tgz.lock'
File exists: /Users/travis/.npm/edcb04d4-pm-source-map-0-1-34-package-tgz.lock
Move it away, and try again. 
The command "npm update" failed and exited with 47 during .
Your build has been stopped.
```

**Comment by jdalton** [comment]
I'm seeing more failures as of late when installing newer npm. This is one I see often (just about every other job run):

![image](https://cloud.githubusercontent.com/assets/4303/6218681/a057cdd2-b5d5-11e4-903e-51c943456857.png)

**Comment by jdalton** [comment]
If not that error it's
![image](https://cloud.githubusercontent.com/assets/4303/6218750/6a57d636-b5d6-11e4-84e9-67f43f613cda.png)

**Comment by BanzaiMan** [comment]
Is this issue confined to OS X builds? If not, https://github.com/travis-ci/travis-ci/issues/2389#issuecomment-74163184 suggests it might be related to CDN.

**Comment by jdalton** [comment]
> Is this issue confined to OS X builds? If not, #2389 (comment) suggests it might be related to CDN.

I'm using the  worker-linux.

**Comment by jdalton** [comment]
I'm not sure about the cdn stuff but the errors keep happening (sometimes), a rerun solves it usually (or a rerun of the rerun). Any ideas?

**Comment by jdalton** [comment]
I can't actually go a single test run without failures. Ugh.

**Comment by joshk** [comment]
Can you please email support and we can dive in deeper

**Comment by jdalton** [comment]
Sure thing.

**Comment by andig** [comment]
I'm seeing this in non-OSX builds as well, e.g. https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/62674124

**Comment by BanzaiMan** [comment]
npm has gone above 5, so I am guessing that this is no longer relevant. If there is an outstanding issue with the current version, we should have a new discussion.
