### ISSUE TITLE
Maven Builds on OSX return Error: JAVA_HOME is not defined correctly

### ISSUE THREAD

**Issue by dhalman** [travis-ci/travis-ci#2839]
Running maven to manage appium tests, worked great on travis until recently. Now returns this error:

```
$ bundle exec rake appium uiteststravis
Executing: `appium --full-reset >/dev/null 2>&1 &`
Executing: `export JAVA_HOME=$(/usr/libexec/java_home)`
Executing: `cd UITests`
Executing: `mvn -Dtravis -DretryCount=2 test`
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/libexec/java_home/bin/java
[!] Failed with exit code 1 while running: `mvn -Dtravis -DretryCount=2 test`
The command "bundle exec rake appium uiteststravis" exited with 1.
Done. Your build exited with 1.
```

**Comment by dwtj** [comment]
In case this helps anyone else: I have been running into this same problem with `brew`-installed version of `Maven`:

```
fir:~% mvn --version
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/libexec/java_home/bin/java
```

As others have said, `JAVA_HOME` can be set manually to work around this problem. I found when using `zsh`,

```
#export JAVA_HOME="/usr/libexec/java_home"  # This doesn't work.
export JAVA_HOME=$(/usr/libexec/java_home)  # This does work.
```

So, using the `$(...)` syntax works:

```
fir:~% mvn --version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T11:29:23-06:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
```

**Comment by henrikhodne** [comment]
Looks like this issue will be fixed in Maven 3.2.6, which is due to come out soon, so we'll try to get it in the next environment update for Mac.

**Comment by rppgowtham** [comment]
Thanks guys ! I was trying to fix this problem for last one week but now I found the reason :-) Now I'm follow 'dwtj' idea to use maven. 

Cheers!!

**Comment by sschuberth** [comment]
Meanwhile, the latest Maven release is 3.3.3, and I still see this issue: https://travis-ci.org/sschuberth/jenkins-ansicolor-plugin/jobs/85867593.

**Comment by BanzaiMan** [comment]
Closing as it's become stale. If there is a new concern, do let us know.
