### ISSUE TITLE
.travis.yml webhook notifications don't support https with certain ciphers

### ISSUE THREAD

**Issue by Asmod4n** [travis-ci/travis-ci#2850]
When trying to setup webhook notifications i couldn't get https to work.

My nginx ssl config:

```
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_dhparam /etc/ssl/dh2048.pem;
    ssl_trusted_certificate /etc/ssl/ca-bundle.pem;
    ssl_ciphers EECDH+AESGCM:EDH+AESGCM:EECDH:EDH:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;
    ssl_ecdh_curve secp384r1;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    resolver [::1];
    ssl_stapling on;
    ssl_stapling_verify on;
    spdy_headers_comp 0;
```

According to https://www.ssllabs.com/ssltest/ this setup works with every ssl implementation which is still supported by its vendors.

**Comment by icecreammatt** [comment]
Sorry to bump an older thread. @jalev I'm having the same issue as you. I suspect after reading this thread that Dockerhub has issues with their webhook when combined with CloudFlare's SNI SSL certificates. I'm able to get notifications on HTTP but not on HTTPS. @Hidendra Were you ever able to get webhooks working with SNI and CloudFlare?

**Comment by icecreammatt** [comment]
I just got feedback from one of Dockerhub's support engineers which said that they currently do not support SNI.
