### ISSUE TITLE
Request for inclusion of libicu-dev package in base images

### ISSUE THREAD

**Issue by sickill** [travis-ci/travis-ci#2851]
Referring to the Twitter conversation I had with @BanzaiMan about bundler cache and Docker queue (https://twitter.com/hiro_asari/status/519870019941826560) I'd like to request the inclusion of `libicu-dev` package in Travis base images.

We are building Gitorious on Travis (https://travis-ci.org/gitorious/mainline) and one of the gems we use depends on charlock_holmes gem, which in turn depends on `libicu-dev` package to build its native ext. We'd love to be put on the Docker queue but we use sudo in our `.travis.yml` to install this package (see here https://github.com/gitorious/mainline/blob/master/.travis.yml#L7).

**Comment by emq** [comment]
Also waiting for this :+1: 

any chances it will be done anytime soon? :pray:

**Comment by BanzaiMan** [comment]
This will be included in the next environment updates, most likely the end of January.

**Comment by Fire-Dragon-DoL** [comment]
Was this included? PhantomJS2.1 uses libicu 5.2, I still can't get precompiled binaries due to this, so I'm forced to use `sudo` which is pretty sad
