### ISSUE TITLE
Improve documentation about Apache/Symfony2

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#2852]
A customer suggests to improve our docs as follows. This might also hint at improvements to the Apache setup on our images?

> In regards the documentation, here http://docs.travis-ci.com/user/languages/php/#Apache-%2B-PHP I would add the following:
> 
> Modify /var/lib/apache/fastcgi permissions was needed as apache was failing when restarting:
> - sudo chmod 777 /var/lib/apache2/fastcgi
> 
> There is a bug in the OS version you are using in your vm's, this one https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/1177140
> 
> We have solved it doing this which differs from your documentation:
> # Bypasses a bug into travis box OS, restart apache
> - sudo /etc/init.d/apache2 stop && sudo rm -rf /var/lock/apache2 &&
>   sudo /etc/init.d/apache2 start
> 
> And the last one, this is more Symfony2 focused, change the user which apache is run with, to let it write inside app/cache and app/logs directories:
> - sudo sed -i -e "s,www-data,$USER,g" /etc/apache2/e

**Comment by BanzaiMan** [comment]
Closing this as it's become stale. We have the "Improve the docs" button, so if anyone is interested, they can send us suggestions!
