### ISSUE TITLE
Testing debian packages with piuparts fails with "cannot umount /proc"

### ISSUE THREAD

**Issue by bguerin** [travis-ci/travis-ci#2859]
Hello,

I am trying to continuous build personal debian packages with Travis.
I managed to build packages (via chroots build with [pbuilder](http://pbuilder.alioth.debian.org/)) and now I would like to test built packages with a tool called [piuparts](https://wiki.debian.org/piuparts).
Piuparts run debian packaging specific commands into a chroot to ensure a package installs, uninstalls, upgrades, ... successfully.

This step is currently failing with :

```
0m38.7s DEBUG: Starting command: ['chroot', '/tmp/tmpdKELWf', 'umount', '/proc']
0m38.7s DUMP:
umount: /proc: device is busy.
(In some cases useful info about processes that use
the device is found by lsof(8) or fuser(1))
```

I add some debug (lsof inside and ouside the chroot, ...) and I cannot figure what is going wrong.
I also reproduce my whole build on a fresh new Ubuntu 12.04.05 Server LTS VirtualBox virtual machine, without any problem.

From what I read on Internet, this could be a bug from the VZ Host kernel, which is fixed on 2.6.32-042stab092.3 and newer. Unfortunately, it seems that your are running 2.6.32-042stab090.5.

My builds can be seen here : https://travis-ci.org/bguerin/rtsp-linux-v2.6

Thanks for your help, and keep going guys, Travis CI is just awesome for anyone needing continuous integration to his open source projects !

**Comment by BanzaiMan** [comment]
Sorry for the long silence here. Is this still an issue?

**Comment by bguerin** [comment]
Hi @BanzaiMan 

I managed to workaround this problem with -k option (do not clean temporary directory in chroot)

I just launch a new build of my repo, without the -k option, and now it is working as expected. So not an issue anymore.
Thanks !
