### ISSUE TITLE
Sudo Access on Educational Travis

### ISSUE THREAD

**Issue by nickbabcock** [travis-ci/travis-ci#2862]
It's awesome that you guys are participating in the [Github Student Pack][]. I signed up for that immediately, as I have a couple projects on `.org`. The problem came when I tried to add one of my private repos for a school project that had the inconspicuous line of `sudo apt-get install -y postgresql-server-dev-9.3`. Travis would fail with `sudo: must be setuid root`. I've never come across this error before and googling this didn't raise my hopes.

I only realized that this problem is due to me signing up for the educational version of travis after I saw the price discrepancy in the what Github said and [what you guys offer][]. I then found the [blog post][] that held the key:

> Note that the Docker-setup currently doesn't support any commands requiring sudo

Luckily the build environment comes with `postgresql-server-dev-9.3`, so I didn't need to install it anyways, but I found it frustrating why my build was failing and I couldn't find information on why it was failing.

I think a better solution would be to inform the user that they are using the educational version of travis and so `sudo` is disabled (instead of the usual snippet indicating paranoid mode: `Sudo, the FireFox addon, setuid and setgid have been disabled.`). Ideally, `sudo` isn't disabled, but that may be wishful thinking :smile:

[Github Student Pack]: https://education.github.com/pack
[what you guys offer]: https://travis-ci.com/plans
[blog post]: http://blog.travis-ci.com/2014-10-07-free-builds-for-students-github-student-developer-pack

**Comment by meatballhat** [comment]
See travis-ci/travis-build#372 :smiley_cat:

**Comment by roidrage** [comment]
I'm closing this as sudo on educational plans is now possible.
