### ISSUE TITLE
PGXS environment broken for Postgres installations

### ISSUE THREAD

**Issue by cwelton** [travis-ci/travis-ci#2864]
-> Trying to build and test a Postgres Extension leveraging the postgres PGXS framework.

pg_config identifies the pgxs makefiles in a specific location:

>   $ pg_config --pgxs
>   /usr/lib/postgresql/9.3/lib/pgxs/src/makefiles/pgxs.mk

However when actually trying to build with this fails stating that the pgxs.mk file does not exist:

>  $ make
>  Makefile:44: /usr/lib/postgresql/9.3/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
>  make: **\* No rule to make target `/usr/lib/postgresql/9.3/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

Likewise the postgres extension files seem to be missing:

> $ psql -c "create extension hll" hll_regress
> ERROR:  could not open extension control file "/usr/share/postgresql/9.3/extension/hll.control": No such file or directory

Both of the above indicate that the Postgres environment is not correctly setup.

See: https://travis-ci.org/cwelton/postgresql-hll

**Comment by beyoung** [comment]
Thanks ,that works for me !

**Comment by alexshavelev** [comment]
@cwelton worked! thanks

**Comment by datahacker1** [comment]
Thanks, works for me

**Comment by fwd079** [comment]
@cwelton cheers mate, worked. :+1:  :smile:

**Comment by swayamnayak** [comment]
I am unable to install pg_bulkload on windows box. Its throwing error as pgxs.mk is missing at the ./PostgreSQL/9.4/lib/pgxs/src/pgxs.mk is missing.

process_begin: CreateProcess(NULL, C:/Program Files/PostgresPlus/9.5AS/bin --pgxs, ...) failed.

**Comment by kalpabarbosa** [comment]
@cwelton, funcionou para instalar a extensão cstore_fwd no postgres. Valeu

**Comment by chenzuoli** [comment]
> Resolved with:
> 
> ```yaml
> before_script:
>   - sudo apt-get install postgresql-server-dev-all
>   - sudo apt-get install postgresql-common
> ```

how can i do when i am use the centos7

**Comment by grunmin** [comment]
> > Resolved with:
> > ```yaml
> > before_script:
> >   - sudo apt-get install postgresql-server-dev-all
> >   - sudo apt-get install postgresql-common
> > ```
> 
> how can i do when i am use the centos7

use
```bash
yum install postgresql-devel -y
```
even you use postgresql10 since postgresql10-devel does not create this file.

**Comment by darkdefender27** [comment]
How do we get around the same issue on a Mac :/ (Mojave)

**Comment by steve-estes** [comment]
Just here to note that the AWS-supplied version of postgresql11 from AWS Extras seems to lack pgxs / pgxs.mk from its deployment.  After a bit of wondering whether I was missing something, I discovered there were some `yum` packages available that looked like the ones desired here:

`yum list post*`

`sudo yum -y install postgresql-server postgresql-server-devel`

...and that did the trick.

**Comment by WShihan** [comment]
how to install postgresql-server-devel on win11, any suggestions would be appreciateed

**Comment by saifxd7** [comment]
As @WShihan told, please help me the same!
