### ISSUE TITLE
riak 2.0 support

### ISSUE THREAD

**Issue by bhicks** [travis-ci/travis-ci#2866]
It would be nice to be able to run riak 2.0. There are new features (CRDTs) that prohibit test suites from running on travis, which currently supports riak 1.4.

**Comment by BanzaiMan** [comment]
Riak will be 2.0 during the next build env update. (Some time in February, I reckon, but not exactly sure.)

**Comment by bhicks** [comment]
Awesome, thanks :smile:

**Comment by ctro** [comment]
:+1: Yipee!
