### ISSUE TITLE
Support vimscript language

### ISSUE THREAD

**Issue by dbarnett** [travis-ci/travis-ci#2867]
Some testing tools are available for testing vimscript plugins: https://wincent.com/wiki/Vim_testing_tools. There's no one-size-fits-all approach, but Travis could support "VimL" as a valid language setting and install some common dependencies like a full-featured vim. Could also install neovim and neovim/python-client.

For reference, here's the (slightly hacky) .travis.yml file for google/vim-maktaba: https://github.com/google/vim-maktaba/blob/master/.travis.yml. It uses [google/vroom](https://github.com/google/vroom) and currently requires an active X DISPLAY for vim clientserver support.

**Comment by roidrage** [comment]
While we currently have no immediate plans to support this, it could be provided as a community language: http://blog.travis-ci.com/2014-12-10-community-driven-language-support-comes-to-travis-ci/

I'm closing this issue for now, we do welcome pull requests to the relevant repositories.

**Comment by dbarnett** [comment]
Thanks, "generic" has been working great for me. The linter does accept it now, but FWIW the docs still don't seem to call "generic" out as an option for language.

**Comment by llucax** [comment]
I don't know if this is intended or not, but `generic` seems to have the same effect as using `c` as `language`.
