### ISSUE TITLE
OS X instance: Errno::ENXIO: Device not configured - /dev/tty

### ISSUE THREAD

**Issue by brixen** [travis-ci/travis-ci#2872]
Getting an error running the Rubinius specs that /dev/tty is not configured on OS X. The error can be seen on this run at line 2574: https://travis-ci.org/rubinius/rubinius/jobs/38114630#L2574

As recently as 11 days ago, this was not failing. Apparently, 7 days ago, it was failing: https://travis-ci.org/rubinius/rubinius/jobs/37369712

Nothing has changed in Rubinius or the specs that I know of that would cause this error.

Has something changed with the OS X instance configuration?

**Comment by andschwa** [comment]
@henrikhodne I think the change "The build script is now run in a TTY" has regressed in `osx_image: xcode7.3`. I came across this issue when I ran into a similar problem caused by a lack of a TTY, and verified on the OS X runner:

```
$ tty
not a tty
```
