### ISSUE TITLE
Display friendlier message when there are no builds

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2875]
Currently, the message is:

`There are no builds in this repository.`

https://github.com/travis-ci/travis-web/blob/5dec305cda0d16307a5c4cbc5c175390e5a68ba1/assets/scripts/app/templates/builds/not_found.hbs

We should add a few reminders to:

1. Check that the repository is enabled in settings
1. Push a commit
1. Check the requests page

**Comment by roidrage** [comment]
We rolled this out recently, so I'm closing this, woot!

**Comment by roidrage** [comment]
![activeadmin - travis ci 2015-07-23 18-40-16](https://cloud.githubusercontent.com/assets/5373/8856299/46b1da82-316a-11e5-9c33-245e73c92844.jpg)
