### ISSUE TITLE
Support multiple independent job configurations

### ISSUE THREAD

**Issue by dbarnett** [travis-ci/travis-ci#2877]
Some repositories need to test with several independent jobs that don't have much configuration in common. For instance, a single repository might need to run test suites for python, C, and "generic" languages, each with their own configuration for `matrix`, `env`, `setup`, `install`, `script`, etc. Travis CI should support more than one job configuration per repository.

There should probably still be build-wide fields like `notifications` that wouldn't make sense to configure per-job.

**Comment by ariovistus** [comment]
+1

**Comment by cancan101** [comment]
There seems to be a trends toward monorepos such as Google and [now Facebook](http://gregoryszorc.com/blog/2015/03/28/notes-from-facebook%27s-developer-infrastructure-at-scale-f8-talk/) so having the ability to specify different languages within n repos is important.

**Comment by dbarnett** [comment]
Just checking in here. Looks like this has come up for several other people, too. Any hope for getting it implemented?

**Comment by localheinz** [comment]
:+1:

**Comment by miguelaferreira** [comment]
+1

**Comment by localheinz** [comment]
![q3fls](https://cloud.githubusercontent.com/assets/605483/9497165/fff5517c-4c13-11e5-834e-c2f4017055f6.jpg)

**Comment by bweir** [comment]
Building cross-platform Qt applications. This is a requirement before I can start using the multi-OS feature. +1

**Comment by Joshua-Anderson** [comment]
@bweir It's poorly documented, but you can do this with `matrix.include`

libssl has a good example: https://github.com/libressl-portable/portable/blob/9e090286b55def5ca2c0cc375c65023a70d8796e/.travis.yml

**Comment by bweir** [comment]
@Joshua-Anderson I wanted to let you know that your comment has allowed me to create my whole build infrastructure for PropellerIDE. =D

Look at this glorious thing, all set up. https://github.com/parallaxinc/PropellerIDE/releases/tag/0.32.0

Thanks a lot for that excellent response!

**Comment by chasen** [comment]
+1

**Comment by bweir** [comment]
@Joshua-Anderson I completely forgot to reply to this but that example was hugely helpful. I'm using it for all my projects now.
https://github.com/parallaxinc/PropellerIDE/blob/master/.travis.yml

**Comment by ismay** [comment]
So if I understand correctly crossplatform builds are currently already possible, but cross language builds aren't right? Because for https://github.com/superwolff/metalsmith-in-place I want to run a linter on the latest node version, but my unit tests on multiple node versions. That's not currently possible right?

Reason I'd like to do this is that eslint does not support node < 4. Which means that my builds fail, because eslint doesn't support the same node versions as my unit tests.

**Comment by BanzaiMan** [comment]
As already mentioned, this should be possible with `matrix.include` and its alias `jobs.include`.
