### ISSUE TITLE
Please consider disabling API documentation "warping" behaviour

### ISSUE THREAD

**Issue by kentfredric** [travis-ci/travis-ci#2878]
The present API documentation has a very very annoying quirk in that as you're scrolling down the page, even a single segment, as soon as the heading for the next segment comes into view, the WHOLE segment warps to the top.

Which means to read any text at the bottom of some segments, you have to let it warp to the following segment, then scroll backwards to bring the bottom of the segment ( which is now _above_ your screen ) back into view.

This is very frustrating when scrolling, or even just trying to read the documentation scanning for something relevant, and you get the feeling somebody is nannying you and saying "Hey, you're not smart enough to scroll a page on your own, let me show you how its done", or you have a toddler slapping your face with a fish repeatedly while you're just trying to read a book.

Worse, when you scroll far enough for the "Lint" section to come into view, you can get perpetually stuck below that heading, as all attempts to scroll back up past it has it force you back down.

It is a seriously unpleasant effect and I found myself having to restrain myself with expressing exactly how frustrating that is =)

Repeat:
1. Scroll down to "Accounts"
2. _SLOWLY_ scroll down to Annotations
3. When `Annotations > Attributes` comes into the bottom of the viewport, the document hash changes, and the whole viewport scrolls up so `Annotations` is the new screen top.
4. Slowly scroll up again to accounts
5. When `Annotations > Attributes` falls outside the viewport, the document hash changes, and the entire 'Accounts' section is forcibly scrolled to the top so `Accounts` as the new screen top.

NB. Although it appears that way on that heading on that case, it doesn't appear to be strictly heading related and I'm not sure what is going on, but the effect seems to be a side effect of both each sections size in combination with screen size somehow. Amplifying/Reducing zoom level has no impact on the effect.

**Comment by andrewgross** [comment]
+1 on this, it is infuriating.

**Comment by BanzaiMan** [comment]
Sorry for the delay.

We are now working to get a new version of API out, and with it, a new documentation site. We will take this feedback into account. As a result, we have chosen to not spend efforts on this issue.

Thanks again!
