### ISSUE TITLE
The amount of *swap* (not physical ram) is way too low

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#2904]
The current boxes come up with [4.5GB of total memory](https://travis-ci.org/dbsrgits/dbix-class/jobs/38904324#L78) (3 physical, 1.5 swap). In addition the physical memory is not always fully available, due to some weird issues with the startup (hence [this commit](https://github.com/dbsrgits/dbix-class/commit/fcdd56ca)).

But even if the 4.5 were available at all times - this is not enough for a lot of users out there. Consider:
https://github.com/travis-ci/travis-ci/issues/2721
https://github.com/travis-ci/travis-ci/issues/2606 (incorrectly tagged as duplicate)
https://github.com/travis-ci/travis-ci/issues/2516
https://github.com/travis-ci/travis-ci/issues/2407
https://github.com/travis-ci/travis-ci/issues/2101

And the hard evidence that Pg+MySQL+Oracle+a buildjob is sometimes too much: https://travis-ci.org/dbsrgits/dbix-class/jobs/38904324#L776

Now - if this was a plain linux system - I would just create an extra file, mkswap, swapon and move on. However this is not possible in the openvz containers used - the kernel does not allow the swapon ioctl. One also can not fiddle with the /proc/sys/vm/overcommit_memory setting in order to get proper malloc-failure semantics: once again the kernel does not allow it.

Please, given the [massive amount of space](https://travis-ci.org/dbsrgits/dbix-class/jobs/38904324#L560) available to every build, consider updating the images to come up with at least a 4GB swap space, if not 8GB. Most of your users run resource intensive build environments on these nodes, the 4.5GB with OOM killer enabled is becoming increasingly difficult to work with.

I know there are some intentions to [move off openvz](https://github.com/travis-ci/travis-ci/issues/2105#issuecomment-39406329), but in the meantime the simple fix will make the life of many of your users much much easier.

Thank you in advance

* Note - some of the links in this ticket point to actual travis job logs, and may not navigate to the correct line due to https://github.com/travis-ci/travis-ci/issues/1501

**Comment by TheMarex** [comment]
We frequently run into problems with the swap space as well. Even a build process on a single core can take up more than >4GB of memory. As you might have guessed we compile heavily templated C++ code, thus the large memory footprint.

As a result we currently need to restart about half of our builds because of OOM killer errors.
*Please* bump this up to something more sensible in the area of 8GB. Travis is becoming really unusable for us.

**Comment by DennisOSRM** [comment]
bump

**Comment by jonnew** [comment]
Im running into this issue as well.

**Comment by bilderbuchi** [comment]
seeing the same problems with our C++ builds.

**Comment by ribasushi** [comment]
For anyone following this issue, here is a couple of recipes I use to minimize my memory footprint as much as possible:

* [This shuts off the pre-started databases and moves their datafiles off the ramdrive](https://github.com/dbsrgits/dbix-class/blob/3c26d329/maint/travis-ci_scripts/10_before_install.bash#L5-L15) (explanation in [the commit message](https://github.com/dbsrgits/dbix-class/commit/06278456a))

* [In case MySQL is needed - install a minimized config before restarting](https://github.com/dbsrgits/dbix-class/blob/3c26d329/maint/travis-ci_scripts/10_before_install.bash#L99-L105) (the config can be [found here](https://github.com/dbsrgits/dbix-class/blob/3c26d329/maint/travis-ci_scripts/configs/minimal_mysql_travis.cnf))

The result so far has been a complete elimination of OOMs in all my builds. Feel free to reuse as you see fit.

Cheers!

**Comment by solarce** [comment]
Thanks for sharing @ribasushi. I would encourage those of you who are interested to give our Trusty beta a try, http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/, as the instances are provisioned as a GCE `n1-standard-2`, which has 7.5GB of memory and 2 vCPUs.

But per, http://docs.travis-ci.com/user/trusty-ci-environment/#Environment-common-to-all-VM-images, please note:

> the mega image does not currently contain all the common tools and services present in our Precise images. This is something we’ll be expanding over the next couple of months.

So you may need to add additional setup steps depending on runtime and services needed.

**Comment by joepvd** [comment]
Closing, as this refers to the legacy infrastructure.
