### ISSUE TITLE
VMs running out of disk space?

### ISSUE THREAD

**Issue by myronmarston** [travis-ci/travis-ci#2907]
I'm seeing some RSpec builds fail due to insufficient disk space.  I've never seen this failure before.

https://travis-ci.org/rspec/rspec-mocks/jobs/38944287#L99

```
/home/travis/build/rspec/rspec/.git/refs: No space left on device
```

In https://travis-ci.org/rspec/rspec-mocks/jobs/38944290 it manifested a bit different:

```
compiling gherkin_lexer_ca.c
ragel/i18n/ca.c.rl:453:1: fatal error: error writing to /tmp/ccXAhXjb.s: No space left on device
```

**Comment by meets2tarun** [comment]
Issue still persists and it seems after multiple restarts
https://travis-ci.org/xeon-zolt/meilix/builds/255183213#L952
