### ISSUE TITLE
maven-antrun-plugin tasks output not piped and broken pipes

### ISSUE THREAD

**Issue by Scottmitch** [travis-ci/travis-ci#2917]
I am experimenting with travis CI and am running into some issues.  The project in question (https://travis-ci.org/akamai/netty) is java based and builds with maven.  One of the sub modules runs a few maven-antrun-plugin tasks to get information about the host (ldd version and uname info) and uses this to build a native module.  The issue is that the maven-antrun-plugin commands (which should just be sh commands) are either running into `printf: write error: Broken pipe` errors or I'm not seeing the output being displayed on the console at all (pipe error?).  This parent project has been building for a while on our dedicated CI without issue, and will also build if you pull the project locally (use a newer linux distro to ensure the module in question is being built).

Here is a log with broken pipes:
https://travis-ci.org/akamai/netty/jobs/39340049#L3901

Here is a log where I'm not sure if the second command is run (or perhaps the output isn't piped properly?):
https://travis-ci.org/akamai/netty/jobs/39338869#L3901

**Comment by joepvd** [comment]
Closing.
