### ISSUE TITLE
RVM 2.0.0-p247 fails on Mac worker

### ISSUE THREAD

**Issue by segiddins** [travis-ci/travis-ci#2918]
See https://travis-ci.org/CocoaPods/CocoaPods/jobs/39350517 for the error.
The relevant line in `.travis.yml` is https://github.com/CocoaPods/CocoaPods/blob/master/.travis.yml#L11.
Note that other `rvm` versions do not error.

**Comment by segiddins** [comment]
@BanzaiMan any update?

**Comment by BanzaiMan** [comment]
We have 2.0.0-p576 installed now.

**Comment by segiddins** [comment]
@BanzaiMan this ticket was about 2.0.0-p247, not 2.0.0-p576.

**Comment by jcampbell05** [comment]
Any updates ?
