### ISSUE TITLE
IRC notifications don't work

### ISSUE THREAD

**Issue by purpleidea** [travis-ci/travis-ci#2920]
Seems that IRC notifications aren't working... None of these commits produced a valid IRC message:

https://github.com/purpleidea/puppet-gluster/commit/198d616747ccff61b996e9523fe3d08bd783efb8
https://github.com/purpleidea/puppet-gluster/commit/7bb58159a034fd75e51678aa7c1be1847efe2182
https://github.com/purpleidea/puppet-gluster/commit/d329934e43e468820f07de1464af46044dd75fb1

(They did test successfully though).

**Comment by pjanouch** [comment]
I have set up my own simplistic IRC server, and while I can see in the log that Travis CI connects to the server (and keeps the connection open for a very long time, it seems), no messages are getting through. It is very awkward.

**Comment by purpleidea** [comment]
On Sat, Feb 7, 2015 at 10:34 PM, Přemysl Janouch <notifications@github.com>
wrote:

> I have set up my own simplistic IRC server, and while I can see in the log
> that Travis CI connects to the server (and keeps the connection open for a
> very long time, it seems), no messages are getting through. It is very
> awkward.



If someone can fix this bug, it would be great :)

**Comment by pjanouch** [comment]
I have probably found the problem (just by looking at the source code; didn't know Travis IC was open source). I still might be wrong, but I think it's very unlikely that I am.

In https://github.com/travis-ci/travis-tasks/blob/master/lib/travis/addons/irc/client.rb you use "puts" which doesn't output "\r\n" as required by the IRC protocol, but only "\n". Change it to ```socket.write "...\r\n"``` and then it should start working everywhere.

Some IRC servers tolerate this kind of input but not all of them, e.g. mine doesn't.

**Comment by BanzaiMan** [comment]
@pjanouch Interesting find. Could you point to the protocol documentation for the record?

**Comment by pjanouch** [comment]
@BanzaiMan IRC is defined in RFC 2812 (which supersedes RFC 1459).

> IRC messages are always lines of characters terminated with a CR-LF
> (Carriage Return - Line Feed) pair, and these messages SHALL NOT
> exceed 512 characters in length, counting all characters including
> the trailing CR-LF. Thus, there are 510 characters maximum allowed
> for the command and its parameters.  There is no provision for
> continuation of message lines.  See section 6 for more details about
> current implementations.

**Comment by BanzaiMan** [comment]
@pjanouch Thanks. We'll take a look. Is there a IRC channel I can send notification to? If you don't want to divulge that information here, email it to support@travis-ci.com, please.

**Comment by BanzaiMan** [comment]
@pjanouch Test notification should have fired. Could you confirm that you received it?

**Comment by pjanouch** [comment]
@BanzaiMan unfortunately nothing seems to have come through. I can see some Amazon instances connecting, so there's that, at least.

**Comment by BanzaiMan** [comment]
Deployment actually failed. I'm still testing. Sorry about that.

**Comment by BanzaiMan** [comment]
@pjanouch OK. This time deployment worked, and there should've been a notification. Could you confirm it?

**Comment by pjanouch** [comment]
Yup, got through:
```
       >> │ travis-ci (travis-ci@ec2-54-204-171-231.compute-1.amazonaws.com) has joined #anathema
travis-ci │ travis-pro/test-repo-staging1#26 (master - 7d49167 : Hiro Asari): The build passed.
travis-ci │ Change view : https://github.com/travis-pro/test-repo-staging1/compare/631c887047ee...7d491671aea0
travis-ci │ Build details : http://staging.travis-ci.com/travis-pro/test-repo-staging1/builds/5741
       << │ travis-ci (travis-ci@ec2-54-204-171-231.compute-1.amazonaws.com) has left #anathema (travis-ci)
```

**Comment by BanzaiMan** [comment]
Awesome.

**Comment by BanzaiMan** [comment]
@pjanouch Thanks so much for your help on this.

**Comment by purpleidea** [comment]
On Mon, Feb 9, 2015 at 12:27 PM, Hiro Asari <notifications@github.com>
wrote:

> Closed #2920 <https://github.com/travis-ci/travis-ci/issues/2920> via
> travis-ci/travis-tasks@6f40205
> <https://github.com/travis-ci/travis-tasks/commit/6f40205b641dbca94826573bf52d07f4f76a020e>
> .
>


Sweet. When should I except this patch to be in the public instance (so
that I know when to test IRC again) ?

**Comment by pjanouch** [comment]
It works already.

**Comment by purpleidea** [comment]
On Mon, Feb 9, 2015 at 4:06 PM, Přemysl Janouch <notifications@github.com>
wrote:

> It works already.



Having just tested it, it does not work. I received the email, but no IRC
notification.

Example:
https://travis-ci.org/purpleidea/puppet-ipa/builds/50116227

**Comment by pjanouch** [comment]
Then it is probably a different issue, as several notifications have been successfully delivered to me by IRC. I cannot spot another problem with the IRC module however. Which doesn't necessarily mean that there isn't any.

Wouldn't you have "MODE +n" set on your channel per chance?

**Comment by BanzaiMan** [comment]
The log records a successful delivery.

```
Feb 09 21:21:05 travis-tasks app/tasks.3:  I [task] Successfully notified irc.freenode.net:#freeipa 
```

**Comment by purpleidea** [comment]
Channel had +n mode set, so in addition to the now fixed bug, you also need
to set skip_join: false

This works:
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false

Cheers

**Comment by BanzaiMan** [comment]
@purpleidea Awesome! Do you mind creating a PR for the doc re: `+n` mode switch? That'll be fantastic!

**Comment by purpleidea** [comment]
On Mon, Feb 9, 2015 at 6:58 PM, Hiro Asari <notifications@github.com> wrote:

> @purpleidea <https://github.com/purpleidea> Awesome! Do you mind creating
> a PR for the doc re: +n mode switch? That'll be fantastic!


If you send me a link to the file to edit in the git repo...





...and I think you're asking for a patch ;)

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/docs-travis-ci-com/

**Comment by purpleidea** [comment]
To add some context for someone looking for this:

The n mode stops random bots from messaging in channel.
`/mode -n` to remove the -n mode.
but freenode has mlock to set certain modes...
run `/mode #mgmtconfig` to figure out which modes your channel has set.
and `/msg chanserv info #mgmtconfig` to see your channel mlock.
and finally: `/msg chanserv set #ohmyvagrant MLOCK +tc-slk` to remove -n. The default is `+ntc-slk`

cheers!
