### ISSUE TITLE
Mac OS X 10.10 SDK

### ISSUE THREAD

**Issue by joeydong** [travis-ci/travis-ci#2921]
Does TravisCI have the Mac OS X 10.10 SDK available for use?

We have an app that takes advantage of a method in the new SDK which is causing our builds to fail when linked against the 10.9 SDK

**Comment by meatballhat** [comment]
For the record: as Xcode 6.1 is now the default when building on OSX, there is no special configuration needed to use the 10.10 SDK. :shipit:
