### ISSUE TITLE
Right most column gets cut off on Chrome on Yosemite

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2922]
We received the following feedback:

> Latest chrome. OSX 10.10. 100% zoom.
> The finished column looks cut off and has no option to scroll.
> 
> When right hand bar is expanded the cutoff also leads me to think I can scroll right, but can't.

![travis_sidebar](https://cloud.githubusercontent.com/assets/25666/4844958/a9f2997a-6040-11e4-92f7-51a052372e0b.png)

![travis_no_sidebar](https://cloud.githubusercontent.com/assets/25666/4844963/ae57e6aa-6040-11e4-8a1c-6544bff25bc2.png)

**Comment by roidrage** [comment]
Closing this as this page has gotten a revamp, which also includes touches on this bit, making the UI more responsive, subsequently not cutting off data anymore, or at least phasing it out.
