### ISSUE TITLE
Passing a float to `branches.only` results in silently rejected build request

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2928]
Given

``` yaml
branches:
  only: 2.3
```

(See, for example, https://github.com/cakephp/datasources/blob/3376083/.travis.yml)

We end up with a `NoMethodError` [here](https://github.com/travis-ci/travis-core/blob/8b3b174f568516daecc48ecb46340cf2fb47e8f9/lib/travis/model/request/branches.rb#L32). We reject this request, but there is no clear indication why. (That is another issue.)

**Comment by renatomoya** [comment]
Steps to reproduce this? (Clearly I am not too familiar with the project but I want to help)

**Comment by joshk** [comment]
I have a fix in travis-ci/travis-core@e22b770 nearly ready, just need to merge and deploy
