### ISSUE TITLE
Consider pre-booting android emulator(s)

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/travis-ci#2929]
In order to cut down on average job time, consider creating a default instance of the emulator, pre-installed and pre-runned (as the first run of the emulator is extra slow) instance with enabled snapshot feature.  Furthermore, consider starting such pre-running emulators for API10, API19, and API21.

**Comment by SandroMachado** [comment]
+1

**Comment by vashisthg** [comment]
+1

**Comment by danielpassos** [comment]
+1

**Comment by magneticflux-** [comment]
+1

**Comment by guitcastro** [comment]
+1
