### ISSUE TITLE
Travis-ci sends notification emails to the wrong address

### ISSUE THREAD

**Issue by ljbade** [travis-ci/travis-ci#2943]
In my Mapbox settings I have personal repo notifications set to my primary address (my personal one).

I then have all the mapbox team repos set to go to my mapbox email address via the custom routing settings.

However travis-ci continues to send mapbox notifications to my personal email address.

How do I get travis-ci to send the mapbox notifications to my mapbox email.

**Comment by paroxp** [comment]
It's been a while. Can we get this back on the table?

**Comment by cuzzlor** [comment]
Yeah me too so annoying getting a gazillion notifications sent to my personal email when my work email is set up for this repo.

**Comment by dzuelke** [comment]
Yes please, fix this?

**Comment by rplankenhorn** [comment]
Yes I would like to see this fixed as well.

**Comment by ibash** [comment]
This is lolsy, how is this not possible?

**Comment by knittingarch** [comment]
I also can't believe this isn't an available feature.  Is there any movement on this?  Not familiar with Github's API, but surely there is some way to allow a user to input an alternate email for routing in the interface...
