### ISSUE TITLE
Request to preinstall Android NDK r10c for Android language CI environment

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#2946]
It will be great if the Android NDK can be preinstalled to reduce the build time due to downloading and installing the NDK itself before each build test.

**Comment by noamtamim** [comment]
Last official update on this issue was a year ago. @BanzaiMan wrote they will look into it at a later time.
In my project, installing the NDK takes ~50 seconds, and the actual build takes ~130 seconds.

**Comment by iphydf** [comment]
Tox4j solves the time problem by installing only the strictly necessary parts of the NDK, using p7zip to filter files when extracting. See the [ndk extraction script](https://github.com/TokTok/jvm-toxcore-c/blob/dda69d0558c6348b7979d719a6e23f46de0f7416/buildscripts/01_ndk).
