### ISSUE TITLE
Search bar instead of sync message

### ISSUE THREAD

**Issue by Nijikokun** [travis-ci/travis-ci#2954]
![Sync details](http://dump.nexua.org/Screen_Shot_2014-11-13_at_7.38.02_PM.png)

This box looks like a search bar, and it is not, it would be very efficient and ux friendly to put it here, to search the list below.

**Comment by roidrage** [comment]
We've rolled out updates recently, that changed the look and feel of this part of the UI:

![mathias meyer - profile - travis ci 2015-07-23 18-47-34](https://cloud.githubusercontent.com/assets/5373/8856445/4af5535c-316b-11e5-82c6-558599eddc26.jpg)

As there's no border there anymore which would suggest it's a search box, I'm closing this issue.
