### ISSUE TITLE
'sudo: false' ignores 'os' key (in particular, 'osx' value)

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2957]
Given:

```yaml
sudo: false
os:
  - linux
  - osx
```

we expect to have 2 jobs; one with `sudo: false` on Linux, the other with `os: osx` on OS X. But we only get the former.

If you just have `os: osx` and `sudo: false`, we get the same one.

`sudo: false` is causing `os: osx` to be ignored, and the two jobs are collapsing into the same one, so that we get only one job.

**Comment by ribasushi** [comment]
Has anyone considered promoting `docker-linux` to an `os` in its own right, and then have `sudo: false` implicitly select `os: docker-linux` unless the `os` is already specified?

This way one can construct a single matrix with **some** jobs running with `sudo: false` and hence within a container, and then some others running in an openvz with sudo available (unless this is already possible and I am simply unaware how to go about it)

I personally have a use case for this, where my matrix contains two main "forks" - one is regular testing, one is stress-testing of sorts. The later requires a lot of `apt-get` acrobatics. I assume I am not alone with such a setup.

Thoughts?

**Comment by rkh** [comment]
Might be an option. Our queue selection code is a bit messy right now, we
had some initial issues with adding the educational logic there, too.

**Comment by ribasushi** [comment]
I think I didn't come across correctly. What I was trying to say is that *abstracting* docker into an "os" of its own will likely reduce the level of "mess". That is orthogonal to the usability benefit I described above.

**Comment by joshk** [comment]
I'm :-1: on `docker-linux` or similar.

Personally I prefer allowing people to specify each job and all the bits about the job.

**Comment by ribasushi** [comment]
> Personally I prefer allowing people to specify each job and all the bits about the job.

@joshk ultimately this is what I am after anyway. Here is [an excerpt from my matrix](https://github.com/dbsrgits/dbix-class/blob/34d2deae2/.travis.yml#L83-L96): the `CLEANTEST=true` runs can complete without `sudo`, the other one can't. Currently specifying `sudo` in the matrix is ignored.

The reason I am brought up `docker-linux` or similar is because of the main topic of this ticket - the `sudo` flag clashing with the concept of a different OS (`osx`). Hence the proposal to make it impossible to *request* `docker` with one option, while requesting `osx` (or maybe `windows` wink-wink) with another.

**Comment by fwalch** [comment]
> Currently specifying sudo in the matrix is ignored.

Something like this seems to work:

```yaml
sudo: false
env:
  matrix:
    CI_TARGET=A
matrix:
  include:
    - env: CI_TARGET=B
      sudo: true
```

**Comment by meatballhat** [comment]
This now works, it appears.  Yay accidental feature support!

**Comment by bilderbuchi** [comment]
@meatballhat are you sure this works? If I paste @fwalch's code snippet above into the travis validator, I get "in matrix.include section: unexpected key sudo, dropping".

**Comment by fwalch** [comment]
Maybe it's just a problem with the validator (it also says things like `unexpected key before_cache, dropping`)

**Comment by bilderbuchi** [comment]
OK, so Travis accepts that, and starts a container build. Unfortunately, I need a package, [specified like this](https://github.com/openframeworks/openFrameworks/blob/a1a956b5d0d6dbdd1431a582988f55d33f10dd6f/.travis.yml#L21-L26) (according to [docs](http://docs.travis-ci.com/user/migrating-from-legacy/#Adding-APT-Packages)), but the build [complains](https://travis-ci.org/openframeworks/openFrameworks/jobs/72432680#L128) about "command not found" - how do I verify that the package really got installed?

**Comment by bilderbuchi** [comment]
Validator issue reported: travis-ci/travis-yaml#66

**Comment by bilderbuchi** [comment]
OK, I put my failing build into a separate issue: #4557
