### ISSUE TITLE
Do not start MySQL and PostgreSQL on boot

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2959]
There is some confusion about which services are available on boot, and which are not.

Furthermore, these may be contributing to some memory pressure situations where processes get killed out of nowhere. (These may be Linux bug, but we should mitigate them whenever we can.)

This change is huge, and it will require some planning in terms of announcement, but I think it is one worth considering.

**Comment by joshk** [comment]
I am going to close this issue for now as we are not planning to change this in the next 3-6 months.

**Comment by grooverdan** [comment]
when/if in future you decide to do this, here https://github.com/grooverdan/travis-dbtest is a way to determine if postgresql or mysql was used during the build.

Example: https://travis-ci.org/grooverdan/travis-dbtest
