### ISSUE TITLE
`git stash` fails during deployment

### ISSUE THREAD

**Issue by mrsimonemms** [travis-ci/travis-ci#2960]
I'm trying to make deployments to OpenShift from tags.  Knowing the existing tags deployment bug (https://github.com/travis-ci/travis-ci/issues/1675) I'd set `all_branches:true` and `tags:true`.  However, the deployment still fails.

Looking through the logs (https://travis-ci.org/riggerthegeek/kitbag-api/builds/41031580), it appears to start the deployment but there's an error in the **preparing deployment** section.  From line 1383:

```
Preparing deploy
authenticated as riggerthegeek
found app kitbagapi
Generating public/private rsa key pair.
Your identification has been saved in .dpl/id_rsa.
Your public key has been saved in .dpl/id_rsa.pub.
The key fingerprint is:
ea:b6:d0:c9:d1:e2:a8:16:cc:76:d4:9e:55:fb:71:8a testing-worker-linux-9-2-9206-linux-14-41031581
The key's randomart image is:
+--[ RSA 2048]----+
| |
| . |
| . . . |
| . ... . . . |
| o . .ooS o + |
| = .=o= E o |
| . oo * |
| .. o. |
| .. .o. |
+-----------------+
/usr/lib/git-core/git-stash: 186: /usr/lib/git-core/git-stash: cannot create /home/travis/build/riggerthegeek /kitbag-api/.git/logs/refs/stash: Directory nonexistent
```

The final line is where it gets an error.  As it refers to the .git/logs/refs/stash folder, I'm getting that I might need to do something in the _pre_deploy_ section - does anyone have any ideas?

**Comment by stefanbuck** [comment]
I get the same error! Did you solved this issue in the meantime?

**Comment by riggerthegeek** [comment]
No.  I bravely gave up on OpenShift as it works fine for ages then just stops working for a myriad of different reasons (and none of them good).

**Comment by project-vrum** [comment]
Getting this issue all of a sudden too.

**Comment by mrowles** [comment]
+1 getting this issue seemingly all of a sudden also.

**Comment by riggerthegeek** [comment]
To the best of my knowledge, no fix has been attempted by Travis or a workaround offered.  As said above, I've decided against using OpenShit as my PaaS and used Bamboo for my deployments which, as you have to configure it yourself, offers fine-grain control

**Comment by lijunle** [comment]
I am getting the same error when deploy to Azure, here is the [log](https://travis-ci.org/lijunle/depcheck-www/jobs/92777400#L578).

**Comment by jaraco** [comment]
I also am getting the error, but not always. When I tried to replicate the behavior, I couldn't. Every time I tried to check for the existence of .git/logs/refs, it [was present](https://travis-ci.org/jaraco/jaraco.financial/jobs/167942664), even though when I wasn't checking, the [error was reported](https://travis-ci.org/jaraco/jaraco.financial/jobs/167938927). I don't have a lot to add, but when I do, I'll report back here.

**Comment by letmaik** [comment]
Same error: https://travis-ci.org/letmaik/lensfunpy/jobs/224718122#L941

**Comment by BanzaiMan** [comment]
Is this still a consistent problem for anyone?

We could try inserting a command to ensure that `.git/logs/refs` is created with the user ownership before cleanup happens.
