### ISSUE TITLE
HHVM LTS

### ISSUE THREAD

**Issue by GrahamCampbell** [travis-ci/travis-ci#2961]
Would it be possible to `hhvm-lts` available as well as `hhvm` and `hhvm-nightly`.

lts: 3.3.1
stable: 3.4.0
nightly: 3.5.0-dev

**Comment by ClemensSahs** [comment]
:+1: for Majkl578

**Comment by fredemmott** [comment]
how about '3.3', '3.6' (LTS, ~ 1 year), and just 'stable' instead of specifying which non-LTS you wish to use. While 'stable' would still move, this would be equivalent to the current situation.

**Comment by nicolas-grekas** [comment]
Any solution allowing to play with several versions of HHVM would be awesome!
