### ISSUE TITLE
Preinstall openjdk-8-jdk and openjfx packages on java images

### ISSUE THREAD

**Issue by schildbach** [travis-ci/travis-ci#2968]
It would make it easier to compile Java8 code against OpenJDK on Travis.

**Comment by gildegoma** [comment]
I've asked the maintainers of `openjdk-r` PPA if the addition of JavaFX 8 is planned for the Precise platform, and will keep you informed. Both (`openjdk8` and `openjfx`) packages are planned to be added to `trusty-backports`, but it is not done yet.

@BanzaiMan what about introducing  with `openjdk8` without JFX ?

**Comment by jawnsy** [comment]
It'd be nice to get OpenJDK 8 and OpenJDK 9 (latter is in Debian experimental, not sure about Ubuntu). I saw that OpenJDK 8 was [removed from the docs awhile back](https://github.com/travis-ci/travis-ci/issues/1647), but it looks like this issue is for adding it back :)

[OpenJDK 9 early access builds](https://jdk9.java.net/jigsaw/) are also available. These can be handy for people that want to try the new JDK 9 features or just make sure that their projects still compile under Java 9.

**Comment by gildegoma** [comment]
Maybe good to know:

* OpenJDK 8 is already available on the [Trusty Beta environment](http://docs.travis-ci.com/user/trusty-ci-environment/#JVM) (with JavaFX support).

* An OracleJDK "9 Early Access" installer package is [available thanks to Webupd8Team PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/java). I've started to work on a pull request to propose to add this JDK version to the preinstalled stuff of the JVM build environments... but in the meantime you can easily install it on the Tusty Beta and Precise Legacy environment [with a few instructions in your `.travis.yml`](https://github.com/gildegoma/travis-ci-inspector/blob/54595ecd31475285f59864d9bf9e7b7935018b37/.travis.yml#L5-L8) as [demonstrated here](https://travis-ci.org/gildegoma/travis-ci-inspector/builds/86151353#L210)

**Comment by gildegoma** [comment]
@jawnsy I've prepared the pieces to introduce `oraclejdk9` (see https://github.com/travis-ci/travis-cookbooks/pull/587). Travis core team will decide when it makes sense to preinstall it, but as explained above you already can install it during the build.

**Comment by koppor** [comment]
@gildegoma Did you change something in the Trusty Beta environment? We [switched to it](https://github.com/JabRef/jabref/commit/98baefe2b023), but [the build fails](https://travis-ci.org/JabRef/jabref/jobs/101143676):

    $ jdk_switcher use openjdk8

    Sorry, but JDK 'openjdk8' is not known.

    The command "jdk_switcher use openjdk8" failed and exited with 1 during .

**Comment by dschuermann** [comment]
We also need OpenJDK 8 to compile our own fork of Bouncy Castle (Oracle JDK requires you to sign Java Crypto Providers). See https://github.com/open-keychain/open-keychain/pull/1915

**Comment by neugens** [comment]
I've read a couple of comments that state, or imply, that  "JFX is part of Java 8". Unfortunately, this is not true. JavaFX is not part of Java 8, as can be seen from the Java 8 JSR: https://jcp.org/en/jsr/detail?id=337. OpenJFX is a JEP, and a project sponsored by the Swing Group, but that doesn't make it part of Java 8 either: http://openjdk.java.net/projects/openjfx/

**Comment by kno10** [comment]
Oracle actually end of life'd Java 7.

So openjdk-8 should even become the _default_ (as the default Java on most Linux distributions); but at least it should become _available_...

**Comment by BanzaiMan** [comment]
OpenJDK 8 is available now on Trusty images. It is unlikely that we add it to Precise images, so if you want OpenJDK 8, please use Trusty.

JavaFX is a separate issue; if you want it, please open a separate issue.

**Comment by mokun** [comment]
If I don't want to do a parallel testing of using (1) Oracle's official JDK and (2) OpenJDK with OpenJFX, how should I specify that in my .travis.yml ?

Currently, I have the following : 

```
language: java
dist: trusty
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
- oraclejdk10
- openjdk10
addons:
apt:
packages:
- oracle-java10-installer
cache:
directories:
- $HOME/.m2
after_success:
- mvn coveralls:report
```

The oraclejdk10 portion works fine, but the openjdk10 portion fail because it can't find any javafx packages. 

How do I specific the openjfx package when loading openjdk10 part of the test ?
