### ISSUE TITLE
local-dir should be local_dir in .travis.yml s3 deploy options.

### ISSUE THREAD

**Issue by ramaboo** [travis-ci/travis-ci#2972]
On http://docs.travis-ci.com/user/deployment/s3/ you describe the local-dir option for S3 deployments. Shouldn't it be local_dir (underscore vs dash) as all the other options (and YML in general) use the underscore style.

**Comment by BanzaiMan** [comment]
It is normalized to one, iirc. Either way, I've fixed this with https://github.com/travis-ci/docs-travis-ci-com/commit/ec72446.
