### ISSUE TITLE
HHVM >= 3.3.0 and Xdebug

### ISSUE THREAD

**Issue by jails** [travis-ci/travis-ci#2980]
Hi,

Since Xdebug has been included in HHVM 3.3.0, I tried to add in my travis config file:

```
before_script:
  - echo 'hhvm.xdebug-not-done.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
```

I followed the indications I found in [the documention](http://docs.travis-ci.com/user/languages/php/#Custom-PHP-configuration) but I get stuck on the following error:

```
The command "echo 'hhvm.xdebug-not-done.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini" failed and exited with 1 during .
```

Is the name of the config file is different for HHVM environment ? Am I missing something here ?

Thanks !

**Comment by garwat82** [comment]
Had the same issue when trying to set "short_open_tags = 0" which is required when "<?xml ... ?>" is used in one of the files.

**Comment by BanzaiMan** [comment]
Does HHVM even allow customization this way? You can't modify `/etc/hhvm/php.ini` on container-based workers at the moment, but if HHVM does not afford any other means of customization, perhaps changing the owner of this file to `travis` is acceptable.

**Comment by garwat82** [comment]
@BanzaiMan Yes, that would be help for sure!

**Comment by BanzaiMan** [comment]
Please test this. Thanks.

**Comment by garwat82** [comment]
Don#t know why but it made no difference: https://travis-ci.org/aimeos/arcavias-core/jobs/47031215

**Comment by BanzaiMan** [comment]
@garwat82 `echo "short_open_tags = Off" >> /etc/hhvm/php.ini` succeeds (https://travis-ci.org/aimeos/arcavias-core/jobs/47031215#L242) Your test failure appears to come from the code coverage task, which, as far as I can tell, is quite different.

**Comment by garwat82** [comment]
The test fails because of the "<?xml ... ?>" header in the file that causes the fatal error. This was the reason I was looking for a workaround to disable PHP short open tags for HHVM.

Unfortunately, changing /etc/hhvm/php.ini has no effect as is doesn't seem to be used for the HHVM builds.

**Comment by till** [comment]
@garwat82 That file should be used by HHVM. At least according to [docs](http://docs.hhvm.com/manual/en/configuration.file.php) and so on.

Can you add something like this in your build:

```php
<?php var_dump(ini_get('short_open_tag')); ?>

**Comment by garwat82** [comment]
Done in https://travis-ci.org/aimeos/arcavias-core/jobs/47574725:
[exec] short_open_tag:
[exec] bool(false)

Seems like /etc/hhvm/php.ini isn't used

**Comment by jails** [comment]
yup same here, seems `/etc/hhvm/php.ini` isn't used as the HHVM config file.

**Comment by jails** [comment]
My bad since version > 3.3.0 `hhvm.xdebug-not-done.enable` has been renamed in `xdebug`. So adding the following in the script make it work as expected ! Thanks for your help !

```php
if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
```

**Comment by garwat82** [comment]
The short_open_tag problem seems to be a bug HHVM.
Issue is opened: https://github.com/facebook/hhvm/issues/4758
