### ISSUE TITLE
Active build count graph on status. looks wrong

### ISSUE THREAD

**Issue by alex** [travis-ci/travis-ci#2986]
![screen shot 2014-11-25 at 11 19 20 am](https://cloud.githubusercontent.com/assets/772/5187762/046e6a38-7495-11e4-98b5-02ca4b9104c6.png)

The blue line is above the "400" line, but the count says 321. Seems like one of these numbers must be wrong.

**Comment by joshk** [comment]
Closing this issue for now as it has become stale.
