### ISSUE TITLE
Ruby 2.2.0-preview1 in OSX machines

### ISSUE THREAD

**Issue by deivid-rodriguez** [travis-ci/travis-ci#2987]
I'm specifiying

    rvm:
      - 2.0.0
      - 2.1
      - 2.2
      - ruby-head

And it's failing for `2.2` in OSX because it can't find the Ruby installation.  In #2816 it is mentioned that `2.2.0-preview1` is installed in the OSX VMs so maybe it's just the link from `2.2` to `2.2.0-preview`1 that's not properly configured?

Thanks!

**Comment by deivid-rodriguez** [comment]
@mpapis I just tried this and it still can't match `2.2.0-preview1` to `2.2`.

    davidr@pantani:~/Proyectos/byebug$ rvm --version
    rvm 1.26.7 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
    davidr@pantani:~/Proyectos/byebug$ rvm list

    rvm rubies

       ext-ruby-2.3.0dev-r49059 [ i686 ]
       ruby-2.0.0-p598 [ i686 ]
    => ruby-2.1.5 [ i686 ]
     * ruby-2.2.0-preview1 [ i686 ]
       ruby-head [ i686 ]

    # => - current
    # =* - current && default
    #  * - default

    davidr@pantani:~/Proyectos/byebug$ rvm use 2.2
    ruby-2.2.0 is not installed.
    To install do: 'rvm install ruby-2.2.0'
    davidr@pantani:~/Proyectos/byebug$

The abilitty to autocomplete to preview and rc versions is really minor and nobody will ever need this until `2.3.0-preview1`, but just wanted to let you know. :wink: 

Closing as this is definitely not a travis issue.

**Comment by mpapis** [comment]
@deivid-rodriguez travis uses `--fuzzy` flag, try:
```bash
rvm use 2.2 --fuzzy
```

**Comment by deivid-rodriguez** [comment]
Nice, didn't know that one. :open_mouth: 

Thanks for your patience, I'm learning a lot!

**Comment by mpapis** [comment]
you can make it permanent with:
```bash
echo rvm_fuzzy_flag=1 >> ~/.rvmrc
```
I had it for some time although ended up removing it, using `--fuzzy` when I do not have time to install exact ruby version and there is similar one (patchlevel difference for `1.8`-`2.0`, teeny version difference for `2.1`+)

**Comment by deivid-rodriguez** [comment]
:+1:
