### ISSUE TITLE
Travis CI for forked golang projects

### ISSUE THREAD

**Issue by shashidharatd** [travis-ci/travis-ci#2988]
I am facing an issue, where i have forked a golang project from the mainline in github. Travis CI for the mainline repo works fine. but my travis ci build fails. The reason being the package imports in golang. 
Is there any way we can make this work?

**Comment by MikeRalphson** [comment]
For other people finding this issue, you can also set the `go_import_path` explicitly in your `.travis.yml' file.

See https://docs.travis-ci.com/user/languages/go#Go-Import-Path
