### ISSUE TITLE
`travis-lint` does not detect that `deploy` is not an array of hashes

### ISSUE THREAD

**Issue by wei2912** [travis-ci/travis-ci#2991]
For my repository at [blog_src](https://github.com/wei2912/blog_src), it appears that I get the following [error](https://travis-ci.org/wei2912/blog_src/builds/42329638):

```
Using worker: worker-linux-10-2.bb.travis-ci.org:travis-linux-5

An error occurred while compiling the build script: no implicit conversion of Symbol into String

Test your configuration file with http://lint.travis-ci.org.
```

I tested my [configuration file](https://github.com/wei2912/blog_src/blob/master/.travis.yml) with `travis-lint` and it appears to pass flawlessly.

**Comment by destijl** [comment]
+1 for picking this up in the linter, I just ran into it too.

**Comment by garethahealy** [comment]
+1 updating linter to check 'deploy'
