### ISSUE TITLE
Extract number of tests passed from build output

### ISSUE THREAD

**Issue by gwenzek** [travis-ci/travis-ci#2992]
Most of travis-build includes some kind of unit-testing. Most of unit-testing tools outputs some statistics about the number of test passed. 

Could it be possible to extract this information from the build output (maybe through a regex provided by the user) and summarize it in a new column to the 'build history' tab ?

This would allow to see easily which commit breaks unit-tests, and which fixes them.
Sometimes the one-bit information pass/failed is not enough.

(Maybe this idea already has been suggested, but I didn't find it in the issues.)

**Comment by leandro-lucarella-sociomantic** [comment]
> As for #239, this is our preferred option and will be looking to integrate it with 'build artefacts' next year.

"next year" :)

Anyway, I guess this was completely dropped or is it under the radar still?

**Comment by rkh** [comment]
It is on the radar, as in we've keep bringing it up as a potential future project, but we're not working on anything related at the moment.

**Comment by cxbrooks** [comment]
See [@icyphy/github-issue-junit](https://github.com/icyphy/github-issue-junit) for a hack that, from travis, reads the ant junitreport output from GitHub pages and appends the results to an issue.  Collaborators can then subscribe to the issue to get JUnit summary information.

This is definitely a hack, more could be done to make the code robust and more featureful.

Based on a suggestion by @nebgnahz,  I extended  the work of @vitalets ([github-trending-repos](https://github.com/vitalets/github-trending-repos/)) to create [@icyphy/github-issue-junit](https://github.com/icyphy/github-issue-junit)

I can't comment on [bug #239 Handle Ant's JUnit XML formatted output from test/spec runs](https://github.com/travis-ci/travis-ci/issues/239), so I commented here and on [bug #3042 Allow more complex test reporting](https://github.com/travis-ci/travis-ci/issues/3042)
