### ISSUE TITLE
"Failed to query the list of test cases in the test bundle"

### ISSUE THREAD

**Issue by hkellaway** [travis-ci/travis-ci#3001]
hello --

i've been getting the error message `Failed to query the list of test cases in the test bundle` periodically with my Travis build. i originally posted about it in Issue #2179, but that Issue is closed. So, I'd like to re-open to see if I can get this resolved.

here is my `.travis` file:

```
language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
  - xctool test -workspace RRiOSApp/RRiOSApp.xcworkspace -scheme RRiOSApp -sdk iphonesimulator8.1
```

Failing build is [here](https://travis-ci.org/RefugeRestrooms/refuge-ios/builds/42924879)

anyone have a clue why?

**Comment by wenzhishen** [comment]
@hkellaway , did @ankurp 's solution work for your issue? Mine is still anoying me.

**Comment by BanzaiMan** [comment]
Seems like xctool is to blame here. Could you try switching to xcodebuild?

**Comment by couchdeveloper** [comment]
Seems to be broken again.:

```
script:
- xcrun xctool -project Foo.xcodeproj -scheme Foo -sdk iphonesimulator run-tests
```

xctool v0.3.1 runs flawlessly on my machine.
