### ISSUE TITLE
travis.yml: need more control to help developer to skip a build

### ISSUE THREAD

**Issue by brownman** [travis-ci/travis-ci#3005]
## option 1:
- Edit on github ->  commit message will contain: 
  by default: '[skip-ci]'
## option2
- add a travis.yml a scope related to conditional building based on regular expression

example:
- I want to enable a travis-build only if commit message contains: [enable ci]

**Comment by paulsapps** [comment]
The problem I find is that some one will simply edit readme.md a few times and trigger a ton of pointless builds.

**Comment by malinoff** [comment]
I use appveyor to test on Windows. Their config file allows me to specify a regex to skip commits like this:
```yaml
skip_commits:
  message: /.*\[skip appveyor\].*/
```
So any commit message contains `[skip appveyor]` will trigger TravisCI's build, but not Appveyor's.
It would be useful to have such feature for Travis to trigger vice versa.

I know about `[skip ci]`, but it won't work in my case (if I need to trigger only Windows build).

**Comment by paulsapps** [comment]
That sounds like a good idea, a filter for messages and maybe for files or file paths? So anything under ./docs won't trigger a build for example

**Comment by slawekjaranowski** [comment]
**+1** for rexp filter on message commit and files paths

**Comment by justinmchase** [comment]
Appveyor also allows you to skip based on author.

    skip_commits:
      message: /^v[0-9]/
      author: ci

It would be nice to support skipping by author as regexp so you could skip _all_ excepted the matched author as well.

**Comment by jbaruch** [comment]
Huge :+1: on that, specially by author.

**Comment by sushihangover** [comment]
+1 for rexp filter on message commit

**Comment by dankan1890** [comment]
**+1** for rexp filter on message commit and files paths

**Comment by anuragkapur** [comment]
+1 for filtering based on author. The java/maven based CI process that I have currently gets into a never ending loop of builds when using the maven release plugin that commits back to the repo.

**Comment by sagikazarmark** [comment]
:+1: Would be great with StyleCI

**Comment by vors** [comment]
:+1:

**Comment by vors** [comment]
Currently there is no way to test windows build on AppVeyor, but skip linux build in Travis.  AppVeyor has a distinguishable tag `[skip appveyor]`, but trevis doesn't https://www.appveyor.com/docs/how-to/skip-build

**Comment by stackedvbadmin** [comment]
I'd very much like the install script to be able to make the decision as to whether the build would proceed (in my case I want to make the decision based on the branch name). If an install script failure caused a silent abort (ie skip) of the build I'd have the necessary control.

If this is considered a misuse of the install script, then perhaps an optional check script (preceding the install script) could be created.

**Comment by jsmaniac** [comment]
It is possible to call `travis_terminate 0` to cause the whole job to be skipped.

This seams to be an undocumented feature, searching for [site:https://docs.travis-ci.com "travis_terminate"](https://www.google.fr/search?q=site%3Ahttps%3A%2F%2Fdocs.travis-ci.com+"travis_terminate") on google returns no results.
