### ISSUE TITLE
Alternate syntax for IRC channels no longer working

### ISSUE THREAD

**Issue by akerl** [travis-ci/travis-ci#3009]
Back when notification code existed inside the travis-core repo, I submitted https://github.com/travis-ci/travis-core/pull/355 to add "server.net#channel,key" syntax. This allows multiple channel keys for multiple channels and also resolved the issue which is now being tracked in #2813, where channel keys and other IRC notification parameters do not support encryption via `travis encrypt`. I've had a long thread with TravisCI support about this issue, and they directed me here to open an issue.

I'd be to make a PR to fix this, but it looks like my prior patch was ported over to the new repo:

https://github.com/travis-ci/travis-tasks/blob/master/lib/travis/addons/irc/task.rb#L54-L55

I can't find a way for me to test this to see why the code isn't working, and so far the TravisCI team hasn't provided any kind of error message or debugging information.

**Comment by akerl** [comment]
Any news here?

**Comment by joshk** [comment]
@BanzaiMan I see you merged in the PR, has this been deployed to Hub and Tasks?

**Comment by BanzaiMan** [comment]
It should be. It was merged a while ago. If it's not effective, then there are other things to consider.

**Comment by joshk** [comment]
That is very cryptic :)
Could we look into this later this week?

**Comment by akerl** [comment]
@joshk To be clear, are you referring to a *new* PR? https://github.com/travis-ci/travis-core/pull/355 was merged forever ago and then some change on Travis's end (seems to be when addons were reworked) broke it. If there's a new PR, is there somewhere I can take a look at what the change is that my original code was missing?

**Comment by joshk** [comment]
@akerl sorry for the confusion, I wasn't referring to a new PR, just that we need to investigate why this isn't working anymore.

**Comment by akerl** [comment]
Ping?
