### ISSUE TITLE
Error in pusher and no updated data retrieved

### ISSUE THREAD

**Issue by dmathieu** [travis-ci/travis-ci#3011]
On travis-ci.com, I often get the following error:
![b4ffyd0caai8cy6](https://cloud.githubusercontent.com/assets/9347/5380023/56f5d776-8095-11e4-830d-d6fbeb43af8a.png)

When this happens, I don't get updated data in the build, which forces me to reload entirely the page to see when it's finished.

**Comment by dmathieu** [comment]
I'm still getting that error quite frequently.
![](https://www.dropbox.com/s/1mmv898v01esrym/Screenshot%202015-03-13%2018.01.40.png?dl=1)

**Comment by joshk** [comment]
I believe this issue has been fixed. I'm going to close it for now, but if you are still experiencing it please let us know and we can bump it up the chain.
