### ISSUE TITLE
[Feature Request] Make it possible to support user keys for definitions (useful for exclude).

### ISSUE THREAD

**Issue by LionsAd** [travis-ci/travis-ci#3025]
Use case:

I currently use:

```
env:
  global:
    SOME_VAR=1
  matrix:
    VAR_1="A" VAR_2="X"
    VAR_1="B" VAR_2="Y"
    VAR_1="C" VAR_2="Y"
```

But the exclude feature only works with the exact same lines, so I can't do:

```
matrix:
  exclude:
     - php: 5.3
       VAR_2="Y"
```

but need to repeat the two lines.

What would be nice to do is:

```
matrix_user_vars:
  - var_1
  - var_2

var_1:
  - A
  - B
  - C

var_2:
  - X
  - Y

```

and have then:

```
TRAVIS_USER_VAR_1 = "A|B|C"
TRAVIS_USER_VAR_2 = "X|Y"
```

automatically set.

This could internally be just put in env= and show up the same in the admin interface, but being able to specify it in that way makes things more flexible for different combinations of custom environment variables.

**Comment by roidrage** [comment]
I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
