### ISSUE TITLE
Add support for older versions of xctool

### ISSUE THREAD

**Issue by guidomb** [travis-ci/travis-ci#3027]
It would be nice to be able to choose a specific version of xctool to be used. The current option is use the one provided by travis ci or update to the lastest one. There is no reliable way to install a specific version of xctool. I tried homebrew/versions but it does not have xctool.

I propose that travis ci support the last N versions and gives the posibility to the users to install other versions of xctool and then activate it via the `brew switch` command.

**Comment by solarce** [comment]
Since we rely on homebrew to install xctool, we could potentially support this if you were able to get it added to https://github.com/Homebrew/homebrew-versions. It's not something we'd be able to take on supporting through some kind of custom scripting though.

**Comment by BanzaiMan** [comment]
xctool is no longer supported by Facebook, so I'm closing this.
