### ISSUE TITLE
Non-unique travis build number

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#3028]
We have noticed sometimes Travis-CI may generate builds with non-unique travis-build-number (the human readable one). Fortunately, the internal travis-build-id is still unique despite this issue. See: https://travis-ci.org/urho3d/Urho3D/builds. The last occurrence as of this writing is build number 2648. It appeared thee times.

Here is our use case. In our project we have one master branch (as per usual) and three more CI branches (differs from master branch by one commit which altered the content of .travis.yml so that the Travis CI build jobs run on different OS environment than master branch). We have setup our build in such a way that when master branch's HEAD is moved, it eventually triggers a git rebase on these three CI branches. These CI branches are then pushed to GitHub in a closed for-loop. This subsequently triggers Travis-CI, but although Travis-CI assigns them different internal build ids, it from time to time fails to assign them unique build number.

**Comment by custotestor** [comment]
same issue today:

https://travis-ci.com/custotestor/NoraUi/jobs/273190281 so I use https://api.travis-ci.org/v3/job/273190281/log.txt

But travis CI API return an other project: https://travis-ci.org/Bartosz-D3V/Notes-App/jobs/273190281

why travis-CI return not unic job id (273190281)?
