### ISSUE TITLE
Retrying hung builds

### ISSUE THREAD

**Issue by henryanand** [travis-ci/travis-ci#3031]
Occasionally some of the Vitess integration tests hang and get terminated with the following error message.

"No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself. The build has been terminated"

Is there a way to retry the build when it hangs? We are already running with travis_retry but that doesn't help.

https://github.com/youtube/vitess/blob/travis-ci/.travis.yml
https://travis-ci.org/youtube/vitess

**Comment by BanzaiMan** [comment]
Automatically restarting a build that hangs consistently is not practical. And there is no way to tell from our vantage point if the hang is consistent or just a hiccup.
