### ISSUE TITLE
Certificate issue with Python 2.7.9

### ISSUE THREAD

**Issue by astrofrog** [travis-ci/travis-ci#3032]
The following minimal repository:

https://github.com/astrofrog/travis_certificate

produces a build that fails:

https://travis-ci.org/astrofrog/travis_certificate/builds/44017535

This is related to changes in Python 2.7.9:

https://www.python.org/dev/peps/pep-0476/

As described in that PEP, it indicates issues with the machine's ability to check certificates (so it is making explicit errors that were hidden before). Does anyone have any idea how to fix certificate-checking on Travis when using the latest version of Python?

**Comment by dstufft** [comment]
This is probably because of https://github.com/ContinuumIO/anaconda-issues/issues/228

**Comment by BanzaiMan** [comment]
Thanks, @dstufft. For now, I'm closing this as an upstream issue. @astrofrog, if you discover evidence to indicate there is something we should do, let us know.
