### ISSUE TITLE
Logs get over 4MB due to progress bars

### ISSUE THREAD

**Issue by letmaik** [travis-ci/travis-ci#3034]
The actual online log is pretty small: https://travis-ci.org/esa/auromat/jobs/44099748 But when you download the log you see that there are lots and lots of lines just updating progress bars. Apparently travis ci uses the raw log for checking the max log limit. However it should use the same as what's displayed online, and actually also store just that. Who cares about control codes and progress bars?

**Comment by jakirkham** [comment]
Yeah, have to agree. This seems unnecessarily restrictive.
