### ISSUE TITLE
C# support, mono, and PCL Profile328

### ISSUE THREAD

**Issue by csMACnz** [travis-ci/travis-ci#3036]
Ive just setup [this build](https://travis-ci.org/csmacnz/BCLExtensions/builds/44171101) for my PCL library, and it seems to be failing because it can't find Profile328 of the PCL.  Not sure what to try, since its running Mono, Version 3.10.0.0, and according to [this site](http://lastexitcode.com/projects/NuGet/PortableProfiles/) it should be in 3.10, any suggestions/solutions other people have used with PCLs?

cc @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
@csmacnz The PCL reference assemblies should now be correctly installed, can you try and close this issue when it works?

**Comment by nterry** [comment]
Indeed, It looks like the PCL is included in the MDK, not the MRE. It also
appears that the Xamarin packages are only MRE-based...

**Comment by BanzaiMan** [comment]
Closing, as this has become stale. If there is anything more to do, let us know.
