### ISSUE TITLE
Issue: It's not possible to start Android emulators (api19+) on Docker workers

### ISSUE THREAD

**Issue by ardock** [travis-ci/travis-ci#3037]
Google released a second revision of android-21 and new extras revisions
to support Android Wear 21 the next day VM were updated on December 2014. 
And released new system images (e.g sys-img-armeabi-v7a-android-wear-21) but
I don't propose include it until a possible disk space issue (docker) be solved.

Unzipped versions of system images 19+ are close to 1Gb and a temporal 0,5Gb file is
duplicated when emulator is created. Two system images of this type were added last month
and now it's difficult to update other components or use emulator for android19+ without work arounds.

Different errors manifestate the disk space issue:

* NAND: could not write file /tmp/android-travis/emulator-RHC31V, No such file or directory
* NAND: could not write file /tmp/android-travis/emulator-UVyLkW, File exists
* (Installing  a new component)  Unzip failed: No space left on device
* Error: Update ADB failed Error: No space left on device
* NAND: could not write file /home/travis/.android/avd/.../userdata-qemu.img, No such file or directory

See [Related stackverflow question](http://stackoverflow.com/questions/5604951/no-space-left-on-device-android)
See [Related android documentation](http://developer.android.com/tools/devices/emulator.html#diskimages)
See [Related issue](https://travis-ci.org/ardock/iosched/builds/44118507)
See [Related work around](https://travis-ci.org/ardock/iosched/jobs/44098724#L30)

I would appreciate an official solution or help to check disk space or possible removable folders to gain space. I'm not familiar with docker or VM space limitations.

There is a fast and bad solution, no include 19+ system-images but I propose (in the case I'm not wrong) to valorate an alternative solution as cache the zips (only 200Mb) or try to reuse the original user_data.img without duplicate it (using command arguments). I'm thinking a work around.

Four images to compare sizes (note system.img and user_data.img sizes and the size before and after unzip):

![sysimg_armv7a-18_r02](https://cloud.githubusercontent.com/assets/1142360/5456085/553927c0-8541-11e4-8829-be939b40382d.png)

![sysimg_armv7a-19_r02](https://cloud.githubusercontent.com/assets/1142360/5456093/62f461d6-8541-11e4-9af0-57909232d548.png)

![sysimg_wear_arm-20_r04](https://cloud.githubusercontent.com/assets/1142360/5456098/699bb246-8541-11e4-80ef-f058346ae94c.png)

![sysimg_wear_arm-21_r01](https://cloud.githubusercontent.com/assets/1142360/5456101/702dc2d4-8541-11e4-882c-c1697fc98aae.png)

**Comment by BanzaiMan** [comment]
Is this still an issue with the latest update?

**Comment by ardock** [comment]
I don't know because I'm not currently using your service. 

I requested a new SDK tools update, I'll try next time you update workers, I close this by now.
