### ISSUE TITLE
Exclude rules for caching

### ISSUE THREAD

**Issue by oehme** [travis-ci/travis-ci#3039]
I just tried caching the ```.gradle``` folder to speed up my builds. Unfortunately, Gradle writes ```.lock``` files in that directory, so Travis will always detect a change and repackage the cache, which takes quite some time. It would be nice if I was able to exclude certain file patterns from a directory.

**Comment by BanzaiMan** [comment]
Could you try removing the `.lock` file after the successful build?

**Comment by oehme** [comment]
Yes, I guess that is a good workaround.

**Comment by rkh** [comment]
I think this would be a useful feature nonetheless.

**Comment by BanzaiMan** [comment]
Hello! We have an experimental version of the caching utility that is smarter about file change detection. Do you mind testing it?

If you are interested, add the following to `.travis.yml`:

```yaml
cache:
  branch: md5deep # <= new!
  ⋮
```

**Comment by oehme** [comment]
Sure, but could elaborate a little on what that line does? :)
Am 02.07.2015 15:19 schrieb "Hiro Asari" <notifications@github.com>:

**Comment by BanzaiMan** [comment]
@oehme Sure thing.

It uses a different branch of the caching utility (https://github.com/travis-ci/casher/tree/md5deep), which uses `md5deep` to compare the files' md5 checksums rather than time stamps to determine if the files in question changed or not.

You can see the difference here: https://github.com/travis-ci/casher/compare/production...md5deep

**Comment by oehme** [comment]
It correctly detects that nothing has changed, but there is a problem with
my build it seems:

At the beginning it says "could not download cache" and at the end I get
"nothing changed". As a result, no cache is created ever again.

See https://travis-ci.org/oehme/xtend-contrib/builds/69707290

2015-07-02 15:59 GMT+02:00 Hiro Asari <notifications@github.com>:

**Comment by joshk** [comment]
Ohhh, this is odd and interesting.

I guess the question is, is `~/.gradle` being used?

Can you add a `after_script` step which confirms the contends of `~/.gradle`?

**Comment by oehme** [comment]
Yes, .gradle is being used, see for instance line 106.

**Comment by oehme** [comment]
In [this previous build](https://travis-ci.org/oehme/xtend-contrib/builds/62347903#L88), it correctly detected that ".gradle is not yet cached"

**Comment by joshk** [comment]
@BanzaiMan this definitely looks like an issue with first time cache upload, can you please look into this?

Thank you @oehme for pointing us to this.

**Comment by BanzaiMan** [comment]
Hi, @oehme, I pushed a possible fix to the `md5deep` branch. Could you restart https://travis-ci.org/oehme/xtend-contrib/builds/69707290 and see if it uploads the cache?

**Comment by oehme** [comment]
Yes, the cache is now uploaded again. But now I'm back to changes being
detected every time. Is there a way to get more logging about which files
changed?
Am 06.07.2015 17:28 schrieb "Hiro Asari" <notifications@github.com>:

**Comment by BanzaiMan** [comment]
@oehme The new branch is now deployed to production (so you can drop `cache.branch`).

I am not familiar with how gradle works. Does it write files with different names on each invocation?

I've also deployed the change to casher which will display which files changed with respect to checksums. Could you push a new commit and see what's going on?

**Comment by oehme** [comment]
Thanks for that change, there are indeed a few files in there that will
change their content. For instance there is a .log file.

I guess I'll have to be more selective about the cached directories or I
will need the originally proposed filters.

2015-07-07 20:52 GMT+02:00 Hiro Asari <notifications@github.com>:

**Comment by BanzaiMan** [comment]
Thanks for the update. I'm closing this issue now.
