### ISSUE TITLE
Allow more complex test reporting

### ISSUE THREAD

**Issue by dguido** [travis-ci/travis-ci#3042]
I'm working on a library with about 200 unit tests, and I want to see the pass/fail status of each unit test individually reported on every build. Our test runner outputs the results of each unit test to an XML file (the junitreport file format that Jenkins understands). Travis could have an optional addon that, when a test output file is specified, sucks it up and displays a test matrix.

Example test output: https://code.google.com/p/googletest/wiki/V1_7_AdvancedGuide#Generating_an_XML_Report

There are storage concerns for Travis, but you could limit the filesize to a modest amount (example: 1k per build) or make it a pro-only feature.

**Comment by cxbrooks** [comment]
See [@icyphy/github-issue-junit](https://github.com/icyphy/github-issue-junit) for a hack that, from travis, reads the ant junitreport output from GitHub pages and appends the results to an issue.  Collaborators can then subscribe to the issue to get JUnit summary information.

This is definitely a hack, more could be done to make the code robust and more featureful.


Based on a suggestion by @nebgnahz,  I extended  the work of @vitalets ([github-trending-repos](https://github.com/vitalets/github-trending-repos/)) to create [@icyphy/github-issue-junit](https://github.com/icyphy/github-issue-junit)

I can't comment on [bug #239 Handle Ant's JUnit XML formatted output from test/spec runs](https://github.com/travis-ci/travis-ci/issues/239), so I commented here.
