### ISSUE TITLE
sudo: false generates errors in the logs when starting services (redis, mongodb, elasticsearch)

### ISSUE THREAD

**Issue by peterhellberg** [travis-ci/travis-ci#3044]
The builds are green, but we get some error output in the logs when Travis-CI is starting the databases.

**Worker**: worker-linux-docker-f9ca5b07.prod.travis-ci.com:travis-linux-2
**Build image provisioning date and time**: Sat Dec 13 12:46:32 UTC 2014
## Log output when sudo is disabled

```
$ sudo service mongodb start
* Starting database mongodb
$ sudo service elasticsearch start
* Starting Elasticsearch Server it: error setting limit (Operation not permitted) error: permission denied on key 'vm.max_map_count'

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.

See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

Setting environment variables from .travis.yml
```

**Comment by FractalizeR** [comment]
Well, why to keep false warnings?

**Comment by joshk** [comment]
Sorry, can you explain what you mean by false warnings?

**Comment by FractalizeR** [comment]
I'm sorry, may be I should have opened a new issue for this. But some features of Travis use sudo even in containtered environment. Using redis service for example. We have the following output in our build:

```
sudo service redis-server start
redis-server start/running, process 2180
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
```

[.travis.yml](https://github.com/fhteam/laravel-cache-redis-extended/blob/master/.travis.yml)

**Comment by joshk** [comment]
The warning about the container based infrastructure and sudo not being available is after redis is started, meaning, we don't remove sudo until after we start redis.

This warning needs to be displayed in my opinion, but where it is displayed may change in the future.

**Comment by FractalizeR** [comment]
Well, I don't understand then what is this warning about? I am a user of Travis, I am told, that sudo does not work in container-based infrastructure. Yet Travis uses it itself and shows me an error about that fact. What should I think? ;)

**Comment by joshk** [comment]
It isn't an error, it is a notice to let you know that sudo is not available.

I understand your point that this is opt in, but this also makes others aware of the fact, eg. people who chance across your project and send you a PR might want to know why sudo doesn't work?

**Comment by FractalizeR** [comment]
Ah, I see. Thanks.
