### ISSUE TITLE
Code Sign error: seen on Travis but not happening on my local machine

### ISSUE THREAD

**Issue by hironmoypaul** [travis-ci/travis-ci#3047]
This is my .travis.yml 

language: objective-c

before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool

xcode_sdk: iphonesimulator

script:
    - xctool -workspace cam-pro.xcworkspace -scheme cam-beta build

I am seeing the error below on Travis only.Not happening on my local machine

 ✗ Check dependencies (1 ms)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Check dependencies

Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “XVT8K7BYMV” were found.

CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

2 errored, 0 warning (1 ms)

Failures:

0) Check dependencies

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Check dependencies

Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “XVT8K7BYMV” were found.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

** BUILD FAILED ** (48994 ms)

**Comment by marciok** [comment]
I had the same error, try to import a development cert/key and your team prov. profile on your script
ex:

```shell
#!/bin/sh


KEY_CHAIN=ios-build.keychain
security create-keychain -p travis $KEY_CHAIN
# Make the keychain the default so identities are found
security default-keychain -s $KEY_CHAIN
# Unlock the keychain
security unlock-keychain -p travis $KEY_CHAIN
# Set keychain locking timeout to 3600 seconds
security set-keychain-settings -t 3600 -u $KEY_CHAIN

security import ./scripts/certs/dist.cer -k $KEY_CHAIN -T /usr/bin/codesign
security import ./scripts/certs/dev.cer -k $KEY_CHAIN -T /usr/bin/codesign

security import ./scripts/certs/dist.p12 -k $KEY_CHAIN -P abc123  -T /usr/bin/codesign
security import ./scripts/certs/dev.p12 -k $KEY_CHAIN -P abc123  -T /usr/bin/codesign

```

**Comment by hironmoypaul** [comment]
Using this fixed the problem for me

- xctool -workspace cam-pro.xcworkspace -scheme cam-beta clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

**Comment by xohozu** [comment]
@hironmoypaul It helps me. Thx!

**Comment by paulbruneau** [comment]
@marciok you have saved me! I am following the directions at https://www.objc.io/issues/6-build-tools/travis-ci/ and they said nothing about needing dev credentials. But sure enough, I have added them and it's building.

**Comment by jeeftor** [comment]
Can the Code Signing stuff be enabled in an .xctool-arg

**Comment by gabrielPeart** [comment]
@hironmoypaul Thank you! Your suggestion help me!

**Comment by janderson-primary** [comment]
@marciok I'm confused by your suggestion, can you please help me?

I'm following the same guid as @paulbruneau, and it says nothing about needing dev credentials.  Additionally, dev credentials (cert/key) would be necessary for a debug build, but I am trying to create an Ad Hoc distribution build.  As such, you need a distribution cert and key, not developer.

Can you explain your situation, and why using developer cert/key worked?  I assume you were not building a distribution build for testing?

**Comment by marciok** [comment]
Hi @janderson-primary, 
I'm sorry but I don't know why the dev cert is needed.
Check your code signing options at your project.

**Comment by davidquon** [comment]
Not sure if CocoaPods is being used but if it is this might help https://github.com/CocoaPods/CocoaPods/issues/3198#issuecomment-131115253.
