### ISSUE TITLE
Mysql dramatically slower compared to postgres on new docker container based images

### ISSUE THREAD

**Issue by andrerom** [travis-ci/travis-ci#3049]
The [blog post](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) on this explained that mysql & postgresql is now _not_ running on memory filesystem.

However during testing this we're experiencing a small speedup of both unit tests and integration test using postgresql, while mysql builds are dramatically slower; going from 7-9 minutes to more than 1 hour..

Links:
- PR for using containers: https://github.com/ezsystems/ezpublish-kernel/pull/1120
- 2 builds after switching (PR) to contiainer env: [1](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/44736397) [2](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/44737910)
- 2 builds before change to contianer env: [1](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/44563070) [2](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/44555939)

Any possibility to improve this by default, or document how we can tune it on our side?

**Comment by andrerom** [comment]
Any news on this?

**Comment by BanzaiMan** [comment]
Sorry, but no updates. General feeling is that I/O intensive tests are slower on the containers. Until we can figure this out, you might consider moving the MySQL job to allow_failures, then turn on fast_finish, so that the slow build does not lengthen the feedback loop. (http://docs.travis-ci.com/user/build-configuration/#Fast-finishing)

**Comment by andrerom** [comment]
Ok, thanks for the feedback, I'll consider the workaround.

What surprised me was that we did had positive impact with postgresql (exactly same tests!), which is why I partly assumed this was issue on the mysql container itself and not docker.

**Comment by mattab** [comment]
Hello Travis,

Fyi: at Piwik we spent fair amount of time making changes to use new `sudo:false`  infrastructure, and then we noticed the builds were slower and timing out because Mysql does not run off the RAM. So we reverted to the old infrastructure :-) https://github.com/piwik/piwik/issues/9146

**Comment by andrerom** [comment]
@mattab You are not the only one, been waiting to use the newer trusty infrastructure, and as of last week it seems to be ready to be used: https://github.com/travis-ci/docs-travis-ci-com/issues/396

**Comment by andrerom** [comment]
@BanzaiMan Seems after move to GCE this issue is also affecting `precise`, any:
- input on what changed?
- tips on how to tune mysql on travis so we can just as well move to trusty?
- upcoming changes planned to improve this?

Now: https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/125799668 *(takes around 30-50min, will most likly time out during your afternoon rush)*
Legacy infra: https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/89636174 *(8min)*

**Comment by andrerom** [comment]
*Context: We are in the middle of deciding about going all in on Travis-ci for our commercial repos, or all out because of issues like this and missing communication on when to expect new infra to be out of beta for instance.*

**Comment by BanzaiMan** [comment]
Once a job starts running, the system usage does not affect how fast it runs. Each job is run on individual VM on GCE.

One possible explanation for the slowness is that MySQL (or other software) requires decent amount of entropy, but there isn't enough in `/dev/random`.

The JRuby team reports good results using [`haveged`](http://packages.ubuntu.com/precise/haveged): https://github.com/jruby/jruby/wiki/FAQs#why-is-jruby-so-slow-to-install-via-rvm.

Could you try that?

**Comment by BanzaiMan** [comment]
It might be due to the absence of `tmpfs`. See https://github.com/solarce/piwik/commit/f7bf16fdb30fa5dbd162ffdb22de594337750d0a#diff-354f30a63fb0907d4ad57269548329e3R139

**Comment by mattab** [comment]
Confirmed, running mysql off RAM (https://github.com/piwik/travis-scripts/commit/864d684487c0cb8ee2e05b9f88dc42f55a4afb62) has fixed the performance issue :+1:

**Comment by BanzaiMan** [comment]
So, this issue was opened for containers, but has since evolved into one for GCE.

We still don't have effective workaround for containers, but perhaps we can close this, with "use GCE and `tmpfs`" as a workaround?

**Comment by andrerom** [comment]
I'll test today

**Comment by andrerom** [comment]
Works.

So then this is a doc issue, here is what I have on my side:

Specifically for trusty:
```
# Mysql isn't installed on trusty (only client is), so we need to specifically install it
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
```

Both:
```
    # make sure we don't run out of entropy apparently (see link above)
    sudo apt-get -y install haveged
    sudo service haveged start
    # make tmpfs and run MySQL on it for reasonable performance
    sudo mkdir /mnt/ramdisk
    sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
    sudo stop mysql
    sudo mv /var/lib/mysql /mnt/ramdisk
    sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
    sudo start mysql
```


----

This does not solve the afternoon slow down however *(When US wakes up)*.

**Comment by kwiliarty** [comment]
I had a job that was topping 50 minutes (and timing out) when using PHP7 and MySQL. Using the workaround in the previous comment that job now finished in 15 minutes. It ends up being a strong incentive to use the `sudo: required` architecture.

**Comment by edmorley** [comment]
travis-ci/travis-cookbooks#888 would help with this
