### ISSUE TITLE
Directory caching is broken for Go builds

### ISSUE THREAD

**Issue by mislav** [travis-ci/travis-ci#3055]
Setup:

```
language: go
cache:
  directories:
    - vendor/bundle
```

Respecting this directive, Travis sets out to cache this directory

```
~/build/OWNER/REPO/vendor/bundle
```

So far so good, except that this is not the actual final build directory, because Go project get rsync'ed to a location in GOPATH:

```sh
export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/OWNER/REPO
cd $HOME/gopath/src/github.com/OWNER/REPO
```

The actual build will happen there, and any build artefacts that get created will have gone undetected by Travis cache system because at the end of the build, it will take a peek inside `~/build/OWNER/REPO` and decide that nothing has changed.

**Comment by BanzaiMan** [comment]
Hmm. This seems like an issue with the user setup, no? We do not do anything special for Go builds with respect to caches. Users are expected to know which directories to cache. If Go expects to find cache in `~/gopath/src/github.com/OWNER/REPO`, then that's the directory that should be cached.

I believe you can use:

```yaml
cache:
  directories:
    - $HOME/gopath/src/github.com/$TRAVIS_REPO_SLUG
```

**Comment by mislav** [comment]
Thank you for the workaround, but I don't feel that this is a problem with user setup. In project configurations for other languages, configuring a directory `foo/bar/` to get cached means that this directory within the project's root directory will get cached. In Go builds, this configuration will silently fail to cache anything.

**Comment by BanzaiMan** [comment]
Ah, I see! Indeed, the problem is on `travis-build`. Sorry for the roundabout.

https://github.com/travis-ci/travis-build/commit/473d4153205866a271412318dbd24bfc0ed5d82b is the commit that made this change.

The description of the original issue that motivated this change follows (we've since disabled issues on travis-build, so it's not accessible):

> Currently the Go builder clones the repo to `~/build/user/repo` and sets the `GOPATH` to `~/gopath`. This means that if I have subpackages from my repo imported like `github.com/user/repo/subpackage`, `go get` will clone the repo into `$GOPATH/src/github.com/user/repo` and use the subpackages from the master branch of the second clone. The result is that there can be revision mismatches when building revisions other than master.
> 
> The solution is to clone into `$GOPATH/src/github.com/user/repo` the first time and build there, removing the redundant clone.
> 
> I'm happy to write a patch for this, but I'm not sure what the best way to pass the clone path into the git clone step is. Alternatively, the setup step of the build can `mv` the directory into the correct spot.

**Comment by BanzaiMan** [comment]
It seems to me that this difference with Go builds seems rather substantial. Perhaps we should just document this difference and advise Go users to set up caches accordingly.

**Comment by mislav** [comment]
> Perhaps we should just document this difference and advise Go users to set up caches accordingly.

Or maybe if Travis is going to `cd` to another directory before the build process starts, relative paths such as `directories: vendor/bundle` could get resolved with the new directory as base, not the old one?

**Comment by BanzaiMan** [comment]
That is also possible. I suspect it might be the best solution here.

**Comment by mislav** [comment]
Note that per my above comment, a symlink instead of the rsync operation might be both the simplest and most thorough solution. For instance, it would solve the caching problem without having to amend cache code.

**Comment by BanzaiMan** [comment]
@mislav https://github.com/travis-ci/travis-build/commit/59d589a7a30301c8076eee5ddaf18318a9e092a2 is the commit that introduced `rsync`. I don't know enough about the issue at hand to comment. I'll defer that to @meatballhat (who's on vacation right now).
