### ISSUE TITLE
Build Error for Rubinius

### ISSUE THREAD

**Issue by ecleel** [travis-ci/travis-ci#3056]
Hi,

I have an Ruby open source project called [hijri](https://github.com/ecleel/hijri) and I use travis ci for testing it in multiple ruby versions and implementations. Yesterday Rubinius (rbx) start to fail building the environment. you can check the job here https://travis-ci.org/ecleel/hijri/jobs/45059774

NB I try rbx and rbx-2 with no luck.

**Comment by paddor** [comment]
I think this bug came back from the dead. I'm encountering the same: https://travis-ci.org/paddor/czmq-ffi-gen/jobs/102737652

**Comment by BanzaiMan** [comment]
@paddor I don't think `rubinius` is ever intended to work with RVM. I'm sure you need `rbx` instead. See https://github.com/rvm/rvm#implementation.

**Comment by paddor** [comment]
@BanzaiMan Oh I see. I've been using `rubinius`, but on the legacy platform, which worked fine. I'll change it to `rbx` and retry. Thanks!

**Comment by paddor** [comment]
Yep, using `rbx` does the trick. Thanks again. :-)
