### ISSUE TITLE
Bintray as deployment target?

### ISSUE THREAD

**Issue by jbaruch** [travis-ci/travis-ci#3057]
Hi guys,
Do you have any plans to support Bintray as a deployment target (similar to your support of github-releases)?

We see increasing number of questions "How can I deploy to Bintray from Travis-CI?".
At the moment we provide them with a script to run, but it would be nice to have it out of the box.

**Comment by jweaver** [comment]
Hey guys, was there any resolution to this?  I'm interested in the same thing.  I noticed https://github.com/travis-ci/dpl/issues/160 is a very similar issue, but there was no conclusion.  Is it a matter of writing a new provider (https://github.com/travis-ci/dpl/tree/master/lib/dpl/provider) to handle the bintray API?

**Comment by Joshua-Anderson** [comment]
@jweaver Yes. If. Somebody can find a CLI for bintray, they just need to write a provider that wraps it.

**Comment by eyalbe4** [comment]
We will soon submit a pull request for a Bintray provider at dpl.
We have one question though:
We are testing the new provider on dpl locally. Is there a way to test it on Travis to make sure it works properly?
Thanks!

**Comment by Joshua-Anderson** [comment]
After your code is merged, you can test it before general availability by adding `edge: true` to your `.travis.yml`.

**Comment by eyalbe4** [comment]
Pull request has been submitted:
https://github.com/travis-ci/dpl/pull/255

**Comment by saulshanabrook** [comment]
PR has been merged and is available now: https://github.com/travis-ci/dpl/pull/259#issuecomment-118131046
