### ISSUE TITLE
PyPi deploy marked successful although it failed

### ISSUE THREAD

**Issue by m1keil** [travis-ci/travis-ci#3058]
Hey, 
I'm sorry in advance if this is a dupe, I remember very clearly reporting about this before but can't seem to find it now.

It looks like PyPi deployment marked as OK even though it returned non zero exit code. For example, trying to deploy a version that's already exists in the repo will lead to error, but Travis will ignore it.
Here is an example: https://travis-ci.org/m1keil/test_travis_deploy/builds/39254689

Note the `Upload failed (400)` message.

Am I missing something in the process or it's a bug?

Thanks!

**Comment by cyberb** [comment]
I have the same problem with error 500, but travis build.is green. Very confusing.
Register failed:
https://travis-ci.org/syncloud/platform/builds/57113847#L366
Upload failed:
https://travis-ci.org/syncloud/platform/builds/57113847#L572

**Comment by kaste** [comment]
Bump! https://travis-ci.org/kaste/mockito-python/jobs/125267636#L426

Please comment about the status of this issue. It's from Dez 2014 already.

**Comment by RonnyPfannschmidt** [comment]
this basically means travis is silently unreliable for release automation,
if you cant fix it at least document it -_-

**Comment by BanzaiMan** [comment]
A variation of #2679, which in turn is a variation of https://github.com/travis-ci/dpl/issues/143.

**Comment by BanzaiMan** [comment]
Closing as a duplicate.
