### ISSUE TITLE
Create a ccache bucket

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#3061]
It's fairly easy to cache compilation of C programs using ccache and configuring travis to cache the /home/.ccache directory but some predefined defaults like turning on compression and setting the compression level would be nice. See the configuration [here](http://ccache.samba.org/manual.html#_configuration_settings).
I assume that ccache is not installed by default so it should be.
Enabling it should be done by:
```yaml
cache:
  - ccache
```

**Comment by BanzaiMan** [comment]
We can add the `cache: ccache` shortcut. `ccache` will have to be added to the cookbooks.

**Comment by thedrow** [comment]
Thank you!

**Comment by chrisdembia** [comment]
+1

**Comment by chrisdembia** [comment]
Super eager for when I can use this with `sudo: false` (our repo is public).

This would speed up our tests by a factor of 5; we spend most of the time compiling c++ code.

**Comment by thedrow** [comment]
@BanzaiMan You labeled this issue for C/C++. ccache can also cache Ojbective-C/Objective-C++ compilation objects. FYI.

**Comment by thedrow** [comment]
@BanzaiMan If it's implemented and documented I think this issue should be closed.
