### ISSUE TITLE
Please update App::cpanminus in perl image.

### ISSUE THREAD

**Issue by kentfredric** [travis-ci/travis-ci#3064]
I've started noticing a recurring SEGV issue with cpanminus that happens with certain modules. 

Importantly, on the docker targets, ( for instance, `worker-linux-docker-7fbdd350.prod.travis-ci.org:travis-linux-6`  ), And on Perl 5.10.1 , which has `App::cpanminus` version `1.7021`

That specific version unfortunately has a known problem with `SEGV` on `5.10.1` :(  https://github.com/miyagawa/cpanminus/issues/421 

And this is resolved in [1.7022](https://metacpan.org/source/MIYAGAWA/App-cpanminus-1.7022/Changes#L3)

**Comment by BanzaiMan** [comment]
@kentfredric Could you confirm that the update earlier this month fixed this issue?

**Comment by kentfredric** [comment]
`cpanm (App::cpanminus) version 1.7024 (/home/travis/perl5/perlbrew/bin/cpanm)`.

And a test on 5.10.1 omitting my "force upgrade" trick appears to install and pass.

So I think that fixes this issue. =)
