### ISSUE TITLE
Cleanup not occurring / HEAD detached generating 1000+ log lines for heroku deployment

### ISSUE THREAD

**Issue by cwphobia** [travis-ci/travis-ci#3065]
Example:
https://magnum.travis-ci.com/tastemade/tastebase3/builds/8308583

At the end of our heroku deployments, a `HEAD detached` message occurs, followed by upwards of 1300 lines of "changes not staged for commit" in the logs.  The deployment appears to complete successfully, but the noise makes it a pain to get to the relevant parts of the deployment log.

Suspicion is that the deployment is not cleaning up (ref. #3020), but I don't know for certain.

**Comment by cwphobia** [comment]
Where would I set that git config?  In the `before_deploy` section of .travis.yml where I had to add `git fetch --unshallow`?

**Comment by BanzaiMan** [comment]
@cwphobia Yes, that would be a reasonable place to put it.

**Comment by cwphobia** [comment]
That change did not appear to make a difference:

https://magnum.travis-ci.com/tastemade/tastebase3/builds/8426838

**Comment by lllpsi** [comment]
We are having a similar problem. How do we fix this?

**Comment by BanzaiMan** [comment]
@cwphobia @lllpsi Hmm. Could it be that these messages are coming from Heroku, then?

**Comment by BanzaiMan** [comment]
Any update? I'm closing this for now. If you are continuing to see this problem, please open a new issue.
