### ISSUE TITLE
Not all files are cached

### ISSUE THREAD

**Issue by probonopd** [travis-ci/travis-ci#3073]
I my .travis.yml file I am setting a matrix with 4 different URLs which I would like to cache (SDKs for 4 different platforms); however, it appears that only 1 of the 4 is actually cached.

https://github.com/probonopd/announce/blob/master/.travis.yml

Wouldn't it a better idea to cache downloads on an URL basis, i.e., have a "cached-wget" command that tries to retrieve files from a local (shared for all travis-ci users and projects) cache, and only downloads from the Internet if the cache doesn't return the requested file?

**Comment by roidrage** [comment]
No, I was saying that our cache isn't suitable for the kind of files you want to store in it.

**Comment by probonopd** [comment]
Thank you for the clarification.
