### ISSUE TITLE
Any update on using Ubuntu 14.04 as the Linux OS?

### ISSUE THREAD

**Issue by Arnavion** [travis-ci/travis-ci#3074]
(#2046 is locked so I have to ask in a new issue like this.)

#2046 has had no new info since October. Is there any update or planned timeline on using 14.04 as the Linux OS for the build machines?

We at [HexChat](https://github.com/hexchat/hexchat) would like to start using glib >= 2.36 instead of the two-year-old 2.32 that 12.04 has, but if we can't do that with Travis we'll start looking at making our own build servers.

cc @TingPing

**Comment by roidrage** [comment]
There's no official update yet, sorry. We'll have something on our blog and [our build environment announcement list](http://docs.travis-ci.com/user/build-environment-updates/) when we're ready.

**Comment by microcai** [comment]
too said, ubuntu 12.04 is not even supported any more.
