### ISSUE TITLE
go tip is set to 1.4

### ISSUE THREAD

**Issue by jonlawlor** [travis-ci/travis-ci#3076]
When using a go build, if you indicate the version to be tip:
```yml
language: go

go:
 - tip
```

The builder reports that it is using version 1.4, instead of the expected `go version devel +9ef10fde754f Thu Dec 11 16:32:25 2014 +1100 darwin/amd64` (or something to that effect).  Perhaps gvm is using an outdated cache?

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/builds/45741914#L101-L104

```
$ gvm install tip --binary || gvm install tip
Installing tip from binary source
ERROR: Failed to download binary go from http://golang.org. Trying https://storage.googleapis.com
ERROR: Failed to download binary go
Installing tip...
 * Compiling...
```

Seems like gvm should do better getting `tip` installed. Could this be related to Go's move to GitHub? I'm guessing this issue is related https://github.com/moovweb/gvm/issues/111.

Once the gvm issue is fixed, we can roll out a build environment update.

**Comment by meatballhat** [comment]
This should be working correctly now with the switch to `gimme`.  Please yell if otherwise and I'll reopen!

**Comment by jonlawlor** [comment]
@meatballhat, it seems like `release` is not working:

https://travis-ci.org/gonum/stat/jobs/49237718

```
$ eval "$(gimme release)"
I don't have any idea what to do with 'release'.
  (using type 'auto')
$ export GOPATH=$HOME/gopath:
$ export PATH=$HOME/gopath/bin:$PATH
$ mkdir -p $HOME/gopath/src/github.com/gonum/stat
$ rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/gonum/stat/
$ export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/gonum/stat
$ cd $HOME/gopath/src/github.com/gonum/stat
$ gimme version
v0.2.2
$ go version
/home/travis/build.sh: line 41: go: command not found
go.env
```

**Comment by meatballhat** [comment]
@jonlawlor there is no tag named `release` afaict :confused:

**Comment by meatballhat** [comment]
```
➜  go git:(master) git remote -v
origin  https://github.com/golang/go.git (fetch)
origin  https://github.com/golang/go.git (push)
➜  go git:(master) git rev-parse HEAD
3c0fee10dbe82771dcaa956a95bdfabdced5fff7
➜  go git:(master) git tag | grep release
release.r56
release.r57
release.r57.1
release.r57.2
release.r58
release.r58.1
release.r58.2
release.r59
release.r60
release.r60.1
release.r60.2
release.r60.3
```

**Comment by jonlawlor** [comment]
OK, then I'll just switch to explicit go version numbers + tip.  Thanks for fixing!

**Comment by meatballhat** [comment]
@jonlawlor or any other valid tag, for that matter! :-D

**Comment by jonlawlor** [comment]
So, uh, what is `gimme` coming from?  I can't seem to find it.

**Comment by BanzaiMan** [comment]
https://github.com/meatballhat/gimme
