### ISSUE TITLE
C# - NuGet causes segfault/times out occasionally

### ISSUE THREAD

**Issue by Robmaister** [travis-ci/travis-ci#3077]
It works most of the time, but every once in a while the `nuget restore SharpNav.sln` in [my .travis.yml](https://github.com/Robmaister/SharpNav/blob/master/.travis.yml) causes issues in 1/4 of the jobs in my build matrix and makes my project's shield appear as "Error" instead of "Passing" or "Failing".

For example, this one causes a segfault in Mono:

https://travis-ci.org/Robmaister/SharpNav/builds/45588331

And this one times out when trying to download packages:

https://travis-ci.org/Robmaister/SharpNav/builds/45588727

Other than that, really good job on the C# support!

/cc @joshua-anderson @akoeplinger @nterry

**Comment by Joshua-Anderson** [comment]
Hmmm. We should add retry code to NuGet. Travis CI has had strange timeout issues and the like for a while now, so retrying was added to the other package managers a while ago.

**Comment by akoeplinger** [comment]
Yeah, the timeout is likely something with the Travis CI infrastructure, a retry would solve that (since you invoke nuget yourself, you can just prepend it with `travis_retry`).

I'm a little bit concerned about the segfault as that would obviously be a Mono bug. I think you only ran into this once, right? I've never seen it segfaulting on nuget before, so might be a pretty rare race condition.

**Comment by Robmaister** [comment]
Yeah, it looks a bit worrisome but since it's only happened once and under the same conditions as the timeout, I'm guessing it's some race condition that exists somewhere in the code that handles a timeout or something like that. If it happens again I'll open up another issue and try to investigate a bit.

I'll go ahead and prepend `travis_retry`, thanks for the tip!

**Comment by Mailaender** [comment]
We added https://github.com/OpenRA/OpenRA/pull/7216 and https://github.com/OpenRA/OpenRA/pull/7235 but sadly this timeout still occurs very often. AppVeyor does not seem to be affected.

**Comment by akoeplinger** [comment]
@Mailaender yeah, that is unfortunate, but I don't think we can do anything in the C# support for this, it seems to be a an issue in the Travis infrastructure.

One thing you could try is to add `sudo: false` to your .travis.yml. This means that the build will get routed to the [new Docker-based infrastructure](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) that runs on EC2 (which hopefully doesn't have those timeouts). You'd need to get your build working without `sudo` though.

**Comment by Mailaender** [comment]
Sadly we require `sudo` for dependency installation on deployment. https://github.com/OpenRA/OpenRA/blob/bleed/.travis.yml#L37 Is it possible to have `sudo: false` conditionally as in use Docker for pull requests and the legacy system for the few deployment builds?

**Comment by akoeplinger** [comment]
@Mailaender Hmm, I don't think you can do that. Maybe it's possible to install the dependencies without sudo (see http://askubuntu.com/questions/339/how-can-i-install-a-package-without-root-access)? Should be easy for markdown as it has not dependencies, but might be more difficult for nsis (dpkg should be installed by default).
