### ISSUE TITLE
CSharp Compiling Error

### ISSUE THREAD

**Issue by jaredbroad** [travis-ci/travis-ci#3078]
I think there's an error copying the build output? The solution builds fine in Windows & Mono on my desktop. Thank you :)

@joshua-anderson @akoeplinger @nterry

/home/travis/build/QuantConnect/Lean/QuantConnect.Lean.sln (default targets) ->
(Build target) ->
/home/travis/build/QuantConnect/Lean/Engine/QuantConnect.Lean.Engine.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (PostBuildEvent target) ->
	/usr/lib/mono/4.5/Microsoft.Common.targets: error : Command 'rem copy algorithm to output directory
echo f | xcopy "/home/travis/build/QuantConnect/Lean/Engine/bin/Release/../../../Algorithm/bin/Release/*" "/home/travis/build/QuantConnect/Lean/Engine/bin/Release/" /y' exited with code: 127.
	 33 Warning(s)
	 1 Error(s)
Time Elapsed 00:00:10.6394870
The command "xbuild /p:Configuration=Release QuantConnect.Lean.sln" exited with 1.
Done. Your build exited with 1.

**Comment by akoeplinger** [comment]
@jaredbroad `rem` is a comment in a Windows batch file, and xcopy is a Windows tool for copying. Both of these make no sense on Linux.

**Comment by jaredbroad** [comment]
Got it :) Thank you
