### ISSUE TITLE
travis command line utils alters .bashrc without notification, breaking things.

### ISSUE THREAD

**Issue by shevett** [travis-ci/travis-ci#3079]
When the travis-ci gem is installed, it automatically adds this line to the users ~/.bashrc/:
# added by travis gem

[ -f /Users/(username)/.travis/travis.sh ] && source /Users/(username)/.travis/travis.sh

First, this shouldn't happen without it prompting the user to ask if this is okay.  Adding 88k of code to every shell on a users machine without prompting is fairly rude behaviour.

Secondly, the entry is formatted wrong, and will cause login errors.  On many Mac computers, usernames frequently have spaces in them, which will cause an error similar to this:

-bash: [: /Users/dave: binary operator expected

I'd suggest an environment setup mechanism for the travis command line.  IE, if you run the 'travis' command and the environment is not loaded, source it then, not everytime the user starts a terminal.

**Comment by rkh** [comment]
Hm. Which version are you running? The travis gem should prompt the user asking for permission to modify the .bashrc.

**Comment by shevett** [comment]
Daves-MacBook-Pro:~ dave shevett$ travis --version
1.7.4

**Comment by rkh** [comment]
That's the current version. The prompt was added in 1.5.7.

**Comment by shevett** [comment]
It is possible I blew past it and didn't notice.  :-/  Still though, that's an odd way of setting up environments.  'travis', a Ruby script, is already in the path.  Oh, it looks like it's setting up auto-complete entries in the users shell.  That's... interesting.  I suppose an argument can be made that this is useful, but the space in the username is probably something that should be addressed.

**Comment by kislyuk** [comment]
I don't think the travis gem should be touching my .bashrc. At minimum, the prompt in question should explicitly spell out what it will do to install the completions. Ideally, the gem should be installing a bash-completion module instead of this custom completion script.

**Comment by kislyuk** [comment]
This issue has not been addressed.

The travis gem should not touch `.bashrc`. It should install shell completion using the standard technique, by placing a file in `/etc/bash_completion.d` or equivalent.
