### ISSUE TITLE
Container/Docker based infstructure doesn't have /bin/ping (and /bin/ping6?)

### ISSUE THREAD

**Issue by Mikaela** [travis-ci/travis-ci#3080]
[Limnoria](https://github.com/ProgVal/Limnoria)'s [Unix plugin](https://github.com/ProgVal/Limnoria/tree/testing/plugins/Unix) has commands that use /bin/ping and /bin/ping6 to ping 127.0.0.1 and ::1 to see that the plugin works. However your container/docker images don't have /bin/ping and it can probably be assumed that there isn't /bin/ping6 either.
This prevents [Limnoria](https://github.com/ProgVal/Limnoria) from using `sudo: false`.
- One log: https://travis-ci.org/Mikaela/limnoria/jobs/45758823#L3651

CC: @ProgVal

**Comment by Mikaela** [comment]
If I understood correctly, you are using Ubuntu and on `Ubuntu 14.10` ping should be included by default and it's marked as priority: important.

```
Package: iputils-ping
Priority: important
Section: net
Installed-Size: 160
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Noah Meyerhans <noahm@debian.org>
Architecture: amd64
Source: iputils
Version: 3:20121221-5ubuntu2
Provides: ping
Depends: libc6 (>= 2.14), libcap2 (>= 2.10), libgnutls-openssl27
Recommends: libcap2-bin
Filename: pool/main/i/iputils/iputils-ping_20121221-5ubuntu2_amd64.deb
Size: 52744
MD5sum: 489ff2c3b89cff4ebde8fccc6a4940b0
SHA1: e5a408a84f706c1082994d970dbdeb33df51fc19
SHA256: d68e04250404e613d04fd3ff9fbad8839a498520a60482b128e70a305c6fc487
Description-en: Tools to test the reachability of network hosts
 The ping command sends ICMP ECHO_REQUEST packets to a host in order to
 test if the host is reachable via the network.
 .
 This package includes a ping6 utility which supports IPv6 network
 connections.
Description-md5: d70a0a65fee86f2e5c78f759703e9922
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m
Task: minimal
```

**Comment by dstufft** [comment]
Isn't ping a setuid binary?

**Comment by Mikaela** [comment]
I am not sure what you mean. Ping can be ran by any user and in my previous comment there is line `Task: minimal` which means that this package is included even in the minimal installation.

There are some flags that require root though.

**Comment by dstufft** [comment]
Sorry if this below your level, I'm not going to make any assumptions!

As far as I know the Travis CI Docker containers do not allow you to use ``sudo`` or run any setuid or setgid binary. This is because Docker doesn't protect against malicious code being executed as root in the container. A setuid binary is essentially a binary that, for that binary only, has an implicit ``sudo`` associated with executing it. So if ``/bin/ping`` is setuid to root, then calling ``/bin/ping`` is similar to calling ``sudo /bin/ping``, it just happens behind the scenes and with slightly different mechanisms.

I believe, (and a quick google seems to confirm - https://unix.stackexchange.com/questions/51874/root-owned-program-with-setuid-bit-on) that ``ping`` and ``ping6`` are both setuid which means they cannot run on the Travis CI Docker infrastructure because if there was a way to trick the ``ping`` code into say, executing another binary, it would execute as if the root user was running it.

**Comment by Mikaela** [comment]
I see. It appears that Limnoria will continue not using Docker.

**Comment by joshk** [comment]
Thanks for the awesome description @dstufft 

I'm actually going to reopen this as maybe we can allow ping and ping6.

@meatballhat @BanzaiMan @henrikhodne thoughts? Do you think it would be safe enough to allow these two binaries?

**Comment by BanzaiMan** [comment]
Looks like [iputils-ping](http://packages.ubuntu.com/precise/iputils-ping) is simply missing from the Docker image. It is indeed suid, but that bit will be removed during the build.

**Comment by BanzaiMan** [comment]
My inclination is to wait until we can allow privilege escalation. `ping`/`ping6` seems reasonable to me, but that introduces a maintenance burden ("What about this utility X?") that can be avoided for now.

**Comment by joshk** [comment]
In general I agree, although ping is a pretty important utility, and we don't know when sudo will become available.

**Comment by henrikhodne** [comment]
What happens if you try to run ping without it having the setuid bit set? It appears it isn't set on my (non-Ubuntu) Linux machine.

**Comment by BanzaiMan** [comment]
```
ping: icmp open socket: Operation not permitted
```
https://travis-ci.org/BanzaiMan/travis_production_test/builds/45953799#L144

**Comment by meatballhat** [comment]
My first reaction is that I'd like to tackle this as part of selinux policy tuning, which will effectively allow sudo and setuid/setgid stuff once it's all done.

**Comment by Ede123** [comment]
Will this be implemented eventually or do I better work around it?

**Comment by BanzaiMan** [comment]
@Ede123 It is unlikely to be looked at any time soon. If you need `ping` now, you should use `sudo: required`.

**Comment by ProgVal** [comment]
A solution was to add a flag to disable use of suid binaries.
It also fixes issues when running your program with `LD_PRELOAD`, eg. with `eatmydata`

**Comment by Ede123** [comment]
Still an issue...

**Comment by BanzaiMan** [comment]
We will be moving away from containers. https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

As before, if you need `ping`, please use VMs.
