### ISSUE TITLE
block orgs from sync

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#3083]
It would be useful to be able to block orgs from syncing (even if that's something manual we have to do in a config file). The @gitpan org has ~36k repos, which apparently keeps every member from being able to sync their accounts.

**Comment by rkh** [comment]
We could also use a feature flag for this.

**Comment by oalders** [comment]
I'm a member of gitpan and had reported the issue.  Thanks for looking into this.

**Comment by oalders** [comment]
Is there any progress on this?  I had mentioned the issue to @schwern and he thinks this may be a regression.

**Comment by schwern** [comment]
I can understand if Travis doesn't want to add a bunch of extra code to support our one org with a hojillian repositories.  We don't need to use Travis with Gitpan, but we would like to use our other repositories.  Maybe a simple fix is to allow organizations to be disabled?  Or have Travis automatically disable an organization with too many repositories?

**Comment by joshk** [comment]
@rkh was this issue addressed?

**Comment by oalders** [comment]
Is there a status on this?  At this point I'm guessing my only move is to remove myself from the org in question.  I haven't been able to add a new repo to Travis in months.

**Comment by oalders** [comment]
As a follow-up, with the new UI, my profile page in general is basically locked up with a sync message, regardless of what I click:

![screenshot 2015-04-06 15 11 33](https://cloud.githubusercontent.com/assets/96205/7010450/54866c04-dc6f-11e4-976f-b61d067567e9.png)

**Comment by joshk** [comment]
I believe I fixed this for you now.

We have a new 'GitHub sync' app in the works and hope to have it deployed soon.

**Comment by joshk** [comment]
The blocking of orgs was implemented a while ago, but will be tweaked in the future as we rebuild this component.

**Comment by oalders** [comment]
Ah, it works!  Thank you!!! :100:
