### ISSUE TITLE
mkdir: Command not found

### ISSUE THREAD

**Issue by vermiculus** [travis-ci/travis-ci#3084]
Um, is there a *better* way to create a directory? [`make[1]: mkdir: Command not found`][no-sudo].  I also tried using `sudo` with the makefile [to no avail][sudo]. What's going on here? I can't believe a bug like this would exist, so I must be doing something wrong. Here is my configuration file at the present time: [`.travis.yml`][yml].

[no-sudo]: https://travis-ci.org/vermiculus/sx.el/jobs/45904425#L114
[sudo]: https://travis-ci.org/vermiculus/sx.el/jobs/45955809#L106
[yml]: https://github.com/vermiculus/sx.el/blob/4dd17c3a6fe7a9b7fe613e6832370c4a67125cba/.travis.yml

**Comment by BanzaiMan** [comment]
`mkdir` exists on the image, of course. https://travis-ci.org/vermiculus/sx.el/jobs/45944159#L102

You are managing `$PATH` in your `Makefile`: https://github.com/vermiculus/sx.el/blob/4dd17c3a6fe7a9b7fe613e6832370c4a67125cba/Makefile#L19 Perhaps this is messing up your `$PATH`.

**Comment by vermiculus** [comment]
I did think of that, but if the PATH were being completely borked, wouldn't I lose `rm` as well? The makefile works locally when run as `make 4` for instance. As far as I see, I am prepending my paths to the current `PATH` -- though this wouldn't be the first time Make's syntax has thrown me for a loop.

**Comment by BanzaiMan** [comment]
We can spin up a debug VM for you. Please email support@travis-ci.com.

**Comment by vermiculus** [comment]
Sorry – this is still on the radar, but things have gotten very hectic around here. I should be able to give this more attention after Jan 25 or so. Thanks for the offer of the debug VM :smile:

**Comment by roidrage** [comment]
I'm closing this issues for now as there haven't been any further updates recently.

**Comment by vermiculus** [comment]
Ah, sorry for not following-up with you. January turned out to be a hectic time with changing jobs (good things, good things :smile:)

We still use evm in the project and we haven't had any problems since I opened this issue, so I'd say it's N/R for now. Thanks for helping look into it with me :smile:
