### ISSUE TITLE
Support for non-Github projects

### ISSUE THREAD

**Issue by singpolyma** [travis-ci/travis-ci#3087]
Most general way to do this would be to have a git endpoint that could be pushed to to trigger a build (could throw out the repo contents after the build so storage doesn't grow).  Alternative might be to allow creating a project with a public git URL, and then have a webhook that could be hit by the other service.

This would allow GitLab and Gitorious based, as well as self-hosted, open source projects to use travis-ci.

**Comment by roidrage** [comment]
Thanks for the suggestion. As #667 shows, this is not something that's on our immediate roadmap to implement and support, maybe at some point in the future.
