### ISSUE TITLE
travis encrypt with renamed repo

### ISSUE THREAD

**Issue by soniah** [travis-ci/travis-ci#3093]
I'm using these instructions: http://docs.travis-ci.com/user/encryption-keys/

I've logged in to travis using

```shell
% travis login --github-token YhJ4lJgiqWc8ABsQFMYG # not my real token
```

However, when I do:

```shell
travis encrypt FOO=bar --add
```

I get:

```shell
not logged in, please run travis login --pro
```

Why do I need travis pro for encrypting data, for an open source project?

**Comment by roidrage** [comment]
travis encrypt doesn't require a pro account.

Can you try running `travis encrypt FOO=bar --add --org`?

**Comment by soniah** [comment]
Hey thanks. Running the above gives:

```
% travis encrypt FOO=bar --add --org
repository not known to https://api.travis-ci.org/: soniah/terraform-provider-dnsmadeeasy
```

But that repo is currently running Travis: https://travis-ci.org/soniah/terraform-provider-dme (notice the shortened name).

So the problem is that I renamed my repo a while ago. But now I can't find where travis is caching this information on my local machine. It's not in ~/.travis, as I removed that directory.

**Comment by BanzaiMan** [comment]
Hi, @soniah, what git remote do you have defined in your working copy? You could also specify which repository to encrypt against by `-r soniah/terraform-provider-dme`.

**Comment by soniah** [comment]
Banzai! Thanks. My git remote is good, I'll use the -r option. Thanks!

**Comment by spencergibb** [comment]
The travis slug is stored in `.git/config`.  You can change it there instead of constantly using the `-r` option.

**Comment by jennybc** [comment]
@spencergibb Thank you so very much for that info! Very useful. Had same problem (#4154) and this allowed me to start encrypting files again.

**Comment by fpapadopou** [comment]
Thumbs up for @spencergibb! Thanks a lot! :+1:

**Comment by BrightShadow** [comment]
I have a repository not renamed and "m facing the problems described here despite the solutions.
 Any idea? Now I get
`repository not known to ....`
When trying to encrypt data, I'm logged in.

**Comment by TomasVotruba** [comment]
I still have the same issue, despite using the `-r` option. I didn't rename the repo.

**Comment by TeemuKoivisto** [comment]
I also renamed my repo but my slug name seemed right and `travis init` would yield the same name.

Only thing was that in GitHub I had two upper cases while Travis named my name with all lowercase. Renaming it from `teemukoivisto/react-courseproject-2017-frontend` to `TeemuKoivisto/react-courseproject-2017-frontend` would fix the problem.

**Comment by BrightShadow** [comment]
I've left Travis. I'm using Visual Studio Online and it is working like a charm!

**Comment by kenorb** [comment]
Same here.

```
$  travis login --github-token 45...
Successfully logged in as kenorb!
$  travis login --org --github-token 45...
Successfully logged in as kenorb!
$ travis status
not logged in, please run travis login --pro
$  travis encrypt "e4..." -add deploy.api-key
not logged in, please run travis login --pro
$ travis setup releases
not logged in, please run travis login --pro
$ travis --version
1.8.9
```

This is what worked (adding `--org`):

`$  travis encrypt "e4..." -add deploy.api-key --org`

Stil it didn't create in the right place, but under `dd.secure`, but it was easy to move.

**Comment by lgarczyn** [comment]
Same problem here, solution was simple:

The git url was lowercase for some reason, so when travis tried to load the repo, it found "improve" instead of "ImproVe".

Solved it using `travis encrypt -Rlgarczyn/ImproVe fwefwefwfwefw`

**Comment by Nishkalkashyap** [comment]
In my case I had multiple remotes configured in my git repo. Changing to the appropriate remote in .git/config file fixed my issue.
