### ISSUE TITLE
Install pandoc in images?

### ISSUE THREAD

**Issue by msabramo** [travis-ci/travis-ci#3094]
Because of the popularity of GitHub, many people prefer writing docs in Markdown. 

In the Python world at least (this may or may not be a problem in other communities), the package server (PyPI) doesn't support Markdown so people need to use a converter (usually based on pandoc) (e.g.: https://pypi.python.org/pypi/setuptools-markdown) or have a crappy or no description. 

I have tried to popularize https://pypi.python.org/pypi/setuptools-markdown but a common complaint is that it will fail on a CI server if pandoc is not installed. Of course, you can put `sudo apt-get install pandoc` but I think that would preclude using the new Docker container infrastructure because of the sudo, correct?

**Comment by fommil** [comment]
:+1: if there is a general "install ubuntu packages in docker" ticket, I'll subscribe to that instead... it's really the only thing about travis that bugs me.

**Comment by meatballhat** [comment]
see travis-ci/travis-build#372 :smiley_cat:

**Comment by BanzaiMan** [comment]
Add

```yaml
addons:
  apt_packages:
    - pandoc
```

**Comment by msabramo** [comment]
This is very cool. Thank you!

**Comment by msabramo** [comment]
Hmmm. https://travis-ci.org/bebraw/pypandoc/builds/49015577 just failed because it didn't install pandoc as requested. Does this feature not work on PRs perhaps?

**Comment by arve0** [comment]
@msabramo Did you make this work?

**Comment by msabramo** [comment]
Yes, I got it to work. Here's an example:

https://travis-ci.org/bebraw/pypandoc/builds/52055345

**Comment by arve0** [comment]
Thanks! :octocat:

**Comment by guenneguezt** [comment]
Is it possible to implement check for markdown language support
