### ISSUE TITLE
Elixir support

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3096]
I think this is a good one to support, though having some language expert would be nice.

https://github.com/travis-ci/travis-cookbooks/pull/430 added `kiex` installation to the Erlang image. Now the question is how to add the language build support.

One is to add a new language `elixir` (a la https://github.com/travis-ci/travis-build/compare/ha-feature-elixir) which would require some extra work on travis-core but has a nice feeling about specifying the language itself.

The other is piggybacking on the existing language `erlang`. This works in the [ha-feature-elixir-with-kiex branch](https://github.com/travis-ci/travis-build/compare/ha-feature-elixir-with-kiex), but feels somewhat kludgy.

Either way, I suspect users would want the `elixir` key to be expanded into build matrices, so I guess some work on travis-core is inevitable.

**Comment by joshk** [comment]
:+1: to `language: elixir`

How you do it in travis-build is up to you, but I agree that it makes more sense to specify `elixir` as a language then `erlang` with an `elixir` version.

**Comment by joshk** [comment]
@gildegoma if you want to subscribe to an issue you can do that on the right hand side, under the heading 'notifications'

**Comment by gildegoma** [comment]
@joshk Sorry for the noise. 

I know the subscribe function, but in this case it is of few value since I'm watching `travis-ci/travis-ci` project in its whole. Commenting on the issue thread instructs GitHub to send me the e-mail notification in CC instead of BCC, which is handy to build two notification channels. Do you mind if I (rarely) continue to do so?

**Comment by arrowcircle** [comment]
+1 to language: elixir

**Comment by BanzaiMan** [comment]
This supersedes #2964.

**Comment by BanzaiMan** [comment]
This has been deployed earlier this month.
