### ISSUE TITLE
"What is this?" button on "Allow failures" does not do anything

### ISSUE THREAD

**Issue by cebe** [travis-ci/travis-ci#3099]
Kind of a very minor thing, but:

![screenshot-2015-01-10t23 15 27](https://cloud.githubusercontent.com/assets/189796/5693484/d81ee8fa-991e-11e4-8cd0-366f1345b03d.png)
https://travis-ci.org/yiisoft/yii2/builds/46584685

Clicking on the question mark does nothing.

**Comment by drogus** [comment]
Thanks for the report. I've fixed it with travis-ci/travis-web@8b6db44
