### ISSUE TITLE
[Build] configure php versions with --enable-debug

### ISSUE THREAD

**Issue by shouze** [travis-ci/travis-ci#3101]
This will help when running gdb to find some segfault we can't reproduce elsewhere than into the travis-ci worker:

![capture d ecran 2015-01-12 a 10 42 15](https://cloud.githubusercontent.com/assets/54712/5701160/dee864b6-9a47-11e4-88b0-f6fdaa7ffecc.png)

You just have to add `--enable-debug` into [ci_environment/phpbuild/templates/default/default_configure_options.erb](https://github.com/travis-ci/travis-cookbooks/blob/6db2719461ea54f5603bdfac7c852405cd9a85f2/ci_environment/phpbuild/templates/default/default_configure_options.erb)

**Comment by BanzaiMan** [comment]
Hmmm. Doesn't this slow down the tests?

**Comment by shouze** [comment]
@BanzaiMan yes you get a point. With this configure option we don't strip debug symbols. It affects threaded a lot performance of threaded processes.

So... maybe it's more accurate to introduce provisioned worker with the 2 flavours:
- php-X.Y.Z
- php-X.Y.Z-debug

**Comment by BanzaiMan** [comment]
We cannot do that with all versions, I'm afraid. We can spin up a debug VM for you, though. Please email support@travis-ci.com.

**Comment by photodude** [comment]
@shouze Did you ever figure this out to get the core dump? If you did, How did you do it?
I'm stuck at [No symbol table info available.](https://travis-ci.org/photodude/fof/jobs/332156772#L749)
