### ISSUE TITLE
Missing PR column in pull_requests view

### ISSUE THREAD

**Issue by kbrock** [travis-ci/travis-ci#3102]
In the pull requests view ([example](https://travis-ci.org/ManageIQ/manageiq/pull_requests)) there are 6 headers but only 5 columns of data.

The data for the column titled "PR" is currently missing.
It is very helpful to determine the latest build for each github PR.

Thanks for the great service

**Comment by joshk** [comment]
Thanks for reporting this!

We are rolling out a fix now.

**Comment by BanzaiMan** [comment]
@kbrock Could you confirm that the fix works for you?

**Comment by kbrock** [comment]
@BanzaiMan @joshk Thanks so much
So nice to scan down the pr column to see that a PR has indeed been fixed

![travis ci - free hosted continuous integration platform for the open source community 2015-01-13 09-22-06](https://cloud.githubusercontent.com/assets/1930/5721981/ec5ede2c-9b05-11e4-9665-f3234e4ba1a5.png)
