### ISSUE TITLE
Install swig on the VM images

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#3104]
Swig is needed to install m2crypto python library.

**Comment by adepue** [comment]
+1 for this.  Thanks!

**Comment by BanzaiMan** [comment]
I assume this is for containers.

**Comment by adepue** [comment]
Yep for containers.

**Comment by adepue** [comment]
@BanzaiMan Now that this is whitelisted in your commit, when can we start using it?  We are still having issues when the cache with our pip wheels fails to download and then we can't build the pip packages b/c this is missing.

**Comment by amwhearsay** [comment]
+1

**Comment by BanzaiMan** [comment]
You can install `swig` now. https://travis-ci.org/BanzaiMan/travis_production_test/builds/53294466#L88 if it's not working, there is some other problem.

**Comment by adepue** [comment]
@BanzaiMan we have tried adding
```yaml
addons:
  apt_packages:
    - swig
```
to the .travis.yml file, however the package still doesn't end up being installed.  Is there an install syntax we need to use that is different?

**Comment by adepue** [comment]
I stand corrected, I had an error in the yaml file with 2 addons regions defined.  Thanks for the help!
