### ISSUE TITLE
Redis cannot use the notification system

### ISSUE THREAD

**Issue by ametaireau** [travis-ci/travis-ci#3105]
Since 2.8.0, Redis provides a notifications system, which isn't enabled by default (there is a need to activate it via a configuration option).

It's currently not available on Travis, or a didn't found how to activate the support for it. That would be nice to have it.

Documentation for notifications are at: http://redis.io/topics/notifications

Thanks!

**Comment by BanzaiMan** [comment]
Thanks for the heads up. https://launchpad.net/~rwky/+archive/ubuntu/redis shows that the 2.8 is now available; it should be available in the next round of environment updates (No ETA). Is there any configuration change on the system side necessary? Doc says:

> Notifications are enabled using the notify-keyspace-events of redis.conf or via the CONFIG SET.

which indicates to me that the user can issue this command to enable the feature, once 2.8 is available.

**Comment by ametaireau** [comment]
Oh yeah, you're right, it seems possible to actually enable it only by a CONFIG SET command, which should be enough.

**Comment by ametaireau** [comment]
How can I know which version of redis is running now?

**Comment by Natim** [comment]
``redis-cli info Server`` or from your test file.

**Comment by BanzaiMan** [comment]
This information should be available in the "Build system information" fold in your build logs. (https://travis-ci.org/BanzaiMan/travis_production_test/builds/46358901#L3)

In fact, it is running 2.8.18 (or something close). Please try running the config command and see if it works for you.

**Comment by BanzaiMan** [comment]
If it still doesn't work, please point to a build log URL that shows the problem.

**Comment by ametaireau** [comment]
Actually it worked! Thanks for the help.

**Comment by ametaireau** [comment]
https://travis-ci.org/mozilla-services/loop-server/builds/46745351
