### ISSUE TITLE
Can't install python-zmq

### ISSUE THREAD

**Issue by remram44** [travis-ci/travis-ci#3106]
Installing python-zmq via aptitude yields:

```
...
Selecting previously unselected package libzmq1.
Unpacking libzmq1 (from .../libzmq1_3.2.2-0~travis1_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/libzmq1_3.2.2-0~travis1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libzmq.so.3.0.0', which is also in package libzmq3 3.2.2+dfsg-1~travis1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
...
Errors were encountered while processing:
 /var/cache/apt/archives/libzmq1_3.2.2-0~travis1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

https://travis-ci.org/VisTrails/VisTrails/jobs/46761015#L310

Related: #982?

**Comment by BanzaiMan** [comment]
Why are you getting `libzmq1_3.2.2`? It should be 2.1.11 on Precise. http://packages.ubuntu.com/precise/libzmq1

Seems like some dependency resolution is broken for precise. See https://travis-ci.org/VisTrails/VisTrails/jobs/46761015#L115-L117
```
dpkg: error processing /var/cache/apt/archives/libzmq1_3.2.2-0~travis1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libzmq.so.3.0.0', which is also in package libzmq3 3.2.2+dfsg-1~travis1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
```

**Comment by remram44** [comment]
Precise doesn't have a package libzmq3, so ths really looks specific to Travis.

**Comment by BanzaiMan** [comment]
Does this package dependency resolution error happen on any Precise machine? (My short experiment confirms it does.) If so, this is an issue with Ubuntu itself.

**Comment by remram44** [comment]
[Precise doesn't have a libzmq3 package.](http://packages.ubuntu.com/search?keywords=libzmq&searchon=names&suite=precise&section=all) The `~travis` in package versions are a sign that some tempering was done here...

**Comment by BanzaiMan** [comment]
Ah. You're right. Sorry about that. We'll take a look.

**Comment by BanzaiMan** [comment]
(Remotely related: https://github.com/travis-ci/travis-ci/issues/2558)

**Comment by thefosk** [comment]
I'm experiencing the same error.

**Comment by BanzaiMan** [comment]
Before reinstalling `libzmq3`, try removing the file: `/etc/apt/sources.list.d/travis_ci_zeromq3-source.list`.

**Comment by htgoebel** [comment]
Adding `sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list` just in front of `sudo apt-get install -y python-zmq' solved the problem for me. See e.g. https://travis-ci.org/htgoebel/pyinstaller/builds/61910151

**Comment by geertw** [comment]
This issue is still occurring and is becoming more problematic when moving to Docker build machines. For now, I've worked around the problem by install pyzmq using pip, but this takes more build time than it should and it's counterintuitive.

This travis.yml snippet does **not** work in Docker builds:
```yaml
addons:
  apt:
    packages:
   - python-zmq
```

as this returns the following error:
```
Unpacking libzmq1 (from .../libzmq1_3.2.2-0~travis1_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/libzmq1_3.2.2-0~travis1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libzmq.so.3.0.0', which is also in package libzmq3 3.2.2+dfsg-1~travis1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
```

See [this build](https://travis-ci.org/geertw/rdt-serviceinfo/builds/86090823) for an example.

This does work for me:
```yaml
install:
  - pip install pyzmq
```

**Comment by remram44** [comment]
@BanzaiMan did you take a look yet? It's been 9 months...

**Comment by BanzaiMan** [comment]
I reverted the source removal.

**Comment by remram44** [comment]
Still getting the same error.

```
dpkg: error processing /var/cache/apt/archives/libzmq1_3.2.2-0~travis1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libzmq.so.3.0.0', which is also in package libzmq3 3.2.2+dfsg-1~travis1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
...
Errors were encountered while processing:
 /var/cache/apt/archives/libzmq1_3.2.2-0~travis1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by remram44** [comment]
Seems to work now. `libzmq3_4.0.4+dfsg-2_amd64.deb` was installed, so whatever Travis hack was there has been removed since.
