### ISSUE TITLE
python-config not linked in virtualenv

### ISSUE THREAD

**Issue by jeremyherbert** [travis-ci/travis-ci#3107]
Hi,

Related to https://github.com/pypa/virtualenv/issues/169 , the "python-config" command points to the system python rather than the virtualenv python.

**Comment by BanzaiMan** [comment]
Paging @dstufft.

**Comment by BanzaiMan** [comment]
This is a virtualenv issue, right? Until it's fixed and the fix is deployed to our images, I think tweaking `$PATH` (https://github.com/travis-ci/travis-ci/issues/7138#issuecomment-272819462) is a workaround.
