### ISSUE TITLE
Add io.js runtime

### ISSUE THREAD

**Issue by mathiasbynens** [travis-ci/travis-ci#3108]
Are there plans to pre-install [io.js](https://github.com/iojs/io.js) on the VMs, or should users do this themselves in `before_script`?

**Comment by BanzaiMan** [comment]
No concrete plans at the moment. I don't know how they are going to release it, and how that would impact our existing Node.js environment. It is too early to say if/when we can support it.

**Comment by Joshua-Anderson** [comment]
Travis CI uses NVM for node version management, and IO.is work is still in progress. See creationix/nvm#590. When that is done you and Travis CI updates it you will be able to specify io.us as a option.

**Comment by jonathanong** [comment]
all you guys have to do now is upgrade your `nvm` to the latest version. is that something that can be easily done?

**Comment by mathiasbynens** [comment]
What @jonathanong said: [nvm v0.23.0+ supports io.js](https://github.com/creationix/nvm/releases/tag/v0.23.0).

**Comment by joshk** [comment]
Thanks everyone, we are working on it,

**Comment by popomore** [comment]
Waiting for it.

**Comment by bajtos** [comment]
+1 from Node Inspector (/cc @3y3)

**Comment by evantahler** [comment]
+1 over over here from www.actionherojs.com as well!

**Comment by BanzaiMan** [comment]
This has ben deployed earlier this month.
