### ISSUE TITLE
Provide Erlang 17.4

### ISSUE THREAD

**Issue by kxepal** [travis-ci/travis-ci#3109]
Erlang 17.4 was [released](http://www.erlang.org/news/81) month ago, but seems it not yet available on travis:
```
$ source $HOME/otp/17.4/activate

/home/travis/build.sh: line 41: /home/travis/otp/17.4/activate: No such file or directory
```

**Comment by BanzaiMan** [comment]
It will replace 17.3 on the next update. https://github.com/travis-ci/travis-cookbooks/commit/4f6a3b170e65c044868b762544f31b7d05270a16

**Comment by kxepal** [comment]
Thanks! Do you know when the next update happens?
