### ISSUE TITLE
Log doesn't update after restart

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#3111]
We got a report that the log on the website doesn't always update when restarting a job.

In this case, the following happened: Build had failed, restart was attempted and build was passing, but log didn't update (even after refresh). Another restart was attempted and this time the build passed.

This is with Google Chrome 39.0.2171.95 on OS X 10.9.4.

HS#12009

**Comment by joshk** [comment]
Was this on .org or .com?

**Comment by henrikhodne** [comment]
.org

**Comment by joshk** [comment]
I am closing this as it has become stale.
