### ISSUE TITLE
Add SlimerJS

### ISSUE THREAD

**Issue by trodrigues** [travis-ci/travis-ci#3114]
We've recently switched to using SlimerJS instead of PhantomJS. SlimerJS is a headless version of firefox that is easy to install and setup, and given that PhantomJS uses a very old version of webkit (the webkit update is slated only to the next major version of PhantomJS which has been continuously delayed), it's becoming increasingly problematic (not to mention other slowness issues).

At the moment we are doing

```
install:
  - "npm install -g slimerjs"
```

In order to get SlimerJS, but if Slimer was already available like Phantom is, it would make things faster.

A little bit of input on running SlimerJS:
The method described on http://docs.travis-ci.com/user/gui-and-headless-browsers/, using xvfb by setting the display and starting the service, which was necessary for older versions of PhantomJS and for other methods of running a headless firefox didn't seem to exactly work for us with slimer.

Instead, what we are doing is running `xvfb-run karma start --single-run --browsers SlimerJS` (karma knows how to go and get slimer).

Slimer is available at http://slimerjs.org/

Thanks!

**Comment by BanzaiMan** [comment]
We can add this to our next update for testing. If it goes well, we can announce it and add to documentation.

**Comment by Blackbaud-PaulCrowder** [comment]
Any update on this?  My team has recently ditched PhantomJS in favor of SlimerJS because of its support for web fonts.  We're doing screenshot testing and we need the web font support.

**Comment by christianhaller** [comment]
+1

**Comment by BanzaiMan** [comment]
We did not add this, obviously.

My understanding is that Chrome supports headless mode. Does it suffice?

**Comment by BanzaiMan** [comment]
I'm closing this in favor of Chrome's headless mode.
