### ISSUE TITLE
share app directories as volumes in docker-based matrix build

### ISSUE THREAD

**Issue by JeanMertz** [travis-ci/travis-ci#3115]
I wonder if there is any interest in having the option to share app directories as volumes when using docker-based matrix builds.

The reason I ask is an investigation into using something like `Simplecov` (or more precisely, www.codeclimate.com) for test-coverage, while also using `Knapsack` to build our app across four different Travis build instances.

We use the new Docker-based builds, so if we could have the other matrix-builds shared with `--volume-from` with Docker, we could join all the `json` output of the test-coverage run, and push it to CodeClimate.

This is probably complex and a very specific request, so if anyone has any other ways of solving this problem, I'm all ears.

**Comment by joshk** [comment]
Hi Jean, thanks for the suggestion. I'm sorry but we are unlikely to add this as it is a possible security risk. Also, jobs are spread out across several (15+) different hosts, so it is unlikely they will share a common host to then be able to share a volume with.
