### ISSUE TITLE
iOS builds failing all the time

### ISSUE THREAD

**Issue by bringel** [travis-ci/travis-ci#3117]
My iOS project's builds have been failing for a while with some strange reasoning.

Here's the error message that is printed:
>Failed to build workspace Gumshoe with scheme Gumshoe.
>    Reason: The run destination iPhone 4s is not valid for Running the scheme 'Gumshoe'.

Here's the command that travis is trying to run:
`xctool -workspace Gumshoe.xcworkspace -scheme Gumshoe -sdk iphonesimulator build test`

I've tried it with `iphonesimulator8.1` also with no luck. The same commands work on my local machine

**Comment by vintagexav** [comment]
Hi @bringel, 
It looks like your development target is >=8.0
As the default (or previous) simulator/device (i.e. run destination) used by xctool is 7.0, you encounter that crash.
I recommend you to run a custom command instead.
In your travis.yml file write the following two lines at the end of the file:

```
script: 
    - "xctool -workspace Gumshoe.xcworkspace -scheme Gumshoe -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=8.1' build test"
```

That should do the trick!

**Comment by bringel** [comment]
I got this to work earlier in the week by passing `-destination "platform=iOS Simulator,name=iPhone 6"` actually as `xctool_args`

It seems odd that the default isn't being read in from the deployment target in the scheme being used. I don't think I had to do the same thing when I ran xctool locally, but I'm not sure I have the iOS 7 simulators installed anymore, so that could be why

**Comment by roidrage** [comment]
I'm closing this issues for now as there haven't been any further updates recently.

Let us know if you continue to have issues.
