### ISSUE TITLE
Node 0.7 builds always fails

### ISSUE THREAD

**Issue by DanSorahan** [travis-ci/travis-ci#3118]
Upon attempting to process a 0.7 job, it will fail every time after rebuilding with NVM, you are presented with a npm issue regarding self signed certificates, [due to a change made in February last year](http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more).

````
Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN
````

[Example build](https://travis-ci.org/DanSorahan/genoset-chronsdisease/jobs/47221944)

**Comment by joshk** [comment]
Node 0.7 is considered a development/unstable release, and an old one at that.

We recommend updating to 0.11 if you want to use an unstable version, or 0.10.
