### ISSUE TITLE
improve cache change detection for scala sbt/ivy caches

### ISSUE THREAD

**Issue by fommil** [travis-ci/travis-ci#3122]
We're starting using the docker infrastructure with caching, thanks, it's great!

However, a new cache gets build pretty much every single time we build, even if our dependencies haven't changed.

I suspect that sbt/ivy are touching files or something and making it look like there are changes when there are not... or leaving lock files behind.

It would save you a lot of disk space / network if the ivy change detection was improved.

Example project: https://github.com/ensime/ensime-server https://travis-ci.org/ensime/ensime-server/ and I noticed this a lot in my branch https://travis-ci.org/fommil/ensime-server

Another (simpler) example project (where I first noticed this) https://travis-ci.org/fommil/kerbal-calculator

**Comment by BanzaiMan** [comment]
I believe this is a variation of #3039. If you know ahead of time what fils can be excluded from the cache, you can manage them manually until a feature (as described in #3039) is implemented.

**Comment by fommil** [comment]
I don't think it is entirely the same, although your implementation may have overlap. This issue is more about working around the fact that ivy just touches things like crazy. It would be far too onerous to explicitly list what needs to be cached. Global travis exclusion rules for ivy caches might not be a bad idea.

**Comment by jjuraszek** [comment]
have you found any bypass for that issue?

**Comment by fommil** [comment]
nope, I just let the cache get rebuilt for trivial touches that Ivy makes. It slows down the build a little but it isn't prone to errors (which is the case if we don't use the cache at all)

**Comment by pkallos** [comment]
:+1:

**Comment by BanzaiMan** [comment]
Hello! We have an experimental version of the caching utility that is smarter about file change detection. Do you mind testing it?

If you are interested, add the following to `.travis.yml`:

```yaml
cache:
  branch: md5deep # <= new!
  ⋮
```

**Comment by BanzaiMan** [comment]
Checksum-based file change detection has been deployed. If the cache continues to be uploaded, I suspect the file contents *are* changing. I'm closing this issue optimistically, but if you still see problems, do let us know.
