### ISSUE TITLE
Environment variable visibility switcher has no label

### ISSUE THREAD

**Issue by neoascetic** [travis-ci/travis-ci#3123]
![screen shot 2015-01-18 at 16 56 40](https://cloud.githubusercontent.com/assets/725836/5792813/7ec2edd6-9f33-11e4-9c1f-b625f62d72de.png)

OS: OSX 10.9
Browser: Firefox Developer Edition

**Comment by drogus** [comment]
Thanks for the report, I've fixed it with trvis-ci/travis-web@9d45132
