### ISSUE TITLE
GitHub repo sync stuck

### ISSUE THREAD

**Issue by sindresorhus** [travis-ci/travis-ci#3124]
It's been on "Please wait while we synchronize your data from GitHub" for almost a day now.

**Comment by joshk** [comment]
Fixed and fixed.

Sorry for the issues.

**Comment by leoromanovsky** [comment]
Bump, same for me today. Do you need my account to debug?

**Comment by joshk** [comment]
@leoromanovsky please email support. Also, please don't comment on old closed issues, it is better to either comment on an open issue, or open a new one. But in this case, emailing support is best.
