### ISSUE TITLE
Consider setting JAVA7_HOME and JAVA8_HOME

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#3127]
It may be useful to have paths for jdk7 and 8 in case both are needed. I'm not sure if this is a standard practice, a customer requested this.

**Comment by BanzaiMan** [comment]
What the user needs is probably a convenient (and documented) way to switch between JDK installations. This is easily done with `jdk_switcher`. For example: https://github.com/BanzaiMan/travis_production_test/blob/42dad8404329337ea4fd707c76f0eaf4126c2bf0/.travis.yml

I've added this to documentation: http://docs.travis-ci.com/user/languages/java/#Switching-JDKs-Within-One-Job
