### ISSUE TITLE
MTU for Container-Based Infrastructure

### ISSUE THREAD

**Issue by jeffreyc** [travis-ci/travis-ci#3129]
When using Travis's new [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) (i.e., `sudo: false`), it would be great if we could specify the MTU via `.travis.yml`. By default, the MTU is set to 9001:
```
$ ip addr show eth0
1967: eth0: <BROADCAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP qlen 1000
    link/ether 9a:77:b6:23:9a:2e brd ff:ff:ff:ff:ff:ff
    inet 172.17.3.215/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::9877:b6ff:fe23:9a2e/64 scope link
       valid_lft forever preferred_lft forever
```

Unfortunately, when connecting to Amazon Redshift, they [prefer/require an MTU of 1500](http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-drop-issues.html). With the default MTU of 9001 on the container-based infrastructure, our tests error due to timing out; i.e., they hang when attempting to communicate with Redshift.

I recognize that jumbo frames may be desirable for most users of Travis, but it would be great if the MTU was configurable for those users that perform integration testing using Redshift. It looks like this is possible via [Docker command-line options](https://docs.docker.com/articles/networking/#quick-guide-to-the-options), so hopefully this is a matter of allowing users to specify (or even just toggle) options via `.travis.yml`.

I'm hesitant to call this a regression, but the MTU on the old infrastructure was 1500, and this is a blocker for our switching to the new infrastructure.

**Comment by henrikhodne** [comment]
Hi, I’m sorry for leaving this unanswered for so long. We’re going to be deploying a fix to push the MTU back down to 1500, as we’re seeing a lot of other networking issues that are resolved by decreasing the MTU.

**Comment by henrikhodne** [comment]
The MTU is now lowered to 1500 on the container-based infrastructure.
