### ISSUE TITLE
npm install fail 

### ISSUE THREAD

**Issue by lucemia** [travis-ci/travis-ci#3130]
npm install fail again and again due to the following errors.
but will I re-run the test, it is ok.
Is it a bug? Any suggestion to solve this issue?

Thx

```
pre-build test passed successfully!
npm ERR! EEXIST, open '/home/travis/.npm/83f1dfb7-vis-npm-lodash-2-4-1-package-tgz.lock'
File exists: /home/travis/.npm/83f1dfb7-vis-npm-lodash-2-4-1-package-tgz.lock
Move it away, and try again. 
```

**Comment by littleq0903** [comment]
may refer to this bug: https://github.com/npm/npm/issues/6309

**Comment by BanzaiMan** [comment]
This looks like an upstream issue. As such, I'm closing this. If there is anything to be done on our side, do let us know.

**Comment by BanzaiMan** [comment]
@ceoaliongroo If the intermittent npm issue is affecting the PR build, the best bet is to restart the failed build. The issue appears to be one best addressed by npm, so I am not sure what we can do on our side.

**Comment by ceoaliongroo** [comment]
@BanzaiMan I understood, but i have i almost a day restarting the the failed build fixed in master, but all the branches failed. 

I can merge with errors. https://travis-ci.org/Gizra/negawatt-server/builds/56876983  

Is possible to access via ssh to the build? to performance test in only of the npm library installation an not do all the test?

Thanks

**Comment by BanzaiMan** [comment]
@ceoaliongroo I understand your frustration, but I still believe that this is an upstream issue. You can wrap your `npm install` calls with the `travis_retry` function to make it more resilient (by retrying up to 3 times), but this only hides the real problem.

Though I do not believe it will be much of help, we can spin up a debug VM for you. If you want it, please email support@travis-ci.com. Thank you.

**Comment by ceoaliongroo** [comment]
Thanks, 

Because, you previous comment, i did a doble check in the npm repository. Looks like is a issue that correct and reappears again.

For now, i could remove ``npm packages`` relates with the error. 

Greant to know the option of ``travis_retry`` 

All the best.
