### ISSUE TITLE
APT whitelist request for liblapack-dev, g++-4.8 (ppa:ubuntu-toolchain-r/test), python-nose, valgrind, ccache

### ISSUE THREAD

**Issue by chrisdembia** [travis-ci/travis-ci#3131]
I hear that the `sudo: false` users will be able to request whitelisting certain apt packages?

We depend on:
* liblapack-dev
* freeglut3-dev
* libxi-dev
* libxmu-dev
* g++-4.8 (from ppa:ubuntu-toolchain-r/test)
* python-nose
* valgrind
* ccache

Would greatly appreciate if some of these could be whitelisted!

**Comment by BanzaiMan** [comment]
ccache should be available already.

Currently we do not allow extra PPAs.

**Comment by chrisdembia** [comment]
Awesome. I'll keep an eye on #979 then.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/apt-package-whitelist/commit/e14a1e2d4991d06882c5c39da72f3268913cb1f5 adds the rest, except `python-nose`.

**Comment by chrisdembia** [comment]
Thank you!
