### ISSUE TITLE
QGIS & PostGIS incompatibility

### ISSUE THREAD

**Issue by carolinux** [travis-ci/travis-ci#3132]
Hello!
I have the following lines in my install:
        - sudo apt-get install qgis
        - sudo apt-get install python-qgis

I think the first one removes postgis2.1, which is why I can't use it later on (https://travis-ci.org/anitagraser/TimeManager/builds/47823155) 
getting the error: could not access file "$libdir/postgis-2.1"

I think the only way it can work is if I install qgis first and postgis second. Any ideas how to solve this? Is it possible to start up a container without the preinstalled PostgreSQL? (then I would be able to test this more easily offline) Or any way to use postgis 2.0 instead of 2.1?
I can't just remove the ubuntugis ppa because then I can't install QGis (as proposed here https://github.com/travis-ci/travis-ci/issues/2401)

**Comment by BanzaiMan** [comment]
Hello. Sorry for the late response. Were you able to establish the desirable sequence of events that makes your builds run to completion?

If you need postgis 2.0, you can try removing `postgresql-9.1-postgis-2.1` and installing  `postgresql-9.1-postgis-2.0` (for the default PostgreSQL 9.0; change the version string accordingly if you use some other PostgreSQL version).

**Comment by carolinux** [comment]
My workaround was to remove ubuntugis-stable and download qgis from a different source.
Here is the file which works acceptably now (except that this qgis doesnt seem to have spatialite support as expected)

https://github.com/anitagraser/TimeManager/blob/a349c70d6017a8b24270f1580e49fb2d6390c9de/.travis.yml
