### ISSUE TITLE
build passed but with exit code was 1

### ISSUE THREAD

**Issue by timaschew** [travis-ci/travis-ci#3134]
https://travis-ci.org/componentjs/resolver.js/jobs/47850570

the tests with npm/mocha failed, at the end you see this:

```
make: *** [test] Error 1
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

**Comment by BanzaiMan** [comment]
Sorry, but it appears that you've restarted the build, and it no longer shows the error you describe. Is there another example we should look at?

**Comment by timaschew** [comment]
The build was overwritten after a new restart of the job.

**Comment by BanzaiMan** [comment]
I'm closing this, then. Let us know if you run into it again.
