### ISSUE TITLE
APT whitelist request for boost/gmp/mpfr

### ISSUE THREAD

**Issue by xu-cheng** [travis-ci/travis-ci#3136]
As `apt` finally is available for education users. I hope these packages can be whitelist:

* libboost-all-dev
* libgmp-dev
* libmpfr-dev
* <del>cmake</del>

These are the common libraries for multiprecision arithmetic which would be very handy for researchers if it's available. As for the cmake, I really hope I can use the latest version of it on travis-ci for the latest sweet sweet features.

Would be extremely appreciate if this list got approved.

**Comment by BanzaiMan** [comment]
`cmake` is installed by default, and it is the whatever the latest version available. http://packages.ubuntu.com/precise/cmake

**Comment by xu-cheng** [comment]
While cmake v2.8.7 is not newly enough. Is there any way to use newer version of it say 3.1.0 on Travis?

**Comment by chrisdembia** [comment]
For 3.1.0, I'd download the binary each time: http://www.cmake.org/download/

**Comment by xu-cheng** [comment]
@chrisdembia, thanks for such advice. Why I didn't think of that before?

**Comment by chrisdembia** [comment]
> Why I didn't think of that before?

Well, I'd prefer to use apt as well! Two-year old software is too old though :/.

**Comment by BanzaiMan** [comment]
Doesn't `libboost-all-dev` install *all* boost libraries? seems like an overkill.

**Comment by xu-cheng** [comment]
@BanzaiMan this is similar to TeXLive. We should whitelist both separate packages and the full package. Like this:
```
libboost-all-dev
libboost-date-time-dev
libboost-dev
libboost-filesystem-dev
libboost-graph-dev
libboost-graph-parallel-dev
libboost-iostreams-dev
libboost-math-dev
libboost-mpi-dev
libboost-mpi-python-dev
libboost-program-options-dev
libboost-python-dev
libboost-regex-dev
libboost-serialization-dev
libboost-signals-dev
libboost-system-dev
libboost-test-dev
libboost-thread-dev
libboost-wave-dev
```
