### ISSUE TITLE
S3 deployment fails on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3137]
A few users reported issues with S3 deployment on OS X. Example: https://travis-ci.org/octoblu/gateblu-ui-build/builds/48015341

```
ERROR:  Error installing aws-sdk-v1:
	ERROR: Failed to build gem native extension.
    /Users/travis/.rvm/rubies/ruby-1.9.3-p547/bin/ruby extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... yes
Building nokogiri using packaged libraries.
checking for gzdopen() in -lz... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.
```

**Comment by BanzaiMan** [comment]
There appears to be a race condition regarding the log message. The native extension that fails to build is `nokogiri`, not `aws-sdk-v1`.

**Comment by BanzaiMan** [comment]
I seem to remember nokogiri changing the way it installs. I'll investigate.

**Comment by BanzaiMan** [comment]
Paging @tenderlove and @flavorjones

**Comment by flavorjones** [comment]
Howdy, yes, we are now checking for the presence of `zlib` at install time, this is likely the root cause. The underlying ticket appears to be using `--use-system-libraries`, and in those instances we should skip this check.

Let me try to cut an RC to fix this.

**Comment by flavorjones** [comment]
Ah, no, wait -- the above message indicates the user is installing the packaged libraries, in which case zlib development files are really a requirement. Can we jump on IRC to discuss? #nokogiri

**Comment by flavorjones** [comment]
@BanzaiMan ping. Can you jump on IRC? freenode #nokogiri 

I'd like to either try to repro this, or else I'll back out of https://github.com/sparklemotion/nokogiri/commit/13edff71e0bf004dab1a192da1c7ec31e51f2542 in an RC that you can try

**Comment by flavorjones** [comment]
I'm going to revert the zlib check and push 1.6.6.2.

**Comment by flavorjones** [comment]
Nope, actually, I'm *not* going to revert Nokogiri. I believe that the output pasted above from @BanzaiMan is actually an XCode version issue; and that the problem reported in the Travis build log appears to me to be an issue with the aws-sdk-v1 gem:

```
cannot load such file -- aws-sdk-v1 
```

if this was nokogiri, it would not be failing with that message.

Please let me know if you have an environment which successfully installs 1.6.5 but fails when installing 1.6.6.1? Otherwise, it's likely *not* a Nokogiri issue.

**Comment by flavorjones** [comment]
I've also emailed Travis support asking for Nokogiri to be enabled for OSX builds, so we can try to reproduce.

**Comment by BanzaiMan** [comment]
I'm pretty sure that `aws-sdk-v1` is a red herring. It is a pure-ruby gem, and it fails to install because it depends on `nokogiri`.

**Comment by BanzaiMan** [comment]
Nokogiri 1.6.6.2 should fix this issue. If you've encountered this problem before, please try again.
