### ISSUE TITLE
Can't enable GitHub service from Travis-CI

### ISSUE THREAD

**Issue by jezdez** [travis-ci/travis-ci#3138]
While trying to enable Travis for the repo django/djangoproject.com I wasn't able to successfully enable it from the profile/django URL. See screenshot for JavaScript error related to `Access-Control-Allow-Origin` header missing.

![screenshot 2015-01-23 19 07 28](https://cloud.githubusercontent.com/assets/1610/5879859/3df8e662-a333-11e4-9b70-34b981770a79.png)

**Comment by jezdez** [comment]
For the record, I've tried resetting the browser Cache and that did not do the trick.

**Comment by joshk** [comment]
Hey Jannis,




Hmmm, very odd, could you go into incognito mode and see if that helps?




Thanks,




Josh

**Comment by jezdez** [comment]
Hi @joshk, same result:

![screenshot 2015-01-23 19 25 49](https://cloud.githubusercontent.com/assets/1610/5880089/a8582b38-a335-11e4-986a-8584b0e37e6b.png)

**Comment by joshk** [comment]
Hmmmmm, very very odd, works perfectly for me. I won't if one of your extensions is getting in the way?

Can you disable extensions and see if there is any improvements?

**Comment by jezdez** [comment]
Disabled all of them (had only JSONView enabled for incognito mode) and get the same error.

**Comment by jezdez** [comment]
BTW, I tried that a few days ago and it failed the same way. I then added Travis manually via GitHub's service settings. I just earlier removed it again since the PR integration didn't work (didn't send notifications). Maybe that helps digging into this.

**Comment by joshk** [comment]
Hmmmm, this is really strange, I can't replicate this, but I have seen a few similar reports.

@drogus @rkh can you both please look into this.

**Comment by jezdez** [comment]
I also tried with another repo of this org, with the same error.

**Comment by drogus** [comment]
This is most likely an error in the API. Currently we don't send headers for 500 responses, thus the misleading message. I'm looking into it.

**Comment by drogus** [comment]
@jezdez it seems like a problem with the OAuth token we have in the database. Could you try to revoke your token on GitHub and then sign in again? That should force the new token.

**Comment by fixe** [comment]
Happening to me as well. Revoking the token doesn't solve the issue.

**Comment by rkh** [comment]
We have another user reporting the issue for an org repo, so the assumption was it might be related to the new app whitelisting, but travis is whitelisted for the org in question. Revoking the token did not help.

**Comment by jezdez** [comment]
Aha! So here is what I did to make this work for me:

- Went to https://github.com/settings/applications and removed tokens for both Travis CI and Travis CI Private
- Went to https://travis-ci.org/ and signed out
- Signed in again
- On the GitHub authorize page ask for access for the org whose repo I want to enable Travis for (incidently I'm an admin there so I could just click "grant access")
- Went back to Travis-CI to my profile and clicked on the org in question in the left column
- Toggled the switch for the repo and it worked :joy_cat:

**Comment by jezdez** [comment]
Closing this issue since it's "fixed" for me. Feel free to reopen if others also see it.

**Comment by drogus** [comment]
@fixe could you try this procedure again and see if you can grant access to Travis CI on GitHub oauth authorization page? There could be also a list of orgs with their status: "Organizations determine whether the application can access their data.":

![](http://cl.ly/image/0F2H2a2n0A3S/Image%202015-01-27%20at%2010.41.51%20am.png)

Do you see a ✓ next to the org you're having trouble with?

**Comment by fixe** [comment]
@drogus working fine now, thanks.

**Comment by vzrenggamani** [comment]
ITS WORK :) THANKS 💯

**Comment by kblicharski** [comment]
Ran into this issue, the fix @jezdez mentioned worked for me. Still very frustrating.
