### ISSUE TITLE
Docker build: install aws cli without sudo

### ISSUE THREAD

**Issue by mfornasa** [travis-ci/travis-ci#3139]
I need to install AWS command line interface during a "sudo:false" build.
I used to do something like:
`sudo pip install awscli`

It should be possible to install them without sudo (http://docs.aws.amazon.com/cli/latest/userguide/installing.html#install-bundle-user) but It would be useful to have it using a .travis.yml directive.

**Comment by jtangelder** [comment]
:+1:

**Comment by BanzaiMan** [comment]
```yaml
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
```
should do.

**Comment by jtangelder** [comment]
Awesome, works like a charm

**Comment by BanzaiMan** [comment]
Closing this, since it a reasonable workaround exists. (A directive in `.travis.yml` is an overkill in my opinion.)

**Comment by eksperimental** [comment]
:+1: thank you guys for this one

**Comment by ASCrookes** [comment]
This also worked for me in case anyone stumbles onto this

**Comment by imgarylai** [comment]
I got this 
```
$ pip install --user awscli
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

Should I remove `--user` argument?

**Comment by alexjurkiewicz** [comment]
> Should I remove `--user` argument?

Yes.

**If you use the `python` image**, set this in `.travis.yml`:
```
language: python
cache: pip
```
And run `pip install aws-cli`

**If you use another image**, set this in `.travis.yml`:
```
cache:
  directories:
  - $HOME/.local
```
And run `pip install --local aws-cli`

**Comment by tsal** [comment]
@alexjurkiewicz  - unfortunately, `pip install --local aws-cli` won't work.  I don't believe `--local` is a valid flag for pip. I think you mean `--user`.

**Comment by alexjurkiewicz** [comment]
Thanks, updated my comment
