### ISSUE TITLE
Trouble deploying to S3 with an Ember.js app

### ISSUE THREAD

**Issue by tubbo** [travis-ci/travis-ci#3142]
Hi guys, I'm trying to deploy my Ember.js app to Amazon S3 using the Travis deploy tool. You can see the [whole log right here](https://travis-ci.org/tubbo/blog/builds/48298314), but the most relevant part is at the bottom when deployment fails the build:

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:375:in 
`return_or_raise': Authorization header is invalid -- one and only one ' ' (space) required 
(AWS::S3::Errors::InvalidArgument)
```

I'm not sure what's causing this. It might be [some bad travis.yml configuration](https://github.com/tubbo/blog/blob/master/.travis.yml)...but I followed the docs precisely and it didn't work. After removing a bunch of the special static website config that I was using and still observing the error, I began to question whether I've found a bug with S3 deployments.

**Comment by Joshua-Anderson** [comment]
Sorry you're having trouble. The build you link to is throwing a error saying you need to include your aws access key.

**Comment by BanzaiMan** [comment]
@tubbo https://github.com/tubbo/blog/blob/e22e55c036683c3a8bad739d36746b25816ef1d0/.travis.yml#L28-L34

does not have values for `access_key_id` and `secret_access_key`. Please supply them. (See http://docs.travis-ci.com/user/deployment/s3/.)

**Comment by tubbo** [comment]
oh hey, that might be what was going on :) sorry about that...
