### ISSUE TITLE
Haskell : cannot install hxt-regex-xmlschema 

### ISSUE THREAD

**Issue by alexDarcy** [travis-ci/travis-ci#3144]
Hi,
My Travis build fails with :

```
 The package 'hxt-regex-xmlschema' requires Cabal library version
 -any && >=1.18 but no suitable version is installed.
```

The full log is here : https://s3.amazonaws.com/archive.travis-ci.org/jobs/48392047/log.txt. Here is my cabal file :

```
build-depends: base,  hxt, aeson, aeson-pretty, bytestring, text
```

Can I force a cabal update ?

**Comment by BanzaiMan** [comment]
Strange. The installed version is 1.18.0.2 Why is this the version check failing? https://travis-ci.org/BanzaiMan/travis_production_test/builds/48394333#L101

**Comment by BanzaiMan** [comment]
This has become stale. If you are seeing problems with `dist: trusty`, do open a new issue.
