### ISSUE TITLE
Stuck in 'Please wait while we synchronize your data from GitHub'

### ISSUE THREAD

**Issue by Dudemullet** [travis-ci/travis-ci#3146]
Been waiting for more than half an hour, seems to be stuck on infinite loop, since its always sending the same 2 `OPTIONS` and `GET` requests

**Comment by joshk** [comment]
Thanks for reporting this issue.

I've reset the 'lock' around the 'syncing' logic.

You can resync your account and everything should be good to work.

Have a great day

**Comment by Dudemullet** [comment]
Thanks, is there anything I did or something I can do in the future on my part to try and avoid this issue happeniing again ?

**Comment by BanzaiMan** [comment]
This is known to happen every now and then, unfortunately. We have plans to improve this in the future.

Thanks for your patience.

**Comment by Dudemullet** [comment]
Thank you
