### ISSUE TITLE
Could not fetch .travis.yml from GitHub

### ISSUE THREAD

**Issue by lite3** [travis-ci/travis-ci#3147]
https://api.travis-ci.org/jobs/48589879/log.txt?deansi=true

**Comment by roidrage** [comment]
Sorry, but what's the bug or problem you're reporting?

**Comment by lite3** [comment]
i build https://travis-ci.org/lite3/DragonBonesCPP , i got it. 

> Using worker: worker-linux-9-2.bb.travis-ci.org:travis-linux-8
> Could not fetch .travis.yml from GitHub.
> /home/travis/build.sh: line 2: travis_terminate: command not found
> Done. Your build exited with .
> /home/travis/build.sh: line 5: travis_terminate: command not found

I think I should report to you . my project has `.travis.yml` file at root dir.

**Comment by roidrage** [comment]
Can you push another commit and see if this was a one-off problem?

**Comment by lite3** [comment]
I rebuild, it is still.

**Comment by roidrage** [comment]
Are you pushing another commit (new build as requested above) or rebuilding an existing build?

**Comment by lite3** [comment]
it is ok when I push an new commit.
