### ISSUE TITLE
Fastly name not resolved

### ISSUE THREAD

**Issue by dmathieu** [travis-ci/travis-ci#3151]
I've been getting those errors from time to time while using Travis Pro since yesterday:
![screen shot 2015-01-30 at 11 07 52 am](https://cloud.githubusercontent.com/assets/9347/5974074/572b88e6-a870-11e4-8a8f-63221ea7e53c.png)

**Comment by joshk** [comment]
Hey @dmathieu 

Are you still seeing these errors?

Have you tried another browser? Are you using Chrome?

Thanks,

Josh

**Comment by dmathieu** [comment]
I am using chrome. I haven't been seeing those errors again so far. I haven't been using travis too much with the week-end either though.
I'll let you know at the end of the day if I still see the issue.

**Comment by dmathieu** [comment]
Closing, I haven't seen it today. Will let you know if it happens again.

**Comment by dmathieu** [comment]
I'm getting it again right now :crying_cat_face:

**Comment by BanzaiMan** [comment]
Hmmm. Can you resolve this host outside of Chrome?

**Comment by dmathieu** [comment]
It's not happening anymore. I'll try with safari and firefox when I see it again.

**Comment by dmathieu** [comment]
I'm seeing it happening in an other app at the moment, not only in Chrome.
This seems to be a fastly issue though, as it doesn't appear for travis.

**Comment by roidrage** [comment]
Is this still occurring?

**Comment by dmathieu** [comment]
Not recently, but I got the (fairly bad) habit of not relying on streaming anymore, and reloading the page.

**Comment by joshk** [comment]
@dmathieu I'll close this issue for now, but if you see it happen again please let us know and we can dive in deeper.
