### ISSUE TITLE
Stuck on Synchronizing from GitHub

### ISSUE THREAD

**Issue by rpearce** [travis-ci/travis-ci#3153]
I've seen plenty of issues having to do with this

```
Please wait while we synchronize your data from GitHub...
```

*Short Term*
Could you manually sync me for now?

*Long Term*
I see in my Travis Accounts manager that `thoughtbot`, which has `533` repos, is included; however, I have no interest in watching thoughtbot's repos -- could it be that it is stuck trying to sync those, as well as the `326` I have under `Articulate`? How could I remove thoughtbot from my account? Would this fix the issue?

**Comment by BanzaiMan** [comment]
@rpearce I've manually reset the status and resync'd data for you.

This is a known problem, and we are looking to improve this for the future. (Currently, there is no way to dissociate the user from a GitHub organization.)

**Comment by rpearce** [comment]
Awesome, it's working. Is the appropriate method of reporting this via GH issues?

**Comment by BanzaiMan** [comment]
Hi, @rpearce Great to hear that it's working for you. For now, I suggest getting in touch with us at support@travis-ci.com if this happens again.

I'm closing this now.
