### ISSUE TITLE
Composer outdated, could not load dependency

### ISSUE THREAD

**Issue by pawelbaranski** [travis-ci/travis-ci#3154]
you can see the build output here:

https://travis-ci.org/devhelp/piwik-api/jobs/48987393

**Comment by mwjames** [comment]
You could just call `composer self-update` before the `composer install` command.

**Comment by pawelbaranski** [comment]
O.o... thank you :)

**Comment by BanzaiMan** [comment]
Well, I suppose we should call that on our side regardless.

**Comment by BanzaiMan** [comment]
Time-based warning has been addressed in our documents: https://github.com/travis-ci/docs-travis-ci-com/commit/786fa7db9e87344c35674431585cfab3f1cb029c

Updating on users' behalf is probably unnecessary.
