### ISSUE TITLE
Can not build dart project

### ISSUE THREAD

**Issue by valotas** [travis-ci/travis-ci#3156]
Using the following `travis.yml`
```
language: dart
dart:
  - stable
  - dev
```

I get a nice [error](https://travis-ci.org/valotas/mustache4dart/builds/49074964) that only `dev` and `stable` are supported!

@a14n, @devoncarew, @sethladd

**Comment by a14n** [comment]
It's a [known issue](https://github.com/travis-ci/travis-build/pull/357#issuecomment-72166447) that should be fixed in the next days. /cc @BanzaiMan

**Comment by BanzaiMan** [comment]
It'll go live Monday. Sorry about the delay.

**Comment by sethladd** [comment]
Thanks for trying it out, @valotas !
