### ISSUE TITLE
APT whitelist request for enchant

### ISSUE THREAD

**Issue by dantleech** [travis-ci/travis-ci#3157]
Enchant is a "Wrapper for various spell checker engines". We use it for spell checking sphinx documentation.

**Comment by dantleech** [comment]
Hi, I added the `addons.apt_packages` key as follows:

https://github.com/symfony/symfony-docs/pull/4917/files#diff-354f30a63fb0907d4ad57269548329e3R10

But the package (`enchant`) doesn't seem to be installed:

https://travis-ci.org/symfony/symfony-docs/builds/49948563

**Comment by BanzaiMan** [comment]
I can't figure out why yours failed. It is working for me. https://travis-ci.org/BanzaiMan/travis_production_test/builds/49951423#L76 (https://github.com/BanzaiMan/travis_production_test/blob/af5a8a0859418b0d40ca48169058501e4059fb8a/.travis.yml)

**Comment by dantleech** [comment]
Hmm, seems only not to work on forked repositories, created an issue:

https://github.com/travis-ci/travis-ci/issues/3199
