### ISSUE TITLE
all jobs starting at once causing issues.

### ISSUE THREAD

**Issue by jdalton** [travis-ci/travis-ci#3159]
Now on commits almost all jobs are running at once. See https://travis-ci.org/lodash/lodash-cli.
This causes an issue with my saucelabs runs that assumed 3 runs would be going at any one time. I've set the concurrent runs to 3 in the travis-ci setting but it doesn't seem to be respecting the setting.

![](https://cloud.githubusercontent.com/assets/4303/5994907/cc92ca84-aa39-11e4-9b97-e3a031843902.png)

**Comment by BanzaiMan** [comment]
You can limit the number of jobs that can run simultaneously on a repo in the settings page. In this case, https://travis-ci.org/lodash/lodash-cli/settings. Please try it.

**Comment by BanzaiMan** [comment]
Sorry. I overlooked that you've set this already. This seems like a bug. We'll investigate.

**Comment by BanzaiMan** [comment]
Hi, there. A fix has been deployed.

I'm closing this optimistically, but if you still see problems, do let us know.

**Comment by jdalton** [comment]
Ok cool. Thanks!
