### ISSUE TITLE
Failed to transfer file. Return code is: 502 , ReasonPhrase:Bad Gateway

### ISSUE THREAD

**Issue by karussell** [travis-ci/travis-ci#3160]
In the recent days I often get connection issues when downloading via maven (but only on travis). Is there a problem at travis or is this apache? Also it seems to happen only for jdk8 (I guess this is because jdk8 is installed on only a destinct set of servers)

'Using worker: worker-linux-027f0490-1.bb.travis-ci.org:travis-linux-9'

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project graphhopper: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-compiler-plugin:jar:3.1 -> org.apache.maven.shared:maven-shared-incremental:jar:1.1 -> org.apache.maven:maven-core:jar:2.2.1 -> org.apache.maven:maven-settings:jar:2.2.1 -> org.codehaus.plexus:plexus-interpolation:jar:1.11: Failed to read artifact descriptor for org.codehaus.plexus:plexus-interpolation:jar:1.11: Could not transfer artifact org.codehaus.plexus:plexus-interpolation:pom:1.11 from/to central (https://repo.maven.apache.org/maven2): Failed to transfer file: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.pom. Return code is: 502 , ReasonPhrase:Bad Gateway. -> [Help 1]

**Comment by BanzaiMan** [comment]
Sorry about the issue. Could you point to build logs that shows this problem? Oracle JDK 8 should be available on all build images.

**Comment by karussell** [comment]
Sorry, it looks like the logs got overwritten when I restarted the job (was hoping it just created a separate job). Will report back when I get it again and feel free to close within a month ;)

**Comment by karussell** [comment]
Please see these logs where a similar problem occured: https://travis-ci.org/graphhopper/graphhopper/jobs/50259455

**Comment by BanzaiMan** [comment]
Does your repo require `sudo`? If not, could you try container builds? http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

It has overall better network connection.

**Comment by karussell** [comment]
Thanks, this is working! Will report back if this fails in the future.

Are you planning to add a special repository manager for java projects? This would often avoid going out to maven central and could speed up the build.
