### ISSUE TITLE
Add support for running browser tests in dart builds.

### ISSUE THREAD

**Issue by bgourlie** [travis-ci/travis-ci#3162]
Support running browser tests using content_shell for Dart builds.

**Comment by a14n** [comment]
See the [related PR](https://github.com/travis-ci/travis-build/pull/377).

**Comment by kevmoo** [comment]
Fixed? https://github.com/travis-ci/travis-build/pull/377

**Comment by a14n** [comment]
Correct.
@BanzaiMan or @bgourlie : could you close this issue ?

**Comment by kevmoo** [comment]
Ping to close? @BanzaiMan or @bgourlie
