### ISSUE TITLE
Minor bug: Composer packages using relative paths to local git need to be explicit

### ISSUE THREAD

**Issue by onnimonni** [travis-ci/travis-ci#3163]
Hey!

Just noticed that relative composer packages as:
```json
"repositories": [
        {
            "type": "vcs",
            "url": "../"
        }
]
```
[Won't work](https://travis-ci.org/Koodimonni/Composer-Dropin-Installer/builds/49222789).

But [they work](https://travis-ci.org/Koodimonni/Composer-Dropin-Installer/builds/49223298) when using .git repo explicitly:
```json
"repositories": [
        {
            "type": "vcs",
            "url": "../.git"
        }
]
```

I realised this when testing my custom [composer installer plugin](https://github.com/Koodimonni/Composer-Dropin-Installer). And both scenarios work in local development (OS X).

Is this because the relative git repo isn't bare git repo?

**Comment by stof** [comment]
@onnimonni this is not a Travis issue. It is a misuse of Composer, which indeed expects getting a path to the git repo, not to the git working copy. When using a non-bare repo, the git repo is the ``.git`` folder.

**Comment by BanzaiMan** [comment]
OK. I'm closing this as a non-issue. Thanks for reporting.
