### ISSUE TITLE
Bug: OCLint broken on OS X Machines

### ISSUE THREAD

**Issue by caffeineflo** [travis-ci/travis-ci#3165]
Executing `oclint --version` crashes all scripts and stops further execution. The binary seems to be broken and outdated (judging from the last blog post mentioning the version). All other actions (creating a report) fail as well with either crashes or common error known at v0.7 (currently at v0.8.1).
In addition that, docs.travs-ci.org don't reflect the existence of oclint at all. So that would be something to fix as well.

**Comment by evils** [comment]
@henrikhodne If you let me know how I can contribute a verification, I'm more than happy to do that.

**Comment by solarce** [comment]
Is this still relevant? If so, please make note of which version of `osx_image:` you're using and a link to a build URL showing the issue

Thanks,

**Comment by BanzaiMan** [comment]
Closing, as it's become stale.
