### ISSUE TITLE
Version 'iojs' not found - try `nvm ls-remote` to browse available versions.

### ISSUE THREAD

**Issue by JiangJie** [travis-ci/travis-ci#3166]
```javascript
Using worker: worker-linux-ac3bc85a-1.bb.travis-ci.org:travis-linux-5

$ git clone --depth=50 --branch=master git://github.com/JiangJie/node-proxy.git JiangJie/node-proxy
Cloning into 'JiangJie/node-proxy'...
remote: Counting objects: 144, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 144 (delta 3), reused 0 (delta 0)
Receiving objects: 100% (144/144), 21.94 KiB | 0 bytes/s, done.
Resolving deltas: 100% (55/55), done.
Checking connectivity... done.
$ cd JiangJie/node-proxy
$ git checkout -qf 48e142b03a80e49a65c12ff83b3a0d18e8acaf57
0.12s$ nvm install iojs
Version 'iojs' not found - try `nvm ls-remote` to browse available versions.
The command "nvm install iojs" failed and exited with 3 during .
Your build has been stopped.
```

**Comment by roidrage** [comment]
As per the upcoming build update is only scheduled for this afternoon http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/, io.js isn't yet supported, but should be available afterwards.

**Comment by JiangJie** [comment]
Thanks, I'll try later.

**Comment by dougwilson** [comment]
It is well after 15:00 UTC and nvm still shows up as 0.20.0 in builds, which is not high enough to support io.js.

**Comment by dougwilson** [comment]
I appologize for the unnecessary comment; the update page was in my browser cache. I see there is an update on the page now saying it's been rolled back http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#Schedule

**Comment by BanzaiMan** [comment]
Sorry about that. We'll schedule the update soon.
