### ISSUE TITLE
Option to prioritize PRs over branches (or vice versa)

### ISSUE THREAD

**Issue by Fryguy** [travis-ci/travis-ci#3169]
In our repo, we have many PRs come in at once, and at the same time we are merging PRs.  I would really like to have the incoming PRs prioritized over the merges on the master branch.  When we merge a PR, we already know it's green, so there's a high probability it will also be green on master, and so we are less likely to care about their status as readily as PRs.

I think a project option or a .travis.yml setting could accomplish this.

I looked at #1155, and it's sort of related, but not the same.

**Comment by roidrage** [comment]
This looks like a duplicate of #2801.

**Comment by Fryguy** [comment]
Oh thanks!  Also laughing at the fact that the replies in that thread are all my colleagues.
