### ISSUE TITLE
build hangs forever

### ISSUE THREAD

**Issue by digitalkaoz** [travis-ci/travis-ci#317]
e.g. http://travis-ci.org/#!/digitalkaoz/digitalkaoz.net/builds/311876 hangs since more than 24 hours, and blocks following builds...

the build script exited with 0, dont know what todo, maybe someone can investigate and kill the build?

**Comment by johannesjo** [comment]
Same issue for me https://travis-ci.org/johannesjo/ng-fab-form/builds/52178505

**Comment by david-vega** [comment]
@johannesjo had the same problem today and I fixed adding this `sudo: false` to `.travis.yml`
