### ISSUE TITLE
Handle click tracking on main domain.

### ISSUE THREAD

**Issue by aenario** [travis-ci/travis-ci#3171]
I can understand you might for some reason want to measure emails click-through. However, on slow connection (mobile), the additional round-trip to clicks.travis-ci.org is a bother. It would be great if you could handle it server-side at travis-ci.org.

**Comment by roidrage** [comment]
Thanks for bringing this up, and I can certainly understand that this causes extra redirects.

The click tracking isn't done by our application but a mail provider we're using, so I'm afraid this is not an option right now, sorry.
