### ISSUE TITLE
Travis-CI fails to parse .travis.yml with UTF BOM mark

### ISSUE THREAD

**Issue by MartinNowak** [travis-ci/travis-ci#3172]
It took us quite a while to understand why the language was detected incorrectly.
The reason was a [Byte order mark](http://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) in the .travis.yml file.
The YAML file seems to be ignored (swallowed exception maybe?) and a default ruby build is triggered.
https://travis-ci.org/MartinNowak/memutils/builds/49356629

**Comment by BanzaiMan** [comment]
Sorry it took me a while to realize it, but I am going to close this in favor of #4839.
