### ISSUE TITLE
Issues with Sonatype repositories on Docker-based infrastructures

### ISSUE THREAD

**Issue by pdalpra** [travis-ci/travis-ci#3174]
We've been having issues on https://travis-ci.org/gatling/gatling-highcharts (and others repos) when downloading some dependencies from [Sonatype OSS Snapshots repository](https://oss.sonatype.org/content/repositories/snapshots/).

We've switched to the new Docker-based infrastructure a while ago but, after disabling it, these issues were fixed.

This is the kind of errors we have when attempting to download the dependencies:

```
[error] SERVER ERROR: Service Temporarily Unavailable url=https://oss.sonatype.org/content/repositories/snapshots/io/gatling/gatling-recorder/2.2.0-SNAPSHOT/maven-metadata.xml
[error] SERVER ERROR: Service Temporarily Unavailable url=https://oss.sonatype.org/content/repositories/snapshots/io/gatling/gatling-recorder/2.2.0-SNAPSHOT/gatling-recorder-2.2.0-SNAPSHOT.pom
```

**Comment by henrikhodne** [comment]
Are you seeing these errors all the time or only intermittently?

**Comment by pdalpra** [comment]
We've seen those errors all the time since 3-4 days.

**Comment by henrikhodne** [comment]
Can you link me to a build where you see this issue?

**Comment by pdalpra** [comment]
Of course : https://travis-ci.org/gatling/gatling-highcharts/builds/49433461
This is a previous build I restarted just a few minutes ago, which uses both Docker-based infrastructure and caching.

**Comment by buckett** [comment]
We're also seeing these issue on our Docker based caching build:

https://travis-ci.org/sakaiproject/sakai

We expect oss.sonatype.org to return 404s for some URLs but they come back as 503s.

**Comment by henrikhodne** [comment]
We don't inject any kind of proxy for the build environments, so that means that the Sonatype site is actually returning 503s. I wonder if there's some kind of rate limiting in place causing this (all requests from the Docker infrastructure come from the same IP as we have a NAT in place). Is there a way to get in touch with Sonatype about this?

**Comment by buckett** [comment]
I think the way to get support on the Sonatype OSS repository is to file a issue in:

https://issues.sonatype.org/browse/OSSRH

**Comment by gehel** [comment]
Same problem for me : https://travis-ci.org/jmxtrans/jmxtrans2/builds/49650391

**Comment by BanzaiMan** [comment]
Reported here: https://issues.sonatype.org/browse/OSSRH-13718

**Comment by BanzaiMan** [comment]
All right. The JIRA issue above has ben resolved, so I'm closing this one, too.

If you are still seeing problems, let us know.
