### ISSUE TITLE
iojs - nvm install iojs-v1.0.4

### ISSUE THREAD

**Issue by alexsantos** [travis-ci/travis-ci#3175]
After the deploy of 03/02/2015 the tests of my module [alexsantos/soap-cli-simple](https://travis-ci.org/alexsantos/soap-cli-simple) passed but now it is erroring with:

```
Version 'iojs-v1.0.4' not found - try `nvm ls-remote` to browse available versions.
```

**Comment by roidrage** [comment]
Sorry about that.

The deploy was rolled back and will be rescheduled as per https://twitter.com/travisci/status/562678057635704834
