### ISSUE TITLE
tag with same name as a branch might break builds

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#3178]
If there is a tag with the same name as a branch, we might fail at checking out a specific sha, as it's not being being fetched with the clone. We should make the ref an explicit branch ref when cloning to fix this.

**Comment by joshk** [comment]
Hmmmmm, interesting, @drogus could you weigh in with some advice?

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #1590.
