### ISSUE TITLE
Error During Pull Request Commit Build from Fork to Organization Repo

### ISSUE THREAD

**Issue by bhermanmit** [travis-ci/travis-ci#3180]
Travis errored during a test where I set up a temporary organization from my user account and forked it, and then submitted a pull request from my fork to the organization.

When I did this, Travis tried to run the following code during the commit build:

```bash
git clone --depth=50 --branch=travis_pull git://github.com/bherman53/openmc_travis.git bherman53/openmc_travis
```

This is trying to get the travis_pull branch from the organization repo, instead of the fork. The fork (bhermanmit/openmc_travis) is the only place where this branch exists.

**Comment by roidrage** [comment]
Could you point us to the builds where you're seeing this issue?

**Comment by bhermanmit** [comment]
The build location is at:

https://travis-ci.org/bherman53/openmc_travis/builds/49201876

The pull request is at:

https://github.com/bherman53/openmc_travis/pull/1

**Comment by roidrage** [comment]
The build you've linked to is for a branch push, which seems correct given your own history on the projects:

![image](https://cloud.githubusercontent.com/assets/5373/6059273/d1c0ad48-ad2f-11e4-84af-8600e34c1958.png)

It seems like you pushed a branch to bherman53/openmc_travis, but deleted it quickly thereafter, likely before the build kicked off, so Travis CI couldn't find the referenced branch.

The build for the pull request is [here](https://travis-ci.org/bherman53/openmc_travis/builds/49201995), and it seems to show the correct behaviour. Note that the link in your pull request also links to the correct build.

![openmc_travis 2015-02-05 12-12-18](https://cloud.githubusercontent.com/assets/5373/6059309/40b6a77a-ad30-11e4-8aab-419ef0eed4f3.jpg)

**Comment by BanzaiMan** [comment]
Is further investigation necessary?

**Comment by bhermanmit** [comment]
Nope, I understand, thanks for the explanation.
