### ISSUE TITLE
Get dependencies and run tests by default for Elixir

### ISSUE THREAD

**Issue by optikfluffel** [travis-ci/travis-ci#3182]
First of all: Thanks so much for supporting [Elixir](http://elixir-lang.org) with your [latest environment update](http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/). :heart: 
It would be great if you could also support [Mix](http://elixir-lang.org/getting_started/mix_otp/1.html), which is a default tool Elixir ships with, to [get external dependencies](http://elixir-lang.org/getting_started/mix_otp/7.html#7.1-external-dependencies) via `mix deps.get` and [run the tests](http://elixir-lang.org/getting_started/mix_otp/1.html#1.3-running-tests) via `mix test` by default without the need to specify this steps in the `.travis.yml`.

**Comment by BanzaiMan** [comment]
This is pretty straightforward to implement. Do you have a sample repo that I can use to test?

**Comment by optikfluffel** [comment]
[elixir-lang/plug](https://github.com/elixir-lang/plug) should work although it still uses the old Erlang stuff in it's [`.travis.yml`](https://github.com/elixir-lang/plug/blob/master/.travis.yml).
Also I'm not sure right now if I maybe missed `mix local.hex` as a step above to get [Hex](https://hex.pm) installed or if this happens automatically.

**Comment by optikfluffel** [comment]
@BanzaiMan ok, I tried and the `mix local.hex` command should be added too, to be able to install these dependencies, otherwise you'll get asked `Shall I install hex? [Yn]` on the command line, which should of cause time out after a while at Travis. Sorry.

PS: Here's a version of [plug's `travis.yml`](https://github.com/optikfluffel/plug/blob/update-travis-configuration/.travis.yml) how I think it should look in the end.

**Comment by BanzaiMan** [comment]
You need:

```
mix local.hex --force
mix deps.get --only test
```

Or did I miss something?

**Comment by optikfluffel** [comment]
The `--force` also updates the local hex installation, I'm not sure we need that 'cause we're starting with a clean system anyway (so ne latest should be installed by default because there is no 'old one' right?)
For the `--only test` option I'm not sure, but maybe that's a sane default anyway. Maybe @josevalim could help out with his intentions here?

**Comment by optikfluffel** [comment]
I [spoke with him on Twitter](https://twitter.com/josevalim/status/563398286959476737) and [read the docs](http://elixir-lang.org/docs/stable/mix/Mix.Tasks.Local.Hex.html), long story short:
```
mix local.hex --force
mix deps.get
```

**Comment by BanzaiMan** [comment]
Test → https://staging.travis-ci.org/BanzaiMan/plug/builds/405690

Fixed by https://github.com/travis-ci/travis-build/commit/f7d1c13745d00ad9e48380d39fa21e2c4a583139 and subsequent commits. It's been deployed.

**Comment by josevalim** [comment]
This is great, thanks everyone! Quick question: should we support precompiled files too? Today we make precompiled files available in github and s3. That's what we use in plug:

https://github.com/elixir-lang/plug/pull/179/files#diff-354f30a63fb0907d4ad57269548329e3L8

Should we support this directly in the cookbook or should we add it to kiex? I assume it would save time on building elixir for every build?

**Comment by optikfluffel** [comment]
I think kiex would be the best place for that in general, but I have no idea if this would speed up things at travis or if they somehow cache that anyway, [the logs](https://travis-ci.org/elixir-lang/plug/jobs/49672305#L87-L90) say it only took a second anyway so I guess it simply is installed on their container/vm?

**Comment by BanzaiMan** [comment]
Right now, Elixir 1.0.2 is pre-installed with kiex on the build image. If you want a different version, my understanding is that kiex will install it on demand.

Not sure we will be pre-installing multiple versions of Elixir going forward yet.

**Comment by josevalim** [comment]
Ah , awesome. Thanks @BanzaiMan!

Elixir is really tiny (2.5MB zipped) so if there is ever a need to pre-install more versions it shouldn't be a concern! Thanks for adding Elixir support!
