### ISSUE TITLE
Unexpected upgrades to pip and setuptools in the Python environment break builds.

### ISSUE THREAD

**Issue by moorepants** [travis-ci/travis-ci#3190]
Before a couple of days ago the version of pip installed in the Python virtualenv was 1.5.6. It is now 6.0.7. The 6 series introduced a number of backwards incompatibilities. These incompatibilities are also in setuptools ~> 8.0, which also seems to have been upgraded to 12.0.5.

It would be nice if Travis had pinned versions of software so that users' build systems are not taken down by unannounced software upgrades. I have not been able to find an announcement about these changes. I'm not sure how many people it may affect, but it would be nice to have some warning mechanism or an option for users to pin to specific environment recipes so the user can choose when to upgrade.

**Comment by BanzaiMan** [comment]
Please try https://github.com/travis-ci/travis-ci/issues/3060#issuecomment-73227013. I'm closing this as this is addressed by that issue.
