### ISSUE TITLE
Webhooks are not delivered to subsequent endpoints if one fails

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3192]
When there are more than one webhook endpoint is defined, and the first one fails, subsequent delivery attempts do not seem to be made.

I looked at the code, but could not reason why it should behave this way, but there are some anecdotal evidences that suggest this bug.

**Comment by crunis** [comment]
Please consider the referenced PR, when the webhook times out (due to packet drop by a firewall) Faraday generates an error of type "Faraday::Timeout" that is not captured by a generic rescue. 
https://github.com/travis-ci/travis-tasks/pull/51

**Comment by BanzaiMan** [comment]
This issue should be resolved.
