### ISSUE TITLE
.com Sessions do not stick on Safari 8.0.3, OS X 10.10.2

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3193]
A user reports:

> When I want to see something about the builds in this repository I have to click "Travis CI for Private Repositories" button and then "Start Trial" every time I want to check something. Why can't I see the reop in the left pane right after I launch the website?

I was able to reproduce this with the same setup on my VM.

**Comment by wczekalski** [comment]
Waiting for a solution!

**Comment by BanzaiMan** [comment]
This does not appear to happen on .org.

**Comment by wczekalski** [comment]
Let me test, but in my machine it actually works on `.com`

**Comment by wczekalski** [comment]
It doesn't but I have to log in every time I enter the website

**Comment by wczekalski** [comment]
@BanzaiMan AFAIK when I enter https://travis-ci.com it should redirect me to https://magnum.travis-ci.com/repositories if I logged to Travis once, right?

**Comment by roidrage** [comment]
I'm closing this as this has been reported as fixed.
