### ISSUE TITLE
Is the Haskell Platform actually installed?

### ISSUE THREAD

**Issue by Blaisorblade** [travis-ci/travis-ci#3197]
While investigating #3196, I realized another setup inconsistency. It seems that the cookbook code installing the Haskell platform is dead — you're just installing ghc from the GHC tarballs, and tools separately — and then, quite reasonably, you don't install the platform in addition.

More in particular, the platform seems not there: in particular, #2221 (upgrading alex and happy) hasn't been solved by #2690 (upgrading GHC and the Haskell Platform), seemingly because the [update of the Haskell Platform](https://github.com/travis-ci/travis-cookbooks/commit/62860715012a308098be54db971886fe58f07e4b#diff-81a323c14404cbb1012e810086c1a40cL2) changed dead code. Finally, I don't see Haskell Platform-specific packages (say, attoparsec) available in machines (see for instance `ghc-pkg list` output here: https://travis-ci.org/Blaisorblade/pts/jobs/49888345).

[haskell.yml](https://github.com/travis-ci/travis-cookbooks/blob/a68419ebe0ce92876a70534cd145ddd931d0feee/vm_templates/common/haskell.yml) calls `haskell::multi`, but nothing else.

BTW, even after the changes in #2690, [Travis docs mention the Haskell Platform 2012.2.0](http://docs.travis-ci.com/user/ci-environment/#Haskell-VM-images). Would you please stop mentioning the Haskell Platform?

**Comment by BanzaiMan** [comment]
This has become unfortunately stale. Please test again, and if the issue persists, please open a new issue.
