### ISSUE TITLE
apt_packages not installing on forked pull request builds (?)

### ISSUE THREAD

**Issue by dantleech** [travis-ci/travis-ci#3199]
I have configured `addons.apt_packages` to install `enchant`, but the setting seems to have no effect on the following pull request from a fork:

https://github.com/symfony/symfony-docs/pull/4917/files#diff-354f30a63fb0907d4ad57269548329e3R10

https://travis-ci.org/symfony/symfony-docs/builds/49948563

I have just tried it again on a pull request within the organization and it works:

https://github.com/symfony-cmf/symfony-cmf-docs/pull/637

Could it be that `apt_packages` only work on buids from within the organization? or is it something else?

**Comment by dantleech** [comment]
Just tested on the organization repository from a fork and I get the same problem:

https://travis-ci.org/symfony-cmf/symfony-cmf-docs/builds/49974587

So it would appear that you cannot currently use this feature from forked repositories.

**Comment by meatballhat** [comment]
See https://github.com/travis-ci/travis-core/pull/429

**Comment by msabramo** [comment]
I have this issue too:

https://travis-ci.org/bebraw/pypandoc/builds/50087355

**Comment by jck** [comment]
I think apt_sources needs to be added to the PR whitelist too?

**Comment by meatballhat** [comment]
@jck Yep, we're working on a comprehensive fix.  Sorry about the trouble!  See https://github.com/travis-ci/travis-core/pull/446 for updates.

**Comment by meatballhat** [comment]
Both `apt.packages` and `apt.sources` should work on PR builds now.  Thanks for your patience!
