### ISSUE TITLE
Project doesn't build, and I can not figure out why.

### ISSUE THREAD

**Issue by PFCKrutonium** [travis-ci/travis-ci#3200]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/49977264/log.txt

Scroll to the bottom... Can someone help?

Project https://github.com/PFCKrutonium/OpenRCT2Launcher

**Comment by joshk** [comment]
Have you tried running this on another computer?

Could this be related? `Tool /usr/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "My Project/Resources.resx,obj/Release/Launcher.Resources.resources"`

Please remember to cc to appropriate maintainers (you can find them at the top of the log)

**Comment by PFCKrutonium** [comment]
@joshua-anderson @akoeplinger @nterry[0m

As for running it on another computer, I only have Windows computers locally.

**Comment by Joshua-Anderson** [comment]
Have you tested your code with mono for windows?

**Comment by akoeplinger** [comment]
I added /v:diag to the xbuild command to enable verbose logging and it seems it fails at the Vbc compilation stage (though no exception/error is logged which is a bit weird?).

It looks like a Mono VB bug to me, which is unfortunate. I don't think we can do anything about it here, your best bet is filing a [bug report](https://bugzilla.xamarin.com) (note that VB support is kind of a side-project for Mono as the majority of code is C#).

Another option for you would be to investigate [AppVeyor](http://appveyor.com) as they build on Windows and use the Microsoft toolchain which should work fine (sorry Josh I know it's a competitor, just trying to come up with a solution for @PFCKrutonium :smile: ).

**Comment by PFCKrutonium** [comment]
@akoeplinger Thank you for taking the time to try for me :+1: and Telling me about that other site! :100:

**Comment by Joshua-Anderson** [comment]
@PFCKrutonium Good Luck! I'm sorry that you're having issues with mono.

**Comment by PFCKrutonium** [comment]
It's okay, it's not like its your fault, now is it? :P
