### ISSUE TITLE
Please support different versions of pypy

### ISSUE THREAD

**Issue by sontek** [travis-ci/travis-ci#3202]
Recently with http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/ the pypy installation was upgraded to pypy 2.5.   I would love to be able to test against 2.3 and 2.5 if possible.

**Comment by BanzaiMan** [comment]
@alex Thoughts? Currently our concern is the disk usage. We are unable to support too many runtimes at the moment. We can probably do the most recent and the one before (is PyPy 2.4 considered stable? if so, 2.4 & 2.5; if it's not, we can do 2.3 & 2.5).

Ideally, we can support on-demand installation, a la RVM, nvm, kiex, but I don't think we have that for Python, do we?

**Comment by alex** [comment]
@BanzaiMan I think last two makes sense for "included by default"; I' not sure if we have on-demand installation, that'd be awesome though! /cc @dstufft

**Comment by dstufft** [comment]
It depends on what you mean by on demand. pyenv can install things on demand and for PyPy it's going to install a binary package, however for CPython it's going to compile CPython as part of the installation step.

**Comment by BanzaiMan** [comment]
PyPy is now installed on demand, so I think this can be closed.
