### ISSUE TITLE
APT whitelist request for petsc

### ISSUE THREAD

**Issue by prudhomm** [travis-ci/travis-ci#3203]
Please add the petsc package to the white list
thanks in advance

**Comment by BanzaiMan** [comment]
Sorry, but that package is not supported on Precise. http://packages.ubuntu.com/precise/petsc

**Comment by BanzaiMan** [comment]
Ah. You meant this one. http://packages.ubuntu.com/source/precise/petsc

We've added libmpfr-dev and libgmp-dev. Does that suffice?

**Comment by BanzaiMan** [comment]
Or do you need http://packages.ubuntu.com/precise/petsc-dev?

**Comment by prudhomm** [comment]
Yes I really petsc and the development package ☺
Thanks in advance
C

**Comment by floli** [comment]
The package whitelisted is ```petsc```, but the package is actually ```petsc-dev``` (http://packages.ubuntu.com/search?keywords=petsc&searchon=names&suite=precise&section=all). ```petsc``` is not found and ```petsc-dev``` is disallowed. How to actually use petsc on container based infrastructure?

**Comment by prudhomm** [comment]
@floli @meatballhat indeed petsc-dev is needed, that's what I meant with development package
