### ISSUE TITLE
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

### ISSUE THREAD

**Issue by iziz** [travis-ci/travis-ci#3206]
in https://travis-ci.org/iziz/libPhoneNumber-iOS/builds/50189587

Always fail, I was updated README file. :(

**Comment by BanzaiMan** [comment]
Did you mean https://travis-ci.org/iziz/libPhoneNumber-iOS/builds/50185696? Was the problem perhaps transient?

**Comment by iziz** [comment]
Yes, but I tried many times.
Finally it works fine, too strange
