### ISSUE TITLE
APT whitelist request for libmemcached-dev

### ISSUE THREAD

**Issue by kitcambridge** [travis-ci/travis-ci#3213]
[`libmemcached-dev`](https://launchpad.net/libmemcached) supports the [Ruby](https://rubygems.org/gems/memcached), [Python](https://github.com/lericson/pylibmc), and [Go](https://github.com/varstr/gomc/) memcached clients that bind to the C client library. Handy for testing with the preinstalled memcached server.

**Comment by kitcambridge** [comment]
Thanks, @meatballhat! :star2:

**Comment by meatballhat** [comment]
![](http://maele.net/english/sonia/clip%20arts/High20Five_answer_2_xlarge.jpeg)

:heart:
