### ISSUE TITLE
Put the `to top` link under `follow log` button in build view

### ISSUE THREAD

**Issue by toeb** [travis-ci/travis-ci#3214]
When the machine is booting and no console output was generated the 'to top' link is above the 'follow log' button in the z-index.  

This is a minor nuisance when a build is booting and you want the log to follow directly.

**Comment by joshk** [comment]
Thanks for reporting this bug, we will get this fixed very shortly.

**Comment by toeb** [comment]
Also it seems that when you toggle follow log it goes will not be deactivated by clicking the `to top` link

**Comment by roidrage** [comment]
As we now don't display the log anymore when a build hasn't started yet, this should now be fixed.

![test-project-for-travis - travis ci 2015-07-24 12-22-05](https://cloud.githubusercontent.com/assets/5373/8872585/9b93076c-31fe-11e5-82ef-089c9b09198c.jpg)
