### ISSUE TITLE
Allow folks to opt-out of content_shell and test_runner install

### ISSUE THREAD

**Issue by kevmoo** [travis-ci/travis-ci#3215]
These installs take a *lot* of time when initializing a test.

Great if you want to use them, but if you're just testing console code with your own setup, it'd be awesome to be able to skip them.

CC @a14n , @seaneagan, @nicolasgarnier

**Comment by devoncarew** [comment]
+1. I think the slowness comes from installing all of `content_shell`'s dependencies. Having build scripts opt-in to installing content_shell would be great.

**Comment by pq** [comment]
+1!

**Comment by seaneagan** [comment]
I do think it's kind of nice to start from a blank pub cache, and just run `pub global activate test_runner` manually.  Folks might want to run `test_runner` through a task runner instead like `grinder`, and would want to avoid installing it twice.

**Comment by kevmoo** [comment]
FYI: in the mean time, I've managed to set up a very thin install of Dart for `source_gen` – https://github.com/kevmoo/source_gen.dart

Take a look for inspiration

**Comment by a14n** [comment]
There will be an opt-in once https://github.com/travis-ci/travis-build/issues/387 is merged.

**Comment by BanzaiMan** [comment]
PR has been merged and deployed.

**Comment by a14n** [comment]
@BanzaiMan Thanks !
