### ISSUE TITLE
Xcode 6.3 beta (Swift 1.2) Support

### ISSUE THREAD

**Issue by jeffh** [travis-ci/travis-ci#3216]
Swift 1.2 (and Xcode 6.3 beta was just released). It would be nice run tests against Swift 1.2 on Travis-CI.

Related project: [Quick#243](https://github.com/Quick/Quick/issues/243)

**Comment by peterprokop** [comment]
I think Xcode 6.3 beta is still under NDA - it can't be legally used in Travis VMs. But it's a shame that Xcode 6.2 & iOS SDK 8.2 aren't supported yet.

**Comment by jeffh** [comment]
According to [travis-ci](http://blog.travis-ci.com/2014-10-22-xcode-6-update-postmortem/), it seems like it might be possible for them to support beta versions.

**Comment by a2** [comment]
I was looking in [iOS Developer Program License Agreement](http://adcdownload.apple.com//Documents/license_agreements__ios_standard/iOS_Program_Standard_Agreement_20150309.pdf) but it's all legalese.

**Comment by aleffert** [comment]
Xcode 6.3 with Swift 1.2 goes public today. https://twitter.com/SwiftLang/status/585867047084503040

**Comment by masters3d** [comment]
Anything on this? Are you planning to move to 10.10.3 so we can have Xcode 6.3 support?

**Comment by felipesabino** [comment]
@masters3d I am also needing these updates, but I am very skeptical that it will be that soon as they are still working to have 6.2 running properly #3373

**Comment by masters3d** [comment]
The issue is not Xcode but the server not running 10.10

**Comment by Keithbsmiley** [comment]
Xcode 6.3's minimum supported OS version is 10.10

**Comment by mxcl** [comment]
Swift 1.2 is sad.

**Comment by 3lvis** [comment]
I need this too, would be great if you guys (TravisCI) made a priority.

**Comment by joshk** [comment]
I can promise everyone here it is a priority. Due to Xcode needing 10.10.3, we need to investigate upgrading our infrastructure to support this. We are also looking into options which may not require the upgrade.

We plan to have more information available next week.

**Comment by carloslozano** [comment]
:+1: - great news. I think Apple wants you to buy another box.

**Comment by carlad** [comment]
In case anyone missed the news we started public beta tests of a new image last week.

You can read more here:http://blog.travis-ci.com/2015-05-26-xcode-63-beta-general-availability/
