### ISSUE TITLE
ImageMagick dev version way out of day.

### ISSUE THREAD

**Issue by Danack** [travis-ci/travis-ci#3218]
It looks like when specifying the environment setting `IMAGEMAGICK_VERSION=dev` a quite old version of ImageMagick is used, instead of the most up-to-date one. e.g. [from here](https://travis-ci.org/mkoppanen/imagick/jobs/50271941#L3385)

> checking if ImageMagick version is at least 6.2.4... found version 6.6.9 Q16 

ImageMagick is currently on 6.9.0-5.

The Travis env setting I'm using is:

    - IMAGEMAGICK_VERSION=dev
    - IMAGEMAGICK_VERSION=6.8.7-0
    - IMAGEMAGICK_VERSION=6.7.5-3
    - IMAGEMAGICK_VERSION=6.6.0-9
    - IMAGEMAGICK_VERSION=6.5.3-10
    - IMAGEMAGICK_VERSION=6.4.0-11
    - IMAGEMAGICK_VERSION=6.3.4-10
    - IMAGEMAGICK_VERSION=6.2.3-6

**Comment by BanzaiMan** [comment]
ImageMagick is provided by http://packages.ubuntu.com/precise/imagemagick, which is at 6.6.9. If you need something newer, you'll need to figure out a way to provide it.

**Comment by Danack** [comment]
I don't understand how Travis pulls in ImageMagick versions, but setting the required version to 
IMAGEMAGICK_VERSION=6.8.7-0 [works fine](https://travis-ci.org/mkoppanen/imagick/jobs/50271942):

> checking if ImageMagick version is at least 6.2.4... found version 6.8.7 Q16 

It seems very odd that the dev version is so far behind the available versions.

**Comment by BanzaiMan** [comment]
Your build is pulling ImageMagick source and compiling it. https://travis-ci.org/mkoppanen/imagick/jobs/50271942#L97

**Comment by Danack** [comment]
oops, thanks.
