### ISSUE TITLE
Revert PHP5.2

### ISSUE THREAD

**Issue by garex** [travis-ci/travis-ci#3219]
* As a workaround try to downgrade xdebug to 2.1.4 for php5.2
https://github.com/xdebug/xdebug/blob/XDEBUG_2_1_4/xdebug_var.c
* If php5.3 builds with xdebug 2.2.7 then it's strange as it's also does not have const there
https://github.com/php/php-src/blob/PHP-5.3/Zend/zend_API.h
* Try to see in gcc compile options and how they differs between 5.2 and 5.3 — most possibly in 5.2 there could be some param like warning->error that is not in 5.3

**Comment by BanzaiMan** [comment]
Duplicate in spirit of #3152.
