### ISSUE TITLE
Update RubyMotion

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#3224]
> the default version of RubyMotion used on your build boxes is 2.33 (as of 6 Feb), and the current version of RubyMotion is 3.3

I see 3.2 on their releases https://github.com/HipByte/RubyMotion/releases

**Comment by MarkVillacampa** [comment]
@svenfuchs Hi Sven,

The Github releases in that repo are not really kept up to date, as users update their copy of Rubymotion via the 'sudo motion update' command, and not via git.

The latest version as of today is 3.6:

```
$ motion --version
3.6
```

**Comment by solarce** [comment]
We've been updating rubymotion in recent image updates. Which Xcode version(s) are you using?

**Comment by MarkVillacampa** [comment]
The latest version of RubyMotion (4.12) supports Xcode 7 and Xcode 8 Beta.
