### ISSUE TITLE
APT whitelist request for extra boost libs on trusty

### ISSUE THREAD

**Issue by xu-cheng** [travis-ci/travis-ci#3227]
It appears that the boost on trusty has extra libs.

```
libboost-tools-dev
libboost-atomic-dev
libboost-chrono-dev
libboost-context-dev
libboost-coroutine-dev
libboost-exception-dev
libboost-locale-dev
libboost-log-dev
libboost-random-dev
libboost-timer-dev
```

Also I wonder how to tell travis to use trusty instead of precise?

**Comment by BanzaiMan** [comment]
Did not run automated check because extra boost libs on trusty needs trusty

**Comment by BanzaiMan** [comment]
Automated running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'extra boost libs on trusty' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for extra boost libs on trusty' is ambiguous. Please specify only one.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/358.

        Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

        Thank you!
