### ISSUE TITLE
Can't stop Travis from tripping over Sauce Labs limits

### ISSUE THREAD

**Issue by vr2262** [travis-ci/travis-ci#3230]
Sometimes my Travis builds fail because there are too many active Sauce Connect tunnels. I tried limiting the number of concurrent builds on Travis to 5 (then 4...) but it still happens.

Here is an example: https://travis-ci.org/SEL-Columbia/dokomoforms/jobs/50537933

Even worse, due to #3091 the build stalls and I either have to wait for it to timeout or cancel it manually.

**Comment by joshk** [comment]
You should limit to 3 as Sauce only provides 3 concurrent VMs to Open Source projects.

**Comment by vr2262** [comment]
Ah, I see. The "allowed: 5" response made me think 5 was the limit.

**Comment by joshk** [comment]
Sorry, what `allowed: 5` response?

Can this issue be closed?

**Comment by vr2262** [comment]
The Travis log shows these messages:
```
12 Feb 19:52:05 - Error: POST https://saucelabs.com/rest/v1/vr2262sel/tunnels: HTTP response code indicated failure.
12 Feb 19:52:05 - Error: response: {"error": "Too many active tunnels: 5; allowed: 5"}.
12 Feb 19:52:05 - Error: failed to create tunnel.
```

In any case, yes, I'll close the issue. Thanks for your help.

**Comment by admc** [comment]
We are increasing our open source offering concurrency limit to 5, which should help with this.

**Comment by aicioara** [comment]
Not sure why this issue was closed. Is there a way for Travis CI to detect when this error is thrown and fail the build immediately, instead of stalling for 10 minutes? Thank you

**Comment by vr2262** [comment]
@aicioara 

This issue was closed because it's correct behavior; I was just confused by it.

The issue you want is this one: #3091 (as well as #3097).
