### ISSUE TITLE
Missing grunt-cli for Node.js 0.11.16, 0.12.0 and io.js 1.2.0

### ISSUE THREAD

**Issue by dancek** [travis-ci/travis-ci#3231]
Apparently `grunt` is not available in Node.js 0.12 and io.js environments, as seen eg. in this build: https://travis-ci.org/dancek/grunt-more-css/builds/50741238

```
sh: 1: grunt: not found
````

Documentation suggests that [grunt-cli is provided for Node.js >= 0.8](http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#Node.js-VM).

**Comment by dancek** [comment]
The same goes for Node.js 0.11.16: https://travis-ci.org/dancek/grunt-more-css/jobs/50738884

**Comment by BanzaiMan** [comment]
The document is a bit inaccurate. The pre-installed versions, iojs-v1.1.0 and 0.11.15, have grunt pre-installed, but these more recent versions are installed on demand by NVM, and as such, does not have grunt.

@ljharb Is there a way to make this easier on users?

**Comment by ljharb** [comment]
@BanzaiMan the only options I can think of are:
1) pre-prepare the newer versions on the VM with grunt preinstalled
2) change the VM to `nvm install X && npm install -g grunt` (but I never use grunt, so I'd prefer not to slow down my tests for it)
3) symlink `$(nvm use iojs-v1.1 && npm root -g)/grunt` and `…/.bin/grunt` etc automatically on `nvm install`, but this almost certainly will break across `node`/`iojs` versions, so I don't recommend it.
4) if a dev needs X, then they can configure their `travis.yml` `before_install` script to install X.

The general community convention is that if a module requires X, X should be in package.json as a dependency/devDependency, and if it's a cli, it should be run via `npm run` - relying on `grunt` being globally installed is already making life harder for users, so I'm not sure it's beneficial for `travis-ci` to be implicitly encouraging it.

**Comment by dancek** [comment]
@ljharb I agree that it's best to have as little as possible installed globally. Unfortunately the Grunt plugin convention seems to be to define the test script as `grunt test`. I'm new to this, but at least that's the way `grunt-init gruntplugin` suggests and most plugins I've seen do in practice.

My suggestion is to mention in the documentation that Travis CI used to have `grunt-cli` pre-installed, but it is deprecated and current versions don't have that anymore. Preferably suggest a way to run grunt without a global grunt-cli, or mention the `before_install` option.

**Comment by BanzaiMan** [comment]
I've cleared up this point in the update announcement.

Given the options, I am of the opinion that there is no clean way to provide `grunt-cli` for versions that are not pre-installed on the image.

**Comment by ljharb** [comment]
@dancek Any task begun underneath an `npm run` command will have `node_modules/.bin` in the `PATH`, and thus `grunt test` will work just fine. As long as `grunt` is a dependency, and any `grunt` tasks are initiated somewhere within an `npm run-script` command, you'll be fine - no globals needed.

**Comment by joshk** [comment]
I am totally for not pre-installing grunt and instead advise people to use `npm run`

**Comment by dancek** [comment]
@ljharb thanks for clearing that up. I added a dev dependency to `grunt-cli` and wrote the scripts section in `package.json` this way:

```json
  "scripts": {
    "grunt-test": "grunt test",
    "test": "npm run grunt-test"
  },
 ```

I see no downsides to this approach, so I'm going to suggest it for `grunt-init-gruntplugin`.

**Comment by ljharb** [comment]
@dancek Great! You could also shorten that to `"test": "grunt test"` since `npm test` is shorthand for `npm run-script test`, but I tend to keep my individual tests separate and then `npm run` them one by one in `test` as well :-)

**Comment by BanzaiMan** [comment]
I've clarified the announcement, and there is no mention of grunt in the language page. There is nothing to do here, right? I'm closing this.

**Comment by ErisDS** [comment]
We're suddenly running into this in TryGhost/Ghost. Our build matrix looks like:

```
 - "0.10"
 - "0.12"
 - "iojs-v1.2.0"
```

I spoke to @henrikhodne on IRC who pointed me here.

Our full build has been using that matrix for over a month and passing, and then randomly started failing yesterday (during the difficulties). Sometimes node v0.12 runs ok, sometimes iojs-v1.2.0 runs ok and sometimes they both fail. It's seemingly completely random:

- In this build you'll see the 3 with node v12 are failing with the `sh: 1: grunt: not found` error: https://travis-ci.org/TryGhost/Ghost/builds/59435026
- This master build is failing with the same error but on io.js: https://travis-ci.org/TryGhost/Ghost/builds/59574179
- This build in the middle worked just fine: https://travis-ci.org/TryGhost/Ghost/builds/59549222

I understand if we need to make some changes, but I'd like to understand what's going on and why we are only just affected? This thread mentions an update announcement but there is no link so I'm not sure if there is more info there.

Is this somehow dependent on what exact versions of node are preinstalled on a given VM? Has something only just changed? Or are we running into a bug?
