### ISSUE TITLE
robodoc on travis-ci?

### ISSUE THREAD

**Issue by zbeekman** [travis-ci/travis-ci#3235]
Is there a robodoc package available through a PPA for use with travis-ci, or do we have to download and build it from source every time?

**Comment by BanzaiMan** [comment]
http://packages.ubuntu.com/precise/robodoc doesn't have it, so you'll have to add PPA and download it every time for now.

**Comment by zbeekman** [comment]
OK… I guess I can always download and install from source too… it would be nice to have this by default.

**Comment by roidrage** [comment]
I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by zbeekman** [comment]
that’s fine, we’re moving to a different doc generator anyway.
