### ISSUE TITLE
Travis is looking for the repo in the old location after renaming it on github

### ISSUE THREAD

**Issue by inf3rno** [travis-ci/travis-ci#3236]
I renamed my repo on github now I got a failing build:

[![Build Status](https://travis-ci.org/inf3rno/dataflower.png?branch=master)](https://travis-ci.org/inf3rno/dataflower)

It claims that cannot find the yml config file, that's why it fails.

I checked the log (dflo2 was the old name of the repo, now it is dataflower):

> $ git clone --depth=50 --branch=master git://github.com/inf3rno/dflo2.git 

Is it possible to fix this somehow?

**Comment by BanzaiMan** [comment]
Could you try synchronizing your user data? https://travis-ci.org/profile

**Comment by inf3rno** [comment]
Now it appears to fixed itself somehow, but it is even more stranger:

> $ git clone --depth=50 --branch=master git://github.com/inf3rno

Now it clones all my repos I assume...

**Comment by inf3rno** [comment]
Ohh I expanded and this was the whole line:

> $ git clone --depth=50 --branch=master git://github.com/inf3rno/dataflower.git inf3rno/dataflower

So everything is okay, probably some cache stored the old location.
