### ISSUE TITLE
Xcode: "dyld: Symbol not found: _objc_readClassPair"

### ISSUE THREAD

**Issue by stephencelis** [travis-ci/travis-ci#3237]
I use Travis with an iOS/OS X framework. I've converted 2 separate framework targets into 1 universal target, which is working swimmingly locally, but Travis craps out during both `xcodebuild test` runs.

```
dyld: lazy symbol binding failed: Symbol not found: _objc_readClassPair
  Referenced from: /Users/travis/Library/Developer/Xcode/DerivedData/SQLite-cxalxlmwmvqsabgcsrhmyfnfmfyi/Build/Products/Debug/SQLite Tests.xctest/Contents/MacOS/../Frameworks/libswiftCore.dylib
  Expected in: /usr/lib/libobjc.A.dylib
dyld: Symbol not found: _objc_readClassPair
  Referenced from: /Users/travis/Library/Developer/Xcode/DerivedData/SQLite-cxalxlmwmvqsabgcsrhmyfnfmfyi/Build/Products/Debug/SQLite Tests.xctest/Contents/MacOS/../Frameworks/libswiftCore.dylib
  Expected in: /usr/lib/libobjc.A.dylib
```

—https://travis-ci.org/stephencelis/SQLite.swift/jobs/50801576

What's strange is that Travis ran the tests just fine before adding this config file (to allow for the universal framework in the first place):

https://github.com/stephencelis/SQLite.swift/blob/universal-framework/SQLite/SQLite.xcconfig

This config more or less mirrors what others have done before: https://github.com/kylef/Stencil/commit/5a080f92ccda1390ba6cd7444517afd1e6fb6c8c

I'm not sure what Travis' images look like and if something in my xcconfig is tripping it up, but the above repo's tests are running just fine: https://travis-ci.org/kylef/Stencil

**Comment by stephencelis** [comment]
Looks like #2940 reported a similar issue?

**Comment by BanzaiMan** [comment]
If this is a symbol in Yosemite, please wait for the upcoming support (no ETA).

**Comment by stephencelis** [comment]
The tests ran fine before I made things a universal framework (the actual code does't use this symbol). Any clue as to why this symbol be required merely with an updated xcconfig?

**Comment by BanzaiMan** [comment]
Hmm. That's interesting. Did you update your Xcode version and/or change the build target?

**Comment by stephencelis** [comment]
The commit's here: https://github.com/stephencelis/SQLite.swift/commit/906b709f122e7576d75c3761e5997b62db6f74fb

2 build targets became 1, so the build target changed. The Xcode version hasn't changed.

**Comment by stephencelis** [comment]
Any insights would be helpful. I may dig into this again in the future but it's difficult to troubleshoot without access to your boxes :(

In the meantime I've had to disable Travis CI for this project. Hope to re-enable it in the future, though!

**Comment by mietek** [comment]
Apparently, Xcode 7 introduces a new build setting, “Implicitly Link Objective-C Runtime Support”, or `CLANG_LINK_OBJC_RUNTIME`, which defaults to `YES`.

More information:
[“Undefined symbols: "_objc_readClassPair" when opening existing project in Xcode 7”](https://forums.developer.apple.com/thread/17757)

**Comment by BanzaiMan** [comment]
This seems like a stale issue at this point. I'm closing this. If this is still relevant (to more recent versions of Xcode), do open a new issue.
