### ISSUE TITLE
Escaping in Travis

### ISSUE THREAD

**Issue by jluttine** [travis-ci/travis-ci#3240]
I couldn't find any detailed documentation on escaping characters in travis. So that is the first general issue: please provide one. :)

In particular, I would like to have the following lines in .travis.yml:
```
before_script:
  - echo "backend : Agg" > matplotlibrc
```
or
```
before_script:
  - echo "backend : Agg" | tee matplotlibrc
```

They don't work, and the latter one gives me the following error:
```
The command "{:"echo \"backend"=>"Agg\" | tee matplotlibrc"}" failed and exited with 127 during .
```

How can I fix this?

**Comment by BanzaiMan** [comment]
@jluttine Colons are special in the YAML specifications. It is a delimiter for the hash/associative arrays. Your command is interpreted as shown in the error message.

I can't remember if it's possible to escape it with a backslash (`- echo "backend \: Agg" | tee matplotlibrc`). If not, you should consider writing a script that does this and calling that instead.

**Comment by jluttine** [comment]
Thanks! Backslash didn't help but I think I got it working like this:
```
before_script:
  - "echo backend : Agg > matplotlibrc"
```
