### ISSUE TITLE
Confusing/duplicate CI status on github

### ISSUE THREAD

**Issue by Habbie** [travis-ci/travis-ci#3241]
On https://github.com/PowerDNS/pdns/pull/2239 I see (text copy/pasted mostly in case things change):

 Failed — 1 errored and 1 successful checks
Details continuous-integration/travis-ci — The Travis CI build could not complete due to an error
Details continuous-integration/travis-ci/pr — The Travis CI build passed

Both Details-links go to the same (passed!) build. If I have to guess, travis-ci changed the CI 'tag' or 'identifier' to perhaps support multiple classes of builds, now that Github supports showing results from multiple CI systems. However, for PRs being updated/rebuilt 'over' this change, this is somewhat confusing.

If the story is "yes, this happened, any new builds won't suffer from this", I'm fine with that by the way :)

**Comment by BanzaiMan** [comment]
I believe this is related to https://github.com/travis-ci/travis-tasks/pull/31.

**Comment by joshk** [comment]
Hi @Habbie 

I think this issue is because the PR was restarted after we deployed this change.

Looking at the PR, that it was submitted 2 days ago, I can confirm this is the case.

Please disregard this issue. If it occurs again for new PRs please open a new ticket and we can dive in deeper.

Have an awesome day!

**Comment by Habbie** [comment]
This is exactly as I thought. Thanks for checking!

**Comment by rstacruz** [comment]
I'm not sure if this is the place to ask about this, but I'm confused at why some PRs get built twice. This screenshot shows `travis-ci/push` and `travis-ci/pr` builds.

![pasted_image_3_4_15__5_10_pm](https://cloud.githubusercontent.com/assets/74385/6480682/585bfecc-c291-11e4-8e0e-d79780aa1ddd.png)

I'm the owner of the repo, and I'm issuing a PR from a branch on that same repo.

**Comment by joshk** [comment]
@rstacruz this is because Travis is testing the branch and the PR merge commit, which are two different things to be tested.

**Comment by rstacruz** [comment]
Can't Travis figure out if it's testing the same commit SHA?

**Comment by joshk** [comment]
It isn't testing the same SHA, we are testing the commit from the branch, and then the newly created merge commit by GitHub for the PR.

**Comment by rstacruz** [comment]
ah! that explains it.. interesting.

**Comment by yangmillstheory** [comment]
@rstacruz I was able to build only PR's by telling Travis not to build pushes:

![image](https://cloud.githubusercontent.com/assets/2729079/16531471/7c517456-3f81-11e6-9a12-92e990f6f539.png)

**Comment by daenney** [comment]
I find this behaviour rather confusing though. Especially since I've had cases where the one of the two fails for a random reason. Considering you now also have the option to squash merge (which doesn't cause a merge commit) I'm not sure it makes that much sense to test that by default?

**Comment by minggo** [comment]
How can i distinguish

* first time the PR is generated (it will generate push event)
* the PR is merged (will generate push event too)

Because i only want to know if a PR is merged and do some special things. Now it seems that `push` event will trigger travis when the above situations.

**Comment by minggo** [comment]
@joshk could you please take a look the above question? Thanks.

**Comment by stuaxo** [comment]
This is a waste of resources, it would be good if there was a way to suppress these duplicate builds - I like CI, but I don't need to doubly heat up some server room somewhere.
