### ISSUE TITLE
Cannot sign in using Safari 8.0.3

### ISSUE THREAD

**Issue by tohuw** [travis-ci/travis-ci#3245]
When I attempt to sign in to the site, I receive an error "What‽ Your browser did something unexpected. Please contact us if the problem persists."

The URL does contain a proper-looking auth link, including the string `travis-ci.org`

It works fine in FireFox.

I have two-factor auth enabled, but it works fine in all other circumstances. 

Let me know how I can test further or help in some way. Thanks.

**Comment by BanzaiMan** [comment]
Probably related to #3193.

**Comment by tohuw** [comment]
@BanzaiMan, possibly, but this is on org where it happens. I haven't tried .com. Let me know if I can assist.

**Comment by drogus** [comment]
I believe this is something new.

@tohuw do you use any extensions? Can you try to sign in on private mode to rule out any environment influence?

**Comment by tohuw** [comment]
Ah, sorry, should have tested that initially.

I can repeat the problem in Private mode. I have no particular "odd" settings in my Safari beyond a few extensions, which of course are not invoked in Private mode.

**Comment by joshk** [comment]
Hi @tohuw 

Sorry, would you be able to record a small screencast of the bug you are experiencing so we can try and replicate ourselves?

Thanks,

Josh

**Comment by tohuw** [comment]
Sure thing: [here's the screencast](https://gist.github.com/tohuw/0106f0aa8cf7be53e046/raw/22ab524386e22fd99dd4c5685c9c8df0882894b2/travis-error.mov).

**Comment by joshk** [comment]
Thanks for the extra info. This is a GitHub error page and probably needs to be escalated to them first.

**Comment by tohuw** [comment]
Possibly so, but here's something interesting: I just discovered it works fine from my iMac, which has the same version of OS X (10.10.2) and the same Safari version. The only difference is that the Air (from which I previously tested) is participating in the "Seed" program, but I don't see any other relevant early updates that might cause this. Interesting, no?

**Comment by joshk** [comment]
Well, I'm not sure sorry, have you emailed GitHub support about this issue?

**Comment by tohuw** [comment]
I was able to resolve the issue by signing out of GitHub, then clearing all cookies and cache. I find it odd that the Private mode was not sufficient to simulate this, but there you have it.
