### ISSUE TITLE
Cache is uploaded even if there are no changes

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#3246]
It seems that the cache archive is uploaded even if there are no changes.
Notice the change between https://travis-ci.org/tomchristie/django-rest-framework/jobs/51078526#L88 and https://travis-ci.org/tomchristie/django-rest-framework/jobs/51227926#L101
and the change between https://travis-ci.org/tomchristie/django-rest-framework/jobs/51078526#L104 and https://travis-ci.org/tomchristie/django-rest-framework/jobs/51227926#L115
Enabling caching does make the build faster but the way travis cache works makes the build slower.
Is there a reason why the archive is uploaded every time?

**Comment by BanzaiMan** [comment]
Could you elaborate on what you want to show with these lines from the logs?

Cache change is defined by mtime. Even if the file contents are the same, if the mtime is updated it will be added to the cache. If the cache gets too big, it will also add to the build time.

**Comment by thedrow** [comment]
I'm prooving that the fact that we cache pip dependencies does make the build process faster.
Take a look on the [build times](https://cloud.githubusercontent.com/assets/647359/6249340/760866e0-b77e-11e4-82ce-1f5418b9d254.png).
The caching process itself makes the build slower.

**Comment by BanzaiMan** [comment]
Sorry, but where did you get the impression that caching will always make the builds faster? If you get that impression from our documentation, we need to fix that.

**Comment by thedrow** [comment]
Caching, especially in these very simple cases where there are a few dependencies to install should make the builds faster.
This is not a documentation bug. This is an actual problem with the product. One that also affects pro users.

**Comment by BanzaiMan** [comment]
Understood. In that case, I believe this is a duplicate of #2435.

**Comment by joshk** [comment]
Hey @thedrow

Thanks for the feedback.

We are working on improving our caching to instead check the checksum of the file. This will help where some dependency solutions, like pip, might change the mtime of files.

To touch upon your point about caching speeding up builds where you are only installing a few libraries, this should generally be true, but of course you will see the greatest improvements when you have many many many dependencies.

Thanks a bundle,

Josh

**Comment by thedrow** [comment]
Yup this is a duplicate. Closing this one.
