### ISSUE TITLE
"Skipping deployment..." message is still confusing

### ISSUE THREAD

**Issue by gsf** [travis-ci/travis-ci#3247]
Following up on [my comment](3209#issuecomment-73791821) at #3209, I realized I misunderstood the nature of the message. I now understand that it appears for each deployment where the branch condition is not met.

The real issue here is that this is defined as a "failure message" and displayed in red when my configuration is correct and deployment is functioning as expected. In most multiple deployment cases this message is merely informational, or at most a warning, rather than an outright error or failure.

I propose the following:

1. Revert the inclusion of the branch name, which I see now is redundant, and change "this branch is not permitted to deploy" to "this branch does not meet a condition" to align it with language in the docs.
2. Color these messages yellow.
3. Modify the message to "Skipping a deployment..." The indefinite article makes it clear we're not necessarily skipping the entire deployment.

PR forthcoming.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/390 has been merged and deployed.
