### ISSUE TITLE
APT whitelist request for libc++-dev

### ISSUE THREAD

**Issue by nicolasnoble** [travis-ci/travis-ci#3248]
If on a C++ project you are using clang and its memory sanitizer feature in your tests, you need an instrumented libc++, which is provided by that libc++-dev package.

**Comment by BanzaiMan** [comment]
This package is not available for Precise.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libc++-dev' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libc++-dev' needs trusty

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/359.

        Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

        Thank you!
