### ISSUE TITLE
Rust language support broke with the latest nightly

### ISSUE THREAD

**Issue by sfackler** [travis-ci/travis-ci#3249]
Travis's Rust install logic doesn't seem to work with the new Rust nightly: https://travis-ci.org/sfackler/rust-postgres/builds/51319131

**Comment by BanzaiMan** [comment]
Is this addressed by https://github.com/travis-ci/travis-build/pull/391?

**Comment by sfackler** [comment]
Looks like it should be.

**Comment by fenhl** [comment]
It is. Fixed by #391.
