### ISSUE TITLE
UI: Notify users that new repo may be inaccessible before sync

### ISSUE THREAD

**Issue by josegonzalez** [travis-ci/travis-ci#3253]
I had a user attempt to check a private repository after I added it to travis and they were given a message similar to the following

```
The repository at seageek/derp was not found.
```

After a bit of back and forth on the travis-ci chatroom, it turns out the user's profile had not sync'd since the repository was created on github (earlier in the day) and thus they were unable to see that they had access to the repository. I was able to access it just fine since it was required that I sync before I enable the repository on travis.

Rather than just throw this message to the user - the poor, poor users - we could signal in the travis ui that all users should sync their profiles if the repository was recently enabled. This could be shown for ~12 hours, which should be enough time to signal to a large team, as well as be unobtrusive. Perhaps closable via an X. Obviously this would only show to users currently with access, which will aid in debugging.

Shitty mockup time!

![http://cl.ly/image/2n3l3F0u3l1z](http://cl.ly/image/2n3l3F0u3l1z/Image%202015-02-19%20at%205.55.29%20PM.png)

And the equally awful html (sorry!):

```html
<div id="new-summary" style="
    margin-bottom: 10px;
    background: #dC9136;
    color: black;
    min-height: 30px;
">
    <div class="mainline">
      <div class="subject" style="
    margin-bottom: 12px;
    color: #fff;
    margin-left: 220px;
    margin-right: 0;
    text-align: center;
">Users may need to <a href="https://magnum.travis-ci.com/profile">sync their profiles</a> before receiving access to this repository</div>
    </div> 
  </div>
```

**Comment by joshk** [comment]
Hi @josegonzalez 

Thanks for the suggestion.

One of the issues here is that you may have users which don't have access to that repo for a good reason. So showing a message of any form would then become noise.

The main issue is that we need to improve our sync, and see if there is an event we can respond to which will allow us to presync all org members if a new repo is added.

Also, it might be better for us to add a screen so you can see all users who have access to a repo on Travis.

I'm going to close this for now.

Thank you for the suggestion though, and taking the time to mock this up.

Josh
