### ISSUE TITLE
APT whitelist request for lib32z1 lib32ncurses5 lib32bz2-1.0

### ISSUE THREAD

**Issue by eyphka** [travis-ci/travis-ci#3254]
These libraries are meant to allow running 32 bit dependent software on a 64 bit machine, specifically for me, installing and using the gcc ARM embedded toolchain.

**Comment by alxn** [comment]
@eyphka I was wondering which gcc ARM embedded toolchain you were installing?

**Comment by eyphka** [comment]
Hi Alun, 

Attempting to install the gnu Arm toolchain which you can find here. 
https://launchpad.net/gcc-arm-embedded

The Debian pkg for this is a little behind, resulting in me not being able to compile... although I can't seem to get it to work still on Travis.



—
