### ISSUE TITLE
C# build fails when referencing EntityFramework NuGet package

### ISSUE THREAD

**Issue by paulirwin** [travis-ci/travis-ci#3255]
Build output: https://travis-ci.org/feature23/Data-Access-Extensions/builds/51555705
Repo: https://github.com/feature23/Data-Access-Extensions

cc @joshua-anderson @akoeplinger @nterry

This project references the EntityFramework 6.1.2 NuGet package, but from looking at the build output at the link above, the build seems to be using the EntityFramework.dll from /usr/lib/mono/4.5/EntityFramework.dll instead of from the packages folder at /home/travis/build/feature23/Data-Access-Extensions/packages. Since this builds fine in Visual Studio, and the error is that a property doesn't exist on the System.Data.Entity.Database type, I assume this means that the EntityFramework.dll at /usr/lib/mono/4.5 is out of date, but regardless, it should be using the NuGet version.

Let me know if there's any more info I can provide. Thanks!

**Comment by akoeplinger** [comment]
@paulirwin The path to the nuget packages in [your csproj](https://github.com/feature23/Data-Access-Extensions/blob/5de0c897fc8a879de7b4015b11a1e857d037cbbf/src/F23.DataAccessExtensions.EntityFramework/F23.DataAccessExtensions.EntityFramework.csproj#L36) is wrong, it misses an extra `..\`. 

As xbuild cannot find the DLL it proceeds with resolving from the GAC, which is an old EF version (I've [advocated](http://lists.ximian.com/pipermail/mono-devel-list/2014-November/042425.html) for removing it, hopefully we can do it in the upcoming Mono 4.0).

Works as designed :smile:

**Comment by BanzaiMan** [comment]
I'm closing this, based on @akoeplinger's input.
