### ISSUE TITLE
Be able to view the status of prior runs of restarted jobs

### ISSUE THREAD

**Issue by lbergelson** [travis-ci/travis-ci#3256]
I find that no matter how hard we try to nail our dependencies to the ground, things manage to change out from under us with some regularity.  Often to test this, it's useful to rerun an build that had been in a passing state previously but is now failing.  The issue is that once you rerun a build you lose all the old information from that build. 

It would be useful to be able to see multiple instances of the same build if you reran it, so that you could easily diff the logs for instance.

**Comment by BanzaiMan** [comment]
Thanks for the feedback. I am closing this one in favor of #2993.
