### ISSUE TITLE
Background colors in log output are too bright to be readable

### ISSUE THREAD

**Issue by mgorny** [travis-ci/travis-ci#3260]
In regular *nix terminals, background colors are rather dark, fit for light text. However, in Travis' HTML rendering those colors are rather light, which causes white error messages to be rather unreadable.

Here's a screenshot comparing the background colors in travis-ci log to xfce4-terminal:

![bg_demo](https://cloud.githubusercontent.com/assets/110765/6319237/ed310810-bab4-11e4-96f9-64ef63d9c32e.png)

Please consider using darker background colors.

Demo: https://travis-ci.org/mgorny/travis-bright-bg-demo

**Comment by joshk** [comment]
@drogus @rkh @saltinejustine @henrikhodne thoughts on this?

Also, do we have a bug with background colour and foreground colour?

**Comment by saltinejustine** [comment]
Hey @joshk what do you mean by background and foreground color bug?

**Comment by joshk** [comment]
In the screenshot you can see his terminal on the right, and the Travis terminal on the left. On the right hand side In his terminal you can see 'BRIGHT FOREGROUND' with a coloured background, something which we aren't doing in our terminal. 

It would be nice to fix this, but I would need the help of the amazing @drogus for this.

As for terminal colours, I leave that up to you. You might want to talk to @henrikhodne about some of this as well as he helped with the colours we have now.

**Comment by saltinejustine** [comment]
okay, so not really a bug, just something we should work on toe make it easier for people to relate to their own terminal settings?

Sorry, just want to make sure I'm understanding the problem correctly.

**Comment by joshk** [comment]
Well, it's both a bug and improvement, but nothing major either :)

**Comment by mgorny** [comment]
As far as I'm concerned, the bright background colors are more important of an issue because it means that once I added some highlighting to make errors more noticeable, the error messages became less readable.

As for the bright foreground issue, it's because escape sequences seem to implicitly reset previous state instead of applying new bits on top of it. In this case, `\033[1m` is supposed to 'set bold' while leaving the other attributes intact.

**Comment by mgorny** [comment]
Hmm… but it wasn't closed? In any case, it's still the case.

**Comment by mgorny** [comment]
Apparently I can't reopen it for some reason ...
