### ISSUE TITLE
APT whitelist request for postgresql-server-dev-*

### ISSUE THREAD

**Issue by tomhughes** [travis-ci/travis-ci#3261]
Please add the postgresql-server-dev-<version> packages to the APT whitelist so that postgres extensions can be built.

**Comment by BanzaiMan** [comment]
The only version that is available on Precise is 9.1. http://packages.ubuntu.com/precise/postgresql-server-dev-all Is this what you need?

**Comment by tomhughes** [comment]
Yes 9.1 is fine, but there seemed to be more than that - one for each version of postgres that was supported in fact.

I think the builders are actually using apt.postgresql.org for postgres aren't they?

**Comment by BanzaiMan** [comment]
Good point. I don't know if we can allow these packages to be installed with the whitelist. I'll have to check.
