### ISSUE TITLE
If you cancel the build for the push, it should cancel the build for the PR

### ISSUE THREAD

**Issue by chriscct7** [travis-ci/travis-ci#3266]
So Travis runs a separate build for the build and the pr. If you cancel the build one, its really annoying to have to go and find and cancel the pr build that it corresponds to

**Comment by joshk** [comment]
Thanks for the suggestion @chriscct7 

We are not likely to add this as a Push build and a PR build are testing two different things, one is testing the push to the branch itself, and the other is testing the merge commit created by GitHub.

Have an awesome weekend!

**Comment by chriscct7** [comment]
Is there anyway that could be added as a config setting? We only use branches to stage commits before a pr, so it doesn't make much sense for both to run once a pr is submitted.

**Comment by joshk** [comment]
Sorry, can you explain the use case a bit more, ideally step by step, I think I'm a little confused now.

**Comment by chriscct7** [comment]
Sure,
Let's say we're making a release, like our next major version (2.3).

So we have a branch called release/2.3. 

We're working on a feature that may or may not make it into the 2.3 release, so it's on a branch called issue/xxxx. 

Let's say I've finished the issue, it looks good to go, so I want to merge it into release/2.3

So I open a pull request from issue to 2.3. 

Another team member always reviews each others code before it goes in. He notices I have an indentation mistake. So I commit a fix to the issue/xxx branch, which in turn, updates the pr with this commit.

So Travis, seeing this, does a build for the branch and the pr. But in the process of fixing the indentation, my mouse went a bit crazy and it's removed a semi colon. I can see all of the runs on the branch build are failing because of this. Realizing the issue, I've committed a fix for this. Because each build takes 10 or so minutes, and I want to speed things along, I want to cancel both  of the builds for the branch and the pr from the faulty indentation fix. The first one is easy, because I'm already staring at the build for that in Travis, because thats how I found the issue. So I cancel that. Then I have to also manually go over to the pr build list and cancel the one for the pr, so that Travis starts on the builds for the syntax fix.

It'd be nice if cancelling the build for the branch, cancelled it also for the pr I made. Its kind of annoying to go track down the pr build to go cancel it manually. And because sometimes cancelling the build requires pushing the button, refreshing, and pushing it again for some builds, it can get a bit tedious.

Does that make sense?

**Comment by joshk** [comment]
Thanks for the extra information, I completely understand now.

I think this feature has some merit, although is also a feature which will see little usage too.

For this feature to happen we would first need to link Push and PR builds together.

I'm going to leave this issue open for a bit while I ponder it a little more.

Thanks for taking the time to explain this further.

**Comment by joshk** [comment]
I'm sorry but I'm going to close this issue for now as we are unlikely to get to it within the next 3-6 months.

Thank you for taking the time to create the issue and explain the idea behind it.
