### ISSUE TITLE
vows 0.8.1 with istanbul 0.3.6 times out.

### ISSUE THREAD

**Issue by Mkoopajr** [travis-ci/travis-ci#3267]
When running test on a nodejs project using vows 0.8.1 and instanbul 0.3.6 travis hits the timeout. The tests run fine up until it is supposed to print the coverage report then it hangs. Downgrading to vows 0.8.0 fixes this issue.

**Comment by joshk** [comment]
Thanks for creating this issue.

Is this maybe an issue that should be reported to the vows developers first? How might this be a Travis issue?

**Comment by Mkoopajr** [comment]
Well that configuration runs locally on my machine fine. So I'm not really sure what's causing the issue to be honest. The vows test still pass which you can see [here](https://travis-ci.org/Mkoopajr/ilconstitution/builds/51801547) it just hangs. After the downgrade you get [this](https://travis-ci.org/Mkoopajr/ilconstitution/builds/51803342).

**Comment by joshk** [comment]
Have you confirmed locally that you are using the exact same set of npm libs? Also, are you using a Mac or Linux machine locally?

**Comment by Mkoopajr** [comment]
Actually I did lie to you. I apologize after clearing node_modules folder and reinstalling this is indeed a vows issue and hangs on my local machine. I am using a mac.

**Comment by joshk** [comment]
Ok, great to know. Going to close this issue.
