### ISSUE TITLE
Using php executables with a shebang fail with pdo_pgsql driver

### ISSUE THREAD

**Issue by ambroisemaupate** [travis-ci/travis-ci#3268]
I tried to use a php executable which needs PDO pgsql driver without prefixing with `php`:
```bash
bin/roadiz orm:schema-tool:create -n
```
This executable uses `#!/usr/bin/php` shebang and works perfectly with `mysql` and `sqlite` drivers. But it fails with `pdo_pgsql` driver.    
See: https://travis-ci.org/roadiz/roadiz/jobs/51545515

Then I found out that we need to use following syntax:

```bash
php bin/roadiz orm:schema-tool:create -n
```
See: https://travis-ci.org/roadiz/roadiz/jobs/51803765

So why php binaries have not the same behaviour with or without `php` executable prefixed?

**Comment by BanzaiMan** [comment]
PHP runtimes are managed by phpenv. Your script calls the system PHP instead of the one Travis CI uses. Please use `#! /usr/bin/env php` instead.

**Comment by ambroisemaupate** [comment]
Thanks for your advice. I’ll correct it right now.
