### ISSUE TITLE
kiex cannot find any known version

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3269]
https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/428572#L90

Not quite sure why, but `kiex` cannot find known Elixir releases. As a result (and because there is a problem with the build script), non-default version of Elixir cannot be used at the moment.

**Comment by danielberkompas** [comment]
@BanzaiMan My Elixir builds are still using the default version of Elixir. See this sample build: https://travis-ci.org/danielberkompas/ex_twilio/jobs/56160581#L81

![job__5_1_-_danielberkompas_ex_twilio_-_travis_ci](https://cloud.githubusercontent.com/assets/1186992/6983581/78add18c-d9d4-11e4-91d5-695e4983c585.png)

For some reason, it looks like kiex is unable to install the specified version.

**Comment by danielberkompas** [comment]
I've also checked what releases kiex on Travis knows about, and it looks like it doesn't know about any:
![job__37_1_-_danielberkompas_ex_twilio_-_travis_ci](https://cloud.githubusercontent.com/assets/1186992/6983599/bccf363a-d9d4-11e4-8ff8-c732ddf70f5d.png)

In contrast, my local shell returns the following versions when I run `kiex list known`:

![1__dberkom_bastiat____dev_dialyxir__zsh_](https://cloud.githubusercontent.com/assets/1186992/6983610/d786da50-d9d4-11e4-9356-7924e1705fd8.png)

Is Travis using an outdated version of kiex?

**Comment by BanzaiMan** [comment]
@danielberkompas Looks like a temporary issue with connectivity with GitHub. https://travis-ci.org/danielberkompas/ex_twilio/jobs/57044720#L87 shows that it works.

**Comment by BanzaiMan** [comment]
We can either retry, or fall back to 1.0.3.

**Comment by BanzaiMan** [comment]
With https://github.com/travis-ci/travis-build/commit/bbead30, we will retry up to 3 times. If it still fails after 3 times, then we have a real problem.

**Comment by DevL** [comment]
Looks like this issue has resurfaced. I've got a string of builds that fail miserably (builds 54-74): https://travis-ci.org/DevL/plug_require_header/builds/58594973

**Comment by BanzaiMan** [comment]
Sorry about that. We are looking into this issue again.

**Comment by roidrage** [comment]
Could this be because of API rate limiting? Everything from the container setup is going to the GitHub API with the same IP

Would be great to coerce some output from kiex from the curl command.

I've been trying to reproduce this as well: https://travis-ci.org/roidrage/Radpath

**Comment by BanzaiMan** [comment]
@roidrage I've contacted GitHub support for some insight. :smile:

**Comment by BanzaiMan** [comment]
I'll drop some further debugging stuff to our fork of `kiex`, then inject it with `travis-build`, so that we can get more information on the reasons for the failure. Stay tuned.

**Comment by BanzaiMan** [comment]
I was able to do it without hacking `travis-build`: https://travis-ci.org/BanzaiMan/travis_production_test/builds/58769492#L4698-L4717

At least, for this instance, we are getting 403 from GitHub. I'll relay this information and see if we can resolve it.

**Comment by BanzaiMan** [comment]
It's the rate limit.

**Comment by DevL** [comment]
Thanks for looking into this, it's much appreciated!

**Comment by BanzaiMan** [comment]
Another approach would be to package Elixir or to find a trust-worthy Elixir package. https://travis-ci.org/phoenixframework/phoenix/builds/65131002#L91 shows such a possibility.

While it is conceivable that a build on Travis CI needs to switch Elixir version during the build, but I suspect that will be an exception. Having a consistently usable Elixir environment is probably more desirable.

**Comment by BanzaiMan** [comment]
So, the general strategy is to install Elixir from the binary package from s3.hex.pm if and only if the version is not pre-installed (which, at the moment, means anything other than 1.0.2).

I am thinking that the presence of binary packages add very little additional burden on image provisioning, so we'll have most (if not all) of 1.0.x onward preinstalled starting with the next update.
