### ISSUE TITLE
Build stalled, cannot use API's restart

### ISSUE THREAD

**Issue by neothemachine** [travis-ci/travis-ci#3270]
I have setup a cronjob which restarts the latest build for a project of mine every week (to update some html on github pages). But since 2 weeks or so it is stuck in the yellow state without anything to do and no possibility to kill it: https://travis-ci.org/neothemachine/pixelpitch/builds/45704655 If this is a normal "stalled" build, shouldn't it be automatically killed after some time?

**Comment by joshk** [comment]
Thanks for reporting this.

We aren't sure how this happened, but what I have done is restarted the job and this has now restarted the build.

Can you check if things are working better for you now?

**Comment by neothemachine** [comment]
I will write here again if the builds stall. But currently it seems to be working again.

**Comment by joshk** [comment]
Great to hear. If it happens again please open a new issue. I'll close this one for now.

**Comment by sorawee** [comment]
the same happens here: https://github.com/square/inspect/pull/10
