### ISSUE TITLE
Move default Ruby version to 2.1.5

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3271]
Ruby 1.9.3 has officially run its course and EOL'd today. https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

What could break if we move the default Ruby version to 2.1.x?

**Comment by BanzaiMan** [comment]
dpl is now build and deployed with 2.1.5 (https://travis-ci.org/travis-ci/dpl/jobs/51899869).

**Comment by BanzaiMan** [comment]
I've created a test Ruby VM with 2.1.5 as default, and seems to work fine (so far. Deployment has not been tested).

**Comment by liquid** [comment]
@BanzaiMan It feels counter intuitive having to specify the current stable ruby version in `.travis.yml` but our tests fail on 1.9.3 (which I don't think may projects still support)

What can we do to help getting this issue to progress?

**Comment by joshk** [comment]
Closing this as it's become stale.
