### ISSUE TITLE
No login link on travis-ci.org when using iPhone

### ISSUE THREAD

**Issue by cvrebert** [travis-ci/travis-ci#3272]
If you open e.g. https://travis-ci.org/twbs/bootstrap on an iPhone, you'll observe that there's no Log In link anywhere on the page, making it impossible to log in to the site from such devices.
Environment: Safari on an iPhone 5S running iOS 8.1.3

**Comment by BanzaiMan** [comment]
Thanks for the report.

![twbs_bootstrap_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/6342770/2a575864-bbac-11e4-94b3-5313523474ac.png)

Upper right bar seems squashed and shows nothing.

For the login link to show up, the screen needs to be about 800 pixels wide (even then, it is not easy to figure out what the green blot is).

![travis_ci_-_free_hosted_continuous_integration_platform_for_the_open_source_community](https://cloud.githubusercontent.com/assets/25666/6342829/d19bfa4e-bbac-11e4-9ed3-759015e201a7.png)

**Comment by joshk** [comment]
Thanks for reporting this. I'll have the web team look into this, as well as the general design of all our pages to see how we can make the experience better.

**Comment by cvrebert** [comment]
Funny enough, this *had* been working just fine (albeit not specially mobile-optimized) prior to your recent super-flat redesign.

**Comment by joshk** [comment]
We have made some big CSS changes under the hood. We will look into this, but I don't have an ETA for a fix sorry.

**Comment by cvrebert** [comment]
Your new collapsing navbar has fixed this.
