### ISSUE TITLE
Ruby-head is slightly old

### ISSUE THREAD

**Issue by eregon** [travis-ci/travis-ci#3274]
ruby-head on Travis is:
`ruby 2.3.0dev (2015-02-16 trunk 49615) [x86_64-linux]`
r49615 was committed on Mon Feb 16, 2015 and they were plenty [green builds](https://travis-ci.org/ruby/ruby/builds) in between.
I also tried to hit the hook URL with my browser, but got a server error.

How often do you update ruby-head?
For ruby/rubyspec it would be fairly useful to have a recent version, but of course I understand if resources do not allow updating it at every build.

**Comment by BanzaiMan** [comment]
Hi, there. Thanks for pointing this out. I've looked into it, and found that there was a configuration change in the build process that wasn't reverted. I've fixed this, and see that the builds are happening now.

The `*-head` builds should be updated shortly. (Linux one is there already; http://rubies.travis-ci.org/ubuntu/12.04/x86_64/ruby-head)

I'm going to close this optimistically.

**Comment by eregon** [comment]
Awesome, I can confirm https://github.com/ruby/rubyspec/pull/33 passed, thanks!
