### ISSUE TITLE
Shell globbing / wildcard not working

### ISSUE THREAD

**Issue by neothemachine** [travis-ci/travis-ci#3275]
I try to append `PATH` with a folder name that I don't exactly now, I just know how it begins. Therefore I thought let's use `export PATH=$PATH:$PWD/ffmpeg-*` which works on my own machine but [not in Travis](https://travis-ci.org/esa/auromat/jobs/51992632#L220). Is this really not supported or am I doing something wrong?

**Comment by BanzaiMan** [comment]
Curious. What shell allows this behavior?

**Comment by neothemachine** [comment]
I tested it on bash. What does travis use?

**Comment by BanzaiMan** [comment]
bash 4.2 (http://packages.ubuntu.com/precise/bash) or something similar. Anyhow, it doesn't work on the shell we use. Find what directories are available with `ls`, and add each to `$PATH`; or create a symlink that you can add to `$PATH`.

**Comment by neothemachine** [comment]
I solved it with 
```sh
export PATH=$PATH:$PWD/`ls | grep ffmpeg-`
```
Note that I only need to add a single folder.
