### ISSUE TITLE
Builds fail if branch name has weird characters

### ISSUE THREAD

**Issue by fiestacasey** [travis-ci/travis-ci#3278]
For no particular reason our development team uses emoji's in branch names. This works fine in git, github, etc, but will not build on travis-ci.

[Example failure](https://magnum.travis-ci.com/wantable/wantable-2/builds/9721736) with branch name reportSSSS:snake:

```
Using worker: worker-linux-3602e2d9-2.bb.travis-ci.com:travis-linux-20

3.76s$ git clone --depth=50 --branch=reportSSSS\ git@github.com:wantable/wantable-2.git wantable/wantable-2
Cloning into 'wantable/wantable-2'...
warning: Could not find remote branch reportSSSS to clone.
fatal: Remote branch reportSSSS not found in upstream origin

The command "eval git clone --depth=50 --branch=reportSSSS\ git@github.com:wantable/wantable-2.git wantable/wantable-2" failed. Retrying, 2 of 3.
Cloning into 'wantable/wantable-2'...

warning: Could not find remote branch reportSSSS to clone.
fatal: Remote branch reportSSSS not found in upstream origin

The command "eval git clone --depth=50 --branch=reportSSSS\ git@github.com:wantable/wantable-2.git wantable/wantable-2" failed. Retrying, 3 of 3.
Cloning into 'wantable/wantable-2'...

Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
warning: Could not find remote branch reportSSSS to clone.
fatal: Remote branch reportSSSS not found in upstream origin

The command "eval git clone --depth=50 --branch=reportSSSS\ git@github.com:wantable/wantable-2.git wantable/wantable-2" failed 3 times.

The command "git clone --depth=50 --branch=reportSSSS\ git@github.com:wantable/wantable-2.git wantable/wantable-2" failed and exited with 128 during .

Your build has been stopped.
```

**Comment by BanzaiMan** [comment]
Thanks for the report. I believe this is a known issue, previously reported in #2169, which is a variation of #1376.

**Comment by joshk** [comment]
@BanzaiMan the difference is that this build doesn't stall, but the emoji doesn't work for the branch name either.

**Comment by BanzaiMan** [comment]
It depends on the codepoint that appears on the branch name, it seems. https://travis-ci.org/BanzaiMan/travis_production_test/builds/52073766 fails with ':bow:' and https://travis-ci.org/BanzaiMan/travis_production_test/builds/52073967 succeeds with 'あ'. Either way, I think this is a problem with the way we push our build script to the VM.

**Comment by Turbo87** [comment]
@BanzaiMan any plans on fixing this bug? I just ran into the same trap...
