### ISSUE TITLE
Expose Env Vars with info on source of PR

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#3279]
eg. TRAVIS_PR_SOURCE_REPO and TRAVIS_PR_SOURCE_BRANCH

**Comment by joshk** [comment]
@BanzaiMan could you pretty please look into this? I think it would be a great addition.

**Comment by BanzaiMan** [comment]
https://github.com/travis-pro/team-sapphire/issues/14

**Comment by svenfuchs** [comment]
This has never been fully completed. We've added changes to travis-core (see https://github.com/travis-pro/team-teal/issues/343) but these never ended up in scheduler, which is not even using travis-core any more. So I'm going to re-open this.

**Comment by BanzaiMan** [comment]
I think I can close this with recent additions of `$TRAVIS_PULL_REQUEST_{BRANCH,SHA,SLUG}`.
