### ISSUE TITLE
Access to Accounts/Profile page via Tor Browser fails with 401 Unauthorized response code

### ISSUE THREAD

**Issue by BobGirard** [travis-ci/travis-ci#3280]
After signing in to travis-ci.org with my GitHub credentials, I attempt to access the Accounts page from the menu hanging off my username.  The page displays the animated "Loading" message, but never presents any actual account or profile information.  Repeating this HTTP request with the browser console running, I see the message "Error while processing route: accounts.index" in the Console window and a 401 Unauthorized HTTP response code in the Network window (screenshots attached).  This behavior is reproducible with every attempt.  I'm using Tor Browser version 4.0.3 (based on Firefox ESR 31.4.0) on Linux Mint 17 Cinnamon 64-bit.

The page appears to work entirely normally in non-Torified Firefox 35.0.1.

![travis-ci accounts profile page](https://cloud.githubusercontent.com/assets/6164385/6363286/d8f7c22c-bc8e-11e4-95d2-b902dfcc7728.png)
![tor browser web console diagnostics](https://cloud.githubusercontent.com/assets/6164385/6363293/e990f054-bc8e-11e4-8c6c-a965eef2d797.png)
![tor browser network console diagnostics](https://cloud.githubusercontent.com/assets/6164385/6363298/f894e88a-bc8e-11e4-93b5-7e84be711de6.png)

**Comment by tacitus-aedifex** [comment]
this is still the case with tor browser 6.0.5.  please fix this.

**Comment by lislis** [comment]
Hey @BobGirard and @tacitus-aedifex!
Thank you for opening this issue. 

First of all I want to say that using Travis over Tor can degrade your anonymity as you need to enable JavaScript and log into both GitHub and Travis.

That being said, I took a look with Tor browser 6.0.7. and indeed, a lot of request get 401 or 403 statuses. It seems like sometimes `access-control` headers that we use to authenticate some api calls disappear from the request.

This however seems like a bug in Tor browser. One ticket is filed here https://trac.torproject.org/projects/tor/ticket/18080 

I'm therefore closing this ticket, as it has nothing to do with our web client but with the Tor browser itself.
