### ISSUE TITLE
Stuck in 'Please wait while we synchronize your data from GitHub' #3191

### ISSUE THREAD

**Issue by timani** [travis-ci/travis-ci#3284]
Hi there, 

I have the same issue where my account has been stuck synchronizing for about an hour

**Comment by sinthetix** [comment]
Hi @timani 

We're working through a database brownout right now which is impacting user sync. You can view the status of this incident here: http://www.traviscistatus.com/incidents/bc3jgcrjs7gt

Sorry for the delays and thank you for your patience! :)
