### ISSUE TITLE
APT whitelist request for libhdf5-serial-dev libatlas-base-dev libatlas-dev libblas-dev liblzo2-dev libbz2-dev libzmq3-dev

### ISSUE THREAD

**Issue by bosr** [travis-ci/travis-ci#3285]
In order to build the Python numerical packages (`scikit-learn`, `numpy`, `numexpr`, `scipy`, `pandas`, etc), on travis-ci.com I need the following packages:

- `libhdf5-serial-dev`
- `libatlas-base-dev`
- `libatlas-dev`
- `libblas-dev`
- `liblzo2-dev`
- `libbz2-dev`
- `libzmq3-dev`

Thank you in advance,
Regards
Romain

**Comment by BanzaiMan** [comment]
[libzmq3-dev](http://packages.ubuntu.com/precise/libzmq3-dev) is not available for Precise.

**Comment by bosr** [comment]
Argh, thanks 

Romain

**Comment by BanzaiMan** [comment]
@bosr If you are using libzmq3-dev, it is provided by our cookbooks, so your build should be unaffected.

**Comment by meatballhat** [comment]
@BanzaiMan so we're OK with libzmq3-dev after all, yes?

**Comment by BanzaiMan** [comment]
@meatballhat OK in the sense that it's a noop.

**Comment by bosr** [comment]
Thanks. My builds are now completing again, and are much faster. 

Regards

Romain
