### ISSUE TITLE
APT whitelist request for libproj-dev

### ISSUE THREAD

**Issue by bong0** [travis-ci/travis-ci#3287]
I need that geospatial library. It's a critical part of my project.

**Comment by bong0** [comment]
@BanzaiMan I still get a "Disallowing packages: libproj-dev" on `worker-linux-edu-docker-SOME_ID.prod.travis-ci.com:travis-linux-4`

**Comment by BanzaiMan** [comment]
Sorry about that. Could you try again?

**Comment by bong0** [comment]
@BanzaiMan Still disallowing. Any Idea how we can debug this issue? When do you read that whitelist? Every time you build the container for the run?

**Comment by bong0** [comment]
works now. If this is actually the normal procedure you should note this in the documentation!
