### ISSUE TITLE
Using hdiutil and codesign in node_js environment

### ISSUE THREAD

**Issue by Yimiprod** [travis-ci/travis-ci#3299]
Hi,
I'm using travis-ci to build and release a node-webkit application, and in the build process i try to create a dmg file.
For this i need hdiutil, and because i need to sign the app, i also use codesign.
Thoses two command doesn't exist and i can't figure how to install it (brew isn't available in node_js environment).

Any idea how to achieve it?

Thanks

**Comment by BanzaiMan** [comment]
You need to run those tools on OS X images. For that, you need `language: objective-c`. There, you should have a recent version of node.js and be able to build your application.

**Comment by Yimiprod** [comment]
thanks worked like a charm
