### ISSUE TITLE
extra "]" in the cran repo url during installing R packages

### ISSUE THREAD

**Issue by maverickg** [travis-ci/travis-ci#3301]
In my .travis.yml file, say I have

```
r_packages:
  - inline
  - Rcpp
```

But it fails to install those package because of an extra "]" in the repo url.  This is I can see from the output:

```
$ Rscript -e 'install.packages(c("inline", "Rcpp"), repos="http://cran.rstudio.com]")'
..

Warning: unable to access index for repository http://cran.rstudio.com]/src/contrib
Warning message:
```

@craigcitro @eddelbuettel  @hadley

**Comment by craigcitro** [comment]
Do you have a link to your repo? Is there any chance you're manually setting the `CRAN` variable to something with a `]` in it?

**Comment by craigcitro** [comment]
aha -- i found the commit.

the problem was actually in the `.travis.yml` file itself -- see line 42 on the RHS here:

https://github.com/stan-dev/rstan/commit/aed0b5f077ea7f3078ec766f478ac1b8177401db#diff-354f30a63fb0907d4ad57269548329e3R42

there's a `'` vs. `"` mismatch, which leads to the syntax error.

@BanzaiMan i think we can close.

**Comment by maverickg** [comment]
Because I could not use `r_packages`, I did it manually.  I did make a mistake in the place @craigcitro pointed out.  

Anyway, I created a pull request to remove the extra ]: https://github.com/travis-ci/travis-build/pull/393

**Comment by craigcitro** [comment]
wow -- thanks for catching that @maverickg!

looking into why that failure doesn't cause the build to error out.

**Comment by maverickg** [comment]
Thanks for all the efforts making it possible to test R packages and thanks for the travis-ci service.

**Comment by BanzaiMan** [comment]
The PR was merged and deployed.
