### ISSUE TITLE
IPv6 in containerized environment

### ISSUE THREAD

**Issue by else** [travis-ci/travis-ci#3302]
We use Travis to deploy our project on an IPv6-only host. While this works using the virtualized boxes, it did not work in the container-based infrastructure ("network unreachable"). I was unable to find information on whether this is a general limitation or whether it's a routing problem. Can someone tell me if IPv6 in containerized environments should work in principle?

Here's a build that failed: https://travis-ci.org/raumzeitlabor/rzl-homepage/builds/52490634#L932

Thanks for the great service.

**Comment by BanzaiMan** [comment]
The container workers are on EC2, so I do not think IPv6 is available. https://forums.aws.amazon.com/thread.jspa?messageID=595152

**Comment by joshk** [comment]
Thanks for creating the issue @else, we will look into updating our documentation to reflect this issue.

**Comment by else** [comment]
Would it be possible to tunnel IPv6 traffic from your build hosts? Docker gained IPv6 support with [version 1.5](https://blog.docker.com/2015/02/docker-1-5-ipv6-support-read-only-containers-stats-named-dockerfiles-and-more/).

**Comment by solarce** [comment]
https://docs.travis-ci.com/user/ci-environment/#Networking has been kept up to date about where IPv6 has worked, but this functionality was a by-product of the hosting platform used for sudo enabled Precise builds, but it's not something we consider a core feature that we support in Travis CI at this time and it will go away as we migrate away from that hosting platform. 

Unfortunately, the major public cloud providers do not provide any supported methods for having internal IPv6 connectivity nor are there any real options for in-bound IPv6 external connectivity in a way that is usable for Travis's build environments, so we're limited by what is supported on the providers which give us the best economies of scale and overall feature sets we need. So at this time we are unable to make any commitments to supporting IPv6 in our containerized builds.
