### ISSUE TITLE
Julia cannot find a library that's on `LD_LIBRARY_PATH` in Travis/Linux

### ISSUE THREAD

**Issue by dpo** [travis-ci/travis-ci#3303]
We're running Julia code on Travis/Linux with both `release` and `nightly` that's failing to find a library. The library is on the `LD_LIBRARY_PATH`, and the latter [has been `export`ed](https://travis-ci.org/optimizers/CUTEst.jl/jobs/52505181#L407).

[Here](https://travis-ci.org/optimizers/CUTEst.jl/jobs/52505181#L540) is the error. The library in question is linked in using a command of the form
````JULIA
run(`gfortran ... -lcutest ...`)
````

Before trying to link that library in, the Julia code runs an executable that's on the `PATH`, and that works.  The script output consists in [lines 538--539](https://travis-ci.org/optimizers/CUTEst.jl/jobs/52505181#L528).

I tried [`push`ing the library path explicitly](https://travis-ci.org/optimizers/CUTEst.jl/jobs/52505181#L524) before running the tests, to no avail.

Any hints would be welcome. Thanks in advance!

cc: @tkelman @ninjin @staticfloat @abelsiqueira

**Comment by tkelman** [comment]
This isn't Julia failing to find the library, it's ld. Does the same linking command work outside of Julia? If not, I'd just spell out the location of the library with `-L`.

**Comment by abelsiqueira** [comment]
@tkelman is right. The linking outside of Julia is not working, and the solution I found, apart from passing `-L`, is sending `libcutest.so` to `/usr/local/lib` or similar, which is the workaround I used.

**Comment by dpo** [comment]
Sorry, that's right, it'd `ld`'s fault. The issue seems to be specific to Ubuntu. We don't have this problem on Travis/OSX (the repo I pointed to above isn't OSX enabled, but @abelsiqueira's fork is) or on Arch Linux. We've had to specify `-L` explicitly.

Thanks!
