### ISSUE TITLE
Issues with msbuild and Mono in a C# project

### ISSUE THREAD

**Issue by philippgille** [travis-ci/travis-ci#3307]
Please note that I'm new to Travis CI and Coverity. But I'd like to share my experiences anyway. I wanted to try them out and created a "Hello world!"-project for the Nancy framework running on ASP.NET.

Error
------

On scan.coverity.com, when adding the project and selecting "Configure Travis CI" for uploading a build, they show an example snippet that you can use in the travis.yml. It contains these lines:
```yml
build_command_prepend: "msbuild /t:Clean"
build_command:   "msbuild /t:Rebuild"
```
I wondered why Coverity kept telling me to upload a build, although the build completed successfully on Travis CI. Then I looked into the build logs on travis-ci.org and found (after expanding the line with the tag `build_coverity`):

`bash: line 74: msbuild: command not found`.

Solution
---------

From the `bash` hint it's easy to tell that you're obviously using Linux machines. And `msbuild` is Windows-only.

After replacing `msbuild` by `xbuild` in the `travis.yml` it worked (kind of - I'll come to that in a moment).

Suggestions
----------------

So, I know the source of the fault is me, the user, but maybe you could improve this by:

- Showing some warning when the coverity scan fails (e.g. when it doesn't get to `Uploading Coverity Scan Analysis results...`) and showing the reason for it
- In the [Travis CI C# documentation](http://docs.travis-ci.com/user/languages/csharp/) mention that you're using xbuild instead of msbuild and that the `travis.yml` has to be changed accordingly
- Just replace `msbuild` by `xbuild` in the `travis.yml`. Maybe a bad idea because when the user a specific build tool in the travis.yml, exactly that one should be used. But on the other hand xbuild is built to be compatible to msbuild as far as I know.
- Let the user choose which build tool to use in the main configuration section of travis.yml, where `csharp` and the solution name are. You're probably using Linux machines currently and you would have to use Windows machines for that, but it might be better suited for C# projects. PaaS like AppHarbor use msbuild as well. I didn't try it yet, but I think Mono isn't able to compile and run every kind of C# project, for examle when frameworks like WPF or WCF are being used. I'm actually getting a warning regarding a .NET 4.5 library that's in ASP.NET projects by default and can't be found on Travis CI: `assembly named 'System.Web.Entity' not found`, while looking for it in `/usr/lib/mono/4.5/` and `/usr/lib/mono/4.5/Facades/`. I guess this could be a GitHub issue on its own.

Follow-up problem
-----------------------

Now regarding the "kind of works":

The Travis CI build logs don't contain the msbuild error message anymore but a seemingly successful `Uploading Coverity Scan Analysis results...`, after a successful build. But on Coverity there's an error message:
> Build uploaded has not been compiled fully. Please fix any compilation error. You may have to run bin/cov-configure as described in the article on Coverity Community. Last few lines of cov-int/build-log.txt should indicate 85% or more compilation units ready for analysis...[more](https://communities.coverity.com/message/4820#4820)

I'm not sure if I can fix this with some configuration? Maybe this should be an issue on its own as well?

Other thoughts
-------------------

The way the project is currently set up, there are 2 builds that seem to be exactly the same: The one for coverity first, and yours right afterwards. Couldn't you just build the project once and then also use it to upload the results to Coverity?

@joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
Coverity seems to only support C# on Windows right now, see http://stackoverflow.com/questions/27177284/does-coverity-support-xbuild-mono.

As we're building with Mono on Linux, the behavior you're seeing is "by design" and I don't think we can do anything about it until Coverity starts supporting Linux.

The issue tracker also has some entries for Windows support on Travis (https://github.com/travis-ci/travis-ci/labels/windows), but no idea what the status of that is.

Regarding `System.Web.Entity`: I'd be surprised if you actually needed that assembly in a Nancy application, since it only contains the Entity Data Source control for WebForms for older versions of Entity Framework.

**Comment by philippgille** [comment]
Thanks for the first link! For others reading these ticket comments the most important parts:
> Our C# analysis only supports the Visual Studio C# compilers

and
> C# build capture is only supported on Windows.

What about the idea to notify the user somehow and skip the step when the `travis.yaml` contains `coverity_scan` as plugin and either `msbuild` or `xbuild` as build command?

`System.Web.Entity` isn't needed, that's correct. It was just an example that depending on which framework you use there are projects that can't be built with Mono.

But it's great to see that you're looking into offering builds on Windows machines (#2104).

**Comment by akoeplinger** [comment]
>What about the idea to notify the user somehow and skip the step when the  travis.yaml  contains  coverity_scan  as plugin and either  msbuild  or  xbuild  as build command?

As far as I know, with the way the C# plugin is integrated into the Travis build this is not possible, since we don't know that Coverity is enabled. We could of course add a note to the docs about it :)

**Comment by philippgille** [comment]
That would be great, thanks!
