### ISSUE TITLE
Client side JavaScript error when viewing help for allowed failures

### ISSUE THREAD

**Issue by nicolasmccurdy** [travis-ci/travis-ci#3309]
## Reproducing
1. Visit a build that has allowed failures (I saw noticed the issue on [this build](https://travis-ci.org/nicolasmccurdy/request/builds/52693373)).
2. Click the "?" icon next to "Allowed Failures". It should not matter if the build is in progress or completed.

## Expected behavior
I see some sort of help dialogue, or I am taken to a help page.

## Actual behavior
- Nothing happens.
- The following error is shown in the JavaScript console:
```
travis-bdfa836e35ea2e374c4ceff2a87e0ec4.js:10
Uncaught TypeError: undefined is not a function
```

## Affected browsers
- Mac OS 10.10.2 (Yosemite)
  - Firefox 36.0
  - Google Chrome 40.0.2214.115
  - Safari 8.0.3

**Comment by clekstro** [comment]
On that build I currently see the following dialog shown when hovering over the `?`:
<img width="326" alt="screen shot 2016-02-13 at 10 31 22 pm" src="https://cloud.githubusercontent.com/assets/366944/13030193/b6c54f06-d2a1-11e5-9003-bd4394a88df4.png">
There also doesn't appear to be a JS console error anymore. @nicolasmccurdy Can this be closed?

**Comment by nicolasmccurdy** [comment]
This is fixed, thanks!
