### ISSUE TITLE
Logs not being dumped on failure

### ISSUE THREAD

**Issue by craigcitro** [travis-ci/travis-ci#3312]
my fix in travis-ci/travis-build#396 causes the build to fail before we have a chance to actually dump the install/test logs (eg [this build](https://travis-ci.org/gavinsimpson/neotoma/builds/52632808)).

one way to fix this is to track exit status, but a nicer one would be to override `after_failure` in the build script. @BanzaiMan is there a way to override `after_failure`? i tried and failed to do this when writing the original PR, but i suspect it was user error on my part.

**Comment by joshk** [comment]
travis-build should not define a default after_failure, that is meant for the user.

Just to confirm, is the motivation to display the install and test logs when install or test fails?

Does the tooling not do this already when running the install and test scripts?

**Comment by craigcitro** [comment]
@joshk yes, that's right -- when `R` install/check commands fail, they just give a reference saying "go check this file for more information". the convention with r-travis was that i provided a `dump_logs` command that people could add to the `after_failure` block, so i was thinking of doing the same thing here.

it's easy enough to just track exit status and dump logs before calling `sh.failure`, but i wanted to check first.

**Comment by joshk** [comment]
I would recommend that approach, to check the exit code then cat the logs.

Is it possible to ask the R team to add a verbose mode and print the errors to STDOUT?

**Comment by jimhester** [comment]
Has there been any progress here?  I don't need to have a built-in `dump_logs`, but I do need to be able to run commands in `after_failure` if the tests fail (so I can dump the logs).

Currently the entire build stops as soon as the check fails, which makes it impossible to dump the test logs.

**Comment by craigcitro** [comment]
@jimhester no -- i've been slammed with other stuff, and haven't had a chance. if you're interested in trying to roll a fix, i can point you in the right direction ...

**Comment by jimhester** [comment]
Sure I can take a stab at it.  I assume removing the assert from [travis-build/lib/travis/build/script/r.rb#L145-L146](https://github.com/travis-ci/travis-build/blob/e96e9fc2a1ec4cb93a5b84f34566516dfe5bd457/lib/travis/build/script/r.rb#L145-L146) would be the first step, then probably removing the current `after_failure` function definition.

I'll then just have to figure out the correct way to check the exit code and how to fail, but not abort the build, which I can do.

**Comment by craigcitro** [comment]
yeah, that sounds about right. i think you can just pull the `after_failure` bit in, so something like:

    sh.cmd "R CMD check \"${PKG_TARBALL}\" #{config[:r_check_args]}",
                 assert: false
    sh.if '$? -neq 0' do
      sh.echo 'R CMD check failed, dumping logs'
      dump_logs
      sh.failure 'R CMD check failed'
    end

**Comment by jimhester** [comment]
Ok that makes sense to me, thanks for the sketch.

**Comment by craigcitro** [comment]
no sweat -- thanks for helping! :grin: 

this has been in my queue for a while, but just hasn't made it to the top. :grimacing:

**Comment by jimhester** [comment]
Ok this should be fixed in https://github.com/travis-ci/travis-build/pull/427

**Comment by BanzaiMan** [comment]
The PR has been merged and deployed.
