### ISSUE TITLE
[Feature Request] Performance Testing

### ISSUE THREAD

**Issue by thefosk** [travis-ci/travis-ci#3313]
It's been a while since #352 has been closed, and I wonder if now could be a better time to do some brainstorming on it.

**Comment by joshk** [comment]
Feel free to get the brainstorming started :)

**Comment by roidrage** [comment]
Thank you for your suggestion, but I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
