### ISSUE TITLE
Yellow Status Favicon Difficult To See

### ISSUE THREAD

**Issue by sinthetix** [travis-ci/travis-ci#3325]
We recently have been receiving lots of feedback about our changing favicon depending on build status and it has been overwhelmingly positive (yay!). 

However, there has been honest feedback about the icon being difficult to see. So we are opening up an issue to get more feedback on how everyone feels about the new icon (Mr. T in red, yellow, green, and grey depending on build status). :)

![yellowicon](https://cloud.githubusercontent.com/assets/5157195/6467767/46044c82-c19e-11e4-9866-9af5b273efad.png)

**Comment by saltinejustine** [comment]
maybe this will work better. the actual color is kind of ugly but it's vastly more readable against the grey tabs?

![yellow-favicon-01](https://cloud.githubusercontent.com/assets/823381/6472099/1443f714-c244-11e4-985a-b9713794c5a9.png)

**Comment by joshk** [comment]
The darker yellow looks a bit better, lets get that deployed

**Comment by nicolasmccurdy** [comment]
@saltinejustine :+1:

**Comment by saltinejustine** [comment]
Fixed and deployed!
