### ISSUE TITLE
Broken link to PR in notifications for Slack

### ISSUE THREAD

**Issue by xaka** [travis-ci/travis-ci#3326]
Here is the notification:

```
Build #7817 (8ef0478) of <project>@<branch> in PR # by <author> passed in 7 min 16 sec
```

As you can see, there is no PR number after hashtag (#) and link points to `https://github.com/<project>/pull/`, which is invalid URL.

**Comment by BanzaiMan** [comment]
What does your `.travis.yml` look like?

**Comment by xaka** [comment]
I hope you only need `notifications` part as I cannot share the whole file for security reasons:

```
notifications:
  slack:
    secure: LGsUSjdnGwPvMTu2J43aZOyg0SGzTZaUOdGncqCAdDc8RoFRX36SAYJG8l3k42yeqKgYt0NoH2fz1soyUzbmvT5tgAWZj7Np/klyAsBxkwLKX1I95Ya/fWWXoUPAK/dbYFDde38pm+dYVbsqO5nnR+37cgq048TNbEvsTSLx+X0=
```

If you need additional details, we can move our conversation to support chat.

**Comment by BanzaiMan** [comment]
Please email support@travis-ci.com.

**Comment by BanzaiMan** [comment]
This is an issue alluded to in https://github.com/travis-ci/travis-tasks/pull/25#issuecomment-71565138.

**Comment by BanzaiMan** [comment]
@xaka I've pushed a potential fix, and my test was successful. Could you test it?

**Comment by xaka** [comment]
It works! Thanks
