### ISSUE TITLE
Riak ulimits not set

### ISSUE THREAD

**Issue by jerith** [travis-ci/travis-ci#3328]
Riak needs a lot of file handles, and it's currently using the (pretty low) defaults. This can be adjusted by creating the file `/etc/default/riak` with the following content:
```
ulimit -n 65536
```

**Comment by jerith** [comment]
Actually, this seems to be a little less simple than it appears. Sometimes my builds already have a suitable ulimit set and sometimes they don't (and are unable to set it), with the only apparent difference being the worker running the build. For example:

* https://travis-ci.org/jerith/travis-riak-weirdness/builds/53016951 has a `ulimit -n` of 1024, which riak complains about on lines 78-81 of the log
* https://travis-ci.org/jerith/travis-riak-weirdness/builds/53016680 has a `ulimit -n` of 65536 or higher and riak starts happily without complaining on line 78 of the log

In both builds, this happens after my repository has been cloned, but before any of my own scripts are executed.

**Comment by joepvd** [comment]
This issue refers to the legacy infrastructure. Please open a new issue if you encounter this on the current infrastructure.
