### ISSUE TITLE
www.rabbitmq.com is down, cannot run apt-get update

### ISSUE THREAD

**Issue by cadrian** [travis-ci/travis-ci#3330]
I don't know what www.rabbitmq.com is but `apt-get update` fails because the server seems to be down

e.g. [this build](https://travis-ci.org/cadrian/libcad/builds/53020234)

What can I do?

Thanks

**Comment by gau1991** [comment]
Yah.. I am also facing this issue..
From my Travis:

```
Get:77 http://security.ubuntu.com precise-security/universe TranslationIndex [05 B]
Get:78 http://security.ubuntu.com precise-security/main Translation-en [216 kB]
Hit http://security.ubuntu.com precise-security/multiverse Translation-en
Hit http://security.ubuntu.com precise-security/restricted Translation-en
Get:79 http://security.ubuntu.com precise-security/universe Translation-en [65.3 kB]
Fetched 5,955 kB in 3s (1,712 kB/s)
W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/Release.gpg Could not connect to www.rabbitmq.com:80 (192.240.153.117). - connect (113: No route to host)
W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/main/binary-amd64/Packages Unable to connect to www.rabbitmq.com:http:
W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/main/binary-i386/Packages Unable to connect to www.rabbitmq.com:http:
W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/main/i18n/Translation-en_US Unable to connect to www.rabbitmq.com:http:
W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/main/i18n/Translation-en Unable to connect to www.rabbitmq.com:http:
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update" failed and exited with 100 during .
Your build has been stopped.
```

**Comment by BanzaiMan** [comment]
Sorry about the troubles. Is this a persistent problem, or a transient one?

**Comment by cadrian** [comment]
It is the first time I see this problem. Their site seems to be back up, I am restarting my build and I will tell you.

**Comment by cadrian** [comment]
It runs fine now. Sorry for the trouble.

**Comment by DavidLP** [comment]
It is again down...

**Comment by cristicbz** [comment]
Also hit by it, happened yesterday and still happens today:
https://travis-ci.org/cristicbz/rust-doom

**Comment by dmelamedcl** [comment]
Same here, really annoying...

**Comment by BBonifield** [comment]
@BanzaiMan This is a persistent issue.  The RabbitMQ team said on their twitter that they are doing maintenance, but the problem is that the rabbitmq apt source is added on the VMs by default.  So if you are doing `apt-get update` in your machine setup, you run into this.  I tried removing the two sources in `/etc/apt/sources.list.d`, but that doesn't seem to do it.  Recommendations?

**Comment by freeman-lab** [comment]
Just to add, I also experienced this issue twice in the last couple days, but it does seem intermittent (I had a few builds run successfully without any issue)

**Comment by SamuelRamond** [comment]
Same issue here today, i manage apt-get update after 10 retry now impossible to apt-get install i had to retry 5/6 times too

**Comment by Juanlu001** [comment]
Had this problem too yesterday, is there any temporary workaround?

**Comment by SamuelRamond** [comment]
In my case after retrying 5/6 time it succeeded, some server might still be up :+1:

**Comment by Niall1stLoughnane** [comment]
www.rabbitmq.com server is down?

**Comment by martinb3** [comment]
Was just down again for about 10 minutes, confirmed through various 3rd parties.

**Comment by marek-obuchowicz** [comment]
Still down...

**Comment by azr** [comment]
having the same issue trying to bring up a local travis build here. 
Is https://quay.io/repository/travisci/travis-go still okay to run local tests ?
