### ISSUE TITLE
APT whitelist request for libmagic-dev

### ISSUE THREAD

**Issue by bensie** [travis-ci/travis-ci#3331]
We're trying to use the `ruby-filemagic` Ruby gem in CarrierWave, which depends on this package. Thanks!

**Comment by bensie** [comment]
@meatballhat Thanks! How long before this should take effect on Travis builds? Just attempted a retry on one and it's still failing due to this being disallowed.

**Comment by meatballhat** [comment]
sorry about the delay!  I was doing a batch of changes before restarting
travis-build and then got sidetracked by an incident :scream_cat:

you should be all set now :metal:
