### ISSUE TITLE
Unable to install PostgreSQL extentions

### ISSUE THREAD

**Issue by almet** [travis-ci/travis-ci#3332]
Hi,

I'm not able to use PostgreSQL extensions, is there anything I'm mi-trying?

https://travis-ci.org/mozilla-services/cliquet/jobs/53074641#L132-L134

Travis file interesting part is:

```
sudo: true
addons:
  postgresql: "9.3"
before_install:
  - sudo apt-get install postgresql-contrib-9.3
before_script:
  - psql -c "CREATE DATABASE testdb ENCODING 'UTF8' TEMPLATE template0;" -U postgres ; psql -c "CREATE EXTENSION pgcrypto;" -U postgres;

```

Thoughts?

**Comment by BanzaiMan** [comment]
Maybe it's not installing the extension to the right version? Though the output doesn't seem to indicate such a problem. Email support@travis-ci.com, and we can spin up a debug VM for you.

**Comment by BanzaiMan** [comment]
It's become stale.
