### ISSUE TITLE
Sauce Connect addon doesn't close tunnels.

### ISSUE THREAD

**Issue by vr2262** [travis-ci/travis-ci#3333]
Many of my builds were failing because of open Sauce Connect tunnels hanging around from completed Travis builds. It looks like the VM gets killed before the `sc` process has a chance to close the tunnel properly.

As a workaround I added this section to my `.travis.yml` file:
```
after_script: 
  - kill $(ps aux | grep '[b]in/sc' | awk '{print $2}')
  - sleep 5
```
This gives the `sc` process time to close the tunnel:
https://travis-ci.org/SEL-Columbia/dokomoforms/jobs/53076569#L688

**Comment by joshk** [comment]
Thanks for reporting this @vr2262, we will look into a fix shortly

**Comment by vr2262** [comment]
Thanks for the quick turnaround @meatballhat
