### ISSUE TITLE
unable to find a .travis.yml file

### ISSUE THREAD

**Issue by geuis** [travis-ci/travis-ci#3334]
I get this error when attempting to run tests.

    WARNING: We were unable to find a .travis.yml file. This may not be what you want. Build will be run with default settings.

Github: https://github.com/geuis/argon
The Travis url: https://travis-ci.org/geuis/argon

The build history shows my commits and the travis.yml file is in the repo. 

What am I missing?

**Comment by BanzaiMan** [comment]
Hello. The [latest build](https://travis-ci.org/geuis/argon/builds/53090126) seems fine. Has anything changed?

**Comment by nicolasmccurdy** [comment]
> The build history shows my commits and the travis.yml file is in the repo.
Make sure your repository has a `.travis.yml` file (with the period in front).

It's also possible that you deleted `.travis.yml` in another branch, or pushed a new commit on a branch that never had a `.travis.yml` file.

**Comment by sickill** [comment]
I have the same issue: https://travis-ci.org/asciinema/asciinema/builds/53200097
I renamed repository on GitHub, then synced with Github on Travis, pushed, and it now can't find .travis.yml.

**Comment by sickill** [comment]
Ok, it fixed now when I pushed new commit.

**Comment by geuis** [comment]
@BanzaiMan Sorry, didn't get a chance to report back. My fix was to make a one line change of a space in .travis.yml and pushed that to master. Then travis picked it up.

**Comment by BanzaiMan** [comment]
@geuis Thanks for the report. Glad to hear that it's working for you!

**Comment by tabalinas** [comment]
The same issue for me after renaming my repo. Pushing of new commit solves the problem.
