### ISSUE TITLE
py.test stalls after tests succeed

### ISSUE THREAD

**Issue by nikmolnar** [travis-ci/travis-ci#3336]
I'm having a problem with py.test when running a Python 3.4 build. The Python 2.7 build completes just fine, but with the 3.4 build, the tests succeed, but py.test never exits and eventually the build times out and fails. It's not related to any change in the code: I've tried running a previous build which previously succeeded and now it stalls. Any ideas?

Full test output for 3.4 (failed): https://s3.amazonaws.com/archive.travis-ci.org/jobs/53085853/log.txt
Full test output for 2.7 (succeeded): https://s3.amazonaws.com/archive.travis-ci.org/jobs/53085854/log.txt

**Comment by BanzaiMan** [comment]
Very curious. If the old code is hanging, too, then it is probably the bad interaction between the updated components. Email support@travis-ci.com, please. We can spin up a debug VM for you.

**Comment by nikmolnar** [comment]
Thanks for the quick response! I'll follow up by email.

**Comment by nikmolnar** [comment]
I got a debug VM and was able to track the problem to an bug in the latest version of HTTPretty (https://github.com/gabrielfalcao/HTTPretty/issues/228). Using the previous version of that library resolved the issue.

Thanks for your help!
