### ISSUE TITLE
APT whitelist request for libprotobuf-dev protobuf-compiler

### ISSUE THREAD

**Issue by dapurv5** [travis-ci/travis-ci#3341]
When using google protobuf in my project, I need the protoc command in the command line which is available via installing these packages in ubuntu.
Please whitelist these packages so they can be installed.

**Comment by dapurv5** [comment]
i tried rebuilding my project after you did this but it still complains as.

Disallowing packages: libprotobuf-dev, protobuf-compiler
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process

Do I need to wait for a day to see the changes reflected?

**Comment by meatballhat** [comment]
sorry about the delay!  I was doing a batch before restarting travis-build
and then got sidetracked by an incident :scream_cat:

you should be all set now :+1:

**Comment by dapurv5** [comment]
Hey, 
Thanks a lot. The packages can be installed now. Could you please help me with how I can install the 2.5.0 version using apt_packages instead of the default version.

**Comment by BanzaiMan** [comment]
http://packages.ubuntu.com/precise/protobuf-compiler only has 2.4.1. If you need a newer version, you need to compile it from source.

**Comment by meatballhat** [comment]
@BanzaiMan I double checked since we have a few more sources in the build env than `precise main` and sure enough it's not available:

```
travis@b4f70aa1a7c1:~$ sudo apt-get install protobuf-compiler=2.5.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '2.5.0' for 'protobuf-compiler' was not found
```

@dapurv5 A nice advantage of the container-based infrastructure is that directory caching is free, so doing as @BanzaiMan suggests and installing from source plays nicely if you do something like:

``` yaml
cache:
  directories:
  - $HOME/.protobuf

before_install:
- # download the tarball
- # compile however (I'm guessing here)
- ./configure --prefix=$HOME/.protobuf
- # etc...
```
