### ISSUE TITLE
Permission denied for mocha when running coverage script

### ISSUE THREAD

**Issue by am11** [travis-ci/travis-ci#3347]
Hi, we have a [coverage script](https://github.com/sass/node-sass/blob/beffe92723c2a1848eef248b27c79dac2bcf6446/scripts/coverage.js) in node-sass for TravisCI. It was last updated on Nov 4 2014. It was reporting coverage [to covealls](https://coveralls.io/r/sass/node-sass) till yesterday when I rebased https://github.com/sass/node-sass/commit/c9ed9300640cf746fb99204c10fc3aa8046bee6b over https://github.com/sass/node-sass/commit/b45adb69488c215d3019374e005bcfbc04605e65 (added scripts/upload.js, which is a totally unrelated file). Now we get permission denied on TravisCI: https://travis-ci.org/sass/node-sass/jobs/53495198#L1320 on running the coverage script (after passing all tests with mocha).

>\> node-sass@2.0.1 coverage /home/travis/build/sass/node-sass
 node scripts/coverage.js
>
/home/travis/build/sass/node-sass/node_modules/.bin/_mocha: 1: /home/travis/build/sass/node-sass/node_modules/.bin/_mocha: /bin: Permission denied

I don't know what to make of it. There is no change made in directory permissions either. Could it be a recent change in TravisCI job worker?

//cc @kevva

**Comment by raine** [comment]
sounds like it could be related to #3348

**Comment by joshk** [comment]
In that case, closing this as a duplicate

**Comment by am11** [comment]
@raine, this turned out to be mocha issue:

https://travis-ci.org/am11/node-sass/jobs/53533514#L1310 (mocha v2.1.0) vs.
https://travis-ci.org/sass/node-sass/jobs/53495198#L1320 (mocha v2.2.0).

Thanks for pointing it out,  (-8
