### ISSUE TITLE
unable to give arguments to mocha

### ISSUE THREAD

**Issue by raine** [travis-ci/travis-ci#3348]
It seems to be interpreting `--harmony` as a file location. I am pretty sure this worked before, as I have builds on Travis that succeeded with the same `make test`.

https://travis-ci.org/raine/ez-jenkins/builds/53493011

```
Now using node v0.12.0
$ node --version
v0.12.0
$ npm --version
2.5.1
$ nvm --version
0.23.3
$ npm install 

> ez-jenkins@0.1.4 prepublish /home/travis/build/raine/ez-jenkins
> make prepublish
$ npm test

> ez-jenkins@0.1.4 test /home/travis/build/raine/ez-jenkins
> make test

node_modules/.bin/mocha --harmony
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn --harmony ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
make: *** [test] Error 1
npm ERR! Test failed.  See above for more details.

The command "npm test" exited with 1.

Done. Your build exited with 1.
```

### update

Same issue if you run mocha directly with npm test, instead of using make

```
  "scripts": {
    "test": "mocha --harmony-generators"
  },
```

### update 2

The issue persists even with the branch reverted to the state of [last working commit](https://travis-ci.org/raine/ez-jenkins/builds/53411796), so problem isn't code.

**Comment by joshk** [comment]
Can you please confirm that the version of Mocha is the same as previous runs?

We have not changed the build environment in weeks, so I have some doubts it is related to Travis, rather I think it is related to some dependency changes.

**Comment by raine** [comment]
It seems you're absolutely right. I should've checked mocha's issues before making noise here.

https://github.com/mochajs/mocha/issues/1583
