### ISSUE TITLE
Casher fails to create cache

### ISSUE THREAD

**Issue by kkaefer** [travis-ci/travis-ci#3352]
I'm seeing failures in the "store build cache" step: https://travis-ci.org/mapbox/mapbox-gl-native/jobs/53658034#L1537

Casher seems to crash when getting the mtime of a file that does not exist. Why it tries to get that file's mtime I don't know.

**Comment by BanzaiMan** [comment]
Sorry about the delay. Does/did the file in question exist in the cache when the build started? I think there is a bug with the caching utility, just this way.

**Comment by BanzaiMan** [comment]
We have deployed many improvements in the caching utility recently.

I'm closing this optimistically. If you continue to see problems, do open a new issue. Thanks.
