### ISSUE TITLE
Unable to build native modules with io.js

### ISSUE THREAD

**Issue by bpaquet** [travis-ci/travis-ci#3355]
I'm unable to build any native modules with io.js.

Example : https://travis-ci.org/bpaquet/node-logstash/jobs/53721892#L312

io.js does not success to get the tarball of node code to get headers : https://github.com/TooTallNate/node-gyp/blob/master/lib/install.js#L246

The same package.json works without problems with node 0.10 or 0.12.

Is there anything specific to add in travis config ?
For example to specify the dist-url to node-gyp ?

**Comment by BanzaiMan** [comment]
I believe the subject of this issue is misleading. The error comes from the failures to fetch the source, not the inability to build modules.

What server is this trying to reach, and what are the exact URLs that return 404?

**Comment by bpaquet** [comment]
The 404 is when node-gyp try to fetch the node source code to build native module. It can be related to io.js / npm install.

**Comment by BanzaiMan** [comment]
So, what is the URL that your job is getting 404 for?

**Comment by bpaquet** [comment]
Hi,

It's not my job which get the 404. It's npm when he try to install the zmq
node binding, which requires native compilation.

The native compilation is performed by node-gyp, and node-gyp gets a 404
when he tries to get the node source code (it's what I understand when I
read the node-gyp code).
So the url in 404 should be  http://nodejs.org/dist/ + '/v' + version + '
/node-v' + version + '.tar.gz'. May be nodejs.org is not replaced by iojs ?

Bertrand

**Comment by BanzaiMan** [comment]
You can access the value while the test is executing, right? You can dump the value of the URL to the log if it fails. And see if that URL actually corresponds to an existing resource.

**Comment by bpaquet** [comment]
So, I finally find a source of the problem : when I add npm install -g npm in before_install hooks (to force npm update), travis is unable to build native module with iojs. I don t know why.

You can find a build with no code, just a package.json and .travis.yml which points out the problem.
https://travis-ci.org/bpaquet/travis_iojs_native

If you think it's not a real issue, feel free to close it.

**Comment by BanzaiMan** [comment]
@bpaquet For sure, this is not a Travis CI problem. I forked your travis_iojs_native repo, and added `--verbose` to the install command. Take a look:

https://travis-ci.org/BanzaiMan/travis_iojs_native/jobs/54187595#L213 shows:

```
gyp http GET http://nodejs.org/dist/v1.5.1/node-v1.5.1.tar.gz
```

which does not exist. I am guessing that `gyp` assumes that it is running on Node.js, and that the version corresponds to that of Node.js instead of io.js.

I don't know who should fix what, but that's the crux of this problem.

**Comment by rgbkrk** [comment]
I'm not too surprised that the combination of node-gyp, nvm, travis, and node-zmq is causing problems. My builds are failing with an electron app after recent updates to Electron. :unamused:

**Comment by rgbkrk** [comment]
Travis is awesome, no doubt, but I'm a bit stuck. Builds in a docker container are fine as are builds on OS X boxes.

**Comment by BanzaiMan** [comment]
@rgbkrk Sorry to hear about the problem. If it is a different issue, please open a new one, along with a relevant build log URL. Thanks.
