### ISSUE TITLE
docs: "If you do not override the install build phase" is unclear on caching page

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#3357]
On http://docs.travis-ci.com/user/caching/ this phrase is used in multiple places:
"If you do not override the install build phase"
...including for the pip section, which was the one in which I was interested.

I interpreted this as "if you do not override the cache directory for pip by using --download-cache, this will work". Whereas it actually means:
"If you do not define your own 'install' section in .travis.yml"

ie: I didn't even know there was a default install step, so didn't know there was anything to override.

**Comment by edmorley** [comment]
It would be great to link to https://github.com/travis-ci/travis-ci/issues/3239 as well :-)

**Comment by BanzaiMan** [comment]
Could you suggest the improvement as a PR to https://github.com/travis-ci/docs-travis-ci-com? Thank you!

**Comment by techtonik** [comment]
I am a second that this phrase needs to be changed and linked to documentation on why Travis works this way. @BanzaiMan, I believe only Travis developers know this.

**Comment by edmorley** [comment]
Ah thank you I hadn't seen that repo - opened travis-ci/docs-travis-ci-com#214
