### ISSUE TITLE
No output in the last 10 minutes issue

### ISSUE THREAD

**Issue by yarden** [travis-ci/travis-ci#3358]
Hi,

I'm new to Travis CI and having a similar issue to the one described here before, where the build terminates because no output was received in last 10 minutes. My package installs fine normally using `pip install .` but that command apparently creates a situation, in installing my package's Python dependencies (`scipy`, I believe), where no output is written for more than 10 minutes and travis kills the build. The output is here: https://travis-ci.org/yarden/MISO/jobs/53883801

The relevant bit is at the end:

```
    /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      writer = ep.load(installer=installer)
  Running setup.py install for scipy
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

It seems like the solution might be to break up the `pip install .` into separate `pip` calls, with `travis_wait` for dependency that might have installation processes that don't produce output for more than 10 minutes. Is that the right approach? It doesn't seem like an ideal solution.

When I try this, it appears to works for Python 2.7 (https://travis-ci.org/yarden/MISO/jobs/53886605) but not for Python 2.6 (https://travis-ci.org/yarden/MISO/jobs/53886604). To summarize, I took my previous build file and changed `pip install .` to: 

```
install:
  - travis_wait pip install scipy
  - travis_wait pip install pysam
  - pip install .
```

since I thought the packages `scipy` and `pysam` might be the culprits. Any thoughts on how to fix this?

**Comment by jackiekazil** [comment]
I am having a similar problem. Thank you for tip, but yeah, this seems like an issue to me.

**Comment by Glavin001** [comment]
I am also experiencing this issue. It was recommended at http://stackoverflow.com/a/28833319/2578205 to use `travis_wait`. See http://docs.travis-ci.com/user/build-timeouts/ for more details. I am giving it a try now.

**Comment by kenorb** [comment]
Related: #5201

**Comment by pcantrell** [comment]
Getting it here too: builds failing at different times with different errors, but all related to the build timing out. https://travis-ci.org/bustoutsolutions/siesta/builds/130948257

The build is _incredibly_ slow to start, and to compile, and to run. It looks like Travis is currently overloaded, and is timing itself out when in the overloaded state.

**Comment by BanzaiMan** [comment]
@pcantrell Yours is an OS X job, so quite possibly a different issue. The delay in start is due to the capacity issue on OS X builds. Sorry about that.

**Comment by winsvega** [comment]
@pcantrell semms like you are right. the issue is in travis

**Comment by lypht** [comment]
Also experiencing the same, but at random lines within `before_script`.  We are currently in a trial _Pro_ version.  Are there documented steps for remedy?

**Comment by BanzaiMan** [comment]
@lypht Sorry for the issue. The cause for your particular issue is hard to diagnose from here. Please send email to support@travis-ci.com with details (which repo you're having problems with).

**Comment by lypht** [comment]
@BanzaiMan Thanks.  Email sent.

**Comment by servatti** [comment]
Here is the same of @pcantrell. I'm trying to test a very simple iOS app and I'm getting the error.

**Comment by anas10** [comment]
Same here today with a simple iOS project

**Comment by p2** [comment]
I am also still getting this issue [an OAuth2 OS X framework](https://github.com/p2/OAuth2) and this config file:

    language:      objective-c   # well "swift" actually
    osx_image:     xcode7.3
    xcode_project: OAuth2.xcodeproj
    xcode_scheme:  OAuth2OSX
    xcode_sdk:     macosx10.11

**Comment by abitrolly** [comment]
`travis_wait` is the way to fix that - https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received This issue can be closed probably.

**Comment by BanzaiMan** [comment]
Closing this now, as it's become stale.
