### ISSUE TITLE
before_script is run before 

### ISSUE THREAD

**Issue by gavinwahl** [travis-ci/travis-ci#3359]
I recently started seeing this error from using psql in my before_script <https://travis-ci.org/fusionbox/django-widgy/jobs/53861004>:

```
$ psql -c 'create database widgy;' -U postgres
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

This just started (I've been using this same .travis.yml for years). I assume that the before_script is getting run before the environment is fully initialized.

If I can wager a guess, did the worker environment recently switch from sysv init to systemd? Seems like systemd's lazy behavior could cause the init process to return before it's completely finished.

Can you wait until the environment is ready before starting the before_script?

Other people are having this issue as well; See https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/458

**Comment by joshk** [comment]
Hi @gavinwahl 

Is this a consistent error? This is the first report of such problems with Postgres.

**Comment by gavinwahl** [comment]
No, it happens maybe once ever 50 builds

**Comment by joshk** [comment]
I've sent you a PR which runs builds on our new setup.

I highly suggest merging it in if it passes :)

**Comment by roidrage** [comment]
@gavinwahl Are you still experiencing these issues?

**Comment by joepvd** [comment]
Closing as no feedback was received from reporter.

**Comment by j0nimost** [comment]
> Closing as no feedback was received from reporter.
I have this issue when using version Postgresql version 10.6.
