### ISSUE TITLE
APT whitelist request for ghdl (from ppa)

### ISSUE THREAD

**Issue by jck** [travis-ci/travis-ci#3361]
https://launchpad.net/~pgavin/+archive/ubuntu/ghdl

**Comment by BanzaiMan** [comment]
Sorry, we cannot accommodate custom PPAs at the moment.

**Comment by jck** [comment]
@meatballhat I noticed you added this source to the apt-source-whitelist. Please add it the package(ghdl) to the whitelist too :)

**Comment by meatballhat** [comment]
@jck sorry for delay!

**Comment by jck** [comment]
Thanks!
