### ISSUE TITLE
BrowserStack integration

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#3362]
BrowserStack is a service like Sauce Labs that allows you to run tests in different browsers.
While it has [instructions](https://www.browserstack.com/automate/continuous-integration#ci-travis) on how to set it up to work with travis it would be nice if we were able to simply specify some arguments in the addons section much like how the Sauce Labs integration work.

**Comment by joshk** [comment]
This integration would be great and we would be happy to work with someone on a PR for travis-build.

**Comment by thedrow** [comment]
I think that pinging them would be best.

**Comment by joshk** [comment]
Probably would be. Please feel free to put us in contact with them. We haven't any any specific request for BrowserStack support, but happy to help add this support if we can find someone to help lead the development.

**Comment by roidrage** [comment]
Thank you for your suggestion, but I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
