### ISSUE TITLE
AppThwack integration

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#3363]
[AppThwack](https://www.appthwack.com) is a service that allows you to run tests on *real* mobile devices.
It is possible to use their HTTP API or thier one of their clients but it would be nice if we could just configure AppThwack through the addons section.

**Comment by joshk** [comment]
Happy to add this, would you be interested in helping with a PR to travis-build?

**Comment by thedrow** [comment]
We're not using them yet so not for now. I figured it might be useful for others anyway.
I think that pinging @appthwack might expedite this.

**Comment by joshk** [comment]
Please feel free to put us in contact with them.

As we haven't had requests to add this support yet, we will wait for someone to help add this support to travis-build.

**Comment by roidrage** [comment]
Thank you for your suggestion, but I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
