### ISSUE TITLE
Oracle database support

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#3364]
We have a component in our system that inserts data to an Oracle database and naturally we need to run tests to ensure that the component works.
The Travis CI environment has two things missing:
1) The client library.
2) The ability to create an Oracle database instance during the CI process.

It is possible to install the client library using the [following script](https://github.com/eikonomega/oracle_instant_client_for_ubuntu_64bit) but it requires sudo access so the container based infrastructure won't work unless we whitelist all the dependencies that it installs and there are quite a few of them.
The linked script also only works on 64bit machines if that's an issue.
The client library can only be installed if you have the source file (rpm) and a license as far as I know.

Since the container based infrastructure is hosted on AWS we could utilize RDS to create and destroy and Oracle instance.

I think that this feature could proove useful to Pro users, ORM and oracle database driver developers but I'm not sure how it would work for you guys if you'll allow this on the org environment.
In any case, I need it as a Pro user.

**Comment by theory** [comment]
I would make use of an Oracle instance for fuller coverage of the [Sqitch tests](https://travis-ci.org/theory/sqitch). [Vertica](https://my.vertica.com), too.

**Comment by tgulacsi** [comment]
The hard job is not the server:
    docker pull wnameless/oracle-xe-11g && docker run -d -p 49161:1521 wnameless/oracle-xe-11g

It is the client libs - you can't redistribute them, AFAIK...

**Comment by theory** [comment]
Yeah. Maybe Oracle would be willing to let them be used on Travis hosts for testing only? I don't know whom to talk to, alas.

**Comment by tgulacsi** [comment]
Oracle is not that open, I'm afraid.

I've "solved" this by using a closed s3 bucket, with keys encrypted by the travis gem.
This way I can say: "I've accepted the license aggreement when downloaded the libs from Oracle's home page, and nobody else can access these."

My .travis.yml: https://github.com/go-goracle/goracle/blob/v1/.travis.yml

**Comment by theory** [comment]
Looks like @cbandy has a [possible workaround](/cbandy/travis-oracle).

**Comment by roidrage** [comment]
Thank you for your suggestion, but I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by ericminio** [comment]
Thx to @tgulacsi to suggest the use of wnameless/oracle-xe-11g for the server. The server also comes with the client libraries. The fun game is to make them available from outside the container to run code that lies outside the container.

Here is a working example, in case it is useful to someone:
https://travis-ci.org/ericminio/learning-oracle/builds/487723233

**Comment by theory** [comment]
> Here is a working example, in case it is useful to someone:
> https://travis-ci.org/ericminio/learning-oracle/builds/487723233

Looks like your Docker image was built from `wnameless/oracle-xe-11g`, but I don't see it on Docker Hub anywhere. FWOFW, from [the README](/wnameless/docker-oracle-xe-11g#readme), it looks like it was taken down by a DMCA request.
