### ISSUE TITLE
Default ImageMagick is missing PNG support

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/travis-ci#3365]

**Comment by BanzaiMan** [comment]
Currently, we rely on http://packages.ubuntu.com/precise/imagemagick to provide ImageMagick binary. If it's not supported there, it's not there.

I'm happy to work with anyone who wants to create a cookbook. (A quick Google search reveals a few abandoned efforts to do so.)

**Comment by BanzaiMan** [comment]
Closing as it's become stale.
