### ISSUE TITLE
Multi-language support or Android project as subproject

### ISSUE THREAD

**Issue by karussell** [travis-ci/travis-ci#3366]
I'm not sure if that is already possible, but for [graphhopper](https://github.com/graphhopper/graphhopper/) (Java) we currently build on travis ci without the android demo app which is located in the subfolder '[android/app](https://github.com/graphhopper/graphhopper/tree/master/android/app)'. 

Now I saw that Android is possible, but is it possible in a subfolder or could I somehow still use `language: java` then use the script functionality for Android and before download the Android dependencies via `android: xy`?

I've searched a bit the mailing list and found [this multi language discussion](https://groups.google.com/forum/#!searchin/travis-ci/android$20/travis-ci/3pzCgvxWZAo/LrSckrasFnkJ) including a workaround. Should I use this workaround or is there an official solution already?

**Comment by BanzaiMan** [comment]
The `language` value is fixed for each build. Mathias's workaround is reasonable.

For your particular use case, though, you can choose `language: android`, since it has all the parts you need for the Java tests. (The Android image is missing Leiningen and Scala parts.)

**Comment by karussell** [comment]
Thanks, I'll try!
