### ISSUE TITLE
Cache upload timeout should fail silently (and not affect build result)

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3367]
```
changes detected, packing new archive
uploading archive


No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

When cache upload fails to print to STDOUT, it should fail silently.

**Comment by joshk** [comment]
We actually don't have a way to know if it is caching, so we can't fail it silently, as the log 10min check happens in the worker.

I would suggest wrapping the upload command with something which outputs dots while it uploads, thus bypassing this restriction.

This would be a temp solution while we rework caching.

Also, how big is the cache being uploaded?

**Comment by BanzaiMan** [comment]
The one I saw was about 220 MB, so 10 minutes should be plenty of time to execute.

**Comment by BanzaiMan** [comment]
Actually a duplicate of #2214.
