### ISSUE TITLE
Allow use of `apt-get` on container-based infrastructure.

### ISSUE THREAD

**Issue by theory** [travis-ci/travis-ci#3369]
It'd be great to be able to install dependencies via `apt-get` when using Travis's new [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) (i.e., `sudo: false`). Or perhaps offer some other way to define dependencies to install?

**Comment by BanzaiMan** [comment]
At the moment, such dependencies are managed through https://github.com/travis-ci/apt-package-whitelist. If you have packages you need, please make a request here according to the procedure described.

It is meant to be a temporary measure; we want to allow `sudo` on containers eventually. Until then, this is what we have.

I'm closing this now. Thank you.

**Comment by theory** [comment]
Thanks @BanzaiMan. I'm not sure how to install whitelisted packages, though. If I wanted graphviz, for example (which appears not the list), what do I put into my `.travis.yml`?

**Comment by theory** [comment]
Never mind, found [this page](http://docs.travis-ci.com/user/apt-packages/). Thanks!

**Comment by baztian** [comment]
The page is now located here: http://docs.travis-ci.com/user/apt/
