### ISSUE TITLE
travis-ci not running test jobs from after repo migration to github organization 

### ISSUE THREAD

**Issue by shadowbq** [travis-ci/travis-ci#3370]
## travis-ci is not creating the first test run from the organization repo from which I own and have rights.

I am a 'owner' for the packets-at-rest github org repository.

Using : https://travis-ci.org/profile/shadowbq

1. I can click on `packets-at-rest` on the left menu bar

  - https://travis-ci.org/profile/packets-at-rest

2. I want to add the repo packets-at-rest/packets-at-rest 

   - I can click sync and the repository is there..

  - I change `packets-at-rest` from *off* to *on* 

3. Push to the repo on github https://github.com/packets-at-rest/packets-at-rest

    - See no change.. and `packets-at-rest` is now switched back to off on travis-ci.

    - I can't get the repository`https://travis-ci.org/packets-at-rest/packets-at-rest` to show in `https://travis-ci.org/repositories`

**Comment by shadowbq** [comment]
The `Services / Manage Travis CI` webhooks on the GIT HUB repo for the Organization is not being set.

https://github.com/packets-at-rest/packets-at-rest/settings/hooks/

Traditionally the webhooks are installed from https://travis-ci.org/profile/packets-at-rest to manage your hooks.

**Comment by shadowbq** [comment]
Manually adding the webhook to the GITHUB page fixed the missing repo, then re-enabling the packets-at-rest from off to on seems to fix it.

**Comment by BanzaiMan** [comment]
Sorry to hear about the problem you had. I am not quite sure how it happened, though. Regardless, I'm happy to hear that it's working for you now.

Is there anything else for us to do?

**Comment by shadowbq** [comment]
Was just wondering if other people had hook issues with Organization repos?

**Comment by joshk** [comment]
We are seeing plenty of issues, but they are sadly out of control as they are related to GitHubs 3rd Party Auth.
