### ISSUE TITLE
Xcode 6.2 & iOS SDK 8.2 support

### ISSUE THREAD

**Issue by peterprokop** [travis-ci/travis-ci#3373]
Xcode 6.2 & iOS SDK 8.2 are released for about a week now - it would be nice to have support of the latest stable SDK

**Comment by mzsanford** [comment]
Note that this is required for testing Apple Watch apps. The error in the mean time is:

```
target specifies product type 'com.apple.product-type.application.watchapp', but there's no such product type for the 'iphonesimulator' platform
```

*mostly included here for people searching Github*

**Comment by teknolog2000** [comment]
Yes we need this too ASAP.

**Comment by 1ec5** [comment]
See also #3216.

**Comment by nlutsenko-fb** [comment]
+1 Would be fabulous to have it. Also - it looks like there are a little bit of differences in Swift conversion, specifically for UIKit that were introduced with Xcode 6.2.

**Comment by felipesabino** [comment]
I have been told that while it is not publicly available, anyone interested in this XCode version should email support@travis-ci.com and they will give you info on the Beta and enable it for the repositories you need - https://twitter.com/j2h/status/582648430104735744

_also mostly included here for people searching Github_

**Comment by BanzaiMan** [comment]
FYI, we have discovered serious issues with the current Xcode beta testing, and we've decided to halt it until they are addressed. Thank you.

**Comment by nlutsenko-fb** [comment]
FWIW, Xcode 6.2 is not in beta ;)

Thanks for letting us know, though... 
It's good to have some timeline on this :D

**Comment by sobri909** [comment]
Apple Watch apps require at least Xcode 6.2. So this is a fairly significant blocker.

**Comment by intelliot** [comment]
Same problem here: `target specifies product type 'com.apple.product-type.application.watchapp', but there's no such product type for the 'iphonesimulator' platform`

Additionally, I'm seeing: `iOS deployment target '8.2' for architecture 'x86_64' and variant 'normal' is greater than the maximum value '8.1.99' for the Simulator - iOS 8.1 SDK.`

**Comment by BanzaiMan** [comment]
We are working to bring this support. Until further update (hopefully very soon!), I'm locking this issue.

**Comment by BanzaiMan** [comment]
At the moment, we do not have Xcode 6.2. But if the code is compatible with 6.3.x, you can use:

```yaml
osx_image: beta-xcode6.3
```

to use that. http://blog.travis-ci.com/2015-05-26-xcode-63-beta-general-availability/

Thanks.
