### ISSUE TITLE
Support Android / Arm

### ISSUE THREAD

**Issue by carllerche** [travis-ci/travis-ci#3376]
I maintain a number of Rust projects. Rust supports Android / ARM processors as a compilation target. It would be nice to be able to include such an environment in CI runs.

For example, the following project provides bindings to OS APIs https://github.com/carllerche/nix-rust, and this one a non-blocking IO event loop: https://github.com/carllerche/mio

Both theoretically support being run on Android / ARM processors but running the tests as part of the CI run would be nice :smile:

**Comment by meatballhat** [comment]
Paging @tianon :smiley_cat:

**Comment by moul** [comment]
(subscribing)
I'm working on this and can provide ARM servers from labs.online.net

**Comment by meatballhat** [comment]
@moul :+1: why thank you!  In all likelihood we'll be implementing this as a backend over here: https://github.com/travis-ci/worker/tree/master/lib/backend.  Any help you can offer with regard to how best to use the OnlineLabs API is greatly appreciated :smiley:.

/cc @henrikhodne

**Comment by moul** [comment]
@meatballhat I'm building an image with [travis-ci/worker](https://github.com/travis-ci/worker) in.

Repository: [online-labs/image-service-travis](https://github.com/online-labs/image-service-travis)

For now, it's only for testing, but we can imagine to use this base to build the official travis-ci image on Online Labs

**Comment by meatballhat** [comment]
@moul thanks so much for your work in this!  I should clarify that there are at least two components needed.

One is [travis-ci/worker](https://github.com/travis-ci/worker), which ideally runs in our Amazon VPC and talks to an API (such as Online Labs).  We already have some provisioning bits in place for this, thankfully, although it is lacking a backend for the Online Labs API.

The other is to have at least one image available for provisioning within a given cloud that includes the bare minimum tooling to be able to run a script generated by [travis-build](https://github.com/travis-ci/travis-build).  As of today, this means `bash` and a few other shell basics.  For all other clouds, we're currently using chef-solo in combination with either [travis-images](https://github.com/travis-ci/travis-images) or packer to perform this provisioning, which is part of the reason why I tackled [packer-builder-onlinelabs](https://github.com/meatballhat/packer-builder-onlinelabs).  We're hoping to standardize on packer, fwiw.

**Comment by moul** [comment]
Ok, got it; Don't worry, I will keep this image for my tests :)
My goal is to be sure you have everything needed

I will try to generate some scripts using [travis-build](https://github.com/travis-ci/travis-build/) and get as much needed binaries as possible for the different languages ([travis-build/lib/travis/build/script](https://github.com/travis-ci/travis-build/tree/master/lib/travis/build/script)) in a single image

We will probably have some limitations on 32bits armhf and you will probably need to create a matrix of available tests per architecture

**Comment by meatballhat** [comment]
Even if you're able to get the image capable of running a script from
`language: generic`, this is a great first step.  There is a `travis
compile ` command available that may come in handy, although I'm told the
results are highly variable.  We can also generate such a script via
internal Travis admin tools if necessary.

**Comment by moul** [comment]
I'm interested to get those generated scripts if you can
Thanks

**Comment by meatballhat** [comment]
@moul here's a stripped down example with `echo` for both the `install` and `script` steps: https://gist.github.com/meatballhat/dd3b723a25082aea0586

**Comment by moul** [comment]
Perfect, I will give a try, is the `/etc/profile` custom and could block my tests ?

**Comment by meatballhat** [comment]
@moul `/etc/profile` itself is pretty stock:

``` bash
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "$PS1" ]; then
  if [ "$BASH" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

# The default umask is now handled by pam_umask.
# See pam_umask(8) and /etc/login.defs.

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
```

It's the contents of `/etc/profile.d/*.sh` that get interesting :smiley:

``` bash
root@c5bf9b01f88e:/# ls -l /etc/profile.d
total 40
-rwxr-xr-x 1 root   root     42 Feb  5 14:46 clang.sh
-rw-r--r-- 1 root   root     44 Feb  5 14:51 java_home.sh
-rwxr-xr-x 1 travis travis  166 Feb  5 15:43 load_jdk_switcher.sh
-rwxr-xr-x 1 root   root     44 Feb  5 14:52 maven.sh
-rwxr-xr-x 1 travis travis   91 Feb  5 14:54 nvm.sh
-rw-r--r-- 1 root   root     36 Feb  5 15:08 phantomjs.sh
-rwxr-xr-x 1 travis travis   75 Feb  5 14:53 rvm.sh
-rwxr-xr-x 1 travis travis 1196 Feb  5 14:44 travis_environment.sh
-rw-r--r-- 1 root   root     26 Feb  5 15:40 travis.sh
-rwxr-xr-x 1 root   root    328 Feb  5 14:46 Z90-gimme.sh
```

All of these are written by cookbooks in the [travis-cookbooks](https://github.com/travis-ci/travis-cookbooks) repo under the [ci environment tree](https://github.com/travis-ci/travis-cookbooks/tree/master/ci_environment).

**Comment by shouze** [comment]
@meatballhat well, when can we be able to make travis builds on arm machines ?! Thx @moul for this repo, can't wait!

**Comment by bobvanderlinden** [comment]
For anyone interested, it's possible to build on emulated ARM through Travis using `qemu-user-static` and `binfmt_misc`. [Here is an example](https://github.com/bobvanderlinden/machinekit/commit/6031d91c9bd04b7b970cf5b599da3c4a10eb1869). Basically, binfmt_misc is configured to use `/usr/local/bin/qemu-arm-static` whenever the kernel find a binary that is ARM-based. Then a ARM-based docker image is used, like `armbuild/debian:wheezy` ([link](https://hub.docker.com/r/armbuild/debian/)). This docker image is a minimal version of ARM debian and (in addition) has added `/usr/local/bin/qemu-arm-static`. Everything that's being run inside of the container is being emulated.

Do note though that it is very slow. For our purposes it resulted in > 50m, so a timeout. For other purposes I can imagine it being sufficient.

Hardware-based ARM Travis workers would be ideal. Is there some way to host your own worker that travis-ci.org can use?

**Comment by larsbrinkhoff** [comment]
:+1: For ARM builds.

**Comment by moul** [comment]
Hello, I'm the author of the `armbuild/debian:wheezy` image quoted by @bobvanderlinden,

I moved my work from `armbuild/*` to `multiarch/*` ([organization](https://github.com/multiarch)), which is basically the same but for any targets:

* https://hub.docker.com/r/multiarch/debian-debootstrap/
  * supported archs: `armhf`, `armel`, `arm64`, `amd64`, `mips`, `mipsel`, `powerpc`, `i386`, `s390x`
* https://hub.docker.com/r/multiarch/ubuntu-debootstrap/
* https://hub.docker.com/r/multiarch/ubuntu-core/

I also created a `binfmt-support` configurator as a Docker image ([link](https://hub.docker.com/r/multiarch/qemu-user-static/))

So if your kernel supports the `binfmt` feature, you can on a fresh host start to use cross-platform Docker images with:

```console
$ docker run --rm --privileged multiarch/qemu-user-static:register
$ docker run -it --rm multiarch/debian-debootstrap:armhf-jessie
root@88a6ead2fd63:/# uname -a
Linux 88a6ead2fd63 4.1.13-boot2docker #1 SMP Fri Nov 20 19:05:50 UTC 2015 armv7l GNU/Linux
root@88a6ead2fd63:/#
```

As it only uses `Docker` client, it works out of the box with *local* and *remote* Docker servers (tested on `boot2docker` and `swarm`-based remote Docker cluster)

**Comment by bcecchinato** [comment]
+1 for ARM builds :)

**Comment by meatballhat** [comment]
I'm closing this out based on what appears to be a reasonable workaround.  Please yell if you think otherwise! :heart:

**Comment by dlech** [comment]
Although qemu does work about 80-90% of the time in my experience, it would still be nice to be able to build on real ARM hardware for the times when qemu is not good enough.

**Comment by giggio** [comment]
We can't use qemu to run Go based programs. See https://github.com/golang/go/issues/13024 for more information.
I agree we should have support for ARM on Travis.

**Comment by swarren** [comment]
FWIW, I wanted to use qemu-aarch64-static to build the Arduino IDE (and its many dependencies) for AArch64 but found that the emulation wasn't sufficient and had to switch to real HW. So, the workaround described here will work in many cases, sure, but it certainly doesn't work for all cases. True AArch64 (64-bit ARM) hardware would be quite useful.

**Comment by projectextremum** [comment]
So, what about retrieving relocatable cross-toolchain binaries using `curl`?

Also, `proot` + a very small rootfs image of debian / ubuntu + cross toolchain should work as far as I can think. `proot` project is unmaintained though.

**Comment by junaruga** [comment]
Sorry to share this on `travis-ci` page.
As a CI supporting ARM, Shippable CI. [1]
That's free for public project.
In my experience, Shippable user experience can be more improved in the future.
Here is my experimental page for that. [2]
There is Works on ARM service. [3] Though I have not used it.

[1] https://app.shippable.com/
[2] https://github.com/junaruga/ci-multi-arch-test
[3] https://www.worksonarm.com/cluster/

**Comment by michal-at-travisci** [comment]
I've just stumbled upon this one accidentally while googling - just leaving information, that Travis CI can now build on Linux also for arm64, s390x and ppc64le if it helps to create your binaries: https://docs.travis-ci.com/user/multi-cpu-architectures/
