### ISSUE TITLE
Travis killing javadocs task

### ISSUE THREAD

**Issue by gabizou** [travis-ci/travis-ci#3377]
Basically, a few commits back on a rather important PR for a group project, Travis started killing the build tasks on javadoc creation. When I tried to debug, Travis produces some odd exceptions about having to kill the task, but no reason _why_ the task is being killed.

Link to relative builds; https://travis-ci.org/SpongePowered/SpongeAPI/builds/54329825

Edit: I've been testing with various other branches and it seems that Travis is just killing all builds, regardless of the branch:

https://travis-ci.org/SpongePowered/SpongeAPI/jobs/54333291 The only difference between that checked out branch and master is [this commit](https://github.com/SpongePowered/SpongeAPI/commit/11c9fa97ab14381e65df4ebb39dc900b0c3d6bc4).

What is going on with Travis and Gradle?

**Comment by gabizou** [comment]
After further testing, it seems like the Docker containers are having issues with our builds. A workaround the problem is removing `sudo: false` and our builds work again.

**Comment by BanzaiMan** [comment]
See also https://github.com/travis-ci/travis-ci/issues/3396

**Comment by BanzaiMan** [comment]
While we are unable to spin up a debug VM, you might be able to reproduce the issue on the Docker image we use.

https://quay.io/repository/travisci/travis-jvm The image with the `latest` tag is one used.

**Comment by gabizou** [comment]
Thanks @BanzaiMan, it does seem that one of our developers has found a workaround to some tasks consuming too much memory, causing the build to fail (as to why it works normally on JDK8, I don't know).

https://github.com/SpongePowered/SpongeAPI/compare/master...Minecrell:Tmp

While it seems that those specific changes build with travis, I don't know whether any future changes to the containers will affect the builds again.

**Comment by BanzaiMan** [comment]
Closing.
