### ISSUE TITLE
Restart button does not work on IE11

### ISSUE THREAD

**Issue by am11** [travis-ci/travis-ci#3378]
*(seems like a [browser sniffing](https://developer.mozilla.org/en-US/docs/Web_development/Writing_forward-compatible_websites#Sniffing) case)*

In IE11, clicking on restart button does not restart the build job:

![TravisCI on IE11](https://cloud.githubusercontent.com/assets/3840695/6652850/2db5bed6-ca86-11e4-8173-45c963df02da.png)

**Comment by akoeplinger** [comment]
To add some more insight, if you look at the request that gets sent:

![image](https://cloud.githubusercontent.com/assets/1376924/6758401/2054a1d8-cf38-11e4-99fc-4eccbe741771.png)

The JSON just contains `undefined`, so it's likely some javascript value that's wrong.

**Comment by joshk** [comment]
@drogus can you please look into this?

**Comment by joshk** [comment]
Thanks for reporting this, I have escalated it within the team.

**Comment by akoeplinger** [comment]
@joshk any update on this? It still repros even in Microsoft Edge.

**Comment by joshk** [comment]
Our web team are looking into it, I hope to have some more info tomorrow.

**Comment by clekstro** [comment]
I'm able to restart builds currently within both IE11 and Edge.  @am11 @akoeplinger is this still an issue or can it be closed?

**Comment by am11** [comment]
@clekstro, just tested and this is indeed fixed. Many thanks :tada:
