### ISSUE TITLE
UTF-8 characters in comments .travis.yml lead to parse erros

### ISSUE THREAD

**Issue by stapelberg** [travis-ci/travis-ci#3380]
This .travis.yml fails: https://raw.githubusercontent.com/robustirc/robustirc/384f0e855635e7da90800f4d080aa569c63cd5e7/.travis.yml

The message I’m getting is 
![image](https://cloud.githubusercontent.com/assets/55506/6653989/22c52c74-caa8-11e4-8416-a986bbccfdba.png)

Removing the quotation marks works around the issue (see https://github.com/robustirc/robustirc/commit/e2f22973e21ce002f86124d0c7f0a50400c69fd5), but I think I shouldn’t have to :).

**Comment by BanzaiMan** [comment]
Sorry for the delay. Is this still an issue? If so, do you have a more recent example to show the problem?

**Comment by stapelberg** [comment]
Can’t reproduce this issue anymore. Tried with https://travis-ci.org/stapelberg/i3/builds/194740764
