### ISSUE TITLE
Unable to enable travis for plv8/plv8js

### ISSUE THREAD

**Issue by clkao** [travis-ci/travis-ci#3381]
Here's the PUT request returning with 500:
![2015-03-15 2 33 51](https://cloud.githubusercontent.com/assets/69736/6654949/9fdf4816-cb20-11e4-9f30-550351bfed3c.png)

**Comment by BanzaiMan** [comment]
Does the plv8 organization has trusted-application feature enabled? If so, is Travis CI authorized to access the org's data?

**Comment by clkao** [comment]
I see, the organization was created after I granted travis-ci access.  Perhaps some error message would be helpful! ;)

**Comment by BanzaiMan** [comment]
I don't think GitHub exposes the reason for 404, so I don't think there is much we can do beyond showing  a possible cause. This, of course, is better than no indication at all.

**Comment by roidrage** [comment]
@clkao Is this still an issue?

**Comment by clkao** [comment]
It's no longer an issue for the repo.  So this issue is more about having some useful error information when you have repo in new organization after you granted access to travis.

**Comment by joshk** [comment]
Thank you for the feedback.

I'm going to close this issue for now as we have made some updates and improvements to this page recently.
