### ISSUE TITLE
Unable to scroll down in Travis-CI log

### ISSUE THREAD

**Issue by yarden** [travis-ci/travis-ci#3382]
I have a build that is failing here (https://travis-ci.org/yarden/MISO/jobs/54042023) and I don't know why. The build output is very long and when I try to scroll down to the bottom to see the error, the output is truncated (the size of the page changes dynamically) and I can never scroll all the way down to see what the error was. I tried this on Mac OS X on both Chrome (Version 40.0.2214.111 (64-bit)) and Safari. I am using OS X 10.9.4. Any idea what is wrong here? It seems like some sort of javascript bug in the web pages produced by Travis-CI. Is there a different way to access the build log so I can see the error?

Thanks!

**Comment by BanzaiMan** [comment]
I loaded the page in question and observed the strange problem you are describing.
![job__7_1_-_yarden_miso_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/6744251/6c282a8c-ce7d-11e4-9cd7-ff5bfe274f4e.png)

However, when I waited long enough (say 10 seconds), the entire log (well, the first 10K lines) showed up. To see the rest, though, you'll have to download the logs, from the top of the page.

**Comment by drogus** [comment]
This should be fixed now, closing.
