### ISSUE TITLE
APT whitelist request for firebird2.5-superclassic

### ISSUE THREAD

**Issue by theory** [travis-ci/travis-ci#3384]
And `firebird2.5-dev`. You'll want to add it to your [databases list](http://docs.travis-ci.com/user/database-setup/), too. Not sure if it needs special permissions to start, but I currently install and configure it on a regular Travis box like so:

    before_install:
      - sudo apt-get update -qq
      - sudo apt-get install -qq firebird2.5-superclassic firebird2.5-dev
      - sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
      - cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
      - sudo service firebird2.5-superclassic start

**Comment by meatballhat** [comment]
The whitelisting is done, so I've opened a separate issue to track implementation of the service provider.

**Comment by theory** [comment]
So, does that mean it's usable now?
