### ISSUE TITLE
Build matrix UI is now very confusing

### ISSUE THREAD

**Issue by graemerocher** [travis-ci/travis-ci#3386]
Previously prior to the recent UI changes we could clearly see which build was which for our build matrix defined at:

https://github.com/grails/grails-data-mapping/blob/master/.travis.yml#L26

Now it seems to output the environment and JDK version is displayed but nothing about the matrix:

https://travis-ci.org/grails/grails-data-mapping/builds/54554749

So it is impossible to tell which of the matrix is which unless I am missing something.

**Comment by joshk** [comment]
Thanks for creating the issue, and for the great feedback.

I see the issue with the UI and we will get this fixed tomorrow.

We are also working on some updates to our updates from the great feedback we have received.

**Comment by marutosi** [comment]
Same.
https://travis-ci.org/marutosi/redmine/builds/54651138
![screenshot-marutosi-redmine - travis ci - mozilla firefox](https://cloud.githubusercontent.com/assets/200784/6679255/ae349ccc-cc88-11e4-8423-6e03197b89e3.png)

**Comment by BanzaiMan** [comment]
We are working on improvements. Thanks. <3

**Comment by BanzaiMan** [comment]
We've made some changes to the matrix display, and I'm closing this.
