### ISSUE TITLE
download.elasticsearch.org: ERROR: no certificate subject alternative name matches

### ISSUE THREAD

**Issue by groovecoder** [travis-ci/travis-ci#3394]
We have a travis install script that uses `wget` to get the elasticsearch `.deb` from download.elasticsearch.org:

https://github.com/mozilla/kuma/blob/3ae992e8f1552c227b26aa02954035da8014043e/scripts/travis-install#L18

But we just started to get this error today from [our Travis builds](https://travis-ci.org/mozilla/kuma/jobs/54732362).
```
+wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.7.deb
--2015-03-17 15:20:49--  https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.7.deb
Resolving download.elasticsearch.org (download.elasticsearch.org)... 2406:da00:ff00::36f3:4d9e, 2406:da00:ff00::36e1:85c3, 2406:da00:ff00::36e1:40a1, ...
Connecting to download.elasticsearch.org (download.elasticsearch.org)|2406:da00:ff00::36f3:4d9e|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name `download.elasticsearch.org'.
To connect to download.elasticsearch.org insecurely, use `--no-check-certificate'.
```
A local `wget` doesn't get the error.

(Also filed https://github.com/elastic/elasticsearch/issues/10129 on the elasticsearch side)

**Comment by rkh** [comment]
Hi @groovecoder, thanks for the report.

elasticsearch.org has updated their SSL certificate to one using SNI. Unfortunately, wget 1.13 (the latest version offered by Ubuntu) can't handle that. We are looking into compiling wget 1.14 from source so we can roll out an update to fix this.

In the mean time replacing `wget` with `curl -O` should fix this issue for you.

**Comment by BanzaiMan** [comment]
The next build environment update will include wget 1.16.3.
