### ISSUE TITLE
Feature: cancel builds from "build history" page

### ISSUE THREAD

**Issue by headius** [travis-ci/travis-ci#3395]
It would be supergreat if we could cancel builds from the build history page. Whenever I need to kill a bunch of bad builds, it's much slower having to click through each.

**Comment by joshk** [comment]
We have this in the backlog and will add it shortly, I expect a week or two.

**Comment by headius** [comment]
Excellent! :+1:

**Comment by carlad** [comment]
Here is a similar request from Jan 4 2016 https://github.com/travis-ci/travis-ci/issues/5402

**Comment by carlad** [comment]
Another user, @Jsquyres has also asked for a similar feature through HelpScout

**Comment by jsquyres** [comment]
I confirm: yes, I definitely asked for this.  I agree with @headius -- this would be a very useful feature to have.  :smile:

**Comment by BanzaiMan** [comment]
We shipped this a few days ago.
