### ISSUE TITLE
APT whitelist request for libgif-dev

### ISSUE THREAD

**Issue by vr2262** [travis-ci/travis-ci#3397]
Required for the node-canvas package.

**Comment by uhop** [comment]
It looks like the problem has surfaced again --- my project started to fail on installing dependencies (see https://travis-ci.org/uhop/grunt-tight-sprite/builds/98043474). You can check that the previous builds installed dependencies properly.

**Comment by BanzaiMan** [comment]
@uhop Your issue is entirely different; since you're not running on containers, whitelist does not apply.

Your issue is probably #5221, which should be fixed by running `sudo apt-get update` before `sudo apt-get install`.

**Comment by uhop** [comment]
@BanzaiMan Thank you! I'll try your suggestion, and report back if it failed for me.
