### ISSUE TITLE
APT whitelist request for chrpath

### ISSUE THREAD

**Issue by rossburton** [travis-ci/travis-ci#3399]
Our build needs chrpath to modify RPATHs in binaries that we've built, please add this to the whitelist.

**Comment by meatballhat** [comment]
@rossburton Will you also need sudo privileges to use `chrpath` on system binaries, or is this strictly for your own binaries?

**Comment by rossburton** [comment]
This is strictly for binaries that I've built.

Cheers
Ross

**Comment by meatballhat** [comment]
@rossburton excellent, thanks! :thumbsup:
