### ISSUE TITLE
UI is broken on CentOS 6 Firefox 31.5.0

### ISSUE THREAD

**Issue by marutosi** [travis-ci/travis-ci#3402]
https://travis-ci.org/marutosi/openproject/builds/54864581

<pre>
$ LANG=C rpm -qi firefox
Name        : firefox                      Relocations: (not relocatable)
Version     : 31.5.0                            Vendor: CentOS
Release     : 1.el6.centos                  Build Date: Wed Feb 25 10:41:01 2015
Install Date: Fri Mar 13 16:44:44 2015         Build Host: c6b9.bsys.dev.centos.org
Group       : Applications/Internet         Source RPM: firefox-31.5.0-1.el6.centos.src.rpm
Size        : 113062147                        License: MPLv1.1 or GPLv2+ or LGPLv2+
Signature   : RSA/SHA1, Wed Feb 25 12:04:05 2015, Key ID 0946fca2c105b9de
Packager    : CentOS BuildSystem <http://bugs.centos.org>
URL         : http://www.mozilla.org/projects/firefox/
Summary     : Mozilla Firefox Web browser
Description :
Mozilla Firefox is an open-source web browser, designed for standards
compliance, performance and portability.
</pre>
![10](https://cloud.githubusercontent.com/assets/200784/6709959/b78758f8-cdc0-11e4-944f-8b7296ddd526.png)
![11](https://cloud.githubusercontent.com/assets/200784/6709960/b7b29d2e-cdc0-11e4-8716-e47f726087fc.png)

**Comment by BanzaiMan** [comment]
Could you elaborate on what the problem is? What exactly is broken? Your build has 66 jobs, some of which pass, some of which fail, and most are just canceled.

Please explain which jobs shows the problem you are trying to address, what you expected to happen, and what actually happened.

**Comment by marutosi** [comment]
See mouse pointer.

**Comment by BanzaiMan** [comment]
Sorry, but I have no idea what they point to. Please explain. If you don't feel comfortable in English, I do understand Japanese.

**Comment by marutosi** [comment]
2015年3月18日 22:49 GMT+9　の時点でマウスを移動すると上記ハードコピーのようにぐちゃぐちゃに崩れました。上記ではCentOS6のffでと述べましたが、Windowsでのie/ff/Chromeでも崩れました。
現時点ではこの現象は確認できません。

ところで、#3386 は解決していないのに、書き込み禁止にしたのは一体何故でしょうか？
全く理解できません。
ですのでこのチケットを作りました。

**Comment by BanzaiMan** [comment]
返答が遅れました。

スクリーンショットの画像のどの辺が崩れていたのか、パッと見では解り辛かったようです。今は解決されたとの報告、有り難うございます。

#3386 の書き込みを禁止したのは、問題がこちらでも確認できて、あれ以上に「この問題に直面している」という報告にはあまり技術的な意味が無い、と判断した為です。
