### ISSUE TITLE
Text does not have enough contrast in the new UI

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#3403]
The grey text in the new UI does not have enough contrast, making it hard to read the build matrix

![travis_colors](https://cloud.githubusercontent.com/assets/439401/6713197/22798d8c-cd91-11e4-95af-7f4856b4f115.png)

**Comment by joshk** [comment]
Thanks for the feedback, we are looking into it.

**Comment by saltinejustine** [comment]
Hey @stof! Thanks for filing this. I agree that the colors in browser are looking more subdued that originally intended and we will be fixing it.

Have a great day!

**Comment by afeld** [comment]
http://webaim.org/resources/contrastchecker/ and other tools like it may be of use. Looks great otherwise – thanks for addressing this!

**Comment by pjanouch** [comment]
The interface is completely unreadable. Please fix.

**Comment by keithj** [comment]
Yes, please change this. I have to "select all" on the page to read the text.

**Comment by joshk** [comment]
Thank you for the feedback, we will be looking into contrast improvements this coming week.

**Comment by BanzaiMan** [comment]
We've made some changes to the display in recent weeks.
