### ISSUE TITLE
"ruby-2.2.1 is not installed" with 2.2.1 in .ruby-version

### ISSUE THREAD

**Issue by dmolesUC3** [travis-ci/travis-ci#3404]
Despite seeing Ruby 2.2.1 in the [precompiled versions list](http://rubies.travis-ci.org/), on updating from Ruby 2.2 to Ruby 2.2.1, I got the error above.

See [this build, which failed](https://travis-ci.org/CDLUC3/dash2-harvester/builds/54915114) and [this commit, which updates the version](https://github.com/CDLUC3/dash2-harvester/commit/934fdfc40d252079b3b142564c4ec53109cffb63).

**Comment by BanzaiMan** [comment]
2.2.1 will be pre-installed for the next build environment update, scheduled for early April.

Until then, it will have to be installed on demand.

**Comment by dmolesUC3** [comment]
Is there a list of pre-installed versions? Supposedly it's in the CI Environment Guide, but all the [Ruby section](http://docs.travis-ci.com/user/ci-environment/#Ruby-(aka-common)-VM-images) says is that 1.8.6 and 1.9.1 aren't supported and that Travis uses rvm.

**Comment by joshk** [comment]
@BanzaiMan this issue is actually related to the beta feature we have with reading and using the ruby version from the `.ruby_version` file when it isn't preinstalled.

I'm reopening this as we really should find a fix for this.

**Comment by BanzaiMan** [comment]
@dmolesUC3 In the "Build system information" fold, you will find the list of pre-installed Ruby versions.

**Comment by BanzaiMan** [comment]
Hmmm. There is something strange going on with the information fold, since it only lists 1.9.3-p551, which is not true at all. :-/ That is a different issue.

**Comment by dmolesUC3** [comment]
I'm happy to have helped find *a* bug, even if it wasn't the bug I thought I'd found. :)

**Comment by BanzaiMan** [comment]
I found a workaround and pushed the fix based on it. I'm going to close this (again—sorry about the earlier hasty one) optimistically. If you see problems, do let us know.

**Comment by dmolesUC3** [comment]
Looks good, @BanzaiMan, thanks!

**Comment by waits** [comment]
I know this is old, but I'm now getting the same issue. "Pre-installed ruby versions" under "Build system information" only shows ruby-1.9.3-p551. On both [free](https://travis-ci.org/waits/ntwrk/builds/93852639) and [pro](https://travis-ci.com/janowski/wedding-expo/builds/18387607) repos. The [docs](https://docs.travis-ci.com/user/languages/ruby/#Supported-Ruby-Versions-and-RVM) don't help; they claim recent versions of 2.2.x are installed but 2.2.0 was the newest I could find (via trial-and-error).

**Comment by BanzaiMan** [comment]
@waits Indeed, that seems like a different issue altogether. Could you open a separate issue, please?

**Comment by waits** [comment]
Done: https://github.com/travis-ci/travis-ci/issues/5190
