### ISSUE TITLE
APT whitelist request for chef and chefdk

### ISSUE THREAD

**Issue by smith** [travis-ci/travis-ci#3410]
These are available in the packagecloud chef/stable repository: https://packagecloud.io/chef/stable/install

**Comment by coderanger** [comment]
:+1: Would allow removing https://github.com/coderanger/halite/blob/master/.travis.yml#L13-L19 from all my builds.

**Comment by coderanger** [comment]
Would also be nice to get libgecode and libgecode-dev for people installing Chef stuff via bundler.

**Comment by meatballhat** [comment]
opened a separate one for libgecode in #3411 fwiw

**Comment by meatballhat** [comment]
These are both now available, along with the support for custom apt sources as described here: http://docs.travis-ci.com/user/apt-sources/

![](http://media.giphy.com/media/MrojfwWKzkje0/giphy.gif)
