### ISSUE TITLE
Disabling git --depth option

### ISSUE THREAD

**Issue by wokalski** [travis-ci/travis-ci#3412]
We use git rev-list HEAD --count for build numbering and it's not correct because of --depth option. It doesn't even increase and it's really misleading.

**Comment by joshk** [comment]
Hi @wczekalski 

Sorry, could you please explain further what is misleading by it?

`--depth` is used as to make sure we only clone what is needed.

You can use:

```
git:
  depth: 9999999
```

which is a little (untested) hack around disabling `--depth`

Let us know how you get on.

**Comment by wczekalski** [comment]
Sorry for not being clear. It's misleading because the build number generated by git rev-list is not increasing and it's easy to get lost there

**Comment by weitjong** [comment]
@wczekalski If I understand you correctly then you need to call ```git fetch --unshallow``` before performing the count. On our project we use ```git describe``` to construct our build version string and we found the version string was incorrect without the unshallow operation. We only need to unshallow on certain type of CI-builds where we need build version string.

I agree with joshk that Travis-CI should only clone what is needed for the build. In general case ```--depth=50``` is already more than enough. IMHO, getting more than needed by default would increase the CI build time unnecessarily (especially on project that has a huge commit history). On the contrary, I would suggest Travis-CI team to revise it to use ```--depth=1```. In theory the CI build should only "look at" what is the latest.

**Comment by BanzaiMan** [comment]
@wczekalski Have you tried either of the suggested workarounds? Is there anything else to address here?

**Comment by wczekalski** [comment]
@BanzaiMan I just do git fetch --unshallow and it works perfectly. The only thing I would address here is to somehow write about the depth in the documentation and include possible cases like this

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/docs-travis-ci-com/commit/130d6342da7889a80b8134c321dd005c371e1398.
