### ISSUE TITLE
UI has large white block between header and content in IE when sidebar is visible

### ISSUE THREAD

**Issue by akoeplinger** [travis-ci/travis-ci#3413]
See screenshot:
![image](https://cloud.githubusercontent.com/assets/1376924/6758608/943c9596-cf39-11e4-8d26-8b4782711deb.png)

The white block doesn't appear when the browser windows is made smaller so that the sidebar is hidden.

IE11 on Win 8.1

**Comment by akoeplinger** [comment]
Doesn't repro anymore in the latest redesign:

![image](https://cloud.githubusercontent.com/assets/1376924/6837343/80e03bc2-d34b-11e4-9173-005f1e82d53c.png)

**Comment by joshk** [comment]
why did you close the issue?

**Comment by akoeplinger** [comment]
@joshk as I said above, the issue is gone in the latest redesign. wasn't that clear from the above?

**Comment by joshk** [comment]
ah, sorry, my eyes missed that, its been a long day.

thanks for closing the issue :)

**Comment by akoeplinger** [comment]
no worries :smile:
