### ISSUE TITLE
"Pull Request #XX" could link to the pull request page

### ISSUE THREAD

**Issue by spinda** [travis-ci/travis-ci#3415]
See `Pull Request #363` here:

https://travis-ci.org/ucsd-progsys/liquidhaskell/builds/55263427

And `PR #363` on the pull request listings tab:

https://travis-ci.org/ucsd-progsys/liquidhaskell/pull_requests

This would make for easier navigation between Travis and GitHub. As it stands (as far as I can tell), to view the pull request with which a build is associated, one must either manually construct a URL based on the PR number or navigate over to the repository and dig for the PR in the list.

Could work for branch names as well:

https://travis-ci.org/ucsd-progsys/liquidhaskell/branches

https://travis-ci.org/ucsd-progsys/liquidhaskell/builds/55263414

**Comment by joshk** [comment]
Hi @spinda 

Thanks for the suggestion.

As a PR can have many builds associated with it, would the URL, eg. `pr/363` go to the latest build?

**Comment by spinda** [comment]
Ah, I meant the other way round, actully. The "Pull Request #XX" text on
the build page on Travis would be a link going to the GitHub page for the
Pull Request.

**Comment by joshk** [comment]
Ok, so you mean the main commit message in the build header?

That link is currently on the right hand side side, which is where our external links are.

**Comment by spinda** [comment]
Ah, wow, I missed that! Thanks, and sorry for wasting your time here.

**Comment by joshk** [comment]
My time was not wasted, it is good to hear all feedback, this was very helpful :)

Have an awesome day.
