### ISSUE TITLE
Android "dx" command fails with exit code 137

### ISSUE THREAD

**Issue by donv** [travis-ci/travis-ci#3416]
Hi!

This is probably not a travis issue in itself, but I have struggled with this error since last year now, and it is hurting the project.  I beg for your help, please!  :)

We run a matrix of tests that use the Android "dx" command to build apps.  The apps can contain several jars and the "dx" command fails with exit code 137 on certain builds in travis-ci.  The tests run green on OS X, and in VirtualBox Ubuntu boxes on OS X.

I have no actual clue what is wrong.

I have researched a lot, but the closest I have come to a theory is that it is a memory problem.  The "dx" command is a shell script that calls Java, so I have experimented with different settings for -Xmx.  High values seem to trigger the problem, while lower values seem to allow more matrix variants to work.

Too low values, like -Xmx1024M, makes the dx command fail with an informative error message that it is out of memory.

I did have a problem a while ago where the Java VM was unable to allocate the virtual memory it needed when the travis worker had no swap at all.  After workers got some swap, that problem went away.

The best solution would be to find a way to debug why dx fails with error 137, and fix what is wrong, but I would be happy for absolutely any help.

**Comment by donv** [comment]
The best build lately is https://travis-ci.org/ruboto/ruboto/builds/55248786

**Comment by donv** [comment]
Well, actually this one was better:  https://travis-ci.org/ruboto/ruboto/builds/54868732

**Comment by BanzaiMan** [comment]
@donv Exit code 137 is most likely OOMKiller terminating your process when your VM runs out of memory. The best course of action is to reduce memory consumption if possible. Presently, VM on the standard infrastructure has only 3 GB of memory, so raising the memory limit may not help much.

I surveyed your repo, and seems that you don't need `sudo` to run, so I suggest moving to containers (http://docs.travis-ci.com/user/workers/container-based-infrastructure/), which gives you larger VMs.

**Comment by donv** [comment]
Hi @BanzaiMan !

Thanks for the quick response.  OOMKiller sounds like the likely cause.  I had a limited success with reducing the memory usage, so there is progress :)

I will look into containers for our build.  Thank you!

**Comment by BanzaiMan** [comment]
@donv Hopefully https://github.com/ruboto/ruboto/pull/709 would give you good results. :-D

**Comment by donv** [comment]
@BanzaiMan I created a branch ```fix_travis``` that is easier to experiment with.

**Comment by donv** [comment]
@BanzaiMan I am watching build https://github.com/ruboto/ruboto/pull/709 now :)

**Comment by donv** [comment]
The change looks like it solves this issue.  Thanks again!
