### ISSUE TITLE
APT whitelist request for gccmultilib

### ISSUE THREAD

**Issue by 50Wliu** [travis-ci/travis-ci#3425]
gccmultilib is needed in order for [spcomp](https://github.com/alliedmodders/sourcepawn/tree/master/compiler) to run on 64-bit machines.  I'd really like to be able to transition to the new container-based infrastructure and this is the only thing holding me back at this point :).

**Comment by 50Wliu** [comment]
:sparkles: Thanks!

**Comment by meatballhat** [comment]
@50Wliu :metal: :smiley_cat:
