### ISSUE TITLE
Documentation for language: csharp. Use of filename expansion

### ISSUE THREAD

**Issue by wallymathieu** [travis-ci/travis-ci#3426]
@joshua-anderson @akoeplinger @nterry
Could the documentation be made simpler by using filename expansion? I.e. write:

    mono ./packages/NUnit.Runners.*/tools/nunit-console.exe

Instead of hard coding the test runner version.

**Comment by akoeplinger** [comment]
Hmm, I'm torn about this one since we explicitly mention the version when installing the NuGet package and it may lead to confusion if we omit it later on (filename expansion might not be familiar to most .NET devs coming from Windows). I'd prefer being explicit I think.

What do the others think?

**Comment by wallymathieu** [comment]
Well, true.

What a developer could do is to add the test runner nuget package to the solution package.config. The package config file found in the .nuget directory. That's usually how I specify testrunner for use with travis and appveyor. If you do a nuget restore on the solution, then that package will be installed as well.

Perhaps a different section on the documentation page?

"Using solution nuget package"

**Comment by akoeplinger** [comment]
Yep, sounds good. The docs file is in https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/languages/csharp.md, so feel free to send a PR :)

**Comment by wallymathieu** [comment]
There:
https://github.com/travis-ci/docs-travis-ci-com/pull/216

**Comment by BanzaiMan** [comment]
We merged the doc PR.
