### ISSUE TITLE
apt_packages should note disallowed but provided packages

### ISSUE THREAD

**Issue by arr2036** [travis-ci/travis-ci#3434]
apt_packages should note in its output when a package is provided as part of the image, if it's going to disallow the installation of that package.

Output from the build [here](https://travis-ci.org/arr2036/freeradius-server/jobs/55338462), indicated that I would need to follow the whitelisting process to use the autoconf package.

```
Installing APT Packages (BETA)
Disallowing packages: autoconf, build-essential, debhelper, dh-make, fakeroot, lintian, pbuilder, python-dev, quilt, libruby, ruby-dev, libcollectdclient-dev, firebird-dev, libcap-dev, libcouchbase2-libevent, libcouchbase-dev, libcurl4-openssl-dev, libgdbm-dev, libhiredis-dev, libidn11-dev, libiodbc2-dev libiodbc2, libjson0, libjson0-dev, libkrb5-dev, libldap2-dev, libmysqlclient-dev, libpam0g-dev, libpcap-dev, libpcre3-dev, libperl-dev, libpq-dev, libreadline-dev, libsnmp-dev, libssl-dev, libtalloc-dev, libtalloc2-dbg, libunbound-dev, libwbclient-dev, libykclient-dev, libyubikey-dev
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
```

Which lead to spurious ticket: https://github.com/travis-ci/travis-ci/issues/3427

**Comment by meatballhat** [comment]
I've added all of the packages that come pre-installed to the whitelist, so this should no longer be an issue.  Thanks for the report!
