### ISSUE TITLE
APT whitelist request for varnish, apache2, libapache2-mod-fastcgi & ttf-mscorefonts-installer

### ISSUE THREAD

**Issue by shouze** [travis-ci/travis-ci#3435]
Packages to whitelist:
- varnish
- apache2
- libapache2-mod-fastcgi
- ttf-mscorefonts-installer

**NOTICE**: about apache, should be great to be able to use `a2en*` & `a2dis*` commands (like a2enmod).

**Comment by Spy-Seth** [comment]
:+1:

**Comment by gmorel** [comment]
:+1:

**Comment by stephpy** [comment]
:+1:

**Comment by tyx** [comment]
:+1:

**Comment by meatballhat** [comment]
Tackling `a2en*` and `a2dis*` usage is going to be more involved.  Any chance you can open a separate issue for that? :smiley_cat:
