### ISSUE TITLE
pyquery broken unexpectedly?

### ISSUE THREAD

**Issue by groovecoder** [travis-ci/travis-ci#3436]
We just started getting these on some of our travis jobs. [[1]](https://travis-ci.org/mozilla/kuma/jobs/55490148)[[2]](https://travis-ci.org/mozilla/kuma/jobs/55525733):
```
  File "/home/travis/build/mozilla/kuma/vendor/packages/pyquery/pyquery/__init__.py", line 10, in <module>
    from pyquery import PyQuery
  File "/home/travis/build/mozilla/kuma/vendor/packages/pyquery/pyquery/pyquery.py", line 6, in <module>
    from cssselectpatch import selector_to_xpath
  File "/home/travis/build/mozilla/kuma/vendor/packages/pyquery/pyquery/cssselectpatch.py", line 6, in <module>
    from lxml.cssselect import Pseudo, XPathExpr, XPathExprOr, Function, css_to_xpath, Element
ImportError: cannot import name Pseudo
```
[A RedHat bug suggests it's an incompatibility with libxml2-dev](https://bugzilla.redhat.com/show_bug.cgi?id=966102) and old version of pyquery (like ours). Was libxml recently updated on Travis CI hosts?

**Comment by jwhitlock** [comment]
tox 1.9.1 has an issue where it installed the latest versions of packages, not the pinned version from requirements.txt.  tox 1.9.2 has been released and reverts to 1.9.0's behaviour, installing the pinned versions.

**Comment by joshk** [comment]
So this isn't a Travis issue?

Can this issue be closed?

**Comment by groovecoder** [comment]
Correct, this is a tox issue.
