### ISSUE TITLE
SVG image seems stuck when build is passing.

### ISSUE THREAD

**Issue by shaunbrady** [travis-ci/travis-ci#3438]
Hello,
    For a few days now this image: https://api.travis-ci.org/nimbis/django-x509-auth.svg?branch=master has shown as failing.  My master branch (https://travis-ci.org/nimbis/django-x509-auth/branches) has been passing for 4 days.  Let me know if there is any thing else I can do on my side to remedy this.  As well I can provide any information needed.

Thank you,

Shaun Brady
Senior Web Services Engineer
Nimbis Services, Inc.

**Comment by roidrage** [comment]
It looks like the build badge is now showing the correct information, can you confirm?

**Comment by shaunbrady** [comment]
The build badges now show correctly.  Let me know if there was something we did to cause this issue; else, thanks.
