### ISSUE TITLE
GOPATH export should not have trailing : when using language: go

### ISSUE THREAD

**Issue by gbrayut** [travis-ci/travis-ci#3439]
The GOPATH created by both the container and vm build systems adds a : to the end of the value. Example: `export GOPATH=$HOME/gopath:`. This causes commands that use $GOPATH to fail. 

https://travis-ci.org/bosun-monitor/bosun/builds/55571114

The GOPATH should only contain a single path, so unlike the PATH export is should NOT use : as a delimiter. Adding `export GOPATH=$HOME/gopath` to the .travis.yml file fixes the GOPATH export:

https://travis-ci.org/bosun-monitor/bosun/builds/55571775

**Comment by shurcooL** [comment]
Agreed. It's very odd that the GOPATH in Travis contains a single path, with a colon at the end.

It's as weird and unnecessary as doing `export PATH=/foo/bar:$PATH:".

Typically, when GOPATH contains one path, it's valid to do `cd $GOPATH/src/foo/bar", but having that colon breaks that ability.

**Comment by meatballhat** [comment]
You're absolutely right that explicitly adding a trailing `:` is weird and unnecessary, so I'll take care of backing that out.  That being said, I'm very much against promoting the use of `$GOPATH` as a singular path entry.  If you need to rely on a single entry, you should use `${GOPATH%%:*}` (which is safe for singular or plural), e.g.:

``` yaml
env:
  global:
  - TOP_GOPATH=${GOPATH%%:*}

# ...
script:
- cd $TOP_GOPATH/src/foo/bar
```

It's my hope that if the rules around `$GOPATH` change in the future such that it is a singular path entry that it will be a new variable, at which point Travis can support both :smiley_cat:.

**Comment by shurcooL** [comment]
Thanks for fixing it.

As far as `GOPATH` being a list of Go workspaces, which may contain 1, 2, 3 or more entries (just like `PATH`), I am extremely familiar with that (I've fought many battles helping other people fix their Go code that made the incorrect assumption and didn't work with my valid Go environment).

My attitude towards it is the following. If you're making a Go tool or library that uses the value of `GOPATH`, you should absolutely treat and parse `GOPATH` correctly (by using [`filepath.SplitList`](http://godoc.org/path/filepath#SplitList). It's very bad to assume the user will always have one Go workspace entry.

However, if you are a _user_ and you control your Go environment and you explicitly know your own `GOPATH` contains exactly one entry (for example, on your own private server), then it's okay to take the shortcut and do things like `cd $GOPATH/src/foo`.

**Comment by meatballhat** [comment]
@shurcooL I fully agree :smiley_cat:  I'll get this deployed soonish :+1:
