### ISSUE TITLE
OS X/iOS SDK versions missing

### ISSUE THREAD

**Issue by Ashton-W** [travis-ci/travis-ci#3440]
Supported OS X/iOS SDK versions #
    
    Currently pre-installed on our systems are the following SDKs for Xcode:
    
    iOS 8.1 (simulator and device)
    iOS 7.1 (simulator)
    iOS 7.0 (simulator)
    OS X 10.10
    OS X 10.9
http://docs.travis-ci.com/user/languages/objective-c/

A [recent build log](https://travis-ci.org/cruffenach/CRToast/builds/55447319) will show you only the following are available:
- iOS 8.1 (simulator and device)
- ~~iOS 7.1 (simulator)~~
- ~~iOS 7.0 (simulator)~~
- OS X 10.10
- OS X 10.9

**Comment by henrikhodne** [comment]
Hi, I'm sorry for the very late reply on this. We've since updated the page to show the different versions of SDKs that are available on the different OS X images.
