### ISSUE TITLE
Local deployment of Travis-CI

### ISSUE THREAD

**Issue by sowani** [travis-ci/travis-ci#3442]
I am interested in running Travis-CI locally. I want to do this for a new platform not yet supported by Travis-CI.org/.com and my porting changes will be given back to Travis-CI community.

I reviewed following threads in this regard:
https://github.com/travis-ci/travis-ci/issues/2114
http://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally

However I would like to know if there exist any documentation or plan which might tell the minimum Travis-CI modules required to be ported or what all needs to be done for getting Travis-CI up and running on a stand-alone machine.

I hope somebody from existing Travis-CI community would be interested in this task and might be willing to guide me to appropriate documents/pointers.

Thanks!
Atul.

**Comment by bmcorser** [comment]
:+1:

**Comment by roidrage** [comment]
Travis CI is available to be installed locally via our [Enterprise](https://enterprise.travis-ci.com) version. Sorry, but at this point we have no instructions how to set it up locally, so I'm closing this issue.
