### ISSUE TITLE
Clang not being used though it is requested

### ISSUE THREAD

**Issue by stnava** [travis-ci/travis-ci#3446]
https://travis-ci.org/stnava/ANTsR

on the above repository i am exporting clang as my environment and R compiler variables.  however, it seems this is no longer being picked up by the travis environment.  cant see any reason why as this used to work fine.

more info: see

https://api.travis-ci.org/jobs/55659699/log.txt?deansi=true

and search for g++ and you will see ITKR compile is using g++ ... while others use clang.

maybe i am misunderstanding something, though.  here is the travis.yml:

https://github.com/stnava/ANTsR/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
Sorry for the long delay.

I'm closing this as it's become stale. (This predates our community support of R.)
