### ISSUE TITLE
APT whitelist request for capnproto, libcapnp, libcapnp-dev

### ISSUE THREAD

**Issue by bozaro** [travis-ci/travis-ci#3447]
When using Cap'n Proto in my project, I need the capnp command in the command line which is available via installing these packages in ubuntu.
Please whitelist these packages so they can be installed.

**Comment by meatballhat** [comment]
@bozaro These packages don't seem to be available in our default sources.  Is there a PPA or other APT source you need to have added?

**Comment by bozaro** [comment]
This deb-packets available in Ubuntu 14.04+ by default (universe):

 * http://packages.ubuntu.com/en/trusty/capnproto
 * http://packages.ubuntu.com/en/trusty/libcapnp-0.4.0
 * http://packages.ubuntu.com/en/trusty/libcapnp-dev

I am sorry, I forgot that Travis uses Ubuntu 12.04 :(

**Comment by meatballhat** [comment]
@bozaro 14.04 is coming soon! :heart:

**Comment by dwrensha** [comment]
@bozaro: I think building capnproto from source is your best option for now. Here's how I do it [for capnproto-java](https://github.com/dwrensha/capnproto-java/blob/05ee85b3752f6461e1c393098c26053fb13eda4d/.travis.yml) using a release tarball, and [for capnpc-rust](https://github.com/dwrensha/capnpc-rust/blob/a59e22fcbef05665f26e85f77ee1f4f1a695649a/.travis.yml) using `git clone`.

**Comment by bozaro** [comment]
@dwrensha: Thanks for the advice and library capnpc-rust. At the moment I'm just trying to tie it to my home project.
I'm trying to use a container assembly, since it is faster and cheaper :)

**Comment by BanzaiMan** [comment]
Did not run automated check because 'capnproto, libcapnp, libcapnp-dev' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because 'capnproto, libcapnp, libcapnp-dev' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for capnproto, libcapnp, libcapnp-dev' is ambiguous. Please specify only one.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/360.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
