### ISSUE TITLE
Secure env vars for multiple repos in a single .travis.yml is broken

### ISSUE THREAD

**Issue by cvrebert** [travis-ci/travis-ci#3449]
This is a follow-up to https://twitter.com/travisci/status/580390353330671616 (I'd forgotten y'all had this issue tracker).
Basically, [Bootstrap's `.travis.yml`](https://github.com/twbs/bootstrap/blob/master/.travis.yml#L27) has some secure env vars encrypted for [twbs-savage/bootstrap](https://github.com/twbs-savage/bootstrap) in addition to others that are encrypted for twbs/bootstrap. Commits regularly get pushed from twbs/bootstrap to twbs-savage/bootstrap.
The builds had been working fine up through https://travis-ci.org/twbs-savage/bootstrap/jobs/55118683#L126 (build 181), but the env vars seem to have disappeared starting with https://travis-ci.org/twbs-savage/bootstrap/jobs/55452209#L118 (build 182). The Travis config was the same for both builds and hasn't been altered for a while.

Some context for interpreting the build output: `$TWBS_S3_BUCKET` is one of the secure env vars and it's accessed by the `./test-infra/s3_cache.py` script. In the earlier builds, the env var is present and the script runs fine. In the later builds, the env var is apparently absent and thus the script outputs an error message about the absence of `$TWBS_S3_BUCKET`. Similarly, the fact that no Grunt tasks are executed in the later builds is due to the lack of other secure env vars (such as `$SAUCE_ACCESS_KEY`).

I am more than happy to provide further information to aid your troubleshooting/debugging.

**Comment by joshk** [comment]
Hmmm, this is very interesting.

The important things to notice is https://travis-ci.org/twbs-savage/bootstrap/jobs/55118683#L79 and https://travis-ci.org/twbs-savage/bootstrap/jobs/55452209#L79

I think we have a bug which is causing the global env vars to not be exported. Where the bug is though I am not sure yet.

We are looking into it and hope to have more information soon.

**Comment by rkh** [comment]
Hi @cvrebert, could you trying re-encrypting all the values? Apologies for the inconvenience.

**Comment by cvrebert** [comment]
And now it started working again, even though we haven't made any changes on our end:
https://travis-ci.org/twbs-savage/bootstrap/jobs/55826007

**Comment by rkh** [comment]
Yes, we rolled back to an earlier deploy.

**Comment by BanzaiMan** [comment]
Closing.
