### ISSUE TITLE
Pull request status on github is stuck on pending despite of the build being completed

### ISSUE THREAD

**Issue by jck** [travis-ci/travis-ci#3450]
This is happening to multiple PRs on https://github.com/jandecaluwe/myhdl
Example: jandecaluwe/myhdl#39

**Comment by joshk** [comment]
Thank you for the report, we are looking into it.

**Comment by jck** [comment]
This is not happening anymore. Thanks for looking into it.

**Comment by senid231** [comment]
same on https://github.com/yeti-switch/yeti-web

example https://github.com/yeti-switch/yeti-web/pull/763
