### ISSUE TITLE
Travis-CI docker worker fails to clone repo

### ISSUE THREAD

**Issue by kaspermarstal** [travis-ci/travis-ci#3451]
I recently upgraded my .travis.yml file to avoid the use of `sudo` and build on Travis' new EC2 infrastructure, but Travis' `git clone` causes the build to fail _before_ the `before_install` step is reached, because Travis builder seems to use sudo itself. The following error is thrown:

    This job is running on container-based infrastructure, which 
    does not allow use of 'sudo', setuid and setguid executables.

However, the error occurs when Travis is simply cloning my repo. That is, before the .travis.yml file is even touched (as far as I understand).

[This is the .travis.yml file][1]:

    sudo: false

    language: cpp

    compiler:
      - gcc
      - clang

    before_install:
      - pwd
      - date -u
      - uname -a
      - $CXX --version
  
    before_script:
      - export OMP_NUM_THREADS=2
      - echo $OMP_NUM_THREADS

    script:
      - mkdir SimpleElastix-build
      - cd SimpleElastix-build
      - cmake -DWRAP_CSHARP:BOOL=OFF -DWRAP_JAVA:BOOL=OFF -DWRAP_LUA:BOOL=OFF -DWRAP_PYTHON:BOOL=OFF -DWRAP_R:BOOL=OFF -DWRAP_RUBY:BOOL=OFF -DWRAP_TCL=BOOL=OFF ../SimpleElastix/SuperBuild
      - make >/dev/null --jobs=4
 
    after_script:
      - ./SimpleITK-build/bin/SimpleITKUnitTestDriver0 >/dev/null
      - ./SimpleITK-build/bin/SimpleITKUnitTestDriver1 >/dev/null
      - ./SimpleITK-build/bin/SimpleITKUnitTestDriver2 >/dev/null
      - ./SimpleITK-build/bin/SimpleITKUnitTestDriver3 >/dev/null
      - ./SimpleITK-build/bin/SimpleITKUnitTestDriver4 >/dev/null
      - ./SimpleITK-build/bin/SimpleITKUnitTestDriver5 >/dev/null
      - ./SimpleITK-build/bin/SimpleITKUnitTestDriver6 >/dev/null
      
[This is the error message][2] (see link for full log):

    Using worker: worker-linux-docker-bcc59c93.prod.travis-ci.org:travis-linux-13
    travis_fold:start:system_info
    [0K[33;1mBuild system information[0m
    Build language: cpp
    [34m[1mBuild image provisioning date and time[0m
    Thu Feb  5 15:09:33 UTC 2015
    [34m[1mOperating System Details[0m
    Distributor ID: Ubuntu
    Description:    Ubuntu 12.04.5 LTS
    Release:    12.04
    Codename:   precise
    [34m[1mLinux Version[0m
    3.13.0-29-generic
    [34m[1mCookbooks Version[0m
    a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
    [34m[1mGCC version[0m
    gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
    Copyright (C) 2011 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    [Installed databases etc is redacted for brevity, see link for full system information]

    travis_fold:end:system_info
    [0K
    travis_fold:start:git.checkout
    [0Ktravis_time:start:010c8fae
    [0K$ git clone --depth=50 --branch=SimpleElastixRebase git://github.com/kaspermarstal/SimpleElastix.git kaspermarstal/SimpleElastix
    Cloning into 'kaspermarstal/SimpleElastix'...
    remote: Counting objects: 4524, done.[K

    remote: Compressing objects: 100% (2244/2244), done.[K
    Receiving objects:   0% (1/4524)    
    Resolving deltas: 100% (2511/2511), done.
    Checking connectivity... done.
    travis_time:end:010c8fae:start=1427297403999154316,finish=1427297406473918291,duration=2474763975
    [0K$ cd kaspermarstal/SimpleElastix
    $ git checkout -qf f14b32da8ea8d4b721c092c5b3357bba9e04b3a3
    travis_fold:end:git.checkout
    [0K
    [33;1mThis job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.[0m
    [33;1mIf you require sudo, add 'sudo: required' to your .travis.yml[0m
    [33;1mSee http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.[0m
    $ export CXX=g++
    $ export CC=gcc
    $ gcc --version
    gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
    Copyright (C) 2011 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    travis_fold:start:before_install.1
    [0Ktravis_time:start:024aaf70
    [0K$ pwd

As is apparent from the log, travis_fold:start:before_install is invoked _after_ the error is thrown.

Any insights as to what goes wrong? Is it my setup?

  [1]: https://github.com/kaspermarstal/SimpleElastix/blob/f14b32da8ea8d4b721c092c5b3357bba9e04b3a3/.travis.yml
  [2]: https://s3.amazonaws.com/archive.travis-ci.org/jobs/55813858/log.txt

**Comment by kaspermarstal** [comment]
The message 

    This job is running on container-based infrastructure, which 
    does not allow use of 'sudo', setuid and setguid executables.

was not an error, just for information. The error was related to misconfiguration of nested folders.

**Comment by joshk** [comment]
Great to hear the core issue has been found and resolved.

Closing this.
