### ISSUE TITLE
APT whitelist request for firebird-dev

### ISSUE THREAD

**Issue by arr2036** [travis-ci/travis-ci#3458]
Needed for rlm_sql_firebird in the FreeRADIUS project

**Comment by arr2036** [comment]
@meatballhat firebird2.5-dev has a dependency on firebird-dev, so both are probably required? Unless I'm misunderstanding the page here: http://packages.ubuntu.com/precise/firebird2.5-dev

**Comment by meatballhat** [comment]
Whoops!  I meant to add all of the packages defined in the package source.
