### ISSUE TITLE
APT whitelist request for libcouchbase2-libevent libcouchbase-dev

### ISSUE THREAD

**Issue by arr2036** [travis-ci/travis-ci#3460]
Needed for rlm_couchbase in the FreeRADIUS project

**Comment by meatballhat** [comment]
@arr2036 I'm not finding these in our current sources.  Does a PPA or other APT source need to be added?  Thanks! :smiley_cat:

**Comment by arr2036** [comment]
Ah, darn. Very likely. You don't allow 3rd party PPAs currently do you?

**Comment by arr2036** [comment]
Hmm, yes, this is what is in the non-container ``.travis.yml``

```
  - wget -O - http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
  - sudo sudo wget -O /etc/apt/sources.list.d/couchbase.list http://packages.couchbase.com/ubuntu/couchbase-ubuntu1204.list
```

So obviously not going to work here... Oh well. It's not absolutely critical.

**Comment by meatballhat** [comment]
@arr2036 the `apt_sources` addon was added this week.  I'll see about getting this source added :smiley:

**Comment by arr2036** [comment]
Yay! Thanks :+1:

**Comment by meatballhat** [comment]
@arr2036 :metal: :smiley_cat:
