### ISSUE TITLE
It would be nice for the D compiler to be updated to v2.067.0

### ISSUE THREAD

**Issue by nomad-software** [travis-ci/travis-ci#3472]
It would be nice for the D compiler to be updated to v2.067.0.

Thanks.

ping @MartinNowak.

**Comment by MartinNowak** [comment]
Will look into that soon.

**Comment by nomad-software** [comment]
Thanks Martin.

**Comment by MartinNowak** [comment]
Fixed, it's now possible to specify `dmd`, `gdc`, or `ldc` to get the latest compiler versions.

**Comment by BanzaiMan** [comment]
Closing this, since the PR has been merged.

**Comment by nomad-software** [comment]
Awesome, thanks all.

**Comment by deadalnix** [comment]
How fast do we expect this to kick in and start using 2.069 ?
