### ISSUE TITLE
update Firefox and Chromium

### ISSUE THREAD

**Issue by deepsweet** [travis-ci/travis-ci#3475]
hi.

as far as I can see Firefox and Chromium versions installed on Travis are outdated, at least Karma shows me this:
* `Firefox 31.0.0 (Linux)`, but current ESR is `31.5.4`
* `Chromium 37.0.2062 (Ubuntu)`, but current stable is `41.0.2272.101`

it's not so critical, but anyway it would be nice to hear some words about browsers update policy.

**Comment by BanzaiMan** [comment]
Firefox will be updated for the next build environment update to something more recent.

Chromium is unlikely to see an update, since there is nothing newer on http://packages.ubuntu.com/precise/chromium-browser.

**Comment by deepsweet** [comment]
thanks, that's enough :+1:

**Comment by deepsweet** [comment]
looks like Ubuntu 12.04 stucked with Chromium 37 for years, because 14.04 package contains 41 http://packages.ubuntu.com/trusty/chromium-browser

**Comment by BanzaiMan** [comment]
Fixed by travis-ci/travis-cookbooks@fb042e0.

**Comment by silentroach** [comment]
Chromium 37 is very, very old :{

**Comment by BanzaiMan** [comment]
@silentroach Does the firefox addon not work for you? http://docs.travis-ci.com/user/firefox/

**Comment by silentroach** [comment]
My project is a chrome extension, so I need to test it with karma+chrome.
Now I need to install stable chrome via apt-get

**Comment by BanzaiMan** [comment]
@silentroach Then it is a matter of choosing `sudo: required`, and using `sudo apt-get` to install what you need. Did I miss something?

**Comment by silentroach** [comment]
Yep. Not an easy way
