### ISSUE TITLE
Organizations on my profile page don't load

### ISSUE THREAD

**Issue by JasonBarnabe** [travis-ci/travis-ci#3476]
I'm trying to add a project from an organization I'm an owner of. I'm going to https://travis-ci.org/profile/JasonBarnabe and under the Organizations sidebar, there's just the "loading" icon. It never lists my organizations. Tried under Firefox 36 and Chrome 41 on Ubuntu.

**Comment by JasonBarnabe** [comment]
This was an organization that was created after I created my Travis account. I found in GitHub the setting to authorize access to it, and it works now.

Still though, a useful error message in Travis would be good.

**Comment by joshk** [comment]
Hi @JasonBarnabe 

Sorry for the issues, I am escalating this to our Web team so we can roll out a fix ASAP.

Have a great day

Josh

**Comment by drogus** [comment]
@JasonBarnabe what was the setting that you changed? Was it "third party access"?

**Comment by JasonBarnabe** [comment]
Yes, approving third party access for Travis to the organization.

**Comment by joshk** [comment]
I'm going to close this issue for now. We have two improvements in the works to improve the cases where orgs are not shown.

Thank you for opening this.
