### ISSUE TITLE
Occasionally a build does not start

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#3477]
Occasionally one or two of the builds in our matrix wouldn't start.
Example: https://travis-ci.org/HaxeFoundation/haxe/jobs/55958101

Log:

```
No output has been received in the last ... minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Note that restarting the build "fixes" it.

**Comment by meatballhat** [comment]
@andyli Hi there!  Thanks so much for the report.  We've gotten an increasing number of reports and are rolling out a release with more debugging to see if we can get to the root cause.  Thanks for your patience!

**Comment by andyli** [comment]
Just to report that this still happens to our builds. Hope it will be resolved soon.

**Comment by weitjong** [comment]
Same here. This was one of the example. https://travis-ci.org/urho3d/Urho3D/jobs/60914193. Restarting the job usually fixes the problem although on a few rare occasion the restarted job also ends in a similar problem and need another restart. Interestingly, it only occurs on our CI jobs on OSX build environment.

**Comment by weitjong** [comment]
The problem seems to be resolved now since the last two days. I wonder something has been done on Travis build side to improve the situation. If so, you have my thanks.

**Comment by andyli** [comment]
It still occurs to our builds today :(

**Comment by weitjong** [comment]
Yes. It happens again since today. https://travis-ci.org/urho3d/Urho3D/jobs/62204710.

**Comment by juanvimartinez** [comment]
Hapenning to me during the last 3 days with a Java/Android project. Restarting the build doesn't solve the issue.

**Comment by weitjong** [comment]
Yup. It is definitely happening all over again today. The last two runs of our OSX CI build failed today. It was ok in between the time. Apparently when it is ok then we would not be here making the comment.

**Comment by SandroMachado** [comment]
Still happening... Restart the build fixed the issue

**Comment by voltrevo** [comment]
Also experiencing this issue. Very confusing.

**Comment by stevenvachon** [comment]
Restarting the build won't fix it for me. The build isn't shown in "Requests" either.
