### ISSUE TITLE
APT whitelist request for clang-3.5, clang-3.6 and clang-3.7

### ISSUE THREAD

**Issue by ldionne** [travis-ci/travis-ci#3478]
This is related to my request for LLVM's official apt repositories at https://github.com/travis-ci/apt-source-whitelist/issues/1.

**Comment by meatballhat** [comment]
@ldionne you should be all set now!  The source aliases match the third token in each llvm source line.

**Comment by ldionne** [comment]
Thank you, I'm giving it a try!

**Comment by jaredsburrows** [comment]
@ldionne  Did you get this working?

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6

`clang-3.6` and `clang-3.7` does not work.

**Comment by ldionne** [comment]
@jaredsburrows 
3.6 works for me, 3.7 used to work but stopped working 3 days ago. See [this build](https://travis-ci.org/ldionne/hana/builds/72598291), which works on 3.6 but not on 3.7.

**Comment by ldionne** [comment]
@jaredsburrows By the way, no wonder your 3.6 is not working if you use `llvm-toolchain-precise-3.7`.

**Comment by jaredsburrows** [comment]
@ldionne I have switched it back and forth on a `dev` branch of mine. I will try again.

**Comment by jaredsburrows** [comment]
@ldionne  I have added `llvm-toolchain-precise-3.6` and `clang-3.6` from https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json#L89 and https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise#L309.

I got it working here: https://travis-ci.org/jaredsburrows/CPlusPlusCmakeTemplate/jobs/73594798

Have you seen this `#include <limits>` error before?

**Comment by ldionne** [comment]
Nope, and I suspect this is not specific to clang 3.6 but rather to you doing something wrong. Try compiling with `-v` to see the include paths.

**Comment by jaredsburrows** [comment]
@ldionne Yes I did that: https://travis-ci.org/jaredsburrows/CPlusPlusCmakeTemplate/jobs/73689147.

It has to do with CLang. I am still looking into it.

**Comment by ldionne** [comment]
I would expect to see something along the lines of `/some/prefix/include/c++/v1` in the include paths, which is the directory containing libc++'s headers. AFAICT, there's no C++ standard library in your include path. Try compiling this dummy file with verbose:

```c++
#include <vector>
int main() {}
```

Also, use `make VERBOSE=1` so we can see the actual command line used to launch the compilation, not only the clang `cc1` invocation.

**Comment by jaredsburrows** [comment]
I am using CMake and it does not get that far: https://travis-ci.org/jaredsburrows/CPlusPlusCmakeTemplate/jobs/73698634

**Comment by ldionne** [comment]
Instead of `rm -rf build/ && mkdir build/ && cd build/ && cmake .. && make VERBEROSE=1  && ctest` on a single line, use

```shell
rm -rf build/
mkdir build/
cd build/ && cmake ..
make VERBOSE=1
ctest
```

This will make it more obvious which commands are failing and which ones are succeeding.
Also note that you must replace `VERBEROSE` by `VERBOSE`.

**Comment by jaredsburrows** [comment]
Haha. Sorry about the misspelling.

Here is the new build with the new `.travis.yml` changes.

https://travis-ci.org/jaredsburrows/CPlusPlusCmakeTemplate/jobs/73699490

**Comment by ldionne** [comment]
You seem to be using `-stdlib=libc++`, but there does not seem to be a libc++ installed on the system.

**Comment by ldionne** [comment]
Regardless, you should try to study [this](https://github.com/ldionne/hana/blob/c8542789946b9ff8be693301c7b57d8bd14d8c4b/.travis.yml) `.travis.yml` if your build does not work. It builds with Clang 3.5/3.6 and libc++/stdlibcxx.
