### ISSUE TITLE
Can't add coverage for a new project

### ISSUE THREAD

**Issue by tkrajcar** [travis-ci/travis-ci#3481]
Trying to enable Travis on a new project in a new organization. When I hit the slider, it goes to 'On', but refreshing shows it as 'Off' again. Looking at my JavaScript console, I'm seeing a 500 error: 

![screenshot 2015-03-24 11 39 13](https://cloud.githubusercontent.com/assets/621861/6859624/2eabb9a2-d3d8-11e4-8100-1915413a2e78.png)

Tried logging out and back in, tried fresh sessions, etc.

The repo I'm trying to add coverage for is pennmush/pennmush.

**Comment by joshk** [comment]
Hi @tkrajcar 

Thanks for reporting this. This is a known issue.

This is usually related to http://help.github.com/articles/approving-third-party-applications-for-your-organization

Can you please check if Travis is approved.

We are working on some better error handling on our end.

**Comment by tkrajcar** [comment]
No, it's not approved, and it also doesn't show as pending, either. I'd rather not remove all access restrictions. Any ideas on how to get it to show?

**Comment by joshk** [comment]
You may want to follow this guide: https://help.github.com/articles/requesting-organization-approval-for-your-authorized-applications/

Without Travis having approval, we can't access the API and enable repos for testing.

**Comment by tkrajcar** [comment]
Travis doesn't appear as requesting access there, either. It would appear I need to do something to trigger an access request on the Travis side?

**Comment by joshk** [comment]
Is this for .org or .com?

**Comment by tkrajcar** [comment]
@joshk .org

**Comment by joshk** [comment]
I think it would be best to contact GitHub support and discuss the issue with them as this is out of our control sorry.

Please let us know how it goes, and feel free to cc in support@travis-ci.com

**Comment by tkrajcar** [comment]
@joshk Not trying to be rude here, and I am grateful for the support of this open source project. I'm not following at all how this would be Github's issue. I see no evidence that Travis has initiated any sort of request to Github to request organizational permissions. There's not even any place in the Travis UI to do so that I can see.

How is this supposed to work normally?

**Comment by joshk** [comment]
Is this Org new?

**Comment by tkrajcar** [comment]
Yes, it was only created a few days ago.

**Comment by joshk** [comment]
This article might explain it better https://help.github.com/articles/about-third-party-application-restrictions/

```
When you create a new organization, third-party applications are restricted by default. Organization admins can disable third-party application restrictions at any time.
```

Since you have already logged into Travis with your GitHub account, prior to creating the Org, GitHub doesn't have us listed as requesting permission. This is a usability issue I am raising with GitHub.

This is sadly entirely in GitHubs control, and is sadly a support issue we run into on a weekly basis.

I would highly suggest emailing GitHub and cc'ing us in to.

**Comment by roidrage** [comment]
I'm closing this issues for now as there haven't been any further updates recently.
