### ISSUE TITLE
[Feature Request] Adding notes to a build

### ISSUE THREAD

**Issue by ankon** [travis-ci/travis-ci#3485]
It would be nice if one could annotate a build, for example to describe why it failed. Best case right now: github is under a DDoS attack, so builds fail because clones fail. Being able to add a note to that effect would help other developers to ignore the failure, without spending too much time again on working out why it failed.

**Comment by BanzaiMan** [comment]
Sounds like a duplicate of #168.

**Comment by ankon** [comment]
Agreed, this is a duplicate, closing. Thanks for finding that one :)
