### ISSUE TITLE
API won't recognize that my repository exists

### ISSUE THREAD

**Issue by pmclanahan** [travis-ci/travis-ci#3487]
I'm trying to encrypt some values in my .travis.yml. In order to do that the CLI needs to get information about my repo from the Travis API. When it tries to do that it gets an error:

``` bash
$ curl https://api.travis-ci.org/repos/pmclanahan/contribute.json
{"file":"not found"}
```

It does return a public-key if I append `/key` to the end of the above URL. I've disabled and re-enabled the repo but that hasn't changed anything. This seems like I've hit some edge case, but I can't figure out what. I thought maybe the `.` in the repo name was a problem, but other repos named like that (e.g. travis-ci/travis.rb) are fine.

**Comment by pmclanahan** [comment]
Update: IRC user `GeekOnCoffee` discovered that the following URL does work:

https://api.travis-ci.org/repos/pmclanahan/contribute.json.json

So this issue is due to the repo slug ending in ".json". I'd change the setting to that full slug, but then other requests fail...

```bash
$ curl https://api.travis-ci.org/repos/pmclanahan/contribute.json.json/key
{"file":"not found"}
```

**Comment by svenfuchs** [comment]
Paging @rkh

**Comment by joshk** [comment]
`curl https://api.travis-ci.org/repos/pmclanahan/contribute.json/key` works

**Comment by rkh** [comment]
Yeah, this is because of the file extension parsing we do right now, which is horrible idea to begin with. We only parse the file extension from the end of the URL (excluding query string). This "feature" will be completely removed in v3.

**Comment by rkh** [comment]
You should also be able to use the ID as a workaround (2785952). Don't think we can easily fix this behaviour in our legacy API, which we are going to replace soon, though I don't know the code the well, @svenfuchs probably has a better understanding of that part.

**Comment by svenfuchs** [comment]
To be honest, I'm not sure it would be worth trying to fix that stuff for v2, as long as there's a reliable workaround.

@rkh How do you use the repository id? Does `--repo` accept an id as well?

**Comment by pmclanahan** [comment]
The [API URL with the ID](https://api.travis-ci.org/repos/2785952) works, but the CLI client reports an error:

```bash
$ travis encrypt $(heroku auth:token) --add deploy.api_key -r 2785952
GitHub repo name is invalid, it should be on the form 'owner/repo'
```

**Comment by rkh** [comment]
Ah, yes, the CLI doesn't support passing in the ID. Does the CLI give an error under normal use?

**Comment by pmclanahan** [comment]
Yeah. That's the original issue: `repository not known to https://api.travis-ci.org/: pmclanahan/contribute.json`

**Comment by pmclanahan** [comment]
My goal is to encrypt a value in my `.travis.yml`. I can get the public RSA key via the API using curl, but I've yet to figure out how to properly encrypt a value with it outside of the travis.rb CLI.

**Comment by rkh** [comment]
``` ruby
$ travis console
>> repo(2785952).encrypt("example")
=> "GjPBwTQFVyI4IuNChPRgof69uDhktDLCk4KlDkgOFlSYmzbgkzRRw8/mNHAmIR1WwSzOwQHVyDdG0qzL8/uK4LVXPLu5jbxExL3HORn/SBpEBLnrWo6wC2AGoR7hKs/AnfSwyKnE83X21fqeUMwO7kMxi4KC5Hm4SX44vqJ8QGg="
```

**Comment by pmclanahan** [comment]
Ah! Nice. Thanks Konstantin!

**Comment by NicolasRouquette** [comment]
I ran into the same problem building this repo:
https://github.com/TIWG/org.omg.oti.uml.json

The travis-ci.org repo is here:
https://travis-ci.org/TIWG/org.omg.oti.uml.json

On Travis, I configured an environment variable, ENCRYPTION_PASSWORD.
However, this variable is not set in the builds; e.g.: 

https://travis-ci.org/TIWG/org.omg.oti.uml.json/builds/156270354

So I tried to query via the API and realized that it can't recognize my repo either!

```
$ travis env list --org --repo TIWG/org.omg.oti.uml.json/
repository not known to https://api.travis-ci.org/: TIWG/org.omg.oti.uml.json/
```

Appending '/key' does not work either:

```
 travis env list --org --repo TIWG/org.omg.oti.uml.json/key
private method `load' called for nil:NilClass
for a full error report, run travis report --org
rouquett@imce-infr-dev-01:10 [1] : /opt/local/imce/users/nfr/github.NFR/org.omg.oti.uml.json
[1038] $ travis report --org
System
Ruby:                     JRuby 1.7.19 like Ruby 1.9.3-p551
Operating System:         Linux
RubyGems:                 RubyGems 2.6.6

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-08-30 17:29:20 UTC

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "NicolasRouquette"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis env --org`:
    NoMethodError: private method `load' called for nil:NilClass
        from /home/rouquett/.rvm/gems/jruby-1.7.19/gems/travis-1.8.2/lib/travis/cli/repo_command.rb:24:in `setup'
        from /home/rouquett/.rvm/gems/jruby-1.7.19/gems/travis-1.8.2/lib/travis/cli/env.rb:16:in `setup'
        from /home/rouquett/.rvm/gems/jruby-1.7.19/gems/travis-1.8.2/lib/travis/cli/command.rb:197:in `execute'
        from /home/rouquett/.rvm/gems/jruby-1.7.19/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
        from /home/rouquett/.rvm/gems/jruby-1.7.19/gems/travis-1.8.2/bin/travis:18:in `(root)'
        from org/jruby/RubyKernel.java:1087:in `load'
        from /home/rouquett/.rvm/gems/jruby-1.7.19/bin/travis:1:in `(root)'
        from org/jruby/RubyKernel.java:1107:in `eval'
        from /home/rouquett/.rvm/gems/jruby-1.7.19/bin/jruby_executable_hooks:15:in `(root)'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

It seems that a git repo should not end in '.json'.

**Comment by BanzaiMan** [comment]
@NicolasRouquette That repository seems to have moved to https://github.com/TIWG/org.omg.oti.uml.json.schema. Try resyncing user data (https://travis-ci.org/profile/TIWG).

**Comment by NicolasRouquette** [comment]
@BanzaiMan Yes, I renamed it, thinking that the name ending in '.json' is the problem. I re-synced travis.

In my `.git/config`, I updated the slug:

```
[travis]
	slug = TIWG/org.omg.oti.uml.json.schema
```

The CLI seems OK:

```
travis env list --org --repo TIWG/org.omg.oti.uml.json.schema
# environment variables for TIWG/org.omg.oti.uml.json.schema
ENCRYPTION_PASSWORD=[secure]
```

But the build still fails because the env. var isn't set!

https://travis-ci.org/TIWG/org.omg.oti.uml.json.schema/builds/156302333

Suggestions?

**Comment by BanzaiMan** [comment]
@NicolasRouquette Secure variables are not available for PRs. https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by NicolasRouquette** [comment]
@BanzaiMan On reflection, I'll rework my travis workflow to differentiate PRs where I can't use encrypted vars of any kind (settings or in .travis.yml)
