### ISSUE TITLE
/dev/fuse has the wrong permissions within containers

### ISSUE THREAD

**Issue by spinda** [travis-ci/travis-ci#3491]
Using Travis's container-based environment with the `fuse` package installed, `/dev/fuse` should have read-write permissions for all users:

```
vagrant@precise64:~$ stat /dev/fuse
  File: `/dev/fuse'
  Size: 0         	Blocks: 0          IO Block: 4096   character special file
Device: 5h/5d	Inode: 5880        Links: 1     Device type: a,e5
Access: (1666/crw-rw-rwT)  Uid: (    0/    root)   Gid: (  104/    fuse)
Access: 2015-03-27 21:40:45.965043080 +0000
Modify: 2015-03-27 21:40:45.965043080 +0000
Change: 2015-03-27 21:40:45.965043080 +0000
 Birth: -
```

...but within a container on Travis, it's missing those permissions:

```
$ stat /dev/fuse
  File: `/dev/fuse'
  Size: 0         	Blocks: 0          IO Block: 4096   character special file
Device: fc07h/64519d	Inode: 18012512    Links: 1     Device type: a,e5
Access: (0660/crw-rw----)  Uid: (    0/    root)   Gid: (  115/    fuse)
Access: 2015-03-27 22:08:12.830311753 +0000
Modify: 2015-03-27 22:08:12.830311753 +0000
Change: 2015-03-27 22:08:12.838311539 +0000
 Birth: -
```

This prevents `fuse` filesystems from being mounted within containers.

```
fuse: failed to open /dev/fuse: Permission denied
```

This is similar to a previous issue with the `fuse` package from Debian, but it looks like Travis is installing the correct package version (`fuse 2.8.6-2ubuntu2`), so I think it's a container problem.

(Maybe this could be solved by adding the `travis` user to the `fuse` group? That's just a guess, though.)

**Comment by spinda** [comment]
Any help on this would be appreciated as this is blocking us from moving to Travis containers.

**Comment by joshk** [comment]
fuse is not available on the container setup as enabling the capability is a security issue.

We do have a new setup which is nearly ready for beta testing which will allow for fuse.

I am going to close this issue for now, but please email support@travis-ci.com and we can talk about it there.

**Comment by spinda** [comment]
Will do.
