### ISSUE TITLE
Magnum Travis VM confused

### ISSUE THREAD

**Issue by slavosarik** [travis-ci/travis-ci#3492]
Private github repo: slavosarik/Crowdex

Hello, since yesterday we are not able to finish build. 
Issue: We are trying to build ruby app, but Travis starts executing rspec-test suite before all ruby gems are installed. It causes random failed tests due to this issue. Also, if I cancel build and click on restart, new build starts with "empty" log containing  on last line `Job canceled`  or  `RSpec::Retry: 5th try ./spec/views/sample/sample.rb:254` and this build continues with this line on the end of log.

- sometimes it keeps building even I clicked on cancel button 
- also sometimes it successfully finish build under 2 minutes (about 1/5 rspec tests executed) eventhough standard build duration is 12-15 minutes

Could you please look at this VM? We didnt have any problem for 3 months, now it started to behave very strangely. 

> Screen how it looks like is included here: 
https://www.dropbox.com/s/k3ik0mk60cl01so/travis.png?dl=0 
Look at gem install proccess and tests already running before command bundle exec rspec has been executed.

> I canceled build and it kept building even the build was grayout and marked as Canceled in build list. https://www.dropbox.com/s/8g59enqqqroe1ul/travis2.png?dl=0

**Comment by BanzaiMan** [comment]
@slavosarik Hello. Are you still having this problem? For a specific support question, could you email support@travis-ci.com if you haven't done so already?

Thank you.

**Comment by slavosarik** [comment]
Nope, no problem right now. It happens occasionally.
