### ISSUE TITLE
Builds failing because rabbitmq times out consistently

### ISSUE THREAD

**Issue by cbeck88** [travis-ci/travis-ci#3498]
Hi, we at wesnoth observed many builds that seem to fail with connectivity problems related to rabbitmq. Maybe 50% of the builds failed with logs very similar to this one in the last 48 hours or so.

https://travis-ci.org/wesnoth/wesnoth/jobs/56263027

    45.23s$ sudo apt-get update -qq
    W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/main/i18n/Translation-en_US  Connection failed
    E: Some index files failed to download. They have been ignored, or old ones used instead.
    The command "sudo apt-get update -qq" failed and exited with 100 during .

Or, https://travis-ci.org/wesnoth/wesnoth/jobs/56196525

    44.39s$ sudo apt-get update -qq
    W: There is no public key available for the following key IDs:
    3B4FE6ACC0B21F32
    W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/main/i18n/Translation-en_US  Could not connect to www.rabbitmq.com:80 (192.240.153.117), connection timed out
    W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/main/i18n/Translation-en  Unable to connect to www.rabbitmq.com:http:
    E: Some index files failed to download. They have been ignored, or old ones used instead.
    The command "sudo apt-get update -qq" failed and exited with 100 during .

The builds seem to work fine locally.
Is this a general problem with rabbitmq? I didn't see any indication of this on http://www.traviscistatus.com/
Is there something wrong with our build configuration?

**Comment by meatballhat** [comment]
@cbeck88 Thanks for getting in touch and sorry about the trouble.  We're evaluating options and will be updating this incident accordingly: http://www.traviscistatus.com/incidents/6xtkpm1zglg3

**Comment by cbeck88** [comment]
Thank you, all the builds seem to be working now. :+1:

**Comment by meatballhat** [comment]
@cbeck88 Great, thanks for letting us know! :metal: :smiley_cat:
