### ISSUE TITLE
OSX is not included in build matrix

### ISSUE THREAD

**Issue by david-ragazzi** [travis-ci/travis-ci#3499]
I've spent some time and googled it lot to try find why my build matrix doesn't show OSX but even I have specified it in `os` section, my current matrix only shows linux environments.

Travis file:
https://github.com/nupic-community/nupic.studio/blob/master/.travis.yml

Build matrix:
https://travis-ci.org/nupic-community/nupic.studio/builds/56333874

Could someone point me what I'm doing wrong, please??

**Comment by joshk** [comment]
Have you followed the guide here: http://docs.travis-ci.com/user/multi-os/ and requested the feature be enabled?

**Comment by david-ragazzi** [comment]
> Have you followed the guide here: http://docs.travis-ci.com/user/multi-os/ and requested the feature be enabled?

Hmm.. I have to request this by email.. Thanks @joshk .
