### ISSUE TITLE
Unable to enable repository in Chromium

### ISSUE THREAD

**Issue by waterlink** [travis-ci/travis-ci#3500]
Occurs to me when I'm trying to enable repository for an organization (I'm owner). When I tick the switch, I see this in Chromium console: https://gist.github.com/waterlink/b2e1846a9604e7c4f292

Personal repositories work just fine.

**Comment by waterlink** [comment]
The same happens to me on Firefox.

**Comment by joshk** [comment]
Is this issue on travis-ci.org or travis-ci.com?

**Comment by waterlink** [comment]
travis-ci.org

**Comment by joshk** [comment]
Can you please go to https://github.com/settings/connections/applications/88c5b97de2dbfc50f3ac and check if 3rd Party Auth is enabled for the Travis CI OAuth application?

**Comment by waterlink** [comment]
I see. There was no access to this specific organisation. I have granted the access and will try again

**Comment by waterlink** [comment]
Yes, now it works! Many many thanks @joshk!

**Comment by waterlink** [comment]
Error is very confusing, though..

**Comment by joshk** [comment]
You are right, we are working on some changes to help improve this situation.

Great to know it is working now.
