### ISSUE TITLE
Travis architecture.

### ISSUE THREAD

**Issue by sowani** [travis-ci/travis-ci#3501]
Hi,

I am trying to understand Travis architecture. I have gone through most of the documentation available at the Travis website, collected some bits and pieces from the README.md files and some deployment information about Travis-ci.com as well. However I am unable to piece together this information as some more details are missing from my collection. For example, how WebUI works? How the information is exchanged between travis-worker and the VM used to compile project? What are the inter-dependencies of Travis components etc.

There may be some document explaining all this and that I missed it altogether. So could somebody please point me in right direction? In case such documentation is missing, what are the recommendations to learn about Travis architecture?

Thanks,
Atul.

**Comment by joshk** [comment]
Hi @sowani 

I'm sorry but we don't have this kind of documentation available right now.

I suggest reading the readmes for travis-logs, travis-hub, travis-tasks, and travis-web (which is a little sparse). One component (travis-gatekeeper) isn't opensource at the moment.

**Comment by sowani** [comment]
Hi @joshk 

I was trying to learn the Travis architecture with reference to my earlier issue (https://github.com/travis-ci/travis-ci/issues/3442). I am interested in porting various popular Open Source packages to Power8 platform. Considering the volume of packages and their dependencies, I want to make Travis-CI available locally on Power8 platform so that I can generate local P8 packages.

However I am facing a lot of hurdles such as unavailability of information on how to setup Travis-CI on my local machine. At the minimum I would want core functionality without luxury of WebUI to work in first phase. Later on I can think and try porting Web component to Power8 platform as well.

Another lacking part is understanding of Travis-CI components and their inter-dependencies. This is especially important if there are some components (e.g. travis-gatekeeper) which are not open source.

Having technical understanding of Travis internals will also help estimating feasibility of my endeavour as well as formulating strategies in case it is feasible.

By doing this, of course, I hope I am not conflicting with your business plans in any way.

Best regards,
Atul.

**Comment by joshk** [comment]
Hi @sowani 

Is there a particular reason you need to port the web component to Power8 as well?

Is Power8 required for Fortran?

To be honest @sowani, we don't have all the docs you are after as we have never had the opportunity to really put time into them. 

This is why I asked earlier if you had found a host or supplier for Power8 servers? Without demand from the community, we would not add support for another platform for which we need to support if there are no suppliers of the computing resources we need.

I guess I don't fully understand the intentions of what you are trying to achieve.

Thanks

Josh

**Comment by gerrit-power** [comment]
Hey Josh, I work with Atul.  We are basically working our way through key enterprise open source and ensuring that it is ported to the Power8 Little Endian architecture.  So, anything that is available, that customers might use, we prioritize and dig in.  So, we can probably help by generating some architectural level documentation based on how we learn a bit as we port Travis CI to Power8 LE.  We typically use Power8 as another option for servers - including anything from support for mobile apps (e.g. web servers and front ends) to back end databases and such.  We will likely also use Travis-CI as a way to support continuous integration of our changes, as well as some regression testing.  And, we hope to Dockerize it.

We and Atul will will both have access to Power8 servers, so that isn't an issue.

Any support you can provide will be helpful - but if we need to learn or create on our own, we'll dig into it.

thanks!

gerrit

**Comment by sowani** [comment]
Hi!

Referring to the Travis website and the documentation available, I have tried to piece together possible relationship(s) between prominent components. Considering my exposure to Travis, I am sure that this picture does not contain all relationships and it is highly unlikely that they are correct. For example, I am a bit confused about the exact functional boundary between travis-logs and travis-build. So here is my version of the elephant:

![travis-arch](https://cloud.githubusercontent.com/assets/11497583/6939780/83c9fdcc-d88d-11e4-94ea-314e475dfbb4.PNG)

I hope most of the important Travis components are covered in this picture, but as I said, some might still be missing. Review comments, corrections and enhancements are highly appreciated! This will help me creating the correct architecture diagram, so that it will be easy for novice to understand Travis-CI.

Thanks!

Atul.

**Comment by joshk** [comment]
@gerrit-power @sowani I think it would be best to setup a call so I can understand what you are trying to achieve with Power8.

As for the diagram, although it is on the right path, there are many things not correct, and I don't think discussing this via a GitHub issue is ideal.

Would you have time tomorrow to talk on Skype?

I'm going close this issue for now, but you can contact us at support@travis-ci.com to arrange a good time to talk.
