### ISSUE TITLE
How a language is supported by Travis-CI?

### ISSUE THREAD

**Issue by sowani** [travis-ci/travis-ci#3502]
Hi,

I am trying to understand how a programming language is supported by Travis-CI.

I understand that a YML file specifies the details such as language, compilers and execution scripts used by a project. However I would like to know what Travis does after receiving this information. What is the workflow? If I have to support a new language which is not yet in the list of Travis' supported language list, (say FORTRAN) what all I need to do/implement? Can somebody please help me understand this?

Thanks,
Atul.

**Comment by joshk** [comment]
Hi @sowani 

You can add extra languages by sending Pull Requests to travis-ci/travis-build

Two good examples are https://github.com/travis-ci/travis-build/pull/386 and https://github.com/travis-ci/travis-build/pull/406

If you are interested in adding FORTRAN you will need to also find one or two other maintainers to help with any issues which arise.

You can also find more information on Community Supported Languages here http://blog.travis-ci.com/2014-12-10-community-driven-language-support-comes-to-travis-ci/ (proper docs guide coming soon)

I'm going to close this issue for now.

Thanks

Josh
