### ISSUE TITLE
Organization missing

### ISSUE THREAD

**Issue by ddliu** [travis-ci/travis-ci#3504]
Travis-ci user name: ddliu

Missing organization: arkphp

The missing organization has been created at Github for almost a month, but I've never saw it at Travis-ci.

**Comment by joshk** [comment]
Can you please go to https://github.com/settings/connections/applications/88c5b97de2dbfc50f3ac and check if Travis CI is an authorized app for that Org?

If not, you will need to enable it and then resync your account on Travis.

**Comment by ddliu** [comment]
Yes it's not enabled, don't remember I have to do that before for other organizations.

Tried to enable and sync it just now, but without lucky. Maybe I have to wait for a few minutes?

**Comment by ddliu** [comment]
@joshk, it works now, thank you for your help!
