### ISSUE TITLE
APT source whitelist request for apt.mopidy.com

### ISSUE THREAD

**Issue by jodal** [travis-ci/travis-ci#3510]
Source line: `deb http://apt.mopidy.com/ stable main contrib non-free`
GPG key: https://apt.mopidy.com/mopidy.gpg

This plus a few whitelisted packages will hopefully enable a bunch of Mopidy-related projects to move to the new container-based build infrastructure.

Ref. discussion at https://twitter.com/travisci/status/582630587443245056

**Comment by meatballhat** [comment]
:clap: great, thank you!
