### ISSUE TITLE
Where did the apt_sources plugin go?

### ISSUE THREAD

**Issue by arr2036** [travis-ci/travis-ci#3512]
It was here yesterday...

Removing it broke all our builds... Can it come back please?

https://travis-ci.org/FreeRADIUS/freeradius-server/jobs/56440357

**Comment by sinthetix** [comment]
Hi there :) The apt_source plugin is now apt.sources. See the documentation here: http://docs.travis-ci.com/user/apt/

**Comment by arr2036** [comment]
@sinthetix yep, that did it, thanks!

**Comment by sinthetix** [comment]
No problem, happy to help. :)
