### ISSUE TITLE
Failing apt package installation in container based infrastructure does not cause build error

### ISSUE THREAD

**Issue by arr2036** [travis-ci/travis-ci#3513]
https://travis-ci.org/FreeRADIUS/freeradius-server/jobs/56440357

Because _someone_ removed the apt_sources plugin (see here https://github.com/travis-ci/travis-ci/issues/3512), the couchbase source is no longer available, which means package installation fails.

```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends install autoconf build-essential debhelper devscripts dh-make fakeroot gdb lintian pbuilder python-dev quilt libruby ruby-dev libcollectdclient-dev firebird-dev freetds-dev libcap-dev libcouchbase2-libevent libcouchbase-dev libcurl4-openssl-dev libgdbm-dev libhiredis-dev libidn11-dev libjson0 libjson0-dev libkrb5-dev libldap2-dev libmemcached-dev libmysqlclient-dev libpcap-dev libpcre3-dev libperl-dev libpq-dev libreadline-dev libsnmp-dev libssl-dev libtalloc-dev libunbound-dev libwbclient-dev libykclient-dev libyubikey-dev
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libcouchbase2-libevent
E: Unable to locate package libcouchbase-dev
```

Which causes build errors:

```
checking for rusers... /usr/bin/rusers
checking for locate... no
checking for dirname... /usr/bin/dirname
checking for grep... (cached) /bin/grep
checking for _talloc in -ltalloc... no
checking for _talloc in -ltalloc in /usr/local/lib... no
checking for _talloc in -ltalloc in /opt/lib... no
configure: WARNING: talloc library not found. Use --with-talloc-lib-dir=<path>.
configure: error: FreeRADIUS requires libtalloc
```

Would be better if the build errored out if the packages couldn't be installed...

**Comment by meatballhat** [comment]
@arr2036 Sorry about the trouble.  The `apt_sources` feature shipped as a beta last week, so I was hoping the impact would be small, but clearly this has unfairly affected you and for that I am sorry.  Have you been able to update your config to use the new `apt.sources` config structure?

**Comment by arr2036** [comment]
@meatballhat all is well now @sinthetix pointed me towards the new documentation :+1:. All is forgiven :smile: 

The immediate issue is that plugin failures should really stop the build, so there aren't spurious errors later, and that's what I raised this ticket for.

Thinking a bit more, they're really a different sort of error, almost a system or infrastructure error. The main difference between those and user errors, is they're likely transient, and make the build a good candidate for automatic rescheduling (if such a feature were ever implemented).

**Comment by BanzaiMan** [comment]
Tidying up the loose ends. If there is more to do, please open a new issue. Thanks.
