### ISSUE TITLE
Allow execution of apache utils in Docker instances

### ISSUE THREAD

**Issue by shouze** [travis-ci/travis-ci#3519]
We should be able to run the following with root privileges:
- a2enmod
- a2dismod
- a2ensite
- a2dissite

**Comment by quicksketch** [comment]
:+1:

It's difficult to set up Apache in a way similar to the non-container instances, as we need to enable rewrite and fastcgi: http://docs.travis-ci.com/user/languages/php/#Apache-%2B-PHP

**Comment by richardfullmer** [comment]
:+1:

**Comment by shouze** [comment]
ping @travis-ci, any news about this one?

**Comment by cjmurphy42** [comment]
:+1:

**Comment by niels-nijens** [comment]
For those of you trying to run Apache2 with fastcgi / PHP-FPM in the container-based infrastructure.
I've created a gist with a working solution / workaround: https://gist.github.com/niels-nijens/548e0c4fe80c3c79ca30

**Comment by BanzaiMan** [comment]
Sorry for the long delay.

Root privileges are not going to be granted for these (or any) executable for container-base builds. We are happy to include @niels-nijens's workaround for our docs. PR should go to https://github.com/travis-ci/docs-travis-ci-com/.

I'm closing this.
