### ISSUE TITLE
Some builds being auto-opted-in to container-based builds?

### ISSUE THREAD

**Issue by craigcitro** [travis-ci/travis-ci#3521]
i'm seeing reports from users (eg craigcitro/r-travis#151) of users being automatically opted in to the container-based infrastructure. 

i don't see any new updates about this on the blog, but there seem to be some plans afoot, eg [this docs update](https://github.com/travis-ci/docs-travis-ci-com/commit/790fc19a54dd87c6c32b970205e09e691da4a213).

is this done by literally detecting `sudo` in the `.travis.yml`? if so, that seems like it won't work: lots of commands might end up using superuser privs without explicitly calling `sudo`. this is the case for virtually all R users of travis (either via r-travis or with native R support), so if you're making this change, it'd be great to have a heads-up.

**Comment by meatballhat** [comment]
Hi @craigcitro, thanks for the report.  The automatic detection is definitely not exhaustive, as you've pointed out, although explicitly enabling sudo is fairly straightforward (by adding `sudo: required`, or really any truthy value).  This is a change we've been slowly rolling out, with more projects being affected as we move the cutoff date as discussed here: http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/.

We try to communicate such changes in advance, and to notify users via multiple channels.  In this case we're finding that more up-front communication probably should have happened.  I'm sorry about the negative impact.

**Comment by craigcitro** [comment]
thanks @meatballhat -- that explains a lot.

one more related question: for R support in travis, we currently require the use of `sudo`. we're working on changing this, but currently we're not getting much feedback on how to proceed (see #3290). any chance someone could pipe in on that ticket and let us know if we're headed in the right direction?
