### ISSUE TITLE
APT whitelist request for cross-compiling build targeting Windows platform and Ubuntu 32-bit arch.

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#3522]
List of packages for targeting Windows platform:
a) Windows 32-bit:
```
gcc-mingw-w64-i686
g++-mingw-w64-i686
binutils-mingw-w64-i686
```

b) Windows 64-bit:
```
gcc-mingw-w64-x86-64
g++-mingw-w64-x86-64
binutils-mingw-w64-x86-64
```

List of packages for targeting Ubuntu 32-bit arch:
```
libxrandr-dev:i386
libglapi-mesa:i386
libgl1-mesa-glx:i386
libgl1-mesa-dev:i386
libxext-dev:i386
libxrender-dev:i386
```

EDIT: we also require ```libasound2-dev``` to be white listed.

This request is for building [Urho3D](http://urho3d.github.io/) cross-platform public/open-source project.

**Comment by weitjong** [comment]
And for completeness sake, we also need the ```libasound2-dev``` to be white listed. This particular package has been requested by others too.

**Comment by weitjong** [comment]
Thank you!!

**Comment by meatballhat** [comment]
@weitjong :metal: :smiley_cat: :heart:

**Comment by weitjong** [comment]
I am not able to migrate our project CI build to container-based infra because I have forgotten to also request for ```g++-multilib``` to be whitelisted. This package has been requested by others too.
https://github.com/travis-ci/travis-ci/issues/3583
https://github.com/travis-ci/travis-ci/issues/3595
I just wonder whether the whitelisting review could be prioritize as I can imagine a number of cross-compiling project may need this. Thanks.
