### ISSUE TITLE
The cogwheel icon is not displaying in /profile/{user}

### ISSUE THREAD

**Issue by Zarthus** [travis-ci/travis-ci#3523]
There is an invisible piece of HTML between enabling a repository and the actual repository that directs you to the settings.

The piece of HTML to look for his here
```
<a id="ember1547" class="ember-view profile-settings" href="/USERNAME_HERE/REPOSITORY_HERE/settings" title="Repository settings"><span class="icon icon--cog"></span></a>
```

This occurs on any https://travis-ci.org/profile/PROFILE_NAME_HERE url

Chrome Debugger image:

![image](http://i.imgur.com/WXQtWFC.png)

This issue is tested on chrome 42.0.2311.60 beta-m (64-bit), altough if it is what I think it is then this would exist on all browsers. (On Windows 7)

**Comment by joshk** [comment]
Thanks for reporting this, we will look into this shortly.

**Comment by Zarthus** [comment]
Seems like this was fixed at https://github.com/travis-ci/travis-web/commit/ac05a6d19aa843614e6a1831bef35ea0c275626c and it is working for me again.

To my knowledge, I think this issue is resolved. Cheers! (I'll leave the issue open in case something else still needed to be done - I don't want to prematurely close it. If all is okay though - sweet!)

**Comment by joshk** [comment]
:trophy:
