### ISSUE TITLE
small display error showing Node.js 0.1 instead of 0.10

### ISSUE THREAD

**Issue by lookfirst** [travis-ci/travis-ci#3525]
screenshot: http://take.ms/CJKO4

**Comment by BanzaiMan** [comment]
Does this change if you specify `'0.10'` in `.travis.yml`?

**Comment by lookfirst** [comment]
Yes.

https://github.com/lookfirst/systemjs-seed/blob/master/.travis.yml#L6
https://travis-ci.org/lookfirst/systemjs-seed

So, now we know where the loss is. Still means there is a display issue though.

**Comment by BanzaiMan** [comment]
The loss of information happens on YAML processing. The YAML specification turns `0.10` (in the bare) into a float `0.1`, which will be used later on. (`'0.10'` is a string, so there is no loss.)

We can hack around it (and we do, for choosing the Node.js runtime), I guess, but there will be no way to tell the difference if versions `0.1` and `0.10` are indeed different. (This is not currently the case with Node.js, but it can easily happen.)

**Comment by lookfirst** [comment]
As a developer, I fully understand what the issue is. :smile:
As an end user, I was surprised to see `0.1` on a web page for NodeJS versions.

I guess you guys (Travis) need to decide who you want to placate more. :lollipop:

**Comment by BanzaiMan** [comment]
Is there anything to do here?

**Comment by BanzaiMan** [comment]
Paging @drogus @joshk

**Comment by roidrage** [comment]
As this restriction is documented, I think we can close this issue.
