### ISSUE TITLE
Sauce Connect tunnel doesn't close if a build times out

### ISSUE THREAD

**Issue by vr2262** [travis-ci/travis-ci#3526]
See this log:

https://travis-ci.org/dokomo-sauce-matrix/dokomoforms/jobs/56594346

A continuation of #3333

**Comment by tristanbes** [comment]
+1 it's annoying since it blocks futher builds when reaching the tunnel limit on saucelabs.

**Comment by BanzaiMan** [comment]
We updated Sauce Connect to 4.3.11 recently. Is this still a problem?

**Comment by vr2262** [comment]
I assume it is since the problem was that this function was not getting called: https://github.com/travis-ci/travis-build/blob/cebf05126e4e7bb8c472687937c04f716821e663/lib/travis/build/addons/sauce_connect/templates/sauce_connect.sh#L70-L92

I will fire off a build to check.

**Comment by vr2262** [comment]
Yes, it is still a problem:

https://travis-ci.org/dokomo-sauce-matrix/dokomoforms/builds/77681934

Builds 15-19 time out without closing the Sauce Connect tunnel, so build 20 (and so on) can't open new tunnels and fail.

**Comment by vr2262** [comment]
It looks like closing the Sauce Connect tunnel is supposed to happen here:

https://github.com/travis-ci/travis-build/blob/cebf05126e4e7bb8c472687937c04f716821e663/lib/travis/build/addons/sauce_connect.rb#L37-L42

I suppose `after_after_script` doesn't happen in the event of a time out.

**Comment by BanzaiMan** [comment]
Ah, when there is no output for a pre-defined limit? I overlooked this crucial detail.

This is true. When that happens, no cleanup can be performed. I think there is a previous issue about this, but I can't find it at the moment.

**Comment by vr2262** [comment]
I found #4221 which isn't quite the same but is related.

**Comment by BanzaiMan** [comment]
@vr2262 Thanks for finding that issue! I think this is the same general issue: Better cleanup after timeout (with `after_*` phases). As such, I'm going to close this as a duplicate.
