### ISSUE TITLE
APT source whitelist request for kubuntu-ppa/backports

### ISSUE THREAD

**Issue by dagar** [travis-ci/travis-ci#3530]
Please add ppa:kubuntu-ppa/backports. This is a convenient way to get access to a slightly newer cmake that's compatible with llvm.

**Comment by chrisdembia** [comment]
+1

**Comment by dawagner** [comment]
:+1: :)

**Comment by dagar** [comment]
Thanks!

**Comment by meatballhat** [comment]
:metal: :smiley_cat:

**Comment by chrisdembia** [comment]
Thank youu

**Comment by dawagner** [comment]
Thanks indeed :)
