### ISSUE TITLE
PHP VM: mtime changes don't seem to happen correctly

### ISSUE THREAD

**Issue by narcoticfresh** [travis-ci/travis-ci#3532]
Hi guys..

I hope this is the correct place for my problem. We have a bunch of PHPUnit tests for our build. Now, they run through (without errors) locally but fail on Travis currently.

The failing test (and all behind it) relies on mtime (so unix file modification timestamp) changes that produces cache invalidation. Only if the cache gets invalidated, the test succeeds.

Investigating, we found out (see [this job](https://travis-ci.org/libgraviton/graviton/jobs/56689721)) that inside the PHP VM the mtime of the files don't get updated.

We open the file, write something to it and close it again. This normally *must* change the file mtime - but not on the PHP VM on Travis.

There seems to be nothing we can do about that, it seems to be a wrong behavior inside the VM..
Could there any cause to this? Does the app maybe run on a `nomtime` mount (mount options)? Any other special stuff that could produce this behavior?

Thanks for any help!

**Comment by BanzaiMan** [comment]
I am not sure if I understand the problem correctly. The filesystems we use do have mtime updated.

I ran a short experiment to verify this.

See https://travis-ci.org/BanzaiMan/travis_production_test/builds/56732032#L104 vs https://travis-ci.org/BanzaiMan/travis_production_test/builds/56732032#L114 with [`touch file1` in between](https://travis-ci.org/BanzaiMan/travis_production_test/builds/56732032#L109).

I am not familiar with your test suite, so please elaborate how you determined that mtime didn't change.

**Comment by narcoticfresh** [comment]
Hi @BanzaiMan 

The experiment you linked seems to work with plain `touch` on the command line.. That's great..

I investigated that further and it seems it's a blocking issue. Meaning that our "touch" (done as fopen/fwrite/fclose in PHP) doesn't happen strictly before the cache check as it's non-blocking. Locally in our environments (Ubuntu LTS / Mac OSX) this never seems to be a problem; inside the Travis VM this fails.

Using the PHP function `touch()` would solve that - but that function is known to be very slow (as it completely blocks); we've seen it's slower by a factor of 8000 (yes..).. So that is not an option for us really..

I'm not sure if you can do anything about it.. We'll try to find another approach (in PHP) to solve our issue..

Would be just interesting to know why it works locally and the Travis VM behaves differently.. I don't think you have an idea what could cause the different behavior?

**Comment by BanzaiMan** [comment]
Can PHP call the external shell to touch the file? (Or is it what the `touch()` function does?)

We can spin up a debug VM for you if you want to troubleshoot further. Email support@travis-ci.com if you want that.

**Comment by BanzaiMan** [comment]
Is there anything for us to investigate?

**Comment by narcoticfresh** [comment]
Hi guys.. Sorry for the inactivity.. :-) 
We still needed to workaround, but we were also unable to provide a testcase.. So let's close it then
