### ISSUE TITLE
GHC 7.10 is parsed as GHC 7.1

### ISSUE THREAD

**Issue by hellerve** [travis-ci/travis-ci#3539]
[In a project of mine](https://github.com/hellerve/unlambda/blob/master/.travis.yml) where I use Haskell/Travis, I recently added GHC 7.10 as build target. It does not seem to be available yet. Fair enough. [But the build system parses it as if I had specified version 7.1 instead](https://travis-ci.org/hellerve/unlambda/builds/56743309), which may not be what you guys want.

Cheers

**Comment by BanzaiMan** [comment]
This is a well-known issue with YAML parsing. Please put `7.10` in quotes (i.e., `'7.10'`) so that YAML parser will recognize it as a string, rather than a float.

**Comment by hellerve** [comment]
Thanks for the quick answer! Should have read the specs first, huh? ;)

**Comment by BanzaiMan** [comment]
Well, this is also a common mistake with Node.js 0.10 and Perl 5.20. In that sense, it _might_ make sense to do the same for GHC 7.10.
