### ISSUE TITLE
APT whitelist request for libgeos-3.3.3 and libgeos++-dev

### ISSUE THREAD

**Issue by pnorman** [travis-ci/travis-ci#3553]
more [osm2pgsql dependencies](https://github.com/openstreetmap/osm2pgsql/blob/acc82b94c0853d867aa18a158d8708bbfa985727/.travis.yml#L28)

**Comment by meatballhat** [comment]
@pnorman hey there!  It looks like this requires the `ppa:boost-latest/ppa` PPA, so we'll have to get that reviewed first.  It also looks like you're depending on conditional package installation, which unfortunately is not supported by the `apt` addon, but we're working on a solution.

**Comment by pnorman** [comment]
ah, deps on #3554

**Comment by pnorman** [comment]
I didn't realize libgeos-3.3.3 was from boost-latest, so I'll probably change it over to the OS libgeos, or add the postgresql apt and get geos 3.4.
