### ISSUE TITLE
APT source whitelist request for postgresql

### ISSUE THREAD

**Issue by pnorman** [travis-ci/travis-ci#3555]
https://wiki.postgresql.org/wiki/Apt

`deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main`

Key is at https://www.postgresql.org/media/keys/ACCC4CF8.asc

Not just useful for PostgreSQL as it also has some other geo-related packages for PostGIS

**Comment by meatballhat** [comment]
@pnorman This repo is already available in all build environments :metal: :smiley_cat:
