### ISSUE TITLE
APT whitelist request for libxtst-dev

### ISSUE THREAD

**Issue by DamonOehlman** [travis-ci/travis-ci#3556]
Looking into getting octalmage/robotjs using Travis for test automation (see discussion on octalmage/robotjs#17) and in progress testing branch here: 

https://github.com/DamonOehlman/robotjs/tree/testing

**Comment by DamonOehlman** [comment]
Thanks heaps :)

**Comment by meatballhat** [comment]
:metal: :smiley_cat:
