### ISSUE TITLE
APT whitelist request for libgcrypt11-dev:i386, libssl-dev:i386, zlib1g-dev:i386 and linux-libc-dev:i386

### ISSUE THREAD

**Issue by alamaison** [travis-ci/travis-ci#3557]
I'm cross-compiling libssh2, which fails in the container-based build system because the 32-bit counterparts are disallowed.  The 64-bit versions of these packages are in the whitelist already.

https://travis-ci.org/alamaison/libssh2/jobs/56865682

**Comment by SethTisue** [comment]
+1. I could use this for building a haxe/neko based project.
