### ISSUE TITLE
APT source whitelist request for ghc

### ISSUE THREAD

**Issue by emwap** [travis-ci/travis-ci#3560]
ppa:hvr/ghc contains several versions of the GHC Haskell compiler.

This PPA is used by many Haskell projects, as per instructions in https://github.com/hvr/multi-ghc-travis 
Adding it would make it possible to test with many GHC version in the containerized environment.

/cc @hvr

**Comment by hvr** [comment]
:+1:

**Comment by emwap** [comment]
@BanzaiMan, shouldn't this have the apt-source-whitelist label?

**Comment by meatballhat** [comment]
@emwap Yep!  Fixed, and reviewing right now :smiley_cat:
