### ISSUE TITLE
Cache download takes a long time (or fails)

### ISSUE THREAD

**Issue by degemer** [travis-ci/travis-ci#3566]
Hey,

We recently configured our builds to use the cache associated with the container-based infrastructure, and it's really nice, but sometimes the cache download takes quite a long time (> 200s for a cache of ~30MB), or fails the build (10 min without output, related to https://github.com/travis-ci/travis-ci/issues/2214).

Here are some examples:
- https://travis-ci.org/DataDog/dd-agent/jobs/56912450 (no output for 10min)
- https://travis-ci.org/DataDog/dd-agent/jobs/56952829#L106 (380s)
- https://travis-ci.org/DataDog/dd-agent/jobs/56952839#L105 (220s)

It's really surprising since as I said the cache size is only 30MB.
Let me know if I can do anything to help!

**Comment by BanzaiMan** [comment]
Could you try it with the following additional flags?

```yaml
cache:
  debug: true
  edge: true
  ⋮
```

**Comment by degemer** [comment]
Sure, here are two example with debug enabled:
- https://travis-ci.org/DataDog/dd-agent/jobs/57060702#L180
- https://travis-ci.org/DataDog/dd-agent/jobs/57060729#L181

**Comment by BanzaiMan** [comment]
Thanks. One more thing. Could you dump the content of `$HOME/.casher/fetch.log` in `before_install`?

**Comment by degemer** [comment]
Yep, here are the results (it seems to only happen between during the "working day" EDT, I tested before at 10h and last weekend, no problem):
- https://travis-ci.org/DataDog/dd-agent/jobs/57357114#L180
- https://travis-ci.org/DataDog/dd-agent/jobs/57357113#L180
- https://travis-ci.org/DataDog/dd-agent/jobs/57357110#L180

**Comment by degemer** [comment]
We are still seeing this problem sometimes, for instance https://travis-ci.org/DataDog/dd-agent/jobs/58483397#L181, so do you have any update/fix ?
Thanks!

**Comment by degemer** [comment]
The casher timeout (https://github.com/travis-ci/casher/pull/10) solved our problems (rebuilding from scratch is a lot better than failing), thanks!
