### ISSUE TITLE
NSSearchPathDirectory.DocumentDirectory returns bogus path

### ISSUE THREAD

**Issue by juliantejera** [travis-ci/travis-ci#3567]
I've been trying to unit test an iOS project which uses Core Data. I'm using the usual Core Data stack which is generated by Xcode. The line failing is the following: 

    lazy var applicationDocumentsDirectory: NSURL = {
        let urls = NSFileManager.defaultManager().URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask)
        return urls[urls.count-1] as NSURL
    }()

On my mac it returns: `file:///Users/juliantejera/Library/Developer/CoreSimulator/Devices/{UNIQUE ID}/data/Containers/Data/Application/{UNIQUE ID}/Documents/`

On travis: `file:///var/empty/Documents/`

Therefore my NSManagedObjectContext cannot be created and my app crashes. Any solutions?

More details from the log: 

Failed to query the list of test cases in the test bundle: 2015-04-06 14:43:03.911 sim[3587:303] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/sim: No simulator devices appear to be running.  Setting data directories to /var/empty.
2015-04-06 14:43:03.915 sim[3587:303] DYLD_INSERT_LIBRARIES contains possible bad values.  Caller beware: /usr/local/Cellar/xctool/0.2.3/libexec/lib/otest-query-lib-ios.dylib

**Comment by juliantejera** [comment]
After a week I was finally able to solve my problem by using a NSInMemoryStoreType for the NSPersistentStoreCoordinator whilst running unit tests. 

```swift 
var isRunningUnitTests = NSClassFromString("XCTest") != nil
var storeType = isRunningUnitTests ? NSInMemoryStoreType : NSSQLiteStoreType
```

Basically you cannot manipulate files while running unit tests when you use xctool because the NSBundle.mainBundle() is set to file:///var/empty

**Comment by BanzaiMan** [comment]
@juliantejera Hello. Thanks for the update. Is this is an `xctool` issue, or a Travis issue?

**Comment by juliantejera** [comment]
After a lot of inspection I was able to reproduce the bug on my machine by downloading xctool and running my travis script. The project worked without a hitch with xcodebuild which confirms xctool has a bug and not travis. So this can be closed. @banzaiman
