### ISSUE TITLE
APT whitelist request for python-pip, python-virtualenv, libevent-dev

### ISSUE THREAD

**Issue by andrewgaul** [travis-ci/travis-ci#3575]
Needed to run S3Proxy s3-tests:

https://travis-ci.org/andrewgaul/s3proxy

**Comment by stof** [comment]
pip is already available by default.

**Comment by andrewgaul** [comment]
@stof I want to address this error which fails my build later:

```
Installing APT Packages (BETA)
Disallowing packages: python-pip, python-virtualenv, libevent-dev
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
```

https://github.com/andrewgaul/s3proxy/blob/master/.travis.yml

**Comment by mfogel** [comment]
+1, and I'd also request to add `virtualenvwrapper` to the apt whitelist.

The pattern I've been following is to never use pip in a system-wide context - only use it within a virtualenv. Without python-virtualenv installed, I don't believe this is possible.

**Comment by andrewgaul** [comment]
@meatballhat Could you also add libevent-dev?
