### ISSUE TITLE
sudo add-apt-repository ... failed

### ISSUE THREAD

**Issue by vnijs** [travis-ci/travis-ci#3576]
@craigcitro, @eddelbuettel and @hadley

I'm getting the following build error on travis. From the error message it seems this is not something in my code because the error occurs even before installing any packages. 

The command "sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -cs)/"" failed and exited with 1 during .
Your build has been stopped.

Full log:

Using worker: worker-linux-docker-1ea58431.prod.travis-ci.org:travis-linux-4
system_info
Build system information
Build language: r
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
git.checkout
2.09s$ git clone --depth=50 --branch=master git://github.com/vnijs/radiant.git vnijs/radiant
Cloning into 'vnijs/radiant'...
remote: Counting objects: 1840, done.
remote: Compressing objects: 100% (977/977), done.
remote: Total 1840 (delta 1077), reused 1513 (delta 851), pack-reused 0
Receiving objects: 100% (1840/1840), 22.82 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1077/1077), done.
Checking connectivity... done.
$ cd vnijs/radiant
$ git checkout -qf 0841b1a7f03cfbfe3fe306cf7e38ec0492ff00a6
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
R for Travis-CI is not officially supported, but is community maintained.
Please file any issues using the following link
  https://github.com/travis-ci/travis-ci/issues/new?labels=community:r
and mention @craigcitro, @eddelbuettel and @hadley in the issue
Installing R
0.06s$ sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -cs)/"
sudo: must be setuid root
The command "sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -cs)/"" failed and exited with 1 during .
Your build has been stopped.

**Comment by craigcitro** [comment]
hi @vnijs,

did you just create the repo? if so, you need to add `sudo: required` to the `.travis.yml`; the travis folks have just [made a change](http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/) that makes this necessary on new repositories.

i'll work on getting some doc updates shortly.

**Comment by vnijs** [comment]
Thanks for the quick reply! I have been using Travis for 21 days according to the log. I did change my user-name and used travis on different branches in the same repo. I am using the new structure for [`.travis.yml`](https://github.com/vnijs/radiant/blob/master/.travis.yml)

Regardless, I added `sudo: required` as suggested and the build is running along nicely now. Thanks @craigcitro

**Comment by eddelbuettel** [comment]
Interesting.  I had a pull request fail for the same reason, which now makes sense: "new user", freshly forked.  

Total pain in the arse, though.   And am I reading this correctly that you cannot possibly adapt `travis-tool.sh` because one need a new top-level declaration?   Just glorious...

That said, the [apt addon](http://docs.travis-ci.com/user/apt/) looks good, and a move towards Docker is of course even better,   So with that maybe we take the good with the bad?

**Comment by BanzaiMan** [comment]
Sorry for the inconvenience. Newly activated repositories are now sent to the Docker queue (http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/). For R repositories, it means you need to add `sudo: required` explicitly.

**Comment by eddelbuettel** [comment]
@craigcitro:

Travis CI is completely broken right now for new repos containing R and C++11.  I just wasted six commits on getting a working `.travis.yml`, and I failed miserably.  I went all the way up up into switching to my repo's copy of `travis-tool.sh` with hardwired installation of `g++-4.9`  and it still failed.   Sadly we are also not showing the build log.  

Which is a bug.  Maybe one of (hi @hadley) actually needs to go in and make the `${PKGNAME}.Rcheck/00install.out` file visible at failure.

**Comment by eddelbuettel** [comment]
Hi @BanzaiMan :  been there, done that, still swearing.

See the repo https://github.com/eddelbuettel/rcpptoml/ if you want to test locally.  Essentially one function exported to R, but one that builds on an included C++11 header file.

Not. A. Snowflake's. Chance. In. Hell. To. Get. It. Building.

I am a co-author of r-travis, and it stumped me.  It only passed `R CMD check` after ... I took out all the code.  A sad day.

**Comment by craigcitro** [comment]
@eddelbuettel failing to dump the build log on failure is currently not happening for native R builds, because of some bad exit code handling on my part. i just haven't had a minute to roll a fix.

however, i'm surprised it's not working with `travis-tool.sh` -- is there a log that isn't being printed by `dump_logs`?

**Comment by eddelbuettel** [comment]
No. I just kept silently failing on 'is the package installable' and tried various tricks to get a newer g++-4.9, but without luck.

I have around half-a-dozen packages which worked with the exact same setup. So this failure is rather frustrating.  So Travis is useless for me on new(er) projects it seems.  Kinda sad.

**Comment by craigcitro** [comment]
@eddelbuettel can you point me to the repo? if nothing else, i want to confirm where we do/don't spit enough debug info.

**Comment by eddelbuettel** [comment]
Sure.  It is the faily new [RcppToml](https://github.com/eddelbuettel/rcpptoml) that I worked on for the past week -- hence a new repo.  I only added `.travis.yml` this morning and if you roll back the last few commits you see what happens.

Anyway, in each an every case I bomb on 

    * checking whether package ‘RcppToml’ can be installed ... 

which I can replicate here if I force `g++-4.6`.  I did not succeed in letting Travis use a newer compiler.

As this works with other repos, I suspect an interaction with the new containers.  But this is now beyond me, and I turned Travis off for this repo.

**Comment by dselivanov** [comment]
Is there any way use travis without sudo for R packages which need C++11?

**Comment by eddelbuettel** [comment]
@dselivanov I think you are hijacking the wrong thread -- but for what it is worth I prefer Travis in the old mode with `sudo`, and I have a few R packages where I do turn on C++11.  One example is [RcppTOML and this .travis.yml](https://github.com/eddelbuettel/rcpptoml/blob/master/.travis.yml) which also installs a newer `g++`.  _But_ if you look at [this .travis.yml of the underlying cpptoml package](https://github.com/skystrife/cpptoml/blob/master/.travis.yml) you see C++11 used without sudo.

**Comment by dselivanov** [comment]
@eddelbuettel , thanks a lot, already borrowed file from `RcppTOML`.

**Comment by BanzaiMan** [comment]
I think we can close this one.
