### ISSUE TITLE
APT whitelist request for llvm-3.5, llvm-3.5-dev, llvm-3.6, llvm-3.6-dev, llvm-3.7, llvm-3.7-dev

### ISSUE THREAD

**Issue by redstar** [travis-ci/travis-ci#3580]
These packages are provided by the already white-listed sources `llvm-toolchain-precise`, `llvm-toolchain-precise-3.5` and `llvm-toolchain-precise-3.6`.

**Comment by meatballhat** [comment]
Looks like I got these by way of another request :metal: :smiley_cat: https://github.com/travis-ci/apt-package-whitelist/commit/6bd96aa06c785f529a61def5a7243fa4d4aed82d
