### ISSUE TITLE
APT whitelist request for g++-multilib

### ISSUE THREAD

**Issue by grtlr** [travis-ci/travis-ci#3583]

**Comment by grtlr** [comment]
Apparently neovim/neovim is not dependent on g++-multilib anymore, I will still leave this open because of #3595.

**Comment by andyli** [comment]
Our [haxe](https://github.com/HaxeFoundation/haxe/) and [hxcpp](https://github.com/HaxeFoundation/hxcpp/) builds also depend on *g++-multilib*.

**Comment by weitjong** [comment]
+1

**Comment by weitjong** [comment]
Many thanks.

**Comment by meatballhat** [comment]
:metal: :smiley_cat:
