### ISSUE TITLE
APT whitelist request for libstdc++-4.8-dev

### ISSUE THREAD

**Issue by aaronpuchert** [travis-ci/travis-ci#3585]
This is required for a decent C++11 support. Updating compilers and libraries for all containers would be nice, but will apparently not happen soon. (#1379)

**Comment by aaronpuchert** [comment]
For an example, see https://travis-ci.org/aaronpuchert/logic/builds/57052312#L89.

**Comment by aaronpuchert** [comment]
It seems this gets installed automatically with the corresponding GCC. But since `libstdc++` is also used with Clang, it might make sense to install it separately.

**Comment by meatballhat** [comment]
@aaronpuchert I'm not finding `libstdc++-4.8-dev` in the current sources.  Does this request also require the addition of an APT source?

**Comment by aaronpuchert** [comment]
I used it before via `sudo apt-get` and apparently it was there: https://travis-ci.org/aaronpuchert/logic/builds/48407510#L130. I can't find it in the package list of [ubuntu-toolchain-r/test](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test), though.

**Comment by meatballhat** [comment]
@aaronpuchert ah, I didn't realize this was coming from ubuntu-toolchain-r.  I'll try again with that source added.

**Comment by meatballhat** [comment]
@aaronpuchert found 'em

**Comment by aaronpuchert** [comment]
Nice, thank you!
