### ISSUE TITLE
Under certain circumstances, build is marked a failure for no apparent reason

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3586]
This build: https://travis-ci.org/ap--/python-seabreeze/builds/57058699 comes from [this `.travis.yml`](https://github.com/ap--/python-seabreeze/blob/b4cfd3a24a30f1cbb2c947cf0771a4bf22a09a66/.travis.yml).

Notice that there is only one command, `echo "done."`, in `script`, but for some reason it is marked a failure.

A consequence of this failure is that the deployment is never triggered, even though this build _is_ a tagged build.

Curiously, https://travis-ci.org/ap--/python-seabreeze/builds/57058682 is a build with the same commit, but a push build, and it is marked a success.

**Comment by BanzaiMan** [comment]
I have not been able to come up with a reasonable minimal example to show this problem yet.

**Comment by ribasushi** [comment]
@BanzaiMan Note that the [build_wheel script](https://github.com/ap--/python-seabreeze/blob/b4cfd3a24a30f1cbb2c947cf0771a4bf22a09a66/travis/build_wheel.sh) is sourced (not executed in a subshell), and that it contains an explicit [set -e](https://github.com/ap--/python-seabreeze/blob/b4cfd3a24a30f1cbb2c947cf0771a4bf22a09a66/travis/build_wheel.sh#L2) which persists for the rest of the build.

This is almost certainly a variant of https://github.com/travis-ci/travis-ci/issues/891#issuecomment-32318632

**Comment by ap--** [comment]
Yes It's the set -e. just created a minimal testcase: https://github.com/ap--/travis-deploy-bug

https://travis-ci.org/ap--/travis-deploy-bug/builds/57146008 works (push build).
https://travis-ci.org/ap--/travis-deploy-bug/builds/57146018 fails (tag build).

**Comment by BanzaiMan** [comment]
I am closing this. `test -e` is not encouraged, because some critical functionalities of our build script relies on commands not killing the script itself.

**Comment by amadornimbis** [comment]
>I am closing this. test -e is not encouraged, because some critical functionalities of our build script relies on commands not killing the script itself.

Is usage of `set -e` discouraged everywhere? If this is the case then it looks like the docs linked below need to be updated, because they suggest the use `set -ev`.
https://docs.travis-ci.com/user/customizing-the-build#Implementing-Complex-Build-Steps
