### ISSUE TITLE
[Wishlist] Ability to access allowed_failure status from within a job

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#3588]
It would be rather convenient to have `TRAVIS_ALLOWFAIL=true` or something like this in the environment. This way one can decide whether to run more "adventurous" tests or not. Currently I am doing this by adding an envvar to each part of my matrix I marked as allowfail, in a rather redundant manner.

Thanks!

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-scheduler/pull/60
https://github.com/travis-ci/travis-build/pull/937

**Comment by ribasushi** [comment]
This seems to have been implemented, and documented in https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

Thanks!
