### ISSUE TITLE
I can not build my C# Project

### ISSUE THREAD

**Issue by fipso** [travis-ci/travis-ci#3594]
Hello,
I tried to build my C# Project, but it is not working.
I am using the XNA Framework 4.0.

I got this error: http://pastebin.com/cDSKEzt7

**Comment by simi** [comment]
I found this https://travis-ci.org/fipso/Epic-Space-Game.

Travis CI is using linux environment (Mono for .NET). Are you sure you can use XNA Framework with Mono?

**Comment by fipso** [comment]
Hi,
There is something called MonoGame which supports XNA Framework: https://github.com/mono/MonoGame
But think Travis CI does not use MonoGame.
I am new to Travis CI, is there a way that i can install the Dependencies manually ?

**Comment by Joshua-Anderson** [comment]
It looks like xbuild can't find the monogame libraries, have you added the monogame nuget packages to your solution?

**Comment by fipso** [comment]
No, how can i do that ?

**Comment by fipso** [comment]
OK, now i added : MonoGame , MonoGame.Binaries and MonoGame.ContentProcessors.
But it says: All packages listed in packages.config are already installed.

**Comment by Joshua-Anderson** [comment]
I think you want the package `MonoGame.Framework.Linux`. How are you adding the nuget packages?

**Comment by fipso** [comment]
In Visual Studio i used the packet manager console to add the package.
But in the Build log at Travis CI it sad : All packages listed in packages.config are already installed.
I think the files xbuild needs are not in the MonoGame.Framework.Linux package. But on windows i only installed the MonoGame SDK and it is working.

**Comment by Joshua-Anderson** [comment]
What build are you referencing where this happens, your builds that I see don't show nuget even attempting to install anything?

**Comment by fipso** [comment]
Yes, now i use the way with the packages.config. Look again at my latest log.

**Comment by Joshua-Anderson** [comment]
I'm not sure at this point exactly what is wrong, but I don't think that your solution is pointing to the version of monogame that nuget is installing. @akeoplinger might know more than me on the subject.

**Comment by fipso** [comment]
Ok, thanks
