### ISSUE TITLE
APT whitelist request for clustalw

### ISSUE THREAD

**Issue by peterjc** [travis-ci/travis-ci#3599]
The ``clustalw`` package is one of several command line tools Biopython has wrapper code for, and we therefore would like to have it installed for testing that wrapper code.

We currently do this with ``sudo apt-get install clustalw`` etc, see https://github.com/biopython/biopython/blob/master/.travis.yml - but would like to switch to the new container architecture as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

I have tried this on a branch, e.g. https://travis-ci.org/peterjc/biopython/jobs/56862415

```
Installing APT Packages (BETA)

Disallowing packages: clustalw, clustalo, muscle, mafft, probcons, wise, emboss, samtools, bwa

If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
```

(I would like to have `` clustalo``, ``muscle``, ``mafft``, ``probcons``, ``wise``, ``emboss``, ``samtools``, ``bwa`` all white listed too, but am happy to file issues for each of them - some are quite large and complex packages)

**Comment by peterjc** [comment]
Thank you!

**Comment by meatballhat** [comment]
:metal: :smiley_cat:

**Comment by peterjc** [comment]
Cross reference new request for xenial,

https://travis-ci.community/t/apt-package-safelist-request-clustalw-clustalo-muscle-mafft-probcons-wise-emboss-samtools-bwa/9387
