### ISSUE TITLE
APT whitelist request for libgflags-dev and libgflags

### ISSUE THREAD

**Issue by adamretter** [travis-ci/travis-ci#3609]
Required for building RocksDB https://github.com/facebook/rocksdb

**Comment by meatballhat** [comment]
@adamretter It looks like these are currently being installed with `dpkg` (?)  https://github.com/facebook/rocksdb/blob/6059bdf86a9cedb029be8d14c5b4c8b17bea6dfa/.travis.yml#L11-L14  Do you know if these debs are available in an APT repo somewhere?

**Comment by adamretter** [comment]
@meatballhat I think they are just in the Ubuntu repo now? http://packages.ubuntu.com/trusty/libgflags-dev

**Comment by meatballhat** [comment]
@adamretter if these aren't available in a backports repo or PPA somewhere, then it'll have to wait for trusty to land :crying_cat_face:

**Comment by adamretter** [comment]
@meatballhat Yeah only seems to be available in a repo for trusty and onwards. Any chance of getting access to the travis beta on trusty?

**Comment by BanzaiMan** [comment]
@adamretter Please email support@travis-ci.com with details.

I'm going to close this for now.

**Comment by jmswen** [comment]
@BanzaiMan I have the same issue.  We're trying to migrate from the old Travis infrastructure to the new container-based infrastructure.  According to the whitelist (https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise), libgflags-dev should be available in the container-based Precise environment, but I can see from my build logs that there's an error locating libgflags-dev: https://gist.github.com/jmswen/89c2dee6413d155b41b6#file-configure-sh-L405
