### ISSUE TITLE
APT whitelist request for liblua5.2-dev

### ISSUE THREAD

**Issue by chfoo** [travis-ci/travis-ci#3612]
I would like `liblua5.2-dev` so I can test lua scripting support in the container setup. Thanks!

**Comment by chfoo** [comment]
Looks like there might be a typo, `liblua5.1-0-dev` exists, but the 5.2 version is called `liblua5.2-dev` (without the `-0-`).

**Comment by meatballhat** [comment]
Oh goodness!  fixing...

**Comment by meatballhat** [comment]
@chfoo on second look, I don't see `liblua5.2-0-dev` in the default sources.  Is there an APT source we need to add as well?

``` bash
~$ sudo apt-cache search liblua5 | awk '/^liblua5\.2/ { print $1 }'
liblua5.2-0
liblua5.2-0-dbg
liblua5.2-dev
```

**Comment by chfoo** [comment]
@meatballhat I'm looking at the ubuntu-precise whitelist and it has `liblua5.2-0-dev` but it should be `liblua5.2-dev` instead? It seems to be an inconsistency mistake on the package name by Debian/Ubuntu.

**Comment by meatballhat** [comment]
@chfoo I don't know what happened there, I'm sorry :stuck_out_tongue_winking_eye:
