### ISSUE TITLE
APT whitelist request for libkyotocabinet-dev

### ISSUE THREAD

**Issue by marshall-lee** [travis-ci/travis-ci#3613]
Required for building good old [kyotocabinet-ruby](https://github.com/marshall-lee/kyotocabinet-ruby).

**Comment by meatballhat** [comment]
@marshall-lee I'm not finding this in the default sources.  Is there an APT source that needs to be added?

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libkyotocabinet-dev' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/361.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
