### ISSUE TITLE
Travis I hook does not activate

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [travis-ci/travis-ci#3615]
Check the [video reproducing the problem](http://youtu.be/IVkf_vhkPn0).

As you can see, when I try to enable travis hook in [js-cookie/js-cookie](https://github.com/js-cookie/js-cookie) organization repo, it seem the information is not saved. After that if, I push a new commit to the repository no build is triggered.

Is there anything I might be doing wrong?

**Comment by joshk** [comment]
Hi there,

This is due to 3rd Party Auth'd Orgs on GitHub.

Can you please go to https://github.com/settings/connections/applications/f244293c729d5066cf27 and check if the Travis CI oauth app is authorized for the js-cookie org?

Thanks

Josh

**Comment by FagnerMartinsBrack** [comment]
That's weird, I had to add the authorization to make the organization show up in the travis-ci listing some time ago. It should have everything authorized, but it js-cookie wasn't.
