### ISSUE TITLE
Possibility to have conditional addons.apt.sources and addons.apt.packages

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#3618]
In our CI build setup we use commit message to trigger different kind of ```build type``` for our CI jobs. In the non container-based build infrastructure we could use ```before_install``` or ```install``` step to add different list of ppa repositories and install different set of software packages as necessary depends on the ```build type``` with the help of ```sudo``` command. In the container-based build infrastructure I understand we have to use ```addons.apt.sources``` and ```addons.apt.packages```. However, it appears to me that the source list and the packages list can only be statically defined in the ```.travis.yml```. We could of course just combine all our sources and packages list regardless of our ```build type``` but this will just waste the valuable resource and time.

Could we somehow define some environment variables for source and package in the ```before_install``` or ```install``` steps and Travis-CI will combine the values in these variables into the final ```addons.apt.sources``` and ```addons.apt.packages```? Or is there other better way to achieve this? Thanks.

**Comment by BanzaiMan** [comment]
I think this is a variation of #3505.

**Comment by weitjong** [comment]
There is one crucial difference. What I propose above does not require the environment variable to be exported first. In a nutshell, what I request is a possibility to dynamically append the ```addons.apt.sources``` and ```addons.apt.packages``` using environment variables that I set in the ```before_install``` or ```install``` step. If the environment variable contains source or package that is not whitelisted, the entry should be rejected/ignored. I suppose the check is done on the ```addons.apt.sources``` and ```addons.apt.packages``` anyway. So, IMHO, there is no security risk here.

**Comment by joshk** [comment]
Hi @weitjong 

Thanks for submitting this feature request.

I'm sorry, but this feature is not currently possible due to how we generate the build script. The crux of the issue is around how and when Env vars are exported for security reasons. 

I'm going to close this issue for now sorry, but please watch #3505 for updates.

Thanks a bundle

Josh

**Comment by weitjong** [comment]
Thank you all for prompt reply. I will subscribe to that issue to get the updates there as you suggested. But I want to take the opportunity to explain on our specific use case. We use a **same** CI build job to trigger different build type based on the commit message, so the static ```addons.apt.sources``` and ```addons.apt.packages``` declaration per CI job does not meet our requirement to migrate to the new build infra.
