### ISSUE TITLE
Add pantsbuild to the Travis CI environment/VM

### ISSUE THREAD

**Issue by caniszczyk** [travis-ci/travis-ci#3622]
Pants is available via PIP (pip install pantsbuild.pants)

We'd have to setup a virtualenv for it though.

Next step, figure out actually how to do this.

**Comment by jsirois** [comment]
Note this will almost never be the "right thing to do".  We do not have a bootstrap script ala gradlew but we need one/will have one and that will handle creating a virtualenv and pip installing the right version of pants for the particular project at hand.  Presumably adding pants as a default-available tool on Travis either pins a version or floats on HEAD - neither of which should suit most projects using pants now or going forward.

**Comment by BanzaiMan** [comment]
What is pantsbuild, and what help do you need from us?

**Comment by jsirois** [comment]
The tool is called pants (the github org is pantsbuild) - and its equivalent to maven or gradle from TravisCI's perspective, see: http://pantsbuild.github.io/

The idea would be to get pants included in the base TravisCI images as an easily available ready-to-go build tool option for TravisCI users.

That said, I've pointed out difficulties above - ie: if you were willing to add pants to your base image, we'd need to pick a version / have a way to get you-all to upgrade the picked version, etc.

**Comment by BanzaiMan** [comment]
Oh, I see. Do you need the issue open? I am not quite sure what is required on our end.

(I'm happy to chat with you if you want to further brainstorm. If so, please email support@travis-ci.com.)
