### ISSUE TITLE
OS X 10.10.3 Support for Xcode 6.3?

### ISSUE THREAD

**Issue by masters3d** [travis-ci/travis-ci#3626]
Is this planned?
http://docs.travis-ci.com/user/osx-ci-environment/

**Comment by masters3d** [comment]
https://github.com/travis-ci/travis-ci/issues/3373
https://github.com/travis-ci/travis-ci/issues/3216

**Comment by carloslozano** [comment]
:+1:  - ditto the question.

**Comment by joshk** [comment]
Closing this in favour of #3216
