### ISSUE TITLE
Augeas PPAs

### ISSUE THREAD

**Issue by raphink** [travis-ci/travis-ci#3633]
Hello,

There are quite a few projects (augeasproviders* and more Puppet projects) that require to test against various versions of Augeas.

For this, we need the Augeas PPAs to be allowed in the container infrastructure.

The PPAs are the following:

- ppa:raphink/augeas-0.10.0
- ppa:raphink/augeas-1.0.0
- ppa:raphink/augeas-1.1.0
- ppa:raphink/augeas-1.2.0
- ppa:raphink/augeas-1.3.0
- ppa:raphink/augeas-1.0.0
- ppa:raphink/augeas
- ppa:raphink/augeas-dev
- ppa:raphink/augeas-old

Can these be whitelisted please?

**Comment by raphink** [comment]
Any news on this? I have a dozen projects that could use containers if this was whitelisted.

**Comment by mcanevet** [comment]
:+1:

**Comment by raphink** [comment]
@henrikhodne is this still the right process to get PPAs allowed on containers?

**Comment by raphink** [comment]
@henrikhodne The apt-source-whitelist issues seem to be stalled since April or so… Are they still being processed?

**Comment by raphink** [comment]
@henrikhodne ping?

**Comment by emdantrim** [comment]
Fixed in travis-ci/apt-source-whitelist#179.

**Comment by emdantrim** [comment]
Re-opened per https://github.com/travis-ci/apt-source-whitelist/pull/179#issuecomment-153375045

**Comment by emdantrim** [comment]
@raphink, does this look ok now?

**Comment by raphink** [comment]
This is great, thank you @emdantrim. How do I proceed when there's new releases, do I open a new PR or comment here?

**Comment by emdantrim** [comment]
Glad to hear it. I'd say open a new PR here. Happy building.
