### ISSUE TITLE
Pre-install git-lfs on build images

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3634]
https://git-lfs.github.com/

It makes sense to have this installed on all images, rather than doing it with travis-build (since it'll have to be done in `configure` or some such, which will waste a lot of bandwidth).

**Comment by stevendlander** [comment]
Any possibility of this making it into the default container environment?  I am really struggling getting git-lfs working at all with my Travis environment.

**Comment by mmahalwy** [comment]
any luck with this?

**Comment by BanzaiMan** [comment]
Sorry, but this will have to wait until the next build image update.

In the meantime, you might want to try something like:

```yaml
# for OS X
before_install:
- wget https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-darwin-amd64-1.2.0.tar.gz
- tar -zxvf git-lfs-darwin-amd64-1.2.0.tar.gz
- export PATH=`pwd`/git-lfs-1.2.0:$PATH
- echo "https://${GH_TOKEN}@github.com" > .git/credentials
- git config credential.helper "store --file=.git/credentials"
- git remote set-url origin https://github.com/PlutoVR/lfs-test.git
- git lfs install
- git lfs pull
```

```yaml
# for Linux
before_install:
- mkdir -p $HOME/bin
- wget https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz
- tar xvfz git-lfs-linux-amd64-1.1.2.tar.gz
- mv git-lfs-1.1.2/git-lfs $HOME/bin/git-lfs
- export PATH=$PATH:$HOME/bin/
```

**Comment by tjanez** [comment]
To complement [@BanzaiMan's instructions](https://github.com/travis-ci/travis-ci/issues/3634#issuecomment-220554067), use:
```yaml
before_script: git lfs pull
```
to fetch LFS files from the remote and checkout the required working tree files.

**Comment by nfantone** [comment]
@BanzaiMan 

> Sorry, but this will have to wait until the next build image update.

So... have we wait enough already? Today, I tried to use `git lfs pull` on my `.travis.yml` and got:

```sh
$ git lfs install
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	log
The command "git lfs install" failed and exited with 1 during .
Your build has been stopped.
/Users/travis/build.sh: line 109: shell_session_update: command not found
```

Do I need to enable something in order for this to work?

**Comment by nfantone** [comment]
@BanzaiMan Incidentally, why not use `brew` to install `git-lfs` instead of manually downloading the binaries with `wget` and tampering with other things?

Just,

```yml
before_install:
- brew update && brew install git-lfs
- git lfs install
before_script: 
- git lfs pull
```

**Comment by tsaleh** [comment]
@BanzaiMan could I ask you to link to an issue that tracks when this will be supported?

**Comment by Lin-Buo-Ren** [comment]
@BanzaiMan Git LFS is still not preinstalled, any info?

**Comment by carlthome** [comment]
Update?

**Comment by nicolas-albert** [comment]
Something new?

Today, what is the simplest way to get lfs pull working ?
My travis output show me nothing about lfs, here a sample of my .travis.yml :
```
dist: trusty
sudo: false
language: java
jdk: oraclejdk8
before_script: git lfs pull
...
```

**Comment by carlthome** [comment]
Considering [this](https://docs.travis-ci.com/user/customizing-the-build#Git-LFS-Skip-Smudge) mentions LFS, I guess it's being preinstalled now?

**Comment by vtjeng** [comment]
https://docs.travis-ci.com/user/customizing-the-build#linux

> Git LFS is supported by default on our Ubuntu Trusty, Xenial and Bionic images.

Instructions for [installing on macOS](https://docs.travis-ci.com/user/customizing-the-build#macos)
