### ISSUE TITLE
'deploy' doesn't think my local dir is there, even though it appears in before_deploy's ls

### ISSUE THREAD

**Issue by kchodorow** [travis-ci/travis-ci#3636]
I'm basically trying to deploy my output/ directory to GCS.  This directory is created by the [compile.sh](https://travis-ci.org/google/bazel/builds/57836392#L139) step of my script.  However, it looks like dpl doesn't "see" this directory, as it [prints an error](https://travis-ci.org/google/bazel/builds/57836392#L229) when it tries to deploy.  However, I added an `ls` to the `before_deploy` step and [the output directory is there](https://travis-ci.org/google/bazel/builds/57836392#L195).  `output` is in my [.gitignore](https://github.com/google/bazel/blob/master/.gitignore), if that matters.

For reference, my [.travis.yml file](https://github.com/google/bazel/blob/master/.travis.yml).

**Comment by BanzaiMan** [comment]
@kchodorow Hello! Could you try adding `skip_cleanup: true` to your `deploy` section? http://docs.travis-ci.com/user/deployment/gcs/

**Comment by kchodorow** [comment]
Sigh, I thought I already had that.  Worked perfectly, thanks!
