### ISSUE TITLE
Manual gpg file encryption fails on container-based build

### ISSUE THREAD

**Issue by Manu343726** [travis-ci/travis-ci#3637]
I have followed [your docs](http://docs.travis-ci.com/user/encrypting-files) about file encryption, specifically gpg manual encryption encrypting the passphrase first using travis gem.

The call to gpg is exactly the same from the docs:

``` yml
- echo "${gpg_password}" | gpg archlinux/aurup.gpg
```

But then gpg states "gpg-agent is not available in this session" and asks for the passphrase.

[Here](https://travis-ci.org/biicode/packages/builds/57843014)'s my build.

**Comment by BanzaiMan** [comment]
Is this the right invocation of `gpg` to pass the passphrase? https://www.gnupg.org/gph/de/manual/r1023.html suggests either:

```
echo "${gpg_password}" | gpg --passphrase-fd 0 archlinux/aurup.gpg
```

or 

```
 gpg --passphrase "${gpg_password}" archlinux/aurup.gpg
```

is correct. (Assuming that `${gpg_password}` decrypts correctly.

**Comment by ReportMort** [comment]
The first suggestion of the two you listed worked for me (adding `--passphrase-fd 0`)

My .travis.yaml looked like this:
```
env:
  global:
  - secure: {secure_string_here}
before_install:
- echo $gpg_password | gpg --passphrase-fd 0 myfile.txt.gpg
```

I encrypted using this command from CLI:
```
travis encrypt gpg_password={password_goes_here} --add
```
