### ISSUE TITLE
APT whitelist request for php5*

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#3640]
Specifically, for the [haxe repo](https://github.com/HaxeFoundation/haxe), we need:
 * php5
 * php5-mysql
 * php5-sqlite

**Comment by stof** [comment]
@andyli php is already pre-installed in the VM AFAIK

**Comment by andyli** [comment]
No.

A simple [test](https://travis-ci.org/andyli/HaxeCI/jobs/59009009#L880):
```
$ haxe build-php.hxml && php bin/index.php
/home/travis/build.sh: line 41: php: command not found
The command "haxe build-php.hxml && php bin/index.php" exited with 127.
```

**Comment by BanzaiMan** [comment]
Only the PHP image has PHP managed by `phpenv`.
