### ISSUE TITLE
APT whitelist request for libgnome-keyring-dev

### ISSUE THREAD

**Issue by as-cii** [travis-ci/travis-ci#3643]
Hi there,

in Atom we're working to use Travis to run a `cibuild` for our core (https://github.com/atom/atom/pull/6248). We're almost ready to make it happen and [we've already managed to run some builds](https://travis-ci.org/atom/atom/builds/57837685): we would :heart:, however, to take advantage of the new containerized infrastructure for our Linux build.

As you can see from our current [.travis.yml](https://github.com/as-cii/atom/blob/as-public-ci/.travis.yml) file, we need `sudo` to install a bunch of apt packages: almost all of them are already available as part of the apt plugin, exception made for libgnome-keyring-dev.

That's the only missing part to make use of your new Docker system and we would love to see that package whitelisted. If there's anything I can do to help you throughout the approval process I'd be more than happy to do so :sparkles: 

Thank you :pray: 

/cc: @kevinsawicki

**Comment by meatballhat** [comment]
@as-cii sorry for the wait! :raised_hands: :heart:

**Comment by as-cii** [comment]
:clap: :clap: :clap: 

@meatballhat: thanks a lot for this!!! :heart: :green_heart: :blue_heart:
