### ISSUE TITLE
I'm not seeing commit status updates on PRs.

### ISSUE THREAD

**Issue by dopry** [travis-ci/travis-ci#3646]
My  PR, https://github.com/spry-group/python-vultr/pull/13, build successfully, https://travis-ci.org/spry-group/python-vultr/pull_requests.

The build status does not appear on the PR. How can I get the build status to appear on the PR?

**Comment by BanzaiMan** [comment]
Sorry for the troubles. I am not sure what happened then. Unfortunately, our logs have rolled over and we don't have much of a clue now.

Could you push a new commit to the PR? (You can force push it, if you don't want the second commit to the PR.)

**Comment by dopry** [comment]
I can tomorrow. I'm offsite today.

**Comment by dopry** [comment]
@BanzaiMan I just pushed some an update. Can you take a look?

**Comment by BanzaiMan** [comment]
Thanks. The log indicates data integrity issue on our end, but I'm not quite sure how to fix it. I'll ask around and find a solution. Thanks.

**Comment by BanzaiMan** [comment]
I spoke too soon. We need an admin of the organization (https://github.com/spry-group) to log back in to Travis CI, so that we have a valid GitHub token to post to the repository.

Paging @Table28 and @m-antis for it.

**Comment by dopry** [comment]
I am the owner for the organization. neither @Table28 nor @m-antis are
admins of the organization.
ᐧ

On Fri, Apr 17, 2015 at 11:26 PM, Hiro Asari <notifications@github.com>
wrote:

> I spoke too soon. We need an admin of the organization (
> https://github.com/spry-group) to log back in to Travis CI, so that we
> have a valid GitHub token to post to the repository.
>
> Paging @Table28 <https://github.com/Table28> and @m-antis
> <https://github.com/m-antis> for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/travis-ci/issues/3646#issuecomment-94122077>
> .
>



-- 
Darrel O'Pry
The Spry Group, LLC.
http://www.spry-group.com
718-355-9767 x101

**Comment by dopry** [comment]
It seems to be working now. I had to fix some permissions in our ORG. I had enabled the additional org level access controls for apps, after setting up the project initially. I'm guessing this caused problems with the token. I had to re-allow travis-ci at the org level.
