### ISSUE TITLE
Using haxe 3.2.0-rc.2

### ISSUE THREAD

**Issue by ibilon** [travis-ci/travis-ci#3650]
@andyli @waneck @Simn

Trying to do:
```
language: haxe
haxe: "3.2.0-rc.2"
```
fails with this error:
```
The command "curl -s -L --retry 3 'http://haxe.org/website-content/downloads/3,2,0-rc,2/downloads/haxe-3.2.0-rc.2-linux64.tar.gz' | tar -C ~/haxe -x -z --strip-components=1 -f -" failed and exited with 2 during .
```
Full log here: https://travis-ci.org/HaxePunk/HaxePunk/builds/58075789

It's looking for `haxe-3.2.0-rc.2-linux64.tar.gz` but the file is called `haxe-3.2.0-rc2-linux64.tar.gz` which does not follow `haxe-version-linux64.tar.gz`.

**Comment by Simn** [comment]
I suppose I should learn how to semver. The builds are available as 3.2.0-rc2 without the dot, but our download site has the dot. Can you try without it?

**Comment by ibilon** [comment]
I did, still error.
```
The command "curl -s -L --retry 3 'http://haxe.org/website-content/downloads/3,2,0-rc2/downloads/haxe-3.2.0-rc2-linux64.tar.gz' | tar -C ~/haxe -x -z --strip-components=1 -f -" failed and exited with 2 during .
```
https://travis-ci.org/HaxePunk/HaxePunk/builds/58081778

The problem is that the folder and filename don't follow the same convention.

**Comment by Simn** [comment]
Indeed. Can you report this at https://github.com/HaxeFoundation/haxe.org/issues and close here? It's not related to travis itself.
