### ISSUE TITLE
Custom deployment, error when using ssh-add

### ISSUE THREAD

**Issue by eddiejaoude** [travis-ci/travis-ci#3652]
**ssh** agent issue?

```
$ ssh-add .travis/deploy.pem
Could not open a connection to your authentication agent.
```

**Comment by henrikhodne** [comment]
Are you starting an SSH agent yourself as part of the build? There isn’t one running by default, but you could start an SSH agent with `eval "$(ssh-agent -s")`.

**Comment by eddiejaoude** [comment]
> There isn’t one running by default

Thank you! I will try that now.

**Comment by eddiejaoude** [comment]
Yes that worked. Thank you! :+1: 

Note: I fixed the typo :smile:  should be `eval "$(ssh-agent -s)"`
