### ISSUE TITLE
Python job treated as a Ruby job, causing failure

### ISSUE THREAD

**Issue by themattrix** [travis-ci/travis-ci#3654]
**Example:** https://travis-ci.org/themattrix/bashup/jobs/58380026

Travis correctly recognizes the jobs as Python (here's the corresponding [.travis.yml](https://github.com/themattrix/bashup/blob/3bfaa0f7c120c23b101177cbf358ab2b8e85d9b3/.travis.yml)), but Ruby steps are run in the container instead. This obviously causes the build to fail.

**Comment by themattrix** [comment]
Non-container builds fail for the same reason:

![image](https://cloud.githubusercontent.com/assets/1551295/7146280/1181916e-e2b8-11e4-831b-f63baae99b67.png)

![image](https://cloud.githubusercontent.com/assets/1551295/7146515/b3c142e8-e2b9-11e4-810b-0c8b36281365.png)

**Comment by themattrix** [comment]
Today, with absolutely no changes on my end, it works.

**Comment by BanzaiMan** [comment]
It works sometimes? That is very curious. Do you have a log URL that did work?

**Comment by themattrix** [comment]
Sure, I've re-run all of the failed builds now and have gotten them all to pass.

Here's a now-passing one: https://travis-ci.org/themattrix/bashup/jobs/58382413

And here's the log from when it had previously failed:

```
Using worker: worker-linux-docker-c5416fea.prod.travis-ci.org:travis-linux-3

Build system information
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"

$ git clone --depth=50 --branch=master git://github.com/themattrix/bashup.git themattrix/bashup
Cloning into 'themattrix/bashup'...
remote: Counting objects: 298, done.
remote: Compressing objects: 100% (214/214), done.
remote: Total 298 (delta 149), reused 217 (delta 72), pack-reused 0
Receiving objects: 100% (298/298), 52.05 KiB | 0 bytes/s, done.
Resolving deltas: 100% (149/149), done.
Checking connectivity... done.
$ cd themattrix/bashup
$ git checkout -qf 6fd29ad845c320c595f53046fb89a3e0520feca8

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
$ rvm use default
Using /home/travis/.rvm/gems/ruby-1.9.3-p551
$ ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
$ rvm --version
rvm 1.26.10 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.7.6
$ gem --version
2.4.5
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

The command "rake" exited with 1.

Done. Your build exited with 1.
```

**Comment by BanzaiMan** [comment]
I have a hunch about this, but I'll need to get in touch with a few folks to see how feasible it is. Sorry for the delay, but please hang on while we investigate.

**Comment by BanzaiMan** [comment]
When you see a build fail this way next time, could you leave it there so that we can see it? (I know this is an eyesore, but please indulge us.)

**Comment by themattrix** [comment]
Sure thing - I won't re-run the next failed build until you've had enough time to analyze it. It's been green for the past few runs so I'm not sure how likely it is to occur again. I'll kick an older build a few times and see if I can get it to fail.

**Comment by BanzaiMan** [comment]
This doesn't appear to be an issue any longer, so I'm closing this optimistically. If you see another occurrence, do let us know.

**Comment by douglasmoraisdev** [comment]
Getting the same error:
https://travis-ci.org/douglasmoraisdev/ead_api/builds/214466244

**Comment by BanzaiMan** [comment]
@douglasmoraisdev Your file is `travis.yml`, not `.travis.yml`. https://github.com/douglasmoraisdev/ead_api/tree/5ea8173cb8e650ce993252983527d35a05567087

**Comment by douglasmoraisdev** [comment]
Wow, thanks @BanzaiMan , my mistake.
But it's crazy, Travis was trying to build with no **.travis.yml**
Just the **travis.yml** with wrong name was present.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/douglasmoraisdev/ead_api/builds/214466244#L6 tells you that it is doing so. And you can change this behavior by turning off building if `.travis.yml` is not found. https://travis-ci.org/douglasmoraisdev/ead_api/settings.

**Comment by hemanth5636** [comment]
getting the same error, even thought my .travis.yml file is correct.
https://travis-ci.org/hemanth5636/photo_CI/jobs/349672327
please help me out.

**Comment by mirzakhalov** [comment]
Had this problem today. Reason in my case was the fact that **there was a type/error in my .travis.yml** file. Once I fixed it, it started running normally again.
