### ISSUE TITLE
Build matrix UI for C and Android projects just says "no language set"

### ISSUE THREAD

**Issue by jmarshall** [travis-ci/travis-ci#3655]
Before recent UI changes we could see which build job was which easily.  Now they appear mostly identical in e.g. [samtools/samtools](https://travis-ci.org/samtools/samtools/builds/58303417):

![build matrix](https://cloud.githubusercontent.com/assets/70921/7132481/96de32c2-e281-11e4-8c7e-77c83c890fc9.png)

Our [.travis.yml file](https://github.com/samtools/samtools/blob/develop/.travis.yml) has

```
language: c
compiler:
  - clang
  - gcc
```

(and also an extra **gcc**/**-O0** build) but the UI no longer identifies **clang** or **gcc** builds.

Similarly for example with [curl](https://travis-ci.org/bagder/curl).

**Comment by weitjong** [comment]
+1

**Comment by capnslipp** [comment]
I'm seeing the same for Objective-C.  `.travis.yml` has `language: objective-c` defined; all builds have “no language set” displayed in the UI.

**Comment by mloskot** [comment]
I've noticed the same issue on [SOCI/soci](https://github.com/SOCI/soci/) build matrix, despite we have got the `language: cpp` set in .travis.yml.

**Comment by dagar** [comment]
Same problem.

language: cpp

compiler:
  - clang
  - gcc

https://github.com/dropbox/pyston/blob/master/.travis.yml

**Comment by abbeycode** [comment]
Like @capnslipp I'm seeing this with Objective-C projects ([UnrarKit](https://travis-ci.org/abbeycode/UnrarKit) and [UnzipKit](https://travis-ci.org/abbeycode/UnzipKit))

**Comment by BanzaiMan** [comment]
Sorry, this is a known issue, and we are tracking internally. The fix is a little more involved than others. Thanks for your patience.

**Comment by briansmith** [comment]
Any update on this? It is especially confusing for multi-language projects. For example, in my project (https://travis-ci.org/briansmith/ring), some jobs are ```language: rust``` and others are ```language: cpp``` and people get confused because of this issue.

**Comment by joshk** [comment]
Hi Brian




We haven't forgotten about this, we are just in the middle of some other work right now. 




Thanks a bundle




Josh

**Comment by kcharwood** [comment]
Seeing this too.

**Comment by neersighted** [comment]
Bump

**Comment by larsbrinkhoff** [comment]
Still wrong.

**Comment by msabramo** [comment]
Same here - matrix project with `language: python`

https://travis-ci.org/msabramo/python-panci

**Comment by TheKing42** [comment]
Still having this issue https://travis-ci.org/danfiscus/factorpro

**Comment by niemeyer** [comment]
Same for Go projects.. the feature is probably not working at all. How about just hiding the column so people stop thinking there's an issue to be fixed?

**Comment by weitjong** [comment]
> Same for Go projects.. the feature is probably not working at all. How about just hiding the column so people stop thinking there's an issue to be fixed?

The feature is partially working and partially not. I think most of us here still want it. For those cases when it is working, it is invaluable to be able to tell which is which in a large build matrix with a mix bag of compiler setting.

**Comment by LorenzoBettini** [comment]
Same for language java:

```
language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
```

isn't there any workaround?

**Comment by DavidUser** [comment]
Happen with my C++ project like @dagar.
Removing the "language: cpp" that's back to work but default ruby language are get.

Very confused.

**Comment by DavidUser** [comment]
The better way is set "language: generic"

**Comment by ulfgebhardt** [comment]
Problem remains with:
* android
* objective-c

**Comment by larsbrinkhoff** [comment]
Problem still remains.

**Comment by vasily-v-ryabov** [comment]
We have the same problem for Python.

**Comment by jfcabral** [comment]
I have the same issue for `Java` 😞

**Comment by TimMcCauley** [comment]
Bump - dito, same issue with java

**Comment by jlewicki-nevo** [comment]
Bump - Still an issue with Android.  Very confusing to users.

**Comment by BanzaiMan** [comment]
If there is still missing languages, do let us know.

**Comment by karenetheridge** [comment]
I see this with just one build on perl (where a custom perl is built from the latest commit in the main language repository): https://travis-ci.org/karenetheridge/Test-CleanNamespaces/builds/465692178

**Comment by BanzaiMan** [comment]
@karenetheridge I am not sure what you are saying. The values shown on https://travis-ci.org/karenetheridge/Test-CleanNamespaces/builds/465692178 correspond to the values defined in [your `.travis.yml`](https://github.com/karenetheridge/Test-CleanNamespaces/blob/a8061e5e37e38e1ff5163ea92fd7b1464a863088/.travis.yml#L7-L20).

**Comment by karenetheridge** [comment]
> The values shown on ... correspond to the values defined in your .travis.yml.

Something has changed. On some builds I was looking at yesterday, the build for blead did indeed just say "no language set", not "Perl: blead" which is what it says now.
