### ISSUE TITLE
Why `sudo` sometimes necessary for R-Travis?

### ISSUE THREAD

**Issue by surmann** [travis-ci/travis-ci#3656]
Hallo All,

A successful test of my package [ODEnetwork](https://github.com/surmann/ODEnetwork) needs `sudo: required`. Why is this not necessary for other packages like [ecr](https://github.com/jakobbossek/ecr)?

Thanks!

As said in the Travis CI:
@craigcitro, @eddelbuettel, @hadley

**Comment by eddelbuettel** [comment]
Recent change at Travis in their migration to _a completely new archictecture_; see [eg here on their blog](http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/).

**Comment by surmann** [comment]
Thanks for the link.

Did I understand it correctly: Obviously, the ODEnetwork package has some code in it, that needs `sudo`?

Is a file access like plotting in tests an example that needs admin rights?

**Comment by tdhock** [comment]
I have the same issue. Shouldn't `sudo: required` be the default?

**Comment by BanzaiMan** [comment]
The `sudo` detection logic should also look at the `language` value. cc @meatballhat

**Comment by BanzaiMan** [comment]
@jimhester Did we do away with the need for `sudo` (by user) in recent changes?

**Comment by jimhester** [comment]
Yes, `language: r` no longer needs `sudo: required` to work.

**Comment by BanzaiMan** [comment]
@jimhester On a related note, could you review and update https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/languages/r.md? Thank you for your hard work!

**Comment by craigcitro** [comment]
+1 on @jimhester being awesome. :grin:

**Comment by surmann** [comment]
@jimhester Thanks! Unfortunately, I get the following error after removing `sudo: required`:
`The command "Rscript -e 'devtools::install_github(c("jimhester/covr"), build_vignettes = FALSE)'" failed and exited with 1 during .` Do you have an idea why?

You find more information in my package [ODEnetwork](https://github.com/surmann/ODEnetwork).

**Comment by hadley** [comment]
@surmann that seems unrelated, and I suspect is just a github glitch. I'd also recommend you add `cache: packages` to your `.travis.yml`.

**Comment by surmann** [comment]
@hadley Obviously. I rerun the build with and without the `cache` option, and everything was fine. Thanks.

**Comment by surmann** [comment]
I was wrong, it only runs with the caching option. Thanks for the hint @hadley

**Comment by Bohdan-Khomtchouk** [comment]
@surmann Have you tried setting up a personal access token on Github: https://github.com/blog/1509-personal-api-tokens

This would really make your life easier in terms of avoiding errors of the type: `The command "Rscript -e 'devtools::install_github(c("jimhester/covr"), build_vignettes = FALSE)'" failed and exited with 1 during .`, especially if you're trying to access other R packages in your Github profile (e.g., data packages that your main R package depends on).
