### ISSUE TITLE
Why shows Permission denied

### ISSUE THREAD

**Issue by IftekherSunny** [travis-ci/travis-ci#3658]
my .travis.yml file is 

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run

![capture](https://cloud.githubusercontent.com/assets/8013399/7138480/81907de2-e2e2-11e4-8925-2ba9528985d5.JPG)

**Comment by BanzaiMan** [comment]
Is `vendor/bin/phpsec` executable? Where is it coming from?

**Comment by IftekherSunny** [comment]
yeah. when I execute vendor/bin/phpspec in my terminal it shows green. but travis shows Permission denied

@BanzaiMan

**Comment by BanzaiMan** [comment]
The script is coming from an external source. Do you have a build log URL to show the problem?

**Comment by IftekherSunny** [comment]
Yes brother. and thanks for helping me.  https://travis-ci.org/IftekherSunny/SunMailer/builds/58443637

**Comment by BanzaiMan** [comment]
`vendor/bin/phpspec` is checked in to your repository, and it is not executable. Please make it so.

```sh-session
$ git clone https://github.com/IftekherSunny/SunMailer.git; ls -l SunMailer/vendor/bin/phpspec
Cloning into 'SunMailer'...
remote: Counting objects: 1645, done.
remote: Compressing objects: 100% (1200/1200), done.
remote: Total 1645 (delta 439), reused 0 (delta 0), pack-reused 369
Receiving objects: 100% (1645/1645), 953.22 KiB | 0 bytes/s, done.
Resolving deltas: 100% (636/636), done.
Checking connectivity... done.
-rw-r--r--  1 asari  staff  142 Apr 14 11:26 SunMailer/vendor/bin/phpspec
```

**Comment by IftekherSunny** [comment]
Thanks brother. problem solved.
