### ISSUE TITLE
Downloading the Coverity scan analysis tool every time increases build time a lot

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#3660]
I talked with @evilsocket about adding Coverity to https://github.com/evilsocket/gibson.
We added it and the new build with Coverity enabled takes a lot more than 8-12s like it used to.

**Comment by evilsocket** [comment]
This is the log, it's stuck on the last line:

    Using worker: worker-linux-docker-1c98b733.prod.travis-ci.org:travis-linux-6
    system_info
    Build system information
    Build language: c
    Build image provisioning date and time
    Thu Feb  5 15:09:33 UTC 2015
    Operating System Details
    Distributor ID:	Ubuntu
    Description:	Ubuntu 12.04.5 LTS
    Release:	12.04
    Codename:	precise
    Linux Version
    3.13.0-29-generic
    Cookbooks Version
    a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
    GCC version
    gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
    Copyright (C) 2011 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    LLVM version
    clang version 3.4 (tags/RELEASE_34/final)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    Pre-installed Ruby versions
    ruby-1.9.3-p551
    Pre-installed Node.js versions
    v0.10.36
    Pre-installed Go versions
    1.4.1
    Redis version
    redis-server 2.8.19
    riak version
    2.0.2
    MongoDB version
    MongoDB 2.4.12
    CouchDB version
    couchdb 1.6.1
    Neo4j version
    1.9.4
    RabbitMQ Version
    3.4.3
    ElasticSearch version
    1.4.0
    Installed Sphinx versions
    2.0.10
    2.1.9
    2.2.6
    Default Sphinx version
    2.2.6
    Installed Firefox version
    firefox 31.0esr
    PhantomJS version
    1.9.8
    ant -version
    Apache Ant(TM) version 1.8.2 compiled on December 3 2011
    mvn -version
    Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
    Maven home: /usr/local/maven
    Java version: 1.7.0_76, vendor: Oracle Corporation
    Java home: /usr/lib/jvm/java-7-oracle/jre
    Default locale: en_US, platform encoding: ANSI_X3.4-1968
    OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
    git.checkout
    0.16s$ git clone --depth=50 --branch=unstable git://github.com/evilsocket/gibson.git evilsocket/gibson
    Cloning into 'evilsocket/gibson'...
    remote: Counting objects: 439, done.
    remote: Compressing objects: 100% (210/210), done.
    remote: Total 439 (delta 283), reused 366 (delta 223), pack-reused 0
    Receiving objects: 100% (439/439), 163.25 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (283/283), done.
    Checking connectivity... done.
    $ cd evilsocket/gibson
    $ git checkout -qf 6e303b75b5b115e915c6cfc662311c6c89621750
    git.submodule
    0.02s$ git submodule init
    0.02s$ git submodule update
    This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
    If you require sudo, add 'sudo: required' to your .travis.yml
    See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
    Setting environment variables from repository settings
    $ export COVERITY_SCAN_TOKEN=[secure]
    $ export PROJECT_NAME=[secure]
    Setting environment variables from .travis.yml
    $ export COVERITY_SCAN_TOKEN=[secure]
    $ export CC=gcc
    cache.1
    Setting up build cache
    $ export CASHER_DIR=$HOME/.casher
    0.13s$ Installing caching utilities
    0.34sattempting to download cache archive
    found cache
    $ gcc --version
    gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
    Copyright (C) 2011 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    0.25sadding /home/travis/.ccache to cache
    $ export PROJECT_NAME=evilsocket/gibson
    Coverity Scan analysis selected for branch unstable.
    Coverity Scan analysis authorized per quota.
    $ curl -s https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh | COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG" COVERITY_SCAN_NOTIFICATION_EMAIL="evilsocket@gmail.com" COVERITY_SCAN_BUILD_COMMAND="make -j4" COVERITY_SCAN_BUILD_COMMAND_PREPEND="cmake ." COVERITY_SCAN_BRANCH_PATTERN=unstable bash
    Note: COVERITY_SCAN_PROJECT_NAME and COVERITY_SCAN_TOKEN are available on Project Settings page on scan.coverity.com
    Coverity Scan configured to run on branch unstable
    Coverity Scan analysis authorized per quota.
    Downloading Coverity Scan Analysis Tool...

**Comment by thedrow** [comment]
This causes the build to cancel since there wasn't any output in the last 10 minutes.

**Comment by thedrow** [comment]
@BanzaiMan Should we try to switch to the old infrastructure and try again?

**Comment by thedrow** [comment]
Coverity does work on the non-containerized infrastructure.
Please let me know when you guys have a fix for it.

**Comment by arr2036** [comment]
FWIW we're experiencing the same issues. It was working up until recently though.

**Comment by BanzaiMan** [comment]
I believe this is a general networking issue we are seeing on containers. See #3692 for a more detailed discussion.

**Comment by grooverdan** [comment]
appears resolved

**Comment by tanzislam** [comment]
I've got a Linux (containerized) + macOS (VM) configuration, and this problem is happening frequently only on the macOS builds. Example: https://travis-ci.org/tanzislam/cryptopals/jobs/278333534#L2203

**Comment by BanzaiMan** [comment]
I'm closing this now. If you see this again, please open a new issue.
