### ISSUE TITLE
What is the recommended number of concurrent build process for container-based infra

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#3664]
In the old Linux CI build environment we used to set number of concurrent build process to 3, i.e. ```make -j3```. What is the recommended number of concurrent build process in the new container-based infra? Thanks in advance.

**Comment by thedrow** [comment]
Each build job has a VM with only two CPUs so I assume that ```make -j2``` is probably the best.

**Comment by weitjong** [comment]
Thanks for your reply. Based on the available doc and blog, it states that the legacy infra has 1.5 cores (with burst capacity) and 3GB, while the new infra has 2 cores (dedicated) and 4GB. Throuh trial and error we found 3 concurrent build process is the best for our project. I would probably do the same experiment on our project against the new infra to see how far we can push it. But it is good know what is the official recommendation in this case.

**Comment by weitjong** [comment]
I have done some tests last night. Setting it to 4 gave a marginal speed up over 3 in the new infra, and increasing it further did nothing to improve the build speed which is expected. This is just an observation based on one trial run using our project. It is by no mean a recommendation setting. As there is no official response from Travis CI team up until now, I guess they never will. So, closing the issue now.
