### ISSUE TITLE
Cannot encrypt heroku auth:token

### ISSUE THREAD

**Issue by MoonTahoe** [travis-ci/travis-ci#3666]
Running this command used to work fine for me:

                  travis encrypt $(heroku auth:token) --add deploy.api_key

I updated travis, because the cli made me, and now I get this error all the time:

                   $ travis encrypt $(heroku auth:token) --add deploy.api_key
                   resource not found ({"file":"not found"})

I get this error if I try to encrypt anything

                   $ travis encrypt SOMEVAR=secretvalue
                   resource not found ({"file":"not found"})

How can I resolve this issue.  I have the __.travis.yml__ file in the directory where I am running the encrypt command.

**Comment by BanzaiMan** [comment]
I suspect this is a different manifestation of #3647.

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate of #3647.
