### ISSUE TITLE
Project status in Travis CI currently reflects most recently completed build, even if that build is of an old push. Project status should instead *always* reflect latest build of most recent push.

### ISSUE THREAD

**Issue by sampablokuper** [travis-ci/travis-ci#3667]
This bug report is based on [my comment](https://github.com/travis-ci/travis-ci/issues/1597#issuecomment-92855629) on #1597 . #1597 is currently marked "closed", so I figured I the bug I reported wouldn't receive any attention there and am therefore opening a new issue.

Earlier today, I found myself in the following situation - all of the following were true simultaneously:

- My most recent push is reflected in build 5, which passed.
- An earlier push is reflected in build 2, which failed.
- For some reason (I think because I restarted it), build 2 completed *after* build 5.
- Therefore (and this is, I agree with @pbellec , a bug in Travis CI), my project's status as a whole is currently showing as "failed": https://travis-ci.org/sampablokuper/dwgen/ .

The expected behaviour, at least from my perspective, is that the project status Travis CI reports should refer to the build reflecting the most recent push. It should **not** refer to the build that completed most recently on Travis CI's worker infrastructure, because that is something potentially out of the control of the user and anyhow irrelevant to whether the latest push to the CI-tracked branch of the repository builds successfully or fails. If someone wants to check the status of a particular build, they can always do so by looking at the build history

**Update:**

I was able to work around this bug by manually restarting build 5, which resulted in its becoming the latest completed build, which in turn resulted in the project status as a whole updating to "passed". This is, nevertheless, a workaround, not a fix.

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #1781.

**Comment by BanzaiMan** [comment]
Or #483.

**Comment by sampablokuper** [comment]
Duplicate of #483.
