### ISSUE TITLE
Minor issue with "matrix.include" with the "compiler" key having a list of values

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#3670]
There is an error in the build log of the jobs generated by `matrix.include`.

```
$ ["gcc", "clang"] --version
/home/travis/build.sh: line 41: [gcc,: command not found
```

Edit: I have modified the issue description because it was myself who got confused by the Travis CI web which does not indicate which jobs are `gcc` and which are `clang` as it used to be. :smile:
So, only the minor issue remains valid. Sorry for the noise.

**Comment by joshk** [comment]
Can you please link us to an example .travis.yml

**Comment by weitjong** [comment]
Thanks for the prompt reply. Here is the [link](https://github.com/weitjong/Urho3D/blob/docker-CI/.travis.yml#L24-L26) for your perusal.

**Comment by joshk** [comment]
Ok, so you have exposed an edge case of an edge case we don't document supporting yet.

This syntax is in line for a revamp, but I don't have an ETA yet sorry. I'm not sure we will fix this edge case yet as we need to review the `include` syntax further.

Thank you for reporting this, we will keep this open so we can update it with more info.

**Comment by jck** [comment]
A similar thing is happening with language versions.

**Comment by BanzaiMan** [comment]
I don't think this is a bug, after all.

Jobs defined in `matrix.include` is supposed to be a complete job specification, while inheriting the default values. The values that define the build matrices such as `os`, `env`, and other language-dependent matrix dimensions (e.g., `rvm` for Ruby, `python` for Python, `compiler` for C/C++) should take on exactly one value for each of the jobs in the matrix.

When you add jobs to the matrix via `matrix.include`, the jobs should conform to this expectation. Unless the dimension is given as a single-valued list (say `compiler: [ gcc ]`), the job thus added cannot determine which value to choose.
