### ISSUE TITLE
Problems with notifications to IRC over SSL

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#3671]
There is a java error thrown hen trying to connect to an IRC channel over SSL: `java.lang.RuntimeException: Could not generate DH keypair`. I only tried freenode's `ircs://irc.freenode.org:6697`, so I'm not sure if this is a general problem with our IRC handling or a problem with freenode in particular. Quick google search indicates that this might be [a Java's bug](http://stackoverflow.com/questions/6851461/java-why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception)

**Comment by BanzaiMan** [comment]
This is a duplicate of https://github.com/travis-ci/travis-ci/issues/2850, and documented in http://docs.travis-ci.com/user/notifications/#Note-on-HTTPS.

**Comment by BanzaiMan** [comment]
Duplicate, in the sense that travis-tasks (running with JRuby) cannot talk to HTTPS servers with certain ciphers.

**Comment by BanzaiMan** [comment]
It's not just HTTPS servers, so I'll update the document.
