### ISSUE TITLE
Custom version for haxe

### ISSUE THREAD

**Issue by 7-by** [travis-ci/travis-ci#3672]
Hi! @andyli`, `@waneck`, `@Simn` Now travis can use only 3.1.3 stable version (or other stable versions) or nightly build (latest), but last nightly build sometimes not fully stable. It would be good to add opportunity for setup url for haxe or something else. Because when i try to set last stable 3.2.0-rc.2 then travis can't download it and made wrong link. For example i set haxe version *3.2.0-rc.2* then i will got *http://haxe.org/website-content/downloads/3,2,0-rc.2/downloads/haxe-3.2.0-rc.2-linux64.tar.gz*. But it wrong link, because in file name betwen *rc.2* we have dot. On haxe.org we havent this dot. When i remove this dot from version in yaml file, then i will have wrong symbols in first part of url (*3,2,0-rc2*)

**Comment by Simn** [comment]
This has been discussed in https://github.com/travis-ci/travis-ci/issues/3650 and was moved to https://github.com/HaxeFoundation/haxe.org/issues/119.

**Comment by BanzaiMan** [comment]
closing as a duplicate
