### ISSUE TITLE
Allow setting max-duration on the sauce connect addon

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#3673]
Users sometimes experience timeouts when using the sauce connect addon. Because the addon does not allow to set the max-duration option they'll need to fallback to using sauce manually.

This should be an easy addition to the addon.

**Comment by drogus** [comment]
We got a response that this was in fact a problem with max duration setting for a test, not for a connection, which can be set through the API: https://docs.saucelabs.com/reference/test-configuration/#maximum-test-duration

A connection of an addon is most likely not bound with any timeouts.
