### ISSUE TITLE
Travis-ci / Saucelab tests got this error : GnuTLS recv error (-9)

### ISSUE THREAD

**Issue by emilient** [travis-ci/travis-ci#3676]
Not every times, but so many times, I got this error from travis-ci tests : 
Exception: Got an error while making a request: GnuTLS recv error (-9): A TLS packet with unexpected length was received.

Travis see 'Error' as test result and saucelab keep 'complete' as result instead of 'passed' whereas the test was successfull.

My research tells that a lots of services now use TLS instead of SSL with curl; so i tried to add some custom option like this in Sauce/Sausage/SauceAPI.php : 
```
curl_setopt(\$ch, CURLOPT_SSLVERSION, 3);
```
or 
```
curl_setopt(\$ch, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
```

But nothing works.
In fact, after working on it with SauceLab, we defined that the issue comes from travis; 
Other users have the same problem with travis only whereas it works fine in local.

You can see the issue here i you want : https://travis-ci.org/emilient/Easy_MultipleDomains/builds/56311207

**Comment by BanzaiMan** [comment]
Which job shows this problem? There are 24 of them in the build, one of which passed and many failed.

**Comment by emilient** [comment]
Many of failed one are failed because of the related issue.
For example (line 691) : https://travis-ci.org/emilient/Easy_MultipleDomains/jobs/56311209

**Comment by rmcdaniel** [comment]
I am having the same issue.

**Comment by bshaffer** [comment]
I have been dealing with this same issue... does anyone know a workaround?

**Comment by rdok** [comment]
Same https://travis-ci.org/rdok/elasticemail-php/jobs/157301726

**Comment by hohl** [comment]
Still seems to be the case (with php7.0-curl). Anybody got a workaround for that?

**Comment by BanzaiMan** [comment]
I think this is a precursor to #6339 (issue with PHP and SSL). That ticket has more information on the problem we are facing, so I'm closing this one.
