### ISSUE TITLE
New commits to pull request not being recognized by git hook?

### ISSUE THREAD

**Issue by jakemac53** [travis-ci/travis-ci#3677]
see https://github.com/angular/angular/pull/1282/commits, I tried closing and reopening the pull request as well in case it was just a transient error, but I can't seem to get it to run the new commit?

**Comment by BanzaiMan** [comment]
The PR https://github.com/angular/angular/pull/1282 is not mergeable, so we do not run the build. Could you try rebasing it or making it mergeable by some other means?

**Comment by jakemac53** [comment]
Ah yep that seems to have worked.

**Comment by jakemac53** [comment]
It would be great to get a better error message in this case, it could just show up as a failed check so its clear whats going on?

**Comment by jakemac53** [comment]
Seems to be happening again, but the pull request is mergable now.

**Comment by meatballhat** [comment]
@jakemac53 hey!  We're getting reports of heightened error levels for incoming GitHub events.  Investigating...

**Comment by jakemac53** [comment]
Ah looks like it did get picked up, must have just been a bit backlogged :). Thanks!
