### ISSUE TITLE
R CMD Passed: Build Failed

### ISSUE THREAD

**Issue by brendan-R** [travis-ci/travis-ci#3678]
(As requested by the travis messages:  @craigcitro, @eddelbuettel and @hadley)

My recent commits to boxr ([travis log here](https://travis-ci.org/brendan-R/boxr)), have been passing R CMD check, but returning a build error.

Fellow file transfer enthusiast @karthik seems to have the same problem with rdrop2 today ([travis log here](https://travis-ci.org/karthik/rdrop2)).

Lines of output I don't recognise at the end of the travis log are:

```bash
/home/travis/build.sh: line 307: conditional binary operator expected
/home/travis/build.sh: line 307: syntax error near `-neq'
/home/travis/build.sh: line 307: `if [[ $? -neq 0 ]]; then'
```

Is there something wrong with my travis.yaml, are NOTEs now failures, or is this a bug?

**Comment by craigcitro** [comment]
i think this is a bug that i might have introduced with @jimhester. it looks like it should be `-ne`, not `-neq`.

i'll roll a fix right now.

**Comment by meatballhat** [comment]
Deploying shortly :smiley:

**Comment by karthik** [comment]
Thanks everyone!
and esp @brendan-R for catching this (I was scratching my head all morning).

**Comment by craigcitro** [comment]
@karthik score -- everything is up and running again? ;)

**Comment by karthik** [comment]
All good now @craigcitro 
![](http://media0.giphy.com/media/lLhk62YIbon0Q/200.gif)
