### ISSUE TITLE
iphoneos8.1 xcode_sdk: “No architectures to compile for”

### ISSUE THREAD

**Issue by capnslipp** [travis-ci/travis-ci#3679]
When I add an `xcode_sdk:` entry of `iphoneos8.1` to my `.travis.yml`:
~~~
language: objective-c
before_install:
    - rvm get stable --auto-dotfiles
xcode_workspace: P-001.xcworkspace
xcode_scheme: P-001.G-imr
xcode_sdk:
    - iphoneos8.1
    - iphonesimulator8.1
    - iphonesimulator7.1
    - iphonesimulator7.0
~~~

then that specific build fails with:
~~~
…

=== BUILD ===

  xcodebuild build P-001.G-imr
    Pods / Pods-FontAwesomeIconFactory (Debug)
      ✗ Check dependencies (8 ms)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Check dependencies
No architectures to compile for (ARCHS=i386, VALID_ARCHS=arm64 armv7 armv7s).
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      1 errored, 0 warning (8 ms)

…

** BUILD FAILED ** (1113 ms)


The command "xctool -workspace P-001.xcworkspace -scheme P-001.G-imr -sdk iphoneos8.1 build test" exited with 1.

Done. Your build exited with 1.
~~~

The project builds and tests fine for iOS simulator & device on my own machines _(Xcode 5.1.1 on OS X 10.8.5 for iOS 6.0/6.1/7.0/7.1, and Xcode 6.1.1 on OS X 10.10.3)_ and other Travis 3 builds _(`iphonesimulator8.1`, `iphonesimulator7.1`, and `iphonesimulator7.0`)_ also build & test just fine:
![screen shot 2015-04-15 at 7 33 33 pm](https://cloud.githubusercontent.com/assets/74679/7171431/5b7b320e-e3a6-11e4-8614-e97dc0fffe9d.png)

**Comment by solarce** [comment]
@capnslipp is this issue still happening for you?

**Comment by capnslipp** [comment]
Not sure.  I gave up on Travis-CI about a year ago; I really didn't need what a couple of local scripts that run when I step away from my computer could do faster & better.

I can give it another go, but it may take a while.  The repo in question is no longer on GitHub.

**Comment by solarce** [comment]
Thanks for the update. No need to try it if you're not actively using it.
