### ISSUE TITLE
APT whitelist request for libdw-dev

### ISSUE THREAD

**Issue by g2graman** [travis-ci/travis-ci#3681]
@meatballhat 
Package is necessary to build kcov (re: https://github.com/SimonKagstrom/kcov) manually (with container-based infrastructure, i.e., sudo disabled)

**Comment by meatballhat** [comment]
Looks like I covered this along with libelf :metal: :smiley_cat:

**Comment by g2graman** [comment]
@meatballhat Looks like I tagged the right person then :P
Thank you!

**Comment by meatballhat** [comment]
Yep!  :metal: :smiley_cat:
