### ISSUE TITLE
APT whitelist request for shellcheck

### ISSUE THREAD

**Issue by Maijin** [travis-ci/travis-ci#3684]
`shellcheck` is able to detect possible errors in BashScript as well as warning about potential problems

**Comment by meatballhat** [comment]
@Maijin I don't see `shellcheck` in the default sources.  Is there an APT source that needs to be added first?

**Comment by Maijin** [comment]
Oh ok it's in utopic devel ; trusty-backports or vivid :(

**Comment by BanzaiMan** [comment]
Did not run automated check because 'shellcheck' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because 'shellcheck' needs trusty

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/362.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
