### ISSUE TITLE
Builds hanging with Coverity

### ISSUE THREAD

**Issue by arr2036** [travis-ci/travis-ci#3686]
Last couple of builds have stopped responding after starting to download the scan tool.

https://travis-ci.org/FreeRADIUS/freeradius-server/builds/58826805
https://travis-ci.org/FreeRADIUS/freeradius-server/builds/58670000

We've made no changes on our side.

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #3660.

**Comment by arr2036** [comment]
Yes, it is.
