### ISSUE TITLE
Apt package whitelist request for libiodbc2-dev libiodbc2 libpam0g-dev

### ISSUE THREAD

**Issue by arr2036** [travis-ci/travis-ci#3687]

**Comment by meatballhat** [comment]
@arr2036 did you mean for this to be a package request?  If it *is* a source request, do you have the source line needed?

**Comment by arr2036** [comment]
Yes It was meant to be package, sorry.

**Comment by meatballhat** [comment]
@arr2036 :+1: got it!

**Comment by arr2036** [comment]
@meatballhat Is there an issue with libiodbc2-dev libiodbc2 that means they can't be added?
