### ISSUE TITLE
valgrind version too old for travis-ci machines

### ISSUE THREAD

**Issue by gnzlbg** [travis-ci/travis-ci#3690]
The current valgrind version provided (3.7) has a bug (fixed in 3.10) that makes valgrind SIGSEV in the current travis-ci machines when testing software compiled with `-march=native` flag. 

The bug is: https://bugs.kde.org/show_bug.cgi?id=280835

**Comment by BanzaiMan** [comment]
I'm sorry to say, but the Precise package is old: http://packages.ubuntu.com/precise/valgrind

If you need 3.10 now, I suggest finding a PPA with a newer version and go through the process described in https://github.com/travis-ci/apt-package-whitelist.

If you really want Trusty, email support@travis-ci.com, please. We'll see what we can do.

**Comment by BanzaiMan** [comment]
Closing.

**Comment by gnzlbg** [comment]
@BanzaiMan I remember trying to look for a PPA with a newer version without success. I hope we get Trusty soon.

People of the future: I ended up using `sed` in the travis build to replace all uses of `-march=native` as follows: 

>   - sed -i 's/march=native/msse4.2/' CMakeLists.txt

IIRC sse4.2 was the "largest" architecture set supported by valgrind 3.7 in ubuntu Precise due to the bug.

**Comment by fsaintjacques** [comment]
For reference if anyone is looking for this in the future, the bug is found at this link

https://bugs.kde.org/show_bug.cgi?id=273475

any code with AVX/AVX2 instructions will fail.
