### ISSUE TITLE
"cache: ccache" shortcut does not work in the new container-based build infra

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#3691]
I am trying to enable ccache for my CI build jobs following the documentation to use
```cache: ccache```
It does not work although my ```.travis.yml``` does not have custom install step. So why it does not work?

Changing it to use arbitrary directory caching method below seems to work as expected.
```cache: { directories: $HOME/.ccache }```

**Comment by BanzaiMan** [comment]
Thanks for reporting. Do you have a build log that shows that it doesn't?

**Comment by weitjong** [comment]
Thanks for prompt reply. Here is the one that did not work (using shortcut):
https://travis-ci.org/weitjong/Urho3D/jobs/58922429

And here is the one that works (using arbitrary directory caching method):
https://travis-ci.org/weitjong/Urho3D/jobs/58933957

**Comment by BanzaiMan** [comment]
It works with `language: c`, but not with `language: cpp`.

**Comment by BanzaiMan** [comment]
Duh. I didn't implement it for C++ script. I'll fix and deploy this on Monday.

**Comment by weitjong** [comment]
Thanks in advance for this. BTW, I have also noticed a few other things regarding ccache and I will log them under separate issues when I have time today.

**Comment by weitjong** [comment]
Thanks again.

I wonder if it makes sense to enable the shortcut for ```llanguage: android``` too. In my CI setup for Android build I also need to enable the ccache support because our project uses Android NDK compiler toolchain, which is basically a GCC/Clang cross compiler toolchain. I don't think using Android NDK is unique to our project.

**Comment by thedrow** [comment]
@BanzaiMan Actually ccache makes sense when working with any language that provides C/C++ bindings.
It will speed up installing libraries from pip or rubygems as well as compilation of your own project.
