### ISSUE TITLE
mongo 3.x support?

### ISSUE THREAD

**Issue by mgenev** [travis-ci/travis-ci#3694]
For sails-mongo We'd like to update a project to mongo driver 2.0, but it requires mongodb 3.0 and the travis build breaks when we try. Is there a way to tell Travis that we want it to install version 3.0? I'm not seeing it in the docs...

https://github.com/balderdashy/sails-mongo/issues/233#issuecomment-94093296

**Comment by danscan** [comment]
+1

**Comment by BanzaiMan** [comment]
Sorry about the lag here. We would love to support MongoDB 3.0 soon. This should supersede #2246.

Note that [previous attempt to update to 2.6](https://github.com/travis-ci/travis-cookbooks/pull/350) was [abandoned](https://github.com/travis-ci/travis-cookbooks/pull/364). (The details escape me at the moment, but I beleive the procedure was incomplete.)

**Comment by fyockm** [comment]
Any movement on supporting MongoDB 3.0?

**Comment by simonmorley** [comment]
+1

**Comment by simonmorley** [comment]
Just found a work-around referenced in a commit here:

https://github.com/fauvel/CM/commit/97f4c9840b558ce86013b2182fa0cb6be757ae2a

That's got Mongo 3 working in Travis for me for the short-term.

**Comment by jeromeWeb** [comment]
+1

**Comment by bjb568** [comment]
+1

**Comment by dasfrosty** [comment]
+1

**Comment by thedrow** [comment]
You can use the new docker enabled infrastructure to pull a mongo 3.x container.

**Comment by fyockm** [comment]
this seems to be working for me now. can anyone else verify?

```
sudo: false
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
```

**Comment by thedrow** [comment]
Yeh that should also work. I forgot I requested the package to be whitelisted.

**Comment by fyockm** [comment]
And I believe this should be preferable over some of the other solutions noted here because it will run on the new container-based infrastructure.

**Comment by laike9m** [comment]
+1

**Comment by bubenkoff** [comment]
+1

**Comment by morenoh149** [comment]
has the package been requested to be whitelisted? I see no mention of mongo in https://github.com/travis-ci/apt-source-whitelist or https://github.com/travis-ci/apt-package-whitelist

**Comment by jstop** [comment]
@thedrow How are you using a docker container, because according to there [docs](https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) that is not yet possible.

**Comment by thedrow** [comment]
Sorry don't recall what I did...

**Comment by maksimf** [comment]
+

**Comment by na-ga** [comment]
+1

**Comment by Elyasin** [comment]
+1

**Comment by davemitchell** [comment]
+1

**Comment by BanzaiMan** [comment]
Mongo 3.x should be here now on Trusty images.
