### ISSUE TITLE
Feature request for creating one cache (ccache) per branch per CI job

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#3699]
I have enabled ccache for my CI build jobs in the new build infra and found that the cache hit/miss ratio was too low to be correct. In some situation the cache was totally miss, which is not possible in a local build environment where the ~/.ccache is mounted locally. My CI setup in this particular branch has 16 jobs using 4 types of compilers (Clang, GCC, x86_64-w64-mingw32-gcc, i686-w64-mingw32-gcc). If nothing was being done, that means I only got 2 caches for my branch (one for Clang and one for GCC). Yes, it lumped MinGW cache inside the GCC cache. There are two problems with Travis CI in fetching and storing the caches:

1. It downloads and uploads the cache at each build job. If there are more than one job using a same compiler type and they happen to start build at almost the same time then they download the same cache at the start of the build (this is not the problem). However, when they complete the build and upload the cache, only the cache being uploaded by the last completed job stays in S3. The others are just being overwritten. This explains the low hit ratio. The cache is only good for one CI job and not its peers.
2. For ```language: cpp``` case, the granularity is one cache per branch per compiler. This is not enough as it lumped all the GCC-derivative compilers into one and it seems there are no documented way which can modify this cache granularity. This is not good for two reasons:

    1. The cache size swell and upload/download time increase nullifying the benefit of having ccache.
    2. Most of the cached object from the other compilers are never ever going to be used, so it is a waste of space too.

IMHO the only way to get a high cache hit/miss ratio is to have one cache per branch per job (defined in that branch). It solves all the above problems at the same time. I have modified my CI build setup using an undocumented way (read: hack) to coerce Travis CI to create one cache per branch per job as I proposed above and now my CI build time is much improved. See https://travis-ci.org/weitjong/Urho3D/builds/59029591. Each cache size is less than 100MB. Below is from Debug configuration build. Release config build has even smaller cache size per job.
```
On branch docker-CI:
cache--compiler-clang-32bit-shared                  last modified: 2015-04-18 22:20:27  size: 56.44 MiB
cache--compiler-clang-32bit-static                  last modified: 2015-04-18 22:21:34  size: 55.36 MiB
cache--compiler-clang-64bit-shared                  last modified: 2015-04-18 22:18:16  size: 59.26 MiB
cache--compiler-clang-64bit-static                  last modified: 2015-04-18 22:18:43  size: 58.9 MiB
cache--compiler-gcc-32bit-shared                    last modified: 2015-04-18 22:17:55  size: 65.72 MiB
cache--compiler-gcc-32bit-static                    last modified: 2015-04-18 22:15:30  size: 65.21 MiB
cache--compiler-gcc-64bit-shared                    last modified: 2015-04-18 22:19:17  size: 72.28 MiB
cache--compiler-gcc-64bit-static                    last modified: 2015-04-18 22:19:28  size: 72.2 MiB
cache--compiler-i686-w64-mingw32-gcc-d3d9-shared    last modified: 2015-04-18 22:30:03  size: 74.5 MiB
cache--compiler-i686-w64-mingw32-gcc-d3d9-static    last modified: 2015-04-18 22:29:50  size: 63.43 MiB
cache--compiler-i686-w64-mingw32-gcc-shared         last modified: 2015-04-18 22:26:21  size: 74.42 MiB
cache--compiler-i686-w64-mingw32-gcc-static         last modified: 2015-04-18 22:26:20  size: 63.26 MiB
cache--compiler-x86_64-w64-mingw32-gcc-d3d9-shared  last modified: 2015-04-18 22:25:15  size: 85.78 MiB
cache--compiler-x86_64-w64-mingw32-gcc-d3d9-static  last modified: 2015-04-18 22:28:01  size: 71.41 MiB
cache--compiler-x86_64-w64-mingw32-gcc-shared       last modified: 2015-04-18 22:23:26  size: 85.69 MiB
cache--compiler-x86_64-w64-mingw32-gcc-static       last modified: 2015-04-18 22:26:38  size: 71.23 MiB
```
I make this feature request so that the cache granularity can be changed properly. Thanks.

**Comment by BanzaiMan** [comment]
Can we close this one, since we deployed https://github.com/travis-ci/travis-build/pull/706?

**Comment by weitjong** [comment]
Yes, you can close it. Since the cache key is now unique (provided that each jobs have different environment variable values), we do not need to rely on the ```compiler``` key "hack" anymore. Thanks again.

**Comment by BanzaiMan** [comment]
Yay!

**Comment by weitjong** [comment]
@BanzaiMan Today I just realized a minor but crucial issue with the current travis-build's setting up cache logic. Please see below two build logs before I explain the issue.
https://travis-ci.org/urho3d/Urho3D/jobs/134555844
https://travis-ci.org/urho3d/Urho3D/jobs/134650715
The first log is coming from a branch called ```Android-CI```. The second log is from a branch called ```proller-arm-Android-CI```. The latter is a new branch so cache store does not have a cache file exactly matching this new branch yet.

```
attempting to download cache archive
fetching proller-arm-Android-CI/cache-linux-precise-ae7fd984c7cc2baa0bc9be92d329bc6e5214aa9e1df105ab482c2eb979458cfe--jdk-oraclejdk8.tgz
fetching proller-arm-Android-CI/cache--jdk-oraclejdk8.tgz
fetching master/cache-linux-precise-ae7fd984c7cc2baa0bc9be92d329bc6e5214aa9e1df105ab482c2eb979458cfe--jdk-oraclejdk8.tgz
fetching master/cache--jdk-oraclejdk8.tgz
could not download cache
```

Although this is not entirely wrong because travis-build does not know ```proller-arm-Android-CI``` is related to ```Android-CI``` branch. The fallback attempt to find the matching cache file in the ```master``` branch sounds reasonable. Having said that, after your recent improvement, the cache key is actually quite unique, so I wonder whether you can enhance the logic further by attempting to search from all the "active branches" having the matching cache key instead. In this case the cache file should be found in:

```
Android-CI/cache-linux-precise-ae7fd984c7cc2baa0bc9be92d329bc6e5214aa9e1df105ab482c2eb979458cfe--jdk-oraclejdk8.tgz
```

The meaning of "active branches" is yet to be defined. But suffix to say, it may not be just ```master``` branch.

This is a minor issue though because only the initial run of this new branch would have no cache. So, we are fine if this is not fixable. We just want to bring this to your attention and basically want to be a responsible user :smiley:. We want to finish our jobs as fast as possible so the computing resources can be freed up sooner for others.

**Comment by weitjong** [comment]
Alternatively, could we have another yaml tag to describe the fallback branch name, say, ```cache_fallback_branch``` or something like that. When it is absent in the ```.travis.yml``` then it is assumed to be ```master```. Thus, it is backward compatible with the existing behavior. Then on my above particular case, I could modify my ```.travis.yml``` to read something like this:

```
cache: ccache
cache_fallback_branch: Android-CI
```

The travis-build script would then attempting to fallback to use this branch instead of simply assuming the ```master``` branch.

**Comment by weitjong** [comment]
Just want to add that for one of our build matrix on OSX build environment would even exceed 50 minutes limit in initial run, but with a reasonably good cache then it would cut down to just around 25 minutes. Since the initial run could exceed the time limit and Travis-CI simply just errors out without possibility to save those cache objects, the next CI job could not also benefit from the cache. So we actually are forced again to come up with our own custom solution to have an interrupt mechanism to skip building after reaching 40 minutes mark and exit gracefully so that Travis-CI could save our cache objects generated so far in the initial build, and the next CI build would then be able to reuse the cache and able to complete the build. In this particular case, the cache file is so important even in the initial run (because without our interrupt/continuation mechanism the job never has a chance to complete within time limit in the first place and for subsequent runs too). My point is, being able to find and use a cache file is very critical to our project.
