### ISSUE TITLE
Travis fails to execute binary file from an sh script

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [travis-ci/travis-ci#3701]
I have a script that changes the current working directory to be able to execute a compiled program in `src/test/resources`.

* [Here is the source file of the program](https://github.com/FagnerMartinsBrack/release/blob/2cc7355d1d3c865cef9a3226e998ab26d108aff5/src/test/resources/program.cpp).
* [Here is the script that changes the current working directory and execute the compiled program](https://github.com/FagnerMartinsBrack/release/blob/2cc7355d1d3c865cef9a3226e998ab26d108aff5/src/test/resources/script.sh)
* [Here is Travis, failing to find the program](https://travis-ci.org/FagnerMartinsBrack/release/builds/59048804#L2384-L2390)

When I run the tests in Ubuntu the program is found and executed, but in Travis it is not.

**Comment by FagnerMartinsBrack** [comment]
I managed to track down the root cause.

Travis is missing the 32-bit libc libraries, a workaround is adding the following in .travis.yml:

```yml
sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386
```

**Explanation:**
Necessary to enable sudo in Travis.
```yml
sudo: required
```
<hr>
Update apt-get to be able to install the required libraries
```yml
sudo apt-get update
```
<hr>
Install 32-bits libc libraries that are missing on Travis
```yml
sudo apt-get install libc6:i386 libstdc++6:i386
```
<hr>
I will leave this open because I don't know if you guys plan into providing this out-of-the-box.

**Note**

By requiring sudo I lose the possibility to use maven caching: https://github.com/travis-ci/travis-ci/issues/1441#issuecomment-94196522

**Comment by BanzaiMan** [comment]
Check the value of `$PATH`, please. Modify it, or call your executable with `./` or the absolute path.

**Comment by BanzaiMan** [comment]
The plan is to offer `sudo` on containers at some point in the future, but there is no ETA. The stop-gap measure is the apt-whitelist.

**Comment by FagnerMartinsBrack** [comment]
Any possibility to have the 32-bit libraries available by default?

**Comment by BanzaiMan** [comment]
@FagnerMartinsBrack Sorry for the delay. For the 32-bit varieties, could you open a separate issue at https://github.com/travis-ci/apt-package-whitelist? I'm closing this in the meantime.

**Comment by FagnerMartinsBrack** [comment]
:point_up: done.
