### ISSUE TITLE
APT whitelist request for fonts-humor-sans

### ISSUE THREAD

**Issue by tacaswell** [travis-ci/travis-ci#3711]
Used as part of matplotlib testing (to make sure [xkcd](http://matplotlib.org/xkcd/examples/showcase/xkcd.html) plots work correctly).

**Comment by meatballhat** [comment]
@tacaswell FYI this will also require adding `debian-sid` to `addons.apt.sources` :metal: :smiley_cat: (see https://github.com/travis-ci/apt-source-whitelist/commit/0a4762051802a9d7eae932cd5020ce7db12c5a5c)
