### ISSUE TITLE
APT whitelist request for libgammu-dev

### ISSUE THREAD

**Issue by nijel** [travis-ci/travis-ci#3714]
Please whitelist ``libgammu-dev`` for compiling programs against libgammu.

**Comment by BanzaiMan** [comment]
This one wants to daemonize, and I can't see how we are protected against careless `setgid` calls. It is supposed to be calling only `setgid`, but it's a bit more involved to investigate further.

**Comment by nijel** [comment]
The library and -dev should contain nothing like that, it's only in gammu-smsd.
