### ISSUE TITLE
APT whitelist request for postgis

### ISSUE THREAD

**Issue by r0man** [travis-ci/travis-ci#3718]
Hello,

could you please add the `postgis` package to the whitelist. There are already packages in the whitelist for specific versions, but not for the `postgis` package, which is only declared as a recommended dependency of those other packages. You can see this here:

http://packages.ubuntu.com/utopic/misc/postgresql-9.4-postgis-2.1

The `postgis` packages ships the `shp2pgsql` command line program which is needed to load shapefiles into a PostGIS database.

Thanks, Roman.

**Comment by BanzaiMan** [comment]
We have PostGIS 2.1.x installed for PostgreSQL 9.4.x now. Does it not do what you are after? Besides, the package does not exist for Precise.

**Comment by r0man** [comment]
@BanzaiMan I was looking for the `shp2pgsql` binary on the new container images, but couldn't find it. Postgis was indeed installed on those images, but not the `shp2pgsql` program, which is often needed to load shapefiles into a PostGIS database. This file package comes with the `postgis` package, which is missing on the images. I think there are only the Postgis version specific packages installed, like `postgis-2.x` etc, but not the plain`postgis` package.

**Comment by BanzaiMan** [comment]
The issue here is that our packages come from postgresql.org, so mixing with Ubuntu repo may or may not work. (Not to mention that the package you mention does not exist for Precise.)

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71798926#L277

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits.

See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71892493.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits.

See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71893992.

**Comment by BanzaiMan** [comment]
I should mention that the version on Precise is 1.5.3 (https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71896718#L153), which may not be what you want, after all.
