### ISSUE TITLE
Feature request for processing multiple documents in a single .travis.yml stream to support "virtual branch"

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#3719]
This is NOT a duplicate of issue #2873 and #2877. I would not reexplain here what is YAML ```document``` and ```stream``` as this has been discussed in earlier issues. What I am about to propose here, IMHO, should be totally backward-compatible with what Travis CI currently has and even what will be in the future in respect to CI jobs configuration. But before I do that, first let me give you a concrete use case of how thing could be improved by this feature request. My apology if this is a rather long, but I want to ensure my request is not getting shot down too quickly.

Currently in my CI setup, I have to use 5 branches (yes, five) as follow:

1. master branch with [.travis.yml](https://github.com/weitjong/Urho3D/blob/master/.travis.yml) that defines 16 jobs targeting 32-bit/64-bit Linux and Windows platforms.
2. Android-CI branch with [.travis.yml](https://github.com/weitjong/Urho3D/blob/Android-CI/.travis.yml) that defines 10 jobs targeting Android platform for different ABIs and API levels.
3. RPI-CI branch with [.travis.yml](https://github.com/weitjong/Urho3D/blob/RPI-CI/.travis.yml) that defines 4 jobs targeting Raspberry-Pi and Raspberry-Pi 2 platforms.
4. OSX-CI branch with [.travis.yml](https://github.com/weitjong/Urho3D/blob/OSX-CI/.travis.yml) that defines 10 jobs targeting 32-bit/64-bit OSX and iOS platforms.
5. Emscripten-CI with [.travis.yml](https://github.com/weitjong/Urho3D/blob/Emscripten-CI/.travis.yml) that defines 1 job targeting HTML5 platform.

There are a few reasons why I set it up this way. Our project is cross-platform. Our project is late to register for multi-os beta user. It is easier to maintain separate .travis.yml for each group of platforms (e.g. branching logic for APT package selection is much simpler than when the whole things are lumped into one document). And also we get a nice [build status image](http://urho3d.github.io/) for each branch as a bonus!

This technique works beautifully, however, it does have its own few drawbacks, such as:

1. Overhead in maintaining multiple CI-mirror branches in GitHub. The branch content is otherwise identical to master branch if not for that one extra commit at the tip to modify the .travis.yml for the respective CI-mirror branch. The mirror branches need to be constantly rebase to follow master branch too of course or Travis CI jobs for those mirror branches won't be triggered.
2. When we receive a PR, Travis CI only triggers 16 jobs defined by .travis.yml in the master branch instead of the complete suit of CI jobs setup for our project. It would be great to be able test the PR for all the platforms before merging it into master branch. There were a number of times where we got into trouble with bad PR because of this drawback.
3. When we create new topic branch, it also only "inherits" the first 16 jobs defined in master branch. So again we have a risk of bad branch being merged because only partial CI jobs are being tested.

So, here is my proposal (feature request) to improve this. Add support of loading multiple documents  in a single .travis.yml stream. Each document has a syntax of what Travis CI currently support or will support in future. When there is only one document found in the stream, the document is considered to be coming from master branch (backward compatible). When there are more documents then each additional document is considered to be coming from a ```virtual branch```. You can introduce a new hash map to define the name of the ```virtual branch``` and whether it should be considered as active (more to that later), say:
```
branch:
  name: Emscripten-CI
  active: yes
```
When the hash is not defined for the first document then it is defaulted to
```
branch:
  name: master #whatever the name of the actual branch containing the .travis.yml
  active: yes
```
for backward compatibility again. For each document that is "active", process it as per what you have currently. That is, as if the document is really coming from master branch, Emscripten-CI branch (in my example), or any other ```virtual branch``` which does not have to be really exist in GitHub. As such, the Travis CI web interface, build status images, notification, cache storage management, etc should not be impacted by this feature request (I hope). They should not be able to tell whether it is coming from a real GitHub branch or ```virtual branch```.

With this change, I could then just provide one multi-documents .travis.yml in my master branch and delete all my GitHub CI-mirror branches.
```
---
# content of my original master .travis.yml goes here
---
branch: { name: Android-CI, active: yes }
# content of my original Android-CI .travis.yml goes here
---
branch: { name: RPI-CI, active: yes }
# content of my original RPI-CI .travis.yml goes here
---
branch: { name: OSX-CI, active: yes }
# content of my original OSX-CI .travis.yml goes here
---
branch: { name: Emscripten-CI, active: yes }
# content of my original Emscripten-CI .travis.yml goes here
...
```

And here are a few potential possibilities:
- User is able to activate / deactivate a ```virtual branch``` very easily without overhead of maintaining a real Git branch.
- The existing ```[ci skip]``` feature can be enhanced to support say ```[ci vb:a,comma,separated-list,of,virtual,branch,names]```
to just process the document with matching virtual branch name even when it is set to deactivated, i.e. user is able to trigger a one-off CI job(s) on-demand.
- PRs and topic branches get the complete suit of CI jobs automatically as they get the multiple-documents .travis.yml stream from master. The only thing not so nice about this is, may be the name of the PR or topic branch may need to be prepended to the virtual branch name to form the effective virtual branch name. Using my example above, ```PR #1``` would generate multiple entries in Travis CI web interface: ```PR #1```, ```PR #1 - Android-CI```, ```PR #1 - RPI-CI```, and so on; or something like that.

I hope I have explained my idea clearly. Again sorry for the long post.

**Comment by weitjong** [comment]
I have edited the issue description to add a section to illustrate how the multi-documents .travis.yml should look like if this feature request is implemented.

**Comment by weitjong** [comment]
I have just added yet another CI mirror branch for our project setup. The new branch is for specifying a special CI job for ```Coverity Scan```. As the Coverity Scan limits the number of builds allowed, it fits into the one-off on-demand CI job that I proposed above. Currently we have to employ other mean to limit the coverity scan frequency in our Rakefile script.

Any chance this feature request will be implemented? Pretty please.

**Comment by weitjong** [comment]
FYI, I have partially implemented what I have requested in this feature request within our own CI setup.   However, since this is more like a hack to coerce Travis CI build to process multiple documents in a single .travis.yml stream, I have to still work with real Git branch (instead of "virtual branch" as I intended, should this feature is implemented properly by Travis CI build scripts). Still, it is an improvement because now these CI mirror branches can be created and deleted on the fly and as such there are no overhead in maintaining them anymore, among other benefits that I have already pointed out.

Please note that this also means all the CI mirror branches that I mentioned in my initial feature request do not exist anymore. The .travis.yml links of CI mirror branches are now invalid. Only the link to [.travis.yml](https://github.com/weitjong/Urho3D/blob/master/.travis.yml) of the master branch remains valid and it now contains multiple documents! :sunglasses:

**Comment by roidrage** [comment]
Thank you for your suggestion, but I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by weitjong** [comment]
Sure. Since I already have my own "solution" for this, the Travis-CI inability to process multiple documents in a single ```.travis.yml``` stream is not a pressing issue to me anymore.
