### ISSUE TITLE
APT whitelist request for libgvc6

### ISSUE THREAD

**Issue by tacaswell** [travis-ci/travis-ci#3720]
See build log for https://travis-ci.org/matplotlib/matplotlib/jobs/59246359

Looks like this is part of graphviz http://packages.ubuntu.com/trusty/libgvc6

**Comment by BanzaiMan** [comment]
The current builds are on Precise, so please find a PPA that has a Precise package.

**Comment by tacaswell** [comment]
I am a bit confused what being installed could be pulling in a newer library.  Could adding `debian-sid` to the sources be confusing things and pulling in too-new version of things?

**Comment by tacaswell** [comment]
For reference https://github.com/matplotlib/matplotlib/pull/4355 is the config I am playing with.

**Comment by tacaswell** [comment]
Yeah, the issues is that I had `debian-sid` in as a valid source (as per https://github.com/travis-ci/travis-ci/issues/3711) which is pulling in I assume newer versions of things which had cascading effects.

#3721 Should be handled the same as this request as I assume it is the same problem (as removing the `debian-sid` fixed both).

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libgvc6' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libgvc6' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/363.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
