### ISSUE TITLE
APT source whitelist request for ppa:kalakris/cmake

### ISSUE THREAD

**Issue by daboross** [travis-ci/travis-ci#3722]
Asking for a whitelist for the ppa:kalakris/cmake ppa, for a more recent version of cmake.
This isn't the latest version, but it is newer than what travis-ci has currently.

**Comment by Towerism** [comment]
ppa:george-edison55/cmake-3.x has an even newer version

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:kalakris/cmake' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/23.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
