### ISSUE TITLE
PHP builds don't work anymore on Travis Pro

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#3726]
PHP builds on Travis Pro started failing with the error ``phpenv: command not found``

**Comment by BanzaiMan** [comment]
Could you point to the build log URL, please?

**Comment by stof** [comment]
I saw it on https://magnum.travis-ci.com/Incenteev/Incenteev/builds/11264503

**Comment by BanzaiMan** [comment]
Looks like an issue with .org as well.

**Comment by BanzaiMan** [comment]
My theory right now is that the wrong image was chosen somehow. The current culprit is the API calls, but I could be mistaken.

**Comment by Dog** [comment]
I believe we just ran into the same problem

https://travis-ci.org/exercism/xphp/builds/59418248

**Comment by BanzaiMan** [comment]
The API issues have been resolved, and the build capacity is back to normal, although there are long back logs. Please restart the jobs that failed this way, and they should run correctly.

**Comment by stof** [comment]
closing as this indeed works again
