### ISSUE TITLE
ccache does not appear to be working correctly in the new build infra today

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#3727]
It was still OK a day ago. I use ```cache -s``` to show the stats on each build. A day ago I got something like this:
```
$ ccache -s
cache directory                     /home/travis/.ccache
cache hit (direct)                   528
cache hit (preprocessed)             392
cache miss                             0
called for link                       77
called for preprocessing               4
compile failed                         2
unsupported source language            1
unsupported compiler option            4
files in cache                      1837
cache size                          20.2 Mbytes
max cache size                     100.0 Mbytes
```

But today it just like this:
```
$ ccache -s
cache directory                     /home/travis/.ccache
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             0
files in cache                         0
cache size                             0 Kbytes
max cache size                     100.0 Mbytes
```

I also previously "good" cache in my branches turn "bad". Their size some how becomes smaller than the last time I checked using ```travis cache``` command. So, I have forced delete all of them before restarting all the jobs. But as you can see in the above output, the ccache does not seem to be working anymore. 0 files in cache after the build completed is just not possible.

**Comment by BanzaiMan** [comment]
Sorry about the issue. Could you point to the build log URLs to explain this issue?

**Comment by weitjong** [comment]
Wow. Thanks for the fast response. This is today log. https://travis-ci.org/weitjong/Urho3D/builds/59414639. The cache stats is at the end in the ```before_cache``` step.

**Comment by weitjong** [comment]
I think I may know what have happened. After you have helped me to fix the issue #3691, I haven't got the time to change all my .travis.yml to use the ```cache: ccache``` shortcut yet for the cpp language CI jobs. They still use the ```cache: { directories: $HOME/.ccache }```. And I think that's the problem.

After your fix, if the shortcut is not used then CCACHE_DISABLE environment variable is set to TRUE. So using arbitrary directory caching method will not automatically set this variable to FALSE. Only when the shortcut is used then the variable is set to FALSE.

I think it is quite confusing when Travis CI do thing such as this behind the user back. I suppose it would be best to let user to decide how to set their environment variables.

**Comment by weitjong** [comment]
BTW, not sure I should raise this as separate issue or not. If you look at my ```before_script``` step in the log, you will notice that I need to do a few more setup to make ccache actually works. I need to adjust the PATH and also create missing ccache symlinks for clang and clang++ (I have an Ubuntu 12.04 LTS VM locally and those two are in /usr/lib/ccache together with the rest).

IMHO if the documentation clearly states what environment variable is being set/reset by the shortcut then it would still be acceptable. But then, I would also expect the shortcut also adjust the PATH environment variable correctly :smiley:. i.e. setup all the required or don't do it at all and leave it to user.

**Comment by weitjong** [comment]
Update: I have time to investigate this further, I can confirm that it was caused by the CCACHE_DISABLE environment variable. I managed to resolve the issue by explicitly unsetting this environment variable in the ```before_script``` step. Currently in the ```install``` step it always export this environment variable and toggle its value from TRUE to FALSE if the ```cache: ccache``` is used, however, it seems ccache disables itself when the variable is defined regardless of its value. At least that is  what happened with the ccache version currently installed in the new container-based build infra. So, the Travis CI build script for handling the ccache has multiple issues now on my count.

**Comment by BanzaiMan** [comment]
Ah, I see. `CCACHE_DISABLE` is explicitly set to `true` in all cases, but turned off only if the shortcut `cache: ccache` is used.

Perhaps we can just not touch `CCACHE_DISABLE` at all?

**Comment by weitjong** [comment]
Yes, that would be one way to fix this. Don't export the CCACHE_DISABLE environment variable at all in the shortcut. Without adjusting the PATH environment too, ccache by itself won't come into action. In other words, using PATH environment variable you can achieve what you originally intended to do with that shortcut. Having said that, there is one other way user can activate ccache without adjusting the PATH env var. So I am in favor of don't do any other extra setup that may surprise uesers and I guess that means less documention work too.

**Comment by weitjong** [comment]
Thank you!

**Comment by weitjong** [comment]
I just tested it and it did not work for cpp language. Looking at the commit travis-ci/travis-build@dd1c0d9, it looks like the ```lib/travis/build/script/cpp.rb``` is being left out.

**Comment by BanzaiMan** [comment]
@weitjong You are right about that! I removed the specs, but forgot to push the code change. This is addressed in https://github.com/travis-ci/travis-build/commit/59a221c49908f14d4ccf9f04eac7d87fc96277d2.

**Comment by weitjong** [comment]
Thanks again. It is working now. I am restarting my last jobs again. BTW, cannot seem to restart via Travis CI web interface today. Fortunately, I can still do it via ```travis``` command line interface.
