### ISSUE TITLE
Queue priority should be modified to account for type of builder & failures in infrastructure

### ISSUE THREAD

**Issue by parkr** [travis-ci/travis-ci#3728]
Hi!!

Was just chatting with @sinthetix on IRC about [today's outage](http://www.traviscistatus.com/incidents/crzxldg09nnr). It looks like it only affects sudo-enabled (i.e. non-container-based) Linux VMs. I hopped into the IRC channel because I was confused that the container-based builds weren't booting and running. I expected only the heavy-weight Linux VMs to be held up.

If the docker containers can be booted and used without any trouble, why hold them up for heavy-weight VM builds? This is especially concerning when there's an outage that only affects one builder type, i.e. Mac, Linux, or Docker. Would it be possible to queue these separately so fast-building, fast-booting docker containers can slide by slow-booting, slow-running, sometimes broken VMs? Individual priority based on availability would seem to be A Good Plan :tm: to me, anyway. :smile: 

Thanks so much!

**Comment by rodaine** [comment]
:+1:
