### ISSUE TITLE
APT whitelist request for a list of packages on trusty.

### ISSUE THREAD

**Issue by lekshmideepu** [travis-ci/travis-ci#3734]
I would like to have the following list of packages for trusty: (sorry for the long list..)

ipython3, original-awk, autoremove, indent, python-debian, python-matplotlib, python-tk, python-coverage, python-setuptools, python-mpi4py, openmpi-doc, python3-all-dev, python3-numpy, python3-scipy, python3-nose, cython, libghc-readline-dev, python-django, python-django-tagging, python-svn, git-svn, python-cheetah, python-jinja2, python-mock, python-tk, python-gmpy, python-imaging-tk, cvs e2fsprogs gettext libpackagekit-glib2-dev groff libssh2-1-dev python-libssh2 slang-gsl libncurses5-dev check, cppcheck, vera++

**Comment by BanzaiMan** [comment]
Did not run automated check because 'a list of packages on trusty.' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because 'a list of packages on trusty.' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for a list of packages on trusty.' is ambiguous. Please specify only one.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/364.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
