### ISSUE TITLE
Maven repository caching appears to corrupt jars

### ISSUE THREAD

**Issue by headius** [travis-ci/travis-ci#3745]
Yesterday we (jruby/jruby) were investigating a problem with one of our maven artifacts and opted to reset maven caches and restart builds. During the course of the day, the build got steadily more and more unstable, reporting missing classes, corrupted jars, and other nonsensical errors. For example, one of the worst builds: https://travis-ci.org/jruby/jruby/builds/59463418

After ensuring builds were working ok for us locally, we again flushed maven caches and restarted some builds. This time, most jobs succeeded but a few still failed with issues that appeared to be caused by corrupt jar files: https://travis-ci.org/jruby/jruby/jobs/59485193

Finally we opted to disable the maven cache, and our builds went green (modulo a few fixes that snuck in during red times).

It seems like the caching has some problems. To me it feels like a concurrency issue...like multiple concurrent builds are stepping on each other when updating the cache.

**Comment by headius** [comment]
Worth pointing out that JRuby has a large number of jobs per build, so when we get queued up 10 jobs will hit the fan immediately. Great opportunity for a concurrency issue to mess things up.

**Comment by weitjong** [comment]
This sounds similar to my issue #3699. The difference is mine happened with ```ccache``` $HOME/.ccache, while yours with maven repository $HOME/.m2. I believe the root cause is the same though. The current cache granularity is not at each job level. Sharing a cache with multiple concurrent jobs thrash the cache.

**Comment by BanzaiMan** [comment]
We will be working to address this issue *soon*.

**Comment by joshk** [comment]
@BanzaiMan do you know what the issue is?

**Comment by BanzaiMan** [comment]
This is probably a cache corruption. Will continue in #4393.
