### ISSUE TITLE
travis-build - non-container addons-apt still applies whitelist

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#3748]
<pre>
sudo: required

language: cpp
compiler: gcc
#  - clang
cache:
  - apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - automake1.9
      - dpatch
      - libaio-dev
</pre>

when building in a non-container the whitelist of packages still applies.

https://travis-ci.org/openquery/mariadb-server/builds/59636717

**Comment by BanzaiMan** [comment]
We should discard `addons.apt` if `sudo: required`.

**Comment by grooverdan** [comment]
> We should discard addons.apt if sudo: required.

I wouldn't rush to this. Supporting addons.apt in sudo: required provides an easier migration path to/from container builds without maintaining two different forms of a dependency list.

**Comment by BanzaiMan** [comment]
By "discard", I mean dropping the configuration data, so that the build script doesn't execute anything related to the addon.

**Comment by grooverdan** [comment]
I understood discard to mean the same thing. When migrating to container builds this is the first thing you change. There may be a couple of remnant sudo requiring things left. Having addons.apt working in sudo: required mode is useful, it just would be slightly more useful if the whitelist didn't apply as that way a configuration can be ready for an easy switch to sudo: false when the package is whitelisted.

**Comment by BanzaiMan** [comment]
I guess I misunderstand the purpose of this issue, then. If this is the desired behavior, then this is a non-issue, right?

**Comment by grooverdan** [comment]
It would be useful if the whitelist didn't apply when sudo: required. Currently it does. If you add a package that isn't whitelisted and have sudo: required, the build will fail.

If the whitelist didn't apply for addons.apt, a configuration can be ready and tested in sudo: required, ready for an easy switch to sudo: false, when the all the required packages are whitelisted.

so this is a feature request.

**Comment by BanzaiMan** [comment]
I apologize for being a bit slow here, but I am still unclear what is requested.

With the current behavior, I expect the following scenario to unfold:

1. The user starts out with a functioning `.travis.yml` with `sudo apt-get install`.
1. The user sets up the equivalent `addons.apt` and removes `sudo apt-get install`. If the build passes, great. If not, we identify which packages are disabled (see, for example, https://travis-ci.org/openquery/mariadb-server/builds/59636717#L103); notice that we install the ones that are whitelisted. (The user can also look at https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise)
1. Once the build passes with `sudo: required`, the user can switch to `sudo: false`.

What did I miss?

**Comment by grooverdan** [comment]
I was looking at the possibility of whitelisting being disabled during sudo: required but as you point out there is an easy work around. You've got plenty of other tickets in the queue.
