### ISSUE TITLE
[RFE] Log the version of git in the "Build system information"

### ISSUE THREAD

**Issue by Fryguy** [travis-ci/travis-ci#3756]
There are version numbers for many other packages, but git has been left out.  This could be useful if any scripting is written to leverage git.

**Comment by BanzaiMan** [comment]
`git --version` appears further down in the logs.

**Comment by jrafanie** [comment]
@BanzaiMan I don't see it here:  https://s3.amazonaws.com/archive.travis-ci.org/jobs/59555884/log.txt

**Comment by BanzaiMan** [comment]
Hmm. I guess I was mistaken.

**Comment by BanzaiMan** [comment]
What is `[REF]`, by the way?

**Comment by BanzaiMan** [comment]
This will be addressed in the next build env update (with https://github.com/travis-ci/system_info/commit/f553edd15d3274fa2630f846e9810e66ab0d13c7).

**Comment by jrafanie** [comment]
No worries @BanzaiMan.  Thanks.  I think it means request for enhancement.

**Comment by Fryguy** [comment]
RFE = request for enhancement

Working in enterprise software for so many years has ruined me.  :)

**Comment by Fryguy** [comment]
@BanzaiMan Out of curiosity, how often do you rebuild the envs?  I noticed that commit was from Mar. 4.

**Comment by BanzaiMan** [comment]
@Fryguy Every 2 months. http://docs.travis-ci.com/user/build-environment-updates/

**Comment by BanzaiMan** [comment]
It should be there now.
