### ISSUE TITLE
When using ghc version 7.2 in .travis.yml instead of failing it instead continues using 7.4.1

### ISSUE THREAD

**Issue by taladar** [travis-ci/travis-ci#3764]
ghc_find: error, no such version 7.2

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.4.1

The expected result would be that it either uses the version specified or, if that version is not available, fails. It should never use a different version and continue the build which I would consider a silent failure.

**Comment by lwm** [comment]
Duplicate of https://github.com/travis-ci/travis-ci/issues/7807 or?

**Comment by BanzaiMan** [comment]
Closing in favor of #7807.
