### ISSUE TITLE
APT whitelist request for qtbase5-dev

### ISSUE THREAD

**Issue by equalsraf** [travis-ci/travis-ci#3765]
Cheers

For Qt5 development, the ubuntu-sdk-team ppa was whitelisted in #3685, but the Qt packages still need to be whitelisted. There is a bunch of them, hopefully these are enough to get most people using Qt5 with Travis containers

qtbase5-dev, qtbase5-dev-tools, qtsensors5-dev, qtconnectivity5-dev, qt5-qmake, qt5-default, qtdeclarative5-dev, qtmultimedia5-dev, qtscript5-dev, qtxmlpatterns5-dev-tools, qtdeclarative5-dev-tools, qt5-image-formats-plugins

**Comment by grtlr** [comment]
:+1: I would also love to see these packages added.

**Comment by BanzaiMan** [comment]
This package does not exist for Precise: http://packages.ubuntu.com/precise/qtbase5-dev

Do you know of a PPA that does for Precise?

**Comment by equalsraf** [comment]
From #3685

deb http://ppa.launchpad.net/ubuntu-sdk-team/ppa/ubuntu precise main
deb-src http://ppa.launchpad.net/ubuntu-sdk-team/ppa/ubuntu precise main

**Comment by elken** [comment]
Any progress on this? We need these for container builds.

**Comment by lolzballs** [comment]
@BanzaiMan the ppa that adds it (ubuntu-sdk-team) is already whitelisted.

**Comment by coorasse** [comment]
How can use qt5 in the new container base infrastructure? Sudo is forbidden, right?

**Comment by The-Compiler** [comment]
You can't (at least not easily), currently. Doing something like downloading/unpacking the debian package by hand to ~ and then fixing up stuff might or might not work.

**Comment by elken** [comment]
You can't because they're not whitelisted.
qt4 packages are already in, so you can easily.

**Comment by equalsraf** [comment]
Alternatively there is also this PPA (https://launchpad.net/~beineri/+archive/ubuntu/opt-qt541) that is [expected to support Qt 5.5 too](http://forum.qt.io/topic/50340/installing-qt-5-4-dev-packages-in-travis-ci/).

**Comment by elken** [comment]
There's already a PPA whitelsited that fully supports qt5.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'qtbase5-dev and other Qt5 dev packages' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'qtbase5-dev and other Qt5 dev packages' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for qtbase5-dev and other Qt5 dev packages' is ambiguous. Please specify only one.

**Comment by elken** [comment]
Only one isn't enough. `qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` is all _I_ need.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 libqt5core5a libqt5gui5 libqt5libqgtk2 libqt5network5 libqt5opengl5 libqt5sql5 libqt5sql5-mysql libqt5sql5-odbc libqt5sql5-psql libqt5sql5-sqlite libqt5sql5-tds libqt5xml5 libqt5dbus5 libqt5test5 libqt5concurrent5 libqt5widgets5 libqt5printsupport5 qtbase5-dev qtbase5-private-dev libqt5opengl5-dev qtbase5-dev-tools qt5-qmake qtbase5-examples qtbase5-dbg qtbase5-dev-tools-dbg qtbase5-examples-dbg qt5-default qtbase5-doc-html

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72482793.

**Comment by The-Compiler** [comment]
Those indeed look benign to me. :wink:

**Comment by elken** [comment]
Yeah they all are :p They're just referencing functions that _check_ for setuid, they don't actually modify it.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/365.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
