### ISSUE TITLE
travis-build error "no implicit conversion of Symbol into Integer"

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#3766]
Build output resulted:
<pre>
Using worker: worker-linux-da6418d7-1.bb.travis-ci.org:travis-linux-12

An error occurred while compiling the build script: no implicit conversion of Symbol into Integer

Test your configuration file with http://lint.travis-ci.org.
</pre>

build:

https://travis-ci.org/openquery/mariadb-server/jobs/60081675

yaml:

https://github.com/openquery/mariadb-server/blob/4ceff60ffb534d69a57afafeb1f02feab695052f/.travis.yml

**Comment by grooverdan** [comment]
removed unused/incomplete coverity addon and the build error went away: https://github.com/openquery/mariadb-server/commit/cbea125c04e41aecdf855aab534daeee648253d4

**Comment by BanzaiMan** [comment]
I think this was a bad data structure in `addons.coverity_scan.project`, which should be a map, not an array. https://docs.travis-ci.com/user/coverity-scan/#travis.yml
