### ISSUE TITLE
Deploy on heroku from a subdirectory

### ISSUE THREAD

**Issue by luzfcb** [travis-ci/travis-ci#3767]
Hello, I need to deploy to heroku from a subdirectory.

I found nothing in the [travis heroku documentation](http://docs.travis-ci.com/user/deployment/heroku/) on how to set this up.

I sent the following message to support@travis-ci.com several days ago, but no any response yet. 

> Hello, I have some doubts on how to properly configure deploy to Heroku.
> 
> All doubts are based on [.travis.yml](https://github.com/luzfcb/cookiecutter-django/blob/test-deploy/.travis.yml) and [deploy_by_travis.sh](https://github.com/luzfcb/cookiecutter-django/blob/test-deploy/deploy_by_travis.sh) files, avaliable on this branch
> 
> https://github.com/luzfcb/cookiecutter-django/tree/test-deploy
> 
> First the context of what I want to do:
> 
> cookiecutter-django is a django based project template.
> To generate a new design based on the template, normally I would:
> 
> ```
> pip install cookiecutter
> cookiecutter https://github.com/luzfcb/cookiecutter-django.git
> ```
> 
> such as the objective is a test, I do it in 
> https://github.com/luzfcb/cookiecutter-django/blob/test-deploy/deploy_by_travis.sh#L11-L25
> https://github.com/luzfcb/cookiecutter-django/blob/test-deploy/deploy_by_travis.sh#L39-L42
> 
> and the project is generated in cookiecutter-django-demo folder
> 
> The questions are:
> 1. how I set .travis.yml to deploy on heroku from a project located in a subdirectory
> 2. what is the right way to set Heroku addons and environment variables, such as I do in:  https://github.com/luzfcb/cookiecutter-django/blob/test-deploy/deploy_by_travis.sh#L98-L114
> 
> This documentation is not explicit enough to handle with such cases (at least for me, that I am not native English speaker): 
> http://docs.travis-ci.com/user/deployment/heroku/ 
> 
> Thanks!

**Comment by luzfcb** [comment]
related: https://github.com/travis-ci/dpl/issues/254

**Comment by BanzaiMan** [comment]
Does Heroku API allow such a maneuver?

**Comment by maul-esel** [comment]
Workaround: `cd` into the directory you want to deploy in `before_deploy`. Works for me.

**Comment by ajoys** [comment]
Have you found a solution?

**Comment by BanzaiMan** [comment]
@ajoys I think @maul-esel just showed it. Did it not work for you?

**Comment by MoonTahoe** [comment]
I am trying to deploy only the artifacts in my `./build` folder. The build process creates some additional subfolders and files under the `./build` folder, that are not tracked in the repo. The `cd ./build` command on `before_deploy` seem to work, it only deploys contents that are being tracked by the repo under ./build folder.  However, Travis does not deploy any of the artifacts in that folder. I tried to use `skip_cleanup: true` to make sure these files make it to heroku, but it does not seem to be working.  What am I doing wrong?

```
language: node_js
node_js:
  - 4.6.1
  - 6.9.1

before_deploy:
  - cd ./build

deploy:
  provider: heroku
  api_key: [my api info]
  skip_cleanup: true
  app: [my app]
  on:
    repo: [my repo]
    branch: master
```

**Comment by BanzaiMan** [comment]
@MoonTahoe https://travis-ci.org/eveporcello/moonhighway/jobs/177836528#L1243 says your app is on Cedar-10 stack, which no longer is supported by the API. Try updating your app's stack.
