### ISSUE TITLE
Wrong Image for build status. 

### ISSUE THREAD

**Issue by ankithbti** [travis-ci/travis-ci#3768]
My Build is passing and green, but in Image it's still shows as failed.
Link for my repo: https://travis-ci.org/ankithbti/newHttpServerOnMac

Please assist me to correct this issue.

**Comment by ankithbti** [comment]
Any update on this ?

**Comment by BanzaiMan** [comment]
Sorry for the late response. When you have a green build again, could you ping us? Thanks.

**Comment by ankithbti** [comment]
Hi Hiro,

Its green right now, but image is still shows failing. :(

Thanks & Regards
Ankit

**Comment by BanzaiMan** [comment]
This should be good for you now.

**Comment by ankithbti** [comment]
Yup....its green now.....what was the issue ?

**Comment by BanzaiMan** [comment]
The cache gets out of sync sometimes, and we need to manually intervene.

**Comment by ankithbti** [comment]
Ok. Thanks a million.
