### ISSUE TITLE
APT source whitelist request for Groonga

### ISSUE THREAD

**Issue by kou** [travis-ci/travis-ci#3770]
Groonga APT repository exists on Launchpad: https://launchpad.net/~groonga/+archive/ubuntu/ppa

We can use `ppa:groonga/ppa` for apt-line.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'Groonga' needs source whitelisting

**Comment by kou** [comment]
Could you tell me what should I do for source whtielisting?

**Comment by BanzaiMan** [comment]
Please consult the instructions here: https://github.com/travis-ci/apt-source-whitelist

**Comment by kou** [comment]
Thanks for your answer but I couldn't understand what I should do.
Maybe what I should do is "Please be patient".

**Comment by BanzaiMan** [comment]
@kou Ah, I understand now. Sorry for the confusion.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/24.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
