### ISSUE TITLE
travis-build: preserving the status in $?

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#3771]
Whether make succeeds or fails $? is always 1.
<pre>
script:
  - make -j 4
  - COMPILE_RESULT=$?
  - echo COMPILE_RESULT=${COMPILE_RESULT}
</pre>

output:
<pre>
..
The command "make -j 4" exited with 0.

$ COMPILE_RESULT=$?
The command "COMPILE_RESULT=$?" exited with 0.

$ echo COMPILE_RESULT=${COMPILE_RESULT}
COMPILE_RESULT=1
</pre>

**Comment by BanzaiMan** [comment]
Each line in the `script` section is processed by the [travis_cmd](https://github.com/travis-ci/travis-build/blob/01cd2df860d076fd9dd7d803efed9b0b4bc672fc/lib/travis/build/templates/header.sh#L12-L54) `bash` function. (The value `1` coms from the immediately preceding test `[[ -n "$retry" ]]` on line 38.)

I understand the motivation for using `$?` this way (and potentially other special variables) in the script section, but achieving it without breaking the currently working builds may be hard.

I tend to think it is better to document this behavior, and advise writing a custom script if the user wants to do something involving `$?` in the script section.

**Comment by grooverdan** [comment]
I think anyone who's tried to use $? has come across this limitation and avoided it by writing a custom script (like I should be doing now). Thanks for the prompt response.

**Comment by BanzaiMan** [comment]
I've noted this in http://docs.travis-ci.com/user/customizing-the-build/#Note-on-%24%3F. (Improvement suggestions welcome!)

I'm closing this now.

**Comment by weitjong** [comment]
The trick is, you have to get it right after the command.
```
make -j4; export COMPILE_RESULT=$?
```

Though in my .travis.yml I usually just combine the command using "&&" or "||" bash operator or inside another ```if``` statement, so I don't really need to use ```$?``` explicitly to get the exit status of the earlier command. e.g.:
```
make -j4 && other-cmd-to-execute-when-make-was-successful
```
or
```
make -j4 || other-cmd-to-execute-when-make-was-failed
```

**Comment by grooverdan** [comment]
@BanzaiMan , while I'm still not convinced that there is a person using `$?` to extract the value of `[[ -n "$retry" ]]` the alternative for documentation is here:

<pre>
- COMPILE_RESULT=0 ; make -j4 || COMPILE_RESULT=$?; expr $COMPILE_RESULT != 0
- [ $COMPILE_RESULT -ge 2 ] && echo makefile error
</pre>

So the two objectives in deciding this structure where to make $COMPILE_RESULT have the value of the return and to give travis a true/false indicator of the result of the compile. @weitjong suggestions are of course valid (though export is excessive)  however sometime additional flexibility is needed.

**Comment by BanzaiMan** [comment]
Improvement to the documentation is also welcome!

**Comment by ryansmith94** [comment]
Thanks @weitjong :+1:

**Comment by wiprodev** [comment]
Does Travis capture the non zero exit code for init scripts like `sudo service xyz start` ? In my case though the service fails to start it shows build successful.

**Comment by JenniferBrooks39** [comment]
I’m hopeful:)
