### ISSUE TITLE
C#: Mono fails to install: Untrusted GPG

### ISSUE THREAD

**Issue by muhqu** [travis-ci/travis-ci#3776]
Our builds for [cucumber/gherkin3](https://travis-ci.org/cucumber/gherkin3) started to fail because it was unable to install 'Mono': see https://travis-ci.org/cucumber/gherkin3/jobs/60265021 for an example...
```
C# support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry
Installing Mono
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.IB4CbU8d5B --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
gpg: key D3D831EF: public key "Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
12.14s1.02sE: Unable to correct problems, you have held broken packages.
The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .
Your build has been stopped.
```

Any advise?

/cc @joshua-anderson @akoeplinger @nterry @aslakhellesoy

**Comment by akoeplinger** [comment]
Mono 4.0 was just released and looks like there are some issues with the packages (i.e. it currently breaks for everyone). I'm looking into it :)

**Comment by akoeplinger** [comment]
If you need a short-term workaround, specify `mono: 3.12.0` in .travis.yml.

**Comment by muhqu** [comment]
@akoeplinger thanks, I'll try out `mono: 3.12.0`

**Comment by akoeplinger** [comment]
I just heard back from the developer, looks like the issue is the fsharp package. It'll get fixed shortly.

**Comment by muhqu** [comment]
@akoeplinger thanks for the help, `mono: 3.12.0` [works just fine](https://travis-ci.org/cucumber/gherkin3/builds/60271074)

If you could let us know when its supposed to work again with `mono: latest`, that would be great... :smile_cat:

**Comment by obrakmann** [comment]
I'd like to echo the sentiment, thanks for your efforts, much appreciated!

**Comment by akoeplinger** [comment]
Update: after the fsharp package problem was fixed we ran into another problem that'll take until tomorrow to be resolved. To un-break people, I made a hotfix on the Travis side to stick with 3.12.0 as the latest Mono for everyone. Sorry for the inconvenience ;)

**Comment by nterry** [comment]
@akoeplinger Mono 4 is early release/alpha, not released yet.

**Comment by akoeplinger** [comment]
@nterry believe me, it is released (run apt-get update && upgrade if you don't believe me :) )

**Comment by BanzaiMan** [comment]
Is there anything to do here?

**Comment by akoeplinger** [comment]
@BanzaiMan The issues are resolved upstream, but I wanted to wait a bit until the dust around //build settles before I roll back the hotfix.
