### ISSUE TITLE
error with elixir 1.0.4 / otp 17.5 in 2015/4/27 rollout

### ISSUE THREAD

**Issue by adamkittelson** [travis-ci/travis-ci#3777]
Support for otp 17.5 and elixir 1.0.4 was rolled out today but I'm getting errors in my builds.

For example in this build https://travis-ci.org/zencoder/zencoder-ex/builds/60265446

It blows up when checking the version of elixir after activating otp 17.5

````
source $HOME/otp/17.5/activate
kiex
Using Elixir 1.0.4
$ elixir --version
{"init terminating in do_boot",{{badmatch,{error,{elixir,{bad_return,{{elixir,start,[normal,[]]},{'EXIT',{{badmatch,{error,enotsup}},[{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,272}]}]}}}}}}},[{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,75}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
````

**Comment by BanzaiMan** [comment]
It appears that OTP Release 17.5 seems broken.

**Comment by BanzaiMan** [comment]
Thanks for the reports and we are really sorry for the issues. We are going to roll back the latest 2014-04 updates at 2015-04-28 1300 UTC. Cancel the 2014-04 updates altogether and concentrate on the next update and a better long-term planning.

See the details: http://stspg.io/10Su

**Comment by BanzaiMan** [comment]
This might have been an issue with Elixir 1.0.4 that we built with `kiex` (which was pre-installed on the April image). The newer scheme (installation with pre-built packages) seems to work better.

**Comment by BanzaiMan** [comment]
On-demand installation of 17.5 is now possible. We'll revisit the build env issue when we plan the next one.

Closing.
