### ISSUE TITLE
Cannot install Mono after environment update?

### ISSUE THREAD

**Issue by kpstolk** [travis-ci/travis-ci#3780]
It looks like that the [Environment updates](http://www.traviscistatus.com/incidents/yk24wrkb4082) caused that Mono can't be installed anymore? I get an error while building (also with builds that did pass before):

> Installing Mono
> Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.TghxEJZ3Ru --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
> gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
> gpg: key D3D831EF: public key "Xamarin Public Jenkins (auto-signing) releng@xamarin.com" imported
> gpg: no ultimately trusted keys found
> gpg: Total number processed: 1
> gpg:               imported: 1  (RSA: 1)
> 16.08sW: Size of file /var/lib/apt/lists/ppa.launchpad.net_rwky_redis_ubuntu_dists_precise_main_binary-amd64_Packages.gz is not what the server reported 609 612
> W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-backports_main_source_Sources.gz is not what the server reported 5479 5482
> W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-backports_multiverse_source_Sources.gz is not what the server reported 5886 5888
> W: Size of file /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_precise-security_multiverse_binary-amd64_Packages.gz is not what the server reported 2253 2256
> W: Size of file /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_precise-security_multiverse_binary-i386_Packages.gz is not what the server reported 2437 2439
> 2.33sE: Unable to correct problems, you have held broken packages.
> The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .
> Your build has been stopped.

**Comment by kpstolk** [comment]
@joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
Please see https://github.com/travis-ci/travis-ci/issues/3776

**Comment by kpstolk** [comment]
Thanks, didn't see that other issue ;-)

**Comment by BanzaiMan** [comment]
Thanks for the reports and we are really sorry for the issues. We are going to roll back the latest 2014-04 updates at 2015-04-28 1300 UTC. Cancel the 2014-04 updates altogether and concentrate on the next update and a better long-term planning.

See the details: http://stspg.io/10Su
