### ISSUE TITLE
MySQL failures mid-build after 2015-04 update

### ISSUE THREAD

**Issue by cjsaylor** [travis-ci/travis-ci#3781]
Example (private) build that contains the issue: https://magnum.travis-ci.com/zumba/service/jobs/16784895

The build template includes a `mysql` cli command to import database schema of which succeeds.

Midway through the build, we started to see: 

```
PDOException: SQLSTATE[HY000] [2002] No such file or directory
```

I tried changing the connection parameters to use a TCP address instead of `localhost`, and in place of seeing No such file or directory, it would show:

```
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
```

**Comment by BanzaiMan** [comment]
In general, connecting over TCP with `127.0.0.1` as opposed to over the socket at `/var/run/mysqld/mysqld.sock` should work, although @cjsaylor's last case above seems a little different.

**Comment by cjsaylor** [comment]
@BanzaiMan Is there an additional workaround that we can do for the time being?

**Comment by Xety** [comment]
I have the same issue https://travis-ci.org/Xety/Xeta/jobs/60306567 (It worked fine before the update)

**Comment by baldurrensch** [comment]
Same issue here

**Comment by ypresto** [comment]
We have below error after update.

```
Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

https://magnum.travis-ci.com/maychannel-dev/server/builds/11442277 (travis pro)

**Comment by bc-petrkotek** [comment]
Same issue here.

@travis-ci Is there a plan to support connection via `/var/run/mysqld/mysqld.sock` or not?

(note that connecting via TCP works fine; that can be usually forced by specifying `127.0.0.1` as hostname rather than `localhost` or `NULL`)

**Comment by BanzaiMan** [comment]
Thanks for the reports and we are really sorry for the issues. We are going to roll back the latest 2014-04 updates at 2015-04-28 1300 UTC. Cancel the 2014-04 updates altogether and concentrate on the next update and a better long-term planning.

See the details: http://stspg.io/10Su

**Comment by ryantpt** [comment]
Thanks for the update! #same_issue

**Comment by cosmo0920** [comment]
Thanks for the update!
Same issue here. And sometimes get a following error with randomly:

```log
checking for mysql_config... mysql_config
configure: error: You don't have mysql_version.h. Please install development package of MySQL.
```

It occurred this build: https://travis-ci.org/project-hatohol/hatohol/jobs/60328753

**Comment by cjsaylor** [comment]
@BanzaiMan Thank for the update. Sorry you have to rollback :(.

**Comment by rayward** [comment]
Any word on when 5.6 is going to be made available again?

**Comment by rramsden** [comment]
Also curious about this :+1: any updates?

**Comment by roidrage** [comment]
Closing this issue as the breakage was resolved with the rollback.

We'll post news on MySQL 5.6 updates in other tickets/channels.
