### ISSUE TITLE
`nvm` tests fail with 2015-04 update

### ISSUE THREAD

**Issue by ljharb** [travis-ci/travis-ci#3782]
This test: https://github.com/creationix/nvm/blob/master/test/install_script/nvm_reset fails. It's exercising this [code](https://github.com/creationix/nvm/blob/master/install.sh#L237-L241).

I SSHed into a test instance, and on the command line, `foo() { echo; } ; unset -f foo ; type foo` works as expected, but I was able to reproduce the test failure. However, on my local machine, I could not.

Documenting here for posterity.

**Comment by ljharb** [comment]
@BanzaiMan were we ever able to resolve this one?

**Comment by BanzaiMan** [comment]
@ljharb Is it still a problem? We rolled back this update, so I'm not sure if it's relevant today. If it is, do let us know.

**Comment by ljharb** [comment]
In that case, sounds like we're good :-)
