### ISSUE TITLE
Mono SIGSEGV in nuget restore

### ISSUE THREAD

**Issue by sapek** [travis-ci/travis-ci#3783]
This might be related to the April update. [Log](https://travis-ci.org/Microsoft/bond/jobs/60334604).

~~~
Native stacktrace:
	/usr/bin/cli() [0x4b1d6c]
	/usr/bin/cli() [0x50833e]
	/usr/bin/cli() [0x428bfd]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0xfcb0) [0x7f020d227cb0]
	/usr/bin/cli() [0x513767]
	/usr/bin/cli(mono_binary_search+0x40) [0x623a60]
	/usr/bin/cli(mono_class_interface_offset+0x1f) [0x514abf]
	/usr/bin/cli() [0x5245eb]
	/usr/bin/cli() [0x4b4548]
	[0x40e86046]
Debug info from gdb:
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/home/travis/build.sh: line 41: 19049 Aborted                 $NUGET restore cs/cs.sln
~~~

**Comment by akoeplinger** [comment]
This should be fixed now.

**Comment by BanzaiMan** [comment]
Closing this optimistically based on @akoeplinger's comment above.

**Comment by HelloKitty** [comment]
Encountered the same issue this morning.

**Comment by akoeplinger** [comment]
@HelloKitty can you link to a log? Does it happen consistently?

**Comment by HelloKitty** [comment]
Sorry, I was just about to correct my post to reflect that it likely was the result of not enabling NuGet Restore on the solution. Moq was unrelated and after enabling NuGet Restore on the solution I did not encounter the issue.

**Comment by akoeplinger** [comment]
@HelloKitty thanks, though a SIGSEGV should never happen under normal circumstances (not enabling NuGet Restore was likely just a conincidence here). Unfortunately it seems to happen **really** rarely so we couldn't repro it yet, but let me know if you encounter it again :)

**Comment by HelloKitty** [comment]
@akoeplinger Hmmmm, well in that case here is the [log](http://pastebin.com/iCTMrALd) it's a private repo so I made a pastebin. I hope it can help in some fashion.

**Comment by akoeplinger** [comment]
@HelloKitty Thanks!

**Comment by HelloKitty** [comment]
Occurred again with no real major change. Just a small diff that filled out an interface in C#. Here is the [log](http://pastebin.com/RS71uL4u). As you can see the diff is not much http://imgur.com/z3e86yk and nothing of function at all was added.

**Comment by akoeplinger** [comment]
Yeah, this has nothing to do with your code since it's restoring nuget packages that triggers the Mono bug. It might be fixed in the upcoming release but without a consistent repro it's impossible to tell.
