### ISSUE TITLE
GHC 7.10

### ISSUE THREAD

**Issue by kazu-yamamoto** [travis-ci/travis-ci#3785]
I would like to use GHC 7.10 with the following `.travis.yml`:

```
ghc:
    - "7.10"
```

But it seems to me that GHC 7.10 is not prepared yet. Would you install GHC 7.10 to Travis CI?

**Comment by asr** [comment]
:+1:

**Comment by khibino** [comment]
:+1:

**Comment by juhp** [comment]
:+1:

**Comment by notogawa** [comment]
:+1:

**Comment by BanzaiMan** [comment]
We'll plan this for the next 2015-06 update.

**Comment by solarce** [comment]
We understand the frustration with the delay here. We are working towards when we'll have an ETA on our next Precise build environment update but do not have something to share yet. 

In the mean time I'd invite you to review https://github.com/ucsd-progsys/liquidhaskell/blob/master/.travis.yml for a recipe for having 7.10 in your builds.

Thanks for your patience.

**Comment by BanzaiMan** [comment]
It's available on Trusty now.
