### ISSUE TITLE
Build breaks for hhvm-nightly

### ISSUE THREAD

**Issue by fpietka** [travis-ci/travis-ci#3788]
Since update, `composer self-update` seems to require sudo on hhvm-nightly. Since we're using docker, we don't have sudo enabled.

```
$ composer self-update
Installing last hhvm-nightly!
sudo: must be setuid root
```

**Comment by fpietka** [comment]
In fact, even without self-update, it is failing later:
```
composer config github-oauth.github.com [...]
Installing last hhvm-nightly!
sudo: must be setuid root
```

**Comment by BanzaiMan** [comment]
I dug into this in a bit more detail. It appears that `hhvm-nightly` installation is broken at the moment.

If you try this directly, you'd get:

```sh-session
$ sudo apt-get install hhvm-nightly
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libbison-dev libgeos-3.2.2
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  hhvm
The following NEW packages will be installed:
  hhvm-nightly
0 upgraded, 1 newly installed, 1 to remove and 107 not upgraded.
Need to get 24.8 MB of archives.
After this operation, 0 B of additional disk space will be used.
Err http://dl.hhvm.com/ubuntu/ precise/main hhvm-nightly amd64 2015.04.24~precise
  404  Not Found
Failed to fetch http://dl.hhvm.com/ubuntu/pool/main/h/hhvm-nightly/hhvm-nightly_2015.04.24~precise_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
$ sudo apt-get update -qq
$ sudo apt-get install hhvm-nightly
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hhvm-nightly
```

Subsequently, `phpenv` tries to install `hhvm-nightly` by itself, but at that point `sudo` is disabled, and that, as well as `composer self-update` would fail.

My immediate guess is that there is a change in HHVM repository, but I don't know how we should fix it yet.

**Comment by BanzaiMan** [comment]
This is unrelated to the 2015-04 build env update.

**Comment by BanzaiMan** [comment]
HHVM team stopped building Precise packages, I believe.

http://dl.hhvm.com/ubuntu/dists/precise/main/binary-amd64/

**Comment by BanzaiMan** [comment]
See https://github.com/facebook/hhvm/issues/5220

**Comment by BanzaiMan** [comment]
Facebook has decided to stop building `hhvm-nightly`. As such, I'm afraid we are unable to continue supporting it on Travis CI until we roll out Trusty support.

Sorry for the inconvenience.
