### ISSUE TITLE
Rails4+postgresql failed

### ISSUE THREAD

**Issue by Javix** [travis-ci/travis-ci#3792]
My build failed with no reason: https://travis-ci.org/Javix/jlc-invest/builds/60348484.

**Comment by BanzaiMan** [comment]
Did you restart the failing build, which subsequently passed? Do you have the log?

**Comment by Javix** [comment]
Yes, everything came back to normal after the promised rollback: I restarted the build and it is germane now. So, I'll close the issue. Thank you for your feed back.
