### ISSUE TITLE
APT source whitelist request for protobuf

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#3794]

**Comment by BanzaiMan** [comment]
Hello. Where does one get this for Precise? Ubuntu repo does not have it. http://packages.ubuntu.com/precise/protobuf-dev

**Comment by thedrow** [comment]
The package name is **libprotobuf-dev** as mentioned in the title. http://packages.ubuntu.com/precise/libprotobuf-dev
Also please whitelist the protobuf compiler http://packages.ubuntu.com/precise/protobuf-compiler

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'Whitelist libprotobuf-dev' is ambiguous. Please specify only one.

**Comment by thedrow** [comment]
Both libprotobuf-dev and the protobuf compiler are required.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/76.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
