### ISSUE TITLE
Cannot unzip Gradle distribution

### ISSUE THREAD

**Issue by WonderCsabo** [travis-ci/travis-ci#3795]
I am seeing these exceptions in the build log lately:
```
Unzipping /home/travis/.gradle/wrapper/dists/gradle-2.2.1-bin/3rn023ng4778ktj66tonmgpbv/gradle-2.2.1-bin.zip to /home/travis/.gradle/wrapper/dists/gradle-2.2.1-bin/3rn023ng4778ktj66tonmgpbv
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at org.gradle.wrapper.Install.unzip(Install.java:157)
	at org.gradle.wrapper.Install.access$400(Install.java:26)
	at org.gradle.wrapper.Install$1.call(Install.java:67)
	at org.gradle.wrapper.Install$1.call(Install.java:44)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:44)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
```

An [example](https://travis-ci.org/excilys/androidannotations/jobs/60349974#L4026) of such failed build. Please note we do cache the `.gradle` directory, not sure if it is related.

**Comment by BanzaiMan** [comment]
Looks like an issue with pulling the cache.

```sh-session
$ Installing caching utilities
attempting to download cache archive
fetching PR.1380/cache--jdk-oraclejdk8.tbz
running `casher fetch` took longer than 180 seconds and has been aborted
adding /home/travis/.gradle to cache
/home/travis/.gradle is not yet cached
adding /home/travis/.m2 to cache
/home/travis/.m2 is not yet cached
```

Is your `gradlew` expecting to find the zip file in `/home/travis/.gradle/wrapper/dists/gradle-2.2.1-bin/3rn023ng4778ktj66tonmgpbv/gradle-2.2.1-bin.zip`? Is the task supposed to work if the cache is not there in `/home/travis/.gradle`?

**Comment by WonderCsabo** [comment]
> is your gradlew expecting to find

Hmm, `gradlew` is not *mine*, it is the Gradle wrapper actually. Sorry for asking, but are you familiar with that? I am just asking to know should i explain the problem.

**Comment by BanzaiMan** [comment]
I do not know how `gradlew` works, I'm afraid. I am reading the log output, and trying to figure out where the problem arises. Since you are caching `~/.gradle`, and cache download failed, if `gradlew` is expecting to find the zip file there, it stands to reason that the build failed.

Failure to fetch the cache, on the other hand, seems to be happening recently. We are looking into that issue separately.

**Comment by WonderCsabo** [comment]
To be sure, i read the [source](https://github.com/gradle/gradle/blob/master/subprojects/wrapper/src/main/java/org/gradle/wrapper/Install.java) for the Gradle wrapper. 

It seems if 
* there is already a zip file, it uses that,
* otherwise it downloads a new one.

Since we are caching, it finds the zip file, but because of the cache failure (i guess), it cannot really open it, and fails.
So your black box assumption is totally correct i think. :)

**Comment by BanzaiMan** [comment]
I see that the builds are still failing with the same issue. We are rolling back the 2015-04 at the moment. My expectation is that the new instances (when .org gets refreshed) would have the network issue fix, and that you would see fewer cache fetching issues.

**Comment by WonderCsabo** [comment]
OK. Thanks. Actually i am seeing other similar issues, like Maven cannot open Maven dependency jar files (which are also zips).

**Comment by WonderCsabo** [comment]
I see Travis is reverted. I cleared the caches, and now my builds seems to be stable now. Thanks!

Should we close this issue?

**Comment by BanzaiMan** [comment]
That is interesting. I am not entirely clear what triggered the issue, and I would love to know what did, but I am thinking that tracking down would require a lot of time.

I am closing this for now, and we will offer a better way to test the new images in the future so that problems like this can be avoided.

**Comment by kenorb** [comment]
Related: #5329, #5478
