### ISSUE TITLE
"Restart Build" is no effect

### ISSUE THREAD

**Issue by marutosi** [travis-ci/travis-ci#3796]
https://travis-ci.org/marutosi/redmine-bb/builds/60316911
https://travis-ci.org/marutosi/redmine-bb/builds/60316974
https://travis-ci.org/marutosi/redmine-bb/builds/60317033

**Comment by alloy** [comment]
Wanted to report this too, but for OS X (beta 6.2), so I guess it’s not related to the platform.

**Comment by k-okada** [comment]
me too, on `Chromium 40.0.2214.94 Ubuntu 14.04`

**Comment by vincent-zurczak** [comment]
Same for me on Firefox 37.0.1 (Ubuntu 14.04).

**Comment by BanzaiMan** [comment]
Thanks for the report. We are looking into it.

**Comment by BanzaiMan** [comment]
There is a back log, but the requests are being processed now. If you don't see any change in 30 minutes, do let us know.

**Comment by BanzaiMan** [comment]
Task back logs are clear now.

Closing this.
