### ISSUE TITLE
[osx beta-xcode6.2] Default terminal character encoding not set to UTF-8

### ISSUE THREAD

**Issue by alloy** [travis-ci/travis-ci#3797]
Had to [set it to UTF-8](https://github.com/artsy/eigen/commit/0cc3a6459b2f1e2db4d0e8be75308e86864aaa6f) to fix issues such as https://travis-ci.org/artsy/eigen/builds/60363793#L919

**Comment by solarce** [comment]
@alloy is this still an issue?

**Comment by alloy** [comment]
Not sure, haven't been using it in a while. I'd say close it for now.
