### ISSUE TITLE
APT whitelist request for libsdl2

### ISSUE THREAD

**Issue by th0br0** [travis-ci/travis-ci#3799]
Would be great to be able to use the various libsdl2 packages (esp. the -dev ones of course)!

**Comment by bdero** [comment]
I second whitelisting `libsdl2-dev`. :+1:

**Comment by LavenderMoon** [comment]
I definitely need these packages. :+1:

**Comment by BanzaiMan** [comment]
There is no package available for Precise. http://packages.ubuntu.com/search?keywords=libsdl2&searchon=names Is there a PPA we can use?

**Comment by LavenderMoon** [comment]
[This](https://launchpad.net/~zoogie/+archive/ubuntu/sdl2-snapshots?field.series_filter=precise "SDL2 Snapshots : Michael Imamura") was the closest I found. They're a year out of date and don't include libsdl2-dev. I've [contacted](https://github.com/ZoogieZork/SDL2-Package/issues/8#issuecomment-108570756 "Different names in the packages · Issue #8 · ZoogieZork/SDL2-Package") the maintainer of the PPAs to ask for an update, but [asking](https://wiki.ubuntu.com/UbuntuBackports "UbuntuBackports - Ubuntu Wiki") the [Ubuntu Precise Backports](https://launchpad.net/precise-backports "Precise Backports in Launchpad") project for an official backport of SDL2 and SDL2-dev might be the better option. Unfortunately, I don't have a Linux box to complete the steps with. @th0br0, @bdero, would either of you be willing to do that?

**Comment by DrMcCoy** [comment]
I'd need that too for [xoreos](https://github.com/xoreos/xoreos).

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libsdl2*' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libsdl2*' needs source whitelisting

**Comment by BanzaiMan** [comment]
Please open a separate request for PPA source. Thanks.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/366.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!

**Comment by maqifrnswa** [comment]
Source whitelist request:
travis-ci/apt-source-whitelist#88

**Comment by dprotti** [comment]
I join the cause. I need libsdl2-dev for CI of [Infinity plugin](https://dprotti.github.io/infinity-plugin).

**Comment by stianeklund** [comment]
Is there any way to use newer versions of Ubuntu with Travis CI or add a PPA for libsdl2 development files as well as libsdl2-image?
