### ISSUE TITLE
APT source whitelist request for ubuntu-elisp PPA

### ISSUE THREAD

**Issue by lunaryorn** [travis-ci/travis-ci#3802]
The PPA is at `ppa:ubuntu-elisp/ppa`.  It provides snapshot builds of GNU Emacs' trunk, which many Emacs packages use to test against Emacs trunk to be prepared for the next major release of GNU Emacs.

**Comment by BanzaiMan** [comment]
Could you combine #3804 with this one?

**Comment by lunaryorn** [comment]
@BanzaiMan What do you mean with “combine”?

**Comment by BanzaiMan** [comment]
I meant, close this one, and add a detailed note on #3802. Sorry about being unclear.

**Comment by BanzaiMan** [comment]
I don't know what I'm doing, do I?

**Comment by dgutov** [comment]
+1.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ubuntu-elisp PPA' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT source whitelist request for ubuntu-elisp PPA' is ambiguous. Please specify only one.

**Comment by lunaryorn** [comment]
@BanzaiMan ?

**Comment by BanzaiMan** [comment]
Sorry for the alarm; the comment was posted by a script I'm writing to make the ticket management easier.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/25.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
