### ISSUE TITLE
APT whitelist request for emacs24-nox

### ISSUE THREAD

**Issue by lunaryorn** [travis-ci/travis-ci#3803]
`emacs23-nox` is already present, but `emacs24-nox` is curiously missing.

**Comment by BanzaiMan** [comment]
http://packages.ubuntu.com/precise/emacs24-nox does not exist. Do you know of a PPA that has it for Precise?

**Comment by lunaryorn** [comment]
It's in cassou-emacs, which is [already whitelisted](https://github.com/travis-ci/apt-source-whitelist/blob/63454fd9da89fce908ab316a69defa28f34c1743/ubuntu.json#L15)

**Comment by BanzaiMan** [comment]
Cool. Thanks.

**Comment by BanzaiMan** [comment]
Resolved by https://github.com/travis-ci/apt-package-whitelist/commit/adbc6a3da9c197a879dc7054adf4be6d838573ad
