### ISSUE TITLE
APT whitelist request for emacs-snapshot

### ISSUE THREAD

**Issue by lunaryorn** [travis-ci/travis-ci#3804]
This would allow Emacs packages to use the container-based infrastructure for testing against Emacs snapshot builds.  Needs #3802

**Comment by BanzaiMan** [comment]
See #3802:

> The PPA is at ppa:ubuntu-elisp/ppa. It provides snapshot builds of GNU Emacs' trunk, which many Emacs packages use to test against Emacs trunk to be prepared for the next major release of GNU Emacs.

**Comment by dgutov** [comment]
+1.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'emacs-snapshot and emacs-snapshot-nox' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'emacs-snapshot and emacs-snapshot-nox' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for emacs-snapshot and emacs-snapshot-nox' is ambiguous. Please specify only one.

**Comment by lunaryorn** [comment]
@BanzaiMan ?

**Comment by BanzaiMan** [comment]
The script I'm working on requires exactly one package name to be specified in the request subject. (It doesn't do any natural language processing.) So "emacs-snapshot and emacs-snapshot-nox" is not good.

**Comment by lunaryorn** [comment]
And what am I supposed to do now?  I mean no offense, but this is becoming much of a nuisance for what is supposedly just a simple addition to a JSON file…

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/367.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
