### ISSUE TITLE
Provide ability to change a build's position in the queue

### ISSUE THREAD

**Issue by habdelra** [travis-ci/travis-ci#3809]
I feature request that I'd love to see is the ability to change a queued build's position in the queue. I run into the scenario a lot where I have an important build that I need complete that is waiting on builds that are not so important higher up in the queue. An ability to move a build higher up (or down) in the queue position would be lovely.

**Comment by BanzaiMan** [comment]
Similar requests have been made in the past (#1155, #2801, #2038), and we are looking into offering some capability.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by saveriomiroddi** [comment]
I wonder if this is still not planned. I suppose that urgent/priority PRs, which need to take priority in the queue, are generally routine.
