### ISSUE TITLE
Maximum time limit for jobs is not fulfilled

### ISSUE THREAD

**Issue by nsuarezml** [travis-ci/travis-ci#3810]
Sometimes the jobs are stopped by time out, with the next log message: `The job exceeded the maxmimum time limit for jobs, and has been terminated`.

In the documentation says: `With our current timeouts, a job will be terminated if it's still running after 50 minutes (120 minutes on travis-ci.com)`. I use travis-ci.com but my jobs are stopped before 120 minutes.

The average execution time of my jobs is 50 minutes.

**Comment by BanzaiMan** [comment]
Could you point to a build log URL, please?

**Comment by nsuarezml** [comment]
https://magnum.travis-ci.com/mercadolibre/mobile-ios/jobs/16893938

**Comment by BanzaiMan** [comment]
Thanks. At the moment, the Mac build timeouts are hard set to 50 minutes. (Not quite sure how that particular job got terminated a little short of that, though.) We are looking into changing the hard limits.

**Comment by BanzaiMan** [comment]
Documentation needs clarification.

**Comment by adam-siton** [comment]
Any estimation on when the hard limits will change? I'm running UI tests that take longer than 50 minutes, so I can't run the tests on builds.

**Comment by cybertk** [comment]
+1

**Comment by Hibbert-pku** [comment]
+1, could we extend the time on linux?
