### ISSUE TITLE
APT source whitelist request for ppa:ubuntugis/ppa

### ISSUE THREAD

**Issue by ograycode** [travis-ci/travis-ci#3812]

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:ubuntugis/ppa' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/26.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
