### ISSUE TITLE
UnknownHostException

### ISSUE THREAD

**Issue by avurro** [travis-ci/travis-ci#3814]
after performing the build of my repository (https://github.com/jmapper-framework/jmapper-test.git) i have the error:
java.net.UnknownHostException: home

**Comment by BanzaiMan** [comment]
Do you have a build log URL that exhibit this problem?

**Comment by avurro** [comment]
https://travis-ci.org/jmapper-framework/jmapper-test/jobs/60606467

**Comment by BanzaiMan** [comment]
What is `home`? It seems like a configuration error in your code.

**Comment by avurro** [comment]
No error in my configuration, all tests end with success

**Comment by BanzaiMan** [comment]
How does `home` resolve on your machine?

**Comment by avurro** [comment]
i don't know what is `home`. This word doesn't exists in my project

**Comment by BanzaiMan** [comment]
Hmm. Very curious. If I run the tests on my machine, it fails with the same failure and the same error (but with a different host name).

```
Results :

Failed tests:   testConstructorParameters(com.googlecode.jmapper.integrationtest.application.JMapperExceptionTest): null expected:<ERROR - [MappingNotFoundException: the classes: BeanD2 and BeanS aren't configured, verify file://Users/asari/Development/tmp/jmapper-test/JMapper Test/src/test/resources/testJmapper.xml mapping file](..)

Tests in error: 
  testRelationalJMapperWithXML(com.googlecode.jmapper.integrationtest.application.RelationalJMapperTest): java.net.UnknownHostException: Users
```

`Users` is the first level directory of the working directory on my machine (`/Users/asari/Development/tmp/jmapper-test/JMapper Test/src/test/resources/testJmapper.xml`) and `home` is the same on Travis CI (`home/travis/build/jmapper-framework/jmapper-test/JMapper Test/src/test/resources/testJmapper.xml`).

I tend to think there is something wrong with your code, but I can't put a finger on it.

**Comment by BanzaiMan** [comment]
Ah. I see what's happening. Note the `file` URL on https://travis-ci.org/jmapper-framework/jmapper-test/jobs/60606467#L905: `file://home/travis/build/jmapper-framework/jmapper-test/JMapper Test/src/test/resources/testJmapper.xml`

It only has 2 slashes after `file:`, so `home` is considered to be the host name in the URL. There should be 3 slashes if the URL is to be considered to point to the local file system. You should also note that your directory `JMapper Test` has an unescaped space in it, so the tests can break in unexpected ways. The space should be escaped to `%20`, or dropped altogether.

Does it work on your machine? Do you use Windows?

**Comment by avurro** [comment]
yes, on MAC too, however I try to adjust the path now

**Comment by avurro** [comment]
fixed. I have removed one slash: from `file://` to `file:/'
