### ISSUE TITLE
APT whitelist request for more recent SQLite 3 version

### ISSUE THREAD

**Issue by waltaskew** [travis-ci/travis-ci#3815]
I'm using features of sqlite3 which are not present in the version provided by the current `sqlite3` package in the whitelist:
https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise#L5609

I'd appreciate if I could request a version of sqlite >= 3.7.11 as that is the first version which supports bulk insert statements.
Maybe we could add an sqlite3-8 package to the whitelist?

Thanks!

**Comment by BanzaiMan** [comment]
Do you know of a PPA that has a recent version of sqlite3? http://packages.ubuntu.com/precise/sqlite3 does not.

**Comment by waltaskew** [comment]
I've been pulling from ppa:travis-ci/sqlite3

Does that ppa actually have anything to do with travis?  I thought it was odd that I couldn't find it in the apt sources whitelist: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json

**Comment by BanzaiMan** [comment]
Ah, indeed, that is the PPA we are using (sorry, the setup predates my involvement with Travis). But I believe it is largely unmaintained.

**Comment by waltaskew** [comment]
Ah -- well that PPA offers `sqlite3=3.7.15.1-1~travis1` which is new enough for me.

**Comment by BanzaiMan** [comment]
Very well, then. I'm going to close this one for now.

**Comment by waltaskew** [comment]
But that's not the version of sqlite3 that's on travis by default, nor is it the one that you get by doing

```
addons:
  apt:
    packages:
    - sqlite3
```

I'm having to do this in my travis.yml:

```
before_install:
  # The default version of sqlite on travis doesn't support bulk inserts.
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-get -y install sqlite3=3.7.15.1-1~travis1
```

When I'd rather be able to do something like:

```
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3.7.15.1-1~travis1
```

**Comment by BanzaiMan** [comment]
Ah, I see. We are not actually using the recipe that I thought we were using.

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for more recent SQLite 3 version' is ambiguous. Please specify only one.

**Comment by waltaskew** [comment]
> Did not run automated check because title 'APT whitelist request for more recent SQLite 3 version' is ambiguous. Please specify only one.

sqlite >= 3.7.11 is what I need.  Let's say... 3.7.15, why not?

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/368.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
