### ISSUE TITLE
Use `default_branch` or allow to specify default branch for caching

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#3817]
When using caching, we will populate the cache from master branch, regardless which branch is set as a main branch on GitHub. We should probably use main branch and/or allow to specify `default_branch` in cache options.

**Comment by drogus** [comment]
I've created a PR travis-ci/travis-core#453 to send default_branch to worker. Regardless of what we choose to implement in travis-build, this could come in handy also in other situations.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/2661

**Comment by joshk** [comment]
@BanzaiMan would you mind following up on this and seeing if this has been implemented, and what it would take to implement it?

**Comment by BanzaiMan** [comment]
`travis-scheduler` needs to put the default branch information on the payload, so that `travis-build` can consume it.

**Comment by BanzaiMan** [comment]
This has been deployed to production.
