### ISSUE TITLE
Bus errors from Ruby/Nokogiri on after 2015-04 updates

### ISSUE THREAD

**Issue by anarchivist** [travis-ci/travis-ci#3818]
(Caveat: I know the build environment was rolled back already; the build I'm linking to is from Monday, 4/27/15).

Under Ruby 2.1.3, our builds are failing after Bundler fetches all the dependencies:

```
/home/travis/build/dpla/KriKri/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.6.2/nokogiri/nokogiri.so: [BUG] Bus Error at 0x007fd86a70f8fc
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]
# ... SNIP ...
-- C level backtrace information -------------------------------------------
Inconsistency detected by ld.so: dl-open.c: 221: dl_open_worker: Assertion `_dl_debug_initialize (0, args->nsid)->r_state == RT_CONSISTENT' failed!
```

Full build logs: https://travis-ci.org/dpla/KriKri/builds/60246616

**Comment by BanzaiMan** [comment]
Probably a bad cache. Try removing the cache, please.

**Comment by BanzaiMan** [comment]
Or you can try disabling the cache one time and see if it improves the build.

**Comment by anarchivist** [comment]
As noted, I'm not currently seeing this; I'm reporting it based upon the known issues with the previously deployed build environment.

**Comment by BanzaiMan** [comment]
This is probably not an issue that specifically affects the 2015-04 update. When the binaries get updated, extensions with binary components (`nokogiri`, `mysql2`, etc.) may need to be recompiled.

I'm going to close this now. Thanks for reporting.
