### ISSUE TITLE
APT whitelist request for r-base

### ISSUE THREAD

**Issue by jbarnoud** [travis-ci/travis-ci#3819]
The `r-base` package installs the Rscript interpretor, and some of the most used Rscript modules. The Rscript language (also called R, or GNU R) is commonly used in science and statistics. Moreover, R scripts are often embedded in program written in other languages as many algorithms are only implemented in R. Please, add the `r-base` package to the APT whitelist.

See <http://packages.ubuntu.com/precise/r-base> for details about the package.

**Comment by jbeezley** [comment]
It would also be helpful to include `r-base-dev` to allow compilation of R packages.

**Comment by lbergelson** [comment]
What's the status on this?  We need this to be able to do containerized builds.

**Comment by BanzaiMan** [comment]
Hello. Do note that whitelisting R packages will not help with running R builds on containers, since the build script will call `sudo` after `sudo` is disabled. Modifying the build script to accommodate such possible changes is not straightforward.
