### ISSUE TITLE
script output that does not end with a newline character is silently swallowed

### ISSUE THREAD

**Issue by SethTisue** [travis-ci/travis-ci#3820]
so for example if I put `echo -n foo` in my `script:` section, I get:

```
$ echo -n foo

The command "echo -n foo" exited with 0.
```

`foo` is never printed.

Is this a serious problem? Well, I don't know how often it will come up, but I did just lose almost a day of work to it. I was debugging someone else's code where they printed a diagnostic message to stderr and exited, but they forgot to put `\n` at the end of the message, so I couldn't see it, so it appeared to me the program was just silently dying.

**Comment by BanzaiMan** [comment]
This should work now. https://travis-ci.org/BanzaiMan/travis_production_test/builds/240666766#L180

**Comment by SethTisue** [comment]
sweet! thank you!
