### ISSUE TITLE
.config/.travis.yml

### ISSUE THREAD

**Issue by shannonmoeller** [travis-ci/travis-ci#3829]
As more and more tools have become best-practice when authoring npm modules, from `package.json` to `.*rc` to `*file.js`, the root directory of projects has become a very loud place. This dot-noise pushes README content farther and farther down the main page of git repos.

![screenshot 2015-05-01 21 41 51](https://cloud.githubusercontent.com/assets/155164/7439468/e8f2ff9e-f04a-11e4-8c1b-4248379053e9.png)

What if the above could optionally be simplified to the following?

![screenshot 2015-05-01 21 50 12](https://cloud.githubusercontent.com/assets/155164/7439513/179455c2-f04c-11e4-9577-c3b73c2b01c3.png)

This is a simple example and that's already about a 30% vertical space savings. I started the conversation over in the [npm repo](https://github.com/npm/npm/issues/8159), but I'm also submitting issues to the `findup`, `findup-sync`, `karma`, and `zuul` repos.

**Comment by roidrage** [comment]
Thank you for your suggestion, but I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by shannonmoeller** [comment]
Thanks for your consideration.

**Comment by JoshCheek** [comment]
I would appreciate a feature like this as well.

Side thought: If Github allowed an author some customizability of that main page, it would obviate the need to add this feature to every tool. If a Github competitor added it, that would be a selling point for them.

**Comment by joshk** [comment]
As a small update, we are considering supporting a `.travis` directory, but I don't have an ETA on this at the moment.

**Comment by ocornut** [comment]
Thank you for considering this @joshk.
For me personally the ideal but simple solution would be to specify a path+filename on Travis-project-side (defaulting to /.travis.yml) so I can move the file outside of the root directory. I (personnally) wouldn't have use for .travis sub-directory.

I am not a paying user so I realize our opinion bear little weight, just wanted to put that idea out. Thanks a lot for all your work.

**Comment by JoshCheek** [comment]
My use case matches @ocornut and @shannonmoeller's
