### ISSUE TITLE
Control + C in a setup now I'm screwed.

### ISSUE THREAD

**Issue by GantMan** [travis-ci/travis-ci#3832]
I was going through an encrypt when I noticed I typed the wrong username.   Then I hit control C

Now everytime I type any real command I get 
> GitHub repo name is invalid, it should be on the form 'owner/repo'

I tried removing the gem and reinstalling it, but it's sticking around!

**Comment by weitjong** [comment]
Have you tried to pass the '-r owner/repo' explicitly? If it works then you can stick to that repo SLUG by passing '-R' instead of small '-r' to store it permanently.

**Comment by GantMan** [comment]
that worked!   Thanks.  I'll close the issue, but definitely a gotcha to anyone who uses ctrl + c in the setup.
