### ISSUE TITLE
APT whitelist request for libsdl1.2-dev

### ISSUE THREAD

**Issue by Turbo87** [travis-ci/travis-ci#3833]

**Comment by LavenderMoon** [comment]
I also need `libsdl1.2-dev`. :+1:

**Comment by Turbo87** [comment]
@BanzaiMan do you know how long it will take for the new whitelist to go into production?

**Comment by BanzaiMan** [comment]
@Turbo87 It should be available now. https://travis-ci.org/BanzaiMan/travis_production_test/builds/69131145#L79 What problems are you having?

**Comment by Turbo87** [comment]
@BanzaiMan nevermind. it looked like https://github.com/Turbo87/XCSoar-TE/pull/7 still didn't work but it seems to work now. thanks a lot!
