### ISSUE TITLE
APT whitelist request for libpng-dev

### ISSUE THREAD

**Issue by Turbo87** [travis-ci/travis-ci#3835]

**Comment by Turbo87** [comment]
@meatballhat is there anything I can do to help you speed up the process?

**Comment by meatballhat** [comment]
@Turbo87 so sorry about the delay.   This was added recently for #3746   Looking good now?

**Comment by Turbo87** [comment]
@meatballhat Sorry, I didn't see the other issue. Unfortunately there are quite a few more missing until I can close/merge https://github.com/Turbo87/XCSoar-TE/pull/7 ... let me know if I can help with the others.
