### ISSUE TITLE
NVM on osx image does not install correctly 

### ISSUE THREAD

**Issue by timurvafin** [travis-ci/travis-ci#3854]
Hey,

Looks like nvm installed via Homebrew does not install node using binary and trying build it from sources instead: https://travis-ci.org/fs/test-nvm-on-travis/builds/61286554

Timur

**Comment by timurvafin** [comment]
Looks like after `brew update` issue fixed.

**Comment by timurvafin** [comment]
Nope, when I use `set -e` looks like build is failing.

https://travis-ci.org/fs/test-nvm-on-travis/builds/61301846

**Comment by BanzaiMan** [comment]
Duplicate of #2311, right?

**Comment by timurvafin** [comment]
@BanzaiMan nope.

* Based on this build https://travis-ci.org/fs/test-nvm-on-travis/builds/61286554
* But when all command in the single build script with `set -e` we got exit code `2` https://travis-ci.org/fs/test-nvm-on-travis/builds/61301846

**Comment by BanzaiMan** [comment]
Your script is exiting with status 2. `set -e` changes the way your script behaves; it exits on the first error. Based on the output, I suspect it is the `brew` command, but you need to understand how your script is behaving. Try `set -ex`, for example.

**Comment by BanzaiMan** [comment]
That reminds me; `nvm` is already installed via `brew

**Comment by BanzaiMan** [comment]
I see that the error is happening (https://travis-ci.org/fs/test-nvm-on-travis/builds/61436701#L1411) while sourcing `nvm.sh`. A short experiment shows that that `nvm.sh` does not work with `set -e`. (You can see observe this behavior if you add `set -e` in `nvm.sh`.)

Turn off the switch while you source `nvm.sh`:

```bash
set +e
source $(brew --prefix nvm)/nvm.sh
set -e
nvm install 0.12.2
```

**Comment by timurvafin** [comment]
Thanks, looks like this is some "expected" behavior of `nvm.sh`
