### ISSUE TITLE
APT whitelist request for jq

### ISSUE THREAD

**Issue by vaibhavsagar** [travis-ci/travis-ci#3858]
I need it to install packages from Github Releases. For example, see [this .travis.yml](https://github.com/vaibhavsagar/resume/blob/master/.ci/prepare.sh).

**Comment by BanzaiMan** [comment]
`jq` should be available already. Do you have reasons to believe otherwise?

**Comment by vaibhavsagar** [comment]
That's a bit embarrassing, I thought it wasn't available because it isn't listed [here](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise). I will try it now.

**Comment by vaibhavsagar** [comment]
You're right, `jq` is available. Thanks!
