### ISSUE TITLE
An error occurred while compiling the build script: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by abma** [travis-ci/travis-ci#3860]
travis shows the error:
"An error occurred while compiling the build script: undefined method `[]' for nil:NilClass"

https://travis-ci.org/spring/spring/jobs/61382219

but the validator says "Hooray, your .travis.yml seems to be solid!"

the travis file:
https://github.com/spring/spring/blob/c9769cf59090553a8ff27b407d328953dae098e4/.travis.yml

imo it should show at least a line number which allows to fix the error.

**Comment by BanzaiMan** [comment]
Sorry that the linter isn't giving you the correct information.

But given that the build 1156 ran (and failed) while build 1157 errored on the `coverity_scan` branch, the error was probably introduced here: https://github.com/spring/spring/compare/59a318cb9bb8...322b33ad794c

**Comment by abma** [comment]
i didn't fully test, but after readding the lines

      project:
         name: spring/spring

https://github.com/spring/spring/blob/develop/.travis.yml#L47

it worked again!
