### ISSUE TITLE
Add [no cache] to have a commit skip using the caches.

### ISSUE THREAD

**Issue by AeroNotix** [travis-ci/travis-ci#3870]

**Comment by BanzaiMan** [comment]
If you are making a commit, removing the `cache` will have the same effect, and it is more declarative than the magic `[no cache]`.

I am not sure how another magical comment is good.

**Comment by AeroNotix** [comment]
We should strive to automate as much as possible, clearing the cache in the UI is slow, manual and not all users have access to it (requires repo owners to do it).

Having a way to declaritively express when caches are to be cleared or ignored is a superior option since this allows a greater level of automation.

**Comment by roidrage** [comment]
Could you outline your use case a bit more?

**Comment by AeroNotix** [comment]
A commit which changes dependencies, version bump, etc. You want to easily control whether it skips or cleans the cache, going to the UI is clumsy.

**Comment by roman-gliffy** [comment]
I'd like to add another case for having a conditional check to disable caches: for example we want nightly builds run without caches, so in case of dependency problems in gems or npm - the build would actually break. 

```
  8 cache:
  9   directories:
 10     - $HOME/.m2
 14   on:
 15     branch: master
 16     condition: $TRAVIS_EVENT_TYPE != cron
```
