### ISSUE TITLE
OSX rvm version is outdated

### ISSUE THREAD

**Issue by deivid-rodriguez** [travis-ci/travis-ci#3885]
It has version 1.25.33, and current stable is 1.26.11

That version cannot fuzzily match ruby 2.2 version so if people specify 2.2 in their ruby matrix, the build fails.

**Comment by BanzaiMan** [comment]
Sorry about the issue. You can update it yourself in the meantime: `rvm get stable; rvm reload`.

**Comment by BanzaiMan** [comment]
Perhaps we should roll this into our build script.

**Comment by deivid-rodriguez** [comment]
The problem happens when the Ruby version is selected from the `.travis.yml` values. I don't see how I can update rvm before that happens. The current workaround is to use the full version number.

By the way, can a different set of rubies be specified for different os?

**Comment by solarce** [comment]
We've shipped newer rvm versions in our recent Xcode 7.x and Xcode 8 images. We are hoping to ship updates for our older Xcode 6.x images in a few weeks
