### ISSUE TITLE
OSX ruby version is outdated

### ISSUE THREAD

**Issue by deivid-rodriguez** [travis-ci/travis-ci#3886]
Could you install 2.2.2 so people can test their gems against latest Ruby?

Thanks!

**Comment by BanzaiMan** [comment]
Thanks for the nudge. We are woking on the Mac environment update, and we will include 2.2.2 for that. (Sorry, there is no ETA.)

In the meantime, I've compiled 2.2.2 on the Mac, so that it may be installed on demand.

**Comment by deivid-rodriguez** [comment]
Thanks for the update!
