### ISSUE TITLE
APT source whitelist request for opt-qt541

### ISSUE THREAD

**Issue by The-Compiler** [travis-ci/travis-ci#3888]
Hi!

I'd like to request `ppa:beineri/opt-qt541` to be added to the source whitelist - this is a PPA which packages a recent Qt version installed to `/opt`.

There's also `ppa:beineri/opt-qt541-trusty` for Ubuntu Trusty if that's relevant already.

**Comment by The-Compiler** [comment]
Clarification: #3765 and #3685 are related, but those only seem to offer source packages, while this offers ready-to-use binaries - and Qt is rather hard to compile.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'opt-qt541' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/27.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
