### ISSUE TITLE
Making /opt writable in containers?

### ISSUE THREAD

**Issue by The-Compiler** [travis-ci/travis-ci#3889]
Hi,

could you please consider adjusting the permissions of `/opt` so it's writable as non-root user in container builds? That would make it easier to install software as an user which is intended to be installed to `/opt`.

**Comment by BanzaiMan** [comment]
What software wants to write to `/opt`?

**Comment by The-Compiler** [comment]
Writing isn't an issue, but it'd make installing possible.

For example, I could unpack/install #3888 without needing root, and without having to do source/package whitelist requests for every new release (because the source changes with each version...).

I tried to unpack it to /tmp, but the libraries have `/opt` paths hardcoded, so that didn't work.

I'm sure there's similiar software which can get installed to `/opt` - so having it writable would make this all much easier and I don't see any drawback :wink:

**Comment by The-Compiler** [comment]
This is still applicable as far as I'm ware.
