### ISSUE TITLE
Support Rust on OS X

### ISSUE THREAD

**Issue by carllerche** [travis-ci/travis-ci#3890]
According to these docs, Rust is not supported on the OS X environment. It would be nice to run tests on OS X as well: http://docs.travis-ci.com/user/osx-ci-environment/

**Comment by BanzaiMan** [comment]
Rust implementation is based on purely bash (with platform-neutral commands), so if you want to use Rust on the Mac, you would need to turn on the [Multi-OS](http://docs.travis-ci.com/user/multi-os/) feature.

Once you have the feature enabled, it works as expected; e.g., https://travis-ci.org/BanzaiMan/travis_production_test/builds/62203841.
