### ISSUE TITLE
APT whitelist request for python-opencv

### ISSUE THREAD

**Issue by cancan101** [travis-ci/travis-ci#3892]
http://packages.ubuntu.com/precise/python-opencv

**Comment by cancan101** [comment]
In order to make this work in the python virtualenv, you need to do something along the lines of http://ntraft.com/opencv-in-a-virtualenv/:
```bash
sudo cp /usr/lib/pymodules/python2.7/cv* /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
```

**Comment by cancan101** [comment]
@BanzaiMan Why remove the label?

**Comment by BanzaiMan** [comment]
If `sudo` is required to make use of the installed package, it does not make sense to add it to the whitelist. (I haven't tested this, so I could be mistaken.)

**Comment by cancan101** [comment]
sudo is not required to use opencv. sudo is required as part of the install.

**Comment by cancan101** [comment]
I follow [this yml file](https://github.com/devernay/openfx-opencv/blob/master/.travis.yml#L22) to get a more recent version of OpenCV that works on Travis:
```yaml
- sudo add-apt-repository -y ppa:kubuntu-ppa/backports
- sudo apt-get update -qq
- sudo apt-get install -qq python-opencv 
```

**Comment by cancan101** [comment]
bump.
