### ISSUE TITLE
node binary not found when running from child process

### ISSUE THREAD

**Issue by jenius** [travis-ci/travis-ci#3894]
I've got a test suite using node which opens up a child process and executes a file using the `node` command from within the child process. I'd think that node would be installed on the VM since it's used to run the tests, but I'm getting the following error on the test:

```
/bin/sh: 1: node: not found
```

Is there any sort of path configuring or something that I need to do in order to get this working? I've spent some time searching issues and browsing through docs but have been unable to find a solution here :cry:

**Comment by roidrage** [comment]
Thank you for reporting this issue.

What's the child process doing, is it running a command using sudo, by any chance or just running node as an external command?

**Comment by jenius** [comment]
No sudo, just a normal node command. Like this:

```js
var exec = require('child_process').exec;
exec('node some_file.js', console.log);
```

**Comment by BanzaiMan** [comment]
@jenius How does `exec` call work on Node.js? Is it inheriting `$PATH` from the parent process, or is it setting up its own? Our environment is such that `node` is not found in the usual places (e.g., `/usr/bin` or `/usr/local/bin`).

**Comment by jenius** [comment]
Honestly, I'm not entirely sure, I'd have to read node's source to find out. It doesn't lay down that specific of implementation details in the docs, all I could find was the it uses [popen(3)](http://linux.die.net/man/3/popen), if I'm not mistaken.

A symlink to `/usr/bin` or `/usr/local/bin` would be great, or even just some sort of environment variable that I can grab the binary's location from?

**Comment by BanzaiMan** [comment]
`nvm which $TRAVIS_NODE_VERSION` should tell you in the shell, but you may not have that environment variable defined in the `exec()` call.

**Comment by BanzaiMan** [comment]
@jenius Have you had any revelations?

**Comment by jenius** [comment]
Hey there! Yeah so I confirmed that it does inherit `$PATH` from the parent process, and also realized I had been overwriting `$PATH` by accident, which seemed to me like it was a likely cause of the issue. However, I just fixed this, confirmed that it is working locally, and unfortunately have the same error still on travis :confused:

**Comment by BanzaiMan** [comment]
Hmmm. Could you email support@travis-ci.com? We can spin up a debug VM for you.

**Comment by jenius** [comment]
Yeah, I'll shoot an email over there soon. Thanks so much for the excellent support guys :sparkling_heart:

**Comment by Poltergeist** [comment]
I did have the same problem. In my case I was trying to run a node script in my test, which failed, because the node binary wasn't in the usual place. The file had execute rights. I solved it by running?
```js
var exec = require('child_process').exec;
exec('node /path/to/script.js', callback);
```
For me that was a valid solution.

**Comment by gocreating** [comment]
Same problem

here is my broken code

```
const exec = require('child_process').exec;
const child = exec(`node build/${dest}/app.js`, {
  env: {
    NODE_ENV: NODE_ENV,
    EXSEED_INIT: options.init,
  },
});
```

**Comment by rjz** [comment]
> How does exec call work on Node.js? Is it inheriting $PATH from the parent process, or is it setting up its own? 

Unless `env` is overridden, the default behavior passes the parent's `process.env` through to the child—this question is spot on.

Since the issue here arises when `env` is explicitly overridden in a call to `exec`/`spawn`, a minimal workaround would include `{ PATH: process.env.PATH }` in the `env` argument (though @gocreating's solution should produce a more consistent environment).

**Comment by BanzaiMan** [comment]
It seems to me that this is an application issue, and thus can be closed. Right?

**Comment by rjz** [comment]
@BanzaiMan, agreed!

**Comment by BanzaiMan** [comment]
Very well!
