### ISSUE TITLE
APT whitelist request for gir1.2-networkmanager-1.0

### ISSUE THREAD

**Issue by tomspur** [travis-ci/travis-ci#3895]
It is used to test getting-things-gnome. Or could potentially the network be manipulated and this is a bad idea to whitelist it?

**Comment by emdantrim** [comment]
This requires all of `network-manager` to be installed. `network-manager` itself doesn't call `setuid` on anything, but network-manager still runs its own daemon that allows users to interact with it, right?

@solarce, @meatballhat, @henrikhodne: can you perhaps shed some more light on whether or not this is okay to whitelist?

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207087 found problems with Python code.

**Comment by tomspur** [comment]
It seems to be only in the examples and man page. Can those maybe deleted as they are not needed for the program itself?

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/372.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
