### ISSUE TITLE
APT whitelist request for aspcud

### ISSUE THREAD

**Issue by talex5** [travis-ci/travis-ci#3898]
This solver is useful for the `opam` package manager (in the `avsm` source, which is already whitelisted).

Without it, builds print `[WARNING] Recommended external solver aspcud not found.` and may give suboptimal (or, sometimes, wrong) solutions.

Thanks,

**Comment by avsm** [comment]
This would be very useful for OCaml packages, which really need `apscud` to be installed correctly via OPAM.
