### ISSUE TITLE
APT source whitelist request for bintray

### ISSUE THREAD

**Issue by sinthetix** [travis-ci/travis-ci#3899]
Customer request :smile:

**Comment by BanzaiMan** [comment]
Where can we find it? It doesn't exist in the Ubuntu repository. http://packages.ubuntu.com/precise/bintray

**Comment by josegonzalez** [comment]
Bintray is a repository.

Specifically, we want to use [sbt from bintray](https://bintray.com/sbt).

**Comment by josegonzalez** [comment]
Was there any movement on this, or information I can provide to help?

**Comment by BanzaiMan** [comment]
Did not run automated check because 'bintray' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/29.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
