### ISSUE TITLE
travis-ci.org uses ~ 1 CPU core

### ISSUE THREAD

**Issue by mpapis** [travis-ci/travis-ci#390]
travis-ci.org uses ~ 1 CPU core after 2-3 hours of left alone in Chrome or Firefox. opening again fixes this. maybe autoreload in every 30 minutes of not touching it ?

**Comment by echlebek** [comment]
Hello from 2017, I found that my Travis tab was maxing out both of my CPU cores. Chromium on Fedora.

**Comment by ddomgn** [comment]
Travis build and build history pages on Firefox 57.0.1 consume so much CPU that my laptop produces noise like a vacuum cleaner.
