### ISSUE TITLE
APT source whitelist request for nodesource-node-0.12-precise

### ISSUE THREAD

**Issue by radeksimko** [travis-ci/travis-ci#3900]
`deb https://deb.nodesource.com/node_0.12 precise main`

Here's a key URL: `https://deb.nodesource.com/gpgkey/nodesource.gpg.key`

**Comment by BanzaiMan** [comment]
We manage Node.js runtimes with nvm. Is there a reason that you need an Ubuntu package?

**Comment by radeksimko** [comment]
@BanzaiMan Well, there is a reason. NVM and generally all NodeJS-related packages are only installed when I specify `language: node_js`, but I may need NodeJS in other environments.

Example:
https://travis-ci.org/TimeIncOSS/git-lint/ is a Python project and it happilly takes all the benefits coming from `language: python` (including VirtualEnv, multiple versions of Python etc.), but as it's a testing tool, it needs other testing tools from other languages.

**Comment by BanzaiMan** [comment]
nvm is installed on all images. You just have to call `nvm intall X` before you need `node`.

**Comment by BanzaiMan** [comment]
Your `git-lint` builds are failing because you are running the `npm` command with `sudo`. I don't think you need it. https://github.com/TimeIncOSS/git-lint/pull/1.

**Comment by BanzaiMan** [comment]
Besides, you are using `sudo` for this build. You can use `apt-get` to install the package if you really need it.

**Comment by radeksimko** [comment]
Thanks, I will have a look. I did not know nvm was available in all images.
