### ISSUE TITLE
Updating store cache in any job?

### ISSUE THREAD

**Issue by drgarcia1986** [travis-ci/travis-ci#3903]
For some reason in every job travis is updating the cache (even not occurring changes).
It's the right behavior?

https://travis-ci.org/drgarcia1986/simple-settings/jobs/62652372#L337
(if I restart this build will redo the cache).

**Comment by pecota** [comment]
I have this problem to on my java build.

![cache-problem](https://cloud.githubusercontent.com/assets/1915988/7657812/6f8369c0-fb0b-11e4-9c00-af9a18faf59b.png)

**Comment by BanzaiMan** [comment]
The cache updates are detected by mtime at the moment. If the change in the pip cache is expected, you need to remove it from the cache.

This is expected behavior for now. (We are looking to improve this area, but no ETA for that.)

**Comment by BanzaiMan** [comment]
Hello. We've deployed the checksum-based file change detection earlier this week. This should improve your case. 

I'm closing this issue optimistically, but if you still see the problems, so let us know.
