### ISSUE TITLE
No branches available

### ISSUE THREAD

**Issue by lkundrak** [travis-ci/travis-ci#3904]
No matter what I do, nothing appears here: no branches or anything:

https://travis-ci.org/lkundrak/NetworkManager/branches

**Comment by joshk** [comment]
Hi there

I see that you don't have any builds on Travis yet, which means we can't populate the branches tab.

Could you try running your first build on Travis and let us know how you get on?

Thanks

**Comment by lkundrak** [comment]
How do I trigger a build? Can't see anything that would let me do that via the UI. I pushed to a branch, but nothing seems to have happened.

**Comment by joshk** [comment]
Have you followed the Getting Started guide? Especially this step http://docs.travis-ci.com/user/getting-started/#Step-two%3A-Activate-GitHub-Webhook

**Comment by joshk** [comment]
I checked https://travis-ci.org/lkundrak/NetworkManager/requests and I see you disabled all pushes, added the .travis.yml to your travis branch, then possibly reenabled pushes, but as you haven't commited to that branch since, no builds have been built.

**Comment by lkundrak** [comment]
I tried to. I flipped the switch, have "Build pushes" enabled and verified that the web hook is present on GitHub. The branch I pushed into has .travis.yml file.

I did not validate it, I presumed I'd get an error message if it's not correct. The branch is here: https://github.com/lkundrak/NetworkManager/tree/travis

**Comment by lkundrak** [comment]
Well, the UI was not responsive, I'm not really sure what state it was in. I'll try doing another push -- thanks for the suggestion.

**Comment by lkundrak** [comment]
Oh, I see a build in the build history now.

Thanks for the assistance, it's very much appreciated!

Closing this now.
