### ISSUE TITLE
Swift 1.2 Support

### ISSUE THREAD

**Issue by ankurp** [travis-ci/travis-ci#3905]
There has been no update on this issue https://github.com/travis-ci/travis-ci/issues/3216 

@joshk Are you or someone else still working on this as more than a month has passed since Swift 1.2 is out?

**Comment by BanzaiMan** [comment]
Thanks for the nudge. Yes, we are working on it, and will update #3216 once we have news to share. In the meantime, I'm closing this as a duplicate.
