### ISSUE TITLE
APT whitelist request for libgstreamer1.0-dev

### ISSUE THREAD

**Issue by bennygr** [travis-ci/travis-ci#3912]
GStreamer 1.0 core development files

**Comment by BanzaiMan** [comment]
This package does not exist for Precise: http://packages.ubuntu.com/precise/libgstreamer1.0-dev

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libgstreamer1.0-dev' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libgstreamer1.0-dev' needs trusty

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/373.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
