### ISSUE TITLE
APT whitelist request for python-pypy.translator.sandbox

### ISSUE THREAD

**Issue by ProgVal** [travis-ci/travis-ci#3918]
It's available in Precise: http://packages.ubuntu.com/precise/amd64/python-pypy.translator.sandbox

Note: Starting from Trusty, it is renamed [python-pypy.sandbox](http://packages.ubuntu.com/search?keywords=python-pypy.sandbox)

**Comment by BanzaiMan** [comment]
Perhaps I'm missing something, but why do you need PyPy? The packages in repositories are older than the version preinstalled on the Python image.

**Comment by ProgVal** [comment]
This package provides a sandboxed version of Pypy, which is called by my application for running untrusted code.
