### ISSUE TITLE
D language support: ability to select GDC 4.9.2

### ISSUE THREAD

**Issue by p0nce** [travis-ci/travis-ci#3920]
"gdc-4.9.2" doesn't work
and "gdc" is not it, it selects a DMDFE 2.055 front-end.

Ping @MartinNowak, @klickverbot and @ibuclaw

**Comment by MartinNowak** [comment]
A little more detail on what doesn't work would be helpful.
Do you have build output?

**Comment by p0nce** [comment]
Sure.

This is a problem for https://github.com/p0nce/dplug which critically depends on `@nogc`.
This Travis configuration is used: https://github.com/p0nce/dplug/blob/master/.travis.yml


For the worker with "gdc-4.9.2" (I've stripped the beginning of the ouput which is quite long and unrelated)
```
0.29s$ git clone --depth=50 --branch=master git://github.com/p0nce/dplug.git p0nce/dplug
Cloning into 'p0nce/dplug'...
remote: Counting objects: 491, done.
remote: Compressing objects: 100% (301/301), done.
remote: Total 491 (delta 226), reused 330 (delta 85), pack-reused 0
Receiving objects: 100% (491/491), 1.17 MiB | 0 bytes/s, done.
Resolving deltas: 100% (226/226), done.
Checking connectivity... done.
$ cd p0nce/dplug
$ git checkout -qf 19b1d905051afd31f71ea10ae21885b1b8a5d7a2
$ export DC=gdc
$ export DMD=gdmd
D support for Travis-CI is community maintained.
Please make sure to ping @MartinNowak, @klickverbot and @ibuclaw when filing issues under https://github.com/travis-ci/travis-ci/issues.
Installing compiler and dub
0.02s$ CURL_USER_AGENT="Travis-CI $(curl --version | head -n 1)"
0.01s$ curl() { command curl -fsSL --retry 3 -A "${CURL_USER_AGENT}" "$@"; }
0.01s0.54s$ curl http://gdcproject.org/downloads/binaries/x86_64-linux-gnu/gdc-4.9.2.tar.xz | tar --strip-components=1 -C ~/gdc -Jxf -
curl: (22) The requested URL returned error: 404
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command "curl http://gdcproject.org/downloads/binaries/x86_64-linux-gnu/gdc-4.9.2.tar.xz | tar --strip-components=1 -C ~/gdc -Jxf -" failed and exited with 2 during .
Your build has been stopped.
```

For the worker with just "gdc":
http://pastebin.com/Stus50xB (the compiler errors on @nogc thus revealing it's based on DMDFE 2.055)

**Comment by MartinNowak** [comment]
Iain will have to add symlinks from http://gdcproject.org/downloads/binaries/x86_64-linux-gnu/gdc-4.9.2.tar.xz to http://gdcproject.org/downloads/binaries/x86_64-linux-gnu/i686-linux-gnu_2.066.1_gcc4.9.2_f378f9ab41_20150405.tar.xz, then I can update http://ftp.digitalmars.com/LATEST_GDC.

**Comment by ibuclaw** [comment]
The site just needs a better way to structure downloads.

**Comment by MartinNowak** [comment]
Maybe simply add another symlink for now and do something better later?

**Comment by ibuclaw** [comment]
OK, managed to hop on an add it.  I think what you mean was the x86_64 tarball, not the i686 cross.

**Comment by p0nce** [comment]
Can confirm it works. Thanks!

**Comment by MartinNowak** [comment]
Great, I'll update the latest version as well (so that `gdc` uses `gdc-4.9.2`).

**Comment by MartinNowak** [comment]
Done
