### ISSUE TITLE
APT source whitelist request for webupd8team/sublime-text-2/3

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#3921]
* ppa:webupd8team/sublime-text-2
 * ppa:webupd8team/sublime-text-3

They are used for testing sublime text packages.
The testing script using the ppas: https://github.com/randy3k/UnitTesting/blob/cd63917cf7cf9d44a09a3e73a75ca906e678f2a9/sbin/travis.sh

**Comment by BanzaiMan** [comment]
Did not run automated check because 'webupd8team/sublime-text-2/3' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/30.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
