### ISSUE TITLE
Corrupted build output with repeating message.

### ISSUE THREAD

**Issue by danielkza** [travis-ci/travis-ci#3924]
The following build seems to have it's logs corrupted for some reason. A message (which actually makes sense in context) is repeated thousands of times throughout, but even in places where it could not possibly have happened yet, before the code is even checked out.

https://travis-ci.org/mezuro/kalibro_processor/builds/63250756

edit: I restarted the build thinking the link would still be valid but it isn't anymore. Sorry, I forgot to save the logs beforehand. I hope you guys can still get them even if I can't.

**Comment by BanzaiMan** [comment]
Unfortunately a restart does not preserve previous logs. Please re-open if it's still an issue.
