### ISSUE TITLE
APT source whitelist request for analizo

### ISSUE THREAD

**Issue by danielkza** [travis-ci/travis-ci#3925]
[Analizo](http://analizo.org) is a tool to measure source code metrics for C, C++ and Java. 

Repository configuration:

```
deb http://www.analizo.org/download/ ./
deb-src http://www.analizo.org/download/ ./
```

GPG key: http://www.analizo.org/download/signing-key.asc

**Comment by BanzaiMan** [comment]
Did not run automated check because 'analizo' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/31.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
