### ISSUE TITLE
APT whitelist request for mailx

### ISSUE THREAD

**Issue by efx** [travis-ci/travis-ci#3929]
http://packages.ubuntu.com/precise/mailx
need to ensure binary exists for use within script

**Comment by BanzaiMan** [comment]
Do you have a preference on which one? There are 3 listed in http://packages.ubuntu.com/precise/mailx.

**Comment by efx** [comment]
http://packages.ubuntu.com/precise/heirloom-mailx
Thanks.

**Comment by BanzaiMan** [comment]
This package includes a `setgid` binary, but the bit will be removed when it is installed on the container.
