### ISSUE TITLE
HHVM builds don't work with phpenv

### ISSUE THREAD

**Issue by shadowhand** [travis-ci/travis-ci#3930]
Similar to #2523, but not quite the same:

```
$ phpenv config-add .travis.php.ini
cp: cannot create regular file `/home/travis/.phpenv/versions/hhvm/etc/conf.d': No such file or directory
The command "phpenv config-add .travis.php.ini" failed and exited with 1 during .
```

We want to be able to build on HHVM _and_ PHP 5.x. Right now it seems the only way to work around this is to create a custom `.ini` only for HHVM, which we'd like to avoid.

cc @dolfelt

**Comment by BanzaiMan** [comment]
Can you create the directory `/home/travis/.phpenv/versions/hhvm/etc/conf.d` before you run this?

**Comment by shadowhand** [comment]
Probably, but I assume there is a deeper infrastructure problem... if the `conf.d` directory is not created, it probably means that the default HHVM config is not attempting to load from that directory.

**Comment by BanzaiMan** [comment]
HHVM is known to diverge from what the reference PHP does.

**Comment by shadowhand** [comment]
This is a server configuration issue, not a difference in HHVM vs PHP runtime.

**Comment by BanzaiMan** [comment]
Well, it's not. Upon further inspection, I think it is how we bend HHVM package to work with phpenv. Anyhow, until we fix the cookbooks, I suggest creating the directory.

**Comment by photodude** [comment]
I've been working to include [HHVM in a build](https://github.com/photodude/joomla-cms/tree/patch-2) and found similar issues; like the missing conf.d
I tried working around this issue by starting services and using apt-get (pecl isn't supported in HHVM)
PHP 7 and HHVM both seem to be basically "nightly" builds where "common PHP extensions" are not preinstalled (related to the lack of PECL in PHP7 and HHVM)
The php.ini is also in a different location for HHVM so I included the following for hhvm
```
    PHPINI=/etc/hhvm/php.ini
    echo "extension_dir = /etc/hhvm" >> $PHPINI
```

**Comment by photodude** [comment]
This is still an issue...

**Comment by photodude** [comment]
in the .travis.yml
```yml
 - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then cat hhvm.php.ini >> /etc/hhvm/php.ini; fi
```

with the hhvm.php.ini set to your required memory limit
```ini
memory_limit = 4000M
```
