### ISSUE TITLE
APT source whitelist request for protobuf 2.5.0

### ISSUE THREAD

**Issue by riteshkfb** [travis-ci/travis-ci#3931]
The launchpad url for the ppa is : https://launchpad.net/~chris-lea/+archive/ubuntu/protobuf. The ppa desc is ppa:chris-lea/protobuf

Need this for compiling apache hadoop.

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'Addition of protobuf 2.5.0 to apt whitelist for ubuntu precise' is ambiguous. Please specify only one.

**Comment by BanzaiMan** [comment]
Looks like a duplicate of #3794.
