### ISSUE TITLE
Add PHP 7, HHVM to testing example

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#3933]
The [Travis CI example for PHP](https://github.com/travis-ci-examples/php) needs some updates to make the example more valuable to developers. 

A PR has been created for this update https://github.com/travis-ci-examples/php/pull/18

**Comment by BanzaiMan** [comment]
Thank you! I merged the PR.

**Comment by photodude** [comment]
@BanzaiMan Thank you for merging the PR
