### ISSUE TITLE
Something weird is happening on the Mac OSX build environment lately

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#3934]
We have an Emscripten CI job setup on OSX build environment. It was running fine and we managed to tweak our job so that it compiles and tests run within the 50 minutes time limit. But until recently, the CI job has constantly been killed by Travis as it did not complete the test and sometimes even the build itself within the time limit.

Perhaps below also shows there is something wrong with OSX build infra lately. It appears to be saturated quite frequently even at low volume.
![osx-saturated](https://cloud.githubusercontent.com/assets/5548048/7740178/05336cac-ffa0-11e4-962f-649d5b287879.png)

**Comment by BanzaiMan** [comment]
We are making changes to the Mac infrastructure, indeed. If you are seeing problems, do email support@travis-ci.com with details.

We'll make announcement about this change soon.

**Comment by weitjong** [comment]
Thanks for the prompt reply. Is that mean whatever the changes Travis team has made into the Mac infrastructure lately will become permanent? And we will have to cope with it on our end?

**Comment by BanzaiMan** [comment]
@weitjong I don't know what changes you are seeing, so I can't really say. Either wait for the announcement, or email details, please!

**Comment by weitjong** [comment]
Ok. I will wait for the announcement then. Just in case what I am seeing is just a fluke while Travis team making changes.

**Comment by BanzaiMan** [comment]
@weitjong Could you elaborate on what you meant by "something weird"? Is it that the "Mac" graph seems extremely low? If so, I suspect it is due to the metrics not being wired up correctly (with the new infrastructure coming online). We are looking to fix that now.

**Comment by BanzaiMan** [comment]
@weitjong Also, could you point to the build log that shows the timeout problems you are having? Thanks!

**Comment by weitjong** [comment]
Here is one from today run. https://travis-ci.org/urho3d/Urho3D/builds/63451237
It is weird because it was running so slow. We have heavily tuned our Emscripten CI build such that it would adapt based on the elapsed time of certain process to decide whether it would skip the next process and so on. So, when the Mac infra is fast then our job would run the full suit of our tests and when the infra is under heavy load (i.e. slow) then our job would skip one or two or even all the tests (i.e. only build the software).

However, in the past few days the infra was atypically slow that even the job was struggling to building the software alone, let alone to test it. And since our elapsed time checkpoint are finely tuned, the atypical slow performance of the infra has rendered our checkpoints useless.

**Comment by henrikhodne** [comment]
Hi, sorry for the slowness. I discovered that on our previous set up we had two cores allocated to each VM, while on the new one we only had one core allocated with the default image. I changed the configuration to now allocate two cores to each VM, so hopefully things are back to a similar speed. The underlying CPU is still different from the old setup (old clock speed was 2.28 GHz, new clock speed is 2.92 GHz, for example), but it should be much closer in speed now. Could you re-run your tests and see if you notice a change?

Thanks for reporting this :heart: :sparkles:

**Comment by weitjong** [comment]
Instead of waiting for thing to get better again on Mac OS X build infra, we have successfully migrated our Emscripten CI job to new container-based build infra just today. As the new container-based build infra has 2 dedicated CPUs allocation per VM, I hope the migrated Emscripten CI job is now resilient to the Travis server load there. Note that the reason we could not use the Linux build infra earlier is because Emscipten SDK only provides prebuilt toolchain binaries for Mac OS X, but I managed to prebuild the SDK for Linux using our own way now to facilitate this migration.

@henrikhodne I could switch back to use Mac OS X build infra temporarily in my own fork of our project to test out your changes for Mac OS X. I will let you know shortly my test result.

**Comment by weitjong** [comment]
The [result](https://travis-ci.org/weitjong/Urho3D/builds/63642745) is inclusive with just one run and especially at these hours. At least I can confirm the job did not have any problem now to build the software itself. But it was still a struggle to test run all the test cases. However, I would probably say that is perfectly "back to normal". That is why we have those elapsed-time checkpoints as I mentioned in my earlier comment. I am triggering another run to see how it goes. Usually performance on Mac OS X build infra is bad at night time (Singapore Time) and is decent at day time SGT.

**Comment by weitjong** [comment]
Closing this issue as the root cause has been found and fixed by your team on Mac OS X build infra and I am no also no longer having this issue after migrating it. Thank you for all your support.
