### ISSUE TITLE
Travis can suddenly not find .travis.yml even though it exists

### ISSUE THREAD

**Issue by lau** [travis-ci/travis-ci#3936]
https://travis-ci.org/lau/calecto/builds/63119604
"Could not find .travis.yml, using standard configuration."

.travis.yml is there. Why can Travis not find it?

The repo was renamed in GitHub and suddenly this error appeared.

**Comment by digitalheir** [comment]
Go to your profile: https://travis-ci.org/profile/{username}

Click 'Sync'. This should let Travis know about your renamed repo. Retrigger the build, it should work again. You may also need to update your build badge due to the name change.

**Comment by lau** [comment]
Hi. Thanks for the response. I'll keep that in mind next time it happens. I think I just pushed a new commit to Github and then the problem went away.

**Comment by venkatsamuthiram** [comment]
The repo was renamed in GitHub and suddenly this error appeared. 
@lau   that is right but, I transfer my repository to my company repository. Now, Travis test default Ruby, 
my project write on PHP lang. what will do??
