### ISSUE TITLE
Renaming repo causes repository not known error.

### ISSUE THREAD

**Issue by StephenTurley** [travis-ci/travis-ci#3938]
renamed repo from grocery_totes to grocery-totes and get the following error:

`repository not known to https://api.travis-ci.org/: StephenTurley/grocery-totes`

I've removed the link to the original name, and re-cloned the project. I've also re-authorized access to my github account. 

The travis dashboard still has the original name in the list of repositories.

**Comment by BanzaiMan** [comment]
Please try syncing your user data on https://travis-ci.org/profile and try again.
