### ISSUE TITLE
NuGet often times out and fails the build

### ISSUE THREAD

**Issue by Mailaender** [travis-ci/travis-ci#3940]
Somehow the Travis infrastructure has severe connectivity problems to nuget.org which exceptionally often fails the build and requires manual restarting:

> WARNING: Error: ConnectFailure (Connection timed out)

or

> WARNING: Could not connect to the feed specified at 'https://www.nuget.org/api/v2/'.

`travis_retry` is no help. It will just fail three times then.

> The command "make all-dependencies" failed 3 times.

**Comment by splitice** [comment]
+1

**Comment by BanzaiMan** [comment]
Sorry for the late note here. cc  @joshua-anderson @akoeplinger @nterry

**Comment by Mailaender** [comment]
As it turned out to be a problem with the NuGet client on Mono somehow beyond your control we decided to create a workaround shell script: https://github.com/OpenRA/OpenRA/blob/bleed/thirdparty/noget.sh
