### ISSUE TITLE
APT whitelist request for npm

### ISSUE THREAD

**Issue by singingwolfboy** [travis-ci/travis-ci#3941]
`npm` is provided by the `node_js` language environment on Travis, but sometimes projects that use different language environments need to use `npm`. `nodejs` is whitelisted, but not `npm`.

**Comment by BanzaiMan** [comment]
On all build environments, `nvm` is installed, and you can install Node.js runtimes on demand. You can then install npm as well.

**Comment by singingwolfboy** [comment]
@BanzaiMan Thanks for the tip! However, that means changing build scripts to insert an extra step. I'd rather change my build scripts as little as possible.

**Comment by BanzaiMan** [comment]
@singingwolfboy But you will be modifying `.travis.yml` if this package is added, right? My personal goal is to not rely on this addon for the long term. Using `nvm` is a more future-proof solution.

**Comment by emdantrim** [comment]
The `npm` package in the `precise` apt repository is pretty old (1.1.4) and it seems that @singingwolfboy's issue was solved in the linked ticket and https://github.com/edx/edx-ora2/pull/705#issuecomment-106827389 , so I think that this is safe to close.
