### ISSUE TITLE
APT whitelist request for mpich2

### ISSUE THREAD

**Issue by justusc** [travis-ci/travis-ci#3955]
Package http://packages.ubuntu.com/precise/mpich2

**Comment by BanzaiMan** [comment]
```
  * Make /usr/bin/mpdroot setuid. This is the default after the installation
    of mpich2 from source, too. LP: #616929
```

There are a couple of Python source files with `os.setuid()` calls. I _*think*_ the installation itself is OK, but I would like a second opinion here.

@meatballhat @emdantrim Could you take a look?

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/370.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
