### ISSUE TITLE
APT source whitelist request for ubuntu-wine

### ISSUE THREAD

**Issue by kriegfrj** [travis-ci/travis-ci#3959]
ppa:ubuntu-wine/ppa

The version of wine available with Ubuntu 12 is out of date and buggy and won't run the software I was trying to run (Oracle JDK 7 for Windows). Either enabling this ppa or possibly enabling Ubuntu 14 would allow me to get this working.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ubuntu-wine' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ubuntu-wine' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/28.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
