### ISSUE TITLE
APT whitelist request for wine1.6

### ISSUE THREAD

**Issue by kriegfrj** [travis-ci/travis-ci#3960]
Also wine1.7. Default wine enabled by #3183 installs wine1.4 which doesn't run Oracle JDK 7.

Depends on whitelisting the ubuntu-wine ppa too (#3959).

**Comment by BanzaiMan** [comment]
Did not run automated check because 'wine1.6' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'wine1.6' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/371.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
