### ISSUE TITLE
Brace expansion not working in NPM scripts

### ISSUE THREAD

**Issue by pdubroy** [travis-ci/travis-ci#3963]
NPM scripts which use shell brace expansion are failing when they are run on Travis CI.

E.g., with the following in package.json:
```
  "scripts": {
    "foo": "ls {README.md,TODO.md}"
  }
```

Running `npm run foo` on Travis results in the following error:
```
ls: cannot access {README.md,TODO.md}: No such file or directory
```

I tried putting the same command in my .travis.yml file:

```
before_install:
  - "ls {README.md,TODO.md}"
```

This works as expected.

You can find an example of the error in line 1180 of job #7.1 of my only repository on travis-ci.com.

**Comment by BanzaiMan** [comment]
This seems like an npm issue to me. Is this a recent new feature?

**Comment by pdubroy** [comment]
Brace expansion is a Bash feature (http://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html) and has been around for quite a while (about 10 years IIRC). Since the command works when it's run in the `before_install` script, and the NPM script works on my machine (Mac OS X, same version of NPM), it seems to be something related to the Travis environment.

Aaaand after some investigation into how `npm run-script` selects the shell (https://github.com/npm/npm/issues/6543), I think the problem is that it *always* uses /bin/sh -- which is bash on OSX, but DASH on Ubuntu.

So, I guess it's a bad idea to include bash-isms in NPM scripts, and not an issue with the Travis environment. Sorry!

**Comment by BanzaiMan** [comment]
No problem! Closing this now.
