### ISSUE TITLE
APT source whitelist request for google-chrome

### ISSUE THREAD

**Issue by Waog** [travis-ci/travis-ci#3964]
I'm not that much of a Linux and APT expert, so I'll just copy the link's into this ticket which I assume to be required (feel free to edit this ticket). Links taken from: http://www.ubuntuupdates.org/ppa/google_chrome

- deb http://dl.google.com/linux/chrome/deb/ stable main
- https://dl-ssl.google.com/linux/linux_signing_key.pub
- *package name:* google-chrome-stable

Thx in advance for reading it :)

**Comment by dsnopek** [comment]
+1 We also need to be able to install Chrome! Our Selenium-based tests depend on it.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'Google Chrome' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'Google Chrome' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT source whitelist request for Google Chrome' is ambiguous. Please specify only one.

**Comment by Waog** [comment]
Don't exactly know what to do!? I changed the title to *APT source whitelist request for google-chrome*, does that help?

**Comment by BanzaiMan** [comment]
@Waog Sorry for the alarm. There is nothing for you to at the moment.

We are in the process of automating APT whitelist request processing, and my previous comment came from that.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/35.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
