### ISSUE TITLE
APT whitelist request for fontforge ttfautohint

### ISSUE THREAD

**Issue by shehi** [travis-ci/travis-ci#3965]
Hi. I need these packages (```fontforge``` and ```ttfautohint```) to build web-font assets of my project. These tools don't require ```sudo``` for usage, but they do for installation. I checked ```precise```'s repo, and I believe both packages are available in official repo.

The project I use these tools in, is: http://github.com/AudithSoftworks/Basis (```admin-panel-ui``` branch). TravisCI builds start from https://travis-ci.org/AudithSoftworks/Basis/builds/64079425

My application of tools is derived from tutorials at: http://www.useragentman.com/blog/the-css3-font-converter/

Thanks.

**Comment by BanzaiMan** [comment]
Where is `ttfautohint` found? It's not in http://packages.ubuntu.com/precise/amd64/fontforge/filelist.

**Comment by shehi** [comment]
```ttfautohint``` exists in Trusty (Ubuntu 2014), not Precise. Anyway, I stopped using TravisCI due to continuous problems (builds couldn't even fetch composer dependencies), so feel free to disregard this request. I don't even understand why you bother processing these whitelisting requests for Precise - it's just archaic and waste of time.
