### ISSUE TITLE
 APT whitelist request for python-swiftclient

### ISSUE THREAD

**Issue by kahing** [travis-ci/travis-ci#3966]
Needed to run SwiftProxy tests:

https://travis-ci.org/bouncestorage/swiftproxy/builds/64131426

**Comment by BanzaiMan** [comment]
Where is this found? It's not in the official repository. http://packages.ubuntu.com/precise/python-swiftclient

**Comment by kahing** [comment]
is travis only on precise?

**Comment by BanzaiMan** [comment]
Right now, yes.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'python-swiftclient' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because 'python-swiftclient' needs trusty

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/374.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
