### ISSUE TITLE
APT source whitelist request for older clang versions

### ISSUE THREAD

**Issue by brunocodutra** [travis-ci/travis-ci#3969]
Older versions of popular compilers are very useful to attest code portability, however approved sources currently provide only the newest versions of clang (3.5 - 3.7). Please consider whitelisting this [PPA](https://launchpad.net/~h-rayflood/+archive/ubuntu/llvm)¹, which provides ports of Debian LLVM packages for older versions of clang (2.9-3.6)

As a side note, I've noticed [travis-ci-tester/travis-test-clang-3.2 ](https://github.com/travis-ci-tester/travis-test-clang-3.2/blob/cmake.clang-3.2/.travis.yml) also uses this PPA, if that's of any relevance.

[1] ppa:h-rayflood/llvm

**Comment by BanzaiMan** [comment]
Did not run automated check because 'older clang versions' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'older clang versions' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT source whitelist request for older clang versions' is ambiguous. Please specify only one.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/32.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
