### ISSUE TITLE
bundle: command not found for JRuby 9.0.0.0.pre2

### ISSUE THREAD

**Issue by RX14** [travis-ci/travis-ci#3972]
I'm having issues with a travis build where it doesn't install bunder. This is a ruby build and the docs say that bunder is in the default gemset.

The failing build: https://travis-ci.org/RX14/satapi/builds/64324440
Another failing build not con the container infrastructure: https://travis-ci.org/RX14/satapi/builds/64322169

**Comment by BanzaiMan** [comment]
Looks like RVM is preferring https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0.pre2/jruby-bin-9.0.0.0.pre2.tar.gz (https://travis-ci.org/RX14/satapi/builds/64324440#L105) to ours (http://rubies.travis-ci.org/ubuntu/12.04/x86_64/jruby-9.0.0.0.pre2.tar.gz).

Neither seems to have bundler pre-installed, actually. This, I believe, is an issue with RVM.

@mpapis, I have questions.

1. Is it possible to prefer pre2 on rubies.travis-ci.org to one on S3?
1. Why does our archive not include bundler? You can see the build log here: https://travis-ci.org/travis-ci/travis-rubies/jobs/60599751

**Comment by RX14** [comment]
It's not just pre2, it seems to be any jruby version...

**Comment by BanzaiMan** [comment]
What versions did you try?

1.7.19 is pre-installed, and it works. https://travis-ci.org/BanzaiMan/travis_production_test/builds/64330874#L94

**Comment by mpapis** [comment]
@BanzaiMan RVM stopped supporting `bundler` by default some time ago, Travis defines gems to add/remove - add `bundler` to the list Travis requires

**Comment by RX14** [comment]
@banzaiman you can see the build log and repo from the Travis url to see what versions I have tried.

**Comment by BanzaiMan** [comment]
@RX14 Currently, the only pre-installed version is 1.7.19. I don't see any build from today using it.

**Comment by RX14** [comment]
I'll try 1.7.19. Although it says in the docs that these builds should be usable.

**Comment by RX14** [comment]
Okay 1.7.19 doesn't seem to have the same problems, although I'm now seeking some errors with the build cache and bundler.

Here is the build: https://travis-ci.org/RX14/satapi/builds/64342545

Regardless, I think that these ruby versions should work because they are advertised on your own binary rubies site. I actually couldn't find any docs on which rubies were installed vs which were binary downloads.

**Comment by BanzaiMan** [comment]
@RX14 What is the problem with this build? It is strange that you get all those warnings when `rvm --version` and `gem --version` run, but my build did not. But the warnings aside, the problem seems to be an issue with your `ci` Rake task.

We'll look into why non-pre-installed JRuby runtimes don't work. Thanks for raising the issue.

**Comment by RX14** [comment]
Yeah the failing build itself is my fault, although the errors on bundler etc. and the error in the caching save step are not.

**Comment by BanzaiMan** [comment]
@RX14 I think there are a few issues, to be sure.

1. I am having a hard time reproducing your "Ignoring ** because its extensions are not built." messages. [Google search](https://www.google.com/search?q=ignoring+because+its+extensions+are+not+built&oq=ignoring+because+its+extensions+are+not+built&aqs=chrome..69i57.10744j0j1&sourceid=chrome&es_sm=119&ie=UTF-8) reveals this to be a common problem, but the suggested fixes don't seem to apply on Travis, when the builds start from scratch. I tend to think that there is something in your repo, but I am not sure what that might be.
1. I'm a little surprised that the cache upload is even attempted, since the build failed. At any rate, the gems are not added to the cache because you override the `install` section (see http://docs.travis-ci.com/user/caching/#With-a-custom-install-step).

**Comment by RX14** [comment]
Ah I will keep that in mind.

**Comment by BanzaiMan** [comment]
@mpapis We have this in `~/.rvmrc`, which I thought was supposed to tell RVM to install Bundler:

```
export rvm_user_install_flag=1
export rvm_path="/home/travis/.rvm"
export rvm_project_rvmrc=0
export rvm_silence_path_mismatch_check_flag=1
export rvm_max_time_flag=5
export rvm_autoupdate_flag=0
export rvm_without_gems="rubygems-bundler"
export rvm_with_default_gems="rake=~>10.4.2 bundler=~>1.9.2"

rvm_without_gems="rubygems-bundler"

rvm_with_default_gems="rake=~>10.4.2 bundler=~>1.9.2"
```

What am I missing?

**Comment by mpapis** [comment]
@BanzaiMan aha, so if you build this ruby to repackage it you should use `global` not `default` gemset - so try changing `~/.rvmrc` from `rvm_with_default_gems=` to `rvm_with_gems=`

**Comment by BanzaiMan** [comment]
@mpapis when did that change happen?

**Comment by mpapis** [comment]
it's not a change - it all depends on what you want to achieve, global gemset represents the rubys gems location when used without rvm, default gemset is separate directory that is not packaged back with ruby - and it was not my choice to use one or another, I only added code for what was requested - it was the default at the time.

**Comment by BanzaiMan** [comment]
@RX14 I reproduced your problem: https://travis-ci.org/BanzaiMan/travis_production_test/builds/64403295#L133. The problem manifests only when `JRUBY_OPTS=--2.0` is set. The default compat version for JRuby 9k is MRI 2.2, and the 2.0 mode is not officially supported on the 1.7 series, so you should not put that in.

**Comment by RX14** [comment]
I think I will simply upgrade to jruby 9000, remove the jruby opts and have done with it. Thanks for the help!

**Comment by dekellum** [comment]
I seem to have the same problem of no bundler, in build below and some prior builds, with jruby-head and without JRUBY_OPTS being set (by me at least): 

https://travis-ci.org/dekellum/fishwife/jobs/67468574

**Comment by BanzaiMan** [comment]
@dekellum I just tried it, but was unable to reproduce it. https://travis-ci.org/BanzaiMan/travis_production_test#L173 The only difference I could find is the jruby head's commit (1dc3b6e vs ba4a334). Can you try another build?

**Comment by dekellum** [comment]
Restarted and picked up 1dc3b6e jruby-head. Same result.  It doesn't get farther than checking for the `bundle --version` before its clear there is a problem with lack of bundler:

https://travis-ci.org/dekellum/fishwife/jobs/67468574#L174

**Comment by BanzaiMan** [comment]
@dekellum I'm having problems reproducing it. I tend to think there is something in your repository that's causing the problem, but I don't know what that is. If you email support@travis-ci.com we can spin up a debug VM for you.

**Comment by dekellum** [comment]
OK, I've spent some time debugging with a simpler project and have reported jruby/jruby#3078, which I believe to be the true culprit in my case.

Is the travis build script somehow masking error output/status from `bundle --version`? Might the `bundle: command not found` error be erroneous, as a result of a non-zero exit status from this command (and more involved error?) or some other error in a previous setup step?

**Comment by dhoppe** [comment]
I am facing the same problem, since we added JRuby to the build matrix. 

https://travis-ci.org/voxpupuli/puppet-collectd

Any idea if we just missed some sort of configuration?

https://github.com/voxpupuli/puppet-collectd/pull/473

**Comment by BanzaiMan** [comment]
@dhoppe You are setting invalid `$JRUBY_OPTS`. This appears to be interfering with our `ruby` invocation.

```sh-session
$ rvm use jruby-1.7.19
Using /Users/asari/.rvm/gems/jruby-1.7.19
$ export JRUBY_OPTS="-J -Xmx1024M --debug"
$ ruby -v                                 
Error: Could not find or load main class 
```

Remove that offending line and try again.

**Comment by dhoppe** [comment]
@BanzaiMan Thank you very much for pointing me into the right direction, but there is still one problem left. 

Sometimes our builds are failing because the binaries of Ruby 2.3.0 could not be found/installed.

OK https://travis-ci.org/voxpupuli/puppet-collectd/jobs/124940340
FAILED https://travis-ci.org/voxpupuli/puppet-collectd/jobs/124962194

**Comment by BanzaiMan** [comment]
@dhoppe Us `2.3.0`, not `2.3`.

**Comment by dhoppe** [comment]
@BanzaiMan Thank you very much, but this does not make any sense. This syntax is still working for 2.1/2.2 and should fetch the latest patch release.

**Comment by BanzaiMan** [comment]
@dhoppe There is an alias `2.1` and `2.2` pointing to a more precise versions, while there is none for `2.3`. Also, this issue is about JRuby, not MRI.

**Comment by dhoppe** [comment]
@BanzaiMan Thank you very much. Next time I will create an separate issue.

**Comment by BanzaiMan** [comment]
JRuby 9.0.0.0 was released long time ago. If you see problems still, do let us know.
