### ISSUE TITLE
Installed libssl 1.0.0 misbehaves

### ISSUE THREAD

**Issue by Rantanen** [travis-ci/travis-ci#3976]
There seems to be something wrong in `libssl` on travis-ci.org environments. This manifests in for example `openssl` command line tools exhibiting some incosistent behaviour.

VM-based infrastructure: https://travis-ci.org/Rantanen/node-dtls/jobs/63860821
Container-based infrastructure: https://travis-ci.org/Rantanen/node-dtls/jobs/63988024

I contacted support about this earlier and with invaluable help from @drogus I managed to reproduce this in a docker-based container - Before this I had unsuccessfully tried to reproduce the problem over SSH in a debug VM he provided and in a [travis-ci/travis-cookbooks](https://github.com/travis-ci/travis-cookbooks) based Vagrant environment I set up. (It seemed like there were some differences between the debug VMs available over SSH and the actual VM based CI infrastructure?)

In the container based environment it was easily reproduced by running `openssl s_server -dtls1` in one terminal and `openssl s_client -dtls1` in another - the `s_server` process crashed to Segmentation Fault.

`gdb` pointed the stack trace to `libcrypto.so.1.0.0` which is part of `libssl` package. When I tried installing the debugging symbols with `apt-get install libssl1.0.0-dbg` I saw `libssl1.0.0` being installed as well and after I re-executed my tests the issue was gone.

The conclusion I came to is that there's a `libssl` version compiled/installed from a source other than the ubuntu repositories that is causing issues. Installing the `libssl` from ubuntu repositories fixed this. When I added `sudo apt-get install libssl1.0.0` to my `.travis.yml` the problem went away on travis-ci.org as well.

**Comment by BanzaiMan** [comment]
This is curious. We install `openssl` package from the Ubuntu repository (https://github.com/travis-ci/travis-cookbooks/blob/ff28e574541d34669f90c2bd9f21a297307f31f3/ci_environment/openssl/recipes/default.rb#L20; http://packages.ubuntu.com/precise/openssl).

This package in turn installs `libssl1.0.0`, which puts file `/lib/x86_64-linux-gnu/libssl.so.1.0.0` (http://packages.ubuntu.com/precise/amd64/libssl1.0.0/filelist; https://travis-ci.org/BanzaiMan/travis_production_test/builds/64468969#L106).

Could it be the bad version installed?

**Comment by Rantanen** [comment]
Guess it could be that. It would explain why the new VMs, etc. won't exhibit the same behavior.
