### ISSUE TITLE
ruby-head on default OS X is old

### ISSUE THREAD

**Issue by eregon** [travis-ci/travis-ci#3977]
ruby-head on the default OS X configuration (just listed in `os`, no `osx_image`) is
```
ruby 2.2.0dev (2014-12-03 trunk 48697) [x86_64-darwin13]
```

Could you update it to a recent version?

The builds of ruby/ruby seem to pass on OS X as well: https://travis-ci.org/ruby/ruby/builds/64539171.
Is the webhook also rebuilding for OS X?

**Comment by BanzaiMan** [comment]
New ones do not exist because the build is failing: https://travis-ci.org/travis-ci/travis-rubies/jobs/64541720#L273-L277

I'm looking into fixing it.

**Comment by BanzaiMan** [comment]
To clarify: the binary compiles, but the resulting installation is unable to install Bundler, so we do not upload the archive to the server.

**Comment by eregon** [comment]
I see, thanks for looking into it!

**Comment by BanzaiMan** [comment]
I "fixed" by skipping the check altogether. This should at least update the `ruby-head` archive. If there are issues with the resultant archive, please open a new issue.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/3985
