### ISSUE TITLE
APT whitelist request for mariadb

### ISSUE THREAD

**Issue by naderman** [travis-ci/travis-ci#3980]
Needed to move phpBB to container infra https://github.com/phpbb/phpbb/blob/3.1.x/travis/setup-mariadb.sh

**Comment by BanzaiMan** [comment]
Is this addressed by https://github.com/travis-ci/travis-ci/issues/3730?

**Comment by naderman** [comment]
No I meant to install the current 5.5 version.

**Comment by BanzaiMan** [comment]
Where can one find it? It doesn't exist for Precise: http://packages.ubuntu.com/precise/mariadb

**Comment by naderman** [comment]
Oh indeed I entirely missed that we run:
```
MIRROR_DOMAIN='ftp.osuosl.org'
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
sudo add-apt-repository "deb http://$MIRROR_DOMAIN/pub/mariadb/repo/$VERSION/ubuntu $OS_CODENAME main"
sudo apt-get update
```

Looks like OSUOSL are the only ones currently hosting it.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'mariadb' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'mariadb' needs source whitelisting

**Comment by BanzaiMan** [comment]
We've deployed MariaDB addon support (https://github.com/travis-ci/travis-build/pull/303#issuecomment-123393121). Can we close this?

**Comment by naderman** [comment]
Yes, thank you!
