### ISSUE TITLE
Unknown build status

### ISSUE THREAD

**Issue by monolithed** [travis-ci/travis-ci#3984]
![1432917544791](https://cloud.githubusercontent.com/assets/803674/7887533/7082fc98-063a-11e5-9924-1b5f5e5c1129.png)

[![Build Status](https://travis-ci.org/Polyfiller/polyfiller.svg?branch=master)](https://travis-ci.org/Polyfiller/polyfiller)

**Comment by BanzaiMan** [comment]
It appears that you deleted and re-created the repository with the same name. We currently do not handle this situation well, and the badge and the build state were disconnected. I've resolved the name conflict now, and the image should reflect the correct status.

**Comment by qurben** [comment]
We at https://travis-ci.org/Vennik/contextproject have the same issue, our badge hasn't updated for at least a day, while we currently have a passing build.

**Comment by davezuko** [comment]
Been getting the same issue myself for https://travis-ci.org/davezuko/daedalus

Tried disabling the repo in my Travis account then re-enabled it after a few days, re-ran old cancelled builds, re-ran latest/new builds, etc. all with no success. Any chance you could check it out as well? Thanks.

**Comment by BanzaiMan** [comment]
@davezuko Sorry about that. We opened #4024 in general, which we believe is now fixed.
