### ISSUE TITLE
APT whitelist request for lmodern or context

### ISSUE THREAD

**Issue by andrewalker** [travis-ci/travis-ci#3987]
When generating PDF using LaTeX templates in *pandoc*, the 'lmodern.sty' file is required, which is provided by the `lmodern` package. The `context` package depends on `lmodern`, so whitelisting it would also solve the problem.

Right now, I'm using `texlive-full` which downloads hundreds of MB unnecessarily, besides the `lmodern` I need.

**Comment by andrewalker** [comment]
Thank you!

**Comment by davidsan** [comment]
:+1:
