### ISSUE TITLE
travis_wait and error "No output has been received in the last 10 minutes"

### ISSUE THREAD

**Issue by GaetanCambier** [travis-ci/travis-ci#3989]
hello, i test the command "travis_wait"
but i bave always the error : No output has been received in the last 10 minutes

example here : https://travis-ci.org/GaetanCambier/spksrc/jobs/64713529

where is the error ?

**Comment by eagle00789** [comment]
my suggestion is that if you remove  > /dev/null from line 47 in your .travis.yml file, you can see why the script has stalled...

**Comment by BanzaiMan** [comment]
Looks like the suggestion fixed the issue. Let us know if there is anything for us to investigate.
