### ISSUE TITLE
`SSL Error` and  `No compatible version found: lodash` for io.js v2.2.0

### ISSUE THREAD

**Issue by AlexKVal** [travis-ci/travis-ci#3992]
I'm pushing yesterday's 'green' version of `react-bootstrap` with no changes
and getting these errors:
```SSL Error: https://registry.npmjs.org/chai does not support SSL```
```SSL Error: https://registry.npmjs.org/sinon does not support SSL```
```No compatible version found: lodash@'>=3.5.0 <4.0.0'```

I've created dedicated branch for it https://travis-ci.org/AlexKVal/react-bootstrap/builds/64775931

**Comment by stoeffel** [comment]
Same here
https://travis-ci.org/1-liners/module-indexer/jobs/64788541
and here
https://travis-ci.org/jstransformers/test-jstransformer/jobs/64781546
looks like it is only on iojs

**Comment by AlexKVal** [comment]
refs: 
https://github.com/npm/npm/issues/8406
https://github.com/nodejs/io.js/issues/1850

**Comment by taoeffect** [comment]
Same here for lodash and iojs. https://travis-ci.org/okTurtles/dnschain/jobs/64859016

**Comment by AlexKVal** [comment]
It is fixed now.
https://github.com/nodejs/io.js/issues/1850#issuecomment-107303709
