### ISSUE TITLE
Build status unknown persists

### ISSUE THREAD

**Issue by qurben** [travis-ci/travis-ci#3996]
The badge for https://travis-ci.org/Vennik/contextproject has been 'Build status: Unknown' for more than a day, while we currently have had multiple passing builds in that repository.

Is there a way we can fix this?

**Comment by BanzaiMan** [comment]
It appears that you deleted and re-created the repository with the same name. We currently do not handle this situation well, and the badge and the build state were disconnected. I've resolved the name conflict now, and the image should reflect the correct status.

**Comment by shinnn** [comment]
https://travis-ci.org/shinnn/gulp-gh-pages has the same issue.

![image](https://cloud.githubusercontent.com/assets/1131567/7936493/66eb87da-0974-11e5-8e2a-a2bd7f0fd560.png)

And, when I reload the page, it sometimes shows "There are no builds for this repository".

![image](https://cloud.githubusercontent.com/assets/1131567/7936514/9f39fedc-0974-11e5-9039-5398e793cf4e.png)

Note that shinnn/gulp-gh-pages has been transferred from rowoot/gulp-gh-pages at 23 Feb. https://github.com/shinnn/gulp-gh-pages/issues/50

**Comment by BanzaiMan** [comment]
@shinnn Sorry about the issue. I've resolved your conflict, too.

**Comment by shinnn** [comment]
Really quick response and fix! I confirmed the problem has been resolved. Thanks @BanzaiMan and Travis CI!

**Comment by YannBertrand** [comment]
Same problem with https://github.com/FriendsBet/API @BanzaiMan

**Comment by YannBertrand** [comment]
Seem to be corrected now! Thanks!

**Comment by danielstjules** [comment]
@BanzaiMan We're currently seeing the same issue with https://github.com/mochajs/mocha/

**Comment by BanzaiMan** [comment]
@danielstjules Yes. And I resolved the conflict now.

**Comment by danielstjules** [comment]
Perfect, thank you! :)

**Comment by drisso** [comment]
I seem to experience the same issue in https://travis-ci.org/drisso/RUVSeq
I did rename the repo and then renamed it back to the original name. I guess this might have created a similar conflict?

**Comment by BanzaiMan** [comment]
@drisso Sorry for the issue. I resolved your conflict.

**Comment by drisso** [comment]
Thank you @BanzaiMan!

**Comment by Haehnchen** [comment]
@BanzaiMan is this still an overall issue? also having problems here: https://travis-ci.org/Haehnchen/idea-php-symfony2-plugin

**Comment by BanzaiMan** [comment]
@Haehnchen Yes. I've resolved yours, too.

**Comment by ajschumacher** [comment]
Hi @BanzaiMan! Maybe the same thing is happening here? https://travis-ci.org/ajschumacher/mergic Is this something I could fix myself? Thanks!

**Comment by BanzaiMan** [comment]
@ajschumacher There was a conflict with yours, too. I resolved it, but the correct repository doesn't have any build, so it still shows "unknown".

**Comment by ajschumacher** [comment]
Works like a charm! Thanks @BanzaiMan!

**Comment by iamcdonald** [comment]
Hi @BanzaiMan, I feel as though I'm just piling on here but I also seem to be having the same issue (https://travis-ci.org/iamcdonald/nadda). If there is anything I can do to fix this myself I'll more than happily do it just point me in the right direction.

**Comment by TizianoPerrucci** [comment]
Same problem here https://travis-ci.org/StarterSquad/prudentia , can I do anything? Thx

**Comment by ifsnop** [comment]
After deleting, unsetting and creating again travis-ci webooks from github/travis-ci, I still don't get a build "passed" banner in my project, I'm still stuck with the "unknown" banner.

https://travis-ci.org/ifsnop/mysqldump-php

Is there anything someone can do to fix it?

Thanks in advance!

**Comment by ryanpetrello** [comment]
I seem to be having this problem with a few project of my own as well:

https://travis-ci.org/ryanpetrello/pecan
https://travis-ci.org/pecan/pecan

**Comment by joshk** [comment]
Hi @ryanpetrello 

https://travis-ci.org/ryanpetrello/pecan is fine, I see the status correctly

but https://travis-ci.org/pecan/pecan is marked as 'unknown' as the only builds for that repo have been Pull Requests. Once you have a build to a branch then the status should be reported correctly.

**Comment by carlosrabelo** [comment]
Same problem here https://travis-ci.org/carlosrabelo/mars

**Comment by joshk** [comment]
@carlosrabelo everything looks to be working now as you have just run your first build on the master branch. Happy testing.

**Comment by victorwestmann** [comment]
Sorry to bother but I believe we're suffering the same issues on the project https://github.com/coursera-dl/coursera-dl

**Comment by guerrero** [comment]
Hi guys, same problem here https://travis-ci.org/guerrero/stylint-loader. But I haven't deleted and re-created this repo or migrated it from another user or organization.

Thanks in advance!

**Comment by RNAer** [comment]
same situation here: https://travis-ci.org/biocore/micronota

**Comment by daneah** [comment]
I've got the same problem with https://github.com/working-bikes/working-bikes presently. I recently migrated this to an organization (I thought I did so before integrating Travis CI, but I could be mistaken).

**Comment by daneah** [comment]
@travis-ci are you able to provide support for these cases? Is there a workaround I can perform on my end?

**Comment by BanzaiMan** [comment]
@daneah https://travis-ci.org/working-bikes/working-bikes/builds shows green to me. Is that not what you want?
![builds_-_working-bikes_working-bikes_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/10913537/a67703f4-824e-11e5-88d6-236ecae4c7b9.png)

**Comment by daneah** [comment]
@BanzaiMan I was ultimately able to resolve this by forcing a few empty commits and pushing them. I was unable to select the `master` branch for the badge until I did so, probably because all previous builds had been based on pull requests. Thanks!

**Comment by Mingling94** [comment]
https://github.com/NebulousLabs/Sia-UI has the same issue

**Comment by danyaljj** [comment]
Same issue here! 
https://travis-ci.com/IllinoisCogComp/lbjava
<img width="467" alt="lbjava" src="https://cloud.githubusercontent.com/assets/2441454/11541414/c676cc1a-98f7-11e5-9796-0529ff10f61e.png">

**Comment by BanzaiMan** [comment]
@danyaljj Yours should be fixed now, since the "master" branch has a successful push build. Only push builds are considered for determining the status.

**Comment by mathiasbynens** [comment]
Same problem here: https://github.com/tibiamaps/tibia-map-data ![](https://api.travis-ci.org/tibiamaps/tibia-map-data.svg?branch=master)

**Comment by mathiasbynens** [comment]
Ignore my previous message, it was my bad. I should’ve used `?branch=gh-pages` instead of `?branch=master`.

**Comment by Akaryatrh** [comment]
HI there,

@BanzaiMan I have the same problem with this repository : https://github.com/Akaryatrh/svgAssets
And last build is all green : https://travis-ci.org/Akaryatrh/svgAssets

Moreover, only the master branch can be selected in the badge dropdown, is that an expected behavior ?

Thx for support!

**Comment by BanzaiMan** [comment]
@Akaryatrh The badge reflects push build statuses, but https://travis-ci.org/Akaryatrh/svgAssets/requests shows that push builds are disabled.

**Comment by Akaryatrh** [comment]
@BanzaiMan I activated push builds, badge is now green :) Thx for answer!

**Comment by ChristopherKing42** [comment]
@BanzaiMan Same problem here it appears https://travis-ci.org/ChristopherKing42/skynet

**Comment by ChristopherKing42** [comment]
@BanzaiMan Nvm, its fixed now.

**Comment by marhyorh** [comment]
I'm also having the same issue https://travis-ci.org/marhyorh/stackPie/requests. Thanks

**Comment by ilp416** [comment]
I'm sorry. I have same problem https://travis-ci.org/ilp416/other_joins
I have re-created repository.

**Comment by BanzaiMan** [comment]
@marhyorh Your repository does not contain `.travis.yml`. See https://raw.githubusercontent.com/marhyorh/stackPie/master/%20.travis.yml, there is a whitespace before '`.travis.yml`'.

**Comment by BanzaiMan** [comment]
@ilp416 Your repo's hook was invalid. I reset it. Please push a new commit to test.

**Comment by ilp416** [comment]
@BanzaiMan Didn't run. https://travis-ci.org/ilp416/other_joins

**Comment by marhyorh** [comment]
You're right @BanzaiMan. Thanks! I didn't notice that, it's now passing.

**Comment by DaikiMaekawa** [comment]
I got the same issue here. https://github.com/DaikiMaekawa/akihabara_map_for_geeks
only gh-pages branch isn't detected.

**Comment by DaikiMaekawa** [comment]
@BanzaiMan can you fix the problem?

**Comment by andreamazza89** [comment]
https://github.com/andreamazza89/airport_challenge

I think I have the same problem where the badge shows status as `unknown`, although the latest build passed. I wonder if you could help @BanzaiMan ? 

Many thanks

**Comment by BanzaiMan** [comment]
@DaikiMaekawa We've never run a build for the `gh-pages` branch. https://travis-ci.org/DaikiMaekawa/akihabara_maps/branches (https://docs.travis-ci.com/user/customizing-the-build#Whitelisting-or-blacklisting-branches)

@andreamazza89 [Your URL](https://raw.githubusercontent.com/andreamazza89/airport_challenge/54984e591dc7d729ddc6fdf91afd6270980086eb/README.md) is wrong. The correct one is https://api.travis-ci.org/andreamazza89/airport_challenge.svg?branch=master (Drop `.png` at the end.)

**Comment by DaikiMaekawa** [comment]
@BanzaiMan oh, I see. Is there something way for build testing Github Pages with Travis?

**Comment by BanzaiMan** [comment]
@DaikiMaekawa Yes. Please whitelist the `gh-pages` branch. See the documentation.

**Comment by andreamazza89** [comment]
@BanzaiMan Thank you very much!

**Comment by DaikiMaekawa** [comment]
@BanzaiMan It works. Thanks!

**Comment by TMandzu** [comment]
https://travis-ci.org/TMandzu/REKLAPP-server

I have the same problem. I created repository on github, then deleted and created again. Please help!

**Comment by rcorty** [comment]
I made the same mistake -- made a new repo with the same name (ironically, I remade it because I thought it would be easier to start with travis on an empty project and build up rather than add it to my existing big project).  The project is here:  https://travis-ci.org/rcorty/CortyKit

**Comment by msmfsd** [comment]
Same here for both https://travis-ci.org/msmfsd/codefolio-api & https://travis-ci.org/msmfsd/codefolio

I made private repos public. Can you help please?

Many thanks

**Comment by steview** [comment]
Is there a way of resolving this ourselves yet?

My GH repo is private.

Thanks.

**Comment by leonyipwh** [comment]
@BanzaiMan pls fix https://travis-ci.org/leonyipwh/generator-angular-coffee-sass

**Comment by BanzaiMan** [comment]
@leonyipwh There is no build for that repository.

**Comment by mirzap** [comment]
@BanzaiMan I have the same issue:

https://travis-ci.org/bosnadev/ronin

**Comment by BanzaiMan** [comment]
@mirzap You need a push build. https://github.com/travis-ci/travis-ci/issues/3996#issuecomment-161459691

**Comment by mralexgray** [comment]
@BanzaiMan what is a "push build"?

**Comment by BanzaiMan** [comment]
@mralexgray Builds initiated by git pushes (as opposed to PR requests).

**Comment by mralexgray** [comment]
@BanzaiMan  OK, i thought so.. in my case... i just had to wait a few minutes..  for the build status to update...

**Comment by mauipipe** [comment]
@BanzaiMan got the same issue with push build activated https://travis-ci.org/mauipipe/api_utils.  Could you please address me how to fix it?

**Comment by warapitiya** [comment]
Same here, Can you fix this also. https://travis-ci.org/warapitiya/gulp-yarn

**Comment by MengJueM** [comment]
https://travis-ci.org/mengjues/mengjues.github.io/

It seems that I have to raise the ticket here?

**Comment by brittdawn** [comment]
I have an issue with this as well: https://travis-ci.org/alexa-skillz/alexa-interview-overflow Would appreciate any help!

**Comment by BanzaiMan** [comment]
@MengJueM The badge on https://travis-ci.org/mengjues/mengjues.github.io/ points to the `master` branch builds, but that branch has no build. https://travis-ci.org/mengjues/mengjues.github.io/branches

@brittdawn There is no push builds for your repo. https://travis-ci.org/alexa-skillz/alexa-interview-overflow/builds

**Comment by Ohen** [comment]
@BanzaiMan Same issue here! can you fix the problem?
https://github.com/spearhead-ea/mongoose-transaction-plugin
https://travis-ci.org/spearhead-ea/mongoose-transaction-plugin/builds

**Comment by BanzaiMan** [comment]
@Ohen Your default branch is `master`, which doesn't have any build on Travis CI.

**Comment by Ohen** [comment]
@BanzaiMan 
![image](https://cloud.githubusercontent.com/assets/10244446/22276456/1107c2f8-e2f7-11e6-9199-292e566497eb.png)

make a travis CI build for master, checking for "https://travis-ci.org/spearhead-ea/mongoose-transaction-plugin/builds/195045012"

**Comment by BanzaiMan** [comment]
@Ohen Check your browser cache. I see the passing badge now.

**Comment by Ohen** [comment]
@BanzaiMan  Seem to be corrected now! Thanks!

**Comment by andela-gike** [comment]
@BanzaiMan I am also having issues with my Badge it is passing but the badge is showing build unknown

**Comment by Benjamin28** [comment]
I'm having the same issue with build status unknown after deleting and remaking the repository.

https://travis-ci.com/cs373c-spring-2017/collatz-Benjamin28

Is there a way I can fix this on my own?

**Comment by andela-cofor** [comment]
I have an issue Travis shows build passed but badge says build unknown

**Comment by andela-oadeniran** [comment]
@BanzaiMan I have the same issue. build unknown badge while the build exited with 0.

**Comment by BanzaiMan** [comment]
@andela-gike @andela-cofor @andela-oadeniran I can't guess which repository you are having problems with. Please indicate which repositories we should look into.

In general, though:

1. Check the push build status on the default branch. PR builds and builds on non-default branches don't count.
1. Try force reloading. Sometimes browser has stale cache.

Thanks.

**Comment by omidfi** [comment]
Is it the same problem I'm having here? 

https://travis-ci.org/omidfi/moro/builds/210089147

**Comment by andela-cofor** [comment]
Simple logic the markdown is showing for master branch i just checked for
your devops/travis
https://travis-ci.org/omidfi/moro.svg?branch=devops/travis copy and paste
and you'll see this one passes

Chinedu Ofor / Andela.com
<http://andela.com/?utm_source=andela&utm_medium=email&utm_campaign=signature>
Software Developer / 070.302.96.746 / @Andela <http://bit.ly/andelatwitter>
We're hiring! Check out our careers page. <http://bit.ly/andelacareers>

**Comment by mhh1422** [comment]
Does the problem still exist? The badge is stuck on "Unknown" despite the status of the build.

https://github.com/itvisionsy/laravel-modules

**Comment by SketchK** [comment]
@BanzaiMan I deleted and re-created the repository with the same name twice, so the building state seems wrong now, Could you fix my conflict ? Thank you!
https://travis-ci.org/SketchK/SketchK.github.io/jobs/215220304

By the way, Could you delete the build history of the repo both i deleted and re-created ?  because some important informations can be found in the log.

**Comment by LookOnTheBrightSide** [comment]
@BanzaiMan Hi. We are trying to fix the build unknown issue, could you please help us out?
https://travis-ci.com/charlawl/DublinBikeApp

**Comment by lilrom13** [comment]
@BanzaiMan same for me, could you please fix the problem ?
[https://travis-ci.org/wefaves/client](url)
Thank you !

**Comment by naharrison** [comment]
@BanzaiMan I am also having this issue due to a deleted and re-created repository. Could you please resolve the issue for the following repository?
https://github.com/JeffersonLab/clas12-offline-software
https://travis-ci.org/JeffersonLab/clas12-offline-software
Jefferson Lab's CLAS Collaboration thanks you!

**Comment by BanzaiMan** [comment]
@LookOnTheBrightSide @lilrom13 @naharrison I check your repositories, and they are showing the correct status to me. Could you double check?

**Comment by LookOnTheBrightSide** [comment]
@BanzaiMan it worked after about a day. Apologies for not reporting back. Thanks for looking!

**Comment by naharrison** [comment]
@BanzaiMan Thanks for your reply. If you go to this link: https://github.com/JeffersonLab/clas12-offline-software and scroll down to view the README.md file, the top of the file has a button that links to the Travis page. This button has said "build unknown" for quite a few weeks now despite the build being successful.

**Comment by BanzaiMan** [comment]
@naharrison Your image link in [README.md](https://github.com/JeffersonLab/clas12-offline-software/blob/ce5acbaffff47e877d36e091ff82345bd42450da/README.md) is https://travis-ci.org/JeffersonLab/class12-offline-software.svg?branch=master, while it should be https://travis-ci.org/JeffersonLab/clas12-offline-software.svg?branch=master. The repository name has only one `s` in `class12`.

**Comment by naharrison** [comment]
@BanzaiMan Woops, that's an embarrassing bug. Thanks so much for pointing it out! It is working now.

**Comment by markosh82** [comment]
Same problem here, although I'm just a beginner, 2 tests passed ok but is stays build/unknown

**Comment by TPeterW** [comment]
This is the same thing here, branch updates enabled, both passed, somehow still unknown.
https://travis-ci.com/dartmouth-cs52-17S/project-api-dartcourses

**Comment by jattoabdul** [comment]
@BanzaiMan am having the same issue, please help 
https://travis-ci.org/jattoabdul/andela-bootcamp-postit

**Comment by BanzaiMan** [comment]
@jattoabdul Not sure where you are seeing this. https://api.travis-ci.org/jattoabdul/andela-bootcamp-postit.svg shows green for me.

**Comment by jattoabdul** [comment]
sorry i needed to hard refresh my browser. thanks @BanzaiMan

**Comment by tonyjin** [comment]
@BanzaiMan not sure if this is a similar situation to the deleted/recreated repo, but I recently made this repository public and the build status remains at 'build: unknown'

https://travis-ci.com/box/box-content-preview
https://github.com/box/box-content-preview

Thanks!

**Comment by BanzaiMan** [comment]
@tonyjin Your README is pointing to shield.io. I don't know how that services works. https://raw.githubusercontent.com/box/box-content-preview/271cbbb6c27d7b08b0258751e95522148e3d6dff/README.md

**Comment by tonyjin** [comment]
I assume they're just checking the Travis API, which is also returning build: unknown -
 https://api.travis-ci.org/box/box-content-preview.svg

**Comment by BanzaiMan** [comment]
@tonyjin There are no public builds for this repository as of now. https://travis-ci.org/box/box-content-preview/builds

**Comment by tonyjin** [comment]
Ah thanks - figured it out. Forgot Travis separates private and public repos so I had to re-set it up once I made the repository public. Also needed to follow the steps described here: https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda in order to build PRs and merges to master.

**Comment by cjmash** [comment]
all my test are running but the budge build is still unkown wht ???
https://github.com/cjmash/BucketList/blob/develop/README.md

**Comment by shah-nishant** [comment]
@BanzaiMan Facing same issue in my private repo. How do I solve this?

**Comment by DreamingDevs** [comment]
@BanzaiMan Same issue here as well. https://travis-ci.org/AutomobileServiceCenter/AutomobileServiceCenter.Core

**Comment by omerlh** [comment]
Also have the issue [here](https://travis-ci.org/Soluto/wordpress-plugin-tests-template)

**Comment by Eddyosos** [comment]
@BanzaiMan same https://travis-ci.org/fabrica-ufg-2017-2/portal-da-transparencia

**Comment by BanzaiMan** [comment]
@Eddyosos You have no push builds. https://travis-ci.org/fabrica-ufg-2017-2/portal-da-transparencia/builds

**Comment by Eddyosos** [comment]
@BanzaiMan I actually had 24 builds before....
Manually triggering the build corrected the badge.

**Comment by rob-nash** [comment]
Hi. I also have the same issue [here](https://travis-ci.org/rob-nash/Rotary).

**Comment by Coubiac** [comment]
Hello, i have the same issue [here](https://travis-ci.org/Coubiac/clubalfa44)

**Comment by kabasakalis** [comment]
I have the same issue for 
https://github.com/kabasakalis/mymusic-rails-api,
https://github.com/kabasakalis/ruby-maze
and
https://github.com/kabasakalis/elixir-maze

I will appreciate your help.

**Comment by dirmeier** [comment]
+1

**Comment by Borisbudini** [comment]
Same issue here: https://github.com/uracreative/identihub/tree/dev

**Comment by BanzaiMan** [comment]
@rob-nash Seems OK to me.

@kabasakalis Are these private repos?

@Borisbudini https://travis-ci.org/uracreative/identihub.svg?branch=dev shows green for me.

**Comment by Borisbudini** [comment]
@kabasakalis seems to be fixed over here as well now! Thanks!

**Comment by kabasakalis** [comment]
@BanzaiMan Actually I deleted them and uploaded them again with a slightly different name, since they did'nt have any stars or activity anyway.

**Comment by ozerovandrei** [comment]
@BanzaiMan hello. Can you please also fix "build unknown" status for the repo: https://github.com/selectel/go-selvpcclient ?
It has been renamed from the selectel/go-selvpc, so I think that caused this issue.

**Comment by BanzaiMan** [comment]
@ozerovandrei https://travis-ci.org/selectel/go-selvpcclient/builds shows no build on the `master` branch.

**Comment by ozerovandrei** [comment]
@BanzaiMan you're right. But it still shows "build|unknown" for the badge: [go-selvpcclient.svg?branch=master|https://api.travis-ci.org/selectel/go-selvpcclient.svg?branch=master] for some reason.

**Comment by BanzaiMan** [comment]
That's still the `master` branch. Please specify the branch of your interest.

![](https://api.travis-ci.org/selectel/go-selvpcclient.svg?branch=resell-v2-client)

**Comment by ozerovandrei** [comment]
@BanzaiMan oh my bad. Thank you 😄

**Comment by diegoreymendez** [comment]
I'm seeing the same problem in our branch that integrates the Travis status badge: https://github.com/wordpress-mobile/AztecEditor-iOS/tree/try/update-readme.md

**Comment by BanzaiMan** [comment]
I'm locking this issue. I've addressed many common misunderstanding of this issue, and we have addressed those in our document as well. https://docs.travis-ci.com/user/status-images/#Travis-CI-pages-show-the-default-branch%E2%80%99s-result
