### ISSUE TITLE
boto and simple blocked by --allow-hosts

### ISSUE THREAD

**Issue by andrewgaul** [travis-ci/travis-ci#4003]
s3proxy integration tests recently started failing with:

```
Installed /home/travis/build/andrewgaul/s3proxy/s3-tests
Processing dependencies for s3tests==0.0.1
Searching for boto>=2.0b4
Link to http://pypi.python.org/simple/boto/ ***BLOCKED*** by --allow-hosts
Couldn't find index page for 'boto' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Link to http://pypi.python.org/simple/ ***BLOCKED*** by --allow-hosts
No local packages or download links found for boto>=2.0b4
error: Could not find suitable distribution for Requirement.parse('boto>=2.0b4')
```

https://travis-ci.org/andrewgaul/s3proxy/builds/64713859

Previously this succeeded:

https://travis-ci.org/andrewgaul/s3proxy/builds/62490610

Did some Travis configuration change for boto and simple?  These tests pass for me locally.

**Comment by BanzaiMan** [comment]
It seems that many dependencies have changed between the two builds. I noticed `setuptools` went from 15.2 to 17.0. Not clear if this is the only thing that changed, but if you try building this application from scratch, it would fail for you, too.

I'm sorry, but I can't help much beyond that, as my understanding of Python is not strong. If you want to track the issue down, we are happy to provide you with a debug VM (which would run on the standard infrastructure but close enough for troubleshooting issues like this one).

**Comment by andrewgaul** [comment]
@BanzaiMan These tests succeed for me locally with setuptools 17.0 so I am not sure what has gone wrong here.  I would live to fix this so if you can provide me a debug VM I can try to triage this further.

**Comment by BanzaiMan** [comment]
Sorry to hear that. Please email support@travis-ci.com, please.

**Comment by BanzaiMan** [comment]
Is this still an issue? Recent builds are passing.

**Comment by andrewgaul** [comment]
Recent builds pass because I disabled the s3-tests portion of the build.  Compare with a build re-enabling the tests which have the same blocked errors:

https://travis-ci.org/andrewgaul/s3proxy/builds/70101456

**Comment by andrewgaul** [comment]
Magically fixed by: https://github.com/ceph/s3-tests/pull/66
