### ISSUE TITLE
Invalid nvm versions 0.8, 0.10, 0.12

### ISSUE THREAD

**Issue by danielgtaylor** [travis-ci/travis-ci#4005]
Any idea what's going on here?

https://travis-ci.org/danielgtaylor/nesh/jobs/65022134

It seems that `iojs` works:

https://travis-ci.org/danielgtaylor/nesh/jobs/65022136

**Comment by anthonator** [comment]
Seeing the same issue.

https://travis-ci.org/anthonator/pwny/builds/65024706

**Comment by BanzaiMan** [comment]
For a time, http://nodejs.org/dis was unreachable, and this resulted in this. It should be back now.
