### ISSUE TITLE
APT whitelist for python-tz

### ISSUE THREAD

**Issue by charbeljc** [travis-ci/travis-ci#4007]
Timezones for python, used by Odoo Community Addons (https://github.com/OCA/)

**Comment by BanzaiMan** [comment]
If you are using this on a Python image, you will have to install it with `pip` or some other way. The system package will be found only by the system Python.

**Comment by charbeljc** [comment]
Hi @BanzaiMan thank you for your answer, I was a bit young in this sort of thing and were trying to make our travis builds faster but pytz is obvioulsy not the culprit, so we can close this issue, if no body need this.
