### ISSUE TITLE
"No space left on device" error during build

### ISSUE THREAD

**Issue by onyb** [travis-ci/travis-ci#4008]
I gathered that this is a known problem which has been fixed before, but for some reason I am getting it during the build. Here is the [log](https://travis-ci.org/vgvassilev/cling/jobs/64740877), and the [travis.yml](https://github.com/vgvassilev/cling/blob/FixMacOS/.travis.yml) for reference.

Though it is a Debug+Asserts build, I don't think that is the culprit. The problem only came up recently after we moved to container based infrastructure by adding `sudo: false`.

**Comment by enigmagroup** [comment]
Same here: https://travis-ci.org/enigmagroup/enigmabox-openwrt/builds/66330613#L1840

We need moar space...

**Comment by roidrage** [comment]
Are you still experiencing these issues?

**Comment by enigmagroup** [comment]
Well I can't tell, the build is failing, but...

```
The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

The build has been terminated.
```

**Comment by joshk** [comment]
Can you look at reducing you log output? That way we can confirm if the issue is still, well, an issue :)

**Comment by enigmagroup** [comment]
Well I ran the build with the reduced output: https://travis-ci.org/enigmagroup/enigmabox-openwrt/builds/72422904 - it says: "Please re-run make with -j1 V=s to see what's going on"... This is a deadlock situation.

**Comment by joshk** [comment]
Ok, is the deadlock issue a Travis issue?

**Comment by enigmagroup** [comment]
Is there a way to increase the log size of travis to more than 4 MB?

**Comment by joshk** [comment]
Not at the moment sorry, this limit is set for everyone.

**Comment by enigmagroup** [comment]
Ok. Then I have no chance for investigating the exact error at the moment. You can close this issue.

**Comment by meatballhat** [comment]
I'm closing this out for now.  Please yell if you are still experiencing this problem!  :heart:

**Comment by digitalentity** [comment]
Still having the issue: https://travis-ci.org/iNavFlight/inav/jobs/285091312

**Comment by HarryFengYX** [comment]
Me too, why are all unanswered bugs closed?
