### ISSUE TITLE
Caching feature never executes in "osx" and GCE environments

### ISSUE THREAD

**Issue by mislav** [travis-ci/travis-ci#4011]
We've recently enabled "osx" builds in `github/hub`. The [travis.yml contains](https://github.com/github/hub/blob/4ea62ada5b4c56257d6383e4c02e21f5c6ac253d/.travis.yml#L15-L17):

```yml
cache:
  directories:
    - vendor/bundle
```

However, in "osx" environment [there is no attempt](https://travis-ci.org/github/hub/jobs/65079463) to save or restore the cache. There is no "Setting up build cache" in the output. This is consistent through multiple builds. Meanwhile, the "linux" environment does perform caching as usual.

**Comment by jacebrowning** [comment]
In all of my `osx_image: beta-xcode6.3` environments, caching is still not working. Near the start of builds:

```
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
$ Installing caching utilities
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p643'.
attempting to download cache archive
fetching <redacted>/cache--rvm-default--gemfile-Gemfile.tgz
fetching <redacted>/cache--rvm-default--gemfile-Gemfile.tgz
could not download cache
adding /Users/travis/build/<redacted>/Pods to cache
```

However, near the end of builds:

```
store build cache
$ bundle clean
Cleaning all the gems on your system is dangerous! If you're sure you want to remove every system gem not in this bundle, run `bundle clean --force`.
changes detected, packing new archive
uploading archive
```

It appears that cache archives are uploaded, but fail to be unpacked when builds start.

**Comment by joshk** [comment]
Hi @jacebrowning 

This looks to be a different issue than the one Mislav was reporting. Can you please email support@travis-ci.com and we can look further into this.

Thanks a bundle

**Comment by jacebrowning** [comment]
@joshk Thanks. I'll submit this as a separate issue if they direct me to.

**Comment by BanzaiMan** [comment]
@jacebrowning Hello. We have an issue with the Mac caching not working on private repositories, and we should investigate further.

@mislav: caching on the Mac for public repositories is not yet available. We want to enable it, though; so we will keep this issue open.

**Comment by BanzaiMan** [comment]
@jacebrowning I should clarify. Your case with the private repository is slightly different. Caching is working, but it yields some warning messages:

```
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin' is not at first place,

         usually this is caused by shell initialization files - check them for 'PATH=...' entries,

         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',

         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p643'.
```

**Comment by BanzaiMan** [comment]
I opened https://github.com/travis-ci/travis-ci/issues/4207.

**Comment by sheerun** [comment]
We experienced the same on Travis Pro we're evaluating. It's a bummer.

**Comment by BanzaiMan** [comment]
@sheerun Caching should work on the private repos. If you haven't done so, please email support@travis-ci.com with details. Thank you.

**Comment by sheerun** [comment]
@BanzaiMan I already did 10 days ago, and they sent me here :) It doesn't.

**Comment by develar** [comment]
I want to install wine/mono on OS X but without caching it took 48 minutes instead of 2 minutes...

**Comment by quanglam2807** [comment]
@develar I face the same issue with wine. Have you found a solution?

**Comment by develar** [comment]
@quanglam2807 No. I found possible solution — https://github.com/octoblu/gateblu-ui-build/blob/master/.travis.yml (custom cache on amazon s3), but not yet tried to use it. Decided to use linux for now.

**Comment by localheinz** [comment]
![maxresdefault](https://cloud.githubusercontent.com/assets/605483/13179887/62d3026a-d726-11e5-9448-59e405bbc792.jpg)

**Comment by kenorb** [comment]
I've the same for Ubuntu build at [#122079627](https://travis-ci.org/EA31337/EA31337-Lite-Sets/builds/122079627):

```
attempting to download cache archive
fetching ci/cache.tgz
fetching ci/cache.tbz
fetching master/cache.tgz
fetching master/cache.tbz
could not download cache
adding /home/travis/.wine to cache
```

My [`.travis.yml`](https://github.com/EA31337/EA31337-Lite-Sets/blob/5516ecefe52764273abab55606d97415f875dfb6/.travis.yml):

```
cache:
  apt: true
  pip: true
  directories:
  - "$HOME/.wine"
```

**Comment by BanzaiMan** [comment]
@kenorb GCE doesn't have caching feature deployed yet. We are working on that.

**Comment by BanzaiMan** [comment]
https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone

It's available now!
