### ISSUE TITLE
Build is not starting after receiving requests.

### ISSUE THREAD

**Issue by SachinAgarwal1337** [travis-ci/travis-ci#4014]
After receiving requests (as per requests log) the build is always in wait state. Not starting. Timer also do not start. It is just in the yellow state always. Even after restarting the build, its the same. 

here : https://travis-ci.org/SachinAgarwal1337/Php-reflection-deflector

**Comment by BanzaiMan** [comment]
It looks like this build is in a strange state; it runs, but something is sending cancel message.

**Comment by SachinAgarwal1337** [comment]
How should I solve this?

**Comment by SachinAgarwal1337** [comment]
My tests work fine on local machine. And my .travis.yml file is also validated.
```
language: php
php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --dev --prefer-source --no-interaction

script: vendor/bin/phpunit --coverage-text
```

**Comment by BanzaiMan** [comment]
It's not your tests, but our backend. Can you try canceling right now, and see if it falls into a consistent state, from which you can run it again?

**Comment by SachinAgarwal1337** [comment]
all builds are canceled. they are in stop state now. Black state.

**Comment by SachinAgarwal1337** [comment]
If I try to restart, its the same thing again.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/SachinAgarwal1337/Php-reflection-deflector/builds/65239144 finished, though. Could you try restarting another?

**Comment by SachinAgarwal1337** [comment]
other builds are starting, but as the notice says, there is delay in starting the tests.

**Comment by BanzaiMan** [comment]
Hmm. Perhaps I misunderstood, then. Besides the delay in start, is there any issue to look at regarding this ticket?

**Comment by SachinAgarwal1337** [comment]
Yeah one small prob, The build flag/tag shows `canceled` for develop branch even though it passes. But on master branch it shows `passing`.

And on travis page it is always `build canceled` 
https://travis-ci.org/SachinAgarwal1337/Php-reflection-deflector

**Comment by BanzaiMan** [comment]
@SachinAgarwal1337 Sorry, but that's a separate problem. We are aware of that, and working on a fix. See #4024.

I'm closing this, since the original problem is resolved.

**Comment by SachinAgarwal1337** [comment]
Oh great. Thanks for helping me out :)
