### ISSUE TITLE
Consistent "errored" runs on apt-get since the last week or so

### ISSUE THREAD

**Issue by SimonKagstrom** [travis-ci/travis-ci#4015]
All the latest builds on multiple Linux projects have failed for me. I get errors in the apt-get update stage early on, so it seems completely unrelated to my commits. An example:

  https://travis-ci.org/SimonKagstrom/emilpro/builds/65225908

I've tried ignoring apt-get update failures, but it gets stuck in the next step instead then.

Seems to have started about a week ago or so.

**Comment by meatballhat** [comment]
@SimonKagstrom are you able to switch to `apt-get ... -y` (minus `-qq`) or pipe the logs off somewhere and `cat` them in an `after_failure:` block so we can see the details of the failure?

**Comment by SimonKagstrom** [comment]
I've committed a change to apt-get update -y, which is being built here:

https://travis-ci.org/SimonKagstrom/emilpro/builds/65250214

It hasn't started yet though because of some other infrastructure issue.

**Comment by BanzaiMan** [comment]
Looks like we need to have this run a few times before we get the segmentation fault again. :-(

**Comment by SimonKagstrom** [comment]
OK, scary. My later commits seem to work now.

I'll get back if I manage to trigger it. I've had many failures (i.e., every push) in multiple projects the last week though, so it was very easy to trigger before.

**Comment by roidrage** [comment]
Are you still experiencing these issues?

**Comment by SimonKagstrom** [comment]
No, I haven't seen them since early june. Feel free to close - I'll reopen if I happen to trigger this again.

**Comment by roidrage** [comment]
Thanks for the quick follow-up!
