### ISSUE TITLE
Status image is incorrect

### ISSUE THREAD

**Issue by swarmer** [travis-ci/travis-ci#4019]
The status image in my project says `failing` even though the latest builds are all green:
[https://travis-ci.org/swarmer/bsuapp/builds](https://travis-ci.org/swarmer/bsuapp/builds)

**Comment by drogus** [comment]
Sorry for that, changes in the DB revealed a bug in our API that resulted in the wrong images being served. It should be fixed now, but please let us know if this happens for any other repo.
