### ISSUE TITLE
Wrong image for build status

### ISSUE THREAD

**Issue by Revolucent** [travis-ci/travis-ci#4020]
My build is passing and green, but the wrong status image is showing:

https://travis-ci.org/Prosumma/CoreDataQueryInterface

Perhaps I'm doing something wrong, but I researched extensively via StackOverflow and Google before submitting this issue.

**Comment by FractalizeR** [comment]
![screen shot 2015-06-04 at 10 13 11](https://cloud.githubusercontent.com/assets/318489/7978820/59050e3c-0aa2-11e5-9c4c-0ac68ccf15ca.png)

I have the same problem. Our badge is always "Build error", but overall build status is green.

**Comment by drogus** [comment]
Sorry for that, changes in the DB revealed a bug in our API that resulted in the wrong images being served. It should be fixed now, but please let us know if this happens for any other repo.

**Comment by FractalizeR** [comment]
Fixed for me, thanks!
