### ISSUE TITLE
Running out of disk space

### ISSUE THREAD

**Issue by petrus-jvrensburg** [travis-ci/travis-ci#4026]
I'm seeing `No space left on device` when populating a postgres db from a dump file. It's on the `unhaggle/unhaggle` project.

**Comment by BanzaiMan** [comment]
How big are your seed data?

**Comment by petrus-jvrensburg** [comment]
the dump is 3.6 Gb

**Comment by petrus-jvrensburg** [comment]
... and there's roughly another 1 Gb's worth of other data files

**Comment by BanzaiMan** [comment]
It is not clear how much disk space each VM can use. Could you try reducing the seed test data?

**Comment by petrus-jvrensburg** [comment]
Let me see what I can do.

 But still, if there's no clear limit, how much would I have to reduce it in order for the tests to run reliably?

**Comment by petrus-jvrensburg** [comment]
Okay, so I've managed to save a bunch of disk space, but I'm still having issues. Can I have some guidance as to how much is too much?

**Comment by BanzaiMan** [comment]
@petrus-jvrensburg Sorry to hear about the continued problem. I wonder if a debug VM would help here. Though the debug VM may not have the exact disk space allotment as the ones you are having problems with, it may help you with getting an estimate on the constraints.

Does it sound good? If so, please email support@travis-ci.com.

**Comment by petrus-jvrensburg** [comment]
Sure, let me give it a shot. Thanks.

**Comment by roidrage** [comment]
Are you still experiencing these issues?

**Comment by petrus-jvrensburg** [comment]
No, that's been sorted, thanks. Let me close the issue.

**Comment by meets2tarun** [comment]
Issue still persists and continued after several restarts of the build
https://travis-ci.org/xeon-zolt/meilix/builds/255183213#L952
