### ISSUE TITLE
% successful sparkline

### ISSUE THREAD

**Issue by drbrain** [travis-ci/travis-ci#403]
The travis-ci page should have a sparkline with the % of successful builds over the last N builds in a tasteful location.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by Arthaey** [comment]
I've written a small project that creates tiny spakline-esque bar charts showing build histories, in case that helps anyone here: https://github.com/Arthaey/travis-build-history-badges
