### ISSUE TITLE
APT source whitelist request for ppa:coolwanglu/pdf2htmlex

### ISSUE THREAD

**Issue by spect88** [travis-ci/travis-ci#4033]
Project homepage: https://github.com/coolwanglu/pdf2htmlEX

```
deb http://ppa.launchpad.net/coolwanglu/pdf2htmlex/ubuntu trusty main
```

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:coolwanglu/pdf2htmlex' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:coolwanglu/pdf2htmlex' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/33.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
