### ISSUE TITLE
Node.js directory caching

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#4035]
On http://docs.travis-ci.com/user/caching we should mention that for node.js one needs to workaround the facts that we're currently using mtimes for cache freshness detection, and node.js is touching them. 

Apparently npm 2.8.x now touches entire packages. 

This is how one can work around this:

```
before_cache:
  - rm -rf ./node_modules/fly-components/
```

**Comment by alisdair** [comment]
(Where `fly-components` is the name of your npm package)

**Comment by BanzaiMan** [comment]
The checksum-based file change detection has been deployed. https://github.com/travis-ci/casher/releases/tag/production-2015-07-07 (I've tested a simple Node.js repo, and it worked.)

I'm closing this, but if you see problems, do let us know.
