### ISSUE TITLE
APT whitelist request for libz-dev

### ISSUE THREAD

**Issue by dexX7** [travis-ci/travis-ci#4036]

**Comment by langerhans** [comment]
+1

**Comment by dexX7** [comment]
@langerhans: a quick tip: you may subsitude [libz-dev](http://packages.ubuntu.com/en/precise/libz-dev) with [zlib1g-dev](http://packages.ubuntu.com/en/precise/zlib1g-dev).

**Comment by BanzaiMan** [comment]
Use `zlib1g-dev`, please.
