### ISSUE TITLE
build unknown when everything passes

### ISSUE THREAD

**Issue by tejasmanohar** [travis-ci/travis-ci#4040]
http://i.imgur.com/PbErwUn.png

"build unknown" but everything seems to be passing... been showing this for an hour or so

**Comment by tejasmanohar** [comment]
https://github.com/tejasmanohar/node-schedule

**Comment by BanzaiMan** [comment]
Same as https://github.com/travis-ci/travis-ci/issues/3991, https://github.com/travis-ci/travis-ci/issues/3996.

I've resolved the conflict now.

**Comment by andela-cofor** [comment]
@BanzaiMan 

https://github.com/andela/izanagi-cfh

Build Unknown but passes all travis test
