### ISSUE TITLE
Java 8 version update and bug

### ISSUE THREAD

**Issue by vertti** [travis-ci/travis-ci#4042]
My build fails on travis:

https://travis-ci.org/NitorCreations/Puggly

Error thrown is apparently a bug in Java8 that has been fixed but Travis is using an old version of Java8. Travis reports using (build 1.8.0_31-b13). The same code works fine on my machine running Java8  (build 1.8.0_45-b14).

The bug is this: https://bugs.openjdk.java.net/browse/JDK-8044546

Is there a way to run a more recent version of Java on Travis or are you planning on upgrading it?

**Comment by BanzaiMan** [comment]
Java 8 is picked out from here: https://launchpad.net/~webupd8team/+archive/ubuntu/java

The next build environment update will include Java 8u45 (or later), but we do not have concrete plans yet. If you need 8u45 right now, you can use [apt addon](http://docs.travis-ci.com/user/apt/), like so:

```yaml
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
```

You can see this in action here: https://travis-ci.org/BanzaiMan/travis_production_test/builds/65772094#L188

**Comment by vertti** [comment]
Thanks alot. That worked and I can live with that for now.

**Comment by stevenschwenke** [comment]
Worked for me, too. Thanks a lot! :)

**Comment by janisz** [comment]
It's not working for me :( I need Java 8u45 and used addon option but there is still u31
https://travis-ci.org/janisz/knowledge-representation/builds/80905848
https://github.com/janisz/knowledge-representation/blob/fourth_version/.travis.yml#L9

**Comment by cquiroz** [comment]
I'm hitting a javac compiler on the travis version when trying my sbt build:

[error] An exception has occurred in the compiler (1.8.0_31). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
[error] java.lang.AssertionError: isSubClass D
[error] 	at com.sun.tools.javac.code.Symbol.isSubClass(Symbol.java:447)

I tried to use the addons to run with Java 8u45 as we do in our dev environment but it seems it has no effect if the language is java.

Should it work the same for scala?

**Comment by koppor** [comment]
In the TravisCI setup as of June 27, 2016, one has to remove the `jdk:` part. Source: https://github.com/travis-ci/travis-ci/issues/5897#issuecomment-218354129
