### ISSUE TITLE
Live chat: "URA_LIMIT_REACHED"

### ISSUE THREAD

**Issue by hugovk** [travis-ci/travis-ci#4047]
1. Go to https://travis-ci.org/
2. Click Help -> Live Chat
Takes you to https://chat.travis-ci.com/

3. Under "Join Travis CI Support on Slack" Enter an email address and click "GET MY INVITE"

Expected error: Can chat with Travis CI.
Actual error: button shows error message: URA_LIMIT_REACHED

The only Google result: https://twitter.com/slackhq/status/518232693482323968

**Comment by pipermerriam** [comment]
Same issue.  Would be nice to be able to get into chat support.

**Comment by roidrage** [comment]
Thanks for reporting this issue.

I've fixed the issue on our end. While we're working on a longer term solution, I'm closing this issue.

In general, if you can't reach our live chat, the best way to get in touch with us is to shoot an email to support@travis-ci.com.

**Comment by carnun** [comment]
I get the same error.
