### ISSUE TITLE
"There are no builds for this repository."

### ISSUE THREAD

**Issue by hugovk** [travis-ci/travis-ci#4048]
There's something wrong with this repo:

https://travis-ci.org/python-pillow/pillow-wheels

It says "There are no builds for this repository." and "build unknown" in the badge.

But when following the link under "My repositories" on the left it takes me to the same URL, and I can see the builds under each tab. They're passing but the badge still says "build unknown".

Similar to #3996?

**Comment by BanzaiMan** [comment]
Yes. I've resolved the conflict for you. Sorry about the inconvenience.

**Comment by hugovk** [comment]
Thank you!

**Comment by hugovk** [comment]
@BanzaiMan Oh, looks like the same thing has happened here: https://travis-ci.org/pylast/pylast

**Comment by BanzaiMan** [comment]
@hugovk That's done, too.

**Comment by startaq** [comment]
@BanzaiMan: It looks like we have the same issue here too: https://travis-ci.org/mamedev/mame

Builds show up when I log in into Travis.

**Comment by BanzaiMan** [comment]
We deployed a fix for this issue recently, so the conflicts should be resolved automatically.

**Comment by Lotsolee** [comment]
@BanzaiMan how you solve this problem due to i also facing this problem
https://travis-ci.org/Lotsolee/Practical3.2exe1

**Comment by BanzaiMan** [comment]
@Lotsolee Sync happens periodically. I see the build in your repo now.

**Comment by ChristopherKing42** [comment]
It would be nice if it said when it checked last, so we don't think we are doing something wrong.
