### ISSUE TITLE
webrtc/samples Build status unknown and link unreachable

### ISSUE THREAD

**Issue by KaptenJansson** [travis-ci/travis-ci#4049]
Hi,

We moved our repo from googlechrome/samples to [webrtc/samples](https://github.com/webrtc/samples) a while back.

Due to this I'm pretty sure we are hitting issue #3996 because when I go to the [link](https://travis-ci.org/webrtc/samples) directly I see no info or branches however if I click on webrtc/samples in the my repo section it works fine. Build status remains unknown all the time though.

Could you take a look?

**Comment by BanzaiMan** [comment]
Sorry about the issue. I've resolved the conflict.

We are also looking at more automatic conflict resolution. For now, manual intervention is required.

**Comment by KaptenJansson** [comment]
Thank you for the swift response, I've confirmed that it's solved!
