### ISSUE TITLE
APT whitelist request for heroku-toolbelt

### ISSUE THREAD

**Issue by zupo** [travis-ci/travis-ci#4052]
The app that I test on Travis runs on Heroku. I have a script that:

1. shuts down the staging app
2. creates a copy of production db and restores it to staging app
3. runs DB migration scripts
4. starts up the staging app

This is ran on Travis every time there is a change in the migrations dir --> this way I get automatic DB migrations testing against production data.

However, the script depends on the heroku-toolbelt to be installed. Since moving to the containerized infrastructure I can no longer use sudo to run the following to install the heroku-toolbelt debian package:

```
  # add heroku repository to apt
  echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list

  # install heroku's release key for package verification
  wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -

  # update your sources
  apt-get update

  # install the toolbelt
  apt-get install -y heroku-toolbelt
```

**Comment by BanzaiMan** [comment]
Did not run automated check because 'heroku-toolbelt' needs source whitelisting

**Comment by zupo** [comment]
What does this mean? Is there an approx. ETA on getting this fixed?

**Comment by BanzaiMan** [comment]
Did not run automated check because 'heroku-toolbelt' needs source whitelisting

**Comment by BanzaiMan** [comment]
@zupo Sorry about the alarm. We're automating processing these requests.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/375.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
