### ISSUE TITLE
Xcode 6.4

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4054]
Xcode 6.4 beta is available now, and will go GA shortly.

(For Xcode 7, see #4055.)

**Comment by BanzaiMan** [comment]
We are testing 6.4 beta on our staging environment, and wil make Xcode 6.4 publicly available as soon as we can after it goes GA.

**Comment by pietbrauer** [comment]
Any update on this? Could use it for https://github.com/facebook/ios-snapshot-test-case/pull/90 as the compiler seems to segfault when using Xcode 6.3.1

**Comment by BanzaiMan** [comment]
Please note that, during the time Xcode 6.4 is beta, we are unable to make the image publicly available.

**Comment by guidomb** [comment]
Any updates on this?

**Comment by pietbrauer** [comment]
It shipped today. https://twitter.com/travisci/status/616154472897773568

**Comment by guidomb** [comment]
Nice!

**Comment by BanzaiMan** [comment]
Closing.
