### ISSUE TITLE
Xcode 7

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4055]
Xcode 7 is coming soon.

**Comment by BanzaiMan** [comment]
We will test 7.0 beta on our staging environment, and make it publicly available as soon as we can after it goes GA.

**Comment by michaelengland** [comment]
You guys rock. Looking forward to this one. :)

**Comment by BanzaiMan** [comment]
Please note that, during the time Xcode 7 is beta, we are unable to make the image publicly available.

**Comment by pietbrauer** [comment]
Why is that? Because of maintenance or because of the NDA? Ship.io already has Xcode 7 support and afaik they didn't get sued so far :wink:

**Comment by brentleyjones** [comment]
Would really be nice to have support for beta Xcode's...

**Comment by Dan2552** [comment]
+1

**Comment by kamoljan** [comment]
Any update on this issue?

**Comment by brentleyjones** [comment]
bitrise.io also has Xcode 7 Beta. I've been using them for the time being. I believe we live in a different time TravisCI, and we should have CI on beta versions.

**Comment by abbeycode** [comment]
:+1:

**Comment by lfaoro** [comment]
Xcode 7 support followup, please?

**Comment by jaysenmarais** [comment]
For a good 3 months after WWDC every year there's an Xcode beta available (not to mention point-release betas throughout the year). Having our CI system dictate what tools we can use is getting harder to justify all the time. I'd understand if Xcode Beta VMs were a "use at your own risk" deal, but not supporting Xcode betas at all is frustrating.

**Comment by kamoljan** [comment]
+1

**Comment by roidrage** [comment]
We don't have an update yet, but we're working on one. We're already testing out Xcode 7.0 beta with a few customers on travis-ci.com, and we're working on a full announcement soon. If you'd like to start using Xcode 7.0 for your private projects, shoot us an email to support@travis-ci.com. :metal:

**Comment by SandroMachado** [comment]
:+1:

**Comment by lfaoro** [comment]
News? ETA?

**Comment by cybertk** [comment]
+1

**Comment by roidrage** [comment]
![](http://i.giphy.com/ErLimaUL0blbW.gif)

**Comment by lfaoro** [comment]
.....

**Comment by brentleyjones** [comment]
Will the next beta be handled better? An ability to use the betas, especially when it comes to Swift, which requires a certain Xcode to compile, is a must have feature these days. Not being able to use CI for 3 months of the year is a real drag.

**Comment by abbeycode** [comment]
Also, is there an ETA on support for travis-ci.org?

**Comment by orta** [comment]
So, http://blog.travis-ci.com/2015-08-26-xcode-70-beta-is-now-available/ is available for private customers. 

For OSS, I wouldn't imagine it taking too long. FWIW, this is _really_ cool, this is the first time that travis have done a beta version of Xcode like this and it's a really good step forwards for the community!

**Comment by roidrage** [comment]
Regarding availability of Xcode 7.0 for open source repositories, the Travis team sends their love and this:

![](http://i.giphy.com/12oQNsLa6CccDu.gif)

Happy testing!

**Comment by solarce** [comment]
We've found an issue with the configs that is resulting in an earlier Xcode7 beta image being used, we're fixing this and will update this issue once we've confirmed builds are running with B6 like we want them to

**Comment by solarce** [comment]
Thank you all for your patience, I am happy to report that ** Xcode 7 beta 6** is now working as the default image when you use `osx_image: xcode7`. I have an [example build](https://travis-ci.org/solarce/osx-tests/builds/77560508) with it and the [`.travis.yml`](https://github.com/solarce/osx-tests/blob/6c089632cac02e5df49f2c19f87d134966cc901e/.travis.yml).

Please note that this means that **only Beta 6** is available now. It is possible to use https://github.com/neonichu/xcode-install#usage to install other Xcode 7 beta versions, but this can add a lot to your build time as you need to remove the existing version first, then install the new one from the Internet, so it's not something we can provide official help/support for at this time, if you run into issues with it.

Going forward we're going to focus on supporting the latest stable and beta version of Xcode only and will be releasing some more details and documentation on that in the neat future

As with every image update, we've updated both Xcode, OS X,  and a number of the common community tools, and with the number of changes those bring, it can lead to build breakage. We've been working through them as we moved from a limited to paid beta, to a full paid beta, to now an open public beta, but please reach out to [support at travis-ci.com](mailto:support@travis-ci.com) if you do need help with working through any build issues.

Thanks and Happy building!

**Comment by cybertk** [comment]
I am failed to run tests against Xcode 7. When I run tests with `xcodebuild test -sdk iphonesimulator`, Travis complained with

```
xcodebuild: error: Failed to build project XX with scheme XX.
	Reason: Xcode cannot run using the selected device.
```

**Comment by solarce** [comment]
@cybertk we'd be happy to help, please email support at Travis-CI.com and if you would, include a link to the failing build and we'll take a look. Thanks

**Comment by mattyohe** [comment]
@solarce same as @cybertk I did email, but here's a link as well: https://travis-ci.org/willowtreeapps/WillowTreeReachability/builds

Note the diffs between green and red builds are not changes to the actual project.

**Comment by cybertk** [comment]
@mattyohe I solved it by running test with:

```
xcodebuild test -scheme $(project) -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO OBJROOT=$(PWD)/build SYMROOT=$(PWD)/build
```

**Comment by mattyohe** [comment]
@cybertk thanks for the tip. Doesn't seem to work however either.

**Comment by mattyohe** [comment]
Ah, what did work was appending: `-destination 'platform=iOS Simulator,name=iPhone 6 Plus'`

**Comment by solarce** [comment]
The Xcode 7 GM is live now. http://blog.travis-ci.com/2015-09-09-xcode7-gm/

**Comment by cybertk** [comment]
Awesome speed

**Comment by mattyohe** [comment]
Wow, very impressive. Nice work team!
