### ISSUE TITLE
APT whitelist request for Crystal

### ISSUE THREAD

**Issue by will** [travis-ci/travis-ci#4056]
http://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html

```
apt-key adv --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
echo "deb http://dist.crystal-lang.org/apt crystal main" > /etc/apt/sources.list.d/crystal.list
```

**Comment by BanzaiMan** [comment]
@will Thanks for opening the issue. Do you wish to have Crystal as a language (a la `language: crystal`, say), or do you want to have these packages available for your builds in another language?

If the former, then it would be best to have community support. We have recently published the guideline at http://docs.travis-ci.com/user/languages/community-supported-languages/. Could you take a look and see if it is something you would like to pursue?

Thank you!

**Comment by will** [comment]
Originally I was following the instructions on http://docs.travis-ci.com/user/caching/#Caching-Ubuntu-packages " If you need to install packages from a repository not available in the list below, please shoot us an email, and we’ll add it for you." Then was directed to this process from that email.

Regardless of all that, I do think it being a `language:` would be best. I'll close this and start that process, thanks!
