### ISSUE TITLE
OSX + Rust fails to build

### ISSUE THREAD

**Issue by frewsxcv** [travis-ci/travis-ci#4058]
Sorry for the poor Issue title

OSX support is enabled for this repository: https://github.com/servo/core-graphics-rs

I opened a pull request that enables travis to run on it https://github.com/servo/core-graphics-rs/pull/38/files

Here is the result: https://travis-ci.org/servo/core-graphics-rs/builds/66054130

If I switch `os: osx` to `os: linux`, it builds fine.

**Comment by BanzaiMan** [comment]
@frewsxcv This might be related to the current DNS issue. http://stspg.io/1Ert

Could you wait for a while and try again?

**Comment by frewsxcv** [comment]
Looks like things are working now :+1:
