### ISSUE TITLE
multiple PHPUnit versions

### ISSUE THREAD

**Issue by lenada** [travis-ci/travis-ci#406]
Is it possible to have multiple PHPUnit versions pre installed? 
would be great. to have 3.4 and 3.5

currently I install the required phpunit version on every build  :/ 
not an elegant workaround really
https://github.com/lenada/travis-phpunit34/blob/master/.travis.yml

**Comment by jarofgreen** [comment]
Can this be looked at again? Now PHPUNIT 6 is out, it contains a non-BC breaking change. Thus all my tests break. I've added https://github.com/OpenACalendar/OpenACalendar-Web-Core/commit/84abf236c14c4abbd36a95790449d5dee59db12c to fix it which is not ideal as I'm putting a extra download bandwidth on both you and phpunit.

**Comment by BanzaiMan** [comment]
@jarofgreen Having a specified version of PHPUnit is different from what is being asked here (having multiple versions pre-installed and switch between them). If your build requires a specific version of PHPUnit, then we recommend what you are doing.
