### ISSUE TITLE
APT source whitelist request for Apache QPID

### ISSUE THREAD

**Issue by mbroadst** [travis-ci/travis-ci#4060]
ppa:mcpierce/qpid-testing

Also, as a requirement for automated testing without authentication (i.e. without configuring SASL etc), the following line must be added to /etc/qpid/qpidd.conf:

```
auth=no
```

**Comment by mbroadst** [comment]
@BanzaiMan Hi, is there any sort of timeline you guys follow for merging these in? Going back to non-containerized (sudo: true) builds has been killing iterations ;)

Just looking for a ballpark, especially if it's going to be months - I know y'all are busy!

**Comment by BanzaiMan** [comment]
Sorry for the delay. Unfortunately, vetting a package source takes a little more time.

**Comment by mbroadst** [comment]
@BanzaiMan no worries, I expected it would take some time. Please let me know if you would like me to get project maintainers in touch with you, in order to verify that the PPA is in fact their official repository for ubuntu packages (if that would help).

**Comment by BanzaiMan** [comment]
Did not run automated check because 'Apache QPID' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'Apache QPID' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT source whitelist request for Apache QPID' is ambiguous. Please specify only one.

**Comment by mbroadst** [comment]
@BanzaiMan are these messages directed to me?

**Comment by BanzaiMan** [comment]
@mbroadst Sorry. Those were generated by the script. There is no action for you at this time. Sorry for the confusion.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/36.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!

**Comment by mbroadst** [comment]
Gotcha, I did in fact originally make it there, but at the time the README.md text pointed users at creating the issues on the main issue tracker. Thanks!
