### ISSUE TITLE
Document  xctool_args for .travis.yml

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#4063]
http://docs.travis-ci.com/user/languages/objective-c/ should mention that it is possible to use `xctool_args` along with other, more specific options, like `xcode_project` in .travis.yml for objective-c builds.

The way it works is:

It detects if `xctool_args` is present. If so it uses it, otherwise defaults to an empty string. Now, for each of the known options `xctool_project`, `xctool_workspace`, `xctool_scheme`, and `xctool_sdk` it will add the respective value as a flag.

E.g. the following in .travis.yml

```
xctool_args: "-destination 'platform=iOS Simulator,name=iPhone 5s'"
xctool_workspace: "Foo.xcworkspace"
xctool_scheme: Foo 
xctool_sdk: iphonesimulator
```

would result in this test (script) command:

```
xctool -destination "platform=iOS Simulator,name=iPhone 5s" -workspace Foo.xcworkspace -scheme Foo -sdk iphonesimulator build test
```

See https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/objective_c.rb#L102-L108 for the implementation.

**Comment by joshk** [comment]
cc. @plaindocs

**Comment by svenfuchs** [comment]
moving this to https://github.com/travis-ci/docs-travis-ci-com/issues/252
