### ISSUE TITLE
Build environment: Use unbranded Firefox version for extensions testing

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#4064]
> Firefox is planning to introduce mandatory extension signing (https://blog.mozilla.org/addons/2015/02/10/extension-signing-safer-experience/) soon, which is going to break any and all firefox testing on Travis.
> 
> [This] will break all those Travis builds that test extensions, as extensions will have to be signed by Mozilla before the regular release version will load them. The only way to continue doing automated tests for this scenario is to have the unbranded build available in Travis.
> 
> The unbranded version is not bleeding edge, it is the same version as the released version, just with the extension signing enforcement disabled.

**Comment by carlin-q-scott** [comment]
Ok, so it's been a year and a half without progress on this issue. I can't keep using a browser release from two years ago...

**Comment by carlin-q-scott** [comment]
I found a fix for this in someone else's travis-ci build and adapted it to be universal. Here's the code: https://gist.github.com/carlin-q-scott/7d57cb4684fa28c1823169b53997368c

**Comment by BanzaiMan** [comment]
@carlin-q-scott Thanks for your interest. We apologize for the delay in getting this implemented.

I looked at your proposed solution, and I am interested in incorporating it to a more general solution. Your code parses an HTTP response body and looks for the "latest" version. It feels a bit brittle, however; if the HTTP response changes, it will break. Do you know if there is a more robust way to find the URL for the binary we want?

**Comment by carlin-q-scott** [comment]
I think it's unlikely for that page to change any more than an API would but I could try intercepting the Mozilla Firefox update detection requests and see where they go as there's likely a more programmatic interface to the updates.

**Comment by BanzaiMan** [comment]
We ended up using a different method to find the latest unsigned binary.
