### ISSUE TITLE
Failed building wheel for lxml

### ISSUE THREAD

**Issue by groovecoder** [travis-ci/travis-ci#4066]
We have a number of builds that just started failing today trying to build a wheel for lxml:

https://travis-ci.org/mozilla/kuma/jobs/66288024
https://travis-ci.org/mozilla/kuma/jobs/66287802
https://travis-ci.org/mozilla/kuma/jobs/66287763

Every once in a while [a job will pass](https://travis-ci.org/mozilla/kuma/jobs/66280826), but the failure rate is probably 90%.

**Comment by BanzaiMan** [comment]
Troubleshooting this issue requires some intimate knowledge about what is being run. Please email support@travis-ci.com, and we'll spin up a debug VM for you.
