### ISSUE TITLE
phpenv php binaries don't link to compiled libraries installed into /usr/local/lib

### ISSUE THREAD

**Issue by shadiakiki1986** [travis-ci/travis-ci#4067]
Issue: The php binary in phpenv on travis-ci workers doesn't automatically link to newly compiled libraries that get installed into /usr/local/lib. Below I specify my particular case applied to installing curl 7.42.1 with gnutls 3.1.28, but I think this is the case for any compiled and installed library

To reproduce:
1. compile nettle 2.7.1 from source and install
2. compile gnutls 3.1.28 from source and install
3. compile curl 7.42.1 from source and install
4. Expect php binary to show curl version 7.42.1 instead of the default 7.22.0, and GnuTLS 3.1.28
    `echo '<?php $cv=curl_version(); var_dump($cv["version"],$cv["ssl_version"]); ?>' | php`

Workaround: Install a separate php CLI other than the ones that travis-ci workers already have (in phpenv) solved it for me. Then, the php binary /usr/bin/php5 links properly to the curl and gnutls libraries that I install in /usr/local/lib
    `echo '<?php $cv=curl_version(); var_dump($cv["version"],$cv["ssl_version"]); ?>' | /usr/bin/php5`  (note the */usr/bin/php5* at the end of the line instead of plain *php*)

Proper solution: get the phpenv installed php binaries to link properly

Reference: Check [gnutls-3.1-travisci](https://github.com/shadiakiki1986/gnutls-3.1-travisci) which demonstrates this issue

**Comment by BanzaiMan** [comment]
Is this a phpenv issue?

**Comment by joshk** [comment]
When PHP is compiled it will be linked to the versions of CURL available when it was compiled. This would explain why your newly compiled version of PHP links to the updated packages.

**Comment by shadiakiki1986** [comment]
I don't compile the new version of php. I install it with sudo apt-get
install php5-cli

On Thu, Jun 11, 2015 at 5:10 PM, Josh Kalderimis <notifications@github.com>
wrote:

> When PHP is compiled it will be linked to the versions of CURL available
> when it was compiled. This would explain why your newly compiled version of
> PHP links to the updated packages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/travis-ci/issues/4067#issuecomment-111149015>
> .
>



-- 
Best, Shadi AKIKI
www.akikieng.com/shadi

**Comment by BanzaiMan** [comment]
It seems to me that when you compile these new software packages, they are finding the `/usr/bin` binaries instead of the runtimes that Travis CI VMs use. I suggest looking at configuration options to tell them where to look for `php` executable. We are happy to spin up a debug VM for you if you want to tweak your procedures more interactively.

**Comment by shadiakiki1986** [comment]
A debug VM would be fabulous!

**Comment by BanzaiMan** [comment]
@shadiakiki1986 Please email support@travis-ci.com.

**Comment by BanzaiMan** [comment]
Is this still an issue?

**Comment by shadiakiki1986** [comment]
Actually, I haven't had much time to continue my project these days, and I don't think I'll have much time for it in a couple of months. Anyway, it's not blocking me from using travis, so I'll just close the issue. At least it's documented now in case someone else faces the same problem.
