### ISSUE TITLE
Switch to https in the build_url irc token

### ISSUE THREAD

**Issue by maek** [travis-ci/travis-ci#4069]
Since you are using https on https://travis-ci.org/ it is more coherent to make the `build_url` irc token using it (as it is for `compare_url` and https://github.com/).

**Comment by BanzaiMan** [comment]
Where do you see HTTP URLs?

**Comment by maek** [comment]
In the irc notifications:

```
00:00:01	travis-ci	http://travis-ci.org/example/example/builds/01234567
00:00:02	travis-ci	https://github.com/example/example/compare/0123456789ab...0123456789ac
```

**Comment by BanzaiMan** [comment]
Thanks. We'll fix that soon.

**Comment by maek** [comment]
Ok, I close here since it seems solved. Thank you!
