### ISSUE TITLE
C# ANTLR

### ISSUE THREAD

**Issue by humsp** [travis-ci/travis-ci#4072]
cc @joshua-anderson @akoeplinger @nterry
Hey,

i want to complie my c# code, but an error occurs. 
- TweeVisitor.cs(18,43): error CS0246: The type or namespace name `Twee' could not be found. Are you missing an assembly reference?

I think it has something to do with the antlr-parser. See: https://travis-ci.org/humsp/uebersetzerbauSWP/builds/66446511

My travis.yml look like this:

sudo: required
language: csharp
solution: Twee2Z/Twee2Z.sln
install:
- nuget restore Twee2Z/Twee2Z.sln

Can you tell me, what i did wrong?
Thanks

**Comment by akoeplinger** [comment]
Yes, this seems to be an ANTLR problem. Looks like it needs Java (see https://github.com/tunnelvisionlabs/antlr4cs/issues/100), which isn't installed on the Travis machines when building a C# project.

Unfortunately, I don't think we can easily support that. @sharwell

**Comment by sharwell** [comment]
@akoeplinger see the discussion in tunnelvisionlabs/antlr4cs#94. I really want to get this resolved; the 4.5 releases will move to beta (currently alpha) as soon as this issue is handled. I think seeing it work on Travis will be a major motivating factor and proof that we were successful. I welcome any ideas or pull requests to help get us there. :+1:

**Comment by akoeplinger** [comment]
@sharwell I can guide you into setting up Travis for antlr4cs if that would help. Leveraging IKVM sounds like a great idea to me.

**Comment by sharwell** [comment]
@akoeplinger It would be difficult to build antlr4cs *itself* on Travis (it requires .NET Compact Framework 3.5), but I'm sure we could either do a restricted build for compatibility testing, or configure a different project to build on Travis using ANTLR.

**Comment by akoeplinger** [comment]
@sharwell ok, feel free to loop me in when you try it :)

**Comment by humsp** [comment]
thanks for your support :)

**Comment by sharwell** [comment]
@akoeplinger the latest beta release supports Travis. I have a new repository using it in the tunnelvisionlabs organization.

**Comment by akoeplinger** [comment]
@sharwell nice! any special steps/config you need to do in the .travis.yml?

**Comment by sharwell** [comment]
@akoeplinger a sample is available here: https://github.com/tunnelvisionlabs/antlr-integration-tests-csharp
