### ISSUE TITLE
Build fails for my fork, but works for Pull Requests

### ISSUE THREAD

**Issue by akhilaananthram** [travis-ci/travis-ci#4074]
It fails on my fork before it even attempts to compile my code. The code compiles and passes all tests on my local machine. Additionally, it works when I submit pull requests.

If I add "sudo: required" to .travis.yml, then it works on my fork and it still works for PR.  However, the PR worked fine without "sudo: required"

My fork's Travis CI console:
https://travis-ci.org/akhilaananthram/nupic/jobs/66115117

One of my PRs:
https://travis-ci.org/numenta/nupic/builds/66459764

Is there a work around to avoid modifying .travis.yml?Are there some account permissions I need to change?

**Comment by joshk** [comment]
It is likely the original project was created before we routed new projects to the Docker setup by default.

I highly recommend leaving the `sudo: required` in there.

**Comment by akhilaananthram** [comment]
But without "sudo: required" it works on other people's forks still.

**Comment by joshk** [comment]
It depends when does forks were created.

Sorry, I think the best solution is to add `sudo: required`
