### ISSUE TITLE
Add Perl 5.22

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#4077]

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-cookbooks/pull/482

**Comment by wbraswell** [comment]
@BanzaiMan 
Can I somehow use this to enable Perl v5.22 testing in a normal Travis setup?

My .travis.yml file:

https://github.com/wbraswell/rperl/blob/master/.travis.yml

My Travis landing page:

https://travis-ci.org/wbraswell/rperl

Thanks!
~ Will

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-cookbooks/pull/482#issuecomment-119029979

**Comment by pine613** [comment]
:+1:

**Comment by thaljef** [comment]
:+1:

**Comment by zoffixznet** [comment]
:+1:

**Comment by paultcochrane** [comment]
:+1:

**Comment by wbraswell** [comment]
So does Travis support Perl v5.22 yet or not?!?

**Comment by paultcochrane** [comment]
I received a very informative email from one of the Travis developers concerning this issue.  They know about the problem and it is being worked on.  The current container-based infrastructure (`sudo: false`) runs on Ubuntu 12.04 which hasn't yet had the changes on the master branch of the `travis-cookbook` repo pushed to it (`travis-cookbook` is where the Chef cookbooks used to provision the hosts are kept).  Theoretically, perls 5.10 to 5.22 should be available on the fully virtualized Ubuntu 14.04 systems (`sudo: required; dist: trusty`), however this is currently not working; the developer knows about the issue and is working on it.  We need to be patient for a bit longer before the new version is deployed.

**Comment by wbraswell** [comment]
@paultcochrane 
Thank you very much for the information, at least now we (kinda) know what is going on!
:-)

**Comment by BanzaiMan** [comment]
This is coming next Monday via https://github.com/travis-ci/travis-build/pull/518.

**Comment by zoffixznet** [comment]
Wooohoo \o/

**Comment by wbraswell** [comment]
@BanzaiMan ++
:+1:

**Comment by DrHyde** [comment]
And Travis just ran some of my tests with perl 5.22! Huzzah!

(so it looks like this can be closed now)

**Comment by BanzaiMan** [comment]
Indeed. I'm going to close this, because 5.22 is installed on demand if it's not yet available, and it will be for the build environment update.

**Comment by wbraswell** [comment]
IT WORKS!
@BanzaiMan ++
:+1:
