### ISSUE TITLE
APT whitelist request for metacity

### ISSUE THREAD

**Issue by LorenzoBettini** [travis-ci/travis-ci#4078]
For all my Eclipse projects I use SWTBot (https://www.eclipse.org/swtbot/) for UI/functional testing; SWTBot needs a Window Manager (xvfb is not enough) and metacity is usually the best to run SWTBot tests.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/apt-package-whitelist/commit/5eb7909ee915e6e60d5dbdce4383b1bd3bab3ac1 closes this.
