### ISSUE TITLE
APT whitelist request for FreeCAD dependencies

### ISSUE THREAD

**Issue by kuba1** [travis-ci/travis-ci#4080]
I'm working on .travis.yml script for FreeCAD (http://freecadweb.org/). It currently has quite a bit of dependencies - http://www.freecadweb.org/wiki/?title=CompileOnUnix#Debian_and_Ubuntu

I would need following packages:
libcoin60-dev
libsoqt4-dev
libxerces-c-dev
python-pyside
pyside-tools
libopencascade-dev
libshiboken-dev
libode-dev
libzipios++-dev
libsimage-dev
checkinstall
python-pivy
libcoin60-doc
libspnav-dev

also those but they already have separate issues:
python-matplotlib
qt4-dev-tools
libeigen3-dev

Thanks for help.

**Comment by kuba1** [comment]
Is this kind of issue acceptable? Should I create a separate issue for every package?

**Comment by BanzaiMan** [comment]
Sorry for the delay. Could you break this down to each package, please?

**Comment by kuba1** [comment]
I've done that. This one can be closed now I guess. Thanks for help.

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.
