### ISSUE TITLE
opcache.load_comments disabled on php7

### ISSUE THREAD

**Issue by Ma27** [travis-ci/travis-ci#4091]
is there any reason, why the *opcache.load_comments* option is disabled on php7??
https://travis-ci.org/Ma27/SenNetwork/jobs/66924968#L773

I've already tried to fix it using ini_set, but it didn't work

**Comment by BanzaiMan** [comment]
I'm not familiar with it. What does it do, and is it a compile time option, perhaps? If so,it isn't enabled. https://github.com/travis-ci/php-src-builder/blob/master/.travis.yml shows you how the nightly is built.

**Comment by sebastianbergmann** [comment]
It was removed anyway: http://git.php.net/?p=php-src.git;a=commitdiff;h=0a21a0c752a06d25704e04c15464700f75164849

**Comment by mikemix** [comment]
My build fails with PHP 7.0 as well.
Setting opcache.load_comments to 1 with phpenv is ignored.

**Comment by Ma27** [comment]
@sebastianbergmann thanks a lot!

**Comment by BanzaiMan** [comment]
Is there anything for us to do on this issue?

**Comment by sebastianbergmann** [comment]
No. Once the Travis' build of PHP 7 includes http://git.php.net/?p=php-src.git;a=commitdiff;h=0a21a0c752a06d25704e04c15464700f75164849 the issue will be gone.

**Comment by BanzaiMan** [comment]
The last build happened around 19:00 UTC yesterday with the latest source at that time, so it's already there, or it will be there later today.
