### ISSUE TITLE
APT source whitelist request for gcc-arm-embedded

### ISSUE THREAD

**Issue by jameysharp** [travis-ci/travis-ci#4092]
Please whitelist `ppa:terry.guo/gcc-arm-embedded`, ARM Ltd's cross-compile tool-chain. Thanks!

**Comment by BanzaiMan** [comment]
Did not run automated check because 'gcc-arm-embedded' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'gcc-arm-embedded' needs source whitelisting

**Comment by flixr** [comment]
:+1:  also need this package..

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/34.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
