### ISSUE TITLE
"Build unknown" in the badge

### ISSUE THREAD

**Issue by alexander-yakushev** [travis-ci/travis-ci#4094]
Project: https://travis-ci.org/clojure-android/neko/
Same as #4040 and similar issues. The build succeeds, although the badge doesn't update. I remember I created and then removing that repository in Travis before, so there might a conflict. But if there is a patch incoming that fixes all such repositories at once, there is no rush.

**Comment by BanzaiMan** [comment]
Sorry about the issue. I believe you deleted this repository and recreated a new one with the same name. I resolved the conflict, and the badge should work now.

**Comment by alexander-yakushev** [comment]
Thanks a lot!
