### ISSUE TITLE
Wrong file version in requirement package

### ISSUE THREAD

**Issue by buxx** [travis-ci/travis-ci#4096]
A file seems to be outdated in requirements package *synergine-0.0.1.9* when environment is build.

*.travis.yml*

    language: python
    python:
      - "3.4"
    install:
      - "pip install -r tests_requirements.txt --upgrade"
      - "pip install python-coveralls"
    script:
      - coverage run tests.py --rcfile=.coveragerc -v && coverage report -m && python3.4 tests.py
    after_success:
      - coveralls

**tests_requirements.txt**

    synergine>=0.0.1
    synergine_xyz>=0.0.1

**travis-ci.org** build log:

    [...]
    pip 6.0.7 from /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages (python 3.4)
    install.1
    
    1.74s $ pip install -r tests_requirements.txt --upgrade
    
    You are using pip version 6.0.7, however version 7.0.3 is available.
    
    You should consider upgrading via the 'pip install --upgrade pip' command.
    
    Collecting synergine>=0.0.1 (from -r tests_requirements.txt (line 1))
    
      Downloading synergine-0.0.1.9.tar.gz
    
        pypandoc not found
    
    Collecting synergine-xyz>=0.0.1 (from -r tests_requirements.txt (line 2))
    
      Downloading synergine_xyz-0.0.1.9.tar.gz
    
    Installing collected packages: synergine-xyz, synergine
    
      Running setup.py install for synergine-xyz
    
      Running setup.py install for synergine
    
        pypandoc not found
    
    Successfully installed synergine-0.0.1.9 synergine-xyz-0.0.1.9
    
    [...]
    
    [...]
    0.31s$ coverage run tests.py --rcfile=.coveragerc -v && coverage report -m && python3.4 tests.py
    
    [...]
    
      File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/synergine/core/simulation/MetaValue.py", line 19, in unset
    
        del (state[subject])
    
    NameError: name 'state' is not defined

The ``synergine/core/simulation/MetaValue.py", line 19, in unset`` on travis-ci build is:

    del (state[subject])

If we look ``synergine/core/simulation/MetaValue.py", line 19, in unset
`` available on [pypi][1]:

    del(metas[subject])

Files are not identicals. Problem is in a travis-ci cache ? How can i fix that ?

Build page available [here][2].

  [1]: https://pypi.python.org/packages/source/s/synergine/synergine-0.0.1.9.tar.gz#md5=84dfad46c5433a7b5a0672b0d8a6ab61
  [2]: https://travis-ci.org/buxx/intelligine

**Comment by BanzaiMan** [comment]
I am not quite sure how this is happening. This package, synergine-0.0.1.9, is not installed on the build image, so it must be downloaded for your builds at the build time. Assuming that the same problem manifests with `sudo: required`, we can spin up a debug VM for you. Please email support@travis-ci.com.

**Comment by buxx** [comment]
Hi, just sended a mail, thank's ;)

**Comment by BanzaiMan** [comment]
Is this still an issue? The most recent build (https://travis-ci.org/buxx/intelligine/builds/69353984) is passing.

**Comment by buxx** [comment]
Hi,
After discuss with Henrik Hodne by email, we not found how to fix issue. But problems maybe come from pypi (strange cache rule for download from travis-ci ..?). So, if we're right, travis-ci is not owner of bug.
I close issue ;)
