### ISSUE TITLE
Change oldest perl runtime named 5.8 from `5.8.9` to `5.8.8`

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#4097]
When @miyagawa added https://github.com/haarg/travis-cookbooks/commit/9057439d4, it didn't occur to anyone that perl `5.8.9` is a rather weird release. It happened **1 year** after `5.10.0` and as a result was a weird amalgamation of the `5.8.x` and `5.10.x` development trees. There are no known cases of an OS shipping this perl version - the only way to get it was/is for the user to compile it by hand.

This is why I propose changing the `5.8` runtime to [perl 5.8.8](https://metacpan.org/release/NWCLARK/perl-5.8.8), as testing against `5.8.9` is hardly more than burning TravisCI resources to test against a `5.10.0` wannabe.

/cc-ing the usual suspects: @haarg, @dagolden, @rjbs, @karenetheridge, @miyagawa, @shadowcat-mst

**Comment by dagolden** [comment]
FWIW, I agree.  I think mapping "5.8" to "5.8.8" is much more representative than 5.8.9.

**Comment by rjbs** [comment]
Totally agree.  5.8.9 is a platypus and, more importantly, not really used.

**Comment by haarg** [comment]
Agreed.  I've created travis-ci/travis-cookbooks#484 to change this.

**Comment by miyagawa** [comment]
Sounds good to me.

**Comment by BanzaiMan** [comment]
I merged the PR. Thanks, everyone, for the input!
