### ISSUE TITLE
[php][composer] No output has been received in the last 10 minutes

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#4098]
I'm lately seeing a lot of these messages for stale builds, typically composer gets stuck:

```
$ if [ "$DEPENDENCIES" = true ]; then composer install; fi
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/home/travis/.phpenv/versions/5.5/bin/composer self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev)
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

e.g. on https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/67001147#L110

I'm wondering if it would be possible to implement something like automatic restart (at least once) of stuck builds. Currently a lot of my prs turn up red, only due to stuck builds...

**Comment by BanzaiMan** [comment]
Automatic restarts are a problem if it is a truly stuck process, as it burns the resources perpetually.

**Comment by andig** [comment]
Here is another one where travis stalls: https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/67810566. This seems to happen more frequently recently and I've not seen such behaviour locally.

> Automatic restarts are a problem if it is a truly stuck process, as it burns the resources perpetually.

Of course. Yet, restarting once might help with transient failures like this one. Maybe restarting could be limited to operations considered standard or save like composer or npm?

**Comment by joshk** [comment]
I would have to agree with @BanzaiMan sorry, restarting something automatically hides the issue, and is fairly complicated to know when something is valid to restart or not.

Is it possible to run `composer install` in verbose mode so we can see where and why it is getting stuck?

**Comment by andig** [comment]
> Is it possible to run composer install in verbose mode so we can see where and why it is getting stuck?

Glad to. Here's another one that got stuck: https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/67819181. `composer -vv` doesn't show anything yet, I'll retry with `-vvv`.

**Comment by joshk** [comment]
Is this issue consistent? or intermittent?

**Comment by andig** [comment]
The issue is intermittent but always related to `composer`. Here's yet another one: https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/68123819. I have yet to catch one with highest logging level.

**Comment by andig** [comment]
Finally caught a build with highest composer log setting failing (https://travis-ci.org/andig/volkszaehler.org/jobs/68586115):

	...
	Installing dependencies (including require-dev)
	Downloading https://packagist.org/p/provider-2013$64cefc090dc586bcea264a3e17529dfa29b16b2bf50c52626562f13772982949.json
	Writing /home/travis/.composer/cache/repo/https---packagist.org/p-provider-2013.json into cache
	Downloading https://packagist.org/p/provider-2014$9ee92c17e2c998401fc1ae3dc963fd078fac8d42c6d56e19cfacce92388628e3.json
	Writing /home/travis/.composer/cache/repo/https---packagist.org/p-provider-2014.json into cache
	Downloading https://packagist.org/p/provider-2014-07$6241ad45014876b6293f399d05dadaa6463b083e59312d2aa0e73facd1790b3d.json
	Downloading https://packagist.org/p/provider-2014-07$6241ad45014876b6293f399d05dadaa6463b083e59312d2aa0e73facd1790b3d.json
	Writing /home/travis/.composer/cache/repo/https---packagist.org/p-provider-2014-07.json into cache
	Downloading https://packagist.org/p/provider-2014-10$eeb4fcc381c017efacf0bc795f959b20bbff46803e570d8a77238fb4e5f83b52.json
	Writing /home/travis/.composer/cache/repo/https---packagist.org/p-provider-2014-10.json into cache
	Downloading https://packagist.org/p/provider-2015-01$bbcbcd8632272384db42a941e5dd718d30190ccac06f3542677a00b602779a33.json
	No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
	The build has been terminated

**Comment by BanzaiMan** [comment]
So, sounds like this particular instance is an issue with slow downloads from packagist.org.

**Comment by BanzaiMan** [comment]
@andig Is this happening recently?

**Comment by joselfonseca** [comment]
@BanzaiMan it is happening to me here https://travis-ci.org/joselfonseca/laravel-api-tools/jobs/73126081only for PHP 5.5

**Comment by andig** [comment]
> @andig Is this happening recently?

Not to me. I've upgraded our build to use containers this week and have not seen it since. If @BanzaiMan is right that is is an infrastructure issue of a specific node may it make sense to put nodes with lots of stalled builds into review queue or similar? It's impossible to diagnose from the outside...

**Comment by joselfonseca** [comment]
@BanzaiMan it just worked, i heard composer was having some issues, i guess that is the reason. i do have to upgrade to containers. Thanks!

**Comment by BanzaiMan** [comment]
Closing this. If you continue to see this issue, please open a new one.
