### ISSUE TITLE
Go tip fails

### ISSUE THREAD

**Issue by al3xdm** [travis-ci/travis-ci#4101]
```
language: go

go:
  - tip
```

Fails with the error message:

```
$ eval "$(gimme tip)"
error: Missing bootstrap installation
error: Unable to compile go from git clone
I don't have any idea what to do with 'tip'.
  (using type 'auto')
```

Example build: https://magnum.travis-ci.com/PotentialWeb/feeder/jobs/18975078

I think this is because starting with Go 1.5, go actually compiles itself so needs an existing go installation set via $GOROOT_BOOTSTRAP

**Comment by meatballhat** [comment]
@al3xdm Thanks for the report!  This will be fixed over via meatballhat/gimme#16

**Comment by al3xdm** [comment]
Awesome, thanks for getting on it quickly @meatballhat  :) 

Once a fix has been cooked up, how long does it take for an updated gimme to get out to the container environment? Is there an option to deploy "edge" like on the dpl tool?

**Comment by meatballhat** [comment]
@al3xdm We're able to do this for everyone via [this option](https://github.com/travis-ci/travis-build/blob/6b4b10223541fa454e4e117186f665a51922a3f6/lib/travis/build/script/go.rb#L14) or you can `curl` the latest `gimme` manually if you choose :smiley_cat:

**Comment by joepvd** [comment]
https://github.com/travis-ci/gimme/issues/16 has been closed. We will close this one as well. Please reopen if the problem persists.
