### ISSUE TITLE
Build not triggered when merge commit pushed to pull request

### ISSUE THREAD

**Issue by lukeyeager** [travis-ci/travis-ci#4102]
See this pull request: https://github.com/NVIDIA/DIGITS/pull/137.

## Problem

The contributor added some commits and a new build was not triggered:
https://travis-ci.org/NVIDIA/DIGITS/builds

## Failed attempted solutions

* Nothing
  * It should trigger automatically, right?
* [Close & reopen PR](https://github.com/NVIDIA/DIGITS/pull/137#issuecomment-112488549)
  * [This comment on SO](http://stackoverflow.com/a/25046839/2404152) suggested that should work.

## Things that'll probably work, but I shouldn't have to do

* Ask contributor to add a new noop commit to the branch
* Ask contributor to squash his commits and repush as a single commit (he'll have to do that later anyway)

## My guess

I'm guessing the problem is due to the fact that the most recent commit pushed to the branch was [a merge commit](https://github.com/Deepomatic/DIGITS/commit/84a74ad8d8f9260331cd4fef3d234c701dc19d0f), and Travis doesn't know what to do with it?

**Comment by roidrage** [comment]
Thanks for reporting this issue.

Just to confirm, was the pull request in question mergeable with the latest commits added, incl. the merge commit?

**Comment by lukeyeager** [comment]
Oh, does the commit need to be merge-able without conflicts before Travis will trigger? So I just need to ask the contributor to rebase against master?

**Comment by roidrage** [comment]
Confirmed, it needs to be mergeable, as we build the merge between the downstream and upstream branch.

**Comment by lukeyeager** [comment]
Got it. Thanks for the help!
