### ISSUE TITLE
Typo at document `*deployment` -> `*deploy`

### ISSUE THREAD

**Issue by 59naga** [travis-ci/travis-ci#4103]
Doesn't work `*deployment` hooks with the method described at document.

http://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
> 
before_install
install
before_script
script
after_success or after_failure
after_script
OPTIONAL __before_deployment__
OPTIONAL __deployment__
OPTIONAL __after_deployment__

At example:
> https://github.com/59naga/pixel-util/commit/6e5d1ca810953a6cba97264925aeec0b7729d767
> https://travis-ci.org/59naga/pixel-util/builds/67118783#L523

Rename to `*_deploy`, it works.
> https://github.com/59naga/pixel-util/commit/ab0389e62e97043f65bbd848a098c9762955dfac
> https://travis-ci.org/59naga/pixel-util/builds/67119161#523

**Comment by BanzaiMan** [comment]
Thanks for pointing this out. Do you mind creating a PR for https://github.com/travis-ci/docs-travis-ci-com?

**Comment by 59naga** [comment]
Ok, move to this.
