### ISSUE TITLE
Failed to add mongo.so extension

### ISSUE THREAD

**Issue by smilesrg** [travis-ci/travis-ci#4104]
As described in [manual](http://docs.travis-ci.com/user/languages/php/#Custom-PHP-configuration) I am trying to add mongo.so extension, but it fails: https://travis-ci.org/ddeboer/data-import/jobs/67207422

https://github.com/smilesrg/data-import/blob/master/.travis.yml
https://github.com/smilesrg/data-import/blob/master/travis_php.ini

UPD: I tried to move ```phpenv config-add travis_php.ini``` from ```before_script``` to ```install``` section, but it doesn't work too. It shows warning:
```
Warning: PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/nightly/lib/php/extensions/no-debug-zts-20141001/mongo.so' - /home/travis/.phpenv/versions/nightly/lib/php/extensions/no-debug-zts-20141001/mongo.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

**Comment by BanzaiMan** [comment]
This is curious. https://travis-ci.org/ddeboer/data-import/jobs/64682188 shows it sometimes works, without any change in system or code. If you restart this job, does it suceed?

**Comment by smilesrg** [comment]
@BanzaiMan yes, it is strange. While it works for PHP 5.x now, it doesn't work for [PHP7](https://travis-ci.org/ddeboer/data-import/jobs/67319426) and [PHP HHVM](https://travis-ci.org/ddeboer/data-import/jobs/67319428)

**Comment by BanzaiMan** [comment]
Mongo extension is not available for PHP nightly. See https://github.com/travis-ci/travis-ci/issues/3286#issuecomment-76333570

**Comment by BanzaiMan** [comment]
Is this still an issue? If the issue persists on the standard infrastructure (i.e., with `sudo: required`), then we can spin up a debug VM for you.

**Comment by roidrage** [comment]
We haven't heard back from you on this issue, so we're closing this for now.

Keep us posted if you continue to experience issues here.

**Comment by mapkyca** [comment]
Just googled an issue I'm having, and it seems to be the same as this.

I'm building for php 5.4/5/6 and the script has suddenly stopped working (intermittently) for mongo builds, complaining that it can't find the .so

E.g.

``` 
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/mongo.so' - /home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/mongo.so: cannot open shared object file: No such file or directory in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/mongo.so' - /home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/mongo.so: cannot open shared object file: No such file or directory in Unknown on line 0 
```

Given that it works sometimes and fails others, my hunch is that there are a few broken build images around...
