### ISSUE TITLE
APT whitelist request for shellcheck

### ISSUE THREAD

**Issue by cep21** [travis-ci/travis-ci#4105]
Shellcheck is a great tool for integration/unit testing https://github.com/koalaman/shellcheck

**Comment by BanzaiMan** [comment]
This package does not exist for Precise http://packages.ubuntu.com/precise/shellcheck or Trusty http://packages.ubuntu.com/trusty/shellcheck. Which PPA has this?

**Comment by cep21** [comment]
Do either of these help:

http://packages.ubuntu.com/trusty-backports/devel/shellcheck
https://launchpad.net/ubuntu/trusty/+source/shellcheck

**Comment by BanzaiMan** [comment]
Sorry, we don't support Trusty just yet.

**Comment by BanzaiMan** [comment]
If you are using a Haskell image, you'd have `cabal`, and I suspect you can run

```
cabal update
cabal install shellcheck
```

**Comment by cep21** [comment]
Unfortunately, using cabal works but increases my build time by 30 minutes

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71822108

**Comment by BanzaiMan** [comment]
Did not run automated check because 'shellcheck' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/376.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!

**Comment by jhoblitt** [comment]
@BanzaiMan Even with `dist: trusty` I am getting `E: Unable to locate package shellcheck`

**Comment by jhoblitt** [comment]
OK - looks like `shellcheck` is not whitelisted for trusty.  However, it doesn't seem to be working with precise either: https://travis-ci.org/lsst/lsstsw/builds/88011361

**Comment by BanzaiMan** [comment]
With Trusty, you can use `sudo`.

**Comment by jhoblitt** [comment]
@BanzaiMan I am using `sudo: required` -- is the expectation that end users need to setup the core apt repos [again] ?

**Comment by jhoblitt** [comment]
Let me be clear.  It does not work with the beta apt addon, nor does it work with `sudo: required`, nor does it work with `sudo: required` & `dist: trusty`.  I'm guessing that the package is missing from the internal apt mirror.
