### ISSUE TITLE
APT whitelist request for qemu-system-x86_64

### ISSUE THREAD

**Issue by ArielAbreu** [travis-ci/travis-ci#4110]
I need this to test my build. Using sudo apt get install, I get a failed to fetch error.

**Comment by BanzaiMan** [comment]
You get the error because this package does not exist for Precise. http://packages.ubuntu.com/precise/qemu-system-x86_64

Where do you expect to download it from?

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/377.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
