### ISSUE TITLE
Travis should not run Pull request (PR) again if PR has same hash and same target.

### ISSUE THREAD

**Issue by marutosi** [travis-ci/travis-ci#4114]
Related https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-76325277 .

OpenProject claims this travis behavior.
https://github.com/opf/openproject/pull/3098#issuecomment-110508826

> Reopening the same PRs again and again against the recommendations of the team was quite a feat (triggering TravisCI Pr runs for each one).

**Comment by BanzaiMan** [comment]
Sounds like a duplicate of #2200.
