### ISSUE TITLE
update `Building an R Project`

### ISSUE THREAD

**Issue by mfrasca** [travis-ci/travis-ci#4115]
the page at http://docs.travis-ci.com/user/languages/r/ states what you minimally need to build a r project.
at the very least, you also need
`sudo: required`

I know it is stated *after* the file. I think it would better be *in* the file, with the correct syntax.

**Comment by BanzaiMan** [comment]
Thanks for the suggestion. Could you open a PR for https://github.com/travis-ci/docs-travis-ci-com?

**Comment by mfrasca** [comment]
https://github.com/travis-ci/docs-travis-ci-com/pull/268

**Comment by BanzaiMan** [comment]
Thanks. I merged the PR.
