### ISSUE TITLE
APT whitelist request for libwxgtk2.8-dev

### ISSUE THREAD

**Issue by Hiradur** [travis-ci/travis-ci#4119]
libwxgtk2.8-dev or newer

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 libwxbase2.8-0 libwxbase2.8-dev libwxbase2.8-dbg libwxgtk2.8-0 libwxgtk2.8-dev libwxgtk2.8-dbg libwxgtk-media2.8-0 libwxgtk-media2.8-dbg libwxgtk-media2.8-dev python-wxgtk2.8 python-wxgtk2.8-dbg python-wxversion python-wxtools wx-common wx2.8-headers wx2.8-i18n wx2.8-doc wx2.8-examples libwxmsw2.8-dev libwxmsw2.8-dbg wx2.8-headers-msw

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72408112.

**Comment by BanzaiMan** [comment]
This APT source request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/378.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
