### ISSUE TITLE
hover over full date on job page

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#4124]
On the job page, the top right hand corner reports info similar to

```
    2401.1 errored
    Commit 4f2781c
    Compare b203415..4f2781c
    ran for 17 min 59 sec
    5 days ago
```

It would be nice if '5 days ago' showed a complete date when hovered over, similar to the /builds listing.

**Comment by BanzaiMan** [comment]
I think we do this now.

![job__2162_1_-_banzaiman_travis_production_test_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/12234419/e2109854-b83a-11e5-9301-1a56d274121e.png)

**Comment by jayvdb** [comment]
confirmed; probably fixed when the UI was recently overhauled (very nicely I must add)
