### ISSUE TITLE
Could not find an executable 'phantomjs' that matched the requirements '~> 1.8', '>= 1.8.1'

### ISSUE THREAD

**Issue by gajendrajena** [travis-ci/travis-ci#4127]
Could not find an executable 'phantomjs' that matched the requirements '~> 1.8', '>= 1.8.1'
I have intalled phantomjs 2.0.0 using 
  brew install phantomjs

When I try the following in console it works
Cliver.detect!('phantomjs', '>=1.8.1')
 => "/usr/local/bin/phantomjs"

but the following didn't work
Cliver.detect!('phantomjs', '~>1.8', '>=1.8.1')
Cliver.detect!('phantomjs', '~>1.8')

**Comment by BanzaiMan** [comment]
Is this happening on Travis? If so, could you point to the build log URL? What is `Cliver`, and is `~>` a valid operator for the version you are using?

**Comment by tansaku** [comment]
I'm currently having this issue in https://travis-ci.org/AgileVentures/LocalSupport/builds/151377304

the strange thing is that we nothing about those versions of phantomjs in our gemfile or gemfile.lock ...

**Comment by BanzaiMan** [comment]
A [Google search](https://www.google.com/search?q=Cliver%3A%3ADependency%3A%3AVersionMismatch&oq=Cliver%3A%3ADependency%3A%3AVersionMismatch&aqs=chrome..69i57j69i58.302j0j4&sourceid=chrome&ie=UTF-8) leads to a couple of issues related to poltergeist:

https://github.com/teampoltergeist/poltergeist/issues/574
https://github.com/teampoltergeist/poltergeist/issues/595

which suggests updating that gem might be a good idea. Indeed, in @tansaku's case, poltergeist is [1.5.0](https://rubygems.org/gems/poltergeist/versions/1.3.0), which is 3 years old.

**Comment by tansaku** [comment]
thanks @BanzaiMan - I think I've resolved that issue by running bundle update across the board

**Comment by BanzaiMan** [comment]
@tansaku Thanks for the confirmation. I'm closing this now optimistically, as there is nothing on our side to do.

@gajendrajena If you believe there are other issues to resolve, do let us know.

**Comment by tansaku** [comment]
thanks @BanzaiMan
