### ISSUE TITLE
Clarify Documentation On Specifying Mono Versions

### ISSUE THREAD

**Issue by martincostello** [travis-ci/travis-ci#4130]
Started from discussion in #3546.

In the Travis CI documentation for [specifying a version of Mono to use](http://docs.travis-ci.com/user/languages/csharp/#Choosing-Mono-version-to-test-against) there is some room for interpretation of how the version specified in ```.travis.yml``` works as the patch version is ignored when getting the version of Mono. For example, specifying ```3.12.0``` would download ```3.12.1``` instead of ```3.12.0``` if the latest patch release of the ```3.12.0``` *series* was ```3.12.1```.

Whilst this a limitation of the Xamarin repositories, calling this out in the documentation may prevent user confusion.

**Comment by BanzaiMan** [comment]
I am not familiar with C# ecosystem, so I very much appreciate community involvement on this.

@martincostello @joshua-anderson @akoeplinger @nterry

Suggestions are welcome to https://github.com/travis-ci/docs-travis-ci-com.
