### ISSUE TITLE
error results in 0 returned, check passed

### ISSUE THREAD

**Issue by edzer** [travis-ci/travis-ci#4133]
See last lines of https://travis-ci.org/edzer/trajectories/builds/68041961

```
Package suggested but not available: ‘OpenStreetMap’
The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.
See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
* DONE
Status: 1 ERROR, 1 NOTE
0.01s$ for name in $(find "${RCHECK_DIR}" -type f -name "*fail"); do echo ">>> Filename: ${name} <<<"; cat ${name}; done
R CMD check failed
$ export RCHECK_DIR=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package, ".Rcheck"))')
0.01s$ grep -q -R "WARNING" "${RCHECK_DIR}/00check.log"; RETVAL=$?
The command "grep -q -R "WARNING" "${RCHECK_DIR}/00check.log"; RETVAL=$?" exited with 0.
```

it looks like only a warning triggers a fail.

**Comment by BanzaiMan** [comment]
Paging @craigcitro @eddelbuettel @hadley

**Comment by craigcitro** [comment]
so i think this makes the errors here and in #3697 clear -- it's the old bad-exit-code handling bug, likely due to a different codepath.

i'm a bit slammed, but will see if i can roll a quick fix this afternoon.

**Comment by craigcitro** [comment]
quick update: i know where the problem is, but i don't understand why it's failing. will update once i figure that out.

**Comment by edzer** [comment]
maybe change the final line of the travis script from

`grep -q -R "WARNING" "${RCHECK_DIR}/00check.log"; RETVAL=$?`

into

`grep -q -R -e "WARNING" -e "ERROR" "${RCHECK_DIR}/00check.log"; RETVAL=$?`

in case `warnings_are_errors: true`

**Comment by craigcitro** [comment]
this should be fixed now -- @edzer if you can re-run your build to confirm, that'd be awesome. thanks!

**Comment by edzer** [comment]
confirmed, works fine now. Thanks @craigcitro !
