### ISSUE TITLE
Transferred Repo Uknown Build Status

### ISSUE THREAD

**Issue by creichert** [travis-ci/travis-ci#4134]
I had a repo transferred to my account today which was previously a fork:
https://github.com/creichert/ido-vertical-mode.el

The build has an unknown status badge: https://travis-ci.org/creichert/ido-vertical-mode.el.svg?branch=master, even though I've submitted several builds.

I do have successful builds but they are no shown in the repo's travis page. I get the message `There are no builds for this repository.` Only when I click on a successful build link do the builds pop up: https://travis-ci.org/creichert/ido-vertical-mode.el/builds/68065122

**Comment by BanzaiMan** [comment]
Sorry about the issue. I resolved the name conflict.
