### ISSUE TITLE
APT whitelist request for boost*

### ISSUE THREAD

**Issue by floli** [travis-ci/travis-ci#4136]
apt-source-whitelist contains
```
  {
    "alias": "boost-latest",
    "sourceline": "ppa:boost-latest/ppa",
    "key_url": null
  }
```
which contains packages like ```boost1.55```, see https://launchpad.net/~boost-latest/+archive/ubuntu/ppa

These packages are not whitelisted. What is the use of this whitelisted repository then?

Thanks!

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #3759. If you believe otherwise, do let us know.
