### ISSUE TITLE
Ignore branches that don't have .travis.yml file

### ISSUE THREAD

**Issue by renan** [travis-ci/travis-ci#414]
Right now every thing that needs to be configured in done on .travis.yml file, which gives you all the control you need for a singular branch. However there is no way to have "global" configuration per say, eg: disabling a specific branch without having a .travis.yml file.

I don't really get why there is a way to blacklist/whitelist a specific branch, I would rather:
- Not have a .travis.yml on a branch that I don't need/want testing
- Or, have a "enabled: false"/"disabled: true" key on .travis.yml
- Or, have a global configuration on Travis website to define specific branches and others configurations (eg: disable notifications)

On CakePHP we have 5 keys branches now, and only one or two of those branches will actually use Travis. We will simply not have tests on Travis for 1.x and 2.0 releases as they are on stable release and new features can't be implemented on it.

This is the conversation I had with @michaelklishin on IRC: http://bin.cakephp.org/view/416566988

**Comment by kaizhu256** [comment]
shouldn't this issue be closed, since u can now toggle .travis.yml build in project settings?
