### ISSUE TITLE
Automatically populate list of Scala versions from SBT key

### ISSUE THREAD

**Issue by travisbrown** [travis-ci/travis-ci#4140]
It's currently necessary to list Scala versions in `.travis.yml` files, like this:

```yaml
scala:
  - 2.10.5
  - 2.11.6
```

Alternatively Scala projects can provide their own script that calls SBT with `+test`, etc., but that means that you don't get the nice Scala version matrix in the Travis reporting.

It's pretty easy to get the Scala versions supported by the SBT build:

```
ostrich (develop)]$ sbt "show crossScalaVersions"
[info] Loading global plugins from .sbt/0.13/plugins
[info] Loading project definition from ostrich/project
[info] Set current project to ostrich (in build file:ostrich/)
[info] List(2.10.5, 2.11.6)
```

Would it be possible to have SBT's cross version list used when the `.travis.yml` list is (optionally) omitted?

**Comment by BanzaiMan** [comment]
Thanks for opening the issue.

Unfortunately, I do not think this is going to work. When we construct a build matrix, we do it with the information given in `.travis.yml`, and in `.travis.yml` alone. There is no chance for anything on the build image to influence the build process (let alone build matrix) until the VM is provisioned and booted up; `sbt` cannot see what's in your repository until the build matrix had already been constructed.

**Comment by BanzaiMan** [comment]
It might be possible to create a `git` commit hook that updates the `scala` array, based on the information in your file, though.

**Comment by BanzaiMan** [comment]
I'm closing this, since we are unable to do this.
