### ISSUE TITLE
Failed git checkout on forced push

### ISSUE THREAD

**Issue by jhalterman** [travis-ci/travis-ci#4141]
I have a build where git checkout is failing after having done a --force'ed push.

https://travis-ci.org/jhalterman/concurrentunit/jobs/68377364

I dug around and saw some old issues related to this, but they look to have been already fixed.

**Comment by BanzaiMan** [comment]
Sounds like a duplicate of #2118.

**Comment by jhalterman** [comment]
Yep, I think you're right.
