### ISSUE TITLE
APT source whitelist request for cython-dev

### ISSUE THREAD

**Issue by itziakos** [travis-ci/travis-ci#4144]
The launchpad repository for the latest `cython` version `ppa:cython-dev/master-ppa`.  Having `cython` already installed will speed up a number of python packages testing.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'cython-dev' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'cython-dev' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/37.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
