### ISSUE TITLE
APT whitelist request for r-recommended

### ISSUE THREAD

**Issue by yihui** [travis-ci/travis-ci#4146]
Thanks @meatballhat for whitelisting the R packages at https://github.com/travis-ci/apt-package-whitelist/commit/87d55e3039d82d62c0d4aaf7718665b8437c6113. However, it will be much more convenient to just whitelist the meta package `r-recommended`, which has all the `r-cran-*` packages (listed in https://github.com/travis-ci/apt-package-whitelist/commit/87d55e3039d82d62c0d4aaf7718665b8437c6113) as its dependencies. It is cumbersome to list all `r-cran-*` in .travis.yml.

**Comment by meatballhat** [comment]
Awesome!  That's much cleaner :smiley_cat:

**Comment by yihui** [comment]
Perfect. Glad that I no longer have to type 20 package names :+1:
