### ISSUE TITLE
APT whitelist request for libsodium-dev

### ISSUE THREAD

**Issue by emembrives** [travis-ci/travis-ci#4148]

**Comment by paddor** [comment]
+1

**Comment by BanzaiMan** [comment]
This package does not exist for Precise. http://packages.ubuntu.com/precise/libsodium-dev

**Comment by paddor** [comment]
Thanks for the info. I'm currently just compiling libsodium for every build.

**Comment by BanzaiMan** [comment]
In the absence of appropriate package repository, I'm closing this for now.
