### ISSUE TITLE
Icon is not centered correctly

### ISSUE THREAD

**Issue by alex** [travis-ci/travis-ci#4150]
![screen shot 2015-06-27 at 3 51 16 pm](https://cloud.githubusercontent.com/assets/772/8393593/68d2df3e-1ce4-11e5-8d81-d9fc146ff4e2.png)

On close inspection it's clear that the X is not centered.

**Comment by lislis** [comment]
This is fixed now, I'm closing this.
![screen shot 2015-10-23 at 12 00 31](https://cloud.githubusercontent.com/assets/1006478/10692772/f2a08a48-7993-11e5-97f8-ec36b7422db5.png)
![screen shot 2015-10-23 at 12 05 56](https://cloud.githubusercontent.com/assets/1006478/10692773/f2a3016a-7993-11e5-93a1-1b1e5d3b32d2.png)
![screen shot 2015-10-23 at 13 49 17](https://cloud.githubusercontent.com/assets/1006478/10692771/f2a059ce-7993-11e5-86ba-5028c64d154e.png)
