### ISSUE TITLE
Travis CI With Visual Studio VB not building

### ISSUE THREAD

**Issue by PSNAppz** [travis-ci/travis-ci#4156]
0.03s$ xbuild /version
XBuild Engine Version 12.0
Mono, Version 4.0.1.0
Copyright (C) 2005-2013 Various Mono authors
1.17s$ nuget restore QuantConnect.Lean.sln
Cannot locate a solution file.
The command "nuget restore QuantConnect.Lean.sln" failed and exited with 1 during .
Your build has been stopped.  
```

THIS IS MY REPO:

https://github.com/PSNAppz/KeyLogger

**Comment by BanzaiMan** [comment]
Paging @joshua-anderson @akoeplinger @nterry

**Comment by ikkentim** [comment]
The solution you've linked to does indeed not contains a `QuantConnect.Lean.sln` but does contain a `KeyLogger.sln`

Update the line `nuget restore QuantConnect.Lean.sln` to `nuget restore KeyLogger.sln` in your travis.yml.

**Comment by PSNAppz** [comment]
Oh Sry

**Comment by ikkentim** [comment]
Try resolving the warnings it gives

`warning : Reference 'System.Deployment' not resolved`

You don't seem to be using it in your code so simply remove the reference as it's apparently not part of the mono library.

**Comment by PSNAppz** [comment]
Unused References Removed Now this appeared!

Project "/home/travis/build/PSNAppz/KeyLogger/KeyLogger.sln" (default target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "Release|Any CPU".
	Target Build:
		Project "/home/travis/build/PSNAppz/KeyLogger/KeyLogger/KeyLogger.vbproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
				Created directory "bin/Release/"
				Created directory "obj/Release/"
			Target GenerateResources:
				Tool /usr/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "about.resx,obj/Release/KeyLogger.About.resources" 
				Tool /usr/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "controlpanel.resx,obj/Release/KeyLogger.controlpanel.resources" 
				Tool /usr/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "Form1.resx,obj/Release/KeyLogger.Form1.resources" 
				Tool /usr/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "Menu.resx,obj/Release/KeyLogger.Menu.resources" 
				Tool /usr/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "My Project/Resources.resx,obj/Release/KeyLogger.Resources.resources" 
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
		Done building project "/home/travis/build/PSNAppz/KeyLogger/KeyLogger/KeyLogger.vbproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/travis/build/PSNAppz/KeyLogger/KeyLogger.sln".-- FAILED
Done building project "/home/travis/build/PSNAppz/KeyLogger/KeyLogger.sln".-- FAILED
Build FAILED.
	 0 Warning(s)
	 0 Error(s)
Time Elapsed 00:00:01.2113860
The command "xbuild /p:Configuration=Release KeyLogger.sln" exited with 1.
Done. Your build exited with 1.

**Comment by BanzaiMan** [comment]
@PSNAppz Instead of pasting logs, please provide the URL to a build that shows the problem. Makes the issue more concise.

**Comment by PSNAppz** [comment]
Git Hub Repo:
https://github.com/PSNAppz/KeyLogger

TRAVIS:
https://travis-ci.org/PSNAppz/TravisTest

**Comment by PSNAppz** [comment]
Any Solution yet?

**Comment by akoeplinger** [comment]
@PSNAppz I recently identified an issue in Mono 4.0 that broke VB projects (it's now fixed in Mono master and the upcoming 4.2). You can work around it by passing `/p:VbcToolExe=vbnc.exe` to the `xbuild` command in `.travis.yml` for now.

**Comment by PSNAppz** [comment]
I didn't get it can u make the .travis.yml for me?

**Comment by PSNAppz** [comment]
Not working

**Comment by akoeplinger** [comment]
Hey @PSNAppz, sorry for the delay. I've sent you a PR that fixes the errors you're seeing: https://github.com/PSNAppz/KeyLogger/issues/3

**Comment by PSNAppz** [comment]
Thank you !
