### ISSUE TITLE
APT whitelist request for qt5-default and libqt5webkit5-dev

### ISSUE THREAD

**Issue by mcmire** [travis-ci/travis-ci#4157]
This is necessary in order to run capybara-webkit tests against a project that requires Qt 5 (using features that weren't available in Qt 4, such as ES5 getters/setters). ([Source](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#debian-testing-unstable-stable-wheezy--ubuntu-1404-lts))

Thanks!

**Comment by BanzaiMan** [comment]
Did not run automated check because 'qt5-default and libqt5webkit5-dev' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'qt5-default and libqt5webkit5-dev' needs trusty

**Comment by mcmire** [comment]
I thought that Trusty is installed on the Linux boxes?

**Comment by BanzaiMan** [comment]
Did not run automated check because 'qt5-default and libqt5webkit5-dev' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'qt5-default and libqt5webkit5-dev' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for qt5-default and libqt5webkit5-dev' is ambiguous. Please specify only one.

**Comment by mcmire** [comment]
Ah, I see what the issue is. I'll post separate issues for both packages.
