### ISSUE TITLE
C# Failing builds

### ISSUE THREAD

**Issue by notdev** [travis-ci/travis-ci#4161]
Builds are failing on:
Inner exception: Could not find a part of the path "/home/travis/build/notdev/MovieLibrary/MovieLibrary/resources/functions.js".

Full log available at:
https://travis-ci.org/notdev/MovieLibrary

/cc  @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
@notdev The file it's complaining about is actually contained in the "MovieLibrary/**R**esources/" folder (not upper case R). As Travis is building on Linux with a case-sensitive file system it can't find the file, try changing the casing to match with what's on disk.

**Comment by notdev** [comment]
I have renamed the folder to lowercase 'resources' but it still fails.

Any advice how to proceed?

**Comment by akoeplinger** [comment]
Hey @notdev, sorry for the delay. I've sent you a PR that should fix the errors you're seeing: https://github.com/notdev/MovieLibrary/pull/1

There are a few caveats as e.g. the MSTest framework is only supported on Windows and Travis uses Mono/Linux to build and Fody throws an error as well.

**Comment by notdev** [comment]
Thank you, accepted PR
