### ISSUE TITLE
Erlang 18 support

### ISSUE THREAD

**Issue by lpgauth** [travis-ci/travis-ci#4162]
When adding 18.0 to release list:
```
otp_release:
  - 18.0
```
I get the following error:
```
$ source $HOME/otp/18.0/activate
/home/travis/build.sh: line 41: /home/travis/otp/18.0/activate: No such file or directory
The command "source $HOME/otp/18.0/activate" failed and exited with 1 during.
```
Even though it is supported by kerl:
```
./kerl list releases
R10B-0 R10B-10 R10B-1a R10B-2 R10B-3 R10B-4 R10B-5 R10B-6 R10B-7 R10B-8 R10B-9 R11B-0 R11B-1 R11B-2 R11B-3 R11B-4 R11B-5 R12B-0 R12B-1 R12B-2 R12B-3 R12B-4 R12B-5 R13A R13B01 R13B02-1 R13B02 R13B03 R13B04 R13B R14A R14B01 R14B02 R14B03 R14B04 R14B R14B_erts-5.8.1.1 R15B01 R15B02 R15B02_with_MSVCR100_installer_fix R15B03-1 R15B03 R15B R16A_RELEASE_CANDIDATE R16B01 R16B02 R16B03-1 R16B03 R16B 17.0-rc1 17.0-rc2 17.0 17.1 17.3 17.4 17.5 18.0
```

**Comment by BanzaiMan** [comment]
Sorry, but it is not pre-installed yet on the Erlang image.

**Comment by lpgauth** [comment]
17.5 would also be nice.

**Comment by tsloughter** [comment]
+1 to 17.5 and 18.0 :)

**Comment by BanzaiMan** [comment]
While we wait for the Erlang image with 17.5 and 18.0 to arrive, I am working on an on-demand installation of these OTP Releases.

If you want to try, enable your repository on the staging environment (https://staging.travis-ci.org/profile), then simply add:

```yaml
language: erlang
otp_release:
  - 18.0
```

**Comment by BanzaiMan** [comment]
The on-demand installation has been deployed.

I'm closing this for now. We plan to pre-install 17.5 and 18.0 for the next build env update (unscheduled).

**Comment by lpgauth** [comment]
Looks good, thanks!
https://travis-ci.org/lpgauth/marina/jobs/69926583

**Comment by tsloughter** [comment]
This worked this morning but suddenly it is failing to get 18 and 17.5 again, testing with rebar/rebar3.

**Comment by tsloughter** [comment]
Nevermind, it works :). I oddly was sent to staging travis-ci from github page and there it was failing...
