### ISSUE TITLE
APT source whitelist request for ppa:ubuntugis/ubuntugis-unstable

### ISSUE THREAD

**Issue by nyalldawson** [travis-ci/travis-ci#4166]
ppa:ubuntugis/ubuntugis-unstable

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:ubuntugis/ubuntugis-unstable' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:ubuntugis/ubuntugis-unstable' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/38.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
