### ISSUE TITLE
APT source whitelist request for ppa:smspillaz/cmake-3.0.2

### ISSUE THREAD

**Issue by nyalldawson** [travis-ci/travis-ci#4167]
We require a cmake version >= 3.0, which is available at:

ppa:smspillaz/cmake-3.0.2

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:smspillaz/cmake-3.0.2' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:smspillaz/cmake-3.0.2' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/39.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
