### ISSUE TITLE
APT source whitelist request for ppa:kedazo/doxygen-updates-precise

### ISSUE THREAD

**Issue by nyalldawson** [travis-ci/travis-ci#4168]
Includes a newer doxygen version (1.8.8):

ppa:kedazo/doxygen-updates-precise

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:kedazo/doxygen-updates-precise' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:kedazo/doxygen-updates-precise' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/40.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
