### ISSUE TITLE
Apt whitelist request for stack

### ISSUE THREAD

**Issue by mboes** [travis-ci/travis-ci#4169]
[stack](https://github.com/commercialhaskell/stack) is a new build tool for Haskell projects, similar to `cabal-install`, actively maintained and actively developed by the Commercial Haskell SIG. stack is stable software and used by a number of projects together with Travis CI.

* deb http://download.fpcomplete.com/ubuntu/vivid stable main
* deb http://download.fpcomplete.com/ubuntu/utopic stable main 
* deb http://download.fpcomplete.com/ubuntu/trusty stable main 
* deb http://download.fpcomplete.com/ubuntu/precise stable main

Repos signed using the FP Complete key, available here:

* https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key

Package name: `stack`.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'Haskell stack' needs source whitelisting

**Comment by mboes** [comment]
cc @snoyberg.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'Haskell stack' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'Apt whitelist request for Haskell stack' is ambiguous. Please specify only one.

**Comment by mboes** [comment]
@BanzaiMan could you tell me more about what's ambiguous? I updated the title to specify the name of the package in the title along with the title of the project as listed in its Github project page. But not sure if this is what you meant?

**Comment by BanzaiMan** [comment]
@mboes We are in the process of automating APT whitelist request processing. The process expects to find exactly one package name (no space, no colons) in the request title. This one also requires source whitelisting; it will have to be approved in https://github.com/travis-ci/apt-source-whitelist first before we can run tests.

I hope that makes it clear. Thanks.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/379.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
