### ISSUE TITLE
Build statuses reported twice to GitHub

### ISSUE THREAD

**Issue by byroot** [travis-ci/travis-ci#4176]
Something weird is happening to https://github.com/rubygems/rubygems.org on at least the last 4 commits on master.

It appear like if the same build was enqueued multiple times concurrently.

For example https://github.com/rubygems/rubygems.org/commit/09bc5ec42204e31d67085962a9d81778fab85ac8 you can see via the status api https://api.github.com/repos/rubygems/rubygems.org/commits/09bc5ec42204e31d67085962a9d81778fab85ac8/statuses that the reported status timeline make very little sense. First the *11 statuses* point to the same build id, and then the multiple pending statuses are reported consecutively.

**Comment by BanzaiMan** [comment]
The [build in question](https://travis-ci.org/rubygems/rubygems.org/builds/69292376) has 6 jobs. We send notifications to GitHub when build's status changes. For example, when we receive a build request, we set the status to "pending"; when a job finishes, it is set to something appropriate ("error", "success"), and so on. If you restart a job, there would be more.

In our logs, I see 11 such events for this build, corresponding to the statuses returned from the GitHub API.

**Comment by joshk** [comment]
@BanzaiMan you are correct, but I think you are a little mistaken, we send status updates for Build events, and not job events.

11 is too many, and I am not sure why we sent an error event when the errored job in in the allow failures block.

This is a bug.

**Comment by roidrage** [comment]
Possibly related to their use of fast_finish? https://github.com/rubygems/rubygems.org/blob/master/.travis.yml#L41-L46

**Comment by BanzaiMan** [comment]
@roidrage Ah. Sounds like a plausible explanation.

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #1696.
