### ISSUE TITLE
APT whitelist request for texlive-lang-cjk

### ISSUE THREAD

**Issue by Constellation** [travis-ci/travis-ci#4180]

**Comment by BanzaiMan** [comment]
This package does not exist for Precise. http://packages.ubuntu.com/precise/texlive-lang-cjk

**Comment by BanzaiMan** [comment]
Did not run automated check because 'texlive-lang-cjk' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because 'texlive-lang-cjk' needs trusty

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/380.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
