### ISSUE TITLE
Job stuck in building for weeks

### ISSUE THREAD

**Issue by chemdrew** [travis-ci/travis-ci#4182]
https://travis-ci.org/chemdrew/object-tie

is stuck in a building status and won't allow me to run any new tests on commits or manually. Can I at least get this job reset so I can run tests? Thanks

**Comment by joshk** [comment]
Hi @chemdrew 

I'm sorry for our delayed reply.

I have restarted the job manually. We are working on some improvements to our build state updating component.

Have a great day, and sorry for the issues

Josh
