### ISSUE TITLE
priority of execution environments

### ISSUE THREAD

**Issue by Ma27** [travis-ci/travis-ci#4183]
hey there,

one my build system, I have the version 5.5, 5.6 and 7-dev. ON php5.5 I generate a coverage report using phpunit: https://github.com/Ma27/SenNetwork/blob/master/.travis.yml.
Scrutinizer waits for that report and after a specific time it aborts the analysis.
As you can see, this analysis fails extremly often, I usually retry it manually in order to get a proper report.

But is there a way to automate this. Is it possible to say, that php5.5 MUST be executed first in order to send the coverage report??

Thank you.

**Comment by joshk** [comment]
Hi @Ma27 

Could you link us to some builds which you mention fail extremely often.

Are your other builds relying on PHP 5.5 sending this coverage report? If so, is there a way to remove this requirement?

I'm sorry but there is currently no way to say 'PHP 5.5 must be executed first, then the others can be run'

Thanks

**Comment by Ma27** [comment]
well, as you understood, I'd like to execute the php 5.5 environment first, but if this is impossible, there's no way to fix it now.
