### ISSUE TITLE
Job not restarting

### ISSUE THREAD

**Issue by beefcurtains** [travis-ci/travis-ci#4186]
[This job is running for more than 24 hours.](https://travis-ci.org/voidlinux/void-packages/jobs/69347689) At the bottom of the log, it says:
```
[mThere was an error with the connection to the VM.

Your job will be requeued shortly.
```
It has yet to do that. What gives?

**Comment by BanzaiMan** [comment]
That is strange. Could you try canceling and restarting?

**Comment by beefcurtains** [comment]
I have no control over that job.

**Comment by BanzaiMan** [comment]
Could you ask someone who does?

**Comment by joshk** [comment]
Hiro, can you please check papertrial logs to see what might have happened?




And then can you use a console to set the job status to created (it will be restarted)

**Comment by beefcurtains** [comment]
Am I expected to do something?

**Comment by joshk** [comment]
@beefcurtains sorry, no, not yet, we will look into this on Monday.

cc. @BanzaiMan

**Comment by beefcurtains** [comment]
Thank you! :purple_heart:

**Comment by BanzaiMan** [comment]
The job started on worker-linux-docker-a93b8a40, but the worker just seems to have disappeared. Papertrail doesn't seem to offer much in the way of explanation.

**Comment by BanzaiMan** [comment]
OK. The job finished in an error.
