### ISSUE TITLE
should output the log as the command goes when using travis_wait

### ISSUE THREAD

**Issue by Da-Huang** [travis-ci/travis-ci#4190]
When `travis_wait` is added as prefix, the log should be output as the command goes, instead of after it finishes.

**Comment by BanzaiMan** [comment]
Sorry, that is how the function is implemented right now. If you have suggestions for improvement, you can look at the code here: https://github.com/travis-ci/travis-build/blob/68cdaaf2cfcad54671c3b5896cd867e21a63c737/lib/travis/build/templates/header.sh#L108-145

**Comment by joshk** [comment]
Hi @Da-Huang 

Thanks for your suggestion.

As @BanzaiMan suggested, we are happy to take PRs to improve this. I'm going to close this issue for now as we can discuss any changes within the PR.

Thanks a bundle

Josh

**Comment by evilaliv3** [comment]
@Da-Huang enjoy the following solution:

```bash
  long-living-command & # send the long living command to background!

  minutes=0
  limit=30
  while kill -0 $! >/dev/null 2>&1; do
    echo -n -e " \b" # never leave evidences!

    if [ $minutes == $limit ]; then
      break;
    fi

    minutes=$((minutes+1))

    sleep 60
  done
```

**Comment by Da-Huang** [comment]
Wow, cool! Thanks, @evilaliv3

**Comment by abitrolly** [comment]
I replaced `travis_wait` with this
```
 install:
    # Output something every 10 minutes or Travis kills the job
    - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
    - long-living-command
    # Killing background sleep loop
    - kill %1
```

**Comment by Gama11** [comment]
Thanks @abitrolly, that works perfectly. 👍 I ran into some issues with OSX jobs though, it looks like "minutes" / the `m` is just ignored by the `sleep` command there, meaning the keep-alive-output is printed every 9 _seconds_. Replacing `sleep 9m` with `sleep 540` fixes that (and still works fine on Linux).

**Comment by kinow** [comment]
I used the workaround mentioned above, and got the console output, and the build timed out correctly. But a co-worker, when reviewing the code, suggested a simpler approach, using the GNU [`timeout`](http://www.gnu.org/software/coreutils/manual/coreutils.html#timeout-invocation).

The behaviour is the same, but with a single line. Just in case someone else needs similar thing, `travis_wait` is still not printing the output, and you need to do the same :grimacing: 

And sorry for commenting and reviving an old & closed ticket.

Cheers
Bruno
