### ISSUE TITLE
Error 137 - Killed

### ISSUE THREAD

**Issue by benilton** [travis-ci/travis-ci#4192]
@craigcitro, @eddelbuettel, @hadley et. al.,

I trying to get my oligo package working with Travis CI. My commit ce8b36cfd3fcfb98871faf37cf1f2cafab095643 worked fine "by accident", but now I get the error below:

```
** testing if installed package can be loaded
/home/travis/build.sh: line 41: 25432 Killed                  Rscript -e 'source("http://bioconductor.org/biocLite.R"); options(repos=biocinstallRepos()); biocLite(c("BiocGenerics", "oligoClasses", "Biobase", "Biostrings", "affyio", "affxparser", "preprocessCore", "zlibbioc", "BSgenome.Hsapiens.UCSC.hg18", "hapmap100kxba", "pd.hg.u95av2", "pd.mapping50k.xba240", "pd.huex.1.0.st.v2", "pd.hg18.60mer.expr", "pd.hugene.1.0.st.v1", "maqcExpression4plex", "genefilter", "limma", "RColorBrewer", "oligoData", "BiocStyle", "ACME", "biomaRt", "AnnotationDbi", "GenomeGraphs")); if (!all(c("BiocGenerics", "oligoClasses", "Biobase", "Biostrings", "affyio", "affxparser", "preprocessCore", "zlibbioc", "BSgenome.Hsapiens.UCSC.hg18", "hapmap100kxba", "pd.hg.u95av2", "pd.mapping50k.xba240", "pd.huex.1.0.st.v2", "pd.hg18.60mer.expr", "pd.hugene.1.0.st.v1", "maqcExpression4plex", "genefilter", "limma", "RColorBrewer", "oligoData", "BiocStyle", "ACME", "biomaRt", "AnnotationDbi", "GenomeGraphs") %in% installed.packages())) {  q(status = 1, save = "no") }'

The command "Rscript -e 'source("http://bioconductor.org/biocLite.R"); options(repos=biocinstallRepos()); biocLite(c("BiocGenerics", "oligoClasses", "Biobase", "Biostrings", "affyio", "affxparser", "preprocessCore", "zlibbioc", "BSgenome.Hsapiens.UCSC.hg18", "hapmap100kxba", "pd.hg.u95av2", "pd.mapping50k.xba240", "pd.huex.1.0.st.v2", "pd.hg18.60mer.expr", "pd.hugene.1.0.st.v1", "maqcExpression4plex", "genefilter", "limma", "RColorBrewer", "oligoData", "BiocStyle", "ACME", "biomaRt", "AnnotationDbi", "GenomeGraphs")); if (!all(c("BiocGenerics", "oligoClasses", "Biobase", "Biostrings", "affyio", "affxparser", "preprocessCore", "zlibbioc", "BSgenome.Hsapiens.UCSC.hg18", "hapmap100kxba", "pd.hg.u95av2", "pd.mapping50k.xba240", "pd.huex.1.0.st.v2", "pd.hg18.60mer.expr", "pd.hugene.1.0.st.v1", "maqcExpression4plex", "genefilter", "limma", "RColorBrewer", "oligoData", "BiocStyle", "ACME", "biomaRt", "AnnotationDbi", "GenomeGraphs") %in% installed.packages())) {  q(status = 1, save = "no") }'" failed and exited with 137 during .
```

I understand that errors with the keyword "Killed" are often associated with exceeding a RAM threshold. But here, I don't see how I could be exceeding this possible limit (given that it's only biocLite() running). I also looked for other errors during the build process, but couldn't find any...

Any thoughts on how to address this?

Thank you very much,

**Comment by craigcitro** [comment]
i believe the exit code of 137 suggests something did a `kill -9` on the parent, i.e. the travis build script itself.

@BanzaiMan any way to find out why a build like [this one](https://travis-ci.org/benilton/oligo/builds/69591179) was killed?

**Comment by BanzaiMan** [comment]
The most likely cause is running out of memory. This does not necessarily mean that the job in question is exhausting resources, but that the host the job is running on did. The best defense still is to reduce memory usage of the job in question. I am not sure, though, how we can gauge the R job's memory usage.

**Comment by benilton** [comment]
The problem is that all that the biocLite() call is doing is installing the package dependencies.... really can't think how to reduce memory usage.... thanks though

**Comment by bilderbuchi** [comment]
I get the same issues sometimes when unpacking Android NDKs during the build. I guess it happens about 30-50% of the time (e.g. in one build, [this one](https://travis-ci.org/openframeworks/openFrameworks/jobs/72422259) worked, but [that one](https://travis-ci.org/openframeworks/openFrameworks/jobs/72422261) didn't), build restarting often works. 
I have already whittled down the extracted size to about 1/3 (<1GB). I have asked 7z to only use one thread with  `-mmt=1` to reduce memory consumption, but I'm not sure if this gets picked up as pzip [talks about](https://travis-ci.org/openframeworks/openFrameworks/jobs/72422261#L148) seeing 32 CPUs! (maybe that causes issues?)
Is there a way to get more information about why this fails, beyond "error 137"? What is the bottleneck? CPU? disk? our memory usage? memory usage of other builds? (why would _that_ lead to our build being killed anyway?)

**Comment by bilderbuchi** [comment]
BTW, is it possible to only have some of the elements in a multi-OS matrix build to run with `sudo: false`? We have some builds which need sudo, but others (like the Android ones) where I could see getting rid of sudo, but putting `sudo: false` in a `matrix` section does not validate. @BanzaiMan ?

**Comment by kenorb** [comment]
Got the same issue. I'm running my Python script and it got killed after few minutes of run. See this [build](https://travis-ci.org/EA31337/FX-MT-VM/builds/93843086) or [this](https://travis-ci.org/EA31337/FX-MT-VM/builds/93841476) one as example.

**Comment by kenorb** [comment]
I think the workaround is to increase the stack size by adding:

    ulimit -s 1082768  # Require a bit of more memory.

then check/monitor your memory by:`ulimit -a`/`free -m`. Especially when you compiling something.

In my case I needed much more memory than that, therefore I had to rewrite my Python script to do some stuff in chunks and it helped.

**Comment by guyzmo** [comment]
I'm hitting this issue when running my test suite against [python 3.6-dev](https://travis-ci.org/guyzmo/git-repo/jobs/167974293#L374) and against [python nightly (3.7-dev)](https://travis-ci.org/guyzmo/git-repo/jobs/167974294#L374).

I've marked this tests as *allowed failure*, so it's not a major issue for me yet… But when python3.6 will become the stable version, I'd be releaved to have it actually fail loudly in case of problems!

**Comment by BanzaiMan** [comment]
Closing, as it's become stale.

**Comment by cxbrooks** [comment]
Interestingly, if one uses the coreutils timeout executable to kill -9 a process, then the return code of the killed process would be 137.  

https://www.gnu.org/software/coreutils/manual/html_node/timeout-invocation.html  says:

```
Exit status:

124 if command times out
125 if timeout itself fails
126 if command is found but cannot be invoked
127 if command cannot be found
137 if command is sent the KILL(9) signal (128+9)
the exit status of command otherwise
```

My [icyphy/ptII travis job](https://travis-ci.org/icyphy/ptII/jobs/372695413) was returning 137 from ant.  /var/log/syslog and dmesg said nothing.  My [.travis.yml](https://github.com/icyphy/ptII/blob/master/.travis.yml) file invokes a script that places the more than 10K lines of output into a log file and has a wait loop that generates messages every one minute so that Travis knows the script is alive.  I modified the wait loop to invoke ```free -m``` every minute and, indeed, memory was fine:

```yaml
  # travis_wait does not help here because we want to redirect the output of cmake.
  # See https://github.com/travis-ci/travis-ci/issues/4190

  # Echo status messages so that Travis knows we are alive
  - while sleep 1m; do echo "=====[ $SECONDS seconds still running ]====="; free -m; done &

  - echo "About to call ptIITravisBuild.sh at $SECONDS seconds."

  - $PTII/bin/ptIITravisBuild.sh $SECONDS

  - echo "Done with ptIITravisBuild.sh at $SECONDS seconds."

  # Killing background sleep loop.
  - kill %1
```

Inside [$PTII/bin/ptIITravisBuild.sh](https://github.com/icyphy/ptII/blob/master/bin/ptIITravisBuild.sh), I invoke the coreutils ```timeout``` command  with ```timeout -s 9```, which was returning 137!

So, if you are getting a 137 return code, also consider the possibility that your command is getting a kill -9.  Using wait() in your .travis.yml file is one way to diagnose a possible memory problem.
