### ISSUE TITLE
My repos aren't showing in my travis-ci profile

### ISSUE THREAD

**Issue by FavioVazquez** [travis-ci/travis-ci#4193]
Hello, I'm having some troubles setting up travis-ci to my repos because my profile has been "Syncing from GitHub" for the last 2 hours. It just recognized 4 of my repositories (I have like 40), and when I logged out, and then login again it said "Just a few more seconds as we talk to GitHub to find out which repositories belong to you" and that has been going on for like an hour. I don't know what to do by now. If you please could give some advise I'll appreciate it.

Some images

![travis1](https://cloud.githubusercontent.com/assets/10162068/8513341/17b8d722-2331-11e5-8d10-2a77959c160f.PNG)

------------------------
------------------------
------------------------

![travis2](https://cloud.githubusercontent.com/assets/10162068/8513342/17f97a52-2331-11e5-90d6-b9607be4d482.PNG)

**Comment by joshk** [comment]
Hi @FavioVazquez 

Sorry for the issue, I have fixed your sync manually. We are also in the process of deploying some changes to improve this issue you ran into.

Have a great day

**Comment by FavioVazquez** [comment]
Thanks @joshk!
