### ISSUE TITLE
secure env vars are sometimes not decoded (even when PR is from an origin/branch)

### ISSUE THREAD

**Issue by vvo** [travis-ci/travis-ci#4196]
We had issues lately of secure env vars being sometimes not decoded:

Take this build:
- failed build: https://travis-ci.org/algolia/algoliasearch-helper-js/builds/69885191
- corresponding travis.yml: https://github.com/algolia/algoliasearch-helper-js/blob/8f387f9ed57d32bb0d0327766d49d3c3abd31996/.travis.yml

[Log says](https://s3.amazonaws.com/archive.travis-ci.org/jobs/69885192/log.txt):

```txt
[33;1mSetting environment variables from .travis.yml[0m
$ export SAUCE_USERNAME=as-helper-js
```
Now the same travis.yml resulting in decoding of the env vars (when merged on develop branch):

- green build: https://travis-ci.org/algolia/algoliasearch-helper-js/builds/69885497
- corresponding travis.yml: https://github.com/algolia/algoliasearch-helper-js/blob/f9a3440531e12dac3ee779c65a85ad0e14ecfc4c/.travis.yml

[Log says](https://s3.amazonaws.com/archive.travis-ci.org/jobs/69885498/log.txt):

```txt
[33;1mSetting environment variables from .travis.yml[0m
$ export SAUCE_USERNAME=as-helper-js
$ export SAUCE_ACCESS_KEY=[secure]
$ export INTEGRATION_TEST_API_KEY=[secure]
$ export INTEGRATION_TEST_APPID=[secure]
```

Showing that env vars where decoded. So what's the issue here?

It seems to be present since we switched to `sudo: false`, not sure.

**Comment by BanzaiMan** [comment]
We have received a few reports of this kind. We are investigating.

**Comment by BanzaiMan** [comment]
The issue has been identified and fixed. I'm closing this optimistically, but if you see problems, do let us know.

**Comment by vvo** [comment]
thanks a lot for quick answer and fix
