### ISSUE TITLE
Concurrent jobs

### ISSUE THREAD

**Issue by yagop** [travis-ci/travis-ci#4199]
I've set `Concurrent jobs` as 1, however all the jobs (5) are running at the same time.

![captura de pantalla de 2015-07-07 22 41 27](https://cloud.githubusercontent.com/assets/5002453/8556772/768a43ca-24f9-11e5-9363-63376023697d.png)
![captura de pantalla de 2015-07-07 22 42 21](https://cloud.githubusercontent.com/assets/5002453/8556773/7692e6f6-24f9-11e5-8335-29ab05ca56d5.png)

Last time (hours ago) was working.

**Comment by BanzaiMan** [comment]
Sorry to hear about this issue. Which repository are you seeing this?

**Comment by yagop** [comment]
https://travis-ci.org/yagop/node-telegram-bot-api

**Comment by svenfuchs** [comment]
@yagop sorry about the troubles. i have just pushed a fix and it seems to work as expected on our staging environment again. could you please re-try to see if it works for you, too?

**Comment by yagop** [comment]
Working again, thanks a lot! 
By the way, I think the Concurrent jobs form pattern is wrong, should be written without `/`. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-pattern
http://www.html5rocks.com/en/tutorials/forms/html5forms/#toc-validation-constraint-attr

**Comment by svenfuchs** [comment]
@yagop thanks for checking!

you're right, there are a few things wrong with the UX on that view. our frontend team is working on a bunch of improvements atm.
