### ISSUE TITLE
coverity_scan addon exiting with 0 is still resulting in builds being marked as failed

### ISSUE THREAD

**Issue by solarce** [travis-ci/travis-ci#4201]
From support ticket: https://secure.helpscout.net/conversation/103069666/17689/

> The addon [downloads and executes](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/coverity_scan.rb#L78) a [build script](https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh) which checks our quota system, runs a build and uploads results to our servers. When the quota is not met, the script exists with a code of zero without running the build or uploading results. For some reason, this is still being reported as a build failure by Travis. I'm wondering, might you have any insight into why that would be?

> An example of this condition can be seen [here](https://travis-ci.org/aceofspades/Android-IMSI-Catcher-Detector/builds/69993183).

I am moving the discussion of this particular failure case to a GH issue

**Comment by aceofspades** [comment]
I believe https://github.com/travis-ci/travis-build/pull/471 should fix this issue

**Comment by BanzaiMan** [comment]
The PR has been merged and deployed.
