### ISSUE TITLE
Caching of custom folders works for the last folder in the list only

### ISSUE THREAD

**Issue by yeputons** [travis-ci/travis-ci#4203]
Example repo is <a href="https://github.com/Asana/travis-cache-check">here</a>
It has a very simple script, `doit.sh`, which checks that empty files `cache1/file` and `cache2/file` are presented. If they're not - it creates them. So, with caching first run should create these files and next runs should do nothing.

My Travis setup looks like this (included in the repo):
```
sudo: false
cache:
  directories:
    - cache1
    - cache2
script:
  - bash doit.sh
```
During the <a href="https://travis-ci.org/Asana/travis-cache-check/builds/70138328">first build</a> no cache was presented yet and my script successfully create files in both directories. However, after I re-run the build (like <a href="https://travis-ci.org/Asana/travis-cache-check/builds/70138481">this</a>), it shows that only content of `cache2` was actually cached, because `cache1/file` is absent, while `cache2/file` is here.

I think it's a problem with changes detection and cache updating, because second build tells that `/home/travis/build/Asana/travis-cache-check/cache1 is not yet cached` (and nothing similar for `cache2`). Also, when I ran it in a private repository, size of the cache looked like size of last directory cached, not size of all directories combined.

**Comment by BanzaiMan** [comment]
Sorry to hear about the issue, but https://travis-ci.org/Asana/travis-cache-check/builds doesn't have any build. Do you have a build URL that shows the problem?

**Comment by BanzaiMan** [comment]
OK. I ran an experiment of my own, and confirmed this issue.

**Comment by yeputons** [comment]
@BanzaiMan I was testing it when it were private repo. Added public builds to my initial message as well

**Comment by BanzaiMan** [comment]
@yeputons Hi, there. I've pushed a fix to production. Do let us know if you continue to see problems. Thank you!

**Comment by edmorley** [comment]
Working great for me - thank you :-)

**Comment by BanzaiMan** [comment]
@edmorley Great to hear!

**Comment by yeputons** [comment]
I've removed the original repository and moved its content to a <a href="https://gist.github.com/yeputons/2d3320b923c133c48e5d">gist</a>. Hope that's ok and the issue is already resolved.

**Comment by BanzaiMan** [comment]
@yeputons No worries. Thanks for checking in.
