### ISSUE TITLE
npm deployments made with Node.js 0.11.16 fail

### ISSUE THREAD

**Issue by astorije** [travis-ci/travis-ci#4205]
Because of [this](https://github.com/npm/npm/issues/8822#issuecomment-119431682), the automatic deployments to npm started by Node.js 0.11 will always fail: Node.js 0.11.16 is a known bad version.

Would it be possible to deactivate the deployment for Node 0.11 (until it's fixed there)? [One of my packages defines versions 0.10 to 0.12](https://github.com/astorije/chai-immutable/blob/a5b6b465a6ddf79b5dd9479d79b9e821d0588a7c/.travis.yml#L4) and every time the 0.11 build will finish first, the deployed package will be borken (invalid checksum at `npm install`).

**Comment by BanzaiMan** [comment]
If you have a build matrix, it is not a good idea to deploy from all jobs in the matrix. Use conditional deployment instead.

```yaml
deploy:
  provider: npm
  on:
    node: '0.10'
```

Dealing with a bad release of a frequently-released language like Node.js from our end is a bad idea in my opinion. When the fix is released the deployment will be disabled until the fix from our side is.

**Comment by astorije** [comment]
Indeed, I missed [this part of the doc](http://docs.travis-ci.com/user/deployment/npm/#Conditional-releases)!

Since version 0.11 has been made obsolete by version 0.12, I'm gonna remove it anyway, and add this condition on 0.12 in my config file. Thanks!

But still, it means that anyone trying to deploy with version 0.11 will have an invalid package, maybe it's worth adding a note in the doc?

**Comment by BanzaiMan** [comment]
I tend to think that if the user is using the development branch 0.11.x to deploy, they know what they are doing.

**Comment by astorije** [comment]
Fair enough, closing the issue then.
