### ISSUE TITLE
APT source whitelist request for ppa:terry.guo/gcc-arm-embedded

### ISSUE THREAD

**Issue by farcaller** [travis-ci/travis-ci#4208]
We require gcc-arm-none-eabi available through ppa:terry.guo/gcc-arm-embedded.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:terry.guo/gcc-arm-embedded' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:terry.guo/gcc-arm-embedded' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/41.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
