### ISSUE TITLE
APT source whitelist request for ppa:vala-team/ppa

### ISSUE THREAD

**Issue by arteymix** [travis-ci/travis-ci#4212]
Here it is: https://launchpad.net/~vala-team/+archive/ubuntu/ppa

By the same time, it would be great to whitelist the following packages provided by the repository:

 - vala (and specific versions like vala-0.28)
 - libgee-0.8
 - valadoc

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:vala-team/ppa' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:vala-team/ppa' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/42.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
