### ISSUE TITLE
APT package whitelist request for libsoup2.4-1 and libctpl2

### ISSUE THREAD

**Issue by arteymix** [travis-ci/travis-ci#4213]
These two packages are used to build [Valum](https://github.com/valum-framework/valum).

 - libsoup-2.4 offers a nice HTTP stack (client, server, websockets, ...)
 - libctpl is a very basic templating library.

**Comment by BanzaiMan** [comment]
Neither libsoup-2.4 nor libctpl does not exist for precise or trusty. http://packages.ubuntu.com/precise/libsoup-2.4 Where do you expect to find it?

**Comment by arteymix** [comment]
Both packages are registered:

 - http://packages.ubuntu.com/precise/libsoup2.4-1
 - http://packages.ubuntu.com/precise/libctpl2

For the `-dev` packages:

 - http://packages.ubuntu.com/precise/libsoup2.4-dev
 - http://packages.ubuntu.com/precise/libctpl-dev

**Comment by arteymix** [comment]
@BanzaiMan Thanks!
