### ISSUE TITLE
APT whitelist request for mongodb-org-server

### ISSUE THREAD

**Issue by wbthomason** [travis-ci/travis-ci#4214]
From http://downloads-distro.mongodb.org/repo/ubuntu-upstart/dists/dist/10gen/binary-amd64/.
The source is already permitted (alias 'mongodb-upstart') but the package is not yet in the whitelist; only mongodb-10gen is. Thanks!

**Comment by cchantep** [comment]
+1

**Comment by wbthomason** [comment]
@BanzaiMan Is there anything I can do to help with the process? Probably should’ve asked earlier.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'mongodb-org-server 2.6.6' needs source whitelisting

**Comment by wbthomason** [comment]
Ah, ok. I had thought that it was included as a part of the (already whitelisted) mongodb-upstart source.

**Comment by BanzaiMan** [comment]
I'll have to rerun the tests.

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for mongodb-org-server 2.6.6' is ambiguous. Please specify only one.

**Comment by wbthomason** [comment]
Sorry, I’m not quite sure I understand how it’s ambiguous. I was requesting that version 2.6.6 of the package mongodb-org-server, available in the mongoldb-upstart source (as shown here: http://downloads-distro.mongodb.org/repo/ubuntu-upstart/dists/dist/10gen/binary-amd64/), be whitelisted for installation. If that’s ambiguous, I’ll gladly do whatever is necessary to disambiguate it.

**Comment by BanzaiMan** [comment]
@gilesbowkett The automated process expects exactly one word (no spaces, no colons) in the place where `__PACKAGE__` place holder is. So, here, it is `mongodb-org-server 2.6.6`, so it was skipped.

**Comment by wbthomason** [comment]
Ah, alright. Thanks; sorry for the confusion.

**Comment by gilesbowkett** [comment]
typo, or am I just forgetful?

**Comment by BanzaiMan** [comment]
@gilesbowkett Sorry! My typo. Not sure how your user name came up.

**Comment by BanzaiMan** [comment]
Couldn't find source. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72216904#L434

We add `deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen` to the source (https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72216904#L312), so I'm not quite sure what's going on.

**Comment by wbthomason** [comment]
It appears to be trying to use `mongodb-org` as the source package rather than `mongodb-org-server`, which could be a problem (at least, I’m not sure why it made that choice). As well, it looks like it may not have successfully added `ubuntu-upstart` (https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72216904#L401).

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/381.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
