### ISSUE TITLE
APT source whitelist request for ppa:duggan/bats

### ISSUE THREAD

**Issue by jamesramsay** [travis-ci/travis-ci#4219]
Bats is nice tool for testing CLI interfaces: https://github.com/sstephenson/bats

**Comment by BanzaiMan** [comment]
It is simple to install via `git`, no? I'm not saying that this is a bad idea, but it is probably just as fast to install it to somewhere under `$HOME` (https://github.com/sstephenson/bats#installing-bats-from-source; and manipulate `$PATH`) as installing it via `apt`. Vetting a source will also take a little while.

**Comment by jamesramsay** [comment]
Good tip. I don't personally need this then. Happy to close and save you the effort of reviewing.
