### ISSUE TITLE
APT whitelist request for libdbus-1-dev, libgconf2-dev, libnss3-dev

### ISSUE THREAD

**Issue by zcbenz** [travis-ci/travis-ci#4222]
They are needed for building atom/electron.

**Comment by zcbenz** [comment]
Those libraries are actually already installed on the CI machine, we just need the development headers, so I think it won't affect the environment of CI machine.

**Comment by fxlb** [comment]
libdbus-1-dev is also need for a more complete build of libpcap. Thanks.

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for libdbus-1-dev, libgconf2-dev, libnss3-dev' is ambiguous. Please specify only one.

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for libdbus-1-dev, libgconf2-dev, libnss3-dev' is ambiguous. Please specify only one.

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for libdbus-1-dev, libgconf2-dev, libnss3-dev' is ambiguous. Please specify only one.

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for libdbus-1-dev, libgconf2-dev, libnss3-dev' is ambiguous. Please specify only one.

**Comment by abarth** [comment]
I broke this bug up into three separate bugs, one for each package.  Hopefully that will make the requests non-ambiguous.

**Comment by BanzaiMan** [comment]
@abarth Thanks! Closing this one.
