### ISSUE TITLE
APT whitelist request for cython

### ISSUE THREAD

**Issue by safl** [travis-ci/travis-ci#4226]

**Comment by BanzaiMan** [comment]
I think this includes directly mapped system calls in `Cython/Includes/posix/unistd.pxd`

```
    int          setegid(gid_t)
    int          seteuid(uid_t)
    int          setgid(gid_t)
    int          setpgid(pid_t, pid_t)
    pid_t        setpgrp()
    int          setregid(gid_t, gid_t)
    int          setreuid(uid_t, uid_t)
    pid_t        setsid()
    int          setuid(uid_t)
```

**Comment by BanzaiMan** [comment]
Not clear to me if we can allow this.

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
Re-run the tests, and found suspicious bits. Sorry for the mixup, but it will be reverted shortly. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206822

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/382.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
