### ISSUE TITLE
APT whitelist request for fglrx

### ISSUE THREAD

**Issue by safl** [travis-ci/travis-ci#4228]

**Comment by BanzaiMan** [comment]
The package includes many binary files, in which `set*id` strings are found. I cannot determine if this is safe to allow this.

**Comment by safl** [comment]
The fglrx[-dev] and opencl-headers allow users to test their OpenCL code running on the CPU.

**Comment by ntessore** [comment]
:+1:

**Comment by haahh** [comment]
:+1:

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71824976

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206809

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/383.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
