### ISSUE TITLE
APT whitelist request for fglrx-dev

### ISSUE THREAD

**Issue by safl** [travis-ci/travis-ci#4229]

**Comment by BanzaiMan** [comment]
See #4228. These files (http://packages.ubuntu.com/precise/amd64/fglrx-dev/filelist) don't have "set*id" strings, but I am not sure if they are useful without the binaries.

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71822478

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/384.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
