### ISSUE TITLE
APT whitelist request for python-docutils

### ISSUE THREAD

**Issue by safl** [travis-ci/travis-ci#4241]

**Comment by b4n** [comment]
Second that, would like it very much

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/390.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
