### ISSUE TITLE
APT whitelist request for python-pygments

### ISSUE THREAD

**Issue by safl** [travis-ci/travis-ci#4244]

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207655 found problems, but may be in the list of keywords to highlight. Needs further investigation.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/391.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
