### ISSUE TITLE
APT source whitelist request for ppa:v-launchpad-jochen-sprickerhof-de/pcl

### ISSUE THREAD

**Issue by kashefy** [travis-ci/travis-ci#4258]
deb source: ppa:v-launchpad-jochen-sprickerhof-de/pcl
For installing pre-built binaries for [Point Cloud Library](http://pointclouds.org/downloads/linux.html)

Thank you

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:v-launchpad-jochen-sprickerhof-de/pcl' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:v-launchpad-jochen-sprickerhof-de/pcl' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/43.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
