### ISSUE TITLE
APT source whitelist request for libreoffice

### ISSUE THREAD

**Issue by awead** [travis-ci/travis-ci#4259]
I'd like to add libreoffice on Travis's list of sources. We use it to test derivative file creation in Word and Excel documents. The PPA is `ppa:libreoffice/ppa` and the name of the package is just `libreoffice`. On Travis's old infrastructure, I'm doing:
```
add-apt-repository ppa:libreoffice/ppa
apt-get install libreoffice
```
but would like to take advantage of the new infrastructure with addons.

**Comment by wvengen** [comment]
:+1: I guess [libreoffice from universe](http://packages.ubuntu.com/trusty/libreoffice) would also be an option.

**Comment by awead** [comment]
Works for me!

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/75.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
