### ISSUE TITLE
virtualenv: system_site_packages: true breaks Python version not supported

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#4260]
Currently using system_site_packages: true causes jobs for versions other than Python 2.7 and 3.2 to fail, as it tries to use a virtualenv that doesnt exist (e.g. python3.3_with_system_site_packages).

``` bash
$ source ~/virtualenv/python3.3_with_system_site_packages/bin/activate
/home/travis/build.sh: line 41: /home/travis/virtualenv/python3.3_with_system_site_packages/bin/activate: No such file or directory
The command "source ~/virtualenv/python3.3_with_system_site_packages/bin/activate" failed and exited with 1 during .
```

https://travis-ci.org/jayvdb/pywikibot-core/jobs/70303024

It would be nice if travis-ci somehow supported this.  Some options that come to mind are:
1.  gracefully ignored virtualenv: system_site_packages: true if the Python version doesnt support it
2. allow virtualenv: system_site_packages: true to be specified within the version. e.g. `'2.7' virtualenv: system_site_packages: true`
3. deprecate 'virtualenv: system_site_packages: true' and document & support targets '2.7_with_system_site_packages' and '3.2_with_system_site_packages' , subject to the normal travis-ci policy of removing targets as required.

The workaround we are using is to specify a version of '2.7_with_system_site_packages'.
https://travis-ci.org/jayvdb/pywikibot-core/jobs/70366148

**Comment by BanzaiMan** [comment]
http://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs

@dstufft Opinions?

**Comment by dstufft** [comment]
I talked to @joshk about this when I reworked the cookbook. The fundamental problem is ``--with-system-site-packages`` is useless on anything but 2.7 and 3.2 (On Ubuntu Precise). You *could* create virtual environments that had it turned on for the other Python versions, but Ubuntu Precise didn't ship with them so you'd just be pointing at the versions installed into /opt/ instead of the apt-get packages. That makes it mostly useless since the only real reason to use ``--with-system-site-packages`` is because you want to be able to ``apt-get`` a Python package and import it.

This also means that once you move off Precise and onto Trusy it won't be 2.7 and 3.2 that have system site packages, but instead it'll be 2.7 and 3.4. Personally I'd just deprecate the feature, if people really need it they can manually deactivate the virtual environment that travis uses and create their own that uses site-packages.

**Comment by joshk** [comment]
Ok, so system site packages for 3.3 won't work due to precise, which makes sense. And I would have to agree with @dstufft here about deprecating this feature.

**Comment by jayvdb** [comment]
The reason I'd like to use --with-system-site-packages is to that we're doing a job with tests running against the version of python-requests & python-ipaddr that are shipped with precise, which is old & stable & is closer to what real users will typically see.  This has already uncovered one bug.

I could emulate that by installing specific versions using pip, but it means we need to keep a list of versions that 'precise' ships, and install them, which makes the builds take longer.

**Comment by phw** [comment]
AFAIK --with-system-site-packages is necessary for e.g. python-qt4, since that cannot be installed via PIP. Downloading and installing pyqt4 via other means than APT is surely possible but a major pain. So I would prefer the --with-system-site-packages option not to go away too soon.

**Comment by jayvdb** [comment]
I notice that the Trusty images fail when using `python: 3.4` with `virtualenv: system_site_packages: true` .

I hope this will be fixed in due course, but appreciate it is likely not to be near the top of the list for getting trusty images out of beta.

**Comment by m-kuhn** [comment]
Just for other people who might find it useful.

For a `dist: trusty` with `python-qt4` requirement we use this workaround to escape the virtualenv.

```
  - export PATH=/usr/bin:$PATH
```

It has a really bad kitten-factor but I couldn't think of a better solution.

**Comment by Midnighter** [comment]
@m-kuhn: I use the following code in `virtualenvwrapper`'s `postmkvirtualenv` script that links the necessary Qt components into the virtualenv:

```bash
libs=(PyQt4 sip.so sipconfig.py)

python_version=python$(python -c "import sys; print (str(sys.version_info[0])+'.'+str(sys.version_info[1]))")
var=( $(which -a ${python_version}) )

if [ ${#var[@]} -lt 2 ]; then
    echo "could not find system install of ${python_version}: unable to link PyQt components" >&2
else
    get_python_lib_cmd="from distutils.sysconfig import get_python_lib; print (get_python_lib())"
    lib_virtualenv_path=$(${var[0]} -c "${get_python_lib_cmd}")
    lib_system_path=$(${var[-1]} -c "${get_python_lib_cmd}")
    for lib in ${libs[@]}
    do
        if [[ -f "${lib_system_path}/${lib}" ]] && [[ ! -e "${lib_virtualenv_path}/${lib}" ]]; then
            ln -s "${lib_system_path}/${lib}" "${lib_virtualenv_path}/${lib}"
            echo "linked '${lib}' into virtualenv" >&2
        else
            echo "could not link to '${lib_system_path}/${lib}'" >&2
        fi
    done
fi
```

Maybe that's of help to you. You could create symlinks to the `virtualenv`'s `bin` directory as well.

**Comment by thorade** [comment]
There are many packages besides `python-qt4` that are easily installed via apt, but very cumberome to install otherwise. One of them is `omniORB` and `omniidl-python`. They seem to get installed into system python dist-packages, which means I always end up with `ImportError: No module named omniORB`.

**Comment by ensonic** [comment]
Another package that needs to be installed from the system is python3-dbus, it won't work from a virtualenv. So if you are deprecating the feature, please tell people how to replicate it for their builds. Please also understand that at least some percentage of people use it for a reason.

**Comment by bogdanap** [comment]
As mentioned in [the comment above](https://github.com/travis-ci/travis-ci/issues/4260#issuecomment-120405756) --system-site-packages will only be used with the default versions of Python in each Ubuntu distro, so this behaviour is expected - we will try to document it better to prevent further confusion.
As for deprecating the feature, we're not planning to do it anytime soon. 😄
