### ISSUE TITLE
APT source whitelist request for gazebo

### ISSUE THREAD

**Issue by traversaro** [travis-ci/travis-ci#4261]
This repository contains the latest version of the Gazebo robot simulator ( http://gazebosim.org/ ) and the Ignition Robotics libraries (http://ignitionrobotics.org/) a set of libraries for robotics applications. 

Deb source line: `deb http://packages.osrfoundation.org/gazebo/ubuntu precise main`
Key: `http://packages.osrfoundation.org/gazebo.key`

fyi : @j-rivero

**Comment by j-rivero** [comment]
Thanks @traversaro for starting this request. Any job that needs to be done in order to get OSRF repository whitelisted, please let me know.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'gazebo osrf repositories' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'gazebo osrf repositories' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT source whitelist request for gazebo osrf repositories' is ambiguous. Please specify only one.

**Comment by traversaro** [comment]
I modified the title. Is this ok?

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/44.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
