### ISSUE TITLE
APT whitelist request for libplack-perl

### ISSUE THREAD

**Issue by nichtich** [travis-ci/travis-ci#4262]
de-facto standard base for web applications and frameworks in Perl

**Comment by BanzaiMan** [comment]
Do you need this in a system package? If you are using the Perl image, you would not be using it, since each runtime will have to install Plack.

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71826988

**Comment by nichtich** [comment]
thanks!
