### ISSUE TITLE
APT source whitelist request for ppa:zoogie/sdl2-snapshots

### ISSUE THREAD

**Issue by startaq** [travis-ci/travis-ci#4263]
Contains SDL2 libraries.

https://launchpad.net/~zoogie/+archive/ubuntu/sdl2-snapshots

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:zoogie/sdl2-snapshots' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:zoogie/sdl2-snapshots' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/45.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
