### ISSUE TITLE
APT whitelist request for gcc-arm-linux-gnueabihf

### ISSUE THREAD

**Issue by GreyCat** [travis-ci/travis-ci#4269]
Required for cross building of software for ARM.

**Comment by GreyCat** [comment]
Somewhat related requests: #4092, #4208

**Comment by BanzaiMan** [comment]
Did not run automated check because 'gcc-arm-linux-gnueabihf' needs source whitelisting

**Comment by GreyCat** [comment]
Note that `gcc4.6-arm-linux-gnueabihf` is already whitelisted, and `gcc-arm-linux-gnueabihf` is just a trivial wrapper that provides symlinks which are slightly easier to use than calling binaries with weird names like `/usr/bin/gcc4.6-arm-linux-gnueabihf` instead of regular gcc cross-compiler.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'gcc-arm-linux-gnueabihf' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/400.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
