### ISSUE TITLE
APT whitelist request for libwxgtk3.0-dev, libwxgtk3.0-0

### ISSUE THREAD

**Issue by timw4mail** [travis-ci/travis-ci#4271]
My project [Tyro](https://github.com/timw4mail/Tyro) depends on wxWidgets 3.0.

**Comment by BanzaiMan** [comment]
This package does not exist for Precise. http://packages.ubuntu.com/precise/libwxgtk3.0-0

Could you help us find a PPA that has it for Precise?

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libwxgtk3.0-dev, libwxgtk3.0-0' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libwxgtk3.0-dev, libwxgtk3.0-0' needs trusty

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for libwxgtk3.0-dev, libwxgtk3.0-0' is ambiguous. Please specify only one.

**Comment by timw4mail** [comment]
Codelite has repos for precise: http://codelite.org/LiteEditor/WxWidgets30Binaries

**Comment by danilaml** [comment]
deb http://repos.codelite.org/wx3.0/ubuntu/ precise universe

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/417.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
