### ISSUE TITLE
APT source whitelist request for bsdowl

### ISSUE THREAD

**Issue by michipili** [travis-ci/travis-ci#4272]
Many of my projects depend on **bmake** and **bsdowl**.

WWW https://launchpad.net/~michipili/+archive/ubuntu/bsdowl

**Comment by BanzaiMan** [comment]
Did not run automated check because 'bsdowl' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'bsdowl' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'bsdowl' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'bsdowl' needs source whitelisting

**Comment by michipili** [comment]
@BanzaiMan What does this mean?  How can I help with this?

**Comment by BanzaiMan** [comment]
@michipili Sorry for the alarm. It's a comment generated by the script.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/52.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!

**Comment by michipili** [comment]
Nice, thanks!
