### ISSUE TITLE
APT whitelist request for wcslib-dev

### ISSUE THREAD

**Issue by dstndstn** [travis-ci/travis-ci#4274]
wcslib-dev is a library for astronomical coordinate transformations
(request is for https://github.com/dstndstn/astrometry.net)
thanks!

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71832500
