### ISSUE TITLE
APT source whitelist request for gcc/g++-4.9 in ppa:h-rayflood/gcc-upper

### ISSUE THREAD

**Issue by daveol** [travis-ci/travis-ci#4276]
- repository: [ppa:h-rayflood/gcc-upper](https://launchpad.net/~h-rayflood/+archive/ubuntu/gcc-upper)
- key: not needed is ppa based
- packages: g++-4.9 and gcc-4.9

**Comment by BanzaiMan** [comment]
Did not run automated check because 'gcc/g++-4.9 in ppa:h-rayflood/gcc-upper' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'gcc/g++-4.9 in ppa:h-rayflood/gcc-upper' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT source whitelist request for gcc/g++-4.9 in ppa:h-rayflood/gcc-upper' is ambiguous. Please specify only one.
