### ISSUE TITLE
APT source whitelist request for clang++/clang-3.6 in ppa:h-rayflood/llvm-upper

### ISSUE THREAD

**Issue by daveol** [travis-ci/travis-ci#4277]
- repository: [ppa:h-rayflood/llvm-upper](https://launchpad.net/~h-rayflood/+archive/ubuntu/llvm-upper)
- key: not needed is ppa based
- packages:  llvm-toolchain-3.6

**Comment by BanzaiMan** [comment]
Did not run automated check because 'clang++/clang-3.6 in ppa:h-rayflood/llvm-upper' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'clang++/clang-3.6 in ppa:h-rayflood/llvm-upper' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT source whitelist request for clang++/clang-3.6 in ppa:h-rayflood/llvm-upper' is ambiguous. Please specify only one.
