### ISSUE TITLE
APT whitelist request for intltool

### ISSUE THREAD

**Issue by b4n** [travis-ci/travis-ci#4278]
Many applications (including the one I try to port, obvly :) need `intltool` for internationalization of various extra files (notably UI and Desktop files).

FTR, while `intltool-debian` is already allowed, it's of no use as it's not actually providing any actual executable for the normal users.

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/418.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
