### ISSUE TITLE
APT source whitelist request for ppa:octave/stable

### ISSUE THREAD

**Issue by cbm755** [travis-ci/travis-ci#4279]
Required for testing Octave-based software (such as https://github.com/cbm755/octsympy, and https://github.com/catch22/octave-doctest).

Should be tagged `apt-source-whitelist` `apt-whitelist` but I don't see how to do so...

thanks

**Comment by jjgreen** [comment]
Would also be used by [maxmod-matlab](https://travis-ci.org/jjgreen/maxmod-matlab).

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:octave/stable, octave, liboctave-dev' needs source whitelisting

**Comment by cbm755** [comment]
@BanzaiMan I had labelled it `apt-source-whitelist`, was there something else I should do?

**Comment by BanzaiMan** [comment]
@cbm755 Well, that comment above came from a script that automates some of the required work. In particular, it checks if the ticket shows exactly on package to test before moving on to other things (like checking for the `apt-source-whitelist` label and moving on). So, please split this into 2 separate tickets (or change the subject to have one package and create a second one).

I hope that makes sense.

**Comment by cbm755** [comment]
I think so.  I renamed this just for the ppa and filed two new ones.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:octave/stable' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/53.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
