### ISSUE TITLE
APT whitelist request for rst2pdf

### ISSUE THREAD

**Issue by b4n** [travis-ci/travis-ci#4280]
Not as important as `docutils` (#4241), but would be good to have too.

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72129485 returned cleanly.
