### ISSUE TITLE
APT whitelist request for ppa:ondrej/mysql-5.6

### ISSUE THREAD

**Issue by austerus** [travis-ci/travis-ci#4281]
allows the instalation of mysq server & client version 5.6 (haven't seen a source for 5.6 whitelisted yet)

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:ondrej/mysql-5.6' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:ondrej/mysql-5.6' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/419.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
