### ISSUE TITLE
APT whitelist request for ppa:ondrej/php5-oldstable and all the packages it provides

### ISSUE THREAD

**Issue by untitaker** [travis-ci/travis-ci#4284]
It's currently impossible to get a recent PHP into a non-PHP build.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'ppa:ondrej/php5-oldstable and all the packages it provides' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT whitelist request for ppa:ondrej/php5-oldstable and all the packages it provides' is ambiguous. Please specify only one.

**Comment by untitaker** [comment]
https://github.com/travis-ci/travis-ci/issues/4529
