### ISSUE TITLE
APT whitelist request for haskell-platform

### ISSUE THREAD

**Issue by yihui** [travis-ci/travis-ci#4288]
to build Haskell packages

**Comment by BanzaiMan** [comment]
To confirm, you are not using the Haskell image? http://docs.travis-ci.com/user/languages/haskell/

**Comment by yihui** [comment]
For some reason, the Haskell image did not work well for me. I had some weird problems with `cabal install` (I was trying to build Pandoc from source), and `haskell-platform` was working well when I was using the old `sudo` approach. Thanks!

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.
