### ISSUE TITLE
APT whitelist request for equivs

### ISSUE THREAD

**Issue by yihui** [travis-ci/travis-ci#4289]
to build .deb packages

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
It's there now.

**Comment by yihui** [comment]
Many thanks!
