### ISSUE TITLE
APT source whitelist request for ppa:gijzelaar/opencv2.4

### ISSUE THREAD

**Issue by hainesr** [travis-ci/travis-ci#4293]
Allows the installation of OpenCV 2.4 into Ubuntu 12.04. There are significant changes in 2.4 that are not present in 2.3. A lot of projects will be using 2.4 now as it is available in Ubuntu 14.04 LTS.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/54.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
