### ISSUE TITLE
git issues during builds

### ISSUE THREAD

**Issue by Manu343726** [travis-ci/travis-ci#4294]
We are having git related issues on the ci builds of [ericniebler/meta](https://github.com/ericniebler/meta).

Some builds, like [this one](https://travis-ci.org/ericniebler/meta/jobs/70091013), errored after being unable to update submodules. (It's happening [on forks too](https://travis-ci.org/Manu343726/meta/jobs/70441741)).
Some others, like [this](https://travis-ci.org/ericniebler/meta), are run but the git repo is corrupted in some way that makes certain operations to fail. See for example [this warnings](https://travis-ci.org/ericniebler/meta/jobs/70087500#L582) after a `git clean -df` call prior to deploy. Note the behavior is a bit random, since some jobs of that builds run without problem.

See https://github.com/ericniebler/meta/issues/26

**Comment by BanzaiMan** [comment]
Am I correct to understand that this repo has itself for a git submodule? https://github.com/ericniebler/meta/commit/7ee4f976325d7e398433c2218e1dcda5802fee5d points to commit 1d69b6655759cc4779e6bd0f03222e9ff8a7beac, but that commit is not available for this repo (https://github.com/ericniebler/meta/commit/1d69b6655759cc4779e6bd0f03222e9ff8a7beac).

As for https://travis-ci.org/ericniebler/meta/jobs/70087500#L582, do you know what wrote to `libcxx`? Could it be this command (https://github.com/ericniebler/meta/blob/master/.travis.yml#L66) and the directory is owned by `root`? The jobs that fail are precisely the ones which have `$CLANG_VERSION` set, so I think this explanation is consistent.

If you want a more interactive environment to troubleshoot, we can spin up a debug VM for you. Please email support@travis-ci.com.

**Comment by ericniebler** [comment]
> ericniebler/meta@7ee4f97 points to commit 1d69b6655759cc4779e6bd0f03222e9ff8a7beac, but that commit is not available for this repo (ericniebler/meta@1d69b66).

Oh, that was the clue I needed. I has committed locally, updated the submodule reference, but forgot to push the updated docs to the gh-pages branch. So yes, the commit didn't exist, the submodule reference was invalid. I just pushed an everything should be better now.

Sorry for the noise.

**Comment by BanzaiMan** [comment]
There is nothing for us to do here. Closing.
