### ISSUE TITLE
APT source whitelist request for ppa:texlive-backports/ppa

### ISSUE THREAD

**Issue by davidsan** [travis-ci/travis-ci#4295]
`ppa:texlive-backports/ppa`

This allows the installation of a more recent version of TeX Live in Ubuntu 12.04 container.

https://launchpad.net/~texlive-backports/+archive/ubuntu/ppa

**Comment by zbeekman** [comment]
:+1: a million times

**Comment by zbeekman** [comment]
To elaborate more you need this to use any LaTeX features that are not ancient.

**Comment by nomeata** [comment]
:+1:

**Comment by pdiegmann** [comment]
Would be interested in it as well!

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/55.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
