### ISSUE TITLE
APT whitelist request for libdnet-dev

### ISSUE THREAD

**Issue by fxlb** [travis-ci/travis-ci#4296]
Needed for tcpdump project

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits.

Seehttps://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71878540

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/422.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
