### ISSUE TITLE
APT whitelist request for libcap-ng-dev

### ISSUE THREAD

**Issue by fxlb** [travis-ci/travis-ci#4298]
Needed for the tcpdump project

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits.

See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72216065.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72216065 found suspicious bits.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/423.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
