### ISSUE TITLE
cache: pip fails

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#4299]
Following the instructions on http://docs.travis-ci.com/user/caching/ , which says to just add "cache: pip" causes the following error

```
store build cache
changes detected, packing new archive
FAILED: tar -Pzcf /home/travis/.casher/push.tgz 
tar: Cowardly refusing to create an empty archive
Try `tar --help' or `tar --usage' for more information.
uploading archive
failed to upload cache
curl: Can't open '/home/travis/.casher/push.tgz'!
curl: try 'curl --help' or 'curl --manual' for more information
```
https://travis-ci.org/jayvdb/pywikibot-core/jobs/70479367#L3341

However following the example at https://github.com/nickstenning/travis-pip-cache/blob/master/.travis.yml works correctly
```
cache:
  directories:
    - $HOME/.cache/pip
```
https://travis-ci.org/jayvdb/pywikibot-core/builds/70514971

**Comment by BanzaiMan** [comment]
Hello. `cache: pip` did not work because you are overriding `install`. This is mentioned in http://docs.travis-ci.com/user/caching/#pip-cache:

```
If you have not overridden the default install step, use:
⋮
```

**Comment by jayvdb** [comment]
Hmm. Then it looks like a dup of issue #3239 , which has a lot of activity.  If `pip` is being used normally during the `install`, why shouldnt `cache: pip` work as expected?
