### ISSUE TITLE
APT whitelist request for libarmadillo-dev

### ISSUE THREAD

**Issue by njanetos** [travis-ci/travis-ci#4300]
Seems like it should be included since libarmadillo2 is already included.

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found an additional package.
