### ISSUE TITLE
Build does not finish

### ISSUE THREAD

**Issue by joetm** [travis-ci/travis-ci#4303]
After successfully completing the tests, the builds just keep running and eventually time out.
Example:
https://travis-ci.org/joetm/crowd-ui/builds/70539792

**Comment by BanzaiMan** [comment]
Looks like the latest build passed. Was something waiting for user input at the end of the test?

**Comment by joetm** [comment]
I checked again and it did not pass. The tests all succeed, but then the build just sits there and is terminated after some minutes.

**Comment by BanzaiMan** [comment]
Oh, I see. I "passed" because no tests ran.

If I clone the code and run `npm install` and `npm test`, the execution similarly hangs, so I tend to think this is an error with your tests.

**Comment by joetm** [comment]
I think it's related to the karma config setting:
    singleRun: false
That will continuously run karma and wait for changes of the files ("continuous integration mode").
Is there a way to watch for file changes but still successfully test on travis? Like overwriting the singleRun setting in the build?

**Comment by joetm** [comment]
I've set up a separate npm task in the package.json. Works fine now. Thanks.
