### ISSUE TITLE
Allow specification of different firefox versions in a test matrix

### ISSUE THREAD

**Issue by gggeek** [travis-ci/travis-ci#4305]
As far as I could tell, it is possible to tell Travis that a specific version of Firefox is needed, but only using the "plugin" configuration key.
What I'd like to have instead, is to be able to set up a test matrix, where the version of Firefox changes as one of the variables.

Maybe this is already possible and I just missed the information?

Thanks
Gaetano

**Comment by BanzaiMan** [comment]
Currently there is only one version of Firefox is installed in `/usr/local/bin/firefox`. Could you tell me where you got the impression that there were multiple versions?

We just download tarball from Mozilla and create a symlink to it in `/usr/local/bin`. (If you are familiar with Chef, look at the cookbook: https://github.com/travis-ci/travis-cookbooks/tree/master/ci_environment/firefox.)

If you want to test multiple versions, you can set up a build matrix:

```yaml
env:
  - FIREFOX_VERSION=1
  - FIREFOX_VERSION=2
```

then use `$FIREFOX_VERSION` in your `install` (or any other subsequent build phase) to download the version you want, expand it, and set up `$PATH` to invoke the desired version.

**Comment by Joshua-Anderson** [comment]
@BanzaiMan I think he was talking about [the Firefox add-on](http://docs.travis-ci.com/user/firefox/).

**Comment by gggeek** [comment]
Exactly.
I could write shell scripts to install a specific version, but given the existing add-on, I thought maybe I could reap the benefits without doing the hard work :-)

**Comment by BanzaiMan** [comment]
Addons are not supported in build matrix construction.

**Comment by joshk** [comment]
I'm sorry but we are not looking at adding matrix expansion to addons at this time. It might be something we revisit later, but I don't have an ETA on when that might be sorry.

Have an awesome weekend!
