### ISSUE TITLE
Travis does not update current build status after replacing old repo with transferred one

### ISSUE THREAD

**Issue by Yuhta** [travis-ci/travis-ci#4307]
1. I had a forked repo at https://github.com/Yuhta/netrc-rs and I hooked Travis CI with it.
2. Then I deleted this repo, accept the transfer from upstream repo and becomes the owner of it.
3. However, when I go to https://travis-ci.org/Yuhta/netrc-rs the current build status still shows the old forked repo instead of the transferred one.

**Comment by BanzaiMan** [comment]
I've resolved the conflict, and it now shows the correct status.
