### ISSUE TITLE
Build status not showing correctly

### ISSUE THREAD

**Issue by startaq** [travis-ci/travis-ci#4309]
https://travis-ci.org/mamedev/mame/

Our build status is never changing from "Build unknown" even though multiple builds pass. Also I can only view the builds when logged into Travis, it says "No builds for this repository" otherwise.

**Comment by BanzaiMan** [comment]
Hello. I've resolved the name conflict. Could you push a new build, and see if it shows up?

**Comment by startaq** [comment]
Thank you, it seems to work fine now.
