### ISSUE TITLE
APT whitelist request for sagemath-upstream-binary

### ISSUE THREAD

**Issue by isuruf** [travis-ci/travis-ci#4311]
`sagemath-upstream-binary` package from `ppa:aims/sagemath` 

This package is needed for [sympy](http://github.com/sympy/sympy) and [symengine](http://github.com/sympy/symengine)

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for sagemath-upstream-binary does not exist, or needs an APT source.

See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71944185.

**Comment by isuruf** [comment]
Package is available here, https://launchpad.net/~aims/+archive/ubuntu/sagemath from an APT source not whitelisted yet. Is it possible to whitelist the ppa?

**Comment by BanzaiMan** [comment]
@isuruf For that, you need https://github.com/travis-ci/apt-source-whitelist.

**Comment by isuruf** [comment]
Thanks

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/424.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
