### ISSUE TITLE
APT whitelist request for python-pandas

### ISSUE THREAD

**Issue by quentindemetz** [travis-ci/travis-ci#4313]

**Comment by quentindemetz** [comment]
I can't afford to wait for it to compile on a VM

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/401.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
