### ISSUE TITLE
APT whitelist request for libsvm-dev

### ISSUE THREAD

**Issue by njam** [travis-ci/travis-ci#4315]

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found additional packages. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72172373
