### ISSUE TITLE
APT whitelist request for re2c

### ISSUE THREAD

**Issue by njam** [travis-ci/travis-ci#4316]

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71832658

**Comment by BanzaiMan** [comment]
Duplicate of #4225.

**Comment by njam** [comment]
Ups, thought I looked for it. Sorry!
