### ISSUE TITLE
Inconsistent build timeout and failure

### ISSUE THREAD

**Issue by zankich** [travis-ci/travis-ci#4317]
Hello!

For some reason our builds will inconsistently stall and eventually be killed due to long run times.

In this [build](https://travis-ci.org/hybridgroup/gobot/builds/70632977), you can see that one of the builds succeeded, but the other builds stall at different parts of the build process.

https://travis-ci.org/hybridgroup/gobot/jobs/70632980#L650
https://travis-ci.org/hybridgroup/gobot/jobs/70632978#L658

Do you have you have any advice or insights into why it might be failing?

Thanks for all the hard work and a great service!

**Comment by BanzaiMan** [comment]
Hello, Serious Programmer Adrian! I am sorry to say, but I am not sure why jobs sometimes stall. If you would like a debug VM, we are happy to spin one up for you. Please email support@travis-ci.com.

**Comment by zankich** [comment]
@BanzaiMan I just sent an email, thanks!

**Comment by joshk** [comment]
Hi @zankich 

I did have one small question, are your tests running in a random order or is the order consistent?

Thanks a bundle

**Comment by zankich** [comment]
@joshk the order is consistent

**Comment by joshk** [comment]
I created https://github.com/hybridgroup/gobot/pull/212 to see if this helps at all
