### ISSUE TITLE
APT whitelist request for libxvidcore4 / libxvidcore-dev

### ISSUE THREAD

**Issue by DrMcCoy** [travis-ci/travis-ci#4319]
I'd need that for [xoreos](https://github.com/xoreos/xoreos).

Thanks.

**Comment by BanzaiMan** [comment]
`libxvidcore4 / libxvidcore-dev` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)
