### ISSUE TITLE
APT source whitelist request for beanstalkd

### ISSUE THREAD

**Issue by xiphiaz** [travis-ci/travis-ci#4320]
Beanstalkd is a simple fast queue. It can be installed on ubuntu with `sudo apt-get install beanstalkd`

See https://github.com/spira/spira/pull/79/files, it is failing when `beanstalkd` is tried to be used - 
See https://travis-ci.org/spira/spira#L1297

**Comment by petri** [comment]
+1, pretty please. I hope to use travis for running pybeanstalk tests.

**Comment by catwell** [comment]
+1, I also use it in [haricot](https://github.com/catwell/haricot) (Lua client) tests.

**Comment by xiphiaz** [comment]
@BanzaiMan what is the meaning of the two labels `apt-source-whitelist` & `apt-whitelist` ? Is there something blocking beanstalkd being whitelisted?

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/47.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
