### ISSUE TITLE
APT whitelist request for cppcheck

### ISSUE THREAD

**Issue by mckelvin** [travis-ci/travis-ci#4321]
It's required by https://github.com/douban/libmc/blob/master/.travis.yml#L19

I met the issue while migrating from legacy to container-based infrastructure https://travis-ci.org/mckelvin/libmc/jobs/70681267

```
Installing APT Packages (BETA)
Disallowing packages: cppcheck
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
```

Tx.

**Comment by mckelvin** [comment]
Thanks @BanzaiMan :beers:

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Sorry, but the rerun found a problem. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72172410

We'll be reverting this shortly.

**Comment by BanzaiMan** [comment]
Actually, those occurrences seem benign. Sorry about the alarm.
