### ISSUE TITLE
APT whitelist request for libexplain-dev

### ISSUE THREAD

**Issue by taekwonbilly** [travis-ci/travis-ci#4322]

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found problems. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72172621

This will be reverted shortly.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/402.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
