### ISSUE TITLE
APT source whitelist request for moreutils

### ISSUE THREAD

**Issue by jewilmeer** [travis-ci/travis-ci#4323]
To enable the use of `ifne`

http://packages.ubuntu.com/precise/utils/moreutils

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/48.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
