### ISSUE TITLE
APT source whitelist request for atool

### ISSUE THREAD

**Issue by jewilmeer** [travis-ci/travis-ci#4324]
For our projects we need to have `atool` installed in order to unpack our archives properly

https://launchpad.net/ubuntu/+source/atool/0.38.0-1

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/49.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
