### ISSUE TITLE
APT whitelist request for libopenjpeg-dev

### ISSUE THREAD

**Issue by shezadkhan137** [travis-ci/travis-ci#4325]

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found additional packages. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72172339
