### ISSUE TITLE
APT whitelist request for stunnel4

### ISSUE THREAD

**Issue by mp911de** [travis-ci/travis-ci#4326]
I'd need stunnel to test SSL tunneling with mp911de/lettuce and mp911de/spinach

Thanks.

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for stunnel does not exist, or needs an APT source.

See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71944385.

**Comment by mp911de** [comment]
You're using Ubuntu 14.04? The package details are listed at http://packages.ubuntu.com/trusty/stunnel4

Sometimes stunnel is referenced just as stunnel and sometimes as stunnel3 or stunnel4.

**Comment by BanzaiMan** [comment]
@mp911de Sorry, we are on Precise.

**Comment by mp911de** [comment]
Here you go: http://packages.ubuntu.com/precise/stunnel4

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/403.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
