### ISSUE TITLE
APT whitelist request for qq

### ISSUE THREAD

**Issue by simonmorley** [travis-ci/travis-ci#4327]

**Comment by BanzaiMan** [comment]
Sorry, `qq` doesn't exist for Precise. http://packages.ubuntu.com/precise/qq. Where do you expect to find this?

**Comment by simonmorley** [comment]
Not using precise on dev. machines. Let me check shortly.

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for qq does not exist, or needs an APT source.

See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71944409.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/404.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
