### ISSUE TITLE
APT whitelist request for markdown

### ISSUE THREAD

**Issue by devfubar** [travis-ci/travis-ci#4328]
I use this to convert .md files to html

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run did not find any problem. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72172510

**Comment by devfubar** [comment]
Perfect thanks :-)

Ill change over to the new container builds very soon
