### ISSUE TITLE
APT whitelist request for libxml-xpath-perl

### ISSUE THREAD

**Issue by miguelbalparda** [travis-ci/travis-ci#4330]

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run did not find any problem. Sorry for the alarm. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72182984
