### ISSUE TITLE
APT whitelist request for python-pywbem

### ISSUE THREAD

**Issue by cathay4t** [travis-ci/travis-ci#4332]

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run did not find any problems. Sorry for the alarm. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72183070
