### ISSUE TITLE
APT whitelist request for libpolarssl-dev

### ISSUE THREAD

**Issue by jvanbaarsen** [travis-ci/travis-ci#4333]

**Comment by jvanbaarsen** [comment]
@BanzaiMan Thanks!

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Rerun found no problems. Sorry for the alarm. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72174342
