### ISSUE TITLE
APT whitelist request for srecord

### ISSUE THREAD

**Issue by marcelstoer** [travis-ci/travis-ci#4336]
http://srecord.sourceforge.net/

> The SRecord package is a collection of powerful tools for manipulating EPROM load files.

Sample build: https://travis-ci.org/marcelstoer/nodemcu-firmware/builds/70789081

**Comment by marcelstoer** [comment]
How long does it usually take until non-invasive libraries such as this one are approved (i.e. whitelisted)? Is it a matter of days, weeks or even months?

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by marcelstoer** [comment]
Keeping my fingers crossed as I already submitted a PR to a project that depends on this: https://github.com/nodemcu/nodemcu-firmware/pull/571

**Comment by BanzaiMan** [comment]
Re-run found no problems. Sorry for the alarm. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72174683
