### ISSUE TITLE
🍦 APT whitelist request for ppa:chris-lea/zeromq ppa:marutter/rrutter

### ISSUE THREAD

**Issue by samccone** [travis-ci/travis-ci#4337]
https://github.com/twosigma/beaker-notebook uses travis and we :heart: it. Currently our builds are quite slow and we would love to speed them up. There are a few dependencies that we need however.
- **~~ppa:nginx/stable~~**
  - ~~nginx~~
  - :white_check_mark: looks like nginx was added here https://github.com/travis-ci/travis-ci/issues/1976
- **ppa:chris-lea/zeromq**
  - https://github.com/zeromq/pyzmq
- **ppa:marutter/rrutter**
  - Assorted R libs

We are also blocked on pandas :panda_face: :bamboo: https://github.com/travis-ci/travis-ci/issues/4313

Thanks so much for your time :clock10:

**Comment by scottdraves** [comment]
still need these....

**Comment by Krinkle** [comment]
Looks like these are now tracked on https://github.com/travis-ci/apt-package-whitelist. Maybe try again there?
