### ISSUE TITLE
APT whitelist request for tcpdump

### ISSUE THREAD

**Issue by mcr** [travis-ci/travis-ci#4338]
need tcpdump to do comparisons on packets emitted by code in test harness.

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found problems. This will be reverted shortly. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72181046

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/405.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
