### ISSUE TITLE
APT whitelist request for mpich-bin

### ISSUE THREAD

**Issue by QuLogic** [travis-ci/travis-ci#4339]
#4164 conveniently added not only `libhdf5-openmpi-dev`, but also `libhdf5-mpich-dev` and `libhdf5-lam-dev`. The trouble is that `mpich-bin` and `lam-runtime` are not whitelisted, so you can't run any MPI-compiled binaries.

**Comment by BanzaiMan** [comment]
@QuLogic Could you split this ticket into 2, unless `mpich-bin` and `lam-runtime` are defined in the same source package? That'll help our automation tools.

**Comment by QuLogic** [comment]
Done.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207083 found problems with Python code.

**Comment by QuLogic** [comment]
It looks like the source package is being checked. If that's the case, then how did `libmpich1.0-dev` get whitelisted, since it's built from the same source. Also, `mpich-3.1` is not the version available in precise.

**Comment by BanzaiMan** [comment]
I think it's coming from here: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json#L37-L41 The check is not quite sophisticated as to which sources should be consulted (it just add them all). I'll have to think about how to get around this problem.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/406.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
