### ISSUE TITLE
Build memcached with sasl support

### ISSUE THREAD

**Issue by jaysonsantos** [travis-ci/travis-ci#434]
As I talked with @michaelklishin on IRC it would be great if memached is build with sasl support.
We have talked about how ugly is build it with sources and maybe apt-get source should be a better approach as it is the same package as in production.
Here is a simple how to http://code.google.com/p/memcached/wiki/SASLHowto
Thank you for this great project

**Comment by XadillaX** [comment]
@michaelklishin Can you provide default login-password pair for memcached SASL on travis?

**Comment by michaelklishin** [comment]
I haven't been involved with Travis infra for over 3 years.
