### ISSUE TITLE
APT whitelist request for tomcat7

### ISSUE THREAD

**Issue by sideshowbarker** [travis-ci/travis-ci#4340]
I use tomcat to run a smoke test of a built java war file by installing+starting a tomcat instance, deploying the built war file to it, and doing a simple test to see if the resulting web app is responding as expected.

**Comment by sideshowbarker** [comment]
Thanks!

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found no problems. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72173652
