### ISSUE TITLE
APT whitelist request for texlive-bibtex-extra

### ISSUE THREAD

**Issue by pdiegmann** [travis-ci/travis-ci#4341]
Would be great to have a bit more of all those LaTeX / BibTeX Packages :)

```
Disallowing packages: texlive-bibtex-extra biblatex, chktex
```

**Comment by BanzaiMan** [comment]
textlive-bibtex-extra is already listed https://github.com/travis-ci/apt-package-whitelist/blob/949bdbf3b9459cba0b72bd9cec1f6b2f0fab5148/ubuntu-precise#L6887

Are you requesting biblatex and chtex?

**Comment by BanzaiMan** [comment]
I see #4342 and #4343.

**Comment by pdiegmann** [comment]
Ah, sorry for the duplicate. Was just wondering because it appeared while running a build (just as printed above).

And yes, I also requested biblatex and chtex.
