### ISSUE TITLE
APT whitelist request for chktex

### ISSUE THREAD

**Issue by pdiegmann** [travis-ci/travis-ci#4343]
Would be great to have a bit more of all those LaTeX / BibTeX Packages :)

```
Disallowing packages: texlive-bibtex-extra biblatex, chktex
```

**Comment by zbeekman** [comment]
I too would love to have chktex

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run did not find any problem. Sorry for the alarm. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72183011
