### ISSUE TITLE
"No such file or directory" when executing a binary

### ISSUE THREAD

**Issue by raks81** [travis-ci/travis-ci#4346]
The test case of my program requires an mp3 file to be passed to a binary executable, both of which are part of the codebase. The program executes the the binary (fpcalc - acousticid fingerprint generator) programatically and reads the output. The test case passes in my dev box, however on travis I see this error:

    panic: fork/exec /usr/local/bin/fpcalc: no such file or directory [recovered]
    panic: fork/exec /usr/local/bin/fpcalc: no such file or directory

I tried to execute the same command as an entry in the "scripts" section, but see similar issue:

    $ /usr/local/bin/fpcalc /home/travis/gopath/src/github.com/raks81/go-acousticid/test.mp3 /home/travis/build.sh: line 41: /usr/local/bin/fpcalc: No such file or directory
    The command "/usr/local/bin/fpcalc /home/travis/gopath/src/github.com/raks81/go-acousticid/test.mp3" exited with 127.

This is the build: https://travis-ci.org/raks81/go-acousticid/jobs/70871380

Is there any restriction on executing pre-built binaries on travis-ci?

**Comment by roidrage** [comment]
There is a restriction indeed, and it is that binaries are expected to be 64 bits, and the one you're using seems to be 32 bits.

Recompiling it for the proper architecture should help fix the issue.

**Comment by raks81** [comment]
Yes, the binary is 32-bit as I am running a 32-bit machine. I will try again with 64-bit binary and report back. Thanks for the tip!

**Comment by raks81** [comment]
Nice. That worked. Thanks!!
