### ISSUE TITLE
APT whitelist request for iceweasel

### ISSUE THREAD

**Issue by dracos** [travis-ci/travis-ci#4348]
So we can run selenium tests in Travis, thanks!

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207227 found problems.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/407.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
