### ISSUE TITLE
travis-build fails when an environment variable contains an apostrophe

### ISSUE THREAD

**Issue by xZise** [travis-ci/travis-ci#4350]
It seems that it creates an invalid build.sh when there are environment variables which contain an apostrophe on exporting the variable:

* [Exporting the variables without a problem](https://travis-ci.org/xZise/pywikibot-core/builds/70889034#L134)
* [One variable contains an apostrophe and it complains](https://travis-ci.org/xZise/pywikibot-core/builds/70887908#L134)

It also prints the resulting build.sh and the relevant line in 41 does:

```
$ eval export\ USER_PASSWORD\=not\'password
bash: unexpected EOF while looking for matching `''
bash: syntax error: unexpected end of file
```

And that is called [later in the file](https://travis-ci.org/xZise/pywikibot-core/builds/70887908#L551).

**Comment by roidrage** [comment]
The easiest fix for this is to put the value into double quotes, as this is somewhat normal shell behaviour. We've been contemplating a fix for this, but when you're encrypting something, this will work the best and solve the issue.

**Comment by xZise** [comment]
Okay that seems to work as a workaround but maybe that should be highlighted? Either when someone is trying to input a string with a single quote or in general. Or is it intentional that the content is not quoted?

**Comment by henrikhodne** [comment]
It is indeed intentional that the content isn't quoted, since several projects rely on things like `FOO=$(bar)` working.

**Comment by BanzaiMan** [comment]
We cannot ascertain the user's intentions just by the value, though. So I think our current implementation is best.

I've added a note in documentation. http://docs.travis-ci.com/user/environment-variables/
