### ISSUE TITLE
APT whitelist request for libqt5gui5

### ISSUE THREAD

**Issue by elken** [travis-ci/travis-ci#4352]
Ik #3765 exists, but nothing's been done in ~3 months.

**Comment by philipp-spiess** [comment]
:+1:

**Comment by nicolas-dular** [comment]
:+1:

**Comment by olivierlacan** [comment]
Would be useful to me as well.

**Comment by TheOneRing** [comment]
would be great

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by olivierlacan** [comment]
Hey @BanzaiMan, might want to check your GitHub account.

**Comment by BanzaiMan** [comment]
@olivierlacan Or the logic of the script that was posting comments. (Or make script sophisticated enough to not comment if there is one already.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 libqt5core5a libqt5gui5 libqt5libqgtk2 libqt5network5 libqt5opengl5 libqt5sql5 libqt5sql5-mysql libqt5sql5-odbc libqt5sql5-psql libqt5sql5-sqlite libqt5sql5-tds libqt5xml5 libqt5dbus5 libqt5test5 libqt5concurrent5 libqt5widgets5 libqt5printsupport5 qtbase5-dev qtbase5-private-dev libqt5opengl5-dev qtbase5-dev-tools qt5-qmake qtbase5-examples qtbase5-dbg qtbase5-dev-tools-dbg qtbase5-examples-dbg qt5-default qtbase5-doc-html

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72485040.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/408.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
