### ISSUE TITLE
Older iPhoneSimulator SDKs missing on Xcode 6.4 image

### ISSUE THREAD

**Issue by tjarratt** [travis-ci/travis-ci#4355]
According to [the Obj-C docs](http://docs.travis-ci.com/user/languages/objective-c/) the Xcode 6.4 image (specified by adding `osx_image: xcode6.4` to a project's `.travis.yml`) should include iOS 7.1, 8.1, 8.2 and 8.3 simulators.

It appears that only the 8.4 simulator is available. I have [an open pull request](https://github.com/pivotal/cedar/pull/345) where I'm trying to switch over to using the `osx_image` declaration in our travis.yml, and stop testing iOS 7.0.3 in favor of 7.1, but when we switched to using `osx_image`, some of the simulators we want to test against are missing.

[You can see an example of this failing for one of our test runs here](https://travis-ci.org/pivotal/cedar/jobs/70454170). Search for "xcodebuild: error: SDK "iphonesimulator8.3" cannot be located."

We do override some of the build steps in our travis.yml, perhaps that's the problem?

``` travis.yml
language: objective-c
osx_image: xcode6.4

env:
  matrix:
    - CEDAR_SDK_VERSION="8.1" CEDAR_SDK_RUNTIME_VERSION="7.1" TASK="ci"
    - CEDAR_SDK_VERSION="8.1" CEDAR_SDK_RUNTIME_VERSION="8.1" TASK="ci"
    # - CEDAR_SDK_VERSION="8.1" CEDAR_SDK_RUNTIME_VERSION="8.1" TASK="ci"

    # Analyze takes too long to vary on runtime SDK
    - CEDAR_SDK_VERSION="8.1" CEDAR_SDK_RUNTIME_VERSION="8.1" TASK="suites:specs:analyze"
    - CEDAR_SDK_VERSION="8.1" CEDAR_SDK_RUNTIME_VERSION="8.1" TASK="suites:uispecs:analyze"
    - CEDAR_SDK_VERSION="8.1" CEDAR_SDK_RUNTIME_VERSION="8.1" TASK="suites:focused_specs:analyze"

before_install: brew update
install:
  - bundle install
  - brew install ios-sim

script:
    # run a printer task to keep travis from terminating static analysis
    - 'while true; do echo "(waiting)"; sleep 60; done &'
    - rake $TASK
    - kill %1
```

**Comment by henrikhodne** [comment]
Starting in Xcode 6.2, Apple started to only include the simulators for older versions of iOS, and stopped including the simulator SDKs. So the simulators are still there for launching with instruments (or any other tool that you are launching simulators with), but you can only build against one SDK (8.4 for the Xcode 6.4 image).

**Comment by tjarratt** [comment]
Thanks for the information, @henrikhodne -- is there a good solution in place if I want to actually build and run my tests against multiple simulator SDKs?

**Comment by JALsnipe** [comment]
You could download a previous version of Xcode and copy the simulator SDK from there into your new Xcode.

Example to use the iOS 8.4 Simulator SDK with Xcode 7:

From Xcode 6.4:
Take the directory `Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk`
Rename it from iPhoneSimulator.sdk to iPhoneSimulator8.4.sdk.

Copy it to Xcode 7:
`Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs`

Observe your new Simulator SDKs:

![screen shot 2015-10-02 at 11 07 30 am](https://cloud.githubusercontent.com/assets/4513736/10249890/d0e25598-68f5-11e5-9c4c-a646c0f0a273.png)

**Comment by bengartner** [comment]
Is this still an issue? Can it be closed?
