### ISSUE TITLE
APT whitelist request for libace-dev

### ISSUE THREAD

**Issue by Tuxity** [travis-ci/travis-ci#4360]
`libace-dev` from Ubuntu Precise (http://packages.ubuntu.com/precise/libace-dev)

**Comment by Tuxity** [comment]
Do I've to wait a bit to get this deploy and working with my build ?

**Comment by BanzaiMan** [comment]
@Tuxity It should be available now. If it's not working, please provide the build log URL. Thanks.

**Comment by Tuxity** [comment]
Ah it's good, thank you. I just wait a bit more (~30min) and relaunch my build :)

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found some problems. This will be reverted shortly. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72183039

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/410.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
