### ISSUE TITLE
APT whitelist request for libxerces-c2-dev

### ISSUE THREAD

**Issue by tph-thuering** [travis-ci/travis-ci#4366]
We need this package for our project:

https://travis-ci.org/SwissTPH/openmalaria/builds/71049435

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found no problems. Sorry for the alarm. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72190547
