### ISSUE TITLE
Putting an unknown sourcelist in addons.apt.sources silently fails

### ISSUE THREAD

**Issue by dawagner** [travis-ci/travis-ci#4370]
The following entry in .travis.yml:

``` {.yml}
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalaris-cmake
```

Should trigger a build error because "kalaris-cmake" doesn't exist: there's a typo - the actual name is "kala**k**ris-cmake".

Not triggering an explicit error in such cases leads to hard-to-debug build failures.

**Comment by BanzaiMan** [comment]
A message:

```
Disallowing sources: kalaris-cmake
```

now appears.

**Comment by dawagner** [comment]
Does the build fail in such a case? Thanks for looking at this, anyhow.

**Comment by BanzaiMan** [comment]
It does not.
