### ISSUE TITLE
APT whitelist request for libiptcdata-dev

### ISSUE THREAD

**Issue by cdmicacc** [travis-ci/travis-ci#4376]

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for libiptcdata-dev does not exist, or needs an APT source.

See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71975813.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/412.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
