### ISSUE TITLE
APT whitelist request for ruby1.9.1

### ISSUE THREAD

**Issue by cdmicacc** [travis-ci/travis-ci#4377]

**Comment by BanzaiMan** [comment]
Ruby runtimes are available on all images via RVM. Installing Ubuntu packages probably would not have effects you are after. Could you elaborate on how you intend to use this?

See #4378.

**Comment by cdmicacc** [comment]
We are building in a Go environment and need to install some gems and run some ruby scripts.  Normally "rvm install ruby1.9" will compile Ruby -- is there a Travis shortcut for this?

**Comment by BanzaiMan** [comment]
Go images come with RVM, and 1.9.3 should be available. (You can also run `rvm use 2.1.6 --binary --fuzzy --install`.) See https://travis-ci.org/BanzaiMan/travis_production_test/builds/71108792 and [the corresponding `.travis.yml`](https://github.com/BanzaiMan/travis_production_test/blob/bbd47e2d92e2b0b333da1f04ac024740c2ebd76c/.travis.yml).

**Comment by cdmicacc** [comment]
Ah, ok.  Thanks. I'll give that a try once the other packages are available.
