### ISSUE TITLE
casher detects changes, but packs nothing

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/travis-ci#4380]
We've received a report of casher detecting changes, but the file list for the `tar` command is apparently empty.:

```
changes detected, packing new archive

FAILED: tar -Pzcf /Users/travis/.casher/push.tgz 

tar: no files or directories specified



uploading archive

failed to upload cache

curl: Can't open '/Users/travis/.casher/push.tgz'!

curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by BanzaiMan** [comment]
Looks like if the `diff` results could be just a bunch of white spaces when we compare the checksums.

**Comment by kamoljan** [comment]
Hi @BanzaiMan similar issue in my case:

    language: objective-c

    # enable container mode
    sudo: false

    # whitelist
    branches:
      only:
        - master

    before_install:
      - gem install cocoapods
      - brew update
      - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
      - ./CI/install-creative-sdk.sh

      podfile: ShoppingXXX/Podfile

      xcode_workspace: ShoppingXXX/ShoppingXXX.xcworkspace
      xcode_scheme: ShoppingXXX
      osx_image: xcode6.4
      xcode_sdk: iphonesimulator8.4

    cache:
      - bundler
      - cocoapods

**Comment by evils** [comment]
same here

**Comment by BanzaiMan** [comment]
Closing this in favor of #4615.
