### ISSUE TITLE
APT whitelist request for elinks

### ISSUE THREAD

**Issue by jwilk** [travis-ci/travis-ci#4382]
Needed for https://github.com/jwilk/pwnsjp.

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found no suspicious bits. Sorry for the alarm. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72193534
