### ISSUE TITLE
APT source whitelist request for datastax

### ISSUE THREAD

**Issue by stuartf** [travis-ci/travis-ci#4383]
I need to be able to install Cassandra from datastax. The sources.list entry looks like:

    deb http://debian.datastax.com/community stable main

and the gpg key is at http://debian.datastax.com/debian/repo_key

**Comment by BanzaiMan** [comment]
Did not run automated check because 'datastax' needs source whitelisting

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/50.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
