### ISSUE TITLE
`git clone` uses insecure (plaintext) `git://` protocol with GitHub repositories

### ISSUE THREAD

**Issue by vszakats** [travis-ci/travis-ci#4384]
Using the `git://` protocol is not [advertised or encouraged](https://github.com/travis-ci/docs-travis-ci-com/pull/284) by GitHub and it also has the disadvantage of being a [plaintext](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#The-Git-Protocol) protocol [without authentication](https://gist.github.com/grawity/4392747#protocols-to-choose-from-when-cloning). This makes no guarantee (and no easy way to verify) that the code arriving onto the build server is the same as it was on GitHub's servers. 

It'd be nice if Travis-CI would switch to use `https://` by default, when accessing `github.com` repositories (and possibly others where this choice is available).

If making it a default is not an option for some reason, it'd still be useful to make this controllable via a [`.travis.yml`](https://github.com/travis-ci/travis-yaml/blob/master/SPEC.md#git) option.

[ `git://` protocol is also used in several places inside Travis-CI codebase to reference dependencies, which would probably be best to switch to `https://` as well. ]

**Comment by reedloden** [comment]
:+1: -- just noticed that earlier today as well.

**Comment by BanzaiMan** [comment]
Just noting here that I am getting the following error message if I try to set up git credentials and push changes up:

```
  You can't push to git://github.com/travis-ci/apt-whitelist-checker.git
  Use https://github.com/travis-ci/apt-whitelist-checker.git
```

I'm not sure if this is new (within the last week), but it is something to note. One must reconfigure the remote:

```
git remote rm origin
git remote add origin https://github.com/travis-ci/apt-whitelist-checker.git
git fetch origin
git checkout master # or any other branch
```
