### ISSUE TITLE
APT whitelist request for moreutils

### ISSUE THREAD

**Issue by EvanK** [travis-ci/travis-ci#4385]
Needed for `ts` command, to timestamp piped data

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71799478#L273

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found no problems. Sorry for the alarm. https://github.com/travis-ci/travis-ci/issues/4385
