### ISSUE TITLE
APT whitelist request for bash-completion

### ISSUE THREAD

**Issue by kruton** [travis-ci/travis-ci#4386]
bash-completion needed to run unit tests on bash-completion scripts

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71799468

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206438
