### ISSUE TITLE
Error: "xvfb-run: error: Xvfb failed to start"

### ISSUE THREAD

**Issue by brauliobo** [travis-ci/travis-ci#4387]
I'm having the error "xvfb-run: error: Xvfb failed to start" quite frequently.

For example, see https://travis-ci.org/noosfero/noosfero/jobs/70839566. On this same build, another job (https://travis-ci.org/noosfero/noosfero/jobs/70839565) also uses xvfb for selenium tests. Maybe the problem is with two concurrent jobs using xvfb?

**Comment by brauliobo** [comment]
Removing
```yml
before_install:                                                                                                                                                        
 - export DISPLAY=:99.0   
 - sh -e /etc/init.d/xvfb start
```
Made it work. (I was already using `-a` option to `xvfb-run`)

http://docs.travis-ci.com/user/gui-and-headless-browsers/ should be updated with this

**Comment by BanzaiMan** [comment]
@brauliobo Thanks for the info. Do you mind opening a docs PR?

**Comment by brauliobo** [comment]
@BanzaiMan sorry for the delay, please review the doc change at https://github.com/travis-ci/docs-travis-ci-com/pull/311

**Comment by ussserrr** [comment]
I have the same issue, my setup was (according to docs https://docs.travis-ci.com/user/gui-and-headless-browsers/):
```yaml
language: python
python: ...
services:
  - xvfb
install: ...
script:
  - xvfb-run python -m unittest -b -v
```
What's help is to start the script as:
```
xvfb-run --auto-servernum --server-num=1 python -m unittest -b -v
```

**Comment by Akuli** [comment]
To me it worked without xvfb-run.

Figured it out by looking at what other stuff travis did before trying to `xvfb-run`, and one of the things was `$ export DISPLAY=:99.0`. This seems to be the display that xvfb is using, and this env var gets passed to all programs regardless of whether they're running under `xvfb-run` or not.

**Comment by axelpale** [comment]
In my case, I had to add `--auto-servernum --server-num=1` and update the screen number from 0 to 1 in `--server-args="-screen 0 1024x768x24"` so that the resulting script command is:

    xvfb-run --auto-servernum --server-num=1 --server-args="-screen 1 1024x768x24" make test
