### ISSUE TITLE
cache.directories does not work with glob wild cards

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4390]
Is it a good idea to accept them? What are possible disadvantages?

**Comment by sebworks** [comment]
@BanzaiMan, was this implemented?

**Comment by sebworks** [comment]
Would it be possible to implement that feature?  It just makes it easier than listing out a series of directories. We want to use it to cache a series of nested node_module directories.

**Comment by christian-bromann** [comment]
This would be particular useful for speeding up the bootstrap process for projects using Lerna.
