### ISSUE TITLE
APT source whitelist request for oracle java

### ISSUE THREAD

**Issue by scaryclam** [travis-ci/travis-ci#4394]
{
    "alias": "oracle-java",
    "sourceline": "ppa:webupd8team/java",
    "key_url": null
  }

**Comment by BanzaiMan** [comment]
This is the PPA that we use to install Java 8, so it should be available already. What package do you need? If you need Java 8u45 now, see https://github.com/travis-ci/travis-ci/issues/4042#issuecomment-109756980.
