### ISSUE TITLE
bash script not recognising docker

### ISSUE THREAD

**Issue by mrmiroslav** [travis-ci/travis-ci#4395]
I am trying to simplify yml file by moving none travis related commands into bash file and it errors with ```line 29: docker: command not found```. If I run ```which docker``` just above the bash script - it runs and it is aware of docker. Comments?

```
dist: trusty

script:
  # @todo: for some reason rolling_update.sh does not recognise docker without `which docker`
  - which docker
  # Run rolling update
  - source rolling_update.sh
```

**Comment by BanzaiMan** [comment]
That sounds quite bizarre. Do you have a build log URL that shows this problem?

**Comment by mrmiroslav** [comment]
@BanzaiMan It is bizzarre.

https://magnum.travis-ci.com/PotentialWeb/imager/builds/13684026
vs
https://magnum.travis-ci.com/PotentialWeb/imager/builds/13684470

**Comment by BanzaiMan** [comment]
Sorry for the delay. Is this still an issue? If so, please email support@travis-ci.com for the followup. I'm closing this now, since the discussion will now be most likely private.
