### ISSUE TITLE
APT source whitelist request for haproxy-1.5

### ISSUE THREAD

**Issue by maxdrift** [travis-ci/travis-ci#4396]
We need haproxy 1.5 to test our cloud backend and we're trying to migrate to *container-based infrastructure*.

`ppa:vbernat/haproxy-1.5`

Thanks!

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/51.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
