### ISSUE TITLE
APT whitelist request for libvips-dev

### ISSUE THREAD

**Issue by gasi** [travis-ci/travis-ci#4398]
This is needed to build the Node.js image library `sharp` which uses VIPS: https://github.com/lovell/sharp/

#### Script
```
before_install:
  - echo "Installing libvips..."
  - sudo add-apt-repository -y ppa:lovell/precise-backport-vips
  - sudo apt-get update
  - sudo apt-get install -y libvips-dev
```

See: https://github.com/lovell/sharp/issues/187#issuecomment-121789796

/cc @lovell

**Comment by BanzaiMan** [comment]
Did not run automated check because 'libvips-dev' needs source whitelisting

**Comment by gasi** [comment]
@BanzaiMan Thanks for checking. Could we add source whitelisting for it? We’d love to use `libvips-dev` on the new container based architecture :smile:

**Comment by BanzaiMan** [comment]
@gasi For that, please open a separate request.

**Comment by gasi** [comment]
> @gasi For that, please open a separate request.

Thanks, done: https://github.com/travis-ci/travis-ci/issues/4515

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/425.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!

**Comment by gasi** [comment]
@BanzaiMan My bad. Thanks for moving it :+1:

**Comment by BanzaiMan** [comment]
@gasi No worries. This move is a recent development. Thanks for your understanding.
