### ISSUE TITLE
APT whitelist request for xdotool

### ISSUE THREAD

**Issue by DaveDavenport** [travis-ci/travis-ci#4399]
This is needed to run regressions tests on rofi.
https://github.com/DaveDavenport/rofi

Thanks.

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by DaveDavenport** [comment]
As background,  I use it for regression testing.  Scripts start an Xvfb and then uses xdotools to send keyboard input to the window. Code can be found here https://github.com/jordansissel/xdotool

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71799462

**Comment by jordansissel** [comment]
@BanzaiMan xdotool author here. It looks like your test went well, cool!  Let me know if there's any trouble with xdotool :)

**Comment by DaveDavenport** [comment]
Thanks!
