### ISSUE TITLE
APT whitelist request for libopenmpi1.5-dev

### ISSUE THREAD

**Issue by GiovanniBussi** [travis-ci/travis-ci#4409]

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207081 found problems.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/426.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
