### ISSUE TITLE
APT whitelist request for rethinkdb

### ISSUE THREAD

**Issue by belucid** [travis-ci/travis-ci#4411]
ppa:rethinkdb/ppa

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/428.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
