### ISSUE TITLE
APT whitelist request for libinsighttoolkit3-dev

### ISSUE THREAD

**Issue by dcoeurjo** [travis-ci/travis-ci#4415]
Needed for github.com/DGtal-team/DGtal

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72208718 found problems; but it looks like a call to Gtk. Needs further investigation.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/429.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
