### ISSUE TITLE
mactex install in osx fails for language: R

### ISSUE THREAD

**Issue by iagomosqueira** [travis-ci/travis-ci#4417]
I have moved an existing mutli-os project (https://travis-ci.org/flr/FLCore) to making use of the full integration of R, by having in .travis.yml

```yaml
os:
  - linux
  - osx
language: R
sudo: required
```
This worked fine in Linux, but in OSX I get

The command "wget http://mirror.ctan.org/systems/mac/mactex/mactex-basic.pkg -O "/tmp/mactex-basic.pkg"" failed and exited with 8 during .

When I look at

http://ctan.mackichan.com/systems/mac/mactex/

I can see these .pkg files

BasicTeX.pkg
MacTeX.pkg
basictex-20150613.pkg
mactex-20150613.pkg

I assume the URL needs to be changed to basictex-VERSION.pkg

Cheers,

Iago

@craigcitro @eddelbuettel @hadley

**Comment by iagomosqueira** [comment]
Variable mactex seems to be set in Line 365 of

https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb

Not sure what to suggest to find what is the right filename to use

**Comment by craigcitro** [comment]
yeah, it looks like package names have changed -- quick PR out to clean it up.
