### ISSUE TITLE
APT whitelist request for python-pil

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#4420]
Python2: python-pil and python-pil.imagetk
Python3: python3-pil

It is useful to test using the platform provided version of Pillow.

**Comment by BanzaiMan** [comment]
`Python Pillow` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`Python Pillow` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`Python Pillow` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`Python Pillow` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`Python Pillow` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`Python Pillow` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`Python Pillow` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`Python Pillow` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
Sorry about the noise there.

**Comment by jayvdb** [comment]
no worries; happy to see automation in action! ;-)

**Comment by jayvdb** [comment]
@BanzaiMan I'm seeing an odd error
https://travis-ci.org/jayvdb/pywikibot-core/jobs/72557477#L96

```
Package python-pil is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-pil' has no installation candidate
```

**Comment by BanzaiMan** [comment]
It looks like it is coming from a whitelisted source

https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72228954#L418

which is defined here: https://github.com/travis-ci/apt-source-whitelist/blob/8dc7511d7f535b78c82bc40bdb47e260d75f8c73/ubuntu.json#L38

Try adding:

```yaml
addons:
  apt:
    sources:
    - debian-sid
```

**Comment by jayvdb** [comment]
@BanzaiMan , just adding that, causes an apt error

https://travis-ci.org/jayvdb/pywikibot-core/jobs/73356653#L121
See that commit
https://github.com/jayvdb/pywikibot-core/commit/e6e717d6872591521f9ea07e9331db7b229be451
It's parent is a branch off our master, which is passing all tests.

**Comment by BanzaiMan** [comment]
How does this build relate to python-pil?

**Comment by BanzaiMan** [comment]
Ah. You are trying to *add* `python-pil` to this.

**Comment by jayvdb** [comment]
Yes, I encountered the same errors when adding `python-pil` with sources: `debian-sid`, but before annoying you I tried to isolate whether just adding sources: `debian-sid` causes the problem.  It does.

**Comment by BanzaiMan** [comment]
Hmmm. Could it be that `graphviz` also exists in `debian-sid`, but with different dependencies, which are no longer satisfied with the list of packages that you gave? https://travis-ci.org/jayvdb/pywikibot-core/jobs/73356653#L108 Or, there are other reasons that the dependency is no longer satisfied with the addition of `debian-sid`.

I'm sorry to say this, but I suppose you'll have to go down whacking one dependency block at a time to get the list of packages you need.

There is no "platform provided version" of Pillow for Precise. http://packages.ubuntu.com/precise/python-pil, so if the real goal is to test against it, then I suggest waiting for Trusty. We are testing the new setup for it, and if you would like to try it, please email support@travis-ci.com.
