### ISSUE TITLE
APT whitelist request for libpam-dev

### ISSUE THREAD

**Issue by rmbreak** [travis-ci/travis-ci#4421]

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for libpam-dev does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365171.
