### ISSUE TITLE
APT whitelist for MongoDB 2.6 and above

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#4424]
See https://github.com/travis-ci/apt-package-whitelist/pull/17 and https://github.com/travis-ci/apt-source-whitelist/pull/13
This will allow the MongoEngine build to install only the MongoDB server for all MongoDB versions.
We'd like to upgrade to the new build infrastructure but that's blocking us.
Can you please merge both PRs as soon as possible?

**Comment by BanzaiMan** [comment]
The issues have now been resolved. MongoDB 2.6 should be available. My cursory attempt to use 3.0 did not work; if there are other things to test/whitelist, let us know.
