### ISSUE TITLE
APT whitelist request for libghc-gstreamer-dev

### ISSUE THREAD

**Issue by dougthor42** [travis-ci/travis-ci#4425]
It seems like `libghc-gstreamer-dev` is needed to build wxPython 3.0.2.0 from source.

I haven't figured out another way to install wxPython. Pre-built binaries for wxPython only go to Ubuntu 11.4 (natty) and wx 2.8.12.0

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run found no problems. Sorry for the alarm. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72194482

**Comment by dougthor42** [comment]
Thanks for the updates.

It appears that whitelisting this package allows for wxPython to be built from source. (But then I run into other, unrelated issues of course :disappointed:)

**Comment by BanzaiMan** [comment]
Hmm. I may have put that comment in error. The log doesn't seem to indicate problems. I'll revisit it soon.

(If I don't, please ping me.)

**Comment by BanzaiMan** [comment]
It was added by https://github.com/travis-ci/apt-package-whitelist/pull/78. Not sure how I missed it.

Sorry for the confusion.
