### ISSUE TITLE
Adding an env variable via Settings changes the umask of ~/.netrc

### ISSUE THREAD

**Issue by postmodern** [travis-ci/travis-ci#4426]
Previously we added env variables to our `~/.netrc` file via a `before_install` hook:

```
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
```

Recently, we modified the env variables via the Settings dashboard. Suddenly, the [netrc](https://rubygems.org/gems/netrc/versions/0.10.3) gem began raising exceptions that the umask of `~/.netrc` file was 0644 and not 0600.

**Comment by BanzaiMan** [comment]
Do you have build log URLs that show the problem? How recent is "recently"?

The build script's umask should be 022, so I expect the new files to have mode 0644.

I looked at the code, but I didn't immediately see how this part of logic might have changed recently.

**Comment by BanzaiMan** [comment]
Hmm. I'm seeing umask as 002. Not sure where that came from.

**Comment by postmodern** [comment]
This has been happening this week on magnum. Googling around showed other people just added a chmod to reset the umask. Also re-starting the build seemed to not reset the `~/.netrc` file and caused `unexpected EOF` errors. Removing the command and file entirely seemed to fix the issue.

**Comment by BanzaiMan** [comment]
Were you caching `~/.netrc`?

**Comment by postmodern** [comment]
I don't believe so.

**Comment by BanzaiMan** [comment]
Sorry for the long silence. Is this still an issue? If so, could you point to a relevant build log URL? Thanks.
