### ISSUE TITLE
APT whitelist request for runit

### ISSUE THREAD

**Issue by powerman** [travis-ci/travis-ci#4433]
This is needed for https://magnum.travis-ci.com/inCaller/server-prototype

**Comment by BanzaiMan** [comment]
Re-ran the test, and found issues. Sorry for the mixup, but it will be reverted shortly.

https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206722

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/430.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
