### ISSUE TITLE
APT whitelist request for ta-lib

### ISSUE THREAD

**Issue by femtotrader** [travis-ci/travis-ci#4435]
Hello,

I need to compare results from my Python Pandas implementation of technical indicators https://github.com/femtotrader/pandas_talib with results of Python TA-Lib wrapper https://github.com/mrjbq7/ta-lib.

For this, the library ta-lib should be whitelisted http://ta-lib.org/

http://www.zwets.com/ta-lib/
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=437177

Kind regards

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for ta-lib does not exist, or needs an APT source.

See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71992185.

**Comment by femtotrader** [comment]
Could you try

 deb     http://www.zwets.com/debs    unstable/
 deb-src http://www.zwets.com/debs    unstable/

see http://www.zwets.com/ta-lib/

Source is also available here

http://ta-lib.org/hdr_dw.html
http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz

**Comment by BanzaiMan** [comment]
@femtotrader Could you open a request for source separately? Thanks.

**Comment by BanzaiMan** [comment]
@femtotrader Please open a source request separately.

**Comment by femtotrader** [comment]
Not sure of what you are requesting ?

You want me to open an other issue at
https://github.com/travis-ci/travis-ci/issues/ 

?

**Comment by BanzaiMan** [comment]
@femtotrader You can use https://github.com/travis-ci/apt-source-whitelist/ for that. Thank you.

**Comment by femtotrader** [comment]
Done

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/431.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
