### ISSUE TITLE
APT whitelist request for libboost1.48-all-dev

### ISSUE THREAD

**Issue by haahh** [travis-ci/travis-ci#4438]
Please whitelist:

```
libboost-chrono1.48-dev
libboost-date-time1.48-dev
libboost-filesystem1.48-dev
libboost-graph-parallel1.48-dev
libboost-graph1.48-dev
libboost-iostreams1.48-dev
libboost-locale1.48-dev
libboost-math1.48-dev
libboost-mpi-python1.48-dev
libboost-mpi1.48-dev
libboost-program-options1.48-dev
libboost-python1.48-dev
libboost-random1.48-dev
libboost-regex1.48-dev
libboost-serialization1.48-dev
libboost-signals1.48-dev
libboost-system1.48-dev
libboost-test1.48-dev
libboost-thread1.48-dev
libboost-timer1.48-dev
libboost-wave1.48-dev
libboost1.48-all-dev
libboost1.48-dbg
libboost1.48-dev
libboost1.48-doc
```

Versions 1.55 (from boost-latest) and 1.46 of Boost Libraries are already on the white-list.

**Comment by haahh** [comment]
http://packages.ubuntu.com/source/precise/boost1.48

**Comment by BanzaiMan** [comment]
`libboost 1.48` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`libboost 1.48` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`libboost 1.48` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`libboost 1.48` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`libboost 1.48` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`libboost 1.48` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`libboost 1.48` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`libboost 1.48` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
`libboost 1.48` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for libboost1.48 does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365187.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 bjam boost-build libboost1.48-dbg libboost1.48-dev libboost1.48-all-dev libboost1.48-doc libboost-chrono1.48.0 libboost-chrono1.48-dev libboost-date-time1.48.0 libboost-date-time1.48-dev libboost-filesystem1.48.0 libboost-filesystem1.48-dev libboost-graph1.48.0 libboost-graph1.48-dev libboost-graph-parallel1.48.0 libboost-graph-parallel1.48-dev libboost-iostreams1.48.0 libboost-iostreams1.48-dev libboost-locale1.48.0 libboost-locale1.48-dev libboost-math1.48.0 libboost-math1.48-dev libboost-mpi1.48.0 libboost-mpi1.48-dev libboost-mpi-python1.48.0 libboost-mpi-python1.48-dev libboost-program-options1.48.0 libboost-program-options1.48-dev libboost-python1.48.0 libboost-python1.48-dev libboost-random1.48.0 libboost-random1.48-dev libboost-regex1.48.0 libboost-regex1.48-dev libboost-serialization1.48.0 libboost-serialization1.48-dev libboost-signals1.48.0 libboost-signals1.48-dev libboost-system1.48.0 libboost-system1.48-dev libboost-test1.48.0 libboost-test1.48-dev libboost-thread1.48.0 libboost-thread1.48-dev libboost-timer1.48.0 libboost-timer1.48-dev libboost-wave1.48.0 libboost-wave1.48-dev.

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72367385.

**Comment by haahh** [comment]
Hi, I'm sorry for wrongly naming the issue. I saw this issue https://github.com/travis-ci/travis-ci/issues/3759 and named my accordingly.
 
> Either the source package for libboost1.48 does not exist, or the package needs an APT source.

Yeah, `libboost1.48` package does not exist.

>If the source package of your requested package contains other related packages, you do not
>have to open another one for those.

OK, so I think the name should be changed to `APT whitelist request for libboost1.48-all-dev` since this package contains all of above excluding 'libboost1.48-dbg` and `libboost1.48-doc` which are not important.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 bjam boost-build libboost1.48-dbg libboost1.48-dev libboost1.48-all-dev libboost1.48-doc libboost-chrono1.48.0 libboost-chrono1.48-dev libboost-date-time1.48.0 libboost-date-time1.48-dev libboost-filesystem1.48.0 libboost-filesystem1.48-dev libboost-graph1.48.0 libboost-graph1.48-dev libboost-graph-parallel1.48.0 libboost-graph-parallel1.48-dev libboost-iostreams1.48.0 libboost-iostreams1.48-dev libboost-locale1.48.0 libboost-locale1.48-dev libboost-math1.48.0 libboost-math1.48-dev libboost-mpi1.48.0 libboost-mpi1.48-dev libboost-mpi-python1.48.0 libboost-mpi-python1.48-dev libboost-program-options1.48.0 libboost-program-options1.48-dev libboost-python1.48.0 libboost-python1.48-dev libboost-random1.48.0 libboost-random1.48-dev libboost-regex1.48.0 libboost-regex1.48-dev libboost-serialization1.48.0 libboost-serialization1.48-dev libboost-signals1.48.0 libboost-signals1.48-dev libboost-system1.48.0 libboost-system1.48-dev libboost-test1.48.0 libboost-test1.48-dev libboost-thread1.48.0 libboost-thread1.48-dev libboost-timer1.48.0 libboost-timer1.48-dev libboost-wave1.48.0 libboost-wave1.48-dev

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72397372.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/432.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
