### ISSUE TITLE
APT whitelist request for python-pivy

### ISSUE THREAD

**Issue by kuba1** [travis-ci/travis-ci#4460]
FreeCAD dependency http://www.freecadweb.org/wiki/?title=CompileOnUnix#Debian_and_Ubuntu

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72208640 found problems with Python code.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/414.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
