### ISSUE TITLE
Duplicate builds for all commits

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#4463]
For some reason I get duplicate builds for all commits.
See https://travis-ci.org/idan/oauthlib/builds

![screenshot from 2015-07-19 13 33 50](https://cloud.githubusercontent.com/assets/48936/8765570/e0345e80-2e1a-11e5-9400-3b531b847dfb.png)

**Comment by joshk** [comment]
Hi @thedrow 

Could you please check the service hooks screen and confirm your hook is only setup once?

**Comment by thedrow** [comment]
I don't have owner access to the repository. I'll have to ask.

**Comment by roidrage** [comment]
Have you been able to find out if the service hook is only setup once?

**Comment by thedrow** [comment]
It seems that it was setup twice. Thanks.
