### ISSUE TITLE
APT whitelist request for rpm-build

### ISSUE THREAD

**Issue by unindented** [travis-ci/travis-ci#4475]

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for rpm-build does not exist, or the package needs an APT source.If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process.Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72220160.

**Comment by unindented** [comment]
I'm closing this, as `rpmbuild` is included in the `rpm` package on Debian, which is already whitelisted.

Sorry about this.
