### ISSUE TITLE
APT whitelist request for libluajit-5.1-2

### ISSUE THREAD

**Issue by mneudert** [travis-ci/travis-ci#4479]
To compile nginx in the container environment with lua support baked in I would like to see the following packages whitelisted:

- libluajit-5.1-2
- libluajit-5.1-common
- libluajit-5.1-dev

Installation in the regular environment using `sudo apt install` works flawlessly but requires the regular environment ;)

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for libluajit-5.1 does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72225077.

**Comment by mneudert** [comment]
The exact packages are the ones in the issue description. Sorry for the confusion with the title :D

According to a setup I use they should be readily available from the default sources:
https://github.com/mneudert/luxy/blob/master/.travis.yml#L11
