### ISSUE TITLE
APT whitelist request for libhdf5-dev

### ISSUE THREAD

**Issue by cancan101** [travis-ci/travis-ci#4480]
http://packages.ubuntu.com/trusty/libhdf5-dev

**Comment by BanzaiMan** [comment]
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71805283

**Comment by pb-cdunn** [comment]
E: Package 'libhdf5-dev' has no installation candidate

* https://travis-ci.org/pb-cdunn/blasr/builds/71821866
* https://github.com/pb-cdunn/blasr/commit/8b3d997ed7a27c13bdb35c615b8244fd617cb2d5

Am I Doing It Wrong? :confused:

**Comment by cancan101** [comment]
That looks right to me.

**Comment by BanzaiMan** [comment]
@pb-cdunn Sorry. You didn't. I misread the test results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71805283#L256

**Comment by cancan101** [comment]
Looks like in precise it's called: http://packages.ubuntu.com/precise/libhdf5-serial-dev

**Comment by pb-cdunn** [comment]
I don't think serial-dev includes everything. (And I'm not sure where the headers are either.)

**Comment by pb-cdunn** [comment]
Even though it's in the whitelist, I still cannot find it using `ppa:ubuntu-toolchain-r/test`, which I think I need for the dockerized container builds.

* https://travis-ci.org/pb-cdunn/blasr/builds/72148799

```
2.34s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-4.8 g++-4.8 clang libhdf5-dev
Reading package lists...
Building dependency tree...
Reading state information...
Package libhdf5-dev is a virtual package provided by:
  libhdf5-serial-dev 1.8.4-patch1-3ubuntu2
  libhdf5-openmpi-dev 1.8.4-patch1-3ubuntu2
  libhdf5-mpich-dev 1.8.4-patch1-3ubuntu2
  libhdf5-lam-dev 1.8.4-patch1-3ubuntu2
E: Package 'libhdf5-dev' has no installation candidate
```
Another version of those libs are there already (1.6 I think; see `ls /usr/lib` in the log) but without an actual installation, I can't find any HDF5 headers.

**Comment by BanzaiMan** [comment]
Sorry. I had to re-run the test, and found this bit: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206938 This will have to be reverted.

**Comment by cancan101** [comment]
So does that mean there is no way to include the lib on travis container service?

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/416.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
