### ISSUE TITLE
APT whitelist request for octave

### ISSUE THREAD

**Issue by cbm755** [travis-ci/travis-ci#4486]
Split out from #4279 as per https://github.com/travis-ci/travis-ci/issues/4279#issuecomment-123048502

**Comment by cbm755** [comment]
please label: `apt-whitelist`

**Comment by BanzaiMan** [comment]
Sorry, the closure might have been premature. I believe this is for the `octave` package from a different source.

I'm reopening this now.

**Comment by BanzaiMan** [comment]
`octave` and friends have been whitelisted (https://github.com/travis-ci/apt-package-whitelist/commit/5e10320bc3c28173da924a415dcea46f42fbb9e8), so if you want to do that, you can.

**Comment by cbm755** [comment]
thanks!  I think this will allow us to use Octave 3.6, so I will close this bug.  FTR: I have #4279 for the ppa which gives a later Octave (currently 3.8).

**Comment by cbm755** [comment]
> this will allow us to use Octave 3.6

FTR, Octave 3.2.  And maybe there was no liboctave-dev in old ubuntu, as I cannot find it.

I expect anyone finding their way here should follow https://github.com/travis-ci/apt-source-whitelist/issues/53
