### ISSUE TITLE
APT whitelist request for flexc++/bisonc++

### ISSUE THREAD

**Issue by jdm64** [travis-ci/travis-ci#4490]
I'm trying to convert to the container build system.
I need flexc++/bisonc++ to build my compiler's front-end.
see: https://github.com/jdm64/saphyr

**Comment by BanzaiMan** [comment]
Please split this into 2 requests, so that we can run tests. Thanks.

**Comment by BanzaiMan** [comment]
Superseded by #4534 and #4535.
