### ISSUE TITLE
APT source whitelist request for paparazzi-uav/ppa

### ISSUE THREAD

**Issue by flixr** [travis-ci/travis-ci#4498]
Please whitelist `ppa:paparazzi-uav/ppa`

This PPA contains packages for the [IVY bus] (http://www.eei.cena.fr/products/ivy/) and dependencies for the Paparazzi UAV project.

https://launchpad.net/~paparazzi-uav/+archive/ubuntu/ppa

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/56.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
