### ISSUE TITLE
APT source whitelist request for Scipy

### ISSUE THREAD

**Issue by cbenz** [travis-ci/travis-ci#4499]
ppa:pylab/stable
https://launchpad.net/~pylab/+archive/ubuntu/stable

Useful to use python-scipy >= 0.12

Ubuntu Precise [provides 0.9](http://packages.ubuntu.com/precise/python-scipy)

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/57.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
