### ISSUE TITLE
APT source whitelist request for bashes

### ISSUE THREAD

**Issue by agriffis** [travis-ci/travis-ci#4501]
This is similar to the deadsnakes repo but for bash. I announced this originally on Twitter and got some endorsement from Josh K, so it would be nice to see it available in the container-based infra too.

PPA: https://launchpad.net/~agriffis/+archive/ubuntu/bashes
Original announcement: https://twitter.com/arongriffis/status/314920844101050369
Full writeup: http://arongriffis.com/2013/03/25/bashes.html

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/58.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
