### ISSUE TITLE
APT source whitelist request for ppa:aims/sagemath

### ISSUE THREAD

**Issue by isuruf** [travis-ci/travis-ci#4505]
This is needed to get the package `sagemath-upstream-binary` needed for [symengine](github.com/sympy/symengine) and [sympy](github.com/sympy/sympy)

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/59.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
