### ISSUE TITLE
APT whitelist request for lam-runtime

### ISSUE THREAD

**Issue by QuLogic** [travis-ci/travis-ci#4507]
Split off of #4339.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229016.

**Comment by QuLogic** [comment]
I don't think a list of identifiers for syntax highlighting should be a problem.

**Comment by BanzaiMan** [comment]
This is meant to be a textual analysis. We'll have to take further look. Thanks for your patience.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 lam-mpidoc lam4-dev liblam4 lam-runtime.

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365250.
