### ISSUE TITLE
APT whitelist request for highlight

### ISSUE THREAD

**Issue by yihui** [travis-ci/travis-ci#4508]

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229022.

**Comment by yihui** [comment]
That is a false positive. It is just a keyword to be syntax highlighted. It is not calling `setuid` to do anything.

**Comment by BanzaiMan** [comment]
Will be re-running the check again, with more information in the comment.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 highlight highlight-common libhighlight-perl.

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365254.

**Comment by yihui** [comment]
Thanks a lot!
