### ISSUE TITLE
[feature-request] add support for code analyzers (pep8 / pylint / jslint)

### ISSUE THREAD

**Issue by armisael** [travis-ci/travis-ci#451]
It would be really cool to add support for code analyzers such as pep8 / pylint (for python) and similars.

I'm thinking about something like the way Jenkins does it: http://tinyurl.com/828xrzj
It may have a different badge as well, so projects could have two or more badges for code quality on their github page.

**Comment by michaelmior** [comment]
@lawrenceakka CodeClimate has added the ability to create your own analysis engines including a couple that already exist for Python
