### ISSUE TITLE
APT source whitelist request for libvips-dev

### ISSUE THREAD

**Issue by gasi** [travis-ci/travis-ci#4515]
Supersedes: https://github.com/travis-ci/travis-ci/issues/4398

This is needed to build the Node.js image library `sharp` which uses VIPS: https://github.com/lovell/sharp/

#### Script
```
before_install:
  - echo "Installing libvips..."
  - sudo add-apt-repository -y ppa:lovell/precise-backport-vips
  - sudo apt-get update
  - sudo apt-get install -y libvips-dev
```

See: https://github.com/lovell/sharp/issues/187#issuecomment-121789796

/cc @lovell

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/68.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
