### ISSUE TITLE
logs are fine in one build, and out of order in another build on the same commit

### ISSUE THREAD

**Issue by uber5001** [travis-ci/travis-ci#4517]
I pushed a commit to both origin [(build here)](https://travis-ci.org/uber5001/react-native-renderer/builds/71977479) and upstream [(build here)](https://travis-ci.org/angular/react-native-renderer/builds/71978306).

For some reason, the build for origin fails during initialization of a submodule, so I restart that build.

When I come back much later, both builds have passed, but the logs of the build for origin are messed up and out of order. For some reason, commands run by travis are code-folded inside of each other, and logs for each command are intersected with each other. The log for the origin build says on the first few lines that it is using 3 workers.

This isn't blocking me on anything, it's just a weird anomaly. Thought you'd like to know about it.

**Comment by uber5001** [comment]
It looks like it ran three copies of the build and merged the logs.

**Comment by BanzaiMan** [comment]
Sorry about the problem and the delay. Is this an issue with recent builds?

**Comment by uber5001** [comment]
I don't know how to reproduce the issue at this point. I don't think I knew how then either! IIRC, I just ran the builds again and it worked fine.

Feel free to close the issue; I only submitted this issue so there would be a recorded case in case anyone else ran into the same anomaly.

**Comment by BanzaiMan** [comment]
OK. Do let us know if you see the problem again. Thank you!
