### ISSUE TITLE
APT whitelist request for libqt5webkit5-dev

### ISSUE THREAD

**Issue by mcmire** [travis-ci/travis-ci#4519]
This is necessary in order to run capybara-webkit tests against a project that requires Qt 5 (using features that weren't available in Qt 4, such as ES5 getters/setters). ([Source](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#debian-testing-unstable-stable-wheezy--ubuntu-1404-lts))

Thanks!

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229082.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/443.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
