### ISSUE TITLE
clang in osx builds

### ISSUE THREAD

**Issue by AbdealiJK** [travis-ci/travis-ci#4523]
I am trying to install clang on OSX builds as I need it for some tests.

When I use brew to install it, I get a timeout of 50mins. Apparently clang takes hours to install using brew on OSX ... as it compiles itself.

Here's the build - https://travis-ci.org/AbdealiJK/coala/builds/71417931

Could you suggest how I can install clang on OSX ?

Note : Specifically, I need only the clang library for my project (libclang.dylib)

**Comment by BanzaiMan** [comment]
llvm.org has pre-built binaries. For example: http://llvm.org/releases/download.html#3.6.0

```sh-session
$ tar tvf clang+llvm-3.6.0-x86_64-apple-darwin.tar.xz clang+llvm-3.6.0-x86_64-apple-darwin/lib/libclang.dylib
-rwxr-xr-x  0 sebastiandressler staff 13751180 Feb 25 02:41 clang+llvm-3.6.0-x86_64-apple-darwin/lib/libclang.dylib
```

**Comment by AbdealiJK** [comment]
Thanks, I'll try that out
