### ISSUE TITLE
Issues with gridengine due to lack of sudo

### ISSUE THREAD

**Issue by cancan101** [travis-ci/travis-ci#4524]
[Repasted](https://github.com/travis-ci/travis-ci/issues/3773#issuecomment-123562600):

I am having trouble using gridengine without `sudo`. [This is how one user currently uses the package with sudo](https://github.com/pygridtools/drmaa-python/blob/5c157204b64384d3658063e4e4335474d42bb9b6/travis/install_sge.sh). 
The issue is that the `travis` user is not set up as a manager in the grid config so attempts to modify the cluster result in:
```
$ qconf -as localhost
denied: "travis" must be manager for this operation
```

Looking closely at the install logs:
```
Setting up gridengine-master (6.2u5-4) ...
Initializing cluster with the following parameters:
 => SGE_ROOT: /var/lib/gridengine
 => SGE_CELL: default
 => Spool directory: /var/spool/gridengine/spooldb
 => Initial manager user: sgeadmin
...
Adding user sgeadmin as a manager
```

**Comment by jakirkham** [comment]
The following lines would be necessary to fully configure SGE. The first two are absolutely essential for the current user to manage SGE. Where `user.conf` would look like the following file with "template" replaced by "travis" or the relevant user. ( https://github.com/jakirkham/docker_ubuntu_drmaa_conda/blob/master/gridengine/user.conf.tmpl )

    sudo qconf -Auser ${SGE_CONFIG_DIR}/user.conf
    sudo qconf -au ${USER} arusers
    sudo qconf -as ${HOSTNAME}
    sleep 1
    
    export HOST_IN_SEL=$(qconf -sel | grep -c "$HOSTNAME")
    if [ $HOST_IN_SEL != "1" ]; then sudo qconf -Ae ${SGE_CONFIG_DIR}/host.conf; else sudo qconf -Me ${SGE_CONFIG_DIR}/host.conf; fi
    
    sudo qconf -Ap ${SGE_CONFIG_DIR}/batch.conf
    sudo qconf -Aq ${SGE_CONFIG_DIR}/queue.conf

**Comment by cancan101** [comment]
I should think only one sudo call should be needed: adding the Travis user to the admin list.

**Comment by jakirkham** [comment]
@cancan101, probably right. I just copied over code from the entrypoint script that runs under root and went a little overboard adding `sudo`.

**Comment by jakirkham** [comment]
@cancan101, this may not be necessary if container environments become more flexible. It appears there is traction on this recently ( https://github.com/travis-ci/travis-ci/issues/1418#issuecomment-124859463 ).

**Comment by BanzaiMan** [comment]
We provide a means of installing a package, but running additional commands (in this case, `sudo qconf …`) is not possible. This is highly unlikely to change.

If you need such maneuver beyond what packages provide, you need `sudo`.

I'm closing this.
