### ISSUE TITLE
APT source whitelist request for ppa:beineri/opt-qt55

### ISSUE THREAD

**Issue by jck** [travis-ci/travis-ci#4525]
This PPA has the latest qt 5.5 packages.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/69.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
