### ISSUE TITLE
Travis CI needs a GitHub avatar!

### ISSUE THREAD

**Issue by grenade** [travis-ci/travis-ci#4528]
With CI builds in Travis CI that [publish to GitHub Pages](https://github.com/grenade/grenade-ng/blob/master/publish.sh) by performing commits against a gh-pages repository, it's nice to distinguish commits by the CI process, from those committed by a regular repository contributor or real person. This is easy enough to achieve by setting the commit user.email to the Travis CI builds email account.
However, builds at travis-ci.org doesn't have a GitHub Avatar so all his commits [look boring](https://github.com/grenade/grenade.github.io/commits/master) in GitHub commit lists.
Please, Travis can you associate your handsome face with your builds email on your GitHub profile?
![travis](https://cloud.githubusercontent.com/assets/111819/8823799/bd4deb26-3067-11e5-877a-0825f5969f0c.png)

**Comment by BanzaiMan** [comment]
Hello,

Thanks for opening the ticket, but this is not something we can control. When you set up your git repository during builds on Travis CI, the git commits will inherit these data. If the data are not recognized by GitHub, you will get the generic avatar you see.

The [commit](https://api.github.com/repos/grenade/grenade.github.io/git/commits/4dd064c5275436c80baa3f5d9ec9555705e1724a) in the example you gave was authored by `builds@travis-ci.org`, which was defined in [your `.travis.yml`](https://github.com/grenade/grenade-ng/blob/228ad4acac5a7b0b3dae1c0465d6072a5c898503/.travis.yml#L13-L20).

If you want an avatar to look different, I suggest you set up the git user appropriately.

Thanks.

**Comment by grenade** [comment]
GitHub needs the person who owns the email address to set the avatar. I was hoping that someone at Travis CI, who has access to or owns builds@travis-ci.org, would associate the Travis Avatar, with that address.
Of course I can change my publisher to commit with a different email address, but I don't want to. Since Travis-CI is making the commit, I want to use a Travis-CI email address. Since I don't own or control that address, I cannot set its avatar. Does that make sense?

**Comment by grenade** [comment]
Well, I fixed it in the way you suggested and its a pretty ugly hack. I had to create an email address that I own (travis.ci.build@gmail.com), create a [GitHub profile](https://github.com/travis-ci-build) that I'll never use (other than for Travis CI commits).

This is an ugly solution IMO because a user not affiliated with Travis CI (me) has to own an email address and GitHub profile that misleadingly suggest an affiliation with Travis CI that doesn't exist.

But, it does work to solve my need for a Travis avatar in my publisher [commit logs](https://github.com/grenade/grenade.github.io/commits/master).

I still think it would be better for someone at Travis CI to associate the avatar with a real Travis CI email.

**Comment by BanzaiMan** [comment]
Maybe you can use @travisbot for that?

**Comment by donavon** [comment]
If I want the same, now I have to setup my own email address as well (as does the next person, and the next person). It would be nice if there we an *official* Travis owned email address that was linked to Gravatar that we could *all* use. Another benefit is that YOU (Travis) would own the image and in case you ever changed it, everyone would see the new image.

All that we're asking is that you give us an official email address that has a Gravatar image. This doesn't seem like an unreasonable request.

**Comment by BanzaiMan** [comment]
I'm reopening, but please understand that this is not a high priority.

**Comment by Krinkle** [comment]
> Maybe you can use @travisbot for that?

Seems fair, but while @travisbot has a profile photo, it doesn't have a public e-mail address, so I'm not sure which e-mail address to use in order to trigger a link.

Looking at the commits it pushes, such as https://github.com/travis-ci/apt-package-whitelist/commit/9f8f5a0c150a6848d8ce07286fd6b3913f890436, it uses a forged git author of `Travis CI User <travis@example.org>` - which is not associated with any GitHub or Gravatar account.

@BanzaiMan One very easy way to resolve this is to ensure @travisbot has at least one public e-mail address. The simplest choice would be to simply add `travis@example.org` to its account (It doesn't even need to be verified!). Though a `@travis-ci.com` e-mail would probably be more appropiate. And again, it doesn't need to exist or otherwise be verifiable.

**Comment by Krinkle** [comment]
(don't close)

**Comment by Krinkle** [comment]
Still an issue per https://github.com/travis-ci/apt-package-whitelist/commit/2e98039ba4d9ce0ba0f5d021bafb6284886a3037

**Comment by BanzaiMan** [comment]
@travisbot provides `support@travis-ci.org`

**Comment by finefoot** [comment]
> @travisbot provides `support@travis-ci.org`

I don't know why, but this didn't work for me with `support@travis-ci.org`. It did, however, work with `deploy@travis-ci.org` which is the default value for deployments as described in https://docs.travis-ci.com/user/deployment/pages/
