### ISSUE TITLE
APT source whitelist request for ppa:ondrej/php5-5.6

### ISSUE THREAD

**Issue by untitaker** [travis-ci/travis-ci#4529]

**Comment by BanzaiMan** [comment]
I'm curious to know how our PHP support falls short in your case.

**Comment by untitaker** [comment]
See https://github.com/untitaker/vdirsyncer for project: It is a Python
application for which integration tests are run against PHP server software
(but only for some builds in the matrix).

I need a particular bugfix (https://bugs.php.net/bug.php?id=69655), which will
presumably be not available in any PHP version Ubuntu provides.

Perhaps the broader, better request here is to have multi-language projects so
I can use your PHP nightlies.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/70.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
