### ISSUE TITLE
multi os - different build matrices

### ISSUE THREAD

**Issue by AbdealiJK** [travis-ci/travis-ci#4530]
Im using the multi os feature - and it works great :)

I was wondering if I could set different build matrices for each os.

I currently have:
```
os:
  - linux
  - osx
env:
  matrix:
    - PYTHON_VERSION=3.4.2
    - PYTHON_VERSION=3.3.5
```

and this runs 4 builds of linux+3.4 , linux+3.3 , osx+3.4 , osx + 3.3

I want to add more tests for linux, as linux container builds are fast, but osx builds are still slow.

How I can add `PYTHON_VERSION=3.2.5` only for linux ?

**Comment by solarce** [comment]
You can do this by removing the `os:` block and using `matrix.include`. A great example of this is the PyCA's build matrix: https://github.com/pyca/cryptography/blob/master/.travis.yml
