### ISSUE TITLE
HHVM 3.5 is no longer supported

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4532]
Facebook has dropped support on the 6-month-old HHVM 3.5 (https://github.com/facebook/hhvm/issues/5761#issuecomment-123169514). We need to provide access to more recent version(s) for HHVM.

**Comment by keradus** [comment]
Yeah, that would be really great !
Any plans about that ?

**Comment by BanzaiMan** [comment]
HHVM is now updated on precise on demand. (It is 3.6.6 at the moment.)
