### ISSUE TITLE
APT whitelist request for libnewlib-arm-none-eabi

### ISSUE THREAD

**Issue by gebart** [travis-ci/travis-ci#4539]
libnewlib-arm-none-eabi is used for building many bare metal ARM embedded projects

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 libnewlib-dev libnewlib-doc libnewlib-arm-none-eabi newlib-source.

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365259.

**Comment by gebart** [comment]
The `setuid`, `setgid`, `seteuid` parts are inside the C code and header files because newlib prodvide basic stubs for these system calls for embedded systems. There are no setuid files installed from the package.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-package-whitelist/issues/435.

Moving forward, please create new requests at https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___

Thank you!
