### ISSUE TITLE
Elasticsearch server does not start on Docker

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#4543]
A customer reports that on php/docker images the elastic search addon does not work because of a permissions problem:

```
$ sudo service elasticsearch start
* Starting Elasticsearch Server it: error setting limit (Operation not permitted)
error: permission denied on key 'vm.max_map_count'
```

**Comment by BanzaiMan** [comment]
This is a known benign warning, which we documented in http://docs.travis-ci.com/user/database-setup/#Garbled-Output. As far as I know, ElasticSearch should function correctly.

I'm closing this for now. If you find the evidence to suggest the contrary, do let us know.
