### ISSUE TITLE
Scala version not set properly

### ISSUE THREAD

**Issue by rrdelaney** [travis-ci/travis-ci#4547]
It seems that in https://travis-ci.org/rrdelaney/vegas/builds/72308679 when plugins are downloading the Scala version is being resolved as 2.10, rather than 2.11.6 as specified in both `.travis.yml` and `build.sbt`

**Comment by BanzaiMan** [comment]
Could you try `echo $TRAVIS_SCALA_VERSION` to see if it is indeed the issue here? https://travis-ci.org/rrdelaney/vegas/builds/72308679#L97 suggests to me that we are picking 2.11.6. https://github.com/travis-ci/travis-ci/issues/4527#issuecomment-124137489 suggests that it might be a tooling issue.

**Comment by rrdelaney** [comment]
https://travis-ci.org/rrdelaney/vegas/builds/72314893#L99
It might be a tooling issue, but it builds fine locally

**Comment by rtyley** [comment]
To repeat my comment on https://github.com/travis-ci/travis-ci/issues/4527#issuecomment-124137489 - the behaviour you're seeing of downloading plugins for Scala 2.10 is expected, and this issue (#4547) should be closed.

SBT runs with Scala 2.10, no matter what version of Scala you're compiling your project against.

**Comment by rrdelaney** [comment]
https://github.com/travis-ci/travis-ci/issues/4527#issuecomment-124142017 seemed to fix this
