### ISSUE TITLE
Unstable disk writes on /tmp

### ISSUE THREAD

**Issue by brauliobo** [travis-ci/travis-ci#4549]
Completely randomly and quite frequently, I get the error:

```
No such file or directory @ rb_sysopen - /tmp/other-pic.jpg20150723-8450-18bo51p (Errno::ENOENT)
```

See for example: https://travis-ci.org/noosfero/noosfero/jobs/72325617

I never get these errors locally, so it might be a problem with travis' /tmp

**Comment by esambo** [comment]
See https://github.com/travis-ci/travis-ci/issues/4656#issuecomment-131212402

**Comment by brauliobo** [comment]
The issues haven't been happening for quite some time
