### ISSUE TITLE
[travis-build][addon-mariadb] mariadb support a multivalue configuration

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#4554]
A multiple list form would be really nice to test an application against multiple versions.
[single list form](https://github.com/grooverdan/PyMySQL/commit/f70e40fe3b5e1fe406f19f5f1fb3777fb62712a6) resulted in [[5.5] as the version](https://travis-ci.org/grooverdan/PyMySQL/jobs/72040844) and hence didn't install 5.5. [multiple list form](https://github.com/grooverdan/PyMySQL/commit/038d47a5a58d069eb22f895b89142a02e2a34f29) seemed to [ignore all repos](https://travis-ci.org/grooverdan/PyMySQL/jobs/72041918) and resort to mysql.

[matrix builds](https://github.com/grooverdan/PyMySQL/blob/c05bf7c6d0f3161d91b3e1418ac185b8749be8c3/.travis.yml) [not quite right](https://travis-ci.org/grooverdan/PyMySQL/builds/72077568) as the versions aren't tested against every python version.

Can supporting a syntax like:
<pre>
addons:
     mariadb:
        - 5.5
        - 10.0
        - 10.1
        - none
</pre>

Is having *none* as a item in a list acceptable to revert to the installed MySQL so an application can be test against MariaDB versions and MySQL.

I think this might be added here somewhere: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/deploy/script.rb#L9

**Comment by BanzaiMan** [comment]
Right now, addons do not get expanded into the build matrix. There are existing issues about this. If we are to make it possible for this addon, it makes sense to do it for all. I can't really point to the issue, but I'm closing this one on that ground.
