### ISSUE TITLE
[docmentation] document mariadb addon

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#4555]
If #4552 is implemented note:

config files can have sections like [mariadb] [mariadb-10.0], [mariadb-5.5], [mariadb-10.1]  for enabling configurations specific to mariadb, or a mariadb version. Later options will override earlier options.

Also note #4553 and #4554 will affect documentation

**Comment by grooverdan** [comment]
Sample documentation code for building a a matrix of builds against different mariadb versions.
<pre>
matrix:
   include:
        - python: 3.3
          env: DEBUG=1
          addons:
              mariadb: 5.5
        - python: 3.4
          env: DEBUG=0
          addons:
              mariadb: 5.5
        - python: 3.4
          env: DEBUG=1
          addons:
              mariadb: 10.0
        - python: 3.3
          env: DEBUG=0
          addons:
              mariadb: 10.0
        - python: 3.3
          env: DEBUG=1
          addons:
              mariadb: 10.1
        - python: 3.4
          env: DEBUG=0
          addons:
              mariadb: 10.1
</pre?

**Comment by ntwb** [comment]
This is awesome, the matrix per above works for me :+1: 

Though the Travis CI linter doesn't like it https://lint.travis-ci.org/

* `in matrix.include section: unexpected key addons, dropping`
