### ISSUE TITLE
Files deleted 'before_cache' are still triggering a cache archive repack 

### ISSUE THREAD

**Issue by rtyley** [travis-ci/travis-ci#4556]
I have a couple of `before_cache` commands in [my `.travis.yml`](https://github.com/guardian/gu-who/blob/ac2752f2/.travis.yml#L11-L13), which delete unwanted files, like this one:

```
/home/travis/.ivy2/cache/com.jcraft/jsch/ivydata-0.1.46.properties
```

Even though the file [gets deleted in the travis build](https://travis-ci.org/guardian/gu-who/builds/72424291#L144), it's _still_ [reported as a detected change](https://travis-ci.org/guardian/gu-who/builds/72424291#L471), triggering a repack of the cache.

I've tried completely wiping all caches, and starting again with some fresh build, but get the same result. Why are those files still there!?

cc @BanzaiMan

**Comment by BanzaiMan** [comment]
Thanks for the report. I'll look into it.

**Comment by rtyley** [comment]
Thanks @BanzaiMan - I saw your [Travis builds](https://travis-ci.org/BanzaiMan/gu-who#L227) with added md5sum debug - from what I could see, it looked like there were `com.jcraft/jsch` entries in the /home/travis/.ivy2/cache before the build started populating it (part of the default image?) - and they were deleted by my `before_cache` step. Are deletions of pre-existing files enough to trigger a cache repack?

**Comment by BanzaiMan** [comment]
Closing this in favor of #5016.
