### ISSUE TITLE
The column for "env" should grow to show more variables

### ISSUE THREAD

**Issue by briansmith** [travis-ci/travis-ci#4568]
See this annotated screen shot:

![image](https://cloud.githubusercontent.com/assets/16816/8884474/eb539584-3224-11e5-9105-f24153230dbe.png)

A simple, big, and much-appreciated improvement would be to change the CSS for the table so that the "env" column gets all the extra space when the table is resized.

**Comment by briansmith** [comment]
I am closing this since I filed it as travis-ci/travis-web#381 after I found the travis-web project. This is a dupe of that issue.

**Comment by joshk** [comment]
Sorry but all issues are meant to go in this repo and not in the sub projects like travis-web.

**Comment by joshk** [comment]
Hey @briansmith

As discussed on https://github.com/travis-ci/travis-web/issues/381, we have some major UI changes in the works, which will affect the available space in the job list. I'm going to close this issue for the time being.

Thank you for taking the time to open this and give this great feedback.

Josh
