### ISSUE TITLE
travis-build - mariadb addon not whitelisted for pull requests

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#4569]
solved by travis-ci/travis-core/pull/469

**Comment by grooverdan** [comment]
thanks for merging

**Comment by grooverdan** [comment]
It appears this isn't merged yet.

https://travis-ci.org/felixge/node-mysql/jobs/75009892

**Comment by BanzaiMan** [comment]
Sorry about the delay. I thought I'd deployed the changes to the apps, but I was wrong. The changes are now deployed to both .org and .com.

I'm closing this now.

**Comment by grooverdan** [comment]
does that take effect immediately? - Can't see it on https://travis-ci.org/felixge/node-mysql/jobs/77417022#L143 or https://travis-ci.org/amphp/mysql/jobs/77417274#L199

**Comment by BanzaiMan** [comment]
Yes. See https://travis-ci.org/BanzaiMan/travis_production_test/jobs/77426130#L76

https://github.com/felixge/node-mysql/pull/1177 is an old PR, so it is already configured and does not have any addons information associated with the build. Please close and open a new one.

**Comment by grooverdan** [comment]
ack. thanks.

**Comment by nanaya** [comment]
it looks like the addons only work if the pull request branch is from same user/organization? When I create pull request from different user, [the addons is still ignored](/ppy/osu-web/pull/41) whereas it works properly when [the branch is from same user](/ppy/osu-web/pull/40).

**Comment by BanzaiMan** [comment]
@nanaya The latest build on the PR (https://travis-ci.org/ppy/osu-web/builds/78716584) points to this commit (https://github.com/ppy/osu-web/commit/9970ad710bd951a9ee8ade0b536d4efdc427d41c), which does not have MariaDB addon. (https://github.com/ppy/osu-web/blob/9970ad710bd951a9ee8ade0b536d4efdc427d41c/.travis.yml)

Am I missing something?

**Comment by nanaya** [comment]
Yeah, I've been trying to work around that (but still failing unless resorting back to sudo). Let me revert back to how it was.

**Comment by BanzaiMan** [comment]
@nanaya Could you open a separate issue, so that we can track this? Thank you!
