### ISSUE TITLE
Postgresql start sometimes hangs on asking about superuser

### ISSUE THREAD

**Issue by dracos** [travis-ci/travis-ci#4570]
https://travis-ci.org/qgis/QGIS/builds/72577153 and https://travis-ci.org/qgis/QGIS/builds/72576361 both hung at "Shall the new role be a superuser? (y/n)" but builds in-between those two https://travis-ci.org/qgis/QGIS/builds/72576697 and after https://travis-ci.org/qgis/QGIS/builds/72577388 were fine in that respect.

**Comment by m-kuhn** [comment]
If I restart the travis build on a commit that previously failed like described above it normally passes the second time.

**Comment by meatballhat** [comment]
I think I've isolated this to PostgreSQL 9.4 on OpenVZ.  Patch forthcoming :smiley_cat: 

https://staging.travis-ci.org/meatballhat/yolo-octo-adventure/builds/434353
