### ISSUE TITLE
Not all public repos are shown on use page.

### ISSUE THREAD

**Issue by briansmith** [travis-ci/travis-ci#4572]
See https://travis-ci.org/briansmith/. Only the "ring" repo is shown, but I have two public repos: https://travis-ci.org/briansmith/ring and https://travis-ci.org/briansmith/mozillapkix. Both of those repos should be shown on the page. The mozillapkix repo might have been private at one point, which may be the cause of the issue.

**Comment by BanzaiMan** [comment]
Should be fixed now. If you continue to see problems, do reopen this.
