### ISSUE TITLE
Repos cloned from camel case usernames interact poorly with Go imports

### ISSUE THREAD

**Issue by jacobsa** [travis-ci/travis-ci#4573]
(This is related to #1545, which covers the issue from the angle of URLs.)

I'm trying to get Go vendoring set up for my repo GoogleCloudPlatform/gcsfuse. Unfortunately, whoever set up the organization on GitHub apparently chose the camel case name "GoogleCloudPlatform", so GitHub and Travis both treat this as the canonical name. In contrast, imports in Go are usually written in lower case, so my code says:

    import "github.com/googlecloudplatform/gcsfuse"

This causes issues for building on Travis, which I have described in the workaround [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/3047f4fce443762a2a0322e7c7fc4fcbe377396b/.travis.yml#L31-L54). These issues are usually masked for the default Go setup on Travis, and it accidentally works mostly correctly (though there are likely version skew problems). But when disabling the default `install` step, the code no longer builds correctly. Again, please see [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/3047f4fce443762a2a0322e7c7fc4fcbe377396b/.travis.yml#L31-L54) for a writeup.

Assuming there are not a bunch of other Go projects out there that _are_ using camel case names in their source code, it seems like the correct way to fix this is to canonicalize the repo name to lower case before doing the `install` step.

**Comment by BanzaiMan** [comment]
Do you work on a Mac or Windows? Do the tests you run work if you run the code with the case sensitive file system?

The tests seem to fail similarly when I try running them on a Linux system, and my local machine with a case sensitive file system (HFS+, journaled and case-sensitive).

It just so happens that my user name is mixed case, so I cloned the repo, dropped the hack, changed the code reference to match my user name, and ran the build. It passes. https://travis-ci.org/BanzaiMan/gcsfuse/builds/72767448 (see the [corresponding .travis.yml](https://github.com/BanzaiMan/gcsfuse/blob/3204f79260d8a5f98cd53991d44dba2b4be589ba/.travis.yml)).

I suspect (I am not a Gopher, so I can't say this for sure) that it is the Go's language design that it does not do any case normalization when it looks for code, and you need to be mindful of this fact when you look for mixed case files on a case-sensitive file system (as we have on a Linux VM; this is documented in a somewhat obscure corner of our documentation—http://docs.travis-ci.com/user/multi-os/#Operating-System-differences).

I don't think there is anything for us to do here.

**Comment by jacobsa** [comment]
I work on a Mac, cloning into a directory named `googlecloudplatform`, and also on Linux, doing the same. But of course the tests failing on Travis are running on Linux.

`go get` is definitely aware of case in at least some respects. For example: if on a Mac you have an existing directory named `GoogleCloudPlatform` and attempt to `go get github.com/googlecloudplatform/gcsfuse`, it will yell at you about mixing cases.

But yeah, I don't have a strong argument that this is Travis's problem, except that #1545 acknowledged the fact that GitHub's URLs are not case sensitive, which kind of argues that they should be canonicalized before cloning them. Otherwise tools like `go get` will do unexpected things like making a second copy of the repo and using that for subpackages, at the wrong version.

**Comment by BanzaiMan** [comment]
#1545 is about our API differentiating `GoogleCloudPlatform` and `googlecloudplatform`. Our API is not involved in this case. Cloning happens with `git`, and it is successful. Everything after that is Go and your code.

**Comment by joshk** [comment]
Hi @jacobsa 

It sounds like this isn't a Travis specific issue, but more about how Go works, and how you should be using imports.

If it is alright with you I will close this for the time being. If you find more information to show this might be Travis specific, please let us know.

Thanks a bundle

Josh
