### ISSUE TITLE
Allow to reduce the git clone depth

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#4575]
Currently Travis clones a repository to a depth of 50 commits.
We could by all means only clone the latest commit which would mean faster runs.
Cloning the last 50 commits is useful if you are performing git operations but isn't if you're not doing so at all.
I'd like an option to clone with depth of 1.

**Comment by BanzaiMan** [comment]
This is possible with a yet-to-be-documented feature:

```yaml
git:
  depth: 1
```

**Comment by thedrow** [comment]
Thanks. Why is it not documented?

**Comment by BanzaiMan** [comment]
Not quite sure. I'll leave this open while I find out the reason or document this feature.

**Comment by joshk** [comment]
As a side note, using a depth of more than 1 is useful when you have a queue of jobs, otherwise we won't see the commit if new commits are pushed before we get to process the job. This is why we chose 50, because there was no noticeable perf difference in the majority of cases.

**Comment by thedrow** [comment]
So there's a race condition involved in allowing to clone just the latest commit?
Isn't there a better way to resolve this using git?

**Comment by joshk** [comment]
No sorry, we have spoken to our friends at GitHub, and using a reasonable git depth is what they recommended.

Plus, as mentioned, there is no noticeable perf difference in the majority of cases.

**Comment by lucafavatella** [comment]
@BanzaiMan This looks [documented](https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth) now. Maybe this shall be closed now?

**Comment by BanzaiMan** [comment]
@lucafavatella Indeed!

**Comment by darealshinji** [comment]
Sorry for posting in this old issue, but does setting the git depth in .travis.yml also affect the git depth of submodules?
