### ISSUE TITLE
Request for additional ciphers to enable Webhook notifications

### ISSUE THREAD

**Issue by matthewmorley** [travis-ci/travis-ci#4576]
Per: http://docs.travis-ci.com/user/notifications/#Note-on-SSL-TLS-Ciphers

Is it possible to get ciphers from the following list added:
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA

I'm looking to make webhook notifications out to a site hosted at Acquia.

**Comment by BanzaiMan** [comment]
This is a limitation imposed by our use of JRuby. For the time being, we are unable to accept other ciphers.

**Comment by matthewmorley** [comment]
Do you know if this work for this issue with JRuby/OpenSSL has been started, or is being tracked in another issue queue?

**Comment by BanzaiMan** [comment]
For JRuby, that's the right issue to track. Another possibility is for us to switch to another language for travis-tasks, but I don't think we have a plan to do that at this time.

**Comment by BanzaiMan** [comment]
I'm sorry, but I'm going to close this one, since we have no immediate path to a workable solution.
