### ISSUE TITLE
Is it possible to get the Build Duration in a Environment variable ? 

### ISSUE THREAD

**Issue by ashrithshetty** [travis-ci/travis-ci#4580]
I want my current build's duration to be used for my build site . Is it possible to get it from Travis ?

**Comment by joshk** [comment]
I'm sorry but it is not possible to get this from the environment as we only calculate this once the build has finished. You can retrieve this via the API though.

**Comment by ashrithshetty** [comment]
Can you point me to the API doc please ?
 Thanks

**Comment by joshk** [comment]
http://docs.travis-ci.com/api/

**Comment by ashrithshetty** [comment]
Thanks :+1:
