### ISSUE TITLE
uuid-dev not installed via apt?

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#4582]
I'm having trouble migrating to the container infrastructure. Even with uuid-dev installed, build fails. Could you shed light on where the installed uuid-dev can be found:

`.travis.yml`:

	sudo: false
	addons:
	  apt:
	    packages:
	      - uuid-dev

uuid.h doesn't seem to be in the expected location (according to http://packages.ubuntu.com/precise/amd64/uuid-dev/filelist):

	$ ls -R /usr/include/uuid
	ls: cannot access /usr/include/uuid: No such file or directory

The installation itself seems fine:

	$ export DEBIAN_FRONTEND=noninteractive
	$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
	$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install build-essential wget libtool cmake gcc-4.8 clang-3.6 libcurl4-openssl-dev libmicrohttpd-dev uuid-dev libpng-dev libtiff4-dev
	Reading package lists...
	Building dependency tree...
	Reading state information...
	E: Unable to locate package gcc-4.8
	E: Couldn't find any package by regex 'gcc-4.8'
	E: Unable to locate package clang-3.6
	E: Couldn't find any package by regex 'clang-3.6'
	
Is it possible to diagnose if/that the uuid-dev install has somehow failed?

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/builds/74142286#L111

Not sure why your command is failing, but it is working fine for me. Do you have a build log URL that shows this problem?

**Comment by andig** [comment]
Oh dear. I had mentioned gcc-4.8 and clang-3.6 as packages. Those don't exist and therefore apt failed while I was assuming these errors are being ignored. Please excuse me...
