### ISSUE TITLE
Duplicate builds for PR and Push Even when Merge will be FF

### ISSUE THREAD

**Issue by cancan101** [travis-ci/travis-ci#4586]
It looks like travis-ci builds my repo twice: once for the PR and once for the push. This happens even when the merge will be a FF such that the code is the same in the PR and the push.

I understand that there may be cases when the scripts key off of the PR ENV variable but it be nice to have the option to suppress PR builds when there is an FF merge.

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #3340 (at least in spirit).

**Comment by cancan101** [comment]
I am going to close this and made a comment in #3340 about env.
