### ISSUE TITLE
Travis-CI can't find my Organization repos for the entire day

### ISSUE THREAD

**Issue by opsigor** [travis-ci/travis-ci#4588]
Hello, i have an organization that has a repository and i can't find it on travis-ci. I was using another repository from the same organization and it was working fine, but then we moved to this new repository with the same .travis.yml and now i can't even see the organization in travis. I don't even know how many times i've tried to sync, resync, log out, clean cache and the usual answers that i've found in stackoverflow and here. I was hoping someone could give me a light so i can found the answer to this.

The repo i'm trying to see is [this one](https://github.com/GUMGA/components).
Thanks in advance!

**Comment by svenfuchs** [comment]
Hi @opsigor 

Thanks for the report. It seems as if this was a bug in our synchronization logic which has been fixed today. Could you please confirm that you can now see the expected organizations and repos?

Thanks! :heart:

**Comment by opsigor** [comment]
It's working now! Thank you for your support.
