### ISSUE TITLE
PHP nightly stopped working because archive became inaccessible

### ISSUE THREAD

**Issue by HillLiu** [travis-ci/travis-ci#4589]
I discover php7 behavior change recently.

bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command "tar xjf php-nightly-archive.tar.bz2 --directory ~/.phpenv/versions/" failed and exited with 2 during .
Your build has been stopped.

**Comment by robertfausk** [comment]
same here too

**Comment by ntwb** [comment]
Likewise, the same issue for me, appears to have started happening approx 7 hours ago:

Full error: 
```
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

The command "tar xjf php-nightly-archive.tar.bz2 --directory ~/.phpenv/versions/" failed and exited with 2 during .
```

Example job: This job fails before `before_install` even starts so I don't think it's my a .travis.yml issue https://travis-ci.org/ntwb/WP-API/jobs/73149031


In a related project PHP7 fails with the same error for all PHP7 jobs newer than 6 hours, and any jobs 7 hours or older work as expected

~7 Hour job passing: https://travis-ci.org/aaronjorbin/develop.wordpress/jobs/73116526

~6 hour job failing: https://travis-ci.org/aaronjorbin/develop.wordpress/jobs/73123580

**Comment by BanzaiMan** [comment]
Sorry about that. When I fixed the problem with an old (10 days) nightly, I forgot to make the uploaded archive publicly readable. I've fixed this now, so you should be able to use PHP nightly.

Thanks.

**Comment by ntwb** [comment]
@BanzaiMan Thanks, confirmed resolved :+1: https://travis-ci.org/ntwb/WP-API/jobs/73149653
