### ISSUE TITLE
public repository disappeared from travis-ci.org

### ISSUE THREAD

**Issue by grzegorzmazur** [travis-ci/travis-ci#4590]
My profile https://travis-ci.org/profile/grzegorzmazur seems to account for only 2 out of 3 public repositiories I've got on github. The missing one (grzegorzmazur/yacas) is the only one for which testing was actually enabled. The MIA repository is not shown anywhere on the webpage, and the CLI client keeps telling "repository not known to https://api.travis-ci.org/: grzegorzmazur/yacas".

**Comment by svenfuchs** [comment]
Thanks for the report, @grzegorzmazur!

It seems this was a bug in our synchronizing logic which has now been fixed. As far as I can see the repository should now be listed for you. 

:heart:

**Comment by grzegorzmazur** [comment]
You've got really impressive reaction time! The repository is visible and seems to work fine. Thanks a lot!

BTW, there's still a minor glitch, I'm not sure if it's even worth reporting - although I have 3 repositories,  travis claims that I've got 4. But of course this does not cause any problems.

Thanks,
Grzesiek
