### ISSUE TITLE
Provide phpdbg binary in nightly builds

### ISSUE THREAD

**Issue by bwoebi** [travis-ci/travis-ci#4593]
Phpdbg binary got in PHP 7 some functions crucial for code coverage, and is currently the only way for phpunit to generate coverage with PHP 7.
Hence it would be helpful to have phpdbg pre-installed on PHP 7 builds.

**Comment by BanzaiMan** [comment]
@bwoebi Could you elaborate on what this entails? I am not familiar with phpdbg, and I am not certain if we provide this for other non-7/non-nightly PHP runtimes.

**Comment by bwoebi** [comment]
Currently, you could provide it for 5.6 too (as phpdbg is bundled since 5.6). But I only see any importance for phpdbg since PHP 7 now.
phpdbg is just a binary comparable to e.g. php-cgi with a few internal options. (build option is `--enable-phpdbg`)

The request actually is to provide the binary at all, especially for PHP 7.

**Comment by BanzaiMan** [comment]
How do we offer phpdbg for 5.6? http://phpdbg.com/ says it is "Integrated into PHP 5.6 core!" Does that mean it's a part of 5.6? Then we don't do anything special to provide that capability for 5.6, and if we are to add it to PHP nightly (a.k.a. 7/7.0), we would need some help.

You can see how we build the PHP nightly runtime here: https://github.com/travis-ci/php-src-builder/blob/default/.travis.yml Your suggestions are welcome!

**Comment by bwoebi** [comment]
It is part of php-src since 5.6 and as said, just needs an `--enable-phpdbg` configure option.

I see a php-build directory in that file, but where does that come from?

**Comment by BanzaiMan** [comment]
`php-build` is pre-installed on the PHP image.

**Comment by bwoebi** [comment]
Okay, but how does that directory look like?

**Comment by BanzaiMan** [comment]
I believe it's a git clone of https://github.com/php-build/php-build.

**Comment by bwoebi** [comment]
Should be enough to `echo "--enable-phpdbg" >> ~/.php-build/share/php-build/default_configure_options` in `install` step in the .travis.yml file?

**Comment by BanzaiMan** [comment]
I honestly don't know. You can try cloning and try building yourself. (Testing would be a bit involved; you can either try using it with `phpenv` right after the compilation, or uploading it somewhere, pull it down to your local machine, and test it.)

**Comment by bwoebi** [comment]
I tried building it myself:

```PHP
# ls ~/.phpenv/versions/nightly/bin/
phar  phar.phar  php  php-cgi  php-config  phpdbg  phpize  pyrus  pyrus.phar
# ls ~/.phpenv/shims/
phar  phar.phar  php  php-cgi  php-config  phpdbg  phpize  pyrus  pyrus.phar
```

So, it should be there, but it isn't: https://travis-ci.org/amphp/amp/jobs/73371802#L581

I can't tell from here what's going wrong.

**Comment by BanzaiMan** [comment]
How did you get the list of files in `~/.phpenv/shims`? They are not present on the image.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/73412553#L92

Either it needs to be added to the nightly package building process, or you should add `~/.phpenv/versions/nightly/bin` to `$PATH`.

**Comment by bwoebi** [comment]
I meant, I tried to build it locally, and it landed there. … Well, it turns out by running `phpenv rehash`, it lands there too. And works…

I thought that would be done by your build scripts?

**Comment by bwoebi** [comment]
Compare: https://travis-ci.org/bwoebi/travis-test/builds/73417136#L86
to: https://travis-ci.org/bwoebi/travis-test/builds/73416839#L87

why is this difference?!

**Comment by BanzaiMan** [comment]
Probably because the nightly build process doesn't include `phpenv rehash`, and that the shims for `phpdbg` (and others, I guess)

**Comment by BanzaiMan** [comment]
The build passed. Could you try nightly again without `phpenv rehash` and see if you can see `phpdbg`? Thanks.

**Comment by bwoebi** [comment]
I triggered a re-run, but still doesn't pass… Do I have to wait for some cronjob until it is recreated? (https://travis-ci.org/bwoebi/travis-test/builds/73417136)

**Comment by BanzaiMan** [comment]
No, you don't. That means there is a little more work involved. I'll take a look at this next week.

**Comment by kelunik** [comment]
@BanzaiMan You need the `phpenv rehash` after the cURL call to AWS when running other builds, not when building it. `phpenv rehash` should be always used after installing versions, and PHP 7 is only installed when the build runs and is it's downloaded from AWS.

**Comment by BanzaiMan** [comment]
See https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/434582; after `phpenv rehash`, `phpdbg` was found for `nightly` and `7.0.0beta2`, but not for 5.5 and 5.6. I presume the failure with 5.5 is acceptable, but I am not sure why it's not found in 5.6.

Either way, that PR should fix the issue.

**Comment by kelunik** [comment]
:+1:

I don't know how important it is in 5.6, probably not that important. We just need it for 7 to have coverage data, because xDebug isn't ready yet.

**Comment by BanzaiMan** [comment]
All right, then. This has been deployed to production.
