### ISSUE TITLE
Assume sudo: false if sudo not used

### ISSUE THREAD

**Issue by dcousens** [travis-ci/travis-ci#4594]
Thoughts?

**Comment by BanzaiMan** [comment]
Thanks for opening the issue.

This detection is already in place for repositories created after a cutoff date (currently January 1, 2015). This is explained in http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure.

**Comment by dcousens** [comment]
Awesome!  Thanks @BanzaiMan

**Comment by dcousens** [comment]
Would it be possible for TRAVIS users to *opt-in* to this?  I have several repositories that were created before the cut-off that would benefit from it,  and I'd rather not have to go around adding `sudo: false`.

**Comment by BanzaiMan** [comment]
The infrastructure is chosen for each job, which means it has to be specified in `.travis.yml`.

**Comment by dcousens** [comment]
> This detection is already in place for repositories created after a cutoff date

To be clear, this is based on its registration with TRAVIS?  The age of the `.travis.yml`?  Or the time since the initial commit of the repository?

**Comment by BanzaiMan** [comment]
It is determined by the date on which the repository was first enabled on Travis CI.

**Comment by joshk** [comment]
Hi @dcousens 

You are right that the user experience of selecting the stack-of-choice is a little more complicated than we would like.

The detection date is based on when we created the repo in our DB, which is usually based on when you signed up and sync'd that repo.

Although not ideal, Hiro is right that you will need to add this to your .travis.yml file. Adding this to a repo setting, or user setting, is not something we are looking at doing at this time sorry.

Thank you for the great feedback though, we will take this into account next time we plan in a similar system and user wide change.

Josh

**Comment by dcousens** [comment]
> It is determined by the date on which the repository was first enabled on Travis CI.

So I can't delete those repos/my account and just re-add it?  That would still be quicker than committing this.
