### ISSUE TITLE
mysql --version for addons: mariadb plugin displays client version not server version

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#4595]
added https://github.com/travis-ci/travis-build/commit/940fd45e714dc664554ecd546d0254f49717b123

travis-ci/travis-build/pull/483 for a more correct version

**Comment by BanzaiMan** [comment]
Do we ever have a situation where the client and the server versions differ?

**Comment by grooverdan** [comment]
all the time. The addon installs mariadb-server and not mariadb-client (and there isn't a good reason too).

The mysql client is the default from the mysql-client package in the base image.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/builds/73984048#L94-L97 shows that client packages are also installed.

**Comment by grooverdan** [comment]
ah, forgot the client was a dependency of the server. Does seem like an indirect way to go about though.

**Comment by BanzaiMan** [comment]
Closing this.
