### ISSUE TITLE
Having trouble using GitHub API from a  VirtualBox VM running on a Mac VM

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#4599]
I am seeing this in one of my builds. This suggest that we can't reach sites like <https://api.github.com/repos/boot2docker/boot2docker>. As I am able to load this fine locally, this does not seem to be a GitHub issue.

    error in run: Failed to get latest release: Get https://api.github.com/repos/boot2docker/boot2docker/releases: dial tcp: lookup api.github.com on 10.182.0.19:53: read udp 10.182.0.19:53: i/o timeout

**Comment by BanzaiMan** [comment]
Could you point to the build log URL that shows this problem?

**Comment by jakirkham** [comment]
Absolutely, here is a log ( <https://travis-ci.org/jakirkham/mac_boot2docker_startup_app> ).

**Comment by BanzaiMan** [comment]
How is networking configured on this VB image? Is there something we are supposed to on this image you are creating?

**Comment by jakirkham** [comment]
@BanzaiMan, I don't believe this is an issue with VB image used internally. I attempted to simply run the following. Normally, this would print out a list of releases.

    $ curl https://api.github.com/repos/boot2docker/boot2docker/releases

In the Travis CI build this doesn't occur. Instead, I get the following error message below.

    {
      "message": "API rate limit exceeded for 208.78.110.199. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
      "documentation_url": "https://developer.github.com/v3/#rate-limiting"
    }

See this build for more details ( https://travis-ci.org/jakirkham/mac_boot2docker_startup_app/builds/74172873 ).

**Comment by BanzaiMan** [comment]
OK, so this is a variation of #4073. To GitHub, your unauthenticated API requests come from the same IP address (ours), and it is rate limiting your API request.

Could you try creating a special-purpose access token and installing it on your VirtualBox when you make the API call?

**Comment by jakirkham** [comment]
Thanks for the advice. I will look into this and get back to you.

**Comment by jakirkham** [comment]
I believe that your proposed solution would work. However, it ended up not being a priority to implement it as the `boot2docker` CLI was shortly after deprecated and `docker-machine` was provided instead. I don't see that App being moved to `docker-machine`.
