### ISSUE TITLE
Travis doesn't find new commits after repository renamed

### ISSUE THREAD

**Issue by akz92** [travis-ci/travis-ci#4601]
3 days ago I renamed my repository and since then travis isn't running new commits. I've already recreated my account hook and the repository webhook but nothing solved the problem. I have already refreshed my profile info and it changes the repository name correctly but still not finding new commits. 
EDIT: Other services like CodeClimate are working fine. The repository url is:  https://github.com/akz92/estudeantes

**Comment by joshk** [comment]
Hi @akz92 

I checked https://travis-ci.org/akz92/estudeantes/requests and see that you have disabled 'push' builds on the settings page for the repo.

You can go to https://travis-ci.org/akz92/estudeantes/settings and enable push builds and everything should work as expected.

Let me know if that helps.

Josh

**Comment by akz92** [comment]
Thank you @joshk, that solved the problem.
