### ISSUE TITLE
Request: support python minor version 2.7.8

### ISSUE THREAD

**Issue by bdarnell** [travis-ci/travis-ci#4603]
Python 2.7.9 introduced significant changes to the `ssl` module; I would like to ensure that my code is compatible with both the old and new versions. Since version `2.7` in `.travis.yml` is always the latest version in the 2.7.x series, the only way to test the old `ssl` interface on travis-ci is to use Python 2.6 instead. But Python 2.6 is quite old now and many projects are dropping support for it, so it would be better if an older version in the 2.7 series were available for testing. 

I don't think there's a need to make the full array of minor versions available, just one version that predates the `ssl` changes should suffice (Python is normally good about compatibility between minor versions, but since the `ssl` module is security-critical they backported a bunch of features from the 3.x branch at once). Also note that many distributors (including ubuntu) have backported these changes *without* changing version numbers, so if you're not building python from source make sure you're getting a version without the updated ssl module (`python -c "import ssl; print(hasattr(ssl, 'SSLContext'))"` prints `True` on python 2.7.9+ and `False` on 2.7.8)

**Comment by jayvdb** [comment]
+1 I would use a pre 2.7.9 in my build matrix.

**Comment by BanzaiMan** [comment]
Has this issue been reported upstream to the Python team?

**Comment by BanzaiMan** [comment]
I've built the 2.7.8 package, and it's available now.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/73895244#L83

**Comment by bdarnell** [comment]
The upstream python team is well aware of the compatibility risks of the changes in 2.7.9, but this isn't really about an incompatibility per se. I just want to make sure that my code has fallbacks in place when the new functions introduced by 2.7.9 are not present.

Thanks for the quick response.
