### ISSUE TITLE
namespace name `VisualStudio' does not exist in the namespace `Microsoft'

### ISSUE THREAD

**Issue by fredatgithub** [travis-ci/travis-ci#4605]
Hello,
I have this error when compiling my project which is a Microsoft Unit test project
https://travis-ci.org/fredatgithub/MyFavoriteQuotes
I have a travis.yml file in my project
https://github.com/fredatgithub/MyFavoriteQuotes
It compiles ok on Visual Studio 2015
can you check if there's something missing in your script ?
BTW your CI service is awesome, I love it :O)

**Comment by fredatgithub** [comment]
Here is the log file

**Comment by fredatgithub** [comment]
here is a screenshot
![errot](https://cloud.githubusercontent.com/assets/6720055/9038493/e4c05dec-39f4-11e5-9115-0d075e8355e7.png)

**Comment by Joshua-Anderson** [comment]
@fredatgithub Travis C# builds use the mono runtime, which doesn't support MSTest. I'd reccomend switching to a testing framework that does support mono, like NUit, which mono does support.

/cc @akoeplinger @nterry

**Comment by fredatgithub** [comment]
ok thanks for the answer

**Comment by fredatgithub** [comment]
Is there a command disable unit test like Test: off or false ?

**Comment by akoeplinger** [comment]
You can build only the main project by adding something like the following to your .travis.yml:

```
script:
  - xbuild /p:Configuration=Release MyFavoriteQuotes/MyFavoriteQuotes.csproj
```

**Comment by fredatgithub** [comment]
thanks
