### ISSUE TITLE
Build status does not update on GitHub if build is canceled

### ISSUE THREAD

**Issue by mnquintana** [travis-ci/travis-ci#4607]
### Steps to reproduce

1. Trigger a build on Travis from a Pull Request
1. Build status on GitHub should be pending
1. Cancel the build from the Travis web UI
1. Build status on GitHub will still be pending
1. Wait `x` amount of time (days?) - build status on GitHub will still be pending

### Example

![use_latest_npm_in_build_by_mnquintana_ _pull_request__7249_ _atom_atom](https://cloud.githubusercontent.com/assets/823545/9043824/549b875e-39e6-11e5-930f-68aba156f5e2.png)

[The top build](https://travis-ci.org/atom/atom/builds/73929340) was canceled - [the bottom build](https://travis-ci.org/atom/atom/builds/73929425) is currently running.

Let me know if there's any more information you need!

**Comment by kbrock** [comment]
It does feel like it needs a few states: `"running"`, `"succeeded"`, `"failed"`, `"canceled"`.

**Comment by BanzaiMan** [comment]
I think this is a case where GitHub doesn't completely cover the CI life cycle. Currently, [the valid statuses](https://developer.github.com/v3/repos/statuses/) are: `pending`, `success`, `error`, or `failure`.

When you cancel a build, there is no corresponding status on GitHub, and there is nothing for us to do. It is an eye sore, and if it is something you cannot live with, I suggest restarting the build.

I'm closing this for now.
