### ISSUE TITLE
`cache: bundler` is broken

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4608]
If there is no cache exists, `cache: bundler` does not work.

More precisely, it appears to find a cache, adds an empty list of directories to the directories to watch, then fails to create a cache to upload.

https://travis-ci.org/travis-ci/travis-core/jobs/73917402#L3984

```sh-session
$ bundle clean
Resolving dependencies......
schanges detected, packing new archive
FAILED: tar -Pzcf /home/travis/.casher/push.tgz 
tar: Cowardly refusing to create an empty archive
Try `tar --help' or `tar --usage' for more information.
uploading archive
failed to upload cache
curl: Can't open '/home/travis/.casher/push.tgz'!
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by BanzaiMan** [comment]
In the meantime, giving the directories works.

```yaml
cache:
  directories:
    - vendor/bundle
```

for example.

**Comment by BanzaiMan** [comment]
False alarm. The repo was overriding the `install` section.

**Comment by joshk** [comment]
I don't think this is a false alarm. I mean, you should be able to use that caching directive, override the `install` section, and not have that error in the caching saving section, right?

**Comment by BanzaiMan** [comment]
Sort of. I think we have a related discussion in #3239.
