### ISSUE TITLE
Additional options for the Sauce Labs addon are not working

### ISSUE THREAD

**Issue by vlamanna** [travis-ci/travis-ci#4609]
When using the additional options in the Sauce Labs addon, I was getting the following error message:
/home/travis/build.sh: line 490: export: `*.travis.salesfloor.net': not a valid identifier

I've submitted a pull request for fixing the bug here:
https://github.com/travis-ci/travis-build/pull/498

**Comment by BanzaiMan** [comment]
I've merged and deployed the PR. It should work from what I saw, but do let us know if you run into problems.
