### ISSUE TITLE
Add flat style for build badges

### ISSUE THREAD

**Issue by kelunik** [travis-ci/travis-ci#4612]
Would be nice if you could add a flat style of the build badges just like http://shields.io/ does.
That way we don't have to use their external API that stress all servers more.

**Comment by rdlowrey** [comment]
:+1:

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. Could you elaborate on what you want to see happen? On our sites, https://travis-ci.org and https://magnum.travis-ci.com, the images are served from their respective servers, and I am not sure what external API stress you are referring to.

**Comment by kelunik** [comment]
I want a `style` parameter for different badge styles:

![Build Status](https://img.shields.io/travis/amphp/amp.svg?style=flat-square) ![Build Status](https://img.shields.io/travis/amphp/amp.svg)

Currently, we need to request shields.io which queries your API and then delivers the image in the specified style. Would be nice if we could directly use `https://travis-ci.org/amphp/amp.svg?branch=master&style=flat-square`.

**Comment by joshk** [comment]
Using their API vs ours is no issue, at least for us :)

But I'm sorry, we do not have plans to add support for multiple styles right now. We may change to square corners in the future, but there is no ETA or decision on this.

I'm going to close this issue for the time being.

Thank you for the feedback.

**Comment by kelunik** [comment]
It may be an issue for them, at least the image response time isn't that good sometimes.
It would even shrink the images from `725` to `338` bytes. ;-)

Anyway, thanks for your clear feedback.

**Comment by joshk** [comment]
Totally understand, and if anything, we need to work on making our API faster :)

I do understand that it is nice to have all buttons match, one issue we have is that once we add a style, we are also committing to support it, which also means taking feedback from other users on changes they might want too.

I will consider this for the future, but will leave the issue closed for the time being.

Thanks for the awesome feedback!

**Comment by hassankhan** [comment]
This should be a fairly minor change to implement if you're already using Shields, there are only three kinds of styles AFAIK, the default (`plastic`), `flat` and `flat-squared`.

**Comment by SebastianBoldt** [comment]
Any Updates on that issue?

**Comment by vineetchoudhary** [comment]
shields.io support travis-ci. So, for the flat square icon, you can use shields.io like this

```
https://img.shields.io/travis-ci/<PROJECT-OWNER>/<PROJECT-NAME>.svg?style=flat-square
```

Like, for https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation you can use https://img.shields.io/travis-ci/vineetchoudhary/AppBox-iOSAppsWirelessInstallation.svg?style=flat-square

```
[![Build Status](https://img.shields.io/travis-ci/vineetchoudhary/AppBox-iOSAppsWirelessInstallation.svg?style=flat-square)](https://travis-ci.org/vineetchoudhary/AppBox-iOSAppsWirelessInstallation)
```
[![Build Status](https://img.shields.io/travis-ci/vineetchoudhary/AppBox-iOSAppsWirelessInstallation.svg?style=flat-square)](https://travis-ci.org/vineetchoudhary/AppBox-iOSAppsWirelessInstallation)

**Comment by changkun** [comment]
Hi all, the above proposed solution doesn't work anymore. The badge now is in "404 badge not found" status.

**Comment by isfett** [comment]
the new path for img.shields.io is

```
https://img.shields.io/travis/<PROJECT_OWNER>/<PROJECT-NAME>/<BRANCH>?style=flat-square
```

Example for @vineetchoudhary Project

```
[![Build Status](https://img.shields.io/travis/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/master?style=flat-square)](https://travis-ci.org/vineetchoudhary/AppBox-iOSAppsWirelessInstallation)
```

[![Build Status](https://img.shields.io/travis/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/master?style=flat-square)](https://travis-ci.org/vineetchoudhary/AppBox-iOSAppsWirelessInstallation)
