### ISSUE TITLE
Cannot set MAVEN_OPTS in new containerized environment

### ISSUE THREAD

**Issue by strubell** [travis-ci/travis-ci#4613]
I am currently using a workaround in order to set custom MAVEN_OPTS in my Travis build that requires sudo (see issue #1689). It appears that @gildegoma submitted PR travis-ci/travis-cookbooks#475 to resolve this issue but it doesn't look like it's been deployed yet. Please deploy these changes so that teams who need to set custom MAVEN_OPTS can migrate to the new containerized environment, and also not rely on a workaround to the problem. Thanks!

**Comment by BanzaiMan** [comment]
The change has been reverted. See #4621.

**Comment by arahuja** [comment]
Is there a new resolution to this or still the workaround?

**Comment by strubell** [comment]
afaik still the old workaround until someone can fix the changes in travis-ci/travis-cookbooks#475 to not produce the issues reported in #4621

**Comment by jnorgan** [comment]
If you want to use container-based builds (not relying on sudo), you can echo what you want into a $HOME/.mavenrc file and that will take precedence over /etc/mavenrc, like so:

***in .travis.yml***
```script:
- echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc

**Comment by buckett** [comment]
If you're using the standard java scripts then you will probably want to use the before_install phase of the build to setup the `~/.mavenrc` file.

     before_install: echo "MAVEN_OPTS='-Xmx1536m'" > ~/.mavenrc

**Comment by axelfontaine** [comment]
+1

**Comment by strubell** [comment]
@jnorgan thanks, works like a charm!

**Comment by sebastiankirsch** [comment]
Even if I would be able to set MAVEN_OPTS properly at the beginning, the approach of using /etc/mavenrc prevents the [Maven Invoker Plugin](http://maven.apache.org/plugins/maven-invoker-plugin/) from being used properly.

The plugin uses the property [`mavenOpts`](http://maven.apache.org/plugins/maven-invoker-plugin/run-mojo.html#mavenOpts) with which to configure the Maven execution (this simply exports its own `MAVEN_OPTS` environment variable) - which will always be overridden by the /etc/mavenrc instructions.

So the `/etc/mavenrc` approach makes using the invoker plugin with mavenOpts impossible.

**Comment by sebastiankirsch** [comment]
And by the way:

    before_install: export MAVEN_SKIP_RC="true"

skips execution of `/etc/mavenrc` and `~/.mavenrc`.

In contrast to what @jnorgan said, `~/.mavenrc` does not take precedence over `/etc/mavenrc`; it is merely executed afterwards. Thus, missing out to override things set by `/etc/mavenrc` may still screw you in spite of having `~/.mavenrc` in place (at least that is the case for Maven 3.3.3).
