### ISSUE TITLE
APT installation failures in log obscured under collapsed step

### ISSUE THREAD

**Issue by dbarnett** [travis-ci/travis-ci#4617]
When an APT package fails to install in container-based builds, the APT step is collapsed and there's no indication at a glance that anything went wrong:
![travis_apt_collapsed](https://cloud.githubusercontent.com/assets/65244/9083731/9e8dfb1c-3b21-11e5-91b7-a2aaa58d97ba.png)

After expanding it, you see failure messages like "Disallowing packages":
![travis_apt_expanded](https://cloud.githubusercontent.com/assets/65244/9083732/a179a33a-3b21-11e5-9416-e6d991324934.png)

Would be great if that were more obvious at a glance.

**Comment by BanzaiMan** [comment]
The logs trends to be long and tedious. Perhaps it is better to fail the build if the installation fails here.

**Comment by dbarnett** [comment]
I wouldn't mind failing the build. FWIW, this happened when I was first setting up the test and looking pretty closely at the logs to troubleshoot. If the line had been a different color or expanded by default due to the error, I'm pretty sure that would have been perfect for me.

**Comment by BanzaiMan** [comment]
@joshk What do you think?

**Comment by gioele** [comment]
More than one year later, I have had the same experience: I spent half an hour trying to understand what the problem could be before clicking by accident on the apt step to read this

> Installing APT Packages (BETA)
>
> Disallowing packages: autoconf, automake, autotools-dev, bzip2, gcc-4.9, libtool, libjpeg-dev, libtiff4-dev, libpng12-dev, libfreetype6-dev, libgif-dev, libx11-dev, libxml2-dev, libpango1.0-dev, libcairo2-dev, python3.5-dev

As @BanzaiMan said, Travis should either fail the build as soon as the apt step fails or, at least, keep the step expanded in case one of the packages cannot not be installed.
