### ISSUE TITLE
maven integration tests started failing

### ISSUE THREAD

**Issue by mkristian** [travis-ci/travis-ci#4621]
since yesterday some (not all) maven integration tests started failing 
https://travis-ci.org/jruby/jruby/builds/73694801
https://travis-ci.org/jruby/jruby/builds/73608535

the tests are using the invoker plugin. the errors are either one of those:
```
[INFO] /home/travis/.m2/wrapper/dists/apache-maven-3.3.1-bin/22bc38rir9hjukbpmqefdsp306/apache-maven-3.3.1/bin/mvn: 3: export: -Dmaven.repo.local: bad variable name
```
```
[exec] [INFO] /usr/local/maven-3.2.5/bin/mvn: 3: export: -Xmx512m: bad variable name
```

the error disappear when I add to .travis.yml
```
 before_script:
  - export MAVEN_SKIP_RC=true
```

**Comment by BanzaiMan** [comment]
@mkristian Currently, `/etc/mavenrc` contains this line when your build starts:

```sh
export MAVEN_OPTS=${MAVEN_OPTS:-"-Dmaven.repo.local=$HOME/.m2/repository -Xmx512m -XX:MaxPermSize=192m"}
```

Perhaps this is not the right content?

**Comment by mkristian** [comment]
nope does not look right

**Comment by BanzaiMan** [comment]
Do you have any suggestions on improving it?

Previously, it was 
```shell
export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xmx512m -XX:MaxPermSize=192m"
```

Which job has this message in the log? There are too many to really go through.

**Comment by mkristian** [comment]
sorry I did not parse the export statement correctly, but after trying it out on my ubuntu terminal - it actually behaves OK.

the easiest to see the error is in https://travis-ci.org/jruby/jruby/jobs/74246786#L3351

the maven launcher itself does something like
```
MAVEN_OPTS="$(concat_lines "$MAVEN_PROJECTBASEDIR/.mvn/jvm.config") $MAVEN_OPTS"
```
to "update" the MAVEN_OPTS. maybe that is similar what you want o achieve with new "export"

**Comment by cgruber** [comment]
Please roll this back so that maven tests can function until you resolve the ideal configuration.  This is breaking all sorts of projects in the google/ organization, is preventing auto-snapshotting, etc.

**Comment by eamonnmcmanus** [comment]
Hey, this issue has 3740 stars, so it looks as if thousands of people are affected. Could things be put back the way they were before the breakage while you figure out how to achieve what you're trying to do?
