### ISSUE TITLE
Can not build C#6.0 on Mono

### ISSUE THREAD

**Issue by RonnChyran** [travis-ci/travis-ci#4622]
C# 6.0 (Tools version 14.0) doesn't build at all on Mono. Attempting to [force ToolsVersion 14.0](https://travis-ci.org/SnowflakePowered/snowflake/builds/74334753) results in xbuild telling me unknown tools version '14.0'. Building on TV 12.0 [won't either work](https://travis-ci.org/SnowflakePowered/snowflake/builds/74335413) as TV12.0 (C#5) doesn't have support for string interpolation and other C# 6.0 features.

This despite setting the mono version to 4.0 and then nightly. As far as I'm aware Mono 4.0 does indeed have support for such features but I can't get them to work on travis.

**Comment by akoeplinger** [comment]
@RonnChyran that's a bug in Mono's C#6 string interpolation implementation with the code in [JSResponse.cs#L34-L43](https://github.com/SnowflakePowered/snowflake/blob/6e968482938491740cde7db965f2fcc95b1d11c2/Snowflake/Ajax/JSResponse.cs#L34-L43). I filed https://bugzilla.xamarin.com/show_bug.cgi?id=32832 for it.

One workaround for now is to refactor it into something like the following:

```diff
-if (request.MethodParameters.ContainsKey("jsoncallback"))
-{
-    return request.MethodParameters["jsoncallback"] + $@"({
-        JsonConvert.SerializeObject(new Dictionary<string, object>
-        {
-            {"request", request},
-            {"payload", output},
-            {"success", success},
-            {"type", "methodresponse"}
-        })}
-    );";
-}
-return JsonConvert.SerializeObject(new Dictionary<string, object>
+var json = JsonConvert.SerializeObject(new Dictionary<string, object>
 {
     {"request", request},
     {"payload", output},
     {"success", success},
     {"type", "methodresponse"}
 });
+
+if (request.MethodParameters.ContainsKey("jsoncallback"))
+{
+    json = request.MethodParameters["jsoncallback"] + $"({json});";
+}
+
+return json;
```

**Comment by RonnChyran** [comment]
That seemed to have fixed the build. I'm going to close this for now then, but there should be a note made on the C# documentation that string interp doesn't work with a dictionary initializer.

**Comment by akoeplinger** [comment]
@RonnChyran great :) the bug was just fixed in https://github.com/mono/mono/commit/87141d4dfc4162316ff89a5ce631e55e045cb011 and the upcoming Mono 4.2 release, I don't think it's worth adding it to the docs right now since such code isn't very common yet and it'll just work before long anyway.
