### ISSUE TITLE
Status badge for each OS of a build

### ISSUE THREAD

**Issue by thejustinwalsh** [travis-ci/travis-ci#4623]
Is it possible to get a passing/failing badge per operating system using travis, or shields.io?

I understand the concept of a build being a complete unit, and if your library or application is expected to support multiple operating systems, a failing build on an OS would indicate your product is broken. Makes perfect since most of the time.

However, I do find value in knowing what particular os is broken at a glance, so either I or the platform maintainer can identify what OS is causing problems in particular. This becomes especially important when working with C++11/14/17 as MSVC 2015 vs clang vs gcc all have different levels of support for the new features of the standard.

**Comment by roidrage** [comment]
Thank you for bringing this up.

This isn't possible right now, and it's not a feature we have immediate plans for. We prefer to view a build as a whole, with the status badge being an indicator, and the build's matrix results being the single source of truth.

**Comment by weitjong** [comment]
We have worked around the problem by showing the status badges of our branches. The branches are mirror image of the master branch, except the ```.travis.yml``` which differs for each branch to tell Travis-CI to run different build tests for each target platforms. We could also group a few related target platforms into one branch. We have scripted our build system to do all this branching work automatically on each commit, so there is no branch maintenance overhead.

**Comment by kknox** [comment]
I would also like to see independent 'build badges' for each independent 'build job'.  Naively, I think both behaviors could be supported:
`https://travis-ci.org/XXX/YYY.svg?branch=master` could be a URL format that success/fail is the logical AND of all sub-jobs.

`https://travis-ci.org/XXX/YYY.svg?branch=master&job=1` could be a URL format that reports success/fail for a particular job

**Comment by mosra** [comment]
I would also be very happy to see this, I don't want to introduce otherwise meaningless branches just to differentiate OSes in Travis.

Another possible solution: allowing to specify different file than ".travis.yml" at repository root, then the user could have one "travis-linux.yml" and another "travis-osx.yml", having different badge for each and possibly even far more simplified build scripts that don't have to handle platform differences in single file.

**Comment by BanzaiMan** [comment]
Thanks for the input. For the time being, we have no plans to implement this. Thanks for your interest.
