### ISSUE TITLE
All builds stuck at 'created' for > 24 hours

### ISSUE THREAD

**Issue by wibblymat** [travis-ci/travis-ci#4625]
The project at https://travis-ci.org/google/WebFundamentals/builds hasn't had a build actually start since yesterday. I have cancelled and restarted all of the builds but nothing changed.

@petele @crhym3

**Comment by BanzaiMan** [comment]
Hello there!

Sorry for the troubles. This was a fallout from the Mac builds issue from earlier this week. Several Mac builds were stuck at the top of the queue for the organization `google`, and nothing was getting built.

I see now that the stuck builds have been canceled and the queue is moving again. It takes a while, unfortunately, for WebFundatmentals builds to be processed, as there are a few dozen jobs are queued up ahead of them. As I write this, https://travis-ci.org/google/guava/pull_requests are running.

I'm closing this now, but if you still see problems after a while (say a couple of hours), do let us know.

**Comment by wibblymat** [comment]
Thanks for the explanation, hadn't realised that the queue was shared across the org.
