### ISSUE TITLE
maven settings.xml refers to non existent URL nexus.codehaus.org

### ISSUE THREAD

**Issue by sns-seb** [travis-ci/travis-ci#4629]
On a container-based host, I find that `/home/travis/.m2/settings.xml` defines a repository for codehaus snapshots artifacts which links to `nexus.codehaus.org`:

``` xml
        <repository>
          <id>codehaus-snapshots</id>
          <name>Codehaus (snapshots)</name>
          <releases>
            <enabled>false</enabled>
            <updatePolicy>always</updatePolicy>
            <checksumPolicy>warn</checksumPolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>https://nexus.codehaus.org/snapshots/</url>
        </repository>
```

The host `nexus.codehaus.org` does not exist any more, which results into build errors whenever maven tries and fail to resolve this host.

 Codehaus snapshots seem to be now hosted by SonarType (at least some of them): `https://oss.sonatype.org/content/repositories/codehaus-snapshots/`

**Comment by BanzaiMan** [comment]
Sorry for the issue. For the time being, please edit `~/.m2/settings.xml`.

**Comment by sns-seb** [comment]
no pb, I'll work around it

**Comment by msavy** [comment]
For anyone hitting this same issue, I'll save you a bit of time and share what I did:

```
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
```

**Comment by helix84** [comment]
Any chance of fixing this so that we don't have to use the sed workaround?

**Comment by jonespm** [comment]
The apache repo wasn't working for us this week. I found the builds more reliable just removing this settings.xml instead of using the sed command above. Unless travis was actually setting up caching proxies I don't see the point of overriding the known good working repositories in our build with these ones that are out of date and/or not updated. 

```
before_install:
  - rm ~/.m2/settings.xml
```

**Comment by jeacott1** [comment]
I've found that if I dont use --settings .maven.xml, but instead do 
before_install:
  - mkdir -p $HOME/.m2 && cp .maven.xml $HOME/.m2/settings.xml

it works.

**Comment by Oskoss** [comment]
Just an update on 2/10/2017 having this same issue.

**Comment by BanzaiMan** [comment]
Hi, everyone, sorry for the long delay. We've pushed a fix a few minutes ago. Please report how it works for you.

Thank you!
