### ISSUE TITLE
Google Chrome setuid issues

### ISSUE THREAD

**Issue by caspervonb** [travis-ci/travis-ci#4630]
My chrome tests _sometimes_ [fail](https://travis-ci.org/caspervonb/amok/builds/74490276) with the following

``` sh
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```

I'm installing chrome with `sudo apt-get` so the builds are run on legacy, not the new docker hotness.

``` sh
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
```

This might be a duplicate of https://github.com/travis-ci/travis-ci/issues/938 **but** here's where I'm confused, 7/10 times, my tests run and **pass** which seems different from the previously mentioned issue.

**Comment by BanzaiMan** [comment]
Many Google Chrome releases have happened since. If this is still happening, please open a new issue.
