### ISSUE TITLE
python 3 minor versions bug fixes

### ISSUE THREAD

**Issue by Chris7** [travis-ci/travis-ci#4632]
My builds are failing due to a bug fixed in python 3.4.3 versus 3.4.2 (and presumably the 3.3.6 vs. 3.3.5). Are there any plans to upgrade these python distributions to their latest releases on travis?

**Comment by BanzaiMan** [comment]
Python 3.4.3 and 3.3.6 are available now with

```yaml
python:
  - 3.4.3
  - 3.3.6
```
