### ISSUE TITLE
Travis won't run for pull requests made by contributors without write access

### ISSUE THREAD

**Issue by fenollp** [travis-ci/travis-ci#4633]
Hi,

In pull requests opened by people without write access to our project Travis CI never runs a job.
See here: https://github.com/2600hz/kazoo/pull/1189

For pull requests opened by the company's people Travis does run the jobs.
See here: https://github.com/2600hz/kazoo/pull/1192

Is this normal behaviour?

How can I make Travis run jobs for any kind of pull requests?

**Comment by BanzaiMan** [comment]
I believe this is due to the merge conflict in https://github.com/2600hz/kazoo/pull/1189.

**Comment by fenollp** [comment]
@BanzaiMan nah, if you look at all the PRs you see that Travis is rarely run: https://github.com/2600hz/kazoo/pulls

People who have write access are k-anderson, jamesaimonetti, macpie, lazedo and I. Other people's PRs are never run by Travis

**Comment by joshk** [comment]
I had a quick check and I see we are missing a user with admin rights over the repo. 

Could you please have someone log into Travis who is an admin for the repo?

Then you can close and reopen a repo and see if it tests correctly.

**Comment by fenollp** [comment]
@joshk wait, how is this even possible?

Hm.. could you set @k-anderson or @jamesaimonetti manually as the admin?

**Comment by joshk** [comment]
@fenollp it looks like who ever was 'admin' logged out or revoked their token.

We can not set manual admins, we base this off GitHub permissions.

Please have someone who is admin for the repo on GitHub relogin into Travis and resync their account.

Thanks a bundle

**Comment by fenollp** [comment]
@joshk Ok one last thing.

Now that we have assigned an admin to the project, how do we get Travis to pick up on all the PRs that already exist?

**Comment by fenollp** [comment]
Ah! Got it: close then reopen the PRs!
