### ISSUE TITLE
Can't get C++11 to build using Make with Travis.

### ISSUE THREAD

**Issue by ButchDean** [travis-ci/travis-ci#4634]
Hi guys,

I honestly do not know how to fix the 

cc1plus: error: unrecognized command line option ‘-std=c++11’

message, and it is slowly driving me crazy. [Here](https://github.com/ButchDean/PlayingCardsCPP/tree/addtravis) is my repo and [here](https://travis-ci.org/ButchDean/PlayingCardsCPP) is the Travis report. My [makefile](https://github.com/ButchDean/PlayingCardsCPP/blob/addtravis/Makefile) builds everything fine locally.

Any help much appreciated, I've been using Travis for five days and would like it to be able to work with my C++11 projects.

Thanks.

**Comment by ButchDean** [comment]
I got it working by using Clang instead of g++. Leaving open regardless.

**Comment by joshk** [comment]
Thanks for the update @ButchDean 

Since you have it working, can we close this now?

**Comment by ButchDean** [comment]
Sure @joshk . Was only leaving open because it was a workaround rather than a fix. Closing.

**Comment by joshk** [comment]
Ok, what would you suggest the fix be? Sorry but we don't have specific knowledge in this area so need any and all guidance we can get :)

**Comment by ButchDean** [comment]
My workaround was to simply go from g++ to clang(++). So in my makefile I originally had:

```g++ simple.cpp -std=c++11 -o simple```

but Travis kept failing to recognize the -std flag. The workaround was to use clang instead:

```clang++ simple.cpp -std=c++11 -o simple```

And that was it. I don't mind either way but it would be great if it worked with g++ C++11 too.

Note you have to install clang too, pretty much like anything else for the Travis VM. My [.travis.yml](https://github.com/ButchDean/PlayingCardsCPP/blob/master/.travis.yml) shows how to do this.

**Comment by cotsog** [comment]
Hey @ButchDean!

The `-std=c++11` switch has only been available in gcc/g++ 4.7 and higher. The version of gcc/g++ in your build is 4.6.3. In version lower than 4.7 you need to use the following switch to enable C++11 features: `-std=c++0x`.

You can have a look at the following .travis.yml file that will install gcc/g++ 5.0 which supports C++11 and even C++14:

https://gist.github.com/cotsog/3ce84675af0d74438d91

This way you can use the following switches: `-std=c++11` or `-std=c++14`.

Hope this helps.

**Comment by ButchDean** [comment]
Hey @cotsog,

Thank you so much for your input. I tried your travis file on a [new branch](https://github.com/ButchDean/PlayingCardsCPP/tree/trygccagain) but it still fails, not recognizing the switch. I'm a little puzzled still as I remember trying later versions of g++ after 4.7 (in fact I tried against 4.9 which is on my system) with this same result.

Am I missing something?

**Comment by cotsog** [comment]
No problem @ButchDean!

I think the .travis.yml file I gave you was missing a line to redo the symlink for g++. Here it is:

- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++

Let me know if this works.

**Comment by ButchDean** [comment]
It works perfectly now! Thank you so much, @cotsog! You wouldn't believe how much this has been bugging me.

I'm happy now. Thanks again!
