### ISSUE TITLE
On the Mac, Ruby 1.9.3 does not have net-ssh (2.9.2 or lower) pre-installed and attempts to install net-ssh 2.10.1.rc1 instead, causing Rackspace deployment failure

### ISSUE THREAD

**Issue by matthew-brett** [travis-ci/travis-ci#4635]
See : https://travis-ci.org/MacPython/cython-wheels/jobs/74776231

Rackspace deploy  step fails with:

```
Installing deploy dependencies
Fetching: mini_portile-0.6.2.gem (100%)
Successfully installed mini_portile-0.6.2
Fetching: nokogiri-1.6.6.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.6.2
Fetching: net-ssh-2.10.1.rc1.gem (100%)
ERROR:  Error installing fog:
	net-ssh requires Ruby version >= 2.0.
/Users/travis/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fog (LoadError)
```

**Comment by matthew-brett** [comment]
Problem persists : https://travis-ci.org/MacPython/cython-wheels/jobs/74883689

**Comment by matthew-brett** [comment]
Same problem on another repo :  https://travis-ci.org/MacPython/scipy-wheels/jobs/75430030

**Comment by BanzaiMan** [comment]
Confirmed on the Mac, where somehow we end up installing `net-ssh` 2.10.1.rc1 somehow.

Adding

```yaml
before_deploy:
  - rvm 1.9.3 do gem install net-ssh -v 2.9.2
```

should get around this problem for the time being.

**Comment by matthew-brett** [comment]
Any plan for a definitive fix?

**Comment by BanzaiMan** [comment]
Superseded by #4853. net-ssh now requires Ruby 2.x, so we'll need to put a restriction on `net-ssh`.

**Comment by shiralwz** [comment]
change the version of net-ssh in Gemfile
`group :test, :development do
  gem "rspec-rails", ">= 2.5.0"
  gem 'factory_girl', '2.6.4'
  gem 'factory_girl_rails', '1.7.0'
  gem 'faker', '1.1.2'
  gem 'forgery', '0.5.0'
  gem 'magic_encoding', '0.0.2'
  gem 'email_spec', '1.4.0'

  gem 'net-ssh', '~> 2.0'
  gem 'capistrano', '~> 2.15.7'
  gem 'capistrano-rbenv', '1.0.5'
  gem 'rb-readline','0.4.2'
end`
