### ISSUE TITLE
Regression: after a job is clicked, the build is not added to the navigation bar

### ISSUE THREAD

**Issue by brauliobo** [travis-ci/travis-ci#4640]
So there is no way to go back :(

**Comment by jayvdb** [comment]
Yea. This is quite annoying.

**Comment by joshk** [comment]
Thanks for reporting this. Can you please record the issue as a small video so I can pass this onto the team?

Thanks a bundle

**Comment by jayvdb** [comment]
Steps to reproduce:
1. Go to https://travis-ci.org/wikimedia/pywikibot-core/jobs/58974238
2. Try to go to the build page listing all builds which occurred on that
commit
3. Fail.

On Tue, Aug 11, 2015 at 8:23 PM, Josh Kalderimis <notifications@github.com>
wrote:

> Thanks for reporting this. Can you please record the issue as a small
> video so I can pass this onto the team?
>
> Thanks a bundle
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/travis-ci/issues/4640#issuecomment-129818182>
> .
>



-- 
John Vandenberg

**Comment by brauliobo** [comment]
It was fixed.
