### ISSUE TITLE
openat functionality build failures

### ISSUE THREAD

**Issue by technorama** [travis-ci/travis-ci#4642]
Software using the openat() family of functions fails on macos. 

```
Undefined symbols for architecture x86_64:
  "_fdopendir", referenced from:
      _*Dir#initialize<Dir, Int32, String>:Nil in Dir.o
  "_openat", referenced from:
      _*File#do_open<File, Int32, String, String>:Int32 in File.o
      _*Dir#initialize<Dir, Int32, String>:Nil in Dir.o
  ```

I've tried osx_image: xcode63 & xcode64.  Neither works.  The openat() functions were added in yosemite.

Failure: https://travis-ci.org/manastech/crystal/builds/74837986

**Comment by BanzaiMan** [comment]
Is this a Crystal build? Could you try `language: crystal`? (http://docs.travis-ci.com/user/languages/crystal/)

cc @asterite @jhass @waj @will

**Comment by jhass** [comment]
This is nothing Crystal can do anything about, it's a syscall the OS X version running on Travis doesn't support.

**Comment by BanzaiMan** [comment]
Thanks for the info. I'm closing this.
