### ISSUE TITLE
Environment variable for branch from which PR originates

### ISSUE THREAD

**Issue by analyticalmonk** [travis-ci/travis-ci#4643]
Currently, for builds being triggered by PRs we can obtain the target branch of the pull request using the environment variable, TRAVIS_BRANCH.
Similarly, is there any way to obtain and use the branch from which the PR originates?

_Background_: I am running a script on travis (post a successful build) which will require cloning both the target branch and the branch requesting the merge on the travis machine itself in order to run some tests on them using the [Rperform](https://github.com/da-ta-vinci21/Rperform) package.

**Comment by BanzaiMan** [comment]
We are aware of this problem, and have an internal issue to track it. Thanks.

**Comment by analyticalmonk** [comment]
@BanzaiMan Has this issue been addressed by Travis yet? Also, the issue is PR related and doesn't have to do with tags.

**Comment by tdhock** [comment]
any updates on this issue? it will affect what parts of Rperform we will work on in Google Summer of Code 2016.

**Comment by BanzaiMan** [comment]
We now provide `$TRAVIS_PULL_REQUEST_BRANCH`.

**Comment by analyticalmonk** [comment]
@BanzaiMan thanks for the update!
@tdhock Yeah, it will. Will factor this in the code.
