### ISSUE TITLE
Support 'latest' for Firefox version in addon

### ISSUE THREAD

**Issue by davehunt** [travis-ci/travis-ci#4644]
The [Firefox addon](http://docs.travis-ci.com/user/firefox/) allows a specific version of Firefox to be installed. As far as I can tell, this is simply being translated to a download of http://releases.mozilla.org/pub/firefox/releases/[version]/linux-x86_64/en-US/firefox-[version].tar.bz2

In some cases it would be useful to not hardcode the version number, but to install the latest release, beta, or esr version of Firefox. These can be found in the following locations:

* Beta: http://releases.mozilla.org/pub/firefox/releases/latest-beta/linux-x86_64/en-US/
* Release: http://releases.mozilla.org/pub/firefox/releases/latest/linux-x86_64/en-US/
* ESR: http://releases.mozilla.org/pub/firefox/releases/latest-esr/linux-x86_64/en-US/

**Comment by BanzaiMan** [comment]
The above doesn't fix it, since the archives themselves don't have the predictable file name.

**Comment by edmorley** [comment]
Regarding:
> There *may* be an API endpoint to discover them without scraping HTML, but I have not found it

I've managed to find:
https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US
https://download.mozilla.org/?product=firefox-beta-latest&os=linux64&lang=en-US
(they weren't very discoverable unfortunately)

However there doesn't appear to be an equivalent for ESR. I've filed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1206069
