### ISSUE TITLE
When building a tagged commit TRAVIS_BRANCH and TRAVIS_TAG are set to the tag name

### ISSUE THREAD

**Issue by jeffpanici75** [travis-ci/travis-ci#4645]
I'm using travis-ci professional.

I have builds that rely on the branch name in TRAVIS_BRANCH to determine how to run various steps.  However, when a tagged commit is built, the TRAVIS_BRANCH environment variable is set to the same value as the TRAVIS_TAG, which is the tag name.

Ideally, TRAVIS_BRANCH would be the branch the build was triggered from and TRAVIS_TAG would be the tag name.

Is there a way to determine the actual branch name for tagged builds?

**Comment by liddellj** [comment]
I'm having the same issue - described in detail in #4745.

**Comment by BanzaiMan** [comment]
I believe this is a duplicate of #4643. Please provide additional details if you think otherwise. Thanks.

**Comment by sw-carlin** [comment]
@BanzaiMan Issue #4643 is unrelated. This is about a tag build, not a PR build.
