### ISSUE TITLE
./configure && make kicks off a ./configure && make && make test

### ISSUE THREAD

**Issue by cwarner-mdsol** [travis-ci/travis-ci#4647]
If you override the install for ./configure && make && make test with just ./configure && make. The build begins a subsequent kickoff with ./configure && make && make test which I guess makes sense because one should actually have test but if you're just testing the actual make process it probably shouldn't do that and stick to whatever the override is.

**Comment by roidrage** [comment]
I'm sorry, but I'm not sure I fully understand the problem.

Which steps have you overridden in your .travis.yml and in what way? Do you have a link to a build?

**Comment by cwarner-mdsol** [comment]
```
language: c
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libconfig++-dev
  - sudo apt-get install -y sqlite3
  - sudo apt-get install -y autoconf
  - sudo aclocal
  - sudo autoheader
  - sudo automake --force-missing --add-missing
  - sudo autoconf
install: ./configure && make
```

Here is a link to the specific build https://travis-ci.org/cwarner-mdsol/cvechecker/builds/75279543

**Comment by roidrage** [comment]
Ah, okay. You're overriding `install` but `script` is still using our default.

If the steps above are the only parts of your build, then I'd recommend restructuring as follows:

```
language: c
sudo: required
dist: trusty
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libconfig++-dev
  - sudo apt-get install -y sqlite3
  - sudo apt-get install -y autoconf
  - sudo aclocal
  - sudo autoheader
  - sudo automake --force-missing --add-missing
  - sudo autoconf
script: ./configure && make
```

**Comment by cwarner-mdsol** [comment]
Ok, worksforme.. I just made a test directory in the interim but i'll keep this in mind
