### ISSUE TITLE
Feature request: make the Docker images that Travis uses available to users

### ISSUE THREAD

**Issue by vr2262** [travis-ci/travis-ci#4648]
I have encountered many scenarios in which a test passes locally but fails on Travis. Usually it isn't too difficult to determine what the problem is, but it's a real nuisance for headless browser testing (http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-%28e.g.-a-Web-browser%29) when I have no way to see what the browser looks like.

Would it be possible to provide the images that Travis uses so that a user could examine the test environment without having to make a commit and waiting around?

**Comment by BanzaiMan** [comment]
Our images are available at https://quay.io/organization/travisci.

**Comment by vr2262** [comment]
Thanks! This is incredibly useful!
