### ISSUE TITLE
Specify an npm version

### ISSUE THREAD

**Issue by moretti** [travis-ci/travis-ci#4653]
It would be nice if we could specify the version of npm to use on Travis by editing the [`engines`](https://docs.npmjs.com/files/package.json#engines) section of `package.json`:
```json
{
  "engines": {
    "npm": ">=2.13.0"
  }
}
```

I've tried to add the following script to  `before_install`:
```yaml
   - npm install -g npm@'>=2.13.0'
```

But Travis keeps using the outdated version:

```
node" "/home/travis/.nvm/versions/node/v0.12.7/bin/npm" "install"
```

**Comment by joshk** [comment]
Can you please link to a project on Travis so we can investigate further?

**Comment by BanzaiMan** [comment]
I think this is a reasonable feature.

I am curious, though, how you determined that `npm install …` didn't work. I just tested this, and https://travis-ci.org/BanzaiMan/travis_production_test/builds/77092167#L93-L97 shows that `npm install -g npm@'>=2.13.0'` works as expected. (Keep in mind that `npm --version` is executed before any of your commands in `before_install` is executed.)

**Comment by BanzaiMan** [comment]
Hello. I merged the PR to implement this and deployed it, but upon further reflection, we decided to revert it. https://github.com/travis-ci/travis-build/pull/581#issue-124988166

According to https://docs.npmjs.com/files/package.json#engines
`package.json` is consulted for the version of `npm` that can
**install* the pacakge, not one that builds it.

The build process should not be concerned with the content of `package.json`.

This issue remains closed.

**Comment by ericf** [comment]
I handled this by adding a `before_install` script to my `.travis.yml`:

```yml
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
```

This makes sure npm 3 is used even when testing on older versions of Node.

**Comment by marcbachmann** [comment]
We're using that as install script. `jq` is already installed on travis.
```
nvm install "$(jq -r '.engines.node' package.json)"
```

**Comment by ORESoftware** [comment]
How can we prevent the usage of yarn on Travis and just use NPM for installs?

**Comment by nickmccurdy** [comment]
@ORESoftware I don't use Yarn for my Travis projects, as far as I'm aware Travis only defaults to Yarn is a `yarn.lock` file is present. If you want to use npm's lockfile, replace `yarn.lock` with `package-lock.json`and Travis should respect it (make sure it's running at least npm 5).

**Comment by ORESoftware** [comment]
ok I will try that thx

**Comment by raphinesse** [comment]
Here's the `before_install` I use, to make sure I can call `npm ci`:

```yaml
before_install: dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8
```
I check for v5.8 since it contains some bug fixes over the first version that introduced `npm ci`.

**Comment by MilesBHuff** [comment]
Just put the version you want into an `.nvmrc` file -- Travis and NVM will automatically use the version from this file if it is present.

https://github.com/nvm-sh/nvm#nvmrc
