### ISSUE TITLE
Errno::ENOENT: No such file or directory - can't find fixture

### ISSUE THREAD

**Issue by dugjason** [travis-ci/travis-ci#4656]
In build https://travis-ci.org/datasift/datasift-ruby/jobs/75629300 I'm receiving:

```
  1) Error:
DataSift::Odp::#ingest (failure)#test_0001_handles 404 when Managed Source can not be found:
Errno::ENOENT: No such file or directory @ rb_sysopen - ./../../fixtures/data/fake_gnip_tweets.json
    /home/travis/build/datasift/datasift-ruby/test/datasift/odp/batch_upload_test.rb:39:in `initialize'
    /home/travis/build/datasift/datasift-ruby/test/datasift/odp/batch_upload_test.rb:39:in `open'
    /home/travis/build/datasift/datasift-ruby/test/datasift/odp/batch_upload_test.rb:39:in `block (4 levels) in <top (required)>'
    /home/travis/.rvm/gems/ruby-2.2.0/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call'
    /home/travis/.rvm/gems/ruby-2.2.0/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
    /home/travis/.rvm/gems/ruby-2.2.0/gems/vcr-2.9.3/lib/vcr.rb:182:in `use_cassette'
    /home/travis/build/datasift/datasift-ruby/test/datasift/odp/batch_upload_test.rb:38:in `block (3 levels) in <top (required)>'
```

It seems Travis is failing to find my fixture (it's definitely there!). I've checked issues like #1685 which were caused by file names being in the incorrect case (OK vs Ok), but I don't have the same issue.
Any suggestions?

**Comment by roidrage** [comment]
Thanks for reporting this issue.

Is it possible that this is a problem with the relative path? 

Could you try loading it with something like this:

```ruby
payload = File.open(File.expand_path(__FILE__, "./../../fixtures/data/fake_gnip_tweets.json", "rb").read
```

This should make it work no matter where the test file is run from (which can affect what the current working directory is).

**Comment by dugjason** [comment]
Yes!

I had to change the code slightly from what you recommended:

```
payload = File.open(File.expand_path('../../fixtures/data/fake_gnip_tweets.json', File.dirname(__FILE__))).read
```

But it works. I'll have to remember to run the test locally in a load of different ways next time. Thanks for the help!
BTW; I love how fast the new container infrastructure runs my tests. Huge improvement!
