### ISSUE TITLE
Travis builds commits, but logs can't be viewed

### ISSUE THREAD

**Issue by startaq** [travis-ci/travis-ci#4658]
Travis builds our commits and mails on failures, but we can't view the build logs. The page displays "This is not an active repository".

Project page is here: https://travis-ci.org/mamedev/mame/builds/

**Comment by MariadeAnton** [comment]
Was this repo activated manually on GitHub?  We deployed a recent change to show this notice when the repositories haven't been enabled on Travis CI.

Activating the repo over at https://travis-ci.org/profile/mmicko - should fix the issue.  Can you confirm?

**Comment by startaq** [comment]
Activated the repo on my profile and now it appears to work. There were some issues previously that required manual intervention, maybe that was the connection. Thanks!
