### ISSUE TITLE
False positive test run - no space left on device

### ISSUE THREAD

**Issue by filemon** [travis-ci/travis-ci#4659]
Hi,

I need to use a docker on my box, that's why I'm still with the legacy infrastructure. My build seems to be positive, however it failed in the middle during the docker build. 

TRAVIS_REPO_SLUG=topmonks/ftb-web

Thanks in advance, 

The error message:

ERRO[0103] Error from V2 registry: Untar re-exec error: exit status 1: output: write /usr/share/doc/liblcms2-dev/LittleCMS2.6 Plugin API.pdf.gz: no space left on device 
Pulling repository rails
Error pulling image (4.2) from rails, Untar re-exec error: exit status 1: output: write /usr/local/bundle/cache/rails-4.2.3.gem: no space left on device

**Comment by andreif** [comment]
I got `no space left on device` but the build marked as errored, so I guess we can close it.
