### ISSUE TITLE
Unable to stop Docker containers

### ISSUE THREAD

**Issue by mauricioklein** [travis-ci/travis-ci#4661]
Travis.org avoid to stop Docker container.

Images can be pulled and containers can be started without problem, but when trying to stop/kill a running container, a permission denied error is raised.

Example gist showing this behavior can be found [here](https://gist.github.com/mauricioklein/ba69df8eb84561774b69) (please ignore Ruby related instructions, since they're used in my project only).

The Travis build presenting this erros can be viewed [here](https://travis-ci.org/mauricioklein/docker-compose-api/builds/75975639).

**Comment by arkadius** [comment]
I have the same issue with [my build](https://travis-ci.org/arkadius/reliable-http-client) using docker api. Any idea how to fix it?

**Comment by mauricioklein** [comment]
Hello!

I found [this open issue](https://github.com/docker/docker/issues/15101) on Docker project.

It seems to be a know issue, so there isn't much to do until it gets fixed (maybe trying to restart Travis worker can fix the problem, but it's just a shot in the dark).

One of the possible workarounds described there was to kill container by its pid, using _kill_.

That worked for me locally, but failed on Travis, as you can see [here](https://travis-ci.org/mauricioklein/docker-compose-api/builds/76730532).

Hope this get fixed soon o/

**Comment by electricmonk** [comment]
Same thing [here](https://travis-ci.org/wix/sokoban/jobs/77358024). Did anyone find a solution? locally everything works for me but on Travis my build fails...

**Comment by mauricioklein** [comment]
I've read somewhere that, to overcome this problem, some guys are starting a Docker container that provides a Docker container. So, inside the container started by Travis, we theoretically have all the necessary rights and, so, can start/stop containers without problem.

I haven't tried this yet.

As soon I do so, I'll share my thoughts here.

Cheers o/

**Comment by moylop260** [comment]
I have the same issue in my travis build.
FYI I executed same `.travis.yml` script with a little script called [travis2docker](https://pypi.python.org/pypi/travis2docker) in a container --privileged with same version of docker (1.7.0) and we don't have this issue.

**Comment by chrismeyersfsu** [comment]
I have what might be a related issue.

Within a docker container, I get permission denied when trying to kill a child.

Minimal example:
https://travis-ci.org/chrismeyersfsu/test_travisci_docker/builds/81100499

To fix this I added `--privileged=true` to `docker run`

**Comment by benjixx** [comment]
I just stumbled into the same issue. Fortunately, it looks like this can be fixed by doing setting apparmor into complain mode for docker profile:

```yaml
install:
  # place apparmor docker profile in complain mode
  # to workaround https://github.com/travis-ci/travis-ci/issues/4661
  - sudo apt-get -y update
  - sudo apt-get -y install apparmor-utils
  - sudo aa-complain /etc/apparmor.d/docker
```

**Comment by benjixx** [comment]
Hmm, looks like the workaround I proposed is not necessary anymore. It seems to work now OOTB. I haven't found any reference yet why this is the case. Probably ```apparmor``` has been removed as directory ```/etc/apparmor.d``` does not exist anymore.

**Comment by mauricioklein** [comment]
Hello!

Sorry for the long delay in replying...

@benjixx, I've tried your solution with apparmor but I'm facing an error when running aa-complain.

You can see the error [here](https://travis-ci.org/mauricioklein/docker-compose-api/builds/86109030).

Also, I've tried without apparmor, since you pointed that this's not necessary anymore, but the problem persists, as you can see [here](https://travis-ci.org/mauricioklein/docker-compose-api/builds/86109301).

Am I missing something?

Best regards!

**Comment by mauricioklein** [comment]
@moylop260 and @chrismeyersfsu :

I haven't tried your solutions yet, but anyway, running in privileged mode is just a workaround, not a definitive fix. Also, since my project relies strongly on Docker to work, this approach isn't suitable to my needs.

I'll keep investigating for a better approach.

Thanks!

**Comment by benjixx** [comment]
@mauricioklein, I just ran my sandbox project (which I've used to verify correct behavior) again (see [here](https://travis-ci.org/benjixx/sandbox/builds/85583662)), and doing ```docker rm -f CONTAINERID``` there works as expected. I should mention that this does not call ```kill``` command directly.

**Comment by mauricioklein** [comment]
@benjixx you're right, my bad.

I'll give a try calling docker stop/kill instead OS command and see if it works.

Thanks!

**Comment by benjixx** [comment]
@mauricioklein Let me know how things go.

**Comment by mauricioklein** [comment]
@benjixx now docker stop is working (link to Travis build [here](https://travis-ci.org/mauricioklein/docker-compose-api/builds/86167169)).

Thanks a lot for the support of everybody so far!

If no one oppose, I'll close this issue.

Cheers o/
