### ISSUE TITLE
Quotations on Node.JS version in .travis.yml (as shown in travis node docs) file cause Travis to try to build default Ruby build

### ISSUE THREAD

**Issue by kinetics** [travis-ci/travis-ci#4662]
http://stackoverflow.com/questions/32064862/travis-ci-node-js-defaulting-to-ruby-build-no-rakefile-found/32064879#32064879

**Comment by kinetics** [comment]
Docs link with all examples using quotes: 

http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by BanzaiMan** [comment]
This is not a problem with the quote/unquote of the version number.

Under certain circumstances we fail to find the available build images (when our providers' API returns error for various reasons). When this happens, the build will be run on the default image (currently Ruby), and you see the unfortunate error.

For YAML, the presence of quotes is important to distinguish strings and floats. `0.12` (a float) is indistinguishable from `"0.12"` (string) when converted, so this is not an issue. (`0.10` vs `"0.10"` is, but we bend over backwards to deal with this common mistake.)

**Comment by kinetics** [comment]
Thanks for the clarification Banzai! I think it would help people new to Yaml and/or Travis if you added a note of this to the Node-Travis Docs.
