### ISSUE TITLE
Support for New DotNet DNX Projects

### ISSUE THREAD

**Issue by benmmurphy** [travis-ci/travis-ci#4663]
Newer versions of DotNet use project.json and global.json instead of .csproj and .sln files. It would be nice if travis supported this.

https://github.com/aspnet/Home/wiki
https://github.com/aspnet/Home/wiki/Project.json-file

**Comment by BanzaiMan** [comment]
cc @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
@benmmurphy There are already quite a few DNX based projects using Travis right now, e.g. the [Omnisharp-Roslyn](https://github.com/OmniSharp/omnisharp-roslyn/blob/f101d0d96644d57b64bcca1f6f4d26f16e65977b/.travis.yml) project, by just installing DNX as you normally would on Linux during the build.

Given that DNX is still in flux and changes very rapidly, I don't think it makes sense to explicitly add support right now.

I'm definitely in favor of adding some helpers once DNX is more stable (e.g. with the release candidate scheduled for November). Can you list some of the features you'd like to see then? I can imagine things like specifying a DNX version (which would then be installed automatically), running dnu build/publish on a specified path, etc.

**Comment by benmmurphy** [comment]
thanks for the link @akoeplinger that is perfect for me. dnx versions sounds good. i run dnu restore and dnx . test in my project (https://github.com/zensend/zensend_csharp_api/blob/master/.travis.yml)

**Comment by akoeplinger** [comment]
Cool, glad you got it working and thanks for the input :)

**Comment by BanzaiMan** [comment]
Can this be closed?

**Comment by akoeplinger** [comment]
@BanzaiMan I think we should keep this open to track adding helpers for DNX projects, so if you could add some feature/suggestion label that'd be great.

**Comment by oshalygin** [comment]
Just curious @akoeplinger , I did something similar to you, except my TravisCI build just hangs at the end of the successful/failed tests.  

I understand that we're still in beta for vNext, but I was hoping for something to use in the "meantime".  Here is a version of my travis.yml file (https://github.com/oshalygin/SolutionPub/blob/master/.travis.yml)

**Comment by akoeplinger** [comment]
@oshalygin fyi, this is also fixed in Mono 4.2 that'll be released soon.

**Comment by oshalygin** [comment]
@akoeplinger , awesome thanks!

**Comment by Phrohdoh** [comment]
FYI: dnx has been deprecated in favor of [dotnet-cli](https://github.com/dotnet/cli), perhaps the new toolchain will make it easier to create Roslyn-based build environments.

**Comment by nicolasmccurdy** [comment]
Has anyone figured out the optimal caching configuration for DNX projects on Travis? I'm assuming you would want to cache wherever `dnu restore` installs dependencies to, but I'm not sure if caching things installed with `dnvm use` is appropriate.
