### ISSUE TITLE
Problems rendering ANSII output

### ISSUE THREAD

**Issue by jroper** [travis-ci/travis-ci#4666]
We've seen some weird problems when travis attempts to render ANSII output.  An example is the following build:

https://travis-ci.org/playframework/playframework/jobs/76209132

Everything's rendered fine, but then after the last line (line 505), it appears like most of the output is then rendered again, this time in reverse, and with no newlines between it.  In other builds (with a lot more output), it gets even stranger.

**Comment by BanzaiMan** [comment]
We had a few log rendering issues which caused this problem. They should be fixed now, so I'm closing this. If the problem persists, do let us know.

Thanks!

**Comment by jroper** [comment]
The linked job now renders fine, so it looks like it's fixed to me, thanks!
