### ISSUE TITLE
Increased concurrency for open source projects

### ISSUE THREAD

**Issue by jroper** [travis-ci/travis-ci#4668]
Is there any way open source projects can get increased concurrency (and/or a large ec2 instance)?  We'd be happy to pay a premium if necessary.  We've just moved from cloudbees, where a single build took 25 minutes using an EC2 high speed instance, now a single build on travis takes one and a half hours, we've split that into several smaller builds, but it's still slow, and when there's multiple jobs to get done, it can still take hours for the most recent job to reach the front of the queue.

**Comment by BanzaiMan** [comment]
@jroper Could you email support@travis-ci.com to discuss this further? Thank you!

**Comment by thedrow** [comment]
@BanzaiMan We also need larger machines with more RAM and CPUs.
We're paying customers.

**Comment by joshk** [comment]
We do have options for a larger number of concurrent running jobs on .org, but we don't have larger VMs at the moment sorry.

I'm closing this issue for now.
