### ISSUE TITLE
Wrong environment variables for Coverity

### ISSUE THREAD

**Issue by Shamar** [travis-ci/travis-ci#4674]
[This build](https://travis-ci.org/Harvey-OS/harvey/jobs/76350367#L212) show that Travis invokes Coverity Scan using `$TRAVIS_REPO_SLUG` instead of the [variable previously exported by the addon, `$PROJECT_NAME`](https://travis-ci.org/Harvey-OS/harvey/jobs/76350367#L209):

```
$ curl -s https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh | \
  COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG" \
  COVERITY_SCAN_NOTIFICATION_EMAIL="harvey@googlegroups.com" \ 
  COVERITY_SCAN_BUILD_COMMAND="./BUILD all" \
  COVERITY_SCAN_BUILD_COMMAND_PREPEND="./BUILD utils" \
  COVERITY_SCAN_BRANCH_PATTERN=coverity_scan bash
```

Since in our case the project name on coverity and the slug do not match we get an API access error from coverity. To workaround this I [exported `$TRAVIS_REPO_SLUG` in the repository settings](https://travis-ci.org/Harvey-OS/harvey/jobs/76350367#L194) with the value that coverity expects, but this is just an hack that we should avoid.

The correct solution is to set  `COVERITY_SCAN_PROJECT_NAME="$PROJECT_NAME"` before invoking the coverity scan tool.

**Comment by BanzaiMan** [comment]
I take it that `COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"` should be changed to `COVERITY_SCAN_PROJECT_NAME="$PROJECT_NAME"`.

**Comment by Shamar** [comment]
Still not working. See https://api.travis-ci.org/jobs/77740957/log.txt?deansi=true 

It is still setting  `COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"`.

**Comment by BanzaiMan** [comment]
Sorry, but this has not been deployed yet. Probably Monday.
