### ISSUE TITLE
Wrong (missing?) artifacts on OS X workers for deployment

### ISSUE THREAD

**Issue by Snaipe** [travis-ci/travis-ci#4675]
It seems that the deployment script for GitHub releases on OS X workers crashes for my setup, complaining that it cannot find the files I want to deploy -- however, the deployment works correctly on linux boxes:

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
fatal: Unable to read current working directory: No such file or directory
/Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-4.0.1/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory - criterion-test-osx-x86_64.tar.bz2 (Errno::ENOENT)
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-4.0.1/lib/octokit/client/releases.rb:86:in `new'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-4.0.1/lib/octokit/client/releases.rb:86:in `upload_asset'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.7.20/lib/dpl/provider/releases.rb:118:in `block in push_app'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.7.20/lib/dpl/provider/releases.rb:102:in `each'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.7.20/lib/dpl/provider/releases.rb:102:in `push_app'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.7.20/lib/dpl/provider.rb:141:in `block in deploy'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.7.20/lib/dpl/cli.rb:41:in `fold'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.7.20/lib/dpl/provider.rb:141:in `deploy'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.7.20/lib/dpl/cli.rb:32:in `run'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.7.20/lib/dpl/cli.rb:7:in `run'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.7.20/bin/dpl:5:in `<top (required)>'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/bin/dpl:23:in `load'
        from /Users/travis/.rvm/gems/ruby-1.9.3-p547/bin/dpl:23:in `<main>'
failed to deploy
```
(Full log can be found [here](https://travis-ci.org/Snaipe/Criterion/jobs/76377074).)

I made of course sure that the file was, in fact, there in `before_deploy`:

```
$ pwd && ls
/Users/travis/build/Snaipe/Criterion/build
[snip]
criterion-test-osx-x86_64.tar.bz2
[snip]
```

I first thought that it was failing because I was doing an out-of-source build, and that somehow the deploy script changed the work directory back to the source root, so I changed the build script to create the archive in the source root and cd'd back to it before the deploy rule, [but to no avail](https://travis-ci.org/Snaipe/Criterion/jobs/76379277).

I'm going to try another variation of the build script to create the archive out of the source directory and see how it goes since it seems that you are manipulating the git stash before deploying, and report back with the results.

**Comment by Snaipe** [comment]
Good news, the latest test [worked](https://travis-ci.org/Snaipe/Criterion/jobs/76381506)!

Somehow, if I create the archive inside the source folder, it gets deleted somewhere between `before_deploy` and `deploy`.

**Comment by BanzaiMan** [comment]
We run `git stash --all` unless `skip_cleanup: true` is set. This is documented in http://docs.travis-ci.com/user/deployment/#Uploading-Files.

**Comment by Snaipe** [comment]
@BanzaiMan I somehow missed that, sorry.

However, what I find confusing is that `git stash --all` seems to fail on linux workers then, which made me think it was an issue with the OS X worker.
