### ISSUE TITLE
Possible to build an R package on Travis with JAGS?

### ISSUE THREAD

**Issue by nutterb** [travis-ci/travis-ci#4680]
I'm maintaining an R package that has JAGS as a system requirement.  I can't find any resources indicating how to build with Travis with such a system requirement.  Perhaps it isn't possible? Or is there a way to include this system requirement in the build?

@craigcitro @hadley

https://github.com/nutterb/HydeNet

**Comment by craigcitro** [comment]
how does one normally install jags on an Ubuntu system?

**Comment by nutterb** [comment]
Great question!  I hadn't thought to frame the question like that.  After some reading I found that adding the following takes care of it

```
before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get install r-cran-rjags
```

Thanks for the prompt.

**Comment by craigcitro** [comment]
no sweat -- in fact, you could probably just add `rjags` to the list of `r_binary_packages` and it'd just work for you.
