### ISSUE TITLE
Issue with the default exporting of env vars CXX and CC by Travis CI script builder.

### ISSUE THREAD

**Issue by lekshmideepu** [travis-ci/travis-ci#4682]
Travis CI script builder  export the env vars CXX and CC  by default which causes  problems to our project which uses MPI flags like MPI_CXXFLAGS, MPI_CLAGS and MPI_LDLAGS.

For the moment we are using a workaround by resetting the value of the above mentioned env vars as follows:

```yaml
  - if [ "$CXX" == "g++" ]; then export CXX=""; fi
  - if [ "$CC" == "gcc" ];  then export CC=""; fi
```

Another possible workaround is to remove the language setting section.

**Comment by BanzaiMan** [comment]
Could you elaborate on the problem? These values have been exported since our early days, and changing this behavior is likely to break many builds than it helps.

It seems to me that our best option is to document this behavior and advise MPI users of this issue.

**Comment by lekshmideepu** [comment]
Our project is configured in such a way that it should automatically detects the compilers and the other  flags. Hence, we don't prefer to use the default compiler settings. 
Please refer to our Travis build: https://travis-ci.org/INCF/MUSIC/jobs/74627737 (it's failing due to the problem with one of the testsuites which is not relevant here)  and Git repo:  https://github.com/INCF/MUSIC

I also had an email conversation with Mr.Piotr Sarnacki  and he asked me to open up an issue here.

*"CXX and CC env vars are exported by default by Travis CI script builder (if you want to take a look at the code, it's here: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/cpp.rb#L11-L12). Unfortunately it seems that the export section from travis-build is done after exporting any variables set in .travis.yml.
........
That said, I view it as a bug, so could you open an issue here: https://github.com/travis-ci/travis-ci/issues, so we can track it?"*

**Comment by guludo** [comment]
Any update on this? :-)

**Comment by BanzaiMan** [comment]
Hello. This has been documented. https://github.com/travis-ci/docs-travis-ci-com/pull/473
