### ISSUE TITLE
Docker python location

### ISSUE THREAD

**Issue by 2ndalpha** [travis-ci/travis-ci#4683]
Python does not find modules installed via pip.

"docker" service has to be enabled:
```yaml
services:
  - docker
```

Code: https://github.com/2ndalpha/travis-test
Build: https://travis-ci.org/2ndalpha/travis-test/builds/76436307
ImportError: No module named boto.s3.connection

When I remove "docker" service, it does work: https://travis-ci.org/2ndalpha/travis-test/builds/76436527

Figured out that when docker is enabled, location for python & pip are following:
/opt/python/2.7.10/bin/python
/opt/python/2.7.10/bin/pip

Without docker they are:
/usr/bin/python
/usr/local/bin/pip

So to get it working with docker I have to use full path of python & pip from /usr/.

**Comment by BanzaiMan** [comment]
Closing this as it's become stale. If the problem persists on the new Docker setup, please open a new issue.
