### ISSUE TITLE
Problem to perform build

### ISSUE THREAD

**Issue by guiseek** [travis-ci/travis-ci#4684]
Problem to perform build, the tests are working locally, but when I pull request to merge, and travis runs the tests, I'm having problems only in travis logs.

Local:
![screen shot 2015-08-20 at 9 40 18 am](https://cloud.githubusercontent.com/assets/5638096/9383459/94c4e046-471f-11e5-9931-2fe41f6af542.png)

Travis:
https://travis-ci.org/GUMGA/components

Any idea?

**Comment by BanzaiMan** [comment]
Recent builds succeeded. Is there anything to investigate?
