### ISSUE TITLE
travis builds erratically failing

### ISSUE THREAD

**Issue by olaurino** [travis-ci/travis-ci#4686]
Hi,

I recently added a complex optional dependency in the build matrix of our project:
https://github.com/sherpa/sherpa

The new builds that include this dependency appear to erratically fail and in different ways. In some cases, In the past weeks, I have witnessed the build fail, the worker reset and a new build start: the second time around, the build was fine, but this does not seem to happen anymore.

This build failed graciously in this instance, but the build process was killed in the middle of the tests:
https://travis-ci.org/sherpa/sherpa/jobs/76525856

This one failed in a similar fashion, but the error was not properly handled, the build hung, and the 10 minutes timeout went off:
https://travis-ci.org/sherpa/sherpa/jobs/76525687

Here is an example of a green build:
https://travis-ci.org/sherpa/sherpa/jobs/76525259

Ironically, the one that passes is the one that introduces the new build in the master branch, while the two failing ones were triggered by commits that have nothing to do with that code.

The external dependency, which is included as a conda package, makes some new tests run in our code. These may me resource-intensive, but on our local systems they never result in this kind of issues.

Is there any way I can access the logs of the workers to understand why the builds are (sometimes) failing? It is possible that the process is saturating the memory or the storage of the virtual workers, or something more exotic, but it is hard to track the issue down with the sole build logs.

Thanks!

**Comment by BanzaiMan** [comment]
Hello. Sorry for the oversight here. Is it still relevant? I see recent builds passing https://travis-ci.org/sherpa/sherpa/builds.

**Comment by olaurino** [comment]
If I remember correctly the only way to work around it was to use the trusty image. It's been a while so I am not sure what would happen now if I reverted back to the default image.

In any case, given we can't pick our own images or run our own runners we are looking into migrating to GitLab CI.

Thanks for replying.

**Comment by BanzaiMan** [comment]
Great. Do note that Trusty is now the default.

I'm closing this now.
