### ISSUE TITLE
Travis randomly hangs on vmprof tests

### ISSUE THREAD

**Issue by fijal** [travis-ci/travis-ci#4688]
Hi

The test load in question is a bit unusual, but at the end it does that:

```
t0 = time.time()
while time.time() - t0 < 0.5:
   pass
```

which is a busy loop for half a second. This runs with extra signal handler that does things, but it should not really be an issue. Now this timeouts 10min, how is it possible?

PS. Locally I was never able to reproduce this sort of stuff

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows this problem? Are you certain that this is the place it is hanging?

**Comment by fijal** [comment]
Seems to be related with time.time(). This is a run of a loop that just prints time.time() until it exceeds 0.5s https://travis-ci.org/vmprof/vmprof-python/jobs/76967531#L3805 note the massive jump in measured time.

**Comment by BanzaiMan** [comment]
Is it hanging somewhere inside `vmprof.disable()`? Since this is happening on a legacy infrastructure, we can spin up a debug VM for you. Please email support@travis-ci.com.

**Comment by fijal** [comment]
I'm trying to migrate to containers, still missing libdwarf-dev

**Comment by BanzaiMan** [comment]
Sorry, but I do not follow. What does the move to containers influence this issue? I've added `libdwarf-dev`, so you can use the APT addon now, but if the hang randomly happens, that could very well happen on the containers as well.

**Comment by fijal** [comment]
we fixed it by not using time.time(). We'll live with that, feel free to
clsoe
