### ISSUE TITLE
Branch and its builds page

### ISSUE THREAD

**Issue by brauliobo** [travis-ci/travis-ci#4689]
It would nice to have a page so that in the branches tab we can have a link that shows all the builds for a given branch, so that I can give this link and show the latest build and other builds on that branch.

**Comment by bishop335** [comment]
add:Bishop-web

**Comment by kenorb** [comment]
Related: #1996

**Comment by aconz2** [comment]
Related: #2454

**Comment by brauliobo** [comment]
this was done

**Comment by kenorb** [comment]
@brauliobo Can you point where it was done and how to use it?
