### ISSUE TITLE
Cache blacklisting

### ISSUE THREAD

**Issue by kag0** [travis-ci/travis-ci#4693]
While trying to speed up builds, I've been working on caching. One thing I noticed is that I miss the ability to exclude certain files or folders within cached directories. For example the ~/.sbt/boot folder contains a lock file which should not be cached, but also contains sub folders with variable names which should be cached. Also, the ~/.sbt folder contains a couple folders which are desirable for caching, but also can contain a credential file, which should not be cached.

Ignored files could be added as sub-items of a given cached directory, rather than global like a .gitignore. 

Thoughts?

**Comment by BanzaiMan** [comment]
You can use [`before_cache` phase](http://docs.travis-ci.com/user/caching/#before_cache-phase) to delete files you don't want.

**Comment by kag0** [comment]
That's effective, thanks

**Comment by BanzaiMan** [comment]
Great to hear. I'm going to close this.
