### ISSUE TITLE
env not working in GitHub Releases Uploading's file name

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis-ci#4695]
In .travis.yml
```
env:
  - GOOS=linux GOARCH=amd64
  - GOOS=darwin GOARCH=amd64
  - GOOS=windows GOARCH=amd64 EXT=.exe
```
doesn't applies to `file: "$HOME/gopath/bin/deblocus_${TRAVIS_TAG}_${GOOS}-${GOARCH}.tar.xz"` in `deploy:`
Here is part of the log:
```
Deploying application
deblocus_v0.9.3-beta_-.tar.xz already exists, skipping.
```

**Comment by tvvocold** [comment]
@spance

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows this issue?

**Comment by l2d4y3** [comment]
https://travis-ci.org/l2d4y3/deblocus/jobs/76877162

**Comment by BanzaiMan** [comment]
I tried reproducing this with [this `.travis.yml`](https://github.com/BanzaiMan/travis_production_test/blob/aa45f869b02f00c23fd38c229bbafc1cad9374b3/.travis.yml). This resulted in [this build](https://travis-ci.org/BanzaiMan/travis_production_test/builds/101510973), which uploaded the files as expected https://github.com/BanzaiMan/travis_production_test/releases/tag/v0.0.3.

I'm closing this optimistically; if anyone has a reproducible test case, I'm happy to look into it further.

**Comment by spance** [comment]
Maybe the issue has been fixed at some point after reporting this issue.
So far, the env problem has never appeared.
