### ISSUE TITLE
Path is not exported for ccache when it is enabled

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#4698]
Ccahce requires that the path of the ccache enabled compilers will come before the compiler so when ccache is enabled the path should be ```"/usr/lib/ccache/:$PATH"```
The ccache cache option and the directory caching does not enable it.

**Comment by BanzaiMan** [comment]
As described in https://wiki.archlinux.org/index.php/Ccache#Enable_for_command_line, the correct path is `/usr/lib/ccache/bin`.

**Comment by BanzaiMan** [comment]
Note that `$PATH` is modified only for `cache: ccache`.

**Comment by thedrow** [comment]
@BanzaiMan That's for ArchLinux, not Ubuntu. I just checked and it's /usr/lib/ccache/ at least in Ubuntu 15.04. Please verify.

**Comment by BanzaiMan** [comment]
Apologies. `/usr/lib/ccache` is indeed correct. I've fixed and deployed this.

**Comment by thedrow** [comment]
Wonderful. Thanks!
Is there a chance to fix the ccache/pip cache sections to work also when the install step is overridden? Is there an issue about it?

**Comment by BanzaiMan** [comment]
@thedrow There is: https://github.com/travis-ci/travis-ci/issues/3239.

**Comment by thedrow** [comment]
Thanks for the remainder.
