### ISSUE TITLE
travis and long running unit tests

### ISSUE THREAD

**Issue by jangorecki** [travis-ci/travis-ci#4700]
I have a use case when the time required to populate data for unit testing is quite time consuming. The data are being populated in iterations and at the same time the iterations of unit tests goes, results are stored in local db - which at the end is reported in my own way.
I'm interested to run travis build locally (or online if possible) the way I could unit test scalable long process. All the iterations etc. are not exposed to travis and are handled in R.

**Comment by BanzaiMan** [comment]
If you are running on legacy infrastructure, we can spin up a debug VM for you. Please email support@travis-ci.com.

If you are using the containers, then you can find our Docker images at https://quay.io/organization/travisci; find the language image you need. Community-supported languages use the Ruby image.
