### ISSUE TITLE
DNS Weirdness on OSX

### ISSUE THREAD

**Issue by ariscop** [travis-ci/travis-ci#4702]
>$ host 127.0.0.1
>;; reply from unexpected source: 10.182.0.20#53, expected 10.182.0.19#53
>;; reply from unexpected source: 10.182.0.20#53, expected 10.182.0.19#53
>;; connection timed out; no servers could be reached

From: https://travis-ci.org/Elemental-IRCd/elemental-ircd/jobs/76948590

Tests on that project rely on a timely response from the dns server, they currently fail on osx.

**Comment by henrikhodne** [comment]
Thank you for reporting this. We changed the DNS settings for the VMs, and it seems like `host 127.0.0.1` now returns NXDOMAINs instead. Could you try re-running your tests?

**Comment by ariscop** [comment]
Looks fixed, tests are passing
