### ISSUE TITLE
Error installing Bioconductor

### ISSUE THREAD

**Issue by thomasp85** [travis-ci/travis-ci#4703]
Hi @craigcitro, @eddelbuettel, and @hadley
I've began getting the following errors when building with `bioc_required: true`:

```
$ Rscript -e 'source("http://bioconductor.org/biocLite.R"); tryCatch(  useDevel(FALSE),  error=function(e) {if (!grepl("already in use", e$message)) {e}} );'
The command "eval Rscript -e 'source("http://bioconductor.org/biocLite.R"); tryCatch(  useDevel(FALSE),  error=function(e) {if (!grepl("already in use", e$message)) {e}} );'" failed. Retrying, 2 of 3.
The command "eval Rscript -e 'source("http://bioconductor.org/biocLite.R"); tryCatch(  useDevel(FALSE),  error=function(e) {if (!grepl("already in use", e$message)) {e}} );'" failed. Retrying, 3 of 3.
The command "eval Rscript -e 'source("http://bioconductor.org/biocLite.R"); tryCatch(  useDevel(FALSE),  error=function(e) {if (!grepl("already in use", e$message)) {e}} );'" failed 3 times.
The command "Rscript -e 'source("http://bioconductor.org/biocLite.R"); tryCatch(  useDevel(FALSE),  error=function(e) {if (!grepl("already in use", e$message)) {e}} );'" failed and exited with 1 during .
```

Bioconductor recently began moving to https, so it might be related to that, though the http://bioconductor.org/biocLite.R URL is still live.

**Comment by eddelbuettel** [comment]
Can you alter your reference to `https`, maybe set `options("download.file.method"="libcurl)` or rely on R 3.2.2 which makes that a default?

**Comment by thomasp85** [comment]
I'm not fluent in travis - how should my .travis.yml file look to emulate `bioc_required: true`but let me specify the changes you described? (current travis configuration at https://github.com/thomasp85/FindMyFriends/blob/master/.travis.yml)

**Comment by craigcitro** [comment]
that's odd -- is it transient, or does it fail every time? (you can hit the button that looks like "refresh" in the upper right in the travis UI to retry a build without a new push to github.)

**Comment by thomasp85** [comment]
It's persistent. Both with retries and new commits...

**Comment by eddelbuettel** [comment]
Do you know the R version?   The way I run r-travis I get R 3.2.2 from the Ubuntu backports -- built with curl and doing https quite happily.

**Comment by thomasp85** [comment]
While it never gets around to printing the R version it fetches it with:

```
Installing R
$ sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -cs)/"
```

Also, the last build that successfully installed Bioconductor used R 3.2.2 and nothing has changed in my travis config since, so I would assume that the latest version is used...

**Comment by thomasp85** [comment]
The package now builds fine? It has probably been a error on the Bioconductor servers that has been fixed overnight
