### ISSUE TITLE
Large writes to stdout sometimes fail with "Resource temporarily unavailable".

### ISSUE THREAD

**Issue by mvollmer** [travis-ci/travis-ci#4704]
We are happily using Travis but now we seem to be crossing some limit somwhere that causes make to fail with a mysterious "write error".

This is an example: https://travis-ci.org/cockpit-project/cockpit/jobs/76976494

The write error seems to happen when make writes a long command to stdout in large pieces, and the write syscall fails with EAGAIN.  In one case, it made two syscalls with about 6000 bytes followed by about 500 bytes.  I am not super sure about the details as debugging this from my end is a bit hard.

I think stdout/stderr is connected to a pty, so maybe that has something to do with it.

I don't have a simple reproducer yet but I can try to make one if that helps.

As a workaround, we are piping the build output through this program: https://github.com/mvollmer/cockpit/blob/69ae5e0c6ae82b0c5824aa088edd608ba9633fe2/tools/careful-cat.c

**Comment by mvollmer** [comment]
As an attempt at making this more easily reproducible, I made this pull request:

https://github.com/cockpit-project/cockpit/pull/2616

It rapidly writes large buffers to stdout. Sometimes this succeeds

https://travis-ci.org/cockpit-project/cockpit/jobs/77134346

and sometimes the output is truncated:

https://travis-ci.org/cockpit-project/cockpit/jobs/77134347

However, the build is counted as successful, so I guess the write syscall did not actually fail.

**Comment by whitequark** [comment]
This bug makes the OS X worker unusable for solvespace/solvespace, without a hacky workaround that restarts the build a few times.

**Comment by MariadeAnton** [comment]
Possibly related fix: https://github.com/travis-pro/team-blue/issues/225#issuecomment-253178336

**Comment by MariadeAnton** [comment]
Can you try routing your builds to the `xcode8.2` image using:

`osx_image: xcode8.2`

and let us know how it goes?

**Comment by mvollmer** [comment]
I am sorry to report that we are not using Travis anymore, so it is quite difficult for me to verify this fix.

Thanks a lot in any case, I really appreciate it that you didn't lose track of this, as I would have.

**Comment by whitequark** [comment]
I had the same issue, which broke builds about 60% of time even with automatic restart, and I've just had over five successful builds in a row. I am quite certain this is fixed.

**Comment by MariadeAnton** [comment]
Thank you both for following up on this - we'll make sure to post more updates here as if/when this fix is extended to other XCode images :)

**Comment by Drahflow** [comment]
I'm seeing the same error on linux based builds (non-sudo), when running `cat` on a largish file (test outputs).

**Comment by prydonius** [comment]
I've just started seeing this `make: write error` on the `sudo: required` trusty environment (which was updated last Wednesday): https://travis-ci.org/helm/monocular#L2925. Was anyone able to solve this issue?

**Comment by markandrus** [comment]
@prydonius I have not solved this, but I see `tar: write error` often (using travis-multirunner).

**Comment by markandrus** [comment]
I've tried @prydonius's workaround and it works like a charm:

```
group: deprecated-2017Q2
```

Definitely something has changed—I'm not sure what, though.

**Comment by prydonius** [comment]
@markandrus in particular the thing that worked for me was setting `filter_secrets: false` (something Travis support helped me with) https://github.com/kubernetes-helm/monocular/blob/master/.travis.yml#L3

**Comment by vbraun** [comment]
The `make: write error` is almost certainly EAGAIN from stdout. Pretty much every commandline tool expects stdout to be in blocking mode, and does not properly retry when in nonblocking mode. I just spent a fun day figuring out that something inside "npm install ..." was switching to nonblocking mode, causing random failures further down in my build script.

Turn off O_NONBLOCK:

    python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'

Check whether O_NONBLOCK is set (should print "0"):

    python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'

**Comment by felker** [comment]
@vbraun 's post has explained the errors I have been experiencing in https://github.com/travis-ci/travis-ci/issues/8757 . In our case, it was a compilation of a C++ code with MPI that somehow caused a switch to nonblocking mode which caused subsequent compilation `make: write error`. 

I am now able to reproduce the bug outside of Travis CI on my MacBook. I had not observed it locally before because the nonblocking switch requires the two compilations in our test suite to be wrapped by the same process, e.g. the `travis_run_script` command.

**Comment by paulcwarren** [comment]
In case it is helpful I believe I am running into this error.  As you can see my build have been working fine for months and all of a sudden I hit this write error.  It started in this build:-

https://travis-ci.org/paulcwarren/spring-content-examples/builds/316709024

Doesn't matter how often I restart either of the failing builds they fail.  

I am unable to ssh into the container but perhaps you can.

**Comment by j00bar** [comment]
Is this related to #8934?

**Comment by rainwoodman** [comment]
We are seeing this error too. Very long output lines triggers this.

**Comment by NachoSoto** [comment]
Seeing this too.

**Comment by kees-jan** [comment]
It would seem that non-blocking output is set as soon as the build is started. See https://travis-ci.org/kees-jan/scroom/builds/324223965#L785. Thanks @vbraun for catching this.

As far as I can tell, this is a relatively new development. Builds used to work fine.

**Comment by mmdriley** [comment]
In some cases, this may be caused by Node. See the explanation here:
https://github.com/cockroachdb/cockroach/blob/cdfd9981f697b7a8c2d6c0d4dae255a0aa102efb/build/node-run.sh

**Comment by dkfellows** [comment]
I'm guessing that the recent increased incidence of this is due to changes to the runtime environment _outside_ the sandboxes that are handed out.

**Comment by j3mdamas** [comment]
@vbraun thanks for your comment on blocking. as it can be seen, it helped many people solving problems in their builds

**Comment by robertknight** [comment]
> Turn off O_NONBLOCK:
> ```
>   python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
> ```

Thanks! In Python 3.5+ this can be simplified slightly to:

```sh
python3 -c 'import os,sys; os.set_blocking(sys.stdout.fileno(), True)'
```

**Comment by avagin** [comment]
@BanzaiMan Do you have any plan about fixing this issue?

**Comment by BanzaiMan** [comment]
Hi, everyone.

The search continues. Since we've made changes to the existing reports, I'd like to have another round of recent data points. If you have seen the issue in the last 7 days or so, please point to them here.

Thank you so much!

**Comment by avagin** [comment]
@BanzaiMan now O_NONBLOCK (04000) isn't set for stdout, I think it means that the issue was fixed.
```
+ cat /proc/self/fdinfo/1
pos:	0
flags:	0100001
mnt_id:	10
```
https://travis-ci.org/avagin/linux/jobs/352251614

**Comment by brianlheim** [comment]
I'm seeing this a lot on one of my projects: https://api.travis-ci.org/v3/job/357544740/log.txt

**Comment by avagin** [comment]
@brianlheim The date of your log is Dec 14 21:58:09 UTC 2017

**Comment by BanzaiMan** [comment]
@brianlheim Did you restart https://travis-ci.org/supercollider/supercollider/jobs/357544740? I don't see any `write error` that I expect.

**Comment by brianlheim** [comment]
> @brianlheim The date of your log is Dec 14 21:58:09 UTC 2017

That's the date on the build image; this build log is from today.

https://travis-ci.org/supercollider/supercollider/jobs/357544740

> Did you restart https://travis-ci.org/supercollider/supercollider/jobs/357544740? I don't see any write error that I expect.

I didn't restart it. Toward the end of the log you'll see `[Errno 11] Resource temporarily unavailable`.

**Comment by avagin** [comment]
@brianlheim Could you try to reproduce this issue with this patch https://github.com/avagin/supercollider/commit/8f0bfd3f1ea23eeee76d27fb5244421a5166b79d?

**Comment by brianlheim** [comment]
@avagin Sure! The job is here: https://travis-ci.org/supercollider/supercollider/jobs/357667827

**Comment by avagin** [comment]
From this log, we see that O_NONBLOCK isn't set on stdout and stderr.
```
[0K$ cat /proc/self/fdinfo/1
pos:	0
flags:	0100001
mnt_id:	10
```
@brianlheim The job completed successfully. Could you re-execute it? We need to reproduce the issue.

**Comment by avagin** [comment]
@brianlheim I saw that you reproduced this issue. Thank you.
https://travis-ci.org/supercollider/supercollider/jobs/357667827

```
[0Ktravis_fold:end:before_install.1
[0Ktravis_fold:start:before_install.2
[0Ktravis_time:start:0ce8ecd2
[0K$ cat /proc/self/fdinfo/2
pos:	0
flags:	0100001
mnt_id:	10
...
[0Ktravis_fold:start:before_script.1
[0Ktravis_time:start:0235ed5a
[0K$ cat /proc/self/fdinfo/1
pos:	0
flags:	0104001
mnt_id:	10
```

From this log, we can see that O_NONBLOCK was set on the before_install stage. Can it be set by one of command which was executed on this stage? Should travis-ci handle this situation somehow?

**Comment by whitequark** [comment]
I'm still seeing this failure on _every single macOS build_ of solvespace/solvespace. Nothing helps. Not `filter_secrets: false`, not `before_script:  - "python -c 'import os,sys,fcntl; fix = lambda stream: fcntl.fcntl(stream, fcntl.F_SETFL, fcntl.fcntl(stream, fcntl.F_GETFL) & ~os.O_NONBLOCK); fix(sys.stdout); fix(sys.stderr)'"`...

**Comment by whitequark** [comment]
The workaround that _did_ work for me is piping the script output through `awk '/.{0,32}/ {print $0}'`.

**Comment by tnguyen14** [comment]
I recently encountered this while running the command to install `google-cloud-sdk`.  Can this issue be reopened?

**Comment by mikermcneil** [comment]
Got here from google?  Read all the things but still confused?  @vbraun's answer is probably a good hint as to what's happening-- at least it was for us.  Had this happen twice now on our team this year, and every time it was a node script doing funny things w/ stdout, but the impact not being seen until later in the build script (e.g. when doing `git commit`)

**Comment by samvv** [comment]
@vbraun I know these issues shouldn't be used to thank people, but really you saved my day. I would never have found the issue if it weren't for you 👍

**Comment by bwheatley** [comment]
> The `make: write error` is almost certainly EAGAIN from stdout. Pretty much every commandline tool expects stdout to be in blocking mode, and does not properly retry when in nonblocking mode. I just spent a fun day figuring out that something inside "npm install ..." was switching to nonblocking mode, causing random failures further down in my build script.
> 
> Turn off O_NONBLOCK:
> 
> ```
> python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
> ```
> Check whether O_NONBLOCK is set (should print "0"):
> 
> ```
> python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'
> ```

Those 3 lines saved me banging my head against a wall due to a similar node issue. Thank you. <3

**Comment by aaqaishtyaq** [comment]
Hey, Is there any fix for `tar: write error`. I'm still getting this error.

**Comment by pramodk** [comment]
We are having same issue ([here](https://travis-ci.com/github/neuronsimulator/nrn/jobs/340164639#L5860))!
