### ISSUE TITLE
Branch whitelist doesn't seem to be working

### ISSUE THREAD

**Issue by justbuchanan** [travis-ci/travis-ci#4708]
We added a branch whitelist so that our project only runs travis-ci on the master branch, but it doesn't seem to be working - travis runs on all branches.

Our repo can be found at https://github.com/robojackets/robocup-software

**Comment by joshk** [comment]
Have you also added the config to all the branches which have a .travis.yml?

**Comment by justbuchanan** [comment]
There may be some branches that don't have it, but I'm seeing non-master branches that do have this configured being run on travis.

**Comment by joshk** [comment]
Can you please point us to some builds?

**Comment by justbuchanan** [comment]
Sure, try this branch: https://github.com/RoboJackets/robocup-software/tree/travis-whitelist-test.

I actually realized that I was reading this wrong - on the "branches" page in GitHub, clicking on the status indicator for this branch shows a travis build in progress.  Clicking on this though takes me to the currently-pending travis build on the master branch.  Looks like it's not actually building non-whitelisted branches, but it is giving them a status indicator, which is a little confusing.

**Comment by joshk** [comment]
We set the commit status only, if you think there is an issue you might want to report this to GitHub.

Since everything is working, can this issue be closed?

**Comment by justbuchanan** [comment]
Is it expected behavior for blacklisted branches to show a status indicator that links to the master branch?  It'd be nice if travis only set a status for branches that travis is being told to run on.

Yeah this issue can be closed, it's not actually ignoring the whitelist like I originally thought.  Thanks for the help!

**Comment by justbuchanan** [comment]
Actually I think travis still builds pull request branches even if they include a travis config that whitelists only the master branch.  See this branch in our repo: https://github.com/RoboJackets/robocup-software/tree/fix-external-forks.

I have since disabled pull requests in the travis web interface, but it seems like it should have ignored those PRs before anyways.

**Comment by BanzaiMan** [comment]
@justbuchanan I don't see any build for the `fix-external-forks` branch in https://travis-ci.org/RoboJackets/robocup-software/branches. PR build for this branch (https://github.com/RoboJackets/robocup-software/pull/402) ran here (https://travis-ci.org/RoboJackets/robocup-software/builds/77331809) presumably before you disabled PR builds, and the PR builds are considered to be on the head branch (the branch into which the PR will be merged; "master" in this case).

It seems to me that everything is working as expected. Did you find any documentation lacking or confusing about this?

**Comment by justbuchanan** [comment]
Ahh ok, that makes sense.  I didn't realize that PR builds are considered to be on the head branch.  Thanks for clearing that up.

It still seems a little counter-intuitive to me though that travis shows a status on blacklisted branches (which links to the latest build on master).  Is this expected behavior?

**Comment by BanzaiMan** [comment]
Where is the status shown?

**Comment by justbuchanan** [comment]
It's on the branches page for our repository: https://github.com/RoboJackets/robocup-software/branches

Take a look at the `travis-whitelist-test` branch.  It shows that travis-ci was run, but the "Details" link points to the latest build on `master`.

**Comment by BanzaiMan** [comment]
Has there been any build on Travis CI on this particular branch after it was created from `master`?

If I create a new branch and push to GitHub, that status bubble inherits all the checks from the parent branch from which the new branch was created. When a build finishes on Travis and sends update to GitHub, the status will reflect the new build status of the new branch.

**Comment by justbuchanan** [comment]
Ok, I think you're right - I made the new branch but didn't add any commits to it, so it showed the same status as that commit on master.  I think everything's good here, I was just confused on what was going on.  Thanks for clearing this up!

**Comment by larryTheGeek** [comment]
https://travis-ci.org/larryTheGeek/RideApi/jobs/397218707 does no capture commits for other branches
