### ISSUE TITLE
Preinstall fastlane on OS X/iOS builds

### ISSUE THREAD

**Issue by maxgoedjen** [travis-ci/travis-ci#4711]
http://fastlane.tools is pretty quickly eclipsing http://nomad-cli.com in terms of developer tooling, I'd love to have that preinstalled on the appropriate images – takes forever to install otherwise (couple minutes without docs).

**Comment by bejo** [comment]
+1, having Fastlane preinstalled would be great!

**Comment by klefevre** [comment]
+1

**Comment by BanzaiMan** [comment]
We will update this issue when there is one to share. Thank you.

**Comment by henrikhodne** [comment]
:tada: http://blog.travis-ci.com/2015-09-09-xcode7-gm/

fastlane is preinstalled on our new Xcode 7 GM image, and will be preinstalled on all new images we generate in the future. Thank you for suggesting this!
