### ISSUE TITLE
[ci skip] for the build matrix

### ISSUE THREAD

**Issue by tarekziade** [travis-ci/travis-ci#4713]
It would be nice to be able to skip some of the builds when we change for example only the docs.

e.g. I have a build that builds the docs and validates it, but I want to skip the other builds that run tests on the code.

**Comment by BanzaiMan** [comment]
Do you have an example repository to show this use case?

**Comment by grooverdan** [comment]
introduce and env variable into one build of the matrix and build the docs there and not on the other builds.

**Comment by BanzaiMan** [comment]
Assuming that this can be implemented, how does one specify which jobs within a build to skip? Skipping a CI seems to me a build-level concern, not job-level.

**Comment by kevinansfield** [comment]
Something like this would be really useful for our use-case case too where we have both client and server in the same repo. Having the ability to disable the server-side tests when only the client files have changed would save a lot of time running pointless tests.

As you can see in [our travis.yml](https://github.com/TryGhost/Ghost/blob/master/.travis.yml) we have a matrix for various node/db configs and then an `include` that adds the environment-independent client test suite at the end. Every time we make a client-only change we have ~1hr of total build time on unrelated test suites before the client test suite even begins.

**Comment by BanzaiMan** [comment]
I'm going to close this in favor of #6301.
