### ISSUE TITLE
CocoaPods gem not updating to latest version

### ISSUE THREAD

**Issue by abbeycode** [travis-ci/travis-ci#4715]
Part of my build requires a `pod update` to run. Since CocoaPods is crashing on me, I'd like to install the latest pre-release version. I added this line to my `.travis.yaml`:

    before_install:
        - gem install cocoapods --pre

CocoaPods updates, [as you can see here](https://travis-ci.org/abbeycode/UnzipKit/jobs/77593467#L106), but then when the `pod update` call runs, CocoaPods is still [on an old version](https://travis-ci.org/abbeycode/UnzipKit/jobs/77593467#L127).

What am I doing wrong?

**Comment by BanzaiMan** [comment]
Try `bundle exec pod`.

**Comment by abbeycode** [comment]
Thanks for the suggestion. I tried that now, [and got](https://travis-ci.org/abbeycode/UnzipKit/jobs/77682079#L132):

> Could not locate Gemfile or .bundle/ directory

**Comment by BanzaiMan** [comment]
Confirmed this issue with the Xcode 7 image The .default OS X image sites bit exhibit this problem.

**Comment by abbeycode** [comment]
Thanks @BanzaiMan, do you know of any workaround?

**Comment by BanzaiMan** [comment]
Sorry, but I don't know.

**Comment by abbeycode** [comment]
Interesting - the Xcode 7 GM build still didn't actually upgrade CocoaPods correctly, but the problem exception my `pod install` line was causing is gone, so I don't need to upgrade it anymore, either.
