### ISSUE TITLE
Docker: Unable to push after appearentlly successful login

### ISSUE THREAD

**Issue by chad-autry** [travis-ci/travis-ci#4717]
Following the documentation http://docs.travis-ci.com/user/docker/ I attempt to build and then push a docker image to dockerhub.

docker login is apparently successful,
```
0.82s$ docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
WARNING: login credentials saved in /home/travis/.docker/config.json
Login Succeeded
```

Then later on during the push attempt hangs and indicates that I need to log on.

```
$ docker push chadautry/stdin-eval-stdout
The push refers to a repository [chadautry/stdin-eval-stdout] (len: 1)
Please login prior to push:
Username (chadautry): 
```

I've tried moving the login to various points in the build. No change. Definitely the correct login password, it fails if I edit it to be incorrect so isn't just silently failing.

**Comment by chad-autry** [comment]
https://travis-ci.org/chad-autry/stdin-eval-stdout/builds
https://github.com/chad-autry/stdin-eval-stdout/blob/master/.travis.yml

**Comment by smiller171** [comment]
Instead of telling the docker service to start, try adding
    services:
      - docker
to your travis.yml

**Comment by smiller171** [comment]
It's working for me in after_script

https://github.com/smiller171/ansible-docker-images/blob/master/.travis.yml
https://travis-ci.org/smiller171/ansible-docker-images

**Comment by chad-autry** [comment]
@smiller171 
Thanks, for the working example. At least I know it is working for someone.
I just incrementally simplified, and simplified my .travis.yml trying to make it look more and more like yours. Until finally I'm as simple as possible https://github.com/chad-autry/stdin-eval-stdout/blob/2ea8218f1af1ec5600352be5ccc107b9f82fb869/.travis.yml

But still no luck https://travis-ci.org/chad-autry/stdin-eval-stdout/builds/78146440

I don't know what my problem is. Login seems like it is succeeding.

**Comment by smiller171** [comment]
@chad-autry Perhaps there is an issue with Docker incorrectly saying you have authenticated when you actually have not?

I would double check email, username, and password are correct.

Also, are you sure you are pushing to the same repository that you are logging in with?

I had issues at first logging in, because I had to escape a '$' in my password.

**Comment by joshk** [comment]
could you try updating Docker in a before_install or before_script step? I believe Docker 1.7.1 had a fix for this issue.

**Comment by chad-autry** [comment]
After sleeping on it, I've figured out what the issue has to be.

This Docker Hub project was originally an Automated Build. 
> You cannot push to an Automated Build with the docker push command. You can only change the image by committing code to your GitHub or BitBucket repository."

I thought I had turned off it being an automated build by unchecking a box. It doesn't work that way. I will need to delete the automated build and re-push.

Thanks for the assistance.
