### ISSUE TITLE
iojs failing to install which fails build

### ISSUE THREAD

**Issue by danawoodman** [travis-ci/travis-ci#4718]
It seems Travis is somehow failing on `iojs` builds, which seemed to work earlier today. Here is the output of the iojs build:

```
$ nvm install iojs
Version 'iojs' not found - try `nvm ls-remote` to browse available versions.
The command "nvm install iojs" failed and exited with 3 during .
Your build has been stopped.
```

Here is my `.travis.yml`:

```yml
sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
script: 'npm test'
```

**Comment by danawoodman** [comment]
Here is an example failed build: https://travis-ci.org/danawoodman/set-state-mixin/jobs/77640840

**Comment by roidrage** [comment]
Thanks for reporting.

This is already being investigated. https://iojs.org started using CloudFlare, with strict TLSv1.2 enabled, as it seems, which does not appear to be compatible with the curl/OpenSSL combination included in Ubuntu 12.04. They're looking into it.

**Comment by roidrage** [comment]
Just verified, this has been fixed. Restarting previously failing builds should help get them back to green.

**Comment by danawoodman** [comment]
Awesome, thanks, restarting worked!
