### ISSUE TITLE
Not use jruby 9000 In spite of definition in .travis.yml

### ISSUE THREAD

**Issue by marutosi** [travis-ci/travis-ci#4720]
In spite of definition in .travis.yml, jruby 9.0.0.0.pre1 is used.
https://github.com/rvm/rvm/pull/3472

https://github.com/sparklemotion/nokogiri/blob/f9f40794acd8e142429326eed945cd9b731d058d/.travis.yml#L13
https://travis-ci.org/sparklemotion/nokogiri/jobs/77073479#L91

**Comment by BanzaiMan** [comment]
Until we update the build environments, please update rvm in `before_install`:

```yaml
before_install
  - rvm get head
  - rvm use jruby-9.0.0.0 --install
  ⋮
```

**Comment by perlun** [comment]
This one would be *really* nice to get fixed. Ruby 9.0 was released literally *months* ago (July 22). Since it takes around 2 minutes to run

> rvm get master && rvm install jruby-9.0.1.0 && gem install bundler --no-ri --no-rdoc

...this slows down *all* our builds using JRuby 9.0.

Please? :smile: (We are a paying customer btw, but I think the FOSS community would also benefit from first-class JRuby 9k support in Travis).

**Comment by keithrbennett** [comment]
This is an rvm issue.  The rvm developer(s) have fixed this on head but not yet released a new version.  That is why 'rvm get head' solves the problem.  See for more info: https://github.com/rvm/rvm/issues/3475

**Comment by perlun** [comment]
The list of Ruby versions here now includes 9k, but only quite old versions: http://rubies.travis-ci.org/

9.1.2.0 was released months ago. Could we get a binary of it for Ubuntu 14.04? It would speed up our builds _a lot_; right now the Ruby installation takes about 1,5 minutes.

**Comment by dentarg** [comment]
Just checked for myself, and another CI service, Semaphore, seems to support 9.1.20: https://semaphoreci.com/docs/languages/ruby/ruby-support-on-semaphore.html, might help someone in the meantime
