### ISSUE TITLE
Version '0.12' not found - Error just started appearing in builds

### ISSUE THREAD

**Issue by jbrantly** [travis-ci/travis-ci#4723]
My build just started failing with this:

```
$ nvm install 0.12
Version '0.12' not found - try `nvm ls-remote` to browse available versions.
The command "nvm install 0.12" failed and exited with 3 during .
```

There were no changes to `.travis.yml` (and no significant changes to the repo, just a change to README.md)

See https://travis-ci.org/jbrantly/ts-loader/jobs/77971949

**Comment by BanzaiMan** [comment]
`nvm` failed to find available versions. Please re-run the build and see if the problem persists.

**Comment by jbrantly** [comment]
That was the first thing I tried before submitting an issue :D Unfortunately it actually made it slightly worse (in the original build, one of the two jobs works. After the rebuild both jobs failed). I just rebuilt again at your suggestion and it seems to have worked. *shrug* Just one of those glitches I suppose, sorry for the bother.
