### ISSUE TITLE
Add support for AWS CodePipeline

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#4724]
I'd like to use steps that wait for a Travis build to finish before continuing to the next steps in the the pipeline. Currently it's not supported out of the box with Travis but does support Jenkins.
The guide for creating an AWS CodePipeline can be found at http://docs.aws.amazon.com/codepipeline/latest/userguide/how-to-create-custom-action.html#how-to-create-job-agent-workflow

**Comment by roidrage** [comment]
Thanks for opening this issue. At the moment, we don't have any immediate plans to support CodePipeline.

**Comment by samsamm777** [comment]
+1

**Comment by smartnut007** [comment]
+1

**Comment by PhilGuay** [comment]
+1

**Comment by malwhittaker** [comment]
+1

**Comment by acnagy** [comment]
@fh kindly [suggested](https://twitter.com/fholzhauer/status/740890178257080322) a workaround on this for now over here: http://docs.aws.amazon.com/codepipeline/latest/userguide/how-to-manually-start.html#how-to-manually-start-cli

**Comment by BanzaiMan** [comment]
If anyone is interested in providing support, the code is found at https://github.com/travis-ci/dpl/
