### ISSUE TITLE
nvm fails on mac osx, so the whole build fails

### ISSUE THREAD

**Issue by Gum-Joe** [travis-ci/travis-ci#4726]
When build nodejs projects on mac osx with multiple versions of nodejs, travis returns the error that the command `nvm` failed when changing the nodejs version.

Here is a screen shot from my build (https://travis-ci.org/Gum-Joe/Web-OS/builds/78088636):
![screenshot 1](https://cloud.githubusercontent.com/assets/12299307/9586794/baaaf304-5016-11e5-8956-0892091543fb.png)

This issue can be recreated by:
* Creating a nodejs travis build
* Inserting multiple Nodejs versions in .travis.yml:
```
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "stable"
  - "iojs"
```
* Telling travis to build on mac osx:
```
os:
  - Linux
  - osx
```
* And try building the project

**Comment by BanzaiMan** [comment]
We do not yet support Node.js on the Mac. Sorry. https://github.com/travis-ci/travis-ci/issues/2311
