### ISSUE TITLE
OSX hosts fail installing python

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#4729]
Builds with `os: osx` and `language: python` are failing with the following:

Python 2.7
```
Using worker: worker-jupiter-brain:42cb5332-399c-4354-8e06-61701ed4b15a (20f8150e-cb56-4ace-a18a-930dfb40fcfd:)
Build system information
Build language: python
2.7 is not installed; attempting download
/Users/travis/build.sh: line 229: lsb_release: command not found
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

Python 3.3
```
Using worker: worker-jupiter-brain:1ade3cd1-6915-4d69-96f8-dc291b473be3 (f0a8f95d-fb13-4c3b-a948-083f3afcb15b:)
Build system information
Build language: python
3.3 is not installed; attempting download
/Users/travis/build.sh: line 229: lsb_release: command not found
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```
Python 2.6 and Python 3.4 are the same.

Later in each build the virtualenv fails:
```bash
$ source ~/virtualenv/python2.7/bin/activate
/Users/travis/build.sh: line 41: /Users/travis/virtualenv/python2.7/bin/activate: No such file or directory
```

That problem can be seen on the `env: matrix:` builds, which are the first eight jobs on:
https://travis-ci.org/jayvdb/pywikibot-core/builds/78131369

Another bug is that the jobs 9-19 on that build, which are from `matrix: include: `, are run on Linux when `osx` was requested and while displaying the `osx` logo.

**Comment by BanzaiMan** [comment]
We don't support Python on OS X yet. Sorry. https://github.com/travis-ci/travis-ci/issues/2312

**Comment by jayvdb** [comment]
Hi @BanzaiMan , the main repo has had

```yaml
...
language: python
...
os:
  - linux
  - osx
```

Until today, the `os: osx` with `language: python` was discarded, and only Linux builds were created.
Now it is attempting to start OSX builds.  See last build on
https://travis-ci.org/wikimedia/pywikibot-core/builds

We can easily remove the `osx`.  No worries there.  But if it isnt supported, the yaml parser should discard it.

Also, did you see the last paragraph of the original report: it is actually creating Linux instances when only `os: osx` is requested.

**Comment by BanzaiMan** [comment]
We have enabled the multi-os feature for all repositories today, so we started building your Mac builds you specified.

You raise a good point about dropping unsupported build configurations. The reason for this behavior is mostly historical, but also that it is difficult to configure what is expected to work and what is not.

The last point seems to be a legitimate bug, but unrelated to the issue you raised. Please open a separate issue.

Thank you!

**Comment by jayvdb** [comment]
Is there an issue already about unsupported build configurations?
If not, where would detecting unsupported build configurations be best handled, if someone was to have a crack at it?  At the https://github.com/travis-ci/travis-yaml stage , or later in the process ?

**Comment by blag** [comment]
@BanzaiMan Is Python on OS X supported now? I am having the same issue: https://travis-ci.org/SecurityInnovation/PGPy/jobs/204804784

Thanks!

**Comment by BanzaiMan** [comment]
@blag We do not at the moment.

**Comment by blag** [comment]
@BanzaiMan Okay, thanks for letting me know. Please update this thread when it gets added.

**Comment by lukaskollmer** [comment]
Any updates on this?

**Comment by bhylak** [comment]
Also which this was possible.. I'm using pyobjc so Linux builds are impossible.
