### ISSUE TITLE
[FEATURE REQUEST] Add yellow state for warnings

### ISSUE THREAD

**Issue by moylop260** [travis-ci/travis-ci#4730]
A cool feature is can use yellow state for warning cases.

Many compiler use basic states:
  - done: green
  - warning: yellow
  - error: red

In fact, everyone uses 3 states at traffic lights:
 - pass: green
 - warning: yellow
 - stop: red

We feel frustrated with builds in red state by [lint](https://en.wikipedia.org/wiki/Lint_%28software%29) cases because we can't use warning (yellow) state.

We can see a better code state by example:
'Hey, all is fine in your code, you can use it but this can be better with next lint conventions...'
 - Use CapWords style.
 - Remove unused variables.
 - And so on...

What do you think?

**Comment by saltinejustine** [comment]
Hey Moises, thanks for opening an issue and taking the time to explain why you'd like to use 'yellow' for warning. Our warnings are red on travis for errored or failed builds along with icons for our accessibility towards color-blind individuals.

Color concept is a tricky subject as it's entirely subjective to the culture, country and region you're from. And I understand that you're used to treating yellow as a warning. I, myself, from the United States use Yellow more as a caution (yield signs, preparing to slow down my vehicle, etc,) whereas my team members in Germany see yellow as a sign to start their vehicles, (yellow light starts before the light has turned green). 

I super appreciate your feedback and have noted it. Should we decide to revisit our status colors in the future, I'll take it into consideration.

Have a great day!

**Comment by moylop260** [comment]
Thank for answer.

**Comment by moylop260** [comment]
What about use success_with_warnings like as other CIs:
 - https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/5004/diffs#5492807eeff7d8f64b722d397811464b1becdf97_119_122


cc @BanzaiMan

**Comment by adrienbernede** [comment]
Hello, this may be a long closed issue, but I would like to bring a fresh look on it.

A "succeed with warnings" would be useful in combination with "allow_failures" IMO.

Allow_failures does not mean "should faild", so I believe there should be a third state "warning"
to show, back the PR, that Travis jobs didn’t run "perfectly" and would use a closer look.

**Comment by marc-h38** [comment]
Can this be re-opened? I think most people don't care what the color is (it's called "orange" in my country, "amber" elsewhere), the request  is really about **warnings** = intermediate state between pass and fail.

> whereas my team members in Germany see yellow as a sign to start their vehicles, (yellow light starts before the light has turned green).

It's actually yellow AND red together before green in Germany and others. The middle light **alone** is universally announcing an imminent stop and universally a warning sign when flashing.

PS: https://jenkins.io/blog/2012/03/13/why-does-jenkins-have-blue-balls/
