### ISSUE TITLE
OS-X Clang 6.1.0 availability? 

### ISSUE THREAD

**Issue by sushihangover** [travis-ci/travis-ci#4732]
#### Currently the OS-X environment provides Clang 6.0:
![screen shot 2015-08-31 at 8 52 22 pm](https://cloud.githubusercontent.com/assets/1294194/9595934/48d01ce4-5022-11e5-939b-f57f02200dd8.png)

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```
#### Is it possible to get the latest clang installed? 

Is there something manually I can do to install it into the environment?

```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by BanzaiMan** [comment]
http://docs.travis-ci.com/user/languages/objective-c/ Please use a newer image. Either `osx_image: xcode6.4` or (not yet documented but blogged) `osx_image: xcode7` should do.

**Comment by sushihangover** [comment]
Thanks!, I was scratching my head on that on as I was seeing 6.1 in the docs as the default, but thinking Clang 6.1 not Xcode 6.1... thus I need Xcode 6.4 for Clang 6.1.0...

http://docs.travis-ci.com/user/languages/objective-c/#Xcode-6.1
