### ISSUE TITLE
Environment variables from repository settings are not passed to build

### ISSUE THREAD

**Issue by dploeger** [travis-ci/travis-ci#4734]
The latest builds in https://travis-ci.org/Zimbra-Community/python-zimbra don't get the environment variables, that are defined in the repository settings, anymore.

As there was a long time with no builds, maybe the workflow for these variables have changed over time? But I don't see anything special in the documentation about it.

I've just set up the environment variables and use them in the script. That worked until build 36.

**Comment by BanzaiMan** [comment]
Those are pull request builds, which do not decrypt secure variables for security reasons.

**Comment by BanzaiMan** [comment]
See http://docs.travis-ci.com/user/environment-variables/#sts=Defining Variables in Repository Settings.
