### ISSUE TITLE
On Mac, jobs that exceeds log size limit (4 MB) does not terminate immediately

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4736]
And instead, it runs until the time limit is reached. See https://travis-ci.org/thrill/thrill/builds/78005892, and compare 89.1 and 89.7.

**Comment by postmechanical** [comment]
+1 ran into this recently.

**Comment by scpeters** [comment]
+1, I opened #4916 but it's a duplicate of this

**Comment by ytwytw** [comment]
+1, just happened to me today

**Comment by BanzaiMan** [comment]
Closing this in favor of https://github.com/travis-ci/travis-ci/issues/6149.
