### ISSUE TITLE
Multiple Redis on Container Infrastructure

### ISSUE THREAD

**Issue by jpulec** [travis-ci/travis-ci#4737]
I work with a travis project that uses multiple redis instances. As referenced in #1199 we set up multiple redis instances and create the necessary directories via sudo.

We're looking to eventually move to travis's container based infrastructure, and wondering if and how we would still be able to run multiple redis instances. Any push in the right direction would be much appreciated.

**Comment by BanzaiMan** [comment]
Hello. Redis can be set up such a way that you can store the configuration file anywhere on the file system. Then, you can bind to any port you like, and connect to that.

All of this can be done without `sudo`.

**Comment by jpulec** [comment]
Thanks!
