### ISSUE TITLE
The "build pull requests" setting doesn't enable PR builds (probably corner case)

### ISSUE THREAD

**Issue by reinout** [travis-ci/travis-ci#4739]
Short version: pull requests aren't being build for https://travis-ci.org/buildout/buildout/, even though we've switched the relevant setting from on to off and back to on. See below animated gif.

![pr_switch_doesnt_always_work](https://cloud.githubusercontent.com/assets/121433/9626285/c2ba5ab6-515c-11e5-9d28-1930ddc85838.gif)

I assume it is a **corner case**. Reason: the initial hook setup was probably done, years ago, with a script. See https://github.com/travis-ci/travis-ci/issues/2050 for details. This script passed a list of "events" which omitted the pull request event. 

To me, there seem to be two somewhat separate problems/solutions:

- Could you switch on PR builds by hand for https://travis-ci.org/buildout/buildout/ ? This would solve our immediate need (https://github.com/buildout/buildout/issues/206) :-)

- You might want to look at the "enable pull request builds" setting, as it apparently isn't able to overcome our initial mis-configuration. (This might be too much of a corner case, though, to spend time fixing. That's something I cannot really make a good estimation for).

I can make small pull requests if necessary for debugging this.

**Comment by BanzaiMan** [comment]
Hello. Sorry for the troubles.

The hook we had was not listening on PR events for this repository. I've fixed this now, so it should work.

I *think* any new push to an open PR should trigger a build. If not, do let us know.

**Comment by reinout** [comment]
Thanks, it works!

<img width="867" alt="screen shot 2015-09-02 at 14 32 26" src="https://cloud.githubusercontent.com/assets/121433/9631236/ce955098-517f-11e5-8b38-9e80f12c4a67.png">
