### ISSUE TITLE
[QUESTION] Is there way to use a custom docker image?

### ISSUE THREAD

**Issue by moylop260** [travis-ci/travis-ci#4741]
We have docker images with all packages pre-installed and pre-configured.
We need run `script` and `install` section of `.travis.yml` to run test.
Is posible configurate a docker custom image in .travis.yml to use it?

This save a lot time and help me to test my docker image plus my repository source code.

**Comment by BanzaiMan** [comment]
Have you tried `docker pull` in `before_install`?

**Comment by BanzaiMan** [comment]
Is there anything to address on this issue?

**Comment by moylop260** [comment]
@BanzaiMan 
Thanks for reply
I'm talking about of use for example:
```bash
docker pull quay.io/travisci/travis-python
docker run --name quay.io/moylop260/travis-python-custom quay.io/travisci/travis-python bash
pip install -r requirements.txt
apt-get install packages
wget extras-download

git push quay.io/moylop260/travis-python-custom 
```

And now use it in my builds with
.travis.yml 
```
language: moylop260/python-custom
```

**Comment by BanzaiMan** [comment]
@moylop260

Am I correct to understand that, in the end, you want to use the Python image with your requirements pre-installed? Then creating a custom Docker image on top of our build image is not what you want. It is too big for your purposes. (I am also not sure what `git push…` is supposed to do; I assume you meant `docker push …`.)

If you have a public repository using the containers (http://docs.travis-ci.com/user/workers/container-based-infrastructure/) you can simply set up cache (http://docs.travis-ci.com/user/caching).

If you want to use custom Python image, you might want to start with https://hub.docker.com/_/python/.

In all cases, the `language` value in your `.travis.yml` should be one that's recognized; in your case `python`.

**Comment by moylop260** [comment]
Hello BanzaiMan,
Thanks for reply.

typo with `git push` I'm talking about `docker push`.

But I'm understand your point of set up cache I saw the doc.
I will to use it.

However, should be a cool feature that we can choose image where you can run the default travis-ci script from `.travis.yml` structure similar to [shippable](http://docs.shippable.com/docker_build/#post-ci-dockerbuild)
We make a custom image and set up use this one and later `install`, `script` and other `.travis.yml` section are executed into this image.
This is useful when you have a image with all installed and require `sudo`.

But thank you for information.
