### ISSUE TITLE
Test terminates abruptly with “flushU”

### ISSUE THREAD

**Issue by pcantrell** [travis-ci/travis-ci#4742]
(Another rare, intermittent, and non-reproducibly failure. Sorry!)

iOS project, Xcode 7 beta.

In the middle of running tests, Travis abruptly terminates with a mysterious “`flushU`” and then nothing. Build marked as failing; no further diagnostics.

Normally, when a process fails, Travis prints some sort of summary at the bottom of the log. I'm therefore guess that it's Travis itself, not a build process, that bombed.

Here's the build: https://travis-ci.org/bustoutsolutions/siesta/builds/78428342

**Comment by BanzaiMan** [comment]
I think this is a different manifestation of #4716. I'm closing this as such.

**Comment by pcantrell** [comment]
Yes, agreed that it appears to be the same issue.
