### ISSUE TITLE
Mention ssh-agent eval in docs

### ISSUE THREAD

**Issue by gsf** [travis-ci/travis-ci#4743]
According to #3652 one must eval the ssh agent before running ssh-add, but that isn't clear in http://docs.travis-ci.com/user/deployment/custom/.

**Comment by BanzaiMan** [comment]
Closed by https://github.com/travis-ci/docs-travis-ci-com/pull/244

**Comment by gsf** [comment]
Ha I didn't see that PR! Thanks.
