### ISSUE TITLE
Mapping ports to host sometimes fail in build environments that support docker

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#4744]
See https://travis-ci.org/josiahcarlson/rom/jobs/78534216#L44 for example.

**Comment by joshk** [comment]
Sorry, do you have some more information on how this might be a Travis issue?

**Comment by thedrow** [comment]
This always works on my machine or anybody else's for that matter.
That's a basic port mapping between the container and the host. A feature that worked in docker for a very long time.
If that's not supported for some reason, that should be documented.

**Comment by joshk** [comment]
We are not aware of it not being supported on our setup. From what I could see from the build, only one failed. Are you saying that port mapping isn't working at all on Travis?

**Comment by thedrow** [comment]
Yes, port mapping doesn't work but it's not a consistent problem.
Jobs that fail to start the Docker container:
https://travis-ci.org/josiahcarlson/rom/jobs/78534399
https://travis-ci.org/josiahcarlson/rom/jobs/78534400
Jobs that succeed to start Docker container:
https://travis-ci.org/josiahcarlson/rom/jobs/78534398
They all belong to the same repo and build.

**Comment by joshk** [comment]
could you try adding a before_install script which updates the version of Docker. eg.

```yaml
before_install:
  - sudo apt-get update
  - sudo apt-get install lxc-docker
```

**Comment by thedrow** [comment]
Done in https://github.com/thedrow/rom/commit/73ab62fc5316ee1cdae323f52f6f622fe071ca77

**Comment by thedrow** [comment]
So docker didn't fail with 1.7.1 but that's just one build. How do we verify this?

**Comment by joshk** [comment]
Could you maybe start by rerunning the build several times?

**Comment by nakedible** [comment]
I'm seeing the exact same problem. The same build either works or doesn't work, depending on luck. Restarting the build usually fixes the issue. I think 1 in 10 failures as a guess. We are using the paid plan, and I have not tested updating docker at start of build.

**Comment by tonylukasavage** [comment]
I've had the problem consistently, with every build, whenever I attempt to `EXPOSE` and forward a port using the `-p` or `-P` option with `docker run` when running builds in travis. Upgrading from the default docker 1.7.0 to 1.7.1 via the method mentioned by @joshk works for me, but adds ~10-15 seconds to my builds. 

Would it be possible for Travis to consider making the default docker version 1.7.1 to save us from having to add it to all of our .travis.yml files?

**Comment by lhanson** [comment]
I'm seeing this too, but the workaround (`sudo apt-get install lxc-docker`) did not work for me, I'm currently forced to detect when my app is running on Travis and remap the database port to something else.
