### ISSUE TITLE
hipchat notifications to multiple rooms

### ISSUE THREAD

**Issue by jonfen** [travis-ci/travis-ci#4747]
http://docs.travis-ci.com/user/notifications/

Is there a way to configure notifications to multiple rooms?

**Comment by BanzaiMan** [comment]
Pass an array to `notifications.hipchat.rooms`.

**Comment by jonfen** [comment]
I tried an array, but only ROOM 2 (below) received a message:

travis encrypt [TOKEN]@[HIPCHAT SERVER]/[ROOM ID] -r [GITHUB USER]/[REPO] --add notifications.hipchat.rooms

notifications:
  hipchat:
    rooms:
      secure: [TRAVIS ENCRYPTED ROOM 1]
      secure: [TRAVIS ENCRYPTED ROOM 2]
    template:
    - '%{author} pushed to branch <a href="https://github.com/jonfen/%{repository_name}/tree/%{branch}">%{branch}</a>
      of <a href="https://github.com/jonfen/%{repository_name}">%{repository_slug}</a>
      <br>- %{commit_message} (<a href="%{compare_url}">%{commit}</a>) <br>- build
      #%{build_number} (<a href="%{build_url}">%{build_id}</a>) %{result} in %{duration}'
    format: html
    notify: false
    on_success: change
    on_failure: always

**Comment by BanzaiMan** [comment]
I believe you need:

```yaml
notifications:
  hipchat:
    rooms:
      - secure: [TRAVIS ENCRYPTED ROOM 1]
      - secure: [TRAVIS ENCRYPTED ROOM 2]
```

See http://docs.travis-ci.com/user/encryption-keys/#Detailed-Discussion

**Comment by jonfen** [comment]
That worked, thank you.

**Comment by tsal** [comment]
For anyone that comes across this, the above link has been changed to https://docs.travis-ci.com/user/encryption-keys/#detailed-discussion - minor difference, but this will take you straight to it.
