### ISSUE TITLE
/home/travis/.ssh/known_hosts: Permission denied

### ISSUE THREAD

**Issue by abesto** [travis-ci/travis-ci#4748]
This has caused confusion, probably a build failure in https://travis-ci.org/openzipkin/docker-zipkin/builds/78704161, the relevant message is around the middle:

```
Failed to add the RSA host key for IP address '192.30.252.130' to the list of known hosts (/home/travis/.ssh/known_hosts).
```

`whois` shows the IP belongs to GitHub:

```
whois 192.30.252.130 | grep OrgName
OrgName:        GitHub, Inc.
```

To work around this a bit more forcefully I've added `github.com` as described in http://docs.travis-ci.com/user/ssh-known-hosts/, but that also failed in https://travis-ci.org/openzipkin/docker-zipkin/builds/78704874 (even though the build failed for an unrelated reason):

```
Adding ssh known hosts (BETA)
$ ssh-keyscan -t rsa,dsa,ecdsa -H github.com 2>&1 | tee -a $HOME/.ssh/known_hosts
tee: /home/travis/.ssh/known_hosts: Permission denied
```

**Comment by BanzaiMan** [comment]
Sorry about the problem. The file has mode 400 for some reason, so you can't write to it. You should add `chmod u+w ~/.ssh/known_hosts` until we fix the image.

(I created an internal ticket to track this.)

Thanks.

**Comment by abesto** [comment]
Great, thanks!

**Comment by BanzaiMan** [comment]
I think this is fixed now. Please reopen it if isn't.
