### ISSUE TITLE
Missing list of compatible Xcode 7 devices

### ISSUE THREAD

**Issue by bogren** [travis-ci/travis-ci#4749]
The documentation and the blog post are both missing a list of compatible devices for Xcode 7.

**Comment by 0xced** [comment]
I’m running `xcrun simctl list` in the `before_install` phase to get the list of supported devices but I think that would be nice if it was always run just after the `xcodebuild -version -sdk` command in the `announce` phase.

**Comment by henrikhodne** [comment]
We added the list to our docs here: http://docs.travis-ci.com/user/languages/objective-c/#Xcode-7, but I agree that we should probably run `xcrun simctl list` (which is the command I use to get this information in the first place).
