### ISSUE TITLE
Tests fail on Travis CI.

### ISSUE THREAD

**Issue by bicycle1885** [travis-ci/travis-ci#4754]
@tkelman, @ninjin, @staticfloat,

Tests of my package (https://github.com/BioJulia/IndexableBitVectors.jl) fail on Travis CI but pass on my local machine.
This is the log of the failing tests: https://travis-ci.org/BioJulia/IndexableBitVectors.jl/jobs/78961975.

I've checked out the same Julia commit (`3da047c`) in my machine, then the tests passed successfully.

A suspicious warning message about metadata appeared just before the fail:

```
CompactBitVector
  > access
  > rank
    Error :: (line:-1) :: rank
      Expression: rank0(b,i) --> 0
WARNING: could not attach metadata for @simd loop.
      BoundsError: attempt to access 16-element Array{UInt8,1}:
       0x00
       0x40
```

I have no clue to figure out the reason. Could you help me?

**Comment by tkelman** [comment]
What does `versioninfo()` say on Julia running on your local machine? Travis VM's are Ubuntu 12.04, this could be any number of things.

**Comment by bicycle1885** [comment]
This is it:
```
julia> versioninfo()
Julia Version 0.4.0-pre+7327
Commit abdd074* (2015-09-06 03:54 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.4.0)
  CPU: Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

But the tests failed even on OS X of Travis: https://travis-ci.org/BioJulia/IndexableBitVectors.jl/jobs/78961977.

**Comment by tkelman** [comment]
That OS X job apparently ran on

>   System: Darwin (x86_64-apple-darwin13.4.0)
>  CPU: Intel(R) Xeon(R) CPU           X5570  @ 2.93GHz

So not sure what to say other than try to reproduce that environment if you can. Do your tests involve any randomness? I think you can contact Travis' support email address and request temporary ssh access to a build machine if you can't get this to happen locally.

**Comment by bicycle1885** [comment]
Yes, I use `bitrand()` to generate sample data and the random seed is fixed at the top of the tests.
But even if I tried several random seeds the tests always passed, so I thought randomness is not related to this problem.

Okay, I'll contact the support if I can't remove it for a while. Thank you!

**Comment by tkelman** [comment]
LLVM and a few other dependency libraries have code paths that can differ at runtime depending on the capabilities of the processor they run on. Is your local build compiled from source or have you tried using the same nightly binary that was used on Travis?
