### ISSUE TITLE
Multi-platform builds run deployment on each platform

### ISSUE THREAD

**Issue by jingweno** [travis-ci/travis-ci#4755]
I have [Linux and OSX builds](https://travis-ci.org/jingweno/jqplay/builds/78964276) enabled for [jqplay](https://github.com/jingweno/jqplay). I also have [Heroku build enabled](https://github.com/jingweno/jqplay/blob/master/.travis.yml#L13-L20). But both Linux and OSX builds deploy to Heroku. It'd be nice to be able to control it to deploy only once.

**Comment by BanzaiMan** [comment]
Please use conditional deployment so that only one job executes the deployment task. http://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

**Comment by jingweno** [comment]
@BanzaiMan Cool, is there an env variable I could check for Linux vs. OSX?

**Comment by BanzaiMan** [comment]
Sure thing! http://docs.travis-ci.com/user/multi-os/#TRAVIS_OS_NAME-environment-variable

I'm going to close this now. Thanks!
