### ISSUE TITLE
Upgrade PyPy to 2.6

### ISSUE THREAD

**Issue by oberstet** [travis-ci/travis-ci#4756]
Please upgrade PyPy to 2.6. [Cryptography 1.0](https://github.com/pyca/cryptography), a quite important Python package, doesn't run on PyPy 2.5:

```
Collecting cryptography>=0.7 (from pyOpenSSL>=0.11->treq>=15.0.0->crossbar==0.11.0)
  Downloading cryptography-1.0.1.tar.gz (332kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "app_main.py", line 75, in run_toplevel
      File "app_main.py", line 581, in run_it
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-n4Y3Eq/cryptography/setup.py", line 51, in <module>
        "cryptography 1.0 is not compatible with PyPy < 2.6. Please "
    RuntimeError: cryptography 1.0 is not compatible with PyPy < 2.6. Please upgrade PyPy to use this library.
```

**Comment by meejah** [comment]
FWIW, Debian Stable (jessie) ships PyPy 2.4.0 -- is there a stable cryptography release that does support < PyPy 2.6?

("stretch"/testing ships 2.6.0)

**Comment by oberstet** [comment]
* It seems, the lastest release before 1.0 was 0.9.3 https://pypi.python.org/pypi/cryptography/0.9.3
* The cryptography README does not talk about pypy versions supported.
* cryptography 1.0 was tagged 12.08.2015.
* As of Debian: You know my view on distro packaging;) We're shipping Crossbar.io binary packages our own, with all dependencies included, and are hence not affected by distro's shipping years old pypy. It's only Travis not doing pypy2.6 that affects our CI.

**Comment by oberstet** [comment]
@meejah  Looking at https://travis-ci.org/pyca/cryptography, they do test on PyPy. I am wondering why that works ..

There is

https://travis-ci.org/pyca/cryptography/jobs/78957749#L229

where does that come from? what does it do?

**Comment by oberstet** [comment]
ah: https://github.com/pyca/cryptography/blob/master/.travis/install.sh#L54

**Comment by meejah** [comment]
Yeah. It's sucky that crytography doesn't have a version that supports PyPy 2.4.x still as that makes it "harder" for Debian stable users. Also because PyPy doesn't have a Debian installer or build available, I don't believe? (Maybe the Ubuntu one "just works"?) I expect that jessie-backports will get the PyPy 2.6.x from stretch in the not-too-distant future...

FWIW, Cryptography 1.0.0 doesn't have the exception at install time (only 1.0.1 does), but I'm not sure if it actually works or not :/

**Comment by oberstet** [comment]
ubuntu 14.04 is at pypy 2.2 ! ;) well, I didn't know until now, because I never used distro pypy's. the binary the pypy project provides for ubuntu 14.04 just works. downloads. untar. done. who needs distro packages?

**Comment by glyph** [comment]
@oberstet There is a PPA for ubuntu.  Any chance that works? https://launchpad.net/~pypy/+archive/ubuntu/ppa

**Comment by oberstet** [comment]
@glyph Oh, neat! Wasn't aware of that. It provides a PyPy fresher certainly, but is still lagging behind .. PyPy is at 2.6.1, while the PPA provides 2.6.0.

FWIW, [here](http://crossbar.io/docs/Installation-on-Ubuntu/):

```console
oberstet@thinkpad-t430s:~$ sudo apt-get install crossbar
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  libclang-common-3.4-dev libclang1-3.4 libwxbase2.8-0 libwxgtk2.8-0
  linux-headers-3.13.0-32 linux-headers-3.13.0-32-generic
  linux-image-3.13.0-32-generic linux-image-extra-3.13.0-32-generic llvm-3.4
  llvm-3.4-dev llvm-3.4-runtime preview-latex-style texlive-latex-extra-doc
  texlive-pictures texlive-pictures-doc
Verwenden Sie »apt-get autoremove«, um sie zu entfernen.
Die folgenden Pakete werden aktualisiert (Upgrade):
  crossbar
1 aktualisiert, 0 neu installiert, 0 zu entfernen und 34 nicht aktualisiert.
Es müssen 44,4 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 5.830 kB Plattenplatz zusätzlich benutzt.
Holen: 1 http://package.crossbar.io/ubuntu/ trusty/main crossbar amd64 0.11 [44,4 MB]
Es wurden 44,4 MB in 52 s geholt (851 kB/s).                                   
(Lese Datenbank ... 651944 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../crossbar_0.11_amd64.deb ...
Entpacken von crossbar (0.11) über (0.10.4) ...
crossbar (0.11) wird eingerichtet ...
oberstet@thinkpad-t430s:~$ /opt/crossbar/bin/crossbar version
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 0.11.0
   Autobahn         : 0.10.7
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-python-0.4.6
   Twisted          : 15.4.0-EPollReactor
   Python           : 2.7.10/PyPy-2.6.1
 OS                 : Linux-3.13.0-63-generic-x86_64-with-debian-jessie-sid
 Machine            : x86_64

oberstet@thinkpad-t430s:~$ 
```

**Comment by kislyuk** [comment]
This is breaking the test suite for SignXML (https://travis-ci.org/kislyuk/signxml/jobs/80457504). Is there any guidance on the path forward here?

**Comment by mgeier** [comment]
+1

With the currently installed PyPy version, NumPyPy `master` is broken (`pypy-2.6.0` branch still works).
It would also be nice to have a more recent CFFI (>= 0.9), which ships together with PyPy.

**Comment by fijal** [comment]
This one can be superseded by "install pypy 4", superseded by https://github.com/travis-ci/travis-ci/issues/5027

**Comment by glyph** [comment]
Once again I am working late at night to deal with the fallout from the ancient pypy we're stuck with on travis :). https://github.com/rackerlabs/mimic/pull/475

**Comment by hugovk** [comment]
Can this be closed?

Right now, putting these in .travis.yml results in versions in the comments.

```yaml
python:
- 'pypy'        # Python 2.7.10 (7e8df3df9641, Jun 14 2016, 13:58:02)
                # [PyPy 5.3.1 with GCC 4.8.2]
- 'pypy3'       # Python 3.2.5 (b2091e973da6, Oct 19 2014, 18:29:55)
                # [PyPy 2.4.0 with GCC 4.6.3]
- 'pypy-5.3.1'  # Python 2.7.10 (7e8df3df9641, Jun 14 2016, 13:58:02)
                # [PyPy 5.3.1 with GCC 4.8.2]
- 'pypy-5.4'    # Python 2.7.10 (77392ad26350, Aug 28 2016, 06:54:48)
                # [PyPy 5.4.0 with GCC 4.8.2]
- 'pypy-5.4.1'  # Python 2.7.10 (c95650101a99, Sep 06 2016, 11:10:29)
                # [PyPy 5.4.1 with GCC 4.8.2]
```
