### ISSUE TITLE
Travis can not find my public repositories on GitHub

### ISSUE THREAD

**Issue by vadimtsushko** [travis-ci/travis-ci#4758]
That look same as in https://github.com/travis-ci/travis-ci/issues/2765

After signing with GitHub login, I got a message 'Sorry, it seems like we couldn't find any repositories you have access to on GitHub.'
My public repositories are at https://github.com/vadimtsushko/ and https://github.com/inqlik/
My new travis profile is at https://magnum.travis-ci.com/profile/vadimtsushko
I've tried sync repeatedly, did not get any error messages, got message 'last synced less than a minute ago'

**Comment by drogus** [comment]
@vadimtsushko sorry for confusion - we have 2 platforms, https://travis-ci.org for open source projects and https://travis-ci.com for closed source projects. You should go to `.org` version if you look for public projects.
