### ISSUE TITLE
Syncing from GitHub never completes

### ISSUE THREAD

**Issue by htmlguy** [travis-ci/travis-ci#4759]
I just signed up for Travis CI, and authorized access to an organization on GitHub. Since the organization didn't show up on travis, I clicked `Sync` to see if it would update the organization list.
Now, the button has been replaced with `Syncing from GitHub` and a loading icon for quite some time.

I have tried reloading, changing pages, even signing out and signing back in. Nothing seems to work.
#740 didn't present any obvious solution to me.

**Screenshot**:
![travissyncstuck](https://cloud.githubusercontent.com/assets/1672106/9718452/cead7ee8-5549-11e5-89c3-419b799fac9f.png)

This problem *still persists* after revoking access, signing out, and signing back in to travis, re-admitting access.

**Still persists over 2 hours:**  Some help would be nice. Anybody know what's going on, or how to fix it?

**Comment by htmlguy** [comment]
This problem *still persists* after revoking access, signing out, and signing back in to travis, re-admitting access.

**Comment by htmlguy** [comment]
Still persisting after over half an hour.

**Comment by BanzaiMan** [comment]
Not clear what's happened before, but this should be resolved at this time. Could you confirm?

**Comment by htmlguy** [comment]
Yes, it appears to work, reporting "Last synced about 10 hours ago" - Everything appears to have been synced correctly.
