### ISSUE TITLE
Travis CI build no longer running: grails/grails3-functional-tests

### ISSUE THREAD

**Issue by graemerocher** [travis-ci/travis-ci#4760]
Hi,

The following build no longer seems to run https://travis-ci.org/grails/grails3-functional-tests/builds

I cannot restart any of the builds via the UI and we have another build here https://travis-ci.org/grails/grails-core/builds/79128128

That triggers this build via an API request and these triggers are no longer working. Has something changed?

**Comment by rkh** [comment]
Not entirely sure what happened, I restarted our background workers. Can you confirm this works now?
