### ISSUE TITLE
It seems like job/build restarts no longer work

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#4761]
As of approximately 2015-09-07_14-00-00 UTC there seems to be a problem restarting a failed build and/or job. Clicking the appropriate button seems to work, and the `The job was successfully restarted.` banner shows up, but nothing actually happens. One of the jobs I was attempting to restart: https://travis-ci.org/dbsrgits/dbix-class/jobs/79144055

**Comment by rkh** [comment]
Not entirely sure what happened, I restarted our background workers. Can you confirm this works now?

**Comment by ribasushi** [comment]
Yep, restarts seem to work now. Thank you!

**Comment by mschilli87** [comment]
I seem to have the same issue with https://travis-ci.org/BIMSBbioinfo/ciRcus/jobs/215397165.

The log didn't move past `$ export DEBIAN_FRONTEND=noninteractive` for several minutes so I cancelled the job (successfully) to re-start it again (no success so far).
