### ISSUE TITLE
Android M won't start on travis-ci

### ISSUE THREAD

**Issue by xfumihiro** [travis-ci/travis-ci#4763]
Somehow the android-23 emulator won't start on Travis. I've tried extending the Timeout on
the wait script but still no luck.

**Comment by timrae** [comment]
[Same issue here](https://travis-ci.org/ankidroid/Anki-Android/builds/79333139)

**Comment by BanzaiMan** [comment]
I have seen a few reports of this kind. https://travis-ci.org/ankidroid/Anki-Android/builds/79333139#L1220

Does anyone know what this means, and how to get around it?

```
Failed to Initialize backend EGL display
emulator: WARNING: Could not initialize OpenglES emulation, using software renderer.
```

**Comment by JakeWharton** [comment]
That just means it cannot use hardware GPU acceleration.

**Comment by timrae** [comment]
any ETA on this?

**Comment by SandroMachado** [comment]
+1

**Comment by justinhouse** [comment]
Same here. Reverting to 22 does start the emulator, but it's simply not what our project needs.

**Comment by ardock** [comment]
M emulator fails due this issue, star it:
https://code.google.com/p/android/issues/detail?id=189764
http://stackoverflow.com/questions/32952413

x86 emulators are faster than arm, try to offer this possibility please.
http://stackoverflow.com/questions/30355039/error-launching-android-x86-emulator-in-travis-ci

[Configuring Graphics Acceleration](http://developer.android.com/intl/es/tools/devices/emulator.html#acceleration)

> x86 AVD Only - You must use an AVD that is uses an x86 system image target. AVDs that use ARM-based system images cannot be accelerated using the emulator configurations described here.

> Not Inside a VM - You cannot run a VM-accelerated emulator inside another virtual machine, such as a VirtualBox or VMWare-hosted virtual machine. You must run the emulator directly on your system hardware.

I don't know if this is still valid and the documentation updated.

**Comment by spyhunter99** [comment]
Any progress on API 22 and up on travis?

**Comment by albodelu** [comment]
Samples working on API 22 and up:
https://travis-ci.org/albodelu/constraint-layout/builds/220841505
https://travis-ci.org/albodelu/android-maps-utils/builds/220859379
https://travis-ci.org/albodelu/Dexter/builds/220847349
