### ISSUE TITLE
travis-web: JS error on job restart

### ISSUE THREAD

**Issue by nikolas** [travis-ci/travis-ci#4764]
I'm getting this JavaScript error when trying to restart this job: https://travis-ci.org/ccnmtl/worth2/builds/79326922

> Uncaught TypeError: Cannot read property 'loadFlashes' of undefined(anonymous function)
> @ travis-9b8ccc0f08056637cfa5252d54a740dc.js:21E.onreadystatechange
> @ travis-9b8ccc0f08056637cfa5252d54a740dc.js:21

I'm using Chromium 47.0.2498.0 on Ubuntu.

**Comment by vladikoff** [comment]
Same, cannot cancel the job 
![image](https://cloud.githubusercontent.com/assets/128755/9743589/308a0e56-5635-11e5-9585-511796ac7034.png)

```
navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
```

**Comment by vladikoff** [comment]
Same issue in Firefox Dev Edition

**Comment by drogus** [comment]
Sorry for the issues and thanks for reporting. I pushed and deployed a fix.
