### ISSUE TITLE
Build status unknown persists

### ISSUE THREAD

**Issue by victorwestmann** [travis-ci/travis-ci#4775]
Sorry to bother but in our project we're affected by the "build status: unknown" issue: https://github.com/coursera-dl/coursera-dl 

Here it shows everything fine https://travis-ci.org/coursera-dl/coursera-dl but in our readme it doesn't.
I believe someone renamed the project name.

**Comment by BanzaiMan** [comment]
The badge in https://raw.githubusercontent.com/coursera-dl/coursera-dl/14e866ae1612117f9e230ce93246d0039981a76b/README.md points to https://travis-ci.org/coursera-dl/coursera.png?branch=master. https://travis-ci.org/coursera-dl/coursera/builds has no builds, so this "error" seems to be the correct one. You should use https://api.travis-ci.org/coursera-dl/coursera-dl.png?branch=master instead.

**Comment by victorwestmann** [comment]
I already sent a pull request to the project owner with the fix. Thanks for the quick answer.

**Comment by victorwestmann** [comment]
Just one quick question: when I copy the code from https://travis-ci.org/coursera-dl/coursera-dl which is [![Build Status](https://travis-ci.org/coursera-dl/coursera-dl.svg?branch=master)](https://travis-ci.org/coursera-dl/coursera-dl) and I put it in http://markdownlivepreview.com/ it shows: Build status unknown. Am I doing something wrong here?

**Comment by BanzaiMan** [comment]
@victorwestmann Sorry, I don't know how http://markdownlivepreview.com/ is supposed to work.The markup should be correct.

**Comment by victorwestmann** [comment]
It is working flawless now after they've accepted the pull request. Thanks! :+1:

**Comment by rbrito** [comment]
@victorwestmann and @BanzaiMan, it seems that the issue is fixed on our side now. Funny that it worked for a long time (even after the rename) before it started showing up the error (some redirection might have been taking place). Anyway, everything is fine now. :)
