### ISSUE TITLE
csharp builds fail with 404 error

### ISSUE THREAD

**Issue by pboyer** [travis-ci/travis-ci#4779]
Our C# builds are failing on Travis CI with 404 errors. Here's an example:

https://travis-ci.org/DynamoDS/Dynamo/builds/79878921

@joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
Xamarin just rolled out Mono 4.0.4 and the CDNs haven't catched up yet (I talked with the release engineer and they went over quota on invalidations on CloudFront). Please try again later.

**Comment by pboyer** [comment]
Thanks @akoeplinger - I'll keep an eye on this. Would you like to keep this open? It sounds like it's a just a matter of waiting...

**Comment by akoeplinger** [comment]
Yeah, keep the issue open until it is fixed :)

**Comment by akoeplinger** [comment]
The CDNs have now been invalidated and a test build worked on my account, so this should be fixed. Please try and close if it works on your end as well. Thanks for the report ;)

**Comment by pboyer** [comment]
Yup! Working! Thanks for extremely quick turnaround @akoeplinger!
