### ISSUE TITLE
[c#] Cannot install libunwind8 

### ISSUE THREAD

**Issue by natemcmaster** [travis-ci/travis-ci#4780]
Our build started failing without any change in the setup (see [this successful build](https://travis-ci.org/aspnet/Microsoft.Data.Sqlite/builds/79718784) vs [this failed one](https://travis-ci.org/aspnet/Microsoft.Data.Sqlite/builds/79766398). They are the same project setup and code.)

The error: libunwind8 is missing.

I've attempted to add this to build machine, but I cannot installed it. 

libunwind8 is listed in the apt-package-whitelist repo, but it cannot be found.

> Installing APT Packages (BETA)
$ export DEBIAN_FRONTEND=noninteractive
$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libunwind8
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libunwind8

```yml
# in .travis.yml
addons:
  apt:
    packages:
    - libunwind8
```

/cc: @joshua-anderson @akoeplinger @nterry

**Comment by BanzaiMan** [comment]
I'm not sure why the build started failing. However, looking at https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/73679044#L342, I see that you need to add "debian-sid" as the APT source in order to find libunwind8.

**Comment by natemcmaster** [comment]
@BanzaiMan thanks.

**Comment by akoeplinger** [comment]
@natemcmaster please note that there's also a problem installing Mono right now: https://github.com/travis-ci/travis-ci/issues/4779#issuecomment-139604470
