### ISSUE TITLE
Failure on python 3.5 builds

### ISSUE THREAD

**Issue by sloria** [travis-ci/travis-ci#4788]
Now that Python 3.5 final is released, I tried to add `3.5` to my build matrix. However, the build fails with the following message:

```
The command "source ~/virtualenv/python3.5/bin/activate" failed and exited with 1 during .
```

`3.5-dev`, however, is working as expected.

**Comment by BanzaiMan** [comment]
Could you point to a build log URL that shows this problem? I've built the 3.5.0 archive a couple of hours ago, and it should be available now.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/80108941#L93

**Comment by BanzaiMan** [comment]
Please use `'3.5.0'`, not `'3.5'`.

**Comment by sloria** [comment]
Thanks @BanzaiMan . `3.5.0` works as expected.

**Comment by jaitaiwan** [comment]
Is there a reason that the naming scheme has changed from 3.5 to 3.5.0?

**Comment by joshk** [comment]
Thanks for raising the issue @jaitaiwan 

We will look into adding an alias for 3.5.

cc. @BanzaiMan

**Comment by BanzaiMan** [comment]
Hello there. I've revised the Python on-demand installation workflow so that `3.5` is also recognized.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/80230880#L93
