### ISSUE TITLE
Takes a while before closing Sauce Connect

### ISSUE THREAD

**Issue by silvenon** [travis-ci/travis-ci#4789]
When tests finish, Travis CI takes a minute before starting to close Sauce Connect. [Here](https://travis-ci.org/silvenon/jszg-selenium/builds/80115332)'s an example. Is there something I'm doing wrong?

**Comment by BanzaiMan** [comment]
As far as I can tell, this is how long it takes SC to shut down. https://github.com/travis-ci/travis-build/blob/f024330aeab0a7ac267269c96a7f82cb65e5e605/lib/travis/build/addons/sauce_connect/templates/sauce_connect.sh#L70-L92

How long does it take when you do this locally?

**Comment by silvenon** [comment]
Ok, I must have misunderstood the log then. Thanks :+1:
