### ISSUE TITLE
Python 3.5 Support

### ISSUE THREAD

**Issue by jaitaiwan** [travis-ci/travis-ci#4790]
Hi Guys,

Just tried adding py3.5 to the travis builds and I'm getting `/home/travis/build.sh: line 41: /home/travis/virtualenv/python3.5/bin/activate: No such file or directory` so I'm assuming py3.5 isn't yet happening.

Be great to see this added asap :)

**Comment by bjacobel** [comment]
+1

**Comment by BanzaiMan** [comment]
This is a duplicate of #4788.

**Comment by jaitaiwan** [comment]
This issue occurred 4 hours ago and the solution was said to be done some 11 hours ago... So I'd say this isn't a duplicate.
