### ISSUE TITLE
Best ways to do dependencies for multi-os configuration

### ISSUE THREAD

**Issue by vielmetti** [travis-ci/travis-ci#4792]
I'm trying to sort out how to best handle dependencies where I need to install both Linux packages from apt-get (and particular repositories) and the equivalent Mac packages through homebrew for separate setups.

The docs mention multi-os support and brew (which is good) but are thin on suggestions for how to manage parallel build environments. 

So far I have looked at

http://docs.travis-ci.com/user/osx-ci-environment/
http://docs.travis-ci.com/user/multi-os/
http://docs.travis-ci.com/user/installing-dependencies/
http://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

I'm in a state where I can either get `osx` or `linux` each to build, but not both at once. Pointers to working versions would be helpful...let's see, I find this

https://github.com/mono/CppSharp/blob/master/.travis.yml

which seems straightforward.

**Comment by BanzaiMan** [comment]
Hello. I am not quite sure what your question is. What do you want to achieve, what have you tried, and how did it fail to meet your expectations?

The example that you pointed to is a good one.

**Comment by vielmetti** [comment]
Yup, that was a good example. I want to achieve setting up builds for linux (with apt-get dependencies) and osx (with brew dependencies). I tried doing something with `matrix:` but it didn't behave as expected and seemed too complicated. The `mono/CppSharp` was what I needed as a sample to get things to work. Thanks @BanzaiMan for your help. (Closing.)
