### ISSUE TITLE
Tox builds for Python 3.5 fail

### ISSUE THREAD

**Issue by ulope** [travis-ci/travis-ci#4794]
Matrix builds with tox fail for the "py35" facet.

```
language: python
sudo: false
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
install:
  - pip install tox
script: tox
```

Output:

```
export TOXENV=py35
```
...
```
ERROR: InterpreterNotFound: python3.5
___________________________________ summary ____________________________________
ERROR:   py35: InterpreterNotFound: python3.5
```

**Comment by BanzaiMan** [comment]
Currently, 3.5 is available only when it is specified in `python`.

Until the build image is updated to have 3.5 pre-installed, you will have to devise your own plan of action to create the virtualenv you need.

See https://github.com/travis-ci/travis-build/blob/c858502ddce77cc90f88c8871f1fff3982d1f8a6/lib/travis/build/script/python.rb#L88-L92 for hints.

**Comment by ulope** [comment]
Do you have an ETA when the new build image will be available?

**Comment by BanzaiMan** [comment]
Sorry, we do not have one at the moment.

**Comment by maiksensi** [comment]
Is there any news on this? Or is it worth to integrate the workaround?

**Comment by thenewguy** [comment]
Is this something that is going to happen? soon-ish, eventually, never? Trying to decide if I should just wait or go ahead and manually create the environment as mentioned above.  Thanks

**Comment by BanzaiMan** [comment]
I think this is a `$PATH` issue, if I understand it correctly. I'll work on a fix next week.

**Comment by maiksensi** [comment]
:+1:

**Comment by sjakobi** [comment]
Python3.5 is available from the deadsnakes repo. Add the following to your .travis.yml:

```
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
```

**Comment by BanzaiMan** [comment]
As mentioned in https://github.com/travis-ci/travis-build/pull/521, in order to use 3.5 with `tox`, Python 3.5 still needs to be installed.

You can use deadsnakes as @sjakobi mentioned above, or specify

```yaml
python:
  - 3.5
```

This, as well as using the APT addon, will install Python 3.5 in all of the jobs.

One can also use a little matrix trick:

```yaml
matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35
```

(Similar trick should work for the APT addon.)

**Comment by Suor** [comment]
Any progress on this?

**Comment by kalefranz** [comment]
+1

**Comment by mar10** [comment]
This solution worked for me: 
https://pypi.python.org/pypi/tox-travis

**Comment by lwm** [comment]
COMMITS!
