### ISSUE TITLE
APT whitelist request for  libstartup-notification0-dev

### ISSUE THREAD

**Issue by DaveDavenport** [travis-ci/travis-ci#4795]
Required for compiling  [rofi](https://github.com/DaveDavenport/rofi/).

Thanks!

**Comment by BanzaiMan** [comment]
Please follow the instructions in https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

**Comment by DaveDavenport** [comment]
So sorry. I will add it to the right repo.
