### ISSUE TITLE
Please bump Gradle to 2.7

### ISSUE THREAD

**Issue by Flowdalic** [travis-ci/travis-ci#4796]
Gradle 2.7 has been released. Please bump Gradle to 2.7 or provide an easy way to select it.

Projects using the gradle-errorprone plugin require at least Gradle 2.6 to run, or otherwise they fail with https://travis-ci.org/igniterealtime/Smack/jobs/80306827

**Comment by johnscancella** [comment]
The latest version is 2.13. I am trying to build my open source plugin and it fails because of the old version of gradle (2.2.1)
