### ISSUE TITLE
[private] Build from created to started is too slow

### ISSUE THREAD

**Issue by moylop260** [travis-ci/travis-ci#4797]
We have created a new commit for a old PR.
Next build is created: https://magnum.travis-ci.com/Vauxoo/deployv/builds/15533123
But to change the state from `build created` to `build started` is too slow (1 hour aprox).
Note: There isn't queued processes.

**Comment by BanzaiMan** [comment]
Sorry for the problem. Are you still having issues?

**Comment by moylop260** [comment]
I will follow it here:
https://www.traviscistatus.com/incidents/61mbs36zrqcr
Thank you!
