### ISSUE TITLE
Script deploy not updating

### ISSUE THREAD

**Issue by LucioFranco** [travis-ci/travis-ci#4798]
So I have been using script deploy to deploy to my servers. The script that is run on the remote server via ssh does not seem to update. I have a shell script that then runs a bash script via ssh on the remote server. When I update the build script it does not seem to update. When I check what file change from the commit link on travis it is correct but the travis console output runs the old commands and it does even print something when I add a echo to the build script.

**Comment by BanzaiMan** [comment]
Could you point to the build log URL and to the corresponding `.travis.yml`? Thanks.

**Comment by LucioFranco** [comment]
Its on magnum and I would not like to make some things public.

```
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
```
here is my deploy section of the .travis.yml.

**Comment by BanzaiMan** [comment]
Please email support@travis-ci.com. It is very hard to diagnose the problem with this piece of information.

**Comment by LucioFranco** [comment]
Sorry this was my fault. Thank you for the quick resposnes!!! @BanzaiMan
