### ISSUE TITLE
Xcode 7.1

### ISSUE THREAD

**Issue by mattyohe** [travis-ci/travis-ci#4799]
I was super impressed with the speed at which you were able to release the GM of Xcode7.

Are there any hurdles to get 7.1 spun up other than time?

**Comment by BanzaiMan** [comment]
We are working to get 7.1 beta support out the door as soon as we can. Thanks.

**Comment by kcharwood** [comment]
Any update to this?

**Comment by mattyohe** [comment]
Just a data point here: Apple is on record today as releasing the Apple TV next week. It follows that we'll see a 7.1 GM very shortly.

**Comment by mattyohe** [comment]
7.1 coming today: https://developer.apple.com/xcode/download/

**Comment by emdantrim** [comment]
Aaaand you can use it now! `osx_image: xcode7.1`. :)

**Comment by mattyohe** [comment]
Same day releases are amazing. Thank you.

**Comment by emdantrim** [comment]
:sparkling_heart: :blush:

**Comment by Legoless** [comment]
Good work guys!

**Comment by solarce** [comment]
While we worked to get the images dark launched a couple days ago, we've officially announced the support and pushed updates to the documentation. http://blog.travis-ci.com/2015-10-23-xcode-71-701-are-ready/
