### ISSUE TITLE
Mono 4.0 does not install anymore

### ISSUE THREAD

**Issue by Mailaender** [travis-ci/travis-ci#4803]
Currently all Mono builds are failing for https://github.com/OpenRA/OpenRA/pulls since yesterday.

```
GPG error: http://download.mono-project.com wheezy/snapshots/4.0.0 Release: The following signatures were invalid: BADSIG A6A19B38D3D831EF Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>
```

> E: There are problems and -y was used without --force-yes

...

> The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .

cc @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
I've been getting some reports about this last night, but I can't reproduce it right now. Can you please try again and see if it still happens?

**Comment by Mailaender** [comment]
There were also other errors:

> Failed to fetch http://download.mono-project.com/repo/debian/dists/wheezy/snapshots/4.0.0/main/binary-amd64/Packages  Hash Sum mismatch

but indeed this resolved itself now. We just had a 12-24 h downtime.
