### ISSUE TITLE
travis push build on fork of a private repo

### ISSUE THREAD

**Issue by aswinhope** [travis-ci/travis-ci#4804]
Hi all,
How do I enable a travis push build of a fork aswin/sampleRepo of the private repo org/sampleRepo? The organization org uses a startup travis plan and aswin is an owner member of org

Thank you

[EDIT] Note that I dont have any issues running a PR build, I need to run a push build on a fork

**Comment by MariadeAnton** [comment]
Hi @aswinhope, thanks for reaching out - please check your inbox, we've answered your support email :)

**Comment by aswinhope** [comment]
Hi Maria,
I havent received it for some reason. Could you resend it? aswinthomas@hopetechnik.com

Thank you

**Comment by MariadeAnton** [comment]
Hi Aswin,

I jus re-sent it just now. My apologies for the hassle.

Could you confirm you got it?

**Comment by aswinhope** [comment]
Got it. Thank you.

**Comment by MariadeAnton** [comment]
Thank you!

**Comment by pachonk** [comment]
Hi,
What was the result of this? Can I run forks on the org's plan?

**Comment by ElliotNB** [comment]
@aswinhope  @MariadeAnton Also would like to know the outcome of this, thanks!

**Comment by aswinhope** [comment]
As far as I know, builds are enabled only for the organization that has subscription activated. So this is restricted to PR build and push builds to that particular organization.

Since PR builds are supported, it works fine for me.

**Comment by ElliotNB** [comment]
@aswinhope Thanks for the clarification! I was hoping it would be possible for the members of a private org to 'piggy back' on to the paid Travis CI account for commits on their private forks, but I suppose we'll have to make do with running Travis CI on pull requests only.

**Comment by pachonk** [comment]
Yeah, the forked model is a really common model and it sucks to not be able to "piggy back" considering it's the org's repo/code.
That said, what my team has started doing is pushing the forked branch and immediately making a "WIP" Pr so travis runs...
It's a hack, so if CircleCI supports forked privates we're switching to them in a heart beat.
