### ISSUE TITLE
Last travis update broke my build script

### ISSUE THREAD

**Issue by Darelbi** [travis-ci/travis-ci#4805]
my simple original broken script (it was working, then travis updated and it suddendly stopped working):
https://github.com/Darelbi/Infectorpp2/blob/051fcce53438dd9f499c58acefd9a46e3bdebaa4/.travis.yml

My current attemp to fix the script by commeting the errored line(I assumed it had GCC .4.8 installed already:)
https://github.com/Darelbi/Infectorpp2/blob/master/.travis.yml

any clue on how to fix that?

**Comment by BanzaiMan** [comment]
Could you elaborate on what is broken? Did any of your repositories pull the package you need?

**Comment by Darelbi** [comment]
After a travis update this is the incrimanted build fail:
https://travis-ci.org/Darelbi/Infectorpp2/jobs/77049008

ERROR:
    The command "if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi" failed and exited with 100 during

As you see the build is failing at SHELL level.

Build was successfull at build # 66
Build fail at build # 67

however I did not changed any code or build script (the only change was  a change in code's comments, and anyway I can happily run the build on my local machines (Debian and Win Vista), it is just travis that started to give problems.

No clue on how to fix?

**Comment by BanzaiMan** [comment]
Where was `g++-4.8` pulled from? Is it still there?

**Comment by Darelbi** [comment]
As previously linked the
ORIGINAL WORKING SCRIPT IS:
https://github.com/Darelbi/Infectorpp2/blob/051fcce53438dd9f499c58acefd9a46e3bdebaa4/.travis.yml

I spent few days assembling that script, it was working really great, until travis updated VMs, now the script no longer work. I really have no idea what the script was doing, the documentation of Travis is so unclear my only chance was copy-pasting pieces of scripts of other users, that's why I'm disappointed it stopped working, I'm no longer able to get a new script working ^^.

**Comment by Darelbi** [comment]
Everything I know is that the script was working, I don't know why now it no longer works anymore.

**Comment by Darelbi** [comment]
What's the status of the issue?

A) We are aware of the issue and other scripts were broken after our update but we wil not fix that as it is impossible for us.
B) We don't think that's an issue (support appreciated ^^ )
C) We are fixing already the issue and maybe will be implemented within 1 or 2 releases
D) A fix is scheduled for a second moment, we have more important things




Still any chance someone [fix the  / help me] or should I close it and pass on?

**Comment by Darelbi** [comment]
I did a serious trip and tried somewhat like 10 CI different services, I think travis can be better, but it is actually the simpler to use. The issue is fixed for me now ( I redid from scratch my build scripts).

**Comment by joshk** [comment]
Hi @Darelbi 

I'm sorry for our late reply.

Did you find out what was the root cause of the build script failing to work? I would be interested it passing on the issue to our dev teams so we can make sure we don't break scripts like yours again.

Thanks a bundle

Josh

**Comment by Darelbi** [comment]
the failing point is there:

      https://travis-ci.org/Darelbi/Infectorpp2/jobs/77049008

$ if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
E: Unable to locate package g++-4.8
E: Couldn't find any package by regex 'g++-4.8'


My guess is that something inside the configuration of VM is changed. I can't help more than that

**Comment by joshk** [comment]
Is it possible that the package was no longer available from the apt source? Thus it might not be a Travis issue, but an upstream provider issue.
