### ISSUE TITLE
Add carthage for Xcode 7 build boxes

### ISSUE THREAD

**Issue by schwa** [travis-ci/travis-ci#4812]
carthage (http://github.com/carthage/carthage) is a OS X dependency manager that can be used instead of the (more popular) Cocapods tool.

Unfortunately Carthage requires Xcode 6.4 to build (because it relies on Swift 1.2)

This means that travis Xcode 7 build instances cannot easily install carthage manually via .travis.yaml file. 

Having carthage preinstalled on these instances would be great.

**Comment by natestedman** [comment]
I'm using:

    curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.9.3/Carthage.pkg"
    sudo installer -pkg "Carthage.pkg" -target /
    rm "Carthage.pkg"

to install Carthage directly, instead of building it from source.

**Comment by ephread** [comment]
:+1:

It would be so nice to see Carthage treated as a first-class citizen on Travis, the way CocoaPods is. :)

Thanks for the tip @natestedman, I hadn't considered using the prebuilt pkg to install Carthage on the Travis environment.

**Comment by Danappelxx** [comment]
:+1:

**Comment by schwa** [comment]
Installing carthage directly seems to be the best way. Also carthage is now supported in Xcode 7
