### ISSUE TITLE
Dlang: DUB version with annoying bug

### ISSUE THREAD

**Issue by denizzzka** [travis-ci/travis-ci#4813]
```
$ dub test
Error executing command test:
no package file was found, expected one of the following: [immutable(FilenameAndFormat)("dub.json", json), immutable(FilenameAndFormat)("package.json", json)]
The command "dub test" exited with 2.
```
https://travis-ci.org/DSoftOut/pgator/builds/80716590

@ibuclaw @klickverbot @MartinNowak

**Comment by denizzzka** [comment]
DUB 0.9.24 is released

http://forum.dlang.org/post/mtn1rd$2fa5$1@digitalmars.com

**Comment by MartinNowak** [comment]
Could you simply try to rerun the test. Might be a temporary error while trying to fetch the dub.json for one of your dependencies.

**Comment by denizzzka** [comment]
You were right!
