### ISSUE TITLE
PHP 7.0 actually gives 7.1

### ISSUE THREAD

**Issue by GrahamCampbell** [travis-ci/travis-ci#4814]

**Comment by BanzaiMan** [comment]
See https://github.com/php-build/php-build/pull/308

**Comment by BanzaiMan** [comment]
Also https://github.com/travis-ci/travis-ci/issues/4800#issuecomment-140245025

**Comment by BanzaiMan** [comment]
`7` and `7.0` now points to `7.0snapshot` builds, while `nightly` points to the `master` branch of php-src, which yields `7.1.0-dev`.

**Comment by Spomky** [comment]
Hi,

It seems to be broken again: https://travis-ci.org/Spomky-Labs/jose/jobs/95296259

> php --version
PHP 7.0.1-dev (cli) (built: Dec  6 2015 22:41:42) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC3-dev, Copyright (c) 2002-2015, by Derick Rethans

**Comment by GrahamCampbell** [comment]
No it's not? 7.0.1-dev IS 7.0?

**Comment by GrahamCampbell** [comment]
Oh, I see what you mean...

**Comment by Spomky** [comment]
Sorry I was not clear enough. I am expecting to build tests on the last stable PHP 7.0 release, but I have `PHP 7.0.1-dev`.

**Comment by GrahamCampbell** [comment]
I think that is the expected behaviour until travis decide to change it. 7.0 has given the 7.0-dev release for a good few months now, maybe even upto a year (I've lost track).

**Comment by BanzaiMan** [comment]
Please see https://github.com/travis-ci/travis-ci/issues/5207 for the update on 7.0.0 release. This issue is closed.
