### ISSUE TITLE
Defining Environment Variables in .travis.yml is not working for public repos

### ISSUE THREAD

**Issue by vcernomschi** [travis-ci/travis-ci#4815]
Defining Environment Variables in .travis.yml is not working for public repos

Step to reproduce:
1. Defining global env variable (JSPM_GITHUB_AUTH_TOKEN) in .travis.yml by using the following gist (https://gist.github.com/topheman/25241e48a1b4f91ec6d4).

Expected result: Global env var JSPM_GITHUB_AUTH_TOKEN was created successfully.
   
Actual result: JSPM_GITHUB_AUTH_TOKEN was n't created, getting the error below: GitHub rate limit reached. To increase the limit use GitHub authentication.
     Run jspm endpoint config github to set this up.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows this problem?

**Comment by vcernomschi** [comment]
Yep. Here you can see full log: https://api.travis-ci.org/jobs/80826623/log.txt?deansi=true   

Notes:
When I am defining env vars for our private repos it works fine and shows in log lines below (): 
Setting environment variables from repository settings
$ export CODACY_PROJECT_TOKEN=[secure]
Setting environment variables from .travis.yml
$ export JSPM_GITHUB_AUTH_TOKEN=[secure]
$ export COVERALLS_SERVICE_NAME=[secure]
$ export COVERALLS_REPO_TOKEN=[secure]

In case of public repo it doesn't log <export> from .travis.yml. It only shows <export> for env vars added by repository settings and then fails with the mentioned error: 
Setting environment variables from repository settings
$ export CODACY_PROJECT_TOKEN=[secure]

**Comment by BanzaiMan** [comment]
How did you encrypt these values? https://github.com/MitocGroup/deep-microservices-root-angularjs/blob/c304ee28b71db8faf498a59d9ffd6354c8db78cf/.travis.yml#L18-L27

Each repository has its own encryption key, so the secrets cannot be shared among repositories. Please try encrypting again with:

   travis encrypt -r MitocGroup/deep-microservices-root-angularjs 'JSPM_GITHUB_AUTH_TOKEN=SUPER_SECRET'

**Comment by vcernomschi** [comment]
After encrypting from root folder 'travis encrypt -r MitocGroup/deep-microservices-root-angularjs 'JSPM_GITHUB_AUTH_TOKEN=SUPER_SECRET'' I am getting error below: 
repository not known to https://api.travis-ci.com/: MitocGroup/deep-microservices-root-angularjs

**Comment by BanzaiMan** [comment]
You are logged in to .com instead of .org. Try:

    travis encrypt --org -r MitocGroup/deep-microservices-root-angularjs 'JSPM_GITHUB_AUTH_TOKEN=SUPER_SECRET'

**Comment by jakirkham** [comment]
I am seeing this with environment variable that I entered into the build settings.

**Comment by jakirkham** [comment]
I am seeing this with environment variable that I entered into the build settings. This has been an issue since the API attacks on Sept. 15.

**Comment by jakirkham** [comment]
Opened this issue ( https://github.com/travis-ci/travis-ci/issues/4885 ), as it seems to be different from the issue raised here.

**Comment by BanzaiMan** [comment]
Can this be closed?
