### ISSUE TITLE
libgfortran.so.1 is missing

### ISSUE THREAD

**Issue by FlorianWilhelm** [travis-ci/travis-ci#4816]
Starting a few days ago, I get 
> ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory

when installing things like Pandas although libgfortran3 and gfortran is installed. Is there anything messed up right now with ldconfig maybe?

**Comment by BanzaiMan** [comment]
Please provide a build log URL that shows this problem. Thanks.

**Comment by FlorianWilhelm** [comment]
@BanzaiMan sorry, that I forgot: https://travis-ci.org/blue-yonder/pyscaffold/jobs/80824874

**Comment by FlorianWilhelm** [comment]
I got 
>addons:
  apt:
    packages:
      - git
      - python-pip
      - gfortran
      - libgfortran3

**Comment by rizar** [comment]
We also suffer from the same problem: https://travis-ci.org/mila-udem/blocks/jobs/80824056

**Comment by alperyeg** [comment]
We have the same problem: https://travis-ci.org/NeuralEnsemble/elephant/jobs/81465671

**Comment by BanzaiMan** [comment]
What package is supposed to provide this file? http://packages.ubuntu.com/search?suite=precise&section=all&arch=any&keywords=libgfortran.so.1&searchon=contents doesn't return any result.

**Comment by FlorianWilhelm** [comment]
@BanzaiMan Removing the .1 reveals some results:
http://packages.ubuntu.com/search?suite=precise&section=all&arch=any&keywords=libgfortran.so&searchon=contents
It seems `gfortran` includes it. For building libraries that actually use this library I always also include `libgfortran3` due most often also some header files are needed. Since Trusty, `libgfortran.so` resides in `libgfortran-4.7-dev` and everything is a little bit more logical in the partitioning.
I actually wonder why it worked before so flawless and all of a sudden it stopped.

**Comment by FlorianWilhelm** [comment]
Hm.. actually it seems that what @bartvm said in https://travis-ci.org/NeuralEnsemble/elephant/jobs/81465671 seems to solve it. So everything was caused by a change in a conda package that we are using. Still it is strange that an important library like `libgfortran.so` is missing and no one knows how to get in on Ubuntu Precise. This is why I would rather keep this issue open until the library is directly provided.

**Comment by alperyeg** [comment]
@FlorianWilhelm what did you do to solve the problem?

**Comment by FlorianWilhelm** [comment]
@alperyeg I assume you use `conda` as I do for setting up your virtual environment. So all I had to do was 
> conda install --yes numpy=1.9.1 scipy=0.16

Before the version of scipy was pinned to a much older version. They must have changed the conda package of this version, at least that would be an explanation of the observed behavior.

**Comment by alperyeg** [comment]
@FlorianWilhelm thanks! After changing to the newest package versions of numpy, scipy and pandas it works now with the conda build.

**Comment by jakirkham** [comment]
There should be no need for an external `libgfortran` library when using `conda`. Make sure in your build logs that you are seeing a `libgfortran` package being installed in your `conda` logs when installing `numpy` and/or `scipy`. This is required for using `openblas`, which is now used by `numpy` and `scipy` as the default BLAS.

**Comment by jakirkham** [comment]
There should be no need for an external `libgfortran` library when using `conda`. Make sure in your build logs that you are seeing a `libgfortran` package being installed in your `conda` logs when installing `numpy` and/or `scipy`. This is required for using `openblas`, which is now used by `numpy` and `scipy` as the default BLAS. Also, `scipy` has some Fortran code and could be linked against `libgfortran`.

After taking a closer look, I realize that you are using MKL. Perhaps, `scipy` linkage is the cause of this problem. You can install it with conda like so `conda install libgfortran`.

@ilanschnell, raising this to your attention.

**Comment by harrymvr** [comment]
@jakirkham  Thanks a lot! The `conda install libgfortran` saved the day :+1:

**Comment by BanzaiMan** [comment]
Great! Sounds like this can be closed. Could anyone confirm?

**Comment by jakirkham** [comment]
I would say this is an issue with some conda packages and not Travis. So, I think that is safe.
