### ISSUE TITLE
dlang: rdmd for ldc/gdc configurations

### ISSUE THREAD

**Issue by Abscissa** [travis-ci/travis-ci#4817]
Can we get rdmd included for ldc and gdc configurations? And naturally ldmd2/gdmd if they aren't already (not sure if they are).

Or if rdmd shouldn't be included for ldc/gdc since it's not included with official ldc/gdc, is there a good way to set up .travis.yml to grab it? I know I can probably use a custom script for "install: " to download it from somewhere, but is there a better way?

(cc'ing @ibuclaw, @klickverbot and @MartinNowak)

**Comment by MartinNowak** [comment]
I wouldn't want to compile an additional program that might not be used.
This should work and is easy enough.
```yaml
install:
  - curl -fsSLO https://raw.githubusercontent.com/D-Programming-Language/tools/v2.068.0/rdmd.d
  - ${DMD} rdmd.D
  - mv rdmd $(dirname $(which ${DMD}))
```

**Comment by MartinNowak** [comment]
ldmd2 and gdmd are already included as well, you get them with the `$DMD` env variable, as opposed to ldc2 and gdc with the `$DC` env variable.

This issue can be closed.
