### ISSUE TITLE
Node 4.1.0

### ISSUE THREAD

**Issue by vielmetti** [travis-ci/travis-ci#4818]
The NodeJS project has released 4.1.0

https://github.com/nodejs/node/issues/2844

Tracking adding this (or recipes for installing this) inside Travis CI. It's not a huge change (no where near as traumatic as 0.12 -> 4.0.0).

**Comment by BanzaiMan** [comment]
Once it is released, nvm should pick this up automatically.

**Comment by vielmetti** [comment]
`nvm` has it now, closing this. Thanks!
