### ISSUE TITLE
The command "nvm install X.XX" failed and exited with 3 during .

### ISSUE THREAD

**Issue by vladikoff** [travis-ci/travis-ci#4819]
nvm seems totally broken currently, see builds: https://travis-ci.org/mozilla/fxa-auth-server/builds/80875180

```

$ nvm install 0.10
Version '0.10' not found - try `nvm ls-remote` to browse available versions.
The command "nvm install 0.10" failed and exited with 3 during .
Your build has been stopped.
```

**Comment by NickTomlin** [comment]
I just started seeing this as well

**Comment by solarce** [comment]
nvm relies on nodejs.org and iojs.org being able to query when you invoke `nvm install x.x`, https://github.com/creationix/nvm/blob/master/nvm.sh#L86-L93, so if nodejs.org (really whatever CloudFlare.com edge servers are serving where the requests from, as CloudFlare sits in front of nodejs.org) then it will result in the error message above.

We understand this behavior can be confusing and we opened https://github.com/creationix/nvm/issues/759 about it.
