### ISSUE TITLE
py.test version incompatible with Python 3.5.

### ISSUE THREAD

**Issue by coady** [travis-ci/travis-ci#4821]
py.test requires [version 2.7.3](https://github.com/pytest-dev/pytest/issues/744) for Python 3.5.

**Comment by BanzaiMan** [comment]
I've rebuilt Python 3.5.0 archive, which now contains pytest 2.7.3.

**Comment by untitaker** [comment]
Hmm, it doesn't seem like pytest 2.7.3 actually comes preinstalled to me.


If you take a look at https://travis-ci.org/untitaker/vdirsyncer, you'll see that:

* on `master`, py.test 2.7.2 or even older is used
* on `python35`, I try to do `pip install pytest>=2.8.0`, but this fails with `Failed building wheel for psutil` and some older py.test version is still used.

**Comment by coady** [comment]
I'm still seeing the error:
```
==================================== ERRORS ====================================
__________________________ ERROR collecting tests.py ___________________________
../../../virtualenv/python3.5.0/lib/python3.5/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:954: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:892: in _find_spec
    ???
<frozen importlib._bootstrap>:873: in _find_spec_legacy
    ???
../../../virtualenv/python3.5.0/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:137: in find_module
    source_stat, co = _rewrite_test(state, fn_pypath)
../../../virtualenv/python3.5.0/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:278: in _rewrite_test
    rewrite_asserts(tree)
../../../virtualenv/python3.5.0/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:336: in rewrite_asserts
    AssertionRewriter().run(mod)
../../../virtualenv/python3.5.0/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:557: in run
    new.extend(self.visit(child))
/opt/python/3.5.0/lib/python3.5/ast.py:245: in visit
    return visitor(node)
../../../virtualenv/python3.5.0/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:665: in visit_Assert
    top_condition, explanation = self.visit(assert_.test)
/opt/python/3.5.0/lib/python3.5/ast.py:245: in visit
    return visitor(node)
../../../virtualenv/python3.5.0/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:796: in visit_Compare
    left_res, left_expl = self.visit(comp.left)
/opt/python/3.5.0/lib/python3.5/ast.py:245: in visit
    return visitor(node)
../../../virtualenv/python3.5.0/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:757: in visit_Call
    new_func, func_expl = self.visit(call.func)
/opt/python/3.5.0/lib/python3.5/ast.py:245: in visit
    return visitor(node)
../../../virtualenv/python3.5.0/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:700: in visit_Name
    locs = ast.Call(self.builtin("locals"), [], [], None, None)
E   TypeError: Call constructor takes either 0 or 3 positional arguments
```

I'm certain it's the same issue: [https://github.com/pytest-dev/pytest/issues/744].  And @untitaker, agreed, it doesn't seem to matter if a specific pytest version is pip installed in .travis.yml.

**Comment by untitaker** [comment]
>it doesn't seem to matter if a specific pytest version is pip installed in .travis.yml

It *would matter*, but the installation of a specific pytest version fails.

**Comment by untitaker** [comment]
@BanzaiMan Are those changes also available for the legacy infrastructure?

**Comment by BanzaiMan** [comment]
Python 3.5 archive is downloaded from the same place for all infrastructures.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/81306945#L97 shows that 2.7.3 is pre-installed for Python 3.5.0. All other Python runtimes do not have py.test 2.7.3, since they are pre-installed on the build image.

**Comment by untitaker** [comment]
@BanzaiMan See https://travis-ci.org/untitaker/vdirsyncer/jobs/81485618, I have Python 3.5 but an old py.test.

**Comment by BanzaiMan** [comment]
@untitaker I see what was wrong. I only rebuilt the `3.5.0` archive, but not the `3.5` archive. It's on the way now, and it'll be available in 15 minutes or so. Sorry about that.

**Comment by untitaker** [comment]
@BanzaiMan great, no problem, thanks!

**Comment by coady** [comment]
:+1:
