### ISSUE TITLE
`ccache` caching support in pull request branches

### ISSUE THREAD

**Issue by qris** [travis-ci/travis-ci#4829]
Hi, I have a question about how ccache interacts with Travis caches.

The documentation says that:
- Only modifications made to the cached directories from normal pushes are stored.
- Currently Pull Requests will use the cache of the branch they are supposed to be merged into.

I submitted a pull request to enable ccache in .travis.yml:

```
cache:
  - apt
  - ccache
```

But it doesn't appear to have sped up the build. I wonder if pull requests don't write their changes back to the cache of the branch that they're trying to merge to? The documentation above isn't exactly clear on that. Can you advise?

Thanks, Chris.

**Comment by BanzaiMan** [comment]
Could you point to the relevant build log URLs to indicate this problem? Thank you.

**Comment by qris** [comment]
Sure, you can see [this build](https://travis-ci.org/boxbackup/boxbackup/jobs/81207330). `ccache -s

**Comment by BanzaiMan** [comment]
> Is this because the cache created while building the pull request isn't added back to the main branch?

Yes. The PR builds keep their own cache. This is explained in https://docs.travis-ci.com/user/caching/#Pull-request-builds-and-caches.
