### ISSUE TITLE
Global build status incorrect when builds finish out of order

### ISSUE THREAD

**Issue by seancribbs** [travis-ci/travis-ci#483]
I pushed a fix that ended up finishing its build before a previous commit's build. As a result the build status on the left-hand side was incorrect (red). Note that the build-status image shows the correct status.

<div class="thumbnail"><a href="https://skitch.com/seancribbs/8ph32/travis-ci-distributed-build-platform-for-the-open-source-community"><img src="https://img.skitch.com/20120328-b9neqfcgrhqffsnyi3wptxcuk7.preview.jpg" alt="Travis CI - Distributed build platform for the open source community" /></a></div>

<div class="thumbnail"><a href="https://skitch.com/seancribbs/8ph4t/travis-ci-distributed-build-platform-for-the-open-source-community"><img src="https://img.skitch.com/20120328-rghtwygajkcpsdjbbds2t87ny1.preview.jpg" alt="Travis CI - Distributed build platform for the open source community" /></a></div>

**Comment by JamesMGreene** [comment]
:+1:

I ran into this today with [JamesMGreene/qunit-assert-step](https://travis-ci.org/JamesMGreene/qunit-assert-step/). [Build #4](https://travis-ci.org/JamesMGreene/qunit-assert-step/builds/46735425) passed but [Build #3](https://travis-ci.org/JamesMGreene/qunit-assert-step/builds/46735338) (both on the `master` branch) finished after it with an error, so the `master` branch's status badge was "error".

I ended up rerunning [Build #4](https://travis-ci.org/JamesMGreene/qunit-assert-step/builds/46735425) to fix the badge.

**Comment by yelinaung** [comment]
Run into similar problems with two repos. 

[Rabbit-Converter/Rabbit-PHP](https://github.com/Rabbit-Converter/Rabbit-PHP) : [Travis](https://travis-ci.org/Rabbit-Converter/Rabbit-PHP/builds)
[Rabbit-Converter/Rabbit-Elixir](https://github.com/Rabbit-Converter/Rabbit-Elixir) : [Travis](https://travis-ci.org/Rabbit-Converter/Rabbit-Elixir/builds)

Both build passed but the badge is still showing the first build status which is fail/error.
