### ISSUE TITLE
Travis Artifacts are broken

### ISSUE THREAD

**Issue by mourner** [travis-ci/travis-ci#4830]
Travis artifacts are broken since today. Sample build: https://travis-ci.org/Leaflet/Leaflet/builds/81249414. Output:

```
Uploading Artifacts (BETA)
$ travis_artifacts_install
/home/travis/bin/artifacts: line 1: syntax error near unexpected token `newline'
/home/travis/bin/artifacts: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
```

Artifacts configuration:

```
addons:
  artifacts:
    paths:
    - dist
    target_paths:
    - content/build/${TRAVIS_BRANCH}
```

**Comment by BanzaiMan** [comment]
Most likely due to the AWS outage. Please try again when the service is restored. Thanks.

**Comment by mourner** [comment]
Yep, works now. The AWS involvement just wasn't apparent from the error.
