### ISSUE TITLE
Rebuild not working on Pull Requests

### ISSUE THREAD

**Issue by qris** [travis-ci/travis-ci#4831]
I'm trying to rebuild a pull request, it goes to yellow status and says "Hang tight, the log cannot be shown until the build has started." But it never appears to actually start. You can see [the build stuck in this state](https://travis-ci.org/boxbackup/boxbackup/jobs/81207329).

I also tried amending a commit and force pushing to the branch, but this doesn't seem to trigger a rebuild at all.

What is the right way to rebuild a pull request, and why this this job stuck?

**Comment by vielmetti** [comment]
AWS is having issues this a.m. which are affecting Travis and a great many other systems. A very small writeup is here: http://vielmetti.github.io/post/2015/2015-09-20-aws-dynamodb-downtime-sunday-am/ .

Check https://www.traviscistatus.com/ for details specific to Travis.

**Comment by qris** [comment]
OK thanks, I will wait for Amazon to fix their issues :) You might want to make it more prominent on the Travis site that there is an ongoing issue.
