### ISSUE TITLE
No output from php cli script in after_success

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#4833]
I have automatic builds uploaded to sourceforge on each commit using Travis.
However, I've just realized that last successful build was on 5th September.
For instance, this job: https://travis-ci.org/nazar-pc/CleverStyle-CMS/jobs/81331196
Closer to end `php -d phar.readonly=Off upload_build.php` has no output, it looks like it was not even running (if it was running without output - build would have been uploaded).
As you can see from [source code](https://github.com/nazar-pc/CleverStyle-CMS/blob/master/upload_build.php) of that script - there is no way for it to end without any output at all.

So, what happened at 5th of September that it stopped working?

**Comment by BanzaiMan** [comment]
Is this the commit that changed the behavior of your script? https://github.com/nazar-pc/CleverStyle-CMS/commit/e7c7d44d3a791c6127e4adb7e2d40dea511f7fa6

**Comment by nazar-pc** [comment]
No, it would output at least that message, but I do not see anything on Travis job.
That script does print something in any possible case.

**Comment by BanzaiMan** [comment]
Ah, I see. If you look at the raw log (e.g., https://s3.amazonaws.com/archive.travis-ci.org/jobs/81331196/log.txt) you will see:

```
[0K$ php -d phar.readonly=Off upload_build.php
Only regular releases are uploaded, other tags ignoredtravis_time:end:0e4034b9:start=1442813249686797574,finish=1442813249753915393,duration=67117819
```

There is no newline after the `echo`'d string, and it is getting swallowed by the log display.

**Comment by nazar-pc** [comment]
Thanks, it seems to be a bug when command output doesn't contain new line at the end.

**Comment by BanzaiMan** [comment]
Could you try adding a newline character to your output to see if it makes a difference?

**Comment by nazar-pc** [comment]
Yes, new line at the end of string helps: https://travis-ci.org/nazar-pc/CleverStyle-CMS/jobs/81678746

**Comment by jacobtomlinson** [comment]
I'm getting the same thing. My `after_success` script is a rake task which calls a single curl command. However there is no sign of it in the logs, raw or web gui.

https://travis-ci.org/jacobtomlinson/jacobtomlinson.github.io/builds/103101582

**Comment by BanzaiMan** [comment]
@jack-pappas Your problem is the placement of `after_success`. https://github.com/jacobtomlinson/jacobtomlinson.github.io/blob/6d14ea76a6bcab511e11b41c1d7b3e2e5607d9cd/.travis.yml#L25 `after_success` should be at the top level of your `.travis_yml`.

**Comment by jacobtomlinson** [comment]
@BanzaiMan I think you mean me :smile:. 

Awesome thanks! I see now, and I also see that I should be using `after_deploy` instead of `after_success` as I'm purging a CDN after deploying new files.

**Comment by jacobtomlinson** [comment]
@BanzaiMan Ok so the command is now running. But I'm still not getting any output from it.

https://travis-ci.org/jacobtomlinson/jacobtomlinson.github.io/builds/103114564

**Comment by BanzaiMan** [comment]
Sorry about that.Is it supposed to show any more than https://travis-ci.org/jacobtomlinson/jacobtomlinson.github.io/builds/103114564#L816?

```
curl https://www.cloudflare.com/api_json.html -d a=fpurge_ts -d tkn=${CLOUDFLARE_API_KEY} -d email=${CLOUDFLARE_EMAIL} -d z=jacobtomlinson.co.uk -d v=1
```

**Comment by jacobtomlinson** [comment]
Yep. If you look at the [raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/103114565/log.txt) you can see the response. It just isn't visible in the web gui.

```
curl https://www.cloudflare.com/api_json.html -d a=fpurge_ts -d tkn=${CLOUDFLARE_API_KEY} -d email=${CLOUDFLARE_EMAIL} -d z=jacobtomlinson.co.uk -d v=1
{"response":{"fpurge_ts":1453126050},"result":"success","msg":null,"attributes":{"cooldown":20}}travis_time:end:04b17334:start=1453126049799579278,finish=1453126050385812488,duration=586233210
```

**Comment by BanzaiMan** [comment]
Looks like this is the same issue, after all. The `rake` task runs `curl`, but that does not print a new line, and this runs into our timer marker.

**Comment by jacobtomlinson** [comment]
Ah good, I'm not going crazy then :), just me adding complications.

So this is just a bug to be fixed by Travis? I guess I could add a `&& echo -e "\n"` to my rake task for now, but that seems a bit hacky.

**Comment by BanzaiMan** [comment]
This should be fixed by https://github.com/travis-ci/travis-build/pull/602. The existing builds with this problem will need to be re-run.

I'm closing this now, but if the problem persists, do let us know.
