### ISSUE TITLE
com.android.builder.testing.api.DeviceException: No connected devices!

### ISSUE THREAD

**Issue by SandroMachado** [travis-ci/travis-ci#4835]
I am running travis in an android project using a matrix configuration (android-15 vs android-21).

Running the travis on android-15 everything works fine, running on android-21 I get the error: 
`Execution failed for task ':app:connectedDevelopmentDebugAndroidTest'. > com.android.builder.testing.api.DeviceException: No connected devices!`

Changing from android-21 to android-19 the tests run without any issues...

**Comment by luisribeiro** [comment]
Hi there!
   Does anyone know how to solve this problem? I've already tried all those configs...
- sys-img-armeabi-v7a-android-23
- sys-img-armeabi-v7a-android-21
- sys-img-armeabi-v7a-android-19
- sys-img-x86-android-17

   Thank you =)

**Comment by andrewhavens** [comment]
What does your `.travis.yml` config look like?
