### ISSUE TITLE
[Suggestion] Make Travis' Linux VM images available for download

### ISSUE THREAD

**Issue by Darelbi** [travis-ci/travis-ci#4837]
Right now travis has one serious problem, it takes ages to boostrap a script and wait it runs. So basically you have "NO INTERACTIVE TERMINAL". Fixing small errors take ages because you have to wait 10-15 minutes (if not more) for what you can do in seconds if you have access to a INTERACTIVE TERMINAL. 

Across linux distros and versions there are SIGNIFICATIVE differences on what package manager/ compiler ( / or other programs) you have installed by default, so basically each linux machine have to be "manually lifted" before becoming ready for someone as a developing environment, that's not good because even a small change can break a build script (I had to use 3 different scripts to get GCC 5.1 on 3 different machines just to give the idea ^^).

Another possible issue is that using a different linux VM may change whatever default "installed" program is present incurring the risk to actually [break a working build script](https://github.com/travis-ci/travis-ci/issues/4805).  (By reading issues, seems A LOT OF PEOPLE got broken build scripts recently, yes of course, it is always fault of people having "wrong dependencies" or dependencies that are changed.).

Debugging scripts is already cumbersome with a interactive terminal, it is definitely impossible with travis. Having the images for virtual box would be definitely the best things because we can debug everything (at least the linux side) on our own before starting complaining on issue tracker ^^

**Comment by kenorb** [comment]
+1
