### ISSUE TITLE
BOM in `.travis.yml` trips up the build configuration

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4839]
If `.travis.yml` has a byte order mark, the resulting build is "truncated".

Given https://github.com/BanzaiMan/travis_production_test/blob/0de7bc30904817b1e2490c58c2b3bf51a24afb53/.travis.yml, one would expect to find two jobs in a build, but it has only one (https://travis-ci.org/BanzaiMan/travis_production_test/builds/81613238), and it is just `language: go` (this is not visible from the build log page, but the data back up this assertion).

The commit to remove BOM (https://github.com/BanzaiMan/travis_production_test/commit/ba89cf466939de06c2a8ea147a257084f5cac76c) creates the matrix correctly (https://travis-ci.org/BanzaiMan/travis_production_test/builds/81614099).

**Comment by rkh** [comment]
FWIW, travis-yaml can handle the BOM.

**Comment by BanzaiMan** [comment]
This was also reported as #3172.

**Comment by BanzaiMan** [comment]
I'm closing this as WONTFIX.

We show the YAML error in the build log (https://travis-ci.org/BanzaiMan/travis_production_test/builds/196010103), the config view https://travis-ci.org/BanzaiMan/travis_production_test/jobs/196010104/config and requests page.

**Comment by BanzaiMan** [comment]
The report in #7785 suggests that UTF-8 BOM actually allows the build to run, with `language` key in effect, but otherwise empty configuration.

**Comment by BanzaiMan** [comment]
We should fix this.

**Comment by ForNeVeR** [comment]
Please note that there's no any error shown in the build log or somewhere else. It just silently fails with the confusing message. See example [here](https://travis-ci.org/ForNeVeR/1969/builds/236925232).

**Comment by BanzaiMan** [comment]
A fix has been deployed.

If you continue to see problems, do let us know.
