### ISSUE TITLE
[based on containers] pip install with cache intall all packages again

### ISSUE THREAD

**Issue by moylop260** [travis-ci/travis-ci#4840]
I have next .travis.yml [cache section](https://github.com/moylop260/pylint-oca/blob/d097bc9cebdb2d85fab8edfb23d38f4cef7a26ac/.travis.yml#L2-L6)
```yaml
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.pip-cache/
```

I have next [pip install](https://github.com/moylop260/pylint-oca/blob/d097bc9cebdb2d85fab8edfb23d38f4cef7a26ac/.travis.yml#L17)
```yaml
 - pip install . coveralls flake8
```

I saw that my [build](https://travis-ci.org/moylop260/pylint-oca/builds/81635158) use cache here
![cache travis](https://cloud.githubusercontent.com/assets/6644187/10027072/a6c72dec-612a-11e5-9385-22a62fff13aa.png)
Good!

I expected that pip packages cached were not installed.

But I saw that pip packages are installed again in my [build](https://travis-ci.org/moylop260/pylint-oca/builds/81635158#L114)
![pip_install](https://cloud.githubusercontent.com/assets/6644187/10027116/f0f9c46a-612a-11e5-8052-2f34331d3feb.png)

What is wrong with my configuration?

**Comment by BanzaiMan** [comment]
Are you sure that `pip` cached the files to `~/.pip-cache`? My understanding is that the default cache location for `pip` is `~/.cache/pip`.

cc @dstufft @alex

**Comment by alex** [comment]
@BanzaiMan you are correct: https://github.com/pyca/cryptography/blob/master/.travis.yml#L5-L7

**Comment by moylop260** [comment]
Thank for reply

I got it
My bad, sorry

The docs is well!
http://docs.travis-ci.com/user/caching/#pip-cache

I used `pip: cache` and don't worked Is deprecated?

**Comment by BanzaiMan** [comment]
@moylop260 Overriding `install` annuls `cache: pip`. (This is also documented.) I know this is not quite intuitive, and there is an existing issue for that.
