### ISSUE TITLE
Rendering bug with long branch names on organization page

### ISSUE THREAD

**Issue by alex** [travis-ci/travis-ci#4841]
For example https://travis-ci.org/18F/ screenshot:

![screen shot 2015-09-22 at 7 52 27 pm](https://cloud.githubusercontent.com/assets/772/10034963/7ab86eb2-6163-11e5-87cf-2d8d7ad28003.png)

**Comment by joshk** [comment]
Thanks for the report, we will look into a fix shortly.

**Comment by alex** [comment]
This got fixed at some point.
