### ISSUE TITLE
error with var: qt_ntfs_permission_lookup

### ISSUE THREAD

**Issue by PKEv** [travis-ci/travis-ci#4843]
i make pull: https://travis-ci.org/tux3/qTox/builds/81810987 and it was not passed

i use variable "qt_ntfs_permission_lookup"

```
extern Q_CORE_EXPORT int qt_ntfs_permission_lookup;
```

from qt datasheet: http://doc.qt.io/qt-5/qfiledevice.html

**Comment by BanzaiMan** [comment]
Sorry, but this has become stale. If the issue is ongoing, please open a new issue.
