### ISSUE TITLE
Can't run Dart CI tests at all.

### ISSUE THREAD

**Issue by eugene-bulkin** [travis-ci/travis-ci#4846]
Every time I tried running tests, I got this error:

```
│ Unhandled exception:
│ Load Error for "package:unittest/src/deprecated/simple_configuration.dart": Error loading file:///home/travis/build/eugene-bulkin/dart_mysql/test/__test_runner/protocol/packages/unittest/src/deprecated/simple_configuration.dart:
│   FileSystemException: Cannot open file, path = '/home/travis/build/eugene-bulkin/dart_mysql/test/__test_runner/protocol/packages/unittest/src/deprecated/simple_configuration.dart' (OS Error: No such file or directory, errno = 2)
│ #0      _asyncLoadErrorCallback (dart:_builtin:149)
│ #1      _asyncLoadError (dart:_builtin:541)
│ #2      _handleLoaderReply (dart:_builtin:364)
│ #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

It looks like the Dart test runner is trying to load a package that doesn't exist.

CC: @sethladd @a14n @devoncarew

**Comment by a14n** [comment]
Is your repository public?

**Comment by eugene-bulkin** [comment]
It is now: https://github.com/eugene-bulkin/dart_mysql

**Comment by a14n** [comment]
Thanks.

Actually you are mixing old [unittest](https://pub.dartlang.org/packages/unittest) package and the new one [test](https://pub.dartlang.org/packages/test).
Moreover the new _test_ package is not compatible with the _test_runner_ used by default on travis. Just replace the default script with `pub run test`. I submitted eugene-bulkin/dart_mysql#1 to fix your `.travis.yml`.

**Comment by eugene-bulkin** [comment]
Thanks. I was mixing the old one because I was getting a different error (missing unittest/vm_config.dart) instead. I will close this once the PR is pulled in and works.
