### ISSUE TITLE
android-update-sdk: command not found

### ISSUE THREAD

**Issue by tomcashman** [travis-ci/travis-ci#4850]
It seems the android-update-sdk command no longer works? I'm receiving an error on my builds all of a sudden.

https://travis-ci.org/mini2Dx/mini2Dx/builds/82217346

**Comment by BanzaiMan** [comment]
Sorry, but we do not support Android on OS X at this time. https://github.com/travis-ci/travis-ci/issues/2320

**Comment by BanzaiMan** [comment]
Please use Linux in the meantime.
