### ISSUE TITLE
Why not use LXD instead of Docker for containered tests?

### ISSUE THREAD

**Issue by marcoceppi** [travis-ci/travis-ci#4851]
Some of my tests will always require sudo/root to work properly. We run our tests using LXD locally which gives us containerized and constrained isolation but instead of an application container it's a full system container.

Curious if there's a reason Docker was chosen over a system container like LXD/LXC which has the same benefits as Docker (images, fast creation times, isolation) but without the restriction outlined on http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by solarce** [comment]
Thanks for your inquiry @marcoceppi. At the time that Travis began looking into adding a container-based build platform to our offerings, http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/, we felt Docker + EC2 was the best combination of technology available at the time and so far we've seen a lot of uptake and happiness with the container based platform, even with the `sudo` restrictions we currently implement.

At this time we don't have any plans to re-evaluate what containerization technology we're using but if we do, we would definitely take a deeper look at LXD.

Cheers!
