### ISSUE TITLE
linter does not accept "stable" and "node" as nodejs version

### ISSUE THREAD

**Issue by hennr** [travis-ci/travis-ci#4852]
The following config does not validate on http://lint.travis-ci.org while the doc says it valid and an actual build job runs it nicely.

```
language: node_js
node_js:
      - "stable"
      - "node"
```

**Comment by bitinn** [comment]
In addition, does `node` currently default to v4.0.0 for some reasons? Shouldn't it be using the latest stable, which is v4.1.1 at the moment?

**Comment by BanzaiMan** [comment]
@bitinn It is up to nvm.

**Comment by jasonkarns** [comment]
The `stable` alias is deprecated by nvm. Perhaps travis should remove it from the documentation?

**Comment by BanzaiMan** [comment]
Fixed by https://github.com/travis-ci/travis-yaml/commit/52d1575ff93b86026a9bd6994b032d1dfd2615c3
