### ISSUE TITLE
Linux Builds for Open Source projects don't kick off

### ISSUE THREAD

**Issue by automatictester** [travis-ci/travis-ci#4855]
Here is an example:
https://travis-ci.org/automatictester/lightning/builds/82296019

According to your status page there is a problem with OS X builds, but this is not OS X, this is just Linux.

**Comment by BanzaiMan** [comment]
Sorry about the issue. We had a build processing issue earlier today. http://stspg.io/1WHn

Please close this issue when it is processed. Thank you.
