### ISSUE TITLE
500 internal error when trying to view builds of ProgrammersOfVilnius/pov-server-page

### ISSUE THREAD

**Issue by mgedmin** [travis-ci/travis-ci#4858]
1. Open https://travis-ci.org/ProgrammersOfVilnius/pov-server-page/builds
2. See how it fails to load and instead spins the spinner forever
3. Open dev console, check the error log

> https://api.travis-ci.org/builds?event_type%5B%5D=push&event_type%5B%5D=api&repository_id=1207190
> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**UPDATE**

Steps to reproduce:

- push a `.travis.yml` that mistakenly uses `env:` instead of `python`:

```
env:
  - 2.7
  - 3.4
```

- try to look at the list of builds -- it'll fail to load
- try to look into particular builds, if you can get a link (e.g. from the Branches page) -- it'll fail to load

**Comment by BanzaiMan** [comment]
So, I see the exception thrown in the logs, and it is quite curious. When it tries to load the build data, it is trying to decrypt data from Settings, but it is somehow failing.

```
NoMethodError: undefined method `new' for Float:Class
  from /app/vendor/bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
  from /app/vendor/bundle/ruby/2.1.0/bin/unicorn:23:in `load'
  from /app/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
  from unicorn/http_server.rb:294:in `join'
  from unicorn/http_server.rb:536:in `maintain_worker_count'
  from unicorn/http_server.rb:525:in `spawn_missing_workers'
  from unicorn/http_server.rb:670:in `worker_loop'
  from unicorn/http_server.rb:576:in `process_client'
  from travis/api/app.rb:151:in `call'
⋮
```

Do you have anything in the Settings panel that might explain this exception? I can try looking into the database itself, but that can be sensitive.

**Comment by mgedmin** [comment]
I don't think I even touched Settings here.  It's all defaults:
![ekrano nuotrauka is 2015-09-29 09-10-25](https://cloud.githubusercontent.com/assets/159967/10156463/f9534ed8-6689-11e5-8801-3a42f5a2fab2.png)

There shouldn't be anything sensitive about this repo, so feel free to take a look at the DB.

**Comment by mgedmin** [comment]
This is still failing for me.

I can see tantalizing hints of hidden failures:
![ekrano nuotrauka is 2015-11-03 22-06-18](https://cloud.githubusercontent.com/assets/159967/10920118/2a67a31c-8277-11e5-9ad2-b4f70453baf4.png)

but I can't see any build information if I click on those red Xes:
![ekrano nuotrauka is 2015-11-03 21-57-07](https://cloud.githubusercontent.com/assets/159967/10920126/330f2eea-8277-11e5-8218-1d674ba97433.png)

**Comment by mgedmin** [comment]
Ha!  Looks like a simple mistake in my `.travis.yml` was causing this:
https://github.com/ProgrammersOfVilnius/pov-server-page/commit/ae43d07ebaea9a139d8cd98cd48963b6e8e2e8be

**Comment by mgedmin** [comment]
Uh, I accidentally broke 7 ZopeFoundation repositories by committing erroneous `.travis.yml` files (yay automation).  As long as builds exist with such incorrect metadata, the "Builds" list page of each of those repositories are inaccessible, which is rather inconvenient.

Aserver-side fix would be very welcome.

**Comment by rkh** [comment]
Looking into it.

**Comment by carlad** [comment]
I've gone and looked at the customers page and it seems like everything is working okay for this repo now so i will close the issue.
