### ISSUE TITLE
To brew install qt5 results in the log length exceeding the limit of 4 MB

### ISSUE THREAD

**Issue by agarny** [travis-ci/travis-ci#4861]
Until a couple of days ago, I could install qt5 within Travis CI and this without any problem. However, today, it just keeps failing. I have noticed that a new version of the formula has been released.

Basically, Travis CI complains about the log length exceeding the limit of 4 MB. Checking the Travis CI output when installing qt5, I can see that the 'progress bar' doesn't progress 'normally' and, in fact, flashes all over the place. I am not sure what is going on under the hood, but it's certainly causing Travis CI to 'fail'. (My 'fix' currently consists of redirecting the output to /dev/null, but that's clearly not something I want to have to do.)

I have asked the brew team about it and someone told me that the problem was most likely due to Travis CI. Any ideas?...

FWIW, the script that 'fails' (but used to work a couple of days ago) can be found [here](https://github.com/opencor/opencor/blob/3f8a31be724aef8cb5c4a70b95f6fda9f3b6c10b/.travis.yml#L32) while the one that I am now using (temporarily, I hope) can be found [here](https://github.com/opencor/opencor/blob/2db293c3144146832812184d73e58eece6806e21/.travis.yml#L35).

**Comment by BanzaiMan** [comment]
I don't know what Homebrew uses to display the progress bars, but in general, manipulating the terminal output with ANSI escape codes can be problematic with our log display, which is stream based. If Homebrew emits too much escape codes and exceeds the quota, I'm afraid there is not much we can do. Redirecting the output somewhere, either a file (which you can choose to reveal in a case of failure, or upload via artifacts) or `/dev/null`, is probably best.

**Comment by agarny** [comment]
From https://github.com/Homebrew/homebrew/issues/44446, it would seem that the progress bar comes from downloading ```qt5``` using ```curl```. What I don't understand is that it used to work fine with the previous version of their ```qt5``` formula, which I imagine would have resulted in roughly the same amount of escape codes, if any. Also, my ```.travis.yml``` script installs ```cmake``` before installing ```qt5```, and it's working just fine, i.e. the progress bar doesn't flash or anything. So, I am not sure why, all of a sudden, things are not working with the new version of the ```qt5``` formula.

FWIW, [here](https://travis-ci.org/opencor/opencor/builds/82883318) is a typical output of what I am getting.

**Comment by agarny** [comment]
@BanzaiMan, I think you can safely close this issue since everything is 'normal' and a 'fix' has been provided (see https://github.com/Homebrew/homebrew/issues/44446).
