### ISSUE TITLE
Unsure if working or not

### ISSUE THREAD

**Issue by npateman** [travis-ci/travis-ci#4863]
I'm currently seeing the following in travis-ci,

<img width="703" alt="travis" src="https://cloud.githubusercontent.com/assets/1122645/10168729/f1be2026-66c5-11e5-8006-813ecf857a17.PNG">

I'm unsure why the last (first) entry says "Build created successfully" but has a red X on the left and whether or not it is doing anything after detecting that a push has been made.  Should I be waiting much longer for it to do something?

**Comment by BanzaiMan** [comment]
This is strange. `gh-pages` branch should not be built at all. If you want to build it, you need to whitelist it. http://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches

**Comment by npateman** [comment]
Great thanks, doing that has got something happening, thanks :)
