### ISSUE TITLE
Build fails on PHP 7 because `pecl` command unavailable

### ISSUE THREAD

**Issue by ramsey** [travis-ci/travis-ci#4865]
Until recently, the `pecl` command was available with PHP 7 on Travis CI. See this build from yesterday:

https://travis-ci.org/ramsey/uuid/jobs/82593307#L496

That is highlighting the line where the `pecl` command is used successfully. This functionality has been working since PHP 7 was available on Travis CI.

However, today, builds are failing because the `pecl` command is not available. See the same project build here (again with the line highlighted where the `pecl` command is used):

https://travis-ci.org/ramsey/uuid/jobs/82782647#L494

All other PHP versions appear to be operating normally, with the `pecl` command available.

**Comment by ramsey** [comment]
I looks like this is related to #4800, though I'm not sure why it was working yesterday.

**Comment by BanzaiMan** [comment]
Looks like I broke 7 packaging. I'll take a look.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/4800#issuecomment-144465991
