### ISSUE TITLE
Pull request author can't cancel builds

### ISSUE THREAD

**Issue by o11c** [travis-ci/travis-ci#4867]
Recently I submitted a PR to a repository I don't have push access to, then discovered a typo in the matrix and force-pushed.

However, unlike with my own repos, I could not cancel the known-bad build, so I had to wait for all those matrix rows to run before the fixed ones could be.

**Comment by BanzaiMan** [comment]
Canceling/restarting builds requires push access to the repository on which the build is running.

Furthermore, the commit author data may not map to a GitHub user data. We understand this case, but I don't think we can resolve this in a clean way.

**Comment by o11c** [comment]
Commit author doesn't matter, you can look at the fork that the PR was made from. That information is visible in the web UI, so I can only presume it is visible in the API as well ...

**Comment by kbrock** [comment]
Yes, is it possible for me to cancel a build on travis from a PR that I created?
You know my github identity, and you display me as the author of the PR.

I agree, correlating to the commit author would be too tricky, but nailing this down the th PR author, that is determined from my github identity, seems solid.

I feel terrible submitting a double build to travis.
And I'd really like to cancel these bogus builds and reduce the load on travis.
(and make it quicker for me too)

**Comment by rnelson0** [comment]
I'd like to vote for this (effective) feature. Perhaps an easier way would be that if the PR is updated, the running matrix entries could end and then the build finishes with the non-started matrix entries never running. That would still be a lot faster than letting a build with 20 entries that we know are going to fail to keep processing. This could be a setting on a repo (Quick finish builds when a PR is updated) so there's still some control on whether the behavior is desired.

**Comment by kbrock** [comment]
@rnelson0 I've seen the request for auto finishing of builds (I've made it too) but so far, it looks like the team is leaning against this. So the next best thing is to let me cancel it if I know that the build is no longer valid. (this Issue)

**Comment by joshk** [comment]
There is a high likely hood that we will be able to look into auto cancelling in the second half of this year, and maybe allow for 'author' cancelling as well, but that is a lot more involved.

**Comment by kbrock** [comment]
@joshk thanks for your work and keeping us in the loop.

I had thought `author` canceling would be easy - but that is from a pointy haired engineer who doesn't know your code. Thanks so much for such a great resource

**Comment by joshk** [comment]
I do see the value in auto cancelling, as it gives more control of the queue to the user/owner.

I don't have any ETAs as we have a very busy Q1 and Q2 planned, some exciting things in the works, which I will blog about soon.

**Comment by rnelson0** [comment]
@joshk Thanks for the update!

**Comment by PeterDaveHello** [comment]
May I ask if there is update here? This would be very very useful and can help Travis CI save building resource, thanks!

**Comment by berndhahnebach** [comment]
Same here! I'm main developer of a project and travis does not give me more run time. The craze thing is I would need less run time in summary if they would give me more. What I do if I need a test I make a PR to our main repo but if there is a typo or something similar I can not cancel the build which means even more run time for travis which is not needed at all, but I can not cancel the build.

cheers bernd

**Comment by SaschaNaz** [comment]
Canceling by closing a PR will be good, if possible.

**Comment by gaborbernat** [comment]
bump

**Comment by Varun-garg** [comment]
I just forced pushed into a pull request 3 times, and each build takes about 1.5 hours. It's not just a waste of time but also hours of computing.

**Comment by cognifloyd** [comment]
I guess we'll need a 89 day bump post until this is added. Sorry for the spam people. Bump.

**Comment by Ericson2314** [comment]
Yeah this is definitely the biggest, lowest, hanging fruit for travis CI.

**Comment by BanzaiMan** [comment]
I'm merging this with #887, as the implementation would be similar (if not identical).

**Comment by berndhahnebach** [comment]
Does it mean somewhere in the future I will be able to stop a started travis run?

**Comment by rnelson0** [comment]
FWIW that issue is locked, this was the last place people could express support for this feature request.
