### ISSUE TITLE
Rails Build is Failing with "LoadError: cannot load such file -- rails/all"

### ISSUE THREAD

**Issue by joshuabremer** [travis-ci/travis-ci#4868]
I have a Rails project that is failing on every build, even previously passing builds with the following error:

`LoadError: cannot load such file -- rails/all`

```
Running command: bin/rake db:create
rake aborted!
LoadError: cannot load such file -- rails/all
```

Failing build is private: https://magnum.travis-ci.com/sweetspot/platform/jobs/16851325

**Comment by BanzaiMan** [comment]
When previously successful builds start to fail, it is usually due to changes in the underlying dependencies. Comparing the dependencies before and after often gives you an idea what the culprit might be.
