### ISSUE TITLE
Restricted access to accounts

### ISSUE THREAD

**Issue by mathstuf** [travis-ci/travis-ci#4871]
Is there a way to only give permission to Travis-CI for specific repos and/or orgs (other than creating a new account and linking it with Travis)? I would really rather just not give Travis-CI access to repos that don't matter in the first place.

I suspect this is basically GitHub's permission model being inexact, but it'd still be nice if it is possible.

**Comment by BanzaiMan** [comment]
As you mention, our access model closely reflect that of GitHub. As GitHub does not give us the level of granularity you seek, it is not possible at this time. We may revisit this in the future, but for now, I'm closing this.
