### ISSUE TITLE
Cache constantly invalidated by pre-installed virtualenv pytest

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#4873]
The Travis Python environment comes with pytest/nose/mock pre-installed in the virtualenv. 

Unfortunately that version of [pytest](https://pypi.python.org/pypi/pytest) (v2.6.4) and its inherited dependency, [py](https://pypi.python.org/pypi/py) (v1.4.26), is older than the one we have in [our dev requirements file](https://github.com/mozilla/treeherder/blob/82a32b84b042a3e49560998e297b2b43bd8d5107/requirements/dev.txt).

This combined with us using Travis directory caching for the virtualenv (specifically `$HOME/virtualenv/python2.7.9`, see [.travis.yml](https://github.com/mozilla/treeherder/blob/82a32b84b042a3e49560998e297b2b43bd8d5107/.travis.yml)) means that on every Travis run, the cache is invalidated. eg:
https://travis-ci.org/mozilla/treeherder/builds/83192578

```
store build cache
change detected:
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/py-1.4.26-py2.7.egg-info/dependency_links.txt
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/py-1.4.26-py2.7.egg-info/installed-files.txt
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/py-1.4.26-py2.7.egg-info/not-zip-safe
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/py-1.4.26-py2.7.egg-info/PKG-INFO
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/py-1.4.26-py2.7.egg-info/SOURCES.txt
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/py-1.4.26-py2.7.egg-info/top_level.txt
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/py/_apipkg.pyc
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/py/_apipkg.pyc
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/py/_builtin.pyc
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/py/_builtin.pyc
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packa
...
changes detected, packing new archive
```

This means:
- Lots of superfluous cache archives (I've recently had a spring clean, or you'd see dozens [here](https://travis-ci.org/mozilla/treeherder/caches))
- The job runtime is increased due to the time taken to pack and upload the archive, which means waiting longer before the job goes green on GitHub, which delays the Heroku deploy.

Things that would help us:
1) Updating the base Travis Python environment to use a newer version of pytest et al. (These were supposed to be updated as part of [this update](http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/) but unfortunately the whole thing was scrapped, rather than just the mysql 5.6 parts.)
2) Making the job "turn green" even before the upload cache step has finished, so at least it doesn't delay getting the result.
3) Changing the order of virtualenv creation / cache unpacking, so our cache files "win" and the invalidation doesn't occur in the first place.

Thanks :-)

**Comment by edmorley** [comment]
@BanzaiMan - I see the Python label has been added, however I wonder if really the main problem here is (3) from above - ie: the order of cache unpacking vs the language-specific tasks? If the existing cache archive was unpacked later in the build, then it wouldn't have gotten overwritten in the first place.

**Comment by edmorley** [comment]
So looking into this more, I think the rough chain of events is:
1) Directory that is being cached is already present in the image
2) Existing cache gets downloaded and unpacked over this directory, but any files present in the directory already are not cleaned out.
3) The caching tool then takes a snapshot of the directory, which is original_cache + files_already_present
4) The pip install step then cleans up the leftover files (since it sees it as a pytest update)
5) At the end of the job, the caching tool then compare the snapshot with the directory contents, and unsurprisingly they don't match.

IMO the bug here is that the caching tool should do either of these rather than the current behaviour:
1. Wipe the existing directory, when unpacking the cache
2. Take the cache checksum/snapshot based on the downloaded cache archive, not cache archive + whatever else happened to be lying around in that directory already. (ie: unpack the cache into a staging directory, then take the checksum, then copy over the target directory).

**Comment by edmorley** [comment]
Alternatively, if we had a `before_cache_unpack` step (ie a start-of-job equivalent of `before_cache`) I could clean out the unwanted files to avoid this manually.

**Comment by edmorley** [comment]
That said, I think the best fix here might just be to stop bundling things in the virtualenv - it only serves to mask that people have things missing from their requirements.txt, and for everyone else - the chances are that it doesn't save any runtime, since they'll be using a different version.

**Comment by jjyr** [comment]
Same error

**Comment by phlax** [comment]
this wastes a lot of net/cpu/io cycles

**Comment by edmorley** [comment]
> IMO the bug here is that the caching tool should do either of these rather than the current behaviour:

@BanzaiMan I was thinking of trying to fix this -- which of the two approaches above would you prefer?

**Comment by edmorley** [comment]
Hmm thinking about it, option 1 seems like it would break this setup for example:
```yml
      cache:
        directories:
          - $HOME/virtualenv
```

...since on first run, the cache would be empty and therefore the existing virtualenv would get wiped out before it had a chance to be cached.

This leaves the following options:
2) Extracting the cache to a staging directory and generating the hashes there, then copying them over the target. Though presumably the hashes file contains paths, and shuffling files around could increase cache setup times, so this becomes non-trivial.
3) Stopping bundling pytest in the default virtualenv (or adding a `.travis.yml` option for a "clean" virtualenv).
4) Adding a `before_cache_unpack` build stage, in which users could `pip uninstall pytest ...` themselves.

I'm personally more in favour of (3) since whilst it might sound like a convenience to have pytest installed, it lets users introduce non-determinism into their test run, by (a) not pinning dependencies, (b) not having a setup that works locally too.

**Comment by edmorley** [comment]
Still applicable

**Comment by edmorley** [comment]
> Still applicable

**Comment by edmorley** [comment]
> > Still applicable

**Comment by BanzaiMan** [comment]
So, these dependencies are still older than the one you are caching, after 3 years?
