### ISSUE TITLE
Failure in MariaDB addons installation is not detected

### ISSUE THREAD

**Issue by nanaya** [travis-ci/travis-ci#4874]
As can be seen here:

https://travis-ci.org/ppy/osu-web/jobs/83279917

Since mysql is already preinstalled and all commands are the same as mysql, status check using `mysql --version` doesn't actually tell if the installation is successful.

**Comment by grooverdan** [comment]
This build had a network error connecting to the mariadb mirror. The latest build on travis did install mariadb-10 correctly.

**Comment by BanzaiMan** [comment]
Closing.

**Comment by nanaya** [comment]
I must've missed the first reply because problem with my github email notification but the problem wasn't "can't install mariadb" but "there's network problem when installing mariadb but travisci assumed it went all right because it checks installation result status by doing `mysql --version` instead of return status of apt-get"
