### ISSUE TITLE
Builds seem to be going way slower

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#4875]
Within about a week, I have seen my build times rise about 50% on average. I'm a little confused as to what has caused this change as there has been little change to build (no new dependencies, no new tests, etc.). The changes themselves have been primarily documentation based. Is there a reason that these builds appear so slow?

**Comment by BanzaiMan** [comment]
Please include relevant build log URLs to show this problem. Thanks.

**Comment by jakirkham** [comment]
Sure, @BanzaiMan, take a look at the builds here ( https://travis-ci.org/jakirkham/nanshe/builds ). In particular, build number 2103 and before show typical build times prior to the slowdown. All builds after 2103 show examples of the slowdown.

**Comment by jakirkham** [comment]
This seems to have since improved.
