### ISSUE TITLE
using invalid (perl) version, does not fail build

### ISSUE THREAD

**Issue by glensc** [travis-ci/travis-ci#4879]
(originally mentioned [here](https://github.com/travis-ci/travis-cookbooks/pull/482#issuecomment-145216180))

specifying 5.22 in .travis.yml file does not yeild an error, but rather continues with 5.14 version.

cut from build log:

```
$ perlbrew use 5.22
ERROR: The installation "5.22" is unknown.
$ perl --version
This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
(with 57 registered patches, see perl -V for more detail)
```

as you can see, it continued with next command (`perl --version`)

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-build/pull/518

**Comment by BanzaiMan** [comment]
Related: #5333

**Comment by BanzaiMan** [comment]
Reverted the change due to some reports of errors I didn't consider.
