### ISSUE TITLE
Crystal: 'crystal: command not found' error

### ISSUE THREAD

**Issue by rhysd** [travis-ci/travis-ci#4880]
@asterite, @jhass, @waj, @will

I'm developing [crdoc](https://github.com/rhysd/crdoc) with Crystal and Travis reported the build was failure with below error.

```
$ crystal --version
/home/travis/build.sh: line 41: crystal: command not found
```

The log is [here](https://travis-ci.org/rhysd/crdoc/builds/83524938)

Note that this was OK [yesterday](https://travis-ci.org/rhysd/crdoc/builds/83485714) but not OK today.  I didn't change any source code and `.travis.yml`.

- [.travis.yml](https://github.com/rhysd/crdoc/blob/master/.travis.yml)

**Comment by jhass** [comment]
Probably a network issue, installing the GPG key failed: https://travis-ci.org/rhysd/crdoc/builds/83524938#L67

Could you retry the build please?

**Comment by rhysd** [comment]
I retried but it still reported the same error.

https://travis-ci.org/rhysd/crdoc/builds/83525296

**Comment by waj** [comment]
This is happening very often. Should we switch to a different key server? `pgp.mit.edu` maybe?

**Comment by jhass** [comment]
I don't know, `keys.gnupg.net` is a roundrobin DNS service and working fine for me locally. The folks at `#gnupg` on Freenode were rather surprised of it not working somewhere too. Another popular pool is https://sks-keyservers.net/ but https://sks-keyservers.net/status/ doesn't look too reassuring either.

**Comment by rhysd** [comment]
I confirmed [the CI had been passed](https://travis-ci.org/rhysd/crdoc/builds/83525296).  Thank you for the work.

I remain this issue open because I don't know this issue is really resolved.  If so, please close this issue.

**Comment by jhass** [comment]
I guess Travis had a bad server cached, you can close the issue and reopen if you see it again.

**Comment by rhysd** [comment]
OK, thank you again.
