### ISSUE TITLE
ENH: Provide `conda` and `conda-build`

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#4883]
In the Python community, particularly in data orientated fields, `conda` has seen a great deal of success. This in no small part due to how it is able to easily install commonly used packages like the SciPy Stack ( http://www.scipy.org/stackspec.html ) on any platform. It is even given attention PyPA ( http://python-packaging-user-guide.readthedocs.org/en/latest/science/?highlight=conda#the-conda-cross-platform-package-manager ). As a consequence, many projects install `conda` as part of the build process. In order to speed up build times across the board and provide some better functionality, it would be nice to provide `conda` out of the box.

**Comment by eliteraspberries** [comment]
:+1:

**Comment by jakirkham** [comment]
It's true. It really is a language agnostic, cross-platform package manager. Though a lot of the users work with and packages are from Python. That being said, there is also substantial support for R. Also, there are many communities that provide packages that one can install with `conda`. Thus support for things like Perl, C, C++, Lua and other languages can be provided.

**Comment by yoavram** [comment]
👍

**Comment by jakirkham** [comment]
Can this please be reopened? AFAIK this has not been solved. Thanks. :)

**Comment by pitrou** [comment]
Opened anew as #10225.
