### ISSUE TITLE
Provide `conda` deploy option to anaconda.org

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#4884]
An orthogonal but related issue to ( https://github.com/travis-ci/travis-ci/issues/4883 ).

It would be nice to have a deploy step for `conda` packages so they could be uploaded to [anaconda.org](https://anaconda.org/). This can be done by installing the [`anaconda-client`](https://github.com/Anaconda-Server/anaconda-client) and running `anaconda upload` with the right credentials. Uploads can be done using an API key or user/pass. However, the former should certainly be an option as it allows better access control.

**Comment by jhamman** [comment]
+1

**Comment by BanzaiMan** [comment]
We invite you to write a deployment provider with [dpl](https://github.com/travis-ci/dpl).

**Comment by yoavram** [comment]
I'm currently doing it with this in my package.
Here is a [gist](https://gist.github.com/yoavram/05a3c04ddcf317a517d5) with the relevant code.

**Comment by jakirkham** [comment]
@BanzaiMan, it would kind of require [`miniconda`]( http://conda.pydata.org/miniconda.html ) and [`anaconda-client`]( https://github.com/Anaconda-Server/anaconda-client ) to be there. See ( #4883 ).

**Comment by yoavram** [comment]
See the gist above on how download and install all requirements. Conda-build is also required and jinja2 if versions are parsed from git describe.

**Comment by jakirkham** [comment]
Not really asking for advice, @yoavram. I do this regularly in my builds. If you would like to take a stab at providing a solution, of the sort that @BanzaiMan is asking be my guest. I am hardly a ruby expert.

**Comment by yoavram** [comment]
I see. I'm not even a ruby novice. Maybe the info we provided here will help someone else, though.

**Comment by BanzaiMan** [comment]
Sorry for the delay.

@jakirkham It is possible to install dependencies during the deployment, unless it requires `sudo` (for maximum compatibility).

**Comment by jakirkham** [comment]
Ah, sorry for the long delay @BanzaiMan, having been restructuring my notifications and I think this one got lost in the mix.

So, `conda` lives in any directory the user specifies as does anything it installs. As long as the user picks a sensible location (e.g. their home directory), there is no need for `sudo`.

**Comment by BanzaiMan** [comment]
@jakirkham No worries. If you want some advice, I am more than happy to give it to you. :-)
