### ISSUE TITLE
Defining secret environment variables via settings not working

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#4885]
Providing secret environment variables to Travis CI build in the settings page is not resulting in these variables being defined. Instead, the environment variables appear to be empty.

**Comment by mattyohe** [comment]
@jakirkham is this happening on .com? Definitely not occurring on .org. Tested this here:
https://travis-ci.org/mattyohe/testing-travis#L96

**Comment by jakirkham** [comment]
Interesting, nope this is on `.org`. Well, maybe it is just happening to me, but I disagree that it is not happening.

I have also tried deleting and readding these value to no avail. I have two repos suffering from this exact problem.

**Comment by jakirkham** [comment]
@mattyohe, would you mind testing something in your example? Try deleting a secret environment variable and then readding it with some new value. This is what I did during the security incident on the Sept. 15. Maybe there is an issue with readding environment variables?

**Comment by mattyohe** [comment]
@jakirkham did that via the interface: https://travis-ci.org/#L97 and it worked.

Where's your repo?

**Comment by jakirkham** [comment]
Maybe my repos have some issues then.

This one ( http://github.com/nanshe-org/nanshe/ ) and this one ( https://github.com/jakirkham/splauncher ).

**Comment by mattyohe** [comment]
@jakirkham maybe a link to the issue/line in question? Just looking at your recent builds, GH_TOKEN appears to work, no? Is it one of the others?

**Comment by jakirkham** [comment]
Nah, unfortunately, it is just an empty string.

It tries to push and errors ( https://travis-ci.org/nanshe-org/nanshe/#L3966 ). I had a separate branch on `splauncher` where I verified that this isn't the wrong token, but is in fact an empty string.

**Comment by jakirkham** [comment]
Here is a build from `splauncher` with some details. ( https://travis-ci.org/jakirkham/splauncher/builds/83385969 )

Branch `temp` was based off of the current `master` with only commits necessary to print out some more details and chop down testing time to do some introspection on the VM.

**Comment by mattyohe** [comment]
@jakirkham no clue what's going on, but I'd recommend setting the value from the travis CLI just to rule out browser issues. `travis env set GH_TOKEN <your token>`

or if you want to be secret about that token even in your terminal:
```bash
read -s NEW_TRAVIS_PASS
<enter your password in the empty void>
cd <directory containing the cloned splauncher repo>
travis env set GH_TOKEN $NEW_TRAVIS_PASS
unset NEW_TRAVIS_PASS
```

**Comment by bpinto** [comment]
I had a similar issue, apparently my env var value had a ; on it and was not being escaped correctly. Using the command line I was able to get it to work.

**Comment by jakirkham** [comment]
Sorry for the long delay. Thanks @mattyohe. That seems to fix it.

Also clueless as to the problem. No weird characters in the tokens. Setting them by command line does appear to help.

**Comment by dtantsur** [comment]
Folks, could you please fix this issue or at least document the work around officially? It could save me some grey hair..

**Comment by BanzaiMan** [comment]
@dtantsur Where did you look for information? We try to warn this issue any relevant place; e.g., https://docs.travis-ci.com/user/encryption-keys#Note-on-escaping-certain-symbols, 
![settings_-_banzaiman_travis_production_test_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/23553351/5ecd4710-ffee-11e6-819e-08633f42f64f.png)

The CLI is a notable omission currently.

**Comment by dtantsur** [comment]
Well, I did not see any special characters in my github key. And anyway, it was replaced by an empty string, not just something incorrect.

**Comment by BanzaiMan** [comment]
@dtantsur What github key? I am afraid your problem is unrelated to this issue, then.

**Comment by dtantsur** [comment]
Well, the symptoms seem the same: an environment variable set via travis-ci.org setting pages (as opposed to travis.yml) appears empty.

**Comment by BanzaiMan** [comment]
@dtantsur Do you have an example build log URL? If there is no special character in the secret, this issue does not apply.

**Comment by dtantsur** [comment]
I think this one: https://travis-ci.org/dtantsur/rust-openstack/builds/207344183. Note that in the latest builds I switched to a secret in travis.yml.

**Comment by BanzaiMan** [comment]
@dtantsur Very curious. It does appear that `$GITHUB_API_KEY` is empty. Could you invalidate the API key which was used in https://travis-ci.org/dtantsur/rust-openstack/builds/207344183, and open a new issue along with the plain text value of this old key, so that we can investigate further? Thanks.
