### ISSUE TITLE
node fails running node-gyp rebuild

### ISSUE THREAD

**Issue by OmgImAlexis** [travis-ci/travis-ci#4886]
I don't have any issues running `npm install` on any of my systems including a new version of Ubuntu with the same version of Node, nvm and npm as Travis. It seems to fail running `node-gyp rebuild` for `bcrypt`. So I'm not sure which package is at fault or if it's an issue with Travis itself.

[Here](https://gist.github.com/OmgImAlexis/ffcb44a4c5903ecc9200) are my logs.

**Comment by OmgImAlexis** [comment]
I'm guessing this has to do with the other issue opened https://github.com/travis-ci/travis-ci/issues/4771

**Comment by BanzaiMan** [comment]
Indeed, this is a duplicate.
