### ISSUE TITLE
Undefined page title

### ISSUE THREAD

**Issue by anmonteiro** [travis-ci/travis-ci#4887]
Browser / OS: Chrome 45.0.2454.101 (64-bit) on Mac OS X 10.11

Navigating to my account page (shown below) produces undefined `document.title`

<img width="330" alt="screen shot 2015-10-05 at 21 22 21" src="https://cloud.githubusercontent.com/assets/661909/10290941/4aa4c452-6ba7-11e5-92bf-448ef7416be9.png">

**Comment by joshk** [comment]
Thanks for reporting this issue. We will take a look soon and push out a fix ASAP.

**Comment by BanzaiMan** [comment]
This should be fixed at this point. Please reopen if you continue to see problems. Thanks.
