### ISSUE TITLE
To use the original css and scripts instead of cdn

### ISSUE THREAD

**Issue by Kagamine** [travis-ci/travis-ci#4888]
There is the Great Firewall of China(GFW) in China, and it blocked the fastly cdn, so I cannot access to the travis-ci.org home.

![image](https://cloud.githubusercontent.com/assets/2216750/10308515/c418c0d8-6c68-11e5-8617-986e55acf1a2.png)

![image](https://cloud.githubusercontent.com/assets/2216750/10308565/193463ec-6c69-11e5-9b50-917f9fc96267.png)

**Comment by joshk** [comment]
Can you try this again, our awesome CDN provider just pushed out a fix for this.

**Comment by Kagamine** [comment]
Thanks, it works :smile:
