### ISSUE TITLE
Build is not triggering for my repo

### ISSUE THREAD

**Issue by tusharborolelithium** [travis-ci/travis-ci#4890]
The travis build is not triggering for my repo, even after making any commits. This was working till last week and suddenly stopped working. Can you please help quickly.

**Comment by tusharborolelithium** [comment]
Looks like other services are also not building in my organization repo

**Comment by mattyohe** [comment]
@tusharborolelithium Do you have a link to the repo?

**Comment by BanzaiMan** [comment]
Sorry for the delay. If this is still an issue, email us at support@travis-ci.com along with the details, and we will investigate.

Thank you!
