### ISSUE TITLE
Docker permission denied in travis builds

### ISSUE THREAD

**Issue by achanda** [travis-ci/travis-ci#4891]
I am trying to use docker in a travis build, I keep getting 
```
Failed to stop container 49022978f3a6fa75c552601354677823a40900d82cacf1bd54e8899efbd21e8a: API error (500): Cannot stop container 49022978f3a6fa75c552601354677823a40900d82cacf1bd54e8899efbd21e8a: [8] System error: permission denied
```
How do I get this to work?

**Comment by BanzaiMan** [comment]
Sorry for the delay.

If this is still an issue, email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.

Thanks.

**Comment by joepvd** [comment]
Closing.
