### ISSUE TITLE
Xcode 7.0.1

### ISSUE THREAD

**Issue by mikefinney** [travis-ci/travis-ci#4894]
Would you please support xcode 7.0.1?

I see that when xcode7 is used for the osx_image, it is using the older build.
When I specify osx_image: xcode7.0.1 or try osx_image: xcode701, it does not work.

Looking at the following as an example. I would have expected xcode701 to work if you supported it;http://docs.travis-ci.com/user/build-environment-updates/2014-12-18/  True?   

Thanks!

**Comment by emdantrim** [comment]
Oops, looks like this ticket fell through the cracks! We announced 7.0.1 support: http://blog.travis-ci.com/2015-10-23-xcode-71-701-are-ready/ http://docs.travis-ci.com/user/languages/objective-c/#Xcode-7 . Happy building!
