### ISSUE TITLE
The branch page should not list pull request builds

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#4896]
When displaying the status of the 5 latest builds for a branch, PR builds should not be used. PRs builds are not testing the branch, they are testing code which which may be merged into the branch later. So failing PR builds should not mark the branch as failing.

**Comment by lislis** [comment]
Hey there @stof! 
You are absolutely correct, that was a mistake on my side. I have deployed a fix and the branches does not show PR builds anymore.  
Thanks for reporting!  
![cool beans](http://i.giphy.com/ci0uDcGQtBh0k.gif)
