### ISSUE TITLE
Casher will error if branch has ' in name

### ISSUE THREAD

**Issue by sinthetix** [travis-ci/travis-ci#4901]
This line: https://github.com/travis-ci/casher/blob/50da4d54f9e8231e4a985a455634ef22301a8b38/bin/casher#L57 will fail if the branch has a ' in its name. This causes the cache to fail.

**Comment by nabijaczleweli** [comment]
[Example](https://travis-ci.org/nabijaczleweli/Cpponfiguration/builds/84398357)

**Comment by BanzaiMan** [comment]
It doesn't seem to get to the caching phase when there is a `'` in the name of the branch.

I understand there is a bug, but I suggest avoiding these characters for now.
