### ISSUE TITLE
Enabling Docker breaks mono installation

### ISSUE THREAD

**Issue by funlambda** [travis-ci/travis-ci#4907]
I need to use both mono and docker in one of my builds, but I can't manage to get them both installed on the build host. When I use this .travis.yml:

    language: csharp
    mono:
      - latest

    services:
      - docker

    script:
      - ./build.sh
      - ./push_images.sh

I get this error during mono installation:

    Installing Mono
    Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.y5djX5PsT7 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
    gpg: key D3D831EF: public key "Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>" imported
    gpg: Total number processed: 1
    gpg:               imported: 1  (RSA: 1)
    9.06s0.31sE: Unable to correct problems, you have held broken packages.
    The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .

Mono works fine w/o docker and docker works fine w/o mono, but I can't get them both working together. I also tried adding commands to manually install docker during before_install but that failed when trying to use docker (daemon not found).

Are there any workarounds for this?

**Comment by Joshua-Anderson** [comment]
@funlambda Docker builds use Ubuntu trusty while normal builds use Ubuntu precise. As a result we will need to adjust our mono installation script to take that into account.

/cc @akoeplinger

**Comment by akoeplinger** [comment]
Yeah, I didn't realize Trusty is already broadly available on Travis. It should be pretty easy to adapt our script.

**Comment by akoeplinger** [comment]
@funlambda A fix for this was deployed to production. Can you please test it works now and close this issue? Thanks!

**Comment by funlambda** [comment]
Works as expected now -- thanks!
