### ISSUE TITLE
Mono seems not to be affected by cache: apt.

### ISSUE THREAD

**Issue by OlegJakushkin** [travis-ci/travis-ci#4909]
I have a C# project that is [opensource](https://travis-ci.org/OlegJakushkin/TestSWIG/builds/84589564)  and under mono. I have ```cache: apt``` in my [.travis.yml](https://github.com/OlegJakushkin/TestSWIG/blob/master/.travis.yml). Should it not mean that mono shall be cached?

**Comment by Joshua-Anderson** [comment]
I've never seen the apt cache in use before, but I think it is a network level cache that simmply caches Debian downloads that go through it. @BanzaiMan Does apt caching support custom repositories or only the official Ubuntu ones?

**Comment by BanzaiMan** [comment]
Sorry about the delay. I think this was a misunderstanding about what `cache: apt` did.

It added a local apt cache to .com repositories. It does nothing to cache apt packages. (That is to say, apt packages will need to be downloaded, always.)

We don't do that any more, even for private repositories.
