### ISSUE TITLE
gcc-4.8, g++-4.8, cpp-4.8, gcc-5, g++-5, cpp-5, libsdl2-dev whitelisted but not found

### ISSUE THREAD

**Issue by madebr** [travis-ci/travis-ci#4911]
All packages mentioned in the title are whitelisted on https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise,
but they don't install.
Error:
E: Unable to locate package gcc-4.8
E: Couldn't find any package by regex 'gcc-4.8'
E: Unable to locate package g++-4.8
E: Couldn't find any package by regex 'g++-4.8'
E: Unable to locate package cpp-4.8
E: Couldn't find any package by regex 'cpp-4.8'
E: Unable to locate package libsdl2-dev

See https://travis-ci.org/madebr/OpenJK/jobs/84681943 for the complete output.

**Comment by rabernat** [comment]
I am having the same issue. How was this resolved?
