### ISSUE TITLE
Reduce in number of concurrent jobs for Urho3D open source project

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#4915]
Our project CI used to get 5 concurrent jobs until lately where it seems it always get only maximum 3 concurrent jobs now (even during off peak hours). I have a personal fork of that project and have setup similar CI job matrix on my personal travis CI acccount and I can confirm I still get maximum 5 concurrent jobs. In the https://travis-ci.com/plans, it only says "Fair Use" for Open Source project. I just want to make sure our project is not being penalized because the project has a very active development, i.e. triggering many CI build jobs (though most of our jobs are finished extremely fast due to ccache).

**Comment by BanzaiMan** [comment]
Hello. Is this still a problem? According to our logs, we had a period during which we were running 5 concurrent jobs for urho3d/Urho3D earlier today.

**Comment by weitjong** [comment]
The problem has resolved by itself. Our builds get maximum 5 concurrent jobs as before. You can consider this as case close.
