### ISSUE TITLE
when there is no script step, last environment var is exposed

### ISSUE THREAD

**Issue by muhmuhten** [travis-ci/travis-ci#4917]
This may expose a "secure" variable. Sample of a .travis.yml with this issue:

    language: generic
    
    deploy:
      - provider: script
        script: deploy.sh
        on:
          branch: master

**Comment by BanzaiMan** [comment]
Do you have a more concrete example? I tried https://travis-ci.org/BanzaiMan/travis_production_test/builds/86185321 (with [the corresponding `.travis.yml`](https://github.com/BanzaiMan/travis_production_test/blob/9c4acd306b8eb891808dc2c6e03b740ff9ef278d/.travis.yml)) without any problem.

**Comment by BanzaiMan** [comment]
I see the problem now. Sorry for the confusion there.

**Comment by BanzaiMan** [comment]
This is no longer the case, since we display the `bash` version in `announce`.
