### ISSUE TITLE
Add HTTPS for docs.travis-ci.com

### ISSUE THREAD

**Issue by alex** [travis-ci/travis-ci#4918]

**Comment by Joshua-Anderson** [comment]
The documentation and blog are hosted with github pages, which makes it difficult to support ssl. It can be done with cloudflare's flexible SSL but that's about it.

**Comment by alex** [comment]
Any reverse proxy would do, but indeed.

**Comment by BanzaiMan** [comment]
https://blog.travis-ci.com/2015-11-23-docs-are-now-served-over-ssl
