### ISSUE TITLE
Add a "docker registry" deployment

### ISSUE THREAD

**Issue by alex** [travis-ci/travis-ci#4919]
This could build a docker image, and push it to a registry

**Comment by caarlos0** [comment]
+1

**Comment by patrickpierson** [comment]
+1.  Currently looking for a way to push docker images via travis builds.  Work around is to use legacy travis ci infra to build and push images to registry.

**Comment by joshk** [comment]
We would be happy to accept a PR to https://github.com/travis-ci/dpl which adds a `docker` or `docker-registry` provider.

**Comment by Skilgarriff** [comment]
+1

**Comment by webspinner** [comment]
+1

**Comment by BanzaiMan** [comment]
Closing in favor of https://github.com/travis-ci/dpl/issues/867.
