### ISSUE TITLE
CI job hang after showing this message: There was an error with the connection to the VM.

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#4920]
Worse, the hung CI job need to be canceled or killed manually or otherwise the job would run indefinitely in that state. I have encountered and killed a few of such jobs for the past two days. Never have this kind of problem before.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows this problem?

**Comment by weitjong** [comment]
This problem has also resolved now. Unfortunately I don't have the log URL ready with me and those failed build logs have buried quite deep after a week.

**Comment by BanzaiMan** [comment]
Thanks for the information. If you see the problem resurface, do let us know!
