### ISSUE TITLE
install GNU Multiple Precision Arithmetic Library

### ISSUE THREAD

**Issue by thiloklein** [travis-ci/travis-ci#4921]
The GNU Multiple Precision Arithmetic Library at http://gmplib.org should be installed in the build environment. Otherwise any R package depending on CRAN package gmp fails to build.

See for example: https://api.travis-ci.org/jobs/84698190/log.txt?deansi=true

\* installing *source* package ‘gmp’ ...
\** package ‘gmp’ successfully unpacked and MD5 sums checked
creating cache ./config.cache
checking for __gmpz_ui_sub in -lgmp... no
configure: error: GNU MP not found, or not 4.1.4 or up, see http://gmplib.org
ERROR: configuration failed for package ‘gmp’

**Comment by BanzaiMan** [comment]
Hello there. Is there an Ubuntu package that can be installed? If so, please follow the procedure described in https://github.com/travis-ci/apt-package-whitelist/ to request the package be whitelisted.

Thanks.
