### ISSUE TITLE
ssl certificates issues

### ISSUE THREAD

**Issue by ddtxra** [travis-ci/travis-ci#4922]
Dear team,
We are having some issues to connect to a resource in https.
If we configure travis (in yml file) before script: 
- `wget https://www.nextprot.org -qO -` we get a an exit 5 (exit with 5 ssl verification)

but if we run the same command in our machines or an ubuntu machine on Amazon EC2 it works...
Could you help us to find the cause? A test environment was created here:
- https://travis-ci.org/MatSchaeff/grunt-qunit-seed

**Comment by cotsog** [comment]
Cf. https://secure.helpscout.net/conversation/129666705/20974/

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/builds/195981102 shows that for this particular case, using GCE (with `sudo: required`) or Trusty (with `dist: trusty`) solves the problem, which is probably due to old SSL certificate.
