### ISSUE TITLE
Build created but never started

### ISSUE THREAD

**Issue by moylop260** [travis-ci/travis-ci#4925]
https://travis-ci.org/OCA/pylint-odoo/builds/84748218
2 days with next screen
![pylint-odoo](https://cloud.githubusercontent.com/assets/6644187/10436301/28d20aa8-70eb-11e5-9963-ed2da7c028b4.png)

**Comment by jcrist** [comment]
Same here: https://travis-ci.org/blaze/dask/builds/84969701

![screen shot 2015-10-12 at 2 56 16 pm](https://cloud.githubusercontent.com/assets/2783717/10437253/78eb36bc-70f1-11e5-9609-004f5f37a2c9.png)

Only build in the queue, been queued for 3 hours now. Tried restarting it, but no luck.

**Comment by jcrist** [comment]
Ok, my build has ran now. I assume the build was hung due to some global slowdown, and is an intermittent issue.

**Comment by moylop260** [comment]
I still had the same problem: https://travis-ci.org/OCA/OCA/pylint-odoo/builds/84812186

**Comment by moylop260** [comment]
oh!
Now is working fine!
