### ISSUE TITLE
Build tags for deploy with 'Build pushes' off?

### ISSUE THREAD

**Issue by mattyohe** [travis-ci/travis-ci#4926]
It appears that with the option `Build pushes` set to off, any tags pushed (created via Github releases) do not build.

Is there a way to achieve building of tags for deploy to a Github release but also keep `build pushes` off?

**Comment by BanzaiMan** [comment]
Deployment is restricted to push builds at the moment, so I do not think this is possible.

**Comment by BanzaiMan** [comment]
API builds will fire regardless of this setting, so you can use that.

https://docs.travis-ci.com/user/triggering-builds

![banzaiman_travis_production_test_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/15087506/ef6cd79c-1384-11e6-9c89-04c7dcb7edc4.png)

**Comment by BanzaiMan** [comment]
That is to say, with "Build pushes" disabled:

1. Push tags
1. Fire API build with the payload

    ```json
    {
      "branch": "branch_name_to_deploy"
    }
```
