### ISSUE TITLE
Notification payload: pull_request_number is 0

### ISSUE THREAD

**Issue by inukshuk** [travis-ci/travis-ci#4930]
Hi Travis CI - thanks for a great service!

We have a bot that helps contributors with PRs by posting comments to GitHub on failed builds. This was working fine so far, but recently the `pull_request_number` in the notification payload is always 0 (`type`, `pull_request`, and `pull_request_title` are all set to their correct values).

Do you have any idea what might be causing this?

**Comment by rmzelle** [comment]
I'm pretty sure this is one of the builds with the problem: https://travis-ci.org/citation-style-language/styles/builds/85118272

**Comment by inukshuk** [comment]
Yes. On the build page there is a correct link to the PR (number 1728) but the number in the notification is 0.

**Comment by joshk** [comment]
Thanks for creating the issue. Which notification payload are you referring to? Webhook? Email? IRC?

**Comment by inukshuk** [comment]
It's a webhook notification payload. I should also add that it was working well until recently.

**Comment by joshk** [comment]
@svenfuchs were you able to look into this issue?

**Comment by rmzelle** [comment]
We're seeing this same issue in another repo as well: https://github.com/inukshuk/styles/pull/7#issuecomment-149619834

**Comment by svenfuchs** [comment]
Hmmm, I'm not sure how to reproduce this. I'm seeing this in the console on `travis-hub-production`:

```
build = Build.find(85118272)
>> build.number
=> "5354"
>> Travis::Addons::Serializer::Webhook::Build.new(Build.find(85118272)).data.slice(:pull_request_number, :pull_request_title)
=> {:pull_request_number=>1728, :pull_request_title=>"Shelbot Testing"}
```

Any ideas, @joshk?

**Comment by rmzelle** [comment]
Would it help if we provided a (sanitized) version of one of the webhook notification payloads?

**Comment by joshk** [comment]
That would be great @rmzelle

**Comment by rmzelle** [comment]
@inukshuk, can you pull one up?

**Comment by inukshuk** [comment]
I'm pasting a full notification that we received below. Sadly, we don't have the one @svenfuchs references above, because we had not turned full logging at that point.

The notification below was triggered by [this build](https://travis-ci.org/inukshuk/styles/builds/86405138); notice how it contains the correct [compare_url](https://github.com/inukshuk/styles/pull/7) with the correct issue/PR number 7, but `pull_request_number` is still set to 0.

Let me add, also that this was working without a problem earlier. If it helps, [here is the code](https://github.com/inukshuk/Sheldon/blob/master/lib/sheldon/travis_ci_helper.rb#L22) where we parse the notification and the full notification is pasted below.

Thanks for looking into this!

    {
      "id": 86405138,
      "repository": {
        "id": 2918085,
        "name": "styles",
        "owner_name": "inukshuk",
        "url": "http://citationstyles.org"
      },
      "number": "18",
      "config": {
        "sudo": false,
        "language": "ruby",
        "cache": "bundler",
        "rvm": [
          2.2
        ],
        "notifications": {
          "email": {
            "recipients": [
              "rintze.zelle@gmail.com",
              "karcher@u.northwestern.edu"
            ],
            "on_success": "change",
            "on_failure": "always"
          },
          "webhooks": {
            "urls": [
              "https://shelbot.herokuapp.com/build",
              "https://styles-update.zotero.org:8827/"
            ],
            "on_success": "always",
            "on_failure": "always",
            "on_start": "never"
          }
        },
        ".result": "configured"
      },
      "status": 1,
      "result": 1,
      "status_message": "Broken",
      "result_message": "Broken",
      "started_at": "2015-10-20T14:02:47Z",
      "finished_at": "2015-10-20T14:04:55Z",
      "duration": 128,
      "build_url": "https://travis-ci.org/inukshuk/styles/builds/86405138",
      "commit_id": 24579241,
      "commit": "362d3b88f2ff2017c21ee01ce725e1dbd3ba76f7",
      "base_commit": "5f371db428f26768d6a1d36b51b0ac84828fbfa1",
      "head_commit": "61becdde1a780950853585e3b9284ad2909fe43d",
      "branch": "master",
      "message": "Create validation error",
      "compare_url": "https://github.com/inukshuk/styles/pull/7",
      "committed_at": "2015-10-20T14:02:12Z",
      "author_name": "Rintze M. Zelle",
      "author_email": "rintze.zelle@gmail.com",
      "committer_name": "Rintze M. Zelle",
      "committer_email": "rintze.zelle@gmail.com",
      "matrix": [
        {
          "id": 86405139,
          "repository_id": 2918085,
          "parent_id": 86405138,
          "number": "18.1",
          "state": "finished",
          "config": {
            "sudo": false,
            "language": "ruby",
            "cache": "bundler",
            "rvm": 2.2,
            "notifications": {
              "email": {
                "recipients": [
                  "rintze.zelle@gmail.com",
                  "karcher@u.northwestern.edu"
                ],
                "on_success": "change",
                "on_failure": "always"
              },
              "webhooks": {
                "urls": [
                  "https://shelbot.herokuapp.com/build",
                  "https://styles-update.zotero.org:8827/"
                ],
                "on_success": "always",
                "on_failure": "always",
                "on_start": "never"
              }
            },
            ".result": "configured",
            "os": "linux"
          },
          "status": 1,
          "result": 1,
          "commit": "362d3b88f2ff2017c21ee01ce725e1dbd3ba76f7",
          "branch": "master",
          "message": "Create validation error",
          "compare_url": "https://github.com/inukshuk/styles/pull/7",
          "started_at": "2015-10-20T14:02:47Z",
          "finished_at": "2015-10-20T14:04:55Z",
          "committed_at": "2015-10-20T14:02:12Z",
          "author_name": "Rintze M. Zelle",
          "author_email": "rintze.zelle@gmail.com",
          "committer_name": "Rintze M. Zelle",
          "committer_email": "rintze.zelle@gmail.com",
          "allow_failure": false
        }
      ],
      "type": "pull_request",
      "state": "failed",
      "pull_request": true,
      "pull_request_number": 0,
      "pull_request_title": "Pull request for testing",
      "tag": null
    }

**Comment by svenfuchs** [comment]
Thanks a lot, @inukshuk. I can reproduce the issue with this build id.

```
>> Build.find(86405138).pull_request_number
=> 7
>> Build.find(86405138).commit.pull_request_number
=> 0
```

I have no idea why this would happen, but I believe this should be an easy fix. I'll look into testing on staging, and hopefully deploying to production tomorrow.

**Comment by svenfuchs** [comment]
I have just deployed a fix to production. Could you please re-try? @rmzelle, @inukshuk

**Comment by rmzelle** [comment]
@svenfuchs, yes, that seems to have done the trick! (@inukshuk, see https://github.com/citation-style-language/styles/pull/1741)

**Comment by rmzelle** [comment]
(fixed by https://github.com/travis-ci/travis-hub/pull/47)

**Comment by inukshuk** [comment]
Yes, it looks good. Thanks a lot @svenfuchs

**Comment by svenfuchs** [comment]
Awesome, great to hear. Thanks for the feedback, @rmzelle, @inukshuk

**Comment by rmzelle** [comment]
Thanks! (we love Travis CI, by the way)
