### ISSUE TITLE
Install system Java on OSX

### ISSUE THREAD

**Issue by aviks** [travis-ci/travis-ci#4934]
I have an application that loads the JVM via JNI. On Travis OSX, this causes a message `No Java runtime present, requesting install.` as can be seen here: https://travis-ci.org/aviks/JavaCall.jl/jobs/84890628 or here: https://travis-ci.org/aviks/JDBC.jl/jobs/84886643

Note that my application finds the Oracle 7.0.45 JDK that has been installed on that machine, and successfully `dlopen`'s it, and attempts to initialise the JVM. However, a Oracle Java bug causes it to fail to initialise. Apparently the workaround is to install the system JVM, even though it is not used. 

More info here: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7131356

**Comment by solarce** [comment]
Fixed in more recent image releases.
