### ISSUE TITLE
Commands with updating progress bars kill log files

### ISSUE THREAD

**Issue by scpeters** [travis-ci/travis-ci#4936]
I was having trouble with some builds exceeding the log file size limit of 4 MB, even when it didn't seem like there was that much output. For example, [this build](https://travis-ci.org/osrf/homebrew-simulation/builds/84636939) was terminated with the following error even though it only had 415 lines of terminal output:

~~~
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
~~~

When I downloaded the [raw log file](https://api.travis-ci.org/jobs/84636940/log.txt?deansi=true), I discovered the culprit. I was testing some homebrew formulae, which included a `brew fetch` command that downloads a tarball and verifies that the checksum matches the expected value. That command uses curl without the `--silent` option, which uses a live-updating progress bar. Travis stores every update of this progress bar, here's a short sample:

~~~
#####                                                                      7.3%
#####                                                                      7.3%
#####                                                                      7.4%
#####                                                                      7.4%
#####                                                                      7.4%
#####                                                                      7.4%
#####                                                                      7.4%
#####                                                                      7.4%
#####                                                                      7.5%
#####                                                                      7.5%
#####                                                                      7.5%
#####                                                                      7.5%
~~~

As a workaround, I pipe `brew fetch` to `grep -v '%$'` to filter out the repeated lines.

This might not be considered a bug by the travis-ci developers, but it was unexpected for me, so I wanted to post this in case other users have this same problem.

**Comment by mikemcquaid** [comment]
@xu-cheng and I can take a look at this.

**Comment by mikemcquaid** [comment]
@scpeters Feel free to file any other Homebrewy things to us directly if you like; we will look at them.

**Comment by xu-cheng** [comment]
This is a dupe with https://github.com/Homebrew/homebrew/issues/44446. In short, we should offer env variable and/or a flag to silent curl progress bar.

**Comment by scpeters** [comment]
@mikemcquaid thanks, I didn't want to overburden you.

**Comment by mikemcquaid** [comment]
Fixed by https://github.com/Homebrew/homebrew/pull/45561.

**Comment by scpeters** [comment]
Thanks!
