### ISSUE TITLE
Allows to modify an environment variables set in settings

### ISSUE THREAD

**Issue by jreybert** [travis-ci/travis-ci#4938]
In project settings, an environment can only be set, or deleted.

The new behavior would be:
* user set a variable
* this variable appears in settings and can be modified by the user

For example, it could be used to have an environment variable which enable verbose debug output during integration. This feature ease the verbosity enabling (user doesn't have to remember its variable name

**Comment by mattyohe** [comment]
Why would you have to remember the name? You can add the same variable twice, so just copy the name, paste it into a new field and press add. Delete the old. No?

**Comment by joshk** [comment]
Thanks for the suggestion @jreybert, I would have to agree with @mattyohe on this though. Having env vars in the settings be immutable is preferable.

Could you elaborate why the current delete-then-add-again workflow doesn't work for you?

**Comment by jreybert** [comment]
Actually, I didn't though about this workflow. Indeed, this workflow works very well.

However, I would prefer to be able to change the value: fewer clicks and copy/paste. Anyway, it is just a matter of comfort.

If you think immutable envs are preferable, then you can close this ticket.

**Comment by joshk** [comment]
Thanks for your feedback. We will keep this in mind for the future. I'll close this ticket for now though as we are not likely to change the UX in the near term.

Have a great weekend.
