### ISSUE TITLE
Support for Lua/LuaJIT

### ISSUE THREAD

**Issue by alexsergeyev** [travis-ci/travis-ci#4939]
It's possible to run lua right now as discribed here https://github.com/travis-ci/travis-ci/issues/1307, but it will be great to have native support for that

**Comment by BanzaiMan** [comment]
Thanks for opening this issue. As you point out, we do not support Lua out of the box. If you are interested, we invite you to read http://docs.travis-ci.com/user/languages/community-supported-languages/ and add it as a community-supported language.
