### ISSUE TITLE
Unhelpful behavior for tabs in .travis.yml

### ISSUE THREAD

**Issue by tripleee** [travis-ci/travis-ci#4947]
I had builds failing somewhat spectacularly because my `.travis.yml` contained some tabs instead of spaces.

The [request queue](https://travis-ci.org/tripleee/emacs-snapshot/requests) contains "missing config" for the pushes I attempted during this time; but there was no indication anywhere in the user interface that there was a problem, and I discovered it more or less by accident.

So there are multiple things to fix here;
- When a request fails, display something in the web UI
- When there is a syntax error (or similar) in `.travis.yml`, don't say it's missing
- Ideally, be more lenient with tabs for whitespace; Emacs out of the box will tabify when you indent something beyond seven consecutive leading spaces

Should I submit separate tickets for each problem?

**Comment by BanzaiMan** [comment]
The YAML syntax error issue is #2025. (This is the first 2.)

The last one is really due to the YAML specification, which is picky about white spaces. We cannot be lenient and use a specification-compliant parser.
