### ISSUE TITLE
apt addon doesn't pull in secondary dependencies

### ISSUE THREAD

**Issue by umlaeute** [travis-ci/travis-ci#4949]
i'd like to use the mingw64 cross-compiler, so I added

      addons:
        apt:
          packages:
            - gcc-mingw-w64-i686

Unfortunately, [this fails](https://travis-ci.org/umlaeute/test/jobs/85530842), as `gcc-mingw-w64-i686` depends on `binutils-mingw-w64-i686` which is not automatically installed.

of course it is easy to manually add and 2nd level dependencies to the `.travis.yml`, but why can't this be handled automatically? I guess the call to `apt-get` is missing a `-f`

**Comment by BanzaiMan** [comment]
This is by design, since we do not test secondary dependencies. Please request whitelisting what you need, or move to Trusty, where `sudo` is available.
