### ISSUE TITLE
Travis Abruptly fails on XCodeBuild

### ISSUE THREAD

**Issue by amol-c** [travis-ci/travis-ci#4952]
Problem Definition:
1. xcodebuild abruptly fails while running the test. Everything was working fine until recently.

Please find the last few lines from logs below:

```
    ✓ URL_for_image__should_return_nil_URL_UserstravisbuildTeachersPayTeachersiosUnitTestsTestsViewModelsThumbImageViewModelSpecswift_13 (0.001 seconds)
UIDeviceSpec
    ✓ deviceInfo__should_return_the_correct_string_for_notification_purposes_UserstravisbuildTeachersPayTeachersiosUnitTestsTestsUIDeviceSpecswift_8 (0.002 seconds)
    ✓ modelNameWith__modelCode_is_iPod5_1__should_return_the_correct_model_name_UserstravisbuildTeachersPayTeachersiosUnitTestsTestsUIDeviceSpecswift_16 (0.005 seconds)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated

```

**Comment by cotsog** [comment]
Hey @amol-c,

Sorry for the troubles.

Can you send a link to a build log to support@travis-ci.com for us to investigate?

Thanks!

**Comment by amol-c** [comment]
Hi @cotsog ,
I just sent an email to the email mentioned above. Keeping fingers crossed.

Thanks :)

**Comment by mattyohe** [comment]
Seeing something similar here. Only really started seeing this on Xcode 7.1. Possibly related to #4913 ?
Will send logs to support.
