### ISSUE TITLE
Travis build is passing despite Karma reporting failed tests

### ISSUE THREAD

**Issue by karrde00** [travis-ci/travis-ci#4953]
When using travis with Jasmine, Karma and gulp. Tests are showing as failed yet the build is still passing. I've linked copies of my travis.yml and the log from travis. What do I need to do in order to get the build to fail as per expected when jasmine/karma reports a failing test?

<img width="375" alt="screen shot 2015-10-15 at 1 35 39 pm" src="https://cloud.githubusercontent.com/assets/2541223/10523753/a761187a-7341-11e5-8523-f6bb9c8cede4.png">

<img width="749" alt="screen shot 2015-10-15 at 1 32 56 pm" src="https://cloud.githubusercontent.com/assets/2541223/10523699/5be686f0-7341-11e5-82b0-483ce8258f93.png">

**Comment by karrde00** [comment]
Found the issue was with how I had karma runner setup. Needed to make the system end with the correct exit code on server run.

**Comment by joshk** [comment]
Great to hear, can this issue be closed?

**Comment by karrde00** [comment]
Yes this can be closed now. Thanks
