### ISSUE TITLE
Can't install whitelisted Xvfb package, because of capital letter

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#4954]
I've the following config in my `.travis.yml` file:

	sudo: required
	addons:
	  apt:
	    packages:
	    - Xvfb      # X virtual framebuffer.

and it fails with:

> Disallowing packages: Xvfb

error, despite `xvfb` is on the [whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise).

I think the apt-get package names should be case insensitive.

Is it something to fix?

Or requesting to whitelist it at travis-ci/apt-package-whitelist/issues/1402 is enough?

**Comment by BanzaiMan** [comment]
Why are you using the capital letter?

**Comment by kenorb** [comment]
@BanzaiMan Probably for no real reason, so I've found this problem by accident as using `apt-get install Xvfb` normally it works. This is actually the popular [case convention](https://en.wikipedia.org/wiki/Xvfb) (e.g. used in Wikipedia) and binary it-self it's `Xvfb`.

**Comment by BanzaiMan** [comment]
The package name is `xvfb` (http://packages.ubuntu.com/precise/xvfb), so it is a good idea to stick with that. It _might_ be safe to normalize, but I can't say that this is true for all Debian packages.

Is it OK to close this?

**Comment by kenorb** [comment]
That's fine, works for me.
