### ISSUE TITLE
Can't listed different version of whitelisted wine package.

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#4955]
I'm using `sudo` environment and I'm installing `wine` in the following way:

	sudo: required
	addons:
	  apt:
	    packages:
	    - wine1.7

However the [build fails](https://api.travis-ci.org/jobs/85602233/log.txt) with:

> Disallowing packages: wine1.7

despite being on the [whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise).

Is it something to improve, or requesting it for whitelisting at  travis-ci/apt-package-whitelist/issues/1401 is enough?

**Comment by BanzaiMan** [comment]
Sorry, but `wine1.7` is not listed. A package with that name does not exist for Precise (http://packages.ubuntu.com/search?keywords=wine&searchon=names).
