### ISSUE TITLE
sudo apt-get causing: E: Invalid operation

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#4956]
What's wrong with [this build](https://travis-ci.org/EA31337/EA31337/EA31337-Sets/builds/85615423)?

	$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes xvfb xdotool winbind wine1.7 realpath
	E: Invalid operation xvfb
	The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes xvfb xdotool winbind wine1.7 realpath"
    failed and exited with 100 during .

Without `-yq` the same thing (without additional info).

`Invalid operation` usually happens on typos (see [Ask Ubuntu](http://askubuntu.com/q/521855/78223)), but the syntax seems fine for me.

**Comment by solarce** [comment]
@kenorb you need to give `apt-get` a command to run, https://travis-ci.org/EA31337/EA31337-Sets/builds/85615423#L1082 only gives it a list of package names.

So `sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes xvfb xdotool winbind wine1.7 realpath` 

should be `sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install xvfb xdotool winbind wine1.7 realpath`, adding **`install`** after **`--force-yes`**

**Comment by kenorb** [comment]
Sorry, I'm blind:) Too many parameters.

**Comment by solarce** [comment]
No worries, happy to help!
