### ISSUE TITLE
Julia: should release point to 0.4 version?

### ISSUE THREAD

**Issue by felipenoris** [travis-ci/travis-ci#4958]
cc @tkelman, @staticfloat
```
julia:
    - release
    - nightly
```

**Comment by felipenoris** [comment]
Also, Julia build is failing on nightly OSX.
https://travis-ci.org/felipenoris/InterestRates.jl/jobs/85723423

**Comment by tkelman** [comment]
Yes, the stable link at status.julialang.org needs to be changed to point to 0.4-latest. The latter is Homebrew.jl being broken on nightly. Neither are really Travis issues.

**Comment by felipenoris** [comment]
Thank you, @tkelman.

**Comment by tkelman** [comment]
status.julialang.org is fixed so `release` now points to 0.4-latest

**Comment by felipenoris** [comment]
awesome!
