### ISSUE TITLE
iOS 8 simulators not available with `osx_image: xcode7`

### ISSUE THREAD

**Issue by kgn** [travis-ci/travis-ci#4962]
The documentation [here](http://docs.travis-ci.com/user/languages/objective-c/#Xcode-7) says that simulators for `iOS 8.1-9.0` are available with `osx_image: xcode7`, but I am seeing failures when trying to use any of the `iOS 8` simulators:

```
language: objective-c
osx_image: xcode7

env:
  matrix:
    - SDK=iphonesimulator8.1
    - SDK=iphonesimulator8.2
    - SDK=iphonesimulator8.3
    - SDK=iphonesimulator8.4
    - SDK=iphonesimulator9.0
```

But the builds are failing and I don't see these simulators available in the list of simulators printed in the error:

```
ERROR: SDK 'iphonesimulator8.1' doesn't exist.  
Possible SDKs include: iphonesimulator,
iphonesimulator9.0, 
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator2.0.sdk, 
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS2.0.sdk,
iphoneos9.0, 
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk,
watchsimulator2.0,
macosx10.11,
machos,
watch simulator,
iphoneos, 
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk,
watchos2.0,
watchos, 
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk
```

**Comment by kgn** [comment]
Looking around I think I found a solution. It seems that building is done with one sdk, but then testing can be done on multiple destinations. Is this correct?

```
  matrix:
    - DESTINATION="OS=9.0,name=iPad 2"
    - DESTINATION="OS=9.0,name=iPhone 6"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"

    - DESTINATION="OS=8.1,name=iPad 2"
    - DESTINATION="OS=8.2,name=iPhone 4s"
    - DESTINATION="OS=8.3,name=iPhone 5"
    - DESTINATION="OS=8.4,name=iPhone 5s"

script: 
  - xctool clean test -project "$PROJECT.xcodeproj" -scheme "$SCHEME" -sdk iphonesimulator -destination "$DESTINATION"
```

**Comment by tamastimar** [comment]
Possibly connected with #5001.

**Comment by henrikhodne** [comment]
Your second comment is correct. There's only one SDK available (Apple removed the ability to download older SDKs a few Xcode versions ago), but all simulators ("destinations") that can be downloaded through Xcode should be available. For older SDKs you need to use an older version of Xcode.

**Comment by kgn** [comment]
Is there a way to define the version of Xcode in a matrix?

**Comment by jcanizales** [comment]
I'd love the ability to do that too. We're trying to support iOS versions 7.1 +, but none of the `osx_image` has 7 and 9 available together.

**Comment by Lyoness** [comment]
Hello! 

I'm closing out old issues.  

Is there a way to define the version of Xcode in a matrix? You can try 

```
matrix:
  include:
  - os: osx
    osx_image: xcode6.4
  - os: osx
    osx_image: xcode7
  - os: osx
    osx_image: xcode8
  - os: osx
    osx_image: xcode8.3
  - os: osx
    osx_image: xcode9
  - os: osx
    osx_image: xcode9.1
  - os: osx
    osx_image: xcode9.2
```
