### ISSUE TITLE
No IPv6 support in Trusty VM

### ISSUE THREAD

**Issue by DarthGandalf** [travis-ci/travis-ci#4964]
I have a test which listens on `::1`, and then connects to itself.
I don't need external IPv6 connectivity, as opposed to #3302

http://docs.travis-ci.com/user/ci-environment/#Networking puts OSX and Trusty to single bucket "do not currently have IPv6 connectivity", but `::1` works fine on OSX and on legacy Precise (the one with sudo).

Some related logs:
```
socket(PF_INET6, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
setsockopt(3, SOL_SOCKET, SO_OOBINLINE, [1], 4) = 0
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
bind(3, {sa_family=AF_INET6, sin6_port=htons(6667), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 EADDRNOTAVAIL (Cannot assign requested address)
```

```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP group default qlen 1000
    link/ether 42:01:0a:f0:00:02 brd ff:ff:ff:ff:ff:ff
    inet 10.240.0.2/32 brd 10.240.0.2 scope global eth0
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:7a:6e:24:c5 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
4: lxcbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether 92:83:46:70:16:a2 brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.1/24 brd 10.0.3.255 scope global lxcbr0
       valid_lft forever preferred_lft forever
```

**Comment by waja** [comment]
@DarthGandalf Maybe this is related to https://github.com/travis-ci/travis-ci/issues/4978 ?

**Comment by Mikaela** [comment]
It's not, because that issue says that IPv6 related entries should be removed while this issue is about IPv6 being supposed to exist.

> http://docs.travis-ci.com/user/ci-environment/#Networking puts OSX and Trusty to single bucket "do not currently have IPv6 connectivity", but ::1 works fine on OSX and on legacy Precise (the one with sudo).

**Comment by DarthGandalf** [comment]
@waja this is related to #4978, yes. If they add `::1` to interface `lo`, both these issues will be fixed, because `localhost` will resolve to correct addresses again.
However, there is an easier fix for #4978, to just delete `::1` from `/etc/hosts`, as you did for workaround. That doesn't fix my issue because I want to use IPv6.
For now, I'm using `127.0.0.1` instead of `::1`

P.S. instead of `grep foo | wc -l` you can use `grep -c foo`, but as you just want to check whether it's found there or not at all, check of return value of grep would be enough: `ip addr show | grep "inet6 ::1" || sudo sed -i ...`

**Comment by ldemailly** [comment]
This blocks me too for WDT
(and right now, I can't connect to cmake.org on the old container because of certificate and can't run my tests on trusty because ::1 doesn't work... so kinda stuck)

https://travis-ci.org/facebook/wdt/builds

**Comment by ldemailly** [comment]
I tried to fix it myself with 
$ sudo ifconfig lo add ::1/128 
but got :
SIOCSIFADDR: Permission denied
despite sudo

what is the technical (or otherwise) reason for not having ipv6 on the loopback at least ?

**Comment by BanzaiMan** [comment]
https://code.google.com/p/google-compute-engine/issues/detail?id=8 indicates that it is not yet available.

**Comment by solarce** [comment]
I understanding this may be disappointing, but I can tell you that having IPv6 has been a by-product of where we've been hosting precise before, but it's not something we consider a core feature that we support in Travis CI at this time and it will go away as we migrate away from that hosting platform. 

Unfortunately, the major public cloud providers do not provide any supported methods for having internal IPv6 connectivity nor are there any real options for in-bound IPv6 external connectivity in a way that is usable for Travis's build environments, so we're limited by what is supported on the providers which give us the best economies of scale and overall feature sets we need.
