### ISSUE TITLE
DNS Failures on OSX

### ISSUE THREAD

**Issue by ariscop** [travis-ci/travis-ci#4965]
Job [84714781](https://travis-ci.org/Elemental-IRCd/elemental-ircd/jobs/84714781) for example

**Comment by henrikhodne** [comment]
Thank you for opening this, I'm looking into it now.

**Comment by henrikhodne** [comment]
I just pushed a fix and I am no longer able to reproduce this. Could you try restarting the job and see if the clone works now?

**Comment by ariscop** [comment]
Seems to be fixed

**Comment by ariscop** [comment]
Working as expected, thanks :)

**Comment by henrikhodne** [comment]
Thank you for verifying! Sorry again for this, it was an error in our network configuration that had snuck in when we were working to resolve the previous incident.
