### ISSUE TITLE
travis-build hardcodes the Ruby version used for dpl

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#4969]
The hardcoded Ruby version used for `dpl` is not installed on our Trusty images. Assuming this version will change over time, should we switch to using `rvm default` (or whatever gives the default ruby)?

https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/deploy/script.rb#L10
https://secure.helpscout.net/conversation/130894214/21160/

**Comment by BanzaiMan** [comment]
We have an internal logic to pick a reasonable version of Ruby to run deployment now.
