### ISSUE TITLE
postgres / postgis job stalls after outputting (END)

### ISSUE THREAD

**Issue by mprins** [travis-ci/travis-ci#4970]
I have a project that stalls (and then times out) during `before_install` phase. In essence it sets up two databases, one with postgis and the tries to load some data. However before it gets to loading the data the build stalls after outputting `(END)` in the log, actuall after executing `psql -U postgres --list`.

  - stalled build: https://travis-ci.org/B3Partners/brmo/builds/85877293
  - project .travis.yml: https://github.com/B3Partners/brmo/blob/travis-integration/.travis.yml

#4618 talk about a similar problem but does not talk about a solution, 
 also put this on [stackoverflow](https://stackoverflow.com/questions/33175655/job-stalls-with-end)

**Comment by BanzaiMan** [comment]
The raw output is:

```
[0K$ psql -U postgres --list
[?1049h[?1h=
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileg es   
-----------+----------+----------+-------------+-------------+------------------ -----
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 rsgb      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 staging   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres           +
           |          |          |             |             | postgres=CTc/post gres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres           +
           |          |          |             |             | postgres=CTc/post gres
 travis    | travis   | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
(6 rows)

[7m(END)[27m[K
```

The command I believe is failing is:

`psql -U postgres -d rsgb -f ./datamodel/generated_scripts/datamodel_postgresql.sql --echo-all`

Does the content in this SQL file explain how this might hang?

**Comment by mprins** [comment]
that file is about 1.7Mb, we use it all the time though; the next two are much bigger, do you think it's just timing out loading the schema and data?

I tried adding the -a (echo all) option to the psql command to no avail: https://travis-ci.org/B3Partners/brmo/builds/86250153 (no output)

Then tried to disable those 2 of those 3 sql scripts and add some directory listing in beween; but it seems to hang up after the `psql -U postgres --list` command and not get to the ls command after... or the processing of the datamodel_postgresql.sql file

```
  - psql --version
  - psql -U postgres -c 'create database staging;'
  - psql -U postgres -c 'create database rsgb;'
  - psql -U postgres -d rsgb -c 'create extension postgis;'
  - psql -U postgres --list
  - ls -l ./datamodel/generated_scripts/
```
https://travis-ci.org/B3Partners/brmo/builds/86253970

**Comment by mprins** [comment]
so then I disabled the `psql -U postgres --list` command and it start running the `datamodel_postgresql.sql`  for a bit and then outputs `(END)` but actually before the end of the file is reached, see: https://travis-ci.org/B3Partners/brmo/builds/86256451

to me it seems like something is hanging up the connection

**Comment by mprins** [comment]
this seems to have been resolved, not clear if using `travis_wait` is the solution

**Comment by ctaggart** [comment]
I'm not sure what resolved it for you, but I simply set the environment variable of `PAGER=cat` to stop the paging. That solved it for me. I posted that answer to http://stackoverflow.com/a/36192894/23059.
