### ISSUE TITLE
travis-build env vars containing a pipe break

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#4971]
It seems the way we set env vars breaks when the value contains a pipe/vertical bar.

I haven't tried to reproduce this, but I guess this should be considered a bug.

https://secure.helpscout.net/conversation/131195067/21220/

**Comment by BanzaiMan** [comment]
We do not escape variables so that users can have

    FOO=$(cmd -a -r -g -s)

We have a note in http://docs.travis-ci.com/user/environment-variables/:

> Notice that the values are not escaped when your builds are executed. Special characters (for bash) should be escaped accordingly.

The placement currently makes it read like this note applies only to the environment variables set on the Settings page, which I believe is not true. We should fix that.

**Comment by BanzaiMan** [comment]
Closing in favor of #1775.
