### ISSUE TITLE
Pushover notification no longer works

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4972]
https://github.com/travis-ci/travis-tasks/pull/28#issuecomment-149310767

This is most likely due to incompatible SSL cipher. See http://updates.pushover.net/post/126918128857/api-upcoming-upgrade-to-sha256-ssl-certificate

**Comment by BanzaiMan** [comment]
I have updated JRuby to 1.7.22 on travis-tasks in the hopes of adding more SSL ciphers. Currently, the following ciphers are available:

AES-128-CBC AES-128-CFB AES-128-CFB8 AES-128-ECB AES-128-OFB AES-192-CBC AES-192-CFB AES-192-CFB8 AES-192-ECB AES-192-OFB AES-256-CBC AES-256-CFB AES-256-CFB8 AES-256-ECB AES-256-OFB AES128 AES192 AES256 BF BF-CBC BF-CFB BF-CFB8 BF-ECB BF-OFB CAMELLIA-128-CBC CAMELLIA-128-CFB CAMELLIA-128-CFB8 CAMELLIA-128-ECB CAMELLIA-128-OFB CAMELLIA-192-CBC CAMELLIA-192-CFB CAMELLIA-192-CFB8 CAMELLIA-192-ECB CAMELLIA-192-OFB CAMELLIA-256-CBC CAMELLIA-256-CFB CAMELLIA-256-CFB8 CAMELLIA-256-ECB CAMELLIA-256-OFB CAMELLIA128 CAMELLIA192 CAMELLIA256 CAST CAST-CBC CAST5-CBC CAST5-CFB CAST5-CFB8 CAST5-ECB CAST5-OFB CAST6-CBC CAST6-CFB CAST6-CFB8 CAST6-ECB CAST6-OFB DES DES-CBC DES-CFB DES-CFB8 DES-ECB DES-EDE DES-EDE-CBC DES-EDE-CFB DES-EDE-OFB DES-EDE3 DES-EDE3-CBC DES-EDE3-CFB DES-EDE3-CFB8 DES-EDE3-ECB DES-EDE3-OFB DES-OFB DES3 RC2 RC2-40-CBC RC2-64-CBC RC2-CBC RC2-CFB RC2-CFB8 RC2-ECB RC2-OFB RC4 RC4-40 SEED SEED-CBC SEED-CFB SEED-CFB8 SEED-ECB SEED-OFB

Note that SHA256 ciphers are still not available, and the notification continues to fail:
```
Oct 21 17:36:43 travis-tasks app/tasks.2:  I type=pushover build=86672462 repo=digsjs/digs-dev uuid= time=0.271 jid=5099b5d08415f9fadbbde6d6 
Oct 21 17:36:44 travis-tasks app/tasks.2:  I Error connecting to Pushover service for token REDACTED user REDACTED: Could not generate DH keypair
```

See also: https://www.openssl.org/docs/manmaster/apps/ciphers.html

**Comment by BanzaiMan** [comment]
I contacted Pushover for assistance. I will update this ticket if I hear from them.

**Comment by jamestalmage** [comment]
What JDK?

**Comment by jcs** [comment]
(Pushover developer here)

Is this applicable to your servers? http://stackoverflow.com/questions/6851461/java-why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception

**Comment by jamestalmage** [comment]
@jcs That was my suspicion. I would guess that JRuby relies on the ciphers available on the underlying JVM, so bumping the JDK might have more of an impact than bumping JRuby.

**Comment by jamestalmage** [comment]
This comment shows promise: https://github.com/jruby/jruby/issues/2872#issuecomment-97295776

as well as the following one.

**Comment by jamestalmage** [comment]
I have verified this is caused due to running on an old JVM:

code:
```ruby
# test.rb
require "net/https"

url = URI.parse("https://api.pushover.net/1/messages.json")
req = Net::HTTP::Post.new(url.path)
req.set_form_data({
                      :token => "REDACTED",
                      :user => "REDACTED",
                      :message => "hello world",
                  })
res = Net::HTTP.new(url.host, url.port)
res.use_ssl = true
res.verify_mode = OpenSSL::SSL::VERIFY_PEER
res.start {|http| http.request(req) }
```

Using java 1.6
```sh
$  jruby --version
jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on Java HotSpot(TM) 64-Bit Server VM 1.6.0_65-b14-466.1-11M4716 +jit [darwin-x86_64]

$ jruby test.rb
Handshaker.java:1012:in `checkThrown': java.lang.RuntimeException: Could not generate DH keypair
....
```

Using java 1.8
```sh 
$ jruby --version
jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 +jit [darwin-x86_64]

$ jruby test.rb
# no output, and I get the notification
```

**Comment by jamestalmage** [comment]
Updating the code as follows allows it to run in java 1.7 (it will not run in java 1.6 regardless). 

```ruby
#test.rb
require 'java'

java.security.Security.setProperty("jdk.tls.disabledAlgorithms", "SSLv3, DHE")

require "net/https"

url = URI.parse("https://api.pushover.net/1/messages.json")
req = Net::HTTP::Post.new(url.path)
req.set_form_data({
                      :token => "REDACTED",
                      :user => "REDACTED",
                      :message => "hello world",
                  })
res = Net::HTTP.new(url.host, url.port)
res.use_ssl = true
res.verify_mode = OpenSSL::SSL::VERIFY_PEER
res.start {|http| http.request(req) }
```

I am not sure what implications disabling the `DHE` algorithm would have on other parts of the system. It seems the easy solution is to upgrade to java1.8

@BanzaiMan The question remains - what version of the JDK does travis use for it's servers.

**Comment by jamestalmage** [comment]
https://github.com/travis-ci/travis-tasks/issues/40

All the tests pass if you bump to JDK 1.8

**Comment by BanzaiMan** [comment]
@jamestalmage Thanks for the information. Moving to Java 8 is not a small undertaking, so we'll have to plan it more carefully.

**Comment by jamestalmage** [comment]
Disabling `DHE` is also a viable option. 

> In short, probably the best long-term move is to switch to elliptic curves (ECDHE) as soon as possible.
>
>  - http://blog.cryptographyengineering.com/

@BanzaiMan: `DHE` can be disabled on the client (travis server) side as follows:

```ruby
require 'java'

java.security.Security.setProperty("jdk.tls.disabledAlgorithms", "SSLv3, DHE")
```

It is highly unlikely any of the official notification services supported by Travis do not have `ECDHE` enabled. The only potential downside would be custom `webhook` notifiers with endpoints that only support `DHE`. You should not feel too bad about breaking that though, since you are forcing them to move to newer safer standards.

@jcs 

When your service launching in 2012, `ECDHE` was already widely supported. I think it is VERY unlikely you have clients that do not support it. Perhaps you should consider disabling `DHE` on your end (or at least experiment with that option).

**Comment by jamestalmage** [comment]
Doesn't look like disabling DHE forces ECDHE.

jvm | DHE disabled | success | negotiated cipher
-----|--------------------|-------------|------------------------
1.7 | no                   | no           | SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA
1.7 | yes                 | yes          | SSL_RSA_WITH_3DES_EDE_CBC_SHA
1.8 | no                   | yes          | SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA

That may be less desirable from a security standpoint.

Table above generated using my sample code from earlier and:

```
$ jruby -J-Djavax.net.debug=all test.rb | grep Session
```

**Comment by jantman** [comment]
I haven't been doing any work on Travis-tested repos for the past 2 weeks or so, but just made some commits to one of my projects and notifications are flowing through again as of this evening. Not sure if anything was changed or not, but it appears to be working again.

**Comment by Mikaela** [comment]
Same with https://github.com/travis-ci/travis-ci/issues/5093 (ircs) which was having the same error message.

**Comment by BanzaiMan** [comment]
We made changes to the app responsible for notifications. The Pushover notification might be working again. Could any of you test it?

**Comment by jantman** [comment]
I can confirm that this build https://travis-ci.org/jantman/awslimitchecker/builds/92914347 notified me via pushover _just now_, almost immediately when it finished.

**Comment by BanzaiMan** [comment]
Super. I'm closing this now.
