### ISSUE TITLE
[GitHub Releases Uploading] 401 - Bad credentials on deploy

### ISSUE THREAD

**Issue by Arnotjevleesch** [travis-ci/travis-ci#4973]
Hi,

I am trying to deploy a file on GitHub Release following http://docs.travis-ci.com/user/deployment/releases/  

I have experimented the three to do it with CLI :
- Generate api_key with travis setup releases
- Encrypt a token generated by GitHub
- Encypt my GitHub passwork

but I meet every time the error "401 - Bad credentials on deploy" :
https://travis-ci.org/Arnotjevleesch/Arnotes/builds/86017816

Could you help me?

My GitHub repo : https://github.com/Arnotjevleesch/Arnotes

Thank a lot

**Comment by BanzaiMan** [comment]
Hello. What do you mean by "Encrypt a token generated by GitHub"? Could you show the commands you ran on your machine?

**Comment by Arnotjevleesch** [comment]
Hello,

First, thank for the fast answer!

I mean the three ways to generate the deploy part of .travis.yml :
- travis setup releases
- travis encrypt <personal token generated by GitHub> --add deploy.api-key
- travis encrypt <GitHub password> --add deploy.password

**Comment by BanzaiMan** [comment]
I don't think the API key was successfully encrypted. Could you retry with:

```
travis encrypt -r Arnotjevleesch/Arnotes --org
```

and give the token on STDIN?

**Comment by Arnotjevleesch** [comment]
You are absolutely right!
It seems to be the repo forcing with -r that solve the problem :
I had noticed that, when I used travis setup releases, CLI proposed to me to deploy in Arnotjevleesch/arnotes (with a little a)
Have you any clue about this kind of issue?

**Comment by cotsog** [comment]
@Arnotjevleesch, regarding:

> Arnotjevleesch/arnotes (with a lower case 'a')

Is it possible that you renamed this repo and its first name was with a lower case 'a'?

**Comment by Arnotjevleesch** [comment]
@cotsog you must be right, I did not want my module name was the same as the repo.
I will think about that when I reset my repo because of the too many commit I have about travis deployment ;)
I close, thanks a lot to everyone!
