### ISSUE TITLE
Bug report: Getting many 'broken' emails

### ISSUE THREAD

**Issue by evert** [travis-ci/travis-ci#4975]
I noticed when my build breaks I now get 8 distinct notification emails. When it's fixed again, I get just one. This looks like a bug. Could it have to do something with the `fast_finish` option?

* [My project](https://github.com/fruux/sabre-dav/)
* [A failed build that triggered 8 emails](https://travis-ci.org/fruux/sabre-dav/builds/86319684)

**Comment by joshk** [comment]
There is a bug with `fast_finish` which we have not been able to look into yet. I would recommend removing it for the time being.

**Comment by evert** [comment]
Turning off fast_finish did indeed fix my problem.

**Comment by Croydon** [comment]
See also #4928 and #4988.

**Comment by joshk** [comment]
Closing as this is a duplicate of #4928
