### ISSUE TITLE
Notifications are sent to commit author who does not have write access to repository

### ISSUE THREAD

**Issue by andrewnicols** [travis-ci/travis-ci#4976]
I have a fork of Moodle on my GitHub repository, and I have been trying to get travis-ci.org integration working. All has been going well.

One of my colleagues was trying out my changes on his fork of Moodle. We both have Travis-CI integrated with our own _personal_ forks of Moodle. I do not have write-access to his fork, and he does not have write-access to my fork. They are public repositories so we both have read-access to one-another's code.

However, when I cherry-pick one of his commits, and I push a branch with that commit to my fork, and that commit generates a notification, we have seen that both he and I receive notifications.

According to http://docs.travis-ci.com/user/notifications/#How-is-the-build-email-receiver-determined%3F:
```By default, a build email is sent to the committer and the author, but only if they have access to the repository the commit was pushed to. This prevents forks active on Travis CI from notifying the upstream repository’s owners when they’re pushing any upstream changes to their fork.```

In this case:
* the repository was https://github.com/andrewnicols/moodle/tree/MDL-51458-master-break
* andrewnicols (me) was the committer
* andrewnicols has push access to the repository
* danpoltawski was the commit author
* danpoltawski does *not* have push access to the repository
* the build was https://travis-ci.org/andrewnicols/moodle/builds/86314338

From my understanding, although danpoltawski was the commit author, since he does *not* have commit access to my repository, he should not receive the e-mail notification.

**Comment by joshk** [comment]
Thank you for creating this issue.

This has been a regression with how we send emails. We have found the code which needs to be changed and will look into this ASAP.

Sorry for the extra emails, and thank you once more for the detail you have provided.

**Comment by joshk** [comment]
We have a fix ready and will deploy it shortly.

**Comment by mudrd8mz** [comment]
Has this been fixed in prod?

**Comment by joshk** [comment]
Ah, thanks for reminding me, yes, it has been fixed and deployed to production around 3 weeks ago.

Closing :tada:
