### ISSUE TITLE
Looking for Transifex(localisation tool) integration with Travis

### ISSUE THREAD

**Issue by niccs** [travis-ci/travis-ci#4981]
I am looking for integrating Transifex (localization tool) with our application, to have latest translations files pulled before doing a build, and we are following travis build. Is there something available??

Something inline with:--

A Sinatra server that integrates Transifex with GitHub:-- https://github.com/transifex/txgh
or
This is Jenkins way to use Transifex client :- http://docs.transifex.com/integrations/jenkins/

**Comment by meatballhat** [comment]
This here?
https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/transifex.rb

**Comment by niccs** [comment]
Great :-).. Do you have some documentation? Still not sure how to include this in .travis.yml for android app.

**Comment by tooomm** [comment]
@niccs did you managed to find out for yourself or did @meatballhat came back to you?

**Comment by niccs** [comment]
None of the above :-) That development part is still on hold for us.
