### ISSUE TITLE
GHC 7.10 support

### ISSUE THREAD

**Issue by liamoc** [travis-ci/travis-ci#4982]
Hi Travis, 

Issue #3785 is still not resolved, and Haskell users have not able to use the latest GHC version for many months. Can GHC 7.10 support be added soon?

**Comment by solarce** [comment]
I've posted an update on the original issue.

**Comment by nh2** [comment]
@solarce It is now over 9 months since the original request, and the original issue is still locked, so we cannot ask questions there.

Is there any ETA?

**Comment by wildlyinaccurate** [comment]
Is there any update on this? The https://github.com/hvr/multi-ghc-travis solution is fine but first-class support for GHC >7.8 would be great.
