### ISSUE TITLE
Manually-triggered builds do not start when "Build Pushes" is disabled

### ISSUE THREAD

**Issue by ndahlquist** [travis-ci/travis-ci#4983]
Steps to reproduce:
1. Disable the "Build Pushes" option.
2. Follow the instructions at http://docs.travis-ci.com/user/triggering-builds/ to trigger a build via the API.

Observed behavior:
No build is triggered. If I re-enable the "Build Pushes" option, the instructions work as expected.

Even if this is not patched, it would be nice to add a note to that page to save other developers the trouble. Thank you for your help!

**Comment by ndahlquist** [comment]
In case other sorry souls should happen upon this issue, here is my hacky workaround:

```bash
# Enable pushes
body='{
  "settings": {
    "build_pushes": true
  }
}'
curl -s -X PATCH \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Authorization: token $API_TOKEN" \
  -d "$body" \
  https://api.travis-ci.com/repos/408768/settings

# Trigger build
body='{
"request": {
  "message": "Override the commit message: this is an api request",
  "branch":"master"
  }
}'
curl -s -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Travis-API-Version: 3" \
  -H "Authorization: token $API_TOKEN" \
  -d "$body" \
  https://api.travis-ci.com/repo/Snapchat%2Fandroid/requests

# Disable pushes
body='{
  "settings": {
    "build_pushes": false
  }
}'
curl -s -X PATCH \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Authorization: token $API_TOKEN" \
  -d "$body" \
  https://api.travis-ci.com/repos/408768/settings
```

**Comment by joshk** [comment]
Thank you for reporting the issue. We will take a look at this and let you know what we find.

**Comment by carlad** [comment]
Hi ndahlquist,

As a quick update, we have just deployed a fix to this issue.

We actually had a bug in place that prevented API build requests from being accepted when "Build pushes" was turned off via repository settings.

This should now be fixed.

Again, thanks a lot for reporting the issue.

Have an amazing day!

**Comment by ndahlquist** [comment]
Thank you for the fix! :+1:

**Comment by ObjectiveTruth** [comment]
Still seems to be an issue. API kept giving a `500` status code

Turned back **on** Build Pushes and worked instantly
