### ISSUE TITLE
Trusty Beta: RVM unable to install ruby 1.8.7

### ISSUE THREAD

**Issue by agis-** [travis-ci/travis-ci#4984]
It seems ruby 1.8.7 can't be installed (w/ RVM) in the new Trusty environment (mega image): https://travis-ci.org/bundler/bundler/jobs/86492969.

Any insights?

Thanks in advance.

**Comment by joshk** [comment]
Hmmmm, 1.8.7 EOL was several years ago, but I can talk to the team and see what we can do.

cc @solarce

**Comment by agis-** [comment]
Awesome, thanks!

**Comment by agis-** [comment]
Hey, any news on this one?

Thanks.

**Comment by BanzaiMan** [comment]
The issue appears to be that the binary we built is not statically linked. It is linked to `libruby.so.1.8`, which *appears* to be available when we built the archive, but not when we run it on Trusty.

**Comment by BanzaiMan** [comment]
I looked at this in more detail, but I couldn't figure out how to resolve this issue cleanly.

I have confirmed, however, that `1.8.7-head` works, so use that instead.

**Comment by BanzaiMan** [comment]
Well, that was incorrect. After a bit of trial and error, I've found that the current Trusty image does not have certain RVM-related files. There is a hacky way to get around it (one that sets Ruby version to something other than 1.8.7), but I'm not yet sure what the real cause is, and how best to resolve it.

**Comment by BanzaiMan** [comment]
I did a little more digging, and I think this can be fixed by https://github.com/travis-ci/travis-build/pull/619. Tested on staging: https://staging.travis-ci.org/BanzaiMan/bundler/jobs/483303.

**Comment by BanzaiMan** [comment]
The fix mentioned above has been deployed to production. Could you try it? You can retry an old failing build, or push a new commit.

**Comment by segiddins** [comment]
-> https://travis-ci.org/bundler/bundler/builds/108427168

**Comment by BanzaiMan** [comment]
Hmm. That didn't work?

**Comment by BanzaiMan** [comment]
ah. `1.8.7` still has a problem, but `1.8.7-head` is OK. I'll try re-packaging `1.8.7`.

**Comment by BanzaiMan** [comment]
@segiddins Hmmm. I cannot get RVM to package `1.8.7`. Could you specify `1.8.7-head` instead and try again?

**Comment by sodabrew** [comment]
Same issue still present. Will try the 1.8.7-head workaround.
```
10.31s$ rvm use 1.8.7 --install --binary --fuzzy
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
ruby-1.8.7 is not installed - installing.
Searching for binary rubies, this might take some time.
Found remote file https://s3.amazonaws.com/travis-rubies/binaries/ubuntu/14.04/x86_64/ruby-1.8.7.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
ruby-1.8.7 - #configure
ruby-1.8.7 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2560k  100 2560k    0     0  3020k      0 --:--:-- --:--:-- --:--:-- 3019k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-1.8.7 - #validate archive
ruby-1.8.7 - #extract
ruby-1.8.7 - #validate binary
Libraries missing for ruby-1.8.7: libruby.so.1.8. Refer to your system manual for installing libraries
Mounting remote ruby failed with status 10, stopping installation.
Gemset '' does not exist, 'rvm ruby-1.8.7 do rvm gemset create ' first, or append '--create'.
```

**Comment by sodabrew** [comment]
Using 1.8.7-head does not resolve the problem:
```
9.16s$ rvm use 1.8.7-head --install --binary --fuzzy
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
ruby-1.8.7-head is not installed - installing.
Searching for binary rubies, this might take some time.
Found remote file https://s3.amazonaws.com/travis-rubies/binaries/ubuntu/14.04/x86_64/ruby-1.8.7-head.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
ruby-1.8.7-head - #configure
ruby-1.8.7-head - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2560k  100 2560k    0     0  2263k      0  0:00:01  0:00:01 --:--:-- 2264k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-1.8.7-head - #validate archive
ruby-1.8.7-head - #extract
ruby-1.8.7-head - #validate binary
Libraries missing for ruby-1.8.7-head: libruby.so.1.8. Refer to your system manual for installing libraries
Mounting remote ruby failed with status 10, stopping installation.
Gemset '' does not exist, 'rvm ruby-1.8.7-head do rvm gemset create ' first, or append '--create'.
The command "rvm use 1.8.7-head --install --binary --fuzzy" failed and exited with 2 during .
```

**Comment by BanzaiMan** [comment]
I'm sorry, but I am at my wits end to make this happen. Can you stay with Precise for 1.8.7?

**Comment by sodabrew** [comment]
Is it possible to mix Precise and Trusty in the same matrix?

**Comment by solarce** [comment]
@sodabrew yes, this is possible with a matrix like:

``` yaml

language: ruby

matrix:
  include:
  - sudo: false
    env: SUDO=false PLATFORM=precise
  - sudo: required
    dist: precise
    env: SUDO=true PLATFORM=precise
  - sudo: required
    dist: trusty
    env: SUDO=true PLATFORM=trusty

script:
  - uname -a
  - true

```

See this [.travis.yml](https://github.com/solarce/mixed-test/blob/ed1cd86f68e1be65530c15529a23e14eaeb67c76/.travis.yml) and this [build](https://travis-ci.org/solarce/mixed-test/builds/111923405)

**Comment by sodabrew** [comment]
Thanks! Then yes, I will stick to Trusty and call it a day for 1.8.7 :)

**Comment by segiddins** [comment]
@BanzaiMan has this been fixed?

**Comment by BanzaiMan** [comment]
@segiddins I don't think we can spend much more time on this issue. Sorry. Use Precise for 1.8.7, please.
