### ISSUE TITLE
New branches view slow to load & scroll

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#4985]
Viewing https://travis-ci.org/mozilla/treeherder/branches in Firefox Nightly can be quite slow to both load and then scroll once loaded. The list of branches is also pretty unwieldy.

Would it be possible to hide the inactive branches under a "show all" / "show inactive" toggle, so the rest load (and render) faster?

Thanks :-)

**Comment by joshk** [comment]
Thanks for the feature suggestion.

We are looking at adding this in the near future, but I don't have an ETA sorry.

**Comment by edmorley** [comment]
Thank you :-)

**Comment by BanzaiMan** [comment]
Is this still an issue?

**Comment by edmorley** [comment]
The page appears to both load and scroll faster than before, though there are still deleted 12 month old branches shown, that would be nice to hide under a "show inactive branches" toggle or similar.

However happy to close this out if you prefer :-)
