### ISSUE TITLE
Multiple IRC build reports for single build

### ISSUE THREAD

**Issue by headius** [travis-ci/travis-ci#4988]
In the past few days we've started to get multiple IRC notifications for a single build, and it's clogging up the channel.

https://www.dropbox.com/s/gjrhqbxub6v5dfq/Screenshot%202015-10-21%2010.10.08.png?dl=0

For now I will need to silence travis in #jruby but we'd appreciate having someone investigate this issue.

**Comment by joshk** [comment]
hey @headius, are you using `fast_finish` by chance?

**Comment by eregon** [comment]
@joshk Yes

**Comment by joshk** [comment]
please remove that for the time being, we have a bug with that feature which we will look into fixing soon.

**Comment by Croydon** [comment]
This issue still floods our IRC channel. Any progress so far?

**Comment by joshk** [comment]
Closing as this is a duplicate of #4928
