### ISSUE TITLE
Trusty beta: Inconsistent Python versions / confusing UX

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#4989]
I have a WIP branch to migrate a container-infra `.travis.yml` to using Trusty, so we can work around https://github.com/travis-ci/apt-package-whitelist/issues/1206#issuecomment-149884653 .

In the existing [.travis.yml](https://github.com/mozilla/treeherder/blob/master/.travis.yml) file I have:

``` yml
python:
  - "2.7"
```

The docs (http://docs.travis-ci.com/user/trusty-ci-environment/#Runtimes) don't mention whether they honour this existing Python version (in setting the default version) or whether there was a virtualenv created or not, but a first attempt to pip install (via peep) whilst not using sudo, resulted in
`OSError: [Errno 13] Permission denied: '/opt/python/2.7.10/lib/python2.7/site-packages/gunicorn'`
(https://travis-ci.org/mozilla/treeherder/builds/86624847#L475)
...so (a) it's v2.7.10, and (b) there's obviously not a virtualenv activated.

I thought I should just be able to use sudo whilst peep installing (wrapper around pip to enforce hashes, https://github.com/erikrose/peep), however now suddenly peep fails, since the pip version is different (too new for peep).

Looking closer:

``` bash
$ python --version
Python 2.7.10
$ sudo python --version
Python 2.7.6
$ pip --version
pip 6.1.1 from /opt/python/2.7.10/lib/python2.7/site-packages (python 2.7)
$ sudo pip --version
pip 7.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

(https://travis-ci.org/mozilla/treeherder/builds/86639592#L137)
...which presumably means pyenv isn't working when I'm using sudo? (I didn't invoke pyenv myself, but presume it's done as part of the image setup, given I have python 2.7 listed in my .travis.yml)

Ok, let's try creating a virtualenv instead of using sudo:

``` bash
$ virtualenv $HOME/virtualenv
New python executable in /home/travis/virtualenv/bin/python
Installing setuptools, pip, wheel...done.
$ source $HOME/virtualenv/bin/activate
$ python --version
Python 2.7.6
```

(https://travis-ci.org/mozilla/treeherder/builds/86639592#L145)
So virtualenv must have been installed with the system python, not 2.7.10, which is not what I want.

So maybe I should be using the virtualenv plugin with pyenv then - in case it works better? However it's not installed:

``` bash
$ pyenv virtualenv 2.7.10 $HOME/virtualenv
pyenv: no such command `virtualenv'
The command "pyenv virtualenv 2.7.10 $HOME/virtualenv" failed and exited with 1 during .
```

(https://travis-ci.org/mozilla/treeherder/builds/86633246)

Whilst I could fix the above by using the `--python` option to virtualenv to specify the Python 2.7.10 binary, or say use `--user` with pip (presuming peep supports it too), it would be great if the experience was more consistent out of the box.

Would it be possible to:
1) Indicate in the docs whether the trusty beta honours the python version specified under `python:` in .travis.yml, since at the moment it's not clear.
2) Make the version of Python given for both `python --version` and `sudo python --version` consistent, and also make virtualenv use that same version too.

Thanks :-)

**Comment by lekshmideepu** [comment]
Currently, Trusty Beta is available as two images, [minimal and mega:]
(http://docs.travis-ci.com/user/trusty-ci-environment/#Image-differences-from-Precise)

![screen shot 2015-11-01 at 21 36 53](https://cloud.githubusercontent.com/assets/7138338/10871208/cf07e956-80e0-11e5-9f7e-eea263fe246e.png)
![screen shot 2015-11-01 at 21 37 24](https://cloud.githubusercontent.com/assets/7138338/10871209/cf088d0c-80e0-11e5-8416-f14c2a8cbbed.png)
Package versions are consistent in **minimal** when compared to **mega**
![screen shot 2015-11-01 at 21 41 16](https://cloud.githubusercontent.com/assets/7138338/10871244/ccac3f30-80e1-11e5-8dc4-d286638d7511.png)
![screen shot 2015-11-01 at 21 42 00](https://cloud.githubusercontent.com/assets/7138338/10871245/ccb072c6-80e1-11e5-9002-09d9cdbf115f.png)

For the time being, it is good to use the **minimal** image by setting the **language : generic** in .travis.yml file.

**Comment by BanzaiMan** [comment]
Could this be a `$PATH` issue that I described in #5326?

**Comment by edmorley** [comment]
> Could this be a $PATH issue that I described in #5326?

Sorry for the delay in replying. Yeah I imagine that's quite likely.

Since the OP, our `.travis.yml` no longer uses `--user` with pip (looking at the git log, I see it occurred inadvertently in a refactor), but yet nothing broke, strangely. eg:
https://travis-ci.org/mozilla/treeherder/jobs/111483795#L231
https://github.com/mozilla/treeherder/blob/ee2dd677b9ceee8ccbf44064145a991d6f76fa0d/.travis.yml

However since the OP, we've also started specifying `python: "2.7.11"` rather than `python: "2.7"`, so perhaps the Travis "install python" step is adding the new Python version to the start of `PATH`, thereby working around the issue in a different way?

I'm happy to dupe this to #5326 if you believe it to be the cause.

Many thanks :-)
