### ISSUE TITLE
python 3.5 and 3.6 are not pre-installed

### ISSUE THREAD

**Issue by jhamman** [travis-ci/travis-ci#4990]
Builds using `python: "3.5"` are getting this log message:

```
3.5 is not installed; attempting download
```

This is just takes a bit of time to download and install.  It would be good to include by default.

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. We are planning to have Python 3.5.x available out of the box for the next update. For the time being, this time is necessary.

**Comment by jhamman** [comment]
Yup - sounds good.  Thanks.

**Comment by elopio** [comment]
Our jobs fail when we try to use 3.5. It's not just slower. Here's the output:

3.5 is not installed; attempting download
[...]
Setting environment variables from .travis.yml
$ export TEST_SUITE=unit
$ source ~/virtualenv/python3.5_with_system_site_packages/bin/activate
/home/travis/build.sh: line 45: /home/travis/virtualenv/python3.5_with_system_site_packages/bin/activate: No such file or directory
The command "source ~/virtualenv/python3.5_with_system_site_packages/bin/activate" failed and exited with 1 during .

https://travis-ci.org/ubuntu-core/snapcraft/jobs/97160325

**Comment by BanzaiMan** [comment]
@elopio There is no 3.5 with system site packages.

**Comment by elopio** [comment]
@BanzaiMan, and that's a bug, right?

**Comment by BanzaiMan** [comment]
No, it's not. We do not support that configuration.

**Comment by elopio** [comment]
@BanzaiMan how do I request this to be supported?

**Comment by BanzaiMan** [comment]
@elopio I don't think we can, since Ubuntu (neither Precise nor Trusty) has that package.

**Comment by jhamman** [comment]
@elopio - just use `miniconda`.  You can install python3.5 on travis that way. 

http://conda.pydata.org/docs/travis.html

**Comment by nsoranzo** [comment]
I think this can be closed according to: https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against

**Comment by chrisspen** [comment]
I'm getting this error over a year later. If 3.5 isn't supported, why is it listed as an option in the docs?

https://docs.travis-ci.com/user/languages/python/

**Comment by chrisspen** [comment]
This error went away went I added this to the beginning of my `install` section:

    - sudo apt-key update
    - sudo apt-get update -q
    - sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade
    - sudo apt-get -y install build-essential
    - sudo apt-get -y --force-yes install linux-headers-`uname -r`
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

**Comment by nschloe** [comment]
@BanzaiMan The documention [here](https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against) needs an overhaul to remove Python version from 3.5 onwards.

**Comment by BanzaiMan** [comment]
@nschloe We are open to suggestions! Please open a PR (or an issue) for https://github.com/travis-ci/docs-travis-ci-com.

**Comment by shish** [comment]
Now that 3.6 is stable (and 3.5 has been for a while), can they be added to the base images? I'd also like this for a different reason -- I'm using the image from quay.io to build a travis-compatible python3.5-opencv package, and I'm not sure that my python3.5 setup is identical to yours.

(This is what I'm doing to build a "fake travis-python+3.5" image: http://stackoverflow.com/questions/41635824/travis-docker-image-missing-python-3-5 )

**Comment by bittner** [comment]
@BanzaiMan I'm not getting it: Are you going to add Python 3.5 and 3.6 to the Python base images, or not? Technically, this isn't a problem, is it? ([pyenv](https://github.com/pyenv/pyenv) and others to your rescue)

It's a real pain, because

- Python 3.6 is not available on the python:3.5 image, and
- Python 3.5 in turn is not available on the python:3.6 image,

all the other versions are.

See [build #66](https://travis-ci.org/painless-software/painless-continuous-delivery/builds/221821408) and [build #67](https://travis-ci.org/painless-software/painless-continuous-delivery/builds/221830911) of our painless-continuous-delivery project for reference.

**Comment by bittner** [comment]
@travisci Any feedback? What are your plans re Python?

**Comment by zschmidt** [comment]
Does anyone have a workaround for this? Is there some sort of caching that could be done? 

It seems like the method with creating a new Docker image with python3 would be the ticket, but it's huge overkill for my task...

I've tried pulling python3 in with pip and then caching pip, but that doesn't work. Python is admittedly not my main language, so I don't particularly know my way around it...

**Comment by BanzaiMan** [comment]
@bittner 
It is not clear to me what you mean by:
> Python 3.5 in turn is not available on the python:3.6 image

Python 3.5 is pre-installed on all our build images. If you want to test with both 3.6 and 3.5 on the same image, set `python: 3.6`, and switch between 3.5 and 3.6 using virtualenv.

```yaml
python: '3.6'
before_install: # or any other customizable place
  - source ~/virtualenv/python3.5/bin/activate
⋮ # rest
```

See https://travis-ci.org/BanzaiMan/travis_production_test/jobs/226155301 for an example build.

**Comment by bittner** [comment]
@BanzaiMan virtualenv? Then this should work with tox out of the box, right? But it doesn't.

Can you take a look at the builds [I mentioned above](https://github.com/travis-ci/travis-ci/issues/4990#issuecomment-293982655), and try to make tox work on the Python images? Tox uses virtualenv under the hood, and it works for all versions up until Python 3.5, but it's broken for the rest.

Having to switch "manually" using virtualenv as you propose is not going to make Python users happy who care about common best practices.  :confused:

**Comment by BanzaiMan** [comment]
I don't know how `tox` works its magic, so I can't comment on why it fails the way it does. As I mentioned above, `source …` should work. Since it isn't in your case, I would guess that this is not what `tox` does.

**Comment by adamchainz** [comment]
`tox` needs the command `python3.5` to be resolvable

**Comment by BanzaiMan** [comment]
Then `source …` before invoking `tox` should suffice.

**Comment by nschloe** [comment]
For anyone as desperate for a more recent software stack, check out [CircleCI 2.0] with its docker support (https://circleci.com/docs/2.0/) (currently in beta, but working well for all I know). I've switched some weeks ago for a handful of projects and haven't looked back. With `ubuntu:17.04` as base image, you'll get Python 3.5.

**Comment by bittner** [comment]
@BanzaiMan Is this so hard to understand? Python 2.7 through 3.5 are all resolvable as `pythonx.y` on a `python:3.5` image, `python3.6` is not. This is called a bug (a.k.a. a missing interpreter) in Python land when you want to run tox.

Can you please try to find out why your new setup differs from the older ones? Ask yourself, why is `python3.6` not simply resolvable, without having to explicitly opt in into a virtualenv?

Please note that this is not "just about me". And @adamchainz. And @nschloe. And @zschmidt. And the [behave-django](https://github.com/behave/behave-django) project. The missing Python 3.6 (and flaky 3.5) support is troubling for the whole Python eco system. At least for the open source projects that rely on Travis for running their tests (against several versions of Python, using tox).

**Comment by adamchainz** [comment]
Agree, I've got about 20 projects testing on Python 3.6 only because they can't get a python 3.5 binary running under tox in the same image.

**Comment by BanzaiMan** [comment]
If you got the impression that we think there is no issue to address, I apologize. There is.

Please do recognize, however, that the issue is best addressed by updating the build images, when they have 3.6 pre-installed, and that I am trying to present you with a workaround while we wait for such update.

As indicated before, we want to use a build image that has 3.5 pre-installed, and specify `python: '3.6'`, so that it gets installed on the fly. (I said earlier that 3.5 is pre-installed on all images, but this is not true for Precise container image.)

So, for example, this configuration

```yaml
python: '3.6'
dist: trusty
sudo: false

before_install:
  - if [[ $TOXENV = py35 && -f ~/virtualenv/python3.5/bin/activate ]]; then source ~/virtualenv/python3.5/bin/activate; fi
⋮
```

would make `python` to point to the version 3.5 exactly when `TOXENV` is set to `py35`, while making Python 3.6 available everywhere else.

This incurs some additional cost of installing Python 3.6 everywhere, which is not ideal. This cost can be overcome by using `sudo: required`, but I suspect the boot time for this case would be more than offset by the time you would spend installing Python 3.6 everywhere.

**Comment by bittner** [comment]
@BanzaiMan Any progress on fixing this issue? Do you know how to proceed, or are you open to suggestions? ([miniconda ](http://conda.pydata.org/docs/travis.html) and [pyenv](https://github.com/pyenv/pyenv) have been mentioned above)

What is your route, your roadmap, the ETA for a fix? We need to know! Please, tell us!

**Comment by bittner** [comment]
@BanzaiMan Your proposed workaround is unfortunately flawed for PyPy. See [Travis job #230009854](https://travis-ci.org/painless-software/painless-continuous-delivery/jobs/230009854). PyPy works on `precise`, but not on `trusty`.

Hence, we need a definite fix asap. The workaround is limited.

**Comment by BanzaiMan** [comment]
Thanks for testing. For a complete fix that covers all of 3.5, 3.6 and PyPy, we need a build image update. As I said before, that needs a little more time.

**Comment by bittner** [comment]
Has there been any progress on this issue?

@BanzaiMan, can you give an estimation for "needs a little more time"? An ETA would be helpful.

**Comment by bittner** [comment]
Any progress, @BanzaiMan? The builds are still failing as almost two months ago.

**Comment by BanzaiMan** [comment]
Trusty GCE images should now have Python 3.5 and 3.6 pre-installed.

```yaml
sudo: required
dist: trusty
```

**Comment by bittner** [comment]
This looks good! All the [builds are passing](https://travis-ci.org/painless-software/painless-continuous-delivery/builds/247285239), for Python 2.7, 3.4, 3.5, 3.6 and PyPy. Thanks! :+1:

**Comment by ionelmc** [comment]
@BanzaiMan note that latest trusty image don't have pypy. Only `deprecated-2017Q2` seems to have 'em all.

**Comment by benjaoming** [comment]
@BanzaiMan awesome, thanks!

Quick note: You need to add `python: 3.6` to the config, too.

**Comment by ssbarnea** [comment]
As of today python3.6 is installed but the python3.6 executable is not installed, making it useless for tox. See https://travis-ci.org/pypa/virtualenv/jobs/283366066

**Comment by benjaoming** [comment]
@ssbarnea 
Your log says:

> `ERROR: unknown environment 'python3.6'`

That's not because of a missing executable, but because of a missing environment, hence `TOXENV=python3.6` instructs Tox to use an undefined env. Check your `tox.ini`

**Comment by ssbarnea** [comment]
@benjaoming Sorry it was a PEBKAC kind of issue ;)  I forgot to update the `tox.ini`. Travis works quite fine now, thanks!

**Comment by gauravv7** [comment]
I had a similar issue, python3.5 in travis image is there, so interpreter is found but it is not executable, i.e. my virtualenv by tox cannot run/find it.
tried trust/xenial distros, even tried apt-get update( @chrisspen  comment above) but didn't worked well.
finally added apt-get install python3.5(from deadsnake) in travis conf. worked well.
guess distros here doesn't have running python > 3.4
PS: till py34 everything works well.

**Comment by mushkevych** [comment]
I have a similar issue using matrix where Python 3.5 and 3.6 could not be found.
I tried including links to the Travis VirtEnv, but it did not worked. 
Now, I am trying to install the python3.5 and python3.6 like this:
```
    - python: "3.5"
      env: PYTHON_BINARY="python3.5"
      addons:
        apt:
          packages:
          # Travis-ci has a known issue with Python3.5 and 3.6
          - python3=3.5*
          - python3-setuptools
          - python3-dev
```

but only to this error:
```
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install python3=3.5* python3-setuptools python3-dev" failed and exited with 100 during .
```

any thoughts?

**Comment by gauravv7** [comment]
Try using deadsnakes repo.. I remember installing python but it couldn't install from the official source(some installation error).

Take ref from here
https://github.com/asyncee/django-easy-select2/blob/master/.travis.yml

**Comment by bittner** [comment]
@mushkevych Post your original matrix attempt for Python 3.5 and 3.6, and we can give hints to make it work. What you posted looks very hacky, don't go this direction. The simpler the better.

**Comment by mushkevych** [comment]
@bittner please find the `.travis.yml` file here: https://github.com/mushkevych/scheduler/blob/2.0/.travis.yml

Failing Travis-CI jobs could be found here: https://travis-ci.org/mushkevych/scheduler/builds/331669995

My project provides its own Python virtual environment and has to deactivate one from travis-ci.
Hence, I am defining python binary (for instance: `PYTHON_BINARY="python3.6"`) and use it later like this: `${PYTHON_BINARY} launch.py install`

**Comment by mushkevych** [comment]
@gauravv7 thank you. specifying the `deadsnakes` in apt sources allowed to install Python3.5 and Python3.6
Unfortunately, `easy_install-3.5` and `easy_install-3.6` were reported as `pyenv: easy_install-3.6: command not found` while I was able to successfully call it in a debug build.

In summary I disabled the Python3.5 and 3.6 as it was taking me too much time. I guess bitbucket->pipelines could be an alternative.

**Comment by gauravv7** [comment]
@mushkevych happy to help :)
call me crazy :D but I saw ppa error for python3.6 and somehow the official ppa is not executable at travis docker images which they use.
Not only bitbucket, but any pipeline would work, since travis has not updated I think [researched it abit in my own happenings - https://github.com/asyncee/django-easy-select2/pull/36]
Let me know if I can be of any help further :) Happy programming!

**Comment by Borda** [comment]
hello, do you have an idea why package `python3.5` cannot be found - `E: Unable to locate package python3.5`, see [build](https://travis-ci.org/SuperElastix/SuperElastix/jobs/379509513)

**Comment by BanzaiMan** [comment]
@Borda You are using `apt`. Trusty doesn’t have a `pyhton3.5` package. https://packages.ubuntu.com/trusty/web/python3.5

**Comment by Borda** [comment]
ok, and how can I get python 3.5 there because the default 3.4 does not build `pandas`

**Comment by BanzaiMan** [comment]
@Borda Please read out Python document. https://docs.travis-ci.com/user/languages/python

**Comment by gauravv7** [comment]
@borda take reference from here https://github.com/asyncee/django-easy-select2/blob/master/.travis.yml

**Comment by Borda** [comment]
I know this, but can I also use C++ compilation along with python?

**Comment by gauravv7** [comment]
Yes you can, for c++ packages to build I assume you are using gnu compilers and using c libraries, you would need to install them first and then make the build.
You would probably proceed the build to include such package in your python script(test or usual) for which you should do it before your env building in tox. 

Take reference from here 
https://djw8605.github.io/2016/05/03/building-centos-packages-on-travisci/

Let me know if it works or if I can help by any means :)

**Comment by Borda** [comment]
@gauravv7 thanks, for now, I postponed my issue, I removed pandas and then it is fine to use default python3.4 ... I will have look later on that

**Comment by gauravv7** [comment]
another work around I had to use to manually install multiple python versions, 
https://github.com/asyncee/django-easy-select2/pull/63/commits/93305a4c08e0262589bcf8ffd27ee167f55a61f5

all approach tested here - https://github.com/asyncee/django-easy-select2/pull/63
