### ISSUE TITLE
A container-based job does not complete even if all scripts are done

### ISSUE THREAD

**Issue by Atry** [travis-ci/travis-ci#4991]
https://travis-ci.org/ThoughtWorksInc/json-stream/jobs/86659498

**Comment by BanzaiMan** [comment]
Could you elaborate? That job finished successfully.

**Comment by Atry** [comment]
I guess it is due to a network error on https://travis-ci.org/ThoughtWorksInc/json-stream/builds/86659463 page. It shows as the job is running for more than 10 hours.

The page become complete right now.
