### ISSUE TITLE
Set pre-release for Github releases deploy

### ISSUE THREAD

**Issue by filfat** [travis-ci/travis-ci#4993]
It would be great if we could set the Github releases deployment to preleases.
Maybe something like

    ...
    deploy:
      provider: releases
      pre-release: true
      ...
    ...

Cheers

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. There is a preexisting discussion over at https://github.com/travis-ci/dpl/issues/234, so let us use that ticket instead.
