### ISSUE TITLE
Trusty beta: Add support for dependency/directory caching

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#4997]
We've had to switch our open-source project from the container infra to the [Trusty beta](http://docs.travis-ci.com/user/trusty-ci-environment/) to work around #1986 (since we cannot use the apt whitelist feature due to https://github.com/travis-ci/apt-package-whitelist/issues/1206#issuecomment-149884653).

Unfortunately this means we also lose support for dependency caching, resulting in a 3 minute increase in the setup time for each job (previously it was < 10 seconds).

I know the Trusty beta is still a WIP, but I couldn't find a ticket for adding support for caching, so thought I'd create one.

Thanks :-)

**Comment by joshk** [comment]
Thanks for creating the ticket.

We have this on our direct roadmap but I don't have an ETA sorry.

**Comment by edmorley** [comment]
No problem - many thanks :-)

**Comment by XhmikosR** [comment]
Are there any news about this? We need java 8 in Bootstrap and the easiest solution was to use the trusty image. But without caching, builds have been a lot slower. :/

**Comment by patlola** [comment]
@joshk @edmorley any update on this ?

**Comment by BanzaiMan** [comment]
We are working on this. Getting close to general availability, but no ETA just quite yet.

**Comment by BanzaiMan** [comment]
https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone

It's available now!
