### ISSUE TITLE
error finding package  xunit.runner.dnx

### ISSUE THREAD

**Issue by surlakew** [travis-ci/travis-ci#4998]
@joshua-anderson
 @akoeplinger
 @nterry
I'm seeing an error ( Error: FindPackagesById: xunit.runner.dnx ) when trying to build an asp.net 5 project with xunit test project.

**Comment by BanzaiMan** [comment]
Hello. Instead of pasting the log, could you paste the build log URL? That'll save a lot of scrolling.

**Comment by surlakew** [comment]
Sorry, here it is. 
https://s3.amazonaws.com/archive.travis-ci.org/jobs/86834032/log.txt

**Comment by akoeplinger** [comment]
@surlakew you're using the ancient k stuff according to:
```
Installing to /home/travis/.k/runtimes/kre-mono.1.0.0-beta3
Adding /home/travis/.k/runtimes/kre-mono.1.0.0-beta3/bin to process PATH
Setting alias 'default' to 'kre-mono.1.0.0-beta3'
```

You should try using the current aspnet5/DNX beta8 bits instead.

**Comment by mgolois** [comment]
@surlakew 
you can use my example, mine is working: https://raw.githubusercontent.com/mgolois/DivineChMS/master/.travis.yml
