### ISSUE TITLE
Virtual machine inside travis

### ISSUE THREAD

**Issue by luqasz** [travis-ci/travis-ci#5005]
Hi

I would like to run a virtual machine inside travis to test my application. This machine is a propertiary router and I need network access to it. I could use qemu-user but i need root access to setup custom networking stuff. Any idea how I can achieve my goal ?

**Comment by solarce** [comment]
Unfortunately, we do not currently support any nested full virtualization options. 

The closest we support is running stuff in [Docker containers inside a build](http://docs.travis-ci.com/user/docker/), but I do not think that would be sufficient for the use case you've described.

You could potentially create a Digital Ocean droplet, which does support nested virtualization via KVM, as part of the build and run your router image there, but that would, of course, involve some costs on your part for each build.
