### ISSUE TITLE
trusty, python, pip: setuptools must be installed to install from a source distribution

### ISSUE THREAD

**Issue by nschloe** [travis-ci/travis-ci#5006]
Builds that use `pip install` and succeeded a week ago now fail with
```
setuptools must be installed to install from a source distribution
```
See, e.g., https://travis-ci.org/nschloe/matplotlib2tikz/builds/86041955.

In more detail, it's the following that fails
```
$ python -c "import setuptools"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/virtualenv/python3.4_with_system_site_packages/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>
    from setuptools.extension import Extension
  File "/home/travis/virtualenv/python3.4_with_system_site_packages/lib/python3.4/site-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/home/travis/virtualenv/python3.4_with_system_site_packages/lib/python3.4/site-packages/setuptools/dist.py", line 18, in <module>
    from setuptools import windows_support
  File "/home/travis/virtualenv/python3.4_with_system_site_packages/lib/python3.4/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/lib/python3.4/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: /home/travis/virtualenv/python3.4_with_system_site_packages/lib/python3.4/lib-dynload/_ctypes.cpython-34m-x86_64-linux-gnu.so: undefined symbol: _PyTraceback_Add
```
(from https://travis-ci.org/nschloe/matplotlib2tikz/builds/87418012).

**Comment by nschloe** [comment]
@xavfernandez [suggests](https://github.com/pypa/pip/issues/2931):

> From my understanding of the venv/lib/python3.4/lib-dynload/_ctypes.cpython-34m-x86_64-linux-gnu.so: undefined symbol: _PyTraceback_Add issue, this happened after a minor upgrade of the distribution provide python 3.4.
Your venv contains symlinks to the standard library located in /usr/lib/python3.4 but a copy of the interpreter.
>
> During the python upgrade, the symlinked standard library was updated but not the copied interpreter, making them incompatibles. A possible solution is to replace your venv python (located in path/to/your/venv/bin/python3.4) by the one from your system (/usr/bin/python3.4), a simple cp /usr/bin/python3.4 path/to/your/venv/bin/python3.4 should do it.
>
> An other, even simpler, solution is to destroy and recreate your venv from scratch :)

**Comment by BanzaiMan** [comment]
Could you confirm that jobs with non-system package Python (e.g., python: '3.5.0') does not exhibit this problem?

**Comment by nschloe** [comment]
Python 3.5.0 don't even start:
```
3.5.0 is not installed; attempting download
git.checkout
$ git clone --depth=50 --branch=clean-output https://github.com/nschloe/matplotlib2tikz.git nschloe/matplotlib2tikz
Cloning into 'nschloe/matplotlib2tikz'...
remote: Counting objects: 804, done.
remote: Compressing objects: 100% (325/325), done.
remote: Total 804 (delta 518), reused 741 (delta 468), pack-reused 0
Receiving objects: 100% (804/804), 639.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (518/518), done.
Checking connectivity... done.
$ cd nschloe/matplotlib2tikz
$ git checkout -qf 6b090e57a8ebb63714d59ba1e2440fcd5fad6d72
$ source ~/virtualenv/python3.5.0_with_system_site_packages/bin/activate
/home/travis/build.sh: line 41: /home/travis/virtualenv/python3.5.0_with_system_site_packages/bin/activate: No such file or directory
The command "source ~/virtualenv/python3.5.0_with_system_site_packages/bin/activate" failed and exited with 1 during .
```
See https://travis-ci.org/nschloe/matplotlib2tikz/builds/87477033.

**Comment by BanzaiMan** [comment]
@nschloe Ah. I see that you are using:

```yaml
virtualenv:
  system_site_packages: true
```

**Comment by BanzaiMan** [comment]
I don't think the Trusty image has that virtualenv set up yet. (On-demand Python installations—such as `3.5.0`—are possible, but only without `system_site_packages`.)

We will look into it. Thanks.

**Comment by nschloe** [comment]
Yup, we need those system packages at the moment since we depend on numpy, which is too big to install every time anew.

**Comment by BanzaiMan** [comment]
This should be fixed on Trusty.

**Comment by rky0930** [comment]
Thanks. I fixed the same problem after trying @xavfernandez's suggestion.

I found that my python3 version in Virtualenv is python3 = 3.4 and native python3 = 3.4.3.

So, change the python3(v3.4.0) in  Virtualenv  to python3(v3.4.3). 

And problem solved!

Thank you
