### ISSUE TITLE
pull request-specific test

### ISSUE THREAD

**Issue by RNAer** [travis-ci/travis-ci#5007]
Is there any way for Travis CI to find the files changed in a pull request and launch the tests targeted for those files only (rather than the whole set of tests)?

**Comment by kbrock** [comment]
hi @RNAer I'm currently trying to solve that same problem at [johnny_five].
I'll ping you when I get closer to the end.

[johnny_five]: https://github.com/kbrock/johnny_five_sample

**Comment by RNAer** [comment]
cool. thanks!

**Comment by BanzaiMan** [comment]
You can gather the list of files that changed with something like `git diff --name-only $TRAVIS_COMMIT_RANGE`. It is up to you to decide what to do with this information.

Do note, however, that the PR can always override such information and trigger other tests.
