### ISSUE TITLE
Rust uses kcov for coverage. Please provide it as part of a default environment for Rust

### ISSUE THREAD

**Issue by ehiggs** [travis-ci/travis-ci#5010]
[The Rust community relies on kcov for measuring coverage](https://users.rust-lang.org/t/tutorial-how-to-collect-test-coverages-for-rust-project/650). It would probably be best for the travis machines to have this installed by default for the Rust language environment so it doesn't need to download it for each build.

**Comment by cholcombe973** [comment]
+1

**Comment by Razican** [comment]
+1

**Comment by colin-kiegel** [comment]
+1

**Comment by Ygg01** [comment]
+1

**Comment by rossmuir** [comment]
+1

**Comment by softprops** [comment]
+1

**Comment by nathanross** [comment]
+1

**Comment by BanzaiMan** [comment]
https://travis-ci.community/t/add-kcov-support-as-a-standard-rust-feature/864
