### ISSUE TITLE
Failed build showing as a success on GitHub PR

### ISSUE THREAD

**Issue by sloria** [travis-ci/travis-ci#5013]
We are seeing builds that are showing up as successes on the corresponding GitHub PR.

Travis Build: https://travis-ci.org/CenterForOpenScience/osf.io/builds/87511607
PR: https://github.com/CenterForOpenScience/osf.io/pull/4409#issuecomment-151253136

I'm not sure if this has to do with the fact that we run parallel jobs for each of our builds.

Thanks in advance for your help.

**Comment by Garonenur** [comment]
we just had the same problem for https://github.com/genometools/genometools#679 and https://travis-ci.org/genometools/genometools/builds/87491796

**Comment by svenfuchs** [comment]
Sorry about the troubles, @sloria, @Garonenur 

This is a bug that has been in production for a short time, and has been fixed meanwhile. See also https://github.com/travis-ci/travis-ci/issues/5019

Closing this. Please re-open if there are further issues.

**Comment by sloria** [comment]
Thanks for the quick response to this!

**Comment by Garonenur** [comment]
:+1: thanks.
