### ISSUE TITLE
Xcode 7.2

### ISSUE THREAD

**Issue by mattyohe** [travis-ci/travis-ci#5018]
Hopefully it's possible to get some of the betas going this time around:
https://developer.apple.com/xcode/download/

Thanks again!

**Comment by emdantrim** [comment]
Ready to go ~ !
`osx_image: xcode7.2b1`

**Comment by mattyohe** [comment]
Thanks once again.

Anyone else checking this out, here's notes on that (including the mention that it's OS X is 10.11!):
http://docs.travis-ci.com/user/languages/objective-c/#Xcode-7.2-Beta
