### ISSUE TITLE
Travis-CI is giving wrong status github 

### ISSUE THREAD

**Issue by hargup** [travis-ci/travis-ci#5019]
Recently we merged a broken pr (https://github.com/sympy/sympy/pull/10042) because Travis-ci gave a success status on github even though [the build](https://travis-ci.org/sympy/sympy/builds/87496535) was broken. Such bugs can be very problematic to communities like ours and I urge you to look into the matter as soon as possible.

**Comment by svenfuchs** [comment]
Thanks for the report @hargup, and sorry about the troubles.

Around that time (Oct 26, 20:30) a faulty version of the component that reports builds status to GitHub was in production. This bug has been fixed and deployed in the meanwhile.

Just ran build that would have reproduced the bug to see if it's still around: https://github.com/svenfuchs/test/pull/2

**Comment by hargup** [comment]
Thanks!
