### ISSUE TITLE
Trusty beta Python 2 fails with WeeChat

### ISSUE THREAD

**Issue by Mikaela** [travis-ci/travis-ci#5021]
WeeChat builds without issues on the old system, but with trusty all builds using Python 2 fail (no issues with Python 3).

```
/usr/bin/ld: /opt/python/2.7.10/lib/python2.7/config/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/opt/python/2.7.10/lib/python2.7/config/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

* https://travis-ci.org/weechat/weechat/builds/87766719
* https://github.com/weechat/weechat/pull/564

**Comment by BanzaiMan** [comment]
Is this still a problem?

**Comment by Mikaela** [comment]
@BanzaiMan Yes. https://travis-ci.org/weechat/weechat/builds/96924890

I rebased the PR on latest WeeChat master and pushed.

**Comment by Mikaela** [comment]
Still happening. https://travis-ci.org/Mkaysi/weechat/jobs/97531953

There is also PR open on moving to containers (https://github.com/weechat/weechat/pull/624), but there is question when will it get a more recent version and what do those mysterious whitelist mesages mean, but I have contacted the support email.

**Comment by BanzaiMan** [comment]
Hello. Could you try dropping non-system Python paths from `$PATH`?

```yaml
before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
```

**Comment by Mikaela** [comment]
Works. Why are non-system Python paths in the `$PATH`?

**Comment by BanzaiMan** [comment]
@Mikaela Yay! I think the root cause is that of provisioning process, which I described in #5326.

Can we close this one?

**Comment by Mikaela** [comment]
I think so if we close this as duplicate of https://github.com/travis-ci/travis-ci/issues/5326.
