### ISSUE TITLE
Add cache support for Carton (perl)

### ISSUE THREAD

**Issue by markwellis** [travis-ci/travis-ci#5022]
it's like bundler, but it's carton. saves it's files in local/

i tried to use cache directory, but it takes longer to install Carton than to install the deps i want caching

**Comment by BanzaiMan** [comment]
Can you add Carton to your cache?

**Comment by markwellis** [comment]
@BanzaiMan what do you mean?

**Comment by BanzaiMan** [comment]
Build Carton once, then add that to your cache via directories.

**Comment by markwellis** [comment]
That's possible but it would require messing around with $PATH and such in
order to get carton to work, in which case I'd be better off setting up a
local::lib and using that.

Can you add Carton as a pre-installed perl module if that's easier than
making `cache: carton` work?
