### ISSUE TITLE
Unable to deploy to OpenShift, unauthenticated when password contains $

### ISSUE THREAD

**Issue by davet1985** [travis-ci/travis-ci#5023]
Travis was unable to authenticate with OpenShift after I had changed my password to contain a $. Other characters in the password were A-Z, a-z and 0-9. Here is a link to the build that errored:

https://travis-ci.org/handihealth/ehrscape-provisioner/builds/87890708

I proved this by changing my password again to not include $ and travis was able to authenticate. Here is the subsequent successful build:

https://travis-ci.org/handihealth/ehrscape-provisioner/builds/87909612

**Comment by BanzaiMan** [comment]
Could you try escaping special characters and pass that to `travis encrypt`? http://docs.travis-ci.com/user/encryption-keys/#Note-on-escaping-certain-symbols

**Comment by davet1985** [comment]
I encrypted the password using `travis encrypt 'Blah\$1234'` and still received the unauthenticated error. Link to build: https://travis-ci.org/handihealth/ehrscape-provisioner/builds/87918842

**Comment by davet1985** [comment]
Thanks for your help.

I have found that using `travis encrypt 'OPENSHIFT_PASSWORD=Blah\$1234' --add` and using `secure: $OPENSHIFT_PASSWORD` works.

I was originally using `travis setup openshift` which I assume is not taking into account escaping of special characters when it encrypts the password, so there may still be an issue with this.
