### ISSUE TITLE
Landing page for specific branch

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#5024]
I'd like to have a page (URL) which I use to to link it from my build status badge (e.g. in [here](https://github.com/mycognitive/ads)).

For example this link points to master: https://travis-ci.org/mycognitive/ads

But I can't find URL which points to the specific branch.

In here (https://github.com/travis-ci/travis-ci/issues/1996#issuecomment-46432115) somebody mentioning about `/:owner/:repo/builds/latest/:branch`, but when I go to https://travis-ci.org/mycognitive/ads/builds/latest/7.x-1.x I see the blank page, nothing else.

Can anybody demonstrate working example, so we can finally solve it?

It seems this has been requested in many issues, but still I don't see it's working (as issues get closed without any solution so far): #1996, #4689, #2454.

**Comment by mbdevpl** [comment]
Possible duplicate/reincarnation of https://github.com/travis-ci/travis-ci/issues/1363 ?

**Comment by kenorb** [comment]
It seems it has been fixed at some point.

The syntax is: `https://api.travis-ci.org/travis-ci/travis-api.svg?branch=master`.

For example:

- ![](https://api.travis-ci.org/travis-ci/travis-api.svg?branch=master) (`travis-api.svg?branch=master`)
- ![](https://api.travis-ci.org/travis-ci/travis-api.svg?branch=enterprise-2.1) (`travis-api.svg?branch=enterprise-2.1`)
- ![](https://api.travis-ci.org/travis-ci/travis-api.svg?branch=bd-intercom) (`travis-api.svg?branch=bd-intercom`)

**Comment by kaidokert** [comment]
Maybe user/repo/builds page could simply have a filter like user/repo/builds?branch=master ?

**Comment by matrixik** [comment]
Don't go.

**Comment by tooomm** [comment]
👍

**Comment by lpenz** [comment]
:heavy_plus_sign:

**Comment by techtonik** [comment]
Did anyone create thread on https://travis-ci.community/ already?

**Comment by DracoBlue** [comment]
@techtonik see https://travis-ci.community/t/landing-page-for-specific-branch/6710

**Comment by vinniefalco** [comment]
Yeah this would be nice but after 5 years is it safe to say it will never happen?

**Comment by kousu** [comment]
I would also like this feature. There's already https://travis-ci.org/github/$org/$repo/branches/, just add https://travis-ci.org/github/$org/$repo/branches/master or https://travis-ci.org/github/$org/$repo/branches/dev.
