### ISSUE TITLE
Install PyPy 4.0.0

### ISSUE THREAD

**Issue by fijal** [travis-ci/travis-ci#5027]
Travis has been slow in upgrading pypy versions, please install pypy 4.0.0 before the new release comes up.

**Comment by alex** [comment]
https://github.com/yyuu/pyenv/issues/463 needs to be resolved first (the pyenv folks are usually pretty snappy, I expect this to be done within a day)

**Comment by alex** [comment]
It's landed in pyenv, the commit is 6c3dd0a24f12851139326ea9e482f7a92d7f2700

**Comment by jhgg** [comment]
+1

**Comment by Juanlu001** [comment]
+1 Looking forward to this :)

**Comment by sublee** [comment]
+1

**Comment by lrq3000** [comment]
+1

**Comment by frol** [comment]
There is already PyPy 4.0.1... However, it turned out to be quite easy to install the required version yourself; just add the following code to the install section:

```bash
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          cd "$PYENV_ROOT" && git pull
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="4.0.1"
        "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
      fi
```

You can follow my `.travis.yml` for one of my recent projects: https://github.com/frol/flask-restplus-server-example/blob/master/.travis.yml (here is how the Travis log for pypy looks like: https://travis-ci.org/frol/flask-restplus-server-example/jobs/101854973)

**Comment by Juanlu001** [comment]
Thanks for sharing @frol!

**Comment by brian-brazil** [comment]
What's the status on this? It's been almost a year and there's no obvious blockers.

**Comment by TiberiumPY** [comment]
Travis guys, can you add latest PyPy? There was a lot of improvements over 2.5 version

**Comment by acdha** [comment]
Just to document for anyone else, this causes builds to fail when accessing HTTPS resources when the remote server depends on SNI to serve the requested hostname. Among other things, this breaks downloads from the Apache.org servers used by projects such as Solr:

```
/home/travis/virtualenv/pypy-2.5.0/site-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
```

```
/home/travis/virtualenv/pypy-2.5.0/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
```

**Comment by haypo** [comment]
My python/performance job just failed on installing Mercurial 4.0.0 on PyPy: https://travis-ci.org/python/performance/jobs/173964546

In logs, I see that it's still PyPy 2.5.0 released in February 2015: https://morepypy.blogspot.fr/2015/02/pypy-250-released.html

Would it be possible to upgrade PyPy to a more recent version please? Thank you in advance ;-)

**Comment by squeaky-pl** [comment]
In the meantime for anybody that can't wait you can grab the portable binaries from https://github.com/squeaky-pl/portable-pypy, just untar it and you are ready to go.
