### ISSUE TITLE
Link to builds from branch page is broken

### ISSUE THREAD

**Issue by piuccio** [travis-ci/travis-ci#5028]
Hi

If you go to a branches page, like this https://travis-ci.org/guardian/switchboard/branches
and click on the build number, you'll see that the link is https://travis-ci.org/guardian/guardian/switchboard/builds/88100388

The organization is repeated twice in the URL. It works fine when you click the first time, but if you refresh the page or open the link in a new tab you get to a blank page.

This is the message in the console
```
Attempting URL transition to /guardian/guardian/switchboard/builds/88100388
Uncaught UnrecognizedURLError: /guardian/guardian/switchboard/builds/88100388
```

**Comment by lislis** [comment]
Hi @piuccio! Thanks for opening the ticket! 
I fixed it and it's now live.  
![high five](http://i.giphy.com/9wZybot8h5Nte.gif)

**Comment by piuccio** [comment]
that was quick! thanks
