### ISSUE TITLE
HHVM and PDO with PostgreSQL

### ISSUE THREAD

**Issue by jarofgreen** [travis-ci/travis-ci#5029]
Is this not supported currently?

https://travis-ci.org/OpenACalendar/OpenACalendar-Web-Core/jobs/88177032

I found http://docs.hhvm.com/manual/en/ref.pdo-pgsql.php which suggests it's done by an external lib.

Thanks.

**Comment by BanzaiMan** [comment]
How do you make this work on your development machine?

**Comment by jarofgreen** [comment]
Um, to be honest, I don't. If this isn't stable / production-ready yet I'm happy to just be told "No".....

**Comment by BanzaiMan** [comment]
I think the best thing to is to try it.

In the meantime, I'm closing this. If you find something lacking on our side, please reopen this issue. We can investigate and help.
