### ISSUE TITLE
python 3.4 and 3.5 failing to install

### ISSUE THREAD

**Issue by nikolas** [travis-ci/travis-ci#5038]
Hi,
Using travis's old infrastructure (using sudo), python 3.4 and 3.5 fail to install. Is this the expected behavior?

https://travis-ci.org/freedombox/Plinth/jobs/88540147
https://github.com/freedombox/Plinth/pull/273

    3.4 is not installed; attempting download
    bzip2: (stdin) is not a bzip2 file.
    tar: Child returned status 2
    tar: Error is not recoverable: exiting now

**Comment by BanzaiMan** [comment]
Could you try 3.4.3 and 3.5.0?

**Comment by nikolas** [comment]
Those are also failing, see:
https://travis-ci.org/freedombox/Plinth/jobs/88675309
https://travis-ci.org/freedombox/Plinth/jobs/88675310

**Comment by BanzaiMan** [comment]
I have a feeling that this is related to #5006. Can you try with without `system_site_packages`?

**Comment by nikolas** [comment]
It's working after removing `system_site_packages`. Thanks.
