### ISSUE TITLE
/home/travis/build.sh: line 41:  2915 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by nadar** [travis-ci/travis-ci#5039]
Can someone help me on this issue? The phpunit tests seems to run fine, but afterwards i got this 

```
/home/travis/build.sh: line 41:  2915 Segmentation fault      (core dumped) vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --configuration travis.phpunit.xml
```

error, which makes the build failing. It only occurs on php7 job.

The Build (where only php7 fails): https://travis-ci.org/zephir/luya/builds/88664369
The failing job: https://travis-ci.org/zephir/luya/jobs/88664372#L287

I was unable to find something on stackoverflow as mentioned in the contribution guidelines, nor google.

regards

**Comment by BanzaiMan** [comment]
As you are using `php: 7`, it is using the 7.0 development branch, which may contain some bugs. If it started seg faulting recently, please get in touch with the PHP development team or wait a few days to see if your particular issue is fixed.

**Comment by nadar** [comment]
@BanzaiMan Thanks for your reply!

**Comment by arcanedev-maroc** [comment]
Hi @BanzaiMan,

I have the same issue in one of my packages : https://travis-ci.org/ARCANESOFT/Auth/jobs/97489752

It says: `../home/travis/build.sh: line 45:  3977 Segmentation fault      (core dumped) vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover`

Even that PHP 7 is stable now.

This one works perfectly : https://travis-ci.org/ARCANESOFT/Foundation/jobs/97486050

**Comment by BanzaiMan** [comment]
@arcanedev-maroc Please open a separate issue. Thank you.

**Comment by arcanedev-maroc** [comment]
Okey :+1:

**Comment by DenBeke** [comment]
The same issue here:

```
/home/travis/build.sh: line 45:  2625 Segmentation fault      (core dumped) phpunit
The command "phpunit" exited with 139.
```

**Comment by BanzaiMan** [comment]
@DenBeke If PHPUnit 4.8.21 is segfaulting on PHP 7.0.0, I don't think it is something we can fix. According to https://phpunit.de/ 4.8.x is for PHP versions up to 5.6.x. If it ever worked in this combination, it is more by luck than by design.

**Comment by DenBeke** [comment]
@BanzaiMan I've enabled phpunit 5 in my composer file, like in the other issue, but still having a segfault:

```
$ phpunit
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.
/home/travis/build.sh: line 45:  2750 Segmentation fault      (core dumped) phpunit
The command "phpunit" exited with 139.

$ php index.php
/home/travis/build.sh: line 45:  2805 Segmentation fault      (core dumped) php index.php
The command "php index.php" exited with 139.
Done. Your build exited with 1.
```

I also do a simple `php index.php` comment, and it also gives a segfault, which is without phpunit.

**Comment by BanzaiMan** [comment]
@DenBeke You may be seeing https://github.com/travis-ci/travis-ci/issues/533. We'll need more information than that in order to help you.

**Comment by DenBeke** [comment]
Tried 7.0.1, still the same problem... Can I give you a link to a private travis project? Or won't you have access to that?

**Comment by BanzaiMan** [comment]
@DenBeke If you'd rather communicate privately, please email support@travis-ci.com.

Thanks.

**Comment by DenBeke** [comment]
Thanks, I have sent an email...

**Comment by odan** [comment]
I have the same issue with php nightly and PHPUnit 5.1.3.

For the moment I fixed it with:

```
language: php
php:
  - 5.6
  - 7.0
  - 7.0.1
 # - nightly
```

**Comment by BanzaiMan** [comment]
@odan Sorry to hear that. Nightly should be refreshed daily, but it can fail any day.

**Comment by beporter** [comment]
This has been happening to my builds lately even with PHP 5.6:

```
$ php --version
PHP 5.6.5 (cli) (built: Feb 12 2015 01:41:10)

# (snip)

$ bin/phpunit -v

# (snip)

Generating code coverage report in Clover XML format ...
/home/travis/build.sh: line 45:  3785 Segmentation fault      (core dumped) bin/phpunit -v
```

This happens at different points in the phpunit execution.
