### ISSUE TITLE
Python 2 and 3 in parallel

### ISSUE THREAD

**Issue by cod3monk** [travis-ci/travis-ci#5041]
I need to be able to use python 2 and 3 in parallel on the same container, with pip. If python 3.4 is selected, pip2 exists, but fails due to permissions: https://travis-ci.org/RRZE-HPC/kerncraft/jobs/88750226

Unfortunately one of my install scripts depends on mechanize, which is not python3 compatible, but I would like to test my library with python3 regardless. 

Is there a way to get python and pip 2 and 3 at the same time?

**Comment by cod3monk** [comment]
I solved the problem by changing from mechanize to requests, but it still leaves the question unanswered.

**Comment by BanzaiMan** [comment]
You can call virtualenv's activate script if you need to switch between Python versions within a single job.

```
source ~/virtualenv/python2.7/bin/activate
⋮
source ~/virtualenv/python3.5/bin/activate
⋮
```

**Comment by BanzaiMan** [comment]
Have you tried it? I'm closing in the meantime.
