### ISSUE TITLE
Brew update error: Specify a version for EmacsRequirement

### ISSUE THREAD

**Issue by diogoguimaraes** [travis-ci/travis-ci#5044]
`brew update` is failing when building with travis. I can update homebrew locally but when building the project in travis I get: 
 ```
$ brew update
Updated Homebrew from 91b03473 to 18c483f1.
Error: Specify a version for EmacsRequirement
```
Do you know what may be causing this to happen?
Thank you.

**Comment by ptmt** [comment]
Have the same problem. Fixed by `brew update || brew update` from here: https://github.com/Homebrew/homebrew/issues/45616

**Comment by BanzaiMan** [comment]
Is this a Homebrew issue, then? Can we close this?

**Comment by diogoguimaraes** [comment]
Yes, it has been solved by Homebrew. Thank you.
