### ISSUE TITLE
No syntax errors, but my build exited with 255.

### ISSUE THREAD

**Issue by olefredrik** [travis-ci/travis-ci#5045]
My build seems to be fine with no syntax errors. However it's failing with the following error message:
```
The command "$WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php" exited with 255.

Done. Your build exited with 1.
```

The build fail error message:
https://travis-ci.org/olefredrik/FoundationPress/jobs/88859682#L183

Here is my .travis.yml file:
https://github.com/olefredrik/FoundationPress/blob/master/.travis.yml

Anyone got a clue what's going on?

**Comment by brendanw** [comment]
Did you make no code changes but only renamed some files?
