### ISSUE TITLE
Invalid z-index for builds table / Safari 9.0 @ OS X 10.11

### ISSUE THREAD

**Issue by kiler129** [travis-ci/travis-ci#5046]
While badge code window is open hovering on one of rows in builds table produces little strange effect:
<img width="942" alt="screenshot 2015-11-03 00 14 39" src="https://cloud.githubusercontent.com/assets/1227834/10897283/0b8866f0-81c0-11e5-8c27-e0b980ce5104.png">

**Comment by lislis** [comment]
Hey @kiler129 and thanks for finding and reporting the bug!
I fixed and deployed it and it is now live.
Thanks again!
![high five](http://i.giphy.com/CDMz3fckRXXDG.gif)
