### ISSUE TITLE
Stuck on syncing from GitHub

### ISSUE THREAD

**Issue by awolski** [travis-ci/travis-ci#5047]
As per https://github.com/travis-ci/travis-ci/issues/2689, Travis CI Pro never finishes syncing from GitHub.  Looks like there are many other occurrences of this that have been resolved by a manually sync?

**Comment by BanzaiMan** [comment]
This should be fixed now. Could you retry it if it's not done already?

**Comment by awolski** [comment]
Yep, fixed by manual sync. Thank you.
