### ISSUE TITLE
'rebar' tool for erlang projects is slightly outdated

### ISSUE THREAD

**Issue by vladdu** [travis-ci/travis-ci#5052]
Rebar has released new versions of the tool, that have useful new features (like being able to work with dialyzer). Latest version is 2.6.1 at the time of this writing.

Please update it. I thought it was a matter of editing the corresponding recipe, but after checking that I confess that I don't know how to make that change myself.

**Comment by binarytemple-bet365** [comment]
Copying a binary blob into every project is not a good thing. Having rebar and rebar3 on the PATH would definitely be a good thing, and not very difficult to implement at all.

**Comment by BanzaiMan** [comment]
Closing this in favor of #6506.
