### ISSUE TITLE
Unable to run 1.4.13 Appium on travis

### ISSUE THREAD

**Issue by xiaojin** [travis-ci/travis-ci#5055]
I've tried using osx_image xcode7.1 with iphonesimulator 9.1, install the appium with 1.4.13
When running appium on travis, appium can't start Instruments. I'm getting this error:

> sh: appium: command not found

>ERROR: Unable to connect to Appium. Is the server running? (RuntimeError)
> /Users/travis/.rvm/gems/ruby-2.1.2/gems/appium_lib-8.0.0/lib/appium_lib/driver.rb:497:in `rescue in start_driver'
 >/Users/travis/.rvm/gems/ruby-2.1.2/gems/appium_lib-8.0.0/lib/appium_lib/driver.rb:482:in `start_driver'
>  /Users/travis/build/AtlasWayfinder/atlas-auditor-iOS/features/support/env.rb:9:in `Before'

**Comment by xiaojin** [comment]
> - npm install appium
- export PATH=node_modules/.bin:$PATH
> in before_install 
*That will fix this issue*

**Comment by BanzaiMan** [comment]
Look like this issue has been resolved.
