### ISSUE TITLE
Build failure on Xcode 7.0.1+

### ISSUE THREAD

**Issue by saiday** [travis-ci/travis-ci#5057]
I use Xcode 7 to build my iOS project on Travis CI.
Added `osx_image: xcode7` on my `.travis.yml`, it works great at `2015/10/14`.
The log shows it was Xcode 7.0
```
Xcode 7.0
Build version 7A220
```

Since yesterday, my project cannot build successfully in same commit, and I noticed that Xcode version is
```
Xcode 7.0.1
Build version 7A1001
```

I always got error on 
```
  ✓ Run custom shell script 'Check Pods Manifest.lock' (104 ms)
  ✓ Compile mapping model Model1_to_Model2.xcmappingmodel (2207 ms)
  ✓ Compile data model xxxDataModel.xcdatamodeld (619 ms)
  ✗ Precompile xxx-Prefix.pch (4286 ms)
  ...

In file included from /Users/travis/build/xxx/xxx-ios/xxx/xxx/Supporting Files/xxx-Prefix.pch:19:
/Users/travis/build/xxx/xxx-ios/xxx/xxx/AppDelegate.h:10:9: fatal error: 'FBSDKLoginManager.h' file not found
#import <FBSDKLoginManager.h>
```

I tried Xcode 7.1 on Travis CI, still got no luck.

**Comment by mattyohe** [comment]
@saiday 7.0.0 was replaced with 7.0.1 according to [this post](http://blog.travis-ci.com/2015-10-23-xcode-71-701-are-ready/).

There was also a header issue with that pod you're referencing that was updated after the 2015 date you mention above: https://developers.facebook.com/docs/ios/change-log-4.x

**Comment by saiday** [comment]
@mattyohe Thanks for your reply.

Actually it's not related to Facebook pod, it happens at each pod dependencies, the logs shows 
```
fatal error: 'FBSDKLoginManager.h' file not found
```
just because it's the first pod been imported when building, if there's any other pod before it, it fails either.

My job succeeded on `7.0.0` image on Travis CI, at the same commit, build fails on `7.0.1`+. Hence, I open this issue for help.

btw, I ran my script on local, from clean clone to testing. It succeeded.
Am I the only one had this issue?

Thank you @mattyohe

**Comment by saiday** [comment]
This log may help:
```
ProcessPCH /Users/travis/Library/Developer/Xcode/DerivedData/streetvoice-cgzoejwljnnxhweuviklvepjyiga/Build/Intermediates/PrecompiledHeaders/streetvoice-Prefix-gwojeivsckjeezhjbwfekjnkftwy/streetvoice-Prefix.pch.pch streetvoice/Supporting\ Files/streetvoice-Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

and I'm just wondering is that a problem, in local environment, my pch inside `DerivedData/../Build/Intermediates/PrecompiledHeaders` naming is `streetvoice-Prefix.pch.pch.hash-criteria` different to `streetvoice-Prefix.pch.pch` in travis.

**Comment by mattyohe** [comment]
@saiday that command `ProcessPCH` is for processing PCH files, and the file named `Prefix.pch.pch.hash-criteria` is not a pch file, so you wouldn't expect it to show up in that log. That hash-criteria file I presume also exists locally.

I would compare compile log to compile log instead of travis compile log to files in your derived data folder.

**Comment by saiday** [comment]
@mattyohe thank you for your clarify.

Since my repo is private, so I upload entire logs to gist, please take a look. Two jobs is entirely same except xcode 6 and 7 image.

Xcode 6 (which succeeded)
https://gist.github.com/saiday/3b9dc45893d65de01df2/raw/a5e7b4153519f9bd622519f0819f607bbb7d5357/travis_xcode6

Xcode 7 (which failed)
https://gist.github.com/saiday/f8d1d077dc71c7d78920/raw/a3703bbe8c3dd316ff1decd6755def726eafda28/travis_xcode7

Thanks again.

**Comment by saiday** [comment]
hi, @mattyohe, do you guys had any progress on this issue?

**Comment by mattyohe** [comment]
@saiday Sorry, I'm not associated with Travis-CI, just was being helpful.

Does your build still fail on Xcode 7.1? There's no reason to use the old Xcode anymore, anyway.

**Comment by saiday** [comment]
OK, I found a solution. It seems root cause relating to `pod install` or not.

opened another issue: https://github.com/travis-ci/travis-ci/issues/5298
