### ISSUE TITLE
Installing PHP with phpenv on Trusty beta environment fails

### ISSUE THREAD

**Issue by osma** [travis-ci/travis-ci#5058]
I'm trying to switch to the Trusty beta for a project that needs both PHP and Java8 to run its tests. But it seems that phpenv is not working at all:

```
$ phpenv global 5.6 2>/dev/null
5.6 is not pre-installed; installing
0.18sbzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
0.00s0.02s$ phpenv global 5.6
rbenv: version `5.6' not installed
The command "phpenv global 5.6" failed and exited with 1 during .
Your build has been stopped.
```

The same happens for all versions of PHP that I have configured in .travis.yml (5.3, 5.4, 5.5, 5.6). You can click open any of the jobs of this build, all fail in the same way: https://travis-ci.org/NatLibFi/Skosmos/builds/89208946

Here's my .travis.yml: https://github.com/NatLibFi/Skosmos/blob/jena3-text-index/.travis.yml

This seems similar to #4750 except I'm not using the Docker service, this is (or should be) a plain Trusty environment.

**Comment by BanzaiMan** [comment]
For build process, Docker and Trusty are synonymous. As such, I will close this as a duplicate.
