### ISSUE TITLE
Add xdebug to PHP 7 environment

### ISSUE THREAD

**Issue by cyberwolf** [travis-ci/travis-ci#5064]
Since a few days there's a xdebug beta out that should be compatible with PHP 7: https://t.co/9Hr6ppaB5V

**Comment by BanzaiMan** [comment]
xdebug master doesn't seem to work.

Trusty: https://staging.travis-ci.org/travis-ci/php-src-builder/jobs/450130#L236
Precise: https://staging.travis-ci.org/travis-ci/php-src-builder/jobs/450131#L412

**Comment by BanzaiMan** [comment]
The PHP 7 archive should have xdebug at this time.
