### ISSUE TITLE
Package required but not available: ‘RODBC’

### ISSUE THREAD

**Issue by lbraglia** [travis-ci/travis-ci#5066]
Hi,

am i missing something here (since RODBC should be on cran)?

https://travis-ci.org/lbraglia/yapomif/builds/89912401

Many thanks in advance

cc: @craigcitro  @hadley

**Comment by craigcitro** [comment]
it looks like RODBC failed to install:
  https://travis-ci.org/lbraglia/yapomif/builds/89912401#L964

i'm guessing it needs a system dependency; easiest choice is probably to just add it to `r_binary_packages`?

**Comment by lbraglia** [comment]
Fixed using

```
apt_packages:
 - unixodbc-dev
```

best, Luca
