### ISSUE TITLE
Build Fails Before Running Anything in .travis.yml

### ISSUE THREAD

**Issue by brodkin** [travis-ci/travis-ci#5068]
Hey kids,

I have a build that can't seem to get off the ground. I think the config is right, but please correct me if I am wrong.

https://travis-ci.org/brodkinca/docker-jira-software

The goal here is:
1. Run a container with PHP (*this is where we currently fail*)
2. Pull down dependencies
3. Execute a small build script that generates a Dockerfile for the latest JIRA version
4. Build that Dockerfile to ensure it works
5. Push a tag for the build to Github
And in a future commit...
4.5. Push the image to Docker Hub

Can I not run a Docker service in a PHP container? Is this a bug or what am I missing?

**Comment by BanzaiMan** [comment]
Sorry for the delay. Your build is failing at `git commit…`, which is run at the time when no files have been added to the staging area. As you can see in the logs, we are running your commands given in https://github.com/brodkinca/docker-jira-software/blob/1dd20d7ae39a3cf4df4856723ad99ecfd3eaf7b8/.travis.yml.

Please review your build configuration.

**Comment by brodkin** [comment]
Thanks for the reply @BanzaiMan. As you said it looks like my build is failing now for other reasons.

Previously the builds were erroring out much earlier...
https://travis-ci.org/brodkinca/docker-jira-software/builds/90579632

I guess whatever was causing that has been fixed.
