### ISSUE TITLE
Builds remain in queue indefinitely if travis-ci fails to provision slot

### ISSUE THREAD

**Issue by nanonyme** [travis-ci/travis-ci#507]
These builds have duration > 24h. 
http://travis-ci.org/#!/heroku/heroku/builds/1115299
http://travis-ci.org/#!/symfony/symfony/builds/1118598 
I was able to see that they were still kicking and gathering more duration when it was less than 24. Since there are plenty free worker slots, these builds most likely ended up in some weird stuck state.

**Comment by rraallvv** [comment]
I'm having a similar issue with this job:
https://travis-ci.org/rraallvv/ObjC-Lua/jobs/67556992
It's just stuck at the queued phase

**Comment by BanzaiMan** [comment]
@rraallvv Sorry about the issue you had. We had problems with Mac builds (https://www.traviscistatus.com/incidents/h5bxh21wb8mr), which was unrelated to this issue.
