### ISSUE TITLE
travis_wait holding up on the logs

### ISSUE THREAD

**Issue by nasht00** [travis-ci/travis-ci#5071]
My build is taking a long time (expected) with moments of silence. Which can often bring up the 10 minutes timeout.

You've documented a great workaround with `travis_wait`.

However I noticed that when using `travis_wait` I do not see **any** output log from my build script until the very end. It'd be nice if you would continue to stream the logs as usual even with the `travis_wait` flag.

**Comment by BanzaiMan** [comment]
The `travis_wait` works by redirecting the output a file, while continuing to write to STDOUT, so that the process does not get killed. This way, the output is not mixed on the log stream.

I am happy to explore the alternatives to achieve its goal with different means.

**Comment by evilaliv3** [comment]
:+1:

**Comment by evilaliv3** [comment]
anyhow this is a duplicated issue of: https://github.com/travis-ci/travis-ci/issues/4190
