### ISSUE TITLE
Getting ERROR 1114 (HY000) at line 3957 during MySQL DB import

### ISSUE THREAD

**Issue by leolandotan** [travis-ci/travis-ci#5074]
So I have a DB that needs to be imported and it's about 180MB. The command I use is ```zcat default.sql.gz | mysql default``` but I get an error:

```
ERROR 1114 (HY000) at line 3957: The table 'default_table_name' is full
The command "zcat default.sql.gz | mysql default" failed and exited with 1 during .
```

Any ideas on this? The previous DB also was only about 29MB w/c imports with no errors.

Thanks!

**Comment by BanzaiMan** [comment]
Is this from a job running on a container?

**Comment by leolandotan** [comment]
@BanzaiMan Yes it is. I saw this http://stackoverflow.com/questions/730579/error-1114-hy000-the-table-is-full but I'm not familiar how to apply the mysql config during the Travis CI build process. I mean when the build starts.

**Comment by leolandotan** [comment]
In my .travis.yml file before the line where it imports the DB I placed:
```
- echo -e "[server]\ninnodb_file_per_table" | sudo tee -a /etc/mysql/my.cnf
- echo -e "innodb_data_file_path = ibdata1:10M:autoextend" | sudo tee -a /etc/mysql/my.cnf
- echo -e "key_buffer_size = 256M" | sudo tee -a /etc/mysql/my.cnf
- echo -e "tmp_table_size = 256M" | sudo tee -a /etc/mysql/my.cnf
- echo -e "max_heap_table_size = 256M" | sudo tee -a /etc/mysql/my.cnf
- cat "/etc/mysql/my.cnf"
- sudo service mysql reload
- sudo service mysql restart
```
But still doesn't work. The DB file size by the way is just 27MB gzipped.

**Comment by BanzaiMan** [comment]
`sudo` doesn't work on containers. You might have better luck with the new Trusty builds, or reducing the imported data.

**Comment by leolandotan** [comment]
Oh! but in the ```- cat "/etc/mysql/my.cnf"``` line I saw the configurations I have added. With all the configuration changes I have added, it still fails with only 27MB of DB. :(

Any idea on this?

**Comment by BanzaiMan** [comment]
Perhaps `my.cnf` file is writable by our user. Does the service get restarted?

**Comment by leolandotan** [comment]
Yes the service get restarted. It shows:
```
mysql stop/waiting
mysql start/running, process 8314
```

**Comment by BanzaiMan** [comment]
If you are still experiencing this problem, pleas indicate a recent build log URL that shows this problem. Thanks.

**Comment by leolandotan** [comment]
Sorry for a very late response but I did another way not related to Travis CI configurations. I just removed about 90-95% of the content in the DB. I got it down from 29MB to 7MB(gzipped).

Thanks you!
