### ISSUE TITLE
Provide building on Debian images (not Ubuntu)

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#5075]
Would be good in addition to Ubuntu Trusy image have also Debian image to build on.

**Comment by BanzaiMan** [comment]
This (and/or a variant) has been asked before, to allow builds to run on different OS. It is on our long-term roadmap, and we are laying ground work for it, but we do not have ETA.

**Comment by BanzaiMan** [comment]
I'm pretty sure there is a previous issue, too, but I can't find it.

**Comment by igagis** [comment]
I don't need this anymore, as I found a way to do it right now using sbuild. So, you can close the bug.
