### ISSUE TITLE
Container-based CI build did not fail immediately on apt-get (via addons) failure

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#5077]
I have encountered a CI build error today where I did not expect it to fail because the code has been build tested fine upstream before merging into my own fork. It took me a while to study the build logs to discern the root cause of failure. It turned out it was caused by the apt-get failure to install some of the requested packages listed in the ```addons``` section of my ```.travis.yml```. I could understand that the Ubuntu software package repos are beyond the responsibility of Travis team and one should expect that those mirrors may fail from time to time. Having said that, I would at least expect that Travis-CI build should raise the apt-get install failure further up and error-out the build job if have to, rather than let it continues and fails later on leaving user to figure out what has happened.

These are the two CI build logs that encountered the apt-get failure this morning.
https://travis-ci.org/weitjong/Urho3D/jobs/90243624
https://travis-ci.org/weitjong/Urho3D/jobs/90243625

**Comment by coderanger** [comment]
Just saw this myself, relevant trace:

```
Installing APT Packages (BETA)

$ export DEBIAN_FRONTEND=noninteractive

70.36s$ sudo -E apt-get -yq update &>> ~/apt-get-update.log

63.78s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libgecode-dev

Reading package lists...

Building dependency tree...

Reading state information...

The following extra packages will be installed:

  libboost-dev libboost1.46-dev libgecode30 libgecodeflatzinc30

  libgecodegist30

Suggested packages:

  libboost1.46-doc libboost-date-time1.46-dev libboost-filesystem1.46-dev

  libboost-graph1.46-dev libboost-iostreams1.46-dev libboost-math1.46-dev

  libboost-program-options1.46-dev libboost-python1.46-dev

  libboost-random1.46-dev libboost-regex1.46-dev

  libboost-serialization1.46-dev libboost-signals1.46-dev

  libboost-system1.46-dev libboost-test1.46-dev libboost-thread1.46-dev

  libboost-wave1.46-dev xsltproc doxygen docbook-xml docbook-xsl default-jdk

  fop libgecode-doc

The following NEW packages will be installed:

  libboost-dev libboost1.46-dev libgecode-dev libgecode30 libgecodeflatzinc30

  libgecodegist30

0 upgraded, 6 newly installed, 0 to remove and 217 not upgraded.

Need to get 11.3 MB of archives.

After this operation, 74.1 MB of additional disk space will be used.

Err http://us.archive.ubuntu.com/ubuntu/ precise/main libboost1.46-dev amd64 1.46.1-7ubuntu3

  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Err http://us.archive.ubuntu.com/ubuntu/ precise/main libboost-dev amd64 1.48.0.2

  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Err http://us.archive.ubuntu.com/ubuntu/ precise/universe libgecode30 amd64 3.7.1-3

  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Err http://us.archive.ubuntu.com/ubuntu/ precise/universe libgecodegist30 amd64 3.7.1-3

  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Err http://us.archive.ubuntu.com/ubuntu/ precise/universe libgecodeflatzinc30 amd64 3.7.1-3

  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Err http://us.archive.ubuntu.com/ubuntu/ precise/universe libgecode-dev amd64 3.7.1-3

  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/b/boost1.46/libboost1.46-dev_1.46.1-7ubuntu3_amd64.deb  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/b/boost-defaults/libboost-dev_1.48.0.2_amd64.deb  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gecode/libgecode30_3.7.1-3_amd64.deb  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gecode/libgecodegist30_3.7.1-3_amd64.deb  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gecode/libgecodeflatzinc30_3.7.1-3_amd64.deb  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gecode/libgecode-dev_3.7.1-3_amd64.deb  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.24 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by BanzaiMan** [comment]
Retries have been added to the APT addon by https://github.com/travis-ci/travis-build/pull/600.

I think we can fail the builds after 3 attempts.

**Comment by weitjong** [comment]
I have a quick looked on the changes. I don't think it is a good idea to retry ```apt-get install``` in this manner. If the previous install process already failed then the filesystem could be already in a flux state because we have no way to know for sure it only failed at download stage, and so retrying another ```apt-get install``` would just be delaying the inevitable.

The root cause of my issue above is travis-build script does not check the exit status of the ```apt-get install``` properly. I would be already very happy if the script is being changed in such a way that when ```apt-get install``` failed (for whatever the reasons including temporary network problem) then travis-build propagates up the failure exit status by failing the CI jobs immediately also. So, it frees up the valuable computing resources sooner. Continuing building and testing at this point is meaningless.

And I would even give kudos when travis-build script could preempt the ```apt-get install``` failure caused specifically by temporary network problem. If I were to enhance that script then I would probably do the installation in two stages: first ask apt-get to download the packages and second ask apt-get to actually install the already downloaded packages. I would use the "retry" option only at the first stage in order to counter for the potential temporary network problem. The second stage would be called only when the first stage exits with a success status. All failure exit statuses just propagate up. (Check the manpages of ```apt-get``` and look for ```--download-only``` option. i.e. The first stage uses this option and the second stage just call ```apt-get``` as per normal)

**Comment by tpetazzoni** [comment]
Another occurence of a similar problem can be seen at https://travis-ci.org/buildroot/buildroot-defconfig-testing/jobs/107509137. The package installation fails with: "dpkg: error: dpkg status database is locked by another process", but the build still continues. So there are really two problems:

 1/ Package installation should not fail randomly
 2/ The build should not continue if the package installation fails

This is happening quite frequently, around one build out of three or four is failing for us due to package installation problems.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/656 will change this behavior.

**Comment by tpetazzoni** [comment]
@BanzaiMan This will indeed solve problem (2), but problem (1) still remains: it is somewhat unfortunate that the installation of packages randomly fails.

**Comment by BanzaiMan** [comment]
@tpetazzoni If `apt-get update` fails for whatever reason, unreliable network conditions for example, the package may not be found. I do understand the frustration when the random failures come in.

**Comment by andyli** [comment]
What about my PR https://github.com/travis-ci/travis-build/pull/605? It adds both retry and assert.

**Comment by BanzaiMan** [comment]
@tpetazzoni Could your lock issue be related to `apt-get update` failure? Did it, for example, leave the lock file unexpectedly?

**Comment by BanzaiMan** [comment]
@andyli Oh! I overlooked that one. I'll look into incorporating yours as well! Thank you!

**Comment by tpetazzoni** [comment]
@BanzaiMan I don't know, but I'm pretty sure that apt-get update doesn't leave stale lock files behind it even upon failure. But well, this particular instance only occurred once IIRC, the other cases were network connections issues.

**Comment by BanzaiMan** [comment]
An `apt-get install` failure now marks the build error.

If the lock file issue arises again, we will take a look again.

I will close this now.

**Comment by weitjong** [comment]
Thank you!
