### ISSUE TITLE
"bzip2: (stdin) is not a bzip2 file." occurred when installing python 2.7.6

### ISSUE THREAD

**Issue by Damnever** [travis-ci/travis-ci#5078]
My .travis.yml file is here: https://github.com/Damnever/pigar/blob/master/.travis.yml
Now I removed `2.7.6` from the file.

Failed when installing Python 2.7.6:
```
2.7.6 is not installed; attempting download
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

The build log: https://travis-ci.org/Damnever/pigar/jobs/90252515

**Comment by BanzaiMan** [comment]
2.7.6 is not pre-installed, and we don't have a matching binary archive, so this fails. 2.7.6 is rather old. Do you need this particular version to test?

**Comment by Damnever** [comment]
The module `ast`of 2.7.6 has some difference with other 2.7.x.

**Comment by BanzaiMan** [comment]
We built the 2.7.6 archives for Trusty and Precise. Please test it, and close this if it works.

**Comment by Damnever** [comment]
Thank you.
