### ISSUE TITLE
mentioning consistency

### ISSUE THREAD

**Issue by lbraglia** [travis-ci/travis-ci#5079]
Hi,

just a little thing. Looking here

http://docs.travis-ci.com/user/languages/r/

it's suggested to mention @craigcitro, @hadley and  @eddelbuettel while (eg) here 

https://travis-ci.org/lbraglia/yapomif/builds/90302839#L81

only  @craigcitro and @hadley

thanks, best, Luca.

**Comment by eddelbuettel** [comment]
Yes, that is on purpose.

**Comment by lbraglia** [comment]
uhm i see..

**Comment by joshk** [comment]
Hi @lbraglia 

Thanks for bringing this up.

@eddelbuettel I have removed you from the docs.

High 5 Everyone

Josh

**Comment by stof** [comment]
@eddelbuettel send a PR to https://github.com/travis-ci/docs-travis-ci-com to update the doc :smile:

**Comment by eddelbuettel** [comment]
@joshk :+1:
