### ISSUE TITLE
JavaFX

### ISSUE THREAD

**Issue by GAlexMES** [travis-ci/travis-ci#5081]

**Comment by GAlexMES** [comment]
In my opinion it is not possible to deploy JavaFX application, which use a class out of the javafx.scene.control package.

**Comment by BanzaiMan** [comment]
I am not exactly sure what you are asking. Could you elaborate? Thanks.

**Comment by xea** [comment]
Some JavaFX features (eg. Alert) were introduced with JavaFX 8u40. I think he means that projects using these classes won't compile with Travis' JDK. Actually, I'm experiencing this too and I haven't found a way to specify the JDK version more precisely than the major version number. Cheers.

**Comment by GAlexMES** [comment]
Yeah, that is what I mean. Sorry for the bad description!

**Comment by BanzaiMan** [comment]
OK. In that case, I will close this as a duplicate.

**Comment by DivineThreepwood** [comment]
This issue is still not solved for me!
Even by forcing Travis to use the trusty distribution there is currently only java 1.8.0_51 available which has some newer javafx service methods missing.  Since a week I try to force java updates or try to find a way to build my javafx project with the latest or at least a newer java compiler.

Is there any way to get a newer java version? Issue #3259

**Comment by BanzaiMan** [comment]
@DivineThreepwood We rely on https://launchpad.net/~webupd8team/+archive/ubuntu/java to provide JDK packages for pre-installed packages. If you can find a repository with newer JDK packages, you are welcome to use it.

**Comment by DivineThreepwood** [comment]
But in the repository you referred to the latest java version is 8u92 but travis is using 8u51. 
How can I perform an update to download the newest version?

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338

**Comment by Vogel612** [comment]
@BanzaiMan It would be helpful to have this information in a "public-facing" documentation. It's a bit annoying to scour the internet for a solution to this and find at least three different conflicting ways to do this in github issue-comments that all may or may not work. ... Can this be put up at [the user-docs](https://docs.travis-ci.com/user/languages/java/)?

**Comment by BanzaiMan** [comment]
@Vogel612 Could you elaborate on what you are asking? We always welcome PRs for our documentation as well.

**Comment by Vogel612** [comment]
@BanzaiMan Opened a PR. Comments are very welcome :+1:
