### ISSUE TITLE
Latest Firefox Beta download

### ISSUE THREAD

**Issue by freaktechnik** [travis-ci/travis-ci#5082]
Mozilla is planning to stop using the directory the "latest-beta" build for Firefox is currently downloaded from: https://bugzilla.mozilla.org/show_bug.cgi?id=1223019

I guess it's hard to say, if it'll be possible to continue supporting "latest-beta", but beta.mozilla.org already uses download.mozilla.org links which are only generic for the windows stub installer, which sucks.

**Comment by freaktechnik** [comment]
The betas have now been removed from said folder and instead a readme with instructions on how to create an equivalent download.mozilla.org link has been placed: http://archive.mozilla.org/pub/firefox/releases/latest-beta/README.txt

Apparently the product to use is firefox-latest-beta.

**Comment by BanzaiMan** [comment]
I see that Mozilla changed the names from `latest-*` to `firefox-*-latest`, which is rather unfortunate.

**Comment by freaktechnik** [comment]
Note that `latest` (without any - and other attribute) is also `firefox-latest` now.

**Comment by freaktechnik** [comment]
It seems downloads for firefox by version are also broken.

**Comment by azakus** [comment]
Unfortunately it looks like the `firefox` addon checks the value, so we can't just put `firefox: firefox-latest` in the config :-1:
