### ISSUE TITLE
Unexpected lint errors for R language repo

### ISSUE THREAD

**Issue by leeper** [travis-ci/travis-ci#5084]
The web-based lint interface does not allow R language, despite it being supported. I encountered the following two error messages, which shouldn't be occurring given community support for R:

```
in language section: illegal value r, defaulting to ruby
unexpected key r_github_packages, dropping
```

**Comment by mschilli87** [comment]
This still seems to be an issue.
I'm trying to get started with Travis-CI for an R project, followed the docs and got an error

> Build config file is required via repository settings, but config is empty.

So I wanted to validate my `.travis.yaml` file just to get

> - in language section: illegal value r, defaulting to ruby
> - unexpected key r, dropping
> - unexpected key bioc_required, dropping
> - value for cache section is empty, dropping
> - in cache section: unexpected key packages, dropping

from http://lint.travis-ci.org

**Comment by leeper** [comment]
This issue is not resolved.

**Comment by mschilli87** [comment]
Can anyone confirm this was actually resolved?
