### ISSUE TITLE
Unable to get logs for Travis CI Pro 

### ISSUE THREAD

**Issue by brave-warrior** [travis-ci/travis-ci#5085]
Executing the request `GET https://api.travis-ci.com/jobs/{job_id}/log` returns the following response:

    Status Code: 400
    Server: AmazonS3
    x-amz-request-id: 8003891E638D77E6
    Transfer-Encoding: chunked
    x-amz-id-2: dFKAnQaBg17//iLjY3BeYRXJC/ozNbf08R7opVrjA2XectRE78CvzYOr58FigKi9pLrNBn4+ofU=
    Content-Type: application/xml

    <Error>
      <Code>InvalidArgument</Code>
      <Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message>
      <ArgumentName>Authorization</ArgumentName>
      <ArgumentValue>token [token value]</ArgumentValue>
      <RequestId>1453AD4F4DF25838</RequestId
      <HostId>qoBjd4QtD8mFHTgodjroLXMYiMcv1pvAwpw+dnKZvA2uE327Mf/J/lNuO4+B8hHxYAngl0ERkG4=</HostId>
    </Error>

However, the plain text of the log is expected. Such call works well on Travis CI (https://api.travis-ci.org), but doesn't work well on Travis CI Pro. Correct authorization header was set.

**Comment by BanzaiMan** [comment]
@brave-warrior Sorry for the issue. Could you email support@travis-ci.com with further details? Seems this is too public a forum to discuss potentially sensitive issue.

**Comment by brave-warrior** [comment]
Emailed, didn't get any response. The issue is the following: 
execution of `GET https://api.travis-ci.com/jobs/{job_id}/log` required authentication token. So, the request contain auth token in headers, however, such URL redirects to the Amazon server, where log file is placed. During redirection request headers are also redirected. But Amazon server cannot recognize such authentication token.

Solution:
Catch redirection on getting plain log file and remove authentication token from request headers. Issue is resolved in this way. Hope, this will help somebody.

Would be nice to specify such behaviour somewhere.

**Comment by joshk** [comment]
Sorry that you didn't receive a reply from us on this issue. I have pinged @rkh who will get back to you later today via this issue.

**Comment by rkh** [comment]
Hi @brave-warrior. Sorry for not documenting this. We're planning to rework the logs API, as it is actually a bug in the API.
