### ISSUE TITLE
dist trusty failed to set up environment for building R package 

### ISSUE THREAD

**Issue by maverickg** [travis-ci/travis-ci#5086]
It failed when it needs command line prompt, see https://travis-ci.org/stan-dev/rstan/jobs/90447999

@craigcitro  @hadley

**Comment by craigcitro** [comment]
... did this behavior change from precise to trusty?

**Comment by maverickg** [comment]
There was no such a problem for the old dist.  But I guess there is no harm to add `-y` to `apt install` even though it is not necessary for precise.
