### ISSUE TITLE
MySQL fails to start during build

### ISSUE THREAD

**Issue by dastergon** [travis-ci/travis-ci#5088]
Hello,

I am trying to migrate a repo from Ubuntu `precise` to `trusty-beta` but I stumbled upon some issues with `mysql` service.

In the documentation about [trusty](http://docs.travis-ci.com/user/trusty-ci-environment/#Data-Stores) it is mentioned that MySQL is pre-installed and should be enabled via `services` key. However, when the build starts I get the following error in the `services` phase.

![screen shot 2015-11-11 at 3 17 16 pm](https://cloud.githubusercontent.com/assets/1192342/11091865/6c373080-8887-11e5-8e1f-4ede138f1920.png)

The build can be found [here](https://travis-ci.org/codebendercc/eratosthenes/builds/90513856).
My `.travis.yml` file is also [here](https://github.com/codebendercc/eratosthenes/blob/travis-trusty-beta/.travis.yml)

Thanks in advance,
Pavlos

**Comment by BanzaiMan** [comment]
Sorry for the confusion. MySQL was erroneously mentioned in the docs. We do not yet support MySQL on Trusty. If you wish, please use `sudo` and install packages on Trusty.

**Comment by dnvriend** [comment]
I never want to nitpick .. but its 2016-07-30 as of now, and the ticket is of 2015-11-12, and the docs still show the erroneously information, I just figured out.. :(
