### ISSUE TITLE
SauceConnect tunnel is suddenly not working

### ISSUE THREAD

**Issue by rnicholus** [travis-ci/travis-ci#5089]
After no changes to [my build](https://github.com/Widen/fullstack-react/blob/testing/.travis.yml), Selenium tests using SauceLabs are no longer working. The immediate symptom is a test failure due to inability to locate elements on the page. Looking closer, the SauceConnect tunnel, which is active, is not able to communicate with the server started as part of my Travis build. The SauceLabs job details indicate that this is a tunneling issue, as I am seeing "SauceConnect disabled". 

Here is a passing test from a few days back: https://saucelabs.com/beta/tests/8df3fa8265ec4e14a797931a37738479/commands

And a failing one from today: https://saucelabs.com/beta/tests/1ccf2a0c36e34343b5533aeda6eb08f3/commands

You can clearly see that one has a tunnel ID in the details (passing test) and one does not (failing test). Seems like something changed outside of my code recently.

**Comment by rnicholus** [comment]
Update: Everything works fine if I run my test and tunnel locally. So the issue does appear to be with Travis.

**Comment by rnicholus** [comment]
Looks like the issue still exists as of today. My configuration is very basic, and everything was working a little while back. Any insight into this issue?

**Comment by rnicholus** [comment]
Still perplexed. My setup is fairly simple, and it _was_ working at one point without any obvious changes on my end. Even a "you're an idiot, xyz in your config is completely wrong" would be helpful at this point.

**Comment by BanzaiMan** [comment]
Hello. The latest build seems to be working correctly. https://travis-ci.org/Widen/fullstack-react/jobs/90558318#L1328 Am I mistaken?

**Comment by rnicholus** [comment]
@BanzaiMan That build is failing. The SC tunnel is started, but there is no actual tunnel between Travis and SL. The links in my initial description provide further information in this regard.

**Comment by BanzaiMan** [comment]
The tunnel starts up here, no? https://travis-ci.org/Widen/fullstack-react/jobs/90558318#L1247

The error seems to come from your code: https://travis-ci.org/Widen/fullstack-react/jobs/90558318#L1285

And the tunnel is closed line 1328.

**Comment by rnicholus** [comment]
The error message you are seeing is a red herring. If I run the tests locally and start up my own Sauce tunnel, everything works fine. Also, the same exact tests were passing without any notable code changes a week or so back. 

On the Sauce Labs side, a passing test initiated by Travis yields a tunnel ID on the VM dashboard (first link in my question above). When running the build now, the same VM on the Sauce Labs side yields a "Sauce Connect Disabled" message. This suggests that the tunnel is not working correctly. **The tests are failing because there is no connection between Sauce Labs and the Travis build server**.

**Comment by albedithdiaz** [comment]
Hi,
I was able to run my test using Travis and a Sauce Connect tunnel. On my end all I had to do was add the following to my .travis.yml file:
```
addons:
  sauce_connect: true
```
And add the following desired capability in my test script:
```
desired_capabilities['tunnel-identifier'] = os.environ.get('TRAVIS_JOB_NUMBER')
```
This is the resulting test: https://saucelabs.com/beta/tests/019db4dd2b274da9b4bcb36f851e31ad/commands
Also you can find my repository here: https://github.com/albedithdiaz/Travis

I noticed that when a Sauce Connect tunnel is started through Travis it will have a tunnel identifier which your test script needs to know of if you want it to run using the tunnel. This is the reason why you need to specify the tunnel identifier in the desired capabilities.

I hope that helps!

**Comment by rnicholus** [comment]
@albedithdiaz Thanks for the response! I've been able to get it working before with similar config, as you can see from the history of attempts in my project. It seems like something else is at play here.

Looks like I'll have to chalk this up to SauceLabs being unreliable. Now I'm only able to get the SL tunnel up about 10% of the time locally. On top of that, SauceLabs docs site is completely down. Guess I'll have to find a new cloud VM provider for selenium testing. Thanks everyone for your time.
