### ISSUE TITLE
NPM builds triggered from Pull Requests should not trigger a release

### ISSUE THREAD

**Issue by mstade** [travis-ci/travis-ci#5090]
[The documentation says][1]:

> Builds triggered from Pull Requests will never trigger a release.

[1]: http://docs.travis-ci.com/user/deployment/npm/#What-to-release

Yet when I create a pull request, bump a version, and push the tags, Travis will dutifully deploy to npm. So it seems this is either a bug in Travis, a bug in the documentation, or I'm misusing the thing altogether. For reference, the pull request is websdk/nap#31 – any help is much appreciated!

**Comment by clayreimann** [comment]
Dup of #5073

**Comment by mstade** [comment]
Drats, and I searched for this issue and everything. Not to self, include "PR" in the search next time. :o)

Thanks for noticing and linking the issues, @clayreimann. Here's hoping it get fixed one way or the other, soon.
