### ISSUE TITLE
apache module autz_host not working

### ISSUE THREAD

**Issue by SHoogland** [travis-ci/travis-ci#5094]
I am trying to validate my apache config.
the build logs show that the autz_host module is being enabled.
but the validation test still fails over "Order", see build:
https://travis-ci.org/SHoogland/apacheConfig/builds/90717772

**Comment by BanzaiMan** [comment]
Sorry, we don't know too much about Apache configuration. If the problem persists with the legacy infrastructure, we can spin up a debug VM for you. Alternatively, you can use our PHP Docker image, found at https://quay.io/repository/travisci/travis-php to troubleshoot.

**Comment by SHoogland** [comment]
Alright, Thanks for the reply ill keep trying some things.
