### ISSUE TITLE
Build in Python 3.5 failing at pip install

### ISSUE THREAD

**Issue by theherk** [travis-ci/travis-ci#5097]
Very little changed since the last build (nothing in .travis.yml). I cannot tell what is causing the issue in building theherk/pinkopy.

I would have just asked on SO, but given the simplicity of the task, I am thinking there is an interesting issue happening.

```
Python 3.5.0
$ pip --version
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Current thread 0x00007fe307c61700 (most recent call first):
/home/travis/build.sh: line 45:  1791 Aborted                 (core dumped) pip --version
0.12s$ pip install .
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Current thread 0x00007fd306817700 (most recent call first):
/home/travis/build.sh: line 45:  1797 Aborted                 (core dumped) pip install .
The command "pip install ." failed and exited with 134 during .
Your build has been stopped.
```

edit: It is worth adding that I can get around this without a problem, because I don't really need to do the installation in this library, but I think something interesting is going on.

**Comment by gasman** [comment]
Also happening here: https://travis-ci.org/torchbox/wagtail/builds/90770305. Same repo built successfully 7 days ago, with no substantive code changes since then: https://travis-ci.org/torchbox/wagtail/builds/90770305

**Comment by BanzaiMan** [comment]
We changed the way on-demand installation is done. There might have been an issue with the new archives. Could you try restarting failing builds?

**Comment by theherk** [comment]
Great @BanzaiMan; back to working. I don't know what you did, but it was the right thing. Thanks a bunch.

**Comment by BanzaiMan** [comment]
@theherk Thanks for the confirmation. Sorry for the troubles.
