### ISSUE TITLE
API should handle unescaped URIs

### ISSUE THREAD

**Issue by supermarin** [travis-ci/travis-ci#5101]
Triggering jobs via API requires the user to manually escape slashes into `%2F`.
It makes the URI harder to read, because escaping happens *only* in the slug:

``` bash
    curl --silent --request POST --data "$body" \
        --header "Content-Type: application/json" \
        --header "Accept: application/json" \
        --header "Travis-API-Version: 3" \
        --header "Authorization: token $TRAVIS_TOKEN" \
        "https://api.travis-ci.com/repo/user%2Frepo/requests"
```

And it makes the end user do terrible things like this to invoke jobs:

``` bash
travis_slug=${GITHUB_SLUG//\//%2F}
```

**Comment by rkh** [comment]
I'm very :-1: on this. It's causing issues in our old API at the moment (try calling your repository "settings" or "requests").

Escaping happens properly as defined by RFC 6570 and RFC 3986.

If the URI is not written by hand, but generated, I would recommend to do proper URI escaping in the first place. Better yet, actually use a URI Template library. That way you'll make sure this easily works with Travis Enterprise.

Not 100% sure what the best way in Bash would be, in Ruby I'd do something like this:

``` ruby
require 'addressable/template'

# this can also be programatically discovered by fetching https://api.travis-ci.com/
template = 'https://api.travis-ci.com/repo/{repository.slug}/requests'
url      = template.expand("repository.slug" => "user/repo")

HTTP.post(url, ...)
```

**Comment by BanzaiMan** [comment]
Closing for now.
