### ISSUE TITLE
npm install from private github repo fails

### ISSUE THREAD

**Issue by b-dur** [travis-ci/travis-ci#5103]
Travis can't access private Github repo when doing npm install on new projects. This hasn't been an issue for us before. 

I just created a new repo by cloning an existing and working project. The new cloned repo is failing in Travis.

The only difference I can see between the two Travis projects is that the SSH key for the working project has a different name and can be deleted and the new project has a default key which can't be deleted.

Has there been done any changes on how Travis is creating SSH keys to github?

**Comment by BanzaiMan** [comment]
@b-dur Sorry for the issue. Do you have a build log URL to show this problem?

**Comment by b-dur** [comment]
@BanzaiMan It is a private build project, but this path was logged on error:  `/home/travis/build/trustpilot/B2bDashboardApp/npm-debug.log`
Is this helpful?

**Comment by BanzaiMan** [comment]
@b-dur Looks like this repository never had a build with successful install of this private dependency. From your description, I think that the working repo was set up with "[Deploy key](http://docs.travis-ci.com/user/private-dependencies/#Deploy-Key)", while this one was not. Could you review the documentation and see if works for you?

**Comment by b-dur** [comment]
Both repos have configured a Deploy key, which happens when enabling a repo build in Travis.

When I look at the deploy key in Github I can see following
Working repo: the key has never been used 
Broken repo: the key has been used

The working repo logs
`Installing an SSH key from: repository settings`

The broken repo logs
`Installing an SSH key from: default repository key`

We have a dedicated Github user for Travis, which have access to all repositories (working, broken, and the private repos)
My feeling is that the working repo is accessing the repo using the Github user, while the broken (newer) build is using the deploy key (which doesn't have access to the private repo).

**Comment by b-dur** [comment]
Got it solved.
Had to generate a ssh key using `travis sshkey --generate`
