### ISSUE TITLE
APT whitelist request for dos2unix

### ISSUE THREAD

**Issue by mernst** [travis-ci/travis-ci#5105]
Could you please whitelist the dos2unix package so that I can install it with .travis.yml syntax like this?

```addons:
  apt:
    packages:
    - dos2unix
```

Thanks!

**Comment by BanzaiMan** [comment]
Hello. Thanks for opening the issue, but this is not the right place. Please follow the instructions given in https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

Thanks.
