### ISSUE TITLE
New Python 2.7.10 build compiled with 2byte wide Unicode Characters

### ISSUE THREAD

**Issue by ewdurbin** [travis-ci/travis-ci#5107]
Previously, 2.7.9 was compiled with 4byte wide unicode characters.

This has lead to broken builds for us with trusty, since we were packaging wheels of `psycopg2`, `gevent`, and others for our imaging tasks.

Error is:

```
undefined symbol: PyUnicodeUCS2_AsUTF8String
```

When importing on the target system (Ubuntu 14.04, Default Python 2.7.6).

a test for unicode character width:

```
python -c "import sys; opts = {1114111: 'ucs4', 65535: 'ucs2'}; print(opts.get(sys.maxunicode));"
```

shows that travis builds with 2.7.10 are building with 2byte width, while ubuntu 14.04 has 4byte width.

Thanks.

**Comment by ewdurbin** [comment]
if you decide to go with 4-byte unicode characters, the new 2.7.10 build should use `--enable-unicode=ucs4`

**Comment by ewdurbin** [comment]
```
sudo: required
dist: trusty
language: python
python:
- '2.7'
```

Possibly relevant parts of our `.travis.yml`

**Comment by ewdurbin** [comment]
seems only by setting `dist: trusty` gets this build of Python 2.7.10, which is compiled with `ucs2`

removing `dist: trusty` gets a build of Python 2.7.9, compiled with `ucs4`

**Comment by pfhayes** [comment]
+1, I've also observed this issue after migrating to trusty

**Comment by holm** [comment]
We have also been bitten by this now

**Comment by jtschichold** [comment]
Same problem. Wheels with native extensions built on Travis-CI trusty can't be used on stock Ubuntu Trusty. I have solved this by switching to "language: c" to avoid the initial virtualenv and changing the readding /usr/bin at the beginning of the PATH to avoid the alternative python2.7.10 installed in a /opt subdirectory. Ugly workaround.

**Comment by BanzaiMan** [comment]
This is the sam issue as #4948, right?

**Comment by BanzaiMan** [comment]
A new 2.7(.10) archive with 4-byte unicode characters will be available shortly.

**Comment by pfhayes** [comment]
@BanzaiMan is the new archive available? Do we need to change anything to use this or will it be the default?

**Comment by BanzaiMan** [comment]
The new archive is downloaded and installed if it is not available locally. This holds for `2.7` and `2.7.10`.

**Comment by pfhayes** [comment]
Our builds appear to still be using a UCS2 version. Our .travis.yml looks like this:

```yml
language: python

sudo: required
dist: trusty

python:
  - '2.7'

addons:
  postgresql: '9.3'
  artifacts:
    paths:
    - [redacted]

install:
- python -c "import sys; print ('UCS4 build' if sys.maxunicode > 65535 else 'UCS2 build')"
- [redacted]
```

The command in `install` prints `UCS2 build`

**Comment by pfhayes** [comment]
@BanzaiMan is this expected behaviour? is there something else I need to configure on my end?

**Comment by tbarbugli** [comment]
any updates on this?

**Comment by BanzaiMan** [comment]
On Trusty, 2.7.10 (USC2 build) is preinstalled, so this won't work until the image is updated. `2.7.11` should work.

**Comment by tbarbugli** [comment]
you mean, if I select python `2.7.11` I get USC4?

**Comment by BanzaiMan** [comment]
Yes.
