### ISSUE TITLE
embedding deploy config in .travis.yml

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#5109]
It would be good to have as an option a possibility to embed deployment configuration right in .travis.yml.

For example, right now I have a separate JSON file which describes deployment to bintray. Would be nice to have that JSON snippet inside travis.yml as a subfield of deploy:

```
deploy:
- provider: bintray
  config: {...JSON...}

```

this would reduce amount of files lurking here and there.

**Comment by BanzaiMan** [comment]
> this would reduce amount of files lurking here and there.

Could you elaborate on this?

In general, though, I am :-1: on adding a preprocessing step to build configuration.

**Comment by igagis** [comment]
Why adding preprocessing step? It is not a preprocessing. It is postprocessing. The only difference is that right now bintray deployer takes its config from a separate file indicated in travis.yml:

```
deploy:
- provider: bintray
  file: bintray_config.json
```

I just propose to make it possible to configure the deployer right here in travis yml.

Either by allowing embedding that bintray_config.json file contents right in travis.yml as follows:

```
deploy:
- provider: bintray
  config: {...bintray inlined JSON...}
```

or by allowing configuration of bintray deployer in YAML right in travis.yml:

```
deploy:
- provider: bintray
  package: libsomething
  repo: deb
  files: "../(.[^/]*(\\.deb)$)"
  ...etc.
```

**Comment by igagis** [comment]
invalid
