### ISSUE TITLE
PHP 7 build is broken

### ISSUE THREAD

**Issue by mhujer** [travis-ci/travis-ci#5111]
See https://travis-ci.org/mhujer/json-simple-db/jobs/91164148

```
...
7 is not pre-installed; installing
tar: 7.0snapshot: Cannot mkdir: Permission denied
tar: 7.0snapshot: Cannot mkdir: Permission denied
tar: 7.0snapshot/share: Cannot mkdir: No such file or directory
tar: 7.0snapshot: Cannot mkdir: Permission denied
tar: 7.0snapshot/share/xdebug: Cannot mkdir: No such file or directory
tar: 7.0snapshot: Cannot mkdir: Permission denied
tar: 7.0snapshot/share/pyrus: Cannot mkdir: No such file or directory
tar: 7.0snapshot: Cannot mkdir: Permission denied
tar: 7.0snapshot/share/pyrus/.pear: Cannot mkdir: No such file or directory
tar: 7.0snapshot: Cannot mkdir: Permission denied
...
```

**Comment by nubs** [comment]
I am seeing the same thing.  Here's another link to a build: https://travis-ci.org/nubs/vectorix/jobs/91178645

**Comment by arcanedev-maroc** [comment]
Same here : https://travis-ci.org/ARCANEDEV/LogViewer/jobs/91190667

**Comment by bugalot** [comment]
Same here:

https://travis-ci.org/oat-sa/qti-sdk/jobs/91262364

**Comment by Francismori7** [comment]
Same here.

**Comment by bzick** [comment]
+1

**Comment by BanzaiMan** [comment]
Sorry for the breakage. I have some ideas about how it broke and how we can fix it. I plan to work on it Monday.

**Comment by nubs** [comment]
This seems to be working now

**Comment by arcanedev-maroc** [comment]
@nubs nice :+1:

**Comment by krakjoe** [comment]
Working now, thanks for speedy fix :+1:

**Comment by dmecke** [comment]
Thanks for your responsiveness and the quick fix! :+1:

**Comment by mhujer** [comment]
Thanks for fixing it!

**Comment by pdt256** [comment]
This appears to be broken again.
https://travis-ci.org/inklabs/kommerce-core/jobs/91949611

**Comment by BanzaiMan** [comment]
Sorry about that. I'll take a look tomorrow.

**Comment by ntwb** [comment]
Just adding myself here and noting that the WordPress builds are also affected by this:
https://travis-ci.org/aaronjorbin/develop.wordpress/builds

**Comment by mathmarques** [comment]
Same here:
https://travis-ci.org/mathmarques/Smarty-View/jobs/91974790

**Comment by alxmsl** [comment]
the same here: https://travis-ci.org/alxmsl/TelegramBotClient/jobs/91975688

**Comment by valendesigns** [comment]
Same here

**Comment by keradus** [comment]
same https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/91932810

**Comment by pamil** [comment]
Happens also on Sylius: https://travis-ci.org/pamil/Sylius/jobs/91995798

**Comment by chrismou** [comment]
Is this likely to be an ongoing issue? I'm tempted to add php7 as an allowed failure until it's been nailed for good

**Comment by Soullivaneuh** [comment]
Same here: https://travis-ci.org/Soullivaneuh/php-cs-fixer-styleci-bridge/jobs/92007516

**Comment by JanPietrzyk** [comment]
same in my private repos

**Comment by casperbakker** [comment]
Yep, broken in private repos here as well :cry:

**Comment by steefaan** [comment]
Same here.

**Comment by BanzaiMan** [comment]
This should be fixed now. https://travis-ci.org/BanzaiMan/travis_production_test/builds/92067772

The reason that it was broken, then was working for a while, then broken again, is a bit of implementation detail. We standardized some parts associated with the on-demand language installations, but the archive creation process was a bit off. I fixed this, and it should work reliably going forward.

**Comment by nubs** [comment]
Thanks @BanzaiMan!

**Comment by keradus** [comment]
You have saved the world @BanzaiMan :D

**Comment by chrismou** [comment]
Cheers @BanzaiMan, looks to be back to normal :+1:

**Comment by rdeutz** [comment]
Looks good Thanks @BanzaiMan

**Comment by ntwb** [comment]
Thanks :+1:

**Comment by avdevs** [comment]
Only PHP7 build fails for concrete5 build :
https://travis-ci.org/concrete5/concrete5/builds/96022311
https://travis-ci.org/concrete5/concrete5/builds/96041906
https://travis-ci.org/concrete5/concrete5/builds/96005274

and many more

How can i solve php7 issue?
is that problem with travis-ci or it something like programatic fault?

**Comment by BanzaiMan** [comment]
@avdevs That `phpunit` issue was reported as #5267, which was subsequently fixed. If you rerun the failing jobs, they should pass.

The problems this issue addresses have been fixed. If you experience problems with PHP 7, please open a new issue, rather than tacking on to this issue.

I'm locking this now.
