### ISSUE TITLE
How to make travisbot understand deb source line for adding package to source whitelist

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#5112]
I've tried to add `wine1.7` into APT source whitelist in here: https://github.com/travis-ci/apt-package-whitelist/issues/1768

however @travisbot said it couldn't find source package.

In [here](https://github.com/travis-ci/apt-source-whitelist#source-approval-process) I could read:

> The body of the issue must include the "deb source line" which may be a ppa alias such as `ppa:fkrull/deadsnakes`. If the deb source is not a PPA, you must also include the URL to the GPG key.

which I did by specifying:

Deb source line:

    deb http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu vivid main
    deb-src http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu vivid main

Can anybody tell me what is the right syntax, so @travisbot can understand it?

**Comment by SlySven** [comment]
It seems you might have to have the title line of your PR as:
```
APT source whitelist request for ppa:ubuntu-wine/ppa
```
Obviously the 'bot does not understand the line unless it is in exactly the right form, the above is a _guess_ on my part.  I note you specified ```vivid``` but be aware that the default Travis Linux platform is a ```preciseLTS```  distribution (though I think you can manually specify a ```trusty``` one in your ```.travis.xml``` file)...

**Comment by BanzaiMan** [comment]
Please review the documentation here: http://docs.travis-ci.com/user/apt/#Adding-APT-Sources

The source whitelist is handled separately.
