### ISSUE TITLE
My build is getting killed

### ISSUE THREAD

**Issue by retorquere** [travis-ci/travis-ci#5114]
My builds are getting killed (see eg [here](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/91284283#L766)) but I have no idea why. It runs fine locally.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/91284283#L768 says that the command exited with status 137, which is often an indication of memory exhaustion.

**Comment by retorquere** [comment]
The same builds have started succeeding. Odd.

**Comment by BanzaiMan** [comment]
Could your build, or noisy neighbors. For now, I'm closing this.
