### ISSUE TITLE
Cache compiling something in the background + `missing config` despite .travis.yml is present.

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#5115]
I've added the following lines in my `.travis.yml`:

	cache:
	  - apt
	  - pip
	  directories:
	    - /opt
	    - ~/.wine

but my build behave weird with a lot of logs at the start, see [here](https://travis-ci.org/EA31337/EA31337-Sets/builds/90722441).

Something like:

    removing: _configtest.c _configtest.o
    C compiler: gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/opt/python/2.6.9/include/python2.6 -c'
    gcc: _configtest.c
    _configtest.c:5:5: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/opt/python/2.6.9/include/python2.6 -c'
    gcc: _configtest.c
    _configtest.c:5:5: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    success!
    removing: _configtest.cpip 6.0.7 from /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages (python 3.4)

Even [full log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/90722442/log.txt) is so long, that it doesn't actually finish.

Is that suppose to be there?

**Comment by BanzaiMan** [comment]
That does not look like output from the caching utility, but whatever you are using to compile the code. Please review your tools' documentation to reduce output.

**Comment by kenorb** [comment]
@BanzaiMan The thing is that I don't compile anything and this happens before Travis initialize it-self.

This is way before:

> Build system information
and

> Setting environment variables from .travis.yml

that's why I have no idea what is it, but it's coming from Travis CI, before my `.travis.yml` is even read.

**Comment by BanzaiMan** [comment]
The log is confusing, though. Nothing that we run in before the control gets to user-defined commands will print this information.

**Comment by BanzaiMan** [comment]
PR 12 for your repo did not trigger a build because it was missing `.travis.yml`.
![ea31337_ea31337-sets_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/11196367/9bbd400a-8c84-11e5-82f2-37a7df7a2313.png)
The corresponding commit was https://github.com/EA31337/EA31337-Sets/commit/dded9fb, which indeed lacks the config file. See https://travis-ci.org/EA31337/EA31337-Sets/requests. Your issue in this case is not affected by the issues we had.

Moving back to the original issue at hand, could you try restarting [this build](https://travis-ci.org/EA31337/EA31337-Sets/builds/90722441) to see if we can get a clean, consistent log so that we can look at the issue in more detail?

**Comment by kenorb** [comment]
@BanzaiMan

To double check:

- which config? [`dded9fb` has `.travis.yml`](https://github.com/EA31337/EA31337-Sets/blob/dded9fbdc7809dfbf6efe781d0320fad4fdda9c4/.travis.yml) in [here](https://github.com/EA31337/EA31337-Sets/commit/dded9fb#diff-354f30a63fb0907d4ad57269548329e3), which was just modified to test it (it was in previous and the new commit)

Btw. Build #90722441 seems to be ok now, before it was like compiling NumPy in the background.

**Comment by BanzaiMan** [comment]
Hmm. You're right about that. Could you push another commit?

**Comment by kenorb** [comment]
I did git push to [`travis-cache-test` branch](https://github.com/EA31337/EA31337-Sets/commit/90aebf55b781fba2aa1caee81713b865e8d30feb). I can't see Requests tab anymore to check what's the error, but doesn't seems it [picked it up](https://github.com/EA31337/EA31337-Sets/commits/travis-cache-test).

**Comment by BanzaiMan** [comment]
Ah, sorry about that. This `missing config` in https://travis-ci.org/EA31337/EA31337-Sets/requests can also mean badly formatted YAML file, which is the case here. We are not relaying this information effectively.

Here's the log for the `missing config` for the latest commit:

    Nov 24 12:05:28 travis-gatekeeper app/gator.1:  E TID=70270790525900 [fetchconfig] [request:fetch_config] Error parsing .travis.yml for https://api.github.com/repos/EA31337/EA31337-Sets/contents/.travis.yml?client_id=f244293c729d5066cf27&client_secret=854b82528a65e6a7a32da4a8120e5f53224ebc79&ref=90aebf55b781fba2aa1caee81713b865e8d30feb: (<unknown>): did not find expected '-' indicator while parsing a block collection at line 11 column 3 

Fix this, and let us try again.

**Comment by kenorb** [comment]
Fixed, it works now.

Probably because I was wrongly trying mix different [`caching`](https://docs.travis-ci.com/user/caching/), so:

	cache:
	- bundler
	- apt

with:

	cache:
	  directories:
	  - vendor/something
	  - .autoconf

so the correct syntax is:

	cache:
	  apt: true
	  directories:
	  - vendor/something
	  - .autoconf


So the cache worked, I'll re-test further more to see if there are any other issues.

Yes, the error is misleading. It should say `syntax error` instead of `missing config`.

As when validating the config file at https://lint.travis-ci.org/
