### ISSUE TITLE
PHP7.1

### ISSUE THREAD

**Issue by krakjoe** [travis-ci/travis-ci#5117]
PHP7.0 has been branched already, so now master is 7.1 and 7.0 is a separate branch, they have already diverged quite a bit.

Is there a way to use php-src master ?

Alternatively can 7.1 be added as a php environment ?

**Comment by BanzaiMan** [comment]
You can use `nightly` for this purpose. https://travis-ci.org/BanzaiMan/travis_production_test/builds/91370358#L89

**Comment by krakjoe** [comment]
Thanks muchly ...
