### ISSUE TITLE
Default install step for Go builds

### ISSUE THREAD

**Issue by AntoineAugusti** [travis-ci/travis-ci#5123]
Hi,

Did you change recently the default install steps for Go builds? It seems that you were doing `go get -t -v ./…` if the Travis file was missing an install section but this behaviour has been removed.

See the following builds:
- Silent install command: https://travis-ci.org/AntoineAugusti/moduluschecking-api/builds/90996123
- Install section was replaced with `true`: https://travis-ci.org/AntoineAugusti/moduluschecking-api/builds/91149566
- Build is fixed by moving the command to the `before_install` section: https://travis-ci.org/AntoineAugusti/moduluschecking-api/builds/91199592

**Comment by meatballhat** [comment]
@AntoineAugusti this is "correct" behavior when a makefile is present, although we could certainly make it more obvious what's going on.  See: https://github.com/travis-ci/travis-build/blob/7a7c4706d0ae01932c615db198e9ae253ba31b6f/lib/travis/build/script/go.rb#L87-L104
