### ISSUE TITLE
Travis CI not starting builds and can't stop and restart build

### ISSUE THREAD

**Issue by graemerocher** [travis-ci/travis-ci#5124]
Our builds are not starting at the moment:

https://travis-ci.org/grails/grails-data-mapping/builds/91397840

If I try and stop and restart the build it doesn't seem to do anything

Any ideas?

**Comment by BanzaiMan** [comment]
Sorry about the troubles. We are investigating this issue now. http://stspg.io/1flZ

Please follow that issue there. Thanks.

**Comment by rnicholus** [comment]
I'm seeing the same problem now as well. https://travis-ci.org/Widen/fullstack-react/builds/91613882

**Comment by brianjmiller** [comment]
+1 https://travis-ci.org/RusticiSoftware/TinCanPHP/builds/91614248

**Comment by Nadahar** [comment]
[It seems] (https://www.traviscistatus.com/) they have gotten the queue moving again, but I'm betting there's some catching up to do before the queues are processed.

**Comment by BanzaiMan** [comment]
Sorry about the issue. We had a couple of issues to halt build processing today. They are resolved, so I'm going to close this ticket now.

If you see a new problem, please open a new one.
