### ISSUE TITLE
Xcode version gets reported in travis ui even for linux builds

### ISSUE THREAD

**Issue by thomasvl** [travis-ci/travis-ci#5125]
[Sorta spun out of issue 3975.]

If a build is mult-ios, it seems the Xcode version gets reported even for platforms where the info doesn't apply.

Google's protobuf setup builds on linux and OS X.  Since issue 3975 recently got fixed, we were able to add in Objective C testing to the mix of languages by adding the osx_image tag and extending out script.  But now it seems every build, even the ones on linux, list the Xcode version.  Example: https://travis-ci.org/google/protobuf/builds/91337154

This info should only get reported for OS X builds where it applies.

**Comment by BanzaiMan** [comment]
@thomasvl You have `osx_image` defined on the top level of your `.travis.yml`, so that value is effective for all jobs in the matrix. https://github.com/google/protobuf/blob/a0066f4f75e2929296a0cc9eba55aebfcbda14b7/.travis.yml#L11

**Comment by thomasvl** [comment]
The tag only seems to work at the top level, in the past I wasn't able to list it under just the OS X builds and have it honored.  Is it now supported when nested within the matrix?

Even though it is top level, it doesn't mean anything on non OS X VMs, so why should it get listed on those?

**Comment by BanzaiMan** [comment]
It is not intuitive, to be sure.

**Comment by yiwu-arbug** [comment]
Bump. Any chance this get a fix? Seeing the same bug for RocksDB repo: https://travis-ci.org/facebook/rocksdb

**Comment by tkittel** [comment]
Bump again. Same issue seen on https://travis-ci.org/mctools/ncrystal/builds/332163335

**Comment by graingert** [comment]
@thomasvl can you re-open? I also added an issue to https://travis-ci.community/t/xcode-version-gets-reported-in-travis-ui-even-for-linux-builds-5125/2047

**Comment by chrahunt** [comment]
Additionally, if you have multiple `osx_image` it looks like an entry is generated in the build matrix for linux for each `osx_image` value. See [here](https://travis-ci.com/chrahunt/pyenv/builds/101368779) for example. I have raised this issue with support.

**Comment by graingert** [comment]
Travis should clearly just reuse the dist keyword
