### ISSUE TITLE
Can't sync Github with Travis CI

### ISSUE THREAD

**Issue by brianmontanaweb** [travis-ci/travis-ci#5126]
Both Travis CI and Travis CI Pro have access but only Travis CI Pro is showing the repositories.

**Comment by joshk** [comment]
Hi @brianmontanaweb 

Are you not seeing any public repos on travis-ci.org?

Have you recently signed up?

**Comment by brianmontanaweb** [comment]
Yup signed up this morning but can't see anything that's public

**Comment by joshk** [comment]
I just fixed the issue, can you go back to your profile page and you should see your repos which you can now activate.

**Comment by joshk** [comment]
Closing this optimistically.

**Comment by brianmontanaweb** [comment]
Yup, perfect! Thanks!
