### ISSUE TITLE
Running MongoDB service in container based infrastructure

### ISSUE THREAD

**Issue by stremlenye** [travis-ci/travis-ci#5128]
I have such build definition:
```yaml
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
services:
  - mongodb
```
and seems like tests have no chance to access mongo service on a url "mongodb://127.0.0.1:27017" as far as log include such text:
```sh
$ sudo service mongodb start
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
```

**Comment by BanzaiMan** [comment]
@stremlenye Do you have a build log URL to show that you cannot connect to the MongoDB server? From the look of the log you've shown, it appears to me that:

1. The service is started
1. You are seeing the message about the container-based infrastructure which we print after the service has already started.

**Comment by stremlenye** [comment]
Sure, here it is: https://travis-ci.org/stremlenye/Tasks4Squares.server

**Comment by BanzaiMan** [comment]
It's starting. https://travis-ci.org/stremlenye/Tasks4Squares.server/builds/91588182#L84

And the port 27017 is open: https://travis-ci.org/BanzaiMan/travis_production_test/builds/91602800#L98

If you are seeing connexion issues, it is due to something else.

**Comment by stremlenye** [comment]
Thank you for explanation. I'll try to figure out what wrong and close the issue for now.
