### ISSUE TITLE
Installing lxml under pypy broken

### ISSUE THREAD

**Issue by untitaker** [travis-ci/travis-ci#5130]
Basically I'm hitting https://bugs.launchpad.net/lxml/+bug/1377501, see https://travis-ci.org/untitaker/vdirsyncer/jobs/91042854

However, this happens under the `pypy` target, which is not supposed to be PyPy3. Unfortunately I can't verify the actual Python version used in that build since the logging seems to be broken.

**Comment by BanzaiMan** [comment]
Sorry about the logs issue. https://s3.amazonaws.com/archive.travis-ci.org/jobs/91042854/log.txt shows that it is PyPy 2.5.

**Comment by BanzaiMan** [comment]
@alex Do you have any insight?

**Comment by alex** [comment]
PyPy 2.5 is extremely old at this point, Travis CI should really upgrade to a modern PyPy (2.6.1, or ideally 4.0).

**Comment by Wooble** [comment]
It looks like this is caused by a new release of lxml; version 3.4.4 was building fine under pypy 2.5 last week, and version 3.5 is erroring.

**Comment by untitaker** [comment]
Any update on this? It's been quite a long time since the PyPy build is broken.

**Comment by untitaker** [comment]
Note that this breaks also for me with pypy 2.6.1 or 4.0.1. As @Wooble said, lxml==3.5 fails to install, older versions work.

**Comment by untitaker** [comment]
fijal on `#pypy` said that this is a long-standing problem with LXML. See http://packages.pypy.org/

This is not a Travis issue in either case, although updating PyPy would certainly help.
