### ISSUE TITLE
Travis Network related issues

### ISSUE THREAD

**Issue by odeceepsenger** [travis-ci/travis-ci#5135]
We have a paid subscription, our server is [https://magnum.travis-ci.com/woolworthslimited/api-search-v3/builds  ](https://magnum.travis-ci.com/woolworthslimited/api-search-v3/builds ) We use Maven for our Node JS / Apigee build. It pulls artifacts from a nexus/maven repo on the internet from 

```
http://repo.apigee.com:8081/artifactory/repo
```

**This process has worked for months.** Now it times out, but only in the Travis environment. I know this because, I can run it locally and it works. I can run it from the local Coffee shop, my office, or in the Library, and it works
.

```
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1000)
	... 43 more
Caused by: java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
```

I added this line to my travis yaml file and ran Travis Lint against the file and it passed.
 
```
install: travis_wait mvn install
```

However, I get this error.

```
The command "travis_wait mvn install" exited with 1.
```

**Comment by BanzaiMan** [comment]
Sorry for the issues and the tardy reply. Is this still a problem? Did this ever work on Travis? Is this host reachable? I just tried it on my machine (physically located in Japan), and the connexion timed out.

```sh-session
$ curl http://repo.apigee.com:8081/artifactory/repo
curl: (7) Failed to connect to repo.apigee.com port 8081: Operation timed out
```

**Comment by odeceepsenger** [comment]
Close the ticket, Apigee moved the server. We are good now.

On 11 December 2015 at 10:13, Hiro Asari <notifications@github.com> wrote:

> Sorry for the issues and the tardy reply. Is this still a problem? Did
> this ever work on Travis? Is this host reachable? I just tried it on my
> machine (physically located in Japan), and the connexion timed out.
>
> $ curl http://repo.apigee.com:8081/artifactory/repocurl: (7) Failed to connect to repo.apigee.com port 8081: Operation timed out
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/travis-ci/issues/5135#issuecomment-163782879>
> .
>



-- 

*Regards,*
*Philip Senger*

P: 0406 770 664 | E: psenger@woolworths.com.au

-- 
CAUTION: This email and files included in its transmission are solely 
intended for the use of the addressee(s) and may contain information that 
is confidential and privileged. If you receive this email in error, please 
advise us immediately and delete it without copying the contents contained 
within. Woolworths Limited (including its group of companies) do not accept 
liability for the views expressed within or the consequences of any 
computer viruses that may be transmitted with this email. The contents are 
also subject to copyright. No part of it should be reproduced, adapted or 
transmitted without the written consent of the copyright owner.

**Comment by BanzaiMan** [comment]
@odeceepsenger Thanks for the update!
