### ISSUE TITLE
Cannot run a server

### ISSUE THREAD

**Issue by gocreating** [travis-ci/travis-ci#5139]
I'd like to open a testing server on travis for my nodejs project

both of the ways below didn't work:

1. use nodemon
2. use exec method of child_process

  ```es6
  const exec = require('child_process').exec;
  const child = exec('node build/test/app.js', {
    env: {
      ...process.env,
      NODE_ENV: NODE_ENV,
      EXSEED_INIT: options.init,
    },
  });

  // show outputs in realtime
  child.stdout.on('data', (data) => {
    console.log(data);
  });

  child.stderr.on('data', (data) => {
    console.log(data);
  });
  ```

my app does log something when it starts running, and the test script works properly `locally`:

![image](https://cloud.githubusercontent.com/assets/5002343/11299399/6aa5063e-8fc1-11e5-8a1f-75e5ecff5d4b.png)

but it `always` doesn't open a server on travis:

![image](https://cloud.githubusercontent.com/assets/5002343/11299449/cd69ef6e-8fc1-11e5-8366-e2bdcbfae2a4.png)

anybody know what happened?

**Comment by BanzaiMan** [comment]
What dos `double callback!` mean?

**Comment by gocreating** [comment]
Problem solved!

I ran the mocha test before the server is ready

so just delay 5 seconds before testing and then the problem solved
