### ISSUE TITLE
clang fails in math-finite.h (included from math.h)

### ISSUE THREAD

**Issue by c-lipka** [travis-ci/travis-ci#5140]
The clang C++ build environment does not seem to be set up properly; specifically, in a project I'm trying to build, clang eventually pulls in /usr/include/x86_64-linux-gnu/bits/math-finite.h, but can't digest some language constructs therein:

https://travis-ci.org/c-lipka/povray/jobs/92330742

**Comment by BanzaiMan** [comment]
Thanks for opening the issue, but I believe this is a packaging issue beyond our control. If `math-finite.h` is lacking, then I suggest getting in touch with the package maintainer.

That file belongs to `libc6-dev`, according to `dpkg -S`. https://travis-ci.org/BanzaiMan/travis_production_test/builds/92849731#L196
