### ISSUE TITLE
Some combinations of `services: - docker` + build matrixes can cause build routing issues on GCE 

### ISSUE THREAD

**Issue by dnephin** [travis-ci/travis-ci#5142]
Build: https://travis-ci.org/docker/compose/builds

You can see from [the history](https://travis-ci.org/docker/compose/builds) these builds have been successful for a while, but starting today [the linux builds are failing](https://travis-ci.org/docker/compose/jobs/92293739#L99) with three errors:
* `tar: Error is not recoverable: exiting now` when trying to download python 2.7? (which seems to be non-fatal)
* `docker: unrecognized service` (which seems to be non-fatal)
* followed by `/home/travis/build.sh: line 45: /home/travis/virtualenv/python2.7/bin/activate: No such file or directory` (which is failing the build)

Travis config: https://github.com/docker/compose/blob/master/.travis.yml (hasn't changed in over a month)

The OSX build in the matrix is still passing.

**Comment by liZe** [comment]
Same error here with Python 3.5: https://travis-ci.org/Kozea/CairoSVG/jobs/92360438

**Comment by dnephin** [comment]
I updated the title since it looks like it has more to do with the python setup.

**Comment by solarce** [comment]
Thank you for the error reports, we are looking into this right now

**Comment by BanzaiMan** [comment]
Hi, @liZe, your issue appears to be a different from @dnephin's. Could you restart your failing job to see if it was not a temporary network issue?

**Comment by liZe** [comment]
@BanzaiMan it's fixed, thanks!

**Comment by solarce** [comment]
@dnephin I have determined why your builds started failing. The way your `.travis.yml` is right now is technically wrong but was working because of an edge case which we fixed this week, as part of work we're doing in preparation of supporting both Trusty and Precise on GCE, but which is not meant to be used yet.

Essentially our build routing logic gets fairly complicated when `matrix: include:` is involved and we're discovering edge cases that crop up as we begin to support multiple Ubuntu editions on the same cloud platform, which did not crop up when only one edition was supported.

To get your builds back on track I've submitted a PR of what's needed, https://github.com/docker/compose/pull/2439, you can see a successful build of a simplified example in https://travis-ci.org/solarce/trusty-tests/builds/92375407

**Comment by dnephin** [comment]
Excellent, thanks!

**Comment by solarce** [comment]
https://travis-ci.org/stan-dev/rstan/builds/92346993 is also resulting in a similar routing failure but has a very different matrix setup, need to dig into why

**Comment by pulyaevskiy** [comment]
I'm also getting "docker: unrecognized service" here:
https://travis-ci.org/pulyaevskiy/dart-kafka/builds/92473536

Even initial `sudo service docker start` fails. And I'm not using build matrixes...

**Comment by solarce** [comment]
@pulyaevskiy if you add `dist: trusty` to your .yml it'll work

**Comment by pulyaevskiy** [comment]
thanks @solarce !

Just added but it didn't work for some reason. Worker information still shows precise. 
https://travis-ci.org/pulyaevskiy/dart-kafka/builds/92497318

Anything I'm doing wrong here?

**Comment by meatballhat** [comment]
@pulyaevskiy I'm pretty sure `language: dart` is the issue.  I've just tagged the trusty "mega" images with dart support so that the image selection doesn't fall through to the precise ruby image.  Can you lmk if it's looking better? :heart:

**Comment by pulyaevskiy** [comment]
@meatballhat

Yes, it did help! Thanks a lot!

**Comment by meatballhat** [comment]
@pulyaevskiy excellent, thanks for the follow-up! :heart_eyes_cat:

**Comment by trinitronx** [comment]
Seems that this is a known issue, but in case this helps track things down better...

I just decided to proactively test using the new GCE infrastructure, and have found
that the `docker: unrecognized service` issue affects builds that are using:

```
sudo: required
dist: precise
group: edge

 services:
   - docker
```

Docker package seems to be missing from the GCE precise host build, which causes any builds that use docker to fail.  Getting rid of `dist: precise` or specifying `dist: trusty` forces it to use a trusty host on GCE, which appears to have docker installed.  So the workaround for those who don't need to test specifically on a `12.04 precise` host can use `dist: trusty` or not specify `dist` to get a host that supports docker.

Example builds:

 - With `dist: precise`, `group: edge`: https://travis-ci.org/trinitronx/fastest-servers/builds/93993378
 - Same but without `dist: precise`: https://travis-ci.org/trinitronx/fastest-servers/builds/93995457
 - Same but with `dist: trusty`: https://travis-ci.org/trinitronx/fastest-servers/builds/94001411

**Comment by trinitronx** [comment]
Additional:  The builds I referenced above were not using `language: python`, but `language: ruby` (it seems the worker info has `travis-ci-ruby-precise`, which leads me to believe it's using different base images per-language?).  So hopefully this adds the extra context needed to see what worker types are affected.

**Comment by solarce** [comment]
@trinitronx thanks for the info, we do not support using Docker in your builds on 12.04, only 14.04. So it failing when `services: - docker` is included should be expected.

**Comment by trinitronx** [comment]
@solarce: Gotcha!  Thanks for the info!  I'll leave out the `dist: precise` :smile_cat:

**Comment by solarce** [comment]
These routing issues should be ironed out now. Please re-open if you come across a new one.

**Comment by yurishkuro** [comment]
I just ran into similar issue, the build triggered via matrix/include did not have docker available:

https://travis-ci.org/uber/tchannel-go/jobs/151099064

But after adding `dist: trusty` it worked:

https://travis-ci.org/uber/tchannel-go/jobs/151100813

**Comment by solarce** [comment]
@yurishkuro thank you for the report, this appears to be a case where our build matrix expansion is setting a default of `dist: precise` where it shouldn't, and so explicitly setting `dist: trusty` does get the results you want. 

I'll file an issue about this in the appropriate code base after I cook up a minimal reproducible test case, in the mean time, it is advisable to explicitly set `dist: trusty` if using a list of multiple language runtime versions or a `matrix` block in your `.travis.yml` file
