### ISSUE TITLE
configuration option "php_ini" is not set to php.ini location

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#5143]
When installing APCu through PECL, `extension=apcu.so` is not added to `php.ini` with PHP 7, while it works fine with PHP 5.x
Example of PHP 5.5 log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/92391681/log.txt
Example of PHP 7.0 log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/92391683/log.txt

I first case:
```
Build process completed successfully
Installing '/home/travis/.phpenv/versions/5.5.21/lib/php/extensions/no-debug-zts-20121212/apcu.so'
Installing '/home/travis/.phpenv/versions/5.5.21/include/php/ext/apcu/apc.h'
Installing '/home/travis/.phpenv/versions/5.5.21/include/php/ext/apcu/apc_api.h'
Installing '/home/travis/.phpenv/versions/5.5.21/include/php/ext/apcu/apc_cache_api.h'
Installing '/home/travis/.phpenv/versions/5.5.21/include/php/ext/apcu/apc_lock_api.h'
Installing '/home/travis/.phpenv/versions/5.5.21/include/php/ext/apcu/apc_pool_api.h'
Installing '/home/travis/.phpenv/versions/5.5.21/include/php/ext/apcu/apc_sma_api.h'
Installing '/home/travis/.phpenv/versions/5.5.21/include/php/ext/apcu/apc_bin_api.h'
Installing '/home/travis/.phpenv/versions/5.5.21/include/php/ext/apcu/apc_serializer.h'
install ok: channel://pecl.php.net/apcu-4.0.8
Extension apcu enabled in php.ini
```
In second case:
```
Build process completed successfully
Installing '/home/travis/.phpenv/versions/7.0snapshot/lib/php/extensions/no-debug-zts-20151012/apcu.so'
Installing '/home/travis/.phpenv/versions/7.0snapshot/include/php/ext/apcu/apc.h'
Installing '/home/travis/.phpenv/versions/7.0snapshot/include/php/ext/apcu/apc_api.h'
Installing '/home/travis/.phpenv/versions/7.0snapshot/include/php/ext/apcu/apc_cache_api.h'
Installing '/home/travis/.phpenv/versions/7.0snapshot/include/php/ext/apcu/apc_lock_api.h'
Installing '/home/travis/.phpenv/versions/7.0snapshot/include/php/ext/apcu/apc_pool_api.h'
Installing '/home/travis/.phpenv/versions/7.0snapshot/include/php/ext/apcu/apc_sma_api.h'
Installing '/home/travis/.phpenv/versions/7.0snapshot/include/php/ext/apcu/apc_serializer.h'
install ok: channel://pecl.php.net/apcu-5.1.0
configuration option "php_ini" is not set to php.ini location
You should add "extension=apcu.so" to php.ini
```
`.travis.yml` become unnecessary more complex when overcoming such edge cases with in-line bash conditions.
@BanzaiMan?

**Comment by till** [comment]
Ran into this as well.

**Comment by jmikola** [comment]
Just started seeing this in the [mongodb/mongo-php-library](http://github.com/mongodb/mongo-php-library) builds on 5.4 (c.f. [failed job](https://travis-ci.org/mongodb/mongo-php-library/jobs/97301425)). Manually setting `php_ini` didn't seem to work:

```
pecl config-set php_ini ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
```

For the time being, I suppose we can resort to a conditional echo into the `php.ini` file.

**Comment by nazar-pc** [comment]
This is an old one, do not see this particular issue any more.

**Comment by kwn** [comment]
@nazar-pc 

I've faced that issue recently. I've tried to install rdkafka extension against php 5.4 and the extension hasn't been enabled automatically:

https://travis-ci.org/kwn/monolog-kafka-handler/jobs/131263204#L536

Any suggestions? It seems it's a bug as it happens only for php 5.4. Could you please reopen that issue as it's not fixed?

**Comment by nazar-pc** [comment]
PHP 5.4 is not supported officially and I do not support it as well for quite a long time (in fact, my framework is 5.6+ right now).
So, my suggestion will be: migrate to modern version of PHP as quickly as possible (preferable to 5.6 or 7.0).
