### ISSUE TITLE
Travis CI API broken?

### ISSUE THREAD

**Issue by graemerocher** [travis-ci/travis-ci#5148]
We had previously used this Gradle plugin:

https://github.com/adrianbk/gradle-travisci-trigger-plugin

To trigger a downstream functional test Travis build. However something has changed and now the Travis API is returning forbidden. You can see this here:

https://travis-ci.org/grails/grails-core/builds/92489062#L2532

Has something changed with regards to the API or have tokens been revoked?

**Comment by BanzaiMan** [comment]
Sorry for the delay. I am not sure what might have been going on around Thanksgiving last year.

Is this still an issue? If so, could you point to a more recent build log URL that shows the problem?

Thanks.

**Comment by BanzaiMan** [comment]
Closing in the mean time.
