### ISSUE TITLE
Coverity scan API currently broken.

### ISSUE THREAD

**Issue by avuton** [travis-ci/travis-ci#5149]
Hello! Let me begin by saying thanks for all the hard work on Travis CI.

It appears the Coverity Scan API has broken. I'm not sure if it will right itself on the Coverity site, or if a 
Travis change will be necessary to fix it.

Two examples of broken builds from my ```coverity_scan``` branch are <A HREF="https://travis-ci.org/avuton/dmix/builds/92123020">#526</A> and <A HREF="https://travis-ci.org/avuton/dmix/builds/92575150">#527</A>.

In build #526:
```
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/json/common.rb:148:in `parse': 746: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /api/upload_permitted was not found on this server.</p> </body></html> (JSON::ParserError)
```
makes it appear that this is a remote issue.

The last coverity_scan successful build for me was <A HREF=https://travis-ci.org/avuton/dmix/builds/89121410>#514</A>.

**Comment by BanzaiMan** [comment]
The error is coming from https://scan.coverity.com/api/upload_permitted. Not sure why 404 is returned; we'll have to ask Coverity.

**Comment by avuton** [comment]
As I suspected, the problem was fixed on the remote side, eventually. Thanks!
