### ISSUE TITLE
Avira detects TR/Dropper.gen

### ISSUE THREAD

**Issue by nripendra** [travis-ci/travis-ci#5151]
The electron application using wine in travis-ci is detected as TR/Dropper.gen by avira. It doesn't happen when building using same script on my machine.

![tr-droppergen](https://cloud.githubusercontent.com/assets/1594619/11330372/8db34ea2-91d2-11e5-9bb5-56f49eb4eec3.png)

**Comment by nripendra** [comment]
Looks like a false positive.. but not sure why this happens when building using travis-ci + wine only and not on my local machine..
https://www.virustotal.com/en/file/c265b5fb3ebd7c0b6998faca78526223607d460c06f66236e1505d7d4eea0a63/analysis/1448256395/

**Comment by BanzaiMan** [comment]
I'm sorry to say, but I don't think we have much expertise on Wine. You can try our Docker image to see if you can track this down further; e.g., https://quay.io/repository/travisci/travis-ruby (for Ruby).

**Comment by BanzaiMan** [comment]
Did you get much further in your investigation? There isn't much evidence as to what we need to do here.

**Comment by nripendra** [comment]
No, couldn't get any further. I posted false alarm report to avira, and they have accepted. The latest update in Avira hasn't fixed it yet.

I'll close the issue, as it seems like there is very little we can do about it.
