### ISSUE TITLE
wget SSL failure to CloudFront / Comodo RSA certificate sites

### ISSUE THREAD

**Issue by cardoe** [travis-ci/travis-ci#5156]
Connecting to https://static.rust-lang.org fails with the following error in a new-style container based build:
```
OpenSSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Unable to establish SSL connection.
```

You can see the certificate appears valid according to SSL Labs.

https://www.ssllabs.com/ssltest/analyze.html?d=static.rust-lang.org
https://www.ssllabs.com/ssltest/analyze.html?d=static.rust%2dlang.org&s=54.230.35.204&latest

An example of the failure is visible here: https://travis-ci.org/starlab-io/meta-rust/builds/92396595

**Comment by BanzaiMan** [comment]
Thanks for opening this issue. I think this is a variation of #5059, which I believe is beyond our control. (Namely, `wget` on Precise is too old; https://github.com/travis-ci/travis-ci/issues/5059#issuecomment-153992790.)

Does `curl` work for you?

**Comment by cardoe** [comment]
Unfortunately Yocto does not support using curl as the fetch command (according to the people in #yocto) so I'll have to come up with another work around.

**Comment by BanzaiMan** [comment]
@cardoe Try Trusty. It might have a version that works.

In the meantime, I'm going to close this as a duplicate.
