### ISSUE TITLE
Merging ENV variables from .travis.yml and manually set ones

### ISSUE THREAD

**Issue by janko-m** [travis-ci/travis-ci#5159]
I have some public ENV variables set in .travis.yml, and some private ones set using Travis UI directly. Without the .travis.yml the manually set ENV variables are properly loaded, but when I add .travis.yml, only ENV variables from .travis.yml are set.

It would be nice if those two sources of ENV variables are merged together.

**Comment by janko-m** [comment]
This issue happens only when the build is run for PRs, not for pushes.

**Comment by BanzaiMan** [comment]
We do not pull in secure environment variables on PRs for security reasons (https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests). I believe this is expected behavior.

**Comment by janko-m** [comment]
I understand, I agree that this is the correct behaviour, thanks!
