### ISSUE TITLE
Possibility to only build the latest version of a branch. 

### ISSUE THREAD

**Issue by PommeVerte** [travis-ci/travis-ci#5160]
Hey guys,

I was wondering if it were possible to tell travis to only build the latest version of a branch. If I make 5 merges within 5mn I'm not interested in having each and every one of those merges tested by the CI, same with pushes to branches. Only the latest one is relevant and if an error occurs I can take it locally and revert/test there to fix things.
This gets really painful if you're constantly dealing with 1h builds and can quickly clog up your history with pending builds.

If it isn't possible could this become an option? 
It doesn't necessarily need to close running builds but if any builds are **pending** for the **same** branch then it would discard all but the latest one.

Cheers.

**Comment by tkelman** [comment]
I have a little script that accomplishes this (AppVeyor calls this "rolling builds") by failing a build right away if there are any newer builds pending for the same PR or branch: https://github.com/JuliaLang/julia/blob/master/contrib/travis_fastfail.sh

**Comment by kbrock** [comment]
depending upon your needs, you may want to fast fail and return a true or a false.
I really like this idea too and notice a number of requests for this functionality.

**Comment by jakirkham** [comment]
Definitely could use this at conda-forge. 😉

cc @pelson

**Comment by ntwb** [comment]
Just to add from the #6782 issue I opened and now closed:

AppVeyor include a feature called "Rolling Builds":
> https://www.appveyor.com/docs/build-configuration/#rolling-builds
> “Rolling builds” are great for very active OSS projects with lengthy queue. Whenever you do a new commit to the same branch OR pull request all current queued/running builds for that branch or PR are cancelled and the new one is queued. Other words, rolling builds make sure that only the most recent commit is built.
>
> For example, you do commit A to master branch - it’s being queued and then run. Then you do B commit to master branch while A is running - build of A will be cancelled immediately and B is queued. If you do another C commit while B is queued it will be cancelled and C queued.

It would be great if Travis CI also offered something similar and easily configurable in `.travis.yml`

----

And to add the context of our use case, adding @johnbillions comment also:
> For background, [the WordPress project](https://travis-ci.org/aaronjorbin/develop.wordpress/builds) experiences backlogs of builds during periods of frequent pushes (via commits to its svn repo), and a rolling build would be ideal to mitigate this.

**Comment by ntwb** [comment]
> depending upon your needs, you may want to fast fail and return a true instead of a false.

Unfortunately due to #1696 / #4928 WordPress [had to remove](https://core.trac.wordpress.org/changeset/35150) `fast_finish: true`

**Comment by jakirkham** [comment]
Also this issue ( https://github.com/travis-ci/travis-ci/issues/964 ) first asked for this feature, but it got closed off. Still the fact that there are multiple requests for this feature should signal that this needs to be on the roadmap.

**Comment by HaraldNordgren** [comment]
I would love a `build_only_latest: true` option when debugging.

**Comment by megies** [comment]
:+1: for rolling build support

**Comment by Daenyth** [comment]
This would really help my OSS project

**Comment by joshk** [comment]
I am going to close this issue a little rematurely as we have https://github.com/travis-ci/beta-features/issues/8 landing this coming week.

Essentially, we will auto cancel builds which haven't started if a new Build request comes in.

**Comment by Daenyth** [comment]
What about ones that have started but haven't finished? Will it cancel at
the matrix level or only if nothing has started?

**Comment by joshk** [comment]
@Daenyth if you check out the link to the beta-features issue you will see that it will not cover that use case initially but we will be adding it soon.

**Comment by joshk** [comment]
Hi All

We are really excited to announce that Build Auto Cancellation has just been released into public beta!

You can check out the blog post here: https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

**Comment by jakirkham** [comment]
Neat! Thanks for the update. Is there/will there be an API for setting this per repo?

**Comment by megies** [comment]
@jakirkham see https://github.com/travis-ci/beta-features/issues/8#issuecomment-288489800

**Comment by jeroenst** [comment]
I would like to have a feature to cancel the current building process if a new push is detected. 

Now when I'm doing multiple pushes in a short time I get multiple building processes in Travis, which is unneeded and only wasting processor time.

**Comment by BanzaiMan** [comment]
@jeroenst https://docs.travis-ci.com/user/web-ui/#auto-cancel-branch-builds
