### ISSUE TITLE
Use JRE 8 on non-java project

### ISSUE THREAD

**Issue by eapache** [travis-ci/travis-ci#5161]
We have a golang project whose test suite relies on running a java server process. This has historically been quite simple; we download and run the java process locally in our `before_install` and everything works fine.

However, the latest version of this java server requires JRE8 which (as far as I can tell) is not installed by default on the images. Since this is a `language: go` project not a `language: java` one, all of the various "use java 8" stanzas I have tried seem to be ignored.

How do I tell travis to use JRE 8 to run our server, on a project which is still actually a go language project?

**Comment by BanzaiMan** [comment]
On non-JVM images, you would have to manage `$PATH` yourself. Basically, https://github.com/travis-ci/travis-cookbooks/blob/master/cookbooks/travis_java/templates/ubuntu/jdk_switcher.sh.erb

```shell
if [[ -d "/usr/lib/jvm/java-8-oracle-$ARCH_SUFFIX" ]] ; then
    # Currently unused, because the `travis_java` cookbook doesn't create this architecture specific symbolic link
    ORACLEJDK8_UJA_ALIAS="java-8-oracle-$ARCH_SUFFIX"
    ORACLEJDK8_JAVA_HOME="/usr/lib/jvm/java-8-oracle-$ARCH_SUFFIX"
else
    ORACLEJDK8_UJA_ALIAS="java-8-oracle"
    ORACLEJDK8_JAVA_HOME="/usr/lib/jvm/java-8-oracle"
fi
⋮
switch_to_oraclejdk8 () {
    echo "Switching to Oracle JDK8 ($ORACLEJDK8_UJA_ALIAS), JAVA_HOME will be set to $ORACLEJDK8_JAVA_HOME"
    sudo $UJA --set "$ORACLEJDK8_UJA_ALIAS"
    export JAVA_HOME="$ORACLEJDK8_JAVA_HOME"
}
```

(Obviously, you may not use `sudo` on containers.)

**Comment by mmkal** [comment]
@eapache given that it's been nearly a year, I image you've figured this out by now. But for anyone reading this from the future, adding this to `.travis.yml` worked for me:
```yml
before_install: 
  - sudo apt-get install oracle-java8-set-default
```

**Comment by sideshowbarker** [comment]
For travis builds where you don’t enable `sudo`, this refinement of https://github.com/travis-ci/travis-ci/issues/5161#issuecomment-257046000 works:
```yaml
addons:
  apt:
    packages:
      - oracle-java8-set-default
```

**Comment by rainerhahnekamp** [comment]
In my case I also had to set JAVA_HOME since some of my build tools depend on it. So the answer from @BanzaiMan is the complete one.
