### ISSUE TITLE
APT whitelist request (?) "Disallowed packages gcov-4.9, libqt5opengl-dev in container-based infrastructure"

### ISSUE THREAD

**Issue by davidok8** [travis-ci/travis-ci#5162]
Hi Travis team,

I am trying to move my build to the container-based infrastructure. Builds are failing: 
https://travis-ci.org/DO-CV/sara/builds/92853653

Contrary to the legacy infrastructure, `<QGLWidget>` header files are not found in the container-based infrastructure. `libqt5opengl` and `libqt5opengl` package provide what I need but they are disallowed apparently.

`gcov-4.9` is also disallowed and I think I will need it to send code coverage to coveralls.

Is it possible to allow these packages to be installed?

**Comment by BanzaiMan** [comment]
Thanks for opening the issue, but please read https://travis-ci.org/DO-CV/sara/builds/92853653#L102

> If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
