### ISSUE TITLE
Rackspace deploy error on OS: 'mime-types' missing

### ISSUE THREAD

**Issue by matthew-brett** [travis-ci/travis-ci#5165]
On a deploy that has previously worked, the following error:

```
Deploying application
[fog][WARNING] 'mime-types' missing, please install and try again.
```

https://travis-ci.org/MacPython/astropy-wheels/jobs/93023883#L3168

**Comment by BanzaiMan** [comment]
Also https://github.com/travis-ci/travis-ci/issues/5165

**Comment by BanzaiMan** [comment]
Could you test https://github.com/travis-ci/dpl/commit/59d12251970d9ab370a1b6a88c700ae54e2db583 with:

```yaml
deploy:
  provider: cloudfiles
  edge: true
  ⋮
```

**Comment by matthew-brett** [comment]
Thanks - yes - that worked e.g. https://travis-ci.org/MacPython/astropy-wheels/jobs/93205769

I know this will sound funny, but is there any continuous integration testing for the OSX deploy stuff?

**Comment by BanzaiMan** [comment]
@matthew-brett Good to hear. I'll release 1.8.11 shortly.

We do have CI on `dpl`, but runtime dependencies can be hard to pin down.

**Comment by BanzaiMan** [comment]
dpl 1.8.11 is out.

**Comment by matthew-brett** [comment]
Thanks for that.

I guess you mean, that you run the tests on commits, but not - say - nightly - so that, when other packagers update their packages, they may break the instal?

Would it be possible to run nightly tests to find this kind of thing?   Or run from a known state?

**Comment by rgbkrk** [comment]
Thank you!
