### ISSUE TITLE
Can we add some more information in email build notifications?

### ISSUE THREAD

**Issue by sanketd11** [travis-ci/travis-ci#5167]
In my scenario, I am running casperJS automated test scripts on we application. CasperJS generates test reports in xml format. I am parsing that xml file and generatin summary. I just want my summary table to be displayed in build notification email. How can I do that.

**Comment by BanzaiMan** [comment]
This is an extension of #239. We have JUnit output support on the roadmap, but no ETA.

I'm inclined to close this as well for the time being.
