### ISSUE TITLE
Update Maven on OSX to a recent version (or at least 3.2.5)

### ISSUE THREAD

**Issue by mprins** [travis-ci/travis-ci#5170]
Currently OSX images are running 3.2.3, but a (final) 3.2.5 was released almost a year ago, any chance you could update to a more recent version than 3.2.3?

**Comment by BanzaiMan** [comment]
I believe maven is the version pre-installed on OS X. For now, I recommend using Homebrew to update it.

**Comment by mprins** [comment]
thanx, I managed this using the following snippet:

```yml
before_install:
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
         brew update --quiet;
         brew upgrade maven;
     fi
   - ...
```
