### ISSUE TITLE
Emails are broken since last week

### ISSUE THREAD

**Issue by tristanbes** [travis-ci/travis-ci#5171]
Emails notification when a build is broken are broken too, html without style or so.

I'm on Travis Pro

**Comment by MariadeAnton** [comment]
Hey @tristanbes. We've managed to reproduce this issue and linked it to the internal issue to get it fixed (see above)

Thanks a lot for reporting :100: !

**Comment by joshk** [comment]
I have just deployed a fix to travis-ci.org and travis-ci.com. Can you please let us know if the issue is fixed for you or if you are continuing to see layout issues.

Thank you for reporting this.

**Comment by BanzaiMan** [comment]
This has been fixed.
