### ISSUE TITLE
PRs are not tested anymore when using the branch whilelist

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#5172]
Previously, when using the branch whitelist, PRs targetting one of the whitelisted branch were triggering a build (but the push build was skipped).
It looks like both builds are now skipped. This makes the whitelist much less useful (as PRs sent from a feature branch in the repo to the master branch are not tested anymore).

See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1231

**Comment by stof** [comment]
Note that things are working fine on .com currently

**Comment by BanzaiMan** [comment]
Take a look at https://travis-ci.org/FriendsOfSymfony/FOSRestBundle/requests. It shows that commit https://github.com/FriendsOfSymfony/FOSRestBundle/commit/cf69701 triggered a build but https://github.com/FriendsOfSymfony/FOSRestBundle/commit/8cb50ec did not. This probably means that the latter contains some YAML syntax error, and we were not able to configure a build.

**Comment by stof** [comment]
Indeed, there is a syntax error. It would be great to report some feedback in such case (you could mark the commit status as errored, with a message saying the config file is invalid). Otherwise, it is hard to understand what happens.

**Comment by BanzaiMan** [comment]
Right. That's basically what #2025 addresses. I'm closing this now.
