### ISSUE TITLE
Add language: none

### ISSUE THREAD

**Issue by linquize** [travis-ci/travis-ci#5175]
I have projects that use only shell script and other unix utilities only.
I need a build environment that only need bash and other unix utilities. I do not need gcc.
However, if I do not specify language in `.travis.yml`, Travis gives me ruby, which wasted VM starting time.

I suggest to add `language: none`

**Comment by BanzaiMan** [comment]
Please use `language: generic` for this purpose.

**Comment by linquize** [comment]
IC

**Comment by joshk** [comment]
@BanzaiMan do you think it is worth also supporting `none`? it feels like `none` makes more sense than `generic`.

**Comment by BanzaiMan** [comment]
We support `language: bash` now, and I think that is a much better display of intent than `none`.

Let us close this.

**Comment by markasoftware** [comment]
@BanzaiMan why is Bash not listed [here](https://docs.travis-ci.com/user/languages/)?

**Comment by abitrolly** [comment]
> @BanzaiMan why is Bash not listed here?

@markasoftware looks like it is autogenerated from the list of files here - https://github.com/travis-ci/docs-travis-ci-com/tree/master/user/languages so the way to make this happen (and score at https://hacktoberfest.digitalocean.com/) is to add a page there. I still doubt what page content should be.
