### ISSUE TITLE
Logos on site have incorrect links

### ISSUE THREAD

**Issue by Legoless** [travis-ci/travis-ci#5179]
Logos on site: https://travis-ci.com/logo are broken and are linked to Blue logo, instead of being linked to the correct color:

https://cdn.travis-ci.com/images/logos/mascot-bg-blue-74537338f8ec8ea2c0722b4d60f9777f.png

**Comment by clekstro** [comment]
@Legoless it looks like this issue has since been fixed. I double-checked all the logos, and did notice [one issue](https://github.com/travis-ci/travis-ci/issues/5626), but not the one you're describing. Could this be closed?

**Comment by Legoless** [comment]
Yep, seems all right.
