### ISSUE TITLE
Can't login to travis-ci.org

### ISSUE THREAD

**Issue by henders** [travis-ci/travis-ci#5180]
When loading up the https://travis-ci.org/ page, I see the following in the console:
![screen shot 2015-11-30 at 2 49 10 p m](https://cloud.githubusercontent.com/assets/515143/11474744/ca78aa9a-9771-11e5-8df2-57357f669f5a.png)

Then when clicking on the 'Sign-in with Github' button, I see a 403 pop up in the network pane:
 
![screen shot 2015-11-30 at 2 49 48 p m](https://cloud.githubusercontent.com/assets/515143/11474790/e5a40b02-9771-11e5-8cc4-851d7e28cb32.png)

The button changes to a 'signing in....' state but stays there.

I can login fine to the private section of travis: https://travis-ci.com/

**Comment by henders** [comment]
I can reproduce in Safari which has no plugins or extensions installed.

**Comment by joshk** [comment]
Hi @henders 

Do you experience then same issues with Firefox or Chrome?

**Comment by henders** [comment]
The traces above were from Chrome.  I've replicated it both in Firefox and Safari as well.

**Comment by drogus** [comment]
@henders could you try revoking access to "Travis CI" on [GitHub's applications list](https://github.com/settings/applications)?

It looks like we can't authenticate against GitHub and API returns 403 for all of the requests as a result.

**Comment by henders** [comment]
Sure, I'll give that a go.

**Comment by henders** [comment]
@drogus , that did not help, I revoked access, but symptoms are unchanged. I cleared cache from Safari to no avail either.

**Comment by henders** [comment]
Just to clarify, when I revoked access and clicked the 'Sign-in with Github' button, it did not bring me to the github authentication approval page, but just went to the same spinning 'signing in...' state.

**Comment by joshk** [comment]
@henders just to confirm, have you tried flushing all cookies? and using private mode?

**Comment by henders** [comment]
@joshk , yup, in Chrome I went into incognito mode and saw the same thing. I flushed history in both Firefox and Safari as well with the same affect.

**Comment by rkh** [comment]
There's something going on here. If I run an automatic check against your account, our system tells me that the scopes on your github token have changed from what they were when you signed up. Investigating.

**Comment by rkh** [comment]
Uhm, just ran the test again and now it came back as all good. Something is up.

**Comment by henders** [comment]
@rkh , I just rebooted my machine for extra effect, and when it came back up, that page started working. Did  you do anything on the backend?

**Comment by henders** [comment]
Anyway, I'll close this issue. Thanks folks for the fast response in helping me!

**Comment by rkh** [comment]
Triggered another sync for your account, triggered a login handshake with the GitHub token we have on file. I think we may have had the wrong scopes in our DB for some reason (we track them so we know to log out ppl if we have to change scopes). Not sure how that happened, though.

**Comment by henders** [comment]
Ah, thanks for the explanation @rkh!

**Comment by springmeyer** [comment]
I'm also hitting this. Also had a nearby coworker replicate by logging out of travis-ci.org and then logging back in did not work. However, just tried again right before saving and now it works again (to login). So, something pretty odd and variable is happening here that might not be completely solved.

**Comment by springmeyer** [comment]
Perhaps related: I'm also seeing the requests to display the logs failing like:

![screen shot 2015-12-02 at 12 31 41 pm](https://cloud.githubusercontent.com/assets/20300/11538598/b51a43fe-98f0-11e5-8a89-01a86646f553.png)

The `...` just stays put and the logs never appear:

![screen shot 2015-12-02 at 12 32 22 pm](https://cloud.githubusercontent.com/assets/20300/11538646/e3ad5aa8-98f0-11e5-862a-60cd2307c7a4.png)

**Comment by joshk** [comment]
This is a different error, can you please open a new issue and we can investigate first thing tomorrow.

**Comment by henders** [comment]
Hi, unfortunately I just ran into this again:
![screen shot 2016-01-04 at 16 07 44](https://cloud.githubusercontent.com/assets/515143/12093886/65b1a268-b2fd-11e5-9761-5cb6f92b93f9.png)

**Comment by henders** [comment]
@rkh fixed this last time by resyncing my account. Can this be done to see if it fixes it again?

**Comment by henders** [comment]
I can get into travis-ci.com but not travis-ci.org, same as last time.

**Comment by henders** [comment]
Ah, seems to have resolved itself!

**Comment by J3RN** [comment]
I am also getting a 403 when I try to sign in, and the "Signing In..." animation goes on indefinitely.
<img width="1440" alt="screen shot 2016-07-05 at 12 45 00" src="https://cloud.githubusercontent.com/assets/2058614/16592386/6c824444-42ae-11e6-9630-c0b87456455a.png">

OS X 10.11.5, Chrome and Firefox, also occurs in Incognito mode for both

**Comment by dansondergaard** [comment]
I have this exact problem (403 Forbidden). I revoked the privileges for Travis on GitHub and tried to sign in again (in private mode), but the button is just "spinning", nothing happens. It's been like this for several hours. One of my coworkers have the same problem (we tested Chrome, Safari and Firefox).

**Comment by YohanObadia** [comment]
Same problem here, I get stuck at the github hanshake
![image](https://user-images.githubusercontent.com/14013774/80309343-b48a4b00-87d4-11ea-86ea-5f514a15de4a.png)

**Comment by akimd** [comment]
Likewise.  I can't log on travis-ci.com ("Can't login"), but I can log on travis-ci.org though.  Both via GitHub.

**Comment by akimd** [comment]
... and after a few more attempts, it worked...

**Comment by Inffinite** [comment]
Almost a year later and i am facing the same issue
