### ISSUE TITLE
[travis-web] bug: Cmd+Click is broken on left-hand side repositories listing

### ISSUE THREAD

**Issue by jasonkarns** [travis-ci/travis-ci#5181]
Given: Cmd+Click on repository link or build number from left-hand side repository listing

Expected: Current tab remains unchanged, open clicked repo or build in a new tab.

Actual: Current tab loads the clicked repo/build AND clicked repo/build opens in new tab.

**Comment by clekstro** [comment]
@jasonkarns I wasn't able to reproduce. Are you still experiencing this or can this be closed?

**Comment by jasonkarns** [comment]
still occurring. chrome on osx

**Comment by clekstro** [comment]
@jasonkarns Thanks, I had another look and was able to see what you mean. It looks like there are a few things here that are unexpected. I've opened a [PR](https://github.com/travis-ci/travis-web/pull/458) to address this.

**Comment by jasonkarns** [comment]
thanks!

**Comment by clekstro** [comment]
@jasonkarns Have a look now. That PR is now live and should resolve this issue.

**Comment by jasonkarns** [comment]
woot!
