### ISSUE TITLE
MySQL not available?

### ISSUE THREAD

**Issue by sorenh** [travis-ci/travis-ci#5183]
MySQL access does not seem to work for me all of a sudden?

https://travis-ci.org/aaSemble/python-aasemble.django/jobs/94111561#L125

See line 125 and 412.

**Comment by sorenh** [comment]
Very strange. Another build: https://travis-ci.org/aaSemble/python-aasemble.django/jobs/94113125

Line 56 seems to suggest that mysql is installed, but "dpkg -l" doesn't show it and /etc/init.d does not have the init script.

**Comment by BanzaiMan** [comment]
Hello. Your builds in question are running on Trusty, which does not have MySQL server installed. (But it has the client—https://travis-ci.org/aaSemble/python-aasemble.django/jobs/94113125#L973.) See https://docs.travis-ci.com/user/trusty-ci-environment/#Data-Stores. You can use `sudo` to install and configure it.

**Comment by sorenh** [comment]
Well, that's fair enough, but why did my build all of a sudden switch to using Trusty?

**Comment by BanzaiMan** [comment]
I did not. You have `services: docker`, which routes the builds to Trusty.

**Comment by sorenh** [comment]
Oh, ok. Thanks.
