### ISSUE TITLE
Parenthesis around build command gives confusing error message

### ISSUE THREAD

**Issue by ericmj** [travis-ci/travis-ci#5188]
Build: https://travis-ci.org/hexpm/hex/builds/94224112

```
Using worker: worker-linux-5590757e-1.bb.travis-ci.org:travis-linux-15
Could not fetch .travis.yml from GitHub.
/home/travis/build.sh: line 2: travis_terminate: command not found
Done. Your build exited with .
/home/travis/build.sh: line 5: travis_terminate: command not found
```

The problem seems to be the parenthesis on line 5 below:

```
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - git clone https://github.com/hexpm/hex_web.git
  - (cd hex_web && mix deps.get && MIX_ENV=hex mix compile)
  - mix deps.get
  - MIX_ENV=test mix deps.compile
```

Maybe the error message can be improved to indicate a syntax error or even allow the syntax?

**Comment by BanzaiMan** [comment]
The error is `Could not fetch .travis.yml from GitHub.` I am fairly certain that it was a network issue. Please retry.

**Comment by ericmj** [comment]
I tried switching back and forth 2 times, it worked when I removed the parenthesis, it didn't work when they were there. I can try again.

**Comment by BanzaiMan** [comment]
Is this still a problem?

**Comment by ericmj** [comment]
No, it was probably a network issue like you said. I was just unlucky it only showed when I changed the travis file.
