### ISSUE TITLE
Build system information fold only shows one Ruby version

### ISSUE THREAD

**Issue by waits** [travis-ci/travis-ci#5190]
There is a discrepancy between the docs, the build log, and the Ruby versions that are actually installed on your machines.

* In the build log, "Pre-installed ruby versions" under "Build system information" shows only ruby-1.9.3-p551
* The [docs](https://docs.travis-ci.com/user/languages/ruby/#Supported-Ruby-Versions-and-RVM) claim recent versions of 2.2.x are installed
* Based on trial-and-error, 2.2.0 is really installed on your machines, but 2.2.1, 2.2.2, and 2.2.3 are not (they give a "ruby-2.2.x is not installed" message)

Here's a private build showing the [incorrect system information](https://travis-ci.com/janowski/wedding-expo/builds/18387042#L28) and the [ruby-2.2.1 is not installed](https://travis-ci.com/janowski/wedding-expo/builds/18387042#L98) message. Here's a [free repo](https://travis-ci.org/waits/ntwrk#L28) with the incorrect system information.

**Comment by samrussell-ps** [comment]
I have since rolled back my apps to 2.2.0 in order to use the locally installed version too.

**Comment by waits** [comment]
I ran `ls -l /home/travis/.rvm/gems` in before_script to get the real list:

```
1.8.7
1.9.2  1.9.3
2.0.0
2.1.2  2.1.3  2.1.4  2.1.5
2.2.0
```

https://travis-ci.org/waits/ruby-version-test#L104

**Comment by waits** [comment]
This seems to have been fixed in the new Trusty/GCE environment.

**Comment by BanzaiMan** [comment]
Confirmed.
