### ISSUE TITLE
[precise-gce] apt-get update required

### ISSUE THREAD

**Issue by adamchainz** [travis-ci/travis-ci#5194]
I have a build that installs some packages from apt at the start of the build. They failed to install on my first GCE builds - apt complained that they didn't exist, but adding a `sudo apt-get update` to the script made them pass.

Failed build: https://travis-ci.org/adamchainz/django-mysql/jobs/94509828
Passed build: https://travis-ci.org/adamchainz/django-mysql/builds/94511684 (one red cross there is due to app code not the build environment).

**Comment by BanzaiMan** [comment]
Thanks for taking the time to open this issue.

As described in https://docs.travis-ci.com/user/installing-dependencies#Installing-Ubuntu-packages, there is always a chance that the package indices on our image is out of date, and it is a good idea to run `sudo apt-get update` before installing new packages.

**Comment by adamchainz** [comment]
Okay thanks. It was just weird that it had always worked on the old environment - it's a not a new package and I'm not asking for a specific version.
