### ISSUE TITLE
Composer can't resolve PHP version on PHP 5.3.29

### ISSUE THREAD

**Issue by clphillips** [travis-ci/travis-ci#5195]
On any PHP 5.3.29 install, after running `composer install` composer reports that it can't resolve the version of PHP on the machine. Is this because the default composer on the php 5.3.29 machines is outdated? Is the recommendation to run `composer update` during the build? Would that resolve the issue?

composer.json
```
{
  "require": {
    "php": ">=5.3"
  }
}
```
output:
```
The requested package php could not be found in any version, there may be a typo in the package name.
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL to show this problem?

**Comment by clphillips** [comment]
Sure do: https://travis-ci.org/phillipsdata/minphp-acl/jobs/94058251

**Comment by BanzaiMan** [comment]
You have 

    "require-dev": {
        "php": ">=5.4.0",
        ⋮
    }

in your `composer.json`. So the resolution fails. Composer's error message is misleading, but that's beyond our reach. If you change the requirement in `require-dev`, it should work.

**Comment by clphillips** [comment]
Ah, you're right. Thanks for pointing it out.
