### ISSUE TITLE
Unable to locate packages on new platform for Legacy Precise builds.

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#5196]
There is only short time difference between my two builds: [94527760](https://travis-ci.org/EA31337/FX-MT-VM/builds/94527760) ([raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/94527761/log.txt)) and [94534595](https://travis-ci.org/EA31337/FX-MT-VM/builds/94534595) ([raw log](https://api.travis-ci.org/jobs/94534596/log.txt?deansi=true)).

It seems the worker, release and platform changed and it's now showing the error:

> E: Unable to locate package language-pack-en

My provisioning file is having:

    apt-get install -qy language-pack-en

and it was working before.

Do I need to change anything? Or it's temporary glitch?

**Comment by BanzaiMan** [comment]
Does the problem persists if you run `sudo apt-get update` prior to `apt-get install`?

**Comment by kenorb** [comment]
Seems to [worked](https://travis-ci.org/EA31337/FX-MT-VM/builds/94541674) after `apt-get update`, I think in the previous version of build it was doing that automatically.

So I guess nothing to fix in here.
