### ISSUE TITLE
how can i mkdir without sudo

### ISSUE THREAD

**Issue by NetWilliam** [travis-ci/travis-ci#5197]
I want to use container to speed up the test, so i don't want `sudo` command
but here's the thing: i need sub-directories in /var/log/xxx, however /var/log/xxx even not exists!!
i don't have permission to write in /var/log, how i can do that?

**Comment by BanzaiMan** [comment]
You can't do that without `sudo`. `/var/log` belongs to `root` (or its subdirectories to their respective owner, such as `mysql` and `elasticsearch`). If you have software that wants to write to that directory, you'd need to figure out a way to change the configuration to write elsewhere.
