### ISSUE TITLE
Commit hash not verified during PR builds

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#5198]
When checking out a PR, Travis CI claims to be on a certain commit SHA, but may not in fact be on that SHA and it makes no effort verify on that SHA. It should check to see if the SHA matches the one it expects to build. Ideally, if it doesn't, it should checkout the matching SHA, merge it with the default branch (e.g. master), and test it. If it can't checkout the SHA, it should error immediately instead of building the wrong one.

**Comment by BanzaiMan** [comment]
Could you indicate which build is showing the behavior you describe? Thanks.

**Comment by jakirkham** [comment]
Take a look at this PR for an example ( https://github.com/nanshe-org/nanshe/pull/304 ). The first and final commits should pass and the middle two should fail. These are correctly indicated because another CI service is used that is merging the right commits in. On Travis it grabs the last commit and merges it into master every time because the commits all got pushed before any of the Travis builds started.

**Comment by jakirkham** [comment]
Here is an example ( https://travis-ci.org/numpy/numpy/builds/100116425 ). This should fail as this commit ( https://github.com/numpy/numpy/commit/407a1ffb41751e2d87b9894b26a342cedae45c01 ) refers to `A`, which is undefined. However, it is passing because it is pulling the latest commit from the PR.

**Comment by BanzaiMan** [comment]
Are these tests run?

The sequence of commands run is this:
```sh-session
$ git clone --depth=50 https://github.com/numpy/numpy.git numpy/numpy
$ cd numpy/numpy
$ git fetch origin +refs/pull/6930/merge:
$ git checkout -qf FETCH_HEAD
```

If you run these commands, you would end up with the merge commit that we test. You could double check that with `git log -1`.

I must admit that I am a bit confused. A previous build for this PR https://travis-ci.org/numpy/numpy/builds/100114148 ran with this commit https://github.com/numpy/numpy/commit/bbd34c82d23df78a3218cd9d9c8af77dc8442113 but it failed https://travis-ci.org/numpy/numpy/jobs/100114149#L307 with undefined global name `A`, but I don't see any reference in that merge commit.

**Comment by jakirkham** [comment]
Yes, they are run. I have been using them to reliably debug an implementation I am working on for numpy.

> `git checkout -qf FETCH_HEAD`

That is the issue. The HEAD has now changed. Is there some way of fetching this ASAP and caching it before beginning the actual builds.

> ...but I don't see any reference in that merge commit.

Here is such a line followed by a few others below (wasn't able to select multiple lines) in the merge commit with this undefined `A`. ( https://github.com/numpy/numpy/commit/407a1ffb41751e2d87b9894b26a342cedae45c01#diff-bc1e8d40b8b7758facc5e143be016f99R1996 )

**Comment by jakirkham** [comment]
Sorry, I was hoping to provide a cleaner example, but didn't end up having time to do so. Hence the delay on giving you one.

**Comment by jakirkham** [comment]
I think this may have been fixed. In particular, it seems like Travis CI caches may be caching the repo and fetched heads. Was able to restart an old PR and test the right merge commit despite it no longer being retrievable. Going to go ahead and close as it seems like this may be resolved.
