### ISSUE TITLE
Julia executable fails to download

### ISSUE THREAD

**Issue by micahjsmith** [travis-ci/travis-ci#5199]
Travis tests for a package [are failing](https://travis-ci.org/micahjsmith/BlsData.jl/jobs/93801160#L94) because the Julia executable itself is failing to download:
```
Installing Julia
$ mkdir -p ~/julia
$ curl -s -L --retry 7 'https://status.julialang.org/stable/linux-x86_64' | tar -C ~/julia -x -z --strip-components=1 -f -

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

The command "curl -s -L --retry 7 'https://status.julialang.org/stable/linux-x86_64' | tar -C ~/julia -x -z --strip-components=1 -f -" failed and exited with 2 during .

Your build has been stopped.
```

Not sure what could be going on here. Julia version in `.travis.yml` is set to `release`.

cc @tkelman @ninjin @staticfloat

**Comment by tkelman** [comment]
restart that, there was a dns migration issue last weekend. also https://github.com/travis-ci/travis-build/pull/557 changed the download location.

**Comment by micahjsmith** [comment]
Got it, that was. Thanks!
