### ISSUE TITLE
Assimilation build fails on GCE

### ISSUE THREAD

**Issue by Alan-R** [travis-ci/travis-ci#5200]
Some of our tests perform loopback testing using ::1. It looks like this fails. We don't need routable ipv6 addresses, but _everything_ we do is ipv6.  It doesn't even make sense to write software that uses ipv4 native addresses any more - and hasn't for a few years. So, when we started this software back in 2010, we simply didn't (even then) see any need to support native ipv4 addresses.

We translate all ipv4 addresses to ipv6 - _everywhere_. We don't need "real" ipv6 addresses, but we do need ::1, and we need for the kernel to have the ipv6 stack enabled, so that when we mention ::ffff:1.2.3.4 or similar that it will treat it as a legitimate address. Again, we don't need to route anything, but we do need for this to work.

You can see how this has hosed up [this build](https://travis-ci.org/assimilation/assimilation-official/builds/94694137).

**Comment by BanzaiMan** [comment]
Hello. As you read in the [blog post](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future), we are unable to offer IPv6 support, due to the limitations imposed by our service provider. We hope we can get there eventually, but we do not have a feasible timeline for that.

**Comment by Alan-R** [comment]
Yes I did read it. But that was VERY short notice that I need to move to another build system - and of course, I didn't find out until it broke. So, I'll have my CI guy figure out where we should move to :-(.

And we just moved here a few months ago :-(.

In any case, thank you for a few months of free service.

**Comment by solarce** [comment]
@Alan-R we can understand your frustration and apologize that this caught you off guard.

 While we agree that IPv6 is definitely part of the future, unfortunately at this point none of the major cloud providers offer any support for IPv6, even on localhost, it's disabled in the Linux images they provide by default.

The official Ubuntu Precise image that we're building our images from has this in `/etc/systctl.d/99-gce.conf`:
```
# Requirements from Google. Documented at:
#       https://developers.google.com/compute/docs/images#buildingimage

# Disable IPV6 as unsupported
net.ipv6.conf.all.disable_ipv6 = 1
```
One of our customers noted that using one of our Docker build VMs (based on Trusty), you get `inet6` on `lo` inside a Docker container, as shown below:

```
brandon@sol-docker-ipv6:~$ grep ipv6 /etc/sysctl.d/99-gce.conf
net.ipv6.conf.all.disable_ipv6 = 1
brandon@sol-docker-ipv6:~$ ip addr show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
brandon@sol-docker-ipv6:~$ sudo docker run -it --rm ubuntu:precise ip addr show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
```

We're investigating this further to see if it's something we can officially recommend to users, but if you'd like to try getting your builds working in a docker container and see if it works with the loopback device in the container, we'd love to hear the results of your testing.

Please let me know if that's something you'd be interested in.

Thanks

**Comment by Alan-R** [comment]
I do all my personal testing under Docker - and have for quite a while.

What can I do further?

On December 3, 2015 6:47:15 PM MST, Brandon Burton <notifications@github.com> wrote:
>@Alan-R we can understand your frustration and apologize that this
>caught you off guard.
>
>While we agree that IPv6 is definitely part of the future,
>unfortunately at this point none of the major cloud providers offer any
>support for IPv6, even on localhost, it's disabled in the Linux images
>they provide by default.
>
>The official Ubuntu Precise image that we're building our images from
>has this in `/etc/systctl.d/99-gce.conf`:
>```
># Requirements from Google. Documented at:
>#       https://developers.google.com/compute/docs/images#buildingimage
>
># Disable IPV6 as unsupported
>net.ipv6.conf.all.disable_ipv6 = 1
>```
>One of our customers noted that using one of our Docker build VMs
>(based on Trusty), you get `inet6` on `lo` inside a Docker container,
>as shown below:
>
>```
>brandon@sol-docker-ipv6:~$ grep ipv6 /etc/sysctl.d/99-gce.conf
>net.ipv6.conf.all.disable_ipv6 = 1
>brandon@sol-docker-ipv6:~$ ip addr show dev lo
>1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
>group default
>    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>    inet 127.0.0.1/8 scope host lo
>       valid_lft forever preferred_lft forever
>brandon@sol-docker-ipv6:~$ sudo docker run -it --rm ubuntu:precise ip
>addr show dev lo
>1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
>    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>    inet 127.0.0.1/8 scope host lo
>       valid_lft forever preferred_lft forever
>    inet6 ::1/128 scope host
>       valid_lft forever preferred_lft forever
>```
>
>We're investigating this further to see if it's something we can
>officially recommend to users, but if you'd like to try getting your
>builds working in a docker container and see if it works with the
>loopback device in the container, we'd love to hear the results of your
>testing.
>
>Please let me know if that's something you'd be interested in.
>
>Thanks
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/travis-ci/travis-ci/issues/5200#issuecomment-161847828

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rusher** [comment]
And java openJDK 7 has problem if ipv6 is not enabled due to this bug : https://bugs.openjdk.java.net/browse/JDK-8044306.

**Comment by Alan-R** [comment]
OK then. I use the Neo4j database, and it's Java-based. They declare a dependency on Java 7. So, even if I fix my code, it might be the case that Neo4j will crap out when I run tests that rely on it (I have those tests). I'll keep that in mind.

**Comment by Alan-R** [comment]
@borgified - can you look into implementing the workaround described above rellated to this:
$ grep ipv6 /etc/sysctl.d/99-gce.conf
net.ipv6.conf.all.disable_ipv6 = 1

**Comment by Alan-R** [comment]
Looks like the ipv6 setting suggestion fixes it: https://github.com/assimilation/assimilation-official/pull/18#issuecomment-162266132

**Comment by solarce** [comment]
@Alan-R 

Firstly, I've whipped up a quick demo showing that `ping6` does work with `lo` in an Ubuntu Precise container, see https://travis-ci.org/solarce/ipv6-docker-test/builds/95074324 and https://github.com/solarce/ipv6-docker-test/blob/5eec42be3a3bcbbeca0fae2e1dcf471d5ce6609b/.travis.yml

To be able to [use our Docker support](http://docs.travis-ci.com/user/docker/) in your builds, you'd need to redo the testing in your `.travis.yml` such that your build environment, building, and testing all an run inside one or more docker containers.

I'd recommend taking the time to move what you do in `install:` and `before_script:` into a Docker image that you pre-build and publish to the Docker Hub, then you can just Docker pull it for each build and run your code's build and testing.

@rusher as far as I can tell, that particular JDK7 issue you've linked to is related to when the OS has IPv6 configured on the interfaces, but the the IPv6 connectivity is not working properly, which confuses things as the JVM tries to use the broken IPv6 when it should use the working IPv4. **I do not believe this is applicable in our case on GCE as IPv6 is disabled for the build VM OS entirely, via `sysctl` settings.** If you have a reproducible test case showing some Java code and the failure, we'd definitely appreciate seeing it so we can determine an appropriate fix for Linux on GCE.

As far as Travis's overall take on this, we're still discussing how much guidance/support we can offer for the "IPv6 localhost inside docker" scenario at this time.

**Comment by Alan-R** [comment]
So, what you're saying is that we should stop using travis, and start using Docker hub for testing.

There are automatic triggering and authentication issues associated with automatically publishing a Docker hub image that I'll have to solve myself, that I don't have to worry about using Travis. Basically, if I can do that easily, there's no need for Travis...

You folks figure out what you're going to do with regard to the ipv6 localhost issue. If you decide we can't use what we're doing, then please give us a few weeks to find somewhere else to test.

**Comment by solarce** [comment]
@Alan-R I am just catching up on your additional comments on the results of https://github.com/assimilation/assimilation-official/pull/18#issuecomment-162266132.

To clarify, I did not intend to suggest changing the sysctl setting, e.g. `echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6`, I was suggesting that you take advantage of the fact that even when IPv6 is disabled in the host, it still works inside the docker container(s) without needing to change any settings in the host.

We would definitely not be able to provide any official support for using `echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6` inside a build, as Google does not support it. We wouldn't say you *can't* use it, just that we would not be able to provide help in troubleshooting issues related to IPv6 networking in the Linux builds.

Tapping into the fact it does work inside a Docker container is something we're considering making people aware of, but we would not provide support for it as well. 

Unfortunately, if IPv6 support as a supported feature is a requirement for your CI needs at this time, then Travis is not currently able to provide it due to limitations of what our current cloud providers officially support. We appreciate your desire to use Travis but also understand that sometimes there are requirements that our current supported feature set don't meet.

**Comment by Alan-R** [comment]
I understand your desire to get onto a more cost-effective infrastructure, and appreciate also the fact that you provide this for free for open source projects, and very much appreciate that!

No offense, but the suggestion of prebuilding and so on in Docker hub doesn't make much sense. It bypasses almost all the value that Travis provides.

We build under Docker all the time. I build for 10+ versions of Linux on my infrastructure when I get ready for a release.

Can I run Docker as part of a Travis build/test?

**Comment by solarce** [comment]
@Alan-R You're able to use Docker inside a build, with http://docs.travis-ci.com/user/docker/, the build runs in a Trusty VM on GCE and has Docker pre-installed, you're able to do any Docker interactions you might do on a local machine, our usual time outs on output and total build length time do still apply.

So what I was envisioning would be something like

1. Move your `install:` and `before_scripts` steps into a Dockerfile you put in your repository. and then use the Docker Hub to build, publish, and store it for you.
2. Make your `install:` step consistent of a `docker pull ...`
3. Modify your `script:` steps so that you use `docker run ...` inside the container you build above, which contains what you need to build and test your code.

We have a number of users who've moved to a similar workflow now we support build VMs that can run Docker in them.

Please let me know what you think of what I have outlined above.

**Comment by Alan-R** [comment]
What would be simpler would be to just run one of the docker scripts
(all called "dockit") for a given (or even random) environment. This
would have the advantage of exactly matching what I do when I build
10-12 environments on my home system for a release.

This is already all set up and ready to go. It does the github pull and
so on all by itself. I seem to recall they take around 20-30 minutes
each to run on my machine. On the other hand, I probably have a lot of
those packages cached... I could certainly have my CI guy experiment
with it.

On the other hand, what we have works, and in my judgment is unlikely to
have troubles. I could even make only the one or two tests that need
ipv6 turn it on and off as needed...

I'll discuss it with my CI guy.


On 12/07/2015 04:46 PM, Brandon Burton wrote:
>
> @Alan-R <https://github.com/Alan-R> You're able to use Docker inside a
> build, with http://docs.travis-ci.com/user/docker/, the build runs in
> a Trusty VM on GCE and has Docker pre-installed, you're able to do any
> Docker interactions you might do on a local machine, our usual time
> outs on output and total build length time do still apply.
>
> So what I was envisioning would be something like
>
>  1. Move your |install:| and |before_scripts| steps into a Dockerfile
>     you put in your repository. and then use the Docker Hub to build,
>     publish, and store it for you.
>  2. Make your |install:| step consistent of a |docker pull ...|
>  3. Modify your |script:| steps so that you use |docker run ...|
>     inside the container you build above, which contains what you need
>     to build and test your code.
>
> We have a number of users who've moved to a similar workflow now we
> support build VMs that can run Docker in them.
>
> Please let me know what you think of what I have outlined above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/travis-ci/issues/5200#issuecomment-162707407>.
>


-- 

Alan Robertson / CTO
AlanR@AssimilationSystems.com <mailto:AlanR@AssimilationSystems.com>/ +1
303.947.7999

Assimilation Systems Limited
http://AssimilationSystems.com

Twitter <https://twitter.com/ossalanr> Linkedin
<https://www.linkedin.com/in/alanr> skype
<https://htmlsig.com/skype?username=alanr_unix.sh>

**Comment by solarce** [comment]
@Alan-R I'll defer to you on how you'd prefer to proceed, but the summary is that if you run the tests that need `::1` on `lo` inside a build by using http://docs.travis-ci.com/user/docker/, you'll be able to have working IPv6 and at this time that's the only way to achieve it while using Travis CI for Linux builds.

**Comment by Alan-R** [comment]
The only supported way. We have a way now, just not a supported way.
