### ISSUE TITLE
How to run test that takes longer than 10 minutes to run?

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#5201]
I've set of tests which run longer than 10 minutes and I don't expect any output during that time, however the test fails with:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Is there any options that I can set to increase that time limit or ignore stopping the script at all?

Similar to #4098, but I don't have any test/network issues and I want to disable this limitation intentionally.

**Comment by BanzaiMan** [comment]
@kenorb You can use an undocumented bash function `travis_wait`. It'll send the command to the background, and writes `.` to STDOUT. When the command finishes, the result in dumped to the log.

```
travis_wait DO_LONG_STUFF # up to 20 minutes
```

or

```
travis_wait 30 DO_LONG_STUFF
```

**Comment by kenorb** [comment]
Seems it's working fine, thank you.
It's actually documented in here: [Build times out because no output was received](https://docs.travis-ci.com/user/build-timeouts/)

Related:

- [How can I install scipy from pip on travis-ci.org without a timeout?](http://stackoverflow.com/q/28746046/55075) at SO
