### ISSUE TITLE
Elasticsearch synonyms

### ISSUE THREAD

**Issue by tjgillies** [travis-ci/travis-ci#5202]
We are trying to migrate over to Docker enabled Travis builds, however we have a synonym configuration for elasticsearch that we need to set. It looks similar to
`sudo cp config/elasticsearch/address_synonyms.txt /etc/elasticsearch/address_synonyms.txt`. Is there a way to configure this without being root?

**Comment by BanzaiMan** [comment]
Sorry, but there is not, as `/etc/elasticsearch` is owned by `root`. (Which I believe is the configuration dictated by the package.)

**Comment by tjgillies** [comment]
Is there a way to tell the absolute path of a file in the repo as it is on the Travis server?

**Comment by BanzaiMan** [comment]
@tjgillies I think you want `$TRAVIS_BUILD_DIR`, which points to the root of the repository when it is cloned. For others, please consult https://docs.travis-ci.com/user/environment-variables/.
