### ISSUE TITLE
When deploying using a custom script rvm is unset

### ISSUE THREAD

**Issue by pabloh** [travis-ci/travis-ci#5205]
I tried running a custom deployment script by setting `provider: script` and the rvm environment was no longer set. 

I had to workaround it by setting the script value to: `script: "rvm $TRAVIS_RUBY_VERSION do deploy.sh"` in order to use the correct Ruby version from the Job.

**Comment by BanzaiMan** [comment]
@pabloh Thanks for taking the time to open the issue. When we deploy, we use a version of Ruby that we know to exist on all build images, so your Ruby version does not affect the execution environment. We know this is not very intuitive and also not clearly documented.

We have discussed how we may make this experience better, but we do not yet know how.

Is it sufficient to note this in our documentation?

**Comment by pabloh** [comment]
@BanzaiMan, I guess better documentation would suffice. But I must admit is still surprising that is falling back to Ruby 1.9.3 instead of a more recent version, specially if you take in to account that Ruby 1.9.3 is not officially supported any more.

**Comment by BanzaiMan** [comment]
@pabloh I understand how you feel about 1.9.3. We are looking to update the version that we have on every image, but the issue will persist, no matter what the version.

**Comment by pabloh** [comment]
@BanzaiMan , yes I understand there is no simple way around the other issue.
