### ISSUE TITLE
PHPUnit requires PHP 5.6

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5206]
As originally reported by @jadatkins in https://github.com/travis-ci/travis-ci/issues/5204#issuecomment-161996467

> the pre-installed version of PHPUnit requires PHP 5.6, but we've requested 5.5 in our .travis.yml. Our production server is running PHP 5.5, so it would be better if we could stick with 5.5 really.
>  ```
phpunit -c tutorfair/tests/phpunit.xml --colors tutorfair/tests/apps
This version of PHPUnit requires PHP 5.6; using the latest version of PHP is highly recommended.
make: *** [tests] Error 1
The command "make tests" exited with 2.
```

**Comment by jadatkins** [comment]
I'm confused. Do I have to send a support email now or not?

**Comment by BanzaiMan** [comment]
@jadatkins If this is the only issue remaining, it is up to you. We will investigate it and keep you in the loop.

**Comment by jadatkins** [comment]
Well, I don't really mind which channel it is. I've sent an email now as well. Do I need to request that our builds stay on the previous architecture until this is fixed or something?

I suppose I add
```yaml
    dist: precise
    group: stable
```

to my .travis.yml? Only that won't work, because we're already using `group: dev` for MySQL 5.6.

**Comment by BanzaiMan** [comment]
@jadatkins This is a packaging issue, as it turns out. Until we can fix the 5.5 package, do this in your `before_install:`

```yaml
  - curl -s -o $HOME/.phpenv/versions/5.5/bin/phpunit https://phar.phpunit.de/phpunit-old.phar
  - chmod +x $HOME/.phpenv/versions/5.5/bin/phpunit
```

**Comment by BanzaiMan** [comment]
Re-packaging 5.5.30 is possible, but it would be without PEAR. I wonder if that's feasible now.

**Comment by jadatkins** [comment]
Ok. We actually need PHPUnit 4.8, ideally, so I've added the following.

```yaml
before_install:
  - curl -s -o $HOME/.phpenv/versions/5.5/bin/phpunit https://phar.phpunit.de/phpunit-4.8.9.phar
  - chmod +x $HOME/.phpenv/versions/5.5/bin/phpunit
```

... and that seems to have worked. Great! Thanks.

**Comment by BanzaiMan** [comment]
@jadatkins Great to hear. I'm going to keep this open while we work out the packaging issue.

**Comment by dregad** [comment]
For the record, we're facing the same issue here https://travis-ci.org/mantisbt/mantisbt/jobs/95206430.

I will try the proposed workaround. Any ETA on a fix for this ?

**Comment by fagundes** [comment]
Some progress to fix this?

**Comment by BanzaiMan** [comment]
The PHP 5.5 package should be fixed now. https://travis-ci.org/BanzaiMan/travis_production_test/builds/96659602#L130

**Comment by dregad** [comment]
Thanks !

**Comment by jadatkins** [comment]
@BanzaiMan Does that mean I should remove my `before_install` section now?

**Comment by BanzaiMan** [comment]
@jadatkins Your build should work without it now.
