### ISSUE TITLE
pear.php.net hardware failure and how it affects Travis CI

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5207]
One of the core servers of the PHP ecosystem, pear.php.net has encountered a catastrophic hardware failure about a week ago.

https://twitter.com/official_php/status/671424892613427200

> http://pear.php.net  update: still being worked on; no ETA on full restoration at present. Root cause of outage is a hardware failure.

An interim server is up, but its SSL certificate is invalid, so any connexion to https://pear.php.net will fail.

This affects many things, including the tool we use to compile PHP (which is how PHP 7 is supported at the moment); extension installation should similarly fail.

We are sorry for the inconvenience, and we thank you for your understanding and patience.

**Comment by BanzaiMan** [comment]
Sorry about the delay. https://peR.php.net is now serving a valid certificate, but I've been traveling across the Pacific for a conference and have not had time to follow up on building PHP 7.0.0 official release. I hope to have some time tomorrow (JST).

Thanks.

**Comment by GrahamCampbell** [comment]
We've removed pear from php-build now btw.

**Comment by cweiske** [comment]
Our server is back up; you can re-enable pear it in your builds.

**Comment by BanzaiMan** [comment]
@GrahamCampbell That poses a problem. Now, I need to stay with https://github.com/php-build/php-build/commit/557cb45 and hope that later definitions and fixes will apply cleanly, or read the php-build code on how to enable pear in the build process.

**Comment by GrahamCampbell** [comment]
We'd accept a PR to add some sort of hook system to allow users to write a pear extension.

**Comment by BanzaiMan** [comment]
The server is functioning correctly, so I'm closing this one, and follow up on the other issue (PHP building process) in #5256.
