### ISSUE TITLE
Tests suite that has never passed, don't display a graph

### ISSUE THREAD

**Issue by shoham-stratoscale** [travis-ci/travis-ci#5209]
When creating a new test suite, and the tests suite has always failed to pass, travis doesn't show a graph for the tests.
Only when all the tests in the suite passed for the first time, a graph is displayed.
The correct behavior, if I have 100 tests and 1 fails to pass, to display a graph with 99 "green" tests and one "red" test

**Comment by BanzaiMan** [comment]
Could you show build logs, what configurations you've tried, how they failed, and so on? I am sorry to say, but there is nothing we can act on in this description.

**Comment by shoham-stratoscale** [comment]
@BanzaiMan Thank you so much for your reply.
I'll of course supply any information I can to help get this bug fixed.
I don't think that there was any failures, the metadata was collected successfully, simply a graph is not displayed until the entire test suite passed successfully. If 99/100 tests pass, the graph is not displayed.
Only after the test suite passes fully (100/100), the graph is displayed correctly, for the failed history as well.

In the log, I see:
```
Recording test results
Collecting metadata...
Metadata collection done.
```

And to achieve this, in my configuration, I wrote:
![screenshot]
(http://s21.postimg.org/4crl4p2s7/Screenshot_from_2015_12_06_10_52_17.png)

Any other information I can supply?

**Comment by BanzaiMan** [comment]
That looks like a Jenkins configuration page. Do you have a build log URL on Travis to illustrate what you're trying to do?

**Comment by shoham-stratoscale** [comment]
Oh OK. So I guess I'll open this issue on jenkins' page. Thanks for your help
