### ISSUE TITLE
reports asio.hpp missing?

### ISSUE THREAD

**Issue by dpocock** [travis-ci/travis-ci#5212]
The libasio-dev package is successfully installed but during the build g++ complains that asio.hpp is missing:

https://travis-ci.org/resiprocate/resiprocate/jobs/94955809

It was not failing like this before.  This part of the code hasn't been changed recently.  Has something changed in the way Ubuntu or the compiler is configured by default?

I checked the contents of the libasio-dev package and the asio.hpp header file is installed to /usr/include/asio.hpp so it should have been found by a normal compiler.

**Comment by BanzaiMan** [comment]
Could you run `find /usr -name asio.hpp -type f` to see where it really is?

**Comment by dpocock** [comment]
Is there a way to log in to the travis-ci filesystem to do that?

I downloaded the package from https://launchpad.net/ubuntu/trusty/amd64/libasio-dev/1.10.1-1

and manually extracted it

    cd /tmp
    mkdir asio-test
    cd asio-test
    wget http://launchpadlibrarian.net/164641257/libasio-dev_1.10.1-1_all.deb
    dpkg -X libasio-dev_1.10.1-1_all.deb .
    find . -name asio.hpp

and it shows me

    ./usr/include/asio.hpp

**Comment by dpocock** [comment]
looks like some other package from Ubuntu is conflicting and it was quietly removing the asio package after installing it
