### ISSUE TITLE
R check, ncdf and rgdal cannot correctly installed.

### ISSUE THREAD

**Issue by Yuanchao-Xu** [travis-ci/travis-ci#5215]
Try to use travis for [my package](https://github.com/Yuanchao-Xu/hyfo).

with .travis.yml
```{}
language: r
warnings_are_errors: true
sudo: required
env:
  global:
    - NOT_CRAN = true
```
I got the error message `ERROR: dependencies ‘rgdal’, ‘ncdf’ are not available for package ‘hyfo’`

Then I added the following to install dev version of `ncdf` and its dependences. It seems the problem with `ncdf` has been solved, but the problem with `rgdal` still existed.
```{}
apt_packages:
  - libnetcdf-dev
  - udunits-bin
  - libudunits2-dev
  - netcdf-bin
```

Then I use the same way to install dev version of `rgdal`, added following lines under `apt_packages`,
```{}
- libproj-dev
- libgdal-dev
```

And here comes the endless lack of dependencies, I install them one by one, the final settings are like following:

```{}
apt_packages:
  - libnetcdf-dev
  - udunits-bin
  - libudunits2-dev
  - netcdf-bin
  - libproj-dev
  - libcurl4-gnutls-dev
  - libdap-dev
  - libgdal-dev
  - libgdal1h
  - libhdf5-7 = 1.8.11-3ubuntu1~precise1~ppa1
  - libhdf5-dev
  - libhdf5-serial-dev
  - libgdal-dev
  - libgdal1-dev
```

And I still get the error message below, but ` libhdf5-7 = 1.8.11-3ubuntu1~precise1~ppa1` was suggested by the machine the second last trial.

```{}
E: Unable to locate package 
E: Unable to locate package 1.8.11-3ubuntu1~precise1~ppa1
E: Couldn't find any package by regex '1.8.11-3ubuntu1~precise1~ppa1'
```

Anybody can help me with this? Is this a problem with travis or with package `rgdal`?

**Comment by BanzaiMan** [comment]
This should be fixed by now. Please try again.

**Comment by Yuanchao-Xu** [comment]
@BanzaiMan Thx, I've solved problem by changing the dependency version of rgdal. from 0.9-3 to 0.8-16, and then install binary rgdal.
