### ISSUE TITLE
Update the default Node.js version to 4.2.x

### ISSUE THREAD

**Issue by jasonkarns** [travis-ci/travis-ci#5218]
Latest stable node is 5.1.1 (as of today). The default installed stable node by travis is 3 versions behind.

**Comment by jasonkarns** [comment]
Presently, the `stable` alias is deprecated, but should have been installing 0.12 most recently (not 0.10). And the current recommended alias (`node`) installs the latest node. Is travis using an old version of nvm?

**Comment by BanzaiMan** [comment]
4.2.x is the current LTS version, so we should move there.

We'll need to update the cookbooks and provision images before the default can be changed on the build script.

Also, see #5333.

**Comment by ntwb** [comment]
Should there be `4.x` and `5.x` aliases for the branches which would currently be `4.2.x` and `5.3.x` respectively? Rather than, or in addition to the _minor_ alias `4.2.x`?

**Comment by BanzaiMan** [comment]
@ntwb Those names are a different issue entirely (and handled by `nvm`).

**Comment by ntwb** [comment]
Right, thanks :+1:

**Comment by un1versal** [comment]
Can you guys update or add node.js 6.4.0 we need minimum version 6.x...

alternatively if theres a way to load/build against that in travis please let me know how...

**Comment by jdalton** [comment]
@jasonkarns  Has this changed?

**Comment by ntwb** [comment]
@jdalton Everything is working as expected for me, or at least it was ~3 hours ago

**Comment by jasonkarns** [comment]
@jdalton yep, closing. Seems to be using v7 right now.
