### ISSUE TITLE
Issue with building  .NET 4.5 C# application - caused by the Mono version

### ISSUE THREAD

**Issue by andronachev** [travis-ci/travis-ci#5219]
Hi there, 

We're developing an API Client using .NET 4.5 and C#. We're explicitly setting the SecurityProtocol in our library, because the API only works with Tls2. 
However, the build fails in Travis because the version of Mono installed does not have Tls2 in it. 
The concrete error is: 

`System.Net.SecurityProtocolType' does not contain a definition for`Tls12'

Our line of code which build fine locally, becasue it's .NET 4.5, not mono: 

System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Can you recommend any way arround this ? I'm not sure if updating the Mono version is an option. 

Thanks for your ideas
@joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
The Tls12 define was only recently added (https://github.com/mono/mono/commit/2dc99a0e43179aa2e2854cc1312ed486e2806431). You need to use the weekly Mono build, wait until the next release or work around it some other way.

**Comment by bhelx** [comment]
We've added `weekly` as suggested:

https://github.com/recurly/recurly-client-net/pull/143/files#diff-354f30a63fb0907d4ad57269548329e3R3

The Travis console states this version:

```
0.04s$ xbuild /version
XBuild Engine Version 14.0
Mono, Version 4.5.0.0
Copyright (C) 2005-2013 Various Mono authors
```

Yet still the constant is undefined

```
Client.cs(33,73): error CS0117: `System.Net.SecurityProtocolType' does not contain a definition for `Tls12' /usr/lib/mono/4.5-api/System.dll (Location of the symbol related to previous error)
```

**Comment by bhelx** [comment]
Any updates on this issue? Should we file this with mono instead?

@akoeplinger Does my travis config look right?

**Comment by bhelx** [comment]
A workaround I have found is to do what the Kestrel project is doing here:

https://github.com/aspnet/KestrelHttpServer/blob/14bbba06418234f1f6d41eb2540ca26f8598fd23/test/Microsoft.AspNetCore.Server.KestrelTests/HttpsConnectionFilterTests.cs#L30

**Comment by akoeplinger** [comment]
@bhelx it looks like the value wasn't added to the .NET 4.5 contracts/reference assemblies. You should be able to workaround if you target .NET 4.6.

**Comment by bhelx** [comment]
Thanks a lot @akoeplinger

I'll make a reminder to update our project

**Comment by aniljain100** [comment]
Hi All,

I am trying to deploy a .NET Web API to mono using the below command, but its failing to push.

_cf push consoleapp -b https://github.com/cloudfoundry-community/.net-buildpack_

I am posting this question here as it looks like **andronachev** is able to deploy .NET framwork 4.5.x on cloud foundry.

My apologies if I posted in the wrong forum.

Any help will be really appreciated.

Thanks
