### ISSUE TITLE
Build fails because package can't be located

### ISSUE THREAD

**Issue by est31** [travis-ci/travis-ci#5221]
[Minetest](https://github.com/minetest/minetest) fails to build on the [new gce based infrastructure](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future):
- Working build on `worker-linux-44a99d76-1.bb.travis-ci.org:travis-linux-14` https://travis-ci.org/minetest/minetest/jobs/93740414
- Failing build on `travis-worker-gce-org-prod-1:9f9e40c8-86f3-4dff-a99d-457b43b033ff` https://travis-ci.org/minetest/minetest/jobs/94725512

No changes of travis related scripts between those two builds.
The [error message of the failing build](https://travis-ci.org/minetest/minetest/jobs/94725512#L127):

```
E: Unable to locate package p7zip-full
```

**Comment by est31** [comment]
It seems to work again if you add `sudo apt-get update` to it, but it does require additional build time to download all those sources.

https://github.com/minetest/minetest/pull/3427

**Comment by neothemachine** [comment]
[Same problem for me](https://travis-ci.org/neothemachine/lensfunpy/jobs/95086875). Package `liblensfun-dev`.

**Comment by marc1706** [comment]
Same issue for our current phpBB builds for retrieving the package ```parallel```: https://travis-ci.org/phpbb/phpbb/jobs/95065974

**Comment by meatballhat** [comment]
@est31 @neothemachine @marc1706 Does the addition of `sudo apt-get update` fix the problem?  The apt lists are currently being wiped at the end of the image-baking process, although this step was added prior to GCE and the space savings aren't as big of a deal on GCE, so I can see leaving the apt lists in place as a decent fix.

**Comment by neothemachine** [comment]
@meatballhat [Yes](https://travis-ci.org/neothemachine/lensfunpy/jobs/95117092#L199).

**Comment by est31** [comment]
@meatballhat I confirm, `sudo apt-get update` fixes the problem, as pointed out above. That's why I've closed the bug. I did reopen it because I've thought that I'm not the only one having the problem, and perhaps the `apt-get update` could be done before the image gets created, so that it would require less time for all the builder instances. It would also be consistent with previous behaviour.

**Comment by marc1706** [comment]
@meatballhat If adding ```apt-get update``` fixes that I'm fine with it. I just don't want to change this and then have to revert it again a few days later because you added the apt lists again.

**Comment by michaelcullum** [comment]
Running `apt-get update` doesn't resolve this issue for `parallel` https://travis-ci.org/phpbb/phpbb-website/jobs/95158185

**Comment by hugovk** [comment]
I reported a similar problem in https://github.com/travis-ci/travis-ci/issues/5232.

Adding `sudo apt-get update` fixes the issue here too.

**Comment by hobofan** [comment]
Package `fglrx` is also not fixed by running `sudo apt-get update` (which has already been in place):
https://travis-ci.org/autumnai/collenchyma/jobs/95217779

**Comment by meatballhat** [comment]
For anyone still experiencing this issue, can you confirm that your universe and/or multiverse packages are still unavailable after an `apt-get update`?   If so, please include a link to the job showing the problem.  Thank you! :heart_eyes_cat:

**Comment by hobofan** [comment]
@meatballhat https://travis-ci.org/autumnai/collenchyma/jobs/95217779 still not working. It looks like `fglrx` is a restricted package. Are those supposed to be gone?

**Comment by michaelcullum** [comment]
@meatballhat As previously said, `apt-get update` doesn't fix it always. https://travis-ci.org/phpbb/phpbb-website/jobs/95158185

**Comment by meatballhat** [comment]
@hobofan got it, I'll verify the restricted package situation

**Comment by TimmyLiu** [comment]
As mentioned in issue #5249 builds that depend on fglrx (OpenCL) are still falling on GCE platform.
two examples are
clBLAS: https://travis-ci.org/clMathLibraries/clBLAS/jobs/95440841
boostorg/compute: https://travis-ci.org/boostorg/compute/jobs/95215890

both failed at the stage of installing fglrx.

**Comment by fniephaus** [comment]
Same here: https://travis-ci.org/hpi-swa/smalltalkCI/jobs/95878116#L113
We can't even run `apt-get update` manually, because it fails when running the Smalltalk build script.

**Comment by BanzaiMan** [comment]
Are we seeing recent problems?

**Comment by hobofan** [comment]
Problem still remain:
https://travis-ci.org/autumnai/collenchyma/jobs/96801081

**Comment by BanzaiMan** [comment]
@hobofan Could you try restarting that build?

**Comment by hobofan** [comment]
@BanzaiMan Still the same. If you need to retry the build a few times for troubleshooting, feel free to do that. (I asume you have some special privileges to do so?)

**Comment by fniephaus** [comment]
I re-ran one of the jobs and they also still have the same problem:
https://travis-ci.org/hpi-swa/smalltalkCI/jobs/95878128

Do I need to trigger new builds?

**Comment by meatballhat** [comment]
Sorry for the delays, all :heart:

The `restricted` sources should now be available on both precise and trusty `group: edge`.  Promotion to `group: stable` will likely happen in the next 24 hours for precise, whereas promotion for trusty will likely be at the beginning of 2016.  Related PRs:

* https://github.com/travis-ci/travis-cookbooks/pull/653
* https://github.com/travis-ci/travis-cookbooks/pull/654
* https://github.com/travis-ci/packer-templates/pull/136

**Comment by cdeterman** [comment]
@meatballhat 

I added `group: edge` to my `.travis.yml` (precise) but fglrx still won't install.

My [.travis.yml](https://github.com/cdeterman/gpuR/blob/master/.travis.yml)
Build [result](https://travis-ci.org/cdeterman/gpuR/builds/97229616)

Did I miss something in your last comment?

**Comment by cdeterman** [comment]
This still continues to remain a problem.  Have there been any further updates or did I miss something.  Apologies if I am being obtuse here.

**Comment by fniephaus** [comment]
@cdeterman same here

**Comment by kknox** [comment]
@cdeterman @fniephaus 
I have a hack workaround for fglrx builds; building the [OpenCL ICD library from source](https://github.com/clMathLibraries/clSPARSE/blob/develop/.travis.yml#L89).  This won't allow you to run opencl programs (such as on CPU device) but you can build because all the linkable symbols are present.

**Comment by joshk** [comment]
So, I am a bit lost now, what is the problem, has anything been solved, and can this be closed and any remaining issues be moved to a new issue?

**Comment by fniephaus** [comment]
My problem is that none of the following packages can be installed in trusty images:
`apt-get install --no-install-recommends libc6:i386 libuuid1:i386 libfreetype6:i386 libssl1.0.0:i386`

even though they do exist (e.g. [here](https://launchpad.net/ubuntu/trusty/i386/libssl1.0.0)).

Maybe there's a general problem with installing `i386` packages?

**Comment by fniephaus** [comment]
Maybe the following would fix it?
```bash
sudo dpkg --add-architecture i386
sudo apt-get update
```
Installing `i386` packages certainly worked in precise images.

**Comment by joshk** [comment]
@meatballhat @BanzaiMan thoughts and ideas?

**Comment by cdeterman** [comment]
@joshk It also still appears that `fglrx` is still not able to be installed.

**Comment by pfalcon** [comment]
> sudo dpkg --add-architecture i386
> sudo apt-get update
> Installing i386 packages certainly worked in precise images.

I confirm this fixed problem for us. Thanks!

**Comment by Ladsgroup** [comment]
Adding `sudo apt-get update` didn't work and also `sudo dpkg --add-architecture i386`. Just finding this page took several hours of mine. You should put a notice about a bug this big in travis-ci.org

**Comment by pfalcon** [comment]
From yesterday, our builds requiring i386 started to fail, e.g. https://travis-ci.org/micropython/micropython/builds/113235132 . The error is:

~~~
$ sudo dpkg --add-architecture i386
$ sudo apt-get update -qq
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
~~~

No idea how google with its chrome got into our build. Must be a trojan rampaging thru travis servers.

**Comment by pfalcon** [comment]
Following worked it around for us:

~~~
-  - sudo apt-get update -qq
+  - sudo apt-get update -qq || true
~~~

**Comment by JaredCrean2** [comment]
I am having the same issue with mpich:
```
+sudo apt-get install mpich

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package mpich is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'mpich' has no installation candidate
```

**Comment by est31** [comment]
@pfalcon another theory than a trojan, albeit less exciting is that its a bug, probably caused by usage of the new container infrastructure and whitelisted apt sources being used on the same machine. But no idea.

**Comment by bobzoller** [comment]
```
sudo apt-get update
[... snip ...]
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

(as others, we don't add the Chrome repo, it must be there in the base legacy image.)

https://travis-ci.com/goodeggs/purchase-orders-api/builds/22123944

**Comment by dissolve** [comment]
This thread seemed to get on to several other issues,
but I found a few more packages for the list
libsdl2-dev
libboost-locale-dev

I have tried a couple of different ways to make sure, and both fail with "Unable to locate package"

https://github.com/dissolve/EStation3/blob/d798cc2b22148ff2e39365cb952e5aa3eba862bd/.travis.yml
resulted in 
https://travis-ci.org/dissolve/EStation3/builds/141189619

https://github.com/dissolve/EStation3/blob/b5be38df156f4935626b36c5f57bc9d038da10ef/.travis.yml
resulted in
https://travis-ci.org/dissolve/EStation3/builds/141193136

Any suggestions?

**Comment by meatballhat** [comment]
Apologies for allowing this thread to go cold.  Please yell if you are still having issues with locating packages! :heart:

**Comment by dissolve** [comment]
@meatballhat still having problems

E: Unable to locate package libsdl2-dev
E: Unable to locate package libboost-locale-dev

https://travis-ci.org/dissolve/PieStation/builds/141428489

**Comment by sih4sing5hong5** [comment]
It still failed with `E: Unable to locate package libx11-dev`

https://travis-ci.org/sih4sing5hong5/tai5-uan5_gian5-gi2_kang1-ku7/jobs/212042053

**Comment by WilixLead** [comment]
I have same issue for libxkbcommon-x11-dev
`E: Unable to locate package libxkbcommon-x11-dev`

I use `sudo apt-get -qq update` before. This is part of my .travis.yml

```yml
language: node_js
dist: precise
sudo: required

node_js:
  - node

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libx11-dev libxtst-dev libxt-dev libx11-xcb-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxkbcommon-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxkbcommon-x11-dev; fi
```
Also, I check [approved packages](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) and found "libxkbcommon-x11-dev" in list. But build's still fail

**Comment by bstabler** [comment]
I also had the same issue, but for `libnlopt-dev`.  Adding `dist:trusty` worked for me as well.

```
language: R
sudo: true
dist: trusty
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libnlopt-dev
```

**Comment by taqtiqa-mark** [comment]
We're seeing the same issue with `debootstrap-base`.  The `dist: trusty` sudo: true` and `apt-get update` workarounds do not work for us.

**Comment by sivhollup** [comment]
I have a similar issue with language-pack-no 
Neither trusty nor precise work for me.

**Comment by BanzaiMan** [comment]
@sivhollup Which repository is supposed to have it? Ubuntu certainly does not. https://packages.ubuntu.com/trusty/language-pack-no

**Comment by sivhollup** [comment]
Good question, I thought my google mojo was off today. I found language-pack-nb now, but that does not solve my problem (same for language-pack-nn). I'm going to have to work around this with a different approach. Thanks for a quick reply!
