### ISSUE TITLE
/tmp not large enough for extracting coverity tools

### ISSUE THREAD

**Issue by devernay** [travis-ci/travis-ci#5222]
Using the default coverity scan script, coverity tools can not be installed anymore.
The archive size itself is 345Mb.
When untarred, it grows beyound the 1Gb space available in /tmp

It may be a coverity issue too (tools should better be installed in /opt for example)

See line 241+ of 
https://travis-ci.org/devernay/openfx-misc/jobs/95075677

**Comment by meatballhat** [comment]
I've reverted 1G of `tmpfs` in `/tmp` in favor of the existing 768M of `tmpfs` in `/var/ramfs`, meaning `/tmp` should be part of the root partition once again.  Please yell if you see otherwise!
