### ISSUE TITLE
Git version too old

### ISSUE THREAD

**Issue by miloyip** [travis-ci/travis-ci#5225]
After the migration, an error is reported for using `git clone --single-branch` option in a build script.

https://travis-ci.org/miloyip/rapidjson/jobs/95137724

~~~
git version 1.7.9.5
error: unknown option `single-branch'
~~~

It seems the git version is very old (4 years ago).

**Comment by floooh** [comment]
Same here: https://travis-ci.org/floooh/yakc/jobs/95184602

**Comment by meatballhat** [comment]
Thanks for the report!  I'm working on getting this fixed up.  Related PR: https://github.com/travis-infrastructure/packer-templates/pull/123

**Comment by meatballhat** [comment]
See also: https://github.com/travis-ci/travis-cookbooks/pull/641

**Comment by floooh** [comment]
Confirmed working :) Thanks!
