### ISSUE TITLE
Stucking at Syncing from Github

### ISSUE THREAD

**Issue by DevVersion** [travis-ci/travis-ci#5229]
As followed my organizations won't show up, and the `Sync-Button` is doing his animation all time.

After that I removed my cookies and local storage and then I saw a few errors in the Chrome Dev Tools

![](https://i.gyazo.com/670a84025a410fd40f31668cbc89be6d.png)

**Comment by BanzaiMan** [comment]
Is this still a problem?

**Comment by BanzaiMan** [comment]
Closing due to lack of response.
