### ISSUE TITLE
Stuck at downloading maven dependency

### ISSUE THREAD

**Issue by beikov** [travis-ci/travis-ci#5230]
As you can see here, the download seems to be stuck: https://travis-ci.org/Blazebit/blaze-persistence/jobs/95073316#L2273

The build of the previous commit worked just fine on the old infrastructure: https://travis-ci.org/Blazebit/blaze-persistence/jobs/94650037#L2370

I don't really understand why, but a different build matrix entry works just fine: https://travis-ci.org/Blazebit/blaze-persistence/jobs/95073317#L2307

Any idea how I could fix this?

**Comment by BanzaiMan** [comment]
Is this still a problem? Seems like it's a temporary network issue.

**Comment by beikov** [comment]
Still a problem: https://travis-ci.org/Blazebit/blaze-persistence/jobs/95073316

**Comment by BanzaiMan** [comment]
Curious that there are other downloads on this job prior to https://travis-ci.org/Blazebit/blaze-persistence/jobs/95073316#L2292 that fetches files from repo.maven.apache.org.

**Comment by beikov** [comment]
Still a problem: https://travis-ci.org/Blazebit/blaze-persistence/jobs/108278896

**Comment by beikov** [comment]
I already tried different JDKs, different Maven versions, but still it's stuck at downloading that same dependency!
https://travis-ci.org/Blazebit/blaze-persistence/builds/109458084

**Comment by BanzaiMan** [comment]
Looks like the latest builds are doing better. https://travis-ci.org/Blazebit/blaze-persistence/builds/117556260

Can this be closed?

**Comment by beikov** [comment]
I actually applied a workaround. I let maven download the problematic dependency already in an earlier module and switched to only build the necessary modules for the active profiles instead. This issue is still a problem.
