### ISSUE TITLE
Failure to install node 4.2.0 when also python 2.7 is specified as requirement

### ISSUE THREAD

**Issue by evilaliv3** [travis-ci/travis-ci#5234]
As visible in the following links/screenshots indicating multiple software versions (python: 2.7, node_js: 4.2.0) travis is failing to setup node 4.2.0

the error given should not be taken in care but i can confirm that is simply due to the fact that a software we are using (protractor)  is failing due to the missing of node >= 4.2.0

https://travis-ci.org/globaleaks/GlobaLeaks/builds/95225428

the reference .travis.yml is: https://github.com/globaleaks/GlobaLeaks/blob/89f1ca1a4cd5935ccb1078a6ea7e4f2c09b9e57d/.travis.yml

as visibile in the following screenshot travis seems recognize the requirement for bot h python 2.7/node.js 4.2.0 but that it does not take any action for node.js

![screenshot from 2015-12-06 21 22 05](https://cloud.githubusercontent.com/assets/217034/11615390/81871e82-9c5f-11e5-8492-0077250c94a2.png)

**Comment by evilaliv3** [comment]
i just re-triggered the build and it appear now fixed. 

the issue appears to have been caused by a network failure.

**Comment by evilaliv3** [comment]
I'm reopening this issue cause it's really seems that if i specify both pyhon 2.7 and node 4.2 travis is failing to setup node 4.2 and still uses 0.10:
- https://travis-ci.org/globaleaks/GlobaLeaks/jobs/95933960
- https://s3.amazonaws.com/archive.travis-ci.org/jobs/95933960/log.txt

**Comment by BanzaiMan** [comment]
Your `.travis.yml` is configured to use `python`. In this case, `node_js` key is a no-op, and the default is used. I suggest using `nvm` to install the version of Node.js you want in `before_install` (or any place before the first use of `node`):

```yaml
before_install:
  - nvm install 4.2
  ⋮
```

**Comment by evilaliv3** [comment]
@BanzaiMan the suggested nvm install 4.2 is failing so that i think this cannot be alone a solution.

https://travis-ci.org/globaleaks/GlobaLeaks/jobs/96816823
https://s3.amazonaws.com/archive.travis-ci.org/jobs/96816823/log.txt

the issue seems similar to https://github.com/bnoordhuis/node-iconv/issues/136 and is probably related due to the fact that the environment cannot be updated to node 4.2 starting from the default travis one.

do you have any hint?

**Comment by evilaliv3** [comment]
here is the coloured output: https://travis-ci.org/globaleaks/GlobaLeaks/jobs/96837802

![screenshot from 2015-12-14 22 29 56](https://cloud.githubusercontent.com/assets/217034/11794561/46802438-a2b2-11e5-88e8-95d3611091bd.png)

**Comment by evilaliv3** [comment]
okay, i updated to trusty and all is now fixed.

**Comment by BanzaiMan** [comment]
@evilaliv3 What does "the environment cannot be updated to node 4.2 starting from the default travis one" mean? As far as I know, we use a straightforward installation of `nvm`, and if it can't update Node.js to a more recent version, then it is an issue with `nvm`.

@ljharb Do you have any insight into this issue?

**Comment by ljharb** [comment]
@BanzaiMan The log indicates that the user has a binary node module in their dependency tree that is simply incompatible with node 4 - note the `Nan` error with `iconv`.

**Comment by evilaliv3** [comment]
exactly @ljharb 

basically i think that the nvm install 4.2 cannot work on the current precise image, but from a trial & error fixing i got it working on the travis image.

**Comment by BanzaiMan** [comment]
@evilaliv3 Interesting. Is it something beyond what we documented in https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements? If so, we welcome your improvements.

**Comment by evilaliv3** [comment]
@BanzaiMan i think it's exactly; sorry for have not found that documentation before :(

**Comment by BanzaiMan** [comment]
@evilaliv3 No worries. Happy to hear that you were able to resolve the issue.
