### ISSUE TITLE
No secure random source

### ISSUE THREAD

**Issue by overheadhunter** [travis-ci/travis-ci#5235]
On the old infrastructure it was no problem to run unit tests, that rely on secure random numbers. Apparently no such source is available any longer on the new infrastructure. I really don't want to adjust the tests to the capabilities of one build system, if the random number generator on the build system can be a symlink to a deterministic source (totally sufficient for tests).

I wrote a minimal test consisting of only 3 lines of code in [this repo](https://github.com/overheadhunter/secrandom-precise-gce).

This is the corresponding [build result](https://travis-ci.org/overheadhunter/secrandom-precise-gce/builds/95242579), timing out after 10 seconds, but on a different project I experience the same even after 10 minutes (used to work on old infrastructure).

As no "real" entropy is needed during tests, it would be feasible to provide a fake random generator in the VMs.

By the way the [same problem exists for Docker containers](https://travis-ci.org/overheadhunter/secrandom-precise-gce/builds/95242178), a possible solution might be [given here](http://stackoverflow.com/questions/26021181/not-enough-entropy-to-support-dev-random-in-docker-containers-running-in-boot2d).

**Comment by BanzaiMan** [comment]
To clarify, you are reporting issues with the [container-based infrastructure](https://docs.travis-ci.com/user/workers/container-based-infrastructure), correct?

For the new GCE-based one (with `sudo: required`), one user reported that [haveged](http://packages.ubuntu.com/precise/haveged) provides enough entropy.

**Comment by overheadhunter** [comment]
Nope, this is about GCE-based infrastructure as well as container-based. See buid logs (I just updated the links).

**Comment by BanzaiMan** [comment]
Could you try haveged, then?

**Comment by BanzaiMan** [comment]
Sorry. Didn't mean to close.

**Comment by overheadhunter** [comment]
> Could you try haveged, then?

How? I don't think one I tell the JVM to use a specific source, or can I?

**Comment by BanzaiMan** [comment]
Here is HAVEGED documentation: http://www.issihosts.com/haveged/

Also, [the man page](http://manpages.ubuntu.com/manpages/precise/man8/haveged.8.html):

> Haveged is a daemon that uses HAVEGE to maintain a 1M  pool  of  random
bytes  used  to  fill /dev/random whenever the supply of random bits in
dev/random falls below the low water mark of the device.

I've never used it, but it appears to me that you can just keep the daemon running and use `/dev/random`.

**Comment by overheadhunter** [comment]
But I guess I need sudo for installation in the `before_script` phase, so this isn't an option for the container-based infrastructure..?

**Comment by overheadhunter** [comment]
@BanzaiMan Using haveged works! Thanks! I'll close this issue, as it was primarily about the GCE builds.

I added:
```
before_script: sudo apt-get install haveged && sudo service haveged start
```
(not sure if the latter command is needed, though)
