### ISSUE TITLE
bundle install failing

### ISSUE THREAD

**Issue by trusche** [travis-ci/travis-ci#5239]
Hiya! With ruby-1.9.3, `bundle install` is failing with this error:

```
Using bundler 1.7.6

NoMethodError: undefined method `spec' for nil:NilClass
```

Details here: https://travis-ci.org/trusche/httplog/jobs/95253337

Seems like this old issue: https://github.com/bundler/bundler/pull/3559

Maybe a bundler update could fix this?

Thanks for a great tool!

**Comment by RochesterinNYC** [comment]
Not sure if they're planning on updating bundler anytime soon. #3531

**Comment by trusche** [comment]
Thanks @RochesterinNYC

**Comment by alexmamonchik** [comment]
+1. Any solutions?

**Comment by alexmamonchik** [comment]
helped in `.travis.yml`
```
before_install:
  - gem install bundler
```

**Comment by anthonator** [comment]
:+1:  for @alexmamonchik's solution!
