### ISSUE TITLE
smaller /tmp space affects pmem/nvml tests

### ISSUE THREAD

**Issue by marcinslusarz** [travis-ci/travis-ci#5241]
https://travis-ci.org/ldorau/nvml/jobs/95310781

The test which fails creates 2 1GB files in /tmp.

If it's permanent change please say so - we'll scale it down or disable this test on Travis.

**Comment by meatballhat** [comment]
@marcinslusarz  Thanks for the report!  The change made last week on GCE was to ensure `/tmp` is `tmpfs`, which was based on my flawed understanding of the legacy Linux setup & requests from folks who wanted `/tmp` to be `tmpfs`.  What I'm seeing now is that both the legacy Linux setup and GCE setup have `/var/ramfs` of 768MB, but `/tmp` is part of the root fs.  If you're able to control *where* the files are being created, I recommend `/var/tmp` or `$HOME/tmp`.  If you absolutely need `/tmp` to be bigger than 1GB, I can see about either backing out the `tmpfs` change or specifying a different size.

**Comment by marcinslusarz** [comment]
@meatballhat Thanks for the quick response.

@ldorau made the change to move those files to /var/tmp, but it seems his builds are run again on legacy infrastructure. Is there any way to enable new infra manually?

**Comment by meatballhat** [comment]
I've backed out the 1G of `tmpfs` on `/tmp` in favor of the existing 768M of `tmpfs` on `/var/ramfs`, meaning `/tmp` should once again be part of the root partition.  As for routing to the new infrastructure, this can be ensured by including `group: edge` :smiley_cat:
