### ISSUE TITLE
new Legacy Precise platform doesn't seem to support hhvm

### ISSUE THREAD

**Issue by terrafrost** [travis-ci/travis-ci#5243]
See https://travis-ci.org/phpseclib/phpseclib/jobs/95287426

It works with https://travis-ci.org/terrafrost/travisci-test/builds/95341273 but I'm guessing that's not using the new Legacy Precise platform..

**Comment by mnapoli** [comment]
Same here it seems: https://travis-ci.org/PHP-DI/PHP-DI/jobs/95319109

**Comment by BanzaiMan** [comment]
@meatballhat The HHVM package source will have to be added: http://docs.hhvm.com/hhvm/installation/linux#ubuntu-14.04-trusty

**Comment by meatballhat** [comment]
The HHVM source & package have been re-enabled (https://github.com/travis-ci/packer-templates/pull/130), and should be available on `group: edge` within the next hour.  Promotion to `group: stable` (the default) will likely happen in the next 18 hours.

**Comment by syronTill** [comment]
829638

**Comment by syronTill** [comment]
Issue

**Comment by BanzaiMan** [comment]
Confirmed fixed.

**Comment by syronTill** [comment]
https://github.com/travis-ci/travis-ci/issues/5243
