### ISSUE TITLE
Testing concurrency issues with OpenMP

### ISSUE THREAD

**Issue by stevenvdb** [travis-ci/travis-ci#5245]
I would like to test whether my project was parallelized correctly (with OpenMP). My idea would be to run the unit tests first with the environment variable OMP_NUM_THREADS=1, then run them using OMP_NUM_THREADS=4. Of course we would like the outcome to be the same.

I created a minimal project containing race conditions here: https://github.com/stevenvdb/travisci_openmp
On my local machine, the program gives the wrong result when OMP_NUM_THREADS=4, indicating race conditions. On the Travis server I get the correct result in both cases: https://travis-ci.org/stevenvdb/travisci_openmp

I think this is related to the fact that only 1.5 virtual cores are used by Travis (https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-build-on-one-VM). I wonder if there is a solution to truly get concurrency on the Travis server in order to detect parallelization errors in the code.

**Comment by wence-** [comment]
FWIW, this is an absolutely terrible way to attempt to catch races in your code.

**Comment by BanzaiMan** [comment]
Thanks for taking time to open the issue.

We offer build environment in one size (for each cloud). If OpenMP cannot be fooled into thinking that the build environment has more resources, I am not sure how we can help you out here.

**Comment by stevenvdb** [comment]
@wence- Could you please explain some better ways to catch race conditions? Preferably methods that can be used on Travis CI.

**Comment by wence-** [comment]
Your best bet is using a tool such as `helgrind` or `drd`, which come as part of the valgrind suite.  However, the last time I used them, they threw up some number of positives in my code (however, it was a very large code base).  There's no magic bullet here as far as I am aware.  But running code in parallel that may have races in it and comparing to a serialised result is not guaranteed to catch bugs: as you've observed on travis, depending on how the OS schedules the threads, racy code /may/ appear race free.

I believe modern versions of clang come with a thread sanitiser that you can use to instrument your code (if you compile with clang).  See http://clang.llvm.org/docs/ThreadSanitizer.html.

**Comment by BanzaiMan** [comment]
I think this is beyond scope of our support. I'm closing this.
