### ISSUE TITLE
travis compile failed with "data.slug must not be empty"

### ISSUE THREAD

**Issue by gfiedler** [travis-ci/travis-ci#5247]
I installed travis-build as described in "Use as addon for CLI" and run "travis compile" on a simple .travis.yml file which contains only a single line "language: java".

I got the following error:

$ travis compile
'os' key is unsupported in local build script compilation. Setting to default, 'linux'.
data.slug must not be empty
for a full error report, run travis report

**Comment by BanzaiMan** [comment]
Looks like we failed to detect the repository. I think https://github.com/travis-ci/travis-build/pull/564 might solve this problem.

**Comment by BanzaiMan** [comment]
The PR has been merged. Please try again.
