### ISSUE TITLE
Builds don't cancel

### ISSUE THREAD

**Issue by RMcGirr83** [travis-ci/travis-ci#5248]
https://travis-ci.org/RMcGirr83/phpBB-3.1-searchusertopics

This build has been running all day long and clicking on the cancel button doesn't seem to do anything.  Get a response that build was successfully cancelled but it doesn't seem to be.

**Comment by BanzaiMan** [comment]
Sorry to hear about the problem. Does this issue persist?

**Comment by RMcGirr83** [comment]
Seems to now be working fine so closing
