### ISSUE TITLE
builds that depend on opencl (fglrx) will fail with GCE platform

### ISSUE THREAD

**Issue by TimmyLiu** [travis-ci/travis-ci#5249]
A few projects rely on installing fglrx to link with libopencl.so would fail with GCE platform:

clBLAS: https://travis-ci.org/clMathLibraries/clBLAS/jobs/95440841
boostorg/compute: https://travis-ci.org/boostorg/compute/jobs/95215890

we used to be able to do sudo apt-get install fglrx but now it would complain " Package 'fglrx' has no installation candidate"

**Comment by BanzaiMan** [comment]
Seems like a duplicate of #5221.

**Comment by TimmyLiu** [comment]
Hi,
Do you rather me close this issue and maybe mention it in #5221 to track it?

**Comment by BanzaiMan** [comment]
@TimmyLiu Please rerun your build, and see if a recent image fixes your issue. In the meantime, I'll close this issue. If the issue persists, please follow up on #5221.
