### ISSUE TITLE
Upgrading system to Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by kshitij10496** [travis-ci/travis-ci#5251]
Are we looking to upgrade the current system from Ubuntu 12.04 LTS to Ubuntu 14.04 LTS ?

**Comment by roidrage** [comment]
We already did, though 12.04 is still the default: https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta

**Comment by kshitij10496** [comment]
@roidrage Thats cool !
But why don't we make 14.04 as the default system ?

**Comment by roidrage** [comment]
We'll have an internal chat about it, and see when we could make that switch. Changing the default isn't something to take lightly or that we can do within a week, as it could break a lot of builds.

**Comment by solarce** [comment]
Our path to being able to support Trusty on our container based builds and then phase it into the default build environment is definitely going to take us well in 2016. 

Our recommendation at this time would be to keep an eye on http://docs.travis-ci.com/user/trusty-ci-environment/ and/or follow us on https://twitter.com/travisci for news of when we expand our Trusty support.

Thank you for your questions.
