### ISSUE TITLE
apt-get says "Unable to locate package sshpass"

### ISSUE THREAD

**Issue by aschempp** [travis-ci/travis-ci#5252]
On the old infrastructure I used `sshpass` to connect to a remote server. `sshpass` was installed using `sudo apt-get install sshpass`, which seems to no longer work.

See https://travis-ci.org/contao/docs/builds/95556803 for the build log.

PS: I know about the bad practice of `sshpass`, I just could not come up with anything better as I can't install a certificate on the server …

**Comment by meatballhat** [comment]
@aschempp The latest images should ship with the cached apt lists in place, meaning you won't necessarily have to `apt-get update` first.  Is this still happening for you?

**Comment by BanzaiMan** [comment]
@aschempp Please follow up on #5221.

**Comment by aschempp** [comment]
Re-running the job did not fix it, but adding `sudo apt-get update` does :+1:
