### ISSUE TITLE
HHVM build fail

### ISSUE THREAD

**Issue by mnapoli** [travis-ci/travis-ci#5253]
Please see this build: https://travis-ci.org/PHP-DI/PHP-DI/jobs/95319109

> Updating HHVM

> E: Unable to locate package hhvm

It worked correctly until now that it's running on the "new platform for Legacy Precise builds".

**Comment by meatballhat** [comment]
@mnapoli Thanks for the report!  The cached APT sources on the legacy platform have refs to a packaged named `hhvm` that are no longer available on the freshly-baked 12.04 images.  Luckly, setting a version of `7` is known to work.  Are you able to switch to declaring `7` as the version?

**Comment by mnapoli** [comment]
I'm not sure I understand what you are suggesting. Version `7` of "PHP" is not the same thing as HHVM.

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate of #5243.
