### ISSUE TITLE
travis-ci.org container based builds are unable to connect to joomla.org 

### ISSUE THREAD

**Issue by solarce** [travis-ci/travis-ci#5255]
Initially reported via https://twitter.com/stevenrombauts/status/674171714532728833.

I've confirmed the issue only exists on the travis-ci.org container based builds and works on travis-ci.com container based builds and other build platforms on both sites.

https://travis-ci.org/solarce/container-tests/builds/95703496 is a build demonstrating the failure:

```
nc: connect to joomla.org port 80 (tcp) failed: Connection timed out
The command "nc -z -v joomla.org 80" exited with 1.
30.05s$ curl -v -m 30 http://joomla.org
* About to connect() to joomla.org port 80 (#0)
*   Trying 72.29.124.146... Timeout
* connect() timed out!
* Closing connection #0
curl: (28) connect() timed out!
The command "curl -v -m 30 http://joomla.org" exited with 28.
```

I am going to reach out to the joomla.org folks to help troubleshoot further

**Comment by solarce** [comment]
I've posted on what I believe is the correct Joomla.org forum, http://forum.joomla.org/viewtopic.php?f=7&t=901984, and I will see what response I get

**Comment by mbabker** [comment]
I ran [a job](https://travis-ci.org/mbabker/travis-tests/builds/95727967) pinging different subdomains on different servers using both ports 80 and 443 and the way that build looks the failure is isolated specifically to the server for the root domain.  I've got a ticket in with Joomla's hosting partner to get things looked into.

**Comment by solarce** [comment]
@mbabker thanks for the quick response. Let me know how else I can help with any troubleshooting.

**Comment by mbabker** [comment]
Per hosting:

> it looks like some IP addresses under Amazon's EC2 ranges had been blocked in your server's firewall

They removed that block and my failing job now passes on the `joomla.org` domain.

**Comment by stevenrombauts** [comment]
I can confirm issue is fixed on our end too. Thanks a lot for your help, @solarce and @mbabker!

**Comment by BanzaiMan** [comment]
Thanks for the update.
