### ISSUE TITLE
Current PHP support status (including PHP 7.0.0) on Travis CI

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5256]
This issue supersedes #5207.

This issue describes how we provide support for PHP, and what issues we are facing.

# How PHP binary is created

Currently, we are using https://github.com/travis-ci/php-src-builder to create PHP archives to be used by build image provisioning process, as well as the on-demand installations. This process uses https://github.com/php-build/php-build to compile binaries.

# Removal of pear and pyrus from php-build

Recently, https://github.com/php-build/php-build/pull/347 removed support for pear and pyrus. I am not privy to the reasoning behind it, and I plan to reach out to the php-build team to understand it. The impact of this is that we are currently unable to provide extensions support we [have documented](https://docs.travis-ci.com/user/languages/php#PHP-extensions) for any archive we create. (This includes many newer archives, including nightlies, as well 7.0.0, which is yet to be made available.)

# New archives do not have all the extensions mentioned in the documentation

As a result, new archives do not have all the extensions mentioned.

**Comment by BanzaiMan** [comment]
I think I managed to restore extension building functionality with pear and PHP 5.5.30. https://travis-ci.org/BanzaiMan/travis_production_test/builds/95729908#L255

If other people could also test this functionality, it would be most appreciated.

**Comment by BanzaiMan** [comment]
# Note on Pyrus

I note here that Pyrus does not appear to be in active development any longer. The last commit on https://github.com/pyrus/Pyrus is 1.5 years ago, the last release was more than 3 years ago, and the URL http://pear2.php.net/PEAR2_Pyrus no longer works.

It might be safe to assume that pyrus is no longer a valid means of installing extensions.

**Comment by tedivm** [comment]
I wasn't having issues with pear < 7 yesterday. I just triggered some jobs to work.

For php 7 you should be able to use the pecl version that ships with ubuntu- it doesn't have major changes for php7, and used the php dev tools installed with php rather than trying to ship it's own anyways.

**Comment by BanzaiMan** [comment]
@tedivm Using Ubuntu packages is not an option at this time.

**Comment by tedivm** [comment]
The php 5.5 tests that were working for me yesterday no longer seem to be.

**Comment by BanzaiMan** [comment]
@tedivm Could you show the failing and passing build URLs, please?

**Comment by tedivm** [comment]
PECL worked here - https://travis-ci.org/tedious/Stash/jobs/95518475
PECL did not work here - https://travis-ci.org/tedious/Stash/jobs/95515702

**Comment by BanzaiMan** [comment]
@tedivm Did you paste the right URLs? They both passed.

**Comment by tedivm** [comment]
My test suite checks to see that the extensions are installed and skips tests that are unavailable. If you look at the "php_setup" script results in those examples you'll see that pecl worked in the first one and failed in the second, resulting in the second run I linked skipping a chunk of tests.

Everything passed, but code coverage dropped as a result of the tests that I can no longer run.

**Comment by BanzaiMan** [comment]
@tedivm I'm sorry to say, but I lack the context and understanding of your test suite's nuances. It is not very obvious to me where to look.

Where in the log does it show that extensions are missing? And what extensions?

**Comment by shouze** [comment]
@BanzaiMan ok so as you bring composer, would you bring pickle wich indeed is a good defacto replacement?

**Comment by BanzaiMan** [comment]
@shouze Quite frankly, I was not aware such a thing existed! It is an interesting proposition, and deserves a separate issue to discuss it. Do you mind opening a new issue?

**Comment by shouze** [comment]
@BanzaiMan yes issue opened https://github.com/travis-ci/travis-ci/issues/5266

**Comment by tedivm** [comment]
Hmm, seems it *is* working for me. I may have been facing a caching issue (ie, I was looking at the wrong results).

Anyways, why not just-

```
wget https://pear.php.net/go-pear.phar
php go-pear.phar
```

As long as you're using HTTPS for wget this should be pretty secure.

**Comment by shouze** [comment]
@tedivm try if you want:
```
php go-pear.phar
```

You will see it's an interactive installer... so to automate it you shloud need some tricks like installing `expect` for example... BTW pear is pretty/almost a dead project. Pyrus was its successor but it's dead too... almos 1.5 year without any progress.

So... pickle ATM is the best candidate to replace all this stuff. It's built on the shoulders of composer so it's clearly the right direction to take.

**Comment by BanzaiMan** [comment]
PHP 7 should be working reasonably now. I'm closing this.

**Comment by oparoz** [comment]
Care to explain? Is pecl back? If not, has documentation been added on how to use its replacement?

**Comment by BanzaiMan** [comment]
@oparoz PECL issue is here: https://github.com/travis-ci/travis-ci/issues/5303

**Comment by oparoz** [comment]
Thanks!
