### ISSUE TITLE
Can't view badges

### ISSUE THREAD

**Issue by A-Helberg** [travis-ci/travis-ci#5257]
When viewing travis build status badges I get an error.
![screen shot 2015-12-09 at 10 37 52 am](https://cloud.githubusercontent.com/assets/4280509/11680546/a0b6493c-9e61-11e5-8343-cf5d6b12697a.png)

The url that gets generated for the image, when visited, says access denied.
If I send the url for the image to someone else they also get access denied.
If someone else views the travis page, and sends me their link to the image, I can see it.

So this isn't an issue with the repo itself, or the travis config, but with the access tokens that get generated for my account.

**Comment by joshk** [comment]
Hi @A-Helberg 

I'm sorry for the issue you experienced. I have fixed the problem with how we generate the token, and this should be working for you now.

Have a great day

Josh

**Comment by napon** [comment]
This seems to be happening to my account as well and I can't seem to find any help online except for this ticket. Could you look into this for me?

**Comment by uuf6429** [comment]
Same here..
