### ISSUE TITLE
OS X and linux-container builds?

### ISSUE THREAD

**Issue by zbeekman** [travis-ci/travis-ci#5260]
Hi I was wondering what the correct way is---if it is even possible---to trigger a linux container based build and OS X build. [Here](https://github.com/zbeekman/opencoarrays/commit/eb99e97) is my attempt, and I am getting a [missing config](https://travis-ci.org/zbeekman/opencoarrays/requests) rather than the build starting...

**Comment by Joshua-Anderson** [comment]
You can use `matrix.include` to add different builds. One example is [travis-rubies](https://github.com/travis-ci/travis-rubies/blob/build/.travis.yml).

**Comment by zbeekman** [comment]
amazing, thank you kind sir

**Comment by BanzaiMan** [comment]
Can this be closed?

**Comment by zbeekman** [comment]
sure, thanks.

**Comment by zbeekman** [comment]
I'm still getting `missing config` when I look at the [requests](https://travis-ci.org/zbeekman/opencoarrays/requests) and I don't understand why.

**Comment by BanzaiMan** [comment]
@zbeekman Your `.travis.yml` (https://github.com/zbeekman/opencoarrays/blob/b4fe6c644ce5d6f5e7b731c670d65a3949226d84/.travis.yml) is invalid.

**Comment by zbeekman** [comment]
ah, sorry. My pre-commit hook checking my .travis.yml is not working, because my ruby environment got messed up

**Comment by zbeekman** [comment]
ok, I think I have resolved my issue with homebrew and ruby, thanks
