### ISSUE TITLE
Requesting Precise, getting Trusty

### ISSUE THREAD

**Issue by fniephaus** [travis-ci/travis-ci#5262]
I have explicitly defined that a build should use Ubuntu Precise (via `dist: precise`) and the log file says `Build dist: precise`.

However, I am getting an Ubuntu Trusty image: https://travis-ci.org/hpi-swa/smalltalkCI/jobs/95945713

Am I doing something wrong or is this a bug?

/cc @meatballhat @emdantrim @solarce

**Comment by gracjan** [comment]
I'm getting opposite: `dist: trusty` gives me `precise`, but only on docker workers.

```
Using worker: worker-linux-docker-30385cc9.prod.travis-ci.org:travis-linux-7
system_info
Build system information
Build language: emacs-lisp
Build group: stable
Build dist: trusty
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
```

Link: https://travis-ci.org/haskell/haskell-mode/jobs/96380771

**Comment by BanzaiMan** [comment]
@gracjan There is no Trusty image on containers.

**Comment by fniephaus** [comment]
According to [this](https://gist.github.com/meatballhat/d0c8aab9e3bd8a8bcacd), the [mentioned build](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/95945713) should have even run on Blue Box and not on GCE.
That's odd.

**Comment by quicksketch** [comment]
> According to this, the mentioned build should have even run on Blue Box and not on GCE.
That's odd.

I'm seeing this as well. Regardless of requesting
```
sudo: required
dist: precise
group: stable
```

Which supposedly is Blue Box, I'm getting GCE instead:
```
Worker information
hostname: travis-worker-gce-org-prod-1:054bf3f7-7fb7-4674-9e8b-ea3854df8278
version: v2.0.0-24-g8f5b41a https://github.com/travis-ci/worker/tree/8f5b41a07b602643e7ee8cf307787f9ca8f4b00b
instance: testing-gce-26774b29-3b03-42d6-9f73-3be0536a4930:travis-ci-mega-trusty-1445287562
startup: 1m3.860175465s
```

**Comment by solarce** [comment]
My apologies, but the gist got outdated, we've updated it.

The keys to use are:
```
sudo: required
dist: precise
group: legacy
```

Additionally, `dist: trusty` will have no effect when paired with `sudo: false`, for the time being.

**Comment by quicksketch** [comment]
Thanks @solarce! Confirmed that `group: legacy` does the trick. We're now back in business running on Blue Box.

We'll switch over the the Trusty images once they [start including PHP versions](https://docs.travis-ci.com/user/trusty-ci-environment/#PHP). For now, the GCE Precise servers [appear to have issues](https://github.com/backdrop/backdrop-issues/issues/1422) for our project. Thanks!

**Comment by fniephaus** [comment]
I'd like to reopen this issue since it hasn't been solved:

```
Build group: stable
Build dist: precise
...
Codename:	trusty
```
https://travis-ci.org/hpi-swa/smalltalkCI/jobs/97670866#L16

**Comment by fniephaus** [comment]
I was able to resolve this by specifying all builds within `matrix.include` only.
Looks like the scheduler app was confused by my `.travis.yml`.

**Comment by BanzaiMan** [comment]
I'm reopening this. As @fniephaus points out, there is still an issue to be resolved. More precisely (see what I did there?), this is a problem with Smalltalk builds.

This

```yaml
language: python

matrix:
  include:
    - python: 3.5
      os: linux
      sudo: required
      env: BUILDERCI=true
```
gets a Precise image, while

```yaml
language: smalltalk

matrix:
  include:
    - smalltalk: Squeak-4.4
      os: linux
      sudo: required
      env: BUILDERCI=true
```

does not.

**Comment by fniephaus** [comment]
Thanks, @BanzaiMan.
Haven't had the time to look at the scheduling code myself. I don't even know if the code is open source. But when I have, I am happy to help.

**Comment by BanzaiMan** [comment]
I'm going to close this in favor of https://github.com/travis-ci/travis-ci/issues/5973.
