### ISSUE TITLE
GitHub Releases Uploading not working

### ISSUE THREAD

**Issue by Bonczidai** [travis-ci/travis-ci#5263]
I am trying to generate a secure GitHub token for deployment, but it gives me the following error:

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
```

The repository belongs to an organization, I have `owner` rights. I took the following steps:

- setup a machine with Travis client
- generate access token on GitHub with `public_repo` scope
- login with my GitHub credentials in Travis client
- run the following cmd:
```
travis encrypt 'GIT_NAME="<github_user>" GIT_EMAIL=<mail> GH_TOKEN=<token_with_public_rep_scope>'
```
which outputs ~ : 
```
secure: "dALKUpIxCRXds49YQZMVQw2EwmXy8QG3pN1SNETUxJ/0SHRHIf/9GZoALps3AxLHhfAMSuT6UsXg3bUPcadw+hGfHhNLzamzgkKf1A0VdQB3Fimn3zGKyfbTbiLPgzjio81/XbXgNXjfpXT8w7Pdw0J4jPCToxFmJ1qA78Dls2w="
```
.. copied this into `.travis.yml` file

Any suggestion what could go wrong?

[.travis.yml](https://github.com/CloudSlang/cloud-slang/blob/c0db403ee472c7d7e65eadc5efc2fd105f21b31e/.travis.yml)
[build](https://travis-ci.org/CloudSlang/cloud-slang/jobs/95806487)

**Comment by Joshua-Anderson** [comment]
All you need to add is the token, since it already has associated user info.


So just `travis encrypt <oauth token>`

**Comment by BanzaiMan** [comment]
https://travis-ci.org/CloudSlang/cloud-slang/jobs/96001069 shows successful deployment.

**Comment by Bonczidai** [comment]
thanks @Joshua-Anderson - with that cmd it works indeed
