### ISSUE TITLE
no build

### ISSUE THREAD

**Issue by yeziahehe** [travis-ci/travis-ci#5264]
I use [hexo](https://github.com/hexojs/hexo) with travis-ci, but when i push just get request no build.
message is config missing, why?
<img width="904" alt="2015-12-10 2 44 59" src="https://cloud.githubusercontent.com/assets/8090437/11710483/8a733ff0-9f5a-11e5-8c8f-c4ab9cb20b90.png">
<img width="955" alt="2015-12-10 2 57 12" src="https://cloud.githubusercontent.com/assets/8090437/11710484/8ab289a8-9f5a-11e5-8aae-9bcb09cb78d0.png">
<img width="639" alt="2015-12-10 3 08 20" src="https://cloud.githubusercontent.com/assets/8090437/11710513/b419f0f6-9f5a-11e5-96c7-f0d6dae49020.png">

**Comment by Xuanwo** [comment]
ref https://github.com/hexojs/hexo/issues/1640, not relate to travis-ci, please close this issue.

**Comment by Xuanwo** [comment]
comment used in yml is `#` instead of `/`
