### ISSUE TITLE
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

### ISSUE THREAD

**Issue by Broich** [travis-ci/travis-ci#5265]
Hi there,

I'm having trouble getting our tests to run to the end. 

After executing the first couple of tests travis hangs and after 10 more minutes I get ```No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.``` in the log.

I do not perform any long-running tasks so I would assume there is no need to add ```travis_wait``` to the configuration. Local test run finishes in a few seconds.

Is there anything I can do about it or tweak my yaml file:

```
osx_image: xcode7.1
language: objective-c

before_install:
- xcrun simctl list

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

xcode_workspace: Kitchen Stories.xcworkspace

script:
- set -o pipefail
- xcodebuild -workspace Kitchen\ Stories.xcworkspace/ -scheme 'Kitchen Stories' -sdk iphonesimulator -destination "OS=9.1,name=iPhone 6s" clean build | xcpretty -c || true 
- xcodebuild -workspace Kitchen\ Stories.xcworkspace/ -scheme 'Kitchen Stories' -sdk iphonesimulator -destination "OS=9.1,name=iPhone 6s" test | xcpretty -c 

branches:
  only:
    - travis
```

Also the point where Travis hangs is completely arbitrary. I can't reproduce it with one particular case.

Thanks for your support!

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows this problem?

**Comment by Broich** [comment]
Hey, thanks for your reply. Since it is a private repository I guess I'll have to send it with email?

**Comment by BanzaiMan** [comment]
Please do. I am closing this now.
