### ISSUE TITLE
Preinstalled phpunit is broken

### ISSUE THREAD

**Issue by tmatsuo** [travis-ci/travis-ci#5267]
It started failing today (yesterday similar build succeeded).
https://travis-ci.org/satooshi/php-coveralls/jobs/96038289#L235

```
$ phpunit
/home/travis/.phpenv/versions/7.0/bin/phpunit: line 1: html: No such file or directory
/home/travis/.phpenv/versions/7.0/bin/phpunit: phpunit: line 2: syntax error near unexpected token `<'
'
```

**Comment by keradus** [comment]
Same here https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/95780602#L158 :(

**Comment by tmatsuo** [comment]
From the error message, I assume that's an HTML page for redirect or 404.

**Comment by tmatsuo** [comment]
https://travis-ci.org/satooshi/php-coveralls/builds/96053218#L144

**Comment by oschwald** [comment]
I also experienced this today too. I switched to installing phpunit with composer.

**Comment by tmatsuo** [comment]
Great to see the fix is coming.

BTW, is it possible to have a test case for this?

**Comment by BanzaiMan** [comment]
@tmatsuo I've tweaked the script so that when phpunit.phar download fails, the build will also fail. This prevents the erroneous archive to be uploaded. There are ways to verify the archives, but the build script doesn't have such functionality just yet.

**Comment by BanzaiMan** [comment]
The new 7.0.0 archive is uploaded with phpunit downloaded from the correct source. Could you re-run the failing test(s) and see if the archive is good?

Thank you.

**Comment by nWidart** [comment]
Hello,

I also had this issue, and build is back to green now. :smile:

**Comment by tmatsuo** [comment]
Thanks! The build is green now.

**Comment by BanzaiMan** [comment]
Thanks for reporting this issue. We apologize for the interruption.

**Comment by czettnersandor** [comment]
This has happened again:
https://travis-ci.org/czettnersandor/gpslogger/jobs/103703260

**Comment by BanzaiMan** [comment]
@czettnersandor thanks for the report. looks like PHPUnit maintainers decided to move the file download URL. It'll be up in 30 minutes or so.
