### ISSUE TITLE
Python 3.5 - error while loading shared libraries: libpython3.5m.so.1.0

### ISSUE THREAD

**Issue by dstufft** [travis-ci/travis-ci#5268]
Today I noticed that when attempting to use Python 3.5.0 any attempt to invoke Python (even the ``python --version`` at the start) is failing with this error message:

```console
$ python --version
python: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
```

I don't believe that anything I did could have caused this, so I re-ran a previously successful job and it is also now failing.

An example of one of the failing jobs - https://travis-ci.org/pypa/warehouse/jobs/96033825

**Comment by BanzaiMan** [comment]
Looks like the archives for `3.5.0` and `3.5` have somehow diverged. `3.5` works right now, but `3.5.0` does not.

**Comment by BanzaiMan** [comment]
Confirmed fix: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/96150901#L90

**Comment by dagheyman** [comment]
I'm still seeing this issue. [This build](https://travis-ci.org/Yubico/yubikey-manager-qt/jobs/179759983) succeeded before, now fails with 
```(libpython3.5m.so.1.0: cannot open shared object file: No such file or directory)```. 

I have `language: cpp` though, does that matter ?

**Comment by BanzaiMan** [comment]
@dagheyman Do you have a build log of a passing build?

**Comment by dagheyman** [comment]
@BanzaiMan Well, the [commit before](https://travis-ci.org/Yubico/yubikey-manager-qt/jobs/179734282) is still green if thats what you mean?

**Comment by BanzaiMan** [comment]
@dagheyman Yes. So, in your case, I believe that the Dec 5 image update (https://travis-ci.org/Yubico/yubikey-manager-qt/jobs/179759983#L14) caused the failure. I am guessing that somehow `python3-config` is not valid, and giving `configure` (and `make`) bad configuration flags somehow.

I think this is a separate issue from the one we discussed above. Please open a new one.

**Comment by redstoneleo** [comment]
The simplest case cammand here http://stackoverflow.com/a/26657830/1485853 helped me！
