### ISSUE TITLE
gzip/tar started failing

### ISSUE THREAD

**Issue by sapek** [travis-ci/travis-ci#5271]
Today my build started to fail extracting a .gz file.
~~~
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
~~~

https://travis-ci.org/Microsoft/bond/jobs/96154054

Tested locally and the file looks fine.

**Comment by BanzaiMan** [comment]
The archive might be corrupt. Please check the archive's content is valid.

https://travis-ci.org/Microsoft/bond/jobs/96154054#L1543

**Comment by sapek** [comment]
I did download the [file](https://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz) locally and verified that it can be extracted.

**Comment by sapek** [comment]
OK, it looks like it was an intermittent failure. Works fine now.
