### ISSUE TITLE
Cannot run: `rvm osx-ssl-certs update all` at osx_image: xcode7.2

### ISSUE THREAD

**Issue by marciok** [travis-ci/travis-ci#5274]
Hi,
I'm trying to run `rvm osx-ssl-certs update all` using the image xcode7.2, and I get the error:
```
Updating certificates for /usr/lib/ssl/cert.pem: Updating certificates in '/usr/lib/ssl/cert.pem'.
mkdir: /usr/lib/ssl: Operation not permitted
mkdir -p "/usr/lib/ssl" failed, retrying with sudo
mkdir: /usr/lib/ssl: Operation not permitted
Can not create directory '/usr/lib/ssl' for certificates.
```` 
And I need this command to fix the problem:

``` 
Users/travis/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
 ```
I've tried sudo; rvmsudo but none of them worked. I'm out of solutions :(

**Comment by BanzaiMan** [comment]
On [containers](https://docs.travis-ci.com/user/workers/container-based-infrastructure), you cannot run `sudo`. If you need it, please add `sudo: required` to your `.travis.yml`.

**Comment by BanzaiMan** [comment]
Ooops. This is for Xcode 7.2 image. I think it is running on El Capitan, which does not let you modify certain protected directories such as `/usr`.

**Comment by marciok** [comment]
I ended up reinstalling ruby `rvm reinstall 2.0.0-p643 --disable-binary` 
That fixed the RVM + OpenSSL  issue.

**Comment by BanzaiMan** [comment]
Can this be closed, then?

**Comment by marciok** [comment]
Done :)

**Comment by fastred** [comment]
@BanzaiMan are there any plans to fix this issue on the system level, so that we won't have to reinstall ruby on each build?

**Comment by BanzaiMan** [comment]
I suspect I am missing the big picture. Why do you want to do this?

Modifying `/usr/lib` is not allowed on El Capitan. Coming up with a different solution to the problem is probably a better approach.

**Comment by fastred** [comment]
@BanzaiMan I don't need to run `rvm osx-ssl-certs update all` per se. It's just that one of [fastlane's](https://github.com/fastlane/fastlane) tools ([sigh](https://github.com/fastlane/sigh)) fails on `xcode7.2` osx_image with:
```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```
when it tries to connect to a server using https connection. Exactly the same setup works fine on `xcode7.1`.

I didn't debug this comprehensively because of the lack of time :disappointed:. I saw [some tickets](https://github.com/fastlane/fastlane/search?utf8=✓&q=SSL_connect&type=Issues) mentioning this issue but no other solution (like updating openssl) worked for me. Reinstalling ruby was the only thing that seemed to fix this issue.

**Comment by marciok** [comment]
@fastred I had the same problem.
I believe the main issue is that RVM provides ruby versions with binaries so we don't have to compile. These binaries are linked with OpenSSL and the certificates are outdated, so you have to update them or reinstall without the binaries. 

If Travis CI could provide an image with rubies, without these compiled binaries would be great. Could use rbenv for instance.

This is just my naive suggestion.

**Comment by victor** [comment]
Yes, please update the Xcode 7.2 image so we don't have to do this each time. Updating the fastlane gem and all Cocoa pods on every build already takes a lot of time.

**Comment by ChristopherDrum** [comment]
@marciok I'm confused by your solution. Did `rvm reinstall 2.0.0-p643 --disable-binary` alone fix the issue, or are you saying that after reinstalling ruby you were then able to successfully run `rvm osx-ssl-certs update all`?

**Comment by marciok** [comment]
@ChristopherDrum Sorry if I wasn't clear, just `rvm reinstall 2.0.0-p643 --disable-binary` did the job

**Comment by ChristopherDrum** [comment]
@marciok No worries, and thanks for the workaround. Just confirmed it worked for me as well.

**Comment by Sega-Zero** [comment]
This workaround didn't work for me, should I place it in before_install of before_script?
Also, an image rebuild is much better than wasting more time on packages rebuild.

**Comment by marciok** [comment]
@Sega-Zero I recommend to add on before install --that's usually where I download my project dependencies. 
Yes having to reinstall a ruby every time sucks, would be great if could Travis provide an image without this issue.

**Comment by ChristopherDrum** [comment]
@Sega-Zero before install is where I ran it with success
