### ISSUE TITLE
nvm failing to install 0.10

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [travis-ci/travis-ci#5275]
So, all of my build-matrix entries on `0.10` are failing, without even spitting out any error; about halfway into nvm's ‘download’ phase, output stops appearing, and the build simply gets marked as ‘errored’ with no other information:

https://travis-ci.org/ELLIOTTCABLE/Paws.js/jobs/96397645 ([.travis.yml](https://github.com/ELLIOTTCABLE/Paws.js/blob/82bae56e/.travis.yml))

(I'm using the sudo-less architecture; and the beta apt-sources / `gcc` 4.8 to try and compile native dependencies for Node v4.0+.)

**Comment by BanzaiMan** [comment]
Could you try restarting this job? The log appears incomplete. (And the failure has nothing to do with `nvm` failing to install 0.10.

**Comment by ELLIOTTCABLE** [comment]
How can you tell it has nothing to do with nvm?

(I restarted it before posting this, and watched: if definitely stops doing anything in the middle of nvm install, immediately becoming ‘failed’)

I'll restart one more time when I get back upstairs, but,

**Comment by ELLIOTTCABLE** [comment]
Ah, it *was* a later part of the build. I have no idea why it stopped displaying output immediately before failing, though; should I submit that as a separate issue?
