### ISSUE TITLE
[macos request] Provide Qt package in OS X images

### ISSUE THREAD

**Issue by jcelerier** [travis-ci/travis-ci#5278]
Hello,

In the next OS X image upgrade, would it be possible to provide the package `qt5` from homebrew ? It takes a lot of time to install at each build and I suppose that it is mildly common for cross-platforms C++ software : https://github.com/search?utf8=%E2%9C%93&q=%22brew+install%22+%22qt5%22&type=Code&ref=searchresults

Also, `cmake` and `ninja` would be must-haves :p but they take a lot less time to install so it's not as critical.

Best regards
Jean-Michaël

**Comment by luzpaz** [comment]
:+1: for qt5 and cmake

**Comment by jcelerier** [comment]
In the mean time I just compressed the packages on my computer, gzipped + uploaded them to dropbox and I unpack them at the beginning of each build in /usr/local/Cellar. I gained 10 minutes at each odx build.

**Comment by jcelerier** [comment]
It could be nice if it was in xcode7.3

**Comment by konserw** [comment]
+1 for qt5 and cmake :)

**Comment by jcelerier** [comment]
more than 1600 software building on travis with Qt5 and it's still not there... think of the bandwidth :(

**Comment by konserw** [comment]
Thanks to @marco-piccolino for now I'm using script from https://github.com/benlau/qtci for Qt on travis OSX

**Comment by tooomm** [comment]
In the meantime `cmake` is included btw @jcelerier. But Qt is still missing.

>If there are any packages you’d like to see added to our macOS images, please file a Github Issue and include `[macos request]` in your subject line.

(from https://blog.travis-ci.com/2017-12-06-xcode-92-has-landed)

I doubt it's that, but maybe you want to adjust the title that people can find it more easily.

**Comment by luzpaz** [comment]
> more than 1600 software building on travis with Qt5 and it's still not there... think of the bandwidth :(

1 year anniversary of https://github.com/travis-ci/travis-ci/issues/5278#issuecomment-269920964

**Comment by jcelerier** [comment]
okay, I'll just bump every day

**Comment by jcelerier** [comment]
bump

**Comment by jcelerier** [comment]
@BanzaiMan if it's not going to happen at all you might as well close the issue

**Comment by jcelerier** [comment]
> We'll gladly take a look again!

**Comment by jcelerier** [comment]
> We'll gladly take a look again!

**Comment by luzpaz** [comment]
+1

**Comment by lhy0403** [comment]
Any update on this Qt issue ?

**Comment by lhy0403** [comment]
Should we keep this active?

**Comment by jcelerier** [comment]
isn't travis a dead company anyways

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
bump

**Comment by zgyarmati** [comment]
+1

**Comment by luzpaz** [comment]
+1

**Comment by luzpaz** [comment]
bump

**Comment by jcelerier** [comment]
bah, travis is dead anyways
