### ISSUE TITLE
First test always be stack level too deep

### ISSUE THREAD

**Issue by kalashnikovisme** [travis-ci/travis-ci#5279]
Hi, everybody!
I have problem with my project.

First test always returned `SystemStackError: stack level too deep` but on my local machine everythings is good. What can it be?

https://travis-ci.org/ulmic/ulmicru/builds/96369484#L1021

**Comment by BanzaiMan** [comment]
This is quite curious, but I don't know if it's Travis CI issue. https://travis-ci.org/ulmic/ulmicru/builds/96369488, which ran the same commit, passed, and subsequent commits show completely different errors.

If you have more evidence to show that there is something we should fix, we are happy to look into it, but it seems like an application issue to me.

I'm closing this for now.
