### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by RMcGirr83** [travis-ci/travis-ci#5285]
builds are failing with Ubuntu gets

Err http://us-central1.gce.archive.ubuntu.com precise-updates/multiverse amd64 Packages

  403  Forbidden [IP: 199.223.234.73 80]

**Comment by renemilk** [comment]
[Still happening](https://travis-ci.org/wwu-numerik/dune-stuff/jobs/96718837#L144)

**Comment by ynelin** [comment]
Also have this problem
Err http://us-central1.gce.archive.ubuntu.com trusty/main amd64 Packages
  403  Forbidden [IP: 130.211.168.42 80]

**Comment by stefanhorning** [comment]
Same here. You should probably update your status page somehow to not leave people figuring...

**Comment by domsj** [comment]
we're having the same problem https://travis-ci.org/openvstorage/alba/jobs/96756174 :-(

**Comment by stefanhorning** [comment]
It's basically happening on all boxes (tried 12.04 and 14.04).

**Comment by solarce** [comment]
It seems that the primary Ubuntu mirror that's available for the GCE region we use, *us-central1*, has started returning 403s.

You can mitigate the issue by using `sudo sed -i 's/us-central1.gce/us-central1.gce.clouds/' /etc/apt/sources.list && sudo apt-get update` and we are looking into how to fix this, as the mirror *us-central1.gce.archive.ubuntu.com* is the mirror picked by how Ubuntu's cloud-init mirror selection works. We're also working to reach out to Canonical about the issue.

**Comment by stefanhorning** [comment]
@solarce thanks!

**Comment by solarce** [comment]
As the primary mirror at __us-central1.gce.archive.ubuntu.com__ is managed by Google, we've opened a support case with GCE support about this issue, while also seeing if we can get in touch with someone on Canonical side to help us escalate.

**Comment by liuzxc** [comment]
@solarce thanks a lot!

**Comment by tomchadwin** [comment]
@solarce That works for me - many thanks.

**Comment by solarce** [comment]
It appears that us-central1.gce.archive.ubuntu.com has started working again, we have also deployed a runtime fix to prefer us-central1.gce.clouds.archive.ubuntu.com in the mean time, while we wait for further info from GCE support.

**Comment by stefanhorning** [comment]
Cool, everything seems to work again. :+1:

**Comment by solarce** [comment]
At this time the mirror is working again so we're going to close this issue. Thanks everyone!

**Comment by tomchadwin** [comment]
Thanks, all. Much appreciated.

**Comment by sataly1995** [comment]
Goo

**Comment by Habbie** [comment]
Mirror is 503ing for me currently.

**Comment by Habbie** [comment]
```
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/universe/b/boost-defaults/libboost-graph-dev_1.54.0.1ubuntu1_amd64.deb  503  Service Unavailable [IP: 173.255.118.228 80]
```

```
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/universe/y/yaml-cpp/libyaml-cpp0.5_0.5.1-1_amd64.deb  503  Service Unavailable [IP: 173.255.118.228 80]
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/g/geoip/geoip-bin_1.6.0-1_amd64.deb  503  Service Unavailable [IP: 173.255.118.228 80]
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/g/geoip/libgeoip-dev_1.6.0-1_amd64.deb  503  Service Unavailable [IP: 173.255.118.228 80]
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/universe/y/yaml-cpp/libyaml-cpp-dev_0.5.1-1_amd64.deb  503  Service Unavailable [IP: 173.255.118.228 80]
```

**Comment by Habbie** [comment]
Works again.

**Comment by chdemko** [comment]
Currently not working

~~~
E: Failed to fetch https://packagecloud.io/basho/riak/ubuntu/dists/trusty/main/source/Sources  401  Unauthorized
E: Failed to fetch https://packagecloud.io/basho/riak/ubuntu/dists/trusty/main/binary-amd64/Packages  401  Unauthorized
E: Failed to fetch https://packagecloud.io/basho/riak/ubuntu/dists/trusty/main/binary-i386/Packages  401  Unauthorized
~~~

**Comment by MFreidank** [comment]
I am running into the exact same issue as @chdemko 
No changes to my build pipeline were made, so I'm assuming a bug on the travis-side.

**Comment by carrickr** [comment]
Basho went into receivership back in July of 2017, so I'm guessing that mirror is not coming back.

**Comment by cotsog** [comment]
@chdemko @MFreidank @carrickr Thanks for the reports!

We are currently tracking this over at https://github.com/travis-ci/travis-ci/issues/8607

The current workaround if you aren't using riak is to remove the source like this:

```
before_install:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get update
```
