### ISSUE TITLE
[feature request] sparse-checkout support

### ISSUE THREAD

**Issue by PeterDaveHello** [travis-ci/travis-ci#5286]
Hi there, seems there is no issue for sparse-checkout, I would like to respectfully suggest travis-ci to have this feature, which can help decrease the disk space a project need, also release the io performance, especially for large projects, sometimes we don't need to checkout all the files for a test, not sure what do you think, so I just open this issue, thanks!

**Comment by BanzaiMan** [comment]
I am not sure why one would want to do that on a CI build. git checkout is probably a small portion of a build, and not having certain files in tests seems a bigger problem than the problem this tweak attempts to address. If the repo is huge, you can change the depth of the checkout with `git.depth`.

**Comment by PeterDaveHello** [comment]
Hi @BanzaiMan, the reason can by found at #2715, to prevent all the files been checkouted.

**Comment by PeterDaveHello** [comment]
@BanzaiMan I am trying to implement this feature in https://github.com/travis-ci/travis-build/pull/882, would you please take a look and help review/audit it? Thanks a lot!

**Comment by annulen** [comment]
@BanzaiMan We use Travis CI to do style checks on WebKit, and doing full checkout (including layout tests, which take > 1.5 Gigs and don't need style checks) takes a significant portion of the total check time.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/1149 is the replacement PR.

**Comment by annulen** [comment]
@BanzaiMan When will this feature be deployed to travis-ci.org?

**Comment by BanzaiMan** [comment]
@annulen It is deployed now.

**Comment by annulen** [comment]
@BanzaiMan Is `sparse_checkout` value supposed to be a path relative to repository root? E.g. in documentation `sparse_checkout: skip-worktree-map-file` means there is file named `skip-worktree-map-file` in the repo alongside with `.travis.yml`, correct?

**Comment by annulen** [comment]
Actually, I've stepped through commands in log, and it looks like you have a bug in https://github.com/travis-ci/travis-build/commit/fa7d7c8abb0b5f4a6f71b51672819512d859b1bb#diff-289130ba5abd69fecc49c9536b980bc9 - `cat` (or `cp`) should be used there, otherwise checkout contains only file which is the argument of `parse_checkout`

**Comment by annulen** [comment]
See https://travis-ci.org/annulen/webkit/builds/312475083?utm_source=github_status&utm_medium=notification - both times `echo .travis-sparse-checkout >> annulen/webkit/.git/info/sparseCheckout` is run, while second command should be `cat .travis-sparse-checkout >> annulen/webkit/.git/info/sparseCheckout` or `cp .travis-sparse-checkout annulen/webkit/.git/info/sparseCheckout`

**Comment by BanzaiMan** [comment]
@annulen You are right about that. Would you like to work on a PR?

**Comment by annulen** [comment]
See #1268

**Comment by PeterDaveHello** [comment]
Hmmm, I think I use `cat` in origin commit, I can send a PR if you don't mind.
