### ISSUE TITLE
How can I build branches/commits on demand in Travis CI?

### ISSUE THREAD

**Issue by kichalla** [travis-ci/travis-ci#5289]
I originally posted this question on StackOverflow over [**here**](http://stackoverflow.com/questions/34272907/building-branches-commits-on-demand-in-travis-ci)...any suggestions?

I would like to achieve the following setup in Travis CI.

1. Do a build whenever commits are pushed to `dev` or `release` branches only.

2. Disable builds whenever commits are pushed to any other branch apart from `dev` or `release` but build pull requests.

3. If a developer is really interested to know if his commits are good, then he should be able to kick start a build on Travis CI explicitly by choosing a branch/commit.

From reading the documentation on Travis CI and some blog posts, I see that I can achieve "**1.**" and "**2.**"

Does anyone know how to make "**3.**" work?

**Update-1:**  
The reason I want scenario "**3.**" is because the developers in our team (or in general any other team) make several commits and push them even before they send out a pull request. Building for every single commit of a private branch even before it goes for a pull request is causing lot of requests to queue up in the Travis CI queue which unnecessarily blocks developers who really care to verify a particular commit to check if everything is good or not before sending out a pull request.

Having the following is just fine for us:

- Build on every commit push to `dev` and `release` branches
- Build on every commit pushed to a pull request

**Comment by kbrock** [comment]
@kichalla There is a work around that seems to work fine:

Travis will run on every branch push and pull request change.
But what travis does is up to you.

So you can edit the `script` section of your `.travis.yml` file and just short circuit your script with a success if you don't want to run. I played around with a script that created `.skip-ci` file to skip the build [here](https://github.com/kbrock/johnny_five_sample).

that could have any logic and be written in any language.
Just remember to have `script: $skip_ci || $build_command` and not `script: $run_ci && $build_command` - the first one will always return true and travis will report it better.

**Comment by joshk** [comment]
3. should be achievable via https://docs.travis-ci.com/user/triggering-builds

I'm going to close this issue for now as there is a working solution for this use case.

**Comment by irving-ssk** [comment]
Are you serious? To force a user to do coding instead of adding a single button `resubmit` to UI?

**Comment by fniephaus** [comment]
@irving-ssk: have you seen the `Trigger build` option? The Travis team has added a lot of great features in the last few years, no need to "get serious".

![image](https://user-images.githubusercontent.com/2368856/37730174-45803ad6-2d3f-11e8-95ba-032481501c22.png)

**Comment by BanzaiMan** [comment]
@irving-ssk Looks like this bit @fniephaus mentioned never made it to the docs proper, though it was announced in the blog https://blog.travis-ci.com/2017-08-24-trigger-custom-build. Sorry about that. We'll have to fix that shortcoming.

**Comment by irving-ssk** [comment]
Folks, this is great to end up being wrong while complaining. :)
Thanks!
