### ISSUE TITLE
Downgrade to bundler 1.10.x

### ISSUE THREAD

**Issue by mattolson** [travis-ci/travis-ci#5290]
Bundler 1.11.0 introduced a bug that is causing builds to fail:
https://github.com/bundler/bundler/issues/4147

Is it possible to specify a different version? If not, Travis should consider downgrading until this is fixed.

**Comment by solarce** [comment]
We've found that the following fixes builds for folks encountering issues with the latest bundler.

```
before_install:
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.10.6
```

**Comment by mattolson** [comment]
@solarce Thank you, that worked!

**Comment by jmeridth** [comment]
@solarce Your technique is the cleanest I've seen and used so far.  Thank you for sharing.

**Comment by solarce** [comment]
We're glad to hear it's working, credit goes to @cotsog for coming up with it, I just passed it along :)

**Comment by jmeridth** [comment]
@cotsog @solarce  :beers:
