### ISSUE TITLE
Container based g++ compilation picks wrong g++ version

### ISSUE THREAD

**Issue by pranith** [travis-ci/travis-ci#5295]
Please see the build here: https://travis-ci.org/pranith/qsim/jobs/96907781

I set g++ version as 4.8 in my .travis.yml file. But the version of g++ picked up is 4.6 as seen in the log. This causes build failures when I used C++11 features enabled by passing -std=c++11 flag, which is present only from 4.8 onwards.

Please fix.

Thanks!

**Comment by BanzaiMan** [comment]
You are invoking `gcc` and `clang` as compilers. Would this help?

```yaml:
compiler:
  - gcc-4.8
  - clang-3.4
```

**Comment by BanzaiMan** [comment]
Duplicate of #5293.
