### ISSUE TITLE
CocoaPods install cause pod not found on Xcode 7 image

### ISSUE THREAD

**Issue by saiday** [travis-ci/travis-ci#5298]
`'AnyPodDependency.h' file not found` when building

On Xcode 7 image, only if I commit all my cocoapods dependencies into git, skipping pod install on Travis CI, then my build works. On Xcode 6 image, skipping pod install on Travis CI is unnecessary, In other words, this is tricky that cannot `pod install` on specified image?
I tried CocoaPods `0.37.0` and default, both with no luck.

                              | Xcode 6 image | Xcode 7 image
------------------------ | -------------------- | ------------------- |
pod install              |           v             |             x          |
without pod install  |           v             |             v         |

I upgrade from Xcode 6, this issue bothered me for a month. And this is weird, how come I don't see any issue related?

**Comment by mattyohe** [comment]
@saiday Can you check in your pods?

Also your cocoa pods is out of date, you should update that as well.
