### ISSUE TITLE
Enabled repository has 'no builds' despite pushes

### ISSUE THREAD

**Issue by timwis** [travis-ci/travis-ci#5299]
Hey folks, I hate to come here with such a simple thing, but I really think there may be something wrong.

I created a very simple [.travis.yml](https://github.com/timwis/leaflet-choropleth/blob/gh-pages/.travis.yml) file that just expects it to run `npm test`. I've enabled the repository in my profile on travis-ci.org, and I've made several commits & pushes since then - both using `--allow-empty` and making an actual change to the readme file. I can see these commits in the *Settings > Requests* tab of travis, but it says "No builds for this repository" on the *Current* / *Build History* tabs.
[![Build Status](https://travis-ci.org/timwis/leaflet-choropleth.svg)](https://travis-ci.org/timwis/leaflet-choropleth)

I've tried disabling it and removing the hook on github.com and starting over to no avail. Seems to simple to get wrong, but have I? Or is there an issue here?

Thanks for your time.

**Comment by stof** [comment]
@timwis The gh-pages branch is excluded by default in Travis, as it is meant to contain a website. If you want to run builds for it, you need to specify it in the .travis.yml file: https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches

**Comment by BanzaiMan** [comment]
@stof has it right. You can also check this on https://travis-ci.org/timwis/leaflet-choropleth/requests.

**Comment by timwis** [comment]
Wow, thanks @stof, wouldn't have guessed that. Perhaps a tooltip or something on the requests page might make this less of a gotcha in the future? Anyway, thanks for your help.
