### ISSUE TITLE
Allow custom timeouts

### ISSUE THREAD

**Issue by gsnedders** [travis-ci/travis-ci#5306]
It'd be nice to allow custom timeouts, at least those which are shorter than the default. I have a project where job times are normally under three minutes: I'd had to restart a whole load of builds due to an external issue, and two jobs on one build were still going after half an hour meaning that Travis CI wasn't starting on other builds: it'd be nice to set a far lower than the default timeout, given a ten times increase in test suite time is _not_ expected!

**Comment by joshk** [comment]
Thanks for the idea. We will keep note of this.
