### ISSUE TITLE
Python 3.5 builds are failing

### ISSUE THREAD

**Issue by par2** [travis-ci/travis-ci#5307]
Recently nosetests throws this error when trying to import `pandas`:

    ERROR: Failure: ValueError (numpy.dtype has the wrong size, try recompiling)

I'm using a pinned dependencies and reverted changes to the last known point of it working, yet this error still only happens only for 3.5.  2.7, 3.3 and 3.4 always pass.  Did something change with the 3.5 why it won't install `pandas`?

**Comment by BanzaiMan** [comment]
Did this ever work for 3.5?

**Comment by par2** [comment]
Yes it worked well.

**Comment by par2** [comment]
FYI - I tried a simple add/revert on my test repo and got a similar result - failure on py35 with a setup that worked ~2 weeks ago.

**Comment by BanzaiMan** [comment]
Do you have build log URLs that show a previous success and a recent failure?

**Comment by par2** [comment]
Here is a lucid example of failures post-amend/revert operations using my test repo:

Prior success: [requirements.txt and yaml were copied](https://travis-ci.org/par2/lamana-test/jobs/95118880)

Recent failures: [latter files were changed](https://travis-ci.org/par2/lamana-test/jobs/97354254), then [reverted to original files](https://travis-ci.org/par2/lamana-test/jobs/97356952)

---
I notice Python 3.5.1 was released [Dec. 6](https://www.python.org/downloads/release/python-351/), one day after my last successful build on py35.  Althouh the build history says Python 3.5.0 was used, the new release should affect any server-side backends, correct?  Thanks for your assistance.

**Comment by BanzaiMan** [comment]
Thanks for the info. I have a suspicion that it is an issue with packaging. Could you try `3.5.1`? This is different from the current `3.5` archive, and has undergone a different packaging procedure.

**Comment by par2** [comment]
I tried 3.5.1 and got the same result - [3.5 fails while 2.7, 3.3 and 3.4 work](https://travis-ci.org/par2/lamana-test/jobs/97569311).  Though I am unsure why the original 3.5.0 version suddenly stopped working.

**UPDATE: Unpinning numpy solved the build issue on travis.** Perhaps a change in the MS Visual Studio compiler affected both python 3.5.0 and 3.5.1 (?).

I will offer this feedback: on a separate machine running a fresh conda version of py 3.5.1 (and Visual Studio Community [V.14 for Visual C++](https://matthew-brett.github.io/pydagogue/python_msvc.html)), `pip install -r requirements.txt` failed.  I conclude `matplotlib==1.4.3`, `numpy==1.9.2` and `pandas==0.16.2` have issues on Python 3.5.

**Comment by BanzaiMan** [comment]
@par2 Thank you for following up. I am happy to know that you were able to find the culprit and the workaround. Can this issue be closed, then?
