### ISSUE TITLE
ruby-head is old

### ISSUE THREAD

**Issue by eregon** [travis-ci/travis-ci#5308]
ruby-head on http://rubies.travis-ci.org/ubuntu/12.04/x86_64/ruby-head was last built on
`2015-12-09 12:46:35 UTC`.

But there has been a few green builds since then on https://travis-ci.org/ruby/ruby/builds.

Could you investigate why the ruby-head binary was not updated?

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/travis-rubies/jobs/96778459#L565

> `ERRO[0009] failed to upload: /home/travis/build/travis-ci/travis-rubies/ruby-head.tar.bz2  err=The AWS Access Key Id you provided does not exist in our records.`

**Comment by BanzaiMan** [comment]
Not sure how we lost the credentials. :-/

**Comment by BanzaiMan** [comment]
We cleaned up usage of AWS credentials a week ago, which explains the lack of updates.

I've fixed that now. I've manually triggered `ruby-head` and `ruby-head-clang` builds, so that the binaries are up to date. Others will be updated shortly as the builds succeed.

**Comment by eregon** [comment]
Thank you!
Latest specs [passed](https://travis-ci.org/ruby/rubyspec/builds/97220946)!

**Comment by BanzaiMan** [comment]
@eregon Yay! Thanks for reporting.
