### ISSUE TITLE
PHP builds that require mongo extension are failing

### ISSUE THREAD

**Issue by luispabon** [travis-ci/travis-ci#5309]
Doesn't seem to happen on all PHP versions though, only php 5.5 through to php 7.

Example:
https://travis-ci.org/FriendsOfSymfony/FOSOAuthServerBundle/builds/97188958

```
echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script.2

composer selfupdate
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/mongo.so' - /home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/mongo.so: cannot open shared object file: No such file or directory in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/mongo.so' - /home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/mongo.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

**Comment by cjsaylor** [comment]
We had this same problem as well and it necessitated installing via pecl.

```bash
printf "\n" | pecl install mongo
```

It is a BC breakage from the legacy infrastructure though.

**Comment by BanzaiMan** [comment]
Thanks for the report. The PHP runtimes which are installed on demand do not have all the extensions mentioned in the documentation (https://docs.travis-ci.com/user/languages/php#PHP-extensions). We will have to repackage them.

**Comment by BanzaiMan** [comment]
I should note here that `mongo` is not compatible with PHP 7. https://docs.mongodb.org/ecosystem/drivers/php/

**Comment by luispabon** [comment]
According to that page, the latest mongodb driver is compatible with PHP7, unless I'm missing something here?

**Comment by BanzaiMan** [comment]
@luispabon Correct. Currently, we are compiling that for `7.0snapshot`, but it is not available for `7` yet.

**Comment by luispabon** [comment]
Copy that, thank you for the heads up :+1:

**Comment by BanzaiMan** [comment]
7.0.0 has been packaged with mongodb driver. Could you try it now?

**Comment by luispabon** [comment]
Checking now

**Comment by luispabon** [comment]
Hmmm now the build fails with a different error altogether:

https://travis-ci.org/FriendsOfSymfony/FOSOAuthServerBundle/builds/97697345

(.travis.yml file is definitely there)

**Comment by BanzaiMan** [comment]
@luispabon Hmmm. Could you try pushing a new commit to this PR?

**Comment by luispabon** [comment]
Build triggered now correctly :+1: waiting for results

**Comment by BanzaiMan** [comment]
Hmm. it didn't work. :-/

**Comment by luispabon** [comment]
:'(

**Comment by BanzaiMan** [comment]
Oh, it's calling `mongo`. I don't think that's PHP 7 compatible. Could you try `mongodb`?

**Comment by luispabon** [comment]
Damn, it's a requirement on one of the dependencies, I have no control over it. These use the legacy mongo extension, instead of mongodb.

https://docs.mongodb.org/ecosystem/drivers/php/

Opened an issue here https://github.com/doctrine/mongodb-odm/issues/1316 and someone else did the same here https://github.com/doctrine/mongodb/issues/239

Will report back once these projects switch to the new driver.

Is the new mongodb extension available on older php versions on travis?

**Comment by BanzaiMan** [comment]
@luispabon 5.5.30 should have both `mongo` and `mongodb` now.

The original problem for which this issue was opened is now fixed, I believe.

https://travis-ci.org/FriendsOfSymfony/FOSOAuthServerBundle/jobs/97188968#L144 shows that `mongo.so` was not found for PHP 5.5, but it now is: https://travis-ci.org/FriendsOfSymfony/FOSOAuthServerBundle/jobs/97703920

Can this be closed?

**Comment by luispabon** [comment]
It can :+1: thank you so much for all your help. Have a great weekend!
