### ISSUE TITLE
Builds hang forever

### ISSUE THREAD

**Issue by sushantdhiman** [travis-ci/travis-ci#5310]
Travis CI build are not starting and it blocks other builds as well. 

Check this build https://travis-ci.org/sequelize/sequelize/builds/97216226

Its not even started even if queue is empty.

**Comment by BanzaiMan** [comment]
Sorry for the issue. Could you try canceling and restarting the build?

**Comment by guillaumevincent** [comment]
same here https://travis-ci.org/guillaumevincent/lesspass/builds/97227340

**Comment by sushantdhiman** [comment]
Thanks, Build is restarted and its now working. But is there any specific reason behind it. This happened twice to my CI builds today.

**Comment by sushantdhiman** [comment]
PR are hanging again here https://travis-ci.org/sequelize/sequelize/builds/100301184 

I noticed it only happens when I use forced update

**Comment by joshk** [comment]
Are you seeing consistent issues with forced pushes?

**Comment by sushantdhiman** [comment]
Yes

**Comment by sushantdhiman** [comment]
@joshk This one just got stuck https://travis-ci.org/sequelize/sequelize/builds/100635151, It was a forced update as well.

**Comment by fernandofleury** [comment]
I'm constantly facing problems with `--force` as well. I've checked and it's not on the roadmap right now, right?

Is there any workaround I can apply to get builds running properly? I'm constantly rebasing + forcing branches for my current workflow

**Comment by sushantdhiman** [comment]
This issue is so easy to reproduce, Please have a look on it.

**Comment by Andretalik** [comment]
This one of mine has been unable to run the tests.
https://travis-ci.org/Andretalik/bucketlist_API

**Comment by BanzaiMan** [comment]
@Andretalik Looks like yours were simply queued and took longer to start than you'd hoped.

**Comment by Andretalik** [comment]
@BanzaiMan Not really, the build starts, then the tests take so long to start that Travis terminated the build because no output was generated for 10 mins

**Comment by BanzaiMan** [comment]
@Andretalik That is not what this issue was about.

**Comment by sushantdhiman** [comment]
I haven;t seen this issue from some time
