### ISSUE TITLE
Specifying Python v2.7.11 results in "bzip2: (stdin) is not a bzip2 file."

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#5313]
For both the container builds and the new trusty GCE beta, if I specify the Python version as 2.7.11 (see [.travis.yml](https://github.com/mozilla/treeherder/blob/python-2.7.11/.travis.yml)), I get:

Container...
https://travis-ci.org/mozilla/treeherder/jobs/97257340
```
2.7.11 is not installed; attempting download
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

Trusty GCE beta:
https://travis-ci.org/mozilla/treeherder/jobs/97257343
```
2.7.11 is not installed; attempting download
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
Many thanks :-)

**Comment by BanzaiMan** [comment]
I've created a 2.7.11 archive. It should work now. Though it might have a narrower Unicode support. See #4948.

**Comment by edmorley** [comment]
Working great now - thank you :-)
https://travis-ci.org/mozilla/treeherder/builds/97292124
