### ISSUE TITLE
Can't use ruby 2.2.4 for build because of the `--binary` flag

### ISSUE THREAD

**Issue by yous** [travis-ci/travis-ci#5314]
https://travis-ci.org/ruby/www.ruby-lang.org/builds/97257736

```
$ rvm use 2.2.4 --install --binary --fuzzy
ruby-2.2.4 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-2.2.4 do rvm gemset create ' first, or append '--create'.
```

Maybe the `--binary` flag should be removed, since RVM will try to download binary ruby package first, as the following is from `rvm help install`:

> By default RVM will try to download binary ruby package instead of compiling.
> If such package is not available normal compilation will be performed.
> Using binary builds can significantly decrease ruby installation time.
>
> There are two options controlling binary rubies installation:
>
> - `--binary` - force binary installation, do not try to compile ruby.
> - `--disable-binary` - do not try binary ruby, always compile.

Is the `--binary` flag intended, to disable ruby compilation?

**Comment by BanzaiMan** [comment]
It is intended, so that we can pull the binary package when it's available.

**Comment by yous** [comment]
Thanks for the quick response! I'll wait for the binary package. Closing.

**Comment by BanzaiMan** [comment]
It should be there now, by the way.

**Comment by yous** [comment]
Now the binary package is available, thanks.
