### ISSUE TITLE
Access private repository over GitHub SVN for the first time

### ISSUE THREAD

**Issue by k06a** [travis-ci/travis-ci#5315]
I am trying to do `pod install` and one of my pods is installed via `svn`:
```
[!] Error installing MySuperLib
[!] /usr/local/bin/svn export --non-interactive --trust-server-cert --force https://github.com/MySuperOrg/MySuperRepo/tags/1.1.1/libraries/MySuperLib/ /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/d20151216-750-7kjldv
svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Unable to connect to a repository at URL 'https://github.com/MySuperOrg/MySuperRepo/tags/1.1.1/libraries/MySuperLib/'
svn: E215004: No more credentials or we tried too many times.
Authentication failed
```

We just need to execute `svn list https://github.com/MySuperOrg/MySuperRepo/`, then enter GitHub login and password for bot account and `(p)ermanentely` save server key on client (travis) side.

**Comment by k06a** [comment]
Found solution, added this lines to permanently trust server SSL-cert and tell svn login and password:
```
before_install:
- echo p | svn list https://github.com/MySuperOrg/MySuperRepo --username=<LOGIN> --password=<APP_TOKEN>
```

**Comment by BanzaiMan** [comment]
Happy to hear that you were able to find a solution. Can this be closed?

**Comment by k06a** [comment]
Sure, hope anyone with the same problem will be able to discover solution here :)

**Comment by sunkaraamrutha** [comment]
@k06a : Were you able to establish the connection to the github repo from SVN? I am running into the same issues while trying to download a specific directory from the github repo using SVN.

**Comment by k06a** [comment]
@sunkaraamrutha this work fine:
```
before_install:
- echo p | svn list https://github.com/MySuperOrg/MySuperRepo --username=<LOGIN> --password=<APP_TOKEN>
```
