### ISSUE TITLE
Init with empty elasticsearch/scripts folder

### ISSUE THREAD

**Issue by eshem** [travis-ci/travis-ci#5317]
I am using elasticsearch and need the ability to copy scripts in to the elasticsearch configuration ```/etc/elasticsearch``` dir for builds. The issue is that the scripts are placed in to ```/etc/elasticsearch/scripts``` folder which needs to be created manually.

This requires the use of ```sudo mkdir```. I am trying to upgrade to Travis' container based infrastructure where sudo is not permitted. A potential implementation would be initializing the machine with an empty ```scripts``` folder that can be leveraged by users if necessary.

**Comment by BanzaiMan** [comment]
Hello. Using `service`s beyond what the package provides by default requires `sudo` at this time.

**Comment by eshem** [comment]
Sure, I am currently doing that. Thanks. 

Just an idea for an enhancement.

**Comment by BanzaiMan** [comment]
Closing this for now. `elasticsearch` is currently simply passed to `sudo service X start`. While not impossible, it seems like a corner case best dealt with individually.
