### ISSUE TITLE
Documentation for uploading artifacts

### ISSUE THREAD

**Issue by mernst** [travis-ci/travis-ci#5318]
https://docs.travis-ci.com/user/uploading-artifacts/ says, "Unless you programatically generate unique filenames and folders, artifacts are overwritten every build."  However, using examples from that webpage, for my build #706 the artifacts appeared on S3 in directory `GITHUBID/GITHUBPROJECT/706/706.1/...`.  Therefore, I suggest that you update the documentation.

As another comment, when I didn't specify which particular files to archive, I got this error during archiving:

```
/home/travis/build.sh: line 45: /home/travis/bin/artifacts: Argument list too long
```

Since there are many discussions on the web about what to do when encountering this error, I think that the documentation should mention this as a common problem.  Even better would be to change the implementation of the default behavior so that users don't encounter it.

Thanks!

**Comment by BanzaiMan** [comment]
Sorry for the delay. Could you clarify how you suggest to improve the docs? Better yet, could you open a PR for https://github.com/travis-ci/docs-travis-ci-com?

Thank you!

**Comment by mernst** [comment]
Can you clarify what you don't understand about my comments?  You haven't said what is ambiguous or confusing.  It sounds like you just want me to write the exact same thing again. :-)  I don't want to waste our time doing that.

You added the tag "documentation", but this is also a request to improve the default behavior.
With regard to writing a pull request to change the default behavior, I am not familiar with the implementation and so you would be able to do this much more efficiently than I could.

**Comment by barbeau** [comment]
@mernst Did you come up with a configuration that overwrites the same artifact on each build?

I'm seeing the same issue of Travis generating a build-specific upload.  For example:
https://travis-ci.org/CUTR-at-USF/gtfs-realtime-validator/builds/226532486

...created an S3 upload URL specific to that build number (290):
https://s3.amazonaws.com/gtfs-rt-validator/CUTR-at-USF/gtfs-realtime-validator/290/290.1/target/gtfs-rt-validator-1.0-SNAPSHOT.jar

I don't want this - I want the JAR file to be overwritten on each build so I can use the same URL to download the latest build for that version, like:
https://s3.amazonaws.com/gtfs-rt-validator/gtfs-rt-validator-1.0-SNAPSHOT.jar

**Comment by mernst** [comment]
@barbeau Sorry, I didn't figure out how to overwrite the same artifact.

**Comment by barbeau** [comment]
@mernst Ok, thanks!

For anyone else stumbling on this thread, I did finally get the upload to work overwriting the same artifact, but using `deploy:` instead of `artifacts:`:

~~~
deploy:
  # Travis will only attempt a deployment for master branch
  on:
    branch: master
  provider: s3
  # Below 3 values are configured as environmental variables in Travis web console
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  # Prevent Travis from deleting build directory
  skip_cleanup: true
  acl: public_read
  # Path to build artifacts
  local_dir: $HOME/.m2/repository/edu/usf/cutr/gtfs-rt-validator/1.0.0-SNAPSHOT
  upload_dir: travis_builds
  # Set the Cache-Control header.
  cache_control: "max-age=21600"
~~~

Full `.travis.yml` is [here](https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/.travis.yml).

**Comment by jononomo** [comment]
For the life of me I cannot understand the Travis artifacts documentation, and I keep getting the error: `/home/travis/bin/artifacts: Argument list too long`

**Comment by BanzaiMan** [comment]
Sorry about the terse response earlier. The issue here is that the file list appears to be too long for `bash` to process. The addon needs to take this into account; split the file list and run `artifacts` multiple times instead.

**Comment by jononomo** [comment]
thanks for your response, @BanzaiMan -- I asked my question with more details here: https://stackoverflow.com/questions/50457297/how-do-i-upload-artifacts-from-my-travis-tests-to-s3

My config file is as follows:

```
language:
- node_js
node_js:
- '10.0'
addons:
  artifacts:
    working_dir: dist
    target_paths: gdpr
    s3_region: us-east-2
    debug: true
env:
  global:
  - secure: encrypted_ARTIFACTS_KEY (AWS access key id)
  - secure: encrypted_ARTIFACTS_SECRET (AWS secret access key)
  - ARTIFACTS_BUCKET: my.specialbucket.com
```

**Comment by basisbit** [comment]
this issue is still not solved. Documentation is horrible and the error message does not actually state the problem.
