### ISSUE TITLE
Fetch cache from different branch

### ISSUE THREAD

**Issue by keradus** [travis-ci/travis-ci#5319]
https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches states:
> If a branch does not have its own cache yet, it will fetch the master branch cache.

Is it possible to somehow switch that behaviour to fetch the cache from branch, for which one send PR? If one send PR for `legacy` branch it would be cool to use that cache instead of `master` branch cache.

**Comment by keradus** [comment]
ref #2661

**Comment by joshk** [comment]
Hi @keradus 

I believe that is the case. Do you have a build which you see this not happening?

**Comment by keradus** [comment]
So you said that docs is outdated and it already fetch cache from PR-target branch ?

**Comment by joshk** [comment]
I believe it might be, do you have a build I can look at if it is not working the way I have described?

**Comment by keradus** [comment]
It is working as you said (ref https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/97054910#L99), thanks!
In that case please, could the documentation be updated ? It states the cache would be taken from master, and it is not always true, as in my example.

**Comment by joshk** [comment]
Sure, we can look into getting this updated.

cc. @plaindocs

**Comment by plaindocs** [comment]
Sure thing.

**Comment by keradus** [comment]
Thank you!
