### ISSUE TITLE
Github releases deployment error "Permission denied"

### ISSUE THREAD

**Issue by micfort** [travis-ci/travis-ci#5320]
Hey, 

I'm trying to deploy to github releases and I get an error permission denied.
```
/Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-4.2.0/lib/octokit/client/releases.rb:86:in `initialize': Permission denied - OpenPSTD-2.0.103-osx.dmg (Errno::EACCES)
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-4.2.0/lib/octokit/client/releases.rb:86:in `new'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-4.2.0/lib/octokit/client/releases.rb:86:in `upload_asset'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.8.11/lib/dpl/provider/releases.rb:118:in `block in push_app'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.8.11/lib/dpl/provider/releases.rb:102:in `each'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.8.11/lib/dpl/provider/releases.rb:102:in `push_app'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.8.11/lib/dpl/provider.rb:145:in `block in deploy'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.8.11/lib/dpl/cli.rb:41:in `fold'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.8.11/lib/dpl/provider.rb:145:in `deploy'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.8.11/lib/dpl/cli.rb:32:in `run'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.8.11/lib/dpl/cli.rb:7:in `run'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.8.11/bin/dpl:5:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/bin/dpl:23:in `load'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p547/bin/dpl:23:in `<main>'
failed to deploy
```

I configured the deploy with the command ```travis setup releases``` and only added ```skip_cleanup```
The complete build is at https://travis-ci.org/micfort/openPSTD/jobs/97412916
and the github repo https://github.com/micfort/openPSTD

edit: the personal acces token has the ```public_repo``` scope

**Comment by BanzaiMan** [comment]
[The corresponding build](https://travis-ci.org/micfort/openPSTD/builds/97412914) doesn't look like a build triggered by a tag.

![micfort_openpstd_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/11887455/5dd46b60-a502-11e5-8b24-30dfa1188f75.png)

[Build 104](https://travis-ci.org/micfort/openPSTD/builds/97413066) is supposed to be that tagged build, but no attempt to deploy is made.

I seem to recall an issue with deploying from numeric-only tags (which build 104 is), but I can't locate it. Could you try tagging with at least one alphabet?

**Comment by micfort** [comment]
I have tried what you asked, but still the same problem: https://travis-ci.org/micfort/openPSTD/jobs/97648274

**Comment by BanzaiMan** [comment]
Sorry about the delay. Looks like the repo has undergone some changes, and I can't quite figure out the latest status is.

Another possibility is that the API key was not properly encrypted.

Do you need further assistance?

**Comment by BanzaiMan** [comment]
Closing due to lack of details. If you are still having issues, please open a new one.
