### ISSUE TITLE
Seemingly outdated documentation

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#5327]
From what I observed, after the changes last week there are more columns now in the [build environment matrix](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments). It would be great if this one got updated to reflect the current state of affairs. For example it seem that `precise` on `GCE` has the same 7Gb of RAM, instead of the ~3 available in [the `stable` group](https://gist.github.com/meatballhat/d0c8aab9e3bd8a8bcacd#file-01-matrix-include-travis-yml).

Cheers!

**Comment by BanzaiMan** [comment]
Thanks for the note, and sorry for the delay. We've updated the documentation recently.
