### ISSUE TITLE
On Trusty, most recent HHVM is not installed

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5328]
See https://staging.travis-ci.org/BanzaiMan/travis_staging_test/jobs/465702#L115

With
```yaml
language: php
php:
  - hhvm
sudo: required
dist: trusty
```
we expect the latest version of HHVM (3.11.0 as of this writing) to be installed, but we get 3.6.6.

https://github.com/travis-ci/travis-build/pull/571 was an attempt to rectify this issue, but it brought about a different issue where this set up caused 5.6 to be used on containers.

**Comment by jails** [comment]
Even container-based infrastructure are not up to date and still on 3.6.6 https://travis-ci.org/crysalead/router/jobs/100464581#L94

**Comment by BanzaiMan** [comment]
@jails The container's on Precise, and so 3.6.x is as good as it gets.

**Comment by jails** [comment]
Thanks for the head-up !
Hope we won't need to wait for the 12.04 end of life for having trusty on container-based infrastructure.

**Comment by BenMorel** [comment]
Just tried myself with `sudo: required` and `dist: trusty`, and getting the following error:

> hhvm is not pre-installed; installing
> bzip2: (stdin) is not a bzip2 file.
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now

**Comment by BanzaiMan** [comment]
@BenMorel Sorry about that. Currently there is a branch logic that skips HHVM installation if it's not on Precise, and HHVM (and PHP in general) is not yet fully supported on Trusty. See https://docs.travis-ci.com/user/trusty-ci-environment#PHP

**Comment by BanzaiMan** [comment]
@BenMorel `group: edge` will force your build to run on an newer image, which has HHVM 3.11 pre-installed.

**Comment by BenMorel** [comment]
@BanzaiMan Thanks, it runs indeed on HHVM 3.11.0 now. Sorry to be picky, but I need to run it against the latest version (3.11.1) that was released 3 days ago, as a bug that broke my build was just fixed in this version. Should I wait until you update the images, or is there a command I can add to force updating HHVM to the latest version?

**Comment by BanzaiMan** [comment]
@BenMorel on Trusty, you have `sudo`, so you can update the package with `apt-get` if you want.

**Comment by BenMorel** [comment]
It does update it to 3.11.1 indeed. Thank you!

**Comment by BanzaiMan** [comment]
```yaml
language: php
sudo: required
dist: trusty
group: edge
php: hhvm
```

**Comment by andrerom** [comment]
Is there any place where there are info on what enters edge and what enters stable on trusty env?

Specific question right now is: when does this hit stable group for trusty?
However there are a lot of questions such a log would constantly answer, so it is a pity the deployment logs stopped coming after the fucks ups last year that where rolled back.

**Comment by BanzaiMan** [comment]
@andrerom Sorry, there is no easy list to share.

We apologize for the lack of updates. Hopefully we will be working on that soon.

On a side note, please refrain from using "f*". I understand that you are frustrated, but the word serves no purpose in our discourse. Thanks.

**Comment by andrerom** [comment]
issues

**Comment by andrerom** [comment]
Ok, any rough idea on when we might see updated images for trusty in `group: stable`? *(aka no group, unsure which values are valid there as my repo does not have feature flag)*

Specifically interested in when we'll see updates to hhvm, docker and docker-compose out of the box.
