### ISSUE TITLE
Maven ignores environment variables when execution maven commands

### ISSUE THREAD

**Issue by nerro** [travis-ci/travis-ci#5330]
Hi,
I have a maven project (https://travis-ci.org/nerro/table-layout), that will be build for 3 java compiler levels (`1.5`, `1.6` and `1.7`). Therefore I define in my travis-ci.yml file the following environment variables
```
env:
  - JDK5
  - JDK6
  - JDK7
```

If I run it via command line on my machine like `mvn -X package -DJDK5`, so I can see, that `source` and `target` are 1.5 as expected. From Travis logs I see always `1.7` will be used.

My question: will be environment variables passed to maven command? Or my approach is false?

**Comment by BanzaiMan** [comment]
@nerro Hi, there. That is not how you define environment variables. You'll need `NAME=VAL`:

```yaml
env:
  - COMPILER_LEVEL=JDK5
  - COMPILER_LEVEL=JDK6
  - COMPILER_LEVEL=JDK7
⋮
```

Then it will be available for use: `mvn -X package -D$COMPILER_LEVEL`. Please read https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-.travis.yml.

**Comment by nerro** [comment]
Thx
