### ISSUE TITLE
Update to PHP 7.0.1

### ISSUE THREAD

**Issue by BenMorel** [travis-ci/travis-ci#5332]
I have a build failing on Travis CI:

https://travis-ci.org/brick/geo/jobs/95249500

On my local machine, the issue seems to have been fixed since I upgraded to PHP 7.0.1 (released yesterday). On 7.0.0, it segfaults.

Unfortunately, Travis seems to be locked at 7.0.0 (I tried `apt-get update` and `apt-get upgrade`, but it didn't help).

Could you please update the PHP 7 package?

**Comment by BanzaiMan** [comment]
Try `php: 7.0.1` now. I have not released this to `7.0` yet.

**Comment by BenMorel** [comment]
Works with `php: 7.0.1`, thanks. Could you please update this issue when `7.0` points to `7.0.1`?
