### ISSUE TITLE
[precise-gce] python-config --ldflags returns incorrect values

### ISSUE THREAD

**Issue by chiggs** [travis-ci/travis-ci#5336]
We run a suite of tests against Python 2.7 and Python 3.4 as part of our build matrix.  Our build involves compiling a Python extension and linking against libpythonX.so.  This works fine for Python 3.4 (with some softlink hackery to make our build work), however we have a regression on 2.7 that seems to be caused by the migration to precise-gce.  The Python version from command-line is shown as 2.7.9:

```
$ python --version
Python 2.7.9
```

However we get the wrong answer from `python-config --ldflags`
```
$ python-config --ldflags
-lpthread -ldl -lutil -lm -lpython2.6
```

See https://travis-ci.org/potentialventures/cocotb/jobs/97818342

Similar to #5301 and #5269.

**Comment by chiggs** [comment]
Some additional debug (from [this build](https://travis-ci.org/potentialventures/cocotb/jobs/97819815#L157)).

```
$ which python-config
/opt/python/2.6.9/bin/python-config

$ which python
/home/travis/virtualenv/python2.7.9/bin/python

$ find /home/travis/virtualenv/python2.7.9/ -name "*config*"
# No python-config or python2.7-config found
```

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #5326.

**Comment by chiggs** [comment]
Duplicate of #5326.  Fixed by adding the following to `before_install`:

```
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
```

[Working build here](https://travis-ci.org/potentialventures/cocotb/jobs/97827544).  Thanks @BanzaiMan.

**Comment by BanzaiMan** [comment]
Hmm. I thought #5326 was only on Trusty, but I am happy to hear that you were able to resolve it! :-D
