### ISSUE TITLE
Container-based infrastructure: Allow installation of whitelisted packages in scripts

### ISSUE THREAD

**Issue by probonopd** [travis-ci/travis-ci#5338]
> APT packages can be installed through the APT addon, which is avaliable in all infrastructures. When using the container based infrastructure, sudo is disabled in user-defined build phases such as before_install. This prevents installation of APT packages via apt-get

A (suid) helper (e.g., `whitelisted-apt-get`) could allow the installation of the whitelisted packages in scripts rather than having to specify them upfront in `travis.yml`.

Rationale: My build scripts require certain packages, but which packages can only be determined at runtime rather than upfront.

**Comment by BanzaiMan** [comment]
How would you propose that we determine the list "at runtime"? We will fetch *only* `.travis.yml` and we process it to only compile the build script. No user code will be run before `sudo apt-get install` is run and `sudo` is disabled.

The best bet is to list everything you need in the whitelist, and incur hit on build time. Unless you have a huge list, I would think that the additional time should be tolerable.

**Comment by probonopd** [comment]
I don't know enough about the inner workings of travis-ci but I was assuming there is a way from the "outside" to the "inside" of the build container.

**Comment by bfops** [comment]
> which packages can only be determined at runtime rather than upfront.
@probonopd what do you mean? Why can the packages only be determined at runtime?

@BanzaiMan Installing all possible packages isn't always an option, e.g. different versioned ppas might provide the same packages, and different versioned packages might provide the same binaries.

**Comment by probonopd** [comment]
> @probonopd what do you mean? Why can the packages only be determined at runtime?

The dependency packages can vary depending on build arguments that differ between different builds.

**Comment by probonopd** [comment]
Not solving an issue is not a good reason for closing an issue.

**Comment by BanzaiMan** [comment]
I feel that using `sudo: required` is the best course of action.
