### ISSUE TITLE
ability to build v0.10.x, v0.12.x, v4.x with npm3?

### ISSUE THREAD

**Issue by calidion** [travis-ci/travis-ci#5340]
currently the v4.x and below version don't support npm3.
even if i use 
before script
npm install -g npm@3.5

the npm version seems not changed.

**Comment by BanzaiMan** [comment]
Do you have a build log URL to show that this doesn't work for you? I just tried (https://github.com/BanzaiMan/travis_production_test/blob/578f15c5a56a8f582d55fa15d5578ac14c17848a/.travis.yml) and it [works](https://travis-ci.org/BanzaiMan/travis_production_test/builds/97911082).

**Comment by calidion** [comment]
@BanzaiMan thank you very much.
 Seems due to my script problem, changed to yours and it works.
