### ISSUE TITLE
"chef-solo: command not found" —legacy precise vs. legacy infrastructure

### ISSUE THREAD

**Issue by migurski** [travis-ci/travis-ci#5344]
In [a recent test](https://travis-ci.org/openaddresses/machine/jobs/98044136), I observed a failure I’d not seen before. [An equivalent job from last week](https://travis-ci.org/openaddresses/machine/jobs/96321807) with the same code ran fine. I’ve tested the installation leading to the error `chef-solo: command not found` on a local copy of Ubuntu Precise and found that it worked as expected.

The failed job says “This job ran on our new platform for Legacy Precise builds.” The successful job says “This job ran on our legacy infrastructure.”

Failed job, new legacy precise platform:
https://travis-ci.org/openaddresses/machine/jobs/98044136#L640

Equivalent line from successful job, legacy infrastructure:
https://travis-ci.org/openaddresses/machine/jobs/96321807#L643

**Comment by migurski** [comment]
Following up to confirm that this failure does repeat: https://travis-ci.org/openaddresses/machine/jobs/98051680

**Comment by migurski** [comment]
Following up with some additional details [from a more recent job](https://travis-ci.org/openaddresses/machine/jobs/98262830):

* `chef-solo` [exists ahead of time](https://travis-ci.org/openaddresses/machine/jobs/98262830#L508) at `/usr/bin/chef-solo`
* [It’s a symlink](https://travis-ci.org/openaddresses/machine/jobs/98262830#L648) to `/opt/chefdk/bin/chef-solo`
* `/opt/chefdk/bin/chef-solo` doesn’t exist.

So, this looks like a broken or incomplete chef installation that exists prior to and separate from this testing job.

**Comment by BanzaiMan** [comment]
Sorry for the delay. I see that you disabled Travis on the repository. If you are interested in troubleshooting further, do let us know.

Thanks.

**Comment by migurski** [comment]
Thank you, yes: I found that chef-solo worked on Circle CI.

**Comment by BanzaiMan** [comment]
@migurski Well, I don't have a clear answer for you, and I am not an expert on Chef. However, if you would like to have access to a live VM for debugging purposes, we can arrange that for you. Please email support@travis-ci.com.
