### ISSUE TITLE
container based infrastructure and apache

### ISSUE THREAD

**Issue by DeepDiver1975** [travis-ci/travis-ci#5345]
Is there a recommended way to setup apache in the container based infrastructure?

The usual mechanism as described in https://docs.travis-ci.com/user/languages/php#Apache-%2B-PHP requires sudo.

THX

**Comment by BanzaiMan** [comment]
I believe apache by default binds to a privileged port, which requires `root` access. If you can manage to bind to a port above 1023, and then it should be possible. http://askubuntu.com/questions/694036/apache-as-non-root has some tips, but the instructions assume `sudo` access as well.

**Comment by DeepDiver1975** [comment]
Why is this closed? I still have no solution at hand.

THX

**Comment by BanzaiMan** [comment]
If you need to bind to a privileged port, as I believe Apache's default configuration requires, you need to use `sudo`.

If your tests can cope with talking to a nonstandard port, you will need to tell `httpd` to find the configuration file that you can write to.

https://httpd.apache.org/docs/2.4/invoking.html
`/usr/local/apache2/bin/apachectl -f /usr/local/apache2/conf/httpd.conf`

**Comment by DeepDiver1975** [comment]
If the travis Team whats us devs to primarily use the dicker Infrastructure.
Many CI scenarios include Integration Tests which requires (in case of web apps) a running web Server.

I would be great to have a real suggested solution by the travis Team.

THX

**Comment by drupol** [comment]
I'm also willing to bind a particular port in my tests and I'm unable to do it on Travis.
