### ISSUE TITLE
Question: Exception for 120 minute build timeout

### ISSUE THREAD

**Issue by sedouard** [travis-ci/travis-ci#5346]
Hey There!

We recently picked up Travis CI to run validations on our [Azure resource manager templates community repository](https://github.com/azure/azure-quickstart-templates).

The jobs are very IO bound and the vast majority time is really just spent waiting on Azure to get back to us. We do a variety of mitigations such as only testing deployments of modified files as well as doing our deployments in parallel. Even then we sometimes can hit the timeout See https://travis-ci.org/Azure/azure-quickstart-templates/builds/98048287

Is there any way an exception can be made above the 120 minute mark (which I'm well aware is extremely long but I can't think of any other way around it).

**Comment by BanzaiMan** [comment]
Could you try GCE builds with `sudo: required` to see if it gives you more reliable results?

**Comment by BanzaiMan** [comment]
Closing, as it's become stale.
