### ISSUE TITLE
container (sudo false) linux image: how to get a recent openssl

### ISSUE THREAD

**Issue by ldemailly** [travis-ci/travis-ci#5349]
the openssl coming by default is 
openssl version
OpenSSL 1.0.1 14 Mar 2012

which doesn't work at all for aes128-gcm for instance (EVP_aes_128_gcm())

trying to add
 - openssl-1.0.1f
to packages (
https://github.com/facebook/wdt/commit/46380a367e9f999d66c2472017c280b7d0cbce83
)

yield ( https://travis-ci.org/facebook/wdt/jobs/97595741 ):

Installing APT Packages (BETA)
Disallowing packages: openssl-1.0.1f

How can I get a more recent openssl with my setup ?
https://github.com/facebook/wdt/blob/master/.travis.yml

workaround: I'm building openssl from source in the meantime but that takes a long time unnecessarily

Thanks a lot !
Laurent

**Comment by BanzaiMan** [comment]
http://packages.ubuntu.com/precise/openssl doesn't have this version, so moving to Trusty or compiling source seems a good bet.

**Comment by ldemailly** [comment]
Thanks for the reply @BanzaiMan - that version, according to http://changelogs.ubuntu.com/changelogs/pool/main/o/openssl/openssl_1.0.1-4ubuntu5.32/changelog seems do be from dec 4th 2015

yet "openssl version" shows "OpenSSL 1.0.1 14 Mar 2012"

(while the one I build from source shows "OpenSSL 1.0.1q 3 Dec 2015")

I can't use trusty because it doesn't have even localhost (::1) ipv6 but it seems even precise should have a newer version - should I try some variant of apt-get upgrade ? (which I can't issue directly as I'm trying to stick to the faster/better sudo false)

**Comment by BanzaiMan** [comment]
@ldemailly Does that actually change the version string printed? Does it have the capability you need? The [apt addon](https://docs.travis-ci.com/user/apt) can get you the most up-to-date openssl package for Precise:

```yaml
addons:
  apt:
    packages:
      - openssl
```

but it may be insufficient.

**Comment by BanzaiMan** [comment]
I should add that the container (which runs on EC2) doesn't support IPv6, either.

**Comment by ldemailly** [comment]
@BanzaiMan  that doesn't help (was the first thing I tried) 

https://travis-ci.org/ldemailly/travis_debug/builds/98253386

it seems it does download  http://us.archive.ubuntu.com/ubuntu/ precise-updates/main openssl amd64 1.0.1-4ubuntu5.32
but still gets
$ openssl version
OpenSSL 1.0.1 14 Mar 2012

btw that test build also shows that localhost (::1) ipv6 works fine on container (otherwise many of our tests would fail and that's why I can't move to the other one until it also supports some minimal ::1 support)

but back to openssl -

**Comment by ldemailly** [comment]
I think the problem might be:

$ dpkg -S  /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
libssl1.0.0: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0

yet:
Disallowing packages: libssl

https://travis-ci.org/ldemailly/travis_debug/builds/98255092

**Comment by BanzaiMan** [comment]
My question is still unanswered. Does the `openssl` executable in the 1.0.1-ubuntu5.32 package give the output you are expecting? I believe that the currently installed version on the container is 1.0.1-ubuntu5.21 (https://travis-ci.org/BanzaiMan/travis_production_test/builds/98254900#L114), which, according to http://changelogs.ubuntu.com/changelogs/pool/main/o/openssl/openssl_1.0.1-4ubuntu5.21/changelog, was compiled on 2015-01-09.

Please test the executable from 1.0.1-ubuntu5.32, and see if it suffices. If it does not, you would have to move to Trusty, or compile from source.

As for IPv6, it may be that you just need a loopback device. On this apparently I'm wrong.

**Comment by BanzaiMan** [comment]
`libssl` is a dependency of `openssl`, so it should be up to date when you update the latter.

**Comment by ldemailly** [comment]
well it doesn't seem it is / I can't query it's version (though maybe it's an unrelated issue)

filled
https://github.com/travis-ci/apt-package-whitelist/issues/2124
for that part

I haven't bisected which version of openssl is the first one that works with aes128gcm but I do know that 1.0.1-ubuntu5.21 doesn't and a recent one like 1.0.1e or newer does work

**Comment by ldemailly** [comment]
with the -ubuntu5.32 version aesgcm128 fails - just tried again to be sure:
https://travis-ci.org/facebook/wdt/jobs/98256499

**Comment by BanzaiMan** [comment]
Thanks for checking. Your best bet is to use Trusty or continue to compile from source.

**Comment by ldemailly** [comment]
I can't use trusty because of lack of even loopback ipv6 support there
( https://github.com/travis-ci/travis-ci/issues/4964 )
any chance to get a recent version of openssl (libssl-dev really) whitelisted ?
or even better move this env to ubuntu 14+ (yet not to google app engine until they support basic ipv6)

**Comment by BanzaiMan** [comment]
Since there is no Ubuntu package that meets your requirement, I don't think there is much to do here.

Addition of Trusty to the container is in planned, but no ETA. Sorry.
