### ISSUE TITLE
[precise-gce] `npm install` failing

### ISSUE THREAD

**Issue by dhcole** [travis-ci/travis-ci#5353]
We're seeing errors now on a branch that did not previously have them: https://travis-ci.org/18F/federalist/builds/98410419

```sh
$ npm install 
npm ERR! git rev-list -n1 npm-changes: fatal: ambiguous argument 'npm-changes': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 npm-changes: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 npm-changes: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 npm-changes: 
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.2.3/bin/node" "/home/travis/.nvm/versions/node/v4.2.3/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code 128
npm ERR! Command failed: git rev-list -n1 npm-changes
npm ERR! fatal: ambiguous argument 'npm-changes': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/18F/federalist/npm-debug.log
```

This is a branch off of `master` with no changes, which has previously built without issue: https://travis-ci.org/18F/federalist/builds/97728930

I'm not sure how to begin troubleshooting this. I'd love any advice you have. Thanks!

**Comment by BanzaiMan** [comment]
Where is this output coming from?

```
git rev-list -n1 npm-changes: fatal: ambiguous argument 'npm-changes': unknown revision or path not in the working tree.
```

It seems to me that the issue is with your dependency.

https://github.com/18F/federalist/blob/5a2acbd3454edf52a9965504be93f251c5db3c3c/package.json#L63 suggests to me that your repo is supposed to checkout branch/ref `npm-changes` in this repo: https://github.com/18f/web-design-standards, but none such exists at this time. Did someone in your organization remove it?

**Comment by dhcole** [comment]
Ah, that's totally it. The branch was merged / deleted. I saw `npm` in the branch name and thought the error was actually related to `npm`. Sorry for the false alarm and thanks for the help!
