### ISSUE TITLE
Xcode 7.2 UI Testing problem

### ISSUE THREAD

**Issue by k06a** [travis-ci/travis-ci#5354]
I have two UI tests for iOS application, one of them always fails.
```
✗ testFirst, UI Testing Failure - Failure getting refresh snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error -25215 getting snapshot for element <AXUIElement 0x7fc418471af0> {pid=3288}" UserInfo={NSLocalizedDescription=Error -25215 getting snapshot for element <AXUIElement 0x7fc418471af0> {pid=3288}}
✓ testSecond (29.619 seconds)
```

I have not enough info to detect a problem. Test always success on my Mac with erased simulator.

**Comment by BanzaiMan** [comment]
Do you have a build log URL to show this problem?

**Comment by k06a** [comment]
@BanzaiMan it on travis-ci.com for private project.

**Comment by BanzaiMan** [comment]
@k06a Please email support@travis-ci.com with details. I'll close this one, since we cannot discuss matters privately here.
