### ISSUE TITLE
[precise-gce] why disabling local IPv6?

### ISSUE THREAD

**Issue by sobomax** [travis-ci/travis-ci#5359]
Hi, we've been quite upset by the decision to disable IPv6 on precise builds including all loopback networking, this hinders us quite a lot. Unfortunately we cannot use container-based instances either because as part of some of the tests we run tcpdump and I don't think this is possible to do it with the containers at all. Yes, it was mentioned that IPv6 has had some issues with routing and whatnot, but that should not affect ability to use loopback, should it?

**Comment by BanzaiMan** [comment]
Please see previous discussions, #4964 and #5200.
