### ISSUE TITLE
Unable to use ruby 2.3.0 on OS X images

### ISSUE THREAD

**Issue by segiddins** [travis-ci/travis-ci#5361]
See https://travis-ci.org/CocoaPods/CocoaPods/jobs/98784787 for the full log. Relevant bit is:

```
$ rvm use 2.3.0 --install --binary --fuzzy
ruby-2.3.0 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-2.3.0 do rvm gemset create ' first, or append '--create'.
```

**Comment by BanzaiMan** [comment]
RVM is failing to install statically built binaries. I opened https://github.com/rvm/rvm/issues/3591.

**Comment by abonas** [comment]
Same issue happens on Ubuntu images:
```
$ rvm use 2.3 --install --binary --fuzzy
ruby-2.3 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-2.3 do rvm gemset create ' first, or append '--create'.
The command "rvm use 2.3 --install --binary --fuzzy" failed and exited with 2 during .
```
System info:
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version 3.13.0-29-generic

**Comment by roidrage** [comment]
@abonas That's because our current rvm version doesn't yet know 2.3 as an alias for 2.3.0. You can get it to work by specifying `2.3.0` instead of `2.3`.

**Comment by abonas** [comment]
> @abonas That's because our current rvm version doesn't yet know 2.3 as an alias for 2.3.0. You can get it to work by specifying 2.3.0 instead of 2.3.

thanks for your reply. any eta for 2.3 to be recognized?

**Comment by roidrage** [comment]
Enabling 2.3 to be recognized requires a build environment update, and I don't have an ETA on that yet, sorry.

**Comment by thomasfedb** [comment]
@roidrage Any idea if this is something we'll see in days/weeks/months? We have an issue in @carrierwaveuploader that's blocking on this.

**Comment by segiddins** [comment]
FWIW, even specifying `2.3.0` causes a failure on OS X

**Comment by BanzaiMan** [comment]
@segiddins What error do you see right now?

**Comment by segiddins** [comment]
https://travis-ci.org/CocoaPods/CocoaPods/jobs/98784787

**Comment by segiddins** [comment]
@BanzaiMan any other info I can get you? I recently shipped a 2.3.0 bug because CI couldn't catch it

**Comment by jbender** [comment]
@segiddins while definitely not ideal, you can temporarily work around this by adding the following:

```yaml
 before_install:
  - rvm get stable --auto-dotfiles
  - rvm install 2.3.0
```

**Comment by segiddins** [comment]
@jbender how would I do that with my existing set of different ruby versions?

**Comment by jbender** [comment]
@segiddins haven't done it so take this with a grain of salt, but this might point you in the right direction:

```yaml
matrix:
  include:
    - rvm: ruby-head
      before_install:
        - rvm get stable --auto-dotfiles
        - rvm install 2.3.0
```

You can explicitly add new things into your matrix (see https://docs.travis-ci.com/user/customizing-the-build/#Explicity-Including-Builds)

**Comment by pirj** [comment]
@jbender as per (travis-yaml lint)[http://lint.travis-ci.org/]:

```
in matrix.include section: unexpected key before_install, dropping
```

So it makes sense to put this to the root of yml:
```
before_install:
  - rvm get stable --auto-dotfiles
```

**Comment by jbender** [comment]
@pirj that'll definitely work, but it'll unfortunately add the step to each of your builds, which isn't ideal :neutral_face:

**Comment by kasper** [comment]
@jbender Working around this in `before_install` doesn’t seem to work. Travis CI is trying to resolve the Ruby version even before this. https://travis-ci.org/kasper/phoenix/jobs/117456864

**Comment by jbender** [comment]
@kasper Travis is trying to resolve it based on your `.ruby-version`, which is failing; if your `.ruby-version` specifies a known ruby (say `2.2`), you can then upgrade it in the `before_install`

**Comment by kasper** [comment]
@jbender Right, indeed. Forgot about that, thanks! Obviously this makes working around this issue even more non-ideal.

**Comment by lolgear** [comment]
[same](https://travis-ci.org/lolgear/JWT/builds/151872780)

Version 2.2.5

**Comment by vishrutshah** [comment]
We just noticed this issue in travis-ci as it was working since while. Is this issue resurfaced recently, again? 

https://travis-ci.org/Azure/autorest/builds/165390659

cc: @BanzaiMan

**Comment by BanzaiMan** [comment]
@vishrutshah That job is running on Trusty. I don't think that's related to this issue.
