### ISSUE TITLE
Slow wget downloads from github.com?

### ISSUE THREAD

**Issue by fniephaus** [travis-ci/travis-ci#5362]
Some of our builds are failing, because a simple `wget` download hangs for more than 10m:
https://travis-ci.org/hpi-swa/smalltalkCI/jobs/98858859#L208

Any idea what is causing this problem?

**Comment by BanzaiMan** [comment]
Is this a persistent problem? Recent builds are passing.

**Comment by fniephaus** [comment]
Seems to be working atm. Thanks
