### ISSUE TITLE
Extra double colon in `$PATH` causes $PWD to be included

### ISSUE THREAD

**Issue by ljharb** [travis-ci/travis-ci#5363]
Per @roidrage:

> `$PATH` contains an empty entry on our new infrastructure.
> `home/travis/.gimme/versions/go1.4.2.linux.amd64/bin ​*::*​ /usr/local/phantomjs/bin`

https://travis-ci.org/ljharb/nvm/jobs/98285372 fails, and https://travis-ci.org/ljharb/nvm/builds/98355402 with https://github.com/ljharb/nvm/pull/1 succeeds.

Filing here so I can link to it from a commit.

**Comment by BanzaiMan** [comment]
This appears to happen only on Precise GCE builds.

**Comment by ljharb** [comment]
Any update on this one?

**Comment by joshk** [comment]
Now that we are back from Xmas and NY, we will see what we can do about this.

ping @meatballhat and @solarce

**Comment by ljharb** [comment]
ping :-)

**Comment by ljharb** [comment]
ping again - it's now been over a month since this was reported :-/

**Comment by roidrage** [comment]
@ljharb Sorry, the team has had to focus on other things in the past couple of weeks, and that might continue for a couple more weeks. We'll look into this as we upgrade the affected infrastructure, but I can't make any promises on when that might happen.

Just to leave this here for the record, should someone run into this, there's a known workaround to clean the `$PATH` from double colon entries in the meantime:

```yaml
before_install
  - export PATH=$(echo $PATH | sed 's/::/:/')
```

**Comment by ljharb** [comment]
@roidrage 6 more weeks later :-) just another friendly ping

**Comment by ljharb** [comment]
@roidrage Any update?

**Comment by BanzaiMan** [comment]
I'd fix this with `travis-build` on the fly (until the image is fixed).

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/5326#issuecomment-230570196 for further explanation.

**Comment by BanzaiMan** [comment]
Hmmm. The above may not be true. But the issue is somewhere in the cookbooks.

**Comment by BanzaiMan** [comment]
OK. The fix is out. Cookbooks still needs fixing.

**Comment by meatballhat** [comment]
As it turns out, the current version of the cookbook that writes `/etc/profile.d/pyenv.sh` ensures that `PATH` will be *at least*:

``` bash
PATH="/opt/pyenv/bin:$PATH"
```

The legacy cookbook used to provision Ubuntu Precise images *does* have a bug where `PATH` can end up with `::`, but we are not planning to change any of the Ubuntu Precise images (aside from security updates) prior to retiring them.

After comparing notes with @BanzaiMan, we agree that leaving the colon-subbing code in place at the travis-build level is a reasonable safeguard.
