### ISSUE TITLE
Artifacts uploading does not work for PR builds

### ISSUE THREAD

**Issue by zealisland** [travis-ci/travis-ci#5367]
It seems that Artifacts uploading works for push triggered builds but does not work for pull request triggered builds. More details at http://stackoverflow.com/questions/34402595/travis-ci-artifacts-uploading-does-not-work-for-pr-builds.

**Comment by BanzaiMan** [comment]
This is by design. Since PR builds can be initiated by anyone, we do not upload files anywhere, either via deployment providers or artifacts addon.
