### ISSUE TITLE
Travis CI build errorring on internal keyword functions

### ISSUE THREAD

**Issue by coatless** [travis-ci/travis-ci#5368]
Greetings and Salutations,

While building an R package with Travis CI, I am receiving error messages that I cannot duplicate on a local install of linux, OS X, Windows around help documentation that is coded with the ` @keyword internal`. Specifically, I receive the following warning from travis CI:

`Functions or methods with usage in documentation object 'hidden function here' but not in code:`

This warning then becomes an error while evaluating examples:

e.g. `Error: could not find function "hidden function here"`

and causes the build to fail.

Travis CI report (v1.0.1):

https://travis-ci.org/SMAC-Group/gmwm

CRAN report (v1.0.0):

https://cran.r-project.org/web/checks/check_results_gmwm.html

@craigcitro and @hadley

**Comment by craigcitro** [comment]
Quick question: can you repro the same issue locally if you run with the same flags (in particular, I'm thinking of `--as-cran`)?

**Comment by coatless** [comment]
I have not been able to repro the problem locally using `--as-cran`. The issue seems to be stemming from Travis detecting help files for Rcpp functions that are tagged as internal using roxygen2.

**Comment by craigcitro** [comment]
did you end up getting to the bottom of this?
