### ISSUE TITLE
Build not triggered on push hook

### ISSUE THREAD

**Issue by TiS** [travis-ci/travis-ci#5371]
I have a public repository. Today, a build has not been triggered on it, besides making several changes in the repository (I have added PHP 7.0 to test matrix and so on).

Test hook also does not seem to trigger the build.

https://travis-ci.org/Gendoria/param-converter-bundle

**Comment by BanzaiMan** [comment]
Very strange. Today's commits from this repository are "missing". https://github.com/Gendoria/param-converter-bundle/commits/master

https://github.com/Gendoria/param-converter-bundle/commit/d0802242c412ddeeabac4f3d5fea01162654a35f
https://github.com/Gendoria/param-converter-bundle/commit/38ba54238007c06ab66baa42dd3876018faabdf0
https://github.com/Gendoria/param-converter-bundle/commit/3198df470cd80b638147f143d9e6e969fdca372b
https://github.com/Gendoria/param-converter-bundle/commit/2e63e7f90ea3bc9c3b6305139ca8f9b738740a1f

I've never seen this before. Could you contact GitHub support?

**Comment by TiS** [comment]
Yes, after I submitted this ticket I discovered, that also packagist was not updated. This seems to be a GitHub issue indeed. I'm closing it, then.

Sorry for the trouble, but I'm just startibng creating packages and having good travis score is some help to show that they are good enough :) Thus, I was concerned.
