### ISSUE TITLE
can't use the DC variable when overriding the script tag for a D project

### ISSUE THREAD

**Issue by SingingBush** [travis-ci/travis-ci#5378]
@ibuclaw, @klickverbot and @MartinNowak

I have a D project that builds with dmd, ldc, and gdc. I wanted to override the default _script_ as defined in the documentation: https://docs.travis-ci.com/user/languages/d

```
dub test --compiler=${DC}
```

I just wanted to do a _build_ instead of _test_ (otherwise build fails due to unit tests in dependencies). I've tried both of the following:

```
dub build --compiler=${DC}
```

```
dub build --compiler=$DC
```

neither of them are able to pick up the environment variable. I've also tried just putting `dub build` in the hope that the compiler option would be automatically appended.

Could you let me know what I'm doing wrong here?

**Comment by MartinNowak** [comment]
Not sure what your problem is, your test run works as documented.
https://travis-ci.org/SingingBush/eloquent/jobs/99409626#L167
https://travis-ci.org/SingingBush/eloquent/jobs/99409626#L191

**Comment by SingingBush** [comment]
I was expecting the log to show:

```
dub build --compiler=ldc2
```

In previous builds the DC variable showed up in the log as the actual value when doing the default `dub test` see:
https://travis-ci.org/SingingBush/eloquent/jobs/71218809

**Comment by MartinNowak** [comment]
The bash output prolly shows the original env variables to not leak secure information.
But b/c that's not a problem for the build scripts they can show `bash -x` output.

**Comment by MartinNowak** [comment]
Can be closed as well. The compiler is clearly indicated in the log and the env variables are available.
Actually the log output now contains `dub build --compiler=ldc2`, maybe the site expands safe variables now?
