### ISSUE TITLE
Tests with multiple languages simultaneously

### ISSUE THREAD

**Issue by Sannis** [travis-ci/travis-ci#538]
A far away example: use Travis to test something like MySQL: both server and connectors code. Such project may contain code in different languages in one repository. Is this use-case planned for Travis?

**Comment by jleclanche** [comment]
This is a tad annoying when working on a non-python project which has python 3 scripts, since the default python in travis is 2.7.

**Comment by BanzaiMan** [comment]
@jleclanche You can install `python3`.

**Comment by jleclanche** [comment]
Not in the container-based infrastructure.

**Comment by BanzaiMan** [comment]
@jleclanche http://docs.travis-ci.com/user/apt/ `python3` is whitelisted.

**Comment by ashnazg** [comment]
I was able to get python3 available in container via the `addons` option.

**Comment by fiatjaf** [comment]
Without using sudo, I've managed to **update and run** `node` along with Go: http://entulho.fiatjaf.alhur.es/guias/how-to-use-node-along-with-other-language-on-travis-ci/
