### ISSUE TITLE
Environment variables are not expended into the cache bucket's name when spcified in matrix.include

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#5384]
See https://travis-ci.org/miloyip/rapidjson/jobs/99577035#L245 for example.
This is really hurting performance.

Here's the .travis.yml file:
https://github.com/thedrow/rapidjson/blob/5fb5002e9a154b57490964877aff132eabc44548/.travis.yml

**Comment by BanzaiMan** [comment]
Duplicate of #3023.
