### ISSUE TITLE
Using DOCKER_PASSWORD with `)` character in value fails build

### ISSUE THREAD

**Issue by Stephanvs** [travis-ci/travis-ci#5387]
I ran into an issue where I'm trying to build a docker image.

`.travis.yml`:
```yml
...
before_install:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
...
```

DOCKER_PASSWORD=somethingwhichcontains)character

interesting log parts:
```
Setting environment variables from repository settings
$ export DOCKER_USERNAME=[secure]
$ export DOCKER_PASSWORD=[secure]
/home/travis/build.sh: eval: line 45: syntax error near unexpected token `)'
/home/travis/build.sh: eval: line 45: `export DOCKER_PASSWORD=xxxxxxx)xxxxxxxx'
$ export DOCKER_EMAIL=[secure]
...
$ docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
Password: 
```

Here it just hangs until terminated.

Find log output here: https://gist.github.com/Stephanvs/c9ebb28d1bdf434669bc

**Comment by BanzaiMan** [comment]
This is a variation of #1566. Please escape accordingly. Also see https://docs.travis-ci.com/user/encryption-keys#Note-on-escaping-certain-symbols.
