### ISSUE TITLE
Travis can't find .travis.yml even though it exists

### ISSUE THREAD

**Issue by polybuildr** [travis-ci/travis-ci#5389]
At https://travis-ci.org/felicity-iiith/felicity16-website/builds/99806020, the `.travis.yml` file exists, but Travis says it can't find one. Restarting the build doesn't help either.

**Comment by polybuildr** [comment]
I amended the commit and force pushed and the issue was miraculously resolved. Leaving this issue open, though, because something weird certainly did happen.

**Comment by BanzaiMan** [comment]
We failed to fetch `.travis.yml` for whatever reason. (Sorry, but I don't have much more insight than that.)

Restart doesn't help because of #1485.

I'm going to close this in favor of that issue.
