### ISSUE TITLE
Need to manually install gmp when using BigInt in Crystal

### ISSUE THREAD

**Issue by dkhofer** [travis-ci/travis-ci#5392]
@asterite
@jhass
@waj
@will

As you might guess, I'm playing around with code involving BigInts today.

I found that when running the specs on travis libgmp doesn't seem to get set up automatically, eg this build failed:

https://travis-ci.org/dkhofer/algorithms/builds/99850848

So I had to do this:

https://github.com/dkhofer/algorithms/blob/a3c8c172aa9dbf4da3bc52ded43a8451136f0cab/.travis.yml#L3

It's not the worst thing in the world but thought I would mention it and see if anyone had any suggestions for a better way to include this dependency.  Thanks!

**Comment by jhass** [comment]
I think we should just install it.

**Comment by will** [comment]
Is this a dependency that the apt package should require, or is it
something that we should put into the Travis script?

**Comment by jhass** [comment]
You need it once you write Crystal programs that use the Bignum standard library, which is a GMP binding. The compiler doesn't so it's not a hard dependency on the package.

**Comment by dkhofer** [comment]
:smile:
