### ISSUE TITLE
Preinstall Android NDK

### ISSUE THREAD

**Issue by smarek** [travis-ci/travis-ci#5395]
Hello,

would it be possible, now that you use container based infrastructure, to provide Android NDK (r10e would be great) preinstalled in **/usr/local/android-ndk/** ?

To demonstrate possible overhead this would remove please see start of output in my builds: https://travis-ci.org/smarek/android-unbound-dns/builds/99968489

Travis CI script:
```yaml
before_script:
  - export TERM=dumb
  # Approx. 3 seconds
  - curl -L http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O
  - chmod u+x android-ndk-r10e-linux-x86_64.bin
  # Usually around 1 minute 
  - ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - rm android-ndk-r10e-linux-x86_64.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
  - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
  - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
  - export PATH=$PATH:${ANDROID_NDK_HOME}
  - env
```

Would be simplified to 
```yaml
before_script:
  - export TERM=dumb
  - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
  - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
  # This maybe would be removed, depends on PATH settings in android language
  - export PATH=$PATH:${ANDROID_NDK_HOME}
  - env
```

**Comment by smarek** [comment]
Also I know this was discussed before in #2946 but that was more than year ago, so I guess the situation about available storage space might have changed, is it ? @BanzaiMan

**Comment by BanzaiMan** [comment]
Thanks for taking the time to open this issue. I am sorry to inform you, however, that there have not been any change to warrant reconsideration on this.
