### ISSUE TITLE
Unable to deploy to github

### ISSUE THREAD

**Issue by linearregression** [travis-ci/travis-ci#5397]
TravisCI build link:
https://travis-ci.org/linearregression/travis_elixir_plt_generator/builds/100015119
I am using travis.yml:
https://github.com/linearregression/travis_elixir_plt_generator/blob/23c5cf8531b043506b58dc26079dd1ba9ed1a9dc/.travis.yml
Issue:
1)It looks like before_deploy is never called.
2) A Error of : Skipping a deployment with the npm provider because this is not a tagged commit

It looks like there are a lot of issues related to deploy to git; the git deploy usability is not great either (very opaque, unsure what caused the error)
Can something be done to improve git deploy feature?

**Comment by BanzaiMan** [comment]
https://travis-ci.org/linearregression/travis_elixir_plt_generator/builds/100015119 is not a tagged commit. Please push the tag you want.

**Comment by BanzaiMan** [comment]
The last tagged build I see in https://travis-ci.org/linearregression/travis_elixir_plt_generator/builds is https://travis-ci.org/linearregression/travis_elixir_plt_generator/builds/99897473, but that build has [`tags: false`](https://github.com/linearregression/travis_elixir_plt_generator/blob/8a42b66676534605956c3312e6bf74bdc551b5c4/.travis.yml#L45) so it was [skipped](https://travis-ci.org/linearregression/travis_elixir_plt_generator/jobs/99897486#L302).
