### ISSUE TITLE
Travis not accumulating build exit codes

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#5399]
Build exit codes of intermediate commands from **script:** clause are ignored in the end, only exit code from last command matters. I.e. if some intermediate command fails but last command succeeds the build is still marked as success.

According to https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step the build should be marked as failed if one of commands has failed.

I found that somebody has the same problem: http://stackoverflow.com/questions/31563684/travis-not-accumulating-build-exit-codes

**Comment by BanzaiMan** [comment]
Please provide a link to a job that exhibits this problem.

**Comment by igagis** [comment]
here you go: https://travis-ci.org/igagis/morda/jobs/100024815

**Comment by igagis** [comment]
I found that problem was in my script, I used semicolon instead of && to separate commands
