### ISSUE TITLE
Selenium integration HOWTO

### ISSUE THREAD

**Issue by benel** [travis-ci/travis-ci#540]
It seems that selenium integration was documented at http://about.travis-ci.org/docs/user/selenium-setup/.
Unfortunately the page doesn't exist anymore. 

While I understand the rationale for a [generic page](http://about.travis-ci.org/docs/user/gui-and-headless-browsers/), some people (like me) would hesitate to spend time learning Travis without knowing how difficult it is to integrate existing functional tests.

Is there any plan to document this? Or is there anywhere the old document could be found?

**Comment by atwellpub** [comment]
+1
