### ISSUE TITLE
Nothing is deployed despite Deploying Application says success

### ISSUE THREAD

**Issue by linearregression** [travis-ci/travis-ci#5401]
TravisCI build link:
https://travis-ci.org/linearregression/travis_elixir_plt_generator/jobs/100028532
I am using travis.yml:
https://github.com/linearregression/travis_elixir_plt_generator/blob/8b95c2de3c64a2b7052042a3eb6da2001fb7bb05/.travis.yml
Issue:
No file under:
https://github.com/linearregression/travis_elixir_plt_generator/tree/master/plts

Log:
```
Installing deploy dependencies
Fetching: addressable-2.3.8.gem (100%)
Successfully installed addressable-2.3.8

Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.9.2.gem (100%)
Successfully installed faraday-0.9.2
Fetching: sawyer-0.6.0.gem (100%)
Successfully installed sawyer-0.6.0

Fetching: octokit-4.2.0.gem (100%)
Successfully installed octokit-4.2.0
5 gems installed

Fetching: mime-types-2.99.gem (100%)
Successfully installed mime-types-2.99
1 gem installed
dpl.2

Preparing deploy
Deploying to repo: linearregression/travis_elixir_plt_generator
Current tag is: otp-17.3-elixir-1.0.4
dpl.3

Deploying application
```

**Comment by BanzaiMan** [comment]
[This build](https://travis-ci.org/linearregression/travis_elixir_plt_generator/builds/100028516) is not a tagged build, so it is basically a no-op. This should be more clearly marked.

The Releases deployment creates a GitHub Release, which is found under https://github.com/linearregression/travis_elixir_plt_generator/releases, not the file in the git repository. For that, you need to add the file to the repository, commit and push the commit.
