### ISSUE TITLE
Request to add cancel build on builds history page.

### ISSUE THREAD

**Issue by linearregression** [travis-ci/travis-ci#5402]
When having a build matrix, it will be very helpful to just click o cancel build on one page rather then click on each to cancel.
e.g.
https://travis-ci.org/linearregression/travis_elixir_plt_generator/builds

**Comment by carlad** [comment]
There's an identical request here https://github.com/travis-ci/travis-ci/issues/3395.

I've noted this issue in that one, so will close this one.
