### ISSUE TITLE
Add notes to https://docs.travis-ci.com/user/speeding-up-the-build/

### ISSUE THREAD

**Issue by andrewnicols** [travis-ci/travis-ci#5403]
Just thought that I'd suggest that it may be worth updating the notes on speeding up builds with some more language-specific solutions. I notice that most of the solutions are ruby at present, but one massive change we recently discovered was to disable php-xdebug.

Just removing the php-xdebug configuration during our before_install step showed speed improvements of between 130% and 200%. Our time to run a complete unit test suite on php7 went from 28:42 to 14:45.

There is information on our changes at https://tracker.moodle.org/browse/MDL-52595 and the relevant section of our .travis.yml is available at https://github.com/moodle/moodle/blob/master/.travis.yml#L61

It may be worth adding a generic section to your documentation suggesting disabling the xdebug plugin when:
* you are not generating code coverage reports; or
* you are able to use `phpdbg -qrr phpunit` (possible when testing against php56 and above).

**Comment by BanzaiMan** [comment]
Thanks for the suggestion. The doc site repo is https://github.com/travis-ci/docs-travis-ci-com. We welcome your PR!

**Comment by andrewnicols** [comment]
Thanks @BanzaiMan. I've raised a new pull request (https://github.com/travis-ci/docs-travis-ci-com/pull/465). Closing this issue.
