### ISSUE TITLE
(Look before just closed out) Deploy tag_name is not well-formed although git tag is present and created on git repo

### ISSUE THREAD

**Issue by linearregression** [travis-ci/travis-ci#5404]
This is https://github.com/travis-ci/travis-ci/issues/5400
before_deploy: git fetch --tags to your .travis.yml has already been added before the issue is submitted.
Please look at the build log and travis.yml per that links in issue before just close this out.

**Comment by BanzaiMan** [comment]
I've reopened #5400.
