### ISSUE TITLE
OS X: Allow Nested VMs

### ISSUE THREAD

**Issue by johanneswuerbach** [travis-ci/travis-ci#5413]
We are currently exploring CI for a project using the new OS X `Hypervisor.framework` https://github.com/zchee/docker-machine-driver-xhyve/pull/29

It would be awesome if nested VMs support could be enabled for OS X VMs https://communities.vmware.com/docs/DOC-8970

**Comment by BanzaiMan** [comment]
Closing in favor of #6992.

**Comment by BanzaiMan** [comment]
Or #5738.
