### ISSUE TITLE
libclang1 and libclang1-dev not found

### ISSUE THREAD

**Issue by posix4e** [travis-ci/travis-ci#5415]
I'm trying to build https://github.com/posix4e/elephantpump. I need libclang.so for bindgen. I currently have to sudo apt-get install it as although libclang1-3.7 is an authorized package, it's not found when I try to install it.

**Comment by BanzaiMan** [comment]
If a whitelisted package is not found, you need to add a source. See https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json for the current aliases you can use.
