### ISSUE TITLE
Better workaround for golang private imports from github

### ISSUE THREAD

**Issue by tomdionysus** [travis-ci/travis-ci#5418]
The documentation on [installing dependencies from private repositories in a golang project](https://docs.travis-ci.com/user/languages/go#Installing-Private-Dependencies) describes a workaround that requires adding usernames and tokens into the repo - although this works, there are obvious security problems with the approach.

Using [this article](https://michaelheap.com/golang-how-to-go-get-private-repos/) as a guide we managed to get this working without any tokens in the repo, by ensuring that the SSH key being used by Travis had access to the dependency repos and adding the following to `.travis.yml`:

```
before_install:
  - git config --global url."git@github.com:".insteadOf "https://github.com/"
```

This causes `go get` to use SSH to clone the dependencies, removing the need for explicit token authentication to private repos in github.

If the community has similar success and agrees that this is a better approach, would it be possible to change the documentation to reflect this?

**Comment by kbrock** [comment]
@tomdionysus have you looked at https://docs.travis-ci.com/user/encryption-keys/
It allows you to add secrets to travis that are not exposed

**Comment by tomdionysus** [comment]
@kbrock appreciated, and yes I have seen that - but I'm not logging an issue and asking for help, I've found a working way to solve the problem without putting secrets/tokens into the repo _at all_ and I'm asking the community if it works for them also.

**Comment by kbrock** [comment]
+1 thanks. cool

**Comment by kbrock** [comment]
@tomdionysus huh. I have insteadOf in my global `.gitconfig` - basically to fix the same issue on my dev machine. Thanks for the share. I'm thinking this feature has a number of uses I hadn't considered in the past.

NOTE: I have both http and https in mine.

**Comment by RongxinZhang** [comment]
@tomdionysus Thanks for the suggestion. How would you be able to `go get` a specific branch? Because if you just use `go get` it would only clone master?

**Comment by tomdionysus** [comment]
@RongxinZhang I'm not sure you can do that - `go get` only ever pulls master, regardless of rewriting rules.

**Comment by RongxinZhang** [comment]
@tomdionysus Thanks interesting
Out of curiosity, have you used "relative paths" for your local imports like this:
```go

import (
   "./logger"
   "./key"
)
```

**Comment by tomdionysus** [comment]
No, they're all standard `"github.com/<user>/<repo>"`

**Comment by RongxinZhang** [comment]
Ok. Does that mean everyone who clones your code, must have the same directory structure as you when they develop?
e.g `github.com/rongxin/test`

**Comment by tomdionysus** [comment]
Well, yes, but that's the standard way go imports work: https://github.com/golang/go/wiki/GithubCodeLayout

**Comment by RongxinZhang** [comment]
@tomdionysus Got it. Appreciate the time 👍
