### ISSUE TITLE
Why not allow combined branch and tags condition for deployment conditions?

### ISSUE THREAD

**Issue by patflynn** [travis-ci/travis-ci#5419]
Hi there,

According to [this doc](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A) if you specify `tags: true` then `branch` is ignored.  But for github teams using the [feature branch workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) this means that anybody that pushes a tag to any remote branch triggers a deployment.  

It would be really nice if we could limit deployments to tags made on the master branch. This way the master branch can be protected, while developers can push whatever they want to their feature branch without triggering deployment.

**Comment by joshk** [comment]
Hi @patflynn 

Tags aren't really made against a branch, but a commit ref. This means that we can not diffientiate between a tag you made when you were on the master branch or a development branch.

Do you use a specific naming pattern for the tags?

**Comment by patflynn** [comment]
we don't, but we could.  Is there a way to limit deployments to tags that match a regexp?

**Comment by mwcraig** [comment]
@joshk -- shouldn't something like this return a non-empty value if the commit corresponding to the  tag is on a particular branch, e.g. master:

```bash
git branch --contains $TRAVIS_TAG | grep -l master
```

so that to create a variable with non-zero length only if the commit is a tag and the commit is on a particular branch one can do:

```bash
if [[ "$TRAVIS_TAG" && -n "$(git branch --contains $TRAVIS_TAG | grep '^[\* ] master$' -l)" ]]; then upload_build="true"; else upload_build=; fi
```

@patflynn right now I'm using this to control deploys like this (not extensively debugged, so use at your own risk):

```yaml
on:
    tags: true
    condition: $(git branch --contains $TRAVIS_TAG | grep -l '^[\* ] master$')
```

**Comment by patflynn** [comment]
@joshk Thanks!  

I resigned myself to a workflow without this level of control, as I was persuaded that that's the 'git way'.

**Comment by BanzaiMan** [comment]
I think we can close this.
