### ISSUE TITLE
secure environment variables unavailable if changes on .travis.yml

### ISSUE THREAD

**Issue by fabiocarneiro** [travis-ci/travis-ci#5420]
Can someone confirm if that is true, and if yes can someone point me to the docs where I should be able to find this information or include it?

**Comment by BanzaiMan** [comment]
@fabiocarneiro Could you elaborate on the problem? What did you do, what did you expect to happen, and what actually happened instead? Please provide URLs to relevant builds as well.

**Comment by BanzaiMan** [comment]
Closing since it's become stale.
