### ISSUE TITLE
Travis produces broken npm modules on deploy

### ISSUE THREAD

**Issue by mahnunchik** [travis-ci/travis-ci#5423]
Travis produces broken npm modules on deploy.

Error: https://github.com/npm/npm/issues/11089

```bash
npm ERR! shasum check failed for /tmp/npm-5-a8645995/registry.npmjs.org/telegram-promise/-/telegram-promise-1.0.0.tgz
npm ERR! Expected: 0035da5f882c7108e0b0b1869f593c23c576d677
npm ERR! Actual:   cf436472e47b34649af351c00d6d2d3179ad8c46
npm ERR! From:     https://registry.npmjs.org/telegram-promise/-/telegram-promise-1.0.0.tgz
npm ERR! 
```

Project: https://travis-ci.org/mahnunchik/telegram-promise

**Comment by BanzaiMan** [comment]
Which build shows the problem?

**Comment by mahnunchik** [comment]
Hi @BanzaiMan 

Build log shows that all was right but 2 latest `deploy` [[1](https://travis-ci.org/mahnunchik/telegram-promise/builds/101050794)] [[2](https://travis-ci.org/mahnunchik/telegram-promise/builds/101042961)] to npm are have incorrect shasum.

To reproduce you can try to install:
```bash
$ npm install telegram-promise@1.0.0
or
$ npm install telegram-promise@0.0.2
```

**Comment by mahnunchik** [comment]
https://github.com/npm/npm/issues/11089

**Comment by BanzaiMan** [comment]
We just run `npm publish`. https://github.com/travis-ci/dpl/blob/24be18406f87fd8b65a6f031a69672a39bdf8d18/lib/dpl/provider/npm.rb#L32

I don't know how this can happen. Does it work if you do it locally?

**Comment by BanzaiMan** [comment]
I noticed that in hhttps://travis-ci.org/mahnunchik/telegram-promise/builds/101050794 you are deploying from both jobs in the build matrix. The on that deploys later https://travis-ci.org/mahnunchik/telegram-promise/jobs/101050795#L286 is failing because one already exists.

I seem to recall `npm` misbehaving in this case, but I can't find the reference.

**Comment by mahnunchik** [comment]
* Deploy from my laptop is correct `npm install telegram-promise@0.0.1`
* Two deploys from travis are incorrect =(

> I seem to recall npm misbehaving in this case, but I can't find the reference.

I don't know how to prevent multiple deploys but before it produces correct packages (one build publish, another fails to publish).

I'm trying to investigate the error from npm side https://github.com/npm/npm/issues/11089

**Comment by BanzaiMan** [comment]
Try uploading version 0.0.1 again from your machine. If my theory is correct, `npm` will try, but errors out with status 403, and subsequently the install of that version will fail because of the checksum error.

**Comment by BanzaiMan** [comment]
(If you want to keep version 0.0.1, then you can try a bogus version, say 0.0.3.

**Comment by mahnunchik** [comment]
telegram-promise@0.0.3 was published correctly
```
$ npm install telegram-promise@0.0.3
```
Works without any errors.

**Comment by BanzaiMan** [comment]
Did you upload 0.0.3 twice?

**Comment by mahnunchik** [comment]
No, once. npm disallow more than one publication of specified version of package.

**Comment by BanzaiMan** [comment]
That is exactly the point I'm trying to make. Your build ends up running `npm publish` twice. The second fails. My theory is that this action corrupts the checksum.

To restrict deployment, please read https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A.

**Comment by mahnunchik** [comment]
Hi @BanzaiMan

Parallel publishing of module from travis make the broken packages in the npm repository. Shasum of this modules is incorrect.

I've created test repository to reproduce this error:
* GitHub repo https://github.com/mahnunchik/test-travis-npm-deploy-shasum-check-failed
* Travis build https://travis-ci.org/mahnunchik/test-travis-npm-deploy-shasum-check-failed/
* NPM package https://www.npmjs.com/package/test-travis-npm-deploy-shasum-check-failed

The build which produced package with incorrect shasum: https://travis-ci.org/mahnunchik/test-travis-npm-deploy-shasum-check-failed/builds/101228494

```bash
npm ERR! shasum check failed for /tmp/npm-2538-55d80a6e/registry.npmjs.org/test-travis-npm-deploy-shasum-check-failed/-/test-travis-npm-deploy-shasum-check-failed-1.0.3.tgz
npm ERR! Expected: 5bcd4ade3acef4f051cab4048a723004fe1fab62
npm ERR! Actual:   9aac2b6298da4c4d9978baa393905b91435f29d5
npm ERR! From:     https://registry.npmjs.org/test-travis-npm-deploy-shasum-check-failed/-/test-travis-npm-deploy-shasum-check-failed-1.0.3.tgz
```

**Comment by BanzaiMan** [comment]
Thanks for the follow up. I reviewed the code involved to see if I can reason about it, but I have not been able to. Ultimately, the only code we run on deploying is:

```
env NPM_API_KEY=#{option(:api_key)} npm publish
```

Currently it is not possible to coordinate deployments among jobs in a matrix. It seems to me that the best solution at the moment is to document it and encourage users to use conditional deployment.

It would be instructive to understand when and how npm module checksum is computed and stored.

**Comment by mahnunchik** [comment]
> Currently it is not possible to coordinate deployments among jobs in a matrix. It seems to me that the best solution at the moment is to document it and encourage users to use conditional deployment.

* I would like to have it to be documented in `main` doc of npm releasing: https://docs.travis-ci.com/user/deployment/npm
* Also it would be really helpful to have `travis setup npm` with right `conditional` of deployment.

**Comment by BanzaiMan** [comment]
Ah. It is #4738. It is documented in https://docs.travis-ci.com/user/deployment/npm#Conditional-releases.

> A deployment issue is reported when multiple attempts are made. We recommend deploying from only one job with Conditional Releases with on:.
