### ISSUE TITLE
URL for docs about container-based infrastructure uses http://, not https://

### ISSUE THREAD

**Issue by domenic** [travis-ci/travis-ci#5425]
> This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
>
> If you require sudo, add 'sudo: required' to your .travis.yml
>
> See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

Last line should be HTTPS :)

**Comment by BanzaiMan** [comment]
Good catch! (Do note that it will be redirected to https.)
