### ISSUE TITLE
Kerl missing from `language: erlang`

### ISSUE THREAD

**Issue by tsloughter** [travis-ci/travis-ci#5428]
I've just started having this failure on a private repo today that had been working:

```
18.1 is not installed. Downloading and installing pre-build binary.
$ kerl update releases
No command 'kerl' found, did you mean:
 Command 'erl' from package 'erlang-base' (main)
 Command 'erl' from package 'erlang-base-hipe' (universe)
 Command 'perl' from package 'perl-base' (main)
kerl: command not found
```

**Comment by BanzaiMan** [comment]
@tsloughter As I mentioned in the support ticket, this is due to the build being sent to the Trusty queue, which currently lacks the capability to run Erlang. We will be adding more capability, but in the meantime, please avoid Trusty.

**Comment by tsloughter** [comment]
Ok. It was the best way I could find to use Postgres 9.5 and Postgis 2.2. It seems I may have to go all the way back to the old infrastructure with `sudo` so I can install any packages?

**Comment by BanzaiMan** [comment]
I can look into installing `kerl` on demand as a stop-gap.

**Comment by tsloughter** [comment]
Sounds good, thanks.

**Comment by BanzaiMan** [comment]
Hi, @tsloughter, I've been reminded that there is a more recent image that should have Erlang stuff. Could you add:

```yaml
group: edge
```

at the top level of your `.travis.yml` to see if that suffices?

**Comment by tsloughter** [comment]
That did it, thanks!

**Comment by tsloughter** [comment]
@BanzaiMan I can open another issue if need be, but just wanted to ask quickly about the fact that with `group: edge` riak isn't found: `riak: unrecognized service`

Do I need to move riak to a docker container instead of using `service: riak`?

**Comment by BanzaiMan** [comment]
@tsloughter Please open a separate issue. It should be there.
