### ISSUE TITLE
Failing on purpose in script

### ISSUE THREAD

**Issue by IngwiePhoenix** [travis-ci/travis-ci#5429]
I want to test functionality of a scripting language standard library. Since there is no good testsuite for it just yet, I'll have to work around this for a while. Therefore, i would like to fail on purpose. Basically:

```bash
./program
if [ "$?" == 2 ]; then
    exit 0; # Success
else
    exit 1; # failure
fi
```

Do I need an extra `.sh` file, or can I just put it in a single line in my travis file?

**Comment by BanzaiMan** [comment]
If you want to mark a build as a failure, you can use `false` (or any other command with a non-zero exit status) in the `script` section. See https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step.
