### ISSUE TITLE
No npm deployment becasue Travis doesn't see the tagged commit

### ISSUE THREAD

**Issue by ddewaele** [travis-ci/travis-ci#5433]
I can't get the auto npm deploy on tagged commits to work on my [travis builds](https://travis-ci.org/ddewaele/web-gpio-react) for my [github repo](https://github.com/ddewaele/web-gpio-react)

I keep getting the error : ```Skipping a deployment with the npm provider because this is not a tagged commit```

An [example travis build](https://travis-ci.org/ddewaele/web-gpio-react/builds/101344262) containing a tag is this : https://github.com/ddewaele/web-gpio-react/commit/169e4ee1064086b982d0fa86dca3f60c42c77502 

It contains a new tag that was generated when I release a new version like this :

```
git add .travis.yml 
git commit -m "travis config change"
[master b868ed4] travis config change
 1 file changed, 1 deletion(-)

npm version 0.0.7 -m "Upgrade to %s"
v0.0.7

git push

Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 718 bytes | 0 bytes/s, done.
Total 7 (delta 4), reused 0 (delta 0)
To git@github.com:ddewaele/web-gpio-react.git
   7ab8bf3..169e4ee  master -> master
 * [new tag]         v0.0.7 -> v0.0.7

git rev-list -n 1 v0.0.7
169e4ee1064086b982d0fa86dca3f60c42c77502
```

Any ideas ?

**Comment by BanzaiMan** [comment]
You are excluding builds to only the `master` branch. https://github.com/ddewaele/web-gpio-react/blob/v0.0.7/.travis.yml#L12-L14 You can see this on https://travis-ci.org/ddewaele/web-gpio-react/requests.

**Comment by ddewaele** [comment]
Thx .,.. appreciate it ... assumed that this master branch config was not related to the deployer config. Assumed Travis would do a pull, see the new tag and build that tag.

I specified the master branch because I only want to build from that branch (and no other dev branches), and assumed that tags put on commit ids from the master branch would get picked up.

Is it mentioned somewhere in the docs ? I looked at [NPM deployment](https://docs.travis-ci.com/user/deployment/npm) and [Building-Specific-Branches](https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches)

**Comment by ddewaele** [comment]
@BanzaiMan : Also noticed that despite specifying ```branch: master``` in the travis deploy section, this [alpha build](https://travis-ci.org/ddewaele/web-gpio-react/builds/101388450) triggered by a commit on a dev branch also resulted in a deploy to npmjs

So still a bit confused. Would like Travis to only deploy to npmjs when something is tagged on the master branch. Alpha / Beta versions built on dev branches should not result in a deploy to npmjs. Is such a setup possible ?

(If you prefer I put this on SO instead of this issue feel free. I'll post the link then.)

Thx.

**Comment by BanzaiMan** [comment]
@ddewaele https://travis-ci.org/ddewaele/web-gpio-react/builds/101388450 triggered the build because you have [`tags: true`](https://github.com/ddewaele/web-gpio-react/blob/531f686312b83823aa729dd38848774acf1c7019/.travis.yml#L19). As documented in https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A, this negates the `branch` condition.
