### ISSUE TITLE
build.sh uses unbound variables, bash set -u results in fail

### ISSUE THREAD

**Issue by zer0main** [travis-ci/travis-ci#5434]
Invoking `set -u` from `.travis.yml` or from a shell script which is `source`d from `.travis.yml` results in `unbound variable` error.
https://travis-ci.org/zer0main/battleship/jobs/100161553#L327

**Comment by BanzaiMan** [comment]
What is your motivation for using this option?

**Comment by zer0main** [comment]
I use it to catch errors in my own scripts. This bug can be fixed: http://stackoverflow.com/a/11362364

**Comment by corydodt** [comment]
Still happening almost two years later. This is trivial to fix. Travis, any updates?

**Comment by edmorley** [comment]
catting `travis_stages` shows the failing line to be the `if [[ -n $secure ...` one below:

```sh
  if [[ -n "$retry" ]]; then
    travis_retry eval "$cmd $secure"
    result=$?
  else
    if [[ -n "$secure" ]]; then
      eval "$cmd $secure" 2>/dev/null
    else
      eval "$cmd $secure"
    fi
    result=$?
    if [[ -n $secure && $result -ne 0 ]]; then
      echo -e "${ANSI_RED}The previous command failed, possibly due to a malformed secure environment variable.${ANSI_CLEAR}
${ANSI_RED}Please be sure to escape special characters such as ' ' and '$'.${ANSI_CLEAR}
${ANSI_RED}For more information, see https://docs.travis-ci.com/user/encryption-keys.${ANSI_CLEAR}"
    fi
  fi
```

Even if this instance was changed to use `-v` (supported as of bash >= 4.2) or else `"${secure-}"` , there appear to be many other instances throughout.

Perhaps `travis_cmd()` should `set +eu` after the `eval` to restore the shell options after each command that is run? (A bit like `travis_terminate()` already does a `set +e`)

The source is here:
https://github.com/travis-ci/travis-build/blob/f2763a4e8bff3ad26c260a2da18221148072d1df/lib/travis/build/templates/header.sh#L64-L79

**Comment by edmorley** [comment]
Still applies

**Comment by webknjaz** [comment]
Still there: https://travis-ci.org/webknjaz/get-pip/jobs/368184942#L441

**Comment by edmorley** [comment]
> Still applies

**Comment by webknjaz** [comment]
Workaround: do `set +u` in the end of script

**Comment by ArlindKadra** [comment]
Thanks, it works.

**Comment by BanzaiMan** [comment]
I'm closing this for now. I understand the usefulness for this flag, but at the moment the generated build scripts will rely on `nounset` option not being set. Please add `set +u` when your customization makes way to the generated portions.
