### ISSUE TITLE
Python 3.5 missing on Python 3.5 build

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#5436]
Here is a sample build ( https://travis-ci.org/numpy/numpy/jobs/101598744 ). This normally works, but appears to now be failing. See screenshot below.

<img width="1554" alt="screen shot 2016-01-11 at 10 13 09" src="https://cloud.githubusercontent.com/assets/3019665/12237285/fb095e98-b84b-11e5-9238-2b9f5fb380de.png">

**Comment by BanzaiMan** [comment]
Most likely culprit is the network. Please try restarting it.

**Comment by jakirkham** [comment]
Yeah, I commit amended and force pushed, which resulted in a rebuild that didn't encounter this. Just wanted to share as I thought it was strange enough that I felt someone at Travis should know.
