### ISSUE TITLE
if export fails it will print the value

### ISSUE THREAD

**Issue by jchauncey** [travis-ci/travis-ci#5437]
I noticed this morning that on one of my builds if the export fails (with non 0 exit code) it will print out the value of the environment variable. If this value is a password for a public build that can be troublesome. Has anyone else seen this or know why it might be happening?

**Comment by jchauncey** [comment]
I should say that this is for a project that is marked as `language: bash`

**Comment by BanzaiMan** [comment]
Perhaps you ended up running `export` by itself, which will print all the environment variables. There is no way we can prevent that.

**Comment by jchauncey** [comment]
I have 1 export statement and thats in a script that occurs later in the build. This is literally the first thing that happens when the build starts - 

```
Setting environment variables from repository settings
$ export QUAY_USERNAME=[secure]
$ export QUAY_PASSWORD=[secure]
$ export QUAY_EMAIL=[secure]
$ export DOCKER_EMAIL=[secure]
$ export DOCKER_USERNAME=[secure]
$ export DOCKER_PASSWORD=[secure]
$ export FOO=[secure]
The command "export FOO=foo" exited with 0.
```

I added the FOO value so it would print that instead of the docker hub password

**Comment by BanzaiMan** [comment]
Is there a reproduction we can look at? (If the information is still sensitive, please email support@travis-ci.com.)

**Comment by jchauncey** [comment]
Alright I emailed support with the build (ive removed all the logs but would like to keep the build secret for now) will definitely update the issue with the resolution =)

**Comment by BanzaiMan** [comment]
Resolved by https://github.com/travis-ci/travis-build/pull/589.
