### ISSUE TITLE
Error /home/travis/build.sh: line 112:  2312 Terminated

### ISSUE THREAD

**Issue by skirpichev** [travis-ci/travis-ci#5441]
I see this strange message at the end of pip install phase
```
install:
  - travis_wait pip install .[exports,plot,interactive,gmpy]
```
of my build script:
```
...
Successfully installed Theano-0.7.0 cycler-0.9.0 decorator-4.0.6 gmpy-1.17 ipython-4.0.1 ipython-genutils-0.1.0 matplotlib-1.5.1 mpmath-0.19 multipledispatch-0.4.8 path.py-8.1.2 pexpect-4.0.1 pickleshare-0.5 ptyprocess-0.5 pyparsing-2.0.7 python-dateutil-2.4.2 pytz-2015.7 scipy-0.16.1 simplegeneric-0.8.1 six-1.10.0 strategies-0.2.3 sympy-0.7.7.dev0 toolz-0.7.4 traitlets-4.0.0
/home/travis/build.sh: line 112:  2312 Terminated              travis_jigger $! $timeout $cmd
```

An example build:
https://api.travis-ci.org/jobs/101721477/log.txt?deansi=true

**Comment by BanzaiMan** [comment]
It is a side effect of `travis_wait`.

**Comment by skirpichev** [comment]
On Tue, Jan 12, 2016 at 07:21:56AM -0800, Hiro Asari wrote:
>    It is a side effect of travis_wait.

The end of the last string looks just like an unescaped shell
command.  So, I expect, there is still something wrong.

**Comment by BanzaiMan** [comment]
`travis_wait` works by sending the process to the background and capturing STDOUT and STDERR to a file, which will be displayed when the function ends. The output `Terminated …` comes from STDERR here, which I do not think can be separated from the STDERR of the command `travis_wait` runs.

Perhaps I missed something obvious. I welcome your PR to improve this.

You can look at the implementation here: https://github.com/travis-ci/travis-build/blob/31f420f7e70d2d13376e00ca9a519815185940c1/lib/travis/build/templates/header.sh#L108-L145
