### ISSUE TITLE
Previously working encrypted files doesn't work anymore

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#5442]
We have set up encryption of our ssh key using `travis encrypt-file` previously and it worked for us for a long time. It still worked for [our build on 2015-12-03](https://travis-ci.org/HaxeFoundation/haxe.org/builds/94416072).

Until recently, [our build on 2015-01-06](https://travis-ci.org/HaxeFoundation/haxe.org/builds/100593015) failed with error:
```
bad decrypt
140170419500704:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:539:
Agent pid 2405
Enter passphrase for deploy_key:
```

Has the encryption method changed or something?

**Comment by BanzaiMan** [comment]
@andyli You cannot run `encrypt-file` multiple times. Only the last one will be valid. See https://docs.travis-ci.com/user/encrypting-files#Encrypting-multiple-files.

**Comment by andyli** [comment]
I _think_ we've only encrypted one file, named "deploy_key". Or have we accidentally encrypted multiple times?

**Comment by BanzaiMan** [comment]
@andyli Hmm. How did you (or anyone with the push access to this repo) invoke the command?

**Comment by andyli** [comment]
We're not sure... Anyway, we're re-encrypted the key and it works fine now. Thanks!
