### ISSUE TITLE
Travis CI - docker: unrecognized service

### ISSUE THREAD

**Issue by rolivieri** [travis-ci/travis-ci#5444]
I am using Travis CI (enterprise) and followed the instructions on this URL https://docs.travis-ci.com/user/docker/ to use docker. Unfortunately, every time I run a build, I get the same errors:

docker: unrecognized service
docker: command not found

My travis.yml file follows exactly the one on the tutorial. I saw other posts here about the same issue but no resolution so far (https://github.com/travis-ci/travis-ci/issues/5390, https://github.com/travis-ci/travis-ci/issues/4395).

Is there a work around for this issue?

**Comment by BanzaiMan** [comment]
@rolivieri Sorry to hear about this issue. Since yours is an issue with Enterprise, we will continue our discussion on the support ticket. Thank you.

**Comment by vsinha** [comment]
Are there any solutions to this? I'm having the same issue (waiting on enterprise support to reply)

**Comment by mirague** [comment]
Same issues here, what's the status?

**Comment by BanzaiMan** [comment]
@mirague If it is a Travis Enterprise installation, please send us email.
