### ISSUE TITLE
R package builds erroneously requiring readr

### ISSUE THREAD

**Issue by tomschenkjr** [travis-ci/travis-ci#5447]
For some reason, builds of [RSocrata](https://github.com/Chicago/RSocrata) are resulting in unit tests that returns an error due to [readr not being installed](https://travis-ci.org/Chicago/RSocrata/builds/101982791#L2744) ([plain text](https://api.travis-ci.org/jobs/101982797/log.txt?deansi=true)). This error seems to only occur on Travis. The same build in AppVeyor (Windows) [does not present this error](https://ci.appveyor.com/project/cityofchicago/rsocrata/build/1.0.97#L261). 

Also ran the build process (`--as-cran`) on an Ubuntu box, but did not get an error. Additional local builds on Windows and MacOS also did not present an issue.

So, I think I've narrowed it to Travis as a factor, but cannot see where this is being introduced. Might there be dependencies being introduced during the Travis build that might lead to this error?

/cc @craigcitro @hadley @marks

**Comment by jimhester** [comment]
In your [.travis.yml](https://github.com/Chicago/RSocrata/blob/b681661d7d3eee5706dca7d4367f704555499741/.travis.yml#L12) you are installing the development version of httr.

Which uses readr to parse tsv and csv files (https://github.com/hadley/httr/blob/f0fc278b96e8814c3527bb7a6ada19522d297df0/R/content-parse.r#L111-L123)

However you are not installing the devel versions in your [appveyor.yml](https://github.com/Chicago/RSocrata/blob/dev/appveyor.yml)

**Comment by tomschenkjr** [comment]
Ah, did not do a thorough enough job on my review. Apologies and thanks.
