### ISSUE TITLE
Cache does not work for iOS project (language: objective-c/swift)

### ISSUE THREAD

**Issue by NicholasTD07** [travis-ci/travis-ci#5450]
* I am using the `.org` site
* This is my repo: https://github.com/NicholasTD07/SwiftDailyAPI
* No matter which config of the following for `cache` I use, Travis just does NOT cache
  * Nothing about caching in log(ging)

**My current `.travis.yml` file**
```
language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
cache: cocoapods
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace SwiftDailyAPI.xcworkspace -scheme "SwiftDailyAPI-iOS" -destination "OS=9.2,name=iPhone 6s Plus" test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

Log: https://travis-ci.org/NicholasTD07/SwiftDailyAPI/builds/102064284

Also tried to set the `cache` section to the following 3 from #4615 , still did not work.
```
# 1
cache:
  cocoapods: true
```
Log: https://travis-ci.org/NicholasTD07/SwiftDailyAPI/builds/102071034

```
# 2
cache:
  edge: true
  cocoapods: true
```

Log: https://travis-ci.org/NicholasTD07/SwiftDailyAPI/builds/102087642

```
# 3
cache:
  directories:
    - Pods
# Build failed but not relevant to this issue
```
Log: https://travis-ci.org/NicholasTD07/SwiftDailyAPI/builds/102091702

Spent almost a day on this issue trying to get it working. :sob: :sob:

**Comment by BanzaiMan** [comment]
Sorry about the trouble you had. As you found out, caching is not enabled on .org platforms except for the container-based one. This is documented in https://docs.travis-ci.com/user/caching:

> The features described here are currently only available for private repositories on travis-ci.com and our new container-based infrastructure.

We have discussed this internally to make it better, but we do not have ETA at this time.

I am closing this for now. We will make an announcement when this changes in [our blog](https://blog.travis-ci.com/).

Thank you.

**Comment by NicholasTD07** [comment]
@BanzaiMan Thank you for getting back so fast! I guess that, with all the titles being so big and obvious, that line, even thought it's bold (still tiny) just got skipped by me while I was looking/skimming for the section talking about caching for CocoaPods.

Is it possible to make that quoted line even more obvious so people who's new to travis-ci.org/com would notice the first time?
