### ISSUE TITLE
MySQL db reused across docker containers?

### ISSUE THREAD

**Issue by vladikoff** [travis-ci/travis-ci#5452]
Hello! 

Is it possible that the mysql db / connection would be reused across environments in some cases? Which could lead to MySQL errors.

See this build for example: https://travis-ci.org/mozilla/fxa-oauth-server/builds/100226840
The failing env throws a 

```
fxa-oauth-server.db.mysql.ERROR: updateDbSchema Error: ER_DUP_FIELDNAME: Duplicate column name 'authAt'
```

Or maybe the db is not cleaned up after the container is done running the tests and if reused it will cause issues?

Might be related: https://github.com/travis-ci/travis-ci/issues/3758 - `node_modules` also not cleaned up after the container is done and reused on a fresh container?

**Comment by BanzaiMan** [comment]
We shut down containers after each job. Do your tests perhaps have race condition to create columns?
