### ISSUE TITLE
Cache should take OS information (os and release name) into consideration 

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5460]
This is a variation of https://github.com/travis-ci/travis-ci/issues/4393.

With a build matrix, it is possible to have different OSes and releases. Caches should take these vital information into consideration.

**Comment by h-2** [comment]
Does this mean that currently it is not possible to use ccache at all if I have a amtrix with different compilers / operating systems?

Thanks for your help!

**Comment by BanzaiMan** [comment]
@h-2 It is not impossible to use, but it is most likely ineffective, unless there are other considerations to vary the cache name (e.g., language runtime version).

**Comment by h-2** [comment]
@BanzaiMan I have setup individual directories for each configuration and create symbolic links before the build. Still there is **no** caching taking place at all. The ccache is always empty and also accessing the cache from the travis web interface yields nothing.
Could you have a look at it?
https://travis-ci.org/seqan/lambda/builds
https://github.com/seqan/lambda/blob/master/.travis.yml

Thank you!

**Comment by BanzaiMan** [comment]
@h-2 Sorry, but that has nothing to do with this issue. Your cache directive is wrong. https://github.com/seqan/lambda/blob/89afb39f3388671bcecdaa1bc2d83cac5470c52f/.travis.yml#L4-L6

**Comment by h-2** [comment]
@BanzaiMan why is it wrong? I use the ccache folder (no .) and create subfolders for the different setups, then I link these subfolders to ${HOME}/.ccache : https://github.com/seqan/lambda/blob/master/.travis.yml#L79
Or is the syntax wrong?

Sorry for hijacking the thread, but I got no response on mail-support, yet...

**Comment by BanzaiMan** [comment]
@h-2 https://docs.travis-ci.com/user/caching/#With-a-custom-install-step

```yaml
cache:
  directories:
    - directory1
```

**Comment by BanzaiMan** [comment]
Just a heads up: I deployed a fix to production about 10 minutes ago. Please observe how your caches are behaving, and report issues if you see any.

**Comment by BanzaiMan** [comment]
This has been deployed and documented.
