### ISSUE TITLE
Crystal build is no longer working

### ISSUE THREAD

**Issue by miketheman** [travis-ci/travis-ci#5461]
From: https://travis-ci.org/miketheman/statsd.cr/builds/102263107
Full stack: https://gist.github.com/miketheman/0b5d3cb891f556add9fe

It appears the step to install a package from the repo is no longer working.

Tagging @asterite, @jhass, @waj and @will

**Comment by miketheman** [comment]
Seems like https://github.com/travis-ci/travis-ci/issues/4880 has come back.

**Comment by jhass** [comment]
Indeed
```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.rSrgMJInvR --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54

gpg: requesting key 7CC06B54 from hkp server keys.gnupg.net

?: keys.gnupg.net: Host not found

gpgkeys: HTTP fetch error 7: couldn't connect: Success

gpg: no valid OpenPGP data found.

gpg: Total number processed: 0
```

I see nothing we as maintainers of a community supported language can do about these, if anything it's something for the folks running the infrastructure to look at. Though I'd even be able to understand if it's declared as temporary fluke, please try again.

**Comment by miketheman** [comment]
@jhass Indeed - I was following the directives in the output.

Issuing a rebuild right now passes, so it does seem focused around the keyserver availability - something that a web search for similar error messages turns up a plethora of results.

keys.gnupg.net is a CNAME to `pool.sks-keyservers.net.` - which is a pool of nodes - see https://sks-keyservers.net/ for details.

Any given server response has a TTL of 60 seconds, so it's entirely possible that an overloaded/erroring keyserver is still around during a particular build's lookup.

The addition of `--verbose` to the gpg command should output the hostname of the server resolved - this may be helpful in further debugging a keyserver issue - I'm not certain where one would affect this change.

One idea is a bash "retry once after 60 seconds" might work here - as after a window of 60 seconds you should resolve the DNS record to a new pool member.

Another idea is that if the GPG public key file is made available on dist.crystal-lang.org somewhere, we may do something like `gpg --fetch-key http://dist.crystal-lang.org/packages@crystal.gpg.key` or such, and bypass the keyserver altogether.

**Comment by jhass** [comment]
Yes, the latter is entirely possible, but then defeats the entire point of signing the packages in the first place when pulling it from the same possibly compromised location, we would at least need to verify the fingerprint afterwards.

**Comment by BanzaiMan** [comment]
So, the error occurs whenever we are handed an unreachable host from the pool?

**Comment by miketheman** [comment]
@BanzaiMan That's what I've understood so far, correct.

**Comment by BanzaiMan** [comment]
If the pool gives us a lemon, what can we do? Is a retry meaningful?

**Comment by jhass** [comment]
Only if we can bust the DNS cache I'd say.

**Comment by miketheman** [comment]
So I've been going back and forth, and since there seems to be a [complicated process in getting a package/repo "blessed" by Travis](https://github.com/travis-ci/apt-package-whitelist#package-approval-process) to be included in an image, I wonder if getting the singing key would be simpler - so that when using the repo, there's no need to call the keyserver, since its availability is spotty.

**Comment by jhass** [comment]
So, one alternative would be something like https://github.com/jhass/travis-build/commit/c4408b25d81aed3836045071b28abd039b869c52. But I'm not sure I feel much better about that approach.

**Comment by miketheman** [comment]
@jhass thanks for your efforts on making the build system more resilient!
I found that the merged change caused a different failure mode, and commented: https://github.com/travis-ci/travis-build/pull/754#issuecomment-230286390

**Comment by BanzaiMan** [comment]
I think this can be closed now.
