### ISSUE TITLE
Build fails due to package installation error

### ISSUE THREAD

**Issue by nalimilan** [travis-ci/travis-ci#5462]
Since yesterday my builds fail due to a package installation error:
```
Setting up r-base-core (3.2.3-3precise0) ...

Creating config file /etc/R/Renviron with new version

/var/lib/dpkg/info/r-base-core.postinst: 57: /var/lib/dpkg/info/r-base-core.postinst: mktexlsr: not found
```
https://travis-ci.org/nalimilan/logmult/builds/102293330

Any ideas?

**Comment by BanzaiMan** [comment]
Paging @craigcitro @hadley @jimhester

**Comment by psolaimani** [comment]
i have the same issue (https://travis-ci.org/psolaimani/BenchmarkR/builds/102361268)

**Comment by dbailleul** [comment]
Same here: https://travis-ci.org/dbailleul/RClone/builds/102365375
With a nice "The command "sudo apt-get install -y --no-install-recommends r-base-dev r-recommended qpdf" failed and exited with 100 during ."

**Comment by jimhester** [comment]
This seems to be due to a change in the Debian package, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810963

@eddelbuettel is there anything we need to do or will your fix just propagate in time?

**Comment by psolaimani** [comment]
is it possible to choose for an earlier version of R? till the fix has been propagated...

**Comment by eddelbuettel** [comment]
The fix is in (since last eve) and we're waiting for the build.
https://launchpad.net/~marutter/+archive/ubuntu/rrutter/+build/8847574

@psolaimani Of course. *Everything* is *possible* but not automatic. You "merely" need to point all the runs in the world to a different repo.

**Comment by jimhester** [comment]
Thanks Dirk.

**Comment by psolaimani** [comment]
Thanks Jim for following up on this and Dirk for the fix. 

@jimhester: What struck me in Travis is the amount of freedom you get to adjust the build environment. I'm curious if one can also choose the R version to be installed, or is that (as Dirk pointed out) not possible?

**Comment by eddelbuettel** [comment]
@psolaimani You still misunderstand; yes you can; people have done and do it; @gaborcsardi even has it canned.

**Comment by jimhester** [comment]
Currently the native r travis does not let you use older versions of R. But as Dirk says it is entirely possible to do so (see https://github.com/metacran/r-builder for an example implementation).

Supporting multiple versions of R is one of the things I am planning on adding to the native r-travis soon, along with a number of other changes to allow using it on Travis' container based build system.

**Comment by gvegayon** [comment]
Fingers crossed!

**Comment by eddelbuettel** [comment]
Still in the queue.  Would be nice if we could tell Launchpad that we really *really* **really** want this built .

**Comment by eddelbuettel** [comment]
The package has been built for Ubuntu precise, and I had my first Travis run use it.

**Comment by jimhester** [comment]
Yep builds are working normally again, this can be closed.

**Comment by BanzaiMan** [comment]
Thank you!
