### ISSUE TITLE
Feature Request: add Consul to available Database Services

### ISSUE THREAD

**Issue by HariSekhon** [travis-ci/travis-ci#5463]
Feature request to add Consul (by HashiCorp) to the list of available database services.

**Comment by dentarg** [comment]
Still no Consul @ https://docs.travis-ci.com/user/database-setup/

**Comment by BanzaiMan** [comment]
We are happy to review your PR (see, for example, one for [RethinkDB](https://github.com/travis-ci/travis-build/pull/676)). But for now, I'm closing this ticket, as it is not something we can look at in the near future.
