### ISSUE TITLE
Multiple Accounts Seem to have been Created

### ISSUE THREAD

**Issue by tam5** [travis-ci/travis-ci#5465]
I recently got started with Travis with two open-source projects with the basic free account. Then, I wanted to use Travis for a private project I have here on GitHub. I clicked start trial, and I got the free educational version as I am a student.

The problem is that I seem to have two separate accounts, a free account, plus my educational account, not one single account. Meaning, in my specific case I have two open-source projects, and three private projects on GitHub, and instead of seeing all three on my Travis account, I see only the two open-source ones, or the three private ones.

This is a bit confusing so I will provide screenshots and steps of how I can switch between the two accounts.

If I sign out completely, hit the main https://travis-ci.org page, and click log in with GitHub, and I go to my account page, I am taken to https://travis-ci.org/profile/tam5, and it shows I only have two repos:

<img width="1340" alt="screen shot 2016-01-14 at 3 33 36 pm" src="https://cloud.githubusercontent.com/assets/11488762/12337235/d87b9bba-bad6-11e5-8f4e-46ba9d5be55c.png">

Now, If I sign out, and go back to the home page https://travis-ci.org, and then click ‘plans’, I am now signed in again, but this time I seem to be signed in to a different account, though still at https://travis-ci.com/profile/tam5. Now, the repos I am showed are the three private repos that I have on GitHub, but not my open projects:

<img width="1337" alt="screen shot 2016-01-14 at 3 36 50 pm" src="https://cloud.githubusercontent.com/assets/11488762/12337262/fb97c362-bad6-11e5-8509-09a750ffc6b8.png">

As a side point I think this is the reason my build status icon is showing unknown, because I think the link is probably broken as there seem to be two different values at https://travis-ci.org/profile/tam5.

**Comment by tam5** [comment]
never mind this is intentional

**Comment by emilosman** [comment]
I was confused by the very same thing.
Turns out private repos are accessible via https://travis-ci.com
and public ones via https://travis-ci.org
