### ISSUE TITLE
Using travis_wait with R

### ISSUE THREAD

**Issue by dbailleul** [travis-ci/travis-ci#5469]
Good afternoon,
I've got some problems since I was asked to cover my R package the most possible with unit tests.
I'm using github/travis and coveralls, and testthat.
My unit tests take too long to run, so Travis just drops the analyse.

I've tried the "travis_wait" tricks, presented
here: https://github.com/craigcitro/r-travis/wiki
and here: https://twitter.com/noamross/status/483773346551570432
and here: https://github.com/eddelbuettel/rquantlib/blob/master/.travis.yml

But, it's not working :
https://travis-ci.org/dbailleul/RClone/builds/102618978

What am I doing wrong ?
https://github.com/dbailleul/RClone/blob/master/.travis.yml

Thanks in advance for yours advices.

**Comment by BanzaiMan** [comment]
Where is `travis-tool.sh` supposed to come from? If it is https://github.com/craigcitro/r-travis/blob/master/scripts/travis-tool.sh, then you are using @craigcitro's "r-travis" tool, which is superseded by our `language: r` support. Please consult https://docs.travis-ci.com/user/languages/r.

**Comment by dbailleul** [comment]
I think *travis-tool.sh* may come from r-travis ...
So, do you have any idea of how to be able to run travis_wait with *language: r*?

I've tried this, with no success:
https://github.com/dbailleul/RClone/commit/659412acf0c012ff64856698bf04f4f3766fec99

And I've tried this also:
https://github.com/dbailleul/RClone/commit/9d63bcf5be8113b789f562c39dc7ca2ca7600cd5

I understand I'm mixing commands but I've seen nowhere how to use *travis_wait* for ALL the functions run by *testthat*.

**Comment by BanzaiMan** [comment]
https://github.com/dbailleul/RClone/commit/9d63bcf5be8113b789f562c39dc7ca2ca7600cd5 looks to be the most promising of your attempts. `travis_wait()` is a function that executes commands that you pass. You still need to fix the commands (e.g., https://travis-ci.org/dbailleul/RClone/builds/102606962#L1122) but I think that's all there is.

I'm closing this now, since there is nothing on our end to do.

**Comment by craigcitro** [comment]
Adding @jim_hester just for visibility -- Jim, issues around better wait handling are another bit of user friction.
