### ISSUE TITLE
Encrypted env variables not exported.

### ISSUE THREAD

**Issue by GandaG** [travis-ci/travis-ci#5470]
Only 1 of my 2 secure env variables is being decrypted.

I already tried these commands:
`travis encrypt API_TOKEN=the_token_was_here -r GandaG/unitypackage-ci`, 
`travis encrypt 'API_TOKEN=the_token_was_here' -r GandaG/unitypackage-ci` and 
`travis encrypt "API_TOKEN=the_token_was_here" -r GandaG/unitypackage-ci`.

The other variable was encrypted with the first command and is being successfully exported.

The log from `--debug` was:
```
** Loading "C:/Users/Daniel/.travis/config.yml"
** Faraday::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
** GET "repos/GandaG/unitypackage-ci"
**   took 0.56 seconds
** GET "repos/my_repo_key/key"
**   took 0.53 seconds
Please add the following to your .travis.yml file:

  secure: "H8ZRdreadS+2JJhneDvW+uWXPEAumBb4o8+aRX/grEC7YfFffn0C/B8bj7E8NHtb1BtFVYQcCTag/hDY3+qmHwadlVwfxK8pYK5hvDP4SHZds30FrkIlRPbj6965zZ5ZcUyzfzDe5Kt8lrrR5vxKehKJvbuoW4N24jZaEQ8WV+oXal1YHU8UYIcPvZtk8dzwZzpsrmeU9cphhCsy/zc31+uFKvgi/tPg7GgZJtDLZevd3jdeP70t7cTmZ6yPIf/2g6/FQH3U49ZQiSWniJzMLmWxow7CQoHCRfTTA06Lzmy/G586rnaJmvJTYSC9iIlFsJKr8n8vF2uYofm7PbdZuo64YFDTU/OVpQdz1ul9oRaOt+KyMyK4VdeWdKHwyvUmmPM1mZivofiL0FYMHdhXHCZl55hCT4k5yal2ptQKNUTzM3+jquDTdJ69skhEARi81wLHds8KcaAXFK/0xiQn6A9psmyC8bXf6uaXWrhxRNlm5PqhJ9DGrOcri3yHHpxhTZ1wcOVZ+NQt471IuaMz3sTn9TyjXLeaKznznPR5GR4azOGUgdtIn6g+X/jHLgeUPqGVyojKjP0ZIkmbh//tBBWFF0n18uMYNyjK4raxeGitE0lmL59qxqj3SN70Ch4hxT8Tm/jExy8IEiEkcJZAAvzvi7qzc3DyUkjTVGOqQAk="

Pro Tip: You can add it automatically by running with --add.
** Storing "C:/Users/Daniel/.travis/config.yml"
```

(The other variable resulted in the same debug and ssl error)

My repo is at [unitypackage-ci](https://github.com/GandaG/unitypackage-ci/), the branch in question at [gh_deploy](https://github.com/GandaG/unitypackage-ci/tree/feature/gh_deploy) and the build at [travis](https://travis-ci.org/GandaG/unitypackage-ci/builds/102655997).

Please note that the unencrypted variable contains a "_" character which I tried to escape from but the result was the same.

**Comment by BanzaiMan** [comment]
I don't think [your `env.global` structure](https://github.com/GandaG/unitypackage-ci/blob/c308fc37b2b672613b24f8e237887ff77f48dc6f/.travis.yml#L13-L16) matches the one you wish to have after decrypting.

Try:

```yaml
```

See https://docs.travis-ci.com/user/encryption-keys#Detailed-Discussion for

**Comment by GandaG** [comment]
It works! Thank you :)

**Comment by piotrekkmt** [comment]
A note for others looking for answers related to this, took me a whole morning to understand what was happening. **Secure environment variables** will not be exported when running builds from forked PRs. 

- If you're forking your repository and want to make a Pull Request from your fork to an org repo with Travis builds running with _secure_ environment variables it will not work, because that PR will be considered **unsafe**. Otherwise if you make a PR from the same repos different branch it will pick them up no problem.
