### ISSUE TITLE
Document support for more recent versions of node

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [travis-ci/travis-ci#5471]
According to [the docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Provided-Node.js-Versions), only node versions up to 4.1 are supported. However, I needed a more recent version so tried setting up a `.travis.yml` with 5.4 and it just worked. I'm not sure what versions are available, but the docs seem to be out of date.

**Comment by zbeekman** [comment]
@uhoh-itsmaciek are you running on the container based infrastructure? A few container based builds have been hanging on `nvm install 4.2.1` https://travis-ci.org/kvz/bash3boilerplate/builds/109619625

**Comment by uhoh-itsmaciek** [comment]
@zbeekman we are, but that's a separate issue, no? The documentation claims that the provided node versions only go up to 4.1.x but we're setting "5.4" and it works fine. This suggests the docs are incomplete, no?

**Comment by zbeekman** [comment]
Yes, the issue is separate. What I was asking you was if you were able to build using a container based build, i.e., `sudo: false`

**Comment by uhoh-itsmaciek** [comment]
Ah, yes. Sorry, wasn't sure what you were asking. For what it's worth, this is setup:
```
$ cat .travis.yml 
language: node_js
sudo: false
dist: trusty
cache:
  directories:
      - node_modules
node_js:
  - "5.4"
env:
  - CXX=g++-4.9 PGSSLMODE=disable DB_SSL=false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
  postgresql: "9.4"
services:
  - redis-server
script: npm test && npm run lint
```

We moved to containerized builds after my initial `.travis.yml` setup, so I'm not sure why we need everything here, but I'm guessing we need gcc 4.9 to make this work (if memory serves, that was not needed without containerized builds).

**Comment by BanzaiMan** [comment]
The document has been updated.
