### ISSUE TITLE
Im having trouble but its probably me.

### ISSUE THREAD

**Issue by hellknighthicks** [travis-ci/travis-ci#5472]
.travis.yml - file as follow

language: csharp
solution: Windows 10 Privatizer - BETA.sln

**Comment by BanzaiMan** [comment]
Paging @joshua-anderson @akoeplinger @nterry

Looking at https://travis-ci.org/hellknighthicks/Destroy-Windows-10-Spying/builds/102745836#L979, though, I think you need to account for spaces. Our builds run on Linux, so white spaces are used for delimiting command arguments and options.

**Comment by hellknighthicks** [comment]
So Change the SLN file name to have _ instead of space?

**Comment by hellknighthicks** [comment]
Took the spaces out and made it a little further.

CSC: error CS2001: Source file `Lib/Paths.cs' could not be found
CSC: error CS2001: Source file `Lib/WindowsUtil.cs' could not be found
			Task "Csc" execution -- FAILED
			Done building target "CoreCompile" in project "/home/travis/build/hellknighthicks/Destroy-Windows-10-Spying/DWS/Pro Silver Systems - Windows 10 Privatizer.csproj".-- FAILED
		Done building project "/home/travis/build/hellknighthicks/Destroy-Windows-10-Spying/DWS/Pro Silver Systems - Windows 10 Privatizer.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/travis/build/hellknighthicks/Destroy-Windows-10-Spying/Windows_10_Privatizer-BETA.sln".-- FAILED
Done building project "/home/travis/build/hellknighthicks/Destroy-Windows-10-Spying/Windows_10_Privatizer-BETA.sln".-- FAILED
Build FAILED.
Warnings:
/home/travis/build/hellknighthicks/Destroy-Windows-10-Spying/Windows_10_Privatizer-BETA.sln (default targets) ->
(Build target) ->
/home/travis/build/hellknighthicks/Destroy-Windows-10-Spying/DWS/Pro Silver Systems - Windows 10 Privatizer.csproj (default targets) ->
/usr/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets (ResolveAssemblyReferences target) ->
	/usr/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Deployment' not resolved
Errors:
/home/travis/build/hellknighthicks/Destroy-Windows-10-Spying/Windows_10_Privatizer-BETA.sln (default targets) ->
(Build target) ->
/home/travis/build/hellknighthicks/Destroy-Windows-10-Spying/DWS/Pro Silver Systems - Windows 10 Privatizer.csproj (default targets) ->
/usr/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->
	CSC: error CS2001: Source file `Lib/Paths.cs' could not be found
	CSC: error CS2001: Source file `Lib/WindowsUtil.cs' could not be found
	 1 Warning(s)
	 2 Error(s)
Time Elapsed 00:00:01.4048770
The command "xbuild /p:Configuration=Release Windows_10_Privatizer-BETA.sln" exited with 1.

**Comment by nterry** [comment]
Check your source paths in the sln. Csc (the compiler) can't find Paths.cs
and WindowsUtil.cs

**Comment by hellknighthicks** [comment]
Spaces again huh?

**Comment by hellknighthicks** [comment]
Looks like i fixed the issues there... But im still getting a warning. 

/usr/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Deployment' not resolved

**Comment by Joshua-Anderson** [comment]
It looks like from a quick google that `System.Deployment` is not supported by mono, sorry. :frowning:

**Comment by akoeplinger** [comment]
Yeah, `System.Deployment` is a Windows-only library but given that you're not using it you can just remove it from your csproj.

**Comment by BanzaiMan** [comment]
Sounds there is not anything to do here.

I'm closing this.

**Comment by hellknighthicks** [comment]
Thanks for the help fellas
