### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by msimerson** [travis-ci/travis-ci#5473]
Since #1818 is closed and locked, I can't post comments (+1) there, and who knows what resources have changed since then.

I've recently done a bunch of work on automating the snot out of some $work related Linux deployments with Docker. Inspired (and in cases, disappointed) by the Docker tools, I took the time to port the same containerization and encapsulation ideas over to my [Mail Toaster](https://github.com/msimerson/Mail-Toaster-6) project.

I'd encourage a Travis developer or two to create a FreeBSD 10.2 VM (I use VMware Fusion) and run through the install. I think you'll find the provisioning process to be very familiar to the Docker-aware, and perhaps not that great of an engineering challenge.

Of course, rather than engineering a FreeBSD specific solution, there's always [Docker on FreeBSD](https://wiki.freebsd.org/Docker) that could also reduce the level of investment needed to provide this feature.

**Comment by BanzaiMan** [comment]
Thank you for taking time to open this issue. However, there has not been much progress in the way of natively supporting other operating systems since https://github.com/travis-ci/travis-ci/issues/1818#issuecomment-41922754. You at be able to achieve some objectives with our recent [Docker support](https://docs.travis-ci.com/user/docker/) by finding appropriate FreeBSD images.

**Comment by msimerson** [comment]
> You may be able to achieve some objectives with our recent Docker support by finding appropriate FreeBSD images. 

Oooohhhhhh, I shall investigate. Thanks!

**Comment by mmatuska** [comment]
Travis CI Docker is limited to Linux. You can't run other operating systems on it.

**Comment by cederom** [comment]
+1 for Jenkins over Travis for FreeBSD support.. not really interested in Travis if it only runs Linux :-)

**Comment by benrubson** [comment]
Travis support told me yesterday that the FreeBSD idea has been explored in the past, but that they are not planning to offer it in the near future :|

**Comment by mmatuska** [comment]
I would gladly offer them my help for free (l live in the same city btw.). The solution could be jail-based (preferable) or VM-based like Mac OS X is. FreeBSD runs well on GCE.

**Comment by cederom** [comment]
+1 again.. :-)

**Comment by execve** [comment]
+1

**Comment by msimerson** [comment]
UPDATE: for anyone that doesn't already know, the FreeBSD Docker guests will only run on FreeBSD servers. FreeBSD does run extremely well on VMware.

**Comment by forquare** [comment]
+1

**Comment by BanzaiMan** [comment]
We will visit support for other OSes in the future. If you are interested in updates, please subscribe to this issue instead of adding +1's.
