### ISSUE TITLE
use ruby and jruby in one run

### ISSUE THREAD

**Issue by davidak** [travis-ci/travis-ci#5476]
i can't use the matrix feature because i have multiple languages in the project.

it defaults to the ruby vm but i can't just run `jruby`, so i install it with apt.

https://github.com/davidak/satzgenerator/blob/26cbab2eb808d7c8b0d4f1e348277860c7492b05/.travis.yml

but i still can't use it:
```
$ /usr/bin/env jruby -v
jruby: unknown option --client
$ jruby -h
jruby: unknown option --client
```

**Comment by BanzaiMan** [comment]
You should use RVM to switch Ruby runtimes. Trusty's [`jruby` package](http://packages.ubuntu.com/trusty/jruby) is way too old to be useful at this point.

**Comment by davidak** [comment]
thanks

**Comment by davidak** [comment]
I installed it using `rvm install jruby` but can't start it.

`jruby: command not found`

if i just use `ruby` it is still the Ruby version.

https://travis-ci.org/davidak/satzgenerator/builds/102833266

how can i use it after installing?

**Comment by BanzaiMan** [comment]
`rvm use jruby` https://rvm.io/rvm/basics

**Comment by davidak** [comment]
it seams to get used now but i can't use any parameters like getting the version number. is the version broken?

```
$ ruby -h
jruby: unknown option --Xcompile.invokedynamic=false
$ ruby --version
jruby: unknown option --Xcompile.invokedynamic=false
$ ruby -v
jruby: unknown option --Xcompile.invokedynamic=false
```

https://travis-ci.org/davidak/satzgenerator/builds/102858645#L371

**Comment by BanzaiMan** [comment]
@davidak Sorry for the troubles. There is an error on our side, just on Trusty. We need to fix that. In the meantime, could you do this (somewhere in your build before you execute `jruby`)?

```
export '--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -Xcext.enabled=false -J-Xss2m -Xcompile.invokedynamic=false'
```

**Comment by davidak** [comment]
putting that in the build script gives me the error:

```
export: --: invalid option
export: usage: export [-fn] [name[=value] ...] or export -p
```

**Comment by BanzaiMan** [comment]
@davidak I updated the `export` command in the previous comment.

**Comment by davidak** [comment]
that finally fixes the issue. thank you!
https://travis-ci.org/davidak/satzgenerator/builds/102880050#L332

**Comment by sheldonh** [comment]
Is it expected that "rvm use jruby-9.0.4.0" should take about 6 minutes? Visually, it looks like most of the time is spent importing the default and global gemsets. Coupled with a 5 minute bundle install, my test jobs that complete in under a minute with MRI ruby take over 10 minutes with jruby.

**Comment by BanzaiMan** [comment]
@sheldonh JRuby is slow to spawn a new process. Depending on your workload, it can be pretty slow. https://github.com/jruby/jruby/wiki/Improving-startup-time might help you.

**Comment by sheldonh** [comment]
Actually, I've dug into the rvm code, and I think it's this: https://github.com/rvm/rvm/issues/2728

What would be great is if I could demand a matrix of Ruby versions, without using RVM. I'm happy to build my own binary ruby distributions and install them myself from the install script. But I can't prevent the wasted time in the RVM import.

**Comment by sheldonh** [comment]
By the way, I have to build my own rubies anyway, because Precise's ruby binaries are all linked against ancient libssl that doesn't support TLSv1.2 (important to my tests).

So what would also work for me is a lifecycle hook that happens before the "rvm use" is executed.

**Comment by josephbridgwaterrowe** [comment]
@davidak, How can I set the export command before the `ruby --version` is executed?

I'm having a problem with this build at https://travis-ci.org/westernmilling/gman-services/builds/108592286 saying that bundler isn't present. I've tried gem install and apt-get but neither work, so I'm trying to resolve the errors to see if its all related.

Thanks.

**Comment by BanzaiMan** [comment]
@josephbridgwaterrowe I think you are seeing a variation of #5578 (which deals with the Trusty case, but I suspect something similar happens for JRuby here). RVM is reading the `gemsets` file from `/usr/local` somehow, which is empty and Bundler is not available for this build. I noticed that you are using `language: jruby`, which I believe is unsupported. See https://docs.travis-ci.com/user/languages/ruby for more details.

**Comment by josephbridgwaterrowe** [comment]
Thanks @BanzaiMan, changing to `language: jruby` got me going.

:gift:

**Comment by BanzaiMan** [comment]
@josephbridgwaterrowe I hope you meant `language: ruby`. :-) Happy to hear that you got it going.

**Comment by josephbridgwaterrowe** [comment]
@BanzaiMan, Yes I did... whoops... editing previous comment.

Thanks again!
