### ISSUE TITLE
After calling `pod install`, wait for a long time to execute `Updating local specs repositories`

### ISSUE THREAD

**Issue by Cee** [travis-ci/travis-ci#5478]

**Comment by BanzaiMan** [comment]
Could you elaborate on what the issue is? Do you have a build log URL that shows the problem?

**Comment by Cee** [comment]
![7b70fed4-a8b6-420c-87fd-dc6c2ce417e4](https://cloud.githubusercontent.com/assets/5436953/12378471/7dd3fdb0-bd79-11e5-8ce9-5b6efa036395.png)

Log here: https://travis-ci.org/Cee/SwiftGGApp#L236

Takes about 5 minutes on `pod install`.

**Comment by BanzaiMan** [comment]
Sounds like it does take a long time to install dependencies.

A part of it is undoubtedly CocoaPods:

```sh-session
$ time pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Pre-downloading: `SwiftyJSON` from `https://github.com/SwiftyJSON/SwiftyJSON.git`
[!] Unable to find a specification for 'SwiftyJSON'.

[!] Unable to load a podspec from `SwiftyJSON.podspec`, skipping:

Pod::DSLError
pod install  77.31s user 19.56s system 68% cpu 2:20.72 total
```

It took 77 seconds to resolve dependencies on my machine (and failed—not sure why).

On my machine, 1.0.0.beta.2 was much faster:

```sh-session
$ git clean -dfx  
Removing Podfile.lock
Removing Pods/
$ pod --version   
1.0.0.beta.2
$ time pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `SwiftyJSON` from `https://github.com/SwiftyJSON/SwiftyJSON.git`
Downloading dependencies
Installing Alamofire (3.1.4)
Installing Kingfisher (1.9.2)
Installing Moya (6.0.0)
Installing Neon (0.0.3)
Installing Result (1.0.1)
Installing SwiftyJSON (2.3.2)
Installing UIColor_Hex_Swift (1.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 6 dependencies from the Podfile and 7 total pods installed.
pod install  4.52s user 1.12s system 76% cpu 7.323 total
```

You might want to try:

```yaml
before_install:
  - gem install cocoapods --pre
```

**Comment by Cee** [comment]
@BanzaiMan https://travis-ci.org/SwiftGGTeam/SwiftGGApp/builds/102951322
Oops, still not working. And I don't know what's wrong.

**Comment by BanzaiMan** [comment]
Sorry, but I don't know what's going on there.

**Comment by srubin** [comment]
I'm having this issue too: long waits in the "Updating local specs repositories" step.

**Comment by bogren** [comment]
We have the same issue `pod install` takes forever due to `Updating local specs repositories`. We also noticed that the pod repo fails to cache properly.

Current solution, we added `pod repo remove master` and `pod setup`. Went from 500s to 50s in build time. 
```
install:
- bundle install ... 
- pod repo remove master
- pod setup
- bundle exec pod install
```

**Comment by kenorb** [comment]
Related: #5329

**Comment by carlossless** [comment]
Hm, my solution was to cache the spec repo
```
  directories:
    - $HOME/.cocoapods/
```
And then update the repository on each build:
```
install:
  - gem install bundler
  - bundle install --jobs=3 --retry=3 --deployment --without distribution
  - bundle exec pod repo update
```
However, for some reason "$HOME/.cocoapods/" never gets cached. What could be the problem here, @BanzaiMan .

**Comment by BanzaiMan** [comment]
How do you know that this is a solution of you can't get it to work?

**Comment by carlossless** [comment]
@BanzaiMan sorry, I phrased it the wrong way. Made an edit to my original comment.

**Comment by dragvs** [comment]
I'm trying to resolve this issue too. Every build with 'pod install' takes extra 5 to 10 minutes just to clone CocoaPods master repo. Thats strange that every build must clone the repo and take so long without any caching behavior.
I've tried to cache '$HOME/.cocoapods/repos' directory but it fails giving the following error message: "running `casher push` took longer than 180 seconds and has been aborted".

**Comment by jamessa** [comment]
Same here. It becomes an catch 22 for us. If `$HOME/.cocoapods` is cached, it takes too long to upload the cache. But if i just use `cocoapods` in `cache` nothing happens. And take a long time to install.

**Comment by FranklinYu** [comment]
My `~/.cocoapods` is 2.4 GB. CocoaPods Spec repository is known to be large.

This issue hasn’t been resolved but it has been closed. Shall we create a new issue or re-open this one?
