### ISSUE TITLE
intial github sync stalls or does not complete

### ISSUE THREAD

**Issue by diffalot** [travis-ci/travis-ci#5479]
I've just signed up for travis-ci.org and the initial synchronization has not completed (after at least 2 hours).

I was hoping that I could manually force a sync with `travis sync --force`, but that command doesn't seem to do anything: travis-ci/travis.rb#358

Could someone look into why my sync appears to have stalled?

**Comment by BanzaiMan** [comment]
@diffalot sorry about that. I've reset the sync status, and manually restarted the sync. It finished now, please check again.

**Comment by diffalot** [comment]
Thank you @BanzaiMan! 

Looks great from here :thumbsup:

**Comment by BanzaiMan** [comment]
Thanks for the confirmation.
