### ISSUE TITLE
AWS Content-Encoding issue?

### ISSUE THREAD

**Issue by AJGarrett** [travis-ci/travis-ci#5480]
Not sure this is Travis issue, but thought there might be someone who can assist me in finding a solution.

I have a project in Travis that runs a gulp process, and then uploads the output to Travis.  That works great.  My issue is that the html files don't have an extension, so the content type is being set as "binary/octat", and then they try to download when they are clicked.

I need to be able to control the content-type.   I can manually from the aws cli with the command
"aws s3 sync . s3://bucket --content-type "text/html" "

Any suggestions on the best way to do this with Travis?

Can I use an after_deploy script, and if so do I have access to the AWS cli?   Can I write a shell script, if if my travis build language is node?

This is my one last hurdle to have a complete process in travis.  Any help would be very appreciated.

Thanks

**Comment by BanzaiMan** [comment]
Our deployment utility relies on file extensions to detect their content types. Without extension, we cannot do that. Specifying content types _might_ be an option, but I suspect it will be difficult to do it cleanly.

The step logically belongs to `after_deploy`. We do not install `aws` CLI, but you should have access to a Python runtime, and be able to install awscli:

```yaml
after_deploy:
  - pip install --user awscli
  - aws s3 … # assume `aws` is correctly configured
```

**Comment by AJGarrett** [comment]
Thanks, I'll have to try it this week.

Can I put my after deploy in a script and call like this?

after_deploy:
  - ./aws_script.sh

**Comment by BanzaiMan** [comment]
I believe you can.

**Comment by RobertJGabriel** [comment]
@BanzaiMan @AJGarrett over a year old but did you find a solution to this?

**Comment by AJGarrett** [comment]
@RobertJGabriel Yes, I was able to do solve this issue.   

Here's my travis config:

`
...
script: gulp dist
after_success: bash postdeploy.sh 
....
`

Here's what's in the postdeploy.sh  in the root of the project:
`
#!/bin/bash
pip install --user awscli
aws configure set aws_access_key_id $AWSKeyID
aws configure set aws_secret_access_key $AWSSecretKey
aws configure set default.region us-east-1
aws configure set default.output json
cd dist
find . -name '*.html' ! -iname 'index.html' -exec sh -c 'mv "$0" "${0%.html}"' {} \;
aws s3 sync . s3://bucket --exclude "*" --include "*.svg" --include "*.otf" --include "*.woff" --include "*.svg.css" --cache-control "max-age=1314000" 
aws s3 sync . s3://bucket --exclude "*" --include "*.jpg" --include "*.png" --include "*.gif" --cache-control "max-age=86400"
aws s3 sync . s3://bucket --exclude "*" --include "*.*" --cache-control "max-age=1800"
aws s3 sync . s3://bucket --content-type "text/html" --cache-control "max-age=1800"

`

**Comment by RobertJGabriel** [comment]
Brilliant thanks @AJGarrett
