### ISSUE TITLE
Handling multiple R versions in a build

### ISSUE THREAD

**Issue by MansMeg** [travis-ci/travis-ci#5481]
Hi! @craigcitro, @hadley and @jimhester

I would like to create two builds of my R package, one for the latest stable realease of R and one for R-devel (CRAN policy). I tried to set a travis matrix with environemnet variables RVERSION that should work in the old travis build (non R native):
https://github.com/MansMeg/markmyassignment/blob/master/.travis.yml

But it looks like that it do not use the RVERSION environment variable. See below:

https://travis-ci.org/MansMeg/markmyassignment/builds/103099160

I can't find any documentation in the native R Travis documentation.

Thanks for all you good work!

**Comment by jimhester** [comment]
Building with non-release builds is not currently supported in native R travis. But including that support is being actively worked on. Full documentation on native R travis can be found at https://docs.travis-ci.com/user/languages/r

**Comment by MansMeg** [comment]
Great! Do you have any idea when this will be up and running?

**Comment by BanzaiMan** [comment]
I think @jimhester got this working now. Thank you, @jimhester!
