### ISSUE TITLE
Never-ending travis tests: runtime over 1 hour but job does not stop

### ISSUE THREAD

**Issue by stnava** [travis-ci/travis-ci#5482]
https://travis-ci.org/stnava/ANTsR/jobs/103228966

https://travis-ci.org/stnava/ANTsR/jobs/103218695

these jobs are continuing despite the travis.yml script having ended.

i am unclear as to why this would happen.  the only change from my previous submissions is that i enabled building package vignettes.

**Comment by stnava** [comment]
Also "this build can't be canceled"

**Comment by stnava** [comment]
and, finally, only on OSX build ...

**Comment by BanzaiMan** [comment]
They both finished. Perhaps the log updates stopped working while you had the page open? I've experienced such issues recently.

**Comment by stnava** [comment]
ahh ... ok ... i've noticed some buggy log behavior as well.   thanks for monitoring the situation.  am happy as long as they do finish ( eventually ).  thx.
