### ISSUE TITLE
Complete configuration for Github Releases

### ISSUE THREAD

**Issue by GandaG** [travis-ci/travis-ci#5484]
Is there any documentation for a complete (with all supported features) configuration of Github Releases?

For example, from testing I know it is possible to set a release as a draft but it's nowhere in the travis docs.

**Comment by BanzaiMan** [comment]
Is it possible to set the release to a draft? I wasn't aware of that. Do you have a build log URL that it is?

**Comment by GandaG** [comment]
[Here.](https://travis-ci.org/GandaG/unitypackage-ci/builds/103507480)

I simply set the draft option inside deploy to True (has to actually be a boolean, it complained when I sent it as a string). So the docs are truly all the devs know for sure can be done?

**Comment by BanzaiMan** [comment]
@GandaG That is probably a byproduct of your versioning. We do not explicitly set the Release's draft status to `true`.

**Comment by GandaG** [comment]
@BanzaiMan I don't think so, at least in [this log](https://travis-ci.org/GandaG/unitypackage-ci/builds/103503379) there is an error that specifically states:

```
/Users/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/GandaG/unitypackage-ci/releases: 422 - Invalid request. (Octokit::UnprocessableEntity)
For 'properties/draft', "true" is not a boolean. // See: https://developer.github.com/v3
```

This was when I set `"draft": "true"` instead of `"draft": True` (I'm using python to make the api request to travis).

**Comment by BanzaiMan** [comment]
@GandaG Sorry, but I am having a hard time understanding how you are setting up the deployment. https://github.com/GandaG/unitypackage-ci/blob/v0.1-alpha5/.travis.yml does not use our deployment provider at all.

**Comment by GandaG** [comment]
@BanzaiMan Oh right, sorry. When I need to deploy I make a request to travis to start another build with a different config. The config is in [this file](https://github.com/GandaG/unitypackage-ci/blob/feature/gh_deploy/CI/deploy_set_up.py), more specifically this:

```
{"provider": "releases",
"api_key": github_token_goes_here,
"file": file_to_deploy,
"draft": True,
"skip_cleanup": "true",
"on": {"tags": "true"}}
```

The title field in the file was me experimenting but it didn't work.

**Comment by BanzaiMan** [comment]
I can say with a degree of certainty that this is an undocumented lucky coincidence that `draft` is respected. https://github.com/travis-ci/dpl/search?utf8=%E2%9C%93&q=draft

**Comment by GandaG** [comment]
@BanzaiMan So other lucky coincidences are not to be expected? :/ The only features supported are already in travis docs?

**Comment by BanzaiMan** [comment]
Ah, I see. https://github.com/travis-ci/dpl/pull/189 enabled some extra options that had not been allowed hitherto. That PR allowed extra options such as `draft: true`, but I think the document now lags behind. (I asked for documentation update in that PR, but I guess that never materialized.)

The options respected are documented in https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/releases.rb.

**Comment by GandaG** [comment]
That's exactly what I needed! Thanks :)
