### ISSUE TITLE
virtualenv>14.0.0 is incompatible with python 3.2

### ISSUE THREAD

**Issue by touilleMan** [travis-ci/travis-ci#5485]
Hi,

Virtualenv 14.0.0 has been released (2016-01-19) and embedded pip 8.0.0 which has dropped support for Python 3.2.

Here is a typical failed test using python3.2 and the `precise-stable` coockbook: https://travis-ci.org/MongoEngine/mongoengine/jobs/103574798
As you can see the pip embedded by travis's virtualenv is version 8.0.0 which makes it install failed.

To solve this I think travis should use virtualenv==13.1.2 for Python 3.2

According to this piece of code from the `master`, it seems the last available version of virtualenv is used:
https://github.com/travis-ci/travis-cookbooks/blob/master/community-cookbooks/python/attributes/default.rb#L45

The bug is more subtle on `precise-stable` branch: virtualenv installed version is a correct 12.0.6 (see https://github.com/travis-ci/travis-cookbooks/blob/fad6c97068c6154df32f6c5a3091779a6d0d817c/ci_environment/python/recipes/virtualenv.rb#L31), but after that pip is fetched from `/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl` which cause the crash. I have no idea what this `virtualenv_support` comes from (it should be a `virtualenv/virtualenv_support` if virtualenv is installed inside a virtualenv...)

**Comment by Kami** [comment]
We have the same issue - https://travis-ci.org/apache/libcloud/jobs/103525615

I agree with @touilleMan that probably the best thing to do is use older version of pip / virtualenv, otherwise support for Python 3.2 is broken on Travis.

Thanks.

**Comment by BanzaiMan** [comment]
Thanks for the report. We will look into the cookbooks issue.

@Kami If you are updating virtualenv on your own accord, though, it is not accurate to say that "support for Python 3.2 is broken on Travis."

**Comment by Kami** [comment]
@BanzaiMan Thanks!

As far as updating virtualenv on our own accord - we are not actually doing that. We use tox and as far as I know, tox uses system virtualenv which pulls in latest pip (8.0.0) which breaks things - https://travis-ci.org/apache/libcloud/jobs/103525615#L133

**Comment by BanzaiMan** [comment]
@Kami I am a bit confused. What is pulling down the latest virtualenv and/or pip that is incompatible with Python 3.2? Is it tox? Is it virtualenv? 

https://travis-ci.org/apache/libcloud/jobs/103525615#L109-L110 suggests to me that your requirements are too loose (this might be due to your requirements, or tox's):

    Collecting virtualenv>=1.11.2 (from tox)
      Downloading virtualenv-14.0.0-py2.py3-none-any.whl (1.8MB)

The version of virtualenv that we have _right now_ is compatible with Python 3.2, correct? If none of these tools have the smarts to avoid versions incompatible with Python 3.2 (or users tell them to ignore such restrictions—willingly or not), there is very little Travis CI can do to prevent that.

Yes, we can offer a version of virtualenv compatible with Python 3.2 ***by default*** with cookbooks, but what happens after that at runtime is up to the user.

**Comment by touilleMan** [comment]
@BanzaiMan thanks for the tip ! I've fix my project by explicitly installing virtualenv<14.0.0 along with tox (see https://github.com/MongoEngine/mongoengine/commit/b4af8ec751a17fe6c819c2e129e89e7005a1d0ae)

On the side, I've tried running my project without tox and it works fine on travis. I guess this show the trouble is not on travis side but on how pip handle it dependencies (installing virtualenv from python 3.2 should not lead to install a package without "Programming Language :: Python :: 3.2" inside it tags...)

**Comment by Kami** [comment]
@touilleMan Great, thanks for the info / tip.

I will try the same workaround on our side as well :)

**Comment by BanzaiMan** [comment]
I should note that the version of virtualenv that's installed is 13.1.0 across the board, defined in https://github.com/travis-ci/travis-cookbooks/blob/14f498763ec972ec6bfee6cecfe648d86597c7f7/cookbooks/travis_python/recipes/virtualenv.rb#L34.

**Comment by BanzaiMan** [comment]
I don't think there is much for us to do here.
