### ISSUE TITLE
Slowed down and stalled builds

### ISSUE THREAD

**Issue by bsipocz** [travis-ci/travis-ci#5489]
The status page is still green, but builds are super slow and stalling for a few hours now. No obvious reason within the packages I checked (I've also restarted previously passing builds so it's definitely non package related).

An example here: https://travis-ci.org/astropy/astropy/jobs/103628140#L462

Another example where most of them should (and usually) finish within a minute: https://travis-ci.org/bsipocz/ci-helpers/builds/103614996

**Comment by GandaG** [comment]
There was an [emergency update](https://www.traviscistatus.com/incidents/fcllblkclgmb), I'm guessing that is why builds are slow.

**Comment by BanzaiMan** [comment]
Sorry for the inconvenience. The issue should be resolved now.

I'm closing this.

**Comment by bsipocz** [comment]
@BanzaiMan - just a ping, that the same issue is starting to build up now.

**Comment by BanzaiMan** [comment]
@bsipocz We tend to have a huge queue (and back log) for the container builds when there is a sudden surge in build requests. I see that this is happening right now.

**Comment by bsipocz** [comment]
@BanzaiMan - I don't mean (and mind) the queue, etc, but the builds are also slow when started and then stalling and thus failing https://travis-ci.org/astropy/ci-helpers/jobs/104108018, so they have to be restarted at some point which adds up to an ugly positive feedback.
Can you suggest what to do in situations like this?

**Comment by BanzaiMan** [comment]
@bsipocz Timeouts are happening while downloading stuff, or what? Where is it downloading from?

**Comment by bsipocz** [comment]
It's installing a conda environment, so the urls are at continuum.
```
         channel URLs : https://conda.anaconda.org/astropy-ci-extras/linux-64/
                        https://conda.anaconda.org/astropy-ci-extras/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
```
here is a log of the same build when it passes: https://travis-ci.org/astropy/ci-helpers/jobs/104102500, or this one with a more detailed debug output https://travis-ci.org/astropy/ci-helpers/jobs/104092880
