### ISSUE TITLE
Build continued even after failure to install Python 2.7.11

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#5492]
There was an error whilst extracting Python 2.7.11 on the container infra, in:
https://travis-ci.org/mozilla/treeherder/jobs/103842767
```
2.7.11 is not installed; attempting download

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

Even with that error, the build continued to run later steps, finally erroring out during our pip install in `before_install`.

Whilst I'm presuming this is just a transient error, it would be great if the run aborted sooner (ie immediately after the error above) instead of continuing, since at first glance it was easy to miss these errors and instead think the later failures (during `before_install`) were the issue.

Many thanks :-)

**Comment by asmeurer** [comment]
Just had the same error at https://travis-ci.org/sympy/sympy/jobs/105492949. Here is the full log https://gist.github.com/asmeurer/4b6274159365ad21e08b. I am going to restart the job, so the log will not be on the Travis url any more.

**Comment by asmeurer** [comment]
Assumedly whatever is downloading the Python zip should be checking hashes for integrity, and attempting a redownload if the hash check fails.

**Comment by edmorley** [comment]
Many thanks for fixing this Hiro :-)

**Comment by rlgomes** [comment]
If this is fixed how come I still see the issue here:

https://travis-ci.org/juttle/juttle/builds/112931312

nvm hit: 
```
$ nvm install 5.0
curl: (35) Unknown SSL protocol error in connection to nodejs.org:443 
Binary download failed, trying source.
```
then later instead of running with 5.0 we were running with: 
```
$ node --version
v0.10.36
```

Is this the case of a different kind of failure ? The first error message does indicate `trying source` but seems like `nvm` didn't get to install the required version of node and instead of failing things there the run proceeded to fail in a way more cryptic manner later.

**Comment by edmorley** [comment]
The PR that closed this issue only affected Python (see the filenames modified).

I'd file a new issue for nodejs.

**Comment by rlgomes** [comment]
@edmorley shoot I thought there was a PR for `nvm` as well let me open one if I can't find one, my bad!
