### ISSUE TITLE
"language: android" is listed as "no language set"

### ISSUE THREAD

**Issue by donv** [travis-ci/travis-ci#5493]
Hi!

When setting "language: android" in .travis.yml the builds are listed as "no language set".

I would expect the language to be listed as "android".

Example: https://travis-ci.org/ruboto/ruboto/builds/103839566

**Comment by BanzaiMan** [comment]
I'm going to close this as a duplicate of #3655.

**Comment by donv** [comment]
Thanks!  I'll follow that issue.
