### ISSUE TITLE
script provider docs may imply that executable file is required

### ISSUE THREAD

**Issue by blbradley** [travis-ci/travis-ci#5494]
The language is:

> `script` must be a scalar pointing to an executable command.

But the example shows `scripts/deploy.sh`.

Maybe the language should be:

> `script` must be a scalar pointing to an executable file or command.

and another example showing that a single command can be run. I believe this difference would improve usage for some people. I'm brave and willing to try new things; so, I just put a single command in and tried it. But not everyone would.

Thanks for considering! I couldn't find a repo for Travis CI docs. My apologies if this is not the right place.

**Comment by BanzaiMan** [comment]
A script is also a command, no? The docs are found at https://github.com/travis-ci/docs-travis-ci-com.

**Comment by blbradley** [comment]
@BanzaiMan Yes! I agree. But newer *nix users might not understand the difference.

**Comment by BanzaiMan** [comment]
Closing this in favor of the docs issue.
