### ISSUE TITLE
Error when building Android on Travis with android 23.0.2 build tools

### ISSUE THREAD

**Issue by emartynov** [travis-ci/travis-ci#5498]
I have config:
```
android:
  components:
    # The BuildTools version we are using for our project
    - build-tools-23.0.2
```
I see in logs:
```
...
Fetching URL https://dl-ssl.google.com/android/repository/repository-10.xml
...
Error: Ignoring unknown package filter 'build-tools-23.0.2'
Warning: The package filter removed all packages. There is nothing to install.
         Please consider trying to update again without a package filter.
```
I've checked XML that is downloaded doesn't have a notion about **23.0.2** build tools. But repository 11 has. 

Should Travis use the newer repository URL?

Full log is available here https://travis-ci.org/wasabeef/recyclerview-animators/builds/104028289

**Comment by BanzaiMan** [comment]
If you need the latest development tools, try adding `platform-tools` and `tools` to `android.components` (this is discussed in the first example in https://docs.travis-ci.com/user/languages/android).

**Comment by emartynov** [comment]
The issue is with `build-tools` and I need specific build tools

**Comment by BanzaiMan** [comment]
Did you try it? See https://travis-ci.org/BanzaiMan/travis_production_test/builds/104119101#L632-L637

This one took a long time to install `tools` (https://travis-ci.org/BanzaiMan/travis_production_test/builds/104119101#L448-L453), but it eventually found the version you want.

To cut down on times, you'd have to wait for the next build environment update.

**Comment by emartynov** [comment]
If I use this variant, does it festch latest? What will happen if Google releases newer version?

**Comment by emartynov** [comment]
I see again that build tools is not fetched:
```
curl -v https://dl-ssl.google.com/android/repository/repository-10.xml 2>&1 | grep 23.0.2
```

**Comment by BanzaiMan** [comment]
Adding `tools` should fetch `repository-11.xml`. I don't know why Google splits the information this way, and I don't know how you can get the files you need without downloading the huge `tools` component.

**Comment by emartynov** [comment]
Nope, doesn't work:
https://travis-ci.org/wasabeef/recyclerview-animators/builds/104311863

**Comment by BanzaiMan** [comment]
Perhaps you need `platform-tools`, too. See the first example: https://docs.travis-ci.com/user/languages/android.

**Comment by emartynov** [comment]
Looks like fixed. It is super strange! Thanks for help!
