### ISSUE TITLE
Set `PIP_DISABLE_PIP_VERSION_CHECK=1` by default in the environment

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#5499]
Newer versions of pip (v6+) check for updates to pip upon every invocation.

This results in an increase in run-time (and also log spam), especially for projects that are testing compatibility with multiple versions of dependencies.

eg in https://travis-ci.org/erikrose/peep/builds/103905714 there are ~280 instances of:
```
You are using pip version 7.0.0, however version 8.0.0 is available.
```
...each of which requires a connection to PyPI before the command will complete.

This can be avoided by defining the environment variable `PIP_DISABLE_PIP_VERSION_CHECK=1`. (Equivalent to the pip install `--disable-pip-version-check` option.)

It seems like this would be something that Travis should set by default in the environment?

**Comment by erikrose** [comment]
Fixed by the above! Somebody with privs can close this.

**Comment by edmorley** [comment]
Many thanks! :-)

**Comment by BanzaiMan** [comment]
The PR above resolve this problem by setting this env var after the initial invocation of `pip --version`, so that the user is aware of the updates.
