### ISSUE TITLE
Bug: enabling Docker service breaks Cassandra service

### ISSUE THREAD

**Issue by HariSekhon** [travis-ci/travis-ci#5502]
/usr/local/cassandra/ stuff disappears breaking my checks:

https://travis-ci.org/HariSekhon/nagios-plugins/jobs/104202614

**Comment by BanzaiMan** [comment]
Cassandra is not yet available on Trusty (a.k.a. Docker service) environment. This is documented in https://docs.travis-ci.com/user/trusty-ci-environment#Data-Stores.

**Comment by HariSekhon** [comment]
Ah, so enabling docker service changes the underlying build and that doesn't yet have a lot of the services integrated yet...
