### ISSUE TITLE
travis-ci cannot find module babel-runtime

### ISSUE THREAD

**Issue by Dindaleon** [travis-ci/travis-ci#5503]
I am having a difficult time getting my project built on travis. On my machine builds and runs fine; however, travis is complaining that cannot resolve module `babel-runtime`

```
ERROR in ./src/components/Layout.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in /home/travis/build/Dindaleon/hapi-react-starter-kit/src/components
 @ ./src/components/Layout.js 12:60-116
```

How may I solve this?

**Comment by BanzaiMan** [comment]
Please show the build log IRL that shows this problem. This is not sufficient to give you any help.

**Comment by Dindaleon** [comment]
here: https://travis-ci.org/Dindaleon/hapi-react-starter-kit/builds/104335652

**Comment by BanzaiMan** [comment]
I see a whole lot of errors in `npm install` (e.g., https://travis-ci.org/Dindaleon/hapi-react-starter-kit/builds/104335652#L163 https://travis-ci.org/Dindaleon/hapi-react-starter-kit/builds/104335652#L167, etc.) and these do occur when I clone this repository and run `nvm install 4`, `nvm use 4`, `npm install` on my machine.

For some reason, though, we fail to detect this error from the exit status of `npm install`, so we continue. I can't say why `npm` does this.

Subsequent invocation of `npm test` is filled with problems, but I don't think this is an issue with Travis CI. If this does not happen on your local machine, then it has something that makes things go that our VM (or my machine) does not have. Please review what is happening with your dependencies.

**Comment by Dindaleon** [comment]
Yes, there probably are some incompatibility issue. I have deployed the app on OpenShift and Heroku without any issues. I see you tried installing on node's version 4, did you try node version 5? I have v5 on my machine.

**Comment by BanzaiMan** [comment]
That's the version you specified in that build. https://github.com/Dindaleon/hapi-react-starter-kit/blob/60c0ea1d81b02d1b485aa4401f86c1a40cc6575c/.travis.yml#L3

**Comment by Dindaleon** [comment]
It now works. I had to specify node version to 5.
