### ISSUE TITLE
ENOSPC yet tests still pass

### ISSUE THREAD

**Issue by mmlb** [travis-ci/travis-ci#5504]
See https://travis-ci.org/mistifyio/mistify-os/builds/104241810 for a build showing both issues.

How much disk space are allotted to the containers? I'm trying out travis to see if we can replace our use of jenkins and will probably need ~40G (I'll do a local build to give a better number). 

Either way I would expect for the build to fail if one of the steps fails (as does the `./buildmistify` step of `script`).

**Comment by BanzaiMan** [comment]
Containers share resources with other containers and the host. And each will have less than 40 GB disk space. Sorry about that.

Deployment failure not marking the build a failure is a known issue. I can't locate the relevant GitHub issue.

**Comment by mmlb** [comment]
Welp yeah I can see how <40G seems reasonable, tbh I'm pretty sure the 2hr build limit would have bitten us any way.

To be clear this was not a deployment failure, but a failure within `script`.

**Comment by BanzaiMan** [comment]
It happened in the cache upload phase. But the idea is the same.

**Comment by mmlb** [comment]
Not quite, the build itself failed also see https://travis-ci.org/mistifyio/mistify-os/builds/104241810#L2867. I did see the other issues about no space errors, but this one seemed a bit different in that a step in `script` fails, and `script` seems to continue as if it did not. Then the cache upload does indeed fail also due to ENOSPC.

**Comment by BanzaiMan** [comment]
You ran `tail`, which exited with 0. You are sending some of the commands to the background, and we will not check exit statuses of those.

**Comment by mmlb** [comment]
Ahh yes you are right, for some reason I was under the impression that `script` was run under `set -e`, which I should have figured out on my own since as you say the next lines *are* being run.

**Comment by BanzaiMan** [comment]
Is there anything else to do on this issue?

**Comment by mmlb** [comment]
Nope.
