### ISSUE TITLE
/home/travis/build.sh: line 45: 10805 Segmentation fault

### ISSUE THREAD

**Issue by mfrasca** [travis-ci/travis-ci#5505]
I do not understand if this is related to something I changed or what else is going on.
https://travis-ci.org/Ghini/ghini.desktop/builds

[build 51](https://travis-ci.org/Ghini/ghini.desktop/builds/104336734) is a single commit push.
[build 50](https://travis-ci.org/Ghini/ghini.desktop/builds/104301677) was succeeding.
I noticed after a couple more commits and I cannot go back to succeed (I did not try yet to undo EVERYTHING, I confess, I just undid bit by bit parts which I considered suspicious, to no avail.)
all tests work fine on my workstation.

**Comment by mfrasca** [comment]
ba9ce930fa101562e64663cdbab4507ae37cc3ce built successfully

**Comment by BanzaiMan** [comment]
Is there something for us to look into? Seems like some Gtk bindings were failing.

**Comment by petrgrishin** [comment]
`/home/travis/build.sh: line 45:  4102 Segmentation fault` into https://travis-ci.org/petrgrishin/array-access/jobs/99397867 😔
