### ISSUE TITLE
New Account Can't Find Repositories

### ISSUE THREAD

**Issue by dougiefresh49** [travis-ci/travis-ci#5506]
When trying to sync my travis-ci.org account with github for the first time, i am getting this message:

Sorry, it seems like we couldn't find any repositories you have access to on GitHub.

I have tried signing out and back in, revoking access on github and then adding the access back, as well as clearing the browser cache (just in case).

github: https://github.com/dougiefresh49

Please advise me on how to proceed. Almost identical issue to #2765 
Thanks in advance

**Comment by BanzaiMan** [comment]
Sorry about the issue. I've reset your user data. You should be able to see the data now. Close this issue if you do.

Thanks.

**Comment by dougiefresh49** [comment]
Awesome! All is fixed, thank you very much!
