### ISSUE TITLE
Erlang/Elixir downloads are not being cached?

### ISSUE THREAD

**Issue by elasticdog** [travis-ci/travis-ci#5514]
I'm not 100% familiar with the inner workings of kiex, but I noticed that every build of my [Elixir project](https://travis-ci.org/elasticdog/lexibomb) (and all Elixir projects) will download and install both the pre-built Erlang binary *erlang-18.0-nonroot.tar.bz2* as well as the desired Elixir binary *v1.2.1.zip*. Shouldn't those be added into my project's build cache automatically to avoid unnecessary downloads? Or is there a configuration option to do so?

I also noticed that it leaves both of those archive files in the top level directory of the repo after extracting them (I had to add a .gitignore for them since I generate documentation and commit any changes). Is that typical, or should the [Elixir build script](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/elixir.rb) clean them up?

**Comment by BanzaiMan** [comment]
Since these runtimes are not preinstalled on the current build images, they need to be downloaded from somewhere. Cache will also incur a download, I don't think adding this to the cache is beneficial.

Cleanup should be performed, yes.

**Comment by elasticdog** [comment]
Thanks for the quick response @BanzaiMan...understood that even with the cache it would incur a download. I guess it's also a reliance on third-party resources being available...the Erlang OTP releases *are* pulled from a Travis-owned S3 bucket, but the Elixir releases are pulled from the upstream hex.pm builds.

Good to know that the build script should clean up those archives. Would you like me to close out this issue and open another for the cleanup specifically, or just rename this issue to track it?

**Comment by BanzaiMan** [comment]
I suppose we can consider mirroring Elixir binaries or something, but I suppose it wouldn't matter much over the long run.

Whether you morph this issue into the cleanup issue or close this and open a new one for the cleanup is entirely up to you. Either would work.

**Comment by BanzaiMan** [comment]
Closing for now.
