### ISSUE TITLE
Where's the PHPUnit binary?

### ISSUE THREAD

**Issue by henrywright** [travis-ci/travis-ci#5515]
Hi guys

I seem to be getting this message when running a build:

> /bin/sh: 1: /usr/local/bin/phpunit: not found

Using the phpunit.de installation guide, `/usr/local/bin/phpunit` is the location I'm told to put phpunit.phar.

Ref: https://phpunit.de/manual/current/en/installation.html

**Comment by BanzaiMan** [comment]
We use phpenv to mange the PHP environments. It is best to just invoke `phpunit` instead of the absolute path. The actual location would vary depending on the PHP version in use.

I'm closing this now.

**Comment by henrywright** [comment]
@BanzaiMan I'm invoking PHPUnit through Gulp using the `gulp-phpunit` plugin and need to provide a path to the executable. For example
```
gulp.task('phpunit', function() {
  var options = {debug: false};
  gulp.src('phpunit.xml')
    .pipe(phpunit('/path/to/phpunit',options));
});
```

**Comment by BanzaiMan** [comment]
Whoa. Does it require an absolute path? Seems a bit odd.

**Comment by henrywright** [comment]
@BanzaiMan take a look at the task I posted above, you should see `/path/to/phpunit`. I have to replace that with a custom path. If I don't, then a default path of  `./vendor/bin/phpunit` is used.

**Comment by BanzaiMan** [comment]
Initially you indicated `/usr/local/bin/phpunit`. If you use `phpunit`, what happens? My expectation would be that it would respect `$PATH`, but I've been surprised by PHP tooling before.

**Comment by henrywright** [comment]
When I use just `phpunit`, I get a strange:

> PHPUnit 4.5.0 by Sebastian Bergmann and contributors.
> option --colors doesn't allow an argument

I've experimented at my end by 

 - renaming the color option in my phpunit.xml from `true` to `auto`
 - removing the color option completely from my phpunit.xml
 - explicitly providing the color option in my grunt task
 - removing the color option from my grunt task

All result in the same:

> option --colors doesn't allow an argument

Here's the build log: https://travis-ci.org/henrywright/buddypress-identicons/jobs/104950980

**Comment by BanzaiMan** [comment]
So, you are able to invoke the correct `phpunit` command then. I am sorry to say this, but the `--colors` bit is an issue with the way you are invoking `phpunit` with `gulp`. Please consult the tool's documentation.

I'm closing this now, since there is no more to do on our side.

**Comment by henrywright** [comment]
> I am sorry to say this, but the --colors bit is an issue with the way you are invoking phpunit with gulp

Do you mean a bug in the gulp plugin or something I'm doing wrong?

**Comment by BanzaiMan** [comment]
Sorry, but I can't tell you much more. If you are not getting this issue locally, double check your dependencies, and/or try following the steps on a fresh machine.
