### ISSUE TITLE
Mac Python won't install 

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#5516]
Here is an example ( https://travis-ci.org/jakirkham/vigra/jobs/104924276 ). Happens with Python 2.7, 3.2, and possibly others.

**Comment by BanzaiMan** [comment]
Currently Python is not supported on the Mac. See https://github.com/travis-ci/travis-ci/issues/2312.

**Comment by jakirkham** [comment]
Thanks.
