### ISSUE TITLE
Enable alternative debian/.travis.yml location, support Travis-CI usage in Debian packaging

### ISSUE THREAD

**Issue by ottok** [travis-ci/travis-ci#5519]
Hello!

Currently it seems that the root of the repository is the only place where a `.travis.yml` can be located at.

This is a problem when using Travis-CI with repositories that are used to develop Debian packages. In Debian packaging, changes are allowed only in the `debian/` subdirectory and touching anything outside that is forbidden as it would contaminate the pristine upstream source part.

The solution would be easy: the code that finds `.travis.yml` could first check if there is a `debian/.travis.yml` file and run it instead if found. If not found, proceed with any usual `.travis.yml` file in the project root.

Without this feature, it is currently not possible to benefit from Travis-CI while developing Debian (and Ubuntu) packages. Having it would be super cool. We all want that when we run `apt-get upgrade` in our preferred distros the packages that come in are well tested and have no regressions, right? Travis-CI could help here.

**Comment by BanzaiMan** [comment]
Hi, Otto.

Can you move the file when you package the software?

**Comment by ottok** [comment]
In Debian packaging the packager is not allowed to touch any file outside the debian/ directory. The packager cannot remove any .travis.yml in the original source root, they could only override by supplying a second travis.yml file in the debian/ directory.

So what I propose is this change in logic:

Your current logic:
  1. check if /travis.yml is found
  2. if found, run it

New logic:
  1. check if /debian/travis.yml file is found
  2. if found, run it and stop
  3. check if /travis.yml is found
  4. if found, run it

**Comment by BanzaiMan** [comment]
Perhaps I am missing something, but can you not move `.travis.yml` _**before**_ the packager starts packaging?

The resulting package doesn't need `.travis.yml`, does it?

**Comment by ottok** [comment]
In this scenario /deb/an/travis.yml is supposed to be the file that triggers the whole Travis-CI build, so it cannot be moved as part of the Travis build.

Let's consider this repo as an example: https://github.com/ottok/debian-entr

If I now drop in a file /debian/travis.yml in that repo, nothing will happen. If I drop in /travis.yml the build will start but my package will no longer be valid Debian policy wise, as I've contamined upstream source part (touched files outside debian/*). The ideal thing would be that simply dropping in the file /debian/travis.yml the Travis-CI build would start.

**Comment by BanzaiMan** [comment]
Why does the package policy dictate the source directory structure? Shouldn't such a policy govern only how the build artifacts are laid out?

**Comment by ottok** [comment]
Policy dictates how upstream sources should be kept, as in Debian pristine sources, reproducable builds, upstream authenticity etc are valued goals, mostly due to security reasons. I cannot find the paragraph in the Debian policy that states this, but feel free to browse http://anonscm.debian.org/cgit/ and see how all packages have a debian/ subfolder where all packager changes reside.

**Comment by freeekanayaka** [comment]
Any news on this issue? I'd like to see it implemented too.

**Comment by sdesalas** [comment]
Would be nice to have alternative `.travis.yml` location. My use case is forking an open source repository but wanting a slightly different build without causing merge conflicts.

**Comment by merlokk** [comment]
any news?

**Comment by RayBenefield** [comment]
Being able to keep `.travis.yml` out of the root directory also helps Developer Experience when visiting a repo like on Github where a list of files is presented above the readme. The more files in the root directory, the farther down the readme on the page. Less files in the home directory means that maintainers have the ability to use logos/badges/etc. to quickly communicate information to a visitor.

This would be a very valuable feature to have as open source grows.

**Comment by merlokk** [comment]
as i see it needs:

1. add to `https://github.com/travis-ci/travis-web` to `settings-general` button "custom location .travis.yml" and add there edit for custom location
2. add to `https://github.com/travis-ci/travis-build` alternate location of ".travis.yml"

is it OK?
how to approve this changes?

**Comment by mpe** [comment]
Supporting a per-repository alternate location for `.travis.yml` would also enable multi-arch/multi-project repositories to use Travis more easily.

For example the Linux kernel supports ~30 different architectures in a single repository, although they can all be superficially built with `make defconfig ; make`, some architectures support multiple configurations and all non-x86 arches require a cross-compiler to be installed before building. Although it would in theory be possible to contain all that complexity in a single `.travis.yml` it's not really feasible in practice.

Additionally there are other projects that exist in the Linux kernel repository, eg. `perf`, `cpupower`, and the kernel selftests. Building any of those using Travis requires a completely different set of instructions, which can really only be handled by a separate `.travis.yml`.

**Comment by pradyunsg** [comment]
Is there any interest from the Travis Team in implementing something along the lines of https://github.com/travis-ci/travis-ci/issues/5519#issuecomment-293477582?

**Comment by nemchik** [comment]
I wanted to reiterate the request from https://github.com/travis-ci/travis-ci/issues/5647 and about allowing `.travis.yml` to work inside the `.github` folder as `.github/.travis.yml`. This would be very nice and allow some cleanup of the root directory of the repo.

**Comment by ocornut** [comment]
+1 to this, allowing Travis to detect the file in either .github/.travis.yml either a custom location would be very appreciated. From my project point of view I am trying to make the root folder as pristine of "building/testing artefacts" as possible and travis is the only thing left in there.

**Comment by BanzaiMan** [comment]
Closing as a variation of #5108.
