### ISSUE TITLE
Artifacts and /var/log: permission denied on a lot of files

### ISSUE THREAD

**Issue by gsmet** [travis-ci/travis-ci#5521]
Hi,

In the artifacts documentation, the example given defines /var/log as a possible path.

The issue with it is that the artifacts process has a lot of "permission denied" errors when trying to copy the /var/log repository.

It would be nice if the artifacts process could run as a privileged user so that we could ship the PostgreSQL/MySQL/... log files to S3: it can be useful for debugging.

-- 
Guillaume

**Comment by BanzaiMan** [comment]
http://www.postgresql.org/docs/9.3/static/runtime-config-logging.html suggests to me that changing log file directory permissions demands some further changes to the PostgreSQL configuration that is not possible without `sudo` permissions.

If you need read access to `/var/log`, it is best to use `sudo: required` and `sudo` to read the logs.

**Comment by gsmet** [comment]
Hi Hiro,

As the artifacts parts is run by Travis itself, I was wondering if you could run the artifacts command with sudo in Travis (thus not requiring sudo in the build).

Using sudo has a lot of drawbacks for Java projects (no cache for the .m2/repository directory).

**Comment by BanzaiMan** [comment]
The build will have `sudo` disabled when the execution gets to `artifacts`. This is irreversible, as far as I can tell.

**Comment by gsmet** [comment]
OK! Thanks for your feedback!
