### ISSUE TITLE
Allow custom build steps

### ISSUE THREAD

**Issue by krlmlr** [travis-ci/travis-ci#5524]
This is for `language: r`, CC @craigcitro, @hadley, and @jimhester

I was looking for a way to add a build step on top of the default build steps. The entire build is supposed to fail if my build step fails but the default build step succeeds. To me, it looks like if I define a `script:` entry in `.travis.yml`, the default behavior is overridden. Please advise.

The `after_script` step unfortunately doesn't seem to break the build if it fails: https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build

**Comment by jimhester** [comment]
I don't think there is a way to do this without overriding the default `script:` block completely. Would it be possible to put the extra commands in the `before_script` block and run them before the check?

If you do need to override the setup the commands that are run are defined at
[travis-ci/travis-build/lib/travis/build/script/r.rb#L143-L189](
https://github.com/travis-ci/travis-build/blob/1a08a160314d00e6b799a77a78448f0b0fd7b2ed/lib/travis/build/script/r.rb#L143-L189).

If you really want to force a failure from the `after_script` block you can by setting `set -e`, then the next command with a non-zero exit status will exit immediately and force a build failure.

See https://travis-ci.org/jimhester/travis-test/builds/105462382 for an test example of failing in the `after_script`.

**Comment by krlmlr** [comment]
I think we could add some logic in the `script` handler that evaluates a custom configuration property, but this behavior would be unique to the "R" language. The `set -e` hack is nice, let's stick to that for now.
