### ISSUE TITLE
[precise-gce] sudoers change to !env_reset

### ISSUE THREAD

**Issue by hugoduncan** [travis-ci/travis-ci#5525]
It seems that the sudoers config has changed to include `!env_reset`.

My project's tests were relying on `sudo` not propagating arbitrary environment variables, so this caused my tests to start failing when run on travis.

Is there a rationale for this change?

**Comment by BanzaiMan** [comment]
I don't think this is true (any longer): https://travis-ci.org/BanzaiMan/travis_production_test/jobs/240647792#L127.
