### ISSUE TITLE
Builds killed without any information

### ISSUE THREAD

**Issue by gsmet** [travis-ci/travis-ci#5526]
Hi,

One of my builds started to be killed without any further information.

See:
https://travis-ci.org/gsmet/hibernate-ogm/builds/105386727#L1585
or
https://travis-ci.org/gsmet/hibernate-ogm/builds/105384637#L1583
killed not exactly at the same test.

A previous build went further and I haven't changed a single line of code between the builds:
https://travis-ci.org/gsmet/hibernate-ogm/builds/105381570

Any idea of what could be the issue?

Thanks.

-- 
Guillaume

**Comment by BanzaiMan** [comment]
Do your builds require a lot of memory? A likely explanation is that they do, and gets killed by the host under memory pressure.

**Comment by gsmet** [comment]
It might be the answer, yes. I switched the build to the new Trusty infrastructure and it works (with the disadvantage of having no cache)!
