### ISSUE TITLE
Dependence on erlang.org when it (probably) shouldn't

### ISSUE THREAD

**Issue by fenollp** [travis-ci/travis-ci#5527]
The website erlang.org goes down way too often, but that's their problem.
Erlang projects in Travis seem to always call `kerl update releases` even though

1. updating releases fetches from erlang.org, thus builds fail twice a week
1. Travis knows which releases it has
1. Travis knows which releases are asked for, in `.travis.yml`

Why update the releases list? [related](https://github.com/travis-ci/docs-travis-ci-com/issues/225)
Also, why is there an otp_src$RELEASE.tar.gz file in $TRAVIS_BUILD_DIR? [related](https://github.com/travis-ci/travis-ci/issues/5514)

Thanks!

**Comment by BanzaiMan** [comment]
Duplicate of #5514.
