### ISSUE TITLE
Persistent no space left on device errors

### ISSUE THREAD

**Issue by lvh** [travis-ci/travis-ci#5528]
I'm getting:

```
       java.io.IOException: No space left on device
```

at https://travis-ci.org/RackSec/desdemona/builds/105570307#L375.

Looking at the issue tracker, it's suggested to just retry the build to see if it's a transient issue. I did, and the issue persisted. Unfortunately killing and restarting [build #4 (the first build)][b4] has successfully cleared its log, but now it thinks it's perpetually still in progress (even though it's actually wedged), but creating some new commits kicked off [build #5][b5] which shows the same error. Alas, that build also seems to be wedged.

[b4]: https://travis-ci.org/RackSec/desdemona/builds/105553086
[b5]: https://travis-ci.org/RackSec/desdemona/builds/105570307

While it is downloading quite a few jars, it shouldn't be so many that it stops working; I have working projects that have more dependencies to drag down (haven't measured in MBs though :)).

**Comment by BanzaiMan** [comment]
Containers run on a shared VM, and it could be affected by neighbors chewing up disk space.

It is not clear to me from the logs how much your build is using the disk space (build hung, so there was no way to get the disk space usage info from your job).

**Comment by lvh** [comment]
FWIW, more builds eventually fixed the problem, although that one cancelled build is still marked as in progress.

**Comment by BanzaiMan** [comment]
Sorry for the delay. Which one is left behind?

I'm closing this now, since the original issue is resolved.
