### ISSUE TITLE
[ci skip] can hide builds that should be run

### ISSUE THREAD

**Issue by dchelimsky** [travis-ci/travis-ci#553]
I pushed a bunch of commits at once, the last of which had "[ci skip]" in the commit message. This caused travis to ignore the whole lot, even though there were commits that didn't have [ci skip] that I would have wanted to run. Now that I know this I'll be careful to push the non-skippable commits first, however it would be really nice if travis could handle this a little more intelligently:

When receiving a commit with [ci skip] in the message, iterate through the parent commits until you reach a) a commit that has already been built, in which case go ahead and ignore the build or b) a commit without [ci skip] that has not been built yet, in which case build it.

**Comment by BanzaiMan** [comment]
This behavior is logically inconsistent and hard to reconcile for the users.

We will respect `[skip ci]` comments in merge commits now. If one wants to force a build, we can use the API request, or push an empty commit on top of the current one.

**Comment by BanzaiMan** [comment]
https://changelog.travis-ci.com/skip-ci-command-is-respected-under-all-circumstances-133546
