### ISSUE TITLE
gcloud and kubectl

### ISSUE THREAD

**Issue by sleepyfox** [travis-ci/travis-ci#5530]
I'm trying to deploy to Google Container Engine using an 'after_success' directive, but if I try and use kubectl Travis tells me that it isn't installed, and if I try and install it using the documentation's recommended method of 'gcloud components update kubectl' then Travis responds with 'You cannot perform this action because the component manager has been disabled for this installation.' as can be seen here: https://travis-ci.com/ygt/hundred-acre/jobs/31771561

Is there a way to get around this, other than doing a fresh local install of the gcloud binary?

Thanks, 
Fox
--

**Comment by shanemcd** [comment]
I havent used Kubernetes on Travis, but can you verify that you have run `gcloud init` in order to authenticate to GCE?

If this doesnt work, I would try installing the latest version of the `gcloud` sdk: https://cloud.google.com/sdk/#linux

**Comment by shanemcd** [comment]
You might also want to ask for help in the [Kubernetes Slack Team](http://slack.kubernetes.io/).

**Comment by sleepyfox** [comment]
I used the solution here: https://github.com/cotsog/travis_ci_prod_trusty/blob/204e3a09d33ed5412ff0f03b2192106dfff00c69/.travis.yml

A bit rubbish really, as the only solution is to make a local install of the Google Cloud SDK and make sure that you call that rather than the build-pack's version, which is from 2014!

Time to update your build-pack I think!

**Comment by mjackson** [comment]
Sorry for commenting on an old closed issue, but I thought someone who stumbled on this issue in the future might find this gist useful: https://gist.github.com/mjackson/5887963e7d8b8fb0615416c510ae8857

It's the bare minimum you'll need if you want to get an updated gcloud + kubectl running on Travis that is also cached between builds. And it avoids the `gcloud.sh` hack too :)
