### ISSUE TITLE
Android Ddmlib is too aggressive with timeouts (RE-OPEN)

### ISSUE THREAD

**Issue by SjoerdvGestel** [travis-ci/travis-ci#5532]
Using an emulator inside of the virtual environment to perform tests on makes the build fail in 90~95% of the time due to com.android.builder.testing.api.DeviceException: com.android.ddmlib.ShellCommandUnresponsiveException
 using ADB_INSTALL_TIMEOUT won't change the issue

**Comment by BanzaiMan** [comment]
Based on recent comments in https://github.com/travis-ci/travis-ci/issues/3110, I don't think there is much for us to do on this.

**Comment by SjoerdvGestel** [comment]
actually, i found a way around it by using adb install apk
