### ISSUE TITLE
Build log is incomplete on error

### ISSUE THREAD

**Issue by jawshooah** [travis-ci/travis-ci#5535]
Frequently, when a build errors out, the log seems to be truncated before any information about the error can be printed. This behavior is similar to #2346, except that we aren't calling `exit` directly from `.travis.yml`. Instead, we have a set of scripts, one for each build phase, each of which uses `set -o errexit` and `set -o pipefail` to ensure that errors are caught.

Here is an example of a build failure with truncated output: https://travis-ci.org/caskroom/homebrew-cask/jobs/105726356

For reference, here is our [before_install.sh](https://github.com/caskroom/homebrew-cask/blob/aef08d685288beeba820c6d47fa67b4c709bfbfa/ci/travis/before_install.sh).

**Comment by BanzaiMan** [comment]
You are [sourcing](https://github.com/caskroom/homebrew-cask/blob/aef08d685288beeba820c6d47fa67b4c709bfbfa/ci/travis/before_install.sh#L9) `helpers.sh`, which [sets `errexit`](https://github.com/caskroom/homebrew-cask/blob/aef08d685288beeba820c6d47fa67b4c709bfbfa/ci/travis/helpers.sh#L9).

So if you run the script and any command exits with non-zero, the build stalls without a chance to finish.

**Comment by jawshooah** [comment]
Wow, can't believe I didn't catch that. I knew we were sourcing the scripts instead of running them, but somehow it didn't click that as a result, setting `errexit` in `helpers.sh` would override whatever custom error handling you guys had set up. Thanks!

**Comment by jawshooah** [comment]
Ah, now I remember why we had to source the scripts instead of running them: environment variables set in `before_install.sh` do not carry over into subsequent scripts when they are run rather than sourced. See [this failed build](https://travis-ci.org/jawshooah/homebrew-cask/jobs/107096639) for an example. Why is this? Seems counterintuitive that Travis should reset the environment between build phases.

Anyway, I reverted the change above and tried a different approach: I [removed the lines setting `errexit` and `pipefail`](https://github.com/jawshooah/homebrew-cask/commit/a25dbded248bee44567010b4ea0673efe38efb77) and [added a line in `before_install.sh` to explicitly return a non-zero exit code](https://github.com/jawshooah/homebrew-cask/commit/26671e4d208df83aed6c1c03ad06ee8a6e9b7a82), hoping that Travis would fail the build when it reached this line. Unfortunately, [it did not](https://travis-ci.org/jawshooah/homebrew-cask/jobs/107100910), counter to the [documentation](https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build):

> If before_install, install or before_script return a non-zero exit code, the build is errored and stops immediately.

So I'm stuck at a crossroads:
+ If I set `errexit` and run the scripts rather than sourcing them, all environment variables set in `before_install.sh` are lost by the time we get to `install.sh`.
+ If I set `errexit` and continue to source the scripts, I get the problem that was the original impetus for opening this issue.
+ If I do not set `errexit` and continue to source the scripts, the build will not error out as expected if a command in `before_install.sh` fails.

What do you suggest I do here?

**Comment by BanzaiMan** [comment]
When you run `before_install.sh`, it is a separate process, so the environment variables that you set in it stay and die with it. If you want to share your custom environment variables, you need to set it in the build script level (via `env`, or whatever).

The exit status of `before_install.sh` is the exit status of the last command in the script. In https://github.com/jawshooah/homebrew-cask/blob/26671e4d208df83aed6c1c03ad06ee8a6e9b7a82/ci/travis/before_install.sh#L69, I see that it is `exit_build.step`. This [`false`](https://github.com/jawshooah/homebrew-cask/blob/26671e4d208df83aed6c1c03ad06ee8a6e9b7a82/ci/travis/before_install.sh#L21) does not halt the execution of your script.
