### ISSUE TITLE
Unbound variable in /home/travis/build.sh

### ISSUE THREAD

**Issue by ChickenNuggers** [travis-ci/travis-ci#5537]
```
/home/travis/build.sh: line 24: $1: unbound variable
```
From: [105820734](https://travis-ci.org/ChickenNuggers/Astronomy/jobs/105820734)

**Comment by ChickenNuggers** [comment]
`travis_cmd lua\ -v --assert --echo --timing` is what appears to be breaking it.

**Comment by BanzaiMan** [comment]
Duplicate of #5434.

**Comment by BanzaiMan** [comment]
See https://github.com/ChickenNuggers/Astronomy/blob/0ed498e9e622d17dba87a5fac55ac44f5d9443e2/.travis/setup_lua.sh#L3
