### ISSUE TITLE
White screen and nothing but

### ISSUE THREAD

**Issue by Dekken** [travis-ci/travis-ci#5539]
When I login, I get the "getting_started" page, and nothing but white

```
 <h1>Hey there!</h1>
          <p>Looks like you have JavaScript disabled.</p>
          <p>The Travis CI webclient needs JavaScript to work properly.</p>
          <h2>Please enable JavaScript to get the best Travis CI experience.</h2>
          <h3>Thank you!</h3>
        </div>
```

I have js enabled.

Chrome Latest, Windows and #!++

travis-ci.com or org

**Comment by clekstro** [comment]
From [MDN](https://developer.mozilla.org/en/docs/Web/HTML/Element/noscript), it seems like this has to be an issue in your browser. That content will only appear if you have scripting disabled. Are you still experiencing this, and, if so, is it possible you have a browser plugin installed that disables JS?

**Comment by Dekken** [comment]
I get the "Looks like you have Javascript disabled" on every page when not logged in, and I can see content. Once I log in I get nothing. 

http://www.enable-javascript.com says I'm all good. Chrome has JS enabled.

**Comment by clekstro** [comment]
Could you attach a screenshot and any console errors (if present)? Also, what version of Windows/Chrome are you using?

**Comment by Dekken** [comment]
Version 48.0.2564.103 (64-bit)

![2016-02-14--1455449205_1920x1080_scrot](https://cloud.githubusercontent.com/assets/30491/13033432/e64e6eb2-d30d-11e5-9d2b-1cc2909147d1.png)

**Comment by clekstro** [comment]
I'm unable to reproduce this on a fresh Windows 10 install with Chrome.  What browser extensions (beyond Disconnect) do you have enabled?

Here's a screenshot of what I see after signing in:
<img width="1024" alt="screen shot 2016-02-14 at 3 34 30 pm" src="https://cloud.githubusercontent.com/assets/366944/13034240/85932748-d330-11e5-9481-0a0abb7b5419.png">

I'm also using the same version of Chrome, so I don't think that's the issue:
<img width="317" alt="screen shot 2016-02-14 at 3 35 54 pm" src="https://cloud.githubusercontent.com/assets/366944/13034251/b8a94996-d330-11e5-95c1-8b1fe04a88e9.png">

**Comment by Dekken** [comment]
Happens with all extensions disabled.

**Comment by clekstro** [comment]
If all browser extensions are disabled, you should be getting the same results as with a clean install. Do you have any other ideas on what could be causing this?

**Comment by Dekken** [comment]
All I can think of is that it something might have gone a bit screwy with permissions for my main account or organisations

**Comment by clekstro** [comment]
Out of curiosity, do you see anything in the API responses that would indicate that? Is there any difference between your main account or any organizations that you belong to, or do you see this behavior consistently?

**Comment by Dekken** [comment]
I don't, it's just a hunch. How would I see the API responses?

The behavior may not be global. but I don't know how confirm. I don't login to travis as an org, not sure you even can.

**Comment by clekstro** [comment]
You could check out the responses in the Network Tab of your Developer Tools in Chrome. As to the different accounts, I didn't mean logging in as an org, just viewing different screens. Probably isn't relevant though if you see this behavior regardless of what screen/repo/build you visit...

Could you perhaps try uninstalling your extensions and starting from a clean slate? If you still have issues, we could at least confirm that those aren't somehow at fault and start looking into the API responses.

**Comment by Dekken** [comment]
I have tried from chrome incognito mode, and it is the same.
Same in Microsoft Edge, so I doubt it's the extensions.

**Comment by clekstro** [comment]
Sorry to back up, but when did this start? Was this your first attempt to authenticate via GitHub? Or did this only recently start? I'm assuming you've tried to sign out and back in again?

**Comment by Dekken** [comment]
First login, after OAuth and granting permissions

**Comment by Dekken** [comment]
Appears to have fixed itself.
