### ISSUE TITLE
Output memcached package version in logs

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#5541]
I'm currently trying to debug an issue that may be dependant on the memcached server version, however unlike many other packages, the version isn't listed in the "Build system information" section of the logs, or in the section that processes the `services` listed in .travis.yml.

It would be great if both the memcached and libmemcached-dev versions were output.

Many thanks :-)

**Comment by BanzaiMan** [comment]
This will be available in the next build environment update. (No ETA.)

**Comment by edmorley** [comment]
Many thanks! :-)
