### ISSUE TITLE
travis-ci — Waiting for status to be reported

### ISSUE THREAD

**Issue by liuzxc** [travis-ci/travis-ci#5542]
I pushed a new commit to my git repo, but travis-ci build isn't triggered.

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/DYs8x.png

It show:
  
>  continuous-integration/travis-ci — Waiting for status to be reported

but no job is running on travis-ci. It is so strange! 

Anyone has idea for this! Thanks in advance!

**Comment by liuzxc** [comment]
today we tried to reopen the PR, then CI can work normally, but this method doesn't work in yesterday. Cannot find the root cause.

**Comment by jononomo** [comment]
I have the same issue

**Comment by BanzaiMan** [comment]
@jononomo Where is your missing status? If you skip build with `[skip ci]`, for example, you will not see any update beyond the initial "waiting".

**Comment by jononomo** [comment]
@BanzaiMan I figured it out -- I had .travis.yml configured to only check the `staging` branch, but I had github.com configured to not permit PR's to be merged to `master` unless Travis approved.  So this was an impossible configuration.
