### ISSUE TITLE
android build failing to create emulators because no space left on device

### ISSUE THREAD

**Issue by JonasJurczok** [travis-ci/travis-ci#5543]
Hi,

I'm building an android project with travis. I'm using spoon to run tests on multiple devices at the same time. This requires that I start all emulators in the same travis build. The script I'm using for this can be found [here](https://github.com/JonasJurczok/alltrack/blob/master/build.sh#L3). The relevant code are the functions in line 3 and 30.

Installing all the android sdk components works but as soon as I actually create the AVDs the third fails with a disk space error. The corresponding build is [here](https://travis-ci.org/JonasJurczok/alltrack/builds/105996375#L1975). I'm creating sdcards for every emulator with a size of 512mb. So overall my build takes ~2.5gb of disk space just for my stuff + the android sdk. What is the disk size limit(average) or is there a trick to increase it?

Thanks

**Comment by BanzaiMan** [comment]
Could very well be a noisy neighbor on the containers. This is very difficult to get around, unfortunately.

If this happens consistently, I suggest using `sudo: required` so you can have a full VM.

I'm closing this for now.
