### ISSUE TITLE
Feedback about the new Trusty environment

### ISSUE THREAD

**Issue by gsmet** [travis-ci/travis-ci#5545]
Hi,

Following the discussion with Gilles in https://github.com/travis-ci/travis-ci/issues/5520, I took a look at the new Trusty environment to provide feedback.

I'll post here the feedback I have.

**Maven**

Maven is outdated (3.1.1), it would be nice if it could be upgraded.

**JDK**

To install the latest JDK 8, I use:
```
addons:
  apt:
    packages:
      - oracle-java8-installer
```

It runs well. But when the jdk_switcher command is run, I end up with the following error and the build still uses the old JDK (it wasn't the case with the container based build):
```
$ jdk_switcher use oraclejdk8
Switching to Oracle JDK8 (java-8-oracle-amd64), JAVA_HOME will be set to /usr/lib/jvm/java-8-oracle-amd64
update-alternatives: error: no alternatives for apt
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-8-oracle-amd64/bin/apt
$ java -Xmx32m -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_51
```

**Cache**

In the container based environment, I used the cache to cache the `.m2/repository` directory.

Maven is quite verbose and if we don't have a cache, the download lines make the log too long and the build is killed. To avoid this, a lot of projects run a first mvn install with the quiet option to download the artifacts quietly. In the long run, I'm not sure it's a good deal for you as we use more resources running the mvn build twice.

Moreover, not having the cache makes the build really slower (2 times slower in my case from 10 minutes to 20).

HTH

-- 
Guillaume

**Comment by BanzaiMan** [comment]
Thanks for the feedback. In general, please refrain from bunching up disparate issues into one GitHub issue. It makes tracking very difficult.

1. The maven issue is already tracked elsewhere, e.g., #4872.
1. Looks like `jdk_switcher` is failing. Please open a separate issue.
1. The last caching issue seems like an issue with maven. I am happy to explore improvements, but I am not yet sure how that would look.

**Comment by koppor** [comment]
For the googlers landing here, #5897 is the issue treating `update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-8-oracle-amd64/bin/apt`
