### ISSUE TITLE
node-gyp build of node-wrtc that uses clang requires sudo?

### ISSUE THREAD

**Issue by diffalot** [travis-ci/travis-ci#5546]
Can you advise me how to avoid using sudo in a node project that installs the wrtc module?

I'd really like to be able to use the container infrastructure to cache the node_modules folder, but since i cannot get npm install to run without also enabling sudo, my builds are using an excessive amount of your compute time.

It seems that node-gyp is unable to complete installing a sucessfully built libwrtc (the build process downloads and uses a correct clang version with chromium's depot_tools/NINJA) when I try to build on the container infrastructure.  The specific error is [`../node_modules/nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler`](https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106074488#L140)

of course, this leads me to #4771 on this repo which suggest that I install g++-4.8 from ubuntu-toolchain-r-test, but when I follow those directions and set environment variables for g++ and/or gcc, the [node-gyp build fails when it tries to build with g++ instead of clang](https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106077229#L259).

you can view all my futile attempts in diffalot/travis-test-node-webrtc#2

**Comment by BanzaiMan** [comment]
I don't see any of your builds using a recent version of clang. See https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements. (This is shown in https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106074488#L86).

Closing this.

**Comment by diffalot** [comment]
thank you, @BanzaiMan, that's some key information, and I'm sorry I missed both those docs and that error.

:100:
