### ISSUE TITLE
failed to install luasec through luarocks

### ISSUE THREAD

**Issue by houqp** [travis-ci/travis-ci#5548]
Hi travis-ci team,

I ran into a strange issue today. Our build suddenly start to fail on following step:

```
travis_retry luarocks --local install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
```

link for the build: https://travis-ci.org/koreader/koreader/builds/106150004
build error log:

```
Installing http://luarocks.org/repositories/rocks/luasec-0.5.1-1.rockspec...
Using http://luarocks.org/repositories/rocks/luasec-0.5.1-1.rockspec... switching to 'build' mode
Cloning into 'luasec'...
remote: Counting objects: 115, done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 115 (delta 36), reused 49 (delta 7), pack-reused 0
Receiving objects: 100% (115/115), 64.86 KiB | 0 bytes/s, done.
Resolving deltas: 100% (36/36), done.
Checking connectivity... done.
error: pathspec 'luasec-0.5.1' did not match any file(s) known to git.
Error: Failed checking out tag/branch from git repository.

The command "luarocks --local install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu" failed 3 times.
```

We haven't changed anything in `.travis.yml` for awhile  and running the above command locally on my laptop works without any error:

```
 $ luarocks --local install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu                                                                                                                                               
Installing http://luarocks.org/repositories/rocks/luasec-0.5.1-1.rockspec...
Using http://luarocks.org/repositories/rocks/luasec-0.5.1-1.rockspec... switching to 'build' mode
Cloning into 'luasec'...
remote: Counting objects: 103, done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 103 (delta 32), reused 41 (delta 3), pack-reused 0
Receiving objects: 100% (103/103), 60.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (32/32), done.
Checking connectivity... done.
Note: checking out '47cc914e693af56b0e78a023325d7b2b02726010'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

gcc -O2 -fPIC -I/home/dave/.local/include -c src/x509.c -o src/x509.o -I/usr/include -Isrc/ -Isrc/luasocket
```
I noticed that the remote objects count is different from the travis build log (103 vs 115). Is it because the build in travis checked out a wrong git repo?

**Comment by mpeterv** [comment]
This is not a problem in travis. A new version of luasec has been released that doesn't provide a source rock as of yet. So, luarocks uses a rockspec and tries to fetch the sources from luasec git repo. Locally you have a newer version of luarocks that runs `git clone --depth=1 git://github.com/brunoos/luasec.git --branch=luasec-0.5.1` to get only the branch it needs. On Travis you use luarocks from apt-get, which is old and runs `git clone --depth=1 git://github.com/brunoos/luasec.git`; that explains the difference in git object numbers. As git on Travis is fairly new, `checkout` then fails because of `--depth=1`. The solution is to somehow install a newer version of luarocks.

**Comment by BanzaiMan** [comment]
Sounds like this can be closed.

Let us know if there is something on our side to do.

**Comment by houqp** [comment]
Thanks @mpeterv for the help :)
