### ISSUE TITLE
sudo and write permissions on /var/lib/gems

### ISSUE THREAD

**Issue by wsfulton** [travis-ci/travis-ci#5549]
I am using:
```
language: cpp
sudo: required
dist: trusty
```
and running the following to try out ruby 2.3 for some C extensions:
```
sudo apt-get -qq install python-software-properties
sudo add-apt-repository -y ppa:brightbox/ruby-ng
sudo apt-get -qq update
sudo apt-get -qq install ruby2.3 ruby2.3-dev
sudo gem pristine --all

```
I get the following error running the last in the script
```
ERROR:  While executing gem ... (Gem::FilePermissionError)

    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
```
I have used ```sudo: required```. What more do I need to do?

**Comment by BanzaiMan** [comment]
Does this happen on a plain Trusty box I'd you go through these steps?

**Comment by wsfulton** [comment]
Yes the same problem occurs on a plain old Trusty box... there is no /var/lib/gems directory. 

We've taken a different approach now and use ```rvm install 2.3.0```. That works nicely and 2.3.0 is available on Travis according to http://rubies.travis-ci.org/.
