### ISSUE TITLE
Two builds with clang-3.7 have the same content but build result is different

### ISSUE THREAD

**Issue by jirkadanek** [travis-ci/travis-ci#5551]
I updated my clang version in .travis.yml after reading #3478.

My first build (job 12) https://travis-ci.org/jirkadanek/pachi/jobs/106184412 failed with

    /bin/sh: 1: clang-3.7: not found

My second build (job 13) https://travis-ci.org/jirkadanek/pachi/jobs/106186368 compiled fine and failed on unit tests (which I expected)

If you look what is different https://github.com/jirkadanek/pachi/compare/ec9fd1062a1b...3a21b783d8f5 it is one word in the README (which I changed to force recompile).

What did I do wrong? Why the build failed first and succeeded afterwards.

**Comment by BanzaiMan** [comment]
Your failing build did not install the packages. https://travis-ci.org/jirkadanek/pachi/jobs/106184412#L178

So it is expected that the build failed. https://github.com/travis-ci/travis-ci/issues/5077 proposes a different behavior (that the build should fail immediately if `apt-get install` fails).
