### ISSUE TITLE
Spelling mistake: "maxmimum"

### ISSUE THREAD

**Issue by sjackman** [travis-ci/travis-ci#5553]
Should be "maximum".

`The job exceeded the maxmimum time limit for jobs, and has been terminated.`

https://travis-ci.org/Linuxbrew/linuxbrew/builds/106142678

**Comment by saltinejustine** [comment]
Hey @sjackman, thanks for catching that!

@drogus or @lislis, one of you wanna look at correcting this spelling error?

**Comment by lislis** [comment]
Hey there @sjackman! Thank you for reporting his! The good news: It's already fixed https://github.com/travis-ci/worker/pull/158  
Dlosing this.

**Comment by sjackman** [comment]
Nice. Thanks.
