### ISSUE TITLE
python unittest / nosetests stalls after tests succeed

### ISSUE THREAD

**Issue by parente** [travis-ci/travis-ci#5555]
I (and some others) are having a problem running the stock python unittest module (or nosetests) in Python 3.4 and 3.5. After the test runner prints that all tests have passed, the build stalls. I've confirmed that the script does not move onto the next step or even continue with another command on the same step (e.g., `python -m unittest discover && echo 'DONE'`). 

Here's a few logs of the problem from jupyter-incubator/kernel_gateway and jupyter/notebook.

* https://api.travis-ci.org/jobs/106384918/log.txt?deansi=true
* https://s3.amazonaws.com/archive.travis-ci.org/jobs/105621460/log.txt
* https://s3.amazonaws.com/archive.travis-ci.org/jobs/106174482/log.txt

The problem never appears to happen against Python 2.7 or 3.3, only against 3.4 and 3.5. And I'm never able to reproduce the problem locally.

The symptoms look a lot like those from #3336, but there's no HTTPPretty in any of the failure cases that I've seen.

**Comment by parente** [comment]
And for what it's worth, I cannot reproduce the problem in a local `quay.io/travisci/travis-python` container in which I run bash followed by all the commands from https://github.com/jupyter-incubator/kernel_gateway/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
Email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.

Thanks.

**Comment by joepvd** [comment]
Closing.
