### ISSUE TITLE
Build fails on Precise Pangolin (12.04) but succeds on Trusty Tahr (14.04)

### ISSUE THREAD

**Issue by timbru31** [travis-ci/travis-ci#5557]
Hi,
I'm having issues running my tests on Travis CI.

The following build succeeds (``build 23``)
https://travis-ci.org/timbru31/mp3lyrics/builds/106412923

The following build fails (``build 24``)
https://travis-ci.org/timbru31/mp3lyrics/builds/106413286

The change between ``build 23 and 24``
https://github.com/timbru31/mp3lyrics/commit/41c03ebc1503861adf9b094e3b96f6ac0cd29a71

I've downloaded and installed a fresh copy of 12.04.5 LTS and run my tests, they were working fine.

Relevant stack trace
```
EOFError: end of file reached
    /home/travis/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'
    /home/travis/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
    /home/travis/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
    /home/travis/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
    /home/travis/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
    /home/travis/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
    /home/travis/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
    /home/travis/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
    /home/travis/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
    /home/travis/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1384:in `request'
    /home/travis/build/timbru31/mp3lyrics/lib/wiki.rb:12:in `fetch'
    /home/travis/build/timbru31/mp3lyrics/lib/azlyrics.rb:12:in `get_lyrics'
    /home/travis/build/timbru31/mp3lyrics/spec/azlyrics_spec.rb:32:in `block (3 levels) in <top (required)>'
```

Making the http request via ``irb`` works fine, too.

Is there something wrong with the Travis CI machine?
Note: There is no 3XX to a https site.

Can I debug this issue myself, too?
Thanks in advance,

Tim

**Comment by BanzaiMan** [comment]
Your tests are making HTTP connexions. Most likely your external resources were unavailable during the time the failing tests ran.
