### ISSUE TITLE
ruby-head does not find libgmp on container images

### ISSUE THREAD

**Issue by eregon** [travis-ci/travis-ci#5560]
See https://travis-ci.org/ruby/spec/jobs/105388767 as a failure.
`libgmp` is installed on these machines though as the Travis run in https://github.com/ruby/spec/pull/185 shows, but maybe at a different location than on the travis-rubies builder.
Nobu left some comment on that PR which might help solving this.
It would be interesting to `ldd` the Ruby binary to see where it looks for libgmp.

**Comment by eregon** [comment]
Running `ldd ruby` on https://s3.amazonaws.com/travis-rubies/binaries/ubuntu/12.04/x86_64/ruby-head.tar.bz2 gives:
```bash
~/tmp/ruby-head/bin ∴ ldd ruby
	linux-vdso.so.1 (0x00007ffc6d5d4000)
	libruby.so.2.4 => /home/eregon/tmp/ruby-head/bin/./../lib/libruby.so.2.4 (0x00007fd61bf28000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd61bb3a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd61b91e000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fd61b716000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fd61b49d000)
```

So it would seem the builder has `/lib64/libgmp.so.10` but not the image.
If ruby-head is built on a standard image then this should not happen, right?

**Comment by BanzaiMan** [comment]
@eregon Could you try re-running the job?

**Comment by eregon** [comment]
@BanzaiMan I tried, but it failed the same way.

**Comment by BanzaiMan** [comment]
@eregon I tweaked the build process again, this time with RVM "stable", rather than "head", to package ruby-head. Could you try again?

**Comment by eregon** [comment]
@BanzaiMan This worked, awesome! Thanks!

**Comment by eregon** [comment]
@BanzaiMan This happened again, in https://travis-ci.org/ruby/spec/jobs/119486278.
I would guess rvm "stable" now includes the problematic change.

In general, I would recommend a simpler way to build MRI, but I am not sure if that's a reasonable change to make.

**Comment by eregon** [comment]
https://travis-ci.org/travis-ci/travis-rubies/jobs/119527480#L638 shows that the rdiscount check is skipped, which means installing C-ext is not tested.

**Comment by eregon** [comment]
https://travis-ci.org/ruby/spec/builds/119756305 shows the same failure by trying to install `rdiscount`, so current ruby-head is broken for everyone for native ext it would seem.

**Comment by eregon** [comment]
@BanzaiMan See https://github.com/travis-ci/travis-rubies/pull/16 as a possible fix.

**Comment by eregon** [comment]
Closed by https://github.com/travis-ci/travis-rubies/pull/16.
