### ISSUE TITLE
"Active branches" view out-dated

### ISSUE THREAD

**Issue by pohly** [travis-ci/travis-ci#5561]
The "Branches" overview of https://travis-ci.org/01org/meta-intel-iot-security/branches shows several "Active Branches" which have already been removed at https://github.com/01org/meta-intel-iot-security

How quickly should that change get detected by TravisCI, if at all? So far it has been more than half an hour; I would have expected it to be nearly instantaneous, as with other changes.

Worse, a new branch was not showing up at all ("travis-local"). I was experimenting with .travis.yml on that branch, so I might have broken the syntax of that file. Therefore I reverted the changes in a separate commit and that made the branch appear. If a syntax error really was the reason (don't know yet, nothing obvious stands out in the diff), what is the expected error reporting?

Silently ignoring the branch is confusing; IMHO it would be better to list the branch with an error message.

**Comment by pohly** [comment]
The "travis-local" indeed did not show up because of a syntax error:
```
- `pwd`/foobar
```
is not valid.

**Comment by GandaG** [comment]
Go to your account page and click "Sync account". That should solve it.

**Comment by pohly** [comment]
"Sync account" fixed it. However, is that the solution or merely a workaround?

**Comment by GandaG** [comment]
As far as I can tell, solution. It does sync automatically but sparingly.

**Comment by pohly** [comment]
@GandaG Thanks. Then I guess it works as designed and I can close the issue ;-}
