### ISSUE TITLE
long wait for build start on objective-c

### ISSUE THREAD

**Issue by sunekaae** [travis-ci/travis-ci#5563]
I'm quite new to travis-ci. I've set it up for an objective-c project: https://github.com/sunekaae/bean-on-the-screen
here's my travis log: https://travis-ci.org/sunekaae/bean-on-the-screen/builds

As soon as I push the code change, the travis recognizes this and says that the build has been created. But instead of the log it says "Hang tight, the log cannot be shown until the build has started". I'm waiting approx 5 minutes. Then eventually/sometimes the build actually starts, and the metric just says something like 5 seconds, ie the time it took for the build itself, not the whole wait time.

I was thinking the configuration was broken, but perhaps it's just very slow to allocate a VM to run the build? what can I do?

**Comment by sunekaae** [comment]
this morning the wait time for the build to start is shorter, approx 1 minute. At least at this point I no longer think it's broken.

Would be very useful with a) indication of total time in the build history (instead of just the time it took to build once the instance was up) and b) an indication of what's going on when staring at the build starting (and showing no log)

**Comment by BanzaiMan** [comment]
The wait for the Mac builds' start is usually an indication that we have hit the capacity on builds. We are working to add more, but until we do, when there is a large demand, you will see the delay every now and then.

So, for the moment, please be patient.

**Comment by BanzaiMan** [comment]
The wait time should be reasonable these days. I'm closing this optimistically.

**Comment by maqui01** [comment]
Hi @BanzaiMan , is it possible that right now is taking waaay much more than usually? It's been waiting for +20 min. Thanks!

**Comment by BanzaiMan** [comment]
@maqui01 Yes, on .org builds, we have a bit of back log. "Active OS X Builds for Open Source Projects" on https://www.traviscistatus.com/ shows you how many Mac jobs we are running.

**Comment by livecano** [comment]
I've been experimenting a long wait over the past days in any of my iOS builds. Have you guys look into this issue again?

**Comment by jakirkham** [comment]
See this [thread]( https://www.traviscistatus.com/incidents/nf3tg08pqg2d ).

**Comment by livecano** [comment]
Thanks @jakirkham

**Comment by jakirkham** [comment]
Of course. 😄

**Comment by jakirkham** [comment]
Though I have to say I've seen really long queue times (e.g. several hours) with Linux Container builds. Yet there doesn't seem to be anything reported on that. Are there issues globally?

**Comment by fulldecent** [comment]
The backlog would be more helpful if it were measured in number of minutes, rather than number of jobs.

Also, "Hang tight, the log cannot be shown until the build has started." would be more helpful if it included a link to the status page showing the expected number of minutes of backlog.

Also, these may help with upselling to paid accounts. Because now people just keep reloading the "Hang tight" message and assume that something is broken.

**Comment by fulldecent** [comment]
@BanzaiMan Because this prior comment includes something that could objectively improved (and generate revenue), I humbly request that this issue be reopened.

**Comment by bryanboyko** [comment]
I humbly +1 the last request from @fulldecent. 10+ min wait times for builds to start today.

**Comment by guitcastro** [comment]
Please reopen this issue, it's obvious that sometimes build get stuck in queue, we do understand that this will happen eventually, but for god sake, give us some feedback.
