### ISSUE TITLE
[macos request] Add ccache to macos/xcode images

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#5567]
ccache can be installed through homebrew so there shouldn't be much of a problem to add it.

**Comment by thedrow** [comment]
I can't find where to add it in the cookbooks myself so I'm gonna leave this to you guys.

**Comment by thedrow** [comment]
@BanzaiMan Can you point to the place in the cookbooks where ccache is installed?

**Comment by BanzaiMan** [comment]
@thedrow Mac images do not use cookbooks.

**Comment by randombit** [comment]
It would be great if the OS X build images could ship with ccache out of the box, since doing `brew update && brew install ccache` takes on the order of 2-3 minutes on the host.

**Comment by charliegracie** [comment]
Would it be possible to get ccache installed in the OS X build images to reduce the time for OS X builds?  The 2-3 minutes spent installing ccache is likely a large percentage of the total build time for a lot of projects.  If this time was removed the hosts would likely be able to complete more builds every day and hopefully reduce the OS X backlog.

**Comment by tooomm** [comment]
Can you adjust your title maybe @thedrow?
Travis asks for a `[macos request]` tag, see https://blog.travis-ci.com/2017-12-06-xcode-92-has-landed
Maybe it helps speeding things up. 😛 

`[macos request] Add ccache to macos/xcode images`

**Comment by thedrow** [comment]
@BanzaiMan Any update on this one? Has it been implemented but the issue was forgotten?

**Comment by diegoferigo** [comment]
@BanzaiMan Having ccache working also with XCode would be amazing :heart_eyes:

**Comment by tooomm** [comment]
bump

**Comment by junghans** [comment]
Adding a block like:
```
before_script:
  - if [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
      brew update;
      export HOMEBREW_NO_AUTO_UPDATE=1;
      brew ls --versions ccache   > /dev/null || brew install ccache;
      export PATH=/usr/local/opt/ccache/libexec:$PATH;
    fi
```
does the trick for me.

**Comment by charliegracie** [comment]
@junghans I believe most people are already doing that.. The issue with installing it every time, is that it slows down the execution of a job.  Running `brew update` and `brew install ccache` can take than some projects full testing, which is effectively doubling the time to run the tests... This increased time puts extra stress on getting OS X builds to start on Travis that could be improved if ccache was just installed in the base image.

**Comment by junghans** [comment]
@charliegracie you are absolutely right, just left the code block there for convenience.

**Comment by diegoferigo** [comment]
bump

**Comment by BanzaiMan** [comment]
Does the Homebrew addon work for you?

```yaml
addons:
  homebrew:
    packages:
      - ccache
```

**Comment by thedrow** [comment]
I guess it does, but we shouldn't need it.
Can't you guys simply update the image?

**Comment by junghans** [comment]
Still not solved.

**Comment by junghans** [comment]
> Still not solved.

Still.

**Comment by junghans** [comment]
Still
