### ISSUE TITLE
osx: clang3.7 installed with brew -> killed

### ISSUE THREAD

**Issue by gabyx** [travis-ci/travis-ci#5568]
i have the following :

```
if [ "$CXX" = "clang++" ] ; then 
  brew update || echo "suppress failures in order to ignore warnings"
  brew doctor || echo "suppress failures in order to ignore warnings"
  brew tap homebrew/versions || echo "suppress failures in order to ignore warnings"
  
  brew install xz || echo "suppress failures in order to ignore warnings"
  brew install isl --HEAD || echo "suppress failures in order to ignore warnings"
  brew install --HEAD llvm37 --with-asan --with-clang --with-libcxx --rtti --all-targets || echo "suppress failures in order to ignore warnings"
  export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; 
fi
```

clang takes more than 10minutes to install, and then travis kills the build...
any help with that?

https://travis-ci.org/gabyx/ApproxMVBB/jobs/106820051

**Comment by BanzaiMan** [comment]
Looks like Homebrew is compiling clang from source. You can try writing something to STDOUT while compiling (which will still require compilation on every build), or you can try the pre-built 3.7.0 binary (http://llvm.org/releases/download.html#3.7.0).

We can't change the way Homebrew installs clang, so I'm closing this.
