### ISSUE TITLE
Script failure exposes secure variables on travis_retry

### ISSUE THREAD

**Issue by bezoerb** [travis-ci/travis-ci#5569]
I have the following script inside my .travis.yml
`travis_retry php composer.phar config --global github-oauth.github.com $COMPOSER_AUTH`
Travis exposes the secure variable `$COMPOSER_AUTH` after the second failure.
See: https://travis-ci.org/bezoerb/generator-grunt-symfony/jobs/106783956

(I've already regenerated the token ;))

**Comment by BanzaiMan** [comment]
Since `travis_retry` is a bash function, which cannot preserve positional parameters without interpolating, I do not think we can prevent this kind of issue. The best we can do is document it.

**Comment by bezoerb** [comment]
Thanks. I'll drop the `travis_retry` then.
