### ISSUE TITLE
Eclipse plugin for travis?

### ISSUE THREAD

**Issue by khatchad** [travis-ci/travis-ci#5572]
Would it make sense to have an Eclipse plugin that acts like the travis CLI utility (e.g., viewing the status of builds)?

**Comment by BanzaiMan** [comment]
I do not personally use Eclipse, but I think it would be a great tool for those who do.

We are happy to help you out if you have questions while writing it.

In the mean time, though, I don't think it makes sense to have an issue open here.

@khatchad If you start work on GitHub (or elsewhere), do invite us.

I'm closing this now.

**Comment by khatchad** [comment]
@BanzaiMan What about leaving this issue open but tagging it with "help wanted?" Perhaps someone would be interested in working on it?

**Comment by vatbub** [comment]
Hey guys, any further updates on that one? I would really look forward to see my build status in eclipse.
