### ISSUE TITLE
Ruby builds - version matrix without TEENY version components

### ISSUE THREAD

**Issue by lowjoel** [travis-ci/travis-ci#5581]
Yesterday, I noticed that Precise builds started showing this:

```
$ rvm alias create 2.0 ruby-2.0.0-p648
ruby-2.0.0-p648 is not installed.
Creating alias 2.0 for ruby-2.0.0-p648....
$ rvm alias create 2.1 ruby-2.1.8
ruby-2.1.8 is not installed.
Creating alias 2.1 for ruby-2.1.8....
$ rvm alias create 2.2 ruby-2.2.4
ruby-2.2.4 is not installed.
Creating alias 2.2 for ruby-2.2.4....
$ rvm alias create 2.3 ruby-2.3.0
ruby-2.3.0 is not installed.
Creating alias 2.3 for ruby-2.3.0...
```

So I've removed the exact version numbers from .travis.yml in my project (Coursemology/Coursemology2#771; I subsequently learnt that Rails has done the same: rails/rails#23502) Today, those lines seem to be missing, so 2.1 is now 2.1.5, and 2.2 is 2.2.0, and 2.3 is... not found.

This seemed to have happened around 5 Feb 2016 2200hrs UTC (by looking at the historical builds in Rails)

What's the behaviour that we should expect (and the version strings we ought to place in .travis.yml)?

**Comment by tagliala** [comment]
Just noticed the same behaviour

https://travis-ci.org/enriclluelles/route_translator/builds/107319065

This could be slightly related to #5580

**Comment by BanzaiMan** [comment]
We rolled this change back, until such time we can safely roll these versions out.

**Comment by lowjoel** [comment]
@BanzaiMan any timeline? Are we talking days or weeks or months (or years?)

**Comment by BanzaiMan** [comment]
I have no idea.

**Comment by BanzaiMan** [comment]
We rolled this change back.
