### ISSUE TITLE
Simple TeX errors in R package build: fullpage.sty not found

### ISSUE THREAD

**Issue by zkamvar** [travis-ci/travis-ci#5585]
community:R

I was redirected here by @jimhester from an issue I placed earlier on r-travis: https://github.com/craigcitro/r-travis/issues/172

My vignettes are failing to build because fullpage.sty is not found.

This is the last run that worked: https://travis-ci.org/grunwaldlab/poppr/builds/104170589
Suddenly, yesterday, this run did not work because of the error above: https://travis-ci.org/grunwaldlab/poppr/builds/107399219#L1307

I attempted to use `tlmgr install preprint` ([see my .travis.yml](https://github.com/grunwaldlab/poppr/blob/47099b770ef3eb23e300e063162aeac1d5b848c4/.travis.yml)) to see if that would make the error go away, but it appears that [preprint already exists in the TeX packages natively installed](https://github.com/yihui/ubuntu-bin/blob/master/TeXLive.pkgs).

There is likely a simple solution for this, but I can't seem to find it.

**Comment by jimhester** [comment]
It looks like your vignettes use a number of packages that are not in the default list.

```shell
> wget 'https://raw.githubusercontent.com/yihui/ubuntu-bin/master/TeXLive.pkgs'
> grep -h '\usepackage' vignettes/*Rnw | perl -ne 'if (/\\usepackage\{(.*)\}/){ print "$1\n"; }' | awk '!a[$0]++' > used_pkgs
> grep -vFf TeXLive.pkgs used_pkgs | xargs echo
graphicx array color fullpage makeidx longtable natbib bm
```

So try running
```shell
tlmgr install graphicx array color fullpage makeidx longtable natbib bm
```
And see if that fixes the error.

**Comment by zkamvar** [comment]
Unfortunately, the error is not fixed that way.

Here's the [latest run](https://travis-ci.org/grunwaldlab/poppr/builds/107511741):

```
$ tlmgr install graphicx array color fullpage makeidx longtable natbib bm
tlmgr: package repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet
tlmgr install: package array not present in repository.
tlmgr install: package bm not present in repository.
tlmgr install: package color not present in repository.
tlmgr install: package fullpage not present in repository.
tlmgr install: package graphicx not present in repository.
tlmgr install: package longtable not present in repository.
tlmgr install: package makeidx not present in repository.
tlmgr install: package already present: natbib
tlmgr: action install returned a warning.
```
