### ISSUE TITLE
Stuck build - cannot be killed

### ISSUE THREAD

**Issue by jhalterman** [travis-ci/travis-ci#5586]
We have a build on a pull request that appears to be stuck, and there's no obvious way to kill it:

https://travis-ci.org/atomix/atomix/builds/107393880
https://github.com/atomix/atomix/pull/109

Any way to kill this?

**Comment by kuujo** [comment]
I pushed a new commit. It restarted the build with that commit and the kill button reappeared. However, for reference here's a screenshot I took of the state of the Travis UI.

![Travis UI](http://imgur.com/LTdK4mN)

**Comment by BanzaiMan** [comment]
Sorry for the delay. The build state was not updated after the job was canceled. I fixed this manually just now.

**Comment by jhalterman** [comment]
@BanzaiMan Aside from a manual fix, hopefully there's a more permanent fix if this case pops up again?

**Comment by BanzaiMan** [comment]
There is an internal issue to track it. Thanks.
