### ISSUE TITLE
Un-needed `bash --version` being run in generic

### ISSUE THREAD

**Issue by client9** [travis-ci/travis-ci#5587]
Hello, thanks for a great service.  I found one minor issue when using  `language: generic`.  It appears to always do a `bash --version` but I'm not sure why this is done and makes the output noisy.

For example, using this github repo  https://travis-ci.org/client9/hjson we have...

```
$ git clone --depth=50 --branch=master https://github.com/client9/hjson.git client9/hjson
$ bash --version  <--- ???? why
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ my-stuff....
```

My system / worker info is:

```
Worker information
hostname: travis-worker-gce-org-prod-8:77f3bc17-01af-47de-af7e-dd62a6a0d773
version: v2.1.0-44-ge7ef5db https://github.com/travis-ci/worker/tree/e7ef5db4f469f8e76792dee8309e601b6e53e56b
instance: testing-gce-95bdef70-e2d5-4de6-a22b-054269d7a608:travis-ci-minimal-trusty-1447278780
startup: 21.29479393s
system_info
Build system information
Build language: generic
Build group: stable
Build dist: trusty
etc.
```

I *think* this might be caused by `travis/build/script/generic.rb`  

https://github.com/travis-ci/travis-build/blob/7f088efe2c406722ea0fadb7c0bff4fdb27304cc/lib/travis/build/script/generic.rb

```ruby
module Travis
  module Build
    class Script
      class Generic < Script
        DEFAULTS = {}

        def announce
          sh.cmd "bash --version", echo: true, assert: true, timing: false
        end
      end
    end
  end
end
```

Was this some leftover debugging?  If we want to display the bash info, could we put it in the system-info instead (or just remove it)?

thanks again for a great service,

regards,

n

**Comment by BanzaiMan** [comment]
This is important information for scripts running in `generic`, and I think it should be displayed prominently. In other languages, we display the language runtime version when that information is also available in the Build System Information.

The current display is verbose, though. So shortening this to:

```sh-session
$ bash -c 'echo $BASH_VERSION'
4.2.45(2)-release
```

might be a good compromise.

**Comment by client9** [comment]
@BanzaiMan thanks for your time and your commit!
