### ISSUE TITLE
Default PEAR configuration is incorrect for PHP 5.5 and PHP 5.6 environments on precise VM

### ISSUE THREAD

**Issue by gauthierm** [travis-ci/travis-ci#5589]
See https://travis-ci.org/gauthierm/HTTP_Request2/jobs/107653292

The `pear config-show` command shows that packages installed via PEAR will go in `/home/travis/.phpenv/versions/5.6.17/lib/php/pear` (the `php_dir` setting).

The include path for PHP is, however, incorrectly pointing to `/home/travis/.phpenv/versions/5.6.17/share/pear`. This causes dependencies installed via PEAR to not be found in tests.

To correct this issue, either the pear config should be updated or the default PHP include path should be updated.

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. I think this is related (if not identical) to #5410. Could you review that issue, and close this one if you think that is the case?

**Comment by BanzaiMan** [comment]
Upon further review, I'm pretty sure this is a duplicate.
