### ISSUE TITLE
dev-next branch ignored on specific project only

### ISSUE THREAD

**Issue by silkentrance** [travis-ci/travis-ci#5593]
I have a project where the ``dev-next`` branch is ignored by ``travis-ci``. See https://travis-ci.org/coldrye-es/esaver. Under branches you will not find the ``dev-next`` branch.

I already push deleted the branch and then once again pushed a new commit to that branch to the repository, but still travis will not pick it up.

Am I doing something wrong here?

**Comment by BanzaiMan** [comment]
Looks like you are skipping builds on this branch via commit messages. https://travis-ci.org/coldrye-es/esaver/requests https://github.com/coldrye-es/esaver/commit/522f5fc284d8dc2c2b253b8f32ab6ebd3c80c342

Have we built anything on this branch?

**Comment by silkentrance** [comment]
According to the build history, dev-next has never been build on travis. And ci skips are only when I bump the version in the dev-next branch for the next version in development.
I will investigate this further when a new dev-next release comes up.

**Comment by silkentrance** [comment]
Yeah, it seems I messed things up and pushed multiple commits at once, the last always being the one with the ``[ci skip]`` directive.
