### ISSUE TITLE
Stuck on syncing from Github

### ISSUE THREAD

**Issue by HarrisRobin** [travis-ci/travis-ci#5595]
Hi,

So i've been 'syncing from github' since last night. I saw a few issues related to this here, can someone do a manual sync on my account please?

Thanks!
<img width="811" alt="screenshot 2016-02-08 14 29 14" src="https://cloud.githubusercontent.com/assets/3880008/12896519/6eef5a1c-ce70-11e5-8141-672e6285560a.png">

**Comment by BanzaiMan** [comment]
Is this on .org or .com?

**Comment by HarrisRobin** [comment]
Hi,
this is .org. Should I be on .com? 

Thanks

**Comment by HarrisRobin** [comment]
@BanzaiMan sorry for the spam, but I just realised the difference between the .org and .com. I need to use .org so this is still an issue.

**Comment by BanzaiMan** [comment]
I manually sync'd your account on .org. Should be fine now. If it gets stuck again in the next 24 hours, do let us know.
