### ISSUE TITLE
ssh_known_hosts does not work on OS X

### ISSUE THREAD

**Issue by FiloSottile** [travis-ci/travis-ci#5596]
https://travis-ci.org/FiloSottile/gvt/jobs/107989548

```
Adding ssh known hosts (BETA)
$ ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H bitbucket.org 2>&1 | tee -a $HOME/.ssh/known_hosts
unknown key type ecdsa
```

**Comment by FiloSottile** [comment]
Should be fixed in travis-ci/travis-build@171bb7a, but does not seem to work.

**Comment by FiloSottile** [comment]
Previously reported as #5184 and attacked by PR travis-ci/travis-build#560

**Comment by BanzaiMan** [comment]
I see how the addon fails; it checks the value of `$TRAVIS_OS_NAME` before it is set.

**Comment by BanzaiMan** [comment]
Rearranging the build phase is probably a bit too risky, so we need a different means of testing the OS.

**Comment by FiloSottile** [comment]
$(uname) = 'Linux' should do it?

Also while at it, there should be a way to set the timeout, or have a higher hardcoded one than 5 seconds. It caused me flappy builds with bitbucket.
