### ISSUE TITLE
Build failing on openjdk 1.7.0_75, successful with openjdk 1.7.0_76

### ISSUE THREAD

**Issue by pmauduit** [travis-ci/travis-ci#5599]
Since last week, we are unable to finish our testsuite on openjdk v1.7.0_75, since the maven process is killed by the kernel before the end of the testsuite.

Example of failing build: https://travis-ci.org/pmauduit/georchestra/builds/107865925

The VM is killed by the kernel OOMkiller, which is very strange since nothing significantly changed in our code / testsuite, the only difference we can see is the Java version changed from 1.7.0_76 to 1.7.0_75 (Which is weird, any reason for having downgraded the JDK version ? For the record, a successful build with openjdk7 from last week: https://travis-ci.org/georchestra/georchestra/builds/106223334), and we are quite sure that the testsuite can fit in the 4GB of memory allocated to the docker instances. Anyway we should see an error in the maven output before the Java process being killed if we were draining all the available Xmx, right ?

Any idea of what is going wrong in our builds ?

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #5594, basically. The process is too large and gets killed.

**Comment by pmauduit** [comment]
But that does not make sense because I capped the Xmx to 3072MB (leaving ~ 1GB of physical memory for the system outside of the JVM), if my build was really running out of memory I should hit a "java.lang.OutOfMemoryError: Java heap space" way before being killed by the kernel.

Something should have changed - and not in our side - that we are not aware of, here is a reset on the master branch in my fork, that is failing:
https://travis-ci.org/pmauduit/georchestra/builds/108233287

The same job was successful last week (exactly the same code as previously, same running conditions on travis-ci):
https://travis-ci.org/georchestra/georchestra/builds/106081031

**Comment by BanzaiMan** [comment]
Sorry for the delay. Is it possible that this is a JDK bug?

**Comment by pmauduit** [comment]
It might be ;  when I wanted to try this in a own environment using the same version as the one used on failing builds, I was unable to find it back on the internet.

For now on, we deactivated the failing test ; if the jvm version changed, it might deserve a reactivation.
