### ISSUE TITLE
Support cmake?

### ISSUE THREAD

**Issue by xuhdev** [travis-ci/travis-ci#560]
Would travis-ci support [cmake](http://www.cmake.org)? This is a popular build system for C/C++ projects, shipped with a testing system called "ctest".

Thanks!

**Comment by jedmao** [comment]
@xuhdev, [Cmake now comes out-of-the-box on all Travis CI VMs](http://docs.travis-ci.com/user/ci-environment/#Compilers-%26-Build-toolchain). Of pertinence to you, see [my recent editorconfig-core-js pull request](https://github.com/editorconfig/editorconfig-core-js/pull/23).

**Comment by xuhdev** [comment]
@jedmao Thanks! I'll make relavent changes.
