### ISSUE TITLE
Builds do not finish but are marked successful 

### ISSUE THREAD

**Issue by kaspermarstal** [travis-ci/travis-ci#5600]
I have a fairly large CMake-based C++ project (1+ hour build time) that always exits prematurely with code 0 and marked successful even though the build is far from finished. The builds typically exit after ~10 min. They are not killed, no errors are thrown, they do not time out, they just silently exit. At the moment it happens mainly during an SVN checkout, but sometimes it also happens during compilation. It happens on both Linux and Mac workers. The builds complete as expected on my local machines. 

The build logs are available at https://travis-ci.org/kaspermarstal/SimpleElastix.

This has been a problem ever since I signed up a little over a year ago. Do you have experience with this issue?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem? Maybe you restarted the failing ones and they ran OK, but I can't see what the problem is.

**Comment by BanzaiMan** [comment]
Looks like you are running the command `make --jobs=2 | grep -v '^--' | grep -v '^Installing'`, which I suspect is writing to STDOUT out of order, and your log is somewhat confusing as a result. Also note that `grep -v` is going to return a success if that command sees a line that does not contain `Installing`.

**Comment by kaspermarstal** [comment]
Piping was indeed the problem. Thank you for your time!
