### ISSUE TITLE
Failed to build C extension with importing a library on ruby-head

### ISSUE THREAD

**Issue by marshall-lee** [travis-ci/travis-ci#5601]
I'm reopening #5552. The issue was closed in favor of #5580 since it's probably related to #5552 and is more informative. Now #5580 is closed too but the issue isn't gone.

Yet another fail: https://travis-ci.org/marshall-lee/regressed/builds/108284723
On `ruby-2.3.0` it's okay, on `ruby-head` it fails.

**Comment by BanzaiMan** [comment]
I think this issue with ruby-head is a variation of #5560. There is something weird with the way RVM is packaging things.
