### ISSUE TITLE
Java Unit tests fail for 

### ISSUE THREAD

**Issue by skyem123** [travis-ci/travis-ci#5603]
This is happening for me on https://travis-ci.org/skyem123/skyeZ80emu/builds/108374098
I have had a similar problem before, but it worked after I made it retry the build, however, this does not seem to work, even after clearing the caches and retrying. (in fact, clearing the caches seem to have made it fail a different unit test.... but it is still the same problem of a unit test failing only on Travis)

This is a very strange issue as it compiles and passes unit tests perfectly on my computer:
```
$ ./gradlew --continue check jacocoTestReport
:compileJava
:processResources UP-TO-DATE
:classes
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test
:check
:jacocoTestReport

BUILD SUCCESSFUL

Total time: 6.458 secs
```

It works fine for @gamemanj as well.

**Comment by BanzaiMan** [comment]
For builds on containers, you can try running it locally: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

For GCE and Mac builds, email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.

Thanks.

**Comment by skyem123** [comment]
Oops, I just noticed that I messed up the title. Should I fix it? (and thanks for checking this anyway!)

I'm setting up the Docker and Travis stuff on my computer right now, though the download is taking a long time.

I'll report what happens when I run this locally as soon as I can.

**Comment by skyem123** [comment]
Sorry, I have encountered a problem while trying to test this locally, which isn't related to this at all. The Travis docker container I installed following the guide seems to have JDK7, while my thing needs JDK8. I'm probably missing something incredibly obvious, but I don't know how to get it set up properly.

**Comment by joepvd** [comment]
Closing.
