### ISSUE TITLE
When deploying to pypi, a ` in the password breaks the process

### ISSUE THREAD

**Issue by vegitron** [travis-ci/travis-ci#5604]
When creating my pypi account, I created a random password that included the ` character.  During the deployment phase, there was this error: 

/home/travis/build.sh: eval: line 45: unexpected EOF while looking for matching ``'
/home/travis/build.sh: eval: line 46: syntax error: unexpected end of file

(from https://travis-ci.org/uw-it-aca/uw-restclients/jobs/108349320#L1355 )

Removing the character from the password resulted in a successful deployment:

https://travis-ci.org/uw-it-aca/uw-restclients/jobs/108388576#L1390

**Comment by BanzaiMan** [comment]
Please escape special characters when you encrypt it. This is documented in https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables and https://docs.travis-ci.com/user/encryption-keys#Note-on-escaping-certain-symbols.
