### ISSUE TITLE
Automatically cache ~/.m2 directory for Clojure

### ISSUE THREAD

**Issue by danielcompton** [travis-ci/travis-ci#5606]
Is it possible to automatically cache the `~/.m2` directory for Clojure projects? This would dramatically decrease the load on Maven Central and Clojars.

**Comment by BanzaiMan** [comment]
Currently all caching is enabled by the user. https://docs.travis-ci.com/user/caching/#Arbitrary-directories

We have discussed changing this behavior for the future, but have no ETA.

**Comment by BanzaiMan** [comment]
I'm going to close this as a duplicate of #5571.
