### ISSUE TITLE
JVM aborts with core dump on openjdk6/openjdk7

### ISSUE THREAD

**Issue by andreaceccanti** [travis-ci/travis-ci#5607]
See:
https://travis-ci.org/italiangrid/voms-api-java/jobs/108538776

The project builds fine locally, on our jenkins infra, and on drone.io.

**Comment by BanzaiMan** [comment]
This is a duplicate of #5227. See https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-182530842 for the fix.
