### ISSUE TITLE
Environment variable input in web UI isn't escaped

### ISSUE THREAD

**Issue by tmccombs** [travis-ci/travis-ci#5611]
When entering an environment variable for a repository via the web UI, the text isn't escaped when setting the variable, which means certain characters can cause problems. This isn't at all obvious. Either the values should be escaped, or there should be clearer documentation (especially on the settings page) that the values input are not escaped.

**Comment by BanzaiMan** [comment]
This is documented in https://docs.travis-ci.com/user/environment-variables/. I agree that this should be noted on the Settings page itself. See the PR.
