### ISSUE TITLE
Ruby needs to be installed on every build

### ISSUE THREAD

**Issue by inket** [travis-ci/travis-ci#5613]
Is it possible to have build containers come with ruby preinstalled? This could shave 30~ seconds off build time.

(Unless I'm missing something about configuring travis correctly so that it doesn't have to do that every time?)

**Comment by BanzaiMan** [comment]
It is impractical for disk space considerations to install every Ruby versions out there.

I agree that the image needs to be updated to have more recent versions pre-installed. For that, we must wait for the build env updates. Sorry for the delay about that. There are some complications that are delaying that.
