### ISSUE TITLE
Install linux-headers 

### ISSUE THREAD

**Issue by mpgn** [travis-ci/travis-ci#5616]
I try to setup Travis, my config file is like this:

```
language: c
compiler:
  - gcc
sudo: required
install:
  - apt-get install -y linux-headers-`uname -r`
script:
  - cd bin
  - make
```

Travis block on 

> Hang tight, the log cannot be shown until the build has started.

The job is running, never stop, no log file...

**Comment by BanzaiMan** [comment]
This sounds like a stuck build than a failure to install. Can you restart it? If not, could you point to the build log URL that shows this?

**Comment by mpgn** [comment]
I remove everything, seem Travis is not able to deal with that.
I tested locally with `travis compile` and run the script, everything was ok. 
Remotly with Travis no so i guess it's not possible or it's buggy.

**Comment by mpgn** [comment]
Seem it's working now

```
language: c
compiler:
  - gcc
env: BUILD_KERNEL=3.13.0-63-generic
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y linux-headers-3.13.0-63-generic cmake
  - sudo ln -s /usr/src/3.13.0-63-generic /lib/modules/3.13.0-63-generic/build
script:
  - make
sudo: 
  - required
```
