### ISSUE TITLE
apc.so file not found

### ISSUE THREAD

**Issue by KaffineAddict** [travis-ci/travis-ci#5618]
Builds failing because apc extension cannot be found. Happens in 5.6 and 7

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/7.0.3/lib/php/extensions/no-debug-zts-20151012/apc.so' - /home/travis/.phpenv/versions/7.0.3/lib/php/extensions/no-debug-zts-20151012/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

[Build](https://travis-ci.org/KaffineAddict/PhoneHelper/jobs/108865331)

**Comment by BanzaiMan** [comment]
Did this ever work on PHP 7?

**Comment by KaffineAddict** [comment]
I have never used it before. According to the documentation it should work. It fails in PHP 5.5 and 5.6 as well.

[Documentation](https://docs.travis-ci.com/user/languages/php/#Preinstalled-PHP-extensions)
[5.5 file not found](https://travis-ci.org/KaffineAddict/PhoneHelper/jobs/108865317#L154)
[5.6 file not found](https://travis-ci.org/KaffineAddict/PhoneHelper/jobs/108865323#L154)

**Comment by PHLAK** [comment]
I'm also having trouble getting apc to work for PHP version 5.5, 5.6 and 5.7 

See [this build](https://travis-ci.org/PHLAK/Stash/jobs/121051334#L216) and other builds for this repo.

**Comment by BanzaiMan** [comment]
I think this is a documentation issue. apc, as I understand it, is an old extension that has not been updated in years. http://php.net/apc
