### ISSUE TITLE
Installing packages fails as no "-y" is given to apt-get

### ISSUE THREAD

**Issue by zecke** [travis-ci/travis-ci#5622]
My latest build of zecke/osmo-smsc is failing is an odd way. During the start of the system additional packages are installed and the apt-get call is stuck waiting for something to answer the prompt.

My travis.yml is here (https://github.com/zecke/osmo-smsc/blob/master/.travis.yml) and the latest build is here (https://travis-ci.org/zecke/osmo-smsc/jobs/108884525). The odd part is that I am using the addons to install dependencies and not apt-get myself.

Any idea who is invoking that apt-get and why it is being stuck? It happens during the "Installing dependencies" phase.

**Comment by zecke** [comment]
It happens as soon as the "docker" service is in the .travis.yml. As the apt-get is installed by the platform and not the travis.yml file it might be a platform issue?

**Comment by BanzaiMan** [comment]
The `apt` addon is not effective on Trusty builds, which you get when you add `docker` service. Use `sudo` to install the packages you need.

**Comment by zecke** [comment]
Sure, but the "apt-get" is not coming from me. Is it a result of "language: smalltalk"? Is this community script public and can be changed/extended or how is this integration working?

**Comment by fniephaus** [comment]
This is a Smalltalk-related problem and there's a tracking bug for it at https://github.com/hpi-swa/smalltalkCI/issues/59.

I guess this can be closed.
