### ISSUE TITLE
Docker builds are much slower (2min vs 8min)

### ISSUE THREAD

**Issue by ndmitchell** [travis-ci/travis-ci#5623]
I converted one of my projects to use the new Docker builds. After the conversion to avoid sudo some elements of the matrix started taking 8 min, in contrast to 2 min before. Switching back to `sudo: true` (but not changing anything else) restores the time to 2 min.
- Run with `sudo: false`: https://travis-ci.org/ndmitchell/neil/builds/108995194
- Run with `sudo: true`: https://travis-ci.org/ndmitchell/neil/builds/108997286

Looking at the slowdown, it appears compiling my project (but not the projects I depend on) with the GHC compiler 7.8 or higher goes vastly slower.

**Comment by snowleopard** [comment]
As reported in https://github.com/snowleopard/shaking-up-ghc/issues/229, the slow down on the new Docker infrastructure can be as much as 36x when running GHC: `815.12s` (Docker build) vs only `22.52s` (with `sudo: true`).

**Comment by BanzaiMan** [comment]
Not sure what is causing the slowdown. If you would like to have a look at the VM running the build, we can arrange that. Please email us at support@travis-ci.com.

**Comment by ndmitchell** [comment]
In both cases we are installing our own version of GHC (the Haskell compiler, from https://www.haskell.org/ghc/) and then using it, so it's not your choice of Haskell compiler, and the binary is one of our chosing, so that's not relevant either. I can only guess at less powerful machines? Or some system configuration? (But I'm far from an expert in these things.)

**Comment by fosskers** [comment]
Hot damn, I just had an 18 minute Haskell build drop from 18 minutes to 3 minutes by adding `sudo: true`.

**Comment by ndmitchell** [comment]
I just benchmarked the two different flavours of sudo and it didn't make any difference, both took identical times.
