### ISSUE TITLE
clang: error: unable to execute command: Killed

### ISSUE THREAD

**Issue by erenon** [travis-ci/travis-ci#5624]
I receive the following error in my [clang 3.5 job][0]. This isn't transient, happened 3 times in a row. I can't reproduce the problem using the same clang and ubuntu versions. 

clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Ubuntu clang version 3.5.0-svn217304-1~exp1 (branches/release_35) (based on LLVM 3.5.0)

Target: x86_64-pc-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://bugs.debian.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 

********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:

Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/devector_test-0b95d4.cpp
clang: note: diagnostic msg: /tmp/devector_test-0b95d4.sh
clang: note: diagnostic msg: 

********************

[0]: https://travis-ci.org/erenon/double_ended/jobs/109002985

**Comment by BanzaiMan** [comment]
For builds on containers, you can try running it locally: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

For GCE and Mac builds, email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.

Thanks.

**Comment by joepvd** [comment]
Closing.

**Comment by erenon** [comment]
Is is supposed to be fixed or just closed?

**Comment by BanzaiMan** [comment]
Please try debugging with the build with the image indicated above. Thanks.
