### ISSUE TITLE
Light logo variant currently unavailable, downloads dark variant instead

### ISSUE THREAD

**Issue by clekstro** [travis-ci/travis-ci#5626]
The link to the light logo variant on the logo page (https://travis-ci.com/logo) downloads the dark one instead. It looks like the `href` on [this line](https://github.com/travis-ci/travis-web/blob/master/app/templates/logo.hbs#L17) simply needs to be updated to the correct image, but the light variant doesn't appear to be present amongst the logos [here](https://github.com/travis-ci/travis-web/tree/master/public/images/logos), so I'm assuming it would just need to be added.

Here's a screenshot to clarify which logo this impacts:
![screen shot 2016-02-13 at 11 25 51 pm](https://cloud.githubusercontent.com/assets/366944/13030424/e9103eb8-d2aa-11e5-84fb-2ad5066893ca.png)

**Comment by BanzaiMan** [comment]
A duplicate of #5179.

**Comment by BanzaiMan** [comment]
Or not?

**Comment by clekstro** [comment]
@BanzaiMan I think this is a separate issue. It sounded like the issue there was that all links were downloading the wrong image. At this point, only the light logo link is incorrect.

**Comment by clekstro** [comment]
Looks like this was fixed in [this PR](https://github.com/travis-ci/travis-web/pull/477). Closing.
