### ISSUE TITLE
python build, cython extensions in  c++, need gcc-4.8 in container

### ISSUE THREAD

**Issue by rabernat** [travis-ci/travis-ci#5627]
I am trying to build a [python package](https://github.com/rabernat/floater) on travis-ci. This package includes [cython extensions written in c++](http://docs.cython.org/src/userguide/wrapping_CPlusPlus.html).

This is a [container-based build](https://travis-ci.org/rabernat/floater): my current [.travis.yml](https://github.com/rabernat/floater/blob/travis/.travis.yml)

In order to build the extensions, cython needs to call gcc with the flag ``-std=c++11``. This [requires gcc version 4.7 or later](https://gcc.gnu.org/projects/cxx0x.html). __I can't figure out how to change my gcc version.__

Failed approaches so far:
* Because this is a container-based build, I can't follow other examples (e.g. #1379, #979) of how to install different gcc versions using ``apt``.
* Likewise, because this is a python project, I cannot specify a ``compilers`` key in my ``.travis.yml`` file, as suggested in [the c++ docs](https://docs.travis-ci.com/user/languages/cpp).

This leaves me with with trying to install gcc-4.8 following the instructions for [installing packages on a container-based infrastructure](https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Container-Based-Infrastructure). gcc-4.8 is in the [whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise), so I thought this would work. I added the following to my ``.travis.yml``
```
addons:
  apt:
    packages:
      - gcc-4.8
```
However, as you can see from the [build log](https://travis-ci.org/rabernat/floater/jobs/109212356#L94), this does not work, giving the error ``E: Unable to locate package gcc-4.8``. (This appears very similar to #4911, which was closed with no explanation.)

To me, the failure to install the addons package seems like a bug in travis-ci. At the least, it is in conflict with the [documentation]((https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Container-Based-Infrastructure).

Any advice on how to overcome this and get my build working would be sincerely appreciated.

**Comment by BanzaiMan** [comment]
You need to add the source `ubuntu-toolchain-r-test`. See the example in https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-on-Container-Based-Infrastructure.

**Comment by rabernat** [comment]
Thanks @BanzaiMan! That worked. gcc-4.8 installed.

I'm almost there. However, the command ``gcc`` still points at 4.6.3. Now I just have to figure out how to do the equivalent of ``update-alternatives``.

**Comment by rabernat** [comment]
Update, I was able to get my build to work by using
```yaml
install:
...
  - CC=gcc-4.8 CXX=g++-4.8 python setup.py build_ext
```
