### ISSUE TITLE
Use resized Travis logo on pull requests page

### ISSUE THREAD

**Issue by emirb** [travis-ci/travis-ci#5628]
## Problem
Image of Travis logo appearing under Checks, in any Pull request, is way too big, and slower to download than needed.

## Preview
![image](https://cloud.githubusercontent.com/assets/3412241/13049087/b41e9cea-d3ea-11e5-895e-d74e74403044.png)

## Proposed solution
Replace [this image](https://cloud.githubusercontent.com/assets/30442/25355/92a5d132-91c8-11e5-9860-8e21b91f0ecb.png) with a smaller one, i.e. 32x32px.

**Comment by roidrage** [comment]
Thanks for reporting this. I'm afraid that which image is being used there is out of our hands, as it is pulled by GitHub based on the OAuth application that we have configured.

From what I can tell, they're pulling the 38px version of our logo (https://avatars0.githubusercontent.com/u/639823?v=3&s=38), which is exactly 6020 bytes in size, which doesn't strike me as overly big.

Are you seeing a different image being used?

**Comment by emirb** [comment]
Thanks for your (fast) response. 

I'm seeing big image:
```html
<img alt="" class="avatar" height="19" src="https://cloud.githubusercontent.com/assets/30442/25355/92a5d132-91c8-11e5-9860-8e21b91f0ecb.png" width="19" />
```
That's a 1657x1643 version.

**Comment by BanzaiMan** [comment]
![introduce_ setup_cache _stage_to_all_builds_by_banzaiman_ _pull_request__626_ _travis-ci_travis-build](https://cloud.githubusercontent.com/assets/25666/13050592/11235b3c-d3ba-11e5-805a-df827cfc9a9a.png)

**Comment by roidrage** [comment]
Can you try reloading the page you're looking at? I've looked at several pull requests, and it's using the 38px version.

**Comment by emirb** [comment]
Reloaded by totally clearing the cache, and it's still showing the same image.

![image](https://cloud.githubusercontent.com/assets/3412241/13050825/369f7e36-d3f6-11e5-9fa9-e6601be955c4.png)

Could it be that this happens only for Travis CI image for Private projects?

**Comment by roidrage** [comment]
Blimey, you're right!

I updated the logo there, so it should now be using a smaller one.

**Comment by emirb** [comment]
Great, the image is now correct. Thanks!
