### ISSUE TITLE
Maven build fails after sucessful test run on container build

### ISSUE THREAD

**Issue by mp911de** [travis-ci/travis-ci#5631]
We run into issues that cannot be reproduced locally so far with our Maven-based build. Once all tests pass the Maven build crashes with a message:

```
The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

This seems to happen only remote and only within the container build. We tried to reproduce the issue within a Trusty Vagrant Box and a Docker environment (quay.io/travisci/travis-jvm) without luck so far, all builds here succeeded. Please find some links to the broken/succeeded remote builds attached:

Within the container build:

* https://travis-ci.org/mp911de/spring-data-redis/builds/109333299  
  Less tests, all tests green -> Maven succeeds
* https://travis-ci.org/mp911de/spring-data-redis/builds/109322287  
  All tests green -> Maven fails after tests

legacy build infrastructure:

* https://travis-ci.org/mp911de/spring-data-redis/builds/109362321  
  All tests green -> Maven fails after succeeds

Would it be possible to get a debug dockerized instance from you to connect using a remote debugger so we can investigate the cause?

Thanks, Mark

**Comment by mp911de** [comment]
Any update on this ticket?

**Comment by cyenyxe** [comment]
We were experiencing the same issue and changing the VM heap size limits in the POM file,  as suggested [here](http://stackoverflow.com/questions/23260057/the-forked-vm-terminated-without-saying-properly-goodbye-vm-crash-or-system-exi/33757854#33757854), fixed it:

```
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
                <!-- Travis build workaround -->
                <argLine>-Xms1024m -Xmx2048m</argLine>
            </configuration>
        </plugin>
    </plugins>
```

It would be nice to know if the Travis machines configuration has changed these last days, though.

**Comment by BanzaiMan** [comment]
For builds on containers, you can try running it locally: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

For GCE and Mac builds, email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.

Thanks.

**Comment by joepvd** [comment]
Closing.
