### ISSUE TITLE
npm deployment doesn't allow me to publish with tags

### ISSUE THREAD

**Issue by wirehead** [travis-ci/travis-ci#5632]
I mostly <3 Travis-CI's npm deployment support.  Turned it on for a few of my npm packages this weekend.

However, I'm noticing in [the docs ](https://docs.npmjs.com/getting-started/using-tags) that there isn't anything documented to add a [release tag](https://docs.npmjs.com/getting-started/using-tags) in npm.

Why is this important?  Well, as a package maintainer, I might want to work with the Chrome-style release channels method, such that every checkin to mainline is packaged as "Canary" and for every tagged release to be uploaded as 'dev', at which point I might upgrade that tagged release up through 'beta' to 'stable' as a manual process.

**Comment by BanzaiMan** [comment]
The implementation is here: https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/npm.rb

We welcome your contribution!

**Comment by BanzaiMan** [comment]
Closing this in favor of https://github.com/travis-ci/dpl/issues/415.
