### ISSUE TITLE
Get rid of expired apple certificate

### ISSUE THREAD

**Issue by adrienbrault** [travis-ci/travis-ci#5633]
I cannot upload beta builds to itunes connect (using fastlane), because I am getting the following error:

```
+xcodebuild -exportArchive -exportOptionsPlist /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/gym20160215-5215-y8q54p_config.plist -archivePath '/Users/travis/Library/Developer/Xcode/Archives/2016-02-15/ProjectNative 2016-02-15 16.31.33.xcarchive' -exportPath /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/gym20160215-5215-21vz0e.gym_output
2016-02-15 16:39:51.413 xcodebuild[8207:21684] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/ProjectNativeStaging_2016-02-15_16-39-51.412.xcdistributionlogs'.
2016-02-15 16:39:52.314 xcodebuild[8207:21684] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7fc662bec0b0>: Error Domain=IDEDistributionErrorDomain Code=1 "(null)"
error: exportArchive: The operation couldn’t be completed. (IDEDistributionErrorDomain error 1.)
Error Domain=IDEDistributionErrorDomain Code=1 "(null)"
```

I tried running doing that locally but it failed too. It turns out that doing the following https://www.reddit.com/r/iOSProgramming/comments/45siza/this_certificate_has_an_invalid_issuer/ fixed the issue locally.

Can you apply that to the xcode images ?

**Comment by adrienbrault** [comment]
FYI running the following at the beginning of my build fixes the issue:

```
sudo security delete-certificate -Z 0950B6CD3D2F37EA246A1AAA20DFAADBD6FE1F75 /Library/Keychains/System.keychain
```

**Comment by Sega-Zero** [comment]
[That fix](https://github.com/fastlane/gym/issues/100#issuecomment-184363602) seems working. Please, update xcode images!

**Comment by emdantrim** [comment]
I'm taking a look at this right now -- we had an internal ticket to update the certificate ahead of time, but it slipped through the cracks last week. Sorry for the fuss!

**Comment by BanzaiMan** [comment]
Hello, there. The hot fix with `travis-build` is now live. Please test it, and let us know how it works for you.

**Comment by Sega-Zero** [comment]
fastlane warns that there are still issues with WWDR
> ERROR [2016-02-18 10:33:49.18]: Looks like there are no local code signing identities found, you can run `security find-identity -v -p codesigning` to get this output. Check out this reply for more: https://stackoverflow.com/questions/35390072/this-certificate-has-an-invalid-issuer-apple-push-services

if I run `security find-identity -v -p codesigning` I get this output:
> 0 valid identities found

I think you should better take this gist into consideration: https://gist.github.com/pesterhazy/0c176b6ee28d8fa2a944

**Comment by Sega-Zero** [comment]
It's a fastlane issue, WWDR is fine on a travis machine

**Comment by BanzaiMan** [comment]
I'm closing this now.
