### ISSUE TITLE
Update default pytest version to 2.8.5 for all Python versions

### ISSUE THREAD

**Issue by kynan** [travis-ci/travis-ci#5635]
As of today (15 Feb 2016), the pytest versions are:
* Python 2.6.9: pytest 2.6.4
* Python 2.7.9: pytest 2.6.4
* Python 3.2.5: pytest 2.6.4
* Python 3.3.5: pytest 2.6.4
* Python 3.4.2: pytest 2.6.4
* Python 3.5.0: pytest 2.8.5

Could pytest please be upgraded to 2.8.5 for Python < 3.5 also?

**Comment by kynan** [comment]
FYI pytest >= 2.8 is required e.g. for pytest-flake8 and [it's not possible to require pytest >= 2.8 because the older version is already installed](https://travis-ci.org/kynan/nbstripout/builds/109454060)!

**Comment by BanzaiMan** [comment]
`pytest` was packaged at the time those runtimes are compiled.

**Comment by kynan** [comment]
@BanzaiMan Can you elaborate? Does that mean all those versions are set in stone? Or are there new runtimes released periodically?

**Comment by BanzaiMan** [comment]
The pre-installed runtimes are not going to be updated until a new image is rolled out. (Even then, we may or may not re-package old versions.) If your tests require a new version, you are in a better position to underatand that requirement and update it than our images can.

**Comment by kynan** [comment]
In this case alas not: Python's (or rather setuptools' / distutils') dependency resolution mechanism is not very sophisticated. If there already is an "unsatisfactory" version of a package installed (pytest 2.6.4 in this case) I *cannot* require a different version. The request fails with a

    pkg_resources.VersionConflict: (pytest 2.6.4 (/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages), Requirement.parse('pytest>=2.8'))

So if upgrading is not an option for you, maybe it would be better to *not* provide pytest at all but leave it to the package to sort out its dependencies.

**Comment by BanzaiMan** [comment]
Can't you install a new version in any of the customizable build phase (`before_install`, `install`, `before_script`, `script`)?

**Comment by khughitt** [comment]
Had same issue (`tmpdir_factory` fixture added in 2.8). Adding a `before_install` directive fixed the broken builds:

```
before_install:
  - pip install --upgrade pytest
```

**Comment by thedrow** [comment]
pytest 2.8 doesn't support Python 2.6 which Travis still supports.

**Comment by kynan** [comment]
@BanzaiMan @khughitt: yes, that works for me too, thanks!

**Comment by BanzaiMan** [comment]
OK. I'm closing this.
