### ISSUE TITLE
R builds failing due to issues with digest

### ISSUE THREAD

**Issue by zkamvar** [travis-ci/travis-ci#5636]
Community: R
@craigcitro @hadley @jimhester

Hello again. 
Here's my latest failing build: https://travis-ci.org/grunwaldlab/poppr/builds/109479976
Here's my last successful build: https://travis-ci.org/grunwaldlab/poppr/builds/108632182

Travis is getting build errors because it [can't seem to find the digest package, necessary to build devtools](https://travis-ci.org/grunwaldlab/poppr/builds/109479976#L454-L456). This might be a CRAN issue, but I can't tell from this vantage point.

**Comment by jimhester** [comment]
You just need to delete your caches at
https://travis-ci.org/grunwaldlab/poppr/caches

This soils be a one time issue sure to the compiled R changing, which
invalidated the cache.
