### ISSUE TITLE
Travis says:  "Travis encountered an error, sorry :(". No other information available.

### ISSUE THREAD

**Issue by hkhurana** [travis-ci/travis-ci#5643]
API REQUEST:

PUT /hooks HTTP/1.1
Host: api.travis-ci.org
User-Agent: TravisPy
Accept: application/vnd.travis-ci.2+json
Authorization: token xxxxxx
Content-Type: application/json
Cache-Control: no-cache

{"hook": {"active": true, "id": 6906598}}

Getting the RESPONSE:

Connection → keep-alive
Content-Type → application/json
Date → Wed, 17 Feb 2016 07:42:55 GMT
Server → nginx
Status → 500 Internal Server Error
Transfer-Encoding → chunked
Via → 1.1 vegur

{
    "error": "Travis encountered an error, sorry :("
}

There is no other information. Please help in debugging this issue.

**Comment by aline-github-ro2** [comment]
I can provide more information if required. Here is the user info:

git hub username: aline-github-ro
Email: aline_github_ro@devfactory.com

**Comment by calebeby** [comment]
Is there any way to fix this?

**Comment by swissglider** [comment]
Any news ?

**Comment by calebeby** [comment]
This hasn't been fixed due to your lack of responsiveness, and that does not mean you can just close the issue. It still needs to be fixed.

**Comment by calebeby** [comment]
This hasn't been fixed due to your lack of responsiveness, and that does not mean you can just close the issue. It still needs to be fixed.

**Comment by BanzaiMan** [comment]
I'm closing this now, not because it is resolved, but because it lacks substantial information. If you are seeing this problem, do send email to support@travis-ci.com with detailed information about the endpoint and the payload you are making this API request on, and we will take a look.

Thanks.
