### ISSUE TITLE
Build Tools failure

### ISSUE THREAD

**Issue by MSF-Jarvis** [travis-ci/travis-ci#5648]
When compiling an Android app, this simply does not allow me to use the latest build tools version : 24.4.1 @corcoran let me know that it wasnt installing, so i would want to know which one actually gets installed so I can use it to build my app.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem?

**Comment by MSF-Jarvis** [comment]
I think I did. Let me grab it real quick

**Comment by MSF-Jarvis** [comment]
https://api.travis-ci.com/jobs/33136293/log.txt?deansi=true&access_token=Af3ddGu7PUPLtK5LXUmKjw

**Comment by BanzaiMan** [comment]
We have received similar reports. I am a bit confused about the failure, since in the logs indicated, I see:

```
Installing Archives:
  Preparing to install archives
  Downloading Android SDK Tools, revision 24.4.1
  Installing Android SDK Tools, revision 24.4.1
    Installed Android SDK Tools, revision 24.4.1
  Done. 1 package installed.
```

on lines 317 through 322.

Later on in the logs, I see platform-tools 23 as well as android-23 being installed. Are these perhaps overriding the previously installed android 24.4.1? Do you perhaps need to specify `android-24.4.1` instead of `android-23` in your components?

**Comment by MSF-Jarvis** [comment]
Committed and pushed. Will let you know if it helps

**Comment by MSF-Jarvis** [comment]
https://raw.githubusercontent.com/MSF-Jarvis/msf-jarvis.github.io/master/misc/travis-paste-20160218

Failed again

**Comment by ardock** [comment]
@MSF-Jarvis I think you are using a wrong [SDK Build Tools](http://developer.android.com/tools/revisions/build-tools.html) version ([SDK tools](http://developer.android.com/tools/sdk/tools-notes.html) are not the same tools).

[Latest Build Tools, Revision 23.0.3 (March 2016)](http://developer.android.com/tools/revisions/build-tools.html)

Replace in `.travis.yml `file:
```
android:
    components:
        - build-tools-24.4.1
```
by
```
android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.3
```
and use the same version in your `build.gradle` file:
```
android {
    ...
    buildToolsVersion "23.0.3"
    ...
}
```

@BanzaiMan [This is a different issue](https://github.com/travis-ci/travis-ci/issues/5036)

**Comment by MSF-Jarvis** [comment]
New error @ardock : 

** * What went wrong:
A problem occurred configuring project ':app'.
> failed to find target with hash string 'android-23' in: /usr/local/android-sdk **

**Comment by ardock** [comment]
Add `android-23` to components too, it's not preinstalled.

```
android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.3
        - android-23
```

**Comment by MSF-Jarvis** [comment]
@ardock : http://paste.omnirom.org/view/949827b1

**Comment by ardock** [comment]
The android support library is included in extra-android-m2repository. You need install it:

```
android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.3
        - android-23
        - extra-android-m2repository
        - extra-google-m2repository
```

It's better that you read [this](https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI) and [this](https://docs.travis-ci.com/user/languages/android) next time. You can also find good answers [here](http://stackoverflow.com/questions/tagged/android+travis-ci).

**Comment by MSF-Jarvis** [comment]
Thanks @ardock, I was getting the feeling I was irritating you.

**Comment by ardock** [comment]
You're welcome, it's ok, I like to help, I'm not irritated, only worried about watchers receiving emails.

I only say that stackoverflow is better for this type of questions, and these links can be useful for you.
