### ISSUE TITLE
/auth/github API endpoint requires User-Agent which begins with 'Travis'

### ISSUE THREAD

**Issue by kevinoid** [travis-ci/travis-ci#5649]
It appears that the [`/auth/github` API endpoint](https://docs.travis-ci.com/api#with-a-github-token) requires a `User-Agent` header which begins with `Travis`.  To demonstrate the issue, consider the following requests (with tokens X'd out).  First a request with a made-up `User-Agent`:

```
$ curl -i -H 'Content-Type: application/json' -d '{"github_token":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}' -H 'User-Agent: SuperExample/1.0' https://api.travis-ci.org/auth/github
HTTP/1.1 403 Forbidden
Connection: keep-alive
Server: nginx
Date: Wed, 17 Feb 2016 21:34:16 GMT
Content-Type: application/json
Content-Length: 92
Status: 403 Forbidden
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Type, Cache-Control, Expires, Etag, Last-Modified
Strict-Transport-Security: max-age=31536000
X-Endpoint: Travis::Api::App::Endpoint::Authorization
X-Pattern: /github
X-Oauth-Scopes: public
X-Accepted-Oauth-Scopes: public
Vary: Accept,Accept-Encoding
X-Rack-Cache: invalidate, pass
Via: 1.1 vegur

you are currently not allowed to perform this request. please contact support@travis-ci.com.
```

Next, the same request with a `User-Agent` starting with `Travis`:

```
$ curl -i -H 'Content-Type: application/json' -d '{"github_token":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}' -H 'User-Agent: Travis/1.0' https://api.travis-ci.org/auth/github
HTTP/1.1 200 OK
Connection: keep-alive
Server: nginx
Date: Wed, 17 Feb 2016 21:34:32 GMT
Content-Type: application/json
Content-Length: 41
Status: 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Type, Cache-Control, Expires, Etag, Last-Modified
Strict-Transport-Security: max-age=31536000
X-Endpoint: Travis::Api::App::Endpoint::Authorization
X-Pattern: /github
X-Oauth-Scopes: public
X-Accepted-Oauth-Scopes: public
Vary: Accept,Accept-Encoding
X-Rack-Cache: invalidate, pass
Via: 1.1 vegur

{"access_token":"XXXXXXXXXXXXXXXXXXXXXX"}
```

This behavior does not appear to be documented (or I overlooked it).  Is it expected?

Thanks,
Kevin

P.S.  Note that the 403 response also sends plain text with `Content-Type: application/json`, which is incorrect, although much easier to work around.

**Comment by xdg** [comment]
Wow.  Thank you for figuring that out.  That has been driving me nuts!  I hope they fix it soon.

**Comment by grosser** [comment]
:heart: great find!

... now someone just needs to fix it :D

**Comment by kevinoid** [comment]
Yes indeed.  Luckily it's not too bad to workaround for many cases, once you know what the problem is.  But, of course, knowing is half the battle.

I'm hoping the User-Agent detection isn't a security measure....

**Comment by grosser** [comment]
Yeah ... great security measure :D

**Comment by jakirkham** [comment]
So, we had been using a `User-Agent` like proposed here for some time. However, it seems that this is not working any more of late. Or at least if it works it is incredibly unreliable. Could someone please clarify how we are suppose to use the Travis CI API with a GitHub token? It is starting to seem like one can't. 😕

**Comment by jakirkham** [comment]
cc @pelson

**Comment by grosser** [comment]
check out https://github.com/grosser/travis_dedup ... works fine there ... maybe you got the headers wrong ...

**Comment by jakirkham** [comment]
So, this was working fine for us for the last 6 months. It has just bricked up in the past few days. Considering we haven't changed anything on our end, I'm a little concerned that something has changed with the Travis CI's API that isn't being made clear or at least I have totally missed it.

**Comment by wisechengyi** [comment]
Getting straight up 403. Anything else I can try?

```
[tw-mbp-yic pants (hack)]$ curl -i -H 'Content-Type: application/json' -d '{"github_token":"<github token>"}' -H 'User-Agent: Travis/1.0' https://api.travis-ci.org/auth/github
HTTP/1.1 403 Forbidden
Connection: keep-alive
Server: nginx
Date: Sat, 02 Jul 2016 08:22:09 GMT
Content-Type: text/plain
Content-Length: 10
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Type, Cache-Control, Expires, Etag, Last-Modified
Strict-Transport-Security: max-age=31536000
X-Oauth-Scopes: 
Vary: Accept-Encoding
X-Rack-Cache: pass
Via: 1.1 vegur

Forbidden
```

**Comment by jakirkham** [comment]
So, we were having lots of issues over the past couple days. However, have found one potential issue with our API usage, which this issue helped clarify. I would say make sure you have the following headers.

* Have some kind of `User-Agent`.
* Have `Accept: application/vnd.travis-ci.2+json`.
* Have `Content-Type: application/json`.

Still have been running into a lot of issues with Travis CI's API even with these, but they have improved the situation. It would be nice if someone could clarify how we are suppose to use the API (what headers are needed). Also, it would be nice if someone could state clearly whether the API is having availability issues. Finally, it would be nice if someone could clarify if there is rate limiting and if so what it is ( https://github.com/travis-ci/travis-ci/issues/6257 )?

**Comment by jakirkham** [comment]
Honestly, I'm still having issues with the API being flaky so added a new issue ( https://github.com/travis-ci/travis-ci/issues/6284 ). Feel free to follow along if you are struggling as I am.

**Comment by jasonmp85** [comment]
This is _insane_.

I can't believe I wasted time on this. _Your own documentation_ contains this text in the right sidebar next to "With a GitHub token"

```
POST /auth/github HTTP/1.1
User-Agent: MyClient/1.0.0
Accept: application/vnd.travis-ci.2+json
Host: api.travis-ci.org
Content-Type: application/json
Content-Length: 37

{"github_token":"YOUR GITHUB TOKEN"}
HTTP/1.1 200 OK
Content-Type: application/json

{"access_token":"YOUR TRAVIS ACCESS TOKEN"}
```

I was going to point out that this request doesn't work, because `MyClient` doesn't start with _Travis_; however, _the above works, too_.

Is there some sort of client whitelist, and if so, can you **please** post it? Or—better yet—remove the logic that's doing this?

**Comment by tqtran7** [comment]
Had the exact same issue. Thanks for sharing the finding. Drove me nuts as well.

**Comment by jasonmp85** [comment]
No, this needs to be fixed.
