### ISSUE TITLE
R: occasional failure to find devtools

### ISSUE THREAD

**Issue by nealrichardson** [travis-ci/travis-ci#5650]
I've seen builds erroring on Travis occasionally, and repeatedly today, when trying to install R dependencies because of a failure to find the devtools package:

```
$ Rscript -e 'deps <- devtools::install_deps(dependencies = TRUE);if (!all(deps %in% installed.packages())) { message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

I did a diff of the [log from a recent error](https://s3.amazonaws.com/archive.travis-ci.org/jobs/109932161/log.txt) compared to a [recent success](https://s3.amazonaws.com/archive.travis-ci.org/jobs/109703283/log.txt), and one difference is that the successful run has these lines in the logs, while the failure does not:

```
sudo mkdir -p /usr/local/lib/R/site-library $R_LIBS_USER
sudo chmod 2777 /usr/local/lib/R /usr/local/lib/R/site-library $R_LIBS_USER
...
export R_LIBS_SITE=/usr/local/lib/R/site-library:/usr/lib/R/site-library
```

My [.travis.yml](https://github.com/Crunch-io/rcrunch/blob/master/.travis.yml) is pretty vanilla and has not changed recently.

cc @craigcitro @hadley @jimhester

**Comment by jemus42** [comment]
I'm running into this problem, too (I was literally about to open an issue about it).  
My error looks like this:

```
Installing *binary* R packages: devtools
Installing apt packages: r-cran-devtools
0.43s$ sudo apt-get install -y r-cran-devtools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
r-cran-devtools is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 113 not upgraded.
Installing R packages from GitHub: sjPlot/sjmisc
0.10s$ Rscript -e 'devtools::install_github(c("sjPlot/sjmisc"), build_vignettes = FALSE)'
Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

Note how I tried to fix it by explicitly installing devtools as a binary package.  
The full log is [located here](https://travis-ci.org/tadaadata/tadaatoolbox/builds/110005130) with a lot of previous builds failing similarly. My `.travis.yml` is located [here](https://github.com/tadaadata/tadaatoolbox/blob/master/.travis.yml), and I tried a multitude of different things in the past day or to with no success.  

This issue evolved from the installation of `sjmisc` (CRAN version) failing due to an error with `nlme` (which occurred even though test builds locally and on the win-builder had no issues) which I [tweeted about previously](https://twitter.com/Jemus42/status/699777786446270465) but I assume these are separate issues.

**Comment by rCarto** [comment]
I have the same kind of message:
```
0.10s$ Rscript -e 'deps <- devtools::install_deps(dependencies = TRUE);if (!all(deps %in% installed.packages())) { message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
The command "Rscript -e 'deps <- devtools::install_deps(dependencies = TRUE);if (!all(deps %in% installed.packages())) { message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
```
full [log](https://travis-ci.org/Groupe-ElementR/cartography/builds/110080989)
and[ .travis.yml](https://github.com/Groupe-ElementR/cartography/blob/master/.travis.yml)

**Comment by pierucci** [comment]
Same here, this issue appeared today. Exactly the same message.

Full log [https://travis-ci.org/pierucci/heemod/builds/110088752](here).
[https://github.com/pierucci/heemod/blob/master/.travis.yml](.travis.yml)

**Comment by masalmon** [comment]
I hadn't seen the issue, sorry. Same issue here. https://github.com/travis-ci/travis-ci/issues/5652

**Comment by paul4forest** [comment]
Same issue, Travis build was successful 3 days ago and now returns an error complaining about missing devtools package :

```
 $ Rscript -e 'deps <- devtools::install_deps(dependencies = TRUE);if (!all(deps %in% installed.packages())) { message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'

Error in loadNamespace(name) : there is no package called ‘devtools’
```
Does devtools need to be installed explicitly in the .travis.yml ?

**Comment by jimhester** [comment]
Travis seems to have rolled back their deployed version which has broken R builds installing binary packages. 

Until it is fixed the best solution is to switch to using the container based builds. This is now the recommended practice for R builds anyway as utilizing the package cache can speed up build times once the package dependencies for your project are cached.

```yaml
sudo: false
cache: packages
```

See https://docs.travis-ci.com/user/languages/r for more information.

I apologize for the issues, I am not sure why this happened but I am looking into it.

**Comment by jimhester** [comment]
This issue was due to a bad merge in travis-build, which is now fixed. If you rebuild your projects they should now work without error.

**Comment by masalmon** [comment]
thanks, @jimhester ! it feels great to get green badges again :relieved:

**Comment by paul4forest** [comment]
Build passed.

**Comment by rCarto** [comment]
thks, it works for me too.

**Comment by BanzaiMan** [comment]
Sorry about the problems. I'm closing this issue now.

**Comment by DavidSichau** [comment]
I have this problem again, with the containerized buildings:

  
```
Checking package
Checking with: R CMD check eOSCEAnalyserShiny_0.0.1.tar.gz --as-cran
1.18s$ R CMD check "${PKG_TARBALL}" --as-cran; CHECK_RET=$?
* using log directory ‘/home/travis/build/iml-it/eosce-analyzer-shiny/eOSCEAnalyserShiny.Rcheck’
* using R version 3.3.1 (2016-06-21)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using option ‘--as-cran’
* checking for file ‘eOSCEAnalyserShiny/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘eOSCEAnalyserShiny’ version ‘0.0.1’
* checking package namespace information ... OK
* checking package dependencies ... ERROR
Packages required but not available:
  ‘reshape2’ ‘plyr’ ‘digest’ ‘ggplot2’ ‘scales’ ‘TAM’ ‘cacIRT’ ‘shiny’
  ‘sirt’ ‘WrightMap’ ‘data.table’ ‘dplyr’ ‘shinydashboard’ ‘DT’ ‘httr’
  ‘shinyjs’ ‘RCurl’ ‘readr’ ‘V8’
Packages suggested but not available:
  ‘devtools’ ‘testthat’ ‘lintr’ ‘covr’ ‘RSelenium’ ‘roxygen2’
The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.
See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
* DONE
Status: 1 ERROR
See
  ‘/home/travis/build/iml-it/eosce-analyzer-shiny/eOSCEAnalyserShiny.Rcheck/00check.log’
for details.
0.07sError in loadNamespace(name) : there is no package called ‘devtools’
Calls: cat ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

And here my travis.yml

```
language: r
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libv8-dev
      - libssl-dev 
      - libsasl2-dev
install:
  -  Rscript -e 'Sys.setlocale(locale="C")'
notifications:
  email:
    on_success: change
    on_failure: change
```

On my local machine the command `R CMD check eOSCEAnalyserShiny_0.0.1.tar.gz --as-cran` produces no error.

**Comment by jimhester** [comment]
@DavidSichau You are overriding the `install:` step, which is when packages are installed. In addition setting the locale is only going to affect that R session, so it will have no effect. `R CMD check` already runs its tests in the C locale, why are you trying to set it explicitly?

**Comment by DavidSichau** [comment]
@jimhester Thanks for the fast response. I have no idea why we had this install part inside the script. I removed it and now everything works.

**Comment by ms609** [comment]
I'm encountered an equivalent problem over the last week or two with two different packages -- one of which stopped working after a commit that cannot possibly have affected the Travis build. 

I'm seeing the [error message](https://travis-ci.org/ms609/TreeSearch/jobs/344744833)

```
Rscript -e 'install.packages(c("devtools", "ape", "covr", "memoise", "phangorn", "R.cache", "Rdpack", "roxygen2", "testthat"));if (!all(c("devtools", "ape", "covr", "memoise", "phangorn", "R.cache", "Rdpack", "roxygen2", "testthat") %in% installed.packages())) { q(status = 1, save = "no")}'
Error in library("devtools") : there is no package called ‘devtools’
Execution halted
```

My .travis.yml reads

```
language: r
r:
 - 3.4.0
 - devel
cache: packages
sudo: false
warnings_are_errors: true
r_check_args: --as-cran
   
git:
  depth: 5
  
r_packages:
 - devtools
 - ape
 - covr
 - memoise
 - phangorn
 - R.cache
 - Rdpack
 - roxygen2
 - testthat

before_script:
 - R -e "devtools::document()"
  
after_success:
  - Rscript -e "covr::codecov()"
  ```
I managed to fix the problem in [a different package](https://github.com/TGuillerme/Inapp/blob/master/.travis.yml) by using `r_binary_packages` in place of `r_packages`, but because I wish to test this package on r 3.4.0, and the devtools binary requires a more recent version of R, this workaround is not available to me here.
