### ISSUE TITLE
Legacy infrastructure has become very slow

### ISSUE THREAD

**Issue by smiller171** [travis-ci/travis-ci#5655]
I am unable to use the new infrastructure because you don't yet support Docker in Docker (shouldn't be at all difficult)

Unfortunately it now takes several minutes longer than it used to for the build to start on the legacy infrastructure.

**Comment by BanzaiMan** [comment]
The new infrastructure is quite popular now, and we have a capacity limit at the moment. As a result, during the US work day (typically) there is a delay before builds start. We are looking to eradicate this problem, but the resolution would take time.

**Comment by smiller171** [comment]
@BanzaiMan I would love to move to the new container-based infrastructure, but I can't until you support docker-in-Docker because I need to build Docker containers in almost all of my projects. Supporting Docker-in-Docker would require only a minor change to your base image and launching the containers with the `--privileged` flag

**Comment by smiller171** [comment]
In the meantime, is there a flag I can set to move off the GCE builders?

**Comment by matthewmorley** [comment]
Is there an update on this? We've also very recently seen our test times explode as a result of the GCE transition. Is there an option to change the default routing to put us not on GCE until this is resolved?

**Comment by BanzaiMan** [comment]
`sudo: required` does it.

We are decommissioning the legacy infrastructure very shortly.

I'm closing this now.
