### ISSUE TITLE
When `bundler_args: --system` and `cache: bundler` are given, travis CI also tries to use --path for bundler argument.

### ISSUE THREAD

**Issue by jcampbell05** [travis-ci/travis-ci#5656]
Given `bundler_args: --system`

`--path` is still attempted to be use.

**Comment by BanzaiMan** [comment]
The circumstances under with `--path` is added to the default `bundle install` invocation is limited. In particular, this happens exactly when `cache: bundler` is indicated and `bundler_args` does not contain `--path`.

When `cache: bundler` is indicated, we should ensure that the gems are found in the place where we cache them. Adding `--system` would violate that expectation.

I am not sure this behavior is worth documenting, but given the conditions given by `.travis.yml` is inherently contradictory.

I'm closing this now, but if you have further questions, do ask.
