### ISSUE TITLE
R: Package installation ERRORs but travis reports success

### ISSUE THREAD

**Issue by jemus42** [travis-ci/travis-ci#5658]
Log excerpt:

```
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘tadaatoolbox’ can be installed ... ERROR
Installation failed.
See ‘/home/travis/build/tadaadata/tadaatoolbox/tadaatoolbox.Rcheck/00install.out’ for details.
* DONE
Status: 1 ERROR
See
  ‘/home/travis/build/tadaadata/tadaatoolbox/tadaatoolbox.Rcheck/00check.log’
for details.
0.15schecking whether package ‘tadaatoolbox’ can be installed ... ERROR
Installation failed.
See ‘/home/travis/build/tadaadata/tadaatoolbox/tadaatoolbox.Rcheck/00install.out’ for details. DONE
Status: 1 ERROR 
0.00s
The command "grep -q -R "WARNING" "${RCHECK_DIR}/00check.log"" exited with 0.
cache.2
store build cache
0.00s
14.62schanges detected, packing new archive
.
.
uploading archive`
Done. Your build exited with 0.
```

Log is [here](https://travis-ci.org/tadaadata/tadaatoolbox/builds/110209108), and travis.yaml is [here](https://github.com/tadaadata/tadaatoolbox/blob/master/.travis.yml).

I have no idea what's going on there, I just migrated to the container version after the devtools issue from yesterday.

**Comment by BanzaiMan** [comment]
I think we deployed a fix for this error. Could you rerun it?

**Comment by jemus42** [comment]
Well, now it [fails and tells me about it properly](https://travis-ci.org/tadaadata/tadaatoolbox/builds/110209108) – However, it doesn't tell my anything about the ERROR, and since that exact package version was just accepted to CRAN I am very suspicious about the legitimacy of that error. Any ideas?

**Comment by BanzaiMan** [comment]
@jemus42 I think that new issue is now also reported in #5668. Since the original issue is resolved, I'm going to close this one. Please follow #5668 for the availability issue.
