### ISSUE TITLE
Plans to upgrade CI to Ubuntu Vivid

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#5659]
Currently the latest Ubuntu on Travis is Trusty (you can set-up this with: `dist: trusty`), however some packages consist some bugs, because of usage of old libraries (such as [gnutls26](https://bugs.launchpad.net/ubuntu/+source/gnutls26/+bug/1444656)) which fails some builds, because of SSL handshake bug.

Here is example [build which fails](https://travis-ci.org/EA31337/FX-MT-VM/jobs/103991713) on installation of software via Wine which uses the old gnutls. The same build was working before the refresh for some reason, but after upgrade of the installer it failed to work. This could potentially work in Ubuntu Vivid since [build-depend on libgnutls28 which restores SSL support](https://launchpad.net/ubuntu/+source/wine-development/1.7.29-2).

**Comment by erg** [comment]
:+1: 

I just started using travis-ci today and it's crazy how outdated things are when you base it on Trusty LTS. For instance, my project only has a handful of dependencies, one being GCC 4.8+ (preferably GCC 5.3) for the ``-std=gnu++11``, but Trusty ships with ``g++ (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3``. Additionally, the ``libyajl`` version is 2.0.2 instead of 2.1, and there are api changes which break my build.

I've wasted several hours today trying to find workarounds for all the outdated versions of things because the travis-ci Ubuntu is too old. How about you take the opposite approach and base the image on Ubuntu 16.04 Xenial and help get it ready for release instead of hammering on old broken Ubuntu LTS versions from almost two years ago?

Thanks for listening.

**Comment by solarce** [comment]
While we can understand the need for some folks to have the newest stuff, building and maintaining our image library, while also ensuring it's usable for the 250,000+ jobs we run each day is a unique challenge.

Given that, we are currently focused on support 12.04 and 14.04 as our primary environments. At the moment, it is unlikely that we'll be supporting 16.04 as a native environment this year.

If you're particular use cases require something newer, I would encourage you to use utilize our [Docker in a build support](https://docs.travis-ci.com/user/docker/#Using-a-Docker-Image-from-a-Repository-in-a-Build), which would allow you run your build inside a Docker image of a newer Ubuntu release. While the start up times are slower than our countainer-based builds, you get a full VM with 7.5GB of RAM, for each build.

Regards,
Brandon Burton
Infrastructure Manager

**Comment by Croydon** [comment]
No support for 16.04 in the entire year is somewhat disappointing to be honest.
Can we count on it at least for 2017?

**Comment by solarce** [comment]
@Croydon I can understand where you're coming from, but adding support for new distribution releases is a significant amount of engineering work on our part. At this moment, other things take a priority.

You can use our [Docker support](http://docs.travis-ci.com/user/docker/) to pull down a 16.04 container and run your build inside it.

I can't comment on timeline for 16.04 support as a supported build environment at this time.

**Comment by jonathanmaron** [comment]
I have come across an almost identical issue with TLS 1.2 support (in PHP/curl). See: http://stackoverflow.com/questions/38375211/curl-error-35-gnutls-handshake-failed/38429611

**Comment by abelboldu** [comment]
For our project, relying on docker images is just not possible, as we had many issues with systemd.

Any ETA for Ubuntu 16.X support?

**Comment by solarce** [comment]
At the moment we plan to start looking into supporting Xenial in late Q2 of
this year. I won't have any more details on the topic until that time frame.

Regards,

-- 

Brandon Burton

Build Infrastructure Engineering Manager

brandon@travis-ci.com


Travis CI   Test and Deploy with Confidence.

www.travis-ci.com


Travis CI GmbH, Rigaer Str.8, 10247 Berlin, Germany
<x-apple-data-detectors://17/1> | GF/CEO: Mathias Meyer, Joshua
Kalderimis | Contact: contact@travis-ci.org

Amtsgericht Charlottenburg, Berlin, HRB 140133 B | Umsatzsteuer-ID
gemäß §27 a Umsatzsteuergesetz: DE282002648

**Comment by strugee** [comment]
@solarce do you have an update on this, since it's early Q3? I know you guys are busy so no worries either way <3

**Comment by solarce** [comment]
Wheels are starting to turn. Adding some level of support for Xenial should start happening as https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming moves along and if it goes as smoothly as we expect.

**Comment by maarky** [comment]
If you're using Ubuntu it doesn't make sense not to support every LTS release as soon as it is released or at least as soon as possible. It's been available for nearly 16 months. I use 16.04 for dev, testing and production so If you don't support it then I can't see the point in using your service.
