### ISSUE TITLE
Apt addon request:  Allow debconf-set-selection 

### ISSUE THREAD

**Issue by dan-blanchard** [travis-ci/travis-ci#5663]
I run a few projects that need to install a local copy of the Grid Engine package to do integration testing.  In order to install it, I use [this script](https://github.com/pygridtools/gridmap/blob/724881759745435640d56442f4c1ecefe7e57efa/travis/install_sge.sh) I came up with.  There's a lot of `sudo` usage in it, but I think most of it could be gotten rid of if there was a way to use `debconf-set-selection` via the apt addon.  We also could use a way to create/users groups without `sudo`.

**Comment by BanzaiMan** [comment]
`apt` addon is designed to be a simple way to install APT packages on containers. It is not intended to be a full replacement for various `apt-get` invocations.

If your use case goes beyond its current scope, I suggest using `sudo: required`.

Thanks.
