### ISSUE TITLE
Coloured output in log is fine, but I use `travis_wait` now is without color

### ISSUE THREAD

**Issue by moylop260** [travis-ci/travis-ci#5665]
Is normal that if I see my log with colors and later of add `travis_wait` I lost the colors?

**Comment by BanzaiMan** [comment]
What command are you sending to `travis_wait`, and does the command produce ANSI colored output by itself?

**Comment by moylop260** [comment]
This is the example without color:
https://travis-ci.org/OCA/l10n-spain/jobs/110457183#L287

I had that add `unbuffer` command to get colors with `travis_wait`

But before of use `travis_wait` I had colors without `unbuffer`

**Comment by BanzaiMan** [comment]
Here's a test: https://travis-ci.org/BanzaiMan/travis_production_test/builds/110634827#L159

I don't know what your script is doing differently, but if you just embed ANSI escape sequences directly into the script's output (https://github.com/BanzaiMan/travis_production_test/blob/47cc3ea928eaead0475ae8bf7f640589a65a14b0/ansi_script) they will show up correctly in the logs.

**Comment by moylop260** [comment]
@BanzaiMan 
Thanks for try.

I will try to reproduce it with a small script.

I can reproduce it here, but is with many other scripts:
[Without color with travis_wait](https://travis-ci.org/Vauxoo/runbot_branch_remote_name_grp_feature2/jobs/110692774#L1251)
[Color without travis_wait](https://travis-ci.org/Vauxoo/runbot_branch_remote_name_grp_feature2/jobs/110692774#L457)

**Comment by BanzaiMan** [comment]
https://travis-ci.org/Vauxoo/runbot_branch_remote_name_grp_feature2/jobs/110692774#L1399 shows some ANSI-encoded color outputs from `travis_wait`.

**Comment by moylop260** [comment]
Yes
The section with unbuffer

**Comment by moylop260** [comment]
I had that create follow PR to add color in all logs of `travis_wait`:
https://github.com/OCA/maintainer-quality-tools/pull/318/files

But I can't to isolate this isssue in a small script...

The case of test is:

| script | color  |
|---|---|
| script.py  |   yes |  
| unbuffer script.py  |   yes |  
| travis_wait script.py  |   no |  
| travis_wait unbuffer script.py  |  yes | 

I will try again to reproduce it
Thanks for reply

**Comment by moylop260** [comment]
I can reproduce it with a file with the python script.
[logging_test.py](https://github.com/moylop260/travis-test/blob/output-color-test/logging_test.py)

The build was: https://travis-ci.org/moylop260/travis-test/builds/110710927

The test case:

| script | color  | lines |
|---|---|---|
| script.py  |   yes | [#L159-L160](https://travis-ci.org/moylop260/travis-test/builds/110710927#L159-L160)  |
| travis_wait script.py  |   no | [#L172-L173](https://travis-ci.org/moylop260/travis-test/builds/110710927#L172-L173)   |
| unbuffer script.py  |   yes |  [#L186-L187](https://travis-ci.org/moylop260/travis-test/builds/110710927#L186-L187)  |
| travis_wait unbuffer script.py  |  yes | [#L193-L194](https://travis-ci.org/moylop260/travis-test/builds/110710927#L193-L194)  |

**Comment by BanzaiMan** [comment]
Is there anything to do on our side?

**Comment by moylop260** [comment]
Using `unbuffer` work fine.
Thank you.
