### ISSUE TITLE
Stuck on "Syncing from Github"

### ISSUE THREAD

**Issue by tregoning** [travis-ci/travis-ci#5667]
Hi,

travis-ci.com (not .org) is stuck in "Syncing from Github" for my account.

After looking at some previous github issues it looks like the procesure is to report it here for you to manually fix it.

Thanks!

JT

**Comment by BanzaiMan** [comment]
Hello there. Sorry for the issue. I've manually sync'd your user data. You should be good to go now. Let us know if you continue to have problems.

Happy building!

**Comment by tregoning** [comment]
Thanks!

**Comment by UtkarshVerma** [comment]
@BanzaiMan I also have the same issue.
