### ISSUE TITLE
Odd behavior when installing gcc-multilib on trusty

### ISSUE THREAD

**Issue by LRFLEW** [travis-ci/travis-ci#5670]
Ok, I've run into an odd issue with the .org build of my project when building for i386, and now that I've narrowed down how to reproduce it, I'll post the details here.

Let's consider a simplified case for the install step. First, I start with this setup:

```
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
```

Now, both of of the following install scripts work as expected:

```
install:
  - sudo apt-get install -y gcc-multilib
  - sudo apt-get install -y zlib1g-dev:i386
```

```
install:
  - sudo apt-get install -y zlib1g-dev:i386
  - sudo apt-get install -y gcc-multilib
```

However, if I use the following install script:

```
install:
  - sudo apt-get install -y gcc-multilib zlib1g-dev:i386
```

I get a strange error:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 gcc-multilib : Depends: cpp (>= 4:4.8.2-1ubuntu6) but it is not going to be installed
                Depends: gcc (>= 4:4.8.2-1ubuntu6) but it is not going to be installed
                Depends: gcc-4.8-multilib (>= 4.8.2-5~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I'm not certain of all the exact conditions needed for producing this result, but I can at least show that this is enough to cause the error on the Trusty builds.

**Comment by LRFLEW** [comment]
Ok, I did some more testing, and I think I understand what's going on. When you run `sudo apt-get install -y zlib1g-dev:i386`, it prints out:
```
The following packages will be REMOVED:
  build-essential g++ g++-multilib gcc gcc-multilib
```

So it is actually uninstalling gcc when you install any i386 library. I'm fairly certain this is not expected behavior, though, so I'll leave the issue open for now.

**Comment by akien-mga** [comment]
I'm having the same issue trying to install gcc-multilib on trusty. I guess the the gcc version provided in the default VM is older than the one apt-get wants to install from the repos, hence a conflict? Updating all packages of the VM might solve it, but would probably take quite some time, as the images date from 2015-09-08.

**Comment by akien-mga** [comment]
I confirm that updating gcc before attempting to install gcc-multilib does the trick. But it's quite bothersome as sometimes the download rate is very low, so it can take up to 25 minutes to just update gcc and its dependencies; and since my builds are quite long, I then easily reach the timeout value.

**Comment by akien-mga** [comment]
I'm still getting the same issue currently: https://travis-ci.org/GodotBuilder/godot-builds/jobs/349720329
```
sudo dpkg --add-architecture i386;
sudo apt-get update -qq;
sudo apt-get install -y gcc-multilib g++-multilib pkg-config:i386 libx11-dev:i386 libxcursor-dev:i386 libxrandr-dev:i386 libglib2.0-dev:i386 libasound2-dev:i386 libpulse-dev:i386 libpng-dev:i386 libfreetype6-dev:i386 libgl1-mesa-dev:i386 libglu1-mesa-dev:i386 libxi-dev:i386 libxinerama-dev:i386;
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libpng12-dev:i386' instead of 'libpng-dev:i386'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 g++-multilib : Depends: cpp (>= 4:4.8.2-1ubuntu6) but it is not going to be installed
                Depends: g++ (>= 4:4.8.2-1ubuntu6) but it is not going to be installed
                Depends: g++-4.8-multilib (>= 4.8.2-5~) but it is not going to be installed
 gcc-multilib : Depends: cpp (>= 4:4.8.2-1ubuntu6) but it is not going to be installed
                Depends: gcc (>= 4:4.8.2-1ubuntu6) but it is not going to be installed
                Depends: gcc-4.8-multilib (>= 4.8.2-5~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

It worked fine a couple weeks ago: https://travis-ci.org/GodotBuilder/godot-builds/jobs/343053714
