### ISSUE TITLE
Unexpected build error

### ISSUE THREAD

**Issue by MartinChavez** [travis-ci/travis-ci#5671]
[This](https://travis-ci.org/MartinChavez/CSharp/builds/110879172) is the build error.

Everything looks normal on my end (solution file is specified and it compiles locally).

Let mer know if I can provide more information.

**Comment by BanzaiMan** [comment]
> Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry
mono-install

**Comment by MartinChavez** [comment]
@joshua-anderson @akoeplinger @nterry

**Comment by Joshua-Anderson** [comment]
I think the important line is:

```
/usr/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.6' not supported by this toolset (ToolsVersion: 12.0)
```

This makes me think that xbuild doesn't support .net  4.6 yet.
Is this true @akoeplinger?

**Comment by akoeplinger** [comment]
Yes, Mono 4.2 doesn't support .net 4.6. It will be in the upcoming release, Mono 4.4.

**Comment by BanzaiMan** [comment]
Ibdont think there is much to do for us.
