### ISSUE TITLE
Syncing from GitHub hangs

### ISSUE THREAD

**Issue by prwater** [travis-ci/travis-ci#5672]
Hello,

After transforming my GitHub account into an organization (https://github.com/orgs/SetBased/) my personal account (https://travis-ci.org/profile/prwater) hangs for more than a day on "Syncing from GitHub". Also, my Organizations are not shown.

Revoking and granting access from/to our repositories did not solve this issue.

With best regards,
Paul

**Comment by hubuk** [comment]
Hi, I have the same problem. My account https://travis-ci.org/profile/hubuk hangs on syncing.
As I see this is a common problem so not to increase issues count I am posting here.

**Comment by rhusar** [comment]
+1 same problem here, I tried revoking permissions and re-authorizing, still hangs.

**Comment by fpaxton** [comment]
I'm having the same issue as well. Looking forward to using the service!

**Comment by prwater** [comment]
Syncing from GitHub works for my account now. I see all my organizations and repositories.

**Comment by hubuk** [comment]
Thanks for the update. I was hoping my too, but it is still syncing.

**Comment by BanzaiMan** [comment]
Thanks for the report. We are prioritizing this to provide you with better UX. In the meantime, is anyone still having this issue?

**Comment by rhusar** [comment]
All good on my account now, it was synced in the morning. So it was hung for couple of hours total (half day or something).

**Comment by hubuk** [comment]
Still syncing on my side.

**Comment by fpaxton** [comment]
Yes, I'm still stuck with "Syncing from Github". I initially had my email set to private so after changing that I revoked and re-authorized but still a no go.

**Comment by BanzaiMan** [comment]
@hubuk @fpaxton I've sync'd your data. Again, sorry for the issue.

**Comment by fpaxton** [comment]
@BanzaiMan Awesome, thanks for the help.

**Comment by hubuk** [comment]
@BanzaiMan Really appreciate your help. Thanks!

**Comment by prwater** [comment]
@BanzaiMan Thanks for the support on this issue. 

All users who commented on this issue can sync from GitHub now I close this issue.

**Comment by BanzaiMan** [comment]
I'm going to reopen this while we pursue a solution to a better fix. (So that other users may find it easier.)

**Comment by craigspara** [comment]
Hi. I too am having the same stuck "syncing from GitHub" issue and have tried many of the same strategies mentioned above to resolve it. Is there a way I can get my account sync'd manually?

**Comment by craigspara** [comment]
After about 6 hours, the sync from GitHub did finish. Thanks to anyone who may have assisted.

**Comment by Garethderioth** [comment]
I'm having the same issue.

**Comment by nzqpeace** [comment]
I'm having the same issue as well, it was hung for two days...

**Comment by boyandim** [comment]
Unfortunately I am experiencing same problem with my travis account. It hangs on "syncing from GitHub" forever. My travis account is boyandim.

**Comment by ethanrubio** [comment]
I'm having the same issue with travis-ci.org where "Syncing form Github" is hanging. I tried revoking and readding the permissions and it looks like the token stays the same. Further, my account works on travis-ci.com, but I need access for my public repos.

I noticed that some of the issues were fixed with a manual sync. Can that be done on my account?

Cheers!

**Comment by abalijepalli** [comment]
@BanzaiMan I'm having a similar issue with my travis-ci.org account. Sync with Github has been stuck for the better part of the day and I can't see my organizations.

**Comment by BanzaiMan** [comment]
@abalijepalli Sorry for the issue. Looks like yours have been sync'd already after a daily sync run has kicked in.

**Comment by geeteshk** [comment]
I do not mean to bump an old issue but @BanzaiMan I am having the exact same problem. Is there any other solution than wait?

**Comment by ethirajsrinivasan** [comment]
@BanzaiMan  i have changed my repository name from collection2csv to ActiveRecord-collection2csv and back to collection2csv.Build is not syncing up .It is passing in travis but in github it is not reflected.

**Comment by sudsred** [comment]
Hi, I apologize for bumping this issue, I am having the same problem. It's stuck on syncing for quite a while now.

**Comment by dumconstantin** [comment]
Same here. Any progress on solving this? We're in the middle of an event for supporting oss and wanted to have all the projects on Travis... any way to go around this?

**Comment by ajhsu** [comment]
Stuck in same issue right now... nothing i can do but wait

**Comment by chrisslater** [comment]
+1 this issue

**Comment by kimoonkim** [comment]
+1. I'm also stuck right now.

**Comment by joeyfreund** [comment]
+1 
Syncing an organization (on travis-ci.com) has been stuck for about 40 minutes already.

I am assuming it is related to an earlier GitHub service outage.

**Comment by Hesham-Elrehaimy** [comment]
I have the same issue. It's been syncing for 20 minutes now.

**Comment by Yangqing** [comment]
Same issue here, syncing for more than an hour.

**Comment by gsdevme** [comment]
Hanging for me also still....

**Comment by Qix-** [comment]
I love Travis but I feel like this has been an issue for ages. Is there some reason why there has always been a hangup? For years the sync button has been broken or hardly working.

**Comment by robfrawley** [comment]
@BanzaiMan Any change you can force-sync my account, as well? The sync is hung up for me, and even worse, once it gets hung up via the browser, I cannot even force a sync on the CLI by issuing `travis enable` using the Travis Ruby CLI interface...

**Comment by MJGwater** [comment]
I was just having this issue, but all I needed to do to make it work was refresh the page. So that's worth trying.

**Comment by ptpaterson** [comment]
It was also hanging for me, so I refreshed and then was notified with "Great News!", everything had been sync'd

**Comment by frostyfrog** [comment]
I just wanted to mention here that, when I went to my account today (first time in years), it appeared to already be syncing. Poking around on the web, I found that https://api.travis-ci.org/users/ displays if it's really syncing and when a sync started(?) I don't recall hitting the sync button before it said `Syncing from Github`.

The sync started at `"synced_at": "2017-09-18T06:29:57Z"` and assuming that it's still syncing from that time, and utcnow.com is correct, then that's roughly 30 minutes shy of 12 hours. I didn't think a sync of my account should've taken that long. Though maybe I'm not understanding how it all works. Eheh.

**Comment by aaronmallen** [comment]
any work around for this my account has been stuck in "syncing" for a few weeks...

**Comment by rcjsuen** [comment]
I'm getting hit by this also. The syncing animation just loops and loops and loops and loops. Kind of like the Energizer bunny if you will.

**Comment by darki73** [comment]
Same for me, been trying to google 'issue name' + last year, and found this one, animation just loops, nothing happens. Any help with that?

**Comment by Qix-** [comment]
Heh. Almost two years now.

**Comment by horacehylee** [comment]
+1 It also hangs for me

**Comment by UtkarshVerma** [comment]
Hanging for me too

**Comment by ntso-k** [comment]
+1 Mine is hanging too

**Comment by Verkurkie** [comment]
+1 Same here

**Comment by OscarWang114** [comment]
I encountered the same problem and investigated a bit.
According to the current [status](https://www.traviscistatus.com/), the engineering team is working hard to get everything set up again. All the best wishes!

**Comment by osidorkin** [comment]
Same issue using travis against enterprise github

**Comment by kmizu** [comment]
+1 me too

**Comment by KLlorente** [comment]
Not sure if this is still active, but mine has been hanging for almost 30 minutes now.

**Comment by mrustl** [comment]
mine too....

**Comment by ianharrigan** [comment]
Ive been having this exact same issue:

![image](https://user-images.githubusercontent.com/3024242/63504575-21c14000-c4d2-11e9-8c9b-6f44060c12f4.png)

**Comment by jdreyf** [comment]
Mine has been running for 3 days: https://travis-ci.org/profile/jdreyf.
