### ISSUE TITLE
R: Stuck on "Do you want to continue? [Y/n] "

### ISSUE THREAD

**Issue by mstellwa** [travis-ci/travis-ci#5674]
During a build the script stops on a Do you want to continue question.

End of my log:
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
debhelper is already the newest version.
debhelper set to manually installed.
lsb-base is already the newest version.
The following extra packages will be installed:
  debugedit libdpkg-perl liblua5.2-0 librpm3 librpmbuild3 librpmio3
  librpmsign1 rpm-common rpm2cpio
Suggested packages:
  lsb-rpm lintian rpm-i18n debian-keyring elfutils reportbug apt-move
  dpkg-repack apt-file deborphan vrms apt-show-versions dctrl-tools debsums
  netselect-apt debtags
The following NEW packages will be installed:
  alien debugedit liblua5.2-0 librpm3 librpmbuild3 librpmio3 librpmsign1 rpm
  rpm-common rpm2cpio wajig
The following packages will be upgraded:
  dpkg-dev libdpkg-perl
2 upgraded, 11 newly installed, 0 to remove and 214 not upgraded.
Need to get 1,521 kB of archives.
After this operation, 2,639 kB of additional disk space will be used.
Do you want to continue? [Y/n] 

My .travsi.yml:
language: R
cache: packages
warnings_are_errors: true
sudo: required

install:
- env
- if [ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] ; then ./shared/dev-tasks/travis-install-ml.sh
  release ; else (exit 0) ; fi
- if [ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] ; then ./shared/dev-tasks/setup-marklogic.sh
  ; else (exit 0) ; fi

Any suggestions @craigcitro, @hadley and @jimhester?

**Comment by jimhester** [comment]
You need to add `-y` to your `apt-get` calls in your custom install script (i.e. https://github.com/mstellwa/rfml/blob/master/shared/dev-tasks/travis-install-ml.sh#L36).

**Comment by mstellwa** [comment]
Yes, of course.

Thanks!


.
