### ISSUE TITLE
R Package Installation Error: Could not find package root

### ISSUE THREAD

**Issue by IsmailM** [travis-ci/travis-ci#5675]
I’m getting the following error when attempting to install ggplot2 as a R package:

```
Rscript -e 'deps <- devtools::install_deps(dependencies = TRUE);if (!all(deps %in% installed.packages())) { message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
Error: Could not find package root.
Execution halted

The command "Rscript -e 'deps <- devtools::install_deps(dependencies = TRUE);if (!all(deps %in% installed.packages())) { message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
```

This is my Travis.ml

```
language: r
warnings_are_errors: false
sudo: required
script: 
  - bash test.sh
r_packages:
  - ggplot2
```

[Raw Log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/110925604/log.txt) | [Travis Page](https://travis-ci.org/IsmailM/R-Core/builds/110925603) | [Github Page](https://github.com/IsmailM/R-Core)

Any Ideas?

@craigcitro, @hadley, @jimhester

**Comment by jimhester** [comment]
R travis expects to be run on a package repository as defined in [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html).

If your repository is using another convention you will have to provide your own `install:` and `script:` steps to install dependencies and run your checks. The following should work (untested).
```yaml
language: r
warnings_are_errors: false
sudo: required
install:
  - install.packages("ggplot2")
script: 
  - bash test.sh
```

**Comment by IsmailM** [comment]
Thanks
