### ISSUE TITLE
Question: Deploying/Running npm publish with multiple npm packages in a single repo

### ISSUE THREAD

**Issue by hzoo** [travis-ci/travis-ci#5676]
This definitely a not a use case most people have (a [monorepo](https://github.com/babel/babel/blob/master/doc/design/monorepo.md)), so I wanted to ask if anyone had suggestions about it.

In my example [repo](https://github.com/hzoo/hzoo-npm-publish), I have multiple npm packages in the `packages/` folder. I want to be able to run a script after a successful merge/commit to the master branch (the script will basically run `npm publish` (something like [this](https://github.com/kittens/lerna/blob/91a22ecb5bca5fd605209960621173840ea30677/lib/commands/publish/npmUpdateAsLatest.js#L21-L22)).

I was reading through https://docs.travis-ci.com/user/deployment/npm, and added it in https://github.com/hzoo/hzoo-npm-publish/blob/master/.travis.yml#L11-L21. However I want to be able to run `npm publish` on my own (on each package, rather than in the top level repo).

Currently I get the error [here](https://api.travis-ci.org/jobs/110878875/log.txt?deansi=true) - that `npm ERR! need auth You need to authorize this machine using npm adduser` since it's not using the npm publish process travis has already setup and since you can't use that prompt in travis.

Just wanted to know if Travis is able to support this use case (this would be used to deploy a canary build of [Babel](https://github.com/babel/babel)).

**Comment by userpixel** [comment]
@hzoo I have the same question.. did you manage to find a solution?

**Comment by hzoo** [comment]
@userpixel not yet still publishing Babel from local atm

**Comment by MartynasZilinskas** [comment]
We are struggling too with publishing.

**Comment by embbnux** [comment]
Does travis support `monorepo` publishing now?

**Comment by MartynasZilinskas** [comment]
This feature is still needed!

**Comment by MartynasZilinskas** [comment]
@embbnux Thanks for the example.
