### ISSUE TITLE
JDK8 problem with Android project

### ISSUE THREAD

**Issue by AlokBansal8** [travis-ci/travis-ci#5677]
I am using retrolambda library in my Android project. But the build fails every time with following message:

> Execution failed for task ':app:compileInternalDebugJavaWithJavac'.
> When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

**Comment by BanzaiMan** [comment]
Did you do either of those things? We only set `JAVA_HOME`, so anything extra is up to you.

**Comment by AlokBansal8** [comment]
solved in evant/gradle-retrolambda/#172
