### ISSUE TITLE
Builds are not restarting

### ISSUE THREAD

**Issue by jcoyne** [travis-ci/travis-ci#5678]
When I click the restart build button  The message "The build was successfully restarted." is displayed, however it continues to display the old log and it doesn't seem to restart.  See https://travis-ci.org/projecthydra-labs/curation_concerns/builds/111069146

**Comment by BanzaiMan** [comment]
Most likely an issue with message bus, which was subsequently resolved.

**Comment by jcoyne** [comment]
Excellent. Thank you.

**Comment by jcoyne** [comment]
It looks like it finally did restart
