### ISSUE TITLE
BOM in .travis.yml: travis/ruby can't handle that

### ISSUE THREAD

**Issue by denizzzka** [travis-ci/travis-ci#5681]
@MartinNowak, @klickverbot and @ibuclaw

Travis-CI only starts dub test, regardless of .travis.yml

Look here, for example:
https://travis-ci.org/denizzzka/vibe.d.db.postgresql
https://github.com/denizzzka/vibe.d.db.postgresql/blob/master/.travis.yml

This behavior appeared a few weeks ago

**Comment by MartinNowak** [comment]
The whole .travis.yml never worked.
https://travis-ci.org/denizzzka/vibe.d.db.postgresql/builds/109338404
Took me a while to figure it out, you have a BOM in your yaml file, and travis/ruby can't handle that.

**Comment by MartinNowak** [comment]
Please rename the issue or open a new one, this is already the second time this happened, and it always takes a long time to figure out.

**Comment by MartinNowak** [comment]
https://github.com/denizzzka/vibe.d.db.postgresql/pull/3

**Comment by denizzzka** [comment]
duplicate:
https://github.com/travis-ci/travis-ci/issues/3172
