### ISSUE TITLE
Missing python version 3.3.3

### ISSUE THREAD

**Issue by asfaltboy** [travis-ci/travis-ci#5683]
I have an issue similar to issue #5078 , only for python version `3.3.3`. See [the failing build log](https://travis-ci.org/asfaltboy/SublimeTestPlier/builds/111198387) for details.

The app I'm testing is a **_Sublime Text 3_** plugin, so I tried to test against the bundled python version that it uses (i.e `3.3.3`). ST3 is quite a popular text editor, so I assume other users will also benefit from testing against this specific version.

**Comment by BanzaiMan** [comment]
Sorry for the delay. I've initiated a build of 3.3.3. It will be available in 10 minutes or so.

Let us know if you continue to have problems.
