### ISSUE TITLE
Build test may fail because of dictionary output in dostring example

### ISSUE THREAD

**Issue by Michael-E-Rose** [travis-ci/travis-ci#5684]
Docstrings with examples that contain a dictionary printout are likely to fail because Travis CI can get another result that what it expected based on the docstring:

```
"""This method prints a dictionary.

Examples
--------
>>> a = dict(x=1, y=2)
>>> a
{'y': 2, 'x': 1}
""""
```

this may fail because Travis CI may get `{'x': 1, 'y': 2}` but expect `{'y': 2, 'x': 1}`. See for example [this Travis CI test report](https://travis-ci.org/networkx/networkx/jobs/111194760).

I consider this as bug because it's really unpredictable in which order the dictionary will be printed. It's annoying when the test fails because of such peculiarity. However it's important to have examples including print-outs.

**Comment by BanzaiMan** [comment]
How is this a Travis bug? Python Dictionaries are not ordered, right? If you are relying on `{'x': 1, 'y': 2}` to  be always written as `{'x': 1, 'y': 2}`, and do not account for `{'y': 2, 'x': 1}`, I think you are overly specific with your tests.

**Comment by Michael-E-Rose** [comment]
This is a bug, or at least an annoying feature, because the build test should pass irrespective of whether Travis CI gets `{'x': 1, 'y': 2}` or `{'y': 2, 'x': 1}`.

**Comment by BanzaiMan** [comment]
Sorry, but this is a language issue, not a Travis CI one.
