### ISSUE TITLE
Log command status message doesn't escape '\n' in commands

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#5685]
My `.travis.yml` contained this line:

``` yaml
script:
  - export TOXENV=`tox -l | grep py${TRAVIS_PYTHON_VERSION/./} | tr '\n' ','`
```

(trying to work around the lack of tox wildcard support, yucky I know)

The resultant log output was displayed over two lines rather than one:

```
The command "export TOXENV=`tox -l | grep py${TRAVIS_PYTHON_VERSION/./} | tr '
' ','`" exited with 0.
```

...since the `\n` was treated literally, even though it was in quotes.

See:
https://travis-ci.org/edmorley/peep/jobs/111210227#L185

**Comment by BanzaiMan** [comment]
Duplicate of #3772.
