### ISSUE TITLE
R   vignette builder 'knitr' not found

### ISSUE THREAD

**Issue by mstellwa** [travis-ci/travis-ci#5687]
I am probably missing some setting but my tests are failing with the following output:

Building with: R CMD build 
0.44s$ R CMD build  .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘rfml’:
* checking DESCRIPTION meta-information ... OK
Error in loadVignetteBuilder(pkgdir, TRUE) : 
  vignette builder 'knitr' not found
Execution halted

My  .travis.yml:
language: R
cache: packages
warnings_are_errors: true
sudo: required

r_binary_packages:
- arules
- knitr
- rmarkdown

install:
- env
- if [ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] ; then ./shared/dev-tasks/travis-install-ml.sh
  release ; else (exit 0) ; fi
- if [ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] ; then ./shared/dev-tasks/setup-marklogic.sh
  ; else (exit 0) ; fi

My imports and suggests in DESCRIPTION
Imports:
    methods,
    httr,
    PKI,
    jsonlite,
    XML
Suggests:
    arules,
    testthat,
    knitr,
    rmarkdown

@craigcitro, @hadley and @jimhester any ideas?

**Comment by jimhester** [comment]
You are overriding the `install` step which is where the dependencies are installed. You might try putting your custom install steps in `before_install:` instead.

**Comment by mstellwa** [comment]
Thanks. 

Changed and now it works.
