### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by AnamaryHdez** [travis-ci/travis-ci#5688]
Hi, I recently installed android-studio-bundle-141.2288178-windows and now I download from github artoolkit5-master. When I tried to run it it gives me problem with the proxy configuration, but I download all the files I need it an put it in the sdk. Now my problem is that when I try to sync it gives me the error:
```
Error:(29, 0) Gradle DSL method not found: 'android()'
Possible causes:<ul><li>The project 'ARBaseLibProj' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Fix plugin version and sync project</a></li><li>The project 'ARBaseLibProj' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>
```
Thanks.

**Comment by BanzaiMan** [comment]
Hello. Could you elaborate on how this error relate to Travis CI?

**Comment by BanzaiMan** [comment]
This has become stale.
