### ISSUE TITLE
[Feature Request] Deliver webhooks with application/json content type.

### ISSUE THREAD

**Issue by jfraboni** [travis-ci/travis-ci#5691]
Please please please provide the option of delivering webhooks with application/x-www-form-urlencoded AND application/json content types.

Many wonderful platforms on the Internet accept only true JSON bodies.

**Comment by BanzaiMan** [comment]
I thought there was only one `Content-Type` header allowed in a request. https://tools.ietf.org/html/rfc2616#section-3.7

**Comment by icolwell** [comment]
YES! x 100
trying to parse application/x-www-form-urlencoded with some existing tools and it isn't fun.

**Comment by asdfkaba** [comment]
+1
Let us choose the content type

**Comment by jfraboni** [comment]
Yes, @BanzaiMan, I mean OR, not both at the same time.

**Comment by scrthq** [comment]
can this get reopened? it's unfortunate that it went stale as this would be a HUGE value addition for webhook endpoints that only accept `application/json` content-type. Currently working on a Google Apps Script based CI/CD notification consumer and dealing with `x-www-form-urlencoded` payloads is painful.

**Comment by Blockost** [comment]
Dear Mr Travis, 

Please, make it happen.

Yours sincerely,

**Comment by mikesparr** [comment]
Has this been implemented yet or is it possible to declare content type in config? Trying to integrate with Spinnaker using webhook trigger and believe it will only work with `application/json` content type header.
