### ISSUE TITLE
Support for .NET 4.6.1?

### ISSUE THREAD

**Issue by NullVoxPopuli** [travis-ci/travis-ci#5692]
cc @joshua-anderson @akoeplinger @nterry

I read in another issue that the currently installed version of mono only supports up to .NET 4.5.

With microsoft's push towords cross-platform open source things, is there a way to maybe use their `dnvm` or `dotnet` toolset for compiling to 4.6.1? Or is support for 4.6.1 coming in mono?

What I'd inevitably like to do is have my project automatically deployed to nuget upon passing a travis build, and the other projects that use my travis project are 4.6.1, and I don't think that compling for 4.5 would work.

Here is my current .travis.yml for reference: https://github.com/etkirsch/NetDiff/blob/master/.travis.yml

**Comment by akoeplinger** [comment]
Yes, the upcoming Mono 4.4 contains support for the .NET 4.6.1 profile.

As for `dotnet`: this is tracked in https://github.com/travis-ci/travis-ci/issues/5189, I intend on adding support

**Comment by NullVoxPopuli** [comment]
Cool, thanks!

Idk if you want to use this ticket to track upgrading mono, or if there is one already -- but feel free to close it. :-)

**Comment by akoeplinger** [comment]
Mono will be upgraded automatically once the stable version is released, so no need to track here :)
