### ISSUE TITLE
Travis can't fetch refs.

### ISSUE THREAD

**Issue by jcampbell05** [travis-ci/travis-ci#5693]
With the recent deploy I have started getting this:

```bash
The command "eval git fetch origin +refs/pull/649/merge:" failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/649/merge
The command "eval git fetch origin +refs/pull/649/merge:" failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/649/merge
The command "eval git fetch origin +refs/pull/649/merge:" failed 3 times.
The command "git fetch origin +refs/pull/649/merge:" failed and exited with 128 during .
Your build has been stopped.
```

A few steps before it has already cloned the repo successfully, so I am not sure what the issue is.

**Comment by BanzaiMan** [comment]
Is the PR still open?

**Comment by jcampbell05** [comment]
@BanzaiMan  ah that would be it, is there a way to trigger an action to cancel the PR request upon merge.

**Comment by BanzaiMan** [comment]
@jcampbell05 That is a reasonable feature, but this does not happen automatically.

Can we close this?

**Comment by jcampbell05** [comment]
@banzaiman sure, should I'll file this request with GitHub?

**Comment by BanzaiMan** [comment]
@jcampbell05 There might have been one already (but I couldn't find it). Maybe your search-fu is stronger than mine, so be sure to search for it before opening one. :-)

I'm closing this in the mean time.
