### ISSUE TITLE
Add support for container builds using Ubuntu 14.04/Trusty

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#5695]
We absolutely love the Travis container infra, however are unable to use it currently since we need MySQL 5.6 (#1986) - and installing anything newer [is broken](https://github.com/travis-ci/apt-package-whitelist/issues/1206#issuecomment-149884653) with the Ubuntu Precise containers.

This means we have to use the [GCE Trusty](https://docs.travis-ci.com/user/trusty-ci-environment) infra, which:
- often has a large pending job backlog (GCE graphs are frequently flatlined on the [status page](https://www.traviscistatus.com/))
- has a slower boot time (unavoidable given full VM)
- defaults to mysql 5.5, so job time still has to be spent installing mysql 5.6
- _[Now fixed: [blog post](https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone)]_ ~~doesn't support caching for our Python deps (#4997)~~
- means we have to resort to undocumented .travis.yml hacks to mix and match stacks [1], which fail the linter & could presumably stop working at any point.

I'm hoping that a Ubuntu Trusty (14.04) based container stack would allow us to install mysql 5.6 using APT [2] and thus avoid the above - and so significantly reduce our test end to end times (plus presumably be cheaper for you too :-)).

A [blog post in November](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future) said:

> Since the new Precise images on GCE do include some updates, we're planning to update the images used in our containerized builds to match, shortly after we get to 100% in the migration. Look for a blog post announcing that and details on what changes will be included in the update.

Since the blog post was 3 months ago, I was wondering:
(a) has 100% migration now occurred, or is the 2015-12-15 update on the blog post still correct?
(b) is there a rough ETA for when the container environments will be updated, or an idea of how much work is left?

Many thanks!

[1] Since we want to only use the non-container infra on the jobs that absolutely need it, so have to nest the `sudo:` and `dist:` keys inside the matrix `include:` section ([our .travis.yml](https://github.com/mozilla/treeherder/blob/master/.travis.yml)).
[2] An [official package](http://packages.ubuntu.com/trusty/mysql-server-5.6) is available, so presumably this will not experience the same conflicts as with the Ubuntu Precise container image.

**Comment by BanzaiMan** [comment]
Please be assured that this is on our roadmap. Unfortunately, we do not have ETA to share yet.

**Comment by edmorley** [comment]
Ok, thank you for the reply :-)

**Comment by photodude** [comment]
:+1: Yes please add a Trusty (14.04) or newer based container stack

HHVM in the Precise container stack is capped at 3.6.6 which is an unsupported HHVM version. Trusty has newer HHVM versions.

**Comment by jakirkham** [comment]
+1, newer copies of Boost on Trusty. Would be great to have this. Though still need to figure out this ( https://github.com/travis-ci/travis-ci/issues/5533 ). :/

**Comment by rastislavszabo** [comment]
+1 for this request

**Comment by emirb** [comment]
+1

**Comment by edmorley** [comment]
I wonder if it's even just worth skipping 14.04 and instead working on 16.04 container support? (Given Xenial was released 4 days ago)

**Comment by solarce** [comment]
@edmorley We are currently focused on support 12.04 and 14.04 as our primary environments. At the moment, it is unlikely that we'll be supporting 16.04 as a native environment this year. We do hope to ship support for Trusty container-based builds in the next few months.

If you're particular use cases require something newer than 14.04, I would encourage you to use utilize our [Docker support](http://docs.travis-ci.com/user/docker/), which would allow you run your build inside a Docker image of a newer Ubuntu release. While the start up times are slower than our countainer-based builds, you get a full VM with 7.5GB of RAM, for each build.

Regards,
Brandon Burton
Infrastructure Manager

**Comment by ThomasWaldmann** [comment]
+1 for trusty container.

i can't use the precise container as i need liblz4(-dev) which is not available there.

**Comment by kevmoo** [comment]
@solarce Any updates on 

> We do hope to ship support for Trusty container-based builds in the next few months.

The Dart org (and community) has been happy users of Travis for a long time, but with our latest builds, we *need* Trusty.

Thanks!

**Comment by BanzaiMan** [comment]
Sorry for the delay, but this is a rather significant undertaking, going beyond offering Trusty images on EC2.

We will update this ticket when we have them. Thank you for your patience.

**Comment by photodude** [comment]
@BanzaiMan are `Xenial Xerus` container-based builds on the roadmap/in-development? Trusty container-based builds on Travis CI have yet to be released and [Trusty is just about to go into maintenance release mode until early 2019](http://www.ubuntu.com/info/release-end-of-life).

**Comment by BanzaiMan** [comment]
@photodude Yes, it is on the roadmap. Thanks.

**Comment by photodude** [comment]
Thanks @BanzaiMan

**Comment by edmorley** [comment]
Hurrah! :-)
https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/

**Comment by solarce** [comment]
As @edmorley linked to, we've opened up a public beta of Trusty container-based builds. The primary _beta_ aspect of it, is that it has its own [apt package allowlist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty) and so we expect **some  🐛 s** along the way while people ramp up usage and we discover packages that need to be added. Please file issues and email support@travis-ci.com as you encounter issues and we'll work to resolve them promptly.

In 2017-Q1, we plan to get the Trusty build environment out of _beta_ and up to parity with Precise, in terms of what's included by default, as far as parity makes sense.

We'll also be planning out changing the default to Trusty sometime in 2017. Finally, the earliest we'll begin work on starting to support 16.04 will be late 2016-Q2. 

All these estimates are, of course, subject to revision based on changing priorities.

Thanks everyone for your patience and continued usage of Travis CI!

**Comment by janisozaur** [comment]
> We'll also be planning out changing the default to Trusty sometime in 2017. Finally, the earliest we'll begin work on starting to support 16.04 will be late 2016-Q2.

I assume you meant **2017**-Q2?

**Comment by solarce** [comment]
@janisozaur I do mean 2017, fixed, thanks

**Comment by photodude** [comment]
@solarce I've reported the following Trusty container-based builds error as requested.
```php
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```
Email sent, and mentioned in this issue https://github.com/travis-ci/travis-ci/issues/6842

**Comment by bardiharborow** [comment]
The Google Cloud SDK is *still* not on the APT whitelist. I've had a request (travis-ci/apt-package-whitelist#3515) in since November, but I identified the blocking issue in December and made a PR (travis-ci/apt-source-whitelist#346). @meatballhat @BanzaiMan I hate to hassle you, but this seems a fairly easy fix from your end. Pretty please?

**Comment by photodude** [comment]
Trusty is still worthless for projects that need mysql, due to issue #6842

**Comment by zachborboa** [comment]
Is it possible to offer rolling releases for containers? It may avoid a lot of the problems caused by using named releases.

**Comment by skirpichev** [comment]
Trusty container buids are noticeably slower than precise, e.g. in diofant/diofant#475 I split jobs several times to avoid timeouts.  Could this be related somehow just to beta testing?

**Comment by edmorley** [comment]
The trusty builds are out of beta, so this is done :-)

For Xenial, there's #5821.
