### ISSUE TITLE
Build skips 'install' step

### ISSUE THREAD

**Issue by mestebangutierrez** [travis-ci/travis-ci#5697]
The [first build](https://travis-ci.org/SmartDeveloperHub/sdh-testing/builds/111590378) of the *develop* branch from our ([SmartDeveloperHub/sdh-testing](https://github.com/SmartDeveloperHub/sdh-testing)) is failing. 

Having a look at the logs, I've seen that the *before_install* step finishes in __line 252__ and that the *before_script* step starts in the following line. What happened to the *install* step? Because that step is not executed the build fails. 

Despite I've retried executing the build several times, the result has not changed. How can we solve it?

**Comment by BanzaiMan** [comment]
You are `source`ing [this script which sets `-e`](https://github.com/SmartDeveloperHub/sdh-testing/blob/942cfc6f7ceb9cba3664ef703ccff7cfbeaac29c/.travis/utils.sh#L2), and it is failing:

```
target/config/ci/secring.gpg.enc: No such file or directory
```

As a result, the build terminates prematurely and it never gets to the `install` and later phases.

**Comment by mestebangutierrez** [comment]
The point is that the failure you mention happens because the __install__ step of the build is not executed, despite the [build lifecycle](https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle) claims that it is executed *__before__* the __before_script__ step. 

Because the __install__ step does not execute, the script executed in the __before_script__ step fails to find a file, and thus fails, causing the build to fail.

So the real problem is that the __install__ step is not being executed. But why and how can it be solved?

**Comment by BanzaiMan** [comment]
You are `source`ing this script in `before_install`: https://github.com/SmartDeveloperHub/sdh-testing/blob/942cfc6f7ceb9cba3664ef703ccff7cfbeaac29c/.travis.yml#L17-L18 Your build never gets to `install`, which happens before `before_script` and `script`.

**Comment by mestebangutierrez** [comment]
I think that you haven't paid attention to the log. I include below the last part of it:
```console
travis_fold:start:before_install
[0Ktravis_time:start:1de58310
[0K$ source ./.travis/utils.sh prepare-repo

travis_time:end:1de58310:start=1456348334241025917,finish=1456348334244416327,duration=3390410
[0Ktravis_fold:end:before_install
[0Ktravis_fold:start:before_script
[0Ktravis_time:start:181fb5a9
[0K$ source ./.travis/utils.sh prepare-keys $ENCRYPTION_PASSWORD
Decrypting private key...
target/config/ci/secring.gpg.enc: No such file or directory
140021058832032:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('target/config/ci/secring.gpg.enc','r')
140021058832032:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
```
As you can see the __before_install__ step starts and end in lines 1 and 6, respectively. In line 7 the __before_script__ step starts, and the ` ./.travis/utils.sh` script is executed in line 9 and fails in line 11, making the build fail lines (lines 12 to end).

Again, the problem is not in the script that fails itself. The script fails because the __install__ step (Maven execution, by default) is not executed. Why doesn't it execute?

**Comment by BanzaiMan** [comment]
Ha. You are right about that. Sorry for the confusion there. Looking further now.

**Comment by mestebangutierrez** [comment]
No problem :smile:

**Comment by BanzaiMan** [comment]
Upon further investigation, though, your `java` build does not have any file to indicate a build method (via Maven, Gradle, or Ant), so nothing happens in the `install` phase. See https://docs.travis-ci.com/user/languages/java for further details.

**Comment by mestebangutierrez** [comment]
Ha. I've just realized that I failed to commit the POM file in my last commit. Therefore Travis could not execute the install step. My fault. :sob: 

I thing that it would be a **great** idea to log this corner case in order to facilitate diagnosing this scenario. Take into account that this could also happen in the *script* step. 

And this makes me wonder if it makes sense to finish the build succesfully if neither the *install* nor the *script* steps are executed because Travis fails to detect what to run...

**Comment by BanzaiMan** [comment]
How would you tell the difference between the unintended absence of `install` method and the intended one? I don't think this is an easy one to answer, and I tend to side with the current behavior.

**Comment by mestebangutierrez** [comment]
Good question. If the user has overriden the default install step, then there's not doubt it will be executed (if possible). If not, then the default install step is to be executed. 

If the default fails to be executed, like in the case described in this issue, it would be easy to log the fact that the default install could not be executed (in the case of this issue because no Maven POM file or Ant build.xml file could be found). 

Travis knows whether or not the install/script steps are overriden (there are lots of validations you carry out for sure :laughing:) and for sure knows which are those defaults used if they are not and the conditions that have to be met for them to be executed. Pouring those details in the log would be great, as I said before.

**Comment by BanzaiMan** [comment]
The issue is not what is known and what is not to Travis. The issue is whether or not there exists a reasonable default for JVM builds when a clear indication does not exist. Writing something to the logs may be convenient for you, but it's not entirely clear for other users.

**Comment by mestebangutierrez** [comment]
As a Travis user, whenever a build fails having as much information as possible regarding the build process is fundamental. 

Given that we cannot access in any manner to the files produced during the failed build, we have to resort to the log to find out what happened. Of course, other user-oriented  diagnostic messages or warnings would be great, as it would not require a deep understanding of the build process for a casual user. However, power user will keep going back to the logs to check everything. And the more information in there to help understanding what happend, the best.

Again, this does not prevent improving the documentation by making clear corner cases such as the one that made me open this issue (I could not see anywhere in the docs where it says that if the defaults cannot be applied the step is skipped), having additional diagnostic messages, etc.
