### ISSUE TITLE
iOS SDK 9.2 is missing on RubyMotion Build

### ISSUE THREAD

**Issue by sxross** [travis-ci/travis-ci#5699]
This makes it impossible for me to test my open-source Ruby Gem, MotionModel. Can the 9.2 SDK be added?

Thanks

**Comment by BanzaiMan** [comment]
Did you choose the correct OS X image? https://docs.travis-ci.com/user/languages/objective-c

**Comment by sxross** [comment]
My .travis.yml looks like this:

```
language: objective-c
before_install:
  - ruby --version
  - sudo chown -R travis ~/Library/RubyMotion
# Figure out if we have latest RubyMotion
  - motion --version
  - sudo motion update
  - motion --version
install:
  - ruby -S bundle install
# rvm:
#   - "1.9.3"
script:
  - bundle install
  - bundle exec rake clean
  - bundle exec rake spec
```

My RubyMotion project specifies the 9.2 SDK, but I don't know how to get Travis to find it.

**Comment by BanzaiMan** [comment]
Did you read the document I showed above? It shows you that Xcode 7.2 and 7.3 images have iOS 9.2 support.

You'd need:

```yaml
osx_image: xcode7.3 # or xcode7.2
```

**Comment by BanzaiMan** [comment]
Closing this now. If you are still having problems with the latest image, please point to a build log that shows the problem.
