### ISSUE TITLE
Help for long running build

### ISSUE THREAD

**Issue by asartori86** [travis-ci/travis-ci#5700]
Hi, I am facing this issue. The building of the dependencies of my code takes long time. On container based system I am forced to compile with `make -j1` because of ram issue. But the building is stopped after 120 minutes. On trusty, I can compile with more processors (since the ram is bigger) but the job is killed after 40 minutes. Obviously, the dependencies will be cached but I need to compile them at least once :)

Could you give me some advice? Thanks!

**Comment by asartori86** [comment]
I've also noticed that sometimes, on Trusty, the job is restarted.. don't know why

**Comment by asartori86** [comment]
A possible workaround could be the possibility to **automatically** cache a dependency once it is built and reboot travis such that the next job will build another dep until they are all built and cached and the actual test procedure can run

**Comment by BanzaiMan** [comment]
I assume that the repository in question is a private one, since you cite the 120-minute limit. With the timeout, there is no chance for any cleanup to take place, including cache uploading.

If the build succeeds on GCE (with `sudo: required`), then you can run one build there and upload the cache, so that subsequent builds on containers. You can't use Trusty, though, because the resulting cache might not be usable on containers (which is currently on Precise). You can specify the release with `dist: precise` along with `sudo: required`.

**Comment by asartori86** [comment]
Hi, thanks for replying. Actually it is a public one.. https://github.com/asartori86/pi-DoMUS

if you need it, I am working on the *openmpi-travis* branch

**Comment by asartori86** [comment]
I've just try to build it using `sudo: required` and `dist: precise` but it was stopped after 48 min https://travis-ci.org/asartori86/pi-DoMUS/builds/112299172

**Comment by BanzaiMan** [comment]
What are you installing? Are there any binary packages available somewhere? I think GCE instances have more memory, so you might have luck with running more jobs, too.

**Comment by asartori86** [comment]
@BanzaiMan, I am installing a solver for sets of partial differentials equations. I need to compile two big libraries: Trilinos and deal.II.  If there is a way to install one at a time and cache them this would be sufficient. something like 
```
if both trilinos and dealii are not installed
then
install only trilinos
cache and exit
else
install the missing one
continue regularly the test
end
```
in such a way the script is not modified and when I know that I need to rebuild the cache I just need to rerun travis a couple of time without changing the script (and commiting)

**Comment by asartori86** [comment]
@BanzaiMan, in the documentation there is this very sentence: **There is no timeout for a build; a build will run as long as all the jobs do as long as each job does not timeout.**

but I'have seen many timeouts :) maybe I need to move the installation of the dependencies in a particular part of the `.travis.yml` file (e.g., `install`, `script`, `before_script`) such that the above statement holds?

**Comment by solarce** [comment]
@asartori86 I apologize for the confusion. We do have a default time limit of 50 minutes for public repository builds. We will update our documentation to better reflect this.

**Comment by gerddie** [comment]
Considering that trilinos is in Ubuntu as of Xenial it should be possible to backport the package to trusty and upload it to an Ubuntu PPA that you can then use to install the pre-build dependency. This should save some build time. 

Apart from that I'd like to mention #5174, i.e. one option from  the side of travis-ci could be to not limit the single build, but the all-over build time a user of a free software project has within a given time frame.

**Comment by kevin-leptons** [comment]
okay, this is problem unsolved. i must run building on local machine and wait half of day for one build :dancer:

**Comment by abhi1693** [comment]
There should be way to increase the build time. I'm also facing the same problem as @kevin-leptons

**Comment by kevin-leptons** [comment]
@abhi1693 , if your prolem are long time of building, use enterprise package of travis-ci or do ti on local system. public them package have many problem for long time building

**Comment by abhi1693** [comment]
@kevin-leptons I've temporary found a solution to my problem. You can check [here](https://github.com/PandaLinux/pandaOS/blob/travis-ci/.travis.yml) for reference.

**Comment by kevin-leptons** [comment]
i had to check .travis.yml of pandaOS. that have two properties are sudo,
os. i did try that properties and build time not longer than 50 minutes 😂.
what does your meaning ?

On Mon, May 9, 2016 at 10:40 PM, Abhimanyu Saharan <notifications@github.com
