### ISSUE TITLE
Godep misbehaves and errors builds when GO15VENDOREXPERIMENT is set

### ISSUE THREAD

**Issue by paddyforan** [travis-ci/travis-ci#5702]
Go underwent (is undergoing?) a vendoring experiment starting with Go 1.5, and it's now on by default in Go 1.6. Basically, it allows for a `vendor` folder in the root of your project, which acts like a `$GOPATH` dir for that project. If you have the following `$GOPATH`:

```
- $GOPATH/src
  - pkgA
    - vendor
       - pkgB
  - pkgB
  - pkgC
```

If you import `pkgB` from within `pkgA`, it automatically rewrites the import path to be `pkgA/vendor/pkgB`. But if you import `pkgB` from within `pkgC`, it uses the `pkgB` import path as usual.

Basically, the same thing Godep does, except there's no rewriting or mucking with the GOPATH. Yay!

This is only problematic because I (and probably others?) use Godep to manage my vendoring, but I use the Go 1.5 vendoring strategy. Meaning Godep doesn't store my packages in `Godeps/_workspace`, it stores them in `vendor`. See the [note in the README](https://github.com/tools/godep/tree/b32db8cfcaad4ba20d85667d0978d02e68a6207f#migrating-to-vendor).

This is only a problem on Travis because, from what I can tell, `godep restore` doesn't have an actual repo to work with, so it can't actually restore.

Here's the error message I got:

```
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
# cd /home/travis/gopath/src/darlinggo.co/tokens/Godeps/_workspace/src/code.secondbit.org/uuid.hg; hg update -r '15ee0cb56e65a4d866745e413efc20114d691862'
```

Fortunately, there's a fix for all of this that isn't too bad. The new vendoring logic is turned on in two very specific conditions:

* We're using Go version 1.5 or higher and the `GO15VENDOREXPERIMENT` environment variable is set to `1`
* We're using Go version 1.6 or higher and the `GO15VENDOREXPERIMENT` environment variable is _not_ explicitly set to `0`

If either of those is true, then there's nothing besides `go build` or `go test` that needs to be run. So if the check for godep use is qualified to only run godep restore and create the folders and such if neither of those conditions is true, then everything should continue to work if it already works, and a few broken things start working, too.

**Comment by sillyfellow** [comment]
This kind of killed my env.

**Comment by paddyforan** [comment]
This is, as far as I know, fixed. Thanks :)
