### ISSUE TITLE
travis-ci default python 2.7 version

### ISSUE THREAD

**Issue by gliptak** [travis-ci/travis-ci#5704]
Running with ```sudo: false```, I see:

```
$ python --version
Python 2.7.3
````
Could a more current ```Python 2.7``` be offered by default?

Thanks

**Comment by BanzaiMan** [comment]
On non-Python images, we provide Python via the Ubuntu package. For Precise, this is 2.7.3. http://packages.ubuntu.com/precise/python

If you need a more recent versions, please use the Python image, or use [Trusty](https://docs.travis-ci.com/user/trusty-ci-environment#Image-differences-from-Precise), which has a more recent version or allows the use of virtualenv.

**Comment by gliptak** [comment]
```Trusty``` is still only ```2.7.5``` ... http://packages.ubuntu.com/trusty/python Thanks for the pointer
