### ISSUE TITLE
Sent confirmation email for wrong PR

### ISSUE THREAD

**Issue by asmaloney** [travis-ci/travis-ci#5706]
This is strange.  I don't know if this is the right place to report this.  I looked all over the Travis-CI page (travis-ci.org - my status page I guess) to try to figure out how to report errors.

I submitted several PRs to a repo in succession.  They all started doing their builds.

One of them (Build #454) finished.

The email that I received claimed that one of the other ones (Build #457) completed and succeeded.

When I looked again through GitHub, it (Build #457) was still running and (Build #454) had completed.

**Comment by BanzaiMan** [comment]
We can't look into them because the references are incorrect.

**Comment by BanzaiMan** [comment]
Closing due to lack of information.
