### ISSUE TITLE
Profile screen freezes on Syncing from GitHub status

### ISSUE THREAD

**Issue by diogolundberg** [travis-ci/travis-ci#5709]
I revoked the Travis-CI access from my organization to test some configurations and now i can't have my organization back.

This is my Travis CI profile:
https://travis-ci.org/profile/diogolundberg
My Organization:
https://github.com/DataViva
I lost my access to:
https://travis-ci.org/DataViva/dataviva-site

I guess it's the same issue to #2765
Could you reset my user data, like the solution given to #5506? =)

I think this must be something related to that https://github.com/travis-ci/travis-core/commit/dd013b9f663c26b01390a627fe8a3d25d5bc068b 

As @rkh said:

> reset_token service gets a 404 from github, then drops the token from our database.
> I can reproduce this with my account. This means we probably lost a lot of tokens.

![syncing](https://cloud.githubusercontent.com/assets/4092969/13384865/dd398138-de78-11e5-9317-16101d3eb3c8.png)

Thanks in advice!

**Comment by renaesop** [comment]
same issue！

**Comment by ultimagriever** [comment]
Same here as well. I'm stuck on that screen for almost a day now.
