### ISSUE TITLE
Mark builds with final status when only allowed failures are left

### ISSUE THREAD

**Issue by segiddins** [travis-ci/travis-ci#5719]
When a build matrix includes allowed failures, the build as a whole will be marked as pending until _all_ builds have finished, even allowed failures. This is unnecessary, as the allowed failure matrix entries cannot effect the status of the build as a whole.

**Comment by BanzaiMan** [comment]
This is what the `fast_finish` option (https://docs.travis-ci.com/user/customizing-the-build#Fast-Finishing) is for. It has some bugs (see https://github.com/travis-ci/travis-ci/issues/2633 for an example), but it accomplishes what you are after.

**Comment by indirect** [comment]
Unfortunately, #2633 makes it completely impossible for us to use `fast_finish`. Will it ever be possible to use `fast_finish` without getting over twenty build notifications per commit?
