### ISSUE TITLE
build failed for apt-get if use sudo: false

### ISSUE THREAD

**Issue by ruiyang2015** [travis-ci/travis-ci#5720]
try to use the new container based by setting sudo: false.
but it failed for apt-get install. I try to put sudo as well, and apt-get can not run.

**Comment by BanzaiMan** [comment]
@ruiyang2015 Sorry, but we need more information to help you. Do you have a build log URL that shows this problem?

**Comment by ruiyang2015** [comment]
ok, found the document for this section, figure out how to do it. thx
