### ISSUE TITLE
Local apt proxy for standard repositories

### ISSUE THREAD

**Issue by tripleee** [travis-ci/travis-ci#5721]
Transient network errors cause intermittent build problems when remote Apt repositories cannot be reached. This is somewhat tricky to debug, because it is not apparent which repositories Travis adds behind the scenes.  (Witness my issue https://github.com/travis-ci/travis-ci/issues/4937 where a build could not proceed because of a MongoDB repo connection problem, even though the build does not use MongoDB for anything.)

In addition to making builds more robust by adding redundancy, a local caching Apt package proxy would also improve performance and reduce load on remote repos.

**Comment by solarce** [comment]
This is something we have tentatively planned for later in the year, can I cannot provide a more definitive ETA for it as this time.

Thanks,

Brandon Burton
Infrastructure Manager

**Comment by tripleee** [comment]
Closing a ticket implies to me that the problem is fixed. Closing a ticket prematurely negates most of the benefits of having a public bug tracking system. Of course, if you can point to a similarly public backlog where people who are affected by this can track its progress, please link to that instead. Thanks.
