### ISSUE TITLE
Builds stated to restart, but restart not occuring

### ISSUE THREAD

**Issue by Kelketek** [travis-ci/travis-ci#5725]
https://travis-ci.org/edx-solutions/xblock-drag-and-drop-v2/builds/112689200

My Google searches on this previously seem to indicate it's often an issue of the message bus being down, but I don't see anything on the status page about this?

**Comment by hadinishad** [comment]
There actually seems to be no such branch on the repo.

**Comment by Kelketek** [comment]
@hadinishad This was fixed before it was looked at, the subsequent build passed, the PR was merged, and the branch was removed post-merge.

**Comment by BanzaiMan** [comment]
Sorry for the delay.

This is an operations issue we work on continuously.

I'm closing this now, since it is not a problem at the moment.
