### ISSUE TITLE
Perfect (working order) c# application fails to build

### ISSUE THREAD

**Issue by codemonkeyrawks** [travis-ci/travis-ci#5726]
Looks like my project written in c# fails to build:
https://travis-ci.org/codemonkeyrawks/AngularJSDemo

Are you guys able to take a look at it and see what might be failing. It uses:
AngularJS
Entity
Bootstrap

I was curious is Entity supported on mono?
I have played with: http://dotnet.github.io/getting-started/ and it seems to work without Entity.

**Comment by BanzaiMan** [comment]
@joshua-anderson @akoeplinger @nterry

**Comment by Joshua-Anderson** [comment]
I think the main warning message is:

```
/usr/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.5.2' not supported by this toolset (ToolsVersion: 12.0).
```

@akoeplinger: Does mono stable support dotnet v4.5.2?

**Comment by akoeplinger** [comment]
It does not, but the upcoming Mono 4.4 will.

You can add `mono: alpha` to try the preview version from the alpha channel.

**Comment by codemonkeyrawks** [comment]
Removing 'System.Web.Entity' helped. I will try installing mono and see if I can get this project to work. Still fails currently.

**Comment by codemonkeyrawks** [comment]
Using: (https://github.com/codemonkeyrawks/AngularJS-Demo-Core/blob/master/.travis.yml) seemed to work for me now that I took some time to learn about the dotnet command line!
