### ISSUE TITLE
`The command "eval git fetch origin +refs/pull/420/merge:" failed. Retrying, 2 of 3.`

### ISSUE THREAD

**Issue by mathiasbynens** [travis-ci/travis-ci#5727]
This recently started happening (without us changing our Travis CI config in any way) for builds triggered by GitHub pull requests:

> The command "eval git fetch origin +refs/pull/420/merge:" failed. Retrying, 2 of 3.

Example failed builds:

* https://travis-ci.org/operasoftware/devopera/builds/113098702
* https://travis-ci.org/operasoftware/devopera/builds/113110701

Log excerpt:

```
$ git clone --depth=1 https://github.com/operasoftware/devopera.git operasoftware/devopera
Cloning into 'operasoftware/devopera'...
remote: Counting objects: 2735, done.
remote: Compressing objects: 100% (2487/2487), done.
remote: Total 2735 (delta 138), reused 1737 (delta 127), pack-reused 0
Receiving objects: 100% (2735/2735), 390.44 MiB | 38.20 MiB/s, done.
Resolving deltas: 100% (138/138), done.
Checking connectivity... done.
Checking out files: 100% (2448/2448), done.
$ cd operasoftware/devopera
3.57s$ git fetch origin +refs/pull/420/merge:
fatal: Couldn't find remote ref refs/pull/420/merge
Unexpected end of command stream
The command "eval git fetch origin +refs/pull/420/merge:" failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/420/merge
Unexpected end of command stream
The command "eval git fetch origin +refs/pull/420/merge:" failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/420/merge
Unexpected end of command stream
The command "eval git fetch origin +refs/pull/420/merge:" failed 3 times.
The command "git fetch origin +refs/pull/420/merge:" failed and exited with 128 during .
Your build has been stopped.
```

**Comment by BanzaiMan** [comment]
The first build (https://travis-ci.org/operasoftware/devopera/builds/113098702) corresponds to this PR (https://github.com/operasoftware/devopera/pull/420), which was merged at 2016-03-02T11:31:16Z. Our build ran at 11:32:16, so the ref we wanted to build did not exist.

The second is similar.

**Comment by ashish173** [comment]
One solution here is to trigger a build manually on your base branch from travis's interface. This feature is in experimental feature but this way it picked up the latest code from the base branch and didn't care about the branch which got merged before the build succeeded.
