### ISSUE TITLE
Golang 1.6 builder fails with not found error on .a file

### ISSUE THREAD

**Issue by longsleep** [travis-ci/travis-ci#5728]
https://travis-ci.org/strukturag/phoenix/jobs/113105385

```
$ go test -v ./...
# testmain
/home/travis/.gimme/versions/go1.6.linux.amd64/pkg/tool/linux_amd64/link: cannot open file /home/travis/.gimme/versions/go1.6.linux.amd64/pkg/linux_amd64/github.com/dlintw/goconf.a: open /home/travis/.gimme/versions/go1.6.linux.amd64/pkg/linux_amd64/github.com/dlintw/goconf.a: no such file or directory
FAIL    github.com/strukturag/phoenix [build failed]
```

For some reason the .a file is not found. Works just fine when building locally with Go 1.6 and works fine for all other Go versions on Travis.

**Comment by BanzaiMan** [comment]
For builds on containers, you can try running it locally: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

For GCE and Mac builds, email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.

Thanks.
