### ISSUE TITLE
Create a $TRAVIS_CURRENT_BRANCH environment variable.

### ISSUE THREAD

**Issue by breerly** [travis-ci/travis-ci#5731]
I've found the behavior of `$TRAVIS_BRANCH` to be rather surprising:

> For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be master).

During builds, this means that `push` and `pr` builds have different values:

```
continuous-integration/travis-ci/push - $TRAVIS_BRANCH=<current branch name>  
continuous-integration/travis-ci/pr - $TRAVIS_BRANCH=master  
```

[This can be problematic!](https://github.com/yarpc/crossdock/issues/31)

## A Solution

I've created a temporary solutions for those who need the current branch name regardless of if their build is a `pr` or `push` - https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/#thetravisymlrecipe

## Proposal

Instead of querying the Github api at build time, I propose that Travis creates a `$TRAVIS_CURRENT_BRANCH` environment variable which *always* contains the name of the current branch, even in the case of `pr`-based build.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-ci/issues/1633 might address what you want.

**Comment by BanzaiMan** [comment]
Can we close this?

**Comment by breerly** [comment]
Sure - looks like #1633 is more or less the same and has been around for more than 2 years :cry:
