### ISSUE TITLE
Travis CI caches withdrawn python package protobuf-3.0.0-alpha-1 ?

### ISSUE THREAD

**Issue by michael-berlin** [travis-ci/travis-ci#5732]
I ran into https://github.com/grpc/grpc/issues/5534

The problem is that within Travis the dependent "protobuf" python package was installed by pip with the version ```protobuf-3.0.0-alpha-1```.

However, this version is hidden on the original mirror because it's bad version name results into being considered newer than actually newer packages:

```
3.0.0-alpha-1 > 3.0.0a3 (alpha 1 > alpha 3)
```

Therefore, also see: https://github.com/google/protobuf/issues/855

Do you cache this "faulty" -alpha1 package on your side maybe?

If so, can you please hide it as well?

Thanks!

**Comment by BanzaiMan** [comment]
We don't cache anything by default at the moment. If anything is cached, it is by the input from the user. If the cache contains a version that satisfies the requirements given by your code, I expect the package manager to use it. Whether `3.0.0-alpha-1` is considered newer or older than `3.0.0a3` is completely up to the package manager, and is beyond the control of Travis CI.

**Comment by michael-berlin** [comment]
Thanks for clarifying.

It must be some super weird combination of software then. I'm closing this issue and will report my findings here: https://github.com/google/protobuf/issues/855
