### ISSUE TITLE
Module not found - Artima Supersafe

### ISSUE THREAD

**Issue by vburca** [travis-ci/travis-ci#5734]
Hi,

I've been looking around for a while now but I can't find out why I get the following error through Travis on my build:
```
[warn] 	module not found: com.artima.supersafe#sbtplugin;1.1.0-RC6
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.artima.supersafe/sbtplugin/scala_2.10/sbt_0.13/1.1.0-RC6/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.artima.supersafe/sbtplugin/scala_2.10/sbt_0.13/1.1.0-RC6/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/travis/.ivy2/local/com.artima.supersafe/sbtplugin/scala_2.10/sbt_0.13/1.1.0-RC6/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/artima/supersafe/sbtplugin_2.10_0.13/1.1.0-RC6/sbtplugin-1.1.0-RC6.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/artima/supersafe/sbtplugin_2.10_0.13/1.1.0-RC6/sbtplugin-1.1.0-RC6.pom
```
Along with the summary of it here:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.artima.supersafe#sbtplugin;1.1.0-RC6: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.artima.supersafe:sbtplugin:1.1.0-RC6 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.artima.supersafe:sbtplugin:1.1.0-RC6 (scalaVersion=2.10, sbtVersion=0.13) (/home/travis/build/vburca/scala-lirc/project/plugins.sbt#L1-2)
[warn] 		  +- default:scala-lirc-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.artima.supersafe#sbtplugin;1.1.0-RC6: not found
```

Here are the instructions on adding the resolvers and plugin to `build.sbt` and `plugins.sbt` respectively:
http://www.scalatest.org/install

At the moment of the failed builds, this is how my build files look like:

[build.sbt](https://github.com/vburca/scala-lirc/blob/master/build.sbt)
[plugins.sbt](https://github.com/vburca/scala-lirc/blob/master/project/plugins.sbt)

To me, the error looks like the `resolvers` from `build.sbt` are not being updated... Locally, this build works fine. 

Am I doing something wrong? How should I properly update the `resolvers` such that `sbt` knows where to look for Artima Supersafe?

Thank you!
Vlad

**Comment by BanzaiMan** [comment]
This sounds like an application issue. If you follow the steps on a fresh machine, does it work? You can also test our Docker image: https://quay.io/repository/travisci/travis-jvm

**Comment by vburca** [comment]
Hi - thanks for the reply. I didn't end up building it in a Docker container, but I just added the resolvers to both `build.sbt` and `project/plugins.sbt`. I am still a bit confused as to why it was working locally for me before (by only having the resolvers in the `build.sbt`) and/or why do I need to put the resolvers in both places, but this is a different question I assume - I don't fully understand sbt I guess :)

Thanks again!
Vlad

**Comment by josiah14** [comment]
Somebody should go through and update the documentation on the official Artima site to reflect that adding the resolvers to global.sbt is not always sufficient. @vburca 's solution worked for me.

**Comment by rehan814** [comment]
@vburca It builds locally because it had already resolved and  downloaded the library in its cache. On my mac its .ivy and .m2 folders which contains all the cached copies. If you delete/move this folder. sbt will have to download it again and thats where you will see the error again.
