### ISSUE TITLE
Mismatch in Python libraries and Python interpreter.

### ISSUE THREAD

**Issue by Svalorzen** [travis-ci/travis-ci#5735]
I'm wrapping my C++ library using Boost::Python, and I use python in order to both compile the wrappings and to run python tests. I use CMake as build system.

At the moment CMake finds PythonLibs 2.7.6, while PythonInterp is 2.7.10. The main problem with this is that it seems that the two versions have different settings regarding unicode, so my tests fail with

> ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0: undefined symbol: PyUnicodeUCS4_FromEncodedObject

I have seen a similar problem in #5107 and possibly #5269. In my `.travis.yml` I have not yet put any python specific settings (language is `cpp`). Trying to install directly python2.7 did not change the result.

Do you have any suggestions on how to fix this problem?

**Comment by BanzaiMan** [comment]
Could you try the workaround mentioned in https://github.com/travis-ci/travis-ci/issues/5326?

**Comment by Svalorzen** [comment]
It works, thank you very much! =)
