### ISSUE TITLE
Private build with Docker doesn't start

### ISSUE THREAD

**Issue by oryband** [travis-ci/travis-ci#5736]
- Tried re-pushing branch
- Tried manual restart
- The above multiple times

For more than 60 minutes now.

Build doesn't start, stuck on "Hang tight, the log cannot be shown until the build has started."

**Comment by solarce** [comment]
We provide a fixed capacity to public builds right now, and unfortunately, right now, we are running at full capacity and a fairly significant backlog for `sudo` enabled builds.

We are working on some significant architectural changes to some of our backend services which should let us scale up this fixed capacity soon, but I am not able to provide a more specific ETA at this time.

Regards,

Brandon Burton
Infrastructure Manager

**Comment by oryband** [comment]
@solarce the topic says: *Private* build.

**Comment by oryband** [comment]
Why did you close the issue without commenting on the relevant topic? We (https://github.com/rounds) are a paying customer and are waiting for a private production build to start for more than an hour.

**Comment by solarce** [comment]
@oryband my apologies, you are correct that I did not notice _private_ in the topic of the issue and I am sorry I did not read your issue more thoroughly.
In general we do not monitor the public issue tracker with the same frequency as we manage our support ticket queue. I see your support ticket and will follow up with you there.

**Comment by oryband** [comment]
- Didn't receive a response via userlike or support@travis-ci.com, so I tried here. (Still haven't, btw)
- Search for recent related GitHub issues, found none.
- Opened this issue.

**Comment by oryband** [comment]
Private builds still don't start.

**Comment by oryband** [comment]
UPDATE: Builds start with a 20-minutes delay.
