### ISSUE TITLE
postgresql: "9.4" addon refuses to start

### ISSUE THREAD

**Issue by rochoa** [travis-ci/travis-ci#5737]
As per https://github.com/rochoa/test-travis/tree/786dce035bf0ebecf0e789f166502434a156cd24 it's not possible to start *PostgreSQL 9.4, because PostgreSQL 9.1 is currently running*.

Failing build example: https://travis-ci.org/rochoa/test-travis/builds/113438047

**Comment by BanzaiMan** [comment]
APT addon is limited in its scope to deal with non-standard installation steps. Here, I see that `apt-get` doesn't want to stop a running PostgreSQL instance, so this would fail.

The only possible workaround at the moment is to use `sudo: required`.

**Comment by rochoa** [comment]
Has that changed recently?

That approach has been working before:
 - Working build: https://travis-ci.org/CartoDB/Windshaft-cartodb/builds/111520460
 - .travis.yml for that build: https://github.com/CartoDB/Windshaft-cartodb/blob/465dde7a51c9ad7d4407533c1bf76ec1be4844bc/.travis.yml

**Comment by BanzaiMan** [comment]
@rochoa One thing that did change is that the failure to install an APT package now marks the build an error. In https://travis-ci.org/CartoDB/Windshaft-cartodb/builds/111520460#L178 you will notice that the package installation actually failed, but we moved on. If the build was passing previously without this package, then either you didn't need this package to begin with, or your tests did not exercise the functionalities provided by it.

**Comment by rochoa** [comment]
Oh, that makes sense. Sorry I didn't realise about previous builds' error log messages.

However the [tests preparation script was doing a `CREATE LANGUAGE plpythonu;`](https://github.com/CartoDB/Windshaft-cartodb/blob/465dde7a51c9ad7d4407533c1bf76ec1be4844bc/test/support/prepare_db.sh#L81).

I just [did a quick test of just removing the postgresql-plpython-9.4 apt package addon](https://github.com/CartoDB/Windshaft-cartodb/commit/9966e971042d2eb33eca08aaa2a4d2f2e2d5bbf4) and it [started to fail because `language "plpythonu" does not exist`](https://travis-ci.org/CartoDB/Windshaft-cartodb/builds/113548526#L662-L664).

Although your explanation totally makes sense to me and I understand that it is better to fail the build if there is an error on an addon installation. But ... isn't a bit weird the change of behaviour in this specific case?

p.s.: I was able to workaround the issues I started to have after this problem arose so this is not a blocker for me.

**Comment by BanzaiMan** [comment]
I don't know enough about these packages to say why it fails without the *attempt to install* `postgresql-plpython-9.4`.

Perhaps just an attempt is good enough to actually install (even though it cannot restart the service). Which leaves us in a bad spot. Perhaps we can accept an optional flag in the `apt` addon to ignore failures such as this (but such an option will leave the users in a vulnerable spot if there are other packages involved).

**Comment by rochoa** [comment]
I guess the important question here is: Does it make sense to make `postgresql-plpython-9.4` available through `apt:package` addons if it's not compatible with `postgresql: "9.4"` addon?

Probably this issue should be *postgresql-plpython-9.4 apt:package addon incompatible with postgresql: "9.4" addon*.

**Comment by zenitraM** [comment]
What seems to be failing on the apt-get install is not the installation of `postgresql-plpython-9.4` itself, but the fact that a newer version of `postgresql-9.4` is available on an added repo and is trying to get installed, and the upgrade fails: 
https://travis-ci.org/zenitraM/test-travis/builds/113658703#L146

The reason for the failure is that there seems to be a 9.1 PostgreSQL installed and maybe running _even if you have disabled the postgres addon_ so you cannot either install any PostgreSQL package separately even if you have disabled the addon: 
https://travis-ci.org/zenitraM/test-travis/builds/113659934#L177

The original PostgreSQL init script allows to have multiple instances running (the new cluster is created on a different port) but Travis seems to be overriding it with a custom one which does not have this behavior:
https://travis-ci.org/zenitraM/test-travis/builds/113663547#L178

**Comment by BanzaiMan** [comment]
I see. Perhaps we can stop Postgres in the APT addon if any of the package names contains `postgresql`.

**Comment by BanzaiMan** [comment]
I'll look at a potential fix some time today. Sorry for the delay.

**Comment by rochoa** [comment]
@BanzaiMan Thanks a lot for your help and understanding, and obviously also for the fix :+1: !

**Comment by jfinkels** [comment]
Does this mean I need to restart PostgreSQL, for example by adding it to "services", after requesting a different version in "addons"? For example:

    addons:
      apt:
        packages:
          - postgresql-9.5

    services:
      - postgresql

I'm having trouble getting [my tests][1] to use the non-default version of PostgreSQL provided by Travis and I'm wondering if this is the problem (I don't think so, but I'm double checking).

[1]: https://travis-ci.org/jfinkels/flask-restless/builds/116327104

**Comment by BanzaiMan** [comment]
@jfinkels 9.5 is not yet supported. See #4264.

**Comment by jfinkels** [comment]
The question still stands for 9.4. Do I need to manually restart the PostgreSQL server and/or do I need to add `postgresql` to `services`?

**Comment by BanzaiMan** [comment]
@jfinkels That is documented in https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version.

**Comment by stephenfin** [comment]
This issue appears to have recurred for me at least, using PostgreSQL 11.

https://travis-ci.org/getpatchwork/patchwork/jobs/446606222

I see the services getting stopped [1](https://travis-ci.org/getpatchwork/patchwork/jobs/446606222#L425):

```
$ sudo service postgresql stop
 * Stopping PostgreSQL 9.2 database server        * Stopping PostgreSQL 9.3 database server        * Stopping PostgreSQL 9.4 database server        * Stopping PostgreSQL 9.5 database server        * Stopping PostgreSQL 9.6 database server
```

...the new package getting installed [2](https://travis-ci.org/getpatchwork/patchwork/jobs/446606222#L428):

```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install postgresql-11 postgresql-client-11
```

...and then the postgres11 service failing to start [3](https://travis-ci.org/getpatchwork/patchwork/jobs/446606222#L525):

```
Refused to start PostgreSQL 11, because PostgreSQL 9.2 is currently running! You should first stop 9.2 instance...
invoke-rc.d: initscript postgresql, action "start" failed.
dpkg: error processing package postgresql-11 (--configure):
 subprocess installed post-installation script returned error exit status 13
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
Errors were encountered while processing:
 postgresql-11
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The issues appears to be because something in the installation step is resulting in the postgres-9.2 service being restarted [4](https://travis-ci.org/getpatchwork/patchwork/jobs/446606222#L494):

```
 * Starting PostgreSQL 9.2 database server       Setting up postgresql-client-11 (11.0-1.pgdg14.04+2) .
```

This is possibly a packaging issue but I'm not sure.

**Comment by jnizet** [comment]
I confirm: installing postgresql 11 by following the instructions of the documentation doesn't work.

**Comment by jhpratt** [comment]
@BanzaiMan I'm unable to get _any_ version other than the default to properly start up. The examples in the documentation (though using newer versions) fail. Is it necessary to start it by hand?

Additionally, the default version is 9.6. The only reason I'm even running into this is because PostgreSQL is complaining that jsonb isn't a type (it was added in 9.4).

Any ideas?

**Comment by BanzaiMan** [comment]
@jnizet @jhpratt Could you open a new topic at https://travis-ci.community/ with relevant build log URLs? Thanks.

**Comment by jhpratt** [comment]
@BanzaiMan [Posted](https://travis-ci.community/t/postgresql-type-jsonb-does-not-exist/2418).

**Comment by harpojaeger** [comment]
To add to this: I'm trying to run Postgres 11.1, and I have the same error as above. The install succeeds, but Travis then complains that 9.2 is still running. In the logs, you can see that Travis stops Postgres 9.3-9.6 before running `apt`, but not 9.2. Is there some way I can modify that behavior? Do I need to kill 9.2 by hand before running `apt`?

```
Installing APT Packages
PostgreSQL package is detected. Stopping postgresql service. See https://github.com/travis-ci/travis-ci/issues/5737 for more information.
$ sudo service postgresql stop
 * Stopping PostgreSQL 9.3 database server        * Stopping PostgreSQL 9.4 database server        * Stopping PostgreSQL 9.5 database server        * Stopping PostgreSQL 9.6 database server       9.06s
$ travis_apt_get_update
```
