### ISSUE TITLE
Julia nightly osx build fail

### ISSUE THREAD

**Issue by Dawny33** [travis-ci/travis-ci#5740]
@tkelman @ninjin @staticfloat

The julia nightly build on osx is throwing the following error: `The command "hdiutil mount -readonly -mountpoint juliamnt julia.dmg" failed and exited with 1 during .`

Url of the build run: https://travis-ci.org/Dawny33/Algorithms.jl/jobs/113445533

**Comment by tkelman** [comment]
It seems to have been long enough since we had a successful nightly build of osx that the existing nightly has been removed. I don't think we have an easy way of fixing this until we get a new mac buildbot that is capable of building master without timing out.

**Comment by Dawny33** [comment]
@tkelman Thank you for updating! Is this issue a duplicate of any issue before?  (If yes, then I can mark it as a dup, and close it. However, I haven't found any!)

**Comment by tkelman** [comment]
No, this is new as of today. Maybe yesterday at the earliest.

**Comment by tkelman** [comment]
This should now be fixed. Please confirm.

**Comment by Dawny33** [comment]
@tkelman Wonderful!  Build successful.  Ref: https://travis-ci.org/Dawny33/Algorithms.jl/jobs/114036014
