### ISSUE TITLE
failed to install postgresql-9.4

### ISSUE THREAD

**Issue by maksym** [travis-ci/travis-ci#5741]
dpkg: error processing postgresql-9.4 (--configure):
 subprocess installed post-installation script returned error exit status 13
dpkg: dependency problems prevent configuration of postgresql-contrib-9.4:
 postgresql-contrib-9.4 depends on postgresql-9.4 (= 9.4.6-1.pgdg12.4+1); however:
  Package postgresql-9.4 is not configured yet.
dpkg: error processing postgresql-contrib-9.4 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of postgresql-9.4-plv8:
 postgresql-9.4-plv8 depends on postgresql-9.4; however:
  Package postgresql-9.4 is not configured yet.
dpkg: error processing postgresql-9.4-plv8 (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because the error message indicates its a followup error from a previous failure.
Errors were encountered while processing:
 postgresql-9.4
 postgresql-contrib-9.4
 postgresql-9.4-plv8

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate/variant of #5737.
