### ISSUE TITLE
missing script: jshint?

### ISSUE THREAD

**Issue by NullVoxPopuli** [travis-ci/travis-ci#5742]
build: https://travis-ci.org/NullVoxPopuli/aeonvera-ui/builds/113668251

not sure what's going on here.

this is a node_js project.

here is my travis.yml https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/.travis.yml

**Comment by etkirsch** [comment]
:+1:

**Comment by NullVoxPopuli** [comment]
Be sure to double check your copy-paste scripts....

I had     

`"test": "npm run jscs && npm run jshint && ember test"`

granted, this is still an issue as I specify to `npm install -g jshint`, but to get my build at least working, I can remove the jshint part of the command.

**Comment by BanzaiMan** [comment]
Can this be closed?
