### ISSUE TITLE
Travis doesn't respect lint.xml for android build

### ISSUE THREAD

**Issue by letientai299** [travis-ci/travis-ci#5746]
I got this [failed build](https://travis-ci.org/letientai299/android-barebone/builds/113838605) on Travis. But the same command work without any problem locally.
I also try `gradle lint`, `gradle lintRelease` on my local, lint found no issue.

**Update**
I have removed  the `lint.xml`, put the configurations into `lintOptions` in the `build.gradle`. 
But Travis also ignores that. Please see the [commit changes](https://github.com/letientai299/android-barebone/compare/468f3efce9df...4bfdb57a55ff) and here the [failed build](https://travis-ci.org/letientai299/android-barebone/builds/113842122).

**Comment by letientai299** [comment]
**Update**
I have removed  the `lint.xml`, put the configurations into `lintOptions` in the `build.gradle`. 
But Travis also ignores that. Please see the [commit changes](https://github.com/letientai299/android-barebone/compare/468f3efce9df...4bfdb57a55ff) and here the [failed build](https://travis-ci.org/letientai299/android-barebone/builds/113842122).

**Comment by BanzaiMan** [comment]
What tool is supposed to discover this file?

**Comment by letientai299** [comment]
I think the plugin `com.android.tools.build:gradle:2.0.0-beta6` should be, and it does the job locally.

**Comment by BanzaiMan** [comment]
Could you try running the build locally? https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

**Comment by letientai299** [comment]
Thanks for guide. I've never used docker before, and currently, but I'll try that when I have time.
About this issue, I end up put `lintOptions { abortOnError false }` into `build.gradle`. I'll still leave this open in case someone faces the same issue.
Thank you, anyway.

**Comment by BanzaiMan** [comment]
This is your project settings, correct? I don't think there is much for us to do here.

Closing.
