### ISSUE TITLE
Problem with Julia Nightly on Mac OS

### ISSUE THREAD

**Issue by lruthotto** [travis-ci/travis-ci#5748]
Hi @tkelman @ninjin and @staticfloat!

I have a problem testing a PR on the latest julia nightly for Mac OS. All other tests worked, so I assume there is some small problem with travis. Please find the full log here:

https://travis-ci.org/lruthotto/ParSpMatVec.jl/jobs/113743093 

Thanks,
Lars

**Comment by ninjin** [comment]
Dupe of #5740 and can be closed.  Apparently the build bots are having [a bit of a hiccup](https://github.com/travis-ci/travis-ci/issues/5740#issuecomment-192112588), hopefully this will be fixed over the next few days.
