### ISSUE TITLE
Build stucked at created for quite some time

### ISSUE THREAD

**Issue by yangarbiter** [travis-ci/travis-ci#5749]
The build queue for our project: https://travis-ci.org/ntucllab/libact/builds

The last build finished is about three days ago, and other jobs are just stucked at created.
We have tried to cancel and restart some of the build but it doesn't work. Does anyone have any suggestions on how to solve this problem?

Thanks.

**Comment by BanzaiMan** [comment]
Sorry about the issue. I canceled some of the old builds (https://travis-ci.org/ntucllab/libact/builds/113319568 https://travis-ci.org/ntucllab/libact/builds/113322686 https://travis-ci.org/ntucllab/libact/builds/113319554). I see the builds moving now.
