### ISSUE TITLE
Start postgresql with `ssl` enabled

### ISSUE THREAD

**Issue by jwilm** [travis-ci/travis-ci#5753]
Postgres has an `ssl` configuration option that, when enabled, allows connecting over TLS _in addition_ to supporting plaintext connections. There is no reason to have this disabled, and having it disabled breaks applications which expect TLS connections.

[Postgres SSL docs](http://www.postgresql.org/docs/9.1/static/ssl-tcp.html)

**Comment by BanzaiMan** [comment]
Does enabling SSL break tests explicitly expecting non-SSL connexions?

**Comment by jwilm** [comment]
Enabling ssl does not break applications relying on cleartext communication. As long as the only change is `ssl = on`, it just expands capability.

There is a `pg_hba.conf` mode that denies non ssl connections (hostssl): http://www.postgresql.org/docs/9.4/static/auth-pg-hba-conf.html

As long as that's not set, everything should be ok!

**Comment by BanzaiMan** [comment]
Thanks for the info. I'll take a look.

**Comment by jwilm** [comment]
@BanzaiMan thanks!

**Comment by BanzaiMan** [comment]
Hmm. This is weird… The PR above solves the problem, but the configuration should be `ssl = true` for our image (at least since September 2013): https://github.com/travis-ci/travis-cookbooks/blame/df6408a2d81b4554f85b9238f3caa1136586e575/cookbooks/postgresql/attributes/default.rb#L9 I am not sure why it is not effective right now.

**Comment by BanzaiMan** [comment]
@meatballhat Could you take a look, when you have a chance, and ensure that this is OK for the next build image provisioning? Thanks.

**Comment by BanzaiMan** [comment]
The SSL is enabled on GCE, but currently not on the container images.

**Comment by meatballhat** [comment]
@BanzaiMan I can't find any evidence that `ssl` should be anything other than `true` 😐 .  More details in https://github.com/travis-ci/packer-templates/issues/256 comment.

**Comment by BanzaiMan** [comment]
I ran tests again, w/o the `travis-build` fix above: https://travis-ci.org/BanzaiMan/travis_production_test/builds/177770491 and I don't see it.

I'm closing this optimistically.

@jwilm, if you still see the problem, please include the build log URL to show how it's failing.

Thanks.
