### ISSUE TITLE
MariaDB add-on broken on GCE infrastructure

### ISSUE THREAD

**Issue by erikrose** [travis-ci/travis-ci#5759]
About 3 days ago, installs of the MariaDB add-on started hanging—but only on GCE infra. It seems to me that the apt-get command that installs mariadb should include `-y` (though it certainly works fine on the containerized infra, perhaps due to details of the environment). The earliest failure we can find is https://travis-ci.org/letsencrypt/letsencrypt/builds/113554374. We can't see anything on our side that should have triggered it. Did anything change on yours?

A reduced example:
* [Hung job](https://travis-ci.org/letsencrypt/letsencrypt/builds/114376298)
* [Mostly-reduced travis.yml file](https://github.com/erikrose/letsencrypt/blob/c10a70ca334cba46c1ba016494815fe32bcb326b/.travis.yml)

**Comment by BanzaiMan** [comment]
Thanks for reporting. This was fixed by https://github.com/travis-ci/travis-build/pull/667. I've deployed it a couple of minutes ago.
