### ISSUE TITLE
Firefox install on OS X is failing

### ISSUE THREAD

**Issue by marco-c** [travis-ci/travis-ci#5760]
```Bash
export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-latest&lang=en-US&os=osx'
wget -O /tmp/firefox-latest.tar.bz2 $FIREFOX_SOURCE_URL
```

The file at https://download.mozilla.org/?product=firefox-latest&lang=en-US&os=osx is a DMG.

**Comment by BanzaiMan** [comment]
Do note that we do not officially support Firefox addon on the Mac.

https://docs.travis-ci.com/user/firefox/

> Our 64-bit Linux VMs include a recent version of Firefox, currently 31.0esr.

**Comment by BanzaiMan** [comment]
Docs update is still pending, but I'm going to close this.
