### ISSUE TITLE
mono NUnit runner crashes with SIGSEGV

### ISSUE THREAD

**Issue by ngeor** [travis-ci/travis-ci#5761]
Hello,

after a seemingly unrelated commit, my project never builds successfully. It's a mono project (C#) with nunit for unit tests. nunit actually runs the unit tests, as seen in the logs, but after that somehow it crashes with SIGSEGV and reports an exit code of 134.

Last successful build: https://travis-ci.org/ngeor/GoogleDriveOfflineBackup/builds/113461371
First failed build: https://travis-ci.org/ngeor/GoogleDriveOfflineBackup/builds/113743832

The command "mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./GoogleDriveOfflineBackup.Tests/bin/Release/GoogleDriveOfflineBackup.Tests.dll" exited with 134.

**Comment by BanzaiMan** [comment]
cc @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
I can reproduce the crash with Mono 4.2.2 on Ubuntu. I don't see it with the latest preview of the next stable Mono release that is available in the alpha channel right now (add `mono: alpha` in your .travis.yml). As it's unlikely that we'll be fixing issues in Mono 4.2 anymore, I'd suggest you use that until stable Mono 4.4 becomes available.

**Comment by ngeor** [comment]
Thanks! I added mono: alpha which seems to pull mono 4.3.2 and then my build turns green!

**Comment by ngeor** [comment]
This is not an issue anymore.
