### ISSUE TITLE
Conflict in .yml files while merging

### ISSUE THREAD

**Issue by rameshthoomu** [travis-ci/travis-ci#5763]
Every developer has to have a different copy of .travis.yml file in their forked repo. When developer made a pull request on Master repository, his.travis.yml will be copied in to the master repository. How do we avoid conflict with the .travis.yml on master ?

I am expecting both .travis.yml files should be there own repositories instead of allowing for conflicts. Please let me know how to achieve this. Thanks in advance!!

**Comment by BanzaiMan** [comment]
If any file (not just `.travis.yml`) diverges on a git repository, the conflict must be resolved before they can be merged.If these conflicts cannot (or should not) be resolved, maybe they do not belong to the same repository.
