### ISSUE TITLE
Docker cache being incorrectly invalidated on Travis

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#5764]
We are running into a problem where the cache is incorrectly getting invalidated by docker on Travis CI. As we use the exact same version of Docker in our deployment VM and are not running into this issue there, we think there is something peculiar going on in the Travis build. For example, we have rebuilt this [commit](https://github.com/jupyter/docker-stacks/commit/457c3edf4b0aaa64b135dd62f445c06bfad24eaa) and deployed new images to Docker Hub that are tagged with the [same git sha and also tagged latest](https://hub.docker.com/r/jupyter/minimal-notebook/tags/). These get repulled on the Travis CI VM [each time](https://github.com/jupyter/docker-stacks/blob/master/.travis.yml#L8) and then are rebuilt [each time](https://github.com/jupyter/docker-stacks/blob/master/.travis.yml#L11). However, even though nothing has changed in the images for that commit, we are still seeing a build failure due to a [`COPY`](https://travis-ci.org/jupyter/docker-stacks/builds/114592634#L254-L256) busting the cache. The file that busts the cache was [last changed](https://github.com/jupyter/docker-stacks/commits/master/minimal-notebook/start-notebook.sh) in December. So, we are struggling to understand what on Travis CI is causing the cache to bust here. Would it be possible for us to inspect a VM so we could understand what is going wrong here?

**Comment by BanzaiMan** [comment]
We destroy the VM that ran your tests after the job has completed. There is no cache for your Docker builds.

We are looking at ways to make this a little better, but we have no ETA.

**Comment by jakirkham** [comment]
> We destroy the VM that ran your tests after the job has completed.

I understand. Would it be possible for me to restart the build and then get access to the VM.

> There is no cache for your Docker builds.

By cache, I am not referring to Travis CI's cache. I am referring to Docker's build cache.

> We are looking at ways to make this a little better, but we have no ETA.

Thanks.

**Comment by BanzaiMan** [comment]
After the build, VMs are terminated. There is no way to preserve it.

I understand that you meant the Docker cache, and there is no cache for it, because the VMs are not preserved. (Even if it is, it is not practical to ensure that your repo's next build is going to use it.)

**Comment by jakirkham** [comment]
> After the build, VMs are terminated. There is no way to preserve it.

So, under what conditions can one get access to the VM? I have seen people do this before with Travis. Is it just not possible under the GCE infrastructure? Even a few minutes with the VM could really help with this problem.

> I understand that you meant the Docker cache, and there is no cache for it, because the VMs are not preserved. (Even if it is, it is not practical to ensure that your repo's next build is going to use it.)

So, we are pulling down the last images built from Docker Hub before we build and we are enabling the docker builds to use cache. Unless there is a delta between the repo when images were last built for Docker Hub and the repo on Travis CI, all of the results are actually cached. We have verified that we see this behavior when building on our VM (even with a completely fresh docker install). Also, if you look at lines prior to the ones indicated, you can see that on Travis CI docker is going from cache. All I am trying to understand here is how a file that has not changed in months (last build was in the last day or two) would bust the cache.

**Comment by BanzaiMan** [comment]
> So, under what conditions can one get access to the VM?

There is something exciting in the works for this. :-)

> I have seen people do this before with Travis.

We have provided users with debug VMs from time to time, that is true.

> Is it just not possible under the GCE infrastructure? Even a few minutes with the VM could really help with this problem.

Correct. But, as I said above, there is something exciting we are working on for that.

As for the cache being bust, I am not familiar enough with Docker's inner workings to comment.

**Comment by willingc** [comment]
@BanzaiMan I'm wondering if it would be possible for us to get access to a debug VM, even for a brief time period, so that @jakirkham and @parente could track down some issues for Project Jupyter which provides underlying tools and libraries for scientific computing and data science. Please let us know if this is possible or if there is someone else we could ask :sunny:

I'm looking forward to hearing more about the exciting new project you are working on. Hope it's going well :smile:

**Comment by jakirkham** [comment]
Also, would be interested in hearing what you have in the works.

Another good solution would be a Vagrantfile or similar if you are using something like this for your Docker builds.

Basically if the file/directory has changed content (not timestamp) since the build, the cache will be invalidated.

It is a bit strange in this case as we know the file (demonstrated by computing sha256 checksums on Travis CI and locally) has not changed and are unable to reproduce this behavior locally using the exact same version of docker on Ubuntu Trusty (14.04.3).

**Comment by BanzaiMan** [comment]
@willingc If you are interested in access to a debug VM, please email us at support@travis-ci.com.

**Comment by willingc** [comment]
@BanzaiMan Will do :+1: Thanks for the contact.

**Comment by ryan-mf** [comment]
Was this ever resolved? We have the same problem - Any Dockerfile that uses ADD or COPY, invalidates the cache related to that file (and any commands that reference that file in the rest of the steps in the Dockerfile), even though we download the current latest images first in the before steps and tell Docker to use those images as cache source when building, and these particular files haven't been changed.

Other steps get properly cached - apt-get install and the like - it's just ADD and COPY steps that cache locally just fine, but get invalidated in Travis.

The reason this impacts us is because we're building Python containers and installing plugins with "pip install" using a requirements.txt that we copy into the container in the preceding step. The cache isn't used for copying the unchanged requirements.txt, so then the next step, `pip install -r requirements.txt` also skips cache. Fixing this would greatly shrink our build & test times upwards of 50%

**Comment by parente** [comment]
@ryan-mf We never did figure out what was causing the cache invalidation, even after ssh'ing into the debug VM and looking at various docker logs and configuration settings. That said, it was nearly 2 years and many docker versions ago, so the situation may be different now.

**Comment by marnen** [comment]
It is still happening. See the builds for https://travis-ci.org/marnen/contraq, where copying an unchanged Gemfile invalidates the Docker layer cache.

**Comment by emaG3m** [comment]
did this ever get resolved??? I'm running into the same issue.

**Comment by jakirkham** [comment]
Not that I'm aware of

**Comment by emaG3m** [comment]
leave me wondering how anyone is using docker with travis?? ¯\_(ツ)_/¯ COPY seems pretty integral..at least for our process..
