### ISSUE TITLE
Repositories not showing up on new account for .com

### ISSUE THREAD

**Issue by Omegastick** [travis-ci/travis-ci#5765]
My repositories aren't showing up on my new account on Travis-ci.com (they still show up on .org) and syncing updates the 'last synced' indicator but doesn't make the repositories show up.

![image](https://cloud.githubusercontent.com/assets/17452111/13620550/9374e0e4-e588-11e5-8ebe-07fe5fb1d127.png)

**Comment by BanzaiMan** [comment]
Do you have any private repository?

**Comment by BanzaiMan** [comment]
Closing due to lack of response.
