### ISSUE TITLE
Contributors able to Cancel master repo Builds from Travis Home page

### ISSUE THREAD

**Issue by rameshthoomu** [travis-ci/travis-ci#5766]
I have made a pull request on `Master Repo`. I could see people who all forked that repository can see the pull request build process in their Travis home page and they even can cancel the builds which is not acceptable.

I am using Public repository. When i made a pull request and travis is building the code changes on the build how come Travis is allowing contributor to cancel the build from his Travis home page by accessing the master repo.

Could you please let me know how to restrict this?

**Comment by BanzaiMan** [comment]
When you open a PR, there will be 2 builds running: one for the push build for the branch that you opened the PR *from*, and the PR build for the base branch (of the base repository) you opened the PR *for*.

The latter, in essence, is a build that belongs to the original repository. The maintainers of that repository, being its owner, is able to cancel the PR build if they wish for whatever reason.

We closely mirror what GitHub has for permissions, and this is how it works.

I'm curious to know why you think this is a bad idea.

**Comment by rameshthoomu** [comment]
The issue i am facing here is, any contributor can cancel the PR from their Travis Home Page. I made a pull Request on Master Repo, some one who is a contributor (not the owner of the repo) can cancel the build from their Travis Home page.

Any specific git hub permission i have to look to restrict this.

**Comment by BanzaiMan** [comment]
Why is the maintainer of the repo against which you opened a PR canceling the build?

**Comment by rameshthoomu** [comment]
Maintainer also should not cancel the build which is in control of the maintainer but in my case `Read` access is there on my public repo and using travis-ci.org.. My question here is When some `x person` send a pull request on Master Branch of the Original repository, I don't want some `Y person` to cancel the build from his Travis Home Page. Right now, the "X" mark is enabled for `Y person` and it's allowing him to cancel the build.

Please suggest me how to resolve this.

**Comment by BanzaiMan** [comment]
If the person Y has write access to the repository, they can cancel the build. I am not sure what ground they have for canceling the build, but that restriction is not available at this time. This is due to our closely mimicking GitHub's scopes.

Read access is not sufficient to cancel builds. If you see the "X" on the build, that's because you have write access to the repository in question. If you go to a running job for a different repo, say https://travis-ci.org/rails/rails/builds, you should not see that.

**Comment by rameshthoomu** [comment]
I have found something on this issue... If `Y` person is part of the Organization then he is able to cancel  (Not intentionally) the build triggered by some one in the organization. Can we restrict this by chance?

No one should be able to cancel the build other than Commiter of the request. Any Thoughts?

**Comment by BanzaiMan** [comment]
Sorry, but that is not possible.

**Comment by BanzaiMan** [comment]
The PR build belongs to the repository against which it was opened, not to the user who opened it or committed the last commit. There is an issue which seeks to allow the user to cancel the PR build, but the restriction *by* the author of the PR doesn't seem a good idea.
