### ISSUE TITLE
ubuntu:trusty image is outdated when pulled inside Travis-CI jobs

### ISSUE THREAD

**Issue by nsuke** [travis-ci/travis-ci#5767]
We use dockerhub as an external docker image cache, i.e., call `docker pull <our pre-built image>` then call `docker build <path inside our repo for the same image>`.
That way, we can rebuild our image (for build env) only when the new commits modified the Dockerfile.

This worked pretty well until this week, but currently, base image mismatch causes full-rebuild every time.
I checked our dockerhub build log and the ubuntu image had following ID.

    Step 1 : FROM ubuntu:trusty
    ---> 07c86167cdc4

It matches with what I see in my local `docker images` output right after `docker pull ubuntu:trusty`, so I believe our pre-built image has latest base image.

In [recent Travis job](https://travis-ci.org/apache/thrift/jobs/114730824#L356)s, ubuntu:trusty always has an ID that is different from the latest,

    Status: Downloaded newer image for ubuntu:trusty
     ---> 56063ad57855

This is causing our build to take total 7 hours instead of 4 hours.

I suspect docker on Travis job is configured to use an alternative docker repository or a proxy.
In that case, much more frequent sync for images would be nice.

**Comment by BanzaiMan** [comment]
Hello, sorry for the troubles. I am not sure what is causing this issue, but we can provide you with access to a live build VM, so that you can troubleshoot this issue more interactively. Please email support@travis-ci.com.

Let us continue discussion there.
