### ISSUE TITLE
INFO and ERRO messages on Travis Log file

### ISSUE THREAD

**Issue by rameshthoomu** [travis-ci/travis-ci#5768]
I am getting so many INFO and ERRO log files on my Travis Log file. I am not specifying anything in my .travis.yml file regarding the Log but still it's printing. Could you please help me how to turnoff these log messages.

Sample LOG FILE:

INFO[0995] Trust graph fetch failed: Get https://dvjy3tqbc323p.cloudfront.net/trust/official.json: dial tcp: lookup dvjy3tqbc323p.cloudfront.net: No address associated with hostname 

INFO[0996] POST /containers/dev-vp1-bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c/stop?t=0 

ERRO[0996] Handler for POST /containers/{name:.*}/stop returned error: no such id: dev-vp1-bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c 

ERRO[0996] HTTP Error                                    err=no such id: dev-vp1-bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c statusCode=404

INFO[0996] POST /containers/dev-vp1-bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c/kill

**Comment by BanzaiMan** [comment]
This is how your tools are printing to the logs. Please consult the tools' documentation, and reduce verbosity if you wish to not have these printed.

**Comment by rameshthoomu** [comment]
@BanzaiMan -- I am giving the mentioned command but it's saying too few arguments 

gcloud --verbosity critical   Could you please help me.

**Comment by BanzaiMan** [comment]
https://cloud.google.com/sdk/gcloud/reference/ says the default is `warning`, but your log shows it is logging `info`. Are you sure this is the tool that's writing these?

**Comment by rameshthoomu** [comment]
I am not sure. Could you please help me.

**Comment by rameshthoomu** [comment]
I didn't find any specific command to control this kind of information. Please help me.. this is killing my time.

**Comment by BanzaiMan** [comment]
@rameshthoomu I can emphasize your frustration, but there is not much information to go on with in this ticket. Do you have a build log URL and the relevant code to show this problem?

**Comment by rameshthoomu** [comment]
@BanzaiMan 
[Log file.txt](https://github.com/travis-ci/travis-ci/files/185328/Log.file.txt)
My Environment is: Executing Go language and Python scripts using Travis CI environment. Travis is connecting to the Docker environment. Below is the Config file:

 #Go langugage
language: go
sudo: required
dist: trusty
 #white list
branches:
 only:
  -master
 services:
 -docker
go:
 -1.6

Starting Docker Daemon:
sudo docker daemon -H tcp://0.0.0.0:$port -H unix:///var/run/docker.sock &.. We are getting INFO and ERRO messages while executing Go and Python scripts. It will be really good if you can provide me the command to restrict these messages.

**Comment by rameshbabu79** [comment]
Issue got resolved.. While starting docker deamon at the end of the command I have given  > /devnul 2&1.. Thank you.
