### ISSUE TITLE
pypandoc seemingly not present at upload

### ISSUE THREAD

**Issue by theherk** [travis-ci/travis-ci#5769]
I hate to open an issue for this, but I don't know how to resolve it on my own. I am referencing a [pinkopy build](https://travis-ci.org/theherk/pinkopy/builds/114970799).

If I upload this to PyPI locally with pypandoc installed, I get proper rst README. So I added pypandoc to install in travis.yml. I would expect this to work, but I don't know from which environment the upload to PyPI takes place. Is it one of the build environment or another separate one that doesn't have installed items? Nevertheless, when it is uploaded to PyPI via the pypi deploy provider in the build job, pypandoc doesn't seem to be present. Why is that?

Is there a log file I can access about the upload.

**Comment by BanzaiMan** [comment]
If you re trying to deploy some build artifacts, you need to skip cleanup. See https://docs.travis-ci.com/user/deployment/pypi#Releasing-build-artifacts

**Comment by BanzaiMan** [comment]
Closing due to lack of response.
