### ISSUE TITLE
[wishlist] Display the output of `ps fuxa` when terminating a job

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#5771]
When one runs a highly concurrent set of tests and receives the dreaded `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself` it is extremely hard to figure out what exactly hung. A simple diagnostic of _here is what is running on the box before we pull the plug_ would be very useful to aid in investigations.

**Comment by BanzaiMan** [comment]
Closing as a duplicate of #4221.
