### ISSUE TITLE
Accessing encrypted env vars in a build triggered through the API

### ISSUE THREAD

**Issue by gideonthomas** [travis-ci/travis-ci#5773]
Hello!

I need to trigger a Travis build for my project through the Travis API. My request looks something like:
```bash
body='{
  "request": {
    "branch": "master",
    "config": {
      "env": {
        "global": ["UPDATE_STRINGS=true"]
      },
      "script": "bash ./scripts/pull-new-strings.sh"
    }
  }
}'

curl -s -X POST \
        -H "Content-Type: application/json" \
        -H "Accept: application/json" \
        -H "Travis-API-Version: 3" \
        -H "Authorization: token <travis_api_token>" \
        -d "$body" \
        https://api.travis-ci.org/repo/<repo_slug>/requests
``` 

This works and triggers the build fine in the other repo and runs the script `pull-new-strings.sh`. In that script however, I need to access an encrypted variable (a github token) which is set in the yaml file of that repo. When I try to however, the variable comes up empty i.e. does not exist.

I suspect that this is because the build that was triggered is considered an "untrusted build" so I do not have any encrypted variables? If this is the case, is there any workaround?

Any help will be appreciated!
Thanks!

**Comment by BanzaiMan** [comment]
Is the secure variable defined in `env.global`? If so, I suspect your payload is overriding the existing configuration. I see why we do this, and also why you expect otherwise.

Could you try moving your setting of `UPDATE_STRINGS=true` to a different phase, for example, `before_script` or rolling it into `script`?

```json
{
  "request": {
    "branch": "master",
    "config": {
      "script": "export UPDATE_STRINGS=true; bash ./scripts/pull-new-strings.sh"
    }
  }
}
```

**Comment by gideonthomas** [comment]
Hmm yeah you're probably right. Since `global` is a list and not a dictionary, it makes sense that you wouldn't merge the lists provided and instead overwrite the value of the key `global`. I guess I was under the false assumption that *everything* (config related) was merged, whereas the docs say that while the config is merged, keys are overridden.

Thanks for the prompt answer! I will try it out in a bit!

**Comment by gideonthomas** [comment]
@BanzaiMan I removed the env config key from my request and it looks like I still can't access my secure variable. In the build, it doesn't seem to be exported.

**Comment by gideonthomas** [comment]
Interesting! Is it safe to add the un-encrypted key to the settings page?

**Comment by gideonthomas** [comment]
I put the unencrypted key in the settings page and tested it out (I can revoke it if it isn't safe).

Awesome! That worked! Thanks for the help!

**Comment by gideonthomas** [comment]
This works now with the suggestion that was provided (Thanks :) ), closing!

**Comment by abid71** [comment]
Encrypted env vars from setting page would return as null when tried to access through APIs i.e. https://api.travis-ci.org/repo/repo_id/env_vars

Is there any way if we can access encrypted enc var?
