### ISSUE TITLE
HTTP 403 when using Remotes in DESCRIPTION

### ISSUE THREAD

**Issue by dmenne** [travis-ci/travis-ci#5777]
Trying to move to new native R-build on travis-ci:

https://travis-ci.org/dmenne/gastrobase#L1088

Package is on github, and I have added 

Remotes: dmenne/d13cbreath

to DESCRIPTION and to .yml
```
language: r
sudo: false
cache: packages
r-github-packages:
  - dmenne/d13cbreath
```
This results in a 403 error, but I can download the package 

https://api.github.com/repos/dmenne/d13cbreath/zipball/master

mentioned below without problems, even from a browser window that is not logged in. Surprisingly, this seem to be an anonymous download, but I am definitively using a token from github on this build

```
$ Rscript -e 'deps <- devtools::install_deps(dependencies = TRUE);if (!all(deps %in% installed.packages())) { message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'

Downloading GitHub repo dmenne/d13cbreath@master
from URL https://api.github.com/repos/dmenne/d13cbreath/zipball/master
Error in download(dest, src, auth) : Forbidden (HTTP 403).
Calls: <Anonymous> ... remote_download.github_remote -> download -> <Anonymous>
```

**Comment by dmenne** [comment]
I still do not understand why, but problem is gone. Closed.

**Comment by iagomosqueira** [comment]
Some thing to do with github's API limit? Anonymous requests are limited to 600 per hour. I assume many of us have tried to move to the new system and hit that limit.

**Comment by dmenne** [comment]
I had thought of that, but this was definitively not the case because nothing else had been running. I think it is 60 requests per hour.

**Comment by iagomosqueira** [comment]
But wouldn't all those access come from the same range of IPs, travis'? 
Just a wild guess

**Comment by dmenne** [comment]
I agree - but this very attempts after doing nothing on this account for weeks. And earlier, I had done heavy lifting on these pages, and never came even close to the limit - you can query it easily, it was always around 10/60 for the hour.

**Comment by iagomosqueira** [comment]
Thanks for the information. I have moved to using pkgs from a repository in the ghpages branch instead of using install_github to avoid this.

**Comment by zkamvar** [comment]
I'm afraid I'm also getting this error:

https://travis-ci.org/grunwaldlab/poppr/builds/115907290#L1012-L1018

**Comment by dmenne** [comment]
I noted that it works now. What was the required change?

**Comment by zkamvar** [comment]
> I noted that it works now. What was the required change?

TBH, I have no clue. Magic?

If I recall, I had initially gotten the error after I cleared my caches so that I could force travis to update R.
The error cleared up after I had specified different R builds in my YAML:

```
r:
  - release
  - devel
```

HTH
