### ISSUE TITLE
Sorry, it seems like we couldn't find any repositories you have access to on GitHub.

### ISSUE THREAD

**Issue by lioncruise** [travis-ci/travis-ci#5781]
All my repository is public.why couldn't it find any repositories I have access to on GitHub?
By the way,I have joined a public organization apparently.Why there is no organization on my travis CI?

**Comment by craigspara** [comment]
This seems to be a common issue. See issue #5672 for more information. Good luck.

**Comment by MariadeAnton** [comment]
@lioncruise please report at support@travis-ci.com for us to investigate, including these details:

- Your username (i.e. lioncruise)
- Name of the org 
- Name of a repo belonging to the org

Thank you!

**Comment by flipjs** [comment]
I have the same issues as well. Just sent an email to support@travis-ci.com . Thanks.

**Comment by flipjs** [comment]
All solved on my end now. Thanks to Travis Support for syncing it for me.

**Comment by AshishJShukla** [comment]
i am facing same issue what to do?

**Comment by liudih** [comment]
i am facing same issue what to do?
