### ISSUE TITLE
R-devel OS X builds using incorrect version

### ISSUE THREAD

**Issue by PeteHaitch** [travis-ci/travis-ci#5783]
My OS X builds using R-devel are currently using R 3.2.4 instead of R 3.3.0 (and have been for the past ~3 days). Linux builds are unaffected. 

An example can be found at https://travis-ci.org/PeteHaitch/bsseq/builds/115691489. I suspect this is related to a now-resolved error with the OS X nightly R-devel builds that I noticed 3 days ago (https://twitter.com/PeteHaitch/status/707707700000333824) but for which Travis hasn't picked up the latest version. Is there something I can do to resolve this or is it a fix that needs to be made on the Travis end?

CC @craigcitro, @hadley and @jimhester

**Comment by jimhester** [comment]
Only r-latest is available for OS X.  See (https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb#L125). This has always been the case, R-devel had never been supported. OS X with R on Travis is experimental so not all features are available and it is _much_ less tested.

**Comment by PeteHaitch** [comment]
Ah right, thanks, Jim. I hadn't realised this (was trying to mimic behaviour from https://github.com/metacran/r-builder). Happy to be a tester if/when this functionality becomes available.
