### ISSUE TITLE
How to add parameters for `postgresql.conf` file?

### ISSUE THREAD

**Issue by moylop260** [travis-ci/travis-ci#5784]
I have an app that require `logging_collector` param enabled from postgresql.

Then I want add follow configuration:
`echo "logging_collector = on" | sudo tee -a /etc/postgresql/9.*/main/postgresql.conf`

But I had follow error:
`sudo: must be setuid root`
That's is right because I'm using `container-based infrastructure` 
Then I'm trying without `sudo` but `travis` user don't have permission to modify this file.

Then I'm trying modify this param on-fly, but I get follow error:
```bash
travis@d5bb5dae033c:~$ psql postgres -c "SET logging_collector TO ON;"
ERROR:  parameter "logging_collector" cannot be changed without restarting the server
```

Then I'm trying with environment variables but I get follow error:
```bash
travis@d5bb5dae033c:~$ PGOPTIONS="-c logging_collector=on" psql -l
psql: FATAL:  parameter "logging_collector" cannot be changed without restarting the server
```

The question is:
Is posible change or add a parameter to postgresql configuration file?

Thanks in advance.

**Comment by BanzaiMan** [comment]
You can't do that on containers, unfortunately. If you need to restart a service with your own configuration, please use one with the `sudo` capability.

**Comment by moylop260** [comment]
I got it
Thank you
:cry:
