### ISSUE TITLE
Docker image is not appearing on Docker Hub after pushed from Travis CI

### ISSUE THREAD

**Issue by rameshthoomu** [travis-ci/travis-ci#5785]
I pushed the Docker Image to Docker Hub from Travis CI. Below is the log after executing the docker push command in Travis CI but I could not see any Image in my Docker hub.
```
$ docker tag $Image rameshthoomu/openchain-peer:latest
INFO[0872] POST /v1.20/images/a1c7f2006d2c/tag?repo=rameshthoomu%2Fopenchain-peer&tag=latest 
The command "docker tag $Image rameshthoomu/openchain-peer:latest" exited with 0.
46.44s$ docker push rameshthoomu/openchain-peer
INFO[0872] POST /v1.20/images/rameshthoomu/openchain-peer/push?tag= 
The push refers to a repository [docker.io/rameshthoomu/openchain-peer] (len: 1)
INFO[0917] Signed manifest for rameshthoomu/openchain-peer:latest using daemon's key:
```
What could be the issue? Some one please help me why the Image is not appearing in Docker HUB.

**Comment by BanzaiMan** [comment]
@rameshthoomu Sorry to hear about this issue, but this is too little information to help you. Please email us at support@travis-ci.com with pertinent information (repository, build log URL, `.travis.yml` content, etc.).

**Comment by rameshthoomu** [comment]
.travis.yml file:
install:
 - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD &
Script:
 - go test -timeout=20m $(go list github.com/openblockchain/obc-peer/... | grep -v /vendor) > build-result.txt
 - chmod +x deploy.sh
 - sudo ./deploy.sh
 - export IMAGE_NAME="$DOCKER_IMAGE_NAME"
 - echo "Image Name $IMAGE_NAME"
 - docker images | grep "openchain-peer\|obcca"
 #- go test github.com/openblockchain/obc-peer/openchain/container -run=BuildImage_Peer &
 #- go test github.com/openblockchain/obc-peer/openchain/container -run=BuildImage_Obcca &
 - ps -ef | grep obc-peer | grep -v grep | kill -9 `awk '{print $2}'`
 - cd $HOME/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/bddtests/
 - sed -i -e 's/172.17.0.1:4243\b/'"$ip:$port"'/g' $HOME/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/bddtests/compose-defaults.yml
 - behave -n  "chaincode example 02 single peer"
 - Image="$(docker images | grep "^openchain-peer" | grep -v grep | awk '{print $3}')"
 - echo $Image
 - docker tag $Image rameshthoomu/openchain-peer:latest
 - docker push rameshthoomu/openchain-peer

Repository: rameshthoomu/obc-peer

Build Log URL: Posted Above. I could able to build the image but after that when i push it to Docker hub using above commands mentioned in .travis.yml file. I couldn;t see any image file in docker hub.

Pls help me!!

**Comment by rameshbabu79** [comment]
It's working now. I could able to see Docker images in my Docker hub. Thanks

**Comment by BanzaiMan** [comment]
Great to hear! Closing this now.

**Comment by molayodecker** [comment]
@rameshbabu79 What did you do differently?

**Comment by TMMunyai** [comment]
how did you solve this @rameshbabu79
