### ISSUE TITLE
problems sharing settings with pull requests

### ISSUE THREAD

**Issue by calidion** [travis-ci/travis-ci#5787]
when a project with encrypted variables, pull requests can not share them to build successfully, even triggered by the repo owner.

please consider to add the ability for repo owner to run pr with encrypted variables.

thanks.

**Comment by BanzaiMan** [comment]
There is an outstanding issue about secure env vars not working on PRs. I can't locate it right now, but I'll do so when I can.

in the meantime, I'm closing this as a duplicate.

**Comment by calidion** [comment]
Is this feature supported now?

**Comment by BanzaiMan** [comment]
The issue is outstanding.
