### ISSUE TITLE
Matrix dependencies

### ISSUE THREAD

**Issue by glennpratt** [travis-ci/travis-ci#5790]
It would be really nice to run some tests serially to avoid wasting resources on hopeless matrix tests. This is very common on private repos I work on and even some public ones, like bundler:

https://travis-ci.org/bundler/bundler/builds/116207890

There I'm wasting 40 jobs to tell me that I missed a colon. A smoke test that stops the matrix before it fans out into 40 tests seems like it could reduce waste and massive build queues.

Another issue where this would be helpful is when I use Travis Deploy. I add deploy to the matrix, but I'd really only like that to run after all other jobs have passed.

**Comment by glennpratt** [comment]
Hypothetical `.travis.yml`s:
```yaml
matrix:
  include:
    script: smoke_test
    dependents: *
```

```yaml
matrix:
  include:
    deploy:
      # Deploy to GitHub.
      provider: releases
    dependencies: *

**Comment by BanzaiMan** [comment]
Dependent builds have been requested before, and it is certainly on our roadmap; e.g., https://github.com/travis-ci/travis-ci/issues/413, https://github.com/travis-ci/travis-ci/issues/1369

The deployment feature is https://github.com/travis-ci/travis-ci/issues/1548.

**Comment by glennpratt** [comment]
Thanks @BanzaiMan, I couldn't find the terms used in those issue. It seems 'build pipeline' is the term.

**Comment by BanzaiMan** [comment]
Can we close this?

**Comment by glennpratt** [comment]
Well, this is probably a dup of #1369, but that's closed.

**Comment by BanzaiMan** [comment]
Right. We have this on the roadmap. No ETA at the moment.

Closing this as a duplicate.
