### ISSUE TITLE
Restarting failed build of organization no longer possible?

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#5791]
Background: I've noticed today that http://github.com/volkszaehler/volkszaehler.org no longer showed travis build status on pull requests. I've re-enabled travis access to that organization that I'm member of. It is unclear what broke this link in the first place.

Now I see that I can no longer restart failed builds of that organization, e.g. https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/116081582

The "Restart Build" button is gone, also the options menu looks different.

Has anything changed as far as organization handling goes for travis?

**Comment by justinotherguy** [comment]
hm - no, can't think of a reason for this. Not aware of any changes since then.
Doesn't that https://travis-ci.org/volkszaehler/volkszaehler.org/builds say, that the build sometimes fails?

**Comment by andig** [comment]
Looking at the failed build https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/116081582 now, the "Restart" button and menu are back. Seems as if travis has fixed the problem or it was an intermittent issue.
