### ISSUE TITLE
.travis.yml wouldn't trigger build

### ISSUE THREAD

**Issue by hellmage** [travis-ci/travis-ci#5792]
My repo [biu~](https://github.com/hellmage/biu-) is a node project. I added .travis.yml and it didn't work. The repo is enabled in my travis ci profile. I followed the documentation and also made a few tries with .travis.yml from other node.js project, but no luck. Could you give some hint, please? Thanks.

**Comment by BanzaiMan** [comment]
Have you pushed any commit after you enabled Travis? https://travis-ci.org/hellmage/biu-/requests doesn't show any.

**Comment by BanzaiMan** [comment]
There was a commit at 2016-04-19T08:05:28Z https://api.github.com/repos/hellmage/biu-/commits/ae613501e65591455527bdaca55f4539050bca8e

This should have triggered a build, but I do not see any request for it. https://travis-ci.org/hellmage/biu-/requests.

**Comment by hellmage** [comment]
Yeah, that's why I opened this issue. I enabled Travis and pushed lots of commits, but nothing happened.

**Comment by BanzaiMan** [comment]
Could you push another?

**Comment by luyun-aa** [comment]
I've pushed another commit to master.

**Comment by BanzaiMan** [comment]
OK. The hook was somehow corrupt. I manually disabled and re-enabled it. The next push should trigger a build. Please try it.

**Comment by hellmage** [comment]
Thanks man, it works!
