### ISSUE TITLE
docker-compose version update

### ISSUE THREAD

**Issue by sergekukharev** [travis-ci/travis-ci#5793]
Hi,

We are now moving our build system to use docker containers, and we are using docker-compose for that.

We had a problem with environment variables passing from Travis-CI to docker containers and after some hours of debugging, we realised, that environment variable interpolation feature was introduced in docker-compose version 1.5.0 while Travis has 1.4.2 and the most recent is 1.6.0.

We would be grateful if you could update docker-compose in your containers.

**Comment by thyrlian** [comment]
When you have a ***docker-compose.yml*** file, you may want to check its integrity by running `docker-compose config`.

While the `config` command was newly added since version 1.6.0.

And current version on Travis is:
```console
docker-compose -v
docker-compose version: 1.4.2
```

So please help upgrade docker-compose, thanks in advance.

**Comment by BanzaiMan** [comment]
I'm closing this in favor of #6020.
