### ISSUE TITLE
Haxe dev is 5 days old on osx

### ISSUE THREAD

**Issue by ibilon** [travis-ci/travis-ci#5794]
@andyli @waneck @Simn

I'm testing compatibility with haxe 3.3,
changed a line to `#if (haxe_ver >= 3.3) Sys.programPath() #else Sys.executablePath() #end`
works on linux but fails on osx.

I checked the versions, on linux it's `3.3.0 (git build development @ 52d6c60)` (hugh's commit from 3h ago)
but osx is `3.3.0 (git build development @ 7bc28bc)` from 5 days ago before @andyli's commit.

Any reason for the lag or bug?

(edit) link to logs if it helps:
linux: https://travis-ci.org/ianharrigan/hxWidgets/jobs/116584656
osx: https://travis-ci.org/ianharrigan/hxWidgets/jobs/116584656

**Comment by andyli** [comment]
@waneck I guess you'll have to take a look at the build server. @nadako also reported there is a lag for the Windows build.

**Comment by andyli** [comment]
Looks like the build server had trouble to build the commit https://github.com/HaxeFoundation/haxe/commit/396dd2a3a1cc54990fdf14251df42b0cb32e7ea5.
With a recent fix (https://github.com/HaxeFoundation/haxe/commit/19676d159f4e9afb6ea2ffa724289b372e6e66f3) and some luck, it should be able to build again. Not sure if @waneck need to restart the server in some way or it will just pick up the new commits and build again soon.

**Comment by ibilon** [comment]
Doesn't look like it restarted manually.

**Comment by ibilon** [comment]
Fixed, thanks.
