### ISSUE TITLE
php:HHVM won't install when service:docker is used

### ISSUE THREAD

**Issue by jderusse** [travis-ci/travis-ci#5796]
Use HHVM with travis worked fine (see https://travis-ci.org/acmephp/symfony-bundle/jobs/115991517)
But since I activate `service: docker`, when the worker install hvm, the following error occured:
```
hhvm is not pre-installed; installing
bzip2: (stdin) is not a bzip2 file.
```
see the next build (https://travis-ci.org/acmephp/symfony-bundle/jobs/116609973)

**Comment by BanzaiMan** [comment]
As documented in https://docs.travis-ci.com/user/trusty-ci-environment#PHP, we do not yet support PHP on Trusty.

You may want to try the `edge` image by adding

```yaml
group: edge
```

at the top level of your `.travis.yml`.

**Comment by jderusse** [comment]
It fix my issue, thank you
