### ISSUE TITLE
ruby-head always use bundler-1.6.9

### ISSUE THREAD

**Issue by hsbt** [travis-ci/travis-ci#5798]
Recent version of ruby-head environment enforce to use bundler-1.6.9. I invoked `gem update bundler` on `before_install` hook. but travis use old bundler. 

see. https://travis-ci.org/ruby/rake/jobs/116381594

It always failed. Please investigate this situation.

**Comment by robertodecurnex** [comment]
Same thing for Ruby 2.3 and 2.2 right now. Probably related with the new platform? 

I went back to 2.1 in order to make it work.

**Comment by BanzaiMan** [comment]
This is quite curious. We do install a newer version of Bundler during the setup, and it is there when you run `gem list bundler`, yet when you invoke `bundle`, it's an older version.

```sh-session
travis@testing-worker-linux-docker-523030ab-2907-linux-2:~/build/BanzaiMan/travis_staging_test$ gem list bundler

*** LOCAL GEMS ***

bundler (1.11.2, 1.6.9)
bundler-unload (1.0.2)
travis@testing-worker-linux-docker-523030ab-2907-linux-2:~/build/BanzaiMan/travis_staging_test$ bundle --version
Bundler version 1.6.9
```

**Comment by BanzaiMan** [comment]
So, Bundler 1.6.9 is installed in the first component of `$GEM_PATH`, while 1.11.2 is in the second. (https://travis-ci.org/BanzaiMan/travis_production_test/jobs/117834889#L192-L213)

`gem update bundler` appears to find the latest version, and does not perform any installation, but when we execute the `bundle` wrapper, it prefers the version found in the first `$GEM_PATH` component:

```ruby
load Gem.activate_bin_path('bundler', 'bundler', version)
```

I tend to think this is a RubyGems bug.

In the meantime, you can either uninstall Bundler 1.6.9--`gem uninstall bundler -v 1.6.9`--or explicitly install Bundler 1.11.2 (or whatever version that meets your requirement)--`gem install bundler -v 1.11.2`.

**Comment by indirect** [comment]
I believe this is related to the changes around GEM_PATH recently made by @tenderlove and @segiddins?

**Comment by BanzaiMan** [comment]
@indirect @tenderlove @segiddins If you think this is worth reporting to rubygems/rubygems, I can do that.

**Comment by robertodecurnex** [comment]
Just to give a little more feedback. I've recreated multiple scenarios
locally with the  ruby and rubygems versions that are failing on travis
without been able to reproduce the problem.

Also, the same build matrix was working on the old boxes. Seems like it's
related to the way that the new boxes setup/pre-setup things.

**Comment by segiddins** [comment]
If you can give us a script to reproduce the issue, an issue on RubyGems would be awesome

**Comment by drbrain** [comment]
This is a RubyGems bug in master:

```
$ gem i bundler:1.6.9 -i ~/tmp/gems/a
Fetching: bundler-1.6.9.gem (100%)
Successfully installed bundler-1.6.9
1 gem installed
$ gem i bundler:1.11.2 -i ~/tmp/gems/b
Fetching: bundler-1.11.2.gem (100%)
Successfully installed bundler-1.11.2
1 gem installed
$ GEM_HOME=~/tmp/gems/a GEM_PATH=~/tmp/gems/b gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.2
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/erichodel/tmp/gems/a
  - USER INSTALLATION DIRECTORY: /Users/erichodel/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/erichodel/tmp/gems/a/bin
  - SPEC CACHE DIRECTORY: /Users/erichodel/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/erichodel/tmp/gems/a
     - /Users/erichodel/tmp/gems/b
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
     - "install" => "--format-executable --no-user-install"
     - "update" => "--format-executable --no-user-install"
     - "uninstall" => "--format-executable --no-user-install"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/erichodel/bin
     - /usr/local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/local/MacGPG2/bin
$ GEM_HOME=~/tmp/gems/a GEM_PATH=~/tmp/gems/b ~/tmp/gems/a/bin/bundle --version
Bundler version 1.11.2
$ gem env version
2.6.2
$ cd rubygems
/Users/erichodel/Work/git/rubygems
$ RUBYLIB=lib GEM_HOME=~/tmp/gems/a GEM_PATH=~/tmp/gems/b ~/tmp/gems/a/bin/bundle --version
Bundler version 1.6.9
```

**Comment by segiddins** [comment]
@drbrain post that in an issue on RubyGems if you'd like me to patch it tomorrow?

**Comment by robertodecurnex** [comment]
Fixed on rubygems https://github.com/rubygems/rubygems/pull/1566

**Comment by hsbt** [comment]
@BanzaiMan I will merge latest rubygems to ruby-head soon.

**Comment by hsbt** [comment]
merged https://github.com/ruby/ruby/commit/64ce7711c0c428531ae09472c85df85cd3d1b603

**Comment by BanzaiMan** [comment]
@hsbt These have been built successfully on Linux: https://travis-ci.org/travis-ci/travis-rubies/builds/118904476 https://travis-ci.org/travis-ci/travis-rubies/builds/118904488

Could you restart previously failing jobs?

**Comment by hsbt** [comment]
I confirmed to use latest bundler https://travis-ci.org/ruby/rake/jobs/116381594#L166

Thank you!
