### ISSUE TITLE
Cannot use curl from deploy or after_script

### ISSUE THREAD

**Issue by mcalhoun** [travis-ci/travis-ci#5807]
I am trying to get travis to kick of a deployment to our internal staging environment via curl. If I run this command from anyhwere I've tried except the travis environment, it works without an issue, but from within travis I get an error message:

```
Script curl -I "http://ci.mydomain.net:8080/buildByToken/build?job=MyApiStaging&token=MyToken&cause=travis-ci" failed with status 7
```

But from anywhere else:

```
curl -I "http://ci.mydomain.net:8080/buildByToken/build?job=MyApiStaging&token=MyToken&cause=travis-ci"                                                                                                                                                                                
HTTP/1.1 201 Created
X-Content-Type-Options: nosniff
Location: http://ci.mydomain.net:8080/queue/item/67/
Content-Length: 0
Server: Jetty(winstone-2.9)
```

I have tried running the script from a script file as well as "raw" in the YAML as part of both after_success and deploy with the same results. Any ideas?

**Comment by BanzaiMan** [comment]
Do you have access to the server logs? Does `curl -v` (or `-vv` or higher) give you any insight as to why the connexion was refused?

**Comment by mcalhoun** [comment]
So it looks like this was an issue with our infrastructure provider having a misconfiguration with routing. Sorry for the false alarm, this is resolved!
