### ISSUE TITLE
R-devel in 4 weeks prior to new R release points to the future R-devel

### ISSUE THREAD

**Issue by lcolladotor** [travis-ci/travis-ci#5809]
Hi,

I was expecting that `r: devel` (using [`language: r`](https://docs.travis-ci.com/user/languages/r)) would point right now to R 3.3.0 instead of 3.4.0 given that it's the current R-devel and will be released in April this year as shown at https://developer.r-project.org/

> The schedule for 3.3.0 is as follows
> 
> Monday 2016-03-14: START
> Thursday 2016-03-17: GRAND-FEATURE FREEZE (3.3.0 alpha)
> Thursday 2016-03-31: FEATURE FREEZE (3.3.0 beta)
> Thursday 2016-04-07: CODE FREEZE (3.3.0 RC)
> Monday 2016-04-11: PRERELEASE
> Thursday 2016-04-14: RELEASE (3.3.0)

However, it also says `Prerelease source tarballs (and binaries for some platforms) are being made available during the 4 weeks until the release.` which means starting on the week of March 21st (so now). 

So, my assumption was that `r: devel` would keep pointing to R 3.3.0 until April 14th. Is that the intended behavior? 

However with R 3.3.0 being pre-released 4 weeks in advance, I guess that the new R-devel (3.4.0) also starts to get distributed 4 weeks in advance. And that could be fine if the behavior of `r: devel` is to stay in line with the fine details of R release cycles. If this is the intended behavior, maybe adding a small note at https://docs.travis-ci.com/user/languages/r would be good.

I'll switch to specifying the actual R version in my Travis builds for now.

Thanks,
Leo

PS I noticed this because https://travis-ci.org/leekgroup/derfinderPlot/builds/117500745 failed and @jimhester made [me realize](https://twitter.com/the_belal/status/712271855164465152) that the build was running on R 3.4.0. 

As stated on the docs, also @craigcitro and @hadley.

**Comment by lcolladotor** [comment]
Posted the complementary issue at Bioc-devel https://stat.ethz.ch/pipermail/bioc-devel/2016-March/008875.html

**Comment by lcolladotor** [comment]
Actually, I can't seem to get Travis to point to R 3.3.0

Using:
* `r: 3.3.0` as in https://github.com/leekgroup/derfinderPlot/commit/c905e9b9aada81e2ff5092a594d1619affaed939 leads to https://travis-ci.org/leekgroup/derfinderPlot/builds/117726139#L377
* `r: release` as in https://github.com/leekgroup/derfinderPlot/commit/bd4bbc102e3a6fd7611531af953f05f0bc6ed5c5 installs R 3.2.3 as shown at https://travis-ci.org/leekgroup/derfinderPlot/builds/117726929#L475
* `r: 3.3` as in https://github.com/leekgroup/derfinderPlot/commit/908eb935d87dd6bc83a204c2ef98ab45b0d7f81b also fails to install R as shown at https://travis-ci.org/leekgroup/derfinderPlot/builds/117727892#L377

So, how I can get R Travis to use R version 3.3.0?

**Comment by jimhester** [comment]
R-devel on travis always tracks SVN trunk (https://svn.r-project.org/R/trunk/). The other R versions are created based on SVN tags https://svn.r-project.org/R/tags/. The 3.3.0 tag won't be released until April 14th.

There is a 3.3 branch https://svn.r-project.org/R/branches/R-3-3-branch/ so I could have a build based on that, but it would have to be updated manually as needed.

IMHO this seems like a Bioconductor BiocInstaller issue, I think it should support installing with _both_ R 3.3 and 3.4 at least until the 14th. What R release are you supposed to be using during this period?

**Comment by lcolladotor** [comment]
Thanks for your thoughts Jim! 

I understand why `r: release` would point to R 3.2.3 and I see why supporting R 3.3.0 does not seem ideal (anything manual is not ideal), even during this period of time.

Lets see what is the response from Bioconductor.

**Comment by mtmorgan** [comment]
Bioconductor packages in devel are / should be building against R-3-3-branch. Technically the R-devel trunk (a.k.a 3.4.0) won't be used by Bioconductor for another 6 months (R's yearly versus Bioc's 6-month release cycle). In some sense trying to use R-devel for the next six months should cause an error rather than message, but it might be straight-forward for a new installation to use bioc-devel.

**Comment by jimhester** [comment]
@lcolladotor R-3.3.0 should now be available by using `r: 3.3.0` (built using R-3-3-branch).

I am not sure if there is anything else to be done on the Travis side to make this situation easier for developers. I could maybe make R version aliases for `bioc-devel` and `bioc-release` that would point to the appropriate R versions for that Bioconducotr release cycle, would that be useful?

**Comment by lcolladotor** [comment]
Hi Jim,

The aliases `bioc-devel` and `bioc-release` would be useful. Without them I'd have to change the R version every 6 months, which is just a minor commit and not a big problem at all. So, those aliases would be like the cherry on the cake.

Martin (@mtmorgan), from ` but it might be straight-forward for a new installation to use bioc-devel` am I interpreting correctly that you will consider changing the behavior of BiocInstaller? Although with Jim's `r: 3.3.0` manual support it's not immediately necessary. 

I see things working properly with `r: 3.3.0` https://github.com/leekgroup/derfinderPlot/commit/a034a4edc369b4fb98fe11fad804372c87e93033 https://travis-ci.org/leekgroup/derfinderPlot/builds/117797830

Best,
Leo

**Comment by mtmorgan** [comment]
yes, source()ing biocLite from R-devel will now install BiocInstaller to use bioc-devel. Should be live now.

**Comment by lcolladotor** [comment]
Awesome Martin! 

I'm here just to verify that it works. See https://github.com/leekgroup/derfinderHelper/commit/a076339fa1e0d44a8ab4260689c371d384732e2e and the build report: uses R 3.4.0 https://travis-ci.org/leekgroup/derfinderHelper/builds/117801152#L475 and does use Bioc-devel (version 3.3) https://travis-ci.org/leekgroup/derfinderHelper/builds/117801152#L576. This is using BiocInstaller version 1.21.3 (https://travis-ci.org/leekgroup/derfinderHelper#L491) versus 1.20.1 (https://travis-ci.org/leekgroup/derfinderPlot/builds/117500745#L493).

**Comment by lcolladotor** [comment]
Actually, that might have been the cache packages working. I see that you fixed this issue with BiocInstaller version 1.21.4.

![screen shot 2016-03-22 at 4 15 02 pm](https://cloud.githubusercontent.com/assets/2288213/13966538/4d5c7f1a-f049-11e5-9899-5b035f3b6b75.png)
Taken from http://bioconductor.org/developers/svnlog/

Currently, https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/BiocInstaller/DESCRIPTION reads:

```
Package: BiocInstaller
Title: Install/Update Bioconductor, CRAN, and github Packages
Description: This package is used to install and update Bioconductor,
    CRAN, and (some) github packages.
Version: 1.21.4
Author: Dan Tenenbaum and Biocore Team
Maintainer: Bioconductor Package Maintainer <maintainer@bioconductor.org>
biocViews: Infrastructure
Depends: R (>= 3.3.0)
Suggests: devtools, RUnit, BiocGenerics
License: Artistic-2.0
```

**Comment by mtmorgan** [comment]
Not sure if you're having problems, looking for clarification, or otherwise, but all the action actually occurs when BiocInstaller is itself installed. It's installed via https://bioconductor.org/biocLite.R, which in turn is created (outside user control) from the trunk/madman/Rpacks/BiocInstaller/inst/script/biocLite.R (i.e., the script in the devel version of the package).

Previously biocLite.R would install BiocInstaller from the devel repo only if R's version was exactly 3.3.0. Now it installs from the devel repo when the version is >= 3.3.0. Once the devel version is installed, all subsequent uses of biocLite() get the devel version of the package.

The script at https://bioconductor.org/biocLite.R is updated every 20 minutes or so, independent of the version of BiocInstaller available in the public repo (via biocLite.R).

**Comment by lcolladotor** [comment]
Hi,

Sorry, I'm not having any more problems. I was just trying to test `BiocInstaller` but your comment has clarified how it works.

Cheers,
Leo

**Comment by kasperdanielhansen** [comment]
I agree with Leonardo that it would be great to have a way to just specific Bioc-devel and then things would get handled automatically.  As people (might) start using Travis for their development in Bioc, you would help a lot of people if it just works.

Going forward, besides switching R version, you also need to run `useDevel(TRUE)` after sourcing `biocLite`, when development happens against a stable version of R (which it does every 6 months).

**Comment by jimhester** [comment]
https://github.com/travis-ci/travis-build/pull/683 adds the aliases. It will run `BiocInstaller::useDevel()` as appropriate for the proper branch so you can test against devel with `r: bioc-devel` and release with `r: bioc-release`

In the future we will need to update the versions as needed in https://github.com/travis-ci/travis-build.

**Comment by lcolladotor** [comment]
I see that https://github.com/travis-ci/travis-build/pull/683 was merged today and it's all working properly now with `r: bioc-devel`.

Merging https://github.com/travis-ci/docs-travis-ci-com/pull/529 is the only piece missing.
