### ISSUE TITLE
docker: unrecognized service

### ISSUE THREAD

**Issue by MarcusSiegmund** [travis-ci/travis-ci#5812]
Hello, I am trying to get docker running with Travis.
However not even the sample from the docu will work and report docker as 'unrecognized service'

$ sudo service docker start
docker: unrecognized service

**.travis.yml**
`
sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t carlad/sinatra .
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
  - bundle exec rake test
`

In case it matters, we are using the **Enterprise** version of Travis.
Are there any limitations or current issues?

At the end I want to use Java as language as seen below, but since the sample above does not work,
I do not know how to continue here.

sudo: required

**intended .travis.yml**
`
dist: trusty
group: edge

services:
  - docker

language: java

....
`

**Comment by BanzaiMan** [comment]
Hello! For Travis Enterprise support, please send email to enterprise@travis-ci.com. Thank you!

**Comment by BanzaiMan** [comment]
Closing this in favor of support via email.
