### ISSUE TITLE
conda does not install properly

### ISSUE THREAD

**Issue by SteveDoyle2** [travis-ci/travis-ci#5814]
Per, the following link, conda environments (a convenient program for installing Python dependencies) should be set up as follows:
http://conda.pydata.org/docs/travis.html

Unfortunately, conda is unable to install properly

    Downloading conda-4.0.5.tar.gz (125kB)
      100% |████████████████████████████████| 126kB 4.1MB/s 
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 20, in <module>
        File "/tmp/pip-build-Bop31K/conda/setup.py", line 30, in <module>
          import auxlib  # a build-time dependency only
      ImportError: No module named auxlib

The full build log can be seen here:  https://travis-ci.org/SteveDoyle2/pyNastran/jobs/118091369
The full yaml file can be seen here:  https://github.com/SteveDoyle2/pyNastran/blob/master/.travis.yml

I've tried using a different conda build
 - https://repo.continuum.io/miniconda/Miniconda2-3.19.0-Linux-x86_64.sh (old)
 - https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh (new)

found from https://repo.continuum.io/miniconda/
but am unable to affect the build message at all.  Version 4.0.5 is still being downloaded.

It's not clear to me if this is related to the migration discussed in:
https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

but this began for me on 2016-3-4 as opposed to 2016-3-12, so I don't think so.

Any ideas what I'm doing wrong?

**Comment by decibel** [comment]
I'm getting the same error, trying to install conda on OS X. pip and python were installed via macports. A manual `sudo -H pip install auxlib` fixed it.

**Comment by SteveDoyle2** [comment]
Thank you for your suggestion.  That worked!

**Comment by ssbarnea** [comment]
Why is this bug closed because clearly this exists and `pip install conda` fails to install `auxlib`. Workaround is to manually install it before with `pip install auxlib` but that's clearly not normal.

I found this on OS X with `pip 8.1.1 from /usr/local/lib/python3.5/site-packages (python 3.5)`
