### ISSUE TITLE
Package dependency problem -- Relax or tcltk

### ISSUE THREAD

**Issue by droglenc** [travis-ci/travis-ci#5817]
I am again trying to use travis-ci with my R package but it is failing.  This time it appears that the problem is related to the relax package, but more likely its dependency on the tcltk package.  Here is [my YAML file](https://github.com/droglenc/FSA/blob/master/.travis.yml) and the [raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/118384205/log.txt) from the last build attempt.  I have tried the YAML without the `install.packages()` code and received the same error (I was attempting to follow the advice in #5756).

Any advice @craigcitro, @hadley, @jimhester?

**Comment by droglenc** [comment]
I added the following to my YAML as the offending packages are only in `Suggests`.  This at least allowed the Travis-CI build to not fail.

```
env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE
```

**Comment by droglenc** [comment]
I reorganized my package so that it does not rely on the `relax` package.  I could then remove `_R_CHECK_FORCE_SUGGESTS_=FALSE` item in the yaml.

**Comment by achubaty** [comment]
I know this issue is closed, but I solved the tcltk problem by making sure it was installed via apt. In my (containerized) `.travis.yml` I added:

```
addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev
```
