### ISSUE TITLE
Build periodically

### ISSUE THREAD

**Issue by jpmckinney** [travis-ci/travis-ci#582]
## Why build periodically?

In most cases, if the code hasn't changed, there is no reason to build. However, in some cases, something external to the code may cause it to fail. For example, if I [scrape](http://en.wikipedia.org/wiki/Web_scraping) information from a website, that scraper code will fail if the website undergoes a redesign. I want to know about that failure, so that I can fix the code.

In #travis, @svenfuchs suggested that I open a ticket and ping @rkh about this new feature.

In terms of implementation, it was mentioned:

    svenfuchs: i'd feel we'd look for an external solution that pings our listener just like github does but maybe konstantin has other ideas, too

I propose the interval be set in `.travis.yml` in either crontab format (`0 0 * * 0`) or words like `daily`, `weekly`, etc.

**Comment by solarce** [comment]
@coderanger has built a super useful service to enable nightly builds of repositories on travis-ci.org.

You can check it out at https://nightli.es/.

**Comment by roidrage** [comment]
With nightlies available, I'm closing this issue for the time being, as we have no immediate plans to support this kind of feature.

**Comment by MariadeAnton** [comment]
Cron Jobs are now available: https://docs.travis-ci.com/user/cron-jobs/ per request.
