### ISSUE TITLE
Disable service

### ISSUE THREAD

**Issue by cchantep** [travis-ci/travis-ci#5824]
Is there any way to disable a builtin service in container? I would like to disable the obselete MongoDB 2.4.

**Comment by BanzaiMan** [comment]
MongoDB should not be running by default. What problems are you seeing?

**Comment by cchantep** [comment]
It's running, with an obslete version (which is in itself an issue), and it prevent running a new version on the usual port.

**Comment by BanzaiMan** [comment]
Please point to the build log URL that shows this problem.

**Comment by BanzaiMan** [comment]
Closing due to lack of information.
