### ISSUE TITLE
Can't upgrade cocoapods to beta version

### ISSUE THREAD

**Issue by theyonibomber** [travis-ci/travis-ci#5827]
Running

    before_install:
    - gem install cocoapods --pre

succeeds, but it seems `pod install` is still running 0.39.0

I saw that issue #4715 was closed because user didn't need to upgrade anymore, but it seems like it's still relevant.

**Comment by BanzaiMan** [comment]
I wonder if this is a variation of https://github.com/travis-ci/travis-ci/issues/5798. Could you try uninstalling `cocoapods` before installing a newer version?

**Comment by theyonibomber** [comment]
Yep, adding
   - gem uninstall cocoapods -a

Solved the issue.
