### ISSUE TITLE
Bundler not looking for local source gem

### ISSUE THREAD

**Issue by emyl** [travis-ci/travis-ci#5829]
Not sure if I'm doing something wrong, but starting from the latest build it looks that Bundler is trying to install my gem from rubygems instead of using local source:

```
An error occurred while installing vagrant-triggers (0.5.3.dev), and Bundler cannot continue.
Make sure that `gem install vagrant-triggers -v '0.5.3.dev'` succeeds before bundling.
```
In this case it fails because the version '0.5.3.dev' is not yet released...

https://travis-ci.org/emyl/vagrant-triggers/builds/119007809

Thanks for any advice :smiley:

**Comment by BanzaiMan** [comment]
I am not sure what's going on here, but I noticed one thing. Your last successful build on your repo was 6 months ago, pointing to version `0.5.2` locally. Can bundler (version 1.5.3 in particular) refer to locally sourced gem with pre-releases?

**Comment by emyl** [comment]
Found the problem, it was a bundler bug. Upgrading to a recent version fixed the issue.

Thanks for your support 😉
