### ISSUE TITLE
rvm build failing due to bundler bug

### ISSUE THREAD

**Issue by TikiTDO** [travis-ci/travis-ci#5831]
[This build](https://travis-ci.org/mojombo/god/builds/119153899) had quite a few failures while trying to bundle required gems.

This is a bug in bundler that was fixed in [this commit](https://github.com/bundler/bundler/commit/a0c90cd53a436b1856c8bcfbdaa44997870e4488), which was included in version 1.7.15, and version 1.8.8. The travis-ci build above used version 1.7.6, and 1.8.4, which resulted in build failure.

Additionally, the older versions of ruby in that build seem to be using a newer version of rake that they can support. Not sure what's up with that.

**Comment by BanzaiMan** [comment]
Looks like some of the Ruby runtimes are indeed using older Bundler versions. This is not going to change until the next build environment update (no ETA at this time), so please update Bundler in `before_install`.

I do not think this statement is true:

> Additionally, the older versions of ruby in that build seem to be using a newer version of rake that they can support. Not sure what's up with that.

To the best of my knowledge, Bundler supports all the older versions of Ruby going back to 1.8.7 with the current 1.x versions. See, for example: https://rubygems.org/gems/bundler/versions/1.11.1:

> REQUIRED RUBY VERSION:
> `>= 1.8.7`

**Comment by bogdanRada** [comment]
I am having some issues with Bundler on Travis also,

This is what i am running
```ruby
 BUNDLE_GEMFILE=/home/travis/build/bogdanRada/sprockets-less/gemfiles/sprockets_2.2.gemfile bundle exec rake spec

```
and this is what i get
```ruby
bundler: failed to load command: rake (/home/travis/build/bogdanRada/sprockets-less/vendor/bundle/ruby/2.0.0/bin/rake)
Gem::LoadError: You have already activated bundler 1.7.6, but your Gemfile requires bundler 1.13.1. Prepending `bundle exec` to your command may solve this.
  /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.13.1/lib/bundler/runtime.rb:40:in `block in setup'
  /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.13.1/lib/bundler/runtime.rb:25:in `map'
  /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.13.1/lib/bundler/runtime.rb:25:in `setup'
  /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.13.1/lib/bundler.rb:99:in `setup'
  /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/bundler-1.13.1/lib/bundler/setup.rb:10:in `<top (required)>'
  /home/travis/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /home/travis/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

I am not sure how to get rid of that old version of bundler.

This is my Travis YML

```yaml
sudo: false
cache: bundler
language: ruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem uninstall -aIx bundler
  - gem install bundler
  - gem update bundler
rvm:
- 2.0.0
- 2.1.5
- 2.2.2
- 2.2.3
- 2.3.1
env:
 - RAILS_ENV=test RACK_ENV=test
notifications:
  email: false

```
Any help on this would be much appreciated.
