### ISSUE TITLE
name resolution yum.puppetlabs.com

### ISSUE THREAD

**Issue by jordiprats** [travis-ci/travis-ci#5832]
Hi,
I've several jobs failing because it is unable to install puppetlabs repo:

```
centos-5-x64 14:05:05$ rpm --replacepkgs -ivh http://yum.puppetlabs.com/puppetlabs-release-el-5.noarch.rpm 

  error:   skipping http://yum.puppetlabs.com/puppetlabs-release-el-5.noarch.rpm - transfer failed - Unknown or unexpected error

  Retrieving http://yum.puppetlabs.com/puppetlabs-release-el-5.noarch.rpm
```

I've tried to install it manually using docker_image_commands, what I get is:

```
  http://yum.puppetlabs.com/el/5/dependencies/x86_64/repodata/repomd.xml: [Errno 4] IOError: <urlopen error (-3, 'Temporary failure in name resolution')>
```

It's quite weird because it only happens on CentOS 5. Running it on my local machine it works thus it makes no sense to me

Can this be caused by some issue on your side?

thanls,

**Comment by BanzaiMan** [comment]
We don't support CentOS 5. How are you running into this problem?

**Comment by jordiprats** [comment]
We are using docker containers:

https://github.com/jordiprats/eyp-apache/blob/master/.travis.yml

Anyway, it does not really matter if it's a centos or a ubuntu, it's a name resolution problem:

```
[Errno 4] IOError: <urlopen error (-3, 'Temporary failure in name resolution')>
```

**Comment by BanzaiMan** [comment]
Isn't that a DNS configuration problem with the Docker image, then?

Take a look at https://travis-ci.org/BanzaiMan/travis_production_test/builds/120578727#L331

This build pulls the `ubuntu` image (`docker pull ubuntu`), installs `curl` and runs `curl -I yum.puppetlabs.com`. The name resolution succeeds, and `curl` reports status 200.

**Comment by BanzaiMan** [comment]
Hmm. I did the same with CentOS 5 image (`docker pull centos:5`), but it also succeeds. https://travis-ci.org/BanzaiMan/travis_production_test/builds/120580750#L320

**Comment by jordiprats** [comment]
This is one of the jobs that are failing:

https://travis-ci.org/AtlasIT-AM/eyp-postfix/jobs/119763658

In this job I'm installing it manually (that's how I got the name resolution error):

https://travis-ci.org/jordiprats/eyp-apache/jobs/119257391

It is failing just for CentOS 5, so I'm not really sure what's going on here

**Comment by BanzaiMan** [comment]
Email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.
