### ISSUE TITLE
Provide the mac worker with an icu enabled boost package

### ISSUE THREAD

**Issue by lenormf** [travis-ci/travis-ci#5840]
Hi,

I've been trying to compile [a small test project](https://github.com/lenormf/test/blob/master/.travis.yml) that uses `boost` with `icu` in a mac worker, to no avail. 

As you can see on the build log [here](http://codepad.org/Z0uoYV9j), `boost` is already installed before the compilation phase starts, and a call `brew options` before the package upgrade will say that the package has been compiled with `icu` support. Since I needed the latest version of the package installed, I used `brew upgrade` to have the latest version of the package, and I thought that would be it.

Unfortunately, my code doesn't compile, the error being that the `boost` library that's used during the linking phase does not have any `icu` symbol. Another call to `brew options` after the package upgrade showed that the package supposedly did have `icu` support enabled as well, but I checked the bottle that is being downloaded and installed by `brew` (at `https://homebrew.bintray.com/bottles/boost-1.60.0_1.mavericks.bottle.tar.gz`), and it turned out that not only there are no `icu` symbols in the libraries, but statically linked libs are also being installed (which contradicst `brew`'s `--without-static` flag returned on a call to `brew options` after the package was upgraded). I tried using the `--force` flag, thinking the already existing files on the system were not being properly overwritten, but that didn't work.

Mac's old version of `ld` also only accepts the `-v` flag to have some sort of debug output, which really is of no help (on earlier versions, I could have used `--verbose` or even `--trace` to check whether I'm just trying to link old libs instead of the new ones with `icu` support).

Finally, I can't ignore all the things above and just do a `brew reinstall` to force recompilation of `boost` with the exact options that I need, because `travis` kills the process after 10 minutes. I think this whole thing is `homebrew`'s fault (the mixup with the options is really weird unless I actually try to link against the wrong libs), but in the meantime I'm stuck with a build that will not work (compilation does work on a proper mac system, and on the linux workers).

Can mac workers have an `icu` enabled install of `boost` by default ? Is that already the case, in which case what libraries am I supposed to link against ?

Thanks.

**EDIT**: I just checked the `INSTALL_RECEIPT.json` file shipped with the `boost` bottle, it contained the following:
```
    "unused_options": [
        "--c++11",
        "--without-static",
        "--with-icu4c",
        "--without-single",
        "--with-mpi",
        "--universal"
    ],
```

So I guess `travis` will have to provide a recompiled `boost` lib by default to allow my project to compile.

**Comment by lenormf** [comment]
Hi,

Could I have an update or an ETA on this please ?

Thanks.

**Comment by solarce** [comment]
@lenormf at the moment we are depending on homebrew to provide that kinds of packages and don't have plans to make customized ones for things like `boost`

I can recommend one of two things:
1. You use https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received to do the `brew reinstall` and see if your whole build can still complete in a timely manner
2. Setup a separate CI build that makes a copy of `boost` with `icu`, that homebrew can install and publish it via your own custom tap, https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/brew-tap.md, then you could use the tap to install it during your primary CI builds
