### ISSUE TITLE
sapling-team/base-extend-backbone Build status unknown and link unreachable

### ISSUE THREAD

**Issue by icepy** [travis-ci/travis-ci#5842]
Hi 

i created repo [base-extend-backbone](https://github.com/sapling-team/base-extend-backbone),add`.travis.yml` and sync repo ,but build status remains unknown .i search [#3996](https://github.com/travis-ci/travis-ci/issues/3996) find to help info , result is Build status remains unknown all the time though,Could you take a look?

travis url : [https://travis-ci.org/sapling-team/base-extend-backbone](https://travis-ci.org/sapling-team/base-extend-backbone)

**Comment by BanzaiMan** [comment]
Your `.travis.yml` file is invalid, and we cannot configure builds.

https://raw.githubusercontent.com/sapling-team/base-extend-backbone/057b85cce93f1c4dd69de76441a185b514a0d762/.travis.yml

Notice the first 2 lines do not have space after colons. Pleas ensure that the file is valid.

**Comment by icepy** [comment]
thank you ~
