### ISSUE TITLE
Android tools preview versions unavailable

### ISSUE THREAD

**Issue by mkjensen** [travis-ci/travis-ci#5843]
`tools-preview`, `platform-tools-preview`, and `build-tools-24.0.0-preview` do not seem to work for android/components.

For `platform-tools-preview` an old version 23.1 rc1 is installed instead of the expected 24 rc1.

For the others, errors occur:

```
Error: Ignoring unknown package filter 'tools-preview'
Warning: The package filter removed all packages. There is nothing to install.
         Please consider trying to update again without a package filter.

Error: Ignoring unknown package filter 'build-tools-24.0.0-preview'
Warning: The package filter removed all packages. There is nothing to install.
         Please consider trying to update again without a package filter.
```

.travis.yml file: https://github.com/mkjensen/danish-media-license/blob/12d5611841446ff6aa492b27a2a11c1f6d517b44/.travis.yml

Build log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/119848463/log.txt

From `android list sdk --all --extended` locally:
```
----------
id: 2 or "tools-preview"
     Type: Tool
     Desc: Android SDK Tools, revision 25.1 rc1
----------
id: 4 or "platform-tools-preview"
     Type: PlatformTool
     Desc: Android SDK Platform-tools, revision 24 rc1
----------
id: 5 or "build-tools-24.0.0-preview"
     Type: BuildTool
     Desc: Android SDK Build-tools, revision 24 rc2
----------
```

**Comment by ardock** [comment]
# [Current build system information](https://github.com/travis-ci/travis-cookbooks/tree/a68419e)
# [Preinstalled sdk tools r24.0.2](https://github.com/travis-ci/travis-cookbooks/blob/a68419ebe0ce92876a70534cd145ddd931d0feee/ci_environment/android-sdk/attributes/default.rb)
```
wget http://dl.google.com/android/android-sdk_r24.0.2-linux.tgz
tar xvfz android-sdk_r24.0.2-linux.tgz
cd android-sdk-linux/tools
```

# Check the suggested and missing components after each installation
There are dependencies like tools depending on a specific platform-tools version:

> Skipping 'Android SDK Tools, revision 24.4.1';
> it depends on 'Android SDK Platform-tools, revision 23.1 rc1' which was not installed.

`./android list sdk --extended |more`

# Install the missing/suggested components
./android update sdk --no-ui --all --filter platform-tools-preview
./android update sdk --no-ui --all --filter tools
cd ../tools
./android update sdk --no-ui --all --filter android-N
./android update sdk --no-ui --all --filter tools
cd ../tools
./android update sdk --no-ui --all --filter platform-tools-preview
./android update sdk --no-ui --all --filter build-tools-24.0.0-preview

**Comment by mkjensen** [comment]
I see, thank you. Could be part of the components configuration but this works.
