### ISSUE TITLE
[precise-gce] cannot install *httpie* package anymore

### ISSUE THREAD

**Issue by gbour** [travis-ci/travis-ci#5844]
when using the new image, httpie package seems to be missing:

```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install httpie elinks
E: Unable to locate package httpie

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install httpie elinks" failed and exited with 100 during .
```

here's the build: https://travis-ci.org/gbour/letsencrypt-erlang/jobs/119855419

**Comment by BanzaiMan** [comment]
Seems like the package index update was incomplete. https://travis-ci.org/gbour/letsencrypt-erlang/jobs/119855419#L174 Since other jobs in this build ran successfully, I believe it is a transient problem. Please restart it.

**Comment by gbour** [comment]
Thanks @BanzaiMan 

This build is using new precise image while others are using trusty:
`instance: testing-gce-e278696c-60b3-405c-8a38-5bf26d6d2723:travis-ci-erlang-precise-1450223375`
vs
`instance: testing-gce-a40c9606-0724-42d0-9597-28cf933cd545:travis-ci-mega-trusty-1445287562`

I assume instance selection is done randomly as part of your migration process

**Comment by BanzaiMan** [comment]
OK. Then I tend to think httpie is not available for Precise. http://packages.ubuntu.com/precise/httpie

Did it work before?

**Comment by gbour** [comment]
You are right, httpie is not packaged in precise
Thanks
