### ISSUE TITLE
Build fails on containers if the resulting build script is too long

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5845]
If `.travis.yml` yields a Bash script that is too long, the build will fail with:

```
Using worker: worker-linux-docker-db0c005f.prod.travis-ci.org:travis-linux-5
/bin/bash: Argument list too long
chmod: cannot access `/home/travis/build.sh': No such file or directory
bash: /home/travis/build.sh: No such file or directory
```

The identical build will run fine on GCE.

See [this `.travis.yml`](https://github.com/BanzaiMan/travis_production_test/blob/a7ec81f69c9a9df1405f9de442d6e4d7403ba447/.travis.yml) and its build: https://travis-ci.org/BanzaiMan/travis_production_test/builds/119930121.

**Comment by ljharb** [comment]
Still a bug, I think.

**Comment by ljharb** [comment]
Still a bug.

**Comment by BanzaiMan** [comment]
@ljharb Remind me… What is your use case in having an extremely long script? The way we communicate with our VMs, I am afraid this may not be something we can overcome (easily, at least).

**Comment by ljharb** [comment]
Any time there's a failure, the more information I can log, the better. In the case of nvm, i have my tests using `+x` - it's often necessary to log everything in the case when the last, say, 10 instructions are infinitely looping, and I need to know what triggered the cycle.

**Comment by BanzaiMan** [comment]
We will consolidate our execution environment to GCE, so this will soon be moot. https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
