### ISSUE TITLE
Docker Container logs are not appearing on Travis Log file

### ISSUE THREAD

**Issue by rameshthoomu** [travis-ci/travis-ci#5846]
I am executing Behave tests from TRAVIS CI and these tests are executing in docker container.. Some times I could see my behave tests are failing and no clue what is causing to failure. 

How to store docker container logs in a file and store that in a remote location to access? Need your help in resolving this. Thanks!!

**Comment by BanzaiMan** [comment]
Try reading the container logs with `docker logs`.

**Comment by rameshthoomu** [comment]
Yes i am using docker logs -f <Container ID> to view the docker container logs but my question is, after completion of my test I could see a failure.. I want to see where that failure happened.. 

Please note I am not running my tests locally and executing from Travis UI. Could you please help me how to store failed scenario **container logs** in a file and export them to any remote machine from Travis.,.,

**Comment by rameshthoomu** [comment]
I am running this command before I execute my behave tests 

```sudo docker daemon -H tcp://0.0.0.0:$port -H unix:///var/run/docker.sock > /dev/null 2>&1 &```

**Comment by BanzaiMan** [comment]
If you need to store build artifacts, you can use [`artifacts`](http://docs.travis-ci.com/user/uploading-artifacts/) or [S3](https://docs.travis-ci.com/user/deployment/s3) to upload the logs to your S3 bucket.

**Comment by rameshthoomu** [comment]
Thanks @BanzaiMan . I could see container logs uploding in S3 bucket but I don't find any option in TRAVIS to send these logs files to developer emails. (We are using Slack and gmail for build notifications). Could you please help me. Thanks!!

**Comment by BanzaiMan** [comment]
You want to include those logs in the notifications? I'm afraid you can't do that. Sorry.

I don't think there is anything left to address on this ticket, so I'm closing it.

**Comment by rameshthoomu** [comment]
Not in notifications.. If there is build failure, i want to send the log files to developers.. Right now, using the mentioned notifications I am sending build result but not the log file. 

When I say build failed, developers are asking for log files. It's very time consuming process to take the files from S3 and send it through an email.. 

Do you have any option?

**Comment by BanzaiMan** [comment]
I see what you are after. Unfortunately, there is no such mechanism exists out of the box.

Perhaps you can be notified of the S3 file upload event (http://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html) and send email notifications.

**Comment by rameshthoomu** [comment]
Thanks @BanzaiMan for the information. I have another requirement in place. I want to send all the logs files to remote machine ex: IBM Bluemix or SoftLayer machine from Travis CI. I didn't find any  documentation to keep application logs in remote machine. (not in S3 or some other cloud). Could you please help me in finding application logs.

**Comment by BanzaiMan** [comment]
Build machines are shut down at the end. You can use [artifacts](https://docs.travis-ci.com/user/uploading-artifacts/) addon to upload such logs. (You might have to share data between the build VM and your Docker container.)

**Comment by rameshthoomu** [comment]
Thanks for quick response. Currently i am uploading logs files "git ls-files -o | tr "\n" ":"" to S3 but the requirement is to upload into Remote machine. The Artifacts link which you have mentioned above is for S3 correct? What you mean share data between build VM and Docker Container? how to do that? Thanks again!!

**Comment by BanzaiMan** [comment]
artifacts will upload files to S3. You might be able to connect to a remote machine directly, but some additional work would b necessary.

For "sharing", I meant the `-v` flag for [`docker run`](https://docs.docker.com/engine/reference/commandline/run/).

**Comment by rameshthoomu** [comment]
@BanzaiMan . I didn't find any option to upload docker files to remote machine other than S3. Could you please give me clear information. I am not interested in Github releases.

**Comment by BanzaiMan** [comment]
Hi, @rameshthoomu I see that you have opened a support ticket. Let us continue there.

**Comment by rameshthoomu** [comment]
Sure. Thank you
