### ISSUE TITLE
git pull is not working from Travis CI

### ISSUE THREAD

**Issue by rameshthoomu** [travis-ci/travis-ci#5847]
I have written git pull command in my shell script which is placed in my remote machine and calling shell script from Travis yml file using CURL command.

I could see, curl command is calling remote machine but git pull command is not executing. .gitconfig file is uptodate with my valid credentials. Pls help me.

**Comment by thedrow** [comment]
Title is misleading. It should be "git pull **isn't** working from Travis CI"...

**Comment by BanzaiMan** [comment]
@rameshthoomu Please give us more information what you are trying to do. If you prefer to inquire about private repositories, please email us at support@travis-ci.com.

**Comment by rameshthoomu** [comment]
@BanzaiMan I am executing curl command from travis-ci.org (Public repo) which calls my shell script included git pull command. When i execute curl command, it's calling the shell script but not executing my git pull command to fetch the latest code from github public repo.

Could you please check this. Will this work from TRAVIS?

**Comment by BanzaiMan** [comment]
@rameshthoomu Please point to a build log URL that shows this problem. Thanks.

**Comment by BanzaiMan** [comment]
Closing due to lack of information.
