### ISSUE TITLE
The command "eval git fetch origin +refs/pull/8/merge:" failed. Retrying, 2 of 3.

### ISSUE THREAD

**Issue by bittner** [travis-ci/travis-ci#5850]
We're getting [all failed build jobs](https://travis-ci.org/behave/behave-django/builds/119961678) since last night caused by:

```
The command "eval git fetch origin +refs/pull/8/merge:" failed. Retrying, 2 of 3.
```

Last night 3/4 of the build jobs still passed successfully, now all jobs are failing after I restarted the build. Is that an issue you are aware of? We can't do anything about it ourselves, can we?

**Comment by BanzaiMan** [comment]
https://github.com/behave/behave-django/pull/8 was merged at 2016-04-01T00:47:07Z (https://api.github.com/repos/behave/behave-django/pulls/8). So we cannot test the PR any longer.

If some of the jobs had passed and not all, I suspect that the PR was merged while the builds were still running.

Restarting a PR build after merging the PR will present this problem.

**Comment by bittner** [comment]
Okay, now I understand. Thank you and sorry for the noise.

What disturbs me though is that the badge now shows a "failing" build for the `master` branch although this reflects the PR only (which only fails because the code is no longer available as Travis expects it to be for a PR).

The badge in our README points to `master`, https://img.shields.io/travis/behave/behave-django/master.svg, shouldn't it reflect the latest commit on `master`? I understand the state of the "merged PR" is expected to be the same. In our very example it is not, though. And I can even trigger a build for `master/HEAD` manually (or can I?).

**Comment by bittner** [comment]
Oh, there was some other build failing ([build 6](https://travis-ci.org/behave/behave-django/builds/119962249)) for an infrastructure issue. I managed to fix this by triggering the affected build job manually.

Now, all is green. Thank you!

**Comment by ashish173** [comment]
One solution here is to trigger a build manually on your base branch from travis's interface. This feature is in experimental feature but this way it picked up the latest code from the base branch and didn't care about the branch which got merged before the build succeeded.

**Comment by lemoustachiste** [comment]
This is a bit of an old issue but I'm facing a similar problem although I have not merged the changes.
I tried opening a new PR but that didn't change the issue.

https://app.travis-ci.com/github/blockchain-certificates/wallet-android/builds/264394568 (https://github.com/blockchain-certificates/wallet-android/pull/68)
https://app.travis-ci.com/github/blockchain-certificates/wallet-android/builds/264394054 (https://github.com/blockchain-certificates/wallet-android/pull/67)

Any help will be appreciated

Thanks

**Comment by lemoustachiste** [comment]
I figured it was likely due to the ubuntu version not being the one I wanted.
