### ISSUE TITLE
AssertionErrors on same build today, which passed yesterday.

### ISSUE THREAD

**Issue by karandesai-96** [travis-ci/travis-ci#5851]
The two Travis logs:

* On Day 0: https://travis-ci.org/tardis-sn/tardis/builds/119843180  
Suddenly builds started failng, so I reverted back two commits to the same commit which passed and did a force push.  
* On Day 1: https://travis-ci.org/tardis-sn/tardis/builds/120237901  
The builds failed, on the changes regarding which it passed some time ago.  
Possible solutions please ?

**Comment by BanzaiMan** [comment]
When previously passing builds start to fail, it is often due to the changes in underlying dependencies. Please review them.

**Comment by karandesai-96** [comment]
Hi, they are AssertionErrors, and my tests pass locally. The failing tests only use one library - `ctypes`, which is python's own as far as I know. Is there a way to debug extensively ? Since `./setup.py test` passes locally, I cannot think of anything right now. Moreover there are other tests which use `ctypes` and they are passing, in the same build.

**Comment by karandesai-96** [comment]
@BanzaiMan Hi, my builds failed because the head of master was updated. Travis automerges before building, which broke my tests. I am closing this issue.
