### ISSUE TITLE
Cannot create .git/logs/refs/stash: Directory nonexistent

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#5854]
I've this [build #120502269](https://travis-ci.org/FX31337/FX-BT-Data-EURUSD-DS/jobs/120502269) which has some issues, click on `Preparing deploy` section and you'll see:

> /usr/lib/git-core/git-stash: 186: /usr/lib/git-core/git-stash: cannot create /home/travis/build/FX31337/FX-BT-Data-EURUSD-DS/.git/logs/refs/stash: Directory nonexistent

```
Preparing deploy
Logged in as EA31337 Tester
Deploying to repo: FX31337/FX-BT-Data-EURUSD-DS
Current tag is: 2015
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
Ignoring path FX-BT-Scripts/
/usr/lib/git-core/git-stash: 186: /usr/lib/git-core/git-stash: cannot create /home/travis/build/FX31337/FX-BT-Data-EURUSD-DS/.git/logs/refs/stash: Directory nonexistent
```

Then:

```
Deploying application
EURUSD1.hst.gz already exists, skipping.
...
No stash found.
```
This is when building tag release. Here is my [travis file](https://github.com/FX31337/FX-BT-Data-EURUSD-DS/blob/51db1348dfd888655c66acb3ec0babb16a4d24c5/.travis.yml). There are two issues for me:

- _cannot create /.git/logs/refs/stash: Directory nonexistent_, then _No stash found._
- _File already exists, skipping_

This happened when I overridden the tag with different commit and pushed with force to re-run the build (probably not relevant).

The first one I don't know why it's happening. No stash is probably the result of it. Then I'm not sure if it's related, but I would like to replace my old files, but it's skipping them, because they exist?

Related: #2960, npm/npm/issues/7914

Another build (not mine): [#40767391](https://travis-ci.org/prismicio/ruby-kit/jobs/40767391)

**Comment by BanzaiMan** [comment]
Regarding the second issue: by default, we do not overwrite existing files. (I think this is a recent update described in https://github.com/travis-ci/dpl#github-releases but not in https://docs.travis-ci.com/user/deployment/releases).

**Comment by BanzaiMan** [comment]
For the first, could you try adding `skip_cleanup: true`? https://github.com/travis-ci/travis-ci/issues/1648#issuecomment-44917013

**Comment by kenorb** [comment]
The `skip_cleanup: true` and `overwrite: true` options worked, thank you. This suppress the warning.

It's still unclear why this error is happening as per your [comment](https://github.com/travis-ci/travis-ci/issues/1648#issuecomment-47457584). Not sure if there is already bug for it.

**Comment by BanzaiMan** [comment]
Thanks for the update. Let us close this one.
