### ISSUE TITLE
[WISHLIST] PostgreSQL non durability configuration for faster builds 

### ISSUE THREAD

**Issue by moylop260** [travis-ci/travis-ci#5858]
There is a faster configuration for postgresql:
http://www.postgresql.org/docs/current/static/non-durability.html

IMHO this is a ideal configuration for a CI build or dev environment.

Is there posible have this configuration in a future with docker based builds?

**Comment by moylop260** [comment]
FYI I'm using the following configuration:
```bash
echo """
fsync=off
full_page_writes=off
checkpoint_timeout=45min
synchronous_commit=off
""" | tee -a /etc/postgresql/*/main/postgresql.conf
```

And is working fine and faster

**Comment by ehuelsmann** [comment]
According to https://travis-ci.org/ehuelsmann/LedgerSMB/jobs/305985759#L994 I'd say this has been realised now. (It shows fsync and full_page_writes being off as well as the output directory being placed on RAMFS).
