### ISSUE TITLE
Travis sometimes misses commits/pulls

### ISSUE THREAD

**Issue by MarcoFalke** [travis-ci/travis-ci#5863]
I've seen this multiple times now, where travis was not triggered on a fresh pull or a fresh commit in an existing pull: eg. https://github.com/bitcoin/bitcoin/pull/7817

The commit subject or commit body did _not_ include `[ci skip]`.

Is there any way to isolate the cause of the issue?

**Comment by BanzaiMan** [comment]
@MarcoFalke Sorry for the issue. According to the logs, when we tried to fetch the config for the commit https://github.com/bitcoin/bitcoin/pull/7817/commits/36e467aa2d8740cf2ff3c230352a4192a66d7382, GitHub returned a 404. As a result, there was no build. It is not clear to me why. Could you push another commit to the PR?

**Comment by BanzaiMan** [comment]
Also, is there any other commit you believe we missed?

**Comment by MarcoFalke** [comment]
​Yes, there are also other commits, but I am sure we force pushed fresh
commits over them. Does it help if I look for the pull requests where it
happened?

Just guessing, it was happening about 5 times total in the last two months.

**Comment by BanzaiMan** [comment]
@MarcoFalke Hmm. The history of that PR is not clear to me and I have no idea how to look into it. If you notice it going forward, could you let us know?

**Comment by promag** [comment]
At one time travis wasn't triggered, but now it's fine.

**Comment by SkyzohKey** [comment]
Hey guys, I get the same issue than you. :x 
How am I supposed to fix that ?

https://github.com/RicinApp/Ricin/pull/109

**Comment by MarcoFalke** [comment]
@SkyzohKey I think your issue is different, as travis will *always* fail. Prob due to your change: https://github.com/RicinApp/Ricin/commit/4e6a2911ec21d5cedcf85bae32ccc549dc72a58f

Please try to revert that commit and open another issue if this does not fix it.

**Comment by SkyzohKey** [comment]
@MarcoFalke Why would i always fail ? This is a script to test if the commit message follow the GitCop pattern :x

**Comment by SkyzohKey** [comment]
Issue is still here :x

**Comment by MarcoFalke** [comment]
@BanzaiMan Mind to share the command line on how to fetch the config?

> when we tried to fetch the config for the commit GitHub returned a 404

**Comment by BanzaiMan** [comment]
@MarcoFalke It is an API call via Octokit.

**Comment by MarcoFalke** [comment]
Looks like there's another one: https://github.com/bitcoin/bitcoin/pull/7730#issuecomment-220126690 ( 9a936e3 was not picked up )
