### ISSUE TITLE
Builds generated by matrix: include: do not start

### ISSUE THREAD

**Issue by Flamefire** [travis-ci/travis-ci#5868]
I create a "regular" build matrix to test with gcc and clang in debug and release (= 4 builds) and add some others via matrix.include to test other versions. I do not want to add this to the env-matrix as this would e.g. result in a gcc build with a set clang version, which is obviously superfluous.

However only the regular jobs start. The ones added via matrix.include just gets queued but never executed (never means >= 1h)

The build is here: https://travis-ci.org/ComputationalRadiationPhysics/halt/builds/121151045
The `.travis.yml` is here: https://github.com/ComputationalRadiationPhysics/halt/blob/6e1177d06d17b3964c7d3c1a4eb652d88da158a2/.travis.yml

**Comment by lbergelson** [comment]
I have a very similar issue with linux/mac builds together in a matrix.

**Comment by BanzaiMan** [comment]
Sorry for the delay. This has become stale.

If this is an issue still, please open a new issue.

Thanks.
