### ISSUE TITLE
Clang extra tools OS X & Linux

### ISSUE THREAD

**Issue by tmsblgh** [travis-ci/travis-ci#5878]
I would like to use Clang extra tools but the prebuilt library not contain extra tools
(The building not possible because of building time) 

Is it possible to put it on whitelist?

**Comment by BanzaiMan** [comment]
If it is a package available from llvm.org's APT repository, please follow https://github.com/travis-ci/apt-package-whitelist/#package-approval-process. Otherwise, it is highly unlikely that we support this.
