### ISSUE TITLE
MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=256M" didn't take effect?

### ISSUE THREAD

**Issue by gliptak** [travis-ci/travis-ci#5879]
The ```.travis.yml``` file is at https://github.com/gliptak/hive/commit/ff9b1064ed0acefb250da1c3ab38937967082322

The build logs are at https://travis-ci.org/gliptak/hive/builds/121959093 showing:

```
main:
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hive-exec ---
[INFO] Compiling 2624 source files to /home/travis/build/gliptak/hive/ql/target/classes
The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.sun.tools.javac.util.Name.append(Name.java:88)
	at com.sun.tools.javac.code.Symbol$TypeSymbol.formFullName(Symbol.java:533)
	at com.sun.tools.javac.comp.Resolve.findIdentInPackage(Resolve.java:1219)
```
and 
```
[INFO] Final Memory: 76M/455M
```

**Comment by gliptak** [comment]
https://github.com/travis-ci/travis-ci/issues/5594 https://github.com/travis-ci/travis-ci/issues/5615
I'm trying out ```openjdk7```

**Comment by gliptak** [comment]
same error with ```openjdk7``` https://travis-ci.org/gliptak/hive/builds/121966559

**Comment by gliptak** [comment]
https://github.com/travis-ci/travis-ci/issues/4613

**Comment by BanzaiMan** [comment]
See also #3893.

I'm closing this as a duplicate.
