### ISSUE TITLE
Exceeded the maximum time limit for jobs

### ISSUE THREAD

**Issue by stlankes** [travis-ci/travis-ci#5881]
Hello,

I have a build failure (https://travis-ci.org/RWTH-OS/HermitCore/builds/122014198) and receive the following error message:

"The job exceeded the maximum time limit for jobs, and has been terminated."

Do you any idea, which behavior triggers such an error message.

Thanks!

**Comment by BanzaiMan** [comment]
The build is simply taking too long to finish.

**Comment by stlankes** [comment]
Hm, I thought that we have unlimited build minutes.

**Comment by BanzaiMan** [comment]
Sorry, we do not. You could try splitting the build into smaller parts, or perhaps parallelize your build.

**Comment by stlankes** [comment]
I will try

**Comment by muschellij2** [comment]
What is the exact meaning of "unlimited build minutes" on the [Travis CI Pricing plans](https://travis-ci.com/plans)?
<img width="1071" alt="screen shot 2016-09-01 at 1 48 34 pm" src="https://cloud.githubusercontent.com/assets/1075118/18178052/d0bf77c8-704a-11e6-83e9-5cbe2d4a6b1e.png">

**Comment by BanzaiMan** [comment]
@muschellij2 It means the plan does not suddenly stop working no matter how many minutes you run the jobs. (Each job is limited, but the number or the sum of those jobs is not.)
