### ISSUE TITLE
cache is empty after upload

### ISSUE THREAD

**Issue by kengz** [travis-ci/travis-ci#5884]
The log shows [uploading archive here](https://travis-ci.org/kengz/aiva/jobs/122169964#L4305), and on viewing the [`Caches`](https://travis-ci.org/kengz/aiva/caches) it is empty.

The [.travis.yml](https://github.com/kengz/aiva/blob/aiva-v3/.travis.yml#L50) does specify the caches. Is there a way to debug it?

**Comment by BanzaiMan** [comment]
This build runs on GCE, which does not have caching feature. See https://docs.travis-ci.com/user/caching/.

We are working on that (https://github.com/travis-ci/travis-ci/issues/4011#issuecomment-208056908).

I'm closing this as a duplicate of the issue above.
