### ISSUE TITLE
travis file not found or not parsed

### ISSUE THREAD

**Issue by sebglon** [travis-ci/travis-ci#5885]
I have an error on this https://github.com/docking-tools/register/commit/58431e2

but i don't see way
This commit solved on missing config...

Why???

**Comment by MariadeAnton** [comment]
missing config usually means there's some issue with the _.travis.yml _file

http://lint.travis-ci.org/docking-tools/register could you check that out?

**Comment by sebglon** [comment]
Is it possible to escape ":" on bash script command on _.travis.yml_

**Comment by BanzaiMan** [comment]
See, for example, http://stackoverflow.com/questions/11301650/how-to-escape-indicator-characters-i-e-or-in-yaml

**Comment by sebglon** [comment]
How can i write this:

curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "staging"}' -X POST https://registry.hub.docker.com/u/dockingtools/register/trigger/77a278d7-7ec8-4a35-ac53-8f96c483ce65/

If i escape with simple cote, the command is on error

**Comment by BanzaiMan** [comment]
@sebglon Did you read the SO answer I showed you? There are a few ways to handle this, one is using `|`, another `>`, and also escaping.

Assuming what you have right now is literally what you want to pass to bash, you can write:

```yaml
after_deploy:
- |
  curl -H "Content-Type: application/json" --data '{\"source_type\": \"Tag\", \"source_name\": \"'"$TRAVIS_TAG"'\"}' -X POST https://registry.hub.docker.com/u/dockinools/register/trigger/$DOCKER_HUB_TOKEN/ ;
```

You can use tools such as http://yaml-online-parser.appspot.com/ to check your work.

**Comment by sebglon** [comment]
I have write with your comment
````
after_deploy:
- |
  curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "0.0.1"}' -X POST https://registry.hub.docker.com/u/dockingtools/register/trigger/$DOCKER_HUB_TOKEN/;
````

But now i have not found error on travis log: https://travis-ci.org/docking-tools/register/builds/122444651

I don't understand why

**Comment by BanzaiMan** [comment]
Sorry, but the command failure appears to be coming from the `curl` command itself. Do you know why? I don't use Docker hub, so I can't tell you much more than that.

**Comment by sebglon** [comment]
the command ```curl``` run write on my laptop and on my c9 ide; but not on travis.
I think this is an parser error or travis environment

**Comment by BanzaiMan** [comment]
Does your `$DOCKER_HUB_TOKEN` contain special characters? https://docs.travis-ci.com/user/encryption-keys#Note-on-escaping-certain-symbols

**Comment by sebglon** [comment]
now the ```$DOCKER_HUB_TOKEN```contain ```77a278d7-7ec8-4a35-ac53-8f96c483ce65```

**Comment by BanzaiMan** [comment]
You can try https://quay.io/repository/travisci/travis-go.

**Comment by sebglon** [comment]
i COPY command on travis log andd paste them on travis-go container;
Thats OK; i have not the same error than auto build 

https://travis-ci.org/docking-tools/register/builds/122444651

**Comment by sebglon** [comment]
When build _.travi.yml_ and copy generated script on travis-go container

ALL is OK:
```
$ curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "0.0.1"}' -X POST https://registry.hub.docker.com/u/dockingtools/register/trigger/$DOCKER_HUB_TOKEN/

OK

The command "curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "0.0.1"}' -X POST https://registry.hub.docker.com/u/dockingtools/register/trigger/$DOCKER_HUB_TOKEN/
  " exited with 0.
```
But when travis run auto build i have 
```
$ curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "0.0.1"}' -X POST https://registry.hub.docker.com/u/dockingtools/register/trigger/$DOCKER_HUB_TOKEN/
      
Not found
```

**Comment by sebglon** [comment]
I did'nt thay way but i have solved my error
