### ISSUE TITLE
[Feature Request] Guix support

### ISSUE THREAD

**Issue by arximboldi** [travis-ci/travis-ci#5886]
Hi!

Guix [1] is a purely functional package manager in the spirit of Nix [2]. Support for either would be nice, even though I prefer the former.

There are many advantages for such a package manager, but there are two that seem particularly relevant for me in the context of Travis CI:
- The ability to **describe all dependencies** and environment for a project in a **language agnostic** way, that is the **same for Travis CI and for local** developer machines [3].
- Purely functional package management means being able to **share intermediate builds** for dependencies between builds safely. No more waiting for a long C++ dependency to build!

Guix support could be something similar to the way Travis supports Pypi, Npm, and other language specific package managers. One can enable it for a particular project and Travis could automatically pick a specified Guix environment file such that the system and dependencies are ready when the script is executed. This would be a huge win specially for C and C++ projects, which are often very complicated to set up on Travis, specially if they require cutting edge compilers and other dependencies.

Thanks a lot!

[1] https://www.gnu.org/software/guix
[2] http://nixos.org/
[3] https://www.gnu.org/software/guix/manual/html_node/Invoking-guix-environment.html

**Comment by BanzaiMan** [comment]
Our deployments are handled by https://github.com/travis-ci/dpl. We welcome your contributions.

**Comment by rasendubi** [comment]
Travis now has Nix support

**Comment by domenkozar** [comment]
@arximboldi would be nice to remove Nix from the issue name, not to confuse anyone.

**Comment by apteryks** [comment]
Hello! Can we reopen this issue? Having the ability to use Guix as a CI environment would be very valuable.
