### ISSUE TITLE
Python package cli not recognized.

### ISSUE THREAD

**Issue by GandaG** [travis-ci/travis-ci#5887]
The [build](https://travis-ci.org/GandaG/fomod-editor/builds/122414891).

Just installed python package "invoke" that has a cli that can be called either throught `invoke `or `inv`

Trying to call that cli results in:

```
$ invoke build
/home/travis/build.sh: line 45: invoke: command not found
The command "invoke build" exited with 127.
```

**Comment by BanzaiMan** [comment]
Probably your tool is installed in a place that's not in `$PATH`.

**Comment by GandaG** [comment]
It should be, I've used that same install script on my own ubuntu laptop and on a vagrant VM and it works without any path changes.

I also just added the folder where the cli is located to path `$HOME/versions/miniconda3-3.19.0/envs/fomod-editor/bin` and still nothing :/

I guess there is something that I'm not seeing but I have no idea what.

**Comment by GandaG** [comment]
I was separating the invoke command from the install script where I guess the path got unset. Fixed by re-setting all the variables for running invoke. Thanks!
