### ISSUE TITLE
Environment Variables values displayed even when display is OFF in R session info

### ISSUE THREAD

**Issue by mstellwa** [travis-ci/travis-ci#5888]
Values of environment variables with "Display value in build log" set to OFF are shown in the R session part of the output log.

@craigcitro, @hadley and @jimhester

**Comment by mstellwa** [comment]
Tested with using encrypted, according to https://docs.travis-ci.com/user/encryption-keys/, variables and there is the same issue with them, the variable value is shown in the R session part of the log.

**Comment by BanzaiMan** [comment]
If the command that you are using is accessing secure environment variables and writing to the logs, there is nothing bash (or the R build script) can prevent them from getting printed.

Bash does not have any idea of which variables are secure and which are not.

**Comment by mstellwa** [comment]
Oh, my mistake. Missed that I had a env command to dump the variables....
