### ISSUE TITLE
Builds with RBX-3 fails on sudoless environment

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#5889]
I tried to specify rbx-3 as an interpreter for the sudoless environment and it seems that sudo is required for it to work. https://travis-ci.org/celluloid/nio4r/jobs/122348616#L153
However when I specify rbx-3.25 everything works as expected https://travis-ci.org/celluloid/nio4r/jobs/122224390#L162

**Comment by BanzaiMan** [comment]
We rely on Rubinius team to provide us with the binaries. See http://binaries.rubinius.com (or http://rubies.travis-ci.org/rubinius for a sorted list) for available versions.
