### ISSUE TITLE
Failed to find Build Tools revision 23.0.3

### ISSUE THREAD

**Issue by SandroMachado** [travis-ci/travis-ci#5891]
Is it possible to update the android travis images to include the new version (`23.0.3`) of the build tools?

**Comment by BanzaiMan** [comment]
See discussion in https://github.com/travis-ci/travis-ci/issues/5648.

Sorry for the delay in build env updates. The next one will (of course) include Android update.

**Comment by SandroMachado** [comment]
There is any ETA for the next release?

**Comment by BanzaiMan** [comment]
No ETA to share at this time.
