### ISSUE TITLE
after_success script blocks build success?

### ISSUE THREAD

**Issue by mattpr** [travis-ci/travis-ci#5893]
Setting up auto-merge for pull requests on github if the travis build passes.
Figured the after_success script was an easy option (simple to update `.travis.yml` in all repos.
Something like the following:

```
after_success:
    - 'curl --silent -X POST --data "pr=$TRAVIS_PULL_REQUEST&repo_slug=$TRAVIS_REPO_SLUG" http://server/travis-success'
```

The little web-service checks the repo/pr and double checks that travis was successful...then merges the PR with an "autobot" comment.

Unfortunately at this stage github reports `mergeable_state: 'unstable'` for the pull request...so we don't merge. 

In theory the build is success at this point and so github should be able to pick that up...

https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build

> The after_success, after_failure, after_script and subsequent stages do not affect the the build result.

Is this just a latency issue (github gets latest build status async), or is there something else I am missing?

Was hoping to keep the webservice stupid simple, but may have to add a queue.  Thought I would check first just in case there is an update bug.

**Comment by BanzaiMan** [comment]
I see how this can be confusing, especially how it is phrased in the document.

To be technically correct, we report CI status back when the build script finished running. Deployment happens before that, of course.

**Comment by mattpr** [comment]
Okay.  I will trigger my auto-merge (on success) with git hooks instead of using the after_success travis script.  Thanks for clarifying.
