### ISSUE TITLE
PR notifications on build failures

### ISSUE THREAD

**Issue by vipulnsward** [travis-ci/travis-ci#5896]
See https://github.com/rails/rails/blob/master/.travis.yml#L49-L51
Based on documentation: https://docs.travis-ci.com/user/notifications/#Campfire-notification
and configuration above, I believe failures or success from builds should not be notified?

But we've been seeing builds errors(failures/errors) getting notified.

Example: http://take.ms/kD3c2

I may be totally wrong, please ignore if thats the case. :smile:

**Comment by BanzaiMan** [comment]
```yaml
  campfire:
    on_success: change
    on_failure: always
```

means:

* When this build is a success, and if the previous build was a failure, notify. On two consecutive successes, the second success will not.
* When this build fails, always notify.

Near the top of the page, you find:

> You can change the conditions for each of the channels by setting the on_success on on_failure flag on that medium to one of:
> 
> `always`: always send a notification.
> `never`: never send a notification.
> `change`: send a notification when the build status changes.

**Comment by vipulnsward** [comment]
@BanzaiMan docs say - "Pull Request builds do not trigger Campfire notifications."
Trying to find nothing gets reported from Pull Requests.

**Comment by BanzaiMan** [comment]
@vipulnsward Hmmm. Which build triggered the notification you showed?

**Comment by vipulnsward** [comment]
Here is an example: 
Build: https://travis-ci.org/rails/rails/builds/120467519
Notification: http://take.ms/hdYLj

**Comment by vipulnsward** [comment]
Sorry about the confusion. We are not running Travis notifications but a special bot, that is causing this. :sweat:
