### ISSUE TITLE
jdk_switcher not working on Trusty environment

### ISSUE THREAD

**Issue by gsmet** [travis-ci/travis-ci#5897]
Hi!

There is something weird going on regarding the jdk_switcher in the Trusty environment.

I use the apt addon to install a newer version of the JDK 8 but when the jdk_switcher is called to switch to this new version, I get the following error:

```
$ jdk_switcher use oraclejdk8
Switching to Oracle JDK8 (java-8-oracle-amd64), JAVA_HOME will be set to /usr/lib/jvm/java-8-oracle-amd64
update-alternatives: error: no alternatives for apt
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-8-oracle-amd64/bin/apt
```

and the build is still using the old default JDK.

References:
- travis.yml: https://github.com/gsmet/hibernate-search/blob/HSEARCH-2217/.travis.yml
- build: https://travis-ci.org/gsmet/hibernate-search/builds/122560314

Thanks!
## 

Guillaume

**Comment by BanzaiMan** [comment]
Looks like the current stable Trusty image has *something* missing. (Not sure what.)

However, I believe the edge image works. Could you try adding

```yaml
group: edge
```

to the top level of your `.travis.yml`?

**Comment by electrum** [comment]
I had the same problem. Try removing the `jdk` section when using `oracle-java8-installer`, which seems to fix the issue: https://github.com/prestodb/presto/commit/ef5d496a31d54ca65c15fbe71601509000d2e162

**Comment by meatballhat** [comment]
@gsmet [This build env update](https://docs.travis-ci.com/user/build-environment-updates/2016-12-06/) shipped a few minutes ago, and is expected to correct issues like this.  Are you able to verify?

**Comment by gsmet** [comment]
@meatballhat looks better!

(it's normal the job is failing)
https://travis-ci.org/gsmet/hibernate-validator/jobs/181629047#L6 uses the latest JDK

Not sure the "Build system information" part not being toggable is expected?

**Comment by meatballhat** [comment]
@gsmet that fold can be toggled after reload, at least, and is definitely an unrelated issue being tracked by humans who work mostly on the web rendering bits 👍

**Comment by thadguidry** [comment]
@meatballhat Do we have something abnormal that causes this same issue ? https://travis-ci.org/OpenRefine/OpenRefine/jobs/260572448
