### ISSUE TITLE
Latest version of Chrome fails to install on Precise

### ISSUE THREAD

**Issue by dtracers** [travis-ci/travis-ci#5899]
Using the workaround supplied in #272, and #938 chrome no longer works in travis with the latest stable build because its dependencies no longer work.

Here is the chromium bug
https://bugs.chromium.org/p/chromium/issues/detail?id=583235&q=os%3Alinux%2Cmac&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

Here is a travis build failing with this error:
https://travis-ci.org/tracyhammond/coursesketch/builds/122883485

It according to the chrome bug 12 is being dropped from chrome support which causes the latest stable build of chrome to fail.

Either travis can come with newer versions of:
libstdc++6 (>= 4.8.0)
lsb-base (>= 4.1)

I will update if I find a workaround

**Comment by BanzaiMan** [comment]
I suggest updating those packages.

http://packages.ubuntu.com/trusty/libstdc++6
http://packages.ubuntu.com/trusty/lsb-base

**Comment by cantsin** [comment]
I get this error too. Updating these packages does not work: 

```libstdc++6 is already the newest version.
lsb-base is already the newest version.```

**Comment by dtracers** [comment]
Those are trusty updates not precise so wouldn't they wont work on 12 only 14

Currently I am running a build that is using the trusty dist instead of the default.

**Comment by dtracers** [comment]
for reference this is the set of commands I am using to install chrome:
```
  - "sudo apt-get remove  -y chromium-browser"
 - "sudo apt-get -qq update"
 - "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections"
 - "sudo apt-get install -qq ttf-mscorefonts-installer"
 - "sudo apt-get install -qq x-ttcidfont-conf"
 - "sudo mkfontdir"
 - "sudo apt-get install -qq defoma libgl1-mesa-dri xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic libappindicator1"
 - "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
 - "sudo mkdir -p /usr/share/desktop-directories"
 - "sudo dpkg -i google-chrome-stable_current_amd64.deb"
 - "sudo apt-get install -f"
 - "sudo dpkg -i google-chrome-stable_current_amd64.deb"
 - "export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox"
 - "sudo rm -f $CHROME_SANDBOX"
 - "sudo wget https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE -O $CHROME_SANDBOX"
 - "sudo chown root:root $CHROME_SANDBOX; sudo chmod 4755 $CHROME_SANDBOX"
 - "sudo md5sum $CHROME_SANDBOX"
 - "sudo chmod 1777 /dev/shm"
```

This fails because installing the ms fonts do not work.

(solution to install the fonts: [Font intstall solution](http://askubuntu.com/questions/659305/package-ttf-mscorefonts-installer-has-no-installation-candidate))


I am attempting to install without the fonts first. removing all font related instalation

**Comment by BanzaiMan** [comment]
Sorry that I overlooked the Chrome bug. If it's not possible to install it on Precise, though, I don't think we can do much about that.

**Comment by azakus** [comment]
Precise was dropped by Chrome: https://groups.google.com/a/chromium.org/d/msg/chromium-dev/FoE6sL-p6oU/mVlwyh02AgAJ

**Comment by blimmer** [comment]
Do we all need to move to the trusty beta then?

**Comment by dtracers** [comment]
It's either that for find a way to get an older version of chrome.  That
will work unless ppl want to use newer features

**Comment by cantsin** [comment]
Moving to the trusty beta works (by adding/changing the following to `travis.yml`)

```
sudo: required
dist: trusty
```

At least, it doesn't break anything for me. YMMV.

**Comment by dtracers** [comment]
Can you share how your are installing chrome?

Installing chrome broke for me

**Comment by cantsin** [comment]
@dtracers Sure. I don't think I'm doing anything special, though:

```
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
```

**Comment by pamil** [comment]
How can we install an older Chrome version? I still prefer the container based infrastructure.

**Comment by BanzaiMan** [comment]
Looks like Google's repository keeps only the latest versions. It seems to me that we are unable to support Chrome on Precise at this time.

I'm inclined to just document it and close this issue.

**Comment by BanzaiMan** [comment]
We do not have meaningful mention of Chrome except https://docs.travis-ci.com/user/build-environment-updates/2015-04-09/, which was subsequently canceled.

**Comment by gkatsev** [comment]
Is there a way to upgrade to a newer distro that chrome supports but still use the container infrastructure (`sudo: false`)?

**Comment by pamil** [comment]
@gkatsev there is Chromium v37 installed which works with Selenium using ChromeDriver v2.12

**Comment by BanzaiMan** [comment]
Is it possible to obtain an older version of the package usable on Precise? If so, is it legal to put that somewhere we can use?
