### ISSUE TITLE
build.sh "value too great for base" error in all trusty builds

### ISSUE THREAD

**Issue by blimmer** [travis-ci/travis-ci#5900]
Had to bump to trusty beta to get chrome working again and now I'm seeing this in every project:

```
/home/travis/build.sh: line 430: [[: 000029000000: value too great for base (error token is "000029000000")
```

```
/home/travis/build.sh: line 462: [[: 000029000000: value too great for base (error token is "000029000000")
```

**Comment by BanzaiMan** [comment]
What token is this?

**Comment by blimmer** [comment]
Not sure, how do I find out?
On Wed, Apr 13, 2016 at 16:32 Hiro Asari <notifications@github.com> wrote:

> What token is this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/travis-ci/issues/5900#issuecomment-209675698>
>
-- 
[sent from my mobile]

**Comment by BanzaiMan** [comment]
Could you point to a build log URL, please?

**Comment by blimmer** [comment]
Sure, [this one](https://travis-ci.com/Ibotta/ibotta-ember-commons/jobs/37735733) shows the problem.

**Comment by BanzaiMan** [comment]
Thanks. Found a bug, and also a fix for it. Will deploy it Monday.

**Comment by BanzaiMan** [comment]
Sorry for the delay. The fix has been deployed.
