### ISSUE TITLE
Job fails on PHP 5.6: mongodb.so: cannot open shared object

### ISSUE THREAD

**Issue by adam-boduch** [travis-ci/travis-ci#5902]
.travis.yml:

```
before_install:
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
```

Log:

`PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.6.5/lib/php/extensions/no-debug-zts-20131226/mongodb.so' - /home/travis/.phpenv/versions/5.6.5/lib/php/extensions/no-debug-zts-20131226/mongodb.so: cannot open shared object file: No such file or directory in Unknown on line 0`

Works fine on PHP7. According to docs (https://docs.travis-ci.com/user/languages/php) it should work also on PHP 5.6

**Comment by BanzaiMan** [comment]
I think this is the same issue as #5618.

**Comment by BanzaiMan** [comment]
Also related #5621.

**Comment by BanzaiMan** [comment]
Please use mongo instead.
