### ISSUE TITLE
travis_wait make docker can not  enable tty mode on non tty input

### ISSUE THREAD

**Issue by kevin-leptons** [travis-ci/travis-ci#5903]
i am building [lfs-auto](https://github.com/kevin-leptons/lfs-auto)

- my build take long time and send many data to stdout, so i redirect all data from stdout to /dev/null to reduce size of log file

- but not thing output to stdout make travis-ci kill process after 10 min. i am continue use **travis_wait** to increase timeout

-  **travis_wait** make **docker** can not start with option **-ti**

you can see build at [lfs-auto#222](https://travis-ci.org/kevin-leptons/lfs-auto/builds/123066496). start process at line 105, error at line 1148 of log file. call docker at [run.sh](https://github.com/kevin-leptons/lfs-auto/blob/bd48497e602f3fc4c1356366852fdcea4e3add4e/run.sh) line 50

**Comment by BanzaiMan** [comment]
`travis_wait` does not handle STDIN redirection, which I suspect `docker run -it` is trying to do.

If `./run.sh` is writing something on STDOUT more frequently than every 10 minutes, it will not be killed. There is no need for `travis_wait`. You should manage docker process in that script instead.

**Comment by kevin-leptons** [comment]
i am trying other solution, thank you

i will close this issue
