### ISSUE TITLE
Travis-CI MONO no solution or script defined

### ISSUE THREAD

**Issue by AndreasAugustin** [travis-ci/travis-ci#5904]
Hello dear developers,

I tried hardly to get my little project to work with Travis, always with the error message:

> No solution or script defined, exiting.

Detailed build information:
[![Build Status](https://travis-ci.org/AndreasAugustin/Gherkin-Demos-mono.svg?branch=master)](https://travis-ci.org/AndreasAugustin/Gherkin-Demos-mono)

 The .travis.yml looks as followed:

`﻿language: csharp
solution: mono.sln
before_script:
  - nuget restore mono.sln
script:
  - xbuild /p:Configuration=Debug mono.sln
` 

I tried to convert line endings from LF to CRLF and played with settings. It is encoded in UTF8.

Maybe you are able to help me here :smile: 

Thanks in advance

@joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
Can you please try removing the BOM from the file? Travis doesn't handle this: https://github.com/travis-ci/travis-ci/issues/4839

**Comment by AndreasAugustin** [comment]
Thank you very much. This solved the problem. Build starting now.
