### ISSUE TITLE
Maven problematic pre-build step using "install" goal

### ISSUE THREAD

**Issue by ctubbsii** [travis-ci/travis-ci#5907]
The docs at https://docs.travis-ci.com/user/languages/java#Dependency-Management say that travis does `mvn install -DskipTests=true` to install project dependencies before building.

However, this is a huge problem, because I want to cache my ~/.m2 directory, to cut time on downloading dependencies, but I can't do that if my own artifacts are installed into ~/.m2 , which is exactly what happens when one runs `mvn install`.

If travis-ci wants to run this pre-step to pre-fetch my dependencies, it should be using `mvn verify -DskipTests -DskipITs` to do this. Even then, other plugins could be running which are wasting time and resources, and possibly corrupting the build which follows or polluting the caches, but it definitely shouldn't be going past the `verify` phase of the Maven build lifecycle.

What might be better is to use `mvn dependency:go-offline` to pre-fetch downloads.

Further, I noticed that the dependencies which are downloaded at this step seem to use the `https` mirror of Maven Central... but when my project does the build I've configured, it uses the `http` mirror (when it grabs the additional dependencies the pre-fetch missed).

In the meantime, there should be a way to disable this pre-fetch step. (perhaps there is, but it's not documented on that linked page where the behavior is documented).

**Comment by ctubbsii** [comment]
[This StackOverflow answer](http://stackoverflow.com/a/33527978/196405) seems to indicate I can override the pre-build step to pre-fetch the dependencies.

I will definitely be trying this. However, the default should not use `mvn install` (`mvn install` is rarely the right thing to use) and the difference in which mirror it uses (https or http) is very strange. It should always use https by default.

**Comment by BanzaiMan** [comment]
I understand the issue you are raising, but I do not think we would be changing the default, as it may break existing builds.

Overriding the `install` step is best.
