### ISSUE TITLE
Update SQLite3 version

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#5908]
According to chagelog: https://www.sqlite.org/changes.html
The feature I'm using was added in 3.6.4 (released 2008-10-15), to be exact, here is the change I need:

> Add option support for LIMIT and ORDER BY clauses on DELETE and UPDATE statements. Only works if SQLite is compiled with SQLITE_ENABLE_UPDATE_DELETE_LIMIT.

Otherwise my builds fail on Travis CI: https://travis-ci.org/nazar-pc/CleverStyle-CMS/builds/123235615

I'm using container-based infrastructure.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/apt-package-whitelist/issues/368#issuecomment-198586476.

**Comment by nazar-pc** [comment]
Unfortunately, it didn't help: https://travis-ci.org/nazar-pc/CleverStyle-CMS/jobs/123242600
Looks like PHP itself should be built with newer SQLite3.

**Comment by BanzaiMan** [comment]
Hmmm. PHP compiles SQLite3 code into the binary?

**Comment by nazar-pc** [comment]
I'm not sure how it works exactly, but I'm almost sure it will need at least headers in order to built extension. So version of SQLite3 present at compilation time should play role here.

**Comment by nazar-pc** [comment]
Can I do something on my side other than using sudo and compiling PHP manually at this point?

**Comment by BanzaiMan** [comment]
Is this still an issue with the current Trusty image?

**Comment by nazar-pc** [comment]
I don't know, had to change SQL in order to please Travis CI more than a year ago

**Comment by BanzaiMan** [comment]
Thanks for the info. I'm closing this for now, then. The Trusty images should have 3.8.2. https://packages.ubuntu.com/trusty/sqlite3
