### ISSUE TITLE
Most builds fail to download dependencies - "Connection reset"

### ISSUE THREAD

**Issue by ctron** [travis-ci/travis-ci#5909]
On our build job [1], most builds fail with "Connect reset". After a few re-tries it sometimes works.

[1] https://travis-ci.org/eclipse/packagedrone/builds

**Comment by BanzaiMan** [comment]
Thanks for the report. It appears the network is somewhat unreliable. Could you try wrapping `mvn package` call in the `travis_retry` Bash function, and/or use caching https://docs.travis-ci.com/user/caching/ to cache maven artifacts?

**Comment by ctron** [comment]
Prefixing this with with `travis_retry` simply seems to run it three times. But in the end still fails. After a few manually re-builds it seems to work then. Implementing caching seems to be a bigger task. But I will give it a try.

**Comment by BanzaiMan** [comment]
Seems to be working.
