### ISSUE TITLE
Mandrill or Mailer / SMTP support?

### ISSUE THREAD

**Issue by daison12006013** [travis-ci/travis-ci#5910]
@henrikhodne hey bro, it seems travis-ci smtp outbound blocks the port?

*Here's the build:*
https://travis-ci.org/phalconslayer/slayer/jobs/123295451

*To make it short:*
```
Swift_TransportException: Connection could not be established with host smtp.mandrillapp.com [Connection refused #111] (uncaught exception) at /home/travis/build/phalconslayer/slayer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php line 265
```

It seems I can't connect through mandrill, or my travis secured credentials might be wrong? I'm pointing it to the same repo anyway when encrypting my credentials, and running mailer on my local is working well.

---

If you guys were not blocking it, I'll try to import a naked credentials and later change the password.

**Comment by BanzaiMan** [comment]
Hello. To the best of my knowledge, we are not blocking outbound SMTP traffic. (Though, in general, I think it is a bad idea to incorporate external resources in your testing.)

It is possible that your credentials are not properly encrypted. Some characters may need escaping. https://docs.travis-ci.com/user/environment-variables

> Notice that the values are not escaped when your builds are executed. Special characters (for bash) should be escaped accordingly.

**Comment by daison12006013** [comment]
Hi @BanzaiMan, I only have single underscore on my password and nothing is special, I tried exporting it through shell and echoing it back, I got the same value.

Or are you referring to the passed *secure*

- secure: "D/ydBvZryeXONbWIPMDCLgyCVGxP1zG2l+dgxMfHt9su+ZACOMRkCMu7NiQGVB1HtWeASR3nOKVoz9Qh8ViEHh36OqCdGMQLqakLHQC7Krtah33XiMuQXKv37O2mATi49LZzhFmMjEmGX6aZ/rR4ayxayle+HGKT/6af+hB70wgs9ONywilnxrI8MvhGbua/DEIyFZVL42F3RBck8UP9QCbhf6dvop326iykhXlwv0JQeDFzaz1UrtwxvE6tdrAjn/OIRhgOsgLHFSL8q1GjxuQBOBwIfASjkzVb05dT7612hrihiWKiFSwhvR4Ts1duXcgIzhdGM2vsvwR1dVZKpkgcdAAZePfJSvyVwkUahITwewMWV6Inr1AhMWKO3XAFG5HUmGjNHX8Cadg/NkabvrJCL+InYKmw7iI17zQFgfT/NQK/aFF3CcbvuYhWZ+0AHQT7hdedwIzUDq5dbfKD0x6Ppto1mEI9KKwuSiRIAMzoY1DE486rgvzqgSod47Q2hMHgAFysSBeXu8PdrozD+/BwexO60mJ8DzsAszPoC8qBxxg5ipN1Xzh7y6/8NaFoh5HQo4y47g0LK0pgSA7pvdMVA9rD3FbP9GqSSLKqnhaUnaN8RGIl4qWGdsaI4Q95KPYRXSWxP8Y8enxvOq5YOAu5Gjqc9UPJySUF3L0wH+w="

Should I escape that?

**Comment by BanzaiMan** [comment]
Underscores are not special in shell, so that shouldn't matter. Beyond getting more debug information (perhaps from Mandrill support), I am not sure what else to do from here.

**Comment by daison12006013** [comment]
I'll gonna try to make it naked/exposed credentials, I'll just regenerate a token on my API again.

or they have a test api token which I could probably test that out, will leave this issue open until my test is done, if the exposed credentials works well, it means the secure might have some encryption issue or I don't know.

If it still blocks and shows an error connection problem, that could probably a problem inside travisci network going to their API.

@BanzaiMan, maybe you could switch on the same network that uses your travisci, and try to telnet this smtp.mandrillapp.com@587

**Comment by BanzaiMan** [comment]
I see. https://travis-ci.org/BanzaiMan/travis_production_test/builds/125262457#L185

I think Mandrill is blocking the traffic. I suggest contacting Mandrill support.

**Comment by BanzaiMan** [comment]
Closing this now, since it appears to be beyond our control. Let us know if there is something we can do.

**Comment by daison12006013** [comment]
Thanks @BanzaiMan, will definitely ask them about this.

**Comment by brookslyrette** [comment]
This was working for me up until September. Were there any changes that might have reopened this issue?

**Comment by BanzaiMan** [comment]
@brookslyrette Have you contacted their support?

**Comment by brookslyrette** [comment]
I did, they seem to think it is on Travis-ci's end. 

> Thanks for reaching out. It looks like you're sending via SMTP. Are you seeing any errors on your end when you view the full SMTP conversation? There may also be an issue where your system is opening too many simultaneous connections (we allow up to 50), or your hosting provider is limiting the amount of bandwidth allowed for sending over SMTP. This can also be because your server is taking too long to send data back to Mandrill, or because there's a networking issue from your server to Mandrill (typically related to your hosting provider, or an intermediate server to Mandrill's). It's also possible that your system is attempting to reuse a connection (this is usually good because reusing a connection can be far more efficient). However, if the connection idles out, you might start seeing these errors intermittently (when it has idled out).
> 
> I'd recommend getting in touch with your host to determine if there are any limitations for using SMTP on the port(s) you're using. Also, you may want to investigate whether/how your system determines when to open a new connection and how to ensure a prior connection is closed.
> 
> Let us know if you have any other questions and we'll be glad to help.

Everything works when I run it locally, it only fails on Travis.

**Comment by BanzaiMan** [comment]
@brookslyrette In https://github.com/travis-ci/travis-ci/issues/5910#issuecomment-213804150, I showed how Mandrill is blocking connexions to port 25. Is this not the case for your builds?

**Comment by brookslyrette** [comment]
We trying to connect to smtp.mandrillapp.com:587. We are getting a timeout error. 

```
org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.mandrillapp.com, 587; timeout -1;
      nested exception is:
        java.net.ConnectException: Connection refused. Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.mandrillapp.com, 587; timeout -1;
      nested exception is:
        java.net.ConnectException: Connection refused
```

**Comment by BanzaiMan** [comment]
@brookslyrette https://travis-ci.org/BanzaiMan/travis_production_test/builds/167082890#L145 I can connect to that port.
