### ISSUE TITLE
xcode hangs the start up times

### ISSUE THREAD

**Issue by jaredsburrows** [travis-ci/travis-ci#5917]
Specifying:

```
osx_image:
 - xcode7.3
```

Seems to delay the build for sometime. Can't we just make this the default?

See: https://travis-ci.org/jaredsburrows/ios-gradle-objc-template/builds/123655312

**Comment by jaredsburrows** [comment]
I think it happens when doing:
```
osx_image:
 - xcode7.1
```
vs.
```
osx_image: xcode7.1
```

Possible grammar/parsing issue?

**Comment by jaredsburrows** [comment]
Based on my new build here: https://travis-ci.org/jaredsburrows/ios-gradle-objc-template/builds/123664044.

It must be a parsing issue.

**Comment by BanzaiMan** [comment]
Could you try removing `sudo: false` line? I suspect that it is taking precedence here, sending the job to containers, which cannot find an Objective-C image (naturally).

**Comment by jaredsburrows** [comment]
Here is my current build: https://travis-ci.org/jaredsburrows/ios-gradle-objc-app-template

https://github.com/jaredsburrows/ios-gradle-objc-app-template/blob/master/.travis.yml#L3

Basically it looks like TravisCI has some sort parsing issue.
