### ISSUE TITLE
xcode7 jobs don't start

### ISSUE THREAD

**Issue by glandium** [travis-ci/travis-ci#5925]
As of writing, I have 5 builds still waiting for xcode7 osx jobs to start.

For example: https://travis-ci.org/glandium/git-cinnabar/builds/124083018

**Comment by BanzaiMan** [comment]
I see that this job is getting perpetually restarted.

**Comment by BanzaiMan** [comment]
Not quite sure what's happening, and I can't reproduce the issue. Could you cancel and restart the offending jobs?

**Comment by glandium** [comment]
I stopped them all and retriggered one:
https://travis-ci.org/glandium/git-cinnabar/jobs/124080904

It seems stuck on "booting".

**Comment by glandium** [comment]
Ah no, it started. It looks like whatever happened is fixed.
