### ISSUE TITLE
Out of memory when building qt5

### ISSUE THREAD

**Issue by tpetazzoni** [travis-ci/travis-ci#5926]
Hello,

As part of our test infrastructure for the open-source Buildroot (http://buildroot.org) project, we build Qt5 with Travis-CI. As can be seen at https://travis-ci.org/buildroot/buildroot-defconfig-testing/jobs/124036142, the Qt5 build fails with:

```
{standard input}: Assembler messages:
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
```

Which we believe is due to the memory limit, as explained at https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error. Unfortunately, there's not much we can do: Qt5 is a pretty complex piece of C++ source code, so yes, g++ consumes quite a bit of memory.

What can we do to solve this problem?

**Comment by BanzaiMan** [comment]
Try GCE with `sudo: required`.

**Comment by tpetazzoni** [comment]
Thanks for the quick feedback! However according to https://docs.travis-ci.com/user/migrating-from-legacy/, the new container-based infra (```sudo: false```) actually offers more resources. So I'm not sure to understand how switching back to the old infra, which provides less resources, would solve this specific problem?

**Comment by BanzaiMan** [comment]
GCE is the new platform, replacing the legacy one. https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

**Comment by tpetazzoni** [comment]
Thanks for the link, I'll try this new platform. I'm closing the bug for now, I'll re-open if I still get some issues.
