### ISSUE TITLE
cd command (change directory) doesn't work anymore in separate build script

### ISSUE THREAD

**Issue by stachnim** [travis-ci/travis-ci#5928]
Hi. My project structure looks like this:
project root (with root parent pom.xml)
|- ice-boar/ (with pom.xml)
|- ice-boar-samples/ (build from parent pom.xml) 

I need to build my project in that way:
1. go to `ice-boar` directory
2. execute `mvn clean deploy`
3. back to root dir
3. execute `mvn clean install`
4. next steps....

`ice-boar` module isn't include in parent project root pom.xml because I wouldn't release this parent pom to Maven Central. This steps I have defined in [build-travis.sh](https://github.com/Roche/IceBoar/blob/master/build-travis.sh).
For previous build [#49](https://travis-ci.org/Roche/IceBoar/builds/122658641) This setup was working. We can see that on screenshot:

![build01](https://cloud.githubusercontent.com/assets/13899811/14636726/71e888b6-062d-11e6-8aa6-de0044b39c2a.png)

In next build [#50](https://travis-ci.org/Roche/IceBoar/builds/124138048) I modify a little bit this script, but `cd ice-boar` command is still there. And looking for build output:

![build02](https://cloud.githubusercontent.com/assets/13899811/14636856/37b35116-062e-11e6-8911-f34decc7ac25.png)

Problems:
* a content of build-travis.sh is not shown
* there is `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V` called - whats this?
* output of build suggest like a root of project is build instead of `ice-boar` module - this is a reason why this build fails.

A diff between this 2 builds: https://github.com/Roche/IceBoar/compare/59afad4f70d6...28ec1af79000

Could you look at this please?

**Comment by BanzaiMan** [comment]
`mvn install …` is the default install command, documented in https://docs.travis-ci.com/user/languages/java#Projects-Using-Maven.

Your `script` phase, where you call `./build-travis.sh` (https://github.com/Roche/IceBoar/blob/84d860d7a8b71801276322447c3fadb06bac4bec/.travis.yml#L2) is never executed because the `install` phase fails.

**Comment by stachnim** [comment]
@BanzaiMan Skipping the Installation Step using `install: true` solve my problem. On this same page we can read:

> install: install any dependencies required
> script: run the build script

So I used a `script` phase to define my Maven build command. It wasn't clear for me that `install` phase also call some maven command. Maybe a default `install` phase should be better documented?

Thanks for help!

**Comment by BanzaiMan** [comment]
@stachnim I can't find that passage in the Java page. The `install` phase is explained there. I also updated the document to be more explicit that these are default commands run during the `install` and `script` phases.

**Comment by stachnim** [comment]
@BanzaiMan It is here: https://docs.travis-ci.com/user/customizing-the-build/ I mix links - sorry. Now a doc looks better. 
Consider my last suggestion: In [Building a Java project](https://docs.travis-ci.com/user/languages/java) is "script command" and "default install", but on [Customizing the Build](https://docs.travis-ci.com/user/customizing-the-build/) page there are defined "install" & "script" as a steps. You can use one word for better "consistence" between pages.

Tanks for quick answers!
