### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by ddobrev** [travis-ci/travis-ci#5931]
GitLab (https://gitlab.com/) is an excellent code hosting service, it even has its own CI. The problem with their CI is that it has to run on the user's server unlike Travis. So integration with Travis is an excellent feature for GitLab users who cannot support their own server, especially given that Travis is the only service offering free OS X builds for open source projects.

**Comment by sanmai-NL** [comment]
It doesn't have to run on your own host, they have "shared runners".

**Comment by ddobrev** [comment]
Even the shared runners have to be installed by the user - http://doc.gitlab.com/ce/ci/runners/README.html, "See the documentation for the different methods of installing a Runner instance.". In other words, the GitLab CI does not offer, let's call it, a fully on-line experience as Travis does. This is why it would be useful if Travis could build code hosted at GitLab as it does with code at GitHub.

**Comment by sanmai-NL** [comment]
That documentation is about their self-hosted software product GitLab Community Edition. Both for gitlab.com repository servers and self-hosted repository servers the let you host your own shared and/or dedicated runners. The shared runners for gitlab.com are freely available. See: https://about.gitlab.com/2016/04/05/shared-runners/

**Comment by solarce** [comment]
@ddobrev, we understand and can appreciate your interest in having Travis CI support Gitlab in a similar manner to how we support Github.

At this time, we integrate heavily with GitHub specific authentication and APIs and are focused on delivering an excellent CI experience for folks using GitHub and we do not have any plans to pursue the kind of integration with Gitlab, that you're looking for.

Mirror your commits to Github would allow you to take advantage of Travis while still using Gitlab for other parts of your workflow, but this does, admittedly, require additional and individual work to accomplish.

**Comment by DavidMont** [comment]
+1 on this, I badly need this and well I could say that gitlab community is growing, the question is when right?

**Comment by jpic** [comment]
Any reason gitlab-ci doesn't satisfy gitlab users ?

**Comment by ddobrev** [comment]
@jpic last time I checked - about the time I reported this issue - GitLab-CI wasn't on-line as Travis is, it required users to host it themselves.

**Comment by solarce** [comment]
As mentioned previously, 

> At this time, we integrate heavily with GitHub specific authentication and APIs and are focused on delivering an excellent CI experience for folks using GitHub. We do not have any plans to pursue the kind of integration with Gitlab that you're looking for.

Given that Gitlab is continuing to expand their own hosted CI services, such as how [Gitlab has partnered with Digital Ocean for their shared runners](https://about.gitlab.com/2016/04/19/gitlab-partners-with-digitalocean-to-make-continuous-integration-faster-safer-and-more-affordable/) and has been expanding the [features of their Shared Runners](https://about.gitlab.com/2016/04/05/shared-runners/). It seems like any users should be able to achieve the experience they're looking for within the Gitlab ecosystem.

**Comment by jpic** [comment]
Well, given how easy it is to execute a gitlab CI test run on your laptop
and let it upload logs and statuses, I didnt expect the shared runners to
be so critical. Thanks for answering!

**Comment by leycec** [comment]
> Any reason gitlab-ci doesn't satisfy gitlab users ?

**Absolutely, Bob:** OS X-based continuous integration.

Whereas Travis does (_of course_) support a plethora of platforms including OS X, the free-as-in-beer GitLab-CI shared runners hosted by Digital Ocean only support a single Docker-based platform: **Linux.** Tragically, this appears [unlikely to change anytime soon](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1188):

> If you are writing about shared runners on GitLab.com, then they are only Linux based (with docker executor). If you need Windows, Mac or any other OS for the runner, then you need to install it on your own host and register it in your project on GitLab.com.

Numerous third-party CI services now integrate cleanly with GitLab-CI pipelines, notably including the Windows-based CI host [Appveyor](https://github.com/appveyor/ci/issues/219). Like Travis, Appveyor is free for open-source projects. This is good. Unlike Travis, Appveyor actually supports GitLab-CI. This is _not_ so good... for Travis, anyway.

Where there is a way there is a will, however. Cross-platform open-source projects supporting OS X hosted at gitlab.com _can_ still be exercised by Travis, even without official support for doing so. It's inelegant, crufty, and more than a little wild-eyed  – but it _can_ be done. Simply mirror a gitlab.com project onto a Travis-integrated github.com project via a hand-rolled git pre-push hook.

Of course, there are numerous reasons that approach sucks: notably, the lack of explicit GitLab-CI integration produces false positives on OS X-specific test failures (e.g., the build status badge on the gitlab.com project page reads "build success!" when, actually, the build horribly failed on OS X over at the github.com project). If that's the best we can do, well... it still beats me manually firing up an OS X laptop every time I commit a change suspected of breaking OS X support. But it's still not great.

I completely understand your position at Travis. GitHub was, is, and probably will continue to be the primary web platform for open-source CI hosting. But other web platforms supported by other CI hosts _do_ exist. If Travis fails to occupy that niche, inevitably, someone else will. Internet tubes abhor a vacuum.

**Comment by gajus** [comment]
> Any reason gitlab-ci doesn't satisfy gitlab users ?

* lack of concurrency settings (no guarantee in the order in which the pipeline will execute tasks)
* DIND approach is incredibly slow (50 second Travis job is taking +7 minutes)
* Using mounted Docker is not feasible without fine grained concurrency settings
* No way to clean up artifacts after build

**Comment by gajus** [comment]
@jpic 

> Any reason gitlab-ci doesn't satisfy gitlab users ?

* lack of concurrency settings (no guarantee in the order in which the pipeline will execute tasks)
* DIND approach is incredibly slow (50 second Travis job is taking +7 minutes)
* Using mounted Docker is not feasible without fine grained concurrency settings
* No way to clean up artifacts after build

**Comment by golyalpha** [comment]
@gajus I concur on the lack of concurrency setings - the pipeline will always execute tasks in build-test-deploy order, if you're looking for some other order, I kind of have to wonder what project are you running. If one of those tasks doesn't exist, it's skipped, if it fails, pipeline is stopped of course.

I do agree with the fact that it is incredibly slow ("build" of a python app, and deployment of it to Heroku takes literally ages - might as well use the Heroku CLI).

And I don't quite understand the "No way to clean up artifacts after build." 
Do you mean within the pipeline, or between different pipelines? Because afaik, every time a pipeline is run, it starts fresh and sets up everything from the config yaml file.

**Comment by BanzaiMan** [comment]
If you want to discuss Gitlab CI, there are other, more suitable venues. I'm locking this now.
