### ISSUE TITLE
"Encrypting multiple files - Note that this method works only with one file."

### ISSUE THREAD

**Issue by fniephaus** [travis-ci/travis-ci#5939]
The wording is a little weird/misleading:
![image](https://cloud.githubusercontent.com/assets/2368856/14717081/1719a7d4-07f0-11e6-97a1-6688f56987c3.png)
https://docs.travis-ci.com/user/encrypting-files/#Encrypting-multiple-files

It'd be better to mention that the cli tool overrides entries, so it's only possible to use it to encrypt one file.

/cc @BanzaiMan

**Comment by BanzaiMan** [comment]
@plaindocs Could you take a look, please?

**Comment by plaindocs** [comment]
Will do, cheers @BanzaiMan , @fniephaus !

**Comment by plaindocs** [comment]
I'm fixing that. While I'm here, line 79 `$ vi .travis.yml` is pretty vague. Are we telling them to add something like

> Please add the following to your build script (before_install stage in your .travis.yml, for instance):
      openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_key -in super_secret.txt.enc -out super_secret.txt -d

**Comment by BanzaiMan** [comment]
@plaindocs Yes, indeed, that is what I meant. The document has been updated.
