### ISSUE TITLE
schedule for updating R versions? printing R versions in results?

### ISSUE THREAD

**Issue by skyebend** [travis-ci/travis-ci#5940]
just got an R package build going in R travis CI, it is amazing, thank you!   @craigcitro, @hadley, and @jimhester.

however, I have questions about the R versions.  The docs say:

>Travis CI supports R versions 3.1.3, 3.2.3 and devel on Linux Precise builds. The names oldrel and >3.1 are aliased to 3.1.2 and the names release and 3.2 are aliased to 3.2.3

but presumably this has been updated?  R release should now be 3.2.5 and R devel  3.3.0?   It is especially important that devel tracks the R devel build from CRAN, as they frequently add new tests and will not accept package submissions unless they completely pass.  

Feature request:    The log file should clearly print the exact R build version used when the test was run.

**Comment by jimhester** [comment]
R-devel is built off of the git mirror (https://travis-ci.org/wch/r-source) of the R SVN repository. It is updated hourly, you can see the latest builds at https://travis-ci.org/wch/r-source.

Every log file prints the R version used in the 'R session information' tab, e.g. (https://travis-ci.org/statnet/ndtv/jobs/124899179#L451)

R-devel is actually currently 3.4, a separate 3.3 branch is created in the weeks prior to a release for testing.

R-release currently points to 3.2.4revisied. 3.2.5 contains no material changes from 3.2.4revised (see the [3.2.5 release notes](https://stat.ethz.ch/pipermail/r-announce/2016/000601.html) and it will be updated to 3.2.5 once https://github.com/travis-ci/travis-build/pull/703 is merged and deployed (probably not until next week). However you can explicitly use `r: 3.2.5` until that time.

The documentation is out of date and should be updated, you can edit the page at https://github.com/travis-ci/docs-travis-ci-com/edit/gh-pages/user/languages/r.md and submit a pull request to update it.

**Comment by skyebend** [comment]
Thanks!
