### ISSUE TITLE
Travis-ci fails to install rabbitmq on osx builds

### ISSUE THREAD

**Issue by vitaly-krugl** [travis-ci/travis-ci#5941]
Hi, I am trying to add osx build via Travis to the pika project on github. See https://github.com/pika/pika/pull/740. pika relies on rabbitmq for testing, and so it specifies in `.travis.yml`

```
services:
  - rabbitmq
```

This works for the Linux builds, but when the osx build runs, rabbitmq is nowhere to be found: `find / -name rabbitmq-server 2>/dev/null` comes up empty.

As a work-around, I am trying to install it manually via Homebrew, but this takes a very long time for both erlang and rabbitmq.

**Comment by solarce** [comment]
At the moment, most of the `services:` things only work on Linux. While we hope to expand our native support in OSX, we don't have any ETA on it yet.

You'll need to add some steps that use homebrew to install this on OSX for now.

**Comment by vitaly-krugl** [comment]
@solarce: according to this Travis-CI user documentation https://docs.travis-ci.com/user/osx-ci-environment/, RabbitMQ should be a supported service thing on osx. I made my decisions based on the information in that public document, and then ended up wasting many hours of my time trying to figure out why it wasn't working for me. :angry:

**Comment by solarce** [comment]
I am sorry if the documentation resulted in confusion and you ending up spending time going down the wrong path.

The mention of RabbitMQ is in the section describing the benefits of the fact that we use a new OSX VM for every build

> It is possible for test suites to create databases, add RabbitMQ vhosts/users and so on

The part of the documentation that discusses pre-installed services is https://docs.travis-ci.com/user/osx-ci-environment/#Services and mentions only:

> - postgis 2.1.3
> - postgresql 9.3.5

I will edit our documentation to remove the reference to *RabbitMQ*, since it's clearly resulting in some confusion

**Comment by vitaly-krugl** [comment]
@solarce, just re-read that doc all the way and came to the same confusion. It's that mention that gave me the false confidence. Cheers!

**Comment by solarce** [comment]
@vitaly-krugl thank you for understanding, I'll make sure rabbitmq is on the list of services for when we do start adding more stuff to our base OSX images.

**Comment by vitaly-krugl** [comment]
@solarce +1 for RabbitMQ on OSX

Also +1 for adding Python Runtime support on OSX (#2312)

Without those two, the build runtime ends up being quite long and `.travis.yml` unnecessarily more complex and error-prone.

Pika's Travis/Linux and AppVeyor/Windows builds are typically just under two minutes each, but Pika's Travis/OSX build ends up taking almost 8 minutes due to the installation overhead of python and rabbitmq/erlang, which is probably not the best use of Travis-CI's resources, either.

Other than that, very pleased with the offering. Travis is a huge boost to the stability of Open Source projects.
