### ISSUE TITLE
Retry logic needed for "addons: apt: packages"

### ISSUE THREAD

**Issue by ruslo** [travis-ci/travis-ci#5942]
Since on containter-based linux machines used "addons: apt: packages" directives to install stuff there is no way to control number of retry attempts on network failure (i.e. I can't add `travis_retry apt-get ...`). It would be nice to have this from the box. Log example:
- https://travis-ci.org/ruslo/polly/jobs/124364616

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-build/pull/605
