### ISSUE TITLE
Very slow access to Ubuntu's precise PPA from GCE

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#5944]
Identical simple `apt-get` jobs dog-slow on GCE, just fine on legacy: https://travis-ci.org/ribasushi/travis-slow-apt/builds/124963804

**Comment by ribasushi** [comment]
This has been the case for ~24 now (started morning UTC Apr 21st)

**Comment by solarce** [comment]
I see you're using archive.canonical.com as the repository and, unfortunately, there's very little we can do about the performance of those servers and the network connectivity in between them and our compute environments.

We are looking into how we could provide caching and mirror of apt repos, inside our own compute infrastructures, but do not have ETA on that at this time.
