### ISSUE TITLE
Not using the right android build tools version for one build before the change.

### ISSUE THREAD

**Issue by michaelzangl** [travis-ci/travis-ci#5946]
Today we experienced an odd issue:

This is the travis config of said build (was working fine before...):
[.travis.yml](https://github.com/jsettlers/settlers-remake/blob/f5e8ba7e9a39d8c82ac8ffffc2acba274ca32282/.travis.yml)
The only change was to comment out caching - this should not have any effect since we are running with sudo:true. 

That build complained about a wrong Android version:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':go.graphics.android'.
> failed to find Build Tools revision 23.0.3
```

[full log](https://travis-ci.org/jsettlers/settlers-remake/jobs/124987527)

We changed the Android version to 23.0.3 one build after this one (both in travis and in the build.gradle files):
[.travis.yml](https://github.com/jsettlers/settlers-remake/blob/0b9c7970/.travis.yml), [full diff](https://github.com/jsettlers/settlers-remake/commit/0b9c797095bcef8555ff2a773e6cf40b8b191809#diff-354f30a63fb0907d4ad57269548329e3)

Why was travis attempting to use the new build tools version for the old commit? Working around this is easy - it works now and worked before. But it is still a bit confusing...

**Comment by BanzaiMan** [comment]
If the removal of the cache made the build fail, it means that your dependency resolution was reliant on finding whatever is in the cache.

My guess is that Gradle looks for the latest version (23.0.3 at the time the build failed) if the dependency is not met. When you had the cache, 23.0.1 was sufficient to satisfy whatever your project's requirements. Without the cache, you need the latest version.

**Comment by michaelzangl** [comment]
Yes, it might have something to do with the cache.

At that time, the branch was in sync with master. So this build should have the same problem - if it would be a problem of a missing cache.
https://travis-ci.org/jsettlers/settlers-remake/jobs/124987515

What I could not retrace yet is the exact revision the failed job used. It only did:
```
git fetch origin +refs/pull/358/merge
```
My guess is that the PR was updated while the build was running. So a build of the new revision was attempted but the old travis.yml was used. So the problem seems to be that not the right source code was used for building. Travis would need to specify the exact revision to use when doing the `git checkout -qf`
