### ISSUE TITLE
Is there a way we can create a GitHub deployment after_success?

### ISSUE THREAD

**Issue by sunildias-engg** [travis-ci/travis-ci#5947]
Is there a way we can create a GitHub deployment after_success? or after_success travis can notify to the webhook which is configured in GitHub at organization level?

**Comment by BanzaiMan** [comment]
For creating a GitHub deployment, simply set up a GitHub token, then send a POST request to the appropriate endpoint. https://developer.github.com/v3/repos/deployments/#create-a-deployment

**Comment by sunildias-engg** [comment]
Why dont we have it as one of a GitHub provider? Is there any future requirement like that?

**Comment by BanzaiMan** [comment]
We welcome your contribution to https://github.com/travis-ci/dpl!

**Comment by BanzaiMan** [comment]
I should also mention that `after_success` is completely up to the user.

**Comment by BanzaiMan** [comment]
Here's a simple `after_success` section to create a deployment:

```yaml
after_success:
  - 'curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" -d "{\"ref\":\"$TRAVIS_COMMIT\", \"required_contexts\":[]}" https://api.github.com/repos/${TRAVIS_REPO_SLUG}/deployments'
```

Verify that `$GITHUB_TOKEN` has the correct scope, and you send a reasonable payload according to the API document.

I'm going to close this issue now.
