### ISSUE TITLE
mongodb: unrecognized service

### ISSUE THREAD

**Issue by marcolenzo** [travis-ci/travis-ci#5948]
When adding `docker` as a service to my build `mongodb` service becomes unrecognized. It is like a different image is pulled that does not have mongodb installed.

```
sudo service mongodb start
mongodb: unrecognized service
sudo service docker start
start: Job is already running: docker
```

This is the link to a sample log.

https://api.travis-ci.org/jobs/125195774/log.txt?deansi=true

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/trusty-ci-environment#Data-Stores

We forgot to mention MongoDB in that document.

Use

```yaml
group: edge
```

**Comment by marcolenzo** [comment]
Thank you. That worked.

**Comment by GregorioDiStefano** [comment]
Seems like this no longer works, mongodb was upgraded to 3.2.8 and now the service is not recognized.

**Comment by jme783** [comment]
+1, is there a workaround for this?

**Comment by GregorioDiStefano** [comment]
I'm manually starting "mongod", but according to travis-ci support, your
can drop the "edge" group.

On Aug 10, 2016 9:58 PM, "Jeff Eiden" <notifications@github.com> wrote:

+1, is there a workaround for this?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/travis-ci/travis-ci/issues/5948#issuecomment-238985163>,
or mute the thread

**Comment by rubydev** [comment]
What is manual start?
Long time this configuration worked well:

<pre>
sudo: false
language: ruby
bundler_args: "--without development --deployment"
cache:
  bundler: true
rvm:
  - 2.3.1
services:
  - docker
  - redis-server
env:
  global:
    - RAILS_ENV=test
    - SPEC_OPTS="--color --profile"
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
before_install:
  - gem install bundler
  - bundle config --global jobs 8
before_script:
  - mongo --version
  - cp .env.example .env
  - bundle exec rake db:seed
  - bundle exec rake db:mongoid:create_indexes
script:
  - bundle exec rspec
</pre>

I want mongo 3.0.8. But any version will be Ok now. How can I fix it?

**Comment by BanzaiMan** [comment]
`sudo service mongod start` (for Mongo 3.x)

```yaml
addons:
  services:
    - mongod
```

might also work (in which case adding `apt` sources and packages is unnecessary).

Mongo appears to have changed the name, so our document is not up to date here. (We might also work to recognize `mongodb` as the service name and start `mongod` when appropriate, too, in the future.)

**Comment by rubydev** [comment]
How can I start specific version of MongoDB?

**Comment by BanzaiMan** [comment]
@rubydev You'll have to manually set up your apt repository, remove the pre-installed version, then re-install it.
