### ISSUE TITLE
Travis does not build HEAD of PR

### ISSUE THREAD

**Issue by Flamefire** [travis-ci/travis-ci#5949]
I have a lengthy PR to which I post more and more commits. However at some point travis started building always the same, old commit: https://travis-ci.org/Return-To-The-Roots/s25client/builds/125222024

**Comment by BanzaiMan** [comment]
Are you sure about that?

The last 2 commits to https://github.com/Return-To-The-Roots/s25client/pull/451 are https://github.com/Return-To-The-Roots/s25client/pull/451/commits/79a098ebd7915ac69520c7ba579af731a1c6f636 (penultimate) and https://github.com/Return-To-The-Roots/s25client/pull/451/commits/380ae9c7319aac46c66e379d52d45e9b6e8c3676 (last).

For https://github.com/Return-To-The-Roots/s25client/pull/451/commits/79a098ebd7915ac69520c7ba579af731a1c6f636, we ran https://travis-ci.org/Return-To-The-Roots/s25client/builds/125089844, which is for this merge commit https://github.com/Return-To-The-Roots/s25client/commit/c41806da8c1cda3d5d4697fe2b25f42df71f824e (Return-To-The-Roots/s25client@ef04f3a + Return-To-The-Roots/s25client@79a098e).

And for https://github.com/Return-To-The-Roots/s25client/pull/451/commits/380ae9c7319aac46c66e379d52d45e9b6e8c3676, we ran https://travis-ci.org/Return-To-The-Roots/s25client/builds/125222024, which is for this merge commit https://github.com/Return-To-The-Roots/s25client/commit/4a8e6966dcd90fedfc14bf1192fd7fbf7cc24630 (Return-To-The-Roots/s25client@ef04f3a + Return-To-The-Roots/s25client@380ae9c).

These merge commits are clearly different, and reflect the newest commits to the PR.

What gave you the impression that we are building the same commit?

**Comment by Flamefire** [comment]
Ok it seems, that it worked. Well I made a commit and checked the linked build (coming from the PR) and have seen references to a line I removed in the last commit. However I either confused something or it works now and was just a display bug. Nevermind, thanks for checking
