### ISSUE TITLE
Versions of services

### ISSUE THREAD

**Issue by sadovnikov** [travis-ci/travis-ci#5950]
It is currently possible to install docker by adding `services` statement to `.travis.yml` file. However the version of the installed service will be fixed. It would be great if it becomes possible to specify version of the service to install. If the requested version is supported, the generated script will install it. 

Something like 

```
services:
  - docker=1.9.1
```

or (leaving logic of using environment variable to the installer of docker service)

```
env:
  global:
    - DOCKER_VERSION=1.9.1  # Install Docker version 1.9.1
services:
  - docker
```

More details are in https://github.com/moul/travis-docker/issues/38#issuecomment-209260158

**Comment by oryband** [comment]
Yes please. Anything new with this?
