### ISSUE TITLE
sort in swift is inconsistent between xcode7.3 (locally vs with travis-ci)

### ISSUE THREAD

**Issue by r0fls** [travis-ci/travis-ci#5953]
Here is what travis tells me:

    missing argument for parameter #1 in call
                let sorted_data = tosort.sort()

And here is what my local machine tells me (after adding a function `greatest` that compares elements):

    error: argument passed to call that takes no arguments
                let sorted_data = tosort.sort(greatest)

I have Xcode version 7.3 and have also set it to that version in my `travis.yml`. Is 7.3 not supported yet?

**Comment by BanzaiMan** [comment]
Did you use the `osx_image: xcode7.3`? The default Xcode version right now is 6.1. https://docs.travis-ci.com/user/languages/objective-c#Supported-OS-X-iOS-SDK-versions

**Comment by r0fls** [comment]
Yes, though I could be doing something else wrong with the setup. Here is my .travis.yml:

    language: swift
    osx_image: xcode7.3

    script:
            - xcodebuild
            - xcodebuild test -scheme SwiftStats

And here is the project:
https://github.com/r0fls/swiftstats

Thank you for the help

**Comment by r0fls** [comment]
@BanzaiMan I'm thinking it may be the Swift version that is messed up, but I can't get the travis log to tell it to me.

**Comment by BanzaiMan** [comment]
You mean the language version?

```sh-session
$ swift --version
Apple Swift version 2.1 (swiftlang-700.1.101.6 clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
```

**Comment by r0fls** [comment]
Yes, that's what I was looking for. My Mac says the swift version is 2.2 so maybe that's what's causing the discrepancy.

**Comment by BanzaiMan** [comment]
The one on `xcode7.3` shows:

https://travis-ci.org/BanzaiMan/travis_production_test/builds/125894733#L266

```sh-session
$ swift --version
Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
Target: x86_64-apple-macosx10.9
```

**Comment by r0fls** [comment]
Ok that is nice, but now I'm back to square one in terms of ideas...

**Comment by r0fls** [comment]
My latest thought is it's a Linux vs Mac thing. Why I think that is from here: https://bugs.swift.org/browse/SR-530. Or it's an outdated OS X image on the travis vm. I think it's beyond my control though, so I guess I'll just wait to do this until the swift compiler becomes more consistent (probably never, sorry mac geeks). I'm just saying, if my comp says I'm using version 2.2, and so does travis, that's pretty weird. Also weird that swift makes you go to Jira to look at their bugs -- I like the wholly integrated Github workflow much better. I'm going to leave this issue open, since I think it still exists, but also just move on with my life, because I think it's out of my control.

Thanks again @BanzaiMan for the help! You're awesome.

**Comment by BanzaiMan** [comment]
Whoa. That's a rather unfortunate bug.

I think we'll close this one here, but if you think we can be of further help, do let us know.
