### ISSUE TITLE
Choose an old Dart version

### ISSUE THREAD

**Issue by xavierhainaux** [travis-ci/travis-ci#5960]
I would like to run my build on a specific Dart version until I explicitly choose to upgrade to the new Dart version.
Dart 1.16 has some breaking change and we need some times to upgrade.

If I specify an old version in the travis.yml. Like:
`dart: "1.15.0"`

It prints an error: 
```
Installing Dart
Only 'stable' and 'dev' can be used as dart version for now
```

@a14n, @devoncarew and @sethladd

**Comment by a14n** [comment]
It will be possible after the merges of kevmoo/travis-build#1 (and travis-ci/travis-build#686 afterwards).

@kevmoo could you take a look at kevmoo/travis-build#1 ?

**Comment by kevmoo** [comment]
@a14n done, rebased, force pushed – hopefully we can get our travis friends to jump on it

**Comment by a14n** [comment]
Thanks @kevmoo

**Comment by a14n** [comment]
Now that travis-ci/travis-build#686 is merged. You should be able to choose an old version soon (once deployed in prod).

**Comment by xavierhainaux** [comment]
Thank you very much @a14n . I'm closing this issue now and wait for the deployment :-)

**Comment by a14n** [comment]
Deployed \o/
