### ISSUE TITLE
SCons not working when using testing against python 3

### ISSUE THREAD

**Issue by arecarn** [travis-ci/travis-ci#5961]
I'm using SCons to run my tests and lint for a python project. The project is tested against Python versions 3.3, 3.4, and 3.5, with the following in my .travis.yml
```yaml
python:
  - "3.3"
  - "3.4"
  - "3.5"
```

When SCons is invoked wtih my setup target:
```yaml
install: scons setup
```
I get the following error:
```
$ scons setup
scons: *** SCons version 2.1.0 does not run under Python version 3.3.5.
Python 3.0 and later are not yet supported.
```

It seems I'm getting this error since version 2.1.0 of SCons only works with Python 2, but since travis uses a python3 virtualenv python 2 is not available. I would SCons to just use the system Python 2 to run SCons instead of the virtualenv Python 3.

here is the relevant build failure https://travis-ci.org/arecarn/dploy/jobs/126148761

**Comment by BanzaiMan** [comment]
Try activating Python 2 virtualenv just for the duration of your `scons` invocation.

For example:

```yaml
install:
  - source virtualenv/python2.7/bin/activate
  - scons setup
  - source virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
```

**Comment by arecarn** [comment]
Inside my SCons targets I am running pip, pytest, and pylint. Wouldn't changing the virtualenv change the python used for these commands?

**Comment by BanzaiMan** [comment]
It might. I don't know how SCons is supposed to work.

You might be able to invoke `scons` with the version of Python provided on the system (`/usr/bin/python`) to get around it. See https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image if you'd like a more interactive environment to test your build.

**Comment by BanzaiMan** [comment]
Is there anything for us to do here?

**Comment by arecarn** [comment]
I found that using the system python won't work because I'm using the virtualenv pylint. Past that I haven't looked into the issue much further myself and had have switched back to using make instead of SCons. It might be that the SCons project has resolved this issue in a later version, but I haven't tried that out on the interactive environment.

I probably won't be looking into this for the foreseeable future either since make gets the job done. I'll leave it up to you to close this.Thanks for your help.

**Comment by BanzaiMan** [comment]
Thanks for the update. I'm closing this for now.
