### ISSUE TITLE
Build time doesn't start a 0s

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#5962]
Looks like the build time for Travis CI builds starts at around 2min 50secs. However, the real build time should start at 0s not factor in some other weird pre-build steps.

<img width="1554" alt="screen shot 2016-04-27 at 15 04 33" src="https://cloud.githubusercontent.com/assets/3019665/14864699/0ab3b276-0c89-11e6-9a51-830efa639fb6.png">

**Comment by BanzaiMan** [comment]
Could you show with examples what you mean?

**Comment by jakirkham** [comment]
It's a bit hard to without having a build that is just starting to show the discrepancy.

**Comment by jakirkham** [comment]
Added a screenshot above. I tried to take it as soon after it started as possible.

This seems to happen for all platforms. This one is on standard non-`sudo` Linux.

**Comment by BanzaiMan** [comment]
I had another look at this issue, but I am sure that this is not the case. The counter should start when the build VM has finished booting and we send the build script to it. If you see the counter not reflecting the elapsed time, maybe the live updates of the logs had stopped. Try reloading the page if you see this again.

**Comment by jakirkham** [comment]
> ...maybe the live updates of the logs had stopped.

That wasn't the case as refreshing still showed time that was off by the same amount. Though there is little I can do to help you debug this further so it is really in your hands at this point.
