### ISSUE TITLE
Config file exists but branch isn't started because missing config file

### ISSUE THREAD

**Issue by congdanhqx** [travis-ci/travis-ci#5964]
Hi,
I'm working on this branch https://github.com/congdanhqx/numberstringify/tree/travis_on_osx
however, Travis CI can't start the build because `missing config` although that config file exists at https://github.com/congdanhqx/numberstringify/blob/travis_on_osx/.travis.yml

![missing](https://cloud.githubusercontent.com/assets/2434885/14879445/88eb32fc-0d53-11e6-98e8-826195e14c20.PNG)

**Comment by congdanhqx** [comment]
![image](https://cloud.githubusercontent.com/assets/2434885/14879618/707290ac-0d54-11e6-8b98-25dd5f630bd1.png)

By this time, I created new branch from master, modified `.travis.yml` then committed and pushed it to GitHub, Travis CI still say `missing config`.

Thanks,
~Danh

**Comment by BanzaiMan** [comment]
The [`.travis.yml` file](https://github.com/congdanhqx/numberstringify/blob/12c99afc16b385535686405e4623fb71b7a977d4/.travis.yml) in question has a syntax error. Please fix it.

The message is misleading, and I have a fix to roll out to make this better.

**Comment by congdanhqx** [comment]
I believe there is a bug in yml validation tool.
It always reports
>did not find expected '-' indicator while parsing a block collection matric.include at line 8 column 5

But the character in line 8 column 5 is really a minus sign `'-'`. This problem was fix by copy the line
>-os: linux

from another object to it.

Could you please give it a check?

**Comment by BanzaiMan** [comment]
It is not a bug at all.

The indentation levels of the items in the sequence under `matrix.include` are inconsistent. In other words, delete 1 space each from lines 20 through 26, and it will be valid YAML.
