### ISSUE TITLE
Deployment to Bintray fails with error code 400

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#5967]
Uploading of debian package to Bintray fails with response code 400 (bad request)

Expected result: deployment should not fail.

Log:
https://travis-ci.org/igagis/stob/jobs/126355776

It was working before, here is the example of successful deployment in February:
https://travis-ci.org/igagis/stob/jobs/109624899

**Comment by BanzaiMan** [comment]
I'm consolidating this with #5966.
