### ISSUE TITLE
Random build failures always pass when re-building

### ISSUE THREAD

**Issue by rajohns08** [travis-ci/travis-ci#5969]
Below is a log for one of the random failures for an iOS build using the following build command:

```
xcodebuild -project JudgecardXSwift.xcodeproj -scheme JudgecardXSwift -destination "platform=iOS Simulator,name=iPhone 6s,OS=latest" test build
```

Log file: [log.txt](https://github.com/travis-ci/travis-ci/files/241698/log.txt)

**Comment by BanzaiMan** [comment]
Email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.
