### ISSUE TITLE
"ldc-latest-unstable"...etc compilers?

### ISSUE THREAD

**Issue by Abscissa** [travis-ci/travis-ci#5970]
Not sure how much work this would be or if it would even be a good idea, but should there be a way to ask travis (in .travis.yml) for the latest dmd/ldc/gdc compiler *including* alphas/betas, similarly to how saying "dmd"/"ldc"/"gdc" gets the latest stable release?

Ping @ibuclaw @klickverbot @MartinNowak

**Comment by MartinNowak** [comment]
The install.sh script already supports `dmd-beta`, see https://github.com/travis-ci/travis-build/issues/717. I guess ldc, and gdc support will follow at some point.
