### ISSUE TITLE
linux environment is too old

### ISSUE THREAD

**Issue by burlen** [travis-ci/travis-ci#5972]
In the 14.04 lts env, we're having to use all kind of ppa and do manual software installs to get our builds going. this is way too much effort. do you have eta of a newer linux environment? generally speaking, in lts releases packages are too old, please use regular ubuntu releases or better still, fedora, which does a better job of providing newer versions of packages.

Thanks
Burlen

**Comment by solarce** [comment]
While we can understand the need for some folks to have the newest stuff, building and maintaining our image library, while also ensuring it's usable for the 250,000+ jobs we run each day is a unique challenge.

Given that, we are currently focused on support 12.04 and 14.04 as our primary environments. At the moment, it is unlikely that we'll be supporting 16.04 as a native environment this year.

If you're particular use cases require something newer, I would encourage you to use utilize our Docker support, as Hiro mentioned, which would allow you run your build inside a Docker image of a newer Ubuntu release. While the start up times are slower than our countainer-based builds, you get a full VM with 7.5GB of RAM, for each build.

Regards,
Brandon Burton
Infrastructure Manager

**Comment by burlen** [comment]
so yes docker is great. I wasn't aware of the docker support. on the flip side, it's yet more work that I don't have time for. It's been a ton of work figuring out all the peculiar stuff you guys have done to the default environment.  eg, python 2.7 install  off in opt, or really old/broken versions of stuff (eg git-lfs). We would have been way better off starting with docker containers.

In theory I'm in love with travis, in practice I'm finding travis is ending up being more work than maintaining our own set of build slaves. Just sayin' since your value add is supposed to be "this just works".
