### ISSUE TITLE
Some languages are not correctly routed to GCE Trusty

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5973]
Some languages are not properly routed to GCE Trusty when specified:

```yaml
sudo: required
dist: trusty # or services: [ docker ]
```

Previously reported:

* `smalltalk`: https://github.com/travis-ci/travis-ci/issues/5262
* `android`: https://github.com/travis-ci/travis-ci/issues/5370

**Comment by BanzaiMan** [comment]
There is also a report of the same issue with `haskell`.

**Comment by BanzaiMan** [comment]
These languages should work with Trusty now.

I'm going to leave this open for a little bit, in case there are others we missed.

**Comment by BanzaiMan** [comment]
Closing this now.

**Comment by fniephaus** [comment]
@BanzaiMan could you reopen this or #5262.
It's actually the other way around:
When `sudo` is required, I get trusty by default, even though precise is requested.
[Here's an example](https://travis-ci.org/fniephaus/vm/jobs/172979140):
```
Build language: smalltalk
Build group: stable
Build dist: precise
Build id: 172979138
...
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

**Comment by BanzaiMan** [comment]
@fniephaus We are making some changes, so the recent issue should be separate. Thanks.

**Comment by fniephaus** [comment]
@BanzaiMan Shall I open a new issue then instead?

**Comment by BanzaiMan** [comment]
@fniephaus Yes, please.
