### ISSUE TITLE
CRAN check not as-cran, misses bad URLs

### ISSUE THREAD

**Issue by shabbychef** [travis-ci/travis-ci#5974]
I have recently had some bad experiences pushing packages to CRAN which seem to pass on travis.  For example, the `dev` branch of `BWStest` [tested here](https://travis-ci.org/shabbychef/BWStest/jobs/126822890) should probably fail for `R-devel` with the error (or NOTE)

```
Found the following (possibly) invalid URLs:
  URL: http://www.thiswebsitedoesnotexistatallreally.com/
    From: README.md
    Status: Error
    Message: libcurl error code 6
        Could not resolve host: www.thiswebsitedoesnotexistatallreally.com
```

In my local homebrew docker CRANcheck experiments, I also have a hard time getting URL checks. Perhaps `curl` or `libcurl` support are not built in?

(Obligatory: mention @craigcitro, @hadley and @jimhester in the issue.)

**Comment by hadley** [comment]
This is because the URL checks (which we want) are part of the version number checks (which we don't want). 

You should be testing with release() or build_win() prior to CRAN submission to avoid such problems.

**Comment by shabbychef** [comment]
I see. Is this set by `_R_CHECK_CRAN_INCOMING_=FALSE` (per this [issue](https://github.com/craigcitro/r-travis/issues/105)) or is there another environment variable responsible?

**Comment by hadley** [comment]
Yes that's right
