### ISSUE TITLE
travis docker images published indicate a large number of security vulnerabilities

### ISSUE THREAD

**Issue by gliptak** [travis-ci/travis-ci#5977]
An example is at:

https://quay.io/repository/travisci/travis/image/42bb82e5066961b3da6a3a3154a222e41010da67c46a0d61e643d9d07a0b99b2?tab=vulnerabilities

**Comment by BanzaiMan** [comment]
Thanks for the report.

These images are old, and they will be updated in due time.

Furthermore, they are not used in public-facing servers, so it is less of a concern at this time.
