### ISSUE TITLE
Travis deploy GAE: Deployment failed

### ISSUE THREAD

**Issue by abdonrd** [travis-ci/travis-ci#5978]
Since a week ago, GAE deploy doesn't work.
I share one of my [.travis.yml](https://github.com/abdonrd/abdonrd.com/blob/develop/.travis.yml).

```
ERROR: (gcloud.preview.app.deploy) Error Response: [13] Errors were encountered while copying file to App Engine.
```

<img width="889" alt="screen shot 2016-05-02 at 01 11 43" src="https://cloud.githubusercontent.com/assets/1007051/14944922/3a104a02-1003-11e6-8374-c7f6a57d3b90.png">

**Comment by BanzaiMan** [comment]
We did release dpl 1.8.15 a few days ago. You can see the changes here: https://github.com/travis-ci/dpl/compare/v1.8.14...v1.8.15 (Also see https://github.com/travis-ci/dpl/pull/410)

Other than that, I am not sure how this change can explain the failure you are showing.

**Comment by abdonrd** [comment]
GAE Issue 784: https://code.google.com/p/google-cloud-sdk/issues/detail?id=784

**Comment by BanzaiMan** [comment]
OK. I'm closing this as an upstream issue.
