### ISSUE TITLE
Test hangs on Travis, but works on CircleCI

### ISSUE THREAD

**Issue by chrisfilo** [travis-ci/travis-ci#5979]
We have one test that hangs (no output for 10 minutes) on Travis, but works well on Circle CI.

This is the test: https://github.com/nipy/nipype/pull/1372/files#diff-8daac0ee3ab98320723ea88796b9edd4R37

(the underlying code uses psutils - maybe this is the problem?)

CircleCI log: https://circleci.com/gh/nipy/nipype/1139

Travis log: https://travis-ci.org/nipy/nipype/jobs/126402644

Related to: https://github.com/nipy/nipype/pull/1372

**Comment by BanzaiMan** [comment]
Does this happen consistently? If so, does the build stops at the same place when it does?

**Comment by chrisfilo** [comment]
Yes and yes!

**Comment by BanzaiMan** [comment]
That's good news. Could you send email to support@travis-ci.com? We'll set you up with a debug VM.

**Comment by Osis** [comment]
+1! Started happening when I bumped to 7.3. Been trying all the tips in various issues with no success.

**Comment by BanzaiMan** [comment]
We have provided access to a debug VM. I'm closing this now. If there is anything further to do on our end, do let us know.
