### ISSUE TITLE
Trusty image hangs on "booting"

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#5980]
Doing some build testing with hhvm on the trusty image. Every build with trusty is hanging and sometimes restarts.

It always hangs on "booting" sometimes it takes **over an hour** for the build to even start. Once started it may or may not stop after 2-3 minutes and resets to booting.

https://travis-ci.org/photodude/joomla-cms/jobs/127258193

**Comment by BanzaiMan** [comment]
Sorry about the issue. I think the issue (on the backend) is resolved now, so I'm closing this.

**Comment by photodude** [comment]
Now it just seems to be a broken record in the following sequence que→create→booting→repeat

sometimes the booting will move on to the build phase, but then it will restart and reboot, even after completing the build.

**Comment by photodude** [comment]
@BanzaiMan Builds are hanging on booting again.

**Comment by jourdanrodrigues** [comment]
+1.

It's taking too long to start (when it finally does) and a message just showed in the build page: "There was an error while trying to fetch the log.".

**Comment by photodude** [comment]
@jourdanrodrigues I would suggest opening a new issue now that trusty is out of beta.
