### ISSUE TITLE
Skipping a deployment with the bintray provider because this branch is not permitted

### ISSUE THREAD

**Issue by Zenexer** [travis-ci/travis-ci#5981]
I can't find any explanation for this error:

```
Skipping a deployment with the bintray provider because this branch is not permitted
```
- [.travis.yml](https://github.com/massbay-cs/cs225-proj4/blob/v0.2.0/.travis.yml)
- [Branch build](https://travis-ci.org/massbay-cs/cs225-proj4/builds/127267719) (works)
- [Tag build](https://travis-ci.org/massbay-cs/cs225-proj4/builds/127267750) (doesn't work)

Because `deploy.*.on.tags: true`, branches shouldn't be considered, right?  Per [the documentation](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A):

> tags: When set to true, the application is deployed when a tag is applied to the commit. This causes the branch condition to be ignored.

Tags have no branch information attached to them, so I'm not sure how it could use a branch condition even if it wanted to.

It's definitely detecting the tag; the name of the build is the name of the tag, rather than the name of the branch.  Also, when it's a normal branch build, it gives a different warning stating that it's skipping tag-only providers.

I'm demonstrating various deployment options to a college class, hence the use of multiple providers.

**Comment by BanzaiMan** [comment]
Could you try removing this `bintray` provider definition: https://github.com/massbay-cs/cs225-proj4/blob/v0.2.0/.travis.yml#L28-L38 (namely, the one with out `on.tags: true`) and push a tagged commit?

**Comment by Zenexer** [comment]
Sure.  I'm working on something else at the moment, but I'll add that to my to-do list.
