### ISSUE TITLE
Perl 5.22 builds failing

### ISSUE THREAD

**Issue by Grinnz** [travis-ci/travis-ci#5984]
Builds for perl 5.22 are failing to install/switch to the perl version consistently as seen below, the errors don't really indicate what the issue is:

https://travis-ci.org/Grinnz/Mojo-JSON-MaybeXS/jobs/127345364

**Comment by BanzaiMan** [comment]
Sorry about the issue. We had a bad deploy that triggered this issue. We deployed a fix about 20 minutes ago. Please rerun the failing build(s).
