### ISSUE TITLE
Secure variables are using old values, ignoring .travis.yml

### ISSUE THREAD

**Issue by certik** [travis-ci/travis-ci#5985]
Steps to reproduce:

1) Generate a testing private variable `DEPLOY_TOKEN=xyz6`:

```
$ travis login --github-token=MY_PERSONAL_TOKEN
$ travis encrypt -r certik/planet-sympy -i --debug DEPLOY_TOKEN=xyz6
** Loading "/home/swuser/.travis/config.yml"
** Loading gh
** GET "config"
**   took 0.25 seconds
** GitHub API: HEAD /repos/certik/planet-sympy
**   took 0.35 seconds
** GET "repos/certik/planet-sympy"
**   took 0.26 seconds
** GET "repos/8421499/key"
**   took 0.27 seconds
** Storing "/home/swuser/.travis/config.yml"
Please add the following to your .travis.yml file:

  secure: "td47Svup3SvnOFxYkWkt1fTdHSiBCbQtitppp4LVm5R2wi8cxxpDYhWf55l/1XcrcQpsIT84SJ5Y8a4qysiCiULR0z7K4VolDtmFIIpbpub9X0AcrXH4wU0lR09gV8vz8TwV0iGrdwx9KTGfRb6psCTuC28F5PfhANaC8biUJmI0ZmTw8sb0qaVTObwcPocMx7dfbeug73JiihC/4wQIC7ehBQyiPyK8v3piVwocj4ovsYAGTDTYlzd83VV4TiNpwuWgzpaRfJhb9vABp+PHOs8XgdZmE0D2aodF0W+3y89qdrfvr32B8OOTvZTnF5dcCztprUEMsQFwhIJbcphpwodyk+qYSSPnmz4NxsW9E1kMqTwjKnfRhYpxF26WMxMhj0yec420TZfPML3oikYxOdgBb0dLktYcQPcRWg/PK6/+BX8q2rW4CmR/8/RjQT2o6oJlJCAHUQqyLEuWFNLe2kCLIJGblgp5MRLw3M3bUrPb0vdnhXvZBQW9yhuOj+XY1Fetz61MTsVvUjRKtiP8JQWL+Io0t7wGre1OOmTfQDhV0+ryBcfCJYzL2DYWDWvgXv5VlhXDWNLQMrehssA0PaKsFWk2kKGnH7JjdMqB8PSvlSVKkmEE5BIeWhJ+pc7i/u6ukUDwVyjnmsx+t92h35c9Nur49++7syhGRTBggHY="

Pro Tip: You can add it automatically by running with --add.
```

2) Put this `secure` string into `.travis.yml` in this commit: https://github.com/certik/planet-sympy/commit/ae2105ca15372b177520452319eaaaa27674b5b3

3) look at the result of a build on Travis-CI: https://travis-ci.org/certik/planet-sympy/builds/127368279, the top of the file contains:
```
$ export DEPLOY_TOKEN2=else15
$ export DEPLOY_TOKEN=[secure]
```
as it should. Then I print the `DEPLOY_TOKEN` further down: https://travis-ci.org/certik/planet-sympy/builds/127368279#L675:
```
+ echo DEPLOY_TOKEN=xxy
DEPLOY_TOKEN=xxy
```
As you can see, `DEPLOY_TOKEN` is equal to `xxy` (which was an old value I used before), and not the correct current value of `xyz6`, set above.

Any ideas what is going on? How do I force it to use the new value from `.travis.yml`? How do I delete the old value?

**Comment by BanzaiMan** [comment]
https://travis-ci.org/certik/planet-sympy/builds/127368279#L619 shows that you are assigning the value `GITHUB_TOKEN` to `$DEPLOY_TOKEN`. Did you mean it? Did you perhaps mean `$GITHUB_TOKEN` instead?

**Comment by certik** [comment]
Ha, I am so stupid! Thanks a lot for this tip. I am assigning an undefined
variable, and Travis must be providing some old value for it. I will try
the fix and report back.

**Comment by certik** [comment]
@BanzaiMan that was it. I fixed it in https://github.com/certik/planet-sympy/commit/a7ac763247da1e44065a99dcbca0216e94e95e39, here is the corresponding build that passes the variable correctly: https://travis-ci.org/certik/planet-sympy/builds/127427964

I am sorry for opening this issue. I spent several hours on this today and I couldn't figure it out.

Thanks for your help.

**Comment by BanzaiMan** [comment]
@certik Happy to hear that you were able to solve it. :-)
