### ISSUE TITLE
PHP 7.0.4

### ISSUE THREAD

**Issue by krakjoe** [travis-ci/travis-ci#5988]
Please can we get an upgrade to 7.0.5, or preferably 7.0.6 (recently released).

7.0.4 has a stupid problem in headers that is causing all ext builds against 7.0 to fail, if they include some part of SPL.

https://travis-ci.org/krakjoe/sysconf/jobs/127472711

**Comment by BanzaiMan** [comment]
We've build 7.0.5 and 7.0.6 for Precise and Trusty.
