### ISSUE TITLE
Android Build fails android-update-sdk command not found

### ISSUE THREAD

**Issue by Blackclaws** [travis-ci/travis-ci#5990]
We didn't change anything in our travis.yml but suddenly builds start failing not because of code changes but because of the dependencies of our build.

As explained in: https://docs.travis-ci.com/user/languages/android we have added android as language

language: android
sudo: required
group: stable
dist: trusty
services:
        docker
android:
        components:
                - build-tools-23.0.3 # Specify your build tools verison
                - android-23 # Android Platform Target

We now get the error:

Installing Android dependencies

0.35s$ android-update-sdk --components=build-tools-23.0.3

android-update-sdk: command not found

The command "android-update-sdk --components=build-tools-23.0.3" failed and exited with 127 during .

Full Build History: https://travis-ci.org/Amos2016GroupOne/amos-ss16-proj1/builds

Something broke apparently between 6 to 3 days ago and it wasn't our code.

**Comment by BanzaiMan** [comment]
This is a fallout from #5973, which fixed the Android Trusty build routing issue. It looks like the Trusty stable image doesn't have the Android tools available.

The build is failing because we do not support Android on Trusty at the moment (https://github.com/travis-ci/travis-ci/issues/5370).

Use Precise for now.

```yaml
language: android
sudo: required
dist: precise
```

**Comment by Blackclaws** [comment]
@BanzaiMan  Thanks for the help and sorry for the duplicate issues.

**Comment by noamtamim** [comment]
Trusty is the default now, and all Android builds are failing!

**Comment by MariadeAnton** [comment]
@noamtamim Thanks for reporting, Noam -  we do have an Android Trusty image available on beta with newer services and tools that you can start testing out - would you drop us a line at support@travis-ci.com to get more details and see how we can help you?

Alternatively and to keep things as they were, please add `dist: precise` to your `.travis.yml` :)

**Comment by noamtamim** [comment]
@MariadeAnton already did that (dist: precise), but that's not a real solution, as my project has **many** branches. I hope you solve this ASAP, because our release and QA system is built on Travis.

**Comment by jaredsburrows** [comment]
@MariadeAnton Why introduce a breaking change?

**Comment by MariadeAnton** [comment]
Hi everyone, thanks for your feedback!

From now on, `language: android` images in Trusty will be sent to the Android Trusty beta to make sure this issue does not happen anymore.

If you rely on Android SDK tools previous to android-23, I'd recommend adding `dist: precise` to ensure the best performance :)
