### ISSUE TITLE
misleading build status in PR with [ci skip]

### ISSUE THREAD

**Issue by rameshthoomu** [travis-ci/travis-ci#5995]
Performed build without [CI SKIP] (Travis executed build process as expected) now, while submitting PR, in PR title I have mentioned [CI SKIP] (Travis ignored build process as expected) but when I see the status for that PR in Pull Requests tab in Git hub it's showing the latest commit build result.

This is misleading people that PR is build though we give [CI SKIP] in PR title.

Request is: Don't show latest commit build status of the PR in Pull request page.

**Comment by BanzaiMan** [comment]
Could you elaborate on what you did with actual pages if they are public? Thanks.

**Comment by rameshthoomu** [comment]
@BanzaiMan - PFA screenshot.
![travis ci skip](https://cloud.githubusercontent.com/assets/17034502/15017924/94fa320a-11e5-11e6-9d2a-e2c7f49191c9.png)

**Comment by BanzaiMan** [comment]
@rameshthoomu Do the ***commits*** associated with these PRs have `[ci skip]` in the comments? PR's title does not affect whether or not we run the builds. Individual comments do.

**Comment by rameshthoomu** [comment]
@BanzaiMan :except the first PR named as [ci skip] all other PR's have git commit with `[ci skip]`. 

Also, Can we skip PR from build process by providing [ci skip] in PR title or in body of the PR? What are the possible cases to skip PR from build process?.

**Comment by BanzaiMan** [comment]
Could you tell me where those commits are? I'm trying to help. The screenshots by themselves do not help.

**Comment by rameshthoomu** [comment]
https://github.com/rameshthoomu/fabric/pulls

**Comment by BanzaiMan** [comment]
See https://travis-ci.org/rameshthoomu/fabric/requests

In each of those PRs, those commits that have `[skip ci]` or `[ci skip]` in the commit message are skipped. Those that do not, did trigger builds, as documented.

**Comment by rameshthoomu** [comment]
@BanzaiMan:  Thanks for the answer.  I am aware that, Travis skips build process for push and PR's if there is a [ci skip] message in commit messages. But my question is, When I do a commit with out [ci skip]  Travis will build and now I want to skip this build process by providing [ci skip] in PR title or in body. Is this possible to avoid build process for PR's from github.

**Comment by BanzaiMan** [comment]
@rameshthoomu That is https://github.com/travis-ci/travis-ci/issues/5374.

**Comment by rameshthoomu** [comment]
@BanzaiMan : I am still not clear. I did a commit from without [ci skip] from my local repo on branch "x" and pushed to remote repo branch "x". Travis executed my build successfully. next step:
I made a pull Request for that commit on my remote master branch from `github` by changing the title of the PR to [ci skip]. Now, I could see Travis is building for PR. 

Can we skip PR build by giving [ci skip] in PR's title or body? I know, Travis looks for latest commit and if there is  a [ci skip] in commit message it will ignore.

If yes, can you please mention steps here.. Thank you..

**Comment by BanzaiMan** [comment]
> I did a commit from without [ci skip] from my local repo on branch "x" and pushed to remote repo branch "x". Travis executed my build successfully.

This is as expected.

> next step: I made a pull Request for that commit on my remote master branch from github by changing the title of the PR to [ci skip]. Now, I could see Travis is building for PR.

As explained in #5374 as well as here, the title of the PR has no bearing on whether or not we run the build. The commit message does. Since the head commit of the PR does not prohibit the build to run, we run the build.

What you are asking is exactly the issue addressed in #5374, and it is not currently possible.
