### ISSUE TITLE
Travis eating up disk space

### ISSUE THREAD

**Issue by svita00** [travis-ci/travis-ci#5997]
Hi,

quite often recently we are encountering issues related to disk space while building an image like:

[Composer\Downloader\TransportException] The "https://getcomposer.org/composer.phar" file could not be written to /home/travis/.phpenv/versions/5.4.37/bin/composer-temp.phar: failed to open stream: No space left on device

I checked the machine travis run on and most of the space is actually occupied by $DOCKER_HOME/aufs/diff. I'm not a docker/aufs expert but it seems it's not deleting unused image layers. 

We use the Enterprise version.
Can you please advise on this? 

Thanks,
Stefano

**Comment by solarce** [comment]
Hello @svita00 

Please email enterprise@travis-ci.com for Enterprise related questions
