### ISSUE TITLE
Multiple builds (different JDK) don't use the cache

### ISSUE THREAD

**Issue by ctubbsii** [travis-ci/travis-ci#6001]
Looking at [this build][1], for example, it's clear that the cache isn't being used for multiple builds on different JDKs. You can see that cached maven dependencies are used fine for the oraclejdk8 build, but the cache is completely ignored for the other JDKs. This results in the 10m timeout problem, probably due to stalled IO activity downloading maven dependencies.

[1]: https://travis-ci.org/apache/accumulo/builds/128105257

**Comment by BanzaiMan** [comment]
Is there a build for OpenJDK 7 that actually finishes and uploads a cache?

**Comment by ctubbsii** [comment]
[This build][1] finished all three just fine. But, are the caches really separate per JDK? For maven dependencies, I'd want the same artifacts, regardless of which JDK is building.

[1]: https://travis-ci.org/apache/accumulo/builds/124057789

**Comment by BanzaiMan** [comment]
Sorry about the confusion there.

17 days ago, there was no caching for Open Source caching. And the caching utility did not show the failure to upload back then, either. Please have a successful build on OpenJDK 7, and then reopen the issue if it persists.

**Comment by ctubbsii** [comment]
But, caching was working for us... maybe because it was an Apache (ASF) project?

**Comment by BanzaiMan** [comment]
Where did you see it working?

**Comment by ctubbsii** [comment]
Nevermind. I thought it was working because I stopped seeing the timeouts. I was wrong. It looks like the downloads just worked for awhile.

**Comment by ctubbsii** [comment]
With all the maven builds, and timeouts, it might make more sense for Maven Central to be proxied by a mirror internal to Travis infrastructure. It would probably serve as a much more efficient cache of Maven Central artifacts than a per-build cache that Maven users will be setting up.

**Comment by BanzaiMan** [comment]
We have improvements on our road map, certainly.

I don't think there is anything to do on this issue, so I'll close this.

**Comment by ctubbsii** [comment]
Thanks for taking a look. Just to clarify, do different jobs (in this case, different JDKs) within the same build have dedicated or shared caches? Similarly, do different branches each have their own cache?
(Essentially, I guess I'm asking... what's the cache key?)

If the JDK is part of the cache key (have separate caches), can I circumvent this by using the [jdk_switcher][1]?

[1]: https://docs.travis-ci.com/user/languages/java#Switching-JDKs-Within-One-Job

**Comment by BanzaiMan** [comment]
JDK version is a part of the cache name. Cache name collisions are possible. See previously reported issues: travis-ci/travis-ci#4393 travis-ci/travis-ci#3023 travis-ci/travis-ci#5460

**Comment by ctubbsii** [comment]
Interesting. So, it seems like cache is handled before and after `script`, so using jdk_switcher inside `script` should force them to share the cache, in exchange for sequential jobs rather than concurrent ones.

**Comment by ctubbsii** [comment]
If anybody could confirm that using `jdk_switcher` would allow us to reuse the same cache for multiple JDK builds, that would be helpful. Thanks.
