### ISSUE TITLE
Pusher API key is missing from https://api.travis-ci.org/config

### ISSUE THREAD

**Issue by cscott** [travis-ci/travis-ci#6002]
This is a bad configuration on your end, perhaps stemming from https://github.com/travis-ci/travis-api/commit/185244f0e7899a4d168d3c0b9ac4ba796af235ec

It seems your `pusher_ws` configuration has the literal string `"key"` in the key field, instead of the actual pusher API key (which is `5df8ac576dcccf4fd076`).  This is causing streaming to break in clients of the travis API, for example see https://github.com/travis-ci/travis.rb/issues/353 and https://github.com/cscott/npm-travis/issues/1 .

**Comment by cscott** [comment]
For example:
```
$ curl https://api.travis-ci.org/config
{"config":{"host":"travis-ci.org","shorten_host":"trvs.io","assets":{"host":"travis-ci.org"},"pusher":{"key":"key"},"github":{"api_url":"https://api.github.com","scopes":["read:org","user:email","repo_deployment","repo:status","write:repo_hook"]}}}
```
There should be an actual API key there in the `config.pusher.key` field, not the literal string `key`.

**Comment by BanzaiMan** [comment]
This should be available now.
