### ISSUE TITLE
go get without -t is run for Go tip builds

### ISSUE THREAD

**Issue by fastest963** [travis-ci/travis-ci#6003]
go `1.5` builds run `go get -t -v ./...` but when running go `tip` builds just `go get -v ./...` is run.

**Comment by BanzaiMan** [comment]
Looks like https://github.com/travis-ci/travis-build/pull/658 broke it for `tip`.

**Comment by dan9186** [comment]
I'm definitely curious about this as it seems to me the change should have not forced 1.6 vendoring, but maybe favored it over older vendoring.  As it stands now, I must include 1.6 vendoring in my repos despite the older vendoring still being valid.

Though I'm likely now going to end up trying to crafting something to validate that older and newer vendoring are both working instead.

**Comment by BanzaiMan** [comment]
Paging @paddyforan

**Comment by paddyforan** [comment]
Argh, sorry, swamped this week.

The thing that jumps out at me immediately is that the patch updated to use `Gem::Version` for version numbers, so comparisons would actually be accurate. `tip` wouldn't be parseable as a semver version number, so `comparable_go_version` would always return `0.0.1`. Which means it would default to the pre-1.2 behaviour. It seems like the solution is to just special-case "tip", like we do "go1". I'll get a patch up for it tonight.

**Comment by BanzaiMan** [comment]
@fastest963 I'm not familiar with Go; so could you confirm that on `tip`, you'd want `go get -t -v ./...`?

**Comment by paddyforan** [comment]
If I understand correctly, the situation is this:

* Before Go 1.2, when using `go get`, the dependencies for test files were not downloaded.
* In Go 1.2, the `-t` flag was [added](https://golang.org/doc/go1.2#gocmd) to `go get`, allowing you to download the test dependencies.
* [Before](https://github.com/travis-ci/travis-build/pull/658/files#diff-fe52d3b67e8fe283d39c20d2b87d82f8L132) travis-ci/travis-build#658, tip was considered a release after 1.2, meaning the flag was available to be used and so was used.
* After the change, we started trying to convert the release to a semver number that could be accurately compared. Unfortunately, 'tip' wasn't special-cased. So it returned as `0.0.1`, which suddenly meant the `-t` flag wasn't available.

So to preserve the functionality of how things worked before the change, I'm in the process of submitting a PR that changes the check from

```ruby
(go_version == 'go1' || comparable_go_version < Gem::Version.new('1.2')) ? 'go get' : 'go get -t'
```
to

```ruby
(go_version == 'go1' || (go_version != 'tip' && comparable_go_version < Gem::Version.new('1.2'))) ? 'go get' : 'go get -t'
```

Which, I believe, should make everything work the same way it did before the merge.

**Comment by paddyforan** [comment]
I've opened travis-ci/travis-build#727 to address this.

**Comment by fastest963** [comment]
@paddyforan thanks! That is a correct summary of the problem. Thanks for the quick PR to address this.

@BanzaiMan yes exactly, that's what I want. Thanks!

**Comment by BanzaiMan** [comment]
All right. This should be fixed on production now (both .org and .com).

Let us know if you encounter problems.
