### ISSUE TITLE
caching directories with space in name

### ISSUE THREAD

**Issue by bolav** [travis-ci/travis-ci#6005]
I'm trying to cache a directory with a space in it's name. I tried:

```
cache:
  directories:
    - "/Users/travis/Library/Application Support/Fusetools/"
    - "/Users/travis/Library/Application\ Support/Fusetools/"
    - "/Users/travis/Library/Application\\ Support/Fusetools/"
```

The last one is the one that looks best.

```
adding /Users/travis/Library/Application Support/Fusetools to cache
```

```
  /usr/local/Cellar/md5deep/4.4: 20 files, 1.7M, built in 33 seconds
/Users/travis/Library/Application: No such file or directory
/Users/travis/build/bolav/fuse-travis/Support/Fusetools: No such file or directory
```

But this still feels wrong. What is the correct syntax?

**Comment by BanzaiMan** [comment]
I don't think it works at the moment.

**Comment by BanzaiMan** [comment]
While fixing another bug on the caching utility, I believe I've fixed this issue, too. However, I am not quite satisfied with the way it works now.

1. Escaping the white space with `\\` is not ideal. It is not very intuitive.
1. When we detect changes in cache directories with spaces in their paths, we only show the last contiguous component without white spaces; e.g.,
```
change detected:
Support/com.apple.spotlight/foobar
```

The second point is not a huge deal, but the first needs more work to figure out how to specify the paths without `\\`.
