### ISSUE TITLE
How to do headless GUI testing with xvfb and xdotools, when wmctrl cannot list the windows?

### ISSUE THREAD

**Issue by richelbilderbeek** [travis-ci/travis-ci#6006]
# Abstract

`wmctrl -l` gives `Cannot get client list properties.` error on Travis
# Full issue

I enjoy Travis CI tremendously (shameless plug: [my Travis C++ tutorial (in progress)](https://github.com/richelbilderbeek/travis_cpp_tutorial))!

Now I am working on a [tutorial about debugging C++ GUI applications (in progress)](https://github.com/richelbilderbeek/testing_cpp_gui_applications_tutorial) and I'd like to use `xdotools` for manipulating windows, like sending key presses and mouse clicks. 

On my local computer all scripts are tested to work correctly, and I'd like to let Travis verify this.

So, I start `xvfb` in my `.travis.yml` scipt, as documented:

```
# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
```

This virtual server has always served me well, up until now, as it appears unable to produce a list of windows. The command `wmctrl` can produce such as list, showing the vital window ID property as well. Yet, when I run the following command on Travis:

```
wmctrl -l
```

it gives the error:

```
Cannot get client list properties. 
(_NET_CLIENT_LIST or _WIN_CLIENT_LIST)
```

The repo I am talking about is [this one](https://travis-ci.org/richelbilderbeek/testing_cpp_gui_applications_tutorial)

I cannot blame the absence of windows when doing headless GUI testing with a virtual server, but I do need it. 

In the Travis documentation, other services are mentioned, but these appear to me to be mostly about browsers, where I create desktop GUI applications.  Should I use these services?

Any other clues?

Thanks for your awesome product, Richel

**Comment by richelbilderbeek** [comment]
I am sorry, I found a nice answer [here](http://stackoverflow.com/questions/12252774/getting-window-list-in-xvfb-server). Feel free to close this issue.

**Comment by richelbilderbeek** [comment]
Too bad, it does not work, `$ DISPLAY=:0; wmctrl -l` results in `Cannot open display` for values of DISPLAY from 0 to and including 3.

**Comment by BanzaiMan** [comment]
Email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.

**Comment by briandealwis** [comment]
Thanks for the pointer on window managers.  I stumbled across this issue trying to figure out why my SWTBot-based tests for Eclipse fail on Travis.  Such tests require running with a window manager to track the active window/shell.  The [GitHub Flavoured Markdown viewer for Eclipse](https://github.com/satyagraha/gfm_viewer)'s [.travis.yml](https://github.com/satyagraha/gfm_viewer/blob/master/.travis.yml) file has an example of setting up metacity.  I added a note on the [SWTBot pages](https://wiki.eclipse.org/SWTBot/Automate_test_execution#On_Travis).

**Comment by richelbilderbeek** [comment]
@briandealwis : I set up Metacity with success on Travis CI. Too bad, [in the Travis logs](https://travis-ci.org/richelbilderbeek/testing_cpp_gui_applications_tutorial), applications started cannot by found by `wmctrl`:

Here I start gedit multiple times on Travis on display 99, with success:

```
$ DISPLAY=:99; gedit &

The command "DISPLAY=:99; gedit &" exited with 0.
```

and

```
$ DISPLAY=:99; gedit &

The command "DISPLAY=:99; gedit &" exited with 0.
```

When I use `wmctrl` to display info about the window manager, Metacity is indeed found:

```
0.01s$ DISPLAY=:99; wmctrl -m

Name: Metacity
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
The command "DISPLAY=:99; wmctrl -m" exited with 0.
```

When I use `wmctrl -l` to display a list of windows, `gedit` is nowhere to be found:

```
0.01s$ DISPLAY=:99; wmctrl -l

The command "DISPLAY=:99; wmctrl -l" exited with 0.
```

At the end of the build I see gedit is terminated indeed:

```
Done. Your build exited with 0.
/home/travis/build.sh: line 107: 19074 Killed                  metacity --sm-disable --replace
/home/travis/build.sh: line 107: 19423 Killed                  gedit
/home/travis/build.sh: line 107: 19440 Killed                  gedit
```

May you have an idea what I overlook?

**Comment by briandealwis** [comment]
@richelbilderbeek you either need to remove the ';':
```
DISPLAY=:99 gedit &
```
or you need to explicitly export the value:
```
export DISPLAY=:99; gedit &
```
Or better yet, use the [`env:` section in your `.travis.yml`](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-.travis.yml)

**Comment by probonopd** [comment]
Did you find a way to test GUI applications on Travis CI with sending keyboard shortcuts to the application? For example, I would like to do a very basic test: launch an application, wait until it is launched, then send Alt-F4, and check if it exited cleanly.

**Comment by richelbilderbeek** [comment]
No, I still cannot do it, although I have tried extensively at [my testing_cpp_gui_applications_tutorial GitHub](https://github.com/richelbilderbeek/testing_cpp_gui_applications_tutorial). Please let me know if you do succeed...

**Comment by richelbilderbeek** [comment]
I have added a bounty at [my testing_cpp_gui_applications_tutorial GitHub](https://github.com/richelbilderbeek/testing_cpp_gui_applications_tutorial/issues/3), contact me if interested.

**Comment by probonopd** [comment]
Since this has not been resolved, please keep it open. Thanks.

**Comment by probonopd** [comment]
Since this has not been resolved, please keep it open. Thanks.

**Comment by jesskie** [comment]
God bless you

jess

**Comment by probonopd** [comment]
Since this has not been resolved, please keep it open. Thanks.

**Comment by TheSashmo** [comment]
I'd like to add the note to keep this open as well.... A side note if you run 
`DISPLAY=:2 xwininfo -tree -root`
It will return the list of open windows.
