### ISSUE TITLE
[Haxe] Default NodeJS version on Mac

### ISSUE THREAD

**Issue by kevinresol** [travis-ci/travis-ci#6007]
For Haxe projects, currently the default NodeJS version on mac is 0.10.x, which is pretty old. Is it possible to update it to at least v4.x?

cc @andyli @waneck @Simn

**Comment by andyli** [comment]
It's not really Haxe related, but just about the default node version on the Mac images. I do hope Travis will upgrade the node installation.

**Comment by BanzaiMan** [comment]
On the Mac, no Node.js is pre-installed. The default version is 0.10.x there, so that it is the same everywhere.

The default will be updated once all our Linux images are updated to have a more recent version. Until then, you can use `nvm` to install a more recent version; e.g., `nvm install 5`.
