### ISSUE TITLE
Travis Ci not Building (CSharp)

### ISSUE THREAD

**Issue by empinel** [travis-ci/travis-ci#6008]
Repository: https://github.com/empinel/Win32.Stolich

I cannot compile using Travis, my solution is in a subdirectory (stolich) and nuget can't find it

**Comment by BanzaiMan** [comment]
Keep in mind that the Linux file systems are generally case sensitive. Ours is no exception.

I think you need to specify the correct file in https://github.com/empinel/Win32.Stolich/blob/e15330b8daef3c2220e67b378ddda6e32906162c/.travis.yml#L4.

**Comment by empinel** [comment]
Thank you
