### ISSUE TITLE
Is there a to bypass mono installation with lang: csharp?

### ISSUE THREAD

**Issue by am11** [travis-ci/travis-ci#6011]
cc @joshua-anderson, @akoeplinger, @nterry

I have configured a TravisCI script to build and test a lib with .NET Core app:
https://github.com/am11/MaxMind-DB-Reader-dotnet/blob/2b36731/.travis.yml

Here is a snapshot of success story: https://travis-ci.org/am11/MaxMind-DB-Reader-dotnet/builds/128413918. It executes the entire matrix, that constitutes four jobs, under 10 minutes with lang: C++.

The language is set to C++ owing to the peculiar behaviour of csharp build box, that it always tends to install mono, which consumes lots of cycles and an utter waste of resource for pure .Net Core jobs. Is there a way to selectively skip mono in C# build box, when TFM is NetStandard1.x? Ideally, it would be great if it installs latest dotnet/cli instead of mono for .NET Core and also a separate SKU for mono+CLI pre-configured (so we don't have to install CLI manually)

**Comment by akoeplinger** [comment]
Not yet, but adding .NET Core support is tracked by #4663 (which I'll work on when RC2 of the new dotnet CLI hits).

**Comment by BanzaiMan** [comment]
@akoeplinger Is there anything to do on this issue?

**Comment by akoeplinger** [comment]
@BanzaiMan I don't think so, feel free to close.

**Comment by am11** [comment]
Thanks @akoeplinger. RC2 is really close, now we have a roadmap: https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/
I will keep and eye on #4663. Bypassing mono installation per job run and running on Docker (`sudo: false`) would be awesome! :)
