### ISSUE TITLE
all tests on OSX hangs

### ISSUE THREAD

**Issue by Ldpe2G** [travis-ci/travis-ci#6019]
Recently I have make a Pull Request on a project, all tests on linux have passed except for the OSX, I have tried many times but still got the same result. I also notice that there was and investigating issues with public and private OSX builds recently reported on the https://www.traviscistatus.com/. 

Is it possible that  the issue is  caused by queue blocking somewhere?

**Comment by BanzaiMan** [comment]
Could you point to builds you are talking about? Thanks.

**Comment by Ldpe2G** [comment]
Sorry for the late reply @BanzaiMan ,  

here is the address: https://travis-ci.org/dmlc/mxnet/builds/128743017

**Comment by BanzaiMan** [comment]
Can you tell from the output where in https://github.com/dmlc/mxnet/blob/7e55c4abb26c85cb011705aae8bc3e730271f832/tests/travis/setup.sh the build is hanging? If not, can you add `set -x` to see where?

**Comment by Ldpe2G** [comment]
thanks @BanzaiMan , problem solved

**Comment by javelinjs** [comment]
@Ldpe2G Could you tell how you solve this problem? which may help others who meet the same issue in future.
