### ISSUE TITLE
tar: Cowardly refusing to create an empty archive

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#6022]
I've got this build [#128717010](https://travis-ci.org/EA31337/FX-MT-VM/jobs/128717010), however it shows the following errors when trying to save the cache:

```
store build cache
changes detected, packing new archive
FAILED: tar -Pzcf /home/travis/.casher/push.tgz 
tar: Cowardly refusing to create an empty archive
Try 'tar --help' or 'tar --usage' for more information.
uploading archive
failed to upload cache
curl: Can't open '/home/travis/.casher/push.tgz'!
curl: try 'curl --help' or 'curl --manual' for more information
Done. Your build exited with 0.
```

It may be related to #3239, but it's closed.

Do I need to change anything, or it's a bug?

I've got the following configuration in [`.travis.yml`](https://github.com/EA31337/FX-MT-VM/blob/c0b2437f0493c9765654889361583f062ba436ee/.travis.yml):

```
cache:
  apt: true
  pip: true
  directories:
    - $HOME/.wine/drive_c/Program Files (x86)
```

**Comment by BanzaiMan** [comment]
This is a variation of #6005. The name of a directory you are trying to cache contains a space *and* parentheses, and we are unable to create auxiliary files needed to cache properly (https://travis-ci.org/EA31337/FX-MT-VM/jobs/128717010#L118).

For now, please use a parent directory that doesn't have a space in the name.

Closing as a duplicate.

**Comment by kenorb** [comment]
Thanks for the info. Thanks for the suggestion, however I've tried parent directory, but it's even worse since I've a lot of Permission and Input/output errors. Build: [#128702272](https://travis-ci.org/EA31337/FX-MT-VM/jobs/128702272#L2884) which fails the build completely, probably because of circular symlinks. I'll wait then for the mentioned fix.

**Comment by BanzaiMan** [comment]
Can you try deleting unnecessary files in `before_cache`?
