### ISSUE TITLE
Travis CI exposes secret environment variables in verbose deployment output

### ISSUE THREAD

**Issue by janschumann** [travis-ci/travis-ci#6026]
Please see an example build here: https://travis-ci.org/janschumann/react-chat/jobs/128794031#L414

**Comment by BanzaiMan** [comment]
This is documented behavior. https://github.com/travis-ci/dpl#azure-web-apps

> verbose: If passed, Azure's deployment output will be printed. Warning: If you provide incorrect credentials, Git will print those in clear text. Correct authentication credentials will remain hidden.
