### ISSUE TITLE
Defining lists with a single value in .travis.yml cause problems

### ISSUE THREAD

**Issue by fniephaus** [travis-ci/travis-ci#6028]
When using something like this:

``` yml
...
os:
  - linux
...
```

then `$TRAVIS_OS_NAME` is `["linux"]` rather than just `linux`.

We ran into problems with this, because also `config[:os]` is set to `["linux"]` and does not match anymore:
https://github.com/travis-ci/travis-build/blob/f4d531479b01d8526b57f2e59b859e5713920605/lib/travis/build/script/smalltalk.rb#L31

/cc @jchromik

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-core/blob/af74ded7750db9494e90d0a9b9ec1db8290c7fcc/lib/travis/model/build/config.rb#L96 is for matrix expansion. I don't think that has any bearing on whether or not `config[:os]` is set.

**Comment by fniephaus** [comment]
The real problem appears to be that only one value is provided *in a list*. In the example above [`config[:os]` is `["linux"]`](https://travis-ci.org/fniephaus/SWT-Demo/jobs/129095032#L136) rather than just `linux`.
So the following fixes the problem:
```yml
os: linux
```

But isn't this something travis-core should take care of? If the list contains a single value, it could replace the list with the single value, so that the script behaves the way it's behaving when doing `os: linux`.

**Comment by BanzaiMan** [comment]
Oh, I see. I don't think that is happening right now.

**Comment by fniephaus** [comment]
I've updated the issue accordingly.

**Comment by BanzaiMan** [comment]
@fniephaus Is this still an issue?

**Comment by BanzaiMan** [comment]
I think it is still a problem.

**Comment by BanzaiMan** [comment]
For the record, #4731 also addressed this problem.

**Comment by BanzaiMan** [comment]
Tested again:

config: https://github.com/BanzaiMan/travis_production_test/blob/ca6f85e0d000961bed8cea3c0e150b9280f3cfb2/.travis.yml#L5-L6
job: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/196158644#L63

I think we can close this, after all.

**Comment by fniephaus** [comment]
Cool, thanks!
