### ISSUE TITLE
Travis web client doesn't support line erasure

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [travis-ci/travis-ci#6030]
https://travis-ci.org/HighSchoolHacking/GLS/builds/129028651

The Travis web client never erases lines that should be rewritten, so the mocha Nyan Cat reporter ends up being this massive series of weird horizontal lines.

*(not sure what the technical term for rewriting lines is)*

**Comment by JoshuaKGoldberg** [comment]
![image](https://cloud.githubusercontent.com/assets/3335181/15135282/39bb007a-1629-11e6-94c1-4f176674f1b7.png)

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. Not all ANSI escape sequences, especially those that change the cursor positions, are not very friendly to the stream based log display. There have been [various issues](https://github.com/travis-ci/travis-ci/issues?utf8=%E2%9C%93&q=is%3Aissue+ansi+escape+) opened in the past, but I'm afraid we do not have plans to support them at this time.

**Comment by JoshuaKGoldberg** [comment]
Gotcha, darn. Thanks for the lightning fast response!
