### ISSUE TITLE
Refreshing a build does not always work correctly

### ISSUE THREAD

**Issue by gerrywastaken** [travis-ci/travis-ci#6031]
We had some issues with our Travis builds failing, however these issues have now been fixed on master. For a few pull requests I could just refresh the build and the tests would all start working correctly in that PR.

However requests like this still fail after refereshing:
https://github.com/michaeldv/awesome_print/pull/211
https://travis-ci.org/michaeldv/awesome_print/builds/94330819

This is the fix on master that addressed the build failures seen on that PR:
https://github.com/michaeldv/awesome_print/commit/ad2ccfe906e474447ca012de1496e201b6554cac

But if I create a new branch where I manually apply the pull request on master they pass:
https://travis-ci.org/gerrywastaken/awesome_print/builds/129095368 (with a merge commit)

## My hypothesis
I don't know how Travis works under the hood, but my guess would be... the Docker container is built once and at that time the `before_install` commands are run. Refreshing the build of the pull request keeps using this container and only runs things after the `before_install` commands and so even though maser has a `before_install` commands which is different from the commands used to build the container, the container is never rebuilt with these new commands.

That's my guess anyway, given what I'm experiencing .

edit: P.S. Thank you for creating Travis. It's awesome.

**Comment by BanzaiMan** [comment]
I think this is a Bundler bug. If you look at the failed jobs in https://travis-ci.org/michaeldv/awesome_print/builds/94330819, you notice that the Bundler versions are old. By running `gem install bundler` in `before_install`, you are ensuring that this bug is no longer present.

**Comment by gerrywastaken** [comment]
@BanzaiMan I think there is a misunderstanding here, I know about the Bundler bug and that running `gem install bundler` fixes it. The issue I'm having a problem with is that refreshing the build associated with PR doesn't appear to run that command `gem install bundler` even though it's now part of the upstream which the PR will be applied to.

**Comment by BanzaiMan** [comment]
@gerrywastaken A build is not reconfigured upon restart (which I assume is what you mean by "refresh"). A commit will be associated with the build, and that will not change.

**Comment by gerrywastaken** [comment]
@BanzaiMan, sorry I did indeed mean "restart".

Ok, so I understand this is logical from the point of view of a developer working on Travis. However I suspect that most of the time when somebody clicks on that button to the top right of a failing PR build, the majority of the time it's because the failures have been fixed on upstream and they now want to rerun the tests against that.

![screen shot 2016-05-10 at 11 27 39 pm](https://cloud.githubusercontent.com/assets/71481/15148068/fa1aeeec-1706-11e6-9d5d-1edc53ebfe52.png)

This is kinda also suggested by the docs:

> Rather than test the commits from the branches the pull request is sent from, we test the merge between the origin and the upstream branch.
https://docs.travis-ci.com/user/pull-requests

However when I click on that button I get a test that is run using the most recent code in upstream, but a build that was generated when upstream was still failing. This also means that there could be many PRs which just have to be closed and a new duplicate PR opened in order to run against a build generated by the current upstream. Unless I'm missing a rebuild PR from scratch option?

This is also quite confusing for people who don't know about this limitation, because the majority of time a restart will apply most changes from upstream. So if an upstream is passing since making fixes to the build and there is a PR with the old build (which has been restarted since the fixes to upstream), then it looks like the PR has caused a regression in the build. But the reality is that it's just running on an old build. This might be obvious to Travis developers, but I doubt it's obvious to many of your users.

I suspect this is a problem that would hit a lot of people, as I ran into it twice in two separate projects. However if you feel this isn't an issue, then that's fair enough, as I admit this is fairly subjective and I'm speculating quite a bit.

**Comment by BanzaiMan** [comment]
If you look at https://travis-ci.org/michaeldv/awesome_print/jobs/94330820#L142, we check out:

```sh-session
$ git fetch origin +refs/pull/211/merge:
```

Until the PR is updated to include the new commit(s) on the head branch, our build will not change.

**Comment by gerrywastaken** [comment]
Ok, I guess that's the case. It seems like the opposite of what is said in the documentation that I quoted above. But I appreciate your response.

**Comment by John-Colvin** [comment]
It's such a pain that I can't use the result of the pr tests to reliably tell me whether clicking "merge" will break the tests on an important branch.

The only workaround short of opening a new pr (with all the friction and cross-conversation that will cause) is to push new commits to the pr branch, which in many cases the maintainer may not have push permissions for. Even with rights, it's a pain and either involves rewriting history or adding dummy commits just to trigger Travis.

Overall, this is a bad situation for me to be in as a maintainer.
