### ISSUE TITLE
HHVM build exceeds memory limit but never uses more than 2097152

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#6034]
Using trusty with hhvm phpunit will error with `Fatal error: request has exceeded memory limit in /phpunit/php-timer/src/Timer.php on line 97`

hhvm reported memory limit using ini_get("memory_limit") reports `17179869184`
but the `memory_get_peak_usage()` reports a max usage of `2097152`

even setting the memory limit to -1  ini_get("memory_limit") will report `9223372036854775807`
but the `memory_get_peak_usage()` reports a max usage of `2097152`
https://travis-ci.org/photodude/joomla-cms/jobs/129306597

why is the memory usage capped way below the actual limit set?

**Comment by BanzaiMan** [comment]
Could it be an HHVM bug, like https://github.com/facebook/hhvm/issues/4723? We are happy to provide you with access to debug VM. Please email support@travis-ci.com.

**Comment by photodude** [comment]
@BanzaiMan is there any specific information I need to include in my reqest for access to debug?

**Comment by photodude** [comment]
Ok I finally got set up and ran a debug job, but I wasn't able to really figure anything more out on the memory issue. 

I'm leaning towards an HHVM bug in `memory_get_peak_usage()` but I'm not sure what, why, how, or specifics of what's going on in the memory use at the point of failure (my debug skills in this scenario are not great) 

If you have any suggestions on how I can profile the memory use during the debug while running phpunit  it would be helpful.

**Comment by photodude** [comment]
I'm closing this issue. I have confirmed this failure of `memory_get_peak_usage()` was related to an HHVM bug that was solved in HHVM 3.15. Unfortunately, the bug will not be fixed in any of the previous hhvm versions.
