### ISSUE TITLE
undocumented configuration options for branches

### ISSUE THREAD

**Issue by onqtam** [travis-ci/travis-ci#6039]
So I looked at [**this**](https://github.com/urho3d/Urho3D/blob/master/.travis.yml) config file and I noticed stuff like

```
---

branch: {name: OSX-CI, active: yes, mandatory: yes}
```

as if there are different configs for different branches in the config file.

So my question is: what do active and mandatory mean? What are the defaults? What if they are no?

I couldn't find this documented anywhere.

And what about this:

```
branch: {name: VS-CI, active: yes, appveyor: yes, last_job: 'x64:SHARED'}
```

I see ps (powershell?) used there and also the appveyor service mentioned - is it possible to have the appveyor config in the travis file? wtf

**Comment by BanzaiMan** [comment]
Perhaps the maintainers of https://github.com/urho3d/Urho3D have motivations for adding these extra values, but we do not do anything with them. Extra information in the YAML file is simply discarded.
