### ISSUE TITLE
Npm install failed in travis with error ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by vcernomschi** [travis-ci/travis-ci#6041]
Npm install failed in travis with error:
```
npm ERR! code ENOSPC
npm ERR! errno -28
npm ERR! syscall write
npm ERR! nospc ENOSPC: no space left on device, write
```
I execute the command below to install dependencies: `/home/travis/.nvm/versions/node/v4.3.2/bin/npm install --loglevel silent --prod' failed in '/home/travis/build/MitocGroup/deep-marketplace/src/DeepMgProperty/Backend/src/Property/Delete`

Here the example of package.json: 
```
{
  "name": "deep-mg-property-delete",
  "version": "0.0.1",
  "description": "Delete Property NodeJS package to be installed via NPM",
  "author": {
    "name": "Mitoc Group",
    "email": "hello@mitocgroup.com",
    "website": "http://www.mitocgroup.com"
  },
  "contributors": [
    {
      "name": "Vitali Cernomschi",
      "email": "vcernomschi@mitocgroup.com"
    }
  ],
  "bugs": {
    "url": "https://github.com/MitocGroup/deep-management/issues"
  },
  "keywords": [
    "DEEP",
    "Digital Enterprise End-To-End Platform",
    "Deep Core Libraries",
    "Property",
    "Properties",
    "Delete Property"
  ],
  "dependencies": {
    "deep-framework": "^1.9.x"
  },
  "devDependencies": {
  },
  "scripts": {
    "postinstall": "npm run compile",
    "compile": "deepify compile-es6 `pwd`"
  },
  "private": true
}
```

Need to take into account that we have about 60 packages and for each we make `npm install` by using 4/8 chunks. 

Travis jobs fail with the error below:
```
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.3.2/bin/node" "/home/travis/.nvm/versions/node/v4.3.2/bin/npm" "install" "--loglevel silent" "--prod"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ENOSPC
npm ERR! errno -28
npm ERR! syscall write
npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc This is most likely not a problem with npm itself
```

Please refer to the full logs:
(for 4 chunks) https://travis-ci.com/MitocGroup/deep-marketplace/jobs/39806346

(for 8 chunks) https://travis-ci.com/MitocGroup/deep-marketplace/jobs/39808331

**Comment by BanzaiMan** [comment]
Looks like your jobs are consistently failing. How much disk space does it require? What are you trying to install?

**Comment by vcernomschi** [comment]
1 - It requires minimum 8 GB disk space. 
2 - We install all dependencies for our backend to be able to make e2e testing for our project.

**Comment by BanzaiMan** [comment]
That is bad news for the container builds. Try `sudo: required` to see if you get more reliable results.

**Comment by vcernomschi** [comment]
Thanks, I will try with it. Can I remove all files /tmp and repeat the command if it fails? Or this can broke the build?

**Comment by BanzaiMan** [comment]
Data do not persist across builds, so removing files from `/tmp` is not going to help.

**Comment by vcernomschi** [comment]
I mean if `npm install` command fails, I will remove /tmp and try again to execute `npm install` command for failed module

**Comment by BanzaiMan** [comment]
It is up to you, but frankly I don't think that is going to help you much.

**Comment by BanzaiMan** [comment]
Looks like GCE builds are working for you.

I'm closing this now, since there is not much to do here to prevent running out of disk space on container builds.

**Comment by cention-ashish-ghosh** [comment]
clear /home/username/.cache works for me.
