### ISSUE TITLE
Downgrade HHVM in Trusty to 3.12 until HHVM 3.14

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#6042]
The trusty build has HHVM 3.13 included which has a bug that prevents external modules from being built. see https://github.com/facebook/hhvm/issues/6957

This bug prevents the use of things like PostgreSQL as there is no 3.13 module available due to this bug. See https://github.com/PocketRent/hhvm-pgsql/issues/113

As such the included HHVM in the Trusty build on Travis CI needs to be downgraded to 3.12 until the 3.14 build is released.

**Comment by BanzaiMan** [comment]
@photodude Do you happen to know the HHVM release schedule?

**Comment by photodude** [comment]
@BanzaiMan the [HHVM release schedule page](http://hhvm.com/blog/6083/hhvm-long-term-support) claims 5-19-2016 is the intended release for 3.14

We'll see if that happens, I'm not confident that it will happen on that date.

**Comment by photodude** [comment]
@BanzaiMan It would also be nice to see the [feature request for HHVM version selection](https://github.com/travis-ci/travis-ci/issues/6043) happen so we can test against multiple HHVM versions; or to exclude HHVM versions when there is an issue like this.

**Comment by BanzaiMan** [comment]
I feel that this is more correctly addressed by #6043. The "latest" means "latest", even if it's broken for whatever reason.

**Comment by photodude** [comment]
This was more of a short term fix, I agree that if  #6043 could be implemented it is the best solution.

**Comment by BanzaiMan** [comment]
I'm closing this, then, in favor of #6043.
