### ISSUE TITLE
frequent UnknownHostException in network HTTP tests

### ISSUE THREAD

**Issue by eighthave** [travis-ci/travis-ci#6044]
I get a lot of these in jobs that test connecting to HTTP sites:

```
java.net.UnknownHostException: Unable to resolve host "yahoo.com": No address associated with hostname
```

I've gotten them for other big sites too, like www.yandex.ru.  Retrying the build almost always fixes it.  And for jobs like [guardianproject/NetCipher](https://travis-ci.org/guardianproject/NetCipher/jobs/129706120) which build against multiple JDKs, this [fails in only one of the jobs](https://travis-ci.org/guardianproject/NetCipher/builds/129706119).

I've tried everything that I could think of but they still keep happening.  Building against a single JDK makes it a lot less likely to happen.

**Comment by BanzaiMan** [comment]
Does the test fail consistently if you restart the failing job?
