### ISSUE TITLE
`sudo apt-get update` fails on Trusty

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/travis-ci#6048]
`sudo apt-get update`  fails on Trusty builds:

```
W: There is no public key available for the following key IDs:
1397BC53640DB551
```

(for example: https://travis-ci.org/MariadeAnton/travis-ci-trusty/builds/129954383#L225)

Per http://askubuntu.com/questions/766883/there-is-no-public-key-available-for-the-following-key-ids-1397bc53640db551-goo and https://www.reddit.com/r/linux4noobs/comments/4grdo7/an_error_occurred_w_there_is_no_public_key/

The current workaround is adding: 

```
before_install:
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo apt-get update
```

https://github.com/MariadeAnton/travis-ci-trusty/blob/chrome%2Bapt-get-update/.travis.yml#L4-L5

We're working on a fix for this and will update here as soon as possible.

**Comment by Gargaj** [comment]
The workaround no longer appears to work: https://travis-ci.org/Gargaj/Bonzomatic/jobs/134744471

**Comment by chouseknecht** [comment]
Before running *apt-get update -qq*, I added the following line, which I cargo-culted from some Ubuntu forum Q&A, and it seems to work:

```
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32 40976EAF437D05B5
```

Not an ubuntu expert by any means. Just want my tests to run. So, this may or may not be the right solution.

**Comment by ciscoheat** [comment]
Since Google stopped providing the 32 bit version of chrome, another fix was needed when installing 386 packages. I had to add these lines in `before_install`, before `sudo apt-get update`:

```
sudo sed -i -e 's/deb http/deb [arch=amd64] http/' "/etc/apt/sources.list.d/google-chrome.list" "/opt/google/chrome/cron/google-chrome"
sudo dpkg --add-architecture i386
```

Source: https://askubuntu.com/questions/724093/no-more-updates-for-google-chrome-apt-get-update-error
