### ISSUE TITLE
Cannot use gcc-4.8 in the container mode builders

### ISSUE THREAD

**Issue by ehsan** [travis-ci/travis-ci#6052]
It seems like the gcc 4.8 packages are not available even though they're in the APT packages whitelist.  See [the failure log](https://travis-ci.org/mozilla/spidernode/jobs/130273480) and the corresponding [.travis.yml](https://github.com/mozilla/spidernode/blob/45c9f6a1de45d5765597f1e6e91ac9391f4d2721/.travis.yml) file.

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirementsYou need to add an APT source. See

**Comment by ehsan** [comment]
Thanks!
