### ISSUE TITLE
Do you have any option to share file between jobs?

### ISSUE THREAD

**Issue by vcernomschi** [travis-ci/travis-ci#6054]
While CI I am testing different node modules in the same time by adding parallelizing builds across virtual machines.  I use the following config:
```
env:
  matrix:
    - TEST_SUITE=deep-asset,deep-cache,deep-core
    - TEST_SUITE=deep-db,deep-di,deep-event
    - TEST_SUITE=deep-fs,deep-kernel
    - TEST_SUITE=deep-framework,deep-log,deep-notification,deep-resource
    - TEST_SUITE=deep-search,deep-security,deep-validation
```

I would like to combine code coverage reports for the TEST_SUITE above and send it to coverage services like coveralls, codacy, codeclimate, etc.

Do you have any option to share file between jobs?

**Comment by BanzaiMan** [comment]
Jobs in a build matrix are independent, and they do not share storage. They are not guaranteed to be running simultaneously, so any scheme which assumes that shared storage is available would be brittle at best.

Persistent storage might merit discussion, but I don't think it would be a long time before it can be realized. As such, I am closing this for now.

**Comment by BanzaiMan** [comment]
I did open an internal issue; if anything comes out of it, we'll update it here.

**Comment by pevik** [comment]
This might help http://sleepycoders.blogspot.cz/2013/03/sharing-travis-ci-generated-files.html

**Comment by Winbobob** [comment]
I have exactly the same question! I am thinking whether we could upload `cc-test-reporter`-generated JSON files to a github repo and when we run `sum-coverage`, we pull JSON files from github.

**Comment by ttodua** [comment]
just for any readers coming here from google. since then travis introduced "workspaces":  https://docs.travis-ci.com/user/using-workspaces/
