### ISSUE TITLE
New feature request: filtered output as an additional security mechanism

### ISSUE THREAD

**Issue by wkoszek** [travis-ci/travis-ci#6055]
# New Feature Request: Filtered output

**Motivation:** Some utilities may leak secrets from environment variables set with `travis env`. It would be great if Travis had protection against this, since it'd give me more comfort in bringing my open source projects into Travis.

## Problem example

I have just enabled https://github.com/fastlane/fastlane on Travis for my iOS app build/release automation. The problem is that it prints out a lot of information. Additionally, it's a lot of Ruby code, and if an exception happens, I don't really know what it'll print out in a trace. Maybe some of my secrets from the environment too?

## Proposed feature: Filtered Output

How I would like it to work?

```
for each N bytes of logging output:
   for each secret in secrets set by `travis env set`
       do bytes have secret?
       if so:
         anonymise value of "Secret env. variable with NAME_OF_SECRET_REMOVED" message
   shift to new bytes, but don't forget to that secrets can be on read-buffer boundary
```

## Example

Assume I did `travis env set FASTLANE_PASSWORD abc123`. 

I suggest we print something like this by default

```
bleh bleh
Variable FASTLANE=<value of your FASTLANE_PASSWORD removed>
```

Right now, without this proposed feature, the output is like this:

```
bleh bleh
Variable FASTLANE=abc123
```

I've noticed 2nd time this impacts me, since sometimes I do a mistake by myself: while debugging scripts on Travis, I'd set `set -xe` which prints out all the secrets and environment variables.

**Comment by BanzaiMan** [comment]
Duplicate of #1478.

**Comment by wkoszek** [comment]
@BanzaiMan Is #1487 the right issue? I can't decipher from it if it's an actual duplicate, since I see no new feature proposal there.

**Comment by BanzaiMan** [comment]
Perhaps I misread what you are asking, but you wrote:

> Some utilities may leak secrets from environment variables set with travis env. It would be great if Travis had protection against this, since it'd give me more comfort in bringing my open source projects into Travis.

#1487 asks to mask secret environment variables from the logs. Which is what I thought you wanted. If not, please clarify.

It does not matter where the secret environment variables come from—whether in `.travis.yml` or in the setting panel (via `travis env`)—they end up in the same place when we execute the build script.

**Comment by wkoszek** [comment]
@BanzaiMan ah, sorry. I somehow opened https://github.com/travis-ci/travis-ci/issues/1478. Maybe I flipped the issue number. #1487 looks good.

**Comment by BanzaiMan** [comment]
@wkoszek Ah, sorry about that. I originally wrote the wrong number when I first responded. I edited the reference shortly afterwards. Perhaps you opened the link from the notification email.

**Comment by wkoszek** [comment]
Yes, I think I did. Thanks for clarification.

On Mon, May 16, 2016 at 12:33 PM, Hiro Asari <notifications@github.com>
wrote:

> @wkoszek <https://github.com/wkoszek> Ah, sorry about that. I originally
> wrote the wrong number when I first responded. I edited the reference
> shortly afterwards. Perhaps you opened the link from the notification email.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/travis-ci/issues/6055#issuecomment-219523202>
>



-- 
Wojciech A. Koszek
wojciech@koszek.com
http://www.koszek.com/
