### ISSUE TITLE
Vagrant inaccessible

### ISSUE THREAD

**Issue by chrisspen** [travis-ci/travis-ci#6060]
I'm trying to create a [build process](https://travis-ci.org/chrisspen/burlap) to run tests across multiple OSes using Vagrant and a Tox plugin. It runs fine on my Ubuntu 14 localhost, but in Travis, but Vagrant times out trying to boot a Virtualbox VM:

    ==> default: Importing base box 'ubuntu/trusty64'...

    ==> default: Matching MAC address for NAT networking...

    ==> default: Checking if box 'ubuntu/trusty64' is up to date...

    ==> default: Setting the name of the VM: functional_tests_default_1463515960654_71459

    ==> default: Clearing any previously set forwarded ports...

    ==> default: Clearing any previously set network interfaces...

    ==> default: Preparing network interfaces based on configuration...

        default: Adapter 1: nat

    ==> default: Forwarding ports...

        default: 22 => 2222 (adapter 1)

    ==> default: Running 'pre-boot' VM customizations...

    ==> default: Booting VM...

    ==> default: Waiting for machine to boot. This may take a few minutes...

        default: SSH address: 127.0.0.1:2222

        default: SSH username: vagrant

        default: SSH auth method: private key

        default: Warning: Connection timeout. Retrying...

        default: Warning: Connection timeout. Retrying...

        default: Warning: Connection timeout. Retrying...

        default: Warning: Connection timeout. Retrying...

        default: Warning: Connection timeout. Retrying...

        default: Warning: Connection timeout. Retrying...

        default: Warning: Connection timeout. Retrying...

        ...

        The job exceeded the maximum time limit for jobs, and has been terminated.

How do you launch a Vagrant/Virtualbox VM inside Travis-CI?

**Comment by solarce** [comment]
We do not support running VirtualBox inside any of our compute environments and currently have no plans to support it. We have some users who launch DigitalOcean droplets during their builds, and run virtualbox inside the Droplet, but this does result in the user needing to pay for the droplet costs.

**Comment by DonRichards** [comment]
This could be a valuable feature. I'd like to automate vulnerability scans (Owasp) but it requires a running web server. Any suggests on how to automate a vulnerability scanner without seeking another product/company?

**Comment by solarce** [comment]
@DonRichards I would suggest trying out our [Docker](https://docs.travis-ci.com/user/docker/) support to run a web server _in the background_.
