### ISSUE TITLE
trusty doesn't work with HHVM

### ISSUE THREAD

**Issue by Ma27** [travis-ci/travis-ci#6062]
hey there,

according to my build, ``hhvm`` is not present on a trusty image: https://travis-ci.org/Sententiaregum/Sententiaregum/jobs/130626811

The corresponding travis-ci config:
https://github.com/Sententiaregum/Sententiaregum/blob/%23258-refactor-flux-implementation/.travis.yml#L2-L8

**Comment by BanzaiMan** [comment]
Technically speaking, we do not yet support PHP on Trusty. https://docs.travis-ci.com/user/trusty-ci-environment#PHP

However, you might be able to get further by using the `edge` image with

```yaml 
group: edge
```

Note, however, there is a report of breakage such as #6042.

**Comment by BanzaiMan** [comment]
Closing this, since the `edge` Trusty image supports HHVM, and the stable one does not officially support it (which is documented).
