### ISSUE TITLE
Restarted Build, now gives: "LaTeX Error: There's no line here to end."

### ISSUE THREAD

**Issue by giuseppec** [travis-ci/travis-ci#6064]
Hi,

since 4 or 5 days, I get always the same error when I do a comit:
```
checking PDF version of manual without hyperrefs or index ... ERROR checking PDF version of manual ... WARNING

LaTeX errors when creating PDF version.

This typically indicates Rd problems.

LaTeX errors found:

! LaTeX Error: There's no line here to end.
```
(see rawlog https://s3.amazonaws.com/archive.travis-ci.org/jobs/130754816/log.txt).

I thought that I did something weird in my comit, but then I restarted a build which was successful on travis and it gave me the same error again. Has something changed last week that could cause this error message?

**Comment by BanzaiMan** [comment]
Paging  @craigcitro, @hadley, and @jimhester

**Comment by giuseppec** [comment]
Nevermind. The problem can was this:

```
#' @param ... \cr
#'   Arguments passed to another function
```

removing `\cr` helped.
