### ISSUE TITLE
Make build queue visible

### ISSUE THREAD

**Issue by lbergelson** [travis-ci/travis-ci#6066]
Builds don't always start in a timely manner and it's difficult to understand why.  There needs to be some visibility into the organization wide build queue so that we can tell when we're hitting our limits and what's causing it.  It looks like something like that already exists in travis-ci.com, but it's not available for travis-ci.org.

**Comment by BanzaiMan** [comment]
We used to do that, but no longer do, for performance reasons. If you want to look at the build queue status, look at the graphs on https://www.traviscistatus.com/.

I'm closing this.

**Comment by lbergelson** [comment]
@BanzaiMan What I mean is not the global build queue, but your own organizations build queue.  Since the number of builds is throttled to a specific number of concurrent builds, it's important to be able to tell how many slots you're using at any given time.  This currently isn't possible.

**Comment by BanzaiMan** [comment]
That should be visible in your "My repositories" bar on the left, no?

**Comment by lbergelson** [comment]
Not as far as I can see.  It exists on travis-ci.com but not on travis-ci.org.

There is a list of "active projects" of some sort.  But they're from multiple organizations mixed together, and it's not an exhaustive list of all the projects in the organization.  

<img width="313" alt="screen shot 2016-06-02 at 2 27 17 pm" src="https://cloud.githubusercontent.com/assets/4700332/15756230/4d2ea35c-28ce-11e6-9520-325a19b666c7.png">

**Comment by lbergelson** [comment]
Bump

**Comment by djshapiro** [comment]
This would be a handy feature.

**Comment by SylvainCorlay** [comment]
Bump
