### ISSUE TITLE
libc++ cannot be installed

### ISSUE THREAD

**Issue by webmaster128** [travis-ci/travis-ci#6067]
In the [Travis Ubuntu-precise apt whitelist][1] there is the package libc++-dev listed, which I try to install via

    # .travis.yml
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kubuntu-backports
        - llvm-toolchain-precise
        packages:
        - g++-4.8
        - cmake
        - libc++-dev

What happens in the APT step in the Travis job is

    $ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install g++-4.8 cmake libc++-dev
    Reading package lists...
    Building dependency tree...
    Reading state information...
    libc-dev-bin is already the newest version.
    libc-dev-bin set to manually installed.
    libc6-dev is already the newest version.
    libc6-dev set to manually installed.
    The following package was automatically installed and is no longer required:
      libxmlrpc-core-c3
    Use 'apt-get autoremove' to remove them.
    The following extra packages will be installed:
      cmake-data cpp-4.8 emacsen-common gcc-4.8 gcc-4.8-base gcc-6-base libasan0
      libatomic1 libc6-armel-cross libc6-armhf-cross libcloog-isl4 libgcc-4.8-dev
      libgcc1 libgcc1-armel-cross libgcc1-armhf-cross libgomp1 libisl10 libitm1
      libpurelibc1 libquadmath0 libstdc++-4.8-dev libstdc++6 libtsan0
    Suggested packages:
      codeblocks eclipse gcc-4.8-locales dietlibc-doc g++-4.8-multilib gcc-4.8-doc
      libstdc++6-4.8-dbg gcc-4.8-multilib libmudflap0-4.8-dev libgcc1-dbg
      libgomp1-dbg libitm1-dbg libatomic1-dbg libasan0-dbg libtsan0-dbg
      libbacktrace1-dbg libquadmath0-dbg libmudflap0-dbg binutils-gold
      libstdc++-4.8-doc
    The following NEW packages will be installed:
      cpp-4.8 dietlibc-dev g++-4.8 gcc-4.8 gcc-4.8-base gcc-6-base libasan0
      libatomic1 libc6-armel-cross libc6-armhf-cross libc6-dev-armel-cross
      libc6-dev-armhf-cross libcloog-isl4 libgcc-4.8-dev libgcc1-armel-cross
      libgcc1-armhf-cross libisl10 libitm1 libklibc-dev libowfat-dietlibc-dev
      libpurelibc-dev libpurelibc1 libstdc++-4.8-dev libtsan0
      linux-libc-dev-armel-cross linux-libc-dev-armhf-cross
    The following packages will be upgraded:
      cmake cmake-data emacsen-common libgcc1 libgomp1 libquadmath0 libstdc++6
      linux-libc-dev
    8 upgraded, 26 newly installed, 0 to remove and 242 not upgraded.
    Need to get 43.6 MB of archives.
    After this operation, 77.1 MB of additional disk space will be used.

So you can see that libc++-dev is not mentioned anymore after the install command line. What happens is that the following packages are added:

* libc-dev-bin
* libc6-dev
* libc6-armel-cross
* libc6-armhf-cross
* libgcc1-armel-cross
* libgcc1-armhf-cross
* libpurelibc1

so I guess there is some regular expression magic going on (does libc++-dev match libc6-dev?).

So, how do I install libc++-dev on Travis?

  [1]: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545284#L392 shows that `libc++-dev` was found in

> http://ftp.us.debian.org/debian/ unstable/main amd64 Packages

which I believe is `debian-sid`. I don't know if that is compatible with other packages you are trying to install, so exercise caution.

**Comment by webmaster128** [comment]
Indeed, the package is available in debian-sid, thanks.

But why didn't I get an error before (I expected one)? Is it possible to deactivate regular expression package searches?

-------------------

For the record: there is a conflict when installing libstdc++-dev from debian-sid. So I am not going to use this package.

```
Preparing to replace locales 2.13+git20120306-3 (using .../locales_2.22-9_all.deb) ...
Unpacking replacement locales ...
dpkg: error processing /var/cache/apt/archives/locales_2.22-9_all.deb (--unpack):
 trying to overwrite '/usr/sbin/update-locale', which is also in package libc-bin 2.15-0ubuntu10.13
dpkg-deb (subprocess): subprocess data was killed by signal (Broken pipe)
dpkg-deb: error: subprocess <decompress> returned error exit status 2
Selecting previously unselected package libc-l10n.
dpkg: considering deconfiguration of locales, which would be broken by installation of libc-l10n ...
dpkg: yes, will deconfigure locales (broken by libc-l10n).
Unpacking libc-l10n (from .../libc-l10n_2.22-9_all.deb) ...
De-configuring locales ...
Preparing to replace libgpg-error-dev 1.10-2ubuntu1 (using .../libgpg-error-dev_1.22-2_amd64.deb) ...
Unpacking replacement libgpg-error-dev ...
Preparing to replace libgpg-error0 1.10-2ubuntu1 (using .../libgpg-error0_1.22-2_amd64.deb) ...
Unpacking replacement libgpg-error0 ...
Processing triggers for man-db ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Errors were encountered while processing:
 /var/cache/apt/archives/locales_2.22-9_all.deb
```

https://travis-ci.org/kullo/smartsqlite/builds/131042898

**Comment by BanzaiMan** [comment]
The package is allowed, even if it's not found. The addon cannot know _a priori_ which packages are available from the sources given in the configuration.
