### ISSUE TITLE
Strange files stored in cache (filename.js and diagrams.graffle)

### ISSUE THREAD

**Issue by blimmer** [travis-ci/travis-ci#6071]
I've been seeing this on my new builds:

```bash
change detected:
diagrams.graffle
filename.js
```

and it doesn't seem related to my project at all.

[example](https://travis-ci.com/Ibotta/partner-portal/jobs/40299453#L1675)

**Comment by BanzaiMan** [comment]
Could you try clearing the cache and see if that helps? We do not write these files, either, so if the caching utility is picking it up as changes, then your build process is doing it. I suggest removing them in `before_cache`.

**Comment by BanzaiMan** [comment]
Is this still a problem? The most recent build does not show these files being detected.

**Comment by blimmer** [comment]
Looks resolved. Closing.
