### ISSUE TITLE
Failing after_script does not fail build

### ISSUE THREAD

**Issue by asbjornu** [travis-ci/travis-ci#6072]
In #758, @drogus mentions that an unsuccessful `after_script` should fail the build:

> There is also `after_script` hook, which runs only if the build passed, but it **will** fail the build.

However, [we have a build here](https://travis-ci.org/GitTools/GitVersion/builds/131213341#L7631) where `unit-console` is run in `after_script` and there's 6 tests failing, which should yield an exit code different to `0`. Travis, however, ends the build with:

> Done. Your build exited with 0.

Is it `nunit-console` that indeed exits with `0` although 6 tests are failing, or is Travis not failing the build, even though it should?

**Comment by danepowell** [comment]
This blog post indicates that the behavior of `after_script` has changed: https://blog.travis-ci.com/after_script_behavior_changes/

**Comment by asbjornu** [comment]
@danepowell I've read that blog post, but it did not lead me to conclude that a failing `after_script` should not fail the build. The only thing I got from that blog post was the order in which the different sections are run and whether the sections themselves will run after a failing previous section. I can't find any information about whether an explosion within `after_script` will make the overall build fail or not.

**Comment by danepowell** [comment]
From the blog post:

> If you rely on the fact that a failure in the after_script phase fails the entire test, you should move such commands to the script phase.

Doesn't that address exactly what you're asking?

You're other option (besides moving `unit-console` to `script`) is to move it to `deploy` using a [script provider](https://docs.travis-ci.com/user/deployment/script). This will only run `unit-console` if `script` passes, but will error out the build if `unit-console` fails.

**Comment by BanzaiMan** [comment]
Indeed, this is documented behavior.

https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build

Please use other stages, as recommended above.

**Comment by asbjornu** [comment]
Ah, I see. The reason I run tests in `after_script` is so the build output is collapsed, so when it is done and succeded, it's only the test output that is automatically visible, making it easier to spot a failing test. When having several steps inside `script`, each step does not seem to visually collapse, making it a bit harder to figure out what went wrong when a build fails.
