### ISSUE TITLE
OS X job fails, log contains "Build dist: precise"

### ISSUE THREAD

**Issue by TheNavigat** [travis-ci/travis-ci#6074]
https://travis-ci.org/TheNavigat/letsencrypt/jobs/131298191

As the commit shows, a section is added to the matrix with `os: osx`. However, on line 9 it says `Build dist: precise`.

I'm not sure what this is, but I think it might be a caching issue.

**Comment by TheNavigat** [comment]
I think this makes it even clearer. https://travis-ci.org/TheNavigat/letsencrypt/builds/131331144, https://travis-ci.org/TheNavigat/letsencrypt/jobs/131331146

**Comment by BanzaiMan** [comment]
It is a default (and incorrect) value in the build payload. You can safely ignore it.

**Comment by TheNavigat** [comment]
This answers my question, if that is enough to close the issue, then I guess it should be closed.

I would personally prefer to keep it open though until that value is corrected.

**Comment by BanzaiMan** [comment]
I'm closing this in favor of #6367.
