### ISSUE TITLE
Update emacs from v23 to v24

### ISSUE THREAD

**Issue by fenollp** [travis-ci/travis-ci#6076]
`emacs24` has been out since 4 years ago ([source](https://www.gnu.org/software/emacs/history.html))

This issue asks for emacs to be updated to emacs24 at least in the docker builds (lightweight builds should run current software, this way people use the lightweight build more often).

Again, 24 is not *latest*, it is *current* and very stable.

**Comment by BanzaiMan** [comment]
Thanks for taking time to open this issue.

We install emacs from the official Ubuntu repository. This means it is [23 for Precise](http://packages.ubuntu.com/precise/emacs) and [24 for Trusty](http://packages.ubuntu.com/trusty/emacs).

Unless the official package gets an update before the next build environment update (no ETA; sorry), this is unlikely to change.

If you need a newer version of emacs for whatever reason, I suggest looking for a newer package.

Thanks.
