### ISSUE TITLE
Unable to locate package libglfw3-dev

### ISSUE THREAD

**Issue by rgkirch** [travis-ci/travis-ci#6078]
This package is in the whitelist.
```
$ sudo apt-get update -qq && sudo apt-get install -y -qq libglew-dev libglfw3-dev libglm-dev
E: Unable to locate package libglfw3-dev
```
I've found someone else with the same error but their solution was just to download and build the source. Why does this not work?
My entire .travis.yml

```
sudo: required
dist: precise
language: cpp
before_install: sudo apt-get update -qq && sudo apt-get install -y -qq libglew-dev libglfw3-dev libglm-dev
script: cmake . && make
```
Thank you.

**Comment by BanzaiMan** [comment]
You need an extra APT source that provides this package. According to https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/83575878#L345, it is [`debian-sid`](https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json#L87-L91).

**Comment by rgkirch** [comment]
Thank you! That works well.
