### ISSUE TITLE
Enable ipv6-over-4 in trusty & container-based with miredo

### ISSUE THREAD

**Issue by Hainish** [travis-ci/travis-ci#6082]
Teredo is an IPv6-over-4 protocol standardized by the IETF in [RFC4380](https://www.ietf.org/rfc/rfc4380.txt).

Other issues such as https://github.com/travis-ci/travis-ci/issues/4964 have requested native IPv6 support in the `trusty` or `container-based` build environment, which travis does not prioritize and can not currently provide.

[Miredo](http://www.remlab.net/miredo/) is an implementation of Teredo which is available in the `ubuntu` and `debian` repositories, using a remote IPv6 relay, and usually works well as an OOTB replacement for networks without native IPv6 connectivity.  Once the `miredo` service starts, a new tunnel interface named `teredo` becomes available, and IPv6 traffic is routed through it.  Although this is not native, kernel support for ipv6 is still of course required.

It seems that in addition to not having the network infrastructure to support IPv6 natively, the `trusty` and `container-based` build environments additionally does not support `miredo`: 
https://travis-ci.org/Hainish/test-travis-ipv6/builds/131556865

I'm not able to determine exactly why, but I suspect it may be because the `ipv6` kernel module is blacklisted.  Is it possible to load this module (or whatever is blocking IPv6 support) in the `trusty` and `container-based` build environments?

**Comment by Joshua-Anderson** [comment]
The trusty and container-based images run on GCE and AWS, neither of which support ipv6. See #4964 The legacy build environment does support ipv6 support, so you could possibly use that.

**Comment by BanzaiMan** [comment]
We have decommissioned legacy infrastructure at this time.

We may revisit this feature in the future, but for now, I am closing this.

**Comment by Hainish** [comment]
@BanzaiMan this is not a request for anything within the legacy infrastructure.  @Joshua-Anderson I am not requesting native IPv6 support, and the issue you mention I already mentioned in my request.  Why exactly was this closed?

**Comment by BanzaiMan** [comment]
Miredo looks stale now, no? And if its support relies on a kernel recompilation, it is highly unlikely that we will add support for it.

**Comment by Hainish** [comment]
How do you mean stale? It works when I install it locally on a non-IPv6 network. Unfortunately I don't know whether it requires a kernel recompilation or not. Probably just requires the ipv6 kernel module and not an entire recompilation.

On May 20, 2016 1:49:15 PM PDT, Hiro Asari <notifications@github.com> wrote:
>Miredo looks stale now, no? And if its support relies on a kernel
>recompilation, it is highly unlikely that we will add support for it.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/travis-ci/travis-ci/issues/6082#issuecomment-220714973

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BanzaiMan** [comment]
"Stale", as in no longer actively developed. The last release was 3 years ago, and the last commit 2. http://git.remlab.net/gitweb/?p=miredo.git

**Comment by Hainish** [comment]
I'm not sure if no commits have been made because the project is in a stable place or because it has been orphaned.

**Comment by Hainish** [comment]
The bot suggests "reopening," but I can not do so, as I am not a project maintainer.  This issue is not resolved yet.
