### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by jasonwilliams200OK** [travis-ci/travis-ci#6086]
We need .NET Core support for Ubuntu and OSX. 

Ubuntu: https://www.microsoft.com/net/core#ubuntu - please white list this aptget feed, so `sudo` isn't needed in any Ubuntu box.

OSX: https://www.microsoft.com/net/core#macosx - please make this PKG pkg available on-demand without `sudo` in any OSX box.

Mono: please make mono optional https://github.com/travis-ci/travis-ci/issues/5189 (we don't need mono when building software with .net core).

**Comment by jasonwilliams200OK** [comment]
FWIW, there are also official docker containers provided https://hub.docker.com/r/microsoft/dotnet

**Comment by BanzaiMan** [comment]
When reporting issues with C#, please include @joshua-anderson @akoeplinger @nterry, as documented. Thanks.

**Comment by jasonwilliams200OK** [comment]
@BanzaiMan, sorry for that. I see the community label added to this issue. By the bye, why can't we have *official* support for .NET Core since there is no huge learning curve involved anymore? Now it's only a 4MB APT package.. https://apt-mo.trafficmanager.net/repos/dotnet/pool/main/d/dotnet-dev-1.0.0-preview1-002702/ and you would be making thousands of GitHub citizens happy.

**Comment by akoeplinger** [comment]
I'll plan on adding .NET Core support as part of https://github.com/travis-ci/travis-ci/issues/5189

**Comment by BanzaiMan** [comment]
@akoeplinger Should this issue be kept alive, or is it sufficient to roll it into #5189?

**Comment by akoeplinger** [comment]
@BanzaiMan Let's roll it into that one.
