### ISSUE TITLE
Octokit "no such file or directory" during deployment step

### ISSUE THREAD

**Issue by reyman** [travis-ci/travis-ci#6088]
Hi,

During github deployment on travis, i have this error due to some gemfile on server : 
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory - 

Deployment failed.
```

**Comment by BanzaiMan** [comment]
Could you point us to a build log URL that shows the problem you are having?

**Comment by reyman** [comment]
Hi,
You can see that here : 
 https://travis-ci.org/gama-platform/gama/builds/131864384

**Comment by BanzaiMan** [comment]
@reyman Does this file exit at the end of the build? `/home/travis/.m2/repository/msi/gama/msi.gama.application/1.7.0-SNAPSHOT/msi.gama.application-1.7.0-SNAPSHOT-linux.gtk.x86.zip`

**Comment by BanzaiMan** [comment]
https://travis-ci.org/gama-platform/gama/builds/131864384#L3424 shows it's getting copied to `/home/travis/.m2/repository/msi/gama/msi.gama.application.product/1.7.0-SNAPSHOT/msi.gama.application.product-1.7.0-SNAPSHOT-linux.gtk.x86.zip` Your path is wrong.

**Comment by reyman** [comment]
Ok, sorry, arg, the path moved ... thanks.
