### ISSUE TITLE
Enabling the Docker service on hhvm environments causes phpenv to fail

### ISSUE THREAD

**Issue by chrismichaels84** [travis-ci/travis-ci#6091]
This same to be the same problem as #4750, except with the hhvm image. I am trying to use docker to run database services and then php and hhvm to run phpunit. All the php versions work, but the hhvm environment fails.

The builds in question are https://travis-ci.org/spider/spider/jobs/131823021 and others in the spider/spider branch docker.

I have the following .travis.yml file
```php
sudo: required
language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
   - php: nightly
   - php: hhvm      # only until docker container can be built

services:
  - docker

env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
    - DOCKER_COMPOSE_VERSION=1.7.1

before_install:
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

  # reinstall docker-compose at specific version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose up -d
  - sleep 10
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
```

I do have a utility `bin/spider-dev` that can run the tests through a setup php docker container. Is that my only option? To forgo Travis's languages and just just docker 100%? Or is there a plan to support hhvm when using docker?

**Comment by BanzaiMan** [comment]
In the log, you see that HHVM is not available.

PHP is not yet supported on Trusty.

Of you want to test it, please use the edge image.

```yaml 
group: edge 
```
