### ISSUE TITLE
R on Mac OS X does not honor "oldrelease"/"devel" versions

### ISSUE THREAD

**Issue by janschulz** [travis-ci/travis-ci#6092]
This is https://github.com/IRkernel/IRkernel/pull/330 which implements tests on both OSX and linux and on three R verisons (oldrelease, release, devel), but it seems that the OS X version of the tests does not installs oldrelease/devel but always latest: the R Session information alsways display a R 3.3 build on OSX but the correct 3.2 and "R Under development (unstable)" versions on linux.

Examples from https://travis-ci.org/IRkernel/IRkernel/builds/132126581
* https://travis-ci.org/IRkernel/IRkernel/jobs/132126591 (oldrelease)
* https://travis-ci.org/IRkernel/IRkernel/jobs/132126589 (devel)

```

**Comment by BanzaiMan** [comment]
When reporting issues with community-maintained languages, please mention the maintainers, as shown in the logs.

Paging @craigcitro @hadley @jimhester

**Comment by jimhester** [comment]
Multiple R versions are only supported on linux precise builds, this is documented at https://docs.travis-ci.com/user/languages/r#R-Versions.

Nonetheless I just sent a PR which should address this (https://github.com/travis-ci/travis-build/pull/735), so this should work after that is merged and deployed.

**Comment by janschulz** [comment]
@jimhester This is great, thank you!
