### ISSUE TITLE
exiftool - command not found although it is whitelisted in container builds

### ISSUE THREAD

**Issue by AbdealiJK** [travis-ci/travis-ci#6093]
I was trying to install exiftool on the container builds.
I found that the package libimage-exiftool-perl is already whitelisted in the apt-package-whitelist and so I tried using it.

I found that exiftool gets installed successfully but the binary `exiftool` is not found.
Here is the log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/132175322/log.txt

It only says "command not found"

**Comment by BanzaiMan** [comment]
The exact error message is:

```sh-session
$ {:"echo \"EXIFTOOL"=>"$(exiftool -ver)\""}
/home/travis/build.sh: line 45: {:echo "EXIFTOOL=: command not found
```

Take a look at your [`.travis.yml`](https://github.com/AbdealiJK/file-metadata/blob/8b0e45056604d9955efca49657183d53f6100133/.travis.yml#L70). The line 70 defines a map, with the key `echo "EXIFTOOL` and the value `$(exiftool -ver)"`.

I suspect you meant something like:

```yaml
- `echo "EXIFTOOL: $(exiftool -ver)"'
```

See https://travis-ci.org/BanzaiMan/travis_production_test/builds/132195375#L157

**Comment by AbdealiJK** [comment]
Darn, I didn't read it properly.
Thanks !
