### ISSUE TITLE
py.test not returning after passing all tests in container

### ISSUE THREAD

**Issue by brackendawson** [travis-ci/travis-ci#6097]
I'm having a seemingly random problem.

I made a commit which on my machine passes, but on travis passed and then never exited: https://travis-ci.org/somakeit/door-controller2/builds/130965876

I then worked on a branch changing the way the recent tests I had added ran until travis worked again, I made a PR back to master and all was passing: https://travis-ci.org/somakeit/door-controller2/builds/132084380

I merged the PR into master and it failed again: https://travis-ci.org/somakeit/door-controller2/builds/132085414 :'-(

Is there a way I can find out what's randomly keeping py.test from returning?

**Comment by BanzaiMan** [comment]
I don't have a very good idea of what might be happening, but we can set up a debug VM for you to investigate further. Please email support@travis-ci.com.

**Comment by brackendawson** [comment]
I tried disabling py.test's caching, it went away for a bit but now it's back: https://travis-ci.org/somakeit/door-controller2/builds/137067132

In this case the commit on master passed, but the failing build is on a tag on that very commit.

Would like to debug please.

**Comment by acnagy** [comment]
Thanks @brackendawson! We'll follow up via email.
