### ISSUE TITLE
Stuck on the 'one more thing' page

### ISSUE THREAD

**Issue by keyboardDrummer** [travis-ci/travis-ci#6098]
Today is the first day I've tried Travis. However I haven't been able to use the service since it's stuck trying to connect to my GitHub account, which is https://github.com/keyboardDrummer

What could be the issue?

**Comment by BanzaiMan** [comment]
Sorry about the issue. Could you attach a screen shot of what you are seeing?

**Comment by keyboardDrummer** [comment]
The issue resolved itself today. I'm guessing it was related to the GitHub outage yesterday.
