### ISSUE TITLE
boost.python: Unable to find pyconfig.h

### ISSUE THREAD

**Issue by AbdealiJK** [travis-ci/travis-ci#6099]
I am trying to compile boost in the virtualenv so that I compile/install dlib which uses boost.python.

I am compiling it by giving it the args `--prefix=$VIRTUAL_ENV` so that it would get configured and installed into the virtualenv and use the python version that is needed for that job. (I need jobs for 2.6, 2.7, 3.3, 3.4, 3.5)

Boost complains `fatal error: pyconfig.h: No such file or directory`. I also checked `find $VIRTUAL_ENV -name pyconfig.h` and it did not return any results. So, it seems like the virtualenv in travis does not have pyconfig.h.
On doing `find / -name pyconfig.h` [here](https://travis-ci.org/AbdealiJK/file-metadata/builds/132495623) I found that this file is at:
```
/opt/python/2.6.9/include/python2.6/pyconfig.h
/opt/python/2.7.9/include/python2.7/pyconfig.h
/opt/python/3.2.5/include/python3.2mu/pyconfig.h
/opt/python/3.3.5/include/python3.3m/pyconfig.h
/opt/python/3.4.2/include/python3.4m/pyconfig.h
/opt/python/pypy-2.5.0/include/pyconfig.h
/opt/python/pypy3-2.4.0/include/pyconfig.h
```

Could you recommend how I can compile this ? Is the pyconfig.h not expected to be in the virtualenv ?

The build can be found at https://travis-ci.org/AbdealiJK/file-metadata/builds/132498595

**Comment by BanzaiMan** [comment]
Hmm. Why is it not finding `/opt/python/3.5.0/include/python3.5m/pyconfig.h`? What is `$VIRTUAL_ENV` and how is it supposed to be set? I don't think our build script sets it.

**Comment by AbdealiJK** [comment]
I have been using `$VIRTUAL_ENV` in travis builds for a while when I need the python virtualenv's path. If it's not being set by travis, I'm guessing it's being added by the package that created the `virtualenv`

https://travis-ci.org/AbdealiJK/file-metadata/jobs/132522625#L487 shows the value - `/home/travis/virtualenv/python3.5.0` for python 3.5 and `/home/travis/virtualenv/python2.7.9` for python 2.7

**Comment by BanzaiMan** [comment]
Could you try `python: 3.5.1`?

**Comment by AbdealiJK** [comment]
I began using minicond with travis (http://conda.pydata.org/docs/travis.html) as it had an easy installer (`conda install boost`) and also had easy installation methods for a bunch of other packages I needed.
This reduced my build time as I didn't need to build them (conda has pre-built binaries).

Hence, I'm closing this issue
