### ISSUE TITLE
Don't inherit explicitly email notification on forks

### ISSUE THREAD

**Issue by junghans** [travis-ci/travis-ci#6100]
When listing an email address in upstream's `.travis.yml`:

```
notifications:
  email:
    - abc@def.com
```

this get inherited by any fork, which is a bit annoying for upstream as they don't really need to know what happens in the fork.

So it would be nice to have some mechanism to have per-repository notification. One could role it own thing using encrypted variables (which don't get inherited), e.g.:

```
after_script:
  - if [[ ${ENCRYPTED} ]]; then echo notification | mail abc@def.com
```

This will work, but it would be nicer to get an email like **standard** travis email.

**Comment by junghans** [comment]
This is related to #1094!

Workaround by @martinec, store email encrypted:
```
encrypt "abc@def.com" --add notifications.email.recipients
```

**Comment by junghans** [comment]
Still relevant!

**Comment by junghans** [comment]
Thanks @stale, but not fixed!

**Comment by junghans** [comment]
Still not fixed!

**Comment by junghans** [comment]
Is this fixed?

**Comment by jesskie** [comment]
It came from you

jess

**Comment by jesskie** [comment]
That's good god bless you

jess
