### ISSUE TITLE
hit timeout issue for waiting for emulator to start using Android 23 version

### ISSUE THREAD

**Issue by helenren** [travis-ci/travis-ci#6104]
I use this android-wait-for-emulator script in my yml file to wait the emulator ready before run the test. While, on Android 23, it always timeout. While it works fine for other versions: 19,21 and 22. Is this a known issue on travis ci? Tried to use the same emulator locally, it works fine.  Here is the yml file I use: https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/unstable/.travis.yml. Is there anything I missing? Thanks

**Comment by ErjanGavalji** [comment]
I get [the same sporadically starting Android-22](https://travis-ci.org/NativeScript/NativeScript/builds/132863841). Any ideas what's wrong? Did the `android-wait-for-emulator` script get changed for some containers, but not others?

**Comment by barbeau** [comment]
You need to add the following to build.gradle within your `android` section:

    // This enables long timeouts required on slow environments, e.g. Travis
    adbOptions {
        timeOutInMs 20 * 60 * 1000  // 20 minutes
        installOptions "-d","-t"
    }

See https://code.google.com/p/android/issues/detail?id=189764#c19 for details.  Your Android Gradle plugin also needs to be `2.0.0-beta3` or higher.

**Comment by ErjanGavalji** [comment]
Thanks!
Giving it a try...
