### ISSUE TITLE
PHP 7.0.7

### ISSUE THREAD

**Issue by tiger-seo** [travis-ci/travis-ci#6106]
Please, can we get an upgrade to 7.0.7 (released today).
thank you

**Comment by BanzaiMan** [comment]
Will build it when https://github.com/php-build/php-build definition is updated.

**Comment by tiger-seo** [comment]
@GrahamCampbell please, help :wink:

**Comment by Ocramius** [comment]
Provided a patch for that in https://github.com/php-build/php-build/pull/380
🎱

**Comment by Ocramius** [comment]
The definitions are updated as per https://github.com/php-build/php-build/commit/f36ea7b13055ced08a9c77ca000685608da827e1

**Comment by BanzaiMan** [comment]
`7.0` now points to `7.0.7`. (Needless to say, `7.0.7` does, too.)

See https://travis-ci.org/BanzaiMan/travis_production_test/builds/133258630.

**Comment by Ocramius** [comment]
@BanzaiMan :+1:
