### ISSUE TITLE
Failed to fetch package hhvm - Unable to connect to dl.hhvm.com

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#6107]
the following error is repeatedly happening (`5/27/16 @9:30am MDT`) restarting builds is not fixing this issue. dl.hhvm.com is web accessible. 

```
Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty-lts-3.12/InRelease  
W: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty-lts-3.12/Release.gpg  Unable to connect to dl.hhvm.com:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
0.29s$ sudo apt-get install -y hhvm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hhvm
```

**Comment by photodude** [comment]
This seems to have self-resolved by (`5/27/16 @9:50am MDT`).

**Comment by BanzaiMan** [comment]
Perhaps we can add retries.

**Comment by photodude** [comment]
Ya, there are other strange things going on with the trusty builds. Sometimes builds that have completed or have been canceled will go back into "create/booting" and rerun possible up to 3 or more times.

I do agree that it might be good to have retries for fetching the hhvm packages.

**Comment by BanzaiMan** [comment]
Unconditionally retrying `apt-get install` is actually a bad idea. We have had some attempts previously (e.g., https://github.com/travis-ci/travis-build/pull/605), but have not come to a reliable solution yet.

At the moment, `apt-get install` failure should result in build error.

**Comment by photodude** [comment]
sounds good, thanks.
