### ISSUE TITLE
Travis-ci.org web UI issue

### ISSUE THREAD

**Issue by NinoSkopac** [travis-ci/travis-ci#6108]
The calendar icon's title is unix epoch time.

![travis bug](https://cloud.githubusercontent.com/assets/1783732/15613523/14a2c23a-245e-11e6-9532-7b435b183412.png)

![travis bug 2](https://cloud.githubusercontent.com/assets/1783732/15613579/4f187310-245e-11e6-87c2-7590d6b8613e.png)

**Comment by lislis** [comment]
Hey @NinoSkopac! Thank you for reporting this bug!

I fixed it here  https://github.com/travis-ci/travis-web/commit/c91e012bc96aade7375e02ec2fa87fbf7bccf1f2 and it is now live in production.

Closing this. Cheers!

![high five](http://i.giphy.com/9o67upvAnOqRy.gif)
