### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by tainarareis** [travis-ci/travis-ci#6110]
Why the build is failing?

Here the errors:
https://travis-ci.org/tainarareis/Urutau/jobs/133647774

.travis.yml
`language: java
script: mvn package
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
jdk:
  - oraclejdk8
  - oraclejdk7`

**Comment by BanzaiMan** [comment]
Your default mvn task is falling. Please fix it. https://travis-ci.org/tainarareis/Urutau/jobs/133647774#L960
