### ISSUE TITLE
having '&' character in the environment variable doesn't set it properly

### ISSUE THREAD

**Issue by typekpb** [travis-ci/travis-ci#6111]
Having defined `DOCKER_PASSWORD=<some random stirng>&<some random stirng>`
causes environment variable to be set incorrectly (for details, see: https://travis-ci.org/datarator/datarator/builds/133498140).

In my unlucky case part of the pwd is beeing logged in the build log (sounds like a serious security problem to me).

Btw: 

* I've changed my dockerhub pwd in the meantime.
* I'm not 100% sure the `&` character was problematic there, but somehow I believe that :)

**Comment by BanzaiMan** [comment]
This is a variation of #2477. If you need special characters, you should put them in single quotes to avoid bash interpretation.
