### ISSUE TITLE
cache timeout when loading /usr/local from 300mb tgz file

### ISSUE THREAD

**Issue by gabyx** [travis-ci/travis-ci#6115]
I have a problem that I want to cache the `/usr/local/include` ,  `/usr/local/lib` and `/usr/local/share`
directories since I need to install alot of dependencies which take almost 50min of time.

The cache I build in a first step, which succeeds but then downloading and installing the cache timeouts
after 10minutes since no output ??

Does somebody know what the problem is here

https://travis-ci.org/gabyx/GRSFramework/builds/134053067

Thanks a lot

**Comment by BanzaiMan** [comment]
Sorry, but is there a recent build that shows the problem? It appears that you've deleted the cache, and then proceeded to change the configurations.

**Comment by gabyx** [comment]
OK, https://travis-ci.org/gabyx/GRSFramework/builds/134274650

it works now it seems that the cache hangs when trying to copy the cache to "sudo" dirs as `/usr/local`
I made the cache now local in the $HOME directory, now everything works fine

**Comment by BanzaiMan** [comment]
Good to hear that you've found a working soution. Is there anything else to do here?

**Comment by gabyx** [comment]
May be to mention in the Cache Help section, that one should not cache system folders with non-user permission which need sudo to copy to and from...

then the cache works =) otherwise the cache timesout (?) giving no error ...

**Comment by joepvd** [comment]
A warning was introduced with https://github.com/travis-ci/docs-travis-ci-com/pull/751. Thanks for suggesting!
