### ISSUE TITLE
Update URL to fetch Elixir builds

### ISSUE THREAD

**Issue by ericmj** [travis-ci/travis-ci#6117]
The URL http://s3.hex.pm is being deprecated in favor of https://repo.hex.pm.

/cc @BanzaiMan

**Comment by BanzaiMan** [comment]
@ericmj Is this broken right now?

**Comment by ericmj** [comment]
Not at all, but it will eventually be broken if you don't change it. We are talking about at least 6 months out, so no hurry.

**Comment by adrienmo** [comment]
Hi @BanzaiMan, could you check at the same time why #6116 is happening ?
Thanks!

**Comment by BanzaiMan** [comment]
@adrienmo That's almost certainly unrelated.
