### ISSUE TITLE
Triggering jobs via the API is not working

### ISSUE THREAD

**Issue by mernst** [travis-ci/travis-ci#6118]
I am not able to triggering builds through the API, as described at
https://docs.travis-ci.com/user/triggering-builds/ .

I pasted the following into my shell:

```
body='{
"request": {
  "branch":"master"
}}'

curl -s -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Travis-API-Version: 3" \
  -H "Authorization: token MYTOKENHERE" \
  -d "$body" \
  https://api.travis-ci.org/repo/codespecs%2Ftest-daikon-staging/requests
```

and the result was 

```
{
  "@type": "pending",
  "remaining_requests": 10,
  "repository": {
    "@type": "repository",
    "@href": "/repo/8226525",
    "@representation": "minimal",
    "id": 8226525,
    "name": "test-daikon-staging",
    "slug": "codespecs/test-daikon-staging"
  },
  "request": {
    "repository": {
      "id": 55711026,
      "owner_name": "codespecs",
      "name": "test-daikon-staging"
    },
    "user": {
      "id": 202480
    },
    "message": null,
    "branch": "master",
    "config": {
    }
  },
  "resource_type": "request"
}
```

but the job at https://travis-ci.org/codespecs/test-daikon-staging did not get run.

Other invocations, which were working as of yesterday, are also failing today.  I double-checked that my token has not changed in the meanwhile.

Can you let me know whether the instructions are out of date, or I need to do something differently, or there is a problem that is outside my control?

Thanks!

**Comment by markandrus** [comment]
I have the same issue. I also see that "remaining_requests" is never decremented.

**Comment by acnagy** [comment]
Hey @mernst and @markandrus - thanks so much for reporting this. We've just deployed a fix, so you should be good to go with triggering builds from the API. Please feel free to let us know/re-open here if you see any further issues. Thanks again!

**Comment by mernst** [comment]
This seems to be working for me -- at least, the example in my original report works.

Thanks very much for the fix!

**Comment by DanielCreagh** [comment]
It looks like this is down again.

I receive a response as expected but cannot see the job being triggered on the Travis web control panel.

Anyone else having this issue?

**Comment by mkruszynski** [comment]
Hi,
I'm having the same issue.
Job was triggered only once, now I'm getting only response, job isn't triggered.

**Comment by frowing** [comment]
Hi, I'm having this issue running a private repo. When I run
```
body='{
 "request": {
 "branch":"development",
 "config": {
   "script": "fastlane ios uitests"
  }
}}'

curl -v -X POST \
   -H "Content-Type: application/json" \
   -H "Accept: application/json" \
   -H "Travis-API-Version: 3" \
   -H "Authorization: token $1" \
   -d "$body" \
   https://api.travis-ci.com/repo/lonelyplanet%2Flpm-flagship-ios/requests
```
I get: 
```
{
  "@type": "pending",
  "remaining_requests": 47,
  "repository": {
    "@type": "repository",
    "@href": "/repo/742916",
    "@representation": "minimal",
    "id": 742916,
    "name": "lpm-flagship-ios",
    "slug": "lonelyplanet/lpm-flagship-ios"
  },
  "request": {
    "repository": {
      "id": 31445154,
      "owner_name": "lonelyplanet",
      "name": "lpm-flagship-ios"
    },
    "user": {
      "id": 96474
    },
    "id": 74704129,
    "message": null,
    "branch": "development",
    "config": {
      "script": "fastlane ios uitests"
    }
  },
  "resource_type": "request"
```
The number of remaining requests is decreased but then if I go to the website there are no jobs running.

Any ideas what might be going on?

**Comment by BanzaiMan** [comment]
@frowing Please email us at support@travis-ci.com for support. Thanks.

**Comment by frowing** [comment]
@BanzaiMan I just messaged you guys from the `Help` menu in the website.
