### ISSUE TITLE
Crystal tests: macro error (not defined before used)

### ISSUE THREAD

**Issue by mauricioabreu** [travis-ci/travis-ci#6119]
I just enabled Travis on my Crystal project and it fails with the following error:

```
0.19s$ crystal spec

Error in ./spec/legends/champion_spec.cr:24: macro 'be_a' must be defined before this point but is defined later

        champions.should be_a(Array(Legends::Champion))
```

It does not happen on my machine. I am running Ubuntu 14.04 and my Crystal version is 0.17.4.
Can you help on indentify the bug?

Here is the full output: https://travis-ci.org/mauricioabreu/crystal-legends/jobs/134244923

@asterite @jhass @waj @will

**Comment by jhass** [comment]
I'm getting the same error locally when running `crystal spec`. How do you run your specs locally?

**Comment by asterite** [comment]
You are doing `require "spec"` after using `be_a`. If you put `require "spec"` as the first line of spec_helper, it works.

**Comment by asterite** [comment]
Maybe we should just change the error to "undefined macro 'be_a'", so it's maybe more obvious that a require is missing before that point?

**Comment by mauricioabreu** [comment]
@asterite it looks more friendly and reasonable.

**Comment by mauricioabreu** [comment]
@jack-pappas I just run `crystal deps`.

**Comment by jhass** [comment]
@mauricioabreu `crystal deps` does not run the specs, it just installs the project dependencies (same as `shads`). Run `crystal spec` to run the specs.

**Comment by mauricioabreu** [comment]
@jack-pappas sorry, I meant `crystal spec`. :-)

**Comment by jhass** [comment]
Well I can't reproduce and Ary apparently neither and gave a fix.

**Comment by mauricioabreu** [comment]
@jack-pappas for me too! It is fixed now.

Thanks @asterite !

**Comment by mauricioabreu** [comment]
Thanks for the help!
