### ISSUE TITLE
Skipping builds does no longer work

### ISSUE THREAD

**Issue by crapp** [travis-ci/travis-ci#6121]
I can no longer skip builds with [ci skip]. I was using this successfully for quite some time. 

I have just issued a commit which triggered this build
https://travis-ci.org/crapp/ealogger/builds/134463412

This is the commit I am talking about
https://github.com/crapp/ealogger/commit/8f2f5eaf09a44f8b786ea20a3f2ead01ac0b2ffc

As you can see I was adding [ci skip] to the commit message but build number 47 was started nonetheless.

**Comment by MariadeAnton** [comment]
Thanks for opening the issue, @crapp!

I just run a quick test and believe this might be happening due to the double spacing in the `[ci skip]` message, could you check that out? Thanks!

**Comment by BanzaiMan** [comment]
Indeed, this looks like a bug (or, at least, inconsistent implementation of the magic comment). If you write `[skip ci]`, the number of spaces between the words does not matter (i.e., `[skip         ci]` still works), while  if you write `ci` first, exactly one space is required.

**Comment by crapp** [comment]
@MariadeAnton  Yes I just tried with exactly one space between ci and skip and that worked. I have to admit I didn't realize i used two spaces at first and it wasn't intentional of course. Thanks for pointing this out to me

**Comment by atz** [comment]
Looks like this can be closed since multiple-spaces is not a documented feature to be protected.

**Comment by BanzaiMan** [comment]
This should be working now.
