### ISSUE TITLE
`sudo apt-get update` issues in Trusty builds

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/travis-ci#6124]
`sudo apt-get update` might fail due to issues with Docker's APT get repo, see: https://github.com/docker/docker/issues/23203

The output would be similar to: 

```
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  Hash Sum mismatch
```

**Comment by obazoud** [comment]
Same probleme with Ubuntu Trusty on Travis CI:

```
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  Hash Sum mismatch
```

**Comment by denniswambua** [comment]
Different problem but affected but apt-get update

`The command "sudo -E apt-get -yq update &>> ~/apt-get-update.log;" failed and exited with 100 during .`

**Comment by bivald** [comment]
W: There is no public key available for the following key IDs:
1397BC53640DB551
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  Hash Sum mismatch

**Comment by obazoud** [comment]
```
W: There is no public key available for the following key IDs:
1397BC53640DB551
```
It's about Google Chrome.

My workaround:
```
sudo apt-get remove -y google-chrome-stable && sudo rm -f /etc/apt/sources.list.d/google-chrome.list*
```

**Comment by MariadeAnton** [comment]
Here's a proposed workaround for the Docker issues: 

https://github.com/docker/docker/issues/23203#issuecomment-223305792

**Comment by MariadeAnton** [comment]
This issue should have been resolved now by the Docker team, see: https://github.com/docker/docker/issues/23203#issuecomment-223328829
