### ISSUE TITLE
Weird disagreement between two Travis runs

### ISSUE THREAD

**Issue by SirCmpwn** [travis-ci/travis-ci#6127]
https://github.com/linode/manager/pull/51

The build is not inconsistent, this is a new problem.

**Comment by BanzaiMan** [comment]
Sorry, but could you please give us more details about what you are reporting? Which two runs show the problem? If "The build is not inconsistent," then there isn't a problem, is there? The GitHub issue you linked to is lacking details we can look into.

**Comment by SirCmpwn** [comment]
Sorry, I meant to say that our build process isn't inconsistent. The same commit will produce the same build results every time, which suggests that Travis got borked.

The branch build passed: https://travis-ci.org/linode/manager/builds/134824965

But the PR build failed: https://travis-ci.org/linode/manager/builds/134824961

This inconsistency happend twice, here's the previous builds:

https://travis-ci.org/linode/manager/builds/134821993

https://travis-ci.org/linode/manager/builds/134821997

**Comment by SirCmpwn** [comment]
One particularly weird thing is the linting errors that come up in the PR build, they refer to a linting error on a line of code that has no such error.

**Comment by SirCmpwn** [comment]
Got it - the branch was out of sync with master and merging master in would cause tests to fail. Didn't realize that was what was happening.
