### ISSUE TITLE
support for musl libc / Alpine Linux

### ISSUE THREAD

**Issue by ncopa** [travis-ci/travis-ci#6128]
It would be nice to be able to set up an environment with musl libc (for example Alpine Linux), either as VM or as docker image.

**Comment by BanzaiMan** [comment]
It is very unlikely that we support anything other than Ubuntu in the near future. Your best bet is to use Docker image with Trusty. https://docs.travis-ci.com/user/trusty-ci-environment https://docs.travis-ci.com/user/docker/

**Comment by marcbachmann** [comment]
Wouldn't it be less work for you if you just offer an alpine linux image that doesn't contain any software? I guess the boot process would also be much faster.

We can manage all the necessary dependencies on our own. We're just using docker.

**Comment by hypoalex** [comment]
Just wanted to put forth a big +1! This would be great.

**Comment by te-online** [comment]
It's understandable that it's hard to keep multiple images secure and that's why you have a rock solid Ubuntu LTS as a base. (*dream-mode-on*) However, imagine one second, how fast all of our builds could be run in a container that starts up so much faster than ubuntu (*dream-mode-off*) 😉

**Comment by cfriedt** [comment]
A thousand times #this - alpine linux packages tend to be *far* smaller than ubuntu packages, so updating a base image is far faster, but also the base image itself is a fraction of the size. There may not be every package under the sun available, but there are many. Also musl is a great libc to build against for those concerned with standards and portability.

**Comment by cfriedt** [comment]
Lastly, alpine linux docker images work on *every architecture*

**Comment by mirabilos** [comment]
@cfriedt I doubt that, considering musl doesn’t even build on Debian/alpha, hppa, ia64, powerpc, ppc64, sparc64, x32, let alone Hurd and kFreeBSD…

(but +1 otherwise, it would be useful to be able to just add musl to the matrix, having just added freebsd and osx the other day; I don’t do docker so the advice wouldn’t help me)

**Comment by cfriedt** [comment]
> @cfriedt I doubt that, considering musl doesn’t even build on Debian/alpha, hppa, ia64, powerpc, ppc64, sparc64, x32, let alone Hurd and kFreeBSD…

Hmm.. supports ppc64, ppc, x32, ..

https://wiki.musl-libc.org/supported-platforms.html
https://packages.gentoo.org/packages/sys-libs/musl

At least every architecture distributed on Docker Hub (which was the point).

https://hub.docker.com/_/alpine

Hurd / kFreeBSD are not architectures of course..
