### ISSUE TITLE
Elixir default script. Problem with solution

### ISSUE THREAD

**Issue by lau** [travis-ci/travis-ci#6130]
In Elixir 1.3 rebar is needed for Erlang dependencies (very common).

Today by default scripts hang (example: https://travis-ci.org/lau/calendar/jobs/135116107 ) waiting for confirmation to install rebar.

It could be fixed by adding `- mix local.rebar --force` to `before_script` (at the end).

**Comment by marceldegraaf** [comment]
Thanks, this saved my butt on an Elixir 1.3 project with Travis 🍻

**Comment by BanzaiMan** [comment]
We now run `mix local.rebar --force` if Elixir 1.3.0 and up is detected.
