### ISSUE TITLE
Email notification although private email @users.noreply.github.com

### ISSUE THREAD

**Issue by Rotzbua** [travis-ci/travis-ci#6133]
Hi,
I use private email option from github. So my commit email is name@users.noreply.github.com. As in the documentation noticed, this email will be used for notification. The result is that I do not get any build notifications.

I think travis should know the primary email address from github sync, so name@users.noreply.github.com to name@primaryprivate.address should work.
Is it possible to get email notifications without make them public?

**Comment by BanzaiMan** [comment]
Is that address contained in the git commit data? https://docs.travis-ci.com/user/notifications/#How-is-the-build-email-receiver-determined%3F

**Comment by Rotzbua** [comment]
Yes, the name@users.noreply.github.com is contained in the git commit data.

My workaround is to add the mail address directly to the `.travis.yml`. To avoid that I get mails from forks I encrypted it with https://docs.travis-ci.com/user/encryption-keys/ .

**Comment by edmorley** [comment]
In case it helps anyone else, I emailed support@ about this, and the reply was:

> Travis CI generally sends email notifications to the email address specified in your Git commit, however, we only send to email addresses that GitHub tells us are known.
> 
> As you noticed, your build https://travis-ci.org/mozilla/treeherder/builds/292166378 has both as the committer and author your GitHub no reply emails, so build notifications are unfortunately being sent to the no-reply box.
> 
> We do have plans to improve this in the future and allow people to overwrite this behaviour. However, there's no ETA for that at this moment.

**Comment by edmorley** [comment]
Still applies (and is something that I hit multiple times a week)

**Comment by oncletom** [comment]
Likewise, I have ticked this box to _not_ make the email address accessible.

![image](https://user-images.githubusercontent.com/138627/42918103-a8ecc960-8b0c-11e8-9d97-0445983633fe.png)

Adding the email in plaintext in `.travis.yml` file defeats the purpose of privacy, not to mention the number of repo it affects.

I was wondering: because the GitHub account is linked, could we consider sending the email to the _Primary email address_ if the commit e-mail is considered as private?

![image](https://user-images.githubusercontent.com/138627/42918202-21c3c690-8b0d-11e8-9a4f-9ab292433cca.png)

**Comment by Skidushe** [comment]
I agree, for now I have made myself a gmail account with for example (me).github@gmail.com and set that as my primary email, and unchecked the privacy option, however I do hope this can happen

**Comment by floehopper** [comment]
I'm seeing this problem too. Something like the behaviour @oncletom suggests would be great!

**Comment by muehan** [comment]
so many years (found closed tickets older then this) and still there is no option to overwrite the email address or have a dropdown to select a specific address from the github addresslist...

any chance that this does change soon?

**Comment by aroxby** [comment]
I would also find this feature very useful.

**Comment by jack1142** [comment]
In case anyone looks here, you can set the email notifications and keep your email private if you use `!secret` in email field (look [here](https://docs.travis-ci.com/user/encryption-keys/#usage)):
```yaml
notifications:
  email:
    recipient:
      - secure: "SECURE STRING GENERATED WITH TRAVIS ENCRYPT COMMAND"
```
