### ISSUE TITLE
Cannot use System.Numerics.

### ISSUE THREAD

**Issue by Samueljh1** [travis-ci/travis-ci#6137]
Hi, I am unable to build projects that use the System.Numerics reference. Is there anyway I can fix this?

**Comment by BanzaiMan** [comment]
Paging @joshua-anderson @akoeplinger @nterry

**Comment by jayvdb** [comment]
I am pretty sure I saw this recently, and the fix for me was to install the APT 'package' `mono-complete`, which drags in way too much, but solved the problem.  I suspect that listing APT package `libmono-system-numerics4.0-cil` will do the trick.

**Comment by akoeplinger** [comment]
`libmono-system-numerics4.0-cil` is a dependency of `mono-devel` which we preinstall, so that shouldn't be required.

@Samueljh1 can you share a sample project/build log=

**Comment by Samueljh1** [comment]
I got a bunch of these errors:

	Core/Misc/ImageMaps/CustomItemFrame.cs(78,114): error CS0246: The type or namespace name `Vector3' could not be found. Are you missing an assembly reference?

**Comment by akoeplinger** [comment]
Vector3 is actually part of System.Numerics.Vectors.dll which was added to .NET in 4.6. We don't support those out of the box in Mono yet.

But you should be able to get the implementation from this NuGet package: https://www.nuget.org/packages/System.Numerics.Vectors/4.0.0 (not that you should use version 4.0.0 of the package as the later versions are targetting the new .NET Standard which might not work yet).

**Comment by Samueljh1** [comment]
Yeah, I tried that, but I got an error saying the nuget version was too low to install the package

**Comment by akoeplinger** [comment]
@Samueljh1 then you didn't install version 4.0.0 of the package but a later version.

**Comment by Samueljh1** [comment]
@akoeplinger Hi, i cant seem to find a way to install nuget 4.0.0. What would the command be?

**Comment by akoeplinger** [comment]
@Samueljh1 that depends on where you do it, if you're in Visual Studio you can open up the Package Management Console and run `Install-Package System.Numerics.Vectors -Version 4.0.0`.

In Xamarin Studio you can open the Add Packages dialog and type `System.Numerics.Vectors version:4.0.0` into the search box.

On the command line you'd use `nuget install System.Numerics.Vectors -Version 4.0.0` but in this case you'll need to wire up the path to the dll in the .csproj yourself.

**Comment by Samueljh1** [comment]
Sure, done that, but i think you guys need to update nuget on all nodes. Alot of new versions on packages i use require v4.0.0.

E.g; The 'System.Globalization 4.0.10' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.8.7.0'.

**Comment by akoeplinger** [comment]
We added the missing Vector APIs as part of https://bugzilla.xamarin.com/show_bug.cgi?id=41537.

We're also working on updating NuGet, but it is a bit more complex due to all the dependencies.

@BanzaiMan I think this can be closed now, there's nothing for Travis to do here :)
