### ISSUE TITLE
Ambiguous travis-build invocation instructions

### ISSUE THREAD

**Issue by ndmeiri** [travis-ci/travis-ci#6138]
The instructions under the travis-build [invocation README section](https://github.com/travis-ci/travis-build#invocation) are ambiguous. For the remainder of this issue, I refer to the three ways that the `travis compile` command can be invoked (according to the order in the README) as Method 1, Method 2, and Method 3, respectively.

Here are just a few examples of the ambiguity:

1. Method 2 involves passing a single integer to `travis compile`, but what that integer represents is unclear. Is it the ID for a build? The ID for a job?

1. And the description for Method 2 may confuse a user even more. "It produces the script for the given build" could mean that Travis uses the `.travis.yml` of the build with an ID equal to the passed integer or it could mean that Travis uses the `.travis.yml` in `$PWD` if it exists. This should be clarified in the description of Method 2 to prevent confusion. Also, after looking through the source code, I think "or the first job of that build matrix" in the Method 2 description should be changed because, when a single integer is passed, the generated script is _always_ for the first job. Furthermore, the phrase "that build matrix" is unclear because the reader could be unsure what "that" is referring to.

1. The invocation section doesn't mention how or if the `compile` command will fail if the passed argument contains an entity ID that does not exist.

Can you please help me understand the invocation section so that I can submit a PR to improve the travis-build README? Thanks!

**Comment by facascante** [comment]
i tried it in windows and it seems that command travis. is not installed

i tried this

vagrant up
vagrant ssh
cd /vagrant
bundle exec rspec spec

the vagrant is up but i do not know how to use it

no travis command?

can you help me

**Comment by ndmeiri** [comment]
@facascante Have you installed the `compile` command? Try following the instructions at https://github.com/travis-ci/travis-build/blob/master/README.md#use-as-addon-for-cli, and let me know if that works for you.

**Comment by BanzaiMan** [comment]
As the document states, this is a plugin for the CLI client. With the CLI client, builds and jobs are referred to by their numbers, not their IDs.

If the build or job with the given number does not exist, we would end up with `nil` for the job we want to compile the build script for, and the script will fail.

```sh-session
$ travis compile 33313133
undefined method `jobs' for nil:NilClass
for a full error report, run travis report
```

@facascante The use of Vagrant is documented for running the tests. To think, though, I think that is generally outdated and should be removed from the documentation.

**Comment by facascante** [comment]
i see, but does this vagrant can simulate my test same in travis-ci, i'm having trouble debugging why my test fail in travis-ci where in it always pass in my local machine.

i tried to install this vagrant, i do vagrant up then ssh to the vm then run the bundle said in docs, but it error out with 

```
Failures:

  1) Travis::Build::Script::DirectoryCache#fetch_url Given "cache: bundler"
     Failure/Error: let(:file_name) { URI(cache.fetch_url).path.split('/').last                                                                                                                                                       }

     URI::InvalidURIError:
       the scheme https does not accept registry part: s3_bucket.s3.amazonaws.co                                                                                                                                                      m (or bad hostname?)
     # ./spec/build/script/directory_cache_spec.rb:83:in `block (4 levels) in <t                                                                                                                                                      op (required)>'
     # ./spec/build/script/directory_cache_spec.rb:85:in `block (4 levels) in <t                                                                                                                                                      op (required)>'

  2) Travis::Build::Script::DirectoryCache#fetch_url Given "cache: bundler" when                                                                                                                                                       looking for cache with extra information
     Failure/Error: let(:file_name) { URI(cache.fetch_url('', true)).path.split(                                                                                                                                                      '/').last }

     URI::InvalidURIError:
       the scheme https does not accept registry part: s3_bucket.s3.amazonaws.co                                                                                                                                                      m (or bad hostname?)
     # ./spec/build/script/directory_cache_spec.rb:88:in `block (5 levels) in <t                                                                                                                                                      op (required)>'
     # ./spec/build/script/directory_cache_spec.rb:90:in `block (5 levels) in <t                                                                                                                                                      op (required)>'

  3) Travis::Build::Script::DirectoryCache#push_url Given "cache: bundler"
     Failure/Error: let(:file_name) { URI(cache.push_url).path.split('/').last }

     URI::InvalidURIError:
       the scheme https does not accept registry part: s3_bucket.s3.amazonaws.co                                                                                                                                                      m (or bad hostname?)
     # ./spec/build/script/directory_cache_spec.rb:98:in `block (4 levels) in <t                                                                                                                                                      op (required)>'
     # ./spec/build/script/directory_cache_spec.rb:100:in `block (4 levels) in <                                                                                                                                                      top (required)>'

  4) Travis::Build::Script::DirectoryCache#push_url Given "cache: bundler" and "                                                                                                                                                      os: osx"
     Failure/Error: let(:file_name) { URI(cache.push_url).path.split('/').last }

     URI::InvalidURIError:
       the scheme https does not accept registry part: s3_bucket.s3.amazonaws.co                                                                                                                                                      m (or bad hostname?)
     # ./spec/build/script/directory_cache_spec.rb:98:in `block (4 levels) in <t                                                                                                                                                      op (required)>'
     # ./spec/build/script/directory_cache_spec.rb:105:in `block (5 levels) in <                                                                                                                                                      top (required)>'

Finished in 12.95 seconds (files took 2.65 seconds to load)
3059 examples, 4 failures, 11 pending

Failed examples:

rspec ./spec/build/script/directory_cache_spec.rb:85 # Travis::Build::Script::Di                                                                                                                                                      rectoryCache#fetch_url Given "cache: bundler"
rspec ./spec/build/script/directory_cache_spec.rb:90 # Travis::Build::Script::Di                                                                                                                                                      rectoryCache#fetch_url Given "cache: bundler" when looking for cache with extra                                                                                                                                                       information
rspec ./spec/build/script/directory_cache_spec.rb:100 # Travis::Build::Script::D                                                                                                                                                      irectoryCache#push_url Given "cache: bundler"
rspec ./spec/build/script/directory_cache_spec.rb:105 # Travis::Build::Script::D                                                                                                                                                      irectoryCache#push_url Given "cache: bundler" and "os: osx"

```


then i ignore it and try some travis command but it's not found

**Comment by ndmeiri** [comment]
@BanzaiMan Thanks for your reply. I have a couple follow-up questions.

1. So is `travis compile 10904` equivalent to `travis compile 10904.1`?
1. Thanks for clarifying how the command will fail. But can you please explain why the command succeeded when I ran `travis compile 2.99999999999`?
1. Is the Vagrant section of the README actually outdated? Was it superseded by a new way to run tests locally?

Thank you!

**Comment by BanzaiMan** [comment]
@ndmeiri 
1. Yes
2. It succeeds for you? When I try it, it fails with a `NoMethodError`.
3. `bundle exec rspec spec` runs the specs for `travis-build`.

**Comment by BanzaiMan** [comment]
@facascante Your issue seems unrelated to this one.

**Comment by facascante** [comment]
sorry.

might be a different, issue, i'm just curious with his progress re-setting up the travis-build so i ask.

**Comment by ndmeiri** [comment]
@BanzaiMan

1. So, just to make sure I have this right: `travis compile M.N` generates a script by querying Travis (via the Travis CLI client) for the relevant settings associated with the `Nth` job of the `Mth` build. Does that sound right?
1. Hm, strange. I tried it a few days ago and it succeeded, but I'll try it again soon. Thanks for trying it yourself.
1. Oh I meant to ask if using the Vagrant setup to debug failing builds for _my own repos_ is outdated.

**Comment by BanzaiMan** [comment]
@ndmeiri 
1. Yes.
2. Let me know what you find.
3. That is indeed outdated.

**Comment by ndmeiri** [comment]
@BanzaiMan 

1. So does `travis compile 10904` reset the repository back to the state it was in when build 10904 was run for the first time in order to retrieve the proper .travis.yml? Or does it use the .travis.yml file associated with build 10904 that Travis has stored on the backend?
1. I sure will.
1. What's the alternative to Vagrant?

**Comment by BanzaiMan** [comment]
@ndmeiri 
1. It just retrieves the existing configuration.
3. Vagrant was mentioned in the `travis-build` README to show how to test it locally. As I said many times here, that is an outdated way to test `travis-build`. The new way is to run `bundle exec rspec spec`.

If you are trying to debug a build, you can use Docker, if your build is running on containers: https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image Otherwise, we can set up a debug VM for you. Please email support@travis-ci.com.

**Comment by BanzaiMan** [comment]
Closing this.
