### ISSUE TITLE
Coverity add-on issues

### ISSUE THREAD

**Issue by rakhimov** [travis-ci/travis-ci#6142]
1. The scan isn't downloading with an error:

```
ERROR: The certificate of ‘scan.coverity.com’ is not trusted.
ERROR: The certificate of ‘scan.coverity.com’ hasn't got a known issuer.
```

2. Even though the download erred,
the overall build is reported as success.
https://travis-ci.org/rakhimov/scram/builds/135806838

**Comment by BanzaiMan** [comment]
1. I am guessing that the SSL certificate for https://scan.coverity.com/ is too new for `curl`. I thought `curl` on Trusty by default was good enough for recent ciphers, maybe I'm mistaken. You can try updating `curl`:

        sudo apt-get install curl

If that doesn't help, you will have to come up with another utility that can download it.

2. Your command is `curl … | bash`. When `curl` fails to fetch data, I am guessing it is writing nothing to STDOUT. `bash` takes this empty string, and executes it. Nothing happens, and it exits with status 0, which means success. What you need is `curl` to fail when it can't get the resources you want, which is achieved with `-f`. https://curl.haxx.se/docs/manpage.html#-f

**Comment by rakhimov** [comment]
Thanks @BanzaiMan.
No luck with ``curl``.
Mailed to Coverity support if they can suggest something.

**Comment by BanzaiMan** [comment]
Is this still a problem? I just tried it here: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/137557822#L172 and it successfully fetched the script in question.

**Comment by flatcap** [comment]
@BanzaiMan 
I'm not the OP, but yes it still seems to be a problem:

From [my build](https://travis-ci.org/neomutt/neomutt/builds/136953987) five minutes ago:
> Coverity Scan configured to run on branch coverity
> Coverity Scan analysis authorized per quota.
> Downloading Coverity Scan Analysis Tool...
> ERROR: The certificate of ‘scan.coverity.com’ is not trusted.
> ERROR: The certificate of ‘scan.coverity.com’ hasn't got a known issuer.

**Comment by BanzaiMan** [comment]
I see. I guess the error message is not coming from `curl`, but something in the script.

Could you try updating the `ca-certificates` package? For example:

```yaml
addons:
  apt:
    packages:
      - ca-certificates
```

**Comment by flatcap** [comment]
The same, I'm afraid:
https://travis-ci.org/neomutt/neomutt/builds/137576913

**Comment by BanzaiMan** [comment]
Thanks for testing. I guess one could try copying the script and replacing `wget` calls with `curl`. (Or ask Coverity to change the script.)

As far as I can tell, [`curl` can verify the certificate](https://travis-ci.org/BanzaiMan/travis_production_test/jobs/137557822#L189-L196), but `wget` cannot.

**Comment by flatcap** [comment]
Thanks @BanzaiMan

> try copying the script and replacing wget calls with curl

It's not _that_ urgent :-)
I'll wait for Coverity to get back to @rakhimov.

**Comment by rakhimov** [comment]
I am sorry for not posting the Coverity response promptly,
but they reiterated the issue with 'too new certificate':
```
Unfortunately, our ca is probably too new for your TravisCI instance (Entrust). Please see the following : http://stackoverflow.com/questions/27144426/error-the-certificate-of-raw-githubusercontent-com-is-not-trusted
```

**Comment by flatcap** [comment]
### Solved!

wget was failing because Entrust's certificate didn't exist in the bundle.
Therefore, we need to get the certificate.

- Open https://scan.coverity.com in your browser
- Save the certificate to disk
  - Firefox: Ctrl-i
  - Security tab
  - View certificate
  - Details
  - Export...
- Upload it somewhere public

The certificate looks something like:
```
-----BEGIN CERTIFICATE-----
MIIFNDCCBBygAwIBAgIQSqWMsU/QNioAAAAAUNgfazANBgkqhkiG9w0BAQsFADCB
ujELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUVudHJ1c3QsIEluYy4xKDAmBgNVBAsT
...
```

I added the following to my `.travis.yml`

```
before_install:
  - curl -s URL-OF-CERT | sudo tee -a /etc/ssl/certs/ca-certificates.crt
```

And my [latest build](https://travis-ci.org/neomutt/neomutt/builds/137660948) succeeded. :tada:

**Comment by nem0** [comment]
@flatcap Thanks, it works like a charm.

**Comment by rakhimov** [comment]
@flatcap ,
Is there a way to script the "Firefox" part?
http://serverfault.com/questions/139728/how-to-download-the-ssl-certificate-from-a-website

@BanzaiMan ,
can Travis automate this for us?

**Comment by flatcap** [comment]
@rakhimov Ah, nice thinking.

```
before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
```

Tested and working for me.

**Comment by BanzaiMan** [comment]
@flatcap Whoa. Nice work! Do you mind putting together a PR for https://github.com/travis-ci/docs-travis-ci-com?

**Comment by flatcap** [comment]
@BanzaiMan 
Done.

**Comment by anonimal** [comment]
Great fixes, thanks everyone! Resolves #6158.

**Comment by umlaeute** [comment]
hmm, while I appreciate the workaround, would it be possible to add the missing certificate to the travis-ci images (that is centrally, by the travis maintainers; not individually by each project?

after all, travis officially supports a `coverity_scan` plugin which currently is simply not working....

**Comment by un1versal** [comment]
I also dont think this should be added per-project, it seems OTT to have to workaround it, but a workaround is better than nothing and indeed a welcome contribution Im sure by all.

I think for a proper fix to trickle down to Travis is unlikely to go fast, from what I see that process *seems* to be as if snails and hurtles from a superglue radioactive environment, had mutant babies

**Comment by BanzaiMan** [comment]
I agree. I'll look at this next week.

**Comment by xirkus** [comment]
I've updated the TravisCI instructions on SCAN to include @rakhimov workaround so that others can benefit.

**Comment by syzzer** [comment]
I keep having these issues, see e.g. this build: https://travis-ci.org/OpenVPN/openvpn/jobs/174203295

The workarounds listed here do not seem to work for me.  Any advice?

**Comment by BanzaiMan** [comment]
@syzzer Your build is a PR build, so Coverity Scan addon is not in effect.

**Comment by syzzer** [comment]
@BanzaiMan: no, my build is not a pull request  build. It is triggered by a push to the coverity_scan branch of the main repo.

**Comment by BanzaiMan** [comment]
Oh, you're right.
