### ISSUE TITLE
Trying to do perl6 build on trusty dist; getting precise

### ISSUE THREAD

**Issue by dwarring** [travis-ci/travis-ci#6143]
I'm building a Perl 6 module that needs libgcrypt20, available under trusty. But, I'm getting precise.

For example, I tried:
```
sudo: required
dist: trusty
group: legacy
language: perl6
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgcrypt20 
perl6:
  - latest
```

Which gave  https://travis-ci.org/p6-pdf/perl6-Crypt-GCrypt/builds/136001080

![image](https://cloud.githubusercontent.com/assets/274095/15877050/6ddeca78-2d65-11e6-8890-b3306570907d.png)

The build dist is `trusty`, but the actual Ubuntu version is `precise`.

How can I get a perl6 build to run on trusty?

**Comment by dwarring** [comment]
^^ @paulcochrane @hoelzro @ugexe @tony-o

**Comment by tony-o** [comment]
can you add a `sudo apt-cache search libgcrypt` so we can see if it's even showing up for `apt`?

**Comment by dwarring** [comment]
@tony-o I've added the apt-search and kicked off build https://travis-ci.org/p6-pdf/perl6-Crypt-GCrypt/builds/136009821

I think I need trusty, which has libgcrypt20, rather than precise which only has libgcrypt11.

See http://packages.ubuntu.com/search?suite=all&searchon=names&keywords=libgcrypt20

**Comment by ugexe** [comment]
Trusty is beta and only supports a subset of Runtimes
https://docs.travis-ci.com/user/trusty-ci-environment/#Runtimes

    Other software #

    You can install other Ubuntu packages using apt-get, or add third party PPAs or custom scripts.

So you can just build it from source like this: https://github.com/ugexe/zef/blob/master/.travis.yml and add `dist: trusty; sudo: required`

**Comment by BanzaiMan** [comment]
@dwarring Your build specifies `group: legacy` (https://github.com/p6-pdf/perl6-Crypt-GCrypt/blob/b625a47363f1c18223b8ae67ce64d8fa540b6d0e/.travis.yml#L3), which routes the build to the Precise image, so the package `libgcrypt20` is not found. Try deleting that `group` line, and it should be sent to Trusty.

**Comment by dwarring** [comment]
@BanzaiMan have removed `group: legacy` build https://travis-ci.org/p6-pdf/perl6-Crypt-GCrypt/builds/136014031

![image](https://cloud.githubusercontent.com/assets/274095/15878267/9d6ae1fc-2d6d-11e6-970b-8686ae8f582b.png)

 Looks different, but still looks like it's trying to build on precise

**Comment by BanzaiMan** [comment]
@dwarring Thanks for trying. I found an issue where `perl6` was not recognized as a valid language to be sent to Trusty. I think I fixed this issue. Could you try restarting the job, or pushing a new commit?

Thanks.

**Comment by dwarring** [comment]
@BanzaiMan That fixed it thanks! Now building and passing on trusty after a bit more finessing.

For the record, here's my final .`travis.yml`
```
sudo: required
dist: trusty
language: perl6
before_install:
  - sudo apt-get -q update
  - sudo apt-get install -y libgcrypt20
perl6:
  - latest
```
