### ISSUE TITLE
R-Travis & C++11

### ISSUE THREAD

**Issue by elbamos** [travis-ci/travis-ci#6145]
I'm trying to travis-test an Rcpp package that needs C++11.  

It seems that this is non-trivial and an issue that's been coming-up.  E.g., https://github.com/wesm/feather/issues/154

I've tried using the solution at https://github.com/jimhester/rio/blob/9026180fd731aaed34f21cba3b5e207124618e5b/.travis.yml#L8-L20, but it just moves the error to a failure to find -lgfortran:  https://travis-ci.org/elbamos/largeVis/builds/136249779

Rather than comment on the `feather` issue, I thought it made better sense to open a new one here.  Can you help?

@craigcitro @hadley @jimhester

**Comment by jimhester** [comment]
You probably need gfortran-4.9 as well and probably set `FC=gfortran-4.9`

**Comment by BanzaiMan** [comment]
Looks like recent builds are passing.

**Comment by elbamos** [comment]
Yes, thanks!
