### ISSUE TITLE
not logged in, please run travis login --pro

### ISSUE THREAD

**Issue by sarbbottam** [travis-ci/travis-ci#6146]
`travis encrypt` errors out with `not logged in, please run travis login --pro`, even though I am logged in.

``` sh
$ travis login --github-token XXXXXXXXXX
Successfully logged in as sarbbottam!
$ travis encrypt GH_TOKEN=XXXXXXXXXX -r sarbbottam/empower-your-users --add
not logged in, please run travis login --pro
```

<img width="1187" alt="screen_shot_2016-06-08_at_3_35_08_pm" src="https://cloud.githubusercontent.com/assets/949380/15913458/f6839de4-2d8e-11e6-99a4-127c655b8cf1.png">

Any pointer would be helpful!

**Comment by BanzaiMan** [comment]
Did you execute the first `travis login` command with `--pro`?

**Comment by sarbbottam** [comment]
Nope, just `travis login` ...

**Comment by BanzaiMan** [comment]
Please try it.

**Comment by sarbbottam** [comment]
>>>Did you execute the first `travis login` command with `--pro`?

>>Nope, just `travis login` ...

>Please try it.

Sorry, I don't have a `pro` account

---

Ok, `travis encrypt` worked but the problem happened again ...

I don't know how to reproduce it. I guess there are some syncing issue or delay between `travis login` and `travis encrypt`.

Please feel free to close the issue, if you think there are no issues.

**Comment by BanzaiMan** [comment]
Oh, I see. Sorry. I misunderstood.

Could you try without the argument?

```
travis encrypt -r sarbbottam/empower-your-users
```

**Comment by sarbbottam** [comment]
As stated earlier, `travis encrypt` worked, w/ & w/o arguments. But I experience the original issue non-deterministically.

**Comment by SketchK** [comment]
Look at this answer @BanzaiMan 
Hope it work for you !

[http://stackoverflow.com/questions/36608870/travis-ci-encrypt-command-is-asking-for-login-pro]()

**Comment by painter1** [comment]
The same error message can arise from a typo in the -r option.

**Comment by SketchK** [comment]
@painter1 use --org instead

**Comment by painter1** [comment]
Using --org doesn't help.   Actually I had done that in the first place.  I encountered no problem with the login.  But a typo in the -r option of "travis encrypt" will cause an error message which incorrectly tells you that you had had a login problem.  I'm sure that it's not the only way to get that message, but in my case fixing the -r option eliminated the problem.

**Comment by indrabasak** [comment]
I am also running into same issues. I logged in using my GitHub credentials. Used -r option with owner/repo option. Still getting the same error message.

not logged in, please run travis login --pro

Why I type 'travis whoami', it gives my correct GitHub login information.

**Comment by kanekotic** [comment]
ok this is happening to me also. I have a theory, if the repo is marked as private, or is a private repo the command will not run if not `--pro` user.

**Comment by Cryptophobia** [comment]
Should we take this to mean that TravisCI is turning into garbage? 🗑

**Comment by PierreFritsch** [comment]
I faced this scenario in Travis CI Enterprise, and [setting the default endpoint](https://stackoverflow.com/a/49365670/4769344) solved the issue for me:

    travis endpoint --set-default --api-endpoint https://travis-ci.my-company.corp/api

**Comment by cklanac** [comment]
Travis creates a slug in the git config. If Travis can't find that repo publicly, then it assumes the repo is private and prompts for a `--pro` login.

To view the current slug: 

```sh
git config travis.slug
```

If the slug is incorrect then remove it and rerun your `travis ...` command.

```sh
git config --unset travis.slug
travis <command>
```

> Removing the slug also solves the issue where the repo name has changed. See #3264. Thanks @fabb

**Comment by jameskleeh** [comment]
This just started happening to me out of the blue. I've been calling `travis encrypt` many times in other repositories without issue. This is a public repository

```
react-webpack master $ travis logout
Successfully logged out!
react-webpack master $ travis login --github-token ...
react-webpack master $ travis encrypt BINTRAY_USER=...
not logged in, please run travis login --pro
react-webpack master $ git config travis.slug
grails-profiles/react-webpack/
react-webpack master $ 
```

**Comment by rkuzsma** [comment]
@jameskleeh From the output above, it's possible that your `travis login --github-token ...` command did not succeed.

Counterintuitively, `travis login` is silent when you specify an invalid token, and prints a success message only when you successfully login. https://github.com/travis-ci/travis-ci/issues/10313

**Comment by Cryptophobia** [comment]
> Counterintuitively, `travis login` is silent when you specify an invalid token, and prints a success message only when you successfully login. #10313

:confused: :mag: This is an anti-pattern. Thanks for pointing it out so maybe maintainers will fix it. Should we open an issue for it as well?

**Comment by shinnya** [comment]
A workaround for this issue is to pass `--org`  explicitly like `travis encrypt --org "XXXXX"`.

**Comment by lxmunro** [comment]
I am having this issue still, I can login successfully but not encrypt files. When I check, it says I am logged in and the repo is connected:

```
lxmunro$ travis report
System
Ruby:                     Ruby 2.3.7-p456
Operating System:         Mac OS X 10.14.6
RubyGems:                 RubyGems 2.5.2.3

CLI
Version:                  1.8.10
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2019-09-11 12:08:23 +1200

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "lxmunro"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

lxmunro$ travis repos
lxmunro/sfdx-travisci (active: yes, admin: yes, push: yes, pull: yes)
```

But then when I try to run the encypt I get the error:
```
lxmunro$ travis encrypt-file assets/server.key assets/server.key.enc --add
not logged in, please run travis login --pro
```

I've tried logging in again, but it says the same thing regardless.

**Comment by haeram27biz** [comment]
please try,
$ travis login --pro --github-token <your-token>
$ travis endpoint --set-default --api-endpoint https://api.travis-ci.com 

travis cli's default api-endpoint is "https://api.travis-ci.org" and top-level domain ".org" supports only for open-source project.
please use ".com" top-level domain for your private project.
