### ISSUE TITLE
Exoscale Deployment is currently disabled

### ISSUE THREAD

**Issue by gildegoma** [travis-ci/travis-ci#6147]
#### Problem

As shown in [this travis build example](https://travis-ci.org/alv-ch/job-desk/builds/135851418#L1156-L1158), the `exoscale` provider is no longer available in http://travis-ci.org.

#### Analysis

This provider was originally based on `cloudControl` provider, but in April 2016 [cloudControl joined the exoscale company](https://www.exoscale.ch/syslog/2016/04/11/cloudcontrol-joins-exoscale/).

According to Exoscale Support, the changes made by travis-ci/dpl#414 shouldn't have removed the `exoscale` support, as their PaaS offer (`exoapp`) is still available.

#### References

- travis-ci/dpl#414
- https://www.exoscale.ch/syslog/2016/04/11/cloudcontrol-joins-exoscale/
- https://docs.travis-ci.com/user/deployment/exoscale

**Comment by BanzaiMan** [comment]
@gildegoma https://github.com/travis-ci/docs-travis-ci-com/pull/1024 says that Exoscale has shut down. Is it OK to remove this provider now?

**Comment by gildegoma** [comment]
@BanzaiMan sure 👍

**Comment by BanzaiMan** [comment]
@gildegoma Thanks!

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/dpl/pull/624 for reference.
