### ISSUE TITLE
Errored builds just sit there, without finishing when log length exceeds allowable limit...

### ISSUE THREAD

**Issue by zbeekman** [travis-ci/travis-ci#6149]
See, for example: https://travis-ci.org/zbeekman/taucmdr/jobs/136535262 ... also why in the world is it erroring in the first place? The job on Precise seems to be fine... anyway that might be more of my problem than yours.

**Comment by BanzaiMan** [comment]
Sorry, what exactly is the problem? https://travis-ci.org/zbeekman/taucmdr/jobs/136535262#L566 says the command failed.

**Comment by zbeekman** [comment]
@BanzaiMan Sorry, I may have distracted you with my "also, why in the world..." question... the real question is the issue's title.

Yes the command failed. The command fails at minute ~2 ish, and by minute 6 or 7 Travis-CI prints an error message (you have to scroll to the bottom of the completed log and wait a while for it to show up) saying that the log exceeded 4MB and will be terminated. However, even after this message appears the job sits there for at least 40 minutes, still marked as running on the web interface... I usually kill them manually when I notice this because they are just hogging resources. Basically Travis-CI knows the job is dead and/or exceeded 4MB but just hangs for many, many minutes.

**Comment by BanzaiMan** [comment]
Ah, I see. When you see the message `The log length has exceeded the limit of 4 MB`, and the log stops updating, could you try reloading the page to see if the status gets updated?

**Comment by zbeekman** [comment]
Yup, tried a bunch of times to reload... The job just sits there... I don't
think it's client side, no emails get generated, etc. until I manually kill
it.

**Comment by BanzaiMan** [comment]
Hmmm. So https://travis-ci.org/zbeekman/taucmdr/jobs/136535262 was left running until the maximum timeout (50 minutes) is reached? :-/

**Comment by zbeekman** [comment]
Yes sir!

**Comment by photodude** [comment]
I'm also seeing the issue with Trusty builds, the Build continues to run after the 4 Mb Log limit has been reached. Kind of pointless to continue running a build if the log length has been exceeded. 
Does not seem to effect the php 5.6+ builds I tested, these builds all died when the log length was exceeded.
