### ISSUE TITLE
Travis build failing with error status code 126

### ISSUE THREAD

**Issue by haarabi** [travis-ci/travis-ci#6150]
Can anyone help me figure out how to get the Travis build working?

The code compiles and runs with no issues, but I have been trying to get the Travis CI working.

My github code repository is located at https://github.com/haarabi/synermed-home.git

> $ npm install 
> synermed-home@0.0.0 postinstall /home/travis/build/haarabi/synermed-home
> typings install
sh: 1: typings: Permission denied
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.2.0/bin/node" "/home/travis/.nvm/versions/node/v6.2.0/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! synermed-home@0.0.0 postinstall: `typings install`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the synermed-home@0.0.0 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the synermed-home package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs synermed-home
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls synermed-home
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/haarabi/synermed-home/npm-debug.log
The command "eval npm install " failed. Retrying, 2 of 3.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/haarabi/synermed-home#L183 says:
```
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
```

Please fix your dependencies. I don't think this is a Travis CI issue.

**Comment by BanzaiMan** [comment]
Actually, the real error is on line 180:

```
> typings install
sh: 1: typings: Permission denied
```

`typings`, wherever it is, is not executable.

**Comment by BanzaiMan** [comment]
Maybe this one: https://github.com/haarabi/synermed-home/blob/d94d0468041696749320ab1403d644e5793514ee/node_modules/.bin/typings

**Comment by dabbara-geetha** [comment]
I'm having similar permission denied issues when using npm copyfiles. 
@BanzaiMan - Please suggest if you have any info on this
Thanks
![image](https://user-images.githubusercontent.com/62707899/79352946-7190c380-7f08-11ea-932a-890ae5fda1fa.png)
