### ISSUE TITLE
Respect JSON files for configuration

### ISSUE THREAD

**Issue by leo** [travis-ci/travis-ci#6151]
In addition to `.yml` files, it would also be very happy about `.json` files getting supported when it comes to configuration of builds (this is great for JS projects).

**Comment by BanzaiMan** [comment]
As JSON is a subset of YAML, if you want to use JSON format for configuration, you can certainly do that. Do note that the file must be named `.travis.yml`; if your JavaScript tools want to refer to something else, say `travsi.json`, simply create a symbolic link.

**Comment by leo** [comment]
@BanzaiMan Thanks for the details! However, IMHO, the fact that JSON is a subset of YAML, doesn't make putting JSON into a YAML file valid. I mean, technically parsing would work fine but since the extension doesn't match the content, it's not clean at all...

I also think that creating a symbolic link isn't a clean solution either. Can't you just support the file name "travis.json", please?

**Comment by BanzaiMan** [comment]
Sorry, but we do not have plans to support that.

**Comment by leo** [comment]
😄 To me, it sounds like 10 lines of code or something. But ok! I'll have to understand that...

**Comment by Joshua-Anderson** [comment]
Github has API limits... by checking for both a `.travis.yml` and a `.travis.json

**Comment by leo** [comment]
Are you sure? Is there really a way to check if a file exists in a certain repo? Or aren't they just loading all files on the root level and then see if there's a matching file in there?

**Comment by svenfuchs** [comment]
We fetch this file from the GitHub API (long before we spin up a VM in order to clone the repo), so yes, this would double the API requests for this particular file. 

As far as I understand the [GItHub contents API](https://developer.github.com/v3/repos/contents/#get-contents) does not support fetching two specific files at once.

**Comment by leo** [comment]
Ah, okay. Then I guess you're right! Simply requesting both files at once would be stupid. But what about the following approach:

Firstly, you're trying to load `.travis.yml` as usual. If it doesn't exist, you don't simply abort the process. Instead of that, you try to load `travis.json`. And once the system knows which file is being used, the answer gets cached.

All in all, this means the API request only doubles once (and only if `.travis.yml` doesn't exist).

**Comment by jayvdb** [comment]
Then what should they do when a repo switches from one filename to another?
A symlink seems like a good free solution. Have you tested it works?

**Comment by leo** [comment]
@jayvdb If the file name that's cached returns a 404 error, the cache should be refreshed.
