### ISSUE TITLE
Build Timeout issue while setting up Travis CI for sugar activities

### ISSUE THREAD

**Issue by YashAgarwal** [travis-ci/travis-ci#6152]
Hello, 
I'm trying to set up Travis CI for a sugar activity (a native program for the sugar OS) 
here is my `.travis.yml` file

```
install: travis_wait 30 mvn install
sudo: required
language: python
branches:
  only:
    - yash-v0
python:
  - "2.7"

before_install:
  - pip install flake8
  - "git clone git://github.com/sugarlabs/sugar-build.git"
  - "cd sugar-build"
  - "./osbuild pull"
  - "./osbuild build"
  - "./osbuild shell"

install: 
  - "cd sugar-build/activities/"
  - "git clone https://github.com/YashAgarwal/testingTravis.git edit-fonts.activity"

script: 
  - "flake8 sugar-build/activities/edit-fonts.activity"

after_success:
  - "python setup.py dist_xo"
  - "cd ~; ls -alFR"

```
The build gets stuck at `./osbuild shell` because there is no output after 10m.
This command opens a new shell which is the part of the sugar environment and it doesn't take more than 10m for that. 
This is the error message I got 
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```
I tried increasing the timeout time using `install: travis_wait 30 mvn install` but there wasn't any change in the error message

**Comment by BanzaiMan** [comment]
What does `./osbuild shell` do? Is it waiting for user input? The hang in the `before_install` will not be affected by changes in `install`.

**Comment by davelab6** [comment]
yes its waiting for input

**Comment by BanzaiMan** [comment]
@davelab6 @YashAgarwal OK. Then that is expected behavior. What do you expect to happen you run `./osbuild shell` and feed no input?

**Comment by YashAgarwal** [comment]
Ok I changed it
I moved the `./osbuild shell` in __after_success:__ and this should open a shell in which rest of the commands mentioned under __after_success:__ are executed 
 
but I'm still getting the same error

**Comment by YashAgarwal** [comment]
FYI, here is the `.travis.yml` file

```
sudo: required
language: python
branches:
  only:
    - yash-v0
python:
  - "2.7"

before_install:
  - pip install flake8
  - "git clone git://github.com/sugarlabs/sugar-build.git"
  - "cd sugar-build"
  - "./osbuild pull"
  - "./osbuild build"

install: 
  - "cd activities/"
  - "git clone https://github.com/YashAgarwal/testingTravis.git edit-fonts.activity"

script: 
  - "flake8 edit-fonts.activity"

after_success:
  - "cd .."
#  - "travis_wait 30 mvn install"
  - "./osbuild shell"
  - "python setup.py dist_xo"
  - "cd ~; ls -alFR"
```

**Comment by YashAgarwal** [comment]
just to be thorough with the explanation 
![problem](https://cloud.githubusercontent.com/assets/2657578/15981703/0f74ff50-2f97-11e6-9a3d-0d0dfbb2dec0.gif)

**Comment by samdroid-apps** [comment]
You need to pipe the input in, eg:

      echo "command" | ./osbuild shell

**Comment by davelab6** [comment]
@samdroid-apps cool - where is that documented? :)

**Comment by samdroid-apps** [comment]
It's how a shell works.  If you want to make the interactive shell run with some predefined input, just pipe it.  It isn't specific to sugar build.

**Comment by BanzaiMan** [comment]
There doesn't seem to be anything for us to fix.

**Comment by davelab6** [comment]
The fact that @YashAgarwal didn't guess that is how it works shows me that this needs to be documented. 

Thanks @BanzaiMan for your help with triaging this :)
