### ISSUE TITLE
osx request Please update CocoaPods to 1.0

### ISSUE THREAD

**Issue by victor** [travis-ci/travis-ci#6153]
As the title suggests.

thanks

**Comment by solarce** [comment]
@victor which [OS X image(s)](https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions) are you currently using?

**Comment by victor** [comment]
I'm using `xcode7.3`

**Comment by Antondomashnev** [comment]
Hey @solarce, what is the status of this request?
