### ISSUE TITLE
Multiple issues with encryption

### ISSUE THREAD

**Issue by ephracis** [travis-ci/travis-ci#6154]
Trying to encrypt a file:

```
travis encrypt-file ... --add
```

**First issue:**
Does not add the environment variable to my `.travis.yml`, though it does add the command for decrypting the file. The `.travis.yml` file was created using `travis init` with Ruby set as main language.

To work around this issue I proceeded to try to encrypt the file by hand. Step 1: create encrypted environment variable:

```
travis encrypt -r simplare-cookbooks/customization my_encrypted_var=testing123 --add
```

Variable is added to `.travis.yml` as expected. I then added the following to the travis file:

```
before_install:
- echo $my_encrypted_var
```

**Second issue:**
The result is an empty line when run on Travis CI. Expected to see `testing123`.

Travis version 1.8.2 running on OS X 10.11.5.

**Comment by BanzaiMan** [comment]
Sorry to hear about the problem. Could you elaborate on what you did and what you observed in each step of the process? As documented in https://docs.travis-ci.com/user/encrypting-files, this command does not automatically alter the content of `.travis.yml`. You'd need to add `--add` if you want that behavior.

```
travis encrypt -r simplare-cookbooks/customization my_encrypted_var=testing123 --add
```
is incomplete, in that you'd need to tell CLI where to add the key to. Please review the content of `.travis.yml`. I suspect it is not setting the environment variable correctly. https://docs.travis-ci.com/user/environment-variables/#Encrypting-Variables-Using-a-Public-Key

**Comment by ephracis** [comment]
I followed the guide verbatim. Yeah, I used `--add` which successfully added the command to decrypt the file, but did not add any environment variable.

Noticed another thing: I'm also having issues with variables set on the website. If I check "Display value in build log" then it is set correctly. It appears in the output of `env` and `echo $foo` outputs the correct value. If I uncheck that setting (ie make it encrypted) then it doesn't appear.

My repo is here: https://travis-ci.org/simplare-cookbooks/customization

**Comment by BanzaiMan** [comment]
Which build shows the problem?

**Comment by ephracis** [comment]
This is the latest build on the PR which tries to use encrypted files:
https://travis-ci.org/simplare-cookbooks/simplare-base/builds/136769826

In it you can see I echo out three variables:

1. `$encrypted_a9691b63a574_key` which is added with `travis encrypt -r simplare-cookbooks/simplare-base encrypted_a9691b63a574_key=testing123 --add`. Value: testing123.
2. `$foo` which is set in web interface as plain text. Value: foo
3. `$bar` which is set in web interface as hidden (encrypted). Value: fota

As you can see, only `$foo` has a value during the build, the two encrypted variables are empty.

**Comment by BanzaiMan** [comment]
https://github.com/simplare-cookbooks/simplare-base/pull/2 is a PR coming from a fork, so encrypted variables are not decrypted. This is documented behavior. https://docs.travis-ci.com/user/environment-variables/

**Comment by ephracis** [comment]
Oh, of course. That makes total sense. 😄
