### ISSUE TITLE
install_name_tool is broken on OSX XCode 7.3 image

### ISSUE THREAD

**Issue by urschrei** [travis-ci/travis-ci#6156]
See failing build here: https://travis-ci.org/urschrei/convertbng/jobs/136751606#L597

**Comment by BanzaiMan** [comment]
Hmm. There is an incomplete error message after the command invocation, and we don't know what it is. Does the build error consistently if you restart it?

**Comment by urschrei** [comment]
It errored a few times with the same invocation on subsequent builds, yeah. Let me try to run it a few more times and see what happens. Is there anything else I can check?

**Comment by urschrei** [comment]
This was a path error on my part. Got a full error on a subsequent re-run. Sorry!
