### ISSUE TITLE
Travis-CI not triggering Coverity Scan

### ISSUE THREAD

**Issue by anonimal** [travis-ci/travis-ci#6158]
We've followed the directions given at:
- https://docs.travis-ci.com/user/coverity-scan/ (https://scan.coverity.com/travis_ci)
- https://scan.coverity.com/projects/monero-project-kovri/builds/new?tab=travis_ci

The account is properly setup, the token is correct, everything appears in order.

Here is our [.travis.yml](https://github.com/monero-project/kovri/blob/coverity_scan/.travis.yml) and [build status](https://travis-ci.org/monero-project/kovri/branches).

Despite repeated merges to ```coverity_scan```, [coverity overview](https://scan.coverity.com/projects/monero-project-kovri?tab=overview) reports:

> No builds were successfully analyzed yet.
> To submit a build for analysis please follow these instructions.

I cannot find a related open/closed issue. Is the documentation correct? Should we contact Coverity?

**Comment by KostyaSha** [comment]
coverity_scan must be under addons? Invalid travis.yml?

**Comment by anonimal** [comment]
Hi @KostyaSha. I've made the change in https://github.com/monero-project/kovri/pull/203 and [merged](https://github.com/monero-project/kovri/pull/204) into ```coverity_scan``` but nothing has changed.

I do notice in [the build report](https://travis-ci.org/monero-project/kovri/builds/138620470#L902):

> ERROR: The certificate of ‘scan.coverity.com’ is not trusted.
> ERROR: The certificate of ‘scan.coverity.com’ hasn't got a known issuer.

After seeing https://github.com/travis-ci/travis-ci/issues/6142, I will try the patch provided and report any findings.

**Comment by anonimal** [comment]
Resolved by #6142. Thanks @KostyaSha.
