### ISSUE TITLE
A problem occurred configuring project ':app'. > failed to find Build Tools revision 23.0.3

### ISSUE THREAD

**Issue by Isabellle** [travis-ci/travis-ci#6160]
Dear, 

Can you please let me know the latest version of your Build version?

Thanks a lot!

isabelle,

**Comment by Isabellle** [comment]
21.1.1 I think.

**Comment by BanzaiMan** [comment]
Did you add necessary components to your configuration? https://docs.travis-ci.com/user/languages/android#Overview

If you are still having problems, please point to a build log that shows the problem.

**Comment by Isabellle** [comment]
Thank you for your answer.
So, I added the following to the configuration file: 

`language: android
android:
  components:
    - build-tools-23.0.3
    - android-23
    - platform-tools

before_script:
    - chmod +x gradlew
`

And the error I get is the following - in the build log:

`FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> failed to find Build Tools revision 23.0.3
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 21.852 secs
The command "./gradlew build connectedCheck" exited with 1.
Done. Your build exited with 1.`

**Comment by ardock** [comment]
The order matters, try 

```
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23


before_script:
    - chmod +x gradlew
```
