### ISSUE TITLE
question: .travis.yml "on" section: "tags" and "branch" cumulative?

### ISSUE THREAD

**Issue by tony-kerz** [travis-ci/travis-ci#6161]
my `.travis.yml` `on` section looks like this:
```
  on:
    tags: true
    branch: master
```
and i pushed to a feature branch (e.g. `tk/travis`), which travis built as i expected, but i also expected that it __not__ deploy because it wasn't the `master` branch,
but travis did the deploy to npm.

i have seen that travis will not deploy if the branch is associated with a pull-request, but i will often push to a feature branch for some period of time before submitting a pull-request,
so in this case i don't want the deploy to happen until the feature branch is merged into `master`.

can someone provide guidance around appropriate configuration to achieve the desired effect?

regards,
tony.

**Comment by BanzaiMan** [comment]
Could you point us to a build log URL that shows the problem you are having?

**Comment by BanzaiMan** [comment]
As documented in https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A:

> `tags`: When set to `true`, the application is deployed when a tag is applied to the commit. This causes the branch condition to be ignored.

Consider using a custom condition instead, if you want to tag a non-`master` branch.

**Comment by tony-kerz** [comment]
thanks hiro,

a custom condition sounds good here.

is a custom-condition "cumulative", for instance, if i have something like:

```
on:
  branch: master
  condition: ! -z $TRAVIS_TAG
```

will that deploy only on `master` and with a non-empty tag?

regards,
tony.
