### ISSUE TITLE
Inconsistent API endpoint behavior for logs

### ISSUE THREAD

**Issue by bnferguson** [travis-ci/travis-ci#6162]
Working with one of our Travis Enterprise customers (who also uses .com/.org) and they brought up that when you hit the API endpoint for logging you can get different responses depending how "fresh" the logs are. If you just built, the end point will just return the log. If it's been a while, and the log has been archived to S3 you get a redirect. 

This feels like an implementation detail, and something we could make completely transparent instead of forcing the API client to deal with it, I think we should always return the log. Thus making the API end point's behavior consistent.

**Comment by jayvdb** [comment]
Note this is probably the same as #5458 , and #5459 for related documentation fixes.
