### ISSUE TITLE
npm cannot find file specified

### ISSUE THREAD

**Issue by halcwb** [travis-ci/travis-ci#6163]
I am trying to build a repository with language: csharp. The build also has a target that tries to run npm. In the machine config it is reported that node has been installed:

> Build system information
> Build language: csharp
> Build group: stable
> Build dist: precise
> Build image provisioning date and time
> Thu Feb  5 15:09:33 UTC 2015
> Operating System Details
> Distributor ID:	Ubuntu
> Description:	Ubuntu 12.04.5 LTS
> Release:	12.04
> Codename:	precise
> Linux Version
> 3.13.0-29-generic
> Cookbooks Version
> a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
> GCC version
> gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
> Copyright (C) 2011 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> LLVM version
> clang version 3.4 (tags/RELEASE_34/final)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> Pre-installed Ruby versions
> ruby-1.9.3-p551
> Pre-installed Node.js versions
> v0.10.36
> etc .....

But when trying to build using npm I get:

>  1) System.Exception: Start of process /usr/local/bin/npm failed. ApplicationName='/usr/local/bin/npm', CommandLine='install', CurrentDirectory='./client', Native error= Cannot find the specified file

Failing build: https://travis-ci.org/halcwb/GenUnitApp/builds/137218045

**Comment by BanzaiMan** [comment]
If you just invoke `npm` instead of `/usr/local/bin/npm`, it should be found (in `~/.nvm/v0.10.36/bin/npm`).

**Comment by halcwb** [comment]
Tried that, doesn't work, see: https://travis-ci.org/halcwb/GenUnitApp/builds/137280176.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/halcwb/GenUnitApp/builds/137280176#L1218 If this is what `npm` gives you, then the process is not respecting `$PATH` the way I expect. I am not familiar with C# tools, but maybe the maintainers do.

Paging @joshua-anderson @akoeplinger @nterry.

**Comment by halcwb** [comment]
I have added the npm filepath as an absolute path like `~/.nvm/v0.10.36/bin/npm`. But, obviously, that's a bit ugly.

**Comment by halcwb** [comment]
See: https://github.com/travis-ci/travis-ci/issues/6186
