### ISSUE TITLE
Add Bitbucket Support

### ISSUE THREAD

**Issue by tback** [travis-ci/travis-ci#6164]
Please consider to support bitbucket (original issue #667). 
In 2012 @michaelklishin stated `Sorry, no immediate plans to do so.`
In 2014 @BanzaiMan locked the issue.
It's 2016 now and I dare to ask again: can we have bitbucket support?

**Comment by BanzaiMan** [comment]
Thanks for taking time to open this issue. In 2016, we still do not have plans to support Bitbucket.

**Comment by wndxlori** [comment]
Big, sad sigh. 😰

Oh, and +1

**Comment by ackleymi** [comment]
-1
