### ISSUE TITLE
Launch multiple pypi deployments in the same build

### ISSUE THREAD

**Issue by aggFTW** [travis-ci/travis-ci#6166]
Hi,

We are working on Travis and PyPI integration for [sparkmagic](https://github.com/jupyter-incubator/sparkmagic/tree/travispypi)

We have three different packages in that repo, each with its own setup.py files:
1. hdijupyterutils
2. autovizwidget
3. sparkmagic

However, we are finding it very difficult to launch a PyPI deployment for each one of them.

The closest we've gotten to is by running a `before_deploy` step to `cd` into the right folder, but it seems like we cannot do this more than once. [Latest attempt.](https://github.com/jupyter-incubator/sparkmagic/blob/travispypi/.travis.yml)

Any way to do this? Or is this a feature request?

Thanks!

**Comment by aggFTW** [comment]
Relevant comment from 2013:
https://github.com/travis-ci/travis-ci/issues/1298#issuecomment-24473374

**Comment by BanzaiMan** [comment]
Why do these 3 packages share the same repository?

**Comment by aggFTW** [comment]
Is it unexpected? Is there something wrong with that?

They depend on each other, and keeping them on the same repo simplifies code changes, testing, and versioning.

**Comment by aggFTW** [comment]
ping :smile: @BanzaiMan

**Comment by BanzaiMan** [comment]
Sorry, but I can't say that our deployment provider is designed to work with this use case.

**Comment by aggFTW** [comment]
Thanks @BanzaiMan! For anyone curious, this is how we resolved it:
https://github.com/jupyter-incubator/sparkmagic/pull/270/files
