### ISSUE TITLE
Installed dependency not present during test session

### ISSUE THREAD

**Issue by mcyprian** [travis-ci/travis-ci#6168]
Some of the tests fails with traceback ImportError: No module named jinja2 (lines 449, 480...) despite the fact Jinja2 is on the list of installed dependencies (line 155).
All the tests passing on my local machine.
log: https://travis-ci.org/fedora-python/pyp2rpm/jobs/137462869

**Comment by BanzaiMan** [comment]
Recent builds are passing. Has the issue been resolved?

**Comment by mcyprian** [comment]
It haven't merged it to master yet, check [epel_template](https://github.com/fedora-python/pyp2rpm/pull/38) branch, build is still failing https://travis-ci.org/fedora-python/pyp2rpm/builds/139181226.

**Comment by BanzaiMan** [comment]
Very curious. Unfortunately, I don't have a good explanation. Send email to support@travis-ci.com, and we'll set you up with a debug VM, if you're interested.
