### ISSUE TITLE
docker.errors.APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.21, server API version: 1.20)")

### ISSUE THREAD

**Issue by ahlusar1989** [travis-ci/travis-ci#6169]
I am attempting to perform browser-based regression testing. However,` docker-compose up -d ` 
triggers the following error. Here is the log:

https://travis-ci.org/DivvyCloud/Regression-Tests/builds/137504348

**Comment by BanzaiMan** [comment]
@ahlusar1989 https://travis-ci.org/DivvyCloud/Regression-Tests/builds/137504348#L373-L374 says:

> compose.config.config.find: Using configuration files: ./docker-compose.yml
> docker.auth.auth.load_config: File doesn't exist

Indeed, `docker-compose.yml` doesn't exist on the repository: https://github.com/DivvyCloud/Regression-Tests/tree/54e04a99f2b02ad76079aa9867420ac35457e79d
