### ISSUE TITLE
Pull request updates may cause commit references to not be found (reference is not a tree: 425384000b6942ccdeee5b61e84c6e0b94b654f3)

### ISSUE THREAD

**Issue by certik** [travis-ci/travis-ci#617]
This looks like a Travis bug:

```
Using worker: ppp3.worker.travis-ci.org:travis-php-5

$ cd ~/builds
$ git clone --depth=100 --quiet git://github.com/sympy/sympy.git sympy/sympy
$ cd sympy/sympy
$ git fetch origin +refs/pull/1209/merge:
remote: Counting objects: 63, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 47 (delta 32), reused 33 (delta 19)
Unpacking objects: 100% (47/47), done.
From git://github.com/sympy/sympy
 * branch            refs/pull/1209/merge -> FETCH_HEAD
$ git checkout -qf 425384000b6942ccdeee5b61e84c6e0b94b654f3
fatal: reference is not a tree: 425384000b6942ccdeee5b61e84c6e0b94b654f3

Done. Build script exited with: 1
```

See the builds at http://travis-ci.org/#!/sympy/sympy/builds/1700321

How did Travis obtain the hash 425384000b6942ccdeee5b61e84c6e0b94b654f3? For some reason it is not in the tree.

**Comment by bucaran** [comment]
Still happening sometimes here. Maybe I should stop `push -f` irresponsibly :smiling_imp:

**Comment by henri-tremblay** [comment]
What is the solution to get the build back on its feet after a `push -f` ?

**Comment by BanzaiMan** [comment]
@henri-tremblay Is the commit unreachable after `push -f`? If so, there is no way to build it right now (#2118).

**Comment by henri-tremblay** [comment]
Not sure. It seems to have magically repaired itself though. The screen was mistakenly reporting continuous failures but in fact the build was passing.
https://travis-ci.org/easymock/objenesis

**Comment by bucaran** [comment]
It's happening again. Is there a like a directive or something I could write in the .travis.yml file that would just fix it, like --depth=100000 or anything that would just work?

**Comment by mariogintili** [comment]
Happening for me as well - we rebase branches and sometimes have to hard push.

This is something I believe **should** be supported - are there any work arounds? 

```
travis_time:end:2976b320:start=1473790513307150055,finish=1473790513808027041,duration=500876986
[0K$ cd mariogintili/sunlight
$ git checkout -qf f2bfbb4fba196afa21f934be8e19ec8f5f7d1262
fatal: reference is not a tree: f2bfbb4fba196afa21f934be8e19ec8f5f7d1262

[31;1mThe command "git checkout -qf f2bfbb4fba196afa21f934be8e19ec8f5f7d1262" failed and exited with 128 during .[0m

Your build has been stopped.
```

**Comment by BanzaiMan** [comment]
@mariogintili Did you force push to the branch before the build was run?

**Comment by mariogintili** [comment]
@BanzaiMan happened to a team member and he was unable to confirm that - I'd go for a yes.

I also opened a customer support ticket, should I follow that conversation there?
