### ISSUE TITLE
Purge stale caches

### ISSUE THREAD

**Issue by kkaefer** [travis-ci/travis-ci#6170]
The "Caches" tab currently allows deleting individual caches, or all caches. It'd be useful to add the ability to clear stale caches, for some definition of stale, e.g. created/used more than X days ago. 

E.g. at https://travis-ci.org/mapbox/mapbox-gl-native, we currently have around 19GB of caches, but we don't want to delete caches that are actively used, while some caches haven't been used in months because the corresponding branches have long been merged.

**Comment by BanzaiMan** [comment]
FYI The old caches are expunged after 45 days since their creation.

**Comment by kkaefer** [comment]
Ah, that sounds like what I'm describing; I got confused by the "2 months", which is probably just on the edge of the 45 day expiration date and gets rounded up. I don't actually see times larger than 2 months.
