### ISSUE TITLE
What is the default location of the files to deploy?

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#6172]
The documentation page about [GitHub Releases Uploading](https://docs.travis-ci.com/user/deployment/releases) isn't clear enough.

If I generate a file and I won't specify absolute path, what is the default location from where Travis uploading the files? E.g.

```
deploy:
  file: "my_file.bin"
```

Is it HOME directory, BUILD directory, or the current/last working directory?
## 

My case is that I've tried to put into [HOME dir](https://travis-ci.org/EA31337/FX-MT-VM/jobs/137608644) (being in different folder), but it didn't work and _Deploying application_ section is just empty.

**Comment by kenorb** [comment]
Update: I've added `cd ~` to `before_deploy` and it seems it worked, so I think the current folder needs to be set to `~`, before deploying the files.

**Comment by BanzaiMan** [comment]
The document should show that the deployment starts in `$TRAVIS_BUILD_DIR`.

**Comment by BanzaiMan** [comment]
@plaindocs Could you take a look?

**Comment by kenorb** [comment]
Not on the page which I've linked. From there I don't know even to which section this page belong to the left. The _Getting Started_ section is expanded, but nothing is highlighted and searching on the page for "release" doesn't give any clues. Could you send the page which says that the deployment starts in `$TRAVIS_BUILD_DIR`?

I think this could be not true, because I had to change my directory to `~` before the deployment so the files can be uploaded, but I may be wrong.

**Comment by plaindocs** [comment]
Yep, I'll fix the docs.

**Comment by plaindocs** [comment]
@kenorb Let me know if that works for you, and close the issue if it looks good.

@BanzaiMan I'll check the other deployment pages for similar info, but that is a separate issue.

**Comment by kenorb** [comment]
@plaindocs I think that's better. Does the current working dir needs to be set to `$TRAVIS_BUILD_DIR` before the deployment happens? For example I've changed the current dir to something else, do I need to make sure that my test should enter `$TRAVIS_BUILD_DIR` in `before_deploy`, or does it happens automatically?

**Comment by plaindocs** [comment]
Looks to me like you have to do that manually. In which case I *really* need to add that to the docs. @BanzaiMan is that how it should work? Or is that a bug?

**Comment by kenorb** [comment]
In that case `$TRAVIS_BUILD_DIR` is just coincidence and it's not likely to be true that the files are deployed from build dir, it's only deploying from there because the build started in that directory initially and when you change it, it really deploying the file from your current working directory.
