### ISSUE TITLE
Cron jobs detection and skipping

### ISSUE THREAD

**Issue by lookyman** [travis-ci/travis-ci#6176]
Let's say I have my build environment split to unit tests and integration tests. I want to run unit tests with every push, but skip integration tests and run those only as a cron job. Now I can detect whether the build is triggered by cron with `TRAVIS_EVENT_TYPE`, but is there a way to actually skip the build entirely, without all the possibly expensive initialization of the build environment?

**Comment by BanzaiMan** [comment]
I'm not sure if I understand the use case. You want to skip certain parts of the build if it's a cron job? Then you should check `$TRAVIS_EVENT_TYPE` before running the expensive initialization steps.

**Comment by lookyman** [comment]
There are build steps before `before_install`, like installing addons and starting services. I might be overthinking my optimizations, but these can potentially take quite some time. Ideally I would like to have entirely separate `.travis.yml` for normal builds and for cron builds. Or be able to exclude jobs in `matrix` based on the `$TRAVIS_EVENT_TYPE`. I know, overthinking..

**Comment by joepvd** [comment]
Valid point, but closing. Sub minute improvements on scheduled jobs is not having a big impact on UX or compute time.
