### ISSUE TITLE
Build fails to start

### ISSUE THREAD

**Issue by sjakobi** [travis-ci/travis-ci#6178]
https://travis-ci.org/sjakobi/path/builds/137832500

I had canceled [previous builds](https://travis-ci.org/sjakobi/path/branches) after Travis failed to start a build after I had pushed a new commit.

**Comment by sjakobi** [comment]
The build finally started after about 1h of waiting.

I'm leaving this open in case you want to investigate.

**Comment by BanzaiMan** [comment]
It appears to me that, at the time (around 2016-06-12 16:00 UTC) the build in question was waiting for its turn to run, you had a lot of jobs already in the build queue. For example:

https://travis-ci.org/sjakobi/stack/builds/137812020
https://travis-ci.org/sjakobi/stack/builds/137817035
https://travis-ci.org/sjakobi/stack/builds/137825271

When these jobs finished, https://travis-ci.org/sjakobi/path/builds/137832500 eventually got the turn and ran.

**Comment by sjakobi** [comment]
> It appears to me that, at the time (around 2016-06-12 16:00 UTC) the build in question was waiting for its turn to run, you had a lot of jobs already in the build queue

This seems plausible. I might not have been thorough enough with the cancelling.

I'm wondering if a visualisation of the build queue for the repo might have prevented my confusion. A simple counter ("5 threads in use, 6 jobs waiting") might have been enough.

**Comment by sjakobi** [comment]
> It appears to me that, at the time (around 2016-06-12 16:00 UTC) the build in question was waiting for its turn to run, you had a lot of jobs already in the build queue

This seems plausible. I might not have been thorough enough with the cancelling.

I'm wondering if a visualisation of the build queue for the repo might have prevented my confusion. A simple counter ("5 threads in use, 6 jobs waiting") might have been enough.
