### ISSUE TITLE
Cannot add i386 architecture in trusty environment

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#6181]
See https://travis-ci.org/miloyip/rapidjson/jobs/138160042#L206
This prevents cross compiling to 32bit architectures on trusty.

**Comment by BanzaiMan** [comment]
Looks like Google Chrome source does not provide the 32-bit binary files, so it should be removed before you run `sudo apt-get update`.

```yaml
before_install:
  - sudo rm /etc/apt/sources.list.d/google-chrome.list
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
```
