### ISSUE TITLE
Unable to deploy to OpenShift when using multiple branches

### ISSUE THREAD

**Issue by alejandroliu** [travis-ci/travis-ci#6184]
I have a github repo with two branches, "master" and "dev".  When I create the openshift app, I use the github repo as the initial URL. 
If I deploy from the "master" branch, then OpenShift deployment works.
If I deploy from the "dev" branch, then OpenShift deployment fails.

It looks like the "dev" branch gets merged with the openshift dev branch (since it was copied from the original URL).  I think the openshift deploy command is doing:

     git push openshift HEAD

Whereas, it should be doing:

    git push openshift HEAD:master

**Comment by BanzaiMan** [comment]
Please use the `on` option, described here: https://docs.travis-ci.com/user/deployment/openshift#Branch-to-deploy-from

In your case, you need

```yaml
deploy:
  provider: openshift
  ...
  on: dev
```
