### ISSUE TITLE
Community Csharp: Old node version

### ISSUE THREAD

**Issue by halcwb** [travis-ci/travis-ci#6186]
When I use node, I notice that the installed version is old:

> -npm WARN engine simplebuild-karma@1.0.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.36","npm":"1.4.28"})
> npm WARN engine shelljs@0.7.0: wanted: {"node":">=0.11.0","iojs":"*"} (current: {"node":"0.10.36","npm":"1.4.28"})

Is it possible to update the node version and making sure that npm can be used from bash?

**Comment by halcwb** [comment]
I have created a small update script to get the latest version of node and npm:

```
#!/usr/bin/env bash

sudo ~/.nvm/v0.10.36/bin/npm cache clean -f
sudo ~/.nvm/v0.10.36/bin/npm install -g n
sudo ~/.nvm/v0.10.36/lib/node_modules/n/bin/n 6.2.1
PATH=/usr/local/n/versions/node/6.2.1/bin:$PATH
```

Note the `PATH` doesn't work yet!

My `.yml` looks like:

```
language: csharp

sudo: required

install:
  - sudo ./install_travis.sh

env:
  - NPM_FILE_PATH=/usr/local/n/versions/node/6.2.1/bin/npm

```

**Comment by halcwb** [comment]
Forget to notify:  @joshua-anderson @akoeplinger @nterry

**Comment by halcwb** [comment]
This remains a bit of a headache issue and I would like to get some reactions.

I have tried this script:

```
#!/usr/bin/env bash

# Get the current node version
node -v
# Get the current npm versino
npm -v

# Update to the latest stable version
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

# Get the current node version
node -v
# Get the current npm versino
npm -v

```

This is what happens in the travis container:

> $ ./npm_update.sh
> v0.10.36
> 1.4.28
> sudo: npm: command not found
> sudo: npm: command not found
> sudo: npm: command not found
> sudo: n: command not found
> v0.10.36
> 1.4.28

The same script runs fine in the os x container.

How can I fix this?

**Comment by BanzaiMan** [comment]
If you want a newer version of Node.js, use [`nvm`](https://github.com/creationix/nvm) to update it. (Depending on the version of Node.js you want, you might need to update `nvm` itself.)

```yaml
before_install:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - node --version
```

**Comment by halcwb** [comment]
Thanks, but this fixes the linux build but breaks the os x build. Is there a way to differentiate?

**Comment by halcwb** [comment]
Ok, I got it working both for linux and mac:

```
#!/usr/bin/env bash

# Get the current node version
echo node version:
node -v
# Get the current npm version
echo npm version:
npm -v

if [[ "$OSTYPE" == "linux"* ]]; then
    # Linux
    echo OS: Linux

    # Update to the latest stable version
    curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
    source $HOME/.nvm/nvm.sh
    nvm install stable

elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    echo OS: Mac

    # Update to the latest stable version
    sudo npm cache clean -f
    sudo npm install -g n
    sudo n stable
fi

# Get the updated node version
echo node version:
node -v
# Get the updated npm version
echo npm version:
npm -v

```
Thanks @BanzaiMan for your support.

**Comment by netdesignr** [comment]
Thank you very much @BanzaiMan for the quick snippet! It works!
