### ISSUE TITLE
Alias PHP '7.1.0alpha1' to '7.1'

### ISSUE THREAD

**Issue by Danack** [travis-ci/travis-ci#6187]
Hi,

Thanks for setting up PHP 7.1 in issue https://github.com/travis-ci/travis-ci/issues/6148

Would it be possible to alias it to just `7.1` - where 7.1 means 'always use the most recent PHP 7.1.x version available?

That would be nicer than compared to hard-coding specific versions in the .travis file.

cheers
Dan

**Comment by PeeHaa** [comment]
Alternatively something like `nightly` would also work for me like you did for php 7.

**Comment by BanzaiMan** [comment]
With 7.1.0alpha3, we now alias this to 7.1. https://travis-ci.org/BanzaiMan/travis_production_test/builds/144064771#L134
