### ISSUE TITLE
Crystal build fails

### ISSUE THREAD

**Issue by stefanwille** [travis-ci/travis-ci#6196]
Hi!

@asterite @jhass @waj @will

My build of crystal-redis fails with
```
/home/travis/build.sh: line 45: crystal: command not found
```

Please can you help me fix this?

I have attached the full Travis log file.

Thanks!
Stefan

[log.txt](https://github.com/travis-ci/travis-ci/files/321926/log.txt)

**Comment by stefanwille** [comment]
The build URL is https://travis-ci.org/stefanwille/crystal-redis/builds/138615443

**Comment by jhass** [comment]
Duplicate of #5461

**Comment by BanzaiMan** [comment]
Closing as a duplicate.
