### ISSUE TITLE
Support "macos" value for "os" key

### ISSUE THREAD

**Issue by leo** [travis-ci/travis-ci#6200]
OS X has been renamed to "macOS". So [this](https://docs.travis-ci.com/user/multi-os/) needs to be adjusted.

**Comment by leo** [comment]
Ok. But don't you simply leave the issue open then?

**Comment by JustinJiaDev** [comment]
@solarce any plan to support `macos`? Sierra will be release soon.

`macos_image` as `osx_image` alias.

**Comment by leo** [comment]
@solarce Please reopen this!

**Comment by JustinJiaDev** [comment]
I tried to open another issue (https://github.com/travis-ci/travis-ci/issues/6634) and got closed because of duplication. Maybe we should re-open this one?

**Comment by leo** [comment]
DEFINITELY!

**Comment by leo** [comment]
Closing this now, as ZEIT has moved to Circle CI.
