### ISSUE TITLE
[QUESTION] Is it possible to only integrate with a fork

### ISSUE THREAD

**Issue by valendesigns** [travis-ci/travis-ci#6204]
Currently we have a client that doesn't want to use Travis, but we do in our fork to run tests and sniffs. Is it possible to only integrate Travis with the fork and not make a connection or approve the integration upstream?

**Comment by BanzaiMan** [comment]
You can set up Travis CI with your account/organization, and you can run builds on your forks.

**Comment by valendesigns** [comment]
Thank you fr the quick response. However, I have admin rights to the repo, the issue is that it's not showing up in the organization account or in my personal account to activate Travis. We have a paid account so it's a bit confusing as to what the cause is.

**Comment by BanzaiMan** [comment]
@valendesigns OK. This is probably better suited for support tickets. Please email support@travis-ci.com with further details (which account/organization you are using, and so on).

I'm closing this now.

**Comment by tir38** [comment]
Care to share how you fixed this. We're seeing the same problem.

**Comment by BanzaiMan** [comment]
@tir38 There is no fix to share, I'm afraid. If you need support, please email us at support@travis-ci.com.

**Comment by valendesigns** [comment]
I contacted support, but never got a response back. 😕

**Comment by BanzaiMan** [comment]
@valendesigns @drogus responded to your email on June 22. Did you not get it? It was sent to the email address on record for you.

**Comment by BanzaiMan** [comment]
@valendesigns I sent another email to that thread. Let us know if you get that.
