### ISSUE TITLE
Xcode 8/iphonesimulator10.0 cannot find scheme

### ISSUE THREAD

**Issue by kwonye** [travis-ci/travis-ci#6205]
I am trying to build my project with Xcode 8 and iphonesimulator10.0, but it is getting stuck in the `[Info] Loading settings for scheme 'CalcPad' ...` stage.

Here is the build url: https://travis-ci.org/kwonye/calcpad/builds/138660855

Log: https://gist.github.com/kwonye/7960f29c7308bfba3f6645cf925e3d67

**Comment by solarce** [comment]
We just updated to Xcode8b2, https://twitter.com/travisci/status/752704816116293632, could you please try running a new build and seeing if things work any better?

**Comment by nasli** [comment]
Hi @kwonye, still has the issue?
I have similar issue and resolved using xcpretty:
```
 - xcodebuild -project 'project.xcodeproj' -scheme 'project' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6' build test | xcpretty -c --test --color
```

**Comment by kwonye** [comment]
Thanks for following up, @solarce and @nasli. I was trying to use xctool, but it looks like FB has effectively deprecated it. Using xcodebuild works fine so I'm closing this. 👍

**Comment by nasli** [comment]
@kwonye At the end they plan to support but.. still in progress https://github.com/facebook/xctool/issues/704 :(
