### ISSUE TITLE
`No gulpfile found` error in all test task that involves Gulp

### ISSUE THREAD

**Issue by inikulin** [travis-ci/travis-ci#6209]
Accidentally today all our tasks that uses Gulp started to fail with `No gulpfile found` error. Meanwhile, everything works just fine locally, so it's unlikely an issue with Gulp itself. I've created a simple reproduction repo: https://github.com/inikulin/travis-gulp-issue-repro
Running `npm test` locally works, but on Travis we have an error: https://travis-ci.org/inikulin/travis-gulp-issue-repro/jobs/139290227

**Comment by BanzaiMan** [comment]
Do you have an older build that passed?

**Comment by inikulin** [comment]
For this particular repo - no, because I've created it to illustrate the issue. But here is the repo for which tests previously sucessfully passed: https://travis-ci.org/DevExpress/generator-testcafe-reporter/builds/136715007, but when I've created test PR which contains just modified README they failed with same error:  https://travis-ci.org/DevExpress/generator-testcafe-reporter/jobs/139285362

**Comment by BanzaiMan** [comment]
This failure https://travis-ci.org/DevExpress/generator-testcafe-reporter/jobs/139285362 off a build that passed 10 days ago, probably means that the underlying dependencies changed and your build no longer works in a fresh machine.

I can reproduce this on my machine.

**Comment by BanzaiMan** [comment]
You do not see the issue because you have the dependencies that makes it go locally (probably in `node_modules`). If you remove it (or move it to somewhere Node can't find), I bet your build will fail locally, too.

**Comment by inikulin** [comment]
I don't get it, how it works locally with freshly created repo: https://github.com/inikulin/travis-gulp-issue-repro  (just created it a couple of hours ago from the scratch)

**Comment by inikulin** [comment]
> This failure https://travis-ci.org/DevExpress/generator-testcafe-reporter/jobs/139285362 off a build that passed 10 days ago, probably means that the underlying dependencies changed and your build no longer works in a fresh machine.

It's not failure with this particular repo, I've tried almost 10 repos and they all fail with the same error now. Also, if you take a look at https://github.com/inikulin/travis-gulp-issue-repro  reproduction repo I've created a couple of hours ago you will see that it contains extremely trivial code and don't have any dependencies except latest gulp (which BTW was [last updated 4 months ago](https://www.npmjs.com/package/gulp)). Such code works perfectly and worked on Travis before today.

**Comment by inikulin** [comment]
Oh, seems like I got your point. Some `gulp` dependency changed, so it now searches for gulpfile in case sensitive manner. That's why I was not able to reproduce this issue on MacOS and Windows. Seems like it should be reported to gulp repo.
Thank you!

**Comment by inikulin** [comment]
Related issue: https://github.com/gulpjs/gulp/issues/1697
