### ISSUE TITLE
Long wait times on Linux Container infrastructure

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6211]
We have some builds that seem to have been waiting (or waited) for hours on Linux Container infrastructure of late. Is there some reason this is going incredibly slowly? Are there other users affected by this?

**Comment by BanzaiMan** [comment]
@jakirkham Do you have other OS X builds ahead of your Linux builds? They share the same queue, and we are having a sizable back log on OS X.

**Comment by jakirkham** [comment]
Yes, ok, that would indeed explain it. I was wondering if they were correlated. Thanks for the pointer. Will close as this is already being dealt with then.

**Comment by jakirkham** [comment]
Would be great to confirm whether Linux and macOS builds still share the same queue or not.

xref: https://github.com/travis-ci/travis-ci/issues/6234
