### ISSUE TITLE
LLVM APT Repositories are back again

### ISSUE THREAD

**Issue by offa** [travis-ci/travis-ci#6217]
LLVM APT Repositories are back again: `http://apt.llvm.org/`

At the moment clang builds are disabled at Travis due the downtime:

> The LLVM APT rpository is currently available. Your builds may fail if your build updates LLVM/clang to a newer version with 'apt'. Please see https://github.com/travis-ci/travis-ci/issues/6120#issuecomment-224072540 for a workaround.

(Issue #6120) 

------------------------------------
Announcement at the [(Mailinglist)](http://lists.llvm.org/pipermail/llvm-dev/2016-June/101500.html):

> Hello,
> 
> Thanks to the LLVM Foundation and Tanya, the apt repository is now back:
> 
> http://apt.llvm.org/
> 
> It will take a few days before all the builds go green [1].
> 
> Please update your configurations.
> 
> Sylvestre
> 
> [1] The same build infra is still used but the builds were failing
> because using llvm.org/apt too.

**Comment by BanzaiMan** [comment]
Could you show a build that disables the build on LLVM? It should be just a warning. The build should continue.

**Comment by BanzaiMan** [comment]
I have removed the warning.

**Comment by offa** [comment]
@BanzaiMan I had failing builds (like [this](https://travis-ci.org/offa/cpp-guards/jobs/140105259)). But if it was just a warning – maybe it was an APT issue.

However, I have re-run the other failed build and it works now, thanks!

**Comment by ldemailly** [comment]
I'm still getting failures:
https://travis-ci.org/facebook/wdt/jobs/139642779

The LLVM APT rpository is currently available. Your builds may fail if your build updates LLVM/clang to a newer version with 'apt'. Please see https://github.com/travis-ci/travis-ci/issues/6120#issuecomment-224072540 for a workaround.
0.18s$ curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -
gpg: no valid OpenPGP data found.
The command "curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -" failed and exited with 2 during .
Your build has been stopped.
