### ISSUE TITLE
build fail for R 3.1

### ISSUE THREAD

**Issue by schloerke** [travis-ci/travis-ci#6218]
Hello,

I'm trying to build my package on R 3.1.  
- It worked fine in https://travis-ci.org/ggobi/ggally/jobs/139940143
- It failed in https://travis-ci.org/ggobi/ggally/jobs/140114477
  Both of these were submitted today.  

There is no difference in code: https://github.com/ggobi/ggally/compare/e7514a8...c641322 beside a branch name change.

Any ideas?

Failure output:

```
$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = TRUE);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
Error in if (capabilities("libcurl")) { : argument is of length zero
Calls: <Anonymous> ... download_method_secure -> download_method -> auto_download_method
Execution halted
```

I can verify on my machine if the capability being checked doesn't exist, it returns a logical(0).

``` r
capabilities("libcurl")
# libcurl 
#    TRUE 
capabilities("asdf")
# named logical(0)
```

Thank you for your help!
- Barret

@craigcitro, @hadley, @jimhester

**Comment by kiwiroy** [comment]
Also reported hadley/devtools#1244
