### ISSUE TITLE
Trusty workers should skip calling update-initramfs

### ISSUE THREAD

**Issue by NaterGator** [travis-ci/travis-ci#6219]
On travis builders using apt addons, some dependencies trigger the update-initramfs hook.

It we just set [update_initramfs=no](http://manpages.ubuntu.com/manpages/trusty/man5/update-initramfs.conf.5.html) in /etc/initramfs-tools/update-initramfs.conf we can skip this fairly slow operation. 

Example build log [here](https://travis-ci.org/mavlink/qgroundcontrol/jobs/140164066#L841)

**Comment by BanzaiMan** [comment]
Thanks for raising the issue. This is now deployed.
