### ISSUE TITLE
Laraval 5.2 build failed

### ISSUE THREAD

**Issue by PSNAppz** [travis-ci/travis-ci#6220]
I'm getting an error like this in my project which uses Laravel 5.2.

`PHP Warning:  require(/home/travis/build/TheOpenBlog/TheOpenBlog/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/travis/build/TheOpenBlog/TheOpenBlog/bootstrap/autoload.php on line 17`

Travis-CI : https://travis-ci.org/TheOpenBlog/TheOpenBlog

Github : https://github.com/theopenblog/theopenblog

StackOverflow(Question) : http://stackoverflow.com/questions/38018283/how-to-test-larval-5-2-projects-with-travis-ci

**Comment by BanzaiMan** [comment]
Looks like it's been answered.

**Comment by PSNAppz** [comment]
Yea
