### ISSUE TITLE
Build on OS X stucked after opening doc (.md/.html) file

### ISSUE THREAD

**Issue by robooo** [travis-ci/travis-ci#6221]
I have test suite with few tests that opens some documentation/README files. On linux build it works good (it opens file and continue to another test, take just second) but on OS X it get stucked (for example 'Opening /Users/travis/build/robooo/path/to/dir/README.md ...'), like in terminal you need Ctrl+C or close file manually.

Is there some solution for this?

**Comment by BanzaiMan** [comment]
How are you opening this file?

**Comment by robooo** [comment]
concretely command `luarocks doc luarepl` (it's blackbox test), which on my personal osx opens README.md in my editor

**Comment by BanzaiMan** [comment]
Is it waiting for user input? Or is it waiting for the process to end?

**Comment by robooo** [comment]
it should just open it and continue, with unix `open` command so I don't know what happend on travis

**Comment by BanzaiMan** [comment]
The default configuration on OS X doesn't have `*.md` files mapped to any app, so I think the command fails.

Compare https://travis-ci.org/BanzaiMan/travis_production_test/builds/140295757#L147 and https://travis-ci.org/BanzaiMan/travis_production_test/builds/140296317#L151.

**Comment by robooo** [comment]
is there some solution or workaround for this?

**Comment by BanzaiMan** [comment]
I suppose you could use tips shown in http://superuser.com/questions/273756/how-to-change-default-app-for-all-files-of-particular-file-type-through-terminal, or http://duti.org/documentation.html.

**Comment by robooo** [comment]
I found workaround for LuaRocks (add `web_browser = "true"` to config) I tried duti like `duti -s /Applications/TextEdit.app .md all` but it won't start build
