### ISSUE TITLE
Repository removed from Github but still shows in Travis

### ISSUE THREAD

**Issue by gauravojha** [travis-ci/travis-ci#6223]
I had a repository on Github which I used to build with Travis. But I removed that repository from github. Coming back to my Travis org account, I synced my Github account. Still I see the removed repository in my Travis repositories.

**Comment by BanzaiMan** [comment]
Which repository is showing up for which account?

**Comment by gauravojha** [comment]
@BanzaiMan 
For my own github account, if you see, I only have one repository "shoppingcart-eloquent". Earlier I had a different repository "shoppingcart" which I have since removed.

Still I can see "shoppingcart" on my profile. Moreoever, the count of repositories is shown as "2"

![image](https://cloud.githubusercontent.com/assets/10114860/16410815/dc5dc12a-3d41-11e6-87aa-4241643197bb.png)

![image](https://cloud.githubusercontent.com/assets/10114860/16410842/f79ffe3a-3d41-11e6-894c-b2e2c3a119b6.png)

Am I missing something, or is there no way to modify this listing on my profile page?

**Comment by BanzaiMan** [comment]
Is this still the case now? The data have been sync'd, according to our data, and it shouldn't be showing up now.

**Comment by gauravojha** [comment]
@BanzaiMan 
Yes. Still the same. 

**Travis view**
![image](https://cloud.githubusercontent.com/assets/10114860/16415878/17694b5c-3d5d-11e6-8d21-441a79e31d83.png)

![image](https://cloud.githubusercontent.com/assets/10114860/16415881/2171188c-3d5d-11e6-8ba9-41f722391fc0.png)

**Github view**
![image](https://cloud.githubusercontent.com/assets/10114860/16415899/3f888080-3d5d-11e6-837a-9497d7a477e8.png)

**Comment by BanzaiMan** [comment]
Thanks for checking. Could you send email to support@travis-ci.com?
