### ISSUE TITLE
Travis encrypt command generates invalid auth token after switching Github repo to private

### ISSUE THREAD

**Issue by baspeti** [travis-ci/travis-ci#6226]
By invalid auth token I don't mean that there is an error message on issuing `travis encrypt` command in the terminal. Everything looks to be OK, but deploy keeps failing with a message:
`invalid option "--api_key="`

Unfortunately this error message does not tell you much, it took me almost 2 days to figure out that the problem is caused by turning a public Github repo into a private one.

Here is a list of steps to reproduce the issue:
1. Create a public repo on Github, and set up Travis CI to [deploy to Github releases](https://docs.travis-ci.com/user/deployment/releases).
2. Use the command line `travis encrypt` command to generate either encrypted GITHUB_TOKEN environment variable, or just simply issue the `travis encrypt "GITHUB TOKEN" --add deploy.api_key` command.
3. Create a tag and you will see that the deployment was successful, everything is just fine.
4. Now make your Github repo private.
5. Make sure that your Github token has the `repo` scope, not only the `public_repo` scope.
   ![image](https://cloud.githubusercontent.com/assets/5700926/16409973/7ef1f3e2-3d20-11e6-82af-2a5f80ce2a34.png)
6. From this point on `travis encrypt` will generate such encrypted texts, which will result failed deploys when you use them.
7. If you use the unencrypted Github token, everything is OK (except the fact that you made your Github token visible...)

Funny thing is that I experienced the same thing when I used Github username and password encrypted by `travis encrypt` command. In that case the deploy attempts failed with `Bad Credentials` error.

Although the things above are clearly a problem, but you can work around this issue, by deleting the Github repo and then create it again with the same name, but this time as a private repo from the beginning. (Or it is safer to create a new private repo, push your things there, delete the old repo, and then rename the new repo to have the name of the old repo.)

**Comment by BanzaiMan** [comment]
At the moment, .org and .com databases are completely separate. Moving a repository from .org to .com (or vice versa) will switch the private key with which to encrypt sensitive data.

We can document this better.

**Comment by baspeti** [comment]
No, that is not the issue. We realized that our project has been moved to .com, but it has nothing to do with the issue I've described above.

**Comment by baspeti** [comment]
Please read the issue more carefully! It is not something that is not documented well enough.

**Comment by BanzaiMan** [comment]
Could you try encrypting your secret again with `travis encrypt --pro`? (Optionally, add `-r OWNER/REPO`)

Thanks.

**Comment by Shalzz** [comment]
Hi! 
I was having the same issue but using the `--pro` flag fixed it.
Thanks!

**Comment by baspeti** [comment]
Thanks!
It worked for me too!

**Comment by ryantmer** [comment]
Came across a similar issue when moving a private repo to public - the solution for me was doing the opposite - `travis encrypt --org SOME_VAR=foo`.

This was despite having re-cloned the repo after it was made public, and having explicitly done `travis login --org`.

**Comment by BanzaiMan** [comment]
We have a reference now. https://docs.travis-ci.com/user/travis-pro/#How-can-I-make-a-private-repository-public%3F

**Comment by robertmain** [comment]
I'm having this problem, but I'm a `.org` user, so I can't try it with the `--pro` flag.
