### ISSUE TITLE
Upgrade request: Haskell - GHC Version 8.0.1

### ISSUE THREAD

**Issue by siddharthist** [travis-ci/travis-ci#6227]
There is a new version of GHC that Travis CI doesn't support yet!

https://www.haskell.org/ghc/download_ghc_8_0_1

Thank you for your awesome service :rocket:

**Comment by frozencemetery** [comment]
As a very slow workaround, one can use `services: docker` to get a VM with a newer version of GHC, but it's rather messy.  A newer version of GHC would be appreciated.

**Comment by BanzaiMan** [comment]
8.0.2 is available on Trusty.
