### ISSUE TITLE
`before_script` fails to run in PR

### ISSUE THREAD

**Issue by rhys-vdw** [travis-ci/travis-ci#6228]
Hi there, I'm experiencing inconsistent behaviour with regard to before scripts.

```yaml
before_script:
  - psql -c 'create database bookshelf_test;' -U postgres
  - mysql -e 'create database bookshelf_test;'
```

The three commits [here](https://github.com/tgriesser/bookshelf/pull/1305) fail to run the `before_script` entries.

However, these work perfectly fine on our [current master branch](https://travis-ci.org/tgriesser/bookshelf/builds/140778358) (from which the above PR is branched).

There is no code or configuration change in the failing PR, which leads me to suspect that this is a Travis issue. (I did modify `.travis.yml` on the third commit in an attempt to fix the issue by adding `services`, but the same problem exists before and after this change.)

**Comment by BanzaiMan** [comment]
Your builds are failing during the `install` phase (e.g., https://travis-ci.org/tgriesser/bookshelf/jobs/140789879#L568), so they never get to `before_script`. (We simply abort the jobs.)

If you fix that, the build should get to `before_script`.

**Comment by rhys-vdw** [comment]
@BanzaiMan thank you!

For anybody else hitting this problem, for me it was due to a [less obvious behaviour of `prepublish`](https://docs.npmjs.com/misc/scripts). `prepublish` is run on `npm install`. I had added a call to `npm test` in `prepublish`; this had the unwanted side effect of causing tests to run prematurely on Travis.
