### ISSUE TITLE
Commit status is not updating

### ISSUE THREAD

**Issue by tianshuo** [travis-ci/travis-ci#6230]
On project http://github.com/tsinghuahigh/become-a-maker, although there are build status icons, the status for commits are not showing. I don't know why this is the case because its showing in other projects. I've tried googling and looking up SO, and found [this article](http://stackoverflow.com/questions/19810386/showing-travis-build-status-in-github-repo) mentioning the same problem, that doesn't help at all.

**Comment by BanzaiMan** [comment]
Where are you expecting the build status to show on https://github.com/tsinghuahigh/become-a-maker? Or do you mean something like https://github.com/TsinghuaHigh/become-a-maker/commits/master? GitHub does not show commit status on the list of commits.

Can you point to an example where "its [sic] showing in other projects"?

**Comment by tianshuo** [comment]
It is mentioned in the SO article here: https://github.com/sebastianbergmann/phpunit/pull/1051/commits

**Comment by BanzaiMan** [comment]
That status is for commits in PRs. Commits page, such as https://github.com/TsinghuaHigh/become-a-maker/commits/master does not have them.

**Comment by tianshuo** [comment]
Strange behavior. So the problem is with github, not with travis. I'm closing this issue.
