### ISSUE TITLE
Follow log breaks scroll bar

### ISSUE THREAD

**Issue by OJFord** [travis-ci/travis-ci#6233]
When following the log during a build via the top-right button, or after the build has finished and 'follow' is still enabled, it is not possible to scroll back up via the scroll bar.

A somewhat forceful turn of the scroll _wheel_ or flick of a trackpad will successfully disable 'follow'.

When using the scroll bar however, it reverts to the bottom and resumes following. At least, that is, in Chrome on Linux, and on macOS.

The expected behaviour would be the same as when using the mouse scroll wheel - to disable follow automatically.

**Comment by BanzaiMan** [comment]
Do you mean the scroll bar on the window? I don't see this on Chrome on OS X.

![untitled_2](https://cloud.githubusercontent.com/assets/25666/16471341/0e7e54f6-3e2a-11e6-937b-a0c26e6ecac6.gif)

**Comment by OJFord** [comment]
Whoops, you're right - I don't see it either - but I definitely do in Chromium on Linux.

**Comment by BanzaiMan** [comment]
Chromium is a pre-release Chrome, right? Do you see this in a release version of any browser?

**Comment by OJFord** [comment]
It's OSS Chrome; on Linux that's all you get.

```sh
$ chromium --version
Chromium 51.0.2704.103
```
