### ISSUE TITLE
Separate queues between Linux and OSX

### ISSUE THREAD

**Issue by tkelman** [travis-ci/travis-ci#6234]
When we get major OSX infrastructure outages like today (edit: or just capacity sitting at its limit all day like on July 11th) and more than 5 builds queue up without being able to start, we end up building up hours of Linux queue too even though those jobs should be able to process fine. If the queue limits were tracked separately by OS this would be much less of an issue. Queued jobs that aren't able to start shouldn't block queued jobs that are able to start from doing so.

**Comment by jakirkham** [comment]
Has this actually already happened? It appears these are now separate in our org, but it would be nice to know if this has actually been completed by Travis CI or if my eyes are playing tricks on me. 😄

**Comment by tkelman** [comment]
Seems separate to me now?
