### ISSUE TITLE
what causes Potential Abuse Detected errors?

### ISSUE THREAD

**Issue by jobevers** [travis-ci/travis-ci#6235]
I recently added a repo https://travis-ci.org/lbryio/lbrycrd/requests to travis.  I've pushed some test commits and all of them result in "Potential Abuse Detected" errors.  The `.travis.yml` for my last commit was simply:
```
install: true
script: true
```
which seems like it shouldn't trigger any abuse flags.

What can I do to get builds working for this repo?

Thanks!

**Comment by BanzaiMan** [comment]
@jobevers We have revoked the abuse detection for your builds.

However, at this time, we do not disclose abuse detection criteria.

Thanks for your understanding.

**Comment by jobevers** [comment]
Thanks for the fix.
