### ISSUE TITLE
potential abuse detected

### ISSUE THREAD

**Issue by olegabr** [travis-ci/travis-ci#6236]
Hello! Can't trigger a build here: https://travis-ci.org/olegabr/docker-bitcoind/requests

The `.travis.yml` file is adopted from another repository and should be ok: https://github.com/docker-library/memcached/blob/3f5295b2be7ad0dd396c75e7b4b0f5aad2215cbd/.travis.yml

I'm doing a pool request against the same repository between different branches. Can it be the cause?
I need it to test travis-ci build before do pool request to the original repo I've forked from - it does not support travis-ci yet.

Thank you.

**Comment by BanzaiMan** [comment]
Please email support@travis-ci.com with this information. Thanks.
