### ISSUE TITLE
Mono fails to install on OSX environment

### ISSUE THREAD

**Issue by devlead** [travis-ci/travis-ci#6238]
Several projects fail to install mono on OSX 
Extract from [WCOMAB/Cake_Git/jobs/141111185](https://travis-ci.org/WCOMAB/Cake_Git/jobs/141111185#L16)
```
C# support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry
Installing Mono
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  302M  100  302M    0     0  1799k      0  0:02:52  0:02:52 --:--:-- 3814k

installer: Package name is Mono Framework
installer: Installing at base path /
installer: The install was successful.

/Users/travis/build.sh: line 45: mozroots: command not found

...
==> sh bootstrap.sh
==> ./configure --prefix=/usr/local/Cellar/md5deep/4.4
==> make install
🍺  /usr/local/Cellar/md5deep/4.4: 20 files, 1.7M, built in 42 seconds

$ mono --version
/Users/travis/build.sh: line 45: mono: command not found

$ xbuild /version
/Users/travis/build.sh: line 45: xbuild: command not found


```

Linux builds still work well
![image](https://cloud.githubusercontent.com/assets/1647294/16482633/ecebcab2-3eb0-11e6-9b06-3c359bd48a37.png)

Example of another project that fails with same error:
[cake-build/cake/jobs/141039074](https://travis-ci.org/cake-build/cake/jobs/141039074)

 cc @joshua-anderson @akoeplinger @nterry

**Comment by BanzaiMan** [comment]
Probably a duplicate of #6239.

**Comment by akoeplinger** [comment]
Yes, this is a duplicate of #6239.

**Comment by devlead** [comment]
Then I'm closing this in favor of the newer issue #6239 which this one was a prequel too :wink:
