### ISSUE TITLE
What version of mono is supported on osx

### ISSUE THREAD

**Issue by maxild** [travis-ci/travis-ci#6239]
/cc @joshua-anderson @akoeplinger @nterry

I am seeing this build [error](https://travis-ci.org/maxild/Prelude/jobs/141203407) on osx when installing mono 4.4.1. Same installation builds on ubuntu 14.04. Is it because I use not supported mono version? I am very new to mono, so please bare with me.

This is my [.travis.yml](https://github.com/maxild/Prelude/blob/3cf4a9d8380e59c8173fd5c1221f645ef8b3f273/.travis.yml) at that commit.

**Comment by akoeplinger** [comment]
This is a side-effect of the Mono OSX package switching from x86 to being universal (x86+x64), so the URL we use doesn't work anymore. I'm working on a fix, but in the meantime just use `mono: latest` as that is 4.4.1 right now anyway.

**Comment by maxild** [comment]
So even after changing to mono latest it is expected that both mono and xbuild is not to found by the build as seen [here](https://travis-ci.org/maxild/Prelude/jobs/141322801)?

And after your fix it will work as expected?

**Comment by akoeplinger** [comment]
@maxild hmm, that's something different but likely related. I'm looking at it.

**Comment by akoeplinger** [comment]
So the `mono: command not found` are actually a regression in the Mono 4.4.1 OSX packages. We switched to using a different way of making `mono` available in the PATH, but it seems this somehow doesn't work in Travis' OSX environment.

We'll be pinning the `mono: latest` version to Mono 4.4.0 for now so the builds don't fail for everyone until we have a fix.

**Comment by leezer3** [comment]
Should this now be working for restarted builds?
This build was originally triggered during the outage, and I've tried a couple of restarts when the service came back again, last of this was ~1 hour ago.

https://travis-ci.org/leezer3/OpenBVE/jobs/141068110

The YML file is nothing too special, only ever been testing against the latest version of Mono:
https://github.com/leezer3/OpenBVE/blob/master/.travis.yml

**Comment by ChrisMaddock** [comment]
@leezer3 - Mine has started passing again probably within the last hour - maybe worth rerunning? Thanks @akoeplinger!

**Comment by leezer3** [comment]
Yeah, now seems to be going.

**Comment by maxild** [comment]
👍

**Comment by tzachshabtay** [comment]
Hi, I'm getting the same error (line 45: mono: command not found), [in this job](https://travis-ci.org/tzachshabtay/MonoAGS/jobs/165212377). This is with Mono 3.12 on Mac. Mono latest on Mac works and Mono 3.12 on Linux works. 

/cc @joshua-anderson @akoeplinger @nterry

Is this the same issue or a new one?

**Comment by Joshua-Anderson** [comment]
This is interesting. The mono package is installed, but the binaries aren't on the path. Maybe something to do with the OSX image rollout today https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/ Could you please try using the `xcode6.4` build image to see if it still fails? Also, please open a new issue because this seems unrelated to this issue.
