### ISSUE TITLE
default ruby should be >=2.2.2

### ISSUE THREAD

**Issue by michaelkirk** [travis-ci/travis-ci#6243]
Rails and the widely used ActiveSupport library version 5 were released today. They require ruby >= 2.2.2. The default travis-ci ruby configuration uses ruby 2.0.

It's possible to specify a per project ruby version by putting (e.g.) "2.2.2" in a .ruby-version file in the root of your repository. But you might just consider bumping your default as more people are going to be affected by this as time goes on.

http://weblog.rubyonrails.org/releases/

**Comment by gerrywastaken** [comment]
Ahhh... yup just started getting these errors:

```
Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
Installing codeclimate-test-reporter 0.6.0
Installing rspec 3.4.0
An error occurred while installing activesupport (5.0.0), and Bundler cannot
continue.
Make sure that `gem install activesupport -v '5.0.0'` succeeds before bundling.
```

On builds that are testing for compatibility against Ruby 1.9.3 😞 

https://travis-ci.org/awesome-print/awesome_print/jobs/141509229

**Comment by BanzaiMan** [comment]
@gerrywastaken If you are testing for 1.9.3 compatibility, you should expect these to fail. This is expected behavior, right?

**Comment by gerrywastaken** [comment]
@BanzaiMan This break only just happened, before the ActiveSupport 5.0 release, these tests were passing. Is there any way for me to check the lock files that Travis is using so that I can see what is creating the dependency on ActiveSupport 5.0 as the tests still pass if I run them on my dev box.

**Comment by michaelkirk** [comment]
@gerrywastaken - you could check in your local Gemfile.lock to ensure that your local dependency resolutions are being used on ci.

Or if you just want to see what they are likely resolving to on ci, try blowing away your Gemfile.lock and doing a fresh bundle install with ruby <2.2.2. My guess is it will fail at that point.

**Comment by BanzaiMan** [comment]
@gerrywastaken There is no `Gemfile.lock` when dependency cannot be resolved.

Whatever your issue is, it is unrelated to having a recent Ruby as a default on Travis CI.

**Comment by gerrywastaken** [comment]
@michaelkirk and @BanzaiMan Good ideas and points. My editor was hiding my lock files from me as it was in my .gitignore. I was able to lock it down to a known working version and that fixed things: https://github.com/awesome-print/awesome_print/pull/252 Thanks to both of you. If you would like me to delete my off topic comments here, just say the word.

**Comment by meatballhat** [comment]
For those following along, the default ruby version will continue to be ~1.9.3 for the default images used in job execution.  The images that include a default of 2.2+ will be going through extended testing before being promoted to the default.  In the meantime, setting this in one's `.travis.yml` *should* allow for verification beginning sometime later today:

``` yaml
# ... other stuff
dist: trusty
group: edge
```

**Comment by apepper** [comment]
> The images that include a default of 2.2+ will be going through extended testing before being promoted to the default.

When will this happen? It's now December and ruby `2.2.5` is still not preinstalled (at least not in https://travis-ci.com/infopark/rails_connector/builds/37102676#L246-L265 ).

**Comment by wopian** [comment]
It's been well over a year since all support for 1.9.3 was dropped too. 

Many gems now require >2.0.0 and you're unable to specify a Ruby version on NodeJS projects.

https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

**Comment by BanzaiMan** [comment]
@apepper @wopian Hello. We don't have a concrete timeline, but it is definitely on our road map.

Just FYI: quite a bit (~16%) of the Ruby builds are currently relying on the default Ruby. I expect that a portion of those may break if the default switches to 2.2.x.
