### ISSUE TITLE
GitHub Releases Uploading is ignored on The OS X Build Environment

### ISSUE THREAD

**Issue by kozo2** [travis-ci/travis-ci#6245]
see

https://travis-ci.org/ecell/ecell4-wheels/jobs/141498106
and
https://github.com/ecell/ecell4-wheels/blob/test1/.travis.yml

**Comment by BanzaiMan** [comment]
That job doesn't have all the log parts, but the job is marked a failure. I have to think that something else is marking this job a failure with a nonzero exit status, but I am not surdeple what that might be.

For the record, https://travis-ci.org/BanzaiMan/travis_production_test/builds/141516274 shows that you can deploy with GitHub Releases on OS X.

**Comment by kozo2** [comment]
@BanzaiMan Thanks for your comment.
I extremely simplified .travis.yml https://github.com/ecell/ecell4-wheels/blob/test2/.travis.yml
But Travis still does NOT proceed to _deploy_ block
https://travis-ci.org/ecell/ecell4-wheels/jobs/141691622

**Comment by BanzaiMan** [comment]
Since `script` commands are exiting with status 0, I must think that deployment *is* getting triggered, and it is failing (and marking the build a failure). If you drop the `deploy` section altogether, does the build finish (and presumably pass)?

**Comment by kozo2** [comment]
I dropped `deploy` section https://github.com/ecell/ecell4-wheels/tree/test3
It finished successfully https://travis-ci.org/ecell/ecell4-wheels/jobs/141811569

**Comment by BanzaiMan** [comment]
Great. Now try adding pieces of the `deploy` one at a time and see when it starts to fail.

**Comment by kozo2** [comment]
I enabled the minimum piece of the `deploy` section https://github.com/ecell/ecell4-wheels/blob/test5/.travis.yml
But Travis did NOT show the `deploy` section info https://travis-ci.org/ecell/ecell4-wheels/jobs/141853667

**Comment by BanzaiMan** [comment]
We need to figure out how deployment is failing. VM might be getting terminated before the logs can be written, which is reported in https://github.com/travis-ci/travis-ci/issues/6018.

Could you add some amount of sleep in either `after_deploy` or `after_script`?

**Comment by kozo2** [comment]
I added sleep commands to `after_deploy` and `after_script`
https://github.com/ecell/ecell4-wheels/blob/test8/.travis.yml

But Travis did NOT show this
https://travis-ci.org/ecell/ecell4-wheels/jobs/142045350

**Comment by kozo2** [comment]
This issue is resolved now.
https://travis-ci.org/ecell/ecell4-wheels/builds/150496714
I have not changed my .traivs.yml.

Thanks.

**Comment by BanzaiMan** [comment]
@kozo2 Probably due to the change in the way we handle caching and deployment. https://github.com/travis-ci/travis-build/pull/812

You were sourcing a problematic bash source terryfy/travis_tools.sh.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/813, rather.
