### ISSUE TITLE
Xcode8: preinstalled Ruby 2.2.5 built without shared libraries

### ISSUE THREAD

**Issue by malept** [travis-ci/travis-ci#6246]
The preinstalled Ruby 2.2.5 on the Xcode8 image was built without shared libraries enabled. I have verified this by inspecting `RbConfig::CONFIG`: https://travis-ci.org/malept/rusty_blank/jobs/141525252#L126

This is different from Ruby 2.3.1 (also preinstalled on that image), which was built with shared libraries: https://travis-ci.org/malept/rusty_blank/jobs/141525253#L127

I'm currently working around it by rebuilding Ruby 2.2.5 from source before using it, but that causes the build to be 7+ minutes longer.

**Comment by solarce** [comment]
We just updated to Xcode8b2, https://twitter.com/travisci/status/752704816116293632, could you please try running a new build and seeing if things work any better?

**Comment by malept** [comment]
The `configure_args` [here](https://travis-ci.org/malept/rusty_blank/jobs/144070549#L120) indicate that it's still built with `--disable-shared`. All I had to do was make sure that `osx_image` was set to `xcode8` and not `xcode8b2` right?
