### ISSUE TITLE
osx support for pip --user

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#6247]
When using the pre-installed pip to `pip install --user x` on osx , pip places scripts into `~/Library/Python/2.7/bin/` (contrary to [PEP 370]( https://www.python.org/dev/peps/pep-0370/ ) . however this isnt in the PATH.

It would be useful to include the following to workaround that:

```bash
export PATH=$PATH:~/Library/Python/2.7/bin/
```

**Comment by BanzaiMan** [comment]
This is a problem with Apple's configuration, right? We don't quite support Python on OS X yet. See https://github.com/travis-ci/travis-ci/issues/2312.

This is good to note, though. It should be a part of the configuration when we support Python on OS X.

I'll make a note of this in the other ticket, and close this one.
