### ISSUE TITLE
Request for post successful tests life cycle event (`after_build`) that still fails on error

### ISSUE THREAD

**Issue by KeithPepin-MW** [travis-ci/travis-ci#6249]
According to the travis docs:

> The `after_success`, `after_failure`, `after_script` and subsequent stages do not affect the the build result.

But there are processes that we need to run after tests are complete that can and should fail the build on error.  In our use case, we want to build RPM packages after testing is completed (and only after tests finish successfully).  We currently run these post test build steps in the `after_success`, but as stated in the docs, if there is an error in the constructing of the RPM, the build will still pass, and no one is the wiser.  Unfortunately there is no better alternative currently, except to hi-jack the `scripts` event, but this feels wrong since the purpose of the scripts event is to run tests.

I'd like to request a new life cycle event, that would still fail the build, but that can be run after tests are completed and have passed.  I realize you probably can't change the existing after_success event since so many people probably rely on its current behavior, but could another option be created?

**Comment by BanzaiMan** [comment]
It is crude, but you can use the function `travis_terminate 1` in `after_*` to halt the build **immediately** in the mean time.

**Comment by KeithPepin-MW** [comment]
@BanzaiMan - What will that do exactly?  You mention "halting" the build.  Is that the same as failing it / exiting with a proper error code?  Can't seem to find documentation to explain this command, and I'm new to Travis, so any additional information would be greatly appreciated.

**Comment by BanzaiMan** [comment]
It is an undocumented bash function in the build. (I don't see us changing it, but it remains undocumented nonetheless.) It is basically a wrapper for the `exit` call. After that, there is no cleanup, there is not output that says `Done. Your build exited with N.`.
