### ISSUE TITLE
Add CPython 3.5.2

### ISSUE THREAD

**Issue by dstufft** [travis-ci/travis-ci#6250]
CPython 3.5.2 has been released and it'd be great if it could be added to the list of versions that can be tested against using the on-demand infrastructure. Currently attempting to use 3.5.2 gives an error like:

```
3.5.2 is not installed; attempting download
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command "sudo tar xjf python-3.5.2.tar.bz2 --directory /" failed and exited with 2 during .
```

**Comment by solarce** [comment]
@BanzaiMan how would we add this?

**Comment by BanzaiMan** [comment]
Python 3.5.2 has been built. See https://travis-ci.org/travis-ci/cpython-builder/builds/141764374

https://travis-ci.org/BanzaiMan/travis_production_test/builds/141765880
