### ISSUE TITLE
Xcode 8 builds almost immediately failing

### ISSUE THREAD

**Issue by austinzheng** [travis-ci/travis-ci#6251]
Hello,

All my Xcode 8 builds for my OS X Swift project have been failing since I upgraded. They all fail in the same way (https://travis-ci.org/austinzheng/Cormorant):

```
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed while trying to gather build settings for your scheme; tried with actions: build, test, analyze. Errors above occured while running xcodebuild -showBuildSettings:
```

My .travis.yml file looks like this:

```
language: objective-c
os: osx
osx_image: xcode8
xcode_project: Cormorant.xcodeproj
xcode_scheme: Cormorant
```

I double-checked: the project name and scheme are both correct, as far as I can tell.

I suspect that this may be an issue with `xctool`, but I just wanted to ask for help/advice in case I'm doing something obviously wrong. Thanks for your time, and have a wonderful day!

**Comment by solarce** [comment]
We just updated to Xcode8b2, https://twitter.com/travisci/status/752704816116293632, could you please try running a new build and seeing if things work any better?

**Comment by sgoodwin** [comment]
I was able to fix this for my builds by telling it not to use xctool at all. Xctool appears to not work with Xcode 8 and they don't seem to plan to do this ever. I used this in my travis config instead:

xcodebuild test -scheme Schipohl -sdk iphonesimulator -destination "name=iPhone SE"

**Comment by solarce** [comment]
@sgoodwin thanks for the feedback, is https://github.com/facebook/xctool/issues/704 what you're referring to?

**Comment by austinzheng** [comment]
Sorry for not posting earlier! Thanks for the update; I'll try using the non-xctool config.
