### ISSUE TITLE
support for .NET core

### ISSUE THREAD

**Issue by liushuping** [travis-ci/travis-ci#6256]
Please add support for .NET core platform with commands
```
dotnet restore
dotnet build
dotnet run
dotnet test
```

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by BanzaiMan** [comment]
Looks like a duplicate of #5692, which, in turn, is a duplicate of #5189.
