### ISSUE TITLE
Travis CI API rate limit

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6257]
Is there a rate limit? If so, what is the rate limit? Related SO [question]( http://stackoverflow.com/questions/32608501/what-are-travis-ci-api-rate-limits ).

**Comment by BanzaiMan** [comment]
Currently, it is set to 10/hour for .org, and 50/hour for .com.

**Comment by jakirkham** [comment]
Thanks for the info. This is probably worth adding to the docs somewhere.

Could you please clarify what those are applying to? For instance, if I have a GitHub token and use it to get a Travis CI access token, I am allowed 10 operations of any kind for an hour with that Travis CI access token on the org side.

Not to seem whiny, but that is pretty low. This (10/hour in particular) is getting close to me just doing things manually. Is there any chance of having these constraints revisited? For instance, GitHub will give you a higher rate limit if you use a token. Could something similar be explored for Travis CI?

**Comment by jakirkham** [comment]
Also, is there any way for one to query this info from the API (ideally with no penalty)?

**Comment by BanzaiMan** [comment]
The limit applies to API builds. You get the number of remaining builds (plus 1, since the one you are making has not been counted yet) in the return value.

```json
{
  "@type": "pending",
  "remaining_requests": 10,
  "repository": {
    "@type": "repository",
  }
}
```

**Comment by BanzaiMan** [comment]
We might review these values in the future.

**Comment by jakirkham** [comment]
> The limit applies to API builds.

So, wait, let me see if I am understanding this correctly. This applies to the number of builds we trigger via API. Is that correct? Or am I misunderstanding the meaning of this term.

What about other things like settings? For instance, I'm trying to enable the "Build only if .travis.yml is present" setting on a large number of repos (should be a one time thing). This is being done to easily skip builds on Travis CI when it is not needed. Is there some limit on the number of changes to the settings that I can make at one time?

**Comment by BanzaiMan** [comment]
Changing settings does not trigger a build.

**Comment by jakirkham** [comment]
Does that mean setting changes are not limited then?

**Comment by BanzaiMan** [comment]
Setting changes does not affect API build rate limit.
