### ISSUE TITLE
[osx request] CMake for xcode8

### ISSUE THREAD

**Issue by eikel** [travis-ci/travis-ci#6258]
In contrast to older xcode images, xcode8 does not contain CMake. I would like to have it in the image so that it does not have to be installed during C/C++ builds that require CMake.

**Comment by solarce** [comment]
@eikel with the Xcode8b2 update, https://twitter.com/travisci/status/752704816116293632, I included the latest Cmake version from homebrew. 

Please let me know if it's what you're looking for, thanks

**Comment by eikel** [comment]
CMake works on xcode8 now, thanks!
https://travis-ci.org/eikel/Geometry/jobs/142029971

**Comment by tusharpm** [comment]
This may be digressing from the original title, but [https://travis-ci.org/tusharpm/iod/jobs/177621733](https://travis-ci.org/tusharpm/iod/jobs/177621733) had CMake missing on xcode8.1.
Please let me know if this needs to be reported as a new issue.

**Comment by thomasvl** [comment]
@tusharpm - fyi I opened #6996 for the xcode8.1 image

**Comment by tusharpm** [comment]
Thanks.
-T
