### ISSUE TITLE
Deploying to PyPI: ImportError: No module named 'clint'

### ISSUE THREAD

**Issue by tlocke** [travis-ci/travis-ci#6264]
Hi, when deploying to PyPI I get the following error:

```
changing mode of build/bdist.linux-x86_64/wheel/chellow-1502.data/scripts/chellow_start.sh to 775
creating build/bdist.linux-x86_64/wheel/chellow-1502.dist-info/WHEEL
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.0/bin/twine", line 7, in <module>
    from twine.__main__ import main
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/twine/__main__.py", line 20, in <module>
    from twine.cli import dispatch
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/twine/cli.py", line 21, in <module>
    import clint
ImportError: No module named 'clint'

```
See https://travis-ci.org/WessexWater/chellow/builds/142388831#L3678 for the context.

Thanks for your help!

**Comment by BanzaiMan** [comment]
https://pypi.python.org/pypi/twine/1.7.0 (which your build used; see https://travis-ci.org/WessexWater/chellow/builds/142388831#L3678) appears to be missing `clint` as an install requirement. https://pypi.python.org/pypi/twine/1.7.1 correctly list it, so I think the deployment will succeed if you rerun it.

**Comment by tlocke** [comment]
Thanks for the quick response. Did a re-run and everything is working perfectly. Also I really appreciated the UI working flawlessly on my mobile browser.
