### ISSUE TITLE
Failed with AccountManagement and PrincipalContext

### ISSUE THREAD

**Issue by Darkitty** [travis-ci/travis-ci#6271]
Hi,

In my soft, I use this two assemblies. But, the compilation failed with Travis because don't exist with the Travis mono version. I tried with windows installer and the compilation run with success Anyone have a alternative to build with success with this wonderful tool ?

Thank you in advance

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by Darkitty** [comment]
OK. I send the issue to fast.
@joshua-anderson @akoeplinger @nterry thanks :)

**Comment by trossner** [comment]
@Darkitty What was the solution? You get it work on Travis ?

**Comment by Darkitty** [comment]
@trossner Sorry, I don't retry since the last time. I will retry when I have time to make a rebuild and tell you I the errors are still here.

**Comment by trossner** [comment]
@Darkitty 
I have now a solution, put the dll as file in the project a referenced this file and it works !!

**Comment by Darkitty** [comment]
@trossner Great! Thank you 👍
