### ISSUE TITLE
compiler options beyond gcc and clang

### ISSUE THREAD

**Issue by jeffhammond** [travis-ci/travis-ci#6273]
I'd like to test compilers other than gcc and clang, which I intend to install myself.  (If it matters, I want to test Intel compilers, which are discussed in https://github.com/travis-ci/travis-ci/issues/4604).

Unfortunately, when I set

```
compilers:
  - gcc
  - clang
  - icc
```

Travis defines `CC=gcc` and `CXX=g++` first thing and then attempts to run `icc --version` (https://travis-ci.org/jeffhammond/PRK/jobs/142852013), both of which are wrong because the whole point is that I want `CC=icc` (and `CXX=icpc`).  Also, since obviously Travis can't install `icc` for me, running `icc --version` will fail before I have installed it.

Thus, I would like the following:

```
language: c
compilers:
  - anything
```

should `export CC=anything` and never attempt to invoke `anything` directly.  The only time a compiler should be invoked is via `$CC` and I do not see any reason to redefine it from the value in `compiler:`.

Furthermore, the statement ["For C projects, env and compiler can be given as arrays to construct a build matrix."](https://docs.travis-ci.com/user/languages/c#Build-Matrix) is confusing (perhaps because I am an idiot).  I could not find any example where `compiler:` was a matrix, but I tried

```
compiler:
  - gcc
    TRAVIS_CC=icc
    TRAVIS_CXX=icpc
    TRAVIS_FC=ifort
```

in https://travis-ci.org/jeffhammond/PRK/jobs/142901692 and it obviously didn't work.  It did the following:

```
$ export CXX=g++
$ export CC=gcc
$ gcc TRAVIS_CC=icc TRAVIS_CXX=icpc TRAVIS_FC=ifort --version
gcc: error: TRAVIS_CC=icc: No such file or directory
gcc: error: TRAVIS_CXX=icpc: No such file or directory
gcc: error: TRAVIS_FC=ifort: No such file or directory
```

which again is exactly the opposite of what I want, because it is both redefining `CC` from the value in `compiler:` _and_ attempting to use the value set in `compiler:` literally.

Thanks.

**Comment by jeffhammond** [comment]
And I'll add that trying to support this as an environment variable hanging off of compiler=gcc is a huge pain.  My build matrix already has 59 entries, with 19-24 cases for 2 os and 2 compilers with 18 exclusions and 8 allow_failures.  I would need to duplicate essentially all of my exclusions and allow_failure, plus modify all explicit and implicit references to CC and CXX throughout my project (https://github.com/ParRes/Kernels), which currently has 1987 lines of code devoted to Travis alone.

**Comment by jeffhammond** [comment]
For what it's worth to those that find this issue in the future before it is fixed, the following disgusting hack works:
```
compiler:
  - clang
  - gcc
  - touch ~/icc ; gcc
```
This succeeds because `touch ~/icc ; gcc --version` does, and one can subsequently query for the existence of `~/icc` to know to override `CC` and `CXX`, e.g.
```
if [ -f ~/icc ] ; then
  export CC=icc
  export CXX=icpc
fi
```

**Comment by cbeck88** [comment]
What I usually do is ignore the whatever CXX travis sets, and use `export CXX=` whatever I want it to be. Since you will almost never use the compiler that travis actually installs. If you want to see an extremely well-developed custom compilers & new versions of C++ standard libraries travis.yml script, checkout this one: https://github.com/boostorg/hana/blob/master/.travis.yml This link has been circulated on /reddit/r/cpp a few times, this travis script is very well maintained.

**Comment by cbeck88** [comment]
A trick he is using there for when using `boost-build` (variously, also called `b2` / `bjam`): Every compiler entry is defined to be "clang", but he makes an environment variable COMPILER which is actually the compiler that he will use. He later writes `export CXX = $COMPILER`. But, he invokes `b2 toolset=clang`. And he writes this line to his project-config.jam, which maps the `clang` toolset to whatever compiler he wants: https://github.com/boostorg/hana/blob/master/.travis.yml#L402 So $COMPILER ends up being used. If use CMAKE then that will respect $CXX anyways. So there's not that much point in messing around with the stuff at the top of the `.travis.yml`.

**Comment by jeffhammond** [comment]
Ok, it sounds like I should just stop bothering with compiler altogether and choose compilers with generic environment variables.  It seems rather lame that the compiler feature is somewhat useless, but since I end up having some many compiler exclusions already, it will probably simplify my Travis scripts to do it without using compiler as its own dimension of the test matrix.
