### ISSUE TITLE
builds are stuck

### ISSUE THREAD

**Issue by oshai** [travis-ci/travis-ci#6275]
I have created a new project, but the builds are not starting for more than 12 hours, for example:
https://travis-ci.org/MicroUtils/kotlin.logging/builds/142861759

**Comment by BanzaiMan** [comment]
Hello. Sorry about the issue. I've manually cancelled this build. Could you try restarting it?

Thanks.

**Comment by oshai** [comment]
it was solved after I removed the repo and add it back.
