### ISSUE TITLE
Make a clear statement about the possibility for running builds locally

### ISSUE THREAD

**Issue by brechtm** [travis-ci/travis-ci#6278]
I've been trying to get the Travis CI builds for my open source project running locally in a Docker image. Having the [Travis Docker images ](https://quay.io/organization/travisci) freely available is already a tremendous help. Thanks for that!

However, I was hoping it would be possible to also automatically run all the builds from a `.travis.yml` configuration. The `travis compile` command (travis-build) seemed like the solution, but this was a disappointment. If multiple Python versions are specified in my `.travis.yml`, the generated build script is not a valid bash script. There are also some [other problems](https://github.com/travis-ci/travis.rb/issues/414) with the generated script.

Next up, [travis-worker](https://github.com/travis-ci/worker). Because of the fact that its sources are available on GitHub and that it has a nice README with installation instructions, it seemed like I would be able to achieve what I se out to do. But besides installation instructions, there is no documentation whatsoever on how to use travis-worker. I can start it, and then it seems to wait for jobs to be queued. There is no information anywhere to be found on how to send jobs to travis-worker. I'm assuming these jobs are queued by another travis-ci component? Contrary to what the README for travis-worker suggests, I don't think it is realistic to run it on my local machine for debugging purposes.

If this is indeed correct, could this simply be stated clearly in your documentation and in the README of travis-worker. Judging from a bunch of StackOverflow posts and travis-ci issues here on GitHub, I believe this might save a lot of people some time.

**Comment by ostera** [comment]
@brechtm, I managed to replicate an issue from this [.travis.yml](https://github.com/ostera/tldr.jsx/blob/ci-release/.travis.yml) with this script:

```bash
#!/bin/bash -xe

readonly BUILD_DIR=$(pwd)/.travis_build
readonly IMAGE=quay.io/travisci/travis-node-js

readonly BRANCH=$(git rev-parse --abbrev-ref HEAD)
readonly REF=$(git rev-parse HEAD)
readonly TIME=$(date +%s)
readonly STAMP=${BRANCH}@${REF}.${TIME}

travis compile $(travis show | tail -n 1 | awk '{ print $1 }' | sed 's/#//') > ${BUILD_DIR}/ci.sh
sed -i "/branch/s#\\\'\\\'#\\\'${BRANCH}\\\'#" ${BUILD_DIR}/ci.sh
chmod +x ${BUILD_DIR}/ci.sh

docker run \
  -ti \
  --entrypoint=/opt/build.sh \
  -v ${BUILD_DIR}/${STAMP}:/root/build \
  -v ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa \
  -v ${BUILD_DIR}/ci.sh:/opt/build.sh \
  ${IMAGE}
```

And I run it from the repo I'm trying to debug. The output after a few runs looks like this:

```
repos/tldr.jsx λ ttt .travis_build
.travis_build
|-- ci-release@080574cefd325e1a99dd5eb52d469ce9fbe3060a.1468580430
|   `-- ostera
|-- ci-release@080574cefd325e1a99dd5eb52d469ce9fbe3060a.1468580570
|   `-- ostera
|-- ci-release@080574cefd325e1a99dd5eb52d469ce9fbe3060a.1468580600
|   `-- ostera
|-- ci-release@080574cefd325e1a99dd5eb52d469ce9fbe3060a.1468580625
|   `-- ostera
|-- ci-release@080574cefd325e1a99dd5eb52d469ce9fbe3060a.1468580874
|   `-- ostera
|       `-- tldr.jsx
|-- ci-release@60e59fc35bd346635b9f0bc59e4a72038fff1efc.1468579034
|-- ci-release@60e59fc35bd346635b9f0bc59e4a72038fff1efc.1468579119
|   `-- ostera
|       `-- tldr.jsx
|-- ci-release@60e59fc35bd346635b9f0bc59e4a72038fff1efc.1468579575
|   `-- ostera
|       `-- tldr.jsx
`-- ci.sh
```

Where  `ostera/tldr.jsx` is the path to the repo I'm building as cloned by Travis. In each of those folders there's the fully built source that can be remounted into the container for further debugging if needed.

It'd be nice if `travis` provided a `local-build` command to try to replicate an issue that behaved somewhat like this.
