### ISSUE TITLE
Unexpected JVM exit

### ISSUE THREAD

**Issue by Capoot** [travis-ci/travis-ci#6282]
The following build broke due to an unexpected exit of the JVM:
https://travis-ci.org/zalando/build-status-traffic-light/builds/143324766

Executing a the build to re-run manually then succeeded:
https://travis-ci.org/zalando/build-status-traffic-light/builds/143324815

I was unable to reproduce the situation, it seems to be utterly randomly. If you need more infos, please feel free to ask.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/zalando/build-status-traffic-light/builds/143324766 shows the message `Killed`, which is often an indication that your process is consuming too much resource and getting killed by the Docker host which is running your job. If this is a frequent occurrence, we suggest using the standard infrastructure to get more resources. https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

I'm going to close this, but if you continue to see the problem with GCE (a.k.a., the standard infrastructure), let us know.
