### ISSUE TITLE
Re-running failed build does not post correct GitHub status

### ISSUE THREAD

**Issue by Capoot** [travis-ci/travis-ci#6283]
I had a build failing randomly and it posted to GitHub the build failed status for the push. After I manually re-run the build it went green again, but the status on GitHub remained failed, so I couldn't merge the pull request. I had to make a new commit to resolve the situation.

I think when re-running the build manually, the GitHub status should also get updated.

**Comment by BanzaiMan** [comment]
Do you have the URL to the PR build you are referring to?

**Comment by Capoot** [comment]
This is the one: https://travis-ci.org/zalando/build-status-traffic-light/builds/143324766

**Comment by BanzaiMan** [comment]
That push build failed, which is correctly reflected in https://github.com/zalando/build-status-traffic-light/pull/7.

![reformatted_hyper_refs_in_readme_by_capoot_ _pull_request__7_ _zalando_build-status-traffic-light](https://cloud.githubusercontent.com/assets/25666/16708221/c5a8f7e0-45b8-11e6-9ffd-e829050592f3.png)

> After I manually re-run the build it went green again, but the status on GitHub remained failed

Where is the a green build that didn't update the PR status?

**Comment by Capoot** [comment]
This is the subsequent build which I started manually by clicking the "restart build" button: https://travis-ci.org/zalando/build-status-traffic-light/builds/143324815

**Comment by BanzaiMan** [comment]
https://travis-ci.org/zalando/build-status-traffic-light/builds/143324815 is a build for a different PR.

**Comment by BanzaiMan** [comment]
By that, I mean, https://travis-ci.org/zalando/build-status-traffic-light/builds/143324766 is a PR build, and the result is correctly reflected in https://github.com/zalando/build-status-traffic-light/pull/6.

**Comment by Capoot** [comment]
Yes, this was what led to the issue: the PR's build status was updated, but not the status of the push (there are 2 statuses). I would have expected, after rerunning the build without pushing a new change, that all statuses in context of the corresponding commit would be updated, but only the PR's status was updated. Thus it was impossible to update the push status without making a change to the source.

**Comment by BanzaiMan** [comment]
The push build *_is_* a failure, and the PR status correctly reflects it for both https://github.com/zalando/build-status-traffic-light/pull/6 and https://github.com/zalando/build-status-traffic-light/pull/7.

**Comment by Capoot** [comment]
Yes, this is correct. But what was irritating me was, that when I restarted the push build, the resulting build was not a push build, but a PR build. This way, GitHub still thought the push build failed and this never got updated.

**Comment by BanzaiMan** [comment]
I am confused by
> when I restarted the push build, the resulting build was not a push build, but a PR build

What build did you restart?
