### ISSUE TITLE
Xcode8 Provisioning profile "filename" doesn't include the currently selected device "Travis’s Mac (217)

### ISSUE THREAD

**Issue by jakjothi** [travis-ci/travis-ci#6285]
I am facing issue with provisioning profile doesn't include the currently selected device "Travis’s Mac (217)
Note: provision profile and certificates imported successfully
My travis build command 

xcodebuild -scheme myapp PROVISIONING_PROFILE="$PROFILE_UUID" CODE_SIGN_IDENTITY="$DEVELOPER_NAME"

**Comment by solarce** [comment]
We just updated to Xcode8b2, https://twitter.com/travisci/status/752704816116293632, could you please try running a new build and seeing if things work any better?
