### ISSUE TITLE
Edited file not going into docker build

### ISSUE THREAD

**Issue by ovidiub13** [travis-ci/travis-ci#6287]
I have [this pull request](https://github.com/ovidiub13/reviewboard-docker/pull/2), in which I change a file that is copied in the Docker image that travis builds. I've printed the file outside of the docker image, but however, when it gets copied in the Docker image, the file is without changes.

Either something is broken in travis, or I misunderstand something.

**Comment by BanzaiMan** [comment]
https://github.com/ovidiub13/reviewboard-docker/pull/2/files#diff-3254677a7917c6c01f55212f86c57fbfR54 

`cat /entrypoint.sh` refers to a file in the root of the file system of your Docker image, right? Does that file exist?

**Comment by ovidiub13** [comment]
Please ignore this. I didn't realize that Travis already has a checkout of the source, and I git cloned it again, and modified a different file.

I'm sorry for the trouble.
