### ISSUE TITLE
website: build log does not load

### ISSUE THREAD

**Issue by kortschak** [travis-ci/travis-ci#6289]
If I navigate to a build page, e.g. https://travis-ci.org/gonum/plot/jobs/143507769, I never get the build log, just the three dot animation. In the past I could get around this by clicking on the raw button - that is now gone.

Every other button on the page works.

This is with FF46.0.1 on ubuntu 14.04.

**Comment by jayvdb** [comment]
I see the log immediately on that link, with FF 47.0 on Ubuntu 16.04

Maybe try using Chrome on your Ubuntu 14.04, or another browser?

**Comment by kortschak** [comment]
Sorted it out. I had forgotten aws was on a block list for NoScript. Thanks.
