### ISSUE TITLE
R: Travis can't install feather package dependency

### ISSUE THREAD

**Issue by Stan125** [travis-ci/travis-ci#6291]
Hi guys,

Thanks for all the work on R Travis! 
I can't seem to be able to get my R package through Travis checks. For some reason I can't install `rio` because of it's `feather` dependency. I always get the following errors in the Travis logs:

`
ERROR: compilation failed for package ‘feather’
`

I have been researching this for a while now but haven't found a solution. All checks run fine locally. My .travis.yml is located [here](https://github.com/Stan125/GREA/blob/master/.travis.yml). The log is found [here](https://travis-ci.org/Stan125/GREA/builds/143383410).

Thanks for your help,
Stani

@craigcitro @hadley @jimhester

**Comment by jimhester** [comment]
The default compilers on travis do not support C++11, so you need to install them yourself. You need to do something like what is done in rio itself to build feather

https://github.com/leeper/rio/blob/master/.travis.yml#L8-L21

**Comment by Stan125** [comment]
I tried this out, it worked! Yay!
