### ISSUE TITLE
Long wait for rebuild

### ISSUE THREAD

**Issue by bakwc** [travis-ci/travis-ci#6292]
Waiting for build for already an hour, https://travis-ci.org/bakwc/PySyncObj/builds/143569765
In logs only:
> Hang tight, the log cannot be shown until the build has started.

**Comment by jayvdb** [comment]
This is occurring on linux container builds, but https://www.traviscistatus.com/ says they are operational, while showing that they are not:

![travis-status-20160709](https://cloud.githubusercontent.com/assets/15092/16708939/d29affb0-462c-11e6-8ec3-aa2fe48f7a2e.png)

**Comment by bakwc** [comment]
Also sometimes build starts if I manually request rebuild of **another** old build. Request to rebuild the same build doesn't help.

**Comment by jayvdb** [comment]
Travis have now issued a status update:

> Investigating - We are investigating why jobs are not being scheduled on travis-ci.org
> Jul 9, 17:34 UTC

**Comment by BanzaiMan** [comment]
Please follow the status page.
