### ISSUE TITLE
Long wait for builds

### ISSUE THREAD

**Issue by nojvek** [travis-ci/travis-ci#6293]
Some builds could take upto an hour to start. Some start within a couple of minutes. I understand using the free version means you can't have your cake and eat it. 

It would be nice to at least display an expected wait time before a build starting. I wonder if it makes sense for travis to offer a feature of immediate builds for a fixed price per build. e.g 50c/build for prioritised almost immediate build.

Kind of like how reddit has give gold feature.

**Comment by jayvdb** [comment]
The current delays are probably due to some operational problem; see #6292

**Comment by nojvek** [comment]
Just curious if there is a way I could bring my own hardware for travis to run the builds?

I have a few digitial ocean nodes that I barely use.

**Comment by BanzaiMan** [comment]
Please follow the status page.
