### ISSUE TITLE
Maven central deployment fails due to password encryption

### ISSUE THREAD

**Issue by skokaina** [travis-ci/travis-ci#6294]
Hi,

Deploying to Maven Central through Travis fails using env. variable for the server password.
Here's an example of failing deployment: https://travis-ci.org/toast-tk/toast-tk-engine/builds/143695617

Here's an extract of our settings.xml:
```xml
<server> 
  <id>ossrh</id>  
  <username>${env.OSSRH_USER}</username>   
  <password>${env.OSSRH_PWD}</password>  
</server> 
```

Here's the error at deploy time:
```java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project toast-tk-interpret: 
Failed to deploy artifacts: Could not transfer artifact io.toast-tk:toast-tk-engine:pom:0.1.3-20160710.114031-5 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): 
Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/io/toast-tk/toast-tk-engine/0.1.3-SNAPSHOT/toast-tk-engine-0.1.3-20160710.114031-5.pom. 
Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
```

Having the password directly set and unencrypted in our settings.xml works but not secure.

Any help, hint would be really appreciated.

**Comment by BanzaiMan** [comment]
Encrypt the password and assign it to an environment variable. Then use `sed` (or `awk`, or write a small script) to modify `settngs.xml` in `before_deploy`.

**Comment by skokaina** [comment]
Thanks for the hint, still the issue came from the password we are using, it contains special characters and travis is truncating the value when these aren't escaped.

https://docs.travis-ci.com/user/encryption-keys/
