### ISSUE TITLE
R: Enable memory profiling, i.e. ./configure --enable-memory-profiling (Linux)

### ISSUE THREAD

**Issue by HenrikBengtsson** [travis-ci/travis-ci#6295]
Please consider enabling memory profiling for the Travis R binaries, i.e. build R using:

``` sh
./configure --enable-memory-profiling
```

The overhead of this is minimal; it's [basically a boolean test (that resolved to FALSE by default)](https://github.com/wch/r-source/blob/tags/R-3-3-0/src/main/memory.c#L2638-L2640) added to each native `allocVector()` call.  Compared to the rest of the `allocVector()` code, the added overhead is teeny (=near zero).

cc: @craigcitro, @hadley and @jimhester

**Comment by HenrikBengtsson** [comment]
I should clarify that this request is for the Linux builds.  It looks like it is indeed enabled for the macOS builds.

**Comment by jimhester** [comment]
Seems like a reasonable suggestion, would it work to enable it only for devel builds or would you prefer it for all builds?

**Comment by HenrikBengtsson** [comment]
Yes, R-devel would be good enough.

FYI, I don't think it would affect the processing time noticeably (= "at all").  For instance, Radford Neal says ""the overhead of having [Rprofmem()] enabled is negligible when profiling is not actually being done" (https://mailman.stat.ethz.ch/pipermail/r-devel/2011-August/061783.html).  I haven't done benchmarking by from code inspection this seems very reasonable.  In other words, I'm think it's 99.9% safe to just enable it.

**Comment by HenrikBengtsson** [comment]
Any updates on this?

If in doubt, I'd say just enable it for all versions, because there is literally no overhead; I bet a beer with anyone who can show me a reasonable benchmark where you actually see a difference in performance.

**Comment by HenrikBengtsson** [comment]
A kind reminder, would like to use this to test [profmem](https://cran.r-project.org/package=profmem), but not critical.

**Comment by jimhester** [comment]
In an hour or two this should now be enabled for all R versions on Travis and for R-devel as well. Thank you for your extreme patience with this, this issue can now be closed.

**Comment by HenrikBengtsson** [comment]
Hey, I've got the patience of an oyster :)  (ha, just googled for what that idiom could be in English, so not sure if it's correct).  Thxs for adding this.

**Comment by HenrikBengtsson** [comment]
Just noticed that [R-devel on Travis CI i no longer built with profmem capabilities](https://travis-ci.org/HenrikBengtsson/profmem/jobs/334182245#L850-L851):
```r
$ Rscript -e 'capabilities()' -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE       FALSE        TRUE        TRUE        TRUE        TRUE 
physical  logical 
      32       32 
```

R oldrel and release _do_ have profmem capabilities.

**Comment by HenrikBengtsson** [comment]
Still the case that R-devel is not built with `--enable-memory-profiling`.

**Comment by HenrikBengtsson** [comment]
Still the case that R-devel is not built with --enable-memory-profiling.

**Comment by HenrikBengtsson** [comment]
Ping

**Comment by jimhester** [comment]
This should now be fixed for R-devel, the issue was the `--enable-memory-profiling` was inadvertently added to the wrong `configure` call. https://travis-ci.org/wch/r-source/jobs/467041306#L4268

This issue can now be closed.
