### ISSUE TITLE
Executing Dredd Tests and sbt run on Travis CI for Play Framework Application

### ISSUE THREAD

**Issue by jesuscreyes** [travis-ci/travis-ci#6296]
I'm trying to run Dredd tests on Travis CI for a simple Play Framework Application in Scala.

The lines in my `.travis.yml` file that call the Dredd test are configured as follows:
![screen shot 2016-07-11 at 8 40 38 am](https://cloud.githubusercontent.com/assets/9061700/16736757/3a9f110c-4743-11e6-9622-bb42a5038502.png)

And in my `dredd.yml` file I have the configuration as follows:
![screen shot 2016-07-11 at 8 42 33 am](https://cloud.githubusercontent.com/assets/9061700/16736810/72341c7a-4743-11e6-96d5-0d5ce2e3fb14.png)

I'm able to run my Dredd tests locally, but not through travis CI. The error I get in Travis is this:
<img width="591" alt="screen shot 2016-07-11 at 8 37 30 am" src="https://cloud.githubusercontent.com/assets/9061700/16736699/02f2e0da-4743-11e6-8a20-abeab46a1eeb.png">

For some reason, Travis CI automatically stops the server before I can perform the Dredd tests. Is there a way to configure it so that I'm able to run my Dredd tests while the server is running?

**Comment by BanzaiMan** [comment]
Why is your server stopping?

**Comment by jesuscreyes** [comment]
That's what I'm trying to figure out. For some reason my Dredd test execution runs differently on Travis CI than on my local machine. I'm wondering if the Travis environment needs to be configured in a particular way so that the server doesn't stop prematurely.

**Comment by jesuscreyes** [comment]
Resolved my issue by using `docker-compose` instead of `sbt run` which doesn't shut down the server right away. This allowed me to run my Dredd tests fine.

The problem of `sbt run` not working properly on Travis is still an issue.
