### ISSUE TITLE
Suggested documentation addition: install a package that resides in a folder in a GitHub

### ISSUE THREAD

**Issue by richelbilderbeek** [travis-ci/travis-ci#6297]
It took me some time to confirm this finding, so I decided to share this:

Thanks to @craigcitro, @hadley and @jimhester, installing an R package from a GitHub is easy. For example, this is a minimal script that installs Jim's `lintr` GitHub:

```
language: r
r_github_packages: jimhester/lintr
```

Jim put the package its `DESCRIPTION` directly in the root of `lintr`, so this works as shown. 
From [the Travis CI documentation](https://docs.travis-ci.com/user/languages/r) I learn that `DESCRIPTION` should be in the root:

```
r_github_packages: A list of packages to install directly from GitHub,
using devtools::install_github from the devtools package. The package
names here should be of the form user/repo.
```

Yet, I needed to install [a package that resides in a folder in a GitHub](https://github.com/rsetienne/PBD).

I tested that this (IMHO miraculously) works in a [minimal example](https://travis-ci.org/richelbilderbeek/soqpbd) and [complex example](https://travis-ci.org/richelbilderbeek/Cer2016):

```
language: r
r_github_packages: rsetienne/PBD/PBD
```

I suggest to add this to [the Travis CI documentation](https://docs.travis-ci.com/user/languages/r), resulting in (emphasized the addition):

```
r_github_packages: A list of packages to install directly from GitHub,
using devtools::install_github from the devtools package. The package
names here should be of the form user/repo. If the package is installed
in a folder, use user/repo/folder
```

I volunteer to put this in a Pull Request.

**Comment by jimhester** [comment]
Feel free to send a PR for this, however in general I would avoid using `r_github_packages()` in favor of [Remotes:](https://github.com/richelbilderbeek/soqpbd/compare/master...jimhester:master), which has the added benefit of easy installation of dependencies for users of your package as well.
