### ISSUE TITLE
Default Maven wrapper build is failing

### ISSUE THREAD

**Issue by ssherwood** [travis-ci/travis-ci#6298]
My sample project: https://github.com/ssherwood/demo-travis2.  Using a basic .travis.yml

```
language: java
jdk:
- oraclejdk8
```

The Travis build is failing to build with the following error:

```
travis_fold:start:install
[0Ktravis_time:start:032e1122
[0K$ ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=192m; support was removed in 8.0
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain

[31;1mThe command "eval ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed. Retrying, 2 of 3.[0m

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=192m; support was removed in 8.0
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain

[31;1mThe command "eval ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed. Retrying, 3 of 3.[0m

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=192m; support was removed in 8.0
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain

[31;1mThe command "eval ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed 3 times.[0m


travis_time:end:032e1122:start=1468333288578977965,finish=1468333291894162488,duration=3315184523
[0K
[31;1mThe command "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed and exited with 1 during .[0m

Your build has been stopped.
```

As far as I can tell, this should be working with no errors.

**Comment by BanzaiMan** [comment]
>  this should be working with no errors.

I am not sure if that is true. If I start out with a fresh clone of your repository and run `./mvnw install …` similarly fails.

I am not familiar with the maven wrapper, but I do not think this is an issue on our side.

**Comment by juliuskrah** [comment]
I am getting the same issue with the maven wrapper on travis-ci. I'm running default configuration for java
>`language: java`
`jdk:`
`- oraclejdk8`

project: url <https://github.com/juliuskrah/spring-profiles>  
Error output
>$ jdk_switcher use oraclejdk8
Switching to Oracle JDK8 (java-8-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-8-oracle
$ java -Xmx32m -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_31
$ ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
/home/travis/build.sh: line 179: ./mvnw: Permission denied
The command "eval ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed. Retrying, 2 of 3.
/home/travis/build.sh: line 179: ./mvnw: Permission denied
The command "eval ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed. Retrying, 3 of 3.
/home/travis/build.sh: line 179: ./mvnw: Permission denied
The command "eval ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed 3 times.
The command "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed and exited with 126 during .
Your build has been stopped.

**Comment by ssherwood** [comment]
@BanzaiMan Can you be more specific with your error?  When I run it locally, it works just fine.  I assume it is possible that there are external environmental factors that might be at play but I'd like more info to research.

Also, when I change the travis.yml to override the default and use mvn without the wrapper it works without errors:

```

jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
```

See https://github.com/ssherwood/demo-travis9.

The issue that I see is that something in Travis-CI detected the mvn wrapper (mvnw) in the default scenarios for install/script and that behavior fails.  Currently, I'm forced to override it with mvn without the wrapper.  Either Travis-CI default should handle mvnw correctly or it shouldn't try to use the wrapper if it is not going to support it.

**Comment by BanzaiMan** [comment]
```
$ docker run --rm -it quay.io/travisci/travis-jvm /bin/bash
root@148e2fccb10e:/# su - travis
travis@148e2fccb10e:~$ git clone --depth=50 --branch=master https://github.com/ssherwood/demo-travis2.git ssherwood/demo-travis2
Cloning into 'ssherwood/demo-travis2'...
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 24 (delta 0), reused 24 (delta 0), pack-reused 0
Unpacking objects: 100% (24/24), done.
Checking connectivity... done.
travis@148e2fccb10e:~$ cd ssherwood/demo-travis2/
travis@148e2fccb10e:~/ssherwood/demo-travis2$ git checkout -qf 6ce6561d8a713eb2ffa00fa506b76a67be2f197d
travis@148e2fccb10e:~/ssherwood/demo-travis2$ jdk_switcher use oraclejdk8
Switching to Oracle JDK8 (java-8-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-8-oracle
travis@148e2fccb10e:~/ssherwood/demo-travis2$ ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=192m; support was removed in 8.0
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
```

**Comment by BanzaiMan** [comment]
with `bash -x`, this command is executed at the end:

```
+ exec /usr/lib/jvm/java-8-oracle/bin/java -Dmaven.repo.local=/home/travis/.m2/repository -Xmx512m -XX:MaxPermSize=192m -classpath /home/travis/ssherwood/demo-travis2/.mvn/wrapper/maven-wrapper.jar -Dmaven.home=/usr/local/maven -Dmaven.multiModuleProjectDirectory=/home/travis/ssherwood/demo-travis2 org.apache.maven.wrapper.MavenWrapperMain install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
```

**Comment by ssherwood** [comment]
Ok, I think I'm starting to figure out what is going on.  The problem is that the mvn wrapper relies on a jar file stored in the .mvn directory of the project.  I've compared my local repo with what GitHub has and its clear that GitHub is somehow stripping/ignoring the jar file used by the wrapper (thus the "Could not find or load main class...".

I'm going to do a little more research to see what other people are doing with the mvn/gradle wrappers in respect to GitHub.  I'm going to assume there is some kind of init step that I can perform that may pull down the required jar as part of the CI build.

**Comment by ssherwood** [comment]
I made a change to the travis.yml and get a successful build now:

```
language: java
jdk:
- oraclejdk8
# GitHub strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
```

I'm having to customize the install step to include a precursor call using mvn itself to download the wrapper jar before running `./mvnw install...`  It would be nice if Travis was able to detect this scenario and default the install process to do the first step if the file .mvn/maven-wrapper.jar doesn't exist (run mvn -N io.takari:maven:wrapper).

I assume other people will hit this snag if they try to use the maven wrapper with GitHub.

**Comment by BanzaiMan** [comment]
@juliuskrah Your `./mvnw` is not executable. (We should probably check the execute bit anyway, and not invoke it.)

**Comment by juliuskrah** [comment]
@BanzaiMan I added this bit to my `.travis.yml` file and it fixed my error.
```bash
before_install:
  - chmod +x mvnw
```

**Comment by BanzaiMan** [comment]
@juliuskrah It's much better to turn on the execute bit on your `mvnw` and commit that to the repo, IMO. Regardless, I'm happy to hear that you were able to overcome the problem.

**Comment by juliuskrah** [comment]
@BanzaiMan My dev environment is a Windows setup and I cannot easily turn on the execute bit. :smile:
Any workarounds will be appreciated.

**Comment by BanzaiMan** [comment]
http://stackoverflow.com/a/21694391/136333

`git update-index --chmod=+x mvnw`

**Comment by juliuskrah** [comment]
@BanzaiMan Thanks man...It works 👍

**Comment by EdenilsonJak** [comment]
esse comando funcionou no meu projeto
before_install:
  - chmod +x mvnw

**Comment by eliasreis54** [comment]
@ssherwood Thanks! Is working now

**Comment by Bacs2009** [comment]
> @BanzaiMan Can you be more specific with your error? When I run it locally, it works just fine. I assume it is possible that there are external environmental factors that might be at play but I'd like more info to research.
> 
> Also, when I change the travis.yml to override the default and use mvn without the wrapper it works without errors:
> 
> ```
> 
> jdk:
> - oraclejdk8
> # would just use default install/script but the ./mvnw script errors on travis
> # obviously this only works for maven builds right now...
> install:
> - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
> script:
> - mvn test
> ```
> See https://github.com/ssherwood/demo-travis9.
> 
> The issue that I see is that something in Travis-CI detected the mvn wrapper (mvnw) in the default scenarios for install/script and that behavior fails. Currently, I'm forced to override it with mvn without the wrapper. Either Travis-CI default should handle mvnw correctly or it shouldn't try to use the wrapper if it is not going to support it.

Thanks. It works for me

**Comment by pujanov69** [comment]
> I made a change to the travis.yml and get a successful build now:
> 
> ```
> language: java
> jdk:
> - oraclejdk8
> # git strips the wrapper jar file so we have to force its download during the build
> install:
> - mvn -N io.takari:maven:wrapper
> - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
> ```
> 
> I'm having to customize the install step to include a precursor call using mvn itself to download the wrapper jar before running `./mvnw install...` It would be nice if Travis was able to detect this scenario and default the install process to do the first step if the file .mvn/maven-wrapper.jar doesn't exist (run mvn -N io.takari:maven:wrapper).
> 
> I assume other people will hit this snag if they try to use the maven wrapper with GitHub.
> 
> _UPDATE_: After a little more research, I figured out it was my .gitignore that was causing the problem as it needed an additional line to not ignore the maven-wrapper.jar. I added a !maven-wrapper.jar and that preserves the jar file that needs to be pushed. As this is now my fault, I don't expect Travis to protect me from myself. Hopefully this issue will help others in the future if they hit a similar problem.

Thanks for this beautiful hack
