### ISSUE TITLE
Go job should error if the desired Go version is not available for use

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#6299]
Supersedes https://github.com/travis-ci/gimme/issues/53

When an invalid Go version is given, we end up with:

```sh-session
$ eval "$(gimme 1.7)"
I don't have any idea what to do with '1.7'.
  (using type 'auto')
```

The build continues with the default Go version, which is misleading and undesirable.

**Comment by breerly** [comment]
Looks like running `eval "$(gimme 1.7)"` in one line is masking the exit code:

```
$ eval "$(gimme 1.7)"
I don't have any idea what to do with '1.7'.
  (using type 'auto')

$ echo $?
0
```

If you run gimme directly, it exits with a `1` status code:

```
$ gimme 1.7
I don't have any idea what to do with '1.7'.
  (using type 'auto')

$ echo $?
1
```
