### ISSUE TITLE
Hash Sum mismatch

### ISSUE THREAD

**Issue by obazoud** [travis-ci/travis-ci#6302]
I got the following error in several projects:

```
apt-get update -qq
W: Size of file /var/lib/apt/lists/httpredir.debian.org_debian_dists_jessie-updates_main_binary-amd64_Packages.gz is not what the server reported 17565 17587
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Any workaround ?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by ryneeverett** [comment]
Workaround for me is running `apt-get update` twice consecutively. I can consistently reproduce this:

```console
$ docker run -it --rm quay.io/travisci/travis-python /bin/bash
root@5156e495023f:/# sudo rm -f /etc/apt/sources.list.d/rabbitmq-source.list
root@5156e495023f:/# apt-get update
...
Reading package lists... Done
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-amd64_Packages.gz is not what the server reported 33653 36677
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-i386_Packages.gz is not what the server reported 33699 36733
W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-backports_multiverse_source_Sources.gz is not what the server reported 5886 5888
root@5156e495023f:/# apt-get update
...
Reading package lists... Done
root@5156e495023f:/#
```

**Comment by catskul** [comment]
Same problem here: 
https://travis-ci.org/catskul/cldoc/builds/342207581

**Comment by lukebakken** [comment]
@vitaly-krugl found some information that may shed light on this issue and commented [here](https://github.com/pika/pika/pull/1016#issuecomment-381271793):

* https://askubuntu.com/questions/329450/e-some-index-files-failed-to-download-they-have-been-ignored-or-old-ones-used
* https://ubuntuforums.org/showthread.php?t=1654068

**Comment by vitaly-krugl** [comment]
@lukebakken, this should probably get reopened. The only reason it has gone stale is because @travis-ci has not been responsive.

**Comment by lukebakken** [comment]
@vitaly-krugl in our case the problem stemmed from ESL's Erlang packages.
