### ISSUE TITLE
OSX builds not timing out

### ISSUE THREAD

**Issue by jobevers** [travis-ci/travis-ci#6303]
My builds on OSX are not timing out and become instead like a zombie process.  No progress is made in the log, but the job timer keeps increasing and the job continues to say that it is running.

I had one build continue in this state for over two hours before I had to manually cancel it.

**Comment by jakirkham** [comment]
Same story. Though it looks like the queue is totally saturated AFAICT. Maybe this is fallout from the GitHub issues yesterday?

**Comment by jakirkham** [comment]
Maybe not exactly as the OP described, but this [log]( https://travis-ci.org/conda-forge/slacker-feedstock/builds/144452925 ) is prettying interesting. Note all of the matrix builds should take roughly the same amount of time (e.g. a couple of minutes).

**Comment by jobevers** [comment]
Here is one that ran for 73 minutes before I manually cancelled it: https://travis-ci.org/lbryio/lbrycrd/jobs/144344633

This one was 3h14m: https://travis-ci.org/lbryio/lbrycrd/jobs/144315999

**Comment by jakirkham** [comment]
This shows this issue ( https://github.com/travis-ci/travis-ci/issues/5334 ) as well.

**Comment by jakirkham** [comment]
Not sure if this is related, but we have a zombie job.

<img width="1552" alt="screen shot 2017-04-06 at 19 05 33" src="https://cloud.githubusercontent.com/assets/3019665/24779095/1506b73c-1afc-11e7-87ef-f37d3af21ead.png">

ref: https://travis-ci.org/conda-forge/gflags-feedstock/builds/197161541

**Comment by Lyoness** [comment]
Hello All, this is a stale ticket, and I'm closing out. 

Build that are stuck in the `created` state but not running have been identified to a few causes:  one cause is a disconnected "golden" xcode host that your build vms get provisioned from.  We've improved the alerting and remediation so that these hosts can be brought back online immediately.  

Thanks.
