### ISSUE TITLE
Rackspace cloudfiles deploy fails with permission denied error (mkdir .dpl)

### ISSUE THREAD

**Issue by ariddell** [travis-ci/travis-ci#6305]
This is the error I'm getting
```
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir': Permission denied - .dpl (Errno::EACCES)
```
Perhaps this can be fixed with a change in the settings of the container?

Failing build is available here: https://travis-ci.org/ariddell/lda-manylinux/jobs/144441028

Thanks!

**Comment by BanzaiMan** [comment]
What user owns the directory `wheelhouse`?

**Comment by ariddell** [comment]
Thanks for looking at this. I found a workaround so I'm happy for now.
