### ISSUE TITLE
R: Build fail when depending on private Github repository

### ISSUE THREAD

**Issue by eriknil** [travis-ci/travis-ci#6306]
I'm unable to build any R-packages that depend on private repositories.

The problem is in ´devtools´ (see https://github.com/hadley/devtools/issues/1262). Package names cannot be resolved if authentication is required. I get the same error if I supply a non-existing Github repository under `Remotes:` in the DESCRIPTION file for the package:

``` yaml
Suggests: missingPackage
Remotes: not-a-user/missingPackage
```

I have uploaded an example of the latter at https://github.com/eriknil/depError . You can find a failing build at https://travis-ci.org/eriknil/depError/builds/144513294.

I have also submitted a PR for `devtools` (see https://github.com/hadley/devtools/pull/1263) that should fix the problem.

@craigcitro @hadley @jimhester

**Comment by DavidSichau** [comment]
@craigcitro @hadley @jimhester 

Is there any chance that this will be fixed, or do you need any help in fixing this?
