### ISSUE TITLE
Rackspace cloudfiles deploy silently fails on OS X

### ISSUE THREAD

**Issue by ariddell** [travis-ci/travis-ci#6309]
The cloudfiles deploy block never gets executed.

- The commit builds successfully (not deploying because not tagged): https://travis-ci.org/ariddell/lda-wheel-builder/builds/144730619
- Same commit, but tagged, fails to deploy and is marked as failed: https://travis-ci.org/ariddell/lda-wheel-builder/builds/144733695

Thanks

EDIT: script is based on https://github.com/MacPython/scikit-learn-wheels, perhaps @matthew-brett is encountering this as well?

**Comment by matthew-brett** [comment]
This is the behavior I see when trying to use the Rackspace deploy from the Linux trusty image : https://github.com/travis-ci/travis-ci/issues/4853#issuecomment-225757663  .  I must admit that, since then, I have switched to using https://github.com/ogrisel/wheelhouse-uploader instead.

**Comment by ariddell** [comment]
Thanks. I managed to get the strategy on display in https://github.com/MacPython/matplotlib-wheels working. Thanks for all your work on these systems!

**Comment by BanzaiMan** [comment]
Closing, since the issue appears to have been resolved (for the repository's use case).

**Comment by matthew-brett** [comment]
I believe that the resolution was not using the travis-ci rackspace deploy scripts - so does closing this issue imply that you are not going to fix?

**Comment by BanzaiMan** [comment]
@matthew-brett It was? https://github.com/ariddell/lda-wheel-builder is no longer available, so I have no way to verify that. I think your case #4853 might be different, but I see how it can be confusing. I'll make a comment there shortly.
