### ISSUE TITLE
stuck build

### ISSUE THREAD

**Issue by ignatenkobrain** [travis-ci/travis-ci#6310]
Hi, https://travis-ci.org/ignatenkobrain/rpm-gitoverlay/builds/144761342 is just stuck (never started actually). I tried to cancel previous and start new one, but nothing happened.

**Comment by graemerocher** [comment]
I have some stuck builds too https://travis-ci.org/grails/gorm-hibernate5/builds

**Comment by ignatenkobrain** [comment]
hm, some of builds just proceeded, but new builds stuck again...

**Comment by BanzaiMan** [comment]
Could you try restarting them now? We had issues with build processing earlier.

**Comment by ignatenkobrain** [comment]
hm, still doesnt work: https://travis-ci.org/ignatenkobrain/rpm-gitoverlay/builds/144781080

**Comment by ignatenkobrain** [comment]
disabled CI integration in my project, enabled back. Closed-Opened PR: new one is stuck (https://travis-ci.org/ignatenkobrain/rpm-gitoverlay/builds/144787406)

**Comment by graemerocher** [comment]
Still hanging for me too.. all builds in this org seem stuck https://travis-ci.org/grails

**Comment by ignatenkobrain** [comment]
Looks like fixed.
