### ISSUE TITLE
NPM setup fails for language: node_js, os: osx, node_js: 0.8

### ISSUE THREAD

**Issue by chearon** [travis-ci/travis-ci#6315]
This error seems to be coming from the generated build script, it runs right after `nvm install`.

```
npm config delete prefix
npm ERR! Error: ENOENT, unlink '/Users/travis/.npmrc'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Darwin 15.5.0
npm ERR! command "/Users/travis/.nvm/v0.8.28/bin/node" "/Users/travis/.nvm/v0.8.28/bin/npm" "config" "delete" "prefix"
npm ERR! cwd /Users/travis/build/chearon/travis-test
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm ERR! path /Users/travis/.npmrc
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/travis/build/chearon/travis-test/npm-debug.log
npm ERR! not ok code 0
```

It's reproducible, I made a bare repository with just a `travis.yml` and a `package.json`

* Test repository: https://github.com/chearon/travis-test
* Failing build with node 0.8: https://travis-ci.org/chearon/travis-test/jobs/145017050
* Successful build with node 6: https://travis-ci.org/chearon/travis-test/jobs/145017051

I tried doing the `npm config delete prefix` on my own computer, apparently with node 0.8 you can't do that if there is no `npmrc` file:

```
$ node -v
v0.8.28
$ npm config delete prefix
npm ERR! Error: ENOENT, unlink '/Users/caleb/.npmrc'
...
```

I can't seem to create a work around either, since the `before_install` hook happens after NPM is setup. All I would have to do is create ~/.npmrc, I think

**Comment by BanzaiMan** [comment]
Is this not a Node.js/npm issue?

**Comment by chearon** [comment]
It definitely is, but without Travis doing some kind of work around, the node 0.8 + OS X environment doesn't work. I don't think there's any work around you can do from the travis.yml
