### ISSUE TITLE
CoverityScan : Ignoring unknown extended header keyword

### ISSUE THREAD

**Issue by Zyres** [travis-ci/travis-ci#6316]
sudo: false
language: cpp
os: linux

Seems something changed on coverity and/or travis. Maybe this issue is based on the new analysis version 8.5.0.

Last successful analysis on 3. Juli: https://travis-ci.org/AscEmu/AscEmu/builds/142054869
Current failing analysis: https://travis-ci.org/AscEmu/AscEmu/builds/144985454

Project: https://github.com/AscEmu/AscEmu

Extracting files:
![covscan](http://i.imgur.com/i9eH0Nd.jpg)

SCM/Data:
![oanalysis](http://i.imgur.com/WyyVaRz.jpg)

**Comment by BanzaiMan** [comment]
I tend to think this is an issue with Coverity Scan itself. We have not changed anything with the way we invoke the tool.

Have you dumped `/home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/scm_log.txt` and analyzed it? Have you gotten in touch with Coverity for support?

**Comment by Zyres** [comment]
> Have you gotten in touch with Coverity for support?

I contacted them, yes... They did not answered my e-mail yet

> Have you dumped /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/scm_log.txt

No, coverity-scan did not run/work while compiling the code, so I assume the information in the scm_log.txt is not helpful at all

**Comment by BanzaiMan** [comment]
Did you hear from Coverity? The script is failing when it tries to extract the archive. I don't think there is much for us to do.

Do let us know if it turns out that there is something we should do.

**Comment by Zyres** [comment]
> Do let us know if it turns out that there is something we should do.

![cove_twitter](http://i.imgur.com/W0XoSN3.jpg)
That was the response...

> The script is failing when it tries to extract the archive. I don't think there is much for us to do.

I don't know either.... Is my travis.yml the source of this issue?

**Comment by Zyres** [comment]
Update:
Switched from gcc 4.8 to 5
Current build: https://travis-ci.org/AscEmu/AscEmu/builds/146715544 
Still the same issue, hope for a solution on twitter... I update this issue if something change.

**Comment by Zyres** [comment]
@BanzaiMan Finally I received an answer.
![co-answer](http://i.imgur.com/TSMFl7G.jpg)

So I have no clue if it is a travis or a coverity issue... I will try to check the solution...
It looks like #6274 is still valid and it would be awsome if you can talk directly to to coverity.... Sure I try to help but currently I feel like a Hamster in a wheel.

**Comment by Zyres** [comment]
A short update (to fill the knowledge base for other peoples)

This looks to resolve the compiler issue in#6274
Configure coverity add something like "cov-configure --comptype gcc --compiler /usr/bin/gcc-5"
Covereity gives me the following note:
![cov-note](http://i.imgur.com/oukSnH1.jpg)
So it seems it did not recognize gcc as compiler.

I never noticed the travis versions of coverity-scan... Did travis use the normal Linux version?  idk I just give you the information I collected so far....
![cov-travis-versions](http://i.imgur.com/ODoO8ve.jpg)

**Comment by BanzaiMan** [comment]
OK. I'll try getting in touch with them.
