### ISSUE TITLE
Make cache expiration configurable

### ISSUE THREAD

**Issue by lukeyeager** [travis-ci/travis-ci#6318]
> The caches expire when they are 45 days old, and this value is not configurable.
https://github.com/travis-ci/travis-ci/issues/6317#issuecomment-233065994

I'd like to be able to configure how long caches last before they expire. In my use case, I'd like to cache the build for 1 week, so a re-build is forced each week.

**Comment by lukeyeager** [comment]
Also requested here:

> It'd be useful to add the ability to clear stale caches, for some definition of stale, e.g. created/used more than X days ago. 
https://github.com/travis-ci/travis-ci/issues/6170#issue-160216372

**Comment by BanzaiMan** [comment]
I understand that you want to control this, but he expiration has to be set for everyone, since the parameter is applicable to all caches used by our service.

**Comment by lukeyeager** [comment]
Ok. Thanks for the quick responses and clear explanations!
