### ISSUE TITLE
PHP 7.1 build fails in pre-script trying to turn off xdebug

### ISSUE THREAD

**Issue by Dragonrun1** [travis-ci/travis-ci#6321]
I understand that xdebug probably isn't ready for PHP 7.1 yet but an empty xdebug.ini file would keep tests from failing.
https://travis-ci.org/Yapeal/yapeal-ng/jobs/145160044

**Comment by BanzaiMan** [comment]
I don't think the current PHP 7.1 (alpha3) has xdebug enabled. If it did, `composer self-update` would complain. Compare [7.1](https://travis-ci.org/BanzaiMan/travis_production_test/jobs/145162300#L134) and [7.0.8](https://travis-ci.org/BanzaiMan/travis_production_test/jobs/145162299#L135).

So you should just skip it.

**Comment by Dragonrun1** [comment]
Don't know you could disable before_script: in travis.yml on a per build basis could you direct me to some docs on how to do that?

**Comment by BanzaiMan** [comment]
```yaml
before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]]; then phpenv config-rm xdebug.ini; fi
```

See https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

**Comment by Dragonrun1** [comment]
TY

**Comment by Dragonrun1** [comment]
Since it's always better to do feature checking then version I came up with this so when PHP 7.1 gets a xdebug version it'll still work there as well.
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi

Took me a lot of tries to get it right since my bash skills are very rusty but it now works like a charm

**Comment by Jean85** [comment]
Could we please reopen this issue? We are close to the end of RC phase for 7.1 and xDebug is starting to support it: https://xdebug.org/updates.php

**Comment by BanzaiMan** [comment]
Recent 7.1 archives should have it enabled. https://github.com/php-build/php-build/blob/master/share/php-build/definitions/7.1snapshot https://github.com/php-build/php-build/blob/master/share/php-build/definitions/7.1.0RC6

**Comment by Jean85** [comment]
I'm not sure it's working. Those commits are from 10 days ago; I have a failed build for missing xdebug from yesterday: https://travis-ci.org/facile-it/paraunit/jobs/178010991
```
$ php --version
PHP 7.1.0RC6 (cli) (built: Nov 10 2016 22:24:18) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0RC6, Copyright (c) 1999-2016, by Zend Technologies
```

versus

```
$ php --version
PHP 7.0.13 (cli) (built: Nov 10 2016 22:24:42) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans```

**Comment by Jean85** [comment]
Now it seems to work! https://travis-ci.org/facile-it/paraunit/jobs/178336396

```
$ php --version
PHP 7.1.0RC6 (cli) (built: Nov 22 2016 16:43:21) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0RC6, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0rc2-dev, Copyright (c) 2002-2016, by Derick Rethans
```
