### ISSUE TITLE
Missing phpdbg for php 5.6

### ISSUE THREAD

**Issue by Dragonrun1** [travis-ci/travis-ci#6323]
Try to use phpdbg which comes with PHP starting with version 5.6 but build fails with code 127.
Is there a reason it's left out for 5.6 but include with 7.0 and 7.1 or is it just oversight to change?

https://travis-ci.org/Dragonrun1/event-mediator/jobs/145229016

**Comment by BanzaiMan** [comment]
We use php-build to build our image. I am not sure if it supports phpdbg for 5.6 yet. https://github.com/php-build/php-build/issues/164

**Comment by BanzaiMan** [comment]
I am afraid this must wait until php-build supports it and our PHP image is updated.

I'm going to close this for now, and revisit when that time comes.

**Comment by Dragonrun1** [comment]
Thanks for looking into it I was just surprised it wasn't there since phpdbg is included with PHP 5.6 as part of core just like cli, cfg, etc. My main concern now would be that since 5.6 has less then a year before EOL by the time it gets add it might not matter to anyone, include possibly me, as everyone will be focused on 7.0 and 7.1 where phpdbg is being built by default already.

I'm sure I'm not alone in mostly using xdebug and phpdbg for their profiling ability to generate clover coverage that is passed on to other mostly off site tools to give me some pretty reports 😉. Otherwise I would not use either as they just slow my test suites and the builds overall with little benefit.

**Comment by alariva** [comment]
I'm facing sort of the same issue, is there any update on this somewhere else?

**Comment by BanzaiMan** [comment]
Please help out on the php-build issue that I linked previously. Thank you.
