### ISSUE TITLE
Fastlane broken dependencies

### ISSUE THREAD

**Issue by MP0w** [travis-ci/travis-ci#6325]
Since some days my build broke -> https://travis-ci.org/devlucky/Kakapo/jobs/145379688
The build doesn't even start because Fastlane has dependency conflicts 

```
/Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate krausefx-shenzhen-0.14.9, because json-2.0.1 conflicts with json (~> 1.8) (Gem::ConflictError)
```

I believe this happened due to a recent update of the OS X VM image

**Comment by BanzaiMan** [comment]
Indeed, the Xcode 7.3 comes with json 2.0.1 pre-installed (probably because it was the latest version when the image was re-provisioned).

Could you try uninstalling that in `before_install` for the time being?

**Comment by MariadeAnton** [comment]
Also reported at: https://github.com/fastlane/fastlane/issues/5381

**Comment by MP0w** [comment]
Thank you and sorry for the late reply, I tried the workaround and seems to work ATM

**Comment by BanzaiMan** [comment]
Thanks for the confirmation. I'm closing this now.
