### ISSUE TITLE
Recent OS X worker update broke SQLite in some way

### ISSUE THREAD

**Issue by Minoru** [travis-ci/travis-ci#6329]
I have this code that built successfully just a week ago: https://travis-ci.org/akrennmair/newsbeuter/jobs/144147088

Now the same code fails to build: https://travis-ci.org/akrennmair/newsbeuter/builds/145505645

It seems like `pkg-config` can't find SQLite anymore. From what I see, SQLite itself wasn't updated, so it's not a problem with Homebrew formula.

I don't have an OS X machine so I can't easily fiddle with the configuration to see what works. Any pointers as to what might be causing the build to fail?

**Comment by DomT4** [comment]
In your [deps](https://github.com/akrennmair/newsbeuter/blob/master/travis-get-deps.sh) script add a line checking for an outdated `pkg-config` formulae & `upgrade` it if necessary. That should fix your issue.

This isn't Travis' fault, we refactored some "stuff" upstream in Homebrew to account for trying to make Homebrew more cross-platform.

**Comment by BanzaiMan** [comment]
@DomT4 Thanks for the information.

I'm closing this now; if there is new information to indicate that there is something on our side to do, let us know.

**Comment by Minoru** [comment]
Indeed, that [fixed the build](https://travis-ci.org/akrennmair/newsbeuter/jobs/145521550). Thanks, @DomT4!
