### ISSUE TITLE
Builds for repos owned by jayvdb not triggered

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#6331]
Commits to my own repos (`jayvdb/..`) have not been building for ~4days.
I've tried builds on a few of my own repos (`jayvdb/..`), to no avail, but commits to master of other projects work ok. `jayvdb/tox-travis`, `jayvdb/pyflakes`, `jayvdb/flake8-putty` and `jayvdb/my-ci-test` all have recent commits with no build triggered.

https://travis-ci.org/jayvdb/tox-travis/builds/145144692 is the last build Travis performed for `jayvdb/..` repos. If the size of that build matrix was a problem, maybe the context at https://github.com/ryanhiebert/tox-travis/issues/22 and https://github.com/pypa/packaging/issues/72#issuecomment-232818577 will be helpful.  Happy to abide by any soft limits if required to have a block lifted.

**Comment by BanzaiMan** [comment]
Hello. Your account has been marked as a potential abuser. Please email support@travis-ci.com so that we can discuss this in more detail.

I'm closing this in the mean time.

**Comment by jayvdb** [comment]
Problem resolved.  Thank you.
