### ISSUE TITLE
language: haskell is seriously busted; please update docs to not recommend it

### ISSUE THREAD

**Issue by ezyang** [travis-ci/travis-ci#6335]
How are thee busted? Let me count the ways:
1. https://docs.travis-ci.com/user/languages/haskell links to three "example" projects for the mode, NONE of which use `language: haskell`.
2. 7.8 is the latest version supported. No later versions are installed on the VM.
3. It's impossible to stop the image from running `cabal update`. Some of us just want our damn GHC binaries!
4. The GHCs that are installed do not come with dynamic or profiling libraries.

**Comment by BanzaiMan** [comment]
Thanks for opening the issue.

1. Some of the examples appear to have diverged from `language: haskell`. See, for example, https://github.com/hspec/hspec/blob/288a967b6ac7b7a0c2f9b743322c51b93bea2bdd/.travis.yml, https://github.com/lwm/es-api/blob/391b1d7ab22852088340a9b8a1c34b48b913683f/.travis.yml. If these are no longer using `language: haskell`, it is best to just remove them from the document.
1. Sorry for the delay in updating the build image. We plan to carry out the update soon.
1. `cabal update` comes from https://github.com/travis-ci/travis-build/blob/bbe7c12b6f2c8bdc6cd9a7d3e839a729048648ae/lib/travis/build/script/haskell.rb#L10. It is easy to remove this, but I think some existing builds may depend on it. It is straightforward to add on option to skip this.
1. We use the official tarball from http://www.haskell.org/, using the Chef cookbook shown here: https://github.com/travis-ci/travis-cookbooks/tree/master/cookbooks/haskell. If you have suggestions to improve it, please let us know.

**Comment by BanzaiMan** [comment]
I've removed the examples from the docs.

**Comment by BanzaiMan** [comment]
Trusty images have newer versions pre-installed.

**Comment by BanzaiMan** [comment]
For now, we'll keep `cabal update`.

If you have suggestions on improving the Haskell cookbooks, please open a separate issue to discuss specific improvements.

I'm closing this now.
