### ISSUE TITLE
Triggered build is for pull request, not commit

### ISSUE THREAD

**Issue by fritsjanb** [travis-ci/travis-ci#6337]
The build that is being triggered by a commit builds the latest version of a pull request, and not necessarily that commit.

Say I have a branch `foo` with a pull request, and I push a commit `commit 1` to it.
This triggers a build, starting the worker, etc.

If I push another commit to the same branch (say commit `commit 2`, meaning the branch `foo` now has `commit 1` and `commit 2`), it triggers a new build. However, if the first build has not yet fetched the code, the first build also contains the commit `commit 2`.

Cause:

``` sh
$ git clone --depth=50 git@github.com:repo/repo
Cloning into 'repo/repo'...
$ cd repo/repo
$ git fetch origin +refs/pull/pull-nr/merge:
```

The result is that Travis CI provides a potential false positive for my `commit 1`.

Of course, it only shows the false positive when `commit 2` actually passed all tests. Not the end of the world, but it does cause a lot of confusion.

Would it make sense to instead of merging the pull request, merge the commit (and its parent commits) that triggered the build?

**Comment by BanzaiMan** [comment]
I don't think there is much we can do in this scenario. Once `commit2` is pushed, the merge commit for the open PR will point to that commit. I am not sure if there is a way to specify "the merge commit of the head branch and `commit1`".

When do you want to test intermediate commits? You can't merge the PR without merging the last commit, can you?

**Comment by fritsjanb** [comment]
The reason I ran into this issue was because we had a green build that had a bug - we had a missing test and a buggy implementation.

I first wrote a failing test case and committed and pushed it.
After that I wrote a fix and committed and pushed that as well.

I tend to commit changes like this to help the code-reviewer.

But indeed, regarding actual merging of pull requests this will not easily lead to issues. The only thing I can think of is the following scenario:

Push commit 1. Push commit 2. The build status of both commits is green. Force-push away commit 2. The branch wont be rebuild commit 1 as that commit hash has already been build. Result: commit 1 is green, but actual build will fail.

**Comment by BanzaiMan** [comment]
I understand there are bad sequences of events that lead to this issue, but I don't think there is much we can do here. There is no payload from GitHub we can act on that avoids it.

In the last scenario you describe, you can also force a new commit corresponding to commit 1.

**Comment by giorgiosironi** [comment]
For what it's worth, the way Jenkins does this in the organization folder plugin is by fetching the latest heads of the mainline branch and of the branch of the pull request, merging them manually to get the new commit to test. The side-effect is that the commit sha resulting from the merge does not exist on Github, but this is true also for the commits at which `pull/:pullId/merge` usually points to, as they are rapidly garbage-collected when the head of the branch changes.

**Comment by nlisgo** [comment]
I have experienced the same thing. There is value in pushing up a test-only commit to trigger a fail in CI and then an additional commit to fix the exposed bug.

We are only able to have this if we delay pushing up the second commit until after the build triggered by the first commit starts.

This shows the effect of pushing the second commit too soon (the first build was supposed to fail): https://github.com/elifesciences/elife-website/pull/493

This pull request shows the value of allowing intermediate builds (we delayed pushing the second commit until after the first build started): https://github.com/elifesciences/elife-ingest-xsl/pull/150

**Comment by peterjwest** [comment]
Linking to (closed) duplicate of this for reference: https://github.com/travis-ci/travis-ci/issues/7459

I don't see why you have to use the merge commit generated by Github - just do one locally. Then you can store the two parent commits in the build metadata.

At the very least, you can use the commit sha which is clearly visible at the top of each build (and must be stored in metadata somewhere). The downside of this being that Github delete this commit after a while when it is out of date.

**Comment by peterjwest** [comment]
Thankfully the bot doesn't seem to work, so the issue is still open.

**Comment by jwalton** [comment]
Why doesn't travis just always `git checkout ${TRAVIS_COMMIT}` at the start?  If that commit has been deleted, then the build will fail, but that's fine - this seems like a more desirable outcome than building and passing with the wrong hash.

I'm running into this problem because I'm using build stages, and in the first part of my build I build a docker image and tag and push it using `get rev-parse HEAD`, but then in the second stage I try to retrieve the image using TRAVIS_COMMIT, which *ought* to be the same, but of course because of this issue it isn't.

**Comment by rpkilby** [comment]
*wipes dust off issue*

**Comment by jwalton** [comment]
I tried to fix my build stage problem by running `git rev-parse head` to fetch the currently checked out hash, instead of relying on TRAVIS_COMMIT.  But this doesn't even work:

* First stage creates a docker image called "build-$COMMIT" and pushes it to our docker registry.
* Second stage runs unit tests by fetching "build-$COMMIT"/
* Someone commits something here
* Third stage runs selenium tests and fetches "build-$NEWCOMMIT" which isn't in the docker registry. 

:(

**Comment by jesskie** [comment]
Thank you sir

**Comment by peterjwest** [comment]
Good job stale bot, you finally did it!

**Comment by OliverJAsh** [comment]
> For the mean time, I use the following workaround to prevent erroneous builds and attempt to checkout the correct commit:

Thanks for sharing your workaround. Unfortunately this is not without further problems: the `.travis.yml` file, which may have changed in the commit at `TRAVIS_COMMIT`, is read _before the install step_—so it's possible that the build will be configured incorrectly.

**Comment by peterjwest** [comment]
That's a good point. I think we ended up not using the workaround for other reasons anyway.
Also we switched to Circle CI instead.
