### ISSUE TITLE
[Rust] `cargo build` doesn't return an exit code

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-ci#6338]
We've had a report where a user was saying that a failure in `cargo build` would not fail his Rust build on Travis CI.

Upon further inspection, it looks like `cargo build` is put in the background and it never returns an exit code.

You can see [in the following build log](https://travis-ci.org/BanzaiMan/travis_production_test/builds/145930253#L500) that we don't see a line of the form

```
The command "cargo build --verbose" exited with N.
```

However, we do see this line for `cargo test --verbose`.

Hence, we should investigate why this happens and hopefully fix it.

Thanks!

**Comment by php-coder** [comment]
Is there workaround for this?

**Comment by BanzaiMan** [comment]
I don't think this is a problem with the `cargo` command at all, but rather, how the default `script` is constructed in `travis-build`. Basically, when there are multiple default commands to be run, only the last one affects the build result.

Fortunately, Rust is the only one that is affected by this issue.

Until we fix the build script, you can override `script` section, like so:

```yaml
language: rust
script:
  - cargo build --verbose
  - cargo test --verbose # or, you can combine the two with `&&`
```
