### ISSUE TITLE
Weird crash in some OS X and Linux images

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6341]
We are seeing a crash in Travis CI OS X and Linux images in some cases. This is long before the build and it only started happening. However, we have been building successfully for some time. Here are two [logs]( https://travis-ci.org/conda-forge/staged-recipes/builds/146188981 ) that both experience this issue. The error message is shown below. It seems the error message is the same in both images.

```
/Users/travis/build.sh: line 380: syntax error in conditional expression
/Users/travis/build.sh: line 380: syntax error near `:echo=>'
/Users/travis/build.sh: line 380: `      elif [[ {:assert=>true, :echo=>true, :timing=>true} ]]; then'
```

cc @pelson @ocefpaf

**Comment by BanzaiMan** [comment]
There was a bad deploy of `travis-build`. We've reverted it, and we should be good now.

Sorry for the issue.

**Comment by jakirkham** [comment]
Thanks for the info and quick fix.
