### ISSUE TITLE
No new build requests on git push or manual trigger

### ISSUE THREAD

**Issue by saulshanabrook** [travis-ci/travis-ci#6345]
I have been using Travis CI for [`react-native-webview-crypto`](https://github.com/saulshanabrook/react-native-webview-crypto) happily for a week or two.

Today, I pushed new changes and Travis did not schedule a build. I checked the ["Requests"](https://travis-ci.org/saulshanabrook/react-native-webview-crypto/requests) and it did not pick up anything from Github.

I went to "Settings > Webhooks & Services > Travis CI" on my Github repo and clicked "Test Service". Still nothing.

I went into Travis and disabled this repo, deleted the service on Github, re-added the repo on Travis, and clicked manual trigger and pushed a new commit. Still nothing.

**Comment by saulshanabrook** [comment]
Just processed an old request!

**Comment by saulshanabrook** [comment]
Hm, it seems to not be picking up a new push. When I try to go to `https://travis-ci.org/saulshanabrook/react-native-webview-crypto/settings` it says "There was an error while loading data."

**Comment by BanzaiMan** [comment]
Please keep an eye on http://stspg.io/2xuZ.

**Comment by saulshanabrook** [comment]
Ah ok, didn't see that at first.
