### ISSUE TITLE
i686-elf cross compiler support?

### ISSUE THREAD

**Issue by amar-laksh** [travis-ci/travis-ci#6347]
Inclusion of C cross-compiler anytime soon?

**Comment by BanzaiMan** [comment]
What kind of support are you talking about? If you are to do this on your development machine, how would you achieve it?

**Comment by amar-laksh** [comment]
No I was referring to adding cross-compiler support as a default option on the Travis platform

**Comment by BanzaiMan** [comment]
I understand your question. I am trying to figure out what sort of "support" you are looking for on Travis.
