### ISSUE TITLE
libtool on osx started to fail recently

### ISSUE THREAD

**Issue by zetok** [travis-ci/travis-ci#6352]
https://travis-ci.org/tux3/qTox/jobs/145272353#L192 ← started failing for no good reason, nothing has been changed in repos that would affect this

https://travis-ci.org/tux3/qTox/jobs/144943554#L194 ← one of last working builds

**Comment by unhammer** [comment]
https://travis-ci.org/unhammer/hfst/jobs/147172555 ← I'm also seeing this
