### ISSUE TITLE
Test Matrix with Multiple R Installs

### ISSUE THREAD

**Issue by coatless** [travis-ci/travis-ci#6353]
Trying to enable Multiple OS builds across different versions following advice:

1. [Testing packages with R Travis for OS-X](https://ropensci.org/blog/2016/07/12/travis-osx)
2. [Testing Your Project on Multiple Operating Systems](https://docs.travis-ci.com/user/multi-os/)
3. [R versions](https://docs.travis-ci.com/user/languages/r#R-Versions)

The initial `.travis.yml` file had builds across multiple OS' and R versions via:

```bash
language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8
      before_install:
        - brew install curl
        - brew link --force curl
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: xcode7.3
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
```

However, [this failed](https://travis-ci.org/SMAC-Group/gmwm/builds/147082225) as each OS specified the build seemed to not be expanded outside of the array, e.g. [`R: oldrel,release,devel`](https://travis-ci.org/SMAC-Group/gmwm/jobs/147082229#L369-L376). 

To get this to work, I had to rely upon:

```bash
# Use the R testing scheme
language: r

# Test on multiple versions (note requirement of R > 3.0)
r:
  - oldrel
  - release
  - devel

# Enable package cache
cache: packages

# Disable sudo to ensure container infrasturcture
sudo: false

# To CRAN, warnings **are** errors.
warnings_are_errors: true

# Build on OS
os:
  - linux
  - osx
```

Any chance of fixing the array issue?

@craigcitro and @jimhester

**Comment by BanzaiMan** [comment]
The problem you are describing is an issue with matrix expansion, which is defined in https://github.com/SMAC-Group/gmwm/blob/a87b49d580b0071bccca05995c88c8520e7153da/.travis.yml.

You have

```yaml
r:
  - oldrel
  - release
  - devel
```
which is inherited by each of the jobs you added in `matrix.include`. There is no way to include *3* jobs for  each of the job that you defined in `matrix.include`.

Try defining the `r` value for each of the jobs you define in `matrix.include`.

**Comment by coatless** [comment]
@BanzaiMan

So, that inflates it to be:

Number of R Versions * Number of OS = Total matrix entries?

3 * 5 =15 entries?

**Comment by BanzaiMan** [comment]
I don't know what sort of build matrix you want to create, so I can't advise you on that. However, you might want to look at other repositories, such as https://github.com/pyca/cryptography/blob/master/.travis.yml.

**Comment by coatless** [comment]
@BanzaiMan Just a way to effectively test R versions against two different OS builds.

Given what you mentioned about the placement of `r` yielding inheritance within the matrix build structure, the solution was again to just individually specify.  

e.g. 

3 R versions with 2 different OSes are given by 3*2 = 6 different job slots in the matrix specified as:

```bash
# Test package on multiple platforms
matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
      latex: false
      r: oldrel
    - os: linux
      dist: precise
      sudo: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
      latex: false
      r: release
    - os: linux
      dist: precise
      sudo: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
      latex: false
      r: devel
    - os: linux
      dist: trusty
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
      latex: false
      r: oldrel
    - os: linux
      dist: trusty
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
      latex: false
      r: release
    - os: linux
      dist: trusty
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
      latex: false
      r: devel
```

I was hoping for a slightly neater solution but this works nicely. 

https://travis-ci.org/SMAC-Group/gmwm/builds/147100524

Thanks again!
