### ISSUE TITLE
Docker not found when language is clojure

### ISSUE THREAD

**Issue by keithmantell** [travis-ci/travis-ci#6354]
```
sudo: required

language: clojure

services:
  - docker

before_install:
  - docker build -t my-clojure-app .
```

gives:

```
$ docker build -t my-clojure-app .

/home/travis/build.sh: line 41: docker: command not found

The command "docker build -t my-clojure-app ." failed and exited with 127 during .
```

**Comment by BanzaiMan** [comment]
Do you have a build log that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
This is probably a different manifestation of https://github.com/travis-ci/travis-ci/issues/6334. We'll take a look.

**Comment by keithmantell** [comment]
Apologies - I realised overnight that I had raised this against github.com and not the github enterprise version that I should have done. 

I have tried the same Dockerfile etc. on github.com and it works
