### ISSUE TITLE
Build stuck at "Created"

### ISSUE THREAD

**Issue by jthomas** [travis-ci/travis-ci#6355]
I've set up a new build for the __ci__ branch on the following repo ([node-red/node-red-docker](https://github.com/node-red/node-red-docker)). Triggering a build when a new commit is pushed, the build is stuck in the "created" phase. I've repeated this process to try again with the same results.

<img width="964" alt="screen shot 2016-07-25 at 17 49 13" src="https://cloud.githubusercontent.com/assets/2322/17109512/250798fc-5290-11e6-8a45-c8f2d845d8e0.png">

https://travis-ci.org/node-red/node-red-docker/branches

**Comment by BanzaiMan** [comment]
Most likely due to http://stspg.io/3BCo. Please follow that page for updates.
