### ISSUE TITLE
Getting "bad decrypt" after using `travis encrypt-file` locally

### ISSUE THREAD

**Issue by matthewadams** [travis-ci/travis-ci#6358]
All builds since https://travis-ci.org/SciSpike/yaktor-dsl-xtext/builds/147367298 have failed on me with a 'bad decrypt' message (ignore https://travis-ci.org/SciSpike/yaktor-dsl-xtext/builds/147371737 -- that one was my bad).

The command I issued on my local machine to encrypt a file was:
`travis encrypt signingkey.asc`
which produced `signingkey.asc.enc` and the `openssl` command.

The line to decrypt is at https://github.com/SciSpike/yaktor-dsl-xtext/blob/master/cli/travis-before-deploy.sh#L6:
```
openssl aes-256-cbc -K "$encrypted_a314b1bbacc4_key" -iv "$encrypted_a314b1bbacc4_iv" -in "$CLI_DIR/signingkey.asc.enc" -out "$CLI_DIR/signingkey.asc" -d
```
where `CLI_DIR` is `./cli` -- `$PWD` is the root of the repository.

The error in the log is at https://travis-ci.org/SciSpike/yaktor-dsl-xtext/builds/147380540#L4081:
```
$ docker exec -it bob cli/travis-before-deploy.sh
bad decrypt
140305188325008:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:544:
```

I don't know what else to try...

**Comment by BanzaiMan** [comment]
Is your local machine Windows?

**Comment by matthewadams** [comment]
No, Mac OS X El Capitan.

**Comment by BanzaiMan** [comment]
Did you run `travis encrypt-file` a second time?

**Comment by matthewadams** [comment]
@BanzaiMan, I've run it several times; no worky.

I even tried doing the `openssl` commands myself:  see commit
https://github.com/SciSpike/yaktor-dsl-xtext/commit/a2e49f7d164b8010f31a37950a18ce9ae580edb9
and build output line
https://travis-ci.org/SciSpike/yaktor-dsl-xtext/builds/147522920#L4074
which is the result of running script
https://github.com/SciSpike/yaktor-dsl-xtext/blob/master/cli/travis-before-deploy.sh.

**Comment by matthewadams** [comment]
@BanzaiMan, FWIW, I also tested those `openssl` commands by encrypting on El Capitan then decrypting on Ubuntu.  Everything worky fine in that test.

**Comment by BanzaiMan** [comment]
After you've encrypted the file the last time, did you add the encrypted file?

**Comment by matthewadams** [comment]
@BanzaiMan, yes, of course:  https://github.com/SciSpike/yaktor-dsl-xtext/commit/a2e49f7d164b8010f31a37950a18ce9ae580edb9#diff-de886083ec0d236f804d31cacf58a644

**Comment by BanzaiMan** [comment]
https://travis-ci.org/SciSpike/yaktor-dsl-xtext/builds/147522920#L4077 Your `openssl` invocation seems wrong, though. https://github.com/SciSpike/yaktor-dsl-xtext/commit/a2e49f7d164b8010f31a37950a18ce9ae580edb9#diff-32a28bb38c2aedf5e59a56c39e5daa8dR6

**Comment by matthewadams** [comment]
What exactly is wrong about it?  *I'm* controlling the encryption myself instead of using `travis encrypt-file` because it's broken for me.

I'm encrypting with the command
`openssl enc -aes-256-cbc -e -in "$SIGNING_KEY_FILE" -out "$OUTFILE" -base64 -K $TRAVIS_GPG_KEY -iv $TRAVIS_GPG_IV`
(at https://github.com/SciSpike/yaktor-dsl-xtext/blob/master/cli/travis-encrypt-signing-key.sh#L32).  `TRAVIS_GPG_KEY` & `TRAVIS_GPG_IV` are randomly generated.

Then I use `travis encrypt` to store the encrypted key & iv values in my `.travis.yml`.

During a build, I decrypt with the command
`openssl enc -aes-256-cbc -d -in "$CLI_DIR/signingkey.asc.x" -out "$CLI_DIR/signingkey.asc" -base64 -K $TRAVIS_GPG_KEY -iv $TRAVIS_GPG_IV`
at (https://github.com/SciSpike/yaktor-dsl-xtext/blob/master/cli/travis-before-deploy.sh#L6).

Again, I tested this manually using El Capitan to encrypt & Ubuntu to decrypt & everything worked normally.

Perhaps you could get me more information about the possible causes of the `iv undefined` message at https://travis-ci.org/SciSpike/yaktor-dsl-xtext/builds/147522920#L4074, we'd find the solution.

**Comment by BanzaiMan** [comment]
You can use `openssl enc` to both encrypt and decrypt the file? If you are not using our encryption method, though, I can't tell what might go wrong.

It was working 4 days ago, and no code change that may affect this part of the build has been deployed.

We can give you access to a debug VM, if you wish. Please email support@travis-ci.com.

**Comment by matthewadams** [comment]
> You can use openssl enc to both encrypt and decrypt the file?

Yes.  the `-e` & `-d` flags control whether you encrypt or decrypt.  The default is to encrypt.  RTFM at https://www.openssl.org/docs/manmaster/apps/enc.html

> If you are not using our encryption method, though, I can't tell what might go wrong.

I'm using `openssl`'s encryption & decryption methods (as is `travis encrypt-file`).  Again, I've tested encryption on Mac & decryption on Linux and got worky worky, happy happy, rainbows, butterflies & blue Twinkies.  I'm storing the encryption key & iv in environment variables, secured by command `travis encrypt XXX=YYY`, whose output I used to update `.travis.yml`.  If, during the Travis build, I could get back the secure environment variables `TRAVIS_GPG_KEY` & `TRAVIS_GPG_IV`, I think I'd be golden.

The `iv undefined` error seems to happen to others using Travis CI as well:
* https://github.com/pockethub/PocketHub/issues/884
* https://github.com/openframeworks/projectGenerator/issues/101

For me, `travis version` yields
```
$ travis version
1.8.2
```
so I'm assuming that the values are being encrypted & placed into my `.travis.yml` ok.

What are the possible reasons that Travis would *not* decrypt secure environment variables?  The pushes that are seeing these build errors are *not* pull requests; they're plain, ol' pushes to `master`.

**Comment by BanzaiMan** [comment]
Those values seem to be decrypted correctly. See https://travis-ci.org/SciSpike/yaktor-dsl-xtext/builds/147522920#L166-L167. I don't know what values are there, but the decryption is working for your builds. You can verify this by peeking into it (echo *some* parts of it, say: `echo $TRAVIS_GPG_KEY | cut -c 1-3`), or you can see this interactively on a debug VM.

**Comment by matthewadams** [comment]
I'm pretty sure I've identified the problem.  I'd forgotten that I'm using a Docker container to build my project, and I forgot to pass those environment variables into the container when creating it.

Silly me, Trix are for containers.  I'll reopen if I'm not stupid.  Building now...

**Comment by matthewadams** [comment]
Fixed:  https://travis-ci.org/SciSpike/yaktor-dsl-xtext#L4093
