### ISSUE TITLE
Compilation error on lombok generated methods

### ISSUE THREAD

**Issue by ekougs** [travis-ci/travis-ci#6361]
I am trying to add CI to my current Spring boot project.
The maven build works perfectly fine locally.
I launched the build on Travis but it always fails on compilation errors on methods generated by Lombok.
Is there something that I am missing ?
I have been stuck on this for more than a week.
And I only got a workaround as a solution on stackoverflow http://stackoverflow.com/questions/38579489/travis-compilation-error-on-lombok-generated-methods
I am setting it up on this branch https://github.com/madicorp/smartinvestplus-back/tree/travis
Travis job: https://travis-ci.org/madicorp/smartinvestplus-back
My travis config
```
language: java
jdk:
  - oraclejdk8
env:
  - MVN_VERSION=3.3.9
cache:
    directories:
        - $HOME/.m2
install: eval mvn clean install -DskipTests=true -B -V
script: eval mvn clean install
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
```

I get these types of compilation error for all the methods generated by lombok in my POJOs
```
symbol:   method isGenerated()
location: variable closeRate of type  net.madicorp.smartinvestplus.stockexchange.domain.CloseRate
[ERROR] diagnostic: /home/travis/build/madicorp/smartinvestplus-back/src/main/java/net/madicorp/smartinvestplus/stockexchange/service/CloseRateDivisionAdjuster.java:28: error: cannot find symbol
    adjustedCloseRate.setRate(closeRate.getRate());


symbol:   method getRate()
location: variable closeRate of type     net.madicorp.smartinvestplus.stockexchange.domain.CloseRate
[ERROR] diagnostic: /home/travis/build/madicorp/smartinvestplus-back/src/main/java/net/madicorp/smartinvestplus/stockexchange/service/CloseRateDivisionAdjuster.java:32: error: invalid method reference
             .map(Division::getRate)
```

**Comment by BanzaiMan** [comment]
Does this not happen locally? If I clone https://github.com/madicorp/smartinvestplus-back and run the maven command on a fresh machine, it fails similarly.

**Comment by ekougs** [comment]
No it never failed locally. Do you launch it via docker or vagrant ? If so, can you give me the base image you use so that I can try to reproduce it. Meanwhile, I will first try to clear my local maven repo and launch a build because it may contain artifacts that are not described in my pom and then make it on a ubuntu VM.

**Comment by ekougs** [comment]
The build did not fail on my local environement when I cleared my local maven repository but on a fresh ubuntu VM, I got the same error. Thx for the tip :), I will investigate further to understand why I get such differences between local build and a build in a VM.

**Comment by BanzaiMan** [comment]
All right. I am closing this, then.

**Comment by ekougs** [comment]
The whole problem came from my main spring boot class. Its filename case did not match the class name. On MacOS it does not seem to matter but it does on Linux. All the other compilation problems were side-effects of this one and vanished as soon as I committed the filename case update. In the end, it had nothing to do with lombok. Thx @BanzaiMan for the idea.
