### ISSUE TITLE
Using secure api_key when configuring Heroku deployment fails.

### ISSUE THREAD

**Issue by aconfee** [travis-ci/travis-ci#6362]
Hello!

I've just been configuring this app: https://github.com/aconfee/MEANTemplateV2 to Travis CI. 

The Problem:
Deploying to Heroku fails with the error: 
  Fetching: dpl-1.8.17.gem (100%)
  Successfully installed dpl-1.8.17
  invalid option "--api_key="
  failed to deploy

This only occurs when I try to use a secure api_key. Using my exact api_key provided by: heroku auth:token works fine. 

What I've tried:
To create my secure API key, I installed the Travic CI CLI according to your documentation: gem install travis -v 1.8.2 --no-rdoc --no-ri. Once this successfully installed, I encrypted and added my api_key using: travis encrypt $(heroku auth:token) --add deploy.api_key according to your documentation.

I did remember to use 'sudo' (dummy check). I also tried manually copy/pasting the api key as well as adding quotes. At this point I can't figure out what I could possibly be doing wrong after following the documentation explicitly. 

Any help is appreciated, thanks!

**Comment by BanzaiMan** [comment]
Clearly your encryption went wrong. I've seen this happen when somehow CLI thinks your repo is what it is not.

Could you try:

```
travis-encrypt -r aconfee/MEANTemplateV2 --org
```

and try manually providing the key (followed by the return and ctrl-d)?

**Comment by aconfee** [comment]
Hey,

Thanks for your quick response. Did you mean 'travis-encrypt' or 'travis encrypt'? I can't find the hyphenated version anywhere. Without the hyphen, I successfully got an api key, but it still didn't work :/

**Comment by BanzaiMan** [comment]
Sorry, no hyphen. I updated the comment above. What value did you encrypt? Does it contain any space at the beginning? (In other words, maybe we are trying to invoke the deployment utility with `--api-key= REST`.)

**Comment by aconfee** [comment]
Sorry, I don't think I understand. I didn't add anything to the command you provided, I entered it exactly as is.  Was I supposed to add a value to encrypt? 

What might have spaces at the beginning? The key in my .yml file? Could you provide more context here?

Thanks!

**Comment by aconfee** [comment]
I just found this documentation which might have been something I'm missing https://docs.travis-ci.com/user/encryption-keys/. Could you elaborate what SOMEVAR and secretvalue are? I imagine secretvalue is my heroku authentication token (in this case), but I don't know what SOMEVAR would be. I also don't understand why I'd be initializing SOMEVAR in order to encrypt secretvalue... or I'm I understanding this completely wrong?

**Comment by BanzaiMan** [comment]
You should get prompted after you type

```sh-session
travis encrypt -r aconfee/MEANTemplateV2 --org
```

You should get prompted:

```
Reading from stdin, press Ctrl+D when done
```

**Comment by BanzaiMan** [comment]
It is expected that you type your API key, followed by the return, then Ctrl+D.

**Comment by aconfee** [comment]
Thanks! That did it, I had no idea I was supposed to type the key I wanted to encrypt first. Could 'Reading from stdin...' be changed to 'Please enter the key you wish to encrypt...'? I didn't see any mention in any of the documentation that indicated I should type the key there (and for some reason, I assumed that it would know how to encrypt based on my repo info). Additionally, much of the documentation aims to accomplish the same thing in different ways; in the cases I provided, the key is added in the initial command.

**Comment by joozybrain** [comment]
Hi there,

I'm facing the same problem as the original poster. Running `travis encrypt $(heroku auth:token) --add deploy.api_key` leads to a failure on TravisCI with the following message. 
```
2.55s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Fetching: dpl-1.9.5.gem (100%)
Successfully installed dpl-1.9.5
1 gem installed
 ▸    not logged in
invalid option "--api_key="
failed to deploy
```

However, I'm able to get it to work by doing the following steps manually:
1) `heroku auth:token`
2) `travis encrypt <output of heroku auth:token>`
3) Manually pasting the output in `.travis.yml`

Could you share why it fails when I run `travis encrypt $(heroku auth:token)` with the `--add deploy.api_key` option?

**Comment by rutgerhofste** [comment]
The way the user should interact with travis encrypt --add deploy.password is not clear at all.
