### ISSUE TITLE
Can we have Xcode 8b3?

### ISSUE THREAD

**Issue by sgoodwin** [travis-ci/travis-ci#6365]
Hi folks,

Currently my builds are failing because of a compiler error that occurs because the Xcode8 image is using beta 3 and not beta 2. Can this be updated?

**Comment by stuartbreckenridge** [comment]
Would agree with @sgoodwin, this would be useful!

**Comment by sgoodwin** [comment]
Correction, beta 4 is out now.

**Comment by stuartbreckenridge** [comment]
See issue #6399

On 2 Aug 2016, at 4:55 PM, Samuel Goodwin <notifications@github.com<mailto:notifications@github.com>> wrote:


Correction, beta 4 is out now.

-

**Comment by BanzaiMan** [comment]
Sorry for the delay. I'm closing this in favor of #6399.
