### ISSUE TITLE
Travis CI throws an error and shows blank screen with latest Chrome Canary

### ISSUE THREAD

**Issue by blimmer** [travis-ci/travis-ci#6366]
![](https://i.imgur.com/F6TuefF.png)

![](https://i.imgur.com/WOQZyKl.png)

![](https://i.imgur.com/TNmKAO2.png)

At first I thought this could be a problem with Ember 2.7, but ember twiddle @2.7 still works

**Comment by backspace** [comment]
This isn’t Travis-specific, as you can see [here](https://github.com/travis-ci/travis-ci/issues/6366). Perhaps if you provoke Twiddle to generate an Ember error it would cause the same problem? Or maybe it relates to production builds? We are still investigating.

**Comment by backspace** [comment]
Hey, this is fixed now in Chrome Canary. I updated this morning and it’s working again. Thanks for the report! You can see more information in the [Ember thread](https://github.com/emberjs/ember.js/issues/13919).

**Comment by blimmer** [comment]
🎉 thanks for the follow up!
