### ISSUE TITLE
Invalid `dist` value is silently accepted and appears in the build log

### ISSUE THREAD

**Issue by alxempirical** [travis-ci/travis-ci#6367]
According to #5821, `dist: xenial` is improperly configured.  If that's the case, it's surprising that travis doesn't even provide a warning when `dist: xenial` is used.

Travis would have been dead to me today if I wasn't in an environment which already uses it, because I couldn't figure out why `services: docker` wasn't working for me.

**Comment by jayvdb** [comment]
@alxempirical, what does `dist: xenial` do?  Does it create a xenial image, or is it a precise or trusty image?
If it is creating the wrong type of image, then a warning or an error seems reasonable.

**Comment by alxempirical** [comment]
As far as I know it's a xenial environment, but the key thing for me today is that the [documented](https://docs.travis-ci.com/user/docker/) `services: docker` functionality [doesn't work when you set `dist:xenial`](https://travis-ci.org/alxempirical/travis-test/builds/147914899), [but does if you leave it out](https://travis-ci.org/alxempirical/travis-test/builds/147812996).

**Comment by BanzaiMan** [comment]
`xenial` is an unrecognized value in our routing app, so the jobs will be routed to the default image for the infrastructure. At this time, it is Precise.

**Comment by alxempirical** [comment]
It's unfortunate that the build output doesn't prominently alert users that that's what happens, since it's surprising behavior and xenial is now the official ubuntu release so it's a natural choice for people who don't know that detail of your infrastructure.

**Comment by BanzaiMan** [comment]
This is a variation of https://github.com/travis-ci/travis-ci/issues/6074.
