### ISSUE TITLE
iOS Unit Tests Fail in Travis, Pass Locally with same command

### ISSUE THREAD

**Issue by janderson-primary** [travis-ci/travis-ci#6370]
I'd like to know more about exactly what type of environment Travis sets up to perform iOS builds, and tests, since I've ran into a very frustrating problem:

Unit tests that pass locally, are consistently failing in Travis.  Not ALL tests are failing, just a handful of specific tests!

One group of failed tests, is testing date formatting, for all timezones returned by [NSLocale availableLocaleIdentifiers].  Is it possible this API performs differently based on your environment setup?  

Another group of failed tests is failing on some basic UI assertions.  I am testing that a UIViewController displays expected label values.  Other UI assertions are passing, but these fail.

Locally, everything passes....

**Comment by BanzaiMan** [comment]
Sorry, but there is very little information for us to advise. Please email support@travis-ci.com with the build log URL that shows the problem you are having, and we will set you up with access to a debug VM.

In the meantime, I am going to close this.
