### ISSUE TITLE
Does the Imagemagick library come installed with osx and linux?

### ISSUE THREAD

**Issue by amilajack** [travis-ci/travis-ci#6376]
Does the Imagemagick library come installed with osx and linux? I'm getting the following errors when running code that depends on it.
```
Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "./tmp/CardList.png" this most likely means the gm/convert binaries can't be found
```

**Comment by BanzaiMan** [comment]
I don't think they are pre-installed on OS X images. You can use `brew install imagemagick` to get it.

It should be available on Linux VMs. If not, you can use `apt` addon (or `sudo apt-get install imagemagick` as appropriate) to install it.

**Comment by amilajack** [comment]
Thanks!

**Comment by jfoclpf** [comment]
any tips on how to do it on windows?
