### ISSUE TITLE
JWT addon

### ISSUE THREAD

**Issue by halkeye** [travis-ci/travis-ci#6383]
Looking at https://travis-ci.org/saucelabs-sample-test-frameworks/Java-TestNG-Selenium/jobs/148427092 and the default maven job
SAUCE_ACCESS_KEY is not available until after mvn install is run

**Comment by halkeye** [comment]
I've updated the jwt branch for https://github.com/travis-ci/travis-build/pull/356

**Comment by halkeye** [comment]
@BanzaiMan 

`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUcmF2aXMgQ0ksIEdtYkgiLCJzbHVnIjoic2F1Y2VsYWJzLXNhbXBsZS10ZXN0LWZyYW1ld29ya3MvSmF2YS1UZXN0TkctU2VsZW5pdW0iLCJwdWxsLXJlcXVlc3QiOiIiLCJleHAiOjE0NzAwNjkyODUsImlhdCI6MTQ3MDA2Mzg4NX0.ZaiYGyCni-BKQFtmi-Z4QRBuHXurmd6jYXBzGd1rK38eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ`

has empty pull-request field even though its setup as a pull request (https://github.com/saucelabs-sample-test-frameworks/Java-TestNG-Selenium/pull/14)

is data.pull_request no longer valid?

**Comment by halkeye** [comment]
Interesting

You are right, the one in the logs works fine. I wonder where I got mine.

**Comment by halkeye** [comment]
No wait, 

https://travis-ci.org/saucelabs-sample-test-frameworks/Java-TestNG-Selenium/jobs/148904222

has `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUcmF2aXMgQ0ksIEdtYkgiLCJzbHVnIjoic2F1Y2VsYWJzLXNhbXBsZS10ZXN0LWZyYW1ld29ya3MvSmF2YS1UZXN0TkctU2VsZW5pdW0iLCJwdWxsLXJlcXVlc3QiOiIiLCJleHAiOjE0NzAwNjkyODQsImlhdCI6MTQ3MDA2Mzg4NH0.wPDSYlMe8PnXR7x829EcklY5dzMfgVY6pcCCymyD1Po`

which does not have it.

![image](https://cloud.githubusercontent.com/assets/110087/17306376/b22a5162-57e4-11e6-8df2-ca121cf22ac7.png)

**Comment by halkeye** [comment]
@BanzaiMan pull-request is purely a meta field, doesn't break functionality, but it is curious why its inconsistent

**Comment by BanzaiMan** [comment]
@halkeye https://travis-ci.org/saucelabs-sample-test-frameworks/Java-TestNG-Selenium/jobs/148904222 is a push build, so it has `"pull-request": ""`. Is that not the desired value?

**Comment by halkeye** [comment]
@BanzaiMan oh sorry, I just realized I pushed to the wrong remote, thats why it was breaking

We are all good

**Comment by BanzaiMan** [comment]
@halkeye Good to hear!

**Comment by BanzaiMan** [comment]
It just occurred to me. Does it make sense to version the JWT payload?

**Comment by halkeye** [comment]
I don't see any immediate need. If we ever have to add breaking changes it might be useful to add then.

**Comment by halkeye** [comment]
@BanzaiMan all my tests show things are working.

I'm going to close this issue for now.

https://github.com/travis-ci/docs-travis-ci-com/pull/674 is the only out-standing peice now.

**Comment by BanzaiMan** [comment]
@halkeye Sweet!
