### ISSUE TITLE
Do not set GOROOT

### ISSUE THREAD

**Issue by starius** [travis-ci/travis-ci#6388]
I install Go manually in my Travis built script, but Travis has its own Go installed and it sets GOROOT. If I run my Go, it is confused by GOROOT variable pointing to system Go installation and it won't work because of missing libraries. I have to `unset GOROOT` to make it working.

On the other hand, `GOROOT` [is not needed](http://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really) when compiling or using Go 1.0 or later. Could you refrain from setting it, please?

**Comment by AlekSi** [comment]
See https://github.com/golang/go/issues/21313 for a recent related problem.

**Comment by starius** [comment]
It still sets GOROOT=/home/travis/.gimme/versions/go1.7.4.linux.amd64

**Comment by starius** [comment]
The issue is still there.

**Comment by BanzaiMan** [comment]
Sorry about the long delay. `$GOROOT` is set by https://github.com/travis-ci/gimme. Do you mind opening an issue there?
