### ISSUE TITLE
How to deploy like "push to a dist repo"

### ISSUE THREAD

**Issue by cyrilchapon** [travis-ci/travis-ci#6392]
I've read much about deploy and the "releases" part, but I can't figure out how to make a simple push to a "dist" repo.

As for now, I'm able to :
- Detect any push
- Build my project "on push"
- If this is a tag, "Deploy" it on the same repo (wrap a tag with a release, and add some files)

My build process creates both a "dist" folder and a "dist.zip". I'd like to push to another repository this dist folder. But the dist folder is naturally not commited to my source repository.

I might be missing something but this seems a pretty classical workflow to me :
- I push a tag
- The CI system detect this is a tag, it makes a new "release"
- It deploys the release to a distribution repository

(example : I think Jquery has this workflow working : [sources](https://github.com/jquery/jquery), [distribution](https://github.com/jquery/jquery-dist)

**Comment by BanzaiMan** [comment]
The build on Travis should:

1. Configure git (at the least, you'd need `user.name` and `user.email`).
1. Set up git authentication for the target repo. On GitHub, you can use the auth token with limited scope. Be sure to encrypt this authentication token: https://docs.travis-ci.com/user/encryption-keys; https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables.
1. Clone the target repository
1. Create a new commit
1. Push the new commit

**Comment by cyrilchapon** [comment]
Hey @BanzaiMan,

I succeeded on it but it took me a day long (literally).

For the record I did exactly what you suggested, but with the following :
- Creating a "deploy key" instead of auth token (seemed cleaner to me)
- So I encrypted the file instead of ENV
- Added some conditional to handle tag pushing (and force pushing)

That was incredibly hard.

**Comment by BanzaiMan** [comment]
Thanks for the update.
