### ISSUE TITLE
R development version used by default under Mac OSX

### ISSUE THREAD

**Issue by paleo13** [travis-ci/travis-ci#6394]
Travis uses the development R version for testing packages in the Mac OSX environment by default.

This issue occurs due to the fact that the build script assumes that the latest version of R is listed as the development version of R at this repository (https://r.research.att.com/mavericks/R-devel/). Whilst this may have been true in the past, this is no longer the case as the latest version of R is 3.3.1 and the repository lists 3.4.0 as the development version. 

This issue is significant as the development version may be unstable. Additionally, many packages (eg. mvtnorm, rgdal, rgeos) are particularly difficult to build from source and so it is much easier to install them as a binary package. However, if R version 3.4.0 is installed, then Travis is forced to attempt and fail at building these packages from source.

See here for the build log demonstrating that Travis is using the development R version in Mac OSX

https://s3.amazonaws.com/archive.travis-ci.org/jobs/148211274/log.txt

@jimhester @craigcitro @hadley

**Comment by jimhester** [comment]
Duplicated of https://github.com/travis-ci/travis-ci/issues/6390
