### ISSUE TITLE
Cached .m2 folder frequently contains corrupted files

### ISSUE THREAD

**Issue by mxm** [travis-ci/travis-ci#6396]
Hi Travis team!

We're huge fans of Travis at [Apache Flink](/apache/flink). Most of the time, Travis works just great. However, every few weeks we're seeing an issue with the .m2 folder caching. Files in the cache have a tendency to get corrupted and [the cache has to be frequently cleared](https://issues.apache.org/jira/browse/INFRA-11773) to let our builds work again.  

Is there anything we can do to avoid to corrupt the .m2 folder? Could there be an issue with the caching?

Here are some examples of build failures that are resolved after clearing the cache:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.1:shade (shade-hadoop) on project flink-shaded-hadoop2: Error creating shaded jar: error in opening zip file /home/travis/.m2/repository/org/apache/hadoop/hadoop-hdfs/2.6.3/hadoop-hdfs-2.6.3.jar -> [Help 1]
```

https://s3.amazonaws.com/archive.travis-ci.org/jobs/147969077/log.txt

```
[ERROR] Failed to execute goal org.scalastyle:scalastyle-maven-plugin:0.5.0:check (default) on project flink-runtime_2.10: Execution default of goal org.scalastyle:scalastyle-maven-plugin:0.5.0:check failed: A required class was missing while executing org.scalastyle:scalastyle-maven-plugin:0.5.0:check: scala/Product
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.scalastyle:scalastyle-maven-plugin:0.5.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/travis/.m2/repository/org/scalastyle/scalastyle-maven-plugin/0.5.0/scalastyle-maven-plugin-0.5.0.jar
[ERROR] urls[1] = file:/home/travis/.m2/repository/org/scalastyle/scalastyle_2.10/0.5.0/scalastyle_2.10-0.5.0.jar
[ERROR] urls[2] = file:/home/travis/.m2/repository/org/scalariform/scalariform_2.10/0.1.4/scalariform_2.10-0.1.4.jar
[ERROR] urls[3] = file:/home/travis/.m2/repository/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar
[ERROR] urls[4] = file:/home/travis/.m2/repository/com/typesafe/config/1.2.0/config-1.2.0.jar
[ERROR] urls[5] = file:/home/travis/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.4/plexus-component-annotations-1.5.4.jar
[ERROR] urls[6] = file:/home/travis/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[7] = file:/home/travis/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[8] = file:/home/travis/.m2/repository/org/codehaus/plexus/plexus-resources/1.0-alpha-7/plexus-resources-1.0-alpha-7.jar
[ERROR] urls[9] = file:/home/travis/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.5/plexus-utils-1.5.5.jar
[ERROR] urls[10] = file:/home/travis/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] Number of foreign imports: 1
```

https://s3.amazonaws.com/archive.travis-ci.org/jobs/148348444/log.txt

```
Error:
[INFO] /home/travis/build/apache/flink/flink-libraries/flink-ml/src/main/scala:-1: info: compiling
[INFO] Compiling 43 source files to /home/travis/build/apache/flink/flink-libraries/flink-ml/target/classes at 1460421450188
[ERROR] error: error while loading <root>, error in opening zip file
[ERROR] error: scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
[ERROR] at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
[ERROR] at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
[INFO] at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
[INFO] at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
[INFO] at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
[INFO] at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:172)
[INFO] at scala.reflect.internal.Mirrors$RootsBase.getRequiredPackage(Mirrors.scala:175)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage$lzycompute(Definitions.scala:183)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage(Definitions.scala:183)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass$lzycompute(Definitions.scala:184)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass(Definitions.scala:184)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr$lzycompute(Definitions.scala:1024)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr(Definitions.scala:1023)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1153)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
[INFO] at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
[INFO] at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
[INFO] at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
[INFO] at scala.tools.nsc.Main$.doCompile(Main.scala:79)
[INFO] at scala.tools.nsc.Driver.process(Driver.scala:54)
[INFO] at scala.tools.nsc.Driver.main(Driver.scala:67)
[INFO] at scala.tools.nsc.Main.main(Main.scala)
[INFO] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[INFO] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] at java.lang.reflect.Method.invoke(Method.java:606)
[INFO] at org_scala_tools_maven_executions.MainHelper.runMain(MainHelper.java:161)
[INFO] at org_scala_tools_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
```

**Comment by BanzaiMan** [comment]
We do not control what gets stored in `~/.m2`. If maven is storing things that you don't want, you can remove them in the [`before_cache`](https://docs.travis-ci.com/user/caching/#before_cache-phase) phase. Looking at the logs, updated files are SNAPSHOT-related, which I almost _expect_ to change often.

**Comment by mxm** [comment]
Thanks! I didn't know about the `before_cache` phase. However, clearing the cache for every build renders it useless. 

Where did you find snapshot related dependencies in the cache? The files in error are not snapshot versions but stable versions. We don't have any dependencies on snapshots versions. Many people experience this issue, I think closing here would be too early.

**Comment by BanzaiMan** [comment]
I did not say you should remove the cache. A main use case of that phase is to remove superfluous files in the cached directories that you expect to change often.

In the logs, you will notice:

```
change detected (content changed, file is created, or file is deleted):
/home/travis/.m2/repository/org/apache/flink/flink-annotations/1.1-SNAPSHOT/flink-annotations-1.1-SNAPSHOT.jar
/home/travis/.m2/repository/org/apache/flink/flink-annotations/1.1-SNAPSHOT/maven-metadata-local.xml
/home/travis/.m2/repository/org/apache/flink/flink-annotations/1.1-SNAPSHOT/_remote.repositories
/home/travis/.m2/repository/org/apache/flink/flink-annotations/maven-metadata-local.xml
/home/travis/.m2/repository/org/apache/flink/flink-parent/1.1-SNAPSHOT/maven-metadata-local.xml
/home/travis/.m2/repository/org/apache/flink/flink-parent/1.1-SNAPSHOT/_remote.repositories
/home/travis/.m2/repository/org/apache/flink/flink-parent/maven-metadata-local.xml
/home/travis/.m2/repository/org/apache/flink/flink-shaded-hadoop/1.1-SNAPSHOT/maven-metadata-local.xml
/home/travis/.m2/repository/org/apache/flink/flink-shaded-hadoop/1.1-SNAPSHOT/_remote.repositories
/home/travis/.m2/repository/org/apache/flink/flink-shaded-hadoop/maven-metadata-local.xml
/home/travis/.m2/repository/org/apache/fl
```

As I mentioned earlier, we do not control what is stored in the directory you specify. It is up to you to decide what the cache should look like.

**Comment by mxm** [comment]
These XML files have nothing to do with the errors we're getting. We have problems with jar files that get corrupted. The list is truncated, is there a away to display the entire list? How does the cache get changed? Will it be updated atomically?

**Comment by BanzaiMan** [comment]
If you suspect that the cache is corrupt, could you try clearing the cache, or disabling the cache to see if the build succeeds?

**Comment by mxm** [comment]
Yes, the builds eventually succeed after clearing the caches. Also, locally they run just fine.

The problem about clearing the caches is the following:
>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (default) on project flink-storm_2.10: Error resolving project artifact: Failure to transfer compojure:compojure:pom:1.1.3 from https://repository.apache.org/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-apache has elapsed or updates are forced. Original error: Could not transfer artifact compojure:compojure:pom:1.1.3 from/to sonatype-apache (https://repository.apache.org/releases/): Connect to repository.apache.org:443 [repository.apache.org/207.244.88.143] failed: Connection timed out for project compojure:compojure:jar:1.1.3 -> [Help 1]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/148880730/log.txt

The connection times out. Perhaps the builds cause pressure on the Apache server.

So if the cache seems to get corrupted what could be the cause for that? Is it caused by Maven or could it be an infrastructure problem?

**Comment by BanzaiMan** [comment]
So you are getting a connection timeout to repository.apache.org? And maven doesn't attempt to connect again after the timeout?

**Comment by buckett** [comment]
We're also seeing problems with our builds caused by failed connections to repository.apache.org

https://travis-ci.org/sakaiproject/sakai/builds/149149233

although I haven't seen any evidence of the original issue of corrupt artifacts in ~/.m2/repository/ which we also cache between builds.

**Comment by StephanEwen** [comment]
@BanzaiMan An update to @mxm issue (connection time out) - that is partially due to some strange setup of maven mirrors. We managed to fix that by adding a better repository as source for the dependencies.

The issue of corrupted jar files persists, though, and happens quite frequently. I am wondering if this is simply an artifact of the shared cache directory, being used across multiple concurrent builds. Do all of the builds share the same physical directory? Do they affect each other with deletes/writes/overwrites?

**Comment by BanzaiMan** [comment]
@StephanEwen It is possible that multiple jobs within a build matrix end up sharing a cache. This is documented here: https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices

> If these characteristics are shared by more than one job in a build matrix, they will share the same URL on the network. This could corrupt the cache, or the cache may contain files that are not usable in all jobs using it. In this case, we advise you to add a defining public environment variable name; e.g.,
> 
>     CACHE_NAME=JOB1
> to `.travis.yml`.

**Comment by StephanEwen** [comment]
Thanks, that is a great pointer. I read the "how caching works" section and if you simply tar up the ".m2" directory, that should not introduce a corrupt jar files.

So I am wondering now, in what way concurrent build jobs for the same build matrix entry can interfere with each other
I am wondering, because we only see the JAR file corruptions on the big apache account (many concurrent builds), not for our private accounts.

**Comment by BanzaiMan** [comment]
In addition to the name collisions explained above, if multiple jobs (across multiple builds) end up uploading to the same URL, that can corrupt the cache.

**Comment by StephanEwen** [comment]
Are there any tricks to prevent concurrent cache access? Or should we best try to disable caching?

**Comment by buckett** [comment]
@BanzaiMan If you have multiple jobs uploading to the same URL doesn't this lead to the whole cache file becoming corrupt (and so thrown away?) rather than a few files within the cache becoming corrupt?

**Comment by BanzaiMan** [comment]
@buckett I don't think we can predict what is going to happen.

**Comment by BanzaiMan** [comment]
@StephanEwen I don't think there is, technically speaking. There is pros and cons of using the cache. It is up to you to decide whether you want to use it. In my opinion, the general benefit (faster builds) far outweigh occasional problems (corrupt caches).

**Comment by buckett** [comment]
If the uploading of a cache file isn't atomic and corruption can occur would it be possible to detect the corruption through a checksum and throw away a cache when you know it's gone bad?

**Comment by BanzaiMan** [comment]
@buckett That is a reasonable workaround to consider for the future enhancement.

**Comment by BanzaiMan** [comment]
We use md5 checksums to detect changes in caches. I believe this can be closed.
