### ISSUE TITLE
Allow repo owners to use TRAVIS_SECURE_ENV_VARS on restart of public pull request

### ISSUE THREAD

**Issue by stephengroat** [travis-ci/travis-ci#6398]
Wondering if there's any way to currently allow repo owners to restart a build that can use encrypted variables.

Currently looking to use some web APIs in a repo. Need to encrypt the API tokens and not have non members access them, but want a repo owner to be able to review PR and use encrypted vars.

Any method to currently do this? I realize it's kinda in contradiction to #887, but was curious

**Comment by BanzaiMan** [comment]
Unfortunately, there is not. See #1946.
