### ISSUE TITLE
[D] Dmd installation times out 

### ISSUE THREAD

**Issue by wilzbach** [travis-ci/travis-ci#6401]
> Please make sure to ping @MartinNowak, @klickverbot and @ibuclaw 

I think there are still have issues with the CI timing out, eg have a look at this build:

https://travis-ci.org/dlang/phobos/builds/149152075

The following command failed

```
$ source "$(CURL_USER_AGENT="$CURL_USER_AGENT" bash install.sh dmd-2.071.0 --activate)"
curl: (56) Recv failure: Connection reset by peer
/home/travis/build.sh: line 45: : No such file or directory
```

While I would love to see a better availability of the download server, a quick workaround would probably include a retry loop in the build script?

**Comment by wilzbach** [comment]
Oh this was already reported earlier today at D's Bugzilla - https://issues.dlang.org/show_bug.cgi?id=16349

**Comment by MartinNowak** [comment]
This is an issue of our install script and not a Travis-CI specific bug, think we should close this here and keep it in our Bugzilla.

**Comment by MartinNowak** [comment]
Made a PR to fix the issue https://github.com/dlang/installer/pull/187.
