### ISSUE TITLE
Spring boot build hangs forever

### ISSUE THREAD

**Issue by Tandolf** [travis-ci/travis-ci#6403]
Bare in mind, im a beginner when it comes to travis-ci

Had some successful builds in the past but suddenly in the middle of my integrationTests, it has started freezing up. It builds and launches the spring boot application, then it suddenly just stops. And waits... and waits... and waits... i think it waiting to establish a connection to the db.

It builds fine locally. What have i done wrong?

https://travis-ci.org/Tandolf/lift

**Comment by BanzaiMan** [comment]
Is the process supposed to be sent to the background? Otherwise, your build will wait for your user input forever which never comes.

**Comment by Tandolf** [comment]
the build is supposed to start up a neo4j image with docker, and then when spring boot is up it starts running the integration tests against the spring boot app. It works on my local computer, but here it hangs forever, i don't know what input it should be wating for?

**Comment by BanzaiMan** [comment]
Sorry, but I don't have any idea what is supposed to happen next. If you'd like, we can provide you with access to a live VM so you can troubleshoot more interactively. Please send email to support@travis-ci.com.
