### ISSUE TITLE
build cancellation seems flaky on web

### ISSUE THREAD

**Issue by wisechengyi** [travis-ci/travis-ci#6405]
Hi,

Our [build](https://travis-ci.org/wisechengyi/pants/builds/149549902) has 10 shards, and sometimes when I click 'X' button, some jobs will show up as cancelled, but later some of them will show as 'pending'. Essentially it is a bit flaky because I cannot say for sure if the builds have been fully cancelled, so the following builds can continue.

Could be wide spread problem. Just want to make sure and keep track of the issue.

Thanks,
Yi

**Comment by joepvd** [comment]
This is investigated under #5690.
