### ISSUE TITLE
Ubuntu 12.04 and sqlite bug

### ISSUE THREAD

**Issue by darrenleeweber** [travis-ci/travis-ci#6406]
See https://bugs.launchpad.net/ubuntu/+source/sqlite3/+bug/1609557

This bug was contributing to failures on travis that we could not replicate on more recent OS and sqlite distros, e.g.
https://travis-ci.org/dpn-admin/dpn-server/builds/149562094

**Comment by BanzaiMan** [comment]
Our SQLite3 package is a custom one: https://launchpad.net/~travis-ci/+archive/ubuntu/sqlite3. Ours is newer than the official Ubuntu package (http://packages.ubuntu.com/precise/sqlite3), and unlikely to be changed for the upcoming update. Sorry, but I do not know what customization went into that package.

If you need a newer version of SQLite3, I suggest using Trusty instead. http://packages.ubuntu.com/trusty/sqlite3

**Comment by darrenleeweber** [comment]
Is there any way to specify the container OS in a .travis.yml file?  For example, can we specify a more recent Ubuntu LTS than 12.04, like 14.04 or 16.04?  Is there a parameter to choose one or more docker containers among those available in travis build farms?

**Comment by BanzaiMan** [comment]
Sorry, but there is no way to do that.

**Comment by darrenleeweber** [comment]
We found that the sqlite version was 3.7.9.  To update it, it seems we could add commands to an `install:` phase of the `.travis.yml` recipe, but this update requires `sudo` so it would no longer run in a container when using `sudo` to get this package update, i.e.

```
sudo add-apt-repository ppa:travis-ci/sqlite3
sudo apt-get update
```
In that case, I don't know what kind of OS it would use.  It would be like starting over.

**Comment by darrenleeweber** [comment]
The link you gave above [1] says the sqlite version is `3.7.15.1-1~travis1` but when we checked for the version, we got
```
$ bundle exec sqlite3 --version
3.7.9 2011-11-01 00:52:41 c7c6050ef060877ebe77b41d959e9df13f8c9b5e
```
So that is not the custom library backport that your pointing to.  Are you certain that the backport is installed correctly?

[1] https://launchpad.net/%7Etravis-ci/+archive/ubuntu/sqlite3

**Comment by BanzaiMan** [comment]
I'm closing this as WONTFIX, as we are retiring the Precise image. As for the version expectation mismatch, my guess is that the cookbooks did not use the one on launchpad.net.

At any rate, if you need a newer version of SQLite3, please (continue to) use Trusty.

Thanks.
