### ISSUE TITLE
Unclear documentation for deployment `on` key

### ISSUE THREAD

**Issue by ankon** [travis-ci/travis-ci#6407]
1. The documentation at https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A talks about 'common options', implying that there are more. Unfortunately there is no pointer where I could learn about these.
2. The 'branch' part talks about 'all_branches', but it is unclear where this should be - is it a condition, or something on the 'deploy' key? I assumed it is not a condition, because of the first problem: the list seemed exhaustive, and there was no entry for 'all_branches' in it
   
   > branch Name of the branch. If omitted, this defaults to the app-specific branch, or master. If the branch name is not known ahead of time, you can specify all_branches: true instead of branch: *\* and use other conditions to control your deployment.

**Comment by BanzaiMan** [comment]
1. Uncommon options are documented in individual provider's page; e.g., https://docs.travis-ci.com/user/deployment/s3.
1. As you mention, the document says: `all_branches: true` **instead of `branch`**.
With `branch: *`, you have
```yaml
deploy:
  ⋮
  on:
    branch: release
```
So with `all_branches: true`, you have
```yaml
deploy:
  ⋮
  on:
    all_branches: true
```

**Comment by ankon** [comment]
Thanks!

Regarding the second one: Ultimately I figured that out, partially by trying, and with this article which had an example: http://blog.tgrrtt.com/exploring-the-travisci-configuration-file

**Comment by jplebre** [comment]
What about the &2 *2 used on the cat party example? I can't get code deploy to work and am scratching my head figuring out what those arguments are as they are the only difference between cat party and my travis.yml

**Comment by BanzaiMan** [comment]
@jplebre `&2` and `*2` are YAML [anchors](http://www.yaml.org/spec/1.2/spec.html#id2785586) and [aliases](http://www.yaml.org/spec/1.2/spec.html#id2786196).
