### ISSUE TITLE
Two builds with the same number

### ISSUE THREAD

**Issue by Blaisorblade** [travis-ci/travis-ci#6409]
I just pushed a commit to a pull request on commercialhaskell/stack and this created *two* builds with the *same* visible number, `#3420`, though they're otherwise distinct.
https://travis-ci.org/commercialhaskell/stack/builds/149748655
https://travis-ci.org/commercialhaskell/stack/builds/149748680

This is as if the number in `#3420` was generated by incrementing some counter, and I hit some race condition because the increment isn't atomic enough. Possible?

Can I assume the issue is just cosmetic (as it seems) and not worry too much (trust build results, etc.)?

**Comment by joepvd** [comment]
Thanks for reporting. We believe the underlying cause has been fixed. Only the number has been affected, if you don't rely on this yourself, the bug has been cosmetic.
