### ISSUE TITLE
multiple 'script' deploy targets

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#6411]
Can I have several `- provider: script` entries in `.travis-ci.yml`? Currently this doesn't seem working...

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by igagis** [comment]
https://travis-ci.org/igagis/nitki/jobs/149837371

Ok, the second script provider is actually working, i.e. it is called, but it could not find the `pod` command, for some reason, though `pod` command works ok from within `before_install`

**Comment by BanzaiMan** [comment]
Cocoapods is getting installed for your Ruby runtime, 2.2.1. Deployment is carried out by 1.9.3 for compatibility reasons, so it can't find `pod`. Try calling it with `rvm 2.2.1 do pod …`.

**Comment by igagis** [comment]
It works with `rvm`, thanks! Closing the issue.
