### ISSUE TITLE
10 minutes without log output terminates the build

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#6412]
10 minutes without the log output is too low, can that limitation be removed? There is a total build time limitation of 50 min anyway...

For example, deploying my project to cocoapods takes more than 10 minutes, because cocoapods builds everything as part of their lint process and during that it does not do any log output. How can I overcome that Travis limitation??

**Comment by BanzaiMan** [comment]
See https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received.

**Comment by igagis** [comment]
I tried the suggested solution, but it did not work in deploy script. it said command not found, exit code 127:

https://travis-ci.org/igagis/morda/jobs/152020606

**Comment by igagis** [comment]
https://travis-ci.org/igagis/morda/jobs/152036330
```
Deploying application

/Users/travis/.rvm/scripts/set: line 19: exec: travis_wait: not found

Script failed with status 127

failed to deploy

/Users/travis/build.sh: line 45: shell_session_update: command not found
```

**Comment by BanzaiMan** [comment]
Ah. `travis_wait` is a bash function, so it is not available to `rvm`. If deployment takes 10 minutes, there is something wrong with that process. What is `prorab-deploy-cocoapods.sh`, is there a source (I can't find it in your repo), and what is it doing?

**Comment by igagis** [comment]
I also tried to put `travis_wait` before rvm (in this job https://travis-ci.org/igagis/morda/jobs/152020606), then it also complains that it is not found...

@BanzaiMan you can find the `prorab` source here https://github.com/igagis/prorab/tree/master/src

actually, what takes long is a `pod repo push` because it validates the spec before pushing, so it essentially runs `pod spec lint` first and it takes a long time because it tries to build the all sources again and does it silently, that is the problem. Even --verbose key to `pod repo push` does not help, as it first does all the stuff and only then dumps its output to stdout, so it also keeps silent until all the validation-building process finishes...

**Comment by BanzaiMan** [comment]
Is there a way to either skip some of the long processes, or split into smaller parts, so that the time consuming steps can be run in `before_deploy`? This is a problem with the way the process works, so it might not be easy.

We can extend the timeout in this case, as it seems extraordinary, though. Please send email to support@travis-ci.com with the length of time you'd want the timeout to be.

**Comment by igagis** [comment]
No, there is no way to split it to smaller part, as the `pod repo push` is a single operation and it takes more than 10 min. I'll try to email to support.

**Comment by BanzaiMan** [comment]
OK. I've extended the timeout for you. I'm closing this.

**Comment by igagis** [comment]
It seems working now. Thanks!
