### ISSUE TITLE
Ability to use user_nodefs.h for Coverity addon

### ISSUE THREAD

**Issue by pks-t** [travis-ci/travis-ci#6414]
In http://github.com/libgit2/libgit2, we use a custom `user_nodefs.h` which provides the ability to override how Coverity models certain macros. To do so, we are currently forced to not use the coverty_scan addon but instead use a hand-rolled script which builds and submits the project for Coverity (see [coverity.sh](https://github.com/libgit2/libgit2/blob/73dab7692e780e1df96093a54854795428eb66b4/script/coverity.sh)). Using the `user_nodefs.h` file for Coverity is done in [line 36](https://github.com/libgit2/libgit2/blob/73dab7692e780e1df96093a54854795428eb66b4/script/coverity.sh#L36), where the file is simply copied to a special place inside Coverity's tooling.

It would be nice if the coverity_scan addon was extended to enable submitting custom `user_nodefs.h` files. I guess it would be sufficient to add a new optional field `nodefs_file` or similar, which developers can set to the location of the custom nodefs file relative to the project's root.

**Comment by BanzaiMan** [comment]
Is the use of `user_nodefs.h` documented somewhere?

**Comment by pks-t** [comment]
Well, Coverity's [reference](https://scan.coverity.com/models#c_checker_checkerconfig) has a broken link to the nodef feature and I wasn't able to locate proper documentation for it. I've found [another](https://lost-contact.mit.edu/afs/cs.stanford.edu/pkg/prevent-4.3.1/i386_linux26/opt/prevent-linux-4.3.1/cgi-bin/doc/prevent_admin.html#nodefs) link which documents the feature, even though this is not official.

The Coverity analysis tools seem to have no real documentation, either. While there is a default `config/user_nodefs.h` which is included by the various `coverity_config.xml` templates I did not find any further mention.

**Comment by BanzaiMan** [comment]
Seems to me that this is a private API feature, and adding support would be brittle at best.

Closing this for now.
