### ISSUE TITLE
dart sdk glibc no longer compatible with travis?

### ISSUE THREAD

**Issue by vsmenon** [travis-ci/travis-ci#6415]
Our Dart travis bots are all failing with the following:

```
0.01s$ pub global activate dart_coveralls
/home/travis/dart-sdk/bin/dart: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /home/travis/dart-sdk/bin/dart)
The command "pub global activate dart_coveralls" failed and exited with 1 during .
```
See: [https://travis-ci.org/dart-lang/dev_compiler/jobs/150065086](https://travis-ci.org/dart-lang/dev_compiler/jobs/150065086)

Looks like a version mismatch on glibc.

@a14n, @devoncarew, @sethladd,@kevmoo

**Comment by a14n** [comment]
I can see something similar on https://travis-ci.org/a14n/dart-rational/builds/136750361 . The failure only appears on _dev_ channel. Looks like a dependency change occured on this channel.

**Comment by vsmenon** [comment]
@whesse suggests trying this:

> Instructions are: If you just want to get started using our Trusty beta, then add the following to your .travis.yml.

> sudo:
> required
> dist: trusty

I'll give a spin.

**Comment by a14n** [comment]
I was just on the same page :D
https://docs.travis-ci.com/user/ci-environment#Virtualization-environments

_CONTAINER-BASED_ is based on _Ubuntu 12.04 LTS Server Edition 64 bit_ that seems to be a little old.
@BanzaiMan : is there a migration planned?

**Comment by a14n** [comment]
Should be fixed with #5695

**Comment by kevmoo** [comment]
@a14n I tried getting things working using trusty outside the container environment, but `content-shell` does not install.

Could we detect Trusty in the content_shell config and "do it correctly"?

**Comment by a14n** [comment]
@kevmoo it's possible to make custom things depending on the distribution ( see https://github.com/travis-ci/travis-build/blob/0766724c08aadfb22ad8c1f65d949151724a0edf/lib/travis/build/script/csharp.rb#L90 ).
Almost on vacations and not really confortable about how to install content_shell ( @nicolasgarnier did the job ) I will not be able to fix it quickly. Sorry.

It  would be great if someone could take a look and make some changes in https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/dart.rb to fix the issue.

**Comment by kevmoo** [comment]
FYI: we've decided to roll back our dependency on the new glibc to continue supporting Precise.

I did a bleeding-edge roll of Angular to see if this fixed things. See results here

https://travis-ci.org/dart-lang/angular2/jobs/151294698

from https://github.com/dart-lang/sdk/commit/9d2ab4d0163ba031580e9315e02f84d7a1b0612b

I think this commit will be in dev.5. We can confirm then.

**Comment by kevmoo** [comment]
Related issue: https://github.com/dart-lang/sdk/issues/27048

**Comment by whesse** [comment]
At some point in the future, we will want to revisit this, probably when Ubuntu precise LTS reaches EOL in April 2017.

**Comment by kevmoo** [comment]
> At some point in the future, we will want to revisit this, probably when Ubuntu precise LTS reaches EOL in April 2017.

Amen. 🙏

**Comment by a14n** [comment]
@BanzaiMan you can close this issue

**Comment by BanzaiMan** [comment]
@a14n Thanks.
