### ISSUE TITLE
LLVM support for Crystal lang builds?

### ISSUE THREAD

**Issue by kofno** [travis-ci/travis-ci#6419]
My crystal repo needs llvm to compile. Is is possible to specify that in the .travis.yml, or does it need to be added?

cc/ @asterite, @jhass, @waj and @will

**Comment by jhass** [comment]
It's not.

I'm not sure it's common enough in order to provide and maintain an option inside Crystal build.  `crystal-lang/crystal` runs the tests within a docker container with the right environment setup. You're free to reuse those docker images for your own build.

**Comment by kofno** [comment]
:( 

That's fair. I was hoping not to have to do a lot of customization, but that's cool. I'll probably pipe up in IRC when I'm ready to tackle that.
