### ISSUE TITLE
Can't see end of log output

### ISSUE THREAD

**Issue by benasher44** [travis-ci/travis-ci#6421]
Hello! I've been trying to debug several of my Xcode 8 builds, but I still cannot seem to be able to see the end of the output. It always seems to get cut off, and I'm not sure why:

https://travis-ci.org/benasher44/shapeswift/builds/150504012

Thanks!

**Comment by BanzaiMan** [comment]
You are setting `set -e` (https://github.com/benasher44/shapeswift/blob/235539147c85d67d1aea3f889a64e9ff38fcae0a/scripts/travis/prep_keychain.sh#L30) and something is failing in the middle of the script.

Turn off `errexit`, and continue debugging.

**Comment by benasher44** [comment]
TIL `set -e` affects the parent processes environment. I'll try that and update.

**Comment by BanzaiMan** [comment]
You `source`d the option, not executed it.

At any rate, I don't think this is an issue with our code at this time. I'm closing this.

**Comment by BanzaiMan** [comment]
Or not. Might need further debugging, but turning off `errexit` would be a start.

**Comment by benasher44** [comment]
I turned off set -e, and I get roughly the same result: https://travis-ci.org/benasher44/shapeswift/builds/150508303

**Comment by BanzaiMan** [comment]
Thanks for testing. Perhaps this is a duplicate of https://github.com/travis-ci/travis-ci/issues/6018, of which we do not yet have a good grasp.

**Comment by benasher44** [comment]
It could be! I'm going to add a `sleep` in after_failure and see what happens. Thanks!

**Comment by benasher44** [comment]
Adding a sleep made it work. I agree that this is a dup of #6018
