### ISSUE TITLE
Ninject.Extensions.Conventions error

### ISSUE THREAD

**Issue by bzudi** [travis-ci/travis-ci#6425]
Hi, 

I try to run tests for project which uses .net IoC Ninject ,
During the build i get 
![untitled](https://cloud.githubusercontent.com/assets/7791205/17479287/60184190-5d7a-11e6-8823-6f583c7abe88.png)

My project is https://github.com/bzudi/Elicon

I do have the specified reference,
Any  idea ?  @joshua-anderson @akoeplinger @nterry

Thanks

Udi

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by bzudi** [comment]
I tried to change .net target to 4.5  but build still fails for the same reason
 @joshua-anderson @akoeplinger @nterry
Is that Ninject issue ? 
Should I use different IoC container ?
