### ISSUE TITLE
Increase MySQL `wait_timeout`

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-ci#6429]
Occasionally builds run into the `wait_timeout` after which the server closes the client connection. The timeout is currently set to 180 seconds. This leads to non obvious and hard to debug errors when a testing framework keeps the connection open while doing other work.

This can be remedied by putting a line like this in `.travis.yml`:

```
before_script:
    - mysql -e "set global wait_timeout = 28800;"
```

Reproduced with https://travis-ci.org/joepvd/travis-experiment/builds/150747660:

```
...
$ stdbuf -i0 -o0 -e0 awk 'BEGIN{print "SHOW SESSION VARIABLES LIKE \047%timeout\047;"; system("sleep 500"); print "select now()"}' | mysql --user=travis
Variable_name   Value
connect_timeout 10
delayed_insert_timeout  300
innodb_lock_wait_timeout    50
innodb_rollback_on_timeout  OFF
interactive_timeout 28800
lock_wait_timeout   31536000
net_read_timeout    30
net_write_timeout   30
slave_net_timeout   3600
wait_timeout    180
ERROR 2006 (HY000) at line 2: MySQL server has gone away
```

**Comment by araykopotay** [comment]
.travis.yml:
