### ISSUE TITLE
R Travis: "r: bioc-devel" currently not working

### ISSUE THREAD

**Issue by lcolladotor** [travis-ci/travis-ci#6431]
Hi,

As you can see in some of the latest builds of `recount` https://github.com/leekgroup/recount/commits/master, I keep getting errors when checking with `r: bioc-devel`. The actual error is (from https://travis-ci.org/leekgroup/recount/builds/150837912#L1360-L1365):

```
Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
Error: ‘BiocInstaller’ must be installed for this functionality.
Execution halted
The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
```
I found somewhat related issues: https://github.com/travis-ci/travis-ci/issues/6267, https://github.com/HenrikBengtsson/matrixStats/issues/88, https://github.com/hadley/devtools/issues/1254. However, `recount` is a Bioconductor package and as stated by @jimhester at https://github.com/hadley/devtools/issues/1254#issuecomment-230584710 using `r: bioc-devel` should work (which is in line with the docs at https://docs.travis-ci.com/user/languages/r). 

Using `r: bioc-devel` leads to an R session without `BiocInstaller` as shown at https://travis-ci.org/leekgroup/recount/builds/150837912#L439-L454 using the travis config file https://github.com/leekgroup/recount/blob/a51990fdc4533f9cedbd41a37fca8a5c5875d717/.travis.yml. 
However, also using `bioc_packages: BiocInstaller` as shown in the following config file https://github.com/leekgroup/recount/blob/2ec422179ec80dabb0655f80d4197b5342f168e1/.travis.yml does include `BiocInstaller` in the R session info https://travis-ci.org/leekgroup/recount/builds/150834589#L482 and bypasses the error previously mentioned. This particular build failed because the Bioconductor package dependencies were being installed from Bioc-release (currently 3.3) as shown here https://travis-ci.org/leekgroup/recount/builds/150834589#L3198.

Note that these builds are without `cache: packages` in the Travis configuration file. 

I assume that this issue is due to Bioc 3.3 being released earlier this year. I didn't notice it before because I was installing the only Bioc 3.4 required dependency from `Bioconductor-mirror` (particularly: `Bioconductor-mirror/rtracklayer`). I could change my Travis configuration file to install both `BiocInstaller` from Bioc and `rtracklayer` from GitHub, but this would mean testing in an environment different from Bioc-devel.

Please let me know if you have any questions.

Best,
Leo

**Comment by jimhester** [comment]
I don't know what is going on here. [This build from 15 days ago](https://travis-ci.org/leekgroup/recount/builds/147330044#L400-L444) worked fine as you can see from the `Installing Bioconductor` block in the link. However [The next build](https://travis-ci.org/leekgroup/recount/builds/150828546) from 9 hours ago is missing this section completely. Manually compiling the build script on a vagrant box also includes the `biocLite()` steps correctly and this is explicitly checked for in the [specs for r_travis](https://github.com/travis-ci/travis-build/blob/master/spec/build/script/r_spec.rb#L11-L16). I am baffled why this is not working on the deployed version. @lcolladotor as a workaround you can explicitly set `bioc_required: true` and `bioc_use_devel: true`, which should force the script to install Bioconductor.

@BanzaiMan Any ideas what could be different on the deployed version than the current master?

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/commit/621ddb55b36ad5933c6bef3e4c26812411c774a1 is the current deployed commit.

https://github.com/travis-ci/travis-build/blob/621ddb55b36ad5933c6bef3e4c26812411c774a1/lib/travis/build/script/r.rb#L293 shows when Bioconductor is installed. https://github.com/leekgroup/recount/blob/a51990fdc4533f9cedbd41a37fca8a5c5875d717/.travis.yml doesn't meet either of these conditions, so I expect Bioconductor installation to be skipped.

If it was working before, it was probably by accident.

**Comment by jimhester** [comment]
@BanzaiMan There is also https://github.com/travis-ci/travis-build/blob/621ddb55b36ad5933c6bef3e4c26812411c774a1/lib/travis/build/script/r.rb#L520-L523, which sets `bioc_required: true`, which is why this was working before, still not sure why it stopped working, will look some more.

**Comment by BanzaiMan** [comment]
Interesting. The changes in `r.rb` between the passing and the failing builds can be seen here: https://github.com/travis-ci/travis-build/compare/ad83e8722...621ddb55b

**Comment by lcolladotor** [comment]
Hi,

Thanks for looking into this! Note that the build from 15 days ago was using `cache: packages`. So maybe the issue is from before then. I removed `cache: packages` to force R Travis to install everything from scratch once I saw the `BiocInstaller` error.


In any case, using the workaround Jim Hester suggested worked: https://github.com/leekgroup/recount/commit/3bbd47f07eeb4a337ed47102b4f12267e42965d1 https://travis-ci.org/leekgroup/recount/builds/150984542. Right now, I added the line `cache: packages` to reduce the test time. Hopefully this won't break anything.

Best,
Leo

**Comment by BanzaiMan** [comment]
Hello, everyone. Sorry for the inconvenience. As @jimhester pointe out to me, this appears to be a bug on our side. I've created an internal ticket to track this.

**Comment by BanzaiMan** [comment]
I think this has been fixed. I'm closing this, but if you see problems, do let us know.

**Comment by lcolladotor** [comment]
Thanks! I can verify that it works now as intended =)
