### ISSUE TITLE
In the last few days, builds are created but not processed

### ISSUE THREAD

**Issue by mikand** [travis-ci/travis-ci#6432]
Hi!

In the last few days, we are experiencing problems in getting our builds executed by Travis. In particular, all the builds on our project are correctly created in Travis upon PR or commit, but none of them is executed.

We already tried to cancel the builds and re-starting, and we also tried to remove all the caches for build https://travis-ci.org/pysmt/pysmt/builds/150731865.

The strangest thing is that the master branch of our project (https://github.com/pysmt/pysmt) was tested correctly 11 days ago, but the very same commit is not executed upon a manual restart (see https://travis-ci.org/pysmt/pysmt/builds/148324792).

Any help would be useful,

Thanks a lot!

**Comment by BanzaiMan** [comment]
Hello, there. Sorry for the troubles. The `pysmt` organization (in fact, `pysmt/pysmt` repository) has a bad build stuck at the top of the build queue, preventing all other builds from running.

Cancel https://travis-ci.org/pysmt/pysmt/builds/150133374 and your build queue should clear up in turn.

We are investigating why this build got into this state in the first place. We will get in touch with you if we need additional information.

**Comment by mikand** [comment]
Thanks a lot!

I didn't noticed that build at the end of the PR page. The strange thing is that that particular build (differently from all the others) had no number associated with it: 
![pr](https://cloud.githubusercontent.com/assets/2255972/17515174/1cc9c3f6-5e37-11e6-801b-4846bde660b0.png)

Anyway, thanks a lot for the prompt answer! The builds seems to be regularly scheduled now!

**Comment by BanzaiMan** [comment]
I see the builds running. Restarting https://travis-ci.org/pysmt/pysmt/builds/150133374 is probably a bad idea, since it's incompletely configured. Other than that, I think we are in good shape.

I'm closing this now, but if you see further problems, do let us know.
