### ISSUE TITLE
Changes detected in emptied subfolder while caching 

### ISSUE THREAD

**Issue by peterychuang** [travis-ci/travis-ci#6433]
I was trying to exclude a folder from being cached by removing the content inside:

```
cache:
  directories:
    - $HOME/gopath/src/
    - $HOME/gopath/pkg/
    - $HOME/gopath/bin/
before_cache:
  - rm -rf $HOME/gopath/src/github.com/username/repo/*
```

While the folder appears to have been excluded in the cache, changes are always detected in the emptied folder for some reasons:

```
store build cache

change detected (content changed, file is created, or file is deleted):
/home/travis/gopath/src/github.com/username/repo/something
/home/travis/gopath/src/github.com/username/repo/something-else
# etc etc

...
changes detected, packing new archive
.
uploading archive
```
Perhaps related to https://github.com/travis-ci/travis-ci/issues/3039?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by peterychuang** [comment]
Yes, here it is:
https://travis-ci.org/peterychuang/peterychuang.github.io/builds/150849670

The .travis.yml for this build is here:
https://github.com/peterychuang/peterychuang.github.io/blob/98a54a159fbc41a1fb9eb78f259ca7566aa43dae/.travis.yml

**Comment by BanzaiMan** [comment]
This appears to be a bad interaction between our Go builds and the caching utility (when it is configured to cache `$HOME/gopath/src/`.

Before the cache is set up, we `rsync` files to `$HOME/gopath/src/github.com/peterychuang/peterychuang.github.io/`. (https://travis-ci.org/peterychuang/peterychuang.github.io/builds/150944304#L169)

When we set up cache, we know about these files, these files are known to the caching utility, and therefore if you remove them in `before_cache`, we detect the changes and upload the cache.

**Comment by peterychuang** [comment]
I can try to figure out what's inside `$HOME/gopath/src/github.com` and put them one by one into my config. Though I guess some sort of `exclude` function would be helpful.

On a slightly unrelated note, I've had some troubles caching `node_modules`, which, in the case of my build, is probably located inside `$HOME/gopath/src/github.com/peterychuang/peterychuang.github.io/`. Whether I cache `node_modules` or not seems to make no difference when it runs the `npm install`. I was wondering if caching `node_modules` is not possible in the `language` isn't `node_js`

Thanks.
