### ISSUE TITLE
Matrix whitelist/blacklist branches

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6434]
If this is not already possible, it would be nice to be able to whitelist and/or blacklist branches for certain matrix elements. For instance, one could have a deploy configuration in the matrix for `master` only and one could do testing on PRs to `master`. If there is some way to do this, that would be great information. Thanks.

**Comment by BanzaiMan** [comment]
You can deploy conditionally based on the branch name. https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

**Comment by jakirkham** [comment]
That's not really what I'm looking for. Deployment is only an example of one use case for this functionality. What I really want to do is something like this, exclude one build if it is a PR and exclude a different build if it is not.

**Comment by BanzaiMan** [comment]
You can vary what code is executed by looking at `$TRAVIS_PULL_REQUST`. https://docs.travis-ci.com/user/environment-variables/
