### ISSUE TITLE
gcc downgraded?

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#6436]
recently I started getting build errors due to old gcc:

https://travis-ci.org/igagis/stob/jobs/150951903

now it is 4.6 on trusty image. Was it downgraded from 4.8?

**Comment by igagis** [comment]
Ok, it is not even trusty, it is 12.04 for some reason... `dist: trusty` does not work anymore...

**Comment by BanzaiMan** [comment]
Could you try pushing a new commit? We had issues with routing Trusty builds earlier today.

**Comment by igagis** [comment]
Here you go https://travis-ci.org/igagis/stob/jobs/150997569
Now trusty is correctly run, but my build fails with strange error which was not happening before, make just terminates with error though all commands it ran were successful...

**Comment by BanzaiMan** [comment]
What does this mean? https://travis-ci.org/igagis/stob/jobs/150997569#L409

> dpkg-buildpackage: warning: failed to sign .dsc and .changes file

**Comment by igagis** [comment]
@BanzaiMan this means that I do not sign the generated debian package. It was working before without complaining on that. Something has changed in the trusty image so that it now complains about that...
 I'll try to workaround this now.

**Comment by igagis** [comment]
problem solved
