### ISSUE TITLE
HHVM issue

### ISSUE THREAD

**Issue by truell20** [travis-ci/travis-ci#6438]
I am running some unit tests on a lamp application using phpunit+mysql. I am getting this error:

```Failed to initialize central HHBC repository:
  Failed to initialize schema in /home/travis/.hhvm.hhbc:```

[Here](https://github.com/HaliteChallenge/Halite/blob/master/.travis.yml) is my .travis.yml. [Here](https://github.com/HaliteChallenge/Halite/blob/master/tests/runTests.py) is the script that it fails on.

Maybe this is because of [the image upgrade](https://www.traviscistatus.com/incidents/2p40l49r3yxd)?

**Comment by BanzaiMan** [comment]
Did this step ever work? If so, could you point to a build log URL?

If not, where does the error message mean?

**Comment by truell20** [comment]
We added MySQL to our travis build just today, after the image upgrade.

**Comment by truell20** [comment]
@BanzaiMan Any update?

**Comment by BanzaiMan** [comment]
I think this is a different manifestation of #6451. HHVM is on the `$PATH`, and somehow your [call to `phpunit`](https://github.com/HaliteChallenge/Halite/blob/522e0aaba96f2ca7deb8933ca03823e203d4eb9c/tests/runTests.py#L20) is invoking unwanted sequence.

**Comment by truell20** [comment]
Totally right. I reinstalled php on travis (which should add the non HHVM version to the path) , and it worked.

**Comment by BanzaiMan** [comment]
Great. Thanks for the confirmation. I am closing this in favor of #6451.
