### ISSUE TITLE
$PATH/perlbrew gone from dist:trusty images

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#6439]
After the [issues earlier today](https://blog.travis-ci.com/2016-08-09-outage-gce-images) the new `trusty` images do not contain the `perlbrew` binary (`precise` OTOH behaves as before)

**Comment by ribasushi** [comment]
Same for `$PATH/cpanm` - exists on `precise`, gone on `trusty`

**Comment by BanzaiMan** [comment]
@meatballhat Could you take a look? Thanks.

**Comment by HariSekhon** [comment]
This is quite a serious breakage to all perl builds which use Trusty (including perl builds with docker service it seems) and has broken the build on a couple of my public projects - any ETA on a fix?

**Comment by JJ** [comment]
Just checking in to see the progress of this issue. it is serious indeed.

**Comment by meatballhat** [comment]
Anybody following along have build URLs they can share? :heart:

**Comment by meatballhat** [comment]
This will be resolved once the packer builds resulting from the relevant changes are live, e.g.: https://travis-ci.org/travis-infrastructure/packer-build/builds/151821436 (currently tagged for `group: dev`)

**Comment by meatballhat** [comment]
I'm in the process of vetting some of the images with the fix, promoting images from `group: dev` to `group: edge`, so if you're using `group: dev` and you see regressions, please switch to `group: edge` :heart:

**Comment by meatballhat** [comment]
All of the updated images are now tagged `group: edge`.  I expect them, or future images that include the fix, to be promoted to `group: stable` (the default routing) this coming Monday (2016-08-15).

**Comment by solarce** [comment]
We've prompted these to `group: stable` approx 15:00 PST. If you see any further problems like this one, please re-open this issue.
