### ISSUE TITLE
mongodb service is started by default

### ISSUE THREAD

**Issue by bobzoller** [travis-ci/travis-ci#6443]
Before today, the mongodb service was off by default.  It is now on by default.  Perhaps this was intentional, but I thought I'd log it in case someone else was caught off guard by this change.

We have a script to install custom versions of mongodb, which broke because they're now unable to bind to the default 27017 port unless you first issue a `sudo service mongodb stop`.

**Comment by bobzoller** [comment]
spoke too soon:
```
sudo service mongodb stop
mongodb: unrecognized service
```

trying to find the proper name of the service using `service --status-all` now.

**Comment by bobzoller** [comment]
hrm not in upstart I guess:
```
sudo service --status-all
 [ + ]  acpid
 [ - ]  apparmor
 [ ? ]  apport
 [ + ]  atd
 [ ? ]  atieventsd
 [ ? ]  binfmt-support
 [ ? ]  console-setup
 [ + ]  cron
 [ ? ]  cryptdisks
 [ ? ]  cryptdisks-early
 [ - ]  dbus
 [ + ]  docker
 [ + ]  friendly-recovery
 [ - ]  grub-common
 [ - ]  hhvm
 [ ? ]  irqbalance
 [ ? ]  killprocs
 [ ? ]  kmod
 [ - ]  landscape-client
 [ + ]  memcached
 [ ? ]  networking
 [ + ]  ntp
 [ ? ]  ondemand
 [ ? ]  open-vm-tools
 [ + ]  postgresql
 [ + ]  procps
 [ + ]  rabbitmq-server
 [ ? ]  rc.local
 [ + ]  resolvconf
 [ - ]  rsync
 [ + ]  rsyslog
 [ ? ]  screen-cleanup
 [ ? ]  sendsigs
 [ + ]  ssh
 [ + ]  sshguard
 [ - ]  sudo
 [ - ]  sysstat
 [ + ]  udev
 [ ? ]  umountfs
 [ ? ]  umountnfs.sh
 [ ? ]  umountroot
 [ - ]  unattended-upgrades
 [ - ]  urandom
 [ - ]  x11-common
```

**Comment by bobzoller** [comment]
```
sudo ps auxw| grep mongo
mongodb   1094  1.3  0.6 246068 48784 ?        Ssl  22:13   0:00 /usr/bin/mongod --config /etc/mongod.conf
```

**Comment by bobzoller** [comment]
I gave up trying to find how it gets started.  adding a `sudo killall mongod` has unblocked us for now.

**Comment by tsmgodoi** [comment]
I've got the same problem. We run mongo on a docker container, and after today we can't bind 27017 port anymore.

**Comment by BanzaiMan** [comment]
@tsmgodoi I think that is a different issue. Try binding to 127.0.0.1 rather than `localhost`.

**Comment by tsmgodoi** [comment]
@BanzaiMan 
Maybe I wasn't clear. I'm using docker-compose to run some tests, so we use:
```
mongo:
  container_name: mongo
    image: mongo:3
    ports:
     - "27017:27017"
```

We were getting: **ERROR: for mongo  Cannot start service mongo: driver failed programming external connectivity on endpoint mongo(86ecb83db35edac57bda4f5328f3c922900da14db4fe66c38bfa43b3594125fe): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use
ERROR: Encountered errors while bringing up the project.** 
(https://travis-ci.org/supremotribunalfederal/stfdigital-autuacao-distribuicao/builds/151062429)

So I killed the mongod process like @bobzoller suggested and our build started working again.

**Comment by ruddell** [comment]
We were having this issue yesterday in our tests using docker-compose with mongo, but it seems to have resolved itself sometime in the last 8 hours.

**Comment by BanzaiMan** [comment]
I'm closing this based on @ruddell's report. If you see evidence otherwise, do let us know.
