### ISSUE TITLE
"Go" not found

### ISSUE THREAD

**Issue by wing328** [travis-ci/travis-ci#6445]
Seems like after the incident yesterday, Go has either been removed or the $PATH has changed and therefore the CI can no longer run Go-related test.
```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (go-get-testify) on project Goswagger: Command execution failed. Cannot run program "go" (in directory "/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/go"): error=2, No such file or directory -> [Help 1]
```
Ref: https://travis-ci.org/swagger-api/swagger-codegen/jobs/150961691

**Comment by solarce** [comment]
We've promoted these to group: stable approx 15:00 PST. If you see any further problems like this one, please re-open this issue.
