### ISSUE TITLE
[regression] How to install python requests in multi-os configs

### ISSUE THREAD

**Issue by ruslo** [travis-ci/travis-ci#6446]
Hi,

Looks like Linux/sudo:false images changed recently (?) E.g. here is old build: https://travis-ci.org/ruslo/polly/builds/148046219. It was working before, I've restarted one job and now it's broken. The problem is about `easy_install3 --user requests` command:

```
$ if [[ "`uname`" == "Linux" ]]; then travis_retry easy_install3 --user requests; fi
Searching for requests
Reading http://pypi.python.org/simple/requests/
Best match: requests 2.11.0
Downloading https://pypi.python.org/packages/8d/66/649f861f980c0a168dd4cccc4dd0ed8fa5bd6c1bed3bea9a286434632771/requests-2.11.0.tar.gz#md5=147afc07d8967cf46359701551a6cb69
Processing requests-2.11.0.tar.gz
Running requests-2.11.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ax0hpf/requests-2.11.0/egg-dist-tmp-rv0bxe
warning: no files found matching 'test_requests.py'
  File "build/bdist.linux-x86_64/egg/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
                                                      ^
SyntaxError: invalid syntax
```

Does anybody know the right way to install `requests` for python 3 for multi-os config with Linux sudo:false?

**Comment by BanzaiMan** [comment]
Syntax error suggests change in Python interpreter. Do you know when (in terms of Python versions) that syntax change was introduced?

**Comment by ruslo** [comment]
> Do you know when (in terms of Python versions) that syntax change was introduced?

Sorry, have no idea.

However according to the logs both version are 3.2.

Old working log https://travis-ci.org/ruslo/polly/jobs/148046221:
```
$ python3 "${POLLY_SOURCE_DIR}/bin/build.py" --home examples/${EXAMPLE} --toolchain ${TOOLCHAIN} --config ${CONFIG} --verbose --clear --install --test

Python version: 3.2
```

New broken log https://travis-ci.org/ruslo/polly/jobs/148046220 has `/home/travis/.local/lib/python3.2`:
```
  File "/home/travis/.local/lib/python3.2/site-packages/requests-2.11.0-py3.2.egg/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
                                                      ^
SyntaxError: invalid syntax
```

**Comment by jayvdb** [comment]
Requests no longer supports python 3.2, as urllib3 dropped support for it in v1.15.

**Comment by ruslo** [comment]
> Requests no longer supports python 3.2

As you may noticed from my comment Python 3.2 is for both working and broken configuration. Anyway I'm not tied to the exact 3.2 version (this is Travis default), I need just anything that will have requests.

**Comment by jayvdb** [comment]
The latest release of requests was 2 days ago, after your working build.

**Comment by ruslo** [comment]
Okay, so it's not about Python version, got it. I was disoriented with the [yesterday incident](https://www.traviscistatus.com/incidents/2p40l49r3yxd). Seems that it's a coincidence.

Just for the reference here is fix:
```
easy_install3 --user requests==2.10.0
```

Not a Travis issue, closing.

PS re:{urllib3 dropped support for it in v1.15} so they just break default Travis environment, good job :)

**Comment by jayvdb** [comment]
@BanzaiMan , label trusty-update-2016-08 looks incorrect, as this was a precise build.
