### ISSUE TITLE
mongodb not longer started when using 'edge' group, wrong init script is being called

### ISSUE THREAD

**Issue by GregorioDiStefano** [travis-ci/travis-ci#6447]
Our .travis.yml config:

```
language: go

# related to mongodb as per:
# https://github.com/travis-ci/travis-ci/issues/5948
group: edge

# Forces travis to use VM insted container, required to be able to build containers.
sudo: required

services:
    - docker
    - mongodb

# Golang version matrix
go:
    - 1.6

....
```

travis-ci tries to start mongodb with: `sudo service mongodb start`, but, mongodb has been upgraded to 3.2.8, and the init script is called mongod, so I have to manually call `sudo service mongod start`.

This started happening yesterday, with no changes in our travis file.

Thanks,
Greg

**Comment by BanzaiMan** [comment]
Could you drop `group: edge` to see if that helps? Thanks.

**Comment by cppchriscpp** [comment]
Not the original reporter, but I ran into this problem with a travis file very similar to the one above. I can confirm that removing the edge group got me back up and running!

**Comment by GregorioDiStefano** [comment]
Confirmed. Closing.
