### ISSUE TITLE
docker-compose missing from `trusty` image 

### ISSUE THREAD

**Issue by joohoi** [travis-ci/travis-ci#6448]
The preinstalled docker-compose seems to be missing from the image. Is this intentional, and if so, how to proceed? The documentation still suggests it's available.

The builds have suddenly started failing today with error:

```
+docker-compose up -d
./script.sh: line 9: docker-compose: command not found
```

**Comment by BanzaiMan** [comment]
Could you restart the failing job? We pushed a new image that addresses this.

**Comment by nunofgs** [comment]
@BanzaiMan we've been having this issue the past few days as well. Just tested and docker-compose is _still_ not available. This is from the build output:

```
Build group: stable
Build dist: trusty
Build id: 29582814
Job id: 47318020
travis-build version: 0692ebec4
```

Can I force travis to use this new image you mentioned? when will it be pushed to everyone?

**Comment by joohoi** [comment]
Yeah, still not available for us either.

**Comment by BanzaiMan** [comment]
Thanks for testing. We'll investigate further.

**Comment by joohoi** [comment]
Works again, we're back to normal. Thanks!
