### ISSUE TITLE
Curl to localhost now uses IPv6

### ISSUE THREAD

**Issue by gsmet** [travis-ci/travis-ci#6449]
Hi!

Starting yesterday and the GCE outage, our builds started to fail with curl not being able to connect to our Neo4j server hosted on localhost.

See a failing build here:
https://travis-ci.org/gsmet/hibernate-ogm/builds/150975757

As you can see, it fails to connect to Neo4j in IPv6:
```
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 7474 failed: Connection refused
```

Prior to that, it was connecting to localhost in IPv4 and it was working correctly:
```
Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 7474 (#0)
```

Is it something expected? Should we make all our services work in IPv6? We are using the default Neo4j configuration and with Neo4j we cannot have both IPv4 and IPv6... (see https://github.com/neo4j/neo4j/issues/1743).

For reference, our .travis.yml:
https://github.com/hibernate/hibernate-ogm/blob/master/.travis.yml

Thanks for your feedback!

**Comment by BanzaiMan** [comment]
While we look at resolving the IPv6 issue, you can force `curl` to use IPv4 with `-4` flag.

```
curl -4vX POST http://neo4j:neo4j@$NEO4J_HOSTNAME:$NEO4J_PORT/user/neo4j/password -d"password=$NEO4J_PASSWORD"
```

**Comment by gsmet** [comment]
Yes, I moved all our localhost references to 127.0.0.1 for now and our build passes.

**Comment by BanzaiMan** [comment]
@gsmet Thanks for the update.

We also have a possible workaround to disable IPv6:

```yaml
before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 - ip addr
```

**Comment by BanzaiMan** [comment]
Do note that we are looking at making this the default on the image itself, so that the workaround is unnecessary.

**Comment by BanzaiMan** [comment]
Hello, there. We've deployed a temporary fix to remove `localhost` from IPv6 addresses in `/etc/hosts`. Please restart failing builds, and let us know how it goes. Thanks.

**Comment by gsmet** [comment]
I confirm the workaround you deployed is working correctly.

**Comment by BanzaiMan** [comment]
Sweet! I am closing this now. If you run into further problems, do let us know.

**Comment by gsmet** [comment]
Thanks!
