### ISSUE TITLE
Java fails with trusty beta since 9. Aug. 2016

### ISSUE THREAD

**Issue by treba123** [travis-ci/travis-ci#6450]
Since yesterday, our build system suddenly became corrupt. The builds work fine, but the application does not start up anymore (without any output). After switching back to default (loosing openjdk8) it worked fine again.

https://travis-ci.org/loklak/loklak_server/builds/151158561
https://travis-ci.org/loklak/loklak_server/builds/151099418

**Comment by BanzaiMan** [comment]
How does it fail to start? https://travis-ci.org/loklak/loklak_server/jobs/151158562#L291

**Comment by sebix** [comment]
I can confirm, that there's again something bogus.

Very similar to sudo: required is ignored #6374 and `dist: trusty` to build wrong Ubuntu version #6372

**Comment by sebix** [comment]
And it's not only java, it's python too, but I guess that's irrelevant anyway.

**Comment by treba123** [comment]
Well the corresponding script changed between the two PRs, here are the two codeblocks:
```
echo "starting loklak"
echo "startup" > $STARTUPFILE

cmdline="$cmdline -server -classpath $CLASSPATH -Dlog4j.configurationFile=$LOGCONFIG org.loklak.LoklakServer >> data/loklak.log 2>&1 &";

eval $cmdline
PID=$!
echo $PID > $PIDFILE

while [ -f $STARTUPFILE ] && [ $(ps -p $PID -o pid=) ]; do
	if [ $(cat $STARTUPFILE) = 'done' ]; then
		break
	else
		sleep 1
	fi
done

if [ -f $STARTUPFILE ] && [ $(ps -p $PID -o pid=) ]; then
	CUSTOMPORT=$(grep -iw 'port.http' conf/config.properties | sed 's/^[^=]*=//' );
	LOCALHOST=$(grep -iw 'shortlink.urlstub' conf/config.properties | sed 's/^[^=]*=//');
	echo "loklak server started at port $CUSTOMPORT, open your browser at $LOCALHOST"
	rm -f $STARTUPFILE
	exit 0
else
	echo "loklak server failed to start. See data/loklag.log for details. Here are the last logs:"
    tail data/loklak.log
	rm -f $STARTUPFILE
	exit 1
fi
```
and
```
echo "starting loklak"
echo "startup" > $STARTUPFILE

cmdline="$cmdline -server -classpath $CLASSPATH -Dlog4j.configurationFile=$LOGCONFIG org.loklak.LoklakServer >> data/loklak.log 2>&1 & echo \$! > data/loklak.pid &";

eval $cmdline
while [ -f $STARTUPFILE ]; do 
	if [ `cat $STARTUPFILE` = 'done' ]; then
		break
	else
		sleep 1
	fi
done

if [ -f $STARTUPFILE ]; then
	CUSTOMPORT=$(grep -iw 'port.http' conf/config.properties | sed 's/^[^=]*=//' );
	LOCALHOST=$(grep -iw 'shortlink.urlstub' conf/config.properties | sed 's/^[^=]*=//');
	echo "loklak server started at port $CUSTOMPORT, open your browser at $LOCALHOST"
	rm $STARTUPFILE
	exit 0
else
	echo "loklak server failed to start. See data/loklag.log for details"
	exit 1
fi
```
So the java command line is started via eval. The script then checks whether the temporary startup file exists (and in the first version also if the pid of the command actually exists).

As both versions fail, that means that the startup file is deleted (or not created in the first place, but that should throw an error), which is expected to happen during startup.
But in any case there should be some kind of output in data/loklak.log, which in the first version it also gets printed (the tail data/loklak.log line)

So somehow the java command fails without printing any output. We switched back to precise meanwhile, where everything works as expected.

The change must have happened sometime yesterday IIRC. Before, it worked fine.

**Comment by sebix** [comment]
This is the first non-working build I experienced: https://travis-ci.org/certtools/intelmq/builds/150974530 (2016-08-09T16:24:50Z). It worked at (2016-08-09T12:43:51Z)

**Comment by BanzaiMan** [comment]
@sebix https://travis-ci.org/certtools/intelmq/jobs/150974531 looks to be a different issue. `pip` is trying to write files to `/opt/intelmq`, where the process does not have write permissions. Please open a separate ticket.

**Comment by BanzaiMan** [comment]
Could it be binding to `localhost`? We noticed that currently that is binding to an IPv6 address, which causes problems.

If this is the case, could you try disabling IPv6:

```yaml
before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - ip addr # for confirmation. can be skipped
```

or using a numeric IPv4 address such as 127.0.0.1?

Thanks.

**Comment by BanzaiMan** [comment]
@treba123 I see that recent builds are passing. Can we close this?

**Comment by treba123** [comment]
Didn't yet test (sorry, was too busy) but we can close it and I will reopen if the problem persists.
