### ISSUE TITLE
rake jasmine:ci produces `Invalid argument - connect(2) for "localhost"`

### ISSUE THREAD

**Issue by tansaku** [travis-ci/travis-ci#6452]
hi there, kind of a follow on from https://github.com/travis-ci/travis-ci/issues/5945 which we've fixed by upgrading to ruby 2.3.1, but now we're getting a jasmine fail where everything was fine before - this was also failing on 2.3.0 when we introduced other fixes to #5945  ...

```
 USE_JASMINE_RAKE=true bundle exec rake jasmine:ci
rake aborted!
Errno::EINVAL: Invalid argument - connect(2) for "localhost" port 55965
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/jasmine-2.1.0/lib/jasmine/base.rb:25:in `initialize'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/jasmine-2.1.0/lib/jasmine/base.rb:25:in `open'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/jasmine-2.1.0/lib/jasmine/base.rb:25:in `server_is_listening_on'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/jasmine-2.1.0/lib/jasmine/base.rb:35:in `wait_for_listener'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/jasmine-2.1.0/lib/jasmine/tasks/jasmine.rake:65:in `block (2 levels) in <top (required)>'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/airbrake-5.2.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `load'
/home/travis/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => jasmine:ci
(See full trace by running task with --trace)
The command "USE_JASMINE_RAKE=true bundle exec rake jasmine:ci" exited with 1.
```

The same jasmine command runs fine locally - I've searched the error message, and I guess short of diving in to how the insides of the jasmine rake ci task work I'm a little stuck.

Any help much appreciated.  Example failing build is:

https://travis-ci.org/AgileVentures/LocalSupport/builds/151202862

**Comment by BanzaiMan** [comment]
Could you try connecting to 127.0.0.1 instead of `localhost`?

**Comment by tansaku** [comment]
thanks @BanzaiMan - as far as I know the details of what's happening there are entirely inside the jasmine gem - and I'm not sure whether we can configure what it calls to.  I also note that this also has worked without problem for many months ...

In the meantime I was just trying again with only the very minimum upgrade to fix our cuke not exiting properly issue #5945 - i.e. just upgrading to ruby 2.3.1, and I get this weird pair of failing and passing builds see:

https://travis-ci.org/AgileVentures/LocalSupport/builds/151208888  <-- passing

https://travis-ci.org/AgileVentures/LocalSupport/builds/151208659 <-- failing with jasmine:ci

which seem to correspond to identical code changes, but one of them is the merge into the existing develop branch?

https://github.com/AgileVentures/LocalSupport/commit/d905b29e57e80ff0342a2c7ef5616bbcf67261dc

and

https://github.com/AgileVentures/LocalSupport/commit/f6b821b3b754d394b106a927bad7d15e1d0d219c

respectively - it seems very odd that identical code changes should lead to a fail in one instance and not the other ... I just created this new feature branch directly off develop ...

**Comment by tansaku** [comment]
here's the output summary from the PR:

![](https://www.dropbox.com/s/y17hd3ygs2g5gpb/Screenshot%202016-08-10%2022.20.53.png?dl=1)

**Comment by tansaku** [comment]
it's like the travis-ci/push fails but the travis-ci/pr passes?  What's the difference between these two?  Is it common that one fails and not the other?

**Comment by BanzaiMan** [comment]
@tansaku Interesting. I suspect `localhost` is resolving differently, somehow.

Jasmine doesn't have a way to configure which host to connect to?

**Comment by tansaku** [comment]
@BanzaiMan I found a way to configure the jasmine host: 

https://github.com/AgileVentures/LocalSupport/pull/342/commits/34f41afd0a4259a57e98b0fe89dceac70670e576

but I still get exactly the same issue ... one passing build, one failing one ...

**Comment by tansaku** [comment]
this is the line of jasmine that we are failing on:

https://github.com/jasmine/jasmine-gem/blob/master/lib/jasmine/base.rb#L25

it's this line where the TCPSocket is opened:

```rb
  def self.server_is_listening_on(hostname, port)
    require 'socket'
    begin
      socket = TCPSocket.open(hostname, port)
    rescue Errno::ECONNREFUSED, Errno::ENETUNREACH, Errno::EAFNOSUPPORT
      return false
    end
    socket.close
    true
  end
```

**Comment by tansaku** [comment]
The precise error message is

```
Errno::EINVAL: Invalid argument - connect(2) for "localhost" port 55325
```

hmm, looks like jasmine is ignoring it's own host config on line 35:

https://github.com/jasmine/jasmine-gem/blob/master/lib/jasmine/base.rb#L35

so my config change had no impact - I'm going to have to fork the gem to see if that helps ...

**Comment by tansaku** [comment]
or I could just try updating the jasmine gem ...

**Comment by tansaku** [comment]
upgrading jasmine gem to 2.4 appears to have fixed that issue, but now cukes are failing due to phantomjs incompatibility ...

```
Could not find an executable '/home/travis/.phantomjs/2.1.1/x86_64-linux/bin/phantomjs' that matched the requirements '~> 1.8', '>= 1.8.1'. Found versions were {"/home/travis/.phantomjs/2.1.1/x86_64-linux/bin/phantomjs"=>"2.1.1"}. (Cliver::Dependency::VersionMismatch)
```

I will try and fix that now ...

**Comment by tansaku** [comment]
the weird thing here is that I can find no reference to phantomjs requirements of  '~> 1.8', '>= 1.8.1' anywhere in our gemfile or gemfile lock ... this is failing for me locally AND on travis now ...

**Comment by tansaku** [comment]
okay, fixed that with bundle update - had to make a few other adjustments - and then the jasmine fail came back - hacked up the gem - am now on a custom version of jasmine.  Still getting split of one fail and one not, but both are passing the jasmine thing - temperamental js timeout on the other - gosh this hole is deep ...

**Comment by BanzaiMan** [comment]
OK, so jasmine has `localhost` hardcoded. This make this ticket a variation of #6449.

We deployed a temporary fix to remove `localhost` from IPv6 addresses in `/etc/hosts`. In theory, it should work now. Could you test a previously failing build and confirm that it works for you?

**Comment by tansaku** [comment]
@BanzaiMan thanks for all your efforts - plan to do next week when I'm back from travels ...

**Comment by BanzaiMan** [comment]
This is passing now. https://travis-ci.org/AgileVentures/LocalSupport/builds/166479315
