### ISSUE TITLE
sudo is not allowed to write in /opt

### ISSUE THREAD

**Issue by sebix** [travis-ci/travis-ci#6453]
The command `sudo pip install .` fails because the process can't write to `/opt/`:

    PermissionError: [Errno 13] Permission denied: '/opt/intelmq'

See a non-working build (2016-08-09T16:24:50Z): https://travis-ci.org/certtools/intelmq/builds/150974530
And a working build (2016-08-09T12:43:51Z):  https://travis-ci.org/certtools/intelmq/builds/150888788
No changes to .travis.yml have been made

Similar to #6374 and probably related to #6450

**Comment by meatballhat** [comment]
The fix for this should be available in `group: edge` images within 24 hours, and *may* be part of `group: stable` (the default) in that time window as well.  :heart:
