### ISSUE TITLE
docker image's docker-engine version upgraded but documentation didn't

### ISSUE THREAD

**Issue by erikdstock** [travis-ci/travis-ci#6454]
https://docs.travis-ci.com/user/trusty-ci-environment/#Docker says docker is 1.8.2
https://travis-ci.org/erikdstock/tipjar/builds/151278664 says docker installed version is 1.12.0 (line 252)

**Comment by oryband** [comment]
Dear Travis,

Please keep your documentation updated. You are not a hobby weekend project.

- Thank you, the community.
