### ISSUE TITLE
Build numbers not unique

### ISSUE THREAD

**Issue by adigherman** [travis-ci/travis-ci#6457]
Not sure why Travis generated the same build number for 2nd and 3rd check run (https://travis-ci.org/neuroconductor/oro.nifti/builds). Can you please confirm if this is normal or if it's a bug? I am building a custom web enabled project that relies on those numbers being unique (using the local travis gem to parse the travis logs and associate them with github repos). Thanks!

**Comment by BanzaiMan** [comment]
I think we fixed this issue recently (this side of 13 days, the last time your build ran).

I'm closing this optimistically, but if you see the issue again, please let us know.
