### ISSUE TITLE
Ability to retry GitHub Release artifact uploads

### ISSUE THREAD

**Issue by jpopadak** [travis-ci/travis-ci#6459]
Currently, there is no way to retry GitHub Release artifact uploads.

Every time I try to create a Release using GitHub Enterprise, I get the following error:
`Status: 502 Bad Gateway`

Our TravisCI team looked in the logs and found this:

```
» 20 Jul 2016 15:53:15.332 2016-07-20T19:53:15+00:00 10.40.40.67 program=haproxy <proxy> [20/Jul/2016:19:53:03.501] https_protocol~ web_unicorns/localhost 98/0/15/11681/11794 502 521 - - ---- 645/628/3/3/0 0/0 {<domainAddr>||Octokit Ruby Gem 4.3.0} "POST /api/uploads/repos/jmpopada/ucbot/releases/3734/assets?name=ucbot-with-dependencies.zip HTTP/1.1" Context
» 20 Jul 2016 15:53:16.001 2016-07-20T19:53:15+00:00 10.40.40.67 program=github_access - - [20/Jul/2016:19:53:15 +0000] "POST /api/uploads/repos/jmpopada/ucbot/releases/3734/assets?name=ucbot-with-dependencies.zip HTTP/1.1" 502 87 "-" "Octokit Ruby Gem 4.3.0" "129.42.208.167" 11.680 8.320 . Context
» 20 Jul 2016 21:18:00.512 2016-07-21T01:18:00+00:00 10.40.40.62 program=haproxy <proxy> [21/Jul/2016:01:18:00.347] https_protocol~ web_unicorns/localhost 24/0/0/71/95 201 1288 - - ---- 229/215/3/3/0 0/0 {<domainAddr>||Go 1.1 package http} "POST /api/v3/repos/jmpopada/ucbot/releases/3739/assets/policies?name=ucbot-with-dependencies.zip HTTP/1.1" Context
» 20 Jul 2016 21:18:01.306 2016-07-21T01:18:01+00:00 10.40.40.62 program=github_access - - [21/Jul/2016:01:18:00 +0000] "POST /api/v3/repos/jmpopada/ucbot/releases/3739/assets/policies?name=ucbot-with-dependencies.zip HTTP/1.1" 201 394 "-" "Go 1.1 package http" "10.40.40.62" 0.071 0.071 . Context
» 20 Jul 2016 21:18:09.070 2016-07-21T01:18:09+00:00 10.40.40.62 program=haproxy <proxy> [21/Jul/2016:01:17:56.140] https_protocol~ web_unicorns/localhost 91/0/1/12796/12888 502 521 - - ---- 236/221/5/5/0 0/0 {<domainAddr>||Octokit Ruby Gem 4.3.0} "POST /api/uploads/repos/jmpopada/ucbot/releases/3739/assets?name=ucbot-with-dependencies.zip HTTP/1.1" Context
» 20 Jul 2016 21:18:09.320 2016-07-21T01:18:09+00:00 10.40.40.62 program=github_access - - [21/Jul/2016:01:18:09 +0000] "POST /api/uploads/repos/jmpopada/ucbot/releases/3739/assets?name=ucbot-with-dependencies.zip HTTP/1.1" 502 87 "-" "Octokit Ruby Gem 4.3.0" "129.42.208.167" 12.796 8.643 . Context
```

When I create a Release in GHE, it successfully kicks off a TravisCI build, starts the deployment, and even successfully pushes the zip file to the Release in GHE, but still ERROR's the build.

The issue is when I do this, I get an email along with the build itself Error'ing out even though it successfully uploaded the artifact to GHE.  The file it is looking for already exists. If you go to GitHub Enterprise, the full 110mb .zip file was added to the specified GitHub Release.

Doing some research on this, it looks like this is a valid error response from the GitHub API for Uploading a Release Asset: https://developer.github.com/v3/repos/releases/#upload-a-release-asset

This is my .travis.yml section that deals with artifact pushing to GitHub Enterprise.

```
deploy:
  provider: releases
  file: "target/ucbot-with-dependencies.zip"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure:  <APIKEY>
```

Since I can re-run the exact build request using the TravisCI UI, I can re-run it, and every time I re-run an error'ed build, it successfully completes stating the artifact already exists on that release. So it is uploading it, and the second time it understand it already exists.

**Comment by jpopadak** [comment]
The specific stack trace is here:
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://<hostname>/api/uploads/repos/jmpopada/ucbot/releases/4332/assets?name=ucbot-with-dependencies.zip: 502 - Error uploading asset (Octokit::BadGateway)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:130:in `upload_file'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:111:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:102:in `each'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:102:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider.rb:144:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider.rb:144:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by greglanthier** [comment]
I'm seeing this as well.  The stack trace I see in the Travis UI is:

    /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://<hostname>/api/uploads/repos/<slug>/releases/<release>/assets?name=<filename>: 502 - Error uploading asset (Octokit::BadGateway)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:130:in `upload_file'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:111:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:102:in `each'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:102:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider.rb:144:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider.rb:144:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
    failed to deploy

I don't know if this is related to the size of the upload (67 MB in this case) or some proxy between Travis and GHE.

**Comment by jpopadak** [comment]
Our artifact size is quite large too, around 140MB. But it successfully uploads the full zip it to GHE.
