### ISSUE TITLE
Can't use APT addon to install i386-only packages on Trusty

### ISSUE THREAD

**Issue by mathphreak** [travis-ci/travis-ci#6460]
**UPDATED ISSUE:**

`wine` depends on `wine1.6` depends on `wine1.6-i386`, which is only available on i386 architectures. On Precise (where `wine` depends on `wine1.4` depends on `wine1.4-i386`) this wasn't a problem, but on Trusty it is.

**ORIGINAL ISSUE:**

I need Wine 1.6 available for my deployment process, and until third-party sources becomes available (travis-ci/apt-source-whitelist#28 or https://github.com/travis-ci/apt-source-whitelist/issues/191) the only way to do that without compiling from scratch is on Trusty.

But something APT-related seems to be broken, because when I set `addons: apt: packages: wine` in my `.travis.yml` I get
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wine : Depends: wine1.6 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Symptomatic Travis log: https://travis-ci.org/mathphreak/ReliefValve/jobs/151352357
Symptomatic .travis.yml: https://github.com/mathphreak/ReliefValve/blob/e1f4e2864f2546b5d423dba907398c054e9b20c5/.travis.yml

**Comment by BanzaiMan** [comment]
Try installing `wine1.6` as well.

**Comment by mathphreak** [comment]
That gives https://travis-ci.org/mathphreak/ReliefValve/builds/151397989#L216:

     wine1.6 : Depends: wine1.6-i386 (= 1:1.6.2-0ubuntu4) but it is not installable

Adding `wine1.6-i386` to the list gives https://travis-ci.org/mathphreak/ReliefValve/builds/151398405#L213:

    E: Package 'wine1.6-i386' has no installation candidate

**Comment by mathphreak** [comment]
It looks like that's a multiarch issue.

[On Travis](https://travis-ci.org/mathphreak/ReliefValve/builds/151398926#L1555):
```
$ sudo dpkg --print-foreign-architectures

```
On my system:
```
$ sudo dpkg --print-foreign-architectures
i386
```

It seems like there should still be a way to do this with the APT plugin. Changing the title accordingly.

**Comment by BanzaiMan** [comment]
The `apt` addon is not designed to deal with such use cases. Please use `sudo` commands to achieve your goals.

**Comment by mathphreak** [comment]
If it worked on the Precise images, I think it would make sense for it to still work on the Trusty images, but  maybe that was a deliberate breakage.

**Comment by GregMefford** [comment]
@BanzaiMan Putting `sudo apt-get install -y wine win1.6` in an installation script has the same result. Is that what you meant by "Please use `sudo` commands," or did I misunderstand?

**Comment by mathphreak** [comment]
@GregMefford I had to run `sudo dpkg --add-architecture i386` and then that command worked.

**Comment by GregMefford** [comment]
@mathphreak Thanks for the tip! It didn't work for me, though - is this on Trusy?

I have this in my build script:

```
sudo dpkg --add-architecture i386
sudo apt-get install -y wine wine1.6
```
(I also tried it with just `wine`)

I get the following error:

```
The following packages have unmet dependencies:
 wine1.6 : Depends: wine1.6-i386 (= 1:1.6.2-0ubuntu4) but it is not installable
           Recommends: cups-bsd but it is not going to be installed
           Recommends: gnome-exe-thumbnailer but it is not going to be installed or
                       kde-runtime but it is not going to be installed
           Recommends: fonts-droid but it is not going to be installed
           Recommends: ttf-mscorefonts-installer but it is not going to be installed
           Recommends: fonts-horai-umefont but it is not going to be installed
           Recommends: fonts-unfonts-core but it is not going to be installed
           Recommends: ttf-wqy-microhei
           Recommends: winbind but it is not going to be installed
           Recommends: winetricks but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by GregMefford** [comment]
Never mind. I realized that it wasn't working because I didn't `sudo apt-get update` after adding the architecture.

Here's what does work, for future reference:

```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install -y wine
```
