### ISSUE TITLE
No env variables for pull requests?

### ISSUE THREAD

**Issue by jescalan** [travis-ci/travis-ci#6464]
I have encountered an issue in a few repos where the environment variables are not present in the build when a pull request is submitted. Example here: https://travis-ci.org/static-dev/spike-rooftop/jobs/151542600

Let me know if I have done something wrong here, which probably is the cause (sorry in advance!)

**Comment by BanzaiMan** [comment]
Secure environment variables are not available to the PR builds for security reasons. https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions

**Comment by jescalan** [comment]
@BanzaiMan ah thank you so much! makes perfect sense 👍 guess I should have read the docs
