### ISSUE TITLE
Error in opening zip file, when running tests parallel

### ISSUE THREAD

**Issue by janakact** [travis-ci/travis-ci#6466]
Hi, 
I am contributing to [Apache Tajo](https://github.com/apache/tajo). Here is [my fork.](https://github.com/janakact/tajo). In traivis it fails one build because of `java.util.zip.ZipException: error in opening zip file`. Here is the [log](https://travis-ci.org/janakact/tajo/jobs/151707993).
If I run it with the same test flag in my local machine it works fine.

I found something similar [here](https://github.com/travis-ci/travis-ci/issues/2459). Maybe it is because of multiple builds run at the same time. Is there a way to fix this issue?

**Comment by janakact** [comment]
It is something wrong with caching. It started to work again normal after several days.

**Comment by adamretter** [comment]
This seems to be occurring again - https://travis-ci.com/github/eXist-db/exist/jobs/314882048#L337

**Comment by adamretter** [comment]
@stale /reopen
