### ISSUE TITLE
Useful documentation on all features of .travis.yml impossible to find

### ISSUE THREAD

**Issue by vitaly-krugl** [travis-ci/travis-ci#6468]
I am always struggling to find complete documentation of .travis.yml. For example, I wanted to find out how to use the "virtualenv:" tag (system_site_packages, etc.), and I just can't seem to locate the documentation after spending hours googling for it.

Is it hidden in an obscure place or just doesn't exist. Sorry, but I am so incredibly frustrated by it being so difficult to find the complete documentation. :(

**Comment by BanzaiMan** [comment]
Thanks for the feedback. We are working to improve our documentation in general, and we think good things are coming.

This issue, though, is very vague and very hard to act on. If you have individual issues to address, please do so; I know it is tedious, but I believe it is for the best in the long run.

**Comment by jayvdb** [comment]
@vitaly-krugl , this might help : there are two pre-built virtualenv's with the virtualenv system-site-packages flag enabled.  They are for Python 2.7 and 3.2 ; a simpler way to access them is to use an explicit virtualenv name for the python version (e.g.  `2.7_with_system_site_packages`) 

Example: https://github.com/wikimedia/pywikibot-core/blob/f5aaf85/.travis.yml#L132

**Comment by vitaly-krugl** [comment]
For example, a pressing issue for me now is that I need to update pip and setuptools to newer versions (the default ones are all but obsolete, don't support PEP-508) in https://github.com/numenta/nupic/pull/3262.

However, it's a known issue in travis that doing something like `pip install --upgrade setuptools` doesn't have the desired effect: it claims to install the new version, but the one that gets used is still the old one (see #4194).

So, I am at a loss of what I need to do in order to upgrade both setuptools and pip. Does anyone know? The comments I've seen in related issues have been too vague.

**Comment by jayvdb** [comment]
#4194 is about `pip install --user`.

If you use `sudo: required` as shown in my example above, you do not need to use `--user`, and the `pip install --upgrade pip setuptools` will be successful.

**Comment by vitaly-krugl** [comment]
Thanks for your recommendation, @jayvdb. I will give it a try.

**Comment by vitaly-krugl** [comment]
@jayvdb, that didn't work with our build, which uses the default linux environment that runs in containers. This environment doesn't support sudo. Also, #4194 describes that the problem is with travis-installed pip and setuptools eggs being explicitly at beginning of sys.path, thus preventing upgraded versions from running. This is exactly the problem that I had in my environment - upgrade of setuptools and pip would complete successfully, but when attempting to use, it would run the old version instead of the new. I worked around it by switching to a new virtualenv and not using `--user` with `pip install`.

However, the issue of severely-lacking documentation - the subject of this issue - is a critical one. There just isn't a comprehensive source of information about the travis elements of .travis.yml. Googling for hours at a time to solve a simple problem is not a viable solution.
