### ISSUE TITLE
Add instruction how to use Ubuntu 16.04 on Travis

### ISSUE THREAD

**Issue by techtonik** [travis-ci/travis-ci#6469]
As I understand Ubuntu 16.04 is only possible on Travis with docker (#5821). However, without experience with it, the [current documentation](https://docs.travis-ci.com/user/docker/) is very cryptic (I am not a Sinatra user either). Is it possible to add specific instructions how to use Ubuntu 16.04 on Travis (which comes with gcc 5.3 c++11 support)?

**Comment by BanzaiMan** [comment]
How much do you know about Docker? It is certainly not an easy thing to learn at first, but, with experience, I am sure you can learn how to use it.

Also with experience, you would realize that the example given in our documentation shows nothing peculiar about Sinatra. It just shows how to pull an existing image, run a process using it, with mapping ports appropriately.

You might find some of these GitHub search results handy, but do keep in mind that we do not provide support for any of it. https://github.com/search?utf8=%E2%9C%93&q=docker%20pull%2016.04+filename%3A.travis.yml

I'm going to close this for now.

**Comment by techtonik** [comment]
@BanzaiMan I am using VirtualBox, Vagrant, LXC, LXD, and while, of course, I can learn docker as well, it is not only me who need more updated software than 2 years old stuff on Travis. )

**Comment by meet-bhagdev** [comment]
Any updates on this? Would love to have Ubuntu 16.04 support with TravisCI 👍

**Comment by andreif** [comment]
**Experimental** `dist: xenial` works sometimes. 
I just needed to install extra package to make my build work:

```
sudo apt-get install libgnutls28-dev
```
