### ISSUE TITLE
cocoapods master repo out of date -> travis-ci build time increased dramatically

### ISSUE THREAD

**Issue by ogjklindt** [travis-ci/travis-ci#6473]
since some days we are having issues regarding cocoapods master repo.

`None of your spec sources contain a spec satisfying the dependencies: `Fabric (~> 1.6.8), Fabric (= 1.6.8)`.``

regarding our local setup, cocoapods is finding the new version without any problems. the travis-ci cocoapods does not.

we had to add

`before_install:`
`- pod repo update`

but this task is taking 180 seconds, what is increasing the build time for nothing.. 

we already added

`cache: cocoapods`

but this doesn't help.

Any possibility to get around this issue?

adding `pod repo remove master` and `pod setup` is increasing the build time up to 500 seconds, that is not an option.

**Comment by BanzaiMan** [comment]
Sorry about the issue. Which image are you using? Older images are unlikely to be updated, so if it is at all possible, we recommend using newer ones.

**Comment by ogjklindt** [comment]
we use xcode7.3

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by ogjklindt** [comment]
we are running private repos, think the build logs are private or not?

**Comment by ogjklindt** [comment]
```[14:30:53]: ------------------------------
[14:30:53]: --- Step: default_platform ---
[14:30:53]: ------------------------------
[14:30:53]: Driving the lane 'ios app_version' 🚀
[14:30:53]: -----------------------
[14:30:53]: --- Step: cocoapods ---
[14:30:53]: -----------------------
[14:30:53]: $ pod install
[14:30:54]: ▸ Cloning spec repo `xxxx` from `git@github.com:xxxx/iOSPodSpecs.git`
[14:30:55]: ▸ Analyzing dependencies
[14:30:55]: ▸ [!] Unable to satisfy the following requirements:
[14:30:55]: ▸ - `Fabric (~> 1.6.8)` required by `Podfile`
[14:30:55]: ▸ - `Fabric (= 1.6.8)` required by `Podfile.lock`
[14:30:55]: ▸ None of your spec sources contain a spec satisfying the dependencies: `Fabric (~> 1.6.8), Fabric (= 1.6.8)`.
[14:30:55]: ▸ You have either:
[14:30:55]: ▸ * out-of-date source repos which you can update with `pod repo update`.
[14:30:55]: ▸ * mistyped the name or version.
[14:30:55]: ▸ * not added the source repo that hosts the Podspec to your Podfile.
[14:30:55]: ▸ Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
[14:30:55]: Variable Dump:
[14:30:55]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios app_version"}
[14:30:55]: Exit status of command 'pod install' was 1 instead of 0.```

**Comment by ogjklindt** [comment]
@BanzaiMan any idea how to fix this?

**Comment by BanzaiMan** [comment]
The log says the dependencies cannot be resolved. Have you tried any of the suggestions offered in the logs?

If it is working on your machine, your machine probably has older versions of software that satisfies the dependency.

**Comment by ogjklindt** [comment]
the dependencys cannot be resolved because the cocoapoda master repo on your travis vm is out of date, as I posted we needto to every time a pod repo update thats taking 3-5 minutes... thats nothing I can solve on my side.

**Comment by BanzaiMan** [comment]
So, cocoapods resolves dependencies with local information only?

**Comment by ogjklindt** [comment]
seems so? actually on local I do a pod install and everything works without updating the master repo each time. 

perhaps an issues with cache: cocoapods
? perhaps the master repo got cached and therefore not updated automatically?

but now without pod repo update dependencies can not be resolved.

**Comment by ogjklindt** [comment]
@BanzaiMan 
so I finally figured out some issues.

regarding the out of date master repo of cocopods, was related to the issue that pod install does not update the master repo anymore.

finally I adjusted the travis.yml to this:

```yaml
language: objective-c
osx_image: xcode7.3

cache:
  directories:
    - $HOME/.cocoapods/

before_install:
- gem install cocoapods-acknowledgements
- gem install cocoapods
- "./travis/travis_appversion.sh"
- pod update

before_script:
- "./travis/travis_key.sh"

script:
- "./travis/travis.sh"
```

letting travis do the `pod update` instead of Fastlane has done the trick.

But now facing a new issue regarding the cache, I got now this error:

```
adding /Users/travis/.cocoapods to cache
running `casher add/Users/travis/.cocoapods/` took longer than 180 seconds and has been aborted (180.74s)```

Seems the cache function breaks with cocoapods?

**Comment by mmzoo** [comment]
I have the same issue, adding `pod repo update` adds about 200 seconds to the build.

@ogjklindt So you added `pod update` and it was faster? But that's not the same as `pod install` then?

**Comment by rhwood** [comment]
I'm having this issue also. From the logs:

> Note: as of CocoaPods 1.0, pod repo update does not happen on pod install by default.

This suggests that any project relying on any Pod that was released after the OS X build needs to run ```pod repo update```. Can a prebaked, frequently (daily?) updated cocoa pods repo be made available?

**Comment by cepages** [comment]
Same issue here with internal pods

```
- `CocoaLumberjack (= 2.4.0)` required by `Podfile.lock`
- `CocoaLumberjack (~> 2.3)` required by `INCErrorManagement (0.0.1)`
```

as @mmzoo said we can `pod update` but makes the build much longer and not always is needed.

As @rhwood can this be automated via travis, at least update the specs every day?

**Comment by victorg1991** [comment]
This just happen to me :( in xcode8 image is there any possibility instead of pod repo update?

**Comment by cepages** [comment]
@victorg1991 you can try to avoid pod update with this script:

`pod outdated | awk '{ if ( $1 ~ /^-/ ) { print $0 } }' | awk '{ if ( $3 != $5 ) { pod update $2 } else { print "No updated needed it for" $2 } }'`

**Comment by victorg1991** [comment]
@cepages I don't force a pod update I only update the master spec repo and it isn't taking too much time so its acceptable.

Thank you anyway! 😁

**Comment by pengbins** [comment]
Have the same issue,  can't install newly added pods before add following lines to yml.

```
before_install:
  - pod repo update > /dev/null
```

**Comment by neobeppe** [comment]
Now pod repo update takes about 10 minutes, Friday was fine

**Comment by fassko** [comment]
For me as well. It's so slow and Travis kills the build. Any solutions?

**Comment by m4rr** [comment]
`travis_wait pod install --repo-update` makes sense. But the problem is still here: too long task.

**Comment by rudysuharyadi** [comment]
same here

**Comment by isaced** [comment]
same for me, please travis update cocoapods repo!

**Comment by cepages** [comment]
Probably is for the update in the specs: http://blog.cocoapods.org/Sharding/

**Comment by vegidio-symbio** [comment]
I'm using image xcode8.1 and Cocoapods repo is not updated there either. ☹️

Travis should periodically update Cocoapods repo instead of forcing us to run `pod repo update` in our builds. It's a win-win situation: we don't waste around 10 minutes every time we need to run a new build AND Travis don't have to waste bandwidth we the constant updates that we are forced to do.

**Comment by cepages** [comment]
10 min? My last worker took 22 minutes.

**Comment by sbandol** [comment]
![image](http://i.imgur.com/ZKSCOk9.jpg)

**Comment by atsakiridis** [comment]
This is bitting us as well. Are there any workarounds apart of `pod repo update`, until this is fixed? In my case even when using `pod repo update` the build is canceled before it gets a chance to finish, even if I use `travis_wait`I still get issues (notice that I had to redirect to /dev/null to avoid a huge output file, which results in no output hence the need for travis_wait). Finally, I tried travis_wait 30 to last up to 30 minutes, but still not working :(

Any hints?

Best regards,
Antonis

**Comment by cepages** [comment]
@atsakiridis you need to use `travis_wait num_minutes`

 travis_wait by default allows only 20 minutes

**Comment by atsakiridis** [comment]
@cepages, thanks a lot for your input, but I used `travis_wait 30` which I think should be more than enough but still I get a time out. Here's the  Raw log output:

```
...
$ travis_wait 30 pod repo update > /dev/null 2>&1


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

Isn't it weird that the error message says `No output has been received in the last 10m0s`? Shouldn't it say something like 30m0s instead?

Any hints?

Best regards

**Comment by cepages** [comment]
@aakritigupta it could be the redirection: https://github.com/travis-ci/travis-ci/issues/6591

Try to  add that line in a .sh file and run it in the travis.yml file

**Comment by atsakiridis** [comment]
Good catch @cepages, thanks! That explains it. I mean I redirected to avoid having huge output that breaks my build, but it appears that the redirection messes with travis_wait. Let me retry and post back

**Comment by sbandol** [comment]
@atsakiridis 'travis_wait pod repo update --silent' works better than redirect

**Comment by atsakiridis** [comment]
Thanks @sbandol, that seems cleaner indeed ;) Will try that too

**Comment by atsakiridis** [comment]
@cepages @sbandol both are working fine, thanks :) However, it takes around half hour just to update the repo :(

Are you sure there's no other workaround? So all Apps that employ newly uploaded pods have to go through the same pain?

@BanzaiMan are there any plans to remedy this situation? 

Best regards,
Antonis

**Comment by rudysuharyadi** [comment]
They said we need to use Xcode 8.1 image that has a more up-to-date CocoaPods installed on it

**Comment by victorg1991** [comment]
For me its working without repo update, with xcode8.1 image :DDD

**Comment by fassko** [comment]
Finally Travis CI updated to Xcode 8.1 https://blog.travis-ci.com/2016-11-15-xcode-81-is-here

**Comment by atsakiridis** [comment]
Indeed with 8.1 it's working fine! No need for cocoapods update, etc ;) Thanks!

**Comment by solarce** [comment]
In response to the [recent Sharding change](http://blog.cocoapods.org/Sharding/), we've just promoted new `xcode6.4`, `xcode7.3`, and `xcode8` images with **only** the following changes:

- Ran `brew update`
- Updated the default ruby's version of [Cocoapods](https://cocoapods.org/) to `1.1.1`
- Ran `pod setup` (after upgrading Cocoapods)

The `xcode8.1` and `xcode8.2` images already have been updated in this manner, as part of their releases earlier this week.

We'll be making the same updates to our other images over the next few days and we'll update this issue as we promote them.

**Comment by solarce** [comment]
We've promoted new `beta-xcode6.3`, `xcode7.0`, `xcode7.1`, `xcode7.2` images with *only* the following changes:

- Ran `brew update`
- Updated the default ruby's version of [Cocoapods](https://cocoapods.org/) to `1.1.1`
- Ran `pod setup` (after upgrading Cocoapods)

**Comment by rudysuharyadi** [comment]
Nice. Finally. Thanks, I need this, because we are not ready to move to xcode8 yet.

**Comment by solarce** [comment]
What image are you using?

**Comment by rudysuharyadi** [comment]
xcode7.3. I test it just now, only take 14 minutes to build, compare to 30 minutes before.

**Comment by srubin** [comment]
I'm still seeing this issue with `xcode8.2`. In particular, the line 

```
pod 'EDSemver', '~> 0.4.0'
```

gives me:
``` bash
[!] Unable to satisfy the following requirements:
- `EDSemver (~> 0.4.0)` required by `Podfile`
- `EDSemver (= 0.4.0)` required by `Podfile.lock`
None of your spec sources contain a spec satisfying the dependencies: `EDSemver (~> 0.4.0), EDSemver (= 0.4.0)`.
You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by cepages** [comment]
@srubin I guess that happens because if a new version of a particular pod is released, travis doesn't update their pods immediately.

In my case I always have to run `pod update` just in case a new pod was released. Unfortunately This increase the time of the work in travis a lot.

But if anyone has another solution, please share :)

**Comment by srubin** [comment]
I understand that `pod update` fixes this, but I don't understand why travis doesn't run `pod update` on these VMs on an hourly/daily/? basis to prevent their customers from having to waste their resources running `pod update` themselves.

**Comment by Lyoness** [comment]
>I understand that pod update fixes this, but I don't understand why travis doesn't run pod update on these VMs on an hourly/daily/? basis to prevent their customers from having to waste their resources running pod update themselves.

The short answer:  making any changes to the golden images (that all your build vms boot from) has been difficult and timely to do.  

This has to do with 1) the way that virtualization is limited in macOS, 2) containerized build VMS aren't possible because apple requires virtualized macs to run on mac server hardware. 

We've made recent performance improvements by moving to a new datacenter last week.  You should see improved I/O in your build machines so a `pod update` doesn't take as long, as well as dealing with wait times/ backlog, boot times, etc. 

We needed to get that reliability/stability issue out of the way so we can now focus our attention on a solution that gives you a build vm that has `pod update` and other efficiencies.  This requires automation of xcode build images, which has been one of our biggest challenges without having the use of containers and native virtualization.  But we're exploring new tooling in this space and are hopeful to have improvements in this area. 

I'll keep this open and be in touch with any progress updates in the coming months.

-Your Friendly Neighboorhood Build Infrastructure Team

**Comment by colejona** [comment]
Subscribing with bated breath... is this still on the radar?

**Comment by CodyDunlap** [comment]
Any way we can get an update to the default pod repo on the latest osx image? This is still an issue for me and I'm using osx_image: xcode10.1

**Comment by GregHilston** [comment]
Just ran into this issue as well. Having to run our own `pod repo update` our self takes an additional 70 seconds.

**Comment by FranklinYu** [comment]
Best fix: https://blog.cocoapods.org/CocoaPods-1.7.2/
