### ISSUE TITLE
Inconsistent results from Travis

### ISSUE THREAD

**Issue by KellerFuchs** [travis-ci/travis-ci#6477]
In https://github.com/hashbang/docker-gitolite/pull/2, I have the following situation:
- a single commit was pushed (based on `master`) to a branch and a PR was created;
- ` continuous-integration/travis-ci/push` [passed](https://travis-ci.org/hashbang/docker-gitolite/builds/152201494);
- `continuous-integration/travis-ci/pr` [failed](https://travis-ci.org/hashbang/docker-gitolite/builds/152201548).

From the build log, it seems that `continuous-integration/travis-ci/pr` picked up an obsolete commit.
Restarting the build did not fix it.

**Comment by BanzaiMan** [comment]
I'm not sure what you mean by "an obsolete commit". [The failing build](https://travis-ci.org/hashbang/docker-gitolite/builds/152201548) used https://github.com/hashbang/docker-gitolite/commit/1ebf17fc3d02333434838fbacdd988c6d346b4bd, which is a merge of https://github.com/hashbang/docker-gitolite/commit/fc7c8ddd71614d668a4ac5a5526a3a00bdf404b5 and https://github.com/hashbang/docker-gitolite/commit/a9de9a35a01c4d304ac2396ad0d01db65342e5fc.

I see that you are [caching `$HOME/bootstrap-vz`](https://github.com/hashbang/docker-gitolite/blob/1ebf17fc3d02333434838fbacdd988c6d346b4bd/.travis.yml#L6-L7), and you are updating the `.git` checkout there [only when it doesn't exist](https://github.com/hashbang/docker-gitolite/blob/1ebf17fc3d02333434838fbacdd988c6d346b4bd/.travis.yml#L27). If the intention of https://github.com/hashbang/docker-gitolite/commit/1ebf17fc3d02333434838fbacdd988c6d346b4bd is to update the checkout, it  won't work as long as the cache contains the old code.

**Comment by KellerFuchs** [comment]
> I'm not sure what you mean by "an obsolete commit".
Nevermind, I was confused.

> it won't work as long as the cache contains the old code.
Indeed not!  I forgot to clear the cache.

However, that doesn't explain why the build fails. I will look deeper into this.

**Comment by KellerFuchs** [comment]
PS: Thanks for the super-quick followup.

**Comment by KellerFuchs** [comment]
Confirmed: purging the cache changed nothing.

**Comment by BanzaiMan** [comment]
Sorry to hear that. Purging cache did change the `$HOME/bootstrap-vz` checkout, though.

But [this error message](https://travis-ci.org/hashbang/docker-gitolite/builds/152201548#L523)

> `chown: cannot access '/srv/ssh': No such file or directory`

is coming from your code. This is your Docker mount, no?

**Comment by KellerFuchs** [comment]
@BanzaiMan Yes, but Docker is not yet involved at that point.
I think I got it, though: the task ordering in both builds is not the same, and it turns out that the execution order between `file_copy` and `commands` is unspecified.

**Comment by KellerFuchs** [comment]
OK, confirmed: both builds now pass.
Closing as this was a legitimate, non-deterministic build failure.

Thanks again @BanzaiMan for the help, and sorry for the spurious bug report.  :3
