### ISSUE TITLE
nvm - unexpected EOF while looking for matching `)'

### ISSUE THREAD

**Issue by blimmer** [travis-ci/travis-ci#6480]
Seeing this in build logs lately:

```bash
$ git checkout -qf 1f311867d7da56c51739fbb689ccd30184afe3de

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
Updating nvm to v0.31.0
/home/travis/.nvm/nvm.sh: line 45: unexpected EOF while looking for matching `)'
/home/travis/.nvm/nvm.sh: line 46: syntax error: unexpected end of file
```

Things still appear to be working, but wanted to report.

[example](https://travis-ci.org/blimmer/ember-cli-server-variables/jobs/152261435#L126)

**Comment by BanzaiMan** [comment]
Hmmm. Sounds like downloading nvm.sh failed somehow while updating it. :-(

**Comment by BanzaiMan** [comment]
The funny thing is, there has been no error recorded for the updates.

Does the issue persist if you restart it?

**Comment by blimmer** [comment]
hmm yeah it's not showing up again - maybe just a fluke?

**Comment by BanzaiMan** [comment]
Yeah, I am guessing that it is. Please let us know if you see the issue again persistently.

I'm closing this for now.
