### ISSUE TITLE
Container based CI job got killed randomly

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#6482]
I have observed lately a new issue in Travis-CI builds for our project. A CI job would randomly got stopped/killed and to be restarted again later as the job in question is still in the job queue. This may not be a big problem because all the CI jobs would eventually completed. However, I have not observed this kind of behavior before and decided to make this issue report. It is not good for Travis-CI performance as a whole if/when there are many CI jobs got randomly killed half way this way.

**Comment by BanzaiMan** [comment]
VMs can be killed for unforeseen reasons every now and then. Some VMs are spun up and but terminated by platform provider. This, unfortunately, is inevitable when we spin up and terminate so many of them. We do monitor the error rate, and when it does get high, we take action to ensure good service.

**Comment by weitjong** [comment]
Thanks for your reply.  I thought I was reporting a new issue, but since as you said it is a known issue and a monitoring procedure is already in place, I suppose we can close this.
