### ISSUE TITLE
Add OpenJDK 8 for Java based builds

### ISSUE THREAD

**Issue by jehrhardt** [travis-ci/travis-ci#6483]
Currently a Java based build can only choose between OpenJDK 6 and 7 and Oracle JDK 7 and 8. The option OpenJDK 8 is missing.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/apt-source-whitelist/issues/177

**Comment by omajid** [comment]
As an open source developer, I care more about my projects working with OpenJDK 8 than I do about them working with a proprietary JDK version.

Is there anything I can do to improve the support for OpenJDK (6, 7, 8 and 9) in travis-ci?

**Comment by grahamtriggs** [comment]
My project is now in a situation where I'm going to have to ditch support for Java 7.

However, I don't want to ditch support for OpenJDK. Anything that can be done to bring latest version OpenJDK support to Travis would be a really big benefit.

**Comment by aaime** [comment]
Same here, geoserver.org now builds only on Java 8 and we're missing a way to test openjdk.
There are some subtle differences, for example in graphics2d, that make certain rendering test pass on Oracle and fail on OpenJDK, we would like to know that _before_ merging pull requests :-)

**Comment by rklaehn** [comment]
Is this still not possible? We really need this.

**Comment by mcamou** [comment]
Given Oracle's recent stance on JDK licensing, I think this should be a priority.

**Comment by pauldraper** [comment]
Supporting Oracle but not Open JDK (or at least, no version that hasn't been EOL'ed) is a strange choice for a open-source oriented platform.

**Comment by An7ar35** [comment]
Definitely would be nice to be able to use OpenJDK8.

**Comment by pauldraper** [comment]
The workaround, FYI is

```yaml
before_install:
  sudo add-apt-repository ppa:openjdk-r/ppa
  sudo apt-get -qq update
  sudo apt-get install -y openjdk-8-jdk
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
```

This isn't a real replacement for the `jdk` option, it isn't include in the matrix, but it is a solution for anyone that just wants to build with a current open-source JDK.

**Comment by An7ar35** [comment]
@pauldraper Thanks. How do you switch to it though? I'm getting `The command "jdk_switcher use openjdk8" failed and exited with 1 during` on build.

**Comment by BanzaiMan** [comment]
OpenJDK 8 is available now on Trusty images. It is unlikely that we add it to Precise images, so if you want OpenJDK 8, please use Trusty.

I'm closing this optimistically, but if you see problems on Trusty, do let us know.

**Comment by dlandis** [comment]
Sounds good. Should we open a new issue to get the docs updated too:
https://docs.travis-ci.com/user/languages/java/

Or this happening behind the scenes already? Thanks

**Comment by dougxc** [comment]
What's the process to request that the openjdk8 binaries are updated to [8u121](https://launchpad.net/~jonathonf/+archive/ubuntu/openjdk-staging/+build/11982164)?

**Comment by erikvanoosten** [comment]
For those (like me) that read read this and were still wondering what to do: include `dist: trusty` in your `.travis.yml` and `openjdk8` starts to work. E.g.:

```yaml
env:
  - JDK=oraclejdk8
  - JDK=openjdk8
dist: trusty
before_script:
  - jdk_switcher use $JDK
```

**Comment by mvdan** [comment]
@erikvanoosten I don't know how you got that to work - I just get that `jdk_switcher` doesn't exist. Although the same happens with any Android SDK executables.

This is on `language: android`, not `language: java`. `jdk_switcher` works on the regular, non-beta version.

**Comment by eviltak** [comment]
@erikvanoosten's solution worked, but simply using the `jdk` key with `dist: trusty` works too:

```yaml
dist: trusty

jdk:
- openjdk8
```

**Comment by cromoteca** [comment]
OpenJDK 8 on Travis CI
