### ISSUE TITLE
fglrx kernel module missing from Trusty

### ISSUE THREAD

**Issue by haahh** [travis-ci/travis-ci#6486]
The OpenCL builds with AMD APP SDK on Trusty have recently stopped working (I am not sure if they work on Precise).

Error message:

> modprobe: ERROR: could not insert 'fglrx': No such device
> Error: Fail to load fglrx kernel module!
> Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
> modprobe: ERROR: could not insert 'fglrx': No such device
> Error: Fail to load fglrx kernel module!
> Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly

See https://travis-ci.org/boostorg/compute/jobs/151759262.

**Comment by BanzaiMan** [comment]
Thanks for the report. This issue is tracked in https://github.com/travis-ci/packer-templates/issues/221.
