### ISSUE TITLE
Multicast and `sudo: false`

### ISSUE THREAD

**Issue by sgraf812** [travis-ci/travis-ci#6487]
I have some acceptance tests using UDP Multicast in my test suite and have just figured out a reason why they don't seem to work: I had `sudo: false` in my `.travis.yml`. Switching that to `sudo: true` seems to work, is that intended?

[Note the difference in the output of `ifconfig`](https://travis-ci.org/sgraf812/travis-test/builds) of [this repo I made for reproduction purposes](https://github.com/sgraf812/travis-test).

**Comment by BanzaiMan** [comment]
With `sudo: false`, your job will be running on a Docker container hosted on an EC2 instance. This could mean that certain network capabilities are not present. (I believe UDP multicast is one such.)

**Comment by sgraf812** [comment]
Thanks for clarifying. So there is no way to even have some kind of pseudo multicast interface?

**Comment by BanzaiMan** [comment]
Maybe there is, if you have access to the EC2 instance itself, but the containers on which your builds run probably will not.
