### ISSUE TITLE
UI vague about OS

### ISSUE THREAD

**Issue by retrohacker** [travis-ci/travis-ci#6491]
When you are using a build matrix, the matrix has a nice icon showing you which OS was used for the build. I.E. https://travis-ci.org/retrohacker/peerweb-testing/builds/152567125

When you aren't using a matrix, the UI doesn't show the OS being used. In addition, for OSx builds, the build distribution is labeled as `precise` making it even more confusing. I.E. https://travis-ci.org/retrohacker/peerweb-testing/builds/152774145#L6

**Comment by BanzaiMan** [comment]
When there is only one job in the build matrix, we do not show the job matrix on the build page. There is no place for these values, which are uniquely defined in the build matrix.

The value "precise" appearing on an OS X job was reported in https://github.com/travis-ci/travis-ci/issues/6074, which was superseded by https://github.com/travis-ci/travis-ci/issues/6367.

Closing.

**Comment by retrohacker** [comment]
Thanks for the quick reply @BanzaiMan!

Would it not be possible to put them here? (with a matrix icon for a build matrix)

![drawing](https://cloud.githubusercontent.com/assets/1081565/17716656/a5e0f2e0-63d7-11e6-953a-350d16a63485.png)

Or here?

![drawing](https://cloud.githubusercontent.com/assets/1081565/17716719/e6c3ad16-63d7-11e6-93be-3b91d45dc7b4.png)
