### ISSUE TITLE
Failed builds due to missing env variable from the repository settings

### ISSUE THREAD

**Issue by tobilg** [travis-ci/travis-ci#6492]
My build is defined as

```
language: node_js

before_script:
  - env

node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "6"
```

which is nothing fancy. I also set the `FEBL_ACCESS_TOKEN` variable in the repository settings. In the build logs, I see the following error message:

```
Setting environment variables from repository settings
$ export FEBL_ACCESS_TOKEN=[secure]
/home/travis/build.sh: line 45: afcf05fe8dca812323768f7677b1fcda: command not found
```

and apparently the `FEBL_ACCESS_TOKEN` variable is not set successfully, because it isn't in the `env` output.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by tobilg** [comment]
@BanzaiMan Please have a look at https://travis-ci.org/tobilg/facebook-events-by-location-core/jobs/152902862

**Comment by BanzaiMan** [comment]
@tobilg Looks like your encryption was successful, but it starts with a space, which caused the `export` command to be written as:

```
export VAR=   YOUR_SECRET
```

which is a syntax error.

Try resetting the value without the spaces, or put it in quotes (if it is supposed to start with spaces).

**Comment by tobilg** [comment]
@BanzaiMan Is it possible that a contained pipe symbol could have triggered this? I guess I'd need to quote it then?

**Comment by tobilg** [comment]
It was in fact the missing quotes around the string with contained a pipe. Thanks for the help.
