### ISSUE TITLE
Single-element language version arrays passed as "[elem]" rather than "elem"

### ISSUE THREAD

**Issue by nabijaczleweli** [travis-ci/travis-ci#6493]
1. Explain, as detailed as possible, how to reproduce the issue.
Use `lang: [ver]` in `.travis.yml`, e.g.
```yaml
ruby:
  - 2.2
# or
rust:
  - stable
```

2. Include what you expected to happen, as well as what actually happened.
  * Expected:
     - During the language installation phase the following command(s) to be executed:
```yaml
rvm use 2.2 --install --binary --fuzzy
# or
sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=stable -y --disable-sudo 2> /dev/null
```
  * What actually happened:
    - During the language installation phase the following command(s) were executed, both of which fail to install either the required version (ruby) or at all (rust):
```yaml
rvm use [2.2] --install --binary --fuzzy
# or
sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=\[\"stable\"\] -y --disable-sudo 2> /dev/null
```

3. If it's a bug with the website, please include information on what browser version and operating system you are running.
N/A

4. If it helps, feel free to attach a screenshot or video illustrating the issue.
N/A

5. If you're having trouble with a specific build, please include a link to the build or job in question.
Include all this information in a new issue on our Issue Tracker
N/A

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by nabijaczleweli** [comment]
Ruby: https://travis-ci.org/nabijaczleweli/checksums/jobs/152901703#L135-L157
Rust: https://travis-ci.org/nabijaczleweli/checksums/jobs/152912168#L137-L146

**Comment by BanzaiMan** [comment]
Seems to be working now. https://travis-ci.org/nabijaczleweli/checksums/builds/153033570

**Comment by nabijaczleweli** [comment]
@BanzaiMan because I worked around it using:

```yaml
ruby: 2.2
rust: stable
# instead of
ruby:
  - 2.2
rust:
  - stable
```

So no, it does *not* work

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #6028.

**Comment by nabijaczleweli** [comment]
Yes, definitely. Somehow I didn't find that one when doing the cursory search,
