### ISSUE TITLE
../home/travis/build.sh: line 45:  3257 Segmentation fault      (core dumped) phpunit

### ISSUE THREAD

**Issue by nticaric** [travis-ci/travis-ci#6494]
Can someone help on this issue? PHPUnit seems to fail with

```
../home/travis/build.sh: line 45:  3257 Segmentation fault  (core dumped) phpunit
```

It only occurs on php7.1 job.

Here's the failing job https://travis-ci.org/teamtnt/tntsearch/jobs/152778563

**Comment by BanzaiMan** [comment]
Looks like a legitimate core dump to me.

We are bundling `phpunit` 5.5.0 (https://travis-ci.org/BanzaiMan/travis_production_test/builds/152951526#L151) with 7.1.0beta2, and without any other software, it runs fine. So it is either `phpunit` 5.5.1, or some extension you are loading.
