### ISSUE TITLE
OS X builds still stalling

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6500]
A couple days ago we started having issues with OS X builds on default images stalling. This [status]( https://www.traviscistatus.com/incidents/wrt4td1vc8k1 ) was opened that exactly described our issues. However, even though that problem is marked as resolved, we are still running into this issue. It seems a few builds in a matrix will stall. If they are stopped and restarted manually, we seem to be able to get them to start the next time relatively quickly. Still this seems to indicate this problem is still not completely resolved.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by jakirkham** [comment]
Sure that is a bit challenging to do as this is a bit sporadic at this point and there isn't much to see. However, this is a good [example]( https://travis-ci.org/conda-forge/staged-recipes/builds/153653714 ). Screenshot below. Note it has been waiting for ~1.5hrs.

<img width="1554" alt="screen shot 2016-08-19 at 17 04 51" src="https://cloud.githubusercontent.com/assets/3019665/17824294/146a9492-662f-11e6-9851-5af214cecb21.png">

**Comment by jakirkham** [comment]
Here is another [example]( https://travis-ci.org/conda-forge/staged-recipes/builds/153681826 ).

<img width="1554" alt="screen shot 2016-08-20 at 0 17 50" src="https://cloud.githubusercontent.com/assets/3019665/17828871/90a4acdc-666b-11e6-9b5f-955f1e7aa046.png">

**Comment by jakirkham** [comment]
I haven't seen this for some time. Guessing this was resolved by one of the rounds of maintenance. Will close out. If we do see this reoccur, will open a new issue. Thanks for your help.
