### ISSUE TITLE
Bioconductor R package suggested but not available

### ISSUE THREAD

**Issue by mplex** [travis-ci/travis-ci#6501]
Hi, I am trying to build an R package that suggests a Bioconductor package, and I get the following message:

`Package suggested but not available: ‘Rgraphviz’` 

My `.travis.yml` file has

    #bioc_packages:
    #   - Rgraphviz

But it still gives an error.

I appreciate any suggestions and thanks a lot in advance,
Antonio (github.com/mplex)

@craigcitro, @hadley and @jimhester

**Comment by jimhester** [comment]
`bioc_packages` is currently commented (https://github.com/mplex/multiplex/blob/master/.travis.yml#L5-L6), you need to uncomment it.

**Comment by mplex** [comment]
Thanks a lot. It works now. Best.
