### ISSUE TITLE
Django environment version 1.10.1 not available even though its out Python builds

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#6502]
Could not find a version that satisfies the requirement Django==1.10.1 (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.10a1, 1.10b1, 1.10rc1, 1.10)

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by Monkeyboy2805** [comment]
hold on

**Comment by Monkeyboy2805** [comment]
https://travis-ci.org/Monkeyboy2805/Lolex-Tools/builds/153279627 or https://travis-ci.org/Monkeyboy2805/Lolex-Tools/builds/153275279 or https://travis-ci.org/Monkeyboy2805/Lolex-Tools/builds/153272625. I cannot currently find out the exact url as my travis has kind of froze doing an insane test

**Comment by Monkeyboy2805** [comment]
Also get this error with 1.3 https://travis-ci.org/Monkeyboy2805/Lolex-Tools/jobs/153282951

**Comment by Monkeyboy2805** [comment]
and 1.2 and 1.1 and 1.0

**Comment by BanzaiMan** [comment]
How does `pip` discover available versions?

**Comment by joepvd** [comment]
Possibly versions `1.3` and older is not compatible with python3 (stable support is since `1.6`)

It does not look like a commit has been tagged as `1.10.1` on https://github.com/django/django:

```
% git tag -l '1.10*'
1.10
1.10a1
1.10b1
1.10rc1
```

Closing.

**Comment by Monkeyboy2805** [comment]
Is this fixed now because I have looked on the official django website

**Comment by BanzaiMan** [comment]
https://www.djangoproject.com/download/ still lists 1.10 as the latest version. https://docs.djangoproject.com/en/1.10/releases/1.10.1/ clearly states "under development", so I suggest you wait until it is officially tagged and released.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan thank you
