### ISSUE TITLE
Detect & use packrat when building R packages

### ISSUE THREAD

**Issue by benmarwick** [travis-ci/travis-ci#6504]
Migrating the thread at https://github.com/craigcitro/r-travis/issues/7#issuecomment-240875718 at the suggestion of @craigcitro: 

When we make an R project or R package we sometimes want to include the source files of the R packages we depend on, to prevent changes in other packages breaking our code. 

How can we configure travis to install these packages from the source included in the local project, rather than download from CRAN?

I'm working with an R package that is an RStudio project, and I'm using packrat to keep a local copy of the source of the packages I depend on for my project.

I've got Travis-CI checking my R package each time I make a commit, but each time Travis builds my package it gets the latest version of the dependent packages, rather than the versions I've got in my packrat/ directory.

I can see in @richfitz's [wood](https://github.com/richfitz/wood/) that he appears to have achieved this goal with this in his .travis.yml file:

```
env:
 USE_PACKRAT=1
```
and a fairly complex [make/packrat.mk](https://github.com/richfitz/wood/blob/master/make/packrat.mk) file which makes it all work.

My question is what is the simplest way to configure my project (e.g. my .travis.yml file) to tell the Travis machine to get the packages from my packrat/ directory on github, and not from CRAN?

I have cross-posted this question on [SO](http://stackoverflow.com/questions/39009579/using-r-package-source-files-in-packrat-rather-than-cran-with-travis-ci) and the [rOpenSci list](https://discuss.ropensci.org/t/reproducibility-in-r-package-building-with-travis-and-packrat/445)

**Comment by BanzaiMan** [comment]
Paging @travis-ci/r-maintainers

**Comment by benmarwick** [comment]
After much trial and error and further reading, it seems that this will do it, with a `.travis.yml` file like this:

    # R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
    
    language: R
    sudo: false
    cache: packages
    install:
      - R -e "0" --args --bootstrap-packrat
    warnings_are_errors: false

The key lines in the above file are:

    install:
      - R -e "0" --args --bootstrap-packrat

This will start R, and builds the R packages in the local packrat directory so that they are available in the Travis machine. 

After that, travis will continue and attempt to build the package, and will not need contact CRAN to get the dependencies because they are already available (assuming packrat is working as expected).

I discovered this trick here: https://travis-ci.org/ChowHub/paper-pattern-similarity/builds/127262823 and at https://github.com/rstudio/packrat/issues/158. I've got it working here: https://travis-ci.org/benmarwick/mjbtramp/builds/157747326

The **advantage** of this is we can build on travis with the exact same packages that we're using locally. We don't have to get the latest packages from CRAN when we build on travis, now we can have more control of the package versions that travis builds with in our project. 

The **disadvantage** is that the build time on travis is substantially increased. One of my projects went from 2-3 mins to 13-15 mins after switching to packrat. 

Cross-posted from my Q&A at http://stackoverflow.com/a/39338706/1036500

**Comment by jimhester** [comment]
Ben,

You can probably use caching
https://docs.travis-ci.com/user/speeding-up-the-build/#Caching-the-dependencies
of the packrat directory to speed up the build times.

**Comment by benmarwick** [comment]
Thanks, yes I was just looking at that. It seems I can cache the packrat packages using `cache` like this, to refer to my packrat sources:

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  directories: /home/travis/build/benmarwick/mjbtramp/packrat/lib/x86_64-pc-linux-gnu/3.3.1
  packages: true
install:
  - R -e "0" --args --bootstrap-packrat
warnings_are_errors: false

```

**Comment by craigcitro** [comment]
It would be awesome to get a pointer to a working packrat example in the official docs. (Do we have a cookbook/samples section in the docs? I think so but not looking at them right now.)

**Comment by benmarwick** [comment]
@craigcitro I'm happy to contribute to that (but not sure how to, do I sent some text by email to someone?)

**Comment by jimhester** [comment]
Just send a pull request with the example. File to edit is
https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/languages/r.md

On Sep 6, 2016 3:38 PM, "Ben Marwick" <notifications@github.com> wrote:

@craigcitro <https://github.com/craigcitro> I'm happy to contribute to that
(but not sure how to, do I sent some text by email to someone?)

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/travis-ci/travis-ci/issues/6504#issuecomment-245065082>,
or mute the thread

**Comment by maxheld83** [comment]
I've added the above recommended packrat-caching options, and noticed that Travis will *not* automatically invalidate/append the cache, if new package sources are added to `packrat.lock` and `packrat/scr/`.

Of course it's easy to fix this by just manually deleting the cache off of Travis, but it's also easy to forget this and be confused, especially for newbies.

Is there any chance an automatic travis cache invalidation for new packrat packages could be added?

Should I add this as a new issue?
