### ISSUE TITLE
Add support for emojis on travis-ci.org

### ISSUE THREAD

**Issue by zdroid** [travis-ci/travis-ci#6505]
Currently there is no support for emojis on travis-ci.org, they are displayed in their raw format (such as `:rocket:`). However, as the popularity and usage of emojis has risen to the level that we have plenty of emoji-related projects on GitHub, I think it's very significiant to have the emojis supported. You can see emojis being used on daily basis in repository names, commits and comments.

**Comment by zdroid** [comment]
@BanzaiMan Has this been fixed? I don't have a case to check it on.

**Comment by BanzaiMan** [comment]
Like this one? https://travis-ci.org/BanzaiMan/travis_production_test/builds/373070990 (See the commit data here: https://api.github.com/repos/BanzaiMan/travis_production_test/git/commits/20937b83f701250f943cb36cf2b4fff6b6500980)
