### ISSUE TITLE
Weird Oracle JDK 8, Gradle 14.0 build errors on Travis but not locally

### ISSUE THREAD

**Issue by aschrijver** [travis-ci/travis-ci#6507]
I just created a new Travis project and am experiencing weird compile + build errors with Oracle JDK 8 (both standard and latest version) and Gradle 14.0

This while local gradle build on Ubuntu 15 with exact same JDK and Gradle versions succeeds without a hitch.

The error details and links to build logs can be found in this issue: https://github.com/engagingspaces/vertx-dataloader/issues/2 which is also in the project where the problem occurs.

Did I overlook anything in Travis config?

**Comment by joepvd** [comment]
Have you tried to get more info as suggested by the output: `Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output`?

**Comment by aschrijver** [comment]
No, I followed log suggestion for the first error to add "-Xdiags:verbose" to `build.gradle` complier args, but that didn't help. Actually forgot to do the --info thing on the second error.

I will try to get some more diagnostics later today, or tomorrow (cause I didn't get any sleep overnight, and before you ask, it wasn't partying but open source work (which is just as fun, of course :wink: ))

Ideally somewhere Monday I want to release Vert.x DataLoader `1.0.0`, if I can manage.

**Comment by aschrijver** [comment]
Hi @joepvd ,

I created a Gist at https://gist.github.com/aschrijver/795b62fb5b16190bab0e2c7a3eda4f4f

It contains 3 files:
- One local build output with `--stacktrace` [succeeds]
- One TravisCI build output with `--stacktrace` [fails]
- One TravisCI build output with `--debug` [fails]

The local issue on [vertx-dataloader](https://github.com/engagingspaces/vertx-dataloader) project that refers to this is: https://github.com/engagingspaces/vertx-dataloader/issues/2

**Comment by aschrijver** [comment]
Gradle wrapper wasn't called appropriately. Closing. Thx for support!
