### ISSUE TITLE
Give more information when terminating a stalled build

### ISSUE THREAD

**Issue by petervo** [travis-ci/travis-ci#6512]
Would it be possible to output a ps -ef or something similar before terminating a stalled build with the error.

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

This would help with figuring out what could be causing the problem.

**Comment by BanzaiMan** [comment]
Duplicate of #5771 (and perhaps others as well).

**Comment by BanzaiMan** [comment]
And #4221.
