### ISSUE TITLE
travis_wait seems to cause a failure in the build

### ISSUE THREAD

**Issue by JieGhost** [travis-ci/travis-ci#6513]
Hi,
I saw a weird failure after I add travis_wait in .travis.yml.
https://travis-ci.org/pantsbuild/pants/jobs/154141668.
It failed inside a python library. The reason of failure is a function "_sleep" is reassigned as an int. 
Note this is an official python module, so I don't think the error comes from the code. Plus, without travis_wait, it won't fail. It only fails when I add travis_wait.

I cannot figure out why a bash script can interfere with a variable inside python library.
Does anyone have any clues or theories?

Thank you very much!

**Comment by BanzaiMan** [comment]
`travis_wait` is a bash function, so I fail to see how it can interfere with Python methods. It is also curious that, out of 10 jobs in https://travis-ci.org/pantsbuild/pants/builds/154141666, only one exhibited this problem. Could it be a real threading problem?

**Comment by BanzaiMan** [comment]
Is this still an issue?

**Comment by JieGhost** [comment]
Hi,
we came up with a workaround that does not require travis_wait, thus we didn't spend time investigating on this issue any more. I think I will close it.
Thanks for your follow up!
