### ISSUE TITLE
OS X Backlog

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6515]
It seems that the OS X build queue is pretty backlogged. Looks like they have maxed out constantly with 164 workers occupied for over 9hrs. Though realistically this has been going on closer to 14hrs (with very small rare interruptions). We have several builds on our own queue that have been waiting most of the day to run. Is there some sort of larger issue going on? Could it be related to issue ( https://github.com/travis-ci/travis-ci/issues/6500 )? Or is there some other new issue cropping up?

<img width="1554" alt="screen shot 2016-08-23 at 21 46 36" src="https://cloud.githubusercontent.com/assets/3019665/17915764/1f42750c-697b-11e6-90db-9c3bdd8c3e37.png">

**Comment by jakirkham** [comment]
This improved briefly overnight, but is now occurring again. See screenshot below.

<img width="1554" alt="screen shot 2016-08-24 at 14 47 47" src="https://cloud.githubusercontent.com/assets/3019665/17943537/d4e980a6-6a09-11e6-8898-5e551a8c9093.png">

**Comment by BanzaiMan** [comment]
This is a general issue we are tracking on with https://www.traviscistatus.com/incidents/4mvp857qx8bw. Please subscribe to that issue.

**Comment by jakirkham** [comment]
Am subscribed. Thanks for the update.
