### ISSUE TITLE
The RSS feed for environment updates uses relative URLs

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#6516]
The RSS feed uses URLs like ``/user/build-environment-updates/2016-08-24/``, which don't work fine. It should use the absolute URL

**Comment by clekstro** [comment]
Based on our docs, it seems that the Atom feeds are produced directly within the API. Not sure if this is really an issue or not, but not a web issue from what I can tell.

**Comment by stof** [comment]
The URL of the feed makes me think that the doc is actually responsible for it, as it lives at http://docs.travis-ci.com/feed.build-env-updates.xml
