### ISSUE TITLE
refine branch ordering, and put old branches under a toggle

### ISSUE THREAD

**Issue by jab** [travis-ci/travis-ci#6518]
Looking at a page like https://travis-ci.org/jab/bidict/branches, the branches listed under "Active" and "Inactive Branches" are ordered most-recently-to-least-recently-built, as desired, **except** for branches with a build currently in progress, which are listed last. I think branches with a build currently in progress should instead be listed first.

It also would be nice if both inactive branches, as well as active branches that haven't been built in (say) over 1 month, were not shown by default, but could be easily toggled to appear.

Thanks for your consideration and for the great work on Travis!

**Comment by jab** [comment]
This is still an issue.

**Comment by jab** [comment]
This is still an issue.

**Comment by jab** [comment]
This is still an issue.

**Comment by jab** [comment]
@BanzaiMan Any way to get the stale bot to back off this issue, if it's still in the running for fixing? Thanks.

**Comment by jesskie** [comment]
Don't hide in a mirror

jess
