### ISSUE TITLE
The command "~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm" failed and exited with 78 during.

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [travis-ci/travis-ci#6521]
> Travis CI build log: https://travis-ci.org/LobbyOS/lobby/jobs/154797953

 - Tutorial / Docs: https://docs.travis-ci.com/user/languages/php#Apache-%2B-PHP
 - Travis CI file: https://github.com/LobbyOS/lobby/blob/travis/.travis.yml

Error output:
```travis
sudo apt-get update
sudo apt-get install apache2 libapache2-mod-fastcgi
sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
sudo a2enmod rewrite actions fastcgi alias
echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
sudo service apache2 restart

The command "~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm" failed and exited with 78 during .
```

What should I do?

**Comment by BanzaiMan** [comment]
https://travis-ci.org/LobbyOS/lobby/jobs/154797953#L407-L410

Looks like your configuration is invalid.

```
[24-Aug-2016 16:03:15] WARNING: Nothing matches the include pattern '/home/travis/.phpenv/versions/7.0.10/etc/php-fpm.d/*.conf' from /home/travis/.phpenv/versions/7.0.10/etc/php-fpm.conf at line 125.
[24-Aug-2016 16:03:15] ERROR: No pool defined. at least one pool section must be specified in config file
[24-Aug-2016 16:03:15] ERROR: failed to post process the configuration
[24-Aug-2016 16:03:15] ERROR: FPM initialization failed
```

**Comment by SuriyaaKudoIsc** [comment]
@BanzaiMan How can I configure `.travis.yml` correctly?

**Comment by BanzaiMan** [comment]
I'm not talking about `.travis.yml`. Your PHP configuration seems wrong. https://www.google.com/search?q=php+No+pool+defined.+at+least+one+pool+section+must+be+specified+in+config+file&oq=php+No+pool+defined.+at+least+one+pool+section+must+be+specified+in+config+file&aqs=chrome..69i57j69i64l2.1159j0j4&sourceid=chrome&ie=UTF-8

**Comment by joepvd** [comment]
Closing this. Please reopen if you can provide some pointers that there would be something wrong on Travis' side.

**Comment by romainnorberg** [comment]
@SuriyaaKudoIsc this can help you: https://www.marcus-povey.co.uk/2016/02/16/travisci-with-php-7-on-apache-php-fpm/
