### ISSUE TITLE
New Mac OS build error since the recent outage: "/Users/travis/build.sh: line 109: shell_session_update: command not found error"

### ISSUE THREAD

**Issue by emaloney** [travis-ci/travis-ci#6522]
Since [the recent Travis outage for Mac OS-based builds](https://www.traviscistatus.com/incidents/4mvp857qx8bw), my previously-succeeding builds are now failing with a new error:

```
/Users/travis/build.sh: line 109: shell_session_update: command not found
```

This error occurs despite the build otherwise appearing to succeed. Aside from the error above, the last lines of the build are:

```
▸ Build Succeeded
The command "xcodebuild -project CleanroomLogger.xcodeproj -scheme CleanroomLogger-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty" exited with 0.
Done. Your build exited with 0.
```

The build config is:

``` json
{
  "language": "objective-c",
  "xcode_project": "CleanroomLogger.xcodeproj",
  "osx_image": "xcode7.3",
  "install": "gem install xcpretty",
  "script": [
    "xcodebuild -project CleanroomLogger.xcodeproj -scheme CleanroomLogger-iOS -destination 'platform=iOS Simulator,OS=9.3,name=iPhone 6' clean build CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO | xcpretty",
    "xcodebuild -project CleanroomLogger.xcodeproj -scheme CleanroomLogger-OSX -destination 'platform=OS X' clean build CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO | xcpretty",
    "xcodebuild -project CleanroomLogger.xcodeproj -scheme CleanroomLogger-tvOS -destination 'platform=tvOS Simulator,OS=9.2,name=Apple TV 1080p' clean build CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO | xcpretty",
    "xcodebuild -project CleanroomLogger.xcodeproj -scheme CleanroomLogger-watchOS -destination 'platform=watchOS Simulator,OS=2.2,name=Apple Watch - 42mm' clean build CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO | xcpretty"
  ],
  "group": "stable",
  "dist": "osx",
  "os": "osx"
}
```

I've been experiencing this on multiple repos with multiple branches. One such "failed" build [is here](https://travis-ci.org/emaloney/CleanroomLogger/jobs/154935650).

Please let me know if there's any additional information I can provide that would be helpful.

Thanks a lot,
E.

**Comment by BanzaiMan** [comment]
This should be a duplicate of #6307. You see the same error message in https://travis-ci.org/emaloney/CleanroomLogger/builds/154582705#L379 without any ill side effect.

It is rather odd that the build is getting marked an error, though.

**Comment by phatmann** [comment]
My builds are all failing due to this error.

**Comment by phatmann** [comment]
Seems to be fixed now.

**Comment by springmeyer** [comment]
Still happening for me: https://travis-ci.org/Project-OSRM/node-osrm/jobs/163273079.

> It is rather odd that the build is getting marked an error, though.

@BanzaiMan it seems to break scripts that use `source` in particular.

**Comment by BanzaiMan** [comment]
@springmeyer Your script is sourcing script that sets `errexit` option (https://github.com/Project-OSRM/node-osrm/blob/4e40407e0c088d68ca3c2b9489ce1e48f8d17f50/scripts/setup_mason.sh#L3), so it'll halt the build's execution when any command exits with nonzero status.

**Comment by BanzaiMan** [comment]
@springmeyer I see that the build is a little more complicated than that, but the general idea should still hold. The function should be benign; something else is failing with nonzero status and terminating the build.

**Comment by schwa** [comment]
I'm getting the same error on a very simple build script: 

https://travis-ci.org/schwa/SwiftIO/builds/164488634

```
language: objective-c
osx_image: xcode8
before_script:
- carthage bootstrap --no-use-binaries
script:
- xcodebuild -project SwiftIO.xcodeproj -scheme SwiftIO_iOS -sdk iphonesimulator build
- xcodebuild -project SwiftIO.xcodeproj -scheme SwiftIO_OSX build
- xcodebuild -project SwiftIO.xcodeproj -scheme TestApp build
```

**Comment by springmeyer** [comment]
> so it'll halt the build's execution when any command exits with nonzero status.

@BanzaiMan - that is intentional. I need to halt the build on errors in my scripts. I agree with you that without that `set -e` the build would continue past the `shell_session_update` error, but I can't let other errors happen silently so I need the `set -e`. I worked around this by doing https://github.com/Project-OSRM/node-osrm/commit/cdb5b6c020fcc779da42d2f4234715adb86dc107 and now builds are working fine.

**Comment by jakirkham** [comment]
Seeing this in [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/165091878#L384 )

**Comment by matthew-brett** [comment]
From the fix by @springmeyer:

```
rvm get head || true
```

This looks to be a similar problem to that reported previously at https://github.com/direnv/direnv/issues/210

Would it be reasonable to add ``rvm get head`` or similar to the OSX 7.3 image?

**Comment by jakirkham** [comment]
Wait, it appears the default OS X image has changed from 10.9 to 10.11! Did I miss an announcement somewhere? Can we switch back to 10.9 somehow?

**Comment by matthew-brett** [comment]
@jakirkham - you could try `osx_image: xcode6.4` - that switched the image back for us : https://github.com/travis-ci/travis-ci/issues/6677

**Comment by jakirkham** [comment]
I think we were using XCode 6.1 before; so, am trying `osx_image: xcode6.1`. However, it seems we have a bit of a backlog ATM. Thanks for the suggestion and info.

**Comment by jakirkham** [comment]
So tried forcing `osx_image: xcode6.1`, but it seems this [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/165295938#L4 ) doesn't respect it. The [docs]( https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version ) seem to show that one needs `osx_image: beta-xcode6.1`. However, other users [use this setting]( https://github.com/tombenner/nui/blob/a0850217854dac29c12740f6349c0d4dfee00b53/.travis.yml#L8 ) and have [builds]( https://travis-ci.org/tombenner/nui/jobs/158672422#L4 ) with the correct image. Any reason why this doesn't work? What do we have to set in order to return to the OS X 10.9 XCode 6.1 image we were using? This is causing havoc for our deployments.

**Comment by gappleto97** [comment]
I'm also seeing this as of about a week ago.

**Comment by wsfulton** [comment]
Same problem here for all our builds since the upgrade to xcode 7.3, for example: https://travis-ci.org/swig/swig/jobs/167560225. Adding a `set +e` at the end of the script that has `set -e` is our workaround as the main purpose of setting errexit in our case is to catch errors in the script.

**Comment by CamJN** [comment]
I see this when sourcing `/Users/travis/.rvm/scripts/rvm`

**Comment by BorzdeG** [comment]
actual: https://travis-ci.org/itbasis/jvm-wrapper/jobs/366111718#L2494

**Comment by jakirkham** [comment]
AFAICT this is still an issue.

**Comment by Croydon** [comment]
I just run into this for the first time. Seems like an evergreen bug.
