### ISSUE TITLE
Github hook is sent after after_success

### ISSUE THREAD

**Issue by yilinwei** [travis-ci/travis-ci#6523]
Hi,

We have a project which runs benchmarks and have put the benchmarks to run in the [.travis](https://github.com/functional-streams-for-scala/fs2/pull/695/files) file to `after_success`. This sort of works, because the success of the build isn't determined by the outcome of the benchmark, but the github hook only gets updated after the benchmarks have run.

Should the github hook not update before running `after_success`?

**Comment by BanzaiMan** [comment]
`after_success` fires during the build, but the status is not updated until the build completes.

If you need the build status to report, then you need to use a notification, most notably [webhook](https://docs.travis-ci.com/user/notifications/#Configuring-webhook-notifications).
