### ISSUE TITLE
Disk space to small in mono VM

### ISSUE THREAD

**Issue by forki** [travis-ci/travis-ci#6524]
My project https://github.com/fsprojects/Paket is a .NET dependency manager and has a huge integration test suite. As part of this test suite we try to download and install lots and lots of different dependency trees. We now hit the limit of the VM disk size (see https://travis-ci.org/fsprojects/Paket/builds/155117469)

Is there a chance that we can increase it?

cc @joshua-anderson @akoeplinger @nterry @tforkmann

**Comment by rkh** [comment]
We currently can't offer larger VMs for technical reasons, so even if we wanted to, it would require engineering work from our side.

It would be interesting to know what's using up all the space, afaik machines should have a 30 GB disk each.

**Comment by forki** [comment]
for our project it's expected to consume large amount of disk space since we download/cache A LOT of the existing nuget packages in our integration tests. 

Anyways I do understand the technical issues that are related to increasing VM size, so I added a hack that will [free some space after 10 scenearios](https://github.com/fsprojects/Paket/commit/d4470788a4be14283b21ef5b39a1cabbe5274bd3). This will at least buy us some time.

When we hit the limit again, then it's because the cache is too large. Then I will need to free some cache space from time to time as well. This will make the integration test suite run slower, but hey it's a tradeoff.

Anyways thanks for your response.
