### ISSUE TITLE
Support for Python 2.7.3

### ISSUE THREAD

**Issue by defnull** [travis-ci/travis-ci#6525]
Ubuntu precise (12.4LTS) ships with Python 2.7.3 and is still supported until 26. April 2017. It would be nice if this specific python release would be testable with travis.

    language: python
    python:
        - "2.7.6" # works
        - "2.7.3" # does not work

    2.7.3 is not installed; attempting download
    bzip2: (stdin) is not a bzip2 file.
    tar: Child returned status 2
    tar: Error is not recoverable: exiting now

**Comment by oz123** [comment]
Yep, it would be a great thing to be able to choose minor versions of Python. Other CI systems enable this very easily (for example CircleCI).

**Comment by BanzaiMan** [comment]
This is available now. https://travis-ci.org/travis-ci/cpython-builder/builds/155325759

Do keep in mind that, while the version number matches up, the configuration options and available packages may differ from the one that is offered by the system's Python 2.7.3.
