### ISSUE TITLE
WARNING: We were unable to find a .travis.yml file.  Could not find .travis.yml, using standard configuration.

### ISSUE THREAD

**Issue by jaimejim** [travis-ci/travis-ci#6526]
This is the error <https://travis-ci.org/jaimejim/jaimejim.github.io/>:

![screen shot 2016-08-26 at 14 47 23](https://cloud.githubusercontent.com/assets/1798358/18004356/09962a96-6b9c-11e6-9868-9c469961125e.png)

I have checked other issues under the same topic, namely #3052,  #3334 and #3751: 
**WARNING: We were unable to find a .travis.yml file.**  

I believe that this is might be a different issue as:
- .travis.yml is in the root directory and *seems* correct to me, I have tried multiple combinations. 
- travis lint output is valid too: 

```  bash
jaime@Jaimes-MacBook-Pro:~/code/jaimejim.github.io$ travis lint .travis.yml 
Hooray, .travis.yml looks valid :)
``` 
- Multiple commits did not fix the problem.
- I have not changed the repository name.
- I have used travis in other repos and it works fine, in fact I love it, thanks for the work!

**Comment by BanzaiMan** [comment]
The commit corresponding to [the only build](https://travis-ci.org/jaimejim/jaimejim.github.io/builds/154680300) is https://github.com/jaimejim/jaimejim.github.io/tree/eb32d5b987414f8529e5c600cce815ce04b7d4d7, which indeed lacks `.travis.yml`. If you have this file locally, perhaps you forgot to commit it to the repository.

**Comment by jaimejim** [comment]
Hi @BanzaiMan ,

I see now that I had wrong settings for the build all along...

![screen shot 2016-08-29 at 16 39 58](https://cloud.githubusercontent.com/assets/1798358/18053286/55a835a6-6e07-11e6-8c5f-109ad6b766cf.png)

 After enabling "Build pushes" things work. Silly mistake, thanks for the feedback. 

![screen shot 2016-08-29 at 16 41 32](https://cloud.githubusercontent.com/assets/1798358/18053361/a6ce9ee8-6e07-11e6-8340-c2689a133692.png)
