### ISSUE TITLE
sudo: required is ignored

### ISSUE THREAD

**Issue by rscohn2** [travis-ci/travis-ci#6533]
Was working a few hours ago, but not now. I tried pushing a new commit:

https://travis-ci.org/rscohn2/bench-linux-python-docker

This is the code:
https://github.com/rscohn2/bench-linux-python-docker

**Comment by BanzaiMan** [comment]
A most likely explanation is that we failed to fetch `.travis.yml` for some reason. https://travis-ci.org/rscohn2/bench-linux-python-docker/jobs/155762172/config shows the default configuration (`language: ruby`, etc.).`

Could you try resyncing your data (https://travis-ci.org/profile/rscohn2) and push a new commit?

**Comment by rscohn2** [comment]
That fixes it. Thanks.
