### ISSUE TITLE
Passing build now marked as failing

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6538]
This [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/156080039 ) passed and was marked as passing earlier. However it has now been marked as a failure. In the interim, this build has not been re-run since it passed previously.

Interestingly its log is reminiscent of issue ( https://github.com/travis-ci/travis-ci/issues/5334 ).

**Comment by joepvd** [comment]
Get the impression that this job ran twice on two different VMs at the same time. There recently was a fix that addresses a possible cause, we assume that this should not happen again. Please open a new ticket when you would encounter a similar situation.
