### ISSUE TITLE
Allow to use Nightly or DevEdition of Firefox for testing

### ISSUE THREAD

**Issue by SebastianZ** [travis-ci/travis-ci#6543]
Sometimes it makes sense to test against unstable versions of Firefox, i.e. Developer Edition (aka Aurora) or Nightly, like testing unsigned Firefox add-ons (see also issue #4064).

Therefore those versions should be made available via the [Travis CI Firefox add-on](https://docs.travis-ci.com/user/firefox/).

Sebastian

**Comment by mthamil** [comment]
I had this issue as well, and so I've added the following in my travis config so that I can run tests for unsigned versions of my addon:
```yaml
before_install:
- export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=linux64&lang=en-US'
- wget -O /tmp/firefox-aurora-latest.tar.bz2 $FIREFOX_SOURCE_URL
- tar -xjf /tmp/firefox-aurora-latest.tar.bz2
- export JPM_FIREFOX_BINARY=$PWD/firefox/firefox
- sh -e /etc/init.d/xvfb start

**Comment by BanzaiMan** [comment]
#6755 supersedes this, and it is resolved.
