### ISSUE TITLE
Coverity Scan addon is not passed value of variables

### ISSUE THREAD

**Issue by jodh-intel** [travis-ci/travis-ci#6544]
The Coverity Scan addon makes use of a script that is downloaded from the coverity website [1]. This script accepts a number of variables, one of which is `COVERITY_SCAN_NOTIFICATION_EMAIL` (again, this can be seen in the Travis log).

However, I cannot seem to get Travis to pass the value of this variable to the Coverity script - the Travis log shows the variable is set correctly, but at the end of the build when the addon is called, the value of `COVERITY_SCAN_NOTIFICATION_EMAIL=""`. For an example, see:

- https://s3.amazonaws.com/archive.travis-ci.org/jobs/156247932/log.txt

The only way to pass the notification to `coverity_scan` seems to be via `addons.coverity_scan.notification_email`.

Is this by design (no global variables allowed to be passed to addons maybe?) or is it a buglet?
____

[1] - https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh

**Comment by BanzaiMan** [comment]
Are these values *documented* anywhere? I know these are accessible in the script, but the current documentation of our coverity scan support is https://docs.travis-ci.com/user/coverity-scan/#travis.yml, which asks you to set these values in `.travis.yml`.

I am inclined to say this is by current design.

I think overriding it with settings might be a good idea, though.

**Comment by BanzaiMan** [comment]
See the https://docs.travis-ci.com/user/coverity-scan/#Environment-Variables.
