### ISSUE TITLE
fatal: destination path 'xxxx' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by valentyp** [travis-ci/travis-ci#6545]
I used this command twice, but after the second time I have received this message. How to fix it ???

**Comment by BanzaiMan** [comment]
Duplicate of #2715.

**Comment by osunkoyadavid** [comment]
Getting the same error

**Comment by osunkoyadavid** [comment]
when i run: git clone -b beta https://github.com/flutter/flutter.git, it shows the error below
fatal: destination path 'flutter' already exists and is not an empty directory.
