### ISSUE TITLE
Deploying to GitHub fails with "invalid option --api_key="

### ISSUE THREAD

**Issue by arekkas** [travis-ci/travis-ci#6549]
This is my config: https://github.com/ory-am/hydra/blob/master/.travis.yml#L40

The deploy command fails with `invalid option "--api_key="`: https://travis-ci.org/ory-am/hydra/jobs/156946056#L2065

What am I doing wrong? I tried several options for the API key value, like `${GITHUB_TOKEN}`, `$GITHUB_TOKEN`, `"$GITHUB_TOKEN"` and none of them worked

**Comment by BanzaiMan** [comment]
@arekkas Your token was incorrectly encrypted. https://travis-ci.org/ory-am/hydra/jobs/156946056#L247 I urge you to revoke this token ASAP, and generate a new one. Be sure to not have any space before the token when you define the variable on the settings panel.

**Comment by arekkas** [comment]
Oh shit. Thank you

Gesendet mit meinem HTC

----- Reply message -----
Von: "Hiro Asari" <notifications@github.com>
An: "travis-ci/travis-ci" <travis-ci@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Mention" <mention@noreply.github.com>
Betreff: [travis-ci/travis-ci] Deploying to GitHub fails with "invalid option --api_key=" (#6549)
Datum: Fr., Sep. 2, 2016 13:57

@arekkas Your token was incorrectly encrypted. https://travis-ci.org/ory-am/hydra/jobs/156946056#L247 I urge you to revoke this token ASAP, and generate a new one. Be sure to not have any space before the token when you define the variable on the settings panel.

**Comment by arekkas** [comment]
So @BanzaiMan thanks again for the hint. It would be awesome if you could, next time, hint people privately on security breaches like that. I was in a lot of stress revoking the token on my mobile, as this is a well known repo and people look into issues all the time. :)

**Comment by ambroiseRabier** [comment]
Making this comment for other people that will google search this error: If you are deploying on tag only, also check that your env variable is available to the current branch, I had set my key, to only appear master branch in Travis settings...

**Comment by Fedcomp** [comment]
@ambroiseRabier did you manage to make tag releases without encrypted key in config? i want to use ENV variables i setup in travis web, not adding junk to my repository.

**Comment by ambroiseRabier** [comment]
@Fedcomp I do not understand what you mean, here is my config:

```yml
language: node_js

cache: npm

node_js:
  - stable

install:
  - npm ci

script:
  - npm run build-linux
  - npm run test

after_script:
  - npm run ci-process-cover

deploy:
  provider: npm
  email: $NPM_PUBLIC_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
```

The env variable have been set in Travis (web). There is an option to limit variables to a specific branch, I had limited my variables to master branch. But tags behave like branch in git, basically never setting my variable on any tag branch. I might not have much in common with original issue though :/ .
