### ISSUE TITLE
"Current" build shows status of latest PR build instead of latest master build

### ISSUE THREAD

**Issue by bensie** [travis-ci/travis-ci#655]
It seems odd that if someone goes to see the build status at the root of the project they see the potentially failed build of a random PR. Unmerged PRs may never make their way into a project and should not be considered part of the project's build in the "Current" tab.

**Comment by coderanger** [comment]
Seeing this currently: http://i.coderanger.net/F2M2H.png shows the last master branch build was successful. Most recent build was for a PR (build #17 http://i.coderanger.net/s5V9d.png) and the badge image shows failed (http://i.coderanger.net/1jU70.png).

**Comment by coderanger** [comment]
Is the closed because it is fixed?

**Comment by bensie** [comment]
No, it just cluttered my list of open issues on GitHub and is 4 years old. If someone really wants to push for it I suppose they could open another issue.

**Comment by coderanger** [comment]
Er, that's not how tickets work. Can someone from Travis please re-open this until it actually gets fixed?

**Comment by coderanger** [comment]
@bensie If you want to unsubscribe from updates you can do that in the top-right.

**Comment by bensie** [comment]
@coderanger Did that. GitHub still shows open issues you've created.

![image](https://cloud.githubusercontent.com/assets/4595/16780115/0e1e49da-482a-11e6-805d-b438c88e3f91.png)

I don't even know if it's still an issue, I really don't use Travis much anymore and certainly don't see a need to have this staring me in the face every day as I work through issues/PRs. If you feel that strongly about it and can verify that it's still an issue 4 years later, open a new issue and reference this one.
