### ISSUE TITLE
Travis doesn't support running node with --harmony-proxies flag

### ISSUE THREAD

**Issue by colbycheeze** [travis-ci/travis-ci#6551]
This makes it impossible to run with my build as I get this:
```
to be executed: node_modules/.bin/nyc node --harmony_proxies ./node_modules/.bin/ava 
/home/travis/.nvm/versions/node/v6.5.0/bin/node: bad option: --harmony_proxies
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by colbycheeze** [comment]
Alright so we figured it out...I don't know if it should be an issue here or with a diff project. The problem is with Node 6.5.

The flag works all the way up to Node 6.3 at least.

https://travis-ci.org/IBM-Bluemix/logistics-wizard-webui/builds/156878342

**Comment by BanzaiMan** [comment]
Looks like a Node.js issue, then. Please report the issue with them.

```sh-session
$ node --version                  
v6.5.0
$ node --harmony_proxies          
node: bad option: --harmony_proxies
$ nvm use 6.4
Now using node v6.4.0 (npm v3.10.3)
$ node --version        
v6.4.0
$ node --harmony_proxies
> 
```
