### ISSUE TITLE
Updating the NPM version on a PHP VM

### ISSUE THREAD

**Issue by hohl** [travis-ci/travis-ci#6554]
I'd like to run some `gulp` scripts for preparing the assets of a PHP project. Is there any chance to update the NPM version on the Travis-CI PHP image? The preinstalled Node uses something like `0.10` but we are now at `4.5` (considering the latest LTS).

**Comment by BanzaiMan** [comment]
Use `nvm` to update Node.js, and update npm if necessary.

```yaml
before_install:
  - nvm isntall stable # or 5, 6, or whatever
  - npm update -g npm # if necessary
```

**Comment by hohl** [comment]
Tried to update NPM via `npm update -g npm` but it failed. I'm sorry, totally forgot to update `node` too.
