### ISSUE TITLE
allow_failures with multiple conditions?

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#6558]
If I want to include build matrix entries containing multiple conditions I can do this like this:

    matrix:
      include:
        # httpd-based
        - php: 5.4
          env: DB=mysql TEST_COMPONENT=HTTPD

Similarly though, I cannot use the mechanism to allow failures. This does not work:

      allow_failures:
        - php: 5.4
          env: DB=mysql TEST_ADAPTER=HTTP

Please document how to allow failures depending on multiple build conditions.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by andig** [comment]
> Do you have a build log URL that shows the problem you are describing here?

See this build job specifically https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/155869739 which should be allowed to fail according to https://github.com/volkszaehler/volkszaehler.org/pull/458/files#diff-354f30a63fb0907d4ad57269548329e3R54

**Comment by BanzaiMan** [comment]
Do you mean `TEST_COMPONENT=HTTPD` or `TEST_COMPONENT=HTTP`?
