### ISSUE TITLE
Add ability to conditionally make build logs private

### ISSUE THREAD

**Issue by gajus** [travis-ci/travis-ci#6559]
I have leaked my private tokens too many times, sometimes without even realising it.

I'd like to see an option to make certain build logs private, i.e. that only the admin is able to see those logs.

**Comment by dentarg** [comment]
Here's my use case for private build logs (or be able to have the Travis CI page completely private (we pay for travis-ci.com) but for a public GitHub repo).

Using the Travis Cron feature, we have a repo setup to run a script every day queries the GitHub API to get a list of all of our repos that have a `Gemfile.lock` in the root. We then use [myrepos](https://myrepos.branchable.com/) to efficiently clone these repos and run bundle-audit on each repo.

If the build fails, some repo has a security vulnerability we should address.

The code for doing this has no secrets (the GitHub API token in `.travis.yml` is encrypted), but we would like to still keep the build logs private, in case we are not able to respond to a security vulnerability immediately.

**Comment by dentarg** [comment]
I don’t think this has been solved

**Comment by yasseridris** [comment]
I have a similar use case. Public repo, but need the logs to be private.. Any way to do this ?

**Comment by gajus** [comment]
I stopped using Travis. Feel free to takeover whoever needs this.
