### ISSUE TITLE
Fail hard when timings go above 24 hours

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#6561]
Doing some tests, I found that apparently this build has been running for 10hrs:https://travis-ci.org/Monkeyboy2805/Lolex-Tools/builds/156282461 when I have these settings:
![image](https://cloud.githubusercontent.com/assets/20478546/18247887/49d0febe-736d-11e6-891a-dc85ca851597.png)

**Comment by BanzaiMan** [comment]
There are 560 jobs in this build matrix. They take turns running, and each jobs take a while to run, so I certainly expect your build to run for a long time.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan I am aware but I ran that test just to see what would happen above 24 hours and it was saying my buildhad been running for 10 hours. I did not start it ten hours before that point.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan as regards to #6502 how did you actually get hold of the 1.10 pre releases?

**Comment by Monkeyboy2805** [comment]
@BanzaiMan what is the maximum concurrent jobs you can run?

**Comment by BanzaiMan** [comment]
> …it was saying my build had been running for 10 hours. I did not start it ten hours before that point.

When did you observe this on which build? Did you refresh the page?

> as regards to #6502 how did you actually get hold of the 1.10 pre releases?

I don't know. I am not an expert on Django or Python. (Besides, the issue is most certainly unrelated to this one.)

> what is the maximum concurrent jobs you can run?

5 for your account.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan Thanks, and it was about two days after the build was started. It happened on the website on my Asus Nexus 7 2012 and on Windows 10 in Google Chrome.

**Comment by BanzaiMan** [comment]
Could it be that it was 2 days and 10 hours since the build had started?

**Comment by Monkeyboy2805** [comment]
@BanzaiMan  quite possibly but I don't tend to keep a exact track of these things. all I knew was that I had had that build running for more than 24 hours and it was saying 10 hours. Do you wish for me to run another build so you can see if it happens for you? I have switched repos to an org now, so the build errored about half of them when I deleted the repository.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan This is not a major issue so I will close it for now to clear the issue tracker slightly
