### ISSUE TITLE
Travis-CI kernel incompatibility with mono

### ISSUE THREAD

**Issue by splitice** [travis-ci/travis-ci#6565]
The kernels of both the trusty and precise images do not contain a bug that fixes a major incompatibility with something used in mono's semaphores / multi-threading. This leads to frequent segfaults and issues in multithreaded applications.

Bug details:
- https://bugzilla.xamarin.com/show_bug.cgi?id=29827
- https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1450584

Solution, newer kernel / kernel upgrade.

@joshua-anderson @akoeplinger @nterry

**Comment by Joshua-Anderson** [comment]
Not sure there is anything we can do about this. Travis CI has to update the base image. I thought that the trusty base images were rebuilt recently though, so they should be up to date with the kernel relewsed to trusty at least.

**Comment by splitice** [comment]
Here is a precise & trusty build with the issue:

 - https://travis-ci.org/splitice/SimpleChannel.Net/builds/157785408#L1309
 - https://travis-ci.org/splitice/SimpleChannel.Net/builds/157779444#L1728

Yes, the base image would need to be updated (I am aware thats not you, but mono looks to primarily be the platform affected by the SMP kernel bug)

Its being created by a very simple method:

```
        [TestCase]
        public void TestZmqPutTake()
        {
            ZeroMqQueueChannel<TestModel> qcOut, qcIn;
            SetupConnecitons(out qcOut, out qcIn, 1112);

            TestModel model;
            var task = Task.Run(() => model = qcIn.Take());

            qcOut.Put(new TestModel());

            Assert.IsTrue(task.Wait(1000));

            qcOut.Dispose();
            qcIn.Dispose();
        }
```

Calling Task.Wait results in a native semaphore wait, which causes the native segfault due to assertion.
