### ISSUE TITLE
Can't see new repo.

### ISSUE THREAD

**Issue by aug24** [travis-ci/travis-ci#6570]
I've created a new repo called 'de-haro-camera' in the ConnectedHomes github repo, but it doesn't show up when I synchronise repos, so I can't turn the build on.  Have I missed something?

**Comment by BanzaiMan** [comment]
@aug24 Your user data had not been synced since this new repository was created an hour ago. I manually resynced the data for you, and you should see it now.

**Comment by aug24** [comment]
Hmmm... I had hit the re-sync button many many times.

**Comment by PercussiveRepair** [comment]
Re-sync fails to work for me too. "Sorry, it seems like we couldn't find any repositories you have access to on GitHub."

**Comment by Monkeyboy2805** [comment]
@PercussiveRepair How many projects do you have!?

**Comment by aug24** [comment]
I'm missing something still.  I can see the builds taking place, but I still don't see the project in the ConnectedHomes profile: https://travis-ci.com/profile/ConnectedHomes

**Comment by PercussiveRepair** [comment]
I'm an admin on our org, so _a lot_ :)

**Comment by Monkeyboy2805** [comment]
@PercussiveRepair ah right I see. I have just created the third repo. It overflowed the ci test. LOL!

**Comment by kathur** [comment]
i'm able to see my private repos fine in travis-ci.com, but not my public repos in travis-ci.org.
in cli it keeps saying sync in progress..

**Comment by BanzaiMan** [comment]
If you are still having problems, please send email to support@travis-ci.com.
