### ISSUE TITLE
This issue tracker

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#6571]
When I look throught this issue tracker, I actually can't find my own issues because too many of them are open. Most of them have been open for ages as well. Why is this?

**Comment by Monkeyboy2805** [comment]
Literally, there are issues that were opened more than five years ago that haven't been closed.

**Comment by BanzaiMan** [comment]
Thanks for the feedback. We'll try cleaning up things better.

In the mean time, I'm closing this issue, since it is not really actionable.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan Sure thing
