### ISSUE TITLE
CI build spam

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#6572]
The CI builder for this repo should have the option "only build if travis.yml is present" set to on.

**Comment by BanzaiMan** [comment]
Like this? ![settings_-_banzaiman_travis_production_test_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/18328929/4293dbaa-758c-11e6-9bdd-206300c7b6f2.png)

Or did you find something else in mind?

**Comment by Monkeyboy2805** [comment]
@BanzaiMan Yes

**Comment by BanzaiMan** [comment]
So the feature is there. Is it not working for you?

**Comment by Monkeyboy2805** [comment]
@BanzaiMan Yes, it is working I just picked up on it for this repo that's all! Might not look brilliant on you if your own CI is failing. Also, is it possible that that option can be turmed on by default?

**Comment by BanzaiMan** [comment]
I'm sorry, but I am not quite sure what you are asking about in this issue.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan If the switch has been turned to on on this repo then this issue can be closed because that is the only reason I opened it.
