### ISSUE TITLE
#6489 is back

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#6575]
#6489 is back. Sorry about the dupe issue but I couldn't reopen the old issue.

**Comment by BanzaiMan** [comment]
This should be fixed. https://travis-ci.org/BanzaiMan/travis_production_test/builds/158918524

**Comment by Monkeyboy2805** [comment]
Looks good to me, I shall test it on my next update/push. Cheers!

**Comment by Monkeyboy2805** [comment]
@BanzaiMan Fails still. Look at #2 build at https://travis-ci.org/LolexInc/Lolex-Tools.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan  but it works for this repo's build : https://travis-ci.org/LolexInc/Lolex-Number-Growth. I am completely bewildered at why this happening. Must be something in the settings for the build matrix. I HAVE NO IDEA! HELP! WHAT IS GOING ON?!

**Comment by BanzaiMan** [comment]
Rerunning a previously configured build does not change the configuration. Please push a new commit.

**Comment by Monkeyboy2805** [comment]
k

**Comment by Monkeyboy2805** [comment]
Nope, still fails.

**Comment by Monkeyboy2805** [comment]
#1

**Comment by BanzaiMan** [comment]
Looking further, https://github.com/LolexInc/Lolex-Tools/blob/3a051f62326068c6306ad48b827288297e632925/.travis.yml does not contain the data you want.

```yaml
language: python
python:
 -"3.2"
 -"3.3"
 -"3.4"
 -"3.5"
 -"3.5-dev"
 -"nightly"
install: "pip install -r requirements.txt"
script: nosetests
```

Defines the `python` value precisely this way:

```
"-\"3.2\" -\"3.3\" -\"3.4\" -\"3.5\" -\"3.5-dev\" -\"nightly\""
```

What you want instead is:

```yaml
python:
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.5-dev"
 - "nightly"
```

Notice the white space after `-`.

**Comment by Monkeyboy2805** [comment]
k give that a shot now
