### ISSUE TITLE
Not working package through apt addon

### ISSUE THREAD

**Issue by ale5000-git** [travis-ci/travis-ci#6577]
When I set android-tools-adb in the apt addon inside .travis.yml then I get "Unable to locate package android-tools-adb".

The package is whitelisted so I don't know what is the problem.

**Comment by BanzaiMan** [comment]
Please follow the instruction was https://docs.travis-ci.com/user/installing-dependencies#Installing-Projects-from-Source.

**Comment by ale5000-git** [comment]
I have already read, but I don't know what to do.
I have found over the internet this: sudo apt-get install android-tools-adb but I need adb on the container based infrastructure (and unfortunately sudo apt-get is not available on it) so I have used the apt addon hoped it works out the box.

But it just say this: https://travis-ci.org/ale5000-git/test/jobs/158591848

**Comment by BanzaiMan** [comment]
Oops. Sorry. The more relevant portion is this: https://docs.travis-ci.com/user/installing-dependencies#Identifying-the-source-for-a-missing-package

You need a non-standard source.

**Comment by ale5000-git** [comment]
Following the guide I get to this page: https://travis-ci.org/travis-ci/apt-package-whitelist/jobs/86179487
but I do not found the phrase “Fetching source package for …”

**Comment by BanzaiMan** [comment]
@ale5000-git That is the job that adds packages to the list. The issue and the build which actually tested the packages is in the commit message: https://github.com/travis-ci/apt-package-whitelist/issues/1410, https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/86171300.

I'm closing this, since the checks are happening now.

**Comment by ale5000-git** [comment]
@BanzaiMan: Sorry to be annoying but in the point 4 "Match that source against the alias name shown in the source list" I don't know what to search of that line "500 http://ftp.us.debian.org/debian/ unstable/main amd64 Packages".

**Comment by BanzaiMan** [comment]
That is a known problem with `debian-sid`. See https://github.com/travis-ci/travis-ci/issues/4838.
