### ISSUE TITLE
installing libboost-dev fails on Travis build

### ISSUE THREAD

**Issue by javierdlg** [travis-ci/travis-ci#6578]
Trying to run a Travis container where Boost is installed before running tests and I get:

`The command "sudo apt-get install libboost-dev" failed and exited with 1 during .`

Keep in mind that it worked this morning but failed a few hours ago. I thought this was exclusive to me but my class (yes this is for a college class) of +100 people are having the same issue with no resolution. Hopefully someone can shed some light into it.

**Comment by jkdf2** [comment]
Add education pack customers have moved to container-based infrastructure.

You must use [the apt plugin](https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F) instead of `sudo apt-get`.

**Comment by cotsog** [comment]
Hey @javierdlg and @jkdf2,
​
Thanks for reaching out and sorry for the troubles.
​
We just rolled back a change that created this behaviour, can you try pushing a new commit on your repository and let us know if your builds now get routed to the right infrastructure?
​
Please let us know if it fix your issue or not.

Thanks!

**Comment by javierdlg** [comment]
@cotsog Yup! Error is gone for the moment. The class' TA also made some changes to the travis.yml file to fix the issues as follows: 
- removed the clang compiler
- change g++-4.8 to g++-5
- change gcov-4.8 to gcov-5

hopefully this will help solve the issue in the future!
