### ISSUE TITLE
Failing to install content_shell (Dart version 1.19.1)

### ISSUE THREAD

**Issue by evanweible-wf** [travis-ci/travis-ci#6579]
Travis CI builds that require the installation of Dart and content-shell have recently started failing when trying to unzip `content_shell`.

Example: https://travis-ci.org/Workiva/w_transport/builds/158596014#L595-L604

This presumably coincides with the release of Dart SDK 1.19.1.

cc @kevmoo @nex3 @sethladd

**Comment by kevmoo** [comment]
Known issue with Dart build process. @whesse is looking into it.

Not a Travis issue, AFAIK

**Comment by BanzaiMan** [comment]
Thanks, @kevmoo. I'm closing this.

**Comment by whesse** [comment]
This is now fixed.  The files were in .../latest/dartium/dartium instead of .../latest/dartium.  This type of thing can happen when copying a directory and the destination directory already exists.  I'm not sure why our release scripts hit this problem this time.
