### ISSUE TITLE
Command to know available memory in a travis docker container

### ISSUE THREAD

**Issue by harendra-kumar** [travis-ci/travis-ci#6580]
Is there a command or proc fs file to find out how much memory is available inside a container? I am facing a problem where a compile command in a travis build hangs and then gets killed. The command takes around 400-600 MB memory on my machine. I am not sure whether the docker container on travis provides that much memory or not.

**Comment by npostavs** [comment]
[free(1)](https://manned.org/free.1)?

**Comment by harendra-kumar** [comment]
Doesn't work on containers, see https://fabiokung.com/2014/03/13/memory-inside-linux-containers/ .
