### ISSUE TITLE
Rails database.yml has mysql host:127.0.0.1; travis fails w/ access denied

### ISSUE THREAD

**Issue by saizai** [travis-ci/travis-ci#6585]
[Build](https://travis-ci.org/MakeYourLaws/MakeYourLaws/jobs/159017508#L926):

```
Mysql2::Error: Access denied for user 'travis'@'localhost' (using password: NO)
```

[database.yml](https://github.com/MakeYourLaws/MakeYourLaws/blob/c74ff0056fa43af94dcb18aa9db22b769909e529/config/database.yml):

```
basics: &basics
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  password: <%= Keys.get "database" %>  # results in empty string in test environment

test: &test
  <<: *basics
  username: travis
  database: myl_test
  host: 127.0.0.1
```

**Comment by BanzaiMan** [comment]
You are installing MySQL yourself, potentially overwriting the configuration to allow password-less connection for the `travis` user. https://travis-ci.org/MakeYourLaws/MakeYourLaws/jobs/159017508#L233.

Could you try setting up the user yourself, too?
