### ISSUE TITLE
Travis fails to install ruby-2.3.1 or rbx-3.58 in OSX

### ISSUE THREAD

**Issue by saizai** [travis-ci/travis-ci#6586]
Build log failures:
[ruby-2.3.1](https://travis-ci.org/MakeYourLaws/MakeYourLaws/jobs/159017509#L40)
[rbx-3.58](https://travis-ci.org/MakeYourLaws/MakeYourLaws/jobs/159017511#L40)

**Comment by BanzaiMan** [comment]
Ruby 2.3.x issue is #5361.

There is no Rubinius 3.58 for OS X (which should be released by the Rubinius team), so it is not available for you. See http://binaries.rubinius.com.

I'm closing this.

**Comment by saizai** [comment]
> There is no Rubinius 3.58 for OS X

There is, if not in binary form.

Why not permit Travis to compile if source is available but binaries not?
