### ISSUE TITLE
Build of package with dependencies on Rcpp and BH successful in release and 3.2.4 but fails in devel

### ISSUE THREAD

**Issue by abossenbroek** [travis-ci/travis-ci#6587]
I am building a package that has dependencies on `Rcpp`, `BH` and `testthat` that works on `release` and `3.2.4` but fails on `devel` with a `gcc -I` path not found error:

`/bin/bash: I/home/travis/R-bin/lib/R/include: No such file or directory`

The link to the successful build log for [`release`](https://travis-ci.org/abossenbroek/GeneralTree/jobs/159065206) and [`3.2.4`](https://travis-ci.org/abossenbroek/GeneralTree/jobs/159065208).

The link to the failed build log for [`devel`](https://travis-ci.org/abossenbroek/GeneralTree/jobs/159065207)

The error seemed to have creeped in when I started using C++11. Before that everything went fine. I deleted the caches and saw that the compilation of `Rcpp` went well.

Note that a similar build is working on windows as reported by [`this appveyor build`](https://ci.appveyor.com/project/abossenbroek14587/generaltree/build/0.0.0.9001.217/job/rgh4t6skn4tra592)

pinging: @craigcitro, @hadley and @jimhester

**Comment by jimhester** [comment]
I am aware of this issue, it stems from a change in how the configure script for R determines C++11 compatibility.

You can work around the issue by setting the `CXX11` variable. See https://github.com/hadley/devtools/blob/master/.travis.yml#L23 for an example.

**Comment by abossenbroek** [comment]
Thanks that fixed the problem!
