### ISSUE TITLE
Travis shell script exiting with code 255

### ISSUE THREAD

**Issue by juju4** [travis-ci/travis-ci#6589]
Hello,

I have tested multiple times my roles out and in travis and can't explain travis behavior with some tasks
https://travis-ci.org/juju4/ansible-adduser/jobs/159116621
https://travis-ci.org/juju4/ansible-mhn/jobs/159131437

```
$ sudo -E su $USER -c "lxc exec run-${distribution}-${version//./} -- time sh -x /etc/ansible/roles/adduser/test/integration/default/serverspec/run-local-tests.sh"

The command "sudo -E su $USER -c "lxc exec run-${distribution}-${version//./} -- time sh -x /etc/ansible/roles/adduser/test/integration/default/serverspec/run-local-tests.sh"" exited with 255.
```

ansible role test is working fine in simple trusty and docker case. only lxd with centos exhibited this issue.
but local testing is working fine.
I don't understand how can have exit code 255 and not a single line of output with -x option.

Please, don't close like https://github.com/travis-ci/travis-ci/issues/6479, it's a travis issue.

Thanks

**Comment by juju4** [comment]
ping

**Comment by BanzaiMan** [comment]
Recent builds are passing https://travis-ci.org/juju4/ansible-adduser/builds. Were you able to resolve this?

**Comment by juju4** [comment]
I didn't manage to solve this or explain it. I switch to another build way which didn't trigger any issue.
So will close but it would be nice to have more tools to debug this kind of issue. not having any command output with just an exit error code is kind of hard.

Thanks
