### ISSUE TITLE
travis_wait has no effect

### ISSUE THREAD

**Issue by duck-rh** [travis-ci/travis-ci#6591]
Quack,

In https://travis-ci.org/OSAS/ansible-role-middleman_builder/jobs/159283742
I used travis_wait because the build is very very slow (as experienced with many other tasks too). As it is multi languages, I cannot use the bundler cache to speedup. Anyway, I instructed it to let the command run for 30 minutes, but the whole build is interrupted after "10 min 47 sec" according to the same page. So I can only conclude travis_wait does not work, at least in my configuration.

_o<

**Comment by jadr2ddude** [comment]
@duck-rh 
I had a similar problem, but eventually figured out it was my fault. travis_wait works by writing output to the log. In my case, I was accidentally redirecting travis_wait into a file. I looked at your code and you might be doing the same thing.

**Comment by duck-rh** [comment]
I'm not redirecting nor piping, so travis_wait should still have control of stdout.
I have no control over what ansible-playbook does anyway.

**Comment by duck-rh** [comment]
For the record, using sudo is the problem. sudo forks and travis_wait then catch the wrong PID.

So my approach was to use travis_wait from the sudo shell. Unfortunately the way Travis works makes it very difficult. There is no function file I could source because the build.sh script is generated with everything embedded.

I then tried to export the functions, but reloading fails, seems a bash problem but not sure. Then I tried to only get travis_wait and travis_jigger (dependency), hopping the code would not change too often. My latest attempt is here:
  https://travis-ci.org/OSAS/ansible-role-middleman_builder/builds/168307612
Inside travis_cmd's eval it seems I cannot export these functions, but I don't know why. I was able to make it work on my laptop using bash 4 (Travis env has version 3), so maybe it was improved in the meanwhile.

It's really too complicated to use Travis for this use case so I'm quitting. I'll try to reply to questions if anyone wants to solve this problem, but I soon won't have the test case ready to work, sorry.

**Comment by BanzaiMan** [comment]
You can write something invisible to STDOUT indefinitely:

```bash
function write_visual_bells() {
  while true; do
    echo -en "\a"
    sleep 10
  done
}
write_visual_bells&
```

I am thinking something like this might be beneficial for everyone.

At any rate, I think I can close this.

**Comment by khatchad** [comment]
Hm, I'm not using sudo but also have this problem.

**Comment by khatchad** [comment]
@BanzaiMan  So, I would put that function and call in the "script" clause of my `.travis.yml` file immediately prior to the `mvn` invocation, correct?

**Comment by damianobarbati** [comment]
@duck-rh were you able to solve this? I'm stuck on this, resorted to manually building my clients projects.
Opened several support requests but Travis support team wasn't able to solve it in 2 months!

`travis_wait` does not work and putting in the top of my sh script @BanzaiMan function does not prevent the timeout from happening.

If anyone did solve this, please help 😞

**Comment by duck-rh** [comment]
Quack,

On 02/08/2018 01:30 AM, damiano.barbati wrote:
> @duck-rh <https://github.com/duck-rh> were you able to solve this? I'm
> stuck on this, resorted to manually building my clients projects.
> Opened several support requests but Travis support team wasn't able to
> solve it in 2 months!

I quit on this and I'm using Shippable now for this specific use, and
the GitLab pipeline too on other projects, so I'm going away from this
solution slowly it seems.

\_o<
