### ISSUE TITLE
xcodebuild fails randomly on xcode8 image

### ISSUE THREAD

**Issue by arikis** [travis-ci/travis-ci#6592]
Swift framework with 3 supported platforms (`ios`, `tvOS` and `macOS`) randomly fails with errors after switching to Swift 3 and `xcode8` TravisCI image. 

It seems that tests mostly fail after this line:

```bash
/usr/bin/codesign --force --sign - --timestamp=none /Users/travis/Library/Developer/Xcode/DerivedData/Overdrive-frlmvfbjimgtbygnszqmyqmhwvbr/Build/Products/Release-appletvsimulator/Tests.xctest
** TEST FAILED **
```

When build is restarted, some jobs that previously failed will sometimes pass and some previously passed will fail.

xcodebuild command for `macOS` used:

```bash
xcodebuild clean \
    -project $PROJECT \
    -scheme "${SCHEME}" \
    -sdk "${MACOS_SDK}" \
    -destination "${MACOS_DESTINATION}" \
    -configuration Release \
    ONLY_ACTIVE_ARCH=YES \
    CODE_SIGNING_REQUIRED=NO \
    ENABLE_TESTABILITY=YES \
    test
```

**Comment by benasher44** [comment]
This looks like a dup of #6422.

**Comment by arikis** [comment]
It seems that the issue is fixed now. Previously failed builds now are now built and tested successfully.
