### ISSUE TITLE
maven build fails with ACCESS DENIED

### ISSUE THREAD

**Issue by lkwg82** [travis-ci/travis-ci#6593]
While adjusting our build we see a failure with connectivity to repo.maven.apache.org.

```bash
Could not transfer artifact org.apache.maven.plugins:maven-failsafe-plugin:pom:2.18.1 from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-failsafe-plugin/2.18.1/maven-failsafe-plugin-2.18.1.pom , ReasonPhrase:Forbidden
```
https://travis-ci.org/idealo/logback-redis/builds/159322848

We strongly think it is not our fault. We reran an alread successful build and have seen this problem.

Plz tell how to circumvent this issue?

Thx in advance!

**Comment by karussell** [comment]
Same here [for us](https://travis-ci.org/graphhopper/graphhopper/builds/159337454)

**Comment by lkwg82** [comment]
As temporary workaround we tried to use a maven mirror from google. But it fails for some artifacts.

**Comment by lkwg82** [comment]
Since now it runs again. I'll close this issue.

Thx anyway!

**Comment by overheadhunter** [comment]
Just for the record, if this happens again: A temporary workaround is to switch the build environment from docker to GCE (`sudo: required`). The latter one wasn't affected by this "access denied" issue.

**Comment by lkwg82** [comment]
thx

**Comment by paulcwarren** [comment]
I am having this issue on several of my builds:-

https://travis-ci.org/paulcwarren/spring-content/builds/183639334

**Comment by s17t** [comment]
The same issue here after update some dependency.

https://travis-ci.org/yasserg/crawler4j

**Comment by oubiwann** [comment]
This popped up again today ... I've been seeing failing builds with this error for the past 20 minutes. Looks like someone else reference this in issue #92 27 minutes ago as well :-/

**Comment by karussell** [comment]
Having the same issue. The `sudo: true` workaround works.

Some duplicates were opened: #10053 and #10055

**Comment by hiranya911** [comment]
We suddenly started seeing this as well.

```
[ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7: Could not transfer artifact org.sonatype.plugins:nexus-staging-maven-plugin:pom:1.6.7 from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.7/nexus-staging-maven-plugin-1.6.7.pom , ReasonPhrase:Forbidden. -> [Help 2]
```

Interestingly the POM at the URL is available and can be fetched using curl or a web browser.

**Comment by lukehutch** [comment]
I see some descriptions elsewhere of solving this by setting `nonProxyHosts` to `localhost|127.0.0.1`. However, this seems to require setting this in `settings.xml` as `<proxy><nonProxyHosts>localhost|127.0.0.1</nonProxyHosts></proxy>` or possibly `<proxy><useProxy>false</useProxy></proxy>`, but I don't know how to set up `~/.m2/settings.xml` for Travis builds, and I don't think you can add these options to `pom.xml`? (Maybe someone with more knowledge of Maven and Travis than me could try this option to see if it works...)

**Comment by seanf** [comment]
> I see some descriptions elsewhere of solving this by setting nonProxyHosts to localhost|127.0.0.1. However, this seems to require setting this in settings.xml as <proxy><nonProxyHosts>localhost|127.0.0.1</nonProxyHosts></proxy> or possibly <proxy><useProxy>false</useProxy></proxy>, but I don't know how to set up ~/.m2/settings.xml for Travis builds, and I don't think you can add these options to pom.xml? (Maybe someone with more knowledge of Maven and Travis than me could try this option to see if it works...)

@lukehutch where did you see that?

**Comment by seanf** [comment]
@lukehutch I [tried](https://github.com/BrynCooke/cdi-unit/pull/145) a basic proxies section in `.m2/settings.xml`, but it looks like it needs to be filled out more than this before Maven will accept it:

```xml
  <proxies>
    <proxy>
      <nonProxyHosts>localhost|127.0.0.1</nonProxyHosts>
    </proxy>
  </proxies>
```

```
[ERROR] Error executing Maven.
[ERROR] 1 problem was encountered while building the effective settings
[ERROR] 'proxies.proxy.host' for default is missing @ /home/travis/.m2/settings.xml
```

Looking at [the Maven docs](https://maven.apache.org/guides/mini/guide-proxies.html), I don't think it makes sense to define `nonProxyHosts` unless you are defining an HTTP proxy which you want to use for other hosts.

**Comment by lukehutch** [comment]
> where did you see that?

It came right up in a Google search for the error message. The first suggestion I found was here, but I saw this same suggestion in several places:

https://stackoverflow.com/questions/21196514/deploy-from-maven-to-nexus-got-error-reasonphraseforbidden

The alternative `<useProxy>false</useProxy>` was here:

https://stackoverflow.com/questions/13728547/maven-applying-proxy-to-nonproxyhost

**Comment by keets2012** [comment]
the same problem for building failure .
`https://travis-ci.org/keets2012/Auth-service`

**Comment by lukehutch** [comment]
There are multiple dups:
#10053 
#10055 
#9987 
#2281
#9941

This may affect other languages too (I saw many similar "403 Forbidden" failure error reports for Python, Go, and Ruby/JRuby), e.g. the following (not sure if these have the same cause):
#9744
#9552 
#9803
#9826 
(+ many more that I didn't link here...)

The one thing I don't see is almost any comment from the Travis team on almost any of the bug reports I looked at. It looks like @BanzaiMan is on the Travis team?

**Comment by beatngu13** [comment]
Out of the blue we get this issue again (see [build log](https://travis-ci.com/retest/recheck/builds/116928217#L4344)):

```
[ERROR] Plugin org.apache.maven.plugins:maven-gpg-plugin:1.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-gpg-plugin:jar:1.6: Could not transfer artifact org.apache.maven.plugins:maven-gpg-plugin:pom:1.6 from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-gpg-plugin/1.6/maven-gpg-plugin-1.6.pom , ReasonPhrase:Forbidden. -> [Help 1]
```

In our case Travis CI cannot access central to download the GPG plugin. I also see several new commits/PRs that reference this issue.

Our `.travis.yml` usses Trusty, so I would assume `sudo` is not necessary because that is said to be the [default](https://docs.travis-ci.com/user/reference/overview/#linux)?

**Comment by wallrj** [comment]
See https://travis-ci.community/t/continuous-maven-repo-403/3908

**Comment by paulcwarren** [comment]
This happened again today: https://travis-ci.org/paulcwarren/spring-content-examples/builds/569186703

**Comment by mekya** [comment]
It also happens for me 

Access denied to: https://repo.maven.apache.org/maven2/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.jar

https://travis-ci.org/ant-media/Ant-Media-Server/builds/569733421

**Comment by anantbhargatiya** [comment]
I also faced same issue and for me the problem was password issue in settings.xml and security-settings.xml.... mvv has two commands for password encryption mvn -emp <password> which goes to security-settings.xml and another one is mvn -ep <password> which goes to settings.xml. make sure you use correct command and update passwords in both files correctly.
