### ISSUE TITLE
OS X workers saturated

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6597]
It appears the OS X workers have been saturated for most of the day. We are still seeing jobs waiting to start ATM. It would be great if someone could take a look.

<img width="1554" alt="screen shot 2016-09-12 at 20 40 28" src="https://cloud.githubusercontent.com/assets/3019665/18457745/2e46ba14-7929-11e6-83bb-4373623c8135.png">

**Comment by jakirkham** [comment]
Here is an updated screenshot. It looks like it is improving slowly.

<img width="1554" alt="screen shot 2016-09-13 at 2 43 36" src="https://cloud.githubusercontent.com/assets/3019665/18463967/e3650b30-795b-11e6-8dc7-5ff496ea787b.png">

**Comment by jakirkham** [comment]
This situation is returning. We have jobs stalled out waiting to run. See the screenshot below.

<img width="1554" alt="screen shot 2016-09-13 at 10 19 54" src="https://cloud.githubusercontent.com/assets/3019665/18477438/ae40c5b2-799b-11e6-81cf-cc0c94ed7919.png">

**Comment by solarce** [comment]
We have a finite amount of OSX capacity, as it is privately hosted hardware. When it's busy there can be a long wait time. We added some additional capacity today and have plans to add more in the future, but as this is our most expensive compute platform by far, we're only to provide so many resources to it.
