### ISSUE TITLE
Python nightly is now python3.7

### ISSUE THREAD

**Issue by yan12125** [travis-ci/travis-ci#6599]
Since changeset https://hg.python.org/cpython/rev/c781adae884d, python nightly should be python3.7. Cross compiling Python requires the latest Python interpreter. See the last few lines in https://s3.amazonaws.com/archive.travis-ci.org/jobs/159854378/log.txt for details. Please consider update it.

**Comment by BanzaiMan** [comment]
I'm closing this in favor of #6613 (which is essentially the same issue).
