### ISSUE TITLE
Travis won't start new builds after Github repo ownership transfer

### ISSUE THREAD

**Issue by juancabrera** [travis-ci/travis-ci#6602]
We had Travis working perfectly fine in our organization repo (private), let's call it `organization-a/web-project`, we did a github ownership transfer to `organization-b/web-project` and turn off and on the switch on Travis.

- We can see all old builds and old branches, we can even restart old builds.
- When we create new PRs the build doesn't get started, also we can't see the new branches on Travis.

We even tried to generate new keys but isn't working.

**Comment by MariadeAnton** [comment]
@juancabrera can you try triggering a sync for both organization-a and organization-b in their profile pages? 

- https://travis-ci.com/profile/organization-a 
- https://travis-ci.com/profile/organization-b 

That should sync Travis CI up with the updated permissions over the repository and authorize PRs properly.

If that doesn't work, please drop us a line at support@travis-ci.com!

**Comment by amishyn** [comment]
I have similar issue. Difference is that I can restart old builds. While new commits do not appear

**Comment by BanzaiMan** [comment]
@amishyn If the new organization does not have a valid subscription, we do not run private builds. If you have further questions, please email us at support@travis-ci.com with details. Thanks.

If others have similar problems, please resync data as @MariadeAnton showed above, and try again. If it doesn't resolve the issue, email us.

I'm closing this.

**Comment by amishyn** [comment]
@BanzaiMan Does it mean that I can't fork this repo to organization with valid subscription and run build there ? It doesn't work in my case.

**Comment by BanzaiMan** [comment]
@amishyn If the fork belongs to an organization with a valid subscription, we should. I thought it didn't in your case, since you said:

> I think that new organisation does not have travis-ci.com account

Please email us with details. Thanks.
