### ISSUE TITLE
build fails on deployment phase and the log is truncated

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#6603]
https://travis-ci.org/igagis/papki/jobs/159884872

the log is truncated at the end and it is not possible to analyse what is the error.
It happens every time with this build.

**Comment by BanzaiMan** [comment]
What is `prorab-apply-version.sh`, and what is it doing? If it is setting `errexit` (e.g., `set -e`), then the build will stop immediately if *any* command exits with nonzero status.

**Comment by igagis** [comment]
I actually found the root cause already, problem was that prorab-apply-version.sh was not found at all. Although there was no any record about that in the log...

**Comment by BanzaiMan** [comment]
@igagis That is probably because you'd set `errexit` elsewhere prior to the call to `prorab-apply-version.sh`, and the failure to find the command resulted in immediate termination of the build.
