### ISSUE TITLE
Travis fails to report when some ini commands fail.

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#6605]
`ini_set()` will return `false` on failure to set an ini setting, Travis CI seems to ignore when these failures happen in the build from .travis.yml commands

one example
`hhvm --php -r 'ini_set("hhvm.php7.all", 1);'`
as in 
` - if [[ $HHVMPHP7 == "yes" ]]; then hhvm --php -r 'ini_set("hhvm.php7.all", 1);'; fi`

The expected result should be a notice in the travis log
```
The command "if [[ $HHVMPHP7 == "yes" ]]; then hhvm --php -r 'ini_set("hhvm.php7.all", 1);'; fi" exited with false
```

**Comment by BanzaiMan** [comment]
The PHP function may return `false`, but the command doesn't seem to return nonzero status.

```sh-session
$ php --version
HipHop VM 3.5.0 (rel)
Compiler: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424
Repo schema: b88b6fee8ef78ab638506d212abcbefe74a276ac
$ hhvm --php -r 'ini_set("hhvm.php7.all", 1);'
$ echo $?
0
```

So this command:

    if [[ $HHVMPHP7 == "yes" ]]; then hhvm --php -r 'ini_set("hhvm.php7.all", 1);'; fi

will not halt the build.

**Comment by photodude** [comment]
so HHVM may have an issue with proper returns on the command line...

I tried the following on php 5.6 on travis and it did not halt the build.
if [[ $TRAVIS_PHP_VERSION != hhv* ]]; then php -r 'ini_set("hhvm.php7.all", 1);'; fi

Maybe that's expected since `ini_set()` returns the old value or `false` on failure to set. So there could be a situation where `false` or `0` is the old value and it would return false but it's a success not the return of `false` on failure.

maybe travis just needs to echo the return to the log when `ini_set()` is used from the command line so there is a better chance of discovering when an ini value fails to set with `ini_set()`

**Comment by photodude** [comment]
ok, closing as expected behavior.
