### ISSUE TITLE
Build continues running for 15 minutes after `script` finishes and cannot be cancelled

### ISSUE THREAD

**Issue by shadiakiki1986** [travis-ci/travis-ci#6608]
Hi. I'm using `docker` to launch an instance of an image and then run some tests against it. The problem is that the build continues running after my test script finishes. Also, the build cancel button doesn't let me cancel saying "this build cannot be cancelled". It ran for 15 minutes after test completion, then it ended successfully.

Here are some links:
- [build log](https://travis-ci.org/shadiakiki1986/rserve-php/builds/160145556)
- [travis file](https://github.com/shadiakiki1986/rserve-php/blob/use-namespaces-and-psr4-autoload/.travis.yml)

Am I using the `docker` command wrong?

Edit: I added a `docker stop` command to `after_success`. This seems to stop the build. The [documentation](https://docs.travis-ci.com/user/docker/) didn't mention this. Perhaps just a documentation update is required?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by shadiakiki1986** [comment]
So a simple reload would have sufficed?

**Comment by BanzaiMan** [comment]
Yes. There is an issue with web updates not updating (which is a known issue), and not communicating why you couldn't cancel the build, though.
