### ISSUE TITLE
Python-nightly seem faulty (report wrong version and crash)

### ISSUE THREAD

**Issue by Carreau** [travis-ci/travis-ci#6613]
This does not seem to come from upstream

See this build:

https://travis-ci.org/Carreau/reenum/jobs/160562157

that purely consist of 

```
language: python
python: 
    - "nightly"
    - "3.6-dev"
script:
    - python -c 'import sys; print(sys._mercurial)'
    - export PYTHONWARNINGS='ignore'; python -c 'print(1)'
```

You'll see in particular that 

```
$ python --version
Python 3.6.0a4+
```

while

```
$ python -c 'import sys; print(sys._mercurial)'
('CPython', 'default', 'b66e0856ab24')
```

Which is Python 3.6  post-beta 1 (so report wrong version)

and 

```
export PYTHONWARNINGS='ignore'; python -c 'print(1)'
```

lead to : 
```
'import warnings' failed; traceback:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/warnings.py", line 496, in <module>
    _processoptions(sys.warnoptions)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/warnings.py", line 178, in _processoptions
    _setoption(arg)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/warnings.py", line 184, in _setoption
    import re
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/re.py", line 122, in <module>
    import enum
ModuleNotFoundError: No module named 'enum'
```

Which for the same local build of same Python commit on OS X and  Linux seem to work fine. 

Not sure where the code that build the nightly is stored and how to submit a PR to fix that,

**Comment by BanzaiMan** [comment]
We rely on [`php-build`](https://github.com/yyuu/pyenv/tree/master/plugins/python-build/share/python-build) to create Python archives for on-demand installation. If the resultant runtime is reporting a wrong version, I tend to think this is an issue with the code base itself.

The utility to build the runtime is found here: https://github.com/travis-ci/cpython-builder

**Comment by Carreau** [comment]
Or I can reproduce the traceback locally if I use `virtualenv --distribute`, though the version number being the wrong one seem to definitively be a travis-ci specific thing.

**Comment by skirpichev** [comment]
> If the resultant runtime is reporting a wrong version, I tend to think this is an issue with the code base itself.

Your runtime definitely is not up to date.  I still see [this issue](pytest-dev/pytest#1957) on my 3.6-dev build, while it was fixed two weeks ago or more.  How often 3.6-dev is updated?

**Comment by BanzaiMan** [comment]
The build is run daily. The latest failure https://travis-ci.org/travis-ci/cpython-builder/jobs/165953135#L447 shows that php-build is rejecting the resulting binary because it is not executable (https://github.com/yyuu/pyenv/blob/0e298b691d8490064cc069a56be91597afdb590b/plugins/python-build/bin/python-build#L1526).

**Comment by skirpichev** [comment]
> The latest failure

Oh, it seems, this is broken long time ago.  E.g. [this](https://travis-ci.org/travis-ci/cpython-builder/jobs/163551953) (10 days ago).  Unfortunately, there are too little debugging info.  It's even not clear if this file exists at all.

**Comment by skirpichev** [comment]
It looks like the binary name is python3.7.  Perhaps, you should use [3.6.0b1](https://github.com/yyuu/pyenv/blob/master/plugins/python-build/share/python-build/3.6.0b1) for 3.6-dev builds?

**Comment by BanzaiMan** [comment]
I overlooked https://github.com/travis-ci/travis-ci/issues/6599.

**Comment by Carreau** [comment]
Sorry I hadn't had a chance to dig in deeper yet. But there seem to be both a `venv` and a travis-specific issue. I didn't had a change to report to venv yet.

**Comment by BanzaiMan** [comment]
Once https://github.com/yyuu/pyenv/pull/729 is merged, we can start building 3.7-dev as nightly.

**Comment by skirpichev** [comment]
Also, 3.6-dev should be fixed (https://github.com/yyuu/pyenv/pull/730).

**Comment by BanzaiMan** [comment]
`nightly` now points to 3.7-dev. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/166400944#L134

`3.6-dev` is new, and points to the bleeding edge of the 3.6 development post b1: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/166400945#L134

`3.5-dev` points to the 3.5 development branch, as before.

**Comment by Carreau** [comment]
Can you reopen ? The following part is still unfixed
```
'import warnings' failed; traceback:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/warnings.py", line 496, in <module>
    _processoptions(sys.warnoptions)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/warnings.py", line 178, in _processoptions
    _setoption(arg)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/warnings.py", line 184, in _setoption
    import re
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/re.py", line 122, in <module>
    import enum
ModuleNotFoundError: No module named 'enum'
```

Cf https://travis-ci.org/Carreau/reenum/jobs/166480396 

Unless you want to keep it closed as this is not a travis-issue, though it _does_ affect travis `nightly` and `3.6-dev`.
