### ISSUE TITLE
Who do a pr should be able to restart a job in timeout.

### ISSUE THREAD

**Issue by latot** [travis-ci/travis-ci#6615]
Hi all, well, this issue don't is about some timeouts of travis, you know when we are masters of some repo we have available the "Restart Job" option, very useful when travis have a timeout, so i think this should be able to who do a pr too, because actually when this happen we must start using useless changes to do travis works.

As a note, the master of pr have enabled the "Restart Build" button but not the "Restart Job" button.

Thx. Cya.

**Comment by BanzaiMan** [comment]
Sounds like a duplicate of #887.

**Comment by latot** [comment]
ups you are right!
