### ISSUE TITLE
HHVM nightly is not nightly on Trusty builds

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#6616]
The HHVM nightly on the Trusty builds are not actually nightly.

build showing latest hhvm
https://travis-ci.org/photodude/joomla-cms/jobs/160930724

build showing nightly hhvm
https://travis-ci.org/photodude/joomla-cms/jobs/160930722

The Compiler: tags and the Repo schema: are exactly the same Id's I believe thaty means nightly is latest rather than nightly.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/blob/ef82e82457f82c6518d090544bb533dc0faf0063/lib/travis/build/script/php.rb#L123-L125

We simply run `apt-get install hhvm-nightly` from the HHVM's repository (https://github.com/travis-ci/travis-build/blob/ef82e82457f82c6518d090544bb533dc0faf0063/lib/travis/build/script/php.rb#L104). If it's not getting updated, it is because the installation failed.

**Comment by BanzaiMan** [comment]
…or the HHVM team stopped updating the packages.

**Comment by photodude** [comment]
I'm wondering if HHVM isn't updating the nightly packages.

**Comment by BanzaiMan** [comment]
I see 2016.09.19 packages in http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-amd64/Packages.

**Comment by photodude** [comment]
Ok, Closing as an HHVM issue with the nightly builds

**Comment by photodude** [comment]
Reopening as the new HHVM nightly for 9-20 is definitely correct but not installing

**Comment by photodude** [comment]
@BanzaiMan any thoughts on why `apt-get` on travis is failing to install the current nightly pacakges for hhvm?

The hhvm-nightly builds are still showing 3.15.0 rather than 3.16.0-dev, even though HHVM fixed the nightly build issue they had due to not tagging the next version. I also see 2016.09.21 packages in http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-amd64/Packages

I even tried to force apt-get update and upgrade and I still end up with 3.15.0 rather than 3.16.0-dev.

**Comment by photodude** [comment]
I do have an open issue with HHVM, for this https://github.com/facebook/hhvm/issues/7355

HHVM wonders the following
>I'm not sure how that travis job is getting it's nightly package, but, after checking, the 2016.09.20 package for Trusty is 3.16.0-dev

**Comment by BanzaiMan** [comment]
It appears that hhvm-nightly builds are not adding the apt source required for it.

**Comment by photodude** [comment]
I tried to force add the source to the .travis.yml, but it conflicted and didn't update
```php
W: Duplicate sources.list entry http://dl.hhvm.com/ubuntu/ trusty/main amd64 Packages (/var/lib/apt/lists/dl.hhvm.com_ubuntu_dists_trusty_main_binary-amd64_Packages)
W: You may want to run apt-get update to correct these problems
update-alternatives: warning: alternative /usr/bin/hhvm (part of link group php) doesn't exist; removing from list of alternatives
update-alternatives: warning: /etc/alternatives/php is dangling; it will be updated with best choice
```

I'm not sure but it seems like the source is right as I can get a log item for hhvm-nightly from `apt-get install -y hhvm-nightly`
```php
Unpacking hhvm-nightly (2016.09.22~trusty)
```
but the install seems to be falling back to hhvm rather than installing `hhvm-nightly` as the version reported with `php --version` is still 3.15.0 rel

**Comment by BanzaiMan** [comment]
I think I understand the issue now. I do not think `hhvm-nightly` ever worked (we can only test Trusty now, and I am guessing that it didn't on Precise, ever, but I can't confirm it).

I have some ideas on how to fix it; I plan to do that next week.

**Comment by photodude** [comment]
Thank you for fixing this @BanzaiMan

**Comment by photodude** [comment]
@BanzaiMan I just noticed that the hhvm-3.15 build is erroring after the fix for hhvm-nightly
```php
 phpenv global hhvm-3.15 2>/dev/null
The command "phpenv global hhvm-3.15 2>/dev/null" failed and exited with 1 during .
```
https://travis-ci.org/photodude/joomla-cms/jobs/164664456

**Comment by BanzaiMan** [comment]
Because we are passing `hhvm-3.15` to `phpenv global`. You should use `hhvm` now.

**Comment by photodude** [comment]
Doesn't only using `hhvm` that defeat the point of #6043 and the resulting patch that allowed specifying HHVM LTS versions like hhvm-3.12 or hhvm-3.15?

**Comment by BanzaiMan** [comment]
Ah. Sorry. I forgot about that ticket. I'll take a deeper look.

**Comment by photodude** [comment]
Thanks for fixing this @BanzaiMan

**Comment by shimondoodkin** [comment]
seems again last package is from 1 jan
