### ISSUE TITLE
Accept ConstraintLayout licenses

### ISSUE THREAD

**Issue by SUPERCILEX** [travis-ci/travis-ci#6617]
I keep getting the following error saying that Travis didn't accept the ConstraintLayout licenses:

```
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Solver for ConstraintLayout 1.0.0-alpha8, ConstraintLayout for Android 1.0.0-alpha8].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here? Are you listing licenses to accept? https://docs.travis-ci.com/user/languages/android#Dealing-with-Licenses

**Comment by SUPERCILEX** [comment]
This issues is documented in several places:
https://code.google.com/p/android/issues/detail?id=212128
http://kechengpuzi.com/q/s37615379
http://stackoverflow.com/questions/37615379/travis-ci-build-doesnt-work-with-android-constraint-layout

I can't find/don't know what licenses I need to add to my Travis build to make it compile.

**Comment by SUPERCILEX** [comment]
I forgot to update this issue, there's been a fix for a while now:
```yml
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
```

**Comment by wolkenschieber** [comment]
According to documentation all license should be accepted per default. Travis doesn't do that for ConstraintLayout. Also manually setting the license hash results in a failing build.

The issue should be reopened.

**Comment by miankhalid** [comment]
All solutions mentioned here are failing other than the one that @wolkenschieber mentioned. Thanks alot for the fix, finally my builds are running 😄 

Reference: https://github.com/edx/edx-app-android/pull/1065/commits/fe06b43af8872a54514ef3635e59f591185dfe41
