### ISSUE TITLE
jruby install fails on vm based builds

### ISSUE THREAD

**Issue by pezra** [travis-ci/travis-ci#6619]
The `rvm use jruby-...` hangs while importing the gemset. The version of jruby doesn't seem to matter, i have the same problem with 9.0.0.0, 9.0.1.0 and 9.0.5.0. Searching for issues with RVM or Travis did not turn up anything other than that proxy misconfigurations can sometime cause RVM to exhibit this symptom.

**example build**: https://travis-ci.org/cequel/cequel/builds/161351335
**log output**:
> $ rvm use jruby-9.0.0.0 --install --binary --fuzzy
> Unknown ruby string (do not know how to handle): jruby-9.0.0.0.
> Unknown ruby string (do not know how to handle): jruby-9.0.0.0.
> jruby-9.0.0.0 is not installed - installing.
> Unknown ruby string (do not know how to handle): jruby-9.0.0.0.
> Unknown ruby string (do not know how to handle): jruby-9.0.0.0.
> Searching for binary rubies, this might take some time.
> Unknown ruby string (do not know how to handle): jruby-9.0.0.0.
> Unknown ruby string (do not know how to handle): jruby-9.0.0.0.
> Found remote file https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0/jruby-bin-9.0.0.0.tar.gz
> Checking requirements for ubuntu.
> Requirements installation successful.
> jruby-9.0.0.0 - #configure
> Unknown ruby string (do not know how to handle): jruby-9.0.0.0.
> jruby-9.0.0.0 - #download
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 35.3M  100 35.3M    0     0  11.5M      0  0:00:03  0:00:03 --:--:-- 11.5M
> jruby-9.0.0.0 - #validate archive
> jruby-9.0.0.0 - #extract
> jruby-9.0.0.0 - #validate binary
> jruby-9.0.0.0 - #setup
> jruby-9.0.0.0 - #gemset created /home/travis/.rvm/gems/jruby-9.0.0.0@global
> jruby-9.0.0.0 - #importing gemset /home/travis/.rvm/gemsets/jruby/global.gems
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> The build has been terminated

**Comment by pezra** [comment]
Thanks! That did seems to fix the issue.

**Comment by jrochkind** [comment]
Hey, _what_ fixed the issue?  I believe I am having this issue, have no idea what to do about it. 

The thing you point to in JRuby now has anchor: https://github.com/jruby/jruby/wiki/FAQs#why-is-jruby-so-slow-to-install-why-does-jruby-take-so-long-to-make-secure-connections

It suggests it's a problem with entropy (do NOT understand why that effects downloads from S3, but okay), and that one solution might be "to install and enable a source of entropy like haveged."  However, it's unclear how to do this, or if it's even possible, on travis. 

I am very annoyed. It should not be rocket science to get travis to download/use a certain jruby version.
