### ISSUE TITLE
write /var/lib/docker/tmp/GetImageBlob398223075: no space left on device

### ISSUE THREAD

**Issue by arunsoman** [travis-ci/travis-ci#6620]
https://travis-ci.org/arunsoman/text-processor
Ia it because the test server has limited storage provisioned ?

**Comment by BanzaiMan** [comment]
Yes. How big is your Docker image?

**Comment by arunsoman** [comment]
I am trying to do this
$ git clone https://github.com/emc-advanced-dev/unik.git
$ cd unik
$ make

**Comment by BanzaiMan** [comment]
The `make` command is clearly pulling a docker image https://travis-ci.org/arunsoman/text-processor/builds/161384145#L273. How big is it (are they)? Did you try pulling it down to your machine?

**Comment by BanzaiMan** [comment]
Looks like you've restructured your builds, and this is no longer a concern.
