### ISSUE TITLE
Clang uses wrong headers

### ISSUE THREAD

**Issue by Elronnd** [travis-ci/travis-ci#6621]
I'm confused as to why clang is using gcc's headers.  You can see [here](https://travis-ci.org/Elronnd/roguelike-with-no-name/jobs/161390283#L434) that clang is erroring out because it's using gcc's headers.  Anyone know anything I can about this?

**Comment by jeffhammond** [comment]
Have you determined that this is a Travis-specific issue?  Does it not occur with the same Linux+GCC+Clang/LLVM versions outside of Travis/AWS?

(To be clear, I do not work for Travis CI.  I'm just a random person from the internet commenting on Github issues related to my experience.)
