### ISSUE TITLE
Make failure notification on allowable failures configurable

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#6622]
Our app build on php nightly where its allowed to fail, often due to php segfaulting. It would be nice to NOT reiceive "build failed" emails in this case on a configurable basis.

**Comment by BanzaiMan** [comment]
In your use case, what configurable options do you propose?

**Comment by andig** [comment]
> In your use case, what configurable options do you propose?

This could either be:

  1. always treat allowable failure as success. The current solution is inconsistent as Travis UI shows build status in green, yet error notification is sent out. So this bring notifications in line with ui.
  2. configure as part of the `allowable_failures`, i.e. - as part of the matrix - add something like `treat_as: success|failure`. This status would then be used by the notification system as documented in https://docs.travis-ci.com/user/notifications/. If failure is selected that would still leave the ui inconsistent as overall build status is green.
  3. configure as part of the notifications. Currently there are `on_success` and `on_failure`. You could add `treat_allowable_failure_as` or `on_allowable_failure` The latter might not work with `change`.

So- although this is a change in behaviour- I would personally prefer 1. Least impact would probably be with 2.

**Comment by BanzaiMan** [comment]
If the `nightly` jobs are allowed to fail, they should not affect the build result. If they are, it is either your configuration is wrong, or there is a bug.

**Comment by andig** [comment]
> If the nightly jobs are allowed to fail, they should not affect the build result.

I did not especially test this, but:

  -  as PHP dev I might accept HHVM failure especially since not all database modules are available on HHVM
  - I currently have an upstream package broken that breaks my build but am willing to accept and would like to check whether it's back to green

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
I am closing this as it's become stale. If you are still having problems, do let us know.
