### ISSUE TITLE
Unable to build iOS project

### ISSUE THREAD

**Issue by rhwood** [travis-ci/travis-ci#6628]
I am attempting to build an iOS project using the `xcode8` image and `iphoneos9.3` SDK, but get the following erroneous result:

```
$ set -o pipefail && xcodebuild test -workspace "${TRAVIS_XCODE_WORKSPACE}" -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" | xcpretty

xcodebuild: error: SDK "iphoneos9.3" cannot be located.
The command "set -o pipefail && xcodebuild test -workspace "${TRAVIS_XCODE_WORKSPACE}" -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" | xcpretty" exited with 64.
```

A failing build is https://travis-ci.org/rhwood/roster-decoder/jobs/162168991/config

**Comment by nasli** [comment]
@rhwood  Try to use xcodebuild with -destination parameter, this works for me

```
 - xcodebuild -project 'project.xcodeproj' -scheme 'project' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6' build test | xcpretty -c --test --color
```
If cannot be locate this simulator, the output will show a list of available simulators

**Comment by Lyoness** [comment]
Closing out older tickets.
