### ISSUE TITLE
Build started failing to compile json 1.8.3 native extension on ruby-head

### ISSUE THREAD

**Issue by kytrinyx** [travis-ci/travis-ci#6630]
I realize that this may be the wrong place to post this; please feel free to close the issue if I'm barking up the wrong tree.

Recently (in the past few days, not exactly sure when) the build on my kytrinyx/approvals gem started failing, but only on ruby-head:

https://travis-ci.org/kytrinyx/approvals/builds/160736974

I know that https://github.com/kytrinyx/approvals/commit/63487384a71481c686b83900c838076b29c0449a was committed 7 days ago, and passed at that time.

I reran this build today, and it failed.

Have any of you run into this?

**Comment by BanzaiMan** [comment]
This might be an unfortunate byproduct of my fixing `ruby-head` yesterday. `ruby-head` had been broken for quite some time (https://travis-ci.org/kytrinyx/approvals/jobs/159017322#L182 shows that the last passing build was from July 2). Could you try either deleting or disabling caching to see if that fixes the issue?

**Comment by kytrinyx** [comment]
Thanks @BanzaiMan!

I deleted all the caches and reran the build, and it is still failing to build the native extensions for json.

I tried going to http://docs.travis-ci.com/user/caching/ to see about disabling the cache, but the site wouldn't load for me (I'm on a sketchy wifi, so that might be a problem on my end).

**Comment by kytrinyx** [comment]
@BanzaiMan: Check out this comment from @randycoulman https://github.com/kytrinyx/approvals/pull/73#issuecomment-249385183

This is a problem on our end, because we're supporting older Rubies. I'm going to close this, as I don't think there's anything that can be done on your end.

Thanks so much for your help.

**Comment by BanzaiMan** [comment]
@kytrinyx Ah, cool. Thank you for the update.
