### ISSUE TITLE
SonarQube: major minor version 52

### ISSUE THREAD

**Issue by RecuencoJones** [travis-ci/travis-ci#6631]
I have some TypeScript project that I want to run SonarQube for with Travis:

```
language: node_js
node_js:
  - "5"
  - "6"

addons:
  sonarqube: true

...

script:
  - npm test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
```

I set up the project to use sonar addon and placed my encrypted token, but the build fails with Unsupported major.minor version 52 ([stacktrace](https://travis-ci.org/RecuencoJones/TypeScript-Webpack-boilerplate/jobs/162579925#L1194))

I also tried requiring `jdk: oraclejdk8` with no luck.

**Comment by Darkitty** [comment]
Hi,

I have the same issue with a .NET project ([stacktrace](https://travis-ci.org/Darkitty/KerSSH/builds/162770627)).

Thanks

**Comment by voghDev** [comment]
I guess the problem I'm having on Android is similar. ([stacktrace](https://travis-ci.org/voghDev/dagger2-clean-mvp-example/builds/168071918))

**Comment by alexchiraples** [comment]
Same problem here, PHP [stacktrace](https://travis-ci.org/gov-ithub/maisimplu.gov.ro/builds/176386522)

**Comment by ankon** [comment]
> I also tried requiring `jdk: oraclejdk8` with no luck.

That is only looked at for Java images IIRC, so it won't install a new JDK for you. You can try installing the Oracle JDK8 manually (using the oracle-jdk8-installer apt package), and then set the `JAVA_HOME` environment variable to `/usr/lib/jvm/java-8-oracle` before running sonar-scanner. 

Alternatively try the 'trusty' infrastructure, if you're ok with "beta". :)

**Comment by alexchiraples** [comment]
Thanks @ankon! 

This is how I've managed to get it up and running, using the "beta" :). 
It fails with '/home/travis/build.sh: line 57:  xxx Killed                  sonar-scanner -Dsonar.login=$SONAR_TOKEN'. 
I've managed to have one successful build, but only one - [stacktrace](https://travis-ci.org/gov-ithub/maisimplu.gov.ro/builds/176645667)

This is my current configuration:

`dist: trusty
language: php
php:
  - '5.4'
sudo: false

addons:
  sonarqube: true
  apt:
    packages:
      - oracle-java8-installer
 
env:
  global:
    - JAVA_OPTS='-Xmx3072m'
    - SONAR_RUNNER_OPTS="-Xmx1024m -XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=128m"
    - secure: # add your code here ...

before_script:
  - echo $SONAR_RUNNER_OPTS
 
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN`

**Comment by chepe4pi** [comment]
Same problem with python - https://travis-ci.org/chepe4pi/ethereum_scanner/builds/176766688

**Comment by dkliban** [comment]
I am also experiencing this same problem trying to run sonar-scanner for my Python project.

**Comment by bellingard** [comment]
Hi all, 

SonarQube Scanner needs a JDK8 JVM to run. AFAIK, Precise-based images that target a specific language that is not JVM based won't get a JDK (@BanzaiMan, can you confirm?). So looks like the only valid environments are:
* [JVM VM images](https://docs.travis-ci.com/user/ci-environment/#JVM-(Clojure%2C-Groovy%2C-Java%2C-Scala)-VM-images)
* [Trusty](https://docs.travis-ci.com/user/trusty-ci-environment/)

Non-Java projects ([example](https://github.com/SonarSource/sq-com_example_standard-sqscanner-travis)) will probably want to use Trusty. 

I will update the official documentation to make this clearer.

**Comment by dkliban** [comment]
@bellingard Thank you! Specifying `dist: trusty` fixed the problem for me. Could you please update the example docs?

**Comment by bellingard** [comment]
@dkliban Can you tell me which exact doc you're referring to? I've already updated the ["Get Started"](https://about.sonarqube.com/get-started/) page and I'm about to submit an update to the [official doc of the Travis Add-on](https://docs.travis-ci.com/user/sonarqube/).

**Comment by dkliban** [comment]
@bellingard I was referring to the Get Started page. Thanks for the quick resolution!

**Comment by bellingard** [comment]
@RecuencoJones I think this issue should be closed. As I mentioned in December, solution is to use Trusty environment.

**Comment by RecuencoJones** [comment]
@bellingard, just tried to rebuild the project with `dist: trusty`, works fine hence closing the issue, thanks!
