### ISSUE TITLE
Setting CC and CXX in build matrix

### ISSUE THREAD

**Issue by sxlijin** [travis-ci/travis-ci#6633]
This is one of those issues that's more of a question of "what should the default behavior be" as opposed to "some thing may or may not be broken" - specifically, the inability to set `CC` and `CXX` in the build matrix.

If you want to use a more recent GCC version on a container-based build, say GCC 6, you have to pull `g++-6` down from `ubuntu-toolchain-r-test`, which instead of changing the `g++` symlink to point to the new version of GCC, set up a new one at `g++-6`. 

That being said, this makes specifying your build matrix slightly more complicated, because `CC` and `CXX` are set (either by [`cpp_spec.rb`](https://github.com/travis-ci/travis-build/blob/master/spec/build/script/cpp_spec.rb) or [`cpp.rb`](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/cpp.rb), I'm not entirely sure which) after the build environment is set up irrespective of whatever value they might already have been set to, which means that you have to set `CC` and `CXX` in your `before_install` now.

I've specified a workaround in my build using `MATRIX_ENV="CC=gcc-6 && CXX=g++-6"` in a specific `matrix.include`, and doing `eval $MATRIX_ENV` in `before_install`, but this is something that seems both prone to error and also something that the build matrix should be taking care of me, not the other way around.

**Comment by vslavik** [comment]
This is particularly annoying because in the normal/default setup with just a single gcc compiler, Travis doesn’t even *need* to set these variables, so it really just gets in the way...

**Comment by sxlijin** [comment]
Cross-referencing travis-ci/docs-travis-ci-com#746 since I've used the same `eval` workaround in that submitted PR.
