### ISSUE TITLE
[Feature Request] Gardening - macOS Alias

### ISSUE THREAD

**Issue by JustinJiaDev** [travis-ci/travis-ci#6634]
Allow `macos` in `.travis.yml`:

`os: osx` -> `os: macos`
`osx_image` -> `macos_image` (maybe `xcode_image` is even better?)

**Comment by BanzaiMan** [comment]
A duplicate of #6200.

**Comment by JustinJiaDev** [comment]
@BanzaiMan That one was opened before public release and got closed. 

Comment:

> As Sierra approaches GA, we may add support for macos as an alias to certain things.

Couldn't we leave this issue open?

I'm willing to create a pull request if no one have time to implement it.
