### ISSUE TITLE
Add ability to define a timeout

### ISSUE THREAD

**Issue by lededje** [travis-ci/travis-ci#6636]
As an engineer I want a job that takes longer than x minutes to fail to force a conversation about speeding up our builds.

The time it takes to complete a build is often overlooked. When a project starts it's typically fast enough for people not to notice, but soon it creeps up and like a frog in boiling water you end up waiting over half an hour for tests to complete. It would be good to set hard timeouts that cause your builds to fail to force a conversation within your team to work on speeding up builds.

**Comment by philmd** [comment]
similar to #5306

**Comment by BanzaiMan** [comment]
@philmd Thanks for the ping.

Looks like we can close this as a duplicate.
