### ISSUE TITLE
.travis.yml not found even after multiple pushes. Branch master not included per configuration

### ISSUE THREAD

**Issue by vignesh0025** [travis-ci/travis-ci#6638]
I am trying to use .travis.yml to my github pages repo. But travis throws error that **.travis.yml** is not found. Please give me a solution.

**Comment by acnagy** [comment]
Hey @vignesh0025! Thanks for opening this. Looks like you fixed it a little bit ago by [safelisting](https://docs.travis-ci.com/user/customizing-the-build#Safelisting-or-blocklisting-branches) the branches you need? I'm seeing a passing build in your GitHub pages repo with this configuration change so I'm gathering you're all set. Lemme know if not. Thanks!

**Comment by vignesh0025** [comment]
Wow! I never know that issue is solved until you said. Thanks btw :-) But i really don't know what i did to get it working

**Comment by acnagy** [comment]
Oh! Glad to have been able to help 😄  The way you had it solved was by safe-listing the `gh-pages` branch, as well as other branches starting with `pages-(.*)`. Looks like it's commented out now, though. That said, you can see if we processed a request for a particular build on your [Requests page ](https://travis-ci.org/vignesh0025/vignesh0025.github.io/requests) (which can be found on a particular repo's page --> 'More Options' --> 'Requests').

That said, if you wanted to safelist all branches here, you could try this:
```
branches:
  only:
      - gh-pages
      - /.*/
```
