### ISSUE TITLE
.net core: No solution or script defined, exiting

### ISSUE THREAD

**Issue by ArgTang** [travis-ci/travis-ci#6640]
@joshua-anderson @akoeplinger @nterry

Hello

I am trying to set up a build server for the first time and are having some trouble. The config file is like this:
```
language: csharp
solution: GroupProject.sln
sudo: required
dist: trusty

mono: none
dotnet: 1.0.0-preview2-003131

branches:  
  only:
    - master
```

I dont think i understand the documentation correctly, Do i need to specify a dotnet restore script? To me it reads like it should do that when adding the solution file in .yml config.
Config file is in this pull request: https://github.com/ArgTang/WebApplikasjonProject/pull/1

**Comment by Joshua-Anderson** [comment]
.NET Core doesn't have a default `script`, so you need to define one yourself in your `.travis.yml`. This is a set of commands that will build and test your project.

**Comment by BanzaiMan** [comment]
Closing.

**Comment by ArgTang** [comment]
Thank you. 
I think the docs could be more clear on this topic for those of us who havent had any experience with CI tools. Maybe provide a travis config that works out of the box for the default .net web application?

**Comment by EdAllonby** [comment]
@ArgTang Yep, I agree. I have been following the progress of the use of TravisCI with DotNet 4.6 for a few months now and I still have no idea how to set up CI for a 4.6+ solution
