### ISSUE TITLE
2 errors from travis ci using mac osx and pyenv

### ISSUE THREAD

**Issue by denfromufa** [travis-ci/travis-ci#6644]
Originally posted here:

https://github.com/yyuu/pyenv/issues/722

**Comment by BanzaiMan** [comment]
What's the problem? You seem to be trying to install Python on OS X with `pyenv`, right? We don't do anything special with that. If the `pyenv` is failing to find the 2.7.12 definition, I'm afraid there is not much for us to do. It could be Homebrew definition, it could be `pyenv` itself, but I am almost certain that it is not our issue.

**Comment by denfromufa** [comment]
@BanzaiMan actually the issue was that osx image provides old pyenv, which does not recongnize python 2.7.12, i fixed this by brew upgrade pyenv

now the issue is following:

installation directory:
    [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-17670.pth'

**Comment by denfromufa** [comment]
i posted more info in the linked issue

**Comment by BanzaiMan** [comment]
I am sorry to inform you that we do not support Python builds on the Mac out of the box (see #2312).

You are installing `pyenv` from Homebrew, so you'd have to ask them what's wrong.
