### ISSUE TITLE
PHP pecl compiles for the wrong version (in 5.6 & 5.4)

### ISSUE THREAD

**Issue by matthiasmullie** [travis-ci/travis-ci#6645]
A related issue (#6490) was filed earlier. In that case, PHP 5.5 environments compiled PECL packages for the wrong PHP version. This has already been fixed for PHP 5.5.

PHP 5.6 & 5.4 environments (at least) still seem to suffer from this same problem, though. Both attempt to configure PECL extensions for PHP 7.0.7 in these 2 examples:
5.6: https://travis-ci.org/matthiasmullie/scrapbook/jobs/161371444#L296
5.4: https://travis-ci.org/matthiasmullie/scrapbook/jobs/161371488#L296

Here's what .travis.yml looks like for this build:
https://github.com/matthiasmullie/scrapbook/blob/00f658d024244b001e635fc868fa3882d6e11090/.travis.yml
And this is the before_script that installs the PECL extension:
https://github.com/matthiasmullie/scrapbook/blob/00f658d024244b001e635fc868fa3882d6e11090/tests/.travis/Apc.sh#L12

**Comment by BanzaiMan** [comment]
Actually, I think this is the same issue as #6490. In https://github.com/travis-ci/travis-ci/issues/6490#issuecomment-244171368 @meatballhat mentioned that the image should be promoted, but the image in use in https://travis-ci.org/matthiasmullie/scrapbook/jobs/161371444#L14 was provisioned *after* that comment.

I'm reopening #6490.
