### ISSUE TITLE
Keeps restarting a build endless

### ISSUE THREAD

**Issue by Pacana78** [travis-ci/travis-ci#6646]
From this morning I experienced this problem building with Xcode 8, the build keeps restarting, I canceled it and I've done another commit to trigger a new one, but I've got the same problem

**Comment by BanzaiMan** [comment]
Thanks for the report. Which job is showing this problem?

**Comment by Pacana78** [comment]
51836216

**Comment by BanzaiMan** [comment]
Please provide the URL. Thanks.

**Comment by Pacana78** [comment]
https://travis-ci.com/team-peanut/peanut-ios/builds/32223808

**Comment by BanzaiMan** [comment]
Thanks. The first one has now started. The second is waiting, since the subscription allows up to one build simultaneously.

**Comment by Pacana78** [comment]
Thank you for your answer, but the problem is that the job will start again in an endless loop, it will never end

**Comment by BanzaiMan** [comment]
It finishes and restarts?

**Comment by BanzaiMan** [comment]
Could you cancel them once, and restart them?

**Comment by Pacana78** [comment]
Yes, I've canceled and restarted it, but the problem is still there. I've also done another commit, but the build never finishes, it keeps restarting

**Comment by Pacana78** [comment]
It is also the same problem reported 1 day ago from another user
Xcode8 image can't run xcodebuild test command #6639

**Comment by Pacana78** [comment]
It's working fine now, thank you :-)

**Comment by janderson-primary** [comment]
I am also experiencing this same problem after updating to XCode8...  What was the solution?

**Comment by Pacana78** [comment]
The problem is that if the build is taking too long, it will automatically restarted. Add | xcpretty at the end of the xcodebuild command
