### ISSUE TITLE
PyPI deployment: Incorrect version used in attempted upload.

### ISSUE THREAD

**Issue by waltherg** [travis-ci/travis-ci#6649]
I have got deployment to PyPI set up like so:

```deploy:
  provider: pypi
  user: ...
  password:
    secure: ...
  on:
    tags: true
    branch: master
```

When tagging my master branch with "v0.3" deployment to PyPI works as expected.
However when then tagging the master branch with "v0.3.1" Travis attempts to upload a "package-name-03.tar.gz" to PyPI which obviously rejects that file.

See logs here:

https://travis-ci.org/markovianhq/nexusadspy/jobs/162538875

Any thoughts on this?

**Comment by BanzaiMan** [comment]
It appears to me that you are trying to upload `0.3` for whatever reason. https://travis-ci.org/markovianhq/nexusadspy/jobs/162538875#L344

https://github.com/markovianhq/nexusadspy/blob/205eeb2add434385b2d2430f1bb5d62ac4b35efd/setup.py#L11

**Comment by waltherg** [comment]
@BanzaiMan thanks so much! Not sure how I missed setting the appropriate value in `setup.py`.
