### ISSUE TITLE
Android build support without the `android` tool

### ISSUE THREAD

**Issue by tir38** [travis-ci/travis-ci#6653]
I just noticed that the `android` tool which Travis relies on is no longer supported. I'm curious if y'all have already given some thought to how to replace it?

https://developer.android.com/studio/tools/help/android.html

**Comment by albodelu** [comment]
[Use sdkmanager](https://developer.android.com/studio/command-line/sdkmanager.html)

[Work in progress here](
http://stackoverflow.com/a/42736695/1009132)

**Comment by albodelu** [comment]
@tir38 Full working sample [here](http://stackoverflow.com/a/42736695/1009132)
