### ISSUE TITLE
Caches that are used can not found by Interface or CLI (and thus also not purged)

### ISSUE THREAD

**Issue by JelteF** [travis-ci/travis-ci#6658]
None of the caches that I have for any of my repos show up. This is both on .org and .com domains.
When I go to the caches page of my repos it will simply show this message:

> No caches have been created yet,
> read more on how to setup caching with your build.

However, I have set them up and they are working, because builds are failing because of outdated caches.

The Travis CLI tool also does not show any available caches, so this is probably a backend bug.

**Comment by renee-travisci** [comment]
This is fixed in production.

**Comment by alerque** [comment]
This is happening again. Since this is the top Google result I'm posting here too ... I see assorted reports on the forum mentioning this too but no solutions.

One example [here](https://travis-ci.community/t/cant-clear-caches-as-caches-settings-page-empty/10058?u=alerque).
