### ISSUE TITLE
Environment variables on travis build

### ISSUE THREAD

**Issue by BandanaPandey** [travis-ci/travis-ci#6660]
I am using travis-ci on my project. I am also using code-climate, so i have to use CODECLIMATE_REPO_TOKEN  and set it as environment variable using travis settings.
On travis build i am getting following::
```
Setting environment variables from repository settings
$ export ENC_KEY=[secure]
$ export CODECLIMATE_REPO_TOKEN =[secure]
```
But i do not want it to be shown. Is there a way by which I can do this??

**Comment by BanzaiMan** [comment]
No, there isn't. These are feedback mechanism so that you can see they are set.

Why do you not want to see them?

**Comment by BandanaPandey** [comment]
@BanzaiMan  Okkk  Got it .
Thanks You
