### ISSUE TITLE
Deploying my Python wheel...

### ISSUE THREAD

**Issue by al3xv3gas** [travis-ci/travis-ci#6663]
Ok, so I've written a Python wheel and I've uploaded the code to GitHub. I've configured travis to do all the testing and to deploy my code. Now my question is, when my code is "deployed" what has to happen to build the wheel and upload it to PyPi? Becuase I think I have done just that, but why am I not seeing a wheel for every commit that I make to the GitHub repo on PyPi? And what would I have to do, for Traviss to uild a wheel every night and upload that wheel to a GitHub repo that would host all the nightly-built wheels?

**Comment by al3xv3gas** [comment]
P.S.: The link to my Repo and the .travis.yml is here: https://github.com/al3xv3gas/vgasscript

**Comment by BanzaiMan** [comment]
https://travis-ci.org/al3xv3gas/vgasscript/jobs/164433751#L250

```
HTTPError: 400 Client Error: A file named "vgasscript-2017.1-py2.py3-none-any.whl" already exists for  vgasscript-2017.1. To fix problems with that file you should create a new release. for url: https://pypi.python.org/pypi
```
Looks like you are trying to upload to the same location from all the jobs within a build.

**Comment by al3xv3gas** [comment]
@BanzaiMan Ok, I I know now what to do. But here is a question: How do I deploy those wheels to a directory inside a Git or GitHub repository (Gitlab in my case)? What settings do I have to change in the travis.yml? Thanks in advance.

**Comment by BanzaiMan** [comment]
What do you mean by "deploy those wheels to a directory"? We only support uploading to PyPI.

**Comment by al3xv3gas** [comment]
Simple: For every new version I want to add the built wheel to this directory: https://github.com/al3xv3gas/carbon-wheels/tree/master/nightly AND to PyPi. PyPi works fine but how about the github repo I just linked? Can I upload the Python wheel to that directory once the wheel has been tested and compiled by TRAVIS? @BanzaiMan

**Comment by BanzaiMan** [comment]
PyPI deployment provider does not support this.

To push the new file to your GitHub repository, basically you'd want to configure a git repo (add user name and email address to the global config), create a commit and push that commit to GitHub.

I'm closing this now. There is not a lot of things to do here.

**Comment by al3xv3gas** [comment]
But here (https://docs.travis-ci.com/user/deployment/pypi/) it says that I can deploy to a custom index. Now if that custom index is  aGitHub repo...what do I have to do? @BanzaiMan

**Comment by BanzaiMan** [comment]
GitHub is not a PyPI index to the best of my knowledge.

**Comment by al3xv3gas** [comment]
Ok but then how would I solve the problem of wanting to automatically upload the finished Python Wheels to that partucular repo? Because I DO NOT want to upload them manually. Give me some steps please!

**Comment by al3xv3gas** [comment]
@BanzaiMan

**Comment by BanzaiMan** [comment]
@al3xv3gas https://github.com/travis-ci/travis-ci/issues/6663#issuecomment-251215694

> To push the new file to your GitHub repository, basically you'd want to configure a git repo (add user name and email address to the global config), create a commit and push that commit to GitHub.

**Comment by al3xv3gas** [comment]
Yes, but how exactly do I do that? @BanzaiMan

**Comment by BanzaiMan** [comment]
The same way you work with git repositories everywhere.

    git config --global user.name "foo"
    git config --global user.email "user@example.com
    git add FILES
    git commit -m "Add FILES"
    git push
