### ISSUE TITLE
PyPI deployment issues

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6665]
So I'm trying to get a project to auto-deploy from Travis CI to PyPI for the first time. However, am running into issues trying to get it to work. Not sure if I'm doing something wrong or what. It seems from the [build log]( https://travis-ci.org/jakirkham/metawrap/jobs/164527224#L659 ) that PyPI expects me to be registered for the deployment to occur. Would have figured this is dealt with behind the scenes, but maybe not. 😕 Any help on this would be appreciated.

**Comment by BanzaiMan** [comment]
What command did you run to get this encrypted value? https://github.com/jakirkham/metawrap/blob/cb5b27302f17b42d2b1b92b1ec1b48b0f3b0a3d3/.travis.yml#L52

**Comment by jakirkham** [comment]
Before starting I made sure the `travis` CLI was up-to-date with `gem`. Right now it is `travis` version `1.8.2`.

Afterwards I ran `travis setup pypi -r jakirkham/metawrap` in the top level directory of the repo. That didn't seem to work.

So I then tried `travis encrypt -r jakirkham/metawrap --add deploy.password`, which is what was done for this build.

In both cases it seems to mess with the `.travis.yml` in ways that didn't seem really necessary (whitespace changes and reordering of sections). So I did some reformatting, but left the `secure` string untouched.

Is there some other way I should be running this or am I missing arguments?

**Comment by BanzaiMan** [comment]
`travis setup …` and `travis encrypt --add` writes to `.travis.yml` in compact format (drops comments and blank lines, normalizes indentation).

Please keep in mind that the secret value is passed as is to bash. If it contains characters with special characters (e.g., `(`, ` `), I suggest enclosing the secret in single quotes (and escape single quotes within it if necessary).

**Comment by jakirkham** [comment]
Good point. Will give that a try. Thanks for the tip.

**Comment by jakirkham** [comment]
Yeah, so I just tried quote the secure string, but am still having issues uploading. In particular, see this [line]( https://travis-ci.org/jakirkham/npctypes/jobs/167132949#L647 ). Have logged into PyPI and can confirm that nothing was uploaded. Any other suggestions?

**Comment by jakirkham** [comment]
Though I think this may be a dup of issue ( https://github.com/travis-ci/dpl/issues/377 ). So I'll close this out and start tracking that one.
