### ISSUE TITLE
xcodebuild exited with 65

### ISSUE THREAD

**Issue by chrisballinger** [travis-ci/travis-ci#6675]
When running tests with xcodebuild, specifically ones targeting the iOS simulator, we often get "exited with 65" errors. https://travis-ci.org/ChatSecure/XMPPFramework/builds/165091671#L3021

We believe it's because the simulator hasn't had a chance to warm up and the test exits prematurely, but aren't exactly sure. The tests pass locally, and only occasionally pass on Travis.

**Comment by kcharwood** [comment]
I'm seeing this as well. Note that rerunning the same failed build will sometimes allow it to succeed, with no code changes.

**Comment by NicholasTD07** [comment]
Me too... I have 5 different targets in my build matrix and every time when CI builds my project, there's always one falling/broken but other four are fine.

For example https://travis-ci.org/NicholasTD07/TDRedux.swift/jobs/165953102

**Comment by gki** [comment]
I'm encountering this.

I've tried some workaround "iPhone SE" (see https://github.com/travis-ci/travis-ci/issues/6422) and "adding sleep" (see https://github.com/travis-ci/travis-ci/issues/4725). But they cannot resolve this issue.

As @kcharwood mentioned, most annoying thing is that the result is unstable. it sometime succeed, but sometime failed, and the result often change by rerunning...

**Comment by NachoSoto** [comment]
Any update on this? It's making Travis basically useless for iOS tests 😕

**Comment by MP0w** [comment]
I opened a radar and Apple asked if I can reproduce it outside travisci... looks like Travis only 😞. It's really unreliable ATM

**Comment by russbishop** [comment]
Anyone having this problem please file a radar. Please configure your CI system to gather log artifacts so when this happens you will have the logs handy.

1. Run `log collect`. It will generate system_logs.logarchive in the local directory.
2. Gather the logs from `~/Library/Developer/Xcode/DerivedData/<project>/Logs`
3. Grab the simulator logs from `~/Library/Logs/CoreSimulator/`, specifically `CoreSimulator.log` and `Simulator.log`

For CI systems it might be helpful to just put this in as an "always run" step at the end of your build and have these files included as artifacts. Then when it fails you'll have the logs ready.

We are interested in solving these problems and appreciate your help. You can send me the radar numbers.

**Comment by MP0w** [comment]
@russbishop ty for explaining how to get the logs. I already opened a radar but I have been asked: "Can you reproduce this outside of the context of Travis, by manually invoking xcodebuild on the command-line?"

*Un*fortunately I never had this issue locally, neither using Xcode nor invoking xcodebuild from command-line.

**Comment by russbishop** [comment]
That's OK, can you grab the logs from the next time it fails, add them to the radar, and send me the radar number?

**Comment by chrisballinger** [comment]
@russbishop Thanks for the instructions! Are the files very large? Can I easily scoop them out of Travis logs via `cat`? I'm not sure of a good way to export file artifacts from our public Travis runs.

**Comment by russbishop** [comment]
They might be a few MB. I haven't used Travis much so I'm not sure how to configure that sort of thing

**Comment by Fengson** [comment]
I am having the same issue. Random Travis Errors 65 after updating to Xcode 8...
Restarting the same job (sometimes as much as 5 times) fixes the issue randomly.
Any updates on this issue?

**Comment by chrisballinger** [comment]
Happening on macOS builds as well: https://travis-ci.org/chrisballinger/ChatSecure-Mac/builds/170019215

**Comment by NicholasTD07** [comment]
Guys check this out. I have done this and it helped me stabilized the
builds a lot tho you still get the error occasionally.

https://discuss.circleci.com/t/xcode-exit-code-65/4284

**Comment by chrisballinger** [comment]
If there is a way to manually and synchronously launch the simulator to
pre-warm it, I think it would solve this issue.

**Comment by Fengson** [comment]
@NicholasTD07 If it still happens, that is not a solution I'm afraid.. :(
Also, which comment exactly helped you out?

**Comment by cotsog** [comment]
Here's a recipe to pre-start/warm up a particular iOS simulator in your Travis CI builds:

```
before_install:
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6 (9.3" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
```

Note that you can change the device and iOS version to your taste. Just ensure that you are picking something listed in the VM when running `instruments -s devices`. You can also use an UDID directly but the recipe above makes it compatible with OS X image changes.

Take also note the builds failing with exit code 65 during the codesigning step in `xcodebuild` can be mitigated by adding `travis_retry` in front e.g.

```
- travis_retry xcodebuild -workspace workspace.xcworkspace -scheme scheme -sdk iphonesimulator [...]
```

This will effectively retry your `xcodebuild` command upon a non-zero exit code up to 3 times. Hopefully, it will reduce the need to manually restart your build as exit code 65 errors seem to be random.

Thank you for your patience.

**Comment by chrisballinger** [comment]
@cotsog Thank you! My other hacks didn't work very reliably, so I'll try this out.

**Comment by adellibovi** [comment]
Do we know if this still happens with the new version of Xcode?

**Comment by jberkel** [comment]
@adellibovi had lots of issue with a build, changed travis.yml to use xcode 8.1 and got a green build immediately. but too early too tell if it really fixes the problem.

**Comment by adellibovi** [comment]
Thanks, @jberkel will give it a try, let's see how it goes

**Comment by adellibovi** [comment]
@jberkel ok, I can confirm that I still get the same random error even with Xcode 8.1. First time went fine than tried again and 65 appeared.

**Comment by jberkel** [comment]
@adellibovi have you tried `travis_retry` as suggested above?

**Comment by adellibovi** [comment]
@jberkel that seems to mitigate the issue

**Comment by russbishop** [comment]
We reworked how the Simulator launches apps in the Xcode 8.2 Beta. It should be more reliable and when it does fail you should see a lot more information in the simulated device logs, including instructions on changing the timeouts. 

I will reiterate since no one took me up on the offer last time: I work on the Simulator. If you file a radar and send me the number I will be happy to look at this. Making CI more reliable is a high priority. If no one is willing to help that makes it much more difficult to figure out what is causing the problem and these short-term bandaids are likely to break again and again.

**Comment by Tzeejay** [comment]
@russbishop Hey I work for CircleCI.com and we would love to gather as much information as we possibly can and provide it to you. Do you prefer this is in a way of Radar or any other way, we could potentially gather a lot.

One thing I noticed even on my local machine is that the Simulator takes longer and longer to boot. Is there any reason for that and can we optimize to cut boot time?
The old Exit Code 65 solution that I came up with and that reliably worked was launching the simulator much in advance via `xcrun instruments -w 'iPhone 7 (10.1)' || true` or similar. rdar://27524047 or https://openradar.appspot.com/radar?id=4977121617248256 for reference.

**Comment by russbishop** [comment]
@Tzeejay The Simulator runs at low priority on the new MacBook to avoid hitting thermal constraints. I don't have a good recommendation for that other than starting the Simulator then waiting 30-60s for it to boot. If you continue compiling or doing other activities the Simulator won't get many CPU cycles. We are aware that people would like faster Simulator boot times.

**Comment by dflems** [comment]
@russbishop:

We see this issue popping up for our OSS projects as well as our private CI (not using Travis). In our case it seems to manifest as `IDETestOperationsObserverErrorDomain Code=3` and/or `DTXProxyChannel error 1` (see also: #6422). In our case, pre-launching the simulator doesn't seem to help. This issue comes up sporadically, but often enough to be a problem and cause flakiness.

Travis and many other services that provide macOS build agents run in a semi-virtualized environment. From my reading, I've gathered that Travis uses MacStadium which runs bare-metal mac minis as well as virtualized hosts running on Mac Pros through a customized VMWare setup. I imagine the free-tier of Travis primarily uses these virtualized hosts. Do you think this factors into the problem at all?

I've certainly noticed weird timing issues on these virtualized hosts. We'll often have to set longer timeouts for testing asynchronous code as short timeouts will fail to fire promptly (presumably because access to the CPU is being shared across many instances).

I've talked to engineers at a few companies that have large-scale macOS deployments in CI but *don't* do any sort of virtualization. They have not reported seeing this particular issue (or at least they've found clever ways around it).

Anyway, thanks for following up on this thread! We'll definitely give the 8.2 beta a shot and see if we can still reproduce this.

**Comment by Ashton-W** [comment]
@russbishop how should we contact you?

**Comment by russbishop** [comment]
@dflems There may be a CPU-starvation component to this, I'm not sure yet. There may also be multiple underlying causes. Can you open a radar?

@Ashton-W Please open a radar and let me know the number.

For anyone filing a radar, including as much of this information as possible is extremely helpful:

Tarball from `sudo sysdiagnose -q`
Contents of `~/Library/Logs/CoreSimulator`
xcactivity logs from your test run `~/Library/Developer/Xcode/DerivedData/<project>/Logs`

**Comment by Ashton-W** [comment]
@russbishop do you have twitter or email?

**Comment by Tzeejay** [comment]
@russbishop 
Thanks for the insight! I had the suspicion that this was the case but was never able to reach anyone.

**Comment by Tzeejay** [comment]
@dflems Machine setup itself isn't really relevant here as I was able to reliably generate Exit Code 65 on a local machine.

It was fixed by letting the iOS simulator boot up first and then continue with whatever you're doing.

**Comment by plu** [comment]
Another possible solution:

```yaml
before_install:
  - gem install simctl --no-rdoc --no-ri --no-document --quiet
  - ruby -rsimctl -e 'SimCtl.warmup("iPhone 6", "iOS 10.1", 300)'
```

The last argument (`300`) is the timeout in seconds, before the warmup is aborted.

The downside is, that it takes quite a bit for the Simulator to be ready:

<img width="744" alt="screen shot 2016-12-29 at 14 46 37" src="https://cloud.githubusercontent.com/assets/31597/21542211/af7cd496-cdd5-11e6-999e-90d0542343d4.png">

Curious how this works?

https://github.com/plu/simctl/blob/master/lib/simctl/device.rb#L107

**Comment by arlo-egg** [comment]
@russbishop I would like to get you the information you need, but am not sure how to extract it from Travis after the build fails. Can you or anybody else help me with this?

**Comment by russbishop** [comment]
@arlo-egg It looks like you are getting a compiler crash unrelated to the Simulator.

**Comment by JESii** [comment]
FWIW: I'm getting the same xcode build error 65 when trying to run an Appium test on a real iOS device (Xcode 8.2.1; Appium 1.6.4(beta); see Appium issue https://github.com/appium/appium/issues/7825

**Comment by rakaramos** [comment]
Anyone has been able to fix the issue already? This is very frustrating.

**Comment by fvvliet** [comment]
Same same

**Comment by russbishop** [comment]
Please try on the Xcode 8.3 beta; several issues have been fixed that should make this more reliable.

**Comment by Tzeejay** [comment]
Personal (favorite) recommendations:

1. Start the iOS Simulator you want to run on early (have a timeout of at least 30 seconds. The more the better). This will prevent a lot of 

```
-> Touching ..../yourproject.xctest

BUILD FAILED
```

2. Split up your `xcodebuild clean build` action and the `xcodebuild test` action into two calls to xcodebuild. This will way you can pass CODE_SIGNING_ALLOWED=NO to the test action and it wont die on you trying to sign your .xctest bundle.

This way you prevent this kind of behavior:
```
-> Touching ..../yourproject.xctest
-> Signing .../yourproject.xctest

BUILD FAILED
```

3. Disable automatic code signing (you should use it in theory). It's still unreliable and sometimes behaves in unpredictable ways. Setup proper signing settings in your project and then import those certs into your CI of choice.

4. If you use xcpretty look at your raw logs. There is usually a lot of information in there as to why your build failed but this never makes it's way through xcpretty.


5. Try saving all the build logs possible and if you run into behavior that you can't explain write radars so that the toolchain can be improved!


I have not tried Xcode 8.3 beta yet so there might be a lot of stuff in there that's fixed. Your mileage may vary.


👋 Tzeejay

**Comment by Ashton-W** [comment]
Good recommendations @Tzeejay, those using fastlane should find actions or configuration for some of these, others we might have to add

**Comment by keith** [comment]
Just a heads up that we're still seeing this in Xcode 8.3.1

**Comment by SamGJohn** [comment]
Try this fix for [xcodebuild exit code 65](https://circleci.com/blog/xcodebuild-exit-code-65-what-it-is-and-how-to-solve-for-ios-and-macos-builds/)

**Comment by carlwright4** [comment]
(#6675)

**Comment by NachoSoto** [comment]
So uhh...  it's coming up on a year since this was reported 😞

**Comment by NachoSoto** [comment]
[Xcode 9 beta 5 release notes](https://download.developer.apple.com/Developer_Tools/Xcode_9_beta_5/Release_Notes_for_Xcode_9_beta_5.pdf) say:

> When under heavy load, xcodebuild test will no longer intermittently fail with ‘Launch session expired before checking in’ or ‘Early unexpected exit, operation never finished bootstrapping - no restart will be attempted’. (32840985)

Does that mean this issues will finally be solved,  @russbishop?

**Comment by NachoSoto** [comment]
This particular error may have been fixed, who knows, but there's still sporadic false negatives going on in Travis...

```
[17:33:39]: â–¸ [35m2017-09-22 17:33:39.960 xcodebuild[6172:24924] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Error retrieving daemon unix domain socket from simulator, failed after 30 attempts.; getenv error: Error Domain=com.apple.CoreSimulator.SimError Code=164 "Unable to getenv("TESTMANAGERD_SIM_SOCK") while not booting or booted.  Current state: Shutdown" UserInfo={NSLocalizedDescription=Unable to getenv("TESTMANAGERD_SIM_SOCK") while not booting or booted.  Current state: Shutdown} If you believe this error represents a bug, please attach the log file at /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/com.apple.dt.XCTest/IDETestRunSession-DC639904-0C42-45C3-A945-7B0A44BA6B66/APITests-CBEB312B-4D35-4152-8DE3-4F6A1E801F97/Session-APITests-2017-09-22_172900-MpXZbA.log" UserInfo={NSLocalizedDescription=Error retrieving daemon unix domain socket from simulator, failed after 30 attempts.; getenv error: Error Domain=com.apple.CoreSimulator.SimError Code=164 "Unable to getenv("TESTMANAGERD_SIM_SOCK") while not booting or booted.  Current state: Shutdown" UserInfo={NSLocalizedDescription=Unable to getenv("TESTMANAGERD_SIM_SOCK") while not booting or booted.  Current state: Shutdown} If you believe this error represents a bug, please attach the log file at /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/com.apple.dt.XCTest/IDETestRunSession-DC639904-0C42-45C3-A945-7B0A44BA6B66/APITests-CBEB312B-4D35-4152-8DE3-4F6A1E801F97/Session-APITests-2017-09-22_172900-MpXZbA.log}[0m


[17:33:39]: â–¸ [35mTesting failed:[0m
```

**Comment by cotsog** [comment]
@NachoSoto: sorry for the continued troubles?

Have you tried pre-starting the iOS simulator in your builds?

You can add the following (or a similar recipe) to do this:

```yaml
before_install:
  - npm install ios-sim -g
  # Pre-start iPhone 7 + iOS 10.2 simulator
  - ios-sim start --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-7, 10.2"
```

`--devicetypeid` values can be found in [the build log](https://travis-ci.org/cotsog/travis_ci_prod_regular/jobs/278714007#L593-L607) or by running `xcrun simctl list` locally.

Let us know if this helps!

Thanks!

**Comment by NachoSoto** [comment]
Why would I have to do that? I'm using a simulator listed [here](https://docs.travis-ci.com/user/reference/osx#Xcode-9.0).

**Comment by cotsog** [comment]
@NachoSoto: Pre-starting/warming up a simulator right at the beginning of a build will help to prevent issues like the one you copy-pasted [above](https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-331517651).

Don't hesitate to send us a link to your build at support [at] travis-ci [dot] com so we can have a closer look.

**Comment by Ronaldoh1** [comment]
I'm also seeing this issue

**Comment by cotsog** [comment]
@Ronaldoh1 could you send us an e-mail at `support [at] travis-ci [dot] com`? Please include the name of you repository and a link/URL to a build showing the exit code 65. Thanks!

**Comment by Ronaldoh1** [comment]
@cotsog I sent an email to support yesterday 👍

**Comment by Ronaldoh1** [comment]
@cotsog I sent an email couple of day ago about this issue and have not heard back from anyone yet.
