### ISSUE TITLE
Erlang 19.1.1

### ISSUE THREAD

**Issue by joedevivo** [travis-ci/travis-ci#6679]
Hello! 

I opened in issue on some other repo a while back with @BanzaiMan about patch releases for Erlang. Patch releases don't seem to end up on erlang.org, but are made available through https://github.com/erlang/otp/releases

19.1.1 was released about a week ago http://erlang.org/pipermail/erlang-questions/2016-September/090464.html and includes some important changes for us to the SSL library. Can you get us support for 19.1.1?

Also, I'd love a way to see all the supported versions of erlang `kerl list installations` isn't really helping too much:

```
$ kerl list installations
R14B02 /home/travis/otp/R14B02
R14B03 /home/travis/otp/R14B03
R14B04 /home/travis/otp/R14B04
R15B /home/travis/otp/R15B
R15B01 /home/travis/otp/R15B01
R15B02 /home/travis/otp/R15B02
R15B03 /home/travis/otp/R15B03
R16B /home/travis/otp/R16B
R16B01 /home/travis/otp/R16B01
R16B02 /home/travis/otp/R16B02
R16B03 /home/travis/otp/R16B03
R16B03-1 /home/travis/otp/R16B03-1
17.0 /home/travis/otp/17.0
17.1 /home/travis/otp/17.1
17.3 /home/travis/otp/17.3
17.4 /home/travis/otp/17.4
```

I know the docs say

> Note that this list does not include releases which are downloaded on demand, such as 18.1 .

but not being able to see any version since 17.4 isn't great.

**Comment by BanzaiMan** [comment]
The OTP Releases are made available on demand as the archives are built by https://travis-ci.org/travis-ci/travis-erlang-builder/builds.

I've initiated the build for 19.1.1 here: https://travis-ci.org/travis-ci/travis-erlang-builder/builds/165290012

It'll be available for use when the jobs succeed.

**Comment by ferd** [comment]
The compilation task failed 26 seconds in.

**Comment by joedevivo** [comment]
@BanzaiMan it needs `ERLANG_VERSION` not `VERSION`

**Comment by BanzaiMan** [comment]
Ooops. https://travis-ci.org/travis-ci/travis-erlang-builder/builds/165297326
