### ISSUE TITLE
add --verbose parameter to Sauce Connect additional parameters

### ISSUE THREAD

**Issue by enriquegh** [travis-ci/travis-ci#6682]
might be related to #1963
Could be useful to add a --verbose parameter on the Sauce Connect parameters to print out the verbose log and have the Customer Support team have more information on a tunnel if needed

**Comment by BanzaiMan** [comment]
Does it expose potentially sensitive information? We don't want leaks.

**Comment by enriquegh** [comment]
it would contain their access key which won't be the best to be exposed.
Is there any way to run this in verbose but storing the logs elsewhere where only the user could retrieve it?
