### ISSUE TITLE
ENH: Error on undefined osx_image

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6684]
Would be nice if `osx_image` was set to a not defined VM the build errored out. Currently it will just use the default image and continue. Thus one may not realize the VM has been dropped or never existed in the first place. Here is an [example](https://travis-ci.org/conda-forge/staged-recipes/builds/165295938#L4) of this behavior.

cc @pelson

**Comment by jakirkham** [comment]
It would be really nice if this was handled before `beta-xcode6.1` is dropped.

**Comment by jakirkham** [comment]
Any thoughts on this?

**Comment by jakirkham** [comment]
Friendly nudge. 😄

**Comment by BanzaiMan** [comment]
This would be a good thing to have, but I am afraid it'll take some careful planning and work to implement.

**Comment by jakirkham** [comment]
I guess I don't know enough about what goes on behind the scenes to comment.

Is there some environment variable that can (or could) tell us which OS X image was selected? We could at least add some kind of assert on our end to make sure it was what we expect it to be.

**Comment by BanzaiMan** [comment]
You can examine the output from `sw_vers -productVersion`, for example. The check will have to happen at run time, I'm afraid.

**Comment by jakirkham** [comment]
Can this please be reopened? AFAIK this has not been solved. Thanks. :)
