### ISSUE TITLE
Segmentation fault using phpunit 5.5.4 on PHP 7.0.11

### ISSUE THREAD

**Issue by danielbachhuber** [travis-ci/travis-ci#6687]
I'm seeing this seg fault on my Travis builds:

```
/home/travis/build.sh: line 48:  8453 Segmentation fault      (core dumped) phpunit
```

Here's the build: https://travis-ci.org/lcache/wp-lcache/jobs/165796240

From https://github.com/lcache/wp-lcache/pull/88

The seg fault is new in the last two days.

**Comment by BanzaiMan** [comment]
Does the problem persist if you restart the build?

**Comment by danielbachhuber** [comment]
> Does the problem persist if you restart the build?

Yes.

**Comment by BanzaiMan** [comment]
Looks like apcu upgraded from [5.1.5](https://travis-ci.org/lcache/wp-lcache/jobs/165371670#L213) to [5.1.6](https://travis-ci.org/lcache/wp-lcache/jobs/165796240#L221). If possible, try pinning this dependency to see if it's an issue with that.

**Comment by danielbachhuber** [comment]
> Looks like apcu upgraded from 5.1.5 to 5.1.6. If possible, try pinning this dependency to see if it's an issue with that.

Good catch, that was it. Thanks for helping to diagnose.

I've submitted a bug report on PHP.net https://bugs.php.net/bug.php?id=73286

**Comment by ceeram** [comment]
good catch indeed, thanks for the find

**Comment by arcanedev-maroc** [comment]
Hi @BanzaiMan, i've the same issue but with 5.6.2 on PHP 7.0

Job: https://travis-ci.org/ARCANESOFT/Auth/jobs/173564144

Best regards

**Comment by BanzaiMan** [comment]
@arcanedev-maroc If the segmentation fault is caused by some native extensions your app uses, I don't think I can help you much, I am afraid.

**Comment by arcanedev-maroc** [comment]
OK. Thanks a lot for your insight @BanzaiMan 👍
