### ISSUE TITLE
configuration matrix error

### ISSUE THREAD

**Issue by stefanseefeld** [travis-ci/travis-ci#6689]
I have defined a build matrix in my .travis.yml file (https://github.com/stefanseefeld/boost.python/blob/develop/.travis.yml), but the actual build only contains a single build job (the last entry in the matrix): https://travis-ci.org/stefanseefeld/boost.python/builds/165867456

If I run `travis show` locally I see all entries in the environment:

```
Config:        env: include=[{:compiler=>"gcc", :env=>"CXX=g++ PYTHON=python CXXFLAGS=-std=c++98"}, {:compiler=>"gcc", :env=>"CXX=g++ PYTHON=python CXXFLAGS=-std=c++11"}, {:compiler=>"gcc", :env=>"CXX=g++ PYTHON=python3 CXXFLAGS=-std=c++98"}, {:compiler=>"gcc", :env=>"CXX=g++ PYTHON=python3 CXXFLAGS=-std=c++11"}, {:compiler=>"clang", :env=>"CXX=clang++ PYTHON=python3 CXXFLAGS=-std=c++98"}, {:compiler=>"clang", :env=>"CXX=clang++ PYTHON=python3 CXXFLAGS=-std=c++11"}, {:env=>"PYTHON=python DOC=1"}], os: linux
```
Is this a syntax error in my .travis.yml file that `travis show` didn't catch, or is there a bug in the Travis CI server ?

**Comment by stefanseefeld** [comment]
Thanks, that fixed it. (I wonder why the command-line `travis` tool didn't tell me...)

**Comment by joepvd** [comment]
The linter does not catch all syntax errors at the moment. It is on the road map to make this more reliable.
