### ISSUE TITLE
Travis occasionaly fails trying to checkout revision using valid commit hash

### ISSUE THREAD

**Issue by vladima** [travis-ci/travis-ci#6690]
As an example, [this build](https://travis-ci.org/Microsoft/TypeScript/builds/165874719) has failed with error
```
$ cd Microsoft/TypeScript
$ git checkout -qf e0e8cf05fb091cdbf8924adfc91a2ac6ffaaad2e
fatal: reference is not a tree: e0e8cf05fb091cdbf8924adfc91a2ac6ffaaad2e
```
and `e0e8cf05fb091cdbf8924adfc91a2ac6ffaaad2e` is [valid merge commit](https://github.com/Microsoft/TypeScript/commit/e0e8cf05fb091cdbf8924adfc91a2ac6ffaaad2e)

**Comment by BanzaiMan** [comment]
That repository has `git.depth: 1`. If there is a commit *after* https://github.com/Microsoft/TypeScript/tree/e0e8cf05fb091cdbf8924adfc91a2ac6ffaaad2e but before https://travis-ci.org/Microsoft/TypeScript/jobs/165874720 started running, we would not be able to check out that commit on the `master` branch.

https://api.github.com/repos/Microsoft/TypeScript/commits/d34916abf8682af409d4b1426f0bb0c2f1700eac/statuses shows that we set the first status to that just such a commit https://github.com/Microsoft/TypeScript/commit/d34916abf8682af409d4b1426f0bb0c2f1700eac at 2016-10-07T17:03:10Z (meaning it saw this commit a few seconds earlier), but we did not start the build until 2016-10-07T17:03:15Z (https://api.travis-ci.org/repositories/Microsoft/TypeScript/builds/165874719.json).

Please increase the depth.
