### ISSUE TITLE
Under OS X julia release is 0.4.7 and julia nightly is 0.6... where is 0.5 ?

### ISSUE THREAD

**Issue by femtotrader** [travis-ci/travis-ci#6692]
Hello,

I have a `.travis.yml` file like

```
language: julia
os:
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
...
```

I noticed that
julia release is 0.4.7 and julia nightly is 0.6...

where is 0.5 ?

Kind regards

PS: see https://github.com/JuliaLang/julia/releases

**Comment by femtotrader** [comment]
CC @tkelman, @ninjin, @staticfloat and @simonbyrne

**Comment by tkelman** [comment]
just use 0.5.

**Comment by tkelman** [comment]
i.e. stop using `release`. better to be explicit about version numbers.

**Comment by femtotrader** [comment]
That's what I did as a temporary fix but I wonder when `release` will be linked to `0.5`.

**Comment by tkelman** [comment]
As soon as https://github.com/travis-ci/travis-build/pull/843 gets merged. I recommend you leave it as the version numbers though, and will be sending a bunch of auto-generated PR's hopefully in a day or two so people don't stop testing on existing releases their REQUIRE file says they should still be supporting.
