### ISSUE TITLE
curl issues with texlive

### ISSUE THREAD

**Issue by adigherman** [travis-ci/travis-ci#6693]
Hi guys. Lately I've started seeing this issue showing on multiple builds:
`The command "curl -Lo /tmp/texlive.tar.gz https://github.com/jimhester/ubuntu-bin/releases/download/latest/texlive.tar.gz" failed and exited with 18 during .`
I tried it today and for the same package I had one fail and one successful build (job ID: 165904149 and 165904173). Any suggestions? Thanks!

**Comment by BanzaiMan** [comment]
Does it persist if you restart the job? https://travis-ci.org/neuroconductor-devel/oro.nifti/builds shows no other failure. Perhaps it was a transient network error?

**Comment by adigherman** [comment]
It's random. I've seen this error quite a few times during the past week with different packages. I'll run some more tests next week and post here. Thanks!

**Comment by BanzaiMan** [comment]
Please reopen the issue if you see the problem again.
