### ISSUE TITLE
cache: ccache - no PATH=/usr/lib/ccache:... set on trusty

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#6695]
<pre>
sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
cache:
  ccache:

script:
  - echo $PATH
</pre>

seems caching ccache isn't occuring on the trusy disto (https://docs.travis-ci.com/user/caching/ undocumented), but also the PATH isn't set to include /usr/lib/ccache before /usr/bin/ for g{cc,++} .
Because of this travis won't build system's won't pick a ccache wrapper to save the output of the compiler.

This would be the cases even if ccache is used perform multiple build passes in a travis job.

**Comment by BanzaiMan** [comment]
That configuration does not define a cache.

```yaml
cache:
  ccache:
```

defines `{"cache": {"ccache": null}}`. You want either:

```yaml
cache:
  - ccache
```

or

```yaml
cache:
  ccache: true
```

**Comment by grooverdan** [comment]
my bad. so sorry. thanks for the explanation.
