### ISSUE TITLE
Getting different images for Mac environment?

### ISSUE THREAD

**Issue by pabloem** [travis-ci/travis-ci#6696]
We have Travis running CI on Mac and Linux for our project (Apache Beam), but for some reason, our Mac images sometimes come with Python's `tox` installed, and sometimes they don't. 

Our tests sometimes [fail because `tox` is already installed](https://travis-ci.org/apache/incubator-beam/jobs/165110120#L62). And they sometimes [succeed because `tox` is not installed](https://travis-ci.org/apache/incubator-beam/jobs/165041185#L62).

Is there a way to ensure that we always get the same Mac image? Or perhaps it's a new change where you guys recently added `tox` to the image?

**Comment by BanzaiMan** [comment]
In general, we do not support Python on the Mac. https://github.com/travis-ci/travis-ci/issues/2312

Having said that, I think this is due to the change in the default Mac image (https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/).

**Comment by BanzaiMan** [comment]
I'm closing this, but if you still see problems, do let us know.
