### ISSUE TITLE
line 45: mono: command not found

### ISSUE THREAD

**Issue by tzachshabtay** [travis-ci/travis-ci#6697]
Hi, I'm getting the error (line 45: mono: command not found), [in this job](https://travis-ci.org/tzachshabtay/MonoAGS/jobs/165212377). This is with Mono 3.12 on Mac. Mono latest on Mac works and Mono 3.12 on Linux works. 

/cc @joshua-anderson @akoeplinger @nterry

Originally asked here: https://github.com/travis-ci/travis-ci/issues/6239#issuecomment-251898269
Based on @joshua-anderson advice, I tried changing the build to use xcode6.4 and it works.

**Comment by BanzaiMan** [comment]
Is this still a problem?

**Comment by tzachshabtay** [comment]
I believe the issue is still there (last time I checked was about a month ago).
Personally not an issue for me though, after having another set of build errors I decided it's not worth the effort and am only compiling with mono latest now.

**Comment by akoeplinger** [comment]
@tzachshabtay Mono 3.12 on Mac works for me, can you please check if you're still seeing the issue or close the issue otherwise?
