### ISSUE TITLE
OpenSSL on Mac disappeared?

### ISSUE THREAD

**Issue by sustrik** [travis-ci/travis-ci#6698]
My project used to build well. Without changing anything related it suddenly started failing with:

```
fatal error: 'openssl/bio.h' file not found
#include <openssl/bio.h>
```

The project is here: https://travis-ci.org/sustrik/libmill

**Comment by gperciva** [comment]
The new version of OSX doesn't include openssl headers, and brew doesn't set up the CFLAGS and LDFLAGS.  One of my company's projects uses this now:

```
 - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS" LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"; fi'
```

You can see it in context here:
https://github.com/Tarsnap/spiped/pull/92

Hope this helps!

**Comment by sustrik** [comment]
That helped. Thanks!

**Comment by sustrik** [comment]
Hm, the problem still persists on *some* configurations. Strange. See https://travis-ci.org/sustrik/libmill/jobs/166527276
