### ISSUE TITLE
Android: Lint fails due to old platform-tools

### ISSUE THREAD

**Issue by Nutomic** [travis-ci/travis-ci#6699]
My Android build works fine, but `./gradlew lint` fails with the following error on travis:

```
The SDK platform-tools version (23.1 rc1) is too old to check APIs compiled with API 24; please update
```

I've seen #6193 and #6040, but these don't fix the problem.

As an example, check out this build (lint is around line 2040):
https://travis-ci.org/Nutomic/syncthing-android/jobs/166016175

The full lint output is here:
https://htmlpreview.github.io/?https://gist.githubusercontent.com/Nutomic/af8699bdefa1ff293f3e4ca4c24737fc/raw/280e75f5168beae7fdfaf1d3a5e4b102b8b6568a/lint.html

**Comment by RoryKelly** [comment]
I have the same issue

**Comment by SUPERCILEX** [comment]
For anyone still encountering this issue, the solution is as simple as putting `android-25` first.

**Comment by Nutomic** [comment]
@SUPERCILEX I just tried that, but it tells me that I didnt accept the SDK license. Any idea what I'm doing wrong?
[Build Link](https://travis-ci.org/syncthing/syncthing-android/builds/178837280)
[Config Link](https://github.com/syncthing/syncthing-android/blob/fix-lint/.travis.yml)

**Comment by SUPERCILEX** [comment]
@Nutomic See: https://github.com/syncthing/syncthing-android/pull/789.
