### ISSUE TITLE
python "nightly" points to 3.7, explicit 3.6 fails

### ISSUE THREAD

**Issue by arekbulski** [travis-ci/travis-ci#6704]
Nightly points to python 3.7 but putting 3.6 explicitly fails.
https://travis-ci.org/construct/construct/builds/166582072

**Comment by BanzaiMan** [comment]
Python 3.6 has not been released, and as a result, it has never been supported. (It was working by accident, when the resulting binary promised that it was a `3.6`.)

If you need the 3.6 development version, use `3.6-dev` instead.

See #6613 and #6599 for more context.

**Comment by arekbulski** [comment]
Thank you, this solves the problem. The "3.6-dev" indeed points to 3.6.
