### ISSUE TITLE
ECONNRESET while using NPM install

### ISSUE THREAD

**Issue by OmgImAlexis** [travis-ci/travis-ci#6705]
This seems to happen every so often, we can a build that just won't run because it can't reach npm's servers. Over the last few months I'd say it's happened 10 - 20 times. We've just moved repo names from `/pymedusa/Sickrage` to `/pymedusa/Medusa` so if any Travis people want to look into this old builds will be found under the old name.

The latest one that won't run is https://travis-ci.org/pymedusa/Medusa/builds/166600170.

**Comment by BanzaiMan** [comment]
Does the issue persist (at the same frequency of errors) if you use `sudo: required`?

**Comment by OmgImAlexis** [comment]
We never had this issue at all when using `sudo: required`. Does the new docker based setup use a different networking setup or something?

**Comment by erikerikson** [comment]
we see this frequently at https://travis-ci.org/Nordstrom/hello-retail.  Examples:
https://travis-ci.org/Nordstrom/hello-retail/builds/225728397
https://travis-ci.org/Nordstrom/hello-retail/builds/224450458

**Comment by OmgImAlexis** [comment]
This seems to happen for us with not only npm but also anything else that uses the network. It seems that travis has outages once or twice a month for up to a few hours but I can never pin point what times they happen.

**Comment by erikerikson** [comment]
Interesting.  We're definitely seeing this issue spread out, albeit semi-randomly much more commonly than once or twice a month.  It semi-frequently "breaks" the build.

**Comment by beberlei** [comment]
This issue breaks about 20% of our builds.
