### ISSUE TITLE
Missing logs on OSX

### ISSUE THREAD

**Issue by sustrik** [travis-ci/travis-ci#6706]
The build failed, but logs are missing. Or, maybe, build timed out before it wrote a single line to logs:

https://travis-ci.org/sustrik/libmill/jobs/166527276

**Comment by BanzaiMan** [comment]
I can see the logs. Could you try reloading the page?

**Comment by sustrik** [comment]
Ok, it's just weirdly formatted. What looks like missing logs on line 817 is actually present at line 166.
