### ISSUE TITLE
Oracle JDK 8u101 is installed on Trusty image, but cannot be used

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#6708]
# Steps to reproduce

Use the following configuration

``` yaml
language: java
sudo: required
dist: trusty
jdk: oraclejdk8
```
# Expected behavior

One would expect to 8u101 to be used (https://travis-ci.org/BanzaiMan/travis_production_test/builds/166776853#L124 shows that this is pre-installed on the current Trusty image).
# Actual behavior

After `jdk_switcher use oraclejdk8` (https://travis-ci.org/BanzaiMan/travis_production_test/builds/166776853#L233), the Java 8 version regresses to 8u65 (https://travis-ci.org/BanzaiMan/travis_production_test/builds/166776853#L239).

**Comment by BanzaiMan** [comment]
On the current Trusty image, I see:

```sh-session
travis@testing-gce-679de391-77ca-4758-a8f0-7886f3715923:/usr/lib/jvm$ ls -l
total 32
lrwxrwxrwx 1 root root   32 Aug 22 00:38 default-java -> /usr/lib/jvm/java-8-oracle-amd64
lrwxrwxrwx 1 root root   20 May  6 23:24 java-1.6.0-openjdk-amd64 -> java-6-openjdk-amd64
lrwxrwxrwx 1 root root   20 Aug 12 10:50 java-1.7.0-openjdk-amd64 -> java-7-openjdk-amd64
lrwxrwxrwx 1 root root   20 Apr 22 13:29 java-1.8.0-openjdk-amd64 -> java-8-openjdk-amd64
drwxr-xr-x 7 root root 4096 Aug 22 00:36 java-6-openjdk-amd64
drwxr-xr-x 3 root root 4096 Aug 22 00:36 java-6-openjdk-common
drwxr-xr-x 7 root root 4096 Aug 22 00:36 java-7-openjdk-amd64
drwxr-xr-x 8 root root 4096 Aug 22 00:37 java-7-oracle
drwxr-xr-x 7 root root 4096 Aug 22 00:36 java-8-openjdk-amd64
drwxr-xr-x 8 root root 4096 Aug 22 00:39 java-8-oracle
lrwxrwxrwx 1 root root   24 Aug 22 00:38 java-8-oracle-amd64 -> /usr/lib/jvm/jdk1.8.0_65
drwxr-xr-x 8 root root 4096 Aug 22 00:37 java-9-oracle
drwxr-xr-x 8 root root 4096 Oct  7  2015 jdk1.8.0_65
```

Notice the symlink `java-8-oracle-amd64`. It points to the 8u65 installation, so when we run `jdk_switcher use oraclejdk8`, it sets `$JAVA_HOME` to the one for 8u65.

The one in `/usr/lib/jvm/java-8-oracle` does point to 8u101.

The arch-specific symbolic link (`java-8-oracle-amd64`) is not supposed to be there, according to https://github.com/travis-ci/travis-cookbooks/blob/64ff883360f3d265b87c072a07f78e9ef0a874fb/cookbooks/travis_java/templates/ubuntu/jdk_switcher.sh.erb#L49, but it does exist, and it is throwing off the switcher.

We can remove this symlink with `travis-build`, but the image should be fixed for the long term.

**Comment by BanzaiMan** [comment]
Tried whitelisting `oracle-java8-set-default`. It does not work on GCE(https://travis-ci.org/BanzaiMan/travis_production_test/builds/175741403).

I think we need `oracle-java8-set-default` on the Trusty image.

**Comment by BanzaiMan** [comment]
@meatballhat Could you take a look? Thanks!

**Comment by BanzaiMan** [comment]
For the record… the current Java 8 version is u111.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/builds/175826756#L247

**Comment by BanzaiMan** [comment]
The hot fix with `travis-build` has been deployed to production.

**Comment by rnicholus** [comment]
`jdk_switcher use oraclejdk8` now uses 1.8.0_101. I'm now (as of the last hour or so), seeing the following error in all of my builds:

```bash
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-8-oracle-amd64
```

Seems related.

**Comment by rnicholus** [comment]
it's in a private project on travis-ci.com. how should I proceed?

**Comment by BanzaiMan** [comment]
Please email us at support@travis-ci.com. Thanks. I'm closing this in the mean time. If anyone else sees an issue with a public repo, do let us know.

**Comment by BanzaiMan** [comment]
Sorry about the continued problems. There is one more issue to make sure that `$JAVA_HOME` is set correctly. I deployed https://github.com/travis-ci/travis-build/pull/889 to rectify this issue.

Could you all test it again? (Restart is fine.)

**Comment by rnicholus** [comment]
Fixed. Thanks for the prompt support!

**Comment by BanzaiMan** [comment]
Sweet. Thanks for the confirmation. I'm closing this again. :-D
