### ISSUE TITLE
Rotating Travis CI token

### ISSUE THREAD

**Issue by alexmuller** [travis-ci/travis-ci#6709]
Hi,

I can't find any way to rotate the value that `travis token` outputs on the command line. I've tried logging out and in again and revoking the Travis app access in my GitHub account. Is it possible to rotate my Travis access token?

**Comment by MariadeAnton** [comment]
@alexmuller thanks for opening this issue! 

At the moment, we need to revoke your Travis CI API token manually. To do so for you, could you please get in touch with us at support@travis-ci.com ?

We'll need your GitHub username as well as the 4 first digits of the tokens you'd like to revoke:

- Travis CI API for public projects,  api.travis-ci.org →  run `travis token --org`
- Travis CI API for private projects,  api.travis-ci.com →  run `travis token --com`

Thank you!
