### ISSUE TITLE
Profile keeps syncing

### ISSUE THREAD

**Issue by vierbergenlars** [travis-ci/travis-ci#671]
When visiting my profile (http://travis-ci.org/profile), it keeps saying it is syncing my data with GitHub.
The page keeps refreshing before it is even completely loaded.
I'm using Chrome. There seems to be no problem when using Firefox.

**Comment by i2000s** [comment]
Hi, sorry for comment on this closed issue. I got the same problem. Profile has been 'synchronizing' for hours. Could you help manually synchronize for me? Thanks.

**Comment by gajjarkishan92** [comment]
Sync is not stopping. Please fix the issue @roidrage

**Comment by BanzaiMan** [comment]
@gajjarkishan92 Sorry for the troubles. After 3 years, your issue is certainly a different issue. I've resync'd your data now.
