### ISSUE TITLE
Builds occurring without .travis.yml?

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6710]
The repo ( https://github.com/conda-forge/pyagrum-feedstock ) has been building on Travis CI even though it has no `.travis.yml` file (never has) and also has the "Build only if .travis.yml is present" enabled. Not sure why this is.

<img width="1554" alt="screen shot 2016-10-11 at 13 16 10" src="https://cloud.githubusercontent.com/assets/3019665/19280679/eefc0ac4-8fb4-11e6-8c38-29b33d7ffefb.png">

<img width="1554" alt="screen shot 2016-10-11 at 13 16 38" src="https://cloud.githubusercontent.com/assets/3019665/19280703/011a1db8-8fb5-11e6-87c0-f667907c7235.png">

**Comment by jakirkham** [comment]
cc @pelson @jschueller

**Comment by jakirkham** [comment]
Have tried toggling the "Build only if .travis.yml is present" setting to see if that makes a difference.

**Comment by jschueller** [comment]
it has now that i enabled osx builds

**Comment by jakirkham** [comment]
Sorry, just noticed that in the PR. Sorry for the noise. Closing.
