### ISSUE TITLE
OS X Backlog

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6712]
Seems jobs are taking a long time to support and the workers have been occupied for the bulk of the day.

<img width="1554" alt="screen shot 2016-10-11 at 19 58 19" src="https://cloud.githubusercontent.com/assets/3019665/19292841/2165ff78-8fed-11e6-8869-aa3616aeee9e.png">

**Comment by BanzaiMan** [comment]
Yes. We are seeing increased traffic. We are processing requests as they come in. Please be patient.

**Comment by jakirkham** [comment]
Ok, only raised as I didn't see something on the status page. Thanks for looking into it.

**Comment by BanzaiMan** [comment]
We are really sorry. Nothing is wrong, but just slowly processing.
