### ISSUE TITLE
Node.js: Option to disable automatic npm install

### ISSUE THREAD

**Issue by beheh** [travis-ci/travis-ci#6713]
Currently (as far as I'm aware) any project using node_js as language and with a package.json present will [automatically](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/node_js.rb#L44) have `npm install` run ([docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Travis-CI-uses-npm)).

With alternative Node package managers popping up I'd like to propose an flag to disable this behaviour. I'd llke to switch a project of mine to [Yarn](https://yarnpkg.com/), but `npm install` would always be run before the `before_script` block is executed, so I'd actually have to `rm -rf node_modules` every single time. This would slow down build time by quite some bit, and even moreso on bigger projects.

**Comment by BanzaiMan** [comment]
You can always override the `install` section.
