### ISSUE TITLE
Build failing trying to run Python scripts within folders

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#6715]
https://travis-ci.org/LolexOrg/Lolex-Tools/jobs/167041994. Any ideas?

**Comment by BanzaiMan** [comment]
You are referring to your files with absolute paths. https://github.com/LolexOrg/Lolex-Tools/blob/d514f56f3f696a54ac7b6b094d339243abe4816c/.travis.yml#L85 I don't know where your files are, but you need to specify the paths correctly.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan How do I do this?
