### ISSUE TITLE
Attempt to print pod --version before bundle install causes error message

### ISSUE THREAD

**Issue by benasher44** [travis-ci/travis-ci#6717]
Hello! [This build](https://travis-ci.org/Instagram/IGListKit/jobs/167102919#L320) has a Gemfile that installs a specific version of CocoaPods. But, travis tries to print the CocoaPods version before running `bundle install`, which results in the following message:
> Could not find proper version of cocoapods (1.1.0.rc.3) in any of the sources

Immediately after that, travis runs `bundle install`, and then the build continues just fine. If there's a Gemfile (and/or install/before_install scripts), travis should wait to print out package version information.

**Comment by BanzaiMan** [comment]
The error is:

```sh-session
$ pod --version
Could not find proper version of cocoapods (1.1.0.rc.3) in any of the sources
```

It tried to find the version of cocoapods defined in `Gemfile`, and couldn't. (Perhaps because of bad rubygems.org index, or whatever.)

It is working now.

**Comment by brianmichel** [comment]
@BanzaiMan this is still happening with our build, but with CocoaPods version 1.1.1 as specified in our Gemfile. 

Seems like this version is properly listed on RubyGems, https://rubygems.org/gems/cocoapods
