### ISSUE TITLE
XCode 8 - Infinite Loop Build. Build restarts over and over and never finishes

### ISSUE THREAD

**Issue by janderson-primary** [travis-ci/travis-ci#6718]
As the title states - My builds seem to be stuck in an infinite loop.

My travis build runs a custom SH script, which does the following:

```

xcodebuild test  -workspace MyProject.xcworkspace -scheme MyProject -sdk iphonesimulator10.0 -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty ; test ${PIPESTATUS[0]} -eq 0

xcodebuild archive -workspace MyProject.xcworkspace -scheme MyProject -archivePath ./build/Release-iphoneos/MyProject | xcpretty

xcodebuild -exportArchive -archivePath ./build/Release-iphoneos/MyProject.xcarchive -exportPath ./build/Release-iphoneos/MyProject.ipa -exportFormat ipa -exportProvisioningProfile "MyProject Ad Hoc Travis"
```

The last thing we do is a command to distribute over crashlytics.

```
if [[ "$TRAVIS_BRANCH" = "development" ]]; then

echo "DEVELOPMENT BRANCH:  Archive + Distribute (Crashlytics)"

./Crashlytics.framework/submit skadjalsdjlkasjdsldjsadkasdj -groupAliases myproject_main_distribution -ipaPath ./build/Release-iphoneos/myproject.ipa  -notifications YES

exit 0
fi
```

The build finishes every time, and even deploys my IPA file to S3 (configured in the travis config file).  Sadly, it just restarts, and loops over and over and over... It never finishes with a success.

**Comment by janderson-primary** [comment]
For the record:

If I just run 

`xcodebuild test  -workspace MyProject.xcworkspace -scheme MyProject -sdk iphonesimulator10.0 -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty ; test ${PIPESTATUS[0]} -eq 0`

independently... Or if I run

```
xcodebuild archive -workspace MyProject.xcworkspace -scheme MyProject -archivePath ./build/Release-iphoneos/MyProject | xcpretty

xcodebuild -exportArchive -archivePath ./build/Release-iphoneos/MyProject.xcarchive -exportPath ./build/Release-iphoneos/MyProject.ipa -exportFormat ipa -exportProvisioningProfile "MyProject Ad Hoc Travis"
```

independently... 

Then the builds work!  They finish, and do not loop infinitely.  It seems like there's some problem with having them both together.

Some people have mentioned in other posts that the log file might be too large.  I have tried to reduce that output using xcpretty... Unfortunately, that doesn't seem to reduce it enough?

**Comment by janderson-primary** [comment]
My current hunch is that this definitely has to do with the size of my console output. 

Running 3 commands in a row, generates a ton of chatter.  It doesn't help that we have a ton of nullability warnings from legacy code.  

If I remove the S3 deployment step (which also outputs a ton to the console), then the build works even with the test, and archive, and export.

**Comment by BanzaiMan** [comment]
Hello. Does your job go over the log limit (4 MB)? If so, we might not be cleaning up the VM if this happens on the Mac. At the moment, we do not have a workaround. Please cancel the job, while we work on a fix.
