### ISSUE TITLE
build error in status image despite success

### ISSUE THREAD

**Issue by shadiakiki1986** [travis-ci/travis-ci#6721]
So my build succeeds on travis-ci, but the status image is still at `build error`.
The only new thing that I did in this build is that I used an `after_script` tag in my `.travis.yml`.
Is it this or is it something else?

Here is the [link to the build](https://travis-ci.org/shadiakiki1986/php-mongodb-utils/builds/167036242)

and here is the status image

[![Build Status](https://travis-ci.org/shadiakiki1986/php-mongodb-utils.svg?branch=master)](https://travis-ci.org/shadiakiki1986/php-mongodb-utils)

**Comment by BanzaiMan** [comment]
Your `master` branch is failing. https://travis-ci.org/shadiakiki1986/php-mongodb-utils/branches

**Comment by shadiakiki1986** [comment]
Ouf... I didn't pay attention to that. Sorry :)
