### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis-ci#6722]
Hi what am I doing wrong? I have my repo at: https://github.com/al3xv3gas/VI and the TRAVIS lint says that my .travis.yml is just fine but why am I getting a build error all the time? Help!!!

**Comment by BanzaiMan** [comment]
https://travis-ci.org/al3xv3gas/VI/jobs/167316558#L145 suggests your `password` is not correctly decrypted.

**Comment by BanzaiMan** [comment]
Which usually means that you didn't encrypt it correctly to begin with.

**Comment by al3xv3gas** [comment]
But when I ran "travis encrypt -r al3xv3gas/VI" I got that string. How can I fix the probelm? @BanzaiMan

**Comment by BanzaiMan** [comment]
Another possibility is that your secret has special characters that prevents the command from running correctly.

**Comment by al3xv3gas** [comment]
But all I want to do is to encrypt my password for PyPi. How do I do that? @BanzaiMan

**Comment by jakirkham** [comment]
xref: https://github.com/travis-ci/dpl/issues/377

**Comment by al3xv3gas** [comment]
Guys my password contains number, lower case letter and upper case letters nd with my other repo the automated Travis CI builds are working. What's going on? @BanzaiMan @jakirkham

**Comment by BanzaiMan** [comment]
@al3xv3gas Could you try it with `travis encrypt -r al3xv3gas/VI --org`?

**Comment by jakirkham** [comment]
So, was just providing that as a suggestion of an issue I ran into recently. Though I don't work for Travis CI so can't comment, @al3xv3gas .

**Comment by al3xv3gas** [comment]
Ok will do. @BanzaiMan 
Point taken. :) @jakirkham

**Comment by al3xv3gas** [comment]
Ok so I tried it and TRAVIS still doesn't like it. @BanzaiMan

**Comment by jezdez** [comment]
@BanzaiMan Hey, I've seen decryption errors in two projects now where I know PyPI deploys worked before that get 401 errors now. Did anything change in the way encrypted variables are decrypted or did something else change in the setup of dpl?

**Comment by BanzaiMan** [comment]
@jezdez Not to my knowledge.

**Comment by BanzaiMan** [comment]
It's become stale.
