### ISSUE TITLE
cdn.travis-ci.org and traviscistatus.com certificate errors

### ISSUE THREAD

**Issue by fniephaus** [travis-ci/travis-ci#6723]
I'm seeing this in a recent Chrome on a public network when visiting traviscistatus.com:
![image](https://cloud.githubusercontent.com/assets/2368856/19355334/486c416c-916a-11e6-8076-31c7e1ecbfba.png)

**Comment by BanzaiMan** [comment]
@fniephaus Could it be a temporary DNS issue? I just tested, and I do not see it.

**Comment by fniephaus** [comment]
Still there, even now that I am on a private and protected WiFi:
![image](https://cloud.githubusercontent.com/assets/2368856/19363396/8c008daa-918a-11e6-9654-9de4e53ace20.png)

**Comment by fniephaus** [comment]
Safari gives me this:
![image](https://cloud.githubusercontent.com/assets/2368856/19363431/bb4a085c-918a-11e6-9a6a-b29e3e4eb46f.png)

**Comment by fniephaus** [comment]
https://news.ycombinator.com/item?id=12702252

**Comment by meatballhat** [comment]
Indeed, a GlobalSign revocation is causing large swaths of internet to experience cert verification problems.  Direct link: https://downloads.globalsign.com/acton/fs/blocks/showLandingPage/a/2674/p/p-008f/t/page/fm/0

**Comment by fniephaus** [comment]
Mh, now things seem to have gotten a whole lot worse:
![image](https://cloud.githubusercontent.com/assets/2368856/19381936/327610a6-91fe-11e6-9deb-a4e2e6f26947.png)
