### ISSUE TITLE
html5lib installing error

### ISSUE THREAD

**Issue by tarsisazevedo** [travis-ci/travis-ci#6724]
this lib requires setuptools > 18.5 and travis has just 12.0.5.
I put setuptools in my requirements but the problem still happening
You can see the problem in this build: https://travis-ci.org/cobrateam/django-htmlmin/jobs/167441871

**Comment by BanzaiMan** [comment]
I don't think this is a Travis issue. Your dependencies do not resolve correctly if I try it on my machine.

**Comment by tarsisazevedo** [comment]
@BanzaiMan what error are you seeing?
I installed it on a empty virtualenv and it works. 

My enviroment:
OSX 10.11.6
python 2.7.12
pip 8.1.2
virtualenv 15.0.2

**Comment by joepvd** [comment]
The problem here seems to be that the `pip` in the Makefile does not understand the virtual environment, and uses a wrong pip. Not sure what kind of magic happens when a virtual environment is sourced, so the following is probably incomplete but might be sufficient as a workaround:

``` yaml
before_install:
    - export PATH="$(dirname $(which python)):$PATH"
```

**Comment by BanzaiMan** [comment]
Looks like the issue has been resolved. https://github.com/cobrateam/django-htmlmin/pull/106#issuecomment-253954062
