### ISSUE TITLE
Added environment variables by file

### ISSUE THREAD

**Issue by sonance207** [travis-ci/travis-ci#6728]
I was trying to do something similar that I do in docker-compose.yml

ex.
    env_file:
      - ./mysql/.after_build_env

**Comment by BanzaiMan** [comment]
Could you elaborate on what you are trying to do?

**Comment by sonance207** [comment]
So I want Travis to use a file that has Linux environment variables in it instead of adding them one by one. The reason why I want to do this is I want my docker compose and Travis to share the same file for environment variables.

**Comment by BanzaiMan** [comment]
You can run `source ./mysql/.after_build_env`. Adding this seems unnecessary to me.

**Comment by sonance207** [comment]
ping

**Comment by BanzaiMan** [comment]
Hmm. The script compilation failed for some reason. The YAML file looks good. Does it fail to compile if you restart it?

**Comment by BanzaiMan** [comment]
Could you retry `source`? Thanks.

**Comment by BanzaiMan** [comment]
I am closing this as it's become stale. If you are still having problems, do let us know.
