### ISSUE TITLE
Cannot access travis-ci.org because of certificate errors

### ISSUE THREAD

**Issue by fniephaus** [travis-ci/travis-ci#6731]
Sorry for opening another bug, but I've mentioned this 5 hours ago and didn't get a reply: https://github.com/travis-ci/travis-ci/issues/6723#issuecomment-253747664.

**Comment by fniephaus** [comment]
This fixed it for me on macOS Sierra:
https://news.ycombinator.com/item?id=12702498

**Comment by MariadeAnton** [comment]
Thanks for reporting, @fniephaus!

Our CDN provider's Certificate Provider currently has [an issue](https://www.globalsign.com/en/customer-revocation-error/). We're working with them to mitigate it.

They're recommending [the following instructions](https://support.globalsign.com/customer/portal/articles/1353318) to remove invalid certificates from the cache.

For macOS:

> If you’d like to delete both OCSP and CRL cache, in a terminal, enter the following command:
`sudo rm /var/db/crls/*cache.db`

**Comment by fniephaus** [comment]
Thanks, @MariadeAnton. Unfortunately, that didn't fix it for me, but this one did:
```
sqlite3 ~/Library/Keychains/*/ocspcache.sqlite3 'DELETE FROM ocsp WHERE hex(serialNum) IN ("040000000001444EF03E20", "040000000001444EF04247");'
```

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
It looks like some of our users are still experiencing connectivity issues due to cached OCSP responses, we are going to check with our upstream CDN provider if there are additional measures we can take to mitigate this.
