### ISSUE TITLE
Can't log in to website with GitHub

### ISSUE THREAD

**Issue by orome** [travis-ci/travis-ci#6733]
When I try to "Sign in with GitHub" to https://travis-ci.org/, I get

> could not resolve github token

I've no clue what the source of this might be. I get no error message beyond that text alone on the webpage I'm taken to when I click on the "Sign in with GitHub" button.

**Comment by famousgarkin** [comment]
The same goes for adding Travis CI integration to GitHub account via https://github.com/integrations/travis-ci. Sometimes it dies with the above, sometimes with

> not a Travis user

**Comment by BanzaiMan** [comment]
@famousgarkin GitHub is currently having a DNS issue, so you cannot get authenticated through them. Sorry. https://twitter.com/githubstatus/status/789433336083001344

**Comment by BanzaiMan** [comment]
If the issue persists, please email us at support@travis-ci.com. Thanks.
