### ISSUE TITLE
Repository not syncing

### ISSUE THREAD

**Issue by bpbond** [travis-ci/travis-ci#6734]
I can't get my https://travis-ci.org/JGCRI/hector/branches to sync with what's actually on GitHub. It lists only two inactive branches (and is out of date by months); the GitHub repo has many active ones. Travis doesn't even see `master`. I've tried logging in and out, revoking permissions on GitHub and re-establishing...nothing has worked.

Thanks!

**Comment by BanzaiMan** [comment]
Do these branches have any build? https://travis-ci.org/JGCRI/hector/builds shows that only `ci` and `project_lib_target` do.

**Comment by bpbond** [comment]
That's what it shows, but it's wrong: branch `ci` (listed on that page) doesn't even exist anymore. Travis-ci is receiving a push notification correctly from GitHub, but then it tries to pull the nonexistent branch. I can't get it to update (i.e., see the current branches in the repo).

**Comment by BanzaiMan** [comment]
Did you try resyncing data on your profile page?

**Comment by bpbond** [comment]
Yes, many times; Travis declares things synced, but the branch list doesn't change at all. As noted above, I've also un- and re-linked Travis and GitHub.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/JGCRI/hector/requests shows that you have disabled push builds. Could you try re-enabling pushes again?

**Comment by bpbond** [comment]
Thanks @BanzaiMan . Did this, and no change - the "branches" remain un-updated, and the build fails because it can't pull the `ci` branch (which no longer exists). Thanks.

**Comment by BanzaiMan** [comment]
@bpbond Sorry for the delay. I checked on our end, and it appears that the webhook with GitHub is invalid. Could you try disabling and re-enabling Travis at https://travis-ci.org/profile/JGCRI?

**Comment by bpbond** [comment]
No problem–thanks for staying with this.

...hey, thank you, it's now working! Excellent. Much appreciated @BanzaiMan

**Comment by BanzaiMan** [comment]
Sweet! Thanks for the confirmation.

**Comment by jeremysf** [comment]
I am having the same problem, but no amount of sync with github/enabling/disabling in Travis or github is working. In my case, the repository is in an organization. I have a "master" branch, and on github.com, I have an "aws" branch but Travis can't see it no matter what I do.

Any ideas?

**Comment by lpantano** [comment]
same problem here, it is an organization.

**Comment by CamiloGarciaLaRotta** [comment]
For anyone who might need it:

I encountered the same problem, my setup was the following:
- I am admin of repo
- The repo is part of an organization of which I am not the admin
- The organization is public, the repo is private

None of the pushes to the branches of the repo were triggering builds on Travis-ci **.com** (Because Private repo)
The reason was that the hook on GitHub was pointing towards  Travis-ci **.org** (Probably when the hook was configured my project was public)

I deleted the hook, set up a new one adding my private token and pointing to the `https://notify.travis-ci.com` domain

**Comment by jaksnair** [comment]
travis-ci will consider **only** your **default** branch of the project hooked. 
When I updated the default branch, it reflected in travis-ci.
Perhaps this limitation is only if you don't have a license (DISCLAIMER : may be, am not sure).
