### ISSUE TITLE
Webhook with different port not being invoked.

### ISSUE THREAD

**Issue by Cypher121** [travis-ci/travis-ci#6735]
I have a webhook configured to fire after build for one of my repositories: https://github.com/Magneticraft-Team/Magneticraft/blob/kt1.9/.travis.yml#L13-L14

Replacing requestbin with URL of my server (as seen [here](https://github.com/Magneticraft-Team/Magneticraft/commit/a6650141f28e81112ed2bb14424034bfe17f452e#diff-354f30a63fb0907d4ad57269548329e3R14)) results in request never reaching the server. Server is not the issue, since github's own webhook target's same host and port and works perfectly. Sending a request to URL manually works too.

My guess is that the error is in how custom ports are handled.

**Comment by BanzaiMan** [comment]
When was the last time you tried sending webhook to this URL?

**Comment by Cypher121** [comment]
I finally had time to test it some more and apparently it's not on travis end, most likely my ISP. Moved server to a different host with same url and port, works perfectly now. Still trying to figure out why github worked.
