### ISSUE TITLE
Access error when building dependencies on OSX

### ISSUE THREAD

**Issue by sustrik** [travis-ci/travis-ci#6738]
I have a dependency installed as desribed here:

https://docs.travis-ci.com/user/installing-dependencies/

However, the build fails on OSX with:

```
/usr/local/bin/ginstall: cannot create regular file '/usr/lib/libdill.6.dylib': Operation not permitted
```

On Linux, everything works just fine.

Here's a link to a failed build:

https://travis-ci.org/sustrik/dsock/jobs/168022444

**Comment by BanzaiMan** [comment]
I don't think you have write permission to `/usr/lib`.

**Comment by sustrik** [comment]
Yes, correct. Yet, the page linked above suggest installing dependencies into /usr. Where should one install instead?

**Comment by BanzaiMan** [comment]
Looks like you were able to overcome it. https://travis-ci.org/sustrik/dsock/jobs/216630952#L1156
