### ISSUE TITLE
Provide more minimal base image for Docker

### ISSUE THREAD

**Issue by LebedevRI** [travis-ci/travis-ci#6739]
Hi.

I'm not sure it is important, but now that docker images can be used as part of the build,
i think it would be nice to have a "minimal" base VM image (the one that is being chosen based on `language`, `sudo`, `services: - docker`), that would only contain:
- the ability to start docker image itself
- git / etc

I.e. no compilers, no interpreters.

**Comment by vielmetti** [comment]
The `alpine` Docker image would be ideal for this.

**Comment by LebedevRI** [comment]
Hmm, now that i have discovered `language: generic`, this may not be needed after all.

**Comment by BanzaiMan** [comment]
As pointed out, `language: generic` might suffice.

I'm closing this for now.
