### ISSUE TITLE
PyLint version reporting false errors

### ISSUE THREAD

**Issue by chrisspen** [travis-ci/travis-ci#6740]
I'm seeing some strange error reports from the version of PyLint available in Travis-CI.

I have some Python code like:

```
from multiprocessing import current_process
current_process()
```

When I run PyLint in Travis-CI to check my code, it gives me the error:

```
E:2,1: current_process is not callable (not-callable)
```

However, according to both the Python 2 and [Python 3 docs](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.current_process), this most certainly is a callable.

Oddly enough, I can't reproduce this error locally. My local version of PyLint doesn't see any problem, as I would expect. Why is Tavis-CI's PyLint behaving differently?

I'm running Ubuntu 16 on my localhost, and I have the most recent pylint==1.6.4. According to the logs, Travis is installing the identical version of pylint.

See the full error at https://travis-ci.org/chrisspen/django-chroniker

**Comment by BanzaiMan** [comment]
Is this still a problem? Recent builds are passing.

**Comment by chrisspen** [comment]
Yes, I don't remember what the exact problem was, but I was able to resolve it myself.
