### ISSUE TITLE
stale cert db

### ISSUE THREAD

**Issue by jhoblitt** [travis-ci/travis-ci#6744]
kernel.org changed its tls cert on Oct 10th. Since then, I have a job that fails downloading a git source tarball:

```
$ curl -# -L -O "https://www.kernel.org/pub/software/scm/git/git-2.2.2.tar.gz"
curl: (35) Unknown SSL protocol error in connection to www.kernel.org:443 
```

I am unable to reproduce this in another env. I suspect the travis container image must have a cert db that is more that 3 months old.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by jhoblitt** [comment]
https://travis-ci.org/lsst/lsstsw/jobs/168335934

**Comment by BanzaiMan** [comment]
Does this not happen on Precise? I tried updating the `ca-certificates` to the latest version, but it still fails to connect. https://travis-ci.org/BanzaiMan/travis_production_test/builds/169690628#L230

The Trusty image works, so use that instead. https://travis-ci.org/BanzaiMan/travis_production_test/builds/169691047
