### ISSUE TITLE
golang: comparison of parsed, Truncated dates fails 

### ISSUE THREAD

**Issue by tdi** [travis-ci/travis-ci#6746]
Hi,

When you compare dates that are both truncated with `time.Truncate`, and one of them is parsed with `time.Parse`, the test fails in travis-ci. It works locally on OSX and Linux, go version 1.6 and 1.7. 

Below is a working example: 

```go
func TestDatesWhichFails(t *testing.T) {
	now := time.Now()
	date2 := time.Now()
	parsed, _ := time.Parse(time.RFC3339, date2.Format(time.RFC3339))
	if now.Truncate(time.Hour) != parsed.Truncate(time.Hour) {
		t.Error("Dates differ", now.Truncate(time.Hour), parsed.Truncate(time.Hour))

	}
}
```

On the other hand this works:
```go
func TestDates(t *testing.T) {
	now := time.Now()
	parsed := time.Now()
	if now.Truncate(time.Hour) != parsed.Truncate(time.Hour) {
		t.Error("Dates differ", now.Truncate(time.Hour), parsed.Truncate(time.Hour))

	}
}
```

Example project can be found in https://github.com/tdi/travisgodate and https://travis-ci.org/tdi/travisgodate.

**Comment by BanzaiMan** [comment]
Could you try reproducing the error with our Docker image on quay.io? https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

**Comment by tdi** [comment]
@BanzaiMan I will try and get back to you.

**Comment by tdi** [comment]
@BanzaiMan I used travis-go image and could reproduce the problem. 
![image](https://cloud.githubusercontent.com/assets/376847/19470463/f4293a4c-951f-11e6-9a61-a4d0897c5fc2.png)

**Comment by BanzaiMan** [comment]
I don't know about Go's date time object models, but in some cases Time's equality requires a lot more than just seconds (even when the standard display of those objects stop at seconds). In Ruby, for example:

```
[1] pry(main)> t = Time.now; u = Time.now; nil
=> nil
[2] pry(main)> puts t
2016-10-18 15:26:26 +0200
=> nil
[3] pry(main)> puts u
2016-10-18 15:26:26 +0200
=> nil
[4] pry(main)> t == u
=> false
[5] pry(main)> t.usec
=> 645008
[6] pry(main)> u.usec
=> 645009
```

**Comment by tdi** [comment]
@BanzaiMan That is why, in my code dates are rounder to the full hour. Notice that example without pause works, the problem is just when one of the dates is parsed. Weird it works everywhere just fine. I will play around with it in travis docker machines and see what differs. https://golang.org/pkg/time/#Time.Truncate

**Comment by tdi** [comment]
I just checked it. The same binary works ok on host systems (dates are equal) but does not in dockers! I checked Travis docker image and the golang image. I will file a bug to the golang team.

**Comment by tdi** [comment]
I am investigating, anyways this is not a travis problem direcly. This is locale problem in docker containers. I am investigating further.

**Comment by BanzaiMan** [comment]
@tdi Thanks for the updates.
