### ISSUE TITLE
Error linking R package with fortran on OSX

### ISSUE THREAD

**Issue by rubak** [travis-ci/travis-ci#6749]
Hi @craigcitro, @hadley and @jimhester

I really hope you can help me out with this one. I just helped my colleague @hojsgaard setting up travis for his repo [gRbase](https://github.com/hojsgaard/gRbase) and it checks just fine on Linux but on OSX there is an error when installing the package. It links to fortran using $(FLIBS) in the `Makevars` file, and the error seems related to linking to fortran (or the warning about the library location just before the error) as seen here:
https://travis-ci.org/hojsgaard/gRbase/jobs/168618083#L1161

**Comment by rubak** [comment]
Maybe the solution is to do as described in [this blog post](http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/) and add the following commands when you setup the travis environment for R:
```
curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2
sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /
```
Note that in the blog post comments @bbolker mentions that in some versions of tar on OSX it may be necessary to

> use bunzip2 first and then used the second line (without the .bz2 extension) to unpack the tarball

**Comment by jimhester** [comment]
I think that sounds correct, could you try adding those commands to your `.travis.yml` to verify if works? If so we can add that to the build steps for OS X.

**Comment by rubak** [comment]
I can confirm that adding `sudo: required` and the two commands above to `before_install:` makes the package install correctly. Let me know when you have added the commands to the build steps for OS X and if there is anything I can do to help you test things.

**Comment by rubak** [comment]
Hi @craigcitro, @hadley and @jimhester

Sorry for reopening this, but apparently it still isn't possible to compile fortran code with the default OSX image/container. I didn't try to add any yaml to install gfortran via homebrew as I was under the impression that this should be done automatically now, and I would rather help debug the community solution rather then find my own workaround. When installing `spatstat` for R-devel on OSX we have a failing dependency `deldir` which tries to compile fortran code, but fails with the following error:
`make: gfortran-4.8: No such file or directory`

The log is here, but it really doesn't say much more:
https://travis-ci.org/spatstat/spatstat/jobs/288393610#L236-L237
