### ISSUE TITLE
PyPI deployment fails with `sh: twine: command not found`

### ISSUE THREAD

**Issue by anthrotype** [travis-ci/travis-ci#6750]
Hello,

the auto deployment to PyPI is failing with my Travis CI osx builds, with the following error:
```
sh: twine: command not found
```
https://travis-ci.org/googlei18n/compreffor/jobs/168684315#L538

(The fact the the build itself passes even though deployment fails I guess is a different issue...)

I don't know what has changed in the meantime, because the very same setup used to be working for our previous release.

I also noticed the warning about PATH, but am not sure if that's related or not:
```
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p648'.
```

Thank you for your help.

**Comment by BanzaiMan** [comment]
This failed deployment is running on a Mac, and we do not currently support Python on it. I think the Python binary is installing `twine` in a place the deployment utility cannot find. https://travis-ci.org/googlei18n/compreffor/jobs/168684307, running on Linux, can deploy it successfully.

**Comment by anthrotype** [comment]
the reason why `twine: command not found` was because the cleanup step was deleting the `venv` folder in the working directory where twine had been installed.
Adding `skip_cleanup: true` for the PyPI deployment fixed the issue.
Thank you.
