### ISSUE TITLE
Travis output timeout

### ISSUE THREAD

**Issue by LaurentGoderre** [travis-ci/travis-ci#6753]
I added some progress indicator to my task that was taking longer than 10 minutes (adding a `.` every 30 seconds) but it still thinks that the log received no output.

I was wondering, does it not see it because it's not a new line?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by LaurentGoderre** [comment]
https://travis-ci.org/wet-boew/GCWeb#L2829

**Comment by BanzaiMan** [comment]
How are you writing `.`? Is it really writing to STDOUT when the job is terminated?

If you add up all the timed commands before `npm run-script travis_after_success`, it is about 14 minutes. With 4 dots every 30 seconds, that is about 16 minutes. If you add the silence of 10 minutes, you get 26 minutes, which is roughly the length of time this build ran. It seems to me that your job really stopped running (and writing to STDOUT).

**Comment by LaurentGoderre** [comment]
Perhaps you are right, maybe I ran into another barrier. Is there a size limit on the VMs?

**Comment by BanzaiMan** [comment]
You can try using GCE with `sudo: required` (https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments) if you suspect having more resources helps your build.
