### ISSUE TITLE
Incorrect formatted secure environment variable leaks content

### ISSUE THREAD

**Issue by kpstolk** [travis-ci/travis-ci#6754]
I added a private key as a secure environment variable, but it seems like I have to escape the input (newlines?) when configuring it?

Now the build fails and outputs the content of the supposedly secure variable, see [example log output](https://travis-ci.org/kpstolk/KP.GmailApi/jobs/169066248):

> /home/travis/build.sh: line 45: export: `KEY-----<MY PRIVATE KEY>': not a valid identifier
> /home/travis/build.sh: line 45: export: `KEY-----n': not a valid identifier

Besides that I shouldn't be able to configure a faulty environment variable at all?

**Comment by BanzaiMan** [comment]
Closing in favor of #1775.

**Comment by kpstolk** [comment]
@BanzaiMan Can you tell me what to escape when adding an environment variable? It seems like the build fails when I put something like `-----BEGIN PRIVATE KEY-----` into a variable.

#1775 has a different error `syntax error near unexpected token `('`

**Comment by BanzaiMan** [comment]
@kpstolk

When incorrectly formatted data leak into the shell script, the value is printed in the error message by Bash. This is the general problem.

Sometimes the issue manifests as `syntax error` (when the value is interpreted as a Bash command or other constructs) sometimes as `not valid identifier` (when the value contains `=`, say).
