### ISSUE TITLE
Build addons for Firefox does not include Dev or Nightly versions

### ISSUE THREAD

**Issue by jrbenny35** [travis-ci/travis-ci#6755]
Currently Travis supports the downloading of the Latest, Latest-Esr and Latest-beta versions of firefox. However, there is not support for the Developer and Nightly versions of firefox.

I would like to see if someone could mentor me in adding this functionality. I have a good idea of how I would do it.

Nightly downloads are available from: https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/

Developer Downloads are available from: https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=osx&lang=en-US. This url is using osx as the os.

For the Developer edition the current way of downloading Firefox would just need to include, firefox-aurora-latest as an option. For Nightly, it is an entire new url and directory folder. I am thinking a simple RegEx to look for the .linux-x86_64.tar.bz2 for linux and .mac.dmg for Osx.

Please let me know what you think. I will get my local dev environment up to contribution status per the docs.

Thanks!

**Comment by BanzaiMan** [comment]
This was resolved by https://github.com/travis-ci/travis-build/pull/864.
