### ISSUE TITLE
Branch to branch pr closed and now builds do not work

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#6759]
Go to github.com/lolexorg/Lolex-Tools/tree/Beta and look at the commits. Last two have not had builds.

**Comment by BanzaiMan** [comment]
Please see https://travis-ci.org/LolexOrg/Lolex-Tools/requests. Please email us at support@travis-ci.com to discuss this further.

I'm closing this now.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan OK, I don't see why there was a problem in the first place, but ok.
