### ISSUE TITLE
Location of docker images for local debug

### ISSUE THREAD

**Issue by over64** [travis-ci/travis-ci#6763]
Hi, guys. Where I can download docker image, used for my build like `Using worker: worker-linux-docker-846de492.prod.travis-ci.org:travis-linux-9` ?
I tried to found here https://quay.io/organization/travisci, but not found. How I need to decode this version to versions published on quay.io?

Also I have some misunderstanding why my build uses different containers. After this silent migration I have broken build - https://travis-ci.org/GreatFruitOmsk/screenly-ose/builds/168907471. Is it organization policy to update containers?

Thanks a lot

**Comment by BanzaiMan** [comment]
Your job needs the python image. See https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally for more information.

**Comment by BanzaiMan** [comment]
There is only one image in use, by the way, and it is the latest one at the time the Docker host was provisioned.

**Comment by over64** [comment]
thanks))
