### ISSUE TITLE
Cannot authenticate on Travis CI

### ISSUE THREAD

**Issue by SylvainCorlay** [travis-ci/travis-ci#6764]
could not resolve github token

**Comment by narendravaghela** [comment]
I am facing the same issue. It redirects to https://api.travis-ci.org/auth/handshake and "shows could not resolve github token"

**Comment by BanzaiMan** [comment]
GitHub is currently having a DNS issue, so you cannot get authenticated through them. Sorry. https://twitter.com/githubstatus/status/789433336083001344

**Comment by BanzaiMan** [comment]
DNS issue should now be resolved. I'm closing this. If you see this problem, do let us know.

**Comment by probonopd** [comment]
Still getting this.

**Comment by narendravaghela** [comment]
Still facing an issue with syncing with GitHub.
