### ISSUE TITLE
Keeping an OS X 10.9 

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6765]
Is there any chance we could keep one OS X 10.9 image when culling the herd of OS X images?

**Comment by jakirkham** [comment]
So we have been using this to set a certain level of compatibility at [conda-forge]( http://conda-forge.github.io/ ). To be more specific, we have 1200+ feedstocks maintained by a group 260+ people that were implicitly relying on the 10.9 XCode 6.1 VM image and have likely surpassed 1M downloads given we were quite close back in [June]( https://anaconda.org/tonyfast/forge_interactive/notebook?version=2016.06.27.1214 ) (though I don't have more recent figures on hand).

While we understand that there are good motivations for dropping it and that it should be possible to still build for the 10.9 target using XCode 6.4 on 10.10, it is going to take us a little while to retool properly. The switch to 10.11 as default has helped us become aware of the scope of this work. A fair bit of this time has been spent making sure people don't accidentally build on 10.11, but are actually building for 10.9.

However, more changes will be required to make sure people are really building with the 10.9 SDK on the XCode 6.4 images as we switch over to them. Given that, would it be reasonable to ask to hold onto the 10.9 XCode 6.1 image until the end of the year? If not, it would be good to know what other sorts of constraints we are working with.

Please let us know either way. Thanks again for your help.

**Comment by jakirkham** [comment]
Further should add we won't get a warning when `beta-xcode6.1` becomes undefined even if we are specifying it, which is a real problem. I would really expect that if `beta-xcode6.1` disappeared on Oct 31 that setting `osx_image` to `beta-xcode6.1` would be an error not a quiet reversion to the default image. Please see issue ( https://github.com/travis-ci/travis-ci/issues/6684 ) for details.

**Comment by meatballhat** [comment]
The current plan is that we will keep the Xcode 6.1 images until January 20th, 2017, with the stipulation that beyond November 8th, 2016, we will not actively support said images.  Please ask questions if you're unsure about exactly what this means! :heart:

**Comment by jakirkham** [comment]
This is really great news! Thanks so much.

As we prepare to upgrade, I would be very curious to know if there are any other OS X image changes in the pipeline that we need to be aware of.

**Comment by mwcraig** [comment]
Excellent, thank you!

**Comment by jakirkham** [comment]
So, I saw this message in a [build]( https://travis-ci.org/conda-forge/ibis-framework-feedstock/jobs/177540562 ) recently.

>  This job is using an [OS X image that will be retired on Monday, Nov 28th at Noon PST]( https://blog.travis-ci.com/2016-11-17-retiring-some-osx-images/ ). After that this build will be routed to our [Xcode 6.4 image]( https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-6.4 ).

I'm a little confused as to what it means as it seems to contradict the [blog post]( https://blog.travis-ci.com/2016-11-17-retiring-some-osx-images/ ) w.r.t. `beta-xcode6.1` images. Could someone please clarify whether `beta-xcode6.1` is still going to be available until mid-Jan or not?

Also, a minor point, it seems the [blog post]( https://blog.travis-ci.com/2016-11-17-retiring-some-osx-images/ ) references Jan 17 as the last day `beta-xcode6.1` will be available while previously here we were [quoted Jan 20]( https://github.com/travis-ci/travis-ci/issues/6765#issuecomment-256703076 ). Is that an error in the blog or has this date been updated?

Thanks in advance.

**Comment by jakirkham** [comment]
Any thoughts on these questions?

**Comment by jakirkham** [comment]
Given today is Nov 28th, could we please get an answer to this question?

**Comment by solarce** [comment]
@jakirkham sorry for the delays, those are both oversights on my part. We'll honor the original date of Jan 20th. I'll update the blog post and our web UI notification later today. Sorry for the confusion.

**Comment by jakirkham** [comment]
No worries. Thanks for letting us know. 😄

**Comment by solarce** [comment]
@jakirkham as you make progress, can you update this issue with the outcome of your using the 10.9 SDK in our 10.10/Xcode 6.4 image? I think it's something that would be helpful for other community users and may warrant an addition to our official docs if it works well. Thanks!

**Comment by jakirkham** [comment]
Of course. Happy to help.

**Comment by carlosperate** [comment]
So will 10.9 definitely go away on January 2017? Is there any chance that date might get extended?

**Comment by ntoll** [comment]
More evidence for prolonging the availability of this image... we're building software to be used in schools. Often public schools all over the world have little option to upgrade and hardware can have a lifetime of up to a decade or more. Since we don't want to exclude schools for whom buying the latest and greatest is not an option we'd rather build against older version of the OS so at least *our* (free - both as in beer and speech) software remains updated and improved.

Yes, I get this is all very "think of the children" - but in this case, it literally is "for the children", many of whom are in educational institutions for whom "upgrade" is not an option. Leaving an old (and, yes, we acknowledge, completely unsupported) image hanging around doesn't cost anything and may actually have significant positive impact in the realms of education.

Does this make sense?

**Comment by jakirkham** [comment]
Saw this recently. Thanks for having them route to XCode 6.4.

> New jobs will route to our Xcode 6.4 infrastructure.

**Comment by jakirkham** [comment]
@ntoll, the XCode 6.4 image still has the 10.9 SDK in it. So even though it is running 10.10, you can build using that SDK and test with it.

**Comment by jakirkham** [comment]
Closing this out as the switch has already occurred.
