### ISSUE TITLE
"False positive build": Build is green even though it should have failed

### ISSUE THREAD

**Issue by larsrh** [travis-ci/travis-ci#6768]
[This build](https://travis-ci.org/lihaoyi/fastparse/jobs/169613880) succeeded, even though it shouldn't have, because
- SBT failed to update
- Nothing has been executed

I'm not sure if the second is caused by the first or if it is an issue on its own right. Of course, the first might be caused by the global DNS outage, but nonetheless, I think it should fail the build.

Here's a screenshot of the log:
![screenshot_20161021_230155](https://cloud.githubusercontent.com/assets/923079/19611523/5fe080aa-97e2-11e6-98ee-5f6aa80ddfa0.png)

For comparison, a [subsequent build](https://travis-ci.org/lihaoyi/fastparse/jobs/169615099) actually executes something:

![screenshot_20161021_230256](https://cloud.githubusercontent.com/assets/923079/19611561/85d9fc5a-97e2-11e6-97f7-422e37ab9e60.png)

In case the code which updates SBT is public, I'd be happy to take a look.

**Comment by BanzaiMan** [comment]
Sorry for the delay. Could you tell us what `perftestsJVM/test-only -- perftests.string` is supposed to do? In https://travis-ci.org/lihaoyi/fastparse/jobs/169613880, the exit status is determined by this command. Does it depend on `sbt` actually doing something?

**Comment by larsrh** [comment]
The full invocation is:

    sbt ++$TRAVIS_SCALA_VERSION "; perftestsJVM/compile; perftestsJVM/test-only -- perftests.string"

It's supposed to compile & run a bunch of benchmarks. The problem is that SBT didn't actually get executed in the first place. (Otherwise, it would've printed some log output.)

**Comment by BanzaiMan** [comment]
Thanks for the explanation.

I think the issue was that `sbt` was executable but empty because the download failed. Such a file, when executed, "returns" status 0, so the build continued.

We should bail early if the download fails.

**Comment by larsrh** [comment]
Indeed, that would explain it. Thanks for the investigation.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/950
