### ISSUE TITLE
New octokit version broke GitHub Releases deployment

### ISSUE THREAD

**Issue by jpd236** [travis-ci/travis-ci#6772]
It looks like a new version of octokit, 4.4.0 was just pushed today which raised the minimum version of Ruby required from 1.9.2 to 2.0.0. This seems to have broken my project's GitHub Releases deployment:

Installing deploy dependencies
Fetching: sawyer-0.7.0.gem (100%)
Successfully installed sawyer-0.7.0
Fetching: octokit-4.4.0.gem (100%)
ERROR:  Error installing octokit:
	octokit requires Ruby version >= 2.0.0.

My project is a C++ build that doesn't use Ruby at all or configure it differently from the defaults.

Working build: https://travis-ci.org/jpd236/xword/jobs/168179892
Failing build: https://travis-ci.org/jpd236/xword/jobs/170010485

**Comment by BanzaiMan** [comment]
Could you try:

```yaml
deploy:
  provider: releases
  edge:
    branch: releases-fix
  ⋮ # rest
```

**Comment by jpd236** [comment]
Looks good: https://travis-ci.org/jpd236/xword/jobs/170136677

**Comment by jpoon** [comment]
Is a fix expected soon? I think we're hitting the same issue with our project: https://travis-ci.org/VSCodeVim/Vim/builds/170033456

**Comment by cotsog** [comment]
@jpoon: can you try to add [the snippet](https://github.com/travis-ci/travis-ci/issues/6772#issuecomment-255663033) mentionned by @BanzaiMan above? It should work in the meantime we release a newer version of the `dpl` gem. Thanks!

**Comment by meatballhat** [comment]
`dpl` `v1.8.23` has been released.  The `releases-fix` branch will be removed soon, so please update your configs accordingly.

**Comment by jpd236** [comment]
Verified a deploy with the above hacks all reverted. Thanks for the quick fix!
