### ISSUE TITLE
Users aren't constant in test environment

### ISSUE THREAD

**Issue by twolfson** [travis-ci/travis-ci#6775]
I'm using Travis CI for testing my server bootstrap script. As part of the bootstrap, we secure all user shells (e.g. set undesired ones to `/bin/false`) and as a result, we have tests to verify that no unexpected users have good shells (e.g. `postgres` shouldn't have a good shell)

In Travis CI, there are some extra users which is fine but they are inconsistent between builds (e.g. sometimes there is a `carmen` user, other times there is an `emma` user, more times there is a `konstantinhaase` user). Since the user lists are inconsistent, I can't predict all the users upfront and will have to update the test every time a new one pops up.

I was wondering if it's possible to either expose all possible users (I'm guessing they are for the Travis CI team to debug) or restrict them to a common account.

For those curious, here's the relevant code in my repo and tests where new users have popped up:

https://github.com/twolfson/twolfson.com-scripts/blob/2.7.0/src/cookbooks/common/recipes/default.rb#L107-L118

https://github.com/twolfson/twolfson.com-scripts/blob/2.7.0/test/security.rb#L50-L93

https://travis-ci.org/twolfson/twolfson.com-scripts/jobs/170069010#L1058

https://travis-ci.org/twolfson/twolfson.com-scripts/jobs/170039969#L1075

https://travis-ci.org/twolfson/twolfson.com-scripts/jobs/170039391#L1074

**Comment by BanzaiMan** [comment]
Sorry, but we don't guarantee anything about users, including the value of `$USER`. This is documented in https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables

**Comment by twolfson** [comment]
Ah damn, alright. Would it be possible to get a list of all possible Travis CI users then (e.g. `emma`, `carmen`, etc)? That way I could build my own whitelist =/
