### ISSUE TITLE
[community:r] Update to R-devel for bioc-devel

### ISSUE THREAD

**Issue by PeteHaitch** [travis-ci/travis-ci#6777]
@craigcitro, @hadley and @jimhester

bioc-devel has moved to R-devel with the latest release (per https://www.bioconductor.org/developers/how-to/useDevel/) Could this please be updated in Travis R builds. I think it just requires changes to https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb#L521-L524 - happy to write PR if that's the case

**Comment by jimhester** [comment]
Sending a PR would be great, the more people who know how to change this type of thing the better IMHO.

That is the correct location, you will also have to make changes to the corresponding test spec, https://github.com/travis-ci/travis-build/blob/master/spec/build/script/r_spec.rb#L12-L13. You can verify everything is correct locally with `bundle exec rspec`, or just send the PR and the travis build can check it.

Mention me in the PR and I can give it a quick review as well.

**Comment by LiNk-NY** [comment]
Hi Peter, @PeteHaitch 
This should be closed :)

Regards,
Marcel
