### ISSUE TITLE
Travis is not using biocLite for Bioconductor packages

### ISSUE THREAD

**Issue by llrs** [travis-ci/travis-ci#6780]
The recommended way of installing a package of the Bioconductor repository is with [biocLite](https://www.bioconductor.org/install/#why-biocLite).
I was surprised to find that in one of my [builds](https://travis-ci.org/llrs/DOSE/jobs/170086973#L1501):

``` sh
Rscript -e 'install.packages(c("DO.db", "org.Hs.eg.db", "fgsea", "GO.db", "GOSemSim"));if (!all(c("DO.db", "org.Hs.eg.db", "fgsea", "GO.db", "GOSemSim") %in% installed.packages())) { q(status = 1, save = "no")}'
```

Which doesn't use the biocLite, shouldn't that be?

``` sh
Rscript -e 'biocLite(c("DO.db", "org.Hs.eg.db", "fgsea", "GO.db", "GOSemSim"));if (!all(c("DO.db", "org.Hs.eg.db", "fgsea", "GO.db", "GOSemSim") %in% installed.packages())) { q(status = 1, save = "no")}'
```

I found several references to biocLite on the [travis-build](https://github.com/travis-ci/travis-build/blob/master/spec/build/script/r_spec.rb) repository and it seems that it can be used to install packages.
Following the docs for [R projects](https://docs.travis-ci.com/user/languages/r/): @craigcitro, @hadley, @jimhester.

**Comment by craigcitro** [comment]
Actually, if you look up near line 401, you can see that bioc is already set up.

Is something not working?

**Comment by jimhester** [comment]
This morning https://github.com/travis-ci/travis-build/pull/868 was merged and pushed to production, which updates the associated R version for bioc-devel to R-devel for this release cycle.

travis uses the [BiocInstaller](https://bioconductor.org/packages/release/bioc/html/BiocInstaller.html) package to set the repos option appropriately for Bioconductor packages, which is what biocLite does for you, so there is no need to use `biocLite()` directly. (source: I was on the Bioconductor core team prior to joining RStudio).

**Comment by llrs** [comment]
Ok, so if I set this option `options(repos = BiocInstaller::biocinstallRepos())` install.packages will use the correct version of Bioconductor? Then this issue should be closed

**Comment by jimhester** [comment]
You don't have to do anything, it was using the incorrect version due to a bug which is now fixed.

**Comment by wlandau** [comment]
My own Travis builds are failing due to a dependency on `graph`, which is on Bioconductor but not CRAN. Example: https://travis-ci.org/ropensci/drake/builds/396193476#L1037

**Comment by jimhester** [comment]
@wlandau You need to set `use_bioc: true` unless your package has a `BiocViews` field.
