### ISSUE TITLE
Support "rolling builds"

### ISSUE THREAD

**Issue by ntwb** [travis-ci/travis-ci#6782]
AppVeyor include a feature called "Rolling Builds":
> https://www.appveyor.com/docs/build-configuration/#rolling-builds
> “Rolling builds” are great for very active OSS projects with lengthy queue. Whenever you do a new commit to the same branch OR pull request all current queued/running builds for that branch or PR are cancelled and the new one is queued. Other words, rolling builds make sure that only the most recent commit is built.
>
> For example, you do commit A to master branch - it’s being queued and then run. Then you do B commit to master branch while A is running - build of A will be cancelled immediately and B is queued. If you do another C commit while B is queued it will be cancelled and C queued.

It would be great if Travis CI also offered something similar and easily configurable in `.travis.yml`

**Comment by johnbillion** [comment]
For background, [the WordPress project](https://travis-ci.org/aaronjorbin/develop.wordpress/builds) experiences backlogs of builds during periods of frequent pushes (via commits to its svn repo), and a rolling build would be ideal to mitigate this.

**Comment by jakirkham** [comment]
Agreed. This would be fantastic. Though seems like a dup of issue ( https://github.com/travis-ci/travis-ci/issues/5160 ). Maybe we should close and consolidate discussion there?

**Comment by ntwb** [comment]
@jakirkham thanks, I didn't come  across this is my original search, agreed, closing in favour of #5160
