### ISSUE TITLE
Unable to write file during JUnit Tests

### ISSUE THREAD

**Issue by evilmtv** [travis-ci/travis-ci#6783]
Greetings,
I'm facing an issue where a command `backup data/empty.xml` entered into my program locally would successfully create a new savefile at `data/empty.xml` and write to it but fails to do so in Travis.
To clarify, the JUnit test passes on Eclipse IDE but not when i push a commit and Travis attempts it.
I tried enabling sudo via .travis.yml but it doesn't help the situation.
Any help or advice would be appreciated!

**Comment by BanzaiMan** [comment]
Does the `data` directory exist and writable by the user?

**Comment by evilmtv** [comment]
thank you for the reply. the 'data' directory does not exist.
I tested creating in an existing directory, i.e. root folder, too and it still fails.
it is writable locally.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?
