### ISSUE TITLE
[BUG][RAILS] [RUBY1.9.3p551] I have to run gem update bundler before_install

### ISSUE THREAD

**Issue by fnicola** [travis-ci/travis-ci#6785]
I get this error while running bundle install
NoMethodError: undefined method `spec' for nil:NilClass

The problem with this is that seems to don't cache the bundle install then..

**Comment by fnicola** [comment]
its actually this: to this https://github.com/travis-ci/travis-ci/issues/5239

**Comment by BanzaiMan** [comment]
Closing as a duplicate.
