### ISSUE TITLE
Travis suddenly unable to install Node Sass

### ISSUE THREAD

**Issue by me4502** [travis-ci/travis-ci#6787]
Over the past day, Travis has been failing due to being unable to install Node Sass.

https://travis-ci.org/KnightHawk3/packr/jobs/170936818

This works fine locally, and no changes were made to it when it started failing. After looking it up, it appears to be an issue with the node environment on the machine.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/KnightHawk3/packr/jobs/170936818#L527 Try disabling (or deleting) cache and try again.

Probably related to http://stackoverflow.com/questions/37324519/node-sass-does-not-yet-support-your-current-environment-linux-64-bit-with-false

**Comment by me4502** [comment]
Yeah, that fixed it, thanks.
