### ISSUE TITLE
Multiple Builds on Push

### ISSUE THREAD

**Issue by EvanOman** [travis-ci/travis-ci#6790]
I have a LaTeX Resume hosted [here](http://www.github.com/EvanOman/Resume) with Travis CI enabled in order to generate a new PDF on every push. You can find the Travis build page [here](https://travis-ci.org/EvanOman/Resume).

I have Travis set to build on push, however every push triggers two builds: one for the push and one for a tag -- even if there is no tag. You can see an example if this behavior below:

![image](https://cloud.githubusercontent.com/assets/1807879/19784112/1fd7adae-9c5a-11e6-873c-d6f181152262.png)

I tried setting `deploy.on.tags` to false but this didn't change anything.

How can I set Travis to only build once for each push?

Here is my `.travis.yml`:

```{yml}
before_install:
- sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng
script:
- mkdir _build
- pdflatex -output-directory _build EvanOman.tex
deploy:
  provider: releases
  api_key:
    secure: <HASHED KEY>
  file:
  - _build/EvanOman.pdf
  skip_cleanup: true
  detect_encoding: true
  on:
    tags: false
after_success:
  "curl --ftp-create-dirs -T _build/EvanOman.pdf -u $FTP_U:$FTP_P ftp://ftp.evanoman.com/public_html/EvanOman.pdf"
```

**Comment by BanzaiMan** [comment]
Something in your workflow is creating and pushing these `untagged-*` tags. I can't tell what that is, but these tags definitely exist.

![evanoman_resume__my_latex_resume](https://cloud.githubusercontent.com/assets/25666/19794735/aa497d1a-9ccc-11e6-9e6f-afe1d3205c6a.png)

`deploy.on.tags` only affects there or not the deployment happens after a successful build, not whether the build happens at all. For the latter, you need safelist or blocklist. https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches

If these tags are legitimately a part of your workflow, please refer to the document above.

**Comment by EvanOman** [comment]
I'll look into it, thanks!
