### ISSUE TITLE
Travis job doesn't finish, when xvfb is used

### ISSUE THREAD

**Issue by donaldpipowitch** [travis-ci/travis-ci#6793]
For a selenium test I recently added xvfb support to my travis config. Now the job hangs for 10 minutes after my scripts run and the job gets killend.

The job worked correctly without the selenium test and without xvfb.
The scripts is correctly finished on my mac with the selenium test.

Example: https://travis-ci.org/Mercateo/ws/builds/171336288

**Comment by BanzaiMan** [comment]
Is it possible that your test is waiting for some user input? I doubt that your Mac is running xvfb, so your local run may not be an accurate reflection of the issues involved.

Also, try running the Docker image locally: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

**Comment by donaldpipowitch** [comment]
You're right. Thank you for the link. It helped me debugging.
