### ISSUE TITLE
Can't run perl scripts, doesn't even get to stage

### ISSUE THREAD

**Issue by JoeBanks13** [travis-ci/travis-ci#6794]
I'm trying to run a perl script in travis and I commit and it starts the build and it fails on this command:

`eval cpanm --quiet --installdeps --notest .`

Is this something I'm doing wrong?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
Closing this. If you have a build log to share, do let us know.
