### ISSUE TITLE
[ci-skip] never works for me

### ISSUE THREAD

**Issue by jedwards1211** [travis-ci/travis-ci#6795]
As you can see below, Travis CI kicked off a build for a `[ci-skip]` commit (which I then canceled).
Am I doing something wrong?  The docs say that adding `[ci-skip]` to the commit message is all it takes to get Travis CI to ignore the commit.

![screen shot 2016-10-28 at 2 55 34 pm](https://cloud.githubusercontent.com/assets/1448194/19820414/e1abb848-9d1e-11e6-8f01-94fdc2eae075.png)

**Comment by BanzaiMan** [comment]
Hello. Please drop the hyphen. It should be `[ci skip]`.

**Comment by jedwards1211** [comment]
Man...the things my brain overlooks... :smile:
Thanks!
