### ISSUE TITLE
Font cache timing out

### ISSUE THREAD

**Issue by josephcslater** [travis-ci/travis-ci#6799]
It doesn't seem to matter what one does, [matplotlib plots time out building the font cache](https://travis-ci.org/vibrationtoolbox/pvtoolbox/builds/171812282). I've tried what I can find (you can see the log). I'm clearly just flailing. Is there a solution?

`/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')`

**Comment by BanzaiMan** [comment]
How long does this take on your machine?

**Comment by josephcslater** [comment]
> On Nov 1, 2016, at 9:56 AM, Hiro Asari <notifications@github.com> wrote:
> 
> How long does this take on your machine?
> 
> 

Seconds. 

This issue of building the cache doesn't arise. 

************************************************************
[jslater@Norma pvtoolbox]$ nosetests --with-doctest --doctest-tests --doctest-extension= 'vtoolbox'
../opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/linalg/basic.py:884: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)
...................
----------------------------------------------------------------------
Ran 21 tests in 2.556s

OK
************************************************************


Thanks,
Joe

**Comment by BanzaiMan** [comment]
I don't think this is an issue with font cache, but with xvfb, which is also reported in #6793. If you can remove xvfb from your equation, please try it, so that we can focus on the issue at hand. Thanks.

**Comment by josephcslater** [comment]
I just resubmitted. 

Please excuse that auto correct changed the spelling of your name in my commit comments (made to reference this email). 

It failed, but per the status to travis-ci:
Update - Switching to another database, logs are not being processing right now. 
Nov 1, 23:54 UTC

**Comment by BanzaiMan** [comment]
Thanks for testing. https://travis-ci.org/vibrationtoolbox/pvtoolbox/builds/172470363 shows that the issue does not manifest in the absence of xvfb, so I think we can close this as a duplicate, as I mentioned earlier.
