### ISSUE TITLE
Enable repo where I am a collaborator in personal github accounts

### ISSUE THREAD

**Issue by epoberezkin** [travis-ci/travis-ci#6800]
I can enable repos in orgs where I am admin.
But I cannot enable repos in personal accounts where I am collaborator.
In coveralls.io I can enable such repos, it would be good to be able in travis too.

**Comment by BanzaiMan** [comment]
With which org/repo are you having troubles?

**Comment by epoberezkin** [comment]
I don't think it is a bug, I think it is a missing feature. I need to enable "olado/dot" github repo where I am a collaborator. And olado is not a github organisation, it is a github user.

**Comment by BanzaiMan** [comment]
Please ask the GitHub user @olado to enable it then. The repo belongs to them, not collaborators.

**Comment by epoberezkin** [comment]
It's done already.

Still I am not sure why collaborators with write access should not be able to do it. On coveralls.io I can enable repo as long as I have write access, both in organisations and in other people accounts. As one may argue that organisation repos also don't belong to me and yet I can enable them.

So this issue is a feature/improvement suggestion, not a bug.

**Comment by joshk** [comment]
Thanks for the feedback @epoberezkin 

This is a limitation imposed on GitHubs side. As you are a collaborator on a personal repo, you don't have `admin` rights, which we need to enable the hook.

With the advent of GitHub Integrations, we are unlikely to revisit this topic for the time being.

Thank you for taking the time to explain the situation.
