### ISSUE TITLE
Automatically accept the license Agreement for Android SDK 25

### ISSUE THREAD

**Issue by apacha** [travis-ci/travis-ci#6801]
Travis should automatically accept the license agreement for the newest android SDK (25) the same as it accepts the licence agreements for all previous versions.

**Comment by apacha** [comment]
See this open-source repository for details: https://travis-ci.org/apacha/sensor-fusion-demo/builds/171981862

**Comment by houxg** [comment]
Because of travis's sdk version is out of date, you need to upgrade sdk first by adding `tools`.
For example:
```
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
```

**Comment by apacha** [comment]
That did the trick. Thanks!

**Comment by GuillemRoca** [comment]
See this issue also for running on android-25: (https://github.com/travis-ci/docs-travis-ci-com/issues/779)
