### ISSUE TITLE
R: _R_CHECK_CRAN_INCOMING_=true ignored

### ISSUE THREAD

**Issue by HenrikBengtsson** [travis-ci/travis-ci#6802]
R-Travis sets `_R_CHECK_CRAN_INCOMING_=false` by default, cf. https://docs.travis-ci.com/user/languages/r/.  I don't seem to be able to override this.  My [.travis.yml](https://github.com/HenrikBengtsson/R.oo/blob/8a924d13a47824375d520a7ad60e04431159afcd/.travis.yml) uses:
```
    - os: linux
      r: devel
      env: _R_CHECK_CRAN_INCOMING_=true
```
and the [Travis log](https://travis-ci.org/HenrikBengtsson/R.oo/jobs/172021465#L421) shows:
```
Setting environment variables from .travis.yml
$ export _R_CHECK_CRAN_INCOMING_=true
```
However, the `R CMD check --as-cran --no-manual` call still [does not run](https://travis-ci.org/HenrikBengtsson/R.oo/jobs/172021465#L1083) the incoming CRAN checks:
```
Checking package
Checking with: R CMD check R.oo_1.20.0-9000.tar.gz --as-cran --no-manual
$ R CMD check "${PKG_TARBALL}" --as-cran --no-manual; CHECK_RET=$?
* using log directory ‘/home/travis/build/HenrikBengtsson/R.oo/R.oo.Rcheck’
* using R Under development (unstable) (2016-10-30 r71606)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘R.oo/DESCRIPTION’ ... OK
* this is package ‘R.oo’ version ‘1.20.0-9000’
* checking package namespace information ... OK
* checking package dependencies ... OK
[...]
```

What I expect to appear is the additional 'CRAN incoming feasibility' check:
```r
* this is package 'R.oo' version '1.20.0-9000'
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Henrik Bengtsson <henrikb@braju.com>'

Version contains large components (1.20.0-9000)

Found the following (possibly) invalid URLs:
  URL: http://www.r-project.org/conferences/DSC-2003/Proceedings/Bengtsson.pdf
    From: inst/CITATION
    Status: 200
    Message: OK
    R-project URL not in canonical form
  Canonical www.R-project.org URLs use https.

The Date field is over a month old.
* checking package namespace information ... OK
```

/cc @craigcitro, @hadley, @jimhester

**Comment by jimhester** [comment]
This is set at https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb#L52

You should be able to override it in a `before_install:` block

```yaml
before_install:
  export _R_CHECK_CRAN_INCOMING_=true
```

@BanzaiMan I am not sure if there is anything we can change in the build script to allow users to override exported variables, or maybe that export statement could check if the variable is already set and use the current value if so.

**Comment by HenrikBengtsson** [comment]
Thanks, using:
```
before_install:
  export _R_CHECK_CRAN_INCOMING_=true
```
worked.

The section on 'Environment Variables' in https://docs.travis-ci.com/user/languages/r/ uses "sets ... defaults" which kind of suggests they can be overridden by the user;

> R-Travis sets the following additional environment variables from the Travis defaults.
> * TRAVIS_R_VERSION=3.2.4 Set to version chosen by r:.
> * R_LIBS_USER=~/R/Library
> * R_LIBS_SITE=/usr/local/lib/R/site-library:/usr/lib/R/site-library
> * _R_CHECK_CRAN_INCOMING_=false
> * NOT_CRAN=true
> * R_PROFILE=~/.Rprofile.site

Being able to use `env` for this would be more natural, but on the other hand, I'm not sure if it makes sense to be able to override them all.

**Comment by BanzaiMan** [comment]
Bash allows for parameter substitution `${VAL1:=$VAL2}`. See http://www.tldp.org/LDP/abs/html/parameter-substitution.html.
