### ISSUE TITLE
The version of this operating system is not supported by .NET Core.

### ISSUE THREAD

**Issue by vicmosin** [travis-ci/travis-ci#6805]
I am trying to CI some [test ASP.NET Core project](https://travis-ci.org/vicmosin/badaboom), but CI fails with that error all the time..
Tried both `1.0.0-preview2-003121` and `1.0.0-preview2-003131`.
Any ideas?

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by Joshua-Anderson** [comment]
@vicmosin The containerized build environment is based on ubuntu precise, which is unsupported by .NET Core, which requires trusty or higher.

You can use .NET Core on the Trusty or OS X VM environment.

**Comment by 304NotModified** [comment]
We have the same problem. I don't understand how to change to config to fix this. It seems that https://docs.travis-ci.com/user/languages/csharp is out to date?

**Comment by 304NotModified** [comment]
ah it should be 

```
 "dist": "trusty",
  "sudo": "required",
```

? Please update the docs
