### ISSUE TITLE
R: Mac builds failing

### ISSUE THREAD

**Issue by cfhammill** [travis-ci/travis-ci#6807]
My stable mac builds are now dying with:

The command "sudo installer -pkg "/tmp/R.pkg" -target /" failed and exited with 1 during 

Could have something to do with the new R release @jimhester @craigcitro

**Comment by jimhester** [comment]
Please link to an example using native R travis build that is failing.

**Comment by cfhammill** [comment]
https://travis-ci.org/cfhammill/RMINC/jobs/172123763

**Comment by jimhester** [comment]
https://cloud.r-project.org/bin/macosx/R-latest.pkg is not found, there must have been a change with the new release and this link is no longer valid. :-/

Probably we need to post to https://stat.ethz.ch/mailman/listinfo/r-sig-mac about this, or hard code the version directly.

**Comment by gvegayon** [comment]
It seems that the link has been fixed (e.g. [netdiffuseR's OSX build](https://travis-ci.org/USCCANA/netdiffuseR/jobs/172716156)).

**Comment by jeffreyhanson** [comment]
I can also confirm that Mac OSX CI is back up and running ([log here](https://travis-ci.org/jeffreyhanson/raptr/jobs/172570648))

**Comment by cfhammill** [comment]
Yup, back for me too, closing!
