### ISSUE TITLE
Is there an issue with Travis CI (.org) ??

### ISSUE THREAD

**Issue by arcanedev-maroc** [travis-ci/travis-ci#6812]
The builds are failing without displaying the log. Any ideas ?

Reference: https://travis-ci.org/ARCANEDEV/LaravelExcel/jobs/172410068

Best regards,

**Comment by BanzaiMan** [comment]
Yes. Please click on the red beacon on the upper left corner, which will lead you to https://www.traviscistatus.com/incidents/lp492hx0z1my

Duplicate of #6810 and #6811.
