### ISSUE TITLE
Unpredictable build failures with open/closed localhost ports

### ISSUE THREAD

**Issue by mbdevpl** [travis-ci/travis-ci#6814]
I've searched for a while for similar open issues, found none. If I missed something, then sorry for duplication.

My issue is that builds on Travis in one of my projects are unpredictable. When building the exact same codebase, at one time build succeeds, at other time it fails.

Specifically, buildscript for one of my projects includes a setup of a temporary IMAP/POP server `dovecot` running on localhost. Server setup is done as a first step, and it doesn't fail. In the log there's `dovecot start/running, process 5975` and similar lines but then the output of `netstat -tuln` varies from build to build. Once it's:
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN     
tcp6       0      0 :::995                  :::*                    LISTEN     
tcp6       0      0 :::110                  :::*                    LISTEN     
tcp6       0      0 :::143                  :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::993                  :::*                    LISTEN     
udp        0      0 0.0.0.0:68              0.0.0.0:*                          
udp        0      0 10.128.0.133:123        0.0.0.0:*                          
udp        0      0 127.0.0.1:123           0.0.0.0:*                          
udp        0      0 0.0.0.0:123             0.0.0.0:*                          
udp6       0      0 :::123                  :::*                               
```
e.g. see: https://travis-ci.org/mbdevpl/maildaemon/builds/172550201#L447

And on different occasion it's:
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
udp        0      0 0.0.0.0:68              0.0.0.0:*                          
udp        0      0 10.128.15.198:123       0.0.0.0:*                          
udp        0      0 127.0.0.1:123           0.0.0.0:*                          
udp        0      0 0.0.0.0:123             0.0.0.0:*                          
udp6       0      0 :::123                  :::*                               
```
e.g. see: https://travis-ci.org/mbdevpl/maildaemon/builds/172555578#L470

Both above examples are logs of builds pointing to the same commit, so the application code is exactly the same. The only difference is time of build. This happens consistently for a few days now. If you'd like to see the pased/failed ratio: https://travis-ci.org/mbdevpl/maildaemon/builds

Is there a way to diagnose this? Is there some good reason why sometimes the ports are open and sometimes not, with the exact same codebase?

That above pass/failure occured for current master and devel for this GitHub repo: https://travis-ci.org/mbdevpl/maildaemon

**Comment by mbdevpl** [comment]
I've also opened an issue in the `dovecot` script setup repo: https://github.com/tedious/DovecotTesting/issues/5 but I'm doubtful if the issue is on that side.

**Comment by BanzaiMan** [comment]
Some services may take longer to start listening on their ports. On the passing build, I see that your setup script took 10 seconds longer to complete. Maybe this is how your tests need to behave.

**Comment by mbdevpl** [comment]
Thank you for your words of wisdom! That was a very very correct observation.

Probability of success of build seems to greatly depend on that delay. I will patch the server setup scripts to make sure that ports are open before moving on to testing my app.

Although your suggestion seems to be obviously right, I will monitor the situation for a day or two before closing this issue.

In any case, thanks a lot for your help, and sorry for cluttering your tracker with a silly user-caused issue.

**Comment by BanzaiMan** [comment]
Thanks for the confirmation.
