### ISSUE TITLE
[Smalltalk] VM + ulimit problem

### ISSUE THREAD

**Issue by fniephaus** [travis-ci/travis-ci#6815]
Dear Travis CI Team,

I'm one of the maintainers of the framework that powers the Travis CI support for Smalltalk.
We'd like to upgrade our VMs that we use for testing, but for that we need to raise the maximum real-time scheduling priority via `ulimit -r 2` which requires sudo permissions. [One way](https://github.com/OpenSmalltalk/opensmalltalk-vm/releases#linux) is to create a file in `/etc/security/limits.d/` but that requires to logout and log back in which is no an option I believe.
The other way that allows us to run a new Smalltalk VM successfully on sudo-enabled environments is this:

`sudo bash -c "ulimit -r 2 && su $USER ./run.sh"`

We want to be able to achieve the same on the container-based infrastructure, so we need to update the [smalltalk.rb](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/smalltalk.rb).

The problem is that we can't call `ulimit -r 2` during the setup stage, because it only works when running as sudo and you can't just do `sudo ulimit...`. Additionally, IIRC it's not possible to call sudo during the [script stage](https://github.com/travis-ci/travis-build/blob/1b0be566a7eda22976a5b186977d6a50b7e5698d/lib/travis/build/script/smalltalk.rb#L72) anymore, so we also can't do:

`sh.cmd "sudo bash -c \"ulimit -r 2 && su $USER $SMALLTALK_CI_HOME/run.sh\""`

Do you have any idea how we could solve this?

Best,
Fabio

/cc @BanzaiMan

**Comment by BanzaiMan** [comment]
There is the `configure` stage, which runs before `sudo` is disabled. Does running `ulimit` in this stage do the trick?

**Comment by fniephaus** [comment]
I assume all stages run in the same shell, and that shell does not have `sudo` permissions, right?
As mentioned, it's not possible to raise the limit by calling `sudo ulimit...`. I believe calling `ulimit` directly would only work if `script` runs in a sub-shell spawned by `configure`. But I don't think that's the case...

**Comment by BanzaiMan** [comment]
Ah, I see. The build script will remain in the same shell. If a new login is necessary, it wouldn't work.

Would `su $USER $SMALLTALK_CI_HOME/run.sh` *_after_* setting the limit in `configure` work? So that users can opt-in to the feature?

**Comment by fniephaus** [comment]
I guess we could run `sudo bash -c "ulimit -r 2 && su $USER ./run.sh"` in `configure`, but then we'd also run the tests in `configure` and not in `script` anymore. Not sure if this is a good idea.

**Comment by BanzaiMan** [comment]
So,

```sh
sudo ulimit -r 2
⋮
su $USER ./run.sh
```

in the same shell would not work?

**Comment by fniephaus** [comment]
Ok, I have an idea. We can create a file in `/etc/security/limits.d/` and then spawn a subshell via `sudo su $USER`, this will login the user in another time with `ulimit -r` set correctly and then the build script will continue.

I'll try to get this working on a sudo enabled machine and then I'll send you a PR :)

**Comment by guillep** [comment]
Sorry to comment in the already closed issue. @fniephaus, was that at the end a solution for you?

**Comment by fniephaus** [comment]
@guillep as it turned out, we currently cannot run heartbeat threaded vms on Travis' container-based infrastructure. We can't change the rtprio at runtime in Docker, the only way would be to update Travis' internal Docker configuration, but that's currently not an option.
However, you can run ht vms with `sudo: required` on Travis which is what we do in OpenSmalltalk VM. In addition, we do [this](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/31450f0cb4cf79471020fbfb000388547a5ee769/.travis_test.sh#L8-L13) in order to raise the rtprio limit temporarily. Lastly, in case you are using [smalltalkCI](https://github.com/hpi-swa/smalltalkCI) it will automatically raise the rtprio limit if sudo is enabled and when a custom vm is provided using the `--vm` option.
As you can see, this is all non-trivial and it would be great to just have one vm which falls back to the itimer if ht is not supported by the system.
Let me know if you need any additional help.

**Comment by cdlm** [comment]
> Lastly, in case you are using smalltalkCI it will automatically raise the rtprio limit if sudo is enabled and when a custom vm is provided using the --vm option.

But it doesn't seem to do it with `sudo: required` but the default VM (Pharo 7), which needs it… why?

**Comment by fniephaus** [comment]
@cdlm Could you please open an issue at https://github.com/hpi-swa/smalltalkCI/issues/new with a pointer to your builds? Thanks! FYI: [here is the code](https://github.com/hpi-swa/smalltalkCI/blob/81e16cae0d8f10f45c3eef5f5726148ad593d16a/run.sh#L352) that should raise the rtprio.
