### ISSUE TITLE
please do something with Let's Encrypt CA

### ISSUE THREAD

**Issue by chipitsine** [travis-ci/travis-ci#6817]
https://travis-ci.org/chipitsine/openvpn/jobs/172945506#L338

I've no idea why do travis-ci images do not trust https://www.openssl.org

**Comment by BanzaiMan** [comment]
Where are these warnings coming from? https://travis-ci.org/chipitsine/openvpn/jobs/172945506#L333-L334 We do not provide `/home/travis/opt`, so I tend to think this is something you are doing.

Getting an archive form https://www.openssl.org works just fine (https://travis-ci.org/BanzaiMan/travis_production_test/builds/172950046#L146), so I am afraid you'll have to dig yourself out of this one.

Try debugging with the Docker image: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

**Comment by chipitsine** [comment]
please, try with "dist: trusty", as I reported for that dist.

**Comment by chipitsine** [comment]
if "dist: trusty" is something legitimate, so I can use it, right ?
it does not make sense why you are trying different image

**Comment by BanzaiMan** [comment]
`sudo: false` + `dist: trusty` is yet-to-be announced feature (yes, you can use it!).

But the issue remains. https://travis-ci.org/BanzaiMan/travis_production_test/builds/172970221#L144

**Comment by chipitsine** [comment]
well, it seems due to "xenial" repo.
I tried on clean "trusty", it works well

https://travis-ci.org/chipitsine/travis-openssl-test

so, nevermind, I'll figure out myself
