### ISSUE TITLE
REQUEST: Option to use a newer version of Ubuntu?

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#6818]
I am aware that the current version is a long term support version but even so, just in case of bigger changes in Ubuntu, I wish to test on newer versions.

**Comment by BanzaiMan** [comment]
We will be working on getting the images updated over time, though they may arrive a little later than you'd like.

In the meantime, you can use newer Docker images to accomplish what you are after.

**Comment by BanzaiMan** [comment]
Closing as a duplicate of https://github.com/travis-ci/travis-ci/issues/5821.
