### ISSUE TITLE
New account cannot see repositories

### ISSUE THREAD

**Issue by cauri** [travis-ci/travis-ci#6819]
I created a new account, connected my GitHub and cannot see any respositories. I've re-synced and it still says no repositories found. My repos are private.

**Comment by BanzaiMan** [comment]
For historical reasons, when you are connected to https://travis-ci.com, you cannot see public repositories, and when you are connected to https://travis-ci.org, you cannot see private repositories.

If these do not apply to you, do let us know what repository you are unable to see. If you'd rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thanks.

**Comment by cauri** [comment]
Got it. Thanks.

**Comment by BanzaiMan** [comment]
Can we close this now?

**Comment by BanzaiMan** [comment]
Closing optimistically. If there is more to be done, do let us know.
