### ISSUE TITLE
Travis doesn't work with R 3.3.2

### ISSUE THREAD

**Issue by fsavje** [travis-ci/travis-ci#6820]
Testing when explicitly using R 3.3.2 doesn't work with Travis.

The following config file:
```yml
# File: .travis.yml
sudo: false
language: r
cache: packages

r:
  - 3.3.2
```

produces the following output:

```
$ curl -Lo /tmp/R-3.3.2.xz https://s3.amazonaws.com/rstudio-travis/R-3.3.2.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   243    0   243    0     0   1410      0 --:--:-- --:--:-- --:--:--  1437

$ tar xJf /tmp/R-3.3.2.xz -C ~
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now

The command "tar xJf /tmp/R-3.3.2.xz -C ~" failed and exited with 2 during .

Your build has been stopped.
```

@craigcitro @hadley @jimhester

**Comment by BanzaiMan** [comment]
The `curl` download appears to have failed. (The file content—243 bytes—is much too short.) Does the issue persist if you restart the job?

**Comment by jimhester** [comment]
R 3.3.2 was just released https://stat.ethz.ch/pipermail/r-announce/2016/000608.html and we had not built a version of it for Travis, this is now done so retarting the build should work.

**Comment by fsavje** [comment]
It now works as expected. Thank you!
