### ISSUE TITLE
Job fails with "C compiler cannot create executables"

### ISSUE THREAD

**Issue by gioele** [travis-ci/travis-ci#6821]
The jobs https://travis-ci.org/fontforge/fontforge/jobs/173100909 and https://travis-ci.org/gioele/fontforge/jobs/173126022 fail during `./configure` because "C compiler cannot create executables".

These are the last lines from the log:

> checking for gcc... gcc-4.9
> checking whether the C compiler works... no
> configure: error: in '/home/travis/build/gioele/fontforge':
> configure: error: C compiler cannot create executables
> See 'config.log' for more details

Similar builds (with no changes to the Travis settings) have been working fine up to yesterday (see <https://travis-ci.org/gioele/fontforge/jobs/172779734>).

**Comment by BanzaiMan** [comment]
Have you looked at the config.log?

**Comment by BanzaiMan** [comment]
Looks like this is a direct result of #6822. I'm closing this. Let us know if you believe it should be separate.
