### ISSUE TITLE
Log output randomly suppresses command output

### ISSUE THREAD

**Issue by stewx** [travis-ci/travis-ci#6826]
It is hit-or-miss whether Travis displays the output of various build commands for me. 

The difference between the two revisions built here is trivial (nothing to do with the build process or anything executed by the build process)

Here, there is no log output shown for this `npm` command:
![screen shot 2016-11-04 at 9 35 25 am](https://cloud.githubusercontent.com/assets/6986171/20005613/100cb946-a272-11e6-99b8-6b2bbb11731d.png)

Here, on the other hand, it shows the full log output that I expect:
![screen shot 2016-11-04 at 9 35 08 am](https://cloud.githubusercontent.com/assets/6986171/20005614/100da3f6-a272-11e6-9548-d333a794e16b.png)

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by stewx** [comment]
@BanzaiMan It's on an enterprise Travis CI server, so I can't link to it, unfortunately. If you have any debugging suggestions, though, I'm all ears and I can post the output.

**Comment by BanzaiMan** [comment]
Ah, I see. Please get in touch with us with email.

I'm closing this now, since there is very little we can do here. We will follow up on with email.

**Comment by stewx** [comment]
Emailing enterprise@travis-ci.com

**Comment by BanzaiMan** [comment]
Thank you!
