### ISSUE TITLE
Can't encrypt value

### ISSUE THREAD

**Issue by marschall** [travis-ci/travis-ci#6830]
Apparently the easiest way to encrypt a value is to [install a gem](https://docs.travis-ci.com/user/encryption-keys/#Usage). That fails with

```
$gem install travis
ERROR:  Could not find a valid gem 'travis' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/latest_specs.4.8.gz)
```

so what are the other less easy ways to encrypt something?

**Comment by BanzaiMan** [comment]
The error indicates a problem between your machine and rubygems.org. What kind of machine are you using?

**Comment by marschall** [comment]
A Mac Book Pro with macOS X 10.12.1

**Comment by BanzaiMan** [comment]
Ah, I see that you are using SSLv3. I believe you need a version of TLS or another supported encryption method. (See https://github.com/rubygems/rubygems/issues/1050.) Not sure how to force TLS on your machine, but https://gist.github.com/luislavena/f064211759ee0f806c88#gistcomment-1913884 may prove helpful to you.

It is possible to use API to obtain the repository's public key (https://docs.travis-ci.com/api#repository-keys) and use that to encrypt values, but I don't think we have document to explain it.

**Comment by marschall** [comment]
How and why can I still be using SSLv3? TLS 1.0 was released in 1999, TLS 1.2 was released 2008. I'm not looking forward to setting up and maintaining a local Ruby development environment, which apparently was using SSLv3 until 2014, just to be able to use a SAAS securely .

Do you have at least a description on how to encrypt the values without the details like command line tool invocations? I fear simply "encrypt it" is missing a fey bits and pieces, like the algorithm for starters.

**Comment by harmittaa** [comment]
@marschall I had the same problem, see "INSTALLING USING UPDATE PACKAGES" http://guides.rubygems.org/ssl-certificate-update/

**Comment by marschall** [comment]
@harmittaa thanks for the link. Unfortunately I can't download the ruby gems update because I get an SSL certificate error because the CA certificate has been revoked.

**Comment by harmittaa** [comment]
@marschall in the guide I linked you'd manually download the update and then install it from the local directory. Not sure if this is the correct solution for your problem though.

**Comment by marschall** [comment]
@harmittaa I'm getting the SSL certificate error when manually downloading.
