### ISSUE TITLE
with --deployment argument fails bundle install

### ISSUE THREAD

**Issue by gamesover** [travis-ci/travis-ci#6833]
I am coding in Win 7, Ruby on Rails. My Gemfile is
```
source 'https://rubygems.org'

# ruby 2.3 has some bug to build gem
ruby '~>2.2.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0'

# Use Puma as the app server
gem 'puma', '~> 3.0'
gem 'ruby-saml', '~> 1.0.0'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
gem 'bcrypt'
# Use Capistrano for deployment
#gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  gem 'rspec-rails'
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
end

group :development do
end

group :test do
  gem 'factory_girl_rails'
end
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

When I use auto bundle install(which is default by travis-ci), it always fail
```
$ gem --version
2.4.8
10.22s$ bundle install --jobs=3 --retry=3 --deployment
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Installing rake 11.3.0
Installing concurrent-ruby 1.0.2
Installing i18n 0.7.0
Installing minitest 5.9.1
Installing builder 3.2.2
Installing thread_safe 0.3.5
Installing erubis 2.7.0
Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES
section: 'nokogiri'
The command "eval bundle install --jobs=3 --retry=3 --deployment" failed. Retrying, 2 of 3.
```
However, if I add `bundler_args: --without deployment`, the `bundle install` will success. I don't know why with `--deployment` always fail the bundle, any advice?

**Comment by BanzaiMan** [comment]
`Gemfile.lock` is corrupt, it says. Re-bundle, commit the change, and try again.

**Comment by gamesover** [comment]
I tried a couple of times to delete `Gemfile.lock` and rerun `bundle install`, no luck. My detailed project and file is `https://github.com/gamesover/free-sms/blob/try_fixed_gem_version_number/Gemfile` . Thanks for your reviewing.

**Comment by BanzaiMan** [comment]
Ah, I see. You are developing on a Windows machine, but the builds will run on Linux. If you don't have access to a Linux box, I think it is best to not check in `Gemfile.lock` to your Git repository.

**Comment by BanzaiMan** [comment]
`--deployment` is for locking down gems, which doesn't apply to your case, because the development and test environments differ.

**Comment by gamesover** [comment]
Well cool. I put `Gemfile.lock` into git ignore list, now my project passed travis-ci test. Thanks so much for your advice. I am quite novice in deployment:)

**Comment by BanzaiMan** [comment]
You bet. I'm closing this now.

**Comment by MoacirPetry** [comment]
Hey guys, I was struggling with this issue too.

The best practice to solve this was to execute the command `bundle lock --add-platform x86_64-linux`, because the travis works with linux machine.

😉  Happy code to you all
