### ISSUE TITLE
Build badge remains unknown even though it fails/is successful

### ISSUE THREAD

**Issue by kyc3** [travis-ci/travis-ci#6834]
Hi,

my build badge remains "unknown" even though it's failing/successful. Using the markdown in Github it works though.

Here is my porject: https://travis-ci.org/ProjectRide/ProjectRide_iOS

Best Regards

**Comment by BanzaiMan** [comment]
The build's default branch is `master`, which has no builds. Either switch your default branch to `develop` (and resync), or run a build on the `master` branch.

**Comment by BanzaiMan** [comment]
This was not explained in our docs. I've opened a PR to explain it. https://github.com/travis-ci/docs-travis-ci-com/pull/789

**Comment by kyc3** [comment]
Okay thanks for explaining. Clicking on the badge is giving me markdown the `develop` branch though. @BanzaiMan

**Comment by BanzaiMan** [comment]
@kyc3 I see that now. We will take a look.
