### ISSUE TITLE
NaN displayed in UI for duration of build command

### ISSUE THREAD

**Issue by stewx** [travis-ci/travis-ci#6835]
In my `before_install` script, one of the commands I run is `sudo apt-get update`. In this instance, the duration of the command is displayed as `NaNs`, as in, "NaN seconds".

![screen shot 2016-11-07 at 4 00 09 pm](https://cloud.githubusercontent.com/assets/6986171/20073626/54930b72-a503-11e6-873c-b221d20b25ef.png)

**Comment by BanzaiMan** [comment]
Is this an issue with your Enterprise installation?

**Comment by stewx** [comment]
Yes

**Comment by BanzaiMan** [comment]
Thanks for the confirmation. As before, please email our support at enterprise@travis-ci.com.

It is not very effective to troubleshoot this issue here.
