### ISSUE TITLE
Python 3.6 fails to install

### ISSUE THREAD

**Issue by wolfy1339** [travis-ci/travis-ci#6839]
It seems as though when it tries to install Python 3.6, it fails. witch errors out my build
Relevent peice of log:
> The command "sudo tar xjf python-3.6.tar.bz2 --directory /" failed and exited with 2 during .

I'm using the Precise containers (sudo: False)
Log: https://travis-ci.org/wolfy1339/Python-IRC-Bot/jobs/174211274

**Comment by BanzaiMan** [comment]
`3.6` is not yet released, and therefore not a recognized version string. Try `3.6-dev` (nightly development builds) or a previous beta version such as `3.6.0b3`.
