### ISSUE TITLE
jdk_switcher is missing on Android container Trusty image

### ISSUE THREAD

**Issue by vchimev** [travis-ci/travis-ci#6843]
```sh-session
$ jdk_switcher use oraclejdk8
/home/travis/build.sh: line 47: jdk_switcher: command not found
The command "jdk_switcher use oraclejdk8" failed and exited with 127 during .
Your build has been stopped.
```
https://travis-ci.org/NativeScript/NativeScript/builds/174521150
https://github.com/NativeScript/NativeScript/blob/master/.travis.yml

**Comment by photodude** [comment]
Looks like another beta Container-based Ubuntu Trusty issue

I'm not sure but I think the package you are looking for is oracle-java8-installer on Trusty

see the trusty package list
https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty

**Comment by vchimev** [comment]
Hey @BanzaiMan, @meatballhat, did this change get into production?

**Comment by mvdan** [comment]
Still the same errors as of April 2017.

**Comment by BanzaiMan** [comment]
This should no longer be an issue.
