### ISSUE TITLE
Trusty container beta missing some postgresql packages

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#6844]
The following packages are missing from the Trusty container public beta

- postgresql-9.5
  - 9.5 is available in sudo enabled trusty
- postgresql-9.6
  - 9.6 is a new package as of September 2016

**Comment by photodude** [comment]
[According to](https://github.com/travis-ci/travis-ci/issues/4264#issuecomment-263550556) @joepvd After the [image update scheduled at 2016-12-01](https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/) this will be fixed

reference related issue #4264

**Comment by photodude** [comment]
@meatballhat @BanzaiMan I believe this has been resolved. Can we close?

**Comment by BanzaiMan** [comment]
Sounds good. Thanks for the ping.
