### ISSUE TITLE
Error: cannot find -lcblas

### ISSUE THREAD

**Issue by HrWangChengdu** [travis-ci/travis-ci#6847]
I encountered "/usr/bin/ld: cannot find -lcblas" in linking process. However, "libatlas-dev" are actually included in my .travis.yml. It still cannot find libcblas.so...
Is there any solution?

Thanks very much

**Comment by HrWangChengdu** [comment]
I added "find /usr/lib -name "libcblas*"" in the install process and it printed nothing.

**Comment by BanzaiMan** [comment]
"libatlas-dev" includes libcblas*? http://packages.ubuntu.com/precise/all/libatlas-dev/filelist has no mention of such files. Could you double check the name of the package you need?

**Comment by HrWangChengdu** [comment]
@BanzaiMan Thank you. I actually need libcblas.so.3....

**Comment by HrWangChengdu** [comment]
I found the solution. libatlas-base-dev is the package that contains libclbas.so.
Thx for your help. Issue closed.
