### ISSUE TITLE
oracle-java-installer broken

### ISSUE THREAD

**Issue by akara** [travis-ci/travis-ci#6848]
Perhaps this is not your issue, but it does impact builds requiring Oracle JDK.

`.travis.yml` entry:

```yaml
addons:
  apt:
    packages:
      - oracle-java8-installer
```

Build errors out as of this morning:

```
Downloading Oracle Java 8...
--2016-11-10 16:12:24--  http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 104.96.220.152, 104.96.220.162
Connecting to download.oracle.com (download.oracle.com)|104.96.220.152|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz [following]
--2016-11-10 16:12:24--  https://edelivery.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 104.96.237.225, 2600:1408:10:185::2d3e, 2600:1408:10:184::2d3e
Connecting to edelivery.oracle.com (edelivery.oracle.com)|104.96.237.225|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.oracle.com/splash/edelivery/index.html [following]
--2016-11-10 16:12:24--  https://www.oracle.com/splash/edelivery/index.html
Resolving www.oracle.com (www.oracle.com)... 104.96.237.225, 2600:1408:10:184::2d3e, 2600:1408:10:185::2d3e
Connecting to www.oracle.com (www.oracle.com)|104.96.237.225|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2016-11-10 16:12:24 ERROR 503: Service Unavailable.
download failed
Oracle JDK 8 is NOT installed.
```

**Comment by BanzaiMan** [comment]
The site is unreachable from my local machine. I think we must wait for Oracle to fix the download server.

**Comment by BanzaiMan** [comment]
Oh, I see. It's getting a redirect. I think Oracle changed the download mechanism, which means that webupd8team would have to work around this new scheme.

**Comment by BanzaiMan** [comment]
It appears to be working again. https://travis-ci.org/BanzaiMan/travis_production_test/builds/174876227#L161

Please restart the previously failing builds, and let us know how it goes.

Thanks.

**Comment by BanzaiMan** [comment]
Should be fine now. Closing.

**Comment by akien-mga** [comment]
There seems to be a similar issue today with `oracle-java9-installer`: https://travis-ci.org/GodotBuilder/godot-builds/jobs/236554109

It only fails on 32-bit linux builds for me, not sure why (especially as I don't even need it, but I update everything for other necessary dependencies).

**Comment by BanzaiMan** [comment]
@akien-mga Sounds like #7778.

**Comment by akien-mga** [comment]
Indeed, thanks.

**Comment by SooLee** [comment]
I'm having the same issue.

**Comment by nikob411** [comment]
@SooLee did you find a fix?

**Comment by bearoutthere** [comment]
It's happening again.  Boggles the mind that a successful software corporation like Oracle can't get their download servers up and running.  And of course there are no mirrors.  Wtf.
