### ISSUE TITLE
travis login --pro Validation Failed 

### ISSUE THREAD

**Issue by bmarks-mylo** [travis-ci/travis-ci#6851]
I can't seem to login with the travis cli with the pro flag and 2FA.

```
$ rm -fr ~/.travis/

$ travis login --pro
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: bmarks-mylo
Password for bmarks-mylo: ********
Two-factor authentication code for bmarks-mylo: 111111
Validation Failed
for a full error report, run travis report --pro

$ travis report --pro
System
Ruby:                     Ruby 2.3.0-p0
Operating System:         Windows
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       never

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (current)

Last Exception
An error occurred running `travis login --pro`:
    RuntimeError: Validation Failed
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:208:in `basic_auth'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:214:in `rescue in basic_auth'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:208:in `basic_auth'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:221:in `login'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:80:in `possible_tokens'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:49:in `each_token'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:36:in `with_token'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/login.rb:31:in `login'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/login.rb:40:in `run'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
        from C:/sdk/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
        from C:/sdk/Ruby23-x64/bin/travis:23:in `load'
        from C:/sdk/Ruby23-x64/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by BanzaiMan** [comment]
Could you try disabling 2FA while you run `travis login`?

**Comment by jlee-locktonmylo** [comment]
I am getting the same error, 2FA disabled.  We are behind a proxy, not sure if that is coming into play or not.

travis login --pro
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: jlee-mylo
Password for jlee-mylo: *************
Two-factor authentication code for jlee-mylo: 111111
Validation Failed
for a full error report, run travis report --pro

C:\Users\JLee>travis report --pro
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Windows
RubyGems:                 RubyGems 2.6.7

CLI
Version:                  1.8.4
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       never

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (current)

Last Exception
An error occurred running `travis login --pro`:
    RuntimeError: Validation Failed
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:208:in `basic_auth'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:214:in `rescue in basic_auth'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:208:in `basic_auth'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:221:in `login'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:80:in `possible_tokens'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:49:in `each_token'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:36:in `with_token'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/cli/login.rb:31:in `login'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/cli/login.rb:40:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/cli/command.rb:198:in `execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/lib/travis/cli.rb:64:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.4/bin/travis:18:in `<top (required)>'
        from C:/Ruby23-x64/bin/travis:22:in `load'
        from C:/Ruby23-x64/bin/travis:22:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
