### ISSUE TITLE
Trusty container beta PDOException: SQLSTATE[HY000]

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#6855]
Running under [Trusty container beta](https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/)

Sort of related to issue #6842 regarding "Can't connect to local MySQL server through socket" 
Following the suggestion in that issue to "shim" or "alias" the socket I get the following issue.
```php
PDOException: SQLSTATE[HY000] [2002] No such file or directory
```
related build
https://travis-ci.org/photodude/joomla-cms/jobs/175096904#L1094-L1095

Additional possibly related issue #6853 showing problems with Trusty container beta

**Comment by photodude** [comment]
also having the following issue if I use the group:edge with `sudo: required` or with Trusty container beta
```php
PDOException: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by photodude** [comment]
Running a new test on sudo required trusty by changing the DSN host from `localhost` to `127.0.0.1` I get a new error for the user `root`
```php
PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)
```

**Comment by photodude** [comment]
The following workaround seems to work
```php
before_install:
  - "sed -i '/^[a-z_]*mysql.*socket/s:$: /run/mysql-5.6/mysqld.sock:' ~/.phpenv/versions/5.6*/etc/php.ini"
```

**Comment by jakub300** [comment]
It looks like there is default password `travis` for root. You can reset it by running `mysql -e 'SET PASSWORD FOR "root"@"localhost" = PASSWORD("");' -uroot` in `before_install`.

**Comment by photodude** [comment]
Thanks @jakub300, that might help has a work around. 

Travis has confirmed the socket issues and will be fixing them after the holidays.

**Comment by photodude** [comment]
Closing as this no longer seems to be a problem
