### ISSUE TITLE
$TERM is set but not exported

### ISSUE THREAD

**Issue by stevekuznetsov** [travis-ci/travis-ci#6857]
In some CI scripts, we have colors, terminal escapes, etc. We generally don't want these to show up in text-based logs so we used code like this to guard it:

```sh
if [[ -t 1 ]]; then
    tput el
fi
```

We noticed in Travis, this is not enough of a check -- we do have file descriptor `1` as a terminal. but `tput` fails with:

```
tput: No value for $TERM and no -T specified
```

Naturally, we changed the logic to look like:

```sh
if [[ -t 1 && -n "${TERM:-}" ]]; then
    tput el
fi
```

However, since `$TERM` is set but unexported in the shell we are given, this also fails for the same reason. `[[` is a built-in and therefore can see `$TERM` if it's not exported, but `tput` is not and cannot see that `$TERM` is set. Now we find ourselves exporting `$TERM` so `tput` can see it. 

This is strange behavior and I would not have expected `$TERM` to be set but unexported.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
In the recent past, `$TERM` was not set on containers. This was reported in #6852, but has since been fixed. https://travis-ci.org/BanzaiMan/travis_production_test/builds/175227149#L157 shows that `$TERM` should be exported to subprocesses now.

**Comment by stevekuznetsov** [comment]
I can quite figure out how to see the earlier builds, but we saw this failure in earlier builds of this PRhttps://travis-ci.org/openshift/origin/builds/175141188

**Comment by BanzaiMan** [comment]
If you restart previously failing jobs, so they fail now?

**Comment by stevekuznetsov** [comment]
We've updated our code to export `$TERM` but I can try removing it on Monday and let you know how it goes.

**Comment by BanzaiMan** [comment]
I'm not asking to change the fix you put in. I'm asking you to restart the build that you suspect didn't export `$TERM`.

**Comment by stevekuznetsov** [comment]
I managed to find the failed build [here](https://travis-ci.org/openshift/origin/builds/174869844). Re-kicking it resulted in the same failure.

**Comment by BanzaiMan** [comment]
That rerun of the PR build failed to fetch the code before it could show whether or not `$TERM` is exported, because the PR in question has been merged.

**Comment by stevekuznetsov** [comment]
Ok. I'll remove the `export` Monday and report back.

**Comment by stevekuznetsov** [comment]
This slipped my mind -- removed the `${TERM}` export, build here: https://travis-ci.org/openshift/origin/builds/184074015 

Everything looks fine.
