### ISSUE TITLE
`nproc` returns 32 now, instead of 2

### ISSUE THREAD

**Issue by iphydf** [travis-ci/travis-ci#6859]
It used to reflect the number of CPUs allocated to the container. Now it seems to be the number of CPUs in the host system.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by iphydf** [comment]
https://travis-ci.org/TokTok/c-toxcore/jobs/175223804#L719

**Comment by iphydf** [comment]
I think this is fixed.
