### ISSUE TITLE
MySQL 5.6 on Trusty seems to have `test` table in `travis` database

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#6860]
Here is failed test: https://travis-ci.org/nazar-pc/CleverStyle-Framework/jobs/175225014#L672

As soon as I added command to drop `test` table everything become fine: https://travis-ci.org/nazar-pc/CleverStyle-Framework/jobs/175228324/config

The only change made between those 2 tests: https://github.com/nazar-pc/CleverStyle-Framework/commit/17e37d4e67e5a19b92a70ebe7d4b3b334d7b8e15

There is no such table on Precise and I have doubts it should be present in Trusty.

**Comment by BanzaiMan** [comment]
Thanks for the report. It is probably a table which needs to be cleaned up during the image provisioning.
