### ISSUE TITLE
Timeout during sudo:required worker setup

### ISSUE THREAD

**Issue by alamaison** [travis-ci/travis-ci#6862]
Builds fails at random with `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`  I've read the trouble-shooting advice and know about the `travis_wait` command but these build are timing out during setting up the worker.  There's no chance for me to intervene and insert a `travis_wait` command at that point.

Here is an example failure: https://travis-ci.org/alamaison/libssh2/jobs/175290669

**Comment by BanzaiMan** [comment]
Thanks for reporting this issue. How often would you say this happens? 10%, 25%, 67%? Is it happening now?

**Comment by alamaison** [comment]
It is happening now. For every build, two to three of our jobs fail for this reason. You can't tell now looking at it because i rerun then manually

**Comment by BanzaiMan** [comment]
@alamaison Do you have a build log URL of a recent failure?

**Comment by BanzaiMan** [comment]
I think this is the same issue as #6861. I'm closing this as a duplicate.

**Comment by alamaison** [comment]
The link I posted originally is recent. I think #6861 is slightly different in that we are seeing timeouts even starting the worker. Our code never gets a chance to run. Whereas in #6861 the code runs and later hangs. 

Of course, they may have the same underlying cause

**Comment by BanzaiMan** [comment]
Do you have the build log URL for a recent failure?
