### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by vchong** [travis-ci/travis-ci#6863]
Hi,

Build jobs failing with 'No space left on device'.
Not sure how to debug, so please help?
Sample job links: [[1]](https://travis-ci.org/vchong/optee_os/jobs/175053155), [[2]](https://travis-ci.org/OP-TEE/optee_os/builds/175154277)

Thanks!

**Comment by igoropaniuk** [comment]
BTW, this issue has been reproducing since Thursday

**Comment by vchong** [comment]
Seemed to have been resolved. Thanks!

**Comment by dustinalan** [comment]
This issue needs to be reopened @BanzaiMan I'm hitting the same problem. This is running sudo apt update and failing. https://travis-ci.com/RX-PREP/learn.rxprep.com/builds/47290681

**Comment by digitalentity** [comment]
Same issue here"
