### ISSUE TITLE
OS X: brew / brew cask suddenly broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [travis-ci/travis-ci#6867]
https://github.com/caskroom/homebrew-versions/issues/2878 see there.

This suddenly broke 1-2 days ago without us changing anything.
The brew maintainers suspect that the brew setup is somehow outdated.

**Comment by BanzaiMan** [comment]
So, to recap what was discussed in the other issue, the package `osxfuse-beta` is trying to install the deprecated package `brew-cask`. Is that accurate?

**Comment by ThomasWaldmann** [comment]
It sounded like that is pointing to an outdated (brew?) installation and recent (brew?) installations have that built-in and don't even try that.

**Comment by ThomasWaldmann** [comment]
Any news on this?

All our OSX builds are still breaking.

https://travis-ci.org/borgbackup/borg/builds/179582838

**Comment by ThomasWaldmann** [comment]
Ping, still broken.

**Comment by ThomasWaldmann** [comment]
Ping, still broken.

**Comment by ThomasWaldmann** [comment]
Found it. It works like this, no idea why this changed suddenly:
```
-    brew install Caskroom/versions/osxfuse
+    brew install Caskroom/cask/osxfuse
```
