### ISSUE TITLE
[request] Cache node_modules by default

### ISSUE THREAD

**Issue by siddharthkp** [travis-ci/travis-ci#6870]
Applicable labels: `node.js`, `feature-request`, `travis-build`

Travis builds run `npm install` and `npm test` by default.

I think `node_modules` should be cached by default as well. Seems [pretty common](https://github.com/search?utf8=%E2%9C%93&q=filename%3A.travis.yml+node_modules&ref=simplesearch)

If approved, I can work on this 😃

**Comment by siddharthkp** [comment]
Umm, but there was no response on it 😢

**Comment by BanzaiMan** [comment]
Hello, there. Caching could have undesirable side effect, with stale or incompatible binary files. Enabling it by default imposes this risk on users, and I am against such behavior

**Comment by siddharthkp** [comment]
Okay, that's fair. Thanks!
