### ISSUE TITLE
Restarted build log intermixes old results?

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#6871]
Noting logs from restarted builds appear finished when they shouldn't. Also they include multiple starting points. Here's an [example]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/175428035#L229 ).

**Comment by BanzaiMan** [comment]
Hello. Thanks for reporting the issue. We will investigate.

**Comment by BanzaiMan** [comment]
Sorry for the troubles. Could you try restarting this job? The duplicates should go away now.

**Comment by jakirkham** [comment]
Thanks for looking into it. Unfortunately I can't restart this log, but I'll keep an eye on this sort of issue in the future.
