### ISSUE TITLE
No PhantomJS in generic Trusty builds

### ISSUE THREAD

**Issue by cbandy** [travis-ci/travis-ci#6873]
The docs for the Trusty CI environment state that the "environment common to all Trusty images" includes PhantomJS as a [headless browser testing tool](https://docs.travis-ci.com/user/trusty-ci-environment/#Headless-Browser-Testing-Tools). However, [the following setup fails](https://travis-ci.org/cbandy/tmp/jobs/175940172) to find a `phantomjs` executable.

```yaml
language: generic
dist: trusty
sudo: required

script:
  - command -v phantomjs
  - phantomjs --version
```

```
$ command -v phantomjs
The command "command -v phantomjs" exited with 1.

$ phantomjs --version
The program 'phantomjs' is currently not installed. To run 'phantomjs' please ask your administrator to install the package 'phantomjs'
The command "phantomjs --version" exited with 127.
```

**Comment by meatballhat** [comment]
This is working as expected on Trusty given `language: generic`, although it is a significant difference from Precise where that language routes to the Ruby image.  We don't currently have routing that takes into account the use of features like phantomjs, so my recommendation is to set something like `language: python` instead.  I'll leave this issue open until I'm able to update the docs.

**Comment by cbandy** [comment]
This appears to be resolved: https://travis-ci.org/cbandy/tmp/builds/348640813
```
$ command -v phantomjs
/usr/local/phantomjs/bin/phantomjs

$ phantomjs --version
2.1.1
```

Related: https://github.com/travis-ci/docs-travis-ci-com/issues/910
