### ISSUE TITLE
[trusty/container] Caching not enabled for trusty?

### ISSUE THREAD

**Issue by ankon** [travis-ci/travis-ci#6875]
We've switched from precise container infrastructure to trusty, mainly because precise is just too old for any sensible work, and installing additional software such as a reasonable JDK8 would eat a lot of time, and eventually broke completely.

I noticed that all our builds stopped using caching at that point, which neither the blog (https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/) nor the documentation mention. Is that an intentional change, or a bug?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by ankon** [comment]
Good question. You made me look closer, and here's another factoid: I can see the cache getting used on our OSS builds, for example https://travis-ci.org/Collaborne/paper-search/jobs/175075033 says it does use it. None of our private builds seem to use it though, see this one for example: https://travis-ci.com/Collaborne/collaborne-login/jobs/56215625.

**Comment by BanzaiMan** [comment]
Thanks for the information. We'll look into it.

**Comment by BanzaiMan** [comment]
@ankon Sorry about the issue. We spotted and fixed a configuration problem. It should be working now on .com as well. Could you confirm?

**Comment by ankon** [comment]
I now see the log entry again that the build cache is used. Awesome, that was really fast! Thanks a lot!

**Comment by BanzaiMan** [comment]
Sweet!
