### ISSUE TITLE
Allow to skip checkout

### ISSUE THREAD

**Issue by junghans** [travis-ci/travis-ci#6876]
In [losalamos/flecsi](https://github.com/losalamos/flecsi) we use docker to build the source, so it would be useful to be able to skip the checkout to save some time, e.g. in `.travis.yml`:
```
checkout:
  - true
```
This feature would also be useful in other case, e.g. [votca/csg](https://github.com/votca/csg), which runs it's own build scripts.

**Comment by BanzaiMan** [comment]
Do you mean skipping `git clone …` step?

**Comment by junghans** [comment]
Yes!

**Comment by BanzaiMan** [comment]
I am not sure if it is going to save you much time, though. It is a couple of seconds at most for this repository's builds (https://travis-ci.org/losalamos/flecsi/jobs/176135996#L85, https://travis-ci.org/losalamos/flecsi/jobs/176136000#L85). Why are other files there in this repo if you don't need them for the build?

**Comment by junghans** [comment]
Actually one can avoid a double checkout by using `COPY` in the dockerfile, see losalamos/flecsi-third-party@c50c073db37a151b684e0c476e9cbc4fa8c48b3a.
