### ISSUE TITLE
Recent images no longer have supplementary groups for root

### ISSUE THREAD

**Issue by headius** [travis-ci/travis-ci#6878]
I have no idea how this would happen, but after some recent update to the default Linux image, the root user no longer has any supplementary groups...not even the root group.

What I would expect (from an Ubuntu VM on my own machine):

```
root@headius-vbox-ubuntu64:~# ruby -e "p Process.groups"
[0]
```

What actually happens (using Travis's docker image):

```
root@20597bb335bb:/# ruby -e "p Process.groups"
[]
```

I can find no indication that this should ever be an expected result. The man page for `getgroups`, used by `Process.groups`, says nothing about a zero-length result. There is no error. The root user simple does not appear to report that it is part of the root group anymore.

This is causing tests to hang for JRuby, because logic that expects to `chown` a file to the first supplementary group (0 for root) fails to run, causing other logic to hang.

**Comment by headius** [comment]
I should add that it appears the Trusty images do not have this problem.

**Comment by meatballhat** [comment]
@headius Hello!  Can you list which docker image (incl tag) you're using above?

**Comment by headius** [comment]
`quay.io/travisci/travis-ruby   latest              e41062702ee0        21 months ago       5.783 GB`

**Comment by headius** [comment]
Interesting that it says it is from 21 months ago...did something else change recently?

**Comment by meatballhat** [comment]
OK, so that's the same image we use in production for precise builds.  It's true that no updates have been made to that image for 21mo.

What's the execution environment like for the snippet above, including the docker version?

**Comment by headius** [comment]
Latest Docker Tools, Version 1.12.3 (13776), running under OS X Yosemite.
