### ISSUE TITLE
gnutls_handshake failing, not allowing installation of a package when the source is on AWS; affects Crystal, R

### ISSUE THREAD

**Issue by miketheman** [travis-ci/travis-ci#6882]
My nightly build failed. https://travis-ci.org/miketheman/statsd.cr/builds/176381274

Specifically, the installation of the crystal package:

```
W: Failed to fetch https://dist.crystal-lang.org/apt/dists/crystal/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed
```

**Comment by miketheman** [comment]
Similar to #6881

**Comment by miketheman** [comment]
cc  @asterite, @jhass, @waj and @will who ought to know about the handshake issue.

**Comment by BanzaiMan** [comment]
This issue affects those APT sources whose backend is on AWS.

A similar issue is reported in #6881.

We have not found the issue to sidestep the issue. Until the issue is resolved on the AWS side, the builds will continue to fail, unfortunately.

**Comment by BanzaiMan** [comment]
We've closed #6881, as the CDN issue appears to have been fixed for GCE instances. Could anyone confirm that it's working for R and Crystal at this time?

**Comment by jimhester** [comment]
I can confirm it is fixed for R [working build](https://travis-ci.org/jimhester/highlite/builds/176451568)

**Comment by BanzaiMan** [comment]
@miketheman Is it working for your Crystal builds?

**Comment by miketheman** [comment]
Nope, error persists.

**Comment by chris-fa** [comment]
Fixed for nodesource on ubuntu precise

**Comment by BanzaiMan** [comment]
@miketheman Is it still a problem for you?

**Comment by miketheman** [comment]
@BanzaiMan Passing build: https://travis-ci.org/miketheman/statsd.cr/builds/176381274

Closing, as reported issues have been resolved.

Thanks!!
