### ISSUE TITLE
Kotlin reflection is having problems on Travis

### ISSUE THREAD

**Issue by MarcinMoskala** [travis-ci/travis-ci#6884]
Code is based on Gradle and works locally, but Travis throw

java.lang.IllegalStateException: Built-in library initialization failed. Please ensure you have kotlin-runtime.jar in the classpath: java.lang.NoClassDefFoundError: kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager

at each test case sience I add and started using reflection in project. The same gradle command is working perfectly well locally.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
Closing, as it's become stale.
