### ISSUE TITLE
Xcode 8.2 beta support

### ISSUE THREAD

**Issue by brianmichel** [travis-ci/travis-ci#6886]
It'd be nice to get ahead of the curve and have an Xcode 8.2 release waiting in the wings for when it goes GM.

**Comment by solarce** [comment]
We've pushed out an Xcode8.2b2 (Build 8C30a) image, which is usable with `osx_image: xcode8.2`, https://blog.travis-ci.com/2016-11-15-xcode-82-is-here.

We'll update `xcode8.2` as new betas come out and then when the stable release is launched, you won't need to change you .yml to get updates

**Comment by brianmichel** [comment]
Thanks @solarce!
