### ISSUE TITLE
Build fails with "SonarQube server [http://localhost:9000] can not be reached"

### ISSUE THREAD

**Issue by mbarre** [travis-ci/travis-ci#6888]
Hi,

First of all thanks for the work you do, travis is a really great tool.

I write to you because our build didn't work anymore since begining of the week. It seems to be a problem with sonar addon but we don't understand what's happen.

Here the command that we launch in our travis.yml file 
`mvn test jacoco:report org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_NEW_TOKEN`

and here the logs 

```
[INFO] ------------------------------------------------------------------------
[INFO] Building The dpmmc Project 9.14
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- sonar-maven-plugin:3.0.2:sonar (default-cli) @ dpmmc ---
[INFO] User cache: /home/travis/.sonar/cache
[ERROR] SonarQube server [http://localhost:9000] can not be reached
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.050 s
[INFO] Finished at: 2016-11-17T10:30:01+11:00
[INFO] Final Memory: 28M/371M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar (default-cli) on project dpmmc: Unable to execute SonarQube: Fail to download libraries from server: Connection refused -> [Help 1]
```

Do you know what's the problem ? 
Thanks in advance

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

@dbmeneses @bellingard Do you have suggestions?

**Comment by mbarre** [comment]
Here is the build log url : https://travis-ci.org/DSI-Ville-Noumea/dpmmc/builds/176209687
Thanks.

**Comment by dbmeneses** [comment]
> Skipping SonarQube Scan because this branch is not master or it does not match declared branches
..
> Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar

sonar-maven-plugin 3.0.2 doesn't support loading configuration from the environment variable that is configured by the addon. v3.2 needs to be used. Was the version locked somewhere?

**Comment by thekosmix** [comment]
Hi,

I faced the same issue. Turned out that some process was running at port 9000 that's why sonar was not able to get up and running. To my surprise, it was eclipse which was running at port 9000. please kill/stop all processes at this port and then try to run sonar.
