### ISSUE TITLE
Multiple tools needed on Travis

### ISSUE THREAD

**Issue by deajan** [travis-ci/travis-ci#6895]
Hello,

I'm using Travis CI to test a bash program with shunit2 test framework (on https://github.com/deajan/osync)
For my tests, I am using
- chattr support
- getfacl/setfacl support
- inotifywait (inotify-tools)

I'm not used to travis, anything I can do to get those missing tools ?

Thank you guys for your work :)

**Comment by BanzaiMan** [comment]
Could you elaborate what you mean by "missing"? Did we provide support for these tools at some point, or are you just asking how to make these work?

**Comment by deajan** [comment]
Sorry if I was not clear. It's probably more a question about how to get them / make them work if containers allow them.

**Comment by BanzaiMan** [comment]
Please consult https://docs.travis-ci.com/user/installing-dependencies/ to install your dependencies.

**Comment by deajan** [comment]
Thanks for your answer. After doing some RTFM, I was able get chattr and inotifywait working.
But there is no way I can get setfacl to work.

Added to following to my .travis.yml file
```
sudo:
    required

before_install:
    sudo apt-get install inotify-tools acl
```

Whenever I try to run setfacl, I get the following:
```
sudo touch /file
sudo setfacl -m o:rwx /file
sudo mount -o remount,acl /
sudo setfacl -m o:rwx /file
```

Is there anything I missed about ACL usage on Travis-CI ?

**Comment by deajan** [comment]
Any idea if Travis CI does support ACL ?

**Comment by BanzaiMan** [comment]
I do not, but if the commands fail, I doubt we do. Do keep in mind that our builds run on VMs, and not all functionalities are available.

**Comment by deajan** [comment]
I see. Thanks for your answer.
