### ISSUE TITLE
0-width terminal?

### ISSUE THREAD

**Issue by isiahmeadows** [travis-ci/travis-ci#6896]
[It's causing breakage in my builds](https://travis-ci.org/isiahmeadows/thallium/builds/176916220). Any idea what would be causing this?

**Comment by isiahmeadows** [comment]
BTW, I've narrowed it down to a Travis issue because none of those errors are reproducing locally, even with a clean install+test with the same exact version. It's not a bug with my code.

**Comment by mislav** [comment]
My build is breaking too since a few days ago due to `tty` now yielding to "not a terminal" and tmux being unable to start. I use tmux in my test suite as a driver for shell completion tests. I haven't found a workaround for convincing tmux server to start even though the build job process isn't connected to a terminal anymore.

**Comment by Gcaufy** [comment]
Also break my build.
See: 
https://github.com/Tencent/wepy/commit/2ae1994423aece3617ca355c1455df4d43ab8594
https://github.com/tecfu/tty-table/pull/29

**Comment by isiahmeadows** [comment]
The best workaround I've found is just falling back to a default if it's a terminal and has a zero-width window, whether it be in your Travis scripts or your program itself. If you are okay with just using Bash (which is what Travis uses), you can just do `[ -t 0 ] && [ "$COLUMNS" -eq "0" ] && export $COLUMNS=80` before you run anything if you don't want/need to modify your program to accommodate Travis' nonsensical value.

**Comment by Gcaufy** [comment]
@isiahmeadows thinks for your advise, but I tried the following commands, seems that `process.stdout.columns` is not changed.

```
 $ node -p -e "process.stdout.columns"
262
 $ echo $COLUMNS
262
 $ export COLUMNS=100
 $ echo $COLUMNS
100
 $ node -p -e "process.stdout.columns"
262
```

**Comment by isiahmeadows** [comment]
@Gcaufy That was right off the top of my head, although [I probably should've googled it first](http://www.thelinuxdaily.com/2010/04/set-linux-terminal-console-column-width/). 😄

**Comment by isiahmeadows** [comment]
BTW, I updated the snippet to be correct.

**Comment by Gcaufy** [comment]
@isiahmeadows cools, thanks, `ssty cols 80` works well for me.

But I tried the following code.

```
$ echo x"$COLUMNS"x
xx
$ echo x"$(tput cols)"x
x80x
$ node -p -e "process.stdout.columns"
0
```

so `tput cols` is not `0`. I have to get rid of the condition, to set cols for all osx system.

**Comment by isiahmeadows** [comment]
@Gcaufy You could probably alter the condition appropriately. (In this case, `[ -z "$COLUMNS" ]` rather than `[ "$(tput cols)" -eq 0 ]`.)

**Comment by isiahmeadows** [comment]
(Not stale, still a problem.)
