### ISSUE TITLE
Travis builds with Xcode 7, .travis.yml specifies Xcode 8.1

### ISSUE THREAD

**Issue by SebastianBoldt** [travis-ci/travis-ci#6899]
I am currently trying to get Travis running with my xcode project. But for some reason travis does not use the xcode version i specified inside my travis file

LOG
`    instance: 45f219aa-96f8-474f-8c4c-7151cf5a0470:travis-ci-osx10.11-xcode7.3-1475610688
`

.travis.yml
```

    {
      "osx_image": "xcode8.1",
      "language": "swift",
      "podfile": "Example/Podfile",
      "before_install": [
        "gem install cocoapods",
        "pod install --project-directory=Example"
      ],
      "script": [
        "set -o pipefail && xcodebuild test -workspace Example/Jelly-Animators.xcworkspace -scheme Jelly-Animators-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty",
        "pod lib lint"
      ],
      "group": "stable",
      "dist": "precise",
      "os": "linux"
    }
```
Any Ideas whats going on here?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by SebastianBoldt** [comment]
Sure. 
https://travis-ci.org/SebastianBoldt/Jelly-Animators

**Comment by BanzaiMan** [comment]
Could you try switching to `language: objective-c`? I am guessing that `language: swift` might be throwing your build off the course.

**Comment by SebastianBoldt** [comment]
I'll try that out.

**Comment by SebastianBoldt** [comment]
It seems to work. Thanks for helping me out. Issue can be closed.
