### ISSUE TITLE
getting sonartube running with C project

### ISSUE THREAD

**Issue by rgetz** [travis-ci/travis-ci#6901]
First - thanks - travis-ci is working great (almost).

I am trying to turn on sonarqube - and am having some issues (most likely between chair and keyboard).

I followed the directions at:
https://docs.travis-ci.com/user/sonarqube/

created a SONAR_TOKEN and SONAR_GITHUB_TOKEN tokens on sonarqube, encyrpted it, and put it in my travis.yml (SONAR_GITHUB_TOKEN is not documented - but the build would not start without)

My travis.yml is at:
https://github.com/analogdevicesinc/libiio/blob/travis-ci/.travis.yml

what seems to be happening is:

14:53:14.290 DEBUG: Upload report
14:53:14.537 DEBUG: POST 403 ://sonarqube.com/api/ce/submit?projectKey=iio:libiio&projectName=LibIIO&projectBranch=travis-ci | time=245ms
14:53:14.542 INFO: ------------------------------------------------------------------------
14:53:14.542 INFO: EXECUTION FAILURE
14:53:14.542 INFO: ------------------------------------------------------------------------
14:53:14.543 INFO: Total time: 47.154s
14:53:14.851 INFO: Final Memory: 78M/776M
14:53:14.851 INFO: ------------------------------------------------------------------------
14:53:14.851 ERROR: Error during SonarQube Scanner execution
Insufficient privileges

I'm not sure what "Insufficient privileges" are coming from?

Any pointers would be great.

Thanks
-Robin

**Comment by BanzaiMan** [comment]
https://travis-ci.org/analogdevicesinc/libiio/builds/177040641#L1065

Does your `$SONAR_TOKEN` have any special character in it?

**Comment by rgetz** [comment]
It shouldn't - it was added by 

travis encrypt SONAR_TOKEN=[...]

I can try a new one if that helps. ()
