### ISSUE TITLE
Builds for a particular repo queueing for hours, not sure why

### ISSUE THREAD

**Issue by carols10cents** [travis-ci/travis-ci#6902]
Hi lovely Traviscians! ❤️ I'm seeing something weird.

Builds for the https://github.com/rust-lang/book repo are sitting in an unstarted, yellow, "Hang tight, the log cannot be shown until the build has started." state for hours.

This happens consistently for this repo, for both branch builds and pull request builds.

For example, I pushed [this commit](https://github.com/rust-lang/book/commit/3510a9f21640bce2c3ea66c1eb9dd5169a236da6) to github quickly after creating it, at 2016-11-17T01:36:36Z. [The build for this commit](https://travis-ci.org/rust-lang/book/builds/176574072) has 2016-11-17T06:49:53Z on the calendar icon on the page-- a good 6 hours later :(

I'm not seeing delays nearly this long with other repos that I'm on. Is there anything we've done that is causing this? Is it because the repo is in the rust-lang organization?

Please let me know if there's any other information that would be useful! Thank you so much!! ❤️ ❤️ ❤️

**Comment by carols10cents** [comment]
Actually, now I just had some builds only take 2 hours, so maybe it's not quite as consistent as I thought. If this was a capacity thing, let me know... but I'd still love it if someone could take a look and see if we're doing anything funky <3

**Comment by sxlijin** [comment]
FWIW my experience (as an educator, so I have a pretty large sample size of builds to draw on) is that Travis builds can stay queued for up to 12 some-odd hours, even outside of U.S. business hours.

**Comment by BanzaiMan** [comment]
Thanks for the report, and we are sorry about the issue.

Is it possible (sorry, I don't have data handy to back this up) that the rust-lang org had many many build requests queued up when this `rust-lang/book` job was created? (All the repositories of the organization share one queue.)

**Comment by carols10cents** [comment]
> Is it possible (sorry, I don't have data handy to back this up) that the rust-lang org had many many build requests queued up when this rust-lang/book job was created? (All the repositories of the organization share one queue.)

I remember checking that, and there was one other repo in the organization that had builds going, but they looked like they were in this queued state as well :-/ I didn't see anything currently running. I'll try to grab a screenshot or something next time I see this happening.

**Comment by carols10cents** [comment]
Aha! Got a build queued right now, a PR in the rust-lang/crates.io repo. The trouble is when I go to https://travis-ci.org/rust-lang, it looks like NONE of the repos are building anything, because their master branches aren't currently building . But if I click into https://travis-ci.org/rust-lang/rust, I can see that it's currently building https://travis-ci.org/rust-lang/rust/builds/179783588.

It'd be super awesome if there was a page that showed an organization's queue so that I could see this state easier, since https://travis-ci.org/rust-lang doesn't show it.

**Comment by BanzaiMan** [comment]
@carols10cents I think there is an outstanding request for more visibility into an org's build queue. (If you don't see one, do let us know.)

I'm closing this now.
