### ISSUE TITLE
"Could not find any downloads that satisfy the requirement travis"

### ISSUE THREAD

**Issue by dimbleby** [travis-ci/travis-ci#6905]
When I `pip install ghp-import --user $USER` I get failure like this:

````
$pip install ghp-import --user $USER
You are using pip version 6.0.8, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting ghp-import
  Downloading ghp-import-0.4.1.tar.gz
Collecting travis
  Could not find any downloads that satisfy the requirement travis
  No distributions at all found for travis

The command "pip install ghp-import --user $USER" failed and exited with 1 during .
````

What?

Eg [here](https://travis-ci.org/dimbleby/rust-c-ares/jobs/177433724).

This worked a week or so ago - eg [here](https://travis-ci.org/dimbleby/rust-c-ares/builds/175027974)

**Comment by BanzaiMan** [comment]
It most likely means that your underlying dependencies changed, and it no longer works.

https://pypi.python.org/pypi/travis is returning 404 now. I don't know who was maintaining it. [Duckduckgo](https://duckduckgo.com/?q=pip+travis&atb=v39-5as&ia=about) thinks it was at http://medecau.github.io/travis/, but I can't find any corroborating information on Google.

At any rate, I suggest reviewing your dependencies. I am closing this now, since I don't think this is a Travis issue, but if you have evidence to suggest otherwise, do let us know.

**Comment by dimbleby** [comment]
Hmm - I'd assumed that it was you guys doing something funny because, so far as I can see, ghp-import has no dependency on anything called "travis".

Here's me installing it in a fresh virtualenv:

```
[dch@pc4296 ~]$ virtualenv tmp
New python executable in tmp/bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
[dch@pc4296 ~]$ source tmp/bin/activate
(tmp)[dch@pc4296 ~]$ pip install ghp-import==0.4.1
Downloading/unpacking ghp-import==0.4.1
  Downloading ghp-import-0.4.1.tar.gz
  Running setup.py egg_info for package ghp-import

Installing collected packages: ghp-import
  Running setup.py install for ghp-import
    changing mode of build/scripts-2.7/ghp-import from 644 to 755

    changing mode of /data/dch/tmp/bin/ghp-import to 755
Successfully installed ghp-import
Cleaning up...
```

Any idea where this "travis" dependency comes from?

**Comment by dimbleby** [comment]
ooh, perhaps I've been living in a fool's paradise with respect to the parameters that "pip install" takes...

`pip install ghp-import --user $USER`; but I dunno where that "--user" came from - and I bet that $USER is "travis".

I'll try taking that out.

**Comment by dimbleby** [comment]
yeah, that's it - sorry for the noise

**Comment by BanzaiMan** [comment]
Ah, cool. Thanks for the update. Happy to hear that you were able to resolve the issue.
