### ISSUE TITLE
No output has been received in the last 10m0s, The build has been terminated despite the travis_wait prefix to the command

### ISSUE THREAD

**Issue by Pacana78** [travis-ci/travis-ci#6908]
I'm trying to archive a build with the following command
travis_wait xcodebuild -verbose -workspace Peanut.xcworkspace -scheme Peanut -configuration Debug clean archive -archivePath build/Peanut.xcarchive DEVELOPMENT_TEAM=XXXXXXX | xcpretty

but despite the travis_wait prefix the output is the following:
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
 
this is the link to the build with the prefix travis_wait
https://travis-ci.com/team-peanut/peanut-ios/builds/35299470

and this is the link to the build without the travis_wait prefix
https://travis-ci.com/team-peanut/peanut-ios/builds/35301230

Thank you for your help.

**Comment by mickael-ange** [comment]
Relates https://github.com/travis-ci/travis-ci/issues/6861

**Comment by BanzaiMan** [comment]
Closing as a duplicate.
