### ISSUE TITLE
PKG_CPPFLAGS supplied by Makevars ignored

### ISSUE THREAD

**Issue by krlmlr** [travis-ci/travis-ci#6909]
See e.g. [RSQLite](https://travis-ci.org/rstats-db/RSQLite/builds/177675826) and previous builds.

CC @jimhester @craigcitro @hadley.

**Comment by jimhester** [comment]
R travis currently does nothing with Makevars, and nothing has changed at all recently.

Running

```shell
 git clone --depth=50 --branch=r-1.0.9016 https://github.com/rstats-db/RSQLite.git RSQLite
cd RSQLite
R CMD build .
R CMD check RSQLite_1.0.9016.tar.gz
```
Results in a check failure during package installation in `RSQLite.Rcheck/00install.out`

```c++
SqliteResultImpl.cpp:1:10: error: 'RSQLite.h' file not found with <angled> include; use "quotes" instead
#include <RSQLite.h>
         ^~~~~~~~~~~
         "RSQLite.h"
SqliteDataFrame.cpp:1:10: error: 'RSQLite.h' file not found with <angled> include; use "quotes" instead
#include <RSQLite.h>
         ^~~~~~~~~~~
         "RSQLite.h"
```

**Comment by krlmlr** [comment]
Confirmed; but devtools::check() does succeed on my system. Will investigate.
