### ISSUE TITLE
Windows build support

### ISSUE THREAD

**Issue by NeverMine17** [travis-ci/travis-ci#6910]
Hello people, i have a repo called lazers. Its using libary called TXLib.
But i cant compile my file on linux or Os x.
Can you add a windows os?

**Comment by BanzaiMan** [comment]
Hello. Windows support has been discussed before (e.g., https://github.com/travis-ci/travis-ci/issues/2104), but at the moment we do not have concrete plans to implement it.

I'm closing this now as a duplicate.
