### ISSUE TITLE
IP address range for travis-ci.com whitelisting

### ISSUE THREAD

**Issue by aweigold** [travis-ci/travis-ci#6912]
We updated various security groups per the IP change blog:
https://blog.travis-ci.com/2016-11-15-new-container-based-public-ips/

However we are still seeing intermittent errors.  The IP address page shows a different set:
https://docs.travis-ci.com/user/ip-addresses/

What is the definitive list for containers on travis-ci.com?

**Comment by BanzaiMan** [comment]
What IP address do you see?

**Comment by aweigold** [comment]
I will have to investigate to find that... but our builds are failing due to connection issues after adding the CIDRs from the blog (not the page).

**Comment by aweigold** [comment]
I added a curl command to an IP addressing site to our build... and I see the following.  It's listed on the IP address page, but not the blog... it might be useful to update the blog entry to help avoid confusion for others.

$ curl ifconfig.co
52.54.40.118
