### ISSUE TITLE
Deploy to GAE makes Travis try to install Google Cloud SDK in a Python 3.5 environment

### ISSUE THREAD

**Issue by bogdanr** [travis-ci/travis-ci#6913]
If I choose to still test my code with Python 3.5 when I want to deploy to Google App Engine, the build will fail because Travis will try to install Google Cloud SDK in a Python 3.5 environment.

Google Cloud SDK only works with Python 2.7 so Travis should know better and run gcloud in a Python 2.7 environment.

Here it's a build where this is happening:
https://travis-ci.org/bogdanr/OTA/jobs/177783107

It would be **VERY** useful to test Python apps with both 2.7 and 3.5 even when they are deployed on GAE because it would make sure the application is kept future proof.

**Comment by BanzaiMan** [comment]
Looks like we need to switch to Python 2.7 before starting PyPI deployment.

**Comment by demosdemon** [comment]
I erroneously thought that the Google Cloud SDK would honor `CLOUDSDK_PYTHON` but it's installed in the same virtualenv as the testing environment and [cannot switch interpreters](https://travis-ci.org/demosdemon/pabuco/jobs/187477169).

**Comment by BanzaiMan** [comment]
Could you try

```yaml
before_deploy:
  - source ~/virtualenv/python2.7/bin/activate
```

**Comment by demosdemon** [comment]
That works.

**Comment by BanzaiMan** [comment]
@demosdemon Good to hear. I think we'll roll this into `dpl` in a near-future release, so that you don't have to keep that workaround forever.

**Comment by BanzaiMan** [comment]
@demosdemon Could you remove the `before_deploy` workaround above, and modify your `deploy` as follows

```yaml
deploy:
  provider: gae
  edge:
    branch: gae-python-2.7
  ⋮ # rest
```

and report how it goes?

Thank you.

**Comment by demosdemon** [comment]
Looks like it failed to switch to 2.7 https://travis-ci.org/demosdemon/pabuco/builds/189215848#L432

**Comment by BanzaiMan** [comment]
@demosdemon Thanks for testing. I pushed another try. Could you restart this job? Thanks.

**Comment by demosdemon** [comment]
Same result, can't find the activate script. https://travis-ci.org/demosdemon/pabuco/builds/189215848#L436

**Comment by demosdemon** [comment]
I added an assertion to my tests to make sure the activate script is present. It passed so it is definitely present. 

https://travis-ci.org/demosdemon/pabuco/builds/189237327#L361

**Comment by BanzaiMan** [comment]
Thanks for testing again.

I made yet another change. This one is able to install SDK: https://travis-ci.org/BanzaiMan/travis_production_test/builds/189241834#L196 (Deployment fails because the repo is not set up for it.)

Could you try again? Thank you. (It would be great if you have a Python 2.7 app set up for GAE as well.)

**Comment by demosdemon** [comment]
Works for 3! I don't have a 2.7 app to test with though.

**Comment by BanzaiMan** [comment]
Test with 2.7: https://travis-ci.org/BanzaiMan/travis_production_test/builds/189286019#L195
