### ISSUE TITLE
[yarn] yarn fails to install on older OS X images

### ISSUE THREAD

**Issue by wojtkowiak** [travis-ci/travis-ci#6916]
Today, a built in support for yarn was introduced and I got this:
https://travis-ci.org/wojtkowiak/meteor-desktop/jobs/177922395

**Comment by BanzaiMan** [comment]
This looks like a new feature (https://github.com/travis-ci/travis-ci/issues/6720#issuecomment-261701985) we didn't test. I am leaning on skipping the GPG signature verification until the OS X/macOS images have `gpg`. (Installing it on the fly is possible, but will add a lot of time to the build. https://github.com/travis-ci/travis-ci/issues/6720#issuecomment-261293997)

**Comment by BanzaiMan** [comment]
Newer images (at least Xcode 8.1) have `gpg` (https://staging.travis-ci.org/BanzaiMan/example-yarn-package/jobs/525690#L97). Older ones do not, as you found out.

**Comment by BanzaiMan** [comment]
Older OS X images (`xcode7.1`, i.e., OS X 10.10, and earlier) will have difficult time with `mktemp`. This is reported as https://github.com/yarnpkg/yarn/issues/1984.

**Comment by BanzaiMan** [comment]
I've deployed the fix for missing `gpg`. We simply skip signature verification.

Older images will still have problems because of the installation script bug mentioned above. I'll keep this open for now.

**Comment by wojtkowiak** [comment]
Thanks for fast investigation.
So I will switch to `xcode8.1` image for now.

**Comment by Daniel15** [comment]
Hmm @BanzaiMan  - The Yarn installer should not fail if `gpg` is not installed, as it explicitly checks that the gpg command is available:
```sh
  # Check if GPG is installed
  command -v gpg >/dev/null 2>&1 || (
    printf "$yellow> WARNING: GPG is not installed, integrity can not be verified!$reset\n"
    return
  )
```

**Comment by BanzaiMan** [comment]
@Daniel15 I don't think that `return` works the way you think. Here's a simple example:

```bash
function foo() {
  false || (echo -n "..."; return)
  echo "no"
}
foo # => "...no"
```

You'd want a more complete `if; then; else; fi` statement:

```bash
function foo() {
  if false; then
    :
  else
    echo "..."
    return
  fi
  echo "no"
}
foo # => ...
```

**Comment by BanzaiMan** [comment]
@Daniel15 I opened https://github.com/yarnpkg/yarn/issues/2012.

**Comment by Daniel15** [comment]
> I don't think that return works the way you think

Doh, of course! You're right 👍

**Comment by Daniel15** [comment]
I'm surprised OSX doesn't come with GPG by default... Does it have its own APIs that it uses to verify integrity of files? I guess native OSX apps probably use code signing similar to Windows apps.

**Comment by BanzaiMan** [comment]
I think this can be closed.
