### ISSUE TITLE
`yarn` command not found

### ISSUE THREAD

**Issue by stianjensen** [travis-ci/travis-ci#6923]
yarn is automatically selected and run in my project which contains a yarn.lock and a package.json.

But I have multiple directories in my project where I need to run `yarn`. With npm I can add the following to my install task:
```
install:
  - npm install
  - cd other/dir && npm install
```

If i do the same with yarn I get `yarn Command not found`

**Comment by BanzaiMan** [comment]
Yes. If you override `install`, you are responsible for installing `yarn` until we roll out the image with `yarn` pre-installed.

From https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

> Please note that, at this time, Yarn is not yet pre-installed on our build images. This means that, if yarn.lock does not exist in the expected location, you are responsible for installing Yarn yourself. ( See this GitHub issue comment for a workaround.)

Thanks.

**Comment by gdub22** [comment]
@BanzaiMan Can travis's yarn detection be moved before install? My `yarn.lock` exists in the expected location, but I want to override `install` to add flags, e.g.:
```yaml
install: yarn --ignore-optional --pure-lockfile --production
```

**Comment by BanzaiMan** [comment]
@gdub22 We do not provide any command in `before_install`; it is meant to be completely customizable by the user. You are free to install `yarn` there.

**Comment by gdub22** [comment]
I'm suggesting that travis's internal yarn detection/download should happen before the actual `install` command gets called, so I don't have to install yarn manually.
