### ISSUE TITLE
Gradle not available on Mac

### ISSUE THREAD

**Issue by johnscancella** [travis-ci/travis-ci#6925]
Currently Java and Maven are already installed on OSX builds. However, gradle is only available on Linux builds. Please add gradle to the OSX images by default so you don't get errors like
```
...
$ gradle clean check
/Users/travis/build.sh: line 57: gradle: command not found
...
```
for full output see https://travis-ci.org/LibraryOfCongress/bagit-java/jobs/178291985

**Comment by SamCarlberg** [comment]
You should be able to add a [gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html)  to your project to avoid needing gradle installed. Then you can use

```bash
./gradlew clean check
```

**Comment by johnscancella** [comment]
@SamCarlberg that requires you to check in the gradle directory which adds a lot of bloat and is something I would rather not do. It also goes against Travis-ci's pattern of having the tool already installed so that I don't waste time during every build downloading the same tools

**Comment by httpdigest** [comment]
I am facing this issue, too. How can I configure the build matrix in Travis that it builds using the Gradle build.gradle and Maven pom.xml under Linux, but only using Maven's pom.xml under OSX?
Currently, my project specifies this:
```
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
language: java
script: mvn clean install -Dmaven.javadoc.skip=false
```
and it contains both a gradle.build file as well as a Maven pom.xml file (for users who want to build with either build system). Now, the above configuration triggers both the Gradle and the Maven build on Travis.
But the OSX build fails.

**Comment by BanzaiMan** [comment]
Homebrew can install `gradle` for you.

```yaml
before_install:
  - brew install gradle
```

Given that the Mac images are already large, it is unlikely that we would be making it available pre-installed.

I'm closing this for now.

**Comment by AresS31** [comment]
@BanzaiMan newbie question:
Is it possible to specify a before_install command/script only for a specific platform and if yes what would be the right syntax to use in the travis.yml file?
