### ISSUE TITLE
OS X builds can't access github repository

### ISSUE THREAD

**Issue by cipher1024** [travis-ci/travis-ci#6929]
While building: https://travis-ci.org/unitb/bipartite-graph/jobs/178421345

I get the following error on OS X. Linux is working just fine.

`Cloning into 'unitb/bipartite-graph'...
fatal: unable to access 'https://github.com/unitb/bipartite-graph.git/': Could not resolve host: github.com
`

**Comment by BanzaiMan** [comment]
Sorry about the issue. I believe this is related to this issue https://www.traviscistatus.com/incidents/3d430hxd59ft which has been resolved.

If you are still having problems, do let us know. Thanks.

**Comment by cipher1024** [comment]
It did solve the problem and very promptly too. Thanks!

**Comment by BanzaiMan** [comment]
@cipher1024 Thanks for the confirmation.
