### ISSUE TITLE
"No builds for this repository" despite .travis.yml and commit

### ISSUE THREAD

**Issue by Delthas** [travis-ci/travis-ci#6932]
Hi,
I've created a private Github repository at https://github.com/Delthas/so6rfc and added a .travis.yml in it.
I've used travis-ci.com to build and deploy from this repository and it worked fine, but now I've decided to make this repository public, I've switched to travis-ci.org and added my repository to it but even after a few commits Travis still doesn't detect any commit on the repo and shows "No builds for this repository" : https://travis-ci.org/Delthas/so6rfc

Thanks.

**Comment by BanzaiMan** [comment]
Currently public and private repositories do not share histories. Private build history does not appear on the public site, and vice versa.

**Comment by Delthas** [comment]
Yeah but I've pushed new commits to the repo after I made it public, so these should appear/trigger a build on travis-ci.org

**Comment by BanzaiMan** [comment]
Try syncing data on .org.

**Comment by Delthas** [comment]
I've already synced using the "Sync account" button on muy account page on travis-ci.org before and after adding commits but it still doesn't work :(

**Comment by BanzaiMan** [comment]
@Delthas Looks like the webhooks were incorrectly configured. I've fixed this for you now. The new commits should trigger builds on .org.

Sorry about the troubles.

**Comment by Delthas** [comment]
It works, thanks!

**Comment by galwaycoder** [comment]
Hi, I'm having the same issue after syncing multiple times, adding the .travis.yml file and pushing commits. Any recommendations?

**Comment by drberg** [comment]
I also have issues with this now. Any suggestions?

**Comment by charlesinto** [comment]
hello, please am having the same issue

**Comment by BanzaiMan** [comment]
If you are having this similar issue, please indicate the repository. Unfortunately we are unable to scan all repositories for possible problems.

**Comment by JesseMcBrennan** [comment]
Hello, I am also having this issue with [this](https://github.com/JesseMcBrennan/dress-the-child-fe) repository.

**Comment by BanzaiMan** [comment]
@JesseMcBrennan I see builds in https://travis-ci.org/JesseMcBrennan/dress-the-child-fe.

**Comment by Xerus2000** [comment]
Travis CI doesn't recognize the .travis.yml here: https://github.com/Xerus2000/monsterutilities/pull/36

**Comment by Xerus2000** [comment]
Same here: https://github.com/sghpjuikit/player/pull/99

**Comment by BanzaiMan** [comment]
@Xerus2000 https://travis-ci.com/Xerus2000/monsterutilities/requests shows that your [`.travis.yml`](https://github.com/Xerus2000/monsterutilities/blob/b113f821e933e8564a292156805acca20ae49067/.travis.yml) has syntax error.

sghpjuikit/player is not active, so that's legit. Please ask the repo owner to activate our service.

**Comment by Xerus2000** [comment]
but was there any way to see at https://travis-ci.com/Xerus2000/monsterutilities/requests where the syntax error was? I figured it out by now, but I see no way at travis for finding the error.

**Comment by shopifychamp** [comment]
Hi, @BanzaiMan  I also have the same issue. I added .travis.yml file but There are no builds for this repo yet. My repo [github link](https://github.com/shopifychamp/shopify-api-php-sdk) and [Travis link](https://travis-ci.org/github/shopifychamp/shopify-api-php-sdk) 
Thanks

**Comment by HelenGezahegn** [comment]
Hello! I am also having this problem.
- Repo link: https://github.com/IndustryBear/MentorApp
- Travis link: https://travis-ci.com/github/IndustryBear/MentorApp

-

**Comment by HelenGezahegn** [comment]
> Hello! I am also having this problem.
> 
> * Repo link: https://github.com/IndustryBear/MentorApp
> * Travis link: https://travis-ci.com/github/IndustryBear/MentorApp

Got it working! I had to change

**Comment by jhabarsingh** [comment]
Go to **More option** >  **trigger build** , It worked for me.

![Selectionshot_2020-08-02_14:03:07](https://user-images.githubusercontent.com/43932986/89119091-1be92280-d4c9-11ea-859e-e0e4a633e98e.png)
![Selectionshot_2020-08-02_14:03:31](https://user-images.githubusercontent.com/43932986/89119096-21df0380-d4c9-11ea-9840-468a44468213.png)
![Screenshot_2020-08-02_14:03:48](https://user-images.githubusercontent.com/43932986/89119101-286d7b00-d4c9-11ea-97d7-86551c3285be.png)
![Screenshot_2020-08-02_14:03:53](https://user-images.githubusercontent.com/43932986/89119104-2dcac580-d4c9-11ea-93f8-624508b29559.png)

**Comment by akhopkar01** [comment]
Hi @BenzaiMan, I am having the issue with [this repo](https://github.com/akhopkar01/Object-Tracking-for-Self-Driving-Cars). I made the repo public from private to make sure travis runs on it but in vain. Please help. Thanks.

**Comment by hg13190** [comment]
Hi @BenzaiMan, me too have the same issue with this repo https://github.com/hg13190/AcademicallyDemoAut

**Comment by arhrina** [comment]
@jhabarsingh Thank you for your comment. I have solved it

**Comment by Eugeniocalabresi** [comment]
> Vai a **Altro opzione** > **trigger build** , ha funzionato per me.
> 
> ![Selectionshot_2020-08-02_14:03:07](https://user-images.githubusercontent.com/43932986/89119091-1be92280-d4c9-11ea-859e-e0e4a633e98e.png) ![Selectionshot_2020-08-02_14:03:31](https://user-images.githubusercontent.com/43932986/89119096-21df0380-d4c9-11ea-9840-468a44468213.png) ![Screenshot_2020-08-02_14:03:48](https://user-images.githubusercontent.com/43932986/89119101-286d7b00-d4c9-11ea-97d7-86551c3285be.png) ![Screenshot_2020-08-02_14:03:53](https://user-images.githubusercontent.com/43932986/89119104-2dcac580-d4c9-11ea-93f8-624508b29559.png)

love u
