### ISSUE TITLE
Yarn isn't installed automatically

### ISSUE THREAD

**Issue by MiguelMadero** [travis-ci/travis-ci#6933]
I have a repo with yarn.lock, when I run yarn it crashes since it doesn't exist. According to [this blogpost](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn) yarn will be installed if yarn.lock is present. 

Workaround: installing it manually fixes the problem. There're many ways to do this https://github.com/travis-ci/travis-ci/issues/6720#issuecomment-254988120 

Still the blog post is misleading. 

**1/26 update. Workaround found and confirmed:** 

> You can put bower under before_script: or in postinstall in package.json to avoid this

Thanks @binoculars for finding this and @giovannipessiva for confirming. Read below for more details.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by bhough** [comment]
@BanzaiMan Here is one with the issue described above: https://travis-ci.com/bhough/the-shift/jobs/58117881

Repo has a `yarn.lock` file in the root.

**Comment by MiguelMadero** [comment]
Sorry. @BanzaiMan it's a private repo. Here is the failure: https://travis-ci.com/zenefits/ui-logger-service/builds/35556434

This is the one after explicitly installing yarn: https://travis-ci.com/zenefits/ui-logger-service/builds/35556520

**Comment by nathanhammond** [comment]
The [fully documented behavior](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Travis-CI-supports-yarn) appears to only work when you also don't specify an `install` hook.

**Comment by MiguelMadero** [comment]
Thanks good to know.

**Comment by MiguelMadero** [comment]
That's bad, since we still need to the `install` hook for `bower install`.

**Comment by binoculars** [comment]
@MiguelMadero You can put `bower` under `before_script:` or in postinstall in package.json to avoid this

**Comment by giovannipessiva** [comment]
I fixed the `yarn: command not found`error by placing all the yarn commands in the before_script section, instead of the install section

**Comment by MiguelMadero** [comment]
I can confirm that moving it to `before_script` works and we can remove two steps and the yarn cache.

**Comment by MiguelMadero** [comment]
While there is a "workaround" I'll leave this open since others are finding this information useful and the original article that led to the confusion hasn't been updated.

**Comment by edmorley** [comment]
This can be closed as yarn is now installed in the base image.

**Comment by BanzaiMan** [comment]
Indeed.
