### ISSUE TITLE
Abuse detected

### ISSUE THREAD

**Issue by IevgenKulyk** [travis-ci/travis-ci#6942]
Hi, guys. Could you please explain what does this message mean:

abuse detected: known offender (request looked fishy)

And what should I do when find this message?

**Comment by BanzaiMan** [comment]
Please email us at support@travis-ci.com. As individual causes differ, I am going to close this ticket.

We will follow up on the support ticket. Thanks.

**Comment by Hadis-Fard** [comment]
@BanzaiMan we are facing the same issue in our build, Travis didn't run the build on a PR with "abuse detected: known offender (request looked fishy)", what should i do when I get this error?

**Comment by Spongman** [comment]
i'm also running into this. sent an email to support, nothing yet, though...
