### ISSUE TITLE
Python3.6 VM fails with bz2 tar error

### ISSUE THREAD

**Issue by mjpieters** [travis-ci/travis-ci#6946]
Python 3.6 runs never get to the code-under-test, because the environment can't be set up:

```
3.6 is not installed; attempting download
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

The command "sudo tar xjf python-3.6.tar.bz2 --directory /" failed and exited with 2 during .
```

See a [full job log here](https://api.travis-ci.org/jobs/179571415/log.txt?deansi=true).

**Comment by BanzaiMan** [comment]
"3.6" is not yet released, so you can't use that yet. See #6839.

**Comment by mjpieters** [comment]
Ah, mea culpa, I should have read the documentation more closely.
