### ISSUE TITLE
hhvm environment has old phpunit

### ISSUE THREAD

**Issue by splitbrain** [travis-ci/travis-ci#6956]
Because different PHP versions need different versions of phpunit I like to rely on the preinstalled phpunit version. This works great for standard PHP. Eg. PHP 5.3 has an old phpunit while PHP 7.1 uses the newest available one.

However when using the hhvm environment, the preinstalled phpunit version is 4.5.0 instead of a more recent version.

Would be great if your could fix that.

**Comment by photodude** [comment]
@splitbrain you need to update your .travis.yml . HHVM stopped supporting precise with HHVM 3.6.6 so you need to use Trusty to test vs current HHVM 3.15.3. 

Follow this guide. https://docs.travis-ci.com/user/languages/php#HHVM-versions

**Comment by photodude** [comment]
Here is an example PR https://github.com/splitbrain/dokuwiki/pull/1774 you can apply to your repos that will get you testing on the current HHVM which has PHPUnit 5.7.2

**Comment by BanzaiMan** [comment]
Is there anything for us to do here?

**Comment by photodude** [comment]
Considering the work already done to allow for different hhvm lts versions as noted in this link, https://docs.travis-ci.com/user/languages/php#HHVM-versions I don't think there is anything that needs to be done (but I'm not the issue submitter so opinions may differ)

**Comment by splitbrain** [comment]
First of all, thanks for providing a pull request. I still think that your images should provide a phpunit compatible with the provided PHP version even if that's an outdated version (as it seems to be the case with hhvm on the default image). But I'm fine with you closing this if you prefer to focus on the upcoming trusty updates.

**Comment by BanzaiMan** [comment]
@splitbrain Could you elaborate on what you are asking? Is HHVM on Precise working with an older version of PHPUnit and it is OK (which I think is what you are saying in the last comment), or are you asking to have PHPUnit updated for HHVM on Precise (which I think is what you are saying in the original description of this ticket)?

If the older version of PHPUnit is fine, then this ticket seems like a non-issue.

**Comment by splitbrain** [comment]
the phpunit version needs to be updated. the installed phpunit version does not work with the installed version of hhvm.

**Comment by photodude** [comment]
@splitbrain phpunit doesn't support running on hhvm, in fact they have removed it from their testing environment. I've run tests against the phpunit self tests on their repo vs hhvm and the self tests fail to even compete, they just die without error messages on some test. 

We all have been lucky when our repo phpunit tests run on hhvm at all considering phpunit's lack of support and compatibility with hhvm. 

For some joomla-framework repos we use composer to specify which phpunit version we run on for different php versions and what minimum phpunit version is used.

**Comment by BanzaiMan** [comment]
If the newer versions of PHPUnit are incompatible with HHVM, then it is not very helpful to upgrade. Maybe it is worth documenting in our docs, but essentially this looks like the dead end for the HHVM-PHPUnit relationship.

**Comment by splitbrain** [comment]
I don't know anything about the official state. All I know is that the installed phpunit and hhvm did not work on our test suite and that upgrading phpunit made it work.

**Comment by splitbrain** [comment]
- failing: https://travis-ci.org/splitbrain/dokuwiki/jobs/180121034
- succeeding: https://travis-ci.org/splitbrain/dokuwiki/jobs/180128285

**Comment by photodude** [comment]
@splitbrain remember hhvm 3.6.6 is EOL. As for your error, I'm not sure but it looks like the issue of "class already declared" is related to phpunit 4.5, there possibly was a fix in PHPUnit 4.6.6. https://github.com/sebastianbergmann/phpunit/issues/1684 (although personally, I would choose phpunit 4.8.x as a minimum and an hhvm version that is not EOL)

**Comment by BanzaiMan** [comment]
Thanks for the information and discussion.

At the time of build image provisioning for https://travis-ci.org/splitbrain/dokuwiki/jobs/180121034 (circa February, 2015), PHPUnit version 4.5.0 was most current, I believe. It may or may not have been fully compatible with HHVM 3.6.6. (According to this build, it is not, and maybe it was not completely unexpected) I can't say that this is the most user-friendly setup, but sometimes bad combinations do happen.

Furthermore, it would have been impossible to foresee that a future version of PHPUnit (5.5.6) would be compatible with HHVM on Precise (at least, for the part of the code https://travis-ci.org/splitbrain/dokuwiki/jobs/180128285 exercises), which the HHVM would drop support for shortly after.

Thought this is a rather unfortunate situation, there is a fortunate workaround of upgrading (or, at least, it is better than PHPUnit 4.5.0) if users on HHVM wants to try it. This is perhaps mentioning in our docs.

Overall, though, I do not think we would be making effort to provide HHVM on Precise. (I do not think you can get Precise packages for HHVM any longer, so we can't provision it.)

I'm closing this now.

**Comment by photodude** [comment]
@BanzaiMan It wouldn't be an HHVM change on Precise. it would be a change to the PHPunit version installed on the HHVM Precise image. the current version is PHPUnit 4.5.0 but it would be better if the default installed version was PHPUnit 4.8.x

That being said, with the public release of the Trusty beta container image I would rather see effort put into that rather than the old Precise images.
