### ISSUE TITLE
Issues with MySQL on the newly released sudo-enabled Trusty images

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-ci#6961]
Customers are reporting issues with MySQL [on our newly released sudo-enabled Trusty images](https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/).

This issue can happen on builds with the following configuration:

```
sudo: required
dist: trusty
```
Here's some more information and suggestions on how to work around them while we straighten things up.

**MySQL 5.6 is now pre-installed by default.** As a result, you might run into issues if you are trying to install MySQL 5.5. Please send an e-mail to support [at] travis-ci [dot] com if you need help installing MySQL 5.5.

**The MySQL service is currently named `mysql-5.6`.** but we are looking into setting it back to `mysql`. In the meantime, if you need to interact with the service, we recommend the following command to ensure your builds won’t break when the name changes:

`sudo service mysql {verb} || sudo service mysql-5.6 {verb}`

**In case of emergency:** you can add the following to your .travis.yml file to route your builds back on the previous version of the image:

`group: deprecated`

If you are still having issues, please e-mail us: support [at] travis-ci [dot] com. Make sure to include the name of your repository and a link/URL to a build log on travis-ci.com or travis-ci.org showing the problem we should investigate.

Thank you for your patience.

**Comment by glebm** [comment]
Another issue seems to be that it is no longer possible to use the `root` user without a password to connect to mysql.

**Comment by camertron** [comment]
@glebm yeah, we're seeing a manifestation of that as well. This works:

`mysql -u root -h 127.0.0.1 -e "SHOW DATABASES"`

but ActiveRecord/Rails can't establish a connection.

**Comment by glebm** [comment]
Looks like the empty password is not set for `root@localhost` (it's only set for `root@127.0.0.1` which is not the same).

This workaround in `before_install` seems to work:

```bash
mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
```

**Comment by camertron** [comment]
@glebm yep, that works for me as well. Thanks!

**Comment by meatballhat** [comment]
This issue *should* be resolved now that [this update](https://docs.travis-ci.com/user/build-environment-updates/2016-12-02/) is live, at least according to the [tests in the image mastering process](https://github.com/travis-ci/packer-templates/blob/10d938a0befbf17921ba3a6e7a7fb185ea2234fa/cookbooks/lib/features/mysql_spec.rb) and [manual verification](https://travis-ci.org/meatballhat/cloaked-octo-tyrion/builds/180739516).  Please yell if you see otherwise! :heart:

**Comment by glebm** [comment]
@meatballhat Since it's Christmas, can we also get MySQL 5.7 here and on the container image? Or at least MySQL 5.6 on the container image? 🙏 

And congrats on finally pushing v5.6 five years after its release. 🎉

**Comment by ashawley** [comment]
Looks like the package name for `mysql` is resolved.  What about affiliated packages, like mysql-server?

[.travis.yml](http://github.com/TechEmpower/FrameworkBenchmarks/blob/4bd7b77/.travis.yml):

```
  apt:
    packages:
      - mysql-server
      - redis-server
```

Here is the error.

```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install mysql-server redis-server
Reading package lists...
Building dependency tree...
Reading state information...
redis-server is already the newest version.
...
The following packages have unmet dependencies:
 mysql-server : Depends: mysql-server-5.5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by BanzaiMan** [comment]
@ashawley Could you open a separate issue on downgrading MySQL on Trusty from 5.6 to 5.5? Thank you!
