### ISSUE TITLE
RVM 1.8.7 fails for Precise

### ISSUE THREAD

**Issue by ygt-mikekchar** [travis-ci/travis-ci#6963]
This seems to have just started happening today.  It seems like the binaries are missing.  I'm not sure if that was intentional or not:

```
5.72s$ rvm use 1.8.7 --install --binary --fuzzy
ruby-1.8.7 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-1.8.7 do rvm gemset create ' first, or append '--create'.
The command "rvm use 1.8.7 --install --binary --fuzzy" failed and exited with 2 during .
```

Yes, I know: what the heck are we doing on 1.8.7???... :-P

**Comment by BanzaiMan** [comment]
Sorry about the issue. The archive with the name `1.8.7` was not available for Precise (and we'd removed it from the latest image). I copied `1.8.7-p371` to `1.8.7`. Please try again and report if it works for you?

Thanks.

**Comment by ygt-mikekchar** [comment]
Hmm... Doesn't seem to work, unfortunately.  I'll try 1.8.7-p371.

**Comment by ygt-mikekchar** [comment]
Yep 1.8.7-p371 works fine it seems.  As far as I'm concerned that's OK, though I won't close the issue in case you want to work on it some more.

**Comment by BanzaiMan** [comment]
Do you have a recent build log URL that shows `1.8.7` doesn't work?

**Comment by ygt-mikekchar** [comment]
By the way, I neglected to thank you for your prompt and helpful response.  I really appreciate it.

I resubmitted this one 20 minutes ago: https://travis-ci.com/ygt/sales/builds/35945023

But now I'm wondering if resubmitting won't work...  Perhaps I should make a different test.

**Comment by ygt-mikekchar** [comment]
Nope.  I tried it with https://travis-ci.com/ygt/sales/builds/35956474 and it also fails.  Note, however that the .travis.yml doesn't specify precise in this one, which was what I originally thought the problem way.

**Comment by BanzaiMan** [comment]
Thanks for the information. I seem to remember that there is special logic in RVM that maps 1.8.7 to something unexpected, but the details escape me at the moment.

I am happy to hear that `1.8.7-p371` work for you now. I will investigate this in a bit more detail next week.

Again, sorry for the troubles.

**Comment by ygt-mikekchar** [comment]
No problem.  The information you gave me helped me a lot.  I would have been pulling my hair out with out it :-)

**Comment by sethherr** [comment]
I also ran into this error&mdash;manually specifying a ruby from [rubies.travis-ci.org](http://rubies.travis-ci.org) fixed the 1.8 issue&mdash;but `ree` is still broken, even with a specified version ([example build](https://travis-ci.org/papertrail/papertrail-cli/builds/180801627))

**Comment by segiddins** [comment]
This has caused new bundler builds to fail unexpected, with no changes to our CI config: https://travis-ci.org/bundler/bundler/builds/180589444

**Comment by MikaelSmith** [comment]
Also running into it at https://travis-ci.org/puppetlabs/mcollective-package-agent/jobs/182322482

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-build/pull/911

**Comment by BanzaiMan** [comment]
I cannot get RVM to install REE on the fly. RVM appears to have a list of locations to pull archives from, and none of them are hosting REE any more.

**Comment by BanzaiMan** [comment]
↑ probably means that we cannot provision an image with REE at all.

**Comment by BanzaiMan** [comment]
A fix has been deployed to .org and .com. When you specify:

```yaml
rvm:
  - '1.8.7'
```

we remap it to `1.8.7-p371`, so that the installation can proceed on the fly.

As I mentioned earlier, REE appears to be unattainable at this time, unfortunately. If you need it, it will have to be added separately with `group: deprecated`. (Note that this may go away any time; it is not practical to support a runtime that stopped updating 4+ years ago.)

```yaml
matrix:
  include:
    - rvm: 'ree'
      sudo: required
      dist: precise
      group: deprecated
```

I'm closing this now, as I believe we've addressed all the issues. If you believe otherwise, do let us know.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/913 enables on-demand installation of REE from source when it is not pre-installed. I've tested it on both Precise and Trusty containers. It adds 4 minutes to the build time, but I hope that is an acceptable compromise.
