### ISSUE TITLE
Trusty kernel upgrade to 4.4.0-45 without announcement?

### ISSUE THREAD

**Issue by domdom82** [travis-ci/travis-ci#6964]
Since today (12/02/2016) my travis builds report as

```
Build image provisioning date and time
Tue Nov 29 16:08:52 UTC 2016
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Linux Version
4.4.0-45-generic
```

which is an update from 3.18 before. Due to DirtyCow, possibly?

I could not find anything on the env feed: https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/

Don't get me wrong - this is great! Been waiting for this for months!

However why did this update go without notice? I think this should be big news, right?

Thanks

**Comment by BanzaiMan** [comment]
Hello. Thanks for opening the issue.

We have opted not to announce kernel updates at this time. Kernel updates could come for various reasons, most likely by way of updates to the base image we use when we provision new images. Guaranteeing kernel versions could be difficult, and documenting them can give false impressions that users can rely on them.

Thanks for your understanding.

I am closing this at this time, but if you have additional questions, do let us know.

**Comment by domdom82** [comment]
Thanks for your response. However I think Travis needs to rethink their policy in this regard. Projects that heavily rely on container technology like Docker are tightly bound to what the underlying OS kernel does support. The latest features in container technology usually requires a fairly recent Linux kernel to match.
