### ISSUE TITLE
Builds created but not running

### ISSUE THREAD

**Issue by aantron** [travis-ci/travis-ci#6965]
Hello,

I have several builds in one repo that have been created, but have not started running:

- https://travis-ci.org/ocsigen/lwt/builds/180762303
- https://travis-ci.org/ocsigen/lwt/builds/180721298
- https://travis-ci.org/ocsigen/lwt/builds/180721316

I have tried restarting the latter two twice. The corresponding requests page: https://travis-ci.org/ocsigen/lwt/requests

A build in another repo started and completed successfully in the meantime: https://travis-ci.org/aantron/lambda-soup/requests

`.travis.yml` hasn't changed since the last commit in the broken repo.

Any information or assistance would be appreciated.

**Comment by ryan-williams** [comment]
Seeing the same thing, 3 builds / 7 jobs across 3 repos, have all been waiting to start for several hours:

https://travis-ci.org/hammerlab/magic-rdds/builds/180782151
https://travis-ci.org/hammerlab/adam/builds/180782573
https://travis-ci.org/hammerlab/genomic-loci/builds/180782412

Status page has said 0 backlogs this whole time for all but OSX-based projects, which these are not.

cf. https://github.com/travis-ci/travis-ci/issues/6725 which asks for an indication about how long builds have been in this state, among other things.

**Comment by BanzaiMan** [comment]
Sorry for the troubles. Please keep in mind that if your organization runs OS X jobs, these can trickle to the top of the build queue for the organization and block Linux builds as a result.

**Comment by aantron** [comment]
Thanks. I suppose this issue can be closed.

It may be good to warn somewhere that having OS X jobs can have this effect. Perhaps somehow mentioning this in status updates or on the status page is sufficient, as I read those. I had expected the behavior today to be that the Linux jobs in each build would run, but the OS X jobs would not run for a long time, not that the entire builds would be waiting.
