### ISSUE TITLE
Linux builds cannot kick off

### ISSUE THREAD

**Issue by lanxi** [travis-ci/travis-ci#6966]
Hi there,

Our travis builds created after a [change](https://github.com/facebook/proxygen/commit/c8deec93930dfd8efc46fc0a60883205a2f2b087) to the [.travis.yaml](https://github.com/facebook/proxygen/blob/master/.travis.yml) for adding c++14 dependencies cannot seem to start for some reason. Could anyone shed some light on why this is happening?

Some of the pending builds:
https://travis-ci.org/facebook/proxygen/builds/180589985
https://travis-ci.org/facebook/proxygen/builds/180759169

Thank you very much!

**Comment by BanzaiMan** [comment]
This is basically the same issue as #6965. There are Mac jobs near the top of the build queue which are preventing Linux jobs to start. Sorry about the issue, but I'm closing this as a duplicate.
