### ISSUE TITLE
General Mac VM network connectivity issue around 2016-12-05

### ISSUE THREAD

**Issue by kovidgoyal** [travis-ci/travis-ci#6968]
Ever since the latest OS X breakage, casher fetching is failing on my OS X builds: For example https://travis-ci.org/kovidgoyal/calibre/jobs/181062365

Error message:

The command "curl https://raw.githubusercontent.com/travis-ci/casher/production/bin/casher  -L -o $CASHER_DIR/bin/casher -s --fail" failed and exited with 77 during .

**Comment by BanzaiMan** [comment]
Looks like a temporary connectivity issue. I'm closing this now optimistically, but if you see the problem consistently, do let us know.

**Comment by kovidgoyal** [comment]
It's been that way consistently for days, ever since the lastest bout of OS X issues started, for example the latest build: https://travis-ci.org/kovidgoyal/calibre/jobs/181355884
Previous failing builds: https://travis-ci.org/kovidgoyal/calibre/jobs/181351089
https://travis-ci.org/kovidgoyal/calibre/jobs/181342039
https://travis-ci.org/kovidgoyal/calibre/jobs/181326025
A build from five days ago showing the same failure
https://travis-ci.org/kovidgoyal/calibre/jobs/180340975

I have had to add os x to acceptable failures, since it is currently always failing.

**Comment by BanzaiMan** [comment]
Oh, I see.

**Comment by BanzaiMan** [comment]
This looks like a general network failure. https://travis-ci.org/kovidgoyal/calibre/jobs/181355884#L48

**Comment by BanzaiMan** [comment]
Could you retry it now?

**Comment by kovidgoyal** [comment]
Restarted the job, same error:
https://travis-ci.org/kovidgoyal/calibre/jobs/181556008

**Comment by BanzaiMan** [comment]
What's in `$PWD/resources/mozilla-ca-certs.pem`? https://travis-ci.org/kovidgoyal/calibre/jobs/182492236#L53 I think that is changing the certificates with which `curl` (and probably `nvm`) is checking the connections.

**Comment by kovidgoyal** [comment]
The same set of certificates as is used by curl (they are downloaded from 'https://curl.haxx.se/ca/cacert.pem') And they have been present and working for a very long time, in both linux and OS X builds.

**Comment by kovidgoyal** [comment]
The last change to the environmnet variables was on Jun 26 https://github.com/kovidgoyal/calibre/blame/master/.travis.yml

Long before this error started appearing.

**Comment by BanzaiMan** [comment]
How are you getting that file? It doesn't exist in https://github.com/kovidgoyal/calibre/tree/master/resources.

**Comment by kovidgoyal** [comment]
It is generated as part of the build process. https://github.com/kovidgoyal/calibre/blob/master/setup/resources.py#L232

**Comment by BanzaiMan** [comment]
That doesn't make sense. `nvm`, as well as `curl` are getting executed before any of your code has a chance to run. Try setting `SSL_CERT_FILE` *_after_* the file has been generated.

Of course, this doesn't explain why it was working before.

**Comment by kovidgoyal** [comment]
So, to be clear, it does not exist when the casher fetch fails. Maybe that's the cause of the problem...although as I said it used to work before. Perhaps newer versions of curl fail when the file is missing, while old ones did not?

**Comment by BanzaiMan** [comment]
One possible explanation is that OS X changed the way it looks up certs. I don't have access to an old OS X image, so I can't say this for sure.

**Comment by kovidgoyal** [comment]
Yeah, I think it was caused by the updated version of curl working differently w.r.t to that ENV VAR. Moving the export to later in the build process seems to have fixed it.
