### ISSUE TITLE
PHP 7.2 Environment Installation Failed

### ISSUE THREAD

**Issue by marktopper** [travis-ci/travis-ci#6969]
See https://travis-ci.org/marktopper/voyager/jobs/181103164

When installing the PHP 7.2 environment:

```
$ phpenv global 7.2
rbenv: version `7.2' not installed
The command "phpenv global 7.2" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by kiulkiel** [comment]
Didn't ever think it was going so that's too bad. Oh well. Doesn't mean I
will stop trying. Git myself off the floor and git what's mine. Never give
up on your dream

**Comment by kiulkiel** [comment]
Didn't ever think it was going so that's too bad. Oh well. Doesn't mean I
will stop trying. Git myself off the floor and git what's mine. Never give
up on your dream

**Comment by BanzaiMan** [comment]
Hello. We rely on https://github.com/php-build/php-build/tree/master/share/php-build/definitions to provide us with how to build stuff. There is no definition for 7.2 yet (and we haven't build an archive for it), so your build will fail.

**Comment by marktopper** [comment]
Thanks 👍

**Comment by BanzaiMan** [comment]
For reference: https://github.com/php-build/php-build/issues/416

**Comment by fiddike** [comment]
PHP 7.2 build definition is now available on https://github.com/php-build/php-build/tree/master/share/php-build/definitions

**Comment by BanzaiMan** [comment]
@fiddike Indeed. As noted in https://github.com/travis-ci/travis-ci/issues/8845#issuecomment-348706181 and elsewhere, 7.2 has been available for about 2 weeks. Enjoy!

**Comment by ktomk** [comment]
I still see these occasionally, restarting the build normally works:

~~~
phpenv global 7.2
rbenv: version `7.2' not installed
~~~
I'm a bit puzzled why it says "rbenv" for the "phpenv" command. 

- https://travis-ci.org/ktomk/pipelines/jobs/327044465#L457-L461 (PHP 7.2) 
- https://travis-ci.org/ktomk/pipelines/jobs/327044466#L466-L470 (PHP 7.0snapshot)
