### ISSUE TITLE
Git log not working as expected after merging branches

### ISSUE THREAD

**Issue by andrey-nest** [travis-ci/travis-ci#6975]
Preconditions: Travis is configured to build commits or PR into _A_ branch.

1. Create _B_ branch or use existing one.
2. Commit some _*.sql_ files into _B_ branch. (repo has folder named __sql_ for added sql files)
3. Merge _B_ branch into _A_ branch.
4. Build triggered.
5. Executed command: 
`git --no-pager log --reverse --diff-filter=A --no-merges --pretty=format:"" --name-only $TRAVIS_COMMIT_RANGE -- _sql | grep '_sql/.*' > sqls.txt || >/dev/null`

_Actual result:_ command returns **list of all** .sql files from _sql folder
_Expected result_: command should return only list of added sql files in range $TRAVIS_COMMIT_RANGE

I've spent pretty much time testing different scenarios, but seems like this behavior occurs only after merges. Regular commits into _A_ branch fetches only newly added _.sql_ files if it was.

I've even hardcoded commits range:
`git --no-pager log --reverse --diff-filter=A --no-merges --pretty=format:"" --name-only 0fbeaad69cbe...7fcb4f5a17bc -- _sql | grep '_sql/.*' > sqls.txt || >/dev/null`
Same result.

I think it's Travis issue because git command executes locally with expected output regardless of whether it was merge or commit.

Thank you.

**Comment by andrey-nest** [comment]
Here is simplified raw log: [raw_build.txt](https://github.com/travis-ci/travis-ci/files/642282/raw_build.txt)

Maybe you'll want to know, what's going on in fetch_commit_range.sh 
Here is content of bash script:

```
SQL_REVISION_NUMBER=$TRAVIS_COMMIT_RANGE

if [ "$FETCH_SQLS_FROM" ]; 
	then SQL_REVISION_NUMBER="$FETCH_SQLS_FROM..HEAD" 
elif [ -z "$TRAVIS_COMMIT_RANGE" ]; 
	then SQL_REVISION_NUMBER="$TRAVIS_COMMIT..HEAD"
fi

echo "$SQL_REVISION_NUMBER"
```

Thank you.

**Comment by BanzaiMan** [comment]
The link above is invalid. Do you have a valid one? Does the log behave as you expect if you start from a fresh clone? Your local clone may have something that your remote on GitHub does not, and log output might be different.

**Comment by andrey-nest** [comment]
> The link above is invalid. Do you have a valid one?

I can't share a direct link to a build job since my repository is private. Here is alternative link to log file https://goo.gl/RWcdd3 if you can't open previous one.

> Does the log behave as you expect if you start from a fresh clone?

I'll try with a fresh clone and will inform you about the result.

**Comment by BanzaiMan** [comment]
@andrey-nest Have you had a chance to investigate further?

You can email us at support@travis-ci.com if you would like to continue discussing.

I'm closing this public issue for now, since there is not much to discuss publicly.
