### ISSUE TITLE
travis.yml not correctly exporting env set in bash script? 

### ISSUE THREAD

**Issue by shuynh** [travis-ci/travis-ci#6976]
i have a spec folder that i'm trying to split in half to take advantage of travis' parallel build matrix. instead creating 2 folders, i'm trying to use `declare` and bash to split the folder up. 

my travis.yml has these sections:
``` 
env:
  - SPEC_PATH="$FEATURES_1"
  - SPEC_PATH="$FEATURES_2"

before_script: chmod a+x travis.sh

script: ./travis.sh && bundle exec rspec $SPEC_PATH
```

and my script looks like this:
```
#!/bin/bash

declare -x FEATURE_FILES=(*spec/features/*_spec.rb)

FILE_COUNT=${#FEATURE_FILES[@]}; FEATURES_1=${FEATURE_FILES[@]:0:$(($FILE_COUNT/2))}; FEATURES_2=${FEATURE_FILES[@]:$(($FILE_COUNT/2)):$FILE_COUNT}

echo FEATURES_1= $FEATURES_1
echo FEATURES_2= $FEATURES_2
```

in my log, i see that's spitting out the correct spec files.. 
```
chmod a+x travis.sh
./travis.sh && bundle exec rspec $SPEC_PATH
FEATURES_1 = spec/features/add_spec.rb spec/features/address_spec.rb spec/features/apples_spec.rb spec/features/email_spec.rb spec/features/courier_spec.rb spec/features/different_bill_spec.rb 
FEATURES_2 = spec/features/founders_spec.rb spec/features/genius_add_spec.rb  spec/features/hundred_percent_spec.rb spec/features/master_spec.rb spec/features/unrecognized_spec.rb spec/features/with_promocode_spec.rb
```
but rspec seems to be running without the env variables. both jobs are just running the full rspec features folder. is this just a syntax issue? i know travis doesn't like multiple lines in the `script` section, but i thought putting it all in a bash would help.

**Comment by BanzaiMan** [comment]
`SPEC_PATH="$FEATURES_1"` should be exported before `travis.sh` is executed and sets `$FEATURES_1` value *inside* the script. `$SPEC_PATH` is empty when the execution gets to `bundle exec rspec`.

If you want to set `$SPEC_PATH` at the time of execution, you need to be a bit cleverer. For example, you might want to try:

```
SPEC_PATH=$(echo $FEATURES_1)
```

**Comment by shuynh** [comment]
thanks for the response @BanzaiMan ! 
hmm.. i think i'm misunderstanding how/where the export is supposed to work. is `$SPEC_PATH` getting emptied in the matrix stage? should i be using a global variable? 
are you suggesting using the `before_script` like this? 
```
env:
  - SPEC_PATH="$FEATURES_1"
  - SPEC_PATH="$FEATURES_2"

before_script: 
- chmod a+x travis.sh
- SPEC_PATH=$FEATURES_1

script: ./travis.sh && bundle exec rspec $SPEC_PATH
```

this one makes sense to me, but it also didnt work :/
```
matrix:
- SPEC_PATH=$(echo $FEATURES_1)
- SPEC_PATH=$(echo $FEATURES_2)
```

**Comment by BanzaiMan** [comment]
Ah, you are right. `SPEC_PATH=$(echo $FEATURES_1)` doesn't work, either.

You'll have to set `SPEC_PATH` after `FEATURES_1` is set.

**Comment by BanzaiMan** [comment]
Set up a build matrix with an intermediate environment variable, then based on that, set `$SPEC_PATH` in the script itself.


`.travis.yml`
```yaml
env:
  - GROUP=1
  - GROUP=2
```

`travis.sh`
```bash
⋮
SPEC_PATH= # set this based on $GROUP
bundle exec rspec $SPEC_PATH
```

I'm closing this now.
