### ISSUE TITLE
Build jobs won't start

### ISSUE THREAD

**Issue by HaraldNordgren** [travis-ci/travis-ci#6978]
I can't get my jobs to run. They are infinitely stuck in 'starting'. Canceling and restarting the build does nothing.

Links to builds:
https://travis-ci.org/HaraldNordgren/homebrew-versions
https://travis-ci.org/HaraldNordgren/homebrew-versions-fork

**Comment by BanzaiMan** [comment]
https://travis-ci.org/HaraldNordgren/homebrew-versions/builds
https://travis-ci.org/HaraldNordgren/homebrew-versions-fork/builds
both show completed builds now.

**Comment by HaraldNordgren** [comment]
Yup, both jobs eventually started.

Building seems to take a long time right now. I have been using the service heavily for a few days now and it was not like this on December 4. I am hitting a rate limit?

Or maybe the workload just higher on weekdays. Any way for me to see how many builds are queued before mine?

**Comment by BanzaiMan** [comment]
Currently, our public Mac builds see demand far surpassing the capacity during the US work day. We understand the frustration for long waits, but for now, please bear with us.

We do not provide information about the jobs' positions in the queue at this time.

Thank you.
