### ISSUE TITLE
PHPUnit reports progress with one dot per line

### ISSUE THREAD

**Issue by mlocati** [travis-ci/travis-ci#6979]
I noticed that recently PHPUnit started reporting progress with one dot per line.
It's not an important issue, but that makes reading the log a bit harder.

For instance:
- before: https://travis-ci.org/concrete5/concrete5/jobs/178392806
- after: https://travis-ci.org/concrete5/concrete5/jobs/181618862

Is this a TravisCI issue, a PHPUnit issue or an issue with the integration of the two?

**Comment by mlocati** [comment]
Cross-reference: https://github.com/sebastianbergmann/phpunit/issues/2388

**Comment by BanzaiMan** [comment]
I don't know how you can explain the changes, but, in addition to the different PHPUnit versions, another notable change is the PHP version (7.1.0RC6 to 7.1.0). It  possible that the new 7.1.0 archive has a different PHPUnit configuration file from the one found in the 7.1.0RC6 one. I am not sure where this file is, however. You can compare [the 7.1.0RC6 build](https://travis-ci.org/travis-ci/php-src-builder/builds/178023286) and [the 7.1.0 build](https://travis-ci.org/travis-ci/php-src-builder/builds/181447327).

You can also compare the archives https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/12.04/x86_64/php-7.1.0RC6.tar.bz2 and https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/12.04/x86_64/php-7.1.0.tar.bz2.

Let me know if we can help in any way.

**Comment by mlocati** [comment]
Thanks for the quick feedback.

I don't think that this issue is affected by changes in version of PHPUnit and/or PHP.

For instance, see these two builds:
- Progress shown correctly:  
  date: 2016-11-30T17:26:16Z  
  commit: b0fa09b67d37bc47b6fa801779fde9a634bd18ae  
  https://travis-ci.org/concrete5/concrete5/jobs/180152674
- Progress reported with one dot per line:  
  date: 2016-12-01T17:14:12Z  
  commit: ea3a119922e48ec631c34dcca4a67d5126a2bda1  
  https://travis-ci.org/concrete5/concrete5/jobs/180461325

As you can see, both builds use this environment:
- PHP 7.1.0RC6 (cli) (built: Nov 22 2016 16:43:21) ( ZTS )
- PHPUnit 5.6.5

The [changes](https://github.com/concrete5/concrete5/compare/b0fa09b67d37bc47b6fa801779fde9a634bd18ae...ea3a119922e48ec631c34dcca4a67d5126a2bda1) to our code between those two builds are irrelevant too.

Comparing the raw logs, I see these differences:
- Progress shown correctly:  
  hostname: i-052d2396-precise-production-2-worker-org-docker.travisci.net:3a6dc42f-0197-4140-8bd1-cfb87f7c9f6e  
  version: v2.5.0-8-g19ea9c2 https://github.com/travis-ci/worker/tree/19ea9c20425c78100500c7cc935892b47024922c  
  instance: 6b20ad9:travis:php
- Progress reported with one dot per line:  
  hostname: i-80696678-precise-production-2-worker-org-docker.travisci.net:929cc872-bebb-4bfa-a6ea-e46f0de14242  
  version: v2.5.0-8-g19ea9c2 https://github.com/travis-ci/worker/tree/19ea9c20425c78100500c7cc935892b47024922c  
  instance: 935cbf8:travis:php

Are those details of some help?

**Comment by BanzaiMan** [comment]
I don't think difference in workers is significant, either.

**Comment by mlocati** [comment]
Thanks to a @sebastianbergmann [comment](https://github.com/sebastianbergmann/phpunit/issues/2388#issuecomment-265176966), it seems it's a problem of latest Composer version: see https://github.com/composer/composer/issues/5936 and https://github.com/composer/composer/issues/5933.

Sorry for bothering you and thanks for the support
