### ISSUE TITLE
node_modules/.bin no longer in the default PATH

### ISSUE THREAD

**Issue by bobzoller** [travis-ci/travis-ci#6984]
On our builds running with `{dist: trusty, sudo: required, language: node_js}` we're seeing that `./node_modules/.bin` is no longer in the default `PATH`, where it used to be prior to this morning.

I suspect this is related to the release that just happened for #6928 ?

**Comment by bobzoller** [comment]
PS -- this appears to be a regression so perhaps it should be fixed, but I'm also happy to go forward adding it explicitly to our configs... adding that to your path is somewhat widespread but not part of any official nodejs install flow, AFAIK.

**Comment by BanzaiMan** [comment]
Sorry for the troubles. This was reverted with https://github.com/travis-ci/travis-build/pull/905. Please restart the failing builds.

See https://github.com/travis-ci/travis-ci/issues/5092 for the intent for this removal.

I'm closing this now.

**Comment by bobzoller** [comment]
thanks for the quick turnaround @BanzaiMan
