### ISSUE TITLE
R 3.3.2: tlctk and X11 support not available

### ISSUE THREAD

**Issue by AkhilNairAmey** [travis-ci/travis-ci#6987]
@craigcitro, @hadley and @jimhester

My build is failing due to either a `tcltk` or `X11` issue.  Running the build without the `tcltk` packages installed via `apt-get` gives the error
```
Error: .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/travis/R-bin/lib/R/library/tcltk/libs/tcltk.so':
  libtcl8.5.so.0: cannot open shared object file: No such file or directory
```

I can install the appropriate libraries using
```
addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev
```

But then I get the warning
```
Warning message:
no DISPLAY variable so Tk is not available
```

I thought the issue might be X11 as checking `capabilities` shows `X11` isn't available
```
$ Rscript -e "capabilities()"
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE       FALSE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE       FALSE        TRUE        TRUE        TRUE        TRUE 
```

A similar output in #5637 shows `X11` as true, so I'm presuming it should be enabled.  

I'm not sure what the root issue is, or whether it's my end or not.  Any advice appreciated, thanks.

**Comment by achubaty** [comment]
Are you using the X virtual frame buffer? In my .travis.yml file I have:

```
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
```

**Comment by AkhilNairAmey** [comment]
Thanks @achubaty, this worked perfectly.
