### ISSUE TITLE
Travis shows "master" for non-master branches on home page

### ISSUE THREAD

**Issue by dmcgillen** [travis-ci/travis-ci#6988]
On the home page (which for me is travis-ci.com, I don't know about .org) the latest build or that which is currently running is shown in the main pane. At the top of this, where it shows the branch name followed by the commit message, it always has the branch as "master" even if it is not.

![branch shown as master](https://cloud.githubusercontent.com/assets/3996560/20965622/7defb038-bc6e-11e6-970c-864238169be9.jpeg)

If I click on the build number link it remains. If, however, I click "Pull requests" or "Build history" to find the build, and then open it, it correctly shows the branch or pull request rather than master.

![branch shown as pull request](https://cloud.githubusercontent.com/assets/3996560/20965634/8b9d78fa-bc6e-11e6-83e4-9241467e235c.jpeg)

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here? If you'd rather not discuss this in public, do send us email at support@travis-ci.com. Thanks.

**Comment by dmcgillen** [comment]
Hi. It's a bit hard to do this because it only appears when a PR is the current or latest build and obviously we are constantly pushing / building stuff. Are you able to recreate it?

**Comment by BanzaiMan** [comment]
The PR build belongs to the branch for which the PR was opened, so if the PR is for the `master` branch, then showing `master` is correct here.

**Comment by dmcgillen** [comment]
Thanks for looking at this.

Just had a look at this again myself. I'm definitely not using master and am building a PR built from a branch. Doing a bit of Googling on $TRAVIS_BRANCH reveals, however, "For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be master)", so I guess that explains it.

I'm not sure why this is the desired behaviour though as I find it hard to know on travis at a glance whether we've broken master or if it's just someone's PR they're working on, in which case it's of no interest to anyone but the developer working on it. I also think the bar on the left that shows the status of each repo (my repositories) should only be red/green based on the latest master, not just the last build which could be someone's PR.

**Comment by drogus** [comment]
@dmcgillen thank you for a detailed explanation and sorry for the long time for a fix. I've deployed a fix today and I believe this should not happen anymore. Let me know if it's otherwise.
