### ISSUE TITLE
After 'git push --force', Travis tries to checkout overwritten commit and fails

### ISSUE THREAD

**Issue by HaraldNordgren** [travis-ci/travis-ci#6991]
I use `git push -f` heavily when debugging to cut down on the number of commits. When starting a job I'm getting,

```
$ git checkout -qf dbcfb630247794170b00f010fa6e6c03ea7df61e
fatal: reference is not a tree: dbcfb630247794170b00f010fa6e6c03ea7df61e
```

where the hash belongs to the overwritten commit.

**Comment by BanzaiMan** [comment]
Could you tell us what you expect to happen here? Your push asked to build a commit, and you erased it, so we can no longer build it.

**Comment by AlexChesters** [comment]
This is one of many reasons why overwriting git history is a terrible idea once it has been pushed to an upstream.

**Comment by HaraldNordgren** [comment]
The behavior that I was expecting was for Travis to skip the build and hop to the next one. But at the same I guess for any production system that would not be a very good idea.

1. The slowness of the Mac build queue is a problem. Whenever I'm pushing a lot of changes, I generally only want the latest one to be build. And to have a bunch of outdated build jobs running is just annoying.

2. It was not immidiately obvious to me that Travus was continuously updating from the git repo in the background. Every push queues a new build, and **if I want to build only the latest that I can cancel the previous ones from the Build history tab**.

3. However, I would like to have this feature (https://github.com/travis-ci/travis-ci/issues/5160) implemented. Basically `build_only_latest: true` in the travis yml would be awesome.

I guess this can be closed.

**Comment by BanzaiMan** [comment]
@HaraldNordgren Thanks for the feedback. Those concerns are valid, and they will be addressed separately.

I'm closing this now.
