### ISSUE TITLE
Secure environment variables on csharp build agents

### ISSUE THREAD

**Issue by floydpink** [travis-ci/travis-ci#6993]
Are there known issues with the community supported csharp build-agent?

The build log does seem to suggest that the agent is getting set with all the configured secure environment variables, but further down it is running into an error of not being able to find one of the secure environment variables set on the Travis CI build settings UI.

Here is the log that shows this issue: https://travis-ci.org/flickr-downloadr/flickr-downloadr-gtk/builds/182247869

/cc @joshua-anderson @akoeplinger @nterry

**Comment by BanzaiMan** [comment]
https://travis-ci.org/flickr-downloadr/flickr-downloadr-gtk/builds/182247869#L47-L48 What's in this value? `fg` should not be a token here, so I have to guess that `FLICKR_DOWNLOADR_SHARED_SECRET` contains it, and somehow Bash is interpreting the pieces of it as a command. If your secret has some special characters (` `, `&`, etc.), then it needs to be quoted or escaped correctly. https://docs.travis-ci.com/user/encryption-keys#Note-on-escaping-certain-symbols

**Comment by floydpink** [comment]
Great... I guess that is what is going on here - I will escape the special characters on that variable's value and update the results here.

Thank you, @BanzaiMan !

**Comment by BanzaiMan** [comment]
It appears to be fixed now. https://travis-ci.org/flickr-downloadr/flickr-downloadr-gtk/builds/182468103#L47

I'm closing this.
