### ISSUE TITLE
Carthage copy-frameworks runs forever in xcode8.1 image

### ISSUE THREAD

**Issue by DanielNilssonGithub** [travis-ci/travis-ci#6994]
Hello,
After I switch to xcode8.1 image (from xcode8.0) I’m having problems building my project.
The problem is that "carthage copy-frameworks” script seems to freeze the build.
Works when i run the fastlane script on my local computer.
I have tried to set travis_wait to 60 but with no success.

**Comment by DanielNilssonGithub** [comment]
Duplicate #6791

**Comment by codeOfRobin** [comment]
Hey @DanielNilssonGithub ! I'm having the same issue. Could you detail how exactly you fixed this?

**Comment by DanielNilssonGithub** [comment]
Hello @codeOfRobin I managed to fix the issue by setting the password of the keychain to empty string. There is probably a more elegant solution to this in #6791 but that was good enough for me.
