### ISSUE TITLE
Not printing which cached files changed

### ISSUE THREAD

**Issue by gabrielittner** [travis-ci/travis-ci#6999]
If you take a look at this build there were detected changes but I can't see what changed (in theory it should be identical):
https://travis-ci.org/gabrielittner/auto-value-playground/builds/178903299
```
store build cache
changes detected, packing new archive
.
.
uploading archive
```

Sometimes I'm correctly getting what changed:
https://travis-ci.org/gabrielittner/auto-value-playground/builds/158738809

**Comment by BanzaiMan** [comment]
Might be a regression that we introduced yesterday. Could you try:

```yaml
cache:
  edge: production-2016-05-24
  ⋮ # rest
```

Thanks.

**Comment by gabrielittner** [comment]
I've added the line and now it doesn't detect any changes: https://travis-ci.org/gabrielittner/auto-value-playground/builds/182622063

After removing the line again it goes back to changes detected without any output:
https://travis-ci.org/gabrielittner/auto-value-playground/builds/182625129

**Comment by BanzaiMan** [comment]
Thanks for the confirmation. We'll be rolling back the change Monday.

**Comment by BanzaiMan** [comment]
@gabrielittner Hello. The change has been reverted, and caching should work as before. Could you confirm?

**Comment by gabrielittner** [comment]
Everything seems to be back to working as expected. Thanks for the quick help
