### ISSUE TITLE
Use gtk3

### ISSUE THREAD

**Issue by waghanza** [travis-ci/travis-ci#7000]
Hi,

I'm running an app test on `travis-ci`.

This app **requires** `gtk3`, but I have 

~~~sh
libui : Depends: gtk+3.0 but it is not installable
~~~

Is `gtk3` blacklisted on `travis` ?

Regards,

PS : https://travis-ci.org/waghanza/pylibui

**Comment by BanzaiMan** [comment]
How do you install this on your development machine?

**Comment by waghanza** [comment]
With a **docker**

Sorry, I have a successful reply by mail and forget to close issue

I use `libgtk-3-0` instead of  `gtk3`
