### ISSUE TITLE
travis stuck sync'ing from GITHUB?

### ISSUE THREAD

**Issue by jose-caballero** [travis-ci/travis-ci#7002]
I was going to start with TRAVIS CI. After logging with my GITHUB account I got the confirmation email. However, one day later -more or less-, it is still trying to sync. 
Is this amount of time expected? 
Should I close the window and start over?

Thanks a lot.
Jose

**Comment by BanzaiMan** [comment]
@jose-caballero Sorry about the troubles. Are you trying to use https://travis-ci.org or https://travis-ci.com?

**Comment by jose-caballero** [comment]
no apologies needed.
The URL that says is still sync'ing is  https://travis-ci.org/first_sync

**Comment by BanzaiMan** [comment]
@jose-caballero According to our records, the data finished syncing in 4 seconds. Could you try reloading https://travis-ci.org?

**Comment by jose-caballero** [comment]
OK. After the reload, the web page says it is done. 
Maybe it is a problem with the browser (or the page itself) more than the actual sync process???

Anyways, thanks a lot for such a prompt response. 

Jose

**Comment by BanzaiMan** [comment]
Thanks for the update! Yeah, sounds like updates got messed up at some point.

We are happy to hear that the problem is resolved. Have a wonderful day!

**Comment by ebrohman** [comment]
Same issue here.  Stuck on syncing in the web UI. I tried to force sync with the ruby cli and got:

```
409: "{\"message\":\"Sync already in progress. Try again later.\"}"
```

It's been hours.  Is there any course of action to take @BanzaiMan ?

**Comment by BanzaiMan** [comment]
@ebrohman According to our records, your account has been sync'd at 2017-05-31 19:20:46 UTC (16 minutes ago).
