### ISSUE TITLE
Ubuntu 14.04 vanilla image & dynamic matrix generation

### ISSUE THREAD

**Issue by nbrady-techempower** [travis-ci/travis-ci#7003]
Hi, guys! I'm one of the maintainers of the framework benchmarks (https://github.com/TechEmpower/FrameworkBenchmarks). One issue we're constantly trying to tackle is getting our travis setup to look like the same process as what we'd want our contributors to go through. This way, we can have at least some high level of certainty, that if their pull request fails on travis, they've done something wrong.

Two things that would make life much more grand:
1) Right now I'm in the process of rewriting our travis.yml so that we can look more like a clean ubuntu image. Something someone would see if they booted up vagrant, or a t2.micro on aws. To do this, I'm using 
`sudo: required, dist: trusty, language: generic`, imploding the rvm and removing some other services, replacing the apt sources and then starting work. You can see that here in my fork: https://github.com/nbrady-techempower/FrameworkBenchmarks/blob/travis-magic/.travis.yml

I can't see it in the documentation, but do you guys have a vanilla ubuntu 14.04 image? One that maybe just has git installed with your testing utilities? When things like the apt sources list look different from what someone would spin up in a fresh ubuntu install, packages don't always align. Also, since most of our tests rely on several different database implementations, we are sometimes hitting a pre-installed service we don't want.

2) We have over 180 matrix combinations that need to complete on a full run. Currently we're running a diff and we know which matrix combinations might be affected. However, since we can't generate the matrix dynamically, we have to boot up an instance, find out we don't need this particular test, then exit. If we only need to test 1 item out of 180, we're spending a lot of time and resources  we don't need to. A way to generate the matrix (some sort of before-matrix hook) would be amazing.

I know that 2) is something others have kicked around as well, and it would probably be a significant undertaking, but I think it would definitely be a solid feature and relieve some pressure on a lot of resources.

Thanks for offering a free service to those of us in the open source community and keep up the great work!

**Comment by BanzaiMan** [comment]
Please close this and  split it into two. We cannot discuss these two disparate issues in the same thread.

**Comment by nbrady-techempower** [comment]
@BanzaiMan Thanks.. I normally respond immediately. Have been down and out with the flu.
