### ISSUE TITLE
How do I release *public scoped package* to NPM?

### ISSUE THREAD

**Issue by gin0606** [travis-ci/travis-ci#7005]
I tried to publish a [scoped package](https://docs.npmjs.com/getting-started/scoped-packages) from TravicCI.
However, the following error occurred.
From the CLI I can publish by adding the option `--access=public` to the `npm publish` command, but is it possible to use this option from TravisCI?

I refer to [npm Releasing - Travis CI](https://docs.travis-ci.com/user/deployment/npm/).

# Travis log
https://travis-ci.org/gin0606/react-stateless-input/builds/182785168

```
npm ERR! publish Failed PUT 402
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.1.0/bin/node" "/home/travis/.nvm/versions/node/v6.1.0/bin/npm" "publish"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code E402
npm ERR! You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @gin0606/react-stateless-input
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/gin0606/react-stateless-input/npm-debug.log
```

**Comment by riggerthegeek** [comment]
I'm also trying to do this. I attempted to do this using a deploy.sh script, which also hasn't worked. This failed with no reason given. Any ideas?

# Travis log
[https://travis-ci.org/steeplejack-js/core/jobs/183511163](https://travis-ci.org/steeplejack-js/core/jobs/183511163)

```
dpl.0
Fetching: dpl-1.8.25.gem (100%)
Successfully installed dpl-1.8.25
1 gem installed
dpl.1
Installing deploy dependencies
!!! Script support is experimental !!!
dpl.2
Preparing deploy
dpl.3
Deploying application
Script failed with status 127
failed to deploy
```

# Deploy script

```
printf "%s\n%s\n%s" $NPM_USER $NPM_PASSWORD $NPM_EMAIL | npm login --scope=@steeplejack && npm publish --access public
```

**Comment by phlummox** [comment]
Ugh, I ran into this. I'd forgotten to check permissions on "deploy.sh" - it wasn't executable. Could that be the problem?

**Comment by riggerthegeek** [comment]
Not for me. My permissions are 755, set to GitHub. I shouldn't need to change the permissions in Travis, assuming it respects the permissions like the Git default behaviour

**Comment by riggerthegeek** [comment]
I found the issue with my deploy. It was because my script was just `deploy.sh`. When I set it to `./deploy.sh`, it deployed fine.

**Comment by etki** [comment]
got hit by this as well

**Comment by wmhilton** [comment]
For others Googling "how to travis publish npm scoped package", I found the simplest solution is to add

```
  "publishConfig": {
    "access": "public"
  },
```

to your `package.json` file. I saw it somewhere on Twitter and it worked for me.

**Comment by gin0606** [comment]
@wmhilton 
great! thanks!!

**Comment by wmhilton** [comment]
Ooh, I'm gonna make a PR to the actual "npm Releasing - Travis CI" page.
