### ISSUE TITLE
fixing gfortran with conda

### ISSUE THREAD

**Issue by chivalry123** [travis-ci/travis-ci#7007]
when trying to import a package, i get:

    [me@server ~]$ ipython 
    Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
    Type "copyright", "credits" or "license" for more information.
    
    IPython 5.1.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    In [1]: import cvxopt
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-14abf1b564a4> in <module>()
    ----> 1 import cvxopt
    
    /home/me/.local/lib/python2.7/site-packages/cvxopt/__init__.py in <module>()
         30 # You should have received a copy of the GNU General Public License
         31 
    ---> 32 import cvxopt.base
         33 
         34 def normal(nrows, ncols=1, mean=0.0, std=1.0):
    
    ImportError: /home/me/.local/lib/python2.7/site-packages/cvxopt/base.so: undefined symbol: _gfortran_st_write_done

my environment is set up completely in conda. What should I do? How do I resolve the gfortran thing with conda only?

**Comment by BanzaiMan** [comment]
How does this relate to Travis?
