### ISSUE TITLE
Travis Stuck at Build

### ISSUE THREAD

**Issue by incubus8** [travis-ci/travis-ci#7018]
Hi,

Thanks for great service.

After several times cancelling jobs/tasks, I tried to run it again but it stuck at build here is the repo https://travis-ci.org/incubus8/nodejs-redis-geolocation-demo/jobs/183337822

Any idea? 

Thanks

**Comment by BanzaiMan** [comment]
We apologize, but our Mac builds see more demands than we have capacity for at the moment. Some lag is to be expected right now. Restarting the build is counterproductive, since your build loses the position in the queue.

**Comment by incubus8** [comment]
@BanzaiMan thanks, it works now

**Comment by incubus8** [comment]
@BanzaiMan umm yes, it's happening again.. looks like a long lag

**Comment by BanzaiMan** [comment]
The queue is long during the work day hours (the Americas). Sorry about that.

**Comment by BanzaiMan** [comment]
Thanks for your patience while we work on adding capacity.
