### ISSUE TITLE
� characters in Travis console log

### ISSUE THREAD

**Issue by sormuras** [travis-ci/travis-ci#7024]
Long lines with multi-byte characters printed by a simple shell script:
```bash
#!/bin/bash

for run in {1..1000}
do
  echo " ▓ ✔✔✔✔✔✔✔✔✔✔ a b c d e f  a b c d e f ✔✔✔✔✔✔✔✔✔✔ ▒ "
done
```
are garbled by Travis to:
```
 ▓ ✔✔✔✔✔✔✔✔✔✔ a b c d e f  a b c d e f ✔✔✔✔✔✔✔✔✔✔ ▒ 
 ▓ ✔✔✔✔✔✔✔✔✔✔ a b c d e f  a b c d e f ✔✔✔✔✔✔✔✔✔✔ ▒ 
 ▓ ✔✔���✔✔✔✔✔✔✔ a b c d e f  a b c d e f ✔✔✔✔✔✔✔✔✔✔ ▒ 
 ▓ ✔✔✔✔✔✔✔✔✔✔ a b c d e f  a b c d e f ✔✔✔✔✔✔✔✔✔✔ ▒ 
 ▓ ✔✔✔✔✔✔✔✔✔✔ a b c d e f  a b c d e f ✔✔✔✔✔✔✔✔✔✔ ▒ 
```

Full log (stable-precise) at https://api.travis-ci.org/jobs/183558479/log.txt?deansi=true
This also effects tree-like ascii renderings (stable-trusty) at https://api.travis-ci.org/jobs/180752503/log.txt?deansi=true

```
│  │  │  ├─ input:95 ✔
│  │  │  ├─ input:94 ✔
│  │  │  ���─ input:87 ✔
│  │  │  ├─ input:89 ✔
│  ├─ TimingExtensionTests
│  │  ├─ sleep20ms() ✔
│  │  ├─ sleep50ms() ✔
```

More details and origin of the bug, see https://github.com/gradle/gradle/issues/1008

**Comment by BanzaiMan** [comment]
What are these characters?

**Comment by sormuras** [comment]
They are [REPLACEMENT CHARACTER](http://www.fileformat.info/info/unicode/char/0fffd/index.htm)s.

Gradle under 3.2 had a similar problem, before https://github.com/gradle/gradle/commit/1746300a fix it.

**Comment by sormuras** [comment]
I _**guess**_ that either the [log writer](https://github.com/travis-ci/worker/blob/master/amqp_log_writer.go) in worker or the receiver of the log part is transfering/receiving in byte chunks - which may lead to wrong encoded UTF-8 sequences, when a multi-byte encoded character is split "in half".

**Comment by sormuras** [comment]
Is there a way, I can contribute to fix this issue?

**Comment by sormuras** [comment]
If I'm not mistaken, the REPLACEMENT CHARACTERs do **not** show up when JDK 9 is running the build:

JDK 8 (provided by Travis CI) log with � : https://travis-ci.org/junit-team/junit5/jobs/242940011#L667
JDK 9 (manually installed by .travis.yml) log **without** � : https://travis-ci.org/junit-team/junit5/jobs/242940012#L448

**Comment by sormuras** [comment]
Dear stale bot, the problem still exists.

**Comment by viane** [comment]
My nodejs project also failing on this, except that the actual value is not interpreted correctly at all.
My code looks like this:

```js
for(i=0;i<100;i++){
    console.log(string1, '   ' ,string2)
    if(string1 === string2){
        console.log('match')
    }
}
```

On my local the string is properly interpreted, but in travis, i will have random string1 or string2 thats ��x��x�.

**Comment by viane** [comment]
@sormuras try add `sleep 0.1` in the for loop call

**Comment by protoEvangelion** [comment]
For the life of me I can't figure this out! I'm having the same problem in Node.

Printing out a table works fine on my local Mac machine but continues to print out the replacement character on every Travis run.

Could this be a difference of Ubuntu vs Mac? Or could this be a result of tty or terminal settings that Travis specifies?

**Comment by sormuras** [comment]
> I guess that either the log writer in worker or the receiver of the log part is transfering/receiving in byte chunks - which may lead to wrong encoded UTF-8 sequences, when a multi-byte encoded character is split "in half".

Here https://github.com/travis-ci/worker/blob/master/amqp_log_writer.go are the � characters coming from, methinks.

**Comment by BanzaiMan** [comment]
I'm moving further discussion to https://travis-ci.community/t/characters-in-travis-console-log/2068, which @protoEvangelion opened.

**Comment by protoEvangelion** [comment]
Thanks @BanzaiMan !
