### ISSUE TITLE
Please add support for dotnet 1.0.0-preview5-004232

### ISSUE THREAD

**Issue by rovale** [travis-ci/travis-ci#7026]
Is it possible to add support for [1.0.0-preview5-004232](https://github.com/dotnet/cli#installers-and-binaries)? This version deals with the csproj project format.

Currently the [build ](https://travis-ci.org/rovale/DotnetIntegration/jobs/183649362) fails with the message:

`Unable to locate package dotnet-dev-1.0.0-preview5-004232
Couldn't find any package by regex 'dotnet-dev-1.0.0-preview5-004232'`

 cc @joshua-anderson @akoeplinger @nterry

**Comment by Joshua-Anderson** [comment]
The error message is exactly correct. Microsoft hasn't published a debian package for that version yet.

**Comment by rovale** [comment]
I have been impatient, [build](https://travis-ci.org/rovale/DotnetIntegration/builds/183927956) succeeds now. Not sure if this is the way to go, though.
