### ISSUE TITLE
Request an increase in job limit timeout?

### ISSUE THREAD

**Issue by danielbachhuber** [travis-ci/travis-ci#7027]
Is it possible to request a increase to the job limit timeout for travis-ci.org?

We're hovering at right about 50 minutes, and experience intermittent build failures. See https://github.com/wp-cli/wp-cli/issues/3652 for more background.

The nut of the problem is that our test suite takes too long to complete. Retooling is a non-insignificant amount of effort, so I'm hoping we can mitigate the problem in the short term by getting an increase.

Thanks!

**Comment by MariadeAnton** [comment]
Could you send us this to support@travis-ci.com, we'll look into what we can do to help :)

Thank you, @danielbachhuber!
