### ISSUE TITLE
Adding a version number to the log of a worker

### ISSUE THREAD

**Issue by tonnymadsen** [travis-ci/travis-ci#703]
Would it be possible to add a version number to the log file from a worker? Best at the very top along with the worker name/ID.

The version would be very useful in the cases where ones build job suddenly seems to behave differently than expected. With the version number we can see if we should consider a changed worker a possible source for the changed behavior of the build job or if we should "just" focus on our own sources and environment.

A version tag or a commit id would both be very useful.

**Comment by joshk** [comment]
Closing this issue as it has become stale.

Thank you for creating this.
