### ISSUE TITLE
[bug] Duplicate build numbers assigned different build ids

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/travis-ci#7030]
We're looking into what may be causing this issue.

This comes from @drdanz's report at https://github.com/travis-ci/beta-features/issues/1#issuecomment-266984010. 

See:  https://travis-ci.org/robotology/yarp/builds

![image](https://cloud.githubusercontent.com/assets/3729517/21180230/4b8de396-c1f8-11e6-9f1e-5c8e6d360890.png)

**Comment by MariadeAnton** [comment]
Tracking here another report from twitter: https://twitter.com/mattwigway/status/808771566238633985, happening in https://travis-ci.org/conveyal/r5/builds

**Comment by drdanz** [comment]
I just noticed that *sometimes*, we get the same build id also for pull requests from a branch in the same repository, see for example these 2 `Build #3342`

https://travis-ci.org/robotology/yarp/builds/188477227
https://travis-ci.org/robotology/yarp/builds/188477249

**Comment by MariadeAnton** [comment]
We've fixed this bug and no new duplicates should appear from now on. Thanks for reporting, @drdanz!
