### ISSUE TITLE
Ubuntu 14.04 vanilla image

### ISSUE THREAD

**Issue by nbrady-techempower** [travis-ci/travis-ci#7032]
Hi, guys! I'm one of the maintainers of the framework benchmarks (https://github.com/TechEmpower/FrameworkBenchmarks). One issue we're constantly trying to tackle is getting our travis setup to look like the same process as what we'd want our contributors to go through. This way, we can have at least some high level of certainty, that if their pull request fails on travis, they've done something wrong.

Right now I'm in the process of rewriting our travis.yml so that we can look more like a clean ubuntu image. Something someone would see if they booted up vagrant, or a t2.micro on aws. To do this, I'm using 
`sudo: required, dist: trusty, language: generic`, imploding the rvm and removing some other services, replacing the apt sources and then starting work. You can see that here in my fork: https://github.com/nbrady-techempower/FrameworkBenchmarks/blob/travis-magic/.travis.yml

I can't see it in the documentation, but do you guys have a vanilla ubuntu 14.04 image? One that maybe just has git installed with your testing utilities? When things like the apt sources list look different from what someone would spin up in a fresh ubuntu install, packages don't always align. Also, since most of our tests rely on several different database implementations, we are sometimes hitting a pre-installed service we don't want.

**Comment by jmb1304** [comment]
Have you taken a look at their docker images?
They post them on the documentation here:

[https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image)

It might be able to answer your question.

**Comment by BanzaiMan** [comment]
As suggested, please consider using the plain Ubuntu image for now. Thanks.
