### ISSUE TITLE
mac: error <atomic> is not implemented

### ISSUE THREAD

**Issue by Opticalp** [travis-ci/travis-ci#7038]
Hi, 
Thank you for the great tool!

Since recently, I get this error with clang: 
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:543:2: error: <atomic> is not implemented
```
e.g. line 520: of https://travis-ci.org/Opticalp/instrumentall/jobs/184198006

http://apple.stackexchange.com/questions/217579/compile-error-atomic-is-not-implemented suggests an incompatible mix of versions...

Thank you

**Comment by BanzaiMan** [comment]
Our current default is Xcode 7.3. Is this feature supported on it? https://docs.travis-ci.com/user/osx-ci-environment#OS-X-Version

**Comment by Opticalp** [comment]
Ok, it is not an issue with Travis, but with Poco libs pocoproject/poco#1453

Issued from a SDK version conflict...
Thank you @BanzaiMan for your answer.
