### ISSUE TITLE
The command "npm install" took longer than 10 minutes

### ISSUE THREAD

**Issue by Lazerbeak12345** [travis-ci/travis-ci#7039]
The command usually only takes a minute or two.

Here is the config for [the job that errored](https://travis-ci.org/Lazerbeak12345/AI.js/jobs/184265840):
```
{
  "language": "node_js",
  "node_js": "iojs",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
```

**Comment by Lazerbeak12345** [comment]
btw I tried restarting the build and it worked, but I am still concerned if it will happen again.

**Comment by cotsog** [comment]
Hey @Lazerbeak12345,

It seems this issue is not specific to Travis CI as we have seen other reports on Twitter.

We've reached out to NPM's support and are waiting for a reply. We will update this issue when we know more.

Thank you for your patience.

**Comment by MariadeAnton** [comment]
Seems this is also affecting other services and we're experiencing intermittent network failures. See: http://stspg.io/4YVZ for updates, thanks!

**Comment by cotsog** [comment]
We've been informed by our upstream provider that there was indeed issue earlier today but these should now have been resolved on their side.

Can you try restarting your build(s) and let us know if things are better?

Thanks!

**Comment by Lazerbeak12345** [comment]
@cotsog It is still a bit slower than normal, but it is working. Thank you for your efforts.

**Comment by BanzaiMan** [comment]
Thanks for the confirmation. I'm closing this now, but if you see further problems, do let us know.
