### ISSUE TITLE
Can't kill child process

### ISSUE THREAD

**Issue by vojtajina** [travis-ci/travis-ci#704]
``` javascript
// node.js
var spawn = require('child_process').spawn;
var p = spawn('/usr/bin/firefox', ['http://localhost/']);

setTimeout(function() {
  p.kill();
}, 1000);

p.on('exit', function(code, signal) {
  // will never happen
});
```

**Comment by stelcheck** [comment]
I seem to have a similar issue with https://travis-ci.org/TypeStrong/ts-node/builds/273609445; for what it is worth, switching the default shell used by `node` from `sh` to `/bin/bash` seems to have some impact: https://travis-ci.org/TypeStrong/ts-node/jobs/273612209

Is it possible that Travis does something special with `sh`?

**Comment by AlexWayfer** [comment]
:confused: 

https://travis-ci.org/thomasfl/filewatcher/jobs/298238166

I'm spawning `/home/travis/build/thomasfl/filewatcher/bin/filewatcher` executable via [`Kernel#spawn`](https://ruby-doc.org/core-2.4.2/Kernel.html#method-i-spawn), but it runs that executable through `sh -c` and returning this `sh -c` pid, which ignoring `SIGHUP`, `SIGINT` or `SIGTERM` on it and its child normal `ruby` process.
