### ISSUE TITLE
Non-sudo apt addon fails when install asks question

### ISSUE THREAD

**Issue by jcoffland** [travis-ci/travis-ci#7040]
My build [here](https://travis-ci.org/CauldronDevelopmentLLC/cbang/jobs/184405349) recently stopped working because the apt addon is not handling interactive configuration questions:

```
Configuration file `/etc/mysql/my.cnf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** my.cnf (Y/I/N/O/D/Z) [default=N] ? 
```
This happens despite these lines in the log output:

```
Installing APT Packages (BETA)
$ export DEBIAN_FRONTEND=noninteractive
5.22s$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install scons libbz2-dev zlib1g-dev libexpat1-dev libssl-dev libboost-iostreams-dev libboost-system-dev libboost-filesystem-dev libboost-regex-dev libsqlite3-dev libv8-dev binutils-dev libmariadbclient-dev
```

Note that ``DEBIAN_FRONTEND=noninteractive`` and ``-y`` is being passed to ``apt-get``.

[This stackoverflow post](http://stackoverflow.com/questions/22957939/how-to-answer-an-apt-get-configuration-change-prompt-on-travis-ci-in-this-case) suggests adding ``-o Dpkg::Options::="--force-confnew"`` to the ``apt-get`` command line.

**Comment by BanzaiMan** [comment]
The `apt` addon is designed for the simplest of use cases. At this time, I'd you need additional control for the `apt-get` command, please use `sudo`.

**Comment by jcoffland** [comment]
Isn't installing a whitelisted package the simplest of use cases?

**Comment by BanzaiMan** [comment]
With no special arguments, yes.

**Comment by jcoffland** [comment]
Right but these special arguments could be needed for any package in non-interactive mode.

**Comment by BanzaiMan** [comment]
For these arguments, please use `sudo apt-get`.

**Comment by jcoffland** [comment]
I'll try that but I'm betting I'm not the only one with this problem.  It's really difficult to use non-sudo mode for anything but the most simplistic projects.  I've tried several times but there's always something that makes it not work.  This was my only project where it succeeded.  And now...

**Comment by BanzaiMan** [comment]
Please try it. I'm closing this now, since this is documented in

https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon

----

## Installing Packages with the APT Addon

You can also use the APT addon.

This addon provides declarative shortcuts to basic operations of the apt-get commands.

If your requirements goes beyond the normal installation, please use another method described above.
