### ISSUE TITLE
Docker login: unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by remojansen** [travis-ci/travis-ci#7042]
# Summary
I'm unable to use the `$ docker login` command. I get the following error:

> Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

# Sample log
https://travis-ci.org/redux-bootstrap/redux-bootstrap-example/builds/184421990#L2348

# [.travis.yml](https://github.com/redux-bootstrap/redux-bootstrap-example/blob/master/.travis.yml)
```
sudo: required

language: node_js

services:
  - docker

node_js:
  - stable

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run release;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t remojansen/redux-bootstrap-example .;
    docker push remojansen/redux-bootstrap-example;
    fi
```

**Comment by BanzaiMan** [comment]
Does your user name or password contain special characters? If they do, they need to be escaped properly to have it correctly set during the build.

**Comment by remojansen** [comment]
👍 thanks for that! the problem was a special character 😄

**Comment by kiulkiel** [comment]
New password just put in. should be good to go.

**Comment by gabrieledarrigo** [comment]
@BanzaiMan Is it possible to escape using env variables from repository settings?
If yes, how?

**Comment by BigstickCarpet** [comment]
In addition to escaping special characters, it also seems that the username must be all lowercase.  Just to help-out anybody else who was stuck on this like I was
