### ISSUE TITLE
openjdk-8-jre not installable

### ISSUE THREAD

**Issue by phadej** [travis-ci/travis-ci#7046]
Todays' builds started to fail with:

```
E: Package 'openjdk-jre' has no installation candidate
```

Example build: https://travis-ci.org/scrive/log/builds/184534064

**Comment by BanzaiMan** [comment]
What source is supposed to provide it?

**Comment by phadej** [comment]
For 16.04 it comes from official repositories, dunno where from it came in previous builds of that repository.

**Comment by phadej** [comment]
Ah, I see, https://travis-ci.org/scrive/log/jobs/177947226, they were disallowed but build was just continuing, so stuff just worked... Weird.

**Comment by BanzaiMan** [comment]
I can't find it in the official repository. http://packages.ubuntu.com/search?keywords=openjdk-jre&searchon=names&suite=xenial&section=all

Can we close this?

**Comment by phadej** [comment]
Sorry, it was about `openjdk-8-jre` package. Which seems to be only in `xenial`. Is there an issue to provide container infrastructure based on xenial images?

**Comment by BanzaiMan** [comment]
Xenial will eventually come, but it will take a bit of time. Sorry. See https://github.com/travis-ci/travis-ci/issues/5821.

**Comment by phadej** [comment]
It's unfortunate that issue is closed, as the task is (hopefully) somewhere on the backlog and not resolved. But anyway, I'm closing this.
