### ISSUE TITLE
Build badges only displays unknown but there are passing builds

### ISSUE THREAD

**Issue by lostatseajoshua** [travis-ci/travis-ci#7049]
I have 4 Travis CI repos and almost all the badges are displaying unknown builds regardless of tests and builds on Pull Requests it shows in the build history. Also on the badge dropdown to change the branch, it only shows the `master` branch. Only one of the badges actually even works. Is there something in the travis.yml needed for it to work? I have also re-synced my repos and tired disconnecting them and reconnecting, it didn't change the outcome.

**Comment by BanzaiMan** [comment]
In all cases with "unknown" status, there are no passing push builds.

**Comment by lostatseajoshua** [comment]
@BanzaiMan can you elaborate on what that means. I have builds that ran and passed on PRs from branches that were pushed. In each repo I keep a develop branch and that doesn't show up in the list of branches.

**Comment by lostatseajoshua** [comment]
@BanzaiMan here is a screenshot of passing builds
<img width="949" alt="screen shot 2016-12-16 at 8 03 48 pm" src="https://cloud.githubusercontent.com/assets/8551292/21283962/d1c26300-c3ca-11e6-9dc6-c4cc4b6441e3.png">

**Comment by lostatseajoshua** [comment]
@BanzaiMan moving to circle ci so don't worry about it.
