### ISSUE TITLE
Job stuck and uncancellable

### ISSUE THREAD

**Issue by Ullaakut** [travis-ci/travis-ci#7050]
Hi!

I'm hunting a random and very rare bug on the functional tests for my repo, which is why I was relaunching the same job all the time yesterday. The issue finally appeared, I fixed it, pushed the fixed code and this morning I just discovered that the build job is **stuck**, even though it's saying that the build is done and exited.

<img width="236" alt="screen shot 2016-12-17 at 11 05 50" src="https://cloud.githubusercontent.com/assets/6976628/21286018/d20c651c-c448-11e6-91e1-8c7dacd858cb.png">

<img width="1517" alt="screen shot 2016-12-17 at 11 08 08" src="https://cloud.githubusercontent.com/assets/6976628/21286026/233240e2-c449-11e6-865d-01a41a9cb993.png">

When I try to cancel it, I get an error message like such :

<img width="326" alt="screen shot 2016-12-17 at 11 05 56" src="https://cloud.githubusercontent.com/assets/6976628/21286019/d20faea2-c448-11e6-9910-af8e0e223a1d.png">

Can this be because of the succession of the ~50 times I restarted a job yesterday, or is it just a very rare bug?

If someone knows a way to _force-cancel_, I'd appreciate it very much!

[Here is the build URL](https://travis-ci.org/EtixLabs/cameradar/jobs/184651430)

**Comment by BanzaiMan** [comment]
The page shows that the job has passed.

**Comment by Ullaakut** [comment]
Right, now I see it done and finished in 15mns as expected. Still no idea why this morning it was showing as running for 9+ hours though, and I tried refreshing the page and cleaning the cache before opening the issue, so there definitely was a problem.

**Comment by BanzaiMan** [comment]
Sometimes the updates get out of sync on the page. I suspect a reload would have shown you the current status of the job. This also explains the error you saw; the job had finished, so you could not cancel it.

**Comment by Ullaakut** [comment]
What do you call a reload? Refreshing the page? If so, I did it, as stated in my previous comment :)

**Comment by BanzaiMan** [comment]
Did you force reload?

**Comment by Ullaakut** [comment]
I used `CMD`+`MAJ`+`R`

**Comment by BanzaiMan** [comment]
What's `MAJ`?

**Comment by Ullaakut** [comment]
Right sorry, french key names, haha. I meant uppercase.

**Comment by BanzaiMan** [comment]
Hmm. That is strange. In my previous encounters with this issue, forcing reload fixed it.

**Comment by Ullaakut** [comment]
Well I'll tell you & make a video sample if I ever encounter this issue again. Thanks for the quick answers! :)

**Comment by BanzaiMan** [comment]
Sounds great. Thank you for reporting. I'll close this issue in the mean time.
