### ISSUE TITLE
Running Travis CLI from it's directory

### ISSUE THREAD

**Issue by jmb1304** [travis-ci/travis-ci#7051]
There is another program on apt-get actually called Travis and Ubuntu 14.04 suggested that I installed it while I was frustratingly trying to follow the directions to install the CLI client. Obviously, it wasn't actually the Travis I wanted and I quickly uninstalled it. When it uninstalled it didn't remove it's entry from the path file and now I can't run Travis because whenever I run
`travis version`
it doesn't run, it just says:
`bash: /usr/bin/travis: No such file or directory`
Please tell me how I can run Travis without the path file / run Travis from the directory it gets installed to.

**Comment by BanzaiMan** [comment]
This is an Ubuntu issue. Please ask your question at more appropriate channel. https://askubuntu.com/ or https://stackoverflow.com/.
