### ISSUE TITLE
Setting the path of Travis database for run the tests

### ISSUE THREAD

**Issue by giancarloandroid** [travis-ci/travis-ci#7054]
**Problem description**

I have an [open source project](https://github.com/PeopleOnMap/people-on-map-site) that use Maven with Java and were defined some variables for the database connection.

> clean spring-boot:run -DJDBC_DATABASE_URL=jdbc:postgresql://localhost/peopleonmap -DJDBC_DATABASE_USERNAME=YOUR_USER -DJDBC_DATABASE_PASSWORD=YOUR_PASSWORD -DSERVER_PORT=YOUR_FAVORITE_PORT

However when I run the tests with [Travis CI (click here to the log)](https://travis-ci.org/PeopleOnMap/people-on-map-site) the connection with the Travis CI database test isn't found and the tests fail. I want to know how I can fix it.

Other detail is that I use `Heroku` and for the connection database I did read in the documentation that is need set the property `spring.datasource.url` in the `application.properties` like this:

> spring.datasource.url=${JDBC_DATABASE_URL}

If have an option to remove the read of `dataSource` during the tests I also considere valid, but I think that is cool and interesting run the tests with a database for the tests in Travis CI.

**Expected result**

Pass in the build and connect in the Travis database test.

**Related links**

[Stackoverflow - Setting the path of Travis database for run the tests](http://stackoverflow.com/q/41208804/4725255)

[GitHub - people-on-map-site - open source project](https://github.com/PeopleOnMap/people-on-map-site)

[Travis - people-on-map-site](https://travis-ci.org/PeopleOnMap/people-on-map-site)

**Comment by BanzaiMan** [comment]
How are you creating the database `peopleonmap`? Is it created during `mvn clean test`?

**Comment by giancarloandroid** [comment]
Thank you. I fixed the `.travis.yml` file, maybe I forgot some settings. The database is created from `.travis.yml` file, but in the last commit I removed some properties.
