### ISSUE TITLE
GCC 4.6 doesn't recognize the -std=c11 switch...

### ISSUE THREAD

**Issue by bumblebritches57** [travis-ci/travis-ci#7057]
this version of C is 5 years old, and your default compiler can't even support it...

I'm good, I build on a Mac, and frankly couldn't care less about anything the communist GPL has infected.

and clang doesn't work at all...

Clang does work, it just takes 20 minutes to compile 75kb of C...

**Comment by BanzaiMan** [comment]
Indeed, that option is not valid with GCC 4.6. http://stackoverflow.com/a/16256596/136333

If you want this flag supported in GCC 4.6, please ask GCC maintainers to add it. Even when it is added, it may take a while for the new package to be available on Precise (if ever).

**Comment by bumblebritches57** [comment]
Lol idgaf about gcc.
