### ISSUE TITLE
ERROR:  could not access file "$libdir/postgis-2.3": No such file or directory

### ISSUE THREAD

**Issue by esdras1976** [travis-ci/travis-ci#7059]
instalando en windows 8, postgis-bundle-pg96x64-setup-2.3.1-1, aparece el error y no me deja crear las extensiones

**Comment by BanzaiMan** [comment]
According to Google Translate, you asked:

> Installing on windows 8, postgis-bundle-pg96x64-setup-2.3.1-1, error appears and will not let me create the extensions

We don't support local installation, and we don't support testing on Windows.
