### ISSUE TITLE
Travis deploy failing

### ISSUE THREAD

**Issue by cocodevienne** [travis-ci/travis-ci#7061]
Guys why is my Travis deploy not working for my Python CLI app? Everytime I update and make anew version, it isn't automagically deployed to PyPi. 

My repos: 
=======
- https://github.com/cocodevienne/curl
- https://github.com/cocodevienne/pitspy
- https://github.com/cocodevienne/cocolangapi

**Comment by BanzaiMan** [comment]
https://github.com/cocodevienne/curl/blob/master/.travis.yml doesn't define any deployment.


I see deployment triggered in the other two. https://travis-ci.org/cocodevienne/pitspy/jobs/185256703#L153 https://travis-ci.org/cocodevienne/cocolangapi/jobs/185277806#L154

https://travis-ci.org/cocodevienne/cocolangapi/jobs/185277806#L307 indicates your credentials are wrong.

**Comment by cocodevienne** [comment]
But I typed my PyPi username and use travis encrypt deploy.password -r cocodevienne/reponamme for each of the passwords...
Whats missing or what am I getting wrong? @BanzaiMan

**Comment by BanzaiMan** [comment]
Is your password actually `deploy.passeord`?

**Comment by cocodevienne** [comment]
Uhm, it says in your docs one should type that command....
@BanzaiMan

**Comment by BanzaiMan** [comment]
@cocodevienne Command in the document is `travis encrypt --add deploy.password`. https://docs.travis-ci.com/user/deployment/pypi

**Comment by cocodevienne** [comment]
Yes but that command doesn't work, now I encrypted again and my credentials are right but travis isn't deploying! Helpme fix this instead of suggesting things I already tried! Thank you! I do not mean to be rude but thsi is really annoying! @BanzaiMan

**Comment by BanzaiMan** [comment]
@cocodevienne I understand that you are frustrated, but the information you have given me has been unreliable at best. If `user.password` is not your actual password with PyPI, your deployment will fail.

> Yes but that command doesn't work

How does it not work? It will ask you to enter the password on STDIN, and it will encrypt what is put in. Did you put in your actual password, or did you write `user.password`?

**Comment by cocodevienne** [comment]
See I downloaded the repo onto my pc, opened up a command prompt inside the repo dir and typed "travis encrypt --add deploy.password" and then it says I should press ctrl+d when done. now I type my password and then press control d or control z and nothing happens. Whats going on? :// @BanzaiMan

**Comment by BanzaiMan** [comment]
Try giving the password on the command line:

```
travis encrypt --add deploy.password YOUR_ACTUAL_PYPI_PASSWORD
```

You may need to escape certain special characters in `YOUR_ACTUAL_PYPI_PASSWORD`, but I don't know what they are on Windows Command Prompt, since I don't use it.

**Comment by cocodevienne** [comment]
Issue solved, but I dunno you should maybe be more explicit in your docs. Just sayin'. Could be very confusing for a newbie. Thanks anyway. @BanzaiMan
