### ISSUE TITLE
Inconsistent behaviour of accessing localhost on Travis (localhost is hijacked)

### ISSUE THREAD

**Issue by thyrlian** [travis-ci/travis-ci#7069]
Project: https://travis-ci.org/thyrlian/SonarOnDocker

On December 5th 2016, the build ([#70](https://travis-ci.org/thyrlian/SonarOnDocker/builds/181464863)) status was fine.  But on December 21st 2016, the build ([#73](https://travis-ci.org/thyrlian/SonarOnDocker/builds/185915241)) failed.  And actually in between there was no real change from my side (just modified the git clone url in Travis config file).

It's all about to test accessing localhost, to see if the status code is 200 or not.  (In my [`docker-compose`](https://github.com/thyrlian/SonarOnDocker/blob/master/docker-compose.yml#L7), I've already set ports with "9000:9000")
```console
curl -s -w "%{http_code}\\n" "http://localhost:9000/" -o /dev/null | grep "200" &> /dev/null
```

**[Before](https://travis-ci.org/thyrlian/SonarOnDocker/builds/181464863#L3430)**: The command exited with 0, which means the status code was 200.

**[Now](https://travis-ci.org/thyrlian/SonarOnDocker#L3546)**: The command exited with 1.  And when I try to print the complete information of the `curl` by using `curl -v "http://localhost:9000/"` or `curl -v "http://127.0.0.1:9000/"`, it simply shows 302 Found with redirection:
```console
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:9000
> Accept: */*
> 
< HTTP/1.1 302 Found
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Cache-Control: no-cache
< Location: http://127.0.0.1:9000/about
< X-Runtime: 11
< Content-Type: text/html;charset=utf-8
< Content-Length: 93
< Date: Wed, 21 Dec 2016 22:32:29 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
<html><body>You are being <a href="http://127.0.0.1:9000/about">redirected</a>.</body></html>
```

I wonder if you guys have changed something with the localhost, and serve something there?  The build was perfect locally and also on Travis side, but only started to fail from yesterday.  Thanks in advance.

**Comment by BanzaiMan** [comment]
OK, so your process listening on port 9000 is now redirecting instead of serving 200. What is the process? We don't run that process, so we can't advise you what might have changed. If you create a new branch off https://github.com/thyrlian/SonarOnDocker/commit/839214b9f285d1da706b740ba8a2315b356f948e and run a build today, does it pass or fail? 

If the process is redirecting, maybe your `curl` command should follow.

**Comment by thyrlian** [comment]
Thanks @BanzaiMan for helping.

Yes it's strange.  I just re-ran the build today, and it still failed - same stacktrace.

BTW, when I
* run the same commands (including `curl`) locally, the IP and port binding (127.0.0.1:9000) is correct (and used to be no problem with Travis).
* created a test repository on GitHub, which does nothing but just try to `curl -v 127.0.0.1:9000`, and turns out there Travis doesn't have any process listen to it.

**Comment by thyrlian** [comment]
The process here I'm running is SonarQube from docker (listening to port 9000).  Good point, though I haven't changed any line of code from my side, but the `docker-compose` uses always the latest SonarQube image, it might be something has been changed there.  Now I'm trying to pull the latest image locally to see what `curl` would return.

**Comment by BanzaiMan** [comment]
I am not asking you to re-run the failing build. I am asking you to create a branch off the passing build (so that the log is preserved), and observe the result.

**Comment by thyrlian** [comment]
Thanks @BanzaiMan just figured out the problem - SonarQube has changed their webpage routing indeed.  It's my bad, I should have thought about that.
