### ISSUE TITLE
rvm: 2.4 installation fails

### ISSUE THREAD

**Issue by segiddins** [travis-ci/travis-ci#7077]
Ruby 2.4 was released within the past few hours, this probably necessitates updating RVM?

```
$ rvm use 2.4 --install --binary --fuzzy

ruby-2.4 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-2.4 do rvm gemset create ' first, or append '--create'.

The command "rvm use 2.4 --install --binary --fuzzy" failed and exited with 2 during .
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
https://travis-ci.org/bundler/bundler/builds/186642571

**Comment by segiddins** [comment]
https://travis-ci.org/bundler/bundler/jobs/186642572

**Comment by BanzaiMan** [comment]
Please try `2.4.0`.

**Comment by segiddins** [comment]
But that wont automatically update when 2.4.1, etc are released, like `2.1` and `2.2` do

**Comment by BanzaiMan** [comment]
I don't think `2.1` or `2.2` work that way, either. For example, `2.2` points to [`2.2.5` at the moment](https://travis-ci.org/bundler/bundler/jobs/186642576#L150), though the latest version is 2.2.6. Similarly for [`2.1`](https://travis-ci.org/bundler/bundler/jobs/186642578#L170).

**Comment by BanzaiMan** [comment]
In other words, MAJOR.MINOR is an alias defined for the runtimes pre-installed on the build image. As such, `2.4` will not work until a version of 2.4.x is pre-installed. This will come in time, but until then, `.0` is necessary.

**Comment by segiddins** [comment]
Ah thanks, I thought it worked the same way as `chruby` (where I obviously have all the versions installed locally).

**Comment by jrochkind** [comment]
It would be awesome if there were some way to tell travis "use the latest 2.4.x".
