### ISSUE TITLE
Ada Development Stack Seems to be Missing

### ISSUE THREAD

**Issue by martinvahi** [travis-ci/travis-ci#7081]
In addition to the various gnat tools it should contain the 
[gprbuild](http://www.adacore.com/gnatpro/toolsuite/gprbuild/).

**Comment by BanzaiMan** [comment]
Did we provide support for this in the past?

**Comment by onox** [comment]
It seems the various `gnat-*` and `libgnat-*` packages are not in the APT package whitelist for Trusty.

Do I need to create a new issue for each package (`gnat`, `gnat-6`, `gnat-6-doc`, `gnat-6-sjlj`, `libgnat-6`, `libgnat-6-dbg`, `libgnatprj6`, `libgnatprj6-dbg`, and `libgnatprj6-dev`) or is just requesting `gnat` sufficient? (if it automatically whitelists dependencies)

**Comment by BanzaiMan** [comment]
If these are `apt` packages that need to be added to the list, please follow the directions in https://github.com/travis-ci/apt-package-whitelist#package-approval-process

I'm closing this issue in the mean time.
