### ISSUE TITLE
Travis doesn't wait for Packer to terminate amazon-ebs builds when I cancel a build

### ISSUE THREAD

**Issue by davidvuong** [travis-ci/travis-ci#7082]
Here's a snippet of my Packer config (but I believe it applies to any amazon-ebs builder):

```
{
  ...
  "builders": [{
    "type": "amazon-ebs",
    "ami_name": "xxx{{timestamp}}",
    "instance_type": "xxx",
    "region": "us-east-1",
    "source_ami": "xxx",
    "ssh_username": "xxx",
    "access_key": "{{user `AWS_SECRET_KEY`}}",
    "secret_key": "{{user `AWS_ACCESS_KEY`}}"
  }],
 ...
}
```

If I press "Cancel build", Travis doesn't wait for Packer to terminate the EC2 box before ending the build. This causes boxes to linger around even though the build has ended. Sometimes we need expensive boxes to build e.g. g2.2xlarge and we don't notice it until later.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by davidvuong** [comment]
I'd be happy to share the URL but the build project is private and I'd rather not post that publicly. Is there direct support for private repos?

**Comment by BanzaiMan** [comment]
Please email us at support@travis-ci.com, then. I'm closing this now.
