### ISSUE TITLE
Docker job treated as a ruby job, fails.

### ISSUE THREAD

**Issue by Khalian** [travis-ci/travis-ci#7083]
https://travis-ci.org/Khalian/docker-swift/builds/187139304

$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

Which is weird because I do not have a single line of ruby in here. I am just trying to build a docker image, thats it.

**Comment by BanzaiMan** [comment]
Your build doesn't have the `language` key defined, so it is treated as a Ruby build.

Could you explain what you expected to happen?

Note: This should be clearly explained somewhere in the docs; for example, in https://docs.travis-ci.com/user/getting-started.

**Comment by Khalian** [comment]
My expectation is that a docker image should build successfully (and thats it). There is no language specific build that is expected. 

I used shippable instead of travis for my use case.

**Comment by BanzaiMan** [comment]
If you are still interested, you can use `language: generic` to achieve what you want.
