### ISSUE TITLE
No output has been received in the last 10m0s in some versions of Node.js

### ISSUE THREAD

**Issue by remojansen** [travis-ci/travis-ci#7084]
I'm having issues with one of my builds in some of the Node.js versions: 

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build details can be found [here](https://travis-ci.org/inversify/InversifyJS).

**Comment by BanzaiMan** [comment]
Looks like legitimate hangs to me. These don't occur on your machine? Try reproducing it with our Node.js image: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

**Comment by remojansen** [comment]
Using Node.js `v6.5.0` on my machine works fine. I'm going to close the issue because it seems to be failing as well in AppVeyor:

```
> gulp default
FATAL ERROR: Malloced operator new Allocation failed - process out of memory
npm ERR! Windows_NT 6.3.9600
```

It must be an issue with one of the packages I have updated.
