### ISSUE TITLE
[community:r] Increase time before timeout when checking/testing

### ISSUE THREAD

**Issue by lgatto** [travis-ci/travis-ci#7086]
Dear  @craigcitro and @jimhester,

My `MSnbase` package takes quite a bit of time to build/check, especially not that I (temporarily hopefully) [disabled parallel processing](https://github.com/travis-ci/travis-ci/issues/7052) on travis. 

I currently get a [timeout](https://travis-ci.org/lgatto/MSnbase#L7099-L7109) using my package checking.

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

How can I use `travis_wait` to extend the time without output when the package is checked, or more specifically when the unit tests are run?

Thanks in advance!

**Comment by jimhester** [comment]
https://github.com/travis-ci/travis-ci/issues/3849#issuecomment-255096774
