### ISSUE TITLE
Cancel Builds from Build History view

### ISSUE THREAD

**Issue by nbrady-techempower** [travis-ci/travis-ci#7087]
Sometimes I have a list of builds that I need to cancel. It would be helpful if you could cancel them all from the list views, like from the Build History view like:

![snippet](http://oi65.tinypic.com/25arygj.jpg)

**Comment by backspace** [comment]
Hello, @nbrady-techempower, thanks for the suggestion! We did end up implementing something like this. Let us know what you think!

**Comment by nbrady-techempower** [comment]
@backspace This is exactly what I was looking for! Thank you!

**Comment by backspace** [comment]
Excellent! You’re welcome, I’m glad it’s useful for you.
