### ISSUE TITLE
Unable to connect to couchdb on OSX environment (localhost:5984 connection refused)

### ISSUE THREAD

**Issue by scottohara** [travis-ci/travis-ci#7088]
I'm using `brew install couchdb` in an OSX build, and then running `couchdb -b` to start the service as a background process.

The service appears to successfully start (logs display the message `Apache CouchDB has started, time to relax.`); however, when I try to connect to `http://localhost:5984/` I am getting a `Connection refused` error.

Also tried `http://127.0.0.1:5984/` with the same result.

Am I doing something wrong?

Relevant commands from `.travis.yml` (rest removed for brevity):

```yaml
os: osx
osx_image: xcode8.2

before_install:
  - brew update
  - brew install couchdb         # Install couchdb
  - couchdb -b                   # Run couch as a background process

before_script:
  - curl http://localhost:5984/  # Quick test to see that couchdb is running
```

Build log:

```
$ brew install couchdb
==> Installing dependencies for couchdb: nspr, spidermonkey, icu4c, wxmac, erlang
==> Installing couchdb dependency: nspr
==> Downloading https://homebrew.bintray.com/bottles/nspr-4.13.1.sierra.bottle.1
==> Pouring nspr-4.13.1.sierra.bottle.1.tar.gz
  /usr/local/Cellar/nspr/4.13.1: 92 files, 1.1M
==> Installing couchdb dependency: spidermonkey
==> Downloading https://homebrew.bintray.com/bottles/spidermonkey-1.8.5_2.sierra
==> Pouring spidermonkey-1.8.5_2.sierra.bottle.tar.gz
  /usr/local/Cellar/spidermonkey/1.8.5_2: 103 files, 10.4M
==> Installing couchdb dependency: icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-58.2.sierra.bottle.ta
==> Pouring icu4c-58.2.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

macOS provides libicucore.dylib (but nothing else).

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include
    PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig

==> Summary
  /usr/local/Cellar/icu4c/58.2: 242 files, 65M
==> Installing couchdb dependency: wxmac
==> Downloading https://homebrew.bintray.com/bottles/wxmac-3.0.2_4.sierra.bottle
==> Pouring wxmac-3.0.2_4.sierra.bottle.tar.gz
  /usr/local/Cellar/wxmac/3.0.2_4: 810 files, 24.6M
==> Installing couchdb dependency: erlang
==> Downloading https://homebrew.bintray.com/bottles/erlang-19.2.sierra.bottle.t
==> Pouring erlang-19.2.sierra.bottle.tar.gz
==> Caveats
Man pages can be found in:
  /usr/local/opt/erlang/lib/erlang/man

Access them with `erl -man`, or add this directory to MANPATH.
==> Summary
  /usr/local/Cellar/erlang/19.2: 7,310 files, 280.9M
==> Installing couchdb 
==> Downloading https://homebrew.bintray.com/bottles/couchdb-1.6.1_8.sierra.bott
==> Pouring couchdb-1.6.1_8.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
To test CouchDB run:
    curl http://127.0.0.1:5984/
The reply should look like:
    {"couchdb":"Welcome","uuid":"....","version":"1.6.1","vendor":{"version":"1.6.1-1","name":"Homebrew"}}

To have launchd start couchdb now and restart at login:
  brew services start couchdb
Or, if you don't want/need a background service you can just run:
  couchdb
==> Summary
  /usr/local/Cellar/couchdb/1.6.1_8: 639 files, 15.0M
```
```
$ couchdb -b
Apache CouchDB has started, time to relax.
```
```
$ curl http://localhost:5984/
curl: (7) Failed to connect to localhost port 5984: Connection refused

The command "curl http://localhost:5984/" failed and exited with 7 during .

Your build has been stopped.
/Users/travis/build.sh: line 148: shell_session_update: command not found
```

**Comment by BanzaiMan** [comment]
I seem to remember CouchDB misleading when it writes

`Apache CouchDB has started, time to relax.`

but it is not accepting connections.

Try sleeping a little before attempting to connect. Either a fixed time (say 10 seconds), or check the port is open:

```bash
until ruby -rsocket -e "TCPSocket.new('localhost',5984)"; do sleep 1; done
```

**Comment by scottohara** [comment]
Thanks for the suggestion @BanzaiMan.

I've tried a few more things, but with no success.  Here's what I've tried:

### 1. Wait until port 5984 is open
##### Change:
Add `until ruby -rsocket -e "TCPSocket.new('localhost',5984)"; do sleep 1; done` before attempting to access CouchDB.

```yaml
before_script:
  - until ruby -rsocket -e "TCPSocket.new('localhost',5984)"; do sleep 1; done
  - curl http://localhost:5984/
```

##### Result:
Build never completes. Endlessly keeps checking the port and getting 'Connection refused'

```
-e:1:in `initialize': Connection refused - connect(2) for "localhost" port 5984 (Errno::ECONNREFUSED)
	from -e:1:in `new'
	from -e:1:in `<main>'
```

##### Example build log:
https://travis-ci.org/scottohara/tvmanager/builds/187563454#L952

### 2. Check the status of the background CouchDB process
##### Change:
After starting couch (`couchdb -b`), check the process status with `couchdb -s`

```yaml
before_install:
  - brew update
  - brew install couchdb                # Install couchdb
  - couchdb -b                          # Run couch as a background process
  - couchdb -s                          # Check status
```

##### Result:
Build fails.  Just as you suspected, CouchDB is indeed misleading when it says `Apache CouchDB has started, time to relax.`.

The `couchdb -s` command reports `Apache CouchDB is not running.` (and returns a non-zero status, causing the build to stop.

```
$ couchdb -s
Apache CouchDB is not running.

The command "couchdb -s" failed and exited with 1 during .
```

##### Example build log:
https://travis-ci.org/scottohara/tvmanager/builds/187565658#L274

### 3. Check the contents of `couchdb.std{out,err}`
##### Change:
After starting couch, `cat` the 2 x files that CouchDB creates for `stdout`/`stderr`

```yaml
before_install:
  - brew update
  - brew install couchdb                # Install couchdb
  - couchdb -b                          # Run couch as a background process
  - cat couchdb.stdout                  # Check stdout
  - cat couchdb.stderr                  # Check stderr
```

##### Result:
Build fails.  Both files are empty, so they provide no clues as to why couch isn't running.  The build proceeds and ultimately fails at the `curl` command that tries to access couch.

```
$ cat couchdb.stdout

$ cat couchdb.stderr

$ curl http://localhost:5984/
curl: (7) Failed to connect to localhost port 5984: Connection refused

The command "curl http://localhost:5984/" failed and exited with 7 during .

Your build has been stopped.
```

##### Example build log:
https://travis-ci.org/scottohara/tvmanager/builds/187570959#L275


At this point, I'm not really sure what else to check?

**Comment by BanzaiMan** [comment]
The only logical conclusion is that CouchDB is not starting up.

The default install of CouchDB on Homebrew appears incomplete.

If you start `couchdb` by itself instead of sending it to the background with `-b`, it [fails](https://travis-ci.org/BanzaiMan/travis_production_test/builds/187625258#L523) with the following:

```sh-session
{"init terminating in do_boot",{{badmatch,{error,{bad_return,{{couch_app,start,[normal,["/usr/local/etc/couchdb/default.ini","/usr/local/etc/couchdb/local.ini"]]},{'EXIT',{{badmatch,{error,{error,enoent}}},[{couch_server_sup,start_server,1,[{file,"couch_server_sup.erl"},{line,56}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}}},[{couch,start,0,[{file,"couch.erl"},{line,18}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
```

I think it is supposed to look for configuration files in `/usr/local/etc/couchdb`, but that directory [does not exist](https://travis-ci.org/BanzaiMan/travis_production_test/builds/187625258#L517-L518).

Ultimately, I think this is an issue with Homebrew's CouchDB packaging, and I advise you to consult the Homebrew team for the way forward.

**Comment by scottohara** [comment]
OK, thanks for your help @BanzaiMan , I will investigate further on the Homebrew side.

For what it's worth, I do have CouchDB installed from Homebrew and running on my dev machine (MacBook Pro), but it was installed a long time ago and I can't recall if I did anything special to get it working back then.

**Comment by scottohara** [comment]
Tried again today and it looks like this issue has now resolved itself. 🎉 

The Homebrew formula has recently been updated from `couchdb-1.6.1_8.sierra.bottle.tar.gz` to `couchdb-1.6.1_9.sierra.bottle.tar.gz`, and CouchDB now successfully starts on the OSX build environment.
