### ISSUE TITLE
Python: use py_compile as script by default 

### ISSUE THREAD

**Issue by judge2020** [travis-ci/travis-ci#7089]
Using python with Travis currently requires you to write some tests. That is well and good, however in other languages tests are not required as basic Travis integration will simply compile the project to make sure it does not have any major problems (such as syntax errors). Using py_compile as the default script will allow basic syntax checking for python projects.

**Comment by BanzaiMan** [comment]
My understanding of the Python ecosystem is that there is no clear consensus as to how to run tests.

[A quick search](https://github.com/search?utf8=%E2%9C%93&q=py_compile+filename%3A.travis.yml) on GitHub shows that there are 42 repositories using `py_compile` out of [88K+](https://github.com/search?utf8=%E2%9C%93&q=%22language%3A+python%22+filename%3A.travis.yml&type=Code&ref=searchresults).

While picking a new default is unlikely to break existing builds, I am not sure `py_compile` should be the default we should choose.

**Comment by judge2020** [comment]
Currently, there is no default for python builds. Compiling the python code would help stamp out syntax errors as with other languages when projects don't have their own tests. It would still be highly recommended to use tests over compiling since Python doesn't have type defining and doesn't even check for legal variables.

**Comment by Monkeyboy2805** [comment]
@judge2020 There's no point in that, you may as well just run the scripts in your travis.yml

**Comment by judge2020** [comment]
Simply thought the default script should be a syntax checking-type device as python has no default compiler, however, I feel this issue is orphaned/too old at this point.
