### ISSUE TITLE
Uploading a report to Coveralls fails due to SunCertPathBuilderException

### ISSUE THREAD

**Issue by kaitoy** [travis-ci/travis-ci#7094]
My Java project [Pcap4J](https://github.com/kaitoy/pcap4j) is using Maven and [coveralls-maven-plugin](https://github.com/trautonen/coveralls-maven-plugin) to upload test coverage reports to Coveralls.
This had been working until 12/23 but today 12/30 it failed due to an error:

```
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.1.0:report (default-cli) on project pcap4j: I/O operation failed: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

The entire build log is [here](https://travis-ci.org/kaitoy/pcap4j/jobs/187788022)

As far as I googled, this seems an SSL certificate chain problem.
My thought is that Coveralls had changed its server certificate very recently and the Travis build system couldn't validate the new certificate Coveralls API returned because some required root certificates or so aren't installed to the system.

**Comment by BanzaiMan** [comment]
Indeed, it appears that the present SSL certificate is valid since December 26. https://travis-ci.org/BanzaiMan/travis_production_test/builds/187857612#L154

As you can see above, though, `curl` is able to connect to coveralls.io over SSLv3, so I am a bit skeptical that the issue lies with our build image.

Does Java 6 use the host's certificates, or does it provide its own? Is Java 6 capable of connecting to coveralls.io now?

**Comment by kaitoy** [comment]
I can connect to Coveralls API https://coveralls.io/api/v1/jobs using Oracle JRE 1.6.0_45 and OpenJDK 1.6.0_35.
It seemed Coveralls doesn't request client certificates, so host's certificates are not relevant. (I saw packets between my JRE and Coveralls using Wireshark.)
The error I reported seems to happen when Java's trust store ($JAVA_HOME/lib/security/cacerts by default) isn't properly configured.
I suspect the trust store may not include the required root certificate.

**Comment by cdragan** [comment]
I'm seeing coveralls upload fail too in my project [Kos](http://github.com/kos-lang/kos) albeit I'm using cpp-coveralls. I don't know if it is related, but I see a Python callstack indicating SSLv3 certificate verification error. Here's the link to the failed job: https://travis-ci.org/kos-lang/kos/jobs/188090245 and here's the callstack:

```
Traceback (most recent call last):
  File "/home/travis/.local/bin/coveralls", line 9, in <module>
    load_entry_point('cpp-coveralls==0.3.12', 'console_scripts', 'coveralls')()
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/__init__.py", line 105, in run
    return report.post_report(cov_report)
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/report.py", line 12, in post_report
    response = requests.post(URL, files={'json_file': json.dumps(coverage)})
  File "/home/travis/.local/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

I have also noticed that there are warnings from the Python urllib3 package installed on Travis systems printed just before the callstack. I looked at previous passing jobs from November and the warnings were already there, and judging by their nature, they are unrelated:

```
/home/travis/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/travis/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
```

**Comment by AndreLouisCaron** [comment]
I'm also getting this for a C project using `cpp-coveralls`.  Strangely, it seems to pass on OSX, but fail on Linux...

Full build logs here: https://travis-ci.org/AndreLouisCaron/libgreen/builds/188436373

**Comment by tobgu** [comment]
Same here: https://travis-ci.org/tobgu/pyrsistent/jobs/189580746

**Comment by zilm13** [comment]
Had the same issue with Travis oraclejdk7. Moreover, after cleaning build cache not only coveralls.io stopped working. Gradle was unable to download dependencies, because they are fetched via HTTPS. And `$JAVA_HOME/jre/lib/security/cacerts` looks different from Oracle distribution.

Solved with a weird hack:
```
before_install:
  - 'if [ ! -d $HOME/.jdk/jdk1.7.0_79 ]; then wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz && tar -zxvf jdk-7u79-linux-x64.tar.gz && rm jdk-7u79-linux-x64.tar.gz && mv jdk1.7.0_79 $HOME/.jdk ; fi'
  - export JAVA_HOME=$HOME/.jdk/jdk1.7.0_79
```

Hope, the bug will be fixed soon, so I could remove above

**Comment by BanzaiMan** [comment]
Does the issue persist on jobs with `sudo: required`?

**Comment by BanzaiMan** [comment]
I have a report that it does.

**Comment by zilm13** [comment]
@BanzaiMan for us, yeah
```
sudo: required
dist: trusty

language: java
jdk: oraclejdk7
```
The issue appeared on 23th December and still actual.

**Comment by kaitoy** [comment]
@BanzaiMan 
My project is with `sudo: required`, too.

**Comment by kaitoy** [comment]
Changing openjdk6 to oraclejdk7 solved the issue to me.

**Comment by helinwang** [comment]
adding
```
dist: trusty
```
solved the issue for me.

**Comment by BanzaiMan** [comment]
We are now updating libssl1.0.0 when necessary. This was effective in allowing connections to TLSv1.2-only sites with `curl`. This might also be effective for this issue.

If it is not, please consider migrating the builds to Trusty, which is shown to resolve the issue.

I'm closing this now.
