### ISSUE TITLE
Could you add "clear" for individual scripts

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#7101]
"clear" doesn't work currently

**Comment by BanzaiMan** [comment]
What is cls?

**Comment by Monkeyboy2805** [comment]
@BanzaiMan I meant clear, sorry. For terminal resetting

**Comment by BanzaiMan** [comment]
Are you expecting `clear` to wipe out the entire build log?

Our build logs are stream-oriented, meaning that we record every byte generated. Some implementation of `clear` just writes a bunch of CRLF pairs, and some others generate ANSI code to achieve it. Either way, these will not work with streams.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan Right OK, I was just wondering, because my project has an animation script that uses clear but I don't know if it looks correct on Linux. Mainly just to look at the animation while on of the builds is in progress

**Comment by Monkeyboy2805** [comment]
@BanzaiMan But maybe not the entire build log :P

**Comment by BanzaiMan** [comment]
Some animation is based on wiping out the current line, and I think it may work on our logs, but in general, I tend to think cursor maneuvers across multiple lines probably won't work.

**Comment by BanzaiMan** [comment]
I don't think there is much to do here. I'm closing this.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan K whatever
