### ISSUE TITLE
travis log does not show output from apt-get install command

### ISSUE THREAD

**Issue by melezhik** [travis-ci/travis-ci#7106]
HI!

Here is my job log - https://travis-ci.org/melezhik/sparrowdo/builds/188990107#L1309-L1312, so lines 1309 ... 1312 are empty but there should be an output from `apt-get install tree` command. The same thing for the following lines L1323 .. L1330 ( `apt-get install mc` ).  Compare the output from the script  which I run manually,  not by the Travis, this is how *right* output should look like:
 
```
/modules/apt-get/ action:install package:tree started
trying to install tree ...
installer - apt-get
Selecting previously unselected package tree.
(Reading database ... 96133 files and directories currently installed.)
Preparing to unpack .../tree_1.7.0-3_amd64.deb ...
Unpacking tree (1.7.0-3) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up tree (1.7.0-3) ...
Package: tree
Version: 1.7.0-3
Status: install ok installed
```

My guess is for some reasons Travis "replace" output from `apt-get install` ( if any ) by blank lines ...

**Comment by BanzaiMan** [comment]
That line is from your invocation of `perl6 -Ilib bin/sparrowdo --host=127.0.0.1 --sparrowfile=examples/package-install/sparrowfile`. Something other than Travis must be redirecting I/O.

**Comment by melezhik** [comment]
HI @BanzaiMan , sorry not sure what you mean?

**Comment by melezhik** [comment]
I am still not clear, why some lines at the Travis are empty , see screenshot ( empty blocks are denoted by orange ). While the same script when gets run directly produce none empty output at those lines?

**Comment by melezhik** [comment]
Well, I can tweak the Travis job setting and will try to turn in colorless mode where it is possible, to minimize ansi symbols presence, lets see if it helps.

**Comment by melezhik** [comment]
Looks like disabling color mode in  my script not that easy. If I got you right you will be looking into this issue anyway?

**Comment by backspace** [comment]
Hey! I am indeed looking into it, thanks for the report, @melezhik. The true experts about log displays are sadly not around right now, so I’m puzzling through some old and untested code.

My current finding is that the logging code overwrites lines that end with decimal ASCII character 13, carriage return, but preserves those that end with 10, line feed. But there’s some curious code to strip carriage returns that seems overeager to me, so I tried [skipping it](https://github.com/travis-ci/travis-web/pull/893/files#diff-a9f1ee3a2839d79578ecf5adef53afe1).

If you [view that log at this test deployment](https://bd-overeager-newlines.test-deployments.travis-ci.org/melezhik/sparrowdo/builds/188990107#L1309-L1312) (you’ll have to log in), does it look more like what you’re expecting?

**Comment by melezhik** [comment]
Hi @backspace ! Thanks for looking into this.

> If you view that log at this test deployment (you’ll have to log in), does it look more like what you’re expecting

Yeah this one looks good . Now logs from apt are here.

**Comment by backspace** [comment]
Excellent news! Thanks for the confirmation.

It probably won’t be until next week that I can ask around with people who are more familiar with this code to confirm that my fix is acceptable. In the meantime, that deployment will work indefinitely.

**Comment by melezhik** [comment]
Yeah, I even changed abit a .travis.yml meanwhile, so no hurry, I even can live with this issue open. Just wanted to let you know :))

**Comment by backspace** [comment]
Thanks for your patience! It took a while to hear back from people who have more experience with this code, but it‘s finally deployed.

**Comment by melezhik** [comment]
Hi @backspace ! Now looks good for me - https://travis-ci.org/melezhik/sparrowdo/builds/197553675 , thanks a lot!

**Comment by backspace** [comment]
Hello, again, @melezhik. I’m sorry to have to do this, but I’m reverting my change because it turns out to have [broken other log rendering](https://github.com/travis-ci/travis-ci/issues/7293). No one was really sure what the code I changed was doing, but it was obviously important.

Now that I’ve looked into this so much, I think we should be able to fix your rendering problem without negatively affecting other logs, but for now, I’m going to cause blank lines in your logs for a while again 😢

**Comment by melezhik** [comment]
Hi , @backspace , that's ok.  As I said , no rush -)

**Comment by backspace** [comment]
I’m back again with [another potential fix](https://bd-log-2-electric-boogaloo.test-deployments.travis-ci.org/melezhik/sparrowdo/builds/188990107#L1309-L1312), which is much more specific to your case. I now know it won’t render certain logs properly, but at least it renders yours properly and [doesn’t break the other one](https://bd-log-2-electric-boogaloo.test-deployments.travis-ci.org/citation-style-language/styles/builds/199495218)!

Sadly, I start vacation tomorrow, so I’m not sure when this will be deployed. Maybe someone will take care of it in my absence! But thanks for your patience.

**Comment by melezhik** [comment]
Hi @backspace ! NP I am on vacation too -)

**Comment by backspace** [comment]
Thanks for being so understanding, @melezhik. I’ve deployed that fix and the linked log is back to rendering properly!

**Comment by melezhik** [comment]
Thanks! :)
