### ISSUE TITLE
Two copies of repo in Travis CI webpage

### ISSUE THREAD

**Issue by juliohm** [travis-ci/travis-ci#7109]
I have two copies of a repo in my Travis CI webpage and none of them have coverage checks:

![screenshot from 2017-01-04 21-19-01](https://cloud.githubusercontent.com/assets/3345261/21664185/ce76e4fc-d2c3-11e6-9d5b-b3829fc733e5.png)

If I delete these repos in the Travis CI webpage, they will also be deleted on GitHub? What is happening here?

**Comment by BanzaiMan** [comment]
This is not our page. That looks more like coveralls.io page. Please ask for support from them.
