### ISSUE TITLE
Builds not being requested on a specific PR

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#7111]
We have twice seen pushes to https://github.com/coala/coala-bears/pull/1147 not trigger a Travis build.

No entry appears in https://travis-ci.org/coala/coala-bears/requests for that PR.  We have regular builds occurring for other PRs.

**Comment by BanzaiMan** [comment]
Sorry about the issue. It seems that our request to fetch the commit resulted in 404 for some reason. Could you try pushing a new commit for this PR?

**Comment by jayvdb** [comment]
not much point now.  We've merged it using a new PR, and closed the problematic one.
