### ISSUE TITLE
Support language: json

### ISSUE THREAD

**Issue by alexbowers** [travis-ci/travis-ci#7116]
Verifying that JSON is valid would be useful

Currently, I have to build using any language (chose node_js), and then install `jq` and run `js '.' filename.json`

This could probably be made simpler / easier

**Comment by BanzaiMan** [comment]
I am not sure if this is a use case worth supporting as a separate "language". JSON is not a language in and of itself that needs install, build, etc. Furthermore, `jq` should be preinstalled in all build images, and you should not have to install it yourself. (If you do, please report.)

**Comment by alexbowers** [comment]
I'm not aware of whether or not I have to install `jq` myself. In my usecase, I did anyway, but didn't test it without.

Instead of a `json` language, would you perhaps have a `no language` option, which is basically a blank box.

For my use case, all I want to be able to do is test whether some json files are valid. I have no need for a full php, node, ruby etc environment, and without these I imagine the tests would run faster (due to less provisioning being required).

**Comment by BanzaiMan** [comment]
You can use `language: generic` then.

**Comment by alexbowers** [comment]
@BanzaiMan Perhaps this could be documented. I did look for something like that, but saw nothing n the docs page: https://docs.travis-ci.com/user/languages/

**Comment by BanzaiMan** [comment]
Sorry, but JSON is not a programming language, so I am not sure how it would fit on the languages page. Perhaps we can introduce a page for `language: generic` and show some example usages, including this.

**Comment by alexbowers** [comment]
Sorry, I meant to document the generic language option

**Comment by BanzaiMan** [comment]
All right, then. I'm going to close this issue in favor of https://github.com/travis-ci/docs-travis-ci-com/issues/910.
