### ISSUE TITLE
Renaming a repository trips Travis

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#712]
I renamed a repository hanke-henry-calendar to hanke-henry through github's admin page. The former had Travis set up (https://travis-ci.org/#!/BanzaiMan/hanke-henry-calendar/builds), but the latter does not. I double checked the set up; https://travis-ci.org/profile shows that Travis is configured and enabled.

I imagine that I can delete and re-create the repository, but I figure I should mention this before doing so.

**Comment by ZevEisenberg** [comment]
Seeing this as well. Any known resolution?

**Comment by ZevEisenberg** [comment]
Scratch that - it looks like it just took a few minutes to refresh. I was confused because I was clicking the Sync button on https://travis-ci.org/profile/, but when it finished, it still said the last sync was 4 hours ago. All good now.

**Comment by s2t2** [comment]
I renamed my repo on GitHub, and Travis is still working as expected, but the repo name in Travis has not been updated.

Its been over a half hour and the name has not yet updated in Travis.
