### ISSUE TITLE
Job appears to be stuck in "created" state

### ISSUE THREAD

**Issue by xoviat** [travis-ci/travis-ci#7121]
https://travis-ci.org/pyinstaller/pyinstaller/builds/190323810

**Comment by BanzaiMan** [comment]
pyinstaller/pyinstaller builds are blocked by https://travis-ci.org/pyinstaller/pyinstaller-osx-tests (in particular, https://travis-ci.org/pyinstaller/pyinstaller-osx-tests/builds/190317942), which, in turn, are blocked by the shortage of OS X build resources at the moment. Once the OS X jobs have run, the build above will go, too.

**Comment by xoviat** [comment]
Thanks. I was confused because there seemed to be enough linux resources.
