### ISSUE TITLE
Ruby 2.3.3 fail to install kali linux

### ISSUE THREAD

**Issue by iamehiz** [travis-ci/travis-ci#7123]
when i run the command " rvm install ruby-2.3.3 " this is what i get

> ruby-2.3.3 - #removing src/ruby-2.3.3..
> Searching for binary rubies, this might take some time.
> No binary rubies available for: debian/Kali_Linux_Rolling/x86_64/ruby-2.3.3.
> Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
> Checking requirements for debian.
> Installing requirements for debian.
> Updating system.
> Installing required packages: libreadline6-dev...
> Requirements installation successful.
> Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
> ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
> ruby-2.3.3 - #extracting ruby-2.3.3 to /usr/local/rvm/src/ruby-2.3.3....
> ruby-2.3.3 - #configuring...................................................-
> ruby-2.3.3 - #post-configuration..
> ruby-2.3.3 - #compiling.....................................................|
> Error running '__rvm_make -j4',
> showing last 15 lines of /usr/local/rvm/log/1483990077_ruby-2.3.3/make.log
> compiling date_strptime.c
> compiling object_tracing.c
> linking shared-object objspace.so
> compiling date_strftime.c
> make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3/ext/objspace'
> installing default date_core libraries
> installing default nkf libraries
> linking shared-object date_core.so
> make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3/ext/date'
> linking shared-object nkf.so
> make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3/ext/nkf'
> make[1]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3'
> uncommon.mk:203: recipe for target 'build-ext' failed
> make: *** [build-ext] Error 2
> ++ return 2
> There has been an error while running make. Halting the installation.

i don't know why?

**Comment by BanzaiMan** [comment]
This looks like an install of 2.3.3 from source with rvm. Please report it to https://github.com/rvm/rvm/issues.
