### ISSUE TITLE
Wrongly understood row as allow_failues

### ISSUE THREAD

**Issue by dg** [travis-ci/travis-ci#7124]
Hello, I think that Travis wrongly understood row "PHP 7" as allow_failues.

This is [travis.yml](https://github.com/nette/caching/blob/492413c6b69861ff5f2c81fe4e59025c06b8451c/.travis.yml) and [result](https://travis-ci.org/nette/caching/builds/190377308) - row "PHP 7 - no enviroment variables set" should not be in Allowed Failures,

It is interesting that this [small modification](https://github.com/nette/caching/commit/3d51979570e6eb8814641f3a83d6eb2c2b397eb4) it fixes - [result](https://travis-ci.org/nette/caching/builds/190378624).

---

btw "PHP 7" should be reported as "PHP 7.0".

**Comment by BanzaiMan** [comment]
Thanks for the report.

`PHP 7` is a separate issue which merits its own treatment. Please open a new issue on that. Thanks.

**Comment by BanzaiMan** [comment]
Since `env` does not exist on the top level `env` in the configuration, the `env` criterion in the `matrix.allow_failures` is ignored, and it is basically

```yaml
matrix:
    allow_failures:
        - php: 7.0
```

which matches 2 jobs in the matrix.

**Comment by BanzaiMan** [comment]
In other words, when we try to match with `env`, there is no `env` to match with in the configuration.

**Comment by dg** [comment]
Thanks for explanation. It is not quite user friendly, because with empty `env` it correctly matches and empty `env` seems like the same as none `env`.

**Comment by BanzaiMan** [comment]
The empty `env` and the absence of `env` are two different things.

**Comment by BanzaiMan** [comment]
Is there anything to do here?

**Comment by dg** [comment]
@BanzaiMan today, something has changed and it doen't work even with empty `env`.

https://travis-ci.org/nette/database/builds/195278191 "coverage: on:" should be in allow_failures ([.travis.yml](https://github.com/nette/database/blob/6c9d418a4a4e220f1c42ceee99e21db359238e35/.travis.yml))

**Comment by BanzaiMan** [comment]
@dg That's probably a bug in the code we deployed earlier today. Please open a separate issue.

**Comment by BanzaiMan** [comment]
Actually, I'll reopen this one.

**Comment by rpkilby** [comment]
I don't know if this is part of the same bug, or if this is a separate issue. This [PR](https://github.com/tomchristie/django-rest-framework/pull/4849) passed as expected with this [build](https://travis-ci.org/tomchristie/django-rest-framework/builds/195141001). However, a merge commit a few hours later today failed as the [build](https://travis-ci.org/tomchristie/django-rest-framework/builds/195195705) stopped marking a few jobs as allowed_failures.

**Comment by BanzaiMan** [comment]
I'm closing this again, since the issue with the deployment was reported in #7221.
