### ISSUE TITLE
"PHP 7" should be reported as "PHP 7.0"

### ISSUE THREAD

**Issue by dg** [travis-ci/travis-ci#7125]
In order to more clearly differentiate PHP 7.0 and 7.1. (example https://travis-ci.org/nette/caching/builds/190378624)

**Comment by BanzaiMan** [comment]
I will note that your configure says `7`, not `7.0`. This is a subtle but important difference.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan Good point

**Comment by dg** [comment]
Do you mean travis.yml? There is 7.0 https://github.com/nette/caching/blob/3d51979570e6eb8814641f3a83d6eb2c2b397eb4/.travis.yml

**Comment by BanzaiMan** [comment]
Sorry, I meant `7.0` vs `"7.0"`. The former is a float, the latter a string.

Compare https://travis-ci.org/BanzaiMan/travis_production_test/builds/192687353 and its config https://github.com/BanzaiMan/travis_production_test/blob/598743633755d34f8cb75ac1b3a9d04f30f6961e/.travis.yml#L3-L5.

**Comment by dg** [comment]
Oh, I see. JavaScript does not see the difference between them 7 and 7.0…

**Comment by BanzaiMan** [comment]
It is not JavaScript, but the YAML parser.

**Comment by simi** [comment]
I think this problem is not in YAML parser, since API returns correct value (https://api.travis-ci.org/builds/190378624, https://api.travis-ci.org/jobs/190378626).

That zero decimal is lost during JSON parsing in browser.

**Comment by BanzaiMan** [comment]
Thanks for the correction.

**Comment by BanzaiMan** [comment]
@simi Upon further reflection, you see that API returns floats. At any rate, we'll take a look.

**Comment by carlad** [comment]
The new `travis-yml` library patches YAML, but we are still in the process of implementing the library. In the meantime it's necessary to specify `"7.0"` - i.e. as a string - rather than `7.0` in the `.travis.yml` file...
