### ISSUE TITLE
trusty containers - short on space (some of them anyway)

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#7126]
https://travis-ci.org/facebook/rocksdb/jobs/190120768

final link failed: No space left on device

Worker information:

hostname: i-03965fc62fde4d95f-production-2-worker-org-ec2.travisci.net:ebad11c0-71ab-47a3-a0ae-72741331f722
version: v2.5.0-8-g19ea9c2 https://github.com/travis-ci/worker/tree/19ea9c20425c78100500c7cc935892b47024922c
instance: 2e189db:travis:default
startup: 5.858092569s

**Comment by BanzaiMan** [comment]
Any idea how much additional disk space the build is consuming?

**Comment by grooverdan** [comment]
I had a look and it appears there is ~9G available. I think I can split up the tests a lot more to work within that limit. Going higher is just looking excessive.
