### ISSUE TITLE
Connection Refused randomly?

### ISSUE THREAD

**Issue by Supamiu** [travis-ci/travis-ci#7127]
Hi, I'm starting a little [server projet](https://github.com/Supamiu/mmoserver) using java.nio and testing it with JUnit:  Once I configured travis, I had some connection refused immediatly, after reading some issues, I found that I had to listen on 0.0.0.0, so I made the change ([see commit](https://github.com/Supamiu/mmoserver/commit/661353161c9f0c7ec53a252575b5612d3529db63#diff-fbbc74bbb6a0a1f113640d986537750cR52)) and the build passed perfectly.

Right after this one, I made a little indent change and I got the connection refused error again.

I already tried to change the port, to add sudo:true in configuration, and to set the port to 80 to be sure that the server was starting (since 80 is already used, I expected an error and got it).

Here are my builds: https://travis-ci.org/Supamiu/mmoserver/builds/

The working one: https://travis-ci.org/Supamiu/mmoserver/builds/190412724
And an example of a failing one: https://travis-ci.org/Supamiu/mmoserver/builds/190431609

Feel free to check the testing code, the repository is a small one at the moment so the testing code is pretty simple.

**Comment by BanzaiMan** [comment]
I don't know what process is supposed to be listening on port 80, or how the process is started. Sometimes processes need time to start listening; perhaps you are testing connections too early.

**Comment by Supamiu** [comment]
I just made it to be sure that my server was starting, as I expected port 80 to be already used and thus my server would throw an error.

my test is pretty simple: start the server, start the client, send a packet from client, check that server got it. 

It fails whan I start the client because it doesn't connect due to Connection Refused.

Since the server is in another thread, maybe I should wait something like 100ms before creating the client, I'll try that but I doubt it will work because it already worked without it :cry:

**Comment by Supamiu** [comment]
Seems like adding a delay between server start and client connection has resolved the problem.

I close the ticket, if the problem comes from something else, I'll reopen it with more details.
