### ISSUE TITLE
Waiting for status to be reported

### ISSUE THREAD

**Issue by sarangan12** [travis-ci/travis-ci#7134]
I have created a PR in my repository which started a Travis CI job. The job has completed successfully an hour back but the PR still indicates "Waiting for status to be reported". PR Link: https://github.com/Azure/autorest/pull/1711 

I did not rename or do any other changes in my repository. Could you please help me resolve the issue?

**Comment by BanzaiMan** [comment]
The unmet requirement is for "default". Not ours. You can see that we report the pass correctly. I can't tell what it is from the available information, but I suggest you should ask the repository administrators.

![added_code_to_change_the_data_type_of_itemtype_by_sarangan12_ _pull_request__1711_ _azure_autorest](https://cloud.githubusercontent.com/assets/25666/21831622/1b6e0e94-d773-11e6-9250-95bf3f8889d1.png)
