### ISSUE TITLE
Core Files are Never Created with "sudo: false"

### ISSUE THREAD

**Issue by zachriggle** [travis-ci/travis-ci#7135]
Under containerize builds, on Ubuntu Precise (the default container), the `sysctl` configuration value `kernel.core_pattern` is set to `|/usr/share/apport/apport %p %s %c %P`.

Unfortunately, `apport` is not installed by default.  Luckily, it is in the [whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/fdcd8ac0100606c5054c7233ba2b592fb15926ad/ubuntu-precise#L56) of allowed packages.  This allows me to do, e.g.:

```
addons:
  apt:
    packages:
      - apport
```

However, even if `apport` is installed via this mechanism:

```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes apport
...
The following NEW packages will be installed:
  apport ...
```

... the service is unable to start.

```
Setting up python-apport (2.0.1-0ubuntu17.15) ...
Setting up apport (2.0.1-0ubuntu17.15) ...
start: Job failed to start
invoke-rc.d: initscript apport, action "start" failed.
```

This means that ultimately, core-files can never be dropped or examined on Precise.  This is unfortunate, because core-files are extremely useful in debugging, and in particular I have a core-file parsing library that generates them on-the-fly (by causing a binary to crash)... but I can't actually test this functionality on Travis if core-files are never generated.

**Comment by zachriggle** [comment]
Apparently, the piped `core_pattern` is executed in the initial namespace, so cores are not dropped inside the container.

Changing `core_pattern` to be a non-piped pattern (e.g. `core.%e.%p`) would permit cores to be dropped inside the container, and available to tests.

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #3754.

**Comment by zachriggle** [comment]
Indeed, that has better progress and workarounds and status.  Closing this in favor of that.
