### ISSUE TITLE
CC-Menu feed for user/org returns 403 Forbidden

### ISSUE THREAD

**Issue by tbroyer** [travis-ci/travis-ci#7137]
For a couple days now (or maybe even just before/during the last week-end), the CC-Menu feed for an account, as documented in https://docs.travis-ci.com/user/cc-menu/#Using-the-CC-feed-with-accounts, returns a 403 Forbidden (tested with BuildNotifier, Chrome, and Firefox, on Ubuntu 16.10).

Compare https://api.travis-ci.org/repos/tbroyer/gwt-maven-plugin/cc.xml (works) with https://api.travis-ci.org/repos/tbroyer.xml (forbidden)

**Comment by BanzaiMan** [comment]
This has been fixed. Thanks for reporting!

**Comment by tbroyer** [comment]
Thanks
