### ISSUE TITLE
Travis attempts (and fails) to use CocoaPods latest before starting provided build steps.

### ISSUE THREAD

**Issue by dtrenz** [travis-ci/travis-ci#7139]
I'm building an iOS project with these settings in my `.travis.yml`:
```
language: objective-c
osx_image: xcode8.2
```

It appears that Travis automatically attempts to output the system pod version, but it errors instead:

![image](https://cloud.githubusercontent.com/assets/639833/21855574/f1a73822-d7ec-11e6-8ae0-72cf44827610.png)

This is not blocking builds for me because I am installing CocoaPods via Gemfile/bundler, but I imagine that any jobs that are trying to use system CocoaPods are failing, as a result of this bug.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

It seems to me that your build is requiring a pre-release version of cocoapods and we somehow failed to find it in the index. The default image should be 1.1.1 (https://travis-ci.org/BanzaiMan/travis_production_test/builds/191031406#L340), and we should be able to install 1.2.0.beta.3 (https://travis-ci.org/BanzaiMan/travis_production_test/builds/191056920#L354).

**Comment by dtrenz** [comment]
I don't believe so. It appears that this is happening before anything that I am specifying as a `before_install`build step is being executed: https://travis-ci.org/dtrenz/BugShaker/builds/191002102

**Comment by BanzaiMan** [comment]
Your `Podfile.lock` specifies [`1.2.0.beta.3`](https://github.com/dtrenz/BugShaker/blob/ce6349dacbe0c19b2bd0387ff26e9464324ba7a0/Podfile.lock#L18) but it is not installed yet.

If you cache your gems, I believe the warning will go away.

**Comment by dtrenz** [comment]
Ah, thanks. Sorry, silly mistake.
