### ISSUE TITLE
Travis doesn't pull from remote branches when opening a pull request

### ISSUE THREAD

**Issue by CorruptComputer** [travis-ci/travis-ci#7142]
When Travis build my [PR](https://github.com/EfficientConversation/EfficientConversation.github.io/pull/2) it shows in the [console](https://travis-ci.org/EfficientConversation/EfficientConversation.github.io/builds/191255195#L249) it pulled from upstream master, not the remote branch.

Is it something wrong with my [`.travis.yml`](https://github.com/EfficientConversation/EfficientConversation.github.io/blob/master/.travis.yml) or a bug?

**Comment by BanzaiMan** [comment]
The log clearly shows that the build was that of the merge commit of the PR in question (https://travis-ci.org/EfficientConversation/EfficientConversation.github.io/builds/191255195#L127):

```sh-session
$ git fetch origin +refs/pull/2/merge:
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 13 (delta 6), reused 8 (delta 3), pack-reused 0
Unpacking objects: 100% (13/13), done.
From https://github.com/EfficientConversation/EfficientConversation.github.io
 * branch            refs/pull/2/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
```

The line you are pointing to is output from the `jekyll` command. If that indicates it is not doing something  a PR builds should not do, then the build process should be fixed.
