### ISSUE TITLE
Add Vulkan support

### ISSUE THREAD

**Issue by realitix** [travis-ci/travis-ci#7143]
Hello,
It would be great to add Vulkan support to Travis CI. You don't need to support the swapchain extension (maybe to complicated) but you can support the core API, it doesn't need graphic interface.

Are you planning to add Vulkan support ? If yes, when?

Thanks,
Jean-Sébastien

**Comment by BanzaiMan** [comment]
What is Vulkan?

**Comment by realitix** [comment]
Vulkan is the future: https://www.khronos.org/vulkan/

**Comment by realitix** [comment]
Any news?

**Comment by simi** [comment]
You can setup Vulkan manually on machines. You can inspire in https://github.com/KhronosGroup/Vulkan-Samples or https://github.com/SaschaWillems/Vulkan repos.

**Comment by BanzaiMan** [comment]
So, this is a request for GPU-based testing?

**Comment by realitix** [comment]
Yes @BanzaiMan

**Comment by realitix** [comment]
@simi It's GPU based so I need a driver that supports Vulkan. It's not just installing the SDK.

**Comment by BanzaiMan** [comment]
Understood. Having a hardware backend for such support depends on many things, and we may consider it for the future.

At the moment, we do not have it on our roadmap. This may change in the future, of course, and we would revisit it in the future.

Thank you for your interest. I'm closing this for now.

**Comment by BanzaiMan** [comment]
Related: #5911.

**Comment by abergmeier-dsfishlabs** [comment]
Would need that too. Especially since setting up an own Travis does not seem trivial.

**Comment by abergmeier** [comment]
Would need that too. Especially since setting up an own Travis does not seem trivial.
