### ISSUE TITLE
Open source macOS builds are running close to capactity 

### ISSUE THREAD

**Issue by jrmuizel** [travis-ci/travis-ci#7148]
It seems like the macOS build pool is headed toward over capacity. It has not dropped below 80 active jobs for the last week.

**Comment by solarce** [comment]
This is known and while we are working to add more capacity to help, there's always going to be a potential for us hitting capacity as there is a huge demand for our macOS offering for public repositories and providing more capacity is very expensive, compared to what we can get using public cloud providers for Linux. Ultimately this a peak capacity for .org macOS and that is _by design_.
