### ISSUE TITLE
travis_wait

### ISSUE THREAD

**Issue by jtroest** [travis-ci/travis-ci#7151]
How is this supposed to work? The documentation https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received does not work. Is this an example or a n instruction?
My iOS build has a step that takes more than 10 minutes (not on my own machine but on Travis apparently) and whether I prefix the command with travis_wait as vaguely suggested or add the line from the documentation makes no difference.
Please tell me how I make my build run beyond the 10 minutes in clear and concise terms.

**Comment by BanzaiMan** [comment]
What do you mean by "the documentation does not work"? What have you tried and what did you see? Do you have a build log URL that shows the problem you are describing here?

**Comment by jtroest** [comment]
I mean what does:
install: travis_wait mvn install
do? I have seen several code examples on the web of people just copying this. For me it did nothing. What is mvn install?
I have figured out from other code examples how travis_wait works, but the documentation appears to show an example without mentioning it is. Or maybe not, since I have no idea what mvn is or does :)

**Comment by BanzaiMan** [comment]
What did you expect `travis_wait mvn install` would do, if you didn't know what `mvn` is?

I see that there is room for improvement in documentation; I want to understand how the problem arose.
