### ISSUE TITLE
Improve/extend search functionality

### ISSUE THREAD

**Issue by michaelklishin** [travis-ci/travis-ci#716]
This is a placeholder issue for some search improvements I'd like to start working on. It will be expanded in the upcoming days.

## Goals

 * Make it easier to find projects, accounts and builds.

## Design

There are two parts to search: indexing and searching. Indexing will involve indexing our existing data set (which is in gigabytes) as well as new data. The plan for that is to add a separate JVM-based service that will have a task to do bulk indexing and consumers that will handle relevant events.

Searching can be either done in the same service (we can trivially start it in a separate thread, without
any interference with the message consumer part) or `api.travis-ci.org`. Our queries won't be complex
so we can use a low-level Ruby client right from the API service.

ElasticSearch will do the actual indexing and querying part. The details of how each field should
be analyzed and what we want to search over will become clear over time but if you have suggestions,
just leave a comment.

## Access Permissions

For Travis Pro, information filtering can be very efficiently done using basic term filtering by account id, org id or any other field.

## Challenges

We have enough data for Heroku ElasticSearch addons (which are very young, by the way) to not be a viable economical option. As such, we will need to take a few samples to see how much data
the index may take for our data set and decide what kind of machine will be sufficient.

## Future Plans

To make searching over logs better, at some point we will look into implementing our own tokenizer. Wiring a custom tokenizer in  with ES is really straightforward.

Per discussion with @joshk. FYI @roidrage @svenfuchs @rkh.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
