### ISSUE TITLE
C# on linux fails to copy embedded resource

### ISSUE THREAD

**Issue by tzachshabtay** [travis-ci/travis-ci#7160]
Hi, my build is failing on Linux (while passing on Mac).

The errors I'm getting are about embedded resources (in a shared project) which cannot be copied. One example:

`/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Cannot copy /home/travis/build/tzachshabtay/MonoAGS/Source/Demo/DemoQuest/Assets/Characters/Beman/Idle/down/down.bmp to /home/travis/build/tzachshabtay/MonoAGS/Source/Demo/DemoQuest.Desktop/obj/Release/DemoQuest.Desktop.Assets.Characters.Beman.Idle.down.down.bmp, as the source file doesn't exist.
`

Weirdly enough, there seems to be only a single folder ("Beman") of embedded resources which gives those errors, the rest of the folders (all sit under the "Assets" folder, same as the failed folder) are copied just fine.
For example:

`Copying file from '/home/travis/build/tzachshabtay/MonoAGS/Source/Demo/DemoQuest/Assets/Characters/Loopy/1.bmp' to '/home/travis/build/tzachshabtay/MonoAGS/Source/Demo/DemoQuest.Desktop/obj/Release/DemoQuest.Desktop.Assets.Characters.Loopy.1.bmp'
`

Also that same folder is copied just fine on the Mac build:

`Copying file from '/Users/travis/build/tzachshabtay/MonoAGS/Source/Demo/DemoQuest/Assets/Characters/Beman/Idle/down/down.bmp' to '/Users/travis/build/tzachshabtay/MonoAGS/Source/Demo/DemoQuest.Desktop/obj/Release/DemoQuest.Desktop.Assets.Characters.Beman.Idle.down.down.bmp'
`

Link to the linux (failed) build log: https://travis-ci.org/tzachshabtay/MonoAGS/jobs/192223574
Link to the Mac (successful) build log: https://travis-ci.org/tzachshabtay/MonoAGS/jobs/192223575
Link to travis.yml: https://github.com/tzachshabtay/MonoAGS/blob/BuildForAndroid/.travis.yml

@joshua-anderson @akoeplinger @nterry

Please help, thanks.

**Comment by Joshua-Anderson** [comment]
Mac OS X has a case insensitive file system while linux has a case sensitive one, so I suspect it has to do with an error in your file path capitalization.

**Comment by tzachshabtay** [comment]
Ah, of course, thank you!
As I was working on a mac, git was ignoring my folder casing rename...
Fixed now, closing this.
