### ISSUE TITLE
Build still not started

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#7162]
https://travis-ci.org/LolexOrg/Lolex-Tools/jobs/192322274

**Comment by BanzaiMan** [comment]
There was a sudden surge in demand for container builds. We are spinning up the instances; it will take a little longer, but the job should start eventually.

**Comment by BanzaiMan** [comment]
Hmmm. Strange. It still hasn't started. Could you try restarting the job?

**Comment by devnoname120** [comment]
I have a similar problem here: https://travis-ci.org/vitasdk/packages/builds/192444627
According to https://www.traviscistatus.com/, there are no backlog container-based Linux builds.

**Comment by BanzaiMan** [comment]
@devnoname120 Your build slots are all in use, one of which is a Mac job waiting to run. https://travis-ci.org/vitasdk/autobuilds/jobs/192437467

**Comment by BanzaiMan** [comment]
@Monkeyboy2805 I wonder why your jobs are prone to getting stuck. (See #6919, for example.)

This could be completely a shot in the dark, but why are you [setting `os: [ "windows"]`](https://github.com/LolexOrg/Lolex-Tools/blob/01cd9863e765a8295951eaf28633b555f0bc91c1/.travis.yml#L1-L2)?

**Comment by Monkeyboy2805** [comment]
@BanzaiMan Oh, that was before I realized that Windows wasn't supported, and I have got round to removing it though

**Comment by Monkeyboy2805** [comment]
I'll try removing it now

**Comment by Monkeyboy2805** [comment]
Done, also cut down to 3 DJANGO_VERSIONs to lighten the load

**Comment by Monkeyboy2805** [comment]
![image](https://cloud.githubusercontent.com/assets/20478546/22017754/82dd0870-dca3-11e6-982c-4f05f366ac63.png)
ERRORED: no build log

**Comment by Monkeyboy2805** [comment]
Restarting...

**Comment by Monkeyboy2805** [comment]
Started

**Comment by Monkeyboy2805** [comment]
WEIRD

**Comment by Monkeyboy2805** [comment]
I have had this before, but I just assumed it was just that I was making too many commits

**Comment by Monkeyboy2805** [comment]
Ignore the error, that was just a GithubWebEditor derp, otherwise it's fine though :thinking:

**Comment by BanzaiMan** [comment]
Is this still a problem?

**Comment by Monkeyboy2805** [comment]
No, as far as I can tell. I'll close this now. Sorry about the wait :P
