### ISSUE TITLE
PHP 5.3 support dropped?

### ISSUE THREAD

**Issue by nilleroux** [travis-ci/travis-ci#7163]
Hi!

Did you drop support for PHP 5.3? My CI scripts used to work with PHP 5.3, but it stopped working some time ago.

```
$ phpenv global 5.3 2>/dev/null

5.3 is not pre-installed; installing
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

$ phpenv global 5.3

rbenv: version `5.3' not installed
```

Please, note that I use the experimental container-based environment.
```
dist: trusty
sudo: false
```

Any clue?
Thanks

**Comment by BanzaiMan** [comment]
We do not support PHP 5.3 on Trusty. If you need PHP 5.3, you need to use Precise. https://github.com/travis-ci/travis-ci/issues/2963
