### ISSUE TITLE
Jobs defined by `matrix.include` should inherit `dist` value if it is defined

### ISSUE THREAD

**Issue by jcelerier** [travis-ci/travis-ci#7165]
See this job : https://travis-ci.org/OSSIA/API/jobs/192458393

The .yml : https://github.com/OSSIA/API/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
Your `dist` is not effective here.

You have a 2x2 build matrix with `os` and `env` keys (https://github.com/OSSIA/API/blob/a98ab0561c9da554dfa04f4510e608ef405c080d/.travis.yml#L3-L9), but you have excluded all of them with the `os` key (https://github.com/OSSIA/API/blob/a98ab0561c9da554dfa04f4510e608ef405c080d/.travis.yml#L27-L29). The resulting 10-job build matrix is defined entirely by `matrix.include` (https://github.com/OSSIA/API/blob/a98ab0561c9da554dfa04f4510e608ef405c080d/.travis.yml#L31-L54), none of which has `dist: trusty`.

**Comment by BanzaiMan** [comment]
It is a bit surprising, though, that `dist` value is not inherited by the included jobs.

**Comment by jcelerier** [comment]
well, this used to work up to yesterday

**Comment by BanzaiMan** [comment]
Matrix expansion code has not changed in months. Could you point to a build that worked?

**Comment by jcelerier** [comment]
Sure, this one : https://travis-ci.org/OSSIA/API/builds/192172510

I also had the same problem on [another project](https://travis-ci.org/OSSIA/i-score/jobs/192627515), that uses the docker infrastructure : I started being greeted by `docker: command not found` while it used to work just before.

**Comment by BanzaiMan** [comment]
@jcelerier I misspoke. The code did change. We will take a look. Sorry about the confusion there.

**Comment by BanzaiMan** [comment]
@jcelerier We've rolled back the change now. Could you try pushing a new commit to verify that it is working for you now?

**Comment by jcelerier** [comment]
Yes, my builds run on trusty now. thanks !

**Comment by carlad** [comment]
Hi @jcelerier I've deployed another change to remove :dist and :group from osx jobs. Please reopen this issue if you see any of your previous problems appearing as a result :)
