### ISSUE TITLE
UI issue on travis-ci.org

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#7168]
![image](https://cloud.githubusercontent.com/assets/20478546/22017934/40d927b4-dca4-11e6-9d21-41795f1944d9.png)
https://travis-ci.org/LolexOrg/Lolex-Tools/builds/192640374

**Comment by BanzaiMan** [comment]
What UI issue do you want to discuss?

**Comment by Monkeyboy2805** [comment]
The seconds is rather squashed underneath the number

**Comment by Monkeyboy2805** [comment]
Not sure if this is just a rendering issue due to the size of the browser window?

**Comment by BanzaiMan** [comment]
Could very well be. Does resizing the window affect the placement? I tested it with Safari, Chrome, and Firefox on the Mac, but didn't see this line break.

**Comment by Monkeyboy2805** [comment]
OK

**Comment by Monkeyboy2805** [comment]
Maybe have an auto-rerender???

**Comment by BanzaiMan** [comment]
What is the status here? Is window resizing effective? Have you tried other browsers to see if the problem exists on them?

**Comment by Monkeyboy2805** [comment]
@BanzaiMan One sec, I'll check it out once I start my next build.
