### ISSUE TITLE
Notification emails never received by Google Group members

### ISSUE THREAD

**Issue by remidenele** [travis-ci/travis-ci#7169]
I am having no luck to get Travis notification emails received by a Google Group.
Here is the dedicated config section set in the .travis.yml file:
 
```notifications:
  email:
    recipients:
      - google-group-name@ourGSuiteDomain.com
  on_success: always
  on_failure: always
```

For what I have done and tested so far:

- I set the Google Group to be entirely public (anyone is allowed to post)
- I added the Group email address to my Github account, the email has been verified 
(it is not the primary email)
- I added builds@travis-ci.com as a member of the group
- I tested to join to the group with a user outside of our G-Suite domain, and I am able to send emails to the group. Emails are received by all the group members
- I added my email address in addition to the group one in the `recipients` section in .travis.yml. 
In that case I received the build notification email and can see that google-group-name@ourGSuiteDomain.com is present in the recipients (To) but nobody in the group received the email
- I read #2513, I don't know if it is related or if someone was able to make Google group members to receive emails from Travis after that

Thanks!

**Comment by BanzaiMan** [comment]
I tend to think this is a duplicate of #2513.

**Comment by remidenele** [comment]
Hi, just to keep you informed that it suddenly started to work but have not yet figured out why, as no changes have been done to the configuration nor the group. Maybe depending on the mail sender server?
