### ISSUE TITLE
Repository changed ownership on Github; can't delete from my Travis.

### ISSUE THREAD

**Issue by g105b** [travis-ci/travis-ci#7171]
I was an admin of a project, used Travis to automate the tests. The project changed ownership on Github and I was removed as admin. Now I can't delete the builds from showing up in my feed.

Repo: rquadling/bower-installer
My username: g105b

**Comment by BanzaiMan** [comment]
This is basically a duplicate of #987.

**Comment by g105b** [comment]
I have successfully deleted other repos, but I can't do this one due to ownership change. That's why I thought there would be reason to raise a new issue.
