### ISSUE TITLE
Waiting for the build to start

### ISSUE THREAD

**Issue by sarangan12** [travis-ci/travis-ci#7172]
I have created the PR https://github.com/Azure/azure-sdk-for-ruby/pull/656 which created the Travis CI Job: https://travis-ci.org/Azure/azure-sdk-for-ruby/builds/192833835 

I have created the PR an hour back. But the job has not started. I have closed and reopened the PR (in the hope that it might trigger a new job). That did not happen.

Can someone help me? Also, if you can tell if the root cause is something that I have done, I could avoid this in the future. Thanks in advance.

**Comment by BanzaiMan** [comment]
Azure is a huge organization, and a long build queue. Azure/azure-sdk-for-ruby shares this queue with other repositories, including Azure/azure-cli, which has many builds queued up. There are about 40 jobs ahead of your PR build.

It will start in time. Please be patient.

**Comment by acnagy** [comment]
Hey @sarangan12 - I made a couple temporary tweaks to help Azure’s builds process a little faster - fingers-crossed you won’t have to wait too long…

**Comment by BanzaiMan** [comment]
The build ran.

**Comment by sarangan12** [comment]
@BanzaiMan The build is stuck again from yesterday night. Is this also related to the huge organization? Does Travis have any recommended best practice or patterns to maintain the organization structure and avoid these kinds of bottlenecks?

**Comment by BanzaiMan** [comment]
@sarangan12 Which job is stuck?

There is currently no way to know how many jobs are queued for an organization. Sorry.

**Comment by sarangan12** [comment]
@BanzaiMan  The PR is https://github.com/Azure/azure-sdk-for-ruby/pull/656. The Job link is not appearing in the PR. 

Thanks for the info on queued jobs. Any idea on the patterns/recommendations?

**Comment by BanzaiMan** [comment]
@sarangan12 Sorry for the trouble. I looked at the logs and found that when the latest commit for the PR (https://github.com/Azure/azure-sdk-for-ruby/pull/656/commits/2bc4c48ba88150facb9384e51390da4ff604ab92) was pushed, we had DB connectivity issue, and could not configure the build. Could you push another commit to the topic branch?

Thanks.

**Comment by sarangan12** [comment]
@BanzaiMan Thanks, That worked
