### ISSUE TITLE
R package cache

### ISSUE THREAD

**Issue by larskotthoff** [travis-ci/travis-ci#7173]
We're using the R package cache in our builds (https://travis-ci.org/mlr-org/mlr) heavily. Without the cache, we hit the 50 minute timeout (yes, we need a lot of packages to be installed).

The recent upgrade of R in Travis invalidated the cache and we now have to start from scratch. The problem is that the cache is only populated by successful builds and we time out every single time (not even close to succeeding). We've tried some things to reduce the build time, but were unsuccessful.

Is there a way to pre-populate the cache with a list of packages, or a special job that can be run for this purpose? The alternative for us would be to manually reduce the number of packages and iterate until we have enough successful builds that the cache contains a sufficient number of packages that the main build succeeds again. Needless to say, this would be a huge pain (especially as we would have to redo this every time the R version is upgraded).

 @craigcitro @hadley @jimhester

**Comment by BanzaiMan** [comment]
@larskotthoff Hello. The build timeout is not something that community volunteers can control.

What sort of timeout are you talking about in the initial cache setup?

**Comment by larskotthoff** [comment]
To be honest I'm not sure what we would need, but something like 1.5 hours should be sufficient.

I'm not asking for the build timeout to be changed, but if there's a way to populate the package cache without having a successful build of the project itself.

**Comment by BanzaiMan** [comment]
@larskotthoff If the build *finishes* without getting killed by the worker, the cache should be uploaded. This should allow partial and slow progress towards a complete cache. I think this is a cumbersome task to repeat. If you are not using the Mac (which is already short on resources), I think extending the timeout is OK here.

**Comment by BanzaiMan** [comment]
@larskotthoff It'll be a small update on the backend. :-)

**Comment by larskotthoff** [comment]
That would be great :)

**Comment by BanzaiMan** [comment]
@larskotthoff I've set the build timeout for mlr-org/mlr at 100 minutes. Please use this awesome power responsibly.

I'm closing this now.

**Comment by larskotthoff** [comment]
Thank you very much! You've saved us a huge headache.

**Comment by larskotthoff** [comment]
@BanzaiMan We're running into issues with the "no output received for 10 minutes now". Is there a way to increase this as well? Thanks!
