### ISSUE TITLE
Can't deactivate webhook

### ISSUE THREAD

**Issue by vmalloc** [travis-ci/travis-ci#7174]
Tried deactivating the Travis hook through the web interface for `vmalloc/dessert`, but it won't switch off. I have since removed the hook from the GitHub settings themselves. How can I restore things to a working state?

**Comment by BanzaiMan** [comment]
Looks like it's working now. https://travis-ci.org/vmalloc/dessert/builds/193020702

Were you able to work this out on your own?

**Comment by vmalloc** [comment]
Yes, just waited a bit and it got working again. Thanks!
