### ISSUE TITLE
My Travis project doesn't get requests

### ISSUE THREAD

**Issue by mcapuccini** [travis-ci/travis-ci#7175]
Hello! From this morning my Travis project (https://travis-ci.org/kubenow/KubeNow) stopped to get requests from GitHub when I push a new commit or a new branch. As a result the new features don't get built. 

This are the commits on GitHub:

![screen shot 2017-01-18 at 10 04 03](https://cloud.githubusercontent.com/assets/1671397/22057586/9e1fb37c-dd65-11e6-984c-53c0281c82e0.png)

And this is the requests page on Travis:

![screen shot 2017-01-18 at 10 06 01](https://cloud.githubusercontent.com/assets/1671397/22057616/c4bd3036-dd65-11e6-93e3-4939b0e10269.png)

Last two commits are not visible in the requests. I get the same problem on branch pushes.

**Comment by mcapuccini** [comment]
Actually is getting requests, but very slowly

**Comment by Monkeyboy2805** [comment]
This may be because there is something dodgy about your builds, so they banned them?

**Comment by mcapuccini** [comment]
@Monkeyboy2805 it started to work again. I am kipping this open in case you want to do some debug.

**Comment by Jean85** [comment]
Maybe this was the cause? https://www.traviscistatus.com/incidents/95zwr8ytldkb

**Comment by BanzaiMan** [comment]
Indeed, it was due to slow processing as indicated. Sorry for the troubles.
