### ISSUE TITLE
Docker not available

### ISSUE THREAD

**Issue by Jean85** [travis-ci/travis-ci#7177]
I followed the instructions in the docs to use Docker in my builds, but [it says](https://travis-ci.org/facile-it/crossbar-http-publisher-bundle/jobs/193015017#L126):

    $ sudo service docker start
    docker: unrecognized service

I was [able to fix](https://travis-ci.org/facile-it/crossbar-http-publisher-bundle/jobs/193017950#L237) it only adding this to the `.travis.yml`:
```yaml
env:
  DOCKER_COMPOSE_VERSION: 1.8.1
```

Obviously the specific version doesn't matter, but the docs don't tell you that this env variable is needed to make Docker work.

**Comment by BanzaiMan** [comment]
The reason that this job https://travis-ci.org/facile-it/crossbar-http-publisher-bundle/jobs/193015017#L126 failed is that it was sent to the precise image for some reason, despite having `services: [ docker ]`. The fix is most likely not due to `DOCKER_COMPOSE_VERSION`, but the correct routing to the Trusty image.

It is not clear to me why the first job was configured wrong.

**Comment by Jean85** [comment]
It seems that the configuration is correct only on the first job, see next build: https://travis-ci.org/facile-it/crossbar-http-publisher-bundle/builds/193054479

**Comment by Jean85** [comment]
Still happening: https://travis-ci.org/facile-it/crossbar-http-publisher-bundle/jobs/193939234
I've removed the `DOCKER_COMPOSE_VERSION` and now all the matrix is failing

**Comment by BanzaiMan** [comment]
Try:

```yaml
dist: docker
```

instead of

```yaml
services:
  - docker
```

**Comment by Jean85** [comment]
It seems to have fixed the issue.

The build is failing and very slow, maybe due to the pulling of the image... Can I cache that? Or Travis does that behind the curtains?

**Comment by BanzaiMan** [comment]
Ooops. I meant `dist: trusty`. Either way, I think the routing is a little off.

Currently there is no way to cache Docker images.

**Comment by Jean85** [comment]
Ok, fixed! But the build is working anyway, it was failing previously because I did a mistake, I didn't wait for the containerized app to be ready. Thanks, ask away if you need any more help do diagnose this issue.

**Comment by BanzaiMan** [comment]
I don't think there is much left to do here.
