### ISSUE TITLE
Deleted tag keeps triggering a release

### ISSUE THREAD

**Issue by victorhurdugaci** [travis-ci/travis-ci#7184]
I had a tag called `0.0.0-dev` at some point in the past and I triggered a few test releases with it. Then I deleted the tag but now every time travis does a build it also triggers a build for that deleted tag, recreating the tag and pushing a build with from it....

Here's my build history;
https://travis-ci.org/victorhurdugaci/ruready/builds 

You can see that after every build there's that `0.0.0-dev` build.

Is there a way to force refresh the travis repo/tags cache?

I've also opened and then closed this issue: https://github.com/travis-ci/travis-ci/issues/7183 Not sure if the repro is 100% reliable but that's what I did

**Comment by BanzaiMan** [comment]
How are you pushing your commits to GitHub? If you edit a file on github.com directly, does the tag get built?

I tried the following sequence on my repo, and was unable to reproduce this.

```sh-session
$ git tag foo -f
Updated tag 'foo' (was fe2b71b)
$ git push origin default --tags
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:BanzaiMan/travis_production_test.git
 * [new tag]         foo -> foo
$ git push origin default :foo
To git@github.com:BanzaiMan/travis_production_test.git
 - [deleted]         foo
$ git push origin default
Everything up-to-date
$ git commit --allow-empty -m "empty"
[default 2dc7c33] empty
$ git push origin default
Counting objects: 1, done.
Writing objects: 100% (1/1), 183 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To git@github.com:BanzaiMan/travis_production_test.git
   df866bb..2dc7c33  default -> default
```

![builds_-_banzaiman_travis_production_test_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/22091834/387fc702-ddc7-11e6-8da4-31a51986432c.png)

**Comment by victorhurdugaci** [comment]
As expected, it was my fault :) My build script was incorrectly assigning the `TRAVIS_TAG` env variable
