### ISSUE TITLE
Committer avatar is authored avatar

### ISSUE THREAD

**Issue by rixx** [travis-ci/travis-ci#7188]
I recently had a pull request merged, which resulted in me being the commit author, but the merging person being the committer. Travis displays this nicely in its view of the build, but it displayed my avatar twice instead of showing the committer's avatar.
![2017-01-19-163416_502x42_scrot](https://cloud.githubusercontent.com/assets/2657547/22113130/9550ded2-de65-11e6-85a0-955dc78ff945.png)

**Comment by BanzaiMan** [comment]
Where do you see this?

**Comment by rixx** [comment]
In the view of the build. The build in question is build [1405](https://travis-ci.org/pretix/pretix/builds/193330114) of the [pretix](https://github.com/pretix/pretix) project.

**Comment by BanzaiMan** [comment]
Thanks for the link. We have an internal issue to track it.

**Comment by BenWiederhake** [comment]
Still occurs: 
![bildschirmfoto_2017-02-24_22-40-36](https://cloud.githubusercontent.com/assets/2690845/23322142/e1316166-fae2-11e6-999c-7235ccb82527.png)

Not sure if related, but also looks fishy:
![bildschirmfoto_2017-02-24_22-41-36](https://cloud.githubusercontent.com/assets/2690845/23322162/f87b7ae6-fae2-11e6-8a90-4b49ee6bbfeb.png)
That's the same mail address three times, so I'm not sure why it's a different icon.

**Comment by rixx** [comment]
Confirmed fixed. Cool bot you have there!
