### ISSUE TITLE
trusty image outdated php nightly

### ISSUE THREAD

**Issue by Stricted** [travis-ci/travis-ci#7194]
for the php extension `ui` we need to test the build against 7.2 (currently nightly build)
but unfortunately the 7.2 build is too old (built: Nov 21 2016 22:47:47)
is it possible to update the nightly build/version?
for the libui dependency we need the trusty distribution because it requires cmake >= 3.0.0

https://github.com/krakjoe/ui/pull/27
https://travis-ci.org/krakjoe/ui/builds/193680088
https://travis-ci.org/Stricted/ui/jobs/193678659
https://github.com/andlabs/libui

**Comment by BanzaiMan** [comment]
Nightly builds on Trusty has been failing. See, for example, https://travis-ci.org/travis-ci/php-src-builder/jobs/193544776.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/3616#issuecomment-262283564.

**Comment by BanzaiMan** [comment]
I have disabled the problematic bits of the PHP nightly builds for Trusty (see the issue linked above). I'm closing this now, since the Trusty nightly is now up to date (albeit in a slightly different configuration).
