### ISSUE TITLE
run distutils to create an RPM?

### ISSUE THREAD

**Issue by jose-caballero** [travis-ci/travis-ci#7196]
Hi,

I know this is a question more than an issue, and therefore I shouldn't use this channel for it. My apologies, in advance. I did try to find some info in google, but I didn't get coherent input. 

So, here is the question. I tried to get TRAVIS to just run command "python setup.py bdist_rpm". My goal was to build the RPM out of python code periodically. It failed. Apparently TRAVIS does not run on RedHat (or compatible) OS. So command rpmbuild is not available.
Is there a way to make TRAVIS to build RPMs from the code in the github repo?

Thanks a lot in advance.
Jose

**Comment by BanzaiMan** [comment]
Our builds run on Ubuntu, or the Mac. https://docs.travis-ci.com/user/ci-environment/

If you need an RPM-based distro, I believe you can do that with [Trusty](https://docs.travis-ci.com/user/trusty-ci-environment/), which allows the use of Docker.

**Comment by jose-caballero** [comment]
OK. I will investigate it. Thanks a lot!
I think it is fair to close this issue. 

Cheers,
Jose
