### ISSUE TITLE
GLX extension not available in node trusty image

### ISSUE THREAD

**Issue by jfirebaugh** [travis-ci/travis-ci#7198]
With `dist: trusty` and `language: cpp`, the GLX extension is available under xvfb. With `language: node`, `glxinfo` fails.

* [Test repo](https://github.com/mapbox/travis-glx-test)
* [Passing commit](https://github.com/mapbox/travis-glx-test/commit/0cea8e1a185b05e30636178659773e399b5b69fd), [build](https://travis-ci.org/mapbox/travis-glx-test/builds/193871578)
* [Failing commit](https://github.com/mapbox/travis-glx-test/commit/7d9b7be120ffa7341721b305e33f988771497c12), [build](https://travis-ci.org/mapbox/travis-glx-test/builds/193869899)

Expected behavior is that GLX is available under both images.

**Comment by jfirebaugh** [comment]
This seems to be a repeat of https://github.com/travis-ci/packer-templates/issues/220 / https://github.com/travis-ci/travis-ci/issues/6508: the node image has the fglrx package installed, and purging it fixes the issue.

**Comment by BanzaiMan** [comment]
@meatballhat Could you take a look?
