### ISSUE TITLE
sbt starts reporting exit value zero even when it fails to build, resulting in false positive

### ISSUE THREAD

**Issue by Sciss** [travis-ci/travis-ci#7212]
Examples: 

- https://travis-ci.org/Sciss/Mellite/jobs/194861060
- https://travis-ci.org/Sciss/FScape-next/jobs/194861057
- https://travis-ci.org/iem-projects/sysson/jobs/194861109

All of these jobs fail to download dependencies, e.g. with

> sbt.ResolveException: unresolved dependency: de.sciss#fscape_2.12;2.6.0-SNAPSHOT: not found

And thus these builds should fail. But travis says the sbt script exited with code zero and marks the jobs as successful. So it seems the sbt script was broken somehow.

**Comment by BanzaiMan** [comment]
We currently fetch https://raw.githubusercontent.com/paulp/sbt-extras/b9c8cb273d38e0d8da9211902a18018fe82aa14e/sbt and use it as `sbt` command. If the command is misbehaving, then the issue should be fixed upstream.

I looked at https://github.com/paulp/sbt-extras/compare/b9c8cb2...4ad1b8a but I don't see any changes that fix this issue.

**Comment by BanzaiMan** [comment]
When the upstream issue is fixed, we can update the SHA for `sbt`.

**Comment by ipa-mdl** [comment]
https://github.com/travis-ci/travis-build/commit/12ac41dfc22346d2d5489540bad04f169fbf66d9#commitcomment-20594568

**Comment by BanzaiMan** [comment]
The offending PR (https://github.com/travis-ci/travis-build/pull/939) has been reverted, so this should be working again.
