### ISSUE TITLE
PHP 7.0 is missing on Precise

### ISSUE THREAD

**Issue by acnagy** [travis-ci/travis-ci#7213]
There have been some reports of `php 7.0` being missing on Precise images. An example build can be found [here](https://travis-ci.org/BanzaiMan/travis_production_test/builds/194894218). However, for reference, affected jobs have logs along these lines:

```
phpenv global 7.0 2>/dev/null

K$ phpenv global 7.0
rbenv: version `7.0' not installed

K$ composer self-update 1.0.0
Updating to version 1.0.0.
    Downloading: connection...    Downloading: 100%         
Use composer self-update --rollback to return to version 1d8f05f1dd0e390f253f79ea86cd505178360019

K$ composer self-update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Updating to version 1.3.1.
    Downloading: Connecting...    Downloading: 100%         
Use composer self-update --rollback to return to version 1.0.0

K$ php --version
PHP 5.6.5 (cli) (built: Feb 12 2015 01:41:10) 
```
We're currently investigating this and will update the issue with more information as it becomes more available.

**Comment by gabehesse** [comment]
👍 this is blocking our entire company. Please address.

**Comment by BanzaiMan** [comment]
The offending PR (https://github.com/travis-ci/travis-build/pull/939) has been reverted, so this should be working again.

Please confirm.

**Comment by sagerman4** [comment]
The issue appears to be fixed for our builds.  Thanks!

**Comment by BanzaiMan** [comment]
Thank for the confirmation. Again, I am sorry for the troubles.

I'm closing this now.
