### ISSUE TITLE
Tests returning Exit status 1, but travis reported the test command exited with 0 creating false positive results.

### ISSUE THREAD

**Issue by jlai403** [travis-ci/travis-ci#7214]
https://travis-ci.com/QuickEstate/QuickEstate/builds/38632015

<img width="980" alt="screen shot 2017-01-24 at 10 39 07 am" src="https://cloud.githubusercontent.com/assets/3282127/22259131/61a8bff4-e221-11e6-8d22-83a757231334.png">

Line 4730 `The command "docker-compose -f ./docker-files/docker-compose.yml run frontend bash -c 'npm run test:karma'" exited with 0.`

**Comment by BanzaiMan** [comment]
The offending PR (https://github.com/travis-ci/travis-build/pull/939) has been reverted, so this should be working again.

**Comment by jlai403** [comment]
Re-ran the build and tests failed 👍🏻

**Comment by BanzaiMan** [comment]
Thanks for the confirmation, and sorry for the troubles.

Closing this now.
