### ISSUE TITLE
Checksum Validation failing on Travis Machines

### ISSUE THREAD

**Issue by sarangan12** [travis-ci/travis-ci#7216]
Ref Job: https://travis-ci.org/Azure/azure-sdk-for-ruby/jobs/194597025 

While running this job, it fails for ruby version 2.3.0 with the error message "Bundler cannot continue installing azure-core (0.1.6)." The reason is "The checksum for the downloaded `azure-core-0.1.6.gem` does not match the checksum given by the server. This means the contents of the downloaded gem is
different from what was uploaded to the server, and could be a potential security issue." 

When I try this locally I am able to install azure-core gem successfully. Is this is a problem with Travis servers? Could someone from Travis team take a look at this issue?

**Comment by BanzaiMan** [comment]
I suspect a corrupt cache. Please delete it and try again.

**Comment by sarangan12** [comment]
@BanzaiMan  How could we delete the cache on Travis machine?

**Comment by BanzaiMan** [comment]
Ah, sorry. I misspoke. There is no cache in play here. Not sure what's going on yet.

**Comment by sarangan12** [comment]
Any updates on this issue please?

**Comment by BanzaiMan** [comment]
Have you tried restarting this job?

**Comment by sarangan12** [comment]
Several times with no success

**Comment by sarangan12** [comment]
This is an issue with rubygems and not related to travis. Ref: https://github.com/rubygems/rubygems.org/issues/1551. Closing this.
