### ISSUE TITLE
Number of active / backlog builds is inconsistent on traviscistatus.com

### ISSUE THREAD

**Issue by jsmaniac** [travis-ci/travis-ci#7217]
Hello,

On https://www.traviscistatus.com/, the number of active and backlog builds (shown in grey in the corner of each item) does not match the number indicated on the graph, sometimes by a very large amount.

Here is a screenshot of the freshly-reloaded page, which consistently displays 125 active OS X builds, but the graph consistently says there are 128. Also, the grey text says that there are 500 builds in the OS X backlog, but the graph says there are 1216.

![jobs-number-inconsistency](https://cloud.githubusercontent.com/assets/299872/22272364/f3e38a2a-e299-11e6-8a70-2a6356d37142.png)

I'm in the Europe/Paris timezone, if that matters.

I can reproduce the issue with Firefox and Chrome, both on Linux (Nix OS)

**Comment by BanzaiMan** [comment]
"125" and "500" are averages over the period shown. It's a bit misleading, I agree, but that's what these figures are showing.
