### ISSUE TITLE
JRuby 9.1.5.0 on OSX does not have bundler

### ISSUE THREAD

**Issue by tagomoris** [travis-ci/travis-ci#7218]
When CI task runs `bundle install`, it fails with "bundle: command not found".
https://travis-ci.org/msgpack/msgpack-ruby/jobs/195039564

Same problem occurs on these environment:
* jruby-head on linux: https://travis-ci.org/msgpack/msgpack-ruby/jobs/195039565
* jruby-head on osx: https://travis-ci.org/msgpack/msgpack-ruby/jobs/195039569
* jruby-19mode on osx: https://travis-ci.org/msgpack/msgpack-ruby/jobs/195039562

`jruby-9.1.5.0` on linux seems to work well: https://travis-ci.org/msgpack/msgpack-ruby/jobs/195039563

**Comment by BanzaiMan** [comment]
Notice that, currently, RVM is preferring to pull JRuby 9.1.5.0 archive from jruby.org's archive (https://travis-ci.org/msgpack/msgpack-ruby/jobs/195039564#L47) instead of http://rubies.travis-ci.org. I suspect that the current images' provisioning process is also preferring jruby.org's to ours.

**Comment by BanzaiMan** [comment]
Hmmm. I don't see it in our archives (e.g., http://rubies.travis-ci.org/osx/10.11/x86_64/jruby-9.1.5.0.tar.gz) doesn't contain it, either.

**Comment by BanzaiMan** [comment]
I figured this out now.

The Linux image's `~/.rvm/gemsets/jruby/global.gemsets` contains `bundler` while the OS X image does not.
