### ISSUE TITLE
Travis sometimes ignores exit codes

### ISSUE THREAD

**Issue by fingolfin** [travis-ci/travis-ci#7220]
Apparently, sometimes Travis decides to ignore nonzero exit codes, resp. treats them as if they were zero. This leads to builds being marked as success when they were actually failures.

Here is an example of such a build: https://travis-ci.org/fingolfin/gap/jobs/194872862

Restarting the build usually fixes this. But I consider this a very serious bug, because it essentially means that we cannot trust Travis at all ; any succesful Travis run must be manually checked, by eyeballing the entire build logs, to make sure it really was a success.

**Comment by BanzaiMan** [comment]
Sorry for the troubles. There was a bad deployment that caused this issue (e.g., #7212, #7213, #7214). I suspect yours is the same. Please restart this build, and it should work as expected.

I'm closing this now optimistically, but if you restart it and still shows the problem, do let us know.
