### ISSUE TITLE
Jobs which are allowed fail were not when the said jobs were defined with `matrix.include`

### ISSUE THREAD

**Issue by cdepillabout** [travis-ci/travis-ci#7221]
Builds for my project in the `allow_failures` section have suddenly started to be required.  I have not changed my `.travis.yml` file.

Here is the last build that succeeded normally:

https://travis-ci.org/cdepillabout/pretty-simple/builds/195005295
 
Here is the first build where the `allowed_failures` section seemed to be ignored:

https://travis-ci.org/cdepillabout/pretty-simple/builds/195306639

Here is the `.travis-yml` file that was used for the two above builds.  It was not changed in between those two builds:

https://github.com/cdepillabout/pretty-simple/blob/90012e925dc448f5749003b833c035a08cc2ef8c/.travis.yml

Here is another user on twitter that seems to be having the same problem:
https://twitter.com/mwop/status/824332332165369856

**Comment by IchHabRecht** [comment]
Having exactly the same problem since hours. Is there any way to fix this asap?

**Comment by cdepillabout** [comment]
@IchHabRecht I'm not associated with travis-ci, but you could always just temporarily disable the builds that are under "allowed_failures" and currently failing.

**Comment by IchHabRecht** [comment]
Thing is, I'm trying to test the allow_failures option in that repo :-/

**Comment by photodude** [comment]
I'm also seeing this type of issue... HHVM is an allowed failure but it's now killing builds since it's showing up as required.
https://travis-ci.org/joomla-framework/database/builds/195300438

**Comment by photodude** [comment]
@BanzaiMan can we get this issue bumped up in severity?

**Comment by photodude** [comment]
Another REPO where multiple allow failures are showing up as required. Seems like it's definitely a platform issue. https://travis-ci.org/joomla/joomla-cms/builds/195347689

**Comment by greg0ire** [comment]
In my repo, only the build not matched inside "include" are not required (nightly and hhvm in [this file](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/.travis.yml#L67))

**Comment by greg0ire** [comment]
@photodude maybe move line 35 to line 51 ?

**Comment by photodude** [comment]
@greg0ire I'm not sure what you're suggesting.

**Comment by BanzaiMan** [comment]
Sorry about this issue, everyone. We had a bad deploy today.

While the code we deployed passed our specs admirably, this is a case where we missed in our specs and jobs were erroneously required. The bad bits have been rolled back. It should work as expected now, but you would have to push a new commit for the correct build configuration.

I'm keeping this open until the complete fix is deployed.

Let us know if you have further questions.

**Comment by greg0ire** [comment]
> @greg0ire I'm not sure what you're suggesting.

I was suggesting moving things that are under include to under allowed_failures, but nevermind, wrong idea apparently.

**Comment by greg0ire** [comment]
> you would have to push a new commit for the correct build configuration.

Or close and reopen the PR, it works too

**Comment by IchHabRecht** [comment]
hallelujah - thanks for fixing this so fast! Works for my repo :-)

**Comment by cdepillabout** [comment]
@BanzaiMan Thanks for the quick fix!

**Comment by BanzaiMan** [comment]
@cdepillabout Not so fast! I'll deploy the new code some time next week with specs for this case and a fix for it. Thank me then. 😉

**Comment by BanzaiMan** [comment]
Hi, everyone, we've just deployed again the PR (with fixes, of course!) which caused this error. The jobs should now be marked correctly with respect to `allow_failures`, and the jobs allowed to fail should have higher job numbers than those that aren't.

I'm closing this issue optimistically (with a couple of small tests), but please let us know if you see problems.

Thank you!

**Comment by photodude** [comment]
Thank you @BanzaiMan
