### ISSUE TITLE
PHPUnit ^5.7.6 on PHP 5.6 throws call to undefined method error

### ISSUE THREAD

**Issue by jonnypickett** [travis-ci/travis-ci#7226]
A recent [patch](https://github.com/sebastianbergmann/phpunit/commit/8a02e9f4411a8cdcd8ddfdc6ecfb86b0b64454bb) in PHPUnit now causes the error below to be thrown when tests are run on PHP 5.6

```
PHP Fatal error:  Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration()
```

I will force PHPUnit 5.7.5 in my builds until a fix is released. I feel like this is more a problem with PHPUnit, but just wanted to give you all a heads up. 

[Here](https://travis-ci.org/jonnypickett/eloquent-sti/jobs/195075768) is an example from my most recent build.

**Comment by jonnypickett** [comment]
Just in case anyone else finds themselves in the same situation, here is what I added to my .travis.yml 

```
before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require --dev --no-update phpunit/phpunit 5.7.5; fi
```

Everything is back to green.

**Comment by jonnypickett** [comment]
Actually look here at phpunit issue [2432](https://github.com/sebastianbergmann/phpunit/issues/2432) for some real illumination.

Using `vendor/bin/phpunit` instead of the global phpunit fixed the issue. No need for the before_install configuration above. Just add this instead.

```
script:
  - vendor/bin/phpunit
```

**Comment by andig** [comment]
@jonnypickett imho this issue should not be closed:

  - travis (apparently?) upgraded global phpunit version
  - global phpunit version throws error -> this is a travis issue
  - using locally installed version works -> so not phpunit issue

If the global phpunit is broken it should be fixed. If it should not be used at all (as phpunit claims) it shouldn't be installed at all.

**Comment by jonnypickett** [comment]
All good points, @andig. The default Travis script probably should be calling the local phpunit if it exists instead of a global version. Reopening and leaving it to Travis to decide how they want to proceed.

**Comment by BanzaiMan** [comment]
Our archives do come with phpunit, which is current at the time of packaging. Faulty versions do get released from time to time, unfortunately. As new versions are packaged and deployed, the issues will eventually be eradicated.

The preference to use the "locally installed" version is an interesting one; it is presumably a matter of setting up `$PATH`, but unless there is a universally accepted location for this, tinkering with `$PATH` on our side is probably more confusing than beneficial (because the users will not know where `phpunit` is coming from).

**Comment by andig** [comment]
@BanzaiMan as-is packaged phpunit is borked. No problem with the package as such but then it should imho be fixed, outside of the regular image release cycle ;)

**Comment by BanzaiMan** [comment]
Pre-installed runtimes that you get by specifying `X.Y` (e.g., `5.6`, as opposed to `5.6.30`) will not be updated outside of the regular release cycles.

**Comment by andig** [comment]
Imagine you had a broken php- same thing? No emergency fix procedure? 

Please don't get me wrong, I love travis!

**Comment by neomerx** [comment]
adding phpunit to dev dependencies in `composer.json`
```json
  "require-dev": {
    "phpunit/phpunit": "^4.6 || ^5.0"
  }
```
and running phpunit from `.trvavi.yml` from local vendor fixes the problem
```.yml
script:
- vendor/bin/phpunit
```

**Comment by sebastianbergmann** [comment]
Re: https://github.com/travis-ci/travis-ci/issues/7226#issuecomment-275465487

No, the packaged PHPUnit is not broken. Your way of using PHPUnit on Travis is broken. If you install PHPUnit as a dependency via Composer then you must not use globally-installed `phpunit` to invoke PHPUnit.

**Comment by andig** [comment]
@sebastianbergmann that makes perfect sense- thanks for clarifying.

**Comment by BanzaiMan** [comment]
OK, so this is a documentation issue?

**Comment by jonnypickett** [comment]
I'm sorry for any confusion. I assumed people would click on the issue link in my comment above where what @sebastianbergman just explained here was already explained. There is no issue with phpunit. This "issue" is only still open, imo, for Travis to decide if they want to find some way to mitigate what is actually a user error. Please feel free to close this whenever you'd like. As far as I'm concerned there is no issue, as I have my Travis script call my local phpunit dependency, which as stated previously is the correct way to execute phpunit.

**Comment by malc0mn** [comment]
What? No idea why there is a reference to this issue here simply because (for personal reference) I included a link to a specific comment in this thread.

That was not my intention, but thanks @neomerx and @sebastianbergmann for the clarification (feeling quite silly that I didn't spot it myself).

**Comment by BanzaiMan** [comment]
Am I correct to understand that, under certain circumstances, it is problematic to provide a version of PHPUnit on our PHP builds? Or is there something we can do to improve this experience?

**Comment by neomerx** [comment]
@BanzaiMan I'd rather say projects typically expect latest PHPUnit however by default travis has not the latest one. In this case your pick for built-in PHPUnit was unlucky which led to troubles.

**Comment by neomerx** [comment]
@BanzaiMan IMHO it would be reasonable to encourage (in official documentation) developers to specify PHPUnit version they want to test on in `composer.json` and run it from `vendor` folder. Also a default backup globally installed PHPUnit could also be in place however it should be stated that it's not possible to guarantee compatibility for all tests.

**Comment by BanzaiMan** [comment]
@neomerx Thanks for the explanation.

It seems to me that the current behavior is reasonable; we package the latest PHPUnit at the time we create the archives. Sometimes such releases are bad, and needs to be updated, depending on the need.

This can be better documented, for sure.

**Comment by elrido** [comment]
Not sure if I should create a separate issue for this or if this is the same problem.

Starting this week our travis builds started failing, but only on PHP 7.0. We are using the global phpunit and do (currently) not depend on a composer installed one.

Here is the error I am getting in the job output:
```
$ cd tst && phpunit
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /home/travis/build/PrivateBin/PrivateBin/tst/ConfigurationTest.php on line 5
PHP Stack trace:
PHP   1. {main}() /home/travis/.phpenv/versions/7.0.16/bin/phpunit:0
```
It sounds like the autoloader does not find the phpunit includes anymore?

Here is a job with the problem for reference:
https://travis-ci.org/PrivateBin/PrivateBin/jobs/210005224

**Comment by neomerx** [comment]
@elrido It't not related. Try to inherit from `PHPUnit\Framework\TestCase`. Should be fine then.

**Comment by dregad** [comment]
PHPUnit 6.x [introduced namespaces](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0#backwards-compatibility-issues), and consequently the classes names changed. This obviously means that tests written for older versions won't work any more.

Since we still need to provide support on older versions of PHP, we can't simply convert the unit tests to be compatible with PHPUnit 6.x namespaces at this time; we can't use the forward-compatibility layer in 5.7 either, because that's [incomplete and won't be expanded](https://github.com/sebastianbergmann/phpunit/issues/2503#issuecomment-279703999), and we also don't want to maintain 2 separate sets of our unit tests.

It would therefore be nice if Travis could allow users to choose which PHPUnit version they wish to run. But if that's not possible, improving documentation to help users understand how they can do it manually would be nice.

**Comment by BanzaiMan** [comment]
Is the path to which composer installs binaries fixed? If so, does it make sense to check for `phpunit` there? That is to say,

```sh
if [[ -x $TRAVIS_BUILD_DIR/vendor/bin/phpunit ]]; then
  $TRAVIS_BUILD_DIR/vendor/bin/phpunit
else
  phpunit
fi
```

**Comment by dregad** [comment]
> Is the path to which composer installs binaries fixed? 

No. It is defaulted, but can be changed, see [https://getcomposer.org/doc/articles/vendor-binaries.md#can-vendor-binaries-be-installed-somewhere-other-than-vendor-bin-](Composer doc for vendor binaries).

**Comment by BanzaiMan** [comment]
@dregad Thanks for the information. It seems to me, then, it is up to the user to invoke the correct `phpunit`, and what remains to do here is to document this behavior.

**Comment by dregad** [comment]
Not perfect, but good enough for me.

**Comment by BanzaiMan** [comment]
Well, it is not impossible to check these small number of configuration possibilities. In my testing, `COMPOSER_BIN_DIR` appears to take precedence over `composer.json`, so we could try going down the list:

```sh
if [[ -n $COMPOSER_BIN_DIR && -x $COMPOSER_BIN_DIR/phpunit ]]; then
  $COMPOSER_BIN_DIR/phpunit
elif [[ -n $(jq -r '.config["bin-dir"]' composer.json) && -x $(jq -r '.config["bin-dir"]' composer.json)/phpunit ]]; then
  $(jq -r '.config["bin-dir"]' composer.json)/phpunit
elif [[ -x $TRAVIS_BUILD_DIR/vendor/bin/phpunit ]]; then
  $TRAVIS_BUILD_DIR/vendor/bin/phpunit
else
  phpunit
fi
```

**Comment by dregad** [comment]
Better :+1: 

Maybe improve performance by storing `jq -r '.config["bin-dir"]' composer.json` in a variable instead of calling it 3 times.

**Comment by BanzaiMan** [comment]
The `phpunit` discovery logic has now changed to accommodate the way Composer does. If you are overriding `install` just to get around this, you should be able to drop it now.

Thank you!

**Comment by jhdxr** [comment]
@dregad phpunit 4.8.35 has introduced a forward compatibility layer so the namespace was supported as well.

**Comment by dregad** [comment]
@jhdxr I know, but unfortunately its coverage is limited (and not sufficient for my purposes), and it won't be expanded (see sebastianbergmann/phpunit#2418)
