### ISSUE TITLE
JDK_HOME undefined

### ISSUE THREAD

**Issue by gchauvet** [travis-ci/travis-ci#7229]
My project required JDK_HOME environment variable to find jni.h in a particular cross-compilation case. Unfortunately, JDK_HOME remind undefined according to provided information from #7019 
Tested with Trusty, Precise, with and without sudo mode. (I use OpenJDK7 only)

Link [to my jobs](https://travis-ci.org/gchauvet/commons-daemon)

Best regards

**Comment by BanzaiMan** [comment]
What is `$JDK_HOME`? Do you mean `$JAVA_HOME`?

**Comment by gchauvet** [comment]
AFAIR, JRE is pointed by the JAVA_HOME and the JDK is pointed by JDK_HOME.

Now if I look logs : 
```
$ jdk_switcher use openjdk7
Switching to OpenJDK7 (java-1.7.0-openjdk-amd64), JAVA_HOME will be set to /usr/lib/jvm/java-7-openjdk-amd64
```
Seems good (include/lib available in this directory). I try with JAVA_HOME.

**Comment by gchauvet** [comment]
I close this ticket because this issue is due to a malformed cmake access to the JAVA_HOME environment variable....
