### ISSUE TITLE
Login impossible on Webinterface

### ISSUE THREAD

**Issue by bebehei** [travis-ci/travis-ci#7230]
I'm unable to login with the user `bebehei` on https://travis-ci.org.

On travis-ci.org after getting forwarded to github.com's oauth-page, after I get forwarded to travis-ci.org again I get stuck on the URL `https://api.travis-ci.org/auth/handshake?code=fb77b7db7c7146cb00a6&state=paftl6_xJyqw7DjH4LMGvQ%3A%3A%3Ahttps%3A%2F%2Ftravis-ci.org%2Fbebehei%2Farchlinux-docker` and I just get a blank page.

- Ironically it works fine on https://travis-ci.com.
- Travis CLI also works fine with my account and a personal token.
- I created a 2nd github account to test it and it works fine with this one.

It would be great, if someone could dig into this deeper. I don't know how to debug this further.

**Comment by bebehei** [comment]
As far as I can see, yes. Chromium waits inifinitely.

**Comment by bebehei** [comment]
More info on this:

I'm using Firefox Nightly by default. I also tested the normal Firefox 50 and both have the same behavior.

As I said, it works with freshly created accounts. Also I have not been logged in to travis the last year. I bet it's a problem with my user-data, which is processed incorrectly in background.

**Comment by bebehei** [comment]
> Chromium waits inifinitely.

At least after some minutes it stops and gives HTTP 500 Error telling me:

> Something went wrong
It looks like something went wrong with your request.
Please try again later.

**Comment by BanzaiMan** [comment]
Thanks for the extra information. We'll take a look.

**Comment by drogus** [comment]
I suspect that it might be a problem with your OAuth token that we don't handle properly. Could you go to [applications](https://github.com/settings/applications) list and revoke access for Travis CI and then try logging in again?

**Comment by bebehei** [comment]
I already tried this a few times.

**Comment by bebehei** [comment]
It's getting awkward now: After trying https://bd-overeager-newlines.test-deployments.travis-ci.org/ (referenced in another issue). I logged in there, and tadaaa: It works now on travis-ci.org again.

I bet the bug is not fixed, but it actually resolved my issue.
