### ISSUE TITLE
Old project that was turned off now won't trigger

### ISSUE THREAD

**Issue by jadekler** [travis-ci/travis-ci#7232]
We're trying to get a project that used to be on travis ci back on travis ci. The project is [pivotal-cf/pivotal-ui](https://github.com/pivotal-cf/pivotal-ui). I have re-checked 'Build pushes' and 'Build pull requests', but no commit on the `development` branch (`development` is default, `master` is reserved for CI) works. When I schedule a daily cron, though, it kicks off with a build of the `development` branch.

Any ideas what the heck?

![screen shot 2017-01-27 at 1 50 45 pm](https://cloud.githubusercontent.com/assets/3584893/22387230/d1450aca-e497-11e6-8581-c4c3d81a134c.png)

**Comment by BanzaiMan** [comment]
Go to https://travis-ci.org/profile/pivotal-cf and deactivate/activate pivotal-ui, please. The commits that you've pushed have now been missed, so you need to push a new one.

**Comment by jadekler** [comment]
Thanks @BanzaiMan

**Comment by BanzaiMan** [comment]
I see that it's running now.

**Comment by jadekler** [comment]
@BanzaiMan I used the cron thing again, but I'll give a shout if disabling/re-enabling doesn't fix it (as soon as our PM is back from lunch!)
