### ISSUE TITLE
Cannot login on travis-ci.org with GitHub

### ISSUE THREAD

**Issue by ale5000-git** [travis-ci/travis-ci#7234]
In the past it was working correctly.
Now I go to https://travis-ci.org/ and click on "Sign in with GitHub", then I see just a blank page.
After refreshing it say "could not resolve github token", please fix it.

**Comment by bebehei** [comment]
Same on #7230

**Comment by bebehei** [comment]
@ale5000-git 

- Are you able to login via travis-ci.**com**?

**Comment by ale5000-git** [comment]
@bebehei: No, I have the same problem on both site.

**Comment by bebehei** [comment]
Still not possible to login?

If not, have a look at #7230

**Comment by ale5000-git** [comment]
Afet various test I have discovered the problem, apparently the [KeepVid Helper](http://es.keepvid.com/userscript/keepvid-helper.user.js) greasemonkey script prevent it from working.

Can someone please fix the incompatibility?

**Comment by lastperson** [comment]
Can login on .com, cannot on .org

**Comment by bebehei** [comment]
> Can login on .com, cannot on .org

I had the excact same behavior. Back then, I resolved this issue for me by logging on a testinstance from travis: https://bd-overeager-newlines.test-deployments.travis-ci.org/

Later on, travis-ci.org worked well.

**Comment by lastperson** [comment]
Tried that, cannot login there either.

**Comment by ChristianUlbrich** [comment]
I am having a similar problem. I cannot login on travis-ci.org, travis-com works though. I have already revoked the access, logged out of GitHub, used different browsers and devices and networks. I have also tried the above workaround from @bebehei; but nothing works. I am always stuck on https://travis-ci.org/auth , whenever I click "Sign in with GitHub" a whole bunch of requets / redirects are happening, but I am always ending up on the same site. 

I am not at loss. Any advice? How can I aid in debugging?

**Comment by BanzaiMan** [comment]
Recent ones over the last 3 days or so are probably #7612. The older ones are probably a different issue (which may have already been fixed).

**Comment by BanzaiMan** [comment]
I'm closing this one now, so as not to confuse the two likely different issues.

**Comment by cirosantilli** [comment]
I had funky chars in my profile info. Removed, logged in, logged out, re-added funky chars (copy paste removed something??), and login now works always.
