### ISSUE TITLE
Travis stalling on android sdk license acceptance

### ISSUE THREAD

**Issue by ChrisMykotaReid** [travis-ci/travis-ci#7238]
So my build was working fine a few days ago when I was doing (pretty much) the exact same thing as I am doing now. I tried explicitly accepting the licenses as well as not explicitly accepting them. I'm kinda stuck right now. Here's a link to my build logs: https://api.travis-ci.org/jobs/196273484/log.txt?deansi=true

relavant yml and scripts:
before_script.txt
install_script.txt
travis_yml.txt

**Comment by ChrisMykotaReid** [comment]
solved by adding echo y | to each package installation

**Comment by BanzaiMan** [comment]
Where do you see a build moving through without accepting the Android license?

**Comment by ChrisMykotaReid** [comment]
It's not moving through which was the kind of the problem.  It was getting to the license and stalling there without accepting or denying it.  At the end of the build this is what happened before erroring


November 20, 2015
Do you accept the license 'android-sdk-license-c81a61d9' [y/n]: 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated

**Comment by BanzaiMan** [comment]
In the original description, you wrote:

> So my build was working fine a few days ago when I was doing (pretty much) the exact same thing as I am doing now.

I took this to mean that there was a build that ran fine for you without accepting the license, which you indicated in https://github.com/travis-ci/travis-ci/issues/7238#issuecomment-275895258.

If there is no such build—that the build always stalled because your configuration did not accept the license—then there is no issue here.

**Comment by ChrisMykotaReid** [comment]
no, the build accepted the license automatically and continued on without stalling is what I meant by the build working fine

**Comment by BanzaiMan** [comment]
So where is the build log showing that the license was accepted automatically?

**Comment by ChrisMykotaReid** [comment]
I misunderstood you, sorry.  Here's a build log where it was: https://s3.amazonaws.com/archive.travis-ci.org/jobs/195745630/log.txt.  Beyond that shouldn't Travis be accepting licenses automatically?  I know it does when using the built in android sdk install through setting the language to android then specifying the components but when I try to do it manually it doesn't automatically accept them.

**Comment by BanzaiMan** [comment]
@ChrisMykotaReid That build comes from this commit, https://github.com/CMPT371Team1/Project/commit/7f117dacfff8abf3fc9f3e1e2b11382798523196, which _clearly_ [accepts the license with `echo y`](https://github.com/CMPT371Team1/Project/blob/7f117dacfff8abf3fc9f3e1e2b11382798523196/scripts/before_script.sh#L17-L22).

**Comment by BanzaiMan** [comment]
The license should always wait for the confirmation, and in Android builds we provide the means of doing so. On all other builds such as yours (`language: node_js`), you are responsible for accepting the license. This logic has not changed since we started supporting Android builds.

**Comment by ChrisMykotaReid** [comment]
Ok, thanks for the responses.  Sorry about the misunderstanding.  My assumption was that all licenses were automatically accepted under any circumstance but clearly this was wrong.

**Comment by BanzaiMan** [comment]
Cool. Since there is nothing to do here, I'm closing this.
