### ISSUE TITLE
Travis yml could not be found No Rakefile found

### ISSUE THREAD

**Issue by RajuSE** [travis-ci/travis-ci#7241]
Build is failing https://github.com/RajuSE/mortar-evolution-stone/compare/8b22b34b7138...e6367f9aa93a
So I added Travis file but still it is showing
> Could not find .travis.yml, using standard configuration.
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

Link: https://travis-ci.org/RajuSE/mortar-evolution-stone
 What can I do to make is pass?

**Comment by BanzaiMan** [comment]
You must have missed adding it to the commit. `.travis.yml` is not there. https://github.com/RajuSE/mortar-evolution-stone/tree/e6367f9aa93ae4cba4bd0cfcc628c44a04601457

**Comment by RajuSE** [comment]
@BanzaiMan I have added travis later and also added 1 commit but Travis not triggered this time.. check No build created: https://travis-ci.org/RajuSE/mortar-evolution-stone/builds

**Comment by RajuSE** [comment]
@BanzaiMan I'd like to get your thoughts on this
