### ISSUE TITLE
Travis job appears stalled at "created"

### ISSUE THREAD

**Issue by wasade** [travis-ci/travis-ci#7242]
Travis CI does not appear to be progressing on a recent PR. Travis CI has worked previously on this repository. I've tried canceling and restarting the jobs, and pushing in dummy commits to trigger new builds All paths lead to the job stalling on "created." If I click on "view config" the job status changes to "queued." One of these stalled jobs can be found [here](https://travis-ci.org/wasade/redbiom/builds/196685966).

**Comment by rplute** [comment]
Have exact same issue. :( My organization has four to five jobs currently frozen. No elapsed time, nothing. The logs just say `Hang tight, the log cannot be shown until the build has started.` This has been going on for the last 15 minutes.

**Comment by BanzaiMan** [comment]
Sorry for the issue. We are having problems with `sudo`-enabled builds such as these. We post updates here: https://www.traviscistatus.com/incidents/v8ymr10glpf3 (and https://twitter.com/traviscistatus).

**Comment by wasade** [comment]
@BanzaiMan no worries, and thank you for the update!

**Comment by BanzaiMan** [comment]
The capacity is coming back online. There are considerable back logs, but the normal operations should resume shortly. I'm closing this optimistically.

**Comment by wasade** [comment]
Excellent, thank you and thank you for resolving this so fast
