### ISSUE TITLE
[community:r] Parallel tests running infinite 

### ISSUE THREAD

**Issue by pat-s** [travis-ci/travis-ci#7243]
When running parallel tests (`foreach`, `doParallel`) R CMD check (checking test...) is running infinite. See [build](https://travis-ci.org/pat-s/sperrorest) here. 

I already extended the test time to 40 min (https://github.com/travis-ci/travis-ci/issues/3849#issuecomment-276088726) although it just takes around 30 secs on my local macOS installation. No errors are thrown regarding any missing packages so I´m rather lost here and help would be highly appreciated.

**Comment by BanzaiMan** [comment]
Please mention @craigcitro, @hadley, and @jimhester for R inquiries, as documented in https://docs.travis-ci.com/user/languages/r. Thanks.

**Comment by jimhester** [comment]
I see the same hanging behavior to travis when running `R CMD build . && R CMD check sperrorest` locally, I would suggest you debug that first. `devtools::test()` is not the same thing.

**Comment by pat-s** [comment]
Indeed, I only did `devtools::check()` and not `R CMD build`. Did not know about the differences. You are right, `R CMD build` is also not working locally. Thanks for the hint 👍

**Comment by pat-s** [comment]
Solved by @gaborcsardi:  https://github.com/hadley/testthat/issues/567#issuecomment-277539984 :sunny:
