### ISSUE TITLE
Build page env column misalignment when ENV value is really long

### ISSUE THREAD

**Issue by pllim** [travis-ci/travis-ci#7245]
The misaligned column is annoying because the test setup gets cut off and I cannot see the full text. I am using Firefox on RHEL6. Also see the same thing using Firefox on Windows 7. Others also report same problem on Mac, etc.

![screenshot](https://cloud.githubusercontent.com/assets/2090236/22470300/d39b4f84-e79c-11e6-9303-77213263af36.png)

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by pllim** [comment]
One of the many: https://travis-ci.org/astropy/astropy/builds/196872066

**Comment by lislis** [comment]
@pllim I deployed a quick fix which works on my setup. Can you hard refresh and tell us if it's fixed for you as well?

**Comment by pllim** [comment]
Yes, much better now. Thanks! Should I close this issue or do you want to keep it open until a not-so-quick fix is in?

**Comment by BanzaiMan** [comment]
Thanks for the confirmation. I'm closing this.
