### ISSUE TITLE
make passing build if in case .travis.yml added later

### ISSUE THREAD

**Issue by RajuSE** [travis-ci/travis-ci#7248]
I added travis.yml later. Now getting build failure
Facing issue https://github.com/travis-ci/travis-ci/issues/7241
In order to make it pass:
Do I have to revert commit https://github.com/RajuSE/mortar-evolution-stone/commit/e6367f9aa93ae4cba4bd0cfcc628c44a04601457
And recommit?

**Comment by BanzaiMan** [comment]
Your repo's notification is set incorrectly for some reason. How did you enable it? Could you try going to https://travis-ci.org/profile/RajuSE and deactivate/activate the repo?

**Comment by BanzaiMan** [comment]
You'd have to push a new commit to the repo.

**Comment by RajuSE** [comment]
As you told, I deactivated and activated it now. Can you check for next few seconds I'll be adding few dummy commits.

**Comment by BanzaiMan** [comment]
It's working now. https://travis-ci.org/RajuSE/mortar-evolution-stone/builds/197058312

**Comment by RajuSE** [comment]
@BanzaiMan thanks!
