### ISSUE TITLE
/gradlew: Permission denied 

### ISSUE THREAD

**Issue by RajuSE** [travis-ci/travis-ci#7249]
Build is failing: https://travis-ci.org/RajuSE/mortar-evolution-stone/builds/197058312#L1685
Error log:
>$ ./gradlew connectedAndroidTest
/home/travis/build.sh: line 57: ./gradlew: Permission denied

**Comment by BanzaiMan** [comment]
Your file doesn't have the execute permission.

```sh-session
$ git clone https://github.com/RajuSE/mortar-evolution-stone.git
Cloning into 'mortar-evolution-stone'...
remote: Counting objects: 136, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 136 (delta 7), reused 0 (delta 0), pack-reused 101
Receiving objects: 100% (136/136), 421.80 KiB | 355.00 KiB/s, done.
Resolving deltas: 100% (13/13), done.
Checking connectivity... done.
$ cd mortar-evolution-stone
$ ls -l gradlew
-rw-r--r--  1 asari  staff  4971 Jan 31 15:01 gradlew
```

You need to give it.

**Comment by iamawaismazhar** [comment]
**It can be fixed using the command:**

`git update-index --chmod=+x gradlew`

**A little desciption to understand the problem.
First of all you can check your permissions using:**

`git ls-tree HEAD`
**You will see:**

> 100644 blob xxxxxxxxxxx gradlew


**As you can see the file has 644 permission.**

**Fix it by setting the executable flag on your gradlew file changing it to 755:**

`git update-index --chmod=+x gradlew`

**Just commit and push the changes:**

```git commit -m "permission access for travis"

[master e80ab1b] gradlew permission access for travis
 1 file changed, 0 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 gradlew
```
For more [explaination](https://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied).

**Comment by apurvaaggarwal** [comment]
1) chmod +x gradlew
2)./gradlew clean
