### ISSUE TITLE
Build does not start

### ISSUE THREAD

**Issue by sugr4** [travis-ci/travis-ci#7250]
We've been waiting over an hour for the build to start. https://travis-ci.org/Microsoft/OMS-Agent-for-Linux/pull_requests 
The build gets stuck on `Hang tight, the log cannot be shown until the build has started.`
I did not see any issues on https://www.traviscistatus.com/
Also tried restarting the build. Any reasons why this could happen?

**Comment by akarnokd** [comment]
Same here, this [PR](https://travis-ci.org/ReactiveX/RxJava/builds/197110630) didn't run in 7 hours and now the [master build](https://travis-ci.org/ReactiveX/RxJava/builds/197241322) seems to do nothing while the status indicates there is no problem with linux build.

**Comment by BanzaiMan** [comment]
We are having [outage on Mac builds at the moment](https://www.traviscistatus.com/incidents/k79mjcv403c4). If your build queue includes Mac jobs, they can take up slots in the build queue and prevent Linux jobs from running. If you can, please cancel Mac jobs, so that Linux jobs may run.

**Comment by akarnokd** [comment]
My jobs are pure Linux only, Java + Gradle type jobs. I cancelled and restarted them several times and still not progressing. Is it possible the Mac outage somehow affects the Linux builds or for some reason my Linux jobs appear to be Mac jobs to the Travis scheduler?

**Comment by BanzaiMan** [comment]
@akarnokd Yours seems like a different issue. (And https://travis-ci.org/ReactiveX/RxJava/builds/197241322 just started running.)

**Comment by akarnokd** [comment]
Thanks. (Based on the Travis status report Linux jobs were indeed held up by Mac jobs for some reason.)

**Comment by BanzaiMan** [comment]
The build issue should be resolved now. I'm closing this.
