### ISSUE TITLE
Rscript error in update.packages 

### ISSUE THREAD

**Issue by HughParsonage** [travis-ci/travis-ci#7252]
During setup for [an R CMD check](https://travis-ci.org/HughParsonage/grattanReporter/builds/197171990), I get the error:

```
Rscript -e 'update.packages(ask = FALSE)'
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
Calls: update.packages -> available.packages -> contrib.url
Execution halted
The command "Rscript -e 'update.packages(ask = FALSE)'" failed and exited with 1 during .
```

I tried deleting the cache but the same error occurred. I hadn't change the `.travis.yml` file since the last successful build (https://github.com/HughParsonage/grattanReporter/compare/1a53e331cb66...345beee4487b)

(N.B. The linked push should result in a broken build, but not because of this.)

@craigcitro
@jimhester

**Comment by chschan** [comment]
I'm also seeing this error. I tried changing .travis.yml to add 
```
before_install:
    - echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > ~/.Rprofile.site 
```
but this doesn't solve the problem as the update.packages seems to be getting called before that line is run.

**Comment by HughParsonage** [comment]
May be due to wider Travis issue: https://www.traviscistatus.com/incidents/k79mjcv403c4 ? Not obviously so, however.

**Comment by chschan** [comment]
I'm using `dist: trusty` with `sudo: required` so it doesn't seem related

**Comment by AdrianHordyk** [comment]
Same problem. Tried adding:
```
repos:
 CRAN: http://cran.rstudio.com
```
but problem remains.

**Comment by graemeleehickey** [comment]
Same here. I tried adding:
```
cran: http://cran.rstudio.com
repos:
  CRAN: http://cran.rstudio.com
  ropensci: http://packages.ropensci.com
```

but did not change. Also, previous successful builds are now failing.

**Comment by ivyleavedtoadflax** [comment]
I'm also seeing this issue. Previous OK builds also now failing.

**Comment by mexindian** [comment]
+1
