### ISSUE TITLE
[r-community] Cannot connect to X server

### ISSUE THREAD

**Issue by pat-s** [travis-ci/travis-ci#7259]
`R CMD check` fail log:

```r
> library("testthat")
> 
> test_check("RQGIS")
: cannot connect to X server 
1. Error: Test, if QGIS-algorithms are working? (@test-run-qgis.R#29) ----------
cannot open the connection
1: get_args_man(alg = "qgis:polygoncentroids", qgis_env = qgis_env) at testthat/test-run-qgis.R:29
2: utils::read.csv(file.path(tmp_dir, "output.csv"), header = TRUE, stringsAsFactors = FALSE)
3: read.table(file = file, header = header, sep = sep, quote = quote, dec = dec, fill = fill, 
       comment.char = comment.char, ...)
4: file(file, "rt")
```

Already tried to fix it with the help of [AskUbuntu](http://askubuntu.com/questions/175611/cannot-connect-to-x-server-when-running-app-with-sudo) and this line `- sudo sh -c 'echo Defaults env_keep="DISPLAY XAUTHORITY" >> ~/visudo'`. I assume that I need to suppress the opening of X server somehow?

Maybe the `cannot open the connection` error is related to the `x server` problem? I checked [this testthat issue](https://github.com/hadley/testthat/issues/86) regarding the connection error.

Build log: https://travis-ci.org/jannes-m/RQGIS/jobs/197807001

@craigcitro and @jimhester

**Comment by jimhester** [comment]
I believe the recommended approach is to use xvfb https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

**Comment by jimhester** [comment]
Or condition your tests to check for a available X Server with something like `if(capabilities("X11"))`.

**Comment by pat-s** [comment]
Forgot to reply. The following works for me: 

```
  - "export DISPLAY=:99.0"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 3 # give xvfb some time to start
```
