### ISSUE TITLE
Ubuntu 16.04 LTS Support

### ISSUE THREAD

**Issue by wtgee** [travis-ci/travis-ci#7260]
I hate to beat a dead horse, but comments are closed on #5821 and it seems like the issue should be reopened. I realize it's possible to run 16.04 in a Docker container (#6469). But, 12.04 (the current default) is about to fall out of LTS and not be supported by Ubuntu. It makes sense for travis to have two options for Ubuntu, those being the two LTSs that are available in any given year. As of April this year that will be 14.04 and 16.04.

Are there any plans to move to 16.04 or will the answer always be to use Docker?

**Comment by BanzaiMan** [comment]
Thanks for taking time to open this issue.

We have a plan to move to 16.04, but at the moment, we do not have ETA for it. We understand that this has been slow in coming, and it's frustrating for you, but we do not have any update to share other than those mentioned in the issues you mention.

**Comment by wtgee** [comment]
Got it. Kind of annoying to have to go the Docker route but sounds like the only option for now. 

Thanks!

**Comment by edmorley** [comment]
As another data point, Heroku have just made their 16.04 based stack the default:
https://devcenter.heroku.com/changelog-items/1139

**Comment by robguttman** [comment]
Is there an ETA yet for supporting Ubuntu 16.04?

**Comment by BanzaiMan** [comment]
We are working on it, but we do not have ETA.

**Comment by ahupp** [comment]
I accidentally left `dist: xenial` in my travis.yml a while back and sometime recently my jobs started using xenial.  So it seems this was released quietly.

**Comment by larsbrinkhoff** [comment]
Perfect timing.  I need to use Xenial right now.

**Comment by budmc29** [comment]
Looks like the ```dist: xenial``` option does not work (anymore?).

**Comment by BanzaiMan** [comment]
As you saw, we are working on `dist: xenial`. It may or may not work, depending on what we are working on. It is not supported in any way, and we apologize in advance that you may experience problems from time to time. We will work on various issues as they come up, but we are unable to offer any support.

**Comment by marcosps** [comment]
Xenial would allow us to use default meson build settings, along with ninja-build. For now I had to setup a docker to make it compile using a fedora image...

Can't wait to have Xenial available!

**Comment by bgard6977** [comment]
Ubuntu 14.04 LTS/Initial release date
April 17, 2014

Maybe in another 4 years we can have nice things. thanks.

**Comment by ysolovyov** [comment]
I suggest to start working on 18.04 and skip 16.04 :)
