### ISSUE TITLE
R for Travis-CI suddenly requires the digest package to be installed

### ISSUE THREAD

**Issue by floscher** [travis-ci/travis-ci#7263]
Since some days my R builds on Travis kept failing with this message:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/travis/R/Library/digest/libs/digest.so':
  libR.so: cannot open shared object file: No such file or directory
ERROR: lazy loading failed for package ‘devtools’
```
See e.g. https://travis-ci.org/floscher/LandClimTools/builds/197986463#L700-L703 for the full log of such a build. Five days ago the exact same commit was built on Travis successfully, I just restarted the build for demonstrating that the issue seems to be introduced in these five days.

My current solution to this is to add
```yaml
addons:
  apt:
    packages:
      - r-cran-digest
```
to my `.travis.yml`, which fixes the problem. But the better solution would be, if you preinstall that for all R builds.

cc @craigcitro
cc @jimhester

**Comment by jimhester** [comment]
I think this is likely a package cache issue due to recent changes allowing multiple R versions in the trusty environment. I would suggest deleting your cache at https://travis-ci.org/floscher/LandClimTools/caches and removing `r-cran-digest`.

**Comment by floscher** [comment]
Thank you! Good catch, the issue is now resolved.
