### ISSUE TITLE
macos r.rb has trouble finding latest R release

### ISSUE THREAD

**Issue by jpritikin** [travis-ci/travis-ci#7266]
See https://travis-ci.org/OpenMx/OpenMx/jobs/198117007

````
Installing R
$ brew update >/dev/null
$ curl -Lo /tmp/R.pkg http://cloud.r-project.org/bin/macosx/old/R-["release"].pkg
````

Looks like you need to normalized_r_version(r_version) on line 117 of r.rb because r_latest is already normalized. See https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb

Here's my [.travis.yml](https://github.com/travis-ci/travis-ci/files/751577/default.travis.yml.txt)

@craigcitro @jimhester Should be an easy fix.

**Comment by jimhester** [comment]
Other R versions are not supported on MacOS, and there are no plans to do so. You just need to remove the `r:` block entirely.

**Comment by jpritikin** [comment]
Gotcha. Thanks.
