### ISSUE TITLE
Sometimes travis starts more builds then needed

### ISSUE THREAD

**Issue by TheNoim** [travis-ci/travis-ci#7267]
Hello,
I noticed, sometimes travis starts more then one build when I commit something.
http://imgur.com/a/MgHXs
It is all the same commit, but why three times ? It is not the first time this happens. And then I need to cancel the other unnecessarily builds to not take others build resources.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
I'm closing this due to lack of information.
