### ISSUE TITLE
Nightly builds of actively supported PHP versions

### ISSUE THREAD

**Issue by sebastianbergmann** [travis-ci/travis-ci#7268]
Using
```
php:
 - nightly
```
in a PHP project uses a nightly build of PHP built from PHP's `master` branch. At the moment this is a nightly build of what will eventually become PHP 7.2.

For a project such as PHPUnit it would be great to be able to test with nightly builds of all branches of PHP, currently PHP 7.0 and PHP 7.1, that are actively maintained by the PHP project.

Here is an idea for how the configuration for this could look like:
```
php:
 - 7.0-nightly
 - 7.1-nightly
 - nightly
```
This would build the project using a nightly build of PHP 7.0, PHP 7.1, and PHP 7.2.

**Comment by hollodotme** [comment]
+1

**Comment by BanzaiMan** [comment]
We use php-build for compiling PHP archives. See https://github.com/php-build/php-build/tree/master/share/php-build/definitions.

It is currently undocumented, but the names you can use for this purpose are `7.0snapshot` and `7.1snapshot`.

**Comment by BanzaiMan** [comment]
`nightly` is an alias for `master`.

**Comment by sebastianbergmann** [comment]
So
```
php:
 - 7.0snapshot
 - 7.1snapshot
 - master
```
would do what I want?

**Comment by BanzaiMan** [comment]
Yes. Have you tried it?

**Comment by sebastianbergmann** [comment]
Yes, I have: https://travis-ci.org/sebastianbergmann/phpunit/builds/201040753

Seems to work, thanks.
