### ISSUE TITLE
.NET (Mono) build fails with permissions error

### ISSUE THREAD

**Issue by Netshroud** [travis-ci/travis-ci#7271]
Looks like this has been an issue for about two weeks or more, from https://travis-ci.org/SteamRE/SteamKit/builds/194149385 to https://travis-ci.org/SteamRE/SteamKit/builds/198420553 

```
$ nuget restore SteamKit2/SteamKit2.sln
Access to the path "/home/travis/.config/NuGet" is denied.
The command "nuget restore SteamKit2/SteamKit2.sln" failed and exited with 1 during .
```
cc @joshua-anderson @akoeplinger @nterry

**Comment by Joshua-Anderson** [comment]
Interesting. @BanzaiMan have you made any changes to containerized images lately that could have changed home directory permissions?

@Netshroud does mono stable still work for you?

**Comment by BanzaiMan** [comment]
Not to my knowledge.https://travis-ci.org/BanzaiMan/travis_production_test/builds/198479932 shows that you can still create `~/.config/NuGet` on the fly. If the process is getting permission denied, then I tend to think something is creating it with undesirable permissions.

**Comment by Netshroud** [comment]
[Build with latest stable Mono](https://travis-ci.org/SteamRE/SteamKit/builds/198481370) works fine.

I'm guessing it's a Mono bug, then?

**Comment by Joshua-Anderson** [comment]
> I'm guessing it's a Mono bug, then?

Seems like it.

**Comment by akoeplinger** [comment]
This was indeed an issue in the Mono 4.8 release in the alpha channel, we pushed a hotfix for that and it should be working fine. Thanks very much for bringing this up!

**Comment by BanzaiMan** [comment]
I'm closing this now, then. Thanks, everyone!
