### ISSUE TITLE
compiling R dependencies from source takes too long

### ISSUE THREAD

**Issue by jpritikin** [travis-ci/travis-ci#7272]
@craigcitro, @hadley, and @jimhester: I enabled the package cache, which is great, but sometimes I can't even get binaries into the cache because building takes too long. For exampe, [here](https://travis-ci.org/OpenMx/OpenMx/jobs/198426412) is a build that timed out just before it got to running tests. I notice that MacOS instances install dependencies much faster because binaries are used. Is there any archive for Linux binaries of R packages that I could use?

**Comment by jimhester** [comment]
Set `sudo: required` and use `r_binary_builds` https://docs.travis-ci.com/user/languages/r/#Additional-Dependency-Fields

**Comment by jpritikin** [comment]
Awesome. Thanks.
