### ISSUE TITLE
Old versions of PHP

### ISSUE THREAD

**Issue by sebastianbergmann** [travis-ci/travis-ci#7275]
I would like to run the test suite for PHPUnit 5.7 against all released versions of PHP 5.6, PHP 7.0, and PHP 7.1 to ensure PHPUnit 5.7 works (and continues correctly) for each PHP version it has to support.

Towards that end, I experimented with
```
php:
  - 5.6.0
  - 5.6.1
  - 5.6.2
  - 5.6.3
  - 5.6.4
  - 5.6.5
  - 5.6.6
  - 5.6.7
  - 5.6.8
  - 5.6.9
  - 5.6.9
  - 5.6.10
  - 5.6.11
  - 5.6.12
  - 5.6.13
  - 5.6.14
  - 5.6.15
  - 5.6.16
  - 5.6.17
  - 5.6.18
  - 5.6.19
  - 5.6.20
  - 5.6.21
  - 5.6.22
  - 5.6.23
  - 5.6.24
  - 5.6.25
  - 5.6.26
  - 5.6.27
  - 5.6.28
  - 5.6.29
  - 5.6.30
  - 5.6
  - 7.0.0
  - 7.0.1
  - 7.0.2
  - 7.0.3
  - 7.0.4
  - 7.0.5
  - 7.0.6
  - 7.0.7
  - 7.0.8
  - 7.0.9
  - 7.0.10
  - 7.0.11
  - 7.0.12
  - 7.0.13
  - 7.0.14
  - 7.0.15
  - 7.0
  - 7.1.0
  - 7.1.1
  - 7.1
  - nightly
```

The result of this can be seen in https://travis-ci.org/sebastianbergmann/phpunit/builds/198554343.

Apparently, not all old versions of PHP can be used on Travis. PHP 5.6.0-5.6.4, PHP 5.6.6-5.6.11, PHP 5.6.20-5.6.22, and PHP 7.1.1 are missing. Is this intentional?

**Comment by BanzaiMan** [comment]
We have not compiled all PHP versions on all Ubuntu releases for use on our service. In the past, there has not been any request.

**Comment by sebastianbergmann** [comment]
Then please consider this ticket the request to add these versions.

**Comment by BanzaiMan** [comment]
The 5.6.x versions mentioned above are available. 7.1.1 will be, when https://travis-ci.org/travis-ci/php-src-builder/builds/209883589 finishes.

I'm closing this now. If you see problems with the archives, please open a separate issue.

Thank you!
