### ISSUE TITLE
Use `rustup.rs` instead of `rustup.sh` for `language: rust` projects

### ISSUE THREAD

**Issue by gifnksm** [travis-ci/travis-ci#7276]
Currently, for rust project, [`rustup.sh`](https://github.com/rust-lang/rustup.sh) is used, but rust's official installation tool has been changed to [`rustup.rs`](https://github.com/rust-lang-nursery/rustup.rs).

`rustup.rs` supports more functions than `rustup.sh` such as cross compiling. I saw many Travis users generating cross compiled binaries on Travis with installing `rustup.rs` by their own.

**Comment by BanzaiMan** [comment]
How does this affect Rust builds? We download `rustup.sh` to install the version of Rust specified. Nowhere else is it used. Are you just requesting that `rustup.rs` be available for your builds?

**Comment by phil-opp** [comment]
`rustup.rs` is the [official installation tool](https://www.rust-lang.org/en-US/install.html) now and completely replaces `rustup.sh` (see the [Readme](https://github.com/rust-lang/rustup.sh) of `rustup.sh`).

`rustup.rs` provides additional functionality after installation. For example, one can add [cross compile](https://github.com/rust-lang-nursery/rustup.rs#cross-compilation) to android through `rustup target add arm-linux-androideabi`. It is also possible to download the corresponding Rust source code through `rustup component add rust-src` (this is needed by tools such as [xargo](https://github.com/japaric/xargo)).

To use these features at the moment, one has to install Rust a second time by manually executing:

```
curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
```

**Comment by beefsack** [comment]
I currently need rustup.rs to install a target that works on both AWS Lambda and AWS Elastic Beanstalk (I need to target x86_64-unknown-linux-musl.)

Currently manually installing rustup.rs using the previous comment's technique but would be much easier if rustup.rs was installed and exposed.

**Comment by BanzaiMan** [comment]
> if rustup.rs was installed and exposed.

Do you mean `rustup`, perhaps? The `curl | sh` pipe will execute the install script given by `https://sh.rustup.rs`, which puts binaries in `$HOME/.cargo/bin`. The binaries installed are:

```sh-session
$ ls ~/.cargo/bin
cargo  rustc  rustdoc  rust-gdb  rust-lldb  rustup
```

**Comment by SirDoctors** [comment]
Whoot! thanks
