### ISSUE TITLE
Build stuck on "Created" for >4 days

### ISSUE THREAD

**Issue by DanielZlotin** [travis-ci/travis-ci#7279]
https://travis-ci.org/wix/react-native-navigation/builds/197366134

**Comment by BanzaiMan** [comment]
Ouch. Can you cancel it or not?

**Comment by acnagy** [comment]
Hey @DanielZlotin - sorry for the trouble. I canceled out this stalled build - feel free to restart it at this point, if you'd like. Thanks for your understanding!
