### ISSUE TITLE
Unimplemented pathspec magic '!'

### ISSUE THREAD

**Issue by natanmoraes** [travis-ci/travis-ci#7280]
I'm trying to execute a gif diff in my build that goes something like this:

`git diff --name-only --diff-filter=d origin/master -- . ':!*.txt'`

And my build is throwing the following error:

`fatal: Unimplemented pathspec magic '!' in 'path/to/my/file.txt`

As per [git's docs](https://git-scm.com/docs/gitglossary.html) it seems my command is valid (look for `magic signature: !`) 

Am I missing something in my .yml file or is Travis' git version not up to date?

Below is my .travis.yml file:

```
language: php
sudo: false

php:
  - 5.6

install:
  # Remove xdebug to make composer faster.

  - phpenv config-rm xdebug.ini
  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Install PHP_CodeSniffer and Drupal config
  - composer global require drupal/coder
  - phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer

before_script:
  # This slows things down but it ensures all remote branches are fetched.
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch --unshallow
  - git fetch origin

script: ./scripts/travis-build.sh
```

**Comment by BanzaiMan** [comment]
Looks like this is a new feature in git 1.9.5. Currently GCE Trusty appears to be the only env which has a version newer than this (https://travis-ci.org/BanzaiMan/travis_production_test/jobs/198479936#L25). So, please try `sudo: required` + `dist: trusty`.

**Comment by natanmoraes** [comment]
@BanzaiMan that did the trick, thanks!
