### ISSUE TITLE
Can't use ENV in .travis.yml

### ISSUE THREAD

**Issue by OmgImAlexis** [travis-ci/travis-ci#7288]
After adding an env called `CLOUDFLARE` and setting the value in the travis dashboard I'm unable to use the `$CLOUDFLARE` var in my `.travis.yml` as I get a yaml error in the build view.

Failed build: https://travis-ci.org/pymedusa/medusa.github.io/builds/199134057

```
before_install:
    - openssl aes-256-cbc -K $encrypted_16ef2a8e0308_key -iv $encrypted_16ef2a8e0308_iv -in .travis/deploy_static.pem.enc -out .travis/deploy_static.pem -d
script:
    - echo "198.211.102.17 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBO+G8ELGG/NTCQ/3H2O7i8POqq9eKkeAnW2emTiEnBEgEFIfc5k/oUUWSFDniqN14tkpkL1t4tTOdaetqhJvxp0="
      > ~/.ssh/known_hosts
    - eval "$(ssh-agent -s)"
    - chmod 600 .travis/deploy_static.pem
    - ssh-add .travis/deploy_static.pem
    - git remote add deploy dokku@198.211.102.17:cdn.pymedusa.com
    - git push deploy master
    - curl -X DELETE "https://api.cloudflare.com/client/v4/zones/1c1c0a6842e72232a6daa534eec42936/purge_cache" -H "X-Auth-Email: xo@wvvw.me" -H "X-Auth-Key: $CLOUDFLARE" -H "Content-Type: application/json" --data '{"purge_everything":true}'
```

**Comment by BanzaiMan** [comment]
Your `.travis.yml` is invalid. Keep in mind that `:` is a delimiter for the map key-value pairs.

**Comment by OmgImAlexis** [comment]
How would I add it then? Also it only complains from $CLOUDFLARE onwards so the : before it doesn't seem to be an issue.

**Comment by BanzaiMan** [comment]
Enclose it in a string.

**Comment by OmgImAlexis** [comment]
It's in a string? `"X-Auth-Key: $CLOUDFLARE"`

**Comment by BanzaiMan** [comment]
Validate with any compliant parser. For example, http://yaml-online-parser.appspot.com/.
