### ISSUE TITLE
Incorrect date shown in tooltip in Branches view when build is not finished 

### ISSUE THREAD

**Issue by stewx** [travis-ci/travis-ci#7291]
There is an invalid date shown in the `title` attribute when builds shown in the Branches page are not finished.

<img width="532" alt="screen shot 2017-02-07 at 5 18 34 pm" src="https://cloud.githubusercontent.com/assets/6986171/22711995/9ab9bdb4-ed59-11e6-84ed-254154ce162f.png">

**Comment by clekstro** [comment]
This should no longer be an issue as of https://github.com/travis-ci/travis-web/pull/1493. Closing.
