### ISSUE TITLE
Not able to add hooks manually for travis-ci.org

### ISSUE THREAD

**Issue by rijincp** [travis-ci/travis-ci#7292]
Hi,
I am trying to add a hook manually to a github repo and it's not working. 
Adding the repo through travis profile page is not possible for the following reason:
- The repo is owned by an org I am part of.
- I have admin access to repo
- Third-party application restrictions are enabled in the org level

Thanks!

**Comment by BanzaiMan** [comment]
Sorry to hear about this issue. To resolve this, could you tell us the repository you are trying to set up?

**Comment by rijincp** [comment]
Hi Banzaiman, thanks for the response!
Here's the repo.
https://github.com/Appdynamics/FastAppConfig

**Comment by BanzaiMan** [comment]
Thanks for the info. It appears that we are having problems syncing data for this organization, and that repository is unknown. You say:

> Third-party application restrictions are enabled in the org level

Is Travis allowed to access organization data?

**Comment by BanzaiMan** [comment]
Can we close this?
