### ISSUE TITLE
CR should overwrite present line consistently

### ISSUE THREAD

**Issue by rmzelle** [travis-ci/travis-ci#7293]
I noticed something strange on our build pages. Take for example https://travis-ci.org/citation-style-language/styles/builds/199495218:

The build page has the following line:

```
 138727/138784 |==================== 99 =====================> |  ETA: 00:00:00 
 138784/138784 |==================== 100 =====================>| Time: 00:01:00
```

(see https://travis-ci.org/citation-style-language/styles/builds/199495218#L205)

However, the whole "138727/138784 |==================== 99 =====================> |  ETA: 00:00:00" substring doesn't appear anywhere in the raw log: https://api.travis-ci.org/jobs/199495219/log.txt?deansi=true

I thought that the build page just showed a condensed (and prettier) version of the raw log. Is this normal?

The line in question is generated by the Fuubar RSpec progress bar formatter (https://github.com/thekompanee/fuubar). I reported the issue there (https://github.com/thekompanee/fuubar/issues/97), but was directed here.

**Comment by BanzaiMan** [comment]
The raw log contains this line: https://api.travis-ci.org/jobs/199495219/log.txt In the logs, you see that there is a CR after each line (but no LF). I think this is where the discrepancy comes in.

**Comment by rmzelle** [comment]
Ah, sorry, I didn't realize that https://api.travis-ci.org/jobs/199495219/log.txt?deansi=true, which is the link given on the build page, is a modified version of https://api.travis-ci.org/jobs/199495219/log.txt. (is "deansi=true" documented anywhere, by the way?)

So you think this might be an issue with travis-web instead of the Fuubar progress bar? If so, I'll just sit tight.

**Comment by backspace** [comment]
Hey, @rmzelle, thanks for reporting this. It does seem likely that it’s a `travis-web` problem introduced via my fix [for this issue](https://github.com/travis-ci/travis-ci/issues/7106). The trouble is that the log-rendering code is mysterious to everyone, so while my fix seemed reasonable, it appears to have broken things for your log. I’ll look at this and hopefully find something that will render everything properly for both instances.

**Comment by backspace** [comment]
Hello again! For now, I’ve reverted the change that I made to address the aforelinked issue. Your logs don’t have the weird double-rendered line now!

I’ll be working on fixing the issue on the other logs and it’s quite helpful to have this instance to check my work against, so thanks again.

**Comment by rmzelle** [comment]
Great, thanks!
