### ISSUE TITLE
PHP Codeception: chmod(): No such file or directory

### ISSUE THREAD

**Issue by zachleigh** [travis-ci/travis-ci#7295]
All Codeception tests are ending before running with the following error: 
```
chmod(): No such file or directory
```
This repo: https://travis-ci.org/zachleigh/larafolio/jobs/199836882   

All tests work locally. Re-running old tests that passed before, also triggers the error and causes failure. Please feel free to run some of the above repo's older test builds to validate that they now fail.

**Comment by BanzaiMan** [comment]
What file is it trying to run this function on?

**Comment by zachleigh** [comment]
@BanzaiMan It doesn't say. The entire error message is: "chmod(): No such file or directory"

**Comment by BanzaiMan** [comment]
> Re-running old tests that passed before, also triggers the error and causes failure. Please feel free to run some of the above repo's older test builds to validate that they now fail.

This could often be caused by changes in underlying dependencies. Identify changes between the last success and the first failure.

**Comment by zachleigh** [comment]
@BanzaiMan Found the chmod that was causing the trouble and found a work-arourd.  I have no idea why this started causing trouble, especially in older builds. No dependencies changed. I got it working, so I'm closing this.
