### ISSUE TITLE
Can we specify particular OS to run during building a python wheel

### ISSUE THREAD

**Issue by rajashekhar1121** [travis-ci/travis-ci#7299]
I wanna builld my python project wheel using debian OS

How can I specify OS to use debian ?

**Comment by BanzaiMan** [comment]
We do not support Linux distributions other than Ubuntu out of the box right now. If you want to test against Debian, you could do so via [Docker](https://docs.travis-ci.com/user/docker/).

We may eventually support other build images, but for now, this is the best option.
