### ISSUE TITLE
Please support .net core 1.0.0-rc4-004771

### ISSUE THREAD

**Issue by thiennn** [travis-ci/travis-ci#7301]
As Microsoft has released the new version of .netcore sdk. https://blogs.msdn.microsoft.com/dotnet/2017/02/07/announcing-net-core-tools-updates-in-vs-2017-rc/

Could you please support it?

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by am11** [comment]
@akoeplinger, @jo

**Comment by am11** [comment]
@joshua-anderson @akoeplinger @nterry, @blackdwarf

TravisCI seems to be downloading the SDK from the following URL: 

https://dotnetcli.azureedge.net/dotnet/preview/Installers/1.0.0-rc4-004915/dotnet-dev-osx-x64.1.0.0-rc4-004915.pkg

which returns 404. However, the URL formed by the [CLI's `obtain` script](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/dotnet-install.sh) is:

https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-rc4-004915/dotnet-dev-osx-x64.1.0.0-rc4-004915.tar.gz

It seems like after certain version (rc3 or preview2), they changed the URL format. Can we conditionally form the download URL based on the version where it stared to differ?

**Comment by am11** [comment]
(or perhaps incorporate CLI's obtain script as is)

**Comment by ThePadawan** [comment]
As of yesterday, 1.0.4 and 1.1.1 are [no longer in preview](https://blogs.msdn.microsoft.com/dotnet/2017/03/07/announcing-net-core-tools-1-0/).

Since the project.json-based infrastructure is now being steadily phased out, I would love to switch my projects over to the .csproj-based infrastructure, but won't do so without proper CI support.

@joshua-anderson @akoeplinger @nterry
Please advise if I can support you in any way to support the new .NET Core SDK versions.

**Comment by Joshua-Anderson** [comment]
@ThePadawan They should be supported now on linux and OSX!

**Comment by akoeplinger** [comment]
@ThePadawan note that 1.0.4 and 1.1.1 are the version numbers of .NET Core, but we're using the version number of the .NET Core Tooling/SDK (aka CLI) in the `dotnet` key (an SDK can install multiple .NET Core runtimes). 

The SDK is at version `1.0.1`, so just use `dotnet: 1.0.1`.

**Comment by thiennn** [comment]
Yeah, it works. Thank you so much

**Comment by ThePadawan** [comment]
Thank you so much, I will try this out ASAP :sweet_potato: !
