### ISSUE TITLE
Postgres version not as defined in addons?

### ISSUE THREAD

**Issue by fredrikaverpil** [travis-ci/travis-ci#7305]
I'm defining the following in `.travis.yml` to use Postgres 9.4:

    language: python

    sudo: required
    dist: trusty

    python:
      - 2.7
      - 3.5

    services:
      - postgresql

    addons:
      postgresql: "9.4"

    install:
      - pip install sqlalchemy psycopg2 jinja2 alembic Mako MarkupSafe python-editor nose coverage

    before_script:
      - psql -c "CREATE DATABASE test_db;" -U postgres
      - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
      - psql --version
      - pg_config --version

But for some reason, the output of `pg_config --version` is not 9.4.x:

    $ psql --version
    psql (PostgreSQL) 9.4.10

    $ pg_config --version
    PostgreSQL 9.6.1

Should not both these report being 9.4.x?

**Comment by BanzaiMan** [comment]
Do you know where this file is coming from? It appears to come from http://packages.ubuntu.com/precise/libpq-dev, which is *outside of* the PostgreSQL official packages we use from https://www.postgresql.org/download/linux/ubuntu/.

**Comment by fredrikaverpil** [comment]
I don't think it's part of `ubuntu:trusty`:

```bash
$ run --rm --interactive --tty ubuntu:trusty
root@5573d36f3503:/# pg_config --version
bash: pg_config: command not found
root@5573d36f3503:/# apt-get update && apt-get install -y libpq-dev
...
...
...
pg_config --version
PostgreSQL 9.3.15
```

**Comment by fredrikaverpil** [comment]
Since it seems the trusty image seems to be loaded with several versions, is it possible that `pg_config` of the most latest one is left behind?

```
Worker information
hostname: travis-worker-gce-org-prod2-6:3ecbcf07-ed5c-4c41-9cf0-41bc84d141e1
version: v2.6.2 https://github.com/travis-ci/worker/tree/fdccca4efd347ebc889baae641ccbf55bb871d19
instance: testing-gce-d80a4fcb-be3a-4350-9e65-eb43323baa02:travis-ci-sugilite-trusty-1480960799
startup: 21.124984477s
...
...
...
Pre-installed PostgreSQL versions
9.2.19
9.3.15
9.4.10
9.5.5
9.6.1
...
...
...
0.16s$ sudo service postgresql start
 * Starting PostgreSQL 9.2 database server       
postgresql
Starting PostgreSQL v9.3
1.40s$ sudo service postgresql stop
 * Stopping PostgreSQL 9.3 database server        * Stopping PostgreSQL 9.4 database server        * Stopping PostgreSQL 9.5 database server        * Stopping PostgreSQL 9.6 database server       
2.24s$ sudo service postgresql start 9.3
0.05s$ sudo -u postgres createuser -s -p 5432 travis &>/dev/null
0.25s$ sudo -u postgres createdb -O travis -p 5432 travis &>/dev/null
0.04s$ sudo -u postgres createuser -s -p 5433 travis &>/dev/null
0.04s$ sudo -u postgres createdb -O travis -p 5433 travis &>/dev/null
```

**Comment by BanzaiMan** [comment]
It comes from `libpq-dev`.

```sh-session
$ dpkg -S `which pg_config`
diversion by postgresql-common from: /usr/bin/pg_config
diversion by postgresql-common to: /usr/bin/pg_config.libpq-dev
libpq-dev, postgresql-common: /usr/bin/pg_config
```

For Trusty, it seems that the postgresql.org repository has only 9.6, and Ubuntu, only 9.3:

```sh-session
$ apt-cache policy libpq-dev
libpq-dev:
  Installed: (none)
  Candidate: 9.6.2-1.pgdg14.04+1
  Version table:
     9.6.2-1.pgdg14.04+1 0
        500 http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg/main amd64 Packages
     9.3.15-0ubuntu0.14.04 0
        500 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
     9.3.14-0ubuntu0.14.04 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     9.3.4-1 0
        500 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

The version 9.6 remains because we install it during the image provisioning, and there is nothing else which replaces it. There is no package available for any other versions on the sources we have, and I am not sure how we can overcome this.

**Comment by fredrikaverpil** [comment]
Allright, this is not an issue for me at this point. I was merely wondering if something was wrong. So I guess we can close this issue then.
