### ISSUE TITLE
Typo in build status when build is cancelled

### ISSUE THREAD

**Issue by Lyxnx** [travis-ci/travis-ci#7306]
I was hovering over the build status badge and noticed a typo when a build was cancelled.
The typo says `canceled` rather than `cancelled`.

![typo](https://cloud.githubusercontent.com/assets/12625420/22856997/da968500-f094-11e6-962c-bde556eb2539.png)

If it helps, using Opera on Windows but I expect that it happens on other OSes also.

**Comment by BanzaiMan** [comment]
That is how it's spelled in American English, which we generally follow. http://grammarist.com/spelling/cancel/
