### ISSUE TITLE
Build crashed on release and branch

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#7309]
https://travis-ci.org/LolexOrg/Lolex-Tools/jobs/200095183
Not sure why this happened but the other jobs failed too.

**Comment by BanzaiMan** [comment]
I think this is a duplicate of https://github.com/travis-ci/travis-ci/issues/1590, where a branch and a tag share the same name.

**Comment by BanzaiMan** [comment]
Closing this as a duplicate. If you believe there is a reason to suggest otherwise, do let us know.
