### ISSUE TITLE
Gradle script that autogenerates code randomly fails on travis-ci only

### ISSUE THREAD

**Issue by lessthanoptimal** [travis-ci/travis-ci#7311]
I have a gradle script for a project ([EJML](https://github.com/lessthanoptimal/ejml)) that only randomly fails when run in Travis-CI during the autocode generation step.  Worked perfectly before auto generated code was added then worked for several weeks without issue after it was added.  

Recently it has been failing with increased frequency and re-running the test fixes it most of the time. When it fails it complains that Gradle returned with a non-zero value and no other error messages.  No external resources are needed at this point.  Can't reproduce this problem on any of my machines and considering how simplistic the script it I suspect that it's something specific to Tracis-CI.  Maybe some sort of resource starvation issue due to the shared environments?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by lessthanoptimal** [comment]
Had to a run it a couple of times to get it to fail again

https://api.travis-ci.org/jobs/200899157/log.txt?deansi=true

**Comment by lessthanoptimal** [comment]
Also worth nothing that 3 environments are being tested and 0 to 3 randomly fail each time.  In this particular instance 2 out of 3 failed.  Here's what it looks like when successful:

https://api.travis-ci.org/jobs/200899159/log.txt?deansi=true

**Comment by lessthanoptimal** [comment]
Still happening.  Any suggestions for debugging this?  Zero issues on all computers I have access to.

**Comment by BanzaiMan** [comment]
Could you try running your build on Docker locally? https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

**Comment by BanzaiMan** [comment]
Looks like it's working for you now. https://travis-ci.org/lessthanoptimal/ejml/builds

Closing.

**Comment by lessthanoptimal** [comment]
Nope please re-open.  I run individual tests multiple times until they pass.  I need to do the docker test you suggested still.

**Comment by BanzaiMan** [comment]
Is there anything left to do here?

**Comment by lessthanoptimal** [comment]
I've yet to do the test.  I probably won't shift development back over to this project for several more weeks.  We can close this ticket for now and re-open it if needed if it makes accounting easier on your end.

**Comment by BanzaiMan** [comment]
Very well. Let us know if you find something that should be fixed on our side.
