### ISSUE TITLE
Error parsing Gemfile on current jruby-head

### ISSUE THREAD

**Issue by prasunanand** [travis-ci/travis-ci#7312]
The new jruby-head is unable to parse Gemfile correctly [link](https://travis-ci.org/SciRuby/nmatrix/jobs/198114642#L732). NMatrix has 4 different gemspecs. It is unable to load the Gemspec both on mac-os and ubuntu.
1. https://travis-ci.org/SciRuby/nmatrix/jobs/198114642
2. https://travis-ci.org/SciRuby/nmatrix/jobs/198114644

**Comment by BanzaiMan** [comment]
Please report the issue to https://github.com/jruby/jruby.

**Comment by prasunanand** [comment]
Thanks @BanzaiMan . Posted an [issue](https://github.com/jruby/jruby/issues/4487).

**Comment by BanzaiMan** [comment]
This is not a Travis issue, as far as I can tell. I'm closing this.
