### ISSUE TITLE
The LinkingTo field in the DESCRIPTION file is ignored

### ISSUE THREAD

**Issue by thk686** [travis-ci/travis-ci#7315]
Any package mentioned in the LinkingTo field of the DESCRIPTION file needs to be made available to packages that eg use Rcpp to compile code on-the-fly. Travis will load the package if it is also included in the Imports directive, but this is not allowed by CRAN.

@craigcitro
@hadley
@jimhester

**Comment by BanzaiMan** [comment]
Is this for R? If so, please follow the instructions in the build log, so that community volunteers are alerted.

**Comment by jimhester** [comment]
Travis does use LinkingTo when installing packages, and you seem to have successful builds as well https://travis-ci.org/thk686/odeintr/builds/201618344, I think this can be closed.

**Comment by thk686** [comment]
Perhaps its is an issue unrelated to Travis -- the problem is that calling
sourceCpp from Rcpp in testthat tests does not work without putting BH in
the Include directive in the DESCRIPTION file. Maybe this is an R runtime
issue? However, adding BH to the Includes section fixed the problem.

**Comment by jimhester** [comment]
I think this is because you have `Rcpp::depends(BH)` in the code you are trying to compile, and R CMD check only makes packages in `Depends`, `Imports`, `Suggests` available at runtime when running tests. If BH is a test dependency you should put it in `Suggests`, not `Imports`.

**Comment by thk686** [comment]
Ah, brilliant. Thanks.

**Comment by BanzaiMan** [comment]
Thanks, @jimhester! I'm closing this now, since the issue appears to have been resolved.
