### ISSUE TITLE
Upcoming Ubuntu 17.04 LTS - Zesty Zapus

### ISSUE THREAD

**Issue by juju4** [travis-ci/travis-ci#7322]
Hello

17.04 is scheduled for April 2017 as of https://wiki.ubuntu.com/Releases
Xenial has not made it into travis (https://github.com/travis-ci/travis-ci/issues/5821)
any shared plan for next release?

Thanks

**Comment by BanzaiMan** [comment]
Hello. Thanks for taking time to open this issue.

We do not have plans to support Zesty at this time. We will be focusing our efforts on Xenial for the longer-term support. Unfortunately, we do not have ETA for that at this time.

If you need these releases right now, we recommend that you run your tests on Docker images.

Thanks!

**Comment by edmorley** [comment]
Note also that 17.04 won't be an LTS release. They are every two years - so 18.04 will instead.
I don't think it makes sense for Travis CI to support non-LTS releases.

**Comment by pachonk** [comment]
I agree. I would rather Travis support the latest LTS than worry about supporting non-LTS versions.

**Comment by andyxning** [comment]
It is in 2018 now and Ubuntu 18.04 has been released. When should the Ubuntu 16.04 be supported? :)

**Comment by pachonk** [comment]
In fairness, Travis' Ubuntu releases are still in maintenance until 19.04
release.

**Comment by andyxning** [comment]
> In fairness, Travis' Ubuntu releases are still in maintenance until 19.04
release.

IMHO, this is a sad news. :(

**Comment by pachonk** [comment]
Well that maintenance cycle is set at Ubuntu and a 5 year cycle is not sad
news.
If there is any sad news, it's that Travis hasn't supported the newer
versions yet.

If it bother you enough, you cold use the containerised setup or switch to
circle ci
