### ISSUE TITLE
Stream Output from travis_wait to Standard Output and Error

### ISSUE THREAD

**Issue by naftulikay** [travis-ci/travis-ci#7323]
Previously reported at: https://github.com/travis-ci/worker/issues/283

> Presently, it appears that the only workaround for long-running builds is to use `travis_wait N` where `N` is the number of minutes to allow a build to run for.

> This command unfortunately does not stream its output to the user, so it is necessary to wait until a job has completely finished before knowing what went wrong. In large test cases or scripts that take 30 minutes to run, it would be nice to see test failures without having to wait the full 30 minutes.

The specific command I'm reporting is [Packer](https://www.packer.io). Sometimes, when Amazon is building an AMI, it takes quite a while for it to transition from `pending` to `ready`, sometimes even over 10 minutes, though I've seen it complete in as little as 2 or 3 minutes in the past.

Therefore, it would be a huge improvement for `travis_wait` to stream the output of stdout and stderr to the console so I can actually monitor its progress.

**Comment by BanzaiMan** [comment]
As I indicated in the original issue, this is not the use case for `travis_wait` as it is currently implemented.

Incidentally, there are other issues with `travis_wait` causing problems, and it will be looked at in the near future.

**Comment by mcasperson** [comment]
The other issue with travis_wait not streaming is that if you have a build that takes too long, you just get a "The job exceeded the maximum time limit for jobs, and has been terminated." error and no additional output at all to help diagnose the issue.

**Comment by naftulikay** [comment]
This is still applicable, as there is no Travis-provided solution to the problem.

**Comment by chabad360** [comment]
A solution for this would be (in your `.travis.yml`):
```yaml
- command-that-takes-a-long-time &
- while [ -e /proc/$! ]; do echo -n "."  && sleep 60; done
```
this will output a `.` (or anything else of your choice) as long as the previously ran process is still running

**Comment by naftulikay** [comment]
This is still applicable and a bug.

**Comment by BanzaiMan** [comment]
As I originally indicated, this is not how the function is designed to work. The use of `travis_wait` is completely optional, and if it does not meet your needs, I suggest looking at other workarounds, as shown in this issue.

We are also able to extend the timeout on a case-by-case basis, so do get in touch via email at support@travis-ci.com if you prefer that.

I'm closing this now.

**Comment by naftulikay** [comment]
For those poor souls who will inevitably run into this issue in the future, I created [travis-pls](https://github.com/naftulikay/travis-pls) explicitly to get around this issue. I had hoped that Travis would fix the issue or provide a solution, but that apparently won't happen.

**Comment by endurance** [comment]
there's always CircleCI.
