### ISSUE TITLE
Python - Include UCS2 compiled versions

### ISSUE THREAD

**Issue by vmuriart** [travis-ci/travis-ci#7329]
For my library [pythonnet](https://github.com/pythonnet/pythonnet) we support CPython built on either [`UCS4` or`UCS2`](https://www.python.org/dev/peps/pep-0261/). Currently all Python instances in Travis are built using `UCS4` and we are unable to test `UCS2` specific sections of the code.

Would it be possible to add python version compiled with `UCS2` that w can use for testing?

**Comment by mingxiaoh** [comment]
we have same request here, would it be possible to add python version compiled with UCS2 that w can use for testing?

**Comment by richvdh** [comment]
The `osx` image comes with a UCS2 build of cpython. To use it, you'll need:

```
language: generic
os: osx
```
You'll probably also want to use `sudo get-pip.py` to install pip. See https://pip.pypa.io/en/stable/installing/ for `get-pip`.
