### ISSUE TITLE
Add the Heroku Toolbelt to the VMs

### ISSUE THREAD

**Issue by markbates** [travis-ci/travis-ci#733]
Because the Heroku gem is deprecated it would be great to have the Heroku toolbelt installed on the VMs so people can have Travis deploy to Heroku when the tests pass, as seen here:

http://metabates.com/2012/10/23/deploying-to-heroku-from-travisci/

Keep up the great work guys!!

**Comment by zupo** [comment]
I'd like to reopen this issue, because running the following command on the new containerized infrastructure is not possible -- it requires sudo:

```wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh```

**Comment by BanzaiMan** [comment]
@zupo Why do you need it? Deployment should be possible without it.

**Comment by zupo** [comment]
I have a script that:

1. shuts down the staging app
2. creates a copy of production db and restores it to staging app
3. runs DB migration scripts
4. starts up the staging app

This is ran on Travis every time there is a change in the migrations dir. And so we get automatic DB migrations testing.

**Comment by BanzaiMan** [comment]
@zupo Could you take a look at https://github.com/travis-ci/apt-package-whitelist, and ask for the source and the package to be whitelisted, please?

**Comment by zupo** [comment]
@BanzaiMan https://github.com/travis-ci/travis-ci/issues/4052

Like so?

**Comment by BanzaiMan** [comment]
@zupo Yup. Thanks.

**Comment by andrecp** [comment]
I am having the same issue as @zupo, any workarounds? Thanks
