### ISSUE TITLE
Update Ubuntu VM's to 16.04

### ISSUE THREAD

**Issue by AraHaan** [travis-ci/travis-ci#7330]
apt-get on the trusty Ubuntu 14.04 VM's does not work anymore because it has reached end of life it seems, however the 16.04 one works when installing gcc / g++ and clang (latest) you guys might need to upgrade the trusty version to that to help with those who need to use those particular compiler versions.

The reason why the trusty build needs an upgrade to 16.04 is when projects (not only C++ or even C ones) but also Python ones, etc. where the language just updates itself where you just need to update the one provided from travis as it is too old to even use successfully.

I hope you guys consider this and hopefully upgrade it ASAP so projects can successfully use apt-get again to install dependencies without building them directly from sources (which on some can easily take over the time limit on builds).

**Comment by BanzaiMan** [comment]
Xenial is on our roadmap, but no ETA at this point.

See #5821, #7322.

**Comment by BanzaiMan** [comment]
Closing this as a duplicate.
