### ISSUE TITLE
R fails to install

### ISSUE THREAD

**Issue by rorynolan** [travis-ci/travis-ci#7334]
@craigcitro @jimhester
See https://travis-ci.org/rorynolan/exampletestr
It fails on the "Installing R" step. 
The command "eval sudo apt-get update -qq " failed. Retrying, 2 of 3.
Is it something I've done? I don't think so because I have travis working on my other repos and I can't see how I've messed it up.
Thanks,
Rory

**Comment by hruffieux** [comment]
Same issue here. Maybe we should cc @craigcitro, @hadley, and @jimhester. 
Thanks.

**Comment by jimhester** [comment]
This is an issue with the travis ppa https://github.com/travis-ci/travis-ci/issues/7332, see that issue for the current status.

**Comment by road2stat** [comment]
Same issue here: https://travis-ci.org/road2stat/msaenet/builds/202785202
Thanks.

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate of #7332.

**Comment by rorynolan** [comment]
Agreed. Thanks guys!

**Comment by rorynolan** [comment]
Just to say this is solved for me now.
