### ISSUE TITLE
I want to trigger deployment for pull requests

### ISSUE THREAD

**Issue by thomblake** [travis-ci/travis-ci#7338]
For my current use case, I want to trigger a deployment for every successful pull request build. But of course I get "Skipping a deployment with the s3 provider because the current build is a pull request." - I would like a way to override this behavior.

**Comment by BanzaiMan** [comment]
This is basically a duplicate of #1946.

**Comment by thomblake** [comment]
@BanzaiMan It's actually pretty different. I don't need anything around encrypted variables, since I only care about PRs from the same repository (kind of standard for private repos), so the variables already work. The only thing I want is a way to have the deploy step actually try to run for PRs, rather than always skip automatically.

**Comment by BanzaiMan** [comment]
In that case, I think you can just create a new topic branch to achieve what you want.

**Comment by thomblake** [comment]
@BanzaiMan I have no idea what you mean by that. Can you elaborate?

I did come up with a workaround for this though - I just took out all the `deploy:` configuration and instead added `pip install awscli` and use a manual deploy script. It would still be nice to be able to do it just using configuration though.

**Comment by BanzaiMan** [comment]
What I meant was this:

```sh-session
$ git checkout -b topic_branch
$ git push origin topic_branch
```


I am not sure why you need a PR to accomplish what you need. Deployment is going to require S3 credentials somewhere, and allowing any PR to do it (or in your script) is going to incur security risk.

**Comment by thomblake** [comment]
I'm still confused. What you described is what we already do - that's how we create PRs. How does that result in deploying my built code to S3? We have Travis run every time a commit is pushed to a PR (as I understand it, this is the usual setup), and I was trying to set it up so that a deployment happens during those runs (for testing purposes).

I'm not sure what you mean by "why you need a PR to accomplish what you need". We're already creating PRs as part of our process for building and deploying software - this is not a new workflow I'm inventing. The plan was to have a deploy happen every time we push to a branch, and it seemed like getting Travis to do the deploy was an obvious way to accomplish that since Travis can supposedly do deployment and we're already doing Travis runs.

Though like I said, this is mostly academic at this point as I've found a workaround and it turns out I actually prefer doing the test deployment *before* running my tests so it's even more likely that the `deploy:` configuration wouldn't be a good fit.

**Comment by majames** [comment]
Can we please re-open this issue? 

I really want to be able deploy on PR and PR only. I want to deploy [storybooks](https://github.com/storybooks/storybook) to my S3 bucket so that reviewers of the PR can view and QA the stories before approving the PR and having it merged to master.

Adding something like `allow_pr` to the `deploy` config would be perfect.

PR is here: https://github.com/devlucky/react-audio-vis/pull/24

**Comment by ngtuna** [comment]
any luck with this @majames ? I am also looking for the travis configuration for deploy the binary to somewhere for each PR, of course for testing purpose

**Comment by austinh** [comment]
Would be great to allow deploys and builds of specific PRs from Travis.
Particularly great for frontend apps where you develop a feature, create a PR, and allow someone to QA before merging to master.
We are not using Travis because of this missing feature.

**Comment by BanzaiMan** [comment]
I understand the usefulness of such a feature, but allowing any untrustworthy PR to deploy your app is simply not acceptable.

**Comment by austinh** [comment]
That's why it could be an optional parameter defaulted to false. Those using private repos with strict permission control should be able to decide whether or not those accessing the build script are acceptable to launch a PR. Especially in the case of a frontend app where all it does is run webpack to compress files and upload them to s3.

**Comment by BanzaiMan** [comment]
For private repositories, I agree that the security is less of a concern, and we do have an internal ticket tracking it. We do not have ETA, though.

**Comment by biodranik** [comment]
This feature is a must to test/QA dev version first, before merging it into a master branch. In our workflow:
- Developer creates a PR, which is built and deployed to GH Pages as a dev version of a web site
- If dev version works fine, then merge to master deploys the site into a production

There should be a way to filter out 3-party requests by checking PR author's permissions/collaborator status. Or at least to run a deploy step manually...

Are there any good workarounds for deployment to Guthub Pages?

**Comment by morgwaiwetrust** [comment]
this feature is a *MUST*
regarding security concerns: it should be implemented to deploy only on PRs originating from the same repository (just like availability for env vars containing credentials etc)

**Comment by housni** [comment]
I also think this is an important feature to have. The decision to deploy via PR should be up to the developer, IMO. Travis can advise us of best practice but it shouldn't limit us. I hope this feature is implemented soon.

**Comment by jake-steeves** [comment]
I would also like to see an allow_pr: true/false feature under the travis deploy options. Although it could potentially be dangerous to automatically deploy on any PR, there are sensible workflows where this feature is safe. Using github protected branches with a conditional "on:" deploy, the deploy would only occur after the PR is reviewed and merged by a project manager. Keeping the setting as default false would prevent it from being misused, but setting it to true is crucial for advanced configurations.

**Comment by trevordmiller** [comment]
I agree that allowing deployment on pull requests is needed to allow QA testing before merging to master - like how [Heroku Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps) work (so you can review a separate deployment from pull request code to ensure everything is working, run end-to-end tests etc. then merge to master and deploy master to production).

**Comment by metaskills** [comment]
> For private repositories, I agree that the security is less of a concern, 
> and we do have an internal ticket tracking it. We do not have ETA, though.

Just FYI, I would be totally interested in that feature for Custom Ink's private organization TravisCI account. The setting requested `allow_pr: true/false` which defaults to false seems to make a lot of sense too.

**Comment by n8n8baby** [comment]
Here's a simple example that will work, although it's not terribly elegant:
```
script:
- sh ./run-tests.sh
# run deploy script when TRAVIS_PULL_REQUEST is not "false"
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || sh ./deploy-pull-request.sh'
```

**Comment by mkay581** [comment]
I would also love this feature but this PR has been closed.

> we do have an internal ticket tracking it. We do not have ETA, though.

@BanzaiMan where is this ticket being tracked? Is it here in this repo?

**Comment by metaskills** [comment]
The only issue I have found with not having this feature officially supported and using the `after_success` is that if the deploy fails for any reason, the branch/build is green. Hence why I think this should be a feature, not a workaround.

**Comment by godban** [comment]
Very useful feature suggestion, why it's closed?

**Comment by sayjeyhi** [comment]
nothing?

**Comment by z3niths** [comment]
3 years passed :P

Workaround, you can add below example code in the script phase.
```
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      bash ./deployStaging.sh
  fi'
```

So every pull request will have one deployment (EX: for staging server)
What I have done inside `deployStaging.sh` are
- prepare the build files from travis
- sync them to a running server 
- bind it with a subdomain EX: branchName.staging.domain.com

So you can have 1 PR / 1 staging environment running.
