### ISSUE TITLE
404 with 'apt-get update' when targeting C/C++

### ISSUE THREAD

**Issue by AraHaan** [travis-ci/travis-ci#7342]
travis is generating 404 on apt-get update when targeting C/C++.
Here is one of my failing builds: https://travis-ci.org/AraHaan/bin2c/builds/202694789
Another: https://travis-ci.org/AraHaan/bin2c/builds/202753872
And another: https://travis-ci.org/AraHaan/bin2c/jobs/202762872
It would be nice if this was to get fixed without me having to manually Add in some things to try to fix apt-get (which is not fully working out rn).

**Comment by BanzaiMan** [comment]
Those 404's are introduced by your mangling of the APT sources; e.g., https://travis-ci.org/AraHaan/bin2c/jobs/202753874#L241. Please verify that your configuration is valid.

I'm closing this now, since I do not believe there is anything for us to do.
