### ISSUE TITLE
Lambda image for tests

### ISSUE THREAD

**Issue by kdybicz** [travis-ci/travis-ci#7343]
Hi,

Is there any chance to provide real Lambda image [(AMI name: amzn-ami-hvm-2016.03.3.x86_64-gp2)](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) as a test environment?

Edit: I guess I should mention that I would need to test Node.js lambda in it.

**Comment by BanzaiMan** [comment]
Hello. What is it in this image that you want but don't get in the current Node.js build image?

Our build images need to run on more than just EC2, so I am afraid this is going to be very difficult to support.

**Comment by kdybicz** [comment]
I'm running some 'integration' tests with binary files precompiled for that environment. They are running fine on my local, but when running them on Travis, with this configuration:
```
language: node_js
node_js:
  - 4
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
```
I'm getting some errors, which could suggest problem with missing dependencies. In theory I can try to recompile everything again, to try to embed all of the dependencies in binaries, but I was hoping to avoid that. At least for now.

**Comment by kdybicz** [comment]
Please ignore me for now. It looks like there is a bug in code or in configure script, that is messing up library references and make it fail on Ubuntu. Will focus on fixing this.

**Comment by kdybicz** [comment]
Yeah, it was missing dependency. So definitively never mind :)
