### ISSUE TITLE
Travis VM can't install mono

### ISSUE THREAD

**Issue by forki** [travis-ci/travis-ci#7344]
It seems Travis cannot install mono any more. See https://github.com/fable-compiler/fable-suave-scaffold/pull/33

https://travis-ci.org/fable-compiler/fable-suave-scaffold/builds/202896722

As requested ccing @joshua-anderson @akoeplinger @nterry

Log:

                           Worker information
    hostname: i-0796329-production-2-worker-org-ec2.travisci.net:80857716-f9b1-40ca-b59d-06c1428524cc
    version: v2.5.0 https://github.com/travis-ci/worker/tree/da3a43228dffc0fcca5a46569ca786b22991979f
    instance: 762d12a:travis:default
    startup: 924.419835ms
    Build system information
    Build language: csharp
    Build group: stable
    Build dist: trusty
    Build id: 202896722
    Job id: 202896723
    travis-build version: f409d292d
    Build image provisioning date and time
    Thu Nov 10 03:26:46 UTC 2016
    Operating System Details
    Distributor ID:	Ubuntu
    Description:	Ubuntu 14.04.5 LTS
    Release:	14.04
    Codename:	trusty
    Linux Version
    4.4.0-45-generic
    Cookbooks Version
    58fad1f https://github.com/travis-ci/travis-cookbooks/tree/58fad1f
    git version
    git version 1.9.1
    bash version
    GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    
    This is free software; you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    gcc version
    gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
    Copyright (C) 2013 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    docker version
    Client:
     Version:      1.12.3
     API version:  1.24
     Go version:   go1.6.3
     Git commit:   6b644ec
     Built:        Wed Oct 26 23:26:11 2016
     OS/Arch:      linux/amd64
    clang version
    clang version 3.5.0 (tags/RELEASE_350/final)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    jq version
    jq-1.5
    bats version
    Bats 0.4.0
    gimme version
    v1.0.0
    nvm version
    0.32.0
    perlbrew version
    /home/travis/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.76
    postgresql client version
    psql (PostgreSQL) 9.6.1
    phpenv version
    rbenv 1.0.0-33-gc7dcaf1
    rvm version
    rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
    default ruby version
    ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    Pre-installed Ruby versions
    ruby-2.2.5
    ruby-2.3.1
    
    $ export DEBIAN_FRONTEND=noninteractive
    W: Size of file /var/lib/apt/lists/dl.google.com_linux_chrome_deb_dists_stable_main_binary-amd64_Packages.gz is not what the server reported 1156 1170
    W: Size of file /var/lib/apt/lists/toolbelt.heroku.com_ubuntu_._Packages.gz is not what the server reported 721 725
    W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-updates_multiverse_source_Sources.gz is not what the server reported 7372 7374
    W: Size of file /var/lib/apt/lists/ppa.launchpad.net_webupd8team_java_ubuntu_dists_trusty_main_binary-amd64_Packages.gz is not what the server reported 3108 3110
    W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
    
    E: Some index files failed to download. They have been ignored, or old ones used instead.
    Reading package lists...
    Building dependency tree...
    Reading state information...
    libc6 is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 146 not upgraded.
    Removing symlink /usr/lib/jvm/java-8-oracle-amd64
    $ sudo rm -f /usr/lib/jvm/java-8-oracle-amd64
    Reload jdk_switcher
    $ source $HOME/.jdk_switcher_rc
    
    C# support for Travis-CI is community maintained.
    Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry
    Installing Mono
    Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.a9RhjxNFtu --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
    gpg: key D3D831EF: public key "Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>" imported
    gpg: Total number processed: 1
    gpg:               imported: 1  (RSA: 1)
    W: Size of file /var/lib/apt/lists/packagecloud.io_rabbitmq_rabbitmq-server_ubuntu_dists_trusty_main_binary-amd64_Packages.gz is not what the server reported 353 2072
    W: Failed to fetch https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/dists/trusty/main/source/Sources  Hash Sum mismatch
    
    W: Failed to fetch https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch
    
    E: Some index files failed to download. They have been ignored, or old ones used instead.
    
    
    The command "sudo apt-get update -qq" failed and exited with 100 during .
    
    Your build has been stopped.

**Comment by akoeplinger** [comment]
Please see #7332 and https://www.traviscistatus.com/incidents/xlhdxb80swcq

**Comment by forki** [comment]
It says fixed 7h ago, but I was seeing this like 2h ago?

Am 18.02.2017 13:47 schrieb "Alexander Köplinger" <notifications@github.com

**Comment by akoeplinger** [comment]
Ah, ok. Please reply in the other issue so the Travis folks get notified.

**Comment by vineus** [comment]
Same issue for `dotnet: 1.0.0-preview2-003131`

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-build/pull/963.

**Comment by cotsog** [comment]
@leezer3 @vineus @tengyifei: we've shipped a fix for this. Can you tell us if it fixes it on your side as well? Thank you for your patience!

**Comment by cotsog** [comment]
cc @lol768: we've shipped a fix for this. Can you tell us if it fixes it on your side as well?

**Comment by vineus** [comment]
@cotsog : this is fixed now!

Thank you so much!

**Comment by lol768** [comment]
> cc @lol768: we've shipped a fix for this. Can you tell us if it fixes it on your side as well?

Looks good to me, many thanks for promptly sorting this 😄

**Comment by cotsog** [comment]
@vineus, @lol768: Thanks for the confirmation!
