### ISSUE TITLE
Inconsistent run times in a build

### ISSUE THREAD

**Issue by DRMacIver** [travis-ci/travis-ci#7347]
[This build for hypothesis-python](https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/203112422) is currently reporting that the build ran for 5 min 4 sec.

However it's also reporting that the TASK=check-quality entry in the build matrix took 8 min 26 sec.

It seems unlikely that both of these things are true: A build step can't take longer than the entire build!

I don't have a consistent reproduction for this problem - it doesn't seem to have happened on any other builds I see on the same repository - and it's not a major issue for me, but I thought it worth mentioning.

**Comment by alexwlchan** [comment]
A few more examples from the hypothesis-python builds:

* [201569724](https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/201569724), build ran for 10 min 12 sec, the TASK=check-py27 job ran for 25 min 29 sec.
* [200714474](https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/200714474), build ran for 10 min 54 sec, the TASK=check-py27 job ran for 34 min 33 sec.

**Comment by BanzaiMan** [comment]
Did you restart these builds?

**Comment by alexwlchan** [comment]
> Did you restart these builds?

Maybe? There’s been enough flakiness in the Hypothesis tests that I do it somewhat often, but I don’t remember exactly when I’ve done it.

**Comment by DRMacIver** [comment]
On experimentation I can confirm this is the source of the problem. I restarted the documentation task on [this build](https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/203119352) and now the build is showing that it completed in 40 seconds.

**Comment by BanzaiMan** [comment]
Restart naturally presents a problem as to what "Ran for …" time should indicate. If you didn't restart all the jobs in the build matrix, what should it represent? Keep in mind that the build ran days (or even months!) ago. Currently, it represents the time it took from the last (re)start and the last end.

There is a "Total time" that sums up all the jobs' elapsed times.

**Comment by slodki** [comment]
"Ran for..." defined as "from last (re)start to last end" is meaningless and have no correlation with build or jobs if a job has been restarted.

```
time [min]:  0        10        20        30        40        50
job 1.1:     <S------F>          <R--------------------------C>
job 1.2:     <S------F>                    <R------C>
```
Current Travis-web:
- job 1.1 ran for 30 min
- job 1.2 ran for 10 min
- build ran for 20 min
-- there was no period of 20 min activity on job 1.1 nor 1.2
-- the build activity for first try was 10 min and 30 min for 2nd
-- it's impossible build last shorter then one of the jobs inside

Result: running time for build is meaningless, it's just distance from one point in one job to some point in different job.

Should be:
a) build ran for 40 min (if we want include history of build activity)
b) build ran for 30 min (if we want analyze only last instances of jobs the same way the total time is counted)
c) build run time N/A (user manually restarted some jobs in this build)

Next problem: if user restart a job and cancel it before restart take place (last restart=last end):
- run time for the build is not displaying while other jobs are still running (it's updated when all jobs finish)
- run time for the build is lost if no other jobs are running

**Comment by slodki** [comment]
The problem still exists

**Comment by slodki** [comment]
Tested today - the problem still exists

**Comment by slodki** [comment]
unstale

**Comment by slodki** [comment]
unstale

**Comment by slodki** [comment]
unstale

**Comment by slodki** [comment]
Unstale
