### ISSUE TITLE
Ruby 1.9.2 binary broken on Trusty (14.04)

### ISSUE THREAD

**Issue by ms-ati** [travis-ci/travis-ci#7348]
For an example, please see this build:
https://travis-ci.org/tcrayford/Values/jobs/202768554

The following Ruby binary is found:
https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-1.9.2-p330.tar.bz2

But the RVM install fails with:

```
Libraries missing for ruby-1.9.2-p330: libruby.so.1.9. Refer to your system manual for installing libraries
Mounting remote ruby failed with status 10, stopping installation.
Gemset '' does not exist, 'rvm ruby-1.9.2-p330 do rvm gemset create ' first, or append '--create'.
The command "rvm use 1.9.2 --install --binary --fuzzy" failed and exited with 2 during .
```

This happens every time and in multiple repositories.

**Comment by segiddins** [comment]
This broke for us on RubyGems/RubyGems sometime last week, without us touching our Travis config

**Comment by BanzaiMan** [comment]
Rebuilding 1.9.2-p330 for Trusty here now: https://travis-ci.org/travis-ci/travis-rubies/jobs/230758072

**Comment by BanzaiMan** [comment]
@segiddins I don't know if this was a cause of recent build issues, though. As you can see, this has not been touched since February until now. Do you have a link to the build that shows your problem?

**Comment by BanzaiMan** [comment]
The new archive is still unusable.

**Comment by simi** [comment]
@BanzaiMan https://travis-ci.org/rubygems/rubygems/jobs/229643203 for example.

**Comment by BanzaiMan** [comment]
@simi That job ran on Precise (and therefore unrelated to this issue). There is a 1.9.2-p330 archive for it, but RVM is not resolving to that version for whatever reason. I'll copy 1.9.2-p330 to 1.9.2.

**Comment by BanzaiMan** [comment]
Precise 1.9.2-p330 archive has been copied to 1.9.2

**Comment by BanzaiMan** [comment]
The 1.9.2 archive for Trusty has been [rebuilt](https://travis-ci.org/travis-ci/travis-rubies/jobs/230777074) and [tested](https://travis-ci.org/BanzaiMan/travis_production_test/jobs/230761816#L153).

**Comment by segiddins** [comment]
Still failing on Precise: https://travis-ci.org/rubygems/rubygems/jobs/230818251

**Comment by BanzaiMan** [comment]
@segiddins Thanks for the report. Please open a separate issue.

**Comment by zismailov** [comment]
Still failing: [](https://travis-ci.org/julik/ru_propisju/jobs/242392752/)
