### ISSUE TITLE
CTest produces no output for >10 minutes

### ISSUE THREAD

**Issue by qris** [travis-ci/travis-ci#7350]
Dear Travis support,

Some of my builds (for example, [this one](https://travis-ci.org/boxbackup/boxbackup/jobs/203208409)) are timing out with the following error:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

The problem is that I'm running tests using CTest (for CMake builds, which is one of the two buildsystems) and it seems to buffer output and rarely forward it to the console. This is quite annoying, and probably needs to be fixed within CTest, but I [read in the Travis manual](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) that "When in doubt, file a ticket or email us first to see if something could be improved about this particular command first." So I am filing a ticket :)

This test should not take anything like 10 minutes to run, and I don't know why it does. Because CTest is buffering the output, and Travis is killing it early, I don't get to see it, so I don't know what's wrong. The [debug version of the same test](https://travis-ci.org/boxbackup/boxbackup/jobs/203208408) passed in <2 minutes.

I could wrap each test command in travis_wait, only when run through Travis, but I'm wondering if you have any other ideas?

Thanks, Chris.

**Comment by BanzaiMan** [comment]
Try prepending the command in question with `travis_wait`. This will send the process in the background, while writing something to STDOUT to keep the job alive up to 20 minutes. This will give you an idea whether or not the command is truly hung.

My guess is that the job is just too slow on the VM; it is running on older hardware, and despite what your tools indicate it probably does not have 2 processors to run the job.

**Comment by BanzaiMan** [comment]
Can this be closed?

**Comment by qris** [comment]
I think so, thanks!
