### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by vlazzarini** [travis-ci/travis-ci#7353]
We're getting this in Trusty (two projects with similar failures)

The command "sudo apt-get install -qq cmake libsndfile1-dev libasound2-dev libjack-dev portaudio19-dev libportmidi-dev libpulse-dev swig liblua5.1-0-dev python-dev puredata-dev default-jdk libfltk1.1-dev libfluidsynth-dev liblo-dev fluid ladspa-sdk libboost-dev libboost-serialization-dev libpng-dev dssi-dev libstk0-dev libgmm++-dev bison flex libportsmf-dev libeigen3-dev libcunit1-dev python-tk" failed and exited with 100 during .

**Comment by roidelapluie** [comment]
You need to run sudo apt update (e.g in before_install)
