### ISSUE TITLE
OSX: Nix doesn't set SSL_CERT_FILE correctly, so cache uploading fails

### ISSUE THREAD

**Issue by domenkozar** [travis-ci/travis-ci#7355]
Example build, see at the very bottom of the log: https://travis-ci.org/input-output-hk/cardano-sl/jobs/203753453

```
failed to upload cache
curl: (51) SSL: certificate verification failed (result: 5)
```

I'm looking into this.

**Comment by domenkozar** [comment]
```
$ ls $SSL_CERT_FILE
/Users/travis/.nix-profile/etc/ssl/certs/ca-bundle.crt
```

This is https://github.com/NixOS/nix/issues/921, which is not released yet.

**Comment by BanzaiMan** [comment]
> Nix support for Travis CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @domenkozar @garbas @matthewbauer

**Comment by domenkozar** [comment]
Workaround is to use `nix-env -i curl`.

**Comment by domenkozar** [comment]
The fix is now in maintenance branch: https://github.com/NixOS/nix/commits/1.11-maintenance

**Comment by domenkozar** [comment]
Nix 1.11.7 has been released that fixes this issue properly.
