### ISSUE TITLE
Debugging a job runs a VM with a different environment

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#7357]
I used the ``Debug job`` feature today. But when I applied our commands one by one, I discovered that the debug VM is inconsistent with the normal VM.
We run the sudo-enabled precise VM for PHP. In this VM, ``nvm`` is available, which allows me to force using node 6 for our gulp-based asset pipeline (instead of the default 0.10 version). But in the debug VM, ``nvm`` is not available.

Fortunately, the issue I was debugging had nothing to do with this part, so I was able to skip the asset processing part. But it makes the usefulness of the debugging feature questionable (if I was about debugging this part, it would have been very weird).

**Comment by BanzaiMan** [comment]
I think this has more to do with the way debug session is started than the VM itself.

`nvm` should be available for login sessions (it is `source`d from `/etc/profile.d/nvm.sh`), but the debug session is not a login shell.
