### ISSUE TITLE
[secure] value seen publicly when errored

### ISSUE THREAD

**Issue by MiCHiLU** [travis-ci/travis-ci#7359]
```
Setting environment variables from .travis.yml
$ export DOCKER_PASS=[secure]
/home/travis/build.sh: eval: line 59: syntax error near unexpected token `('
/home/travis/build.sh: eval: line 59: `export DOCKER_PASS=inMTq+K6d3F(}hhv  2>/dev/null'
The previous command failed, possibly due to a malformed secure environment variable.
Please be sure to escape special characters such as ' ' and '$'.
For more information, see https://docs.travis-ci.com/user/encryption-keys.
```

**Comment by BanzaiMan** [comment]
This is a variation of #1775 and others, which is documented in https://docs.travis-ci.com/user/encryption-keys#Note-on-escaping-certain-symbols.

**Comment by BanzaiMan** [comment]
Looks like our previous attempt to hide it from the logs still has some cases not covered.

**Comment by MiCHiLU** [comment]
@BanzaiMan 
OK, it was documented already.
Thank you!

**Comment by BanzaiMan** [comment]
@MiCHiLU Well, yes, it is documented (see the last line of the quoted log above). The intent, though, is that we want to avoid having to show the `syntax error…` message. Assuming that you have already changed `$DOCKER_PASS`, do you might sharing the previous value, so that we can test this case we apparently missed?

**Comment by MiCHiLU** [comment]
@BanzaiMan 
It is a real log. I already changed my password on Docker.io, so it is no problem.

**Comment by BanzaiMan** [comment]
To confirm, it was `inMTq+K6d3F(}hhv`?

**Comment by MiCHiLU** [comment]
@BanzaiMan YES.
