### ISSUE TITLE
No Builds or branches on working CI

### ISSUE THREAD

**Issue by moogus** [travis-ci/travis-ci#7360]
### [Travis CI - for repo](https://travis-ci.com/ConnectedHomes/bgMobileAppTransformation)

Hi

I have set up a simple CI for a react native project only to ensure all testing passes.  For some reason I have no branches and no build history even though I have multiple CI runs. Am I missing something obvious or is something weird going on.

Darren

```bash
language: node_js
node_js:
- '6'
sudo: required
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm config set registry http://registry.npmjs.org/
  - npm config set spin false
  - git config user.name 'travis-build'

install:
  - yarn install

script:
  - npm test

notifications:
  email: false
```

**Comment by BanzaiMan** [comment]
Could you clarify this?

> I have no branches and no build history even though I have multiple CI runs.

Our records indicate that we have run 9 builds for your repository, and they should show up.

**Comment by BanzaiMan** [comment]
Push builds are disabled, so you would see the PR builds only at https://travis-ci.com/ConnectedHomes/bgMobileAppTransformation/pull_requests.

**Comment by moogus** [comment]
![image](https://cloud.githubusercontent.com/assets/4889659/23199953/7ff83188-f8c9-11e6-9ce5-03b5a95a86f5.png)

![image](https://cloud.githubusercontent.com/assets/4889659/23199967/8c10e0fa-f8c9-11e6-840f-c4b01185043f.png)

**Comment by BanzaiMan** [comment]
Do you see them in https://travis-ci.com/ConnectedHomes/bgMobileAppTransformation/pull_requests?

**Comment by moogus** [comment]
Yes but I have no radiator and no branches doesn't seem right.

![travis build passing](https://travis-ci.com/ConnectedHomes/bgMobileAppTransformation.svg?token=MTGTWp56cUJqdzRmXE2t&branch=master)](https://travis-ci.com/ConnectedHomes/bgMobileAppTransformation)

**Comment by moogus** [comment]
ok so if I enable that it should pick it up? We haven't done that for any of the other repos.

**Comment by BanzaiMan** [comment]
There is no build for any branch. They are for push builds. Since your repository doesn't allow push builds to run, the badge will not show the status.

If you enable push builds, the badge will show the status for the branch involved, and https://travis-ci.com/ConnectedHomes/bgMobileAppTransformation/builds will show them.

**Comment by moogus** [comment]
Ok thanks I'll give it a try

**Comment by moogus** [comment]
Totally worked thanks!!!
