### ISSUE TITLE
Pull Request not updated with completed build status

### ISSUE THREAD

**Issue by bjackman** [travis-ci/travis-ci#7363]
This build: https://travis-ci.org/ARM-software/lisa/builds/204154420 completed at 11:20:26 UTC [1], but as of 13:59:08 UTC the corresponding [Pull Request](https://github.com/ARM-software/lisa/pull/280) still says "Some checks haven’t completed yet".

Am I missing anything?

[1] From Travis' log: `travis_time:end:0c29c24d:start=1487762417181737107,finish=1487762426801594032,duration=9619856925
[0K`

Thanks

**Comment by jakirkham** [comment]
Also am seeing cases where there is not even a pending status on Travis CI commits despite the builds being queued or running. In some cases, these statuses are showing up way after the fact. Am seeing issues with this going back at least 11hrs. @BanzaiMan, do you have any idea what is going on?

**Comment by BanzaiMan** [comment]
Thanks for opening this issue. We are looking into this now.

**Comment by MariadeAnton** [comment]
@bjackman seems the status are have been reported at https://github.com/ARM-software/lisa/pull/280, is that possible? Are you experiencing a delay or is it working now? Have you recently updated ARM-software's 3rd party app restrictions in GitHub?

@jakirkham got a link to one of your repos affected by this? Is this behaviour consistent?

Thank you!

**Comment by bjackman** [comment]
ARM-Software's permissions haven't been updated. The PR I originally linked is now updated and I'm not experiencing any delays in the repo in question any more. I'm not going to close this issue but feel free to do it yourself.

**Comment by jakirkham** [comment]
I think this is no longer occurring, @MariadeAnton. Eventually all builds missing the status got them though several hours later. Perhaps there was a GitHub webhook outage at the time. Not sure.

**Comment by BanzaiMan** [comment]
I'm closing this for now. If you see a similar problem, do open a new issue. Thank you.
