### ISSUE TITLE
Triggering manual build for individual commits via UI 

### ISSUE THREAD

**Issue by MarcinOrlowski** [travis-ci/travis-ci#7364]
I got a project which is configured to be tested by Travis on PR only and "Build pushes" is OFF. Unfortunately there's no way to manually trigger the build on push in such case which would be sometimes useful. When I go to "More Options" -> "Requests" I see the pushes but last column says "Build type disabled via repository settings". I wish there'd be a button or so to just build that commit. For now, I need to go to global settings (btw: I'd be great if we'd set push/pr settings per branch too), enable "Build pushes", do artificial commit and push.

**Comment by acnagy** [comment]
Hey @MarcinOrlowski - thanks for opening this issue, it's a good suggestion to have that override "build this commit" in the UI. That said, would it be possible for you to try triggering a build via api? Our v3 api, which is in the works right now, supports this: https://docs.travis-ci.com/user/triggering-builds You can also pass in `"sha": "123abc...."` in the request body to build a specific commit.

**Comment by MarcinOrlowski** [comment]
Thanks for the API hint, will try it, yet I definitely would prefer having that in UI.

**Comment by acnagy** [comment]
@MarcinOrlowski Sounds good! Let us know how it goes

**Comment by MarcinOrlowski** [comment]
BTW: Do you want me to post separate issue in regards of configuration per branch?

**Comment by BanzaiMan** [comment]
@MarcinOrlowski There is no need for that, since @acnagy changed the description of this issue to reflect your request. Thanks!

**Comment by mnquintana** [comment]
This would really be more helpful in the UI - sometimes Travis fails to even attempt a build on a new commit, which makes it impossible to trigger in the UI without pushing another new commit or going and messing with the API.

**Comment by chris-ratcliffe** [comment]
@MarcinOrlowski , were you able to get the travis API to properly start travis build jobs using specific commits?  I am attempting to do now, and each time I try, it always just uses the latest commit.  I opened issue #8300 for the issue, but I am still not clear if I am simply providing the sha incorrectly in the payload.

**Comment by MarcinOrlowski** [comment]
@chris-ratcliffe no, sorry. I do not think this is the proper way of fixing thing, so I ditched Travis instead.

**Comment by timofonic** [comment]
@BanzaiMan Any news to have this available in the future?

**Comment by BanzaiMan** [comment]
https://blog.travis-ci.com/2017-08-24-trigger-custom-build
