### ISSUE TITLE
R-devel-mavericks-signed.pkg no longer available for download from research.att.com

### ISSUE THREAD

**Issue by lukasstadler** [travis-ci/travis-ci#7370]
looks like https://r.research.att.com/mavericks/R-devel/R-devel-mavericks-signed.pkg was removed.
(or renamed to https://r.research.att.com/mavericks/R-devel/R-devel-mavericks.pkg ?)

failing log:
https://travis-ci.org/gagolews/stringi/jobs/204334607

/cc @craigcitro @jimhester @s-u

**Comment by lukasstadler** [comment]
AFAICS, the r.research.att.com URL was introduced by https://github.com/travis-ci/travis-build/pull/801

**Comment by s-u** [comment]
This typically means that something broke in the build process of the nightly build (either current R trunk doesn't build or there is some issue), so best to report to R-SIG-Mac so it can be fixed.

**Comment by lukasstadler** [comment]
I posted to R-SIG-Mac (waiting for list moderator to approve).

**Comment by s-u** [comment]
The signing has failed so only the unsigned package was available. It's now fixed, but let me know if you see it again as the cause is not necessarily known.
I don't know what you use it for, but you could decide to use the tar ball or fall back to the unsigned one depending on what you want.

**Comment by lukasstadler** [comment]
I guess the file will then reappear with the next nightly build? because the file still appears to be missing.

**Comment by lukasstadler** [comment]
https://r.research.att.com/mavericks/R-devel/R-devel-mavericks-signed.pkg is still missing, maybe https://r.research.att.com/mavericks/R-devel/sign contains a hint as to why:
```
unlock-keychain "-p" "RS1" "/Users/urbanek/Library/Keychains/R-sign.keychain"
productsign: error: Could not find appropriate signing identity for “Developer ID Installer”. 
```

**Comment by s-u** [comment]
Why is clear, but it's unclear how to solve it, because the the unlock succeeds and the key is valid. Also it works in a ssh session, so it's unclear why it doesn't work in the cron job ... still trying to figure our how to get around it. As mentioned above, you can use the tar ball or fall back to unsigned pkg if it's critical.

**Comment by rubak** [comment]
With the upcoming registration of C routines in R-devel (R 3.4) it would be really nice to be able to test packages with compiled code on all platforms (and OSX is not available on R-hub yet). Would it be an option to temporarily use the unsigned pkg here on travis or is that a security problem?
cc/ @craigcitro @jimhester @s-u

**Comment by lukasstadler** [comment]
the signed package is available again. thanks!
