### ISSUE TITLE
csharp builds failing

### ISSUE THREAD

**Issue by LeonidVeriga** [travis-ci/travis-ci#7374]
@joshua-anderson @akoeplinger @nterry

**csharp** language builds started failing https://travis-ci.org/bridgedotnet/Bridge/builds/204771569#L1961

A build, against the commit successfully passed two days ago, fails now also https://travis-ci.org/bridgedotnet/Bridge/builds/204184176#L1968

```
* Assertion at metadata.c:980, condition `index < meta->heap_blob.size' not met
Stacktrace:
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.Assembly.InternalGetAssemblyName (string,System.Reflection.AssemblyName) [0x00000] in <f712f98eb8e445c8918edaf595bbe465>:0
```

Please find the error logs attached [log.txt](https://github.com/travis-ci/travis-ci/files/799040/log.txt)

**Comment by akoeplinger** [comment]
@LeonidVeriga can you please trigger a few more builds and see if it is reproducible? Mono 4.8 just rolled out, maybe you're hitting a regression.

**Comment by LeonidVeriga** [comment]
@akoeplinger, thanks for swift replay.
Infortunately, I tried again several times - still the same error.

**Comment by akoeplinger** [comment]
@LeonidVeriga now that a few more Mono releases happened can you please try again with latest Mono and see if the issue still occurs? If it does please file a bug at https://bugzilla.xamarin.com since it's not a Travis related issue :)

**Comment by LeonidVeriga** [comment]
Thanks @akoeplinger, we will log a Mono issue.
