### ISSUE TITLE
Dub fails to fetch libasync package

### ISSUE THREAD

**Issue by qznc** [travis-ci/travis-ci#7375]
Failed build: https://travis-ci.org/qznc/prema/builds/204959170

It works locally, but not in Travis. I just upgraded all dependencies and libasync is [available](https://code.dlang.org/packages/libasync) on code.dlang.org.

cc @MartinNowak @klickverbot @ibuclaw

**Comment by qznc** [comment]
Just saw this forum post. It might be the server failing?
https://forum.dlang.org/post/o8np89$1iqo$1@digitalmars.com

**Comment by SingingBush** [comment]
may be related to this [issue](https://github.com/dlang/dub/issues/1089) with dub in which optional dependencies are not being treated as optional.

I can build locally (using dub 1.2.2) so it may be worth updating the dub version used by travis (1.2.1) although I cannot confirm if that will fix it.

**Comment by wilzbach** [comment]
Yes that was a server issue:
Since 1.5.0 dub ships with backup mirrors by default.
Also @qznc package builds fine, so this can be closed.
https://travis-ci.org/qznc/prema/builds/240808090
