### ISSUE TITLE
Latest PHP releases cannot be used with Travis CI

### ISSUE THREAD

**Issue by ottlinger** [travis-ci/travis-ci#7377]
After new releases of PHP are out I tried to use them in my .travis.yml.

The builds fail:
* https://travis-ci.org/ottlinger/hornherzogen/builds/204973640 main build
* https://travis-ci.org/ottlinger/hornherzogen/jobs/204973650 PHP 7.1.2
* https://travis-ci.org/ottlinger/hornherzogen/jobs/204973645 PHP 7.0.16

It seems that the new versions are not available - maybe due to a failing
https://github.com/travis-ci/php-src-builder

Thanks for any help :-)

**Comment by BanzaiMan** [comment]
7.0.16 and 7.1.2 are available now. If you'd like, please restart the affected jobs.

**Comment by ottlinger** [comment]
@BanzaiMan thanks, works like a charm!
