### ISSUE TITLE
Note about sudo is unnecessary. Only display if necessary.

### ISSUE THREAD

**Issue by fulldecent** [travis-ci/travis-ci#7378]
> This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
> If you require sudo, add 'sudo: required' to your .travis.yml
> See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

This message is uselessly displayed on billions of build reports.

Instead, please update the `sudo` command to output this message and die.

**Comment by BanzaiMan** [comment]
We now replace `/usr/bin/sudo` with a small script. See https://github.com/travis-ci/travis-build/pull/999
