### ISSUE TITLE
Random "The repository at document-scanner/document-scanner-aggregator was not found."

### ISSUE THREAD

**Issue by krichter722** [travis-ci/travis-ci#7382]
I'm seeing random `The repository at document-scanner/document-scanner-aggregator was not found.` after pushing commits to travis-ci.org for a project which worked fine and 100% of time (> 200 builds over months). I encountered the failure 3 times now for 30 minutes up to 1 day. It resolves automatically. All other projects seem to operate fine and there're no message is the status (checked https://www.traviscistatus.com/ and see nothing in the RSS feed).

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by krichter722** [comment]
Another project, but that doesn't matter: reloading https://travis-ci.org/krichter722/checkstyle/jobs/205821482 causes the following captured situation:

![travis ci test and deploy your code with confidence](https://cloud.githubusercontent.com/assets/4369372/23367286/028dc3a8-fd0a-11e6-92f4-57aa3a96efc0.png)

Checked with Firefox 51.0.1 and konqueror 4:16.04.3-0ubuntu1

**Comment by BanzaiMan** [comment]
Do you still see this issue? We did have some database connexion issues.

**Comment by krichter722** [comment]
> Do you still see this issue? We did have some database connexion issues.

For now it's resolved. Let's assume that it is in general. If it comes back, I'll reopen the issue. Thank you!
