### ISSUE TITLE
Travis CI API returns builds for after_number that came before

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#7384]
Using the Travis CI API, if I request all builds after a particular build number using the URL below. Instead of getting build numbers greater than `12702`, I get build numbers less than `12702` (e.g. `12701`). This seems like behavior one would want with a `before_number` parameter, but not for an `after_number` parameter.

```
https://api.travis-ci.org/repos/{repo_slug}/builds?event_type=pull_request&after_number=12702
```

**Comment by BanzaiMan** [comment]
Could you give a complete URL?

**Comment by jakirkham** [comment]
Sure.

```
https://api.travis-ci.org/repos/conda-forge/staged-recipes/builds?event_type=pull_request&after_number=12702
```

**Comment by cvrabie** [comment]
Can confirm this for the .com api as well.

**Comment by neutrinog** [comment]
This doesn't seem to be fixed yet.

**Comment by hahmed** [comment]
Can confirm this is an issue, opened up a PR to fix this.

https://github.com/travis-ci/travis-api/pull/601

**Comment by joecorcoran** [comment]
AFAIK this behaviour is needed by some consumers of the API, including our own web UI. Admittedly it is a badly-named param, but changing it isn't so simple.

Pinging @drogus for some feedback on this.

**Comment by timofonic** [comment]
@BanzaiMan @drogus @hahmed any news about this? Are there some plans? Excuse for asing on too many issues, but I'm interested in knowing about fixes of certain bugs and features in Travis-CI.

**Comment by sbp** [comment]
The relevant information on the outcome of this bug appears to be here:

https://github.com/travis-ci/travis-api/pull/601#issuecomment-355993168

Summary: the property was working as intended and just badly named, and a way to achieve the desired behaviour may exist in v3 of the API.
