### ISSUE TITLE
Networking errors installing Mono

### ISSUE THREAD

**Issue by Netshroud** [travis-ci/travis-ci#7389]
https://travis-ci.org/SteamRE/SteamKit/builds/205506614

Installing Mono keeps getting 503s, seemingly it's causing build failures more frequently than the build succeeds.

If I try the URLs listed in the build log from my own machines, it consistently works.

**Comment by Joshua-Anderson** [comment]
cc @akoeplinger

Anything going on in the mono repository end?

**Comment by akoeplinger** [comment]
Looks like an issue with the CDN.

@directhex anything we can do to diagnose this?

**Comment by directhex** [comment]
No obvious issues on the back-end, seems purely a CloudFront problem?

**Comment by akoeplinger** [comment]
@Netshroud can you please confirm if this issue still exists or close the issue otherwise?
