### ISSUE TITLE
Setting CACHE_NAME is not sharing cache between jobs

### ISSUE THREAD

**Issue by andreif** [travis-ci/travis-ci#7392]
I am trying to collect Python coverage.py results from all test jobs of the same build in a separate job where they are combined, reported and failed if coverage is not sufficient. 

For that I am trying to use [`CACHE_NAME`][1] environment variable but it seems having no effect. Searching for `CACHE_NAME` [does not show][2] where it's used, so I am not sure if it's still available. 

Is there a better way to collect output from other jobs _within the same build_? 

I must test with various Python versions, and using [`tox`][3] doesn't work due to missing Pythons since I can choose just one version via matrix. Plus, it's harder to understand from `tox` output where it failed -- Travis matrix is much easier in this respect, although slower.

Example of failing build https://travis-ci.org/5monkeys/django-bananas/builds/205764861

[1]: https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices
[2]: https://github.com/search?q=org%3Atravis-ci+CACHE_NAME&type=Code&utf8=✓
[3]: https://github.com/tox-dev/tox

**Comment by andreif** [comment]
@BanzaiMan Hi, I think you were building support for that. Could you confirm if one can still use `CACHE_NAME`?

**Comment by BanzaiMan** [comment]
While your jobs share two environment variables (`CACHE_NAME` and `COVERAGE_FILE`), they do not share `TOXENV`. As explained in https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices, this difference causes the cache names to be different, and your jobs do not share the cache as a result.

**Comment by andreif** [comment]
To solve this I made a small utility for stashing coverage files to some server and then pulling them back for combining and reporting total coverage: https://github.com/andreif/stasher
