### ISSUE TITLE
Add support for JDK 9 EA with Jigsaw

### ISSUE THREAD

**Issue by lpandzic** [travis-ci/travis-ci#7397]
https://jdk9.java.net/jigsaw/

**Comment by BanzaiMan** [comment]
Duplicate (or something close to it) of #7253.

**Comment by lpandzic** [comment]
I'm not sure it actually is a duplicate.
JDK 9 currently has 2 EA builds, one with Jigsaw (https://jdk9.java.net/jigsaw/) and one without (https://jdk9.java.net/download/). How can I build my project on Travis with Jigsaw?

**Comment by BanzaiMan** [comment]
Hmmm. Our OracleJDK support relies on these archives: https://launchpad.net/~webupd8team/+archive/ubuntu/java. If they don't have Jigsaw support, the method I showed in https://github.com/travis-ci/travis-ci/issues/7253 won't work. There may be a way to automate installation of the archive from java.net, but I don't know what that might be.
