### ISSUE TITLE
Cache virtualenv and installed packages

### ISSUE THREAD

**Issue by standage** [travis-ci/travis-ci#7399]
My builds for https://travis-ci.org/dib-lab/kevlar/ spend a lot of time compiling one of the pip-installed pre-requisites pysam. I was hoping that adding `cache: pip` would eliminate this, but it appears that this simply caches the package sources: pysam's C/C++ extensions are still compiled each time. I thought about just adding the virtualenv directory to the cache explicitly via its path, but I wasn't sure how python 2.7 vs 3.5 would be handled, or if this might blow up in other ways.

Is there any way I can cache the *compiled* dependencies?

**Comment by thedrow** [comment]
You can enable ccache which will speed up the C/C++ extensions compilation.
This needs to be done manually. See https://docs.travis-ci.com/user/caching/#ccache-cache
