### ISSUE TITLE
Stuck on Synchronizing from GitHub

### ISSUE THREAD

**Issue by lmaccherone** [travis-ci/travis-ci#740]
Using this account (lmaccherone), I've signed up for a Travis-CI account but when I go to my profile, I get the message 

```
Please hold on ...
We are synchronizing your data from GitHub.
```

I am affiliated with several Organizations on GitHub and one or more of them have private repositories. I would be happy if only my own repositories were synchronized, but as it is now I can't use Travis-CI at all.

**Comment by cyberlaunch** [comment]
![error4](https://cloud.githubusercontent.com/assets/13743035/9191265/c087f88a-401c-11e5-9bf4-c777faa2b4d0.jpg)

Please help

**Comment by drogus** [comment]
@cyberlaunch sorry, but this is an issue tracker for Travis CI, which is a continuous integration platform, I think that you should contact maintainers of "Sony Mobile Flasher" instead
