### ISSUE TITLE
pytest command doesn't work for python 3.3 or 3.4

### ISSUE THREAD

**Issue by jdidion** [travis-ci/travis-ci#7400]
I have a makefile that calls pytest, and I call that make target from my .travis.yml file. When testing on python >= 3.5 this works fine, whereas python < 3.5 fails. For example, see:

https://travis-ci.org/jdidion/atropos/builds/206020042

**Comment by andreif** [comment]
@jdidion Have you tried `py.test` command? I don't know about the details, but sometimes the name is the problem.

**Comment by jdidion** [comment]
Yes, 'py.test' works, but I thought 'pytest' was now the correct command to use.

**Comment by jdidion** [comment]
http://stackoverflow.com/questions/39495429/py-test-vs-pytest-command

**Comment by andreif** [comment]
@jdidion try testing locally with tox/detox to debug the problem

@BanzaiMan I believe the issue is not about Travis CI, but using pytest.
