### ISSUE TITLE
503 Service Temporarily Unavailable when installing Mono

### ISSUE THREAD

**Issue by asbjornu** [travis-ci/travis-ci#7401]
A lot of jobs (see [here](https://travis-ci.org/GitTools/GitTools.Core/jobs/206092488), [here](https://travis-ci.org/GitTools/GitVersion/jobs/203414871) and [here](https://travis-ci.org/GitTools/GitVersion/jobs/205259047)) have been failing lately with the following error message:

```shell
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-jay_4.8.0.495-0xamarin1_amd64.deb  503  Service Temporarily Unavailable [IP: 52.85.142.90 80]
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-csharp-shell_4.8.0.495-0xamarin1_all.deb  503  Service Temporarily Unavailable [IP: 52.85.142.90 80]
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/monodoc-base_4.8.0.495-0xamarin1_all.deb  503  Service Temporarily Unavailable [IP: 52.85.142.90 80]
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono-tools/monodoc-browser_4.2-0xamarin1_all.deb  503  Service Temporarily Unavailable [IP: 52.85.142.90 80]
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/monodoc-manual_4.8.0.495-0xamarin1_all.deb  503  Service Temporarily Unavailable [IP: 52.85.142.90 80]
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-complete_4.8.0.495-0xamarin1_amd64.deb  503  Service Temporarily Unavailable [IP: 52.85.142.90 80]
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono-basic/mono-vbnc_4.0.1-0xamarin1_all.deb  503  Service Temporarily Unavailable [IP: 52.85.142.90 80]
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/n/nuget/nuget_2.12+mono-0xamarin1_all.deb  503  Service Temporarily Unavailable [IP: 52.85.142.90 80]
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/r/referenceassemblies-pcl/referenceassemblies-pcl_2014.04.14-1_all.deb  503  Service Temporarily Unavailable [IP: 52.85.142.90 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .
Your build has been stopped.
```

Any ideas on what's causing this? Is this a problem with `download.mono-project.com` or with Travis' infrastructure? Every time it's failing, I've tried to `wget` the URLs that's failing and they download just fine. Perhaps Travis can cache the packages locally so download on every job isn't required?

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by akoeplinger** [comment]
download.mono-project.com sits behind Amazon CloudFront so the issues are at their end (possibly related to the other issues they had with S3).

**Comment by leezer3** [comment]
I'm seeing these intermittently as well, although not just for Mono, all kinds of packages.

This thread on Launchpad seems to suggest that it can be caused by triggering a request just as the remote server updates:
https://bugs.launchpad.net/ubuntu/+source/autopkgtest/+bug/1319416

Restarting the build always seems works OK-
Would waiting for 10s and retrying once on this error work at all?

If nothing else, I'd say that approach would mean that you're probably wasting less VM time in the long run.

**Comment by grokys** [comment]
I am also getting this reasonably often, but intermittently.

**Comment by ferittuncer** [comment]
I am having the same issue too.

**Comment by efekthalo** [comment]
always need to rerun continuous-integration/travis-ci/pr check because of this issue, sometimes works on 1st try, sometimes only on 4th

**Comment by thasmo** [comment]
Experiencing the same.

**Comment by akoeplinger** [comment]
@asbjornu this should've been fixed long ago, can you please confirm and close the issue?

**Comment by asbjornu** [comment]
I haven't experienced this in a while, so I'll close it.
