### ISSUE TITLE
Blank home page with Safari and Chrome on macOS.

### ISSUE THREAD

**Issue by macmade** [travis-ci/travis-ci#7402]
Since some time, I'm unable to load the `travis-ci.org` site with Safari or Chrome on macOS.  
I get a blank page.

I've seen a few issues like this, but they were apparently fixed a long time ago...

Details:

  - macOS 10.12.3 Beta (16D25a)
  - Safari 10.0.3 (12602.4.8)
  - Chrome 56.0.2924.87 (64-bit)

Latest Firefox build on the same machine has no issues loading the page.  
I don't think this is a login issue, as I never logged-in from Chrome before...

The blank page actually contains the following HTML, which is not displayed:

```
<h1>Hey there!</h1>
<p>Looks like you have JavaScript disabled.</p>
<p>The Travis CI webclient needs JavaScript to work properly.</p>
<h2>Please enable JavaScript to get the best Travis CI experience.</h2>
<h3>Thank you!</h3>
```

But obviously, JavaScript is enabled on both browsers...

The error console on Safari displays the following errors:

```
[Error] Unrecognized Content-Security-Policy directive 'block-all-mixed-content'.
[Error] The Content Security Policy directive 'frame-ancestors' is ignored when delivered in a report-only policy.
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (vendor-dabdb732daad447b5ca1f9215b29433e.css, line 0)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (travis-fe23677a48d19632b01515d382464699.css, line 0)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (vendor-78f747008658772e531138ea919e40b6.js, line 0)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (travis-bfaa1988d14e4c78f057a13547061fd5.js, line 0)
```

Please tell me if you need additional details.
I'll be happy to help, as this is a rather annoying issue...

**Comment by BanzaiMan** [comment]
Is this still a problem for you? What is the user name are you using?

**Comment by macmade** [comment]
Thanks for the reply.

Yes, this is still an issue for me.  
My username is `macmade`

**Comment by macmade** [comment]
Any news on this issue? Anything I can do to help?

**Comment by macmade** [comment]
I can't since I don't have anything displayed on the homepage...

But I did clear all my cookies and website data, still the same issue...

**Comment by suslovsergey** [comment]
+1 not auth.

**Comment by macmade** [comment]
Looks like the issue is fixed... : )
Thanks!
