### ISSUE TITLE
Build hangs, no obvious way to cancel

### ISSUE THREAD

**Issue by dotsdl** [travis-ci/travis-ci#7403]
I restarted an [errored build on Travis for ``alchemlyb``](https://travis-ci.org/alchemistry/alchemlyb/builds/206313839), but this build seems to be stuck in a state that won't let me cancel it. Usually a cancel button renders on the top right, but it looks like the build didn't even get that far before hanging.

Is there something I can do to fix this, or is this something that can only be fixed from your end?

**Comment by mkviatkovskii** [comment]
I have the same issue [`here`](https://travis-ci.org/epam/Indigo/builds/206610901). There is no cancel button, so I cannot stop the build.
![screen shot 2017-03-01 at 5 18 33 pm](https://cloud.githubusercontent.com/assets/4228185/23463622/4be7462e-fea3-11e6-81ef-802be82faf27.png)

**Comment by BanzaiMan** [comment]
We had logs database connexion issues which might explain this strange state. The jobs were running, but the logs weren't showing up, and we did not show the cancel button.

The builds indicated have all finished now. Is it OK to close this?

**Comment by dotsdl** [comment]
Yeah looks good now. Thanks @BanzaiMan!
