### ISSUE TITLE
travis build logs "There was an error while trying to fetch the log." in current build

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#7404]
Builds after the restoration of service on today outage "Issues related to the S3 outage in AWS" are returning "There was an error while trying to fetch the log." attempting to fetch the build log

https://travis-ci.org/grooverdan/mariadb-server/jobs/206470872

Even in progress restarted jobs like https://travis-ci.org/grooverdan/mariadb-server/jobs/206470871 are returning the same error.

**Comment by eclipxe13** [comment]
Same in other project. Currently Travis CI Status say "All Systems Operational"

- https://travis-ci.org/eclipxe13/XmlSchemaValidator/jobs/206478376

**Comment by maxbeutel** [comment]
I think I ran into the same issue when creating a new project on https://travis-ci.org/kodecheck/stree-parser, the build just dies after a while and the message "There was an error while trying to fetch the log." is displayed.

**Comment by BanzaiMan** [comment]
There might have been a connexion issue with the logs database. The issue should be resolved at this time. Please try reloading the page.

**Comment by eclipxe13** [comment]
@BanzaiMan you are right, I can see the logs now. Thanks!

**Comment by grooverdan** [comment]
ack. Works for me. Thanks @BanzaiMan

**Comment by goanpeca** [comment]
Seems to still be an issue

**Comment by shalomsam** [comment]
facing the same issue now

**Comment by okgolove-rf** [comment]
Still doesn't work,

**Comment by okgolove** [comment]
Still doesn't work.

**Comment by kasvith** [comment]
Still not fixed

**Comment by christophercolumbusdog** [comment]
Still an issue... When is the timeframe for getting this resolved? This has a big impact on our workflow.

**Comment by rdev** [comment]
Same here, started happening all of a sudden. Also build that used to take ~2 min now takes forever and had to be manually cancelled.

**Comment by jordan-heemskerk** [comment]
Also experiencing this issue right now

**Comment by ospaarmann** [comment]
Same here

- https://travis-ci.org/ospaarmann/exdgraph/jobs/350666337

**Comment by jaydenseric** [comment]
Logs seem to be back up now.

**Comment by anandwana001** [comment]
Same error with me too - https://travis-ci.org/anandwana001/Tech-Jalsa/jobs/351599224

**Comment by iBug** [comment]
Same issue [here](https://travis-ci.org/taoky/OJSandbox/jobs/351599402), I need the Travis log for other purposes.

**Comment by obozaxy** [comment]
This needs to be fixed, because now i can't fix errors if i do not know what they are. I have deadlines for my programming projects.

**Comment by arobbins** [comment]
Happening to me right now

**Comment by Nenglish7** [comment]
Same for me, I think it could be the server has too many requests and it can not keep up.

**Comment by Kristinita** [comment]
In 2018.4.7 I get this error for any repository of any user.

Thanks.

**Comment by fernando-rodriguez** [comment]
Same here

**Comment by goswami-rahul** [comment]
same error 
https://travis-ci.org/keon/algorithms/jobs/365937437

**Comment by marcindulak** [comment]
At least two more recent issues with that problem:

https://github.com/travis-ci/travis-ci/issues/7952
https://github.com/travis-ci/travis-ci/issues/9144

**Comment by thebongy** [comment]
My bad, seems to be back now. I guess this is just a temporary thing as suggested by above cases.

**Comment by lloricode** [comment]
same error

**Comment by lloricode** [comment]
@marchershey yes

**Comment by PeterDaveHello** [comment]
Same here: https://travis-ci.org/PeterDaveHello/ColorEchoForShell/jobs/369931930, restart not working ...

**Comment by geek1011** [comment]
Same here: https://travis-ci.org/just-install/just-install-updater-go/builds/371378495

It was working fine earlier today.

**Comment by geek1011** [comment]
It's fixed for me now.

**Comment by kblicharski** [comment]
Still an issue.

**Comment by benlongmire** [comment]
I had this issue today, eventually the log showed up but it was missing everything from whilst it wasn't working

**Comment by montao** [comment]
This happens to me today

**Comment by karamuka** [comment]
same issue here

**Comment by huxaiphaer** [comment]
Same

**Comment by huxaiphaer** [comment]
@karamuka , any progress ?

**Comment by kumy** [comment]
@karamuka @huxaiphaer there is an ongoing planned database maintenance https://www.traviscistatus.com/
![Screenshot from 2020-04-11 14-56-32](https://user-images.githubusercontent.com/176794/79044307-a816c780-7c04-11ea-8ef6-6bd78e44b6db.png)

**Comment by huxaiphaer** [comment]
Aaahhh, thanks for letting me know @kumy

**Comment by Sana3883** [comment]
Hi, I have the same error, do you know how long it would take?

**Comment by kumy** [comment]
@Sana3883 absolutely not, I'm not affiliated with them ;)

**Comment by Sana3883** [comment]
The problem is fixed! :)

**Comment by huxaiphaer** [comment]
Are you sure @Sana3883 ?

**Comment by Sana3883** [comment]
> Are you sure @Sana3883 ? Mine is still not working.
@huxaiphaer,  Yes, It is working.

**Comment by hasufell** [comment]
Definitely not working.

**Comment by slifty** [comment]
As @kumy noted it sounds like this is an anticipated issue, and that "There is an ongoing planned database maintenance"

Folks who also came here from google: instead of filling the thread with "not working" (and therefore making it harder to see @kumy's note) I'd suggest using reactions on a recent post to indicate that you are experiencing the error in this particular incident.

I imagine it's clear at this point to the powers that be that folks are experiencing the problem, and in fact it is an anticipated problem that is reflected in the `Under Maintenance` statuses over at https://www.traviscistatus.com/

**Comment by hasufell** [comment]
@slifty we're aware of the database migration. However, it is not clear whether the log problem is something that they are aware of or not, since there was no official response.

**Comment by Rishgod** [comment]
D: not working for me too 
![image](https://user-images.githubusercontent.com/54576074/79050388-4f1c5300-7c47-11ea-9f8b-2cf778af30e4.png)

**Comment by Andrew-Kaplan** [comment]
same here error message: "There was an error while trying to fetch the log."

**Comment by Andrew-Kaplan** [comment]
Builds are going through successfully now for me. Thank you all!

**Comment by huxaiphaer** [comment]
Man, maybe it's sequential let me wait.  @Andrew-Kaplan

**Comment by javeme** [comment]
Most of the time there are still errors for me, and the response is slow. I am not sure whether it's network problem.
![image](https://user-images.githubusercontent.com/9625821/79628814-0a2c7b00-8177-11ea-94cf-937ad83b3333.png)
https://travis-ci.org/github/hugegraph/hugegraph/jobs/676369017

**Comment by DrPhenomenon** [comment]
i am also having the  same error
