### ISSUE TITLE
Is travis-ci.org having troubles right now?

### ISSUE THREAD

**Issue by andreif** [travis-ci/travis-ci#7405]
Hi, I am trying to figure out what is happening with travis-ci.org. It builds and run jobs but it's not possible to get logs, and sometimes job info for 3 hours already, despite status page showing all ✅ . Also, if jobs appear, they often have:
<img src="http://i.imgur.com/ZXj1nEU.png" width=300>

Is it still a fallout from S3? If yes, could you mention it on the status page?

**Comment by andreif** [comment]
Finally updated https://www.traviscistatus.com/incidents/hx7cnxbch9xf

**Comment by andreif** [comment]
It was working fine after the incident was acknowledged, and now same issues happen again.

**Comment by BanzaiMan** [comment]
The general issue with the logs should be addressed. Do let us know if you continue to see the problem.
