### ISSUE TITLE
scala 2.12.1 build also trying to publish 2.11.8

### ISSUE THREAD

**Issue by chandu0101** [travis-ci/travis-ci#7406]
2.11.8 job (success) : https://travis-ci.org/scalajs-react-universe/macros/jobs/206593206
2.12.1 Job (failed) : https://travis-ci.org/scalajs-react-universe/macros/jobs/206593205

**Comment by BanzaiMan** [comment]
Looks like you are calling `sbt` without the argument. https://github.com/scalajs-react-universe/macros/blob/6584ecd06348a5bca62890746c5066a5e952662f/.travis.yml#L25

I believe you need to specify a version here, very much like we do with the default `script`: https://docs.travis-ci.com/user/languages/scala#Default-Test-Command

**Comment by chandu0101** [comment]
@BanzaiMan  thank you very much :)
