### ISSUE TITLE
travis build log still not accessible after s3 outage

### ISSUE THREAD

**Issue by juju4** [travis-ci/travis-ci#7408]
Hello

following yesterday's incident https://www.traviscistatus.com/incidents/hmwq9yy5dh9d, I still can't access to build log, even the ones I rebuild today.

for example
https://travis-ci.org/juju4/ansible-forensicator-fate/jobs/206251143
https://api.travis-ci.org/jobs/206251143/log.txt?deansi=true
```
{"error":"Travis encountered an error, sorry :("}
```

https://travis-ci.org/juju4/ansible-forensicator-fate/jobs/206251142
```
There was an error while loading data. 
```

https://travis-ci.org/juju4/ansible-harden-apache
```
There was an error while trying to fetch the log.
```

Current https://www.traviscistatus.com/ is only about API outage.

Thanks

**Comment by BanzaiMan** [comment]
The web app fetches the logs via API.

**Comment by juju4** [comment]
Thanks for the clarification

**Comment by BanzaiMan** [comment]
This issues should be resolved now. Please let us know if you continue to see it.
