### ISSUE TITLE
Links in broadcast tooltip unreadable with pride navbar

### ISSUE THREAD

**Issue by duncanmmacleod** [travis-ci/travis-ci#7409]
When using the `.pride` navbar, links inside `.broadcast` tooltips are shown with white text on a white background, making them unreadable:

![travis-ci-ui-bug](https://cloud.githubusercontent.com/assets/1618530/23479343/c58417b0-fe89-11e6-928c-80207c799838.png)

**Comment by BanzaiMan** [comment]
We pushed a fix for this. Thanks!
