### ISSUE TITLE
Environment variables from repository settings not set

### ISSUE THREAD

**Issue by subotic** [travis-ci/travis-ci#7412]
Hi

Is there any particular reason, that I'm missing, why in one build the environment variables from repository settings are set while in the other they are not:

variables set: https://travis-ci.org/dhlab-basel/Sipi/jobs/204953911#L238-L245
variables not set: https://travis-ci.org/dhlab-basel/Sipi/jobs/205964272#L238-L239

Both have the same ``.travis.yml``. The only apparent difference is that the build that works is a pull request stemming from a branch inside the same repository, and the not working build is a pull request stemming from a branch from a fork.

Any tips are highly appreciated.

**Comment by BanzaiMan** [comment]
We do not decrypt these in PR builds for security reasons. This is documented in https://docs.travis-ci.com/user/encrypting-files

> Please note that encrypted files are not available for pull requests from forks.

**Comment by subotic** [comment]
Thanks, and sorry for the trouble.
