### ISSUE TITLE
Updating PR on github

### ISSUE THREAD

**Issue by waghanza** [travis-ci/travis-ci#7413]
Hello,

I have made a [PR](https://github.com/mperham/sidekiq.cr/pull/39) on an OSS project.

My [PR](https://github.com/mperham/sidekiq.cr/pull/39) was **initially** failing. Since conversation with the community, I have pushed fixes on my branch, so github updated my [PR](https://github.com/mperham/sidekiq.cr/pull/39).

However I can still see on travis that my [PR](https://github.com/mperham/sidekiq.cr/pull/39) was failing https://travis-ci.org/mperham/sidekiq.cr/builds/206977410 but my branch is not failing
https://travis-ci.org/waghanza/sidekiq.cr

Regards,

**Comment by BanzaiMan** [comment]
This is strange. The pseudo commit associated with https://travis-ci.org/mperham/sidekiq.cr/builds/206977410 is https://github.com/mperham/sidekiq.cr/commit/9711f0af5ada35fdad9b937f1cc6a22680c30583, which is the same as the previous failing build https://travis-ci.org/mperham/sidekiq.cr/builds/202546845.

Could you try closing and reopening the PR?

**Comment by waghanza** [comment]
@BanzaiMan still using the previous commit

**Comment by BanzaiMan** [comment]
Thanks for testing. I remember seeing a similar issue, but can't find it now.

How about pushing a new commit?

**Comment by waghanza** [comment]
@BanzaiMan I have delete README. referenced commit **SHOULD** be `117ba45`

**Comment by BanzaiMan** [comment]
No, it should not. The PR builds such as https://travis-ci.org/mperham/sidekiq.cr/builds/207044467 runs a pseudo commit (here, https://github.com/mperham/sidekiq.cr/commit/0d744039abf1caa65292d9ca82e3bc74a3a50ac4), which is the merge commit of https://github.com/mperham/sidekiq.cr/commit/117ba459e158c52c32fd1c4f3952b8a7fdd6cc74 and the target https://github.com/mperham/sidekiq.cr/commit/f579dc857c748780324cb9c3846159a6a1e62135.

**Comment by BanzaiMan** [comment]
At any rate, a new commit seems to have resolved the issue.

**Comment by waghanza** [comment]
ok, thanks for clarification
