### ISSUE TITLE
Add GIT_PREVIOUS_SUCCESSFUL_COMMIT

### ISSUE THREAD

**Issue by RafaelPlantard** [travis-ci/travis-ci#7414]
Something based at [this](https://issues.jenkins-ci.org/browse/JENKINS-27570).

Added as a default ENV var.

**Comment by BanzaiMan** [comment]
I am not sure how Jenkins is doing this, but I am a bit skeptical how reliable such a value might be.

If the repository is active, there can be multiple builds running concurrently. A new incoming build may look at the last completed build when the build starts, but by the time this build finishes other builds which were running could have finished (and have passed), thus giving the user the impression that the "last successful commit" is pointing to a wrong commit, after some time has passed.

**Comment by RafaelPlantard** [comment]
I got your point. So, this feature is not possible?

**Comment by BanzaiMan** [comment]
I wouldn't say it's not possible, but unreliable and confusing at best, and misleading at worst. Why do you want it?

**Comment by BanzaiMan** [comment]
I'm closing this for now.
