### ISSUE TITLE
PRs link to "https://github.com/[object Object]/..." instead of repo name

### ISSUE THREAD

**Issue by hugovk** [travis-ci/travis-ci#7415]
**Step to reproduce:**
1. Go to a build history page, eg. https://travis-ci.org/python-pillow/Pillow/builds
2. Click the PR number in a commit message, eg. `Merge pull request #2434 from ...`

**Expected result:**
Link is `https://github.com/python-pillow/Pillow/issues/2434`

**Actual result:**
Link is `https://github.com/[object%20Object]/Pillow/issues/2434`

Happens with every repo I've looked at.

Same thing happens on individual build pages, eg. `Merge pull request #2434 from ...` on https://travis-ci.org/python-pillow/Pillow/builds/206880440

**Comment by kevmoo** [comment]
Any updates here? @lislis ?

**Comment by clekstro** [comment]
Hi @kevmoo! This should be working again as expected now that https://github.com/travis-ci/travis-web/pull/1051 is live.
