### ISSUE TITLE
Set TERM=dumb for Gradle projects using Kotlin build scripts

### ISSUE THREAD

**Issue by Minecrell** [travis-ci/travis-ci#7419]
Without setting the `TERM` environment variable to `dumb` before running a Gradle build, Gradle will spam the build log with its status reports. ([Example](https://travis-ci.org/minecraft-dev/MinecraftDev/builds/206662275#L116)). For regular Gradle parts, this was fixed together with https://github.com/travis-ci/travis-ci/issues/2275.

However, [the current code will only check if a `build.gradle` file is present](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/shared/jdk.rb#L17-L19). When using a Kotlin build script, the file is called `build.gradle.kts` (and consequently, the environment variable is not set, [causing massive spam in the log](https://travis-ci.org/minecraft-dev/MinecraftDev/builds/206662275#L116).) Since Kotlin build scripts require adding a `settings.gradle`, the code just needs to be extended to check for that file additionally to `build.gradle`.

**Comment by BanzaiMan** [comment]
Are there any other tool that diverges from the current behavior?

**Comment by Minecrell** [comment]
@BanzaiMan 
I'm not sure I understand your question. Currently, the current check fails when using Kotlin Gradle build scripts but if `settings.gradle` is added to the check it should cover all alternative build script filenames.

**Comment by BanzaiMan** [comment]
We can change the current behavior to check for `build.gradle.kts`, but if there are other tools besides Kotlin that rely on `TERM` being set, then we would like to unify the logic now.

**Comment by Minecrell** [comment]
@BanzaiMan I understand. I'm not aware of any other tool that requires `TERM` being set to `dumb`.
