### ISSUE TITLE
node_js config dropped from Python config

### ISSUE THREAD

**Issue by samuelli** [travis-ci/travis-ci#7421]
Recently, it looks like the config drops the node_js option, which means node no longer works in the Python environment, even though it is pre-installed on every environment.

Config:
https://travis-ci.org/webcomponents/webcomponents.org/jobs/205955365/config
Actual config with `node_js`:
https://github.com/webcomponents/webcomponents.org/blob/master/.travis.yml#L2

**Comment by BanzaiMan** [comment]
If you set `language` to anything other than `node_js`, the `node_js` is dropped. I don't think this behavior changed, ever.

**Comment by samuelli** [comment]
Hmm, I guess you're right. Was there another change, maybe the default node version?

Suddenly, `yarn` step has started failing for us with this message:
```
error typescript@2.2.1: The engine "node" is incompatible with this module. Expected version ">=4.2.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
