### ISSUE TITLE
CouchDB doesn't start on Linux and OSX

### ISSUE THREAD

**Issue by AndreaGi** [travis-ci/travis-ci#7423]
Looks like CouchDB is not starting on both Linux and OSX. The machine says: 
`couchdb start/running, process 1177`

But it fails when the status is requested: 
`$ couchdb -s
Apache CouchDB is not running.`

Build example: https://travis-ci.org/pouchdb/upsert/jobs/207654791

**Comment by nolanlawson** [comment]
False alarm; it appears that we just forgot to enable CORS: https://github.com/pouchdb/upsert/issues/34#issuecomment-284179387

As for why `couchdb` isn't globally available, I'm not sure if `services: couchdb` actually adds a global `couchdb` utility?

**Comment by AndreaGi** [comment]
@nolanlawson good catch.
