### ISSUE TITLE
Ubuntu Precise support will end in under two months

### ISSUE THREAD

**Issue by eliaskosunen** [travis-ci/travis-ci#7424]
The support for Ubuntu 12.04 LTS will end on April 26th. Trusty (14.04) support is *still* in beta for some reason, and Xenial (16.04) support is nowhere to be seen.

**Comment by edmorley** [comment]
Ubuntu 14.04 (Trusty) still being in beta is #5695, and Ubuntu 16.04 (Xenial) is #5821.

**Comment by photodude** [comment]
Trusty is currently worthless for projects that need mysql, due to issue #6842

**Comment by cclauss** [comment]
https://wiki.ubuntu.com/Releases

**Comment by Lyoness** [comment]
Build Infrastructure team has been actively working on this, thus we don't anticipate any disruption to builds using precise. 

We'll publish a blog post soon detailing how we've been planning/preparing for this EOL event and what's on the horizon.  For now, precise will remain the default environment for a short while longer.

**Comment by edmorley** [comment]
In case people hadn't seen the blog, there's been a recent announcement about this:
https://blog.travis-ci.com/2017-04-17-precise-EOL
