### ISSUE TITLE
Could not download apache artifact

### ISSUE THREAD

**Issue by pedja4** [travis-ci/travis-ci#7426]
I keep having this issue when building a project:

    [ERROR] Failed to execute goal on project hbase: Could not resolve dependencies for project com.baeldung:hbase:jar:1.0.0-SNAPSHOT: 
    Could not find artifact org.apache.hbase:hbase:jar:1.3.0 in central     (http://repo.maven.apache.org/maven2) -> [Help 1]

But the artifact is in the repository, not sure what is wrong. Any help? [Link to the build](https://travis-ci.org/eugenp/tutorials/builds/207928078)

**Comment by BanzaiMan** [comment]
Recent builds appear to resolve the dependencies correctly.

**Comment by pedja4** [comment]
Yes, the problem no longer occurs for some time now. Thanks.
