### ISSUE TITLE
non-global secure variables in matrix

### ISSUE THREAD

**Issue by alexgyori** [travis-ci/travis-ci#7429]
I am looking to create a matrix in which only one row in the matrix has access to the secure variables.
I tried to create a minimal configuration like this:
https://github.com/alexgyori/testing-secures/blob/c43805a536a8cf1809cbe38579e22ab2826ac16a/.travis.yml

Unfortunately, this doesn't initialize the secure variable, as shown by the build results at:
https://travis-ci.org/alexgyori/testing-secures/jobs/207971005/config

Is there a way to have secure variables initialized only in one of the jobs of the matrix but not the other(s)?
I am aware I could put the secure variables in the global environment but that's not what I am looking to do; rather, I'm looking to make the secure variable be available only in the row I specify. Is that possible?

Thanks!
Alex

**Comment by BanzaiMan** [comment]
`secure` needs to be a key for a YAML map; this is discussed in https://docs.travis-ci.com/user/encryption-keys#Detailed-Discussion. Then, you can see why https://github.com/alexgyori/testing-secures/blob/c43805a536a8cf1809cbe38579e22ab2826ac16a/.travis.yml#L7 does not do the job; it is a string:

```
MYVAR="TWO"  secure:rxo5zvK6lul/hEDGqwRMlz4BCRJIRofuZch3U6UQHMOBRUS+5mJ828YDQdEPS/cCLgXNBOi+jtSr9gtv2L407LrPqgrH4zBt3My5D9dRNJBtxWOvXMpPHqyX7CFTIq+mJFnrYE/UY5GGjOLGiYnBAJsak5YUWUURmX0FPH7X5j12ZZNp9OLK4sScRZZoaXKNv8KeInALXH7jQYDn3ZaMDmDizfic/1TN+B+YciB3JXns9uvB+as94+nSgfWqbc0rn5qYQqUELGR2MwFZCDUGuV7r6TgzAn2+foEgXZj4JgbeNWH1U+ZY5lHeU+auzs/ANYNEJ5Xp7dp5CpkO5DIplA66VY75TwDuV1laF3nFZrdz/iJOlzkaYCsxvVvAgofcvXjsw+12jCiQzlD5/oKCD27g+rXzMw4HOQcwNDdzZfECWsiSKrE13Y5kYhcloC8pW4gSv2mv19aT3fXTXlkaZSjobYnnOjpJvTbsS/A5hyXFHN/6gLb71QQWU+ZErSlL0xkK6DyTtxum8CGfKCJSnCWZVGx7OOtym0RhLigLCEV7Fe9ej+uZ59dT00gWtjniVWPGEfOgSsDZUhBHZhy312WUhQWV6Lj2Qifk4WOOCBO3nAFsz62vW/TOzS4xLZ2GhQ7KAwnu9LW8XoHU+nt/ape+rtGkhYTDVo2CwMEDefY=
```
and not a map.

You _can_ set the secure environment variable within a build matrix if the *entire* variable is a secret. For example:

```yaml
env:
  - DIST=precise STACK=EC2
  - secure: "gbpCUfPdT7kye6mnRs52JYnCwb3pAxbpZsXwex3ecEQmE2tY0Uk04dxrzfu8hsfuAnvErbkV5nHxu9PfYA1Q+l+GB2x+wysDB/Cxz/Ih5XP+uTZEpEv39yog+rA/ebYLGeApRhwIro935MjDFR9itkCTG98wXKgOn6J6NaY/+U0="
```

This secure env var can contain multiple secrets (`FOO=bar BAR=baz`); https://travis-ci.org/BanzaiMan/travis_production_test/jobs/207985621#L113-L114.

But you cannot mix a plain one and a secret one in one row of a build matrix.

**Comment by alexgyori** [comment]
Thanks for the prompt answer. I have a quick follow up: Can I have two secure variables in the same row of the build matrix? I understand I can merge the two secure variables into a single one my encrypting the several secrets they encryp; I'm asking in the case that I have two secure variables, can I list both of them in the same row?

As a side note, the description at: https://docs.travis-ci.com/user/environment-variables/#Defining-public-variables-in-.travis.yml  is a bit misleading because it leads one to believe that all of DB, SH, and PACKAGE_VERSION would be in the same environment, when the listing there actually creates a matrix in which each environment contains one of them.

Thanks!
Alex

**Comment by BanzaiMan** [comment]
> Can I have two secure variables in the same row of the build matrix?

That's what I showed in the previous comment:

> This secure env var can contain multiple secrets (`FOO=bar BAR=baz`); https://travis-ci.org/BanzaiMan/travis_production_test/jobs/207985621#L113-L114. In the logs, you see the two secrets (`FOO` and `BAR`) exported.

> As a side note…

Improvement suggestions are welcome at https://github.com/travis-ci/docs-travis-ci-com! Thank you!

**Comment by BanzaiMan** [comment]
I'm closing this, as there is no more to do on the technical side. (Documentation should go to the docs repo.)
