### ISSUE TITLE
Unable to use `travis_wait` with a complex command

### ISSUE THREAD

**Issue by dpsanders** [travis-ci/travis-ci#7431]
I'm trying to use `travis_wait` with a complex command, but it's not working:

https://travis-ci.org/dpsanders/ValidatedNumerics.jl/jobs/208041505

The only error (?) message is 
```
/home/travis/build.sh: line 162:  3283 Terminated              travis_jigger $! $timeout $cmd
```

**Comment by BanzaiMan** [comment]
I suspect this is a duplicate of https://github.com/travis-ci/travis-ci/issues/5281. I am guessing that the command you're running is actually `fork`ing and `exec`ing and `travis_wait` doesn't handle it well.

**Comment by dpsanders** [comment]
OK, thanks. We seem to have found an alternative solution.
