### ISSUE TITLE
tcltk (R 3.3.2)

### ISSUE THREAD

**Issue by jchrom** [travis-ci/travis-ci#7432]
Output from travis build

    Error : .onLoad failed in loadNamespace() for 'tcltk', details:
      call: dyn.load(file, DLLpath = DLLpath, ...)
      error: unable to load shared object '/home/travis/R-bin/lib/R/library/tcltk/libs/tcltk.so':
      libtcl8.5.so.0: cannot open shared object file: No such file or directory
    Error : package ‘tcltk’ could not be loaded
    ERROR: lazy loading failed for package ‘aplpack’
    * removing ‘/home/travis/R/Library/aplpack’

@craigcitro and @jimhester

**Comment by BanzaiMan** [comment]
> R for Travis-CI is not officially supported, but is community maintained. Please file any issues at https://github.com/travis-ci/travis-ci/issues and mention @craigcitro and @jimhester in the issue

**Comment by BanzaiMan** [comment]
Looks like a missing shared object file, which suggests either a missing package on the Ubuntu image, or a packaging error on R's `tcltk` package.

**Comment by jimhester** [comment]
I believe you just need to add the tcl-8.5 and tk-8.5 packages, see an [example](
https://github.com/kosukeimai/MatchIt/blob/649a59e2e65722e97ab9acf1355e32a55ab8c836/.travis.yml#L4-L8).

**Comment by jchrom** [comment]
Yep, solved. Thanks!
