### ISSUE TITLE
OSX svn: E000060: Can't read from connection: Operation timed out

### ISSUE THREAD

**Issue by burlen** [travis-ci/travis-ci#7435]
Hi Folks,

In our Apple Travis build I get the above error half way through the checkout of our test data repo. Works fine in our Linux travis build and on every other system I've tested. Can you please advise what is wrong with the Apple VM? 

Thanks
Burlen

**Comment by burlen** [comment]
https://travis-ci.com/LBL-EESA/TECA/jobs/67511189

**Comment by BanzaiMan** [comment]
What's the server are you reading data from? If you would like to discuss this in private, please close this and send email with details to support@travis-ci.com. Thanks.

**Comment by burlen** [comment]
OK, I emailed you

**Comment by burlen** [comment]
no reply to email, so I re-open it

**Comment by burlen** [comment]
command is:
`svn co svn://missmarple.lbl.gov/work3/teca/TECA_data`
get's part way through the co then dies with above error.

**Comment by burlen** [comment]
from the Apple VM console output
```
svn co svn://missmarple.lbl.gov/work3/teca/TECA_data
A    TECA_data/cam5_1_amip_run2_classify_2005_09.bin
A    TECA_data/test_table_sort.bin
A    TECA_data/landsea.nc
A    TECA_data/test_tc_detect_40.bin
A    TECA_data/tracks_1990s_3hr_mdd_4800_median_in_cat.bin
A    TECA_data/py_test_programmable_map_reduce.bin
A    TECA_data/test_tc_candidates_1990_07_01.nc
A    TECA_data/test_table_region_mask.bin
A    TECA_data/test_tc_candidates_1990_07_02.nc
A    TECA_data/cam5_1_amip_run2.cam2.h2.1991-10-01-10800.nc
A    TECA_data/cam5_1_amip_run2_tracks_2005_09.bin
A    TECA_data/cam5_1_amip_run2.cam2.h2.1991-10-02-10800.nc
A    TECA_data/test_table_reader_distribute_20.bin
A    TECA_data/tracks_1990s_3hr_mdd_4800.bin
A    TECA_data/earthmap4k.jpg
A    TECA_data/earthmap4k.png
A    TECA_data/cam5_1_amip_run2_stats_2005_09.bin
A    TECA_data/prw_hus_day_MRI-CGCM3_historical_r1i1p1_19500101-19501231.nc
A    TECA_data/cam5_1_amip_run2_candidates_2005_09.bin
A    TECA_data/cam5_1_amip_run2_1990s
A    TECA_data/cam5_1_amip_run2_1990s/cam5_1_amip_run2.cam2.h2.1992-07-23-10800.nc
svn: E000060: Can't read from connection: Operation timed out
```

**Comment by cotsog** [comment]
@burlen: sorry for the delay.

Can you tell us if you are installing the svn client yourself on our OS X VM? Also, can you tell us which version you are using?
​
Also, can you try adding `travis_retry` in front of your `svn` command? e.g.
​
`travis_retry svn co svn://missmarple.lbl.gov/work3/teca/TECA_data`
​
This will effectively retry your `svn` command up to 3 times upon a non-zero exit code. This could help mitigate the failure you are seeing if the behavior is random.
​
Note that it must be called directly in the .travis.yml file because the `travis_retry` function isn't available in your script.

**Comment by burlen** [comment]
svn is installed via homebrew. the behavior doesn't seem to be random. I'll see if I can get you answers to the other questions.

**Comment by burlen** [comment]
After some poking around, I found that subversion on Apple is very very slow. Svn co of the repo takes more than 14 min on an Apple system vs less than 2 min on a Linux system on the same network. My conclusion is that this is not a Travis issue, but rather Apple, homebrew, or subversion.

I make the following addition to our script to print a '.' every 2 sec in the terminal while svn co runs. This seems to keep Travis happy and build finally runs again.

```bash
+# On Apple svn is very very slow. On my mac book pro
+# this command takes over 14 minutes, while on a Linux
+# system on the same network it takes less than 2 minutes.
+# travis will kill a build  if it does not get console output
+# for 10 min. The following snippet sends progress marks
+# to the console while svn runs.
+svn co svn://missmarple.lbl.gov/work3/teca/TECA_data &
+svn_pid=$!
+while [ -n "$(ps -p $svn_pid -o pid=)" ]
+do
+  echo -n "."
+  sleep 2s
+done
```
