### ISSUE TITLE
multicast does not work between two docker containers on travis

### ISSUE THREAD

**Issue by kpritam** [travis-ci/travis-ci#7436]
build link : https://travis-ci.org/tmtsoftware/csw-prod/builds/208670681

I am spawning two docker containers on travis and registering service through jmdns (java lib for Multicast DNS) from one container and expecting it to be visible from other container. But this two containers are not able to see services registered by each other.

The same docker scripts runs locally on mac machine but fails on travis.

**Comment by joepvd** [comment]
From what I have gathered, mdns is not running by default on our images. Have you tried installing and running [`avahi-daemon`](https://linux.die.net/man/8/avahi-daemon), e.g.

```yaml
install:
- sudo apt-get install -y avahi-daemon
- ...
```

**Comment by kpritam** [comment]
Closing this ticket as i was able to get my mdns tests running on travis ci with docker.
