### ISSUE TITLE
NAsm Package

### ISSUE THREAD

**Issue by amaneureka** [travis-ci/travis-ci#7439]
Seems like installed nasm package is buggy. check this

https://travis-ci.org/amaneureka/AtomOS/builds/208616144#L5275

``` ./Output/Kernel.asm:147: error: segment alignment `0x1000' is not power of two```

While this never happens on any other System (tested on Ubuntu 12.04, 14.04 and 16.10, Win 10 -- cygwin)

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by amaneureka** [comment]
It isn't C# specific problem. NAsm package is causing problem

**Comment by akoeplinger** [comment]
Correct, this is unrelated to C#.

You can try switching to trusty to get a more recent Ubuntu version which may contain a nasm package that doesn't hit this problem: https://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by amaneureka** [comment]
Thanks! It worked!
