### ISSUE TITLE
The Nix language page claims only Nix 1.11.2 is available

### ISSUE THREAD

**Issue by exarkun** [travis-ci/travis-ci#7441]
CC @domenkozar @garbas @matthewbauer

https://docs.travis-ci.com/user/languages/nix says:

    Currently, only version “1.11.2” of Nix is provided. In the future, it may be possible to configure different versions with .travis.yml.

However, builds actually get Nix 1.11.7 and it looks like they're just downloading the release that's current at the time of the build.

**Comment by matthewbauer** [comment]
Yeah we should update this. Ideally you could specify versions though.

**Comment by exarkun** [comment]
Your stale bot seems to have some problems.
