### ISSUE TITLE
Logs missing in GUI

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#7443]
Appears the logs are missing in the GUI. Tried refreshing and switched between a couple of builds. Noticed for one build matrix they showed up after all jobs finished. 😕

<img width="1552" alt="screen shot 2017-03-09 at 13 40 50" src="https://cloud.githubusercontent.com/assets/3019665/23765102/0eb9b454-04ce-11e7-94ff-d138e3cdd297.png">

ref: https://travis-ci.org/jakirkham/xnumpy/jobs/209463159

**Comment by BanzaiMan** [comment]
Could you try reloading the page? I can see it.
![job__79_1_-_jakirkham_xnumpy_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/23765877/b909ebfc-04d0-11e7-9d4a-f247f31c916f.png)

**Comment by jakirkham** [comment]
As mentioned above, they seemed to show up after all builds in the matrix completed, but not before that (even if the particular job had finished).

**Comment by jakirkham** [comment]
Not sure why I saw this before, but am not seeing it now on recent builds. Am guessing it was some spurious rare error. Closing this out.

**Comment by jakirkham** [comment]
This appears to be back. Occasionally I see little snippets of the log, but refreshing makes them go away.

<img width="1552" alt="screen shot 2017-03-14 at 11 15 32" src="https://cloud.githubusercontent.com/assets/3019665/23907474/a5fb384c-08a7-11e7-9b5c-dfa38e81dfde.png">

ref: https://travis-ci.org/conda-forge/conda-build-all-feedstock/jobs/210965360

**Comment by jakirkham** [comment]
This appears to be back. Occasionally I see little snippets of the log, but refreshing makes them go away.

<img width="1552" alt="screen shot 2017-03-14 at 11 15 32" src="https://cloud.githubusercontent.com/assets/3019665/23907474/a5fb384c-08a7-11e7-9b5c-dfa38e81dfde.png">

ref: https://travis-ci.org/conda-forge/conda-build-all-feedstock/jobs/210965360

**Comment by jakirkham** [comment]
Here is such a weird snippet. Seems to only include stuff after I open the log or refreshed it while running.

<img width="1552" alt="screen shot 2017-03-14 at 11 17 54" src="https://cloud.githubusercontent.com/assets/3019665/23907585/fa5dd9e4-08a7-11e7-9125-d2b435e82433.png">

**Comment by jakirkham** [comment]
Tried refreshing after it completed, but the log is now blank. 😕

<img width="1552" alt="screen shot 2017-03-14 at 11 19 31" src="https://cloud.githubusercontent.com/assets/3019665/23907640/2559a358-08a8-11e7-9ba1-0d74fdbcd6c6.png">

**Comment by jakirkham** [comment]
This might be a different issue, but we are seeing an error trying to retrieve the log of this build.

<img width="1552" alt="screen shot 2017-03-20 at 13 44 48" src="https://cloud.githubusercontent.com/assets/3019665/24113536/7e222486-0d73-11e7-9809-19f7ce465f7e.png">

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/213059229

**Comment by Artoria2e5** [comment]
Seeing this with https://travis-ci.org/tootsuite/mastodon/jobs/225683905 too. It worked earlier. The "raw log" download also gives a equivalent of empty logs.

**Comment by jakirkham** [comment]
Fresh one I saw today.

<img width="1552" alt="screen shot 2017-04-29 at 17 55 15" src="https://cloud.githubusercontent.com/assets/3019665/25559300/2c767504-2d05-11e7-96cd-cc65a8fc885d.png">

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/227230169

**Comment by BanzaiMan** [comment]
We've made a series of improvements to logs display. Are you still seeing this?

**Comment by BanzaiMan** [comment]
Closing this optimistically.

**Comment by jakirkham** [comment]
I think you're right. Thanks for working on this.

The only thing similar to this that I have seen is the webpage or log being slow to load, but the log does show up. So it is some other minor unrelated issue.

**Comment by jakirkham** [comment]
Yeah, seems I'm still seeing this. After a little while the log returned, but while it was running I could only see what was present since the last refresh. If I refreshed, the log went away. Reopened after it had finished and got a blank log like the one below.

<img width="1552" alt="screen shot 2017-06-12 at 00 12 40" src="https://user-images.githubusercontent.com/3019665/27019129-e6db7820-4f03-11e7-8fb0-279c6698aeaa.png">

ref: https://travis-ci.org/lucastheis/cmt/builds/241884380

**Comment by jakirkham** [comment]
Another occurrence of this issue today.

<img width="1552" alt="screen shot 2017-06-26 at 11 11 22" src="https://user-images.githubusercontent.com/3019665/27546250-496d3732-5a60-11e7-91d1-732b60914e42.png">

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/247111730

**Comment by jakirkham** [comment]
Could we please have this issue reopened?

**Comment by jakirkham** [comment]
Thanks. FWIW this is happening to the Raw log as well.

**Comment by Arthaey** [comment]
I saw this today for the first time. Triggering a new build showed the log normally. But then later it was "blank" again like in the screenshots above, despite being a successful build. Reloading the page sometimes (but not always) fixes it. Weird...

**Comment by katwre** [comment]
Hi, I also have a problem with empty log body: https://travis-ci.org/BIMSBbioinfo/genomation/jobs/287125327. This R package passed check on my laptop, so this build error on Travis website is very suspicious.

**Comment by jakirkham** [comment]
Here's a more recent one.

<img width="1552" alt="screen shot 2017-11-15 at 23 22 02" src="https://user-images.githubusercontent.com/3019665/32873765-de784018-ca5b-11e7-9534-f1f2db8b1f7b.png">

ref: https://travis-ci.org/conda-forge/pycosat-feedstock/jobs/302546263

**Comment by ArunTejCh** [comment]
Hi, I noticed the same issue while running jobs for https://travis-ci.org/ArunTejCh/python-driver-wheels/jobs/307709085 the log were blank while the job was running, but showed up at the end of the build.

**Comment by feffi** [comment]
I got the error on all my builds after switching to a build matrix. The raw log always shows „null“

**Comment by jakirkham** [comment]
Linking another recent one.

<img width="1552" alt="screen shot 2018-01-21 at 21 27 40" src="https://user-images.githubusercontent.com/3019665/35202664-f30c9194-fef1-11e7-8895-cb9ff51df69d.png">

ref: https://travis-ci.org/conda-forge/conda-forge.github.io/builds/329587357

**Comment by Undistraction** [comment]
Another for the collection:
![cap](https://user-images.githubusercontent.com/161489/36281808-ebdd7524-1296-11e8-8d7a-ee172c4ecb29.jpg)

https://travis-ci.org/Undistraction/folktale-validations/jobs/342067384

**Comment by JimmyMow** [comment]
+1 I am seeing this as well

**Comment by MisanthropicBit** [comment]
I concur. Seeing this as well.

**Comment by Undistraction** [comment]
Looks like they are having [issues](https://twitter.com/traviscistatus/status/964186247936671744) with log delivery as of 22:05 15.02.18

**Comment by MisanthropicBit** [comment]
This has been resolved for me per the updates [here](https://www.traviscistatus.com/incidents/t68jk6rj92q4).

**Comment by jakirkham** [comment]
A more recent one.

<img width="1552" alt="screen shot 2018-04-16 at 00 23 30" src="https://user-images.githubusercontent.com/3019665/38790065-82f2a7ba-410c-11e8-929c-94dff0a0df0c.png">

ref: https://travis-ci.org/conda-forge/conda-forge.github.io/builds/366986407

**Comment by MarkPThomas** [comment]
I am getting this as well, quite frequently. It is making it impossible to compare various build runs. Attempting to view the raw log file returns null.

**Comment by Setheck** [comment]
I'm seeing this issue today, log is empty, clicking on the `Raw Log` button opens a new browser tab who's contents is simply "null"

**Comment by Setheck** [comment]
Interestingly, it appears that travis passes the build, with the null log. Then starts actually running it, which is a bit alarming as I'm not sure what happens if it reports pass, then runs the build minutes (hours?) later and it fails.

**Comment by d4nyll** [comment]
Please re-open this issue as it is still happening. My repo is https://travis-ci.org/d4nyll/resolve-when/builds/430644930

Travis passes the build. Raw log simply says `null`.

**Comment by zivmaor** [comment]
Happening to me again now:
https://travis-ci.org/github/hasadna/OpenCaptcha/jobs/676587406

Happens both when builds succeed and when they fail. Raw log says "null".

**Comment by zivmaor** [comment]
Seems you can see the logs while the test is running, but after it's finished the logs are not accessible anymore.

**Comment by tweirtx** [comment]
I've been having the same issue throughout the day on various repos

**Comment by egregors** [comment]
For two days I have seen only one non-null log from ~10 builds. Looks like we should reopen this issue again 😞

**Comment by Haixiang6123** [comment]
This is very wired. It can show the logs correctly previously, but Travis is showing no logs when all the things are running or finsihed today (Blank logs and null raw logs, like you guys posted). I look into my previous builds, and it shows all the logs, then I switch back to my latest builds (Blank logs when building), and it starts to rebuild and showing all the logs. So, I am assuming this maybe a bug?

**Comment by PyvesB** [comment]
Travis is migrating away from GitHub issues. Probably best to post on the forum, for example here: https://travis-ci.community/t/build-logs-being-truncated/5672

**Comment by jackbarsotti** [comment]
Earlier today I experienced no issues, then on a random push to github the travis build started giving me this issue. The Raw Log returns "null", refreshing the page does not work, pushing from a different branch doesn't work, and restarting the build doesn't work. I also tried what @Haixiang6123 suggested by switching to previous builds (which still show their job logs for me) and switching back to the current build, but this doesn't reveal the current job log either. 

Update: about an hour later it looks like the job logs are showing for the same builds they were missing from earlier. I didn't do anything other than wait.

**Comment by ManishKumarKeshri** [comment]
![image](https://user-images.githubusercontent.com/33408616/86039788-cae09d00-b9f7-11ea-919f-0bba6c40e46b.png)
Facing the same issue. :(

**Comment by adiabuk** [comment]
Still happening 17/04/22

**Comment by dregad** [comment]
I'm seeing null logs as well, both on successful and failed builds, e.g.
- https://app.travis-ci.com/github/mantisbt/mantisbt/jobs/567311276
- https://app.travis-ci.com/github/mantisbt/mantisbt/jobs/567310945
- https://app.travis-ci.com/github/mantisbt/mantisbt/jobs/567310949
