### ISSUE TITLE
Mono fails to install on OS-X

### ISSUE THREAD

**Issue by leezer3** [travis-ci/travis-ci#7444]
I'm aware of the occasional failed build for no apparent reason, but this is well OTT, and would seem to me to be related to the recent network maintenence,

Mono downloads OK and triggers the installer, but I'm then seeing the build stall for 10 mins followed by termination.

Some failed builds:
https://travis-ci.org/leezer3/OpenBVE/jobs/209537455
https://travis-ci.org/leezer3/OpenBVE/jobs/209537468
https://travis-ci.org/leezer3/OpenBVE/jobs/208956906
https://travis-ci.org/leezer3/OpenBVE/jobs/208956918
This OS-X build was from the same matrix as the one above, and worked OK if a little slow, don't know if it tells you anything:
https://travis-ci.org/leezer3/OpenBVE/jobs/208956931

@joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
Yes, I just noticed the same. Travis aborts the build if no output is received after 10mins. Mono install took ~4mins in most of the builds I checked (which seems awfully slow in itself, it takes ~20 seconds on my local Mac).
