### ISSUE TITLE
Sauce Connect fails the build

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#7445]
For our haxe repo, we set `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` as secure env vars, in [.travis.yml](https://github.com/HaxeFoundation/haxe/blob/development/.travis.yml#L7-L9). Since secure env vars are not available in forks, Sauce Connect will [fail to start](https://travis-ci.org/Simn/haxe/jobs/208099204#L2192) there. And since [recently](https://github.com/travis-ci/travis-ci/issues/7193), Sauce Connect errors will fail the build as well.

Can Travis somehow detect the present of `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY`, and only start Sauce Connect if they are set, and only fail the build if the connection fails?

If it is a good solution, I can look into creating a PR.

**Comment by ylavoie** [comment]
I second that!

**Comment by ehuelsmann** [comment]
Here too!

**Comment by iriberri** [comment]
This sounds like a neat solution, @andyli! If you'd like to go ahead and submit a PR that'd be awesome :) ✨
