### ISSUE TITLE
Cannot reference hidden and encrypted environment variables

### ISSUE THREAD

**Issue by zaro0508** [travis-ci/travis-ci#7446]
Hello.  I'm just trying to work with a Github API-TOKEN to pull in some code from private repos however it seems like hidden variables are not available in the build shell.  I followed the instructions from doc: https://docs.travis-ci.com/user/private-dependencies/#API-Token  however I can't seem to make it work.  I am wondering if there's something I've done wrong or if this is a real issue?

The repo is: https://github.com/Sage-Bionetworks/Lilly

Here is my test:
----------------
Setup 2 ENV variables on the Travis UI:
  travis env set NON_SECRET_FROM_UI  not_a_secret -r Sage-Bionetworks/Lilly --public
  travis env set SECRET_FROM_UI  my_secret -r Sage-Bionetworks/Lilly --private

Setup an encrypted ENV VAR in .travis.yml file:
  travis encrypt SECRET_FROM_YML=yml_secret -r Sage-Bionetworks/Lilly --add

the .travis.yml file:
------------------
language: objective-c
osx_image: xcode8.2
before_install:
- echo -e "machine github.com\n  login $NON_SECRET_FROM_UI" >> ~/.test1
- cat ~/.test1
- echo -e "machine github.com\n  login $SECRET_FROM_UI" >> ~/.test2
- cat ~/.test2
- echo -e "machine github.com\n  login $SECRET_FROM_YML" >> ~/.test3
- cat ~/.test3
env:
  global:
    secure: EiIXUXZUQKuOw+k30LSdoCG+8mbAO8aTpWdKPdDhEfQaN+NBxWMWyP8ICQb8xaK+Qsc5RXlS2Q8j7Xjh5o6h56zq/xmTrijo84Lq6uPnkNKWI5dv92NrqwH3wN3Kfqk8A98dZV11+TurNe5A/+ljvLbIjBZ9rkMsm/sRDtYQfDMJkaakDBt7wN374fhuCFJE7qviCgLbXf27Ih1w14M9Y7QLF3mPLBk+2N4qgfxbzgiFjbPnmMii3p12E8FL+3wYpMVq2IfRwcgWrBrGRx5sIygq0dhxiCZYi4c1X/EfsZW606Yju54PMMHXoc0rR0I+xpq7IXzpK3BETuvaSZR5B0Fx5xAs5jRKdLT+RLmQ30Vp+vCaullAN+vxLgbS4K1Vf1s+5B+LE/PWdzaN8o8FUwDlDXYnhnFySphdsEeMDHI2EulClVRoYtoV7dMAJmlRM64izRBYNPX9zpc2rnZsOVusEij1NQwg09+jlPH7EgyFybBbWg3kBJNv+buq71+N4F5Bc0TY1wu5iG44ZqKEW5vzUI6u07XcxLYMxun+8z5EvUr1+QVPqVUDbe3hcAG3ndPI/jnqfgnNk5LOyiUrtHTXj9FqRjVCWo3DErMgOkKvPdfKJyomrgvRaW09bmMCeKRrHeHTg2x2t5z5kUcPQw+KM/E7XHz7VDq52Tt6xBQ=

the log:
--------
![image](https://cloud.githubusercontent.com/assets/3697686/23786406/b3a6eb3c-0521-11e7-8ace-28ab58f4afdb.png)

As the log shows the echo command adds $NON_SECRET_FROM_UI  to ~/.test1 file just fine. However  $SECRET_FROM_UI (hidden) and $SECRET_FROM_YML (encrypted) variables do not resolve to anything thus the 'login' is empty in ~/.test2 and ~/.test3

**Comment by BanzaiMan** [comment]
Looks like all your builds are PR builds. If the PRs are coming from a fork, we do not decrypt any secret. This is documented in https://docs.travis-ci.com/user/encryption-keys. Does this fit your situation?

**Comment by zaro0508** [comment]
Thanks for the reply BanzaiMan.  Yes, that is my situation.  This seems like a pretty typical use case to me.   I want to generate a build from a PR for repo A but the build requires cloning a private repo B so I can then deploy the artifacts.  How would I be able to accomplish this use case with Travis?

**Comment by BanzaiMan** [comment]
In general, you cannot. The [JWT addon](https://docs.travis-ci.com/user/jwt) aims to ease this pain, but it is not generally usable.

I do not know your particular circumstances, but you would need a push access to the repo A in order to trigger a same-repo PR, so that your PR has access to the secure environment variables.

I'm closing this now.
