### ISSUE TITLE
PR build is not triggered

### ISSUE THREAD

**Issue by bsipocz** [travis-ci/travis-ci#7447]
I've pushed a commit to this PR: https://github.com/astropy/ci-helpers/pull/174 over an hour ago, and there is still no travis build sheduled to be run. (Appveyor picked it up without problem). I've tried to force push it again, but it still hasn't been picked up.

Other commits pushed to the same organization (e.g. astropy/astropy), but to a different repo have been picked up without any problem.

**Comment by BanzaiMan** [comment]
Thanks for the report. We are tracking this at https://www.traviscistatus.com/incidents/ccp8bj1x2n6y.

**Comment by BanzaiMan** [comment]
The fix is out. Please close and reopen affected PRs to trigger a build.

I'm closing this optimistically, but if you continue to see problems, do let us know.

**Comment by bsipocz** [comment]
Thanks. Closing/reopening didn't help, but force pushing the latest commit did the trick.

**Comment by BanzaiMan** [comment]
@bsipocz Thank you for the report!
