### ISSUE TITLE
phpunit version mismatch on php 5.6 on sudo-enabled infrastructure

### ISSUE THREAD

**Issue by Lex-2008** [travis-ci/travis-ci#7448]
A job with:
* sudo: required
* php: 5.6
* phpunit

Fails with error message like this:
```
This version of PHPUnit is supported on PHP 7.0 and PHP 7.1.
You are using PHP 5.6.30 (/home/travis/.phpenv/versions/5.6.30/bin/php).
```

Sample failing build:
https://travis-ci.org/Lex-2008/php-test/builds/209804825

**Comment by BanzaiMan** [comment]
Looks like the choice of `phpunit.phar` here (https://github.com/travis-ci/php-src-builder/blob/a846a53400a89e4d873623500655b9e646ab2b08/bin/compile#L35-L36) is no longer valid for PHP 5.6.x.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/php-src-builder/builds/209817030 should bundle PHPUnit 5.7 for the new PHP 5.6(.30) archive.

**Comment by BanzaiMan** [comment]
The `5.6` archives have been updated. Please restart the builds to confirm it's working now. Thank you.

**Comment by Lex-2008** [comment]
It works, indeed. Thanks for the impressive fixing speed!
