### ISSUE TITLE
Using IP based postgresql connections

### ISSUE THREAD

**Issue by waghanza** [travis-ci/travis-ci#7449]
Hi,

Testing `postgresql` features on **travis-ci** with https://github.com/will/crystal-pg, I can see that **IP** based connection (when using `SSL`) automatically close connections on empty queries.

@asterite @jhass @waj @will 
I already noticed this issue : https://github.com/will/crystal-pg/issues/84

Failure on https://travis-ci.org/waghanza/crystal-pg/jobs/209803166 using `localhost`
Success on https://travis-ci.org/waghanza/crystal-pg/jobs/209804391 using **socket**

PS : I'm using the **sudo** base environment

**Comment by jhass** [comment]
@BanzaiMan doesn't look like an issue we as community build maintainers can fix to me :)

**Comment by BanzaiMan** [comment]
A simple test yields that `localhost` can be reached with `psql`. I am not sure what might be different for your case. https://travis-ci.org/BanzaiMan/travis_production_test/builds/210851312#L345

**Comment by jhass** [comment]
@will so maybe a bug in crystal-pg afterall?

**Comment by will** [comment]
@jhass yeah it could be, but I have no idea why it'd be only in the newer ubuntu container and not exposed in other situations. Not sure how to track it down.

**Comment by waghanza** [comment]
@BanzaiMan Could come from `travis-ci` or not, not sure now
@jhass Maybe it's effectively `crystal-pg`
@will Suprisingly some test passes on `circle-ci` https://circleci.com/gh/waghanza/crystal-pg/17. will try to fix them
