### ISSUE TITLE
Can I have multiple solution files on one travis build

### ISSUE THREAD

**Issue by rwobben** [travis-ci/travis-ci#7450]
Hello, 

I have a c# project with mulitple solution files.

Must I make a seperate Travis build voor every solution or can I do it on one build. 

Its about this repo  : https://github.com/rwobben/w3resources-csharp-exercises

Roelof

cc: @joshua-anderson,  @akoeplinger, @terry

**Comment by akoeplinger** [comment]
Yes, but you can't use the `solution` key in .travis.yml, you need to invoke xbuild on the .sln's yourself:

```
script:
  - xbuild /p:Configuration=Release solution1.sln
  - xbuild /p:Configuration=Release solution2.sln
...
```

**Comment by rwobben** [comment]
oke, to be sure that I do understand it well. I do not have to tell where the solutions are being found like : 

    directory1/solution1.snl 
    directory2/solution2.snl

**Comment by akoeplinger** [comment]
@rwobben yes you do need to specify the full path to it, I just gave an example above

**Comment by rwobben** [comment]
I did here but still the sln files are not found : 

    script : 
  - xbuild /p:Configuration=Release basic-exercises/CalculateAverage/CalculateAverage.sln 
  - xbuild /p:Configuration=Release basic-exercise/CalculateTwoNumbers/CalcualateTwoNumbers.sln

**Comment by akoeplinger** [comment]
@rwobben the files in your repo have different names, e.g. `CalculateAverage.sln` has a space and `CalcualateTwoNumbers.sln` is called CalculateTwoNumbers.sln.

**Comment by rwobben** [comment]
Changed it and it still fails

**Comment by BanzaiMan** [comment]
Your file references are wrong.

1. `xbuild` probably expects a single file argument. Since your first file contains a space, it needs to be escaped.
1. The second command is missing an `s`.

**Comment by akoeplinger** [comment]
@rwobben I sent you a PR which built successfully :)
