### ISSUE TITLE
Install yarn by default for node builds

### ISSUE THREAD

**Issue by molovo** [travis-ci/travis-ci#7454]
Yarn is supported when a yarn.lock file is present, but *only* if the `install` step is not overridden. There are many instances where multiple install steps are required, and to disable the installation of yarn when `install` is specified seems a little counterintuitive.

At the very least, if the above isn't going to be resolved, it should be mentioned clearly in the docs, since I only discovered that this was the case by stumbling across the yarn announcement blog post.

**Comment by BanzaiMan** [comment]
We should move that logic to somewhere other than `install` (say, `configure` or `before_before_install`), but should not install `yarn` in all cases.

**Comment by molovo** [comment]
Perhaps not enabled by default, but just if a yarn.lock file is present?

**Comment by BanzaiMan** [comment]
Yes, I think that is reasonable.

**Comment by cyberhck** [comment]
And what if I make heavy use of yarn but I `.gitignore` yarn for some reason?

**Comment by BanzaiMan** [comment]
@cyberhck I'm afraid I do not understand what you are asking. Do you perhaps mean you have `yarn.lock` in your `.gitignore`? If so, you can install `yarn` yourself.

**Comment by cyberhck** [comment]
I know I can install yarn myself, I'm sorry I wasn't clear. Is there a reason yarn isn't installed by default? That is without caring for a presence of a lock file?

**Comment by BanzaiMan** [comment]
Build images need to be updated with `yarn`. There is no good way to determine whether the build should install `yarn` except for the presence of `yarn.lock`. Not all Node.js builds need it, so until the build images have it pre-installed, we need to rely on something, and that something is `yarn.lock`.
