### ISSUE TITLE
Travis installing PHPUnit 4.8.35 but running 6.0.8 (composer)

### ISSUE THREAD

**Issue by jankal** [travis-ci/travis-ci#7455]
Please have a look at: ApiGen/ApiGen#783

`composer.json` specifies, that `phpunit/phpunit:4.8.35` should be installed. Travis is installing this.

But then it runs the tests on `phpunit/phpunit:6.0.8`.

Travis.yml: https://github.com/jankal/ApiGen/blob/feature/php7-required/.travis.yml

Composer.json: https://github.com/jankal/ApiGen/blob/feature/php7-required/composer.json

**Comment by BanzaiMan** [comment]
I think this is a variation of https://github.com/travis-ci/travis-ci/issues/7226. You are installing PHPUnit via Composer, but calling one that's installed globally. https://github.com/travis-ci/travis-ci/issues/7226#issuecomment-277521737

**Comment by jankal** [comment]
@BanzaiMan Thanks. Updated. Works just fine right now.
