### ISSUE TITLE
Using cache on OS X triggers Homebrew update

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#7456]
Am noticing new behavior where, when using caching on Travis CI's OS X build workers, Homebrew now autoupdates itself. This seems surprising as it happens after recovering the cache is complete. So am unclear on what it accomplishes. As we don't make use of Homebrew and have to actively remove it ( https://github.com/travis-ci/travis-ci/issues/7190 ), it is undesirable to have to wait for to update. Our goal in doing caching was to cutdown on build time, but given this behavior it may be totally unachievable or at best a wash. Please see this [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/193826758#L51 ) where it doesn't have this behavior back in January and this [one]( https://travis-ci.org/conda-forge/psutil-feedstock/jobs/210560316#L58 ) from today where it does. Is there some way for us to disable this behavior? If not, could it just be disabled outright? Seems this is something users can do for themselves. Perhaps there is some other reason to do this that we are not aware of.

cc @gqmelo

**Comment by BanzaiMan** [comment]
What are you caching? I am not familiar with what files Homebrew needs, but my understanding is that Homebrew *always* runs the update command.

**Comment by jakirkham** [comment]
In the last example above, it is just the Homebrew uninstall script as I was playing around. The previous one is caching [Miniconda]( https://conda.io/miniconda.html ) and some packages it uses. In practice, this latter one will be our typical use case. Both end up just using the directory cache if that is what you are looking for.

So Homebrew doesn't appear to be updating in the non-caching cases I have seen. To provide an arbitrary example of the non-caching case, please take a look at this [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/210562311 ).

In any event, we definitely would prefer to never have Homebrew update run on our builds regardless of caching. FWICT this update takes somewhere between 1.5min-2min. This seems like a suboptimal use of time especially since we just remove Homebrew in the next step.

**Comment by BanzaiMan** [comment]
Ah, I see. `md5deep` is not available on some Mac images, and we are installing it via Homebrew, which causes update due to the change in the Homebrew behavior.

**Comment by BanzaiMan** [comment]
`md5deep` is required for calculating md5 checksums for files being cached.

**Comment by BanzaiMan** [comment]
Try using a more recent Xcode image, please.

**Comment by jakirkham** [comment]
Thanks for investigating.

Unfortunately, we can't upgrade to a newer image. We need access to the 10.9 SDK and `xcode6.4` is the newest image that has that SDK. Or is this image no longer supported too (had upgraded from `beta-xcode6.1`)?

Couple of follow-up questions. If `md5deep` is needed, would it make sense to have the image rebuilt with that requirement already met? Alternatively, is there a reason the system's copy of `openssl`, which also supports `md5` checksums, cannot be used?

**Comment by BanzaiMan** [comment]
Here's a workaround until you can drop support for 10.9 SDK:

The installation of `md5deep` happens [here](https://github.com/travis-ci/casher/blob/master/bin/casher#L216). I pushed a [branch that skips it](https://github.com/travis-ci/casher/tree/no-md5deep). To use this for your caching, modify your `cache` to:

```yaml
cache:
  branch: no-md5deep
  ⋮ # rest
```

This branch may not be maintained in the future, however, so please use it at your own risk.

**Comment by gqmelo** [comment]
@BanzaiMan thanks! This works fine for our use case (```ccache```)

**Comment by BanzaiMan** [comment]
We have disabled Homebrew's auto update with https://github.com/travis-ci/travis-build/pull/1062. As https://travis-ci.org/BanzaiMan/travis_production_test/builds/237612936 shows, this is now effective in shortening the time to install `md5deep`.

If you were using the `no-md5deep` branch as a workaround, you should be able to remove this and not worry about `brew update` kicking in unexpectedly.

I'm closing this now, but if you spot problems, do let us know.

**Comment by jakirkham** [comment]
Thanks for all your work on this, @BanzaiMan. 😄
