### ISSUE TITLE
latest version of PMD fails for linux but works for mac

### ISSUE THREAD

**Issue by johnscancella** [travis-ci/travis-ci#7457]
I currently have a matrix build setup for both linux and mac(https://travis-ci.org/LibraryOfCongress/bagit-java/builds/210554219). Only the linux one is failing though with the latest version of PMD
https://travis-ci.org/LibraryOfCongress/bagit-java/jobs/210554220#L9242-L9243

I also have other CI servers and they are fine
https://ci.appveyor.com/project/johnscancella/bagit-java
https://circleci.com/gh/LibraryOfCongress/bagit-java

**Comment by BanzaiMan** [comment]
Does jcenter.bintray.com accept TLS handshake other than TLS v1.2? If not, Precise is too old. Try using Trusty.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/LibraryOfCongress/bagit-java/jobs/212601845

I deleted the fork, so the PR may not work now (sorry!), but you get the idea.

I'm closing this now.
