### ISSUE TITLE
Waiting for status to be reported

### ISSUE THREAD

**Issue by nelson-liu** [travis-ci/travis-ci#7460]
Travis-ci checks seem to not update in https://github.com/allenai/deep_qa

I checked the requests, and there are not any delivered from PRs...however, hitting the "test this integration" button on github for travisCI runs a build on master, which suggests that it works.

Interestingly enough, it seemed to work fine ~2 hrs ago.

sample PRs:
https://github.com/allenai/deep_qa/pull/254
https://github.com/allenai/deep_qa/pull/255

Thanks!

**Comment by jrichard0725** [comment]
We're seeing the same issue on a private repo?

**Comment by BanzaiMan** [comment]
Sorry about that. Last Friday's similar issue (https://github.com/travis-ci/travis-ci/issues/7447) resurfaced. We are working on a fix.

Thank you for the report and patience.

**Comment by BanzaiMan** [comment]
This issue has been rectified. Please close/reopen the affected PR, or push a new commit to it, and confirm that it is working for you now.

Thanks, again, for your patience!

**Comment by nelson-liu** [comment]
@BanzaiMan thanks for the prompt resolution!

**Comment by jaques-sam** [comment]
Please reopen, this issue is still popping up sometime:
![image](https://user-images.githubusercontent.com/42445148/45496907-bb3a8a80-b776-11e8-8d9e-b8bb7b7272a0.png)

**Comment by BanzaiMan** [comment]
@jaques-sam Please subscribe to https://www.traviscistatus.com/incidents/d16clc6zpd85 Thanks.
