### ISSUE TITLE
F# 4.1

### ISSUE THREAD

**Issue by gusty** [travis-ci/travis-ci#7464]
@joshua-anderson @akoeplinger @nterry Do you know when F# 4.1 will be supported? I see in my travis builds it still uses F# 4.0

**Comment by akoeplinger** [comment]
It will be once the version bundled with Mono is updated which should happen in the next release.

I'm not sure if there's a way to get the new F# independently e.g. from nuget

**Comment by gusty** [comment]
Thanks @akoeplinger , please let me know when it is integrated. I have a build that will  only succeed with F# 4.1

**Comment by gsomix** [comment]
@gusty For the moment you can use `FSharp.Compiler.Tools` package with latest F#. Just install it with the help of `Paket`:

```
  - mono ./.paket/paket.exe add nuget FSharp.Compiler.Tools version 4.1.0 
  - mono ./.paket/paket.exe install 
```

and refer to build targets in `.fsproj`:

``` xml
    <When Condition="Exists('..\packages\FSharp.Compiler.Tools\tools\Microsoft.FSharp.Targets')">
      <PropertyGroup>
        <FSharpTargetsPath>..\packages\FSharp.Compiler.Tools\tools\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
```
