### ISSUE TITLE
$TRAVIS environment variable not being set

### ISSUE THREAD

**Issue by ofek** [travis-ci/travis-ci#7469]
https://github.com/ofek/bit/blob/master/tests/test_wallet.py#L213 https://travis-ci.org/ofek/bit/builds/211396575

**Comment by BanzaiMan** [comment]
It is most definitely defined and exported. https://travis-ci.org/BanzaiMan/travis_production_test/builds/211438163#L129

**Comment by ofek** [comment]
Closing this. Apparently tox deletes all env vars by default so one must do this: https://github.com/ofek/bit/blob/master/tox.ini#L10
