### ISSUE TITLE
Install specific version of Yarn

### ISSUE THREAD

**Issue by wearhere** [travis-ci/travis-ci#7471]
Hi folks, it seems that you currently [install the latest version](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/node_js.rb#L209) of Yarn when a `yarn.lock` file is present. This seems risky to me since then it can't be guaranteed that local developers are using the same version of Yarn as CI, and a build might break out from under us when Yarn releases a new version. Yarn themselves recommend locking in a specific version of Yarn in [their instructions for TravisCI](https://yarnpkg.com/en/docs/install-ci#travis-tab), but their suggested config is pretty complex.

I'm wondering if perhaps the Yarn version could be controlled via `.travis.yml` similar to [how the NodeJS version is controlled](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/node_js.rb#L106). A specific version would not be required, but if provided, would be [passed to the Yarn install script](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/node_js.rb#L209) as Yarn describes [here](https://yarnpkg.com/en/docs/install#alternatives-tab).

Would you accept a PR against https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/node_js.rb for this?

**Comment by BanzaiMan** [comment]
I am against adding a new key to control Yarn versions. We do not provide such capability for other package managers (Bundler, npm, Composer).

**Comment by wearhere** [comment]
Do you acknowledge the concerns about always installing latest though? How would you suggest we solve those?

An alternative would be for Travis to choose a single version, and consciously update that similar to how you update other package versions, rather than always installing latest.

**Comment by BanzaiMan** [comment]
> Do you acknowledge the concerns about always installing latest though? How would you suggest we solve those?

Override `install`.

**Comment by BanzaiMan** [comment]
Yarn installation logic may change soon. See #7454.

**Comment by wearhere** [comment]
Interesting, ok. I think it sounds fair to leave it to the developer to install a specific version of yarn in some override. Could I ask you to comment here when it's clear where I should place that override? 

I'd be particularly curious about doing it in `before_install` [like what Yarn itself suggests](https://yarnpkg.com/en/docs/install-ci#travis-tab), because then I wouldn't have to override `yarn install` too. It seems that if I installed yarn in `before_install` (at least at present), Travis' default `install` step would detect the presence of my yarn [here](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/node_js.rb#L52) and continue with `yarn install` without reinstalling yarn.

**Comment by BanzaiMan** [comment]
Since `before_install` is also customizable, I think I'll move it to an earlier phase (either `setup` or `configure`; it is not particularly important to the end user which).

**Comment by wearhere** [comment]
You mean you'd install Yarn before any developer overrides run? That'd be slightly unfortunate in a scenario like this bug describes, because Travis' own install would be unnecessary; the developer would end up immediately reinstalling Yarn.

**Comment by BanzaiMan** [comment]
The goal would be to simulate the future build image update that will come with the latest (at the time of the image provisioning) version of Yarn.

**Comment by wearhere** [comment]
Ohh. At which point a specific version will be baked into the build image, and documented, and only updated when a new build image is released? That'd be cool.

**Comment by BanzaiMan** [comment]
Installation of `yarn` now happens before any user customization. As such, if you need a specific version of `yarn`, please customize your build to run the installer, as explained in https://yarnpkg.com/en/docs/install#alternatives-tab. For example:

```yaml
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version [version]
  ⋮
```

Can we close this?

**Comment by wearhere** [comment]
Thanks @BanzaiMan! Last question, is `~/.yarn` automatically cached? That's where the installer script from above extracts yarn to (see [here](https://github.com/yarnpkg/website/blob/master/install.sh#L35)), and it checks that directory in order to avoid unnecessarily reinstalling the same version:

<img width="809" alt="screen shot 2017-03-27 at 6 06 53 pm" src="https://cloud.githubusercontent.com/assets/110000/24384370/369b4f3e-1318-11e7-9136-8b10f0fd3bb6.png">

**Comment by BanzaiMan** [comment]
There is no automatic caching.

**Comment by wearhere** [comment]
Ok thanks @BanzaiMan, will remember to do that myself. Cheers!

P.S. When you update the build image to include Yarn, per your comment [here](https://github.com/travis-ci/travis-ci/issues/7471#issuecomment-286923330), that'll be published [here](https://docs.travis-ci.com/user/build-environment-updates/), right?

**Comment by BanzaiMan** [comment]
@wearhere Yes! You can expect the build image updates on that page. Thank you!

**Comment by OliverJAsh** [comment]
This was working fine for us until today. Now, it seems the custom install doesn't override the default Travis install.

**Comment by OliverJAsh** [comment]
We needed to add `- export PATH=$HOME/.yarn/bin:$PATH` to our `before_install`. Not sure how it worked before, nor what changed.
