### ISSUE TITLE
Why is Travis CI taking too long to download Node.js?

### ISSUE THREAD

**Issue by abhisheksoni27** [travis-ci/travis-ci#7474]
I issued a pull request to Fly.js' repository, which has Travis CI set up, but the checks haven't completed yet,  because of slow download of Node.js' source.

Link to Travis jobs: [Travis build job](https://travis-ci.org/flyjs/fly/jobs/211705786)
Here's the link Travis is using: [Node.js Soruce](https://nodejs.org/dist/v7.7.3/node-v7.7.3-linux-x64.tar.xz)

I tried opening the link on my laptop, and it is working, with good down-rate.

**Comment by BanzaiMan** [comment]
Hello. We are looking into the issue. Thank you for reporting!

**Comment by MariadeAnton** [comment]
@abhisheksoni27 - could you try restarting the [Travis build job](https://travis-ci.org/flyjs/fly/jobs/211705786) and let us if it's persistent? We appreciate the help!

**Comment by abhisheksoni27** [comment]
@MariadeAnton &ndash; I have requested the owner of the repository to restart the build job again.

**Comment by jbucaran** [comment]
@abhisheksoni27 @BanzaiMan Thanks! 🙏

**Comment by BanzaiMan** [comment]
Closing this now.
