### ISSUE TITLE
C# 7 Mono support

### ISSUE THREAD

**Issue by jlewin** [travis-ci/travis-ci#7477]
It would be very helpful to indicate the status of C# 7 Mono support in the [dotnet guide](https://docs.travis-ci.com/user/languages/csharp/) as users upgrade to VS2017 and start trying out new language features.

We recently upgraded to VS2017 and due to the timing of the Mono 4.8.0 release, assumed that it would support all the new compiler/language features. After pushing some commits which utilized new C# 7 aspects, our Travis builds quickly went down. We initially thought that we just needed to reconfigure them to tweak the compiler or target runtime but slowly are coming to the realization that might not be the case.

Mono has very little documentation that we could find describing C# 7 support and the 4.8.0 Release Notes lack any details regarding xbuild compatibility. I finally found the following forum discussion that pretty clearly says there's no support:

https://forums.xamarin.com/discussion/86664/any-roadmap-for-c-7

Any insight that you could provide in the docs regarding this new functionality seems like it would be helpful as others stumble into this situation and look for guidance as to what's supported or what workarounds, if any, exist

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by akoeplinger** [comment]
@jlewin switching from mcs/xbuild to the Roslyn C# compiler and msbuild is currently being worked on, it should hit the next Mono release. At that point you'll be able to use C#7.

There will be alpha releases that you can try out as always :)

**Comment by akoeplinger** [comment]
Oh forgot one thing: if your projects are using .NET Core you can use C#7 today since it ships with Roslyn.

**Comment by jlewin** [comment]
@akoeplinger - thanks for the confirmation. We'll rollback and wait for C#7 support in the next Mono release.

**Comment by BanzaiMan** [comment]
I'm closing this, then, since there is nothing for us to do.
