### ISSUE TITLE
RabbitMQ is already started in trusty container

### ISSUE THREAD

**Issue by manthey** [travis-ci/travis-ci#7480]
Sometime between two days ago (March 14) and today, trusty containers already have the RabbitMQ service started.  Before, I started the service via 

```
services:
  - rabbitmq
```

Now, when this executes, I see the message:
```
sudo service rabbitmq-server start
 * Starting message broker rabbitmq-server       * message broker already running
```
and then when I try to use the broker via celery I see an error `consumer: Connection to broker lost. Trying to re-establish the connection...`

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by manthey** [comment]
See https://travis-ci.org/girder/large_image/jobs/211851994 for a failed job.  A job from a few days ago that passed is here: https://travis-ci.org/girder/large_image/jobs/210970050

**Comment by BanzaiMan** [comment]
Is the connexion failing on the _first_ attempt to connect to the RabbitMQ server? The failing job started at 2017-03-16T18:05:54Z, but according to the logs, the first indication of the failure came [at 2017-03-16 18:18:59,939](https://travis-ci.org/girder/large_image/jobs/211851994#L4418). The command `JASMINE_TIMEOUT=15000 ctest -VV` had run [for 350 seconds](https://travis-ci.org/girder/large_image/jobs/211851994#L3714) before bailing.

My guess is that the RabbitMQ died.

There is no change in the build image.

**Comment by manthey** [comment]
It seems like there must be some change in the build image, as the report form `sudo service rabbitmq-server start` is different from a few days ago.  The command that bailed did so because a secondary task never received messages from rabbitmq and therefore never performed some work, so the failure occurred well before the failure (the logs with the failures are printed at the end of the job _if_ it failed).

**Comment by BanzaiMan** [comment]
Sorry, but there isn't any change, to the best of my knowledge.

https://travis-ci.org/girder/large_image/jobs/210970050#L14
https://travis-ci.org/girder/large_image/jobs/211851994#L14

**Comment by manthey** [comment]
It turns out I was include `rabbitmq-server` in my list of apt-packages.  Prior to March 14, this package was on the latest version, so asking to install it did nothing, and the travis services properly started rabbitmq.  On March 16, a new version of rabbitmq-server was available, and apt installed the new version, starting the rabbitmq server in the process, which then didn't work as expected.

Removing `rabbitmq-server` from the `addons: apt: packages:` list solved the problem.

Thank you very much for all of your help.
