### ISSUE TITLE
Travis not set hidden Environment Variables

### ISSUE THREAD

**Issue by KhasanovBI** [travis-ci/travis-ci#7481]
![image](https://cloud.githubusercontent.com/assets/8990821/24038282/d300eeec-0b11-11e7-8b21-678c10e5ff11.png)

![image](https://cloud.githubusercontent.com/assets/8990821/24038303/e85ce94e-0b11-11e7-8a50-19dfb5a67d65.png)

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by KhasanovBI** [comment]
https://travis-ci.org/hh-school/bot-resume-builder/builds/212035515

**Comment by BanzaiMan** [comment]
That is a PR, so we don't make secure vars available for security reasons. See https://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests.
