### ISSUE TITLE
Print more info's in logs when deploying

### ISSUE THREAD

**Issue by al3xst** [travis-ci/travis-ci#7484]
It would be very useful, to see in the logs if the file, which should be deployed, is not found (and nothing is uploaded/replaced).

Also it would be a nice addition to see a list of files which where found and deployed successfully in the log. 

For example something like appveyor is doing: https://ci.appveyor.com/project/al3xst/knossos/build/1.0.5#L1735

**Comment by BanzaiMan** [comment]
Thanks for the report. Could you elaborate on what provider you are interested in? You can also look at the code: https://github.com/travis-ci/dpl/.

**Comment by al3xst** [comment]
In my case its Github Releases, but I think others will also benefit from this, if this is possible/makes sense with other providers.
Thanks for the link, I'll have a look.

**Comment by al3xst** [comment]
Hm, maybe it was an error in my travis.yml. Logging of successful file uploads and overwrites exists and appears now in my travis-ci log.
I'm closing this issue and will open one for missing files in https://github.com/travis-ci/dpl/
Thank you very much!
