### ISSUE TITLE
Exclude dir from S3 deployment

### ISSUE THREAD

**Issue by rbrtmrtn** [travis-ci/travis-ci#7485]
I'm attempting to build a Node.js app and deploy it along with build artifacts to S3, however I want to exclude the `node_modules` directory. I know there's a parameter `local_dir` for the S3 deployer -- can I use glob syntax or something similar to keep that one folder out?

**Comment by BanzaiMan** [comment]
I believe you can use `before_deploy` to remove everything in `node_modules` to achieve the same thing. https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle

**Comment by BanzaiMan** [comment]
Can we close this?

**Comment by rbrtmrtn** [comment]
It seems like `before_deploy` is the best bet, so I'll go ahead and close. Thanks @BanzaiMan

**Comment by pavelkomarov** [comment]
This advice doesn't seem to work for me. I can remove my tests directory in before_deploy, but I still see Travis putting the tests in to the deployment.

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by pavelkomarov** [comment]
I'm working in python, so travis runs `sdist` which runs `setup.py`, and my `setup.py` was doing a search for all packages. Evidently the `before_deploy:` `- rm -R package/tests` didn't get executed perfectly before setup, so it still found my tests directory and tried to add it to the deployment. The solution was to update the setup script to exclude tests. It is unclear why removing in `before_deploy` would not work.

**Comment by insub** [comment]
check the Job Log -> raw job log.
i think maybe you need sudo.
`- sudo  rm -R package/tests`
