### ISSUE TITLE
PR Builds not getting created

### ISSUE THREAD

**Issue by jrichard0725** [travis-ci/travis-ci#7487]
Using a private repo, it looks like we aren't getting builds to trigger on new pull requests.

This is a pretty major blocker to our dev team and moving code forward.

**Comment by joshk** [comment]
Hi @jrichard0725 

I'm sorry for the issues.

Could you please email support@travis-ci.com and we can look into this.

I'll close this issue for the time.

Thanks

Josh

**Comment by jrichard0725** [comment]
@joshk We did email support and have gotten no response. We've been blocked on this all day.
We emailed support this morning and only received the "We got your email" response at 10:18am MST this morning. Since then, no response or resolution.
