### ISSUE TITLE
Release only when a tag is applied to a specific branch?

### ISSUE THREAD

**Issue by buunguyen** [travis-ci/travis-ci#7488]
I've been reading up the doc and issues but can't find a way to restrict deployment to only when a tag is applied to a specific branch. 

I was expecting the following config to deploy only when tagging master: 

```
  on:
    tags: true
    branch: master
```

However, with that config, tagging doesn't trigger deployment at all. But if I set `all_branches: true`, then it would deploy when tagging other branches, which I don't want.

Is there a way to do what I need?

**Comment by BanzaiMan** [comment]
Git tags are applied to git object independent of any git branch; you can be detached from any git branch, and still apply a tag. (`git checkout HEAD~1; git tag deadbeef`)

So, in general, what you are asking for is not possible.

**Comment by buunguyen** [comment]
Thanks for your reply.

Let's say I have 2 branches with their own .travis.yml files, each with a separate deployment config (e.g. deploy to different NPM repos). When a tag is made in either branch, I suppose both deploy jobs will run?

**Comment by BanzaiMan** [comment]
> When a tag is made in either branch

This does not make sense.

But, yes, when you push a tag, whatever it is, it will trigger a build.

**Comment by buunguyen** [comment]
Sorry I wasn't clear.  I meant if there are 2 travis files in 2 branches and both have their own deployment config. I suppose when tagging a commit, there will be 2 build and then 2 deployments? Or can one file override another somehow?

**Comment by BanzaiMan** [comment]
> I suppose when tagging a commit, there will be 2 build and then 2 deployments?

No, there won't be. You can apply one tag on only one commit. If that commit is on a git branch, it is a coincidence (as overwhelmingly common as this may appear). If you have 2 branches with different HEADs (thus have separate `.travis.yml` files), then you cannot apply the same tag to both of them.

**Comment by buunguyen** [comment]
Thanks a lot for your information!

**Comment by nicolaiparlog** [comment]
Hi, sorry for reviving this zombie thread, but I just stumbled into the same situation and I don't get your explanation, @BanzaiMan:

> Git tags are applied to git object independent of any git branch; you can be detached from any git branch, and still apply a tag.

That's correct, but I don't see how it applies to @buunguyen's request. He's asking for Travis to only release a commit if it is on a specific branch **and** tagged. Travis can already identify each situation, why can't it identify the conjunction?

**Comment by BanzaiMan** [comment]
> if it is on a specific branch and tagged

GitHub sends a single ref on the PushEvent payload, and it is either the branch or the tag, and not both. (And this makes sense for the reasons I explained above.)

**Comment by nicolaiparlog** [comment]
Ok, so if I understand correctly, Travis can't decide just from the event itself whether the condition for `$branch && tagged` is fulfilled, right? It would have to clone the repo and check?
