### ISSUE TITLE
Tensorflow: no attribute tf.tensordot Error?

### ISSUE THREAD

**Issue by n3011** [travis-ci/travis-ci#7491]
tensorflow tensordot attribute error.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by n3011** [comment]
here : https://travis-ci.org/n3011/tefla/builds/212166900

**Comment by jakirkham** [comment]
Sounds like a bug in some Python code either in your library and/or tensorflow. Though it doesn't sound like a Travis CI error.
