### ISSUE TITLE
Could you upgrade the Java 8 version -- seeing compilation failures that don't occur on JDK 1.8 u121

### ISSUE THREAD

**Issue by andyglick** [travis-ci/travis-ci#7492]
I've got a Java project that runs without errors on a Mac running Sierra and JDK 1.8 u121. My project uses Maven and I can run Maven from the command line and from IDEA and am not seeing any compilation errors. I have both the JDK's javac and the Google errorprone-compiler configured. Running each of the compilers on the project on my Mac, there are no compilation errors. 

In contrast the travis-ci builds which use JDK 1.8 u31 are failing consistently with compilation errors, no matter which of the 2 compilers I use.

You can find my project here: https://travis-ci.org/andyglick/cucumber-spring-eclipselink

The only thing that I can think to try is to try a different CI service, but up until this incident I've been very satisfied with the service that you provide.

**Comment by BanzaiMan** [comment]
For OracleJDK 8, see https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338.

For OpenJDK 8, see https://github.com/travis-ci/travis-ci/issues/7337.

Closing as a duplicate.
