### ISSUE TITLE
[bug] Negation doesn't work in .travis.yml

### ISSUE THREAD

**Issue by enumag** [travis-ci/travis-ci#7494]
I want to use `composer oudated` to check if the dependencies of my PHP libraries are up to date. I came up with this command (exit code is 0 for empty output, 1 otherwise):

```
! (composer outdated --direct | grep ^)
```

I tried to [add it to my .travis.yml](https://github.com/Arachne/Verifier/commit/55133d32814d389d95fd5bf9db6391f6ce5c4bc0) but the build has [failed](https://travis-ci.org/Arachne/Verifier/jobs/212636941#L288) because the exclamation mark was omitted for some reason.

EDIT: As a work around I came up with [this](https://github.com/Arachne/Verifier/commit/8be89d0da2bdb6f7d12c122494b383793b0d896c):

```
echo "! (composer outdated --direct | grep ^)" | sh
```

**Comment by BanzaiMan** [comment]
`!` is a special character in YAML.

```yaml
! (composer outdated --direct | grep ^)
```

recuces to a string literal
```yaml
composer outdated --direct | grep ^
```

See http://stackoverflow.com/a/9703472/136333.

**Comment by BanzaiMan** [comment]
You can also write a string:

```yaml
"! (composer outdated --direct | grep ^)"
```

**Comment by enumag** [comment]
Thank you!

**Comment by olleharstedt** [comment]
Still an issue in 2021?

**Comment by olleharstedt** [comment]
Seems like wrapping the command in quotation caused a "Could not parse" error.
