### ISSUE TITLE
Build doesn't start for a while, and the the build errors.

### ISSUE THREAD

**Issue by timotree3** [travis-ci/travis-ci#7498]
[Build 297](https://travis-ci.org/metacurrency/holochain/builds/212725215) never started and then after something like 6 hours, errored.

I have since restarted the build and it passed, so it shows that it passed. 

I expected the build to at least start. If it helps, the commit that errored was from a pull request. (the tests done on the secondary branch when the PR was created passed)

**Comment by BanzaiMan** [comment]
Sorry about the issue. Have you seen this issue since?

**Comment by timotree3** [comment]
@BanzaiMan Not that I'm aware of. It's not a big deal. Just letting you know that there may have been some glitch.

**Comment by BanzaiMan** [comment]
OK. Let's close this for now. If you see this again, do let us know.
