### ISSUE TITLE
Gem::RemoteFetcher::UnknownHostError: timed out

### ISSUE THREAD

**Issue by roschaefer** [travis-ci/travis-ci#7499]
*Explain, as detailed as possible, how to reproduce the issue.*

If I click on "Restart build" on our [current master branch at Travis](https://travis-ci.org/roschaefer/rundfunk-mitbestimmen/builds/212787005), the build fails with: `Gem::RemoteFetcher::UnknownHostError: timed out`. The gem that fails to be installed is different for every new build.

*Include what you expected to happen, as well as what actually happened.*

I expect `bundle install` to succeed, not to fail. I can not reproduce the problem on my machine. In fact, the build *was* green for [this commit ](https://travis-ci.org/roschaefer/rundfunk-mitbestimmen/builds/212817892) already before. There is no [recent incident on ruby gems](https://status.rubygems.org/history). I moved the command `bundle install` to the top of my `.travis.yml` to make sure there is no inter-dependency with the rest of the script. So I assume this to be related to Travis' infrastructure, nameserver etc.

*If you're having trouble with a specific build, please include a link to the build or job in question.*

https://travis-ci.org/roschaefer/rundfunk-mitbestimmen/builds/212937653
https://github.com/roschaefer/rundfunk-mitbestimmen/issues/138

**Comment by roschaefer** [comment]
OK, as a last resort, I removed environment variables, addons and suddenly `bundle` [succeeds](https://travis-ci.org/roschaefer/rundfunk-mitbestimmen). I'm OK to close this issue. However, Why does [this commit](https://github.com/roschaefer/rundfunk-mitbestimmen/commit/974f0ebe87e0cdb34299257bbb943731e1801299) fix an issue related to bundler?

**Comment by roschaefer** [comment]
If it's `ssh_known_hosts: aldebaran.uberspace.de` I wouldn't expect that adding a known host will cause problems with any unrelated host like `rubygems.org`.

**Comment by BanzaiMan** [comment]
There was a network issue with rubygems.org, which should now be resolved. Could you try restarting the failing job to confirm?

**Comment by roschaefer** [comment]
@BanzaiMan thanks for the quick reply! As I said, the build is green now. Current problems are related to Travis CI deployment, not Install+Test anymore.

However, I don't know if the problem was caused by your network issue with rubygems.org or my change to `.travis.yml`. Shall I `git reset` to the commit which made the build fail to track down the problem?

**Comment by BanzaiMan** [comment]
Could you try restarting the jobs that failed to install gems? https://travis-ci.org/roschaefer/rundfunk-mitbestimmen/builds/212937653 and https://travis-ci.org/roschaefer/rundfunk-mitbestimmen/builds/212787005 No git commit is necessary.

**Comment by roschaefer** [comment]
Ok both builds are green. To stop the confusion, the error was in fact related to the network issue, not to any code change, right?

**Comment by BanzaiMan** [comment]
> To stop the confusion, the error was in fact related to the network issue, not to any code change, right?

Correct. The code change did not cause the problem you had.

I'm closing this now.
