### ISSUE TITLE
Travis with R 3.3.3

### ISSUE THREAD

**Issue by fsavje** [travis-ci/travis-ci#7500]
Travis fails when I run it with the following configuration:
```
sudo: false
language: r
r: 3.3.3
```

Specifically, I get the following error message.
```
$ curl -Lo /tmp/R-3.3.3-$(lsb_release -cs).xz https://s3.amazonaws.com/rstudio-travis/R-3.3.3-$(lsb_release -cs).xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243    0   243    0     0   4299      0 --:--:-- --:--:-- --:--:--  4584
$ tar xJf /tmp/R-3.3.3-$(lsb_release -cs).xz -C ~
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command "tar xJf /tmp/R-3.3.3-$(lsb_release -cs).xz -C ~" failed and exited with 2 during .
```

Versions 3.3.2 and below work well, however. Could it be that Travis cannot find the R installer?

@craigcitro @hadley @jimhester

**Comment by BanzaiMan** [comment]
Clearly, there is no 3.3.3 archive available yet.

The `curl` command should run with `-f`, so that when the URL is 404, the build can give a clear indication of why.

**Comment by jimhester** [comment]
The 3.3.3 build now exists and will become the default once https://github.com/travis-ci/travis-build/pull/1010 is merged.

**Comment by fsavje** [comment]
Excellent, thank you!
