### ISSUE TITLE
Artifacts add-on: Access Denied error not displayed on Travis

### ISSUE THREAD

**Issue by birdsarah** [travis-ci/travis-ci#7501]
My assets weren't uploading, this is the end of the debug output from Travis:

```sh
..
assets/style.css: no such file or directory
  retry: 2
ERROR: failed to upload: /home/travis/build/test/68998280.html
assets/20e28182428903b2619580fd00061422.txt
assets/2ab8a28e5882c593e79561e618a257a0.png
assets/49686bcc48c65a6fc1217fed3873dfdb.png
assets/d708b0fdf7ff39ed464c7d4542459263.txt
assets/style.css
  err: open /home/travis/build/test/68998280.html
assets/20e28182428903b2619580fd00061422.txt
assets/2ab8a28e5882c593e79561e618a257a0.png
assets/49686bcc48c65a6fc1217fed3873dfdb.png
assets/d708b0fdf7ff39ed464c7d4542459263.txt
assets/style.css: no such file or directory
Done uploading artifacts
```

I cloned https://github.com/travis-ci/artifacts and ran it locally with the same credentials, the result I got was:

```sh
ERRO[0007] failed to upload: /tests/assets/style.css  err=Access Denied
ERRO[0007] failed to upload: /tests/123.html  err=Access Denied
```

So, I'm guessing I've got a permissions issue which is entirely possible. 

But it would have been helpful to see the `AccessDenied` error not `no such file or directory`

**Comment by birdsarah** [comment]
Closing this. The problem was finding the file. The `$(git ls-files -o)` and `artifacts upload` were not being run from the same directory.

**Comment by BanzaiMan** [comment]
For the record: you can get debug output from `artifacts` with

```yaml
addons:
  artifacts:
    # ⋮
    debug: true
```

Or setting `ARTIFACTS_DEBUG=1` either with `.travis.yml` or repository settings.

https://docs.travis-ci.com/user/uploading-artifacts/#Debugging

**Comment by birdsarah** [comment]
The above output was copied from debug mode.
