### ISSUE TITLE
Mono on OS-X: Curl regularly dropping out

### ISSUE THREAD

**Issue by leezer3** [travis-ci/travis-ci#7502]
I'm seeing curl regularly dropping the network connection when trying to get the Mono package.

The transfer percentage is random, but it's happening an awful lot.

Couple of sample logs:
https://travis-ci.org/leezer3/OpenBVE/jobs/213199613
https://travis-ci.org/leezer3/OpenBVE/jobs/213205644

Can we get some retry logic on this at all, or someone to look at why the connection keeps dropping?
It's wasting VM time, which on OS-X is rather at a premium :)

@joshua-anderson @akoeplinger @nterry

**Comment by computeronix** [comment]
Happening here as well: https://travis-ci.org/bonesoul/CoiniumServ/jobs/213649708

**Comment by akoeplinger** [comment]
I'm seeing this as well quite often. It might be related to the switch to Azure CDN that we did last week.

**Comment by natemcmaster** [comment]
We're also seeing issues with curl to Azure, both to Azure CDN endpoints and Azure Cloud Storage endpoints (their certificates are different). Example:
https://travis-ci.org/aspnet/Identity/jobs/213540574

**Comment by natemcmaster** [comment]
FYI the error we see is
```
curl: (56) SSLRead() return error -36
```

**Comment by leezer3** [comment]
Now this is funky:
https://travis-ci.org/leezer3/OpenBVE/jobs/221756708

Not quite sure what's happened here (Was watching the build...); Saw the Curl error and the build said it had errored, but it seems to have started re-downloading Mono again.

Does this tell the Travis folks anything interesting?

**Comment by akoeplinger** [comment]
I worked around the issue by switching to wget which has a much better retry/resume behavior than curl.

I still see the connection aborts on the majority of builds though.
