### ISSUE TITLE
npm deployment documentation wrong re 'email' field

### ISSUE THREAD

**Issue by ankon** [travis-ci/travis-ci#7506]
https://docs.travis-ci.com/user/deployment/npm/ says
> For npm version 2+ your api_key can be found in your ~/.npmrc file. In your .npmrc you should see a line similar to //registry.npmjs.org/:_authToken=YOUR_API_KEY. A minimal configuration for publishing to npmjs.org with npm version 2+ looks like:
> 
> ~~~~
> deploy:
>   provider: npm
>   api_key: "YOUR_API_KEY"
> ~~~~

This is not true: the 'email' field is required, and not having it leads to errors in Travis:
~~~~
Preparing deploy
NPM version: 4.1.2
missing email
failed to deploy
~~~~

(https://travis-ci.com/Collaborne/collaborne-qa/builds/42392232)

**Comment by BanzaiMan** [comment]
Hmmm. Could this be a recent change to npmjs.org? Either way, we welcome your documentation PR (the easiest way is to click on the "Improve" button on the upper right corner)!

Thank you for reporting!

**Comment by ankon** [comment]
Fair enough then :)

**Comment by svenmuennich** [comment]
I just ran into the same issue and am wondering now why this change is not reflected in the [published docs](https://docs.travis-ci.com/user/deployment/npm/). It looks like the changes made in #1088 were reverted by 92b6eb5936c665dc7c67f2998c28f0dd287403da.
