### ISSUE TITLE
No space left on legacy device, but the status page is all green.

### ISSUE THREAD

**Issue by andreif** [travis-ci/travis-ci#7508]
I am getting builds errored from time to time trying to build private docker image due to `No space left`. The status page is still green. Is it normal and I should just restart such builds or something is broken?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by andreif** [comment]
<img width="939" alt="screen shot 2017-03-22 at 10 43 40" src="https://cloud.githubusercontent.com/assets/259691/24216560/f713d7c0-0f3c-11e7-8c37-461a3b9610b0.png">

**Comment by andreif** [comment]
@BanzaiMan Where should I mail it? My address is in my profile

**Comment by BanzaiMan** [comment]
If you'd rather not discuss this in public, please close this issue and email details to support@travis-ci.com. Thank you!

**Comment by andreif** [comment]
Alright, I think the issue is public so it should be open. There is a similar issue #4659 also related to Docker.

**Comment by BanzaiMan** [comment]
Very well, then. I'm going to close this as a duplicate. If you have a build log URL to share, please post it on #4659.

**Comment by andreif** [comment]
@BanzaiMan That's not a duplicate at all. If you want to close an issue then the old one is a better choice since it's about false positives.

**Comment by andreif** [comment]
BTW your support was so far very slow, unrelated and useless, so I would prefer reporting issues here where you reply quickly and other users can also contribute.

**Comment by BanzaiMan** [comment]
> That's not a duplicate at all.

OK, I can reopen this.

Please provide the build log URL that shows the problem you are seeing. I see the fragments of the issue here and in #4659, but neither shows the entire picture to provide meaningful support.

If you do not wish to discuss it publicly, that is fine; we'll close this again and continue over the support ticket. Please email support@travis-ci.com.

Thanks.

**Comment by BanzaiMan** [comment]
Have you sent support email yet?

**Comment by andreif** [comment]
I close it for now and will email support when it happens again, thanks!
