### ISSUE TITLE
Some Basic Questions on lifecycle

### ISSUE THREAD

**Issue by Wetitpig** [travis-ci/travis-ci#7509]
According to my understanding, the build process must consist of one job or several parallel jobs. A one-job flow diagram shown below:

A - B - C

Or paralleling:

A
B
C

Is there a way of branching? I want to run a common 'install' script and then branch into 'script's with a matrix. I.e:

A - B
|
C

Thanks

**Comment by BanzaiMan** [comment]
Each job within a build matrix is independent, and there is no way to have dependency among them.

**Comment by Wetitpig** [comment]
So there is a maximum of 200 jobs for a build?

**Comment by Wetitpig** [comment]
If I want to create a new job for each directory, can I do something like:

```
script:
- ./script.sh $a
env:
- for b in `find ./a -mindepth 1 -maxdepth 1 -type d`; do a=b; done
```

Thanks

**Comment by BanzaiMan** [comment]
Build configuration must finish before *any* part of job is executed. Since it is not possible to execute `for bi in …` without actually booting build VMs, such invocation is not possible.

If you know the content of `./a` when you commit `.travis.yml`, you can do something like:

```yaml
script:
  - ./script.sh $SUB_DIR
env:
  - SUB_DIR=sub_dir1
  - SUB_DIR=sub_dir2
  - SUB_DIR=sub_dir3
```

**Comment by Wetitpig** [comment]
But it would be like 400 jobs. It exceeds the number of job limit.

Example repo (https://github.com/termux/termux-packages)

**Comment by BanzaiMan** [comment]
You can perhaps group a few of them into a job in a build matrix. These are constraints you have to work with.

**Comment by BanzaiMan** [comment]
Can we close this? I do not think there is anything left to do here.
