### ISSUE TITLE
build successful, but status is errored

### ISSUE THREAD

**Issue by zh99998** [travis-ci/travis-ci#7511]
this one:
https://travis-ci.org/mycard/mycard-store/jobs/213751488

it finished successfully, but status says errored

**Comment by BanzaiMan** [comment]
Sorry, but the build did not pass. https://travis-ci.org/mycard/mycard-store/jobs/213751488#L280

Your script deployment did not come back, so the build was terminated.

**Comment by zh99998** [comment]
well, then the problem is messy logs 
it says 
```
Done. Your build exited with 0.
```
at the end.

**Comment by BanzaiMan** [comment]
There is no such text in https://s3.amazonaws.com/archive.travis-ci.org/jobs/213751488/log.txt, though. Are you looking at the right build log?

**Comment by zh99998** [comment]
sorry, I refreshed this page and it's right.
seems I'm looking at logs before `restart build` .
