### ISSUE TITLE
Cannot test against Ruby 2.4.1

### ISSUE THREAD

**Issue by tagliala** [travis-ci/travis-ci#7512]
Hi,

I'm having an issue while testing against the just released 2.4.1 version of Ruby:

https://travis-ci.org/diowa/icare/builds/214165138

```
5.52s$ rvm use 2.4.1 --install --binary --fuzzy
ruby-2.4.1 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-2.4.1 do rvm gemset create ' first, or append '--create'.
The command "rvm use 2.4.1 --install --binary --fuzzy" failed and exited with 2 during .
Your build has been stopped.
```

Is there something I'm missing on my side?

TIA

**Comment by BanzaiMan** [comment]
Thanks for the report.

I have kicked off the [2.4.1 build](https://travis-ci.org/travis-ci/travis-rubies/builds/214221906) just now. When it passes it will be available for use.

**Comment by tagliala** [comment]
Thanks!

💚 https://travis-ci.org/diowa/icare/builds/214165892

**Comment by AlJohri** [comment]
@BanzaiMan can you add a build for 2.4.2? thanks!

**Comment by tagliala** [comment]
Hi @AlJohri , Ruby 2.4.2 works for me on travis: https://travis-ci.org/lemurheavy/coveralls-ruby/jobs/276561346

**Comment by AlJohri** [comment]
Ah, I just got this message:

```
--2017-09-18 20:09:12--  http://rubies.travis-ci.org/osx/10.12/x86_64/ruby-2.4.2.tar.bz2
Resolving rubies.travis-ci.org... 23.23.117.107, 23.21.48.33, 54.243.117.186
Connecting to rubies.travis-ci.org|23.23.117.107|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-18 20:09:12 ERROR 404: Not Found.
```

maybe the path has changed?

**Comment by AlJohri** [comment]
Seems like its missing for Mac OS X 10.12? http://rubies.travis-ci.org/

**Comment by AlJohri** [comment]
Ah, seems related to https://github.com/travis-ci/travis-ci/issues/8430 and https://github.com/travis-ci/travis-ci/issues/7848

**Comment by radityagumay** [comment]
Hi. i still have problem Gemset '' does not exist, 'rvm ruby-2.4.1 do rvm gemset create ' first, or append '--create'.
