### ISSUE TITLE
Build timeout only on Mac

### ISSUE THREAD

**Issue by juliohm** [travis-ci/travis-ci#7514]
Hello,

First of all, thank you for this great tool, Travis has improved my workflow tremendously. I have an issue regarding the Mac build, it usually times out whereas the Linux build works just fine:

https://travis-ci.org/juliohm/ImageQuilting.jl

Please check the builds for Julia 0.5, which is the current release of the language. The build failures for nightly are expected.

Is there any workaround for this issue? I was reading the [docs](https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out) and thought it would be interesting to ask here first before I try to prefix the julia command with `travis_wait`.

**Comment by juliohm** [comment]
What can be done about it?

**Comment by juliohm** [comment]
@BanzaiMan can you help with this or cc someone else that can provide support?

**Comment by juliohm** [comment]
This issue is beyond my control and I ma quite positive that it is an issue about installing dependencies instead of running tests. All the time spent in the Mac build is in getting all the test dependencies installed. The tests themselves run quickly.

What can be done to get the build working in Mac again?

**Comment by BanzaiMan** [comment]
If you can cache the dependencies or find a trusted source of binary files you need, you can reduce the build time. Your build requires them, but they are not present on the Mac images. https://docs.travis-ci.com/user/caching/

**Comment by juliohm** [comment]
Thank you @BanzaiMan , but this is an issue that goes beyond my roles as a package developer. I am using the standard methods in Julia to get the build going. Should I report this issue somewhere else?

**Comment by BanzaiMan** [comment]
Sorry, but that is how Julia implementation is done on the Mac.

As documented in https://docs.travis-ci.com/user/languages/julia, Julia is a community-supported language. If you have suggestions on improving it, pleas work with @tkelman @ninjin @staticfloat @simonbyrne to realize it.

**Comment by juliohm** [comment]
Do you guys see any solution here?

**Comment by staticfloat** [comment]
Sorry @juliohm it looks to me like you just have pushed the boundary in terms of raw number and breadth of packages+dependencies to install.  We are, as always, working to improve the binary dependency installation story on all platforms, but I don't have any short-term solutions for you that wouldn't require significant engineering effort.  We hope to eventually build much faster and more reliable binary installation methods, but at this time, we don't have anything on offer yet.

**Comment by juliohm** [comment]
Thank you @staticfloat, I appreciate your attention. I will wait for future developments, Julia is improving at the speed of light and I am sure these small issues will go away at some point.

**Comment by BanzaiMan** [comment]
Is this an issue Travis CI should be tracking, then? If not, can we close this?

**Comment by staticfloat** [comment]
I would vote to close this.  @juliohm for future reference, there is some (slow, inconsistent) progress being made toward better binary building infrastructure at this repository, but we're still sketching things out: https://github.com/JuliaPackaging/BinaryProvider.jl

**Comment by tkelman** [comment]
For a shorter term solution I'd look into using the travis caching functionality. You would need to add extra Pkg.update steps and it could be error prone to have stale dependencies so I don't think it would be appropriate to enable by default everywhere. Another thing you could try would be installing (non-overlapping) subsets of your dependencies manually in parallel processes

**Comment by BanzaiMan** [comment]
Thanks, everyone! I'm closing this now.
