### ISSUE TITLE
Build is failing only on Travis-CI

### ISSUE THREAD

**Issue by v-nisidh** [travis-ci/travis-ci#7517]
We are using Travis CI & Appveyor to build MSSQL JDBC jar.

This week we added new plugin `maven-bundle.plugin` from `org.apache.felix` in our pom file. Unfortunately latest version i.e. 3.3.0 is braking our build saying unresolvable build extension. It works fine on Appveyor CI & local build system. 

As I did not enable any kind of cache on Travis-CI.

**Plugin**
````
<plugin>
         <groupId>org.apache.felix</groupId>
         <artifactId>maven-bundle-plugin</artifactId>
        <version>3.3.0</version>
        <extensions>true</extensions>
        <configuration>
             ....
            ....
````

**Exception**
````
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.microsoft.sqlserver:mssql-jdbc:6.1.5 (/home/travis/build/v-nisidh/mssql-jdbc/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:3.3.0 or one of its dependencies could not be resolved: Could not find artifact org.apache.felix:maven-bundle-plugin:jar:3.3.0 in central (http://repo.maven.apache.org/maven2) -> [Help 2]
````

I double check with maven repo and maven central. This plugin is available there. 

`http://mvnrepository.com/artifact/org.apache.felix/maven-bundle-plugin`

In order to create this issue I used temp branch. Please see this [commit](https://github.com/v-nisidh/mssql-jdbc/commit/6eea79e4e382b0e6501325c2c4fe41ab74e820d5). 

Travis Failed Build [#89](https://travis-ci.org/v-nisidh/mssql-jdbc/builds/214838555)
Travis Previous Successful Build [#86](https://travis-ci.org/v-nisidh/mssql-jdbc/builds/214483293)

**Comment by kullfar** [comment]
+1
I have the exatly same problem. By failed build is https://travis-ci.org/scribejava/scribejava/builds/220506374

**Comment by PascalSchumacher** [comment]
Apache PDFBox is suffering from the same problem, e.g.: https://travis-ci.org/apache/pdfbox/jobs/228088394

**Comment by BanzaiMan** [comment]
Not sure if any change on our side has caused this. Could someone take a look at how we might fix it? Local testing procedure is explained in https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally.

**Comment by dynamodan** [comment]
This is an issue for me also when doing a `git clone` followed by `mvn clean install` with everything default.

**Comment by kullfar** [comment]
Can travis try to add '-U' option to this line
'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'
may be mvn on travis has cached missing dependency and do not want to refresh it?

**Comment by kullfar** [comment]
or even maybe docker image cached this failure in the local mvn repo, so resolution will not be reattempted ever.

Does docker image contains such directory?
~/.m2/repository/org/apache/felix/maven-bundle-plugin/3.3.0
mvn output:
```
Failure to find org.apache.felix:maven-bundle-plugin:jar:3.3.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
```

**Comment by PascalSchumacher** [comment]
Problem seems fixed https://travis-ci.org/apache/pdfbox/jobs/230901647

According to @lehmi

>The maven guys did some magic with the repository. So, no need to downgrade the version of the plugin.

see https://github.com/apache/pdfbox/pull/37

**Comment by BanzaiMan** [comment]
Great. I'm closing this now.
