### ISSUE TITLE
Can't start docker `trusty` image

### ISSUE THREAD

**Issue by ruslo** [travis-ci/travis-ci#7518]
Hi,

I'm trying to follow instructions from [Running a Container Based Docker Image Locally](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally) for `sudo:false` + `dist:trusty` but got error "Tag latest not found in repository":

```
> docker run --name travis-debug -dit travisci/ci-amethyst /sbin/init
Unable to find image 'travisci/ci-amethyst:latest' locally
Pulling repository docker.io/travisci/ci-amethyst
docker: Tag latest not found in repository docker.io/travisci/ci-amethyst.
```

Also I need image similar to one used for `lang:cpp`. What I should use `ci-amethyst` or `ci-garnet`?

Thanks

**Comment by BanzaiMan** [comment]
Our Trusty images do not have the `latest` tag, so you'll need to specify a tag. Consult https://hub.docker.com/r/travisci/ci-amethyst/tags/, for example, for valid values.

**Comment by ruslo** [comment]
> Consult https://hub.docker.com/r/travisci/ci-amethyst/tags/, for example, for valid values

Okay, thanks, I see. Just curious, there is no such problem with quay.io images, is it a problem with hub.docker.com?

>  I need image similar to one used for lang:cpp. What I should use ci-amethyst or ci-garnet?

Can you please give me the hint about this one?

**Comment by BanzaiMan** [comment]
You don't have to specify the tag on the quay.io images because there are `latest` tags on them. (https://quay.io/repository/travisci/travis-ruby?tag=latest&tab=tags)

As for amethyst or garnet—either should do, since the requirements for C++ should be met by either.

**Comment by BanzaiMan** [comment]
Can we close this?
