### ISSUE TITLE
Switch from TGZ to Brotli for caching

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#7519]
Brotli has been proven to be a better and faster (de)compression algorithm both for text and binary.
It can decrease build times for us and storage for Travis itself.

There is a CLI written in OCaml named [brozip](https://github.com/fxfactorial/brozip) which may or may not fit the build workers. There are also bindings for Python and Ruby which you guys can use to write your own simple CLI.

**Comment by BanzaiMan** [comment]
Thanks for opening this issue.

This is an interesting possibility for the future, but I do not see this happening any time soon for the following reasons:

1. The utility is not available for Ubuntu (on the official APT repository), or on the Mac (via Homebrew). This necessitates our developing and maintaining a new cookbook to compile and install it from source.
1. `tar` does not understand this compression. Our cashing utility relies on `tar` to do the work. Supporting the compression that `tar` does not understand brings more complexity to the code.

**Comment by thedrow** [comment]
You could change the caching utility to invoke Brotli instead of tar though.

**Comment by Vdragon** [comment]
Does `brozip` support preserve file permissions?  This is important for files such as executables.

**Comment by thedrow** [comment]
That's what we should be doing anyway. Brotli would replace gzip.

**Comment by BanzaiMan** [comment]
We will revisit this when/if Brotli replaces gzip. Until then, the work involved to realize this is too great for the benefit it is supposed to deliver, in my opinion.

**Comment by thedrow** [comment]
:+1:
