### ISSUE TITLE
Build failed with empty log

### ISSUE THREAD

**Issue by Netshroud** [travis-ci/travis-ci#7520]
[This build](https://travis-ci.org/SteamRE/DepotDownloader/builds/215420375) failed - I expected it to - but with **no build output**.

I have no idea if it failed the way it should have, or something else went horribly horribly wrong.

How can I see what happened here?

**Comment by BanzaiMan** [comment]
Try again. We have received a few reports of this kind; the logs do not appear until a little while after the build has finished. I suspect this was the case for yours.

**Comment by BanzaiMan** [comment]
I'm closing this optimistically. If you see problems, do report again, please.

**Comment by katwre** [comment]
Hi, I have the same issue and don't know what to do with it. I don't expect this build to fail, R CMD check on my laptop is ok. https://travis-ci.org/BIMSBbioinfo/genomation
