### ISSUE TITLE
web server running on port in one build prevents web server from starting in different build on separate port

### ISSUE THREAD

**Issue by havok2063** [travis-ci/travis-ci#7522]
I'm trying to run my test suite using a local Flask web server, in both python 2.7 and 3.4 environments.  When I run each build individually each web server starts fine and all tests run and pass.  However, trying to run builds for both python 2.7 and 3.4 at the same time fails.  One web-server always starts fine but the second web-server always fails to load, even when both servers are starting on separate ports.  What is the proper way to start a web-server to ensure multiple python environments can be tested?  

Here is my travis.yml file. 

```
language: python

sudo: false

python:
- '2.7'
- '3.4'

os:
- linux

services:
- postgresql
- memcached

addons:
  postgresql: '9.4'
  apt:
    packages:
      xvfb
      nano

branches:
- master

before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh
- bash ~/miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda

install:
- conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib ipython --quiet
- source activate test_env
- pip install -r requirements.txt --quiet
- pip install psycopg2 --quiet
- pip install blinker --quiet
- pip install nose --quiet
- pip install coverage --quiet
- pip install pytest --quiet
- pip install pytest-cov --quiet
- pip install pytest-sugar --quiet
- python setup.py install

before_script:
- export MANGA_LOCALHOST=1
- export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/python
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- sh $TRAVIS_BUILD_DIR/bin/setup_travis
# make a local port based on python version, e.g. 5027 or 5034
- export LOCAL_MARVIN_PORT=50${TRAVIS_PYTHON_VERSION/.}
# start the local web server on port 50XX
- $TRAVIS_BUILD_DIR/bin/run_marvin -l -d -p $LOCAL_MARVIN_PORT > /dev/null &
- sleep 10
# list the processes running
- lsof -Pnl +M -i4
# test the web server is running
- curl http://localhost:$LOCAL_MARVIN_PORT/marvin2/api/general/getroutemap/

script:
- py.test python/marvin/tests -v --cov python/marvin --cov-report html

after_success:
- coveralls  
```

I pipe the web server standard out into /dev/null.  I've also tried not doing that and I get the same result.  I expected each build to be independent, and originally had my web server start on port 5000, but changed it to be unique to the python build.  I get the same problem regardless.  I print some things as checks.   Here is an example of output when the 2.7 web server started fine, and all tests ran, and the 3.4 server failed to start.  I get the same results, but reversed, when the 3.4 build slightly leads the 2.7 build. 

The 2.7 successfully starts the web server on port 5027 and a curl produces output. 

```
$ lsof -Pnl +M -i4
COMMAND  PID     USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
Xvfb    3516     1000    1u  IPv4 67036287      0t0  TCP *:6099 (LISTEN)
python  3698     1000    5u  IPv4 67163206      0t0  TCP 127.0.0.1:5027 (LISTEN)
python  3698     1000    7u  IPv4 67154596      0t0  TCP 172.17.0.5:55988->155.101.19.34:443 (ESTABLISHED)
python  3698     1000    8u  IPv4 67162470      0t0  TCP 172.17.0.5:55964->155.101.19.34:80 (ESTABLISHED)
python  3713     1000    5u  IPv4 67163206      0t0  TCP 127.0.0.1:5027 (LISTEN)
python  3713     1000    7u  IPv4 67154596      0t0  TCP 172.17.0.5:55988->155.101.19.34:443 (ESTABLISHED)
python  3713     1000    8u  IPv4 67162470      0t0  TCP 172.17.0.5:55964->155.101.19.34:80 (ESTABLISHED)

$ curl http://localhost:$LOCAL_MARVIN_PORT/marvin2/api/general/getroutemap/
--------------------------------------------------------------------------------
INFO in __init__ [/home/travis/build/sdss/marvin/python/marvin/web/__init__.py:146]:
Loading config file: /home/travis/build/sdss/marvin/python/marvin/web/configuration/localhost.cfg
--------------------------------------------------------------------------------
WARNING:root: * CAUTION: flask-profiler is working without basic auth!
WARNING:werkzeug: * Debugger is active!
{
  "data": null, 
  "error": null, 
  "inconfig": {}, 
  "status": 1, 
  "traceback": null, 
  ...
}
```
The 3.4 build fails to start the web server on port 5034 and curl fails. 

```
$ lsof -Pnl +M -i4
COMMAND  PID     USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
Xvfb    3532     1000    1u  IPv4 34279725      0t0  TCP *:6099 (LISTEN)

$ curl http://localhost:$LOCAL_MARVIN_PORT/marvin2/api/general/getroutemap/
curl: (7) couldn't connect to host
The command "curl http://localhost:$LOCAL_MARVIN_PORT/marvin2/api/general/getroutemap/" failed and exited with 7 during .
```
What exactly am I doing wrong here?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by havok2063** [comment]
Yeah, here is the raw log for the build that worked, python 2.7. 

https://s3.amazonaws.com/archive.travis-ci.org/jobs/215340324/log.txt

and here is the log for the build that failed, python 3.4.

https://s3.amazonaws.com/archive.travis-ci.org/jobs/215340325/log.txt

I did manage to get both web servers to start up by increasing the amount of sleep time from 10 seconds to 20 seconds.  I don't know why this mattered since it takes <10 seconds for one web server to start up in one build.  It was also incredibly challenging to track down.  Basically trial and error.   So if you can glean anything from the logs, let me know.

**Comment by BanzaiMan** [comment]
So, it took a little longer than you expected for the server to start responding? This is not uncommon when it comes to servers, unfortunately.

**Comment by havok2063** [comment]
Yeah sure, I get that.  It's just strange if each build is supposed to be independent of one another.  If each build is a single independent one-off instance, then I expect roughly the same behavior between the builds.  Anyway, it can be documented here for posterity as a thing to try when people get failures with no output or indication of anything wrong.

**Comment by BanzaiMan** [comment]
I am having a hard time believing that the jobs are related. The ones indicated in the previous comment didn't even run on the same Docker host. The workloads on the hosts can differ wildly, too.

At any rate, is there anything else for us to do here?

**Comment by havok2063** [comment]
No I think this can be closed.
