### ISSUE TITLE
"No builds for this repository" despite .travis.yml file, permission granted and sync done

### ISSUE THREAD

**Issue by na4lapy** [travis-ci/travis-ci#7523]
Hi, 

we can't get builds to run for https://travis-ci.org/na4lapy/na4lapy-panel despite following the setup process strictly. Could you please take a look?

**Comment by BanzaiMan** [comment]
Have you pushed any commit to the repository since activating Travis CI?

**Comment by wojciech-bilicki** [comment]
Yes :)

https://github.com/na4lapy/na4lapy-panel/commit/c4ac33ad080caa404a94caa2f395379704014ee5

**Comment by na4lapy** [comment]
Solved
