### ISSUE TITLE
Xcode 8.3 support

### ISSUE THREAD

**Issue by NachoSoto** [travis-ci/travis-ci#7524]
The final release is out! :)

**Comment by BanzaiMan** [comment]
Thanks for alerting us. We are working on it!

**Comment by emdantrim** [comment]
I suspect that it'll be out very soon, but not until after EOD PST.
thanks for your excitement!

✨

**Comment by JagCesar** [comment]
Hey guys! Sorry to be *that* guy, but do you have any estimations on when this will be done? We would like to know if we can start upgrading to 8.3 yet, or if we should hold our horses. :)

**Comment by emdantrim** [comment]
8.3 is launched! expect a blog post and tweet soon :)

**Comment by emdantrim** [comment]
ah, there it is! https://blog.travis-ci.com/2017-03-28-xcode-83-ga-is-here
