### ISSUE TITLE
Travis shows "Job log" instead of "Build Jobs"

### ISSUE THREAD

**Issue by SuperTux88** [travis-ci/travis-ci#7526]
## Steps to reproduce:
Open https://travis-ci.org/diaspora/diaspora/builds/215323751

## Expected Results:
Travis shows the build overview with the jobs.

![spectacle nt2945](https://cloud.githubusercontent.com/assets/458548/24385362/0ca97cd0-136a-11e7-986d-3b9ab9f08fa5.png)

## Actual Results:
Travis tries to load "Job log" endless.

![spectacle zw2945](https://cloud.githubusercontent.com/assets/458548/24385355/fe1d826a-1369-11e7-91e3-f3c224a17367.png)

## Additional steps to "fix" it
1. Click on "Build History"
2. Select same build as before (or any other build)
3. Build overview is shown as expected :)

## More ways to reproduce it
* After it works with the steps above, press F5 on the build overview page and it is broken again and tries to load the "Job log" again.
* Open https://travis-ci.org/diaspora/diaspora/branches and select a build, it is also broken.

Tested with Firefox and Chromium on Linux.

**Comment by BanzaiMan** [comment]
Is this the only build that exhibits this strange behavior? (I checked a few others, but didn't find any.)

**Comment by denschub** [comment]
It happens to all of our builds (check https://travis-ci.org/diaspora/diaspora/builds/161192838 for example), but it seems to work for another repo I just checked. Obviously, this only applies to builds with multiple build configurations.

**Comment by SuperTux88** [comment]
It was with all builds (at least all builds of diaspora, I didn't check other projects). But it seems fixed now, I can't reproduce it again, so I close this issue.
