### ISSUE TITLE
cache: bundler results in 0MB caches

### ISSUE THREAD

**Issue by jleclanche** [travis-ci/travis-ci#7527]
Example builds:
https://travis-ci.org/HearthSim/hearthsim.info
https://travis-ci.org/HearthSim/hsdecktracker.net
https://travis-ci.org/HearthSim/HearthstoneJSON.com

All of them use the [same travis.yml file](https://github.com/HearthSim/hearthsim.info/blob/master/.travis.yml). Yet, all of them result in 0MB caches; the next build redownloads everything.

Maybe related to #3126

Ideas?

**Comment by BanzaiMan** [comment]
You are [overriding the default `install` command and running `bundle install`](https://github.com/HearthSim/hearthsim.info/blob/213e507872719ce6035b400f48ccc8446b109b3c/.travis.yml#L8), which puts the gems in the runtime's directory (`~/.rvm/gems/ruby-2.4.0/gems/`), but your directive `cache: bundler` is [adding `vendor/bundle`](https://travis-ci.org/HearthSim/hearthsim.info/builds/215902161#L169).

This behavior should be better explained in the documentation.

**Comment by BanzaiMan** [comment]
It is not clear to me if we can deduce the correct directory to cache when `install` is overridden by an arbitrary command in this way.

**Comment by jleclanche** [comment]
Ah, so `bundle install` is run by default? I guess that means I should remove it?

**Comment by BanzaiMan** [comment]
The default command is explained here: https://docs.travis-ci.com/user/languages/ruby#Travis-CI-uses-Bundler

There is a little more nuance than just `bundle install --jobs=3 --retry=3`, depending on directory structure, but it will try to guess where the caches should go.

**Comment by jleclanche** [comment]
Okay, so my caches are now working, but there is still almost 30 seconds being wasted on purely setting up ruby. See for example: https://travis-ci.org/HearthSim/hearthsim.info/builds/215979549

Is that expected? Is there a way to avoid it?

**Comment by BanzaiMan** [comment]
It is required since 2.4.0 is not pre-installed on the build image.
