### ISSUE TITLE
Build log is not showing

### ISSUE THREAD

**Issue by limonte** [travis-ci/travis-ci#7528]
Examples: 

- https://travis-ci.org/vaadin/vaadin-button/builds/203830592
- https://travis-ci.org/vaadin/vaadin-date-picker/builds/214670437
- https://travis-ci.org/vaadin/vaadin-grid/builds/215534414

Expected result: showing the build log.

Actual result: infinite spinner.

**Comment by snopoke** [comment]
Also having this issue on a number of different builds for the last 12 hours e.g. https://travis-ci.org/dimagi/commcare-hq/builds/215859123

**Comment by limonte** [comment]
![](https://i.imgur.com/kHYY5VR.png)
