### ISSUE TITLE
fatal: reference is not a tree: 8747d37b8e209ba1ff2d8e38120bee21dc34a269

### ISSUE THREAD

**Issue by jacinzhang** [travis-ci/travis-ci#7530]
I user Travis CI to build my project. but when I commit by amend, so git tree don't have before commit, but travis ci still to build before commit that can't find.And  it give me error below 

![image](https://cloud.githubusercontent.com/assets/9859965/24400946/f48be806-13e4-11e7-9bf5-a6cd32d18b89.png)

![image](https://cloud.githubusercontent.com/assets/9859965/24401207/05b57de4-13e6-11e7-98a8-27e332893168.png)

I don't want build in **hexo** branch, and detach commit id.

and I try to delete current branch, user another branch, It still does't work.

so anyone can help me, I can't resolve it.

**Comment by BanzaiMan** [comment]
The commit we test must be reachable from the clone. If it's not reachable, you can't build it.

https://travis-ci.org/jacinzhang/jacinzhang.github.io/builds/215831735 does not show this error, though. Do you have a build log URL that actually shows the problem you are having?

**Comment by BanzaiMan** [comment]
https://api.github.com/users/jacinzhang/events tells me that the branch "hexo" was repeatedly created and deleted a couple of times.

```sh-session
$ curl -sq https://api.github.com/users/jacinzhang/events/public | jq 'map(select( ((.type == "DeleteEvent") or (.type == "CreateEvent") ) and .payload.ref == "hexo" )) | map({id: .id, type: .type, time: .created_at})'

[
  {
    "id": "5577928683",
    "type": "CreateEvent",
    "time": "2017-03-28T10:58:35Z"
  },
  {
    "id": "5577923139",
    "type": "DeleteEvent",
    "time": "2017-03-28T10:57:39Z"
  },
  {
    "id": "5577803254",
    "type": "CreateEvent",
    "time": "2017-03-28T10:37:02Z"
  },
  {
    "id": "5577250175",
    "type": "DeleteEvent",
    "time": "2017-03-28T09:12:10Z"
  },
  {
    "id": "5576647105",
    "type": "CreateEvent",
    "time": "2017-03-28T07:29:40Z"
  },
  {
    "id": "5576645601",
    "type": "DeleteEvent",
    "time": "2017-03-28T07:29:22Z"
  },
  {
    "id": "5576568129",
    "type": "CreateEvent",
    "time": "2017-03-28T07:13:08Z"
  }
]
```

My guess is that when you saw these errors, the builds tried to get git data from GitHub with the designated references, but they did not find them because they did not exist.

I'm closing this for now.

**Comment by jacinzhang** [comment]
@BanzaiMan yes, I find Travis CI try to build commit that unreachable, and Travis CI can't skip it, so I restore the commit that by *git amend commit** and restore the deleted branch.

by the way, Travis CI build can't skip unreachable commit, and following commits can't build cause of the unreachable commit.

My propose: Travis CI provides skip unreachable commit.

**Comment by jacinzhang** [comment]
@BanzaiMan There is some other error in this commit, and I need skip this commit to continue build success, Is there a way?

**Comment by BanzaiMan** [comment]
> Travis CI build can't skip unreachable commit

I am not sure what you mean by this. We configure builds with payload GitHub sends us. The builds retain the configuration data; for example, if you restart https://travis-ci.org/jacinzhang/jacinzhang.github.io/builds/215831735, it will try to fetch "the same" SHA (PR builds use a slightly different semantic to determine what "the same" means).

https://travis-ci.org/jacinzhang/jacinzhang.github.io/requests shows that you have configured your repo to build only when `.travis.yml` is present, but it does not exist on the root directory of the repository (e.g., https://github.com/jacinzhang/jacinzhang.github.io/tree/c965dd8ba53cfbaf67c762ca430bef257cb9ed27).
