### ISSUE TITLE
Xcode 8.3 Image: No iPhone 7 Simulator with iOS 10.0

### ISSUE THREAD

**Issue by SlaunchaMan** [travis-ci/travis-ci#7533]
The Xcode 8.3 image has iPhone 7 simulators with iOS 10.1, 10.2, and 10.3, but no 10.0. Can this be added?

**Comment by solarce** [comment]
Thanks for the report. Unfortunately, this is not a regression in the `xcode8.3` image.

The iPhone 7 stopped being an available hardware option for iOS 10 with the Xcode 8.1 release. Our friends at Bitrise.io have fielded [similar issue reports for their 8.2 images](https://discuss.bitrise.io/t/simulators-missing-on-xcode-8-2-x-macos-sierra-environment/379/2).

Unfortunately, there is nothing in the [Xcode 8.1 Release Notes](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-SW24) that references this or offers any insight into _why_ this changed. Nor was I able to find any other references to this, from a few minutes of Googling.

If anyone knows of a conversation or documentation that lends more insight into it, a link would definitely be appreciated.

For posterity's sake, I checked each of our images to confirm this:

- `xcode8`: https://travis-ci.org/solarce/osx-tests/jobs/216145495#L424-L438

```
-- iOS 10.0 --
    iPhone 5 (C6F7DEAE-2901-40C5-9D6F-1B408BB4960E) (Shutdown)
    iPhone 5s (6B841AF0-3FE6-4B33-B022-D5887643B791) (Shutdown)
    iPhone 6 (655E6800-2BE5-4706-AB65-92B50F99A2EF) (Shutdown)
    iPhone 6 Plus (264697C1-E4EB-4985-AB30-A9B90E117F84) (Shutdown)
    iPhone 6s (74EAD8ED-9246-4F49-B02B-BBE2B0EBB8A4) (Shutdown)
    iPhone 6s Plus (DB4D64F5-216F-4AAB-9933-969E4FF1B827) (Shutdown)
    iPhone 7 (5F911B30-5F23-403B-9697-1DFDC24773C8) (Shutdown)
    iPhone 7 Plus (E3B7D09E-DD71-4DAA-9D1D-6B678487D646) (Shutdown)
    iPhone SE (4C741B6B-7647-4DD6-84A0-A71F44552573) (Shutdown)
    iPad Retina (8EF5A478-A243-4986-9F82-B709795478A4) (Shutdown)
    iPad Air (C650BF69-EEC3-487C-BCCA-463CB74F9718) (Shutdown)
    iPad Air 2 (900EA122-D2E1-48E0-A966-312C7953B065) (Shutdown)
    iPad Pro (9.7 inch) (B2F00ECB-ED23-44B0-8461-B8371827727B) (Shutdown)
    iPad Pro (12.9 inch) (CA3CC9FA-151D-4D1E-9958-6DC7E96854F0) (Shutdown)
```

- `xcode8.1`: https://travis-ci.org/solarce/osx-tests/jobs/216145496#L437-L449
```
-- iOS 10.0 --
    iPhone 5 (C6F7DEAE-2901-40C5-9D6F-1B408BB4960E) (Shutdown)
    iPhone 5s (6B841AF0-3FE6-4B33-B022-D5887643B791) (Shutdown)
    iPhone 6 (655E6800-2BE5-4706-AB65-92B50F99A2EF) (Shutdown)
    iPhone 6 Plus (264697C1-E4EB-4985-AB30-A9B90E117F84) (Shutdown)
    iPhone 6s (74EAD8ED-9246-4F49-B02B-BBE2B0EBB8A4) (Shutdown)
    iPhone 6s Plus (DB4D64F5-216F-4AAB-9933-969E4FF1B827) (Shutdown)
    iPhone SE (4C741B6B-7647-4DD6-84A0-A71F44552573) (Shutdown)
    iPad Retina (8EF5A478-A243-4986-9F82-B709795478A4) (Shutdown)
    iPad Air (C650BF69-EEC3-487C-BCCA-463CB74F9718) (Shutdown)
    iPad Air 2 (900EA122-D2E1-48E0-A966-312C7953B065) (Shutdown)
    iPad Pro (9.7 inch) (B2F00ECB-ED23-44B0-8461-B8371827727B) (Shutdown)
    iPad Pro (12.9 inch) (CA3CC9FA-151D-4D1E-9958-6DC7E96854F0) (Shutdown)
```

- `xcode8.2`: https://travis-ci.org/solarce/osx-tests/jobs/216145497#L463-L475
```
-- iOS 10.0 --
    iPhone 5 (C6F7DEAE-2901-40C5-9D6F-1B408BB4960E) (Shutdown)
    iPhone 5s (6B841AF0-3FE6-4B33-B022-D5887643B791) (Shutdown)
    iPhone 6 (655E6800-2BE5-4706-AB65-92B50F99A2EF) (Shutdown)
    iPhone 6 Plus (264697C1-E4EB-4985-AB30-A9B90E117F84) (Shutdown)
    iPhone 6s (74EAD8ED-9246-4F49-B02B-BBE2B0EBB8A4) (Shutdown)
    iPhone 6s Plus (DB4D64F5-216F-4AAB-9933-969E4FF1B827) (Shutdown)
    iPhone SE (4C741B6B-7647-4DD6-84A0-A71F44552573) (Shutdown)
    iPad Retina (8EF5A478-A243-4986-9F82-B709795478A4) (Shutdown)
    iPad Air (C650BF69-EEC3-487C-BCCA-463CB74F9718) (Shutdown)
    iPad Air 2 (900EA122-D2E1-48E0-A966-312C7953B065) (Shutdown)
    iPad Pro (9.7 inch) (B2F00ECB-ED23-44B0-8461-B8371827727B) (Shutdown)
    iPad Pro (12.9 inch) (CA3CC9FA-151D-4D1E-9958-6DC7E96854F0) (Shutdown)
```

- `xcode8.3`: https://travis-ci.org/solarce/osx-tests/jobs/216145499#L496-L507
```
-- iOS 10.0 --
    iPhone 5 (C6F7DEAE-2901-40C5-9D6F-1B408BB4960E) (Shutdown)
    iPhone 5s (6B841AF0-3FE6-4B33-B022-D5887643B791) (Shutdown)
    iPhone 6 (655E6800-2BE5-4706-AB65-92B50F99A2EF) (Shutdown)
    iPhone 6 Plus (264697C1-E4EB-4985-AB30-A9B90E117F84) (Shutdown)
    iPhone 6s (74EAD8ED-9246-4F49-B02B-BBE2B0EBB8A4) (Shutdown)
    iPhone 6s Plus (DB4D64F5-216F-4AAB-9933-969E4FF1B827) (Shutdown)
    iPhone SE (4C741B6B-7647-4DD6-84A0-A71F44552573) (Shutdown)
    iPad Retina (8EF5A478-A243-4986-9F82-B709795478A4) (Shutdown)
    iPad Air (C650BF69-EEC3-487C-BCCA-463CB74F9718) (Shutdown)
    iPad Air 2 (900EA122-D2E1-48E0-A966-312C7953B065) (Shutdown)
    iPad Pro (9.7 inch) (B2F00ECB-ED23-44B0-8461-B8371827727B) (Shutdown)
    iPad Pro (12.9 inch) (CA3CC9FA-151D-4D1E-9958-6DC7E96854F0) (Shutdown)
```

**Comment by solarce** [comment]
The [ruby script]( https://github.com/travis-infrastructure/osx-image-bootstrap/pull/20/files) that I used to help fix, https://github.com/travis-ci/travis-ci/issues/7532#issuecomment-290117745, does a sort of _brute force_ installation of all potential combinations of devices and [iOS|tvOS|watchOS] versions and just errors out on combinations Xcode says it won't support.

Much to my chagrin, there is now a "iOS 10.0 + iPhone 7" combo available, according to `xcrun cimctl list`, see https://travis-ci.org/solarce/osx-tests/jobs/218313787#L500 

As mentioned in #7532, this is new stuff for us to change, so I'm looking for more testing before we promote it to stable.

@SlaunchaMan, would you mind testing with `osx_image: xcode8.3simfix` for this combo and see if it works as desired

If it does then _hey cool_ and if not, we should probably remove it before the we promote a new 8.3 image.

Thanks!

**Comment by SlaunchaMan** [comment]
[Trying now!](https://travis-ci.org/SlaunchaMan/Clusterfuck/jobs/218479290)

**Comment by SlaunchaMan** [comment]
Hmm, my build failed but it did find an iPhone 7 simulator with iOS 10.0. The build isn’t quite stable yet so I consider this fixed nonetheless.

**Comment by solarce** [comment]
Thank you very much for the testing and for the update. I'll close this issue then.

**Comment by solarce** [comment]
The image has been promoted to production, https://blog.travis-ci.com/2017-04-05-xcode-82-83-duplicate-simulator-fixes. The `simfix` images will be removed momentarily.
