### ISSUE TITLE
Expansion of languageConfigKeys on web site is broken for `dart_task`

### ISSUE THREAD

**Issue by kevmoo** [travis-ci/travis-ci#7537]
See https://github.com/travis-ci/travis-web/pull/1024#issuecomment-290141350

Example: https://travis-ci.org/dart-lang/shelf/builds/216071420

1) I noticed the output get cropped in undesirable ways

![dart_task_layout_weird](https://cloud.githubusercontent.com/assets/17034/24464682/6e840024-145f-11e7-92c1-ebf9be5166f0.png)

2) I noticed that if we have more than just a single string for the task we got `[Object object]` instead

*this is with some manual CSS tweaking to show the full value*
![un_clipped_weird_output](https://cloud.githubusercontent.com/assets/17034/24464837/0b722e9c-1460-11e7-9cc6-2405086351bc.png)

CC @BanzaiMan @a14n @lislis

**Comment by BanzaiMan** [comment]
2 is previously reported as #7415.

**Comment by lislis** [comment]
Thanks for the feedback @kevmoo! 
Some background about 1: it was an on-purpose decision to crop the language key section to make space and have the emphasis on the ENV vars.
The language key is usually a rather short string ("XCode 8.4", "Ruby 2.3.1" etc) where ENV settings tend to be more verbose and, for a lot of users, contain more important build information.
That being said, I see how in this case the spacing is sub-optimal. I'm taking this to our Product team to give it another think.

**Comment by kevmoo** [comment]
Any updates @lislis ? The `[object Object]` bits are pretty annoying...

**Comment by lislis** [comment]
Hey @kevmoo I just deployed a fix for the `Task` key and added a bit more space to the language key section (just enough so team ENV vars doesn't complain (hopefully)).
I'll close this, please reopen if there is something else coming up.
