### ISSUE TITLE
"View Config" doesn't show full travis.yml

### ISSUE THREAD

**Issue by mtoothman** [travis-ci/travis-ci#7540]
There is a key (`notifications`)in my .travis.yml for a project that isn't shown by the "View Config" view in the Travis UI.

UI:
![image](https://cloud.githubusercontent.com/assets/4804034/24508494/9454329c-1531-11e7-93d6-ccc0e930c4cd.png)

`.travis.yml`:
```
dist: trusty
language: python
install: []
sudo: required
before_script:
  - a_bunch_of commands
script: my_script
after_success:
- some_more_commands
notifications:
  slack:
    [long_encrypted_value]
```

The notification is sent and received correctly. Why does `View Config` not show the full file?

**Comment by BanzaiMan** [comment]
Config refers to the job configuration returned by API. Notifications are a build concern, which is one level above the jobs.

**Comment by mtoothman** [comment]
Good info, thanks!
