### ISSUE TITLE
S3 Issue with us-east-2

### ISSUE THREAD

**Issue by carsongee** [travis-ci/travis-ci#7541]
I have a build with an S3 bucket deploy that is fails to work to a us-east-2 bucket with `/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:763:in initialize': execution expired (Seahorse::Client::NetworkingError)`:
https://travis-ci.org/Superpedestrian/sp-design-pattern-library/builds/216529066#L2372

Copying that buckets setting and IAM policy to a us-east-1 bucket led to the build succeeding without any other changes (https://travis-ci.org/Superpedestrian/sp-design-pattern-library/builds/216781989#L2368) and diff here: https://github.com/Superpedestrian/sp-design-pattern-library/commit/59a1a6c2faed853eeaa1e791a6df72e7aa6e66d0, so I think there might be an issue going on there.

**Comment by BanzaiMan** [comment]
Do you have a bucket in the US East 2 without a dot in the name?

**Comment by carsongee** [comment]
I'm afraid not since it's a static Website bucket

**Comment by BanzaiMan** [comment]
Ooops. I meant EU West 2.

So, the bucket is in `us-east-1` (because the deployment succeeds)? Then it can't be found in `eu-west-2`.

**Comment by carsongee** [comment]
Oh man, I just realized I typoed the region as `eu` instead of `us`, I'm so sorry, I thought I had checked it like 100 times.  🙇
