### ISSUE TITLE
Projects are in a permanently throttled state

### ISSUE THREAD

**Issue by kellyselden** [travis-ci/travis-ci#7543]
I have multiple OSS projects hooked up to greenkeeper. An event occurred about a week ago that caused multiple npm dependencies to major version update pretty much at the same time. This queued my projects up for many hours. I noticed that after a while, the projects were getting throttled. npm install was taking about 10 minutes, and then the ember build took over 10 minutes and timing out. This is very unusual for these projects that usually finish in 3-5 minutes. So I waited a few days for my projects to be unthrottled, but I just ran master again and it still times out after 20+ minutes. It seems, from an outsider's perspective, that my projects are stuck in a permanently throttled state.

Here is an example of one of these projects: https://travis-ci.org/kellyselden/ember-tree
https://travis-ci.org/kellyselden/ember-tree/builds/215307030
https://travis-ci.org/kellyselden/ember-tree/builds/216072069
https://travis-ci.org/kellyselden/ember-tree/builds/216014499

**Comment by BanzaiMan** [comment]
Could you elaborate on what you mean by "throttled" state?

I took a look at jobs from these builds, but all of them show that your jobs are actually either halting or busy doing something and had not produced any output to STDOUT for 10 minutes.

**Comment by kellyselden** [comment]
I just reran a build from before this whole ordeal, and it not suffering the same fate. I will research more, but it does not to appear to be a throttling issue. Thanks.

**Comment by kellyselden** [comment]
FYI This was an issue of having both all of babel 5 and 6 as dependencies, plus node 4/npm 2 running in Travis. Fixing these issues brought the build back to normal.
