### ISSUE TITLE
Can we get actual version of Python?!

### ISSUE THREAD

**Issue by pcinkh** [travis-ci/travis-ci#7545]
Guys, pls, 10 days from release Python 3.6.1 (release date: 2017-03-21), I'm using travis for non-commercial and commercial projects with expensive plans also. I wanna get 3.6.1 out of box asap, pls. Of course, I know how to compile it, but pls add it, thx.

**Comment by BanzaiMan** [comment]
Sorry for the delay. I'm working on automating these chores, and I would want to have a situation where there is a release newer than the latest archive in our repository (in this case Python).

If I can't get the automation to go in the next few days, I'd trigger a build of 3.6.1 manually.

Thanks.

**Comment by BanzaiMan** [comment]
I ran out of time. 3.6.1 is now available. Also, `3.6` now points to it. https://travis-ci.org/travis-ci/cpython-builder/builds/224434300

**Comment by pcinkh** [comment]
@BanzaiMan thank's a lot!
