### ISSUE TITLE
Cryptic error in R-devel

### ISSUE THREAD

**Issue by zkamvar** [travis-ci/travis-ci#7549]
Hi @craigcitro and @jimhester, 

I have a situation that's been driving me mad for the past couple of days: my package is not building on R-devel due to a cryptic error (https://travis-ci.org/grunwaldlab/poppr/jobs/217208173#L4272-L4275):

```
Quitting from lines 165-166 (poppr_manual.Rmd) 
Error: processing vignette 'poppr_manual.Rmd' failed with diagnostics:
'missing' can only be used for arguments
Execution halted
```

It first started to fail here: https://travis-ci.org/grunwaldlab/poppr/jobs/216129420

Since the error popped up in a vignette where I had defined a function that used `missing`, I attempted to fix it here: https://github.com/grunwaldlab/poppr/commit/715c857d115e72d0087c14daaeffd986f34221ce

Unfortunately, no builds have been able to pass. Note that I made this change during the recent build outage and I don't know if this might be the reason why the build isn't succeeding?

I've cleared the cache to no avail. I've tested the build on the daily build of R-devel via rocker: https://hub.docker.com/r/rocker/drd/ and have also tested it on the debian-gcc-devel platform on RHub (https://builder.r-hub.io/status/poppr_2.3.0.99-45.tar.gz-afcf860bf90d4e2fae68ed1681f50591), but have not been able to reproduce this error. 

I'm just super confused here as to why this is failing.

**Comment by jimhester** [comment]
I think this is a new bug introduced in R, there were recent changes to `utils::citation()` https://github.com/wch/r-source/commit/7890e9e87d44f85ab76c0e786036a191eacd71d1 and it looks (to me) like a call to `missing(citation.bibtex.max)`, which is not an argument. I would suggest seeing if you can reproduce the issue in a minimal script or package and posting it to R-devel.

In any case this is not a travis issue.

**Comment by zkamvar** [comment]
Thank you for the quick reply!
