### ISSUE TITLE
Cannot copy text from the web client on Chrome

### ISSUE THREAD

**Issue by gsabran** [travis-ci/travis-ci#7550]
(not sure this is the best place to report the issue)

I cannot copy any text from the web client on `travis-ci.com`. This makes things very annoying for debugging. I'm on Chrome 57.0.2987.133. Things work fine in Safari, and I tested on another laptop that's running Chrome 56.0.2924.87 and things work fine there as well. Not sure how much this is related to https://github.com/travis-ci/travis-ci/issues/1466 that was specifically about failing to copy log from a sub-process, while I cannot copy anything on the client. Other websites have not that issue.

**Comment by BanzaiMan** [comment]
Hmm. So, this could be a Chrome issue?

Incidentally, I cannot reproduce this issue on this version of Chrome on the Mac.

![job__60499_4_-_travis-pro_chirp-com-production_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/24565441/3bfb3bca-1623-11e7-8ad4-b9fba8820b31.png)

**Comment by gsabran** [comment]
Yeah I've no idea. Feel free to close the issue if it's too vague

**Comment by BanzaiMan** [comment]
I don't think it is too vague, just that I have not been able to reproduce. Does it work on .org for you?

**Comment by gsabran** [comment]
I didn't try. The issue stopped happening a day ago, while my Chrome didn't update. This is weird and might be a chrome issue after all. Thanks.
