### ISSUE TITLE
TRAVIS_BUILD_URL environment variable

### ISSUE THREAD

**Issue by ivailop** [travis-ci/travis-ci#7552]
To be able to provide a link to a build it would be nice to have a ready to use `$TRAVIS_BUILD_URL` environment variable. It is not that hard to construct one:
```
$TRAVIS_BUILD_URL = https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID
```
however since there are `org`, `pro` and `enterprise` services, from inside a build there is no generic way to determine which domain to use.

**Comment by BanzaiMan** [comment]
What is the use case here? You know ahead of time which service your build will be running on, right?

**Comment by ivailop** [comment]
For a generic tool that provides a service on top of a CI, it is very useful to provide a link back to the originating build. For a 3rd party user of that tool, it is inconvinient to explicitly say what is the CI and/or its URL since the tool could figure that out automatically. 

In our case we provide a service (www.testspace.com) for data collection and analysis. When integrated with a CI, we would like to provide a link back to the data origin - the build that produced them.

**Comment by ivailop** [comment]
As an alternative could you provide `TRAVIS_ENDPOINT` and/or `TRAVIS_API_ENDPOINT`? The same as [documented for you Client](https://github.com/travis-ci/travis.rb#environment-variables).

**Comment by asmeurer** [comment]
Is it at all possible to detect programmatically if the build is running in .com or .org? I develop a tool called [doctr](https://drdoctr.github.io/) that syncs to GitHub pages from Travis, and I'd like to include a link to the build in the commit message. Previously this was easy as we only supported .org, but since open source repos now have both with the migration, how can we tell which is which inside of the build? I agree `$TRAVIS_ENDPONT` would be very useful.

**Comment by DrTorte** [comment]
Hey there,

One possible way of doing it could be to make an API call to either api.travis-ci.com or api.travis-ci.org. The successful one would be the correct end point, and using that would let you determine whether it's on .com or .org.

An exceptionally crude example here: https://travis-ci.org/DrTorte/TestDistro/builds/421395081

**Comment by asmeurer** [comment]
@DrTorte thanks for the response.

This doesn't work for me. I ran this code on both: https://github.com/drdoctr/doctr/blob/26ad4520b170f4fe38ee4433ac7d47ddf3b802ce/doctr/travis.py#L591-L594

On both [.org](https://travis-ci.org/drdoctr/travis-ci-com-testing/builds/421692002#L575) and [.com](https://travis-ci.com/drdoctr/travis-ci-com-testing/jobs/142459096#L575) I get

```
travis-ci.com status code 401
travis-ci.org status code 200
```

Note I'm specifically referring to public repos on travis-ci.com, as part of the transition, not private repos (though supporting those as well would be nice).

**Comment by BanzaiMan** [comment]
We now have `TRAVIS_BUILD_WEB_URL` and `TRAVIS_JOB_WEB_URL` for this purpose. The announcement will be made soon.
