### ISSUE TITLE
phpunit for 5.3~5.5 should be updated

### ISSUE THREAD

**Issue by jhdxr** [travis-ci/travis-ci#7555]
It seems the pre-packaged phpunit for php 5.3/5.4/5.5 is still 4.8.27, while the latest release is 4.8.35 (https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4835---2017-02-06) , which including a important change.

4.8.27 was released 9 month ago, so I'm wondering if there is some reason preventing phpunit from upgrade.

**Comment by BanzaiMan** [comment]
The `phpunit` is pre-packaged with the language runtime, which is installed when the build image is provisioned. These archives are not maintained once they are created.

If your build requires a newer version of `phpunit`, we recommend vendoring it, or updating it in the `before_install` phase.

**Comment by jhdxr** [comment]
@BanzaiMan thx, I fixed this issue by adding `before_install`.
