### ISSUE TITLE
add cron-type build if no recent one?

### ISSUE THREAD

**Issue by juju4** [travis-ci/travis-ci#7557]
Hello,

I know build should be as deterministic as possible but for infrastructure, it's not always easy.
As I build and mature my orchestrations roles, some are not often updates.

I wish there was a way to force a build in travis-ci if no build has been triggered since X time, for example a month or a week.

That can allow to easily say what period of time and often dependency change broke the build instead of discovering that 3 month laters.
Bonus point if it can trigger an alarm (email, github issue or else ;)

Thanks

**Comment by BanzaiMan** [comment]
I think this is best addressed in https://github.com/travis-ci/beta-features/issues/1.

**Comment by juju4** [comment]
Exactly that @BanzaiMan. Perfect timing!
