### ISSUE TITLE
"You are not currently a member of  any organization." + "no repo"

### ISSUE THREAD

**Issue by nico-onmap** [travis-ci/travis-ci#7559]
Travis doesn't seem to see my organization (which I am the owner). I have clicked on `Review and add your authorized organizations.` and permissions seem to be ok:

![travis](https://cloud.githubusercontent.com/assets/26772786/24602697/4765d640-185e-11e7-8a45-8a55c00e2fed.png)

Yet, I cannot access any of my (private) repositories:

![travisnorepo](https://cloud.githubusercontent.com/assets/26772786/24602725/6bb6db02-185e-11e7-85d4-2d8b4539e7f4.png)

I also tried clicking on "sync account", without success.

**Comment by BanzaiMan** [comment]
I checked your account earlier on .com, but did not see any evidence of problem. For example, I was able to confirm that your user account is able to access https://travis-ci.com/OnMapDev/onmap_v6/builds/.

**Comment by nico-onmap** [comment]
It seems to be resolved now indeed. Thank you.
