### ISSUE TITLE
before_script curl download fails to write font file on Travis CI

### ISSUE THREAD

**Issue by edouard-lopez** [travis-ci/travis-ci#7560]
thanks for your work on Travis-CI !

I'm hitting a roadblock as I'm downloading a font to test my app. However, writing the file to the disk fail due to some obscure reason.

    $ bash ./test/fetch-fonts.bash
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
    
    100   176  100   176    0     0    526      0 --:--:-- --:--:-- --:--:--   533
    Warning: Failed to create the file 
    Warning: ./resources/fonts/DroidSansFallbackFull.ttf: No such file or 
    Warning: directory
    0 3938k    0  1925    0     0   4737      0  0:14:11 --:--:--  0:14:11  4737
    curl: (23) Failed writing body (0 != 1925)
    The command "bash ./test/fetch-fonts.bash" failed and exited with 23 during .

### Update

I tried with a smaller font (104Kb instead of 3.8Mb) and got the same behavior .

### Question

How could I solve this?

**related:** http://stackoverflow.com/q/43174325/802365

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by edouard-lopez** [comment]
@BanzaiMan sure, https://travis-ci.org/parlr/Hanzi-Pinyin-Font/builds/217895593

**Comment by BanzaiMan** [comment]
https://github.com/parlr/Hanzi-Pinyin-Font/blob/392d3ada5259761438224a1c502499916c962b59/test/fetch-fonts.bash#L3-L5

The URL is a redirect, so you have to follow it with `-L`.

```sh-session
$ curl -I https://github.com/android/platform_frameworks_base/raw/master/data/fonts/DroidSansMono.ttf
HTTP/1.1 302 Found
Server: GitHub.com
Date: Mon, 03 Apr 2017 13:51:32 GMT
Content-Type: text/html; charset=utf-8
Status: 302 Found
Cache-Control: no-cache
Vary: X-PJAX, Accept-Encoding
X-RateLimit-Limit: 100
X-RateLimit-Remaining: 100
Access-Control-Allow-Origin: https://render.githubusercontent.com
Location: https://raw.githubusercontent.com/android/platform_frameworks_base/master/data/fonts/DroidSansMono.ttf
X-UA-Compatible: IE=Edge,chrome=1
X-Runtime: 0.019132
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src render.githubusercontent.com; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="; pin-sha256="k2v657xBsOVe1PQRwOsHsw3bsGT2VzIqz5K+59sNQws="; pin-sha256="K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q="; pin-sha256="IQBnNBEiFuhj+8x6X8XLgh01V9Ic5/V3IRQLNFFc7v4="; pin-sha256="iie1VXtL7HzAMF+/PVPR9xzT80kQxdZeJ+zduCB3uj0="; pin-sha256="LvRiGEjRqfzurezaWuj8Wie2gyHMrW5Q06LspMnox7A="; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Served-By: 50b06cef3698e972f044d7dc2cb41530
Age: 0
X-GitHub-Request-Id: CB58:BD3E:4A033B7:78695E6:58E25363
```

**Comment by BanzaiMan** [comment]
Ah, sorry. You do that with `--location`. I think you need to create the directory `./resources/fonts` so that `curl` can write to it.

**Comment by edouard-lopez** [comment]
@BanzaiMan adding the missing directory solved the issue. Thanks for catching that!
