### ISSUE TITLE
.NET Core builds now failing

### ISSUE THREAD

**Issue by ctolkien** [travis-ci/travis-ci#7565]
>Failed to fetch https://apt-mo.trafficmanager.net/repos/dotnet-release/dists/trusty/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed

Sample travis.yml:

https://raw.githubusercontent.com/ctolkien/ClubHouse/master/.travis.yml

/cc @joshua-anderson, @akoeplinger and @nterry

**Comment by akoeplinger** [comment]
This seems to be a new issue with the .NET Core repository. Here's what I get on my local Ubuntu 14.04:

```
gnutls-cli -p 443 apt-mo.trafficmanager.net
Resolving 'apt-mo.trafficmanager.net'...
Connecting to '13.80.10.205:443'...
*** Fatal error: A TLS fatal alert has been received.
*** Received alert [40]: Handshake failed
*** Handshake has failed
GnuTLS error: A TLS fatal alert has been received.
```

**Comment by akoeplinger** [comment]
Filed https://github.com/dotnet/core-setup/issues/1947 on the MS side.

**Comment by akoeplinger** [comment]
Temporarily switched back to using http for the APT repository URL (which is fine since package integrity is verified via the GPG key) to unbreak the builds.
