### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by damorton** [travis-ci/travis-ci#7569]
Getting the following error when trying to deploy to Heroku from Travis-CI.org

- I have logged in using the travis cli tools using --org 
- Followed the advice here https://docs.travis-ci.com/user/deployment/heroku/ for the API key encryption.

```
Preparing deploy
No stash found.
Expected(200) <=> Actual(401 Unauthorized)
body: "{\"id\":\"unauthorized\",\"error\":\"Invalid credentials provided.\"}" (wrong API key?)
failed to deploy
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by damorton** [comment]
https://travis-ci.org/damorton/java-getting-started/jobs/218555539

**Comment by BanzaiMan** [comment]
This key https://github.com/damorton/java-getting-started/blob/01e97e2e8bc543630e81977f5e72e78876de457c/.travis.yml#L7 is not correctly encrypted. What command did you use to generate it? On what machine?

**Comment by damorton** [comment]
`travis encrypt $(heroku auth:token) --add deploy.api_key` macOS

**Comment by BanzaiMan** [comment]
Were you in the root directory of this repository? Could you try specifying the repo with `-r OWNER/REPO` and dropping `--add …`?

**Comment by damorton** [comment]
`travis encrypt -r damorton/java-getting-started $(heroku auth:token) deploy.api_key`

Same error https://travis-ci.org/damorton/java-getting-started/builds/218598977

**Comment by damorton** [comment]
@BanzaiMan Got it working by specifying the repo in the travis.yml file along with `-r owner/repo` with the travis cli

`travis encrypt -r damorton/java-getting-started $(heroku auth:token) --add deploy.api_key`

```
deploy:
  provider: heroku
  api_key:
    secure: <encrypted api key>
  app: protected-garden-89563
  on:
    repo: damorton/java-getting-started
```

Thanks for your help.
