### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by schmurfy** [travis-ci/travis-ci#757]
Hi,
I used travis and was logged into maybe a week ago but two days ago I wanted to add a repository and noticed I was logged out and now check I click Login it show "Signing in..." and reload the page periodically but never managed to get me in :(

I tried emptying the cache and deleting cookies for travis-ci.org but after clicking again on Login the same thing happens, I tried with Chrome Canary and the latest Chrome stable release with the same result.

**Comment by dotstormz** [comment]
This issue happens again for me in Chrome. Have removed github and travis cookies, revoked access and reinstated. I have also confirmed that I am not blocking any third party cookies and I do not run an ad blocker.

Login works fine in Firefox ....
