### ISSUE TITLE
docker trusty image documentation is out of date

### ISSUE THREAD

**Issue by RogerTangos** [travis-ci/travis-ci#7570]
I'm trying to pull either ci-amethyst or ci-garnet from either dockerhub or quay.io. This would be much easier with just a little love for the docs, and is related to issue #7518.

The [documentation](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally) isn't quite accurate with pulling trusty, but here's what eventually worked.

[instructions provided on dockerhub](https://hub.docker.com/r/travisci/ci-amethyst/):
```
$ docker pull travisci/ci-amethyst
> Using default tag: latest
```

Fair enough. I should try to find a tag.

```
docker run --name travis-debug -dit quay.io/travisci/ci-amethyst:packer-1487189177 /sbin/init
Pulling repository quay.io/travisci/ci-amethyst
docker: Tag packer-1487189177 not found in repository quay.io/travisci/ci-amethyst.
```

Still no success there. Maybe I should switch to dockerhub?
```
docker run --name travis-debug -dit travisci/ci-amethyst:packer-1487189177 /sbin/init
```
Huzzah! Now there's a docker image

**Comment by BanzaiMan** [comment]
The current text is:

> For Ubuntu 14.04 (trusty), select an image from Docker Hub named either ci-amethyst or ci-garnet (which differ slightly depending on language desired).

**Comment by BanzaiMan** [comment]
Whilst technically not incorrect, if you have ideas on how to improve it, we are open to suggestions.

**Comment by RogerTangos** [comment]
Hey @BanzaiMan - thanks for being so open to it. Looking at it again, I agree that it's technically correct, and I was just lost.

Since the ci-amethyst and ci-garnet images need to be pulled from dockerhub instead of quay.io, maybe the documentation could say

> For Ubuntu 14.04 (trusty), select either the `travisci/ci-amethyst` or `travisci/ci-garnet`  (which differ slightly depending on language desired) image from Docker Hub, and append `:` followed by a relevant [amethyst](https://hub.docker.com/r/travisci/ci-amethyst/tags/) or [garnet](https://hub.docker.com/r/travisci/ci-garnet/tags/) tag.

Feel free to edit, and sorry if it's too basic. It's just that docker can be difficult for newcomers, and I was confused by the need to change repositories and then specify a tag.

**Comment by BanzaiMan** [comment]
We've reorganized the text. See https://github.com/travis-ci/docs-travis-ci-com/pull/1159.
