### ISSUE TITLE
Travis CI for a single R script

### ISSUE THREAD

**Issue by Avery62** [travis-ci/travis-ci#7572]
Sorry had to ask this here as i couldn't get an answer elsewhere.
How do i configure .travis.yml for a single R file? The following doesn't work:
```
language: r
script:
  - Rscript example.R
```
Also what's the difference between script and install in the case of a single R file?

**Comment by BanzaiMan** [comment]
Please mention @craigcitro and @jimhester for R inquiries, as indicated in the build log. Thank you.

**Comment by jimhester** [comment]
The `install:` step reads a `DESCRIPTION` file and installs dependencies listed there, the `script:` step builds a package.

So you will need to override both of them if you do not have a package.

Alternatively you can define a simple DESCRIPTION file to install any package dependencies for your script and not override the `install:` step. The DESCRIPTION only needs two lines, one with a 'name' of your package (can be anything) and the list of dependencies. 

```
Package: myscript
Depends: pkg1, pkg2, pkg3
```
