### ISSUE TITLE
Octokit Unauthorized

### ISSUE THREAD

**Issue by KairusDarkSeeker** [travis-ci/travis-ci#7574]
I can't deploy my builds because of this error

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by KairusDarkSeeker** [comment]
Yeah

**Comment by KairusDarkSeeker** [comment]
Here [log.txt](https://s3.amazonaws.com/archive.travis-ci.org/jobs/218828954/log.txt)

**Comment by BanzaiMan** [comment]
I tweaked the Release provider to [dump the api key](https://travis-ci.org/BanzaiMan/travis_production_test/builds/218876162#L396) when [it is defined in the same way](https://github.com/BanzaiMan/travis_production_test/blob/2553af9eabcf8d1f6a44de63846594c0ab9a2ad7/.travis.yml#L38) as your key is. This experiment indicates to me that you have a wrong API key defined in the Settings page. Please double check the value.

**Comment by KairusDarkSeeker** [comment]
Okay

**Comment by Gauravano** [comment]
Hi @BanzaiMan , we are facing similar issue at https://github.com/publiclab/plots2 . All our builds are stuck due to this issue, creating backlog. Here's the build log https://travis-ci.org/publiclab/plots2/builds/386823762utm_source=github_status&utm_medium=notification .Could you please help in tracking the problem? Thanks.

**Comment by BanzaiMan** [comment]
@Gauravano Sorry, but you are using octokit in your own way, so I don't know it's trying to do the job. You'll have to look at how the `danger` command works.

**Comment by Gauravano** [comment]
Thanks for pointer @BanzaiMan !
