### ISSUE TITLE
New account can't find repositories

### ISSUE THREAD

**Issue by sgurin** [travis-ci/travis-ci#7575]
I get "Sorry, it seems like we couldn't find any repositories you have access to on GitHub." sometimes synchronization freezes and unfreezes only after page reload but the repository is not visible anyway. Could you please check this.

**Comment by acnagy** [comment]
@sgurin Sorry for the trouble! Just checked out your account, and it appears that syncing happened successfully. Is it possible you have not [enabled specific repos](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A) for Travis? That said, if you have, please email us with the repo name at support@travis-ci.com, so we can have a look and discuss your account in more detail. Thanks so much!
