### ISSUE TITLE
Incorrect rev in TRAVIS_COMMIT_RANGE

### ISSUE THREAD

**Issue by jugglinmike** [travis-ci/travis-ci#7578]
The TravisCI documentation describes the `TRAVIS_COMMIT_RANGE` environment
variable as follows:

> The range of commits that were included in the push or pull request. (Note
> that this is empty for builds triggered by the initial commit of a new
> branch.)

That typically takes the form `rev1...rev2` where `rev2` is the SHA of the
latest commit on the pull request's branch. In some pull request jobs, `rev1`
seems to reference an arbitrary commit on found on the target branch. The
following is an example of such a job:

https://travis-ci.org/w3c/web-platform-tests/builds/219056744

The relevant lines from the log file:

    $ echo $TRAVIS_COMMIT_RANGE
    4ae9a348adfbed1a35fbcd9611ea243d9cf59be3...d0528a76b95f04d7eddc1ed0e474d3d55c921ba9
    $ git log --oneline --graph --max-count 20
    *   2b3408379 Merge d0528a76b95f04d7eddc1ed0e474d3d55c921ba9 into 5ad0f83711a9427b0e558213da8b1b29be0a0647
    |\  
    | * d0528a76b Add debugging info and remove extraneous config
    | * a06d094dc DEBuG Add demonstration script
    * |   5ad0f8371 Merge pull request #5388 from w3c/chromium-export-fbe66db9fe
    |\ \  
    | * | 66b0c40fd Upstream StorageManager estimate() test to WPT
    * | | 942f9035a [eme] Fix #4285: Remove unused media files (#4286)
    |/ /  
    * |   af6f835b0 Merge pull request #5249 from mrego/more-focus-within-tests
    |\ \  
    | * | 32cac9abc [selectors4] Remove "interact" flag on new :focus-within tests
    | * | da44da22f [selectors4] Add new tests for :focus-within as universal selector
    * | |   65614057c Merge pull request #5261 from mrego/focus-within-test
    |\ \ \  
    | * | | 860fc328d [selectors4] Upstream WebKit test for :focus-within
    | |/ /  
    * | |   4ae9a348a Merge pull request #5316 from mrego/focus-within-fix-ref
    |\ \ \  
    | * | | 1fd81bb5b [selectors4] Fix reference to avoid glitches on :focus-within tests
    | |/ /  
    | * | 4dbd46c93 Fix lint breakage

In this case, the SHA `4ae9a348a` has no particular significance to the target
branch or the pull request branch.

(Small bugs like these aside, Travis CI is an excellent service, so thank you!)

**Comment by BanzaiMan** [comment]
The PR in question https://github.com/w3c/web-platform-tests/pull/5371 has the base commit https://github.com/w3c/web-platform-tests/commit/4ae9a348adfbed1a35fbcd9611ea243d9cf59be3 and the head commit bocoup:pr-demo. When we build the merge commit `+refs/pull/5371/merge:`, the https://github.com/w3c/web-platform-tests/commit/4ae9a348adfbed1a35fbcd9611ea243d9cf59be3 will be used as the base commit, and you will see this as the beginning of the commit range.

**Comment by jugglinmike** [comment]
In that case, my confusion comes from the definition of a pull request's "base
commit." My assumption was that the value would be the parent of the first
commit in the pull request, but your response indicates otherwise. A "pull
request" is not a concept in git itself, so the pull request's "base commit"
must be defined by GitHub.com or TravisCI. Do you know where I could find the
definition of that term?

**Comment by BanzaiMan** [comment]
```
$ curl -s https://api.github.com/repos/w3c/web-platform-tests/pulls/5371 | jq -r .base.sha
4ae9a348adfbed1a35fbcd9611ea243d9cf59be3
```

**Comment by jugglinmike** [comment]
In other words, the "base commit" is defined by GitHub. It looks like I will
have to follow up with their documentation/support staff to learn how it is
defined.

Thank you!
