### ISSUE TITLE
after_success failure doesn't fail build

### ISSUE THREAD

**Issue by letmaik** [travis-ci/travis-ci#758]
[My build](https://travis-ci.org/neothemachine/glge-gwt/builds/3168070) is (correctly) failing but it is not indicated as such. In the [docs](http://about.travis-ci.org/docs/user/build-configuration/) it says "The outcome of any of these commands indicates whether or not this build has failed or passed", but although both commands of the `after_success` block failed, the build is still green. Either the docs are wrong or there's a bug.

**Comment by KeithPepin-MW** [comment]
We have similar issues.  We cut RPM packages in the `after_success`but there are occasional issues generating these, but the build does not fail on these errors.  I'd love an after_build event that would actually fail the build if errors occurred during those processes.

**Comment by leoselig** [comment]
I just want to point out that it's even more severe if you follow the advice to use `after_success` for manual deployments (https://docs.travis-ci.com/user/deployment/custom/)
I just did this and stumbled over this exact issue so it's simply not an option to use it

**Comment by Chronial** [comment]
We ran into the same problem, and at the moment a good fix is to use this in `script` instead of `after_success`:
```bash
if [ $TRAVIS_TEST_RESULT -eq 0 ]; **mycommand**; fi
```

**Comment by nikhilo** [comment]
Q: Is there a document where I can find out which build step is capable of failing the build and which one isn't ?
A: https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build

**Comment by j3mdamas** [comment]
If there was a flexible "deploy" stage (I think deploy affects the build result), it would be a solution. I think many people that are working around this issue are interested in having something that deploys only after successful building and testing, but that still shows on the build result if deployment fails.

**Comment by Kristinita** [comment]
[**AppVeyor sections**](https://www.appveyor.com/docs/build-configuration/#build-pipeline):

+ `build_script` — for build,
+ `test_script` — for tests.

In both sections exit code not a zero, if errors.

Travis CI [**haven't a section for tests**](https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle).

I think, it would be nice, if would be added section for tests as in AppVeyor.

Thanks.

**Comment by msc-** [comment]
Why was this closed. It hasn't been fixed. Perhaps the early closure is why it is still not fixed after 6 years.

**Comment by weironz** [comment]
@Kristinita  yes ,we need a test_script after script
