### ISSUE TITLE
vulnerable url in travis-ci

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis-ci#7585]
Hi,
First of all , you guys are doing a great job , so +1 for you!
Just so you know , there is a small vulnerability that can be hacked to view all job logs that is carried out by your service even private repo job log can viewed!
 
The Vulnerability is , when travis-ci assigns a job to my repo or any public , it gives a url like https://travis-ci.org/DeathSec/AniScrape/jobs/219370723 , so when i change the number 219370723 to some random number , some random project job log is shown sometimes no log is shown.

So please look into it, if it is intentional , then sorry to report this as a issue!

**Comment by BanzaiMan** [comment]
This has been fixed.
