### ISSUE TITLE
`osx_image` doesn't multiply the matrix

### ISSUE THREAD

**Issue by cartr** [travis-ci/travis-ci#7587]
As documented [here](https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix), variables like `os`, `rvm`, and `env` multiply the build matrix; specifying multiple values gives you jobs with every possible combination of them. However, the `osx_image` option cannot be used in this way. Trying to pass multiple values for it produces [jobs with nonsensical "Xcode:" properties](https://travis-ci.org/cartr/qt4-autobottler/builds/219488405).

It seems odd that this wouldn't be supported; presumably projects would want to test compatibility with different OS X versions just as they test compatibility with different Ruby versions.

**Comment by BanzaiMan** [comment]
Thanks for the report. We'll look into it.

**Comment by bdorfman-stripe** [comment]
Is there any progress on this? This is a problem for us especially now as Xcode9/iOS11 is being released and we would like to check on both the new and old systems.

**Comment by mxcl** [comment]
In case it is a useful intermediate solution, I (and others) have worked around this with stuff like:

https://github.com/mxcl/PromiseKit/blob/master/.travis.yml

It's tedious, but this bug/omission has existed for a long time and doesn't seem to have much momentum behind fixing it.

**Comment by bdorfman-stripe** [comment]
Yeah I just pushed something similar to that to our repo, but I was hoping if I made enough noise someone at travis would fix their code so it would do the combinatorics for us the way it does for every other setting :P

**Comment by mxcl** [comment]
“solved”. I'm moving to CircleCI where their tracker isn't 1700 stale issues and a bot doesn't pretend things are solved when they aren’t.

**Comment by KillWolfVlad** [comment]
Worst bot ever.

**Comment by BanzaiMan** [comment]
It's been working since May last year. https://travis-ci.org/BanzaiMan/travis_production_test/builds/441648190
