### ISSUE TITLE
An error occurred when canceling the job

### ISSUE THREAD

**Issue by loint** [travis-ci/travis-ci#7591]
Hi guys,

I face this issue when trying to cancel a very long time job.

When I click to Cancel Job button. Travis tells me that:
"An error occurred when canceling the job"

Do you have any suggestion in this case ?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

If the job had been running for a long time and if it had already finished, you cannot cancel it. (My guess is that the page stopped updating for some reason, and you saw out-of-date logs.)

**Comment by loint** [comment]
Now it's ok, I think it's already finished so can not cancel.
