### ISSUE TITLE
Travis is running an old version of nvm

### ISSUE THREAD

**Issue by dunn** [travis-ci/travis-ci#7593]
The current release is 0.33.1; the CI servers are on 0.23.3: https://travis-ci.org/tootsuite/mastodon/builds/220030071#L286

This means they don't have access to the LTS version-strings, like `lts/boron`, and we have to specify an exact version number instead.

**Comment by BanzaiMan** [comment]
Since you have [`language: ruby`](https://github.com/tootsuite/mastodon/blob/a11ed316213edc9542385650ce2c4ca1bd8ed196/.travis.yml#L1), you are responsible for updating `nvm` if the pre-installed version is not satisfactory.

**Comment by dunn** [comment]
Fair enough.  I forgot I can do `6` instead of `lts/boron` so I don't need to specify an exact version in any case.
