### ISSUE TITLE
git lfs env shows Endpoint with (auth=none)

### ISSUE THREAD

**Issue by scott-plutovr** [travis-ci/travis-ci#7595]
We followed instructions on how to setup the git credential helper from [this issue][1] but I'm not sure it's working properly. 

Essentially our shell script to install git-lfs on an osx image using brew is:
```shell
#!/bin/bash 
brew update 

brew install git-lfs 
echo "https://${GH_TOKEN}:@github.com" > .git/credentials
git config credential.helper "store --file=.git/credentials"
git remote set-url origin https://github.com/PlutoVR/${REPO_NAME}.git
git lfs install
git lfs env
```

However, when we look at the output of that git lfs env we see,
```
Endpoint=https://github.com/PlutoVR/core.git/info/lfs (auth=none)
```
And frequently our `git lfs pull` will fail with the following error:
```
trace git-lfs: HTTP: 403


< HTTP/1.1 403 Forbidden
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Content-Security-Policy: default-src 'none'
< Content-Type: application/json; charset=utf-8
< Date: Thu, 06 Apr 2017 23:03:02 GMT
< Server: GitHub.com
< Status: 403 Forbidden
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Github-Media-Type: unknown
< X-Github-Request-Id: BA25:BD36:5B357A9:9463EF9:58E6C926
< X-Ratelimit-Limit: 100
< X-Ratelimit-Remaining: 0
< X-Ratelimit-Reset: 1491519793
< X-Xss-Protection: 1; mode=block
< 
trace git-lfs: HTTP: {"message":"API rate limit exceeded for 172.16.49.14. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

And none of the  git lfs files pull down.
For information here are the git and git lfs versions:
```
git-lfs/2.0.2 (GitHub; darwin amd64; go 1.8)
git version 2.10.0
```

When I look from my home machine (not a mac incidentally) my `git lfs env` reports `auth=basic` for the Endpoint.
```
Endpoint=https://github.com/PlutoVR/core.git/info/lfs (auth=basic)
```

This makes me wonder whether or not the instructions to use the file stored credentials are correct? Github.com talks about using [the `osxkeychain` credential helper][2] but they don't provide information on how to store this into the keychain programmatically so that it could be used by an automated build system like travis-ci.

[1]: https://github.com/travis-ci/travis-ci/issues/3634
[2]: https://help.github.com/articles/caching-your-github-password-in-git/#platform-mac

**Comment by scott-plutovr** [comment]
As an additional test I added the following directly before the git remote set-url in the above mentioned install shell script,

git credential-osxkeychain "store --file=.git/credentials" 

To no avail. The Endpoint still shows (auth=none) in the output of git lfs env

**Comment by BanzaiMan** [comment]
Have you set the `GH_TOKEN` value correctly?

**Comment by scott-plutovr** [comment]
I'm not sure I understand the difference between setting the GH_TOKEN value and setting it "correctly"?

We are setting GH_TOKEN in our .travis.yml and see the following earlier in the build output (from the raw log):
[33;1mSetting environment variables from .travis.yml[0m

$ export GH_TOKEN=[secure]

**Comment by BanzaiMan** [comment]
The `export` statement shows that it is set to something. Is it not clear from the output if it is correct.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by scott-plutovr** [comment]
Sure. 
[44140107.zip](https://github.com/travis-ci/travis-ci/files/926356/44140107.zip)

**Comment by BanzaiMan** [comment]
Could you try running a debug build, and confirm that the value for `$GH_TOKEN` is set correctly?

Looking at the data about this build, I decude that you have:

```yaml
env:
  - GH_TOKEN=[secure]
```

In other words, `$GH_TOKEN` value is set to the literal `[secure]`, which is probably not the correct value as a GitHub token.

**Comment by scott-plutovr** [comment]
Ah. I had assumed that that was sanitized to "[secure]" when it was printed to the log. I didn't setup the travis encryption of that environment variable so I'll double check with the developer who did.

**Comment by scott-plutovr** [comment]
How do I run a "debug build"? I just installed the travis ruby gem but it doesn't look like it has a 'decrypt' option.

**Comment by BanzaiMan** [comment]
On the private build log page, in the upper right corner, there is a button to initiate it.

![build__1641_-_travis-ci_travis-gatekeeper_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/25108042/0941a602-23a1-11e7-86fc-3efc6cef1edb.png)

**Comment by scott-plutovr** [comment]
When I run a debug build the output to the log related to setting this environment variable looks the same,

Setting environment variables from .travis.yml
$ export GH_TOKEN=[secure]

but if I ssh over to that host and echo the environment variable it looks like a valid token.

Also, as an additional test I modified our script where we install git-lfs and set the credential.helper stuff to also include,

git config lfs.https://github.com/PlutoVR/${REPO_NAME}.git/info/lfs.access basic

and now I see the expected (auth=basic) for that Endpoint in the git lfs env output:
Endpoint=https://github.com/PlutoVR/core.git/info/lfs (auth=basic)

**Comment by BanzaiMan** [comment]
This is strange. Can you paste the content of `.travis.yml`, or, if you prefer, send it to support@travis-ci.com? Thanks.

**Comment by scott-plutovr** [comment]
I just emailed it.

**Comment by scott-plutovr** [comment]
Looking at a verbose log for our ```git lfs pull``` with the above-mentioned config change,

``` git config lfs.<url>/info/lfs.access basic```

we see "X-Ratelimit-Limit: 3000" in one of the HTTP headers so I think that was required in order for requests to be authenticated.
