### ISSUE TITLE
Specifying node js version doesn't work

### ISSUE THREAD

**Issue by leolorenzoluis** [travis-ci/travis-ci#7597]
I have a travis yml with the following:

```
language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003177

cache:
  directories:
    - node_modules
    - $HOME/.pub-cache
before_script:
  - chmod a+x ./build.sh
  
node_js:
  - "7"
script:
  - ./build.sh --quiet verify
```

But whenever travis builds, the log still says it's using 4.x!

```
npm ERR! argv "/home/travis/.nvm/versions/node/v4.1.2/bin/node" "/home/travis/.nvm/versions/node/v4.1.2/bin/npm"
```

Why am I missing/error?

**Comment by BanzaiMan** [comment]
`node_js` key is effective for builds with `language: node_js`. Since you are using `language: csharp`, you are responsible for setting up your Node.js runtime with `nvm`z
