### ISSUE TITLE
cannot add encrypted var to com project

### ISSUE THREAD

**Issue by yilinwei** [travis-ci/travis-ci#7599]
Hi,

I'm following the guide [here](https://docs.travis-ci.com/user/environment-variables/) for encrypting variables in the .travis.yml for the enterprise travis servers.

The encrypt command is adding something on the end of the travis file, but it's not accessible within the build and the web UI shows the `global_env` as `null`.

I'm explicitly adding encrypting using the `-r` option.

**Comment by BanzaiMan** [comment]
Sorry to hear about the problem you are having. For Travis Enterprise support issues, please send us email at enterprise@travis-ci.com with details.

I'm closing this public issue in the mean time.

Thank you!
