### ISSUE TITLE
Private organization repo is not visible under Travis account

### ISSUE THREAD

**Issue by yambay** [travis-ci/travis-ci#7601]
There is private organization repository and I've got admin access to it.
I know (and see under "Authorized applications" in my GitHub profile), that organizational access was not approved.

Now I can't import that private repo in travis-ci.com:
![travis_problem](https://cloud.githubusercontent.com/assets/11650903/24919360/b04a3904-1ee3-11e7-9776-4d73e9d4429c.png)

Two questions

1. Is it really necessary to authorize Travis for the whole organization?
2. Is it somehow possible to grant access only to selected repository?

Anybody there who can help me?

**Comment by BanzaiMan** [comment]
Is this still a problem, after you've granted Travis Pro access to your private repositories?

**Comment by BanzaiMan** [comment]
Closing this for now. If you require further assistance, please send us email at support@travis-ci.com.

**Comment by mohamedebrahim96** [comment]
I have GitHub education account am I (pro-Travis)?
@BanzaiMan

**Comment by BanzaiMan** [comment]
@mohamedebrahim96 Are you having problems? We are moving to GitHub Apps, and the settings page has changed, so if you are having problems, please contact support.

**Comment by mohamedebrahim96** [comment]
i don't have problems.

actually am asking cuz i don't see the private repo :cry::cry::cry:
