### ISSUE TITLE
Waiting for status to be reported

### ISSUE THREAD

**Issue by LeonFedotov** [travis-ci/travis-ci#7602]
Hi our prs are stuck with some phantom build i cant locate, i saw some similar issues here would love some assistance.
273 is a nop pr it just doesn't start the test at all.
relevant pr's:
https://github.com/Midburn/Spark/pull/273
https://github.com/Midburn/Spark/pull/272
thanks,

**Comment by LeonFedotov** [comment]
@BanzaiMan hey can you take a look? were really stuck here :(

**Comment by BanzaiMan** [comment]
Sorry for the delay.

I looked at these PRs, but I have not been able to reason why the builds are not running. As you can see in https://travis-ci.org/Midburn/Spark/requests, we are not getting notifications from GitHub about the recent commits of these PRs.
1. https://github.com/Midburn/Spark/pull/272 says it has 83 commits, but GitHub API returns only 30.
```sh-session
$ curl -s https://api.github.com/repos/Midburn/Spark/pulls/272/commits | jq 'length'
30
```
I don't know why this is the case. I suspect something is wrong with GitHub data.

**Comment by noamr** [comment]
Hi @BanzaiMan, thanks for looking at this. Github returns by default 30 commits for public repos (https://developer.github.com/guides/traversing-with-pagination/). To support lists with more commits, you need to use per_page (https://api.github.com/repos/Midburn/Spark/pulls/272/commits?per_page=100 returns all the commits) or use pagination (?page=2, page=3).

**Comment by BanzaiMan** [comment]
@noamr Ah. OK. Thanks. I guess the problem lies elsewhere.

**Comment by LeonFedotov** [comment]
@BanzaiMan any ideas? also when i go and try to "test" integration on the github end, it just says "Okay, the test payload is on its way." and nothing happens - is there something you can "flush" or force read on travis end?

**Comment by BanzaiMan** [comment]
When did you test the hook (in UTC)?

**Comment by LeonFedotov** [comment]
@OriHoch can you say when did you test it?

**Comment by OriHoch** [comment]
did it now

![image](https://cloud.githubusercontent.com/assets/1198854/25048104/41b8b710-2143-11e7-9caa-1ad3800de2b4.png)

**Comment by BanzaiMan** [comment]
Hmm. Strange.

Could you try closing and reopening these PRs?

**Comment by LeonFedotov** [comment]
@BanzaiMan tried that as-well :(

**Comment by LeonFedotov** [comment]
also tried re-opening new prs, and disabling travis and re-enabling it again to no avail

**Comment by BanzaiMan** [comment]
So, the build requests which should have been initiated by the GitHub payload has not been seen after this one: https://travis-ci.org/Midburn/Spark/builds/220577510

There are two subsequent build requests in the requests page, but they are both API requests.

**Comment by OriHoch** [comment]
@BanzaiMan that's right - I did some API requests which worked

it looks like travis is not getting notified from github

is it possible to manually connect the github webhook to travis API?

**Comment by binji** [comment]
FYI: the WebAssembly repos seem to be having the same issue, see for example https://github.com/WebAssembly/wabt/pull/400 which isn't triggering a Travis build. In fact, none of the commits have been triggering for the past 4 days.

But I think this must be on GitHub's end, since we also have an appveyor build and it hasn't been triggered either.

**Comment by BanzaiMan** [comment]
Has anyone gotten in touch with GitHub support to track this down further?

I know that some pushes do not fire notifications (e.g., when there are more than 3 new tags are pushed), but I do not know of any condition that may apply here (especially with the test payload).

**Comment by BanzaiMan** [comment]
Could you also confirm that [Travis CI](https://github.com/settings/connections/applications/f244293c729d5066cf27) (for .org) and [Travis Pro](https://github.com/settings/connections/applications/88c5b97de2dbfc50f3ac) (for .com) have been granted access to the repositories?

**Comment by OriHoch** [comment]
@BanzaiMan I'll try to get in touch with GitHub

regarding confirming that both Travis CI and Pro are granted access - 
the repository I have problem with is public, so I can only integrate with Travis CI

My personal profile have authorization on both Travis CI and Pro (e.g. I can login to both)

**Comment by OriHoch** [comment]
thanks everyone, it was a silly problem (as always)

the repository is part of an organization on GitHub which was downgraded from paid to free
there were some remaining private repositories which had to be removed which is why GitHub blocked all webhooks..

Sorry for the trouble and thanks again :1st_place_medal:

**Comment by binji** [comment]
Yes, we were able to resolve by communicating with GH support directly. I don't know the specifics, but yes, it had to do with GH locking billing on the organization which disables webhooks. It probably would be nicer if this was communicated more directly, but that's not really your issue! :-)

**Comment by BanzaiMan** [comment]
@binji Thank you for the information.

I think we can close this now. :-)
