### ISSUE TITLE
Dart project not building

### ISSUE THREAD

**Issue by sanmadjack** [travis-ci/travis-ci#7603]
I've got a project at 

https://github.com/dartalog/dartalog/tree/angular

I just added it to Travis CI, and added the travis config. It seems to run fine except it does not attempt to actually build the project. I checked other projects on github that use travis and saw in their CI logs that they had run pub build web, but it's not running for mine. I checked their travis configs and didn't see anything related to build, am I missing something?

**Comment by BanzaiMan** [comment]
I see one build https://travis-ci.org/dartalog/dartalog/builds/221036069 from 2 hours ago.

**Comment by sanmadjack** [comment]
If you look at the log it didn't actually run the "pub build web" command. Check this build log:

https://travis-ci.org/dart-lang/dart-pad/builds/121949120

There is a [build] section in it that shows it running "pub build web", which is the dart build command for building a web app. The config checked into git for that commit doesn't look to contain anything that tells it to use the build command.

**Comment by BanzaiMan** [comment]
The [`dart-pad` configuration](https://github.com/dart-lang/dart-pad/blob/d904b780c36d5dc9d8485538ccab60c65112984b/.travis.yml) is completely different. So the build execution is naturally different. I'm guessing that [`dart tool/grind.dart buildbot`](https://github.com/dart-lang/dart-pad/blob/d904b780c36d5dc9d8485538ccab60c65112984b/tool/travis.sh#L15) is running `pub build web`.

`language: dart` does not provide any default `script` value, so nothing happens for you.

**Comment by sanmadjack** [comment]
You're right, I can't believe I missed that. Thank you for looking at this and helping me!
