### ISSUE TITLE
"No builds for this repository" despite .travis.yml and commit

### ISSUE THREAD

**Issue by alexshapran-as** [travis-ci/travis-ci#7609]
Hi,
I've created a public Github repository at https://github.com/alexshapran-as/Lab5-test and added a .travis.yml in it.
But Travis doesn't detect any commit on the repo and shows "No builds for this repository" : https://travis-ci.org/alexshapran-as/Lab5-test

Thanks.

**Comment by BanzaiMan** [comment]
I see builds and requests. https://travis-ci.org/alexshapran-as/Lab5-test/requests

According to our records, we have created the repository at 2017-04-12 19:18:33 UTC. Of [the 10 commits](https://github.com/alexshapran-as/Lab5-test/commits/master), the last one that did not trigger was https://github.com/alexshapran-as/Lab5-test/commit/7daaca70c9427109da9362173dea98b784d95813, which was committed at [2017-04-12T19:18:23Z](https://api.github.com/repos/alexshapran-as/Lab5-test/commits/7daaca70c9427109da9362173dea98b784d95813).

I believe things are working correctly.
