### ISSUE TITLE
Limited access to a temporary shell after failure

### ISSUE THREAD

**Issue by brianmhunt** [travis-ci/travis-ci#761]
Sometimes after a build fails it would be exceedingly helpful to have a few moments of time in a shell to figure out what happened. Right now I find myself regularly submitting my rather hefty build script, only so I can try out variations or glean information about something that may have gone wrong.

I'm sure there are easier ways to go about debugging, but I don't know them offhand. So an alternative may be to offer access to a shell after the tests fail.

I would think that a sensible way to do this, from a user interface perspective, would be if during a build one could click a button that said "Run shell on failure", and in doing so one would have access to e.g. 2 minutes of shell commands after a failure - before the virtual machine is reaped.

Just some thoughts!

**Comment by nysthee** [comment]
:ok_hand:

**Comment by BanzaiMan** [comment]
It's on our roadmap. We'll update this issue when we have something to share.

**Comment by BanzaiMan** [comment]
Debug feature is live (and it has been for a while), and the documentation is here: https://docs.travis-ci.com/user/running-build-in-debug-mode/.
