### ISSUE TITLE
Can i specify what version of MongoDB to install 

### ISSUE THREAD

**Issue by rrmerugu** [travis-ci/travis-ci#7614]
Example: 

The blow code installs MongoDB shell version: 2.4.14
```
services:
  - mongodb
```

Is there a way now or in near future to tell what version of service do I want to install ?

**Comment by BanzaiMan** [comment]
This is not possible with the MongoDB service. If you want to use a different version of Mongo, you need to do so manually. See https://github.com/mongodb/pymodm/blob/master/.travis.yml for an example.
