### ISSUE TITLE
Dotnet core install on osx sometimes fails

### ISSUE THREAD

**Issue by treziac** [travis-ci/travis-ci#7615]
@joshua-anderson @akoeplinger @nterry

When installing dotnet core on osx (in the `Installing .NET Core` section), sometimes the curl fail with this message :

```
$ curl -o "/tmp/dotnet.pkg" -fL https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.1/dotnet-dev-osx-x64.1.0.1.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 82  120M   82  100M    0     0  4027k      0  0:00:30  0:00:25  0:00:05 5025kcurl: (56) SSLRead() return error -36
The command "curl -o "/tmp/dotnet.pkg" -fL https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.1/dotnet-dev-osx-x64.1.0.1.pkg" failed and exited with 56 during .
```
wit he following config

```
{
  "language": "csharp",
  "install": [
    "dotnet restore"
  ],
  "script": [
    "make build",
    "make test"
  ],
  "global_env": "CONFIGURATION=Release",
  "dotnet": "1.0.1",
  "env": "DOTNETCORE=1",
  "mono": "none",
  "os": "osx",
  "osx_image": "xcode7.3"
}
```

The curl fail at a random time, for example
```
42  120M   42 51.3M    0     0  2580k      0  0:00:47  0:00:20  0:00:27 1304kcurl: (56) SSLRead() return error -36
91  120M   91  110M    0     0  5102k      0  0:00:24  0:00:22  0:00:02 3016kcurl: (56) SSLRead() return error -36
82  120M   82  100M    0     0  4027k      0  0:00:30  0:00:25  0:00:05 5025kcurl: (56) SSLRead() return error -36
```
some working with the same conf

```
100  120M  100  120M    0     0  12.0M      0  0:00:09  0:00:09 --:--:-- 12.3M
100  120M  100  120M    0     0  2002k      0  0:01:01  0:01:01 --:--:-- 1743k
100  120M  100  120M    0     0  12.0M      0  0:00:09  0:00:09 --:--:-- 12.3M
100  120M  100  120M    0     0  4402k      0  0:00:28  0:00:28 --:--:-- 2989k
```

On aspnet, they retry multiple times (curl --fail --retry 3 --retry-max-time 120 -sSL) and wget if this fail
https://github.com/aspnet/KoreBuild/blob/dev/build/dotnet/dotnet-install.sh#L525

instead of this 
https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/csharp.rb#L109

**Comment by akoeplinger** [comment]
This is tracked at https://github.com/travis-ci/travis-ci/issues/7502. Adding the retry to curl sounds like a good idea!

**Comment by treziac** [comment]
Didnt see it, #7502 is for mono though and this one for .Net core,  but the issues are the same with curl. Feel free to close in favour for the other one :)

**Comment by akoeplinger** [comment]
Yeah the underlying issue seems to be with OSX + curl + Azure CDN.

> Feel free to close in favour for the other one

I don't have issue management permission on this repo so I'd appreciate if you could do it :)
