### ISSUE TITLE
"cancel build" abruptly halts build, provides no cleanup

### ISSUE THREAD

**Issue by ericmjonas** [travis-ci/travis-ci#7617]
The "cancel build" buttons on the web interface simply abort the build, and thus don't enable cleanup . For builds that acquire and release global resources (like launch and terminate servers on EC2) this can leave resources "on". It would be great if there was a `after_cancel` region of the `yaml` file to deal with this. 

This was prompted by the following support interaction : https://twitter.com/travisci/status/852953026205765633

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate of #4221.
