### ISSUE TITLE
"No output has been received in the last 10m0s..." after "Done"

### ISSUE THREAD

**Issue by finom** [travis-ci/travis-ci#7618]
[This build](https://travis-ci.org/matreshkajs/matreshka.io) always ends with "No output has been received in the last 10m0s..." message if run successfully and even if it's really broken. How can I fix it? [There is my config](https://github.com/matreshkajs/matreshka.io/blob/master/.travis.yml).

**Comment by BanzaiMan** [comment]
I think this is a duplicate of #6861.
