### ISSUE TITLE
Cannot use environment variable to set deploy.prerelease in .travis.yml

### ISSUE THREAD

**Issue by Librazy** [travis-ci/travis-ci#7619]
I tried to automate my github prerelease/release deploy. I wish I could ship a release when my commit message start with some magic chars. So I wrote some bash script in before_deploy to set up a environment variable GHTHUB_DEPLOY_PRERELEASE, and set deploy.prerelease to 
```
  prerelease: $GHTHUB_DEPLOY_PRERELEASE
```
everything works fine when preparing deploy.
But it says 
```
For 'properties/prerelease', "false" is not a boolean. // See: https://developer.github.com/v3
```
when deploying application.

full log:
https://travis-ci.org/Librazy/TooltipFilter/builds/222308618

.travis.yml:
https://github.com/Librazy/TooltipFilter/blob/d767b946acd87a701e886c9d282032558e001917/.travis.yml

……Seems that environment variables are always strings?

I don't know whether it is a travis-ci issue or a dpl issue, so i opened it twice. https://github.com/travis-ci/dpl/issues/613

**Comment by BanzaiMan** [comment]
I don't see this environment variable documented.

**Comment by Librazy** [comment]
this is my custom environment variable set in pre-deploy an its value is `true` or `false`

**Comment by BanzaiMan** [comment]
Ah, I see the problem now. I'm closing this, however, in favor of https://github.com/travis-ci/dpl/issues/613.
