### ISSUE TITLE
Build keeps restarting in endless loop even when repository is disabled and more...

### ISSUE THREAD

**Issue by REAANDREW** [travis-ci/travis-ci#7620]
[https://travis-ci.org/REAANDREW/fake-winter-fuel-benefit-service](https://travis-ci.org/REAANDREW/fake-winter-fuel-benefit-service)

My build keeps restarting in an endless loop even after I have disabled Build branch updates & Build pull request updates.  I have also disabled the repository in the settings and even this does not stop the loop.  Finally, hitting the 'Cancel Build' button cancels the build but another one starts immediately after.

- Lots of builds have started in parallel and when a build finished a new build begins.
- When I log out and back in again (after disabling the repository) I do not see it in my list BUT I can search for it and it is still active and in a build loop.
- Disabling the integration inside of Github does not work either as I thought it may be a github web hook repeatedly firing.
- When I go into build history the items are not sorted in build order as it goes from build 254 and the next one up is 285.
- When I cancel a build in the build history [https://travis-ci.org/REAANDREW/fake-winter-fuel-benefit-service/builds](https://travis-ci.org/REAANDREW/fake-winter-fuel-benefit-service/builds) it constantly restarts the same build.

**Comment by REAANDREW** [comment]
Looking at the build history

https://travis-ci.org/REAANDREW/fake-winter-fuel-benefit-service/builds

Lots of builds have started in parallel and when a build finished a new build begins.

**Comment by REAANDREW** [comment]
It appears to be because of the GHR project which uploads releases to Github.

https://github.com/tcnksm/ghr/issues/45

**Comment by BanzaiMan** [comment]
What does this `--delete` do? Is it deleting an old release and creating a new tag? If that new tag (presumably with the same name) is getting pushed to GitHub, then we will run a new build for it.

**Comment by REAANDREW** [comment]
`--delete` removes the tag & release if it already exists and recreates.  I found this was causing the issue.  My fix was to specify inside the .travis.yml file the branches which I wanted the build to trigger on which did not include the name or pattern of tags.  I am going to close this issue as it appears to be configuration related on my part, not TravisCI nor GHR.

**Comment by REAANDREW** [comment]
Sorry didn't see your comment.  Yes, spot on! :-)  that was the issue, thanks.  I specified the branches now in the .travis.yml file which I want the build to trigger on.
