### ISSUE TITLE
Can not login travis-ci.com

### ISSUE THREAD

**Issue by ZAntony** [travis-ci/travis-ci#7623]
Hi, I still can't access travis-ci.com, when I accessed using firefox, see an error on the console: "**the Content Security Policy: instruct 'the frame-src Has had been deprecated. Both Please use the instructions' child-src' the replace.,** "I looked at your web page/header" Content ws-security - Policy ", and found there are contains **frame-src**, but I'm through [content-security-policy.com](https://content-security-policy.com/) view to **frame-src** is not recommended, and replaced with **child-src**, don't know whether this problem, but it does affect me, and my browser display.

**Comment by BanzaiMan** [comment]
Hello. I believe this is a duplicate of #7612. If you would like to add this information to that ticket, you are welcome to do so.
