### ISSUE TITLE
No build if multiple tags are pushed at once

### ISSUE THREAD

**Issue by phil-opp** [travis-ci/travis-ci#7626]
If I do a `git push origin tag_1 tag_2 tag_3 tag_4`, no travis builds are created for these tags and the tags don't appear on the branches page. The same is true if I update multiple tags at once using `--force`. It works fine if I execute multiple `git push origin tag_X` commands instead.

**Comment by BanzaiMan** [comment]
https://developer.github.com/v3/activity/events/types/#createevent

As documented, GitHub does not fire notifications if you push more than 3 tags.
