### ISSUE TITLE
Support for Xcode >8.3

### ISSUE THREAD

**Issue by Boerworz** [travis-ci/travis-ci#7629]
Hey everyone!

According to the [release notes for Xcode 8.3.1](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-SW848), Xcode 8.3 will soon be deprecated and archives built using it won't be accepted by the App Store. It would be great if you could add support for Xcode 8.3.1 (or 8.3.2 which was released two days ago) as soon as possible :)

**Comment by emdantrim** [comment]
8.3.2 is now live! :) ✨
