### ISSUE TITLE
Feature Request: A Way To Cancel Travis Tests

### ISSUE THREAD

**Issue by chriscct7** [travis-ci/travis-ci#763]
Similar to #762, lets examine the following use case:
Lets say I test a commit on 12 environments configurations.
I wish to have a button, that via the Travis-ci.org website, as either the Repo owner OR the commit author can push to cancel all tests for the commit, or cancel all tests for selected (1..*) environment configurations. 

Two uses here:
1. Lets say I make an app, where if one environment fails, I don't care about the rest. Maybe I've made a syntax mistake, so I know the rest will fail. Who knows? But lets say that of my 12 configs, the first one fails. I should be able to cancel the rest of the tests. This would reduce Travis's serverload, as well as allow other queued items to go.
2. Lets say that I accidently did a push, or don't want to test that commit, but I forgot to add my #762 header. There should be a button that I can push to cancel.

**Comment by buley** [comment]
This bookmarklet should hack it when viewing the build queue page:

> javascript:$(".icon.push.created").map(function(e,n){setTimeout(function(){var e=window.open($(n).parent().attr("href"));e.onload=function(){setTimeout(function(){e.jQuery(".button-circle-cancel").click(),setTimeout(function(){e.close()},1e4)},3e3)}},3e3*e)});
