### ISSUE TITLE
Broken link in "This job ran on our Precise" warning

### ISSUE THREAD

**Issue by hugovk** [travis-ci/travis-ci#7630]
For example: https://travis-ci.org/hugovk/test/jobs/219415220

![image](https://cloud.githubusercontent.com/assets/1324225/25231835/08959928-25e2-11e7-8fa3-8bb927391161.png)

>  This job ran on our Precise, `sudo: required` environment which will be updated on May 3rd. You can check [more details about this in our blog](Read about Precise EOL).

The link href is `Read about Precise EOL`

It should be: https://blog.travis-ci.com/2017-04-17-precise-EOL

**Comment by BanzaiMan** [comment]
Thank you for the report. This was fixed by https://github.com/travis-ci/travis-web/commit/b40c57f44d15ead941c62e7d2dd35a3fab810bd2.
