### ISSUE TITLE
PR not building

### ISSUE THREAD

**Issue by jasonkarns** [travis-ci/travis-ci#7631]
Github repo in question: https://github.com/bjeanes/optparse-subcommand

This repo is for an old gem that hasn't had much activity for a long while (~5 years until the last month). Travis was already configured for this repo. 
 - I [opened a PR](https://github.com/bjeanes/optparse-subcommand/pull/5) nine days ago.
 - Travis did not kick off a build for the PR https://github.com/bjeanes/optparse-subcommand/pull/5#issuecomment-293263207
 - repo owner then updated the apikey for the travis webhook https://github.com/bjeanes/optparse-subcommand/pull/5#issuecomment-293273960
 - other PRs have been opened and successfully built (now that api token was updated/fixed)
 - original PR branch has been rebased and new commits pushed, but travis is not recognizing them and not triggering builds https://github.com/bjeanes/optparse-subcommand/pull/5#issuecomment-295769640

**Comment by BanzaiMan** [comment]
This is strange. Could you try closing and reopening the PR?

**Comment by jasonkarns** [comment]
that did it: 
![image](https://cloud.githubusercontent.com/assets/119972/25242234/ecd60170-25c6-11e7-9980-2a4b3481184e.png)

**Comment by BanzaiMan** [comment]
Yay! Thank you for the update. 🎉  I'm closing this now.
