### ISSUE TITLE
dart.rb hides issues when running `dartfmt`

### ISSUE THREAD

**Issue by kevmoo** [travis-ci/travis-ci#7632]
See https://github.com/travis-ci/travis-build/blob/b1ff1c6237164842ec4eddd420725279a98757f4/lib/travis/build/script/dart.rb#L238

```ruby
sh.cmd 'unformatted=`dartfmt -n .`'
```

There's an annoying case where this will fail silently – because pub is trying to run `dartfmt` from a package? Not sure... See https://travis-ci.org/dart-lang/angular_test/jobs/224044980#L226

```
Package "dart_style" is not an immediate dependency.
Cannot run executables in transitive dependencies.
```

This actually fails with code 65.

Anyway, it'd be better to capture the output into a var..maybe? And allow failures to actually fail the task

**Comment by kevmoo** [comment]
CC @a14n @nex3 @BanzaiMan

**Comment by BanzaiMan** [comment]
Hmmm. I'm not familiar with Dart tooling. I am happy to work with @a14n or @nex3 to test (any future) PR in staging, however.

**Comment by kevmoo** [comment]
@BanzaiMan does `sh.cmd` return the stdout of the process in question?

Does it throw if the command fails?

We might be able to fix it up easily in that cose...

**Comment by kevmoo** [comment]
...nevermind. I just realized this code is generated the shell code. 🙄
