### ISSUE TITLE
Debug builds time out after 10 minutes

### ISSUE THREAD

**Issue by danepowell** [travis-ci/travis-ci#7635]
When you activate debug mode on a build, it says it will be active for 30 minutes, but in practice I get kicked out of the SSH session after 10 minutes, which isn't long enough to get far enough into a long-running test to debug an error. Is there any way to extend the debug session?

**Comment by BanzaiMan** [comment]
This is strange. When a debug session starts, it should also start a process that writes dots to STDOUT, which prevents the job from getting killed. Do you know see the dots?

**Comment by danepowell** [comment]
Yeah actually I'm realizing it must be something else causing the session to end, because it's not always exactly at 10 minutes.

What happens is that I ssh in and start a long-running build script, and the moment that script exits the SSH session terminates and the debug build finishes.

We aren't issuing any sort of exit command, do you know why a long-running script in a debug ssh session would cause it to terminate?

**Comment by BanzaiMan** [comment]
> start a long-running build script

What sort of script is this? For example, if this script `fork`s and `exec`s, then the end of the script is the end of the shell process. You could also prevent the termination of the session by creating a new window (`ctrl-b :new-window`) or splitting the existing window (`ctrl-b :split-window -v`), while your script runs in another window/pane.

**Comment by danepowell** [comment]
Ah yes it does spawn processes for behavioral testing, that would make sense. We'll document this with our project. Thanks!
