### ISSUE TITLE
`curl: (56) SSLRead() return error -36` plagues many Nix-based builds

### ISSUE THREAD

**Issue by deepfire** [travis-ci/travis-ci#7636]
Case in point: https://travis-ci.org/NixOS/nixpkgs/jobs/224107885

For some organizational Nix-on-Travis users this issue can be a showstopper, as it can block 80+% of builds for hours.

cc @domenkozar, @garbas and @matthewbauer

This seems related:
1. https://github.com/travis-ci/travis-ci/issues/7502, esp.https://github.com/travis-ci/travis-ci/issues/7502#issuecomment-289164928
2. https://github.com/travis-ci/travis-ci/issues/7615

Suggestions that came up were:
1. to use `wget` instead of `curl`: https://github.com/travis-ci/travis-ci/issues/7502#issuecomment-294841422
2. increase timeouts for the latter: descr. at https://github.com/travis-ci/travis-ci/issues/7615

**Comment by matthewbauer** [comment]
I think this is the same issue as NixOS/nix#1303. I can't figure out yet if it's Travis org nixos.org that is doing this. One useful piece of information though: it only seems to happen on MacOS Travis builds.

**Comment by jmitchell** [comment]
Over the past day most of the pull request builds in [this repo](https://travis-ci.org/input-output-hk/daedalus/pull_requests) have been failing with this error on macOS. Are there any hints in the nixos.org server logs?

https://www.traviscistatus.com/ currently returns a 500 error, but about half an hour ago it reported everything was operational.

**Comment by matthewbauer** [comment]
So we can definitely switch to wget for the install script, but Nix uses curl all over the place. I wonder if it's hitting this as well when it tries to download from the binary cache?

**Comment by jmitchell** [comment]
> most of the pull request builds in this repo have been failing with this error

After a more detailed analysis it's clear this isn't true, but nonetheless the error was surprisingly frequent. Over the past day ~20% of the failures can be attributed to this, and as much as ~55% to potential networking problems. Other networking-related scenarios include Travis failing to fetch the repo and failing to fetch from an S3 bucket.

> I wonder if it's hitting this as well when it tries to download from the binary cache?

I don't recall seeing this particular error while downloading from the binary cache, but I can't categorically rule out the possibility. As a start maybe it's worth switching the installer to `wget` or, failing that, adding `--retry` to the `curl` calls.

**Comment by domenkozar** [comment]
Workaround fix in https://github.com/travis-ci/travis-build/pull/1025

**Comment by BanzaiMan** [comment]
The PR has been merged and deployed. I'm closing this.
