### ISSUE TITLE
docker pull quay.io/travisci/ci-python fails

### ISSUE THREAD

**Issue by alistairbntl** [travis-ci/travis-ci#7637]
First, I hope this is correct platform to post this issue.  If it is not, please let me know the best place to get support.

I'm trying to pull the `ci-python` docker image on `quay.io/travisci/` with the command `docker pull quay.io/travisci/ci-python`.  This generates the following three lines of output:

```
- Using default tag: latest
- Pulling repository quay.io/travisci/ci-python
- Tag latest not found in repository quay.io/travisci/ci-python
```

I expected this command to download the docker image.

When I tried pulling `quoy.io/travisci/travis-ruby`, the image downloaded properly, so I think something is wrong with the `ci-python` image on `quay.io`.

Thanks in advance.

PS - I'm new to docker, so sorry if this a trivial mix up.

**Comment by BanzaiMan** [comment]
There is no image named `ci-python` on quay.io. The name you are looking for is `travis-python`. https://quay.io/repository/travisci/travis-python?tag=latest&tab=tags

This is documented here: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

**Comment by alistairbntl** [comment]
@BanzaiMan - Thank you.  

I would mention that there does appear to be an image `ci-python`.  See https://quay.io/repository/travisci/ci-python.
