### ISSUE TITLE
Missing iOS simulators in latest Xcode image

### ISSUE THREAD

**Issue by alexaubry** [travis-ci/travis-ci#7638]
In the latest Xcode 8.3.2 image, there are no simulator devices for iOS 8.1 ... 10.2, thus making it impossible to run tests on older versions of iOS (pre 10.3).

- macOS image: `osx_image: xcode8.3`

<details><summary>Available simulators</summary>

~~~
$ xcodebuild -version -sdk

[...]
== Devices ==
-- iOS 8.1 --
-- iOS 8.2 --
-- iOS 8.3 --
-- iOS 8.4 --
-- iOS 9.0 --
-- iOS 9.1 --
-- iOS 9.2 --
-- iOS 9.3 --
-- iOS 10.0 --
-- iOS 10.1 --
-- iOS 10.2 --
-- iOS 10.3 --
    iPhone 5 (900578B5-4EB3-429A-B746-21CD15A280F0) (Shutdown)
    iPhone 5s (FD1C5C0E-19DE-4E77-A5DF-DA7BE930C5DB) (Shutdown)
    iPhone 6 (DD5E88FF-1AD0-4ADD-A6F0-162759432055) (Shutdown)
    iPhone 6 Plus (3036ACC2-7793-4C93-991D-FBD3F71987FF) (Shutdown)
    iPhone 6s (01A4566E-C24F-48A8-AFBD-2612205C0E8C) (Shutdown)
    iPhone 6s Plus (0004671C-F9BB-4755-A2B6-1C2A6844401D) (Shutdown)
    iPhone 7 (2437D975-7A64-4F01-B8C9-2510D4DAF5AD) (Shutdown)
    iPhone 7 Plus (32CF67DB-D589-4143-9EB4-E534EB51877B) (Shutdown)
    iPhone SE (09AAB3B1-8423-4B8C-BC6A-1B094341C07A) (Shutdown)
    iPad Air (009C8748-E16A-4387-81C1-C8C55E5DE71E) (Shutdown)
    iPad Air 2 (F2BE0078-A556-467F-A458-588C1F94C321) (Shutdown)
    iPad Pro (9.7-inch) (927B3C76-1FF2-437D-B922-0202906750E1) (Shutdown)
    iPad Pro (12.9-inch) (10C30121-2C7C-4D15-B432-F8B2CE5FC416) (Shutdown)
~~~

</details>

**Comment by abdullahselek** [comment]
I have a similar issue my macOS image: `osx_image: xcode8.3` and I try to run on OS 9.3 iPhone 6.
But available simulators
`
{ platform:iOS Simulator, id:009C8748-E16A-4387-81C1-C8C55E5DE71E, OS:10.3, name:iPad Air }
{ platform:iOS Simulator, id:F2BE0078-A556-467F-A458-588C1F94C321, OS:10.3, name:iPad Air 2 }
{ platform:iOS Simulator, id:927B3C76-1FF2-437D-B922-0202906750E1, OS:10.3, name:iPad Pro (9.7-inch) }
{ platform:iOS Simulator, id:10C30121-2C7C-4D15-B432-F8B2CE5FC416, OS:10.3, name:iPad Pro (12.9-inch) }
{ platform:iOS Simulator, id:900578B5-4EB3-429A-B746-21CD15A280F0, OS:10.3, name:iPhone 5 }
{ platform:iOS Simulator, id:FD1C5C0E-19DE-4E77-A5DF-DA7BE930C5DB, OS:10.3, name:iPhone 5s }
{ platform:iOS Simulator, id:DD5E88FF-1AD0-4ADD-A6F0-162759432055, OS:10.3, name:iPhone 6 }
{ platform:iOS Simulator, id:3036ACC2-7793-4C93-991D-FBD3F71987FF, OS:10.3, name:iPhone 6 Plus }
{ platform:iOS Simulator, id:01A4566E-C24F-48A8-AFBD-2612205C0E8C, OS:10.3, name:iPhone 6s }
{ platform:iOS Simulator, id:0004671C-F9BB-4755-A2B6-1C2A6844401D, OS:10.3, name:iPhone 6s Plus }
{ platform:iOS Simulator, id:2437D975-7A64-4F01-B8C9-2510D4DAF5AD, OS:10.3, name:iPhone 7 }
{ platform:iOS Simulator, id:32CF67DB-D589-4143-9EB4-E534EB51877B, OS:10.3, name:iPhone 7 Plus }
{ platform:iOS Simulator, id:09AAB3B1-8423-4B8C-BC6A-1B094341C07A, OS:10.3, name:iPhone SE }
`

**Comment by alexaubry** [comment]
A temporary workaround could be to create the required simulators on the fly when setting up the build (as the older runtimes are available):

~~~
$ xcrun simctl create 'iPhone 6' \
    com.apple.CoreSimulator.SimDeviceType.iPhone-6 \
    com.apple.CoreSimulator.SimRuntime.iOS-9-3
~~~

This returns an UDID that can be used in the destination specifier.

It seems to do the trick for me...

**Comment by abdullahselek** [comment]
Thanks @alexaubry

**Comment by emdantrim** [comment]
yikes. sorry about this, folks. I'm working on a fix.

**Comment by dimazen** [comment]
Looking forward for updates!

**Comment by pcantrell** [comment]
Here’s a version of @alexaubry’s workaround (thank you!) that translates OS and devices names with dots and dashes that `xcodebuild` needs to the hyphen-separated version that `simctl create` needs: 

```yaml
osx_image: xcode8.3
env:
  - scheme='Siesta macOS' platform='OS X'
  - scheme='Siesta iOS'   platform='iOS Simulator' ios_version='10.3' ios_device='iPhone SE'
  - scheme='Siesta iOS'   platform='iOS Simulator' ios_version='9.3'  ios_device='iPhone 6'
  - scheme='Siesta iOS'   platform='iOS Simulator' ios_version='8.1'  ios_device='iPhone 4s'

before_install: |
  if [[ "$platform" == "iOS Simulator" ]]; then
    ios_simulator_udid=$(
      xcrun simctl create "Siesta testing device" \
          "com.apple.CoreSimulator.SimDeviceType.${ios_device// /-}" \
          "com.apple.CoreSimulator.SimRuntime.iOS-${ios_version//./-}"
    )
    echo "Prelaunching iOS simulator with UDID $ios_simulator_udid"
    open -a "simulator" --args -CurrentDeviceUDID $ios_simulator_udid
  fi

...

  if [[ "$platform" == "iOS Simulator" ]]; then
    platform="$platform,OS=$ios_version,name=$ios_device"
  fi
  travis_retry xcodebuild test \
      -project Siesta.xcodeproj \
      -scheme "$scheme" \
      -destination "platform=$platform"
```

(You can look at Siesta’s [full Travis config](https://github.com/bustoutsolutions/siesta/blob/48dcbed38f3009118d9e37565f77fa53177d7635/.travis.yml) if you want to see that in context.)

**Comment by emdantrim** [comment]
hey there, folks. this should be fixed now.

**Comment by jessesquires** [comment]
Thanks so much @emdantrim ! 🙌  Really appreciate the hard work! 💪
