### ISSUE TITLE
Travis rejects all new commits

### ISSUE THREAD

**Issue by arijoon** [travis-ci/travis-ci#7644]
All new commits are rejected and not built with following message:

    Build type disabled via repository settings (push)

I did change the settings to only build on `.travis.yml` presence (which is present), but since then the builds are rejected. I disabled the setting and builds are still rejected

**Comment by BanzaiMan** [comment]
Which repository is this?

**Comment by arijoon** [comment]
https://github.com/arijoon/vendaire-discord-bot my only repository on travis

**Comment by BanzaiMan** [comment]
OK, so:

> I disabled the setting and builds are still rejected

When you say "disable", you mean you turned off building both Push (branch updates) and PR (pull request updates), right?

![cursor_and_settings_-_banzaiman_travis_production_test_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/25306151/aba9efb4-2755-11e7-9dde-4bffce5e50ca.png)

Try turning them back "ON" and pushing a new commit.

**Comment by arijoon** [comment]
My bad then that works. I enabled "Build Branch Updates" but not "Build pull request updates" since I assumed that one is only for pull requests and it wasn't building. Now I did them both and it is doing it like before. Apologies for false alarm.

**Comment by Borda** [comment]
@BanzaiMan I also have not tried several jobs automatically so I tried to trigger then manually but I got this message `You tried to trigger a build for Borda/pyImSegm but the request was rejected.` What does it mean, what did I do wrong?
