### ISSUE TITLE
Separate dependency install for Linux and OSX

### ISSUE THREAD

**Issue by libeclipse** [travis-ci/travis-ci#7647]
Is it possible to have separate install commands for the different operating systems?

You docs here https://docs.travis-ci.com/user/installing-dependencies/ have the before-install: option, but I don't see a way to specify different commands for both. If I specify apt-get, then OSX fails, and if I specify brew, then Linux fails.

**Comment by BanzaiMan** [comment]
Use the value of `$TRAVIS_OS_NAME` to change behavior.

```yaml
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install foo; else brew install bar; fi
```

**Comment by libeclipse** [comment]
@BanzaiMan Nice! I feel like this should be in the documentation.

**Comment by BanzaiMan** [comment]
We welcome your suggestions for improvement!

**Comment by libeclipse** [comment]
@BanzaiMan Opened a PR [here](https://github.com/travis-ci/docs-travis-ci-com/pull/1121).

**Comment by libeclipse** [comment]
This has been merged.
