### ISSUE TITLE
Can not cancel long time jobs in Travis CI

### ISSUE THREAD

**Issue by loint** [travis-ci/travis-ci#7651]
Hi guys,

I have trouble when trying to stop building jobs. 
Do you have any recommendation ?

![capture](https://cloud.githubusercontent.com/assets/5317864/25315871/b1a7b20c-2886-11e7-9905-14401d76d370.PNG)

**Comment by dquangit** [comment]
:+1: 
same issue

**Comment by BanzaiMan** [comment]
Reload the page. Most likely the job had already finished, and therefore you cannot cancel it any more.

**Comment by BanzaiMan** [comment]
Were you able to resolve this?

**Comment by loint** [comment]
Solved
