### ISSUE TITLE
xcode8.3 image doesn't contain simulator devices other than 10.3

### ISSUE THREAD

**Issue by sinoru** [travis-ci/travis-ci#7652]
So even `anounce` step, It shows simulator devices only for 10.3, no other versions.

**Comment by jshier** [comment]
Just hit this as well. What is this, the third flawed 8.3 image in a row?

**Comment by sinoru** [comment]
Previous `announce`:
![img_0001](https://cloud.githubusercontent.com/assets/1138433/25318518/584ae450-28cb-11e7-864e-29553adca345.PNG)
Current `announce`:
![img_0002](https://cloud.githubusercontent.com/assets/1138433/25318522/6abe1562-28cb-11e7-8c10-1f4016db0523.PNG)

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate of #7638.

**Comment by sinoru** [comment]
@BanzaiMan Opps, I didn't see that. Anyway thanks for looking into it.
