### ISSUE TITLE
Python3.6 libpython3.6m.so.1.0 can't be loaded

### ISSUE THREAD

**Issue by mcyprian** [travis-ci/travis-ci#7655]
Python 3.6 builds of our project started to fail with error: 
python: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory.

Complete log is [here](https://travis-ci.org/fedora-python/pyp2rpm/jobs/225192557#L143).

**Comment by BanzaiMan** [comment]
We updated Python 3.6. Remove cache and try again.

**Comment by BanzaiMan** [comment]
Or specify `python: 3.6.0`.

**Comment by mcyprian** [comment]
It is fixed after I removed cache, thanks
