### ISSUE TITLE
Travis logs secret env variables in failing commands

### ISSUE THREAD

**Issue by dgonzalezruiz** [travis-ci/travis-ci#7660]
Hi,

I accidentally commited a wrong `push` command, with a `$GH_TOKEN` written in it. This command is executed inside a bash script, which is called in the script section of the travis execution. 
When the worker tried to execute the command, it failed (as _expected_), and logged the output and the full command with the right value of the secret, previously encrypted environment variable. Is there anything I can do in order to keep this secret in the logs? (as they are public).

By now, I think I worked it around by redirecting any output from it to /dev/null, but I'd rather use something more graceful. I don't mind trying to submit a PR for this, but first I'd like to get some insights about this, and see if anyone's ever encountered this issue (and the approach he/she took)

Thanks for your time reading this, and thanks in advance in case you decide to answer!

**Comment by BanzaiMan** [comment]
Thanks for taking the time to open the issue. I'm closing this as a duplicate of #1487.
