### ISSUE TITLE
No builds for this repository despite adding .travis.yml and committing to private repo.

### ISSUE THREAD

**Issue by storrdev** [travis-ci/travis-ci#7666]
I set up my first CI using travis after following the guide for a nodejs application, and when I commit to the master branch of the repo, I am still seeing "No builds for this repository" on my travis dashboard.

I've linted my .travis.yml file and it passed. I've double checked that my mocha tests run fine by typing 'npm test'.

This repo is private and belongs to an organization that I am an administrator of.

What could be causing this issue?

Thanks for your help.

**Comment by storrdev** [comment]
fyi, the repo is located at https://github.com/Fyresite/node-zoho (although it's currently private)

**Comment by BanzaiMan** [comment]
Your build requests are rejected, because the org has run out of trial builds, and there is no active subscription.

I've added 75 more trial builds for the organization for now.

Thanks.

**Comment by BanzaiMan** [comment]
You'd need to push new commits to trigger future builds.

**Comment by storrdev** [comment]
Thanks for the help!
