### ISSUE TITLE
No error log

### ISSUE THREAD

**Issue by jeantimex** [travis-ci/travis-ci#7667]
Hi, I don't see any error log in my travis build: https://travis-ci.org/jeantimex/react-webapp-boilerplate

Can someone help me take a look? Thanks!

**Comment by Vdragon** [comment]
You should check out the service status first: [Travis CI Status](https://www.traviscistatus.com/)

Earlier there's a maintenance on the log system so the logs aren't available.

**Comment by BanzaiMan** [comment]
Indeed, we believe this was due to maintenance. I'm closing now.
