### ISSUE TITLE
No logs, but build success.

### ISSUE THREAD

**Issue by yanqd0** [travis-ci/travis-ci#7668]
The error page: https://travis-ci.org/yanqd0/docker-gitbook/jobs/226283854

The output after `travis report --org`:

> System
> Ruby:                     Ruby 2.1.5-p273
> Operating System:         Debian 8.7
> RubyGems:                 RubyGems 2.2.2
> 
> CLI
> Version:                  1.8.8
> Plugins:                  none
> Auto-Completion:          yes
> Last Version Check:       2017-04-27 14:31:23 +0800
> 
> Session
> API Endpoint:             https://api.travis-ci.org/
> Logged In:                as "yanqd0"
> Verify SSL:               yes
> Enterprise:               no
> 
> Endpoints
> org:                      https://api.travis-ci.org/ (access token, current)
> 
> Last Exception
> An error occurred running `travis logs --org`:
>     NoMethodError: undefined method `body' for nil:NilClass
>         from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
>         from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
>         from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
>         from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
>         from /var/lib/gems/2.1.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
>         from /usr/local/bin/travis:23:in `load'
>         from /usr/local/bin/travis:23:in `<main>'

**Comment by yanqd0** [comment]
It is similar to #7667, but success.

I guess the build procedure is OK, only the output is missing.

**Comment by akreuzer** [comment]
Same problem, here.

There was some [maintenance](https://www.traviscistatus.com/incidents/hmjdwhvw3r40) on the logging system. Maybe something went wrong there ...

**Comment by Vdragon** [comment]
[Travis CI Status \- Logs database partition maintenance for public repos](https://www.traviscistatus.com/incidents/hmjdwhvw3r40)

The logs aren't available during the maintenance, should be fine now.

**Comment by yanqd0** [comment]
Sorry, I didn't notice the [maintenance](https://www.traviscistatus.com/incidents/hmjdwhvw3r40).
