### ISSUE TITLE
Pinning to a specific version of Rust nightly gets the wrong version

### ISSUE THREAD

**Issue by polybuildr** [travis-ci/travis-ci#7670]
Hello! I tried running Travis as follows https://github.com/polybuildr/balloon-lang/blob/872472b9ad8434716ee1f60e6b13e0bc1424b346/.travis.yml giving it a specific Rust nightly (`nightly-2017-04-26`) to run on.

However, in the build (https://travis-ci.org/polybuildr/balloon-lang/jobs/226417058), the `rustc` version is `2017-04-25` (25 instead of 26). This made me suspect that Travis didn't have the most recent nightly, which seemed fair. However, I looked at a build I made before this in which the version was marked simply `nightly` -
 https://travis-ci.org/polybuildr/balloon-lang/jobs/226412921 - and this time it manages to run using nightly `2017-04-26`.

So somehow, `nightly` gets me the most recent version, but specifying the most recent version gets me a version that's a day old. :P

**Comment by BanzaiMan** [comment]
According to [this output](https://travis-ci.org/polybuildr/balloon-lang/jobs/226417058#L185), `nightly-2017-04-26` has that version string. You should ask the Rust team what's going on there.

**Comment by polybuildr** [comment]
Oops, that I did not notice. Thanks for the super quick response. :D I shall check with the Rust team and comment here soon.

**Comment by polybuildr** [comment]
Spoke to @alexcrichton on IRC, they told me that it's common for them to be out of sync. One is the publish date, one is the commit date.

Closing this issue since this is expected behaviour.

**Comment by jonhoo** [comment]
I'm a little confused. https://github.com/travis-ci/travis-ci/issues/7167 states that this feature is unsupported. Has that changed?

**Comment by polybuildr** [comment]
Hi @jonhoo. I think this feature works, assuming one of my Travis pipelines hasn't been failing for a while without me noticing. :P

Give it a shot, maybe, and if it doesn't work, discussion can continue on that issue.
