### ISSUE TITLE
Limiting running of tests

### ISSUE THREAD

**Issue by chashmeetsingh** [travis-ci/travis-ci#7673]
Currently I am developing an app which has travis configured to run tests on it. I haven't written any tests yet for the same but whenever a PR is created the tests associated with the individual pods I used run as well increasing the overall build time.

What I want to know is that is there any configuration I need to add to enable to run tests written for the app and not the ones associated with the pods.

App made in swift for iOS
Using a number of Pods

Thanks!

**Comment by BanzaiMan** [comment]
Are you talking about CocoaPods? If you don't instruct to run the tests, there will be no tests run. You can always override `script` to do so. Please review https://docs.travis-ci.com/user/languages/objective-c.

**Comment by chashmeetsingh** [comment]
Ok great! Thanks.
