### ISSUE TITLE
Cannot Re-Delete a Log after Rebuild

### ISSUE THREAD

**Issue by accursoft** [travis-ci/travis-ci#7677]
1. Delete a log.
2. Re-run the build.
3. The UI gives no option for removing the log. Attempting this with the CLI gives `Log for job 123 has already been removed`.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here? How did you delete the log in the first place?

**Comment by accursoft** [comment]
This is on Travis enterprise, so no URL I'm afraid. The log was deleted through the UI.

**Comment by BanzaiMan** [comment]
For Enterprise support, please contact us at enterprise@travis-ci.com. I'm closing this public issue in the mean time. Thanks.
