### ISSUE TITLE
Columns in new dashboard are not all aligned

### ISSUE THREAD

**Issue by alex** [travis-ci/travis-ci#7678]
![screen shot 2017-04-30 at 11 11 58 am](https://cloud.githubusercontent.com/assets/772/25565499/df15c878-2d95-11e7-9f28-6330ba27134b.png)

You can clearly see that repos which do not have the hamburger menu are rendered differently.

This is on the latest Chrome on macOS.

**Comment by lislis** [comment]
hey @alex! Thank you for reporting this! A fix is done and will be live :soon:
See the commit here https://github.com/travis-ci/travis-web/pull/1132/commits/02293bc73328cb644f94be8442ee39950944a55d

**Comment by lislis** [comment]
The fix is live now.
Please re-open if there should still be issues.
