### ISSUE TITLE
oldrel not working for R 3.3.3 for OS X builds

### ISSUE THREAD

**Issue by graemeblair** [travis-ci/travis-ci#7681]
Hi all -- R travis is not building under OS X with the oldrel release currently. The following error is repeated several times: 

> The command "eval curl -fLo /tmp/R.pkg https://cloud.r-project.org/bin/macosx/old/R-3.3.3.pkg " failed 3 times.

That file indeed does not exist. R-3.3.3.pkg is currently being stored as https://cran.r-project.org/bin/macosx/R-3.3.3.pkg

See the job output: https://travis-ci.org/DeclareDesign/fabricatr/jobs/227479172

Will this automatically resolve in a few days or is this a unexpected?

Thank you!

cc @craigcitro @hadley @jimhester

**Comment by jimhester** [comment]
This is a duplicate of https://github.com/travis-ci/travis-ci/issues/7665, I tried to get the link fixed on the CRAN side and was mostly ignored https://stat.ethz.ch/pipermail/r-sig-mac/2017-April/012331.html.

**Comment by BanzaiMan** [comment]
Thanks, @jimhester. I'm closing this as a duplicate.

**Comment by graemeblair** [comment]
Apologies! Thanks, @jimhester and @BanzaiMan
