### ISSUE TITLE
/hooks is giving a 500 error

### ISSUE THREAD

**Issue by isuruf** [travis-ci/travis-ci#7682]
Request data is
```
{'hook': {'id': 13256318, 'active': True}}
```
repo id is for `conda-forge/r-xts-feedstock`.

This call gives a 505 error with the content "Sorry, we experienced an error". This happens consistently for about 24 hours now.

**Comment by BanzaiMan** [comment]
Hi. What is the exact HTTP call you are making? Also, when is the last time (in UTC) you saw this error?

(I'll also assume that you mean 500, not 505.)

**Comment by isuruf** [comment]
Here's the python script we run.
```
url = "https://api.travis-ci.org/hooks"
headers = {'User-Agent': 'Travis/1.0', 'Content-Type': 'application/json', 'Authorization': 'token <mytoken>', 'Accept': 'application/vnd.travis-ci.2+json'}
requests.put(url, headers=headers, json={'hook': {'id': 13256318, 'active': True}})
```
Happened around 2017-05-01T08:47:25Z and 15 minutes ago (don't have the exact time). I meant 500.

I just tried again and it's now working. I'll open this if this comes up again.
