### ISSUE TITLE
New gems (dpl, bundler, etc.) cannot be installed on container-based Precise (i.e. sudo: false, dist: precise)

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-ci#7685]
We are currently receiving reports of Bundler missing on our container-based Precise image i.e. .travis.yml file with the following:

```yaml
sudo: false
dist: precise
```
The error you will see in your log is this:

```
K$ bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
/home/travis/.travis/job_stages: line 220: bundle: command not found

The command "eval bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} " failed. Retrying, 2 of 3.

/home/travis/.travis/job_stages: line 220: bundle: command not found

The command "eval bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} " failed. Retrying, 3 of 3.

/home/travis/.travis/job_stages: line 220: bundle: command not found

The command "eval bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} " failed 3 times.


K
The command "bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}" failed and exited with 127 during .
```

We are investigating and we will update this issue when we know more.

Thank you for your patience!

**Comment by cotsog** [comment]
In the meantime, you can try to route your builds on our sudo-enabled Precise infrastructure by adding the following to your .travis.yml file:

```yaml
sudo: required
dist: precise
```

**Comment by BanzaiMan** [comment]
Or, install Bundler explicitly:

```yaml
before_install:
  - gem install bundler
⋮
```

**Comment by BanzaiMan** [comment]
The issue appears to me that RVM is for some reason not installing Bundler during the Ruby runtime installation. This is supposed to happen via `~/.rvm/gemsets/global.gems`:

```sh-session
$ cat ~/.rvm/gemsets/global.gems
gem-wrappers
rubygems-bundler
bundler
rake
rvm
```

RVM is performing this step: https://travis-ci.org/cotsog/travis_ci_prod_regular/jobs/228071730#L143.

**Comment by BanzaiMan** [comment]
We are getting in touch with rubygems.org maintainers to figure out the way forward. Thank you for your patience.

**Comment by cotsog** [comment]
We've have opened a ticket with rubygems.org to gather their insights: http://help.rubygems.org/discussions/problems/26205-cannot-install-gems-on-ubuntu-precise-on-travis-ci

**Comment by EIrwin** [comment]
We are seeing similar issues as  @BanzaiMan 

```
```ERROR:  Could not find a valid gem 'dpl' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://api.rubygems.org/specs.4.8.gz)


The command "rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .```

**Comment by palewire** [comment]
I am seeing this same issue and believe that #7687 could be a long-term solution to future occurrences for many users.

**Comment by flpStrri** [comment]
Same here, 
```
ERROR:  Could not find a valid gem 'dpl' (>= 0), here is why:
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://api.rubygems.org/specs.4.8.gz)
The command "rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .
```

**Comment by nipendar** [comment]
same here, 

ERROR:  Could not find a valid gem 'dpl' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://api.rubygems.org/specs.4.8.gz)
The command "rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .

**Comment by jadczakd** [comment]
Same here.
ERROR: Could not find a valid gem 'dpl' (>= 0), here is why:
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://api.rubygems.org/specs.4.8.gz)
The command "rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl" failed and exited with 2 during

**Comment by till** [comment]
@BanzaiMan it's also missing, as in, I think if you now require everyone to install bundler, then that BC break should be documented/announced? ;)

**Comment by nipendar** [comment]
if it is failing to connect to rubygems.org how can one install bundler. I am deploying a nodejs app and don't really need to install any ruby gem

**Comment by everzet** [comment]
Not sure if it is connected, but I'm having something along these lines while building my elixir package:

<img width="1001" alt="screen shot 2017-05-02 at 21 59 21" src="https://cloud.githubusercontent.com/assets/30813/25639121/a0f9b830-2f82-11e7-8124-f064ddec4afe.png">

[everzet/text_delta](https://travis-ci.org/everzet/text_delta)

Seems related as the issues also is around SSL.

P.S.: This exact build was passing yesterday.

**Comment by BanzaiMan** [comment]
@till Yes, but the workaround is the same for now.

@everzet Maybe, maybe not. Depends on which SSL provider repo.hex.pm uses.

**Comment by everzet** [comment]
@BanzaiMan I know you're busy resolving this situation for Bundler, but when you have a free minute, can you provide instruction as to where hex.pm maintainers need to look (if they can)?

Hex.pm is the main package repo for Elixir. If it is broken and there's something owners can do about it, I'm sure they'll be happy to know.

**Comment by BanzaiMan** [comment]
@everzet I'm sorry to say, but I don't know their infrastructure enough to offer any meaningful advice. However, in the off chance they are using Fastly (the timing *seems* to indicate they just might be), point them to this issue: https://status.fastly.com/incidents/4n5jrrhh5fyh.

**Comment by everzet** [comment]
@BanzaiMan thank you, I will!

**Comment by BanzaiMan** [comment]
Gem installation should be working now. Please try restarting the previously failing build.

**Comment by BanzaiMan** [comment]
Please report the results. Thank you!

**Comment by cbracken** [comment]
Now passing for me. Thanks for fixing!

**Comment by jadczakd** [comment]
Passing for me on Development.
Checkin production now -> it started failing there ~4 hours ago.

**Comment by glennsarti** [comment]
Working for now too.  Thanks!!

**Comment by emilyaviva** [comment]
Passing for me! 😉🙆🆒

**Comment by nextekcarl** [comment]
Issue seems to be resolved without work arounds listed above now for me, too.

**Comment by yanntm** [comment]
Works now, Great fast response from travis team as usual !
BanzaiMan is da boss !

**Comment by BanzaiMan** [comment]
Thanks, everyone, for the confirmation. I am closing this now.

**Comment by BanzaiMan** [comment]
@everzet FYI: https://repo.hex.pm does indeed gets its SSL certificate from Fastly, so the issue will persist (for Precise container builds) until that issue is resolved.

```sh-session
$ curl -IL https://repo.hex.pm/builds/elixir/v1.4.1.zip
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
travis@e03c2795ac6d:~$ openssl s_client -connect repo.hex.pm:443 -tls1_2
CONNECTED(00000003)
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign CloudSSL CA - SHA256 - G3
verify error:num=20:unable to get local issuer certificate
verify return:0
⋮
```

**Comment by cotsog** [comment]
@everzet: FYI, we are tracking the Elixir issue in https://github.com/travis-ci/travis-ci/issues/7688.

**Comment by BanzaiMan** [comment]
For reference, I point out that this is a different manifestation of #7131. The issue was more visible because of the volume of the affected builds.
