### ISSUE TITLE
Unable to connect to Ruby Gems index

### ISSUE THREAD

**Issue by rbrtmrtn** [travis-ci/travis-ci#7686]
I randomly started getting this error when running my Travis builds:

```
ERROR:  Could not find a valid gem 'dpl' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://api.rubygems.org/specs.4.8.gz)
The command "rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .
Your build has been stopped.
```

Haven't changed anything about my Travis config lately.

This is the project:
https://travis-ci.org/CityOfPhiladelphia/mapboard

Thanks!

**Comment by damorton** [comment]
Same issue here https://travis-ci.org/damorton/dropwizardheroku-event-service/builds/228079963

**Comment by palewire** [comment]
I am also having this bug. It is crashing all my builds.

**Comment by yanntm** [comment]
same here, e.g. https://travis-ci.org/yanntm/ITS-Tools-Dependencies

**Comment by BanzaiMan** [comment]
Closing as a duplicate.
