### ISSUE TITLE
Elixir fails to be downloaded on container-based Precise (i.e. sudo: false, dist: precise)

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-ci#7688]
We are seeing reports saying that Elixir cannot be installed on our container-based Precise i.e. your .travis.yml file would contain something similar to

```yaml
language: elixir
elixir: 1.4.2
sudo: false
dist: precise # this is optional
```

Sample error in the logs:

```
0.02s$ wget https://repo.hex.pm/builds/elixir/v1.4.2.zip
--2017-05-02 22:51:20--  https://repo.hex.pm/builds/elixir/v1.4.2.zip
Resolving repo.hex.pm (repo.hex.pm)... 151.101.33.5
Connecting to repo.hex.pm (repo.hex.pm)|151.101.33.5|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.


The command "wget https://repo.hex.pm/builds/elixir/v1.4.2.zip" failed and exited with 4 during .
```

This is most probably caused by [this change made by Fastly yesterday](https://status.fastly.com/incidents/4n5jrrhh5fyh) and we are contacting the maintainers over at https://hex.pm to have this fixed.

In the meantime, you can route your builds on our sudo-enabled Precise image where the issue isn't found. Here's what you need to add to your .travis.yml file:

```
sudo: required
dist: precise # this is optional
```

We will follow-up here when we know more.

Thank you for your understanding!

**Comment by joepvd** [comment]
Updating `libssl1.0.0` in the build is a workaround that works. To use this workaround, include the following in `.travis.yml`:

```yaml
addons:
    apt:
        packages:
            - libssl1.0.0
```

**Comment by cotsog** [comment]
This should be fixed later today as per [this comment in the Elixir forum](https://elixirforum.com/t/if-youre-using-travis-ci-you-probably-want-to-read-this/4915/4). We will post an update here when it's working again.

Thank you for your patience!

**Comment by cotsog** [comment]
We are confirming that this is now fixed 🎉  => https://elixirforum.com/t/if-youre-using-travis-ci-you-probably-want-to-read-this/4915/6?u=cotsog.

Thanks again for your enduring patience! ❤️
