### ISSUE TITLE
Cannot install PHP 5.3 in Trusty

### ISSUE THREAD

**Issue by jwfuller** [travis-ci/travis-ci#7693]
See https://travis-ci.org/CuBoulder/express/builds/228455772. Building in Trusty to try and work around #4757, but get error for PHP 5.3
```
5.3 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-5.3.tar.bz2
0.07s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by BanzaiMan** [comment]
Sorry, but we do not support 5.3 and below on Trusty. https://github.com/travis-ci/travis-ci/issues/2963 If you need PHP 5.3, please use Precise.

**Comment by BanzaiMan** [comment]
If you need to connect to TLS v1.2 only site, try updating `libssl1.0.0`:


```yaml
addons:
  apt:
    packages:
      - libssl1.0.0
```

https://github.com/travis-ci/travis-ci/issues/4757#issuecomment-299024359

**Comment by jwfuller** [comment]
@BanzaiMan Your suggestion worked, thanks!

**Comment by sabberworm** [comment]
@BanzaiMan How can I use trusty for HHVM and precise for PHP 5.3? It seems there is no way to specify in `.travis.yml` which dist to use for which PHP version. This makes it impossible to test PHP 5.3 and HHVM simultaneously since HHVM on precise tells us to use trusty: “HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.”

**Comment by BanzaiMan** [comment]
@sabberworm See https://github.com/travis-ci/travis-ci/issues/7712#issuecomment-300553336.

**Comment by sabberworm** [comment]
@BanzaiMan Thanks!

**Comment by dhensby** [comment]
@BanzaiMan The docs need updating to this effect, they currently only say 5.2 isn't possible (https://docs.travis-ci.com/user/trusty-ci-environment/#PHP)
