### ISSUE TITLE
The command "docker pull ubuntu" failed and exited with 127 during .

### ISSUE THREAD

**Issue by AJRepo** [travis-ci/travis-ci#7694]
I'm trying to setup a minimal .travis.yml file and pull a xenial ubuntu image from https://hub.docker.com/_/ubuntu/ 

So I'm at the point where I'm just trying to pull anything. I've read the TravisCI docs and seen the example repo: https://github.com/travis-ci/docker-sinatra but something is still off. 

I looked up 127 errors and it seems to be https://github.com/moby/moby/issues/8176 a "device-mapper device busy" error? But I'm not sure. 

The minimal .travis.yml file I now have is 
```
---
sudo: required

services:
  - docker:

before_install:
  - sudo apt-get update
  - docker pull ubuntu

script:
  - docker build
```

I've tried a number of different docker pull arguments (e.g. docker pull tianon/docker-brew-ubuntu-core ) but all fail with the same error 127. 

"The command "docker pull ubuntu" failed and exited with 127 during ."

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
If your `.travis.yml` is exactly what you showed above, then I believe the problem is the `services` definition. It should be:

```yaml
sudo: required

services:
  - docker
⋮ # rest
```

If you still see the problem after changing the definition, please reopen this issue along with the build log URL that shows the problem you are having.

Thank you.

**Comment by AJRepo** [comment]
That solved the 127 error issue. Thank you.
