### ISSUE TITLE
Compilation failing for package 'feather' (again)

### ISSUE THREAD

**Issue by rabutler** [travis-ci/travis-ci#7695]
Hi,

It looks like a new issue with compiling feather has occurred recently, even if .travis.yaml is configured as described in https://github.com/wesm/feather/issues/154

It doesn't look like it is specific to my package (https://travis-ci.org/rabutler/CRSSIO) as `rio` is also failing with the same error (https://travis-ci.org/leeper/rio). 

Thanks in advance for any help resolving @jimhester @craigcitro

**Comment by rabutler** [comment]
As pointed out here https://github.com/tidyverse/readxl/issues/176, adding `dist: trusty` resolves the issue. 

Is that the preferred fix at this point?

**Comment by jimhester** [comment]
Yes `dist: trusty` is the easiest way to resolve this.

**Comment by rabutler** [comment]
Thanks @jimhester
