### ISSUE TITLE
MySQL Unknown System Variable Innodb_page_size

### ISSUE THREAD

**Issue by c9s** [travis-ci/travis-ci#7699]
```
1) IndexCommandsTest::testIndex
PDOException: SQLSTATE[HY000]: General error: 1193 Unknown system variable 'Innodb_page_size'
```
However this variable should be there. It exists since MySQL 5.5.

**Comment by c9s** [comment]
This variable is mentioned here

https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by c9s** [comment]
Yes

https://travis-ci.org/maghead/maghead/jobs/228722257



Hiro Asari <notifications@github.com>於 2017年5月4日 週四，21:49寫道：

**Comment by c9s** [comment]
And if I removed the variable, it shows

1146 Table 'mysql.innodb_index_stats' doesn't Exist

https://travis-ci.org/maghead/maghead/jobs/228727955

Yo-An Lin <yoanlin93@gmail.com>於 2017年5月4日 週四，21:50寫道：

**Comment by BanzaiMan** [comment]
Neither build shows the error message that you initially indicated.

**Comment by c9s** [comment]
The log is too long, let me paste here:

```
There was 1 error:
1) IndexCommandsTest::testIndex
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mysql.innodb_index_stats' doesn't exist
/home/travis/build/maghead/maghead/src/Command/IndexCommand.php:90
/home/travis/build/maghead/maghead/vendor/corneltek/cliframework/src/CommandBase.php:845
/home/travis/build/maghead/maghead/vendor/corneltek/cliframework/src/Application.php:402
/home/travis/build/maghead/maghead/tests/Commands/IndexCommandTest.php:29
```

**Comment by c9s** [comment]
And the second error, looks like the MySQL on Travis CI doesn't support innodb:

```
There was 1 error:
1) IndexCommandsTest::testIndex
PDOException: SQLSTATE[HY000]: General error: 1193 Unknown system variable 'Innodb_page_size'
/home/travis/build/maghead/maghead/src/Command/IndexCommand.php:90
/home/travis/build/maghead/maghead/vendor/corneltek/cliframework/src/CommandBase.php:845
/home/travis/build/maghead/maghead/vendor/corneltek/cliframework/src/Application.php:402
/home/travis/build/maghead/maghead/tests/Commands/IndexCommandTest.php:29
```

**Comment by c9s** [comment]
Build 1: https://travis-ci.org/maghead/maghead/jobs/228725439
Build 2: https://travis-ci.org/maghead/maghead/jobs/228727955

**Comment by BanzaiMan** [comment]
`innodb_page_size` is most definitely defined (see, for example: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/228773656#L136). If it's not available to your code, I tend to think there is a problem between your code (or PDO) and MySQL.

**Comment by c9s** [comment]
If it's the issue (PDO and my MySQL), then it should also fail on my
machine.


Hiro Asari <notifications@github.com>於 2017年5月4日 週四，23:07寫道：

**Comment by BanzaiMan** [comment]
Could you try troubleshooting with our docker image? https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

I don't have the PHP expertise to troubleshoot much further than showing that the variable is defined.

**Comment by c9s** [comment]
I created a test case that only runs mysql from the command-line:
https://github.com/maghead/maghead/blob/master/travis/setup-mysql#L8

And here is the result:
https://travis-ci.org/maghead/maghead/jobs/229161006

**Comment by BanzaiMan** [comment]
Thanks. Upon further investigation, I found that 

```sql
SELECT @@Innodb_page_size
```
does not work with MySQL 5.5.x.

You can use MySQL 5.6.x by moving to Trusty (with `dist: trusty`) or by consulting `information_schema` instead:

```sql
SELECT variable_value FROM information_schema.global_status  WHERE LOWER(variable_name) = 'innodb_page_size';
```

See https://travis-ci.org/BanzaiMan/travis_production_test/jobs/230448981#L188

**Comment by c9s** [comment]
Thanks
