### ISSUE TITLE
"View Config" should mention sudo configuration

### ISSUE THREAD

**Issue by fulldecent** [travis-ci/travis-ci#7700]
`sudo: required` is assumed on some projects but not others. I don't know the actual rule for how you decide which.

This is an undocumented input for running tests, which is BAD.

Therefore, please document this under the "View Config" option for when viewing any repo.

**Comment by BanzaiMan** [comment]
Technically speaking, the `sudo` value is _always_ assumed. The default value is explained in https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments.

This default routing, though, is done on a different level, so it is not available on the config payload.

**Comment by fulldecent** [comment]
Thanks for explaining. The best place for this information would be outside of the json text and right here:

![screen shot 2017-05-04 at 4 54 55 pm](https://cloud.githubusercontent.com/assets/382183/25724609/8d4fe0d4-30ea-11e7-909a-945118b805e7.png)

**Comment by BanzaiMan** [comment]
To think, `sudo` value is shown in the job config. In the screenshot above, right about the middle of the config value display.

**Comment by fulldecent** [comment]
Right, but if I omitted it then a silent default would apply. It that case it would be impossible for you to interpret the configuration of this build.
