### ISSUE TITLE
Processing vignette fails; build stopped.

### ISSUE THREAD

**Issue by timtrice** [travis-ci/travis-ci#7701]
I have a vignette with an R package that has repeatedly failed on a particular piece of code. I am unable to identify the exact problem. 

[The build history of the repository](https://travis-ci.org/timtrice/Hurricanes/builds).

On March 28, 2017, the vignette passed in [Build #16](https://travis-ci.org/timtrice/Hurricanes/builds/215993323). This was state of [the vignette](https://github.com/timtrice/Hurricanes/blob/1b4cd8433e05f356d49b8b91863b9ff39ee64709/vignettes/getting-started.Rmd) at that time.

When I began working on the package this week I noticed builds began failing. The error message has generally been:

```
Building with: R CMD build 
4.90s$ R CMD build  .
* checking for file ‘./DESCRIPTION��� ... OK
* preparing ‘Hurricanes’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Quitting from lines 86-87 (getting-started.Rmd) 
Error: processing vignette 'getting-started.Rmd' failed with diagnostics:
is.character(url) is not TRUE
Execution halted
```

The problem code is this chunk:

```r
get_storm_data("fstadv", link = al.1998.charley %>% .$Link)
```

In Build \#16, this passed. Now it fails. For [Build #57](https://travis-ci.org/timtrice/Hurricanes/builds/228489981), I set the chunk's eval parameter to FALSE. The build failed this time at line #120 which has a similar piece of code:

```r
get_storm_data("fstadv", 
               names = list("fstadv" = "al.1998.charley.fstadv"), 
               link = al.1998.charley %>% .$Link)
```

The function `get_storm_data`  takes the variable `Link` from the dataframe `al.1998.charley` and access that URL, parses the data, loads it into a dataframe.

All tests and checks pass locally.

Now, I've built a [bare example of the vignette](https://github.com/timtrice/Hurricanes/blob/44573110ac5cec50ebed027bb2124af51bcce955/inst/doc/getting-started.Rmd) and submitted. That build, [#73](https://travis-ci.org/timtrice/Hurricanes/builds/228744711) failed. However, it did not fail where I expected it to, in chunk-2:

```r
(a <- al.1998.charley %>% .$Link)
(b <- al.1998.charley %>% select(Link) %>% first())
(c <- al.1998.charley[1,4])
(d <- "http://www.nhc.noaa.gov/archive/1998/1998CHARLEYadv.html")
```

Instead it failed in chunk-6:

```r
get_storm_data("fstadv", link = a, msg = TRUE)
```

So, perhaps it's an issue with my function. So I set chunk-6 (and similar chunks for variables `b` and `c` to `eval = FALSE`) and leave chunk-9 to evaluate:

```r
get_storm_data("fstadv", link = d, msg = TRUE)`
```

[This version of the vignette](https://github.com/timtrice/Hurricanes/blob/5fe4d764f08fb74afb02c013973a9f3f7890fd81/inst/doc/getting-started.Rmd) passes in [Build #74](https://travis-ci.org/timtrice/Hurricanes/builds/228753658).

So, perhaps there's a difference between the values of `a` and `d`. But the following calls all return TRUE:

```r
identical(a, b)
identical(b, c)
identical(c, d)
```

I would also like to note that on previous tests, `b` and `c` also fail. The only way this vignette will now pass travis is if I pass a direct string to the function call. 

I documented initial attempts to resolve it in my repo's [Issue #23](https://github.com/timtrice/Hurricanes/issues/23). I found there may be two separate issues (possibly related but not sure yet); one with the vignette; another with tests. I split the issues. Then continued in [Issue #24](https://github.com/timtrice/Hurricanes/issues/24) which focuses specifically on the vignette.

I believe this to be a travis issue simply because the code now causing the problems did not on March 28 when it passed. I over the blog and the Past Incidents log and saw no updates that seemed to deal with my project. 

If this is not a travis issue; I sincerely apologize but hope someone can point me in the correct direction.

Thank you,

Tim Trice

**Comment by BanzaiMan** [comment]
Please mention @craigcitro and @jimhester for R inquiries, as indicated in the build log. Thank you.

**Comment by jimhester** [comment]
Checking out a commit that failed and running `R CMD build .` reproduces the same error seen on travis on my machine, this is a package issue, not a travis one.

```shell
git clone https://github.com/timtrice/Hurricanes.git
git checkout 03e38026
R CMD build .
# * checking for file ‘./DESCRIPTION’ ... OK
# * preparing ‘Hurricanes’:
# * checking DESCRIPTION meta-information ... OK
# * installing the package to build vignettes
# * creating vignettes ... ERROR
# Quitting from lines 86-87 (getting-started.Rmd)
# Error: processing vignette 'getting-started.Rmd' failed with diagnostics:
# is.character(url) is not TRUE
# Execution halted
```

**Comment by timtrice** [comment]
I reset a new branch to the commit that passed in March; 1b4cd84. I pushed to travis and it failed. [Build #75](https://travis-ci.org/timtrice/Hurricanes/builds/228803810). I guess where I'm confused is why does it fail today but the same commit in [Build #16](https://travis-ci.org/timtrice/Hurricanes/builds/215993323) passed.

On a side note, I'm looking into trying to replicate this on my system. When I run `R CMD build .` I am not getting this error.

**Comment by jimhester** [comment]
The error is happening because you are trying to pass a factor to `httr::GET()` in your `.status()` function, the factor exists because you do not use `stringsAsFactors = FALSE` in your call to `data.frame()` in `.create_df_archives()`. Alternatively use `tibble::data_frame()` to create a tibble (which never implicitly creates factors) rather than a `data.frame`.

```diff
diff --git a/R/dataframes.R b/R/dataframes.R
index fd14699..bcd87ef 100644
--- a/R/dataframes.R
+++ b/R/dataframes.R
@@ -8,7 +8,7 @@
 #' }
 #' @return dataframe
 .create_df_archives <- function() {
-  df <- data.frame("Year" = integer(), 
+  df <- tibble::data_frame("Year" = integer(), 
                    "Name" = character(), 
                    "Basin" = character(), 
                    "Link" = character())
```

I don't know the reason you are not able to reproduce this locally, perhaps you have `options(stringsAsFactors = FALSE)` in your `.Rprofile`, or do not have updated packages (run `update.packages(ask = FALSE)`  to update all of them to the latest versions.

**Comment by timtrice** [comment]
@jimhester thank you very much for your help. I corrected the data frame and the latest build passed. Apologies for not researching more in-depth.
