### ISSUE TITLE
Scala build broken: /usr/local/bin/sbt: Permission denied

### ISSUE THREAD

**Issue by ScalaWilliam** [travis-ci/travis-ci#7703]
![screen shot 2017-05-05 at 10 11 52](https://cloud.githubusercontent.com/assets/2464813/25731714/51d2970e-317b-11e7-8988-6764200c898b.png)

Here's the log: https://travis-ci.org/ScalaWilliam/ActionFPS/builds/228954031

Guess it's to do with the [image updates](https://blog.travis-ci.com/2017-05-04-precise-image-updates).

**Comment by BanzaiMan** [comment]
For now, please add:

```yaml
before_script:
  - chmod +x /usr/local/bin/sbt
```

Thanks.

**Comment by BanzaiMan** [comment]
The fix has been deployed to production. Scala builds should now go without the aforementioned workaround.

**Comment by JEEYOO** [comment]
Thanks man。My prob has been solved
