### ISSUE TITLE
Our Java builds do not use Java 8 anymore

### ISSUE THREAD

**Issue by martinvw** [travis-ci/travis-ci#7704]
The build for Java seem a little bit mixed up, the maven claims to run java 8 but actually the `java` and `javac` refer to Java 7.

https://travis-ci.org/openhab/openhab2-addons/builds/229004752?utm_source=github_status&utm_medium=notification

```
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-115-generic", arch: "amd64", family: "unix"
```

```
$ java -Xmx32m -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
$ javac -J-Xmx32m -version
javac 1.7.0_80
```

**Comment by meatballhat** [comment]
@martinciu I don't see an explicit `jdk:` key in your config.  Can you set that like so to ensure consistent JDK selection?  I understand your jobs may have worked before without this configuration, but it was effectively luck based on the order of operations during image build time.

``` yaml
jdk: oraclejdk8
```

**Comment by martinvw** [comment]
Thanks, we will try that, we keep you posted.

**Comment by martinvw** [comment]
Works, thanks for the quick response!
