### ISSUE TITLE
Error installing stevedore package on python3.5

### ISSUE THREAD

**Issue by abingham** [travis-ci/travis-ci#7708]
I'm seeing an error when I try to install the `stevedore` package under Python3.5 on `precise`:
```
nstalled /tmp/easy_install-rrgemj4i/stevedore-1.21.0/.eggs/pbr-3.0.0-py3.5.egg

/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/setuptools/dist.py:375: UserWarning: Module pbr was already imported from /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pbr/__init__.py, but /tmp/easy_install-rrgemj4i/stevedore-1.21.0/.eggs/pbr-3.0.0-py3.5.egg is being added to sys.path

  pkg_resources.working_set.add(dist, replace=True)

ERROR:root:Error parsing

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pbr/core.py", line 111, in pbr

    attrs = util.cfg_to_args(path, dist.script_args)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pbr/util.py", line 248, in cfg_to_args

    kwargs = setup_cfg_to_setup_kwargs(config, script_args)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pbr/util.py", line 382, in setup_cfg_to_setup_kwargs

    cmd = cls(dist)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/setuptools/__init__.py", line 127, in __init__

    _Command.__init__(self, dist)

  File "/opt/python/3.5.2/lib/python3.5/distutils/cmd.py", line 57, in __init__

    raise TypeError("dist must be a Distribution instance")

TypeError: dist must be a Distribution instance

error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-rrgemj4i/stevedore-1.21.0/setup.cfg: TypeError: dist must be a Distribution instance
```

I've re-run formerly passing tests and they fail this way, as do all new test runs. So I assume something has changed in the underlying image (perhaps in the precise update the recently happened).

For an example of this, see [this build](https://travis-ci.org/sixty-north/cosmic-ray/jobs/199327154).

**Comment by BanzaiMan** [comment]
The version of "stevedore" changed from [1.20](https://travis-ci.org/sixty-north/cosmic-ray/jobs/196868716#L354) in the last surviving passing build to [1.21](https://travis-ci.org/sixty-north/cosmic-ray/jobs/199327154#L342) in recent failing builds. Does 1.21 work for you at all locally? Does it make a difference if you pin the "stevedore" version to 1.20?

**Comment by abingham** [comment]
Interestingly, pinning stevedore to 1.20 does seem to make the problem go away. But this doesn't seem like the real issue. My tests work fine with stevedore 1.21 on the python 3.4, 3.5-dev, 3.6, and nightly images.

**Comment by BanzaiMan** [comment]
It could very well be a combination of Python 3.5 and stevedore 1.21.

Anyhow a recent build is passing https://travis-ci.org/sixty-north/cosmic-ray/builds/235123141, so I'll close this.
