### ISSUE TITLE
Add a git option to control recursiveness of submodule fetching

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [travis-ci/travis-ci#7709]
There are some projects that don't expect recursive submodule fetching, so it would be nice to have an option to control submodule fetching, the same as there is an option to control clone depth. Possible submodule options:
```yml
git:
    submodule: (none|shallow|recursive)
```

Where `none` doesn't fetch submodules at all, `shallow` performs a simple `git submodule update --init` and `recursive` is the current (and default) behavior.

**Comment by BanzaiMan** [comment]
You should disable automatic `submodules` commands and run your own.

https://docs.travis-ci.com/user/common-build-problems/#Git-Submodules-are-not-updated-correctly
