### ISSUE TITLE
R Travis, R 3.4, Mac OS X

### ISSUE THREAD

**Issue by elbamos** [travis-ci/travis-ci#7711]
@craigcitro @hadley @jimhester

How should we configure travis for testing on OS X of R packages that include C++ code that requires compilation?  

I'm now getting an error that `clang` doesn't recognize `-fopenmp`. I think this is because as of 3.4, `Makeconf` on OS X now has OpenMP setup, but by default will attempt to use XCode's older `clang`, which doesn't support OpenMP.

**Comment by jimhester** [comment]
Could you link to a failing build?

**Comment by elbamos** [comment]
Here's an example:  https://travis-ci.org/elbamos/largeVis/jobs/228962416
The package Makevars include openmp since the package tries to use it: https://github.com/elbamos/largeVis/blob/master/src/Makevars

This wasn't a problem before 3.4, I believe because on OS X the `SHLIB_OPENMP_` environment variables were empty.

**Comment by jimhester** [comment]
This will be a problem in general compiling on macOS using Apple LLVM now unfortunately, unless one installs trunk llvm 4.0.0 manually. I get the same error's locally using 

```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
I think you will have to do your own check to see if the compiler actually supports OpenMP in `configure`, the [ARTP2](https://github.com/zhangh12/ARTP2/blob/master/configure.ac) package has an example. This is tangentially mentioned in [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#OpenMP-support)

> Note that the macro SHLIB_OPENMP_CXXFLAGS applies to the default C++ compiler and not necessarily to the C++11/14/17 compiler: users of the latter should do their own configure checks (an example is available in CRAN package ARTP2).

An alternative to using a configure script is to put a condition in your Makevars. I sent a PR with an example (https://github.com/elbamos/largeVis/pull/48) which I believe will work with all common platforms.

**Comment by elbamos** [comment]
Thank you!!!
