### ISSUE TITLE
HHVM image is broken

### ISSUE THREAD

**Issue by wshafer** [travis-ci/travis-ci#7712]
Error on startup:

```
The following packages have unmet dependencies:

 hhvm : Depends: libboost-filesystem1.49.0 but it is not installable

        Depends: libboost-program-options1.49.0 but it is not installable

        Depends: libboost-system1.49.0 but it is not installable

        Depends: libboost-regex1.49.0 but it is not installable

        Depends: libgd2-xpm but it is not going to be installed

        Depends: libboost-thread1.49.0 but it is not installable

E: Unable to correct problems, you have held broken packages.

The command "sudo apt-get install -y hhvm" failed and exited with 100 during .
```

Example failed build: https://travis-ci.org/RWOverdijk/AssetManager/jobs/229353321

Travis.yml
```
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist -n

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests/AssetManagerTest
```

**Comment by BanzaiMan** [comment]
Perhaps Facebook's package dependency specification is incorrect. The versions of `libboost*` packages available for Precise are 1.46.0 or 1.48.0 (http://packages.ubuntu.com/search?suite=precise&searchon=names&keywords=libboost), which are older than 1.49 (http://dl.hhvm.com/ubuntu/dists/precise/main/binary-amd64/Packages).

Does it work if you specify `dist: trusty`?

**Comment by wshafer** [comment]
Yes adding `dist: trusty` to the config got HHVM working.

**Comment by BanzaiMan** [comment]
Thanks for the report. I think it is best to document this, and fail HHVM builds on Precise.

**Comment by aidantwoods** [comment]
@BanzaiMan Didn't work where I'm having this issue, I think I may be running into separate bugs though: https://travis-ci.org/erusev/parsedown/builds/230486015?utm_source=github_status&utm_medium=notification

**Comment by BanzaiMan** [comment]
@aidantwoods That seems like an issue with HHVM and PHPUnit. Do you see the problem if you try it on your machine?

By the way, I should add that we do not support PHP 5.3 on Trusty.

**Comment by aidantwoods** [comment]
@BanzaiMan seems to
<img width="837" alt="screen shot 2017-05-10 at 11 12 09" src="https://cloud.githubusercontent.com/assets/3288888/25893877/8df3ed60-3571-11e7-8b9d-567bcc936aad.png">

Is there any way to switch distros using the build matrix? Tried using `dist: trusty` and `sudo: required` under `include:` but the online travis.yml validator didn't recognise those keys there

**Comment by BanzaiMan** [comment]
You are using `vendor/bin/phpunit`, which is version 5.7.19.

**Comment by aidantwoods** [comment]
Ah yes, I see the travis build was using 5.7.2, still works locally though

<img width="837" alt="screen shot 2017-05-10 at 11 46 33" src="https://cloud.githubusercontent.com/assets/3288888/25895102/68d2ca10-3576-11e7-97d1-626cd62e96a6.png">

**Comment by BanzaiMan** [comment]
Thanks. Could you also try HHVM 3.18.2, and confirm that you are using Ubuntu Trusty?

**Comment by aidantwoods** [comment]
Ah, apologies – thought you'd wanted me to just test hhvm locally (i.e. on my current machine) – whoops 😆 

ubuntu-trusty, hhvm 3.18.2, phpunit 5.7.2
<img width="922" alt="screen shot 2017-05-10 at 13 04 24" src="https://cloud.githubusercontent.com/assets/3288888/25897776/34057d4a-3581-11e7-8f94-a5afb7b01f0b.png">

**Comment by BanzaiMan** [comment]
Thanks for testing these various combinations. I have reproduced your error with some effort, but I am afraid I am at a loss what might be ailing your build.

If you would like, you can see how I reproduced it here: https://gist.github.com/BanzaiMan/941e64f2324effb59e5064b6a5d8f924

**Comment by aidantwoods** [comment]
Ah, we've differed on our method of installing phpunit. Not entirely sure why that matter atm, but I can repro the error now

<img width="912" alt="screen shot 2017-05-10 at 15 27 44" src="https://cloud.githubusercontent.com/assets/3288888/25903787/51c58136-3595-11e7-98c0-ac956b12ddae.png">

**Comment by BanzaiMan** [comment]
@aidantwoods That's good news. Let us know what you find, and tell us what needs fixing. Thank you!

**Comment by aidantwoods** [comment]
Down the rabbit hole...

<img width="912" alt="screen shot 2017-05-10 at 15 34 00" src="https://cloud.githubusercontent.com/assets/3288888/25904119/2cbf6892-3596-11e7-8914-034f67a746b6.png">
<img width="912" alt="screen shot 2017-05-10 at 15 34 25" src="https://cloud.githubusercontent.com/assets/3288888/25904120/2cc5676a-3596-11e7-8b3b-0fef922ff0f5.png">

**Comment by aidantwoods** [comment]
Removing the composer files doesn't seem to change the behaviour either

<img width="912" alt="screen shot 2017-05-10 at 15 35 44" src="https://cloud.githubusercontent.com/assets/3288888/25904209/77c776b8-3596-11e7-8ee0-ec6865e76c6a.png">
<img width="912" alt="screen shot 2017-05-10 at 15 36 11" src="https://cloud.githubusercontent.com/assets/3288888/25904210/77f24942-3596-11e7-9dda-ffaedea35173.png">

**Comment by aidantwoods** [comment]
Seems to be a bug with the phar release of 5.7.2, any reason it needs to be this version? (tried 5.7.19 phar and it doesn't *seem* to have the same behaviour).

**Comment by BanzaiMan** [comment]
There isn't. The version is there because it was the one that was most recent when the build image was provisioned. If it is faulty, I suggest updating it yourself until the image is updated.

**Comment by aidantwoods** [comment]
Sure,

RE
> I think it is best to document this, and fail HHVM builds on Precise.

Will HHVM still be supported on Precise, or should we move over to Trusty if we want to use it?

**Comment by BanzaiMan** [comment]
HHVM team has ceased supporting Precise a while back, so I very much recommend moving on.

**Comment by aidantwoods** [comment]
Cool, and just lastly – am I right in thinking that the build matrix (or otherwise) can't be used run builds on both PHP 5.3 and HHVM (by switching between Precise and Trusty respectively)?

**Comment by BanzaiMan** [comment]
@aidantwoods This is possible with `matrix.include`; e.g.,

```yaml
language: php
dist: trusty
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - hhvm
matrix:
  include:
    - php: "5.3"
      dist: precise
⋮
```

**Comment by aidantwoods** [comment]
Ah perfect, I had tried a setup like that but didn't commit because it didn't pass through the validator over at https://lint.travis-ci.org/

Thanks!

**Comment by BanzaiMan** [comment]
HHVM + Precise will now result in build error.

**Comment by rokob** [comment]
> HHVM + Precise will now result in build error.

It would be nice to update the docs on this, https://docs.travis-ci.com/user/languages/php/#HHVM-versions-on-Precise

<img width="288" alt="screen shot 2017-05-30 at 4 03 51 pm" src="https://cloud.githubusercontent.com/assets/831355/26608663/a79611fe-4551-11e7-8aa3-9936c5f10b2f.png">

How can I set up a build configuration to test both 5.3 and HHVM now?
