### ISSUE TITLE
Failed to install gsl-bin and libgsl0-dev on Trusty

### ISSUE THREAD

**Issue by i2000s** [travis-ci/travis-ci#7716]
Hi there,

I was using travis-CI to build my Jekyll website with `sudo apt-get install gsl-bin libgsl0-dev` in the `.travis.yml` configuration file. It was working fine last week using Trusty, but today, errors popped out:

```
The following packages have unmet dependencies:
 libgsl0-dev : Depends: libgsl0ldbl (= 1.16+dfsg-1ubuntu1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
The full log can be found [here](https://travis-ci.org/i2000s/cn/builds/229563237).
If I include ` libgsl0ldbl`, then `libgsl2` is missing for `gsl-bin` installation.  Surely, I can fix those errors by adding more dependent packages, but I wonder if there is any unnecessary changes on the server side during the past week? 

Thanks!
Qi

**Comment by BanzaiMan** [comment]
This appears to have been fixed with https://travis-ci.org/i2000s/cn/builds/229604492.

**Comment by i2000s** [comment]
Yeah, I fixed it by replacing `gsl-bin` with another package. Is there any weird thing changed during the last a couple weeks?
