### ISSUE TITLE
"Sorry, but JDK '[oraclejdk8]' is not known"

### ISSUE THREAD

**Issue by MarcJose** [travis-ci/travis-ci#7718]
When running a build with the travis-worker I receive the following error:

> Java version: 1.7.0_76, vendor: Oracle Corporation
> Java home: /usr/lib/jvm/java-7-oracle/jre
> 
> sed: cannot rename /etc/hosts: Device or resource busy
> sed: cannot rename /etc/hosts: Device or resource busy
>
> $ jdk_switcher use ["oraclejdk8"]
> Sorry, but JDK '[oraclejdk8]' is not known.
> 
> The command "jdk_switcher use ["oraclejdk8"]" failed and exited with 1 during .
>
> Your build has been stopped.

This happens with all projects which use oraclejdk8 or another one than the preinstalled. I also tried installing it before the tests with:
```
add-apt-repository ppa:webupd8team/java -y
apt-get update -y -qq
apt-get install -y -qq oracle-java8-installer
```
But no changes. Any ideas?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by MarcJose** [comment]
I am running it locally with the quay.io/travisci/travis-jvm container and a build script generated by travis-build.

**Comment by BanzaiMan** [comment]
Local generation does not take build matrix into account. Try this:

```yaml
jdk: oraclejdk8
```

**Comment by MarcJose** [comment]
But isn't that exactly what travis does according to the documentation here?
- Generate buildscript
- Upload it to a testcontainer and run
- Stream logs back

But it seems to work until:

> Switching to Oracle JDK8 (java-8-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-8-oracle
> $ git clone --depth=50 --branch='' https://github.com/ActiveJpa/activejpa ActiveJpa/activejpa
> Cloning into 'ActiveJpa/activejpa'...
> warning: Could not find remote branch  to clone.
> fatal: Remote branch  not found in upstream origin
> Unexpected end of command stream
> The command "eval git clone --depth=50 --branch='' https://github.com/ActiveJpa/activejpa ActiveJpa/activejpa " failed. Retrying, 2 of 3.

(This is not my project, just one I randomly selected for testing from the travis logs). Do I also have to change the clone command manually to include the branch or did I just missed something when running travis compile > ../build.sh to generate the buildscript?

**Comment by MarcJose** [comment]
Okay, I guess the above thing is another issue so back to the original one: 
What would be the syntax if there are multiple jdk's to be tested against? Eg like:
```
jdk:
  - oraclejdk8
  - openjdk7
```

**Comment by BanzaiMan** [comment]
The build script generation is for a single jobs, while the matrix expansion with

```yaml
jdk:
  - oraclejdk8
  - openjdk7
```

is concerned with the build. This does not work with `travis compile`.

**Comment by BanzaiMan** [comment]
`travis-build` generates the build script based on the payload handed to it by `travis-scheduler`. The local build script generation with `travis compile` tries to mimic this payload, but it has some limitations. This is one of those cases.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/#use-as-addon-for-cli

> … that the build matrix expansion is not considered.

**Comment by romeara** [comment]
While the above "build matrix not considered" comments are correct that this is a documented limitation, I am wondering why the script crashes - if it is not considered, why is there a line in the script at all? 

I think this might still be classified as a bug in the line generated - it generated with "["oraclejdk8"]" (for example), when it should be "oraclejdk8", based on reading through jdk_switcher's source code. Using a sed replacement on a generated script "ci.sh":
```
sed -i 's/jdk_switcher\\ use\\ \\\[\\"oraclejdk8\\"\\]/jdk_switcher\\ use\\ oraclejdk8/g' ci.sh
```
fixes the reported error, allowing [jdk_switcher](https://github.com/michaelklishin/jdk_switcher) to recognize the alias being used and successfully switch to it within the travis-jvm Docker image.

Could someone more familiar with this clarify? Is there an environment in which the generated line works that I'm not understanding? Or does Travis just somehow never call the generated script in a way which would execute that line?

**Comment by BanzaiMan** [comment]
> While the above "build matrix not considered" comments are correct that this is a documented limitation, I am wondering why the script crashes - if it is not considered, why is there a line in the script at all?

The `language` value is considered, but matrix expansion is not.

`travis compile` is *not* how we generate build scripts. It is meant to be an approximation (good enough for many cases), but not a replacement.

**Comment by romeara** [comment]
Ah, that clarifies a bit, thank you - from the first little blurb in the readme I got the impression travis-build was used somehow in the "real" build process. Unfortunate, I was trying to reproduce a bug in my stuff that's only popping up in Travis.

Thanks again for the response and clarification!

**Comment by BanzaiMan** [comment]
> I got the impression travis-build was used somehow in the "real" build process

It is, but not via `travis compile` (or equivalent).

If you need a real debug build, we can enable the feature for your repo. See https://docs.travis-ci.com/user/running-build-in-debug-mode/ and email support@travis-ci.com.
