### ISSUE TITLE
Request: PHP 7.1 should be installed by default for phpenv in the base images?

### ISSUE THREAD

**Issue by TysonAndre** [travis-ci/travis-ci#7721]
https://docs.travis-ci.com/user/trusty-ci-environment/

PHP 7.1 is the latest point release of PHP, but every (or almost every?) time it builds, I see "7.1 is not pre-installed; installing" in the output.

> phpenv is installed and we pre-install at least two of the latest point releases such as 7.0.7 and 5.6.24. Any versions that are not pre-installed will be dynamically installed from a local cache, or built via phpenv if unavailable.

Downloading and installing php 7.1(.4) adds an extra 13 seconds to builds

Adding PHP 7.1 both to the default travis image (12.04) and the trusty (ubuntu 14.04) beta would be desirable.

**Comment by TysonAndre** [comment]
Also, I noticed that php 7.0 points to older images on some of the images for `trusty`  (currently 7.0.7, latest on php.net is 7.0.23), but depend on newer patch releases (There were various bug fixes in patch releases, I assume those bugs affected the libraries in earlier patch releases)

https://github.com/symfony/yaml/blob/3.3/composer.json#L19 is an example of this.

- I see this mentioned in https://github.com/travis-ci/travis-ci/issues/8211

Also, 5.6.31 is out.

**Comment by edmorley** [comment]
> Also, I noticed that php 7.0 points to older images on some of the images for trusty (currently 7.0.7, latest on php.net is 7.0.23)

I updated the patch release versions in travis-ci/packer-templates#491, which made it into the new image release that will be pushed out in a couple of days:
https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/

For 7.1, travis-ci/packer-templates#502 has been filed :-)

**Comment by TysonAndre** [comment]
According to https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/ , this should be fixed
