### ISSUE TITLE
Builds marked as failing

### ISSUE THREAD

**Issue by bluescarni** [travis-ci/travis-ci#7722]
Since a couple of days, builds which used to be successful are now marked as failing, even if there's no trace of failures in the logs. Examples:

https://travis-ci.org/bluescarni/mppp/jobs/229661221
https://travis-ci.org/esa/pagmo2/jobs/229444427

I don't know if it matters, but they are both documentation builds involving sphinx and doxygen.

How could I help to debug such an issue?

**Comment by BanzaiMan** [comment]
Are you setting the `bash` `errexit` option somewhere (e.g., `set -x` or `set -o errexit`)? In both of the examples you gave, the build execution stopped at:

```
/usr/bin/clear_console -q
```

I suspect that this command is exiting with nonzero exit status, and the build script exits *immediately*, which results in the error status you are seeing.

**Comment by bluescarni** [comment]
@BanzaiMan Thanks for the quick reply!

We are indeed setting the ``-x`` option on top of our travis scripts. Specifically, we set both the ``-x`` and ``-e`` options at the very beginning:

https://github.com/esa/pagmo2/blob/master/tools/install_travis.sh#L3

Do you think that setting ``+x`` and ``+e`` before ``exit 0`` may solve this issue?

**Comment by BanzaiMan** [comment]
Oops. I meant `set -e`. This is known to cause problems because it terminates the build with any nonzero exit.

**Comment by bluescarni** [comment]
@BanzaiMan Thanks a lot for the help, it seems to work fine now :) I'll close this for the time being.
