### ISSUE TITLE
Option to choose package managers for Travis build, Yarn vs. NPM

### ISSUE THREAD

**Issue by zhujy8833** [travis-ci/travis-ci#7724]
I have a failed travis build for one of my `ember-addon` using `ember-try`(https://github.com/ember-cli/ember-try), it chose to use `Yarn` as the package manager if found out `yarn` is installed globally. 

The fact is that in my repo I have set `dist: trusty` in `.travis.yml`, in order to use features in Trusty build. But it seems that `Yarn` is preinstalled there, which led to the behavior of the build chose `Yarn` rather than `NPM`.

Is there an option that I can explicitly set `package_manager: npm` in `.travis.yml`, so that I can force Travis to run npm command? I found that field would be helpful for some cases, to override some of the test plugin options.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
As explained in https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Dependency-Management, we detect the use of npm and yarn based on the repository's content. If our detection is lacking, please override `install` as you wish.

**Comment by zhujy8833** [comment]
Thanks @BanzaiMan. I've created a github issue on `ember-try` side: https://github.com/ember-cli/ember-try/issues/125, because I feel this is a question to `ember-try` instead of Travis.

Thank you for looking into this.

**Comment by carlwright4** [comment]
(#7724)
