### ISSUE TITLE
Could not find .travis.yml, using standard configuration.

### ISSUE THREAD

**Issue by phpstudyOne** [travis-ci/travis-ci#7727]
travis-ci 经常提示 ：
Worker information
hostname: i-042e8d8-precise-production-2-worker-org-docker.travisci.net:409c82b8-2bc7-4d8d-9b9a-2d0c15ef6078
version: v2.5.0 https://github.com/travis-ci/worker/tree/da3a43228dffc0fcca5a46569ca786b22991979f
instance: b0f4ed7:travis:ruby
startup: 747.506616ms
Could not find .travis.yml, using standard configuration.
Build system information
Build language: ruby
Build group: stable
Build dist: precise
Build id: 229076679
Job id: 229076681
travis-build version: 66bd59b85
Build image provisioning date and time

## Could not find .travis.yml, using standard configuration.

请问  `.travis.yml` 应该如何添加，添加到何处？ 添加何内容？
![image](https://cloud.githubusercontent.com/assets/11455285/25788166/a405ae8e-33d9-11e7-9483-221a246a4bc9.png)

**Comment by BanzaiMan** [comment]
I'm sorry, but not a lot of people can read or write Chinese, so I will assume the following text which I got with Google Translate:

    Will .travis.yml should be added, where to add? What's added?

Furthermore, based on https://travis-ci.org/phpstudyOne/lite/jobs/229815035, I assume that you figured out that `.travis.yml` should be in the root directory of your repository.

Your repository, however, seems to be a PHP app, so please review https://docs.travis-ci.com/user/languages/php to further customize your build to fit your needs.

Thanks.

**Comment by phpstudyOne** [comment]
thanks for your answers, but i still have some questions.
I updated ".travis.yml" file：
```
language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
before_script: composer require atoum/atoum
script: vendor/bin/atoum
```

and then deleted the semicolon “;” in  `index.php` , then it comes to `define('BASE_PATH',str_replace('\\','/',realpath(dirname(__FILE__).'/'))."/")`
why I still can build it successful.

![image](https://cloud.githubusercontent.com/assets/11455285/25840903/5942c27c-34d0-11e7-9eee-f538a3e8f0ac.png)

**Comment by BanzaiMan** [comment]
That seems like an application issue.

**Comment by BanzaiMan** [comment]
I'm closing this, as there is not much to do on our part.
