### ISSUE TITLE
.NET Core build fails on OSX with "Too many open files" error

### ISSUE THREAD

**Issue by JSkimming** [travis-ci/travis-ci#7728]
cc @joshua-anderson @akoeplinger @nterry

I've an [open source .NET Core](https://github.com/JSkimming/abioc "aboic") project that I've been successfully building in [travis for a while on Linux](https://travis-ci.org/JSkimming/abioc/jobs/229872917).

I've just tried to configure a build matrix (JSkimming/abioc#27) to also build on OSX, but it's failing during package restore with an the error "[Too many open files](https://travis-ci.org/JSkimming/abioc/jobs/229873239#L1351)".

From a [quick google](https://www.google.co.uk/search?q=.net+core+travis+OSX+%22Too+many+open+files%22) I've found a few hits, one that suggests [using `ulimit`](https://github.com/dotnet/cli/pull/818/files#diff-2e0af978b082590d4a5a58bca177781dR33) to increase the file description limit, but I can't discover some example configuration.

Is there a recommended set-up to build .NET Core on OSX? The documentation seems to be [mostly around Linux](https://docs.travis-ci.com/user/languages/csharp/#.NET-Core).

**Comment by akoeplinger** [comment]
It should just work the same way on OSX. That said, I've also seen the "Too many open files" issue a few times during package restore on OSX so increasing ulimit is probably the best way until it's fixed in .NET Core.

Try adding this to your .travis.yml:

```
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi
```

**Comment by JSkimming** [comment]
@akoeplinger Thanks for quick reply. That worked out.

For reference. Here is the [working build](https://travis-ci.org/JSkimming/abioc/jobs/229949332/config), and the here is the relevant [`.travis.yml`](https://github.com/JSkimming/abioc/pull/27/files#diff-354f30a63fb0907d4ad57269548329e3R18) changes.
