### ISSUE TITLE
Job Log Not Displayed Due To cssText JavaScript Error

### ISSUE THREAD

**Issue by chrislopresto** [travis-ci/travis-ci#7730]
Over the past few weeks, we have struggled to debug various failed build jobs due to the log not being displayed in the web UI.

<img width="853" alt="screenshot 2017-05-08 11 28 55" src="https://cloud.githubusercontent.com/assets/93691/25811513/8bea509a-33e1-11e7-8696-2711c9942965.png">

I see the following JavaScript error in the console:

```
shared.js:27 Uncaught TypeError: Cannot set property 'cssText' of undefined
    at shared.js:27
    at shared.js:27
    at shared.js:16
    at shared.js:16
```

Is this a known issue? I searched for `cssText` but didn't find anything.

Thanks.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

Does it happen everywhere for you, or just a few pages? Does it happen if you use a private window? Does it happen in a different browser?

**Comment by chrislopresto** [comment]
Sorry, I didn't capture any meaningful state when I noticed this issue. As other folks haven't piled on, I'll just go ahead and close out this issue.

Thanks!
