### ISSUE TITLE
The job exceeded the maximum time limit for jobs, and has been terminated.

### ISSUE THREAD

**Issue by kjnanda** [travis-ci/travis-ci#7731]
I am running my codeception acceptance test on Travis with browser stack integration. Each time my build stops because of this reason -> `The job exceeded the maximum time limit for jobs, and has been terminated.`

I am running the build on `dist: trusty` environment. Not able to figure this out. 

![unnamed image 1](https://cloud.githubusercontent.com/assets/15173772/25845692/7b8503d0-34cc-11e7-8030-c00f70b830eb.png)

Any help would be appreciated.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
Is there anything supposed to run after https://travis-ci.org/kjnanda/rtMedia/builds/230234183#L1380? Looking at this and older builds, it seems to me that they are hanging at various points legitimately.

**Comment by kjnanda** [comment]
This is my config file - https://travis-ci.org/kjnanda/rtMedia/jobs/230234185/config

Where I have added the command to run test suites. The test stops in between the execution only. Means all the test suites are not executing and builds stops. 

I found this - https://github.com/travis-ci/travis-ci/issues/5700 I guess the same problem what I am facing right now.

**Comment by kjnanda** [comment]
Hi @BanzaiMan,
The problem has been fixed now. I have managed to reduce the execution time. As per my conversation with @iriberri `Travis CI has specific time limits for each job, and by default, a job that takes longer than 50 minutes on travis-ci.org will be automatically stopped.
`
closing this issue.

**Comment by BanzaiMan** [comment]
Happy to hear that you were able to resolve the issue.
