### ISSUE TITLE
Firefox Nightly not downloading

### ISSUE THREAD

**Issue by jrbenny35** [travis-ci/travis-ci#7736]
The last revision author forgot to assign the variable ```product``` to the string found here: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/firefox.rb#L81

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by jrbenny35** [comment]
From this line down: https://travis-ci.org/jrbenny35/addons-server/jobs/230538775#L178
