### ISSUE TITLE
commit status on github disappears suddenly

### ISSUE THREAD

**Issue by muwenzi** [travis-ci/travis-ci#7738]
Now , it looks:

![image](https://cloud.githubusercontent.com/assets/12554487/25880908/a757b0f2-356c-11e7-8267-0a22c9ea66dc.png)

 it should show a green hook when it completed successfully

PS: I didn't change my config

Thank you for answering!

**Comment by BanzaiMan** [comment]
Where do you see this?

**Comment by muwenzi** [comment]
@BanzaiMan this is my private repo, but it had green hook before. you can see the commits msg of [react](https://github.com/facebook/react/commits/master), [express](https://github.com/expressjs/express/commits/master) and so on. they had green hook before (I guess, not sure)

**Comment by BanzaiMan** [comment]
Sorry, but there is really no information here to act on. If you would rather discuss this in private, please email us at support@travis-ci.com.

I'm closing this public issue in the mean time.

**Comment by rubo77** [comment]
Did you solve the problem? The green/yellow/red hooks are gone in my public repository too since a few months
