### ISSUE TITLE
Sorry, it seems like we couldn't find any repositories you have access to on GitHub.

### ISSUE THREAD

**Issue by ls-tusimple** [travis-ci/travis-ci#7740]
Hello,

Somehow travis couldn't find any repos that I have access to. Can someone help check?

**Comment by iriberri** [comment]
Hi @ls-tusimple. Are you having these issues with private repositories in your ls-tusimple account? If so, could you please drop us a line at support@travis-ci.com so that we can check your specific case?

Thanks!

**Comment by BanzaiMan** [comment]
Please ensure that the organizations you are concerned with allows third-party access. https://help.github.com/articles/about-third-party-application-restrictions/

At the moment, I'm closing this.
