### ISSUE TITLE
Storage to persist earlier matrix items build output to make it accessible for later jobs

### ISSUE THREAD

**Issue by vb216** [travis-ci/travis-ci#7741]
Hi,

I'm stuck with a build scenario that I can't find a solution for. We build quite a number of project subitems to target multiple OS's (https://travis-ci.org/vb216/javacpp-presets). For some of these, there is an interdependency on jars from previous items, currently solved by specifying multiple subprojects in one line in the matrix (e.g. opencv, chilitags, flandmark, openblas, mxnet.. ). But as that dependency chain gets longer, we're going past the max runtime, and so it seems sensible to split this out into individual matrix items. But, then a later item can't find an earlier items build output jar files. 

Options I've looked at:
- Cache .m2, so earlier built jars are accessible to later dependencies. Doesn't look to work, as cache is unique per matrix item, and in various discussions there doesn't seem a way around to force this, due to concern it could corrupt cache (I'd be happy to run with no job concurrency to get around that though).
- Upload build items externally, and later jobs grab that output. Sticking point here would be that PR's couldn't use any encrypted vars, that would be needed to access the external location. I thought S3 looked a good contender to for this, and just run a sync before and after each matrix item. But as people develop on forks, I can't see a way around this problem. I did wonder about just limited down access the credentials would give (read-write on a given folder), and then limited access to Travis IP range if that's feasible. But it doesn't feel a great solution either.

I wondered if this scenario has cropped up before, it doesn't feel especially unique? Are there any other options, or ways around the above limits?

Thanks

**Comment by BanzaiMan** [comment]
We will announce the new "build stages" feature soon, which I believe address this use case. https://github.com/travis-ci/beta-features/issues/11

Keep your eyes on https://blog.travis-ci.com/ for announcement.

**Comment by vb216** [comment]
Awesome! Looks like just what I need. 

Thanks!
