### ISSUE TITLE
Ruby 1.9.2 fails on Precise

### ISSUE THREAD

**Issue by segiddins** [travis-ci/travis-ci#7743]
See https://travis-ci.org/rubygems/rubygems/jobs/230818251, resulting in:

```
$ rvm use 1.9.2 --install --binary --fuzzy
ruby-1.9.2 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-1.9.2 do rvm gemset create ' first, or append '--create'.
```

**Comment by BanzaiMan** [comment]
Do you need `sudo`?

**Comment by segiddins** [comment]
Yes

**Comment by BanzaiMan** [comment]
Is Trusty an option for you? I could not convince RVM to install and use the 1.9.2 archive. It is possible with manual intervention, but it requires manual intervention before any customization can kick in.

See https://github.com/rubygems/rubygems/pull/1920.

**Comment by BanzaiMan** [comment]
I'm closing this now. If anyone else needs a 1.9.2, please use Precise.
