### ISSUE TITLE
Unable to deploy: sh: 1: Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by bkuhl** [travis-ci/travis-ci#7745]
* **.travis.yml** - https://github.com/bkuhl/game-watcher/blob/master/.travis.yml#L20
 * **travis log output** - https://travis-ci.org/bkuhl/game-watcher/builds/230863975#L1136

I'm unable to release new versions of an open source project.  I made a [minor code change](https://github.com/bkuhl/game-watcher/commit/bdd3bbb3d8beb5665cbb0cac515c8bf4d02032e1) to the frequency of some scheduled work within my application.  The build is now failing in the deployment phase indicating there's a syntax error in a shell script.  I believe this error is related to Travis-CI, not my code.

**Comment by bkuhl** [comment]
Evidence of this working in the past can be found at https://hub.docker.com/r/bkuhl/game-watcher/tags/.  All of these images were built with this configuration.

**Comment by BanzaiMan** [comment]
Your "script" value is not meeting this criterion in https://docs.travis-ci.com/user/deployment/script:

> `script` must be a scalar pointing to an executable file or command.

Try enclosing the entire `cmd1 && cmd2 && …` into a single string, or put it in a script (and make the script executable).

**Comment by BanzaiMan** [comment]
Hmmm. It was working here: https://travis-ci.org/bkuhl/game-watcher/builds/228097925#L1125

**Comment by BanzaiMan** [comment]
The difference: https://github.com/travis-ci/travis-build/compare/b58bfffaa...e06d2d8c7

Deployment hasn't changed, and the `dpl` versions are identical, so I suppose this might be an issue with the filter.

We'll investigate.

**Comment by BanzaiMan** [comment]
Still investigating.

**Comment by BanzaiMan** [comment]
The script indeed has an unterminated string. See https://github.com/bkuhl/game-watcher/pull/6 for a fix.

I'm closing this.
