### ISSUE TITLE
Yarn default install for Ruby Projects

### ISSUE THREAD

**Issue by Oneill38** [travis-ci/travis-ci#7747]
In Rails 5.1 yarn is included by default. For ruby projects it would be nice if we didn't have to install it every time, and it was already included as it is for Node projects on Travis.

**Comment by olivierlacan** [comment]
@BanzaiMan Any news on this. Rails 5.1 shipped several weeks ago now and it seems like the only way to get Yarn support for Ruby apps is to install Yarn manually.

**Comment by BanzaiMan** [comment]
`yarn` should now be available on all images.

**Comment by olivierlacan** [comment]
Thank you @BanzaiMan! :-)
