### ISSUE TITLE
Build stages & matrix issue

### ISSUE THREAD

**Issue by popravich** [travis-ci/travis-ci#7749]
Hi guys! This is related to https://github.com/travis-ci/beta-features/issues/11

I've just started to playing with it and have got an issue with build matrix:
I have a several Python version in my build matrix, so generating multiple test-stage jobs.
Adding another stage without explicitly set python key generates a single job with all python version values collapsed into single value.
Here's the build — https://travis-ci.org/aio-libs/aioredis/builds/231530766

**Comment by BanzaiMan** [comment]
What value of `python` do you expect to be set in these builds https://travis-ci.org/aio-libs/aioredis/jobs/231530771 https://travis-ci.org/aio-libs/aioredis/jobs/231530775?

There is no `python` value set in each of these jobs, so it is inherited from the top level of the configuration, which is:

```yaml
python: ["3.3", "3.4", "3.5", "3.6"]
```

**Comment by popravich** [comment]
Well, I assumed it should be similar behavior with default `test` stage — to generate a job for each python value for `flake8` and `run examples` stages (if not exlicitly defined `python` in that stage job).

**Comment by BanzaiMan** [comment]
The default value for `stage` comes through when there is no `stage` set in the top level. If you [do](https://github.com/BanzaiMan/travis_production_test/blob/a9dd15e93b6c6cbee89e301cf3dfb9b84d2831e3/.travis.yml), you would see that value come through (https://travis-ci.org/BanzaiMan/travis_production_test/builds/231582343).

If you do not define `python` on the top level, you'd get the default value in any job you define.

While it would be instructive to warn upon seeing obviously incorrect `python` value, the build itself is behaving as described in `.travis.yml`.

**Comment by popravich** [comment]
Ok, now it is clear.
I think there should be some notes in docs on the case when top-level build matrix generate
multiple jobs based on language version and/or env values and `jobs.include` does not override those values.
