### ISSUE TITLE
Unable to start PHP embedded web server : Address already in use

### ISSUE THREAD

**Issue by seblucas** [travis-ci/travis-ci#7750]
Hi,

I use travis on my PHP project on Github. In the end of the script I start the PHP embedded web server to test it with Saucelabs.

It started failing with this error 20 days ago (and failed everytime ever since) :
```
[Fri Apr 21 10:00:18 2017] Failed to listen on 127.0.0.1:8888 (reason: Address already in use)
```

My `.travis.yml` is here : https://github.com/seblucas/cops/blob/master/.travis.yml
The command line I use to start the PHP webserver is here : https://github.com/seblucas/cops/blob/master/test/prepareSauceTest.sh#L35

The last build were it worked is here (28 days ago) : https://www.travis-ci.org/seblucas/cops/jobs/222024736#L522-L523
and the first failing build is there (21 days ago) : https://www.travis-ci.org/seblucas/cops/jobs/224287892#L507

Nothing has changed on my end. Is there some specific port that are reserved (is 8888 a bad port) ?

Thanks in advance.

**Comment by BanzaiMan** [comment]
No process should be bound to this non-standard port. Try checking which process is listening on the port:

```
ruby -rsocket -e 'TCPSocket.new("localhost",8888)'
```

There may be an equally quick way to check it with PHP, but I do not know that.

My quick check with the PHP images show that there is no process that meets this criterion by default.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/231599553

**Comment by seblucas** [comment]
I changed the port 8888 to 8080 and everything is fine. I'll try to check which program was listening to that port but you can close the issue if you prefer.

Thanks a lot.

**Comment by BanzaiMan** [comment]
To actually see the process, you'd need to use `lsof -P`. To see processes not owned by you, then you'd need `sudo lsof -P`.

Let us close this for now, unless you find something that we should fix.

Thanks.
