### ISSUE TITLE
Latest PHP releases cannot be used with Travis CI

### ISSUE THREAD

**Issue by ottlinger** [travis-ci/travis-ci#7751]
Similar to #7377 the latest releases of PHP are not available:
* 7.0.19
* 7.1.5

Is it possible to automate using latest releases of PHP with Travis?
http://php.net/

Thanks

**Comment by BanzaiMan** [comment]
We are waiting for https://github.com/php-build/php-build/pull/439 to be merged so that we can build them.

**Comment by BanzaiMan** [comment]
7.0.19 https://travis-ci.org/travis-ci/php-src-builder/builds/231727359
7.1.5 https://travis-ci.org/travis-ci/php-src-builder/builds/231727396

**Comment by ottlinger** [comment]
Works perfectly, thanks @BanzaiMan :-)
