### ISSUE TITLE
Data do not persist between stages

### ISSUE THREAD

**Issue by shazChaudhry** [travis-ci/travis-ci#7753]
I have a simple usecase where I would like to clone a git repo _(SCM stage)_, Build a maven based project _(Build stage)_ and then run quality gates _(SonarQube)_. However, it appears Travis does not persist data between stages. 
* [.travis.yml on github
](https://github.com/shazChaudhry/spring-petclinic/tree/54a906f35de1779bc27cf6bfd5f381870de0d335)
* [Build stages on travis-ci
](https://travis-ci.org/shazChaudhry/spring-petclinic/builds/231664964) 

I will be grateful for any suggestions on how a cloned git repo into a docker volume (SCM stage) can be made available to a Build stage

**Comment by BanzaiMan** [comment]
Hello. The document does not make it clear, but, indeed, the storage does not persist between stages. We do have a few examples of pseudo-persistence via [shared cache](https://docs.travis-ci.com/user/build-stages#Warming-up-a-cache-with-expensive-dependencies), [S3](https://docs.travis-ci.com/user/build-stages#Sharing-files-between-jobs-via-S3), [Docker image](https://docs.travis-ci.com/user/build-stages#Sharing-a-Docker-image).

This lack of storage persistence should be more explicit in the [document](https://docs.travis-ci.com/user/build-stages).
