### ISSUE TITLE
New lines in build output not being interpreted correctly when using ECMA-48 colour codes

### ISSUE THREAD

**Issue by DX-MON** [travis-ci/travis-ci#7755]
During the unit testing phase of several of my builds, I use a unit testing framework which uses Linux's support for ECMA-48 colour codes to make the test output easier to read, if it detects it's outputting to a TTY.

It very clearly does think it's connected to a TTY as evidenced by https://travis-ci.org/DX-MON/crunch/jobs/226147748 however, as also seen here, new lines in that section of the output are being ignored completely, causing the output to get bunched up.

The framework specifically uses only "\n" sequences for new lines, which is interpreted correctly on a real terminal (implied return to start of line on line feed).

**Comment by BanzaiMan** [comment]
Which lines are supposed to have newlines?

**Comment by BanzaiMan** [comment]
Some escape sequences look like:

```
[0;39mAssertion failure: expected (nil), got 0x3e4dcdfe[0;39m[1A[s[1B
[1A[0G[72G[1;34m[[1;31m FAIL [1;34m][0;39m[1A[s[1B
[0;39mAssertion failure: expected (nil), got 0x3e4dcdfe[0;39m[1A[s[1B
[1A[0G[72G[1;34m[[1;31m FAIL [1;34m][0;39m[1A[s[1B
[0;39m[1A[0G[72G[1;34m[[1;32m  OK  [1;34m][0;39m[1A[s[1B
[1;36mtestAssertNotNull...[0;39m[1A[s[1B
```

Why is there a `]` (e.g., `[1;32m]…`. I don't think that's valid. Also, I see `[s`, which I suppose is "Scroll up", which is not supported in our stream-oriented log display. See #1927, #1933, etc.

**Comment by DX-MON** [comment]
Hi @BanzaiMan
Lines 424 through 435.. even if ignoring the scroll up.
If that code was not detecting a TTY then it would not be outputting the colourisation sequences - which would be fine - but the new lines are being ignored there. There are new lines both before the ok/fail []'s and immediately after.

And yes, ] is valid in that context - it's part of the colour code sequence. $PS1 frequently also uses it in the same context.

**Comment by BanzaiMan** [comment]
Those lines do contain `\033[s`.

```
[1;35mRunning test suit testArgsParser...[0;39m[1A[s[1B
[1;36mtestNull...[0;39m[1A[s[1B
[0;39m[1A[0G[72G[1;34m[[1;32m  OK  [1;34m][0;39m[1A[s[1B
[1;36mtestEmpty...[0;39m[1A[s[1B
[0;39m[1A[0G[72G[1;34m[[1;32m  OK  [1;34m][0;39m[1A[s[1B
[1;36mtestIncomplete...[0;39m[1A[s[1B
[0;39m[1A[0G[72G[1;34m[[1;32m  OK  [1;34m][0;39m[1A[s[1B
[1;36mtestInvalid...[0;39m[1A[s[1B
Duplicate argument found: --arg
[0;39m[1A[0G[72G[1;34m[[1;32m  OK  [1;34m][0;39m[1A[s[1B
[1;36mtestArgCounting...[0;39m[1A[s[1B
Not enough parameters given for argument -a
[0;39m[1A[0G[72G[1;34m[[1;32m  OK  [1;34m][0;39m[1A[s[1B
[1;35mRunning test suit testCrunch...[0;39m[1A[s[1B
[1;36mtestAssertTrue...[0;39m[1A[s[1B
[0;39mAssertion failure: expected true, got false[0;39m[1A[s[1B
[1A[0G[72G[1;34m[[1;31m FAIL [1;34m][0;39m[1A[s[1B
[0;39m[1A[0G[72G[1;34m[[1;32m  OK  [1;34m][0;39m[1A[s[1B
[1;36mtestAssertFalse...[0;39m[1A[s[1B
```

**Comment by BanzaiMan** [comment]
If you are concerned purely of color support, I think this is a duplicate of #6752.

**Comment by DX-MON** [comment]
Hi @BanzaiMan - I'm not concerned about colour support and I specifically said ignoring the scrolling commands (which would only cause the "[ FAIL ]" and "[  OK  ]" to appear on the same line as the test or assertion that caused it). I'm concerned that the new lines embedded in that output are being ignored - there's a new line after everu \033[1A\033[s\033[1B which is being ignored, and even after the end of the FAIL/OK output.

The scroll and restore sequences could be stripped (and by the sounds of things, should be by the Travis log reader engine) and that should have no effect other than where the FAIL/OK output is displayed in the log output.

Rather than the lines being bunched up, I should be seeing each of the distinct lines as above, as discrete lines in the main build log output (not the raw, the interpreted).

**Comment by DX-MON** [comment]
I've just tried simplifying the escape sequences code to see if it fares any better with only one \033[1A\033[72G sequence and no \033[s and \033[1B sequences. Results are available in build 70 - https://travis-ci.org/DX-MON/crunch/builds/232545177

**Comment by BanzaiMan** [comment]
OK. You are right about `\033[s`. I was confusing that with `\033[S`.

Anyhow, certain escape sequences such as `\033[s` appears to be interfering with the log display. https://travis-ci.org/DX-MON/crunch/jobs/232545181 seems to back up this hypothesis.

**Comment by DX-MON** [comment]
Aye. I think it would be best if the sequences were ignored rather than being incorrectly interpreted like that..

At least for crunch, the saving and scrolling is generally not necessary as it is designed around going back to the end of the previous line to append the pass/fail markers; but it's not unreasonable to output such sequences in a ncurses type environment to do much more complex displays as part of the captured output.
