### ISSUE TITLE
Where can I find the default `install` and `script` commands executed for `language: r` builds?

### ISSUE THREAD

**Issue by stephlocke** [travis-ci/travis-ci#7756]
After an hour googling and searching repos, I give up! I'd like to see the default commands that the travis-ci build will do for R builds to determine where best to add additional build stages (like before_script) or to override the default activities.

Would you be able to tell me where I can find the default script and/or install steps?

It might be a useful thing to have contained in, or linked to, in the R travis-ci docs for future reference.

 @craigcitro, @hadley,  @jimhester

**Comment by jimhester** [comment]
Remember the first rule of finding source code, search for a unique message by what you are looking for e.g ["mention @craigcitro and @jimhester in the issue"](https://github.com/search?utf8=%E2%9C%93&q=%22mention+%40craigcitro+and+%40jimhester+in+the+issue%22&type=Code).

https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb

**Comment by jimhester** [comment]
Also basically what the default steps do is

```shell
# install
R -e 'devtools::install_deps(dep = T)'

# script
R CMD build .
R CMD check *tar.gz
```

**Comment by stephlocke** [comment]
Thank you @jimhester - I'd looked up a bunch of code lines & commits mentioned in the logs but didn't look that one up. I even looked up Craig and started going through his commit history, not realising that you were the main contributor to the facility these days.

Is it worth having a link to that in the docs so that others can find it more easily? Not sure how much call there is to see it but it might help people debug before having to raise issues.

**Comment by craigcitro** [comment]
(late to the party)

I'd be 👍 on adding a note to the docs with a pointer to the install/script steps, unless @jimhester has an objection.

**Comment by jimhester** [comment]
Feel free!
