### ISSUE TITLE
.NET Core builds on Mac fail to find .NET Core 2.0 preview installer

### ISSUE THREAD

**Issue by powellcj12** [travis-ci/travis-ci#7757]
Link to relevant job: https://travis-ci.org/powellcj12/TwilightImperium.CLI/builds/231867193

The Linux build succeeded just fine, but the Mac build failed to find the installer:
```
$ wget --retry-connrefused --waitretry=1 -O /tmp/dotnet.pkg https://dotnetcli.azureedge.net/dotnet/preview/Installers/2.0.0-preview1-005977/dotnet-dev-osx-x64.2.0.0-preview1-005977.pkg
--2017-05-13 13:22:37--  https://dotnetcli.azureedge.net/dotnet/preview/Installers/2.0.0-preview1-005977/dotnet-dev-osx-x64.2.0.0-preview1-005977.pkg
Resolving dotnetcli.azureedge.net... 72.21.81.200, 2606:2800:11f:17a5:191a:18d5:537:22f9
Connecting to dotnetcli.azureedge.net|72.21.81.200|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-05-13 13:22:37 ERROR 404: Not Found.


The command "wget --retry-connrefused --waitretry=1 -O /tmp/dotnet.pkg https://dotnetcli.azureedge.net/dotnet/preview/Installers/2.0.0-preview1-005977/dotnet-dev-osx-x64.2.0.0-preview1-005977.pkg" failed and exited with 8 during .
```

cc @joshua-anderson @akoeplinger @nterry

**Comment by powellcj12** [comment]
I see - the regex to download and install on Mac assumes a major version of 1. From https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/csharp.rb:
```ruby
DOTNET_VERSION_REGEXP = /^\d{1}\.\d{1,2}\.\d{1,2}(?:-(?:preview|rc)\d+(\.\d+)?(?:-\d)?-\d{6})?$/
```

I can try to get a PR submitted with a fix.

**Comment by BanzaiMan** [comment]
You are [specifying a preview version](https://github.com/powellcj12/TwilightImperium.CLI/blob/ded9a8fb3e56c178b453602700622dda87448f38/.travis.yml#L4) that does not exist. Where did you find this?

**Comment by powellcj12** [comment]
https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview1-download.md

**Comment by powellcj12** [comment]
I figured it out - Microsoft (seemingly) isn't hosting them under the ```dotnet/preview/Installers/``` but rather just ```dotnet/Sdk/``` like the non-preview versions. This worked locally for me:
```
wget --retry-connrefused --waitretry=1 -O /tmp/dotnet.pkg https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005977/dotnet-dev-osx-x64.2.0.0-preview1-005977.pkg
```

**Comment by powellcj12** [comment]
The dotnet/cli repo maintains some [install scripts](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh) which seem to work for this most recent preview release, but not for older (v1.X) preview releases presumably because of the same issue - their install script looks at ```dotnet/Sdk/``` but never ```dotnet/preview/Installers/```

**Comment by JustArchi** [comment]
Bump, could we do something with that? It's just a matter of link change, it can even be as stupid as hardcoding old link if `dotnet` version starts from `1.0`, but new link is absolutely needed for (now second) preview of .NET Core 2.0.

**Comment by JustArchi** [comment]
I can confirm this is now fixed and can be closed @BanzaiMan
