### ISSUE TITLE
Add the ability to filter build stages to certain branches

### ISSUE THREAD

**Issue by alexwlchan** [travis-ci/travis-ci#7758]
The new Build Stages look useful, but I’d like to be able to restrict some stages to particular branches.

My use case: in [hypothesis](https://github.com/HypothesisWorks/hypothesis-python/), we have a "deploy" job in our Travis matrix that tags a new release and uploads to PyPI. To avoid this running on every pull request, the script has some logic to detect:

1. Is this job running on master?
1. Have all the other jobs finished yet? (By querying the Travis API)

I can enforce (2) by putting the "deploy" job in a separate build stage, but I don't think I can do (1). It would be nice if I could say "only ever run the deploy step on master" – so the Travis UI never even shows me the deploy stage if I'm on a feature branch.

There's already:

```yml
branches:
  only:
    - master
```

to restrict pushes to only run on master. How about something like that for Build Stages?

(I feel like this is a common use case, but I haven’t seen another issue for it yet.)

**Comment by BanzaiMan** [comment]
This is a variation of #7149. I'm closing this as a duplicate.
