### ISSUE TITLE
Add `--jobs` parameters to git.submodule initializing 

### ISSUE THREAD

**Issue by sinoru** [travis-ci/travis-ci#7763]
How about adding `--jobs` parameters to git.submodule initializing for parallel fetching submodules. Like bundler maybe set it as 3 for default, and configurable in git config?

Like:
```yaml
git:
    submodule_jobs: 3
```

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/common-build-problems/#Git-Submodules-are-not-updated-correctly

You can disable the default `git submodules` call and add your own in `before_install`.

**Comment by sinoru** [comment]
Ah right.. That must be possible. Thanks.
