### ISSUE TITLE
Cant overwrite a existed file during deploy to github release

### ISSUE THREAD

**Issue by supercoderhawk** [travis-ci/travis-ci#7766]
when I set deploy to github using maven with tag,  build success but the following log show:

```
Deploying application.
XXX.jar already exists, skipping.
```

The tag was forced retagged so there is a previous deployed release, can travis support to force to overwrite the previous deployed release file, so I cant necessary to upload it manually.

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/deployment/releases

> If you need to overwrite existing files, add `overwrite: true` to the `deploy` section of your `.travis.yml`
