### ISSUE TITLE
unable to migrate to container based image

### ISSUE THREAD

**Issue by vb216** [travis-ci/travis-ci#7768]
I've removed all trace of sudo calls, and set sudo: false in the yaml file, thinking this would shift on to the container based approach - as I want to whitelist IP addresses for another service. But, the IP address that comes through looks like its running from google compute. Am I missing something? I guess there's no constant IP address possible if its running from there?

Example job here
https://travis-ci.org/vb216/javacpp-presets/jobs/232773374

**Comment by BanzaiMan** [comment]
https://github.com/vb216/javacpp-presets/blob/36a16d5bfffcc27cd7648de3ac13bdb21770a93a/.travis.yml#L19-L20

The use of Docker sends the jobs to GCE. This is documented in https://docs.travis-ci.com/user/docker/. Your build clearly relies on its presence, so you can't move to containers.

Thanks.
