### ISSUE TITLE
Build failing on "npm install -g firebase-tools"

### ISSUE THREAD

**Issue by Sfshaza** [travis-ci/travis-ci#7770]
I performed multiple commits yesterday with no problems, then the build began failing consistently. 

The fail occurs on "npm install -g firebase-tools". I can run that command locally with no problem. 

https://travis-ci.org/dart-lang/site-www/builds/232626321?utm_source=github_status

**Comment by BanzaiMan** [comment]
This looks like an issue with your repository: https://travis-ci.org/dart-lang/site-www/builds/232626321#L264

> npm ERR! 404 'google-cloud/functions-emulator' is not in the npm registry.

It appears that that either Node.js ([0.10.36](https://travis-ci.org/dart-lang/site-www/jobs/232626322#L274)) or npm([1.4.28](https://travis-ci.org/dart-lang/site-www/jobs/232626322#L275)) (or both) is outdated to handle the module specification you are using.

**Comment by Sfshaza** [comment]
Thanks, @BanzaiMan, it turns out that npm was being updated and was breaking the build.  We've fixed it:  https://github.com/dart-lang/site-www/pull/276

Thanks!
