### ISSUE TITLE
How to launch Docker in Mac OS X?

### ISSUE THREAD

**Issue by yitam** [travis-ci/travis-ci#7773]
Hi, I've been searching high and low on this. We've been satisfied with the Linux env, and now we want to add Mac OS X for our testing. Unlike Linux, Docker is not available, so after some research, this `brew cask install docker` works. I even got the message `docker was successfully installed!`

So far so good, but how do I launch Docker? FYI, this is the latest attempt in my private [repo](https://travis-ci.org/yitam/msphpsql/jobs/233039803)

Any documentation or comment is much appreciated. Thanks!

**Comment by BanzaiMan** [comment]
Thanks for taking time to open the issue. Unfortunately, we do not support running Docker at this time. If you need Docker, please use Linux. See also #5738.

**Comment by nsidhaye** [comment]
@BanzaiMan #5738 is closed saying 

> do not support the use of VirtualBox inside on our builds on either OSX or Linux. So using Docker on OSX is not something we can support.

while docker already launch `Docker for Mac` and also having community edition. https://www.docker.com/docker-mac 

Any plans for releasing docker on mac on travis?

**Comment by BanzaiMan** [comment]
Sorry, but there is no plan at the moment.

**Comment by adamtheturtle** [comment]
@BanzaiMan 

> Thanks for taking time to open the issue. Unfortunately, we do not support running Docker at this time. If you need Docker, please use Linux. See also #5738.

I understand that there is no plan and that is fine but "please use Linux" is not a complete solution. There are differences between Docker for Mac and Docker on Linux, and it would be useful to test my code on macOS. Right now I have untested code and instructions for `coverage.py` to ignore particular lines.

**Comment by vikpande** [comment]
@BanzaiMan , do you have an ETA on this one yet or is it a decision/choice not to have it for OSX.

**Comment by BanzaiMan** [comment]
We apologize, but there is no plan to work on this feature. I understand that there are differences between Docker on different platforms, but we are currently unable to explore the feature to offer it to our users.

Thanks.
