### ISSUE TITLE
The job exceeded the maximum time limit for jobs, and has been terminated.

### ISSUE THREAD

**Issue by dshames** [travis-ci/travis-ci#7774]
Hey,

this is a link for our log:
https://travis-ci.org/TechnionYP5777/SmartCity-ParkingManagement

the error we got was:
"The job exceeded the maximum time limit for jobs, and has been terminated."

I have read that there is a 50 min limit.
This is a public, non-profit university project for studying purposes only.
Is there any way we could get a more extended time limit?

**Comment by BanzaiMan** [comment]
Take a look at https://docs.travis-ci.com/user/speeding-up-the-build for suggestions.

**Comment by BanzaiMan** [comment]
I'm closing this for now.
