### ISSUE TITLE
java.net is down, oracle-java9-installer package is broken, SonarQube can not be used.

### ISSUE THREAD

**Issue by LebedevRI** [travis-ci/travis-ci#7778]
https://travis-ci.org/darktable-org/rawspeed/jobs/232085837#L1315

**Comment by BanzaiMan** [comment]
Does the error persist if you restart it?

**Comment by LebedevRI** [comment]
I wouldn't have reported it if the fix was that simple :)
Yes, the error does not magically fix itself by the job restart.
TBN, [java.net](https://java.net) is down for some time now, at least a few days.

**Comment by BanzaiMan** [comment]
Very well. At the moment, then, you will have to wait until the external resources are available.

**Comment by cpence** [comment]
Not just that, though, java.net [is *permanently* down.](http://www.oracle.com/splash/java.net/maintenance/index.html)

We need whoever is responsible for those oracle-*-installer packages to update the package URLs.

**Comment by BanzaiMan** [comment]
Oh, I see. The packages are maintained by http://www.webupd8.org/. (https://launchpad.net/~webupd8team/+archive/ubuntu/java).

**Comment by chrisalice** [comment]
Is there no alternative available for this yet? It's been two months 😢

**Comment by BanzaiMan** [comment]
@chrisalice Is `jdk: oraclejdk9` not working for you? https://travis-ci.org/BanzaiMan/travis_production_test/jobs/255886575#L422

**Comment by BanzaiMan** [comment]
Or, are you reporting the SonarQube issue?

**Comment by BanzaiMan** [comment]
Ah, I see. Webupd8 team's package has not been fixed. `oraclejdk9` should be available on Trusty images, though.

**Comment by chrisalice** [comment]
@BanzaiMan Thanks for the pointer. I'm trying to run with both JDK 8 and JDK 9 in a single build, though, but this seems to give me two separate build jobs: https://travis-ci.org/google/FreeBuilder/builds/255889005 ?

**Comment by chrisalice** [comment]
Oh, I was being dumb. `jdk_switcher home oraclejdk9` just works reliably now, and I can remove the addons section. Thanks!

**Comment by BanzaiMan** [comment]
This should be OK now.
