### ISSUE TITLE
Deprecate support for non-configured ruby projects

### ISSUE THREAD

**Issue by g2p** [travis-ci/travis-ci#778]
It's not documented anymore, but Travis has implicit support for ruby projects that don't have a .travis.yml file. That support has unintended consequences that are undesirable. For example, branches that don't contain a Rakefile will trigger failed builds.

Such support should be clearly deprecated. This would create an "explicitly configured" project status. Travis should consider a new project unregistered until the first time it sees a .travis.yml file in a push notification. From that point on, the project is marked "explicitly configured", and only push notifications that contain a .travis.yml should be built. Projects that have been successfully built without a .travis.yml file in the past may be grandfathered in, but should be converted to "explicitly configured" projects the first time Travis receives a push notification containing a .travis.yml file.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
