### ISSUE TITLE
Wrong version of libusb-1.0 for Xenial

### ISSUE THREAD

**Issue by Nhoya** [travis-ci/travis-ci#7783]
Apparently the package `libusb` on Xenial is outdated, the version is still `1.0,9-rc3`, while Xenial actually supports `1.0.17`
``` trusty (14.04LTS) (libs): userspace USB programming library
     2:1.0.17-1ubuntu2: amd64 arm64 armhf i386 powerpc ppc64el```

**Comment by BanzaiMan** [comment]
Thanks for taking time to open this issue.

However, as we do not support Xenial at this time (https://github.com/travis-ci/travis-ci/issues/5821), you are probably using Precise still. This explains why the package is outdated.

Try Trusty, which may provide you with temporary relief until Xenial is available.

Thanks.
