### ISSUE TITLE
Travis is looking for rakefile while is a golang repo

### ISSUE THREAD

**Issue by Nhoya** [travis-ci/travis-ci#7784]
As you can see here https://travis-ci.org/nsaway/eventnotifier/builds/232638829
travis is looking for a rakefile but actually the project language is `go`
https://github.com/nsaway/eventnotifier/blob/travis/travis.yml

**Comment by BanzaiMan** [comment]
There is no `.travis.yml`, only `travis.yml`.

**Comment by BanzaiMan** [comment]
Please rename it.
