### ISSUE TITLE
clang, cannot include <random>

### ISSUE THREAD

**Issue by jpritikin** [travis-ci/travis-ci#7787]
Both xcode8.3[^](https://travis-ci.org/OpenMx/OpenMx/jobs/234012986) and xcode7.3[^](https://travis-ci.org/OpenMx/OpenMx/jobs/234018023) fail with `Compute.cpp:22:10: fatal error: 'random' file not found`

I am able to build this code on Travis if I install gcc from http://prdownloads.sourceforge.net/hpc

CRAN is able to build this package with Xcode 8.2.1, clang 4.0.0, GNU Fortran 6.1 [although the resulting binary is not entirely working](https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/OpenMx-00check.html).

What's going on with the \<random\> include? Any ideas?

**Comment by BanzaiMan** [comment]
Is this an R build? If so, please mention @craigcitro and @jimhester for R inquiries, as indicated in the build log.

Either way, please include a build log URL that shows your problem.

Thank you.

**Comment by jpritikin** [comment]
> Is this an R build?

Yes, @craigcitro @jimhester

> Either way, please include a build log URL that shows your problem.

The build logs are linked in my original report (see the links in xcodeY.Y^).

**Comment by jimhester** [comment]
I think you need to explicitly link to clang's standard library for this to work see (http://blog.michael.kuron-germany.de/2013/02/using-c11-on-mac-os-x-10-8/). CRAN started doing this as of 3.4.0, which is likely why it is working there.

`-stdlib=libc++ -lc++`

**Comment by jpritikin** [comment]
OK, I added to Makevars,

```
CXX11FLAGS=-stdlib=libc++ -g -O2
CXX11STD=-lc++

```

but this [failed](https://travis-ci.org/OpenMx/OpenMx/jobs/234043522) with `clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)`. Can you recommend specific Makevars options or do I need to random-walk a bit?

**Comment by jimhester** [comment]
I don't have any other suggestions, sorry.

**Comment by jpritikin** [comment]
OK, I guess I'll close this for now.

**Comment by tbates** [comment]
the  [kuron](http://blog.michael.kuron-germany.de/2013/02/using-c11-on-mac-os-x-10-8) blog says that OS X 10.9 and subsequent default to libc++ and don’t require the extra compiler flag...

But the error certainly suggests lack of access to random, as if the old std library was being called. Not sure if CRAN started doing this as of 3.4.0, or if it is an Apple bug in 10.12?
