### ISSUE TITLE
"Debug job" for public repository from commercial travis-ci.com account

### ISSUE THREAD

**Issue by headupinclouds** [travis-ci/travis-ci#7788]
Is it possible to use the "debug job" feature for a public repository forked to an account associated with a commercial travis-ci.com account?  Any pointers to documentation for this feature would be appreciated.  Thanks.

**Comment by BanzaiMan** [comment]
Any private repository should have debug button accessible from the log page, if you have push access to that repository.

We have the documentation PR at https://github.com/travis-ci/docs-travis-ci-com/pull/1182.

**Comment by headupinclouds** [comment]
Thanks.  Direct link: https://github.com/travis-ci/docs-travis-ci-com/blob/8f1731981728d2faccb1b7bcc1cecd41a9082bf2/user/using-debug-vm.md

Since I have a commercial travis account, it was easiest to clone/duplicate the public fork (required to changes status to private), which enabled the "debug job" icon.  

For the record, public repositories can be debugged (as outlined in the doc above), but it requires a little more `ssh` tinkering.  I'll try that in the future.
