### ISSUE TITLE
Add generic URL option for status png to make forking readmes on github display correct repo

### ISSUE THREAD

**Issue by DavidJFelix** [travis-ci/travis-ci#779]
Feature request:

The current status icon is great for many things, but has its own issues within github.

Say I have a project and the readme has a reference to the status icon, http://travis-ci.org/DavidJFelix/example.png . John Doe forks my project and does a bunch of work, but his readme points to my status icon, regardless of whether or not he has travis-ci setup. This can mean inaccurate information is displayed. This means that perhaps John will need to ignore certain parts when pushing/pulling and make use of filter-branch more frequently. 

Say for another example that I'm a travis-ci zealot and I'm telling a friend how helpful travis-ci can be for projects! I see his project sitting out on github and I think "I know! I'll just patch travis-ci support for him, and all he has to do is turn it on in the admin panel". If I send him a pull request, I have to either set up a hard address for him to pull (this can be further complicated if my friend is organization, and the person who turns on travis could be any admin member of the group).

My proposal is to expand the current controller that handles status images to accept a static route (perhaps travis-ci.org/status_img.png) and check the referer URL. If the URL doesn't exist or can't be linked to a travis user/repo - it reports unknown status. If it parses as a github repository and can be found as a linked repository, display the icon! That way forks can immediately reflect build status.

This could also be expanded to be more reliable. The current solution proposed could be unreliable if the client doesn't report referer url or if an outside site strips the readme for internal documents. In these cases, perhaps the github hooks api could be used to make travis aware of forks that exist/the network graph. This is only really necessary if the referer url proves to be too reliable.

I tried to get help implementing this myself, but I just can't be bothered to learn rails 3 just to implement a 3-10 line pull request - I know it's this simple, but I haven't used rails in years so I can't figure out how. I'll donate $35USD to travis in the name of any person who helps me implement this - regardless of whether the pull request is accepted or not.

**Comment by ilanbiala** [comment]
Has this been implemented in some way?

**Comment by DavidJFelix** [comment]
@ilanbiala nope. Github's "camo" proxy prevents referrer from being passed and therefore the server from detecting where the request is originating.

**Comment by sbelsky** [comment]
And so what? Is is impossible to make directly agreement between travisci and github project teams about communication protocol?

**Comment by DavidJFelix** [comment]
Impossible? No. Infeasible? Yes. Github camo intentionally obfuscates this data to prevent external tracking like what I had initially suggested. While a whitelist position is possible, I'd assume it's unlikely as there are no currently whitelisted services.

**Comment by defunctzombie** [comment]
While camo itself obfuscates the referrer one possible solution is for
github to just add custom headers with the repo and branch info. Since they
make the request knowing this information they can pass it along. This
would require changes to github tho and not camo.
