### ISSUE TITLE
Gravatar link in web UI should use lowercase email.

### ISSUE THREAD

**Issue by DDoSolitary** [travis-ci/travis-ci#7791]
```js
return `https://www.gravatar.com/avatar/${(md5(email))}?s=${size}&d=blank`;
```
https://github.com/travis-ci/travis-web/blob/02d08de8fe9bb603dda729eee070188c9fa7a578/app/services/external-links.js#L27

According to Gravatar's documentation(https://en.gravatar.com/site/implement/hash/), the email address should be converted to lowercase before MD5-ing. So the above code should be something like this:
```js
return `https://www.gravatar.com/avatar/${(md5(email.toLowerCase()))}?s=${size}&d=blank`;
```

**Comment by BanzaiMan** [comment]
Nice! Thanks for pointing this out. Do you mind submitting a patch?

**Comment by DDoSolitary** [comment]
@BanzaiMan PR created.

**Comment by DDoSolitary** [comment]
I thought the PR I submitted should fix the problem that avatars of emails with uppercase letters aren't are always the default one. However, it turned out that I only modified some code which isn't even used (#1135), and the actual code for generating Gravatar IDs is in the `travis-api` repo.

Could you please reopen this issue and I can submit another PR to actually fix the problem.
