### ISSUE TITLE
iOS build: docker service not yet supported?

### ISSUE THREAD

**Issue by wing328** [travis-ci/travis-ci#7793]
I've the following in the .travis.yml config file 
```
sudo: required
language: objective-c
osx_image: xcode7.3
services:
  - docker
```
But seems like docker service is not yet supported in iOS build as the job fails with docker command not found.

Has anyone been able to get docker services running in the iOS build?

**Comment by BanzaiMan** [comment]
Hello. Thanks for taking the time to open this issue. As explained in #5738, this is not something we are looking to support in the near future.

I'm closing this now as a duplicate.

**Comment by wing328** [comment]
@BanzaiMan thanks for the quick reply and pointing me to the right thread.
