### ISSUE TITLE
most recent builds missing logs on https://travis-ci.org/

### ISSUE THREAD

**Issue by kaizhu256** [travis-ci/travis-ci#7794]
attached self-explanatory screen-captures (and url links)

https://travis-ci.org/kaizhu256/node-utility2/builds/234677884
![image](https://cloud.githubusercontent.com/assets/280571/26292327/9705712e-3ee7-11e7-8ba6-606f681ecd0f.png)

https://api.travis-ci.org/jobs/234677885/log.txt?deansi=true
![image](https://cloud.githubusercontent.com/assets/280571/26292330/9beb3dd6-3ee7-11e7-8460-cf2fed3dce3f.png)

**Comment by kaizhu256** [comment]
looks like logs are working now (seems like it was a http redirect problem with your backend ...weird)

https://api.travis-ci.org/jobs/234677885/log.txt?deansi=true

![image](https://cloud.githubusercontent.com/assets/280571/26292824/a6e96006-3eeb-11e7-8fcd-d465366adb40.png)

**Comment by BanzaiMan** [comment]
I suspect that there was a lag in archiving logs.

**Comment by kaizhu256** [comment]
this might be related to https://github.com/travis-ci/travis-ci/issues/6962 (Top part of log cutoff #6962).  i initially had top-part of the log cut off as well.

**Comment by BanzaiMan** [comment]
@kaizhu256 Is this happening in recent builds?

**Comment by kaizhu256** [comment]
not that i have noticed lately.  i'm ok with having this closed and re-opened if it occurs again.

**Comment by BanzaiMan** [comment]
Thanks. Let us know if you see the problems again.
