### ISSUE TITLE
Older Python 2.7 patch version is installed

### ISSUE THREAD

**Issue by Duologic** [travis-ci/travis-ci#7796]
I have to projects with nearly identical .travis.yml files. One runs as expected on the latest patch version of Python 2.7.13, the other runs on an older version Python 2.7.9. The latter also has an older Pip version (Related: https://github.com/travis-ci/travis-ci/issues/7733) which causes the build to fail.

Build project 1 with correct Python version: https://travis-ci.org/vikingco/django-db-locking/jobs/233959290
Build project 2 with older Python version: https://travis-ci.org/vikingco/django-statsd/jobs/234724374

Expected:
```
$ python --version
Python 2.7.13
$ pip --version
pip 9.0.1
```

Actual:
```
$ python --version
Python 2.7.9
$ pip --version
pip 6.0.7 
```

I have searched through the issues but didn't find anything that describes this issue.

As a workaround, I tried updating pip with `pip install -U pip` in .travis.yml, the script continues but breaks a bit later on not finding the pytest 'binary': https://travis-ci.org/vikingco/django-statsd/jobs/234736635

```
/home/travis/.travis/job_stages: line 649: pytest: command not found
```

I'm assuming that the `pytest` issue also relates to having the older Python version.

Can you guys have look what is going on?

Thanks!

**Comment by BanzaiMan** [comment]
If you need a specific version of Python for your tests, please specify it.

```yaml
language: python
python: 2.7.13
⋮
```

The reason for the difference in behavior between the two repositories you mention is explained in https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments; https://github.com/vikingco/django-db-locking was created before the cutoff (2015-01-01), while https://github.com/vikingco/django-statsd is newer.

**Comment by Duologic** [comment]
Alright, thanks for the quick answer.

**Comment by edmorley** [comment]
I think this can be closed?

**Comment by Duologic** [comment]
Sure.
