### ISSUE TITLE
[PHP] Composer degraded-mode

### ISSUE THREAD

**Issue by arcanedev-maroc** [travis-ci/travis-ci#7802]
Hi travis-ci teams,

Today, all my builds fails due to this error:

```
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
```

It works fine yesterday and i've no clue how to solve it. It will be appreciated if you could help me.

You can check my current build: https://travis-ci.org/ARCANEDEV/GeoLocation/jobs/235311342

For more details: https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode

Best regards

**Comment by nbrady-techempower** [comment]
I am having the same issue. PHP builds with composure working yesterday, no changes to those, not working today.

**Comment by arcanedev-maroc** [comment]
Hi again,

The problem was solved by itself ? :thinking:

I'm going to close this issue for the time being.

> I'm going to reopen it if the issue reappeared again.

Cheers 👍
