### ISSUE TITLE
`GLIBC_2.17' not found

### ISSUE THREAD

**Issue by mikewiebe** [travis-ci/travis-ci#7803]
Yesterday we noticed a new Travis issue that we have not seen before.  We have not changed any base requirements in our repo and our builds have been working fine for that past year or so.

```
LoadError:
  /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /home/travis/build/cisco/cisco-network-node-utils/vendor/bundle/ruby/2.2.0/gems/grpc-1.3.4-x86_64-linux/src/ruby/lib/grpc/2.2/grpc_c.so) - /home/travis/build/cisco/cisco-network-node-utils/vendor/bundle/ruby/2.2.0/gems/grpc-1.3.4-x86_64-linux/src/ruby/lib/grpc/2.2/grpc_c.so
```

I am not sure what changed.  I have inspected the build logs and it appears that we are using the same Ubuntu version and installing the same dependencies in each case. 

Good Build: https://travis-ci.org/cisco/cisco-network-node-utils/builds/233751263
Bad Build: https://travis-ci.org/cisco/cisco-network-node-utils/builds/234926067

**Comment by BanzaiMan** [comment]
Could you try disabling the cache (remove `cache` from `.travis.yml`) and try again? If it works, it's probably corrupt cache.

**Comment by mikewiebe** [comment]
@BanzaiMan Thanks for the response.  I tried that but I still see the same failure.

Change Diff: https://github.com/cisco/cisco-network-node-utils/commit/91dea37af6061eccfb75d289ec1acc5cf74d3320

Travis Log: https://travis-ci.org/cisco/cisco-network-node-utils/jobs/235342219

**Comment by BanzaiMan** [comment]
The gem `gprc` was updated from [1.2.5](https://travis-ci.org/cisco/cisco-network-node-utils/jobs/233751264#L239) to [1.3.4](https://travis-ci.org/cisco/cisco-network-node-utils/jobs/235342219#L265). I suspect this is not compatible with your setup.

**Comment by mikewiebe** [comment]
@BanzaiMan Good call.  I missed that in the logs.

Thanks for your help!  I just updated my GemFile to use version 1.2.5 and all is well.
