### ISSUE TITLE
Deploy GitHub release to a different repository

### ISSUE THREAD

**Issue by ErmanSayin** [travis-ci/travis-ci#7805]
Hello, I can deploy GitHub releases to the same repository of the build successfully. But, I want to deploy the releases to a repository separate from the current one (for bleeding edge releases). Is this possible? If not, is it possible to implement this to Travis?

**Comment by BanzaiMan** [comment]
No, it's not possible. If you want to create a GitHub release on a repository, please enable Travis CI on that repository.

**Comment by ErmanSayin** [comment]
managed to do this by writing a node.js script that uploads the binaries to another repo.
