### ISSUE TITLE
"secure" environment variables no longer work

### ISSUE THREAD

**Issue by rnicholus** [travis-ci/travis-ci#7806]
I'm guessing this broke sometime during the most recent key leak. Right around May 8th, parts of my build that depended on "secure" encrypted env vars stopped working. And I noticed something odd in the config section of the build:

Before Travis-CI's key leak issue:
```
"global_env": "DISPLAY=:99.0 DOCS_GH_REF=github.com/FineUploader/docs.fineuploader.com DOCS_PUSH_ACCESS_TOKEN=[secure]",
```

...and now after the "fix":

```
"global_env": "DISPLAY=:99.0 DOCS_GH_REF=github.com/FineUploader/docs.fineuploader.com SCTkMbvjdYC3BnxE1zM7UFTiNAAqdVpVSL2h6vmugyEV/0TNfbA9Fg4nEGD4sVd88AVS3PiAphX6f874rS73sqfNkilcR6HbdIvoFpqeqnHar4K1JU9BzJeDivAiBCWuIG+2mjRIa8qcumvldgTH6FoBfgA8Dcv9wXXFvrotUsl8FJvoFYQSbvUllAOkJJJRcF2h/H1fo11doIhXrza/SxAnWZKicP3BaNSH+jsi5/tmhTekKmvxSfznaUxNmoq/K2oeppi/8n+5k4z7UYkKHrcgP/yu3GApostCANDgBQ4fgEE9dtYW39gOsbOH22jHX5wNNIcn8KWyEoJFnwi4MO2kRlbHKxR2zbm8en4jgabWlgVENG6lVGoZ7dEo7annLQmPIcXsXp7rwDNI1phqhKxWw3H1aOGuRI7QHFUlOe4JXMQRMIL+4/0Ro/+sHcJg17ak6aV/cvleoVZ4xsz457E4nem0kRItC8Mn79IbtXL/6vTiBeaQhqqPpxY9SzWgdBnnWz3jzYmCdO3ebz4W4TQaAEWbVYZ4/2qgvoozd/fbU0cTZWKHAOQ1ny3Cn4j4OwAMNLopKefyxu3Rzpm0u4goSnipiMh+GmFMjjubz34SAL9fetvJngM3axfwYUgpFUQf7f1WklDC7tm6vk2dk4PJRrSPB2sGLy4ywBhkzbA=[secure]",
```

As you can see, the env var name is apparently listed as `[secure]` with the encrypted key as the env var name. This is preventing me from completing any builds.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by Shreeshrii** [comment]
I am having the same problem. Please see log at

https://travis-ci.org/Shreeshrii/tess4eval/builds/235495065

**Comment by rnicholus** [comment]
i just worked around the issue by adding the secure env var in the settings section of the UI.

**Comment by Shreeshrii** [comment]
the error I am getting is

```
remote: Permission to [secure]/tess4eval.git denied to [secure].
fatal: unable to access 'https://user:[secure]@github.com/[secure]/tess4eval.git/': The requested URL returned error: 403
```
when trying to deploy to gh-pages

**Comment by BanzaiMan** [comment]
@Shreeshrii Could you ensure that the token you are using is still valid? (It might be easier to generate a new one.)

**Comment by Shreeshrii** [comment]
OK. I will try regenerating and updating once again.

**Comment by BanzaiMan** [comment]
@rnicholus Hmm. Without more information, we are unable to investigate what is happening here. If you wish to keep your build log URL private, please email us at support@travis-ci.com. Thanks.

**Comment by Shreeshrii** [comment]
@BanzaiMan I regenerated the personal access token on github and then

```
 travis login
travis encrypt GIT_NAME=Shreeshrii --add -r Shreeshrii/tess4eval
travis encrypt GIT_EMAIL=<EMAIL> --add -r Shreeshrii/tess4eval
travis encrypt GH_TOKEN=<TOKEN> --add -r Shreeshrii/tess4eval
```
I also updated token in settings of  https://travis-ci.org/Shreeshrii/tess4eval/settings

still getting same error

**Comment by Shreeshrii** [comment]
Also tried with the `deploy pages` option - see error at

https://travis-ci.org/Shreeshrii/tess4eval/builds/235624097

Is there any setting on github which maybe blocking all access for updates from travis?

**Comment by BanzaiMan** [comment]
@Shreeshrii I'm sorry to hear about the continued problem. However, I am pretty sure that your issue is unrelated to this issue here. Please review https://docs.travis-ci.com/user/deployment/pages and ensure that the token you set in Settings as `$GITHUB_TOKEN` is valid and has the correct scope.

At any rate, please open a separate ticket, or send us email at support@travis-ci.com for further discussion.

**Comment by Shreeshrii** [comment]
Thanks for your help, I got it to work now.
