### ISSUE TITLE
Confusing error output on build failure

### ISSUE THREAD

**Issue by cthoyt** [travis-ci/travis-ci#7809]
I'm having a problem where my tests (run through tox on py27 and py36) succeed locally, but cause an error during my build group (https://travis-ci.org/pybel/pybel/builds/235700392) .

The only feedback that I've received is `ERROR: InvocationError: '/home/travis/build/pybel/pybel/.tox/py36/bin/coverage run -p -m pytest tests -v'` with an exit code of `1`, which isn't helping me in the right direction. Link to log: https://travis-ci.org/pybel/pybel/jobs/235700400

It seems that this isn't because of the tests failing, but something else going wrong. To be more confusing, it's succeeding sometimes for py27 but never for py3{4,5,6}. I haven't been able to emulate this behavior on my system either.

**Comment by BanzaiMan** [comment]
Please take a look at https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally to test your build locally.

I ran a series of commands that leads to this error:

```sh-session
$ wget https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/12.04/x86_64/python-3.6.tar.bz2
$ sudo tar xjf python-3.6.tar.bz2 --directory /
$ git clone --depth=50 --branch=feature/ndex-io https://github.com/pybel/pybel.git pybel/pybel
$ cd pybel/pybel/
$ git checkout -qf 2dab8e15be5a3813ebf0a5957304cc95b8776dd0
$ source ~/virtualenv/python3.6/bin/activate
$ pip install codecov pymysql tox
$ export TOXENV=py36
$ export PYBEL_TEST_CONNECTION=mysql+pymysql://travis@localhost/pybel?charset=utf8
$ tox
```

**Comment by cthoyt** [comment]
I figured out this was a memory problem. I had loaded quite a bit of extra testing data (which I've since cut out) and it was more than Travis was set to handle. Perhaps it would be possible for Travis to give a warning when something like this happens? Otherwise my issue is closed. Thanks for the help.

**Comment by BanzaiMan** [comment]
Happy to hear that you were able to resolve it. I am not sure if we can do much to detect the errors you saw, though. The error message is coming from `tox`; the best bet is to ask them to improve error messages.
