### ISSUE TITLE
How to use imagick

### ISSUE THREAD

**Issue by concept-immo-global** [travis-ci/travis-ci#781]
Hello,
I need to use Imagick when i run my phpunit tests but i don't understand how install Imagick with Travis. 
I try with :

``` ruby
before_script:
    - sudo pecl install imagick
```

or 

``` ruby
service:
    - imagick
```

but don't work.

Thanks for your help

**Comment by Tjitse-E** [comment]
Maybe someone could use this: `printf "\n" | pecl install imagick` stopped working on our builds, so we've changed it to:

```
   - pear config-set preferred_state beta
   - pecl channel-update pecl.php.net
   - yes | pecl install imagick
```
We're able to install Imagick correctly again using PHP7.

**Comment by PowerKiKi** [comment]
Only that single line is enough to install and enable imagick:

```yml
   - yes | pecl install imagick
```
