### ISSUE TITLE
Deploy error: "This version of the API has been Sunset."

### ISSUE THREAD

**Issue by dgattoni** [travis-ci/travis-ci#7810]
Hi Guys!
I was trying to deploy and got this error (screenshot below) according to Heroku, they will sunset v2 of the API on April 15, 2017. For security reasons https://blog.heroku.com/sunsetting_heroku_s_legacy_platform_api_v2, and  the final shutdown Monday, June 26th.

Any estimate date on the transitioning to Heroku API v3 ?

<img width="935" alt="screen shot 2017-05-24 at 14 58 22" src="https://cloud.githubusercontent.com/assets/5312844/26420721/846730f6-4091-11e7-9693-274659c93b45.png">

Thanks! 👍

**Comment by BanzaiMan** [comment]
Sorry for the troubles.

There was [an hour of brownout period earlier today](https://devcenter.heroku.com/changelog-items/1147) that exposed parts of our deployment code that were still using the legacy API version.

The API calls have been fixed by https://github.com/travis-ci/dpl/pull/637, so that the next `dpl` release will no longer have the issue. Naturally, that release must happen before the sunset date (June 26th).

I'm going to leave this open now, until a new version of `dpl` is released.

Thank you.

**Comment by tsheaff** [comment]
@BanzaiMan I'm experiencing this same error right now.

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.55.0/lib/excon/middlewares/expects.rb:11:in `response_call': Expected(200) <=> Actual(410 Gone) (Heroku::API::Errors::ErrorWithResponse)
body: "{\"id\":\"gone\",\"error\":\"This version of the API has been Sunset.\\nPlease see https://devcenter.heroku.com/changelog-items/1147 for more information.\\n\"}"
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.55.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.55.0/lib/excon/connection.rb:388:in `response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.55.0/lib/excon/connection.rb:252:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/heroku-api-0.4.2/lib/heroku/api.rb:84:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/heroku-api-0.4.2/lib/heroku/api/user.rb:9:in `get_user'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/provider/heroku/generic.rb:28:in `user'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/provider/heroku/generic.rb:32:in `check_auth'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/provider.rb:134:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/provider.rb:133:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/provider/heroku/generic.rb:57:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by BanzaiMan** [comment]
Heroku had another brownout, for which we were not prepared. https://status.heroku.com/incidents/1161

We apologize for the recurrence of this issue.

`dpl` 1.8.33 is out now, which should fix this problem. If you are able to run a deployment in the next few minutes (before 21:00 UTC) and report the results, it would be super useful!

Thank you, and sorry for the inconvenience.

**Comment by tsheaff** [comment]
Thanks @BanzaiMan it worked this time around.

**Comment by BanzaiMan** [comment]
FYI: `dpl` 1.8.33 was faulty and was yanked. I'm working on a fix.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/dpl/issues/640#issuecomment-305600224

> We have released `dpl` 1.8.34. Heroku API deployment now uses V3 API endpoint exclusively, and supports `run` and `restart` commands as before.
> 
> I'm going to keep this issue open until the next brownout on Monday, at which time we should know if it **_really_** works.

**Comment by BanzaiMan** [comment]
Hello, everyone!

`dpl` 1.8.37 is out with some code changes (but no functional changes). You should not see any differences in terms of deployment, but the `git-ssh` and `git-deploy-key` strategies will get a deprecation warning (as they are shut down with the legacy API; needless to day, these will fail during the scheduled brownout periods).

Do let us know if you see problems with `api` (which is the default) or `git` strategies.

The next two scheduled brownouts are

* Heroku V2 API Brownout on Monday, June 5th at 16:00 UTC (12:00 EDT)
* Heroku V2 API Brownout on Friday, June 9th at 18:00 UTC (14:00 EDT)

Thanks.

**Comment by BanzaiMan** [comment]
https://status.heroku.com/incidents/1174

> On Thursday, June 8, 2017, starting at 18:00 UTC (14:00 EDT), and continuing until 19:00 UTC (1 hour), Heroku will be performing a service update to our API.

**Comment by deaboway** [comment]
Just say hi

**Comment by stefb965** [comment]
hi

**Comment by kiulkiel** [comment]
Hi

**Comment by BanzaiMan** [comment]
This should no longer be a problem.
