### ISSUE TITLE
Builds hanging when using wget/curl commands to download

### ISSUE THREAD

**Issue by albertvang** [travis-ci/travis-ci#7812]
Around 9AM this morning (5/24), all my builds were self-terminating due to wget returning

"HTTP request sent, awaiting repsonse ...  Read error (Connection timed out) in headers. "

I've been using the same command for months and never had an issue.  I am able to run the same command on my local vm and download the file fine.  I also tried using travis_wait but it made no difference.

So I was wondering if there were any network changes that was done recently to cause this to happen?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by albertvang** [comment]
$ wget --user=${username} --password=${password} "{url}"
--2017-05-24 22:06:24--  {url}
Resolving {host} ({host})... {ip}
Connecting to {host} ({host})|{ip}... connected.
HTTP request sent, awaiting response...


sits like this for 10 mins or so then the build terminates itself

**Comment by BanzaiMan** [comment]
Sorry, but that does not tell us anything new. What's the server you are trying to reach?

**Comment by BanzaiMan** [comment]
I'm closing this now, as there is not much really to work on. If you have further questions, do send us email at support@travis-ci.com with more details. Thanks.
