### ISSUE TITLE
[QUESTION] Build *only* PRs, nothing else

### ISSUE THREAD

**Issue by gvilarino** [travis-ci/travis-ci#7813]
Is there a way for travis to *only* run whenever branch that is a PR is updated/created, and not in any other case?

It's not clear for me from the docs and I'm having a hard time making it work by myself, although it seems it should be a very simple config thing that I'm not nailing.

Thanks in advance.

**Comment by BanzaiMan** [comment]
What have you tried, and what were the results?

If you disable "branch updates" in https://travis-ci.org/OWNER/REPO/settings, it should achieve what you want.

**Comment by gvilarino** [comment]
Thanks @BanzaiMan 

I've tried this:
![image](https://cloud.githubusercontent.com/assets/2538465/26476220/a5438c36-4193-11e7-808d-4cd27fe95ea2.png)

And whenever I open a PR, it doesn't do anything.

It only works if I set Build Branch Updates to ON and using this:
```
branches: 
  except:
    - master
```
in my `.travis.yml`

But that also attempts to build any other branch out there, whenever there's a push to it.

I don't know if it's any difference but `.travis.yml` is not on my `master` branch yet (it'll be there once I sort this out).

**Comment by gvilarino** [comment]
Another thing I've noticed is that when the builds do run, `TRAVIS_PULL_REQUEST` is `false`, even though they're being triggered by a PR being updated...

**Comment by gvilarino** [comment]
BTW, the PR branch is rebased to master and is mergeable.

**Comment by BanzaiMan** [comment]
1. Disable "Build branch updates" in https://travis-ci.org/OWNER/REPO/settings.
1. Create a new branch.
1. Push the new branch.
1. Confirm that the build request resulting from the push is rejected (in https://travis-ci.org/OWNER/REPO/requests).
1. Open a PR.
1. Confirm that the build is initiated by the PR.

Here's what I see in https://travis-ci.org/BanzaiMan/travis_production_test/requests:

![banzaiman_travis_production_test_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/26494516/038c1494-41ed-11e7-9660-24e1f82dd4c1.png)

**Comment by BanzaiMan** [comment]
With which repository are you having problems?

**Comment by gvilarino** [comment]
The repo is https://github.com/tactivos/murally. It's a private repo.

Just tried the exact same steps, and it doesn't work. When looking at the requests, I see:

```
Branch "master" excluded per configuration.
```

In the PR request. But it's not `master` I'm building, it's a PR on a different branch!

**Comment by BanzaiMan** [comment]
PR builds belongs to the target branch. If you have

```yaml
branches:
  except:
    - master
```

your PR builds for the `master` branch will be rejected. You can see this on https://travis-ci.com/tactivos/murally/requests.

**Comment by BanzaiMan** [comment]
@gvilarino Looks like you've been able to sort things out. I'm closing this now.

If you have further questions, do email us at support@travis-ci.com.
