### ISSUE TITLE
Syncing the account uses GitHub API too many times.

### ISSUE THREAD

**Issue by isuruf** [travis-ci/travis-ci#7815]
I'm a member of the github organization [conda-forge](https://github.com/conda-forge) which has more than 2500 repositories. A single sync call makes too many requests (one per repository). Therefore the github token gets rate limited if we do 2 sync calls within an hour.

Would you be able to reduce the number of github API calls that you are using? Alternatively, if you can give an API to sync just one repository from github, then we don't need to sync at all.

**Comment by jakirkham** [comment]
Potentially related to issue ( https://github.com/travis-ci/travis-ci/issues/6320 ). 😉
