### ISSUE TITLE
C++11 with R?

### ISSUE THREAD

**Issue by Ironholds** [travis-ci/travis-ci#7818]
Heya!

I'm wondering how to specify that an R project be built using C++11? My attempted builds all seem to be using 0x.

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements

**Comment by Ironholds** [comment]
Thanks! Resolved separately - looks like just relying on trusty is enough.
