### ISSUE TITLE
Coverity does not work with OSX SIP enabled

### ISSUE THREAD

**Issue by metsma** [travis-ci/travis-ci#7824]
https://travis-ci.org/open-eid/libdigidocpp/jobs/237594744#L543

[ERROR] System Integrity Protection is enabled. In order to use cov-build,
        this must be disabled. If you are confident that SIP has been 
        disabled, pass --no-sip-check to bypass this check.

**Comment by metsma** [comment]
Coverity support
"Unfortunately, there is no current work-around so this is a hard requirement when using our tools under OSX. The bug has been filed with our devs."

**Comment by vit9696** [comment]
Hello @BanzaiMan,

It is not a Coverity bug, but unfortunately a misconfiguration in Travis-CI VMs.
Coverity supports a dedicated `COVERITY_CSRUTIL_PATH` environment variable meant for custom configuration cases and/or future OS updates.

To workaround the problem of bypassing the System Integrity Protection status check you mentioned above, I set this variable to point to a custom tool, which always prints disabled and lets me go further (https://github.com/vit9696/Lilu/commit/d4c7dde6285e70093927d4e7579b02009a8e4bb9). However, it will not do magic as System Integrity Protection will not let Coverity inject its dylib into xcodebuild/clang. The buildlog is a good [proof](https://travis-ci.org/vit9696/Lilu/builds/383757315#L1112) if necessary. I can assure you that cov-scan works just fine with a manual invocation on a machine, where SIP is properly off.

I suppose there is a serious misunderstanding of what System Integrity Protection actually is. While it is a good thing to prevent malicious software from running on a production environment, in a virtual machine with no persistent storage it makes no practical sense, as it blocks proper debugging, kext testing, and integration of various development instruments Coverity included.

Thank you for your understanding, I hope to find SIP disabled in the next update :)

Vit

**Comment by vit9696** [comment]
Hello @BanzaiMan,

Is there any progress on this issue?

Best regards,
Vit

**Comment by metsma** [comment]
This is still not fixed

**Comment by vit9696** [comment]
I spent some time discussing the issue with Travis Support team, and the reason they do not want to disable SIP is much simpler than "system compatibility" and such: they appear to use SIP to slightly improve the security of their VM configurations. I guess I disagree of it being much useful, but they could be understood at least.

In the end I was able to implement a workaround by extending my previous suggestion on abusing the csrutil environment variable, and Travis staff updated their [KB article](
https://docs.travis-ci.com/user/coverity-scan/#os-x--macos-support). They seem to have decided not to answer here, but you can refer to [this change](https://github.com/acidanthera/Lilu/commit/b35c5bf200f57b3bcf3e2e84622bd630ba2a27e8) to see how Coverity can be used in the wild.
