### ISSUE TITLE
Perl 5.26 is now available

### ISSUE THREAD

**Issue by Grinnz** [travis-ci/travis-ci#7825]
Perl 5.26.0 was just released (may still be propagating on mirrors), it would be great to have this available on Travis. https://docs.travis-ci.com/user/languages/perl/ should then also be updated to show the new version.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/perl-builder/builds/238576449

**Comment by BanzaiMan** [comment]
Hmmm. That build may not work. I'll take another look soon.

**Comment by akzhan** [comment]
@BanzaiMan 

You need to simply upload appropriate Perl archive.

```
5.26 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-perl-archives/binaries/ubuntu/14.04/x86_64/perl-5.26.tar.bz2
$ sudo tar xjf perl-5.26.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by akzhan** [comment]
Looks like you need to review https://github.com/travis-perl/helpers / https://github.com/travis-perl/builder

**Comment by akzhan** [comment]
@Grinnz workaround to build on any Perl version: https://github.com/akzhan/perl-YourCompany-Project/commit/d7ba034c51e5647fd7926ec8ac00e6ea0b71efab

**Comment by Grinnz** [comment]
Yes I know about travis-perl helpers. This is not what this issue is about.

**Comment by BanzaiMan** [comment]
Sorry for the delay. We are trying to automate builds of new releases, and it may take a while to work out the issues in the process.

**Comment by BanzaiMan** [comment]
5.26.0 is available now for Linux. https://travis-ci.org/BanzaiMan/travis_production_test/builds/239805541#L95
