### ISSUE TITLE
HHVM is no longer supported on Ubuntu Precise.

### ISSUE THREAD

**Issue by ShahrokhNiakan** [travis-ci/travis-ci#7827]
I got this error on hhvm: 
HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.
https://travis-ci.org/anetwork/validation/jobs/237868311

**Comment by BanzaiMan** [comment]
A duplicate of #7712. Please use Trusty if you need HHVM.
