### ISSUE TITLE
Tests Failing - For past few hours

### ISSUE THREAD

**Issue by Sibiraj-S** [travis-ci/travis-ci#7829]
I have few repositories for build in travis. recently I noticed that builds are failing. I have no clue why that happens. I thought any errors in my project. then I ran few builds that are successful already. but they too fail with this error

```
Installing yarn
30.15s$ curl -o- -L https://yarnpkg.com/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5929    0  5929    0     0    19bash: line 1: syntax error near unexpected token `newline'
6      0 bash: line 1: `<!DOCTYPE html>'
--:--:--  0:00:30 --:--:--  1451
The command "curl -o- -L https://yarnpkg.com/install.sh | bash" failed and exited with 2 during .
```

**Comment by rwjblue** [comment]
Underlying issue is that `yarnpkg.com` is down. 

See https://github.com/yarnpkg/yarn/issues/3549 and https://github.com/yarnpkg/yarn/issues/3550.

**Comment by Sibiraj-S** [comment]
site is up now.
