### ISSUE TITLE
Deploy failed to gh-pages

### ISSUE THREAD

**Issue by SanjoDeundiak** [travis-ci/travis-ci#7834]
I'm trying to deploy docs for my project to gh-pages and script was fully working previously, but now fails with following error:

/Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/fileutils.rb:1386:in `copy': unknown file type: ./docs/. (RuntimeError)

where docs is the directory to deploy to gh-pages.

Full log can be found here: https://travis-ci.org/VirgilSecurity/virgil-sdk-x/jobs/238339093

**Comment by BanzaiMan** [comment]
Where is the previous successful deployment?

**Comment by SanjoDeundiak** [comment]
@BanzaiMan I'm not 100% sure but seems like that's the last successful deployment
https://travis-ci.org/VirgilSecurity/virgil-sdk-x/builds/223934357
Any thoughts on what goes wrong with my deployment?

**Comment by BanzaiMan** [comment]
There is [no difference](https://github.com/travis-ci/dpl/compare/v1.8.31...v1.8.32) in deployment code.

There is [a remarkable difference](https://github.com/VirgilSecurity/virgil-sdk-x/compare/290809273496f8dab8bfa57015810349d879cabc...4.5.0) in your `.travis.yml`, however, and it is that the `local-dir` value changed from the absolute path to a relative one. https://github.com/VirgilSecurity/virgil-sdk-x/commit/9debde58bffdd9c53c48f8b5d81586e5299fedab This suggests to me that your working directory changes during the build before the deployment kicks in, and the `docs` directory is not found.

**Comment by SanjoDeundiak** [comment]
@BanzaiMan local-dir is still absolute path (https://github.com/VirgilSecurity/virgil-sdk-x/blob/master/.travis.yml), however logs tell us nearly nothing about what went wrong during deployment so it's very hard to debug something. Any ideas?

**Comment by BanzaiMan** [comment]
@SanjoDeundiak The actual problem might be here: https://travis-ci.org/VirgilSecurity/virgil-sdk-x/jobs/240394674#L806 If this command is expected to generate `./docs`, the command failure leads to absence of the directory, and the deployment failure.

**Comment by BanzaiMan** [comment]
I'm closing this. See https://github.com/VirgilSecurity/virgil-sdk-x/pull/6.

**Comment by SanjoDeundiak** [comment]
@BanzaiMan thank you
