### ISSUE TITLE
Isolate Environment Variables only on Base Pull Requests

### ISSUE THREAD

**Issue by ProIcons** [travis-ci/travis-ci#7838]
An idea would be to have the option to NOT include an environment variable when building a Pull Request derived from a Fork. 
There are security flaws, which a user can potentially create a malicious code pull request it and retrieve passwords.

**Comment by BanzaiMan** [comment]
If you encrypt the environment variables which contains sensitive information, external PRs won't have access to it. https://docs.travis-ci.com/user/encryption-keys

Do you have a different use case in mind?

**Comment by ProIcons** [comment]
Is this also working with the GUI except with the CLI tool?

**Comment by BanzaiMan** [comment]
If you don't mind PRs having access to such API keys, then there is no real reason to make it a secret. PRs can, for example, send the API key to an external service to dump it.

**Comment by ProIcons** [comment]
I'm aware but let's say there's an API Key bound to travis' IP addresses, 

The username and password is not the same deal. It would be a nice addition to the guy make a field hidden, but also forwardable to the pr, and some other's secret non forwardable to the pr.
