### ISSUE TITLE
Multiple Deployments with Same Provider Not Working

### ISSUE THREAD

**Issue by jamesbyars** [travis-ci/travis-ci#7840]
Build URL: https://travis-ci.com/jamesbyars/mp-web-app/jobs/77792787

```---

language: node_js
node_js:
  - "7.0"

branches:
  only:
    - develop
    - master

before_script:
  - npm install -g @angular/cli@1.0.0
  - npm install

script:
  - ng build --prod
  - ls -al

deploy:
  - provider: s3
    access_key_id: SOME_KEY
    secret_access_key: BOB_DOLE
    bucket: BUCKET_NAME
    local_dir: dist
    default_text_charset: 'utf-8'
    skip_cleanup: true
    on:
        branch: develop
  - provider: s3
    access_key_id: BOB_DOLE
    secret_access_key: BOB_DOLE
    bucket: BUCKET_NAME1
    local_dir: dist
    default_text_charset: 'utf-8'
    skip_cleanup: true
    on:
        branch: master

notifications:
  email:
    on_failure: change
    on_success: change
```

**Comment by BanzaiMan** [comment]
Could you elaborate on what you mean by "not working"?

Looking at the build log, the two providers are getting invoked; the first one is skipped:

    Skipping a deployment with the s3 provider because this branch is not permitted

and the second one is being deployed.

    ⋮
    uploading "assets/ui-js/metisMenu.min.js" with {:content_type=>"application/javascript; charset=utf-8"}
    uploading "assets/ui-js/sb-admin-2.min.js" with {:content_type=>"application/javascript; charset=utf-8"}

This build was on the `master` branch, so this behavior is correct.

**Comment by jamesbyars** [comment]
Thanks for your response, I apologise.  You are absolutely correct.  I must have had tired eyes.
