### ISSUE TITLE
Passing build artifacts across stages

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#7841]
We want to achieve a 2 stage CI:
 * A `build` stage that compiles a program. 2 builds: mac and linux.
 * A `test` stage that use the compiled program. Multiple builds: 2 OSes * number of different language versions (e.g. `python: 2.7` and `python: 3.5`).

It is hard to pass the compiled program to the `test` stage. 2 approaches I thought of:
 * use Travis's caching: Not feasible since the `language:` / `python:` keys are different between the `build` stage and the `test` stage. The cache wouldn't be shared according to https://docs.travis-ci.com/user/caching#Caches-and-build-matrices. Don't even consider what would happen when there are parallel builds of different commits, or when one restart a build of an older commit.
 * use custom S3: It can work in our own repo, however, without exposing our S3 credentials, our forks wouldn't be able to use CI (unless they override the S3 credentials with their own).

It would be great if there is some ad-hoc feature for passing build artifacts across stages.
For reference, the GitLab CI artifacts is pretty perfect: https://docs.gitlab.com/ee/ci/yaml/#artifacts
Their `artifacts` from all previous stages are passed by default, but also can be fine-tuned with `dependencies`.

**Comment by kkm000** [comment]
Yes, pretty please. Our project has run out of the 50 minute time for build and test. I have split it in two jobs, first to build libraries (25 count) and run tests in them, and another to build same libraries (see the pattern?) and then compile binary tools (500+ binaries) that depend on the libraries. Despite ccache (thanks for adding the support!), the test part is on the verge of timing out, and sometimes does. What can I do? I would split it again to build the libraries (ah!) and test only some of them in a separate job each. But the libraries are highly interdependent, so each testing job will still build 80% of library code. What a waste of your CPU resources! Passing on build artifacts would well decrease the CPU requirements and the build time.

FWIW, Appveyor also supports build artifacts very transparently. You can even pull them from API and or a Web page.

**Comment by kuwas** [comment]
👍

**Comment by BanzaiMan** [comment]
I'll close this as a variation of #7590.
