### ISSUE TITLE
Any suggested workaround to not for a Yarn install?

### ISSUE THREAD

**Issue by oshalygin** [travis-ci/travis-ci#7845]
If the configuration calls for Yarn to run(yarn.lock or the yarn cache config), Travis-CI goes out and tries to install Yarn, which makes sense.

My issue comes with, what if Yarn is down(the endpoint is unreachable), is there a way I can bake in the installation of yarn?  Maybe specify a base node image with yarn pre-installed?

Imagine this fails:
`curl -o- -L https://yarnpkg.com/install.sh | bash `

I'd like to see if I can cache the yarn installation altogether as the VM spins up, possible?

**Comment by BanzaiMan** [comment]
As `yarn` gets installed into `$HOME/.yarn`, you can cache that, if you'd like.

However, until the build images are updated with `yarn`, it will have to come from somewhere, and that will always remain as an external dependency. (Caching is also an external dependency.)

**Comment by oshalygin** [comment]
Excellent, that is super clear thank you @BanzaiMan !!
