### ISSUE TITLE
Updating absolute beginner guide

### ISSUE THREAD

**Issue by JuliusKoronci** [travis-ci/travis-ci#7850]
Hi,
Since HHVM is only supported on trusty could you update the guide for absolute beginners to use:

language: php
dist: trusty
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php

I would gladly make a pull request but the github link on the site is broken as well

Thanks

**Comment by BanzaiMan** [comment]
Hello. Thanks for taking the time to open the issue. I just fixed the doc edit links, so you can open a PR for improvement now.

**Comment by JuliusKoronci** [comment]
Thank, PR created :)
