### ISSUE TITLE
PHP 5.5.9 file is corrupt

### ISSUE THREAD

**Issue by yassirh** [travis-ci/travis-ci#7853]
I am trying to build a PHP library using travis-ci. The build goes smoothly for PHP versions 5.4, 5.5, 5.6, 7 and hhvm but [fails for version 5.5.9](https://travis-ci.org/toin0u/DigitalOceanV2/jobs/239300625).

After checking the logs I have realized that the file php-5.5.9.tar.bz2 for ubuntu 14.04 is corrupt. 

```bash
5.5.9 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-5.5.9.tar.bz2
$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

$ phpenv global 5.5.9
rbenv: version `5.5.9' not installed
The command "phpenv global 5.5.9" failed and exited with 1 during .
Your build has been stopped.
```
I can provide more details if needed.

**Comment by BanzaiMan** [comment]
It's not that it was corrupt, but that it wasn't there. When this build succeeds and uploads it, you should be able to use it.

https://travis-ci.org/travis-ci/php-src-builder/jobs/239377072

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/jobs/239383047#L105
