### ISSUE TITLE
Not functioning on my project

### ISSUE THREAD

**Issue by LBYPatrick** [travis-ci/travis-ci#7856]
I have a project called **GameBooster**. Every time I commit, travis-ci does not test the new commit for some reason...

**Comment by BanzaiMan** [comment]
Please check that your account is synced (https://travis-ci.org/profile/), the repository is enabled. Also check the requests page (https://travis-ci.org/OWNER/REPO/requests) to see what happened to your build requests.

**Comment by LBYPatrick** [comment]
But it was able to sync automatically...Why the heck it happened

**Comment by BanzaiMan** [comment]
According to the logs, at the time of your last commit to this repository https://github.com/LBYPatrick/GameBooster/commit/1a9c92b69ed2bd8539eb1367922bec082e7fd326, the repository was not active, and we did not receive the notification to fire a build. (Cron jobs do not need this notification to run, so you got https://travis-ci.org/LBYPatrick/GameBooster/builds/239579910.

I see that the repository is enabled again, so please try pushing another commit.

**Comment by LBYPatrick** [comment]
Yes, that was after I realized it was not building automatically, I enabled Cron Job. And what is "not active"?

**Comment by BanzaiMan** [comment]
"Not active" means that we do not get notified of your commits to GitHub.

**Comment by LBYPatrick** [comment]
Then why did that happen? Does Github have bug on notification system?
