### ISSUE TITLE
Error: Cannot find module './lib-cov/SauceLabs' when Protractor is installed as a dependency.

### ISSUE THREAD

**Issue by AnimaMundi** [travis-ci/travis-ci#7858]
I can't understand this at all and have spent hours today trying to figure this out.

The full error is this:
```
05 06 2017 23:10:11.249:ERROR [karma]: Error: Unable to resolve module [./lib-cov/SauceLabs] from [/home/travis/build/amd-core/amd-angular-ui/node_modules/saucelabs/index.js]
```

It happens at the point that Travis tries to run my unit tests through Karma. Everything was working fine until I tried adding integration tests too. I narrowed down the problem to installing Protractor as a dependency. Even though I have nothing related to SauceLabs in my configuration (I'm planning to use BrowserStack), this error is happening.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by AnimaMundi** [comment]
Yes there is a list of builds here: https://travis-ci.org/amd-core/amd-angular-ui/builds

Build number 41 passes fine: https://travis-ci.org/amd-core/amd-angular-ui/builds/239762561

Then build number 42 breaks: https://travis-ci.org/amd-core/amd-angular-ui/builds/239764378
The changes I made for build number 42 are here: https://github.com/amd-core/amd-angular-ui/commit/940018a36f96fdb4e9c6d2259f1b1b643c104240

I can work on a minimal repro tonight if this is not enough to work with, but you can see there's no changes to the Travis configuration or any script that will run in the build, all I've done is install dependencies.

**Comment by BanzaiMan** [comment]
I am sorry to say, but this looks like a strictly application issue. Try reproducing the issue with the docker image, as described in https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally. (FWIW, the problem is reproducible with the commands you can see in the build log.)

Thanks.

**Comment by AnimaMundi** [comment]
I fixed the issue, I'm so sorry for wasting your time on this, I hope you didn't put too much effort into it. I never even thought to check my own configuration as I couldn't understand how a Sauce Labs error was somehow poking it's head in so I automatically thought that it was something to do with Travis detecting a Protractor installation and then looking for Sauce Lab dependencies. Anyway, the issue was caused by my Karma configuration picking up on protractor tests and trying to run them.

Sorry again!

**Comment by matheo** [comment]
@AnimaMundi thanks for this comment!

`protractor` messing up with `karma` tests was my issue too!

**Comment by AlphaMikeFoxtrot** [comment]
> I fixed the issue, I'm so sorry for wasting your time on this, I hope you didn't put too much effort into it. I never even thought to check my own configuration as I couldn't understand how a Sauce Labs error was somehow poking it's head in so I automatically thought that it was something to do with Travis detecting a Protractor installation and then looking for Sauce Lab dependencies. Anyway, the issue was caused by my Karma configuration picking up on protractor tests and trying to run them.
> 
> Sorry again!

How did you fix it? Like, what did you change in karma config file?

**Comment by AnimaMundi** [comment]
I had a project structure like this:

```
components/
test/
  e2e/
  helpers/
```

`test/e2e` contains all of the e2e test files, while `test/helpers` includes some test helpers that can be used across both e2e and unit tests. All of my unit tests are together with the source files in `components`.

In my `karma.conf.js` file I was using:
````
files: [
  'components/index.spec.ts',
  {
    pattern: 'components/**/*.+(ts|html)'
  },
  {
    pattern: 'test/**/*.ts'
  }
]
```
This would load all of my unit tests, the test helpers *and* the e2e tests. So I changed `test/**/*.ts` to be `test/helpers**/*.ts`. I also had to make a similar change in my `tsconfig.spec.json`.

This is particular to my project structure, but hopefully the explanation can help you to find the source of the problem in your own project.

**Comment by matheo** [comment]
In my case, I had to be sure that no `protractor` stuff was included in the files tested by `karma`.

**Comment by AshMcConnell** [comment]
In my case I accidentally imported $ from protractor rather than jquery. (for any googlers that land here)

**Comment by epiphaneSpecter** [comment]
`In my case I accidentally imported $ from protractor rather than jquery`
### Me too....tks

**Comment by appu353** [comment]
I also faced problem and spend more than 2 hours. Actually in VS code by default EventEmitter is imported from protractor instead of '@angular/core'

**Comment by devashishg** [comment]
> I also faced problem and spend more than 2 hours. Actually in VS code by default EventEmitter is imported from protractor instead of '@angular/core'

Same here, accidentally I had imported event emitter from protractor instead of @angular/core.

**Comment by lnoir** [comment]
> I also faced problem and spend more than 2 hours. Actually in VS code by default EventEmitter is imported from protractor instead of '@angular/core'

Similar problem: in one of my specs VS Code imported `By` from protractor instead of @angular/platform-browser.

**Comment by pankajsri03** [comment]
Same here, accidentally I had imported event emitter from protractor instead of @angular/core.

**Comment by gjsdevs** [comment]
yeah me too. I changed`  import { EventEmitter } from '@angular/core'` to `import { EventEmitter } from '@angular/core'` and it works.

Weird thing is I am pretty sure I did not write it like that. Feel like ti somehow changed itself.

**Comment by shivam1855** [comment]
Me too. I accidently imported element from protractor.

 import { element } from 'protractor';


removing it resolves the issue
