### ISSUE TITLE
Travis Go Docker image is outdated

### ISSUE THREAD

**Issue by mcardosos** [travis-ci/travis-ci#7859]
Hello!
The Travis Go Docker image is running Go 1.6.3. I would expect it to at least run Go 1.8.
I followed the instructions here
https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

**Comment by BanzaiMan** [comment]
In addition to the images we list in the document, we install the Go runtime on the fly with [gimme](https://github.com/travis-ci/gimme). If you need to run a version of Go you can run it to update it. https://travis-ci.org/BanzaiMan/travis_production_test/builds/239790765#L149

**Comment by mcardosos** [comment]
Awesome! Thanks for the quick response :)
