### ISSUE TITLE
LaTeX Error: File `xkeyval.sty' not found.

### ISSUE THREAD

**Issue by mattdowle** [travis-ci/travis-ci#7863]
Hi @craigcitro and @jimhester,

Just started to see this error on Travis.  Seems to have started in the last day or so and seems unrelated to any package changes.   Are any other packages experiencing this problem?  There hasn't been any change to the manual as far as I know. I don't recognize the "xkeyval.sty" latex package.  I've searched every file in the package for "xkeyval" and that string doesn't appear anywhere.

https://travis-ci.org/Rdatatable/data.table/builds/240193910
```
Checking package ...
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! LaTeX Error: File `xkeyval.sty' not found.
Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
! Emergency stop.
<read *> 
         
l.13 ^^M
        
!  ==> Fatal error occurred, no output PDF file produced!
* checking PDF version of manual without hyperrefs or index ... OK
* DONE
Status: 1 WARNING
See
  ‘/home/travis/build/Rdatatable/data.table/data.table.Rcheck/00check.log’
for details.
0.80schecking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! LaTeX Error: File `xkeyval.sty' not found.
Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
! Emergency stop.
<read *> 
         
l.13 ^^M
        
!  ==> Fatal error occurred, no output PDF file produced!
```
What can I do to help or get to the bottom of it?
Thanks in advance,
Matt

**Comment by mattdowle** [comment]
I followed your great doc : 
    https://docs.travis-ci.com/user/languages/r/
and I added this workaround that worked : 
    https://github.com/Rdatatable/data.table/commit/2ccbe6aec4a38956d2abd71ad0a609cfcdf14e18

**Comment by craigcitro** [comment]
This is almost surely related to the recent TeXLive 2016 -> 2017 upgrade; @jimhester will likely know more (and whether we need to just do this by default).

**Comment by jennybc** [comment]
I get this as well. And also have no idea why xkeyval.sty is needed or suddenly not being found. Also I only get the error on oldrel and devel, the release build is ok.

**Comment by achubaty** [comment]
A workaround is to add the missing package:

```
before_install:
    - tlmgr install xkeyval
```

**Comment by jimhester** [comment]
I have added xkeyval to the set of default packages installed on R-Travis' TexLive, so this should be fixed. Please let us know if this is not fixed.

**Comment by mattdowle** [comment]
Thanks.  Just tried but it failed.  Perhaps I tried too soon?
https://travis-ci.org/Rdatatable/data.table/builds/240554737

**Comment by jimhester** [comment]
Sorry, I neglected to delete the old version prior to updating the archives, it should now be working.

**Comment by mattdowle** [comment]
Yes works now. Thanks!

**Comment by MichaelChirico** [comment]
FWIW ran into this in a Docker image and had a slightly different solution:

```shell
tlmgr init-usertree
tlmgr install xkeyval etoolbox
```

(only `xkeyval` to resolve this specific issue here, but immediately ran into the `etoolbox.sty` missing too)
