### ISSUE TITLE
Please upgrade to PhantomJS 2.1.1

### ISSUE THREAD

**Issue by ylavoie** [travis-ci/travis-ci#7864]
PhantomJS 2.0.0 is the version installed and is very outdated.
PhantomJs 2.1.1 is the latest and may well be the last version produced, so I suggest that Travis be updated to use it. It has been stable for a while.

**Comment by spencer-brown** [comment]
@ylavoie looks like phantomjs@2.1.1 is now installed on trusty: https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/

**Comment by BanzaiMan** [comment]
Indeed, it is!
