### ISSUE TITLE
Provision Travis CI PHP VM (trust, sudo required) locally

### ISSUE THREAD

**Issue by pablopaul** [travis-ci/travis-ci#7866]
I try to find the reason why a Laravel Dusk test fails on Travis CI, that is why I am trying to reproduce the used Travis CI environment locally.

How can I provision the "Travis full VM trusty sudo required" locally on Mac OS X?

(Unanswered SO question can be found [here](https://stackoverflow.com/questions/44023509/provision-travis-ci-php-vm-trust-sudo-required-locally))

**Comment by BanzaiMan** [comment]
This is documented in https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally.

**Comment by BanzaiMan** [comment]
If you want a non-Docker environment, you'd need https://docs.travis-ci.com/user/running-build-in-debug-mode/. Please read this document thoroughly, and if you think it helps you, please email us at support@travis-ci.com to enable the feature.

I'm closing this now.
