### ISSUE TITLE
SSL warnings for builds on the Trusty image.

### ISSUE THREAD

**Issue by lekshmideepu** [travis-ci/travis-ci#7868]
I came across some SSL warnings like InsecurePlatformWarning as the python uses an outdated SSL module.
(https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings)
 I could see that few solved this issue by installing _pyopenssl ndg-httpsclient pyasn1_
Instead of this, I think one could also upgrade the default python module.
Could someone please take a look at this issue?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by lekshmideepu** [comment]
https://travis-ci.org/nest/nest-simulator/jobs/239954113

**Comment by BanzaiMan** [comment]
This job is using `language: generic`, so the `python` binary is provided by Ubuntu. https://packages.ubuntu.com/trusty/python I believe you would see this error message until the upstream package is updated.

**Comment by BanzaiMan** [comment]
Our recent archives should satisfy this SSL requirement (e.g., https://travis-ci.org/BanzaiMan/travis_production_test/jobs/240564227#L118).

I'm closing this, as I do not think there is much for us to do here.
