### ISSUE TITLE
Xcode 8.3.3 build failing

### ISSUE THREAD

**Issue by loudmouth** [travis-ci/travis-ci#7871]
My builds are now failing with exit code `127` after running just fine yesterday. My [.travis.yml](https://github.com/contentful/contentful.swift/blob/master/.travis.yml) file is open source along with rest of the project. See the latest build of `master` [here](https://travis-ci.org/contentful/contentful.swift/builds/240341904). 

I restarted the last build (prior to the merge commit linked above) on [master that had passed previously](https://travis-ci.org/contentful/contentful.swift/builds/238753976) to see if it would pass, and indeed it did not despite passing previously. 

My best guess it that the upgrade to Xcode 8.3.3 has broken something.

**Comment by BanzaiMan** [comment]
`xcpretty` is currently installed for the default Ruby runtime. The default Ruby changed to 2.4 with the new image, leaving 2.2 out in the cold without `xcpretty`.

To use it, please install it before the first invocation of it.

```yaml
before_install:
  - gem install xcpretty
```

or add it to your Gemfile.

**Comment by loudmouth** [comment]
I had `xcpretty` in my Gemfile already, and the issue I opened was about `xcodebuild` exiting with code 127. Strangely enough, I'm now getting a new error as I try to debug, this time from Carthage:

`Task failed with exit code 65`. This seems to be happening for multiple dependencies, and not just one, however `carthage` build processes complete successfully on my machine running Xcode 8.3.3.

Latest build log here: https://travis-ci.org/contentful/contentful.swift/builds/240696084

**Comment by loudmouth** [comment]
I noticed that despite trying to workaroudn this issue by locking Xcode to 8.3.2: in my `.travis.yml` like so 
```
osx_image: xcode8.3.2
```

the output of `xcodebuild -version -sdk` in the travis log contains the following:
```
Xcode 7.3.1
Build version 7D1014
```

It seems like the right version of Xcode is not being used.

**Comment by BanzaiMan** [comment]
There is no `xcode8.3.2` image, so your job is getting routed to the default image.

**Comment by loudmouth** [comment]
I see. I reverted back to 

```
osx_image: xcode8.3
```
and the output is still an exit code from `xcodebuild`

```
+rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/DVR-ealoixnvwdxvzheseyfrpbpgolyy /Users/travis/Library/Developer/Xcode/DerivedData/Interstellar-dlgcyeydthlnikfepkbbkgyzfrhe /Users/travis/Library/Developer/Xcode/DerivedData/Nimble-agopuvlqqcrunpacmynedhxrfbve /Users/travis/Library/Developer/Xcode/DerivedData/ObjectMapper-dsnaaieeqshditfgqwinrexyzsbg /Users/travis/Library/Developer/Xcode/DerivedData/ObjectMapper-goxmxuorifzfskfgysnbwwbzrkui
+xcpretty -c
++sysctl -n hw.ncpu
+xcodebuild -jobs 2 test -project Contentful.xcodeproj -scheme Contentful_iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' ONLY_ACTIVE_ARCH=YES CODE_SIGNING_IDENTITY= CODE_SIGNING_REQUIRED=NO OTHER_SWIFT_FLAGS=-warnings-as-errors
./Scripts/travis-build-test.sh: line 13: xcpretty: command not found
2017-06-09 12:52:24.599 xcodebuild[22728:43010]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/travis/Library/Developer/Xcode/DerivedData/Contentful-fmigjwzqplnzwxctnsukkzfqjtog/Logs/Test/701740F3-5CEA-484D-8FCF-30CD5CF24490/Session-ContentfulTests-2017-06-09_125224-5joZWc.log
2017-06-09 12:52:24.606 xcodebuild[22728:43006] [MT] IDETestOperationsObserverDebug: (EEEB358D-4D9E-4F00-80E6-177FEF7243D3) Beginning test session ContentfulTests-EEEB358D-4D9E-4F00-80E6-177FEF7243D3 at 2017-06-09 12:52:24.605 with Xcode 8E3004b on target <DVTiPhoneSimulator: 0x7fb39379bb90> {
		SimDevice: SimDevice : iPhone 6s (8BB869B7-8203-4B31-99C9-CC276640EC3D) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6s } runtime={ SimRuntime : 9.3 (13E233) - com.apple.CoreSimulator.SimRuntime.iOS-9-3 }
} (9.3 (13E233))
The command "./Scripts/travis-build-test.sh" exited with 127.
```

**Comment by BanzaiMan** [comment]
If `xcpretty` is in `Gemfile`, try invoking it with `bundle exec`.

**Comment by loudmouth** [comment]
Changing my build script pipe to `bundle exec xcpretty -c` fixed the issue.

Thanks so much @BanzaiMan 

I consider this ticket closed if you would like to close it.
