### ISSUE TITLE
Python segmentation faults

### ISSUE THREAD

**Issue by nijel** [travis-ci/travis-ci#7873]
Since some time I'm getting Python segmentation faults during running tests. These tests utilize SQLite, tests using other database work just fine, so my assumption is that this is the guilty piece. In past the crashes were happening on Python 3.4 or 3.5, after some not related code change the crashes have moved to 2.7.

This is happening on both Trusty and Precise. Though we can't use Trusty for now due to https://github.com/travis-ci/travis-ci/issues/7790.

As a side note: This is not first time I experience segmentation faults on Travis, maybe it would be good to have some documentation how to debug that, or even better, to have installed segfault handler which will automatically display backtrace (AFAIK something like that is built into systemd). This way it would be way easier to figure out what is going on (and rule out crashes in third party modules).

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by nijel** [comment]
Sure it's here:

https://travis-ci.org/WeblateOrg/weblate/jobs/240671891#L1115

Sorry for not including it in the original report...

**Comment by BanzaiMan** [comment]
Please try disabling caches first.

**Comment by nijel** [comment]
I did retry the build with cleared caches, but I can try disabling them as well.

**Comment by nijel** [comment]
Build with disabled caches is here: https://travis-ci.org/WeblateOrg/weblate/builds/240766995

**Comment by BanzaiMan** [comment]
Thanks for testing. Do you mind trying to reproduce the segmentation fault locally? https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

**Comment by nijel** [comment]
I currently do not have the Docker environment...

**Comment by nijel** [comment]
I've just tried that and it's not reproducible locally.

**Comment by BanzaiMan** [comment]
Recent builds are passing. Did anything change to explain this?

**Comment by nijel** [comment]
As mentioned in https://github.com/travis-ci/travis-ci/issues/7873#issuecomment-307416124, I've started to use newer SQLite library and it works fine since then:

```yaml

addons:
  apt:
    packages:
    - sqlite3
    sources:
    - travis-ci/sqlite3
```

**Comment by nijel** [comment]
Apparently it no longer helps as SQLite based tests has now segfaulted again:

https://travis-ci.org/WeblateOrg/weblate/jobs/253516312#L1329

**Comment by nijel** [comment]
Okay, after digging a while this seems to be known SQLite bug: https://www.sqlite.org/src/info/7f7f8026eda38, it happens when in-memory journal hits certain threshold.

I've created simple repo to trigger this bug:

https://travis-ci.org/nijel/sqlite-travis-test

All it does is executing bunch of SQL statements utilizing transactions (it's based on reproducer in the SQLite bug report, just made to work on older version): https://github.com/nijel/sqlite-travis-test/blob/master/test.py

**Comment by nijel** [comment]
The workaround which seems to work is not to use in memory database for tests, but file backed one.

The proper fix would be to upgrade to SQLite 3.14 or newer.

**Comment by nemesisdesign** [comment]
This has started happening for me too on this repo:
https://travis-ci.org/openwisp/django-x509/jobs/297505773

I also tried to restart one of the previous builds that was completed successfully, after the restart it failed.
The failures, in my case, seem to affect python 2.7 only, the python 3 builds run fine.

I tried the workaround proposed here, as well as removing the travis cache, but it didn't work out.

**Comment by nijel** [comment]
I've just reran the test and it still fails:

https://travis-ci.org/nijel/sqlite-travis-test/builds/365965501

**Comment by raphaelm** [comment]
Running into the same issue. @nijel, what's your current workaroung?

**Comment by nijel** [comment]
My workaround is not to run tests against in memory sqlite. The file backed sqlite makes it a bit slower, but works...

**Comment by raphaelm** [comment]
FYI: We found a way to make the SQLite test faster instead of slower, with working around this bug (for now) at the same time: https://behind.pretix.eu/2018/06/05/too-many-tests/

**Comment by nijel** [comment]
The issue is still valid, I've just reproduced it: https://travis-ci.org/nijel/sqlite-travis-test/builds/424173409

**Comment by IAmAMissingColon** [comment]
> This has started happening for me too on this repo:
> https://travis-ci.org/openwisp/django-x509/jobs/297505773
> 
> I also tried to restart one of the previous builds that was completed successfully, after the restart it failed.
> The failures, in my case, seem to affect python 2.7 only, the python 3 builds run fine.
> 
> I tried the workaround proposed here, as well as removing the travis cache, but it didn't work out.

Same thing with:
 https://travis-ci.org/openwisp/django-ipam/jobs/617307976?utm_medium=notification&utm_source=github_status

Any idea ?
