### ISSUE TITLE
Support pypy-nightly and pypy3-nightly runtime builds.

### ISSUE THREAD

**Issue by amcgregor** [travis-ci/travis-ci#7878]
Similar to current support for [CPython nightly builds](https://docs.travis-ci.com/user/languages/python/#Nightly-build-support) support for Pypy nightly builds would be an excellent addition, and would potentially relieve some urgency in adding specific published versions.  Pypy use a highly iterative development process with _amazingly extensive_ automated testing (sit in #pypy on irc.freenode.net for a while… you'll see ;) which often give the most bleeding edge versions performance or feature improvements that, in some cases, take quite a while to hit a released version, while also maintaining overall stability.  Nightlies are available from the Pypy buildbot: http://buildbot.pypy.org/nightly/trunk/ (with branches for Python 2 vs. Python 3-compatible runtimes).

Thank you for consideration!

See also [a comment by BanzaiMan](https://github.com/travis-ci/travis-ci/issues/7507#issuecomment-307128178) on #7507:

> We can look at PyPy "nightly" options, based on [`pypy-dev`](https://github.com/pyenv/pyenv/blob/master/plugins/python-build/share/python-build/pypy-dev) and [`pypy3-dev`](https://github.com/pyenv/pyenv/blob/master/plugins/python-build/share/python-build/pypy3-dev).

**Comment by BanzaiMan** [comment]
The first build of [`pypy-dev`](https://travis-ci.org/travis-ci/cpython-builder/builds/241023493) (aliased to `pypy-nightly`), and the first build of [`pypy3-dev`](https://travis-ci.org/travis-ci/cpython-builder/builds/241023521) (aliased to `pypy3-dev`).

When they pass, they would be available for use. I see that [`pypy-dev` failed](https://travis-ci.org/travis-ci/cpython-builder/jobs/241023494) for Trusty today.

**Comment by BanzaiMan** [comment]
Hmmm. Building PyPy(3) seems to take longer than 30 minutes?

**Comment by amcgregor** [comment]
@BanzaiMan Also many, many gigabytes of memory.

**Comment by BanzaiMan** [comment]
If these GCE images can't build it, then it may not be possible. :-/

**Comment by amcgregor** [comment]
I was hoping for re-use of existing buildbot artifacts to avoid the recompilation issue, since yeah, the fractal is nice but I can compile the Linux kernel from `depclean` in 45 seconds…

**Comment by Samureus** [comment]
@BanzaiMan translation using PyPy is usually twice as fast. And numpy 1.13 "should" work:

https://morepypy.blogspot.com/2017/06/pypy-v58-released.html

> Anyone using NumPy 1.13.0, must upgrade PyPy to this release since we implemented some previously missing C-API functionality. Many other c-extension modules now work with PyPy, let us know if yours does not.

http://pypy.org/download.html#building-from-source

> if even using PyPy instead of CPython is not enough, try to tweak some internal parameters. Example (slower but saves around 400MB):
`PYPY_DONT_RUN_SUBPROCESS=1 PYPY_GC_MAX_DELTA=200MB pypy --jit loop_longevity=300 ../../rpython/bin/rpython -Ojit`

**Comment by Juanlu001** [comment]
See also #9542 for the latest PyPy issue.

**Comment by Juanlu001** [comment]
Still on it

**Comment by nbraud** [comment]
Are there plans to build some PyPy branches as well?
For instance, having nightly builds of the `py3.6` branch (which has work-in-progress Python 3.6 support) would be highly-useful, both for developers of Python 3.6 projects (to test compatibility with PyPy and speed up testsuites), and for the PyPy project (to get feedback on the current state of `py3.6`)
