### ISSUE TITLE
Switch to GitHub Apps

### ISSUE THREAD

**Issue by abitrolly** [travis-ci/travis-ci#7881]
Travis CI in [GitHub Marketplace](https://github.com/marketplace/travis-ci) is a OAuth App. That's why it has unlimited access to user or organization repositories and impersonates user, which is bad.

GitHub App is more secure option with fine-grained privileges - https://developer.github.com/apps/building-integrations/setting-up-a-new-integration/about-integrations/

**Comment by jahredhope** [comment]
This feature request is still wanted. It would significantly affect the viability of the product as it would allow organisations to whitelist the application to repositories without requiring access to the whole organisation.

I'd like to see this issue stay open.

**Comment by PHPirates** [comment]
My Travis app appears now under GitHub Apps and not OAuth Apps in my settings, so I guess this feature was implemented?

**Comment by jahredhope** [comment]
The app itself uses GitHub Apps API but the portal hasnt been migrated and uses OAuth.
Half way there, but great to see progress.

**Comment by BanzaiMan** [comment]
@jahredhope What "portal" are you referring to?

**Comment by BanzaiMan** [comment]
Closing now.
