### ISSUE TITLE
comments and +1s on issue 2614 seems to be incorrectly locked

### ISSUE THREAD

**Issue by jettero** [travis-ci/travis-ci#7882]
If you don't want to actually do this, maybe close it? 

https://github.com/travis-ci/travis-ci/issues/2614

**Comment by BanzaiMan** [comment]
Thanks for taking time to open this issue.

There is an ongoing effort to improve dashboard. There is no update to share, but #2614 is still relevant.

In the mean time, I'm closing this as a duplicate.
