### ISSUE TITLE
Trusty with oraclejdk7, ends with: ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle

### ISSUE THREAD

**Issue by typekpb** [travis-ci/travis-ci#7884]
Having:
    
    sudo: required

    dist: trusty

    language: java

    jdk:
      - oraclejdk7

Results in:

    $ jdk_switcher use oraclejdk7
    Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
    ...
    $ ./gradlew check
    ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle

see: https://travis-ci.org/p6spy/p6spy/jobs/241447718

**Comment by BanzaiMan** [comment]
My guess is that we can no longer support `oraclejdk7` on our recent build images due to Oracle's withdrawal. http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html

**Comment by iriberri** [comment]
`oraclejdk8` should be available now in the Trusty `sudo: required` environment: https://github.com/travis-ci/packer-templates/pull/441

**Comment by harshavardhana** [comment]
Facing the same problem here https://travis-ci.org/minio/minio-java/jobs/259670433

**Comment by cotsog** [comment]
Please note that `openjdk7` should still work on Trusty if this is an option for you.

**Comment by tresf** [comment]
Due to the [webupd8 article](http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html) on this, is it safe to assume this is a `wontfix` issue moving forward and will ultimately be closed?

**Comment by BanzaiMan** [comment]
Documentation has been updated. Closing this as a WONTFIX.

**Comment by ottlinger** [comment]
The same is happening with openjdk8 as well .....
https://app.travis-ci.com/github/apache/creadur-rat/jobs/572306063
