### ISSUE TITLE
Build fails after 49 min even when logging output for all jobs every 1-2 min

### ISSUE THREAD

**Issue by magician03** [travis-ci/travis-ci#7885]
I have a build for an Ionic project and its E2E testing with SauceLabs. The build is timing out after 49 min 17 sec(50 min). All of my jobs are running well and logging output frequently at least every 2-3 min. The timeout is happening consistently at 50 min.

My build goes meets all the requirements as mentioned [here](https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts) to not suffer a time out. Also, there is no timeout for the build as mentioned in the docs. So the build shouldn't timeout as it is happening in the case. Any resolutions for this Issue?

Here are some of the logs: 

- https://travis-ci.org/magician03/moodlemobile2/builds/241500777
- https://travis-ci.org/magician03/moodlemobile2/builds/241414546
- https://travis-ci.org/magician03/moodlemobile2/builds/241401570

**Comment by BanzaiMan** [comment]
The jobs have a hard timeout of 50 minutes. Please consider speeding them up. https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out

**Comment by magician03** [comment]
@BanzaiMan Yeah, but it isn't the jobs that are timing out, my build is timing out after 50 min. None of my jobs ran for more than 50 min. I doubt speeding or segregating a long job helps here.

**Comment by BanzaiMan** [comment]
Your builds consist of one job each, and the jobs are timing out after 50 minutes. Did I miss something?

**Comment by BanzaiMan** [comment]
Is there anything for us to do here?

**Comment by magician03** [comment]
Thanks for the help, you can close this issue. I'll try to optimize the Travis build as fast as possible.
