### ISSUE TITLE
python-nightly import numpy fails since recently

### ISSUE THREAD

**Issue by arekbulski** [travis-ci/travis-ci#7886]
About few days ago `python-nightly` started failing for no reason, and I dont think its due to my code. In fact it fails on importing numpy but fails to get into catch ImportError. This is a recent BUG.

Build log:
https://travis-ci.org/construct/construct/jobs/241153020

**Comment by BanzaiMan** [comment]
If the nightly builds start failing, it is most likely due to the issues with upstream code. Please report it in the appropriate place. For Python, it is https://bugs.python.org/.
