### ISSUE TITLE
The repository at ltfschoen/parity_d3 was not found.

### ISSUE THREAD

**Issue by ltfschoen** [travis-ci/travis-ci#7887]
I created a repository at [https://github.com/ltfschoen/parity_d3](https://github.com/ltfschoen/parity_d3).
I created a .travis.yml file for the repo at [https://github.com/ltfschoen/parity_d3/blob/master/.travis.yml](https://github.com/ltfschoen/parity_d3/blob/master/.travis.yml).
When I go to [https://www.traviscistatus.com/](https://www.traviscistatus.com/) it says `All Systems Operational`.
When I go to [https://travis-ci.org/profile/ltfschoen](https://travis-ci.org/profile/ltfschoen) to list my public repos, it DOES NOT list ltfschoen/parity_d3. I expected it to be listed.

But when I go to [https://travis-ci.org/ltfschoen/parity_d3](https://travis-ci.org/ltfschoen/parity_d3) using Chrome it gives a message `The repository at ltfschoen/parity_d3 was not found.`. I expected it to be found.
![screen shot 2017-06-11 at 2 14 22 am](https://user-images.githubusercontent.com/6226175/27004374-bfc2514a-4e4b-11e7-9974-9f398fd8d789.png).
I get the same message in Firefox:
![screen shot 2017-06-11 at 2 16 44 am](https://user-images.githubusercontent.com/6226175/27004414-1ab6bb0e-4e4c-11e7-9bfe-48c62b130d1d.png)

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/getting-started

> Sign in to Travis CI with your GitHub account, accepting the GitHub access permissions confirmation.
> Once you’re signed in, and we’ve synchronized your GitHub repositories, go to your profile page and enable Travis CI for the open source repository you want to build. If you want to build a private repository, sign in to Travis CI for private repositories instead.

Please go to your profile page and activate the repository. If you don't see the repository on the profile page, please sync your data. This should happen every 24 hours or so, but sometimes it may be out of date.

**Comment by ltfschoen** [comment]
Thanks. I didn't realise there was a button "Sync account". After I clicked it the ltfschoen/parity_d3 repository showed up in my list.

![screen shot 2017-06-11 at 2 50 20 am](https://user-images.githubusercontent.com/6226175/27004686-c9e3a4f8-4e50-11e7-8b26-85f58553f102.png)
