### ISSUE TITLE
Upgrade request: NodeJS 8

### ISSUE THREAD

**Issue by adamvoss** [travis-ci/travis-ci#7896]
I tried specifying Node.js V8.x in **.travis.yml**

```yaml
node_js:
- "8"
```

The resulting Node.js version appears to be v6.3.0, which causes my build to fail due to usage of newer language features.

Note: Using trusty container beta.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by adamvoss** [comment]
Sure :+1: :https://travis-ci.org/adamvoss/vscode-languagetool-languages/builds/242122032

**Comment by BanzaiMan** [comment]
Your [`.travis.yml`](https://github.com/adamvoss/vscode-languagetool-languages/blob/0782e75eb25c41a88f5bcf2ae535f6e0e4b7adf6/.travis.yml#L1) specifies `language: java`, so `node_js` is ineffective. You need to switch the Node.js version yourself with `nvm install 8`.

**Comment by BanzaiMan** [comment]
(Similarly, if you switch to `language: node_js`, `jdk` would be ineffective.

**Comment by adamvoss** [comment]
Thanks!  That works.  I guess I got confused by [it being documented as  working under Ruby](https://docs.travis-ci.com/user/languages/ruby/#Testing-against-multiple-JDKs-(JRuby)), but I see that is only to facilitate JRuby.
