### ISSUE TITLE
TRAVIS_COMMIT_MESSAGE is not what it supposed to be

### ISSUE THREAD

**Issue by bsipocz** [travis-ci/travis-ci#7897]
In https://github.com/astropy/ci-helpers I've added a few workarounds to be able to run a smaller set of builds on travis. One of these is ``[docs only]`` that skips all testing but the docs building jobs. It uses ``TRAVIS_COMMIT_MESSAGE`` to see whether the contributor added the tag to the commit message. 
However in the following case ``TRAVIS_COMMIT_MESSAGE`` doesn't seem to report back the commit message we all see on github or in the git log, etc, but a merge info.
Would it be possible to return a more verbose commit message in case of these merges? (I assume the commit was a result of a cherry-pick/rebase/squash/etc, it seems totally ordinary to me):

Expected commit message:
```
Mark CCDData documentation as orphan for the moment [build docs] 
```

Returned commit message:
```
Merge e1f7f788a17cce34013f0271b890f5905c69ca3b into d36a3ec7d84e673d7aa761e8593340d68b3a5504
```

Example PR: https://github.com/astropy/astropy/pull/6173 commit: https://github.com/astropy/astropy/pull/6173/commits/e1f7f788a17cce34013f0271b890f5905c69ca3b

**Comment by BanzaiMan** [comment]
Which build shows this problem? On PR builds, we test the *merge* commit (not the head of the topic branch), so the value that you see seems correct to me.

**Comment by bsipocz** [comment]
e.g. this one: https://travis-ci.org/astropy/astropy/jobs/241413617#L380

Thanks for the explanation, indeed it's a PR, and all my testing was on non PR branch builds. I would say this case the variable is not doing what one naively expects. Is there the top of the branch commit message accessible via a variable, or should I use git to get it?

Basically most of this workaround is done to do #5032, we would definitely appreciate if ``[skip travis]`` would be natively supported.

**Comment by SeanTAllen** [comment]
I just got bit by this as well. Definitely not what I was expecting.
