### ISSUE TITLE
Casher takes 60 seconds to extract the cache for a project

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#7898]
In this job, 64 seconds are spent creating the directories/extracting the cache:
https://travis-ci.org/mozilla-neutrino/neutrino-dev/jobs/242170082

In addition, casher then spends 50 seconds calculating that the cache doesn't need updating/reuploading.

Whilst this project is caching quite a lot of files, it seems like there must be wins to be made on the casher side too.

**Comment by BanzaiMan** [comment]
This archive has over 200K files in them (I looked at the cache), and computing md5 checksums for these tiny files would be very time consuming, indeed.

As long as these tasks need to be performed, I am afraid there is not much we can do here. I looked at the current implementation, but did not find any obvious and quick wins.

You may consider creating your own archive to save on the number of files. For example, create an archive your own to be uploaded (`tar czf archive.tar.gz DIR1 DIR2 DIR3 …`), and expand this file in `before_install` (`tar xzf archive.tar.gz DIR1 DIR2 DIR3 …`).

**Comment by BanzaiMan** [comment]
A data point; the archive itself is 248MB, and expands to about 1.3 GB.

**Comment by BanzaiMan** [comment]
Caching the archive may render the cache vulnerable to the order in which the files are added to the archive.

**Comment by edmorley** [comment]
Thank you for taking a look, and so quickly!

I agree MD5 will be expensive on that many files! (Fwiw I hope that yarn adding native support for monorepos and hoisting will help avoid this situation eventually.)

From reading the [casher source](https://github.com/travis-ci/casher/blob/master/bin/casher) I see the hashes are being generated twice per job, even if the cache didn't change. Perhaps the hashes file could be saved into the uploaded archive, so at least the next run's extraction phase will be fast?

Another idea might be to add a `.travis.yml` cache option to force mtimes to be used, even if md5deep is available in the environment?

Many thanks for your help :-)

**Comment by BanzaiMan** [comment]
I ran `md5deep` recursively on the 246MB archive. The resulting file of md5 checksums is about 120 MB. I imagine it'll compress well (as it is a text file), but it will still add a lot of weight to the archive.

Going back to `mtime`-based check may sound appealing, but, with this many files, a single `touch` will soil your cache.

**Comment by edmorley** [comment]
Oh that's a lot larger than I imagined. Thank you for having tried anyway :-)

**Comment by BanzaiMan** [comment]
I'm closing this for now.
