### ISSUE TITLE
Deploy Script fails on ES6 import statement

### ISSUE THREAD

**Issue by dschinkel** [travis-ci/travis-ci#7899]
I am trying to run a .js script for the first time from my travis.yml.  When travis tries to run it, I get:

`Unexpected token import`

<img width="790" alt="screen shot 2017-06-12 at 3 08 12 pm" src="https://user-images.githubusercontent.com/338798/27068127-04f59446-4fd4-11e7-9b58-363af9250384.png">

so it's talking about the first import statement in my deploy-feature-branch.js code.

I'm not sure how to apply es2015 preset basically to this...or, is there something else I need to be doing?

My **travis.yml**:

```
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - npm install -g babel-cli
  - npm install
before_script:
  - yarn run build
  - yarn run test
script:
  - node ./src/client/deploy/deploy-feature-branch.js
```

and here's the first few lines of **deploy-feature-branch.js**
```
import * as deployApi from './deployApi'

const chalk = require('chalk'),
  _ = require('lodash'),
  green = chalk.green,
  info = chalk.yellow,
  Deploy = require('./deployApi')

  require('dotenv').config()

const { env } = process
  let options = {
    awsKey: env.AWS_ACCESS_KEY_ID,
    awsSecret: env.AWS_SECRET_ACCESS_KEY,
    localBuildFolder: 'build',
```
Here's the failed build: https://travis-ci.com/mayfieldrobotics/gizmo_web_app/builds/47985871#L388

**Comment by dschinkel** [comment]
resolved...

**Comment by caseychoiniere** [comment]
@dschinkel I know this is an old issue but any chance you can share how you solved this? I'm running into the same issue trying to build a react-node-mobx app in Travis. The build and deploy works fine outside of Travis but I can't figure out how to apply the babel presets for travis.
