### ISSUE TITLE
mvn fails in concurrency test over relational databases

### ISSUE THREAD

**Issue by cuent** [travis-ci/travis-ci#7901]
I'm using `mvn clean install` but when it starts running a concurrency test the process is killed [1]. The databases I'm using H2, PostgreSQL, MySQL databases. I don't see any build error, and it's working on my machine. Any thoughts? 

[1] https://travis-ci.org/cuent/Test-Travis/jobs/240613851

**Comment by BanzaiMan** [comment]
Most likely the job consumes too much resource and the host killed your process. Try `sudo: required` to get a beefier execution environment.

**Comment by cuent** [comment]
Thanks, @BanzaiMan it seems that the problem is related with MySQL, maybe the version.
