### ISSUE TITLE
travis deploy to heroku

### ISSUE THREAD

**Issue by Mundukm** [travis-ci/travis-ci#7904]
im new to travis, my goal is to deploy my project from github to heroku with travis
but after build nothing changed, only 'Email:' appears in window. Anybody knows what is the problem?
![tr](https://user-images.githubusercontent.com/23221883/27106079-87ba6b92-509a-11e7-81b7-a25a437bdc3a.PNG)

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

Also, please review https://docs.travis-ci.com/user/deployment/heroku and ensure that your deployment configuration has all the necessary authentication information.

**Comment by BanzaiMan** [comment]
https://github.com/ViktoriyaRyazhska/Lv-236.Java/blob/9532921f0954009f892bf51c9c4cb788df17a74e/.travis.yml#L13 Most likely you have an incorrectly encrypted API key.

**Comment by Mundukm** [comment]
Thanks for your feedback!! Look i have next situtation - i'm collabortor to this project on github, also i'm owner of heroku account. I generated that key on my local machine after login in heroku  [ travis encrypt $(heroku auth:token) --add deploy.api_key ]. May be i do something wrong? or may there are some instructions how to do that. Project is integrated with travis, so it builds after changes in branches (i set to buid branch i'm working on), maybe some access is required? Also a read arcticles in travis about key, so now i dont know what the problem is
