### ISSUE TITLE
Command that waits for a domain propagation via dns.lookupAsync() in nodejs hangs on travis

### ISSUE THREAD

**Issue by esalman-sfdc** [travis-ci/travis-ci#7908]
[build](https://travis-ci.org/forcedotcom/LightningTestingService/builds/242647977) is getting terminated after 10 mins with error message suggesting use of [travis-wait](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received)

I tried using the wait, but the [build](https://travis-ci.org/forcedotcom/LightningTestingService/builds/242654981) still hangs.

Command which is hanging runs in node-js environment and tries to wait for domain propagation via dns.lookupAsync() call and I suspect thats what is somehow hanging on travis (may be related to something like network proxies?). 

On local machines the command behaves as expected. It either succeeds or exits with an error code after 2/3 mins or so if its unable to resolve the domain with a clear error message. 
On travis, the command does neither, and eventually gets terminated.

**Comment by BanzaiMan** [comment]
There are no proxies on our build machines.

Please try reproducing the error with our Docker images. https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

I do not know how this function works, but it is very well related to the way DNS/name lookup is configured.

**Comment by esalman-sfdc** [comment]
Thanks for confirmation. Yes I downloaded the image last night. Will try using it for a local repo.

**Comment by BanzaiMan** [comment]
Recent builds are passing. Can we close this?
