### ISSUE TITLE
oraclejdk8 Way  outdated!

### ISSUE THREAD

**Issue by kingcraftingnl** [travis-ci/travis-ci#7910]
My project isnt compilling since the provided oraclejdk8 Its oudated

Travis
===========
: java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
===================
And the current version its: : 8u131

**Comment by BanzaiMan** [comment]
Duplicate of #7337.
