### ISSUE TITLE
Couchdb service on Trusty

### ISSUE THREAD

**Issue by Geolim4** [travis-ci/travis-ci#7912]
Hello,

I can't get couchdb working on trusty, is it available yet on that dist ?
https://travis-ci.org/PHPSocialNetwork/phpfastcache/jobs/242941121#L242

Cheers,
Georges

**Comment by BanzaiMan** [comment]
It is not yet available. https://docs.travis-ci.com/user/trusty-ci-environment#Data-Stores We will be working on getting on the new images in the near future.

**Comment by Geolim4** [comment]
Okay, fine then. Can you close this issue once the couchdb service is available on trusty ?

Thanks you :)

**Comment by Geolim4** [comment]
Should be done by now :)
