### ISSUE TITLE
Add latest PHP releases to Travis

### ISSUE THREAD

**Issue by ottlinger** [travis-ci/travis-ci#7914]
Similar to #7377 the newest PHP releases seem to be missing in the Travis stack:
* PHP 7.0.20 - https://travis-ci.org/ottlinger/hornherzogen/jobs/243018587
* PHP 7.1.6 - https://travis-ci.org/ottlinger/hornherzogen/jobs/243018588

https://github.com/travis-ci/php-src-builder is still failing.
Thanks

**Comment by BanzaiMan** [comment]
[7.0.20](https://travis-ci.org/travis-ci/php-src-builder/builds/243707398)
[7.1.6](https://travis-ci.org/travis-ci/php-src-builder/builds/243707401)

**Comment by ottlinger** [comment]
@BanzaiMan ありがとうございますいます
