### ISSUE TITLE
Travis build failed on .NET Framework 4.6.1

### ISSUE THREAD

**Issue by xavierfoucrier** [travis-ci/travis-ci#7917]
Hi Travis CI team,

I am new to Travis, and I don't know why my build always failed when runned with Travis.
https://travis-ci.org/xavierfoucrier/gmail-notifier/builds

The log is too long, and I get no "error message" from Travis.
May be my "travis.yml" file is not properly written.

My Visual Studio projet works on .NET Framework 4.6, and I get some NuGet packages inside it.
The final application aimed Windows 7/8/8.1/10.

Thanks @joshua-anderson, @akoeplinger and @nterry for you answer.
Best regards.

**Comment by Joshua-Anderson** [comment]
Does your program work with mono or .NET core on linux? These C# run times differ pretty substantially from traditional .NET, so make sure to test your code with those.

**Comment by xavierfoucrier** [comment]
I Joshua, thanks for your answer first.

No, my program work with classic .NET Framework. I am not using mono/.NET Core for the moment, and my program doesn't have ".Tests" code for the moment too. I work on Windows plateform, and I don't think that my program will be one day ported on Linux.

I have tested many configurations on the .yml file, always failed: don't know if this is the syntax, because, my solution folder is composed of two words with one space between them, may be the compiler can't find my solution file. In the log, it seems that Travis is not able to restore my packages with the command:

`nuget restore Gmail notifier/Gmail notifier.sln`

**Comment by xavierfoucrier** [comment]
I. My Travis CI configuration failed because my application path contains escape character. So I renamed the entire path and solution file to "/code/GmailNotifier.sln". It works great now.
