### ISSUE TITLE
Running test with node 8 cannot find dependency

### ISSUE THREAD

**Issue by epoberezkin** [travis-ci/travis-ci#7919]
https://travis-ci.org/epoberezkin/ajv/jobs/243437808

Other node versions work ok
Just before that building in node 8 worked too: https://travis-ci.org/epoberezkin/ajv/jobs/243424014

**Comment by BanzaiMan** [comment]
Seems like a retry succeeded.

**Comment by BanzaiMan** [comment]
I'm closing this now.

**Comment by OmgImAlexis** [comment]
We're getting the same issue with https://github.com/agenda/agendash/pull/56.

Only node 8 seems to be having this issue.

https://travis-ci.org/agenda/agendash/builds/262552788
