### ISSUE TITLE
Trusty BETA: JAVA_HOME is not defined correctly.

### ISSUE THREAD

**Issue by Songbird0** [travis-ci/travis-ci#7920]
Hi there !

I expected to see this happen: All jobs work properly.

Instead, this happened: `oraclejdk7` and `openjdk7`jobs crashed.

Feel free to look at my crashed jobs here: https://travis-ci.org/Songbird0/TS3BBCodeFormatter/builds/243486541, https://travis-ci.org/Songbird0/TS3BBCodeFormatter/builds/243485625.

To reproduce this issue, copy/paste the following `.travis.yml` file:

```yaml
language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
  - openjdk8
```

Error message for openjdk7:
```
$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

Error: JAVA_HOME is not defined correctly.

  We cannot execute /usr/lib/jvm/java-7-openjdk/bin/java
```

Error message for oraclejdk7:
```
$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

Error: JAVA_HOME is not defined correctly.

  We cannot execute /usr/lib/jvm/java-7-oracle/bin/java
```

To "fix" this issue, I wrote a new configuration:

```yaml
language: java
sudo: false
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
```

Unlike `oraclejdk7` and `openjdk7`, `oraclejdk8` and `openjdk8` work properly.

Best regards.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879. I'm closing this as a duplicate.
