### ISSUE TITLE
PHP 5.6.30 mysqli build runners do not have mysqli extension installed

### ISSUE THREAD

**Issue by marc1706** [travis-ci/travis-ci#7921]
Since around 18 hours ago, all of our builds are failing due to the mysqli extension not being installed in the PHP 5.6 build runners with the DB set to mysqli:
```
SQL ERROR [ mysqli ]<br /><br />mysqli_connect function does not exist, is mysqli extension installed? []<br /><br />An sql error occurred while fetching this page. Please contact an administrator if this problem persists.
```
See for example this build:
https://travis-ci.org/phpbb/phpbb/builds/243762799

Related .travis.yml:
https://github.com/phpbb/phpbb/blob/3.2.x/.travis.yml

**Comment by BanzaiMan** [comment]
This is quite curious. We did indeed repackaged PHP 5.6(.30) yesterday; you can see the build result here https://travis-ci.org/travis-ci/php-src-builder/jobs/243707389. Not a lot should have changed since the previous build of this archive (https://travis-ci.org/travis-ci/php-src-builder/jobs/209822026).

In particular, https://travis-ci.org/travis-ci/php-src-builder/jobs/243707389#L4837 shows that MySQL support is enabled.

I am not sure how this difference occurred.

**Comment by marc1706** [comment]
Thanks for linking to that build. The latest build seems to run this configure command for PHP (https://travis-ci.org/travis-ci/php-src-builder/jobs/243707389#L4474):
```
Configure Command =>  './configure'  '--with-config-file-path=/home/travis/.phpenv/versions/5.6.30/etc' '--with-config-file-scan-dir=/home/travis/.phpenv/versions/5.6.30/etc/conf.d' '--prefix=/home/travis/.phpenv/versions/5.6.30' '--libexecdir=/home/travis/.phpenv/versions/5.6.30/libexec' '--enable-intl' '--with-openssl' '--without-pear' '--with-gd' '--with-jpeg-dir=/usr' '--with-png-dir=/usr' '--with-freetype-dir=/usr' '--with-freetype' '--enable-exif' '--enable-zip' '--with-zlib' '--with-zlib-dir=/usr' '--with-mcrypt=/usr' '--with-pdo-sqlite' '--enable-soap' '--enable-xmlreader' '--with-xsl' '--enable-ftp' '--with-tidy' '--with-xmlrpc' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-shmop' '--with-pdo-mysql=mysqlnd' '--enable-pcntl' '--with-readline' '--enable-mbstring' '--with-curl' '--with-pgsql' '--with-pdo-pgsql' '--with-gettext' '--enable-sockets' '--with-bz2' '--enable-bcmath' '--enable-calendar' '--with-libdir=lib' '--enable-fpm' '--enable-maintainer-zts' '--with-gmp' '--with-kerberos' '--with-imap' '--with-imap-ssl' '--with-ldap=shared' '--with-ldap-sasl' '--enable-dba' '--with-cdb' '--with-inifile' '--with-mysql=mysqlnd'
```
While the previous build contained this (https://travis-ci.org/travis-ci/php-src-builder/jobs/209822026#L4290):
```
Configure Command =>  './configure'  '--with-config-file-path=/home/travis/.phpenv/versions/5.6.30/etc' '--with-config-file-scan-dir=/home/travis/.phpenv/versions/5.6.30/etc/conf.d' '--prefix=/home/travis/.phpenv/versions/5.6.30' '--libexecdir=/home/travis/.phpenv/versions/5.6.30/libexec' '--enable-intl' '--with-openssl' '--without-pear' '--with-gd' '--with-jpeg-dir=/usr' '--with-png-dir=/usr' '--with-freetype-dir=/usr' '--with-freetype' '--enable-exif' '--enable-zip' '--with-zlib' '--with-zlib-dir=/usr' '--with-mcrypt=/usr' '--with-pdo-sqlite' '--enable-soap' '--enable-xmlreader' '--with-xsl' '--enable-ftp' '--with-tidy' '--with-xmlrpc' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-shmop' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-pcntl' '--with-readline' '--enable-mbstring' '--with-curl' '--with-pgsql' '--with-pdo-pgsql' '--with-gettext' '--enable-sockets' '--with-bz2' '--enable-bcmath' '--enable-calendar' '--with-libdir=lib' '--enable-fpm' '--enable-maintainer-zts' '--with-gmp' '--with-kerberos' '--with-imap' '--with-imap-ssl' '--with-ldap=shared' '--with-ldap-sasl' '--enable-dba' '--with-cdb' '--with-inifile'
```

Note the difference with mysqli missing in the newer build. It seems like the script that outputs the configure options for your builds either failed or was misconfigured for some reason which resulted in the wrong options being used.

**Comment by laf** [comment]
We are also seeing the same thing at https://github.com/librenms/librenms.

For whatever reason, the actual configure command isn't including mysqli:

New build
```
Configure Command =>  './configure'  '--with-config-file-path=/home/travis/.phpenv/versions/5.6.30/etc' '--with-config-file-scan-dir=/home/travis/.phpenv/versions/5.6.30/etc/conf.d' '--prefix=/home/travis/.phpenv/versions/5.6.30' '--libexecdir=/home/travis/.phpenv/versions/5.6.30/libexec' '--enable-intl' '--with-openssl' '--without-pear' '--with-gd' '--with-jpeg-dir=/usr' '--with-png-dir=/usr' '--with-freetype-dir=/usr' '--with-freetype' '--enable-exif' '--enable-zip' '--with-zlib' '--with-zlib-dir=/usr' '--with-mcrypt=/usr' '--with-pdo-sqlite' '--enable-soap' '--enable-xmlreader' '--with-xsl' '--enable-ftp' '--with-tidy' '--with-xmlrpc' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-shmop' '--with-pdo-mysql=mysqlnd' '--enable-pcntl' '--with-readline' '--enable-mbstring' '--with-curl' '--with-pgsql' '--with-pdo-pgsql' '--with-gettext' '--enable-sockets' '--with-bz2' '--enable-bcmath' '--enable-calendar' '--with-libdir=lib' '--enable-fpm' '--enable-maintainer-zts' '--with-gmp' '--with-kerberos' '--with-imap' '--with-imap-ssl' '--with-ldap=shared' '--with-ldap-sasl' '--enable-dba' '--with-cdb' '--with-inifile' '--with-mysql=mysqlnd'
```
Old build:

```
Configure Command =>  './configure'  '--with-config-file-path=/home/travis/.phpenv/versions/5.6.30/etc' '--with-config-file-scan-dir=/home/travis/.phpenv/versions/5.6.30/etc/conf.d' '--prefix=/home/travis/.phpenv/versions/5.6.30' '--libexecdir=/home/travis/.phpenv/versions/5.6.30/libexec' '--enable-intl' '--with-openssl' '--without-pear' '--with-gd' '--with-jpeg-dir=/usr' '--with-png-dir=/usr' '--with-freetype-dir=/usr' '--with-freetype' '--enable-exif' '--enable-zip' '--with-zlib' '--with-zlib-dir=/usr' '--with-mcrypt=/usr' '--with-pdo-sqlite' '--enable-soap' '--enable-xmlreader' '--with-xsl' '--enable-ftp' '--with-tidy' '--with-xmlrpc' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-shmop' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-pcntl' '--with-readline' '--enable-mbstring' '--with-curl' '--with-pgsql' '--with-pdo-pgsql' '--with-gettext' '--enable-sockets' '--with-bz2' '--enable-bcmath' '--enable-calendar' '--with-libdir=lib' '--enable-fpm' '--enable-maintainer-zts' '--with-gmp' '--with-kerberos' '--with-imap' '--with-imap-ssl' '--with-ldap=shared' '--with-ldap-sasl' '--enable-dba' '--with-cdb' '--with-inifile'
```

**Comment by sgiehl** [comment]
Same at https://github.com/piwik/piwik

@BanzaiMan Can you give any estimate when this will get fixed?

**Comment by BanzaiMan** [comment]
Sorry, I don't have an ETA.

@marc1706 Thanks for your eagle eyes on spotting that difference in the `Configure Command` output. As I mentioned earlier, we define the same flags to be passed to `php-build`. If `--with-mysqli` is getting dropped in the process, I tend to think it is getting dropped by `php-build`.

I've opened https://github.com/php-build/php-build/issues/443 to inquire how this can come about.

In the meantime, could you try 5.6.29, which should use the old build process?

**Comment by laf** [comment]
@BanzaiMan Setting to 5.6.29 does indeed work around this issue for now.

Thanks.

**Comment by robbieaverill** [comment]
@BanzaiMan could you make 5.6.29 the default 5.6 build version unless 5.6.30 is specifically requested until this is resolved? I'd rather not have to update a tonne of packages to use 5.6.29 just for this when they're currently referencing "5.6".

Also - thanks for looking into it :)

**Comment by mattab** [comment]
> could you make 5.6.29 the default 5.6 build version unless 5.6.30 is specifically requested until this is resolved?

Excellent idea, please @BanzaiMan would you consider making this change as to avoid dozens/hundreds of projects hitting this problem? Since we run PHP tests on more than 30 repositories it is time consuming to update them all. And all of them run on the weekly cron and will all start failing as soon as the weekly cron triggers. Would be a big pain and time waster. Thank you!

**Comment by BanzaiMan** [comment]
The `5.6` archive is now a copy of the `5.6.29` one.

**Comment by rxu** [comment]
Restarted some tests but it still installs 5.6.30 https://travis-ci.org/phpbb/phpbb/jobs/244953999#L142

**Comment by BanzaiMan** [comment]
@rxu Sorry. I forgot to repeat the steps for Precise. Please retry.

**Comment by rxu** [comment]
@BanzaiMan Thanks, but now it claims PHP 5.6 is not installed: https://travis-ci.org/phpbb/phpbb/jobs/244980443#L140

**Comment by BanzaiMan** [comment]
@rxu Sorry again! The files were not publicly readable. They should be now. Could you try again?

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/jobs/244998561#L139

**Comment by mattab** [comment]
Thanks @BanzaiMan - very appreciated!

**Comment by VSEphpbb** [comment]
@BanzaiMan seems like PHP 5.6 is back to be broken again by this issue.

**Comment by VSEphpbb** [comment]
@BanzaiMan 
https://travis-ci.org/phpbb/phpbb/jobs/246871687#L145
https://travis-ci.org/phpbb/phpbb/builds/246871679?utm_source=github_status&utm_medium=notification

**Comment by laf** [comment]
It's working for us sitting the php version as an FYI.

**Comment by VSEphpbb** [comment]
@laf we projects should not have to workaround travis' bug/issue ;)

**Comment by laf** [comment]
But it's not a travis bug though is it?

**Comment by mattab** [comment]
we run PHP tests on more than 30 repositories it is time consuming to update them all. And all of them run on the weekly cron and will all start failing as soon as the weekly cron triggers. 

Would be great to set default version to the last one that worked

**Comment by BanzaiMan** [comment]
Sorry about the troubles. There is a tooling issue where  the `5.6` archive was updated daily with the `5.6.30` content. I'm looking into this now.

The current `5.6` should point to `5.3.29`.

**Comment by BanzaiMan** [comment]
The tooling issue has been fixed, so the current `5.6` should not be overwritten automatically (as it had been the last few days).

**Comment by VSEphpbb** [comment]
Thanks BanzaiMan

**Comment by BanzaiMan** [comment]
With https://github.com/php-build/php-build/issues/443 now fixed, I've triggered a new 5.6.30 build (https://travis-ci.org/travis-ci/php-src-builder/builds/251729642). If the fix is good (and the build passes), the new archive will have this extension enabled. Please test it and report results. If it looks good, I'll trigger another build, so that the alias 5.6 will point to it.

**Comment by laf** [comment]
Thanks for tracking and updating. I'm not able to test right now but appreciate the response.

**Comment by BanzaiMan** [comment]
Has anyone tested this?

**Comment by robbieaverill** [comment]
We haven't seen any 5.6 related problems across our SilverStripe builds recently :-)

**Comment by laf** [comment]
@VSEphpbb @mattab ?

**Comment by mattab** [comment]
Builds are green :+1:

**Comment by sgiehl** [comment]
@mattab  our builds are still running php 5.6.29

**Comment by BanzaiMan** [comment]
https://travis-ci.org/phpbb/phpbb/jobs/252169006 (from https://github.com/phpbb/phpbb/pull/4869) seems to show that it was successful.

I've started https://travis-ci.org/travis-ci/php-src-builder/builds/252175979, which will replace the current 5.6 with 5.6.30.

**Comment by BanzaiMan** [comment]
`5.6` is now an alias for `5.6.30`, which now includes mysqli.

**Comment by robbieaverill** [comment]
🎉 Thanks @BanzaiMan
