### ISSUE TITLE
Travis not building

### ISSUE THREAD

**Issue by andela-aalabi** [travis-ci/travis-ci#7923]
My tests are not building on travis.

I am doing some migrations and seeding as a "before hook" in my tests.

I don't know if this is the wrong platform but I can't find any where else to report.

My last attempt to run build was [here](https://travis-ci.org/andela-aalabi/DMS-papyrus/jobs/244185574)

I'd appreciate any feedback asap.

**Comment by ismay** [comment]
Same here. Just stuck on `Hang tight, the log cannot be shown until the build has started.` Even though there a no other active builds:

Build stuck in queue:

<img width="950" alt="screen shot 2017-06-18 at 12 31 39" src="https://user-images.githubusercontent.com/7355199/27260038-1b89e796-5422-11e7-8920-71d73486d892.png">

No other active builds in queue:

<img width="951" alt="screen shot 2017-06-18 at 12 31 01" src="https://user-images.githubusercontent.com/7355199/27260033-07867aac-5422-11e7-8948-4d6f46c4668e.png">

**Comment by andela-aalabi** [comment]
Thanks a lot.

I worked all night o get the tests up and running and my last push didn't
affect the tests so I was wondering what could have caused the break!

Hanging on.

On Jun 18, 2017 11:32 AM, "ismay" <notifications@github.com> wrote:
>
> Same here. Just stuck on Hang tight, the log cannot be shown until the
build has started. Even though there a no other active builds:

**Comment by ipa-mdl** [comment]
Looks like the maintenance last night did not went as expected, the builds got stuck and all new jobs get queued [(>4.7k at the moment)](https://www.traviscistatus.com/)

**Comment by ismay** [comment]
@ipa-mdl Yeah I expected something like that. Well hopefully it'll be resolved soon.

**Comment by andela-aalabi** [comment]
Thanks. I thought as much.
Fortunately, my last build before the massive queue was successful.
I'd just hang on.
Cheers!

**Comment by dinos80152** [comment]
I have this issue as well, it happened 2 hours ago, still doesn't work now.
[Build History](https://travis-ci.org/liam-lai/ptt-alertor/builds)

**Comment by andela-aalabi** [comment]
Just making sure I was not alone. :-)
I guess it'd get sorted out soon

**Comment by dinos80152** [comment]
@andela-aalabi 
My Build is running now, wish yours as well.

**Comment by ismay** [comment]
@dinos80152 Yup, resolved for me as well.

**Comment by andela-aalabi** [comment]
Sane here! *☺ *
Success!

**Comment by BanzaiMan** [comment]
Hello, everyone. Sorry for the delay. This was due to https://www.traviscistatus.com/incidents/l26xy07hwr5q, which has been resolved.

I'm closing this now.

**Comment by retorquere** [comment]
traviscistatus is all green, but my jobs at https://travis-ci.org/fiduswriter/biblatex-csl-converter/builds don't seem to be going anywhere.

**Comment by retorquere** [comment]
Oops, I guess patience is all it took. My jobs just started.
