### ISSUE TITLE
Build fails after merge (but passes on PR)

### ISSUE THREAD

**Issue by astaric** [travis-ci/travis-ci#7927]
One of the builds in our build matrix has been consistently been marked as failed on master branch without any indication why. The same build is marked as passed when PR is tested but fails once it is merged.

Passing:
https://travis-ci.org/biolab/orange3/jobs/244870268

Failing:
https://travis-ci.org/biolab/orange3/jobs/244874145

The [script step](https://github.com/biolab/orange3/blob/master/.travis/stage_script.sh) is pretty trivial (the failing build runs only the first 10 rows of the file): install some packages run a script, collect its exit status and exit with it. I have added some debugging output which shows, that the script exits with 0 in both cases (on PR and on master).

This has been going on for a while. The last passing build on master:
https://travis-ci.org/biolab/orange3/builds/228705342
and the first failing one:
https://travis-ci.org/biolab/orange3/builds/228885696

**Comment by edmorley** [comment]
I don't work for Travis, but I was curious so took a look.

The time of the last passing master job was 2017-05-04 11:59Z, and the first failing was 2017-05-04 20:27Z, and your jobs back then were using the precise container stack, which was updated on the same day:
https://blog.travis-ci.com/2017-05-04-precise-image-updates

That said, the "Build image provisioning date and time" reported in the log is the same for each (presuming the image that's referring to is what the blog post was about), so perhaps that's unrelated.

I did notice that the passing job used travis-build 3d71c3935, whereas the failing used 66bd59b85. The changelog is:
https://github.com/travis-ci/travis-build/compare/3d71c3935...66bd59b85

...which adds the secure environment variable filtering mentioned here:
https://blog.travis-ci.com/2017-05-08-security-advisory

Do PRs see the same secure variables as master? If not, that might explain the difference?

**Comment by astaric** [comment]
The [culprit](https://docs.travis-ci.com/user/customizing-the-build#How-does-this-work%3F-(Or%2C-why-you-should-not-use-exit-in-build-steps)) was the exit in our [stage_script](https://github.com/biolab/orange3/blob/master/.travis/stage_script.sh#L10).

The script is sourced (not executed) in .travis.yml, so I guess the no-exit policy applies.

No idea why it passed on PR, but since I have managed to solve the problem (replacing exit with return) I am closing the issue.
