### ISSUE TITLE
Gradle built of simple IntelliJ Plugin fails

### ISSUE THREAD

**Issue by halirutan** [travis-ci/travis-ci#7930]
I'm using a simple `build.gradle` to build an IntelliJ plugin using the Gradle plugin `org.jetbrains.intellij`. It works out of the box on my machine, but fails on Travis in the initial `gradle assemble` step with an exception

```
java.lang.NoClassDefFoundError: org/gradle/jvm/tasks/Jar
```

Running Gradle with debugging turned can be used to see the full stack trace and here are the important information:

- [Logfile of travis](https://hastebin.com/ugonohevaw.cs). I delete everything before Gradle downloads the IDEA sources.
- Here is the repository with [`travis.yml`](https://github.com/halirutan/IntelliJ-Key-Promoter/blob/master/.travis.yml) and the [`build.gradle`](https://github.com/halirutan/IntelliJ-Key-Promoter/blob/master/build.gradle)

Why doesn't this work? On my machine, I tested Gradle 2.10 and 3.5. Both worked fine.

**Comment by BanzaiMan** [comment]
Could you try reproducing the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)?

**Comment by halirutan** [comment]
@BanzaiMan Without knowing anything about Docker, I installed everything. I'm on 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

When I see this correctly, then the worker on Travis uses

![worker info](http://i.imgur.com/rkNiEg9.png)

the `travis-ci-jvm` image, but the `docker pull` gives

```
sudo docker pull travisci/ci-jvm
Using default tag: latest
Error response from daemon: manifest for travisci/ci-jvm:latest not found
```

Will it help if I use the `jvm` image from the table?

**Comment by halirutan** [comment]
I was able to make it work. Using the Gradle wrapper script, including

```
task wrapper(type: Wrapper) {
    gradleVersion = '3.5'
}
```

in my `build.gradle` and using a `travis.yml` like this

```
language: java
jdk: oraclejdk8
sudo: required
env:
  global:
    - GRADLE_USER_HOME=`pwd`/.gradle

before_script:
    - chmod +x gradlew
```

did the trick
