### ISSUE TITLE
on osx, sudo chsh hangs forever waiting for sudo password

### ISSUE THREAD

**Issue by AlJohri** [travis-ci/travis-ci#7932]
here is a build where the error occurs: https://travis-ci.org/WPMedia/laptop/builds/245221895

the line of code triggering the issue is:

```
sudo chsh -s /usr/local/bin/zsh "$USER"
```

the output looks like:

```
Changing shell for travis.
Password for travis: 
```

and then it hangs

**Comment by AlJohri** [comment]
seems to have fixed it self with no changes to that line? here is a subsequent build: https://travis-ci.org/WPMedia/laptop

**Comment by BanzaiMan** [comment]
Does the issue persist if you restart https://travis-ci.org/WPMedia/laptop/builds/245221895 now?

**Comment by AlJohri** [comment]
@BanzaiMan this was my fault. I have a script that concatenates scripts into a larger one that gets run. I missed to run this build step before pushing.
