### ISSUE TITLE
Updated package-lock.json is ignored

### ISSUE THREAD

**Issue by gushecht** [travis-ci/travis-ci#7936]
My team just started using the package-lock.json file with npm and our builds began to fail.  The error is two missing dependencies.

When we turn off caching, the build succeeds.  My guess is that our cached node_modules directory is taking precedence over what's specified in package-lock.json.

It seems as though support was added for [caching and yarn.lock](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn).  Can similar support be added for npm's package-lock.json?

**Comment by dbraga** [comment]
+1

**Comment by BanzaiMan** [comment]
Not sure what is expected here. If the cache trips up the dependencies, it sounds like this is an issue with the tool (I assume it is `npm`). Am I mistaken?

When you say "support for `package-lock.json`", what does that mean? Are you asking to run a certain command when this file exists?

**Comment by BanzaiMan** [comment]
Could this be related to the older npm version?

**Comment by limonte** [comment]
`package-lock.json` is a joke:

- https://stackoverflow.com/q/45022048/1331425
- https://github.com/npm/npm/issues/17979

**Comment by BanzaiMan** [comment]
Calling it “a joke” seems counterproductive, but it does seem that this is a tooling issue that is best addressed by `npm`.

Is it OK to close this?

**Comment by nickmccurdy** [comment]
If `package-lock.json` is git ignored, should it be added to the cache just like `node_modules`? Besides not having npm 5 on older versions of Node by default, that's the only issue I'm having with `package-lock.json` on Travis currently.

**Comment by BanzaiMan** [comment]
@nickmccurdy If `package-lock.json` is not in the git repository, it does not get cloned when your build runs.

**Comment by nickmccurdy** [comment]
Thanks, I'm aware of this. My question (which I guess is more specific to npm) is if npm will use the same versions of dependencies in a cached `node_modules` directory whether or not `package-lock.json` is present.

**Comment by nickmccurdy** [comment]
Bump

**Comment by usmanaliqureshi** [comment]
Another alternative way is to use `npm audit` which will display all the vulnerable / out-dated dependencies in your **package.json or package-lock.json** and then you can simply follow the instructions shown along with the other information by the audit.
