### ISSUE TITLE
Using "considerably larger image" for Trusty is broken

### ISSUE THREAD

**Issue by fishilico** [travis-ci/travis-ci#7939]
Hello,
According to the documentation (https://docs.travis-ci.com/user/trusty-ci-environment#Image-differences-from-Precise), there is a Trusty image which contains "a considerably larger image which contains (almost) all runtimes and services present in Precise environments.". What is the official way of building with this image?

Here is my use-case. It seems I have been using this image for months to build SELinux tools and libraries with:

- Two C compilers (gcc and clang)
- Several versions of Python (for SELinux Python bindings): 2.7, 3.3, 3.4, 3.5 and PyPy
- Several version of Ruby (for SELinux Ruby bindings): 2.0, 2.1, 2.2, 2.3

The `travis.yml` configuration (https://github.com/fishilico/selinux/blob/f027db4f2f6f104ade02b5345c74281378966e9e/.travis.yml) relied on Python interpreters being installed in `/home/travis/virtualenv/` and Ruby interpreters in `/home/travis/.rvm/rubies`.

Since today the build can no longer find Ruby 2.0 and 2.1 and Python 3.3 (cf. https://travis-ci.org/fishilico/selinux/jobs/245453111 for example). However theses versions are still supported (according to https://docs.travis-ci.com/user/languages/ruby/#Supported-Ruby-Versions-and-RVM and https://docs.travis-ci.com/user/languages/python/). How can I configure a build in order to include all the versions I need in the build environment?

By the way, this might be related to the upgrade to the new Trusty images (https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch).

**Comment by fishilico** [comment]
Hi, the documentation still mentions two Trusty images (https://docs.travis-ci.com/user/reference/trusty/#Image-differences-from-Precise):

> For our Trusty based environments, we’re making a smaller set of images that includes:
> * A minimal image which contains a small subset of interpreters, as well as docker and packer.
> * A considerably larger image which contains roughly the same runtimes and services present in Precise environments.

What is the official way to trigger the use of the second image in projects?

**Comment by fishilico** [comment]
The documentation still tells about two Trusty images, without explaining how the "considerably larger image" can be used. So this issue is not stale, even though it has been opened more that one year ago.

**Comment by BanzaiMan** [comment]
@plaindocs Could you take a look at this, please?

**Comment by plaindocs** [comment]
Hi @fishilico 

Looks like this is what you need. https://docs.travis-ci.com/user/languages/minimal-and-generic/

I'll have a look at how to integrate that better with the existing Trusty docs as well.
