### ISSUE TITLE
Sauce Connect fails to start on osx images

### ISSUE THREAD

**Issue by alsorokin** [travis-ci/travis-ci#7945]
Sauce Connect fails to start on osx images, while working just fine on linux:
https://travis-ci.org/apache/cordova-plugin-battery-status/builds/245683139

Here's an example of output:
```
Starting Sauce Connect
9.26s$ travis_start_sauce_connect
Using temp dir /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/sc.XXXX.NsuIshJq
/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/sc.XXXX.NsuIshJq ~/build/apache/cordova-plugin-battery-status
Downloading Sauce Connect
Extracting Sauce Connect
Archive:  sc-osx.zip
   creating: sc-4.4.7-osx/
  inflating: sc-4.4.7-osx/COPYRIGHT.md  
   creating: sc-4.4.7-osx/config_examples/
   creating: sc-4.4.7-osx/config_examples/upstart/
  inflating: sc-4.4.7-osx/config_examples/upstart/README.md  
  inflating: sc-4.4.7-osx/config_examples/upstart/sc.conf  
  inflating: sc-4.4.7-osx/config_examples/upstart/sc_worker.conf  
   creating: sc-4.4.7-osx/config_examples/systemd/
  inflating: sc-4.4.7-osx/config_examples/systemd/sc@.service  
  inflating: sc-4.4.7-osx/config_examples/systemd/sc.service  
  inflating: sc-4.4.7-osx/config_examples/systemd/README.md  
   creating: sc-4.4.7-osx/bin/
  inflating: sc-4.4.7-osx/bin/sc     
  inflating: sc-4.4.7-osx/license.html  
Waiting for Sauce Connect readyfile
/Users/travis/build.sh: line 362: sc-osx.zip/bin/sc: Not a directory
readyfile not created
~/build/apache/cordova-plugin-battery-status

The command "eval travis_start_sauce_connect " failed. Retrying, 2 of 3.
```

Please note that this is not an intermittent failure, it fails every time, so the build is failed.

**Comment by BanzaiMan** [comment]
Thanks for the report. Looks like the output format of `unzip -l` is not meeting what we expect at this time, and the extraction of the `sc` command is failing.

**Comment by fnolla-carecloud** [comment]
When will this be fixed :( See pr is open

**Comment by BanzaiMan** [comment]
The fix has been merged and deployed.

**Comment by adriano-di-giovanni** [comment]
Sauce Connect fails to start **everytime** on OS X images.
https://travis-ci.org/adriano-di-giovanni/cordova-plugin-shared-preferences/jobs/334833608

I can't figure out why. The `.travis.yml` file is the same as the one from [cordova-plugin-device](https://github.com/apache/cordova-plugin-device/blob/master/.travis.yml) (that is known to be working).

The error seems to be

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/sc.XXXX.PfqqhmZJ/sc-4.4.11-osx/bin/sc (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: _clock_gettime
  Referenced from: /private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/sc.XXXX.PfqqhmZJ/sc-4.4.11-osx/bin/sc (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```

Do I have to upgrade OS X images or there is something to fix?

Thanks,
Adriano

**Comment by BanzaiMan** [comment]
@adriano-di-giovanni Looks like the newer version of `sc` now requires OS X 10.12. Try updating your image accordingly. https://docs.travis-ci.com/user/reference/osx/#OS-X-Version

**Comment by adriano-di-giovanni** [comment]
Thanks, @BanzaiMan
