### ISSUE TITLE
Erlang/OTP 20

### ISSUE THREAD

**Issue by goncalotomas** [travis-ci/travis-ci#7947]
The latest major version of Erlang (20) was made available yesterday. From browsing other issues like #6679, it seems like a request is needed in order for that particular version to be made available.

Also, if there is a way to submit a pull request to support this (and subsequent versions) I'd like to know :)

**Comment by goncalotomas** [comment]
Also, since I'm asking for the binaries to be made available, would it also be possible to add Erlang 19.3 and Erlang 20 to the OS X binaries?

**Comment by chulkilee** [comment]
@BanzaiMan I see you triggered https://travis-ci.org/travis-ci/travis-erlang-builder/jobs/246199948/config - `VERSION` should be just `20.0`, not `OTP-20.0`.

**Comment by BanzaiMan** [comment]
This should be available now.
