### ISSUE TITLE
Redis service broken

### ISSUE THREAD

**Issue by tbarbugli** [travis-ci/travis-ci#7948]
```
$ sudo service redis-server start
Starting redis-server: /etc/init.d/redis-server: 58: ulimit: error setting limit (Operation not permitted)
```

Happens all the time with   "dist": "trusty", "sudo": false

**Comment by nightpool** [comment]
Our project is also experiencing this as well—it means all of our builds are failing until we get this fixed.

**Comment by tbarbugli** [comment]
looks like it's a duplicate of #7941
