### ISSUE TITLE
Yarn downgraded from v0.24.6 to v0.17.8 after Trusty 2017Q2 update

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#7951]
After yesterday's Trusty image update, our Trusty container nodejs jobs ([.travis.yml](https://github.com/mozilla/treeherder/blob/dac80b1fa492481cf2d31c83d8ff0c0a3113f56a/.travis.yml#L35-L58)) are now failing with:
```
$ yarn install --frozen-lockfile --no-bin-links
  error: unknown option `--frozen-lockfile'
```
(From: https://travis-ci.org/mozilla/treeherder/jobs/245713688)

Compare to the last successful run:
https://travis-ci.org/mozilla/treeherder/jobs/245336921

Of note, the jobs previously contained a Travis-instigated "Installing yarn" step (presumably since yarn didn't exist at all), which installed the latest released yarn version (which is currently v0.24.6). 

However now there is no such step, and the pre-installed version of yarn is now the much older v0.17.8 - which doesn't support the `--frozen-lockfile` option.

We had tested the new Trusty images for the sudo-enabled parts of our Travis run, however `group: edge` wasn't available for the container builds (plus the container changes aren't documented - #7950), so the breakage came as a surprise to us.

Please can the base image be updated to use at least the same version that was installed before (0.24.6)?

Many thanks!

**Comment by edmorley** [comment]
I've opened travis-ci/travis-cookbooks#854 to fix this, however unless there is a plan to roll out updated images soon, it won't help short term.

The next best fix might be to update the runtime-install script such that it checks what yarn version is installed, rather than skipping if yarn simply exists at all:
https://github.com/travis-ci/travis-build/blob/b1c1ff156509d53538e05082fca4dab2761dfed5/lib/travis/build/script/node_js.rb#L211

**Comment by BanzaiMan** [comment]
If you need the latest version of `yarn`, you can update it at runtime:

```yaml
env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  # or curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version [version]
```

**Comment by edmorley** [comment]
Thank you - we're already doing that for the sudo-enabled jobs (where yarn isn't installed at all), so we're going to use that as a workaround for container builds in the meantime.

**Comment by dmason30** [comment]
@edmorley Is there going to be a change to add the automatically upgrade of yarn to trusty dists like it does on precise? 

I am using your solution above but seems unnecessary that I will have to do this in every project where I am using yarn (which is basically every project).

**Comment by edmorley** [comment]
The pre-installed yarn for Trusty was updated to 0.27.5 in travis-ci/travis-cookbooks#866.

> @edmorley Is there going to be a change to add the automatically upgrade of yarn to trusty dists like it does on precise?

I'm not sure (I don't work for Travis CI). Perhaps open a new issue?

**Comment by Narretz** [comment]
@edmorley when will this become the default / publicly available? Or do we need to change a config entry for this?

**Comment by edmorley** [comment]
This should already work, I don't know why it isn't. Someone from Travis will have to answer either here or in travis-ci/packer-templates#478...

**Comment by Lyoness** [comment]
Thanks @edmorley for holding down the fort <3.  Many peeps on vacation this week.  

https://github.com/travis-ci/packer-templates/issues/478#issuecomment-321664593

likely a collision with run-time changes happening travis-build.  Will debug / test.

**Comment by edmorley** [comment]
Hmm actually if I use `group: edge` I get the newer version of yarn. I thought there had been a new image rollout since the change landed, but perhaps not? (Or else it was rolled back?)
