### ISSUE TITLE
Error while trying to fetch the log

### ISSUE THREAD

**Issue by carlosperate** [travis-ci/travis-ci#7952]
I'm trying to get the logs from old builds (November, so over 6 months ago) and I get the following:

```
There was an error while trying to fetch the log.
```

Is the a limit on how long the logs are kept around?

These are the three examples I am interested in:
https://travis-ci.org/mu-editor/mu/builds/175643592
https://travis-ci.org/mu-editor/mu/builds/177250885
https://travis-ci.org/mu-editor/mu/builds/175643562

**Comment by jakirkham** [comment]
Yep, getting this too. Started happening during the build and continued after it passed. Though it just now appears to work. 😕

<img width="1552" alt="screen shot 2017-07-07 at 12 29 13" src="https://user-images.githubusercontent.com/3019665/27967186-10ef0fc6-6310-11e7-84bd-205a3a2badbd.png">

ref: https://travis-ci.org/jakirkham/splauncher/jobs/251217794

**Comment by carlosperate** [comment]
Thanks for confirming the issue @jakirkham, glad it ended up working again in your project. Unfortunately my logs are still missing :(

**Comment by BanzaiMan** [comment]
There are data integrity issues with the affected logs. We are looking into it. Sorry for the inconvenience.

**Comment by Flaburgan** [comment]
I just had that here too: https://travis-ci.org/diaspora/diaspora/jobs/254831737
It's a manually relaunched job.

**Comment by wlandau-lilly** [comment]
Same here: https://travis-ci.org/wlandau-lilly/drake/builds/316750892

**Comment by BanzaiMan** [comment]
Those logs should be available now.

**Comment by carlosperate** [comment]
@BanzaiMan If you look at any of the builds linked in the original post you'll notice that **none** of those are available (all show as `null`), and they were definitely available in the past as we saved those specific links to reference an issue we were experiencing with our tests.

**Comment by cjcolvar** [comment]
Just got this now all of sudden while I was trying to download logs from earlier today to compare them in order to debug an issue.  It appears to affect nearly all of my builds including one currently running!

**Comment by jakirkham** [comment]
Also seeing it with this one: https://travis-ci.org/conda-forge/staged-recipes/builds/326220976

<img width="1552" alt="screen shot 2018-01-07 at 23 07 44" src="https://user-images.githubusercontent.com/3019665/34658759-9db7cc38-f3ff-11e7-8f35-bebfea380b2e.png">

**Comment by luke-jr** [comment]
Totally new build... https://travis-ci.org/luke-jr/bips/builds/331094564

**Comment by craftyguy** [comment]
Yep, also seeing this when trying to enable a new repo..

**Comment by ethanent** [comment]
Can confirm that this is happening for me also and has been for the past few weeks.

**Comment by diegolanda** [comment]
Getting this on a newly created repo
https://travis-ci.org/nearshorecode/web-ui/builds/342193295

**Comment by kortschak** [comment]
Same problem here https://travis-ci.org/gonum/gonum/jobs/349097723. Build just run.

**Comment by lmeyerov** [comment]
Same: https://travis-ci.org/graphistry/pygraphistry/jobs/349131068

**Comment by kortschak** [comment]
Now they're back! Yours too @lmeyerov.

**Comment by vernvern** [comment]
Same here: [There was an error while trying to fetch the log.](https://travis-ci.org/vernvern/blog/builds/354155715)

**Comment by dmtucker** [comment]
+1 https://travis-ci.org/dmtucker/netsync/builds/357965248

**Comment by tonyarnold** [comment]
I'm seeing it here now: https://travis-ci.org/tonyarnold/Differ/jobs/362450774

**Comment by Taher-Ghaleb** [comment]
All jobs in the following build have their log contents unavailable.
[https://travis-ci.org/fog/fog/builds/2144841](https://travis-ci.org/fog/fog/builds/2144841)

The logs of most of the builds presented in the comments on this issue are shown, while mine isn't. Hope you find a solution for this.

Thanks.

**Comment by rpaulo** [comment]
Started happening just now:

https://travis-ci.org/artisan-roaster-scope/artisan/builds/363399681

**Comment by spirinvladimir** [comment]
I can not see logs. Here:
[webRunes/WRIO-InternetOS](https://travis-ci.org/webRunes/WRIO-InternetOS/builds/368467676?utm_source=github_status&utm_medium=notification)

**Comment by PeterDaveHello** [comment]
Same here: https://travis-ci.org/PeterDaveHello/ColorEchoForShell/jobs/369931930, restart not working ...

**Comment by carlosperate** [comment]
The issue could be closed, but the logs were never recovered, and absolutely nobody from Travis even bothered to look into why the logs had been permantly "nulled".
