### ISSUE TITLE
Unable to locate package jq

### ISSUE THREAD

**Issue by jonhkr** [travis-ci/travis-ci#7954]
I'm getting this build errors today. Do you know what may be happening?

<img width="1069" alt="screen shot 2017-06-22 at 3 14 40 pm" src="https://user-images.githubusercontent.com/767866/27449625-69ddf87a-575f-11e7-92f6-c57c466fb56b.png">

**Comment by cotsog** [comment]
@jonhkr: we aren't sure yet but it seems like and upstream issue.

As a workaround, we are suggesting to either move your builds on Trusty with `dist: trusty` or install `jq` manually e.g.

```yaml
before_install:
  - mkdir -p ~/bin && curl -sSL -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x ~/bin/jq
  - export PATH=PATH:~/bin
  - jq --version
```

Please let us know if this helps.

Thanks!

**Comment by BanzaiMan** [comment]
Also, `jq` should be pre-installed on all images, so there shouldn't be any reason to install it via `apt-get`.

**Comment by cotsog** [comment]
@jonhkr: I believe the issue was on our side in the end. Sorry for my wrong assumption.

We've just deployed a fix. Can you confirm if you can now install `jq` with `apt-get` again?

Otherwise, as @BanzaiMan mentionned, `jq` is already pre-installed on all our images.

Thanks!

**Comment by jonhkr** [comment]
Oh, didn't know that it was already pre-installed. I just tested and it is working. Thank you.
