### ISSUE TITLE
Cannot find a way to get any JDK on a generic sudo-required Trusty machine

### ISSUE THREAD

**Issue by kenzierocks** [travis-ci/travis-ci#7958]
I'm trying to get my Java addition to a project to build with their Travis configuration. They have C, JS, and Python already building together, so I thought I could throw Java in there as well. Unfortunately, there seems to be no way to get `oracle-java8-installer` to work as it requires agreeing to a license BEFORE running `apt`. See https://travis-ci.org/scanse/sweep-sdk/jobs/246118057#L709. To view my many other attempts to get this building at all, see https://github.com/Team5818/sweep-sdk/commits/feature/java-jna.

**Comment by BanzaiMan** [comment]
I tried a few things to reproduce this license problem, but I have not been able to.

See, for example, https://travis-ci.org/BanzaiMan/travis_production_test/jobs/265005920#L757

Perhaps the newer Trusty image has what you need, even for the `language: generic` one.

Could you try restarting the build? (Or push a new commit?)

**Comment by kenzierocks** [comment]
I solved this a while ago by just sticking everything into a docker container. I'm not sure if the issue exists any more, so I'll close this for now.
