### ISSUE TITLE
PHP master builder is broken

### ISSUE THREAD

**Issue by kelunik** [travis-ci/travis-ci#7959]
Seems like the PHP nightly build hasn't been updated in a while (last in May), could that be a real nightly again?

Quoting from the support response:

> Looks like something changed in our "master" build task, where the "expect" script no longer works. (https://travis-ci.org/travis-ci/php-src-builder/jobs/245828709#L714)

See https://travis-ci.org/travis-ci/php-src-builder/jobs/245828709#L714.

**Comment by BanzaiMan** [comment]
The `master` branch is broken at the moment https://travis-ci.org/travis-ci/php-src-builder/jobs/247141204#L2702 (which looks like an issue with xdebug).

I have ideas, but I can't work on a fix until this issue is resolved.

**Comment by kelunik** [comment]
@BanzaiMan Just disable `xdebug` for now, as [it's not ready yet](https://twitter.com/derickr/status/879749272136298497)? 7.1-nightlies also shipped without it in the beginning.

**Comment by BanzaiMan** [comment]
xdebug is now disabled on the fly for `master` builds.

This is sufficient for a successful build. https://travis-ci.org/travis-ci/php-src-builder/builds/248434311

Earlier build failures hinted that there was a change in PEAR installation prompts, but this does not appear to be the case any more. I did not investigate this too deep.

Closing.

**Comment by kelunik** [comment]
@BanzaiMan Yes, probably that one: https://externals.io/thread/973#email-15670

Thanks!
