### ISSUE TITLE
Request: Emacs with image support

### ISSUE THREAD

**Issue by tkf** [travis-ci/travis-ci#796]
I think Emacs installed in Travis CI does not support image files.  `image-types` is not defined in Emacs in Travis CI.  If you have shell access to the workers, please try

```
% emacs -batch -Q --eval "(print image-types)"
```

I think it will return

```
Symbol's value as variable is void: image-types
```

In my local Emacs, it returns

```
(svg imagemagick png gif tiff jpeg xpm postscript xbm pbm)
```

I installed the server version of Ubuntu 12.04, install Emacs in it and try the same command.  It turned out this Emacs supports image files.  So I wonder why Travis CI does not support it.

I need Emacs with image support to test my project.  Please consider installing Emacs with image file support.

**Comment by BanzaiMan** [comment]
If there is a PPA that has an emacs package with this support, you can try that. Otherwise, I am afraid we cannot support for this.
