### ISSUE TITLE
Not enough memory for the Eclipse Tycho Maven build using the container-based infrastructure : enable swap ?

### ISSUE THREAD

**Issue by nicolas-albert** [travis-ci/travis-ci#7963]
Hi,

I try to build a custom *Eclipse* with the *maven* plugin *tycho.* It works fine locally or with the legacy build, but not with the *container-based* build ( *dist: trusty, sudo: false* ).

The *mvn clean install* stop with a *137 error code*, that means there is not enough *virtual memory* on the host.

I know 4 Go is a good amount of memory but it could be nice to have, through options:
-  a swap space, just in case of memory limit during the build
-  or an extra memory quota

You can see build result here (and the previous, invoked by gradle) : https://travis-ci.org/nicolas-albert/convertigo-eclipse/builds/246175535

Here my successful build using the legacy build (+ docker) : https://travis-ci.org/convertigo/convertigo-eclipse/builds/246139375

**Comment by BanzaiMan** [comment]
Container-based builds are running on a shared host with relatively limited amount of resources. If your builds demand more, please use GCE with `sudo: required`.

**Comment by nicolas-albert** [comment]
That what I do now.

I open this ticket as a suggestion to improve the futur of travis-ci and the BETA image of the container-based.
The build environment have some disk space, so it could be nice to convert a part of this as swap : 
```
# dd if=/dev/zero of=swapfile bs=1M count=1024
# mkswap swapfile
# swapon swapfile
```

**Comment by BanzaiMan** [comment]
I am doubtful that such a maneuver would be a good idea in a container running on a large EC2 instance.

**Comment by BanzaiMan** [comment]
Recent builds on GCE are passing.
