### ISSUE TITLE
Vulnerability: travis printing raw output

### ISSUE THREAD

**Issue by graemerocher** [travis-ci/travis-ci#7966]
Travis is printing the raw output from our bash scripts starting with the character `+`. See

https://travis-ci.org/grails/grails-core/builds/246247960#L194

This has the impact of leaking keys that should be secure.

Why is Travis outputting each line of the bash script? This is the script: 

https://github.com/grails/grails-core/blob/master/travis-build.sh

It is setup to be invoked like:

```
install: /bin/true
script:
  - ./travis-build.sh
```

**Comment by edmorley** [comment]
The second line of your build script is `set -x`:
https://github.com/grails/grails-core/blob/7a5bb56f7e4e959bcee74d46dda15f597f1d5954/travis-build.sh#L2

...which makes Bash output every command to the console prior to being run:
http://tldp.org/LDP/abs/html/options.html

**Comment by graemerocher** [comment]
Wow so obvious. Someone must have added that to debug the script and I didn't notice. My apologies
