### ISSUE TITLE
Text coloring in logs no longer works for "Build history" runs on master (still works for PRs)

### ISSUE THREAD

**Issue by rsimha** [travis-ci/travis-ci#7967]
This appears to have broken over the past couple of days, and might have to do with the recent Trusty image changes.

Logs from PR run (with colored text): https://travis-ci.org/ampproject/amphtml/jobs/245941759
Logs from when the same PR was merged to `master` (no colored text): https://travis-ci.org/ampproject/amphtml/jobs/245989731

This is making it very hard to analyze / debug failures from the logs. Is there any env var that needs to be set to enable colored text for "Build history" runs? (AMP tracking bug [here](https://github.com/ampproject/amphtml/issues/10117).)

**Comment by rsimha-amp** [comment]
FYI, we're using [gulp-util.colors](https://github.com/gulpjs/gulp-util#colors) to print colored text. It works for PR runs on Travis, but not in Build history runs after merging to master.

**Comment by loganfsmyth** [comment]
We're also seeing what sounds like the same issue on https://github.com/babel/babel.

On our default 7.0 branch: https://travis-ci.org/babel/babel/jobs/247293962
```
node -e "console.log('Node has TTY:', process.stdout.isTTY);"
Node has TTY: undefined
```

On a PR: https://travis-ci.org/babel/babel/jobs/247294781

```
node -e "console.log('Node has TTY:', process.stdout.isTTY);"
Node has TTY: undefined
```

**Comment by brixen** [comment]
The Rubinius build [is also failing specs](https://travis-ci.org/rubinius/rubinius/builds/247233924) because STDOUT is not a TTY (this has been an issue at various times on the OS X image in the past).

**Comment by BanzaiMan** [comment]
Hmm. Is there a simpler (or more reliable) means of reproduction? In this build, all stacks report that STDOUT is a TTY. https://travis-ci.org/BanzaiMan/travis_production_test/builds/248368624

**Comment by rsimha-amp** [comment]
@BanzaiMan, we're using the trusty `sudo: required` image for our tests. The only difference I noticed in the config for our build ([no color](https://travis-ci.org/ampproject/amphtml/jobs/245989731/config)) and your build ([with color](https://travis-ci.org/BanzaiMan/travis_production_test/jobs/248368630/config)) was that you've set the env var `STACK=GCE`. Maybe you could try the test without it and see if it makes a difference?

**Comment by BanzaiMan** [comment]
@rsimha-amp `STACK=GCE` is a noop. It is there to visually differentiate the jobs in the build page. https://travis-ci.org/BanzaiMan/travis_production_test/builds/248368624

**Comment by rsimha-amp** [comment]
@BanzaiMan, in that case, I'm not sure what's up. Were you able to look at the [config from our build](https://travis-ci.org/ampproject/amphtml/jobs/245989731/config) and see if anything in there could be causing `stdout` to no longer be a TTY?

**Comment by BanzaiMan** [comment]
We think this is an issue related to our recent efforts to hide secrets in all our logs. The availability of TTY depends on whether or not the filter is active (if there are secrets). I have since restarted https://travis-ci.org/BanzaiMan/travis_production_test/builds/248368624 and was able to reproduce it: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/248368625#L166

We are looking at this further.

Thank you for your reports.

**Comment by faceyspacey** [comment]
having the same issue.

**Comment by rsimha-amp** [comment]
This appears to be fixed now.

**Comment by weitjong** [comment]
We still have this issue on all of our build logs, except those from PR.

**Comment by rsimha-amp** [comment]
In that case, reopening.

**Comment by BanzaiMan** [comment]
@weitjong Where do you see this issue?

**Comment by weitjong** [comment]
This was how the log 2 months ago.
https://travis-ci.org/weitjong/Urho3D/jobs/234231914

And this is now. 
https://travis-ci.org/weitjong/Urho3D/jobs/255270042

**Comment by BanzaiMan** [comment]
Looks like the descendent processes are still losing TTY.

**Comment by rsimha-amp** [comment]
@BanzaiMan This issue is once again affecting our Travis logs, making them difficult to read. I'm seeing color text output in PR builds, but not in push builds.

**PR build (color):** https://travis-ci.org/ampproject/amphtml/jobs/330000955
**Push build (no color):** https://travis-ci.org/ampproject/amphtml/jobs/330018621

**Comment by j1mie** [comment]
Also experiencing this, with TTY only working for PRs. This causes `process.stdout` functions to fail.

**Comment by ralphtheninja** [comment]
Why is there a difference in colored output depending on PR or push? Any workaround?

**Comment by rsimha** [comment]
@BanzaiMan said earlier that it might have had something to do with hiding secrets in logs. Not sure if that's still the case, but logging is broken right now.

**Comment by brian-mann** [comment]
This is definitely due to travis stripping the logs to `stdout` and `stderr` of secret environment variables.

When doing this they are likely piping the child processes from the parent process that executes them. That's why the child processes `isTTY` is `false`.

Here's a screenshot of it in action... **notice line 80**

![screen shot 2018-05-19 at 9 14 43 pm](https://user-images.githubusercontent.com/1268976/40274637-b1761f4c-5ba9-11e8-9048-0122d35740ea.png)

**Comment by garstka** [comment]
You can use `unbuffer` from expect-dev as a workaround for this.

**Comment by alvations** [comment]
Awesome! Thank you @maxbennedich!

**Comment by mischnic** [comment]
>  If that's not the case, please respond before the issue is closed

**Comment by cardil** [comment]
Any advancements on this issue?!

There is walk around with expect-dev, as always with TTY, but it was waorking before without any additional hacks.

PS. It seams that there are color in `after_success` part even if there are no color in main part of the build, here: https://travis-ci.com/wavesoftware/plugs/jobs/169003793#L4332

**Comment by danepowell** [comment]
See the same thing on our project (BLT).

As an example, here's a PR build with color: https://travis-ci.org/acquia/blt/jobs/506404519

And the same build from a source branch without color: https://travis-ci.org/acquia/blt/jobs/506405276

Note that we define encrypted variables, which is consistent with other folks' experience and explanations for the failure.

**Comment by nicolo-ribaudo** [comment]
Could this issue be reopened? :pray:

It's still a bug: https://github.com/babel/babel/pull/10336#issuecomment-521269688

**Comment by eedwards-sk** [comment]
Please re-open. This is an awful use experience and adding additional packages across multiple platforms and changing the entry point to use a new binary just to try and get color output back is a very poor workaround.

**Comment by fingolfin** [comment]
Please re-open

**Comment by antonjuulnaber** [comment]
I am also having this issue
https://travis-ci.org/antonjuulnaber/timewarp/jobs/597899033
