### ISSUE TITLE
Docs: Google Chrome Headless should be backgrounded.

### ISSUE THREAD

**Issue by ryan-roemer** [travis-ci/travis-ci#7968]
❤️  that headless chrome has landed!

The current docs spaketh thusly: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode

```yml
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
```

This actually hangs the CI build, which then times out. Backgrounding the task worked for me in: https://github.com/FormidableLabs/victory-docs/pull/365

So, if the tire-kicking checks our on your end, maybe update the example to:

```yml
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
```

(No idea if backgrounding is needed for mac builds).

**Comment by BanzaiMan** [comment]
Hello. Do you mind opening a documentation PR for the page? There is a button for just such a purpose on the upper right corner of the page.
