### ISSUE TITLE
travis build error in user login form alter

### ISSUE THREAD

**Issue by kumana4** [travis-ci/travis-ci#7970]
Hi all,

I altered the user login form in theme and as well as in module. it is working fine in local environment but when I raised the pr request the travis build is failing. Below is error displayed in travis. 

 Failed scenarios:
features/content_creation.feature:11
1 scenario (1 failed)
6 steps (1 failed, 5 skipped)
0m1.24s (51.52Mb)

Thanks!

**Comment by BanzaiMan** [comment]
Is this an application issue, or something Travis CI needs to fix?

Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
I'm closing this for now, but if you think there is something we should fix, please include further details.
