### ISSUE TITLE
All new jobs rejected

### ISSUE THREAD

**Issue by benselme** [travis-ci/travis-ci#7974]
Travis-ci will not run tests for this PR, or any new PR in this repository:
https://github.com/python-babel/babel/pull/505

The requests tab on travis-ci.org shows "Build created successfully", but hovering over the cross that indicates that no job was run, it says "job rejected".

Using the CLI, `travis requests` returns this:
    
    PR #505 received (HEAD commit not updated)
      8a6b440 - Introduce PyInstaller support. Fixes #500
      received at: 2017-06-24 04:29:10

On the PR page, the travis-ci status says "Waiting for status to be reported".

Rebuilding and re-running master works.

**Comment by BanzaiMan** [comment]
Someone appears to have set the maximum number of concurrent builds for this repository to 0, effectively disabling Travis CI. An admin should raise the limit. I _think_ the builds should start without further intervention, but if they do not, try closing and reopening the affected PRs.

**Comment by benselme** [comment]
Thank you, I'm going to try and raise this with the repository admins.

**Comment by etanol** [comment]
Either I'm not finding the proper setting, or there's something else going on.  Here's part of the Travis settings for python-babel:

![travis-settings](https://user-images.githubusercontent.com/85804/27516983-3936229e-59c4-11e7-85b8-72ad9df46931.png)

And here are a couple of *bumped* pull requests, to trigger Travis builds:

![travis-requests](https://user-images.githubusercontent.com/85804/27516991-5d65c69c-59c4-11e7-8cfd-eecec3110187.png)

They are still failing.

**Comment by BanzaiMan** [comment]
That is strange, indeed. Could you try disabling the "concurrent jobs"?

**Comment by benselme** [comment]
I tried that yesterday, then closed and reopened a PR. It still didn't work. Then I put the 5 limit back, closed, reopened, didn't work. I also cleared the caches.

**Comment by BanzaiMan** [comment]
I've set the max to 5 on the data directly. (Bad practice; don't do this at home!) Could you try again to see if that fixes the issue?

**Comment by BanzaiMan** [comment]
Ah. I see the problem now. This PR's data are somehow causing the uncaught exception. We'll take a look. (You see that other PR builds are being scheduled.)

**Comment by benselme** [comment]
Any news about this issue ? We still cannot get any new PR built on travis. Thanks !

**Comment by benselme** [comment]
@BanzaiMan Still periodically trying builds, and still failing with same error

**Comment by BanzaiMan** [comment]
Sorry for the delay, everyone. We have identified the issue and are working on a fix. We plan to test and deploy it early next week.

Thank you for your patience.

**Comment by timofonic** [comment]
@BanzaiMan Did it got fixed? Thanks a lot!

**Comment by BanzaiMan** [comment]
Sorry for the delay. The fix I had in mind turned out to be ineffective, and we are looking into it more details.

**Comment by BanzaiMan** [comment]
Actually, it is fixed. https://travis-ci.org/python-babel/babel/builds

**Comment by virtualram** [comment]
none of this is helpfull at all

**Comment by lgritz** [comment]
I seem to have a similar problem on a different repo now. Can somebody involved say *what* was wrong and how it was fixed? Thanks, that would help me a lot.

**Comment by pramodk** [comment]
Same issue here. Recently PR's are not being building on travis : https://travis-ci.org/BlueBrain/nmodl

![image](https://user-images.githubusercontent.com/666852/76057461-e96ae600-5f79-11ea-9f96-fa0c72ae2d60.png)

@BanzaiMan : any suggestion?

**Comment by BanzaiMan** [comment]
Check your repo's "requests" page: https://travis-ci.org/OWNER/REPO/requests (or .com, as the case might be). It often tells you why. "Could not parse…" means that your configuration was invalid YAML. You can also use https://config.travis-ci.com/explore to test the configs.
