### ISSUE TITLE
Delete cache after branch is merged

### ISSUE THREAD

**Issue by chrisdembia** [travis-ci/travis-ci#7975]
In order to avoid causing Travis-CI to store excessive caches for our project, is it possible for Travis-CI to automatically delete caches for branches that have been merged into the master branch?

**Comment by BanzaiMan** [comment]
Thanks for the concern, but I don't think that is really necessary.

The caches are stored in S3 or Google Cloud Storage, depending on the infrastructure; the storing them is free, and we pay only for transfers (and that is also free if the transfer happens within the respective network).

Furthermore, the caches are deleted automatically after some time (45 days or thereabouts).

**Comment by chrisdembia** [comment]
Oh okay, sounds good. Thanks.
