### ISSUE TITLE
Problem to run test written in Lua

### ISSUE THREAD

**Issue by EvandroLG** [travis-ci/travis-ci#7976]
I just tried to integrate a project written in Lua with Travis, but it's not working.
In `script` I put the test command to execute, but it's not being found.

The error message:
<code>
lua: cannot open ./test.lua: No such file or directory
</code>

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

The `lua` command is looking for `./test.lua`. Does it exist?

**Comment by EvandroLG** [comment]
@BanzaiMan yes, the file exists there.
- https://travis-ci.org/EvandroLG/str/jobs/246850261
- https://github.com/EvandroLG/simple_test

**Comment by BanzaiMan** [comment]
You are changing directories to `$TRAVIS_BUILD_DI`, which is undefined, so at the point where your build executes `lua ./test.lua`, you are in `$HOME`, which most likely do not have this file.

**Comment by BanzaiMan** [comment]
You may want to consider using `pushd $LUAROCKS_BASE`/`popd` to move around, or `cd $LUAROCKS_BASE`/`cd -` to move *back* to where you were before the last `cd`.

**Comment by EvandroLG** [comment]
You're right.
The variable is `$TRAVIS_BUILD_DIR`. 
Thanks ;)
