### ISSUE TITLE
Android emulator doesn't fully start since June 18, 2017

### ISSUE THREAD

**Issue by yvolk** [travis-ci/travis-ci#7981]
After I successfully changed my .travis.yml on May 29 (see history https://github.com/andstatus/andstatus/commits/master/.travis.yml ) using a solution from https://github.com/travis-ci/travis-ci/issues/6122#issuecomment-293202184 I could run tests using "matrix" of two emulators" API-23 and API-25 (see the Build history https://travis-ci.org/andstatus/andstatus/builds ). starting from this build no.196: https://travis-ci.org/andstatus/andstatus/builds/237050927
Then, starting from build no.206 https://travis-ci.org/andstatus/andstatus/builds/244231655 I began to notice fails, which looked like problems with an emulator, and not with my code. 
In build no.207 emulator worked again, but since that time it looks like the problem _gradually_ (!) became worse and worse and looks like in all subsequent builds, my tests on an Android emulator didn't even start.
At first I thought that only emulator API-23 stopped working and removed it, but now even the only remaining API-25 emulator doesn't start:

travis_wait 30 android-wait-for-emulator

fails with:
Still running (30 of 30): android-wait-for-emulator
Timeout (30 minutes) reached. Terminating "android-wait-for-emulator"
See e.g. yesterday's https://travis-ci.org/andstatus/andstatus/builds/247249222

My observation shows that some resources (emulator memory ?!) were barely enough and at some point emulator began to fail...
This is not specific to my application, because it doesn't even start installing on the emulator.

Please fix!

**Comment by yvolk** [comment]
Update: Today I updated my .travis.yml to Ubuntu Trusty 14.04 image (with Android SDK 25.2.3 pre-installed)  as (I think) was suggested in this StackOverflow answer: https://stackoverflow.com/a/45177269/297710
But emulator still doesn't start even after 30 minutes of waiting (at least "android-wait-for-emulator" doesn't detect its start)"
Today's errored build: https://travis-ci.org/andstatus/andstatus/builds/255522348

**Comment by spyhunter99** [comment]
I'm having similiar issues with osmdroid, starting this past week, sometime between aug 27 and sept 1. I can't only get API8 and 10 emulators to fire up, all other times timeout with the `android-wait-for-emulator` script

**Comment by luncliff** [comment]
Suffering with same issue. Was there any progress?  
My log is here: https://travis-ci.org/luncliff/Muffin/builds/308761379

**Comment by yvolk** [comment]
Yesterday and today I did a lot of attempts to revive the Travis build, but unfortunately I couldn't: Android emulator doesn't start whatever configuration I set.
I tried different emulator APIs and different ABIs...
I ended practically where I started: getting the message: "Timeout (30 minutes) reached. Terminating "android-wait-for-emulator""
The latest today's build: https://travis-ci.org/andstatus/andstatus/jobs/322491314

**Comment by yvolk** [comment]
Thanks to @AllanWang in was able to start emulator with API 24 and to run tests on it. See https://travis-ci.org/andstatus/andstatus/builds/331424073
Unfortunately, this works with currently unsupported "android" tool only and doesn't work using "avdmanager".
It looks like some magic (and incompatibility with avdmanager) occur in Travis image, which currently contains Android 25 tools...

**Comment by shridharkalagi** [comment]
seeing same issue with android 26 as well. I assume on android 22 works currently. Can someone confirm please?

**Comment by yvolk** [comment]
@shridharkalagi  My builds using API 24 emulator still work, see https://travis-ci.org/andstatus/andstatus/builds
Travis config is here: https://github.com/andstatus/andstatus/blob/master/.travis.yml

**Comment by mikehardy** [comment]
If anyone else wants a hint, I have emulators API 16-22, and 24 working successfully. 15, 23 and 25 are problematic for me. I can't locate arm emulators for 26+

https://travis-ci.com/mikehardy/Anki-Android/builds/83362924
https://github.com/mikehardy/Anki-Android/blob/26f25427a1507ee88d55fd584070b3d8f39d01b5/.travis.yml

**Comment by mmcc007** [comment]
I'm getting similar results as @mikehardy. I did a bench test of a bunch of emulators, on both linux and osx. You can find the results [here](https://travis-ci.org/mmcc007/test_emulators).

Just starting up is not a guarantee that they will run in a test. The emulator I use is `system-images;android-22;default;armeabi-v7a` and it has worked like a champ so far. 

@mikehardy I notice u are using some parameters to avdmanager and emulator that are not familiar. Can you suggest how I might use them in my bench test?

**Comment by mikehardy** [comment]
Everything I learned is from the docs. Either avdmanager/sdkmanager/emulator or the android testing docs.
