### ISSUE TITLE
Env var cannot be set via back ticks if the command contains a space

### ISSUE THREAD

**Issue by damianobarbati** [travis-ci/travis-ci#7983]
I tried the following without success:
```
env:
    - $HOSTNAME=`jq -r .host.hostname package.json`
```
```
env:
    - $HOSTNAME=$(jq -r .host.hostname package.json)
```

My goal was to use this variables later:
```
script: rsync -avr --progress --delete-after $TRAVIS_BUILD_DIR/ user@$HOSTNAME:/tmp/build
```

**Comment by BanzaiMan** [comment]
What happens now?

**Comment by damianobarbati** [comment]
```
Setting environment variables from .travis.yml
$ export HOSTNAME=`jq
/home/travis/.travis/job_stages: eval: line 969: unexpected EOF while looking for matching ``'
/home/travis/.travis/job_stages: eval: line 970: syntax error: unexpected end of file
Updating nvm
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by damianobarbati** [comment]
Like this? https://pastebin.com/c6WQySp0

**Comment by BanzaiMan** [comment]
The first form

```yaml
env:
    - HOSTNAME=`jq -r .host.hostname package.json` # note there shouldn't be any `$`
```
appears to be a bug; the value may be getting split, or terminated at the first space, somehow.

The second form

```yaml
env:
    - HOSTNAME=`jq -r .host.hostname package.json` # note there shouldn't be any `$`
```
should work. See https://travis-ci.org/BanzaiMan/travis_production_test/builds/247424622#L164

**Comment by BanzaiMan** [comment]
The more pertinent line is https://travis-ci.org/BanzaiMan/travis_production_test/builds/247424622#L151, where a space within `$()` does not cause a problem.

**Comment by damianobarbati** [comment]
OK confirming this works: 
```
env:
    - HOSTNAME=$(jq -r .development.host.hostname package.json)
```

Backtick syntax was much cleaner but who cares 👍🏻

**Comment by damianobarbati** [comment]
No way to have this working @BanzaiMan ?
```
env:
    - HOSTNAME=$(jq -r .development.host.hostname package.json)
addons:
    ssh_known_hosts:
        - $(dev.$HOSTNAME)
        - $(stg.$HOSTNAME)
        - $(www.$HOSTNAME)
```
Error:
```
getaddrinfo $(dev.$HOSTNAME): Name or service not known
getaddrinfo $(stg.$HOSTNAME): Name or service not known
getaddrinfo $(www.$HOSTNAME): Name or service not known
```
I'd rather not hardcode anything in my travis.yml for reusability...

**Comment by damianobarbati** [comment]
@BanzaiMan  is the following possible now?
```
env:
    - HOSTNAME=$(jq -r .development.host.hostname package.json)
addons:
    ssh_known_hosts:
        - $(echo $HOSTNAME)
```

**Comment by BanzaiMan** [comment]
`exports` happens _after_ the `hosts` addon is triggered, so the hosts values cannot depend on environment variables.

**Comment by damianobarbati** [comment]
doh! so is it mandatory to hardcode them? do you know any way to work this around?
