### ISSUE TITLE
Build fails when trying to install Google Chrome on Ubuntu Trusty

### ISSUE THREAD

**Issue by kunagpal** [travis-ci/travis-ci#7988]
https://travis-ci.org/postmanlabs/postman-sandbox/jobs/247886065

Appears to be related to #7987

**Comment by Lin-Buo-Ren** [comment]
It does seems to be a duplicate of #7987 :-)

**Comment by BanzaiMan** [comment]
Closing as a duplicate. Let us know if it continues to be a problem.
