### ISSUE TITLE
Please add PHP 7.2 alpha images

### ISSUE THREAD

**Issue by nijel** [travis-ci/travis-ci#7989]
Can you please build PHP 7.2.0alpha2 so that it can be used for testing?

The definitions are already [there](https://github.com/php-build/php-build/tree/master/share/php-build/definitions), so it's probably not really much needed to make them work on Travis CI.

Thanks!

**Comment by nijel** [comment]
Currently it fails with:

```
$ phpenv global 7.2.0alpha2 2>/dev/null
7.2.0alpha2 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-7.2.0alpha2.tar.bz2
$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
$ phpenv global 7.2.0alpha2
rbenv: version `7.2.0alpha2' not installed
```

**Comment by alcohol** [comment]
Specifically, https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-7.2.0alpha2.tar.bz2 is a 404.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/php-src-builder/builds/249018407 will generate the archives `7.2.0alpha2` and the alias `7.2.0a2`.

**Comment by jbboehr** [comment]
@BanzaiMan The alias 7.2 won't be available?

**Comment by Majkl578** [comment]
dHi, 7.2.0alpha3 is coming out tomorrow (tag is already made). It will include probably the most awaited feature - the `object` typehint.
Could we please get it built as well & have it aliased to 7.2 so we can start depending on it on CI & slowly start migration to PHP 7.2 (most notably Doctrine - see https://github.com/doctrine/doctrine2/issues/6529)? Thanks. 👍

**Comment by Majkl578** [comment]
Alpha 3 is out: http://news.php.net/php.internals/99794

**Comment by Majkl578** [comment]
Alpha 3 is being handled in https://github.com/php-build/php-build/pull/447.

**Comment by paragonie-scott** [comment]
The next release of 7.2 should have libsodium support via the new sodium extension. Would it be possible to enable this in Travis builds automatically?

**Comment by sebastianbergmann** [comment]
PHP 7.2 has now been branched (`PHP-7.2 branch`) and `master` is now PHP 7.3. This means we need support for `7.2` and `7.2snapshot`. And `master` should be PHP 7.3.

**Comment by Majkl578** [comment]
7.2.0beta1 was just released: http://news.php.net/php.internals/99969. It's up to Travis now to allow open-source world to migrate. 👍

**Comment by rxu** [comment]
```nightly``` is aliased to PHP 7.3.0-dev currently, but ```php: 7.2``` is still unavailable 😉

**Comment by BanzaiMan** [comment]
`7.2.0beta1` is having problems with the `redis` extension. https://travis-ci.org/travis-ci/php-src-builder/builds/256365911 The same holds for `*snapshot`s.

**Comment by BanzaiMan** [comment]
It might need to be installed from source.

**Comment by BanzaiMan** [comment]
Alias `7.2` now points to `7.2.0beta1`, but the version string does seem to reflect it. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/256418945#L232

The build result is shown here: https://travis-ci.org/travis-ci/php-src-builder/builds/256396298

**Comment by Majkl578** [comment]
Thanks @BanzaiMan! Already tested and it looks fine: https://travis-ci.org/doctrine/common/builds/251602714

**Comment by BanzaiMan** [comment]
I think this can be closed now.
