### ISSUE TITLE
Build is failing - Failed to fetch https://debian.neo4j.org/repo/stable/Packages.gz  Hash Sum mismatch

### ISSUE THREAD

**Issue by vmalloc** [travis-ci/travis-ci#7990]
See https://travis-ci.org/getslash/backslash/builds/247876122 - this seems to happen before I even get to run my `.travis.yml` code...

**Comment by ticosax** [comment]
seems to be a duplicate of #7987

**Comment by Jenselme** [comment]
I encountered this problem too. It is solved now. @vmalloc do you confirm?

**Comment by vmalloc** [comment]
@Jenselme running the build again now to check, will update

**Comment by vmalloc** [comment]
@Jenselme yup - seems to be working now. Closing this. Thanks!

**Comment by nikolas** [comment]
I'm getting repeated neo4j.org hash sum mismatches on this build: https://travis-ci.org/ccnmtl/blackrock/builds/248530281

```
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch https://debian.neo4j.org/repo/stable/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by markandrus** [comment]
Yes, I am seeing these errors in the past hour now as well.
