### ISSUE TITLE
DOCS pyrus support looks to have been dropped from trusty

### ISSUE THREAD

**Issue by dhensby** [travis-ci/travis-ci#7993]
It's not mentioned in the docs (https://docs.travis-ci.com/user/trusty-ci-environment/#PHP) but `pyrus` isn't working for us on trusty builds.

```
$ if [[ $PHPCS_TEST ]]; then pyrus install pear/PHP_CodeSniffer; fi
No command 'pyrus' found, did you mean:
 Command 'cyrus' from package 'cyrus-common' (universe)
 Command 'gyrus' from package 'gyrus' (universe)
pyrus: command not found
```

see build: https://travis-ci.org/silverstripe/silverstripe-framework/jobs/248302290#L743

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/5256. Mentions of `pyrus` should be dropped from https://docs.travis-ci.com/user/languages/php.

**Comment by dhensby** [comment]
@BanzaiMan pyrus is still mentioned in the docs

**Comment by MikeiLL** [comment]
I'm wondering what a good way to install php pear packages currently is.

**Comment by dhensby** [comment]
Most packages should be installable with composer

**Comment by dhensby** [comment]
@BanzaiMan pyrus is still mentioned in the docs
