### ISSUE TITLE
Is headless Chrome missing from new stable Trusty?

### ISSUE THREAD

**Issue by benjaoming** [travis-ci/travis-ci#8001]
We used to play:

```
addons:
    chrome: stable
```

Which still works on Trusty beta, however now [we're getting](https://travis-ci.org/learningequality/kolibri/jobs/248495163#L1050):

``` 
29 06 2017 19:21:48.899:ERROR [launcher]: No binary for ChromeHeadless browser on your platform.

  Please, set "CHROME_BIN" env variable.
```

Here are the current docs mentioning headless: https://docs.travis-ci.com/user/chrome

**Comment by BanzaiMan** [comment]
You are using Precise https://travis-ci.org/learningequality/kolibri/jobs/248495163#L158, so the addon is not effective, as documented in https://docs.travis-ci.com/user/chrome. Please use `dist: trusty` at the top level of your `.travis.yml`.

**Comment by benjaoming** [comment]
Oh my, sorry about this and thanks for clarifying - I was under a false impression that Trusty was now the default distribution if not specifying any.

**Comment by BanzaiMan** [comment]
No worries!
