### ISSUE TITLE
Private repo made public, encrypted API key stopped working, cannot encrypt new API key

### ISSUE THREAD

**Issue by monkey0506** [travis-ci/travis-ci#8003]
I originally create a repo at monkey0506/ags-module-stack as private to do testing. After testing, I reset the private repo and made it public. I got an error in the build that authentication failed. I figured I needed to regenerate the API key when moving from travis-ci.com to travis-ci.org, so I tried running `travis setup releases` again, and gives the error:

`repository not known to https://api.travis-ci.com/: monkey0506/ags-module-stack`

I have attempted to entirely delete the repository from Github and delete the `.git` folder in my working directory, but after recreating the remote repository (at the same URL), `travis setup releases`, `travis init`, and `travis encrypt` all return the same error.

How can I redirect the command line to check `api.travis-ci.org` instead of `api.travis-ci.com`?

**Comment by monkey0506** [comment]
I found the `--api-endpoint` switch (and `--org`), but in general is there a way to reset this?

**Comment by BanzaiMan** [comment]
API endpoints are stored in `~/.travis/config`.

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/travis-pro#How-can-I-make-a-private-repository-public%3F should address issues concerning this situation. Let us know if we missed something.

In the mean time, I'm closing this.
