### ISSUE TITLE
Workaround for today's PyPI brownout?

### ISSUE THREAD

**Issue by jacquerie** [travis-ci/travis-ci#8004]
Hi, the `deploy` step of our package is failing with this error: https://travis-ci.org/inspirehep/inspire-schemas/jobs/248674752#L644.

If I understood the error message correctly, we can work around it today by adding `server: https://upload.pypi.org/legacy/`. On the other hand, I believe that this means that your deploy script will start failing starting July 3rd, something you might want to fix : )

**Comment by jacquerie** [comment]
[This commit](https://github.com/inspirehep/inspire-dojson/commit/523abbbf073fcd8f7f9c74c13b84cd46ad7487e9) did in fact fix today's uploading for us.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/dpl/issues/655 for the ongoing discussion.

**Comment by BanzaiMan** [comment]
This should be fixed by dpl 1.8.39.
