### ISSUE TITLE
Crystal Nightly job failing, crystal package not installed

### ISSUE THREAD

**Issue by miketheman** [travis-ci/travis-ci#8005]
https://travis-ci.org/miketheman/statsd.cr/jobs/248736453#L556

> GPG error: https://dist.crystal-lang.org/apt crystal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4EBAC6667697DD2
W: The repository 'https://dist.crystal-lang.org/apt crystal InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.

/cc @asterite, @jhass, @waj and @will

**Comment by miketheman** [comment]
Related https://github.com/crystal-lang/crystal/issues/4648

**Comment by straight-shoota** [comment]
This issue should be fixed according to [crystal-lang/crystal#4648 (comment)](https://github.com/crystal-lang/crystal/issues/4648#issuecomment-312908094).
But crystal-lang/crystal#4647 still prohibits successful builds for Crystal on Travis-CI

**Comment by greenbigfrog** [comment]
@asterite, @jhass, @waj and @will still failing
