### ISSUE TITLE
NVM install failing on macOS agents

### ISSUE THREAD

**Issue by MarshallOfSound** [travis-ci/travis-ci#8008]
Basically all my builds with node 7 and macOS are failing at the install step before any of my config is run (so I have 0 control over it).

https://travis-ci.org/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/builds/245355672 

Support said there is a bug here and to raise an issue on this repo 👍

**Comment by BanzaiMan** [comment]
Seems to be a problem with only newer Mac images. Not clear yet how we can fix it.

**Comment by BanzaiMan** [comment]
Seems like an nvm bug.

```sh-session
Traviss-Mac-8:travis_staging_test travis$ nvm --version
0.33.2
Traviss-Mac-8:travis_staging_test travis$ npm config delete prefix
Traviss-Mac-8:travis_staging_test travis$ nvm install 8
v8.1.3 is already installed.
nvm is not compatible with the npm config "prefix" option: currently set to "/Users/travis/.nvm/versions/node/v8.1.3"
Run `npm config delete prefix` or `nvm use --delete-prefix v8.1.3` to unset it.
```

**Comment by BanzaiMan** [comment]
This `unset`ting is not working.

```sh-session
Traviss-Mac-8:travis_staging_test travis$ nvm use --delete-prefix v8.1.3
Now using node v8.1.3 (npm v5.0.3)
Traviss-Mac-8:travis_staging_test travis$ nvm install 8
v8.1.3 is already installed.
nvm is not compatible with the npm config "prefix" option: currently set to "/Users/travis/.nvm/versions/node/v8.1.3"
Run `npm config delete prefix` or `nvm use --delete-prefix v8.1.3` to unset it.
```

**Comment by BanzaiMan** [comment]
I have reported the nvm issue as https://github.com/creationix/nvm/issues/1573.

**Comment by MarshallOfSound** [comment]
> Seems to be a problem with only newer Mac images

@BanzaiMan Do you know which mac images aren't affected by this issue, trying to find one that works 👍

**Comment by BanzaiMan** [comment]
`nvm install` now works on the Mac. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/338655302#L105

I'm closing now. If you still see problems, do let us know.
