### ISSUE TITLE
Descriptor File documentation about relativity of "includePath" unclear

### ISSUE THREAD

**Issue by solvingJ** [travis-ci/travis-ci#8009]
https://docs.travis-ci.com/user/deployment/bintray/

One example shows an "includePath" as follows: 

> {"includePattern": "build/docs/(.*)", "uploadPattern": "docs/$1"}

It does not indicate where this path is relative to, and I cannot figure it out.  If i hardcode it to the temporary path, it works (/home/travis/build/repoOwner/repoName/(*.rpm).  However, this is obviously dis-advantageous.  

Note: The .rpm builds in the root of my project directory. 

Thus, the simplest case I tried was with the following patterns, and produces the following errors:
```
"includePattern": "(*.rpm)"
```

```
[Bintray Upload] Warning: Path: (*.rpm) does not exist.
```

Can someone please clarify (here and on the docs), where the descriptor file paths are relative to?

**Comment by BanzaiMan** [comment]
I think the pattern is meant to be a regular expression, but you are passing a glob. Try

    "includePattern": "(.*\.rpm)"

**Comment by solvingJ** [comment]
Worked, many thanks!
