### ISSUE TITLE
Support Node.js on ChakraCore

### ISSUE THREAD

**Issue by xzyfer** [travis-ci/travis-ci#8017]
Add support for [node-chakracore](https://github.com/nodejs/node-chakracore). NVM can be used to install nightlys from https://nodejs.org/download/chakracore-nightly/ as outlined in https://github.com/creationix/nvm/issues/1067. However the stable builds are not yet hosted on nodejs.org, in which case there is not yet a reliable solution see https://github.com/jasongin/nvs/blob/master/doc/CI.md#github-api-tokens.

This will help adoption, and stress testing of node-chakracore. 

Related 
https://github.com/appveyor/ci/issues/1148
https://github.com/nodejs/node-chakracore/issues/136
https://github.com/sass/node-sass/issues/1776
https://github.com/sass/node-sass/pull/1777

**Comment by BanzaiMan** [comment]
We should wait until `nvm` supports it fully. As @ljharb said https://github.com/creationix/nvm/issues/1067#issuecomment-308524339, whatever we do now is likely to be incompatible with any possible future support by `nvm`.

**Comment by xzyfer** [comment]
I opened this issue in part because the tone of that, and [previous][1] discussions, suggest little interesting in supporting other Node builds. Where as newer alternatives like [nvs][2] consider alternate builds as first class as well as being x-platform.

I have requested clarification from @ljharb on how to proceed with adding support. He previously expressed [concerns around low usage][4] when jxcore support was requested. However without support from services like Travis CI and AppVeyor adoption among package maintainers is being hampered.

By adding support for ChakraCore you're enabling adoption, and experimentation. It doesn't seem fair to leave that choice in the hands of a package maintainer. Sure users can work around this limitation but it's a non-trivial obstacle, and a sign of low-confidence.

It's also worth noting that other popular version manages have [refused added support for ChakraCore][3] on similar grounds.

[1]: https://github.com/creationix/nvm/issues/729
[2]: https://github.com/jasongin/nvs
[3]: https://github.com/marcelklehr/nodist/issues/114
[4]: https://github.com/creationix/nvm/issues/729#issuecomment-93246941

**Comment by xzyfer** [comment]
Further clarification from nvm suggests a feature is in the works to add a [supported workaround].

[1]: https://github.com/creationix/nvm/issues/1067#issuecomment-312764529

**Comment by BanzaiMan** [comment]
I don’t think this is something we will work on to fix, but rather rely on nvm to provide.

**Comment by xzyfer** [comment]
This feature is coming to nvm - https://github.com/creationix/nvm/pull/1828

**Comment by BanzaiMan** [comment]
Closing as an upstream issue.
