### ISSUE TITLE
401 - Bad credentials (Octokit::Unauthorized)

### ISSUE THREAD

**Issue by ngtuna** [travis-ci/travis-ci#8018]
So I use travis-ci to upload assets to github release. I run `$ travis setup releases` to take the generated encrypted api_key. However the travis build says "Bad credentials"

```
/home/travis/.rvm/gems/ruby-2.2.6/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
```

Somebody said runing `$ travis encrypt <token>` with a proper scope token (public_repo) could help, however it doens't work too. 

Any idea what's going wrong in my case ?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by ngtuna** [comment]
@BanzaiMan yes https://travis-ci.org/ngtuna/kubeless/jobs/249503418

**Comment by BanzaiMan** [comment]
Looks like the encrypted value is incorrect for this repository. Try a few more explicit flags when you encrypt it:

```
travis encrypt -r ngtuna/kubeless --org
```

This should prompt you for the value to encrypt. Type your API key, return, then ctrl-D to terminate.

**Comment by ngtuna** [comment]
@BanzaiMan The error is still there. I am not sure if travis-ci is having problem with github authentication today. It worked for me last week. Is there any clue for that ?

**Comment by BanzaiMan** [comment]
Looks like https://travis-ci.org/ngtuna/kubeless/jobs/249700557 created https://github.com/ngtuna/kubeless/releases/tag/0.0.18.

**Comment by ngtuna** [comment]
Confirm `travis encrypt -r ngtuna/kubeless --org` worked as expected. Thanks for your support @BanzaiMan. Close this

**Comment by namangupta01** [comment]
Hello everyone! Getting the same error in https://github.com/publiclab/plots2/pull/2669. Does anyone have idea how to resolve this?

**Comment by dalen** [comment]
@namangupta01  I got this recently for a repo on travis-ci.com after the move to GitHub Apps. Solved it by adding the `--pro` flag to `travis setup releases`.

**Comment by berry120** [comment]
@dalen Ah, the `--pro` flag was a lifesaver, exactly what I needed - thanks!

**Comment by ssbarnea** [comment]
@dalen Thanks for the hint on `--pro`, I was hit by the same issue.

**Comment by reach2jeyan** [comment]
Somehow suddenly today, I am getting this error in the master branch build. When I try to run `travis setup releases --pro` , I get the error `unknown service release`

**Comment by jesskie** [comment]
Its OK sir the truth will set you free

jess
