### ISSUE TITLE
Crystal build fails, missing signature

### ISSUE THREAD

**Issue by waghanza** [travis-ci/travis-ci#8020]
Hi,

I have a build (https://travis-ci.org/waghanza/cab/jobs/249345022) failing.

@asterite @jhass @waj @will : The signature is missing for gpg keys on https://dist.crystal-lang.org/

Regards,

**Comment by waghanza** [comment]
@BanzaiMan I can not add crystal label

**Comment by BanzaiMan** [comment]
Duplicate of #8005.
