### ISSUE TITLE
Unable to login via Web UI (travis-ci.org)

### ISSUE THREAD

**Issue by gisjedi** [travis-ci/travis-ci#8022]
I've been happily using Travis CI for many years with no trouble, but today is not my day. I was initially trying to run a debug build of a public project and that is what caused me to run into this issue. I attempted to perform a `travis token -org` at the command line and then curl the API using the token - I received an access denied response. As a result I decided to try to refresh my login via GitHub.

Here was my process:
1. Attempted to sign in via the link on the TravisCI home page: https://api.travis-ci.org/auth/handshake?redirect_uri=https://travis-ci.org/
2. Redirect flow dropped me to page with message: `Sorry, we experienced an error.`
3. I then decided to try Chrome private browsing to ensure no stored credentials were messing up the process. I followed same approach as in step 1-2, but this now included logging in to GitHub as prompted by TravisCI. Same error result as in 2.
4. I then completely abandoned Chrome and tried Safari. Exact same error.

It is probably worth noting, logging in to travis-ci.com works for me, just not travis-ci.org.

This was attempted on Chrome 59.0.3071.115 (64-bit) and Safari 10.1.1 (12603.2.4) with MacOS Sierra 10.12.5. I've also attempted this on Windows 10 Pro (1607) with Chrome 59.0.3071.115 (64-bit), Internet Explorer 11.1358.14393.0 and Edge 38.14393.1066.0. _Both IE and Edge worked_, no other combination did.

**Comment by iriberri** [comment]
Thank you for such a thorough report! 💛 

This was a temporary issue in our end and everything should be resolved now - could you please confirm that login in https://travis-ci.org works now, @gisjedi?

**Comment by gisjedi** [comment]
I'm back in. Thank you for the quick response.
