### ISSUE TITLE
Prune inactive branches

### ISSUE THREAD

**Issue by vinniefalco** [travis-ci/travis-ci#8024]
In the Branches view on my repository control panel I see branches that have been deleted a year ago or maybe more. Please provide a method to remove these.

**Comment by BanzaiMan** [comment]
Duplicate of #2614.

**Comment by xypron2** [comment]
#2614 has been marked locked and I do not want to open another duplicate. But seeing no progress on the issue in 5 years is a pity.

**Comment by Senui** [comment]
Any news on this? Loading my Branches page takes a very long time...

**Comment by vinniefalco** [comment]
Going on 6 years now?

**Comment by vinniefalco** [comment]
Maybe time to invent a new sniglet:

"Travisty" (n) - When a defect remains unaddressed for 5 or more years. Portmanteau of "Travis" and "travesty."
