### ISSUE TITLE
language: csharp /usr/bin/env doesn't see fsharpi

### ISSUE THREAD

**Issue by jbtule** [travis-ci/travis-ci#8028]
cc/  @joshua-anderson, @akoeplinger and @nterry

When i try to use `/usr/bin/env` to run `fsharpi` I receive the error.

> /usr/bin/env: fsharpi --define:mono_posix --exec: No such file or directory

https://travis-ci.org/ekonbenefits/dynamitey/builds/249131539

It runs just fine when replaced with `/usr/bin/fsharpi`, which shows that fsharpi is installed.

https://travis-ci.org/ekonbenefits/dynamitey/builds/246595183

So you can see the difference between those two travis-ci runs here:
https://github.com/ekonbenefits/dynamitey/pull/16/commits/8195723d73b32a5d84e2dc181f010de958f9e4bd

**Comment by BanzaiMan** [comment]
Actually, this is not a C# issue.

In the shebang line, `env` takes what is passed to it there as a single argument and executes it. See https://askubuntu.com/a/246957

**Comment by jbtule** [comment]
Thanks, I didn't realize, that's frustrating. [And it doesn't look like it's ever going to change](http://lists.gnu.org/archive/html/coreutils/2017-05/msg00014.html).

 I'll leave my workaround here for reference. 

_FSharp linux shebang (that will work on mac too)_
```
#!/bin/sh
#if bin_sh
  # Doing this because arguments can't be used with /usr/bin/env on linux, just mac
  exec fsharpi --define:mono_posix --exec $0 $*
#endif
```
