### ISSUE TITLE
Build passes with bad YAML

### ISSUE THREAD

**Issue by nnadeau** [travis-ci/travis-ci#8032]
## Expected Behavior
- Build fails with bad YAML

## Actual Behavior
- Build passes

## Context
- Experimenting with the build matrix feature
- Setting Python versions as a version array (e.g., `- 2.7`, `- 3.6`, ...) instead of an explicit Python array (e.g., `- python: 2.7`, `- python: 3.6`, ...)

## Steps to Reproduce the Problem
- Example job: https://travis-ci.org/nnadeau/pybotics/jobs/249973664
- Example bad YAML commit: https://github.com/nnadeau/pybotics/commit/bbc71378c5b05b77e99f30f2ff0a292665c4d107

**Comment by nnadeau** [comment]
The given YAML also fails the [linter](http://lint.travis-ci.org/)

**Comment by BanzaiMan** [comment]
There is a misunderstanding on how `matrix.include` works with respect to matrix dimension keys such as `python`. Each entry in the `matrix.include` array defines exactly one job, and that value is used to compile a build script.

You gave an array with 10 elements (https://github.com/nnadeau/pybotics/blob/bbc71378c5b05b77e99f30f2ff0a292665c4d107/.travis.yml#L10-L19) to `python`, which is then used in the build script. https://travis-ci.org/nnadeau/pybotics/jobs/249973664#L8

The linter points this out.

```
in matrix.include.python section: does not support multiple values, dropping 3.2
in matrix.include.python section: does not support multiple values, dropping 3.3
in matrix.include.python section: does not support multiple values, dropping 3.4
in matrix.include.python section: does not support multiple values, dropping 3.5
in matrix.include.python section: does not support multiple values, dropping 3.5-dev
in matrix.include.python section: does not support multiple values, dropping 3.6
in matrix.include.python section: does not support multiple values, dropping 3.6-dev
in matrix.include.python section: does not support multiple values, dropping 3.7-dev
in matrix.include.python section: does not support multiple values, dropping nightly
```
