### ISSUE TITLE
export command not working via eval

### ISSUE THREAD

**Issue by bobbydeveaux** [travis-ci/travis-ci#8033]
I'm executing this command (FOG_PASSWORD is set in the settings, same as FOG_CREDENTIAL).

```eval "$(echo $FOG_PASSWORD |  FOG_CREDENTIAL=[secure] vcloud-login)"```

The output is something like "export FOG_VCLOUD_TOKEN=adsuf98adf98a98sdf98sdf33" - but it doesn't ```eval``` it, and doesn't set the FOG_VCLOUD_TOKEN env var.

Is there something I'm missing?

Here is the build:
https://travis-ci.org/UKCloud/vcloud-core/jobs/249953774

.travis.yml
```---
language: ruby
sudo: false
rvm:
  - 2.2.2
  - 2.3.0
  - 2.4.0
script:
  - bundle install
  - gem install vcloud-core
  - ./scripts/setfog.sh
  - bundle exec rake integration
notifications:
  email: false
```

setfog.sh:
```
eval "$(echo $FOG_PASSWORD |  FOG_CREDENTIAL=test_credential vcloud-login)"
```

Many thanks

**Comment by BanzaiMan** [comment]
Does this `eval` statement work on your machine?

**Comment by edmorley** [comment]
Hi! Running the script like that will cause it to be run in a subshell, which is unable to affect the parent environment. Source the script instead, ie:
```yaml
  - . ./scripts/setfog.sh
```

See:
https://ss64.com/bash/source.html

**Comment by bobbydeveaux** [comment]
The eval line works on my Mac yes, but obvs don't have the sub shell issue. Will try the source suggestion. Thanks :)

**Comment by BanzaiMan** [comment]
Are you saying that the token shown here was invalid? https://travis-ci.org/UKCloud/vcloud-core/jobs/249953774#L450

**Comment by bobbydeveaux** [comment]
No, I'm saying the token shouldn't have been shown at all. I've managed to get this to work now by bypassing the sub shell and it works as expected without showing the token :)

Thanks peeps
