### ISSUE TITLE
Build step after `script` but before `deploy`

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#8034]
Wonder why there's no a dedicated build step after executing `script`, but before `deploy` which would execute whether the `script` is successful (`after_success`) or failed (`after_failure`)? `before_cache` is there, but should one use it not for cache management?

**Comment by BanzaiMan** [comment]
Use `before_deploy`. https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle

**Comment by Deilan** [comment]
@BanzaiMan Would it execute if deploy should not be done based on it's conditions?

**Comment by BanzaiMan** [comment]
Not at the moment. See #8010. What are you trying to execute in this phase?

**Comment by Deilan** [comment]
@BanzaiMan Because of an issue I need to stop `xvfb` after a build script with tests for Chrome has been executed: When `xvfb`'s running `electron-packager` is being freezed while trying to package an app.
