### ISSUE TITLE
Issue with running build UI

### ISSUE THREAD

**Issue by jake32321** [travis-ci/travis-ci#8036]
There's an issue with overlapping parts of the running builds portion with the cancel build element overlapping the build time element.
<br/>
<img width="124" alt="screen shot 2017-07-04 at 3 48 17 pm" src="https://user-images.githubusercontent.com/7380109/27842504-3727d8ae-60d0-11e7-831b-bbcfb4a06f63.png">

**Comment by BanzaiMan** [comment]
Is this a duplicate of #8035?

**Comment by jake32321** [comment]
yep that's the case.  I will go ahead and close this then.
