### ISSUE TITLE
after_failure script not run if script errors

### ISSUE THREAD

**Issue by lwaldron** [travis-ci/travis-ci#8038]
@craigcitro @hadley @jimhester I have the following in my .travis.yml file for an R package at https://github.com/waldronlab/curatedMetagenomicDataCuration. The .push_gh_pages.sh script runs after a successful package check, but not after a package check where the unit tests produce any error. I've left the package intentionally in an erroring state because I want `./push_gh_pages.sh` to run even if the unit tests fail (actually, *especially* if the unit tests fail, because the vignette is designed to help identify the reason for failure).

```
after_script:
  - ./.push_gh_pages.sh
after_failure:
  - ./.push_gh_pages.sh
```

**Comment by BanzaiMan** [comment]
Looks like the build script is bailing out early, without a chance for `travis-build` to clean up. https://github.com/travis-ci/travis-build/blob/97c7efd0cd1102bbcaaf896536f2ff236687c9df/lib/travis/build/script/r.rb#L239

**Comment by lwaldron** [comment]
I'm now working around this issue by using a `before_script` script to build and push to gh-pages before the travis-CI R script is run. FYI [this previous version](https://github.com/waldronlab/curatedMetagenomicDataCuration/tree/114e245308fa872a35b8eb96908f8ff61e041c8a) shows how I was originally trying to run a script after success or failure.

**Comment by chris-ratcliffe** [comment]
@BanzaiMan I am seeing this issue as well.  In my script section I include a call to `set -e` to force processing to stop when any particular command fails, however, that seems to cause the "bail out" to happen, in which case, neither after_script nor after_failure run.  If I remove the set -e, both of them run when there is a failure, however, I then have all of my unnecessary steps after the failure continue to run.  Is there now way to cause the script section to stop on failure, and make use of the after_* sections?

**Comment by ericchenshine** [comment]
Is there any update on this issue?

**Comment by BanzaiMan** [comment]
Sorry, but I have no updates.

**Comment by jimhester** [comment]
@BanzaiMan Is there a different way to signal failure that would still execute the `after_failure` block? I can change the script if so.

**Comment by BanzaiMan** [comment]
At the moment there is not, I'm afraid.

**Comment by bvberkum** [comment]
I was a bit confounded about an issue with the same behaviour. Until I read the comment by @chris-ratcliffe.

Forgot about some scripts sourced into the build shell, which `set -e` at the beginning. Problems went away by reversing disable exit on error again `set +e`.

https://travis-ci.org/bvberkum/script-mpe/builds/354613175
