### ISSUE TITLE
Commit with tags containing `[skip ci]` in message runs a build

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#8041]
Commit with tags containing `[skip ci]` in message runs a build. As per [documentation](https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build) if there's `[skip ci]` somewhere in a commit's message, a build should not be run.

Script used to commit & push tags, which should not result in a build run:
```bash
#!/bin/bash

GIT_USER_EMAIL=$1
GIT_USER_NAME=$2
GIT_TAG=$3
GIT_COMMIT_MESSAGE=$4

git config user.email $GIT_USER_EMAIL
git config user.name $GIT_USER_NAME
git tag -a $GIT_TAG -m "$GIT_COMMIT_MESSAGE [skip ci]"
git push -q origin --tags
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by Deilan** [comment]
@BanzaiMan Sure. 
Here's the repo: [Deilan/travis-broken-example](https://github.com/Deilan/travis-broken-example)

[Build History](https://travis-ci.org/Deilan/travis-broken-example/builds)

Take a look at the last two builds ([#9](https://travis-ci.org/Deilan/travis-broken-example/builds/250509011) and [#10](https://travis-ci.org/Deilan/travis-broken-example/builds/250509379)). The last but one build [#9](https://travis-ci.org/Deilan/travis-broken-example/builds/250509011) created a tag, a commit with message `Generated by Travis CI [skip ci]` and pushed it. As a result a [tag](https://github.com/Deilan/travis-broken-example/releases/tag/v1.0.0) was created with the same message, which in turn invoked a build [#10](https://travis-ci.org/Deilan/travis-broken-example/builds/250509379).

**Comment by Deilan** [comment]
@BanzaiMan Also note that the build logs are truncated. Why is that?

**Comment by BanzaiMan** [comment]
Sorry, but I don't see any commit in the [commit history](https://github.com/Deilan/travis-broken-example/commits/44389525d2573d611394282549909476468faedd) up to https://github.com/Deilan/travis-broken-example/commit/44389525d2573d611394282549909476468faedd which contains `[skip ci]` at all.

**Comment by BanzaiMan** [comment]
If you are trying to set the commit message with https://github.com/Deilan/travis-broken-example/blob/44389525d2573d611394282549909476468faedd/set-tag.sh#L14, you are just annotating a tag, not adding a commit message.

**Comment by BanzaiMan** [comment]
We only look at commit message, not tag annotations.

**Comment by Deilan** [comment]
@BanzaiMan Is there a way to ignore a tag created in that way?

**Comment by BanzaiMan** [comment]
What do you mean by "that way"?

Do you want to skip a build if it was triggered by a tag?

**Comment by Deilan** [comment]
@BanzaiMan Yes. I create a tag as a part of deployment done by Travis and I don't need a redundant build in that case.

If I am doing wrong then how should I do it correctly? I need to deploy to GitHub releases for every commit at `master` branch and annotate it with a tag.

**Comment by BanzaiMan** [comment]
@Deilan Thanks for the clarification. Could you open a separate issue, stating your use case as such? I don't think this (skipping tags, but running builds on pushes) is possible.

**Comment by Deilan** [comment]
@BanzaiMan Done: #8051.
