### ISSUE TITLE
"wrong_credentials" when attempting debug restart of job via API

### ISSUE THREAD

**Issue by gisjedi** [travis-ci/travis-ci#8042]
I'm attempting to debug a build that has been failing for some time with a truncated log output. Ultimately I just want to see what the full log message is, but I hoped I'd be able to see this full output by running the build via debug. 

I followed the instructions given under [Restarting a job in debug mode](https://docs.travis-ci.com/user/running-build-in-debug-mode/#Restarting-a-job-in-debug-mode-via-API) for my public repo. Using the TravisCI CLI (`travis token`), I was able to retrieve my token and attempted to restart the job in debug mode. When making the actual curl request I keep receiving a JSON response as seen below:

```
{
  "@type": "error",
  "error_type": "wrong_credentials",
  "error_message": "access denied"
}
```

I've attempted a number of CLI commands after my login (`travis whatsup` and `travis env list`) to ensure I was actually authenticated and it seemed so. The curl request made to attempt a restart of the job can be found below:

```
curl -s -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Travis-API-Version: 3" \
  -H "Authorization: token ********************" \
  -d "{\"quiet\": true}" \
  https://api.travis-ci.org/job/249679001/debug
```

The exact build I was attempting to restart can be found here: https://travis-ci.org/ngageoint/scale/builds/249679000

Any details that could be given for why the build log output is truncated would also be helpful.

**Comment by BanzaiMan** [comment]
The repository ngageoint/scale does not have the feature turned on, so it doesn't work for you. This is explained in the document:

> This feature is available for private repositories and those public repositories for which the feature is enabled. To have the feature enabled for a public repository, please email us at support@travis-ci.com indicating which ones. The push access to the repository is also required.

If you would like to turn the feature on, please contact support.

**Comment by gisjedi** [comment]
Somehow I completely overlooked this note. :man_facepalming:  Thanks for the quick response!

**Comment by carlosperate** [comment]
Does this still need to be enabled via email for Public repositories?
I didn't see that note in the current version of the docs: https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by slacAWallace** [comment]
Any word on this? I am sending an email regardless.

**Comment by josejulio** [comment]
> Any word on this? I am sending an email regardless.

I sent the email and they helped me to enable this.

**Comment by bkgoksel** [comment]
It is really frustrating that the email requirement is not documented anymore. Would appreciate if either the documentation or the API endpoint is fixed.

**Comment by paulz** [comment]
Yes, it is frustrating that the API docs: https://docs.travis-ci.com/user/running-build-in-debug-mode/
do not mention that you need to send email to support@travis-ci.com to enable debugging for public repositories.

**Comment by bkgoksel** [comment]
It seems like at least now it is added to the API docs at [here.](https://docs.travis-ci.com/user/running-build-in-debug-mode/#enabling-debug-mode)
But perhaps it could be made more prominent as many people (including maybe me back then) seem to be missing it.

**Comment by jesskie** [comment]
Hope its true

jess
