### ISSUE TITLE
Duplicate testing on recent Python version

### ISSUE THREAD

**Issue by ale5000-git** [travis-ci/travis-ci#8046]
I use this: `coverage run setup.py test`.

Under [Python 3.3](https://travis-ci.org/ale5000-git/pycompatlayer/jobs/250677352) it is tested one time.
Instead under [Python 3.6](https://travis-ci.org/ale5000-git/pycompatlayer/jobs/250677353) (and maybe other recent versions) it is tested TWO times.

Can it be fixed?

**Comment by BanzaiMan** [comment]
This seems like a tooling issue to me. We do not do anything differently. Do you not see this on your machine locally?

You could try reproducing this issue with https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally as well.

**Comment by ale5000-git** [comment]
Sorry the problem doesn't hyave anything to do with Travis.
It is probably a bug in unittest since loading the tests differently fix the problem.

**Comment by ale5000-git** [comment]
Ref: https://bugs.python.org/issue30874
