### ISSUE TITLE
Travis CI windows support for creating windows binary

### ISSUE THREAD

**Issue by LakshmiMekala** [travis-ci/travis-ci#8047]
Hi,

I am trying to build windows binary from OS:windows on travis CI and i was not able to create binary. Kindly let us know how can i create windows binary from Travis CI

**Comment by BanzaiMan** [comment]
What Windows binary are you trying to create? Unless such a process exists on either Linux or the Mac for the tools you are using, we do not support it at this time.

**Comment by LakshmiMekala** [comment]
Am trying to create binary for go lang project

**Comment by BanzaiMan** [comment]
In that case I'm closing this as a duplicate of #2207.
