### ISSUE TITLE
Postgres max connections issue

### ISSUE THREAD

**Issue by SimplyCorey** [travis-ci/travis-ci#8049]
I am receiving the following errors when running my tests on Travis CI.

```SQLSTATE[08006] [7] FATAL:  remaining connection slots are reserved for non-replication superuser connections ```

I searched through the documentation and I am unable to find a way to increase the `max_connections` setting for PostgreSQL within Travis CI.  My build passes locally without any issue.

Here is my addons within my .travis.yml file

```
addons:
  postgresql: "9.6"
```

Is there anything I can add to this to increase the max_connections?  

Thanks for the help.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by SimplyCorey** [comment]
Unfortunately, the link isn't public as it is on travisci.com.     Is there a way to start psql with a different max connections set?

Here are more details:

```
Starting PostgreSQL v9.6
1.37s$ sudo service postgresql stop
 * Stopping PostgreSQL 9.2 database server        * Stopping PostgreSQL 9.3 database server        * Stopping PostgreSQL 9.4 database server        * Stopping PostgreSQL 9.5 database server        * Stopping PostgreSQL 9.6 database server       
2.33s$ sudo service postgresql start 9.6
 * Starting PostgreSQL 9.6 database server       
0.05s$ sudo -u postgres createuser -s -p 5432 travis &>/dev/null
0.36s$ sudo -u postgres createdb -O travis -p 5432 travis &>/dev/null
0.05s$ sudo -u postgres createuser -s -p 5433 travis &>/dev/null
0.04s$ sudo -u postgres createdb -O travis -p 5433 travis &>/dev/null
```

**Comment by BanzaiMan** [comment]
With `sudo`, you can edit your PostgreSQL config file and restart the service. You can ask where the config file is with `SHOW config_file`.

```
$ sudo -u postgres psql -c "SHOW config_file;"
               config_file
------------------------------------------
 /etc/postgresql/9.1/main/postgresql.conf
(1 row)
```

**Comment by SimplyCorey** [comment]
How would I do this using the .travis.yml file in the before_script section?  I don't believe I can log onto the Travis boxes to modify this and it needs to be within this file?

**Comment by BanzaiMan** [comment]
You'd need to come up with a means of modifying the config file noninteractively (say, with `sed`). You can use the debug button to test your commands. https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by SimplyCorey** [comment]
You lean something everyday, I was unaware of the debug option.  Thank you!

**Comment by BanzaiMan** [comment]
Super. Let us know (here, or at support@travis-ci.com) if you need additional help.

**Comment by SimplyCorey** [comment]
I fixed my issue with this in the before_script:

```
  - sudo sed -i 's/max_connections = 255/max_connections = 1000/g' /etc/postgresql/9.6/main/postgresql.conf
  - sudo service postgresql restart```

**Comment by bhaveshAn** [comment]
@SimplyCorey @BanzaiMan 
What if I have to change shared_buffers as well. What would be the command.
