### ISSUE TITLE
New Trusty images reduced log output

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#8050]
In new Trusty images the build log is for some reason much shorter than it was before, many information is not present in the log.

This is the new build: https://travis-ci.org/igagis/svgren/jobs/250799940
And this is the old one: https://travis-ci.org/igagis/svgren/jobs/244411040

I'm using sbuild to build for specific debian release and with new Trusty image I dont' see a lot of log output which was there before. Was there any changes in the image which could affect logging?

**Comment by BanzaiMan** [comment]
Most of the difference comes from this command:

```
if [ "$BUILD_NAME" == "debian" ]; then prorab-deb-prepare.sh && sg sbuild -c "sbuild -A -d testing-amd64-sbuild --run-lintian --debbuildopts '-us -uc'"; fi
```

Looks like you are installing a lot of Ubuntu/Debian packages. Since the new image has more up to date software, I am guessing that your script `prorab-deb-prepare.sh` would be installing fewer packages, reducing the log output.

**Comment by igagis** [comment]
That's right, most of the difference is from this command, but the most interesting logs are missing from there and those are not about installing packages.
The `prorab-deb-prepare.sh` does not install packages, it just substitutes some variables to debian scripts before building.
The main thing which `sbuild` does is that it runs `dpkg-buildpackage` and the most of logging from there is missing, here are the only logs I can see from it right now:

````
dh clean
   dh_testdir
   dh_auto_clean
make[1]: Entering directory `/home/travis/build/igagis/svgren'
make[1]: Leaving directory `/home/travis/build/igagis/svgren'
   dh_clean
dpkg-source: info: using source format `3.0 (native)'
dpkg-source: info: building libsvgren in libsvgren_0.4.17.tar.gz
dpkg-source: info: building libsvgren in libsvgren_0.4.17.dsc
````

while before there was a much more output from `sbuild`.

The command to run `sbuild` is as follows:
`sg sbuild -c "sbuild -A -d testing-amd64-sbuild --run-lintian --debbuildopts '-us -uc'"`
i.e. it runs the `sbuild` command as a different group (`sbuild` group) using the `sg` command, can that be somehow affected that there is no log output when it is run like that?

**Comment by php-coder** [comment]
I'm having the same issues time to time and I don't use Trusty yet. Here is the last failed build: https://travis-ci.org/php-coder/mystamps/jobs/256247215

**Comment by php-coder** [comment]
@BanzaiMan Could you give me a link to the issue? I tried to search and found only this issue.

**Comment by igagis** [comment]
@php-coder perhaps there is no another issue, so why not create a new one?

**Comment by php-coder** [comment]
@BanzaiMan @igagis Ok, I've created a separate issue for that: https://github.com/travis-ci/travis-ci/issues/8189

**Comment by igagis** [comment]
New observation:

If build succeeds then a lot of log output is omitted, like in this build:
https://travis-ci.org/igagis/svgdom/jobs/261590076

But, if build fails, because of compilation error for example, then the log output is fully present and visible, as in this build of the same github repo:
https://travis-ci.org/igagis/svgdom/jobs/261586686

**Comment by igagis** [comment]
I have found that if I supply a `-n` option to `sbuild` then it directs the build log to `stdout`. For some reason in previous image it was by default, but in trusy image it is not.
Anyway, I added the `-n` option now and it works. Closing the bug.
