### ISSUE TITLE
Add latest PHP release candidates

### ISSUE THREAD

**Issue by ottlinger** [travis-ci/travis-ci#8054]
The newly released PHP versions:
* 7.1.7
* 7.0.21
should be made available via Travis.

Thanks :-)

**Comment by BanzaiMan** [comment]
For the record, here's the general flow at this time:

1. The PHP team makes releases
1. https://github.com/php-build/php-build as them to the definitions https://github.com/php-build/php-build/tree/master/share/php-build/definitions
1. https://travis-ci.org/travis-ci/travis-nightly-builder/ runs the daily cron job to check for new releases (not just PHP, but also for Perl, Erlang, etc.), and triggers a build on https://travis-ci.org/travis-ci/php-src-builder if necessary.

All of this should be automated, and should happen roughly within a couple of days once php-build adds the definition.

If you want new PHP releases, please send PR to php-build.

I think this should be documented, but not quite sure where it should be.

**Comment by ottlinger** [comment]
@BanzaiMan thanks for the explanation, let's see if my PR https://github.com/php-build/php-build/pull/447 is helpful :-)

**Comment by ottlinger** [comment]
@BanzaiMan my PR was accepted and hopefully the Travis builds will grep the new definitions this night ....

**Comment by ottlinger** [comment]
Builds are green again, thanks for letting me know how to handle these kinds of issues in the future :-)
