### ISSUE TITLE
C#: cannot execute binary file

### ISSUE THREAD

**Issue by Seikilos** [travis-ci/travis-ci#8058]
I am compiling C# code on a travis instance.
However I noticed something strange: A binary I produce has no x flag set. In my travis script I `chmod +x`  this file but then I still cannot execute the binary. I always get

`/home/travis/.travis/job_stages: line 54: MyProgram.exe: cannot execute binary file`

The nunit test runner works well on this machine so it does not look like I cannot execute c# binaries at entirely. Am I missing something fundamentally there?

**Comment by Seikilos** [comment]
cc @joshua-anderson @akoeplinger @nterry

**Comment by Joshua-Anderson** [comment]
Try `mono MyProgram.exe` to execute the program with the mono runtime
