### ISSUE TITLE
otp_release 20 not found

### ISSUE THREAD

**Issue by jfcalvo** [travis-ci/travis-ci#8059]
Looks like `otp_release` version 20 is not available. I need to set `otp_release` to version `18.2.1` (as available in the documentation) to make it works.

It would be nice to have these last versions and some way to see what versions of Elixir and OTP are available in the platform.

**Comment by BanzaiMan** [comment]
`20.0` should be. See #7947.

**Comment by jfcalvo** [comment]
Thanks @BanzaiMan. I was using `20.0.0`. Now working perfectly with `20.0`.
