### ISSUE TITLE
heroku deploy leaking email address

### ISSUE THREAD

**Issue by simonsmiley** [travis-ci/travis-ci#8061]
When deploying using heroku, in the prepare step the email address used in heroku is leaked.
Below is an example output
```
Preparing deploy
authenticated as address@example.com
checking for app herokuappname
found app herokuappname
```

While the app name is public, the address is not, and shouldn't be displayed.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
If you don't want to share that information, please close this issue and send details to support@travis-ci.com. Thanks.

**Comment by simonsmiley** [comment]
I just sent an email
