### ISSUE TITLE
Go ".0" releases are no longer available

### ISSUE THREAD

**Issue by tantalic** [travis-ci/travis-ci#8065]
It is no longer possible to target the ".0" releases of Go for builds. This is because the Go does not include .0 in it's releases but instead numbers them 1.9, 1.8, 1.7, etc. Previously, one could target these releases by using 1.9, 1.8, or 1.7 as the version. However, now these are interpreted as the latest release (same as 1.9.x) and it is impossible to use the ".0" versions.

See the following job which is tagged for 1.8, but instead runs `go version go1.8.3 linux/amd64`

It appears based this was introduced in: https://github.com/travis-ci/travis-build/pull/1094

**Comment by meatballhat** [comment]
@tantalic Thank you for the report!  This should now be fixed in production.
