### ISSUE TITLE
macOS Error : .onLoad failed in loadNamespace() for 'tcltk', details:

### ISSUE THREAD

**Issue by achubaty** [travis-ci/travis-ci#8067]
@craigcitro and @jimhester
Since the transition to R 3.4.1, I've been getting this error only on macOS builds:

```
Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/tcltk/libs/tcltk.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/tcltk/libs/tcltk.so, 10): Library not loaded: /opt/X11/lib/libfontconfig.1.dylib
  Referenced from: /usr/local/lib/libtk8.6.dylib
  Reason: Incompatib
```

(*e.g.*, see a recent failing build [here](https://travis-ci.org/PredictiveEcology/SpaDES.core/jobs/252215744))

**Comment by BanzaiMan** [comment]
My guess is that the binary file is incompatible with the OS you are running. Try a newer Xcode image, say `osx_image: xcode8.2`.

**Comment by achubaty** [comment]
@BanzaiMan perfect, that did the trick! thank you.
