### ISSUE TITLE
Travis build failing, not reproducible locally by anyone

### ISSUE THREAD

**Issue by axefrog** [travis-ci/travis-ci#8071]
https://travis-ci.org/frptools/collectable/jobs/252331327

I'm on Windows 10 and I've had two others on OS X clone the repo and try to build it as well. All three of us are able to build it successfully. Travis seems like it might be referencing old versions of certain packages or source code and I can't find any good reason why this might be happening. I can't verify what it's referencing though, because the Yarn output does not include a list of packages or package versions it has installed. There is no caching enabled for the repository, as best I can tell.

**Comment by BanzaiMan** [comment]
I was able to reproduce the issue using the steps described in https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

**Comment by BanzaiMan** [comment]
I don't know enough about Node.js ecosystem or your code base to advise, however.

**Comment by axefrog** [comment]
I just mean that all three people who've tested this have cloned the repo locally, completely fresh from Github, and just run the steps Travis is running, without any errors. Two of us have never cloned the repo before, thus mitigating any local caching possibilities. We're all able to build successfully, and the built packages have already been published to npm, and used in local testing.

Travis is the odd one out in this case. It'd be great if Travis would show the list of packages Yarn installed, like it does from the local command when running `yarn`. Is Travis using some special silent configuration to make it hide the installed dependency log?

I've never used Docker before, but will try to find some time in the near future to learn, and in the mean time will just have to put up with the phantom build failure.

**Comment by BanzaiMan** [comment]
I started out with a plain Ubuntu 14.04 image on Docker, and see the same problem.

**Comment by BanzaiMan** [comment]
Actually, `yarn` seems to fail as well in the example above.

**Comment by axefrog** [comment]
I'm having trouble getting Docker working locally. Is there any way you could completely purge the `@frptools/collectable` project from Travis completely? I tried turning the project off and then back on later, but it had no effect. I had a report that someone managed to reproduce the issue, but _only_ on a machine where they'd attempted a much earlier build where the old files would have been present. It's like there's some kind of intermediate caching issue going on in the network. There is literally no reason for Travis to be throwing this error unless, somewhere in the pipeline, it's caching an outdated version of a dependency somewhere in the network and using that one.

**Comment by axefrog** [comment]
Thought you'd like to know the issue ended up boiling down to a weird filename case sensitivity issue that was masked by the way the compilation was happening. The errors being displayed were a red herring. Thanks for the help.
