### ISSUE TITLE
MacOS xcode8.1 onwards issue with confirmation at command prompt

### ISSUE THREAD

**Issue by NileshGule** [travis-ci/travis-ci#8073]
Recently I faced issue with Xcode8.1 image. In my .travis.yml file, I have a command to uninstall homebrew
**ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"**
This was working fine with [xcode7.3](https://travis-ci.org/NileshGule/Mac-dev-playbook/jobs/251921286) and xcode8. From xcode8.1 image it is waiting for the confirmation of delete as shown in the attached image.
<img width="991" alt="screen shot 2017-07-12 at 11 08 57 am" src="https://user-images.githubusercontent.com/1298374/28101549-be37a9a6-66fb-11e7-8646-d74569e35ab0.png">

Here is an example of [xcode8.3](https://travis-ci.org/NileshGule/Mac-dev-playbook/jobs/252248774/config) 

For now I have put a workaround by pipelining the yes command and the build is passing with [xcode8.2](https://travis-ci.org/NileshGule/Mac-dev-playbook/builds/252650720)
**yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"**

Is there any better way of handling the response of the command prompt during the build execution?

**Comment by BanzaiMan** [comment]
If you look at the source code of the uninstall script, you see that there is an option to skip prompts (`-f` or `--force`).

It is not clear to me how the behavior changed between the images, but I suspect this is a change in TTY configuration. Whatever the reason, `-f` or piping `yes` (which you indicated), should work fine.

**Comment by NileshGule** [comment]
Thanks for confirmation. I will continue to us the piping of yes command.
