### ISSUE TITLE
Travis passes build even if tests fail

### ISSUE THREAD

**Issue by chashmeetsingh** [travis-ci/travis-ci#8074]
It seems that the tests added, many times don't execute but when they do and if any of them fails, Travis passes the build even after that. Any idea what needs to be added additionally to fail the build as soon as the first test fails?

Parent Issue: https://github.com/travis-ci/travis-ci/issues/8019

My script:

```
language: swift
osx_image: xcode8.3
cache: cocoapods

before_install:
- gem install cocoapods
- pod repo update

after_success:
  - chmod +x upload-ipa.sh
  - ./upload-ipa.sh

script:
  - xcodebuild test -workspace Susi.xcworkspace -scheme Susi -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' ONLY_ACTIVE_ARCH=NO | xcpretty -c
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by chashmeetsingh** [comment]
Sure, https://travis-ci.org/fossasia/susi_iOS/builds/252313452

**Comment by BanzaiMan** [comment]
In both of these builds, you are running `xcodebuild … | xcpretty`. The exit status of this command pipeline is dictated by the last command, `xcpretty`, which I believe is exiting with 0.

If you need to capture the status of `xcodebuild`, you need to use `PIPESTATUS`. See https://stackoverflow.com/a/1221870/136333.

**Comment by chashmeetsingh** [comment]
Ok, I see. Thanks!
