### ISSUE TITLE
Using openjdk8 causes javac to be java 1.9

### ISSUE THREAD

**Issue by rhtyd** [travis-ci/travis-ci#8075]
When `openjdk8` is used java version returns 1.8, however javac returns 1.9. Please see:
https://travis-ci.org/apache/cloudstack/builds/252705597

**Comment by BanzaiMan** [comment]
We set `$JAVA_HOME`, but it appears that we never use this value to set `$PATH`. If you invoke `$JAVA_HOME/bin/javac -version`, you should see the correct version reported.

**Comment by BanzaiMan** [comment]
I _think_ we should add it in `$PATH`.

**Comment by eed3si9n** [comment]
I just ran into this. Please reopen this issue.

**Comment by eed3si9n** [comment]
Some programs require `javac` on the PATH to match up with JAVA_HOME.
Please reopen this issue.
