### ISSUE TITLE
Pre-installed versions of Ruby on Trusty

### ISSUE THREAD

**Issue by rmzelle** [travis-ci/travis-ci#8077]
I'm a little confused by the pre-installed versions of Ruby in Trusty, since the documentation and actual situation don't seem to agree.

https://docs.travis-ci.com/user/build-environment-updates/2017-07-12/ says "This update applies to Ubuntu Trusty stacks on both sudo-enabled and container-based execution environments" and "bumped pre-installed Ruby versions to jruby-9.1.9.0, 2.2.7, 2.3.4, and 2.4.1 on applicable stacks". However, when I switched to Trusty at https://github.com/citation-style-language/styles/pull/2808, Ruby 2.4.1 didn't seem to be preinstalled: https://travis-ci.org/citation-style-language/styles/builds/252918000#L417 (although 2.4.0 is: https://travis-ci.org/citation-style-language/styles/builds/252918000#L398).

**Comment by meatballhat** [comment]
@rmzelle the job you've referenced is on container-based, which is a gradual rollout process.  We're currently about 40% complete, so within the next 6 hours you should see consistent behavior.

**Comment by rmzelle** [comment]
Okay, thanks!
