### ISSUE TITLE
Multiple & 3D arrays of configurations

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#8080]
I have a project whose tests include about 30 or 40 Dieharder randomness tests, each running against 6 Java PRNGs on 4 JVMs. Running the entire suite of tests in one job, even for just one JVM and just one PRNG, would take around 10 hours; thus, I need a way to launch each of the tests as a separate job per JVM per PRNG. (I'm currently working around this by using only 5% of the recommended sample size for each test.) The project also has unit tests, but most of these are not PRNG-specific, and the full set can easily run as one job per JVM.

Thus, what I need altogether is for the jobs to be a 3-dimensional array of randomness tests (using 2 different environment variables and the JVM selection as the dimensions) plus a 1-dimensional array of unit tests. Is there any way to accomplish this? Here's my current config file: https://github.com/Pr0methean/uncommons-maths/blob/master/.travis.yml

On a related note, this will create a total of between 724 and 964 jobs per push; and at my current limit of 5 concurrent jobs, the entire run will take around 48 hours. Does this still fall within travis-ci.org limits?

**Comment by BanzaiMan** [comment]
Use `env` to set environment variables, which you can then use to choose your PRNG.

```yaml
env:
  - PRNG=type1
  - PRNG=type2
script
  - run_prng_test_using $PRNG
```

Please note that we will reject build requests that create so many jobs.

**Comment by Pr0methean** [comment]
That doesn't quite answer my question: how do I create a *two*-dimensional array per JVM of environment-variable configurations? And how many jobs am I allowed per push (since I'll at least want to partition the Dieharder suite into subsets)?

**Comment by Pr0methean** [comment]
In case it helps, I don't expect to frequently push more than once per day, except during the next week or so; and I have auto-cancel enabled.

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

If you use `env` and `jdk` keys, you'll get a build matrix.

**Comment by Pr0methean** [comment]
Right, but what I need is a build *cube*.

**Comment by Pr0methean** [comment]
I suppose I could pack the PRNG selection and the test-type selection into one numeric variable, and use division and modulo to unpack it in a shell script, but this would be inelegant.

**Comment by BanzaiMan** [comment]
Well, you can't for Java builds, since you'd only get `env` and `jdk`. https://docs.travis-ci.com/user/languages/java#Build-Matrix

If you want to construct a build matrix that you desire, you'll have to come up with the list of `env` values.

**Comment by Pr0methean** [comment]
Also, how many jobs *should* I partition the testing into, given that I'll need around 240 instance-hours per push (when auto-cancel doesn't trigger) altogether no matter how it's sliced?

**Comment by BanzaiMan** [comment]
I am sorry to tell you this, but that is beyond the acceptable limits at this time.

I suggest looking at the changes in your commit to derive a reasonably small subset of tests to run.
