### ISSUE TITLE
[Error] Timeout Error; Build hangs after finishing the build, gets terminated after 10 more minutes

### ISSUE THREAD

**Issue by Richard-Cao** [travis-ci/travis-ci#8082]
https://travis-ci.org/Richard-Cao/Richard-Cao.github.io/builds/253082602

I can see this output:

```
Done. Your build exited with 0.
```

But still error:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Before is normal, like this: https://travis-ci.org/Richard-Cao/Richard-Cao.github.io/builds/252245988

How to solve this?

**Comment by CyberDem0n** [comment]
The same problem for me...
https://travis-ci.org/zalando/patroni/jobs/253147343

**Comment by justinrummel** [comment]
+1 https://travis-ci.org/justinrummel/jr.com-mm/jobs/253031229 

> Done. Your build exited with 0.
>
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
>
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
>
> The build has been terminated

**Comment by dhimmel** [comment]
Also having this issue where `build exited with 0`, but for some reason doesn't register as finished, causing termination after 10 minutes and the build appearing to have failed (although it actually passed).

See example [build with this problem here](https://travis-ci.org/greenelab/scihub-manuscript/builds/253223984).

**Comment by BanzaiMan** [comment]
Hello, everyone. Sorry for the issue.

We have identified an issue with the current strategy to filter secrets. This is a part of our ongoing effort to ensure that the secrets remain secret. Here is a blog entry to give you more context: https://blog.travis-ci.com/2017-05-08-security-advisory

Does this always happen for your affected jobs? If you restart these jobs with errors, does the error persist?

**Comment by justinrummel** [comment]
@BanzaiMan thanks for the quick reply!  I have restarted the jobs twice and it persists.

**Comment by matthewgraybosch** [comment]
This was happening to me as well today, @BanzaiMan, but I appreciate the explanation.

**Comment by BanzaiMan** [comment]
Currently the only common factor among the reported problems is the use of secrets. I've tried reproducing the issue with my own testing repository, but have not been successful yet. (Granted, my test builds are simple.)

**Comment by BanzaiMan** [comment]
OK. I think I have a small reproduction of this issue.

Take a look at https://travis-ci.org/BanzaiMan/travis_production_test/builds/253298937

This build runs the same task on all jobs (on different stacks). You can see that jobs 1 and 2 ran on GCE (with `sudo: required`, which is the default for this repository), and the jobs 3 and 4 ran on EC2 (with `sudo: false`). From this, I deduce that the issue is present only on containers (on EC2, with `sudo: false`).

The difference between this build and my previous attempts is that this build invokes a long-running child process in the build. Here, I'm invoking ```"eval `ssh-agent -s`"```, but I reckon other similar processes that gets in the background are also susceptible to this issue.

# RECAP

This issue appears to manifest when all of the following criteria are met:

1. The job runs on EC2 (with `sudo: false`, or by default on newer repositories)
1. The job contains secrets (either in `.travis.yml` via `secure: …`, or in the Settings page)
1. The job invokes a process that goes into the background

**Comment by BanzaiMan** [comment]
While we work on the fix, try the following:

If you are invoking `ssh-agent`, killing it should clean up the build script.

```
eval `ssh-agent -s`
⋮ # do stuff
ssh-agent -k
```

If you are sending another process into the background, try killing it with `kill $!`.

If you send multiple jobs in the background, you might need to remember these PIDs; e.g., 

    job1 &
    bg_pid1=$!
    job2 &
    bg_pid2=$!
    ⋮
    kill $bg_pid1 $bg_pid2

**Comment by BanzaiMan** [comment]
Of course, do let us know if you are experiencing the issue and your case does not fit the description I gave in https://github.com/travis-ci/travis-ci/issues/8082#issuecomment-315147561.

Thanks.

**Comment by justinrummel** [comment]
Added ```ssh-agent -k``` after adding my [deployment keys](https://github.com/justinrummel/jr.com-mm/blob/jr-branch/.travis.yml#L37) and it worked: https://travis-ci.org/justinrummel/jr.com-mm/jobs/253314302

**Comment by Richard-Cao** [comment]
Added `ssh-agent -k` worked for me!
Thanks!

**Comment by BanzaiMan** [comment]
@Richard-Cao Thanks for the confirmation.

I'm reopening this, though, because the issue persists at the moment, and users should not have to worry about these things. I have an idea for a fix, and will be testing it next week.

**Comment by nerrad** [comment]
Just adding our builds to the mix.  We have a build where  a php web-server and phantomjs service are started.  I thought this might be the cause of the issue based on the notes here so explicitly stopped them (where previously the build environment seemed to kill them just fine).  You can see our build here: https://travis-ci.org/eventespresso/ee-codeception/builds/253583142

I think why we're still seeing this timeout issue is because we also have mailcatcher running in the background.

**Comment by sc0ttkclark** [comment]
@nerrad sounds like it might be similar to some of our issues

**Comment by BanzaiMan** [comment]
Beefed up the description so that this may be more visible in search.

**Comment by dylanon** [comment]
Adding `ssh-agent -k` worked for me as well. Thanks for the quick workaround!

**Comment by dhimmel** [comment]
@BanzaiMan do you have a time estimate for how long a fix will take to deploy (days? weeks? months?). We're considering whether to implement the `ssh-agent -k` workaround, but will hold off if a fix is coming soon.

**Comment by BanzaiMan** [comment]
@dhimmel I cannot promise anything beyond what I'd stated earlier. The fix may not work, either. So, when in doubt, implement your workaround. My fix (if it works) should not interfere with it.

**Comment by DL6ER** [comment]
Another one for this channel. We don't use `ssh-agent`.

https://travis-ci.org/pi-hole/FTL/jobs/253248120#L601

**Comment by mjhamm75** [comment]
My build is failing and I am not using any background processes that I know of.  Here is my SO [question](https://stackoverflow.com/questions/45156059/why-does-my-travis-build-not-finish) and [here](https://travis-ci.com/hipshot/gather-api) is my build.

**Comment by BanzaiMan** [comment]
@mjhamm75 It's impossible to say with certainty, but in the SO question you say your build executes `node server.js`. Are you sure it doesn't send anything in the background?

**Comment by mjhamm75** [comment]
I am basically wiring up some endpoints and running a GraphQL server.  I don't know if either one of those qualify.  [Here](https://gist.github.com/mjhamm75/24740b9046e9ae339e33297fc611d69b) is a copy of the file.  Maybe something will pop out to you.

**Comment by mjhamm75** [comment]
I also have another app doing the same thing.  [Here](https://travis-ci.com/hipshot/gather-fe/jobs/83213673) is a link to that app.

**Comment by lstagner** [comment]
I am also running into this issue here is the [build log](https://travis-ci.org/D3DEnergetic/FIDASIM/builds/254691309)

**Comment by BanzaiMan** [comment]
@mjhamm75 I don't know enough about Node.js to advise. Sorry. If you are seeing this problem, though, the chances are that you do have some process running in the background.

@lstagner https://github.com/D3DEnergetic/FIDASIM/blob/2f7ee45fd0d7b7e73603ba2335a410bcd5f73050/deploy.sh#L29

We will be testing a potential fix US work day tomorrow (in 8 hours' time or so).

**Comment by DL6ER** [comment]
I've been able to resolve this issue by making sure every background process is killed at the end of my build job. Thanks for your mentioning in your Recap further up @BanzaiMan

**Comment by BanzaiMan** [comment]
Hi, everyone! We've deployed a fix for this issue. Do let us know if you continue to see problems.

**Comment by mjhamm75** [comment]
I am still having the same issue with the 2 apps that I deployed.

https://travis-ci.com/hipshot/gather-api/builds/50437764
https://travis-ci.com/hipshot/gather-fe/builds/50438067

Please advise what to do next

**Comment by BanzaiMan** [comment]
@mjhamm75 We have not deployed the fix to .com yet. I apologize for not making this distinction earlier.

**Comment by BanzaiMan** [comment]
@mjhamm75 Did so now. Please try restarting affected builds.

**Comment by BanzaiMan** [comment]
@mjhamm75 Actually, your issue might be different. I do not see any sign of your build terminating; i.e., there is no output

    Done. Your build exited with 0.

Your job seems to be just waiting for additional input from STDIN.

**Comment by mjhamm75** [comment]
That looks to be just the test command.  Why would it give that message
when there are still other commands to run.  I have another build that does
not have that being output.

https://travis-ci.com/hipshot/gather-fe/builds/50442624

**Comment by BanzaiMan** [comment]
@mjhamm75 Your build runs `npm run start`, and that's it. This command is not terminating, so the build sits there indefinitely. What does this command do when you run it on your machine?

**Comment by mauritsvanrees** [comment]
I had the same issue with a long running firefox. I had added a kill command a while ago to work around the build not finishing. I have now [removed](https://github.com/collective/collective.calltoaction/commit/2fd0ecd42c958d6a34f88542ed434e842a5e356b) this, and the build finishes [correctly](https://travis-ci.org/collective/collective.calltoaction/builds/254975612).

So your fix works for me, @BanzaiMan. Thank you!

**Comment by BanzaiMan** [comment]
@mauritsvanrees Sweet! Thank you for your report.

**Comment by mjhamm75** [comment]
So I have another app that is built off of the same boilerplate and it's
build is finishing as expected.

https://travis-ci.com/hipshot/sedd-dashboard-api/builds/50489197

But my other app still does not finish

https://travis-ci.com/hipshot/gather-api/builds/50437764

I am going to dig deeper and see what differences I have missed, but maybe
there is a difference on your end?

**Comment by mjhamm75** [comment]
Something else that is strange about these builds.  The environment
variables are undefined.

**Comment by BanzaiMan** [comment]
@mjhamm75 Please review your application code. [The build that finishes cleanly](https://travis-ci.com/hipshot/sedd-dashboard-api/builds/50489197) runs `npm run build`, and [the one that doesn't](https://travis-ci.com/hipshot/gather-api/builds/50437764) runs `npm run start`. I don't know much about your code base, but I am inclined to guess that they do completely different things. The latter build appears to be genuinely staying in the foreground:

```
{"name":"express-app","hostname":"testing-docker-46ff4fe0-14ab-4174-8ee4-e8642725eaec","pid":8478,"level":30,"msg":"listening on PORT undefined!","time":"2017-07-18T14:30:30.618Z","v":0}
```

"listening on PORT undefined!" seems bad news for your app, but that is most definitely not related to the problem we are discussing here.

As for environment variables… I don't see any defined in your `.travis.yml`. They don't seem defined in the settings page, so I think this is expected.

**Comment by nerrad** [comment]
Just posting to confirm that the released fix has helped all our builds successfully complete.  Thanks!

**Comment by fulldecent** [comment]
Here is a way to kill all background jobs:

    kill $(jobs -p)

> https://unix.stackexchange.com/a/43709

Maybe this should be a default last line in every Travis script that uses background jobs?

I have a 10 minute phantomjs timeout and try this now.

**Comment by oreporan** [comment]
Any updates on this issue?

I want to exit the build on PRs after a certain line, so I have this:

```
$ if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

```

**Comment by hongaar** [comment]
Still seeing this behaviour on Windows builds. No background processes running.

But just in case I tried adding this snippet without any effect:

```
kill $(ps ax | awk '{print $1}') || true
kill $(jobs -p) || true
ssh-agent -k
```

I'll try to close in on the offending part of my build script and post back the results here.

**Comment by hongaar** [comment]
To follow up with the post above, it seems that this behaviour can even be triggered with the simplest of examples:

https://github.com/hongaar/travis-test

```yml
language: node_js

node_js:
  - 'node'

matrix:
  fast_finish: true

os:
  - windows

script:
  - ./test.sh
```

👉 [Repository](https://github.com/hongaar/travis-test)
👉 [Travis build](https://travis-ci.com/hongaar/travis-test/builds/123678752)

**Comment by BanzaiMan** [comment]
@hongaar Your problem with Windows is a different problem from the original issue, which predates our Windows support.

As for your test case, I believe yarn is starting a GPG subprocess, which causes the hang (cf. https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/19)
