### ISSUE TITLE
Travis doesn't support .net4.6.2

### ISSUE THREAD

**Issue by cohen990** [travis-ci/travis-ci#8085]
https://travis-ci.org/cohen990/EasyConfig.Net.Core/builds/253273046

I've been attempting to build my solution which targets multiple frameworks. netstandard1.6 and .net4.6.2

The netstandard1.6 build through dotnet core is totally fine. I've tried using dotnetcore and xbuild to build it against framework 4.6.2 though and I'm getting this error:

`
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/travis/build/cohen990/EasyConfig.Net.Core/EasyConfig.Net.Core/EasyConfig.Net.Core.csproj]
`

I don't see any way to tell travis which frameworks I need through the yaml

Any suggestions?

@joshua-anderson @akoeplinger @nterry

**Comment by clarkd** [comment]
Is this really still an issue?

**Comment by akoeplinger** [comment]
@clarkd the .NET Core SDK tooling still doesn't officially support building .NET Framework libraries. You can use Mono/msbuild to do that though.

**Comment by fubar-coder** [comment]
We had a similar problem and used the following fix: fluentmigrator/fluentmigrator#849
