### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by grandchamp** [travis-ci/travis-ci#8089]
Hi.
I'm trying to build a .NET Core application on Travis, and after some errors on build, i can't start mysql on Docker anymore.

`ERROR: for mysql_mysql_1  Cannot start service mysql: driver failed programming external connectivity on endpoint mysql_mysql_1 (e8bd9042915d1e0050f9e852608b052fafc3090afc550800d8c1b585dad77b7a): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use`
https://travis-ci.org/grandchamp/Identity.Dapper/builds/253364877#L586

What can i do?

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by Joshua-Anderson** [comment]
Does travis possibly run it's local mysql server by default? Try a different port

**Comment by BanzaiMan** [comment]
MySQL may already be running on the image. Try stopping first.

```
sudo service mysql stop
```

**Comment by grandchamp** [comment]
@BanzaiMan thanks! It worked. Same for postgres.
