### ISSUE TITLE
Ruby 1.9.3 - dbm and gdbm missing

### ISSUE THREAD

**Issue by minad** [travis-ci/travis-ci#809]
They are part of stdlib but cannot be loaded. It worked a few days ago. Did you change the ruby version?

See https://travis-ci.org/minad/juno/jobs/3678112

**Comment by vedavrat** [comment]
I had such error of Ruby gem, concerning 
**LoadError: cannot load file 'dbm'** :
# 
```
rdictcc
<internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': 
cannot load such file -- dbm (LoadError)
	from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/bin/rdictcc:28:in `<main>'
```
#

These two commands helped me:
```
gem update
gem install dbm
```
