### ISSUE TITLE
Travis builds are not triggering after making repo public

### ISSUE THREAD

**Issue by tonyjin** [travis-ci/travis-ci#8091]
Travis builds for this project no longer seem to be triggering: https://travis-ci.org/box/box-content-preview

Previously, this was a private repo set up with travis-ci.com. I recently made the repo public and I've since disabled the repo in our travis-ci.com config and enabled it for travis-ci.org. I fiddled around with some settings after discussing in https://github.com/travis-ci/travis-ci/issues/3996, but it now appears that no builds (from PRs or merged PRs into master) are triggering builds.

**Comment by BanzaiMan** [comment]
Somehow the notification hook was disabled on GitHub. I've enabled it now. Please push a new commit and verify.

Thanks.

**Comment by tonyjin** [comment]
Thanks that worked. It seemed like the hook stopped working after I disabled the travis-ci.com job for the repo - maybe there are some weird edge cases when both travis-ci.com and travis-ci.org are set up for the same repo.
