### ISSUE TITLE
Go test coverage command not available in for some go versions

### ISSUE THREAD

**Issue by tantalic** [travis-ci/travis-ci#8095]
As mentioned by @BanzaiMan in #8066 the go test coverage command is not available in the following Go versions:

- **go1.2.1**: https://travis-ci.org/tantalic/travis-go-vet/jobs/253800359
- **go1.4.3**: https://travis-ci.org/tantalic/travis-go-vet/jobs/253800382

**Comment by BanzaiMan** [comment]
Closing this as a duplicate of #8066, which I just reopened.
