### ISSUE TITLE
travis encrypt --add does not work on windows 7

### ISSUE THREAD

**Issue by MFry** [travis-ci/travis-ci#8102]
Following the recommendation on [s3 deployment](https://docs.travis-ci.com/user/deployment/s3/) I used:

`travis encrypt --add deploy.secret_access_key`

`$  Reading from stdin, press Ctrl+D when done`

Pressing `ctrl`+`D` with or without hitting enter does not do anything and the prompt is painfully vague about what it needs.

I think it has to do with `--add` as I can do a 
`travis encrypt SOMEVAR="secretvalue"`

```
travis -v
$ 1.8.8
ruby -v
$ ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601
```

**Comment by BanzaiMan** [comment]
I think EOF is different on Windows. Perhaps `^Z`.

**Comment by MFry** [comment]
@BanzaiMan Thanks for the quick reply! The big issue to me is that adding --add seems to trigger the reading from stdin. It doesn't just add the secure value to the yml file.

**Comment by BanzaiMan** [comment]
When you run `travis encrypt --add deploy.secret_access_key`, can you get out of the command to the prompt if you press *anything*, or do you have to quite the terminal (PowerShell, or Command Prompt, or whatever)?

What is triggering the read is not `--add deploy.secret_access_key`, but the absence of arguments *after* the flag. In other words, 

    travis encrypt --add deploy.secret_access_key SOMEVAR="secretvalue" 

should work for you.

**Comment by MFry** [comment]
@BanzaiMan thanks for the help!
You are correct, I was missing the key-value pair and `ctrl`+`z` does work to stop the stdin (or you can close it with `ctrl`+`c`). 
I think one of my problems was being confused with what the key was in that command since I though
`travis encrypt --add deploy.secret_access_key="secretvalue"` would work, but that wasn't how the command is meant to be run.
