### ISSUE TITLE
pypy2.7-5.8.0 is broken on trusty

### ISSUE THREAD

**Issue by njsmith** [travis-ci/travis-ci#8103]
This .travis.yml errors out before it even reaches my script:
```yml
language: python
python:
  - pypy2.7-5.8.0
sudo: false
dist: trusty
```

It successfully downloads your pypy2.7-5.8.0 tarball, but that tarball appears to be broken:
```
pypy2.7-5.8.0 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/pypy2.7-5.8.0.tar.bz2
$ sudo tar xjf pypy2.7-5.8.0.tar.bz2 --directory /
[...]
$ source ~/virtualenv/pypy2.7-5.8.0/bin/activate
/home/travis/.travis/job_stages: line 54: /home/travis/virtualenv/pypy2.7-5.8.0/bin/activate: No such file or directory
```
Example: https://travis-ci.org/python-trio/trustme/jobs/254722643

Using `pypy3.5-5.8.0` seems to work fine, it's just `pypy2.7-5.8.0` that's broken like this.

**Comment by Lyoness** [comment]
Hi @njsmith -- we've merged pypy version fixes [here](https://github.com/travis-ci/travis-cookbooks/pull/861) thanks to @rht 

It's available only `sudo: required` `group: edge` at the moment,  we hope to promote it to our containerized builds very soon.

**Comment by njsmith** [comment]
I'm confused: looking at that patch, it appears that what it's doing is changing the `pypy` alias to point to 5.7.1? In my example, I'm not using aliases at all, and my point is that you have a build of pypy2 5.8.0 (which supersedes 5.7.1), but it's broken.

**Comment by BanzaiMan** [comment]
@njsmith Sorry about the confusion. I asked @Lyoness to take a look at this without looking into the details. My apologies to both of you.

I think I found the problem with the archiving process, which manifests only for `pypy2*` but not `pypy3*`.

**Comment by BanzaiMan** [comment]
I built `pypy2.7-5.8.0` with the fix. https://travis-ci.org/travis-ci/cpython-builder/builds/255894315

My small test shows that it is working https://travis-ci.org/BanzaiMan/travis_production_test/jobs/255895125#L425

But please test it yourself, and close this issue if you are satisfied.

Thanks.

**Comment by njsmith** [comment]
Yep, seems to be working now, thanks!

https://travis-ci.org/python-trio/trustme/jobs/255905555

**Comment by tonyseek** [comment]
Is it regression again? https://travis-ci.org/tonyseek/python-orphanage/jobs/376262080

**Comment by tobgu** [comment]
I have the same problem as @tonyseek above. Any plans on fixing it? Should I open a new issue for it?
