### ISSUE TITLE
Coverity no longer working on an Android project

### ISSUE THREAD

**Issue by aaronjwood** [travis-ci/travis-ci#8111]
Last year I noticed Coverity stopped working for an Android project of mine. I've been in contact with them and never really got an accurate answer about the situation. They pointed me to https://github.com/travis-ci/travis-ci/issues/6142 the last time I spoke with them but I've found this to not be the issue. FWIW I noticed that things stopped working in November of last year. You can see the last analyzed date https://scan.coverity.com/projects/aaronjwood-portauthority

You can see my `.travisci` file which conforms to what they expect https://github.com/aaronjwood/PortAuthority/blob/development/.travis.yml

Something interesting to note is that it looks like something may either be crashing or getting black holed when the Coverity tool gets executed https://travis-ci.org/aaronjwood/PortAuthority/builds/255100443#L1156
If you look at this build from another project of mine (which is successfully publishing Coverity results and never "broke" on me) you'll see there is a bit more output https://travis-ci.org/aaronjwood/viper/jobs/230194224#L294

I'm not sure if that's due to the type of scan that's being performed (Java vs JS) or if there's something of interest there. Anyone have any ideas about what I'm running into?

**Comment by BanzaiMan** [comment]
# Summary

If anything is going wrong here, it is happening while we execute the script provided by Coverity.

# Details

In https://travis-ci.org/aaronjwood/PortAuthority/builds/255100443#L1147, you see that we are downloading https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh and executing it with `bash` with environment variables `COVERITY_SCAN_*`.

Please keep in mind that this script is beyond our control.

With that disclaimer out of the way, we can look at the script itself. We see [`Running Coverity Scan Analysis Tool...`](https://travis-ci.org/aaronjwood/PortAuthority/builds/255100443#L1156), but not `Tarring Coverity Scan Analysis results...`, so one of these lines are exiting with nonzero status:

```
eval "${COVERITY_SCAN_BUILD_COMMAND_PREPEND}"
COVERITY_UNSUPPORTED=1 cov-build --dir $RESULTS_DIR $COV_BUILD_OPTIONS $COVERITY_SCAN_BUILD_COMMAND
cov-import-scm --dir $RESULTS_DIR --scm git --log $RESULTS_DIR/scm_log.txt 2>&1
```

When the command fails, the entire script bails because it sets `errexit` at the top.

`${COVERITY_SCAN_BUILD_COMMAND_PREPEND}` is set to `./gradlew clean`, and it appears to finish (https://travis-ci.org/aaronjwood/PortAuthority/builds/255100443#L1348).

So the first thing to consider is

```
COVERITY_UNSUPPORTED=1 cov-build --dir $RESULTS_DIR $COV_BUILD_OPTIONS $COVERITY_SCAN_BUILD_COMMAND
```

This evaluates to

```
COVERITY_UNSUPPORTED=1 cov-build --dir cov-int  ./gradlew clean
```

I don't know how this is supposed to behave, but as far as I can tell, but this part of the logic is up to Coverity to handle.

**Comment by aaronjwood** [comment]
I'll see if I can reach out to them regarding this. Is there any way to do some kind of verbose build to see what is causing the exit or to at least see what exit code is being thrown?

**Comment by BanzaiMan** [comment]
> Is there any way to do some kind of verbose build to see what is causing the exit or to at least see what exit code is being thrown?

As the script is provided by Coverity, it is not easy to change its behavior.

**Comment by xirkus** [comment]
It seems that the failure is in the following line in the script:

eval "${COVERITY_SCAN_BUILD_COMMAND_PREPEND}"

which should result in the following being executed:

eval ./gradlew clean

After this command there is no evidence of the following line being executed:

COVERITY_UNSUPPORTED=1 cov-build --dir $RESULTS_DIR $COV_BUILD_OPTIONS $COVERITY_SCAN_BUILD_COMMAND

What we do see in the log is this command being executed:

./gradlew build connectedCheck

which does not match the travis.yml configuraton:

build_command: "./gradlew build"

**Comment by aaronjwood** [comment]
Looks like it's falling back to the default test command for some reason https://docs.travis-ci.com/user/languages/android/#Default-Test-Command-for-Gradle

**Comment by BanzaiMan** [comment]
@aaronjwood [Your configuration](https://github.com/aaronjwood/PortAuthority/blob/df1c1e0a89e9dbeba031c35197dfdbfb6132d9b6/.travis.yml) does not have any `script`, so the default is used.

**Comment by BanzaiMan** [comment]
@xirkus 

> After this command there is no evidence of the following line being executed:
> 
>     COVERITY_UNSUPPORTED=1 cov-build --dir $RESULTS_DIR $COV_BUILD_OPTIONS $COVERITY_SCAN_BUILD_COMMAND

Indeed. This command is most likely failing without much of a fanfare, and the failure is causing the script to bail.

**Comment by aaronjwood** [comment]
@BanzaiMan you're right, I was looking the `build_command` stuff I have but that's all under the `coverity_scan` addons section. Dunno why I assumed that propagated up to the usual travis stuff.

**Comment by aaronjwood** [comment]
@xirkus is there anything I can do to help get this fixed?

**Comment by xirkus** [comment]
I would suggest that you perform a local build capture before trying to
deploy using TravisCI. From what I understand of the submission script, it
is performing as expected. It seems to be an issue with gradle. FWIW, there
are no other projects encountering issues with the script that we've
provided.

**Comment by aaronjwood** [comment]
Sadly, it seems like the issue is Gradle 3.x.

The fix: https://github.com/aaronjwood/PortAuthority/commit/70c1c0fe774fc674e2290ca62202ae6b2dd105c9

Successful build: https://travis-ci.org/aaronjwood/PortAuthority/builds/256729391#L2134

@xirkus Any idea on if Coverity will be updated to work with newer versions of Gradle? It's too bad that 3.x can't be used since Android's Gradle plugin comes with some nice performance/caching enhancements (requiring 3.3+)  https://developer.android.com/studio/releases/gradle-plugin.html#revisions

**Comment by aaronjwood** [comment]
Any update on this?

**Comment by xirkus** [comment]
Sorry; nothing yet.

**Comment by mmoayyed** [comment]
I am running into the same problem as:

```
[WARNING] No files were emitted. This may be due to a problem with your configuration
or because no files were actually compiled by your build command.
Please make sure you have configured the compilers actually used in the compilation.
```

Anyone see the same with Gradle 4+? Specifically 4.4?

**Comment by aaronjwood** [comment]
@mmoayyed I don't think Coverity works with Gradle 3.x or 4.x yet :(
