### ISSUE TITLE
Trouble using private API

### ISSUE THREAD

**Issue by cyberhck** [travis-ci/travis-ci#8112]
# Description
I'm trying to verify why semantic release is failing, after a long debugging, I can see travis is returning `{"file": "not found"}` response for my requests.

# Steps I used
- I tried to get travis's auth token using github token like this:
```http
POST /auth/github HTTP/1.1
Host: api.travis-ci.com
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
	"github_token": "<valid github token>"
}
```

Which returned me with a body similar to:
```json
{
    "access_token": "<some access_token>"
}
```

- Now I tried to get the build information like this:
```http
GET /repos/<organization>/<valid repo>/builds/<build id> HTTP/1.1
Host: api.travis-ci.com
Authorization: token cFLg7HWCT_j6yoPNusVY4A
Accept: application/vnd.travis-ci.2+json
Cache-Control: no-cache
```
which returns:
```json
{
    "file": "not found"
}
```

# Expected
To see some kind of info.

# Actual
404 Not found

I believe this is some kind of permission issue with private api, can someone verify that api.travis-ci.com is working fine?

If I change from .com domain to .org domain and point to some of our opensource project, it works fine.

I've redacted some sensitive info from issue for obvious reason.

**Comment by BanzaiMan** [comment]
Without concrete information on which repository you are trying to use, it is very hard to provide meaningful support. I think this is best dealt with over support ticket. Please close this issue and email us at support@travis-ci.com.

Thanks.

**Comment by cyberhck** [comment]
Hi @BanzaiMan I'm sorry to waste your time, it was a weirdly silly mistake.

Anyone who is facing this issue when using semantic-release, it's because I was using bot user whose Github token was valid, and could login to travis, but the bot didn't have access to the private build, we logged in manually using the bot user, then logged in to travis, granted permissions there, and the issue was solved.

closing this
