### ISSUE TITLE
PHP Nightly on Trusty images - Unexpected failures

### ISSUE THREAD

**Issue by ntwb** [travis-ci/travis-ci#8114]
After switching to Trusty:
• Build 469 https://travis-ci.org/WordPress/wordpress-develop/builds/254762301
• Job 469.10 PHP Nightly https://travis-ci.org/WordPress/wordpress-develop/jobs/254762313

Before switching to Trusty:
• Build 467 https://travis-ci.org/WordPress/wordpress-develop/builds/254710392
• Job 467.10 PHP Nightly https://travis-ci.org/WordPress/wordpress-develop/jobs/254710402

The 467.10 job `failed` correctly as expect.

The 469.10 job `passed` though it actually failed and was unexpected and did not exit with a non-zero exit code

The commit made between the above two builds is here [core.trac.wordpress.org/changeset/41072](https://core.trac.wordpress.org/changeset/41072)

Looking at the versions of installed software between the jobs:

Job 467.10 | Job 469.10
-------|--------
PHP `7.2.0-dev` | PHP `7.2.0-dev`
PHPUnit `6.1.4` | PHPUnit `6.1.4`
MySQL `5.5.41`| MySQL `5.6.33`

I don't see MySQL different versions being the cause of this however

**Comment by BanzaiMan** [comment]
These PHP runtimes are compiled at different times (and presumably with different PHP source commits).

The cause of the errors is that on the Trusty job you are somehow unable to connect to the MySQL database https://travis-ci.org/WordPress/wordpress-develop/jobs/254762313#L466.

I am not sure how your tests are set up, but `grunt` is not reporting this connection problem as an error. https://travis-ci.org/WordPress/wordpress-develop/jobs/254762313#L1793

**Comment by ntwb** [comment]
@BanzaiMan Job restarted and now working as expected, thanks Hiro 💯 

https://travis-ci.org/WordPress/wordpress-develop/jobs/254762313
