### ISSUE TITLE
Julia 0.6 package running in Julia 0.5.2 on Travis-CI

### ISSUE THREAD

**Issue by JeremyRueffer** [travis-ci/travis-ci#8115]
@tkelman, @ninjin, @staticfloat, and @simonbyrne

My package is running on a Julia 0.5.2 instance on Travis-CI despite requiring Julia 0.6.

[ClimateDataIO Travis-CI](https://travis-ci.org/JeremyRueffer/ClimateDataIO.jl/jobs/248819627)

ClimateDataIO Require Contents
```
julia 0.6
DataFrames 0.8.0
ZipFile
```

**Comment by tkelman** [comment]
Don't use "release" in https://github.com/JeremyRueffer/ClimateDataIO.jl/blob/master/.travis.yml, I plan on removing that. Change it to 0.6.

**Comment by JeremyRueffer** [comment]
That fixed it.
