### ISSUE TITLE
Running out of space during deployment

### ISSUE THREAD

**Issue by meets2tarun** [travis-ci/travis-ci#8116]
Travis deployment failed with the error of `no space left on device` although build exited with 0. The issue persists after multiple restarts.
https://travis-ci.org/xeon-zolt/meilix/builds/255183213#L952

There are already issues created in the past but they have no solution and had been sorted too.
https://github.com/travis-ci/travis-ci/issues/4026
https://github.com/travis-ci/travis-ci/issues/2907

**Comment by BanzaiMan** [comment]
Do you know how much disk space your builds are using?

**Comment by meets2tarun** [comment]
Around 3 GB.

**Comment by BanzaiMan** [comment]
Try different `language` values. They have varying disk spaces left after all the software.

**Comment by meets2tarun** [comment]
Which language has max space?

**Comment by Lyoness** [comment]
try using `language: minimal`

**Comment by BanzaiMan** [comment]
Closing.
