### ISSUE TITLE
 brew: command not found on OSX builds

### ISSUE THREAD

**Issue by hcorg** [travis-ci/travis-ci#8117]
looks like #3448 is happening again - in multi OS builds, OSX builds are scheduled to run on ubuntu workers:

https://travis-ci.org/n7mobile/asn1scc.IDE/builds/255225211

**Comment by MariadeAnton** [comment]
Hi @hcorg - we just fixed this see https://www.traviscistatus.com/incidents/74lc35kpxs0y and restarting the build should route it properly now. Could you try restarting it and confirm? Thank you!

**Comment by hcorg** [comment]
it did help, thanks!
