### ISSUE TITLE
Can not login into travis-ci.org

### ISSUE THREAD

**Issue by davidmpaz** [travis-ci/travis-ci#8118]
I apologize if this is not the right place for reporting this. Is just did not found any other place to do it.

I am trying to access my profile by: Sign with Github button. Never pass from: `https://api.travis-ci.org/auth/handshake?......`  get redirected to an Error page after some time.

I have tried to use browser in anonymous mode, also I have revoked OAuth tokens in github.

Am I missing something ?

thanks in advance,
David

**Comment by BanzaiMan** [comment]
Sorry for the issue. If you are still seeing it, please email support@travis-ci.com, and we'll take a look.

**Comment by davidmpaz** [comment]
Thanks for the follow up. I was able to login using chrome on windows. Using chrome on Ubuntu did not success yet, it doesn't matter whether incognito session is used or not.

I will write to the provided email.

Thanks
