### ISSUE TITLE
RethinkDB add-on failing to Install

### ISSUE THREAD

**Issue by cgilson** [travis-ci/travis-ci#8122]
Using the RethinkDB add-on, installation fails with:

```
$ git checkout -qf 635487e816bfdf7b68a63bc5ffefd2960234b9c7
Installing RethinkDB version 2.3.5
rethinkdb: unrecognized service
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.81QoBwTNGL --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x3A8F2399
gpg: requesting key 3A8F2399 from hkp server keyserver.ubuntu.com
gpg: key 3A8F2399: public key "RethinkDB Packaging <packaging@rethinkdb.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
W: GPG error: http://download.rethinkdb.com precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CF9BDC6F03D1F02B
$ sudo apt-get install -y -o Dpkg::Options::='--force-confnew' rethinkdb=$package_version



The following NEW packages will be installed:
  rethinkdb
0 upgraded, 1 newly installed, 0 to remove and 257 not upgraded.
Need to get 14.7 MB of archives.
After this operation, 39.1 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  rethinkdb
E: There are problems and -y was used without --force-yes

Installing RethinkDB default instance configuration
cp: cannot stat `/etc/rethinkdb/default.conf.sample': No such file or directory
Starting RethinkDB v2.3.5
$ sudo service rethinkdb start
rethinkdb: unrecognized service

$ rethinkdb --version
/home/travis/.travis/job_stages: line 850: rethinkdb: command not found
```

Which causes all of our builds to fail. Something has clearly gone wrong with the rethinkDB add-on. Please fix.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by cgilson** [comment]
We don't, the build logs are part of test run in a private repo, but the excerpt above clearly shows the problem. Everything else in our build depends on rethinkdb and fails immediately, and manually installing rethinkdb on a sudo-enabled build fixed it, but drastically increased our test times. I'm guessing something lapsed in the signing for RethinkDB since the organization maintaining it disbanded.

**Comment by BanzaiMan** [comment]
I agree that there is a problem, but it misses some important details about the build itself. If you'd rather not discuss this issue in public, please send email to support@travis-ci.com.

Thanks.

**Comment by cgilson** [comment]
[travis-log.txt](https://github.com/travis-ci/travis-ci/files/1160185/travis-log.txt)

Reviewed the log, I think it should be fine to post publicly here

**Comment by BanzaiMan** [comment]
@cgilson Is that the right log? It does not contain any output from RethinkDB addon.

**Comment by cgilson** [comment]
Nope! Must have grabbed the wrong one. Below should be the correct one.

[travs-log.txt](https://github.com/travis-ci/travis-ci/files/1160255/travs-log.txt)
