### ISSUE TITLE
`cache: cargo` overwrites `$HOME/.cargo/bin`

### ISSUE THREAD

**Issue by CryZe** [travis-ci/travis-ci#8124]
The latest versions of Rust don't seem to be able to be used with rustup 1.4.0 anymore, which is the one that Travis CI uses.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by CryZe** [comment]
https://travis-ci.org/racer-rust/racer/jobs/255346964
https://travis-ci.org/CryZe/livesplit-core/jobs/255302701
https://travis-ci.org/integer32llc/rust-playground/jobs/255088861

```
$ rustup component add rust-src
error: missing key: 'url'
The command "rustup component add rust-src" failed and exited with 1 during .
```

**Comment by CryZe** [comment]
This got fixed in rustup 1.5.0: https://github.com/rust-lang-nursery/rustup.rs/issues/1174

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/builds/255415196#L445 shows that the current effective version of `rustup` is 1.5.0.

We fetch `rustup-init.sh` from `https://sh.rustup.rs` when the app starts, and serve it from https://build.travis-ci.org/files/rustup-init.sh` (https://travis-ci.org/racer-rust/racer/jobs/255346964#L121) I just checked there is any difference between the two files, and found none.

It seems to me that the fix has not made it to 1.5.0.

**Comment by BanzaiMan** [comment]
We can also add `rustup --version` to the announcement section, though.

**Comment by CryZe** [comment]
When I printed it, it said 1.4.0.

https://travis-ci.org/CryZe/livesplit-core/builds/255387936#L276

But looking at all those 3 builds, they are all running on an outdated Travis CI distro (dist: precise). Could that be the reason?

**Comment by BanzaiMan** [comment]
This logic is common across all infrastructures, although it is possible that the installer script itself behaves differently depending on the Ubuntu release. I don't know the internals to say this is true or not.

**Comment by BanzaiMan** [comment]
`rustup --version` should now be displayed. https://travis-ci.org/BanzaiMan/travis_production_test/builds/255415196#L441 (Restarting should show this, too, not just new builds.)

**Comment by CryZe** [comment]
Yeah, it shows it now. But it says it's 1.4.0:
https://travis-ci.org/CryZe/livesplit-core/jobs/255427477#L269

**Comment by CryZe** [comment]
Oh wow, I figured it out. rustup seems to be partially part of the build cache. So for some reason that caused it to never update?! Maybe running `rustup self update` may help. However it's too late for me to test this now, as I've wiped my caches.

**Comment by CryZe** [comment]
A solution could be to remove `.cargo/bin` from the build cache, as that's where the compiler binaries and rustup are stored. However I'm not entirely sure if that will entirely fix it.

**Comment by BanzaiMan** [comment]
I see. So, if you have `rustup` in your cache, it overwrites what is installed by `rustup-init.sh`.

I guess one way to solve this problem is to remove `rustup` from the cache, always. You can do this by

```yaml
before_cache:
  - rm -f $HOME/.cargo/bin/{cargo,rls,rustc,rustdoc,rust-gdb,rust-lldb,rustup}
```

Perhaps this should be documented?

**Comment by CryZe** [comment]
Shouldn't this be fixed instead though, as the default rust language configuration of Travis will always cause that bug.

**Comment by BanzaiMan** [comment]
We do not cache `$HOME/.cargo`.

**Comment by BanzaiMan** [comment]
Well, we provide `cache: cargo`. Hmm.

**Comment by CryZe** [comment]
Yeah, that's what I meant, and that caches .cargo
