### ISSUE TITLE
before_install is run after installing submodules

### ISSUE THREAD

**Issue by gsabran** [travis-ci/travis-ci#8126]
It looks like the before_install hook is run after all the repo is cloned, including submodules. This is problematic when some submodules require specific authentification to be cloned, that could be passed by:

```yaml
before_install:
- echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
```

**Comment by BanzaiMan** [comment]
This issue is described in https://docs.travis-ci.com/user/common-build-problems/#Git-Submodules-are-not-updated-correctly; disable the default submodules behavior and run it yourself.
