### ISSUE TITLE
Why does travis report 'Bad Credential' and 'not a tagged commit' alternately?

### ISSUE THREAD

**Issue by LeiYangGH** [travis-ci/travis-ci#8128]
Hi Men,

I'm new to travis and i'm practicing using travis to build, my goal is to have built output uploaded to github release. But always failed.
**Steps**:

1. Created a github repository to test: https://github.com/LeiYangGH/testci, it is a c# hello world program
2. Generated a personal token in github settings, and in ubuntu, installed ruby, travis cil, and encrypted this key, then added the secure key in .travis.yml
3. Add a **commit.bat** so that i can test commit quickly, each time i just have to edit the version number in the bat file, then run it. then travis build will trigger, but I'm very surprised at the results and don't know what's happening.
My travis builds location: https://travis-ci.org/LeiYangGH/testci/builds
1. From the log you can see **it succeeds and fails alternatively**, but **my only change is the commit tag version number**!
2. When it fails it says bad credential, but you can see i had my secure key unchanged
3. Sometimes it says 'not a tagged commit', but you can see i only change is change the commit tag version number! and from my github tags i'm sure every commit has a tag! https://travis-ci.org/LeiYangGH/testci/builds

Any explanation is appreciated.

<img width="486" alt="buildhis" src="https://user-images.githubusercontent.com/5386998/28398615-9a8406d6-6d3a-11e7-8cc0-247ad13ab2fb.PNG">
<img width="368" alt="tags" src="https://user-images.githubusercontent.com/5386998/28398617-9ea62424-6d3a-11e7-9902-2bc99a1484af.PNG">

**Comment by LeiYangGH** [comment]
Found some fix here: https://github.com/travis-ci/travis-ci/issues/4973
it said we should use travis encrypt -r LeiYangGH/testci --org
which is quite different from docs.travis-ci.com!
After changing the key,
every time it says 'not a tagged commit', but actually I can see deployments were successful. The message is really confusing!

**Comment by BanzaiMan** [comment]
> Hi Men

Please keep in mind that not all of us are "men", so consider a more inclusive phrase.

---

With that out of the way…

When you push tags, there will be two builds triggered (unless you push more than 3 tags at once, in which case GitHub does not deliver tag events to us). One for the commit, and the other for the tag. The former is not a tagged commit, and the latter is.

After the credentials are fixed, you are simply seeing the deployment from the tagged commit. If you do not push the tags, the deployment will not trigger.

**Comment by BanzaiMan** [comment]
Closing. If you have further questions, do ask.

**Comment by grakkit** [comment]
haha internet commenters go "Men"
