### ISSUE TITLE
ImportError: No module named lxml

### ISSUE THREAD

**Issue by JesusZapata** [travis-ci/travis-ci#8132]
I have this repository https://github.com/JesusZapata/travis-ci

In that repository has the follow `.travis.yml` file
```xml
language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - python-lxml

python:
  - "2.7"

env:
  global:
  - LINT_CHECK="0" TESTS="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1"

install:
  - python -c "import lxml;print lxml.__file__"
```

But when ran the travis-ci show the follow error `ImportError: No module named lxml`

You can see one pull request https://github.com/JesusZapata/travis-ci/pull/3 and you can see the travis-ci https://travis-ci.org/JesusZapata/travis-ci/jobs/255655948

**Comment by BanzaiMan** [comment]
Did this ever work?

We use virtualenv to manage Python runtimes on our images, so your `python-lxml` is not found. (Because it goes to the system Python's directories.)

Try installing it with `pip install lxml` (or whatever the package name is).

**Comment by mrichar1** [comment]
I can't comment for `lxml`, but in my case the library was `gi` - and it definitely used to work.

`gi` has to be built against `pygobject` and as such isn't available as a pip install. Therefore I was previously using the `python3-gi` ubuntu package and using system-site-packages. However, even though this package is still being installed, it is no longer available inside the virtualenv (and neither of the methods for requesting system site packages makes a diference).  I've also tried using the `vext` library to work round this, without success.

**Comment by moylop260** [comment]
@BanzaiMan 
I figured out that the main issue is:
[W: --force-yes is deprecated, use one of the options starting with --allow instead.](https://travis-ci.org/JesusZapata/travis-ci/jobs/255655948#L445)

Running the command `$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install python-lxml` for `Ubuntu Trusty` environment.

**Comment by moylop260** [comment]
Any news about
Now we have issues related with wkhtmltopdf

**Comment by bogdanap** [comment]
In order to use python packages installed by apt, the virtualenv needs to be created with the --system-site-packages options. For compatibility reasons, this is only available for the default Python versions that come with Ubuntu (2.7.6 and 3.4.3).
This seems to work as expected, as demonstrated by the following examples:
- lxml: https://travis-ci.org/bogdanap/travis_production_test/builds/308354072
- gi: https://travis-ci.org/bogdanap/travis_production_test/jobs/308357235

**Comment by JesusZapata** [comment]
@bogdanap 
Thanks for your clarify.

In `travis-ci` they have planned to include the another version of python in order to used the `--system-site-packages` with another python version not only the `2.7` and `3.4`

For example to the Ubuntu 16.04 has a python 3.5 for default

**Comment by lamedm** [comment]
For a python newbie, it wasn't obvious that, for python3,  instead of `pip install lxml`  
`pip3 install lxml` would solve this issue.
