### ISSUE TITLE
Not receiving email notifications for GitHub project

### ISSUE THREAD

**Issue by terriyu** [travis-ci/travis-ci#8139]
I setup Travis CI for my Python [GitHub project](https://github.com/voicesauce/opensauce-python), but despite running over a dozen builds, I've never received any email notifications.  Travis build status is [here](https://travis-ci.org/voicesauce/opensauce-python).  The project is under an organization ([voicesauce](https://github.com/voicesauce)), but I'm a team member and listed as an owner (my username is terriyu).  My GitHub primary email address (terri@terriyu.info) is in the commits and I've explicitly asked for all email notifications in the [.travis.yml config file](https://github.com/voicesauce/opensauce-python/blob/master/.travis.yml), so I don't understand what the problem is.  Does Travis not like email address that end in .info ?

**Comment by BanzaiMan** [comment]
Sorry to hear about this issue.

According to the logs, for https://travis-ci.org/voicesauce/opensauce-python/builds/255920172 we did schedule mail delivery:

```
Jul 21 04:48:15 travis-org-tasks-production app/tasks.3: I type=email status=sent msg='email sent' email=ter...@ter....info
```

Was it caught in a spam filter, perhaps?

**Comment by terriyu** [comment]
Unfortunately, I don't see anything in the spam filter.

**Comment by terriyu** [comment]
Do you know the name of the email address from which the notification would be sent from?

**Comment by BanzaiMan** [comment]
It is sent from builds@travis-ci.org for public repositories, and from builds@travis-ci.com for private ones.

**Comment by terriyu** [comment]
I use an email forwarding service for my GitHub email.  The email gets forwarded to my Gmail account.  I asked the email forwarding service to look into this issue.  They think the problem is that the email is being sent through Mandrill, a third-party commercial email service that frequently gets themself blacklisted because they're owned by a company (Mailchimp) that has a bad habit of wrist-slapping people who spam their service to send spam.  They suspect that Gmail is blacklisting Mandrill.

**Comment by terriyu** [comment]
I changed to a different email address and now I'm getting notifications.
