### ISSUE TITLE
abuse detected

### ISSUE THREAD

**Issue by lilgreenbird** [travis-ci/travis-ci#8141]
my PR resulted in a blocked request “abuse detected: known offender (request looked fishy)"

https://travis-ci.org/Microsoft/msphpsql/requests

**Comment by BanzaiMan** [comment]
Please email us at support@travis-ci.com. Thanks.

**Comment by lilgreenbird** [comment]
I have done that already, when should I expect a response?

**Comment by cotsog** [comment]
@lilgreenbird: Sorry for the delay of our reply. We've been able to clear this out. Thank you for your patience!
