### ISSUE TITLE
OSX installs python for no reason, duplicateds linux instance 

### ISSUE THREAD

**Issue by mayou36** [travis-ci/travis-ci#8144]
Hi,

for some reason, the following build behaves wrong. I removed everything down to the essentials:

```bash
os: linux
sudo: false/required (tried both)
language: python
python:
 - '3.4'
 - '3.5'
 - '3.6'

matrix:
 include:
  - os: osx
  - language: generic

script:
 - echo "no tests"
```

What is expected to happen:
3 instances of linux with 3.4, 3.5, 3.6 (works)
1 instance of osx without a specific language (or, ok, the ruby fallback)

what happens instead:
3 instances, which are ok
osx tries to install python and fails (why does it install python? is generic=python? Do I have to specify explicitly a different language like ruby in order not to have python installed?). As in the log python 3.4 is specified, travis seems from the script above to infer that generic=python. Is that expected behavior?
another linux instance with python 3.4 is created (yes, in total there are two linux instances with python 3.4). To notice is that $TRAVIS_PYTHON_VERSION is not set in this instance. This instance is, to me, very odd and I did not find any possible explanation reading the docs and searching the web why this instance is created.

The build and it's logs can be viewed here: https://travis-ci.org/Phynix/uniphy/builds/256410374

**Comment by BanzaiMan** [comment]
Here:

```yaml
matrix:
 include:
  - os: osx
  - language: generic
```

From what you describe, you want

```yaml
matrix:
 include:
  - os: osx
    language: generic
```

**Comment by mayou36** [comment]
-.- starring for too long at the same code...
Thanks a lot, @BanzaiMan
