### ISSUE TITLE
Deploy does not work when tag build is ran from cron

### ISSUE THREAD

**Issue by AMDmi3** [travis-ci/travis-ci#8146]
Here's a project: https://travis-ci.org/repology/homebrew-json-gen-travis

It's set up to rebuild `latest` tag from time to time in order to update github artifact tied to the tag.

When the tag is manually updated everything works fine, however when the very same tag is built from cron, deploy does not happen:

```
Skipping a deployment with the releases provider because this is not a tagged commit
```

The cron/non cron builds look identical, the same branch (in travis terms), the same commit, the same checkout command, however with cron build travis deploy code seem to fail to recognize the build as tag build.

Manual build:
https://travis-ci.org/repology/homebrew-json-gen-travis/builds/256019468

Cron build:
https://travis-ci.org/repology/homebrew-json-gen-travis/builds/256149220

**Comment by AMDmi3** [comment]
I'd rather say it's a bug.

**Comment by AMDmi3** [comment]
No, the issue still exists

**Comment by BanzaiMan** [comment]
Could you elaborate on your use case here? Can you just run a job with `cron`, tag the present commit and push the tag to GitHub?

**Comment by cytopia** [comment]
I am facing the same issue. To give you some information about the use case:

I have a repository of Docker images with a couple of _active_ tags that need to be built nightly. The travis job will only push built docker images if they are on a tag. So by adding those tags to the Travis cron job for nightly/daily builds, the job runs and is then stuck at this condition:

```bash
if [ -n "${TRAVIS_TAG}" ]; then
    make push
fi
```

However, the variable is not set in cronjobs and my tags are never rebuilt.

**Comment by BanzaiMan** [comment]
A major problem here is that tags are tied to commits, whereas we run cron jobs on branches. They work independently.

What you can do here is: On the cron job, fetch tags, and if there is any tag associated with the present commit, carry out the task.

**Comment by cytopia** [comment]
> What you can do here is: On the cron job, fetch tags, and if there is any tag associated with the present commit, carry out the task.

Thanks for this hint. I am now trying it out, looks like so:

```bash
if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then
  if MY_TAG="$( git describe --exact-match "$(git rev-parse HEAD)" 2>/dev/null )"; then
    echo "Pushing cron tag ${MY_TAG}";
    docker tag "${IMAGE}:${PHP}-base" "${IMAGE}:${PHP}-base-${MY_TAG}" &&
    docker tag "${IMAGE}:${PHP}-mods" "${IMAGE}:${PHP}-mods-${MY_TAG}" &&
    docker tag "${IMAGE}:${PHP}-prod" "${IMAGE}:${PHP}-prod-${MY_TAG}" &&
    docker tag "${IMAGE}:${PHP}-work" "${IMAGE}:${PHP}-work-${MY_TAG}" &&
    docker push "${IMAGE}:${PHP}-base-${MY_TAG}";
    docker push "${IMAGE}:${PHP}-mods-${MY_TAG}";
    docker push "${IMAGE}:${PHP}-prod-${MY_TAG}";
    docker push "${IMAGE}:${PHP}-work-${MY_TAG}";
  fi
fi
```
