### ISSUE TITLE
Travis does not execute before_cache and does not upload cache on dist:precise

### ISSUE THREAD

**Issue by gabyx** [travis-ci/travis-ci#8147]
The following travis code does not upload the cache

https://github.com/gabyx/ApproxMVBB/blob/master/.travis.yml

The `Build branch updates` is set to `On`.
There have not been any caches generated since I tried hard to make it work...

Build log: https://travis-ci.org/gabyx/ApproxMVBB/jobs/256614208
Travis File: https://github.com/gabyx/ApproxMVBB/blob/master/.travis.yml
Is this a bug?

**Comment by BanzaiMan** [comment]
Your build is `source`ing https://github.com/gabyx/ApproxMVBB/blob/c60a35913e6dbc7b770fed3c60f0e3407a4bc1d0/travis/build.sh, which is `exit`ing on line 7. This `exit`s the build altogether, and nothing gets executed after that. You'd probably want `return` instead of `exit`.

**Comment by BanzaiMan** [comment]
Or, execute the script, instead of `source`ing it.

**Comment by gabyx** [comment]
Thx for the quick fix, I was dumb not seeing it
