### ISSUE TITLE
`travis` database (MySQL) inconsistency on Trusty

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#8150]
On Trusty container:
* with `php: 7` MySQL database `travis` exists
* with `php: 7.1` MySQL database `travis` exists
* with `php: nightly` MySQL database `travis` doesn't exists

It wasn't present in any of corresponding Precise images before.
Also `hhvm` images seem to have `travis` database.

Could you, please, make it always either present or not and document this again?
Related to inconsistency #6860 and could probably fixed together.

**Comment by BanzaiMan** [comment]
This is strange. The choice of `php` version should not affect the build image in use, which should dictate what databases are configured.

Do you have a build log URL that shows the problem you are describing here?

A more likely explanation is that the database exists on all, but sometimes your job cannot connect to MySQL. This is #8137.

**Comment by nazar-pc** [comment]
Yes, I have: https://travis-ci.org/nazar-pc/CleverStyle-Framework/builds/256768597
Now I think it might be actually related #8152 in a sense that the old version of PHP 7.0 is used for whatever reason. I suspect newer version of PHP might resolve both of these issues.

**Comment by BanzaiMan** [comment]
Where in https://travis-ci.org/nazar-pc/CleverStyle-Framework/jobs/256768598 does the log indicate the database `travis` does not exist?

As I indicated before, the choice of `php` version does not affect the image selection.

**Comment by nazar-pc** [comment]
I'm sorry, looks like I was confused with another issue, another build log and another MySQL error.

`travis` database is present in hhvm version (https://travis-ci.org/nazar-pc/CleverStyle-Framework/jobs/256763211/config), which are kind of also php, but it was so for a long time now, so I don't know if you consider this inconsistent.
