### ISSUE TITLE
python-2.7.8.tar.bz2 is not a bzip2 file

### ISSUE THREAD

**Issue by ezyang** [travis-ci/travis-ci#8153]
In this log https://travis-ci.org/ezyang/pytorch/jobs/256931449 Travis's Python initialization does not work.

```
2.7.8 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-2.7.8.tar.bz2
$ sudo tar xjf python-2.7.8.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command "sudo tar xjf python-2.7.8.tar.bz2 --directory /" failed and exited with 2 during .
```

Perplexingly, this very same build script works in the PyTorch main repo. Are we doing something wrong, or is there some problem with AWS?

**Comment by ezyang** [comment]
Yeah, it's the earliest version of Python we are actively testing / claim support for.

**Comment by BanzaiMan** [comment]
Why 2.7.8, and not 2.7.9, for example?

**Comment by tekulvw** [comment]
It seems like this is happening for versions `3.5.3` and `3.6.1` for us as well, just started happening ~40 minutes ago.

**Comment by samj1912** [comment]
Ditto, happening with py3.6

**Comment by thaddock** [comment]
It's happening for `3.5.2`:
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/3.5.2-python.tar.bz2
$ sudo tar xjf python-3.5.2.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by BanzaiMan** [comment]
@thaddock That was a bad deploy. Sorry about that. Please restart the affected builds.

**Comment by ezyang** [comment]
@BanzaiMan Is 2.7.9 built for Trusty? If so, it may not be too big of a deal for us to bump to that version. We definitely do want to compile with some older versions of 2.7, because not all of our users have managed to get off of Precise after the EOL (unlike you guys :)

**Comment by BanzaiMan** [comment]
2.7.9 should be available for Trusty now.

**Comment by ezyang** [comment]
OK, we bumped to use that, all set!
