### ISSUE TITLE
Package wouldn't upload after successful build

### ISSUE THREAD

**Issue by jarun** [travis-ci/travis-ci#8156]
I am not an expert in Travis so please feel free to ask questions to extract more info.

On every release, I build a deb package and attach it to my release page. I enabled Python 3.6 in my project recently.

Yesterday I got an error after adding a new tag (for next release): https://travis-ci.org/jarun/imgp/jobs/256748802

This was a working setup but I added the `fakeroot` package (https://github.com/jarun/imgp/commit/2f8539ac69eb25b5a901e9e0f8964518521d822f) as the message indicated.

Now my builds are successful but the deb package is no longer uploaded. I get some messages at the end: https://travis-ci.org/jarun/imgp/jobs/256752507
but I'm not sure how to act on it.

Any help is much appreciated.

**Comment by BanzaiMan** [comment]
If you are trying to upload build artifacts, you need to skip cleanup. https://travis-ci.org/jarun/imgp/jobs/256752507#L638 https://docs.travis-ci.com/user/deployment/#Uploading-Files

**Comment by jarun** [comment]
Works like a charm! Thank you!
