### ISSUE TITLE
Skip a stage for PRs

### ISSUE THREAD

**Issue by akosyakov** [travis-ci/travis-ci#8163]
We have a build with `test` and `deploy` stages and would like to run `deploy` stage only on the master branch and not on PRs. Is it possible? Or at least mark a build as successful if `test` stage is successful for PRs.

Our config: https://github.com/theia-ide/theia/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
This is basically a duplicate of #7181.

(Build stages are a different kind of build matrices.)
