### ISSUE TITLE
Trusty taking more time than Precise

### ISSUE THREAD

**Issue by WaleedAshraf** [travis-ci/travis-ci#8165]
With trusty travis is taking around 33min for jobs which were completing in around 23min while using Precise.
I have observed this in almost 50+ jobs which ran on Trusty. avg is around 33min in all jobs.
When switched back to `dist: precise`, jobs were normal around 22mins.

Here's a log from 17th July: 

Here's one from 24th July.

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate of #8162.

**Comment by BanzaiMan** [comment]
@WaleedAshraf Do you have a build log to show the problem?

**Comment by WaleedAshraf** [comment]
@BanzaiMan I have attached some screen-shots above. Let me know if you need anything else.

**Comment by BanzaiMan** [comment]
@WaleedAshraf Those are screenshots of Slack notifications. I would like to have build log URLs that shows characteristics of the builds. If you'd rather not share them, please email them to us at support@travis-ci.com. Thank you!

**Comment by WaleedAshraf** [comment]
@BanzaiMan mail sent.
