### ISSUE TITLE
/usr/share/docker-engine/contrib/mkimage.sh has gone missing

### ISSUE THREAD

**Issue by dlech** [travis-ci/travis-ci#8168]
I attempted a rebuild of a repository that was working 3 months ago (so nothing has changed on my end), but now it is failing because `/usr/share/docker-engine/contrib/mkimage.sh` is missing.

As far as I know, this file should be installed by the `docker-engine` Ubuntu package. Has something changed in the last 3 months that would cause this file to not be installed?

Here is the build for reference: https://travis-ci.org/ev3dev/docker-base/jobs/214376692

**Comment by BanzaiMan** [comment]
I believe they've renamed the package to `docker-ce`. You should call `/usr/share/docker-ce/contrib/mkimage.sh` instead. https://travis-ci.org/BanzaiMan/travis_production_test/builds/257840237#L630

**Comment by dlech** [comment]
Thank you! That got me fixed up.
