### ISSUE TITLE
Travis not removed from PRs

### ISSUE THREAD

**Issue by chashmeetsingh** [travis-ci/travis-ci#8169]
Even though I removed .travis.yml and disabled it from the settings at travis-ci.org, I can still see travis status being reflected in the PRs, for ex: https://github.com/fossasia/susi_iOS/pull/181
Please let me know what steps need to be taken except disabling travis from the web UI.
Thanks!

**Comment by BanzaiMan** [comment]
This is a manual process at the moment. Please email us at support@travis-ci.com.

Thanks.

I'm closing this in the mean time.

**Comment by BanzaiMan** [comment]
On a second thought… You are asking about the GitHub status?

**Comment by chashmeetsingh** [comment]
No, it's just removing travis from the repo so that it doesn't show up in PRs.

**Comment by BanzaiMan** [comment]
I don't think removing our data will do anything to the events and statuses on GitHub.

**Comment by chashmeetsingh** [comment]
So, how do I remove travis being shown on the PRs, already disabled it from the web UI and removed from settings of the repo but it still stays in the PRs.

**Comment by BanzaiMan** [comment]
I don't think GitHub provides a means to do that.

**Comment by BanzaiMan** [comment]
Can this be closed?

**Comment by chashmeetsingh** [comment]
Yup.
