### ISSUE TITLE
Missing ruby version (2.0.0-p648) for xcode9 osx image

### ISSUE THREAD

**Issue by nap-sam-dean** [travis-ci/travis-ci#8170]
Hi,

I'm getting this error when building on the xcode9 image:

```
$ rvm use $(< .ruby-version) --install --binary --fuzzy
ruby-2.0.0-p648 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-2.0.0-p648 do rvm gemset create ' first, or append '--create'.
The command "rvm use $(< .ruby-version) --install --binary --fuzzy" failed and exited with 2 during .
```

My .ruby-version contains `2.0.0-p648`

The documentation here (https://docs.travis-ci.com/user/reference/osx/#Ruby-versions-implementations) says that ruby 2.0.0-p648 is the default installed version?

Jobs on the same build are passing using the xcode8.3 osx_image.

Should I be using a different ruby version for this image, and if so is there a common version between the xcode8.3 and xcode9 images I can use to keep things consistent?

Thanks.

**Comment by nap-sam-dean** [comment]
Hmmm, `2.4.1` works on both images so I can use that.

**Comment by grosser** [comment]
This works:
```
rvm: system
before_install: sudo gem install bundler
```
