### ISSUE TITLE
Build job killed with trusty

### ISSUE THREAD

**Issue by andreasmuelder** [travis-ci/travis-ci#8172]
While downloading a P2 repository via maven  the build job gets killed with trusty, precise is working.
For example:
https://travis-ci.org/Yakindu/statecharts/jobs/257784722

```
[INFO] Resolving dependencies of MavenProject: org.yakindu.sct.plugins:org.yakindu.sct.model.resource:3.0.0-SNAPSHOT @ /home/travis/build/Yakindu/statecharts/plugins/org.yakindu.sct.model.resource/pom.xml
[INFO] Resolving class path of MavenProject: org.yakindu.sct.plugins:org.yakindu.sct.model.resource:3.0.0-SNAPSHOT @ /home/travis/build/Yakindu/statecharts/plugins/org.yakindu.sct.model.resource/pom.xml
[INFO] Computing target platform for MavenProject: org.yakindu.sct.plugins:org.yakindu.sct.model.stext.ui:3.0.0-SNAPSHOT @ /home/travis/build/Yakindu/statecharts/plugins/org.yakindu.sct.model.stext.ui/pom.xml
[INFO] Resolving dependencies of MavenProject: org.yakindu.sct.plugins:org.yakindu.sct.model.stext.ui:3.0.0-SNAPSHOT @ /home/travis/build/Yakindu/statecharts/plugins/org.yakindu.sct.model.stext.ui/pom.xml
/home/travis/.travis/job_stages: line 57:  3924 Killed  
```

**Comment by BanzaiMan** [comment]
My first guess is that your job is too resource intensive to be running on containers. Please try `sudo: required` at the top level. https://docs.travis-ci.com/user/reference/trusty#Fully-virtualized-via-sudo%3A-required

Thanks.

**Comment by codylerum** [comment]
@BanzaiMan FYI I have repos like this that have been running fine on precise container but fail almost every time when they are kicked to trusty container

**Comment by andrewvaughan** [comment]
Also having this issue with new Trusty:

https://travis-ci.org/andrewvaughan/uhppote-rfid/builds/278036748

I attempted to run my jobs with a higher privilege to no avail.  I also attempted to debug with a local Docker install, but the published containers do not match what is being run with Travis.  Something is definitely misconfigured and not enough is released to the community to help debug.

**Comment by edublancas** [comment]
Any solution to this? I'm having the same problem: https://travis-ci.org/paninski-lab/yass/jobs/335478425

```
The command "pip install ." exited with 0.
1.03s$ pytest --flake8
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/travis/build/paninski-lab/yass, inifile: setup.cfg
plugins: flake8-0.9.1
collecting 94 items                                                            /home/travis/.travis/job_stages: line 57:  4898 Aborted                 (core dumped) pytest --flake8
The command "pytest --flake8" exited with 134.
Done. Your build exited with 1.
```

**Comment by damienstanton** [comment]
I'm also seeing this problem:
```
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/travis/build/damienstanton/lab, inifile:
collected 1 item                                                               
tests/test_imports.py /home/travis/.travis/job_stages: line 57:  3933 Aborted                 (core dumped) pytest

The command "pytest" exited with 134.

Done. Your build exited with 1.
```
Prepending my travis file with `sudo: required` did not fix the issue.

**Comment by ctubbsii** [comment]
I'm seeing this same problem on Java builds: https://travis-ci.org/apache/fluo-recipes/builds/347546473
The only thing that seems to work is unsetting _JAVA_OPTIONS environment variable.
I cannot reproduce the problem running Travis locally in Docker.
