### ISSUE TITLE
the option `sudo: required` is not honored

### ISSUE THREAD

**Issue by randy3k** [travis-ci/travis-ci#8173]
It just happens recently, my [.travis.yml](https://github.com/divmain/GitSavvy/blob/5a90caf901fff732554a548f350eedd1449b8453/.travis.yml) has `sudo: required`
but https://travis-ci.org/divmain/GitSavvy/jobs/258009970/config doesn't honor it.

For comparison, an earlier build https://travis-ci.org/divmain/GitSavvy/jobs/257991116/config has `sudo: required`

**Comment by BanzaiMan** [comment]
Please double check your configuration.

[The build in question](https://travis-ci.org/divmain/GitSavvy/jobs/258009970/) points to https://github.com/divmain/GitSavvy/commit/347c6ac1b2ef95d4617af48b2d4a6d17104f22ff, which [does not have `sudo: required`](https://github.com/divmain/GitSavvy/blob/347c6ac1b2ef95d4617af48b2d4a6d17104f22ff/.travis.yml).
