### ISSUE TITLE
eslint not working on trusty as expected.

### ISSUE THREAD

**Issue by WaleedAshraf** [travis-ci/travis-ci#8174]
Eslint build which worked fine on Precise started to fail on Trusty env.
And it passed again when I moved back to precise.
Issue is with space/tab indent size.

Trusty: https://travis-ci.com/caremerge/hfp-users-service/builds/51116349?utm_source=github_status&utm_medium=notification

Precise: https://travis-ci.com/caremerge/hfp-users-service/builds/51117628?utm_source=github_status&utm_medium=notification

**Comment by BanzaiMan** [comment]
I am sorry, but we do not have access to the code to explain this behavior. Could you try running the build in debug mode to see if the error is legitimate?

**Comment by WaleedAshraf** [comment]
Yes, I did run in debug mode. It reproduced in debug mode.
These error are not reproducing when running lint on local, and also not on precise.
The lines mentioned in error logs are commented lines. like this
`      /** Find residents for input facilities **/`
The indent is correct, not sure what issue here. I think trusty is have some change in tab or space size ?

**Comment by BanzaiMan** [comment]
You were able to reproduce it, but couldn't figure out why it failed?

**Comment by WaleedAshraf** [comment]
Yes, it's only appearing on Trusty (in simple build and also in debug mode), but I'm not able to find the cause. 
As there was no change in that file from last 3,4 weeks. Just moved to trusty from precise.
