### ISSUE TITLE
Secure env variables in command

### ISSUE THREAD

**Issue by purohit** [travis-ci/travis-ci#8175]
I'm having a really hard time getting secure environment variables to be interpolated in the build script. For example, one of the lines in my .travis.yml file is:

```
script:
    # Build using GCE
    - gcloud [...] --substitutions _AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID,_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
```

In the repo settings I set two environment variables:
- `AWS_ACCESS_KEY_ID` to some value `ABC` (normal)
- `AWS_SECRET_ACCESS_KEY` to some value `DEF` (secret, i.e. value not displayed in build log)

But while I expect the command to be run to be:

```
gcloud [...] --substitutions _AWS_ACCESS_KEY_ID=ABC,_AWS_SECRET_ACCESS_KEY=DEF
```

The actual command run is 

```
gcloud [...] --substitutions _AWS_ACCESS_KEY_ID=ABC,_AWS_SECRET_ACCESS_KEY=
```

I understand the value being blanked out in the build log, but it's not just that. The command that is actually run is the same as displayed; i.e., totally missing the value of `$AWS_SECRET_ACCESS_KEY`. So the `gcloud` command just gets an empty value for that env variable.

What is going on? How do I get travis to call a command and expand a secret env variable? I need to pass these secret credentials through to the `gcloud` command and can't figure out how.

Thanks for your help.

**Comment by BanzaiMan** [comment]
Are you sure `$AWS_SECRET_KEY` is set to the value you expect? If we recognize it as a secret, then it should show in the logs as `[secure]`.

**Comment by purohit** [comment]
Oh man, fail on my part. No, I had named it `AWS_SECRET_ACCESS_ID` instead of `_KEY`. I couldn't for the life of me find it, but thanks -- everything works now as expected and I get `[secure]` output in the log as expected and the correct command is run.
