### ISSUE TITLE
I don't specify any dist, but I get dist "precise"

### ISSUE THREAD

**Issue by mulkieran** [travis-ci/travis-ci#8178]
My understanding was, that at this time, default dist is "trusty", so I should not be getting precise.

Travis: https://travis-ci.org/stratis-storage/devicemapper-rs/builds/258254607.
GitHub PR: https://github.com/stratis-storage/devicemapper-rs/pull/111.

**Comment by BanzaiMan** [comment]
The switch is getting rolled out with small increments. If your repository is not seeing it, it will come at some point in the near future. Please see the calendar at the end of https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming.

**Comment by BanzaiMan** [comment]
This should no longer be an issue. Do let us know if you continue to see problems.
