### ISSUE TITLE
No build on travis-ci.org after moving repo from travis-ci.com and multiple commits

### ISSUE THREAD

**Issue by jswny** [travis-ci/travis-ci#8179]
I have the same problem as #6932. Basically, after making [my repo](https://github.com/jswny/simplexdb) public and moving it from .com to .org while still having a `.travis.yml` file the whole time, builds do not trigger at all after testing with multiple commits. The builds were working completely fine on .com before this, so they should be working the same on .org, but they are not triggering at all. In addition, my repo still appears in .com despite the fact that it is public and not private anymore. I've synced both .com and .org with GitHub multiple times.

**Comment by BanzaiMan** [comment]
Did you activate the repository on https://travis-ci.org/profile/jswny?

**Comment by jswny** [comment]
@BanzaiMan Yes. The repo is activated on .org and deactivated from .com.

**Comment by BanzaiMan** [comment]
@jswny Thanks for checking. I just double checked the hook on our side as well, and found that it was outdated. I fixed this now, please push another commit to confirm.

Sorry about the troubles.

**Comment by jswny** [comment]
@BanzaiMan Thank you! I'll try to push a commit later today to confirm that this is fixed. Is it possible that the hooks don't automatically refresh and that something needs to be done to fix this? I've seen reports of the same kind of issue before and I believe I have encountered this in the past as well.

**Comment by jswny** [comment]
Closing this as it is resolved but I will be making a new issue for the same exact issue in a different repo.

**Comment by DoanTran** [comment]
@BanzaiMan I have the same issue, please check it for me at https://travis-ci.org/DoanTran/itviec.com

**Comment by BanzaiMan** [comment]
@DoanTran https://travis-ci.org/DoanTran/itviec.com/requests https://github.com/DoanTran/itviec.com/blob/38b1946da7efe35e0b5a33571a0e40a95c6f143a/.travis.yml#L3-L6 has

```yaml
branches:
  only:
    master
    develop
```
which defines `branches.only: "master develop"`, which does not meet any branch name.

What you want is

```yaml
branches:
  only:
    - master
    - develop
```

**Comment by DoanTran** [comment]
@BanzaiMan Thank you very much. It works now.

**Comment by galwaycoder** [comment]
Hi, I'm having the same issue after syncing multiple times, adding the .travis.yml file and pushing commits. Any recommendations?
