### ISSUE TITLE
Javac doesn't support the "modulesourcepath" attribute

### ISSUE THREAD

**Issue by hakdogan** [travis-ci/travis-ci#8184]
Hi.

https://travis-ci.org/hakdogan/Java9#L431

The ``javac -J-Xmx32m -version``command output is ``javac 9`` but I'm getting the "**Javac doesn't support the modulesourcepath attribute**" error.

Any idea about the problem?

Thanks.

**Comment by hakdogan** [comment]
Hi.

I found the source of this problem. The problem was caused by the version of the ant which used by Travis. When updated the version, the problem was solved.

Thanks.

**Comment by BanzaiMan** [comment]
Looks like this can be closed.
