### ISSUE TITLE
Issue while installing ibm-sdk-8 in travis

### ISSUE THREAD

**Issue by ameyjadiye** [travis-ci/travis-ci#8186]
Hi,

as travis dont provide ibm-jdk-8 i'm trying to install it onfly and set JAVA_HOME to newly installed ibm jdk 8 but its not allowing me to do so.

here is the detail stack trace. https://travis-ci.org/ameyjadiye/commons-text/jobs/258930012

I would appreciate if someone can tell the cause and its *fix*

```
JRE libraries are missing or not compatible....
Exiting....
Error: JAVA_HOME is not defined correctly.
  We cannot execute /tmp/jdk/ibmjdk8/ibm-java-i386-80/bin/java
```

I tried installing this on my laptop with below information and it works really fine.

```
amey@xps ~/work/opensource/apache/commons/commons-text $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena
amey@xps ~/work/opensource/apache/commons/commons-text $ uname -a
Linux xps 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by ameyjadiye** [comment]
Here is the Travis settings I did for commons text https://github.com/ameyjadiye/commons-text/tree/travis-fix, I would appreciate any kind of help on this.

**Comment by chandrams** [comment]
Can you try installing IBM Java8 Linux AMD64 build and check if that works?

**Comment by ameyjadiye** [comment]
Thanks for the clue @chandrams  ... x86_64 worked like a charm :D

**Comment by chandrams** [comment]
Hi @ameyjadiye - IBM Java8 build is now available on Travis, you can use it by including the following in the .travis.yml

matrix:
  include:
    - os: linux
      sudo: required
      group: edge
      jdk: ibmjava8

https://github.com/chandrams/myproj/blob/jdk_switcher/.travis.yml

It will be included in the stable trusty images and will be announced officially in early December
