### ISSUE TITLE
Log output is truncated in most of the builds

### ISSUE THREAD

**Issue by php-coder** [travis-ci/travis-ci#8189]
I see that on many of the builds, the log is truncated. Here are some examples:
- https://travis-ci.org/php-coder/mystamps/jobs/259359149
- https://travis-ci.org/php-coder/mystamps/jobs/259294766
- https://travis-ci.org/php-coder/mystamps/jobs/259359082
- https://travis-ci.org/php-coder/mystamps/jobs/259359081

It happens very frequently and doesn't depend on what distro is used (I tried new Trusty and the behavior is the same).

BTW I'm not using containerized builds.

**Comment by php-coder** [comment]
No one experienced this? It's annoying because I can't debug failed builds because of this :(((

**Comment by roversch** [comment]
Same here: https://travis-ci.org/acados/acados/jobs/263076355

**Comment by Shamar** [comment]
Same here too: https://travis-ci.org/JehanneOS/jehanne/builds/263680703

I was looking at the log and there was a certain amount of it, the build was going.
Then I went to the raw log, and saw it was incomplete. Back to the build web page the log was not incomplete. 

The build failed due to no output for 10 minutes, but I have no way to know if there was actually no output or the output was simply lost, like the truncated one.

I started the build again, let see what will happen.

**Comment by php-coder** [comment]
Ping, it still there and I couldn't get the logs from the failed build to find out what has happened: https://travis-ci.org/php-coder/mystamps/jobs/268989113

Is it a problem with showing logs or they haven't been saved?

**Comment by php-coder** [comment]
I suspect that the problem is caused by the way of how my script work. They don't produce any output during the most of the time and save all the output to the files. At the end, they show some statistics and print the content of the files with the output of the commands. I did that to be able to have a short summary of the building at the top of the log.

I don't know how it can be related but that's the most huge customization that I did.

**Comment by php-coder** [comment]
> They don't produce any output during the most of the time and save all the output to the files. At the end, they show some statistics and print the content of the files with the output of the commands.

That is not the cause. My next theory is that my scripts produces to many output in very short amount of time. I'm trying to split one huge script into the separate small scripts.

Unfortunately there is no feedback and clues from Travis CI team, so I have to debug it myself...

**Comment by php-coder** [comment]
> I'm trying to split one huge script into the separate small scripts.

That helped me. Instead of having a one script in the `script` block, now I have a couple, so their output counted differently and I don't exceed this output buffer.

**Comment by php-coder** [comment]
> That helped me. Instead of having a one script in the script block, now I have a couple, so their output counted differently and I don't exceed this output buffer.

It was a wrong theory while it worked in some circumstances. The real solution is to execute `sleep` after the scripts that produce a lot of output. In this case, Travis CI will be able to gather all their output.

Duplicates https://github.com/travis-ci/travis-ci/issues/6018

**Comment by php-coder** [comment]
Duplicate of  #6018
