### ISSUE TITLE
Documentation of TRAVIS_BRANCH environment variable not precise

### ISSUE THREAD

**Issue by Junkern** [travis-ci/travis-ci#8200]
(Not sure whether this fits here or at https://github.com/travis-ci/docs-travis-ci-com)

I stumbled on this recently, and I think the documentation might not be precise enough..

>> TRAVIS_BRANCH:
    for push builds, or builds not triggered by a pull request, this is the name of the branch.
    for builds triggered by a pull request this is the name of the branch targeted by the pull request.
        Note that for tags, git does not store the branch from which a commit was tagged.

However, when I push a tag (named `test1` ), the `TRAVIS_BRANCH` equals the tag name:
```
TRAVIS_PULL_REQUEST: false
TRAVIS_PULL_REQUEST_BRANCH:  EMPTY
TRAVIS_BRANCH: test1
TRAVIS_TAG: test1
```

This might sense in the context of `..or builds not triggered by a pull request, this is the name of the branch`. However, then it contradicts to `Note that for tags, git does not store the branch from which a commit was tagged`.

Or could it be that I am not understand the documentation?^^

**Comment by BanzaiMan** [comment]
You are right to point out this conflation of `$TRAVIS_BRANCH` and `$TRAVIS_TAG`. This issue is basically a variant of https://github.com/travis-ci/travis-ci/issues/4745, which we have on our roadmap to fix (but somewhat low priority over the years).

We welcome your suggestion to improve the documentation in the mean time.

**Comment by KevinYaoooooo** [comment]
I met this issue too, any progress?

**Comment by BanzaiMan** [comment]
@KevinYaoooooo If you are keen on contributing documentation improvements, please see https://github.com/travis-ci/docs-travis-ci-com/ (or use the "Improve …" button on the upper righer corner of https://docs.travis-ci.com/user/environment-variables).

For technical discussion, please see #4745, as I previously suggested. There is no other update.

**Comment by LorensK** [comment]
@BanzaiMan you can close this one too 👍 as per PR#1407
