### ISSUE TITLE
mercurial missing in `dist: trusty`

### ISSUE THREAD

**Issue by asottile** [travis-ci/travis-ci#8202]
documentation [here](https://docs.travis-ci.com/user/reference/trusty#Version-control) indicates mercurial should be installed.

I am finding it is [not installed](https://travis-ci.org/asottile/venv-update/jobs/260833541) (^F `Cannot find command 'hg'`)

**Comment by BanzaiMan** [comment]
Where is your process looking for `hg`? https://travis-ci.org/BanzaiMan/travis_production_test/jobs/264968426#L427-L428

**Comment by asottile** [comment]
The path appears to be `:/bin:/usr/bin` -- the `mercurial` package for trusty (also xenial) installs to:

```
$ dpkg -L mercurial | grep /hg$
/usr/bin/hg
```

From a [cursory test](https://travis-ci.org/asottile/travis-ci-test#L432-L433) it appears travis-ci has moved this binary into `/usr/local/bin`?

**Comment by BanzaiMan** [comment]
Ah, I see. The `mercurial` package is indeed missing from the GCE images (`sudo: required`). https://travis-ci.org/BanzaiMan/travis_production_test/jobs/264968427#L442

**Comment by Lyoness** [comment]
@asottile the mercurial PATH has indeed changed from precise to trusty.  `/usr/bin/hg` is now  `/usr/local/bin/hg` in Trusty.   If you could change your PATH for now, we're working on a cleanup PR for mercurial.
