### ISSUE TITLE
[Trusty 2017Q2] Yarn not autmatically updated

### ISSUE THREAD

**Issue by dmason30** [travis-ci/travis-ci#8203]
Before when it was using precise by default it used to automatically upgrade yarn on node builds. 

On the now default trusty dist it is not doing this. Was this intentional? If so, is there plans to add a config to enable it?

**Comment by BanzaiMan** [comment]
Yes, this is intentional.

Precise images lack `yarn`, so it is installed on the fly; and it always installed the most recent release. Trusty images have it, and there is no install to perform.

**Comment by BanzaiMan** [comment]
For discussion on pre-installed `yarn` on Trusty, see https://github.com/travis-ci/travis-ci/issues/7566. (In particular, read https://github.com/travis-ci/travis-ci/issues/7566#issuecomment-296404685.)

I'm closing this as a duplicate.
