### ISSUE TITLE
Multiple commit PRs with only one [ci skip]

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#8204]
https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build mentions that

> Commits that have [ci skip] or [skip ci] anywhere in the commit messages are ignored by Travis CI.

However this doesnt explain what will happen if there are multiple commits in a PR, and only one commit contains a skip keyword.

**Comment by AllanWang** [comment]
If you have PR builds enabled, it will still build with each new commit. In this case, only those with `[ci skip]` or `[skip ci]` will be ignored. All others will still execute. And if you squash and merge your PR into another branch directly from github, you can also add [skip ci] to the commit to avoid building the merge.

**Comment by jayvdb** [comment]
That answers lots of other scenarios, but not the one I am interested in.

It is possible to *start* a pull request with multiple commits in the PR.  There is only one possible build triggered in this scenario, and it includes multiple commits.

Does this trigger skip the build if all of the commits in the PR use `[ci skip]`, or only when the "top" commit has `[ci skip]`?

IMO, if any do not have `[ci skip]`, the build should proceed.

**Comment by AllanWang** [comment]
@jayvdb it works the same way as if you have multiple commits in a new branch and you push them all to github. It builds based on the latest one. Choosing to skip a build for one commit usually means it's specific to that commit. I personally think there's more instances where a user would want a build to occur even if one of the previous commits can be skipped.

**Comment by AllanWang** [comment]
Oh and by the way, if you want to set it up so that it cancels if any skips were found in previous commits, it likely shouldn't be hard to do in the before script  portion. Just keep in mind that Travis defaults to cloning the latest  50 commits only, so if you have big projets you may need to change the number

**Comment by BanzaiMan** [comment]
If you would like to suggest docs improvement, you are welcome to use the button at the top left corner of the page.

In the mean time, I am closing this, since there is not much else to do.
