### ISSUE TITLE
Disable Gradle daemon in Gradle builds

### ISSUE THREAD

**Issue by jochenberger** [travis-ci/travis-ci#8205]
The default steps should pass `--no-daemon` to `gradle` or `./gradlew`.
See https://docs.gradle.org/current/userguide/gradle_daemon.html#when_should_i_not_use_the_gradle_daemon:
"It is recommend to disable the Daemon for Continuous Integration and build server environments."

**Comment by magneticflux-** [comment]
Definitely an improvement, but I believe this would be better suited as an issue in the [docs repository](https://github.com/travis-ci/docs-travis-ci-com).

**Comment by jochenberger** [comment]
Maybe it should also be added to the docs, but I'm talking about the default configuration.
I guess the best way to disable the daemon globally would be via `«GRADLE_USER_HOME»/gradle.properties`, which is the second option from https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:ways_to_disable_gradle_daemon.

**Comment by magneticflux-** [comment]
@jochenberger I think Travis CI prefers to restrict configuration like that to the `.travis.yml` file, as with the [Gradle caching snippet](https://docs.travis-ci.com/user/languages/android/#Caching). I'm not sure any other properties are set like that using the gradle.properties file without user intervention, or, more importantly, user knowledge of it happening.

**Comment by BanzaiMan** [comment]
Thanks for opening this issue. I think adding this flag makes sense.

I'm also curious to know if the same holds for Android builds that rely on Gradle.

**Comment by magneticflux-** [comment]
@BanzaiMan I develop with Android and I believe the advice holds for Android as well as other types of Gradle builds. I don't think it's possible for a build to require the Daemon enabled.

**Comment by BanzaiMan** [comment]
See also: https://github.com/travis-ci/docs-travis-ci-com/pull/1371
