### ISSUE TITLE
Testing in a Gentoo environment

### ISSUE THREAD

**Issue by TheChymera** [travis-ci/travis-ci#8209]
As far as I can tell, the virtual machine environments are [limted to Ubuntu and MacOS](https://docs.travis-ci.com/user/reference/precise/#Virtualization-environments).

If I wish to test my software in a Gentoo environment (benefiting from the power of the Gentoo package manager - Portage), what would be the best way of doing so? Would it be possible to just point to e.g. [a Gentoo OpenStack](http://gentoo.osuosl.org/experimental/amd64/openstack/) image and have the system start with that?

**Comment by Lyoness** [comment]
Hi @TheChymera ,  we do not officially support beyond Ubuntu and MacOS.  :frowning_face: 

Your best option might be to try our containerized builds running DinD - Docker in Docker, using https://github.com/gentoo/gentoo-docker-images.  The other option is to use a full vm `sudo: required`, using the [Docker service addon](https://docs.travis-ci.com/user/docker/), and then install the extras to run the openstack Gentoo image.  https://wiki.openstack.org/wiki/Docker#Installing_Docker_for_OpenStack

Hope this helps, good luck!
