### ISSUE TITLE
libR.so not found when using `language: r`

### ISSUE THREAD

**Issue by Non-Contradiction** [travis-ci/travis-ci#8212]
When I use `language:r` in .travis.yml, I couldn't find libR.so in R_HOME/lib. After `ls $(R RHOME)/lib` I can only see libRblas.so and libRlapack.so there. 

I need to have `libR.so` because  I am developing an R package which is interface of a Julia package, which needs access to libR. I know I could have `libR` by installing R other ways, but setting `language: r` is really convenient.

 Is it possible to have `libR.so` available while using `language: r`?

@craigcitro, @hadley, @jimhester

**Comment by Non-Contradiction** [comment]
Besides, RStudio also needs access to libR. Another package of mine [TestWithRStudio](https://github.com/Non-Contradiction/TestWithRStudio) tries to provide functionality for testing R Package with RStudio in travis CI. It is really helpful if the libR is available when setting language: r

**Comment by jimhester** [comment]
From [R-admin](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Configuration-options) it states

> Flag --enable-R-shlib causes the make process to build R as a dynamic (shared) library, typically called libR.so, and link the main R executable R.bin against that library. This can only be done if all the code (including system libraries) can be compiled into a dynamic library, and there may be a performance[57] penalty. So you probably only want this if you will be using an application which embeds R. Note that C code in packages installed on an R system linked with --enable-R-shlib is linked against the dynamic library and so such packages cannot be used from an R system built in the default way. Also, because packages are linked against R they are on some OSes also linked against the dynamic libraries R itself is linked against, and this can lead to symbol conflicts.

> [57]: We have measured 15–20% on ‘i686’ Linux and around 10% on ‘x86_64’ Linux.

So I don't think it is appropriate to impose a 10-20% performance penalty on all travis R packages for these use cases.

**Comment by Non-Contradiction** [comment]
Thank you very much for the explaining! Now I understand. 

Is it possible to have an option in language: r for this? like enable_shlib = TRUE?

**Comment by jimhester** [comment]
Unfortunately the R binaries are compiled separately, so enabling this would require us to re-build all existing binaries and add a process for compiling the shared library enabled binary separately. We unfortunately will not have time to implement and support this at this time.

**Comment by BanzaiMan** [comment]
Sounds like there is not much else to do here. Let me know if I'd missed anything.

**Comment by jimhester** [comment]
An update, due to other reasons it was necessary to include `libR.so`, so it is now available for all R versions.
