### ISSUE TITLE
Raw log not working

### ISSUE THREAD

**Issue by basdek** [travis-ci/travis-ci#8213]
When you press the "raw log" button,  nothing happens.

**Comment by iriberri** [comment]
We're taking a look at this and we will post updates here as soon as we know more or the issue is fixed.

Thanks for reporting and for your patience!

**Comment by iriberri** [comment]
We just deployed a fix and the Raw log button should be working as expected now, could you please confirm?

Thank you again!

**Comment by basdek** [comment]
It works again. Terrific!

On 7 Aug 2017 4:49 pm, "Carla" <notifications@github.com> wrote:

We just deployed a fix and the Raw log button should be working as expected
now, could you please confirm?

Thank you again!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/travis-ci/travis-ci/issues/8213#issuecomment-320685152>,
or mute the thread

**Comment by iriberri** [comment]
Thanks for the confirmation, @basdek! Closing, then :)

**Comment by mmoayyed** [comment]
I can also confirm that this is working. Thank you very much.
