### ISSUE TITLE
.NET Core in container-based infrastructure

### ISSUE THREAD

**Issue by philippgille** [travis-ci/travis-ci#8216]
I'm building a small open source .NET Core app on Travis CI, [hello-netcoreapp](https://github.com/philippgille/hello-netcoreapp). The actual code is unimportant, it's meant to be a template / boilerplate code for everything around it, for example build scripts and building on a CI/CD cloud service like Travis CI. So I added a Travis CI configuration according to [docs.travis-ci.com/user/languages/csharp/#.NET-Core](https://docs.travis-ci.com/user/languages/csharp/#.NET-Core) and everything works fine - nice!

But I also read about your container-based infrastructure on https://docs.travis-ci.com/user/migrating-from-legacy/. But even when adding `sudo: false` to the `.travis.yml` file, the container-based infrastructure doesn't seem to be used.

Does this not work when combined with `dist: trusty`? But that's said to be required according to [the above mentioned documentation that I followed](https://docs.travis-ci.com/user/languages/csharp/#.NET-Core).

Or does it just not work for .NET Core yet? That should be fairly easy, because there are official .NET Core Docker containers by Microsoft, see [hub.docker.com/r/microsoft/dotnet/](https://hub.docker.com/r/microsoft/dotnet/). So for example, when using `dotnet: 1.0.5` in the `.travis.yml` file, the Docker image with the tag `1.0.5-sdk` can be used.

There might be a problem with older dotnet versions.

Or maybe you don't use official Docker images at all, but create your own? Anyway, it would be great to be able to use the container-based infrastructure for .NET core projects.

Cc: @joshua-anderson @akoeplinger @nterry

**Comment by Joshua-Anderson** [comment]
@philippgille Are you sure the container based infrastructure isn't being used? For a travis ci user, the only noticeable difference is that they cannot call sudo. Instead of running your CI build inside of a full fledged VM, it runs it inside of a container. But since the container is built from the same script as the virtual machine, it won't appear any different.

**Comment by philippgille** [comment]
@Joshua-Anderson Hm, the [documentation](https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F) says there should be the line `This job is running on container-based infrastructure` in the build log, but it's not.

**Comment by Joshua-Anderson** [comment]
Do you have an example build with this issue?

**Comment by philippgille** [comment]
@Joshua-Anderson Yes: https://travis-ci.org/philippgille/hello-netcoreapp/builds/262001673

**Comment by Joshua-Anderson** [comment]
That build did run inside a container, but you're right that there isn't a message about it. I guess that was removed at some point. You would notice that the build would error out if you tried to use sudo and other side effects like that.

**Comment by philippgille** [comment]
@Joshua-Anderson I think the message would be helpful. Maybe it can be added again?

**Comment by BanzaiMan** [comment]
The message was removed to reduce noise in https://github.com/travis-ci/travis-build/pull/999.

Documentation needs fixing.

This issue can be closed, right?

**Comment by philippgille** [comment]
Thanks a lot for clearing this up!

Yes this issue can be closed, but please reference the issue regarding fixing the documentation (in case it exists) - it might confuse others as well.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/docs-travis-ci-com/issues/1368
