### ISSUE TITLE
PHP 5.3 install fails on Trusty

### ISSUE THREAD

**Issue by sampart** [travis-ci/travis-ci#8219]
I was trying to run a build against PHP 5.3 on Trusty, but the output I got was this:

```
$ phpenv global 5.3 2>/dev/null
5.3 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-5.3.tar.bz2
$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

$ phpenv global 5.3
rbenv: version `5.3' not installed

The command "phpenv global 5.3" failed and exited with 1 during .
Your build has been stopped.
```

(From [this job](https://travis-ci.org/whiteoctober/Pagerfanta/jobs/261884713); I tried a restart to no avail.)

If I visit https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-5.3.tar.bz2 directly in a browser, I get:

```
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>binaries/ubuntu/14.04/x86_64/php-5.3.tar.bz2</Key>
    <RequestId>801217F1CCCA3E69</RequestId>
    <HostId>
        tIzGGTTzQn94mB44Mk0mN5bSgmp630EdLxJF8jMG/LNIZWIYJLu1Afl2kp0TH4otqevHGcIkvvQ=
    </HostId>
</Error>
```
For now I'm going to keep my 5.3 build on Precise, but it would be nice to get this fixed.

(This issue is not the same as https://github.com/travis-ci/travis-ci/issues/8072 - that's about holding 5.2 or 5.3 on Precise but needing sudo.)

**Comment by BanzaiMan** [comment]
Sorry, but we cannot support PHP 5.2 and 5.3 on Trusty. See #2963 for details.

**Comment by sampart** [comment]
Thanks for clarifying, @BanzaiMan.  It would be great if you could change your setup to give a more helpful message like "PHP 5.3 is not supported on Ubuntu Trusty. Please consider using Precise with `dist: precise`", like you do for [HHVM on Precise](https://travis-ci.org/whiteoctober/WhiteOctoberPagerfantaBundle/jobs/235129249).  At present, the output makes this look like a bug rather than a deliberate decision.  But up to you, of course.

**Comment by samayo** [comment]
I agree with sampart but what is trusty?  I only have this configuration: 
```yml
language: php
before_script:
  - composer install --dev --no-interaction
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
```
I see no 'trusty' and whatnot, I am only telling travis to run the tests on php5.3 upto 7.1. 

Why come up with nonsense to make everything else harder.

**Comment by sampart** [comment]
@samayo Trusty is the [codename for Ubuntu 14.04](https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_14.04_LTS_.28Trusty_Tahr.29).  That's the [new default](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming) version of Ubuntu Operating System that Travis builds use.
