### ISSUE TITLE
Logging is a bit Misleading when using Script

### ISSUE THREAD

**Issue by joesan** [travis-ci/travis-ci#8226]
I have the following Travis CI yml file snippet:

```
script:
  - if [ $TRAVIS_BRANCH == "master" ]; then
      sbt clean coverage test coverageReport docker:publishLocal;
    fi
  - if [ $TRAVIS_BRANCH == "/^develop-.*$/" ]; then
      sbt clean coverage test coverageReport;
    fi
```

It sort of works, but I could not understand the logs that it produces. It is sort of misleading. Here is the log from the build server:

```
[success] Total time: 22 s, completed Aug 8, 2017 5:29:28 PM

The command "if [ $TRAVIS_BRANCH == "master" ]; then sbt clean coverage test coverageReport docker:publishLocal; fi" exited with 0.
0.00s

$ if [ $TRAVIS_BRANCH == "/^develop-.*$/" ]; then sbt clean coverage test coverageReport; fi

The command "if [ $TRAVIS_BRANCH == "/^develop-.*$/" ]; then sbt clean coverage test coverageReport; fi" exited with 0.
```

Would it be possible to show the log message that it skipped instead of it saying it exited with code 0?

**Comment by BanzaiMan** [comment]
Hello. Could you elaborate on what you find misleading about the output?

Your script is basically `if [ CONDITION ]; then X; fi`; if `CONDITION` is not met nothing happens.

If you want something written in that case, you'd need `else`:

`if [ CONDITION ]; then X; else Y; fi`

It is working *as you specified*.
