### ISSUE TITLE
Travis configures Go 1.9rc2 with incorrect GOROOT

### ISSUE THREAD

**Issue by jacobsa** [travis-ci/travis-ci#8229]
When running with Go 1.9rc2 (the current release candidate), Travis's setup code somehow results in a Go installation where `runtime.GOROOT` returns a directory that doesn't exist (`/usr/local/go`).

[Here](https://github.com/jacobsa/travis_gopath_bug/tree/d6e6133233ef742fe1f8f5d0658bb022d54eb319) is a repository that demonstrates it. The repo has a simple test that ensures `os.Stat(runtime.GOROOT())` doesn't fail. [This](https://travis-ci.org/jacobsa/travis_gopath_bug/builds/262484215) build shows that the test passes with Go 1.8.3, but fails with 1.9rc2.

This is a problem for any test that attempts to build Go code by invoking the `go` command. The latter always fails with `cannot find GOROOT directory: /usr/local/go`, causing the test to fail on Travis, but not locally.

This may or may not be a bug in `gimme`.

**Comment by Lyoness** [comment]
@jacobsa this is unfortunately a bug with go 1.9 

https://github.com/travis-ci/travis-ci/issues/8177#issuecomment-320376242

workaround for `1.9

```
before_install:
  - export GOROOT=$(go env GOROOT)
```

**Comment by kevinburke** [comment]
Looks like this has been fixed in Go 1.9 proper (or gimme)

**Comment by myitcv** [comment]
@kevinburke my experience with Go 1.9 (via gimme) is that this still requires the workaround. Maybe relevant is that I'm using `go/types` in one of my programs... but I've not done any serious investigation.

**Comment by myitcv** [comment]
Now looks fixed for me following https://github.com/travis-ci/travis-ci/issues/8177#issuecomment-325774347

Thanks

**Comment by BanzaiMan** [comment]
Great. I'm closing this now, but if you see problems again, do let us know.
