### ISSUE TITLE
Travis Build Steps now Resolving global env variables

### ISSUE THREAD

**Issue by joesan** [travis-ci/travis-ci#8231]
I have a set of global env variables in my .travis.ci.yml file:

```
env:
 global:
   - APPLICATION_NAME    = joesan/inland24/plant-simulator
   - DOCKER_REGISTRY_URL = repo.treescale.com
   - IMAGE_VERSION_DEV   = 1.0-SNAPSHOT
```

I have the following as jobs:

```
jobs:
  include:
    #- stage: test
      # script: sbt clean coverage test coverageReport
    - stage: build docker image
      script:
        - if [ $TRAVIS_BRANCH == "master" ]; then
            echo $APPLICATION_NAME
            sbt docker:publishLocal;
            docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL; # seems here it can resolve the registry url as it can successfully login
            docker images;
            docker push $DOCKER_REGISTRY_URL/$APPLICATION_NAME:$IMAGE_VERSION_DEV;
          fi
```

The build now fails with the following reason:

`Error parsing reference: "/:" is not a valid repository/tag: invalid reference format`

So looks like it only could resolve /: and the rest is not substituted. I can confirm this as I tried to remove the $DOCKER_REGISTRY_URL/ from my docker push command and then it failed with the same reason:

`Error parsing reference: ":" is not a valid repository/tag: invalid reference format`

**Comment by joesan** [comment]
Strangely, I moved the docker login and docker push commands out of the build stage and moved that into the after_script part and it just worked! Is this how is it supposed to be?

**Comment by BanzaiMan** [comment]
Environment variable assignments are passed on to `bash`. As such,

```yaml
env:
 global:
   - APPLICATION_NAME    = joesan/inland24/plant-simulator
   - DOCKER_REGISTRY_URL = repo.treescale.com
   - IMAGE_VERSION_DEV   = 1.0-SNAPSHOT
```

results in `$APPLICATION_NAME`, `$DOCKER_REGISTRY_URL`, `$IMAGE_VERSION_DEV` being empty, since there is a space after the identifiers.

Try removing excess spaces around `=`.
