### ISSUE TITLE
trusty randomly failing when trying to install npm modules

### ISSUE THREAD

**Issue by pocesar** [travis-ci/travis-ci#8234]
Test started failing to install, so it never even start the test itself. Last Yesterday it was working properly

![image](https://user-images.githubusercontent.com/461084/29173341-5a39f772-7db9-11e7-8b84-4ff66ac313b5.png)

https://travis-ci.org/pocesar/react-native-stager#L1486

**Comment by BanzaiMan** [comment]
Looks like an issue with dependency resolution (or an issue with indices on npmjs.org): https://travis-ci.org/pocesar/react-native-stager/builds/264936964#L1977

Is this still a problem for you?

**Comment by pocesar** [comment]
nope, not a problem anymore, I'm doing a npm command followed by a `|| true` because NPM was returning a code 1, even though the installation did complete!
