### ISSUE TITLE
There is no way for the build to know it's within a build stage

### ISSUE THREAD

**Issue by honzajavorek** [travis-ci/travis-ci#8239]
There are [environment variables](https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables) allowing the build to introspect the CI job. However, there's no environment variable for the build to detect it's within a build stage. This makes issues like https://github.com/semantic-release/semantic-release/issues/390 impossible to fix.

I propose adding `TRAVIS_BUILD_STAGE_NAME` variable.

**Comment by pbgnz** [comment]
Is there a known work around to get the build stage name ?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
The `TRAVIS_BUILD_STAGE_NAME` env variable now exists! Enjoy! :)
