### ISSUE TITLE
What is the aime of the button Build branch updates ?

### ISSUE THREAD

**Issue by MatthD** [travis-ci/travis-ci#8240]
Hi everyOne,

I would like to know what it the aime of the button "Build branch updates" In settings of a project,
in fact when I disable it.. It will never build anything.. even on master ^^

How to disable the build one all branche but master ?

Thanks

**Comment by BanzaiMan** [comment]
Builds are initiated by pushes to a branch on a repository, or a PR (either from the repository itself, or from a fork). "Build branch updates" determines whether or not the first event triggers a build.

To restrict which branches are built, see https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches.
