### ISSUE TITLE
Firefox 55 disconnect causing build failures

### ISSUE THREAD

**Issue by mjneil** [travis-ci/travis-ci#8242]
We use Karma and QUnit to run our tests and recent travis builds (https://travis-ci.org/videojs/videojs-contrib-media-sources/builds/263297378) are failing because of `Firefox 55.0.0 (Linux 0.0.0): Executed 15 of 89 DISCONNECTED`. The `x of 89` is different every time I restart the build. I attempted to restart one of our previous builds for our most recent tagged release that had passed 25 days ago and it too is failing in the same way now (https://travis-ci.org/videojs/videojs-contrib-media-sources/builds/254606848). You can see here the build for master branch that was done 25 days ago had passed (https://travis-ci.org/videojs/videojs-contrib-media-sources/builds/254606780). I suspect it may be related to the release of firefox 55 a few days ago. I've updated to FF 55 locally and all tests continue to pass

**Comment by mjneil** [comment]
update: Locking firefox to v54 allows tests to pass again https://travis-ci.org/videojs/videojs-contrib-media-sources/builds/263559355

**Comment by BanzaiMan** [comment]
The message is:

```
11 08 2017 17:47:53.495:WARN [Firefox 55.0.0 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
```

Is this a new behavior on Firefox? 10 seconds does seem a long time for the request to not receive any response. Does increasing the timeout make a difference?

The variance in `x of 89` is probably expected, assuming that your tests are configured to be executed in random order (they should be).

**Comment by mjneil** [comment]
I tried increasing the timeout to 2 minutes and still [fails](https://travis-ci.org/videojs/videojs-contrib-media-sources/builds/264421966). The 10 seconds seems to be coming from this [karma config option browserNoActivityTimeout](http://karma-runner.github.io/1.0/config/configuration-file.html)

**Comment by bnenning-empirical** [comment]
We are having the same problem. It's especially annoying because we can pin Firefox to version 54 in .travis.yml, but it auto-updates itself between tests. We've tried many things to stop it from updating, including launching Firefox via xvfb-run to create the profile directory, killing it, and inserting `user_pref("app.update.enabled", false);` in the created profile's prefs.js, but nothing works reliably and it usually ends up updating to 55 and failing with the DISCONNECTED error.

As in the original report, Firefox 55 works fine when testing locally.

**Comment by mjneil** [comment]
@BanzaiMan do you know if anyone has had a chance to look into this yet? This is starting to happen on more of our projects, and not even locking to ff54 is working anymore. latest or locking to a version still causes timeouts.

https://travis-ci.org/videojs/videojs-contrib-eme/builds/277051104
https://travis-ci.org/videojs/videojs-contrib-media-sources/builds/277931737

**Comment by gbiryukov** [comment]
updating karma from `0.13.9` to `2.0.0` and node from `0.12` to `9.4.0` solved this issue
