### ISSUE TITLE
Hanging github login from command line

### ISSUE THREAD

**Issue by HurricanePete** [travis-ci/travis-ci#8250]
Whenever I try to use `travis login` from the command line I am prompted to login normally - however, when I'm entering my credentials the password field will display (despite the prompt indicating otherwise). Upon inputting my credentials and hitting enter, I am left hanging in the command line indefinitely

```
$ travis login
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: MyUsername
Password for MyUsername: MyPassword
```

Any idea why I can't login?

**Comment by BanzaiMan** [comment]
Could you try moving `~/.travis` somewhere else (or delete it altogether) and try the command again?

**Comment by HurricanePete** [comment]
I have tried deleting the `.travis` directory as well as moving it to a sub-folder on my desktop. I am still left with a hanging login when I try `Travis Login` with my credentials. I am met with the same response when I try `Travis Login` from a different computer as well (although with the same dev environment set up).

**Comment by imhighyat** [comment]
Hi guys, I was having the same issues when I use GitBash. What worked for me was running the command prompt and running the ```travis login``` from there. Worked like a charm.

**Comment by lemazza** [comment]
Hey, I'm having exactly the same problems.  I've used ruby 2.2.6 and 2.3.3 on Windows 10.  GitBash didn't work, but command prompt did.

**Comment by jamesppowell** [comment]
Late to the party but confirming that this behavior is still occurring as of April 2018. :+1:

**Comment by spoofBlue** [comment]
Confirmed, this behavior still exists.

**Comment by gamb** [comment]
Honestly cannot find anything to tell me where I get my "--github-token" from?

**Comment by armando2002** [comment]
This behavior still exists in Git Bash. Any updates?

**Comment by kimura-dev1297** [comment]
This issue is still occurring.

**Comment by jjasondavis** [comment]
This is still an issue I experienced it today (12/18/18) on Windows GitBash

**Comment by glexey** [comment]
Try this:
    winpty ruby `which travis` login

**Comment by ken-elsheezy** [comment]
Thanks @glexey ... you saved my day

**Comment by bhansa** [comment]
This issue still exists, tried with cmd, bash, powershell.
Adding travis report below:

```$ travis report --pro
System
Ruby:                     Ruby 2.4.5-p335
Operating System:         Windows
RubyGems:                 RubyGems 3.1.4

CLI
Version:                  1.10.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2020-10-03 11:48:23 +0530

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
com:                      https://api.travis-ci.com/ (default, current)
org:                      https://api.travis-ci.org/ ()

Last Exception
An error occurred running `travis login --pro`:
    RuntimeError: Unknown error
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:212:in `rescue in basic_auth'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:208:in `basic_auth'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:216:in `login'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:81:in `possible_tokens'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:50:in `each_token'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:37:in `with_token'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/cli/login.rb:31:in `login'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/cli/login.rb:50:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/cli/command.rb:200:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/cli.rb:64:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
        from C:/Ruby24-x64/bin/travis:23:in `load'
        from C:/Ruby24-x64/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by Excalibur212** [comment]
Over 3.2 years later since the OP in 2017, now 2021 and still getting exact same error as shown above by @bhansa. LOL

SOLVED: I created a **personal access token** via GitHub under my **Profile - Settings - Developer settings** menu (to answer your question @gamb)... This is from Windows 10 command prompt with latest Travis CI installed (1.10.0):

> travis login --org --github-token [personal access token copied from github]"
Successfully logged in as Excalibur212!

I was then able to proceed with

> travis encrypt-file server.key server.key.enc --add

I'm guessing maybe it has something to do with this.... (TL;DR)

[https://github.com/travis-ci/travis.rb/issues/793]**
Issue #793: "https://api.github.com/authorizations removed #793"**
