### ISSUE TITLE
Travis fail to require package when package name starts with capital letter.

### ISSUE THREAD

**Issue by mabdullah353** [travis-ci/travis-ci#8252]
I am using Sequelize package and i am importing it like this

```js
const Sequelize = require('Sequelize')
```

Now when i run npm tests locally it works without any error:
```bash
$ npm test

> koajsapp@0.0.0 test /Users/XAM/liimex/koajsapp
> mocha --require co-mocha config/tests.js './server/**/*.spec.js'
[TRUNCATED]
  2 passing (119ms)
```

As i submitted this code to github the travis pipelines failed to run it. And throws the following error

```bash
$ npm test
> koajsapp@0.0.0 test /home/travis/build/mabdullah353/koajsapp
> mocha --require co-mocha config/tests.js './server/**/*.spec.js'
module.js:472
    throw err;
    ^
Error: Cannot find module 'Sequelize'
    at Function.Module._resolveFilename (module.js:470:15)
```
[Bulid#19](https://travis-ci.org/mabdullah353/koajsapp/builds/264423057)

This error get resolved when i updated my original code like following: 
```js
const Sequelize = require('sequelize')
```

Now the above error is resolved in this [Build#20](https://travis-ci.org/mabdullah353/koajsapp/builds/264472617)

It seems like Travis won't handle capital letter in `require argument` while running locally npm can handle it.

EXTRA INFO
=====

When travis was complaining  about `Cannot find module 'Sequelize'` I ran the travis pipelines on my local machine from the build to actually debug what is going wrong, so on running the following commands on my local machine, it run without any error.

```
git clone --depth=50 --branch=feat-database https://github.com/mabdullah353/koajsapp.git mabdullah353/koajsapp
cd mabdullah353/koajsapp
npm install
npm test
```

**Comment by BanzaiMan** [comment]
Note that the correct name of the package is `sequelize` (https://www.npmjs.com/package/sequelize).

Since your local machine is a Mac (based on `/Users/…` path), you are most likely on a case-insensitive file system. When you tell your software to look for `Sequelize`, it will find `sequelize`.

Your build is running on Linux with a case-sensitive file system, so it can't find `Sequelize`.
