### ISSUE TITLE
Prebuilt ruby-head binary for Ubuntu 14.04 is outdated (built on May 25th)

### ISSUE THREAD

**Issue by arkadiyt** [travis-ci/travis-ci#8253]
Opening issue as per https://twitter.com/travisci/status/897176013091766272

Can the precompiled ruby-head for Ubuntu 14.04 be bumped to a more recent version?

Thanks,

**Comment by BanzaiMan** [comment]
The S3 upload step is stalling somehow. https://travis-ci.org/travis-ci/travis-rubies/jobs/263547947#L746

**Comment by arkadiyt** [comment]
@BanzaiMan on this commit:
https://github.com/travis-ci/travis-rubies/commit/b861af56062776392f4e69e1b3d633733b8d23e6

A shasum file for ruby is generated with:
```
openssl dgst -sha512 -out $f.sha512.txt
```
But there is no input file specified so it reads from stdin instead, and no stdin input is given so it stalls until the build fails. I believe this command should be:
```
openssl dgst -sha512 -out $f.sha512.txt $f
```

**Comment by arkadiyt** [comment]
Same issue noted here, might have fallen through the cracks: https://github.com/travis-ci/travis-rubies/issues/35

**Comment by BanzaiMan** [comment]
Ah. Thanks for pointing that out. I'll investigate.

**Comment by BanzaiMan** [comment]
This is fixed by https://github.com/travis-ci/travis-rubies/commit/b4bb1e16ef36094dfcbc15190258119cb7ebd290.

See http://rubies.travis-ci.org/ubuntu/12.04/x86_64/ruby-head http://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-head

**Comment by arkadiyt** [comment]
Thanks!
