### ISSUE TITLE
Issue with R Projects on OSX

### ISSUE THREAD

**Issue by tvatter** [travis-ci/travis-ci#8263]
Dear all,

I notice that builds on OSX for R packages are consistently erroring out today during the "Installing R" part of the build.

See for instance:

https://travis-ci.org/tvatter/gamCopula/jobs/265721378

It always seems to fail with

```
curl -fLo \"/tmp/#{mactex}\" --retry 3 http://mirror.ctan.org/systems/mac/mactex/#{mactex}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   349  100   349    0     0    455      0 --:--:-- --:--:-- --:--:--   455
Warning: Failed to create the file "/tmp/#{mactex}": No such file or directory
curl: (23) Failed writing body (0 != 2296)
```

Any idea what is going on?

Note that `curl -fLo \"/tmp/#{mactex}\" --retry 3 http://mirror.ctan.org/systems/mac/mactex/#{mactex}` generates the same error on my local machine.

@craigcitro, @hadley, and @jimhester

**Comment by jimhester** [comment]
Looks like the quoting is not correct in a recent change (https://github.com/travis-ci/travis-build/pull/1132)
