### ISSUE TITLE
Failing of the build due to TimeOut Error

### ISSUE THREAD

**Issue by meets2tarun** [travis-ci/travis-ci#8266]
The build keeps on failing while deployment and it not getting deployment even after several restarts.
https://travis-ci.org/meets2tarun/meilix/builds/265418039?utm_source=github_status&utm_medium=notification

**Comment by BanzaiMan** [comment]
My initial guess is that the build artifacts you are uploading (about 1.5 GB) is just too big to be pushed in the allotted time.

**Comment by meets2tarun** [comment]
Do I need to shorten the build log or shorten the build time or reduce the size of the artifacts?
The last two options were there in the old build also.

**Comment by BanzaiMan** [comment]
Reduce the artifacts size.

**Comment by meets2tarun** [comment]
Thanks that worked
