### ISSUE TITLE
osx builds fail (cpp)

### ISSUE THREAD

**Issue by dvolgyes** [travis-ci/travis-ci#8268]
Suddenly, cpp builds on osx started to fail.
I changed completely unrelated parts.
My toolset compain about the lack of doxygen, 
missing c++11 capability, etc. All have started around 11
hours ago. You can see the pattern here:
https://travis-ci.org/UCL/STIR/pull_requests
(Linux builds work like charm, only osx is affected, both clang and gcc.)
Any idea, suggestion?

**Comment by BanzaiMan** [comment]
*Why* does your build complain about the absence of Doxygen?

**Comment by dvolgyes** [comment]
After a lot of log-reading, I found the issue:
A 3rd party library, which was installed with brew, has changed
which caused a strange chain-reaction, and cmake gave a wrong error message.
I am sorry for the confusion.

So I think its not a bug on Travis side, and we can close this issue.
