### ISSUE TITLE
Update PHP 7.2 to beta

### ISSUE THREAD

**Issue by Jean85** [travis-ci/travis-ci#8269]
PHP 7.2 images are outdated, since they are using a dev version. We now have beta3 available, is it possible to update them? I have a build that is [failing](https://travis-ci.org/getsentry/sentry-symfony/jobs/265881667) because of this, for PR getsentry/sentry-symfony#71.

**Comment by BanzaiMan** [comment]
https://github.com/php-build/php-build/tree/master/share/php-build/definitions needs a beta3 definition before we can proceed.

**Comment by GrahamCampbell** [comment]
Done. :)

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/php-src-builder/builds/266139042

**Comment by BanzaiMan** [comment]
It's available now.
