### ISSUE TITLE
Trusty container: Intermittent failures after https://github.com/travis-ci/travis-build/pull/1140 merged

### ISSUE THREAD

**Issue by ssoloff** [travis-ci/travis-ci#8272]
I've been using the Trusty container for my Gradle-based project without any issues for a couple of months.  However, after https://github.com/travis-ci/travis-build/pull/1140 was merged a few days ago, I started to observe intermittent failures due to the "Gradle Test Executor 1" process being killed by the OOM Killer.  When I switched the build back to using the daemon via passing the `--daemon` flag to `./gradlew` in my Travis configuration, I no longer observed the build failure.

I modified my build to periodically take memory usage snapshots via `ps`.  When running the non-daemon build, I observed the following maximum RSS usage for the various Gradle processes:

Gradle process | Max RSS (MiB)
:-- | :--
Wrapper | 2,661
Test Executor 1 | 475
Test Executor 2 | _no data; build doesn't make it this far_

Similarly, for the daemon build:

Gradle process | Max RSS (MiB)
:-- | :--
Wrapper | 353
Daemon | 916
Test Executor 1 | 540
Test Executor 2 | 596

As you can see, the wrapper process in the non-daemon build has an excessively high RSS for a container that only has 4 GiB available.  However, the daemon process in the daemon build appears to be well behaved, never exceeding 1 GiB RSS.

Upon further investigation, I observed that, during the daemon build, the Gradle wrapper process launches the Gradle daemon process with the `-Xmx1024m` command line argument, which explains why the daemon process RSS never exceeds 1 GiB.  However, no such argument is specified when running the Gradle wrapper process (in both the daemon and non-daemon builds).  Therefore, the wrapper process will use the default maximum heap size, which is 1/4 of the available **host** memory, as opposed to the memory available to the **container** (see this [post](https://developers.redhat.com/blog/2017/03/14/java-inside-docker/) for details).  Running `java -XX:+PrintFlagsFinal -version` on a Trusty container yields a `MaxHeapSize` of approximately **14.7 GiB**.  Thus, the Gradle wrapper process has a maximum heap size that exceeds the available memory of the container, which explains why the RSS of the wrapper process in the non-daemon build continues to grow without bound.

I can address this issue by explicitly specifying `-Xmx1024m` when starting my Gradle wrapper process via a number of mechanisms (e.g. `JAVA_OPTS`, `DEFAULT_JVM_OPTS` in `gradlew`, etc.).  However, I'm wondering if something should be done on the Travis side given that the JVM calculates the default maximum heap size based on the host's memory, and will produce a value that is probably not what most users expect.  I don't know if this should be done explicitly via an environment variable or the `gradle.properties` file, or if it should simply be documented in the [Java/Gradle](https://docs.travis-ci.com/user/languages/java/#Projects-Using-Gradle) project documentation.

**Comment by BanzaiMan** [comment]
We can add something like

```
org.gradle.jvmargs=-Xmx1024m
```

to `~/.gradle/gradle.properties`, but according to https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties it will override the project's properties file. Is that desirable?

**Comment by BanzaiMan** [comment]
The next-generation Trusty image attempts to limit Java memory consumption (up to 2 GB).

Could you test your repo with the following and let us know if it yields better results?

```yaml
dist: trusty
group: edge
⋮ # rest
```

Thanks.

**Comment by ssoloff** [comment]
@BanzaiMan 

> We can add something like `org.gradle.jvmargs=-Xmx1024m`

Note that, per the reference you cited, this setting only affects the _daemon_ process.  Whereas it is the _wrapper_ process that is exhausting available memory in my use case.

> Could you test your repo with the following and let us know if it yields better results?

Sure.  I'll test using that image as soon as I can.

**Comment by ssoloff** [comment]
@BanzaiMan Using the `edge` group, I was able to get the non-daemon build to fail on the second try.  You can view the build log [here](https://travis-ci.org/ssoloff/triplea-game-triplea/builds/270512090).

The RSS of the wrapper process immediately before the build failed was 2,642 MiB.  Since you said the `edge` Trusty container is supposed to limit Java memory consumption to 2 GiB, I'm wondering if I'm missing something in my Travis configuration?  I did confirm the build log contains:

```
Build group: edge
Build dist: trusty
```

**Comment by BanzaiMan** [comment]
@ssoloff The image should have the undocumented `_JAVA_OPTIONS` set to `-Xmx2048m`, but maybe it is not effective?

**Comment by ssoloff** [comment]
@BanzaiMan According to [this SO answer](https://stackoverflow.com/a/13863175/3900879), the Oracle JVM will echo options set via `_JAVA_OPTIONS` to stderr.  I verified this on my local machine:

```
$ _JAVA_OPTIONS=-Xmx1G ./gradlew clean
Picked up _JAVA_OPTIONS: -Xmx1G

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

I searched the previously referenced Travis build log and could not find a similar message.

**Comment by BanzaiMan** [comment]
@ssoloff Thanks for testing. I'll research what's going on here.

**Comment by ssoloff** [comment]
@BanzaiMan FYI, I just ran `printenv` at the start of my build (in `before_install`), and I do not see `_JAVA_OPTIONS`.  Maybe it's not being exported?

**Comment by ssoloff** [comment]
If [this commit](https://github.com/travis-ci/travis-cookbooks/commit/91f5b7b38c43a2965f55f634fd6c3c91712c8f1d#diff-d35fb93ee4e5a49574cca081c37adebb) is where `_JAVA_OPTIONS` was added, then it appears that feature might not be included in the Trusty `edge` image I'm using.  Per the build log, my image timestamp is

```
Build image provisioning date and time
Fri Jul  7 18:52:25 UTC 2017
```

**Comment by ssoloff** [comment]
@BanzaiMan I tested my build after removing the workaround I had previously applied.  20 of 20 builds ran without any failures.  So it looks like the `_JAVA_OPTIONS` environment variable in the latest Trusty `stable` image successfully resolves this issue.  Thanks for your help!
