### ISSUE TITLE
Rust/Cargo projects are built using Ruby/rake by default

### ISSUE THREAD

**Issue by pornel** [travis-ci/travis-ci#8275]
For projects without travis.yml, Ruby/rake is chosen by default, e.g.: https://travis-ci.org/pornel/imgref/builds/266335284

This could be improved. Almost all Rust projects use Cargo, which can be reliably detected by presence of `Cargo.toml` file in the root of the repository. And for Cargo this is sufficient for testing:

```sh
cargo build --verbose
cargo test --verbose
```

Could you detect `Cargo.toml` in Rust projects?

**Comment by BanzaiMan** [comment]
The commit that triggered the build was https://github.com/pornel/imgref/tree/ee754c58ce186b95b3668d779e15267715e5ad5f, which does not have `.travis.yml` in the repository root, so we assumed a Ruby repo. If you want to run this as a Rust one, please add it. https://docs.travis-ci.com/user/languages/rust

**Comment by BanzaiMan** [comment]
We do not detect the repository's structure, since it would not be known until the code is checked out, so `.travis.yml` is necessary.
