### ISSUE TITLE
"travis setup releases" not working

### ISSUE THREAD

**Issue by alankm** [travis-ci/travis-ci#8277]
I'm trying to make travis push the files it has built to the github releases for the project. 

I've followed each of the approaches outlined in the documentation, with the same failed result every time. (https://docs.travis-ci.com/user/deployment/releases/). This includes simply running "travis setup releases", manually adding and encrypting the OAuth token to the .travis.yml file, and attempting to use basic authentication with my github username and (encrypted) password.

My build log fails with a 401 Octokit:Unauthorized error, which I have found in several closed issues, but none of the solutions within those closed issues has helped me. Here is my build log:
https://travis-ci.com/sisatech/vcli/builds/52742604

If it helps to diagnose the issue, I've had all sorts of problems with travis whenever encrypted information is involved. I think there's something I must be not doing to get that working properly.

**Comment by BanzaiMan** [comment]
It is very difficult to troubleshoot with this information alone, but my initial guess is that either: the encryption went wrong for whatever reason, or the token is correct but doesn't have the correct scope.

I can try diagnosing from here, but it might be best to send email to support@travis-ci.com, since some information might be sensitive.

**Comment by BanzaiMan** [comment]
I see that the error is coming when we try to log in, so the scope is not involved (yet).

**Comment by alankm** [comment]
I'll try the support email and see what comes of it. 
Is there any other (non-sensitive) information I could provide that would be helpful?

**Comment by alankm** [comment]
I've solved my issue. I'm not going to claim to know precisely what the cause was, but it seems to me that it's a bug either with the travis command-line client or possibly with the online travis service.

My repository "sisatech/vcli" was originally a private repository. We used it with travis for a long time (though not doing github releases) with no problems whilst it was private. It was building the repository on travis-ci.com, as private repositories should. A few months ago we made the repository public, but travis continued to build on travis-ci.com NOT on travis-ci.org (this might be the bug?). It didn't occur to me that this was an issue.

Perhaps the command-line client noticed that the github repository was public when I ran "travis setup releases" and assumed that it would be building on "travis-ci.org", but it wasn't working. The problem was solved by migrating the build process to "travis-ci.org", rather than "travis-ci.com".

I hope that gives you enough to work with.

**Comment by BanzaiMan** [comment]
There are a few extra steps to take when repository's visibility changes. These are outlined in https://docs.travis-ci.com/user/travis-pro#How-can-I-make-a-private-repository-public%3F.

At any rate, we are happy to hear that you were able to resolve the issue. Closing this now.
