### ISSUE TITLE
Cannot merge a PR because a check didn't trigger after push of a clean merge

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#8279]
Cannot merge a PR because a check didn't trigger after pus of a clean merge.

![eko point feeding 102 by deilan pull request 21 eko point feeding client](https://user-images.githubusercontent.com/4777512/29521057-86309a58-868c-11e7-9f1e-c1a42d5105ed.png)

**Comment by Deilan** [comment]
@BanzaiMan A build hasn't been created, hence I have no logs.

**Comment by BanzaiMan** [comment]
Is this still a problem?

**Comment by Deilan** [comment]
Nope, it's fine now. Closing.
