### ISSUE TITLE
Deploy wasn't triggered

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#8281]
Deploy conditions:
```
on:
    branch: master
    tags: false
```
Result:
```
Skipping a deployment with the releases provider because this is not a tagged commit
```
Started to occur today.

Previously everything worked just fine. Haven't changed anything for almost a month.

**Comment by toonsevrin** [comment]
I'm noticing the same behavior with our builds. Tagless builds no longer work.

**Comment by BanzaiMan** [comment]
That it was deploying before was a bug. See #8185. We fixed it. You need a tag to deploy with GitHub Releases, as documented.

**Comment by BanzaiMan** [comment]
> Please note that deploying GitHub Releases works only for tags, not for branches.

https://docs.travis-ci.com/user/deployment/releases

**Comment by toonsevrin** [comment]
Improvement request: allow the anonymous releases, I really liked them for some of our stuff

**Comment by Deilan** [comment]
@BanzaiMan We were creating a tag on every commit to master as a part of `before_deploy`, which is quite a common solution. You have broken CD processes based on it. Without any warnings and notices. We did not expect such a lack of responsibility. And we pay a decent amount of money for it.

**Comment by BanzaiMan** [comment]
@toonsevrin @Deilan Sorry for the troubles. When you did work with `before_deploy`, did you see the issue described in #8185?

**Comment by toonsevrin** [comment]
@BanzaiMan what's the point of not changing the surrounding documentation and allowing this?

**Comment by BanzaiMan** [comment]
@toonsevrin Could you elaborate on what do you mean by "surrounding documentation"? https://docs.travis-ci.com/user/deployment/releases clearly states that `on.tags: true` is required.

**Comment by Deilan** [comment]
@BanzaiMan We implemented aforementioned CD processes months ago. If there was no tag associated with a commit, against which a build is started, an anonymous tag was created. If there was a tag, such as created as a part of build, a release is deployed against this tag. And everything worked just fine.

**Comment by toonsevrin** [comment]
@BanzaiMan Exactly, could this documentation be removed and can the 'fix' be reverted (allowing for _tags:false_? Our team would appreciate this (the services in question will have to moved to gitlab otherwise 😢)

**Comment by BanzaiMan** [comment]
@Deilan @toonsevrin I would like to understand how this bug (in the sense that it was *clearly* the behavior against the documentation) was taken advantage of. If this is a desirable behavior, as you two indicate, we are more than happy to accommodate it.

Without the tags, you would've seen tags with `untagged-HEX` (which is what #8185 reported, and we fixed with https://github.com/travis-ci/travis-build/pull/1145; this was the most logical way to do, given the documentation). Do you not see these?

Or, are you saying that you are specifically tagging with `git tag` in `before_deploy`? And it worked the way you wanted?

**Comment by Deilan** [comment]
@BanzaiMan Yes, we push a git tag right in `before_deploy` in `master` branch on every single commit, it worked and this is a behaviour we wanted.

**Comment by toonsevrin** [comment]
We also like CD without explicitly defining tags on the master branch. The perfect behavior would be to accommodate for all use cases (eg. have a flag to enable tagless deployments)

**Comment by Deilan** [comment]
@BanzaiMan If there's another way to deploy on every single commit in `master` branch, then please tell us how to do it.

**Comment by BanzaiMan** [comment]
OK. We will revert https://github.com/travis-ci/travis-build/pull/1145 for now.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/docs-travis-ci-com/pull/1383 is a proposed documentation change. Your feedback is appreciated.

**Comment by toonsevrin** [comment]
Awesome! please keep us up to date if anything changes
