### ISSUE TITLE
When getting the status image of a repo with only one branch which is not master, the link will be given with "master" but not with the only branch.

### ISSUE THREAD

**Issue by KuangLei** [travis-ci/travis-ci#8291]
For example, I have a repository. there are **only one** branch in it, `GUI_dev`, not `master`.  
Then I add it to Travis CI, click the Status Image on the top of Travis CI's page, and it shows:  
![Branch: GUI_dev; Url: Image Url; Link: https://travis-ci.org/KuangLei/Base32GUI.svg?branch=master;](https://user-images.githubusercontent.com/12217600/29669886-8185098e-8917-11e7-9beb-c74871c20601.jpg)
The branch menu is pre-chosen as `GUI_dev`, but the url is given with `master` but not `GUI_dev`.  

So I think it may change the branch in the url only when switching the branch menu. It should also check the branch in the url when opening Status Image page.  

(Firefox ESR 52.3.0 (64-bit) / LXDE / Debian 9.1.0 amd64)

Thanks.

**Comment by lislis** [comment]
Hi @KuangLei, thank you for reporting this!
I started working on a fix in this PR https://github.com/travis-ci/travis-web/pull/1260
I'll update this ticket once the fix is in production.

**Comment by lislis** [comment]
It's live now! But I see you were faster than me :D
