### ISSUE TITLE
Option to auto cancel builds of dangling commits on force pushed branches

### ISSUE THREAD

**Issue by akien-mga** [travis-ci/travis-ci#8294]
## Feature request

I would like a new option (likely opt-in, I don't think it fits all workflows) for Travis CI to automatically cancel its PR build jobs when the PR source branch has been rebased and force pushed, and the commit being tested by Travis CI is left dangling.

This would allow to start testing the next build job directly instead of having a no longer relevant build job of a dangling commit wasting resources and time.

## Motivation

In our PR workflow over at https://github.com/godotengine/godot, we often ask users to rebase their PRs/amend the commit with fixup so that we can ensure a clean and readable git history after merge. That implies pushing their changes with `git push --force`, thus making some of the previous commits dangling and no longer testing-relevant.

Taken to the extreme, it often happens that users force push their branches while the Travis CI builds jobs are running (especially since we also use macOS build nodes which are often less available). For example:
![image](https://user-images.githubusercontent.com/4701338/29680349-9336e304-8904-11e7-873f-bae76eb2e38b.png)

Since our build matrix is quite heavy (5 platforms, each taking ~15 min to build) and we get a dozen of PRs every day in average, it can easily lead to a stalled build queue, even more so if there are some global availability issues like with macOS build nodes the last few days.

In our use case, a build job for a dangling commit has no value, and we would therefore all greatly benefit (queue processed faster for us, less resources used for you) with an option to cancel them automatically.

**Comment by BanzaiMan** [comment]
Does auto cancellation feature not work in this case? https://docs.travis-ci.com/user/customizing-the-build#Building-only-the-latest-commit

**Comment by akien-mga** [comment]
Oh, that's great, I had never noticed this feature. I think it satisfies my use case quite well, thanks!

**Comment by vaibhavhrt** [comment]
> If you are only interested in building the most recent commit on each branch you can use this new feature to automatically cancel older builds in the queue that are not yet running. Existing builds will be allowed to finish.

I want to stop the currently running build too and start the latest one is there some way to do that? As at least in my case there is no point in letting running jobs finish if there is a new commit.

**Comment by JMSwag** [comment]
An additional option to cancel currently running builds would be awesome!
