### ISSUE TITLE
Build stages build out of order specified by travis.yml

### ISSUE THREAD

**Issue by canavandl** [travis-ci/travis-ci#8299]
In our travis.yml we specify three stages: build, test, deploy. We've noticed that the stages are now running alphabetically: build, deploy, test.

Here's our travis.yml: https://github.com/bokeh/bokeh/blob/master/.travis.yml

Here's a build: https://travis-ci.org/bokeh/bokeh/builds/268420281

Here's screenshot of that build:
<img width="1074" alt="screen shot 2017-08-25 at 2 00 25 pm" src="https://user-images.githubusercontent.com/2198981/29728769-e6a1f3cc-899e-11e7-886a-00106f7654a7.png">

**Comment by BanzaiMan** [comment]
Hello there. I've reproduced the problem; if there are enough jobs in the build, this issue manifests.

**Comment by weitjong** [comment]
We also seen this problem today in one of CI build. https://travis-ci.org/urho3d/Urho3D/builds/268643607
The housekeep stage should be the last stage in our config but it ended up in the middle and screw up the rest of stage.

**Comment by backspace** [comment]
Thanks for letting us know about this! We have deployed a change that should address this bug. Could you try things again and confirm that this behaviour has disappeared?

**Comment by weitjong** [comment]
It looks now for ours.

**Comment by canavandl** [comment]
This issue appears to have been resolved. Thanks

**Comment by backspace** [comment]
Excellent, thanks for letting us know! 💞
