### ISSUE TITLE
Travis number of cores available inconsistent with cgroup info

### ISSUE THREAD

**Issue by Meijuh** [travis-ci/travis-ci#8303]
It seems that the information provided by [this page](https://docs.travis-ci.com/user/reference/overview/) about the number of cores available on docker infrastructures and Ubuntu Trusty is inconsistent with the information that `/proc/self/status` provides.
The docker builds have a maximum of 2 cores available, while the cpu set information provided by  cgroups in `/proc/self/status` gives 32 cores:

    Cpus_allowed:	00000000,00000000,00000000,ffffffff
    Cpus_allowed_list:	0-31

In practice this makes a common way of determining the number of cores available via glibc unusable, which is:

    size_t cpu_count {
        cpu_set_t cs;
        CPU_ZERO(&cs);
        sched_getaffinity(0, sizeof(cs), &cs);
        return CPU_COUNT(&cs);
    }

If I run a Travis image locally with:

1. `sudo docker run --cpuset-cpus=0 --cpus=1 --memory=4g --name travis-debug1 -dit travisci/ci-garnet:packer-1499451976 /sbin/init`
1. `sudo docker exec -it travis-debug1 bash -l`

The function `cpu_count()` returns the number of cores (which is 1) correctly. However, on a remote Travis CI build (docker, Trusty) `cpu_count()` does not return the correct number of cores (it returns 32).

The issue is that there is no documentation on what additional means one should use to get the correct number of cores on a Travis CI docker build using cgroup info, and what the difference is between running a local docker image with cgroup restrictions and a remote docker build on Travis CI.

To make matters worse, Python also does not recognize the correct number of cores:

      script:
        - pip install psutil
        - echo "printing python cpu count!"
        - echo -e "import psutil\nprint(psutil.cpu_count())" | python

Will print 32, instead of 2.

**Comment by BanzaiMan** [comment]
The difference in behavior likely comes from implementation; our Docker containers currently runs on a large EC2 instance, which may or may not provide accurate information you seek.

**Comment by Meijuh** [comment]
Is there way to get the correct information? 
I can imagine it to be quite a problem for builds using e.g. Java. For example the OpenJDK JRE9 HOTSPOT VM also requires correct information about the number of cores available, see here: http://hg.openjdk.java.net/jdk9/jdk9/hotspot/rev/c5480d4abfe4#l2.44. This piece of code is similar to the one I posted. The HOTSPOT VM requires a correct number of threads to start for garbage collection. I wouldn't be surprised that starting 16 times too many threads causes some builds to hang.

**Comment by gwarnes-mdsol** [comment]
The R "parallel" package (via `parallel::detectCores()` also reports the number of CPU cores as 32.

**Comment by benoit-pierre** [comment]
This is still happening:
* https://travis-ci.org/benoit-pierre/pip/jobs/435949999#L490
* https://travis-ci.org/benoit-pierre/pip/jobs/435675686#L511
