### ISSUE TITLE
The 'user' argument is required

### ISSUE THREAD

**Issue by mh-cbon** [travis-ci/travis-ci#8306]
ref https://travis-ci.org/mh-cbon/go-bin-deb/jobs/268660283#L565

because my bintray deploy section missed the user key.

Is is possible to improve error messages ?

**Comment by BanzaiMan** [comment]
I am not sure what you are asking. The log clearly shows that it is required, and we do state this in the documentation as well. https://docs.travis-ci.com/user/deployment/bintray#Package-Section

**Comment by BanzaiMan** [comment]
Closing this, as there is not much more to do here.
