### ISSUE TITLE
pypi provider is obsolete

### ISSUE THREAD

**Issue by jleni** [travis-ci/travis-ci#8308]
When using travis-ci provider I receive an HTTPError410 (copy below). Is there an alternative provider or some new guidelines?
The documentation here is also obsolete:
   https://docs.travis-ci.com/user/deployment/pypi/

``` .travis.yaml
deploy: 
- provider: pypi 
  server: https://testpypi.python.org/pypi
  ...
```

Error message:
> HTTPError: 410 Client Error: Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html) for url: https://testpypi.python.org/pypi

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by jleni** [comment]
Here is a build log where you can find the HTTPError: 410

https://travis-ci.org/jleni/QRL/builds/269143448

**Comment by BanzaiMan** [comment]
You are specifying the deprecated API endpoint https://github.com/jleni/QRL/blob/15321d597ce99f3e9076dc51c9aa68f318c63048/.travis.yml#L32, and that server is displaying the error message you are seeing. Please use a different one.

Our document does not refer to this server, either. So there is nothing for us to do here.
