### ISSUE TITLE
Log shows uncollapsed `npm ls` output

### ISSUE THREAD

**Issue by ismay** [travis-ci/travis-ci#8309]
My travis build started showing `npm ls` output, and doesn't collapse it by default ([see here](https://travis-ci.org/ismay/ismaywolff.nl/builds/268860667#L486)). Which makes my build logs quite long. Older builds (month ago and earlier) did no such thing ([see here](https://travis-ci.org/ismay/ismaywolff.nl/builds/257309005)), why isn't the output collapsed by default?

**Comment by BanzaiMan** [comment]
This is quite interesting.

Within the `master` branch builds, you see that [build 2205](https://travis-ci.org/ismay/ismaywolff.nl/builds/259418981) has the fold correct, while the next [build 2214](https://travis-ci.org/ismay/ismaywolff.nl/builds/259420265) does not. If you compare the two builds, you see that they ran on the same image, using the same `travis-build` version. So I tend to rule them out as possible culprits.

Could you try tagging [this commit](https://github.com/ismay/ismaywolff.nl/commit/858b83edb004f7d9104066bd52567475be6ff25d) that ran the last "good" build and see if the problem persists?

Thanks.

**Comment by ismay** [comment]
Ah I see. So `npm ls` is run automatically after the install process.

> Could you try tagging this commit that ran the last "good" build and see if the problem persists?

I'm afraid I don't understand what you mean exactly. Do you want me to restart that build?

**Comment by ismay** [comment]
Ah ok, didn't know that tagging a commit would trigger a build. Tagged it, the build is here:

- https://travis-ci.org/ismay/ismaywolff.nl/builds/269939855

**Comment by gkatsev** [comment]
I have the same problem with Video.js. Been happening for quite a while, latest two builds are https://travis-ci.org/videojs/video.js/builds/333778796 and https://travis-ci.org/videojs/video.js/builds/333778826

**Comment by johnBartos** [comment]
It would be nice to not have `npm ls` called by default; it's easy enough for people to add themselves if they want. For larger projects the 1000+ lines of `npm ls` is too noisy.

**Comment by schoenwaldnils** [comment]
Please reopen. Still happening. Still noisy :/

**Comment by BanzaiMan** [comment]
The reason that we call `npm ls` by default is to preserve the behavior `npm` had before version 5. See https://github.com/travis-ci/travis-build/pull/1096.

**Comment by gkatsev** [comment]
I think some people probably don't care for it. At the very least, the fact that it mostly is uncollapsed, if you have a large tree, it makes the logs incredibly long and hard to figure. If it's collapsed, it can be ignored and cleans thing up a lot. Maybe we can have an option to turn it off?

**Comment by ProLoser** [comment]
Please reopen this issue, as it's incredibly annoying to have this hardcoded behavior bloat the logs. If people really wanted this behavior they could do a verbose `npm install`

**Comment by BanzaiMan** [comment]
FYI https://changelog.travis-ci.com/node-js-builds-skips-npm-ls-by-default-74923

**Comment by gkatsev** [comment]
Thanks @BanzaiMan!
