### ISSUE TITLE
Different behavior travis-ci.com and travis-ci.org

### ISSUE THREAD

**Issue by JesusZapata** [travis-ci/travis-ci#8311]
Actually I have two pull request with the same code but the first is one public repository and the second is one private repository and the build in the private repository in travis.com show me the follow mistake

`ParseError: "'buffer' does not have the buffer interface"`

This is the log of the private repository into the [travis.com](https://travis-ci.com/Vauxoo/tanner/jobs/87840927)

This is the log of the public repository into the [travis.org](https://travis-ci.org/JesusZapata/asdcust/builds/269346004)

The source code can see on the follow url https://github.com/JesusZapata/asdcust/pull/2

**Comment by JesusZapata** [comment]
@BanzaiMan 
Do you could help me with check this mistake?

**Comment by BanzaiMan** [comment]
@JesusZapata It is not entirely clear to me these are testing the same code. I don't have a good understanding of your `tanner` repo, so I can't say that I understand the issue, either. Have you tried running a debug build and examining the files mentioned in the error message?

**Comment by JesusZapata** [comment]
@BanzaiMan 
Thanks for you answer, I found one solution to my trouble
I will close this issue
