### ISSUE TITLE
Slack notification not working on build/merge/PR on branch other than master

### ISSUE THREAD

**Issue by SugandhaAgrawal** [travis-ci/travis-ci#8314]
In my project, I have implemented branch specific deployments. To enable the slack notifications, I updated the .travis.yaml with slack token and it triggered no update in Slack. While trying the same in another project where master branch does deployment, the notifications work fine. The questions I have here are : 
- Is it only expected to work for master branch?
- If not, so how can notifications be enabled for specific branch
- I checked the issue : https://github.com/travis-ci/travis-ci/issues/1405. Anytime timeline for this to be supplied?

Thanks

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by SugandhaAgrawal** [comment]
Unfortunately I cannot, its a private company project. But if you need specifics maybe I can clarify further.

**Comment by BanzaiMan** [comment]
Please email us at support@travis-ci.com. There is no public information to share here, so I'm closing this.
