### ISSUE TITLE
Fails to install packages in Trusty

### ISSUE THREAD

**Issue by charlemagnelasse** [travis-ci/travis-ci#8317]
It was reported that https://github.com/mupen64plus/mupen64plus-core/issues/377 now fails suddenly in the "apt-get install" step.

A log of the failed install can be found in https://travis-ci.org/mupen64plus/mupen64plus-core/jobs/269748268
But it worked previously flawless - as you can see in https://travis-ci.org/mupen64plus/mupen64plus-core/jobs/266389369#L1

The config can be found in https://github.com/mupen64plus/mupen64plus-core/blob/master/.travis.yml and was not touched between these two builds.

**Comment by BanzaiMan** [comment]
Did the requirements for these packages change somehow? https://travis-ci.org/mupen64plus/mupen64plus-core/jobs/269437306#L473-L475 says:

```
The following packages have unmet dependencies:
 libsdl2-dev : Depends: libegl1-mesa-dev
               Depends: libgles2-mesa-dev
E: Unable to correct problems, you have held broken packages.
```

but these packages were previously installed (https://travis-ci.org/mupen64plus/mupen64plus-core/jobs/266389369#L459-L468).

**Comment by BanzaiMan** [comment]
Hmm. Perhaps our `apt-get` defaults changed somehow?

If you add the missing dependencies, it appears to work if you add the packages that `apt-get` is complaining about. https://github.com/mupen64plus/mupen64plus-core/pull/380

**Comment by charlemagnelasse** [comment]
No, requirements didn't change. And manually specifying these is not the right solution. apt-get was previously able to resolve the dependencies (which are not direct dependencies of mupen64plus-core)

**Comment by charlemagnelasse** [comment]
Interestingly, it works when using the apt addon. See https://github.com/mupen64plus/mupen64plus-core/pull/381

It looks like something broke horrible on your servers and which most likely also effects other projects which did not yet switch to the apt addon

**Comment by RICCIARDI-Adrien** [comment]
I confirm @charlemagnelasse workaround is working on my project https://github.com/RICCIARDI-Adrien/Strage.

**Comment by AI0867** [comment]
This bug also affects the [Wesnoth](https://github.com/wesnoth/wesnoth) project.

**Comment by ivanperez-keera** [comment]
Ok, so I just looked at the line that travis runs to install with `apt-get`, and it is slightly different from what I was running. I was doing:
```
$ sudo apt-get install <packages>
```
But travis is doing [1]:
```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install <packages>
```
Running `aptitude` gives a bit more info about what's going on:
```
$ sudo -E aptitude install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-gfx-dev

The following NEW packages will be installed:
  freepats{a} libasound2-dev{a} libavahi-client-dev{a} 
  libavahi-common-dev{a} libboost-system1.54.0{a} libdbus-1-dev{a} 
  libegl1-mesa-dev{a} libegl1-mesa-drivers-lts-utopic{a} 
  libegl1-mesa-lts-utopic{ab} libfluidsynth1{a} libgbm1-lts-utopic{a} 
  libgl1-mesa-dri-lts-utopic{ab} libglapi-mesa-lts-utopic{ab} 
  libgles2-mesa{a} libgles2-mesa-dev{a} libjack-jackd2-0{a} libllvm3.5{a} 
  libmad0{a} libmirclient-dev{a} libmirclient7{a} 
  libmirclientplatform-mesa{a} libmirprotobuf-dev{a} libmirprotobuf0{a} 
  libmodplug1{a} libopenvg1-mesa-lts-utopic{a} libprotobuf-dev{a} 
  libprotobuf-lite8{a} libprotobuf8{a} libpulse-dev{a} 
  libpulse-mainloop-glib0{a} libsamplerate0{a} libsdl2-2.0-0{a} libsdl2-dev 
  libsdl2-gfx-1.0-0{a} libsdl2-gfx-dev libsdl2-image-2.0-0{a} 
  libsdl2-image-dev libsdl2-mixer-2.0-0{a} libsdl2-mixer-dev 
  libsdl2-ttf-2.0-0{a} libsdl2-ttf-dev libts-0.0-0{a} libts-dev{a} 
  libtxc-dxtn-s2tc0{a} libudev-dev{a} libwayland-dev{a} 
  libwayland-egl1-mesa-lts-utopic{a} libwebp5{a} libxcursor-dev{a} 
  libxi-dev{a} libxinerama-dev{a} libxkbcommon-dev{a} libxrandr-dev{a} 
  libxv-dev{a} mircommon-dev{a} tsconf{a} x11proto-randr-dev{a} 
  x11proto-video-dev{a} x11proto-xinerama-dev{a} 
0 packages upgraded, 59 newly installed, 0 to remove and 15 not upgraded.
Need to get 49.0 MB of archives. After unpacking 114 MB will be used.
The following packages have unmet dependencies:
 libegl1-mesa : Conflicts: libegl1-x11 which is a virtual package.
 libgl1-mesa-dri-lts-utopic : Conflicts: libgl1-mesa-dri but 10.1.3-0ubuntu0.6 is installed.
 libglapi-mesa-lts-utopic : Conflicts: libglapi-mesa but 10.1.3-0ubuntu0.6 is installed.
 libegl1-mesa-lts-utopic : Conflicts: libegl1-mesa but 10.1.3-0ubuntu0.6 is installed.
                           Conflicts: libegl1-x11 which is a virtual package.
```
It's strange (to me) because this is supposed to be a `trusty` image, but contains `utopic` packages. But it's been reported before, not just on travis.

I believe the right solution is to use the `apt` addon for all packages but, if you want to do what travis does, manually, just use `--no-install-suggests --no-install-recommends` (I removed the latter and the installation failed for me).

This seems to be related to [2]. It's been reported over and over online :(

[1] https://github.com/travis-ci/travis-build/blob/ef82e82457f82c6518d090544bb533dc0faf0063/lib/travis/build/addons/apt.rb#L154-L155

[2] https://bugs.launchpad.net/cloud-images/+bug/1713815

**Comment by charlemagnelasse** [comment]
The last activity was 14 days ago. So keep your stale state for yourself.

    Phrohdoh added a commit to ChariotEngine/Chariot that referenced this issue 14 days ago
     @Phrohdoh
    ci: Use the apt addon for Travis  …
