### ISSUE TITLE
no space left on device after removing file

### ISSUE THREAD

**Issue by tdhock** [travis-ci/travis-ci#8319]
Hi, first of all thanks for your excellent service for the free/open-source software community!

I am getting the error "No space left on device" in https://travis-ci.org/tdhock/PeakSegPipeline#L4242 -- I was expecting that I could write large files, and then delete them. It seems that after deleting the file, it disappears from the file system, but it is still counted in `df`.

My testing code creates a large file, and then deletes it after. You can see the following in the build output -- after having created a large file, but before deleting it:
```
BEFORE removing file (unlink)-------- du -m /tmp/Rtmp3221zu/PeakSegPipeline-test/demo/samples/bcell/MS026601/problems/chr10:18024675-38818835/*.db 
3032	/tmp/Rtmp3221zu/PeakSegPipeline-test/demo/samples/bcell/MS026601/problems/chr10:18024675-38818835/coverage.bedGraph_penalty=15935.9415152135.db
Filesystem     1M-blocks  Used Available Use% Mounted on
udev                3728     1      3728   1% /dev
tmpfs                748     1       748   1% /run
/dev/sda1          30205 26560      2299  93% /
none                   1     0         1   0% /sys/fs/cgroup
none                   5     0         5   0% /run/lock
none                3740     0      3740   0% /run/shm
none                 100     0       100   0% /run/user
none                 768   179       590  24% /var/ramfs
```
The first two lines above are the `du` command line that I used, and the corresponding output -- a file of 3032MB in a temporary directory. The other lines are the output of `df -m`.

After deleting the file I get the following output,
```
AFTER removing file (unlink)-------- du -m /tmp/Rtmp3221zu/PeakSegPipeline-test/demo/samples/bcell/MS026601/problems/chr10:18024675-38818835/*.db 
du: cannot access ‘/tmp/Rtmp3221zu/PeakSegPipeline-test/demo/samples/bcell/MS026601/problems/chr10:18024675-38818835/*.db’: No such file or directory
Filesystem     1M-blocks  Used Available Use% Mounted on
udev                3728     1      3728   1% /dev
tmpfs                748     1       748   1% /run
/dev/sda1          30205 26560      2299  93% /
none                   1     0         1   0% /sys/fs/cgroup
none                   5     0         5   0% /run/lock
none                3740     0      3740   0% /run/shm
none                 100     0       100   0% /run/user
none                 768   179       590  24% /var/ramfs
```
The first two lines indicate that the deletion worked -- the `du` command reports that there is no such file or directory (with the same file glob I used previously). However the `df -m` on the following lines reports that there is still the same amount available (2299MB, 93% on /). I was expecting this amount to increase, since the file has been deleted.

Any idea about how to fix this?

**Comment by BanzaiMan** [comment]
The files may be invisible from the file system, but if any process still has the file descriptors to these deleted files, the disk space will not be released.

**Comment by tdhock** [comment]
great, thanks for the info! I resolved the issue by adding a line of C++ code that closes the large *.db file.

Sorry for the trouble. @BanzaiMan

**Comment by BanzaiMan** [comment]
Good to hear!
