### ISSUE TITLE
Install Unlimited Strength Jurisdiction Policy Files on JVM Build Machines

### ISSUE THREAD

**Issue by mcantrell** [travis-ci/travis-ci#832]
In order to use the stronger encryption algorithms with the Java JCE, the unlimited strength jurisdiction files need to be installed.

http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

The jars simply need to be placed in JAVA_HOME/jre/lib/security

I have integration tests which I'd like to be able to run on Travis but I completely if this request is declined. It's a pain in the butt :( I thought I'd at least ask though.

**Comment by simonbrandhof** [comment]
Does someone have a workaround for non-sudo docker environments ? Thanks

**Comment by WriterZephos** [comment]
Is this a script to automatically install the policy files on clients?

**Comment by kibotu** [comment]
I have the same issue now. my pgp encryption tests fail now because of said missing policy https://github.com/kibotu/Android-PGP
