### ISSUE TITLE
Build succeeds even tests fail

### ISSUE THREAD

**Issue by naveenkumarmarri** [travis-ci/travis-ci#8320]
Hi,

I'm working on python project which has travis-ci integrated.
there are some tests that must pass for build to succeed.
However even though the tests are failing
The build is passing with saying

`The command "test/runtests.py" exited with 0.
Done. Your build exited with 0.`

can someone help me on this?

**Comment by BanzaiMan** [comment]
Your script `test/runtests.py` is exiting with status 0. You must write code that recognizes the failures, and exits with correct status code when it happens. https://docs.travis-ci.com/user/customizing-the-build#Customizing-the-Build-Step
