### ISSUE TITLE
output can't contain the string "true"

### ISSUE THREAD

**Issue by vtjnash** [travis-ci/travis-ci#8322]
Anywhere that our job attempts to print the string "true", Travis instead writes the string "[secure]". For example, see: https://travis-ci.org/JuliaLang/julia/jobs/269818996

**Comment by BanzaiMan** [comment]
One of the secure variables in the build must have the value `true`, and we are filtering it. There is no way to distinguish the unintentionally-revealed `true` and the `true` you *wanted* to see, unfortunately.

**Comment by vtjnash** [comment]
Ah! I wasn't aware someone had been using a secure variable to set the value "true" in our build. I think I've fixed our configuration now. Thanks for the help.
