### ISSUE TITLE
New trusty build box seems to pull in Mariadb 10 even though we ask for 5.5

### ISSUE THREAD

**Issue by pacharya** [travis-ci/travis-ci#8323]
At Versal, we have a travis build like this - 

```
language: scala
jdk:
  - oraclejdk8

sudo: false

addons:
  mariadb: "5.5"

scala:
- 2.11.8

#The -Xmx1G setting is to prevent intermittent Travis build failures in the
#container-based environment. Use caution when adjusting these settings.
#See API-3937 and https://github.com/travis-ci/travis-ci/issues/3775
env:
- _JAVA_OPTIONS="-Xms1G -Xmx1G -Xss4M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M
  -Drest-api-config=CI-config -Drest-api-logging-config=CI-logback.xml"

.. more stuff ...

```

With the new trusty build boxes, all builds started failing. They are failing with the step at which we populate our test db. In fact we have experienced this before in our local vagrant-based test boxes, when I was trying to move from trusty to the xenial xerus (16.04). In that case, `apt` was claiming to install 5.5 but was actuallt installing mariadb 10. Our software and db build process was not compatible with 10. I cant prove it 100% but I think that the trusty based travis boxes are getting mariadb 10, possibly due to a misconfiguration of apt setup. Please look into this or get in touch with me.

Adding `dist: precise` solves this problem for now but thats not a permanent solution. If this is the wrong place to log an issue please let me know.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by pacharya** [comment]
i have but its a private repo. tried looking for travis support, we are a paid customer. is this the wrong forum?

**Comment by BanzaiMan** [comment]
In that case, please email us at support@travis-ci.com with details. There is no need for a public issue, so I'm closing this. Thank you!
