### ISSUE TITLE
Option to downgrade GCC version

### ISSUE THREAD

**Issue by bel2125** [travis-ci/travis-ci#8329]
It seems, the build imaged upgraded to a new gcc version a couple of days ago.

__What was the old version?__
__Is there a way to explicitly not use it but stick to the old one?__

I guess it could probably done by specifying a package (https://docs.travis-ci.com/user/languages/c/), but which one is it, and is there a way to force replacing a new package by an old one (currently I use `sudo: false`).

Reason is, I used to build with -Werror, and the new version raises several spurious warnings, that can't be turned of using #pragmas in this compiler version - and since we are heading for a release, *now* it's not the time to take care about new compilers.

Warnings include (just as some examples): 
Using `__DATE__` rises `expansion of date or time macro is not reproducible` ... so what? That's the purpose of `__DATE__`!

And another false positive (See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=751812 - It seems Debian never solved this, but switched to another compiler version and closed this issue).
```
/usr/include/x86_64-linux-gnu/bits/stdio2.h: In function ‘send_file_data’:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:290:2: error: call to ‘__fread_chk_warn’ declared with attribute warning: fread called with bigger size * nmemb than length of destination buffer [-Werror]
  return __fread_chk (__ptr, __bos0 (__ptr), __size, __n, __stream);
```

**Comment by BanzaiMan** [comment]
If yours was running on Precise before, try `dist: precise`. See https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

**Comment by bel2125** [comment]
It seems, the version were
```
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
clang version 3.4 (tags/RELEASE_34/final)
```
and are now
```
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
clang version 3.5.0 (tags/RELEASE_350/final)
```

It does not work to just add the old versions to `.travis.yml`
```
    packages:
      - gcc-4.6
      - clang-3.4
```
A "side by side" installation of different gcc versions requires a lot of manual configuration (lots of `sudo` and maybe install with --force and turning lots of symlinks in the system).

It's probably not possible to just use the old image, since it's marked as retired (https://docs.travis-ci.com/user/reference/overview/): *Ubuntu precise ... container environment ... Retired as of September 2017*
Is this the update, that has been done now?
Is there some compatibility setting?

In principle, I do want to update to a more recent compiler some time - it's just not a good moment now.

**Comment by bel2125** [comment]
> If yours was running on Precise before, try dist: precise. See https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

Ok thanks (was still typing my last comment before reading your answer).

Is it true
```
sudo: false 
dist: precise
```
will disappear?

Can it be replaced by
```
sudo: required
dist: precise
```

**Comment by bel2125** [comment]
Thanks, your blog (https://blog.travis-ci.com/2017-08-31-trusty-as-default-status) seems to answer all questions. Probably I should have subscribed to the newsletter ...

Thanks - closing this issue.
