### ISSUE TITLE
travis not triggering on github push

### ISSUE THREAD

**Issue by gemerden** [travis-ci/travis-ci#8332]
For the repo `gemerden/wildpath` travis is not triggering. The message is "No builds for this repository". It used to work.

Please help,

Lars van Gemerden

**Comment by BanzaiMan** [comment]
Did you perhaps enable this repository on https://travis-ci.com instead?

If this was unintentional, go to https://travis-ci.org/profile and reenable the repo.

**Comment by gemerden** [comment]
was in private repo part, ...
