### ISSUE TITLE
Travis only recognizes some tags and not others -- seemingly at random

### ISSUE THREAD

**Issue by johanneswilm** [travis-ci/travis-ci#8335]
Due to the update from precise to trusty, I went through a number of version (1.0.0-1.0.5) in order to fix the issue with the biblatex-csl-converter repo [1]. As part of that I noticed that  travis apparently only sometimes recognizes a tag. It did recognize tags at 1.0.3 and 1.0.5, but it didn't notice the one at 1.0.4. All the tags were created the same way (`npm version patch`) and also pushed to github in the same way. Github did take notice of all of them. Because deployment is linked to tagged versions, whenever travis misses a tag, it also means that that version does not get deployed.

 [1] https://github.com/fiduswriter/biblatex-csl-converter/

**Comment by BanzaiMan** [comment]
https://travis-ci.org/fiduswriter/biblatex-csl-converter/builds/271447901 is the tag build for `v1.0.4`, is it not?

**Comment by johanneswilm** [comment]
Yepp. Sorry. It looks like it's making two builds for each commit that has been tagged. And what is random is the order of these: for some it runs the tag-build first, for others it runs the other commit-build first. Forget about it.
