### ISSUE TITLE
Cannot use system site-packages on any Python 3 version

### ISSUE THREAD

**Issue by SolarLiner** [travis-ci/travis-ci#8336]
... even 3.2 using "3.2_with_system_site_packages".

I'm the author of a small CLI written in python for Linux that basically improves on `notify-send` with action and reply support; and was made with a accompanying Node.js module in mind. https://github.com/SolarLiner/libnotify-terminal

Digging around to see how to include the system site-packages in Travis builds, I come around using `virtualenv: system_site_packages: true` but it doesn't work (Travis cannot source the venv activation script as it doesn't exist); so I end up searching more, only to find that only version 3.2 has site-packages support (any explanation on why? Any version of python can be used to access the system site-packages, not just 3.2 or 2.7).

But I resolve myself to using v3.2 and `python: "3.2_with_system_site_packages"`, but it still fails; [here's the log](https://travis-ci.org/SolarLiner/libnotify-terminal/jobs/271451067).

**Comment by BanzaiMan** [comment]
Your build is now using Trusty, which ships with Python 3.4.0 (https://packages.ubuntu.com/trusty/python3). If you want to use `virtualenv.with_system_packages: true`, you'll need to use that version. Here's a long that does it: https://travis-ci.org/BanzaiMan/travis_production_test/builds/272664040#L428

See also https://github.com/travis-ci/travis-ci/issues/4260#issuecomment-120405756 and the discussions surrounding this feature; we may deprecate it at some point in the future.

I'm closing this now in favor of the issue above.
