### ISSUE TITLE
Cannot deploy to (production) PyPi - HTTP 403 although the password is correct

### ISSUE THREAD

**Issue by gdubicki** [travis-ci/travis-ci#8339]
Deploy to PyPi (production) using Travis CI is failing for my project with:

```
(...)
creating dist
Creating tar archive
removing 'gitlabform-0.17.0' (and everything under it)
Uploading distributions to https://upload.pypi.org/legacy/
Uploading gitlabform-0.17.0.tar.gz
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
```

Whole failed build output: https://travis-ci.org/egnyte/gitlabform/builds/271606352

My config is here: https://github.com/egnyte/gitlabform/blob/master/.travis.yml

I have re-encrypted the pypi password that we are using today and during that I made sure that it does not include any special characters mentioned in https://docs.travis-ci.com/user/deployment/pypi/ .

**Comment by BanzaiMan** [comment]
Are you sure the encryption was done correctly? The error message indicates it was not.

**Comment by gdubicki** [comment]
Yeah, I made a mistake when encrypting the password...

I didn't want to use `--add` because it modified my `.travis.yml` formatting and removed my comments, so I used the `VAR=value` syntax: https://docs.travis-ci.com/user/encryption-keys/#Usage . But I didn't read the docs carefully enough and skipped the part that states that var name is encrypted along with the value. And I use some random var name as I though it didn't matter...

In the end I had an issue with ending entering the password in the interactive mode as documented at https://docs.travis-ci.com/user/deployment/pypi/ (Ctrl+D didn't work), so I did this:

```
echo -n "<my password>" | travis encrypt --add deploy.password -r egnyte/gitlabform
```

..and after that I fixed my `.travis.yml` formatting manually before pushing changes to my repo.

In the end I understand that this was my mistake but at the same time I feel that managing secrets with travis cli could be simpler...

**Comment by holzkohlengrill** [comment]
I just wanted to emphasise some part of @gdubicki s comment:

> [the] var name is encrypted along with the value

Also: `encrypt "blah"` is not equal to `encrypt SOME_VAR="blah"`.

This took me hours to realise...
