### ISSUE TITLE
Allow to specify version of python-virtualenv in .travis.yml (with language: generic)

### ISSUE THREAD

**Issue by ale5000-git** [travis-ci/travis-ci#8342]
In .travis.yml inside addons => apt => packages => python-virtualenv (with language: generic) it allow only the default version of it, if I specify a different version it fails.

I need to change to older/newer versions to test (with sudo: false) different versions of Python not supported by default.
Can you please allow it?

It is important to map to a specific version because an update to python-virtualenv can break my testing code.

**Comment by ale5000-git** [comment]
Any news about this?
It is important to map to a specific version because an update to python-virtualenv can break my testing code.

**Comment by ale5000-git** [comment]
Hi, any change?

**Comment by BanzaiMan** [comment]
Hello, there.

You are using `python-virtualenv` from the official APT package repository, which hosts only one version of it at any point.

You could try changing the virtualenv versions on the fly with a different means, but I am afraid we are unlikely to provide you with support beyond that.
