### ISSUE TITLE
cannot build eclipse plugin with maven / tycho (Java 7) anymore

### ISSUE THREAD

**Issue by anb0s** [travis-ci/travis-ci#8345]
I did not changed my yaml file. It worked last time i've pushed my repo 4 days ago, see https://travis-ci.org/anb0s/eclox/builds/270564034

Now Java 7 cannot be executed anymore, see https://travis-ci.org/anb0s/eclox/builds/271423616

> $ mvn clean verify
> Error: JAVA_HOME is not defined correctly.
>   We cannot execute /usr/lib/jvm/java-7-oracle/bin/java
> The command "mvn clean verify" exited with 1.
> Done. Your build exited with 1.
>

**Comment by anb0s** [comment]
Java 7 worked 4 days ago:
```
$ export PATH=$JAVA_HOME/bin:$PATH
$ java -Xmx32m -version
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)
$ javac -J-Xmx32m -version
javac 1.7.0_76
before_script
0.00s$ cd eclox.root
214.49s$ mvn clean verify
[INFO] Scanning for projects...
```
Now Java 8 is there and Java 7 is not working:
```
$ export PATH=$JAVA_HOME/bin:$PATH
$ java -Xmx32m -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_131
before_script
0.03s$ cd eclox.root
0.08s$ mvn clean verify
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-7-oracle/bin/java
The command "mvn clean verify" exited with 1.
Done. Your build exited with 1.
```

**Comment by anb0s** [comment]
.travis.yml:
```
language: java
jdk:
  - oraclejdk7

before_script: cd eclox.root

script: mvn clean verify

```

`oraclejdk7` is not available anymore?

**Comment by BanzaiMan** [comment]
Indeed, OracleJDK 7 is not available. This needs documenting. I'm closing this, though, in favor of #7884.

**Comment by anb0s** [comment]
ok, using openjdk7 and oraclejdk8 now
