### ISSUE TITLE
PEAR channel discovering broken

### ISSUE THREAD

**Issue by yunosh** [travis-ci/travis-ci#8350]
Since recently the automatic channel discovery with the PEAR installer doesn't work anymore, no matter if run on precise or trusty:
https://travis-ci.org/horde/horde/jobs/272455383#L1132
https://travis-ci.org/horde/horde/jobs/272424679#L1810

**Comment by BanzaiMan** [comment]
https://travis-ci.org/horde/horde/jobs/272455383#L1138 says:

```
invalid package name/package file "channel://pear.horde.org/Horde_Role"
```

Is this not an upstream issue? Does this work on your machine?

**Comment by yunosh** [comment]
Yes, it does, and works on some Travis PHP builds.

**Comment by BanzaiMan** [comment]
> Yes, it does, and works on some Travis PHP builds.

Can you show where this works?

**Comment by yunosh** [comment]
It works on all PHP versions but 5.6 and 7.0: https://travis-ci.org/horde/Core/builds/284173854
And this is my temporary workaround:
```
echo "include_path = .:$HOME/.phpenv/versions/$(phpenv version-name)/lib/php/pear" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
```
See the referenced issue #8541.

**Comment by BanzaiMan** [comment]
Thanks for the info. I think this is a different manifestation of https://github.com/travis-ci/travis-ci/issues/8365.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/1201 has been merged and deployed. I'm closing this optimistically, but if you continue to see problems, do let us know.

**Comment by yunosh** [comment]
Looks good, thanks!
