### ISSUE TITLE
New build has been queued for 3+ hours

### ISSUE THREAD

**Issue by capveg** [travis-ci/travis-ci#8354]
Hi, my project FBOSS (https://travis-ci.org/facebook/fboss/builds) has travis-ci integration all setup and working great (thank you!), but our recent change has triggered a build correctly, but it has been sitting there in the "Hang tight, the log cannot be shown until the build has started." state for 3+ hours. 

I've manually triggered a build by hand and it has the same results.  

Any idea what's wrong?  My other projects that use travis seems to be working correctly.  

Thank you in advance!

**Comment by SylvainCorlay** [comment]
Same here. Linux builds "waiting to be queued".

**Comment by BanzaiMan** [comment]
Looks like a large number (10) of Mac jobs are occupying the `facebook` organization's slots (15).

**Comment by capveg** [comment]
Thanks for the reply.  Any way to map those jobs back to the individual projects?  I'm happy to go hassle people on our side to figure out why the burst in utilization.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/facebook/rocksdb/builds/272264106
https://travis-ci.org/facebook/WebDriverAgent/builds/272251668
https://travis-ci.org/facebook/flow/builds/272259854

**Comment by BanzaiMan** [comment]
↑ Those are the ones currently holding the spots. There are many more in the queue, so the problem is likely to persist for a while.

If you can set the repository's limits, it would help. We can widen the `facebook` org's allowance, so that Linux jobs can sneak through (but this assumes that the number of Mac jobs does not increase in the meantime).

**Comment by BanzaiMan** [comment]
Hmm. These don't seem to be moving at all, even in the face of long Mac job queue. Could someone start restarting these?

**Comment by BanzaiMan** [comment]
I have increased the `facebook` organization's limit to 20 for the next 24 hours to alleviate the issue somewhat. (will be a problem again when Mac builds clog all the slots.)

**Comment by capveg** [comment]
Thank you!  Confirmed that my build is running now.  Do you have a documentation pointer for the repository limits?  I've also done an internal heads up to those projects to get humans to look at them to see what's going on.

Thanks for all of your help!

**Comment by BanzaiMan** [comment]
The limit is set according to our agreement with Facebook. I am not sure if we have an outward outlet for this information at this time.

**Comment by BanzaiMan** [comment]
I see some Mac jobs running for facebook now.

https://travis-ci.org/facebook/WebDriverAgent/jobs/272251671
https://travis-ci.org/facebook/WebDriverAgent/jobs/272251683

**Comment by beaufortfrancois** [comment]
I'm seeing the same since yesterday and I do NOT use macOS builds. Only Linux. I've tried restarting builds manually but with no luck.

https://travis-ci.org/google/WebFundamentals/builds/272449994

@BanzaiMan Is there anything I can do there?
