### ISSUE TITLE
Can't restart build

### ISSUE THREAD

**Issue by nikolas** [travis-ci/travis-ci#8356]
Hi, I'm trying to restart this failed build here:

  https://travis-ci.org/ccnmtl/ccnmtldjango/builds/272657694

When I click Restart Build, I get the "Hooray! The build was successfully restarted." alert, but nothing happens. I've tried this a bunch of times.

**Comment by BanzaiMan** [comment]
Somehow we are failing to update the job's status correctly.

```
Sep 06 21:43:33 travis-org-hub-production app/hub.3: W TID=4680 Skipped event job:restart for <Job id=272657696> trying to update state from errored to  data={:id=>"272657696", :user_id=>NNNNNN}
```

**Comment by dcastil** [comment]
I have the same problem here:

https://travis-ci.org/dcastil/concrete/builds/348261267

Instead of the log, the message `There was an error while trying to fetch the log.` shows up. Clicking onto Restart Build triggers same behaviour as in nikolas' comment.
