### ISSUE TITLE
NoMethodError: undefined method `spec' for nil:NilClass

### ISSUE THREAD

**Issue by sarangan12** [travis-ci/travis-ci#8357]
Please refer https://travis-ci.org/Azure/azure-sdk-for-ruby/builds/272666161?utm_source=github_status&utm_medium=notification. The error is happening only for ruby 2.1.5 & 2.2.0. The error is consistently happening. 

The error is happening even for a dummy fix. Refer: https://travis-ci.org/Azure/azure-sdk-for-ruby/builds/272679479?utm_source=github_status&utm_medium=notification. Locally, I have tested with the same version of rvm, ruby and bundler. The error cannot be reproduced. 

Can someone from travis CI team take a look?

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/8355.

Try updating Bundler.

**Comment by sarangan12** [comment]
On updating the bundler, the issue has been resolved. I am closing this issue
