### ISSUE TITLE
Android emulators are broken on trusty env update because avdmanager is not on PATH

### ISSUE THREAD

**Issue by ZacSweers** [travis-ci/travis-ci#8360]
Started happening recently and noticed it on a couple of different android repos

https://github.com/uber/AutoDispose/pull/71
https://github.com/JakeWharton/RxBinding/pull/404

Error is basically `Error: Target id is not valid. Use 'android list targets' to get the target ids.`

**Comment by isnifer** [comment]
Confirm [tipsi/tipsi-stripe](https://travis-ci.org/tipsi/tipsi-stripe/pull_requests)
All builds from the 1st of September are broken. I don't change any config.
![travis](https://user-images.githubusercontent.com/1788245/30165186-db61753e-93e7-11e7-85c9-b6b393bb8193.png)

**Comment by BanzaiMan** [comment]
What target ids are problematic?

**Comment by iriberri** [comment]
Hi @hzsweers and @isnifer, thanks for reporting this issue and sorry for the troubles.

First of all, and while we help you sort out this issue or any other related to the migration to the Android image in Trusty, you can specify `dist: precise` to keep your builds running in the Precise image in which they were working before.

Now, let's get to some details on the new Android image (see https://github.com/travis-ci/travis-ci/issues/5370), which was released recently.

In this update, the `android` tool has been deprecated in favor of `sdkmanager` and `avdmanager`.

Getting back to the specific error you're seeing, the old Android image in Precise came with the following targets preinstalled:

```
id: 1 or "android-10"
id: 2 or "android-15"
id: 3 or "android-16"
id: 4 or "android-17"
id: 5 or "android-18"
id: 6 or "android-19"
id: 7 or "android-20"
id: 8 or "android-21"
```

however, the Trusty image comes only with `android-25`, and other targets (such as android-21 or android-18) need to be explicitly requested in the `android.components` section, as well as the specific ABIs needed. 

For example, I made some tests on a fork of the tipsi/tipsi-stripe repository, and the build seems to be going through this step after adding the following components:

```
- android-21
- sys-img-armeabi-v7a-android-21
```
Could you please give this a try and let us know how it goes?

Thank you!

**Comment by hzsweers** [comment]
Mind taking a look at https://github.com/uber/AutoDispose/pull/79 and letting me know if you spot anything obviously wrong? I've been trying to get this working but without avail (see the recent commits on the PR for various attempts)

**Comment by hzsweers** [comment]
So it seems the crux of the issue is that the `avdmanager` binary is not getting installed, and subsequently any UI tests requiring an emulator won't work

**Comment by isnifer** [comment]
@iriberri show me how did you do that. I tried https://travis-ci.org/tipsi/tipsi-stripe/jobs/273195152 with your suggestion - problem is here

**Comment by hzsweers** [comment]
I've renamed this to be more accurate. Hope travis-ci can look into it soon as it seems to block any project using emulators :/

**Comment by isnifer** [comment]
@iriberri my problem is solved, thank you)

**Comment by BanzaiMan** [comment]
@hzsweers How about you? Is @iriberri's suggestions helpful for you?

**Comment by hzsweers** [comment]
Unfortunately not, if you look at my linked PR you'll see that was one of the things I tried in my iterations

**Comment by BanzaiMan** [comment]
It is not hard to get `avdmanager` on `$PATH` using the tools at your disposal; specifically, by using `sdkmanager`.

As I mentioned in https://github.com/travis-ci/travis-ci/issues/8155#issuecomment-318255019, we should eventually move to `sdkmanager` to manage installed components. I have a primitive working example, but it is not anywhere close to production use. I'll have to work on this a little bit before presenting as a possible replacement going forward.

So, what does that leave you now?

**If** you need `avdmanager` **NOW** and @iriberri's suggestion does not work, you can try the following:

```yaml
env:
  global:
    - ANDROID_SDK_ROOT=/opt/android  # any place `travis` can write to should work
before_install:
  - mkdir -p $ANDROID_SDK_ROOT
  # tailor the following list to your needs; `yes` below means accepting licenses.
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;26.0.1" "extras;android;m2repository"
  - export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH
```

`avdmanager` would be in `${ANDROID_SDK_ROOT}/tools/bin`.

**Comment by isnifer** [comment]
@hzsweers hey, also you can create new installation config based on our `tipsi-stripe` [config](https://github.com/tipsi/tipsi-stripe). Look into `.travis` folder and `.travis.yml` of course

**Comment by hzsweers** [comment]
That didn't work for me either. What did work for me was to actually install the tools manually, as in https://github.com/JakeWharton/butterknife/pull/1055

Does travis maintain updated example projects and docs when updating images?
