### ISSUE TITLE
IPv6 support once worked only for "sudo: false" and is now broken completely

### ISSUE THREAD

**Issue by bel2125** [travis-ci/travis-ci#8361]
While IPv6 was supported for
```
dist: precise
sudo: false
```
it seems it is not supported for
```
dist: precise
sudo: required
```

Thus, continuous integration test for a server/client software testing IPv6 connections fail, since the `sudo: required` is used default for `precise` (https://blog.travis-ci.com/2017-08-31-trusty-as-default-status). It is not possible to connect to the IPv6 loopback `[::1]` - adding `ifconfig` to the script shows IPv6 is not activated.

**Comment by BanzaiMan** [comment]
See #3302, #4964, #5200, #5261, #8304 for previous discussions concerning IPv6.

We are removing `sudo: false` support for Precise. It surprises me that you found it working somehow.

**Comment by bel2125** [comment]
> We are removing sudo: false support for Precise. 

I know, that's why created this issue. A TCP connection to the IPv6 loopback did work on `precise` + `sudo: false` for a long time, but it does not for `precise` + `sudo: required`. It seems to work again for `trusty` + `sudo: false` (but currently I need the old compiler for a month or two - see #8329).

A simple test is to just look at the result of `ifconfig`, if there is an IPv6 address or not.

> It surprises me that you found it working somehow.

Yes, it did since at least two years - I enabled the first IPv6 test on August 13 2015 [here](https://github.com/civetweb/civetweb/commit/0839ca8b29eff01c9f2267ff160f731f2bf3d0d0#diff-354f30a63fb0907d4ad57269548329e3), and it worked ever since.

I don't need full IPv6 to communicate to an outside test server - just a loopback test to [::1] (the IPv6 equivalent of 127.0.0.1) is done. This is independent from the network infrastructure provider, if it's just a local network - e.g., a virtual network in the virtualisation environment (VMware host only adapter, VirtualBox adapter, ... whatever you use). So if the "sudo: required" containers run on a different infrastructure than the "sudo: false" build VMs, it's technically reasonable these two environments behave differently regarding IPv6.

Unfortunately,  `precise` + `sudo: required` is not a full replacement for  `precise` + `sudo: false`, for a server/client software using IPv6 at the moment.

**Comment by BanzaiMan** [comment]
I see. You just want the IPv6 loopback. Please try `dist: trusty` + `sudo: false`. This would send your job to the same infrastructure as `dist: precise` + `sudo: false`, and may work.

**Comment by bel2125** [comment]
As already mentioned: `dist: trusty` + `sudo: false` works from the IPv6 point of view.
But it does not from the compiler point of view (see #8329).

It seems, the only working combination is being discontinued:

. |dist:precise|dist:trusty
--|--|--
**sudo:false**| :white_check_mark: worked :+1: ... but is discontinued :cry: |:x: need to downgrade compiler ([#8829](https://github.com/travis-ci/travis-ci/issues/8329)), solution was to specify `precise`
**sudo:required**|:x: IPv6 not working (#8361)| :interrobang: not tested, but most likely affected by both issues

**Comment by bel2125** [comment]
Is there a way to combine different images in the same .travis.yml file - run some tests on `trusty` and another with different settings one `precise`?

**Comment by BanzaiMan** [comment]
If you can split the tests into 2 suites, you can specify:

```yaml
dist: trusty
sudo: false
script:
  - RUN_TEST_FOR_TRUSTY
matrix:
  include:
    - dist: precise
      sudo: required
      script: RUN_TEST_FOR_PRECISE
```

**Comment by bel2125** [comment]
Thank you, this file seems to work. But it seems, the C language support for **trusty** is somewhat less stable than for **precise** - since ***sporadically*** the compiler is not found: e.g., [here](https://travis-ci.org/civetweb/civetweb/jobs/273256461#L869), [here](https://travis-ci.org/civetweb/civetweb/jobs/273256557#L867), [here](https://travis-ci.org/civetweb/civetweb/jobs/273239782#L812), [here](https://travis-ci.org/civetweb/civetweb/jobs/273239874#L816), [here](https://travis-ci.org/civetweb/civetweb/jobs/273008261#L816), [here](https://travis-ci.org/civetweb/civetweb/jobs/273008394#L816) and many others during the last builds:

```
 The CMAKE_C_COMPILER:

    /usr/local/clang-3.5.0/bin/clang

  is not a full path to an existing compiler tool.
```


---

And just for completeness:

The combination **sudo: required** + **dist: trusty** is indeed affected by both problems - your build environment with **sudo: required** seems to be configured with even IPv6 loopback disabled, so unfortunately it's not **sudo: required** is not a full replacement for **sudo: false** ([from your blog](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status)):

. |dist:precise|dist:trusty
--|--|--
**sudo:false**| :white_check_mark: worked :+1: ... but is discontinued :cry: |:x: need to downgrade compiler ([#8829](https://github.com/travis-ci/travis-ci/issues/8329)), solution was to specify `precise`
**sudo:required**|:x: IPv6 not working (#8361)| :x: tested, affected by  [#8829](https://github.com/travis-ci/travis-ci/issues/8329) and [#8361](https://github.com/travis-ci/travis-ci/issues/8361)

**Comment by pitrou** [comment]
Hello, IPv6 loopback does not seem to work anymore on `dist: trusty` + `sudo: false`. See example here:
https://travis-ci.org/tornadoweb/tornado/jobs/296257095#L1294-L1306

**Comment by bel2125** [comment]
I can confirm: 
While my IPv6 tests worked some days ago, they stopped working.
A week ago, the `ifconfig` in my build script showed an [IPv6 address](https://travis-ci.org/civetweb/civetweb/jobs/294261624#L657), while in a current build there is [no IPv6 address](https://travis-ci.org/civetweb/civetweb/jobs/297274651#L656).

**Comment by bakwc** [comment]
I have the same issue, #8695, seems like IPv6 was broken few days ago.

**Comment by agauniyal** [comment]
isn't there a way to mock ipv6 loopback address somehow? Most of us just need to run tests concerning ipv6 and don't need an actual connection to outside service.

**Comment by bel2125** [comment]
> isn't there a way to mock ipv6 loopback address inside travis container somehow, maybe with some combination of docker or some linux hack :thinking: ? Most of us just need to run tests concerning ipv6 and don't need an actual connection to outside service.

I checked the settings:

      ifconfig
      cat /etc/sysctl.conf
      cat /etc/network/interfaces
      uname -a
      lsb_release -a

(results: see [here](https://travis-ci.org/civetweb/civetweb/jobs/303221633#L671) and [here](https://travis-ci.org/civetweb/civetweb/jobs/303189575#L676))
and I tried to activate IPv6 this way:

      echo "iface lo inet6 loopback" | sudo tee -a /etc/network/interfaces
      sudo service network-manager restart
      sudo service networking restart      (as an alternative command)

But it seems restarting the network does not work this way (see [here](https://travis-ci.org/civetweb/civetweb/jobs/303221633#L742)), so I don't know if this is the right approach (at least I tried ...).  

I don't know other IPv6 tweaks .. maybe someone else does.

**Comment by GiedriusM** [comment]
Not 100% sure if it's the same issue, but adding 
```
before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
``` 
to `.travis.yml` seems to have fixed the issue for node-coap (https://github.com/mcollina/node-coap/commit/7bd04d8104a2b663f6a461ca6f10a9e8d394d51d) builds.

**Comment by bel2125** [comment]
@GiedriusM - this did the job for Linux in the `sudo: required` environment. It must not be set for OSX, so I the following lines, and [everything worked again](https://travis-ci.org/civetweb/civetweb/builds/314042341):
```
before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
```

This seems to work (at least at the moment) - thanks!

@BanzaiMan - I would appreciate if there is some official commitment to **IPv6 loopback** as a feature, that will be supported in future images as well, and I'm sure others will appreciate this as well (#8693, #8695, #8711, #8755).

**Comment by GiedriusM** [comment]
@bel2125, at least in my case, it seems to work for `sudo: false` as well. But yeah, this fix is intended for linux platforms, as OSX already has IPv6 support.

**Comment by bel2125** [comment]
> it seems to work for sudo: false as well. 

Really? It uses **`sudo`**` sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'`, and (as to my knowledge) you can't edit this file without `sudo`, and (according to the [documentation](https://docs.travis-ci.com/user/reference/overview/)) in container environment with `sudo: false` sudo commands are not available.

**Comment by GiedriusM** [comment]
Check https://travis-ci.org/mcollina/node-coap/jobs/313099300/config. If before_script command is removed - the tests will fail (i.e. they failed before adding it). Even better - try it on your build.

When looking for a workaround, I've though that `sudo: required` must be used, but out of curiosity tested it with `sudo: false` and since it's faster and works - hooray for me. Maybe sudo is limited to `script` section, but that's more of a question for Travis team.

**Comment by GiedriusM** [comment]
@bel2125, apparently `sudo: false` is still a VM and not a docker. Testing all suggestions in https://stackoverflow.com/questions/20010199/determining-if-a-process-runs-inside-lxc-docker indicates that it is not running in a docker environment. See https://travis-ci.org/GiedriusM/travis-test/jobs/314078651 for my tests.
