### ISSUE TITLE
Tagging existing commit should not cause new build

### ISSUE THREAD

**Issue by hmottestad** [travis-ci/travis-ci#8362]
Since #1532 is locked I would like to report that this is still an issue.

I just kicked off 50 odd builds while experimenting with tags, and I intend to have travis tag builds that it deploys to docker hub which will cause a nice endless loop of builds.

Any chance there been any progress since this issue was first reported 4 years ago?

**Comment by BanzaiMan** [comment]
Thanks for the ping.

We are making progress on #1532, but we have nothing to really share.

**Comment by BanzaiMan** [comment]
I'm closing this now.

**Comment by hmottestad** [comment]
@BanzaiMan can you at least unlock #1532 so that people can discuss workarounds?
