### ISSUE TITLE
creating travis user in mysql stopped working

### ISSUE THREAD

**Issue by JoshuaWise** [travis-ci/travis-ci#8364]
we have this in our `.travis.yml` under `before_install`:
```
mysql -u root -e "CREATE USER 'travis'@'localhost'; GRANT ALL ON *.* TO 'travis'@'localhost'; FLUSH PRIVILEGES;"
```

It always used to work without issues, but today our builds are all failing with this error:
```
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'travis'@'localhost'

The command "mysql -u root -e "CREATE USER 'travis'@'localhost'; GRANT ALL ON *.* TO 'travis'@'localhost'; FLUSH PRIVILEGES;"" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by JoshuaWise** [comment]
Adding `group: deprecated-2017Q3` to the travis file fixed it

**Comment by Lyoness** [comment]
Hi @JoshuaWise thanks for reporting.  The build environment update actually [grants these mysql permissions by default now](https://github.com/travis-ci/travis-cookbooks/pull/881/files), which is likely the reason your build errored. 

https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/
we can explicitly add this to update the docs as well.  

 You indeed can roll back to the deprecated group, or your can omit that `before_install` and test again.

**Comment by JoshuaWise** [comment]
Ahh okay, thanks for the info
