### ISSUE TITLE
Wrong php_dir for PEAR in pre-installed PHP runtimes

### ISSUE THREAD

**Issue by plessbd** [travis-ci/travis-ci#8365]
It seems either the php include path is missing the correct pear installation, or the pear installation is pointed at the wrong directory.

7.0.7
https://travis-ci.org/plessbd/xdmod/jobs/272951727#L468

https://travis-ci.org/plessbd/xdmod/jobs/272951727#L480

7.1.6
https://travis-ci.org/plessbd/xdmod/jobs/272951729#L471

https://travis-ci.org/plessbd/xdmod/jobs/272951729#L483

my current workaround which I do not like is
`pear config-set php_dir $(php -r 'echo substr(get_include_path(),2);')`

**Comment by BanzaiMan** [comment]
We've just updated our images to point `7.0` to `7.0.22` https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/#Changed. Please restart the `7.0` jobs again to see if this is acceptable.

**Comment by plessbd** [comment]
Same issue with 7.0.22

5.4
https://travis-ci.org/plessbd/xdmod/jobs/273306690#L473

7.0.22
https://travis-ci.org/plessbd/xdmod/jobs/273306693#L467

7.1.16
https://travis-ci.org/plessbd/xdmod/jobs/273306718#L475

**Comment by BanzaiMan** [comment]
Thanks for checking.

**Comment by BanzaiMan** [comment]
I think the problem lies with the use of pre-installed PHP runtimes (`7.0` is, but `7.1` is not—it is dynamically fetched and installed). The archives include `~/.pearrc`, which I believe contains consistent configuration, but the build image does not.

7.0.21, for example, then, should work as you expect.

This needs to be fixed, obviously, but the remedy is not clear to me yet.

**Comment by BanzaiMan** [comment]
Incidentally, `7.1` is actually pre-installed. However, it is the last one installed and the default, so it actually works.

**Comment by BanzaiMan** [comment]
With the current PR, the config would look something like [this](https://staging.travis-ci.org/BanzaiMan/travis_staging_test/jobs/632046#L423-L467):

```sh-session
$ pear config-show
Configuration (channel pear.php.net):
=====================================
Auto-discover new Channels     auto_discover    1
Default Channel                default_channel  pear.php.net
HTTP Proxy Server Address      http_proxy       <not set>
PEAR server [DEPRECATED]       master_server    pear.php.net
Default Channel Mirror         preferred_mirror pear.php.net
Remote Configuration File      remote_config    <not set>
PEAR executables directory     bin_dir          /home/travis/.phpenv/versions/7.0/bin
PEAR documentation directory   doc_dir          /home/travis/.phpenv/versions/7.0/docs
PHP extension directory        ext_dir          /home/travis/.phpenv/versions/7.0.22/lib/php/extensions/no-debug-zts-20151012
PEAR directory                 php_dir          /home/travis/.phpenv/versions/7.0/share/pear
PEAR Installer cache directory cache_dir        /tmp/pear/cache
PEAR configuration file        cfg_dir          /home/travis/.phpenv/versions/7.0/cfg
directory
PEAR data directory            data_dir         /home/travis/.phpenv/versions/7.0/data
PEAR Installer download        download_dir     /tmp/pear/install
directory
Systems manpage files          man_dir          /home/travis/.phpenv/versions/7.0/man
directory
PEAR metadata directory        metadata_dir     <not set>
PHP CLI/CGI binary             php_bin          /home/travis/.phpenv/versions/7.0.22/bin/php
php.ini location               php_ini          /home/travis/.phpenv/versions/7.0.22/etc/php.ini
--program-prefix passed to     php_prefix       <not set>
PHP's ./configure
--program-suffix passed to     php_suffix       <not set>
PHP's ./configure
PEAR Installer temp directory  temp_dir         /tmp/pear/install
PEAR test directory            test_dir         /home/travis/.phpenv/versions/7.0/tests
PEAR www files directory       www_dir          /home/travis/.phpenv/versions/7.0/www
Cache TimeToLive               cache_ttl        3600
Preferred Package State        preferred_state  stable
Unix file mask                 umask            22
Debug Log Level                verbose          1
PEAR password (for             password         <not set>
maintainers)
Signature Handling Program     sig_bin          /usr/bin/gpg
Signature Key Directory        sig_keydir       /home/travis/.phpenv/versions/7.0.22/etc/pearkeys
Signature Key Id               sig_keyid        <not set>
Package Signature Type         sig_type         gpg
PEAR username (for             username         <not set>
maintainers)
User Configuration File        Filename         /home/travis/.pearrc
System Configuration File      Filename         /home/travis/.phpenv/versions/7.0.22/etc/pear.conf
```

`/home/travis/.phpenv/versions/7.0` is a symbolic link to `/home/travis/.phpenv/versions/7.0.22`, so this should be OK.

**Comment by BanzaiMan** [comment]
The PR has been merged and deployed. I'm closing this optimistically, but if you continue to see problems, do let us know.
