### ISSUE TITLE
Compile error with 5.24.2

### ISSUE THREAD

**Issue by ylavoie** [travis-ci/travis-ci#8366]
Although 5.24.2 is installed, Perl still points to 5.24.1 and fail on invocation. See https://travis-ci.org/ledgersmb/LedgerSMB/jobs/272958923#L992

**Comment by BanzaiMan** [comment]
Your cache [contains `/home/travis/locallib`](https://travis-ci.org/ledgersmb/LedgerSMB/jobs/272958923#L599), which appears to have bad shebang line https://travis-ci.org/ledgersmb/LedgerSMB/jobs/272958923#L991. Please delete cache and try again.

**Comment by ylavoie** [comment]
Working. I wonder why changing Perl from 5.24.1 to .2 didn't invalidate the cache.

**Comment by BanzaiMan** [comment]
Because `.1` is not a part of your configuration.

Closing.
