### ISSUE TITLE
Job failed without producing any logging information

### ISSUE THREAD

**Issue by jugglinmike** [travis-ci/travis-ci#8370]
A recent build on an open source project failed without producing any logging information. I'm inclined to believe this was a hiccup, but I thought I would report it here just in case it is indicative of some larger trend.

Unfortunately, due to the absence of logging information, I don't have much data to report beyond a link to the failed job itself:

https://travis-ci.org/jshint/jshint/jobs/271458919

Here's the pull request that triggered it:

https://github.com/jshint/jshint/pull/3180

Thanks for the great service!

**Comment by jugglinmike** [comment]
Here's the raw log: https://api.travis-ci.org/jobs/271458919/log.txt?deansi=true

**Comment by BanzaiMan** [comment]
Looks like it took a little while to archive the logs. It is visible now in its entirety.

**Comment by BanzaiMan** [comment]
I'm closing this, but if you see the problem again, let us know.
