### ISSUE TITLE
Can you give me a help to setup my own travis-ci server with source in https://github.com/travis-ci/travis-ci

### ISSUE THREAD

**Issue by lifubang** [travis-ci/travis-ci#8371]
I try to setup my own travis-ci server.
The travis-build and worker project can work normally.
The travis-web and travis-api also can work, and I can login from github.com, but I don't know how to sync my github respository to travis-web.
I try to run sidekiqs, but the queue name is queue:default, not queue.sync, and the class name Travis::GithubSync::SyncUser can't find in any project.

help me.

**Comment by BanzaiMan** [comment]
At this time, we do not offer any support for setting up our services elsewhere.

If you are interested in on-premises CI product, we offer Travis Enterprise https://enterprise.travis-ci.com/. Please email us at enterprise@travis-ci.com.
