### ISSUE TITLE
No space left on device after trusty upgrade

### ISSUE THREAD

**Issue by stephengroat** [travis-ci/travis-ci#8375]
This only started happening after the trusty upgrade #8315 

Tracking for termux in https://github.com/termux/termux-packages/issues/1403

Happens on all prs in https://github.com/termux/termux-packages while building (early on in the build process)

https://travis-ci.org/termux/termux-packages/builds/273317698?utm_source=github_status&utm_medium=notification

```
Traceback (most recent call last):
  File "/home/builder/lib/android-ndk/build/tools/make_standalone_toolchain.py", line 642, in <module>
    main()
  File "/home/builder/lib/android-ndk/build/tools/make_standalone_toolchain.py", line 626, in main
    sysroot_path, args.stl, host_tag, args.unified_headers)
  File "/home/builder/lib/android-ndk/build/tools/make_standalone_toolchain.py", line 432, in create_toolchain
    copy_directory_contents(prebuilt_path, install_path)
  File "/home/builder/lib/android-ndk/build/tools/make_standalone_toolchain.py", line 180, in copy_directory_contents
    shutil.copy2(src_file, dst_dir)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib/python2.7/shutil.py", line 52, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
Error building metasploit-framework
```

**Comment by cmnbroad** [comment]
We ran into a similar issue on our trusty/sudo-enabled builds after the upgrade (running out of device space when we previously didn't).

**Comment by cmnbroad** [comment]
@stephengroat You might be able to try requesting the old image as described [here](https://blog.travis-ci.com/2017-08-29-trusty-image-updates) (it worked as a temporary solution for us).

**Comment by stephengroat** [comment]
thanks @cmnbroad. that temporary fix seems to work for termux-packages too. wondering what the underlying issue is

**Comment by cmnbroad** [comment]
Any update on this ? We're unable to use the new image since its to small. How long will we be able to opt-out and use the old one ? What other options are available ?

**Comment by stephengroat** [comment]
@cmnbroad issue seems to have resolved itself for me, have you tried within the last day or so?

i was thinking about closing this, but if you're still having issues, i'll leave it open

**Comment by cmnbroad** [comment]
Ah, thanks - I haven't tried lately but will do so today.

**Comment by cmnbroad** [comment]
It seems to be working for us now.

**Comment by stephengroat** [comment]
closing since all affected seem to have the problem solved

**Comment by palewire** [comment]
I am having this issue right now.

**Comment by izhangzhihao** [comment]
`group: deprecated-2017Q3` does not work for me. Still got `No space left on device` error from [#245 errored](https://travis-ci.org/izhangzhihao/intellij-rainbow-brackets/builds/359675450)
