### ISSUE TITLE
Debug button no longer appears

### ISSUE THREAD

**Issue by gbrener** [travis-ci/travis-ci#8377]
Browser: Chrome Version 60.0.3112.101 (Official Build) (64-bit)
OS: macOS Sierra 10.12.4

Today I noticed that the <kbd>Debug</kbd> button no longer appears for failed builds on travis-ci.org. This is making it quite difficult to debug CI failures (related issue: https://github.com/travis-ci/travis-ci/issues/8374).

**Comment by BanzaiMan** [comment]
We never offered Debug button on https://travis-ci.org. Debug builds need a feature flip on the repository, and an API call.

**Comment by gbrener** [comment]
Right - this is on a repository that should have the feature enabled, as it was available yesterday and many days before.

**Comment by gbrener** [comment]
I see - the PR on GitHub is now building the project on https://travis-ci.org, even though it was previously building on https://travis-ci.com. There was probably a configuration change that caused this. Either way the issue is not with the website, so I'm closing.
