### ISSUE TITLE
Sonarcloud addon fails to setup on build

### ISSUE THREAD

**Issue by djohns451** [travis-ci/travis-ci#8379]
The build in question is a fix for a few typos in a comment. The SonarCloud addon fails to unpack or download, then when the script attempts to execute the scanner, the build fails because the scanner doesn't exist.

https://travis-ci.org/SonarSource/sq-com_example_standard-sqscanner-travis/jobs/273378432

The Travis configuration is identical to previous successful builds.

**Comment by DrTorte** [comment]
Hi there @djohns451, just wanted to let you know that we've looked this over and the SonarSource addon only works with Internal Pull Requests at this point.

**Comment by BanzaiMan** [comment]
We've updated the documentation for a little more clarity: https://docs.travis-ci.com/user/sonarcloud/#Activation-for-internal-pull-requests

**Comment by colombod** [comment]
I am following the documentation, but in my build, I get sonar-scanner not found

this is the Travis [report](https://travis-ci.org/OmniSharp/omnisharp-vscode/builds/393892386?utm_source=github_status&utm_medium=notification)

**Comment by colombod** [comment]
I think we need to reopen the issue

**Comment by colombod** [comment]
@klougit I open #9791
