### ISSUE TITLE
Trusty update: `pip install conan` now fails

### ISSUE THREAD

**Issue by fosterbrereton** [travis-ci/travis-ci#8382]
Our running of `pip install conan`, which used to succeed before, has started to fail. A log where the error can be seen is [here](https://travis-ci.org/stlab/libraries/jobs/273078954). The new error that's cropped up is:
```shell
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/jwt'
```

**Comment by fosterbrereton** [comment]
I've also posted a comment about this issue in #8315.

**Comment by fosterbrereton** [comment]
(BTW, a workaround was to call `sudo pip`, but I wouldn't consider that a viable long-term fix.)

**Comment by bogdanap** [comment]
Hi,

With the new image updates we've cleanup up some things around our Python environment setup.
This means that `pip install` will work as before inside a virtualenv (assuming you're using language:python). 
Since it looks like that's not the case, I'd suggest using `pip install --user`.

**Comment by fosterbrereton** [comment]
Great - thank you for that information, I'll give it a try.

**Comment by pbarnum** [comment]
Adding the `--user` flag fixed the issue for me since I was using `language: node_js`

**Comment by BanzaiMan** [comment]
Can this be closed? Perhaps improve documentation as well?

**Comment by BanzaiMan** [comment]
Closing as a duplicate of #8378.
