### ISSUE TITLE
ssh_known_hosts addon cannot use environment variables

### ISSUE THREAD

**Issue by yaseen95** [travis-ci/travis-ci#8386]
The ssh_known_hosts step runs before the environment variables are set. In one of my projects I've defined SERVER environment variable and am using it in both after_success and deploy stages.

I've created a sample project to showcase this behaviour here:
https://github.com/yaseen95/travis-ci-known-hosts-env-var

And the travis builds are here
https://travis-ci.org/yaseen95/travis-ci-known-hosts-env-var

As you can see looking at the logs, ssh_known_hosts runs before the environment variables are set.

**Comment by BanzaiMan** [comment]
This is a variation of #7043. I'm closing this as such.
