### ISSUE TITLE
env var precedenece- matrix cannot override global?

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#8387]
I have the following build matrix:

    env:
      # run composer by default
      global:
        - DB=mysql
        - DEPENDENCIES=standard
        - APC=true
        - TRAVIS_TEST_EXCLUDES="--exclude-group slow,jpgraph,pushserver"

    matrix:
      include:
        # pgsql
        - php: 5.6
          env: DB=pgsql
        # pgsql
        - php: 5.6
          env: DB=sqlite
        # httpd-based
        - php: 5.6
          env: DB=mysql TEST_COMPONENT=HTTPD
        # push-server
        - php: 5.6
          env: DB=mysql TEST_COMPONENT=PUSH_SERVER
        # from..to
        - php: 5.6
          env: DB=mysql DEPENDENCIES=lowest
        # jslint-only
        - php: 5.6
          env: DB= DEPENDENCIES= JSLINT=true

Typically all jobs require a database (mostly mysql). Only the linting job only uses Javascript. I was expecting `env: DB=` to remove the global DB variable (i.e. `global` is the default but not _always_ applied) but it doesn't:

	$ export DB=mysql
	$ export DEPENDENCIES=standard
	$ export APC=true
	$ export TRAVIS_TEST_EXCLUDES="--exclude-group slow,jpgraph,pushserver"
	$ export JSLINT=true

Is this a mistake or am I trying to approach this the wrong way?

Would it make sense- even if an enhancement- to allow matrix settings to override global vars?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by andig** [comment]
Take this for example: https://travis-ci.org/andig/volkszaehler.org/jobs/273573757#L428 with the corresponding `.travis.yml` here: https://github.com/andig/volkszaehler.org/blob/9ab5561654427e01069150f69aba76535b87c5ce/.travis.yml#L42

**Comment by BanzaiMan** [comment]
The assignments of the form `VAR=` is ignored at the moment. You can either `unset VAR` later, or try `VAR=""`.

**Comment by andig** [comment]
Good to know, thank you. Might be worth adding to the docs.

**Comment by BanzaiMan** [comment]
We'll fix it soon.
