### ISSUE TITLE
Build icon shows 'failing' but all builds seem succesful

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-interxion** [travis-ci/travis-ci#8389]
Using the IMAGE URL as given by Travis  
`https://travis-ci.org/AqoviaElements/properties-from-ancestor-behavior.svg?branch=master`  

I see <img src="https://user-images.githubusercontent.com/17986727/30239464-18696824-9555-11e7-87fe-9da6d58c28d2.png" width="68"> here:

![icon](https://travis-ci.org/AqoviaElements/properties-from-ancestor-behavior.svg?branch=master)

But the project doesn't have [any failing builds](https://travis-ci.org/AqoviaElements/properties-from-ancestor-behavior/branches)

And interestingly, the tooltip on the failing icon in Travis seems to be correct:

<img src="https://user-images.githubusercontent.com/17986727/30239424-28e166f8-9554-11e7-954b-b9f167e122db.png" width="300">

**Comment by BanzaiMan** [comment]
I saw this on your page, too. When I click on the badge and bring up the modal dialog box, the badge changed to green. Do you see this, too?

**Comment by slawomir-brzezinski-at-interxion** [comment]
Correct! It changes after clicking:
<img src="https://user-images.githubusercontent.com/17986727/30242266-249542d6-958b-11e7-8f03-32c57ba74697.png" width="250">

**Comment by jean-moldovan** [comment]
Same here. Badge on the travis page changes after clicking, badge on the repo readme remains `build error`, even though last build was successful

`https://api.travis-ci.org/jean-moldovan/instagramjs.svg?branch=master` returns `build error` badge.

**Comment by slawomir-brzezinski-at-interxion** [comment]
Well, looking at mine now (first comment) it seems fine, so I am unfollowing for now, but @jean-moldovan 's case shows the underlying issue is still not fixed so ticket should stay open.

Travis-ci team: I think you've got a good opportunity to investigate this no, or else it will haunt you many times to waste your time.

**Comment by jean-moldovan** [comment]
Okay, looks like mine went back to normal too after retriggering build a couple of times

**Comment by wltjr** [comment]
I think they might be seeing the badge remaining on a failed build, after the next build passes.

1. View a travis build that failed
2. Stay on that page and push a commit that passes
3. Build passes but page still shows failed, as seen in following screenshot

![shot-2018-03-05_21-42-42](https://user-images.githubusercontent.com/12835340/37011438-2df15fcc-20be-11e8-89a2-a346c8f29ead.jpg)

Basically the badge does not refresh when the next build passes. It stays on failed till you refresh the page after a build passes.

**Comment by happilymarrieddad** [comment]
Mine just did this. Thanks!

**Comment by ctkelley** [comment]
It's been happening to me for the last couple days. This issue does not seem to be going away.

**Comment by Sarani1612** [comment]
Happening to me at the moment

**Comment by ta0kira** [comment]
Having the same issue with https://travis-ci.org/github/ta0kira/zeolite and https://github.com/ta0kira/zeolite. The tests have been passing for 10h but the embedded badge still shows "build error".

**Comment by ta0kira** [comment]
I wonder if the problem is the browser caching the image, at least for the embedded badge. I see "build passing" on my laptop and "build error" on my phone.

**Comment by firefelix** [comment]
I have this issue here:
[dsouvage-homepage](https://github.com/firefelix/dsouvage-homepage)

Shows failing/passing randomly on different devices.

**Comment by ilanpillemer** [comment]
happening to me too.
https://github.com/ilanpillemer/health
https://travis-ci.org/ilanpillemer/health.svg?branch=master

**Comment by LandonTClipp** [comment]
Happening to another package:

https://github.com/vektra/mockery

**Comment by jhildenbiddle** [comment]
Same here. Tested in two browsers (Chrome 81 and Safari Technology Preview 105).

https://github.com/jhildenbiddle/css-vars-ponyfill
https://travis-ci.org/jhildenbiddle/css-vars-ponyfill

<img width="1125" alt="Screen Shot 2020-05-13 at 10 55 14 AM" src="https://user-images.githubusercontent.com/442527/81835754-3d5cf280-9508-11ea-9a1d-a2302002d657.png">

**Comment by mrunalk** [comment]
Same here, shows failing on the repo here, https://github.com/rollbar/rollbar-php even though it's passing on master. Please fix the issue.

**Comment by rehmanuet** [comment]
Facing the same issues on https://travis-ci.org/github/rehmanuet/Puppeteer-Headless-Automation/builds/686960528
Please resolve this

**Comment by biona001** [comment]
Happening to me too at https://travis-ci.org/OpenMendel/VCFTools.jl. Clicking the icon doesn't help.

**Comment by PepoBJ** [comment]
I have the same problem, clicking the icon does not work

**Comment by aamironline** [comment]
It is happening here too -> https://github.com/maniartech/InternetObject-js

**Comment by zemse** [comment]
Just go to your browser's preferences and clear cached web content (no need to clear history or cookies).

**Comment by joancolmenerodev** [comment]
Solved it with `command` + `shift` + `DEL` and selecting only `Cached images and files` after that, reload the pages.

**Comment by moutonjr** [comment]
Hello,
Mine as well, though testing with another browser, or clearing browser's cache didn't do the trick...
![Screenshot_20200609-081356](https://user-images.githubusercontent.com/16349417/84112506-305cf180-aa29-11ea-8add-be7622c18888.jpg)

Travis-CI team: any chance that you could answer your issues ? Please reopen...

**Comment by InanisV** [comment]
Sometimes the problem actually occurs. But sometimes it may be caused by the case that browser buffer is not cleared and Chrome displays the repo page with outdated buffer.

**Comment by eyas-ranjous** [comment]
+1. the problem is still happening. Suddenly the icon changes to "Failing" despite all builds passing.

**Comment by jhildenbiddle** [comment]
Per this repo's README:

<img width="883" alt="Screen Shot 2020-06-22 at 1 13 05 PM" src="https://user-images.githubusercontent.com/442527/85321474-51dac600-b48a-11ea-8904-4b5500a3b4eb.png">

Looks like the recent issues described here should be posted here instead: https://travis-ci.community

**Comment by WolfgangFahl** [comment]
This issue is closed but i couldn't find a clue for a solution. Doesn't this need to be reopened then?

**Comment by WolfgangFahl** [comment]
see also https://stackoverflow.com/questions/33011816/why-travis-ci-org-always-show-build-failing-badge/62737244#62737244

**Comment by moutonjr** [comment]
Got issue #8389 opened as well, will close.
Travis team, please get into your issues! :@

**Comment by rmcgirr83** [comment]
Yeah it's still failing.  The svg is being displayed properly on travis as passing but linking on other website shows as build error.  Travis is becoming a real inconvenience.

**Comment by trobe026** [comment]
> I think they might be seeing the badge remaining on a failed build, after the next build passes.
> 
> 1. View a travis build that failed
> 2. Stay on that page and push a commit that passes
> 3. Build passes but page still shows failed, as seen in following screenshot
> 
> ![shot-2018-03-05_21-42-42](https://user-images.githubusercontent.com/12835340/37011438-2df15fcc-20be-11e8-89a2-a346c8f29ead.jpg)
> 
> Basically the badge does not refresh when the next build passes. It stays on failed till you refresh the page after a build passes.

Refreshing the page after the build passes changes nothing.

**Comment by moutonjr** [comment]
Hey, can Travis Dev team can take a look at this heisenbug? It's there for sure a long time without update and this is really inconvenient.

**Comment by WolfgangFahl** [comment]
There seems to be nobody relevant listening here anymore see #10529 and https://travis-ci.community/t/do-not-ignore-github-issues/10478

**Comment by rmcgirr83** [comment]
Unreal, did Idera fire EVERYONE?
