### ISSUE TITLE
Building rkt container: systemd-nspawn: unrecognized option '--setenv'

### ISSUE THREAD

**Issue by taqtiqa-mark** [travis-ci/travis-ci#8393]
Hi,
I'm encountering this error when I try to build a Rkt container within Travis-CI.
see, line 996 here:
https://travis-ci.org/taqtiqa/rkt-base/jobs/273761193

I have logged an issue with [containers](https://github.com/containers/build/issues/324)

Unfortunately, I'm not 100% sure where responsibility lies.....
I do know that this script runs fine on my desktop (Xenial).

Appreciate any hints or tips.  Especially, an opinion on which project wants to own this issue.

**Comment by BanzaiMan** [comment]
The error is coming from this command: `/bin/acbuild --debug run -- groupadd -g 1000 rstudio`, which almost certainly is not something we provide out of the box. It appears to me that you are installing tools necessary for your build, so I am afraid there is not very much we can do here.

I'd check the versions of the software you are installing, and how they interact with each other. Our images run on Trusty. Perhaps you have better luck if you test it with our Docker image: https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

We can also turn on the debug feature for your repo, if you wish: https://docs.travis-ci.com/user/running-build-in-debug-mode/#Restarting-a-job-in-debug-mode

**Comment by taqtiqa-mark** [comment]
This is an issue with the container build tools.  In the case of the `acbuild` tool, try use the chroot engine.
