### ISSUE TITLE
build of git tag no longer consider a tag after restart

### ISSUE THREAD

**Issue by SingingBush** [travis-ci/travis-ci#8398]
I'm using build stages and had to restart this build https://travis-ci.org/intellij-dlanguage/intellij-dlanguage/builds/273731440

It's building a git tag and the _Deploy new release_ normally runs when it detects that it's a tag, however in the log I'm seeing `Skipping a deployment with the script provider because this branch is not permitted` whereas usually the stage runs fine after doing a tag.

**Comment by BanzaiMan** [comment]
Regrettably we no longer have the build log when you ran it the first time, but I am having a hard time reasoning that there was a release then.

The commit that triggered this build has this `.travis.yml`, which indicates that the deployment happens only on the `release` branch for the `Deploy new release` stage: https://github.com/intellij-dlanguage/intellij-dlanguage/blob/cdf21c28800da25394060901b1f83c92a1b39424/.travis.yml#L44-L52

The tag name is `v1.13.1`, which does not match. Hence there should _not_ be a release.

The last (and only) build on the `release` branch is https://travis-ci.org/intellij-dlanguage/intellij-dlanguage/jobs/255470195#L597, which correctly started it.

**Comment by SingingBush** [comment]
sorry for taking your time. It's been a while since last release and I completely forgot about doing this https://github.com/intellij-dlanguage/intellij-dlanguage/commit/6add978235f9fa39d403ef8757038141ac7d6a90
