### ISSUE TITLE
We couldn't find the repository limonte/sweetalert2

### ISSUE THREAD

**Issue by limonte** [travis-ci/travis-ci#8403]
![](https://i.imgur.com/t21IdQW.png)

https://travis-ci.org/limonte/sweetalert2

It's weird because on this page https://travis-ci.org/profile/limonte I can see it enabled:

![](https://i.imgur.com/GaKmJTW.png)

**Comment by limonte** [comment]
Repo does exist of course: https://github.com/limonte/sweetalert2

**Comment by limonte** [comment]
The build badge is currently grey :(

https://i.imgur.com/A2iRv2o.png

**Comment by BanzaiMan** [comment]
Everything seems to be in order now. Could you confirm?

**Comment by limonte** [comment]
Yup, everything is fine now. Thanks!
