### ISSUE TITLE
travis-build: Recent change to environment variable expansion breaks build.

### ISSUE THREAD

**Issue by Jasu** [travis-ci/travis-ci#8404]
[Commit ad9af8bdbf354fd8c68cf604a798c080671e20c4](https://github.com/travis-ci/travis-build/commit/ad9af8bdbf354fd8c68cf604a798c080671e20c4) breaks the build in the following case:

Partial .travis.yml:

    env:
      global:
        - APP_HOST=www.example.com
        - APP_URL=http://$APP_HOST:8080

Output from Travis before:

    Setting environment variables from .travis.yml
    $ export APP_HOST=www.example.com
    $ export APP_URL=http://$APP_HOST:8080

Output from Travis after:

    Setting environment variables from .travis.yml
    $ export APP_HOST=www.example.com
    $ export APP_URL=http://

Specifically, I believe that the [following line in the regex ](https://github.com/travis-ci/travis-build/commit/ad9af8bdbf354fd8c68cf604a798c080671e20c4#diff-fb2f2b328ee88169483a0d9307d2751eR17)matches until the $ and discards the rest:

    [^"'`\$\ ]+ # some bare word, not containing ", ', `, or $

**Comment by BanzaiMan** [comment]
Thanks for the report. Indeed, this is a case I did not consider. Will fix soon.

**Comment by BanzaiMan** [comment]
Strange, it should be matched by the previous one: `\$\S*`.

**Comment by BanzaiMan** [comment]
Ah. right. `$` appears in the middle.

**Comment by BanzaiMan** [comment]
Affected builds can be restarted.
