### ISSUE TITLE
Cannot deploy .net core 2 to GitHub Release

### ISSUE THREAD

**Issue by sebagomez** [travis-ci/travis-ci#8405]
Hi @joshua-anderson @akoeplinger and @nterry
I'm trying to publish my assemblies to GitHub Releases but I'm getting an error which I can't realize if it is something wrong with my travis.yml or is it a bug.

Here's the output:

	/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory @ rb_sysopen - ./src/shelltwit/bin/Release/netcoreapp2.0/publish/* (Errno::ENOENT)
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:86:in `new'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:86:in `upload_asset'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/provider/releases.rb:145:in `upload_file'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/provider/releases.rb:126:in `block in push_app'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/provider/releases.rb:117:in `each'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/provider/releases.rb:117:in `push_app'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/provider.rb:154:in `block in deploy'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/cli.rb:41:in `fold'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/provider.rb:154:in `deploy'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/cli.rb:32:in `run'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/cli.rb:7:in `run'
		from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/bin/dpl:5:in `<top (required)>'
		from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
		from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
	failed to deploy

and here's my travis file:

	language: csharp
	dist: trusty
	sudo: required
	mono: none
	dotnet: 2.0.0
	before_script:
	- chmod a+x ./build.sh
	script:
	- "./build.sh"
	before_deploy:
	- chmod a+x ./publish.sh
	- "./publish.sh"
	deploy:
	  provider: releases
	  api_key:
		secure: oI3sjxaqtND07L8DySCqVPVoXR9M+tTSbgPrrn11a2WvAIxzp23gPrXAc9lW1l4GYRD7P/8d3l1np5hbSODwsDzXws9ald195z5m2cwjmCzr63Fn2IezzPzF7/E7r+UAv4fc4nsvKgEyLUWzGy1IVf2b/7wxziIPsM3vQSqExz0geM+z9Eu0SUNNiSHdFOB+aGHS5cAwWtYrQmuMeJhf4ir9LJwHDaZENu4V4sMEsyq+jJm3h1bE4JVfuz+wVF+DSpbTRZ/LyCXUNzpFtTJpafIaSXnx0JWQTwxkQxxdwycG89NCEnujBdY6wLgT/s3F8OMbN9OhWoLMxd9lZTGHvSCfAS/kscz7QNXJfab0rbs6u2C6SLa6rVut16GYXdeU6Q67CBD5uTYJ31wSQmn3GHKPvdXPXJZXuK72P9ofrT1wJ1qDlarTIKVQ7mbhLQtb5fb0b2GQdJL235RBgz24sM4euYJqDAe050UmcNv7sy8a71i2lxBXmjNvrZsPIQjA4vKppQK2AN3xcPCox4IMvEaL7aXXSrA//tLgSNkreHWyS6nb1TM4hqQxXmXQvtyWIv3YKUAcqxYbpPK5+Ggi+v4S3MHAi2XEHuDvGT+uXhCOMyEWIKV9ajUCTU/pRQbRHq72ARNi+3kRx4PVrUs4Ck+Gb7oNp2ztA19E0SLP4bg=
	  file: ./src/shelltwit/bin/Release/netcoreapp2.0/publish/*
	  skip_cleanup: true
	  on:
		tags: true

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/deployment/releases#Uploading-Multiple-Files

> You can also enable wildcards by setting `file_glob` to `true`. This example includes all files in a given directory.

**Comment by sebagomez** [comment]
I feel dumb :(

That's was it! thanks
