### ISSUE TITLE
jruby is not working

### ISSUE THREAD

**Issue by sobrinho** [travis-ci/travis-ci#8412]
Hi,

I tried to fix the bundler issue with a `gem install bundler` but even the gem command is broken.

There is anything I can do?

Build: https://travis-ci.org/pubnub/ruby/jobs/274836110
PR: https://github.com/pubnub/ruby/pull/56/files

**Comment by BanzaiMan** [comment]
https://travis-ci.org/pubnub/ruby/jobs/274836110#L518 Try changing JDK, say `oraclejdk8`.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/pubnub/ruby/builds/275002165 is passing with `oraclejdk8` (which should be the default on Trusty, if you don't specify it).
