### ISSUE TITLE
"travis setup releases" complains about missing .travis.yml file

### ISSUE THREAD

**Issue by obones** [travis-ci/travis-ci#8413]
Hello,

I'm trying to setup travis for my own fork of a project that already uses it (obones/xgboost-jars) and for this, I have install Ruby under Windows and typing this in the command line:

      travis setup releases -r obones/xgboost-jars --org

However, this gives me the following error message:

    no .travis.yml found

But this is very strange because I'm seeing this file just fine in the repository, and the whole point of this is to allow me to get a valid encryption token for the releases.

What am I missing in my setup to make this work?

**Comment by BanzaiMan** [comment]
Are you in the repository root when you run the command? `travis setup` is trying to write to this file, resulting in the error. You are right, though, that the command should just create a new file if it doesn't exist already.

**Comment by obones** [comment]
Ah, thanks, this was not obvious from the documentation.
As a side note, `git.exe` must be reachable via the `PATH` environment variable and `--force` must also be given because the file already exists.

Thanks for your help.
