### ISSUE TITLE
builds stuck in the "pending" state

### ISSUE THREAD

**Issue by benoit-pierre** [travis-ci/travis-ci#8415]
While looking into the new support for conditional stages, I ended up with 2 builds stuck as "pending". Example: https://travis-ci.org/benoit-pierre/setuptools/builds/275160134

**Comment by BanzaiMan** [comment]
Thanks for the report. We will look into it.

**Comment by webknjaz** [comment]
Please also check this https://travis-ci.org/cherrypy/cheroot/builds/264712417 stuck in created state.

**Comment by svenfuchs** [comment]
@benoit-pierre Thanks for the quick report! ❤️ 

I've been able reproduce the issue, and just shipped a fix:

* config: https://github.com/svenfuchs/test-2/blob/master/.travis.yml
* broken: https://staging.travis-ci.org/svenfuchs/test-2/builds/625702 
* fixed: https://staging.travis-ci.org/svenfuchs/test-2/builds/625705
* production: https://travis-ci.org/svenfuchs/test/builds/275439675

Please let us now if you still see any issues.

**Comment by svenfuchs** [comment]
@webknjaz whoops. didn't reload the page. thanks for the report to you, too! please let us know if you still see any issues.

I'll set update the status of your builds manually.

**Comment by stavalfi** [comment]
hi guys, 

I see this problem constantly in my builds. For example: https://travis-ci.org/stavalfi/TorrentX/builds/414728478?utm_source=github_status&utm_medium=notification

Any help?

**Comment by janlucaklees** [comment]
yeah, same here: https://github.com/521dimensions/amplitudejs/pull/429

Is there a way to bump it or rerun it manually?

**Comment by Nelson-Gon** [comment]
Build shows it passed but stuck on GitHub https://travis-ci.com/github/Nelson-Gon/urlfix/jobs/492758336
