### ISSUE TITLE
RVM fails to install Ruby 2.1.4

### ISSUE THREAD

**Issue by mckaz** [travis-ci/travis-ci#8420]
Job failure can be viewed here: https://travis-ci.org/plum-umd/rdl/jobs/275253641

I have received this error in multiple Ruby repos. Here is the relevant bit from the log:
`$ rvm use 2.1.4 --install --binary --fuzzy`
`ruby-2.1.4 is not installed - installing.`
`Searching for binary rubies, this might take some time.`
`Requested binary installation but no rubies are available to download, consider skipping --binary flag.`
`Gemset '' does not exist, 'rvm ruby-2.1.4 do rvm gemset create ' first, or append '--create'.`
`The command "rvm use 2.1.4 --install --binary --fuzzy" failed and exited with 2 during .`

**Comment by BanzaiMan** [comment]
I've started packaging 2.1.4 for Trusty here: https://travis-ci.org/travis-ci/travis-rubies/jobs/276039639 When it succeeds and the archive is uploaded, it will be available for the on-demand installation.

Also 2.1.5 https://travis-ci.org/travis-ci/travis-rubies/jobs/276039694 and 2.1.3 https://travis-ci.org/travis-ci/travis-rubies/jobs/276039763.

I'm closing this optimistically. If you run into problems, do let us know.
