### ISSUE TITLE
Jobs falsely reporting failure on OS X

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#8422]
Both of these jobs appear to have succeeded, but Travis marked them as failures: https://travis-ci.org/Pr0methean/BetterRandom/jobs/275282993 https://travis-ci.org/Pr0methean/BetterRandom/jobs/275282994 The build (https://travis-ci.org/Pr0methean/BetterRandom/builds/275282984) doesn't show any similar issues with its Linux jobs.

The bottom of the logs, in particular, tells that the error couldn't be traced to my code -- including the pom.xml and the shell script that calls Maven -- and therefore must be a platform-configuration issue:

```
The command "./${OP}.sh" exited with 0.
Done. Your build exited with 1.
```

**Comment by BanzaiMan** [comment]
You have other jobs failing (e.g., https://travis-ci.org/Pr0methean/BetterRandom/jobs/275282993#L50) so the job is marked a failure.

**Comment by BanzaiMan** [comment]
This is somewhat counterintuitive; this is discussed in #1066.
