### ISSUE TITLE
JAVA_HOME environment not set set for jdk7 and jdk6

### ISSUE THREAD

**Issue by danielpeintner** [travis-ci/travis-ci#8423]
Hi,

I noticed that there seems to be some issue with setting JAVA_HOME environment for jdk7 and jdk6.
See https://travis-ci.org/EXIficient/exificient-grammars/builds/275346317

JDK8 runs just fine while the other JDKs complain

```
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

**Comment by BanzaiMan** [comment]
A duplicate of #7884.
