### ISSUE TITLE
usage: cannot find pre-compiled binary for: linux/x64/v7.4.0

### ISSUE THREAD

**Issue by helfi92** [travis-ci/travis-ci#8427]
The error I'm getting:

```bash
> usage: cannot find pre-compiled binary for: linux/x64/v7.4.0
> usage: failed loading provider `linux`
```

Could this be a bug in travis? I wasn't getting this error previously. Running things locally works.

[Link](https://travis-ci.org/taskcluster/taskcluster-queue/builds/275479092?utm_source=github_status&utm_medium=notification) to the travis build

**Comment by BanzaiMan** [comment]
Possibly due to invalid cache. Try disabling or deleting the cache.

**Comment by helfi92** [comment]
That solved it. Many thanks @BanzaiMan
