### ISSUE TITLE
Support of ruby 2.4.2, 2.3.5, 2.2.8

### ISSUE THREAD

**Issue by ShockwaveNN** [travis-ci/travis-ci#8430]
Rubies `2.4.2, 2.3.5, 2.2.8` just released today.
Should be added to build matrix, currently using them raise error.
`Requested binary installation but no rubies are available to download, consider skipping --binary flag`

**Comment by BanzaiMan** [comment]
2.2.8: https://travis-ci.org/travis-ci/travis-rubies/builds/275590595
2.3.5: https://travis-ci.org/travis-ci/travis-rubies/builds/275590601
2.4.2: https://travis-ci.org/travis-ci/travis-rubies/builds/275590607

Mac builds have been canceled for now.

**Comment by BanzaiMan** [comment]
Upload is failing due to the current AWS issue.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
All of those are now built! And the macos ones should be built once they get through the backlog.

**Comment by BanzaiMan** [comment]
The Mac binaries may have some further work to do, similar to https://github.com/travis-ci/travis-ci/issues/7848

**Comment by BanzaiMan** [comment]
This should be OK now.
