### ISSUE TITLE
What is the correct url for connecting to mongodb?

### ISSUE THREAD

**Issue by renanol** [travis-ci/travis-ci#8432]
Hi guys, I have set url in environment variables, but I have connection error.

_MongoDB connection error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]_

**Url inserted:** mongodb://127.0.0.1/my_database

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by renanol** [comment]
Yes,
https://travis-ci.org/renanol/test-node

**Comment by BanzaiMan** [comment]
Have you started your MongoDB server? https://docs.travis-ci.com/user/database-setup/#MongoDB

**Comment by renanol** [comment]
I don't,  but need? but In the image already has MongoDB 3.2.16 istalled?

![deepinscreenshot_select-area_20170914221803](https://user-images.githubusercontent.com/673991/30462248-d5b1faec-999a-11e7-9583-ad8454d284a9.png)

**Comment by renanol** [comment]
You were right! Thank you so much! It's working now! =)
