### ISSUE TITLE
"No builds for this repository" despite .travis.yml file, permission granted, sync done and new commits pushed.

### ISSUE THREAD

**Issue by alemar11** [travis-ci/travis-ci#8434]
Hi,
I can't get builds to run for https://travis-ci.org/tinrobots/CountryKit despite following the setup process strictly. Could you please take a look?

Thanks 🙏🏼

**Comment by BanzaiMan** [comment]
When one of these builds in https://travis-ci.org/tinrobots/CountryKit/builds finishes, you will see stuff on https://travis-ci.org/tinrobots/CountryKit.

**Comment by alemar11** [comment]
Everything works fine! Thanks
