### ISSUE TITLE
Cannot enable GitHub repo

### ISSUE THREAD

**Issue by adigherman** [travis-ci/travis-ci#8438]
I'm trying to figure out why a Github repo does not show up in the Travis CI list. On my backend I did see this error message `not allowed to update service hook for <repo slug>`. Since then I've added other repositories and they were all picked up by Travis without problems. If I manually try to use the CLI to enable the repo, I get:
```
repository not known to Travis CI (or no access?)
triggering sync: . done
repository not known to https://api.travis-ci.org/: <repo slug>
```
This is a public repo https://github.com/neuroconductor-devel/ITKR

**Comment by BanzaiMan** [comment]
Could you include the entire output from the command (including the exact command that you ran, and the directory you ran it from)? Also include the output from `travis report` after the failure.

**Comment by adigherman** [comment]
The next cron job was able to enable it and I did not see any more problems after that. I'll close this issue but keep an eye on similar problems and will report back (if needed). Thanks!
