### ISSUE TITLE
Update docs to clarify status of Oracle JDK 7

### ISSUE THREAD

**Issue by mbrukman** [travis-ci/travis-ci#8439]
https://docs.travis-ci.com/user/languages/java/ says:

> The Travis CI environment provides Oracle JDK 8 (default), Oracle JDK 9, OpenJDK 6, OpenJDK 7, Gradle 2.0, Maven 3.2 and Ant 1.8, and has sensible defaults for projects that use Gradle, Maven or Ant.

which doesn't mention Oracle JDK 7. However, below, it says:

> To test against multiple JDKs, use the jdk: key in .travis.yml. For example, to test against Oracle JDK 7 and 8 and OpenJDK 6:
> 
> ```yaml
> jdk:
>   - oraclejdk8
>   - oraclejdk7
>   - openjdk6
> ```

as well as:

> Travis CI provides OpenJDK 6, OpenJDK 7, Oracle JDK 7, and Oracle JDK 8. Sun JDK 6 is not provided, because it is EOL as of November 2012. OpenJDK 8 is available on our Trusty images, specify `dist: trusty` to make use of it.

I understand that Oracle JDK 7 is no longer supported for the reasons mentioned in [this comment](https://github.com/travis-ci/travis-ci/issues/7019#issuecomment-316769716) and [this issue](https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879).

Please update the doc accordingly so that it's clear:

* remove all mentions of Oracle JDK 7 as being "supported"
* add a note about why Oracle JDK 7 is not being supported to the top of the doc, linking to the web pages in question with the rationale

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/docs-travis-ci-com/pull/1453
