### ISSUE TITLE
travis-build: global env var with backquotes broken

### ISSUE THREAD

**Issue by rakhimov** [travis-ci/travis-ci#8442]
Job: https://travis-ci.org/rakhimov/scram/jobs/276031289

The setup of glob var ``PATH=$PATH:`pwd`/install/bin`` results in:

```bash
export PATH=$PATH:
```

**Comment by BanzaiMan** [comment]
It looks like a case we failed to account for in a recent change. Try `PATH=$PATH:$PWD/install/bin` until it's fixed.

**Comment by rakhimov** [comment]
>It looks like a case we failed to account for in a recent change. Try PATH=$PATH:$PWD/install/bin until it's fixed.

Yes, @BanzaiMan , ``PWD`` env var fixes it: https://travis-ci.org/rakhimov/scram/builds/276149733
