### ISSUE TITLE
Travis-build: Too long commit msg

### ISSUE THREAD

**Issue by IanCStewart** [travis-ci/travis-ci#8443]
Build fails when build in question has a long commit msg.

---

## The twitter convo:

> Having some weird build issues with @travisci on the 'master' branch. Looking for some help 🕵️😅
 https://travis-ci.org/anchorchat/anchor-ui/jobs/275486154 …

> Commit msg for https://github.com/anchorchat/anchor-ui/commit/32bde1a495f314383ebee401a3689933986ad356 … is too long when we try to set `$TRAVIS_COMMIT_MESSAGE`.

**Comment by BanzaiMan** [comment]
Notice that GitHub is not displaying the entire commit message.

**Comment by BanzaiMan** [comment]
The truncation on GitHub happens around byte 29064 (give or take a few) out of 162719.
