### ISSUE TITLE
Fail to install JRuby

### ISSUE THREAD

**Issue by ms-ati** [travis-ci/travis-ci#8446]
See, for example: https://travis-ci.org/enkessler/childprocess/jobs/276347449

These builds are always for just `jruby`. Sometimes the fuzzy matching seems to match `jruby-9.1.13.0200` as above, sometimes `jruby-9.1.9.0`, as in this build: https://travis-ci.org/enkessler/childprocess/jobs/276314057

What can I do to get JRuby tests working on this?

**Comment by BanzaiMan** [comment]
This is an upstream issue. See https://github.com/jruby/jruby/issues/4789.

**Comment by ms-ati** [comment]
Oy vey

**Comment by floehopper** [comment]
The JRuby downloads appear to be working again, but I still have builds failing (e.g. [this one](https://travis-ci.org/freerange/mocha/jobs/275961972)). Is there some caching going on? Is there something I can do to work around this to get my builds passing? Thanks.

**Comment by jurriaan** [comment]
@floehopper I've switched to 'jruby-9.1.9.0', which is the latest pre-compiled jruby by travis (see http://rubies.travis-ci.org/).

**Comment by akabiru** [comment]
We had `jruby-1.7.17` failing as well. Switched to `jruby-1.7.25`, which works atm. 👍

**Comment by BanzaiMan** [comment]
The list in http://rubies.travis-ci.org is unfortunately ineffective at the moment, as our RVM config is such that it always looks for archives from jruby.org's.

jruby_url=https://s3.amazonaws.com/jruby.org/downloads

**Comment by BanzaiMan** [comment]
↑ The above comment applies only to JRuby and JRuby only.

Rubinius binaries point to rubini.us binaries, and MRI archives are pulled from our S3 bucket.

**Comment by bbergstrom** [comment]
Is there a way to configure the build to pull JRuby binaries from an alternative source to work around this issue?

**Comment by BanzaiMan** [comment]
I don't think there is, unless there is a complete, faithful, and trustworthy copy of http://jruby.org/download exists somewhere. The directory structure of http://jruby.org/download and our S3 bucket (for Ruby archives) are quite different, and RVM jumps through a lot of hoops to hide details such as these.

**Comment by bbergstrom** [comment]
I was hoping for a way to set RVM user config as outlined in https://rvm.io/rvm/configuration so I could point it to my own S3 bucket or download server which would satisfy my version requirements.

**Comment by driv3r** [comment]
We are getting same issues now for 9.1.13.0 any ideas what's happening this time?

**Comment by brendon** [comment]
Still broken for 9.1.9.0 :(

**Comment by driv3r** [comment]
It's yet again issue with JRuby S3 buckets - jruby/jruby#4789

**Comment by brendon** [comment]
Ah I see. Troublesome!

**Comment by jirutka** [comment]
This error is still happening.

https://travis-ci.org/jirutka/asciidoctor-rouge/jobs/324414367#L434-L435:
```sh
$ rvm use jruby --install --binary --fuzzy
Unknown ruby string (do not know how to handle): jruby-9.1.15.0200.
```

Version `jruby-9.1.15.0200` does not exist, it should be `jruby-9.1.15.0`. `200` at the end of version number is some garbage (maybe HTTP status code)?

It’s really a shame that it’s still not fixed.

**Comment by BanzaiMan** [comment]
@jirutka Thanks for the followup. This issue (that jruby's archive went missing) is essentially fixed. That `rvm use jruby…` command fails is a separate issue. Could you open a new issue? Thanks.
