### ISSUE TITLE
Build badge does not update after restarting build

### ISSUE THREAD

**Issue by juliohm** [travis-ci/travis-ci#8450]
Is this a bug or a cache issue? I've restarted the build since this morning, but the badge is still red: https://travis-ci.org/juliohm/GeoStats.jl

If I click on the badge, it becomes green, when I reload the page, it turns red again.

**Comment by BanzaiMan** [comment]
The latest build on the `master` branch https://travis-ci.org/juliohm/GeoStats.jl/builds/276351150 failed, so I believe this is the correct behavior.

**Comment by BanzaiMan** [comment]
Note: https://travis-ci.org/juliohm/GeoStats.jl currently points to https://travis-ci.org/juliohm/GeoStats.jl/builds/27635344, a passing build.

**Comment by juliohm** [comment]
Makes sense, sorry for the noise. Closing the issue.
