### ISSUE TITLE
Sync with Github is been running for the last couple of hours

### ISSUE THREAD

**Issue by avina-z** [travis-ci/travis-ci#8451]
Please help. I removed my repository from Github and recreated again then I hit Sync on Travis, but Syncing from GitHub is been running for a couple of hours and does not finish. From the command line I am getting:

[root@dpydalpps0101 bin]# ./travis sync --force --debug
** Loading "/root/.travis/config.yml"
** Timeout::Error: execution expired
** GET "users/"
** took 5.8 seconds
synchronizing: ** POST "users/sync"
** took 0.14 seconds
409: "{"message":"Sync already in progress. Try again later."}"

Repository: https://github.ibm.com/pps/pps

I did not find where to report this for a enterprise account. Please help.

**Comment by BanzaiMan** [comment]
Hello, there.

Please get in touch with your Travis Enterprise operations team.

Thank you!

**Comment by avina-z** [comment]
Thanks. This is now fixed. Support team forced sync from the Travis admin console.
