### ISSUE TITLE
Problem on google app engine deploy with Travis CI

### ISSUE THREAD

**Issue by abdounikarim** [travis-ci/travis-ci#8454]
Hello, I have a problem when Travis want to deploy my project (with Symfony) in google app engine, i add the link for the log file here :
https://travis-ci.org/abdounikarim/louvre/builds/276755786
Can you help me ?

Thanks a lot

**Comment by BanzaiMan** [comment]
There appears to be some application issue you'd need to address. Please read the log carefully and address the issue; e.g., https://travis-ci.org/abdounikarim/louvre/builds/276755786#L2897

I don't know how your application is supposed to handle this, but the error does not appear to be ours.
