### ISSUE TITLE
Builds take very long to start

### ISSUE THREAD

**Issue by offa** [travis-ci/travis-ci#8456]
The builds today take very long to start, usually > 30 minutes. According to the [Travis Status Page](https://www.traviscistatus.com/) the backlog of Linux (and OS X) is increasing constantly today.

I'm using *Trusty* with *sudo required*.

**Comment by AllanWang** [comment]
This has been happening for the past few days. My projects also include non trusty builds and builds without sudo, as well as some Android projects

**Comment by sushantdhiman** [comment]
I am facing similar issue with various builds on https://travis-ci.org/sequelize/sequelize as well.

Our builds are sudo enabled trusty images.
```yml
sudo: required
dist: trusty
language: node_js
```

Started noticing this issue from today.

**Comment by cotsog** [comment]
@offa, @AllanWang, @sushantdhiman: Thanks for reporting and I'm sorry for this unwanted situation. Our Engineering Team is aware of the issue and is currently looking into it.

We also have opened [a public incident](https://www.traviscistatus.com/incidents/4qj8t3220jy8) where we will provide timely updates. You can subscribe to be notified of any movement on that front.

Thank you for your patience!

**Comment by BanzaiMan** [comment]
This can be closed.
