### ISSUE TITLE
C# support for Travis-CI is community maintained

### ISSUE THREAD

**Issue by denis-peshkov** [travis-ci/travis-ci#8461]
Hi guys I have a problem with configuring Travis to build my project:
https://travis-ci.org/denis-peshkov/dw
I saw in logs request to open an issue to you
@joshua-anderson @akoeplinger @nterry

could you please help me with this configuration?

**Comment by GloriousYellow** [comment]
The build log shows an error: 
`If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format. `
Could this be related to your issue?

**Comment by denis-peshkov** [comment]
Hi guys,  it isn't possible,  I have to build a .Net Core 2.0 app. 

Sent from my HTC

----- Reply message -----

**Comment by mdekrey** [comment]
@denis-peshkov: I'm new to using travis-ci with .Net Core 2.0 myself, but `xbuild` is the mono builder. You try to [use the standard `dotnet` commands in your travis config](https://github.com/denis-peshkov/dw/blob/master/.travis.yml#L11-L14), such as `dotnet restore` and `dotnet publish DW.sln -c Release`.

**Comment by denis-peshkov** [comment]
Could anyone help me to configure it?

**Comment by denis-peshkov** [comment]
I got next message in Travis:
**C# support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry**

**Comment by denis-peshkov** [comment]
also next one:

/home/travis/build/denis-peshkov/dw/src/Web/Web.csproj: error : /home/travis/build/denis-peshkov/dw/src/Web/Web.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by akoeplinger** [comment]
@denis-peshkov replace the `nuget restore DW.sln` with `dotnet restore` and the `xbuild /p:Configuration=Release DW.sln` with `dotnet build` to run the build with .NET Core.

**Comment by denis-peshkov** [comment]
Thanks, perhaps it helped, but still can't build it:
https://travis-ci.org/denis-peshkov/dw
https://github.com/denis-peshkov/dw
-- 
it is shared project. Can somebody fix **.travis.yml** and create a pull request ?
