### ISSUE TITLE
The job exceeded the maximum time limit, but never end

### ISSUE THREAD

**Issue by rusher** [travis-ci/travis-ci#8463]
Error is "The job exceeded the maximum time limit for jobs, and has been terminated.". Problem is the job never really get terminated. 

Example here : 
https://travis-ci.org/MariaDB/server/jobs/277167314
log show the "exceeded the maximum time limit", but the job is still not killed.

At the time of writing, page show "Running for 5 hrs 33 min 29 sec". So those job never finished and have to be cancelled manually, or next job will never be launched. 
It seems to me that's new since like 4 days

**Comment by mrkkrp** [comment]
The same here. In addition to that, I have noticed that my jobs almost never get to successful completion because after the phrase "exceeded the maximum time limit" is printed, they are sort of blocked although the UI shows that they are still running.

In the past it worked! For example here:

https://travis-ci.org/mrkkrp/megaparsec/jobs/278227398

```
$ travis_wait 60 cabal build
Still running (41 of 60): cabal build
The job exceeded the maximum time limit for jobs, and has been terminated.
```

We can see this `41 of 60` thing, previously `travis_wait 60 cabal build` managed to finish quite reliably. I can't go on with finishing a feature because of this, CI does not work.

:cry:

**Comment by BanzaiMan** [comment]
@mrkkrp Yours is different. Your job takes too long, and getting terminated because it reached the 50-minute maximum on travis-ci.org.

**Comment by BanzaiMan** [comment]
This issue is about jobs that have finished but their state have not been properly set. Most recently, I see https://travis-ci.org/MariaDB/server/jobs/278433890.

**Comment by lspitzner** [comment]
Things get even more messed up if you decide to restart your builds, e.g. see
https://travis-ci.org/lspitzner/brittany/jobs/277956777. Note in line 708 "Done. Your build exited with 0."
The timeline was roughly:

- build runs and finishes (stuff up to line 709).
- I get a report "status: errored" nonetheless.
- Two hours later, it automatically re-executed the build (lines 710-fin) and
- cancels it a couple minutes later (the cancelling _may_ have been appropriate, but the re-execution itself and log file merging is completely bonkers).

**Comment by bogdanap** [comment]
Hi, thank you for brining this problem to our attention. 
We've created an issue in our worker repo to track this: https://github.com/travis-ci/worker/issues/379 and we're already working on fixing it. 
I'm closing this issue in favor of the one mentioned above, so feel free to track that one for updates.

**Comment by mitchellkrogza** [comment]
@bogdanap any ETA on this? This has brought all my work and my collaborations with others to a complete halt this week. Cannot get any of my projects to run properly as they all just run to 50+ minutes and timeout despite us having our own function to stop the build at a specified time limit of 20 minutes, commit our files and then continue with next build .... all been working 100% for weeks and now all those projects are at a complete standstill.
