### ISSUE TITLE
Python2 cannot handle HTTPS anymore

### ISSUE THREAD

**Issue by chfast** [travis-ci/travis-ci#8464]
I'm not sure, but looks like after some update to Linux image my GitHub upload script stopped working.
The script uses python2. I'm getting exception:

```
Exception:
  hostname 'uploads.github.com' doesn't match either of '*.githubusercontent.com', 'githubusercontent.com'
```

https://travis-ci.org/ethereum/cpp-ethereum/jobs/277203942

**Comment by BanzaiMan** [comment]
Where is the error message coming from? The error message is correct, though. If it used to work, I tend to think it was because the SSL certificate check was more permissive.

https://travis-ci.org/BanzaiMan/travis_production_test/jobs/277709429#L126 indicates to me that at least `curl` thinks the cert chain is legitimate.

**Comment by chfast** [comment]
I'm running this script: https://github.com/ruslo/hunter/blob/master/maintenance/upload-cache-to-github.py.

It is not mine, so I don't know exactly how it tries to reach GitHub, but it was working before. And it is still working on Travis / macOS and some other CI servers.

**Comment by chfast** [comment]
The script uses this GitHub API endpoint:
https://developer.github.com/v3/repos/releases/#upload-a-release-asset

It also requires the HTTP client to have SNI.
https://en.wikipedia.org/wiki/Server_Name_Indication

**Comment by chfast** [comment]
The missing SNI support seams to be the case.
https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support

**Comment by chfast** [comment]
Warning from urllib3 I can see on Travis CI:
```
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
```

**Comment by chfast** [comment]
Yes. I had to upgrade pyopenssl package.
https://github.com/ethereum/cpp-ethereum/blob/develop/.travis.yml#L132

**Comment by BanzaiMan** [comment]
Great to hear that. I'm closing this, then.
