### ISSUE TITLE
Timeouts on Tests

### ISSUE THREAD

**Issue by andrewvaughan** [travis-ci/travis-ci#8469]
https://travis-ci.org/andrewvaughan/uhppote-rfid/builds/278040914

My test suites are unexplainably timing out only in Travis environments.  Thinking this was an issue with Trusty, I've also tried, Precise, with and without `sudo`, with and without caching... etc.

I attempted to load the Travis environment from a Docker container to test, but was unable to do so. 
 Even with the latest push to Docker Hub, I noticed the environments were incredibly unmatched.  The Docker container had Python 2.7.6 whereas the online containers are running 2.7.13, for instance.  This has prevented me from determining any root cause as to why only Travis' environments would be killing a python test command mid-test.  Any assistance would be appreciated.

**Comment by BanzaiMan** [comment]
I just tried reproducing your build problem:

```
$ docker run --name travis-debug -dit travisci/ci-garnet:packer-1503972846 /sbin/init
3d0c09e403acfa1b53925467f1a9850649ae2c7dee5abdf562b77798e9246f25
$ docker exec -it travis-debug bash -l
root@3d0c09e403ac:/# su - travis
travis@3d0c09e403ac:~$ cd builds
travis@3d0c09e403ac:~/builds$ git clone --depth=50 --branch=travis https://github.com/andrewvaughan/uhppote-rfid.git andrewvaughan/uhppote-rfid
Cloning into 'andrewvaughan/uhppote-rfid'...
remote: Counting objects: 76, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 76 (delta 31), reused 62 (delta 17), pack-reused 0
Unpacking objects: 100% (76/76), done.
travis@3d0c09e403ac:~/builds$ cd andrewvaughan/uhppote-rfid/
travis@3d0c09e403ac:~/builds/andrewvaughan/uhppote-rfid$ git checkout -qf c9f9ee5b7d7d7f18bc3acb70de160d2867d96ea3
travis@3d0c09e403ac:~/builds/andrewvaughan/uhppote-rfid$ source ~/virtualenv/python2.7/bin/activate
(python2.7.13) travis@3d0c09e403ac:~/builds/andrewvaughan/uhppote-rfid$ pip install -q -r requirements.txt
(python2.7.13) travis@3d0c09e403ac:~/builds/andrewvaughan/uhppote-rfid$ time coverage run --source uhppote_rfid test
.........................................................................No handlers could be found for logger "UHPPOTE.ControllerSocket"
...............................................Killed

real    0m23.005s
user    0m10.780s
sys     0m3.050s
```

While timeout did not occur, I do observe the process is killed (which I believe is similar to https://travis-ci.org/andrewvaughan/uhppote-rfid/builds/278040283).

**Comment by andrewvaughan** [comment]
Thanks for the help - I was attempting to run the scripts manually instead of using the activate function.  I still have the issue where this killing of the test is only happening in TravisCI containers.  I've tested on a few other CI platforms with no problems.  I'll try to do some more digging to see what the root cause is.

**Comment by andrewvaughan** [comment]
I'm going to close this issue.  It turns out there was a problem with my mock response in a test that was hanging.  I have no idea why it wouldn't fail on any other system; TravisCI is the only one that caught it.

Thanks for looking into this for me, @BanzaiMan.  If you could, please update your Docker documentation to explain the importance of the `source ~/virtualenv/python2.7/bin/activate` line you used!
