### ISSUE TITLE
Can I set shorter timeout for Jobs?

### ISSUE THREAD

**Issue by andreif** [travis-ci/travis-ci#8470]
Today few our builds using Ubuntu images had a hanging job for 2 hours and blocked all workers so that the build queue grew a lot. I wonder if we can set a shorter job timeout to stop it in the case of such hanging. Our jobs run for about 5-10 minutes so we would prefer to fail them after say 15 min instead of waiting until someone notices the problem and restarts them.

**Comment by DrTorte** [comment]
Hey there,

We can certainly add a hard timeout to your repos. Which specific ones were you looking at adding it to?

All the best,

Kris

**Comment by andreif** [comment]
@DrTorte Ideally we would prefer to control timeouts by ourselves since it can be repo-dependent and can change with time.

**Comment by philmd** [comment]
similar to #5306 and #6636

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate of #5306.
