### ISSUE TITLE
Issues migrating my build to Trusty

### ISSUE THREAD

**Issue by gs-rezaem** [travis-ci/travis-ci#8472]
on the migration from precise to trusty [page](https://docs.travis-ci.com/user/precise-to-trusty-migration-guide/) you should mention that trusty no longer has an OpenJDK 6.

**Comment by gs-rezaem** [comment]
According to #8199 openjdk 6 has to be included in the addons. Please document this in the migration docs.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/docs-travis-ci-com/pull/1463
