### ISSUE TITLE
Installing php-enchant library onto PHP Trusty box

### ISSUE THREAD

**Issue by Stetzon** [travis-ci/travis-ci#8473]
Hi, my application needs to utilize the [php-enchant](http://php.net/manual/en/book.enchant.php) library and I am trying to configure this on our Travis box.

My travis.yml:
```
  language: php
  dist: trusty
  sudo: true
  php:
    - 7.1
```

when I debug and ssh into the box, am running 
```
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update
sudo apt-get install php7.1-enchant
```
which all runs fine.  However, when opening up a quick php shell, the enchant functions are not defined:

```
$ php -a -- --with-enchant
Interactive shell

php > var_dump(function_exists("enchant_broker_init"));                                                                                                                                        
php shell code:1:
bool(false)
```

Am I missing a step, or is there an easier way to get up and running with enchant?

**Comment by BanzaiMan** [comment]
I'm guessing that `sudo apt-get install php7.1-enchant` installs stuff in places that our PHP 7.1 (which is managed by `phpenv`) cannot find.

**Comment by SimplyCorey** [comment]
@BanzaiMan Any tips on how to fix it, or know of another repo that places nice with travis?  I'm facing a similar issue.  Thanks!

**Comment by BanzaiMan** [comment]
@SimplyCorey http://php.net/manual/en/enchant.installation.php says that it is bundled with PHP 5.3 and later. Our PHP runtimes are compiled from source with [php-build](https://github.com/php-build/php-build/). Unless php-build explicitly disables this extension, I expect it to be available without your intervention.

**Comment by Stetzon** [comment]
@BanzaiMan even without installing `php7.1-enchant` from apt, enchant is not available from the default box.  After reading your comment discussing `php-build`, I was able to find the default `php-build` [options](https://github.com/travis-ci/travis-cookbooks/blob/precise-stable/ci_environment/phpbuild/templates/default/default_configure_options.erb) linked in the travis docs [here](https://docs.travis-ci.com/user/languages/php#PHP-installation), and it looks like the `--with-enchant` build option is missing.  Is there a way I can add this (or any other build option for that matter) to my travis configuration?

**Comment by BanzaiMan** [comment]
If this is a compile-time-only configuration options, I don't think it's possible to enable it. This is documented. https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

**Comment by Stetzon** [comment]
I created a PR [here](https://github.com/travis-ci/travis-cookbooks/pull/907)

**Comment by SimplyCorey** [comment]
Would someone be able to review the PR before the bot closes this please?
