### ISSUE TITLE
New Trusty image broke test running off xvfb

### ISSUE THREAD

**Issue by konserw** [travis-ci/travis-ci#8481]
We ([cucumber-cpp](https://github.com/cucumber/cucumber-cpp)) have been using xvfb to run gui test and one of those tests begun failing after travis updated trusty image (sudo-enabled). Please see:
Last green build before update: https://travis-ci.org/cucumber/cucumber-cpp/builds/270444116
Example of failing build: https://travis-ci.org/cucumber/cucumber-cpp/jobs/274997879
Green build with `group: deprecated-2017Q3 ` added to config: https://travis-ci.org/cucumber/cucumber-cpp/builds/276870216

**Comment by BanzaiMan** [comment]
I think this is a different manifestation of https://github.com/travis-ci/travis-ci/issues/8262, where xfvb is missing from the image. Please try the workaround shown in https://github.com/travis-ci/travis-ci/issues/8262#issuecomment-323601110

I'm closing this as a duplicate now, but if you have reasons to believe it should be a separate issue, do let us know.

**Comment by konserw** [comment]
Sorry - but this is not the case. I should have writen more details:
* We do install Xvfb: [see .travis.yml](https://github.com/cucumber/cucumber-cpp/blob/0928f2568a9681291b8dff6a5fb3549305109324/.travis.yml#L4)
* We start up Xvfb in a little bit different way than in linked issue, but it worked fine before: [see travis.sh](https://github.com/cucumber/cucumber-cpp/blob/0928f2568a9681291b8dff6a5fb3549305109324/travis.sh#L39)
* First test using Xvfb runs without problems: see travis output from [line 1445](https://travis-ci.org/cucumber/cucumber-cpp/jobs/274997879#L1445) to [line 1574](https://travis-ci.org/cucumber/cucumber-cpp/jobs/274997879#L1574)
* What fails is second test (almost identical): see travis output from [line 1580](https://travis-ci.org/cucumber/cucumber-cpp/jobs/274997879#L1580) to [line 1642](https://travis-ci.org/cucumber/cucumber-cpp/jobs/274997879#L1642)

Please reopen this bug report.

**Comment by konserw** [comment]
Any news?
I just wanted to add that it runs fine on:
* OSX (on travis)
* old linux travis image
* Windows (appveyor)
* Arch linux (my PC)
And that it fails always on example using boost-test, and doesn't fail on very similar example using google-test

**Comment by konserw** [comment]
Also a quote from @muggenhor:

> I've added some extra code to get some extra debugging from the travis script. That produces this: https://travis-ci.org/muggenhor/cucumber-cpp/jobs/279609591
>It seems that we're getting an exit code 139 from the step definition executable, which is a bashism for signal 139-128=11 aka SIGSEGV. I.e. we're getting a memory access violation

**Comment by The-Compiler** [comment]
I don't think this is the issue you're seeing here, but I was seeing a segfault with Qt 5.10 and Xvfb due to [a Qt 5.10 bug](https://bugreports.qt.io/browse/QTBUG-64928).

The only working workaround I found was to install a newer Xvfb from Ubuntu Xenial:

```yaml
sudo: required
addons:
  apt:
  sources:
    - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
  packages:
    - xvfb
```
