### ISSUE TITLE
Error: Unique option is defined multiple times

### ISSUE THREAD

**Issue by r-raymond** [travis-ci/travis-ci#8483]
CC @domenkozar @garbas @matthewbauer

When building my CI tests for my [nixos project](https://www.github.com/r-raymond/nixos-mailserver), I run into the following error

```
error: The unique option `users.users.vmail.group' is defined multiple times, in `/home/travis/build/r-raymond/nixpkgs/nixos/modules/config/users-groups.nix' and `/home/travis/build/r-raymond/nixpkgs/nixos/modules/config/users-groups.nix'.
```

This error is not appearing when I'm running the tests locally. The offending code is in this [file](https://github.com/r-raymond/nixos-mailserver/blob/master/mail-server/users.nix), the user `vmail_user` (`vmailUserName` and `vmailGroupName` are set to the string `vmail` in the tests).

Strangely, if I remove the two lines
```
    name = vmailUserName;
    ...
    group = vmailGroupName;
```
the test passes, whereas it fails locally (postfix complains that the group name `vmail` is not known).

Is there anything special I should be aware of for testing Nixos modules with Travis CI?

**Comment by matthewbauer** [comment]
You can probably just use nixpkgs-unstable by importing the special path ```<nixpkgs>```.

**Comment by r-raymond** [comment]
Thanks for clearing that up. I thought this was a Travis CI quirk.
