### ISSUE TITLE
Two dist-info directories for Python 2.7.13 setuptools on trusty

### ISSUE THREAD

**Issue by andy-maier** [travis-ci/travis-ci#8493]
Hi,
While debugging an issue with reinstalling the Python setuptools package to test with our stated minimum version, we saw that the trusty installation has two dist-info subdirectories of setuptools installed on Python 2.7.13 (this is before we install or update anything):

```
/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/setuptools
/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/setuptools-36.0.1.dist-info
/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/setuptools-36.3.0.dist-info
```

The version in the "setuptools" directory is 36.3.0, so the "setuptools-36.0.1.dist-info" directory is moot.

See Travis run https://travis-ci.org/zhmcclient/python-zhmcclient/jobs/279335595

Pip gets confused about this, see Pip issue pypa/pip#4724.

I suggest that the invalid copy of the dist-info directory be removed in the trusty image.

**Comment by andy-maier** [comment]
I have verified that the Pip issue we are seeing no longer shows up when removing the extra metadata directory `setuptools-36.0.1.dist-info`. See https://travis-ci.org/zhmcclient/python-zhmcclient/jobs/279884689 starting on line 485.

The Pip team has stated in the discussion on issue pypa/pip#4724 that having more than one metadata directories for a package is considered a corrupted system.

**Comment by BanzaiMan** [comment]
This is interesting. I am interested to know _how_ we get to this situation.

Perhaps I am missing something obvious, but we just run `pip install --upgrade pip setuptools wheel` 

https://github.com/travis-ci/travis-cookbooks/blob/be329608f411aa130cca4b1e7f61d8b02be32f25/cookbooks/travis_build_environment/recipes/pip.rb#L12

Is this leading to the "corrupted system"?

**Comment by andy-maier** [comment]
I'd like to check back on this issue. IMO, there are two things to do for Travis:
1. Fix the situation in the trusty image by removing the invalid metadata directory for setuptools.
2. Find out how it got created,

Item 1. can be done without item 2. To date, the trusty image still has this issue.

On item 2.: One suspicion on how the extra metadata directory for setuptools could have been created was mentioned in a comment on issue pypa/pip#4724: Namely, that `easy_install` caused it. However, that suspicion was mentioned as a guess with no real basis.
