### ISSUE TITLE
.NET ASP.Core 2.0  with Docker

### ISSUE THREAD

**Issue by CliffordSimak** [travis-ci/travis-ci#8494]
I use VS 2017 and the option "Add Docker Support".
I try to build docker with Travis. But after line `docker build -f app/Dockerfile -t appname:latest app/.` I take `The command "./deploy.sh exited with 1.`

> deploy.sh 

```
# Create publish artifact
dotnet restore ./app.sln
dotnet publish ./app.sln -c Release -o ./obj/Docker/publish

# Build the Docker images
docker build -f app/Dockerfile -t app:latest app/.
```

> Travis CI

```
dotnet publish ./app.sln -c Release -o ./obj/Docker/publish

/home/travis/build/company/app/docker-compose.dcproj : error MSB4236: The SDK 'Microsoft.Docker.Sdk' specified could not be found.
/home/travis/build/company/app/docker-compose.dcproj : warning NU1503: Skipping restore for project '/home/travis/build/company/app/docker-compose.dcproj'. The project file may be invalid or missing targets required for restore. [/home/travis/build/company/app/app.sln]
Copyright (C) Microsoft Corporation. All rights reserved.

e/travis/build/company/app/app/bin/Release/netcoreapp2.0/app.dll

/home/travis/build/company/app/docker-compose.dcproj : error MSB4236: The SDK 'Microsoft.Docker.Sdk' specified could not be found.

app -> /home/travis/build/company/app/app/obj/Docker/publish/
app-xunit -> /home/travis/build/company/app/app-xunit/bin/Release/netcoreapp2.0/app-xunit.dll
app-xunit -> /home/travis/build/company/app/app-xunit/obj/Docker/publish/

The command "./deploy.sh exited with 1.
```

On my local machine  `dotnet publish ./app.sln -c Release -o ./obj/Docker/publish` works fine!

> Local machine
```
PS D:\Folder\app> dotnet publish ./app.sln -c Release -o ./obj/Docker/publish
Microsoft (R) Build Engine ?????? 15.3.409.57025 ??? .NET Core
(C) ?????????? ?????????? (Microsoft Corporation). ??? ????? ????????.

app-> D:\Folder\app\app\bin\Release\netcoreapp2.0\app.dll
app -> D:\Folder\app\app\obj\Docker\publish\
app-xunit -> D:\Folder\app\app-xunit\bin\Release\netcoreapp2.0\app-xunit.dll
app-xunit -> D:\Folder\app\app-xunit\obj\Docker\publish\
```

> dotnet --info

```
Product Information:
 Version:            2.0.0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

> Dockerfile

```
FROM microsoft/aspnetcore:2.0
ARG source
WORKDIR /app
EXPOSE 555
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "app.dll"]
```

cc @joshua-anderson, @akoeplinger and @nterry.

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by mdekrey** [comment]
It appears that the `Microsoft.Docker.Sdk` is not supported even within Microsoft's own docker containers. As a workaround, I made a new solution configuration called `ci-docker` from Release (no new project configurations so they still build to Release), and unchecked the docker project for that configuration only (as well as others that aren't supported in Travis.)

![image](https://user-images.githubusercontent.com/144461/31046902-d5071d9c-a5c6-11e7-9b9b-90d3f44ab095.png)

Don't forget to update your `-c Release` flag to `-c ci-docker`!

For more details, you can check out the [source of my solution file](https://github.com/mdekrey/GitAutomation/blob/dad7916c7cac7cca065fa5368dea8a8640198aca/GitAutomation.sln), but those aren't terribly readable.
