### ISSUE TITLE
R devel error: "Error: package 'testthat' was installed by an R version with different internals; it needs to be reinstalled for use with this R version"

### ISSUE THREAD

**Issue by virgesmith** [travis-ci/travis-ci#8495]
Hi,

I started getting the above error in a couple of my travis r devel builds (release and oldrel are fine)

My best guess is this started sometime between 11-13 Sept and pretty certain it's not down to my code. (The first build that failed only had a change to the README.md)

See e.g. https://github.com/virgesmith/UKCensusAPI

Package listings in the above repo build logs have:
`testthat     1.0.2   2016-04-23 cran (@1.0.2)` 

DESCRIPTION contains:
```
Depends: R (>= 3.3.3)
Imports:
  reticulate,
  testthat,
```
In another repo (https://github.com/virgesmith/humaleague) it lists
` testthat     1.0.2    2016-04-23 CRAN (R 3.5.0)`
and I get the same error.

Any ideas?  @craigcitro, @hadley and @jimhester 

Thanks

**Comment by hadley** [comment]
You'll need to flush your caches to cause it to get rebuilt.

**Comment by virgesmith** [comment]
worked, thanks!
