### ISSUE TITLE
Build stages are not using sudo: false/required from included jobs 

### ISSUE THREAD

**Issue by sushantdhiman** [travis-ci/travis-ci#8496]
This could be due to mis configuration but I can't figure out reason behind this.

In `sequelize` ([ travis.yml](https://github.com/sequelize/sequelize/blob/660e1bf183a34be33232dc70c1d953e4557d0de6/.travis.yml) ) I have set `sudo: false`, but a few jobs in build stages require sudo, so I have set `sudo: required` for those jobs

Similarly in `sequelize/cli` ( [travis.yml](https://github.com/sequelize/cli/blob/f4090948eee793d43fd758f81384f01480de0643/.travis.yml) )  I have set `sudo: false`, but as none of the jobs require sudo, so build stage has no sudo related configuration.

Now `sequelize/cli` is running everything properly, that means all jobs are running on containers ([recent build](https://travis-ci.org/sequelize/cli/builds/278893675)). But `sequelize` on other hand will run all jobs on gce vm([recent build](https://travis-ci.org/sequelize/sequelize/builds/279576763)).

Am I doing something wrong or build stages does not support this yet?

**Comment by BanzaiMan** [comment]
The configuration for `sequelize/sequelize` [requires `sudo` command in `before_script`](https://github.com/sequelize/sequelize/blob/660e1bf183a34be33232dc70c1d953e4557d0de6/.travis.yml#L35-L36), so we route all the jobs to ones that can handle this.

**Comment by sushantdhiman** [comment]
You are right, but those commands require sudo under specific env variable.

Is there any way to get full control, it seems like a bug where specifying `sudo: false` still gives you a fully virtualized machine. Travis should just throw that user doesn't have sudo permission if they try to run sudo on container builds.

Could moving these commands to a script be a potential solution?
