### ISSUE TITLE
Fail to declare an environment global variable

### ISSUE THREAD

**Issue by localnet** [travis-ci/travis-ci#8501]
This error happens since 2017-09-20.

GitHub ([.travis.yml](https://github.com/localnet/nspawnci/blob/master/.travis.yml)):
```
      env:
        global:
          - TRAVIS_TAG=${NSPAWN_TAGS1}
```

Travis CI ([Job log](https://travis-ci.org/localnet/nspawnci/jobs/279751982)):

> Setting environment variables from repository settings
> $ export GITHUB_TOKEN=[secure]
> $ export NSPAWN_KEYMAP=es
> $ export NSPAWN_LANG=es_ES.UTF-8
> $ export NSPAWN_LOCALTIME=Europe/Madrid
> $ export NSPAWN_TAGS1=repository
> $ export NSPAWN_TAGS2=container

...

> Setting environment variables from .travis.yml
> $ export global=["TRAVIS_TAG=${NSPAWN_TAGS1}"

...

> $ docker cp aurci:/home/pkguser/bin ${TRAVIS_TAG}
> "docker cp" requires exactly 2 argument(s).
> See 'docker cp --help'.
> Usage:  docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
> 	docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH
> Copy files/folders between a container and the local filesystem
> The command "docker cp aurci:/home/pkguser/bin ${TRAVIS_TAG}" failed and exited with 1 during .

**Comment by joepvd** [comment]
The key words `global` and `matrix` for `env` are not recognized within a build stage. Could you try running a build with the `global` keyword dropped from the `env` definition in the phase?

```
env:
- TRAVIS_TAG=${NSPAWN_TAGS1}
```

**Comment by localnet** [comment]
Solved, thank you.

**Comment by DrLuke** [comment]
This should be added to the environment varialbe documentation here: https://docs.travis-ci.com/user/environment-variables/

Would've saved me a couple of hours of debugging...
