### ISSUE TITLE
Remove pagination on the "add repo" page (or add a search field)

### ISSUE THREAD

**Issue by jsmaniac** [travis-ci/travis-ci#8502]
When I go to https://travis-ci.org/profile/jsmaniac, I see a paginated list of repositories which I can activate or de-activate.

When activating a new repository, this means that I have to guess which of the five pages contains it.

Previously, all the repositories would appear in one big list, and I would simply hit <kbd>ctrl</kbd>+<kbd>f</kbd>, flick the switch and move on. Can we go back to the old behaviour and/or add a search field at the top of the list?

For comparison, [coveralls.io](https://coveralls.io/repos/new) has pagination, but at least includes a search field

**Comment by shlomif** [comment]
I ran into this problem today as well. Please look into fixing it.

**Comment by BanzaiMan** [comment]
We have a search field on the page now.

**Comment by shlomif** [comment]
On Tue, 21 Nov 2017 20:09:43 +0000 (UTC)
Hiro Asari <notifications@github.com> wrote:

> We have a search field on the page now.
> 

Great, many thanks! Also thank you for the new dashboard feature - it rocks too!


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Buffy Factoids - http://www.shlomifish.org/humour/bits/facts/Buffy/

My Commodore 64 is suffering from slowness and insufficiency of memory, and its
display device is grievously short of pixels.  Can anybody help?
    — Omer Zak

Please reply to list if it's a mailing list post - http://shlom.in/reply .
