### ISSUE TITLE
Xcode9 supperd？(build、test)

### ISSUE THREAD

**Issue by mingliuboy** [travis-ci/travis-ci#8508]
me create a Xcode 9 project，but travis can't build and test, why?

https://github.com/mingliuboy/hello-world

language:
  objective-c

osx_image: xcode9

install: 
 - rvm reinstall ruby-2.3.0

xcode_project: hello-world/hello-world.xcodeproj

script: ./script/hello-worldBuild.sh

=======================
hello-worldBuild.sh:

xcodebuild clean build test -project hello-world/hello-world.xcodeproj -scheme "hello-world" -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest'

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by mingliuboy** [comment]
Normal, Thanks .
