### ISSUE TITLE
Travis builds suddenly failing with missing gcc

### ISSUE THREAD

**Issue by nonhermitian** [travis-ci/travis-ci#8512]
We are currently having issues with Travis not finding gcc:

```
x86_64-conda_cos6-linux-gnu-gcc -pthread -fno-strict-aliasing -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/travis/miniconda/envs/test-environment/include/python2.7 -c src/C/base.c -o build/temp.linux-x86_64-2.7/src/C/base.o
    unable to execute 'x86_64-conda_cos6-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
```
when building pre-requisite packages.  This just popped up sometime between last night and this morning.

Any suggestions on a resolution would be most appreciated.

**Comment by BanzaiMan** [comment]
Please include relevant build log URLs. Thank you.

**Comment by nonhermitian** [comment]
Please see the following:

https://travis-ci.org/qutip/qutip/jobs/280727756

Thank you for your help.

**Comment by nonhermitian** [comment]
Indeed, it seems that the conda update pulled an updated libgcc package that broke Travis.  The issue has been resolved by not doing the updates, which is fine.  Once again, many thanks for spotting that.

**Comment by DavidLP** [comment]
I have the same issue. May I ask what the solution is now? I guess _not doing the updates_ means `conda update conda`?

**Comment by DavidLP** [comment]
Ok, I see the solution is to not do `conda update conda` in your travis script.
