### ISSUE TITLE
oraclejdk9 (Java 9) does not work with android "language"

### ISSUE THREAD

**Issue by robinst** [travis-ci/travis-ci#8513]
I have a build for a Java project that uses `language: android` (because I want to test on Android as well). I added `jdk: oraclejdk9` to the build matrix but the build fails.

`.travis.yml` here: https://github.com/atlassian/commonmark-java/blob/build-with-java-9/.travis.yml#L5

Output [from build](https://travis-ci.org/atlassian/commonmark-java/jobs/280675032):

```
$ jdk_switcher use oraclejdk9
Switching to Oracle JDK9 (java-9-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-9-oracle
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-9-oracle

[...]

$ java -Xmx32m -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_144
0.01s$ if [ $TEST = java ]; then mvn test -Dsurefire.useFile=false; fi
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

**Comment by BanzaiMan** [comment]
Looks like the Android image didn't get the Oracle JDK 9.

Until it is updated, try this:

```yaml
addons:
  apt:
    packages:
      - oracle-java9-installer

before_install:
  - jdk_switcher use oraclejdk9

⋮ # rest
```

**Comment by robinst** [comment]
Didn't work: https://travis-ci.org/atlassian/commonmark-java/jobs/289338311

> Location: http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz?AuthParam=1508300888_fc932fc74ea9f837529c4bcc722fe513 [following]
> --2017-10-18 04:26:08--  http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz?AuthParam=1508300888_fc932fc74ea9f837529c4bcc722fe513
> Connecting to download.oracle.com (download.oracle.com)|23.63.227.139|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2017-10-18 04:26:08 ERROR 404: Not Found.

**Comment by BanzaiMan** [comment]
Looks like Oracle tanked the archive. You see that the URL the apt package uses returns a 302, but the redirection results in a 404.

**Comment by BanzaiMan** [comment]
See also https://github.com/travis-ci/travis-ci/issues/8600.

**Comment by BanzaiMan** [comment]
It should work now. https://travis-ci.org/BanzaiMan/travis_production_test/builds/295380461#L540

**Comment by robinst** [comment]
Hey. The build you linked has this:

```
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-9-oracle
```

And later:

```
$ java -Xmx32m -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_144
Skipping the install stage due to the configuration.
Skipping the script stage due to the configuration.
```

That doesn't look like it uses JDK 9. Didn't work in my build either.

**Comment by BanzaiMan** [comment]
Hmmm. You're right.

**Comment by karussell** [comment]
@robinst how did you solve this problem? Did you create one branch with `language: java` and another with `language:android`? For our project it would be nice if we could specify these two environments in the travis.yml or maybe the possibility to have two travis files would help too.

**Comment by robinst** [comment]
I didn't solve the problem. This issue is still open and needs to be fixed by Travis.
