### ISSUE TITLE
Cassandra service not starting

### ISSUE THREAD

**Issue by rdingwall** [travis-ci/travis-ci#8514]
Hi there, I'm not sure if this is the correct place to be reporting this bug, but we're having trouble getting the built-in Cassandra service to start: 

```$ sudo service cassandra start
/etc/init.d/cassandra: 72: ulimit: error setting limit (Operation not permitted)
/etc/init.d/cassandra: 73: ulimit: error setting limit (Operation not permitted)

... 

2.05s$ go test -v ./...
panic: gocql: unable to create session: unable to discover protocol version: dial tcp 127.0.0.1:9042: getsockopt: connection refused
```
https://travis-ci.org/monzo/gocassa/jobs/280807993

Note the line that says `Starting Cassandra` is missing (this line is present in [successful builds](https://travis-ci.org/gocassa/gocassa/jobs/159908412#L121)).

The ulimit errors don't seem to be relevant (they are also present in successful builds).

**Comment by bogdanap** [comment]
Hi @rdingwall.
We are tracking this issue as https://github.com/travis-ci/packer-templates/issues/504, so I hope you're ok with me closing this one. Please feel free to track the original issue for updates.

As a workaround until this is fixed, you could try switching to our `sudo: required` infrastructure, which doesn't run in containers and is unlikely to hit the same memory issues.
