### ISSUE TITLE
Feature request: TRAVIS_FAIL

### ISSUE THREAD

**Issue by bsipocz** [travis-ci/travis-ci#8515]
While testing a relatively widely used CI helpers (https://github.com/astropy/ci-helpers) package that takes care of conda/pip installations for python packages, I run into an issue that the expected behaviour of a feature is a failing travis build.

Currently I work around it by listing it under the allowed failures (https://github.com/astropy/ci-helpers/pull/240/files#diff-354f30a63fb0907d4ad57269548329e3R198), but in reality it's not allowed but required to fail. Would it be possible to have such an option?

**Comment by bsipocz** [comment]
I'm having mixed feeling about auto closing feature requests when they are not implemented. Don't get me wrong, I would be OK with a "won't fix/implement" label after proper triaging, but letting the bot close the ones with the "feature-request" label because they were opened a long time ago is a bit unfortunate.

**Comment by BanzaiMan** [comment]
Is this an environment variable to indicate whether or not this job is allowed to fail?
