### ISSUE TITLE
PHPUnit does not run on hhvm

### ISSUE THREAD

**Issue by tomasliubinas** [travis-ci/travis-ci#8516]
PHPUnit does not run on hhvm as PHPUnit6 supports PHP7 only. As current hhvm is compatible with PHP 5.6, PHPUnit version should be selected accordingly.

Example build:
https://travis-ci.org/tomasliubinas/psr7-middlewares/jobs/281028167

Returns with:
`This version of PHPUnit is supported on PHP 7.0 and PHP 7.1.
You are using PHP 5.6.99-hhvm (/usr/bin/hhvm).`

**Comment by BanzaiMan** [comment]
While we work on the fix, try fetching https://phar.phpunit.de/phpunit-5.7.phar to `~/.phpenv/versions/hhvm/bin/phpunit`:

```yaml
before_script:
  - curl -sSf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
```

**Comment by bogdanap** [comment]
We've decided that, rather than revert to an older version of PHPUnit, we'd officially document the workaround.
