### ISSUE TITLE
package:rJava failing to load for Mac OSX Builds of R packages

### ISSUE THREAD

**Issue by russellpierce** [travis-ci/travis-ci#8517]
I'm noticing that packages that depend on rJava are failing to pass because package:rJava isn't loading successfully.  The error I'm seeing is:
```
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/travis/R/Library/rJava/libs/rJava.so':
  dlopen(/Users/travis/R/Library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Users/travis/R/Library/rJava/libs/rJava.so
  Reason: image not found
```

**Comment by BanzaiMan** [comment]
Please mention @craigcitro and @jimhester for R inquiries, as indicated in the build log. Thank you.

**Comment by russellpierce** [comment]
@craigcitro and @jimhester - Sorry I missed that.

**Comment by LiNk-NY** [comment]
Hi Russell, @russellpierce 
This is a known issue for R devel package binaries under Mac. 
It's not a Travis issue and it should be closed.
Regards,
Marcel

**Comment by BanzaiMan** [comment]
Thanks for the ping.

**Comment by russellpierce** [comment]
@LiNk-NY / @craigcitro and @jimhester Who should the issue be raised with in that case?  Are there any known workarounds?
