### ISSUE TITLE
D-Bus spamming when I use firefox

### ISSUE THREAD

**Issue by nkonev** [travis-ci/travis-ci#8520]
In many latest builds I have 
```
(firefox:9067): GConf-WARNING **: Client failed to connect to the D-BUS daemon:

//bin/dbus-launch terminated abnormally without any error message
```

Although it don't fail build, it is too many spamming in console.

I investigated logs, so something happens 
between
https://travis-ci.org/nkonev/blog/builds/272661119 (ok)
https://travis-ci.org/nkonev/blog/builds/273055864 (spam)

As you can see, these builds from same github commit and same firefox version, so I think somebody changed ubuntu image what happen this firefox spamming.

Yes, I'd updated firefox version, but error still present.

**Comment by ilyavf** [comment]
+1 

I am experiencing the same issue.

Here is a full log: https://gist.github.com/ilyavf/27f2c5a8530382883a1bd227f815b4dc

**Comment by BanzaiMan** [comment]
Probably due to the updated maven version (3.3.9 https://travis-ci.org/nkonev/blog/builds/272661119#L368 vs 3.5.0 https://travis-ci.org/nkonev/blog/builds/273055864#L755). Do you see this on your machine?

**Comment by nkonev** [comment]
@BanzaiMan No, I don't see this error in logs on my machine.
And @ilyavf https://gist.github.com/ilyavf/27f2c5a8530382883a1bd227f815b4dc
has non-java application, but has these error.

I don't use your maven, I use maven wrapper, 
```
./mvnw ...
```
which deliver me maven 3.5.0 in both builds

**Comment by nkonev** [comment]
@BanzaiMan 
I installed `dbus-x11` (as recommended [here](https://askubuntu.com/questions/237893/firefox-sluggish-printing-error-message/237917#237917))
My [.travis.yml](https://github.com/nkonev/blog/compare/c9088ef9837e...44c7c1107ab6)
and error [gone](https://travis-ci.org/nkonev/blog/builds/284907677).

Can you add `dbus-x11` into image ? I think it will be useful for another people =)

**Comment by BanzaiMan** [comment]
@nkonev Thanks for the information. I confirm that `dbus-x11` is not a part of the Trusty image. It was on Precise before as a side effect, not by design. If you want to ensure that the package exists for your builds, it is best that you install it.

**Comment by nkonev** [comment]
From viewpoint of a user which wants user firefox: he or she expected that firefox will run ok, but firefox throws error in console. May be there is useful to add this information into doc https://docs.travis-ci.com/user/firefox/ ?

**Comment by BanzaiMan** [comment]
That's a valid point. I see that it is useful to have `dbus-x11` on the base image. Do you mind opening an issue over at https://github.com/travis-ci/travis-cookbooks/, citing this issue and why ("Firefox needs it")? Thank you.
