### ISSUE TITLE
10 minute timeout failure when using travis_wait 30

### ISSUE THREAD

**Issue by krichter722** [travis-ci/travis-ci#8526]
[I just experienced a job to error after 10 minutes when `travis_wait 30 [cmd]` has been used](https://travis-ci.org/krichter722/tomee/jobs/282532805) which would only be logical to me if in

> travis_wait works by starting a process, sending it to the background, and watching the background process. If the command you pass to travis_wait does not persist, then travis_wait does not extend the timeout.

(from https://docs.travis-ci.com/user/common-build-problems/) "persist" means "produce output" (I need to send both stdout and stderr to a log file because it exceeds the 4MB output limit). Since I passed `30` to `travis_wait` I only expect it to timeout after 30 minutes, not 10. I assume that the process is still alive because otherwise `|| head ...` would be executed (which should be `tail`...).

Tip: "persist" is typically used for storing volatile/memory data in a file/permanent store of some kind; when speaking about processes, I'd recommend to use language that everybody is used to, i.e. "keep alive", "remain running", "continue to be executed", etc.

**Comment by BanzaiMan** [comment]
If you have suggestions on improving documentation, please use the "Improve this page on GitHub" button in the upper right corner of the page.

Is there any technical issue you are reporting on here?

**Comment by krichter722** [comment]
> Is there any technical issue you are reporting on here?

Yes, I updated the issue. I have no idea to improve the documentation because I don't understand the behaviour (see above).

**Comment by BanzaiMan** [comment]
The command you defined is:

    travis_wait 30 mvn test verify --batch-mode &> /tmp/tomee-test.log

If `mvn` spawns child processes, `travis_wait` does not check the status of those child processes. If the `mvn` process itself dies, `travis_wait` will not know anything about these child processes, and so it is effectively a no-op.

**Comment by krichter722** [comment]
> If mvn spawns child processes, travis_wait does not check the status of those child processes. If the mvn process itself dies, travis_wait will not know anything about these child processes, and it is effectively a no-op.

I understand. I didn't think about the fact that this is probably caused by the subprocess spawning (probably the surefire maven plugin) and this is covered by the docs. This makes this issue invalid. Since this is potentially hard to understand, you might want to enhance the output with the info that a spawned subprocess might make the timeout no-op, especially if `real timeout < timeout passed as argument`.

A separate issue: I'm sure it's not overly complicated to listen to child processes of the process argument passed to `travis_wait` (which is a subprocess of `travis_wait` or it's interpreter. In doubt parse the output of `ps` or `pstree`. Is `travis_wait` free or open source software?

**Comment by krichter722** [comment]
@BanzaiMan After some time, I came back to this issue and managed to reduce it to a clear problem:

A very simple `.travis.yml`

    language: sh
    script:
    - python script.py

where `script.py` prints numbers from 0 to 1000000 each in a new line and exits with code 1 to simulate a build failure which fails because the 4MB log limit is exceeded, so far so good.

One might want to avoid that without touching the build command by using

    language: sh
    script:
    - python script.py &> /tmp/build.log || (tail -n 100 /tmp/build.log && exit 1)

which works fine (fails the build and prints only the last 100 lines avoiding exceeding the 4MB log limit).

However, it might be necessary to avoid Travis to fail after 10 minutes without output (because everything written to `/tmp/build.log`) which is only possible with `travis_wait`, but

     language: sh
    script:
    - travis_wait 50 sh -c 'python script.py &> /tmp/build.log || (tail -n 100 /tmp/build.log && exit 1)'

both causes the build to succeed when it should fail and prints `/home/travis/.travis/job_stages: line 190:  1721 Terminated              travis_jigger $! $timeout $cmd` (no idea why, I'd expect numbers from 0 to 100 or 0 to 1000000) or the complete output exceeding the log limit again (see https://travis-ci.org/krichter722/tomee/jobs/400470754 for example for the latter case).

I provided an SSCCE at https://travis-ci.org/krichter722/travis-log-exceeded where the latest builds on the branches `master`, `exceed` and `travis-wait` represent the 3 described cases.

[I asked for input on stackoverflow.com](https://stackoverflow.com/questions/46636196/how-to-avoid-log-being-displayed-after-travis-wait) on the issue before I created the much easier reproducer. The suggestion there to change the `travis_wait` implementation didn't work out for me and it seems to be buggy (or I'm not understanding something fundamental) and should thus be fixed for everyone.

**Comment by krichter722** [comment]
I just realized that this only happens because of wrapping the command in `sh -c` which then leads back to the issue being caused by untracked child processes. I still can't wrap my head around this and it's very counter-intuitive. I think this should be covered by warning in the output.

That leaves the question why `travis_wait` can see the output when it's all directed to a file in [this example](https://travis-ci.org/krichter722/tomee/jobs/400470754) and prints it from beginning to shortly before the end before the log limit is exceeded.

**Comment by muschellij2** [comment]
Have something "similar" in https://travis-ci.org/ANTsX/ANTsR/jobs/451223666 where I have `travis_wait` and still getting a build timeout, but there is no "intentional" process spawning here:

```
[0K$ travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;


Still running (1 of 100): R CMD check --timings --as-cran --no-manual --install-args=--build ANTsR_0.4.7.tar.gz
...
Still running (17 of 100): R CMD check --timings --as-cran --no-manual --install-args=--build ANTsR_0.4.7.tar.gz

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```
