### ISSUE TITLE
Job won't start and I don't know why

### ISSUE THREAD

**Issue by NickHeiner** [travis-ci/travis-ci#8529]
This [job](https://travis-ci.org/department-of-veterans-affairs/caseflow/jobs/282772075) has been queued for a while, and I don't know why. It sat for a long time earlier, so I killed it and restarted, but that did not help.

When I click around on the [repo page](https://travis-ci.org/department-of-veterans-affairs/caseflow/), I don't see any indication why my build would not be starting. I don't see other builds ahead of mine in line. For a time, there were no other builds at all.

I wish the Travis UI would tell me why my build was not starting. As a bonus, it could be nice to know how long I should expect to wait. It would also be nice if it said, "these builds are ahead of you in line", so I can go kill those builds if they're not necessary.

![image](https://user-images.githubusercontent.com/829827/31133362-39fdda2a-a82d-11e7-873c-0a28d44e1d0c.png)
 
**Update:** I pushed another branch. The build for that branch started before the one that I posted about here. That confuses me – I would expect branches to be built in the order the commits arrive.

**Update 2:** 40 minutes later, the build still has not started. I have [another build](https://travis-ci.org/department-of-veterans-affairs/caseflow/builds/282781810) that is able to start jobs, but jobs are queued for much longer than usual.

**Update 3:** 52 minutes later, it's finally started.

**Comment by BanzaiMan** [comment]
Most likely due to https://www.traviscistatus.com/incidents/7tb9nm7j4zh7.
