### ISSUE TITLE
Permission denied writing to os.TempDir() in Go tests

### ISSUE THREAD

**Issue by dmjones500** [travis-ci/travis-ci#8530]
My build is failing for https://github.com/dmjones500/go-stash/ because I'm unable to write to a temporary file during my test.

Example failing build: https://travis-ci.org/dmjones500/go-stash/jobs/282866603

My test includes the code:

````go
func makeTempFilename() string {
	rand.Seed(time.Now().UnixNano())
	return fmt.Sprintf("%stest-%d", os.TempDir(), rand.Int())
}
````

The tests, which pass on my dev machine, fail with:

````
?   	github.com/dmjones500/go-stash	[no test files]
=== RUN   TestEmptyFileGetsCreated
--- FAIL: TestEmptyFileGetsCreated (0.00s)
	Error Trace:	stash_test.go:53
	Error:      	Expected nil, but got: failed to write database to '/tmptest-8322247961885827364': open /tmptest-8322247961885827364: permission denied
	Error Trace:	stash_test.go:56
	Error:      	Expected nil, but got: &os.PathError{Op:"stat", Path:"/tmptest-8322247961885827364", Err:0x2}
=== RUN   TestFlush
--- FAIL: TestFlush (0.00s)
	Error Trace:	stash_test.go:73
	Error:      	Expected nil, but got: &os.PathError{Op:"stat", Path:"/tmptest-1342684630198096033", Err:0x2}
=== RUN   TestEmptyFileWriteThenRead
--- FAIL: TestEmptyFileWriteThenRead (0.00s)
	Error Trace:	stash_test.go:81
	Error:      	Expected nil, but got: failed to write database to '/tmptest-4412455961041140558': open /tmptest-4412455961041140558: permission denied
FAIL
FAIL	github.com/dmjones500/go-stash/stash	0.004s
````

Is there a specific path I should be using for temporary files? According to the [Go documentation](https://golang.org/pkg/os/#TempDir), I can tweak the result of `os.TempDir()` by setting `$TMPDIR`, so that would be an obvious solution.

**Comment by dmjones500** [comment]
My build is working with `TMPDIR=/tmp/` in my YAML file. I'll leave this open in case this is a bug worth fixing (I think `os.TempDir()` should return something writeable for Go tests).

**Comment by BanzaiMan** [comment]
`$TMPDIR` should be empty. https://travis-ci.org/BanzaiMan/travis_production_test/builds/282923963#L450

**Comment by dmjones500** [comment]
Is there another solution that would avoid setting `TMPDIR`?

**Comment by BanzaiMan** [comment]
I see your mistake now. Everything is working as documented and correctly.

Notice that
```go
fmt.Sprintf("%stest-%d", os.TempDir(), rand.Int())
```

returns string such as `/tmptest-4412455961041140558`, which was indeed what the error message said.

What you need instead is

```go
fmt.Sprintf("%s/test-%d", os.TempDir(), rand.Int())
```

so that you'd have `/tmp/test-4412455961041140558`.

Closing.

**Comment by dmjones500** [comment]
*holds head in shame*

Thanks for spotting that :-)
