### ISSUE TITLE
TravisCI Org still posting status update to GitHub when deactivated

### ISSUE THREAD

**Issue by mauricioabreu** [travis-ci/travis-ci#8532]
Ok, it is strange. I contribute to this project (https://travis-ci.org/luanfonceca/speakerfight) and even after disabling the project it is still being tested on Travis CI Org.

Is this a bug? I already removed the .travis.yml and it did not make any effect at all.

**Comment by BanzaiMan** [comment]
What do you mean by "still being tested"? The last build was https://travis-ci.org/luanfonceca/speakerfight/builds/269277761, on August 28.

**Comment by mauricioabreu** [comment]
@BanzaiMan See https://github.com/luanfonceca/speakerfight/pull/299

This is a new pull request. TravisCI is disabled and Github integration was removed. Is it a Github bug or Travis CI bug? Or not a bug at all? Thank you!

**Comment by BanzaiMan** [comment]
This is bizarre. Our record shows that the repository is indeed disabled, but somehow there is a post  shown on GitHub. To make it even more interesting, there is no trace of our posting this on the commit in question. https://api.github.com/repos/luanfonceca/speakerfight/statuses/72c8bfedaec427f0c411211e07e59de6465712b0 The statuses associated with this commit are either `ci/circleci` or `pyup.io/safety-ci`:

```sh-session
$ curl -sSf https://api.github.com/repos/luanfonceca/speakerfight/statuses/72c8bfedaec427f0c411211e07e59de6465712b0 | jq .[].context
"ci/circleci"
"pyup.io/safety-ci"
"pyup.io/safety-ci"
"ci/circleci"
"ci/circleci"
```

I've checked our logs, but there is nothing on our end over the last few days concerning this repository. So I'm afraid there is not much we can do here.

I suggest contacting GitHub support.

**Comment by mauricioabreu** [comment]
Thanks for your help! I will contact Github support.

**Comment by BanzaiMan** [comment]
I am curious to know what is happening here, so I'd appreciate the update if you hear anything worth sharing from GitHub. Thank you!

**Comment by mauricioabreu** [comment]
@BanzaiMan I opened a support ticket at Github Support. I will post any received feedback here.
