### ISSUE TITLE
Can't find repository that I'm contributor

### ISSUE THREAD

**Issue by afucher** [travis-ci/travis-ci#8534]
I want to add travis-ci to a public github repository that I'm contributor, but travis don't show it.
It's possible to do that? Or have any plans to add this?

**Comment by BanzaiMan** [comment]
Which repository is this? Were you added to the repo recently? If so, please try syncing data. Also, we've added pagination to the repos list, so you may have to click a few times to see it.

**Comment by afucher** [comment]
Repo: https://github.com/killerall/advpl-vscode

No, I've been added last year. But I also try to sync and doesn't work.
Yeah I see the pagination, but steel don't find it.

**Comment by BanzaiMan** [comment]
Could you add a screen shot of https://travis-ci.org/profile/afucher? Thanks.

**Comment by afucher** [comment]
Hi, I have 53 repositories, that is 3 pages on profile. Do you want a screen shot from all the 3 pages?

**Comment by BanzaiMan** [comment]
Yes.

**Comment by afucher** [comment]
![page1](https://user-images.githubusercontent.com/3756185/31293204-cb0cc25c-aaac-11e7-8950-0082e582909a.png)
![page2](https://user-images.githubusercontent.com/3756185/31293202-cb08c54e-aaac-11e7-914b-334340e481ad.png)
![page3](https://user-images.githubusercontent.com/3756185/31293203-cb08c97c-aaac-11e7-9cd1-fc280a298d52.png)

**Comment by BanzaiMan** [comment]
Thanks. I do see that you are recognized as a member of the repo, but it appears that we are not showing it somehow. We'll look into it.

**Comment by BanzaiMan** [comment]
Looks like the user `killerall`'s data were out of sync. I've resync'd them. You should see killerall/advpl-vscode now.

**Comment by danielkz** [comment]
@BanzaiMan Hi,
Unfortunately, I have the same problem. 
I'm a contributor to this public repo: https://github.com/mmnaseri/summer 
But it's not listed on my travis-ci.org profile: 
![image](https://user-images.githubusercontent.com/5167562/33857219-0500d748-dee0-11e7-85b6-1f4b09a42690.png)

**Comment by BanzaiMan** [comment]
@danielkz You have push access to that repo, but not admin access, which I believe you need to enable it. Please ask the account owner.

**Comment by mmnaseri** [comment]
I see. I have two options:

1. Set up an organization, move this repo to the org, and make us both the admins
2. Transfer ownership to you, make you the only admin.

I am going to do the first.

**Comment by afucher** [comment]
@BanzaiMan sorry for the delay... but I still don't find the repo in my account

**Comment by BanzaiMan** [comment]
@afucher The same for you. You don't have admin access to this killerall/advpl-vscode.

**Comment by afucher** [comment]
But I just can be admin if is a organization repository, right? Or a repo that I'm owner...

**Comment by BanzaiMan** [comment]
@afucher I believe so.

**Comment by afucher** [comment]
Ok, thks!

**Comment by afucher** [comment]
There is any plan to add this feature? Not need to be an admin?

**Comment by BanzaiMan** [comment]
Admin privileges should be extended to only admins.

**Comment by Gerrit0** [comment]
Apparently you now need to have owner permissions on a repository, not just admin. It makes sense to require admin permissions, but owner seems excessive. Am I missing something?

> ### Prerequisites
> Owner permissions for a project hosted on GitHub. - [Travis CI Tutorial](https://docs.travis-ci.com/user/tutorial/)

**Comment by viniciusd** [comment]
Can't find a personal repository to which I was added as a contributor. How should we proceed? Given it does not belong to an organization, it does not have admin rights settings

**Comment by Jaman-dedy** [comment]
I have the same issue, I'm a contributor on a project but I can't see the repository, It should be easy if you could add the functionality... So, am I supposed to be an admin or the owner to see it??
