### ISSUE TITLE
Problems fetching dockerhub images in build env

### ISSUE THREAD

**Issue by zhljen** [travis-ci/travis-ci#8535]
I'm seeing this in our build this morning. The problem is consistent. Here's my build https://travis-ci.org/Netflix/metacat/builds/283749976?utm_source=github_status&utm_medium=notification

A similar issue https://github.com/travis-ci/travis-ci/issues/7367

**Comment by zhljen** [comment]
The error message:
8.0-jre8: Pulling from library/tomcat
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/c9/c9ceb95da54b27d4374a17474ead0b121dfdb6964c895f699fa8f36945b73d8b/data?Expires=1507222173&Signature=KehqTG56o95sC849tMIetIPZ-L6GhXf9vUPl0EA0k0tmSP9qkQPvdR-6AmIGWW0BbUiBpeJSj15XiMkmhVfCJ5pMrgClgu9sQtcPDNnST9aqONSDltmNr8B2LYnAdiZWc3FL0a424fQHPe2lkSBHx5NBnxkxX6SrRvCuWG2T5Lc_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout

**Comment by BanzaiMan** [comment]
Did you restart https://travis-ci.org/Netflix/metacat/builds/283749976? Could it have been a transient network problem?

**Comment by zhljen** [comment]
It passed late yesterday. The problem have been consistently happening for hours.

**Comment by BanzaiMan** [comment]
Seems OK now.
