### ISSUE TITLE
PEAR installer roles don't work in PHP 5.6 and 7.0

### ISSUE THREAD

**Issue by yunosh** [travis-ci/travis-ci#8541]
This may be related to issue #8350. After working around that issue by running `pear channel-discover pear.horde.org` manually, installing Horde_Role succeeds, but the installer role is not registered. https://travis-ci.org/horde/Core/jobs/284173861#L483 is such an example, it says: 
> `File "unittest.js" in directory "<dir name="scriptaculous">" has invalid role "horde", should be one of cfg, data, doc, man, php, script, test, www`

**Comment by yunosh** [comment]
https://travis-ci.org/horde/Core/builds/284173854 has examples of working and non-working PHP versions.

**Comment by yunosh** [comment]
Looks like it all boils down to paths not being set correctly.
PEAR packages are installed in (e.g.) /home/travis/.phpenv/versions/5.6.31/lib/php/pear: https://travis-ci.org/horde/Yaml/builds/284216422#L1280
But the PHP include_path is set to (e.g.) /home/travis/.phpenv/versions/5.6.31/share/pear: https://travis-ci.org/horde/Yaml/builds/284216422#L1378

**Comment by BanzaiMan** [comment]
I think this is a different manifestation of https://github.com/travis-ci/travis-ci/issues/8365.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/1201 has been merged and deployed. I'm closing this optimistically, but if you continue to see problems, do let us know.

**Comment by yunosh** [comment]
Looks good, thanks!
