### ISSUE TITLE
use `branch` over `push` for GitHub status

### ISSUE THREAD

**Issue by tooomm** [travis-ci/travis-ci#8542]
In the status check overview - if you create a pr to master from a branch within the same repo - you have two builds displayed :
- **continuous-integration/travis-ci/pr** — The Travis CI build passed 
- **continuous-integration/travis-ci/push** — The Travis CI build passed 

In general it just sounds more on-spot to use branch, no? Other services use `pr` and `branch` too. 

**Also, in the travis settings the enabling feature is named `Build branch updates` (not `Build pushes` or something!) and `Build pull request updates` respectively.**
![travis_settings](https://user-images.githubusercontent.com/9874850/31286209-c5e7aff6-aabd-11e7-8edd-ccb6be080d0f.png)

Related code might be here: https://github.com/travis-ci/travis-tasks/blob/master/lib/travis/addons/github_status/task.rb#L78

**Comment by styfle** [comment]
Related to #1147

**Comment by tooomm** [comment]
What happened to your fixing pr (https://github.com/travis-ci/travis-tasks/pull/105) @BanzaiMan?

**Comment by tooomm** [comment]
From the linked pr in the travis-tasks repo:
>With the release of the GitHub Checks API, I think it would be best to close this for the time being.

With GitHub Checks API it looks like this and is worded better:
![](https://user-images.githubusercontent.com/9491603/40001584-d0238d68-578e-11e8-892b-133eda0769d6.png)
