### ISSUE TITLE
build status badge doesn't appear

### ISSUE THREAD

**Issue by pushcx** [travis-ci/travis-ci#8543]
Hi. We copied the build status badge markdown into our project's readme and it doesn't appear.

Repo: https://github.com/lobsters/lobsters

Markdown: `[![Build Status](https://travis-ci.org/lobsters/lobsters.svg?branch=master)](https://travis-ci.org/lobsters/lobsters)`

Generated HTML: `<a href="https://travis-ci.org/lobsters/lobsters"><img src="https://camo.githubusercontent.com/a2c99db8067b790e507f305578775150b211a48a/68747470733a2f2f7472617669732d63692e6f72672f6c6f6273746572732f6c6f6273746572732e7376673f6272616e63683d6d6173746572" alt="Build Status" data-canonical-src="https://travis-ci.org/lobsters/lobsters.svg?branch=master" style="max-width: 100%; display: none !important;" hidden=""></a>`

Weirdly, the image request isn't even in the network panel - not the the `travis-ci.org` or the `camo.githubusercontent.com` rewritten image (placeholder?). If I navigate directly to the image url, it works.

**Comment by BanzaiMan** [comment]
I see the badge on this page. 
![lobsters_lobsters__rails_code_running_the_lobsters_link_aggregation_site](https://user-images.githubusercontent.com/25666/31296761-79783db8-aab1-11e7-8dd9-eaa33dd9435b.png)

**Comment by pushcx** [comment]
Oops, adblock.

For anyone else who runs into this, it was the rule `/\.com\/.*[a-f0-9]{110}/$third-party,image` in Fanboy’s Enhanced Tracking List. I was able to add an exception for the domain `camo.githubusercontent.com`.
