### ISSUE TITLE
Auto-Deploy of the  GitHub relases TAG

### ISSUE THREAD

**Issue by Hexer10** [travis-ci/travis-ci#8544]
I've setupped properly the Automatic Deploy of the GitHub relases, but now I'm asking if there's anyway to choose the tag name of the new relase, because now it's like: `untagged-3df167002906725ee9b5`

Thanks in advance.

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

>  If the branch name is not known ahead of time, you can specify `all_branches: true` instead of `branch: **` and use other conditions to control your deployment.

**Comment by BanzaiMan** [comment]
Why you get the tags of the form `untagged-HEX` is discussed here: https://github.com/travis-ci/travis-ci/issues/8185

I'm closing this.
