### ISSUE TITLE
Cannot include OSX PHP build in matrix

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#8547]
Consider this simple yml config:

    language: php

    php:
      - 5.6
      - 7.0
      - 7.1

    # lock distro so new future defaults will not break the build
    dist: trusty

    matrix:
      include:
        - php: 7
          os: osx

    sudo: false

    install:
      - COMPOSER_ROOT_VERSION=`git describe --abbrev=0` composer install --no-interaction

    script:
      - ./vendor/bin/phpunit --coverage-text

The OSX build fails when installing PHP: 

  - `/Users/travis/.travis/job_stages: line 57: phpenv: command not found` (https://travis-ci.org/andig/socket/jobs/285001470#L30) or 
  - `ln: /Users/travis/.phpenv/versions/7: No such file or directory` (https://travis-ci.org/andig/socket/jobs/284812888#L30)

**Comment by BanzaiMan** [comment]
We do not support PHP on the Mac. See #2313.
