### ISSUE TITLE
Deploy to GitHub pages fails to push 

### ISSUE THREAD

**Issue by Midnighter** [travis-ci/travis-ci#8548]
I have a repository whose purpose is to build a website upon commit to `master` and push the result to the `gh-pages` branch of a different repository.

The deploy step fails without any error message that would allow me to investigate the issue further. It simply reads `Couldn't push the build to github.com/opencobra/cobrapy.git:gh-pages`. You can find the failing build [here](https://travis-ci.org/opencobra/cobrapy-website/builds/284858838).

You can see the `.travis.yml` of the website repo [here](https://github.com/opencobra/cobrapy-website/blob/master/.travis.yml).

I used the same configuration before with a dummy repository of my own to test it and there the deploy step worked just fine. You can see that build log [here](https://travis-ci.org/opencobra/cobrapy-website/builds/281213158).

Any advice on how to investigate this issue further is much appreciated. Thank you in advance.

**Comment by BanzaiMan** [comment]
A possible explanation is that your GitHub token is wrong. Please double check it.

**Comment by Midnighter** [comment]
As I said, I successfully used that token to deploy to a test repository. So can you define 'wrong'? In the meantime I will generate a new token and try again.

**Comment by Midnighter** [comment]
The difference between the repositories is that one, which worked, was my personal repo and the other that fails belongs to an organization. I am admin for the second repository but does the token need some additional scope?

**Comment by BanzaiMan** [comment]
It should not.

**Comment by Midnighter** [comment]
I tried again with a new token that has `repo` scope and restarted the build. Same error :(

**Comment by Midnighter** [comment]
So, unlike on my own dummy repository the `gh-pages` branch on the real repo is protected. However, with administrator privileges force pushing should still be possible.

**Comment by Midnighter** [comment]
Alright, turning off branch protection solved the issue. However, I don't quite understand. Protecting the `gh-pages` branch is quite desirable and being a token from an admin user should prevent this from being a problem.

Either way some option for a more verbose error output on deploy would be quite helpful.

**Comment by robertmain** [comment]
@Midnighter I think it's because the `gh-pages` deployment provider for travis uses `git push -f` to do the deployment to the `gh-pages` branch. So if the branch is protected, then the force push is gonna fail.

**Comment by Midnighter** [comment]
@robertmain indeed. I thought having a token with admin rights would allow force pushing but that's not the case.

**Comment by client9** [comment]
Oddly seemed to stop working a few days ago.

Not sure what the right behavior is.  Perhaps this is just a documentation issue.  But the lack of any error message or context seems like a real bug.

```
Doing the git push (workdir: /tmp/d20180311-3577-1273fda/work)...
Couldn't push the build to github.com/client9/client9.github.io.git:master
failed to deploy
```

**Comment by BanzaiMan** [comment]
@client9 See #9312.
