### ISSUE TITLE
Any build that requires running `apt-get update` fails

### ISSUE THREAD

**Issue by 13steinj** [travis-ci/travis-ci#8554]
Say I have a script in my repository, `install/travis.sh`, and this script calls `apt-get update`, and `.travis.yml` calls my `install/travis.sh`, it causes `install/travis.sh` to exit with code 100 and the build to fail. This is because the gpg key for the mongo db repository has expired, and when trying to hit the repo it fails due to the expired GPG key.

I'm not going to list the key ID in case it's a matter of security, for for anyone who can debug builds you can find it by running `sudo apt-key list | grep expired`.

This occurs on both stable and edge groups

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
I just tried it and it's working for me. https://travis-ci.org/BanzaiMan/travis_production_test/builds/285281759#L414

**Comment by 13steinj** [comment]
https://travis-ci.com/13steinj/moakler/jobs/93654496

The above fails because when running `apt-get update` the mongodb repo key is expired. I've tried updating the key manually by going into a debug build to no avail as it either doesn't exist or I don't know what key server it is on. However removing the failing repo from /etc/sources/list.d allows it to continue without issue.

**Comment by BanzaiMan** [comment]
Ah, I apologize. I missed the critical detail about this issue being restricted to mongodb.org.

**Comment by BanzaiMan** [comment]
I don't think our default setup includes mongodb.org APT source. What are you doing in `install/travis.sh`? I see that you are installing 3.2, so you should be following the instructions here: https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-ubuntu/.

**Comment by JimBobSquarePants** [comment]
Here's the specific error reported in my builds if that helps anyone.

```
W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release: The following signatures were invalid: KEYEXPIRED 1507497109
```

https://travis-ci.org/SixLabors/ImageSharp.Web/builds/285289250

We didn't have issues prior to today and have pushed no changes. I'm way outside my comfort zone here so is there something external that would have changed that I now need to update my [yml](https://github.com/SixLabors/ImageSharp.Web/blob/b0e10feec78cd1b8d1f895508f6f218742c0a6d7/.travis.yml) file to account for?

**Comment by 13steinj** [comment]
Before that point all that I am doing is loading in some configuration, and then right after this running `apt-get update`. However none of the configuration alters anything in terms of the source repositories, servers, or gpg keys-- just loads some variables that let other parts of the script know where certain important files/values in the project are.

Along with @JimBobSquarePants, I didn't have this issue until today and have made changes only to the script section (I just pushed some added tests which run far after the section in which this issue occurs).

@JimbobSquarePants, a temporary fix would be to do `sudo rm /etc/apt/sources.list.d/mongodb-3.2.list` before wherever you are running `apt-get update` so long as you're okay with also setting `sudo: required` in your yml and that mongodb isn't a dependency of your application, directly or as a dependency of some other dependency. (I would do this but for me it's a bit of a hack and instead I can wait for a proper fix).

**Comment by BanzaiMan** [comment]
I see that now. Thanks.

Epoch 1507497109 converts to Sunday October 08, 2017 21:11:49 UTC, so the expiration is just about 4 hours ago.

**Comment by BanzaiMan** [comment]
If you have a choice, removing the MongoDB 3.2 list should fix the problem:

```
sudo rm /etc/apt/sources.list.d/mongodb-3.2.list
```

The C# case is not applicable here, because the customizable steps won't have a chance to fix it, unfortunately.

**Comment by BanzaiMan** [comment]
It is not clear if the fix will come from mongodb.org (not clear to me if it's possible to re-upload a valid key, and if so, if the key ID would be identical to the previous one).

The offending APT source will have to be removed on the fly, I think.

**Comment by 13steinj** [comment]
There must be a way to re-upload a valid key, because there are ways for a client to update an old expired key with just a known keyserver to get the new valid key and the old key's ID (`sudo apt-key adv --keyserver <server ip> --recv-keys <key id>`) So I guess the only question is if and or when will the mongodb team get around to it.

**Comment by tsimbalar** [comment]
Hi,
I've had a similar issue in that build : https://travis-ci.org/serilog/serilog/builds/285388771?utm_source=github_status&utm_medium=notification

 /cc @nblumhardt .

**Comment by vmalloc** [comment]
Having similar issues with my build but I do not depend on Mongo at any point. I'm guessing this is some dependency that belongs to Travis. Is there any way to force it not to be used?

**Comment by adrienjoly** [comment]
Adding [that line](https://github.com/hyperledger/composer/pull/2318/files) in the `before_install` section of my `.travis.yml` file solved the problem. Thanks, @sstone1!
