### ISSUE TITLE
inline build matrix does not work with allow_failures

### ISSUE THREAD

**Issue by KyleSanderson** [travis-ci/travis-ci#8559]
https://github.com/alliedmodders/sourcemod/blob/d90975c1c76e3800383b7b43e15f8e773a109f16/.travis.yml

Throwing in the towel, this just doesn't seem possible with travis-ci to manually specify packages to install and couple this with allow_failures. Following the example on https://docs.travis-ci.com/user/languages/c/ rendered the inability to take advantage of fast_finish and allow_failures.

**Comment by BanzaiMan** [comment]
Could you elaborate on what issue you are facing?

The build corresponding to https://github.com/alliedmodders/sourcemod/commit/d90975c1c76e3800383b7b43e15f8e773a109f16 is https://travis-ci.org/alliedmodders/sourcemod/builds/285846377, which does not reveal any problem to me.

Please explain what you observed (what you believe is an error) and what you expected to happen.

Thanks.

**Comment by KyleSanderson** [comment]
Sorry, the issue is that you can't mark builds that are "included" into the build matrix as excluded/fail-able.

https://github.com/alliedmodders/sourcemod/blob/2ccaa376baf3052b8f5c630c10b7744ad1e40c4f/.travis.yml is what I settled on as a middle ground, I know there's another issue in there being the two package statements that I need to quell at some point, but the existing issue remains.

**Comment by BanzaiMan** [comment]
What do you mean by

> builds that are "included" into the build matrix

What are quotation marks for? There is no `matrix.include` in https://github.com/alliedmodders/sourcemod/blob/d90975c1c76e3800383b7b43e15f8e773a109f16/.travis.yml, and there is no equivalent in it that I can see.

**Comment by KyleSanderson** [comment]
Apologies, I actually linked to another blob in the reply 32 minutes ago that should hopefully explain where I landed...

https://github.com/alliedmodders/sourcemod/blob/36f9a8ed7a8f5c85799a42822e94be4823eb3fd2/.travis.yml is another revision with the previously mentioned defect removed, leaving only the original issue now.

**Comment by BanzaiMan** [comment]
@KyleSanderson Could you explain what you are expecting to happen in https://travis-ci.org/alliedmodders/sourcemod/builds/286347066? There are 10 jobs defined, and the jobs allowed to fail are all allowed to do so.

**Comment by KyleSanderson** [comment]
@BanzaiMan I want to be able to list `MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"` as an allowed failure. At the moment this section does not seem to support included jobs in the build matrix.

**Comment by BanzaiMan** [comment]
@KyleSanderson Do you have a build that _does_ have `MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"` in the `matrix.allow_failures` array? In other words, what have you tried?

**Comment by KyleSanderson** [comment]
@BanzaiMan yes. They were all ignored. 

https://github.com/alliedmodders/sourcemod/blob/167578789b963ca7e8f19b92260083ec7001a8e0/.travis.yml

**Comment by BanzaiMan** [comment]
Perhaps I am missing something obvious, but https://github.com/alliedmodders/sourcemod/blob/167578789b963ca7e8f19b92260083ec7001a8e0/.travis.yml#L236-L242 does not define `MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"` as a job.

**Comment by KyleSanderson** [comment]
@BanzaiMan yes you're right.

``` - env: MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
    - env: MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - env: MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
    - env: MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
```

Will all show the bug. Try it.

**Comment by BanzaiMan** [comment]
I'm sorry, but I think we have a communication problem.

Please include:

1. The build page URL that shows the problem you are experiencing.
1. What you expect to happen.
1. What you are observing instead.

Earlier in https://github.com/travis-ci/travis-ci/issues/8559#issuecomment-335982417 you indicated that you want to allow `MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"` job to fail, but I have not seen a _*complete*_ configuration and the build log that back up this claim. Thanks.

**Comment by BanzaiMan** [comment]
Closing, as it's become stale.
