### ISSUE TITLE
Potential conflict of interests between Free Software ideals and TravisCI's support of proprietary technologies

### ISSUE THREAD

**Issue by thoward** [travis-ci/travis-ci#856]
Recently, on issue #216 (support for Windows and Max OSX), an observation was made by @tjordanchat that enabling support for those operating systems is in conflict with the [Free Software](http://en.wikipedia.org/wiki/Free_software) ideals. 

Part of this discussion is a question about whether or not this conflicts with the mission statement of @travis-ci, it's donation process, and it's use of donation monies. @tjordanchat contends that @travis-ci claims to align with the Free Software interests, and that donations made on love.travis-ci.org are expected to be used in accordance with Free Software's ideas and restrictions.

Currently, the discussion is happening on issue #216, which is causing the comment thread there to diverge from it's original topic, and also not properly identifying @tjordanchat's concerns as a separate issue. This Github issue is meant to provide a place to allow this discussion to happen, and hopefully to be resolved. 

Some possible resolutions actions might be:
- An official public statement made about @travis-ci's stance on Free Software
- A specific and unambiguous public document which describes exactly how donations will be used
- A general public offer to refund monies to anyone who made a donation prior to the release of those documents, who feels that they were misled and does not agree with the use of the donation monies that have already given

Personal Note: 

For full disclosure, I'm creating this issue as a matter of process and personally have no strong opinion about the topic. I did donate to http://love.travis-ci.org and I am content with the decisions that the @travis-ci team have made thus far. That said, my opinion is not the only one, and it's fair to make a dedicated space for this discussion and possibly to agree to some basic actions to ensure that this issue is resolved. Specifically, this is a question of transparency which is something I **do** feel very strongly about. If there is any need to improve transparency, that should be identified and steps taken to resolve. 

Thanks,
@thoward

**Comment by cavaliercoder** [comment]
Take comfort friends, two years on, this thread is still generating lols. Thanks Travis team for providing an excellent service!
