### ISSUE TITLE
Consider setting DOTNET_CLI_TELEMETRY_OPTOUT for .NET projects

### ISSUE THREAD

**Issue by nikeee** [travis-ci/travis-ci#8560]
When running .NET Core, we should consider opting out oft Telemetry collection. This is done by setting the environment variable `DOTNET_CLI_TELEMETRY_OPTOUT` to `1`. It seems that telemetry is collected during installation, so the environment variable should be set beforehand.

If [this](https://github.com/travis-ci/travis-build/blob/8067d586b03d5cde21b034e6fbcfa561f5c66748/lib/travis/build/script/csharp.rb#L104) is the relevant spot, I'd create a PR.

Related links:
- https://github.com/dotnet/cli/issues/3093
- https://news.ycombinator.com/item?id=15439001
- https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry

cc @joshua-anderson, @akoeplinger and @nterry.

**Comment by akoeplinger** [comment]
Yes, that would be the correct spot to insert the env variable.

**Comment by nikeee** [comment]
PR: https://github.com/travis-ci/travis-build/pull/1191

**Comment by BanzaiMan** [comment]
The PR has been merged and deployed.
