### ISSUE TITLE
travis_wait should extend wait time if input is received

### ISSUE THREAD

**Issue by abitrolly** [travis-ci/travis-ci#8575]
Without `travis_wait` a build was failing with `No output has been received in the last 10m0s` in 40 minutes because the last binary assembly step is indeed long, but with `travis_wait` that build fails after 20 minutes with `Timeout (20 minutes) reached.`. Looks like `travis_wait` doesn't reset its timer if the input is received.

**Comment by BanzaiMan** [comment]
`travis_wait` watches the process it spawns, not STDOUT. Such a functionality goes beyond its intended purpose, and is impractical to implement at this time.

**Comment by abitrolly** [comment]
@BanzaiMan what is the intended purpose then? And source.. From [the docs](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) it is made to extend the program timeout if no output is being received. So it doesn't fulfill its purpose - it kills program even if output is received.

**Comment by BanzaiMan** [comment]
The purpose is to extend the time limit.

> `travis_wait` then writes a short line to the build log every minute for 20 minutes, extending the amount of time your command has to finish.

The clock starts when the command starts, and it is not reset.

**Comment by abitrolly** [comment]
@BanzaiMan is it used anywhere else, except for the above scenario of "extend the program timeout if no output is being received"? Because it does a poor job in this user story.
