### ISSUE TITLE
Cannot trigger build via REST API for a commit with `[skip ci]` in it's message

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#8578]
Unable to trigger build manually via REST API for a commit with `[skip ci]` in it's message.

Not triggering a build automatically if a commit has `[skip ci]` in it's message is fine. But if one tries to trigger a build for it manually via REST API, it should be definitely launched as a result. Right now it's not, and the displayed reason at the `Requests` page of the repo's dashboard is:
> Build skipped via commit message.

![image](https://user-images.githubusercontent.com/4777512/31507120-3e128faa-af82-11e7-9513-1b07383365df.png)

**Comment by BanzaiMan** [comment]
I think this is the correct behavior. API simply creates a build request; all other conditions should still be met for the build to actually be accepted.

Is there a reason that you can’t push a new commit?

**Comment by Deilan** [comment]
I have a repo with a bundler, which clones multiple separate repos and bundles them to make a final distributable app as a part of CI/CD in Travis. The bundler repo changes rarely, builds for it are being triggered using REST API, therefore there is no need to push new commits to launch new builds. Some changes to bundler doesn't need to or shouldn't trigger new builds on commit, therefore I use `[skip ci]` for them, and here comes the subject issue.

**Comment by jakirkham** [comment]
So you can change the commit message used by the build when using the API.
