### ISSUE TITLE
Make some logos look more human

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis-ci#8584]
[Tessa-pride.svg](https://github.com/travis-ci/travis-web/blob/master/public/images/logos/Tessa-pride.svg) and [TravisCI-Mascot-pride.svg](https://github.com/travis-ci/travis-web/blob/master/public/images/logos/TravisCI-Mascot-pride.svg) have a very unrealistic paper white skin color. Why not make them have realistic skin color like the rest of logos?

[TravisCI-Mascot-pride.svg](https://github.com/travis-ci/travis-web/blob/master/public/images/logos/TravisCI-Mascot-pride.svg) and [TravisCI-Mascot-pride-4.svg](https://github.com/travis-ci/travis-web/blob/master/public/images/logos/TravisCI-Mascot-pride-4.svg) also have a rainbow-painted mustache. Why not make his helmet rainbow colored like [Tessa-pride.svg](https://github.com/travis-ci/travis-web/blob/master/public/images/logos/Tessa-pride.svg) and [Tessa-pride-4.svg](https://github.com/travis-ci/travis-web/blob/master/public/images/logos/Tessa-pride-4.svg) instead? This would look more consistent and less weird, unless that's intended.

**Comment by BanzaiMan** [comment]
Thanks for the feedback. We'll pass it on to our design team.

**Comment by bardiharborow** [comment]
I personally really liked the rainbow mustache. 😄

**Comment by koops76** [comment]
@bardiharborow It looks too weird and not "professional" to some people.
