### ISSUE TITLE
nix: `curl` warning when fetching packages

### ISSUE THREAD

**Issue by vaibhavsagar** [travis-ci/travis-ci#8588]
I'm getting this warning from `curl` when fetching paths for each path that I fetch:

```
Warning: /home/travis/.curlrc:1: warning: '-sS' uses unquoted white space in 
Warning: the line that may cause side-effects!
```

For example, see [this build](https://travis-ci.org/vaibhavsagar/website/builds/287838201)

cc @domenkozar @garbas @matthewbauer

**Comment by matthewbauer** [comment]
Yeah sorry about that. I'm hoping travis-ci/travis-build#1202 fixes it.

**Comment by vaibhavsagar** [comment]
No worries, thanks for the quick fix!

**Comment by BanzaiMan** [comment]
PR has been merged and deployed.
