### ISSUE TITLE
In an after_success curl, some env variables are not replaced

### ISSUE THREAD

**Issue by SchulteMarkus** [travis-ci/travis-ci#8597]
Hi there,

I am using Travis for my project [metric-html-report-as-part-of-travis-demo](https://github.com/SchulteMarkus/metric-html-report-as-part-of-travis-demo).
In the project's [travis.yml](https://github.com/SchulteMarkus/metric-html-report-as-part-of-travis-demo/blob/github/.travis.yml#L32), I am having a "curl" command. Which works fine so far. As you can see in the [Travis build logs](https://travis-ci.org/SchulteMarkus/metric-html-report-as-part-of-travis-demo/builds/289024281?utm_source=github_status&utm_medium=notification) (line 583f.), the curl gets executed, the returned HTTP status 201 indicates, that the authentication works, for example.

**Is**
This curl is a HTTP POST, with JSON-data, having a "target_url". Within this value, there are env-variables, $TRAVIS_COMMIT, for example. This variables are not replaced, the final value for "target_url" is "https://s3.amazonaws.com/$ARTIFACTS_S3_BUCKET/$S3_KEY_PREFIX/$TRAVIS_COMMIT/checkstyle/index.html".
This behavior is even more strange, as the env-variable $GH_MS_API_PERSONAL_ACCESS_TOKEN, which is used at the curl's Authorization, is replaced and works fine.
I tried using the ${TRAVIS_COMMIT}-form for this variables, without success.

**Shoud be**
All env-variables are replaced by it's values at the curl's POST-data.

**Comment by BanzaiMan** [comment]
I think this is a problem with your quoting.

You will notice that the POST request succeeds, so the values for `$TRAVIS_REPO_SLUG` and `$TRAVIS_COMMIT` are actually correct, and in https://github.com/SchulteMarkus/metric-html-report-as-part-of-travis-demo/commits/github you see that the status has been actually posted.

The command that is actually executed is:

```
curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $GH_MS_API_PERSONAL_ACCESS_TOKEN" -d '{"state": "success", "description": "Checkstyle HTML report", "context": "Checkstyle", "target_url": "https://s3.amazonaws.com/$ARTIFACTS_S3_BUCKET/$S3_KEY_PREFIX/$TRAVIS_COMMIT/checkstyle/index.html"}' https://api.github.com/repos/$TRAVIS_REPO_SLUG/statuses/$TRAVIS_COMMIT
```
with the payload 

```
'{"state": "success", "description": "Checkstyle HTML report", "context": "Checkstyle", "target_url": "https://s3.amazonaws.com/$ARTIFACTS_S3_BUCKET/$S3_KEY_PREFIX/$TRAVIS_COMMIT/checkstyle/index.html"}'
```

with single quotes, this literal string was passed, and you get the result you are seeing. You'd need a double quote:

```
curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $GH_MS_API_PERSONAL_ACCESS_TOKEN" -d "{\"state\": \"success\", \"description\": \"Checkstyle HTML report\", \"context\": \"Checkstyle\", \"target_url\": \"https://s3.amazonaws.com/$ARTIFACTS_S3_BUCKET/$S3_KEY_PREFIX/$TRAVIS_COMMIT/checkstyle/index.html\"}" https://api.github.com/repos/$TRAVIS_REPO_SLUG/statuses/$TRAVIS_COMMIT
```

Or write the data to a file and send it via `-d`.

**Comment by SchulteMarkus** [comment]
Thank you, you are right about the single quotes.

I solved it, but the [solution](https://github.com/SchulteMarkus/metric-html-report-as-part-of-travis-demo/blob/github/.travis.yml#L32) is really ugly

    -d \"{\\\"state\\\":   ...
