### ISSUE TITLE
Builds are failing because Oracle JDK cannot be installed

### ISSUE THREAD

**Issue by styurin** [travis-ci/travis-ci#8600]
Our builds are failing: https://travis-ci.org/facebook/buck/jobs/289270679

Error message:

```
Location: http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz?AuthParam=1508290969_cc077c1318f26d77ba44128a980fa011 [following]

--2017-10-18 01:40:49--  http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz?AuthParam=1508290969_cc077c1318f26d77ba44128a980fa011

Connecting to download.oracle.com (download.oracle.com)|23.63.227.139|:80... connected.

HTTP request sent, awaiting response... 404 Not Found

2017-10-18 01:40:50 ERROR 404: Not Found.
```

Looks like Oracle remove 8u144 version and `oracle-java8-installer ` wasn't updated to a newer version.

Is there a workaround for now?

**Comment by BanzaiMan** [comment]
Oracle probably yanked the version the APT package is pointing to.

**Comment by JLLeitschuh** [comment]
Any good known workarounds for this?

**Comment by BanzaiMan** [comment]
I am not aware of any workaround, unfortunately.

**Comment by iriberri** [comment]
For those using OracleJDK8, the Trusty images come with version 8u144 preinstalled - the version that oracle-java8-installer seems to be pointing to and failing to get-, whereas the older Precise versions come with 8u121 and cause the reported error when updating/installing oracle-java8-installer for 8u144.

This probably doesn't help much, but if switching to Trusty if an option for you, this would give you a VM with 8u144 already preinstalled and avoid the problem of it being unavailable from the source.

I see 8u151 was released two days ago: http://www.oracle.com/technetwork/java/javase/8u151-relnotes-3850493.html (and it's available at: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz)

However, as the error says, the old 8u144 to which oracle-java8-installer is pointing to (http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz) is no longer available

**Comment by JLLeitschuh** [comment]
This issue also exists with JDK 9 builds

**Comment by svpernova09** [comment]
Looks like a new version of JDK 8 is out now? http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html is showing Java SE Development Kit 8u151

**Comment by BanzaiMan** [comment]
@svpernova09 That might be explain the reason that Oracle yanked the older version. The issue remains, though, because we wait for the webupd8 team would have to update their apt package.

**Comment by jackalsin** [comment]
Probably a stupid question: but we don't have any upgrading issue before, right ? And, may I ask if I am the only one who didn't Java Update Manager's notification to update (currently on jdk 9+181)

**Comment by JLLeitschuh** [comment]
This may help someone else out.
This does not work:
```yml
matrix:
  include:
    - os: linux
      sudo: false
      jdk: oraclejdk9 # JDK 9+175 or newer
      addons:
        apt:
          packages:
            - oracle-java9-installer # Forces use of even newer JDK 9 build
```

However, this does work:
```yml
matrix:
  include:
    - os: linux
      sudo: false
      jdk: oraclejdk9 # JDK 9+175 or newer
```

Maybe the same will be true for JDK 8 builds.

**Comment by BanzaiMan** [comment]
@jackalsin @JLLeitschuh Those are not installing new packages so they should be fine. The issue is that installation fails.

**Comment by BanzaiMan** [comment]
@styurin https://launchpad.net/~webupd8team has contact information if you sign up. I've also pinged them. I hope to hear from them and resolve the issue soon.

**Comment by jameswald** [comment]
A workaround I prototyped involves using `before_install` to download the 1.8.0u144 JDK archive from our own servers to `/var/cache/oracle-jdk8-installer` before installing `oracle-java8-installer` from apt-get. The installer looks for the archive locally before attempting to download from Oracle. This workaround requires `sudo: false` and doesn't work with `addons` because that runs before `before_install`.

**Comment by styurin** [comment]
Looks like the issue was solved, our builds are passing.

**Comment by micheljung** [comment]
Same thing is happening again. Can we reopen this or should I create a new issue?

**Comment by iriberri** [comment]
@micheljung, @romani: thanks for the follow-up. Another user opened a new issue at https://github.com/travis-ci/travis-ci/issues/9379 - is this the same problem that you've been facing again? It seems that Oracle already sorted out the issue, so it should be working now. Could you confirm? Otherwise, feel free to reopen!

**Comment by romani** [comment]
It works for us now

**Comment by alexflav23** [comment]
@iriberri Builds still intermittently failing even to this day, same problem.

**Comment by jfederico** [comment]
Same here @alexflav23 It was working fine for me a few weeks ago, but it is broken again.

**Comment by iriberri** [comment]
@alexflav23 @jfederico could you please share the link of a build that shows the error here, or send it to support@travis-ci.com if it's a private one? Thanks! We'd be glad to take a further look.
