### ISSUE TITLE
`sudo apt-get update` failures in Linux `sudo: required` builds due to missing source riak

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/travis-ci#8607]
Seems the source https://packagecloud.io/basho/riak/ubuntu is no longer available, which is causing the following 401s or 404s failures in Linux, `sudo: required` builds: 

for those using Trusty:
```
Err:34 https://packagecloud.io/basho/riak/ubuntu trusty/main Sources 401 Unauthorized Get:44 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main amd64 Packages [4,396 B] E
rr:35 https://packagecloud.io/basho/riak/ubuntu trusty/main amd64 Packages 401 Unauthorized 
Err:36 https://packagecloud.io/basho/riak/ubuntu trusty/main i386 Packages 401 Unauthorized
```
for those using Precise:
```
Err:19 https://packagecloud.io/basho/riak/ubuntu precise/main amd64 Packages
  404  Not Found
Err:21 https://packagecloud.io/basho/riak/ubuntu precise/main i386 Packages
  404  Not Found
```

---
A possible workaround, for those not relying in riak is adding right before `sudo apt-get update` the following:

```
before_install:
- sudo rm -vf /etc/apt/sources.list.d/*riak*
- sudo apt-get update

```

We'll continue posting updates/workarounds as soon as we have them.

**Comment by chdemko** [comment]
See #5285

**Comment by MariadeAnton** [comment]
We've just pushed a fix for this issue, could you restart the affected builds and let us know how it goes here with a 👍  / 👎  ? 

Thank you!

**Comment by tessi** [comment]
It passed the `sudo apt-get update` step for me. seems to work 🎉

**Comment by tjiagoM** [comment]
Worked for me as well, thanks!

**Comment by MariadeAnton** [comment]
seems it's indeed fixed - thanks for your patience and for letting us know!

**Comment by Maivaza** [comment]
travis-ci /CONTRIBUTING.md

**Comment by Maivaza** [comment]
https://github.com/travis-ci/travis-ci/issues/8607

**Comment by kenorb** [comment]
This is still happening as per #9058

**Comment by WaleedAshraf** [comment]
@MariadeAnton facing the same issue on multiple jobs. I also sent a mail to support@travis last week but there is no reply yet.

**Comment by BanzaiMan** [comment]
@WaleedAshraf Sorry for the delay. We will get back to you shortly.
