### ISSUE TITLE
Haxe builds intermittently fail with MUnit and HaxeFlixel

### ISSUE THREAD

**Issue by nightblade9** [travis-ci/travis-ci#8609]
I have a [Haxe build here](https://travis-ci.org/nightblade9/eman-adventures) that uses HaxeFlixel. I build the unit tests, run them with MUnit against Neko, and then exit.

Intermittently, I see build failures like the one below:

```
PASSED
Tests: 9  Passed: 9  Failed: 0 Errors: 0 Ignored: 0 Time: 0.01786
Error running 'neko /home/travis/build/nightblade9/eman-adventures/report/test-runner/neko_test.n'
	std@process_exit
	
Error: Error (1) running /home/travis/build/nightblade9/eman-adventures/build/neko_test.n
```

[Here's the project source at a specific version on GitHub](https://github.com/nightblade9/eman-adventures/tree/eb5019c909d18329859e05e817e8a999f07aa11f). 

`travis.yml`:

```
language: haxe
haxe:
  - "3.4.2"
neko: "2.0.0"
hxml:
  - test.hxml
install:
  - haxelib install flixel > /dev/null
  - haxelib install flixel-addons >/dev/null
  - haxelib git helix https://github.com/nightblade9/helix
  - haxelib git haxesharp https://github.com/nightblade9/haxesharp
  - haxelib install munit > /dev/null  
script:  
  - haxelib run munit test --coverage -result-exit-code
```

It looks to me like MUnit is returning a non-zero exit code even if the tests pass. Is that a correct interpretation of the build results? (If so, I can open an issue on the munit repo about this.)

CC @andyli, @waneck, and @Simn

**Comment by andyli** [comment]
I notice you're using Neko 2.0.0. Would you try Neko 2.1.0 instead?

**Comment by nightblade9** [comment]
Sure, I can try that. I'll go ahead and close the issue in a day or two if the problem doesn't resurface.

**Comment by nightblade9** [comment]
Unfortunately, this still seems to fail.  [Here's a recent build](https://travis-ci.org/nightblade9/eman-adventures/builds/290203904?utm_source=email&utm_medium=notification) that failed with an exit code of 1.

Is this something I should ask someone from the MUnit repository about, or is it a build thing?

**Comment by nightblade9** [comment]
@elsassph Can you please take a look at this?

**Comment by elsassph** [comment]
Is it recently intermittent or has been for a long time? munit 2.1.2 was released 2 years ago.

**Comment by nightblade9** [comment]
It's a pretty new project. I would say it's been intermittent all along (I just tended to ignore it the first few times). Out of the last 15 builds, 4 of them failed with this same problem.

**Comment by andyli** [comment]
I think the same problem happened to me when I first tried munit a few years ago, so I think it is no caused by recent changes in Haxe/Neko. But I have no idea whether it is munit or Haxe/Neko's fault.

**Comment by nightblade9** [comment]
If this is indeed an munit or neko bug, I can't imagine that I would be the first person to run into this. Especially if munit (and maybe Neko) were stable over the last two years.
