### ISSUE TITLE
linuxbrew installation fails on android script

### ISSUE THREAD

**Issue by nicks9** [travis-ci/travis-ci#8610]
This was just working 2 days ago, might have something to do with latest updates.

Command I'm executing:
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"`

link to session:
https://travis-ci.com/waglabs/ownerandroid/builds/57205648

Error I'm getting:
```
HEAD is now at ce9a10f Fix style Use safe navigation (&.) [Linux]
==> Tapping homebrew/core
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4640, done.        
remote: Compressing objects: 100% (4423/4423), done.        
remote: Total 4640 (delta 32), reused 336 (delta 7), pack-reused 0        
Receiving objects: 100% (4640/4640), 3.97 MiB | 14.78 MiB/s, done.
Resolving deltas: 100% (32/32), done.
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dmd.rb
Resource "druntime" is defined more than once
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /home/linuxbrew/.linuxbrew/bin/brew tap homebrew/core
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force
```

Thanks!

**Comment by BanzaiMan** [comment]
This looks like an issue with this file: `/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dmd.rb`, which I believe is https://github.com/Linuxbrew/homebrew-core/blob/7dc2d42534a8334bac9d1ce83296e2c8af23070b/Formula/dmd.rb.

You'll have to wait for the upstream fix. The issue has been reported as https://github.com/Linuxbrew/homebrew-core/issues/4740.
