### ISSUE TITLE
c# .net core version 2

### ISSUE THREAD

**Issue by ymazal** [travis-ci/travis-ci#8611]
trying to set travis-ci to work with .net core 2.0.0 and getting the fallowing error:

```sh-session
$ dotnet restore
/home/travis/build/ymazal/log330_V2/model/model.csproj(121,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/2.0.0/Microsoft/WindowsXaml/v14.0/Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
/home/travis/build/ymazal/log330_V2/model/model.csproj : warning NU1503: Skipping restore for project '/home/travis/build/ymazal/log330_V2/model/model.csproj'. The project file may be invalid or missing targets required for restore. [/home/travis/build/ymazal/log330_V2/log330_V2.sln]
/usr/share/dotnet/sdk/2.0.0/NuGet.targets(102,5): warning : Unable to find a project to restore! [/home/travis/build/ymazal/log330_V2/log330_V2.sln]
```

Here is the travis.yml:

```yaml
language: csharp
solution: log330_V2.sln
mono: none
dotnet: 2.0.0
dist: trusty

script:
  - dotnet restore
  - dotnet msbuild
```

Please any one can help ?

@joshua-anderson, @akoeplinger and @nterry

**Comment by tmds** [comment]
"Microsoft.Windows.UI.Xaml" sounds very _Windows_, are you sure this can compile on _Linux_ using a .NET Core 2.0 sdk?

**Comment by akoeplinger** [comment]
Correct, those projects won't work on Linux, you'll need to exclude them when building on Travis.

**Comment by ymazal** [comment]
Witch dll refrence is this so I can remove it

**Comment by akoeplinger** [comment]
Probably log330_V2/model/model.csproj since that's what it complains about.

**Comment by ymazal** [comment]
I just added the .net core in visual studio and added one project on that
framework (of type windows universals .net core 2.0.0)

the only project is this one.

The project as 2 dll refrence automatically added.

I just want to have a project compiled in travis using c# and unit tests...

What should I do to accomplish that. The project as only one empty class

On Oct 19, 2017 6:22 PM, "Alexander Köplinger" <notifications@github.com>
wrote:

Probably log330_V2/model/model.csproj since that's what it complains about.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/travis-ci/travis-ci/issues/8611#issuecomment-338054609>,
or mute the thread

**Comment by akoeplinger** [comment]
hard to say without seeing the project, but `windows universals .net core 2.0.0` makes me guess you added a project that targets UWP i.e. a Universal Windows app. That won't work on Linux.

Try using one that targets .NET Core or .NET Standard.

**Comment by ymazal** [comment]
@akoeplinger 

Wow, thank you so much every one! I have spend 3 days on this for a homework in school.

Adding a project .NET Standard works perfectly.
