### ISSUE TITLE
The command "msbuild /p:Configuration=Release src/MySQLManager/MySQLManager.sln" exited with 1.

### ISSUE THREAD

**Issue by Muhand** [travis-ci/travis-ci#8612]
I made a .NET Standard library, it builds perfectly on my machine; However, there is an issue building using travis, to make long story short, here is the log I get using travis:

`
     Build started 10/19/2017 3:47:22 AM.

     Project "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager.sln" on node 1 (default targets).

     ValidateSolutionConfiguration:

     Building solution configuration "Release|Any CPU".

     Project "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager.sln" (1) is building "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj" (2) on node 1 (default targets).

      /usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file '/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/D:/github/MySQLManager/src/MySQLManager/MySQLManager/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj]

     Build continuing because "ContinueOnError" on the task "ReportAssetsLogMessages" is set to "ErrorAndContinue".

     /usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file '/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/D:/github/MySQLManager/src/MySQLManager/MySQLManager/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj]

    Done Building Project "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj" (default targets) -- FAILED.

    Done Building Project "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager.sln" (default targets) -- FAILED.

    Build FAILED.

    "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager.sln" (default target) (1) ->

    "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj" (default target) (2) ->

    (ReportAssetsLogMessages target) -> 

    /usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file '/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/D:/github/MySQLManager/src/MySQLManager/MySQLManager/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj]

     "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager.sln" (default target) (1) ->

    "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj" (default target) (2) ->

    (RunResolvePackageDependencies target) -> 

     /usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file '/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/D:/github/MySQLManager/src/MySQLManager/MySQLManager/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj]

    0 Warning(s)

    2 Error(s)

    Time Elapsed 00:00:02.21

    The command "msbuild /p:Configuration=Release src/MySQLManager/MySQLManager.sln" exited with 1.

    Done. Your build exited with 1.
`

and here is my `.travis.yml`

`     language: csharp
     
     solution: src/MySQLManager/MySQLManager.sln
     
     before_script:
        - nuget restore src/MySQLManager
     
     script:
        - msbuild /p:Configuration=Release src/MySQLManager`

I get what the error is saying but I do have `obj/project.assets.json` and you can find it in the repository as well, here is a link to the [obj/project.assets.json](https://github.com/Muhand/MySQLManager/blob/Development/src/MySQLManager/MySQLManager/obj/project.assets.json) and also i am running `nuget restore` so I am not sure what is the issue here.
 @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
@Muhand you're not supposed to commit the `obj/` directory to version control, it's a temporary folder that has machine specific information in it. In your case it mentions `D:\github\MySQLManager\...` in the project.assets.json which obviously doesn't make sense on Linux on Travis.

You need to delete the `obj/` folder(s) from your repo.

**Comment by Muhand** [comment]
@akoeplinger That's correct, and that's what threw me off but it turned it out to be my fault for not adding a `.gitignore` anyways, I have added that and removed .obj folder, yet the issue is still the same and here is the log:

Build started 10/19/2017 9:40:15 PM.

Project "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager.sln" on node 1 (default targets).

ValidateSolutionConfiguration:

  Building solution configuration "Release|Any CPU".

Project "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager.sln" (1) is building "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj" (2) on node 1 (default targets).

PrepareForBuild:

  Creating directory "obj/Release/netstandard2.0/".

/usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file '/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj]

  Build continuing because "ContinueOnError" on the task "ReportAssetsLogMessages" is set to "ErrorAndContinue".

/usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file '/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj]

Done Building Project "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj" (default targets) -- FAILED.

Done Building Project "/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager.sln" (default targets) -- FAILED.

Build FAILED.

"/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager.sln" (default target) (1) ->

"/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj" (default target) (2) ->

(ReportAssetsLogMessages target) -> 

  /usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file '/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj]

"/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager.sln" (default target) (1) ->

"/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj" (default target) (2) ->

(RunResolvePackageDependencies target) -> 

  /usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file '/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj]

    0 Warning(s)

    2 Error(s)

Time Elapsed 00:00:01.42

The command "msbuild /p:Configuration=Release src/MySQLManager/MySQLManager.sln" exited with 1.

Done. Your build exited with 1.

**Comment by akoeplinger** [comment]
@Muhand can you please try `msbuild /t:Restore` instead of `nuget restore` ?

**Comment by Muhand** [comment]
@akoeplinger That worked like charm but I am still getting errors regarding assembly not found.
My project is a .NET standard targeting .NET Standard 2.0; I have imported MySql.Data.dll version 6.9.9

`msbuild /p:Configuration=Release src/MySQLManager/MySQLManager.sln` is failing with 48 errors but all of them are related; sample error I am getting is this:

`CRUDManager.cs(699,33): error CS0012: The type 'DbCommand' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. [/home/travis/build/Muhand/MySQLManager/src/MySQLManager/MySQLManager/MySQLManager.csproj]`

I understand the error but not sure how am I supposed to reference it using travis, especially when I am using nuget to download my assemblies.

**Comment by akoeplinger** [comment]
@Muhand  MySql.Data v6.9.9 doesn't support .NET Standard (it target .NET4.0/4.5). NuGet has a newer version which does support it: https://www.nuget.org/packages/MySql.Data/8.0.9-dmr

**Comment by Muhand** [comment]
Wish it was a released MySQL.Data but hopefully they release it soon as a full release; anyways, thanks for your help, it works like charm now.
