### ISSUE TITLE
travis-web waiter specs are not run during CI

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#8614]
The travis-web repo has a set of tests under:
https://github.com/travis-ci/travis-web/tree/master/waiter/spec

Whilst working on #8601 I noticed that the existing specs were buggy so shouldn't be passing, but yet the Travis run is green. Intentionally adjusting a test so it would definitely fail, confirmed that the tests aren't being run at all:
https://travis-ci.org/edmorley/travis-web/builds/290007695

**Comment by backspace** [comment]
We’re aware the tests are failing, which is why they aren’t running in CI. The future of `waiter` is in question and at this point it doesn’t seem worth prioritising getting them passing; the code has barely changed over the past while. But thanks for the message!
