### ISSUE TITLE
PHP 7.2 suddenly not supporting libsodium

### ISSUE THREAD

**Issue by paragonie-scott** [travis-ci/travis-ci#8618]
Compare:

* https://travis-ci.org/paragonie/halite/builds/276315666
* https://travis-ci.org/paragonie/halite/builds/289991707

The only thing that changed between these versions is documentation and comments. (License headers.)

**Comment by BanzaiMan** [comment]
Runtime updated from 7.2.0RC1 to 7.2.0RC3, and pecl is installing [2.0.4](https://travis-ci.org/paragonie/halite/jobs/276315667#L1245) on the successful build and [1.0.7](https://travis-ci.org/paragonie/halite/jobs/289991708#L1244) on the failing one. It is not clear to me why.

**Comment by paragonie-scott** [comment]
Oh no. It must be because 1.0.7 is newer than 2.0.4.

**Comment by paragonie-scott** [comment]
Updated `.travis.yml` to specify `libsodium-2.0.4` and that fixed the problem. Ugh. PECL strikes again.
