### ISSUE TITLE
Unable to deploy to GitHub Releases

### ISSUE THREAD

**Issue by Deadddorks** [travis-ci/travis-ci#8619]
I am new to this, but I have someone very experienced helping me, and we can not git Travis to work whatsoever, he has tried everything. Here is a link to one of my failed builds, its always the same invalid credentials error:

https://travis-ci.org/Deadddorks/Importable/builds/290214117

**Comment by BanzaiMan** [comment]
https://travis-ci.org/Deadddorks/Importable/builds/290214117#L562 says that the access token you provided was incorrect.

**Comment by xoviat** [comment]
He posted his personal API in his GitHub repository. That is not appropriate.

**Comment by BanzaiMan** [comment]
As the previous attempt with a plain access token https://travis-ci.org/Deadddorks/Importable/builds/290212314#L562 also failed the same way, I tend to think that your token is invalid.

**Comment by BanzaiMan** [comment]
@Deadddorks As @xoviat pointed out, I recommend revoking the token, if it is still valid (I doubt it is).

**Comment by chgibb** [comment]
I've been suddenly seeing 401 bad credential errors when uploading with a token which has been working until a few days ago.

**Comment by BanzaiMan** [comment]
@chgibb Sounds like someone revoked the token in question.

**Comment by BanzaiMan** [comment]
I don't think there is much to do here.

If you are having problems, do double check your credentials; create a new one with correct scope if necessary.

**Comment by chgibb** [comment]
Unless Github revoked it, it should still be valid as it is my token. My project suddenly started building on .org instead of .com a few months after I switched the repo to public. That is when release uploading broke.

**Comment by BanzaiMan** [comment]
@chgibb Ah. That is one scenario I did not consider. By making public, you've invalidated the encrypted value in `.travis.yml`. Please read https://docs.travis-ci.com/user/travis-pro#How-can-I-make-a-private-repository-public%3F and re-encrypt the token.

**Comment by chgibb** [comment]
I followed the guide but it did not resolve the issue I'm having. I also tried creating a new encrypted token with ```travis``` encrypt after ensuring the endpoint was .org as well as disabling and renabling my repo in Travis. Nothing seems to work so far.
