### ISSUE TITLE
Can't run xunit tests 

### ISSUE THREAD

**Issue by software770** [travis-ci/travis-ci#8620]
Hi,
here is the travis.yml:

language: csharp
solution: log330_V2.sln
mono: none
dotnet: 2.0.0
dist: trusty

script:
  - dotnet restore
  - dotnet msbuild
  - dotnet xunit Tests/Tests.csproj

The error is shown:

0.14s$ dotnet xunit Tests/Tests.csproj
No executable found matching command "dotnet-xunit"

----------------------------------------------------------------------
If the yml is changed to:
language: csharp
solution: log330_V2.sln
mono: none
dotnet: 2.0.0
dist: trusty

script:
  - dotnet restore
  - dotnet msbuild
  - dotnet test Tests/Tests.csproj

The fallowing error is shown:
4.23s$ dotnet test Tests/Tests.csproj
Build started, please wait...
Build completed.
Test run for /home/travis/build/ymazal/log330_V2/Tests/bin/Debug/netcoreapp2.0/Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
No test is available in /home/travis/build/ymazal/log330_V2/Tests/bin/Debug/netcoreapp2.0/Tests.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.

-------------------------------------------------------------------------------------
But the first yml is inspired from:  http://xunit.github.io/docs/getting-started-dotnet-core
and the second, from https://medium.com/@pjbgf/configuring-ci-for-net-core-using-travis-ci-and-xunit-cc0f809df4fb  and this person seems to claim that it works.

@joshua-anderson, @akoeplinger and @nterry

**Comment by akoeplinger** [comment]
I'd try using `dotnet build` instead of `dotnet msbuild`.
