### ISSUE TITLE
Github integration failing: waiting forever for build status to be reported

### ISSUE THREAD

**Issue by MiraLak** [travis-ci/travis-ci#8621]
Since today, the integration is no more working with Travis and we have a lot of pull requests hanging and waiting for Travis build status (the build was successful BTW)
![screen shot 2017-10-20 at 13 54 56](https://user-images.githubusercontent.com/541422/31821072-192a8634-b5a4-11e7-856e-c5a1272c52fc.png)

**Comment by AndrewBestbier** [comment]
Same here 👍

**Comment by albertobettini-adam** [comment]
Same here

**Comment by AndrewBestbier** [comment]
See here for updates: https://www.traviscistatus.com/incidents/d7y02z19k0y6

**Comment by AndrewBestbier** [comment]
The latest: https://www.traviscistatus.com/incidents/px0g4kzwz4g7
