### ISSUE TITLE
How to choose Node.js 32 bit version?

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#8624]
How to choose Node.js 32bit version? For instance, I use Trusty and I need to use Node.js 6.11.4 x86.

**Comment by BanzaiMan** [comment]
We pass the version to `nvm` (https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Specifying-Node.js-versions).

https://github.com/creationix/nvm/issues/1298 talks about the possible 32-bit binary support. At the moment, though, it does not seem possible.

Closing as an upstream issue.
