### ISSUE TITLE
Bintray: "200 OK" status but file does not get updated

### ISSUE THREAD

**Issue by larsrh** [travis-ci/travis-ci#8625]
Build log: https://travis-ci.org/larsrh/libisabelle/jobs/288539786#L1953
Configuration: https://github.com/larsrh/libisabelle/blob/19d89a49567fe386027b2b18a3b08390911c419b/.ci/bintray

According to the build log, I would have expected the generated binary to be uploaded to Bintray. However, even with `override` set to `1`, the file does not get updated and I don't see any kind of error message.

**Comment by BanzaiMan** [comment]
The status is coming from Bintray. If the status 200 does not mean what you expect, I suggest getting in touch with the Bintray support. You can find the code here: https://github.com/travis-ci/dpl/blob/837da9ab01dc3a6981e9acb7a058091264db3f7f/lib/dpl/provider/bintray.rb

**Comment by larsrh** [comment]
I think this can be closed now. I'm working with the Bintray support to resolve this.
