### ISSUE TITLE
Abuse detected

### ISSUE THREAD

**Issue by solth** [travis-ci/travis-ci#8626]
Hi Travis-CI,
since last week all my pull requests against our repository that uses Travis-CI are rejected with the following message:

`"Job rejected. Abuse detected."`

Since our release manager relies on the Travis checks, my pull requests aren't merged anymore, but there are some important changes that need to be merged into the master branch.

I already contacted support, and they said they reset my account to the state of "trusted", but that apparently has not happened, because I still get the same error whenever I trigger another build. Unfortunately, support does not respond to my mails anymore, either.

**Comment by BanzaiMan** [comment]
Sorry about the silence there. We'll get back to you on the support ticket soon.

**Comment by ntrepid8** [comment]
I've got this issue also where just one PR is triggering this `Abuse detected` failure.

- https://github.com/ntrepid8/ex_crypto/pull/13

I've emailed support just a little while ago so it may take some time for them to respond I guess, but it might help if there was a section in the docs that explained a bit what can cause this.

There are several closed tickets for this issue that just say "email support" to get it resolved, but is there something we can do to prevent triggering the `Abuse detected` error in the future?

That being said, thanks in advance for providing this great service to open source projects!

**Comment by BanzaiMan** [comment]
I am afraid we cannot disclose what trips our abuse detection. Abusers will abuse such disclosures.

**Comment by xoviat** [comment]
![image](https://user-images.githubusercontent.com/15351036/31973508-fbc41de4-b8eb-11e7-8ebb-df9c82d0cc32.png)

Care to disclose what happened there? There's no way that the amount of jobs could have dropped that quickly.

**Comment by presidentio** [comment]
@BanzaiMan I have the same problem. I have repository https://github.com/presidentio/test-data-generator which were not changed during last two years. Today, someone created a PR to my repo, and it were not build on travis-ci with message `Abuse detected`

**Comment by solth** [comment]
Travis CI support solved the issue for me - needed to re-grant Travis-CI access to our repository after github user was transformed into github organization - so I will close this issue.
Thanks for the help, support!
