### ISSUE TITLE
GitHub pages deployment commits from sinyakov

### ISSUE THREAD

**Issue by jrbourbeau** [travis-ci/travis-ci#8630]
I setup up a public GitHub repository to have the project documentation automatically built by Travis CI following these instruction https://docs.travis-ci.com/user/deployment/pages/. This documentation states that the `email` configuration defaults to deploy@travis-ci.org. Upon pushing a commit to my repository the documentation was successfully built and deployed by Travis, however I found that the commit to my project `gh-pages` branch was committed by the user sinyakov on GitHub. Explicitly setting the `email` configuration (e.g. `email: "travis-deploy-github-pages-deploy@travis-ci.org"`) fixes this issue. 

Having deployment commits from sinyakov seems unintuitive to me. Are commits from this user expected? 

For an explicit example of this issue I made a test repository https://github.com/jrbourbeau/travis-deploy-github-pages

**Comment by BanzaiMan** [comment]
Thanks for the report. We are in contact with GitHub support to sort things out.

**Comment by jrbourbeau** [comment]
Awesome, thanks @BanzaiMan

**Comment by folkvir** [comment]
Same thing for me, `gh-pages` branch commits are committed by the user sinyakov.

**Comment by iriberri** [comment]
Thanks all again for reporting this issue. It's been resolved!
