### ISSUE TITLE
Abuse detected

### ISSUE THREAD

**Issue by presidentio** [travis-ci/travis-ci#8632]
I have repository https://github.com/presidentio/test-data-generator which were not changed during last two years. Today, someone created a PR to my repo, and it were not build on travis-ci with message Abuse detected

**Comment by slawekjaranowski** [comment]
I have the similar issue:
https://travis-ci.org/s4u/pgpverify-maven-plugin/requests

**Comment by BanzaiMan** [comment]
Please contact support at support@travis-ci.com. Thanks.

I'm closing this here, since there's not much to do.
