### ISSUE TITLE
Travis-ci has started to hang when pulling a container from Dockerhub

### ISSUE THREAD

**Issue by matthew-brett** [travis-ci/travis-ci#8633]
On multiple builds, I am getting new failures pulling a docker image from dockerhub.  The failing commands are either of:

```
docker pull matthewbrett/trusty:32
docker pull matthewbrett/trusty:64

```
See (for example):

* https://travis-ci.org/MacPython/scipy-wheels/jobs/292452500
* https://travis-ci.org/MacPython/dipy-wheels/jobs/292340619#L637
* https://travis-ci.org/regreg/regreg-wheels/jobs/292330035#L572

You'll see from the build matrices there, that the command only seems to hang sometimes - e.g. 

* https://travis-ci.org/regreg/regreg-wheels

The same command works without any obvious slowdown on a Linux machine I have to hand.

See also https://github.com/MacPython/scipy-wheels/issues/22

**Comment by torokati44** [comment]
We reported the exact same issue 2 minutes apart... :D

**Comment by torokati44** [comment]
And it is already under investigation: https://www.traviscistatus.com/incidents/v4jnp6nkgzqx

**Comment by matthew-brett** [comment]
:) - thanks for the update ...

**Comment by junghans** [comment]
Same for @votca, @espressopp and @laristra.

**Comment by capveg** [comment]
Same for me as well.  Any update on this?

**Comment by BanzaiMan** [comment]
This should be resolved by the upstream.

**Comment by BanzaiMan** [comment]
For the record: https://www.traviscistatus.com/incidents/v4jnp6nkgzqx
