### ISSUE TITLE
Environment variable contents, which may match other strings, are (erroneously?) masked with [secure]

### ISSUE THREAD

**Issue by cgiroua** [travis-ci/travis-ci#8635]
Very new to Travis, but if an environment variable is defined in the Travis repository settings (let's say BLAH=password), if that 'password' string occurs elsewhere in your build (not necessarily tied to that variable) it too will be masked out with the **[secure]** string.  This could potentially lead to some information leakage/association which would be assumed private, via comparison of the code/build output.

See this build output (last section):
https://travis-ci.org/cgiroua/travis-tests/builds/290111237#L647

And corresponding last line in the code here:
https://github.com/cgiroua/travis-tests/blob/master/.travis.yml#L11

In my above case it's somewhat benign (just a common username), but someone may unintentionally trip over this.  I don't see this mentioned in the environment variables documentation, so perhaps just an FYI there would be sufficient?

**Comment by BanzaiMan** [comment]
Thanks for the input. In https://docs.travis-ci.com/user/best-practices-security/, we have:

> To prevent leaks made by these components, we automatically filter secure environment variables and tokens that are longer than three characters at runtime, effectively removing them from the build log, displaying the string [secure] instead.
> 
> Please make sure your secret is never related to the repository or branch name, or any other guessable string. Ideally use a password generation tool such as mkpasswd instead of choosing a secret yourself.

Is that sufficient? Did you find the notice above? How can we make it more searchable?

**Comment by myitcv** [comment]
I'm having a similar issue. For example, consider [the line](https://travis-ci.org/myitcv/x/jobs/363447326#L491):

```
Running tests for [secure].io/...
```

This corresponds to the distinctly [non-secret line in a shell script](https://github.com/myitcv/x/blob/db9b535162e2c37f2722b11f592761ff34a56a99/_scripts/run_tests.sh#L8):

```bash
echo "Running tests for myitcv.io/..."
```

If I were to guess what's going on here; there is an environment variable (possibly Travis-defined) that has a value of `myitcv`; and an over-zealous sanitiser is then "making safe" strings that aren't in fact dangerous.

**Comment by myitcv** [comment]
As a follow up to my previous comment; I did in fact have a secret variable whose value was `myitcv` (not particularly a secret given that I'm telling you about it here!). But it seems there is some sanitisation logic similar to that which I previously described which kicks in despite the variable itself not being used.

**Comment by cgiroua** [comment]
I completely forgot about this, however @BanzaiMan I think tweaking the last section to say something along the lines of (bold are my additions/changes):

Please make sure your secret is never related to the repository or branch name, **any other guessable string, or any common string which may show up elsewhere in your build log output**. Ideally use a password generation tool such as mkpasswd instead of choosing a secret yourself.

The same verbiage could even be a 'Notice' when setting environment variables on the settings page, like the one about values not being escaped.  It could help people avoid stepping on this, though I understand there is likely a desire to keep that page as clean as possible.

**Comment by BanzaiMan** [comment]
@cgiroua That is nice! Do you mind opening a PR? (There is a link "Improve this page on GitHub" in the upper right corner.)

I'll pass on your feedback on the Settings page to the design team.

Thanks!

**Comment by BanzaiMan** [comment]
![banzaiman_travis_production_test_-_travis_ci](https://user-images.githubusercontent.com/25666/40809343-34c0d110-64f8-11e8-9c42-4fac551d34a8.png)

Settings page now has this.
