### ISSUE TITLE
API builds does not override `TRAVIS_COMMIT_MESSAGE`

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#8641]
# Description

Issuing an API build request with `message` value does not change the `TRAVIS_COMMIT_MESSAGE`.

# Steps to reproduce

```
body='{
 "request": {
 "message": "Override the commit message: this is an api request",
 "branch":"master",
 "config": {
   "env": {
     "matrix": ["TEST=unit"]
   },
   "script": "echo FOO"
  }
}}'

curl -s -X POST \
 -H "Content-Type: application/json" \
 -H "Accept: application/json" \
 -H "Travis-API-Version: 3" \
 -H "Authorization: token xxxxxx" \
 -d "$body" \
 https://api.travis-ci.org/repo/travis-ci%2Ftravis-core/requests
```

# Expected behavior

`$TRAVIS_COMMIT_MESSAGE` is set to the value given in the payload: `"Override the commit message: this is an api request"`.

# Actual behavior

It is the same as one given in the latest commit in git.

# Discussion

Currently, `$TRAVIS_COMMIT_MESSAGE` is set by reading the `git` data (https://github.com/travis-ci/travis-build/blob/1f67b6407de09a7a972f8ff568d96b8bd2ef7ba9/lib/travis/build/env/builtin.rb#L43), not the payload passed to `travis-build`. This is done in order to avoid certain issues when passing non-ASCII characters (https://github.com/travis-ci/travis-ci/issues/965#issuecomment-49810156).

**Comment by BanzaiMan** [comment]
https://travis-ci.community/t/travis-commit-message-is-not-overwritten-by-env-set-in-api-payload-it-is-always-set-by-the-git-data/2233

**Comment by AlexHarrisonIBM** [comment]
So is this still an issue

**Comment by mteodori** [comment]
still happening for me in https://travis-ci.com/github/Alfresco/alfresco-docker-base-tomcat
