### ISSUE TITLE
Abuse detected

### ISSUE THREAD

**Issue by Spongman** [travis-ci/travis-ci#8643]
For some reason my account is marked as an abuser in the processing/p5.js repo's Travis build system. I'm trying to get my PRs validated but I can't. I sent an email to support,m. Is there something else I have to do to clear this? Can I at least get an ACK?

**Comment by Spongman** [comment]
Anyone?

**Comment by BanzaiMan** [comment]
Please wait for the response from support. Thanks.

**Comment by Spongman** [comment]
ok, thanks. will do.
