### ISSUE TITLE
ssh localhost: connection reset by peer

### ISSUE THREAD

**Issue by x-yuri** [travis-ci/travis-ci#8647]
Relevant parts of [the build][1] (or so I think):

[1]: https://travis-ci.org/Mic92/mina-sidekiq/jobs/293248580

```
$ ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
Generating public/private rsa key pair.
Your identification has been saved in /home/travis/.ssh/id_rsa.
Your public key has been saved in /home/travis/.ssh/id_rsa.pub.
The key fingerprint is:
a9:25:00:b4:7c:8b:e4:e8:97:14:34:08:81:0e:d6:02 travis@travis-job-mic92-mina-sidekiq-293248580.travisci.net
The key's randomart image is:
+--[ RSA 2048]----+
|Eo=o             |
|o=.+.            |
|+ =.o            |
| = o.o   .       |
|. o.. . S        |
|. . .  +         |
| . o  .          |
|  .              |
|                 |
+-----------------+
$ cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
$ echo "Host localhost" >> /home/travis/.ssh/config
$ echo "  StrictHostKeyChecking no" >> /home/travis/.ssh/config
$ chmod g-rw,o-rw /home/travis/.ssh/*
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/travis/.ssh/config
debug1: /home/travis/.ssh/config line 1: Applying options for *
debug1: /home/travis/.ssh/config line 4: Applying options for localhost
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to localhost [::1] port 22.
debug1: Connection established.
debug3: Incorrect RSA1 identifier
debug3: Could not load "/home/travis/.ssh/id_rsa" as a RSA1 public key
debug1: identity file /home/travis/.ssh/id_rsa type 1
debug1: identity file /home/travis/.ssh/id_rsa-cert type -1
debug1: identity file /home/travis/.ssh/id_dsa type -1
debug1: identity file /home/travis/.ssh/id_dsa-cert type -1
debug1: identity file /home/travis/.ssh/id_ecdsa type -1
debug1: identity file /home/travis/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/travis/.ssh/id_ed25519 type -1
debug1: identity file /home/travis/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8 pat OpenSSH_6.6.1* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug3: load_hostkeys: loading entries for host "localhost" from file "/home/travis/.ssh/known_hosts"
debug3: load_hostkeys: loaded 0 keys
debug1: SSH2_MSG_KEXINIT sent
Read from socket failed: Connection reset by peer
```

Do you have any ideas? Can I ssh to the machine where it builds somehow?

**Comment by AndiDittrich** [comment]
same issue here using the container based testrunner
i've created a minimal testcase https://github.com/AndiDittrich/TEST.travisci

**Comment by x-yuri** [comment]
@AndiDittrich `ssh` supposedly doesn't work in [container-based environments][1]. At least from my experience. Can anyone confirm this?

I've found [two][2] [ways][3] to switch to full virtual machine environment where it works. Also, localhost is [known][4] by definition I suppose.

[1]: https://docs.travis-ci.com/user/reference/overview/
[2]: https://github.com/AndiDittrich/TEST.travisci/pull/2
[3]: https://github.com/AndiDittrich/TEST.travisci/pull/3
[4]:https://github.com/AndiDittrich/TEST.travisci/pull/4

**Comment by IwanVosloo** [comment]
Same issue here. It definitely used to work for us in a container-based environment before.

**Comment by IwanVosloo** [comment]
According to our tests, it used to work on trusty containers (sudo: false and dist: trusty) but the error appears on precise containers (sudo: false and dist: precise).  We only have sudo: false in .travis.yml and according to https://blog.travis-ci.com/2017-08-31-trusty-as-default-status the default dist: used to be precise, but is trusty since 1 Sept 2017.

So our old tests, that used to work ran on precise. We have now forced it to use precise again by overriding the new default to dist: precise and no longer experience the issue.

This obviously does not solve actual the problem....but buys a bit more time.

**Comment by AndiDittrich** [comment]
thanks @IwanVosloo

**Comment by BanzaiMan** [comment]
This seems like a problem with containers. I have not been able to coax it to work with it thus far.

If you need Trusty *and* this behavior, you should be able to accomplish it by `sudo: required`.

**Comment by HerrSpace** [comment]
This is very much not solved. It's not closed though and I don't think I can remove that stale label.

**Comment by HerrSpace** [comment]
bump
