### ISSUE TITLE
401 Bad Credentials After Running travis setup releases

### ISSUE THREAD

**Issue by chgibb** [travis-ci/travis-ci#8648]
[This project](https://github.com/chgibb/PHAT) began as a private project, I switched it to public ~5 months ago without going through the proper steps in the documentation to do so. A week or two ago Travis CI started building the project on travis-ci.org suddenly instead of travis-ci.com. Since then, releases have been failing with 401 bad credentials error. I have since gone through the steps described in the documentation and tried removing the setup config from my ```.travis.yml``` and recreating it with ```travis setup releases``` to no avail.

Running ```travis status``` reports the last build on travis-ci.com though all builds are now triggering on travis-ci.org
```
build #3547 passed
```
I suspect my API key is being encrypted with travis-ci.com's private key and then trying to be decrypted with travis-ci.org's private key.

I also tried creating a new Github token with full repo permissions, encrypting it with ```travis encrypt``` and pasting it into the ```api_key``` section of the release configuration to no avail.

Output from ```travis report```:
```
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Ubuntu 16.04
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-10-26 15:08:31 -0400

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "chgibb"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, default, current)
pro:                      https://api.travis-ci.com/ (access token)

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.

```

Any help is greatly appreciated.

**Comment by BanzaiMan** [comment]
Have you changed the API endpoint? As described in the docs?

Or, you can explicitly use `-e https://api.travis-ci.org` (or the equivalent `--org`) to encrypt it:

    travis encrypt --org

**Comment by chgibb** [comment]
Thanks @BanzaiMan. Looks like that fixed it. I would note that the docs on the shift from private to public are woefully insufficient as I didn't know they existed. This resulted in a broken project (albeit many months later). Thanks for the help!
