### ISSUE TITLE
Trusty MongoDB repo broken again

### ISSUE THREAD

**Issue by HariSekhon** [travis-ci/travis-ci#8649]
```
sudo apt-get update
Ign:1 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty InRelease
Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates InRelease
Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports InRelease
Hit:4 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty Release
Hit:5 http://dl.hhvm.com/ubuntu trusty InRelease
Ign:6 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 InRelease
Hit:7 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease
Hit:8 http://security.ubuntu.com/ubuntu trusty-security InRelease
Get:9 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release [3,462 B]
Get:11 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release.gpg [801 B]
Ign:10 http://toolbelt.heroku.com/ubuntu ./ InRelease
Hit:14 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease
Get:12 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Hit:16 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty InRelease
Ign:17 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:18 https://download.docker.com/linux/ubuntu trusty InRelease
Hit:19 http://dl.google.com/linux/chrome/deb stable Release
Ign:11 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release.gpg
Hit:20 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse amd64 Packages
Ign:21 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Hit:22 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages
Ign:22 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages
Hit:22 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages
Err:22 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages
  Empty files can't be valid archives
Hit:23 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
Hit:25 http://ppa.launchpad.net/hvr/ghc/ubuntu trusty InRelease
Hit:26 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
Hit:27 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
Hit:28 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
Hit:29 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease
Hit:30 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
Hit:31 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release
Hit:13 http://toolbelt.heroku.com/ubuntu ./ Release
Fetched 7,431 B in 5s (1,481 B/s)
Reading package lists... Done
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release: The following signatures were invalid: KEYEXPIRED 1507497109
W: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch store:/var/lib/apt/lists/partial/repo.mongodb.org_apt_ubuntu_dists_trusty_mongodb-org_3.2_multiverse_binary-i386_Packages  Empty files can't be valid archives
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by HariSekhon** [comment]
https://travis-ci.org/HariSekhon/nagios-plugins/jobs/293227643#L1002

**Comment by BanzaiMan** [comment]
Do you manipulate apt repos in any way? A straight-up `apt-get update` does not fail. https://travis-ci.org/BanzaiMan/travis_production_test/builds/293371773#L546

**Comment by HariSekhon** [comment]
No I don't manipulate repos in any way, it must have been a transitory error, as a build retry has succeeded now. Iirc this repo has broken before and a few days ago another repo for riak broke (#8607) so I thought this one required intervention again. Closing.

Cheers

Hari

**Comment by Maivaza** [comment]
sudo apt-get update
Ign:1 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty InRelease
Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates InRelease
Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports InRelease
Hit:4 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty Release
Hit:5 http://dl.hhvm.com/ubuntu trusty InRelease
Ign:6 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 InRelease
Hit:7 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease
Hit:8 http://security.ubuntu.com/ubuntu trusty-security InRelease
Get:9 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release [3,462 B]
Get:11 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release.gpg [801 B]
Ign:10 http://toolbelt.heroku.com/ubuntu ./ InRelease
Hit:14 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease
Get:12 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Hit:16 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty InRelease
Ign:17 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:18 https://download.docker.com/linux/ubuntu trusty InRelease
Hit:19 http://dl.google.com/linux/chrome/deb stable Release
Ign:11 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release.gpg
Hit:20 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse amd64 Packages
Ign:21 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Hit:22 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages
Ign:22 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages
Hit:22 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages
Err:22 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages
  Empty files can't be valid archives
Hit:23 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
Hit:25 http://ppa.launchpad.net/hvr/ghc/ubuntu trusty InRelease
Hit:26 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
Hit:27 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
Hit:28 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
Hit:29 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease
Hit:30 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
Hit:31 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release
Hit:13 http://toolbelt.heroku.com/ubuntu ./ Release
Fetched 7,431 B in 5s (1,481 B/s)
Reading package lists... Done
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release: The following signatures were invalid: KEYEXPIRED 1507497109
W: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch store:/var/lib/apt/lists/partial/repo.mongodb.org_apt_ubuntu_dists_trusty_mongodb-org_3.2_multiverse_binary-i386_Packages  Empty files can't be valid archives
E: Some index files failed to download. They have been ignored, or old ones used instead.
