### ISSUE TITLE
Android 27 project build failure "You have not accepted the license agreements"

### ISSUE THREAD

**Issue by AnmAtAnm** [travis-ci/travis-ci#8651]
Modern variant of #6555. I receive this message both with the `licenses` section ([build log](https://travis-ci.org/google/blockly-android/builds/293369843?utm_source=github_status&utm_medium=notification)) and without ([build log](https://travis-ci.org/google/blockly-android/builds/293383007?utm_source=github_status&utm_medium=notification)), even though [the docs](https://docs.travis-ci.com/user/languages/android/#Dealing-with-Licenses) say Travis accepts all licenses by default.

'''
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':blocklydemo'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 27, Android SDK Platform 27].
'''

I'm assuming the server needs to have some configuration on the build server to note that the licenses are agreed to.

**Comment by AnmAtAnm** [comment]
Bad component versions.

**Comment by magneticflux-** [comment]
@AnmAtAnm What were your component versions? I'm having the same issue all of a sudden.

**Comment by msridhar** [comment]
@magneticflux- I had to follow this instruction to accept the license https://stackoverflow.com/a/47726910/1126796

**Comment by veghtomi** [comment]
It still happens. @msridhar thanks for the solution!

**Comment by magneticflux-** [comment]
Here's the original issue: #8874

**Comment by voghDev** [comment]
Some months have passed, but my Android project is building fine with api level 27. [here](https://github.com/voghDev/HelloKotlin/blob/master/.travis.yml) is the `.travis.yml` file, maybe it helps someone who lands here :)

**Comment by worstkiller** [comment]
> Some months have passed, but my Android project is building fine with api level 27. [here](https://github.com/voghDev/HelloKotlin/blob/master/.travis.yml) is the `.travis.yml` file, maybe it helps someone who lands here :)

thanks it really worked
