### ISSUE TITLE
Failed to create log file during building

### ISSUE THREAD

**Issue by rockie** [travis-ci/travis-ci#8652]
Build job: https://travis-ci.org/kitmi/winstonflight/jobs/293509677

Uncaught Error: ENOENT: no such file or directory, open '/home/travis/build/kitmi/winstonflight/test/temp/all.log'

All my 3 job failed to create the log file. Firstly, I am using a relative path, then changed to absolute path and also tried sudo enabled env in the last job. Don't know the failure reason. Could you please take a look? Thanks.

**Comment by BanzaiMan** [comment]
Create `test/tmp` directory first before writing the logs to that directory.
