### ISSUE TITLE
pip cannot install anything when run with PyPy2 5.8.0

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#8659]
We've run into this in multiple repositories. See https://travis-ci.org/celery/py-amqp/jobs/294051314#L457 and https://travis-ci.org/celery/kombu/jobs/289899601#L459
Tox installs just fine locally with the same PyPy version. When I tried installing something else the same error occurs. See https://travis-ci.org/celery/py-amqp/jobs/294052160#L458
This is the first build where this error occurred as far as I know: https://travis-ci.org/celery/kombu/builds/272580280

**Comment by thedrow** [comment]
@BanzaiMan I apologize that I have to ping directly you but this received no attention at all.
Can you take a look?

**Comment by thedrow** [comment]
This wasn't an issue with Travis per se but strange that PyPy behaves in such a way in your environment and not on others.

**Comment by BanzaiMan** [comment]
@thedrow Sorry for the delay. If you would like to troubleshoot further (perhaps because you're curious), we can enable the debug feature on a repo for you. (Unfortunately, our understanding of Python's intricacies can be limited and may miss some finer points.)
