### ISSUE TITLE
Would this help bringing KVM support?

### ISSUE THREAD

**Issue by natario1** [travis-ci/travis-ci#8660]
I have recently stumbled across #1419 while trying to make the Android emulator work decently. There you say that you can't provide KVM due to infrastructural limits in Google Compute Engine.

Today I have stumbled across this ( https://cloudplatform.googleblog.com/2017/09/introducing-nested-virtualization-for.html ) and this ( https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances ). Now, please bear with me - I know *nothing* about Linux and KVM - but it looks like this feature could help? As far as I understand, you just enable this feature and then KVM will be provided...

If it's true, please consider this! The non-accelerated ARM emulators are so slow and Google is not even releasing the system images anymore for new Android APIs (already absent for API 26 and 27). So the current workaround (use ARM emulators even if it takes 20 mins) won't work forever.

Thanks.

**Comment by BanzaiMan** [comment]
Thanks for the information. We'll take a look.

**Comment by aruiz** [comment]
This is not going to help. You can't get accelerated ARM emulation with KVM unless you run on ARMv8 hardware.

Nesting is about having accelerated KVM machines inside another KVM machines, but KVM itself will only work emulating the host architecture which in the case of Google Compute it's always x86.

**Comment by natario1** [comment]
@aruiz we don't want accelerated ARM emulation here, we want to switch to x86 android emulators, but they require KVM. I only mentioned ARM emulators because that's what we are forced to use right now.

It appears to me that it's just about enabling this flag.. ? Android testing on travis is near to impossible right now.

**Comment by evopen** [comment]
That's right. Android Oreo doesn't have arm image. So it is impossible to run android test on latest Android.

**Comment by mikehardy** [comment]
As evopen mentions, they aren't publishing arm images anymore so the latest two API levels aren't testable on travis. I understand something like Firebase labs integration to be a possibility, but it's important to note that they remove old APIs aggressively so with Travis we can't test the new APIs but with Firebase we can't test the old ones.

**Comment by mikehardy** [comment]
Would be a shame to close this, I just read the links and I know about virtualization. The x86 android emulators using Intel's HAXM acceleration are doing KVM+QEMU and thus enabling nested virtualization in the GCE environment would enable them to run with inside your Travis workers, without even changing distro I think (you are on Ubuntu 14 or 16 IIRC). This would actually lower your costs as the ARM emulators chew through probably 10-20x the compute time as the accelerated x86 emulators, the feature might even pay for itself (something I don't say blithely, I am a CFO and a programmer :-) ). Seriously, hope this works out.

**Comment by hannesa2** [comment]
I support the opinion of @mikehardy 
"Would be a shame to close this"

**Comment by BanzaiMan** [comment]
We will be moving to the community site for further discussions. Please follow https://travis-ci.community/t/add-kvm-support/1406.
