### ISSUE TITLE
"access denied" when trying to authenticate (Travis API)

### ISSUE THREAD

**Issue by bluzi** [travis-ci/travis-ci#8662]
Hello,

I'm trying to authenticate to the API.
I send a GET request to `/users` with the access token appears in my Travis profile after pressing the eye icon, and the response is: `access denied`.

When am I doing wrong?

**Comment by BanzaiMan** [comment]
That is not the token you want. See https://developer.travis-ci.com/authentication.

**Comment by kopax** [comment]
Hi, We are trying bad to create environment variables using `PATCH` but it seems it is only possible to edit with it.

We have synced our repo from a script, do we really need to login to travis using the web UI and to push our key ourselfs?
