### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by zhenyolka** [travis-ci/travis-ci#8664]
Can I use Travis Ci as Vps? 27/7 time Vps.
I m not about technical part, I m about Term of Use part.
I m not be a ban?
Sorry for my English

**Comment by BanzaiMan** [comment]
We do not offer persistent test VMs/containers, if that's what you are asking.

**Comment by zhenyolka** [comment]
No i ask you. If i use Travis ci for apache server(it restart after 50 minutes automatically, i can write it script) i not be ban?
It look like i use travis 24 hours. I need vps server, for compiling and for ota updates. I need use it all time. 
I not need persistent container, i can make persistent by script.
My question this: i not be ban if i use travis all time(for vps server, game server, ota updates......)?
