### ISSUE TITLE
travis debug issue

### ISSUE THREAD

**Issue by rishijain** [travis-ci/travis-ci#8670]
One of the test is failing at travis and not locally. Travis says `HTML screenshot: file:///home/travis/build/unbxd/console/screenshots/screenshot_2017-10-30-07-38-55.710.html`

Is there a way I can access the file mentioned at `HTML screenshot: file:///home/travis/build/unbxd/console/screenshots/screenshot_2017-10-30-07-38-55.710.html`?

**Comment by BanzaiMan** [comment]
Upload it somewhere with `artifacts`. https://docs.travis-ci.com/user/uploading-artifacts/

**Comment by rishijain** [comment]
thanks  👍
