### ISSUE TITLE
Trigger addon based on cron schedule

### ISSUE THREAD

**Issue by CermakM** [travis-ci/travis-ci#8671]
Hi, 

Is it possible to run addon (*coverity_scan* in this case) only if the build was triggered by *cron*? 
I know I can examine the `TRAVIS_EVENT_TYPE` env. variable if it has `cron` value, but is it possible to integrate this to addon triggering? If so, how? If not, can you consider adding this feature? 

Thank you,

Marek

**EDIT:** Could the coverity_scan addon be somehow 'executed' using jobs - i.e giving it a separate stage?

**Comment by BanzaiMan** [comment]
You can use a conditional job to trigger a coverity scan job if the event type is cron. https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-jobs

It should look something like this:

```yaml
jobs:
  include:
    - if: type = cron
      addons:
      ⋮ # rest
```
