### ISSUE TITLE
Error : object ‘choose.dir’ is not exported by 'namespace:utils'

### ISSUE THREAD

**Issue by carlopacioni** [travis-ci/travis-ci#8673]
@craigcitro  @jimhester
I get the error in the subject when trying to build a R package on travis.
I'm not sure whether I'm doing something wrong, but `choose.dir` is from namespace `utils`, which I'm importing with `importFrom` any idea what may be going wrong? 

Thanks!

**Comment by LiNk-NY** [comment]
Hi Carlo, @carlopacioni 
This looks like a package issue and not a Travis issue. Please close the issue. 
Also, for next time, please provide more information such as a link to the project build. 
Regards,
Marcel
