### ISSUE TITLE
An error occurred while generating the build script.

### ISSUE THREAD

**Issue by lolgear** [travis-ci/travis-ci#8674]
An error occurred while generating the build script.

No more information, even error :/

https://travis-ci.org/yourkarma/JWT/builds/295184679

Duplicate of #8675

**Comment by e-e-e** [comment]
I literally just opened the same issue here - https://github.com/travis-ci/travis-ci/issues/8675

**Comment by lolgear** [comment]
@e-e-e I add thumb up for your issue :)

**Comment by Pr0methean** [comment]
Confirmed with https://travis-ci.org/Pr0methean/BetterRandom/jobs/295162674 which passed the first time I ran it, but then errored out when I ran it again (to make sure these errors on later builds weren't my fault).

**Comment by BanzaiMan** [comment]
We had an outage in `travis-build`, which is responsible for compiling the build script, earlier today. https://www.traviscistatus.com/incidents/xgpn2tq6mx7k

This should be fixed now. If your builds were affected, please restart them.

Thanks.

Closing.
