### ISSUE TITLE
dist: trusty sudo: false creates a precise image

### ISSUE THREAD

**Issue by juchem** [travis-ci/travis-ci#8677]
When using `dist: trusty` with `sudo: false` in my `.travis.yml` I end up getting a precise image, even though the documentation states that this is actually a valid combination: https://docs.travis-ci.com/user/reference/trusty/#Using-Trusty

I found #6025 which has been closed as not an issue, but that's contrary to what the documentation says.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
If you are still seeing the problem, do provide build log URLs. Thanks.
