### ISSUE TITLE
"/home/travis/.android/debug.keystore":  not found

### ISSUE THREAD

**Issue by sjudd** [travis-ci/travis-ci#8679]
I have intermittent build failures on travis when trying to build a series of Android sample APKs. Restarting the job typically makes it pass.

Here's a link to a failing build:
https://travis-ci.org/bumptech/glide/jobs/295210824

The full error message is: 
```
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':samples:giphy:packageDebug'.
> com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "/home/travis/.android/debug.keystore":  not found
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':samples:flickr:packageDebug'.
> com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "/home/travis/.android/debug.keystore":  not found
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================
```

**Comment by BanzaiMan** [comment]
What is supposed to create this file? If the restart fixes the problem, there may be some race condition or another problem with your build setup. See, for example, https://stackoverflow.com/questions/8576732/there-is-no-debug- keystore-in-android-folder

**Comment by sjudd** [comment]
I'd assumed it was part of the travis setup, but I'm pretty sure I'm wrong: https://developer.android.com/studio/publish/app-signing.html. It only mentions the IDE generating the keystore automatically, but I'd guess that it's actually supposed to be generated by the build commands. Maybe a race condition when building with --parallel that's (relatively) common on travis because the file has to be created for each build.

**Comment by sjudd** [comment]
Yeah this is not a travis issue.

If I run:

```
mv ~/.android/debug.keystore ~/.android/debug.keystore.backup
./gradlew build --parallel
```

Then ``~/.android/debug.keystore`` is regenerated.

I've also gotten my local build into the same state that travis seems to be in when this fails exactly once by following the same steps a few times. Weirdly the debug.keystore file is present in ~/.android, but for whatever reason gradle/Android are unable to find or open it.

**Comment by sjudd** [comment]
For posterity: I've tried just copying my own keystore into the expected location in a before_script.
