### ISSUE TITLE
Dotnet SDK 2.0.2/3 not available in trusty

### ISSUE THREAD

**Issue by JustArchi** [travis-ci/travis-ci#8685]
Check out https://travis-ci.org/JustArchi/ArchiSteamFarm/jobs/295621288#L436

`dotnet: 2.0.2` is properly working on **[OS X](https://travis-ci.org/JustArchi/ArchiSteamFarm/jobs/295621289#L36)**. **[Official docs](https://www.microsoft.com/net/learn/get-started/linuxubuntu)** also suggest that there should be no problem in doing `apt-get install dotnet-sdk-2.0.2`. Thank you in advance.

cc @joshua-anderson @akoeplinger @nterry

**Comment by edevyatkin** [comment]
I have the same problem. I think it is because this version of SDK is downloaded from [custom Microsoft repository ](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.2-sdk-download.md).

**Comment by halex2005** [comment]
Same issue for me.
Also there is no dotnet-sdk-1.1.4.

Today dotnet sdk 1.1.5 and dotnet sdk 2.0.3 was released: https://blogs.msdn.microsoft.com/dotnet/2017/11/14/net-core-november-2017-update/

How we can add availability for new versions of dotnet sdk?
