### ISSUE TITLE
Issues when build my .net project into travis

### ISSUE THREAD

**Issue by smtdev** [travis-ci/travis-ci#8688]
I am trying to build my project into travis but it drops many errors that cannot handle. This is my first travis-ci build.

This is the project: https://github.com/smtdev/AutorolaProject-NET
This is the build issue log: https://travis-ci.org/smtdev/AutorolaProject-NET/builds/296028338

Maybe someone can give me some tip in order to fix this.

@joshua-anderson @akoeplinger @nterry - I see I should mentioned you in case of .net issue!

Thank you everyone.

**Comment by Tovli** [comment]
The links are broken

**Comment by BanzaiMan** [comment]
Seems invalid.
