### ISSUE TITLE
.travis/job_stages: line 60: secure: unbound variable

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#8696]
Hi!

We need to source a script in `.travis.yml` (so it can set environment variables), however the script includes the command `set -euo pipefail`, which currently results in the following failure:
`/home/travis/.travis/job_stages: line 60: secure: unbound variable`

(See: https://travis-ci.org/mozilla/treeherder/jobs/296442096#L544)

We can work around this by using `set +u`, however it would be ideal if `.travis/job_stages` could be fixed to either (a) check for variable's existence before using them, or (b) run `set +u` itself.

Many thanks :-)

**Comment by BanzaiMan** [comment]
A duplicate of #5434.
