### ISSUE TITLE
GitHub pages support is experimental log message

### ISSUE THREAD

**Issue by jrbourbeau** [travis-ci/travis-ci#8699]
When using the Travis CI GitHub pages deployment provider, the message `!!! GitHub Pages support is experimental !!!` was put into the log file during the deployment (see https://travis-ci.org/jrbourbeau/pycondor/jobs/296965987#L639 for example). 

I didn't find any reference to GitHub pages deployment being experimental in the corresponding documentation https://docs.travis-ci.com/user/deployment/pages/. 

Is this log message out of date? If not, it might be worth considering adding a note to the documentation mentioning that GitHub pages deployment support is still experimental.

**Comment by Bilge** [comment]
I support your idea but your link doesn't seem to support your claim.

**Comment by jrbourbeau** [comment]
Thanks for the comment @Bilge! I've updated the link
