### ISSUE TITLE
Wrong redis extension version on PHP 7.2

### ISSUE THREAD

**Issue by scara** [travis-ci/travis-ci#8701]
The current PHP `7.2` environment has a redis extension marked as "`develop`" while in PHP `7.1` is properly marked as "`3.1.4`".
Test case: https://github.com/scara/moodle/commit/4ca2cec2fab11bc95b16f050d7009b2d14ee297e
Actual results:
- `7.2`: "`develop`", https://travis-ci.org/scara/moodle/jobs/297010497#L1545
- `7.1`: "`3.1.4`", https://travis-ci.org/scara/moodle/jobs/297010501#L1554
- `7.0`: "`3.1.3`", https://travis-ci.org/scara/moodle/jobs/297010506#L1600

**Comment by BanzaiMan** [comment]
7.2 is still a pre-release, so the components may not be what you expect.

We will revisit the runtime build process once the 7.2.0 is officially out.

**Comment by scara** [comment]
Hi @BanzaiMan,
you're right for the PHP schedule - 7.2 should be GAed on 30/11 - but the PHP redis extension has its own life cycle and the current 3.1.4 would be fine for 7.2.

BTW, TNX for your prompt reply!
Matteo

**Comment by BanzaiMan** [comment]
@scara Thanks for your understanding. When 7.2.0 is added to https://github.com/php-build/php-build/ and still not available on Travis, do ping me, so that we can add support for it.

Thanks again.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/php-src-builder/builds/310545935 built 7.2.0 release with redis ext 3.1.4.

**Comment by scara** [comment]
TNX, appreciated 😄 !
Confirmed at my side too (still using the crafted branch above):
- 7.2.0: https://travis-ci.org/scara/moodle/jobs/310612999#L497
- 3.1.4: https://travis-ci.org/scara/moodle/jobs/310612999#L1549
