### ISSUE TITLE
How to skip some commands when using cache?

### ISSUE THREAD

**Issue by Mehdzor** [travis-ci/travis-ci#8704]
I've a few heavy preparation commands I want to save to a cache. Even tho they're being saved, they still run again every time. 
How do I skip it if the cache is up to date? Do I've to write skip-or-run conditions manualy?

**Comment by Bilge** [comment]
Yes, of course. The cache is just a data store, it doesn't bear any logic or intelligence.

**Comment by Mehdzor** [comment]
I mean there is an install step. I do some work and then cache a result. 
How do I skip the install step next time when the cache is up?

**Comment by Bilge** [comment]
By making the installation conditional based on something you've cached, presumably something generated by the previous installation.

**Comment by Mehdzor** [comment]
So I've to do it manualy by putting in conditions in my script. Okay, ty.
