### ISSUE TITLE
requesting perl6 '2017.10', getting '2017.1'

### ISSUE THREAD

**Issue by dwarring** [travis-ci/travis-ci#8707]
Example build: https://travis-ci.org/p6-pdf/Font-FreeType-p6/builds/297276886

The travis configuration for this build was: https://github.com/p6-pdf/Font-FreeType-p6/blob/191133f854fce03960b19125b0182a922872dfeb/.travis.yml

second job configuration not as expected: https://travis-ci.org/p6-pdf/Font-FreeType-p6/jobs/297276888/config

with `perl6: 2017.1`, instead of perl6: 2017.10`.

cc @paultcochrane, @hoelzro, @ugexe, and @tony-o

**Comment by ugexe** [comment]
Have you tried with `perl6: "2017.10"`?

**Comment by dwarring** [comment]
@ugese - just kicked off a build. Yes that seems to work https://travis-ci.org/p6-pdf/Font-FreeType-p6/builds/297293669

**Comment by dwarring** [comment]
Does actually say to quote it in the documentation https://docs.travis-ci.com/user/languages/perl6/. Thanks for pointing me in the right direction.
