### ISSUE TITLE
IPv6 sockets returning "Cannot assign requested address"

### ISSUE THREAD

**Issue by evgeni** [travis-ci/travis-ci#8711]
Ohai,

since about a week, we have issues when running our tests for [robotello-ci](https://github.com/SatelliteQE/robottelo-ci). That repository hosts our Jenkins configuration using jenkins-job-builder.

Debugging the issue, I was able to reproduce the same kind of error on a much smaller test repository: https://github.com/evgeni/potential-pancake

This repo just tries to bind (server.py) or connect to (client.py) sockets using Python. Everything is fine when using IPv4 (on localhost), but IPv6 raises "Cannot assign requested address" errors (see the errors in the build log: https://travis-ci.org/evgeni/potential-pancake/builds/297995394).

I think the issue of the original repo is that it tries to connect to `localhost:8080`, which gets resolved to `[::1]:8080` and then we see the above error (and the error handling code is not expecting this error, so it dies, instead of triggering the right action). [connection refused is fine, it uses a cached/dummy result set then, which is exactly what we want here]

So there are the following two things to look at:
* why don't IPv6 sockets work as they should?
* why does `/etc/hosts` look a bit broken, with multiple `localhost` entries?
```
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.25	travis-job-evgeni-potential-panc-297995395.travisci.net travis-job-evgeni-potential-panc-297995395
127.0.0.1 localhost 127.0.0.1	localhost
```

Workarounds:
* use `sudo: true`
* force IPv4 sockets

**Comment by williamtu** [comment]
we also have similar issue. In our testcase, we try to bind the IPv6 loopback address for some testing. It was working find a week ago, but start to fail last week.
The error message
```
0:[::1]: bind: Cannot assign requested address
```
https://travis-ci.org/openvswitch/ovs/jobs/298249021

**Comment by msteveb** [comment]
Same here:

`::1:5001: Cannot assign requested address`

https://travis-ci.org/msteveb/jimtcl/builds/298791809

**Comment by bel2125** [comment]
There are more recent issue reports for the broken IPv6 support:
https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-341420858,  #8695, #8693

I think we all just need an IPv6 loopback [::1] adapter to work. An "ifconfig" call in my build script shows was an [IPv6 address](https://travis-ci.org/civetweb/civetweb/jobs/294261624#L657), but now there is [no IPv6 address](https://travis-ci.org/civetweb/civetweb/jobs/297274651#L656).

**Comment by bel2125** [comment]
I did some tests to figure out if there is a way to enable IPv6 with some shell commands, but did not succeed yet (see https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-345074513) - maybe someone else has an idea how to do that.

Meanwhile, there is yet another report of IPv6 failing: #8755

**Comment by bel2125** [comment]
Maybe this fix will help here as well:
https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350497804

**Comment by mrmark** [comment]
This might be related to a Selenium problem where it cannot connect to `localhost:8000`, but it works fine if I use `sudo: true`.

`/etc/hosts` when `sudo: false`:
```
::1	 ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.13	travis-job-moodlerooms-moodle-plugin-335223259.travisci.net travis-job-moodlerooms-moodle-plugin-335223259
127.0.0.1 localhost 127.0.0.1	localhost 
```

`/etc/hosts` when `sudo: true`:
```

127.0.1.1 travis-job-b39720bc-54bf-49ea-a648-5f0e3b1ad9bd travis-job-b39720bc-54bf-49ea-a648-5f0e3b1ad9bd ip4-loopback trusty64

127.0.0.1 localhost nettuno travis vagrant
```

Hope this helps, cheers!

**Comment by snarkmaster** [comment]
Travis & Travis + Docker workarounds that worked for me (`sudo` should be `true` or `required` for both):

 - To enable IPv6 loopback `::1` on the VM itself, I followed this: https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350090030 — just add this to `.travis.yml`:

```
before_script:
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
```

- In my case, I am actually running my build inside Docker inside the Travis sudo-enabled VM, so the above doesn't help at all. Instead, I had to enable IPv6 for Docker inside my `.travis.yml`. Here is the rough patch:

```
# Docker disables IPv6 in containers by default, so re-enable it.
before_script:
  # `daemon.json` is normally missing, but let's log it in case that changes.
  - sudo touch /etc/docker/daemon.json
  - sudo cat /etc/docker/daemon.json
  - sudo service docker stop
  # This needs YAML quoting because of the curly braces.
  - 'echo ''{"ipv6": true, "fixed-cidr-v6": "2001:db8:1::/64"}'' | sudo tee /etc/docker/daemon.json'
  - sudo service docker start
  # Fail early if docker failed on start -- add `- sudo dockerd` to debug.
  - sudo docker info
  # Paranoia log: what if our config got overwritten?
  - sudo cat /etc/docker/daemon.json
```

**Comment by ioquatix** [comment]
Having the exact same problem.

https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350497804 has a solution.

**Comment by evgeni** [comment]
That's not a solution, esp not one if you do not want to have `sudo: true` ;)

**Comment by ioquatix** [comment]
@evgeni Dude, it's a solution. I agree thought, it's a shitty one.

**Comment by ioquatix** [comment]
This is still an issue

**Comment by evgeni** [comment]
True, but I can't re-open the issue now.

**Comment by graingert** [comment]
https://travis-ci.community/t/issue-cannot-assign-requested-address-when-connecting-to-1/1098/4
