### ISSUE TITLE
Caching shows `sw_vers: not found` (but the command should succeed)

### ISSUE THREAD

**Issue by ncordon** [travis-ci/travis-ci#8714]
@craigcitro, @jimhester Travis CI is failing when uploading cache in its R-version. It tries to use `sw_vers` inside Ubuntu systems and this seems to be a MacOS command.

![store-cache](https://user-images.githubusercontent.com/5649971/32456133-c9c32de2-c324-11e7-80b0-ffcc27e8d224.png)

The build in which that situation takes place does not fail, but following ones do if they try to use that cache.

https://travis-ci.org/ncordon/imbalance/builds/297608670

**Comment by BanzaiMan** [comment]
Sorry about the noise. The upload should still happen, and the subsequent build shows that it's using the cache. https://travis-ci.org/ncordon/imbalance/builds/297944416#L832

**Comment by BanzaiMan** [comment]
FWIW, the fix is in the `master` branch, but it is not yet deployed to production. If the message really bothers you, you can suppress it with:

```yaml
cache:
  edge: true
  ⋮ # rest
```

Or, if your cache directive is as simple as `cache: bundler`, you need to turn it into `bundler: true`; e.g.,

```yaml
cache:
  edge: true
  bundler: true
```

I plan to deploy it Monday.

**Comment by ncordon** [comment]
@BanzaiMan Thanks a lot!

**Comment by Richard-Cao** [comment]
I think my settings are right. But why I meet the same problem?
This is my job: https://travis-ci.org/attentiveness/reading/jobs/304358723#L4622

**Comment by BanzaiMan** [comment]
The noise should no longer appear.
