### ISSUE TITLE
Cannot uninstall bundler in order to change the bundler version for ruby build

### ISSUE THREAD

**Issue by dyg2104MD** [travis-ci/travis-ci#8717]
Uninstalling bundler with the following command fails

rvm @global do gem uninstall bundler

the error message is 

```
ERROR:  While executing gem ... (Gem::InstallError)
    gem "bundler" cannot be uninstalled because it is a default gem
```

my build is on ruby 2.3.3, rvm 1.29.2, and rubygems 2.7.1. 

i know that bundler will be a default gem in ruby 2.5.0 and above, but since i am using ruby 2.3.3 i would expect this to work.

**Comment by dyg2104MD** [comment]
it looks like bundler is included as a default gem for ruby 2.3.3 on travis here 

``` /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/specifications/default/bundler-1.16.0.gemspec ```

but i'm not sure why.

**Comment by MSP-Greg** [comment]
It seems 2.3.4 & 2.4.1 also have gem issues with bundler.

See https://travis-ci.org/MSP-Greg/travis-ruby/builds/298359169

**Comment by BenFradet** [comment]
The default bundler install seems weird too, I personally only have an `exe/` folder, no `lib/` nor gemspec.

**Comment by AlexanderBelonogov** [comment]
Got the same issue when trying to use bundler with lower version. I fixed that by downgrade `rvm`:
```yaml
before_install:
- rvm implode --force
- \curl -sSL https://get.rvm.io | bash -s 1.27.0
- rvm reload
- rvm install 2.2.3
- gem uninstall -i /home/travis/.rvm/gems/ruby-2.2.3 bundler -x
- gem install bundler -v 1.12.5
```

**Comment by Sharpie** [comment]
Another strategy I've found effective is to remove the entry under `specifications/default/` before installing the version I need:

```yaml
before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem install bundler --version $BUNDLER_VERSION
```
Hacky and bothersome, but some day I won't be testing against a Vagrant dependency that is chained to specific versions of Bundler...
