### ISSUE TITLE
R Bioconductor package timeouts

### ISSUE THREAD

**Issue by mjsteinbaugh** [travis-ci/travis-ci#8719]
I'm running into build timeout problems with some Bioconductor packages currently in development. After the 3.6 release last week, I had to reset the cache on these packages: [bcbioRNASeq](https://github.com/hbc/bcbioRNASeq) and [bcbioSingleCell](https://github.com/hbc/bcbioSingleCell). Now I can't get the builds to cache because the Bioconductor installation is taking too long and causing the build to time out. What is the recommended approach to fix this issue? The problem is happening with both `bioc-release` and `bioc-devel`, although those packages are currently only testing against `bioc-devel` at the moment.

@craigcitro, @jimhester, @lpantano

**Comment by jimhester** [comment]
There is a hard 50 minute total time limit for jobs, if your build is taking longer than that there isn't much you can do AFAIK.

However in both cases the dependencies are getting built, so you could do a build with `script: true` to force a successful build (and populate the package cache), then remove that and do the build as normal. In the second case the build fails when running covr, so the cache was populated, and subsequent builds should use the cache and be faster.

**Comment by mjsteinbaugh** [comment]
Okay great thanks @jimhester we will try this.

**Comment by mjsteinbaugh** [comment]
@jimhester Just to follow up, this works perfectly. Thanks for the tip!
