### ISSUE TITLE
macOS builds fail because of connectivity problems

### ISSUE THREAD

**Issue by fniephaus** [travis-ci/travis-ci#8728]
I assume it is related to [this incident](https://www.traviscistatus.com/incidents/znkxsp5x79cf), but opening this issue anyway. macOS builds currently fail immediately after booting with the following error:

```
Download from https://build.travis-ci.org/filter/redirect_io.rb failed. Trying https://build.travis-ci.com/filter/redirect_io.rb ...

ruby: No such file or directory -- /Users/travis/filter.rb (LoadError)
```

![image](https://user-images.githubusercontent.com/2368856/32603073-b40ee79a-c548-11e7-9c18-c7b700b5205f.png)

**Comment by gallandarakhneorg** [comment]
I confirm this issue.

**Comment by asalom** [comment]
We also have it

**Comment by annejan** [comment]
Same thing happening to my QtPass builds . .

**Comment by makma** [comment]
Same on my project (swift) on my CRON job build
`$ git clone --depth=50 --branch=master https://github.com/Kentico/cloud-sdk-swift.git Kentico/cloud-sdk-swift
Cloning into 'Kentico/cloud-sdk-swift'...
fatal: unable to access 'https://github.com/Kentico/cloud-sdk-swift.git/': Could not resolve host: github.com
The command "eval git clone --depth=50 --branch=master https://github.com/Kentico/cloud-sdk-swift.git Kentico/cloud-sdk-swift " failed. Retrying, 2 of 3.`

**Comment by fniephaus** [comment]
They are on it: https://www.traviscistatus.com/incidents/rqf3s76q1rtw

**Comment by Lutzifer** [comment]
fixed for us

**Comment by fniephaus** [comment]
The incident is resolved. Thanks Travis CI team! 😃
