### ISSUE TITLE
Random Github repositories have locks and can't be activated

### ISSUE THREAD

**Issue by solvingj** [travis-ci/travis-ci#8733]
I currently cannot think of an explanation as to why some of these repos show locks, and some don't.  I created them all, under an org for which I am the owner. 

![image](https://user-images.githubusercontent.com/8557737/32648983-38e81928-c5c6-11e7-8358-8a97d9b912be.png)

**Comment by BanzaiMan** [comment]
Not entirely clear to me why, but we cannot find active admins for the greyed repositories.

**Comment by solvingj** [comment]
went back an hour later, the one i wanted to build was unlocked, some others are still locked.

**Comment by timofonic** [comment]
@solvingj @BanzaiMan Any news?

**Comment by BanzaiMan** [comment]
@solvingj @timofonic which repos are still affected by this?

**Comment by solvingj** [comment]
Sorry, it's the intermittent-type problem... can't reproduce on-demand. When it happens, there's no real-time way to notify you other than the ticket.

**Comment by BanzaiMan** [comment]
@solvingj I meant: are your repos still affected?

**Comment by solvingj** [comment]
no, we can close issue imo

**Comment by BanzaiMan** [comment]
Great. If anyone else sees this error, please open a separate issue.

Thank you.
