### ISSUE TITLE
iv undefined with encrypted settings in pull request

### ISSUE THREAD

**Issue by jdiazcano** [travis-ci/travis-ci#8736]
Hello,

I have been running this build for a while already but pull requests started failing like 2 weeks ago.

https://travis-ci.org/jdiazcano/cfg4k/builds/300044625

This is the latest build. I have tried clearing the caches etc and nothing helps!

**Comment by BanzaiMan** [comment]
As clearly indicated in https://docs.travis-ci.com/user/encrypting-files, external PRs do not have access to secrets, including encrypted files.

**Comment by tansaku** [comment]
@BanzaiMan is there a way for the travis build to notice when a PR is external and choose whether or not to try running the openssl command?

**Comment by BanzaiMan** [comment]
@tansaku You can check `TRAVIS_REPO_SLUG` and `TRAVIS_PULL_REQUEST`. See https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
