### ISSUE TITLE
Trigger PHP 5.6.32 php-src-builder builds on xenial

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#8737]
Hi!

The previous PHP 5.6.32 build failed on Xenial:
https://travis-ci.org/travis-ci/php-src-builder/builds/300190605

However since then the Xenial builds have been fixed on master, in travis-ci/php-src-builder#16.

@BanzaiMan, please could new builds be triggered, to unblock travis-ci/travis-cookbooks#939 ?

Many thanks :-)

**Comment by BanzaiMan** [comment]
Looks like the complier can't find `gmp.h`. https://travis-ci.org/travis-ci/php-src-builder/jobs/300457705#L567

The package which is supposed to provide it (`libgmp-dev`) is already installed, so I don't know what else to do here.

**Comment by edmorley** [comment]
Thank you for triggering those - I think perhaps it's just best I disable the few things that are causing Opal/Sardonyx to fail for now - I've opened travis-ci/packer-templates#549.
