### ISSUE TITLE
Github push not triggering very basic travis ci

### ISSUE THREAD

**Issue by Dean-Coakley** [travis-ci/travis-ci#8739]
I can manually trigger builds from travisci but pushing commits to github repository does nothing.

I think it is the domain url of my github repo might be incorrect. I set it to the url of my travis ci project. Incorrect?

Or do I need to setup some other hook?

**Comment by BanzaiMan** [comment]
Sorry to hear about your problem. Have you looked at our Getting Started Guide? https://docs.travis-ci.com/user/getting-started/

Please read it and follow the instructions, and if you still have problems, please indicate:

* What repository you are having problems with
* What account you are authenticated as

**Comment by Dean-Coakley** [comment]
@BanzaiMan My domain url was indeed incorrect.

Thanks.
