### ISSUE TITLE
Please add ability to docker experimental features

### ISSUE THREAD

**Issue by nkonev** [travis-ci/travis-ci#8740]
I want to test my docker swarm build with compose file.
This is 
```
docker stack deploy --compose-file docker-compose.template.yml MYSTACK
```

`--compose-file` works only if experimantal features turned on 
For turn on docker experimental features I need execute this
```sudo echo '{"experimental":true}' > /etc/docker/daemon.json```
But if iI do it I face error `Permission denied` https://travis-ci.org/nkonev/blog/builds/300630813#L2536
Seems some security software block this.

It'll be cool if I can enable docker experimantal  features, by adding somthing like
```
docker_experimental: true
```
in .travis.yaml

**Comment by BanzaiMan** [comment]
Your invocation of `sudo` with I/O redirection does not work. If you try it on your machine with `sudo`, it should fail, too.

Try:

    echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json

**Comment by pauldotknopf** [comment]
How do I restart the docker service, after writing that file?

**Comment by nkonev** [comment]
@pauldotknopf 
`sudo service docker restart`

**Comment by EdoFede** [comment]
Tried today on the last docker version (19.03.5) on Travis, in order to use "docker run --platform" features, but no way to restart docker after changing /etc/docker/daemon.json.


.travis.yml
```
before_install:
  - ./scripts/travisDockerSetup.sh
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
```

scripts/travisDockerSetup.sh
```
echo ""
echo -e "\033[0;34m# OLD Docker engine config file \033[0m"
sudo ls -la /etc/docker/daemon.json
sudo cat /etc/docker/daemon.json

echo ""
echo -e "\033[0;34m# Enabling Docker engine experimental mode \033[0m"
echo '{"registry-mirrors": ["https://mirror.gcr.io"], "mtu": 1460, "experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
sudo chown travis:travis /etc/docker/daemon.json

echo ""
echo -e "\033[0;34m# NEW Docker engine config file \033[0m"
sudo ls -la /etc/docker/daemon.json
sudo cat /etc/docker/daemon.json
```



Job log:
```
# OLD Docker engine config file 
-rw-rw-r-- 1 travis travis 61 Jan 19 19:55 /etc/docker/daemon.json
{"registry-mirrors": ["https://mirror.gcr.io"], "mtu": 1460}

# Enabling Docker engine experimental mode 
{"registry-mirrors": ["https://mirror.gcr.io"], "mtu": 1460, "experimental":"enabled"}

# NEW Docker engine config file 
-rw-rw-r-- 1 travis travis 87 Jan 19 19:56 /etc/docker/daemon.json
{"registry-mirrors": ["https://mirror.gcr.io"], "mtu": 1460, "experimental":"enabled"}

...

Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2020-01-19 19:56:24 UTC; 7ms ago
     Docs: https://docs.docker.com
  Process: 5691 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 5691 (code=exited, status=1/FAILURE)
```

Same issue trying to restart docker after the update, or before.
Tried also to modify the docker.service, adding " --experimental=true" to the exec line.
No success :(

**Comment by bubuntux** [comment]
i was able to use docker experimental features using 

`cat <<< $(jq '.+{"experimental":"enabled"}' ~/.docker/config.json) > ~/.docker/config.json`

no need to restart the service, just make sure to have jq installed

reference -> https://github.com/bubuntux/nordvpn/blob/master/.travis.yml

**Comment by EdoFede** [comment]
@bubuntux Thanks.
This enables experimental features on docker client, which can be done also with
`echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json`
but not non server-side.
