### ISSUE TITLE
my Github repo is not anymore sync with Travis... 

### ISSUE THREAD

**Issue by erwin16** [travis-ci/travis-ci#8743]
Even when I try to resynch ( button synch) Travis is always getting an old commit .. never the last one...
Is there anyway to remove the repo ? or delete my Travis account and reset it .. ? 
no info on it in the doc...

(public repo : erwin16/ShoppingLists    latest commit #28d516f on GitHub  but #c81b63e in Travis

**Comment by BanzaiMan** [comment]
https://travis-ci.org/erwin16/ShoppingLists/requests shows that you have disabled push builds in the repository settings.

**Comment by HabibSentongo** [comment]
I have this same issue, I'm stuck to a commit to an old version of my commit, for which I amended and force pushed updates but Travis doesn't see them. And I only see one branch on Travis, I wanted to create a dummy brunch and test the updates with it but I can't see my other branch no matter how many time I resync the repos.
