### ISSUE TITLE
PHP 7.2 segfault since today only

### ISSUE THREAD

**Issue by Bilge** [travis-ci/travis-ci#8746]
All my PHP 7.2 builds are segfaulting starting from today only on commit hashes that were passing yesterday. Something has changed today in the PHP 7.2 build that causes PHPUnit to consistently crash at start-up.

* [Example 1](https://travis-ci.org/ScriptFUSION/Mapper/jobs/301010491) (PHPUnit 4)
* [Example 2](https://travis-ci.org/Provider/Steam/jobs/301020920) (PHPUnit 6)

It seems that, during this time, PHP 7.2 has been upgraded from RC5 to RC6. Not sure if this is a fault of Travis, PHP, or PHPUnit.

**Comment by BanzaiMan** [comment]
Same as https://github.com/travis-ci/travis-ci/issues/8748. Delete the cache and rerun.

**Comment by Bilge** [comment]
Some of those jobs don't even have a cache.

**Comment by BanzaiMan** [comment]
The root cause seems the same, though. It appears to me that PHPUnit is incompatible with 7.2.0RC6.

**Comment by Bilge** [comment]
@BanzaiMan Whilst it's not impossible, it seems highly unlikely. It's far more likely there's a binary incompatibility between RC6 and the Xdebug build you're currently integrating. That certainly seems to be Remi's conclusion, since [he can run PHPUnit on RC6 with the latest snapshot](https://github.com/sebastianbergmann/phpunit/issues/2853#issuecomment-343950847).

If it's not too difficult or time consuming, could you try upgrading the Xdebug binary for RC6 on Travis?

**Comment by BanzaiMan** [comment]
To the best of my knowledge, we use the bleeding edge `xdebug` code. https://travis-ci.org/travis-ci/php-src-builder/jobs/300761864#L729

**Comment by BanzaiMan** [comment]
I believe that is defined by php-build. https://github.com/php-build/php-build/blob/af73e8d359101d89d8b0cae02b93d050f54e5557/share/php-build/definitions/7.2.0RC6#L2

**Comment by BanzaiMan** [comment]
At any rate, please add your comments to the other issue. I think it is the same issue, no matter where the root cause lies.
