### ISSUE TITLE
Jobs are exiting with empty logs

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#8747]
None of the following builds shows anything when I open the log, and the "raw log" only yields `{"log":{"job_id":301198522,"parts":[],"@type":"Log"}}` (except with different values of job_id).

https://travis-ci.org/Pr0methean/BetterRandom/jobs/301198522 (passed)
https://travis-ci.org/Pr0methean/BetterRandom/jobs/301198523 (failed)
https://travis-ci.org/Pr0methean/BetterRandom/jobs/301198524 (passed)
https://travis-ci.org/Pr0methean/BetterRandom/jobs/301198528 (failed)
https://travis-ci.org/Pr0methean/BetterRandom/jobs/301198533 (passed)

**Comment by Pr0methean** [comment]
This affects both Linux and OSX jobs, all with sudo:required

**Comment by Pr0methean** [comment]
Update: This may be a transient issue; I can no longer reproduce it.

**Comment by BanzaiMan** [comment]
Thanks for bringing to our attention. In some instances the logs can take a little while to be presented after they are archived.
