### ISSUE TITLE
PHPUnit crashes with "Segmentation fault      (core dumped) php vendor/bin" with PHP 7.2 (which is 7.2.0RC6)

### ISSUE THREAD

**Issue by medz** [travis-ci/travis-ci#8748]
I do not know what the problem is, just a few days ago it was fine.
But today my build fails to run on version 7.2 of PHP.
Work: https://travis-ci.org/slimkit/thinksns-plus/jobs/301196847#L1471

**Comment by BanzaiMan** [comment]
PHP 7.2 has been updated to a recent RC release. If your cache contains any binary file, most likely it is now incompatible with 7.2. Please delete the cache and re-run the job.

**Comment by ptomulik** [comment]
This happens also in my build

https://travis-ci.org/ptomulik/oldbro-ldap/jobs/301389552

I have no cache.

**Comment by BanzaiMan** [comment]
@ptomulik Where is `vendor/bin/phpunit` coming from? That's probably the culprit.

**Comment by ptomulik** [comment]
Installed via composer. My composer.json:
```json
{                                                                               
    "name": "ptomulik/oldbro-ldap",                                             
    "description": "LDAP client library for OLDBRO project",                    
    "type": "library",                                                          
    "license": "MIT",                                                           
    "authors": [                                                                
        {                                                                       
            "name": "Paweł Tomulik",                                            
            "email": "ptomulik@meil.pw.edu.pl"                                  
        }                                                                       
    ],                                                                          
    "require": {},                                                              
    "autoload": {                                                               
      "psr-4" : {                                                               
        "Oldbro\\Component\\Ldap\\" : "src/Oldbro/Component/Ldap",              
        "Oldbro\\Component\\Ldap\\ExtLdap\\" : "src/Oldbro/Component/Ldap/ExtLdap"
      }                                                                         
    },                                                                          
    "require-dev": {                                                            
        "phpunit/phpunit": "^6.4",                                              
        "php-mock/php-mock-phpunit": "^2.0",                                    
        "phake/phake": "^3.0",                                                  
        "symfony/options-resolver": "^3.3"                                      
    }                                                                           
}                                                                               
```

**Comment by kylekatarnls** [comment]
The same happend to me suddently:

https://travis-ci.org/phug-php/renderer/jobs/301395968
https://travis-ci.org/pug-php/pug-filter-less/jobs/300991314
https://travis-ci.org/pug-php/pug-filter-less/jobs/300991315

I have any cache settings and also use phpunit from local vendor/bin installed with composer and use PHPUnit 5.7.23.

**Comment by BanzaiMan** [comment]
Does that version of PHPUnit work with 7.2.0RC6 if you run your tests locally?

**Comment by Bilge** [comment]
I wish I could answer that, but PHP.net doesn't provide [Windows builds](http://windows.php.net/download/) for RCs, so I'll need to leave it to someone on Unix to test it.

**Comment by BanzaiMan** [comment]
OK. Please try running it with:

```yaml
php:
  - '7.2'
  - '7.2.0RC5'
```
and compare the results.

**Comment by Bilge** [comment]
[Done](https://travis-ci.org/Porter-connectors/FileConnector/builds/301565919).

**Comment by BanzaiMan** [comment]
OK. So the same code works with RC5, but not with RC6. I suggest getting in touch with PHPUnit team, then.

**Comment by BanzaiMan** [comment]
@Bilge Could you also try deleting cache to ensure that the jobs are in equal footing? Thanks.

**Comment by Bilge** [comment]
@BanzaiMan I've already done this for another job. Besides, as I mentioned, [that cache is empty](https://travis-ci.org/Porter-connectors/FileConnector/caches) anyway.

**Comment by Bilge** [comment]
@BanzaiMan Although it seems you are building the latest dev-master Xdebug snapshop, I couldn't help but note the [build you cited](https://travis-ci.org/travis-ci/php-src-builder/jobs/300761864#L729) was completed two days ago. Meanwhile, there have been [more recent commits to Xdebug's master branch](https://github.com/xdebug/xdebug/commits/master) in the past 24 hours. Perhaps it would be worth rebuilding?

**Comment by BanzaiMan** [comment]
Sure. It is worth a shot. https://travis-ci.org/travis-ci/php-src-builder/builds/301751395

**Comment by Bilge** [comment]
@BanzaiMan [The build is passing now](https://travis-ci.org/Porter-connectors/FileConnector). Thank you for staying late to fix this issue and indulging my conjecture. 👍 👍 👍

**Comment by BanzaiMan** [comment]
@Bilge Thanks for your suggestion. Without it, we could've been in for a whole lot of frustration.

I'll close this optimistically, but if anyone still sees the problem *after* restarting the affected builds, do let me know. I'm traveling this week for a conference, so the responses may be slower, but I'll keep an eye on this.

**Comment by Bilge** [comment]
@BanzaiMan Thanks again. I'm pretty sure we're good; I just rebuilt all my failing projects and they're fine now.

**Comment by medz** [comment]
@BanzaiMan I use php7.2RC locally to run phpunit properly.

**Comment by medz** [comment]
@BanzaiMan Thanks for the reply.

**Comment by ptomulik** [comment]
[My build](https://travis-ci.org/ptomulik/oldbro-ldap/jobs/301389552) is passing too. Thanks.
