### ISSUE TITLE
Java six-monthly releases

### ISSUE THREAD

**Issue by jodastephen** [travis-ci/travis-ci#8751]
Java is moving to have a new release every six months, with an LTS release (long term support) every three years or so. Some more details [here](http://www.oracle.com/technetwork/java/eol-135779.html) and [here](https://mreinhold.org/blog/forward-faster).

As part of this change, non-LTS releases of Java will only have an official lifetime of 6 months. On the release of the next version, the previous release is officially considered to be dead. Note that Java 9 is a non-LTS release and is scheduled to expire in March 2018 when Java 10 is released. Similarly, Java 10 is scheduled to expire in September 2018 when Java 11 is released.

As of now, it is not clear how this will work in practice, and what versions of Java Travis should support. However, to work at all, it will be necessary to be able to test a version of Java before its release date (so that you can move to the new version on the day of release (in case there is a security patch).

At a minimum, I'd suggest that Travis would need to support each LTS release for around 4 years, and each non-LTS release for around a year. However, this may change if the OpenJDK community ends up providing security-patched releases for a longer period.

Given that Travis has historically had a low frequency of updates, the above represents a challenge, as it needs updates to the available Java versions perhaps once every two weeks (picking up any security patch releases, and the latest early-access version of the next release). Specifically, on the model outlined above, Java 10-ea should already be available in Travis and would need to be updated every couple of weeks until it is released.

**Comment by BanzaiMan** [comment]
It is not very clear to me how this change in release cycles would affect Travis CI, to be honest.

Our build images rely on the apt packages provided by https://launchpad.net/~webupd8team/+archive/ubuntu/java, to start. They may not keep older packages available for long, and that would greatly affect our ability to stay current.

Releasing a new version of JDK every two weeks seems unrealistic.

**Comment by jodastephen** [comment]
The [key part](http://www.oracle.com/technetwork/java/eol-135779.html) is "Java SE 9 will be a short term release, and users should immediately transition to the next release (10, previously 18.3) when available". In order to transition to Java 10 on the release date, developers have to test it before release. which means that Java 10 early access should be on Travis now, and Java 11 early access should be on Travis pretty much as soon as Java 10 is released. I don't have all the answers, but its good to have an issue to track the frequent updates problem.

**Comment by robilad** [comment]
It seems that the Ubuntu OpenJDK packagers have started to provide OpenJDK 10 builds for Bionic, judging by https://packages.ubuntu.com/source/bionic/openjdk-10 .

**Comment by the8472** [comment]
a `jdk: latest` switch would be great.

**Comment by pmonks** [comment]
+INF to what @the8472 said.  Having `jdk:lts`, `jdk:current`, etc. would be phenomenal.

**Comment by Albertus82** [comment]
@the8472 Could `jdk:lts` and `jdk:current` make the builds not reproducible? Perhaps Travis should translate `lts` and `current` into real version numbers on the first run of a certain build, store them in the job config(s) and use them for any subsequent rebuild.

**Comment by pmonks** [comment]
@albertus82 as I understand the proposal, jdk:lts and jdk:current would be in addition to specific version identifiers, so anyone concerned about reproducibility could use those instead.

**Comment by Albertus82** [comment]
@pmonks Travis already does this kind of things, e.g. the "dist" option that is automatically added to the build configuration when it's not specified in `travis.yml`; in that case the default _pro tempore_ value is used and stored permanently in that specific build. A similar behavior may be applied to the proposed options; this would guarantee reproducibility as well as the adoption of the best JDK from time to time. Just my two cents.

**Comment by the8472** [comment]
> Perhaps Travis should translate lts and current into real version numbers on the first run of a build, store them in the job config(s) and use them for any subsequent rebuild.

Sounds reasonable.
