### ISSUE TITLE
PHP 7.2 build skips fail error code and report success build

### ISSUE THREAD

**Issue by TomasVotruba** [travis-ci/travis-ci#8752]
I think this will be related to PHP 7.2 in some way.

Here is fail error code 1:
https://travis-ci.org/Symplify/Symplify/jobs/301444878#L605

![image](https://user-images.githubusercontent.com/924196/32733258-0c768a84-c88f-11e7-8d19-6ed6ff55b37f.png)

But build ends with success:

![image](https://user-images.githubusercontent.com/924196/32733287-22ee7c2c-c88f-11e7-97c8-4fbc1facbc57.png)

**Comment by BanzaiMan** [comment]
Is that the correct build?

**Comment by TomasVotruba** [comment]
It looks like not. I cannot find it now, only the last or 4+ month old build are there.
