### ISSUE TITLE
Does cache: ccache do anything with language: rust?

### ISSUE THREAD

**Issue by nox** [travis-ci/travis-ci#8753]
I don't know if `cache: ccache` properly saves the cache with any other language than `c`, e.g. `rust`.

**Comment by asajeffrey** [comment]
This impacts any Rust build that uses gcc, for example https://github.com/asajeffrey/josephine/issues/46 uses ccache, but this has no effect because it's a Rust project.

**Comment by BanzaiMan** [comment]
The only cache shortcut that takes effect for `language: rust` builds is `cache: cargo`. This is documented in https://docs.travis-ci.com/user/languages/rust#Dependency-Management.
