### ISSUE TITLE
Python builds fail to install python-geoip-geolite2 

### ISSUE THREAD

**Issue by sloria** [travis-ci/travis-ci#8756]
A number of our builds have been failing on installing `python-geoip-geolite2==2015.0303`.

Example failing jobs:

- https://travis-ci.org/CenterForOpenScience/osf.io/jobs/301504394
- https://travis-ci.org/CenterForOpenScience/osf.io/jobs/301504424

The package exists on PyPI (https://pypi.python.org/pypi/python-geoip-geolite2/2015.0303), and I've verified locally that I can install it succesfully.

This happens even after clearing Travis caches. We first noticed this problem this morning, and it has been happening throughout the day.

**Comment by brianjgeiger** [comment]
And clearing out the cache will make the branches that used to pass fail, such as https://travis-ci.org/CenterForOpenScience/osf.io/builds/301504462

**Comment by sloria** [comment]
@travis-ci Is there a limit on disk usage for each build?

**Comment by BanzaiMan** [comment]
Each VM/Container has limited disk spaces.

**Comment by sloria** [comment]
Our builds ended up passing after reordering nvm and yarn install to go after pip commands: https://github.com/CenterForOpenScience/osf.io/commit/4c32da15056fa4e6c5edec6b51a1899da348c210 . 

We have no idea why this fixed it, but our issue is resolved. So closing this.
