### ISSUE TITLE
GNU Make "write error" on osx builds

### ISSUE THREAD

**Issue by felker** [travis-ci/travis-ci#8757]
(sorry I accidentally hit Enter prematurely on this issue)

I am testing a C++ project on both the `osx` VM and Ubuntu `trusty` container environments. The Python test driver in the `script` step repeatedly builds the code with GNU Make, runs the code, and then processes the output. 

While the code runs correctly on the Linux builds, it errors due to `make: write error` in the linking step of compilation on osx builds. The error doesn't usually occur with the first compilation of the code; usually the second or third compilation causes the issue. Even stranger, the error shows up in the middle of a statement in the output log, e.g.

```
/Users/travis/build/johmake: write error
```
where `joh` is part of 'john', an example user directory. 

I have tried `xcode_image=xcode9.1` and `xcode_image=xcode7.3`.  This may be an issue with GNU Make on osx, but I am unable to reproduce it on my personal MacBook. `make --version` returns GNU Make 3.81,  built for i386-apple-darwin11.3.0

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

There is nothing in this issue that can be acted on.

**Comment by felker** [comment]
Here is an example build log: https://travis-ci.com/felker/athena/jobs/98230768

Things I have tried:

- Adding `filter_secrets: false`, as suggested in #4704 
- Disabling parallel make, as another code that uses Travis CI tried: https://github.com/flux-framework/flux-core/issues/1145

**Comment by BanzaiMan** [comment]
The log appears to be mangled somehow with control characters, so I wouldn't think `joemake` tells us anything important or meaningful. The real error message is just `make: write error`.

Have you tried running debug builds? We don't have access to your code, so it is quite difficult to guess what your issue might be.

**Comment by felker** [comment]
Yes, I have run in debug mode, and I experience the same write errors.

**Comment by BanzaiMan** [comment]
Great news! If you can reproduce the issue in the debug mode, you are in the best position to troubleshoot it further.

**Comment by felker** [comment]
The `make: write error` appears in the middle of the tmate output line in debug mode too. 

To clarify, the errors in the debug mode only occur when using `travis_run_script`, not when running the commands one-by-one in the `script` YAML block. For example, the sequence of tests via our Python driver may look like:

``` yaml
script:                        
  - python run_tests.py serial_test1                                                                                     
  - python run_tests.py mpi_test1                       
  - python run_tests.py serial_test2             
  - python run_tests.py serial_test3
```
The `make: write error` only ever occurs on tests that follow the MPI test. Is there something I should know about how `travis_run_script` processes these commands?

**Comment by felker** [comment]
As explained in my post in #4704 , this macOS issue is not specific to Travis CI.
