### ISSUE TITLE
Build requests created successfully, but nothing happens

### ISSUE THREAD

**Issue by res2k** [travis-ci/travis-ci#8758]
I'm having the problem that I don't get new builds processed for new commits.
Requests(multiple, actually...) are created (see https://travis-ci.org/res2k/shader1/requests or screenshot below), but they're not processed at all (hovering over the circle says "Nothing here").

In the UI I cannot see at all what's happening/wrong/….

![screenshot-2017-11-14 res2k shader1 - travis ci](https://user-images.githubusercontent.com/4117506/32774403-75516b44-c92c-11e7-8290-49d7fc834c24.png)

**Comment by BanzaiMan** [comment]
The configuration file https://github.com/res2k/shader1/blob/d7f96ab86a881e506a925f7a96778952defc6717/.travis.yml has a YAML syntax error. The build should still start, however. (And fail immediately.)

**Comment by res2k** [comment]
Hi,
please be so kind and point the syntax error out for me. Neither travis-lint not yamllint are telling me about it.
But, as you already noted, in the past the syntax errors I produced resulted in a failed build, not a silent no-op, so I'd guess that something else going on.

**Comment by BanzaiMan** [comment]
http://yaml-online-parser.appspot.com/ says:

```
ERROR:

while constructing a mapping
  in "<unicode string>", line 26, column 13:
                <<: *sources
                ^
expected a mapping for merging, but found scalar
  in "<unicode string>", line 12, column 9:
          - ubuntu-toolchain-r-test
            ^
```

However, I see that Psych (Ruby YAML parser) does not have a problem with it.

**Comment by res2k** [comment]
Hmm, whaddayknow, by removing these fancy references it works: https://travis-ci.org/res2k/shader1/builds/305330840
Even though aliases are explicitly mentioned in the Travis Docs as well: https://docs.travis-ci.com/user/build-stages/using-yaml-aliases/ ... so I assumes they'd be supported.
I also tried to manually trigger a build where I essentially pasted the current config into the "Custom config" field, that didn't work either (or at that doesn't work as I assumed it would).

AFAICS references in YAML are a legit feature and the Ruby parser supports them, so it's a bit weird this causes builds to fail. (Maybe different parsers are used in different places or so?)

The worse issue might be that the failures are utterly silent, leaving no clue to what's going wrong. With some more direct feedback I probably could have figured it out myself.

That said, thanks for your assistance!

**Comment by BanzaiMan** [comment]
I think this can be closed.
