### ISSUE TITLE
Encrypting files results in bad decrypt in Travis

### ISSUE THREAD

**Issue by asalom** [travis-ci/travis-ci#8759]
Hi,

I'm trying to encrypt two files, first:
```
travis encrypt-file credentials.json
```

And without commiting, I encrypt a second file:

```
travis encrypt-file secret.json
```

I then add both resulting commands to Travis' `before_install`
```
before_install:
- openssl aes-256-cbc -K $encrypted_aac181f0b50b_key -iv $encrypted_aac181f0b50b_iv -in secret.json.enc -out secret.json -d
- openssl aes-256-cbc -K $encrypted_aac181f0b50b_key -iv $encrypted_aac181f0b50b_iv -in credentials.json.enc -out credentials.json -d
```

Travis then complains with the following error message:
```
openssl aes-256-cbc -K $encrypted_aac181f0b50b_key -iv $encrypted_aac181f0b50b_iv -in secret.json.enc -out secret.json -d
0.03s$ openssl aes-256-cbc -K $encrypted_aac181f0b50b_key -iv $encrypted_aac181f0b50b_iv -in credentials.json.enc -out credentials.json -d
bad decrypt
4185:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/evp/evp_enc.c:330:
```

My tools:
macOS: High Sierra 10.13.1
OpenSSL: LibreSSL 2.2.7
Travis: 1.8.8

EDIT: On travis we are using
```
language: objective-c
osx_image: xcode9.1
```

Any tips what am I doing wrong?

**Comment by BanzaiMan** [comment]
You cannot encrypt multiple files. This is documented in https://docs.travis-ci.com/user/encrypting-files#Encrypting-multiple-files

**Comment by asalom** [comment]
Thanks, I missed that part of the documentation. With a unique tar file is now working

**Comment by cheshirekow** [comment]
In case anyone else stumbles upon this before #678 makes it into a release, an alternate workaround is to execute the `encrypt-file` command from a different directory for each file. The problem appears to be that the travis CLI uses the the hash of current working directory as a "unique string" for each encrypted file. The following, for example, appears to have worked for me:

```
  srcdir=${PWD} tmp_dir=$(mktemp -d -t travis-XXXXXXXXXX) \
    && pushd ${tmp_dir} \
    && travis encrypt-file --com --repo cheshirekow/redacted \
       ${srcdir}/redacted.deploy_key \
       ${srcdir}/redacted.deploy_key.enc \
    && popd && rm -r ${tmp_dir}
```

And I have two different encrypted deploy keys in the same directory.
