### ISSUE TITLE
Deploy a travis-wide Apt-Cacher instance

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#876]
After several iterations discussing installation of large .deb packages (in my case Oracle-XE), @Mezzle on irc proposed that the travis infrastructure be augmented with https://help.ubuntu.com/community/Apt-Cacher-Server .

This seems particularly well suited for travis. For one it will lighten the network load for repeatedly installed packages, especially by complex projects with multiple dependencies. In addition since an apt caching proxy is not a full blown mirror, this would minimize issues of "hosting" publicly-accessible but not freely-redistributable binary .debs.

My own use case - implementing this will allow me to install/configure Oracle-XE in about 20 seconds, as opposed to 7 minutes(!) for download only. Will also effectively resolve https://github.com/travis-ci/travis-ci/issues/689 and https://github.com/travis-ci/travis-cookbooks/issues/87

@joshk, @Mezzle what do we need to do to make this happen?

**Comment by roidrage** [comment]
Closing the issue at this point. While we have an apt cacher instance in place in parts of our infrastructure, there are currently too many infrastructure stacks involved to make this worthwhile to pursue.
