### ISSUE TITLE
Encrypted env variable not visible on PR

### ISSUE THREAD

**Issue by AleshaOleg** [travis-ci/travis-ci#8761]
Hey, in [css-vendor](https://github.com/cssinjs/css-vendor) we today received [PR](https://github.com/cssinjs/css-vendor/pull/32). As mentioned  [here](https://docs.travis-ci.com/user/encryption-keys/), we need to encrypt any env variable (in my case is a password to Browserstack account), and it will be automatically connected to build check. For owner and contributors/collaborators it works properly, but if any another user makes PR this encrypted variable not visible, and our tests not pass. Is it possible to include this var in build received from any user? Thank you!

**Comment by AleshaOleg** [comment]
I found this two PR: https://github.com/travis-ci/travis-ci/issues/6112 and https://github.com/travis-ci/travis-ci/issues/1946. Is still no updates on this?

**Comment by BanzaiMan** [comment]
There is not. I'm closing this as a duplicate.
