### ISSUE TITLE
XQuartz is outdated in xcode8 image

### ISSUE THREAD

**Issue by scpeters** [travis-ci/travis-ci#8762]
I get `brew doctor` errors when using the `xcode8` osx_image saying that XQuartz is outdated:

https://travis-ci.org/osrf/homebrew-simulation/jobs/302221876#L125-L134

~~~
Warning: Your XQuartz (2.7.9) is outdated.
Please install XQuartz 2.7.11 (or delete the current version).
~~~

Let me know if this is a `wontfix` issue so I can adjust my CI.

Thanks!

**Comment by BanzaiMan** [comment]
The Xcode 8 image is unlikely to see further updates, so please update the package according to your needs. Thanks.

**Comment by scpeters** [comment]
thanks!

**Comment by scpeters** [comment]
I just switched to the xcode7.3 image and it has the same version of XQuartz and the same `brew doctor` error:

* https://travis-ci.org/scpeters/homebrew-simulation/jobs/302408251#L176-L182

Is that image also unlikely to see further updates?

**Comment by BanzaiMan** [comment]
Yes.

**Comment by scpeters** [comment]
thanks
