### ISSUE TITLE
fatal:destination path 'firstgit' already exists and is not an empty directory

### ISSUE THREAD

**Issue by SivaVelsamy** [travis-ci/travis-ci#8763]
I got this when I clone.I don't know what is the reason for this.So I need  help!

**Comment by BanzaiMan** [comment]
Probably a duplicate of #2715.

**Comment by SivaVelsamy** [comment]
Thx!Banzaiman...

**Comment by BanzaiMan** [comment]
OK. I'm closing this as a duplicate.
