### ISSUE TITLE
Travis detects branch master for PRs

### ISSUE THREAD

**Issue by felixfbecker** [travis-ci/travis-ci#8767]
Take a look at this build: https://travis-ci.org/felixfbecker/php-language-server/builds/302649313

Travis says it was build on branch master:

![image](https://user-images.githubusercontent.com/10532611/32859160-7ae89d94-ca02-11e7-8d23-0bf23897ee5f.png)

Even though it was a PR (https://github.com/felixfbecker/php-language-server/pull/527) from the branch `no_html_completion` (the PR is not merged yet).

This caused the "release" build stage to run on the PR even though the condition says `if: branch = master`, as suggested in the build stages documentation: https://docs.travis-ci.com/user/build-stages/#Specifying-Stage-Order-and-Conditions

https://github.com/felixfbecker/php-language-server/blob/3cf340148aace899fccace3ab8784f0086116303/.travis.yml#L58-L61

 I noticed it in time to cancel the build, but this looks like a seriously dangerous bug to me.

**Comment by felixfbecker** [comment]
Here's another example: https://travis-ci.org/aaronpowell/ps-nvmw/builds/302670670

![image](https://user-images.githubusercontent.com/10532611/32860085-654519b0-ca05-11e7-804f-d2e798702d0f.png)

**Comment by BanzaiMan** [comment]
PR builds such as these belong to the base branch (the branch against which the PR is opened).

If you want to act on non-PR builds, you should check with the specific condition, namely:

```yaml
if: NOT type IN (pull_request)
```

**Comment by felixfbecker** [comment]
Oh, I did not expect that. I would suggest changing the example in the build stages documentation to something like that then before anyone accidentally deploys from a PR, because I don't think anyone would want to deploy on a PR and the example makes it seem like just `if: branch = master` accomplishes that (given the stage is named "deploy"):

> On the same section you can also specify conditions for stages, like so:
>
> ```yaml
> stages:
>   - compile
>   - test
>   - name: deploy
>     if: branch = master
> ```

Would this work?

```yaml
- name: deploy
  if: branch = master AND type = push AND fork = false
```

**Comment by BanzaiMan** [comment]
That's a very good idea. I believe the edit suggest should work. Do you mind opening a PR with this? (There is a button at the upper right corner of the page.)

Thank you!

**Comment by BanzaiMan** [comment]
I'm closing this in the mean time.
