### ISSUE TITLE
Mistakenly pushed branch has broken production build indicator

### ISSUE THREAD

**Issue by dwsteele** [travis-ci/travis-ci#8768]
I accidentally pushed a branch (https://travis-ci.org/pgbackrest/pgbackrest/builds/294834221?utm_source=github_status&utm_medium=notification) that has the same commit (85b35f30a4a4ea07e) as a release commit in master .

Now the release commit is marked as broken even though it passed originally.  Unfortunately, in the meantime the version of `pip` that ships with Ubuntu 12 (Docker in use here) has gone out of support so it's not possible to get a successful built by restarting.  `pip` is only used to install some test software and is not part of the release.

It would be great if there were a way to delete the build logs for a branch so that accidents like this can be corrected.  Actually, it would be nice to clear out build logs for old dev branches in general.  The pgBackRest project has quite a collection now and they are not really useful.  Only the master and integration builds are of interest for historical purposes.

Not an emergency, but it would be nice to be able to mark that build as passing again.

**Comment by BanzaiMan** [comment]
When you say

> Now the release commit is marked as broken even though it passed originally.

Do you mean that a red "x" appears next to "85b35f3" in https://github.com/pgbackrest/pgbackrest/commits/master?

If so, the only way to "fix" it is to post another status for it, using GitHub's statuses API. See https://developer.github.com/v3/repos/statuses/#create-a-status 
 
https://api.github.com/repos/pgbackrest/pgbackrest/commits/8674a4f7aea3bea2db7e92be599c034170b81706/statuses

**Comment by dwsteele** [comment]
Thank you!  That did the trick.
