### ISSUE TITLE
PRs from one particular contributor don't trigger Travis

### ISSUE THREAD

**Issue by TheToolbox** [travis-ci/travis-ci#8769]
PRs from matrix-israel/openemr to openemr/openemr seem to not be triggering a Travis build. An example can be found [here](https://github.com/openemr/openemr/pull/1223). Is there some subtle group behavior we're not understanding? Insight is much appreciated.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/openemr/openemr/requests show that we detected something fishy about the build requests. Please email us at support@travis-ci.com to resolve the issue.

I'm closing this public issue, since the details could be sensitive and not suitable for public discussion. Thanks.
