### ISSUE TITLE
Ability to delete builds

### ISSUE THREAD

**Issue by roidrage** [travis-ci/travis-ci#877]
For abandonded branches, it'd be nice to be able to delete single builds or even all builds for that particular branch.

**Comment by BanzaiMan** [comment]
Web version of this feature was deployed recently.

![log_removal_button](https://cloud.githubusercontent.com/assets/25666/6158891/11981004-b21d-11e4-95ef-230b27317ea0.png)

https://twitter.com/travisci/status/557932883571392512

**Comment by meatballhat** [comment]
While log deletion is live, build deletion is not, nor is it planned.  I'm reopening this for now :smiley:

**Comment by roidrage** [comment]
Closing this issue for good, as this isn't on the roadmap for the near future.
