### ISSUE TITLE
Presence of string "docker" in `before_install` leads to implicit `sudo: required`

### ISSUE THREAD

**Issue by jcrist** [travis-ci/travis-ci#8770]
This took me forever to track down. We were removing the need for docker in our build matrix (no longer required for testing), but removing all references to docker caused our tests to fail. We tracked the failures down to needing to run in a VM instead of a container, but this debugging process was elongated by some implicit setting changes done by travis masking things:

- Implicit setting of `sudo: required` when the string "docker" is present, even if `sudo: false` was set.
- Implicit setting of `sudo: required` when the docker service is requested, even if `sudo: false` was set.

**Examples:**

- No docker service requested, sudo set to `false`, but string "docker" is in `before_install` (but never run). Sudo implicitly set to true, runs on virtual machine.

  - `travis.yml`: https://github.com/dask/distributed/blob/9eec6d031e0836abdca78ff0d69e6b993d34604f/.travis.yml
  - Test run: https://travis-ci.org/dask/distributed/builds/302834544

- No docker service requested, sudo set to `false`, no presence of string "docker" in `before_install`. Sudo remains false, runs in a container.

  - `travis.yml`: https://github.com/dask/distributed/blob/700c6a5e16911166539d5023afadcc8a225cd505/.travis.yml
  - Test run: https://travis-ci.org/dask/distributed/builds/302838825

---

The solution for us for now is to set `sudo: required` (and figure out why containerized builds fail), but the implicit changing of environment based on the presence of a string in a set of commands was unexpected and significantly lengthened the debugging process.

As a user, I'd expect:

- An error when docker services is requested and sudo isn't required (at setup rather than build time)
- An error when docker is used but the service isn't requested (at build time)

Currently neither of these error, and both implicitly work.

**Comment by BanzaiMan** [comment]
Thanks for the feedback. Would it have been helpful to you to know that this sort of re-routing occurs in the logs? For example, with a message such as:

```
This job is running on a `sudo`-enabled environment because you used `sudo` or `docker` in the section `X`.
```

**Comment by jcrist** [comment]
I'd still prefer the build fail if I explicitly request `sudo: false` and do something that requires `sudo: required`. Any checking on the commands run beforehand to do automagic re-routing can fail in certain cases. For example, if I ran a docker command in a bash script instead of in the yaml directly, the re-routing wouldn't have occurred and the build would have failed.

If the current re-routing behavior is unavoidable though (due to backwards compatibility or something), then logging would certainly have helped, provided it's not below a fold in the logs. Alternatively, perhaps a `strict: true` setting (or some other name) that turns off the re-routing, and defaults to false?

**Comment by rlue** [comment]
I encountered this issue as well. In [my particular case](https://github.com/zammad/zammad/pull/1901), a virtualized build was triggered because of the presence of the string "docker" in the following line:

```yaml
after_success:
  - contrib/travis-ci.org/trigger-docker-build.sh
```

In addition to the behavior suggested by @jcrist, it would be nice if the build routing system differentiated between docker commands (_i.e.,_ strings of the format `docker [--option] COMMAND`) and the simple appearance of the string "docker". Such a check would dramatically reduce (though not eliminate) false positives.

**Comment by Krinkle** [comment]
:shit:

**Comment by rlue** [comment]
bump

**Comment by rlue** [comment]
TIL. I'd be happy to close the issue, but for some reason, I don't see a "close" button in GitHub. :\\

**Comment by jesskie** [comment]
Thank you so much sir,

**Comment by jesskie** [comment]
I think that there is one using my account but I will consul to the
expert.thank u sir.happy holliday
