### ISSUE TITLE
Deploy fails if any one of the builds in the matrix fails

### ISSUE THREAD

**Issue by jroweboy** [travis-ci/travis-ci#8773]
On the open source project that I work on, we have travis set up to deploy builds for mac and linux to github releases, but we also have two other sanity check builds in the matrix, one for checking style and one for checking that it works on older linux distros. Only the mac and linux targets are setup to deploy, and if that build passes, I would expect it to deploy. What seems to happen is the check style build will fail, causing travis to not deploy any of the builds. I can't find anything in the documentation about this, nor any way that I can tell travis to deploy if this particular build in the matrix passed. This is important to the project because we deploy a separate build for user to regression test from the PRs that are under review, and often these PRs will have style issues, but we still want the build to be deployed so that we can have people test.

Is there any way I can work around this issue to get successful builds to deploy even if the other builds in the matrix weren't successful?

Current travis.yml: https://github.com/citra-emu/citra/blob/7ef905ea0f4c5a1af3cac608225ed6891027bd4c/.travis.yml

(Most of the build scripts are factored out into their own folder, but I don't think theres anything of note in them but heres a link to the folder for reference: https://github.com/citra-emu/citra/tree/2284367591e82b836039a0f7803a03252f6291bb/.travis)

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

I checked a few jobs in https://travis-ci.org/citra-emu/citra/builds, but I did not see any deployment failure you described.

**Comment by jroweboy** [comment]
My mistake for not including that url originally. This is an example of a build that the check style fails, and we have no deploy from https://travis-ci.org/citra-emu/citra-canary/builds/302693128

Here is the page that it gets uploaded to: https://github.com/citra-emu/citra-canary/releases There has been a long list of releases from appveyor, and travis is also building the same tags, but for some reason, travis stopped uploading one day and the best I can figure is that the clang format check started failing so it won't deploy.

**Comment by BanzaiMan** [comment]
The configuration file for this build is https://github.com/citra-emu/citra-canary/blob/24a0d179d4cf3d92aca172a95f1c822782a9ca27/.travis.yml. This defines 4 jobs in `matrix.include`, which are independent on their execution. Each job will go through the process, and attempts to run deploy task when the job succeeds (https://github.com/citra-emu/citra-canary/blob/24a0d179d4cf3d92aca172a95f1c822782a9ca27/.travis.yml#L45-L46 says the only condition is `tags: true`). Conditional deployment is documented in https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A.

**Comment by jroweboy** [comment]
Okay. I think I see what the real issue is. Thank you for clarifying that it wasn't the issues with the other builds in the matrix.
