### ISSUE TITLE
apt-get update failing

### ISSUE THREAD

**Issue by jchannon** [travis-ci/travis-ci#8774]
After various build failures on PRs I looked at the travis error which was `The command "sudo apt-get update -qq" failed and exited with 100 during .`, I re-ran the builds many times but it always failed for example - https://travis-ci.org/jchannon/Botwin/builds/303129768

**Comment by christophM** [comment]
Same here: https://travis-ci.org/christophM/xai-book/builds/303126623

**Comment by Shockolate** [comment]
Maybe a resurgence of #7332 ?
[Build](https://travis-ci.org/Shockolate/Liquor-Cabinet/builds/303153192)

**Comment by colinthompson** [comment]
I'm getting it on trusty, too. Looks like the i386 packages have been removed from hhvm's mirror.  Extract of build logs:
```
gpg: requesting key EA312927 from hkp server keyserver.ubuntu.com
gpg: key EA312927: "MongoDB 3.2 Release Signing Key <packaging@mongodb.com>" 1 new signature
gpg: Total number processed: 1
gpg:         new signatures: 1
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 54.230.51.133 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
C# support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry
Installing .NET Core
$ export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
$ export DOTNET_CLI_TELEMETRY_OPTOUT=1
Executing: /tmp/tmp.DEIv2wTeER/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
417A0893
gpg: requesting key 417A0893 from hkp server keyserver.ubuntu.com
gpg: key 417A0893: public key "MS Open Tech <interop@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
5.47sW: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 54.230.51.132 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update -qq" failed and exited with 100 during .
Your build has been stopped.
```

**Comment by kratsg** [comment]
I'm also seeing this as well. Indeed, there are only amd-64 packages on the hhvm mirror.

```
sudo: required
dist: trusty
```


```
$ sudo apt-get -qq update
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 13.33.164.196 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by kylelaverty** [comment]
Also seeing the same issue, when you got to: [http://dl.hhvm.com/ubuntu/dists/trusty/main/](http://dl.hhvm.com/ubuntu/dists/trusty/main/) it looks like the only the 64bit version was built properly.

Trusty should be updated to make use of a TravisCI local store that is synced, maybe once a day. That way it would prevent bad deploys like this and would also greatly reduce the network traffic for TravisCI.

**Comment by jayslife** [comment]
**Getting same error**
Installing .NET Core
$ export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
$ export DOTNET_CLI_TELEMETRY_OPTOUT=1
Executing: /tmp/tmp.H87RuSjBfI/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
417A0893
gpg: requesting key 417A0893 from hkp server keyserver.ubuntu.com
gpg: key 417A0893: public key "MS Open Tech <interop@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
3.58sW: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 13.33.164.241 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update -qq" failed and exited with 100 during .
Your build has been stopped.

**Comment by andypohl** [comment]
On the [Travis-CI Status](https://www.traviscistatus.com/) page, it says they're investigating and you can subscribe to be updated.

**Comment by lae** [comment]
Fix has been pushed (and my builds are working fine now).

**Comment by am-kantox** [comment]
The same happened to me since yesterday, Nov 30, for `rabbitmq-server`:
```
$ sudo apt-get update -qq
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
$ sudo apt-get install -qq rabbitmq-server
E: Unable to correct problems, you have held broken packages.


The command "sudo apt-get install -qq rabbitmq-server" failed and exited with 100 during .
```

**Comment by Mary-Kul** [comment]
Getting same problem
`Starting instance
✓ selected image "travis-ci-garnet-trusty-1512502259-986baf0"
✓ rendered startup script
✓ inserted instance
• sleeping 15s before checking instance insert
• polling for instance insert completion...
✓ instance is ready (16.709s)
Uploading script
• waiting for ssh connectivity........
ssh_key
Installing SSH key from: default repository key
Key fingerprint: 6e:0b:b4:a7:c0:45:0a:a5:54:17:4e:89:3b:7c:04:bc
git.checkout
5.81s$ git clone --depth=50 git@github.ibm.com:hda/drilling_advisor.git hda/drilling_advisor
Cloning into 'hda/drilling_advisor'...
Warning: Permanently added 'github.ibm.com,169.60.70.162' (ECDSA) to the list of known hosts.
remote: Enumerating objects: 3649, done.
remote: Counting objects: 100% (3649/3649), done.
remote: Compressing objects: 100% (1472/1472), done.
remote: Total 3649 (delta 2349), reused 3389 (delta 2166), pack-reused 0
Receiving objects: 100% (3649/3649), 98.55 MiB | 32.74 MiB/s, done.
Resolving deltas: 100% (2349/2349), done.
$ cd hda/drilling_advisor
0.71s$ git fetch origin +refs/pull/190/merge:
remote: Enumerating objects: 120, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 75 (delta 52), reused 64 (delta 45), pack-reused 0
Unpacking objects: 100% (75/75), done.
From github.ibm.com:hda/drilling_advisor
 * branch            refs/pull/190/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
0.01s$ source ~/virtualenv/python3.6/bin/activate
$ python --version
Python 3.6.3
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (python 3.6)
0.10s$ sudo apt-get -y install -qq python-docutils
E: Package 'python-docutils' has no installation candidate
The command "sudo apt-get -y install -qq python-docutils" failed and exited with 100 during .
Your build has been stopped.`

**Comment by nerdhiqedme-zz** [comment]
This issue is also happening to me. Exact same error. Has this issue recurred?

**Comment by Zuba112** [comment]
I am getting the same error as well

**Comment by am-kantox** [comment]
Well, I just moved all my projects to GHA.
