### ISSUE TITLE
Possible root issue - _maybe_ security issue

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#8779]
![image](https://user-images.githubusercontent.com/20478546/32955147-09594c30-cbad-11e7-9198-f52e052a308c.png)
https://travis-ci.org/LolexOrg/Lolex-Tools/jobs/303589421#L6 Line 378

**Comment by BanzaiMan** [comment]
The message comes from a run of `system-info`, and is completely harmless.

**Comment by BanzaiMan** [comment]
Duplicate of #7468.
