### ISSUE TITLE
Setting specific system time in container

### ISSUE THREAD

**Issue by andreif** [travis-ci/travis-ci#8785]
It's possible to configure timezone using $TZ env var, but I wonder if there is a way to set system time without installing custom libraries?

**Comment by BanzaiMan** [comment]
It is not clear to me what you are after. What do you want to accomplish that setting `$TZ` cannot?

**Comment by andreif** [comment]
@BanzaiMan I want run tests exactly at 01:02:03 as system time.

**Comment by BanzaiMan** [comment]
That requires root privilege, and that cannot be done on containers.

**Comment by andreif** [comment]
@BanzaiMan Alright, how do I do it with root?

**Comment by BanzaiMan** [comment]
Something like

```
script:
  - sudo service ntp stop
  - sudo date --set="23 June 2017 01:02:03"
```
