### ISSUE TITLE
Script that depends on branch

### ISSUE THREAD

**Issue by betesh** [travis-ci/travis-ci#879]
I'm looking to do something like this in my .travis.yml file:

before_script:
- 1.0-stable: "cd test/dummy && rake db:schema:load"
- 2.0-stable: "cd spec/dummy && rake db:schema:load"
  script:
- 1.0-stable: "bundle exec rake"
- 2.0-stable: "bundle exec rspec spec"

Alternatively, it could be:

branches:
- 1.0-stable: 
  - before_script: "cd test/dummy && rake db:schema:load"
  -  script: "bundle exec rake"
- 2.0-stable: "cd spec/dummy && rake db:schema:load"
  - before_script: "cd spec/dummy && rake db:schema:load"
  - script: "bundle exec rspec spec"

I know I could write my own bash script that does this and then use:

script: my_own_script.sh

but because the conditional logic involved is "What branch am I on?", I'd be duplicating functionality that travis is already doing when parsing the YML file.  I'd also have to have separate files for script, before_script and after_script, which would all use identical logic and vary only in what commands they run in each condition--basically, a lot of code duplication.

It's possible this feature already exists, but I can't find any docs on it.  So I humbly submit it as a feature request.

**Comment by bennyn** [comment]
Hi guys, sorry for commenting this old isse but I tried to put my commands in an extra shell script which does:
```bash
#!/bin/sh

if [ $TRAVIS_BRANCH == 'develop' ]; then
  se-interpreter test/selenium/interpreter_config.json
fi
```

In my `.travis.yml` I put:

```bash
sudo: true

...

before_script:
  - chmod +x before_script.sh
  - ...
script: ./before_script.sh
```

But Travis complains with:

```bash
$ ./before_script.sh
./before_script.sh: 3: [: selenium-config: unexpected operator
The command "./before_script.sh" exited with 0.`
```

Before I ran my Selenium tests with `script: "se-interpreter test/selenium/interpreter_config.json"`. 

So can you tell me what's wrong there and how I can run my `"se-interpreter test/selenium/interpreter_config.json"` command only when building the `develop` branch?

**Comment by BanzaiMan** [comment]
Try putting the statement directly in the `script` section.

```yaml
script:
  - if [ $TRAVIS_BRANCH = 'develop' ]; se-interpreter test/selenium/interpreter_config.json; fi
```

**Comment by bennyn** [comment]
Thanks for your response! Good to know that you can directly write these commands in the `.travis.yml`. However, this command returns:

```bash
$ if [ $TRAVIS_BRANCH == 'develop' ]; se-interpreter test/selenium/interpreter_config.json; fi
/home/travis/build.sh: eval: line 41: syntax error near unexpected token `fi'
/home/travis/build.sh: eval: line 41: `if [ $TRAVIS_BRANCH == 'develop' ]; se-interpreter test/selenium/interpreter_config.json; fi'
The command "if [ $TRAVIS_BRANCH == 'develop' ]; se-interpreter test/selenium/interpreter_config.json; fi" exited with 1.
```

Will write you on the support channel if I cannot resolve it. :)

But great to see that there are at least 3 different options to run selected commands only on specific branch builds. You should add this to your FAQ if not already there. :smiley:

**Comment by bennyn** [comment]
Ok! Got it working! I checked the little line with [SpellCheck](http://www.shellcheck.net/) and it suggested to do this which works now:

```bash
script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then se-interpreter test/selenium/interpreter_config.json; fi
```

The "then" was missing. ;)

**Comment by doublejosh** [comment]
Worth noting if you have just a few short lines and want to forgo creating a bash scripts you can do a small block like so...

```
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      mkdir deploy;
      cp -r !(deploy|README.md|node_modules|composer.*) deploy/;
      zip -r deploy.zip deploy;
    fi
```

**Comment by toddpi314** [comment]
+1 for @BanzaiMan's response. I do the inline bash condition all the time.

**Comment by mathiasrw** [comment]
> Ok! Got it working! I checked the little line with SpellCheck and it suggested to do this which works now:

> ```yaml
script:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then se-interpreter test/selenium/interpreter_config.json; fi
```

@bennyn - nice one. It might even get more smooth by having only 

```yaml
script:
  - $TRAVIS_BRANCH == "develop" && se-interpreter test/selenium/interpreter_config.json
```

**Comment by michaelahlers** [comment]
In addition to @bennyn and @mathiasrw's suggestions, you may use regular expressions in those conditional statements:

```bash
[[ $TRAVIS_BRANCH =~ pattern ]]
```

To illustrate: in my usual workflow, snapshots should be published only from {{master}} and release maintenance branches (those numbered as <code>v<em>MAJOR</em>.<em>MINOR</em>). To make publishing run only under these conditions:

```yml
after_success:
- "[[ $TRAVIS_BRANCH =~ (master|^v[0-9]+.[0-9]+) ]] && sbt publish"
```

**Comment by AlexeySmolyakov** [comment]
Choose destination directory using $TRAVIS_BRANCH.

`/public` directory, where all assets are compiled.
`$PRODUCTION_DIR`, `$DEVELOP_DIR`, `$SSH_PASSWORD`, `$SSH_LOGIN`, `$HOST` are Environment Variables, set in Travis - More options - Settings.

``` yaml
after_success:
  - '[[ $TRAVIS_BRANCH == "master" ]] && DIR="$PRODUCTION_DIR" || DIR="$DEVELOP_DIR"'
  - sshpass -p "$SSH_PASSWORD" scp -r ./public/* $SSH_LOGIN@$HOST:~/$DIR
```

**Comment by theamorn** [comment]
here's my sample for trials and error for anyone. Who has a hard time to figure it out
- if [[ $TRAVIS_BRANCH =~ (^testing) ]]; then fastlane beta; fi

so any branch that start with `testing/*****` is will be triggered
so if you want to build over feature it will be  

- if [[ $TRAVIS_BRANCH =~ (^feature) ]]; then fastlane beta; fi
so all `feature/****` will be triggered

hope that's help
