### ISSUE TITLE
Pull Requests are not being built

### ISSUE THREAD

**Issue by rfjakob** [travis-ci/travis-ci#8790]
For some reason, Travis stopped building pull requests against https://github.com/rfjakob/gocryptfs .
For example, https://github.com/rfjakob/gocryptfs/pull/164 is not being built. I can't seem to figure out why.

I have read through
https://docs.travis-ci.com/user/pull-requests/#My-Pull-Request-isn%E2%80%99t-being-built
but the pull requests are mergeable, and it seems that the problem exists for 6 months (the last pull requests were built 6 months ago).

### Repo settings:
![image](https://user-images.githubusercontent.com/286847/33116840-93a86f6c-cf66-11e7-9989-c0e149bf1ef9.png)

### The last pull requests that were built were 6 months ago:
![screenshot from 2017-11-22 09-22-20](https://user-images.githubusercontent.com/286847/33116872-b8acae18-cf66-11e7-83aa-1583a5008dc2.png)

### Cron builds work fine:
![screenshot from 2017-11-22 09-30-07](https://user-images.githubusercontent.com/286847/33117189-cb32319c-cf67-11e7-9ab4-56ff52365255.png)

**Comment by BanzaiMan** [comment]
https://travis-ci.org/rfjakob/gocryptfs/requests

Please email us at support@travis-come.com to resolve this issue. Thanks.

**Comment by rfjakob** [comment]
Thanks for the reply! I have emailed support@travis-ci.com just now.
The requests page shows "Abuse detected", so I guess this is why they are not built.

**Comment by BanzaiMan** [comment]
Closing this now. Please follow up with the support ticket. Thanks.
