### ISSUE TITLE
The adapter operation was aborted: HTTP Status Code 500: setting a Private Repo to Public

### ISSUE THREAD

**Issue by marcellodesales** [travis-ci/travis-ci#8794]
I was able to get tests for a `Private` repo to work. However, after I switch to `Public`, the build stopped working. The error in the console is `401 (Unauthorized)`.

# Trigger in the UI: HTTP 500

Trying to re-trigger a build through Travis UI shows 500 error in the console logs.

# Viewing: HTTP 401

Can somebody help? 

# Resolution

Removing the `.travis.yml`  from the repo and adding it again apparently fixed the bug.

**Comment by marcellodesales** [comment]
# Trying the rebuild the last build

* It makes the build fail with the following:

<img width="1025" alt="screen shot 2017-11-22 at 4 32 51 pm" src="https://user-images.githubusercontent.com/131457/33155170-eb5ec13e-cfa2-11e7-9659-92ad535294ec.png">

**Comment by BanzaiMan** [comment]
Public repos are built at https://`travis-ci.org

**Comment by BanzaiMan** [comment]
Rebuild is failing because it was a PR build and the PR has already been merged.

**Comment by marcellodesales** [comment]
@BanzaiMan But I had pushed other PRs using the same branch...

Looks like it's working now.
