### ISSUE TITLE
Travis fails on Visual Studio pre build event

### ISSUE THREAD

**Issue by CliffordSimak** [travis-ci/travis-ci#8797]
Hello!

In my git repo I have a `pre-commit git hook`. The hook runs my unit tests. Also in VS 2017 solution  I have a `pre-build` event: `"../hooks/script.sh"`. 

So, my commit runs `pre-commit hook` -> the hook runs `unit tests `-> unit tests run `msbuild` -> my code   `"../hooks/script.sh"`  execute.

In Travis-CI I check my unit tests again. But my `pre-build event` does not work

```
dotnet test ./testproj-test -c Release -f netcoreapp2.0
/home/travis/build/user/repo/repo-project/repo-project.csproj(9,5): error MSB3073: The command ""../hooks/script.sh"
/home/travis/build/user/repo/repo-project/repo-project.csproj(9,5): error MSB3073: " exited with code 126.
```
I think the problem is in the picture, but in VS only `"blabla"` works. On my computer bash and git execute the work perfect.

![image](https://user-images.githubusercontent.com/1014985/33185305-b7b65ee6-d092-11e7-89b4-b31249a6219f.png)

repo-project.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="&quot;../hooks/script.sh&quot;" />
  </Target>

</Project>
```

dotnet --info
```
OS Name:     Windows
OS Version:  10.0.16299
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\2.0.3\
Version  : 2.0.3
```
git --version
```
git version 2.14.2.windows.3
```

Thank you!

@Joshua-Anderson, @akoeplinger and @nterry

**Comment by CliffordSimak** [comment]
Hello @akoeplinger , thanks for the answer. Yeah, looks great... but...

1. [According to the link](https://msdn.microsoft.com/en-us/library/ms165412.aspx) I have to use quotes. Without it `msbuild` doesnt works and I catch `MSB3073`

2. Local bash execute `../hooks/script.sh` or `"../hooks/script.sh"` fine, so why Travis does not?

In VS I cant use variables like `$(SolutionDir)` because `git` can not to understand it.

**Comment by akoeplinger** [comment]
The link in 1. just suggests adding quotes if the command you're invoking is in a path with spaces, which isn't the case here so it should work.

Travis runs on Linux so it might be an issue specific to Linux, I'd suggest filing an issue at https://github.com/Microsoft/msbuild.

**Comment by CliffordSimak** [comment]
@akoeplinger OK, I think it could be right.  I opened an issue, thanks!

https://github.com/Microsoft/msbuild/issues/2744

**Comment by akoeplinger** [comment]
@CliffordSimak thanks, please close the issue here then.

**Comment by CliffordSimak** [comment]
@akoeplinge OK, I'll close this issue when I solve the problem.

**Comment by akoeplinger** [comment]
@CliffordSimak I'm part of the maintainers of C# on Travis so you can trust me :) there's nothing specific to Travis here.

**Comment by CliffordSimak** [comment]
OK, guys and @akoeplinger . The problem is solved. I just gave the file permission

 `chmod 700 ./hooks/script.sh`

🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by akoeplinger** [comment]
ah, you were probably missing the `execute` permission.
