### ISSUE TITLE
Insane amount of errors in `.travis/job_stages`

### ISSUE THREAD

**Issue by karimsa** [travis-ci/travis-ci#8798]
We are looking to move to Travis Pro at Foko Inc. However, our last few builds have failed out in strange ways.

The build log starts with:

<img width="929" alt="screen shot 2017-11-23 at 3 19 19 pm" src="https://user-images.githubusercontent.com/2664912/33187762-1aad001c-d062-11e7-8d58-06e8c8365274.png">

And finally ends after the `script` stage with:

<img width="838" alt="screen shot 2017-11-23 at 3 19 35 pm" src="https://user-images.githubusercontent.com/2664912/33187765-256abc24-d062-11e7-801c-baf38f59de84.png">

I believe it's due to the complex condition used for deployment.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by karimsa** [comment]
It's a private repo. I can provide the part of the travis config that broke the build though:

```
...
deploy:
  provider: elasticbeanstalk
...
  on:
    repo: FoKo/fokoud
    all_branches: true
    condition: test "$TRAVIS_BRANCH" = "develop" || test "$TARGET_ENV" = "develop"
...
```

It's due to travis injecting the condition in between `[[` and `]]` + the condition is wrapped with `(` and `)`. I was able to fix it by rewriting the conditions in the form of a `[[` condition.

**Comment by BanzaiMan** [comment]
Indeed, this is documented in https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A.
