### ISSUE TITLE
R language evaluated as ruby

### ISSUE THREAD

**Issue by bogind** [travis-ci/travis-ci#8803]
one of my projects keeps failing, i just went into the "view config" on the last job it ran on and saw this:
{
  "language": "ruby",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}

i am writing the code in R and the same travis.yml file is working for me on another project.
this is what is in my travis.yml, it has worked 2 months ago with no issues like this.

language: r

matrix:
    include:
        - os: linux
          sudo: required
        - os: osx
          language: r
          osx_image: xcode8

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by bogind** [comment]
yes, here it is.
https://travis-ci.org/bogind/SIRItoGTFS/builds/307400590?utm_source=email&utm_medium=notification

**Comment by BanzaiMan** [comment]
As the log indicates, https://github.com/bogind/SIRItoGTFS/tree/972c714732c8f610d2534f9092860ee2060128ce does not have `.travis.yml` (though it does have `travis.yml`). Please rename the file.
