### ISSUE TITLE
Suggested packages for R not installed anymore on MacOS with R devel

### ISSUE THREAD

**Issue by phgrosjean** [travis-ci/travis-ci#8805]
I check my R packages on Travis-CI on both Linux and MacOS with R devel (@craigcitro and @jimhester). Under Linux everything runs fine, but on MacOS, suggested packages are not detected and/or installed, and consequently, R CMD check cannot proceed. This happens here, more probably:

$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'

You can see an example at: https://travis-ci.org/SciViews/svMisc/builds/307539350.

**Comment by LiNk-NY** [comment]
Hi Philippe, @phgrosjean
There are known issues with the availability of binaries for R packages under Mac. 
This is not really an issue for Travis. I think the issue should be closed.
Regards,
Marcel
