### ISSUE TITLE
Restoring the cache of /opt/pyenv/versions fails silently

### ISSUE THREAD

**Issue by zspencer** [travis-ci/travis-ci#8806]
I have a library that I am running across multiple python versions using pyenv. I went around the standard python versions matrix declaration because the library uses both ruby and python (and eventually javascript and maybe more)

What I discovered is that even if though the cache is registered and identified as changed `/opt/pyenv/versions` it appears to not restore to `/opt/pyenv/versions`.

This prevents me from caching the installed version of python (which, maybe is a good thing?) but it also means that my builds have another ~2m of sitting there compiling over and over again for no good reason.

I'm not sure if this is intended behavior or not, but I spun for a couple hours trying to figure out why on earth I can't cache my python versions like I can with my ruby versions. See https://github.com/wecohere/informed/pull/6 for an example.

Should it fail fast if I try to cache something that the system refused to let restore to? Or is this a bug where you should be able to restore since it *is* writable by the travisci user?

### An Example

* https://travis-ci.org/wecohere/informed/jobs/307689140#L582-L615 - This is the cache of a build acknowledging that it had made a change to the `opt/pyenv/versions` directory
* https://travis-ci.org/wecohere/informed/jobs/307692034#L461-L473 - The subsequent build appearing to restore the cache
* https://travis-ci.org/wecohere/informed/jobs/307692034#L520-L525 - The subsequent build not finding the cached install and re-downloading and compiling python 3.6.2
* https://travis-ci.org/wecohere/informed/jobs/307692034#L584-L610 - And then attempting to store the changes again

**Comment by BanzaiMan** [comment]
`/opt/pyenv/versions` is a symlink to `/opt/python` and we do not follow symlinks when we create the cache. You'd probably want to cache `/opt/python` instead (though this might be huge, and you might want to be selective).

**Comment by BanzaiMan** [comment]
That we do not follow symbolic links should be documented, and we should not print file names that are not in the archives.

**Comment by zspencer** [comment]
Thank you! That makes a ton of sense! How "Huge" is "too huge?" and is the trade off of a few hundred megs of storage worth the ~8CPU Minutes per build savings (from your perspective)?

**Comment by BanzaiMan** [comment]
"Large" depends on how the cache is used. If it takes longer to download/expand/upload the cache than to just create the cache content, then it is too large.

I've pushed a potential fix. Please try it with:

```yaml
cache:
  branch: no-symlink
  ⋮ # rest
```

**Comment by BanzaiMan** [comment]
My test: https://travis-ci.org/BanzaiMan/travis_production_test/builds/308014133#L461

**Comment by zspencer** [comment]
@BanzaiMan nice! That would have saved me a bunch of trouble :D. Could it also indicate where the symlink points?

**Comment by zspencer** [comment]
Also, as a follow up, caching `/opt/python` [resulted in 30s builds](https://travis-ci.org/wecohere/informed/builds/308281047) across the board on existing python versions, :D :D :D (As opposed to 180s+)

**Comment by BanzaiMan** [comment]
A great suggestion. I've added the symlink's destination.
