### ISSUE TITLE
'./node_modules/.bin' shouldn't be in the PATH

### ISSUE THREAD

**Issue by ankon** [travis-ci/travis-ci#8813]
Our builds seem to have this line executed automatically:
```bash
export PATH=./node_modules/.bin:$PATH
```

This is a potential security issue (see https://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules#comment33532258_9683472 for a discussion), and just for that reason should be removed.

I found it however because it also makes our builds of cordova applications fail: cordova-lib depends on a (horribly outdated version of) npm, and with that PATH setting this version gets used whenever 'npm' is called. Starting with at least NodeJS v8.9.1 we now see this happening when the build starts:
~~~~
$ export PATH=./node_modules/.bin:$PATH
[...]
$ nvm install lts/carbon
v8.9.1 is already installed.
Now using node v8.9.1 (npm v5.5.1)
[... setting up caches ...]
$ node --version
v8.9.1
$ npm --version
module.js:538
    throw err;
    ^

Error: Cannot find module 'dezalgo'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/ORG/REPOSITORY/node_modules/npm/lib/utils/correct-mkdir.js:2:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
$ nvm --version
0.33.6
~~~~

I've removed some lines here, please note that we do cache the `node_modules` directory, so the npm binary is already installed here.

**Comment by BanzaiMan** [comment]
This is a variant of #5092. As explained in https://github.com/travis-ci/travis-ci/issues/5092#issuecomment-265243422, removing it from `$PATH` causes problems in other cases.

**Comment by ankon** [comment]
Thanks for finding that ticket -- I tried and must have missed it. Yes, ultimately this is a duplicate of that ticket.

With that said: It took me a considerable amount of time of finding this behavior, and establishing that it indeed leads to this failure.

1. Would you accept a PR that updates the NodeJS documentation in Travis to highlight this?
2. Could you reply in #5092 about the question on adding a build option for this? Right now I'm trying something like this, but it seems not be good enough:
   ```yaml
   before_install:
   - export PATH=`echo ${PATH} | sed -re 's,(^|:)(./)?node_modules/.bin($|:),\1,'`
    ```
   Having an option + documentation pointing to it would definitely help.

**Comment by ankon** [comment]
FWIW: A "nicer" work-around was in https://github.com/travis-ci/travis-ci/issues/2811#issuecomment-143989823:
```yaml
before_script:
  - PATH=${PATH//:\.\/node_modules\/\.bin/}
```

**Comment by NoxFr** [comment]
Another issue here.
With matrix mutliple builds (one repository, 2 differents projects to build), this PATH modification crash our build (cannot find jest when running test).
I have to use the PATH workaround of @boneskull to fix the build 

Here is an example (cleaned my build)

`matrix:
  include:
    language: java
    jdk: oraclejdk8
    before_script:
      - cd project1
  include:
    language: node_js
    before_install :
      - cd project2
# Remove the './node_modules/.bin:' entry, see https://github.com/travis-ci/travis-ci/issues/8813      -  +- export PATH=`echo ${PATH} | sed -re 's,(^|:)(./)?node_modules/.bin($|:),\1,'`
      - export PATH=`echo ${PATH} | sed -re 's,(^|:)(./)?node_modules/.bin($|:),\1,'`
`

**Comment by OmgImAlexis** [comment]
Still an issue.

**Comment by OmgImAlexis** [comment]
Still an issue.

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate.
