### ISSUE TITLE
Cannot activate repository

### ISSUE THREAD

**Issue by ceefour** [travis-ci/travis-ci#8816]
Repository: https://travis-ci.org/ith1b4-2018/linked-list-2-fun-victors

Trying to activate this repository gives:
"Oh no! There was an error while trying to activate the repository."

![image](https://user-images.githubusercontent.com/24123/33336311-0b02bc26-d4a2-11e7-80bd-26d0aa0df8eb.png)

Specifically, the XHR request is:

```
POST /repo/16421045/activate HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Referer: https://travis-ci.org/ith1b4-2018/linked-list-2-fun-victors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,id;q=0.8,ms;q=0.7
```

Response:

```
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Server: nginx
Date: Tue, 28 Nov 2017 18:06:36 GMT
Content-Type: text/plain
Content-Length: 81
X-Request-Id: f6700064-cb3e-4a0f-86ca-4241e92a5188
Via: 1.1 vegur

Sorry, we experienced an error.

request_id=f6700064-cb3e-4a0f-86ca-4241e92a5188
```

Perhaps useful to know that this is a GitHub Classroom-created repository, but it is a public one.

**Comment by BanzaiMan** [comment]
https://github.com/ith1b4-2018/linked-list-2-fun-victors appears to be a private repository, so you need to use https://travis-ci.com instead.

**Comment by ceefour** [comment]
Sorry about the hassle. :(

I turns out that:

1. I deleted the original repository `ith1b4-2018/linked-list-2-fun-victors`
2. Re-created the repository with a different but similar name `ith1b4-2018/linked-list-2-fun-victors-1`
3. Then added the original repository into Travis CI (i.e. I didn't click Sync Now)

I think the confusing part here is Travis CI just said "Oh no! There was an error" both in UI and in XHR request.

I would've noticed the problem outright had it said "The repository ith1b4-2018/linked-list-2-fun-victors cannot be accessed, please ensure it exists and it's a public repository. If it's a private repository, please use https://travis-ci.com"

If possible, I propose an improvement to the error message to be more helpful as above. That would help other people as well. If accepted, I can create a new issue for 'improvement' if necessary. Thank you.

**Comment by s2t2** [comment]
Also seeing this error message. FYI - My original repo was private, but I deleted it and re-constituted a new public repo at the same address.

**Comment by hendraanggrian** [comment]
I'm also seeing the same error message trying to activate some of my repositories. I can attest that all of my repo are public and always have been public. @s2t2 have you found what is the culprit here?

**Comment by justintime4tea** [comment]
@hendraanggrian I am experiencing this now too. Just started experiencing this tonight with a brand new repo. It's definitely public... I blame Microsoft... but seriously though I would love to use TravisCI again.

**Comment by Schachte** [comment]
I'm getting this as well @justintime4tea

**Comment by justintime4tea** [comment]
I figured out my issue... I was using travis-ci.org still but it looks like they've moved (or are moving) everything over to travis-ci.com even the services for public repos. I was able to get everything working by simply using the travis-ci.com site. I'll wait for the auto-migration of my old repo's but I did get the new repo up and running. Hope this helps someone!

**Comment by justintime4tea** [comment]
@Schachte the CORS error is because TravisCI doesn't add the expected headers in their 500 responses but the service not working doesn't have anything to do related to CORS. Wish there were more helpful messages then "Sorry, we are erroring" though.

**Comment by princiya** [comment]
Yes, switching to travis-ci.com works for me too. Good luck 👍

**Comment by liucimin** [comment]
I'm also seeing the same error message trying to activate some of my repositories. I can attest that all of my repo are public and always have been public. What's wrong with travis-ci.org?

**Comment by justintime4tea** [comment]
You can't use travis-ci.org any more, use travis-ci.com, for new repos anyways.

**Comment by hendraanggrian** [comment]
@justintime4tea pardon my poor learning and zero experience with Travis. But travis.com won't let me activate any repository. There aren't toggle/switch button that are usually there on travis.org.

**Comment by Schachte** [comment]
Yup, good to go now, thanks

**Comment by justintime4tea** [comment]
@hendraanggrian There is a good write up about the migration of all projects to travis-ci.com here:
https://docs.travis-ci.com/user/open-source-on-travis-ci-com/

On travis-ci.com all you need to do is "Add Service" from within your GitHub repository settings and then push to master branch (or whatever else you've configured on TravisCI). You don't need to explicitly "activate" the repo like on tavis-ci.org.

In repo settings look for "Integerations and Services" in the left panel. Then choose "Add Service" near the bottom right of the page. Then type/select Travis. In the configuration settings add your username, token and for domain I just used "notify.travis-ci.org" (without quotes). Push some commits or within Travis launch a custom build.

Hope this helps.

**Comment by liucimin** [comment]
After some time, the travis-ci.org is well.

**Comment by bashleigh** [comment]
I moved a repo from my profile to an organisation. I needed to grant access to that organisation in github with travis before I could successfully add my repo

**Comment by mrdulin** [comment]
same issue. My repo is public since created.

**Comment by terrylinooo** [comment]
Same there. But after I logout and then login again, it is working now.
