### ISSUE TITLE
Providing secure env variable in .travis.yml causes View config to show null

### ISSUE THREAD

**Issue by jefftune** [travis-ci/travis-ci#8818]
Reference: [Environment Variables: Defining encrypted variables in .travis.yml](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml)

I am not seeing that my provided `travis encrypt API_KEY=secret` as appearing within Travis CI View config. I need to work with encrypted "secure" secret.

**.travis.yml** was provided with secure:
```
env:
  global:
    - secure: "... encrypted API_KEY=secret ..."
```

but **Travis CI "View config"** is showing, thereby not setting Travis runtime environment with `API_KEY`:
```
"global_env": null,
```

If I provide **.travis.yml** without secure:
```
env:
  global:
    - API_KEY=secret
```

Then **Travis CI "View config"** is showing the following, thereby is setting Travis runtime environment with `API_KEY`:
```
"global_env": "API_KEY=secret",
```

Thank you

**Comment by BanzaiMan** [comment]
`"global_env": null` most likely means your encryption was faulty.

**Comment by BanzaiMan** [comment]
@jefftune I saw your support ticket. https://github.com/TuneLab/tune-reporting-python/pull/35 is an external PR, and as such, secrets are not decrypted. This is documented in https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions (which is linked from https://docs.travis-ci.com/user/encryption-keys at the top).
