### ISSUE TITLE
Using osx_image: xcode7.3 results in xcode8.3 worker

### ISSUE THREAD

**Issue by ArunTejCh** [travis-ci/travis-ci#8821]
https://travis-ci.org/ArunTejCh/python-driver-wheels/jobs/308855956/config

The worker log info shows that the worker is osx 10.12 xcode 8.3
Worker information
hostname: 9370213d-9bfa-4cb8-8467-9213d300cf2a@29132.wjb-2
version: v3.3.1 https://github.com/travis-ci/worker/tree/1153e5010ef9863bf96264b75fba506109633460
instance: d2a6929c-cdac-4b32-9ac2-dad8442eca5d travis-ci-macos10.12-xcode8.3-1507738863 (via amqp)

**Comment by kennytm** [comment]
The error on rust-lang/rust first appears 8 hours ago (2017-11-29T02:28:11Z) in https://travis-ci.org/rust-lang/rust/builds/308756080. It caused us unable to build LLVM in the CI.

**Comment by solvingj** [comment]
Glad to find this issue already opened.  My team just reported an issue with xcode 7.3 jobs.  Same thing, ends up with an 8.3 worker.  Here's two:

https://travis-ci.org/bincrafters/conan-zstd/jobs/308672736
https://travis-ci.org/bincrafters/conan-libpng/jobs/308788891

**Comment by BanzaiMan** [comment]
As announced in https://blog.travis-ci.com/2017-10-16-a-new-default-os-x-image-is-coming and https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce, 8.3 is now the default. Please update your configurations if you need the older image.

**Comment by iriberri** [comment]
Hi everyone - thanks for reporting this issue and bringing this to our attention.

After the Xcode8.3 image was set as the default image in the last hours, an issue related to how we tag these images internally was causing that jobs configured with `osx_image: xcode7.3` weren't properly routed to Xcode7.3, but to Xcode8.3 (the default) instead.

We have already solved this problem and restarting the affected builds should now run the jobs in the correct image. Could someone please give this a try and confirm that everything is working as expected for you?

That being said, I can also confirm that this only affected Xcode7.3, no other versions have stumbled upon this routing issue.

Thanks again for the report and for your patience, and please, don't hesitate to get in contact with us at support@travis-ci.com if you still see any issues or further questions - we'd be glad to help you further.

**Comment by kennytm** [comment]
@BanzaiMan We [did set](https://github.com/rust-lang/rust/blob/2212da6e98381f57e4f0b8306ba595f9fc999c8b/.travis.yml#L39) `osx_image: xcode7.3` in the matrix, yet xcode8.3 is still chosen.

**Comment by iriberri** [comment]
We've received several confirmations from users through different channels that everything is working as expected now with `xcode7.3`, and therefore I'm closing this issue.

Thank you!
