### ISSUE TITLE
Remove PERL_USE_UNSAFE_INC from Perl Environment

### ISSUE THREAD

**Issue by szabgab** [travis-ci/travis-ci#8822]
The environment variable `PERL_USE_UNSAFE_INC=1` adds "." back to `@INC` in Perl 5.26. This makes the Travis-CI environment less realistic than it could be. In a nutshell: There will be code that works on Travis and fails in a standard installation of Perl 5.26.

I've written a bit more about this here: https://perlmaven.com/removal-of-the-current-directory-from-inc-and-travis

IMHO PERL_USE_UNSAFE_INC should *not* be set by Travis.

**Comment by BanzaiMan** [comment]
How did you determine that this environment variable is set? I ran a quick test and found no evidence. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/309238157#L455-L464 and that `@INC` does not contain `.`, either. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/309238157#L448-L453

**Comment by BanzaiMan** [comment]
5.24 build does include `.` (https://travis-ci.org/BanzaiMan/travis_production_test/jobs/309238158#L451), which is expected, according to your account.

**Comment by szabgab** [comment]
Thanks for checking it. I've just checked again myself. Apparently what turns on that environment variable is "make test" and not Travis.

It took me a while to understand how the ENV setting in .travis.yml could override this, but apparently "make test" or more specifically Test::Harness will only set this ENV var if it does not exist.

https://github.com/Perl-Toolchain-Gang/Test-Harness/blob/62688b0c26fedf4760e809ef90186c47d2307b96/lib/Test/Harness.pm#L150

So it is not something Travis can or should fix. Sorry for the false issue.

**Comment by BanzaiMan** [comment]
@szabgab Thanks for the confirmation. I also suggest appending an addendum to your incorrect blog post or deleting it.

**Comment by szabgab** [comment]
Yes, I've already updated it including an apology to Travis.

**Comment by BanzaiMan** [comment]
Super. Thanks.
