### ISSUE TITLE
Installing azure-cli && xz compressed control.tar files not supported

### ISSUE THREAD

**Issue by carmat88** [travis-ci/travis-ci#8823]
Hallo Travis' Folks! There might be a recently Ubuntu dpkg package bug which seems to be solved, but we are happening to experiencing it in our building. Here is the bug I'm referring to: https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627

And here it is the link to our specific builds:
- 1st attempt:  https://travis-ci.org/kubenow/image/builds/308485578
- 2nd attempt:  https://travis-ci.org/kubenow/image/builds/308969031

We are trying to install the azure-cli which requires the following lines of code:

```
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | \
     sudo tee /etc/apt/sources.list.d/azure-cli.list

sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
sudo apt-get install apt-transport-https
sudo apt-get update && sudo apt-get install azure-cli -y
```
Such dpkg package requires some dependencies which happen to be failing possibly due to the bug beforementioned:

```
Errors were encountered while processing:

 /var/cache/apt/archives/locales_2.25-2_all.deb
 /var/cache/apt/archives/libc-l10n_2.25-2_all.deb
 /var/cache/apt/archives/binutils_2.29.1-9_amd64.deb
 /var/cache/apt/archives/libc6-dev_2.25-2_amd64.deb
 /var/cache/apt/archives/libc-dev-bin_2.25-2_amd64.deb
 /var/cache/apt/archives/linux-libc-dev_4.13.13-1_amd64.deb
 /var/cache/apt/archives/binutils-common_2.29.1-9_amd64.deb
 /var/cache/apt/archives/libbinutils_2.29.1-9_amd64.deb
 /var/cache/apt/archives/binutils-x86-64-linux-gnu_2.29.1-9_amd64.deb
 /var/cache/apt/archives/libc6_2.25-2_amd64.deb

E: Sub-process /usr/bin/dpkg returned an error code (1)
```
The specific error for each one of the above deb files is something like this:

`dpkg-deb: error: archive 'var/cache/apt/archives/one-of-the-above_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up`

Is there anything obvious that we are missing?

Thanks for looking into this! Cheers.

**Comment by BanzaiMan** [comment]
Thanks for the report. If the fix is released, I would guess that you can update `dpkg` before running `apt-get`. Could you try that?

**Comment by carmat88** [comment]
Hey @BanzaiMan ! Sure thing, thank you for getting back and for the hint. I've tried to run `aptitude upgrade dpkg` before running the various apt-get commands mentioned above, but we are keep getting the same error: https://travis-ci.org/kubenow/image/builds/309029407

We are honestly a bit confused as by spawning an Ubuntu Trusty machine in one of our Openstack provider, the procedure for installing the azure-cli works flawlessly by just running apt-get update before installing `apt-transport-https` and `azure-cli`. What do you think? Are we naively overlooking something else? Cheers.

**Comment by BanzaiMan** [comment]
Hmm. I guess I would try reproducing the problem with our Docker image. https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

**Comment by carmat88** [comment]
Hey @BanzaiMan! Apologies for the delayed reply. We are looking into trying to reproduce the glitch with your Docker image. Will follow up once we have an update. Cheers.

**Comment by joepvd** [comment]
Hi @carmat88! The repository has its control file in the xz file format. To process this novelty, one needs to have a newer `dpkg` than is available on Trusty. See https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627 for more info.

**Comment by carmat88** [comment]
Howdy @BanzaiMan! I've managed to move a little step forward, but I would kindly request your insights for trying tackling this down.

After [this incident](https://www.traviscistatus.com/incidents/c1s4dlyxd4lf) has been addressed (and I confirm we are not having any network timeout anymore when the VM tries to connect to PPA repositories at least), I started to address those repositories that have their control file in the xz file format.

As you can see from [this job log](https://travis-ci.org/kubenow/cron/jobs/330282572), the debian packages that are failing are linked to the `addons` that I'd like to be globally installed via the related section in the `.travis.yml` ([here the config](https://travis-ci.org/kubenow/cron/jobs/330282572/config) of the same build). Given that the fail occurs at that point of the build, there is no use to try upgrade dpkg in either the `before_install`, `install` or `before_script` stages.

However I wanted to try something kind of silly, that is adding the package `dpkg` in the list of addons to be globally installed before running the rest of the `.travis.yml`. Well, this seems to have resolved the issue of the xz file format controll ! Though, in [this job log](https://travis-ci.org/kubenow/cron/jobs/330290174) I'm now stuck with the following bizarre error:

```
E: This installation run will require temporarily removing the essential package debconf:amd64 due to a Conflicts/Pre-Depends loop. This is often bad, but if you really want to do it, activate the APT::Force-LoopBreak option.
E: Internal Error, Could not early remove debconf:amd64 (2)
```

Now, I could move the installation of all those addons within one of the aforementioned build stages. But I thought to report it first to you this behavior. Any further insights about the new error above when trying to install/upgrade dpkg via the addons' section?

Thanks and Cheers!

**Comment by BanzaiMan** [comment]
Hello, there. This is curious. Unfortunately, it is something beyond what I consider to be my sphere of knowledge regarding `apt` at this point, so I would suggest turning on the debug feature on this repository, so that you can troubleshoot this further. How does that sound?

**Comment by carmat88** [comment]
Alright, sure. Will keep playing around first and if need be turning on the debug feature. Cheers.

**Comment by geerlingguy** [comment]
I was running into the same issue with installing shellcheck using the debian-sid sources, and then in before_install upgrading Docker.

I had:

```yaml
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
```

And would get a similar issue, but with a pigz install error because it was using the debian unstable repo:

```
$ sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  pigz
The following NEW packages will be installed:
  pigz
The following packages will be upgraded:
  docker-ce
1 upgraded, 1 newly installed, 0 to remove and 917 not upgraded.
Need to get 33.2 MB of archives.
After this operation, 72.1 MB of additional disk space will be used.
Get:1 http://ftp.us.debian.org/debian unstable/main amd64 pigz amd64 2.4-1 [57.8 kB]
Get:2 https://download.docker.com/linux/ubuntu trusty/edge amd64 docker-ce amd64 18.02.0~ce-0~ubuntu [33.1 MB]
Fetched 33.2 MB in 1s (21.1 MB/s)
dpkg-deb: error: archive '/var/cache/apt/archives/pigz_2.4-1_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/pigz_2.4-1_amd64.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
```

(This started happening on February 8, 2018—it had been working fine up until that day.)

Changing the method of installing shellcheck to the following (_after_ upgrading Docker) inside before_install fixed it:

```yaml
before_install:
  ...
  # Install shellcheck.
  - curl -sSL "https://ftp-master.debian.org/keys/archive-key-7.0.asc" | sudo -E apt-key add -
  - echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install -y shellcheck
```
