### ISSUE TITLE
Xcode 7.3 image is not Xcode 7.3 anymore

### ISSUE THREAD

**Issue by mosra** [travis-ci/travis-ci#8824]
Possibly related to https://github.com/travis-ci/travis-ci/issues/8552.

After the recent update that made `xcode8.3` images the default, the `xcode7.3` image is no longer Xcode 7.3. The LLVM version reported is 8.1, which is the same as in the default / `xcode8.3` image. It breaks my iOS 9 build. Related build: https://travis-ci.org/mosra/corrade/jobs/308948718

> Apple LLVM version 8.1.0 (clang-802.0.42)
> Target: x86_64-apple-darwin16.7.0

Correct reported version should be the following: https://travis-ci.org/mosra/magnum/jobs/308437119

> Apple LLVM version 7.3.0 (clang-703.0.31)
> Target: x86_64-apple-darwin15.6.0

My guess is that there was some really bad mixup of macOS images.

Thank you for looking into this.

**Comment by BanzaiMan** [comment]
Probably a duplicate of #8821. Please restart the affected jobs and report the results. Thanks.

**Comment by mosra** [comment]
Okay, after waiting for the queue to get through, with the recent builds it's also fixed for me. Closing this then. Thank you and sorry for the duplicate.
