### ISSUE TITLE
The default branch of Rakudo Perl 6 is no longer called `nom`

### ISSUE THREAD

**Issue by raiph** [travis-ci/travis-ci#8825]
https://docs.travis-ci.com/user/languages/perl6/#Default-Perl-6-Version says

> If you leave the perl6 key out of your .travis.yml, Travis CI will build Rakudo Perl 6 from the latest commit from the project’s `nom` branch.

http://rakudo.org/2017/10/27/main-development-branch-renamed-from-nom-to-master/ says:

> we renamed our unusually-named main development branch from `nom` to the more traditional name `master`

**Comment by raiph** [comment]
^^ @paultcochrane @hoelzro @tony-o

**Comment by paultcochrane** [comment]
@raiph: have submitted a patch to fix this issue: https://github.com/travis-ci/docs-travis-ci-com/pull/1574.

**Comment by raiph** [comment]
@paultcochrane @BanzaiMan Thanks. :)
