### ISSUE TITLE
Get latest build for pull request using API

### ISSUE THREAD

**Issue by dlmr** [travis-ci/travis-ci#8827]
Hi!

I'm wondering if it's possible to get the latest build for a pull request. I have been looking at the documentation for version 3 of the API and I can't find a way to do it, is there a way?

The API I want would look something like this.
```
/repo/{repository.slug}/builds?pull_request_number=12
```
[But this is not supported according to the docs](https://developer.travis-ci.com/resource/builds#find) and the API itself is answering with `query parameter pull_request_number not safelisted, ignored`.

The specific scenario I need this for is that I want to be able to restart the latest build for a PR using the API without needing to potentially fetch all builds and filter on the result.

**Comment by BanzaiMan** [comment]
https://developer.travis-ci.org/resource/builds#Builds use query parameter `event_type=pull_request`.

**Comment by dlmr** [comment]
Thanks for the answer but that does not give me a specific pull request though just build triggered as `pull_requests` right? I would like to get all build for a specific pull request, like #12.

**Comment by BanzaiMan** [comment]
Each build in the list contains the field `pull_request_number`, so filter as you need.

**Comment by dlmr** [comment]
I was hoping that I would be able to avoid potentially fetching all builds to get my PR but that seems to not be possible unfortunately, meaning that I might need to fetch 1000s of builds before I find the right one. 

If possible I would like to request this as a feature for a new version of the API if possible, it would greatly allow me to optimize the request I now need to perform.

**Comment by BanzaiMan** [comment]
You can easily overcome that with `sort_by`.

For example, you can list the 100 pull request builds that finished most recently with

    https://api.travis-ci.org/repo/4351/builds?event_type=pull_request&sort_by=finished_at:desc

(with appropriate headers, of course). If you have more than 100 pull requests to consider, `@pagination.next` should tell you what to query next.

**Comment by BanzaiMan** [comment]
Unless you have hundreds of PRs, pagination would not come into play. 

Can I close this?

**Comment by dlmr** [comment]
Thanks for the help! 👍 

While the solution you say will work in most cases I feel like it could be easier by enabling the use of `pull_request_number` as a GET parameter. Please add this as a feature requests if possible. 🙂

**Comment by dlmr** [comment]
I should also note that getting build using `event_type=pull_request` does not mean that I get unique pull requests, meaning that I a few active PRs can fill all the first 100 slots meaning that pagination can easily get into play and the need to fetch a lot of builds.

**Comment by tmkasun** [comment]
I think iterating though all the pull requests to find the required build is inefficient in both ends (for the user and Travis API gateway as well), I too think that it's better if you can expose an API resource that we can pass the required pull request number and repo details and get the build details.

**Comment by tmkasun** [comment]
I tried both V2 and V3 travis APIs but couldn't get the required information, V3 gives no results 

V3 request
```
curl -kv https://api.travis-ci.org/repos/1961681/builds\?event_type=pull_request -H "Travis-API-Version: 3" -H "Authorization: token MY_TOKEN"
```

response
```
{
  "@type": "error",
  "error_type": "not_found",
  "error_message": "resource not found (or insufficient access)"
}
```


V2 request

```
curl -kv https://api.travis-ci.org/repos/wso2/carbon-apimgt/builds\?event_type=pull_request
```

response
```
[
    {
        "id": 569655024,
        "repository_id": 1961681,
        "number": "8607",
        "state": "finished",
        "result": 0,
        "started_at": "2019-08-09T04:47:35Z",
        "finished_at": "2019-08-09T05:43:22Z",
        "duration": 3347,
        "commit": "b3604107ebc16168d79184073705911449825f23",
        "branch": "master",
        "message": "Add comment to travis config regarding the usage of nvm",
        "event_type": "pull_request"
    },
    .
    .
    .
    .
    .
    .
]
```

but it doesn't have the pull request number in the results

My requirement is , Get the travis build information for a particular pull request ID

can you please help me on this

**Comment by hasufell** [comment]
Same here, bad documentation, bad error messages.
