### ISSUE TITLE
OSX: pip command not found

### ISSUE THREAD

**Issue by gpotter2** [travis-ci/travis-ci#8829]
Hello !
Since today, we're getting random "Pip command not found" during our python builds on OSX:

Failing build example: 
https://travis-ci.org/secdev/scapy/jobs/309062611#L47
https://travis-ci.org/secdev/scapy/jobs/309081835#L53
Config of this build:
```
        - os: osx
          language: generic
```
Install file (where it fails): https://github.com/secdev/scapy/blob/master/.travis/install.sh
.travis.yml: https://github.com/secdev/scapy/blob/master/.travis.yml

Have the API been update ? Do we need to do anything ?

Thanks a lot for any support !

**Comment by BanzaiMan** [comment]
Please note that we don't support Python builds on our Mac images. If you need `pip`, on `language: generic` builds, you are responsible for providing it.

**Comment by ArunTejCh** [comment]
The new osx default 10.12 xcode8.3 has different packages compared to the old default xcode7.3. I was facing the same issue. I switch back to the older image `osx_image: xcode7.3` to get it working.

**Comment by gpotter2** [comment]
@BanzaiMan Thanks or clarifying !
This may be closed

**Comment by pat-s** [comment]
On `xcode8.3` you need to use either `pip2` or `pip3`

**Comment by lurch** [comment]
I can confirm @pat-s 's comment - I was able to fix our Mac OS Travis builds (which had been working fine up until last week) by changing `pip` to `pip2` for OSX builds https://github.com/resin-io/etcher/pull/1897  Thanks @pat-s !

@BanzaiMan Perhaps this nugget of golden info could be added to https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce ?
