### ISSUE TITLE
Android: Connection refused to services.gradle.org

### ISSUE THREAD

**Issue by billthefarmer** [travis-ci/travis-ci#8833]
I have been getting sporadic build failures for some time due to network problems downloading dependencies. This morning (30/11/2017) I don't seem to be able to get any successful android builds.
```shell
$ ./gradlew build
Downloading https://services.gradle.org/distributions/gradle-2.14.1-bin.zip
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
```

**Comment by iriberri** [comment]
Hi @billthefarmer,

thanks for reporting this issue and sorry for the troubles.

I believe these connectivity errors are related to an incident that  affected our infrastructure from, approximately, 9:20 to 10:25 AM (UTC time) and  should be solved now: https://www.traviscistatus.com/incidents/mw30zl8rbr10

Could you please try restarting your affected builds and confirm if everything is working for you now? Thank you!

**Comment by billthefarmer** [comment]
OK thank you it's now working
