### ISSUE TITLE
installing .net core failed

### ISSUE THREAD

**Issue by iirsyad** [travis-ci/travis-ci#8839]
@joshua-anderson @akoeplinger @nterry

Hello, I tried to build travis for my aws lambda project.. However it has issue when installing .net core
The error is attached  below.  I did build 2 weeks ago, and had no issue with similar project.  The only I did was changing the project code recently.. I didn't make any changing to travis yml or anything compared with 2 weeks ago when it was succesful..

Here is my travis.yml config:

language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
**install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
script:**    -------- i tried to add this when the first few attempts failed,   but made no difference..
  - ./build.sh --quiet verify
branches:
  only:
    - master
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh
notifications:
  email:
    on_success: never
    on_failure: always

------ Error
Installing .NET Core
$ export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
$ export DOTNET_CLI_TELEMETRY_OPTOUT=1
Executing: /tmp/tmp.GbBlsEKuJ2/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
BE1229CF
gpg: requesting key BE1229CF from hkp server keyserver.ubuntu.com
gpg: key BE1229CF: public key "Microsoft (Release signing) <gpgsecurity@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
3.21sW: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
0.39sE: Package 'dotnet-[secure]-1.0.1' has no installation candidate
The command "sudo apt-get install -qq dotnet-[secure]-1.0.1" failed and exited with 100 during .

**Comment by akoeplinger** [comment]
We had to switch to a new package repository from MS which no longer contains 1.0.1. 

Please use `dotnet: 1.1.5` instead which is currently the latest 1.x version.

**Comment by iirsyad** [comment]
yes.. it fixed it..

Thanks a lot
