### ISSUE TITLE
PTrace tools not working anymore on container based builds

### ISSUE THREAD

**Issue by Lectem** [travis-ci/travis-ci#8840]
My project uses address-sanitizer / leak-sanitizer, and it was working fine yersteday.
A build was triggered this morning and now addess-sanitizer fails to start ptrace.

According to several posts found on the web, the docker image needs `--cap-add=SYS_PTRACE` and perhaps even `--security-opt="apparmor=unconfined"`.

Did any changes happen on the trusty configuration ?
Running fully virtualized with `sudo: required`makes my build work again, but it is way slower.

It would be nice to be somehow notified of such changes to the configurations, or at least have a patch note easily accessible....

With all the same commit :

Built a few days ago : 
https://travis-ci.org/Lectem/Worldstone/jobs/307866822

Today, same .travis.yml (failing) :
https://travis-ci.org/Lectem/Worldstone/jobs/309686521

Today, same .travis.yml except using `sudo:required` (works):
https://travis-ci.org/Lectem/Worldstone/jobs/309691422

**Comment by Lectem** [comment]
Probably linked to #8836

**Comment by mapsam** [comment]
We're also seeing this over at https://github.com/mapbox/node-cpp-skel/issues/93

**Comment by BanzaiMan** [comment]
Please try restarting the affected jobs. #8836 has been resolved.

**Comment by mapsam** [comment]
Jobs are 🍏 again. Thank you @BanzaiMan and @Lectem! 🙏

**Comment by BanzaiMan** [comment]
Thanks for the confirmation. I'm closing this now.
