### ISSUE TITLE
PHP 7.2 still uses RC build

### ISSUE THREAD

**Issue by brendt** [travis-ci/travis-ci#8845]
When configuring PHP 7.2 like so:

```yaml
php:
  - 7.0
  - 7.1
  - 7.2
```

The RC6 build is still used: 

```
$ php --version
PHP 7.2.0RC6 (cli) (built: Nov 14 2017 03:20:47) ( ZTS )
```

An example can be found here: https://travis-ci.org/spatie/laravel-binary-uuid/jobs/309911937

**Comment by BanzaiMan** [comment]
We will revisit this and #8701 when https://github.com/php-build/php-build/pull/488 is merged.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/php-src-builder/builds/310545935 built 7.2.0 release with redis ext 3.1.4.
