### ISSUE TITLE
Conditional in stage doesn't seem to work

### ISSUE THREAD

**Issue by filipesilva** [travis-ci/travis-ci#8846]
Hi,

Our CI was using `before_script: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi` to prevent a few jobs from running in PRs.

I tried to change all optional jobs to a stage called `optional` and add `if: branch = master` to it, as listed in the docs (https://docs.travis-ci.com/user/conditional-builds-stages-jobs/). 

The whole optional stage is still running in my PR though: https://github.com/angular/angular-cli/pull/8707.

I understand this might be a matter of user error but the config change seems pretty straightforward. I also tried adding the conditional in the job itself, but it didn't seem to make a difference.

Thanks for your time.

**Comment by BanzaiMan** [comment]
`branch = master` still runs the PR builds if the said PRs' base branch is `master`. If you want to skip the PRs, you need more; e.g., 

```yaml
if: (NOT type IN (pull_request)) AND (branch = master)
```

See https://github.com/travis-ci/travis-build/blob/97c4a12f8657f7fe9e25d491ad2d8b5feaf2dcb5/.travis.yml#L35-L40

**Comment by filipesilva** [comment]
Oh I didn't know that, thanks for making it clear 👍

**Comment by filipesilva** [comment]
Also thanks for being super quick ^^
