### ISSUE TITLE
Specific Mac build never starts

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [travis-ci/travis-ci#8848]
Hi,
The following Mac build never started : https://travis-ci.org/RICCIARDI-Adrien/Strage/jobs/309720052 (it always errored with "Automatic restarts limited: Please try restarting this job later or contact support@travis-ci.com." message).
However, this build can't fail because the previous one worked and the only changes are in README.md.
It's not important for me (following build works), but there might be a Travis bug related to this behavior.

**Comment by BanzaiMan** [comment]
Could you try restarting now?

**Comment by RICCIARDI-Adrien** [comment]
It worked !
