### ISSUE TITLE
mac builds won't start

### ISSUE THREAD

**Issue by amalfra** [travis-ci/travis-ci#8850]
I am also facing issues with mac builds. It never gets into processing: https://travis-ci.org/amalfra/server-stats. cancelled few builds which were in queue since yesterday morning:https://travis-ci.org/amalfra/recorder, https://travis-ci.org/amalfra/etag.

Also getting these errors: https://travis-ci.org/amalfra/etag/jobs/310408257
```
go test -v
# testmain
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x1d9482fb40 pc=0xf47b]

```

**Comment by BanzaiMan** [comment]
It may take a while, but Mac builds should be processed in time.

**Comment by amalfra** [comment]
@BanzaiMan thanks for the update. Any idea why the fatal error is happening: https://travis-ci.org/amalfra/maildir/jobs/310535574 ? It only for go 1.6

**Comment by BanzaiMan** [comment]
Signal 0xb is segmentation fault. I'd think it's bad binary file somewhere. I don't know enough about Go to comment much more than that.

**Comment by amalfra** [comment]
hmm, the build tasks I am running will only run the tests. Don't think it's related to my code as it doesn't fail in any other go versions and works with go 1.6 in my local too. Seems like something with travis build runner

logs from https://travis-ci.org/amalfra/maildir/jobs/310535574:
```
	/usr/local/go/src/cmd/compile/main.go:32 +0x395 fp=0xc8200cbf40 sp=0xc8200cbe68
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc8200cbf90 sp=0xc8200cbf40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200cbf98 sp=0xc8200cbf90
FAIL	github.com/amalfra/maildir [build failed]
# github.com/amalfra/maildir/lib
runtime: empty check fails b.log[0]= 2620120025824255113 b.log[1]= 2155007762240194584 b.log[2]= 121813249476790225 b.log[3]= 841642664423260160
fatal error: workbuf is not empty
goroutine 5 [running]:
runtime.throw(0x47a130, 0x14)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc82002be58 sp=0xc82002be40
runtime.(*workbuf).checkempty(0x181480)
	/usr/local/go/src/runtime/mgcwork.go:330 +0x153 fp=0xc82002be90 sp=0xc82002be58
runtime.getempty(0x67, 0x0)
	/usr/local/go/src/runtime/mgcwork.go:343 +0x55 fp=0xc82002bec0 sp=0xc82002be90
runtime.(*gcWork).init(0xc820023220)
	/usr/local/go/src/runtime/mgcwork.go:100 +0x53 fp=0xc82002bed8 sp=0xc82002bec0
runtime.(*gcWork).tryGet(0xc820023220, 0x1)
	/usr/local/go/src/runtime/mgcwork.go:141 +0x38 fp=0xc82002bf08 sp=0xc82002bed8
runtime.gcDrain(0xc820023220, 0x5)
	/usr/local/go/src/runtime/mgcmark.go:833 +0x22a fp=0xc82002bf40 sp=0xc82002bf08
runtime.gcBgMarkWorker(0xc820022000)
	/usr/local/go/src/runtime/mgc.go:1435 +0x583 fp=0xc82002bfb8 sp=0xc82002bf40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82002bfc0 sp=0xc82002bfb8
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1330 +0x92
goroutine 1 [GC assist wait]:
cmd/compile/internal/gc.Prog(0xf, 0xc820434b40)
	/usr/local/go/src/cmd/compile/internal/gc/gsubr.go:117 +0x58
cmd/compile/internal/amd64.gins(0xf, 0x0, 0x0, 0xc8209d8240)
	/usr/local/go/src/cmd/compile/internal/amd64/gsubr.go:636 +0xf6
cmd/compile/internal/gc.Ginscall(0xc820434b40, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:2383 +0x1d8
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:495 +0xc78
cmd/compile/internal/gc.funccompile(0xc820515320)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1450 +0x1c0
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:472 +0x2116
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	/usr/local/go/src/cmd/compile/main.go:32 +0x395
FAIL	github.com/amalfra/maildir/lib [build failed]
make: *** [test] Error 2
The command "make build" exited with 2.
Done. Your build exited with 1.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found
```

**Comment by stgraber** [comment]
We've been seeing similar behavior (go segfaults) on OSX over the past 2-3 days with LXD.
https://travis-ci.org/lxc/lxd

**Comment by amalfra** [comment]
@stgraber looks like some issue with travis. I am not an expert in go but from the error logs it definitely is not coming from my code 
```
runtime: empty check fails b.log[0]= 2620120025824255113 b.log[1]= 2155007762240194584 b.log[2]= 121813249476790225 b.log[3]= 841642664423260160
fatal error: workbuf is not empty
```
and it works in all other go versions except 1.6

**Comment by BanzaiMan** [comment]
The `go` problem should be treated in a different ticket. Also, please try reproducing the error with a Docker image as described in https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image.

**Comment by amalfra** [comment]
@BanzaiMan I tried with docker image as mentioned in article. But the go version in the image is 1.7.4. I am getting the error only with go version 1.6. How can I run using 1.6?

**Comment by BanzaiMan** [comment]
@amalfra https://travis-ci.org/amalfra/etag/jobs/310408257#L36 shows you how. And as I indicated before, please refrain from overloading this issue with unrelated issues. Thanks.
