### ISSUE TITLE
Mono Latest: Casing in .csproj files no longer resolved

### ISSUE THREAD

**Issue by leezer3** [travis-ci/travis-ci#8851]
This has had me chasing for a couple of hours, but appears to be a regression in the Mono-latest worker.
Take the following (technically incorrect) csproj entry:
```
<Reference Include="System.XML" />
```
Prior to ~Friday, this was correctly resolved to the following:
```
<Reference Include="System.Xml" />
```

This no longer appears to be happening, and instead this is failing to resolve.
Branch build where I first noticed this one:
https://travis-ci.org/leezer3/OpenBVE/builds/310068659

This originally failed on Friday sometime, and has no changes from the mainline branch which could have caused this.
I first restarted this morning to check that it wasn't an intermittant Travis error, no dice.

Successful build:
https://travis-ci.org/leezer3/OpenBVE/builds/310462004
Changes required:
https://github.com/leezer3/OpenBVE/pull/141/commits/8ca940e28f742c2be2599982a66e08e8a0e8f4ad

@joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
@leezer3 sorry for the late reply. From what I can see in your test logs the builds used the exact same Mono 5.4.1.6 in both builds so it'd be very weird to have different behavior.

I compared https://travis-ci.org/leezer3/OpenBVE/jobs/310068671 to https://travis-ci.org/leezer3/OpenBVE/jobs/310462010.

Do you still see the issue?

**Comment by leezer3** [comment]
Not sure, sorry.
Differing xbuild versions?

I corrected the error & didn't think about it again :)
Can try a basic test repo if you want.

**Comment by akoeplinger** [comment]
I diffed the install log and the installed package versions are exactly the same so I literally don't know how this is possible. It should have been broken all the time :)

**Comment by akoeplinger** [comment]
If you have time and are curious you can certainly try to reproduce it, otherwise we should probably just close it as it should have been failing all along (unless you do hacks like setting MONO_IOMAP).
