### ISSUE TITLE
Problem to install Python in osx

### ISSUE THREAD

**Issue by EvandroLG** [travis-ci/travis-ci#8855]
I've been running my tests over linux and osx.
In linux it's working great, but in osx the job couldn't install python. It looks like there's a problem with the file downloaded from amazon.

```sh
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.12/x86_64/python-2.7.tar.bz2
$ sudo tar xjf python-2.7.tar.bz2 --directory /
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
The command "sudo tar xjf python-2.7.tar.bz2 --directory /" failed and exited with 1 during .
```

- https://travis-ci.org/EvandroLG/pegasus.lua/jobs/310993142

**Comment by BanzaiMan** [comment]
Currently we do not support `language: python` on the Mac. See #2312.
