### ISSUE TITLE
PHP 7.2 and libsodium

### ISSUE THREAD

**Issue by Adrien-H** [travis-ci/travis-ci#8863]
I am currently deploying a Symfony 4 application, which uses the `Argon2i` algorithm for password hashing. PHP 7.2 natively implements the [libsodium](https://wiki.php.net/rfc/libsodium) library. Of course, PHP 7.2 is mandatory in this build and everything is fine on my locale machine with 7.2.0. Application running, tests OK, etc.

But the build fails while deploying.

I have this in my Travis file:
```yaml
# .travis.yml
language: php
php:
  - '7.2'
```

Here is the part of the build logs where PHP is being successfuly installed:
```bash
$ phpenv global 7.2 2>/dev/null
7.2 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-7.2.tar.bz2
12.26s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
0.01s
0.02s$ phpenv global 7.2
0.60s$ composer self-update
You are already using composer version 1.5.5 (stable channel).
$ php --version
PHP 7.2.0 (cli) (built: Dec  2 2017 17:12:55) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0-dev, Copyright (c) 2002-2017, by Derick Rethans
```

But after the composer install, the build fails with this message:
```bash
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In SecurityExtension.php line 509:
!!                                                                                 
!!    Argon2i algorithm is not supported. Please install the libsodium extension   
!!    or upgrade to PHP 7.2+.                                                      
!!                                                                                 
!!  
!!  
The command "composer install" failed and exited with 1 during .
Your build has been stopped.
```

The message from Symfony is pretty clear, I already saw it while testing with PHP 7.1. But it should work with 7.2, I cannot come to understand what is happening.

Any idea?

**Comment by BanzaiMan** [comment]
Is it a compile-time configuration? Or is it supposed to be enabled by default?

**Comment by Adrien-H** [comment]
I was locally using a pre-configured PHP, so to be sure I just compiled PHP 7.2 from sources.

```bash
$ ./php -v
PHP 7.2.0 (cli) (built: Dec  6 2017 15:26:29) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```
Then I tryed to use the `argon2i` algorithm such as described in official [docs](http://php.net/manual/fr/function.password-hash.php):
```bash
$ ./php -r 'echo password_hash("test", PASSWORD_ARGON2I) . "\n";'
Warning: Use of undefined constant PASSWORD_ARGON2I - assumed 'PASSWORD_ARGON2I' (this will throw an Error in a future version of PHP) in Command line code on line 1

Warning: password_hash() expects parameter 2 to be integer, string given in Command line code on line 1
```
While not having any problem with BCRYPT:
```bash
$ ./php -r 'echo password_hash("test", PASSWORD_BCRYPT) . "\n";'
$2y$10$wsWe3BhyzenVqDs6JV/fPOB0XKh0oTuGdrgLp61MnUPzOUdw4jZey
```
This is strange. I would have expected this algorithm to be part of the default PHP 7.2 build, just as other hash algorithms. And nothing seems to indicate the opposite in the docs. I'll investigate. Maybe I understood something wrong.

Anyway, Travis does not seem to be the problem, so the issue can be closed. (:

**Comment by BanzaiMan** [comment]
For the record, configuration options used for compiling `7.2.0` can be found here: https://travis-ci.org/travis-ci/php-src-builder/jobs/310545936#L631

**Comment by mpiot** [comment]
It appear it's an option, we need to compile PHP with: `https://wiki.php.net/rfc/argon2_password_hash` (sources: https://wiki.php.net/rfc/argon2_password_hash)

**Comment by Adrien-H** [comment]
In case of Symfony 4... I did not try yet and intend to let you know when done, but for now I guess the problem can be skirted by using a "travis" environment extending "test" and defining:
```yaml
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            # algorithm: 'argon2i'
            algorithm: 'bcrypt'
```
This would get my DataFixtures work (just using `Bcrypt` instead of `Argon2` is no big deal for tests purposes). This is however a plaster and won't get the job done for everyone.

I agree with @mpiot about the need of being able to configure PHP build. Is there any way?

**Comment by mpiot** [comment]
An idea is to use the method mensionned in https://symfony.com/blog/new-in-symfony-3-4-argon2i-password-hasher, by using the libsodium-php library, but just in Travis:

      before_install:
          # Fix Argon2i password hasher in TravisCi PHP version
          - composer require paragonie/sodium_compat

Maybe it works well :-)

**Comment by Adrien-H** [comment]
Better solution than mine, indeed. (:

**Comment by mpiot** [comment]
Because Symfony has been updated, the previous solution no longer works, then I choose to directly add the libsodium extension with PECL, but it's a bit complicated, because the Travis Image is an Ubuntu 14.04 and don't embed libsodium-dev.

We must download sources, compile it, then compile with pecl the extension, and enable it. It works well, but it take a long time.

    before_install:
    # Manually compile the libsodium library
  - sudo apt-get update -qq
  - sudo apt-get install build-essential git -y
  - git clone -b stable https://github.com/jedisct1/libsodium.git
  - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..

**Comment by mpiot** [comment]
Because Symfony has been updated, the previous solution no longer works, then I choose to directly add the libsodium extension with PECL, but it's a bit complicated, because the Travis Image is an Ubuntu 14.04 and don't embed libsodium-dev.

We must download sources, compile it, then compile with pecl the extension, and enable it. It works well, but it take a long time.

    before_install:
        # Manually compile the libsodium library
        sudo apt-get update -qq
        sudo apt-get install build-essential git -y
        git clone -b stable https://github.com/jedisct1/libsodium.git
        cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..

**Comment by mpiot** [comment]
Because Symfony has been updated, the previous solution no longer works, then I choose to directly add the libsodium extension with PECL, but it's a bit complicated, because the Travis Image is an Ubuntu 14.04 and don't embed libsodium-dev.

We must download sources, compile it, then compile with pecl the extension, and enable it. It works well, but it take a long time.

    before_install:
      # Manually compile the libsodium library
      - sudo apt-get update -qq
      - sudo apt-get install build-essential git -y
      - git clone -b stable https://github.com/jedisct1/libsodium.git
      - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
      - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
      - composer self-update

    install:
      # Manually install libsodium, because the TravicCi image doesn't provide PHP7.2 with libsodium
      - pecl install libsodium
      - echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

**Comment by BanzaiMan** [comment]
You don't need to run `apt-get update` nor `apt-get install`, as those packages should be present on the image.

Since the run-time configuration seems possible, can we close this issue at this time?

**Comment by Adrien-H** [comment]
Having PHP 7.2 compiled with the core libsodium would be a better solution than having to install the PECL extension, which takes some time. But this solution gets the job done for our needs, so I guess the issue an be closed for now. (:

**Comment by BanzaiMan** [comment]
How long does it take to compile?

**Comment by Adrien-H** [comment]
```yaml
before_install:
  - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
install:
  - pecl install libsodium
  - echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
```
I just stopwatched, this part takes about 1'30''.

**Comment by Nenglish7** [comment]
Argon2i has to be enabled during build, `Add Argon2i (v1.3) support in the next PHP 7.x (7.2) via –with-password-argon2.`
https://wiki.php.net/rfc/argon2_password_hash

**Comment by mpiot** [comment]
Yes, but apparently they only use [one file](https://github.com/travis-ci/php-src-builder) to configure PHP compilation options, and this file is the same for all versions of PHP. If we add the option in it, PHP <7.2 will bug when compiling (I suppose, because the option doen't exists for them).

So for the moment, we propose an alternative solution, but it is certain, that it would be better to have a version of PHP compiled with Argon2i.

**Comment by mpiot** [comment]
Maybe we can do a test on the PHP version in the .travis.yml, then if it's a PHP > 7.2 add commands to add the option, because we can't add the option in default_configure_options files, there used by every PHP version.

@BanzaiMan I don't really know how it works... What is the variable tha contain the PHP version ?

**Comment by BanzaiMan** [comment]
@mpiot `VERSION` is overridden by the API build request payload. You can see this in, for example, https://travis-ci.org/travis-ci/php-src-builder/jobs/326899986#L482.

**Comment by BanzaiMan** [comment]
Is it acceptable to assume that this hashing algorithm is (almost) universally available in production environments?

**Comment by Condebk717** [comment]
You mean my wallet hashing?

**Comment by BanzaiMan** [comment]
@Condebk717 Could you elaborate? I have no idea what wallet you are talking about.

**Comment by Condebk717** [comment]
Was clear on your comment mr banzaaiMan

**Comment by Condebk717** [comment]
Sorry I misunderstood the conversation my friend

**Comment by Condebk717** [comment]
Banzaiman i might need some help from you if possible 


Regards.

On Wednesday, January 10, 2018, 10:42 PM, Hiro Asari <notifications@github.com> wrote:


@Condebk717 Could you elaborate? I have no idea what wallet you are talking about.

**Comment by Adrien-H** [comment]
@BanzaiMan >

Most applications still use `BCrypt`, but `Argon2` is expected to become a new standard in the PHP ecosystem. Even Symfony implemented this hash as core encoder (https://symfony.com/blog/new-in-symfony-3-4-argon2i-password-hasher).

I think indeed it would not be a bad move to make it universally available. This is only my opinion, though.

**Comment by mpiot** [comment]
@BanzaiMan I agree with Adrien-H, Argon2 is the new way to hash password in database with PHP. For the Symfony Framework, it's the new BestPractice.

I've do something in a fork: https://github.com/mpiot/php-src-builder/commit/5f9cb9c612f72509db1100390ed683378c24616c
If it can help

**Comment by paragonie-scott** [comment]
This adds a lot of overhead to the CI of most of the projects I develop because libsodium has to be compiled/etc. from scratch.

Can we please get a new PHP 7.2 that includes libsodium 1.0.15 and is compiled with ext/sodium support?

**Comment by codemasher** [comment]
pretty please with sugar on top https://travis-ci.org/chillerlan/php-oauth/jobs/334467006

**Comment by Nenglish7** [comment]
When can we get this fixed?

**Comment by TangRufus** [comment]
For those who having trouble compiling `libsodium`, you can install php 7.2 via `ppa:ondrej/php`.
Example: https://github.com/TypistTech/wp-password-argon-two/pull/8/files

**Comment by rayward** [comment]
This was sufficient for me to get sodium working on PHP 7.0 and 7.2:

```yaml
before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libsodium-dev
install:
  - printf "\n" | pecl install libsodium
```

**Comment by rayward** [comment]
It should be, but if travis are building their own 7.2, then the extension might not be compiled in if they didn't have the correct dependencies (ie. libsodium-dev) installed.

**Comment by paresy** [comment]
I would love to get sodium support, too. This would shorten build/test duration by a lot.

**Comment by codemasher** [comment]
At this point it feels like someone is deliberately breaking the package chain and taunting all of us. Isn't there anyone who can poke the right people to fix this? Meanwhile, the official windows builds work perfectly fine, supporting the old and new sodium syntax in php > 7.0...

**Comment by Jean85** [comment]
> I've do something in a fork, if it can help: mpiot/php-src-builder@a6d5349

@mpiot I've opened a PR starting from your fork, thanks!

https://github.com/travis-ci/php-src-builder/pull/20

**Comment by auvipev** [comment]
This is annoying please update your images.

**Comment by tristanbes** [comment]
+1 📦

**Comment by paragonie-scott** [comment]
Bad bot

**Comment by Jean85** [comment]
travis-ci/php-src-builder#20 got merged! :tada:

**Comment by Majkl578** [comment]
Should be resolved by https://github.com/travis-ci/php-src-builder/pull/22 (fixed https://github.com/travis-ci/php-src-builder/pull/20).

**Comment by paragonie-scott** [comment]
Calling it now: @stale is probably the least helpful contributor in this thread, present and future.

**Comment by paragonie-scott** [comment]
https://travis-ci.org/paragonie/halite/builds/479489381 -- if this has no build errors, then this is completely solved.

**Comment by Jean85** [comment]
Green!! :+1:

**Comment by BanzaiMan** [comment]
Closing

**Comment by tuupola** [comment]
Apparently you need to add `dist: trusty` to `.travis.yml` for this to work. Xenial [still fails](https://travis-ci.org/tuupola/branca-php/jobs/606697319).

**Comment by BanzaiMan** [comment]
@tuupola Can you try a newer version?

**Comment by tuupola** [comment]
@BanzaiMan If you mean newer version of PHP then yes `PHP 7.3` and `PHP 7.4snapshot` do not have problems. However I had the builds fail with `PHP 7.2` unless I use the `dist: trusty`.

**Comment by BanzaiMan** [comment]
I meant the more recent teeny releases of 7.2; e.g., 7.2.21. My guess is that the pre-installed 7.2 on the current Xenial image is too old to have this, and forcing the run-time installation of the newer version might solve this problem for you.

**Comment by tuupola** [comment]
Yeah that is possible. In any case adding the `dist: trusty` to `.travis.yml` solved problem for me. Just wrote a note here for others having the same problem to save some debugging time. Took a while to figure it out.
