### ISSUE TITLE
R package builds: avoid duplicated work between R CMD check and covr

### ISSUE THREAD

**Issue by wlandau-lilly** [travis-ci/travis-ci#8864]
Related: r-lib/rcmdcheck#57. 

The regular R package checks include `R CMD check` then `covr::package_coverage()` after success. My unit tests are long, and build time would halve if I only ran the tests once.  Is there a way to do this and still upload typical `R CMD check` artifacts and a [codecov report](codecov.io)?

As [recommended here](https://github.com/craigcitro/r-travis/blob/master/ISSUE_TEMPLATE.md), I am mentioning @craigcitro, @hadley and @jimhester.

**Comment by jimhester** [comment]
No, there is not and likely will never be a way to do it directly from `R CMD check`.

An alternative would be to run `R CMD check` with `--no-tests` to disable running the tests in the check and put `covr::codecov()` in the script block so it would fail the build if a test fails, which would run the tests only once.

**Comment by wlandau-lilly** [comment]
Your suggestion [appears to have worked](https://travis-ci.org/wlandau-lilly/drake/builds/312499331?utm_source=github_status&utm_medium=notification). Thanks!
