### ISSUE TITLE
GitHub pages deployment creates file with name that should be commit msg

### ISSUE THREAD

**Issue by 153957** [travis-ci/travis-ci#8865]
The deploy to GitHub pages creates an extra file in the commit, the name of the file is what should have been the commit message. This can be seen here:
https://github.com/HiSPARC/sapphire/tree/gh-pages
A file called "deployed at .." was created by the deploy step, it was not created in the earlier steps.
Here is the deploy step in travis:
https://github.com/HiSPARC/sapphire/blob/master/.travis.yml#L44-L54

**Comment by BanzaiMan** [comment]
Closing as a duplicate of https://github.com/travis-ci/dpl/issues/696
