### ISSUE TITLE
Tagged release not triggering CI build

### ISSUE THREAD

**Issue by bkuhl** [travis-ci/travis-ci#8867]
I can create PRs, push new branches, etc. all trigger builds fine.  When I published a release at https://github.com/bkuhl/fpm-nginx/releases/tag/v7.2.0 I can't get a CI build to run.  It's my understanding that I should see the tag listed under "Active Branches" at https://travis-ci.org/bkuhl/fpm-nginx/branches.

Going to "More Options" -> "Requests" in Travis shows me a "There was an error while loading data."

What steps can I take to debug this issue?

**Comment by BanzaiMan** [comment]
Looks like you have disabled branch builds in https://travis-ci.org/bkuhl/fpm-nginx/settings. Please try re-enabling it and force push the tag `v7.2.0` or push a new tag.

**Comment by bkuhl** [comment]
Psh, that was it.  Thanks!

It wasn't clear to me that there would be an impact there on tags, and I toggled that a longtime ago.
