### ISSUE TITLE
[RFE] Supporting big endian Linux environment

### ISSUE THREAD

**Issue by junaruga** [travis-ci/travis-ci#8869]
This is a request for enhancement.

Travis is supporting `os`: `linux`, `osx`, I guess the Linux environment is x86_64 (little endian).

However I want to test on big endian Linux architecture too such as ppc64, s390x, or anything.
The environment is useful for me to find big endian specified bugs.
Though I do not know that how many people are interested in it.

```
$ lscpu | grep "Byte Order"
Byte Order:          Little Endian
```

Following the result of `lscpu` command, is it possible to add an attribute `byte_order` to `.travis.yml`?

```
byte_order: little or big (default: little)
```

**Comment by BanzaiMan** [comment]
POWER support in the works, though we do not have ETA.

**Comment by junaruga** [comment]
@BanzaiMan You meant you are working in progress to support POWER, right?
That's awesome!
Thank you Travis.

**Comment by junaruga** [comment]
@BanzaiMan how is the status? Did you start POWER support?

**Comment by BanzaiMan** [comment]
No, we have not.

**Comment by leventov** [comment]
Is there any progress here?

**Comment by junaruga** [comment]
I found the `ppc64le` (little endian) has already used.

https://github.com/openssl/openssl/blob/master/.travis.yml#L35
> - os: linux-ppc64le

And I was able to run little endian arch, not big endian (ppc64, s390x) on below way.

https://github.com/multiarch/qemu-user-static

```
$ docker run --rm --privileged multiarch/qemu-user-static:register --reset

$ docker run --rm -t multiarch/ubuntu-debootstrap:arm64-bionic uname -a
Linux 28c784e9c7bc 4.4.0-101-generic #124~14.04.1-Ubuntu SMP Fri Nov 10 19:05:36 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
```

But I still do not know how to run big endian environment on Travis CI.

**Comment by junaruga** [comment]
Here is my experimental project to use multi arch on Travis CI.
It might be interesting for someone to run those on Travis.
https://github.com/junaruga/ci-multi-arch-test

**Comment by junaruga** [comment]
@BanzaiMan @leventov I could run big endian arch `s390x` with multiarch project's debian image [1] on Travis CI. (Ref: the `.travis.yml` [2])

```
$ docker run --rm --privileged multiarch/qemu-user-static:register --reset
$ docker run --rm -t multiarch/debian-debootstrap:s390x-jessie uname -a
Linux e774bfd6a08e 4.13.0-1008-gcp #11-Ubuntu SMP Thu Jan 25 11:08:44 UTC 2018 s390x GNU/Linux
```
So, personally I am fine to close this ticket.

[1] https://hub.docker.com/r/multiarch/debian-debootstrap/tags/
[2] https://github.com/junaruga/ci-multi-arch-test/blob/master/.travis.yml

**Comment by jeking3** [comment]
Running `uname -a` is not a sufficient test.  I would not close this ticket.  The environment for s390x-jessie is not useful as the apt repositories are not there any more:
```
jking@ubuntu:~$ docker run --rm -it multiarch/debian-debootstrap:s390x-jessie /bin/bash
root@86c296458f25:/# apt-get update
Ign http://deb.debian.org jessie InRelease
Get:1 http://deb.debian.org jessie Release.gpg [2420 B]
Get:2 http://deb.debian.org jessie Release [148 kB]
Err http://deb.debian.org jessie/main s390x Packages

Err http://deb.debian.org jessie/main s390x Packages

Err http://deb.debian.org jessie/main s390x Packages
  404  Not Found
Fetched 151 kB in 7s (21.2 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-s390x/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

and the powerpc one hangs:
```
jking@ubuntu:~$ docker run --rm -it multiarch/ubuntu-debootstrap:powerpc /bin/bash
root@1dbc95b08024:/# apt-get update
0% [Connecting to ports.ubuntu.com]
```

**Comment by jeking3** [comment]
The mips images just fail:

```
jking@ubuntu:~$ docker run --rm -it multiarch/debian-debootstrap:mips-stretch /bin/bash
standard_init_linux.go:207: exec user process caused "no such file or directory"
jking@ubuntu:~$ docker run --rm -it multiarch/debian-debootstrap:mips-buster /bin/bash
standard_init_linux.go:207: exec user process caused "no such file or directory"
jking@ubuntu:~$ docker run --rm -it multiarch/debian-debootstrap:mips-buster /usr/bin/env sh
standard_init_linux.go:207: exec user process caused "no such file or directory"
jking@ubuntu:~$ docker run --rm -it multiarch/debian-debootstrap:mips-buster /usr/bin/env bash
standard_init_linux.go:207: exec user process caused "no such file or directory"
jking@ubuntu:~$ docker run --rm -it multiarch/debian-debootstrap:mips-buster lscpu
standard_init_linux.go:207: exec user process caused "no such file or directory"
jking@ubuntu:~$ docker run --rm -it multiarch/debian-debootstrap:mips-buster uname -a
standard_init_linux.go:207: exec user process caused "no such file or directory"
jking@ubuntu:~$ docker run --rm -it multiarch/debian-debootstrap:mips-buster uname -a
```

**Comment by junaruga** [comment]
@jeking3 Thank you for report. I think we multiarch project need to create s390x container image for the latest Debian and Ubuntu as a big endian case. Also yeah, the testing for the container images are not enough. We have to add gating tests.
Right now you can see other container images here.
https://github.com/multiarch/qemu-user-static#compatible-images

**Comment by junaruga** [comment]
I think it solved here with "qemu-user-static".
https://github.com/multiarch/qemu-user-static/issues/72#issuecomment-500828529

**Comment by junaruga** [comment]
I just want to share you that we multiarch project released a new feature (new image `multiarch/qemu-user-static`) to use a standard architecture specific container image that creates `/proc/sys/fs/binfmt_misc/qemu-$arch` files with `flags: F` to use QEMU without specifying it for each run time.

Now we can use the standard s390x (and maybe ppc64) container images on x86_64 Travis.
Below commands work.
See the document https://github.com/multiarch/qemu-user-static for detail.

```
$ uname -m
x86_64

$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

$ cat /proc/sys/fs/binfmt_misc/qemu-s390x
enabled
interpreter /usr/bin/qemu-s390x-static
flags: F
offset 0
magic 7f454c4602020100000000000000000000020016
mask ffffffffffffff00fffffffffffffffffffeffff

$ docker run --rm -t s390x/ubuntu uname -m
s390x

$ docker run --rm -t s390x/ubuntu:bionic uname -m
s390x

$ docker run --rm -t s390x/ubuntu:bionic bash -cx '
apt-get -y update && \
apt-get -y install gcc
'

$ echo $?
0

$ docker run --rm -t s390x/fedora uname -m
s390x

$ docker run --rm -t s390x/fedora:30 uname -m
s390x

$ docker run --rm -t s390x/fedora:30 bash -cx '
dnf -y upgrade && \
dnf -y install gcc
'

$ echo $?
0
```

**Comment by illume** [comment]
@junaruga cool project! I'm look for ways to test with things like arm and big endian. Do you know of a repo using this with travis? I want to install some dependencies (ubuntu or debian), compile and then run some tests. I guess `s390x/ubuntu` would give me big endian?

**Comment by junaruga** [comment]
@illume I am glad you like it.

> Do you know of a repo using this with travis? I want to install some dependencies (ubuntu or debian), compile and then run some tests. I guess s390x/ubuntu would give me big endian?

Yes. this "ci-multi-arch-test" repo + travis is using is the most recommended example.
https://github.com/junaruga/ci-multi-arch-test/blob/master/.travis.yml

This is Fedora specific example.
https://github.com/junaruga/fedora-workshop-multiarch/blob/master/.travis.yml

Below is not the example of qemu-user-static.
But if you use `arm64v8/ubuntu` (ARM 64-bit), `arm32v7/ubuntu` (ARM 32-bitr), `s390x/ubuntu` (yes, it is big endian) adding those to used `.travis.yml`, it is useful to refer. Using YAMP's anchor and reference feature with a way you might like.
https://github.com/junaruga/rubygems-to-restore-to-pristine/blob/master/.travis.yml

Dockerfile-ubuntu

```
ARG BASE_IMAGE=ubuntu
FROM ${BASE_IMAGE}

RUN something
```

.travis.yml

```
dist: xenial
language: bash
services: docker
os: linux

.com.github.something.matrix-definitions:
  - &test_in_container
    install:
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - |
        travis_retry docker build --rm -t sample \
          --build-arg BASE_IMAGE=${BASE_IMAGE} \
          -f Dockerfile-ubuntu \
          . 
    script: |
      docker run --rm -t sample make test

matrix:
  include:
    - name: arm64
      env:
        - BASE_IMAGE=arm64v8/ubuntu
      <<: *test_in_container
    - name: arm32
      env:
        - BASE_IMAGE=arm32v7/ubuntu
      <<: *test_in_container
    - name: s390x
      env:
        - BASE_IMAGE=s390x/ubuntu
      <<: *test_in_container

install:
  - something for current logic.
script:
  - something for current logic.
```

Below is example of multiarch/qemu-user-static image. But the way (`multiarch/qemu-user-static:register` + the compatible arch image `multiarch/*`) is deprecated.
I just show those as examples of qemu-user-static.

* "pg" gem (ubuntu i386)
  https://github.com/ged/ruby-pg/blob/master/.travis.yml#L15
* bowtie2
  https://github.com/BenLangmead/bowtie2/blob/master/.travis.yml#L25
* nanopolish (ubuntu ARM 64-bit + armhf ARM 32-bit)
  https://github.com/jts/nanopolish/blob/master/.travis.yml#L20

**Comment by illume** [comment]
Wow @junaruga. Awesome. I'll give it a go in the coming days :)

**Comment by junaruga** [comment]
One more tip is that running arch container on QEMU (qemu-user-static) takes more time than a case without QEMU. Maybe 2 or 3 times.
As one of the possible solution, you can run the task only when Travis is executed on cron mode (daily or weekly and etc) without running it at the timing of the pull-request, using `if: type = cron` like this.

```
    - name: arm64
      env:
        - BASE_IMAGE=arm64v8/ubuntu
      if: type = cron
      <<: *test_in_container
```

**Comment by junaruga** [comment]
Yesterday Travis started supporting the native s390x (big endian).

Build your open source projects on IBM Power and IBM Z CPU architecture
https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z

If you have a question, here is the right place.
https://travis-ci.community/c/environments/multi-cpu-arch

I would close this ticket.
Thank you, Travis!

**Comment by harrypgh12** [comment]
I am building a docker container with s390x/ubuntu, but I have an error with "pthread_mutex_init failed" wihen I ran the executable.
If I build the same docker container by changing to i686/ubuntu or i386/ubuntu, I have no issue.
I wonder if anyone had the same problem with s390x.

**Comment by junaruga** [comment]
You meant running s390x/ubuntu container on QEMU on Travis? This can happen. An issue related to the emulation. 

You can report a bug related to QEMU.
https://www.qemu.org/contribute/report-a-bug/
