### ISSUE TITLE
Allow commit authors to restart/cancel builds

### ISSUE THREAD

**Issue by eteq** [travis-ci/travis-ci#887]
Right now it appears that only repo owners can restart builds or jobs that failed for invalid reasons.  It would be nice if the author of a commit also had the rights to do this (via the web UI).  As far as I can tell this is not the case (although if I'm wrong, all the better!)

See astropy/astropy#552 for an example of when this would be useful.

**Comment by BanzaiMan** [comment]
Continuing this at https://travis-ci.community/t/open-the-cancel-button-permission-to-allow-contributors-to-terminate-the-matrix-build-job/101
