### ISSUE TITLE
Bintray deploy 505 error

### ISSUE THREAD

**Issue by dvajdual** [travis-ci/travis-ci#8872]
Hello! In my project, the application should be placed in BinTray. But installation in travis ends with an error in the step deploy -
[Bintray Upload] Reading descriptor file: travis-bintray.json

Unexpected HTTP response code 505 returned from Bintray while checking if version '$ {TRAVIS_TAG}' exists. Response message: HTTP Version Not Supported

When I pointed out the version existing in Bintray - 0.6 the result was the same.
 
No idea what the problem is?

References to the code and travis:
https://travis-ci.org/dvajdual/SimplyTest/jobs/312881802
https://github.com/dvajdual/SimplyTest/blob/develop/.travis.yml
https://github.com/dvajdual/SimplyTest/blob/develop/travis-bintray.json

**Comment by BanzaiMan** [comment]
Does the deployment succeed if you try it locally?
