### ISSUE TITLE
Where is the Perl6 community support repo?

### ISSUE THREAD

**Issue by JJ** [travis-ci/travis-ci#8873]
I have been unable to find it  @paultcochrane @hoelzro @ugexe @tony-o 
Maybe insert a link in the documentation?

**Comment by BanzaiMan** [comment]
It is not a separate repository. You can find the code here: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/perl6.rb

I don’t think this level of implementation detail is needed in our documentation.
