### ISSUE TITLE
Cannot view job log for following id

### ISSUE THREAD

**Issue by ORESoftware** [travis-ci/travis-ci#8876]
Nothing is showing up in logs, so I click on "raw logs" and I see this:

```json
{
  "log": {
  "job_id": 313828481,
  "parts": [],
  "@type": "Log"
 }
}
```

so I am unable to see the regular logs or raw logs, not sure why

**Comment by BanzaiMan** [comment]
https://travis-ci.org/ORESoftware/poolio/jobs/313828481 shows logs now.
