### ISSUE TITLE
Perl 'blead' version no longer works

### ISSUE THREAD

**Issue by karenetheridge** [travis-ci/travis-ci#8878]
e.g. see this failing job: https://travis-ci.org/karenetheridge/B-Hooks-Parser/jobs/314070096

    blead is not installed; attempting download
    Downloading archive: https://s3.amazonaws.com/travis-perl-archives/binaries/ubuntu/14.04/x86_64/perl-blead.tar.bz2
    $ sudo tar xjf perl-blead.tar.bz2 --directory /
    bzip2: (stdin) is not a bzip2 file.
    tar: Child returned status 2
    tar: Error is not recoverable: exiting now

I understand from https://github.com/travis-ci/travis-ci/issues/7825#issuecomment-305849802 that Perl version detection is now automated; did blead get dropped as a supported version as a result?  ('blead' is the main development branch in Perl; in the past, 'blead' as a version in travis has corresponded to a nightly build of blead.)

**Comment by BanzaiMan** [comment]
Did this ever work? If so, do you have a build log URL that shows it?

**Comment by karenetheridge** [comment]
Apologies, it looks like blead builds were being supported by an additional set of scripts on top -- https://github.com/travis-perl/helpers. I will pursue the issue there.

(Breadcrumb: this build is an example of when things worked: https://travis-ci.org/karenetheridge/Dist-Zilla-PluginBundle-Author-ETHER/jobs/282015994)
