### ISSUE TITLE
Abuse Detected

### ISSUE THREAD

**Issue by aghassemi** [travis-ci/travis-ci#8882]
Hi from [AMP Project](https://github.com/ampproject/amphtml) here.

https://github.com/ampproject/amphtml/pull/12159 is being flagged as abuse. I asked the author to login to Travis with their Github account and they did that, but still getting flagged.  Could you please look into it?

Thank you,

**Comment by BanzaiMan** [comment]
Please email support@travis-ci.com, as it may entail some private information. Thanks.
