### ISSUE TITLE
cannot add public repo from an github organization which I'm owner

### ISSUE THREAD

**Issue by anthrotype** [travis-ci/travis-ci#8884]
"Sorry, it seems like we couldn't find any repositories you have access to on GitHub."

also the "fonttools" organization appears twice in the list:

![image](https://user-images.githubusercontent.com/6939968/33895060-dbba6fea-df5f-11e7-9aee-303f55d2e065.png)

None of the two "FontTools" listed allow me to add a new repo to Travis.

We do have other repos registered with Travis (which I've done myself, as the owner of that github org).

What can i do?

Thanks

**Comment by anthrotype** [comment]
If I click "Sync Account" nothing changes. It just says Last synced less than a minute ago..
I can she repos from other organizations I'm member of, only this one doesn't seem to be working.

If I go to the github.com/fonttools settings page, I can see Travis is listed in green and authorized to access the organization private data:

![image](https://user-images.githubusercontent.com/6939968/33895266-6bf407f6-df60-11e7-99ee-5c64fcd8537a.png)

**Comment by anthrotype** [comment]
Don't know if it may help, but this is the repository I'd like to add to Travis CI.
https://github.com/fonttools/ttfautohint-python

**Comment by anthrotype** [comment]
I'm still having this issue. To be able to run tests on Travis, I had to fork the repo using my personal github account, since Travis doens't let me access the organization repos (despite I'm the owner).

Is there any any support email I can write to?

**Comment by anthrotype** [comment]
It's been three days and I didn't get any reply from Travis support team... :cry: 
I even tried to revoke Travis CI authorization from my github organization's settings and then add it again but still doesn't work.
There is nothing else I can do from my side.

**Comment by BanzaiMan** [comment]
Sorry about the delay. Could you email us at support@travis-ci.com? I am guessing that the duplicate appearances of Fonttools might be to blame, and we'll need some extra sets of eyes.

**Comment by anthrotype** [comment]
No problem, thank you. I’ll write an email there. Sorry if I was too insistent :)

**Comment by anthrotype** [comment]
Thanks Dominic from support@travis-ci.com for solving the issue!
Apparently for some reason there was a duplicate of my organization in your database. Removing one from your end solved the problem.

**Comment by cotsog** [comment]
The problem was duplicate data in our database that needed to be manually fixed on our end.

If you ever run into something similar, please reach out at [support@travis-ci.com](mailto:support@travis-ci.com), we would be happy to help you with this.
