### ISSUE TITLE
Android/A problem of consistent about ./gradlew test

### ISSUE THREAD

**Issue by XinyueZ** [travis-ci/travis-ci#8885]
Hi , 

Android Dev

I have run  ```./gradlew test``` on my local machine and travis.ci , however, I got two different "Delete of stale output file" .

On travis:
Deleting stale output file: 

/home/travis/build/XXXXXXXX/build/generated/source/kapt/mockDebug

* The data-binding generated files will be deleted and the app cannot be built.

On local:
Deleting stale output file: 

/home/travis/build/XXXXXXXX/build/tmp/kapt3/incrementalData/mockDebugUnitTest

which should be *OK* , the data-binding generated files are still there after whole building.

I think it would be a bug. 
I have *mock*, *prod* flavors which should not be matter on this case.

**Comment by BanzaiMan** [comment]
Does the problem persist if you try it on a fresh machine? You may also try reproducing with our Docker images as described in https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image, or we can enable a debug feature for you.

**Comment by XinyueZ** [comment]
@BanzaiMan this happen persistly.  
Same Gradle-Test running on Travis is different from in local command line.

**Comment by XinyueZ** [comment]
@BanzaiMan this happen persistly.  
Same Gradle-Test running on Travis is different from in local command line.

**Comment by BanzaiMan** [comment]
@XinyueZ Did you try reproducing the problem? I suspect your local build has some files that clean machine does not, and you are not setting up the build completely and accurately.

**Comment by XinyueZ** [comment]
my problem, wrong config in modules
