### ISSUE TITLE
Docker image for Travis-ci

### ISSUE THREAD

**Issue by amimas** [travis-ci/travis-ci#8886]
Hello,

I'd like to try out Travis-CI Enterprise but don't want to go through a full setup/installation. Is there a docker image for the Travis-CI server? I checked the docker hub but there are a lot of different images available:
https://hub.docker.com/u/travisci/

It looks like each images are for various different components Travis needs but none of the images listed in docker hub has any documentations or info on how to setup. Are these even official image?

Is it not possible to dockerize Travis CI? Once you setup Travis CI locally, you'll need to upload your license files anyway. So, not sure why there isn't a docker image for the CI server as of yet. Or, maybe I'm looking at the wrong place!

**Comment by BanzaiMan** [comment]
Sorry, but we do not currently provide support for self-hosting Travis CI. If you are interested in testing Travis Enterprise, please send email to enterprise@travis-ci.com.

Thanks.
