### ISSUE TITLE
Travis CI build error for R packages

### ISSUE THREAD

**Issue by bozmik** [travis-ci/travis-ci#8887]
Hi,

I receive the following error from Travis after doing a git push:

Installing R packages from GitHub: jimhester/covr
$ Rscript -e 'devtools::install_github(c("jimhester/covr"), 
build_vignettes = FALSE)'

Error: package ‘devtools’ was installed by an R version with different 
internals; it needs to be reinstalled for use with this R version

Execution halted

Here are examples of my build logs:
https://travis-ci.org/bozmik/genomation/jobs/315357710#L1125
https://travis-ci.org/bozmik/genomation/jobs/315287462#L1125
https://travis-ci.org/bozmik/gseaK/jobs/315369397#L1125

What could be a source of this issue?

Thanks,
Bozena

**Comment by BanzaiMan** [comment]
Please mention @craigcitro and @jimhester for R inquiries, as indicated in the build log. Thank you.

**Comment by rstub** [comment]
I am having the same problem, but removing the cache did not help: 
https://travis-ci.org/RInstitute/rcpparrayfire/jobs/315518645
Maybe because `devtools` is installed as binary package:
https://travis-ci.org/RInstitute/rcpparrayfire/jobs/315518645#L1477
?

**Comment by gergness** [comment]
Wow, was literally typing the same thing as @rstub. 

@jimhester any ideas? For me it's only r-devel that still fails https://travis-ci.org/mnpopcenter/ipumsr

**Comment by jimhester** [comment]
Yes, you are right @rstub, it is because devtools is installed as a binary package with `sudo: required`, which breaks for this case. I will send an update turning off using devtools as binary.

**Comment by asardaes** [comment]
Did something also break for OSX? All my OSX builds are failing now ([example](https://travis-ci.org/asardaes/dtwclust/jobs/322390354#L446)).

The file where the error is found doesn't cause any issues on Linux or Windows, and I didn't even change that file in the commit where the builds started failing.

**Comment by LiNk-NY** [comment]
Has this been fixed? Can the issue be closed? @bozmik @rstub

**Comment by rstub** [comment]
I am still using a workaround by adding `devtools` to `r_packages`. Without that builds with `R-devel` still fail.
