### ISSUE TITLE
Misleading NodeJS docs

### ISSUE THREAD

**Issue by YonatanKiron** [travis-ci/travis-ci#8888]
After reading [this](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/) docs, we tried to write a node_js .travis.yml.
When specifying:

```
language: node_js
node_js:
  - "8" # Or "8.9"
script:
  - nvm list
```
The output of `nvm list` is:
```
$ nvm list
    iojs-v1.1.0
        v0.6.21
        v0.8.27
       v0.10.18
->     v0.10.36
       v0.11.15
0.1 -> v0.10 (-> v0.10.36)
0.10 -> v0.10.36
default -> v0.10.36
node-unstable -> v0.11.15
stable -> 0.10 (-> v0.10.36) (default)
unstable -> 0.11 (-> v0.11.15) (default)
```

Which looks like actually there is no node 8 (or any newer stable version that greater then ` v0.10.36`) 
Which made me wonder if I'm doing something wrong or that there is actual issue with NodeJS 8

**Comment by BanzaiMan** [comment]
Where do you see this output of `nvm list`? `nvm list` only writes the versions locally installed, and it is not indicative of what it can install. For the list of valid versions, you need [`nvm ls-remote`](https://github.com/creationix/nvm/#listing-versions).

If you have suggestions on how to improve the docs, please open a PR (follow the "Improve" button on the upper right corner).

**Comment by YonatanKiron** [comment]
So what 
```
node_js:
  - "8"
```
means? 
Isn't it means that the instance/container contains pre-installed `node 8`?

**Comment by YonatanKiron** [comment]
Ok, now I see that you updated yesterday your trusty image https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch 
which comes with pre-installed nodejs 8.9.1

**Comment by BanzaiMan** [comment]
```yaml
node_js: 8
```
means Node.js 8.x is used for build. It does not mean it is pre-installed.
