### ISSUE TITLE
bower: command not found

### ISSUE THREAD

**Issue by ragesoss** [travis-ci/travis-ci#8890]
As of today, my build is erroring with `bower: command not found`.

See https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/315501483

Bower gets installed globally via `yarn global add bower` in the setup phase and appears to think it got installed successfully:

```
yarn global v1.3.2

[1/4] Resolving packages...

warning bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

[2/4] Fetching packages...

[3/4] Linking dependencies...

[4/4] Building fresh packages...

success Installed "bower@1.8.2" with binaries:

```

**Comment by BanzaiMan** [comment]
Many of the software packages have been updated, including `yarn` (from [0.27.5](https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/315017128#L743) to [1.3.2](https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/315501483#L775)), as shown in https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/. Is it possible that this affects your build? When you install `bower` locally with `yarn`, where is it installed?

**Comment by BanzaiMan** [comment]
Do you mind reproducing the issue with our Docker image as described in https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image?

**Comment by cotsog** [comment]
@ragesoss I believe this issue stems from the binary's path not being in the `$PATH` anymore.

Before, `bower` was installed in `/home/travis/.nvm/versions/node/v7.4.0/bin` which was included in the `$PATH`.

Now, `bower` is installed in `/home/travis/.yarn/bin` on the new image which isn't included in the `$PATH`.

We'll have to check why this is happening and how to fix it.

In the meantime, you can add the following to your .travis.yml file before installing `bower`:

- export PATH=$PATH:`yarn global bin`

Can you let me know if this helps?

Thanks!

**Comment by ragesoss** [comment]
@cotsog thanks! I just tried that, but it still errors with `bower: command not found`: https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/315558659

**Comment by cotsog** [comment]
@ragesoss you were missing the backticks. I've fixed it in this PR => https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1545

**Comment by ragesoss** [comment]
@cotsog that seems to have solved it. Thanks!

**Comment by BanzaiMan** [comment]
Ah, interesting. If this is a change in how `yarn` works, perhaps we should take care of it if we detect use of `yarn`.

**Comment by cotsog** [comment]
Cross-linking to the documented issue and workaround: https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-351395853

**Comment by BanzaiMan** [comment]
`$(yarn global bin)` will be added to `$PATH` everywhere, since `yarn` is pre-installed on all images.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/commit/985787e07cad63b7b4310a8c8f994cf189b9d79f is wrong. It needs to be fixed.

**Comment by Kodwings22** [comment]
You can check this link too may be useful ( https://kodlogs.net/307/bower-command-not-found)
