### ISSUE TITLE
Trusty broken golang builds

### ISSUE THREAD

**Issue by CMogilko** [travis-ci/travis-ci#8903]
Hi, 
with new image travis broke go builds, it doesn't pull dependencies with default `install` `go get -t ./...` it seems.
```
ql2/ql2.pb.go:22:8: cannot find package "github.com/golang/protobuf/proto" in any of:
	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/github.com/golang/protobuf/proto (from $GOROOT)
	/home/travis/gopath/src/github.com/golang/protobuf/proto (from $GOPATH)

cluster.go:12:2: cannot find package "github.com/hailocab/go-hostpool" in any of:
	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/github.com/hailocab/go-hostpool (from $GOROOT)
	/home/travis/gopath/src/github.com/hailocab/go-hostpool (from $GOPATH)

connection.go:15:2: cannot find package "github.com/opentracing/opentracing-go" in any of:
	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/github.com/opentracing/opentracing-go (from $GOROOT)
	/home/travis/gopath/src/github.com/opentracing/opentracing-go (from $GOPATH)
```
https://travis-ci.org/GoRethink/gorethink/jobs/315439011

**Comment by BanzaiMan** [comment]
Could you try reproducing the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)?

**Comment by CMogilko** [comment]
@BanzaiMan old trusty image, success build, default install script is ok:
https://travis-ci.org/GoRethink/gorethink/jobs/313458660 (log line 468)
new image, failed build, default install script don't work:
https://travis-ci.org/GoRethink/gorethink/jobs/315439011 (log line 471)
here https://docs.travis-ci.com/user/languages/go#Dependency-Management said that default install script must be `go get -t ./...` not `true`

**Comment by BanzaiMan** [comment]
Have you tried `go get -t ./...` with the new image? The two failing builds you've shown both skips the install step with `true`.

**Comment by CMogilko** [comment]
oh, I found the reason. A new makefile appeared in the repo so default `install` became `true`. Unexpected.
