### ISSUE TITLE
can no longer install `npm-snapshot` after Trusty 12th December 2017 release

### ISSUE THREAD

**Issue by musketyr** [travis-ci/travis-ci#8905]
running `yarn global add npm-snapshot` shows following warning and won't install `npm-snapshot` to the PATH

```
warning You are using Node "7.10.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
```

**Comment by musketyr** [comment]
closing as this is definitely duplicate of #8890

**Comment by cotsog** [comment]
Cross-linking to the documented issue and workaround: https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-351395853
