### ISSUE TITLE
cURL error 35: gnutls_handshake() failed: Handshake failed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html

### ISSUE THREAD

**Issue by markdza** [travis-ci/travis-ci#8912]
Since yesterday (2017-12-12T17:32:11Z) our builds are getting the following error for Guzzle curl calls:

```
cURL error 35: gnutls_handshake() failed: Handshake failed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html
```

Any idea why the curl calls run fine on local and on our servers and only fails on Travis?

**Comment by BanzaiMan** [comment]
Looks like a duplicate of #6339.

**Comment by markdza** [comment]
Could be the same but the error message is different
