### ISSUE TITLE
After Trusty update SeleniumLibrary acceptance test started failing

### ISSUE THREAD

**Issue by aaltat** [travis-ci/travis-ci#8913]
I use this type of [.travis.yaml](https://github.com/robotframework/SeleniumLibrary/blob/v3.0.1/.travis.yml) configuration. Before the Trusty update on 12.12 this configuration worked perfectly. But now that configuration does not anymore work when tests are run by using the Firefox browser. It seems that some test fails because in some point in the Firefox execution test hangs. If I set the .travis.yaml to contain: `group: deprecated-2017Q4` then all acceptance test [work fine](https://travis-ci.org/robotframework/SeleniumLibrary/builds/316102672).

Is there something that I should change in the `.travis.yaml` file that I could use the latest Trusty image with my project?

**Comment by JDGrimes** [comment]
I am experiencing a [similar issue](https://github.com/WordPoints/wordpoints/issues/757) with Selenium web driver tests run with Codeception and the PhantomJS browser. After the latest image update, the build always stalls somewhere during the tests, and then is killed because there has been no output for 10 minutes. Switching to the previous image allows the tests to complete normally.

**Comment by aaltat** [comment]
I think this does not have anything to do with Travis update. I am seeing similar problems with the `group: deprecated-2017Q4`. After thinking the problem, I think that Chrome and Chromedriver was updated in same time and the Chrome is actually giving problems for me. Because this does not look like Travis problem, I am closing the issue and looking solution from somewhere else.

I have removed the `group: deprecated-2017Q4` configuration from the `.travis.yam` file and running with the latest trusty image.

**Comment by aaltat** [comment]
@JDGrimes I did modify my library logging and made Travis log the Selenium API class to the console. For me, it hangs on Selenium method: `webdriver.Chrome`. I haven not found a solution for the problem, but for more details and further updates, see https://github.com/robotframework/SeleniumLibrary/issues/1058
