### ISSUE TITLE
New Trusty Image broke this build.

### ISSUE THREAD

**Issue by thebithead** [travis-ci/travis-ci#8916]
Reference builds:

1) good Dec 12th: https://travis-ci.org/nuodb/nuoca/builds/315444788
2) bad Dec 14th: https://travis-ci.org/nuodb/nuoca/builds/316420349
3) good Dec 14th: https://travis-ci.org/nuodb/nuoca/builds/316424719

#1 from above was the last known good master build. 
#2 from above has a harmless change in .travis.yml to show that master is now broken. 
#3 from above has the workaround to use the previous Trusty image (mentioned in the TravisCI annoucement of new Trusty image)

**Comment by BanzaiMan** [comment]
Looks like a duplicate of #8906.
