### ISSUE TITLE
Repos' cc.xml feed doesn't show real-time builds when a branch is specified

### ISSUE THREAD

**Issue by iriberri** [travis-ci/travis-ci#8924]
See: https://twitter.com/user/status/940989931786293249

According to https://github.com/travis-ci/travis-api/blob/2241c6a1023b72b2f1d298ade8ead081677ba9cf/lib/travis/api/app/responders/xml.rb#L50-L56:

```
   def build(repository)
      if branch.present?
        repository.last_completed_build(branch)
      else
        repository.last_build
      end
end
```

It appears that, when a specific branch is requested (`https://api.travis-ci.org/repos/OWNER/REPO/cc.xml?branch=master`) Travis checks automatically the last finished build, instead of checking any currently running builds.

**Comment by felixfbecker** [comment]
This is very annoying. With other CI providers like Buildkite I can see a helpful approximate countdown when the build will be finished. But with Travis, only the previous build status is shown.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
