### ISSUE TITLE
Perl 5.28 support

### ISSUE THREAD

**Issue by FGasper** [travis-ci/travis-ci#8930]
This is to request addition of Perl 5.28 to the Linux testing infrastructure.

The following build passed but actually just used system perl, not 5.28:
https://travis-ci.org/FGasper/p5-X-Tiny/jobs/317371227

Thank you!

**Comment by BanzaiMan** [comment]
Sorry, but Perl 5.28 does not seem to be released yet.

**Comment by FGasper** [comment]
My bad … I brain-farted. Perl 5.28 isn’t released yet. Sorry.

**Comment by karenetheridge** [comment]
It has been released now. Could someone please re-open this issue?
