### ISSUE TITLE
Timeout : No output has been received in the last 10m0s

### ISSUE THREAD

**Issue by aurelien-baudet** [travis-ci/travis-ci#8932]
Hello,

Since the new timeout management, my build doesn't work anymore.
My build is working and is printing out some logs in the console:
```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.752 sec - in fr.sii.spring.boot.runtime.testing.ApplicationTests
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.437 sec - in fr.sii.spring.boot.runtime.testing.ApplicationTests
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
Tests ru
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

So I tried to use the new `travis_wait` function set to 30 but still stop after 10m0s.

Here is the command that is run:
```
mvn test -T 2.5C -f "$HOME/classpath-tests/$TEST_FOLDER/pom.xml" -Dmaven.test.redirectTestOutputToFile=false -fae -q | grep -Ei '(error|exception|Tests run:)'
```
This command will run many many tests in different maven projects in parallel. The grep is useful to keep only relevant logs (when something went wrong to be able to fix it quickly).

Even if I remove the grep, the build still fails.

If I remove the `-q` parameter, there will be a lot of useless logs and the build will fail due to the limitation of 4Kb.

Why the output is not taken into account by Travis ? Why `travis_wait` has no effect ?

Thank you

**Comment by BanzaiMan** [comment]
`travis_wait` is ineffective probably because `mvn` is spawning a child process that `travis_wait` cannot monitor.

The best defense is probably to write something to STDOUT with or without `travis_wait`.

**Comment by bkimminich** [comment]
Is this supposedly the same root cause as #8898?

**Comment by aurelien-baudet** [comment]
@BanzaiMan Precisely, when I don't use `travis_wait`, the ouput of the mvn command is written to STDOUT. So I don't understand why Travis considers that there is no output at all. Maybe due to the grep, but why ?

**Comment by bencaradocdavies** [comment]
@aurelien-baudet the new trusty images use Maven 3.5.2. Since this update, almost all [GeoServer builds](https://travis-ci.org/geoserver/geoserver/branches) fail with the same bogus timeout. My investigations revealed that there is a new bug in Maven 3.5.2 (not present in Maven 3.5.0) that causes a deadlock during dependency resolution in multi-threaded builds:
http://osgeo-org.1560.x6.nabble.com/Travis-failures-started-with-new-trusty-images-td5346836.html

My workaround is to add a `before_script` to download and use Maven 3.5.0:
```
before_script:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
  - tar zxf apache-maven-3.5.0-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-3.5.0
- export PATH=$M2_HOME/bin:$PATH
```

Whether this workaround helps you depends on whether the same bug causes the timouts you observe.

**Comment by aurelien-baudet** [comment]
Thanks, it worked. I now use maven wrapper instead.

**Comment by bencaradocdavies** [comment]
@aurelien-baudet can you please clarify? Did you use maven-wrapper to switch to Maven 3.5.0 and thus fix your build?

**Comment by bencaradocdavies** [comment]
I reported the Maven deadlock: https://issues.apache.org/jira/browse/MNG-6323

**Comment by aurelien-baudet** [comment]
@bencaradocdavies yes exactly, I used maven wrapper to force the use of version 3.5.0 and it fixed my build. The problem comes from maven deadlock.

I prefer this solution instead of downloading and configuring a specific maven version for Travis. Now I have a reproducible build and same environment between Travis and local.

**Comment by bencaradocdavies** [comment]
@aurelien-baudet thanks for the clarification and advice.
