### ISSUE TITLE
Include URL for build inside ENV vars

### ISSUE THREAD

**Issue by orta** [travis-ci/travis-ci#8935]
Hello there, I'm looking to provide a link back to your job from inside the build. Right now I can get _close enough_ - but it won't take into account whether you are on: travis.org / travis.com / enterprise

I debated the API, but would end up with the same problem of knowing the API host.

Here's an example of what I can pull out of the env vars:

```sh

// See end of https://travis-ci.org/danger/danger-js/jobs/317790046

//  TRAVIS="true"
//  TRAVIS_ALLOW_FAILURE="false"
//  TRAVIS_BRANCH="env_improve"
//  TRAVIS_BUILD_DIR="/home/travis/build/danger/danger-js"
//  TRAVIS_BUILD_ID="317790044"
//  TRAVIS_BUILD_NUMBER="1840"
//  TRAVIS_COMMIT="b8a4f70062810274ee8ae155b2bbe4d0b4e0ddf4"
//  TRAVIS_COMMIT_MESSAGE="[Env] Start work on improving the status message"
//  TRAVIS_COMMIT_RANGE="1469195a5f86...b8a4f7006281"
//  TRAVIS_EVENT_TYPE="push"
//  TRAVIS_JOB_ID="317790046"
//  TRAVIS_JOB_NUMBER="1840.2"
//  TRAVIS_LANGUAGE="node_js"
//  TRAVIS_NODE_VERSION="8"
//  TRAVIS_OS_NAME="linux"
//  TRAVIS_PRE_CHEF_BOOTSTRAP_TIME="2017-12-05T19:33:30"
//  TRAVIS_PULL_REQUEST="false"
//  TRAVIS_PULL_REQUEST_BRANCH=""
//  TRAVIS_PULL_REQUEST_SHA=""
//  TRAVIS_PULL_REQUEST_SLUG=""
//  TRAVIS_REPO_SLUG="danger/danger-js"
//  TRAVIS_SECURE_ENV_VARS="false"
//  TRAVIS_STACK_FEATURES="basic cassandra chromium couchdb disabled-ipv6 docker docker-compose elasticsearch firefox go-toolchain google-chrome jdk //  neo4j nodejs_interpreter perl_interpreter perlbrew phantomjs postgresql python_interpreter rabbitmq redis riak ruby_interpreter sqlite //  TRAVIS_STACK_JOB_BOARD_REGISTER="/.job-board-register.yml"
//  TRAVIS_STACK_LANGUAGES="__garnet__ c c++ clojure cplusplus cpp default go groovy java node_js php pure_java python ruby scala"
//  TRAVIS_STACK_NAME="garnet"
//  TRAVIS_STACK_NODE_ATTRIBUTES="/.node-attributes.yml"
//  TRAVIS_STACK_TIMESTAMP="2017-12-05 19:33:46 UTC"
//  TRAVIS_SUDO="false"
//  TRAVIS_TAG=""
//  TRAVIS_TEST_RESULT="0"
//  TRAVIS_UID="2000"
```

Any chance we can get a `TRAVIS_BUILD_URL` as `https://travis-ci.org/danger/danger-js/jobs/317790046`>

**Comment by BanzaiMan** [comment]
Could you elaborate on the use case?

**Comment by orta** [comment]
Sure, in my case a failing build sets a commit status on GitHub (it's for http://danger.systems/ruby/) - this has the ability to link to information about the failed build. I'd like that link to be able to go back to the travis build where the commit flag was triggered.

**Comment by csandanov** [comment]
Any news on that issue? We want to build an integration with TravisCI and provide URL for deployed builds

**Comment by ivailop** [comment]
The same has also been asked in #7552 about a year ago

**Comment by BanzaiMan** [comment]
We now have `TRAVIS_BUILD_WEB_URL` and `TRAVIS_JOB_WEB_URL` for this purpose. The announcement will be made soon.

**Comment by orta** [comment]
Awesome, thanks!
