### ISSUE TITLE
Cannot read property 'concat' of undefined in ember build

### ISSUE THREAD

**Issue by lavenya-alagarsamy** [travis-ci/travis-ci#8940]
In Travis 'ember build' command gives error,

```
Cannot read property 'concat' of undefined
TypeError: Cannot read property 'concat' of undefined
    at visit (/home/travis/build/freshdesk/freshfone-widget/node_modules/is-my-json-valid/index.js:366:69)
    at /home/travis/build/freshdesk/freshfone-widget/node_modules/is-my-json-valid/index.js:416:9
    at Array.forEach (native)
    at visit (/home/travis/build/freshdesk/freshfone-widget/node_modules/is-my-json-valid/index.js:409:18)
    at /home/travis/build/freshdesk/freshfone-widget/node_modules/is-my-json-valid/index.js:543:9
    at Array.forEach (native)
    at visit (/home/travis/build/freshdesk/freshfone-widget/node_modules/is-my-json-valid/index.js:540:31)
    at compile (/home/travis/build/freshdesk/freshfone-widget/node_modules/is-my-json-valid/index.js:565:3)
    at visit (/home/travis/build/freshdesk/freshfone-widget/node_modules/is-my-json-valid/index.js:340:16)
    at /home/travis/build/freshdesk/freshfone-widget/node_modules/is-my-json-valid/index.js:416:9
```

node_js: "6.9.4"
ember-cli: 2.12.3
node: 6.9.4
os: linux x64
bower - 1.8.2
phantomjs - 2.1.1

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by lavenya-alagarsamy** [comment]
When we try to run ember test, project does not get built. Here is the log url https://api.travis-ci.com/v3/job/103229621/log.txt?log.token=H4gpJ6X5EArkcuoE1vcsuQ.

**Comment by BanzaiMan** [comment]
Hmmm. Very strange. Have you tried running a debug build? https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by lavenya-alagarsamy** [comment]
Yes. I tried running the build in debug mode and it still shows the same error.

**Comment by BanzaiMan** [comment]
If the issue is reproducible with the debug VM, then you are in the best position to proceed, as we do not have access to your code.

**Comment by HeartSaVioR** [comment]
Same here.
https://travis-ci.org/HeartSaVioR/streamline/builds/318059015

Odd thing is that old image is not used even I put config for that.

**Comment by BanzaiMan** [comment]
@HeartSaVioR Could you try reproducing the issue with our Docker images? https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image
