### ISSUE TITLE
Job failure with no error code or output

### ISSUE THREAD

**Issue by externl** [travis-ci/travis-ci#8941]
Often, our job will abruptly stop without any error or output.

See https://travis-ci.org/zeroc-ice/ice/jobs/318155143

We expect to see the script finish with something like.
```
The command "$DOCKER_RUN "${ALLTESTS} --filter=cpp"" exited with 0.

Done. Your build exited with 0.
```

But with the job above there is no script finished message. Just an abrupt exit and no error. Shouldn't docker **always** print something like:
```
Done. Your build exited with <exit status>.
```

EDIT: We're using the _stage_ beta feature. Maybe there's an issue with it?

EDIT 2: Re-running the failed stage job  always works.

**Comment by avagin** [comment]
> make[2]: write error
This error means that make could not write a message to stdout.

This issue is a dup of https://github.com/travis-ci/travis-ci/issues/8920

**Comment by externl** [comment]
Probably the same as #8920
