### ISSUE TITLE
Python 3.6.4 builds crash

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#8944]
https://travis-ci.org/LolexOrg/Lolex-Tools/jobs/318529090

**Comment by BanzaiMan** [comment]
Python 3.6.4 has just been added to python-build via https://github.com/pyenv/pyenv/commit/2c3998f88bc1924c4a251d442616c64d12ce4266, so it will be available for use on Travis when the archive is compiled at https://travis-ci.org/travis-ci/cpython-builder/builds.

**Comment by Monkeyboy2805** [comment]
Ok

**Comment by BanzaiMan** [comment]
It should be available now. https://travis-ci.org/travis-ci/cpython-builder/builds/318722040

**Comment by Monkeyboy2805** [comment]
Sorted
