### ISSUE TITLE
question: several entries for the same deploy provider possible?

### ISSUE THREAD

**Issue by tooomm** [travis-ci/travis-ci#8947]
Can I add a single provider like `GitHub Releases` e.g. two times with different configs and conditions?
One config for all tagged commits, and another one for a particular branch for example.

In the docs only multiple providers are mentioned. Has it to be different ones?
https://docs.travis-ci.com/user/deployment/#Deploying-to-Multiple-Providers

**Comment by BanzaiMan** [comment]
Yes. You can define multiple deployment providers of the same kind in an array.
