### ISSUE TITLE
Python push builds fail during install

### ISSUE THREAD

**Issue by ylemkimon** [travis-ci/travis-ci#8952]
Python push(branch) builds in our repo, sympy/sympy, are failing during installation(setup.py), without error message in the log, since December 15: https://travis-ci.org/sympy/sympy/builds

PR builds targeting same branch seem to work fine, so it seems it's not due to changes we've made.

**Comment by cpascual** [comment]
I am seeing exactly the same thing with my project: https://travis-ci.org/taurus-org/taurus/builds

**Comment by avagin** [comment]
Welcome to the club: https://github.com/travis-ci/travis-ci/issues/8920

**Comment by avagin** [comment]
https://travis-ci.org/avagin/taurus/builds/319569890

**Comment by ylemkimon** [comment]
@avagin Thank you! It seems to solve it.

So this is probably a duplicate of #8920.
