### ISSUE TITLE
Branches missing, request failing in my repository

### ISSUE THREAD

**Issue by fluffysquirrels** [travis-ci/travis-ci#8956]
[My repository](https://travis-ci.org/fluffysquirrels/itm) is not showing any branches on travis-ci.org, but [there are 3 on Github](https://github.com/fluffysquirrels/itm).

When I try to trigger a custom request it fails.

I tried fixing lint errors shown by `travis lint` version 1.8.8.

I have tried de-activating and re-activating the repository in travis, and deleting the integration in Github.

Any other things I can try?

**Comment by BanzaiMan** [comment]
In https://github.com/fluffysquirrels/itm/blob/e5cd62a436034db170b7cfb2cd96de0ec3c07dd0/.travis.yml#L70-L75, you see that you have disabled builds in most branches.

See also https://travis-ci.org/fluffysquirrels/itm/requests

**Comment by fluffysquirrels** [comment]
Oops! Sorry I didn't see that in the config. Thanks for the help.
