### ISSUE TITLE
[Dart] pub get hangs 

### ISSUE THREAD

**Issue by johncblandii** [travis-ci/travis-ci#8957]
The builds hang consistently, ex - https://travis-ci.org/johncblandii/distinctly-redux.dart. It is 20 minutes in right now.

Any ideas why this would be? I tried a simple config and this detailed one from [dart_dev](https://github.com/Workiva/dart_dev/blob/master/.travis.yml).

// cc @nex3 @a14n

**Comment by a14n** [comment]
Your build seams to hang on `pub get`. Regarding your `pubspec.yaml` all `any` in version ranges could explain that it hangs. You should try to tighten the dependency version ranges to make the job of dependencies solver easier.

**Comment by johncblandii** [comment]
Why would it hang on `any`? That's a valid value to allow other dependencies to control those. I'll adjust them but I'm curious.

**Comment by a14n** [comment]
The more the range of version is large the more the dependency solver will take time.

By simplifying a lot, the solver try to find a compatible set of versions. If you depends on A, B, C that each have 100 versions, in the worse case it could have to try `100 * 100 * 100` combinations to find the best one. If you reduce the ranges to 10 versions by dependency, there now 1000 times less combinations to try.

**Comment by johncblandii** [comment]
Coolio. It is running. Thx
