### ISSUE TITLE
Build succeeds but merge build fails: "fatal: Couldn't find remote ref refs/pull/34/merge"

### ISSUE THREAD

**Issue by AJRepo** [travis-ci/travis-ci#8962]
Right before a merge TravisCI reported the build as passing tests. 

But when I pressed the "Merge" button (standard merge, not squash or rebase) TravisCI errs out saying it can't find the merge and so the build test fails. 

Not sure if this is as intended for merges or if an error in TravisCI. 
 
Here's the build: 

https://travis-ci.org/dguerri/LibVirtKvm-scripts/builds/319763119?utm_source=github_status&utm_medium=notification

**Comment by BanzaiMan** [comment]
https://github.com/dguerri/LibVirtKvm-scripts/pull/34 was closed at 2017-12-21T15:41:41Z (https://api.github.com/repos/dguerri/LibVirtKvm-scripts/pulls/34) before the build started at 2017-12-21T15:52:48Z https://api.travis-ci.org/builds/319763119, so the build was not possible.
