### ISSUE TITLE
google cloud deployment builds started failing today

### ISSUE THREAD

**Issue by ggprod** [travis-ci/travis-ci#8963]
failing during the deployment phase while attempting to install the google cloud SDK

failing during tar extraction (my suspicion is the travis build VM is running out of disk space)

see https://api.travis-ci.com/v3/job/103845379/log.txt?log.token=XIrWu328M4TJ44jR2T8fBA

**Comment by ggprod** [comment]
Also, when I rerun the same build in debug build and ssh in and run the failing command:

if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl
  https://sdk.cloud.google.com | bash; fi

it completes ok

**Comment by ggprod** [comment]
I also found another issue related to the tar: write error.. perhaps this issue is related to that one (below):

https://github.com/travis-ci/travis-ci/issues/4704

**Comment by ggprod** [comment]
yes, it seems to be related to the above issues.. suppressing the output of the offending command via >/dev/null

now fix your shit!

**Comment by hibacha** [comment]
You are right.

**Comment by berryhill** [comment]
Having this exact issue, and fixed it the same way..

**Comment by jnorkus** [comment]
This is still an issue. Redirect to `/dev/null` worked like a charm!
