### ISSUE TITLE
R data.table dev tests failing

### ISSUE THREAD

**Issue by mattdowle** [travis-ci/travis-ci#8964]
cc @craigcitro @jimhester
I've seen the notice about the trusty upgrade.  Likely to do with that but might be something else.

data.table is failing travis checks in dev currently with this log : https://api.travis-ci.org/v3/job/319483990/log.txt
The .travis.yml is here:  https://github.com/Rdatatable/data.table/blob/master/.travis.yml

It works without package caching but is slow.  I saw the docs menion `sudo: false` so I tried that without luck.  See the history of the attempts on that file.

I don't really know what I'm doing at this point.  I don't really understand the difference between 'containerized'  `sudo: false` and `sudo: required` and why those relate to package caching.

Any ideas what I can try?   Thanks!  It used to work perfectly up until yesterday.

**Comment by jimhester** [comment]
Historically package caching was only available on `sudo: false` builds, but today it is available with `sudo: required` builds as well.

I don't see anything in the build log indicating why the build failed and nothing has changed in the script used in R builds as far as I am aware. This may be a bug in the regular travis build script, but in any case I don't think it is anything you can fix on your end.

**Comment by mattdowle** [comment]
Thanks @jimhester!  I reverted travis.yml back to how it was  (i.e. `sudo: required` and `cache: packages`).  That kicked off another run and it looks a bit more promising now.  Different error but a clearer one : 
` The command "sudo apt-get install -y r-cran-devtools" failed and exited with 100 during . `
https://api.travis-ci.org/v3/job/319932659/log.txt

**Comment by mattdowle** [comment]
I just restarted the build and the r-cran-devtools error has gone, but it fails with a different message. Looks like the tests are running but then get interrupted by another process running at the same time.  Could it be something like that?  Is anyone making changes to the r-travis script behind the scenes?  Is that script somewhere I can see and look at and maybe try and help? cc @jimhester 
https://api.travis-ci.org/v3/job/319932659/log.txt

**Comment by jimhester** [comment]
The script is at https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb, but nothing has changed there since october, so I think the problem likely lies elsewhere.

**Comment by mattdowle** [comment]
Thanks. Had a look through the script but nothing jumped out at me.  Are any other packages failing or is it just data.table?
The banner notice says : 
> This job ran on our Trusty environment, which has been updated on Tuesday, December 12th, 2017. Read all about this on our blog and take note that you can add group: deprecated-2017Q4 in your .travis.yml file to use the previous image version.
I haven't tried rolling back yet as I didn't want to just avoid the problem. Do you think it is likely related to this upgrade, somehow?  I looked through the release notes and didn't see any likely suspects though.

**Comment by mattdowle** [comment]
It seems to be working great again now.  Thanks!

**Comment by mattdowle** [comment]
Scratch that.  It's failing again now.  Here's the log file.  Any ideas what it might be?  Is any other package reporting fails or is it just me?
https://api.travis-ci.org/v3/job/324380695/log.txt

**Comment by jimhester** [comment]
There was a similar issue in dplyr, https://github.com/travis-ci/travis-build/commit/00b1504925203e240168e37cd3f1b69cda3b6125#r26507520

From the logs it seems like dumping the output files fails sporadically, not sure why though as it is literally just a `find -exec cat {}`.

In any case this is definitely not due to a problem with data.table in particular.

I think for the time being we should just revert the change unconditionally printing the *out files, which should fix this.

**Comment by mattdowle** [comment]
Awesome. Thanks @jimhester !
