### ISSUE TITLE
Build fails and log cut without any apparent reason

### ISSUE THREAD

**Issue by feliupe** [travis-ci/travis-ci#8965]
My client build it's failing without any apparent reason. Something to note it's that it's an linux build and that the OSX it's running ok.

I also tried to ssh and run the same build commands. It worked fine.

### Log cut (at the log bottom):
![image](https://user-images.githubusercontent.com/4684166/34297860-e24210b2-e71a-11e7-8d20-bf14ad58b772.png)
**Expected**: to run the next instructions (deploy ones)

Until 3 days ago it was working, so I don't think it would be something related to the recent update.

Here it's the `travis.yml` file:
https://gist.github.com/feliupe/bf8ff4279a642fb16c7375b5c6d008db

It has the recommend configuration in case of unexpected failures:
````
 "dist": "trusty",
  "group": "deprecated-2017Q4",
"sudo": "required"
```

**Comment by ylemkimon** [comment]
Maybe related to #8920.

**Comment by ShinyChang** [comment]
I got same issue, anyone can help on this?
I didn't specify `dist` and `group` in my yaml.

**Comment by ylemkimon** [comment]
@ShinyChang Try https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352661024

**Comment by feliupe** [comment]
Thanks @ylemkimon ! It was solved by putting `python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"` on the top of the failing script.
