### ISSUE TITLE
php-fpm examples not working

### ISSUE THREAD

**Issue by uglyoldbob** [travis-ci/travis-ci#8968]
In the documentation https://docs.travis-ci.com/user/languages/php/

There is some configuration example for php-fpm.

Here is the error message I receive
`$ sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
cp: cannot stat ‘/home/travis/.phpenv/versions/5.4/etc/php-fpm.d/www.conf.default’: No such file or directory`

https://travis-ci.org/uglyoldbob/web-admin/jobs/320293437

**Comment by uglyoldbob** [comment]
It appears that the `~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/` folder does not exist

**Comment by BanzaiMan** [comment]
Sorry to hear about this issue. It is possible that our images lack something critical. Could you help us with troubleshooting? You can read more about how here: https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

**Comment by Saw-mon-and-Natalie** [comment]
having the same issue here:

https://travis-ci.org/CiTR/djland/jobs/336008529
