### ISSUE TITLE
"autogen not found" (OK in deprecated-2017Q4 )

### ISSUE THREAD

**Issue by JamesCrook** [travis-ci/travis-ci#8970]
On 17th Dec 2017 CI builds for Audacity started reporting "Autogen not found".

The SAME GitHub commit worked earlier in the day.  The root cause appears to be that earlier in the day the config was 'falling back' as follows:

```
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1) 
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out 
W: Failed to fetch http://toolbelt.heroku.com/ubuntu/./InRelease Unexpected type excepted 21 != 5 
W: Some index files failed to download. They have been ignored, or old ones used instead. 
```

Later in the day https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  was retrieved OK, whereupon the Autogen not found error appeared.

Here are the two logs:
Working:
https://travis-ci.org/JamesCrook/audacity/builds/317702135

Failed:
https://travis-ci.org/audacity/audacity/builds/317708555
The error reported is:
```
autogen --writable test_endswap.def
/bin/bash: autogen: command not found
make[5]: *** [test_endswap.c] Error 127
```

For now we are working around the problem by using deprecated-2017Q4

**Comment by BanzaiMan** [comment]
What's responsible for providing this command?

**Comment by JamesCrook** [comment]
I'm not sure which of our steps pulls in autogen.  Possibly there is some version issue, and we sometimes get an autogen version that is in /bin/bash and sometimes not.  But that is odd, as these are builds built on the same day, so we wouldn't expect the repos to be changing.

The upgrade in 2017Q4 may be a red herring.  We seem to have a rare (random) build failure with identical builds configs and commit ids.  This new example is when running Deprecated-2017Q4.  

This one worked:
https://travis-ci.org/audacity/audacity/builds/325092341

This one failed:
https://travis-ci.org/JamesCrook/audacity/builds/325095842

The salient difference (this time) seems to be here:
The one that worked:
version: v3.3.1 https://github.com/travis-ci/worker/tree/1153e5010ef9863bf96264b75fba506109633460
instance: travis-job-aee2cf9e-224b-46f6-8a5e-9a183097ad90 travis-ci-garnet-trusty-1503972833 (via amqp)

The one that failed:
version: v3.4.0 https://github.com/travis-ci/worker/tree/ce0440bc30c289a49a9b0c21e4e1e6f7d7825101
instance: travis-job-8863066b-e46b-4a42-addc-6390b42f422b travis-ci-garnet-trusty-1503972833 (via amqp)

I'm mystified.  I don't know if these clues help with understanding the root cause.

**Comment by JamesCrook** [comment]
It's an intermittent failure, and we just re-run the job when it happens.
