### ISSUE TITLE
Gradle 4.0 and Java 9 are incompatible

### ISSUE THREAD

**Issue by dpolivaev** [travis-ci/travis-ci#8975]
Hello,

as mentioned on page https://docs.travis-ci.com/user/reference/trusty/ current default configuration for trusty includes the latest oracle jdk9 and gradle 4.0.

Unfortunately, gradle 4.0 can not work with the latest jdk 9.0.1  because of gradle bug fixed in Gradle 4.2.1, see https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457 .

Therefore currently all our builds using preinstalled gradle and JDK oraclejdk9 fail with messages like

```
$ gradle -PTestLoggingFull=true check
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine java version from '9.0.1'.
```

https://travis-ci.org/freeplane/freeplane/jobs/321066757

Could you please update the gradle version for trusty distribution so that the build works again?

Kind regards,
Dimitry Polivaev

**Comment by timofonic** [comment]
@dpolivaev @fractalwreng @MariadeAnton @BanzaiMan Is the Gradle update coming someday?

**Comment by Jonarzz** [comment]
Any update on this?
@MariadeAnton @BanzaiMan

**Comment by BanzaiMan** [comment]
I've opened https://github.com/travis-ci/travis-cookbooks/pull/967 for the next image update.

In the meantime, manual update will be necessary.

**Comment by xor-freenet** [comment]
@BanzaiMan 
> I've opened [travis-ci/travis-cookbooks#967](https://github.com/travis-ci/travis-cookbooks/pull/967) for the next image update.
> 
> In the meantime, manual update will be necessary.

How can we update Gradle manually?

Also please can you re-open this issue, the stale bot wrongly closed it?

**Comment by BanzaiMan** [comment]
Please use https://travis-ci.community for further discussion. Thanks.

**Comment by xor-freenet** [comment]
@BanzaiMan 
> Please use https://travis-ci.community for further discussion. Thanks.

Uhm did you notice that my comment was composed of two aspects, only one of which being a "howto" question, the other noting that this bug here was wrongly closed? :)
