### ISSUE TITLE
Schedule commands

### ISSUE THREAD

**Issue by Pl4gue** [travis-ci/travis-ci#8976]
Hey,
is there any feature in Travis to execute a command every `x` commits? For example, if you want to execute an extra command on every 5th build.

**Comment by BanzaiMan** [comment]
There is not. What is the use case here? You can sort of fake it by checking `$TRAVIS_BUILD_NUMBER` (cf. https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables), but this would not take builds in other branches and PR builds into consideration.

**Comment by Pl4gue** [comment]
@BanzaiMan Yes, thank you for the response, I solved it by checking the Build Number :smile:
