### ISSUE TITLE
Ruby 2.5.0 is not available on the Mac

### ISSUE THREAD

**Issue by segiddins** [travis-ci/travis-ci#8977]
See https://travis-ci.org/rubygems/rubygems/jobs/321665352#L486 for an example. Ruby 2.5 was released a few days ago, but specifying `rvm: 2.5` uses `2.5.0preview1` instead of the final released version.

**Comment by BanzaiMan** [comment]
When https://travis-ci.org/travis-ci/travis-rubies/builds/321784987 succeeds, it should be available.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/jobs/321822334#L460 and https://travis-ci.org/BanzaiMan/travis_production_test/jobs/321822335#L464 show that both `2.5` and `2.5.0` work.

Some additional work is necessary for Mac archives; cf. https://travis-ci.org/travis-ci/travis-rubies/jobs/321784992

**Comment by BanzaiMan** [comment]
2.5.0 should be available for Yosemite (10.10) and up as well.
