### ISSUE TITLE
Email notifications not sent to primary email address

### ISSUE THREAD

**Issue by luchsamapparat** [travis-ci/travis-ci#8981]
Hi!

I know that Travis uses my primary email address form GitHub. I have three addresses configured on GitHub and for some reason all notification emails are sent to the last one in the list, not to my primary one. Is this a known issue?

**Comment by BanzaiMan** [comment]
Which build notifications? (If you'd rather not share this information publicly, please close this issue and email support@travis-ci.com instead.)

**Comment by luchsamapparat** [comment]
Mails from Travis CI <builds@travis-ci.org> which tell me if the latest build has passed or not. The project is this one:
https://travis-ci.org/luchsamapparat/nim?utm_source=email&utm_medium=notification

**Comment by BanzaiMan** [comment]
The notification email for https://travis-ci.org/luchsamapparat/nim/builds/322550300 was sent to the email address associated with the git commit that triggered the build (see https://api.github.com/repos/luchsamapparat/nim/git/commits/739b6c73f0b915af8577053675748d54113dad90), as explained in https://docs.travis-ci.com/user/notifications#How-is-the-build-email-receiver-determined%3F.

If you want the notification sent to a different address, please configure the notifications accordingly.

**Comment by luchsamapparat** [comment]
Well, that makes sense. Thank you very much!
