### ISSUE TITLE
Branches page does not show previous builds for branches containing a #

### ISSUE THREAD

**Issue by aullik** [travis-ci/travis-ci#8986]
Looking at the branches page, the passed and failed builds should appear next to the existing branches. 

However when a branch name contains a Hashtag travis will not show the previous builds. 

[example travis branches page](https://travis-ci.org/aullik/TravisBugReport/branches)

[linked git repo](https://github.com/aullik/TravisBugReport)

**Comment by sakshamsaxena** [comment]
I'd like to work on this one if it's still untouched ?

**Comment by sakshamsaxena** [comment]
@aullik just realised that this same bug is reproduced with Github API too. Might as well report it to them 😄

**Comment by timofonic** [comment]
@sakshamsaxena @aullik @BanzaiMan Has it been fixed? Any plans? What GitHub Team says too?

**Comment by sakshamsaxena** [comment]
I opened a PR on this few hours ago. Waiting for review. I've not yet reported this to GitHub, but just to be clear, that was just an observation and has nothing to do with Travis. It's just a coincidence that both APIs fail when you've a branch with a pound sign.

**Comment by backspace** [comment]
Thanks for letting us know about this, @aullik, and thanks for fixing it, @sakshamsaxena! I’ve merged and deployed the change.
