### ISSUE TITLE
rake error causing job from Github to fail in Travis 

### ISSUE THREAD

**Issue by zackrt** [travis-ci/travis-ci#8987]
0.19s$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-2.4.1@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

https://github.com/zackrt/node-shopping-list-integration-tests

**Comment by zackrt** [comment]
now it works after I went into settings/general and turned ON: Build only if .travis.yml is present

**Comment by vagdevik** [comment]
In my case, I fixed the issue by using [this](https://stackoverflow.com/a/67381391/14619383).
