### ISSUE TITLE
How to fully remove travis-ci from github repo ? 

### ISSUE THREAD

**Issue by Aarbel** [travis-ci/travis-ci#8988]
Hi travis teams !

How could i remove this `required` travis-ci line on github ? We installed Jenkins an we don't want travis-ci to track our repo yet.

NOTE : in my repo settings i cleaned : 
- the webhooks of travis-ci
- the integrations of travis-ci
- the deploy keys of travis -ci 

but it doesn't remove this `require` line)

![image](https://user-images.githubusercontent.com/25119847/34456353-4478b13a-ed94-11e7-814f-1681e1f5887d.png)

Thanks a lot !

**Comment by Aarbel** [comment]
ok i found the solution :

https://help.github.com/articles/enabling-required-status-checks/

**Comment by m-sureshraj** [comment]
FWIW - This post explains how to remove travis-ci from Github in detail. You might find it helpful.

https://remarkablemark.medium.com/remove-travis-ci-from-github-7ea674784897
