### ISSUE TITLE
Support PyPy2.7 v5.10, PyPy3.5 v5.10 and PyPy2.7 v5.9

### ISSUE THREAD

**Issue by webknjaz** [travis-ci/travis-ci#8989]
v5.10 has been released this month: https://morepypy.blogspot.com.es/2017/12/pypy27-and-pypy35-v510-dual-release.html

Also, while there's support for PyPy3.5 v5.9, PyPy2.7 v5.9 is missing for some mysterious reason.

**Comment by timofonic** [comment]
@webknjaz Yes! 👍 
@BanzaiMan Are there some planned upgrade about this?

**Comment by BanzaiMan** [comment]
These should be available now.

**Comment by webknjaz** [comment]
@BanzaiMan 

```
$ http HEAD https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/pypy2.7-5.9.0.tar.bz2
HTTP/1.1 200 OK
```

```
$ http HEAD https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/pypy2.7-5.10.0.tar.bz2
HTTP/1.1 403 Forbidden
```

```
$ http HEAD https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/pypy3.5-5.10.0.tar.bz2
HTTP/1.1 403 Forbidden
```

**Comment by BanzaiMan** [comment]
There are a couple of packaging issues.

**Comment by BanzaiMan** [comment]
One problem: https://github.com/pyenv/pyenv/pull/1069

**Comment by BanzaiMan** [comment]
Once that is merged, we will finesse the build trigger and we'll have the archives.

**Comment by BanzaiMan** [comment]
Trusty archives should now be available. These versions do not support Precise, apparently.
