### ISSUE TITLE
C# 7.2 support

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [travis-ci/travis-ci#8990]
Is C# 7.2 supported on Travis?

> Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> CSC : error CS1617: Invalid option '7.2' for /langversion; must be ISO-1, ISO-2, Default, Latest or a valid version in range 1 to 7.1]

Travis.yml
```
language: csharp  
mono: none
dotnet: 2.0.0
```

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by akoeplinger** [comment]
Hey, sorry for the late reply. C#7.2 is implemented by Roslyn/csc 2.6.0 which should ship in an upcoming Mono release, likely Mono 5.10.

**Comment by geminiyellow** [comment]
```
C# support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry
dotnet-install
Installing .NET Core
```

please

**Comment by jaredcnance** [comment]
It looks like mono [5.10 was released in February and contains Roslyn 2.6.0](http://www.mono-project.com/docs/about-mono/releases/5.10.0/#tools). Is there anything I can do to help move this along?

**Comment by akoeplinger** [comment]
@jaredcnance this should be fixed now, you just need to ensure you're running Mono 5.10, e.g. by using `mono: latest` in your .travis.yml

**Comment by akoeplinger** [comment]
I just took a look at your build and you're using .NET Core instead of Mono. In that case you need to be using .NET Core SDK 2.1. Try adding `dotnet: 2.1.105` to your .travis.yml
