### ISSUE TITLE
[Bug] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 127: invalid continuation byte

### ISSUE THREAD

**Issue by Kristinita** [travis-ci/travis-ci#8993]
### 1. Summary

I have `UnicodeDecodeError` for angle brackets in Travis CI, but not in AppVeyor and [**WWTD**](https://github.com/grosser/wwtd) — Travis CI simulator.

#### 1. Local environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Python 3.6.3,
+ wwtd 1.3.0.

#### 2. .travis.yml

Valid; [**link**](https://github.com/Kristinita/SashaPythonista/blob/master/.travis.yml):

```yaml
language: python
python:
  - "3.6.3"
# command to install dependencies
install:
  - pip install chardet
  - pip install flake8
  - pip install pydocstyle
  - pip install logbook
# command to run tests
script:
  - python EricPackagesChecker.py
  - flake8 . --max-line-length=120
  - pydocstyle .

```

#### 3. Python module

Saved in UTF-8; [**link**](https://github.com/Kristinita/SashaPythonista/blob/master/EricPackagesChecker.py). [**Line 41**](https://github.com/Kristinita/SashaPythonista/blob/master/EricPackagesChecker.py#L41):

```python
if "<body>" in open(filename).read():
```

### 3. Steps to reproduce

I push changes to GitHub [**SashaPythonista**](https://github.com/Kristinita/SashaPythonista) repository.

#### 1. AppVeyor

[**Build success**](https://ci.appveyor.com/project/Kristinita/sashapythonista-7l3yk).

#### 2. wwtd

Build success:

```python
D:\SashaPythonista>wwtd
START
python EricPackagesChecker.py && flake8 . --max-line-length=120 && pydocstyle .
[2018-01-01 13:47:10.021794] ERROR: Sasha Logbook: This line(s) not contains asterisks: 'Is an error in this string?Yes', 'Саша святая? Да' in SashaExample.txt
[2018-01-01 13:47:10.024789] CRITICAL: Sasha Logbook: SashaExample2.txt save in ascii, not in windows-1251 encoding. Please, save a file in windows-1251.
[2018-01-01 13:47:10.025790] ERROR: Sasha Logbook: This line(s) not contains asterisks: 'Great?Yes' in SashaExample2.txt
SUCCESS
rm -rf .bundle
```

### 5. Actual behavior

**For** Travis CI [**I get failure**](https://travis-ci.org/Kristinita/SashaPythonista/builds/323773300):

```python
$ python EricPackagesChecker.py
Traceback (most recent call last):
  File "EricPackagesChecker.py", line 41, in <module>
    if "<body>" in open(filename).read():
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 127: invalid continuation byte
```

### 6. Not helped

1. I try to change Python version:

```yaml
python:
  - "3.6.3"
```

to:

```yaml
python:
  - "3.6"
```

or to 3.3. I get the same traceback.

Thanks.

**Comment by BanzaiMan** [comment]
https://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte

Could you try reproducing the issue with our Docker images? https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

**Comment by jwilk** [comment]
> ```python
> Traceback (most recent call last):
>   File "EricPackagesChecker.py", line 41, in <module>
>     if "<body>" in open(filename).read():
>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/codecs.py", line 321, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 127: invalid continuation byte
> ```

You tried to open a file in text mode without specifying encoding. Python uses locale encoding in such case. On Travis CI, this is UTF-8. But the file in question (`SashaExample.txt`) is not in UTF-8, so reading the file fails, as expected.
This is not a bug in Travis CI, but in your code.

**Comment by timofonic** [comment]
@jwilk What about a fallback option? It seems there are many libraries/programs able to guess text encoding quite accurately.

**Comment by Kristinita** [comment]
@BanzaiMan , @jwilk , thanks for the answers. I write a program, that needs files in Windows-1251 encoding.

If I replace `open(filename)` to `open(filename, encoding='windows-1251')`, I don't have this problem.

But for AppVeyor or Circle CI I don't need additionally add `encoding='windows-1251'`. Possibly, @timofonic reply is a nice solution?

Thanks.

**Comment by Ashish-Gupta03** [comment]
use `encoding="ISO-8859-1"`  to solve the issue.

**Comment by pallavi-das-k** [comment]
for link in links:
    try:
        html = requests.get(link).content
        unicode_str = html.decode("utf8")
        encoded_str = unicode_str.encode("ascii",'ignore')
        new_soup = BeautifulSoup(encoded_str, "html.parser")
        for val in items:
            a_text = new_soup.find(val).get_text()
            print(a_text)
            with open('ChatBot.txt', 'a',errors='ignore',encoding='utf-8') as f:
                f.write(a_text)
                f.write("\n")
                f.write("\n")
    except AttributeError:
        continue

> **It shows error like:
> UnicodeDecodeError                        Traceback (most recent call last)
> <ipython-input-12-3f3f4b5b6341> in <module>
>       2     try:
>       3         html = requests.get(link).content
> ----> 4         unicode_str = html.decode("utf8")
>       5         encoded_str = unicode_str.encode("ascii",'ignore')
>       6         new_soup = BeautifulSoup(encoded_str, "html.parser")
> 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 10: invalid continuation byte**

Please someone correct it for me
