### ISSUE TITLE
Switching from VM to Container

### ISSUE THREAD

**Issue by asturur** [travis-ci/travis-ci#8994]
I'm currently using the trusty VM for the fabricjs CI builds.

I believe i m using VM since i have this before_install script:

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgif-dev libpng-dev libjpeg8-dev libpango1.0-dev libcairo2-dev

that requires sudo.

Is there any container out there ready with those libs so i can skip the sudo apt-get install?

i need a node 4 - 6 - 8 container

Are docker container noticeably faster to start up? my current build time is little bit less than 2 minutes, i wonder if with a container will be faster

**Comment by BanzaiMan** [comment]
Those libraries are listed in the safelist. Use the `apt` addon. https://docs.travis-ci.com/user/installing-dependencies/

**Comment by asturur** [comment]
after i move to aptget addon, how i switch to containers? And also is it worth? is any faster for you or me?

i would like to use travis in the best way for the service itself too.

**Comment by BanzaiMan** [comment]
I can't give you a blanket statement as to which is better. Please read https://docs.travis-ci.com/user/reference/overview/ and experiment which works better for you.
