### ISSUE TITLE
Build jobs not showing

### ISSUE THREAD

**Issue by unional** [travis-ci/travis-ci#8995]
![image](https://user-images.githubusercontent.com/3254987/34474612-241fc862-ef36-11e7-8cc8-86eb50bad37f.png)

Upon inspecting chrome devTool, it has these errors:
```sh
[Report Only] Refused to load the font 'data:font/woff;base64,..........=' because it violates the following Content Security Policy directive: "font-src 'self' https://fonts.googleapis.com/css https://fonts.gstatic.com".
Failed to load resource: the server responded with a status of 403 ()
```
https://65f53bfdfd3d7855b8bb3bf31c0d1b7c.report-uri.com/r/default/csp/reportOnly

https://travis-ci.org/unional/global-test-harness/builds/323861653

**Comment by BanzaiMan** [comment]
I see the build log now. Do you?

**Comment by unional** [comment]
I do see them now.

**Comment by unional** [comment]
![image](https://user-images.githubusercontent.com/3254987/34580615-7a005d4c-f142-11e7-9618-7fbd2b462a3c.png)

Seeing it again
https://travis-ci.org/unional/satisfier/jobs/325166601
Then it pops up.

I think it is related to #9000
