### ISSUE TITLE
Builds slow and failing due to network issue

### ISSUE THREAD

**Issue by unional** [travis-ci/travis-ci#9000]
From https://github.com/travis-ci/travis-ci/issues/8991#issuecomment-354706845

The builds still takes quite a while to start and very slow (15 minutes+ counting from build job started):
https://travis-ci.org/unional/domture/builds/324017975

compare to 3 minutes:
https://travis-ci.org/unional/domture/builds/323482974

One good thing is the `disk quota exceeded` is gone.

EDIT: seems to also have some networking issues:

```sh
curl: (7) Failed to connect to nodejs.org port 443: Connection timed out
Binary download from https://nodejs.org/dist/v9.3.0/node-v9.3.0-linux-x64.tar.xz failed, trying source.
grep: /home/travis/.nvm/.cache/bin/node-v9.3.0-linux-x64/node-v9.3.0-linux-x64.tar.xz: No such file or directory
Provided file to checksum does not exist.
Binary download failed, trying source.
```

https://github.com/travis-ci/travis-ci/issues/8991#issuecomment-354738249

Definitely network issues:

```sh
fatal: unable to access 'https://github.com/unional/global-test-harness.git/': Failed to connect to github.com port 443: Connection timed out
```

**Comment by stefanbethke** [comment]
Me too. See:
* https://travis-ci.org/voxpupuli/librarian-puppet/jobs/324576828
* https://travis-ci.org/voxpupuli/librarian-puppet/jobs/324576862
* https://travis-ci.org/voxpupuli/librarian-puppet/jobs/324541514
* https://travis-ci.org/voxpupuli/librarian-puppet/jobs/324509527

**Comment by simlu** [comment]
Similar problems here in the last few days! Please fix!

**Comment by stefanbethke** [comment]
Builds continue to fail with network issue, tried all through the past 24 hours.

**Comment by kevmoo** [comment]
Ditto! We're seeing the same failures as you can see at the top of this log: https://travis-ci.org/voxpupuli/librarian-puppet/jobs/324576828#L405

```
removed ‘/etc/apt/sources.list.d/basho_riak.list’
Executing: /tmp/tmp.548RdBPrIi/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv
EA312927
gpg: requesting key EA312927 from hkp server keyserver.ubuntu.com
gpg: key EA312927: public key "MongoDB 3.2 Release Signing Key <packaging@mongodb.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
W: The repository 'https://packagecloud.io/computology/apt-backport/ubuntu trusty Release' does not have a Release file.
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty Release' does not have a Release file.
W: The repository 'https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty Release' does not have a Release file.
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/39x/InRelease  Unexpected type excepted 21 != 5
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/trusty/mongodb-org/3.4/InRelease  Could not connect to repo.mongodb.org:80 (54.192.16.193), connection timed out
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by mistercrunch** [comment]
Same here https://travis-ci.org/mistercrunch/superset/jobs/325210312:
```
curl: (7) Failed to connect to nodejs.org port 443: Connection timed out
Binary download from https://nodejs.org/dist/v8.8.1/node-v8.8.1.tar.xz failed, trying source.
grep: /home/travis/.nvm/.cache/src/node-v8.8.1/node-v8.8.1.tar.xz: No such file or directory
Provided file to checksum does not exist.
```

**Comment by raymondschouten** [comment]
Same here, I have to restart my builds a dozen times before it actually succeeds.

The strange this is that I have 5 concurrent builds in my build plan and that some of them (randomly) are done within a minute without any connection issues, and that others run for minutes or hours with continuously "connection timed out" or "failed to connect" errors.

**Comment by smowton** [comment]
Also seeing frequent network outages and occasionally unexplained build stalls; problem is new (or much worse) as of the new year; builds currently have maybe a 75% chance of working, which if you're testing a few configurations means a spurious failure is very likely.

**Comment by Bilge** [comment]
Seeing anywhere between 12-35% of container builds not having any WAN connectivity since around the time this issue was posted.

**Comment by timofonic** [comment]
@BanzaiMan Any results about what causes this issue? Any plans to solve it?

**Comment by cotsog** [comment]
Sorry for the troubles. We will need to look into it but in the meantime, could you try running your builds on our sudo-enabled infrastructure instead by adding the following to your .travis.yml file:

```yaml
sudo: required
```

Please let us know if the issue reproduces itself over there or not.

Thank you for your patience!

**Comment by Bilge** [comment]
The issue is not present on the sudo infrastructure.

**Comment by iriberri** [comment]
Thank you all for your patience.

We scheduled a maintenance process yesterday to replace all the NAT hosts in our container-based Linux infrastructure. We have be posting updates on this through our status page at: https://www.traviscistatus.com/incidents/rxk37q4tby3q, in case you'd like to take a further look.

I can confirm that the replacement of the new NAT hosts has been completed as of today at 05:44 AM (UTC time).

If you were using the recommended `sudo: required` workaround, could you please try routing your builds to `sudo: false` again and let us know how this goes?

Thanks again for your understanding, and don't hesitate to contact us at support@travis-ci.com if you're still experiencing issues and you'd like us to take a look at your specific case.

**Comment by kevmoo** [comment]
Things are looking much better this morning. Thank you!

**Comment by kenorb** [comment]
Related: #8507

**Comment by smowton** [comment]
@iriberri continuing to see frequent container-based builds with no WAN access. Restarting the job 3-4 times is usually good enough to get lucky and get a container with working net access.

Example of a failed build (note failure to connect to www.apache.org amongst others near the top: https://travis-ci.org/diffblue/cbmc/jobs/335160929

**Comment by AntonKrug** [comment]
My build is container-based, but that finished just fine. Then the deployment to the GitHub releases got stalled, by using the 'sudo: required' it got solved.

**Comment by Thor07** [comment]
instance: travis-job-9af4b1d7-1b9d-4181-a8a9-64f84e1471d5 travis-ci-sardonyx-xenial-1553530528-f909ac5 (via amqp)
startup: 6.666341986s
curl: (7) Failed to connect to whereami.travis-ci.com port 443: Connection timed out
Download from https://build.travis-ci.com/filter/redirect_io.rb failed. Trying https://build.travis-ci.com/filter/redirect_io.rb ...

still happens multiple times

**Comment by adityastic** [comment]
> instance: travis-job-9af4b1d7-1b9d-4181-a8a9-64f84e1471d5 travis-ci-sardonyx-xenial-1553530528-f909ac5 (via amqp)
> startup: 6.666341986s
> curl: (7) Failed to connect to whereami.travis-ci.com port 443: Connection timed out
> Download from https://build.travis-ci.com/filter/redirect_io.rb failed. Trying https://build.travis-ci.com/filter/redirect_io.rb ...
> 
> still happens multiple times

same here, @BanzaiMan please check

**Comment by bradyt** [comment]
Same.

**Comment by bradyt** [comment]
@Thor07, @adityastic, seems fixed now.

**Comment by adityastic** [comment]
> @Thor07, @adityastic, seems fixed now.

Yep, Works fine

**Comment by Thor07** [comment]
curl: (7) Failed to connect to whereami.travis-ci.com port 443: Connection timed out
Download from https://build.travis-ci.com/filter/redirect_io.rb failed. Trying https://build.travis-ci.com/filter/redirect_io.rb ...
Traceback (most recent call last):
ruby: No such file or directory -- /home/travis/filter.rb (LoadError)

**Comment by adityastic** [comment]
> curl: (7) Failed to connect to whereami.travis-ci.com port 443: Connection timed out
> Download from https://build.travis-ci.com/filter/redirect_io.rb failed. Trying https://build.travis-ci.com/filter/redirect_io.rb ...
> Traceback (most recent call last):
> ruby: No such file or directory -- /home/travis/filter.rb (LoadError)

failed for me again as well

**Comment by Thor07** [comment]
same : 
hostname: c89d494a-cf33-48d6-816a-f08a4a331691@1.worker-com-69c59c6d6b-kldc4.gce-production-1
version: v6.2.1 https://github.com/travis-ci/worker/tree/4e3246c044eb4915c2378ffacd0b3d3ed0136bba
instance: travis-job-5b6f5ab1-118e-4a33-b5eb-601624efca16 travis-ci-sardonyx-xenial-1553530528-f909ac5 (via amqp)
startup: 6.618357738s
curl: (7) Failed to connect to whereami.travis-ci.com port 443: Connection timed out

**Comment by Thor07** [comment]
@cotsog still recurring haven't tried with sudo:required though. 
hostname: c55620fd-bf73-4d75-8ddc-8856ffaceadb@1.worker-com-69c59c6d6b-4vfsl.gce-production-1
version: v6.2.1 https://github.com/travis-ci/worker/tree/4e3246c044eb4915c2378ffacd0b3d3ed0136bba
instance: travis-job-bdad15e6-79a6-48ef-bc71-626b2f721ac8 travis-ci-sardonyx-xenial-1553530528-f909ac5 (via amqp)
startup: 6.605995014s

**Comment by Thor07** [comment]
curl: (7) Failed to connect to whereami.travis-ci.com port 443: Connection timed out

**Comment by bradyt** [comment]
It's doesn't altogether the same, perhaps we should just open a new issue, and we can reference this issue as similar.

**Comment by afganhalbana** [comment]
curl: (7) Failed to connect to whereami.travis-ci.com port 443: Connection timed out me too

**Comment by bradyt** [comment]
At least we've seen how similar they are that it suggests what to title the new issue, etc.

**Comment by aerovulpe** [comment]
Same, seeing 
```
curl: (7) Failed to connect to whereami.travis-ci.com port 443: Connection timed out
```

**Comment by bradyt** [comment]
If you press "New issue", you'll see

>     # STOP! ✋
>     #
>     # DO NOT OPEN A NEW ISSUE! There's a new and better way to raise your question!!

This points to a forum, https://travis-ci.community/, where I found the following which might be related:

- https://travis-ci.community/t/travis-network-timeout-issue/4584/13
- https://www.traviscistatus.com/incidents/hl4vqb7hvv5n
