### ISSUE TITLE
"xcode8" not working

### ISSUE THREAD

**Issue by tooomm** [travis-ci/travis-ci#9001]
There is this hint shown for builds with `"osx_image": "xcode8"`:

> This job was configured to run on an OS X image that [was retired on November 28, 2017](https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce). It was routed to our [Xcode 8.3](https://docs.travis-ci.com/user/reference/osx/#Xcode-8.3) image.

Not only the linked blog post doesn't mention that the image isn't available any longer, also the [Build Environment docs](https://docs.travis-ci.com/user/reference/osx/#OS-X-Version) mention it as valid option!

`Xcode 8gm` is the last Xcode image with support for macOS 10.11 on travis...

**Comment by timofonic** [comment]
@BanzaiMan Any hopes about this and other macOS issues get solved someday?

**Comment by cotsog** [comment]
@tooomm @timofonic sorry for the confusion. We are indeed keeping our `xcode8` image for the time being. We've released a fix that should not show the banner anymore in that case. Could you confirm if it's still showing or not on your side as well? Thanks!

**Comment by tooomm** [comment]
`instance: .... travis-ci-osx10.11-xcode8-1479248015 (via amqp)`

And no banner shown anymore. Thank you for investigating @cotsog 👍

**Comment by cotsog** [comment]
@tooomm Thanks for the confirmation! :)
