### ISSUE TITLE
downloading external package repo fail in 2017Q4 

### ISSUE THREAD

**Issue by flammie** [travis-ci/travis-ci#9004]
So basically in https://github.com/flammie/omorfi the build 161 failed because of changes in the 2017Q4 things  https://travis-ci.org/flammie/omorfi/builds/324055768 and adding the deprecated2017Q4 fixes it e.g. in https://travis-ci.org/flammie/omorfi/builds/324184257. 
The problem lies somehow in fetching the external package repo or updating it here on line 458 onwards https://travis-ci.org/flammie/omorfi/builds/324055768#L458

**Comment by BanzaiMan** [comment]
I can't reproduce this problem. https://travis-ci.org/BanzaiMan/travis_production_test/builds/324641232

Could it be that some commands in `http://apertium.projectjj.com/apt/install-nightly.sh` failed silently and did not add the source? This script does not handle any error, and the user is left with no indication of intermediate failures.

**Comment by flammie** [comment]
ah, it seems to work for me too now again, maybe it was a temporary problem with networking or so. Thanks for your quick answer and sorry for the bother.
