### ISSUE TITLE
Fixture rollback in latest trusty build

### ISSUE THREAD

**Issue by annaswims** [travis-ci/travis-ci#9010]
Since the most recent Trusty update, we've had failing tests.  It's a rails project with minitest and fixtures on postgresql 9.6.  With the new infrastructure, when we insert some of our fixtures (not all) they're immediately rolled back.   Adding `group: deprecated-2017Q4` makes our problems disappear.

Here's a build where it's a problem:
https://travis-ci.com/mobi/mobi/builds/62711556

**Comment by BanzaiMan** [comment]
@annaswims I looked at the logs, but it is not clear to me where the rollback is indicated. Have you tried running the debug build to troubleshoot further?

**Comment by annaswims** [comment]
On second look, it may be a problem on our end.  
Ultimately, 
 ```ruby
Dir["test/fixtures/{**,*}/*.yml"]
```
lists the files in a different order, which should be fine, but isn't. It's looking like we may clobber earlier fixtures with later ones.
