### ISSUE TITLE
Pull Request is ignored by Travis

### ISSUE THREAD

**Issue by krig** [travis-ci/travis-ci#9015]
This pull request is strangely ignored by Travis:

https://github.com/ClusterLabs/resource-agents/pull/1083

There is no build triggered, and it doesn't appear in the Pull Request list on travis-ci.org either.

The CI is triggered for other pull requests as well as the master branch.

The only reason I can think of is that the PR was submitted from a master branch fork rather than a new branch..

**Comment by BanzaiMan** [comment]
https://travis-ci.org/ClusterLabs/resource-agents/requests

**Comment by krig** [comment]
Aha, interesting. It says "Abuse detected". Is it throttling due to too many rebuilds, or something else?

**Comment by BanzaiMan** [comment]
Could you ask the PR author @ls-zhu to log in to https://travis-ci.org, close and reopen the PR?

**Comment by krig** [comment]
OK, I will do that. Thanks!

**Comment by ls-zhu** [comment]
@BanzaiMan I have logged in  https://travis-ci.org, can not find where to close and re-open the PR. Do you mean I should close and re-open my PR https://github.com/ClusterLabs/resource-agents/pull/1083 ?.
I did that and marked as "Abuse detected", ignored. And my account is flagged as abuse. 
"The account izhu has been flagged for potential abuse. Please contact support@travis-ci.com. " Maybe this is the reason and would you please help on this, Thanks!

**Comment by timofonic** [comment]
@ls-zhu @krig @BanzaiMan Any news about this?

**Comment by BanzaiMan** [comment]
@ls-zhu You can only close the PR on GitHub.

**Comment by BanzaiMan** [comment]
I _think_ this has been addressed. Please let us know if it's not.
