### ISSUE TITLE
Github Releases problem: tag already exists

### ISSUE THREAD

**Issue by JonasCardoso** [travis-ci/travis-ci#9016]
Why travis make only first 5 jobs and rest get this error:
https://travis-ci.org/JonasCardoso/android_kernel_xiaomi_msm8996/builds/325590236
$ git tag "$(date +'%d/%m/%Y')-$(git log --format=%h -1)"
fatal: tag '05/01/2018-dab4764d' already exists
The command "git tag "$(date +'%d/%m/%Y')-$(git log --format=%h -1)"" failed and exited with 128 during .

I do not know the reason, but trevis create another task alone with the same TAG
https://travis-ci.org/JonasCardoso/android_kernel_xiaomi_msm8996/builds/325598543

I wanted all the constructs to be for the same automatic tag of mine, because it's a kind of daily build
https://github.com/JonasCardoso/android_kernel_xiaomi_msm8996/releases

Any can help me?

**Comment by BanzaiMan** [comment]
If you deploy with Releases and the tag you use does not exist, it is created for you. I am guessing that 5 jobs ran before the first deployment succeeded and the tag is thus created.

**Comment by BanzaiMan** [comment]
https://help.github.com/articles/creating-releases/

**Comment by BanzaiMan** [comment]
I don't think this is clear in our document.

**Comment by JonasCardoso** [comment]
With git tag "--force" worked all jobs on build and releasing on github

- git tag "${customkernel}-$(date +'%d/%m/%Y')" --force
