### ISSUE TITLE
We couldn't find the repository iiif-commons/manifesto

### ISSUE THREAD

**Issue by edsilv** [travis-ci/travis-ci#9018]
Hi, seeing this error for my repo:

https://github.com/iiif-commons/manifesto
https://travis-ci.org/iiif-commons/manifesto

![image](https://user-images.githubusercontent.com/1334393/34651899-eb36c148-f3ce-11e7-94fe-62e000c0b6c4.png)

**Comment by BanzaiMan** [comment]
Are your data in sync? https://travis-ci.org/profile/edsilv

**Comment by edsilv** [comment]
I believe so... Have clicked the "sync account" button - still seeing the error. The repo shows up in my list of tracked repos:

![image](https://user-images.githubusercontent.com/1334393/34655082-663564bc-f3fc-11e7-9d58-7a8772ba2a7b.png)

**Comment by BanzaiMan** [comment]
Check the case. https://travis-ci.org/IIIF-Commons/manifesto This case-sensitivity is a known issue.

**Comment by edsilv** [comment]
Yep, that was it. Thanks 👍
