### ISSUE TITLE
apt.llvm.org is very frequently unavailable

### ISSUE THREAD

**Issue by marco-c** [travis-ci/travis-ci#9019]
This breaks https://github.com/marco-c/grcov builds very often (there are 6 builds in the matrix, every time I push something at least one of them fails to install LLVM).

Are there any plans to solve this issue? E.g. providing images with newer versions of Clang pre-installed?

**Comment by BanzaiMan** [comment]
Probably a different manifestation of #9000. I'm closing this as a duplicate.

**Comment by sylvestre** [comment]
@marco-c it was caused by the cdn used by apt.llvm.org
it should be fixed now
