### ISSUE TITLE
Allow disabling build for branches without .travis.yml

### ISSUE THREAD

**Issue by lehnerpat** [travis-ci/travis-ci#902]
My situation: I have a branch in my repo which i use for integrating upstream changes (since upstream is not a git repo, that branch basically mirrors the upstream repo); naturally, that branch has no .travis.yml.

Howevery, when I push to that branch (and forget to either disable travis or add [ci skip]), travis tries to build that branch with its built-in defaults (ruby & rake, which fails of course, since it's a C++ project).

If possible, I want to avoid adding a .travis.yml to that branch so I can retain its mirror status. Therefore, it'd be neat to be able to disable building of branches without a .travis.yml -- obviously, this would have to be a setting in the web-ui since it can't be in the .travis.yml.

**Comment by magthe** [comment]
Has this been removed again?
