### ISSUE TITLE
How do I specify cache timeout as well as `cache: ccache`?

### ISSUE THREAD

**Issue by dwrobel** [travis-ci/travis-ci#9020]
As per https://docs.travis-ci.com/user/caching#Setting-the-timeout it should be possible to specify the timeout for caching however, lint tool is not accepting it (specifying timeout also causes CI to fail).

```
$ cat .travis.yml 
language: c++

cache:
  timeout: 1000
$ travis lint .travis.yml 
Warnings for .travis.yml:
[x] value for cache section is empty, dropping
[x] in cache section: unexpected key timeout, dropping
```

Adding missing ccache also didn't help:

```
$ sed -i 's/cache:/cache: ccache/' .travis.yml 
$ cat .travis.yml 
language: c++

cache: ccache
  timeout: 1000
$ travis lint .travis.yml 
Warnings for .travis.yml:
[x] syntax error: (<unknown>): mapping values are not allowed in this context at line 4 column 10
```

What is then the correct syntax for specifying caching timeout?

**Comment by BanzaiMan** [comment]
The linter is unfortunately unaware of this new key. So you can ignore the output from it.

To use it along with `ccache`:

```yaml
cache:
  ccache: true
  timeout: 1000
```
