### ISSUE TITLE
Brew fails to install Python on OSX builds.

### ISSUE THREAD

**Issue by maciejkula** [travis-ci/travis-ci#9022]
Fails with:
```
Error: python 2.7.14 is already installed
To upgrade to 2.7.14_2, run `brew upgrade python`
The command "brew install python" failed and exited with 1 during .
```
[Link to build](https://travis-ci.org/lyst/lightfm/builds/326022848), link to [`travis.yml`](https://github.com/lyst/lightfm/blob/master/.travis.yml).

The build ran just fine up to a couple of days ago.

**Comment by BanzaiMan** [comment]
The last good build on this repository is https://travis-ci.org/lyst/lightfm/builds/310634819, on 2017-12-02; it detected that [python 2.7.14 was already up to date](https://travis-ci.org/lyst/lightfm/builds/310634819#L995). Looks like there is a new version (of the formula, it seems) 2.7.14_2 is available, and `brew install` is returning a nonzero status. It is debatable that this is a correct behavior on the part of Homebrew, but your build needs to account for this possibility.

**Comment by maciejkula** [comment]
Thanks for your answer! I don't, however, issue the brew command myself -
it looks like it's being run in the initial Travis machine set up step.
Should I figure out how to override it?

**Comment by BanzaiMan** [comment]
It is invoked by https://github.com/lyst/lightfm/blob/94e59ec7e7d1340335f6674a58673f4fcccbacab/.travis.yml#L4.

**Comment by maciejkula** [comment]
Oh dear. My apologies, and thanks for your patience.
