### ISSUE TITLE
Offering Travis CI a free Skylight account

### ISSUE THREAD

**Issue by wycats** [travis-ci/travis-ci#9023]
Hello Travis CI maintainers!

We’re planning on making [Skylight](https://www.skylight.io/) free for open source projects this year and want to offer you a free beta account to use Skylight on your Rails app for free.

If you’re not already familiar with [Skylight](https://www.skylight.io/), it is a smart profiler for Ruby on Rails apps. Skylight makes it easy to pinpoint performance issues in Rails applications.

I work on a lot of open source projects myself, and in my experience it can be pretty hard to get existing contributors to work on application performance issues. Few contributors consider working on performance problems, and the ones that might be interested may not even know where to start. By making performance information more accessible, we hope to inspire potential contributors to tackle slow parts of your app, and have a good way to see if their contributions helped.

This feature is still in beta at the moment for a few reasons. First, we expect that open source apps will add a significant load to our servers, so we plan to phase in free accounts so we can make sure we scale appropriately as the new accounts come online. We also want to be able to address any issues that you as maintainers may find, as this feature required some significant changes to our existing codebase.

Adding Skylight to a Rails application is [very easy](https://www.skylight.io/support/getting-started). All you have to do is add the gem to your Gemfile and set an environment variable with your authentication token.

If you’re interested in participating or if you have any questions, you can reach us at support@skylight.io. We'd also love to feature you on our website as one of the first open source organizations using Skylight. We hope you’ll join us in helping to make performance an accessible way to contribute to an open source project.

---

*I'm not sure if opening a github issue is the ideal way of getting in touch but I didn't have better ideas. At this point, we're offering a free account to a handful of apps; each one was selected by someone on our team as an open source Rails app with a good community or an app they personally care about. This is not a broad-based message we're sending to hundreds of accounts.)*

**Comment by BanzaiMan** [comment]
Hey, @wycats! Thanks for the offer. Perhaps we can take this to our support ticketing system; do you mind sending the same email to support@travis-ci.com?

**Comment by BanzaiMan** [comment]
We got the email! We'll take it from there. <3
