### ISSUE TITLE
artifacts addon does not handle file list with octothorpes in file names

### ISSUE THREAD

**Issue by sschuberth** [travis-ci/travis-ci#9025]
See [this build](https://travis-ci.org/heremaps/oss-review-toolkit/builds/325218919) for a working upload of artifacts if the paths are hard-coded like this (the [path count is 4](https://travis-ci.org/heremaps/oss-review-toolkit/builds/325218919#L2872)):

    addons:
      artifacts:
        paths:
          - ./analyzer/build/reports/tests
          - ./downloader/build/reports/tests
          - ./scanner/build/reports/tests
          - ./utils/build/reports/tests

However, if I try to programmatically list colon-separated artifacts as via 

    addons:
      artifacts:
        paths:
          - $(find . -type f -path "./analyzer/build/reports/tests/*" | tr "\n" ":")
          - $(find . -type f -path "./downloader/build/reports/tests/*" | tr "\n" ":")
          - $(find . -type f -path "./scanner/build/reports/tests/*" | tr "\n" ":")
          - $(find . -type f -path "./utils/build/reports/tests/*" | tr "\n" ":")

as done in [this build](https://travis-ci.org/heremaps/oss-review-toolkit/builds/325226035), no artifacts are uploaded and the [path count is reported as 0](https://travis-ci.org/heremaps/oss-review-toolkit/builds/325226035#L1133).

I also tried the even more general `$(find . -type f -path "*/build/reports/tests/*" | tr "\n" ":")` which did not upload anything either, although I verified in the `script` section that the expression actually matches several files.

While doing so I realized some of the files contain the `#` character as part of their names, in case that's a problem. Because for simpler cases of using `find` like `$(find . -type f -name README.md -o -name LICENSE | tr "\n" ":")` the upload *does* work again.

As a side note, I find is misleading that `count` seems to equal the number of specified paths instead of the number of resolved paths / files.

**Comment by BanzaiMan** [comment]
I'm curious to know why you are generating files with such names.

**Comment by sschuberth** [comment]
It's not me generating these files. These are test result files as generated by the [kotlintest](https://github.com/kotlintest/kotlintest) framework.

**Comment by BanzaiMan** [comment]
It's a rather strange choice for file names.

Anyhow, we'll look into the issue, but in the meantime, I suggest using the path names without these special characters. Specifying files could also lead to long list, which will break the command (because shell cannot handle it).

**Comment by sschuberth** [comment]
The problem with using hard-coded paths, however, is that Travis will then deploy files under the *relative* name WRT the path. That is, if I have

    paths:
      - ./analyzer/build/reports/tests

and there is a file `./analyzer/build/reports/tests/index.html`, then the file will be uploaded in the root of the build as

    <bucket>/<org>/<project>/<build>/<matrix>/index.html

not as

    <bucket>/<org>/<project>/<build>/<matrix>/analyzer/build/reports/tests/index.html

This is a problem if you have multiple `index.html` files in different directories, like I do. The uploaded artifacts will then overwrite each other.

**Comment by sschuberth** [comment]
I believe this has not been solved yet and thus should be kept open.

**Comment by sschuberth** [comment]
I believe this has not been solved yet and thus should be kept open.
