### ISSUE TITLE
macOS 10.10 (xcode6.4) has length Homebrew upgrade (cache enabled)

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#9027]
Have noticed on the `xcode6.4` image (macOS 10.10) that when caching is enabled the Travis CI job spends about 3mins updating Homebrew. Given the default timeout for caching is also 3mins, it aborts restoring the cache. While the user can override this timeout, it is a bit disconcerting that the default can never work on the `xcode6.4` image. Would it be possible to do one of the following (or possibly something else)?

1. Bump the timeout (e.g. 5mins).
3. Separate the Homebrew upgrade step from the cache timeout.
2. Rebuild the `xcode6.4` image with an upgraded Homebrew.

**Comment by BanzaiMan** [comment]
Please raise your timeout https://docs.travis-ci.com/user/caching#setting-the-timeout.

Given the age of the `xcode6.4` image, it is highly unlikely that it will see another update.

**Comment by jakirkham** [comment]
Also noted that in the OP. However is it not concerning that anyone using caching on these images will be using more build time and lengthening the macOS queue by repeating a common procedure that could just as easily be done once during the image build?
