### ISSUE TITLE
Build failing, output truncated mid-line

### ISSUE THREAD

**Issue by Osmose** [travis-ci/travis-ci#9028]
Hi! Our builds are failing, and the output of the build is being truncated mid-line: https://travis-ci.org/mozilla-services/socorro/builds/326919112?utm_source=github_status&utm_medium=notification

I looked through similar looking issues (#6421, #8189, #6018) and tried several workarounds:

- Removed `set -e` from the offending build script.
- Added `python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"` to build script
- Added `sleep 2` to `after_script` in Travis config.

But none of them have resulted in un-truncated output. I'm not sure what else to try that could be a problem with our build vs a Travis issue.

**Comment by BanzaiMan** [comment]
The recent occurrence of this issue is #8973.

**Comment by Osmose** [comment]
> The recent occurrence of this issue is #8973.

Cool, thanks for the pointer!
