### ISSUE TITLE
failed to run headless chrome, other compilation issues

### ISSUE THREAD

**Issue by boneskull** [travis-ci/travis-ci#9029]
Please see [this job](https://travis-ci.org/mochajs/mocha/jobs/326937016).

This started happening--I think--when the Meltdown mitigation was occuring.  It has continued since.

Here's our [config file](https://github.com/mochajs/mocha/blob/9d7d40969ce0264c0db96e4d56cb9a9192751a0b/.travis.yml) at the time of the failure.

I'm not sure what the problem is, but removing `sudo: false` from our config has [since fixed the issue](https://travis-ci.org/mochajs/mocha/jobs/326947735).

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524

Closing as a duplicate.
