### ISSUE TITLE
WebDriverError: unknown error: Chrome failed to start: crashed

### ISSUE THREAD

**Issue by Droogans** [travis-ci/travis-ci#9030]
I had some passing test runs yesterday that suddenly fail with this error today.

The passing test run: [**continuous-integration/travis-ci/pr**](https://travis-ci.org/rackerlabs/helix-ui/builds/326476493?utm_source=github_status&utm_medium=notification).

The failing test run: [**continuous-integration/travis-ci/push**](https://travis-ci.org/rackerlabs/helix-ui/builds/326476437#L552).

Yesterday, both of those were passing. I pushed up a couple of new commits and after troubleshooting for a bit, I went back and re-triggered the "continuous-integration/travis-ci/push" job from https://github.com/rackerlabs/helix-ui/pull/113/commits/b1f4c35577f358b517cd821a7abcf273dbd58efb, expecting it to pass. However, it didn't.

Did something change today? I tried bumping my chromedriver version to 2.34, I tried [installing chrome using the docker package installation technique](https://github.com/travis-ci/travis-ci/issues/7150#issuecomment-340297038), and I'm still seeing this issue occur.

**Comment by mjgiarlo** [comment]
@Droogans see https://github.com/travis-ci/travis-ci/issues/8836

**Comment by BanzaiMan** [comment]
Closing as a duplicate.

**Comment by Droogans** [comment]
If this is a duplicate, then why was this working yesterday?

**Comment by Droogans** [comment]
Specifically, see the thread starting from yesterday: https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356004275
