### ISSUE TITLE
Add php 7.2.1, 5.6.33, 7.0.27, and 7.1.13 support.

### ISSUE THREAD

**Issue by Nenglish7** [travis-ci/travis-ci#9031]
Can you please build php 7.2.1, 5.6.33, 7.0.27, and 7.1.13 so they can be tested.

**Comment by BanzaiMan** [comment]
Compilation has been failing; e.g., https://travis-ci.org/travis-ci/php-src-builder/jobs/326899986. It is not clear to me how.

**Comment by BanzaiMan** [comment]
5.6.33 needs https://github.com/php-build/php-build/pull/491.

**Comment by BanzaiMan** [comment]
Looks like #4704.

**Comment by BanzaiMan** [comment]
These are now available with the sole exception of 5.6.33.

**Comment by Nenglish7** [comment]
Alright thanks, ill update my `.travis.yml` config file. Once php 5.6.33 is working ill close this issue.

**Comment by BanzaiMan** [comment]
5.6.33 should now be available. https://travis-ci.org/travis-ci/php-src-builder/builds/332622126
