### ISSUE TITLE
/var/ramfs Filling Up

### ISSUE THREAD

**Issue by bradyjr** [travis-ci/travis-ci#9036]
As of yesterday, we started running into an issue with what looks like Postgres logs filling up the file system. We have not had any issues with the before, but it seems to coincide with the movement of containers to ec2 instances.

As another note, we also started running into issues with the boto.cfg file at the same time, which we resolved by setting BOTO_CONFIG=/dev/null

```
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             3817196        4   3817192   1% /dev
tmpfs             765940      292    765648   1% /run
/dev/sda1       30929916 13688864  15861688  47% /
none                   4        0         4   0% /sys/fs/cgroup
none                5120        0      5120   0% /run/lock
none             3829684        0   3829684   0% /run/shm
none              102400        0    102400   0% /run/user
none              786432   786428         4 100% /var/ramfs
```

**Comment by lmwnshn** [comment]
I'm running into the same issue. I thought our case could be related to https://github.com/travis-ci/travis-ci/issues/8902 but that did not fix.

**Comment by bradyjr** [comment]
I have seen it sporadically pass, but when it did it had a different Travis worker config. 
Ones that passed had a config similar to this one:
```
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
hostname: 61774a67-8091-48d7-9db7-a95fd225c0a8@1.i-0edb78a-production-2-worker-com-ec2.travisci.net
version: v3.4.0 https://github.com/travis-ci/worker/tree/ce0440bc30c289a49a9b0c21e4e1e6f7d7825101
instance: b966364 travisci/ci-garnet:packer-1512502276-986baf0 (via amqp)
startup: 536.466832ms
```
Ones that failed had configs similar to this one:
```
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
hostname: 5dfb4713-2b79-4128-ad03-8229dc58c402@1.production-2-worker-com-a-1-gce
version: v3.3.1 https://github.com/travis-ci/worker/tree/1153e5010ef9863bf96264b75fba506109633460
instance: travis-job-3112be7b-9c07-4f12-bd83-868eefe69cd2 travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)
startup: 21.201678834s
```

**Comment by joepvd** [comment]
To increase the size of the ramdisk on the sudo enabled infrastructure, the following can be used:

```yaml
before_install: sudo mount -o remount,size=50% /var/ramfs
```

This will make around 3.7 GB of the 7.5 GB RAM available to PostgreSQL.

**Comment by bradyjr** [comment]
That worked. Thanks!
