### ISSUE TITLE
Xenial builds taking well over 30 minutes to start

### ISSUE THREAD

**Issue by onyxdevteam** [travis-ci/travis-ci#9038]
Hello. I have an application that is meant to be tested on as recent an Ubuntu version as possible (in this case, Xenial). I found that if I specify the dist to be Xenial, it does work (even though it's not documented?), and it works well. The only problem is that the builds take over 30 minutes to start each one, even though earlier they were working no problem. If more info is needed, please let me know!

**Comment by BanzaiMan** [comment]
Our Xenial support is undocumented, experimental, and unstable at this time. While we appreciate your report, there are too many moving parts to provide meaningful end-user support.

**Comment by onyxdevteam** [comment]
Thanks for the quick reply and straightforward answer. Is there any plan to support it in the future? Also, just out of curiosity, do the Xenial tests run on the same hardware as the Mac OS X tets? It seems like when there is a large backlog of OS X jobs, the Xenial builds take longer to boot, compared to when there is not that many backlogged jobs. Also, I just want to thank you guys for offering Travis CI free and unlimited for open source projects, rather than limiting resources and having paid open source plans.

**Comment by BanzaiMan** [comment]
Of course! We are working on bringing Xenial support, indeed. Which is why some of the testing is happening in production (and users have accidental access to it). Xenial is running on Linux, and is separate from Mac builds.

**Comment by onyxdevteam** [comment]
Ah, thanks for clearing everything up. Hope to see (full, official) Xenial support soon and look to a better development process by utilizing Travis!

Thanks,
- Onyx Dev

**Comment by BanzaiMan** [comment]
With that clarification out of the way, I'm closing this issue now. If it is ready for public testing, we'll be sure to announce it on our blog. https://blog.travis-ci.com/
