### ISSUE TITLE
Travis-ci badge not updating

### ISSUE THREAD

**Issue by apquinit** [travis-ci/travis-ci#9039]
Hello, our organization's travis badge is not updating.
The current status is still "unknown" even though builds have passed since yesterday.
https://github.com/intelora/core
https://travis-ci.org/intelora/core

**Comment by BanzaiMan** [comment]
This repository was not configured to run branch builds, until https://travis-ci.org/intelora/core/builds/327678098. See https://travis-ci.org/intelora/core/requests
