### ISSUE TITLE
Can not connect to localhost on container-based linux instance

### ISSUE THREAD

**Issue by aarzilli** [travis-ci/travis-ci#9041]
The tests on [this project](http://github.com/derekparker/delve) are currently failing systematically on container-based linux instances because the program can not connect to: https://travis-ci.org/derekparker/delve/jobs/327613416 notice the line saying `dialing:dial tcp 127.0.0.1:40573: getsockopt: connection refused`, that shouldn't happen. Presumably the same problem is causing the tests to become stuck later on.

Running with `sudo: required` doesn't have this problem, is this a bug in Travis-CI that will be fixed or should we permanently switch to VMs for linux?

**Comment by BanzaiMan** [comment]
What process is supposed to be listening on this port? And is it running?

**Comment by aarzilli** [comment]
Same process that's calling connect.

**Comment by asymmetric** [comment]
Having the [same issue](https://travis-ci.org/kinvolk/habitat-operator/jobs/332737468#L591), but in our case with `sudo: required`.
