### ISSUE TITLE
Caching is too early

### ISSUE THREAD

**Issue by rhwood** [travis-ci/travis-ci#9042]
It seems that the cache (when used) is created before the ```after_success``` (and maybe other ```after_*``` steps) are run, such that anything downloaded in the ```after_success``` stage cannot be cached.

In my use case, I am using maven to build and deploy a site (documentation, build reports, etc) in the ```after_success``` stage, but am downloading all the maven dependencies needed for that in that stage, since they are not used elsewhere. Creating the cache after the ```after_*``` steps are run would likely reduce the resources needed to build.

**Comment by BanzaiMan** [comment]
Test for `$TRAVIS_TEST_RESULT` in the `before_cache` step to accomplish what you are after.

```yaml
before_cache:
  - |
    if [[ $TRAVIS_TEST_RESULT = 0 ]]; then
      echo "yes!"
    fi
```

**Comment by rhwood** [comment]
How does that test delay caching until after another phase?

Per https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle, caching is *before* the ```after_success``` or ```after_failure``` states. This is a request to move the caching to *after* those states.

**Comment by BanzaiMan** [comment]
If you download the maven dependencies and deploy the site in `before_cache` as described above, your personal `after_success` step happens before caching, right? You just wouldn't have any `after_success`.

Or did I misunderstand your request?

**Comment by rhwood** [comment]
In my immediate case, I can take what I am doing in ```after_success``` and make it a conditional action in ```before_cache```.

I am requesting that Travis CI consider moving the execution of the ```before_cache``` and ```cache``` phases to after ```after_script``` in [stages.rb](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/stages.rb) (if that is where phase order is controlled) so that users who have actions that might benefit from caching in the after_success|failure|script or *deploy phases can use those phases instead of shoving them all into a script run by the ```before_cache``` phase.

Put another way, it seems strange that the build order is (at a high level) "extract cache, install, build, cache, deal with build success/failure, deploy" when the ordering I expected was "extract cache, install, build, deal with build success/failure, deploy, cache", that is cache management is outside install, build, deploy, not interleaved within it.

**Comment by BanzaiMan** [comment]
Caching after these `after_*` contaminates the cache with things which are not related to the build itself. The very reason that you are asking to swap the stages is precisely the reason that they shouldn't be.

I'm opening to further discussion, so I'm reopening this, but do keep the current order in mind, and that swapping could lead to potential problems to existing builds that depend on it.

**Comment by carlthome** [comment]
What if we could have a `travis_cache` command that we could run whenever we want to checkpoint the current build state?

My `install:` is very slow and I'd like to cache that regardless of whether `script:` succeeds or not because the install has a lot of compiled objects that could be reused between jobs.

I guess there's a better way (defining a cache job and running that once before all the other jobs in the build matrix?).

**Comment by BanzaiMan** [comment]
Caching should take place whether or not `script` succeeds.

**Comment by carlthome** [comment]
Sorry, I was mistaken as my Bazel install defaulted to `$HOME/.cache/bazel` which didn't seem to be detected by the cache despite having set the proper directory in the `cache:` directive. Changing Bazel's output base to residing in $TRAVIS_BUILD_DIR made caching work as expected.
