### ISSUE TITLE
Build cache sometimes not shared across stages

### ISSUE THREAD

**Issue by torokati44** [travis-ci/travis-ci#9043]
Consider two of my previous builds: [#71](https://travis-ci.org/torokati44/inet/builds/327430026) and [#90](https://travis-ci.org/torokati44/inet/builds/327633606)

Each of them consists of two logical stages, with the second one (`Fingerprints`) already split in two, hoping to work around the very problem I'm describing here (semi-successfully).
Only the `TARGET_PLATFORM=linux` case is interesting now.

The difference between the `.travis.yml` file of these two builds can be seen [here](https://github.com/torokati44/inet/compare/0af4696...5f897573f069ddf4ee92730f9132d0af8324a420#diff-354f30a63fb0907d4ad57269548329e3). It is very minor, mostly just formatting.

In build 71, the cache for the `MODE=release` job is carried from the `Test` stage to the `Fingerprints-release` stage. Similarly, from the `MODE=debug` job to the `Fingerprints-debug`. I verified this by looking at the cache key (hash) in the `cache.1` step of each job. This is the behavior I expected.

**In build 90 however, all four cache key hashes are different, making the last job time out. What causes this?** This seems completely illogical to me. I took care to make the set of environment variables the same for the corresponding jobs in the two stages in each build.

I suspect that it is caused by the different order, and the different amount of spaces between the `VAR=val` parts of the `env:` lines. I think the assignments should be "normalized" before hashing, so the formatting and the order doesn't matter. Some care should be taken that if the assigned variables refer to each other, maybe their order should be preserved?

p.s.: Please excuse the meaningless and silly commit messages, I got frustrated.

**Comment by torokati44** [comment]
Yup, confirmed by [#91](https://travis-ci.org/torokati44/inet/jobs/327698975). Just removing a couple of seemingly insignificant spaces from `.travis.yml` makes the cache key hashes match again. This makes the configuration very fragile. :(

**Comment by BanzaiMan** [comment]
It is true that we do not normalize environment variables when computing cache names. They are simply passed to SHA256 digest function verbatim, resulting in the behavior you observed.

**Comment by BanzaiMan** [comment]
While I agree that this is brittle, providing more intelligent cache name computation is a little more complicated (as our app needs to understand all the possible ways the environment variables can be defined).

Note that we also require that environment variable values match exactly when allowing jobs to fail.

The caching documentation can and should be improved, but I am afraid we will not be looking at improving this in the near future.

**Comment by torokati44** [comment]
Thank you for your clarification.
Having a way to define a custom cache key (overriding the one computed by default) would also solve this. In fact, it would be even better, because in some cases it is desirable to have a shared cache even if some environment variables have different values.
