### ISSUE TITLE
Docker image used by osx

### ISSUE THREAD

**Issue by hsiaoyi0504** [travis-ci/travis-ci#9044]
Hi, I am trying to run some kind of troubleshooting for my repo.

I saw some issues in the past:
https://github.com/travis-ci/travis-ci/issues/2114
https://github.com/travis-ci/travis-ci/issues/3442

And one of the option mentioned by other people is to use docker images
https://hub.docker.com/u/travisci/ used by Travis
However, it looks that there is no docker image for OSX, or maybe I am wrong?

Is is possible to provide docker image for OSX?

**Comment by BanzaiMan** [comment]
We do not use Docker for our macOS virtualization, and unfortunately the images we do use are too large to be shared.
