### ISSUE TITLE
Ability to wait for dockerhub build before building on Travis

### ISSUE THREAD

**Issue by ericcurtin** [travis-ci/travis-ci#9046]
I keep my dockerfiles used for the builds in the same repo as my project. When I push to github both my docker images (on dockerhub) and Travis CI build simultaneously. This causes build failures as my PRs can be dependant on the docker image building finishing first.

Could we add a feature that Travis CI waits for dockerhub to finish building first?

**Comment by BanzaiMan** [comment]
By this, I assume that Docker hub starts building your Docker image independently of any Travis CI build.

The builds on any other service, including Docker hub, is not something we can control, I'm afraid.

Instead, what you can try is one of two things:

1. Disable ranch and PR builds on Travis, but trigger one via API at the end of the build on Docker hub.
1. Disable builds on Docker hub, and build your Docker image on Travis in the beginning of your build, push the image to Docker hub, then use that image.

Which one is more desirable depends on your requirements and taste.

**Comment by ericcurtin** [comment]
You know what it's likely dockerhub have a REST API I could use to script this. Might be able to script it manually for the Travis CI builds

**Comment by BanzaiMan** [comment]
Sounds good. I'm closing this now.
