### ISSUE TITLE
My Travis deploy is failing

### ISSUE THREAD

**Issue by UtkarshVerma** [travis-ci/travis-ci#9047]
I want to deploy my hugo site using travis. This error happens:
https://travis-ci.org/UtkarshVerma/UtkarshVerma.github.io/builds/327815416

This is the link to my repo: https://github.com/UtkarshVerma/UtkarshVerma.github.io

Please help me ASAP since I have a deadline to publish a post to this blog.

**Comment by BanzaiMan** [comment]
According to the documentation, `local_dir` should be relative to the build directory, so `${TRAIS_BUILD_DIR}/public` is incorrect. https://github.com/UtkarshVerma/UtkarshVerma.github.io/blob/b623f0f0b342f650ef1574efbde439993222e6e1/.travis.yml#L17

**Comment by utzig** [comment]
Why was it working before?

**Comment by UtkarshVerma** [comment]
Yes it was working before

**Comment by BanzaiMan** [comment]
Either the previous behavior was a bug, or the present documentation is a bug. Either way, dropping `${TRAVIS_BUILD_DIR}` should fix the issue.

**Comment by utzig** [comment]
Thanks, just tried with relative dir and it works now!

**Comment by jfrej** [comment]
This changed a day ago in this PR https://github.com/travis-ci/dpl/pull/719
Doc update here:
https://github.com/travis-ci/docs-travis-ci-com/commit/6eb6a9390a8441d4bd6588a5c9bdf89b6158bafc#diff-6c7d1ade9d9ff1ac77efbb831400f843R46

Also looks like `local_dir` changed to `local-dir`

**Comment by BanzaiMan** [comment]
We normalize the options, so either `local_dir` or `local-dir` works.

**Comment by utzig** [comment]
local_dir is still working for me now, but nice to have a heads up if it breaks again!

**Comment by UtkarshVerma** [comment]
Thanks. Will check it out and tell the results

**Comment by webknjaz** [comment]
@utzig it won't break. The previous doc (written not by me) was suggesting that the user should use absolute path, while I always treated it as relative. Also during refactoring I needed to explicitly calculate absolute path from relative in dpl internally and I couldn't reliably guess which one was supplied.
Additionally, I think it's incorrect to force user to pre-calculate and supply an absolute path, because it doesn't matter where in the fs the project is located and it shouldn't let user reference external dirs.

**Comment by DavidAntliff** [comment]
For anyone else coming across this problem but still having trouble: if your `script:` section performs a `cd somedir` then the `local-dir`is relative to this, not the build directory. This means that `local-dir` isn't necessarily relative to the build directory, it's relative to wherever your build script ends up, which is arbitrary.

**Comment by webknjaz** [comment]
Wow, that's a curious side-effect. It should probably be fixed.

**Comment by webknjaz** [comment]
@DavidAntliff this behaviour has been fixed by #740

**Comment by DavidAntliff** [comment]
@webknjaz thank you. However I'm not sure what exactly I need to put in `.travis.yml` now. I just tried reverting to the full relative path from my build directory but I think it's still affected by the `cd doc` in the `script:` section.

https://github.com/DavidAntliff/esp32-ds18b20/commit/d23cf50935c951b9b4f0b3f9540f1ecf3ac19a13

Do I need to do this as well?

```
before_deploy:
- cd $TRAVIS_BUILD_DIR
```

**Comment by BanzaiMan** [comment]
@DavidAntliff It's not released yet. You can wait until tomorrow, or use `edge: true`:

```yaml
deploy:
  provider: pages
  edge: true
  # rest
```

**Comment by webknjaz** [comment]
Or add that `before_deploy`, but also temporarily

**Comment by DavidAntliff** [comment]
Ah, sorry, I "jumped the gun" - I'll try again tomorrow. Thanks.

**Comment by DavidAntliff** [comment]
Seems to be working now - thank you.
