### ISSUE TITLE
Github release name

### ISSUE THREAD

**Issue by JonasCardoso** [travis-ci/travis-ci#9052]
Is there any way I can manipulate the release name in deploy to github? I searched the environment variables and found nothing.

https://docs.travis-ci.com/user/environment-variables/
https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by Monkeyboy2805** [comment]
https://docs.travis-ci.com/user/deployment/releases/ any help?

**Comment by JonasCardoso** [comment]
There is nothing about it in this article

**Comment by BanzaiMan** [comment]
This can be made more explicit in https://docs.travis-ci.com/user/deployment/releases/#Advanced-options:

> Options from `.travis.yml` are passed through to Octokit API, so you can use any valid Octokit option.

a relevant one being `name`.
