### ISSUE TITLE
Can't find any pages to explain how to [see description]

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#9054]
I want to be able to modify a file and commit it to github during the build if a certain condition is met.
I can only really find stuff about releases. Could you help me here?

**Comment by BanzaiMan** [comment]
Can you accomplish this in `before_deploy`? I am not sure if that's what you're after.

**Comment by Monkeyboy2805** [comment]
I'll have a look.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan Ok. So, basically, for example, if I update my travis.yml at LolexOrg/Lolex-Tools to update the DJANGO_VERSION, and I want to update /project/old/ver.py for example to update that to a certain amount bigger in the CI build then commit it to github an push, securing my password and all that lot. I'm not entirely sure how to do this TBH.

**Comment by BanzaiMan** [comment]
Hmm. So, you want to update `.travis.yml` for the LolexOrg/Lolex-Tools repository in such a way that, during the build the following happens:

1. Updates `DJANGO_VERSION`
1. Update `project/old/ver.py`
1. Creates a commit, and pushes this to GitHub

And all of this before triggering deployment with the Pages provider.

Is that accurate?

The first 2 tasks can be accomplished with any of standard text editing utilities (e.g., `sed`, `awk`, `perl`).

Configuring `git` on the fly and pushing to GitHub is also straightforward (see https://github.com/travis-ci/apt-package-whitelist/blob/dd0f54b19c599f62aeb3a8a35a6db031a2a28e3b/make_pr.sh#L113-L153 for an example); simply set up user name, email and GitHub credentials and push the commit.

**Comment by Monkeyboy2805** [comment]
OK, I'll have a look.

**Comment by Monkeyboy2805** [comment]
Will this not ask for an interaction for the password on push though?

**Comment by Monkeyboy2805** [comment]
@BanzaiMan Don't s'pose you know why this isn't working?

https://travis-ci.org/LolexOrg/Lolex-Tools/builds/336084657

**Comment by BanzaiMan** [comment]
@Monkeyboy2805 https://github.com/LolexOrg/Lolex-Tools/blob/d7990bdeeda1b2ef4f685726f20c6cb36e9cccf7/.travis.yml is invalid. This should actually be rejected, but due to a current bug, we are running the build with default configuration (with `language: ruby`, etc.); the build is naturally failing because your repo expects to use Python.

We will look into the bug (so that the request will be rejected).

In the mean time, please correct the YAML file.

Thanks.

**Comment by Monkeyboy2805** [comment]
Thanks, it's not quite done yet anyway, I'm not familiar with OAuth Tokens and stuff so it wouldn't have worked anyway.

**Comment by Monkeyboy2805** [comment]
Got somewhere but it's not authenticating properly:

https://travis-ci.org/LolexOrg/Lolex-Tools/builds/336577356 (using protected password variable)

https://travis-ci.org/LolexOrg/Lolex-Tools/builds/336576395 (using generated oauth token as protected variable)

I don't really have much expertise in this kind of thing so sorry if I appear to be a little slow here. :P 
All other parts work so I'm not entirely sure what is wrong with the auth thing

**Comment by Monkeyboy2805** [comment]
Okay solved. @BanzaiMan Sorry about the pestering.
For anybody who's wondering, look at https://stackoverflow.com/questions/18027115/committing-via-travis-ci-failing/18029286 first answer.
Also feel free to look at my example ($token is a secure variable under travis as obviously you don't want the access key public) @ https://github.com/LolexOrg/Lolex-Tools/blob/a96cd2ff1096f2f20ea912469a1abd8f20529a35/.travis.yml

**Comment by Monkeyboy2805** [comment]
Closing now. Thanks.

**Comment by Monkeyboy2805** [comment]
Or maybe not. Build after automated commit fails due to "everything being up to date". @BanzaiMan Any way I can solve this?

**Comment by Monkeyboy2805** [comment]
But it's fine for now

**Comment by Monkeyboy2805** [comment]
Oh, EVERY build fails :P

**Comment by Monkeyboy2805** [comment]
STOOPID

**Comment by BanzaiMan** [comment]
Which `git`-controlled files are supposed to be updated during the build? If there's none, you can't create a new commit.

Alternatively, you may try passing `--allow-empty` to `git commit`, so that you will have a commit regardless.

**Comment by Monkeyboy2805** [comment]
It's fine, I've fixed this. I just move it to the actual CI file. That way I won't get dud commits when I put this into production.

**Comment by Monkeyboy2805** [comment]
Okay, branch thing fixed, commit thing fixed so it's cool. @BanzaiMan Thanks.

**Comment by BanzaiMan** [comment]
Sweet!
