### ISSUE TITLE
Process seems to be killed without reason nor error message

### ISSUE THREAD

**Issue by antocuni** [travis-ci/travis-ci#9057]
Consider this [build](https://travis-ci.org/antocuni/pypy-wheels/builds/328211901), and in particular this [job](https://travis-ci.org/antocuni/pypy-wheels/jobs/328211905#L474): at line 474, travis starts `./scripts/run.sh`.
The content of `run.sh` is available [here](https://github.com/antocuni/pypy-wheels/blob/master/scripts/run.sh), but it boils down to this:
```
echo "RUNNING DOCKER"
docker run -e "PYPY" -it --rm -v `pwd`:/pypy-wheels pypywheels/ubuntu14.04:$TAG /pypy-wheels/scripts/build_wheels.sh ubuntu
STATUS=$?
echo "docker run exit status: $STATUS"
echo "end of run.sh"
exit $STATUS
```

as you can see from the log, `docker run` starts but never ends; moreover, it seems that the entire `run.sh` is killed, because it never prints `docker run exit status:`. Finally, travis itself doesn't print *anything* at all regarding the exit status of the script.

The [next line](https://travis-ci.org/antocuni/pypy-wheels/jobs/328211905#L547) says:
```
The command "./scripts/clone-gh-pages.sh" exited with 0.
```

but note that travis never printed anything anything about *starting* `clone-gh-pages.sh`. So, whatever it is happening inside `run.sh`, it definitely confuses travis enough that it messes up the log.

Note that this seems to happen randomly: all the other jobs of the [build](https://travis-ci.org/antocuni/pypy-wheels/builds/328211901) worked well. And if you look at build history, you can see that the build fails every other time, always for the same reason.

**Comment by BanzaiMan** [comment]
Interesting. A more plausible explanation is that some portions of the logs are missing here. The command `./scripts/run.sh` finished, and the job went on to the next step, and the logs from that (`./scripts/clone-gh-pages.sh`) is partially visible. I wonder if the issue persists if you try again. (Try triggering a manual build so that we can keep a record of this failure.)

**Comment by antocuni** [comment]
I have tried it several times: most of the time it passes, but approximately 1 every 5 or 6 times. All the jobs of the build do the same, and every now and then one fails (not always the same).
I don't think that it's simply a truncation of the log: the next step fails because it cannot find the wheelhouse directory, which should be created by run.sh
