### ISSUE TITLE
Regression in running kcov on Travis, setting personality fails

### ISSUE THREAD

**Issue by Rantanen** [travis-ci/travis-ci#9061]
I'm using `kcov` for gathering code coverage stats on a Rust/C++ project. Previously this worked just fine. Within the last few days `kcov` has stopped working, citing the following error:

```
Can't set personality: Operation not permitted
kcov: error: Can't start/attach to /home/travis/build/Rantanen/intercom/target/debug/lib-dea761de4db6d1cb
```

When I noted the issue, I wasn't sure whether this was caused by my changes or something else so I decided to re-build an old commit that previously succeeded. The re-build resulted in the error:
https://travis-ci.org/Rantanen/intercom/builds/326461015

An example of a successful build: https://travis-ci.org/Rantanen/intercom/builds/326076407

**Note, as I'm using `kcov` in `after_script`, the builds themselves are successful despite `kcov` failing to execute. You can see the errors by checking the very end of the log.**

I diff'd the start of the log and in addition to the various build/job IDs being different, the only other change seemed to be the kernel.

- Successful: `Runtime kernel version: 4.9.6-040906-generic` (travis-build: `af4b84614`)
- Failing: `Runtime kernel version: 4.14.12-041412-generic` (travis-build: `d08e1022d`)

**Comment by Rantanen** [comment]
The only change to `kcov` master within the last week involves location of help files. This seems very unlikely to cause the issue. The error message seems to be related to docker's security options.

https://github.com/SimonKagstrom/kcov/issues/151

The issue is reproducible in the docker image as well. Compiling `kcov` and running `./kcov out ./kcov` will result in the `Can't set personality: Operation not permitted` error. Launching the docker image with the unconfined seccomp results in kcov succeeding like it did before.

Nothing has changed in the way Travis runs the docker images within the last week?

**Comment by ilammy** [comment]
To support kcov's innocence, I'm using [a pinned kcov version (v34)][1] for my project. The build [was fine eight days ago][2], but it [started failing recently][3], with the same version of kcov.

I'd say the possible culprit are some new security options for Docker (like `--security-opt seccomp=unconfined` mentioned above [and elsewhere][4]). The error messages and personality(2) syscall usage by kcov line up too neatly. 

[1]: https://github.com/ilammy/sabre/blob/e17af9c4d7a41b226df03e9ebf0ebabec0f8e7c0/tools/install-kcov#L20
[2]: https://travis-ci.org/ilammy/sabre/builds/325491523
[3]: https://travis-ci.org/ilammy/sabre/builds/328401102
[4]: https://github.com/moby/moby/issues/22801

**Comment by npostavs** [comment]
I've hit the same problem. I have a daily "cron" job building latest Emacs version, and it has started failing recently with error:
```
Warning: Your system has a gap between BSS and the
heap (3110968 bytes).  This usually means that exec-shield
or something similar is in effect.  The dump may
fail because of this.  See the section about
exec-shield in etc/PROBLEMS for more information.
**************************************************
make[1]: *** [bootstrap-emacs] Segmentation fault (core dumped)
```

The [first failing build from 4 days ago](https://travis-ci.org/npostavs/emacs-travis/jobs/327431244) says `Runtime kernel version: 4.14.12-041412-generic`, while the [last successful build from 6 days ago](https://travis-ci.org/npostavs/emacs-travis/jobs/326570754) says `Runtime kernel version: 4.4.0-101-generic`.

I confirmed the `personality` system call (which the Emacs uses when building) appears to be failing. 
[try-personality.c](https://github.com/npostavs/emacs-travis/blob/aslr-check/try-personality.c) prints 
```
personality: Operation not permitted
failed to enable ADDR_NO_RANDOMIZE (FFFFFFFF)
```

https://travis-ci.org/npostavs/emacs-travis/builds/328828911

**Comment by CAD97** [comment]
I can confirm that the sudo-enabled environment does not have this issue.

This means that setting `sudo: true` works as a workaround.

**Comment by BanzaiMan** [comment]
Thanks for the updates, everyone. I think this is a recent change in response to Meltdown. https://blog.travis-ci.com/2018-01-08-travis-response-meltdown-spectre

Please use `sudo: required` if you encounter this error.

**Comment by jonhoo** [comment]
@BanzaiMan I think this will necessarily affect every project that wants to get code coverage (because they all need to disable ASLR). Seems unsustainable to tell them all to use `sudo: required` in the long run :/

**Comment by ilammy** [comment]
@jonhoo Every project which uses _kcov-like_ approach for code coverage (logging execution hits by inserting breakpoints). It's definitely possible to measure coverage without disabling ASLR: either by instrumenting the compiler (gcov-like), or by compensating for ASLR when computing addresses for breakpoint insertion.
