### ISSUE TITLE
Could not find .travis.yml, using standard configuration.

### ISSUE THREAD

**Issue by GOVINDDIXIT** [travis-ci/travis-ci#9064]
How to fix this
Will .travis.yml should be added, where to add?

![iss](https://user-images.githubusercontent.com/32304546/34909824-cb576a58-f8ce-11e7-98be-c4be37af0af7.PNG)

**Comment by BanzaiMan** [comment]
Have you read our Getting Started Guide? https://docs.travis-ci.com/user/getting-started#To-get-started-with-Travis-CI

If `.travis.yml` exists in the root of your repo *and* not working, please let us know.

**Comment by GOVINDDIXIT** [comment]
It is present but which is the root folder,I am a beginner
![tr](https://user-images.githubusercontent.com/32304546/34909969-04643f76-f8d2-11e7-816c-34f7cd10e73b.PNG)

**Comment by BanzaiMan** [comment]
Did you resolve this issue? If not, a URL to the repo or the build failure above is more useful than screen shots without any clue.

**Comment by GOVINDDIXIT** [comment]
https://travis-ci.org/addy-org/Addy-Android/builds/328550481?utm_source=github_status&utm_medium=notification

**Comment by GOVINDDIXIT** [comment]
Sorry BanzaiMan I forget to tell ,Issue is solved now
