### ISSUE TITLE
Cannot install sdl2-dev package due to missing depends in repository

### ISSUE THREAD

**Issue by AMDmi3** [travis-ci/travis-ci#9065]
Trying to install `sdl2-dev` package with `sudo apt-get install libsdl2-dev results with failure:

```
$ sudo apt-get install libsdl2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libsdl2-dev : Depends: libegl1-mesa-dev
               Depends: libgles2-mesa-dev
E: Unable to correct problems, you have held broken packages.
```

Reproducible with this simple `.travis.yml`:

```
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install libsdl2-dev
script:
  - echo
```

Repository to demonstrate the problem: https://github.com/AMDmi3/travis-sdl2-bug
Travis failure: https://travis-ci.org/AMDmi3/travis-sdl2-bug

**Comment by BanzaiMan** [comment]
Did you try installing those missing dependencies, as the error message indicated?

**Comment by AMDmi3** [comment]
Why would I install them while I only need `sdl2-dev`, and all its depends should be pulled automatically? Also I forgot to mrntion that there was no such problem in the previous versions of Trusty images.

**Comment by BanzaiMan** [comment]
I wonder if it is due to newer `dpkg` or another utility. Was adding these dependencies to `apt-get install` helpful?

**Comment by AMDmi3** [comment]
> Was adding these dependencies to apt-get install helpful?

Yes: https://travis-ci.org/libSDL2pp/libSDL2pp/jobs/332838573

**Comment by akien-mga** [comment]
For the reference, this issue is still not fixed. Installing dependencies explicitly is a valid workaround, but that doesn't solve the regression for the many users who might not know how to debug apt's cryptic "you have held broken packages" message.
