### ISSUE TITLE
Question: TeX Live repository used by the build enviroment for the R language

### ISSUE THREAD

**Issue by asr** [travis-ci/travis-ci#9066]
After choosing the R language as my build environment

```
language: r
```

Travis starts the installation of TeX Live using

```
$ curl -fLo /tmp/texlive.tar.gz https://github.com/jimhester/ubuntu-bin/releases/download/latest/texlive.tar.gz
```

After visiting the [above](https://github.com/jimhester/ubuntu-bin) repository, I saw it is a fork (43 commits behind) of https://github.com/yihui/travis-bin.

Why is Travis using this fork instead of the original repository?

Note: I didn't get any answer when I asked the same question [here]( https://stackoverflow.com/questions/48031423/tex-live-repository-used-by-the-build-enviroment-for-the-r-language).

**Comment by BanzaiMan** [comment]
Please mention @craigcitro and @jimhester for R inquiries, as indicated in the build log. Thank you.

**Comment by jimhester** [comment]
Using a fork gives us a stable codebase, allows us to deploy the binaries to a different location and lets us update it as needed. Is there some feature from the upstream repository you think is missing?

**Comment by asr** [comment]
> Is there some feature from the upstream repository you think is missing?

No really. I asked just out of curiosity. Thanks!
