### ISSUE TITLE
No space left on device during rsync -az ${TRAVIS_BUILD_DIR}/ ...

### ISSUE THREAD

**Issue by markus-wa** [travis-ci/travis-ci#9068]
My build keeps getting "No space left on device" errors recently.
Example: https://travis-ci.org/markus-wa/demoinfocs-golang/jobs/322983188#L446

The job requires some test data that is close to 2.5 GB, is this too much? This used to work fine for a while now.

PS: I couldn't find any official limit on the disk usage but saw 20 GB mentioned several times. Is that the case?

**Comment by BanzaiMan** [comment]
Your builds are running on containers, and therefore their resources are shared with other jobs. Try moving to GCE with `sudo: required`.

**Comment by markus-wa** [comment]
It seems like that did the trick.

Cheers!
