### ISSUE TITLE
Support limiting matrix rows to branch builds, avoiding pr builds

### ISSUE THREAD

**Issue by iphydf** [travis-ci/travis-ci#9071]
Recently osx has become a real problem, since we need to wait 3+ hours for a runner to become available. Our osx builds almost never break, so to reduce turnover time for pull requests, we'd like to selectively build matrix rows for them.

So, we would build only 2 of the rows for pull requests, which would catch the most likely issues, and then once merged, do a full post-submit build on the branch. Combined with Cron, we could even say to only build pull requests and then only do a nightly build of the master branch with more time consuming matrix rows such as the osx one.

**Comment by BanzaiMan** [comment]
To shape the build matrix based on such cases, use the build stages and their conditional build feature. https://docs.travis-ci.com/user/conditional-builds-stages-jobs/

**Comment by iphydf** [comment]
Nice, that works, thanks!
