### ISSUE TITLE
Can't install AWS CLI on a Mac

### ISSUE THREAD

**Issue by mg262** [travis-ci/travis-ci#9072]
This... 

```
{
  "services": "docker",
  "language": "python",
  "script": [
    "python -m pip install awscli --upgrade",
    "aws --version"
  ],
  "os": "osx"
}

```
fails. The error is

> 2.7 is not installed; attempting download
> Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.12/x86_64/python-2.7.tar.bz2
> $ sudo tar xjf python-2.7.tar.bz2 --directory /
> tar: Unrecognized archive format

Also Travis gives a red exclamation instead of the usual x for a failing build -- does that mean an internal error?

It works on "os": "linux".

**Comment by BanzaiMan** [comment]
We do not support Python on the Mac. https://github.com/travis-ci/travis-ci/issues/2312
