### ISSUE TITLE
pdf-inspector anylaze return nil value

### ISSUE THREAD

**Issue by Wozniaxos** [travis-ci/travis-ci#9079]
Hello,
I'm using pdf-inspector gem https://github.com/prawnpdf/pdf-inspector.
Problem is that the method 'analyze' locally in tests works very well and returns string but remotely on travis it returns nil value.

I use ruby 2.4.2
pdf-inspector 1.3.0

If anyone had similiar case i will be very grateful for any help.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by Wozniaxos** [comment]
![zrzut ekranu 2018-01-17 o 09 06 30 2](https://user-images.githubusercontent.com/26778061/35032251-8e150bba-fb66-11e7-8e19-cf29c2e7f6be.png)

**Comment by BanzaiMan** [comment]
That's a screen shot. Not a build log URL. If you'd rather not discuss this issue in public, please close this issue and email support@travis-ci.com. Thanks.
