### ISSUE TITLE
OSX build not happening

### ISSUE THREAD

**Issue by kannanmadanagopalt** [travis-ci/travis-ci#9084]
1,We are facing more OSX build failures or not getting started. It looks from another issue (https://github.com/travis-ci/travis-ci/issues/9075), that OSX builds are running with reduced capacity. 

https://travis-ci.org/pxscene/pxCore/jobs/328270620

do we have any information, when it will be resolved?.

2,Also, do we have any ways to simulate travis build environment locally in these times?. Please clarify.

**Comment by BanzaiMan** [comment]
Please follow https://www.traviscistatus.com/incidents/c1s4dlyxd4lf for updates.

**Comment by kannanmadanagopalt** [comment]
Thanks, will follow it up. Hoping for getting it soon :)
