### ISSUE TITLE
Build doesn't start

### ISSUE THREAD

**Issue by MansMeg** [travis-ci/travis-ci#9085]
Hi!

My build doesn't start. I pushed yesterday evening and the build did not start for 5h and then just errored with ```null```. I havn't changed my ```travis.yml``` anything and previously everything worked perfectly.

Here is the project (its open): 
```https://travis-ci.org/MansMeg/markmyassignment/builds```

Thanks for a great service!

**Comment by shlomif** [comment]
Hi!

I am getting a similar problem here - https://travis-ci.org/shlomif/project-euler/builds/329781496 - thanks for any future help.

**Comment by MansMeg** [comment]
I think this is an issue related to the problem described here:
https://www.traviscistatus.com/incidents/c1s4dlyxd4lf

**Comment by BorzdeG** [comment]
Build does not queue for execution: https://travis-ci.org/itbasis/jvm-wrapper/builds/329615507

**Comment by shlomif** [comment]
Seems ok for me now - https://travis-ci.org/shlomif/project-euler/builds/329852638

**Comment by MansMeg** [comment]
Yes, me too.
