### ISSUE TITLE
Apache httpd start failed

### ISSUE THREAD

**Issue by vvvggg** [travis-ci/travis-ci#9086]
When the script installed Apache httpd (yes, it's planned due to the project itself is the custom Apache's configuration) and tried to start it, an error occured:

```
(98)Address already in use: AH00072: make_sock: could not bind to address 127.0.0.1:80
```

Who is already listening TCP 80 within the VM environment? How to avoid the conflict?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by vvvggg** [comment]
@BanzaiMan sure, here: https://api.travis-ci.org/v3/job/329804901/log.txt

**Comment by BanzaiMan** [comment]
Looks like your process is. https://travis-ci.org/vvvggg/httpd-config/jobs/329804901#L586

My guess is that it is not correctly detecting that the process is running. https://travis-ci.org/vvvggg/httpd-config/jobs/329804901#L607 Not sure how this is happening, though. If the pid file is the only means by which it is determining, I reckon it is prone to error.

**Comment by vvvggg** [comment]
@BanzaiMan That's right, many thanks!
