### ISSUE TITLE
Job waiting to be queued then no update for several hours.

### ISSUE THREAD

**Issue by katmsft** [travis-ci/travis-ci#9088]
Hi, I have created [this PR](https://github.com/Azure/azure-storage-ruby/pull/113) a while ago and it always shows that the job is waiting to be queued and would be no update since then for several hours. I have tried waiting, re-sending the PR, update the PR, close and reopen the PR but none could actually queue the job and get it running. I noticed that the service is down for a while but resolved for some time. The issue is still there. There are times that Azure org does not have any running job but my job still was not executed...

Can anyone help me to proceed?

**Comment by katmsft** [comment]
The waiting to be queued job is [this one](https://travis-ci.org/Azure/azure-storage-ruby/builds/329855917)

**Comment by BanzaiMan** [comment]
Probably related to https://www.traviscistatus.com/incidents/c1s4dlyxd4lf.

Could you ask the maintainers to restart the build?

**Comment by katmsft** [comment]
Thanks for the response @BanzaiMan . I have restarted the job, the status does not seem to change. However I have done this several times before. It won't resolve the problem.

**Comment by BanzaiMan** [comment]
Hmm. That is strange. Is it OK if I try restarting it from our end?

**Comment by katmsft** [comment]
Sure, it'll be absolutely OK.

**Comment by katmsft** [comment]
Hi @BanzaiMan , I saw that you restarted the job but the status remains the same, anything else we could do on our side?

**Comment by BanzaiMan** [comment]
Not much you can do at this point, I'm afraid. I'm working on it on this side. Thanks for your patience.

**Comment by katmsft** [comment]
Sure, take your time. Again thanks for the help.

**Comment by BanzaiMan** [comment]
The jobs have now run.

The issue here is that the Azure organization's queue is separately set up (by a special arrangement), and sometimes the queue is full, and it takes some time for new jobs to be scheduled.

**Comment by katmsft** [comment]
Sure, so that `waiting to be queued` is also a correct state for a started job? Also, thank you very much for looking into this.

**Comment by BanzaiMan** [comment]
Yes, in this case.

**Comment by BanzaiMan** [comment]
I think we can close this.

**Comment by katmsft** [comment]
Cool. Thanks for the help @BanzaiMan .

**Comment by balazs9510** [comment]
Hi.
We have the same problem, please can you help us?

**Comment by prachianand28** [comment]
> The waiting to be queued job is [this one](https://travis-ci.org/Azure/azure-storage-ruby/builds/329855917).

Where we can see the queued time of each job?

**Comment by alainburindi** [comment]
We are having the same issue

[this is the build](https://travis-ci.com/andela/savage_rangers-ah/jobs/205975574)

**Comment by smakosh** [comment]
I'm having the same issue

[Here is my build](https://travis-ci.org/smakosh/react-flex-ready/builds/553513021)
