### ISSUE TITLE
php hhvm Operation not permitted

### ISSUE THREAD

**Issue by uglyoldbob** [travis-ci/travis-ci#9089]
In my php hhvm build configuration, I see lots of the following error messages.
`set_mempolicy: Operation not permitted`
`get_mempolicy: Operation not permitted`
I see them in this job specifically.
https://travis-ci.org/uglyoldbob/web-admin/jobs/329885568

**Comment by BanzaiMan** [comment]
Could it be that HHVM can't run on Docker on this version? See, e.g., https://github.com/hhvm/hhvm-docker/issues/11

Try `sudo: required`.

**Comment by uglyoldbob** [comment]
I added `sudo: required` to my php hhvm build and it solved this problem.
Here is a commit reference showing my change.
[a7987b7](https://github.com/uglyoldbob/web-admin/commit/a7987b781045f32bec530d4b8de625d9789660c9)

**Comment by BanzaiMan** [comment]
I reckon this is a side effect of our recent security updates to deal with Meltdown. https://blog.travis-ci.com/2018-01-08-travis-response-meltdown-spectre

**Comment by cchantep** [comment]
Considering that regressing to `sudo: enabled` is allow disabling the container mode and so slow down the boot time, that's a quite unfortunate side effect.
