### ISSUE TITLE
Builds failed due to Unknown Error

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#9091]
https://travis-ci.org/LolexOrg/Lolex-Tools/builds/329780872

It seems to be automatically have been cancelled but there's no logs and the build claims to have run for an abnormally long time. Any ideas?

Maybe a different occurrence of #6919 or #7162 ?

**Comment by Monkeyboy2805** [comment]
https://travis-ci.org/LolexOrg/Lolex-Tools/jobs/326733604 failed randomly to say that DJANGO 1.11.8 didn't exist apart from the fact that the general build passed, like build 1100.1. Bit weird and I'm not entirely sure what's going on there

**Comment by BanzaiMan** [comment]
Probably a fallout from this build back log issue https://www.traviscistatus.com/incidents/c1s4dlyxd4lf, during which we canceled many outstanding builds.

You may choose to rerun them.

**Comment by Monkeyboy2805** [comment]
Right ok
