### ISSUE TITLE
Syntax of secure:

### ISSUE THREAD

**Issue by mg262** [travis-ci/travis-ci#9093]
I'm deploying to aws S3, which means that I have the following (generated by the Travis CLI). 

```
deploy:
  secret_access_key:
    secure: <ENCRYPTED>
```

Now I need to run a post-deploy stage using AWS CLI. It seems like I should be able to reuse the <ENCRYPTED> material to set the secret key for the AWS CLI, but nothing I try works. Copying

`secure: <ENCRYPTED>`

inside `env: ... global:` has no effect. I assume this is because the `<ENCRYPTED>` is just a value, without a `variable=`. But

`AWS_SECRET_ACCESS_KEY=secure: <ENCRYPTED>`

`AWS_SECRET_ACCESS_KEY:
   secure: <ENCRYPTED>`

and variants on that cause a syntax error. 

What is the exact syntax of `secure:`? Where can you use it? What can be contained inside?

**Comment by BanzaiMan** [comment]
```yaml
deploy:
  secret_access_key:
    secure: <ENCRYPTED>
```
is for use by the deployment provider you are using. It does nothing (including defining an environment variable) outside of that scope.

I don't think this is suggested in our documentation anywhere. If you saw something like it in the docs, could you point to it?

If you want to define and use `AWS_SECRET_ACCESS_KEY`, you'll have to define it separately.

**Comment by BanzaiMan** [comment]
The syntax is discussed in this document: https://docs.travis-ci.com/user/encryption-keys

**Comment by mg262** [comment]
Thank you.
