### ISSUE TITLE
Travis CI Does Not Catch `Gem::DependencyError`

### ISSUE THREAD

**Issue by maham-nazir-confiz** [travis-ci/travis-ci#9094]
**Background**
I am deploying two `CentOS 7.3` virtual machines via Azure Cloud.
1. VM # 1 has `rubygems -v 1.8.25` installed
2. VM # 2 has `rubygems -v 2.6.14` installed

I try to install this gem called `fog-azure-rm -v 0.4.4` and I get a `Gem::DependencyError` in VM # 1, whereas the same `fog-azure-rm -v 0.4.4` gem is installed properly in VM # 2

It turned out to be a `rubygems` version error so I tried to verify this via Travis CI.
I have a cloned repo of the `fog-azure-rm` gem and I have Travis CI activated on it. I updated my `.travis.yml` file to update the `rubygems` version to `1.8.25`

_**.travis.yml File Snippet**_
`before_install:`
`  - gem update --system 1.8.25`
 ` - gem --version`

**Issue**
Now when Travis CI is run and the `rubygems` version is updated to `1.8.25`, I do not get the `Gem::DependencyError` which is weird because Travis CI runs each job on a clean environement.
Can you explain to me why the error does not get caused?

**Note**
Travis CI first installs the latest `rubygems` version. After that I update it to 1.8.25. Is it possible it might still be using the latest version of `rubygems` in it?

**Travis CI Job Log**
Link: https://travis-ci.org/maham-nazir-confiz/fog-azure-rm/builds/330334751

**Comment by BanzaiMan** [comment]
The most likely explanation is that your `rake` task is exiting with 0. https://github.com/maham-nazir-confiz/fog-azure-rm/blob/6121ddc84692ac2c16227aed694b74a9992e9cf9/rake-script.sh#L2

**Comment by maham-nazir-confiz** [comment]
@BanzaiMan 
The script runs after the `bundle install` command. Travis CI is supposed to throw the gem dependency error during the bundle installation.

**Comment by BanzaiMan** [comment]
Where's the error in https://travis-ci.org/maham-nazir-confiz/fog-azure-rm/builds/330334751?

**Comment by maham-nazir-confiz** [comment]
@BanzaiMan 
That is the problem that there is no error.
When I update the `rubygems` version to `1.8.25` in Travis, there should occur a `Gem::DependencyError` during the `bundle install` but it doesn't happen.

While when I am using `rubygems -v 1.8.25` in a new, clean `centOS 7.3` VM as mentioned in the issue, I get a `Gem::DependencyError`.
You can see this in the following picture
![rubygems-1 8 25 copy](https://user-images.githubusercontent.com/30528870/35139148-a75d4552-fd13-11e7-82f5-db5ac6c158ac.jpg)


Now this same error as shown in the picture should happen in Travis as well when the `bundle install` command is ran and it tries to install all the dependencies for the `fog-azure-rm` gem.

What I'm asking is, is it possible that there might be some processes going on in the back in Travis CI due to which the `Gem::DependencyError` doesn't occur?

**Comment by BanzaiMan** [comment]
I am fairly certain that the issue lies elsewhere. If I clone your repository on a fresh VM, and run `bundle install`, this exception is not raised, independent of Travis CI.

```
$ docker run --rm -it ruby /bin/bash
Unable to find image 'ruby:latest' locally
latest: Pulling from library/ruby
723254a2c089: Already exists
abe15a44e12f: Pull complete
409a28e3cc3d: Pull complete
503166935590: Pull complete
0f46f97746e4: Pull complete
9d641d922d2f: Pull complete
891f591c9621: Pull complete
825fab4554b7: Pull complete
Digest: sha256:090577ac73868da6c74a2c5d716e67189e8f6c597b1d4bfbe61e8a68c829c02e
Status: Downloaded newer image for ruby:latest
root@ca5655e484c7:/# ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
root@ca5655e484c7:/# gem install bundler
Fetching: bundler-1.16.1.gem (100%)
Successfully installed bundler-1.16.1
1 gem installed
root@ca5655e484c7:/# cd
root@ca5655e484c7:~# git clone https://github.com/maham-nazir-confiz/fog-azure-rm.git
Cloning into 'fog-azure-rm'...
remote: Counting objects: 14737, done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 14737 (delta 53), reused 88 (delta 36), pack-reused 14617
Receiving objects: 100% (14737/14737), 2.25 MiB | 2.33 MiB/s, done.
Resolving deltas: 100% (10244/10244), done.
root@ca5655e484c7:~# cd fog-azure-rm/
root@ca5655e484c7:~/fog-azure-rm# bundle install
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching rake 10.5.0
Installing rake 10.5.0
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching faraday 0.13.1
Installing faraday 0.13.1
Fetching faraday_middleware 0.12.2
Installing faraday_middleware 0.12.2
Fetching mini_portile2 2.1.0
Installing mini_portile2 2.1.0
Fetching nokogiri 1.6.8.1
Installing nokogiri 1.6.8.1 with native extensions
Fetching azure-core 0.1.14
Installing azure-core 0.1.14
Fetching azure-storage 0.11.5.preview
Installing azure-storage 0.11.5.preview
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching unf_ext 0.0.7.4
Installing unf_ext 0.0.7.4 with native extensions
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching domain_name 0.5.20170404
Installing domain_name 0.5.20170404
Fetching http-cookie 1.0.3
Installing http-cookie 1.0.3
Fetching faraday-cookie_jar 0.0.6
Installing faraday-cookie_jar 0.0.6
Fetching timeliness 0.3.8
Installing timeliness 0.3.8
Fetching ms_rest 0.6.4
Installing ms_rest 0.6.4
Fetching ms_rest_azure 0.7.0
Installing ms_rest_azure 0.7.0
Fetching azure_mgmt_compute 0.9.0
Installing azure_mgmt_compute 0.9.0
Fetching azure_mgmt_dns 0.9.0
Installing azure_mgmt_dns 0.9.0
Fetching azure_mgmt_key_vault 0.9.0
Installing azure_mgmt_key_vault 0.9.0
Fetching azure_mgmt_network 0.9.0
Installing azure_mgmt_network 0.9.0
Fetching azure_mgmt_resources 0.9.0
Installing azure_mgmt_resources 0.9.0
Fetching azure_mgmt_sql 0.9.0
Installing azure_mgmt_sql 0.9.0
Fetching azure_mgmt_storage 0.9.0
Installing azure_mgmt_storage 0.9.0
Fetching azure_mgmt_traffic_manager 0.9.0
Installing azure_mgmt_traffic_manager 0.9.0
Fetching bit-struct 0.16
Installing bit-struct 0.16
Fetching builder 3.2.3
Installing builder 3.2.3
Using bundler 1.16.1
Fetching docile 1.1.5
Installing docile 1.1.5
Using json 2.1.0
Fetching simplecov-html 0.10.2
Installing simplecov-html 0.10.2
Fetching simplecov 0.13.0
Installing simplecov 0.13.0
Fetching codeclimate-test-reporter 1.0.8
Installing codeclimate-test-reporter 1.0.8
Fetching excon 0.60.0
Installing excon 0.60.0
Fetching formatador 0.2.5
Installing formatador 0.2.5
Fetching mime-types-data 3.2016.0521
Installing mime-types-data 3.2016.0521
Fetching mime-types 3.1
Installing mime-types 3.1
Fetching fog-core 2.0.0
Installing fog-core 2.0.0
Fetching multi_json 1.13.1
Installing multi_json 1.13.1
Fetching fog-json 1.1.0
Installing fog-json 1.1.0
Fetching vhd 0.0.4
Installing vhd 0.0.4
Using far-gem 0.5.1 from source at `.`
Fetching minitest 5.8.5
Installing minitest 5.8.5
Bundle complete! 5 Gemfile dependencies, 43 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
```

Remember, you are running `bundle install` in the source directory, not `gem install`.

**Comment by maham-nazir-confiz** [comment]
So I updated my `travis.yml` like this:

**.travis.yml File**
`language: ruby`
`sudo: false`

`before_install:`
`  - gem update --system 1.8.25`
`  - gem --version`
`  - gem install bundler`
`  - gem update bundler`
`  - gem uninstall -aIx nokogiri -i /home/travis/.rvm/gems/ruby-2.4.1@global nokogiri`
`  - gem install fog-azure-rm`

`rvm:`
`  - 2.0.0`

`after_success:`
`  - gem -v`

and still was unable to reproduce the error, as you can see in the logs.
Travis Logs Link: https://travis-ci.org/maham-nazir-confiz/fog-azure-rm/jobs/330774618
