### ISSUE TITLE
Running for more than 24 hrs

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#9095]
[Build 329587426](https://travis-ci.org/kenorb-contrib/base-build-xml/builds/329587426) reads:

>  Running for more than 24 hrs

But it's not correct since no job is actively running.

<img width="868" alt="screen shot 2018-01-18 at 21 24 46" src="https://user-images.githubusercontent.com/266306/35122262-0c8247da-fc96-11e7-88de-22dc9c4c1fe6.png">

**Comment by BanzaiMan** [comment]
I suspect this was a byproduct of the recent build back log issue https://www.traviscistatus.com/incidents/c1s4dlyxd4lf.

I've reconciled the build status for this one.

Sorry about the troubles. Do you see any other?

**Comment by kenorb** [comment]
That's all, thank you. It was just misleading/confusing.
