### ISSUE TITLE
Tox exiting with 1 even though pytest passes (on py35 and py36 but not py34)

### ISSUE THREAD

**Issue by jrwdunham** [travis-ci/travis-ci#9096]
Some of my Travis jobs are failing even though the Pytest tests are passing. I am using Tox to run the tests with Python 3.4, 3.5 and 3.6. The tests pass locally when running `tox`. See [my tox.ini file](https://github.com/dativebase/old-pyramid/blob/2ee3666a3b5d98ce74ebb830cc115696cc68f60b/tox.ini).

My [.travis.yml file](https://github.com/dativebase/old-pyramid/blob/2ee3666a3b5d98ce74ebb830cc115696cc68f60b/.travis.yml) looks like:

    dist: trusty
    group: deprecated-2017Q2
    language: python
    cache: pip

    before_script:
      - pip install tox

    script: tox

    matrix:
      fast_finish: true
      include:

        - python: "3.4"
          env: TOXENV=py34

        - python: "3.5"
          env: TOXENV=py35

        - python: "3.6"
          env: TOXENV=py36

In all 3 cases, the pytest tests are passing yet tox is exiting with exit code 1 in the py35 and py36 cases but not in the py34 case (where everything works). Here is what the last lines of output on the Travis console look like in the failed py35 case:

    ========================= 266 passed in 394.23 seconds =========================
    ERROR: InvocationError: '/home/travis/build/dativebase/old-pyramid/.tox/py35/bin/pytest old/tests/ -v'
    ___________________________________ summary ____________________________________
    ERROR:   py35: commands failed
    The command "tox" exited with 1.
    store build cache

    Done. Your build exited with 1.

See [this build](https://travis-ci.org/dativebase/old-pyramid/builds/330579600) for an example where the [py34](https://travis-ci.org/dativebase/old-pyramid/jobs/330579601) job is passing but the [py35](https://travis-ci.org/dativebase/old-pyramid/jobs/330579602) is failing (even though pytest is passing)

This may be related to these travis issues:

- https://github.com/travis-ci/travis-ci/issues/4990
- https://github.com/travis-ci/travis-ci/issues/8363

Thanks for your help!

**Comment by BanzaiMan** [comment]
Could you try reproducing the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)?

**Comment by jrwdunham** [comment]
Thanks @BanzaiMan It seems to be working now even though I didn't change anything. See https://travis-ci.org/dativebase/old-pyramid/builds/332980565. This can be closed imo.
