### ISSUE TITLE
Problems with http://ppa.launchpad.net/couchdb/stable/ubuntu

### ISSUE THREAD

**Issue by mg262** [travis-ci/travis-ci#9103]
I'm intermittently hitting issues like

The repository 'http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release' does not have a Release file.

on travis.com. It's quite disruptive as we are scaling up to running a lot of jobs and a proportion of jobs need to be manually rerun -- is there any way to set Travis to retry a few times?

[log.txt](https://github.com/travis-ci/travis-ci/files/1648964/log.txt)

**Comment by fancymelonub** [comment]
who the fuck uses Ubuntu Trusty anymore? use Advark or Zesty

**Comment by mg262** [comment]
I'm not selecting Ubuntu Trusty explicitly; just 'os: linux'.

**Comment by BanzaiMan** [comment]
@fancymelonub Please keep your comments civil and constructive.

We have seen issues like this (our third-party PPA sources falling out of date and causing builds to fail). We'll take a look at this one (next week), as well as a more comprehensive way forward soon.

Sorry for the disruptions.

**Comment by mg262** [comment]
Thank you, BanzaiMan.

**Comment by mg262** [comment]
@BanzaiMan Related thought. For our purposes, we don't really need all of the extra packages and so on that Travis installs -- indeed, there is a substantial advantage in just having a vanilla Ubuntu LTS installation, because then the build environment is completely understood on our side.  Could I make a related feature request for vanilla distros?

**Comment by mg262** [comment]
I'm afraid I cut off the last few lines because they had references to private repos in.  Unfortunately I don't have the full log anymore because I reran through the Travis GUI and it worked.  

The build definitely failed, and it failed before any of my code was executed.  But looking at my most recent successful commit, there are some launchpad issues there too, so that was probably a red herring. 

Probably best to leave this. Sorry to waste your time.  I will email the full log to the email address above next time the issue occurs.

**Comment by BanzaiMan** [comment]
@mg262 Thanks for the update. This and other reports of issues regarding launchpad.net lead us to believe that the issue might be intermittent, or possibly related to interaction with that service. We are looking into that.

Again, thank you for the report.
