### ISSUE TITLE
[macos request] Include protobuf to xcode/osx images

### ISSUE THREAD

**Issue by tooomm** [travis-ci/travis-ci#9105]
http://formulae.brew.sh/formula/protobuf

**Comment by BanzaiMan** [comment]
I’m sorry, but I’m not sure what you are asking.

**Comment by tooomm** [comment]
From https://blog.travis-ci.com/2017-12-06-xcode-92-has-landed
>If there are any packages you’d like to see added to our macOS images, please file a Github Issue and include [macos request] in your subject line.

I request [google's `protobuf`](https://github.com/google/protobuf/) package to be included into the travis xcode/osx images.

**Comment by tooomm** [comment]
bump
