### ISSUE TITLE
Assemblies run one at a time, although the limit is set to no more than 2

### ISSUE THREAD

**Issue by BorzdeG** [travis-ci/travis-ci#9106]
In settings the limit in 2 simultaneous assemblies is specified, but start happens on one assembly at the same time. If to remove a limit, all the same start happens no more than one assembly.
[repository](https://travis-ci.org/itbasis/jvm-wrapper)

Also, start of assemblies for `os`=`osx` happens time in several hours. As result, last couple of testing almost days underwent. [example](https://travis-ci.org/itbasis/jvm-wrapper/builds/331149808)

**Comment by BanzaiMan** [comment]
The limit in the repository settings means maximum *per repository*. There might be other jobs already running and you may not see it. Furthermore, this repository creates 5 jobs on the Mac, which is overwhelmed at the moment; this could lead to significant delay in jobs' start, regardless of the limits.
