### ISSUE TITLE
Composer Private Git Repository Issue

### ISSUE THREAD

**Issue by btica-ro** [travis-ci/travis-ci#9108]
Hi guys.

We have a php project on a private repository on the github synced the travis.

Few days ago, we added an private git repository dependency on the composer.json. Also we added the token for private package. First time when travis tried to build last version of the project, it failed because of the private package. First, we thought is something wrong with the composer.json file or the token. We tested on local machine and all worked perfect. Also, we created same project on a isolated server without any ssh keys from github and all went well. 

I already sent some emails to the support team of Travis, but they still are working on that (almost one week since). 

After few days lost with this issue, we created a mirror github repository, and Travis successfully build the project, witch was the same as in the first case.

Travis build logs:
https://travis-ci.com/mishuvlad/docker-images/builds/63627389#L519, the working one.
https://travis-ci.com/mishuvlad/stars/builds/63628596#L576, the failing one.

Both repositories have same composer.json file.

The main issue is that on one travis repository, all composer dependencies are loaded but on the another travis repository is failing.

**Comment by BanzaiMan** [comment]
I'm sorry to say that I am a bit lost as to why the behaviors may differ in this instance. Could you try running it in the debug mode to troubleshoot further?
