### ISSUE TITLE
rsync authenticity error

### ISSUE THREAD

**Issue by AdmagTwoXray** [travis-ci/travis-ci#9109]
I am trying to use rsync to upload files from a Travis build to my webserver. I am having to use sudo with my commands as if I don't I get a permission denied error when uploading files, even though the user has the correct permissions for the directory. When I try to use sudo though I get this error `The authenticity of host 'ssh.multicrew.co.uk' can't be established`.

I have added ssh.multicrew.co.uk in the ssh_known_hosts section of my .travis.yml file but it still cannot establish the authenticity of my host. My .travis.yml file can be found [here][1] and my deploy script [here][2].

  [1]: https://github.com/MultiCrew/MTC-Test/blob/master/.travis.yml
  [2]: https://github.com/MultiCrew/MTC-Test/blob/master/deploy/deploy.sh

**Comment by BanzaiMan** [comment]
You are [running `rsync`](https://travis-ci.org/MultiCrew/MTC-Test/builds/331441415#L467) as `root` ([with `sudo`](https://github.com/MultiCrew/MTC-Test/blob/729890caa48e30fe7a6351f865f98724dd9fd503/deploy/deploy.sh#L25)), but `root` does not know about the remote host. (The `ssh_known_hosts` addon does it only for the build user, not `root`; this should be clarified int the documentation.)

See https://stackoverflow.com/a/18124444/136333.

**Comment by AdmagTwoXray** [comment]
Am I not running it as the `deploy` user?

**Comment by AdmagTwoXray** [comment]
Also if I were to use that `ssh-keyscan $someip >> ~/.ssh/known_hosts` code would I run it in my .travis.yml file or on my server?

**Comment by BanzaiMan** [comment]
Your build runs as the `$USER` (`travis` at the moment, but we [do not guarantee](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) this value).

Please read the SO answer and the `ssh-keyscan` documentation carefully.

**Comment by soulshake** [comment]
Just a general tip on redirection of commands run with sudo...

[Here](https://travis-ci.org/MultiCrew/MTC-Test/builds/331441415#L461) you are running:
```
sudo echo -e "Host ssh.multicrew.co.uk\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
```

The `~` in  `~/.ssh/config` expands to your user home directory, not root's. You would need `| sudo tee -a /root/.ssh/config` instead of `>> ~/.ssh/config`.
