### ISSUE TITLE
alias [ci skip] to [skip ci]

### ISSUE THREAD

**Issue by sethvargo** [travis-ci/travis-ci#911]
I don't know how many times I accidentally kick off a build because I add `[skip ci]` instead of `[ci skip]` to my commit message.

It'd be nice if Travis honored both, and I think it would save you guys some builds :smile:

**Comment by mathieujobin** [comment]
maybe not the right place to ask this
but can this `[ci skip]` be placed on a PR message so we can open a PR for review without the double-builds ? I need it per PR, not global, thats why

thanks

**Comment by tyru** [comment]
`[skip ci]` alias doesn't seem to work now?
In this repo, `[skip ci]` is included in commit message
but Travis CI Build was fired. vim-jp/vital.vim#380

**Comment by tyru** [comment]
I'm sorry, I was wrong.
As @mathieujobin said, merge commit was skipped but each message has no `[skip ci]` string, build was fired.
