### ISSUE TITLE
The 2017-12-12 image failed to build with error: /bin/sh: 1: cmake: not found

### ISSUE THREAD

**Issue by Prcuvu** [travis-ci/travis-ci#9113]
The error occurred in [this job](https://travis-ci.org/rime/librime/jobs/329548197), starting from line 853:
```
make: Entering directory `/home/travis/build/rime/librime/thirdparty/src/opencc'
mkdir -p build/rel
(cd build/rel; cmake \
	-DBUILD_DOCUMENTATION:BOOL=ON \
	-DENABLE_GTEST:BOOL=OFF \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	../..)
/bin/sh: 1: cmake: not found
make: *** [build] Error 127
make: Leaving directory `/home/travis/build/rime/librime/thirdparty/src/opencc'
The command "./travis-before-install.sh" failed and exited with 2 during .
Your build has been stopped.
```
Curiously, cmake was successfully called before the error occurred, as of line 680.

Going back to previous image by adding `group: deprecated-2017Q4` in `.travis.yml` circumvents the problem. See [this job](https://travis-ci.org/Prcuvu/librime/jobs/331832123).

**Comment by BanzaiMan** [comment]
Where is `cmake`? On the erroneous invocation, it is called from a sub shell, so I suspect `$PATH` is not set up as you expect.

**Comment by Prcuvu** [comment]
@BanzaiMan `cmake` is located in `/usr/local/cmake-3.9.2/bin`. I've found that `cmake` is not recognized when using `sudo`.

**Comment by BanzaiMan** [comment]
This change is intentional. If you want to preserve `$USER`'s environment when invoking `sudo`, pass the `-E` flag.

**Comment by kroggen** [comment]
I tried using the -E flag but it did not work:

https://travis-ci.org/litereplica/litereplica/builds/342759168
