### ISSUE TITLE
Python nightly and 3.7-dev not updating

### ISSUE THREAD

**Issue by njsmith** [travis-ci/travis-ci#9119]
It looks like the Python "3.7-dev" and "nightly" interpreters haven't been updated since August:

```
~$ s3cmd ls s3://travis-python-archives/binaries/ubuntu/14.04/x86_64/ | grep 3.7-dev
2017-08-31 15:53  62313156   s3://travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7-dev.tar.bz2
2017-08-31 15:53        89   s3://travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7-dev.tar.bz2.sha256sum.txt
2017-08-31 15:53       103   s3://travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7-dev.tar.bz2.sha256sum.txt.sha256sum.txt
~$ s3cmd ls s3://travis-python-archives/binaries/ubuntu/14.04/x86_64/ | grep nightly
2017-08-31 15:53  62313156   s3://travis-python-archives/binaries/ubuntu/14.04/x86_64/python-nightly.tar.bz2
2017-08-31 15:53        89   s3://travis-python-archives/binaries/ubuntu/14.04/x86_64/python-nightly.tar.bz2.sha256sum.txt
```

The 3.7 release is scheduled to branch off from master and start its beta cycle on 2018-01-29, a week from today, so it'd be nice if these started updating again so people can test against the upcoming release :-). Thanks!

**Comment by BanzaiMan** [comment]
Nightly builds had neglected these for a while. I revived the builds, but it appears that numpy is not compiling for that. https://travis-ci.org/travis-ci/cpython-builder/builds/332144859

**Comment by njsmith** [comment]
Funny coincidence, what prompted me to file this bug was a conversation about wanting to be able to test numpy on 3.7 :-).

That is an extremely weird error though. One random thought: you're doing `setup.py build && setup.py install`, which something we really support these days. (It's generally bad practice.) And the error is happening deep inside some `bdist_egg` code, which is a weird old thing that's connected to the reasons why `setup.py install` isn't recommended. So this is a bit of a shot in the dark, but possibly it would help to modify `build_numpy_from_source` so that instead of invoking `./setup.py` it does `pip install .`?

**Comment by njsmith** [comment]
See also https://github.com/numpy/numpy/pull/10458

**Comment by Monkeyboy2805** [comment]
3.7 non-updating is an issue I have noticed as well, it's still running alpha 0

**Comment by BanzaiMan** [comment]
I can set up a clone for the Python builder for any of you to take a look, if you are so inclined.

**Comment by jwilk** [comment]
https://github.com/pypa/setuptools/issues/1257

**Comment by BanzaiMan** [comment]
@jwilk Very interesting. Thanks for the pointer!

**Comment by njsmith** [comment]
The numpy issue you hit is now worked around on numpy master. (I still recommend switching from `./setup.py install` to `pip install .`)

@banzaiman are you asking for help? What kind of help do you need here?

**Comment by BanzaiMan** [comment]
@njsmith Could you elaborate on this?

> I still recommend switching from `./setup.py install` to `pip install .`

[numpy's instructions](https://scipy.github.io/devdocs/building/linux.html) explicitly states `python setup.py install`; it does not mention `pip` at all.

> are you asking for help?

Not really. Looks like the numpy team is aware of the problem, and I expect the builds to succeed once it is solve.

**Comment by njsmith** [comment]
Oh, thanks, we should fix those instructions. For your purposes, right now, `setup.py` works fine (though it does print a warning suggesting you use pip). But pip is the better tested path – this particular error is in a code path that I don't think pip would ever hit – and just in general, this is the direction that the Python ecosystem is moving. (The underlying reason is that `setup.py` only works for projects that are using the same buggy and rusted-closed build system that Python's been using for years, while switching to `pip` as the entry point makes it possible to use other build systems.)

> Looks like the numpy team is aware of the problem, and I expect the builds to succeed once it is solved.

Ok. I am a numpy core developer, and I think the issue is solved, so please speak up if not :-)

**Comment by BanzaiMan** [comment]
Indeed, the last night's build was successful. https://travis-ci.org/travis-ci/cpython-builder/jobs/332622424

I'll fix the numpy installation instructions.

Thanks, everyone!

**Comment by BanzaiMan** [comment]
@njsmith Oh, one more thing: is [`setup.py build`](https://github.com/travis-ci/cpython-builder/blob/18380dd50bcb420cdd32b512a8f8df5ed53f6c3c/bin/compile#L25) necessary?

**Comment by njsmith** [comment]
No, everything that needs `setup.py build` will invoke it automatically, you should never need to call it directly.

**Comment by Monkeyboy2805** [comment]
Okay, yeah the nightly build is on alpha4+ now.

**Comment by Monkeyboy2805** [comment]
@BanzaiMan This problem still isn't fixed. https://travis-ci.org/LolexOrg/Lolex-Tools/jobs/337926047 should be running python 3.8.0a0 but it's still on 3.7.0a4+

**Comment by BanzaiMan** [comment]
@Monkeyboy2805 `3.8-dev` definition is not yet available on https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build, so we can't build it. Sorry.

**Comment by BanzaiMan** [comment]
@Monkeyboy2805 It occurred to me. Python 3.7 and up will not work with Trusty and below due to https://github.com/travis-ci/travis-ci/issues/9069.
