### ISSUE TITLE
Publish changelog for worker environment changes

### ISSUE THREAD

**Issue by reid** [travis-ci/travis-ci#912]
Changes in the worker, such as degraded performance, updates to newer versions of programs like PhantomJS or Node.js, and other service modifications can often trigger build errors or failures.

Debugging these failures is very difficult. In addition to others in the Travis community, I have sought how to debug Travis locally:
- [Debugging Travis builds: Installing Travis locally](http://reidburke.com/2013/01/28/debugging-travis-builds/)
- [Debugging test failures locally: travis-ci mailing list](https://groups.google.com/forum/?fromgroups=#!topic/travis-ci/I1Cu4-H-6qI)
- [Debug Your Failed Test in Travis CI](http://ruby-journal.com/debug-your-failed-test-in-travis-ci/)

This sometimes can be helpful. However, there is no way to check when Travis updates their workers to ensure my local VM is up to date.

There's also no way for me to easily correlate a recent test failure to a change in the Travis worker instead of a change to my code.

Please publish a changelog of worker status updates that include changes to installed software and performance degradation events. This would be tremendously helpful in debugging why test failures occur on Travis instead of other environments.

**Comment by mizzao** [comment]
There have been no updates for almost a year now, and I'm in the process of trying to debug a build that started breaking a few months ago (potentially PhantomJS issues; see arunoda/travis-ci-meteor-packages#36). Is there an updated Changelog somewhere?

**Comment by joshk** [comment]
Sorry @mizzao, that changelog is not currently maintained. We are working on a proper solution which will also be integrated with the UI.

If you have a build issue, please email support@travis-ci.com

Thanks

**Comment by mizzao** [comment]
I have a build that broke across trivial changes about three months ago for an OSS project

https://travis-ci.org/HarvardEconCS/turkserver-meteor/builds/43033496 (working)
https://travis-ci.org/HarvardEconCS/turkserver-meteor/builds/44617494 (broken)

and I'm trying to figure out what the environment change is that caused it. I initially thought this was a temporary issue that would resolve itself. It seems that there are significant differences in the preamble so something must have been very different on Travis. Do you think this is something I should e-mail? It seems like more of a PhantomJS issue - as someone pointed out to me, the build works if you force it to run on OS X, but not Linux.

**Comment by Joshua-Anderson** [comment]
@mizzao Is [this](http://docs.travis-ci.com/user/build-environment-updates/) what you are looking for?

**Comment by mizzao** [comment]
Yes! Thank you!

Further debugging of my issue yields strange results, i.e. forcing the test to run on OS X works: https://travis-ci.org/HarvardEconCS/turkserver-meteor/builds/55751466.

This is some weird PhantomJS/Node interaction on a different OS that is beyond my pay grade. Here's hoping that someone else on the Internet will find the problem :)
