### ISSUE TITLE
Environment variables to distinguish travis-ci.org and travis-ci.com

### ISSUE THREAD

**Issue by lmazuel** [travis-ci/travis-ci#9124]
Hello,

Is there a native way to know if you're running on travis-ci.org or travis-ci.com with a default environment variable? Like `TRAVIS_HOST` to be `travis-ci.org` or `travis-ci.com`, or `TRAVIS_PRIVATE=True` or something?
I know I can create my own environment variable to do it, but seems to me this should be in one of the default environment variables:
https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

Thoughts?
Thanks!

**Comment by BanzaiMan** [comment]
I'm closing this as a variation of #8935.
