### ISSUE TITLE
It should be possible to specify that `apt-get update` should be retried when it warns "Failed to fetch"

### ISSUE THREAD

**Issue by JasonGross** [travis-ci/travis-ci#9126]
See also #8507.  When using the `apt` add-on, I want to be able to specify that seeing `W: Failed to fetch ...` should count as a fatal failure of `apt-get update`, and I want to be able to specify a number of retries for this `apt-get update`.

**Comment by BanzaiMan** [comment]
Related https://github.com/travis-ci/travis-build/pull/605 https://github.com/travis-ci/travis-build/pull/600 https://github.com/travis-ci/travis-build/pull/1054

**Comment by JasonGross** [comment]
I don't think this has been solved, and I think it's still applicable.

**Comment by BanzaiMan** [comment]
@JasonGross Do you have a recent build log to indicate the problem? We have added the retries option recently. https://github.com/travis-ci/travis-build/pull/1343
