### ISSUE TITLE
Can we disable apt-daily.service on xenial?

### ISSUE THREAD

**Issue by rcurtin** [travis-ci/travis-ci#9129]
Hi there,

Our Travis configuration is fairly straightforward: install a few dependencies via `apt` in the `before_install` section then perform the build.  But we have found in the past months after switching to xenial that the default systemd `apt-daily` service is locking `/var/lib/dpkg/lock` and as a result our builds intermittently fail.

As far as I can tell, `apt-daily.service` runs when the VM is started, and my attempts to stop it (see here: https://github.com/rcurtin/mlpack/blob/c725576be5b5c35dc796af28d044b9d7764d6a23/.travis.yml and here: https://github.com/mlpack/mlpack/pull/1191 ) have all failed.

Here is a build log, with `ps -ef f` showing apt-daily-related processes running:

https://travis-ci.org/mlpack/mlpack/jobs/332471595

Probably one out of every four of our builds fails because of this.

Is it possible to get a xenial VM without these automatic apt updates running in the background?  Or am I overlooking something simple?  I notice that if I search for "travis apt-daily.service" I am not finding really any information at all other than my own debugging attempts.

Thanks!

**Comment by sbrodehl** [comment]
How about waiting until until `apt-get updated` has been killed, which got invoked from `apt-daily.service`, as described [here](https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image)?

E.g. something like [this](https://unix.stackexchange.com/a/315517):
```shell
systemctl stop apt-daily.service
systemctl kill --kill-who=all apt-daily.service

# wait until `apt-get updated` has been killed
while ! (systemctl list-units --all apt-daily.service | fgrep -q dead)
do
  sleep 1;
done

# now proceed with own APT tasks
apt install ...
```

**Comment by BanzaiMan** [comment]
Our Xenial support is undocumented, experimental, and unstable at this time. While we appreciate your report, there are too many moving parts to provide meaningful end-user support.

**Comment by rcurtin** [comment]
Hi there, thanks for the quick response, I really appreciate it.  Sorry to hear that xenial isn't ready yet, but our needs require it, so I'll keep playing with the experimental support.  When I establish a solution, I'll post it here for anyone to find in the future.

If you'd like to close the issue now, feel free, otherwise I'll do so once I have an answer.

**Comment by BanzaiMan** [comment]
Thanks for your understanding. I'm closing this now.

**Comment by rcurtin** [comment]
Just to finalize this, below is the `before_install` script we are using on the xenial VMs to stop systemd automatic update services:

```
before_install:
  # xenial is not stable yet, so we have to manually disable the systemd
  # automatic updates services.  Ideas adapted from here:
  # https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image
  - sudo systemctl stop apt-daily.service apt-daily.timer apt-daily-upgrade.service apt-daily-upgrade.timer
  - sudo systemctl kill --kill-who=all apt-daily.service apt-daily-upgrade.service
  - while !(systemctl list-units --all apt-daily.service | grep -q dead); do sleep 1; done
  - while !(systemctl list-units --all apt-daily-upgrade.service | grep -q dead); do sleep 1; done
```

I hope that this is helpful for someone in the future.
