### ISSUE TITLE
travis-ci not running

### ISSUE THREAD

**Issue by nisevi** [travis-ci/travis-ci#9130]
Hi there since yesterday the commits on the PR's received [here](https://github.com/AgileVentures/LocalSupport/pulls) stopped running travis-ci, we haven't touched the configuration file lately, could I have your advice on this matter?

**Comment by nisevi** [comment]
Here you have our repo on your system https://travis-ci.org/AgileVentures/LocalSupport

**Comment by BanzaiMan** [comment]
Looks like it's been disabled. Could you check the settings in https://travis-ci.org/profile/AgileVentures?

**Comment by nisevi** [comment]
Thank you for you quick answer @BanzaiMan 

Here the screenshots related to the link you shared:

![image](https://user-images.githubusercontent.com/3024789/35333811-6af93bec-0110-11e8-9627-7a09392dedec.png)

and here the first part of the settings:
![image](https://user-images.githubusercontent.com/3024789/35333838-848b692c-0110-11e8-84ea-9d6e304806d3.png)

**Comment by BanzaiMan** [comment]
Thanks for checking. I've disabled and re-enabled it now to reset the GitHub hook. Could you try triggering a manual build (in "More options" drop down menu) or pushing a new commit?

**Comment by nisevi** [comment]
@BanzaiMan sure thing I will :+1:

**Comment by nisevi** [comment]
@BanzaiMan awesome! is working again :+1: 

Thank you very much!

**Comment by BanzaiMan** [comment]
Thanks!
