### ISSUE TITLE
Pre-existing PyPI files cause the entire build to error

### ISSUE THREAD

**Issue by evhub** [travis-ci/travis-ci#9134]
The Coconut [.travis.yml](https://github.com/evhub/coconut/blob/develop/.travis.yml) is set up to automatically deploy to PyPI. However, we only actually want it to deploy when we increment the version. Previously, I had it set up so that the deploy script would always try to deploy, but if that version already existed on PyPI, it would fail. Until recently, that failure never actually caused the builds to fail--the desired behavior, since we don't care if the deploy fails when the version hasn't been incremented.

However, something changed very recently such that the deploy failures are now causing all of the builds to error. As an example of this, compare [this build from before the change](https://travis-ci.org/evhub/coconut/jobs/331969173) to [this build from after the change](https://travis-ci.org/evhub/coconut/jobs/332583713). In both cases, all of the tests succeed (which is what I care about), and in both cases no deploying to PyPI is done as the version hasn't been incremented. However, in the first case, the build as a whole succeeds, while in the second case, the build as a whole errors.

It's fine if Travis has decided to change the default here, but I would really like a way to specify that I want the old behavior, in that I want to allow my deploy to fail and not cause my entire build to error.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/dpl/pull/717

If you want the old behavior, you can specify

```yaml
deploy:
  provider: pypi
  edge:
    branch: v1.8.45
  ⋮ # rest
```

but future changes will not be incorporated.

**Comment by neetjn** [comment]
@BanzaiMan I'm currently experiencing this even with `edge` in my project. Heres my config: https://github.com/neetjn/py-component-controller/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
@neetjn Your configuration https://github.com/neetjn/py-component-controller/blob/13bffbb3bc4f0554b389a2d9865527ad8bd310fe/.travis.yml#L30-L31 is wrong. This would try to use the `deploy` branch of the `dpl` source, which [does not exist](https://github.com/travis-ci/dpl/tree/deploy) and the deployment [fails](https://travis-ci.org/neetjn/py-component-controller/jobs/340007899#L636).

**Comment by neetjn** [comment]
I created another branch 'deploy' specifically to push to after changes are merged into master to deploy the latest version of my package to pypi. This way the tests run against master, and once I kn ow everything is gravy I can just push to deploy and disregard any following errors when trying to deploy twice. I guess I don't need to use the edge identifier anymore though

**Comment by neetjn** [comment]
*Deploy twice as in each version of Python I test against. I guess I can also resolve this by checking the version of Python and only deploying to a single version. Guess I just rubber ducked the solution.

**Comment by chrisjsewell** [comment]
FYI, this may be a niche use case, by I'm dealing with this issue because I was deploying to PyPi on tagged commits (ok) and deploying to https://test.pypi.org on all other commits (now failing), in order to check that the readme rendered properly on PyPi before updating the version;

https://github.com/chrisjsewell/jsonextended/blob/v0.7.4/.travis.yml
