### ISSUE TITLE
macOS builds for conda-forge organization stalled (?)

### ISSUE THREAD

**Issue by pkgw** [travis-ci/travis-ci#9135]
Over the past week, macOS builds for the [conda-forge](https://travis-ci.org/conda-forge/staged-recipes) organization have been executing very, very rarely. I recognize that you've been having lots of challenges with your macOS infrastructure in this time period, but even so, what we're seeing seems to be unusually bad. Over the past 36 hours, fewer than 10 build jobs have run, according to the monitoring that I've been doing. Our backlog is now more than 500 jobs deep (although to be fair, we drive Travis CI very, very hard).

In the course of checking this out, I noticed that the organization has about 150 build jobs that are in state "created" even though they were cancelled, all from a period of ~12 hours 277 days ago. E.g. [this one](https://travis-ci.org/conda-forge/pyagrum-feedstock/builds/196869616) or [this one](https://travis-ci.org/conda-forge/mumps-feedstock/builds/196906356). Is there any chance these might be affecting what we're seeing?

CC @jakirkham.

**Comment by BanzaiMan** [comment]
The conda-forge organization is huge, and all the available slots are occupied by Mac jobs, which are waiting for their turns in the overwhelmed queue.

**Comment by BanzaiMan** [comment]
As of 2018-01-24T21:15-0500, two jobs in https://travis-ci.org/conda-forge/healpy-feedstock/builds/330366268 are queued.

**Comment by pkgw** [comment]
To put another spin on it: there are other open-source organizations on Travis CI that I am affiliated with, and in the past few days I am pretty confident that they have executed substantially more build jobs than the conda-forge organization. Is it possible that there is something causing unusual delays for builds affiliated with conda-forge?

(Note that, the builds seem to be succeeding just fine once they actually start — it is getting them launched at all that seems to be the problem.)

**Comment by BanzaiMan** [comment]
I looked at the current queue status of `conda-forge`, and I think they are all Mac jobs (though I'd only spot checked them). We have a low max for them, and they need to wait for their turn longer than Linux jobs.

Compare a Linux job https://travis-ci.org/conda-forge/staged-recipes/jobs/333314943 and a Mac job https://travis-ci.org/conda-forge/staged-recipes/builds/332956106 in the same repository.

**Comment by BanzaiMan** [comment]
The next two Mac jobs that will run for `conda-forge` are:

https://travis-ci.org/conda-forge/r-pbdzmq-feedstock/jobs/330489887
https://travis-ci.org/conda-forge/r-pbdzmq-feedstock/jobs/330489888

**Comment by BanzaiMan** [comment]
And https://travis-ci.org/conda-forge/libkml-feedstock/jobs/330489313 had just finished.
