### ISSUE TITLE
Cpython build failing on PyPy build

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#9138]
https://travis-ci.org/travis-ci/cpython-builder/jobs/333109219

**Comment by Monkeyboy2805** [comment]
@DrTorte This issue has decided not to close for some reason?

**Comment by Monkeyboy2805** [comment]
Well, it _did_ until the label got removed

**Comment by DrTorte** [comment]
@Monkeyboy2805 Hey there! There is a 24 hour delay from the label being added until it closes. I'm going to be updating the text to make that a bit clearer. :) Thanks a bunch for pinging me.

**Comment by Monkeyboy2805** [comment]
@DrTorte Okay, that makes sense
