### ISSUE TITLE
Missing jdk_switcher?

### ISSUE THREAD

**Issue by ahankinson** [travis-ci/travis-ci#914]
We're still stuck on openjdk 6 (hopefully not for long!) but just today noticed that it is no longer possible to switch to it in our build:

```
The command "jdk_switcher use openjdk6" failed and exited with 127 during before_install.

Your build has been stopped.
```

Is this a bug, or has OpenJDK6 been removed?

**Comment by mistercrunch** [comment]
Same issue here https://travis-ci.org/apache/incubator-superset/jobs/563664943
