### ISSUE TITLE
Stop Default services

### ISSUE THREAD

**Issue by btica-ro** [travis-ci/travis-ci#9140]
Hi. Currently we are using TravisCI in order to test our php projects.

I saw a lot of services starting at the start of the machine. We don't need services like RabbitMqt,Postgres, Mysql or any other services started by default because we use docker containers.
Is there any work around to stop machine starting those services ? 
Currently I stop postgres with "sudo /etc/init.d/postgresql stop", but I think there should be a more elegant way.

**Comment by BanzaiMan** [comment]
This is a refrain of #2959.

You might want to use `language: generic` instead if your build solely depends on Docker to do the work.
