### ISSUE TITLE
Unable to curl https site

### ISSUE THREAD

**Issue by ycmjason** [travis-ci/travis-ci#9141]
Hi, I have searched for so long to solve this problem but nothing seems to really work.

So I am building a library for grabbing lyrics from websites. So my tests involves fetching some webpages. The test work fine on my macbook but when I try to add travis as my CI, travis doesn't seem to be able to fetch the webpages.

This is my early attempt:
https://travis-ci.org/ycmjason/grab-lyrics/jobs/332698543#L887

As you see, I am getting an error:
`FetchError: request to https://www.azlyrics.com/lyrics/johnmayer/stopthistrain.html failed, reason: socket hang up`

I started trying all kind of thing. I tried to `curl` that site. And it wouldn't work as well (which work on my local)
https://travis-ci.org/ycmjason/grab-lyrics/jobs/332724970#L872

Then I tried one thing, which according to the log, doesn't do anything (but changing the container image?), and it worked. What I did was to do `sudo apt-get -qq update` and `sudo apt-get install -y curl` in `before_install`.
https://travis-ci.org/ycmjason/grab-lyrics/jobs/332964094#L447

Then I assumed that it was because of the environment? So I tried to add the following to my `.travis.yml`. Then this also work.
```yml
sudo: required
dist: trusty
```
https://travis-ci.org/ycmjason/grab-lyrics/jobs/332966172

But only sometimes,
https://travis-ci.org/ycmjason/grab-lyrics/jobs/333164271#L877

This is very frustrating to me. Could someone help please? 😢

**Comment by BanzaiMan** [comment]
This is what I get on our Docker image:

```sh-session
pthistrain.html7891:~$ curl -sSfLv https://www.azlyrics.com/lyrics/johnmayer/sto
* Hostname was NOT found in DNS cache
*   Trying 5.79.76.225...
* Connected to www.azlyrics.com (5.79.76.225) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
*        subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.azlyrics.com
*        start date: 2017-07-04 00:00:00 GMT
*        expire date: 2020-07-03 23:59:59 GMT
*        subjectAltName: www.azlyrics.com matched
*        issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*        SSL certificate verify ok.
> GET /lyrics/johnmayer/stopthistrain.html HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.azlyrics.com
> Accept: */*
>
* SSLv3, TLS alert, Client hello (1):
* Empty reply from server
* Connection #0 to host www.azlyrics.com left intact
curl: (52) Empty reply from server
travis@a14681b97891:~$ curl -sSfLv https://www.azlyrics.com/lyrics/johnmayer/stopthistrain.html
* Hostname was NOT found in DNS cache
*   Trying 5.79.76.225...
* Connected to www.azlyrics.com (5.79.76.225) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
*        subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.azlyrics.com
*        start date: 2017-07-04 00:00:00 GMT
*        expire date: 2020-07-03 23:59:59 GMT
*        subjectAltName: www.azlyrics.com matched
*        issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*        SSL certificate verify ok.
> GET /lyrics/johnmayer/stopthistrain.html HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.azlyrics.com
> Accept: */*
>
* SSLv3, TLS alert, Client hello (1):
* Empty reply from server
* Connection #0 to host www.azlyrics.com left intact
curl: (52) Empty reply from server
```

**Comment by ycmjason** [comment]
Not sure how is that useful? Could you explain a little bit more?

**Comment by BanzaiMan** [comment]
Sorry for being terse. The issue appears to me with the server's response. The above response is observed from my computer using the Docker image, as described in https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image.

The same error is also observed from my machine without the use of Docker:

```sh-session
bash-4.4$ curl -q https://www.azlyrics.com/lyrics/johnmayer/stopthistrain.html
curl: (52) Empty reply from server
bash-4.4$ echo $?
52
```

In short, I don't think this is an issue with Travis, but rather, the remote server itself.

**Comment by ycmjason** [comment]
Opps, I must have given a bad example from my many failed builds.

https://travis-ci.org/ycmjason/grab-lyrics/jobs/332743980#L907

If you look at this one, adding the header works for me on my macbook. But not on travis.

`curl -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36" -v https://www.azlyrics.com/lyrics/johnmayer/stopthistrain.html`

**Comment by BanzaiMan** [comment]
Could they be blocking access from certain IP ranges? The server is not sending any data, so we can't really troubleshoot this issue.

**Comment by ycmjason** [comment]
Does it work on the container? Ya I also suspect about IP range. But it seems to be working once I call`sudo apt-get -qq update`. So weird..

See here:
https://travis-ci.org/ycmjason/grab-lyrics/jobs/333473211/config

**Comment by ycmjason** [comment]
https://travis-ci.org/ycmjason/grab-lyrics/builds/333495511
https://travis-ci.org/ycmjason/grab-lyrics/builds/333496446
https://travis-ci.org/ycmjason/grab-lyrics/builds/333496636

If you look at these 3 builds
They have the exact same codebase, but only the first one with the `apt-get` working.

**Comment by ycmjason** [comment]
It really seems to be an issue with travis to me.

**Comment by BanzaiMan** [comment]
This is quite curious. How did you think `sudo apt-get update` would help? And *how* that could possibly help with the problem at hand? It merely pulls down the list of new packages and versions, right? How should that affect `curl`? I don't understand.

**Comment by ycmjason** [comment]
I was just trying out different things. And spending a day or two trying. Initial thoughts was curl is not updated. So I did apt update and apt install curl. But the log shows they don't do anything but the tests passed. So awkward.

**Comment by ycmjason** [comment]
Any chance you would have a further inspection at this?

**Comment by ycmjason** [comment]
I am very frustrated now. I have tried all kinds of things now and still now working.

My latest attempt is to retry fetch upon failure up to 5 times. And wait for one second upon every failure.

And it is still randomly failing the tests... 😭 

https://travis-ci.org/ycmjason/grab-lyrics/builds/333958637

I log every retry of fetch.

**Comment by BanzaiMan** [comment]
I am sorry to hear about your frustration. As I stated earlier, without meaningful response from the remote server, we cannot help you much. Have you tried asking them what they might be seeing?
