### ISSUE TITLE
There was an error while trying to fetch the log.

### ISSUE THREAD

**Issue by xXNiceYT** [travis-ci/travis-ci#9144]
https://travis-ci.org/CLADevs/CLACore/builds/333572924

**Comment by BanzaiMan** [comment]
Looks like the logs took a little longer to get archived. It is available now.

**Comment by Taher-Ghaleb** [comment]
I am having a difficulty in obtaining the log files for most of the builds in this repository 'fog/fog'. Here is an example:

[https://travis-ci.org/fog/fog/builds/2144841](https://travis-ci.org/fog/fog/builds/2144841)

Thanks.

**Comment by PeterDaveHello** [comment]
Same here: https://travis-ci.org/PeterDaveHello/ColorEchoForShell/jobs/369931930, restart not working ...

**Comment by roperto** [comment]
Same here: https://travis-ci.org/roperto/AzureMoodle/builds/371866996
