### ISSUE TITLE
API V3 /jobs endpoint failing

### ISSUE THREAD

**Issue by surli** [travis-ci/travis-ci#9147]
It seems that the /jobs endpoint is broken for some days on API V3: 

> curl -H "Travis-API-Version: 3" -H "User-Agent: API Explorer"   -H "Authorization: token XXXXX"   https://api.travis-ci.org/jobs?limit=5
> <!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>

Other endpoint seems to work fine:
> curl -H "Travis-API-Version: 3" -H "User-Agent: API Explorer"   -H "Authorization: token XXXXXXX"   https://api.travis-ci.org/job/333392968
{
  "@type": "job",
  "@href": "/job/333392968",
  "@representation": "standard",
  "@permissions": {
    "read": true,
    "debug": true,
    "cancel": true,
    "restart": true,
    "delete_log": true
  },
[....]

**Comment by BanzaiMan** [comment]
Could you record times (in UTC, please) that these errors occurred? Perhaps we've logged some exceptions.

**Comment by surli** [comment]
Apparently it's back to normal. I close the ticket for now.
