### ISSUE TITLE
Question: API V3 build.state vs job.state

### ISSUE THREAD

**Issue by surli** [travis-ci/travis-ci#9148]
I'm working on a Java API for Travis and I would like to know what are the expected values for job.state and build.state. The documentation specify that we can use state filters on endpoint, but not the kind of value they can have. 

Using the endpoints of V2 I discovered that a build can be: 
failed, passed, created, started, errored, or canceled

and it seems that a job can be:
created, finished, queued and received

but is there any documentation to assess that on V3? Or at least to confirm that the state of a build and of a job is different?

**Comment by TimNN** [comment]
It seems like the [travis-ci/travis-api](https://github.com/travis-ci/travis-api) repo contains a list of states for [builds](https://github.com/travis-ci/travis-api/blob/master/lib/travis/model/build/states.rb#L25) and [jobs](https://github.com/travis-ci/travis-api/blob/master/lib/travis/model/job/test.rb#L21).

**Comment by surli** [comment]
OK for V2. But what about V3? 

When looking for this endpoint: 
https://api.travis-ci.org/jobs/360289761 

V2 returns a state "passed" (as for the build) and V3 returns "finished".
