### ISSUE TITLE
Add both UCS2/UCS4 variants of Python

### ISSUE THREAD

**Issue by gsnedders** [travis-ci/travis-ci#915]
As someone who needs to worry about compatibility outside of the BMP, I want to test my Python code under CPython both `--with-wide-unicode` and without.  (This doesn't apply to 3.3 and above where the option is gone). Having both variants available would be nice due to the fairly significant differences (i.e., even `len(u"\U0010FFFF")` varies between the two).

**Comment by vmuriart** [comment]
Whats the likelihood of implementing this? One of my projects would benefit from being able to test against both UCS2/UCS4 variants.
