### ISSUE TITLE
Build stages result is not correct when combining build stages with matrix expansion that expands to one job only

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#9157]
When the matrix expansion expands to two or more jobs then combining them with other build stages in the `jobs.include` does not cause any issues. This may sound like a nitpicking but it would be really awesome when this issue can be fixed. Imagine during experimenting one might alter the build setup by commenting off some jobs in the the job matrix then suddenly the CI build setup became broken simply because the job matrix resolve to just one job after the alteration.

**Comment by BanzaiMan** [comment]
Could you explain the problem with concrete examples?

**Comment by weitjong** [comment]
Thanks for the fast response. In this commit https://github.com/urho3d/llvm-clang/commit/deee6dfd30379e9d10bd93a478c945b287c4e0c4, if I comment off the `DUMMY=1` then the combining does not take place. Travis would just throw away the the single-job matrix and only honor the `jobs.include`.

**Comment by BanzaiMan** [comment]
I believe this is a variation of https://github.com/travis-ci/travis-ci/issues/4681; if there is only one job in the base, `matrix.include` (and `jobs.include`) will remove this job.

In your case, there is no reason for you to define `BRANCH=release_60` in the matrix; it can be inside `env.global`.

**Comment by weitjong** [comment]
> In your case, there is no reason for you to define BRANCH=release_60 in the matrix; it can be inside env.global.

It was initially inside the `env.global` and having this exact issue. So I am forced to turn it into a matrix of two jobs (one real and one dummy). :smile: That's when I decided to raise this Issue here.

Alternatively, you could say, I should just two jobs in `jobs.include` without using job matrix construct. That variant should always work. However, it would need me to rewrite the `.travis.yaml` simply because of this. Not cool.

**Comment by BanzaiMan** [comment]
> It was initially inside the env.global and having this exact issue.

Oh, you're right!

**Comment by BanzaiMan** [comment]
This behavior is unlikely to change. For you, I suggest dropping `env.matrix` and rolling the `BRANCH=release_60` job into the build stage.

**Comment by weitjong** [comment]
Thanks again for the effort. I have looked at your changes. I agree with you that should work (as I have already commented before). However, it is missing my point of raising this issue. I have hit by this issue in the past after the build stage is being introduced and only care to raise the issue yesterday. What I have encountered in the past is closer to scenario I put the in the issue description. I quote below again.

"Imagine during experimenting one might alter the build setup by commenting off some jobs in the the job matrix then suddenly the CI build setup became broken simply because the job matrix resolve to just one job after the alteration."

**Comment by weitjong** [comment]
I am OK if it would not be fixed. Just want to bring this surprisingly behavior to Travis attention. The issue could be workaround, provided one know what exactly what has happened.

Thanks for the PR that shows me the alternative workaround, BTW.
