### ISSUE TITLE
os: linux - EACCES: permission denied, unlink

### ISSUE THREAD

**Issue by vladimiry** [travis-ci/travis-ci#9159]
- It worked well https://travis-ci.org/vladimiry/protonmail-desktop-app/jobs/331193873
- But then a few days later stopped to work https://travis-ci.org/vladimiry/protonmail-desktop-app/jobs/332982617 :

```
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, unlink 'build/Makefile'
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v8.9.4/bin/node" "/home/travis/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/[secure]/protonmail-desktop-app/node_modules/keytar
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-01-29T19_03_52_596Z-debug.log
```

- `node`, `npm`, `keytar`, `node-gyp`, `node-gyp-build` versions as well as `.travis.yml` config remain the same between successful and failed builds.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/vladimiry/protonmail-desktop-app/jobs/332982617#L690

Where is `build/Makefile`, and what permissions does it have?

**Comment by vladimiry** [comment]
During the `npm install` command execution [node-gyp](https://github.com/nodejs/node-gyp) builds a native dependencies of [keytar](https://github.com/atom/node-keytar) module - `node-gyp rebuild` command. So `node-gyp rebuild command.` generates the `build/Makefile` file (`configure` stage).

What I just realized is that `node-gyp` removes the existing `build` folder before starting a new build, and it just can't remove it. `build` was restored from the `npm_moduels` cache. If I remove cache in job's settings then it starts working. So it looks like there was something wrong with permissions set to `npm_moduels` during cache unpacking.

Issue got resolved by manual cache removing. Please close if you think there is nothing to fix on your side.

**Comment by BanzaiMan** [comment]
Very well, then.
