### ISSUE TITLE
Daily CRON jobs skipped with long builds

### ISSUE THREAD

**Issue by torokati44** [travis-ci/travis-ci#9161]
On one of our projects ([INET](https://travis-ci.org/inet-framework/inet/)) we have Travis set up so that it runs once every day (using the CRON feature), on two select branches. Builds for individual pushes are disabled. Pull requests are built, but we don't nearly get them every day.

I have noticed that sometimes the scheduled builds don't get triggered, even though the last build (on both branches) was triggered by the same CRON job the day before.

The "Skip if there was a build in the last 24 hours" option was enabled; I have just disabled it to see if it solves the issue.

I don't know if this is because the "skip" feature checks for the finish time of the previous build (or the time it got out of the potential queue), or because we use build stages, or because the builds take quite a while, but I can imagine any of these as a reason.

**Comment by BanzaiMan** [comment]
When (in UTC, please) do you think a `cron` build should have run, but didn't? I took a glance at the build history, but nothing jumped out at me.

**Comment by torokati44** [comment]
About two hours ago - a couple minutes after 17:00 UTC today. I saw this on the Settings page:
"Ran about 24 hours ago | Scheduled in about 23 hours from now"

This would have been just fine, if the builds have had been triggered very recently. But they weren't, for some reason.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/inet-framework/inet/builds/335257695 and https://travis-ci.org/inet-framework/inet/builds/335257290 ran according to the `cron` schedule, no?

**Comment by torokati44** [comment]
Well, yes, according to "the new ones". Like I said, I disabled the "Skip if ... last 24 hours ..." switch after seeing that the builds didn't trigger. Which (I think?) can only be done by deleting the two old schedules, then recreating them with different settings. The creation of these two new schedules immediately triggered the builds you linked - well, about one minute after they were created.

**Comment by torokati44** [comment]
Now that I think about it...
I understand that there are no real guarantees on the precision/accuracy of the timing of the cron jobs. Is this right?
Now, could it be that had I waited just a couple more minutes, the builds would have triggered as expected, only the "scheduled in" info on the settings page isn't always consistent with the actually triggered cron jobs? And that's why I saw "scheduled in 23 hours", because this didn't take into account the possibility of a job being somewhat late?

**Comment by torokati44** [comment]
Well, since it has never happened, except for that one time (which also might have been a false alarm), it was probably just a transient inconsistency in the "last ran" and "scheduled in" texts on the interface.
So now I think there wasn't even a problem, sorry for bothering you with this.
