### ISSUE TITLE
docker pull travisci/ci-nodejs not found

### ISSUE THREAD

**Issue by kolya182** [travis-ci/travis-ci#9163]
Is this valid `https://hub.docker.com/r/travisci/ci-nodejs/` ?

`docker pull travisci/ci-nodejs
Using default tag: latest
Error response from daemon: manifest for travisci/ci-nodejs:latest not found`

**Comment by BanzaiMan** [comment]
There is no `latest` tag. https://hub.docker.com/r/travisci/ci-nodejs/tags/

But we are not updating those images any more. See https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image for using the latest image.
