### ISSUE TITLE
[Coverity] Builds are not uploaded to Coverity

### ISSUE THREAD

**Issue by wltjr** [travis-ci/travis-ci#9166]
I have several repositories and no issues with Coverity. On this new forked repo, I cannot for the life of me get the initial build uploaded to Coverity. I have no clue what is going wrong. Though it seems maybe a problem with their script and newer systems or something. I see the following output I assume is causing some problem.

```
Running Coverity Scan Analysis Tool...
sh: 1: arithmetic expression: expecting EOF: "0xdeta"
sh: 1: arithmetic expression: expecting EOF: "0xdeta"
sh: 1: arithmetic expression: expecting EOF: "0xdeta"
sh: 1: arithmetic expression: expecting EOF: "0xdeta"
sh: 1: arithmetic expression: expecting EOF: "0xdeta"
```
https://travis-ci.org/Obsidian-StudiosInc/pinentry/jobs/335785815#L1033

Not sure if this is Travis or Coverity issue. I do not recall seeing that on other repos or ever before. I know I have others using jobs and newer images without issues. I cannot explain this one. I also had [issues](https://travis-ci.org/Obsidian-StudiosInc/pinentry/builds/326156258#L1051) before I even switched to jobs. But looking at that log output, seems my build command was off.

I guess this must be a jobs and beta-feature issue. Maybe need to file on the beta-features issue tracker verse here. Not sure, filing here first and can move to beta-feature issue if need be. Thanks!

**Comment by BanzaiMan** [comment]
At the point where the error occurs, we are running https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh. In particular, it is _probably_ 

```
eval "${COVERITY_SCAN_BUILD_COMMAND_PREPEND}"
```

which is in your case 

```
COVERITY_SCAN_BUILD_COMMAND_PREPEND="${COVERITY_SCAN_BUILD_COMMAND_PREPEND:-autoreconf -f -i && automake && ./configure ${OPTS}; make clean}"
```

My guess is that this command is failing. I don't know where your build is picking up `0xdeta`, but curiously that string already happens when you run `autogen.sh`: https://travis-ci.org/Obsidian-StudiosInc/pinentry/jobs/335785815#L1367.

**Comment by wltjr** [comment]
Yes you are correct it is failing. Something is still [off with my coverity build commands](https://travis-ci.org/Obsidian-StudiosInc/pinentry/jobs/335776413#L1041). I guess maybe I should file a new issue/feature request about Travis catching that and throwing some error or the build failing.

I totally missed that Coverity wasn't running for build commands being off. Without looking at output details, I would not see the issue. Totally my fault. Just the same would be nice if it failed, so the failure stood out and was not buried in build output. I kept thinking all was well, when it clearly was not and my fault.

**Comment by wltjr** [comment]
I think you are also correct on autogen.sh causing ```0xdeta```. In another repo I have an [autogen.sh(https://github.com/Obsidian-StudiosInc/asspr/blob/master/autogen.sh) ]committed, but for some reason not using it. Just calling those commands directly. I can just bypass autogen.sh. Though does not seem to be causing general build issues. Without that I do not get a configure. Guess moot either way.

**Comment by wltjr** [comment]
Still having issues, not sure what is going wrong.

Seems the Coverity [build command](https://travis-ci.org/Obsidian-StudiosInc/pinentry/jobs/335812876#L1033) is fixed now. I dropped autogen.sh for the [raw commands](https://github.com/Obsidian-StudiosInc/pinentry/blob/master/.travis.yml#L43) I used in another [repo](https://github.com/Obsidian-StudiosInc/asspr/blob/master/.travis.yml#L3) that uploads to [coverity without issue](https://scan.coverity.com/projects/obsidian-studiosinc-asspr). I had others using [autotools](https://travis-ci.org/Obsidian-StudiosInc/entrance/builds/270985567#L778) before switching to meson. That one was using [autogen.sh](https://github.com/Obsidian-StudiosInc/entrance/blob/6c1ff1d1d77b0ca4947633e388c879d3eca28d6f/.travis.yml#L19).

Seems like the ```0xdeta``` is coming from configure or something else not sure. But I am not sure what is what is causing the problem with Coverity or not. Never had issues with getting the initial build to Coverity before. This is also a forked repo, not sure if that matters. I have it configured and ready in Coverity. Just never see the initial build.

**Comment by BanzaiMan** [comment]
Your `make` is failing. https://travis-ci.org/Obsidian-StudiosInc/pinentry/jobs/335812876#L1356

You'd need to fix that.

**Comment by wltjr** [comment]
Why is it doing that before the script? Is it because of the order in the yaml file? If you look at the next few lines of output. I am literally creating that file it is failing on. If it ran the script section of the yaml file first then coverity it would not be an issue. I guess I have to replicate the entire build env for coverity?

Which means I will move such commands from script to an actual script that is called in script section and build_command_prepend. Seems a bit odd and outside of travis config. I mean I could put much more of the build in a script and just call that.

**Comment by BanzaiMan** [comment]
I'm afraid I don't know the rationale. This is all done inside Coverity's script.

**Comment by wltjr** [comment]
Something seems odd. I do not say tell Coverity what packages to install. I do not believe it downloads its own copy of the repo etc. I thought/assumed it use Travis to build for Coverity and then some upload there. Or at least used the Travis build env with packages, etc. I guess there is another build that takes place at Coverity.

Is there no way to get it to run after the build env is setup? Already seeming to have to duplicate the build commands. I guess the whole things needs to be duplicated. No worries, all me, and my understanding or lack there of, regarding the order and what does what. Thanks

**Comment by wltjr** [comment]
I ended up with the script command wrapper route. Though I guess I could have moved some of that to install. Install is run before the coverity stuff and seems present. I can move anything needed there.
