### ISSUE TITLE
"sudo: false" breaks /etc/hosts by doubling "127.0.0.1 localhost" in the same line

### ISSUE THREAD

**Issue by scara** [travis-ci/travis-ci#9167]
Hello,
when using `sudo: false`, `/etc/hosts` looks like:
```
::1	 ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.13	travis-job-XYZ.travisci.net travis-job-XYZ
127.0.0.1 localhost 127.0.0.1	localhost 
```
i.e. the last line is doubling the `localhost` entry violating the IP/Host map, while with `sudo:required`, you get a plain:
```
127.0.1.1 travis-job-b39720bc-54bf-49ea-a648-5f0e3b1ad9bd travis-job-b39720bc-54bf-49ea-a648-5f0e3b1ad9bd ip4-loopback trusty64
127.0.0.1 localhost nettuno travis vagrant 
```
This behavior has been already reported even in #8711 but it's not the main focus there.

TIA,
Matteo

**Comment by scara** [comment]
TNX for the fix, appreciated! 👍

**Comment by scara** [comment]
Hi @BanzaiMan,
I'm sorry but the issue has been partially fixed, now we get:
```
::1	 ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.4	travis-job-XYZ.travisci.net travis-job-XYZ
127.0.0.1 localhost localhost
```
which is still not fine.
Could you kindly reopen this issue, since it looks like being there even in [your build](https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/711188#L517)?

The expected line should be:
```
127.0.0.1 localhost
```
i.e. without doubling hostnames, here `localhost`.

TIA,
Matteo

**Comment by BanzaiMan** [comment]
Is it *actually* causing a problem?

**Comment by scara** [comment]
HI @BanzaiMan,
we're trying to find the reason why Selenium is not working under `sudo: false` due to a `Bad Request` error while trying to open a session against Firefox.
Read more starting from here: https://github.com/moodlerooms/moodle-plugin-ci/issues/70#issuecomment-361662001.

Before going further w/ the investigation at our side, we'd like to exclude any "network resolution" issue.
Thoughts?

TIA,
Matteo

**Comment by BanzaiMan** [comment]
I do not think this problem of yours is related to `localhost` resolution. In https://travis-ci.org/moodlerooms/moodle-plugin-ci/jobs/335718089#L647, the error indicates that the connection to `travis-job-moodlerooms-moodle-plugin-335718089.travisci.net`, which is bound to `127.0.0.4`.

It seems to me that you are starting the server at `127.0.0.1` on port 8080 (https://travis-ci.org/moodlerooms/moodle-plugin-ci/jobs/335718089#L632). Why is your Selenium driver not connecting to that port? You can try using our Docker image, or we can enable the debug feature for moodlerooms/moodle-plugin-ci if you'd like to troubleshoot this further.

But for this issue, I do not believe there is more to be done.

**Comment by BanzaiMan** [comment]
In the passing one running on GCE, it is connecting to `localhost` on port 8080, from what I can see. https://travis-ci.org/moodlerooms/moodle-plugin-ci/builds/335233134#L661

**Comment by scara** [comment]
Hi @BanzaiMan,
- the Selenium server binding is `127.0.0.1`: https://travis-ci.org/moodlerooms/moodle-plugin-ci/jobs/335718089#L958
- `8080` is used by  the built-in PHP server to expose the Moodle webapp which is the target of these automated tests

BTW we'll keep investigating on our issue and reporting here if we'll be pretty sure that doubling `localhost` is part of the issue.
TNX for taking the time to read the other thread! Much appreciated!
