### ISSUE TITLE
Can't publish to PyPI (HTTPError: 403 Client Error: Invalid or non-existent authentication information.)

### ISSUE THREAD

**Issue by TomasTomecek** [travis-ci/travis-ci#9169]
This is the error I am getting:

```
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
```

I understand there is something wrong with the login credentials. I am using encrypted password. I encrypted it using:
```
$ travis encrypt --add deploy.password <the-password>
```

I made sure it contains only alphanumeric values.

Given the situation, I have no idea how to proceed since I can't verify that the password was encrypted correctly. Any help is greatly appreciated.

https://travis-ci.org/fedora-modularity/conu/jobs/336086222

**Comment by BanzaiMan** [comment]
Most likely the encryption was done incorrectly. Please try passing `-r fedora-modularity/conu` to `travis encrypt`.

**Comment by TomasTomecek** [comment]
That indeed helped, thanks a lot! (might be worth updating the documentation?)

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/encryption-keys#Usage has this information:

> Then, you can use `encrypt` command to encrypt data (This example assumes you are running the command in your project directory. If not, add `-r owner/project`):

If you have ideas as to how to make this more obvious, we welcome your suggestions.

**Comment by TomasTomecek** [comment]
Oh, I feel stupid now; thank you!

**Comment by AdrienHorgnies** [comment]
@TomasTomecek Nope, you're not.
Between travis cli installation process and counter intuitive `travis encrypt`, it's very confusing. I ended up using an environment variable rather than an encrypted password as I could see many people were running in the same problem as me.
