### ISSUE TITLE
Jobs involving docker pulls often hang from time to time and then timeout

### ISSUE THREAD

**Issue by kratsg** [travis-ci/travis-ci#9170]
One of the things we use TravisCI for is to build and push docker images. This has worked great a majority of the time. However, sometimes we've noticed that the `docker pull` commands just seem to.. hang? I'm not sure how to debug these, but a simple `retry` fixes things.

Here's an example of a job: https://travis-ci.org/UCATLAS/xAODAnaHelpers/jobs/335992989 where travis timed out after 10 minutes.

I tried searching in the existing issues but found nothing related.

**Comment by kratsg** [comment]
Another example failure here: https://travis-ci.org/UCATLAS/xAODAnaHelpers/jobs/327270108

**Comment by BanzaiMan** [comment]
Probably a duplicate of #9127.

**Comment by kratsg** [comment]
Indeed, a duplicate. Will close this in favor of above issue.
