### ISSUE TITLE
Failing builds for csharp on trusty

### ISSUE THREAD

**Issue by CallumDev** [travis-ci/travis-ci#9171]
Log is giving:

`The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .`

with

`E: Unable to correct problems, you have held broken packages.`

Job example: https://travis-ci.org/Librelancer/Librelancer/jobs/336159071#L428

**Comment by bartsokol** [comment]
Same here - [example](https://travis-ci.org/bartsokol/Monacs/builds/336192942#L431), cc @joshua-anderson @akoeplinger @nterry - any ideas how this can be solved? Looks like it is [repeating issue](https://github.com/travis-ci/travis-ci/issues/7290).

**Comment by akoeplinger** [comment]
Thanks, I can repro here, it looks like there's a problem in our package repository:

```
The following packages have unmet dependencies:
 fsharp : Depends: msbuild but it is not going to be installed
 mono-complete : Depends: msbuild but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I'm talking to the Linux packaging engineer to get this resolved.

In the meantime you can use `mono: alpha` as a workaround which works fine.

**Comment by akoeplinger** [comment]
The issue was resolved, sorry for the breakage 😄

**Comment by Symbianx** [comment]
@akoeplinger The fix worked, BUT after this issue was resolved I started having an issue installing the dotnet 1.0.1 package:

`0.40sE: Package 'dotnet-dev-1.0.1' has no installation candidate
The command "sudo apt-get install -qq dotnet-dev-1.0.1" failed and exited with 100 during .`

You can see the [build output here](https://travis-ci.org/nosinovacao/name-sdk/builds/336231818#L405).

**Comment by akoeplinger** [comment]
@Symbianx dotnet-dev-1.0.1 shouldn't have been working for a few months now, it was removed from the Microsoft package repositories as it is no longer supported. Please use `dotnet: 1.0.9` for the latest 1.0 version.

**Comment by Symbianx** [comment]
@akoeplinger Thanks for the quick reply, 1.0.9 did not work as travis expects the SDK version, but it got me on the right track. I set it to 1.0.4 and it worked! Thanks

**Comment by BanzaiMan** [comment]
Looks like this can now be closed.
