### ISSUE TITLE
"No such file or directory @ rb_sysopen" error on deploy to chef-supermarket

### ISSUE THREAD

**Issue by trinitronx** [travis-ci/travis-ci#9178]
Seems like there is a problem with the Chef Supermarket integration.  A recent deploy release tag build [has failed with errors like the following][1]:

    /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:1392:in `initialize': No such file or directory @ rb_sysopen - /home/travis/build/trinitronx/kodi-cookbook/Berksfile.lock (Errno::ENOENT)
    [...SNIP...] ## See build log link above for full stacktrace.

Seems like maybe this code is old and not respecting `chefignore`, which has `Berksfile.lock` listed.  So this file should not be included in cookbook deploy to supermarket.

[1]: https://travis-ci.org/trinitronx/kodi-cookbook/jobs/337177613#L1341-L1364

**Comment by BanzaiMan** [comment]
If this is due to the old version of `chef` gem we are using ([11.18.12](https://travis-ci.org/trinitronx/kodi-cookbook/jobs/337177613#L1325)), then this is a variation of https://github.com/travis-ci/dpl/issues/464.

**Comment by BanzaiMan** [comment]
Is `Berksfile.lock` supposed to exist at the time of deployment? It does not exist in the repo. If it's created during the build and the deployment is expecting to find that file, you'd need to add `skip_cleanup: true` at the right spot. https://docs.travis-ci.com/user/deployment/#Uploading-Files-and-skip_cleanup
