### ISSUE TITLE
Travis deployment with on `d: <version>` should work

### ISSUE THREAD

**Issue by wilzbach** [travis-ci/travis-ci#9179]
https://docs.travis-ci.com/user/deployment

```
 on:
   d: dmd
```

> jdk, node, perl, php, python, ruby, scala, go: for language runtimes that support multiple versions, you can limit the deployment to happen only on the job that matches a specific version.

Apparently D isn't part of the list?

**Comment by BanzaiMan** [comment]
At the moment, no.

**Comment by BanzaiMan** [comment]
I just looked at the code, and it seems to me that this should work already (meaning that the document is wrong). Have you tried it?
