### ISSUE TITLE
Web UI is sometimes not updated correctly when a build finishes

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#918]
As reported by @jakehow via a support email

"On another note there are a few spots where the UI gets stale and requires a full refresh of the app. Guessing you guys know about them already but the list of builds doesn't seem to be updated when you click the Travis icon.

If you are sitting on the build page, even when a build finishes, the build stays yellow and the clock keeps counting off seconds."

@drogus, have you ever seen this?

**Comment by roidrage** [comment]
Closing this issue for now, as there's been no updates or new reports on for more than a year.
