### ISSUE TITLE
Python: 3.7-dev seems to have a problem w/ setuptools installation in venv

### ISSUE THREAD

**Issue by jenisys** [travis-ci/travis-ci#9181]
Python3.7 dev builds seems to have a problem since approx. 1 day.
Job #518.7 fails with setuptools installation problem in step "python setup.py -q install".
Job #578.7 (16 days ago) is fine and ran without any problems.

SEE ALSO:
* https://travis-ci.org/behave/behave/builds/337298899

**Comment by BanzaiMan** [comment]
I tend to think this is an issue with Python development. Inform the Python team, or wait for the issue to be fixed.

**Comment by BanzaiMan** [comment]
We have not changed the way we compile things in quite some time.

I'm closing this now, as I don't think there is anything to do on our side.
