### ISSUE TITLE
 jdk 9 build ignores "script" directive

### ISSUE THREAD

**Issue by tebeka** [travis-ci/travis-ci#9182]
I'm installing newer version of gradle since the 4.0 installed does not support JDK 9.

The `script` directive is executed in jdk8 builds but is ignored in the jdk9 build.
See https://travis-ci.org/tebeka/nuclio-java-sdk/builds/337520651

**Comment by BanzaiMan** [comment]
https://travis-ci.org/tebeka/nuclio-java-sdk/jobs/337520653#L445 indicates that OpenJDK 9 is in use. How did you conclude that it was not?

**Comment by tebeka** [comment]
@BanzaiMan The problem is not the JDK version, the problem is that travis ignored the `script` directive in `.travis.yml` (the two other SDKs do not)

**Comment by BanzaiMan** [comment]
Oh, indeed, this is strange.

**Comment by BanzaiMan** [comment]
I used the same configuration in https://travis-ci.org/BanzaiMan/travis_production_test/jobs/338016738, but it didn't exhibit this problem.

**Comment by BanzaiMan** [comment]
@iriberri pointed out to me that the command that is failing is the default `install`, when `gradle assemble` is executed. If you need to update gradle, you should do that in `before_install`. Alternatively, you can skip or override `install` to suppress `gradle assemble`.

**Comment by tebeka** [comment]
That worked, thanks.
