### ISSUE TITLE
Deployment to S3 not working

### ISSUE THREAD

**Issue by vatbub** [travis-ci/travis-ci#9184]
Hi there,
I just realized that deployment to S3 stopped working. I am getting the following error:
```
/home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/s3.rb:47:in `chdir': no implicit conversion of Array into String (TypeError)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/s3.rb:47:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider.rb:154:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider.rb:154:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/s3.rb:75:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

[Last build that worked](https://travis-ci.org/vatbub/HearingAidAndroid/builds/337758600)
[First build that failed](https://travis-ci.org/vatbub/HearingAidAndroid/builds/337798954)

Please note: I did some changes to `.travis.yml` for the builds inbetween the above mentioned builds which caused the builds to fail. I reverted those changes then which revealed the S3 deployment not working.

Would be great if you guys could help, greetings,
vat

**Comment by BanzaiMan** [comment]
Look at the difference between the successful and failing commits, in particular, your `local_dir` value: https://github.com/vatbub/HearingAidAndroid/compare/afb1331c43ec194c3b143531da6e76a7a927fffb...6a86c6fa62da#diff-354f30a63fb0907d4ad57269548329e3R42

This needs to be a scalar, not an array. https://docs.travis-ci.com/user/deployment/s3#Deploy-From-Only-One-Folder

**Comment by vatbub** [comment]
Ah, thanks :) Forgot that I changed that :/
