### ISSUE TITLE
Builds suddenly fail with "No output has been received in the last 10m0s"

### ISSUE THREAD

**Issue by codepunkt** [travis-ci/travis-ci#9185]
I didn't change the configuration and the tests all passed.

Example:
https://travis-ci.org/codepunkt/mongoose-patch-history/jobs/322790191

I'm not sure why this happens and what i can do to resolve this.
Please investigate!

**Comment by Monkeyboy2805** [comment]
This is intentional due to the message it throws at you. This is nothing to do with your config. It's more likely it's just one of your tasks taking too long to run.

**Comment by codepunkt** [comment]
In this case i'd expect the error message to tell me what task/step took too long to run - which it doesn't.

**Comment by BanzaiMan** [comment]
If you look up, https://travis-ci.org/codepunkt/mongoose-patch-history/jobs/322790191#L994 says it was `npm test`.

**Comment by codepunkt** [comment]
That's under the assumption that the log output is correct and the next step would have definately caused a log output? Or is some default end-output missing?

Looks like a normal test run to me.

**Comment by BanzaiMan** [comment]
Yes, and there might have been a problem, that's true. Before we investigate any further, though, could you restart this month-old build to ensure that the problem still persists today?

Thanks.

**Comment by codepunkt** [comment]
Restarted it with the same result.

**Comment by BanzaiMan** [comment]
![job__73_2_-_codepunkt_mongoose-patch-history_-_travis_ci](https://user-images.githubusercontent.com/25666/35879544-793fbdfa-0b49-11e8-8e40-ca3bdd78a235.png)

It's still a month old.

**Comment by codepunkt** [comment]
Not sure why it says that. Did the whole thing again. Doesn't say "about a month ago" now, even though the result is the same, again.

**Comment by BanzaiMan** [comment]
Thanks for testing again. I see that now. I am thinking there is a problem with this commit. I used our Docker image, and went through the build steps in this commit, and can produce the hang at the exact same spot.

**Comment by codepunkt** [comment]
Thanks for all your work on this issue, it's very appreciated! 👍
