### ISSUE TITLE
Continuous deployment with public github repositories and travis encrypt

### ISSUE THREAD

**Issue by strtwtsn** [travis-ci/travis-ci#9188]
We are looking at setting up continuous deployment for our ruby on rails apps which are currently deployed using Capistrano. They are stored in public repo's on github.

I have read the documentation on how to do this with travis-ci.org and it looks like you do something similar to the following:-

```
gem install travis 
travis login 
travis encrypt DEPLOY_KEY="password" --add 
openssl aes-256-cbc -k "password" -in deploy_id_rsa -out config/deploy_id_rsa_enc_travis -a 
```

Then add this to the travis.yml file

```
after_success:   
 - "openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa"  
 - "bundle exec cap deploy" 
```

and this to your deploy.rb file

`set :ssh_options, keys: ["config/deploy_id_rsa"] if File.exist?("config/deploy_id_rsa") 
`

Now my question is, how does this keep the private keys safe. I'm guessing you only commit the following files to the github public repo.

```
config/deploy_id_rsa_enc_travis 
travis.yml 
deploy.rb 
```

and the that private key should be deleted, not committed.

Is there anything else I should look out for?

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/encrypting-files shows you how to encrypt files.
