### ISSUE TITLE
before_deploy not being run before "script provider" deploy script

### ISSUE THREAD

**Issue by brianjmurrell** [travis-ci/travis-ci#9189]
Given the following travis config:

```json
{
  "jobs": {
    "include": [
      {
        "stage": "test",
        "env": "Type='virus scan'",
        "script": [
          "sudo apt-get install clamav -y",
          "sudo freshclam",
          "clamscan --quiet -r ./"
        ]
      },
      {
        "stage": "test",
        "env": "Type='mock build test'",
        "sudo": "required",
        "services": [
          "docker"
        ],
        "before_install": [
          "sudo apt-get update",
          "echo 'DOCKER_OPTS=\"-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper\"' | sudo tee /etc/default/docker > /dev/null",
          "sudo service docker restart",
          "sleep 5",
          "sudo docker pull centos:centos7"
        ],
        "script": [
          "./include/setup_tests.sh"
        ]
      },
      {
        "stage": "deploy",
        "env": "Type='Copr deploy'",
        "before_deploy": [
          "openssl aes-256-cbc -K $encrypted_693d4289a92e_key -iv $encrypted_693d4289a92e_iv -in include/copr-mfl.enc -out include/copr-mfl -d",
          "openssl aes-256-cbc -K $encrypted_693d4289a92e_key -iv $encrypted_693d4289a92e_iv -in include/copr-me.enc -out include/copr-me -d",
          "yum -y install rpm-build rpmdevtools copr-cli yum-utils"
        ],
        "provider": "script",
        "script": "make iml_copr_build"
      }
    ]
  },
  "language": "ruby",
  "group": "stable",
  "dist": "trusty",
  "before_deploy": [
    "openssl aes-256-cbc -K $encrypted_693d4289a92e_key -iv $encrypted_693d4289a92e_iv -in include/copr-mfl.enc -out include/copr-mfl -d",
    "openssl aes-256-cbc -K $encrypted_693d4289a92e_key -iv $encrypted_693d4289a92e_iv -in include/copr-me.enc -out include/copr-me -d",
    "yum -y install rpm-build rpmdevtools copr-cli yum-utils"
  ],
  "env": "Type='Copr deploy'",
  "provider": "script",
  "script": "make iml_copr_build",
  "stage": "deploy",
  "os": "linux"
}
```
[note the incidence of #9090 at the end there]

the `before_deploy` command list is not being executed before the _deploy script_.  Shouldn't it be?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by brianjmurrell** [comment]
https://travis-ci.org/intel-hpdd/nodejs/jobs/337793232

**Comment by BanzaiMan** [comment]
Your `script` command failed, so there is no deployment.

**Comment by BanzaiMan** [comment]
`before_deployment` will not run without a successful `script`.

**Comment by BanzaiMan** [comment]
Also, you do not have a valid deployment definition in https://github.com/intel-hpdd/nodejs/blob/116e17d00ac439c76504b31226cfae499b2e9ded/.travis.yml#L29

Please review https://docs.travis-ci.com/user/deployment/script.

**Comment by brianjmurrell** [comment]
Is the [script:](https://github.com/intel-hpdd/nodejs/blob/116e17d00ac439c76504b31226cfae499b2e9ded/.travis.yml#L30) not the script that is supposed to be run as the deploy action, for a `provider: script` type deploy action?

**Comment by brianjmurrell** [comment]
So, for the top example on [this page](https://docs.travis-ci.com/user/deployment/script), is `scripts/deploy.sh` not the script that gets run to do the actual deployment, similar how how a deployment to _npm_ would happen if I used `provider: npm` instead?

**Comment by BanzaiMan** [comment]
Also, keep in mind that the jobs in a build are independent. What you've done in the `test` stages do not persist to the last job in the `deploy` stage.

**Comment by brianjmurrell** [comment]
Yes, I understand the independence of jobs in stages.

**Comment by BanzaiMan** [comment]
`scripts/deploy.sh` is in `deploy.script`, not `script`. `provider: npm` doesn't support the `script` key under `deploy`.

At any rate, your `deploy` job definition is not what you insist.

```yaml
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_693d4289a92e_key -iv $encrypted_693d4289a92e_iv -in include/copr-mfl.enc -out include/copr-mfl -d
    - openssl aes-256-cbc -K $encrypted_693d4289a92e_key -iv $encrypted_693d4289a92e_iv -in include/copr-me.enc -out include/copr-me -d
    - yum -y install rpm-build rpmdevtools copr-cli yum-utils
    deploy:
      provider: script
      script: make iml_copr_build
```

**Comment by BanzaiMan** [comment]
I just noticed that you are trying to encrypt multiple files. This does not work. https://docs.travis-ci.com/user/encrypting-files#Encrypting-multiple-files

**Comment by brianjmurrell** [comment]
So yes, `deploy.script` is where I want my `script: make iml_copr_build`.  [How] can I do that with build stages?

**Comment by brianjmurrell** [comment]
This does seem to be working now that I got my `script` key under the `depoy` key properly.  Thanks for showing me the way.

**Comment by BanzaiMan** [comment]
Great to hear that you were able to resolve the issue!
