### ISSUE TITLE
ruby 2.0.0p647 on mac missing stringio?

### ISSUE THREAD

**Issue by segiddins** [travis-ci/travis-ci#9190]
See https://travis-ci.org/CocoaPods/cocoapods-downloader/jobs/338116488 -- requiring rubygems seems to fail because stringio (part of the stdlib in 2.0) cannot be required

**Comment by BanzaiMan** [comment]
In https://travis-ci.org/CocoaPods/cocoapods-downloader/jobs/338116488#L53, you see that RVM is finding an archive that is on rvm_io.global.ssl.fastly.net. I am not sure if that has to do with the problem you are seeing, though; I'm just pointing it out. We don't have any archive of 2.0.0 for High Sierra at the moment. http://rubies.travis-ci.org/

**Comment by BanzaiMan** [comment]
We can try compiling our 2.0.0 archive for High Sierra to see if that fixes the problem, or we can enable the debug feature on this repository to troubleshoot further.

**Comment by segiddins** [comment]
Thanks for looking into this :)

**Comment by manicmaniac** [comment]
@BanzaiMan  Is there any progress?

**Comment by BanzaiMan** [comment]
Looks like 2.0.0 goes to p648. Do you really need p647?

**Comment by BanzaiMan** [comment]
http://rubies.travis-ci.org/osx/10.12/x86_64/ruby-2.0.0-p648

**Comment by BanzaiMan** [comment]
`2.0.0` (which points to p648) should work. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/353634193#L79

Not sure if it is worth repackaging p647.

**Comment by segiddins** [comment]
we tested against p647 explicitly since it was an OS X system ruby

**Comment by BanzaiMan** [comment]
The ∂ between p647 and p648: https://github.com/ruby/ruby/compare/v2_0_0_647...v2_0_0_648

And the corresponding announcement: https://www.ruby-lang.org/en/news/2015/12/16/ruby-2-0-0-p648-released/
