### ISSUE TITLE
Xcode version environment variable?

### ISSUE THREAD

**Issue by gnzlbg** [travis-ci/travis-ci#9194]
When using for example `osx_image: xcode.7.3`  is there a way to obtain the value of `osx_image` from within the travis script via an environment variable ?

The docs don't say: https://docs.travis-ci.com/user/reference/osx/#Environment-variables

Maybe `TRAVIS_OSX_IMAGE` ?

**Comment by BanzaiMan** [comment]
What do you want that can't be obtained by `xcodebuild -version`?

**Comment by gnzlbg** [comment]
> What do you want that can't be obtained by xcodebuild -version?

Nothing.

**Comment by BanzaiMan** [comment]
This information is not currently passed around (in a way that can be used to set an env var), and adding this feature is a bit of work. The usefulness seems limited, so it is unlikely that we will be adding this feature. Since you can get the information you need with `xcodebuild -version`, please use that in the mean time.

**Comment by gnzlbg** [comment]
The build matrix shows a `Xcode` key:

![screen shot 2018-02-07 at 18 04 13](https://user-images.githubusercontent.com/904614/35930112-5f4e470c-0c31-11e8-88df-29e6acc8b2b6.png)

which is next to the `Rust` key, for which travis already exposes an environment variable. 

While I can build a parser to parse the result of `xcodebuild -version` for all `xcodebuild` binaries of all `Xcode` versions between 6.4 and at least 9.2 but probably forever (since what I am hearing is that this is a problem that you never plan to solve), I think that doing so is "ridiculous" giving that this information is already in the build matrix.

**Comment by BanzaiMan** [comment]
I was mistaken that this information was not passed on to the component responsible for setting environment variables. It is. (The web page's information comes from a different source.)

**Comment by BanzaiMan** [comment]
The PR above sets it, as long as it is done so in the configuration. If it is not, it is empty, because the default image selection is done outside of the configuration.

**Comment by gnzlbg** [comment]
@BanzaiMan thanks! I can test whether the env variable exist to know if the default configuration is being used (I think it maps to Xcode 8.3). If the default ever changes it might be worth it to make sure that this env variable is always set.
