### ISSUE TITLE
"No builds for this repository", travis-ci.com

### ISSUE THREAD

**Issue by sultanassi95** [travis-ci/travis-ci#9195]
What's up!

I'v just syncronized my account with travis-ci.com and fetched my private repo:
https://github.com/gazaskygeeks/mpcc-assistant/

travis-ci for it is:
https://travis-ci.com/gazaskygeeks/mpcc-assistant

even when .travis.yml is present on MASTER branch.
it still won't build.
fix?

**Comment by BanzaiMan** [comment]
@sultanassi95 I checked our records, and found that you've run out of trials, and have no current subscription. I've added 50 trials, so you can build now, but please consider subscribing to our services.

Thanks.

**Comment by sultanassi95** [comment]
Oooh Man ,, much of love to ur generousity <3
@BanzaiMan
