### ISSUE TITLE
[Request] Trigger build for any open pull requests after merging another pull request

### ISSUE THREAD

**Issue by jonathann92** [travis-ci/travis-ci#9197]
Hi,

I would like to request a feature to rebuild any open pull requests for the base branch after merging a different pull request to the base branch.

For example, I have a base branch named "master" and two feature-1 and feature-2 that derive from master. Feature 1 and feature 2 both have changes, however feature-1 changed a value in the solution (like a constant value) and made changes accordingly so that tests pass, but feature 2 didn't change that value. 

Both of them make a pull request to merge back into the master branch. So when they both make a pull request to master they have passing builds and unit tests. But if you try to make a pull request from feature-2 into feature-1 travis will try to build and the unit tests fail. After merging feature-1 into the master branch, the pull request of feature-2 into master is still showing a passing when in reality feature-2 merging into master will not pass anymore because it has feature-1's changes. 

I would like to add a feature so that when feature-1 gets merged into the master branch then travis will rebuild any pull requests that master has open. Or maybe when there is a commit to a branch travis should check if there are any open pull requests going into that branch then run the build on the pull request.

**Comment by BanzaiMan** [comment]
Sounds like a duplicate/variant of #1620.

Updating the branch on the outstanding PR should achieve the same goal, by the way.

**Comment by endzyme** [comment]
+1 to this request

If a PR already has approvals then rerunning CI on upstream changes would block if it would potentially introduce problems -- This would be nice to be able to configure. (pro-subscriber)

**Comment by BanzaiMan** [comment]
Can we close this as a duplicate, though?
