### ISSUE TITLE
PyQt5 5.10 during nosetests causes Segmentation fault (core dumped) but not locally

### ISSUE THREAD

**Issue by algorys** [travis-ci/travis-ci#9202]
**Impacted Project:** [Alignak-app](https://github.com/Alignak-monitoring-contrib/alignak-app)
**Python:** 3.5, 3.6

Pip freeze:
```bash
alignak-backend-client==1.2.1
astroid==1.6.1
attrs==17.3.0
certifi==2018.1.18
chardet==3.0.4
configparser==3.5.0
cov-core==1.15.0
coverage==4.5
coveralls==1.2.0
docopt==0.6.2
future==0.16.0
idna==2.6
isort==4.3.3
lazy-object-proxy==1.3.1
linecache2==1.0.0
mccabe==0.6.1
mock==2.0.0
nose==1.3.7
nose-cov==1.6
numpy==1.13.3
pbr==3.1.1
pluggy==0.6.0
py==1.5.2
pycodestyle==2.3.1
pylint==1.8.2
PyQt5==5.10
pytest==3.3.0
python-gettext==3.0
requests==2.18.4
sip==4.19.7
six==1.11.0
traceback2==1.4.0
unittest2==1.1.0
urllib3==1.22
wrapt==1.10.11
```

When I run nosetests locally for this project, with PyQt5 5.10 installed (for Python 3.5), everything works fine.

But when running on Travis, it raise:

```bash
/home/travis/.travis/job_stages: line 57:  4166 Segmentation fault      (core dumped) nosetests -xv --nologcapture --with-coverage --cover-package=alignak_app test/test_*.py
```
Example: [travis build](https://travis-ci.org/Alignak-monitoring-contrib/alignak-app/jobs/339046990#L816)

After some research I found that if I go down version of PyQt `5.10`  to `5.9.2`, the tests pass. 

I open issue here because locally, tests are OK with `5.10`.

**Comment by BanzaiMan** [comment]
Could you try reproducing the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)?

**Comment by algorys** [comment]
@BanzaiMan Hello, I've tried with your docker image `travisci/ci-garnet:packer-1512502276-986baf0` but when I launch this docker image, I've only **Python 3.4** installed.

I've tried to install **Python 3.5**, but I can't. Is there some commands to do that ? Because **PyQt5 5.10** is only available for at least Python 3.5.

**Comment by BanzaiMan** [comment]
You'll need to activate virtualenv. See https://travis-ci.org/Alignak-monitoring-contrib/alignak-app/jobs/339046989#L436 https://travis-ci.org/Alignak-monitoring-contrib/alignak-app/jobs/339046990#L431

**Comment by algorys** [comment]
Ok,

I did not think about virtual environments. So I activated Python 3.6 and PyQt installs in the right version.
So I can reproduce the error with your docker image:

```bash
nosetests -xv --nologcapture --with-coverage --cover-package=alignak_app test/test_*.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-travis'
Segmentation fault (core dumped)
```
