### ISSUE TITLE
No devtools package during before_install step

### ISSUE THREAD

**Issue by sshenoy-mdsol** [travis-ci/travis-ci#9204]
@craigcitro and @jimhester

I'm building with two R versions - 3.3 and bioc-release. My package requires installing a package from a private repo so I have been using:
```
before_install:
 - R -e "if (!require('extremevalues')) devtools::install_github('mdsol/extremevalues/cran', auth_token = Sys.getenv('CI_USER_TOKEN'))"
```
This worked fine for both versions of R yesterday but today the build with bioc-release succeeded and the build for R version 3.3 failed:
`Error in loadNamespace(name) : there is no package called ‘devtools’`

Should I not assume that devtools is available during the before_install step? Is there another way I should be doing this? The package that I am installing from a private repo has the same name as a package that is available on CRAN but the CRAN version fails to build on travis, hence the need to install this one first.

**Comment by gwarnes-mdsol** [comment]
The R function `devtools::install_github` looks in the environment variable `GITHUB_PAT` for the github auth token, so you should be able to copy the contents of `CI_USER_TOKEN` into `GITHUB_PAT` and simply include the private repo in `r_github_packages`.

This seems to work:
```
...
env:
  - GITHUB_PAT: $CI_USER_TOKEN

r_github_packages:
  - mdsol/extremevalues/cran
...
```

**Comment by sshenoy-mdsol** [comment]
Thanks!
