### ISSUE TITLE
Support for pypy3 v5.9+ (preferably v5.10.1-final)

### ISSUE THREAD

**Issue by carver** [travis-ci/travis-ci#9206]
Currently, [the default "pypy3" is 5.8.0-beta0](https://docs.travis-ci.com/user/languages/python/#PyPy-Support).

pypy3 5.8 final was released June 2017, and doesn't support some Py3 features. It would be great to get pypy3 upgraded.

Specifically for my use case: The `cytoolz` python library requires `PyFrozenSet_New` which is only available in 5.9 and above.

**Comment by BanzaiMan** [comment]
The PyPy naming scheme changed a while ago, and this is not properly reflected in the documentation.

**Comment by BanzaiMan** [comment]
Use `python: pypy3.5` instead.
