### ISSUE TITLE
deploy.tag_name value is not honored when deploying to GitHub Releases

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#9208]
I've configured a deployment to GitHub Releases. It contains the following:
1. condition `if: tag IS blank`
2. pushing git tag as a part of `before_deploy` if it doesn't exist already.
3. deploy section:

```yaml
deploy:
  provider: releases
  tag_name: "${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}"
```

The issue is being reproduced when I restart any build, which is not the latest one.

Example: the latest build number is 200. If I restart build with number 199 and then when it comes to deployment, it ignores `tag_name` value (`master/199`) and tries to deploy to the latest available tag, which is `master/200`.

Log:
```
Preparing deploy
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
From github.com:eko-point/feeding
 * [new tag]         master/199            -> master/199
 * [new tag]         master/200            -> master/200

Current tag is: master/200 <-- THIS IS WRONG
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by Deilan** [comment]
@BanzaiMan https://travis-ci.com/eko-point/feeding/builds/64492471

**Comment by BanzaiMan** [comment]
Thanks. I see the bug here. `tag_name` is read from `$TRAVIS_TAG`, and when it is not set, the command `git describe --tags --exact-match` is used to compute it. The option `tag_name` is not used at all.

**Comment by Deilan** [comment]
Not stale.
