### ISSUE TITLE
Deploying Twice

### ISSUE THREAD

**Issue by rmb938** [travis-ci/travis-ci#9212]
I have the following travis yaml https://github.com/rmb938/pyk8s-controller/blob/master/.travis.yml that runs python tox commands with different environment variables set. Then deploys the application to pypi.

However it seems that how things are deployed has changed from a few months ago. It seems like the deployment step triggers once for each job, instead of just once for the whole build.

Link to build: https://travis-ci.org/rmb938/pyk8s-controller/builds/339937137

**Comment by BanzaiMan** [comment]
You need to specify condition(s) under which the deployment occurs with `on`. This behavior is explained in https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A and has not changed in some time.
