### ISSUE TITLE
deploy gh-pages: Symlinks don't get copied

### ISSUE THREAD

**Issue by lschuermann** [travis-ci/travis-ci#9214]
When using the `pages` deploy provider, symlinks in the `local-dir` don't get commited.

From the Travis output I'm guessing that it is first using `rsync` to copy all the files to some `/tmp/${id}/work` directory and committing from there. The log says

    skipping non-regular file "index.html"

This behavior can be seen in [this build](https://travis-ci.org/flatrapp/api/builds/340486373#L497) for example. I find it rather inelegant to copy and commit two exact same files and I'm guessing that a missing symlink support could also result in some other software not working as expected.

**Comment by lumag** [comment]
Was hit by more or less the same issue. It would be nice to be able to enforce pushing all files into GH pages, not only "regular" ones.

**Comment by fpoirotte** [comment]
I stumbled upon this too.
Adding the ``--links`` option to rsync would probably do the trick.
