### ISSUE TITLE
Travis won't test pull requests for my feature branch

### ISSUE THREAD

**Issue by nex3** [travis-ci/travis-ci#9215]
I have a branch, `feature.solver`, in the https://github.com/dart-lang/pub repository. This repository is [configured](https://github.com/dart-lang/pub/blob/feature.solver/.travis.yml#L24) to run tests on any branch that matches `/^feature\./`, and indeed Travis [does run tests](https://travis-ci.org/dart-lang/pub/builds/339779199) for the branch.

I also have [a pull request](https://github.com/dart-lang/pub/pull/1802) to this branch. The pull request is on a branch named `solver.lockfile`, and Travis isn't running tests for it. This seems wrong; I'd expect Travis to run tests for all pull requests that target testable branches.

Interestingly, Travis *did* run tests for [a previous pull request](https://github.com/dart-lang/pub/pull/1799) to this branch which was on a branch named `feature.solver.tests`. However, it ran those tests twice: [once as a branch](https://travis-ci.org/dart-lang/pub/builds/339729801) and [once as a pull request](https://travis-ci.org/dart-lang/pub/builds/339729822).

I'd like Travis to run the tests only once, and I'd like them to run even if my pull request's branch name doesn't match `/^feature\./`, just like for pull requests to the `master` branch.

**Comment by BanzaiMan** [comment]
Looks like we are eager on rejecting a certain kind of PR build requests. We'll look into it. Sorry for the inconvenience.

**Comment by BanzaiMan** [comment]
@nex3 Hello, there. Could you reproduce the issue now, so we have a new baseline of the current behavior? Thanks, and sorry for the delay.

**Comment by nex3** [comment]
I'm about to start landing PRs against a new feature branch, so I'll let you know how it goes.

**Comment by nex3** [comment]
Based on https://github.com/sass/dart-sass/pull/592, it looks like this issue doesn't reproduce anymore :smile:.
