### ISSUE TITLE
failing to run encrypted command

### ISSUE THREAD

**Issue by andreineculau** [travis-ci/travis-ci#9219]
Based on the docs, I was expecting that all occurencies of `secure: "..."` will be expanded in the `.travis.yml` file before the actual run.

So I have tried with

```yml
before_install:
  - secure: "<encrypted command with secure arguments>"
```

but it doesn't look like travis is expanding it and instead is trying to execute the encrypted string. See https://travis-ci.org/tobiipro/support-firecloud/jobs/340918564

Am I trying to do the impossible here, or what gives?

**Comment by BanzaiMan** [comment]
Indeed, those sections do not get processed for secrets.

**Comment by andreineculau** [comment]
Ok. Is it not a simpler rule to say that any object with one property named "secure" will be decrypted, no matter where it is in the travis config?

Talking specifically about this case (commands in before_install, install, etc) it is much safer to encrypt the whole command than have an env variable, then use it, then make sure to dispose of it (add a command "unset VARNAME") just to make sure that it doesn't leak.
