### ISSUE TITLE
API V3 /jobs endpoint seems broken

### ISSUE THREAD

**Issue by surli** [travis-ci/travis-ci#9220]
I'm experiencing issues with the /jobs endpoint in Travis V3:

> curl -H "Travis-API-Version: 3" -H "User-Agent: API Explorer"   -H "Authorization: token XXXXX"   https://api.travis-ci.org/jobs?limit=2
Sorry, we experienced an error.

> request_id:b65925a1-22d2-40bd-b6c2-3c2edfad3185

This was executed the Wed Feb 14 10:12:18 CET 2018

**Comment by BanzaiMan** [comment]
Looks like a bug on the API. We'll look into it.
