### ISSUE TITLE
Travis build failing with ci:build:validate:test error

### ISSUE THREAD

**Issue by sandipsmarty** [travis-ci/travis-ci#9221]
While executing the following script it throws error.

$ blt -Dbehat.run-server=true -Dcreate_alias=false -Dbehat.launch-phantom=true ci:build:validate:test -Dblt.verbose=true

[Symfony\Component\Console\Exception\CommandNotFoundException]       
  There are no commands defined in the "ci:build:validate" namespace.  
                                                                       
  Did you mean this?                                                   
      simplesamlphp:build                                              

Can anyone please help?

**Comment by BanzaiMan** [comment]
Looks like a PHP application error, no?

**Comment by sandipsmarty** [comment]
Not sure exactly, build happened successfully for my last commit. In my latest code changes I just updated composer files with some required drupal modules & related configuration changes.

**Comment by BanzaiMan** [comment]
I don't think this is a Travis CI issue. If you find evidence to indicate otherwise, please include it.
