### ISSUE TITLE
mysql-5.7-trusty install fails

### ISSUE THREAD

**Issue by osahner** [travis-ci/travis-ci#9222]
```
{
  "language": "java",
  "jdk": "oraclejdk8",
  "services": [
    "mysql"
  ],
  "addons": {
    "apt": {
      "sources": [
        "mysql-5.7-trusty"
      ],
      "packages": [
        "mysql-server",
        "mysql-client"
      ]
    }
  },
  "sudo": "required",
  "before_install": [
    "sudo mysql_upgrade --force",
    "sudo mysql -e ...",
    "sudo service mysql restart"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
```

```
The following packages have unmet dependencies:
 mysql-client : Depends: mysql-client-5.5 but it is not going to be installed
 mysql-server : Depends: mysql-server-5.5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by osahner** [comment]
strange thing ... no change and it worked again

**Comment by uN1ck** [comment]
Have this problem too. Don't now how to solve :(

**Comment by cliffbroadbent** [comment]
This error has made an appearance over the past 24 hours. Following https://docs.travis-ci.com/user/database-setup/#mysql-57 reproduces this fault.

Wondering if https://github.com/travis-ci/apt-source-safelist/pull/400 may be related.

**Comment by cotsog** [comment]
If it's an option, you can use our Xenial image where this issue isn't happening at this time. Just add `dist: xenial` to your .travis.yml file to get it.

**Comment by cliffbroadbent** [comment]
Switching over to Xenial and using the default MySQL 5.7 worked as intended.

See: https://docs.travis-ci.com/user/database-setup/#mysql

Example changes:
```yaml
dist: xenial

services:
  - mysql

addons:
#  apt:
#    sources:
#      - mysql-5.7-trusty
#    packages:
#      - mysql-server
#      - mysql-client
```

**Comment by cotsog** [comment]
Just wanted to close the loop here.

It seems the MySQL 5.7 packages for Trusty [won't be generated anymore](https://forums.mysql.com/read.php?11,677237,677268#msg-677268):

> Unfortunately, as Ubuntu 14.04 has reached end of life, we no longer support it or publish updates for it. 
>
> Since the OS itself no longer receives important security updates, it's strongly recommended to upgrade, e.g. to Ubuntu 16.04 or 18.04.

As @cliffbroadbent mentioned, the current recommendation is to run your builds on Xenial where MySQL 5.7 is pre-installed. Here's what to add to your .travis.yml file:

```
dist: xenial

services:
  - mysql
```
