### ISSUE TITLE
Not registering deploy config

### ISSUE THREAD

**Issue by jacobp100** [travis-ci/travis-ci#9225]
I have it set up to deploy to npm in my [travis.yml](https://github.com/jacobp100/yoga-prebuilt/blob/master/.travis.yml). I've tried just about every combination on `deploy.on`, but I can't get it to deploy. I don't even get any messages such as _skipping a deployment with the releases provider because this is not a tagged commit_. It just mentions nothing about deployment, and shows nothing about deployment on the [build config](https://travis-ci.org/jacobp100/yoga-prebuilt/jobs/341798579/config).

My builds are [here](https://travis-ci.org/jacobp100/yoga-prebuilt).

Is this something I'm doing wrong, or is there an issue where deployments are being ignored?

**Comment by BanzaiMan** [comment]
My guess is this: https://github.com/jacobp100/yoga-prebuilt/blob/a83e95065a1d3c8287adb5d75ee7ca0d88ab543c/.travis.yml#L16 where `script` is an empty array, which is causing the deployment to not trigger. Try a command that actually succeeds (e.g., `true` or `echo`) or special keyword `script: skip`.

**Comment by jacobp100** [comment]
That fixed it! Thanks!
