### ISSUE TITLE
Any way to make a build wait more than 50 minutes? We really like our unit tests :)

### ISSUE THREAD

**Issue by imarios** [travis-ci/travis-ci#9229]
https://github.com/typelevel/frameless

**Comment by BanzaiMan** [comment]
Please email us at support@travis-ci.com with details, and we'll see what we can work out.

In the mean time, there is nothing to do on this ticket, so I'm closing this.

**Comment by imarios** [comment]
Thank you Hiro @BanzaiMan, I just wrote an email give more details about the issue we are facing. Best!
