### ISSUE TITLE
python 3.8-dev not working: bzip2: (stdin) is not a bzip2 file.

### ISSUE THREAD

**Issue by reox** [travis-ci/travis-ci#9230]
The documentation says that python 3.8-dev is available, so I added it to the travis configuration.
But it seems that the downlaoded file is not a bzip2 file:
```
3.8-dev is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.8-dev.tar.bz2
$ sudo tar xjf python-3.8-dev.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command "sudo tar xjf python-3.8-dev.tar.bz2 --directory /" failed and exited with 2 during .
```

I tried to download that file manually, but I get a 403:
```
$ wget  https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.8-dev.tar.bz2
--2018-02-15 04:38:28--  https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.8-dev.tar.bz2
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.96.37
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.96.37|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-02-15 04:38:28 ERROR 403: Forbidden.
```

here is the job: https://travis-ci.org/androguard/androguard/jobs/342095318

**Comment by BanzaiMan** [comment]
The Python trunk development now requires a newer version of OpenSSL library; see https://github.com/travis-ci/travis-ci/issues/9069. Consequently, `3.7-dev` and `3.8-dev` (alias `nightly`) no longer works.

I'm closing this as a duplicate.

**Comment by SylvainDe** [comment]
Should the documentation be updated for the time being ?

**Comment by BanzaiMan** [comment]
@SylvainDe Please see the issue I referred to. https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-366186791
