### ISSUE TITLE
Deployment to PyPI fails

### ISSUE THREAD

**Issue by pancetta** [travis-ci/travis-ci#9232]
For some reason, updated version do not find their way to PyPI. Travis-CI fails at "Installing deploy dependencies", see e.g. [here](https://travis-ci.org/Parallel-in-Time/pySDC/jobs/342253480#L2027). 

Interestingly, the first thing which happens here seems to be the execution of `https://bootstrap.pypa.io/get-pip.py`. When I look a previous (successful) builds like [this one](https://travis-ci.org/Parallel-in-Time/pySDC/jobs/316877378), Travis-CI refers to `https://bootstrap.pypa.io/ez_setup.py`. I don't know if this is the reason for the current problem, though.

Also, I have no idea what to do about it. Manual deployment via `python setup.py ...` works, but I'd rather work with Travis-CI's own way of handling things. Any ideas/help?

**Comment by mottosso** [comment]
Also seeing this [here](https://travis-ci.org/pyblish/pyblish-lite/builds/350191588?utm_source=email&utm_medium=notification).

Manually deploying for now.

**Comment by pancetta** [comment]
I got a reply from @joecorcoran, providing a workaround for this. Maybe we can/should make this public?

**Comment by pancetta** [comment]
90 days. Any updates on this? Is this fixed?

**Comment by mottosso** [comment]
> I got a reply from @joecorcoran, providing a workaround for this.

What was the workaround?

**Comment by pancetta** [comment]
I had use his branch for deployment, specifying

> edge
>    branch: jc-pypi

in the deploy section of my `.travis.ml`.

**Comment by pancetta** [comment]
This is what it does: https://github.com/travis-ci/dpl/compare/jc-pypi

**Comment by martinpitt** [comment]
This is still very much alive. E. g. the [last release of python-dbusmock still failed](https://travis-ci.org/martinpitt/python-dbusmock/jobs/497442418):
```
Installing deploy dependencies
dpl.2
Preparing deploy
dpl.3
Deploying application
PyPI upload failed.
failed to deploy
```
When expanding "deploying application", it shows a crash with

    pkg_resources.ContextualVersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9.0'), set(['bleach']))

This is something internal to Travis -- dbusmock doesn't use six anywhere.
