### ISSUE TITLE
Script failed with status 127 when deploying on heroku

### ISSUE THREAD

**Issue by lapots** [travis-ci/travis-ci#9233]
I am trying to deploy a sample - though empty because it is some kind of test run - application on heroku. The application itself has not been created on heroku.

The code itself is here
https://github.com/lapots/judge-rule-engine

The job log is here
https://travis-ci.org/lapots/judge-rule-engine/jobs/342273786#L512

However it doesn't show the reason of failure except message **Script failed with status 127**
What is the problem?

**Comment by BanzaiMan** [comment]
Sorry, but you are executing your own script, so Heroku has nothing to do with it.

Status 127 in bash usually means "command not found". In this case, your `./deploy.sh` lacks the execute bit, so the deployment fails. Please fix it.
