### ISSUE TITLE
Add support for go1.10

### ISSUE THREAD

**Issue by posener** [travis-ci/travis-ci#9235]
I added the go1.10 label to my .travis.yml file, and it caused the build to run on go1.1

.travis.yml:
```
language: go
sudo: false
go:
  - 1.10
```

failure:
https://travis-ci.org/posener/wstest/builds/342548603?utm_source=github_status&utm_medium=notification

**Comment by mxschmitt** [comment]
Upstream issue tracked here: https://github.com/travis-ci/gimme/issues/132

**Comment by posener** [comment]
Thanks!
