### ISSUE TITLE
"View Config" not showing correct config

### ISSUE THREAD

**Issue by alechp** [travis-ci/travis-ci#9236]
I've used the same process for Travis across multiple projects & it has worked great. Struggling here.

----

## Context

There are similar issues (which talk about how Travis defaults to ruby, like this one: https://github.com/travis-ci/travis-ci/issues/8590) but in my case:

* .travis.yml is uploaded
* language is specified 

Despite re-pushing, enabling/disabling, confirming correct branch, etc... I'm completely stuck. I've tried toggling the switch to only build when .travis.yml is present as well.

- - - -

## Issue
1. Test is failing:

<img width="408" alt="screen shot 2018-02-16 at 4 25 21 pm" src="https://user-images.githubusercontent.com/3058939/36336200-97a4e6e6-133a-11e8-8884-2763de161226.png">

- - - -

2. Because config is wrong:

<img width="659" alt="screen shot 2018-02-16 at 4 25 36 pm" src="https://user-images.githubusercontent.com/3058939/36336205-9cf55c48-133a-11e8-8d8c-e0742acb3904.png">

* [Travis CI - Test and Deploy Your Code with Confidence](https://travis-ci.org/servexyz/repo-genesis/jobs/342595724/config)
> .travis.yml as displayed on travis-ci.org  

- - - -
3. Despite having the correct config uploaded:

<img width="552" alt="screen shot 2018-02-16 at 4 25 44 pm" src="https://user-images.githubusercontent.com/3058939/36336208-a2083714-133a-11e8-8925-14ff7d5b186a.png">

* [repo-genesis/.travis.yml at master · servexyz/repo-genesis · GitHub](https://github.com/servexyz/repo-genesis/blob/master/.travis.yml)
> Travis config  

----

## Resources
* [NPM - repo-genesis](https://www.npmjs.com/package/repo-genesis)
* [GitHub - servexyz/repo-genesis](https://github.com/servexyz/repo-genesis)
* [Travis CI - repo-genesis](https://travis-ci.org/servexyz/repo-genesis)

**Comment by alechp** [comment]
Fixed it. Using https://github.com/vadimdemedes/trevor to debug was a huge help

**Comment by codezjx** [comment]
@alechp Same situation and  how can I fix it? Already upload the .yml file.
https://travis-ci.org/codezjx/AndLinker/jobs/345675889/config

**Comment by alechp** [comment]
@codezjx In my case, the issue was I copied source from VIM in terminal (from: VIM in Terminal, to: VSCode).

I believe this screwed up the character encoding. Solution was to copy from my IDE (VSCode) to another IDE instance (VSCode).

**Comment by codezjx** [comment]
@alechp Similar situation, I create .yml file in **Android Studio** IDE and copied the content, but the `.travis.yml` seems invalid. Finally I copy an `.travis.yml` from other github project, and it works, that is really weird.

**Comment by thathurtabit** [comment]
To quote: [https://github.com/travis-ci/travis-ci/issues/7540](https://github.com/travis-ci/travis-ci/issues/7540)

> Config refers to the job configuration returned by API. Notifications are a build concern, which is one level above the jobs.

--

It doesn't represent your personal .travis.yml
