### ISSUE TITLE
403 response indicates json response

### ISSUE THREAD

**Issue by yschimke** [travis-ci/travis-ci#9238]
HTTP/1.1 403 Forbidden
Connection: keep-alive
Server: nginx
Date: Sat, 17 Feb 2018 17:46:43 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Type, Cache-Control, Expires, Etag, Last-Modified, X-Request-ID
Strict-Transport-Security: max-age=31536000
X-Endpoint: Travis::Api::App::Endpoint::Authorization
X-Pattern: /github
X-Oauth-Scopes: public
X-Accepted-Oauth-Scopes: public
Vary: Accept,Accept-Encoding
X-Rack-Cache: invalidate, pass
X-Request-Id: d6315ea6-7754-498f-9831-91bf6f56de03
Via: 1.1 vegur

you are currently not allowed to perform this request. please contact support@travis-ci.com.

**Comment by BanzaiMan** [comment]
What is this? What did you do, and what did you expect to get?

**Comment by yschimke** [comment]
This is a failing (403) request, which the response headers indicates carries "application/json" content, but it clearly just a text/plain message.  This breaks tools to process the results based on mimetypes.

**Comment by BanzaiMan** [comment]
Wrong button. Sorry.

So, what did you do to get this response? We can’t investigate the problem when we have no idea how the problem occurred.

Please include relevant details. Thank you.

**Comment by yschimke** [comment]
I think something stupid like mixing up .com and .org tokens. Can’t remember. But not worried about the root error here. But the response handling seems wrong. Why not respond with content type of text?

**Comment by BanzaiMan** [comment]
I believe you, and I understand the issue you are raising, but without further clues, this is simply unactionable.

**Comment by yschimke** [comment]
Sorry about that. I’ve got a workaround in place to handle this, so mainly reporting to help out.

**Comment by BanzaiMan** [comment]
If you run into this again, be sure to record how you got it. I’m closing this in the mean time, then, since we can’t do much about it at the moment.
