### ISSUE TITLE
When a build has a mixture of Linux and Mac jobs, Mac jobs are not properly routed

### ISSUE THREAD

**Issue by BorzdeG** [travis-ci/travis-ci#9240]
https://travis-ci.org/itbasis/jvm-wrapper/jobs/342939607
https://travis-ci.org/itbasis/jvm-wrapper/jobs/342951408

**Comment by cotsog** [comment]
@BorzdeG Sorry for this issue. It seems there's been a regression in the component responsible for routing jobs to the correct Xcode image. We've just released a fix for this hence, could you try to push a new commit and let us know if it's fixed on your side as well? Thanks!

**Comment by BorzdeG** [comment]
I restarted this Job and got the same error: https://travis-ci.org/itbasis/jvm-wrapper/jobs/342951408

**Comment by cotsog** [comment]
Hey @BorzdeG! Sorry for the continued troubles.

Unfortunately, Docker isn't supported on macOS/OS X on Travis CI. See https://github.com/travis-ci/travis-ci/issues/5738.

Also, to test the fix, it's imperative to push new commits and not just restart a previously failing build.

I can see that you are currently in the process of optimizing/rewriting your .travis.yml file in this branch, am I right? Could you try to revert to what you had in the beginning and start from there?

Please keep us posted!

**Comment by BorzdeG** [comment]
I looked - there was a similar problem earlier: https://travis-ci.org/itbasis/jvm-wrapper/jobs/342339282
I had a different configuration - the docker was run only under linux
