### ISSUE TITLE
"No such file or directory" on deploy release

### ISSUE THREAD

**Issue by sgirardin** [travis-ci/travis-ci#9242]
Hello
I've been battling for some hours and can't seem to find the issue, why the files aren't found. I'm sure it must be something really dumb.
So I've checked the following 
1. the binaries are not erased after the build (`skip_cleanup: true` in the travis.yml)
2. binary path exists (looking at the maven logs)

What am I missing? Thanks for the help

References: 
- My build trace ([](https://travis-ci.org/sgirardin/easyContent2Metadata/builds/343074883))
- My travis yml files ([](https://github.com/sgirardin/easyContent2Metadata/blob/feature/addReleaseBinaries/.travis.yml))

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by sgirardin** [comment]
Sorry didn't see the two links were not added.
- My build trace : https://travis-ci.org/sgirardin/easyContent2Metadata/builds/343074883
- My travis  yml file: https://github.com/sgirardin/easyContent2Metadata/blob/feature/addReleaseBinaries/.travis.yml

**Comment by BanzaiMan** [comment]
Your `file` https://github.com/sgirardin/easyContent2Metadata/blob/46d97d160b3f138056c3f9bde04fac6071bc426a/.travis.yml#L23-L25 defines a long string `-"easyContent2Metadata-platform-jar/target/easyContent2Metadata-platform-jar-0.1-SNAPSHOT.jar" -"easyContent2Metadata-share-jar/target/easyContent2Metadata-share-jar-0.1-SNAPSHOT.jar"`, not an array. Please fix it.

**Comment by BanzaiMan** [comment]
More specifically, add a space after `-` on lines 24 and 25.

**Comment by sgirardin** [comment]
@BanzaiMan Thanks a lot it worked. Nice day to you ;-)
