### ISSUE TITLE
Installation of python-lzma has no effect on python 2.7.14

### ISSUE THREAD

**Issue by KOLANICH** [travis-ci/travis-ci#9243]
1 python version `2.7.14` is specified
2 `python-lzma` is installed with apt
3

```python
try:
    import lzma
except ImportError:
    try: 
        import backports.lzma as lzma
    except ImportError:
        import pylzma as lzma
```

doesn't work. Neither of imports suceeds.

Also there is a problem with importing `_lzma` from `lzma` with `python3-nightly` for macos.

**Comment by BanzaiMan** [comment]
As documented in https://docs.travis-ci.com/user/languages/python#Travis-CI-Uses-Isolated-virtualenvs, we use `virtualenv` to manage Python runtime environments. When you specify `python: 2.7.14`, you are using it.

APT package `python-lzma` is for Ubuntu-supplied Python runtime, which is unrelated to the 2.7.14 runtime your build is using.

I suggest installing the module with another means.

**Comment by KOLANICH** [comment]
thank you for the info. Started using pip and that worked.
