### ISSUE TITLE
Builds fails on startup.

### ISSUE THREAD

**Issue by luis-lavaire** [travis-ci/travis-ci#9245]
Hi. I've have been facing an issue on which my builds are failing in the `before_install` step. I tell `apt` to install three packages: squashfs-tools, xorriso and syslinux-common. `apt` fails to run the command and says it was unable to lock `/var/lib/dpkg`.

This started to happen last week. I'm not the only one experiencing this issue, also @anupam-git has got it. So I can be sure it has nothing to do with my project in specific.

[This](https://github.com/luis-lavaire/mkiso/blob/master/.travis.yml) is the `.travis.yml` I'm using.

![image](https://user-images.githubusercontent.com/17011090/36382879-13e6e71a-1550-11e8-872d-589b8140d47f.png)

Thanks for your support guys, and for this awesome and useful tool!
Cheers. :grin:

**Comment by anupam-git** [comment]
![image](https://user-images.githubusercontent.com/5106648/36384418-39b7058c-15b5-11e8-8fc0-ee0a68e36848.png)

Having similar issues. Randomly getting error on apt-get upgrade or apt-get dist-upgrade.

**Comment by MaxUlysse** [comment]
I have the same issue with installing `squashfs-tools`.
```
E: Unable to locate package squashfs-tools
```
