### ISSUE TITLE
Using travis encrypt --add strips all comments from .travis.yml / comment best practices

### ISSUE THREAD

**Issue by lhriley** [travis-ci/travis-ci#9248]
Hello,

We have found that when adding new encrypted secrets to an existing `.travis.yml` file using the travis cli, it will strip all comments from the entire file (standard `# comment` style as described in the yaml spec http://yaml.org/spec/1.2/spec.html#comment//). We extensively use comments in order to better document our `.travis.yml` files for developers. Even though using `travis encrypt --add` is a convenience, it would be ideal if comments were left untouched by any travis cli command that writes to the `.travis.yml` file.

The `.travis.yml` documentation isn't explicit about comments or best practices around them. However, even the example code contains comments as part of the documentation (https://docs.travis-ci.com/user/customizing-the-build/#Explicitly-included-jobs-inherit-the-first-value-in-the-array).

I haven't dug deeply into the related code, but from how this process behaves, I assume that the file is either passed through a yml linter or consumed as part of some `yaml.load()` type function that ignores anything not yaml.

My question is of two parts:

1) Is it possible to support comments within the travis cli (especially since it is supported by yaml spec)?

2a) In the meantime, what are the best practices around comments?
2b) Can the documentation be updated to reflect the comments best practices so they are easier to find?

Thanks in advance!

**Comment by DouglasCAyers** [comment]
Losing the comments in the `.travis.yml` file is a showstopper to any convenience of `--add` parameter. Would be nice if `--add` preserved the comments in the file. Thanks!

**Comment by dbjpanda** [comment]
I think this issue should be opened. I noticed the issie was marked "Wont fix" in 2013. I hope something may have improved within 5 years or contributors should give it a try again.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis.rb/issues/144#issuecomment-37624139. Short of writing our own YAML parser, we are unable to address this problem.

**Comment by RamakrishnanArun** [comment]
So do you think that would be done soon? Right now, everyone who ever uses the CLI to encrypt something manually has to go through and put the comments back into the file.

**Comment by maikelmclauflin** [comment]
this guy https://kev.inburke.com/kevin/more-comment-preserving-configuration-parsers/ seems to think that this parser can maintain comments: https://pypi.org/project/ruamel.yaml/ haven't verified but it seems like they address it: https://yaml.readthedocs.io/en/latest/detail.html?highlight=comments#adding-replacing-comments
