### ISSUE TITLE
Starting instances on osx takes more than 1 minute

### ISSUE THREAD

**Issue by delijah** [travis-ci/travis-ci#9249]
The title already says it all. When we use linux instances, they start almost immediately, mac osx still takes more than 60 seconds.

Could this be decreased?

https://api.travis-ci.com/v3/job/111058433/log.txt?log.token=TcJiqazdCEgHK0GuirSjQQ

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. This boot time is necessary since we have to boot a Mac VM for each build request. Thanks for your understanding.

**Comment by delijah** [comment]
Ok. Thank you!
