### ISSUE TITLE
Travis API V3: is authentication mandatory?

### ISSUE THREAD

**Issue by surli** [travis-ci/travis-ci#9250]
The documentation of API V3 seems to indicate that using a authentication token is mandatory to use the API (see: https://developer.travis-ci.org/gettingstarted).

However I found that doing two get requests on the same endpoints with or without the token does not change anything: 

> curl -X GET -k -H 'User-Agent: API Explorer' -H 'Travis-API-Version: 3' -i 'https://api.travis-ci.org/repo/rails%2Frails'

Is there any rate or limit when using the API without authentication? Or can we use completely the API for requesting data without authentication?

**Comment by asmeurer** [comment]
Related issue https://github.com/travis-ci/travis-ci/issues/9954

**Comment by JJ** [comment]
I'd like to know the answer... It's apparently no, but google returns this issue, so it would be great to really know that.
