### ISSUE TITLE
Brew broken on OSX due to Ruby != 2.3 with language: ruby

### ISSUE THREAD

**Issue by drbrain** [travis-ci/travis-ci#9253]
This was fixed for other languages as described in #8552. I can `brew update` and `brew install` with `language: c` and this was marked as fixed according to [this comment](https://github.com/travis-ci/travis-ci/issues/8552#issuecomment-364254539) which uses `language: swift`.

However, using `language: ruby` I still experience this with some `osx_image` values, see [this build](https://travis-ci.org/drbrain/travis_production_test/builds/344405822) which uses `language: ruby` and is a modification of [this commit](https://github.com/BanzaiMan/travis_production_test/commit/c5e1cef7e2fb112a2a839baf8e79e15622702292) and [this build](https://travis-ci.org/BanzaiMan/travis_production_test/builds/339175377) which is referenced from #8552.

**Comment by drbrain** [comment]
Additionally, if I try to debug one of these builds the build fails to start the debug shell as I get the `Homebrew must be run under Ruby 2.3! You're running 2.0.0.` error while (it seems) Travis is trying to install ruby.

**Comment by drbrain** [comment]
This is still happening: https://travis-ci.org/drbrain/travis_production_test/jobs/344405837#L1872

**Comment by BanzaiMan** [comment]
Switching to, or using, Ruby 2.3 prior to running `brew upgrade` should fix this issue.

```yaml
install:
  - rvm use 2.3
  - brew update
  - brew upgrade openssl
```

We'd probably want to document this, and make sure that `brew addon` does it before hand.
