### ISSUE TITLE
trusty environment: ruby 1.9.3-p545 is unavailable

### ISSUE THREAD

**Issue by rypit** [travis-ci/travis-ci#9257]
When [running a build](https://travis-ci.com/customink/order_service/builds/66593167) on the `trusty` env, we're seeing the following:
```
rvm use 1.9.3-p545 --install --binary --fuzzy
curl: (22) The requested URL returned error: 404 Not Found
Required ruby-1.9.3-p545 is not installed - installing.
curl: (22) The requested URL returned error: 404 Not Found
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-1.9.3-p545 do rvm gemset create ' first, or append '--create'.
```

Similar to #2010

**Comment by BanzaiMan** [comment]
Do you need this particular patch level? Could you use `1.9.3` instead?

**Comment by rypit** [comment]
I see now that this patchlevel [isn't currently available](http://rubies.travis-ci.org/) on the 14.04 Ubuntu environment.

Our application runs on it, but I have switched to `1.9.3` so that we aren't blocked by this issue. We'll probably just upgrade, so unless others are asking for this too, I wouldn't say we _need_ it.

**Comment by BanzaiMan** [comment]
Providing every patch level of Ruby is impractical. I'm closing this now, since there is nothing more to do.
