### ISSUE TITLE
Delete me

### ISSUE THREAD

**Issue by ashtonhogan** [travis-ci/travis-ci#9259]

**Comment by BanzaiMan** [comment]
Could you elaborate on what you are trying to do? The blog post is almost 6 years old, and we are not driving interaction via @travisbot.

**Comment by BanzaiMan** [comment]
An aside: we do not currently support Windows, so Appveyor is not a competitor in the strict sense of the word.

**Comment by ashtonhogan** [comment]
@BanzaiMan as a developer that wants to create a framework and release each version to sonatype, I want to issue a command as shown above and then I want AppVeyor to create a new `tag` or upload the respective tag to maven central if I issue a `release` command

**Comment by BanzaiMan** [comment]
I'm guessing that you are looking for something like https://github.com/travis-ci/dpl/pull/466.

**Comment by ashtonhogan** [comment]
@BanzaiMan Sure but I don't see any documentation being added with that PR
