### ISSUE TITLE
matrix xenial worker startup failed "No output has been received in the last 10m0s"

### ISSUE THREAD

**Issue by mpromonet** [travis-ci/travis-ci#9263]
Since a couple of month, building with xenial dist fails often starting the worker.
In the logs there is something  like : 
```
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
hostname: e33020c8-4cd8-4f8f-a57c-433b94a3b480@1.production-5-worker-org-c-1-gce
version: v3.5.0 https://github.com/travis-ci/worker/tree/77dbc57c72d00592aeb754773b712da843c7e00d
instance: travis-job-63575be3-e8cc-4273-86d6-c3d44527d8f2 travis-ci-sardonyx-xenial-1518209341-4402201 (via amqp)
startup: 26.404347654s
travis_fold:end:worker_info
[0K

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```
Maybe this issue is similar to #9127 however this is not a timeout that occurs running a command,  then some travis_wait command will not help.

I experiment this with matrix job on different project : 
- https://travis-ci.org/mpromonet/v4l2rtspserver/jobs/342781196
- https://travis-ci.org/mpromonet/webrtc-streamer/jobs/343124663

Is there some way to extend this workaround this timeout ?

Best Regards,
Michel.

**Comment by BanzaiMan** [comment]
As noted in https://github.com/travis-ci/travis-ci/issues/9038#issuecomment-356811024, we do not yet provide Xenial support. It may be fixed in the future, but for now, please take this disclaimer into account.

**Comment by mpromonet** [comment]
@BanzaiMan 
I read this, but trusty is really too old, since these problems with travis-ci, I start to move to circle-ci.
Best Regards,
Michel.
