### ISSUE TITLE
No auto-trigger build on push

### ISSUE THREAD

**Issue by inwardmovement** [travis-ci/travis-ci#9265]
Do you know why Travis doesn't auto-trigger a build when I push to `source`? Even after waiting for almost 10 hours.

Here is my [.travis.yml](https://github.com/inwardmovement/inwardmovement.github.io/blob/source/.travis.yml)
Here is the [last build log](https://travis-ci.org/inwardmovement/inwardmovement.github.io)

**Comment by BanzaiMan** [comment]
The webhook appears to have been invalid for some reason. I’ve fixed this now. Please push another commit to confirm (and close this ticket if everything looks good). Thanks.

**Comment by inwardmovement** [comment]
It seems ok now, thanks!

**Comment by henokyen** [comment]
for me it doesn't still work, doesn't auto build upon pushing to my master branch on github
