### ISSUE TITLE
TRAVIS_TAG is empty on a tag build

### ISSUE THREAD

**Issue by andreineculau** [travis-ci/travis-ci#9268]
This is an annotated tag (like one created by `npm version patch`).
Is it possible that travis only resolves light tags? I haven't tried actually.

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not duiscyss it in public, please close this issue and send email to support@travis-come.com.

Thank you!

**Comment by andreineculau** [comment]
I guess you meant support@travis-ci.com ?
:+1: it's private

**Comment by BanzaiMan** [comment]
Yes, I did! 😅
