### ISSUE TITLE
[Build/test do not start] The command "rake" exited with 1.

### ISSUE THREAD

**Issue by funilrys** [travis-ci/travis-ci#9274]
Please find the full log of https://travis-ci.org/dead-hosts/polish-adblock-filters_git_MajkiIT/jobs/346519127#L746-L753 at https://api.travis-ci.org/v3/job/346519127/log.txt.

That issue is really strange because as you can see at https://travis-ci.org/dead-hosts we have build/test currently running without issues ... It seems that this issue only appears for new repository only (?)

```
$ gem --version
2.7.6
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-2.4.1@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
```

**Comment by BanzaiMan** [comment]
Your `.travis.yml` is invalid, so the build is defaulting to Ruby. Please fix it.
