### ISSUE TITLE
High CPU usage on Travis website

### ISSUE THREAD

**Issue by wolfv** [travis-ci/travis-ci#9276]
I've noticed that the travis website makes my CPU fan spin.  
I am wondering if I am alone with this observation (Fedora 27 / Google Chrome). 

Maybe there is something going on with the rendering of the spinners that results in high stress on the CPU?

**Comment by stof** [comment]
you're not alone. I'm using Firefox on Ubuntu (and I have some colleagues experiencing the same with Chrome on Ubuntu). Keeping a Travis tab opened is a no-go for me as it starts eating CPU.

**Comment by wolfv** [comment]
I tried to `display: none` the status spinners, but it didn't reduce the CPU load...
But maybe it's related to the SVG animation in the spinners?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
which specific pages are you seeing this on?

**Comment by wolfv** [comment]
Usually just when I am logged in, and look at a specific build (and there are a bunch of other builds on the left sidebar).
Since I am a member of the conda-forge team, there are a lot of builds (the list on the left is ~20 entries long). Not sure if this contributes to the issue.

**Comment by wolfv** [comment]
As you can see in this screenshot, every second the CPU wakes up to perform some work taking up 100% of one core, and then some of another core. Computing this seems to take 63ms (so a considerable time) on a recent i7 laptop and with the latest chrome.

![screenshot from 2018-05-15 15-09-13](https://user-images.githubusercontent.com/885054/40058629-054d0942-5852-11e8-8d6c-8347bdb43ae7.png)

**Comment by dlech** [comment]
Just looking at https://travis-ci.org/ while logged in and no builds running is using a ton of CPU for me. Firefox 60 on macOS. Ran Firefox in safe mode to confirm that it is not an extension causing the problem. I've attached a 30 second performance profile from Firefox's dev tools. I don't know exactly what I'm looking at, but to my untrained eyes, it looks like `setInterval` in https://cdn.travis-ci.org/assets/vendor-1c64a06233ab3fed36e973861218a7b9.js might be what is causing most of the usage.

[profile.json.zip](https://github.com/travis-ci/travis-ci/files/2100600/profile.json.zip)

**Comment by wolfv** [comment]
Guys, can we please fix this? It's draining my laptops battery (looking at powertop, opening the travis CI website shows a lot of

**Comment by RDIL** [comment]
Can confirm.

**Comment by bnavigator** [comment]
Still a problem

**Comment by kif** [comment]
I also face the issue
