### ISSUE TITLE
Can I make Travis to wait for 190 mins?

### ISSUE THREAD

**Issue by Alann200** [travis-ci/travis-ci#9277]
I'm building a custom ROM with Travis and it's seems that Everytime I try it finishes out with job terminated! Because it needs more time so I used ``` travis_wait ``` I want to know is their any way to extend it to about 190+ mins with ``` travis_wait``` ?
Thanks in advance!
Here's my script! 
https://github.com/DEVviL0/Test/blob/master/.travis.yml
Error I've got:
> 
``` $ travis_wait 30 repo sync -f --force-sync --no-clone-bundle > /dev/null 2>&1

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated

**Comment by BanzaiMan** [comment]
Could you try dropping STDOUT & STDERR redirections? Also, we have a hard limit on a job's life time, and 190+ minutes is over that.
