### ISSUE TITLE
how to run travis test on private server rather than official provided server

### ISSUE THREAD

**Issue by mingxiaoh** [travis-ci/travis-ci#9278]
hello, I am new to travis, but I found that my travis test will be failed on official provided server due to the limited memory. So, I would like to run auto travis test on my private server,  what should I do?

**Comment by BanzaiMan** [comment]
For on-premises use of Travis CI, we offer [Travis Enterprise](https://enterprise.travis-ci.com/). If you are interested, please email us at enterprise@travis-ci.com. We do not support running your own instances at this time.

Thanks.
