### ISSUE TITLE
apt-whitelist-checker failing for every package

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#9279]
Check the [build history](https://travis-ci.org/travis-ci/apt-whitelist-checker/builds). It seems that there is something wrong with the build job since they are all erroring because the `skip` command is missing.

**Comment by thedrow** [comment]
@BanzaiMan ping?

**Comment by BanzaiMan** [comment]
Sorry for the delay. I've just fixed it. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/439485952 (It was due to a repository rename, and we were not following HTTP redirects.)
