### ISSUE TITLE
character 'n' injected at end of multi-line scripts

### ISSUE THREAD

**Issue by richRemer** [travis-ci/travis-ci#9281]
When using the `>` multi-line string specifier in `.travis.yml`, the letter `n` is inserted at the end of the value.  I presume this is some attempt to add a newline that goes awry somehow.

Consider the following example:

```
deploy:
  - provider: script
  - script: deploy && echo "the 14th letter of the alphabet is "
```

That example works as expected: it prints the message `the 14th letter of the alphabet is `.  But consider the next example:

```
deploy:
  - provider: script
  - script: >
        deploy && echo "the 14th letter of the alphabet is "
```

This prints `the 14th letter of the alphabet is n`.  Note the `n` that has been injected into the script; it is not simply appearing at the end of the script's output.  I have verified this using different scripts.  I was also able to verify this with multiple projects, and after clearing the project caches.

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by richRemer** [comment]
https://travis-ci.com/Zingle/socket-server/builds/67184858 line 1060 "Failed to stop sockion.service: Unit sockion.service not loaded." (should be sockio.service)

https://travis-ci.com/Zingle/socket-server/builds/67198152 line 1060 "deployed to ci and rcn" (should be simply rc)

https://travis-ci.com/Zingle/socket-server/builds/67200311 line 1506 "the 14th letter of the alphabet is n" (I was getting annoyed at this point)

https://travis-ci.com/Zingle/socket-server/builds/67203721 line 1058 "this is a workaround for Travis having issues with the letter:n" (this is my current workaround)

I also tried on a different project (https://travis-ci.com/Zingle/socket-server/builds/67203721)

The most telling one is the one where it talks about a missing `sockion.service` because it demonstrates the "n" is appearing in the script itself, and not just in the output.

**Comment by BanzaiMan** [comment]
Looks like we are not handling the `\n` in the `script` provider here. Do note that the newline does exist in your `deploy.script` value. (https://stackoverflow.com/a/21699210/136333)

**Comment by lmittmann** [comment]
Unfortunately this issue persists. Will this bug be fixed in the near future?

**Comment by iriberri** [comment]
The YAML folded style (`|` or `>`) removes the newlines within the string, but it also adds a `\n` at the end, which is detected a part of the deploy script string in these cases.

To avoid these newlines and use the folded style in your .travis.yml, I'd recommend using the chomp indicator (`|-` or `>-`) that will not append the final newline (\n) to the string.

**Comment by lmittmann** [comment]
As @BanzaiMan already [referenced](https://stackoverflow.com/a/21699210/136333), the `>` Folded style should only add a newline at the end and convert double newlines to single newlines.

Example from StackOverflow:
```
Key: >
  this is my very very very
  long string
```
Should result in `this is my very very very long string\n`. And `>-` should remove the tailing newline.

However, using travis the example above will actually result in the following wrong string:
```diff
this is my very very very\nlong string\n
                         ^^
                         newline that should not be here
```

**Comment by iriberri** [comment]
Hi @lmittmann, could you please share a link to a build where the yaml was converted to that string with the \n in the middle?

I've been testing with:

```yaml
deploy:
  provider: script
  script: >-
    echo hi
    echo ho
    echo ha
  on:
    all_branches: true
```

and this is getting converted to:

```
"script": "echo hi echo ho echo ha"
```

**Comment by lmittmann** [comment]
Hi @iriberri, I created a [test repository](https://github.com/lmittmann/test) that reproduces the issue.

I use the following `.travis.yml`:
```yml
language: minimal

deploy:
  provider: script
  script: >-
    echo a
         b
         c
  on:
    branch: master
```
I expect the deploy script to run `echo a b c`, which should result in the output `a b c`. However, the actual output is `an bn c`.

This is the build: https://travis-ci.com/lmittmann/test/builds/85714801#L440

**Comment by iriberri** [comment]
Thanks for the example, @lmittmann! Ah, I think this is because the `b` and `c` are indented inside the `echo`. The result with the \n is the same I get at https://codebeautify.org/yaml-to-json-xml-csv, for example.

Could you try the following instead?

```
language: minimal

deploy:
  provider: script
  script: >-
    echo a
    b
    c
  on:
    branch: master
```

**Comment by lmittmann** [comment]
Thanks, removing the whitespaces solved the issue.
