### ISSUE TITLE
Using Travis CI with Minecraft Forge

### ISSUE THREAD

**Issue by Cubxity** [travis-ci/travis-ci#9283]
Could you make it so that we can install local repository on the Travis CI? Because Minecraft Forge needs minecraft to be compiled locally and not allowed to distribute the decompiled code.

**Comment by BanzaiMan** [comment]
This feels like a niche use case, and it is highly unlikely that we support it. You can try compiling from source and [caching](https://docs.travis-ci.com/user/caching) the artifacts as necessary.

**Comment by felixletsplayYT** [comment]
If you just want to build your forge Mod it is possible with this travis config:
```
language: java
jdk: oraclejdk8
before_install:
 - wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.3.2661/forge-1.12.2-14.23.3.2661-mdk.zip
 - unzip -n forge-1.12.2-14.23.3.2661-mdk.zip
 - rm forge-1.12.2-14.23.3.2661-mdk.zip
install: ./gradlew setupCiWorkspace
script: ./gradlew build
```
