### ISSUE TITLE
Error installing Python3 with `brew` on OSX

### ISSUE THREAD

**Issue by stefanseefeld** [travis-ci/travis-ci#9285]
Hello,

I see a new error in my OSX CI build:

https://travis-ci.org/stefanseefeld/faber/jobs/348406968

(the displayed error is
```
Error: python 2.7.14 is already installed
To upgrade to 3.6.4_3, run `brew upgrade python`
The path python3 (from --python=python3) does not exist
/Users/travis/.travis/job_stages: line 66: venv/bin/activate: No such file or directory
```

This looks vaguely similar to https://github.com/travis-ci/travis-ci/issues/9022, with the difference that I'm running `brew install python3` in the failing configuration (note that another one issuing `brew install python` works fine !).

I don't understand the error, and neither how I can work around it. Any help would be much appreciated. Thanks !

**Comment by BanzaiMan** [comment]
Isn't the error message telling you to run `brew upgrade python` instead of `brew install python3`?

   To upgrade to 3.6.4_3, run `brew upgrade python`

https://travis-ci.org/stefanseefeld/faber/jobs/348406968#L1993

How did you come up with `brew install python3`? Does it work on your machine?

**Comment by stefanseefeld** [comment]
On 02.03.2018 16:03, Hiro Asari wrote:
>
> Isn't the error message telling you to run |brew upgrade python|
> instead of |brew install python3|?
>
> To upgrade to 3.6.4_3, run |brew upgrade python|
>
> https://travis-ci.org/stefanseefeld/faber/jobs/348406968#L1993
>
> How did you come up with |brew install python3|? Does it work on your
> machine?
>

I have no access to an OSX machine, so trial-and-error on Travis-CI is
my only way to figure out how to set up the machine.
Note the above used to work fine until a few weeks ago. I still don't
understand what has changed since then, and what the actual error is.

Are you suggesting that I should use `brew upgrade python` to get a
Python3 version ? Would I then access this as `python` or as `python3` ?

Thanks,


Stefan

-- 

      ...ich hab' noch einen Koffer in Berlin...

**Comment by stefanseefeld** [comment]
For the record: I seem to have found a working setup for both Python2 and Python3: https://github.com/stefanseefeld/faber/commit/9d47cb5a6d02110a2537d0fbc6457fd9ddf6b2ab
I can't claim that I understand why `virtualenv` stopped working, but I'm happy the current setup is functional again.
Thanks for your help,

**Comment by bluca** [comment]
I'm not sure this should be closed. This used to work, and used to be able to use python and python3 at the same time - looks like a regression to me?
