### ISSUE TITLE
travis doesn't start to build 

### ISSUE THREAD

**Issue by dancespiele** [travis-ci/travis-ci#9290]
Hello, I follow all the steps in the documentations and travis doesn't start to build when I push a pull request.
* the file .travis.yml is in the repository https://github.com/spieljs/spiel-client
* the repositori is enable https://travis-ci.org/spieljs/spiel-client

**Comment by BanzaiMan** [comment]
The webhook was somehow incorrect. I've reset it now, so it should work now. Please push a new commit. Thanks.

**Comment by dancespiele** [comment]
Ok now it works, thanks
