### ISSUE TITLE
My Build times out because no output was received

### ISSUE THREAD

**Issue by oPromessa** [travis-ci/travis-ci#9291]
My build output stdout and stderr to files: say log_file
On timeout under: "Build times out because no output was received" error I was hoping to catch the error by setting "tail -100  log_file" under the **after_failure** section of .travis.yml file.

Thing is the after_failure section is not triggered on "No output has been received in the last 10m0s".

Prior to using travis_wait option I was wondering if there is someway to cath the build timeout to show my log files?

- [Example build on this link! ](https://travis-ci.org/oPromessa/flickr-uploader/jobs/348997090)

Thanks in advance for your support.

oPromessa

**Comment by pzrq** [comment]
@oPromessa It [looks like](https://travis-ci.org/oPromessa/flickr-uploader) you got past this issue. 

Did you resolve it or is there still work to be done here?

**Comment by oPromessa** [comment]
Thanks for getting back. Great work!!

I guess the delay was caused by a 3rd party system. 

But, for reference, when a build is cancelled due to timeout is there a way to execute a couple of more debugging/logging commands maybe under the "after_failure" clause?

Thanks in advance for your support.

oPromessa

**Comment by BanzaiMan** [comment]
When a job is terminated forcibly due to silence on the wire, there is currently no cleanup. This is discussed in https://github.com/travis-ci/travis-ci/issues/4221.

If your immediate issue is resolved, please consider closing this issue.

**Comment by oPromessa** [comment]
Thank you. Closing issue.
