### ISSUE TITLE
Julia build on Mac consistently segfault

### ISSUE THREAD

**Issue by juliohm** [travis-ci/travis-ci#9293]
It is been a week already that all my commits on Mac are failing with a segfault: https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/349101888#L615

A friend confirmed on his local Mac laptop that the build is successful https://github.com/JuliaParallel/Hwloc.jl/issues/15 and so I am guessing that hwloc is not able to work properly on some recent Mac update on Travis?

I appreciate if you can help debug this failure, I don't know how I should proceed to fix the issue.

**Comment by juliohm** [comment]
Any help on this issue would be highly appreciated. The build is still failing.

**Comment by BanzaiMan** [comment]
> Julia for Travis-CI is not officially supported, but is community maintained.
> Please file any issues using the following link
>  https://github.com/travis-ci/travis-ci/issues/new?labels=julia
> and mention `@tkelman`, `@ninjin`, `@staticfloat` and `@simonbyrne` in the issue

**Comment by juliohm** [comment]
Thank you @BanzaiMan , opened the issue there.
