### ISSUE TITLE
Travis is slowing down again (03/04/2018)

### ISSUE THREAD

**Issue by unional** [travis-ci/travis-ci#9294]
Trusty builds take up to 30mins+ to start.

https://travis-ci.org/unional/fixture/builds/349148464

![image](https://user-images.githubusercontent.com/3254987/36960863-ba40b46c-1ffd-11e8-8688-32589b6c8f5d.png)

**Comment by kirrg001** [comment]
I experience the same in the last week or two. 

- builds are slow ([example](https://travis-ci.org/TryGhost/Ghost/builds/348876031))
- builds fail randomly more often when Travis is slow
- builds start delayed
- https://travis-ci.org is very slow for me (build pages don't load at all or very slow) - i always need to refresh

**Comment by unional** [comment]
Notice that too, but was not as bad as today. All builds are halted right now.
https://www.traviscistatus.com/ shows no backlog build.

**Comment by BanzaiMan** [comment]
@unional During the time you are referring to in https://travis-ci.org/unional/fixture/builds/349148464, the `unional` user had the maximum number of jobs running already, and as as result your jobs were not started. I see that you are using some third-party utility named `travis-deploy-once`. If the name implies its function, it is simply waiting for other jobs to finish, and this is the case, this is expected.

**Comment by unional** [comment]
@BanzaiMan how can I find out all running job for a particular user?
From what I notice, I did not have any job "running" at that time. All jobs are stuck (across all of my repositories).

As for `travis-deploy-once`, it is a third-party utility by `semantic-release`.
It waits for other jobs in the same build to complete before executing the script that follows.

e.g. in the example above, the build has 3 jobs, node 9, 8, and 6.
`travis-deploy-once` will check and elect the job 38.1 as the master (as it has the highest NodeJS).
It then waits for 38.2 and 38.3 to complete before executing `semantic-release`.

The reason 38.1 takes 36mins to run is that either 38.2 or 38.3 takes 30 min+ to start (and completed in 2/5 mins respectively).
That's why I mentioned in the OP that it takes 30 mins+ to start.

**Comment by unional** [comment]
```sh
> komondor@0.0.0-development coverage /home/travis/build/unional/komondor
> jest --coverage
PASS src/class/isClass.spec.ts (9.251s)
PASS src/index.spec.ts (60.041s)
PASS src/artifact.spec.ts (75.913s)
PASS src/config.spec.ts (75.707s)
PASS src/promise/promise.spec.ts (76.292s)
PASS src/class/class.spec.ts (75.821s)
PASS src/specAction.spec.ts (76.671s)
PASS src/given.spec.ts (77.519s)
PASS src/spec.node-fetch.spec.ts (77.762s)
PASS src/spec.spec.ts (77.03s)
PASS src/function/function.spec.ts (122.755s)
PASS src/given2.spec.ts (122.717s)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by unional** [comment]
After about 20 retries it finally passes.
https://travis-ci.org/unional/komondor/builds/375435954

Nothing has changed in the code throughout the retries.
So I believe the problem is in travis.
I have run the tests locally on the same npm/node version and it is working fine.

**Comment by kalpaitch** [comment]
I'm finding similar issues with Travis. It's got so slow we're going to start using CIrcleCI.
