### ISSUE TITLE
Network connectivity issues on macOS VMs

### ISSUE THREAD

**Issue by ceaglest** [travis-ci/travis-ci#9296]
Hi Travis team,

My name is Chris and I'm an engineer on [Twilio](https://github.com/twilio)'s Video SDKs.

We currently run integration test suites for both our cross-platform C++ library and our Objective-C SDK on macOS. While Linux C++ builds have been pretty smooth, we are seeing some connectivity issues on macOS which are causing test failures for both our iOS and C++ projects.

#### Connectivity Requirements

Our integration tests consist of both googletest (macOS, C++) and XCTest (iOS Simulator, Objective-C) cases hosted on macOS VMs. These tests use the following ports and protocols:

443 (HTTPS) - REST API.
443 (TLS) - Signaling connection.
10,000 - 20,000 (UDP / SRTP / SRTCP) - Media servers.
443, 3478 (TCP and UDP), 5349 TCP - STUN and TURN servers.

#### Results

The main issues we are seeing right now are intermittent failures to complete REST API calls, and signaling connection failures. Over the course of running ~500 integration test cases in a job we may see one or more failures in either the REST calls or the signaling connection. These failures have been observed with iOS simulators hosted on macOS and in C++ tests running directly on macOS.

Unfortunately, since the repos being built are private I've not provided any direct links in this issue. However, I'd be happy to share builds over email to help with diagnosing the issue.

Best,
Chris Eagleston

**Comment by ceaglest** [comment]
@amitshivnani provided some links to example jobs where network connectivity was a problem.

https://travis-ci.com/twilio/video-cpp/jobs/113252065
https://travis-ci.com/twilio/video-cpp/jobs/113211034
https://travis-ci.com/twilio/video-cpp/jobs/113230936

**Comment by BanzaiMan** [comment]
http://stspg.io/24aaef009

**Comment by ceaglest** [comment]
@BanzaiMan the failed jobs we provided are from almost 24 hours ago, and we can find examples from further back than that. Are you saying the incident that was just filed is retroactive?

**Comment by BanzaiMan** [comment]
It is not yet clear to me, but I'm just linking in case they are intertwined.

**Comment by Lyoness** [comment]
Hello!  We're taking the issue to our infrastructure provider to see if they can give us any insight about the transient network errors.  If there are others reading this experiencing same, please post here so we can gauge how wide-spread and the frequency of these errors. 

- Your Friendly Neighborhood Mac Build Infra Team

**Comment by aaalaniz** [comment]
Thanks @Lyoness !

We are happy to provide job IDs and our config file if you need any help diagnosing the problem.

**Comment by ceaglest** [comment]
Thanks for the update @Lyoness! As @aaalaniz said we can provide more example jobs if it will help in the diagnosis.

**Comment by Lyoness** [comment]
Yes, keep a running log of them here as you find them! Having time stamps would be helpful to add to infrastructure provider.

**Comment by Nibbler73** [comment]
Might be a more general issue, as Linux `trusty` is affected too.

Looks like a connectivity issue on `after_success`, as downloading and installing during test-preparation works fine.

Trying with `ncftp`:
https://travis-ci.org/Nibbler73/hp-husic.net/builds/351519213

Trying as described in https://docs.travis-ci.com/user/deployment/custom/:
https://travis-ci.org/Nibbler73/hp-husic.net/builds/352516392

Both approaches used to work a couple of weeks before.

**Comment by ceaglest** [comment]
Hi @Lyoness,

I've emailed support with some new logs which show connectivity issues over the past few days.

Best,
Chris

**Comment by BanzaiMan** [comment]
Thanks, everyone for continued help in troubleshooting this issue.

**Comment by aaalaniz** [comment]
I discovered two more cases of Mac network connectivity issues. In these build jobs the VM failed to download some dependencies from a maven repository.

https://travis-ci.com/twilio/video-cpp/jobs/114761737
https://travis-ci.com/twilio/video-cpp/jobs/114761738

**Comment by ceaglest** [comment]
I've also sent several connectivity logs from the past few days on the support email thread. It's a mix of maven fetching issues and s3 uploading as well as some connectivity issues specific to our product under test.

**Comment by ceaglest** [comment]
Here is a recent example on Xcode 8.2 / iOS 11.2 simulators.

https://travis-ci.com/twilio/twilio-video-ios-internal/jobs/115418997

**Comment by sridharmunendramani** [comment]
Hi, I am facing network timeout issue  in my travis build which is running in iOS
Background:  I use travis to run my automation suite where I spin browsers and run my test suite. Few test cases fail because of these network issues. In my test report there are few tests failed and the screenshot shows network issue.
This is the OS configuration
os: osx
language: java
jdk: oraclejdk11
osx_image: xcode10.1

As advised in some blog, I am using the below addon in my travis, but still I face the network issue. I tried to find any error in my build logs but I am not sure what I should look for.
addons:
  apt:
    config:
      retries: true

Please can someone share your thoughts.
