### ISSUE TITLE
The command "$TRAVIS_BUILD_DIR/vendor/bin/phpunit" exited with 2.

### ISSUE THREAD

**Issue by marinsagovac** [travis-ci/travis-ci#9297]
travis.yml:

```
sudo: false

language: php

php:
    - 7.1

install:
  - travis_retry composer install --no-interaction --no-suggest
  - composer show --installed

branches:
  only: master

before_script:
  - travis_retry composer self-update

after_script:
  - cd vendor/myvendor/app
  - phpunit Tests/ --coverage-clover=coverage.xml
```

composer.json:
```
{
    "name": "myvendor/app",
    "type": "library",
    "license": "MIT",
    "require": {
        "php": "^7.0"
    },
    "require-dev": {
        "phpunit/phpunit": "4.5.*"
    },
    "scripts": {
        "test": "./myvendor/bin/phpunit"
    },
    "autoload": {
        "psr-4": {
            "Myvendor\\App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Myvendor\\App\\": "test/"
        }
    }
}
```

It's failed on command: 0.09s$ $TRAVIS_BUILD_DIR/vendor/bin/phpunit

PHP 7.0 and phpunit 4.5.

How to fix it?

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by marinsagovac** [comment]
Here is a log: https://api.travis-ci.org/v3/job/349573082/log.txt

**Comment by BanzaiMan** [comment]
Apparently this invocation `$TRAVIS_BUILD_DIR/vendor/bin/phpunit` is wrong for your repository. https://travis-ci.org/Codervio/Envmanager/jobs/349573082#L529 Does it work on your machine?

Could you try reproducing the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)? I followed your build steps, and it fails similarly.

**Comment by marinsagovac** [comment]
Okay, how to make Travis to find in phpunit package 

PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in

?

**Comment by BanzaiMan** [comment]
Sorry, but I don't know enough about PHP to help you further.

**Comment by marinsagovac** [comment]
Found a solution. Use phpunit by vendor not by system.

`  - vendor/myvendor/mypackage/vendor/phpunit/phpunit/phpunit vendor/myvendor/mypackage/Tests/ --coverage-clover=coverage.xml`

**Comment by TripathyC** [comment]
The solution does not mean anything to me. Where to place these lines?

**Comment by dbrax** [comment]
me too @TripathyC
