### ISSUE TITLE
Mac Job Errors with Abruptly Ended Log

### ISSUE THREAD

**Issue by aaalaniz** [travis-ci/travis-ci#9299]
I am running a suite of C++ tests using [Google Test](https://github.com/google/googletest) on Mac with Xcode 9.2 and finding that some jobs error. This is fine, but when I try to check the log in Travis, I see that the log has stopped abruptly with no explanation for what caused the job to error.

The last thing seen in the log is a typical Google Test output.

```
[       OK ] RoomObserverTopologyParameterizedTest/RoomObserverTest.ReconnectBeforeSessionTimerExpiry/323 (2803 ms)

[ RUN      ] RoomObserverTopologyParameterizedTest/RoomObserverTest.ReconnectBeforeSessionTimerExpiry/641

Using fake audio device module with /Users/travis/build/twilio/video-cpp/test/support/voice_engine/audio_long16.pcm audio path.

Using fake audio device module with /Users/travis/build/twilio/video-cpp/test/support/voice_engine/audio_long16.pcm audio path.

Using fake audio device module with /Users/travis/build/twilio/video-cpp/test/support/voice_engine/audio_long16.pcm audio path.

Room created with sid: RMe66da04917c1df5874487004dd206eb7: group

Wait for Alice to connect ...

client alice-eecbbeb0-a359-958d-e7e8-686e17c58230 onConnected: ade92edc-4900-d93d-be5e-9ef7385539b6, RMe66da04917c1df5874487004dd206eb7, 0 participant(s)

Wait for Bob to connect ...

client alice-eecbbeb0-a359-958d-e7e8-686e17c58230 onParticipantConnected bob-2b8c04d9-3f56-db0d-c7b4-f95bd89af242

client bob-2b8c04d9-3f56-db0d-c7b4-f95bd89af242 onConnected: ade92edc-4900-d93d-be5e-9ef7385539b6, RMe66da04917c1df5874487004dd206eb7, 1 participant(s)

Disconnect Bob ...

Disconnect Alice ...

[       OK ] RoomObserverTopologyParameterizedTest/RoomObserverTest.ReconnectBeforeSessionTimerExpiry/641 (3215 ms)

[----------] 12 tests from RoomObserverTopologyParameterizedTest/RoomObserverTest (63860 ms total)



[----------] 2 tests from MultipleParticipantsRoomConnectTopologyParameterizedTest/MultipleParticipantsRoomConnectTest

[ RUN      ] MultipleParticipantsRoomConnectTopologyParameterizedTest/MultipleParticipantsRoomConnectTest.MultipleParticipantsShouldConnectToRoomAndBeSeenDisconnected/323

```

I've seen job errors before, but the log usually indicates a segfault or a similar error. There is no indicator that the log limit has been exceeded because the log stops at line 4123.

### Travis Configuration

Snippet from our .yml file
```
    - stage: test
      os: osx
      osx_image: xcode9.2
      compiler: clang
```

I have a pull request to a private repository open that consistently reproduces this problem and would be happy to troubleshoot the problem.

Thanks!

**Comment by MariadeAnton** [comment]
Thanks you for your offer to troubleshoot with us, @aaalaniz. This definitely looks suspicious, specially if the line just cuts off, I agree those normally are segfaults 🤔 
To do so, would you mind emailing at support@travis-ci.com with the details ? Thanks!

**Comment by aaalaniz** [comment]
Sent an email with more details. Thanks @MariadeAnton !

**Comment by ramapal** [comment]
We saw an identical issue happen today. Happy to share the cut off logs if needed.

**Comment by aaalaniz** [comment]
I don't know if these steps will work for everyone, but doing the following seems to have resolved the problem:

- Remove all `travis_wait` commands
- Move commands from the .travis.yml `:script` section to a separate `build_and_test.sh`
- Call `set -e` inside `build_and_test.sh`

Doing these steps ensures the following:

- Logs are preserved for failing Google Test executions
- The job errors correctly when a pipeline returns a non-zero status code
- The job does not falsely pass when a test failure occurs
