### ISSUE TITLE
Build did not honor travis_wait

### ISSUE THREAD

**Issue by paynerc** [travis-ci/travis-ci#9301]
Some of our integration testing on the iOS Simulators can take a long time. Therefore, we use a `travis_wait` when running the tests such as:

`travis_wait 45 ./Scripts/run-tests.sh`.

The job in question was terminated after 16 minutes. The following was in the log:

```
[0K$ travis_wait 45 ./Scripts/run-tests.sh





Still running (1 of 45): ./Scripts/run-tests.sh
Still running (2 of 45): ./Scripts/run-tests.sh
Still running (3 of 45): ./Scripts/run-tests.sh
Still running (4 of 45): ./Scripts/run-tests.sh
Still running (5 of 45): ./Scripts/run-tests.sh

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/common-build-problems/#Limitations-of-travis_wait

> `travis_wait` works by starting a process, sending it to the background, and watching the background process. If the command you pass to `travis_wait` does not persist, then `travis_wait` does not extend the timeout.

**Comment by paynerc** [comment]
So are you suggesting that the `xcodebuild` command that is wrapped inside the `run-tests.sh` script just died after minute five and no output was further passed on?
