### ISSUE TITLE
Could not find .travis.yml, using standard configuration.

### ISSUE THREAD

**Issue by diakogiannis** [travis-ci/travis-ci#9304]
Hi,

I get the error message "Could not find .travis.yml, using standard configuration." and the project is being built as a Ruby project even though the file exists. 

You can check this here https://github.com/diakogiannis/EasyDropboxFileHandler/tree/develop

Thanks,
Alexius

**Comment by BanzaiMan** [comment]
Hello, I see that you've added it. Do you have a question?

**Comment by diakogiannis** [comment]
Hi Hiro,

As I am stating in the ticket, I am getting the error **even though the file exists** 

So the file is there but unfortunately, the project is not getting built. So the problem persists.

Thanks

**Comment by BanzaiMan** [comment]
Sorry, but I think the build is running. https://travis-ci.org/diakogiannis/EasyDropboxFileHandler/builds/350344768

**Comment by BanzaiMan** [comment]
I'm closing this now, as the builds are running. If you have evidence to suggest otherwise, do let us know.
