### ISSUE TITLE
Debug mode not working, hangs on "Preparing debug sessions."

### ISSUE THREAD

**Issue by dark-panda** [travis-ci/travis-ci#9305]
Debug mode is not working on my builds. I was attempting to track down an issue with our builds failing and the build log never gives me an ssh endpoint that I can connect to. Instead, the build ends with the following and just sits there:

```
Debug build initiated by dark-panda
Setting up debug tools.
Preparing debug sessions.
```

At which point nothing else happens. Normally I would expect to see something akin to

```
Use the following SSH command to access the interactive debugging environment:
ssh foo@bar
This build is running in quiet mode. No session output will be displayed.
This debug build will stay alive for 30 minutes.
```

**Comment by BanzaiMan** [comment]
See https://www.traviscistatus.com/incidents/0550rtcznhcj for updates. Thanks.

**Comment by BanzaiMan** [comment]
The service has been restored. Thank you for your patience.
