### ISSUE TITLE
Sync on travis.com does not show private repository in list

### ISSUE THREAD

**Issue by lsnape** [travis-ci/travis-ci#9307]
I've created a private GH repository in our company's organisation (ELiTLtd), and clicked the 'Sync Account' button on the 'https://travis-ci.com/profile/ELiTLtd' page. I would expect to see the newly created repository appear in the list, but the list doesn't change.

I don't remember doing anything else for the other private repos I've enabled in the past. Is there something I'm missing?

Thanks in advance.

**Comment by BanzaiMan** [comment]
What repository are you expecting to see? If you'd rather not discuss it in public, please close this issue and send email to support@travis-ci.com. Thanks.

**Comment by lsnape** [comment]
OK, will do.
