### ISSUE TITLE
Using `git-lfs` 2.4.0 changes ownership of `~/.gitconfig` to `root:root`

### ISSUE THREAD

**Issue by mprins** [travis-ci/travis-ci#9309]
We've started seeing build failures on one of our projects that uses the pl.project13.maven:git-commit-id-plugin in a `sudo:false` configured build. ([master .travis.yml](https://github.com/flamingo-geocms/flamingo/blob/master/.travis.yml)

This started with our fist build in March with https://travis-ci.org/flamingo-geocms/flamingo/jobs/348177332#L1187 which only has a tiny changeset in one javascript file which doesn't explain the changed behavior.

The last succesful builds are https://travis-ci.org/flamingo-geocms/flamingo/builds/347218235 (geotools-19 branch) and https://travis-ci.org/flamingo-geocms/flamingo/builds/347162899 (master branch) both on Feb 28

We are using a similar setup in a different project without any problems, eg. https://travis-ci.org/B3Partners/brmo/branches with a major difference in the config, as that is running with `sudo:true` ([master .travis.yml](https://github.com/B3Partners/brmo/blob/master/.travis.yml)

This may be a duplicate of #7546

**Comment by mprins** [comment]
for some reason it seems that the `.gitconfig` in the home dit is owned by root, see https://travis-ci.org/flamingo-geocms/flamingo/jobs/350721242#L674

**Comment by BanzaiMan** [comment]
Hi. This is quite curious, but I don't think this is an issue with our setup.

In both [passing](https://travis-ci.org/flamingo-geocms/flamingo/jobs/347162901#L16) and [failing](https://travis-ci.org/flamingo-geocms/flamingo/jobs/348177332#L16) jobs the identical image is used (and we have not released new images in the time frame you've given).

If you look at the `~` content with nothing else, that file is [owned by `travis`](https://travis-ci.org/BanzaiMan/travis_production_test/jobs/350824499#L466). Something in your configuration must be.

Indeed, I think it is `git-lfs`. See this after adding it to the above: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/350827662#L490.

**Comment by BanzaiMan** [comment]
I've reported the issue upstream. Hopefully the fix will be out soon. In the meantime, I'm afraid you'll have to use `sudo: required` and revert the ownership back to `travis:travis`.

**Comment by mprins** [comment]
thanx, 
the workaround is not a problem; I do recall a GH blog notifying of a new git-lfs release.

in fact: https://blog.github.com/2018-03-02-git-lfs-2.4.0-released/

**Comment by BanzaiMan** [comment]
It may not be the upstream issue, actually, though the package does seem to play a part.

**Comment by mprins** [comment]
@stale not sure that this has been resolved

**Comment by mprins** [comment]
@Stale Still not sure that this has been resolved

**Comment by mprins** [comment]
still an issue: https://travis-ci.org/flamingo-geocms/flamingo/jobs/469539048#L1053-L1055

**Comment by mprins** [comment]
@Stale Still not sure that this has been resolved

**Comment by mprins** [comment]
@Stale Still not sure that this has been resolved

**Comment by mprins** [comment]
@Stale has this issue been resolved?

**Comment by mprins** [comment]
@Stale has this issue been resolved?

**Comment by mprins** [comment]
@Stale has this issue been resolved?

**Comment by mprins** [comment]
@Stale has this issue been resolved?
