### ISSUE TITLE
Network Timeout Issues in deployment step

### ISSUE THREAD

**Issue by epiclabsDASH** [travis-ci/travis-ci#9310]
Hi,

We are detecting consistent issues in our latest builds (linux based), more specifically issues that seems to be related with network connectivity. One of our steps is deploying the result of our compilation to an ftp server. Since yesterday evening (CET timezone) our deployment process, in the best case, uploads one single file and then gets stalled until a timeout issue is raised. 

This same config has been working like a charm in Travis for the last 2 months, and I have verified same process works fine if I launch it locally.

Build link: https://travis-ci.org/Dash-Industry-Forum/dash.js/builds/350581541

Many thanks in advance!

**Comment by BanzaiMan** [comment]
Hello there. I note that this is probably not an issue with network timeout, but rather a similar one as #9127.
