### ISSUE TITLE
Github Pages deployment is broken with dpl 1.9.0

### ISSUE THREAD

**Issue by theomessin** [travis-ci/travis-ci#9312]
Tried deleting all repository caches as well. Everything worked fine, tried to rebuild the same repo (ie. code) and then nothing worked fine :cry:  

```
Deploying application
/home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:142:in `mkdir': File exists @ dir_s_mkdir - /tmp/d20180308-5759-1rawmx3/work (Errno::EEXIST)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:142:in `github_pull_or_init'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:196:in `block in push_app'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:191:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by deathbeam** [comment]
Same issue happening here after the dpl 1.9.0 update, deploy stopped working.

Here is link to [Travis build](https://travis-ci.org/runelite/runelite.net/builds/350940337?utm_source=github_status&utm_medium=notification)

**Comment by BanzaiMan** [comment]
To revert to the old behavior:

```yaml
deploy:
  edge:
    branch: v1.8.47
  ⋮ # rest
```

**Comment by deathbeam** [comment]
Yeah, started working again after downgrade, ty.

**Comment by dev-head** [comment]
Downgrade isn't working for our enterprise install, reaching out to support at the moment hopefully get something more to go with.

**Comment by BanzaiMan** [comment]
@dev-head What is the version of Travis Enterprise you are running?

**Comment by reicek** [comment]
Same problem here, it just stopped working.

Rolling back fixed it, but now I'll have a commit referencing just this issue on my project :cry: 

Seems like  [dpl 1.9.0 update](https://blog.travis-ci.com/2018-03-05-new-dpl-is-coming#testing-dpl-190-before-the-release) simply broke the deploy system, at least for some of us.

I don't use Ruby at any point in my project (actually at all, I run my project on Node). I used to just deploy to master and it would "just work", so I have some questions:

- Shouldn't this Ruby version update be fully transparent to users like me?
- When will things be working again? (So I can remove that `branch: v1.8.47` part)
- Why is there no proper error message on the console? `Couldn't push the build to github.com/reicek/AI-world.git:gh-pages` provides no reason for *why* it can't.

I'll use this chance to say thanks to the Travis team for such a great project! :1st_place_medal:

**Comment by ShaunaGordon** [comment]
This has been failing for me, too ([latest failing build](https://travis-ci.org/ShaunaGordon/shaunagordon.github.com/builds/351113923)), with or without `keep-history` enabled. Rolling back succeeds, though ([successful build](https://travis-ci.org/ShaunaGordon/shaunagordon.github.com/builds/351117599)).

@reicek It's not Ruby that is breaking, it's DPL, which happens to be written in Ruby (so it's Ruby that's spitting out the stack trace). It's kind of like installing something and getting glibc errors. The author of the Pages diver recently made some major updates to it that made some fundamental changes to how parts of it works.

That said, I agree that "can't push to Github" cryptic as hell and frustrating to troubleshoot.

**Comment by matsp** [comment]
Downgrading is not working with multi delpoyment config ([see](https://github.com/matsp/material-components-vue/commit/5efe5edd2c67735b85e1730c5d1d874f3de69721))

**Comment by inwardmovement** [comment]
As asked in [Travis Blog](https://blog.travis-ci.com/2018-03-05-new-dpl-is-coming#release-schedule), I report here than [my build](https://travis-ci.org/inwardmovement/inwardmovement.github.io/builds/351354454) also fails.

**Comment by reicek** [comment]
You're right @ShaunaGordon , my comment was misleading, already fixed it thanks.

**Comment by BanzaiMan** [comment]
Hello, everyone.

I pushed a potential release for the current problem. To test, please try:

```yaml
deploy:
  provider: pages
  edge:
    branch: pages-ivar-set
⋮
```

(Adjust as needed for multi-deployment definition.)

and report the results. Thank you!

**Comment by jbleyel** [comment]
```
deploy:
  provider: pages
  edge:
    branch: pages-ivar-set
⋮
```
-> error: pathspec 'pages-ivar-set' did not match any file(s) known to git.

```
deploy:
  provider: pages
  edge:
    branch: v1.8.47
⋮
```
-> Success

**Comment by BanzaiMan** [comment]
@jbleyel Oops. I pushed a bad branch name previously. I've fixed this now. Do you mind re-running the failing build? Also, if it is a public repository, please include a build log URL.

**Comment by jbleyel** [comment]
Branch pages-ivar-set works.

**Comment by onaluf** [comment]
Branch pages-ivar-set works for me too:
-> https://api.travis-ci.org/v3/job/351619222/log.txt

**Comment by oncletom** [comment]
I confirm `pages-ivar-set` branch makes it back to normal 👍

**Comment by inwardmovement** [comment]
@BanzaiMan works for me too, thanks!
[build log](https://travis-ci.org/inwardmovement/inwardmovement.github.io)

**Comment by choznerol** [comment]
Branch pages-ivar-set works for me too:
-> https://api.travis-ci.org/v3/job/351628208/log.txt

**Comment by theomessin** [comment]
Works on my end as well https://travis-ci.org/hacksurrey/beta/builds/351665812 :tada:

**Comment by grischard** [comment]
Works for us too, https://travis-ci.org/osmlab/editor-layer-index/builds/351666785. Thank you @BanzaiMan!

**Comment by isteves** [comment]
Wow, I'm so glad I found this thread!  Both downgrading and pages-ivar-set fixed the issues for me.

**Comment by carloscuesta** [comment]
Same problem! And https://github.com/travis-ci/travis-ci/issues/9312#issuecomment-371590249 worksaround it 👌

**Comment by BanzaiMan** [comment]
The fix will be in the `dpl` 1.9.1 release. I'll keep the `puppet_forge-post-1_9_0` branch for a week or so after the 1.9.1 release, so that the repos with this workaround can be switched off it.

**Comment by kaushalmodi** [comment]
> The fix will be in the dpl 1.9.1 release

When is that release?

**Comment by BanzaiMan** [comment]
1.9.1 is out.

**Comment by BanzaiMan** [comment]
I'm locking this to prevent further mentions to this issue from commits pointing to this issue.
