### ISSUE TITLE
TRAVIS_COMMIT_MESSAGE variable incorrect when having subject and body

### ISSUE THREAD

**Issue by szeck87** [travis-ci/travis-ci#9316]
I've been debugging an issue with our OSX build where it sometimes fails with an error stating that it couldn't run gem installed exe's through our test script.  Eventually Travis support had the repo put in debug mode.  When I ran `env`, I noticed that the TRAVIS_COMMIT_MESSAGE environment variable looked off.  I ran echo $[TRAVIS_COMMIT_MESSAGE] and there is a syntax error in there.  See screenshot below.  When I changed it while in debug mode and ran the test script again, it passed.

![screen shot 2018-03-08 at 7 12 33 pm](https://user-images.githubusercontent.com/8315038/37186433-1c90bf76-230b-11e8-9f2d-8b374ef4128d.png)

This seems to happen when you have a subject and body in the commit message.  When doing merges on GitHub, it automatically generates a message and body for the commit that performs the merge by default.

Is this expected behavior in Travis?  Is there something else we should be doing for commit messages?

**Comment by BanzaiMan** [comment]
`$[]` is invalid. Do you mean `${}`?

**Comment by szeck87** [comment]
@BanzaiMan you're right, I don't get that same error message with just `echo $TRAVIS_COMMIT_MESSAGE`.

But I'm still able to recreate the problem just by having subject and body in the commit message.  Here is my fork of the repo with a test commit to show:  https://travis-ci.org/szeck87/atom-beautify/jobs/351126229#L92.  Lines 92-94 show the variable as seen when running `env`.  And like I said, if I modify the variable to something else, it works fine at that point.

I'll also mention the only thing affected seems to be Ruby/Bundle gems.  node, brew, composer installed ones don't have an issue.

**Comment by BanzaiMan** [comment]
What do you mean by "incorrect"? The commit message in this case is:

```
 This is the first paragraph

This is the second paragraph
```

with embedded newlines. Is your code handling such cases?

**Comment by szeck87** [comment]
> Is your code handling such cases?

What does our code need to handle?  We don't use the commit message or that environment variable anywhere in the code.

**Comment by BanzaiMan** [comment]
Maybe I misunderstood. What are you asking? `$TRAVIS_COMMIT_MESSAGE` seems correct to me.

**Comment by szeck87** [comment]
From my investigation it's breaking our build.  I can consistently recreate a failing build by having the commit message like that.  If I make a commit with just one line, it runs fine.

One line commit message:  https://travis-ci.org/szeck87/atom-beautify/builds/351344818
Two line commit message:  https://travis-ci.org/szeck87/atom-beautify/builds/351350754

Similar issue here:  https://github.com/electron-userland/electron-builder/issues/2450

**Comment by BanzaiMan** [comment]
So your code is not handling it in some cases. https://travis-ci.org/szeck87/atom-beautify/jobs/351350757#L2415

**Comment by BanzaiMan** [comment]
I'm closing this, as I do not see anything to fix on our side.

**Comment by bilal-fazlani** [comment]
I am also facing this issues. IMO, Travis CI should provide a safe mechanism to access  TRAVIS_COMMIT_MESSAGE without breaking scripts.
