### ISSUE TITLE
GitHub pages deploy failure, it was working two days ago

### ISSUE THREAD

**Issue by gmarpons** [travis-ci/travis-ci#9317]
Hello,

I have this Travis configuration file: https://github.com/gmarpons/foss-guide-bcn-ca/blob/master/.travis.yml, with different deploys for branches master and develop (the only difference being they push to different repos).

Build https://travis-ci.org/gmarpons/foss-guide-bcn-ca/builds/350261561 worked two days ago with this very same configuration. Now is failing to deploy with:

"Couldn't push the build to github.com/gmarpons/foss-guide-develop.git:gh-pages"

All other builds I've tried have also failed, in both source branches (master, develop) and trying to push either to gh-pages or master. I've generated/added new GitHub access token, and the problem persists. Target branch is not protected.

Many thanks in advance for your help,

Guillem

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
this looks like the same issue described in #9312, can you confirm?

you can try the instructions in [this comment](https://github.com/travis-ci/travis-ci/issues/9312#issuecomment-371590249) as a workaround.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
excellent, thanks!
