### ISSUE TITLE
OpenVZ hosts don't allow loopback mounts

### ISSUE THREAD

**Issue by g2p** [travis-ci/travis-ci#932]
I have [a testsuite](https://github.com/g2p/bedup/blob/master/bedup/test_bedup.py) that [relies on loopback mounts](https://travis-ci.org/g2p/bedup/builds/4802855) (it needs to create a btrfs filesystem and interact with the btrfs kernel module), and that doesn't seem to be allowed by the OpenVZ builders that were introduced recently. Is this something that could be allowed in the OpenVZ configuration, or is nested virtualisation the only option to run this particular testsuite now?

**Comment by hroncok** [comment]
@g2p Could you please point me to a .travis.yml example using vido?

**Comment by gregmac** [comment]
@hroncok 

* https://github.com/g2p/bedup/blob/master/.travis.yml
* https://github.com/naota/godrbd/blob/master/.travis.yml
* https://github.com/g2p/blocks/blob/master/.travis.yml
