### ISSUE TITLE
Redirect from 'https://travis-ci.org/ghc/ghc.svg?branch=master' to 'https://api.travis-ci.org/ghc/ghc.svg?branch=master' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ghc.haskell.org' is therefore not allowed access.

### ISSUE THREAD

**Issue by potomak** [travis-ci/travis-ci#9324]
The page https://ghc.haskell.org/trac/ghc/wiki/WikiStart misses the build status image because the request to https://travis-ci.org/ghc/ghc.svg?branch=master returns the error:

> Redirect from 'https://travis-ci.org/ghc/ghc.svg?branch=master' to 'https://api.travis-ci.org/ghc/ghc.svg?branch=master' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ghc.haskell.org' is therefore not allowed access.

#### Screenshot

![image](https://user-images.githubusercontent.com/153842/37292232-ddb2187a-25e6-11e8-9994-b2afa2a02e60.png)

#### Example response

```
curl -v https://travis-ci.org/ghc/ghc.svg?branch=master
```

```
> GET /ghc/ghc.svg?branch=master HTTP/1.1
> Host: travis-ci.org
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: Cowboy
< Date: Mon, 12 Mar 2018 15:18:23 GMT
< Connection: keep-alive
< Content-Type: text/html;charset=utf-8
< Location: https://api.travis-ci.org/ghc/ghc.svg?branch=master
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 0
< Via: 1.1 vegur
```

Note: if I try to embed the image returned by the resource in the redirect (https://api.travis-ci.org/ghc/ghc.svg?branch=master) it works.

#### Example response from redirected resource

```
curl -v https://travis-ci.org/ghc/ghc.svg?branch=master -L
```

```
> GET /ghc/ghc.svg?branch=master HTTP/1.1
> Host: api.travis-ci.org
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: nginx
< Date: Mon, 12 Mar 2018 15:20:26 GMT
< Content-Type: image/svg+xml
< Content-Length: 724
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: Content-Type, Cache-Control, Expires, Etag, Last-Modified, X-Request-ID
< Strict-Transport-Security: max-age=31536000
< X-Endpoint: Travis::Api::App::Endpoint::RepoStatus
< X-Pattern: /:owner_name/:name
< X-Oauth-Scopes: public
< X-Accepted-Oauth-Scopes: public
< Vary: Accept,Accept-Encoding
< Cache-Control: no-cache
< Etag: "17c6863bea585e3bb6c3691be13e1246"
< Pragma: no-cache
< Expires: Mon, 12 Mar 2018 15:20:26 GMT
< Content-Disposition: inline; filename="passing.svg"
< Last-Modified: Mon, 12 Mar 2018 09:03:04 GMT
< X-Content-Digest: 6a7e16d9fbe5b315f689672a9e5b02a94834961a
< Age: 0
< X-Rack-Cache: miss, store
< X-Request-Id: d070ecc3-b1d4-419c-b09e-f970d095df7a
< Via: 1.1 vegur
```

**Comment by BanzaiMan** [comment]
This falls under the purview of the said site's maintainers. Please contact them to fix it.

**Comment by BanzaiMan** [comment]
or maybe not?

**Comment by drogus** [comment]
This happens, because Trac Wiki adds `crossorigin="anonymous"` attribute to `<img>` tags. I tracked it down to this change: https://trac.edgewall.org/changeset/15894. There's an option to add an origin to safe origins added here: https://trac.edgewall.org/changeset/16025, so as a workaround you could add `travis-ci.org` and `travis-ci.com` to safe origins (apart from changing the host to `api.travis-ci.org`). I'll discuss this with the team and I'll add more details later.

**Comment by potomak** [comment]
@drogus great find! Thanks for the update.

**Comment by JcChimjj** [comment]
#9324
