### ISSUE TITLE
r builds still using 3.4.2 instead of 3.4.3 ?

### ISSUE THREAD

**Issue by ajdamico** [travis-ci/travis-ci#9326]
hi @craigcitro and @jimhester

i just noticed that my travis log is still using 3.4.2 on my repos

	Rscript -e 'sessionInfo()'
	R version 3.4.2 (2017-01-27)
	Platform: x86_64-pc-linux-gnu (64-bit)
	Running under: Ubuntu 14.04.5 LTS
	
i looked around, and it seems others' r release builds are also still stuck in r version 3.4.2
	
https://travis-ci.org/tidyverse/haven/jobs/351723975

https://travis-ci.org/r-dbi/DBI/jobs/352226049

sorry if i'm being dumb.  thanks!

**Comment by jimhester** [comment]
Sorry, should be fixed by https://github.com/travis-ci/travis-build/pull/1327

Also note you can always specify the exact version requirement manually, if you want to force travis to use the current release and the defaults have not been updated!

**Comment by ajdamico** [comment]
thank you!  any idea if this versioning issue is related to libcurl failures that recently popped up in most of my repos?  i don't know enough about all the dependencies here to figure out what changed..  thanks again

https://stackoverflow.com/questions/49254480/r-libraryrcurl-behavior-change-on-travis-ci

**Comment by jimhester** [comment]
@ajdamico, no, I don't think it is related.

**Comment by ajdamico** [comment]
thank you!!!
