### ISSUE TITLE
"We couldn't find the repository"

### ISSUE THREAD

**Issue by feliupe** [travis-ci/travis-ci#9327]
Can someone help me with this?

![image](https://user-images.githubusercontent.com/4684166/37341363-6c86b468-26c1-11e8-8819-11cf900b58de.png)

![image](https://user-images.githubusercontent.com/4684166/37341334-4eb7c95e-26c1-11e8-84a3-1972d763b4f9.png)

**Comment by BanzaiMan** [comment]
At the moment, we are experiencing outage in .com. Please subscribe to this issue: https://www.traviscistatus.com/incidents/z2b3lz2kwcfp

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
The incident has been resolved, so I'm going to close this ticket.

**Comment by feliupe** [comment]
Thanks guys, good job :)
