### ISSUE TITLE
"There are no builds for this repository."

### ISSUE THREAD

**Issue by moaiad717** [travis-ci/travis-ci#9328]
There's something wrong with this repo:

https://travis-ci.org/moaiad717/expediaEx2

It says "There are no builds for this repository." and "build unknown" in the badge.

**Comment by BanzaiMan** [comment]
Should there be any build on this repository?

**Comment by BanzaiMan** [comment]
Have you pushed a commit since enabling it?

**Comment by moaiad717** [comment]
yes, i pushed the .travis.yml file .

**Comment by moaiad717** [comment]
never mind, its working fine now
