### ISSUE TITLE
Travis doesn't run for PR - Waiting for status to be reported

### ISSUE THREAD

**Issue by zoechi** [travis-ci/travis-ci#9331]
private repo
https://github.com/lookAtYouInc/lookatmybaby/pull/784
https://travis-ci.com/lookAtYouInc/lookatmybaby

![image](https://user-images.githubusercontent.com/405837/37399447-ffcf8450-2781-11e8-9e4c-b0322560936c.png)

![image](https://user-images.githubusercontent.com/405837/37399520-2648733a-2782-11e8-9e67-c2249513f275.png)

**Comment by BanzaiMan** [comment]
Hello, there. Looks like your subscription has expired. Could you check it at https://billing.travis-ci.com? If you have further questions, please email us at support@travis-ci.com, and we will help you.

Since it is a private matter, I'm closing this public ticket.

Thanks.

**Comment by zoechi** [comment]
@BanzaiMan Thanks for checking!
Should I see this anywhere in the Travis site?

I'm only a developer and don't manage payments.
A proper hint that this is the reason Travis doesn't run builds would be quite helpful,
so that I can give the owners a note. 
If they get an email message from Travis the'll have no idea what this is about and probably ignore it.

**Comment by BanzaiMan** [comment]
@zoechi Indeed, that would be useful. I'll open an internal ticket to track that.

**Comment by BanzaiMan** [comment]
Just to clarify: the current message (seen in https://travis-ci.com/lookAtYouInc/lookatmybaby/requests) reads:

> Could not authorize build request for lookAtYouInc/lookatmybaby.

This was not sufficient to understand the issue, correct?

**Comment by zoechi** [comment]
Where did it say that? I only saw "waiting for status ..."
I also wouldn't interpret "Could not authorize ..." 
as "charged service not available because payment failed"

**Comment by BanzaiMan** [comment]
If you hover the cursor over the text in the rightmost column of the request page, you should see that.

**Comment by BanzaiMan** [comment]
Having a valid subscription is not the only reason a build request for a private repository can be accepted (e.g., Educational accounts, accounts with trials left), so the message would have included all of these instead.

**Comment by zoechi** [comment]
You can of course find a more generic message. I don't know Travis that well and I'm not a native English speaker. 

I think there should be a message that indicates that user interaction is required 
and a pointer where (account settings, payment settings, ...)

**Comment by zoechi** [comment]
@BanzaiMan I don't even know what "request page" means :-/
