### ISSUE TITLE
macOS: Corrupted `cgal` archive in homebrew cache

### ISSUE THREAD

**Issue by andreabolognani** [travis-ci/travis-ci#9340]
It looks like the homebrew cache contains a corrupted archive for the `cgal` package: running

```
brew update && brew upgrade
```

on macOS results in the following error being logged:

```
==> Installing postgis dependency: cgal
==> Downloading https://homebrew.bintray.com/bottles/cgal-4.11.1.sierra.bottle.tar.gz
Error: SHA256 mismatch
Expected: 32e877c60b4027c9daf9dd9c8c8359097e333327d06fe18d3768bb80e89183db
Actual: dfb607d915656ff43d64d0df1586543903b15d4b30191b65339ba43ad9fe92e2
Archive: /Users/travis/Library/Caches/Homebrew/cgal-4.11.1.sierra.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
```

The build will ultimately succeed, or at least it did before recent changes related to Python caused `brew upgrade` to fail altogether.

See https://travis-ci.org/libvirt/libvirt/jobs/351377032 for an example of the error occurring.

**Comment by BanzaiMan** [comment]
Hello. Why is this a Travis CI issue? I downloaded the archive in question on my machine, and the checksum indeed is dfb…:
```sh-session
$ curl -LO https://homebrew.bintray.com/bottles/cgal-4.11.1.sierra.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 6102k  100 6102k    0     0  3631k      0  0:00:01  0:00:01 --:--:-- 18.9M
$ shasum -a 256 cgal-4.11.1.sierra.bottle.tar.gz
dfb607d915656ff43d64d0df1586543903b15d4b30191b65339ba43ad9fe92e2  cgal-4.11.1.sierra.bottle.tar.gz
```

It seems to me that either Homebrew's expected checksum (32e8…) is wrong, or something updated the archive unexpectedly. Either way, it seems to me that the tool is working as expected.

I suggest reporting the issue to https://github.com/Homebrew/homebrew-core.

**Comment by andreabolognani** [comment]
Yeah, I think you're right. I have zero experience with homebrew outside of Travis, and I clearly misjudged the situation.

FWIW I just opened https://github.com/Homebrew/homebrew-core/pull/25319 against homebrew-core, hopefully that'll solve the problem or lead to a solution.

I'll close this issue now, sorry for the noise.
