### ISSUE TITLE
Erlang/OTP version 20 is supported by elixir 1.6.3 but it's using otp 19.

### ISSUE THREAD

**Issue by steffenix** [travis-ci/travis-ci#9341]
i got the error:
`Erlang/OTP Release [20.1] is not supported by Elixir 1.6.3. Using OTP Release 19.0.`

But you can see the 1.6 is compatible with elixir 1.6:
https://hexdocs.pm/elixir/master/compatibility-and-deprecations.html

Build URL: https://travis-ci.org/CityOfZion/neochat/jobs/353850650

**Comment by BanzaiMan** [comment]
https://github.com/CityOfZion/neochat/commit/45fb6aae3e967c03ea9c454d63bb83bee8cab030#diff-354f30a63fb0907d4ad57269548329e3R6

When adding a job with `matrix.include` and `jobs.include`, each job must define the language runtime exactly. In your case, this means that you must pass

```yaml
otp_release: '20.1'
```

**Comment by BanzaiMan** [comment]
It is surprising to me that `node_js` is accepting `[stable]`.

**Comment by BanzaiMan** [comment]
Ah, I see. We take explicitly the first value in the `node_js` array. We should probably do the same with other languages to accommodate this common error.

**Comment by steffenix** [comment]
Cool thanks for the answer.
