### ISSUE TITLE
npm publish failure: `env: encrypt: No such file or directory`

### ISSUE THREAD

**Issue by giannif** [travis-ci/travis-ci#9342]
One of our jobs is failing to publish to npm. This is a private npm package, and we're logging in, and authentication is a success. We have other jobs that are similar, and they work. 

The only clue is:
`env: encrypt: No such file or directory`

I have gotten no where googling this. Any help would be appreciated. 

<img width="752" alt="screen shot 2018-03-15 at 10 06 05 am" src="https://user-images.githubusercontent.com/448767/37479015-d15eb2a0-2838-11e8-9cd4-2704f1f43924.png">

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by giannif** [comment]
It's a private repo

**Comment by giannif** [comment]
If anyone has this problem, I had to log in and out of travis pro to correctly generate my token
