### ISSUE TITLE
Travis C# build is broken

### ISSUE THREAD

**Issue by bo20202** [travis-ci/travis-ci#9344]
https://travis-ci.org/bo20202/ByondHub/builds/354015796
@joshua-anderson @akoeplinger @nterry

**Comment by RethoughtSolutions** [comment]
Exactly the same error for me, tried different things since 2 hours but nothing seems to work

**Comment by gpictonmg** [comment]
Same error here

**Comment by jonathanrjones** [comment]
Looks like it's likely related to this: https://github.com/Microsoft/vscode/issues/45868

**Comment by bo20202** [comment]
Looks like it's fixed https://travis-ci.org/bo20202/ByondHub/builds/354041814
