### ISSUE TITLE
Is it possible to pin a pgsql version via POSTGRESQL_VERSION up to the patch number?

### ISSUE THREAD

**Issue by scara** [travis-ci/travis-ci#9346]
Hello,
is it possible to pin the version of `env: DB=pgsql` via `POSTGRESQL_VERSION` using optionally the _patch_ version too e.g. `9.6.7`?
It looks like that only `major.minor` can be used since using `POSTGRESQL_VERSION=9.6.7` deploys `9.6.8`, the latest among the 9.6s.

Some recent changes (1 March) create some regressions and it will be useful to stick to 9.6.7 for some tests.

TIA,
Matteo

**Comment by BanzaiMan** [comment]
I'm afraid not. We rely on the APT package from https://apt.postgresql.org, and if the package we use is faulty, we will have to wait until the issue is fixed upstream.

**Comment by scara** [comment]
Hi @BanzaiMan,
it's not faulty but it has been shipped with some breaking changes in the way some SQL statements are now prepared so there is the need to play with actually both `9.6.7` and `9.6.8`, if we play w/ the `9.6` "branch".

It would be really useful to be able to play with the third number. Is it possible via `env`?

TIA,
Matteo

**Comment by scara** [comment]
TNX @BanzaiMan for the link, I missed your point 'till now.
Much appreciated 👍.

Closing 😞.
