### ISSUE TITLE
Got 425 Cannot open data connection when uploading files through ftp

### ISSUE THREAD

**Issue by jdneo** [travis-ci/travis-ci#9347]
Hi team.

I'm using travis CI to run some integration test for my project. The integration test is trying to upload some files onto the target ftp server. The ftp client is using local passive mode.

The integration test works well previously, but start from some time ago, it always get '425 Cannot open data connection' when doing the uploading. (Actually not every time but almost.)

I've run the integration test locally and it can upload the files correctly. Is that related with the CI firewall setting? Any suggestions about this?

Thanks!

**Comment by BanzaiMan** [comment]
I think this is a variation of https://github.com/travis-ci/travis-ci/issues/9112#issuecomment-373031537.

**Comment by jdneo** [comment]
@BanzaiMan Thanks for pointing out. 

To give some more information: The target ftp server I'm uploading with is an Azure Web App ftp server.

And is there any suggestion on how to mitigate this?

**Comment by BanzaiMan** [comment]
If you can run your builds on containers, do. (https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments) We have not figured out how the failures are happening with FTP servers.

**Comment by jdneo** [comment]
The problem seems resolved after I switch to the containers. Thanks.

**Comment by angelgbi** [comment]
For those like me that are searching why are getting errors with ftp connections, here is the answer https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci. 

If you want to use FTP you need to set travis to run on a [container-based environment](https://docs.travis-ci.com/user/reference/overview/#container-based).

A note from travis doc: 

> Note that the following keywords in your .travis.yml file will silently route your builds to our sudo-enabled infrastructure (even if you specify sudo: false): docker, ping, sudo.

**Comment by cderv** [comment]
Hi,
since the [end of container based environment](https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures), we do not have a choice anymore and we encounter an issue we thing related to this (`RETR response: 425`).

Have you a new solution or hints ? We only have FTP as option and not HTTPS or SFTP as advice in the FTP blog post linked above. There is something mentioned about a VPN tunnelling option. Did you try ? 
Thanks.
