### ISSUE TITLE
Python issues with pypy + lxml

### ISSUE THREAD

**Issue by wltjr** [travis-ci/travis-ci#9349]
I am experiencing some odd issues. All of a sudden using lxml with pypy seems to no longer work. It was working and now portage has issues with lxml saying its missing after install.

[Passed build 558](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo/builds/351788804)
[Failed build 559](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo/builds/353158932), no change to travis.yml.
[Passed build 560 Switch to python 3.6](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo/builds/353654926)
[Failed build 561 switch back to pypy](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo/builds/353660011)

Not sure what is going on, but there was no change to my travis.yml between build 558 and 559, thus 559 should not have failed. Seems something changed with Travis images or the environment. Python versions other than pypy double the runtime, so need to fix that route. Why pypy + lxml is failing all of a sudden seems to be on the Travis end of things, nothing I am doing or changed.

Thanks!

**Comment by BanzaiMan** [comment]
Try creating a new branch off (or create a new tag for) this previously passing commit: https://github.com/Obsidian-StudiosInc/os-xtoo/commit/120dbb8adb276de03ca8b82bab2d470dca99ccaa. If it now fails, it most likely means that the changes in underlying dependencies is to blame. Most notably, I see lxml was upgraded from [4.1.1](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo/builds/351788804#L450) to [4.2.0](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo/builds/353158932#L450).

**Comment by wltjr** [comment]
Not to likely as [lxml version 4.2.0 has no issues in Shippable](https://app.shippable.com/github/Obsidian-StudiosInc/os-xtoo/runs/479/1/console) under ```build_ci``` -> ```pip install lxml``` unable to direct link. I see same [lxml version 4.2.0 in Travis build 559 that failed](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo/builds/353158932#L457).

**Comment by BanzaiMan** [comment]
My point is that the PyPy + lxml 4.2.0 combo has a problem. I don't see this working in any of the things you've mentioned. Did I miss anything?

**Comment by wltjr** [comment]
It has no problem on Shippable... Yes you clearly seem to miss that pypy + lxml 4.2.0 works fine on Shippable.

Like [this shippable build](https://app.shippable.com/github/Obsidian-StudiosInc/os-xtoo/runs/476/1/console), here is its information
```
Python 2.7.13 (0e7ea4fe15e8, Dec 22 2017, 08:44:03)
[PyPy 5.10.0 with GCC 6.2.0 20160901]
pip 9.0.1 from /root/venv/pypy/site-packages (python 2.7)
   pip install lxml 43s  
Collecting lxml
  Downloading lxml-4.2.0.tar.gz (4.3MB)
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml: started
  Running setup.py bdist_wheel for lxml: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/56/1d/b7/51f6bc4e8ac688ac653be0a6fca2a2e03ce772b0d74a55a296
Successfully built lxml
Installing collected packages: lxml
Successfully installed lxml-4.2.0
```

So you say pypy + lxml 4.2.0 has a problem. But that problem does NOT exist on Shippable. Thus something on Travis seems off. Travis builds started failing, not Shippable. I can use lxml 4.2.0 + pypy in Shippable, but I can not in Travis. Thus there must be something off or different in Travis.

**Comment by BanzaiMan** [comment]
Thanks for the info. The failing build on Travis is using PyPy 5.8.0 https://travis-ci.org/Obsidian-StudiosInc/os-xtoo/builds/353660011#L450 Does 5.10.0 similarly fail?

We are happy to enable the debug feature if you are interested.

**Comment by wltjr** [comment]
pypy 5.10.0 works on Shippable, that is the version being used as shown above with lxml 4.2.0. I think the problem is pypy 5.8.0 + lxml 4.2.0. I think pypy needs to be 5.10.0 for lxml 4.2.0. Maybe only lxml 4.1.1 works with pypy 5.8.0.

I checked some past Shippable builds
[Shippable build 467](https://app.shippable.com/github/Obsidian-StudiosInc/os-xtoo/runs/467/1/console) uses pypy 5.8.0 with pypy 4.1.1
```
Python 2.7.13 (c925e7381036, Jun 05 2017, 21:20:51)
[PyPy 5.8.0 with GCC 6.2.0 20160901]
Successfully installed lxml-4.1.1
```

[Shippable build 468](https://app.shippable.com/github/Obsidian-StudiosInc/os-xtoo/runs/468/1/console) uses pypy 5.10.0 with pypy 4.1.1
```
Python 2.7.13 (0e7ea4fe15e8, Dec 22 2017, 08:44:03)
[PyPy 5.10.0 with GCC 6.2.0 20160901]
Successfully installed lxml-4.1.1
```

The latest Shippable builds use pypy 5.10.0 with lxml 4.2.0 as shown in previous comment. Thus pretty sure the problem comes from pypy 5.8.2 + lxml 4.2.0. Those maybe incompatible.

**Comment by wltjr** [comment]
Working around this for now with
```diff
-    - pip install lxml
+    - pip install lxml==4.1.1
```

Easier than updating pypy, but seems lxml 4.2.0 requires pypy 5.10.0, and has issues with 5.8.0. 

Though long term I think Travis should have at least 5.10.0 of pypy, or prevent pip from updating lxml to 4.1.1, so older version of pip cache, etc.

**Comment by BanzaiMan** [comment]
You can use pypy3.5-5.10.1 by specifying it. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/355057105#L431

The pre-installed version may be old, but it will be updated with future updates.

I don't think there is much to do here, so I'll close this.

**Comment by wltjr** [comment]
I will try pypy3, for some reason they are omitting pypy3 on [portage travis](https://github.com/gentoo/portage/blob/master/.travis.yml#L2). But it works for 3.x so I assume pypy3 would work as well.

Thanks for updating on future updates!

**Comment by wltjr** [comment]
Pypy3 cannot be used for the same reasons as pypy, [build failed](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo/jobs/355074154). They are both 5.8.0, and that does not work with lxml 4.2.0, only lxml 4.1.1. Both pypy and pypy3 need to be 5.10.0 for lxml 4.2.0.

**Comment by wltjr** [comment]
Oh sorry I missed I needed to specify other stuff for pypy3-5.10.0 I will try that, thanks!

**Comment by BanzaiMan** [comment]
Ah, sorry, I see that I wasn’t more specific. Let us know if you still find problems.

**Comment by wltjr** [comment]
@BanzaiMan no worries you have been more than helpful. It turns out this was an upstream issue per https://github.com/mrueg/repoman-travis/issues/29#issuecomment-375921184. Seems lxml 4.2.1 is working with python 5.8.0. Must have been something specific to 4.2.0. Feel free to keep open or close. It seems moot now on Travis python version updating.
