### ISSUE TITLE
xvfb-run: command not found

### ISSUE THREAD

**Issue by relsqui** [travis-ci/travis-ci#9351]
I'm trying to run some GUI tests in Travis, following the directions [here](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI), but when I try to invoke `xvfb-run` it just tells me `command not found`. Is that method still supported? Do I need to install xvfb-run myself? Do I need to _also_ start xvfb myself before starting the script section? (I'd be happy to PR a docs change if I'm just confused about how this is supposed to work.)

The actual line I'm trying to run, in my script section (of an otherwise-working job, on a private project) looks something like:

`- if [ "$RUN_GUI_TEST" == "true" ]; then do_some_prep_stuff && cd test_dir/ && xvfb-run --server-args="-screen 0 1280x1024x24" npm run test; fi`

Result:

`/Users/travis/.travis/job_stages: line 57: xvfb-run: command not found`

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by relsqui** [comment]
Aha, will do! My bad.

**Comment by KimNikB** [comment]
May I know what the solution to this was in broad terms? I have the same issue

**Comment by relsqui** [comment]
@KimNikB I'm afraid I don't remember, and am no longer working at the company I sent that support email from. If there was a generalizable answer in that email thread, though, Travis CI folks have my permission to share it.
