### ISSUE TITLE
R `sudo: required` builds fail to access ftp:// sites

### ISSUE THREAD

**Issue by ajdamico** [travis-ci/travis-ci#9352]
hi, hopefully i've narrowed this down enough..  here's a [barebones R package repository state](https://github.com/asdfree/trendy/tree/50198cd73d3fa81c214d703fbe74f77ce67322fe) without `sudo: required`  

this R package repository does *nothing* except run one line in [tests/setup.R](https://github.com/asdfree/trendy/blob/50198cd73d3fa81c214d703fbe74f77ce67322fe/tests/setup.R)

	download.file('ftp://ftp.cdc.gov/pub/data/Brfss/CDBRFS84_XPT.zip',tempfile(),mode='wb')

a month ago, ftp:// sites worked with `sudo: required` but now they fail.

adding `sudo: required` to the `.travis.yml` file turns travis from green to red:

green: https://travis-ci.org/asdfree/trendy/builds/354555624
change: https://github.com/asdfree/trendy/commit/b951c81636d8c64fb9d2e4c276419cbd1bdef2ec
red: https://travis-ci.org/asdfree/trendy/builds/354555729
	
i noticed this change when all of my code that required ftp:// access started failing, despite no known changes on my end?

one month ago: https://travis-ci.org/asdfree/trendy/builds/340800484
cron job, no changes but failure:  https://travis-ci.org/asdfree/trendy/builds/352670121

any idea how i can regain ftp:// download access with `sudo: required` on R builds?  thanks!!

cc  @craigcitro  @jimhester

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/9112#comment-373031537

**Comment by ajdamico** [comment]
ahh thanks so much!  i'm sorry i missed this

**Comment by BanzaiMan** [comment]
No worries. I'm closing as a duplicate.
