### ISSUE TITLE
Setting hosts not working as expected

### ISSUE THREAD

**Issue by loic-lopez** [travis-ci/travis-ci#9354]
Hello,

I am using nginx and php-fpm and i got 404 on a existing route : 
`http://api.company.local/api/authenticate/register`

I have an issue with travis and hosts : 
**file .travis.yml**
```
before_script:
  - sudo cp ServerConfig/sites-available.travis/* /etc/nginx/sites-available/
  - sudo ln -s /etc/nginx/sites-available/api.company.conf /etc/nginx/sites-enabled/
  - sudo ln -s /etc/nginx/sites-available/company.conf /etc/nginx/sites-enabled/
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo cat /etc/nginx/sites-enabled/company.conf
  - sudo cat /etc/nginx/sites-enabled/api.company.conf
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo service nginx restart
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - sudo service nginx status

addons:
  hosts:
    - company
    - company.local
    - api.company.local
```

**travis log**
<img width="695" alt="capture d ecran 2018-03-17 a 11 31 06" src="https://user-images.githubusercontent.com/17724398/37554309-d0ec0ee0-29d6-11e8-8a16-6e52917ed286.png">

**PHP code**

<img width="892" alt="capture d ecran 2018-03-17 a 11 32 38" src="https://user-images.githubusercontent.com/17724398/37554316-ed134fca-29d6-11e8-9a9d-0f81f70ac3cb.png">

**Comment by BanzaiMan** [comment]
I don’t think is a problem with the `hosts` addon. The fact that you get a response from `api.company.local` at all means that the addon is working correctly.

That you are getting an unexpected status is an application issue.

**Comment by loic-lopez** [comment]
I have the same configuration on vmware and all tests are passing.

**Comment by BanzaiMan** [comment]
Try dropping `api.company.local` from the `hosts` definition. If you get connection refused error, it means that the addon is working correctly.
