### ISSUE TITLE
Deploy GitHub pages using sphinx-versioning

### ISSUE THREAD

**Issue by Levi-Armstrong** [travis-ci/travis-ci#9356]
Hello,

I am new to using travis-ci and I noticed that you documentation around deploying GitHub pages and I was wanting to try it for updating documentation for this [repository](https://github.com/ros-industrial/ros_qtc_plugin). The only thing is I need to use sphinx-versioning which is a tool which packages all of the documentation for a set branches(aka. versions) into a single set of documents to be pushed for GitHub pages. The current process used is below where I would like to have travis-ci perform every time a pull request is accepted (except for the master branch) and push the changes. Is this possible?

My current process is:
```
git clone https://github.com/ros-industrial/ros_qtc_plugin.git
cd ros_qtc_plugin
git checkout master
sphinx-versioning build -i -b -B 4.4 -r 4.4 -w "^4.*" gh_pages .
git add .
git commit -m "Update Documentation"
git push origin master
```

**Comment by BanzaiMan** [comment]
PR builds will not trigger deployments, so you can't use the Pages deployment provider to accomplish what you describe.

You can use `after_success` to achieve parts of what you are after (https://docs.travis-ci.com/user/deployment/custom/), but only for the PRs that come from the same repo (no forks).

**Comment by Levi-Armstrong** [comment]
Thank you for the help. I will take a look.
