### ISSUE TITLE
Builds keep failing on NodeJS 8 during "npm ls"

### ISSUE THREAD

**Issue by unional** [travis-ci/travis-ci#9357]
https://travis-ci.org/unional/komondor/builds/354929256

It fails at or after npm printing out the dependency tree.

The build works fine for NodeJS 9 and 6.

I tried disabling cache and script but it still fails.

**Comment by unional** [comment]
I've seen the same failure on several other repos. e.g.:
https://travis-ci.org/unional/domture/builds/354489809?utm_source=github_status&utm_medium=notification

**Comment by iriberri** [comment]
This brings me to a fix we released months ago for this behavior where `npm ls` was exiting with non-zero exit codes: https://github.com/travis-ci/travis-build/pull/1098. It looks like this has surfaced again 🤔

**Comment by unional** [comment]
This occurs 80% of the time. If I restart the job enough times, it will go through.
This is currently blocking so many packages that rely on `semantic-release` for publishing.

**Comment by BanzaiMan** [comment]
Can you try other versions of Node.js 8.* (say, 8.0, 8.1.4, etc.)? The fact that it is always the 8.* and not others leads me to think that there is something wrong with that setup.

**Comment by unional** [comment]
How can I do that? I only do:

```yaml
# travis.yaml

node_js:
  - 9
  - 8
  - 6
```

**Comment by unional** [comment]
However, the issue is if I just restart the job, once in a while it will pass.

**Comment by BanzaiMan** [comment]
You can specify any version that `nvm` takes; e.g.,

```yaml
node_js:
  - 8.0.0
```

**Comment by unional** [comment]
I tested to 8.0.0 for a while now and the issue does not exist with 8.0.0.
So it is latest nodeJS 8 doesn't work well with travis
