### ISSUE TITLE
Travis can't find .travis.yml file even though it exist

### ISSUE THREAD

**Issue by kyngsteev** [travis-ci/travis-ci#9358]
https://travis-ci.org/kyngsteev/WeConnect/builds/355060293
"Could not find .travis.yml, using standard configuration."

.travis.yml is there. Why can Travis not find it?

**Comment by BanzaiMan** [comment]
It does not exist on the commit that triggered the build. https://github.com/kyngsteev/WeConnect/tree/827752c5428c9edecae7f321f60a45796b24c65a

**Comment by BanzaiMan** [comment]
Did you forget to add it to the repo?

**Comment by kyngsteev** [comment]
Thanks. Added .travis.yml file to the root and issue was resolved.
