### ISSUE TITLE
dpkg-deb: error: archive has premature member 'control.tar.xz' before 'control.tar.gz'

### ISSUE THREAD

**Issue by carmat88** [travis-ci/travis-ci#9361]
Hello Travis Folks! I would like to report/follow up about a funny (and a bit of an headache) glitch of the currently used Ubuntu image for the CI. I've already touched upon it [in this other thread](https://github.com/travis-ci/travis-ci/issues/8823).

At present in our builds (here is a recent example: https://travis-ci.org/kubenow/image/jobs/355375998), by running a simple command such as: `sudo apt-get upgrade -y` we get stuck with the following error:

```
dpkg-deb: error: archive '/var/cache/apt/archives/base-files_10.1_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/base-files_10.1_amd64.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/base-files_10.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
The probable cause is this bug: https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627

However, I've already tried to first update, autoremove, autoclean, autopurge, even upgrading dpkg. The result is always the same, urgh.

So I've started speculating that maybe the Ubuntu image you're using might need to be rebuilt or directly swapped with a different version of the same release.
Thus as a test I went to one of our openstack providers and created a server with `Ubuntu 14.04 Trusty Tahr 20160304` as OS. The exact sequence of commands that make the above linked CI build failing do not generate any issues at all. Here is the sequence:

```
# Installing Azure command-line client
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
  - sudo apt-get -qq update
  - sudo apt-get -qq upgrade -y
  - sudo apt-get -qq autoremove -y
  - sudo apt-get -qq install apt-transport-https -y && sudo apt-get -qq install azure-cli -y
```

We could workaround this issue by moving those _sudo apt-get_ steps into a bash script and making sure that such a script will always return a zero in order to not break the build process. This is not  ideal and elegant though. Above all, we need certain tools to be installed within the .travis.yml (in this specific case is the azure-cli).

What do you guys think about such glitch? Any suggestions and/or recommendations?

Thanks for you help! Cheers.

**Comment by carmat88** [comment]
Hey guys! As a follow up, it seems that I somehow managed to fix this glitch by removing a specific section in the `.travis.yml` file. Specifically, I was using the `addons` block as follow:

```
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
```
Taking this block out of the travis file fixed all my issues related to funky errors with apt-get. I am honestly not fully understanding why, but you might want to dig into it in case that was useful to understand other past and future similar reported issues (if any).

Cheers!

**Comment by peternewman** [comment]
That would make sense @carmat88 , Debian Sid is their unstable, so newer than say 16.04 and therefore would have tar.xz support and so they'd likely be building packages to support it.

You probably need to either re-archive shellcheck as tar.gz, or source an older deb which is packaged as tar.gz.

**Comment by mintar** [comment]
Yep, the problem is still there. A workaround is to add the following line to your .travis.yml:

```yaml
  - sudo apt-get install -y dpkg  # to upgrade to dpkg >= 1.17.5ubuntu5.8, which fixes https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627
```

But the **proper** fix would be for travis to upgrade dpkg in their base image to  >= 1.17.5ubuntu5.8 .

**Comment by vadi2** [comment]
A better solution now is to use the Xenial image, where the problem is fixed:

```
dist: xenial
```

**Comment by matks** [comment]
Hi, just wanted to share I fixed this issue following https://github.com/EC-CUBE/eccube-2_13/pull/311/files ✅

**Comment by jyhro** [comment]
dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/00-logrotate_3.19.0-1ubuntu1.1_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/00-logrotate_3.19.0-1ubuntu1.1_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/01-dpkg-dev_1.21.1ubuntu2.1_all.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/01-dpkg-dev_1.21.1ubuntu2.1_all.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/02-libdpkg-perl_1.21.1ubuntu2.1_all.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/02-libdpkg-perl_1.21.1ubuntu2.1_all.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/03-libgail-3-0_3.24.33-1ubuntu2_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/03-libgail-3-0_3.24.33-1ubuntu2_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/04-libgtk-3-common_3.24.33-1ubuntu2_all.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/04-libgtk-3-common_3.24.33-1ubuntu2_all.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/05-libgtk-3-0_3.24.33-1ubuntu2_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/05-libgtk-3-0_3.24.33-1ubuntu2_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/06-gir1.2-gtk-3.0_3.24.33-1ubuntu2_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/06-gir1.2-gtk-3.0_3.24.33-1ubuntu2_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/07-libgtk-4-common_4.6.3+ds1-0ubuntu1_all.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/07-libgtk-4-common_4.6.3+ds1-0ubuntu1_all.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/08-libgtk-4-1_4.6.3+ds1-0ubuntu1_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/08-libgtk-4-1_4.6.3+ds1-0ubuntu1_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/09-gir1.2-gtk-4.0_4.6.3+ds1-0ubuntu1_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/09-gir1.2-gtk-4.0_4.6.3+ds1-0ubuntu1_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/10-libclutter-gst-3.0-0_3.0.27-2ubuntu1_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/10-libclutter-gst-3.0-0_3.0.27-2ubuntu1_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/11-gstreamer1.0-clutter-3.0_3.0.27-2ubuntu1_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/11-gstreamer1.0-clutter-3.0_3.0.27-2ubuntu1_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/12-gtk-update-icon-cache_3.24.33-1ubuntu2_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/12-gtk-update-icon-cache_3.24.33-1ubuntu2_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/13-libgtk-3-bin_3.24.33-1ubuntu2_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/13-libgtk-3-bin_3.24.33-1ubuntu2_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/14-libgtk-4-bin_4.6.3+ds1-0ubuntu1_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/14-libgtk-4-bin_4.6.3+ds1-0ubuntu1_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/15-libsvn1_1.14.1-3ubuntu0.22.04.1_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/15-libsvn1_1.14.1-3ubuntu0.22.04.1_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/16-xdg-desktop-portal_1.14.3-0ubuntu2.22.04.1_amd64.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/16-xdg-desktop-portal_1.14.3-0ubuntu2.22.04.1_amd64.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         dpkg-deb: error: el archivo `/tmp/apt-dpkg-install-QRz6q5/17-xdg-utils_1.1.3-4.1ubuntu1.22.04.1_all.deb' contiene un miembro de datos `control.tar.zst' ininteligible, abandono
dpkg: error al procesar el archivo /tmp/apt-dpkg-install-QRz6q5/17-xdg-utils_1.1.3-4.1ubuntu1.22.04.1_all.deb (--unpack):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
No se escribió ningún informe «apport» porque ya se ha alcanzado el valor de «MaxReports»
         Se encontraron errores al procesar:
 /tmp/apt-dpkg-install-QRz6q5/00-logrotate_3.19.0-1ubuntu1.1_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/01-dpkg-dev_1.21.1ubuntu2.1_all.deb
 /tmp/apt-dpkg-install-QRz6q5/02-libdpkg-perl_1.21.1ubuntu2.1_all.deb
 /tmp/apt-dpkg-install-QRz6q5/03-libgail-3-0_3.24.33-1ubuntu2_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/04-libgtk-3-common_3.24.33-1ubuntu2_all.deb
 /tmp/apt-dpkg-install-QRz6q5/05-libgtk-3-0_3.24.33-1ubuntu2_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/06-gir1.2-gtk-3.0_3.24.33-1ubuntu2_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/07-libgtk-4-common_4.6.3+ds1-0ubuntu1_all.deb
 /tmp/apt-dpkg-install-QRz6q5/08-libgtk-4-1_4.6.3+ds1-0ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/09-gir1.2-gtk-4.0_4.6.3+ds1-0ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/10-libclutter-gst-3.0-0_3.0.27-2ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/11-gstreamer1.0-clutter-3.0_3.0.27-2ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/12-gtk-update-icon-cache_3.24.33-1ubuntu2_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/13-libgtk-3-bin_3.24.33-1ubuntu2_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/14-libgtk-4-bin_4.6.3+ds1-0ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/15-libsvn1_1.14.1-3ubuntu0.22.04.1_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/16-xdg-desktop-portal_1.14.3-0ubuntu2.22.04.1_amd64.deb
 /tmp/apt-dpkg-install-QRz6q5/17-xdg-utils_1.1.3-4.1ubuntu1.22.04.1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
