### ISSUE TITLE
Old versions of Firefox no longer downloading

### ISSUE THREAD

**Issue by spookylukey** [travis-ci/travis-ci#9362]
I am following the docs for getting specific versions of Firefox:

https://docs.travis-ci.com/user/firefox

My code:

    addons:
      firefox: "45.2.0"

However, it does not install. `firefox --version` returns:

    Mozilla Firefox 56.0.2

See this build for example - https://travis-ci.org/django-functest/django-functest/jobs/355308796

This line may explain it:

    export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-45.2.0&lang=en-US&os=linux64'

If you try that URL you get a 404. It seems only recent/ESR versions are available at that URL. Old Firefox binaries can now be found here:  https://ftp.mozilla.org/pub/firefox/releases/

This has been broken for a while it seems - for example this build 7 months ago - https://travis-ci.org/django-functest/django-functest/jobs/265262565

It outputs ``Mozilla Firefox 31.0`` instead of the expected "45.2". However, that build succeeded since obviously Firefox 31.0 worked fine. However, somewhere between 7 months and 5 months ago, the default Firefox version on TravisCI machines changed - see https://travis-ci.org/django-functest/django-functest/jobs/284733334 where it has jumped to Firefox 55, and now my build fails (this is connected to Selenium compatibility with more recent Firefox versions).

So, this functionality has been broken for longer, but has only started affecting my builds for about 5 months, because of the change in default Firefox version.

Thanks!

**Comment by BanzaiMan** [comment]
FYI: This download URL scheme has been in place for a couple of years. See https://github.com/travis-ci/travis-build/pull/553

I suppose we could try falling back to the old scheme if the new scheme yields a 404.

**Comment by BanzaiMan** [comment]
By the way, what good is testing with such an old version of Firefox, today?

**Comment by BanzaiMan** [comment]
I should add, though, that this seems like an issue to raise with Mozilla. 🤔

**Comment by spookylukey** [comment]
The purpose of an old version of Firefox is that this one actually works reliably with Selenium. The new Marionette/geckodriver WebDriver implementation is really incomplete - see

* http://django-functest.readthedocs.io/en/latest/installation.html#dependencies 
* https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status
* https://bugzilla.mozilla.org/buglist.cgi?bug_status=__open__&columnlist=assigned_to,bug_status,resolution,short_desc,changeddate,keywords,status_whiteboard&component=Marionette&product=Testing
