### ISSUE TITLE
Specifying python version for language: generic is not recognized

### ISSUE THREAD

**Issue by szeck87** [travis-ci/travis-ci#9363]
We started receiving an error with pip, which can be viewed here https://travis-ci.org/szeck87/atom-beautify/jobs/355503912#L1582.  The suggestion in the error says to upgrade Python to a newer version.  I tried setting Python to 3.4 and 3.6 like this:

```
language: generic
python:
  - "3.4"
  - "3.6"
```
But it still uses 2.7.  The [docs for Python](https://docs.travis-ci.com/user/languages/python/#Using-Tox-as-the-Build-Script) say the default versions are 2.7.6 and 3.4.3, while the [build environment update](https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/) page says 2.7.14 and 3.6.3, so tried both.

Is it not possible to switch to 3.x when having `language: generic`?

**Comment by BanzaiMan** [comment]
`python` is effective only for `language: python` builds, since it relies on `virtualenv` to manage Python runtimes. On `language: generic`, you are responsible for managing all language runtimes.
