### ISSUE TITLE
Upgrade to Maven 3.5.3

### ISSUE THREAD

**Issue by vincent-zurczak** [travis-ci/travis-ci#9366]
Hi,

Currently, Travis CI uses Maven 3.5.2.
This version has a bug related to class loading. The [associated JIRA issue](https://issues.apache.org/jira/browse/MNG-6298) was resolved and closed in Maven 3.5.3, which was released two weeks ago.

Would it be possible to upgrade to this new version?

**Comment by vincent-zurczak** [comment]
Hi,

Any news?

**Comment by vincent-zurczak** [comment]
Hi again,

Any progress about this?
There is even a version 3.5.4 now...

**Comment by agebhar1** [comment]
This issue is a duplicate to #7719.

**Comment by chrisparton1991** [comment]
I had this issue as well, but I found that [Travis supports `mvnw`](https://docs.travis-ci.com/user/languages/java/#maven-dependency-management). I used the Takari Maven wrapper plugin to generate a `mvnw` file in my repo and it worked fine.

The only other thing I had to do was make the new files executable and commit those changes:
```git update-index --chmod=+x mvnw && git update-index --chmod=+x mvnw.cmd```

After that, Maven 3.5.4 is working like a charm.

**Comment by chabala** [comment]
That `mvnw` tool is really a crutch though for folks that can't control their build environment. [Your commit](https://github.com/chrisparton1991/sparkled/commit/73ba34c848e8bd3c7bb09165287cd099565211cc) has added 500+ lines of script that's unrelated to your project into version control, when you really just wanted to specify an updated version of maven.

**Comment by chrisparton1991** [comment]
@chabala it would definitely be better if Travis had the latest Maven version and I don't mean to say that mvnw is the ultimate solution, it's merely an option for people to consider of they're stuck.

The Gradle folks use an equivalent gradlew/gradlew file. I agree that the files are a bit ugly, but they have one benefit: anyone who builds using mvnw/gradlew will automatically get the exact same version of maven/gradle.

Hopefully Travis will update Maven soon though!

**Comment by DrTorte** [comment]
Hello,

I'm going to be taking a look into this internally and seeing where we stand on this. :)

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by cotsog** [comment]
Sorry if this is coming late but you can install Maven "manually" in your builds with a snippet like this in your .travis.yml file:

```
before_install:
  - wget http://apache.mirror.gtcomm.net/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
  - tar xzvf apache-maven-3.6.0-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.0/bin:$PATH
  - mvn -v
```

This will install Maven 3.6.0. See sample build: https://travis-ci.org/cotsog/travis_ci_prod_regular/builds/481500766#L547.

Hope this helps!

**Comment by chabala** [comment]
You sure can @cotsog, but that effort is repeated for every build. It would be better to get Travis to support their infrastructure instead.
