### ISSUE TITLE
Add Java Oracle JDK 10

### ISSUE THREAD

**Issue by sormuras** [travis-ci/travis-ci#9368]
Oracle JDK 10 is not supported yet using `jdk: oraclejdk10` in `.travis.yml`

OpenJDK 10 is installable from http://jdk.java.net/10/ ( using [install-jdk.sh](https://sormuras.github.io/blog/2018-03-20-jdk-matrix.html) )

https://travis-ci.org/sormuras/sormuras.github.io/builds/355946365

**PR**: https://github.com/travis-ci/travis-build/pull/1347

**Comment by javadev** [comment]
+

**Comment by sormuras** [comment]
Related to #8751

**Comment by BanzaiMan** [comment]
No Java 10 package is available yet. https://launchpad.net/~webupd8team/+archive/ubuntu/java

**Comment by pivovarit** [comment]
If you're looking for a working solution, I managed to get it to work using just a few lines of code:
https://github.com/pivovarit/articles/commit/62dcbe70057c79428776feacb4b3b2118ffaab74

**Comment by szpak** [comment]
@pivovarit I hit the problem with:

```
ValidatorException: PKIX path building failed:
sun.security.provider.certpath.SunCertPathBuilderException:
unable to find valid certification path to requested target
```

on artifacts upload to Maven Central while using just "unzipped" the OpenJDK package. It might be needed to also [link](https://github.com/szpak/mockito-java8/commit/f5faa3a6bc7de50d29faffbeee1e7464cab1bf97#diff-903c75152ea94ff6bd94eb9e668b3436R119) the system CA certificated.

**Comment by sormuras** [comment]
Merged your [`-C` feature](https://github.com/sormuras/bach/pull/12) into `install-jdk.sh` @szpak -- works like a charm on Travis CI

**Comment by BanzaiMan** [comment]
Hi, everyone. If anyone is interested in testing with these newer JDK versions, please activate your repository on https://staging.travis-ci.org and report the results, please. I don't have any personally, and I can only test with `java -version` and `javac -version`, which is far less than ideal.

Thanks.

**Comment by sormuras** [comment]
`"Sorry, but JDK 'oraclejdk10' is not known."` https://staging.travis-ci.org/sormuras/sormuras.github.io/jobs/715805

What's the name of the JDK at staging?

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/commit/35435f60cd7dc2d034c914933067dfaaa8313add#diff-c3e62bf39421d7631effc5618ca5b5c0R67

@sormuras 

```
'openjdk9'   
'openjdk10'  
'oraclejdk11'
'openjdk11'  
```

`oraclejdk10` is not on this list because https://sormuras.github.io/blog/2018-03-20-jdk-matrix.html indicates to me that `install-jdk.sh` cannot handle it.

**Comment by sormuras** [comment]
...but just because Travis does not support it. `-F 10 -L BCL` works fine with `install-jdk.sh`.

(...)

Erm, ... wow! Your're integrating  `install-jdk.sh` into Travis CI? 😎

**Comment by BanzaiMan** [comment]
@sormuras Awesome! I've added OracleJDK 10 support with https://github.com/travis-ci/travis-build/pull/1347/commits/aaf732fb07ae9c2a79d4807023f09b8c10b24779.

Yes, incorporating `install-jdk.sh` seems like a good idea, since `jdk_switcher` is unable to keep up at the moment.

Whether or not it is incorporated into future build images remains uncertain.

**Comment by BanzaiMan** [comment]
OracleJDK 10 support has been deployed to staging, by the way.

**Comment by sormuras** [comment]
> ...but just because Travis does not support it. -F 10 -L BCL works fine with install-jdk.sh.

I was mistaken. Dooh! The Oracle JDK is **no* longer available from _java.net_ since GA. This is the official source of it: http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html

How did you add support for JDK 9 when it was released?

**Comment by rleigh-codelibre** [comment]
```
$ source ./install-jdk.sh -F 10 -L BCL
--2018-04-02 15:50:07--  https://download.java.net/java/GA/jdk10/10/binaries/jdk-10_linux-x64_bin.tar.gz
Resolving download.java.net (download.java.net)... 23.1.135.18
Connecting to download.java.net (download.java.net)|23.1.135.18|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-04-02 15:50:11 ERROR 404: Not Found.
```

**Comment by sormuras** [comment]
Well, I spoke to early. Will fix it in `install-jdk.sh` ... soon _TM_

**Comment by BanzaiMan** [comment]
Please try again. https://staging.travis-ci.org/sormuras/sormuras.github.io/builds/715849?utm_source=github_status&utm_medium=notification

**Comment by sormuras** [comment]
Okay. The logs showing an outdated version of `install-jdk.sh` (should echo the version somewhere). Do you load it "on-the-fly" or do you need to update it manually?

Locally, it works now. :)

**Comment by sormuras** [comment]
Let's see how it works out: https://staging.travis-ci.org/sormuras/sormuras.github.io/builds/715866

`.travis.yml`
```
sudo: false
dist: trusty
language: java

matrix:
  include:
# 8
    - jdk: oraclejdk8
    - jdk: openjdk8
# 9
    - jdk: oraclejdk9
    - jdk: openjdk9
# 10
    - jdk: oraclejdk10
    - jdk: openjdk10
# 11
    - jdk: oraclejdk11
    - jdk: openjdk11

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version
```

**Comment by sormuras** [comment]
I guess, after you update the staging environment via `file_update_install_jdk_sh` ... it should work by restarting https://staging.travis-ci.org/sormuras/sormuras.github.io/jobs/715871

**Comment by sormuras** [comment]
@BanzaiMan Oracle JDK 9 and 10 are now supported by `install-jdk.sh`. Can you please update the staging environment?

**Comment by ScalaWilliam** [comment]
Waiting keenly :-)

**Comment by BanzaiMan** [comment]
@sormuras updated.

**Comment by sormuras** [comment]
✔️ https://staging.travis-ci.org/sormuras/sormuras.github.io/jobs/715956

**Comment by mmoayyed** [comment]
@BanzaiMan following the conversation above, it wasn't quite clear whether support for JDK 10 and beyond is now available on https://travis-ci.org. Is that the case, or is support for JDK 10, etc only available on https://staging.travis-ci.org for now?

**Comment by sormuras** [comment]
At the moment, it only works on "staging".

According to this https://github.com/travis-ci/travis-build/pull/1347 PR it might work the default ci enviroment, too, methinks...

**Comment by rleigh-codelibre** [comment]
Works for me: https://staging.travis-ci.org/rleigh-codelibre/ome-common-java/builds/716074 however openjdk10 is failing; might have hit a bug in it.  But I can't view the logs, so can't verify what happened there.

**Comment by sormuras** [comment]
> [...] however openjdk10 is failing; might have hit a bug in it. [...]

Does your build refer snapshot artifacts or some other dependencies that reside on a repository using `https`? Sonatype maybe? Then you hit https://bugs.openjdk.java.net/browse/JDK-8196141 ... which will be resolved in JDK-11, soon. 

`install-jdk.sh` offers a `-C` switch that copies/symlinks the certifactes. If you want to test that, try:

```yml
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
matrix:
  include:
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL -C
```

**Comment by rleigh-codelibre** [comment]
@sormuras Yes, I can reproduce locally.  I'll have to see if that's a regression in openjdk or a bug in our code.

**Comment by doom369** [comment]
FYI. There are available packages already:

```
sudo add-apt-repository ppa:linuxuprising/java
sudo apt-get update
sudo apt-get install oracle-java10-installer
```

**Comment by Andrei-Pozolotin** [comment]
+1

**Comment by Vinetos** [comment]
Can we use the JDK 10 in travis ? Or it stills in development ?

**Comment by chronodm** [comment]
@Vinetos I don't think either openjdk10 or oraclejdk10 works right now.

**Comment by doom369** [comment]
openjdk10 works fine

**Comment by tofi86** [comment]
> openjdk10 works fine

Nope! Not in production: https://travis-ci.org/IDPF/epubcheck/builds/375092528

Neither `openjdk10` nor `oraclejdk10` works:
https://github.com/IDPF/epubcheck/pull/843/files

**Comment by doom369** [comment]
https://travis-ci.org/blynkkk/blynk-server/builds/372442541#L493

**Comment by tofi86** [comment]
@doom369 yeah, well, you've implemented the workaround with `bach`: https://github.com/blynkkk/blynk-server/blob/master/.travis.yml#L4-L9

But I think most of the people are waiting for the final solution to use the travis config like before:

```
language: java
jdk:
  - openjdk10
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
```

**Comment by lujop** [comment]
Is this working by now?
Because I got a `Sorry, but JDK 'oraclejdk10' is not known.`
https://staging.travis-ci.org/lujop/smasolarlib/jobs/722171

**Comment by sormuras** [comment]
`install-jdk.sh` 2018-05-29 includes a bug fix when using the `--target` option on Mac OS X.

**Comment by gavinkflam** [comment]
Thanks Daniel for reporting here!

Just referencing the related builds here.

https://travis-ci.org/gavinkflam/tabula-api/jobs/388662713
https://travis-ci.org/xeqi/kerodon/jobs/388975085

**Comment by gavinkflam** [comment]
Just tested with OpenJDK 9.0.4 u11 and Leiningen 2.8.1 on ArchLinux Docker image.
Everything is OK.
This should be Ubuntu Trusty / Travis specific issues.

**Comment by javadev** [comment]
+

**Comment by sormuras** [comment]
> Users just configuring `jdk:openjdkX` on Travis CI will be surprised if their local `openjdkX` installation behaves differently.

Or in other words: Travis CI should always provide a pristine (unpatched) JDK installation.

If you need some patches applied to a JDK installation, you still may use `install-jdk.sh` with any options passed you need.

**Comment by gavinkflam** [comment]
Thanks @sormuras!

Here is an minimal Travis CI configurations for people reading this in the future.
It involved manually symlinking the system CA certs in the before_install stage.

```
language: clojure
lein: 2.8.1

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

matrix:
  include:
    - jdk: openjdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
```

Alternatively, you can do the JDK installation with a custom matrix as well.

**Comment by danielcompton** [comment]
@gavinkflam I've written this fix up at https://www.deps.co/guides/travis-ci-latest-java/ with a bit more info about the feature.

**Comment by FibreFoX** [comment]
It seems JDK10 is working now, does this mean this issue is fixed? What is missing?

**Comment by tofi86** [comment]
> It seems JDK10 is working now

I can confirm it works without any tweaks:
* https://github.com/IDPF/epubcheck/pull/843/files
* https://travis-ci.org/IDPF/epubcheck/builds/375092528

**Comment by rleigh-codelibre** [comment]
It does work, but I've had a small number of failures of the java download script.  Any reason JDK10 is not part of the base image?

**Comment by sormuras** [comment]
@rleigh-codelibre Travis CI team is thinking about doing this: https://github.com/travis-ci/travis-build/pull/1347#issuecomment-392887224

Closing this issue as Oracle JDK 10 ( and many others: https://travis-ci.org/sormuras/sormuras.github.io ) is now supported.

**Comment by filiphr** [comment]
Not sure if it is related to this issue, but I am seeing 

```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

when trying to pull SNAPSHOT dependencies from sonatype-snapshots. It works on 11 and ea. [Here](https://travis-ci.org/filiphr/mapstruct-examples/builds/403935362) is the entire build. When pulling from central it works ok see [this](https://travis-ci.org/filiphr/mapstruct-examples/builds/403934271) build.

Haven't tried https://github.com/travis-ci/travis-ci/issues/9368#issuecomment-395470644 yet.

**Comment by sormuras** [comment]
> Haven't tried #9368 (comment) yet.

_"manually symlinking the system CA certs"_ is needed for some https connections on **open**jdk10. Or switch to **oracle**jdk10.

See for example https://bugs.openjdk.java.net/browse/JDK-8196141 and related/linked issues.

**Comment by micheljung** [comment]
Still (no longer?) doesn't work for me; #9895
