### ISSUE TITLE
Done. Your build exited with 1

### ISSUE THREAD

**Issue by Nelson-numerical-software** [travis-ci/travis-ci#9369]
Travis CI report that build fails but it seems to be OK 

"make tests_all " is the last command and returns "make tests_all" exited with 0.
but Travis returns: "Done. Your build exited with 1"

How to find the problem ?

see https://api.travis-ci.org/v3/job/356002083/log.txt
https://travis-ci.org/Nelson-numerical-software/nelson/jobs/356002083

Log:
````
[100%] Built target tests_all

travis_time:end:0281c890:start=1521573125369578186,finish=1521573321146813787,duration=195777235601
[0K
[32;1mThe command "make tests_all" exited with 0.[0m
travis_fold:start:cache.2
[0Kstore build cache
travis_time:start:0c290034
[0K
travis_time:end:0c290034:start=1521573321157746684,finish=1521573321165957731,duration=8211047
[0Ktravis_time:start:00634b6f
[0K[32;1mnothing changed, not updating cache[0m

travis_time:end:00634b6f:start=1521573321176509156,finish=1521573322433173662,duration=1256664506
[0Ktravis_fold:end:cache.2
[0K
Done. Your build exited with 1.
````

**Comment by BanzaiMan** [comment]
`make buildhelp` failed. https://travis-ci.org/Nelson-numerical-software/nelson/jobs/356002083#L5352

**Comment by Nelson-numerical-software** [comment]
Oups !!! sorry 
Thanks for your quick help
