### ISSUE TITLE
SIGILL illegal instruction on xcode9.3beta image

### ISSUE THREAD

**Issue by sleweke** [travis-ci/travis-ci#9372]
Hi,

I'm a developer of the CADET simulator ([github.com/modsim/CADET](https://github.com/modsim/CADET)) and we're using Travis for CI on Linux and OS X.

After having added some unit tests recently, I'm getting
```
SIGILL - Illegal instruction signal
/Users/travis/.travis/job_stages: line 57: 11687 Illegal instruction: 4  test/testRunner -d yes --tbbthreads ${NTHREADS}
```
on the `xcode9.3beta` image when running the unit tests. The `xcode9.1` image works fine and all Linux builds that use Clang are good, too. See [https://travis-ci.org/modsim/CADET/jobs/356620532](https://travis-ci.org/modsim/CADET/jobs/356620532).

Some dependencies have been upgraded since the last successful build. However, they are not used by the test runner binary. The test code that raises SIGILL does not even invoke any of the dependencies. The problem occurs when compiling in both release and debug mode.

What can I do to resolve this issue? Is this an issue with the underlying VM host not being capable of executing all instructions supported by OSX 10.13 and emitted by this Clang version?

**Comment by BanzaiMan** [comment]
I would suggest disabling/removing cache first.

**Comment by BanzaiMan** [comment]
Thanks for testing. I don't know enough about your code to make further suggestions. We'd be happy to enable the debug feature, if you'd like to investigate it interactively. https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by sleweke** [comment]
That would be great, thanks!
