### ISSUE TITLE
Webhook: What does "errored" state mean?

### ISSUE THREAD

**Issue by bluzi** [travis-ci/travis-ci#9376]
Hey,

I'm using a webhook to tell when CI builds fail, and sometimes I'm getting `"sate": "errored"` in the payload. What does it mean?

Thanks

**Comment by BanzaiMan** [comment]
It means something besides the tests in `script` (e.g., dependency installation) failed.

**Comment by bluzi** [comment]
Thanks @BanzaiMan, that was super helpful.
