### ISSUE TITLE
xcode 10 / 10.13: kernel extension user consent

### ISSUE THREAD

**Issue by commitay** [travis-ci/travis-ci#9377]
macOS 10.13 introduced a new feature that requires user consent (via GUI) before loading kernel extensions.

https://developer.apple.com/library/content/technotes/tn2459/_index.html

As it isn't possible to approve kext loading via GUI, would it be possible for the image to be changed to allow the kernel extension to be loaded without user consent?

```
Kernel Extension User Consent Usage:
    spctl kext-consent <action>         ** Modifications only available in Recovery OS **
        status
            Print whether kernel extension user consent is enabled or disabled.
        enable
            Enable requiring user consent for kernel extensions.
        disable
            Disable requiring user consent for kernel extensions.
        add <team-id>
            Insert a new Team Identifier into the list allowed to load kernel extensions without user consent.
        list
            Print the list of Team Identifiers allowed to load without user consent.
        remove <team-id>
            Remove a Team Identifier from the list allowed to load kernel extensions without user consent.
```
Disabling `kext-consent` still requires that the kernel extension be properly signed for it to be loaded.

**Comment by ilovezfs** [comment]
Yes, disabling the kext-consent feature is the right thing to do for the Travis CI images since user interaction in the GUI is not possible during CI, but properly signed kexts should still be testable in CI.

**Comment by ilovezfs** [comment]
@BanzaiMan any thoughts here? The status quo has left https://github.com/caskroom/homebrew-cask with no way to test valid kexts in CI on macOS 10.13. See https://github.com/caskroom/homebrew-cask/pull/44751

**Comment by ilovezfs** [comment]
@BanzaiMan gentle ping on this.

**Comment by DrTorte** [comment]
Hello,

As we're no longer supporting GitHub issues but this issue remains open, I'm creating a copy of this on the forum. [Please see this link](https://travis-ci.community/t/issue-xcode-10-10-13-kernel-extension-user-consent/1287).

Thanks and happy building!
