### ISSUE TITLE
Travis Ci unable to download Oracle Java 8

### ISSUE THREAD

**Issue by davidten** [travis-ci/travis-ci#9379]
This might be similar to #7778

[https://travis-ci.org/CS2103JAN2018-F11-B1/main/jobs/357703563](https://travis-ci.org/CS2103JAN2018-F11-B1/main/jobs/357703563)

The log ultimately ends in:
download failed
Oracle JDK 8 is NOT installed.

Refreshing the build does not solve the issue.

**Comment by BanzaiMan** [comment]
As with #7778, it appears that Oracle yanked the file the `apt` package we rely on. There is unfortunately very little we can do, except wait for Oracle to resolve the issue. Unless you need the updated version, we suggest bypassing that step until this issue is resolved.

**Comment by BanzaiMan** [comment]
Looks like the file is back. https://travis-ci.org/BanzaiMan/travis_production_test/builds/357944820#L561 (Installs 8b161 now).

**Comment by jinhyukchang** [comment]
I am still experiencing the problem.
https://travis-ci.org/apache/incubator-airflow/jobs/361250290

Is there any work around?

**Comment by BanzaiMan** [comment]
@jinhyukchang That's a different issue.

**Comment by lpgauth** [comment]
Any workarounds?

**Comment by rubenvp8510** [comment]
I'm facing this issue now, Is there a workaround?

**Comment by BanzaiMan** [comment]
@lpgauth 
@rubenvp8510 See https://travis-ci.org/hawkular/hawkular-metrics/builds/461404042#L484-L498http://download.oracle.com/errors/download-fail-1505220.html

The APT package is trying to install curl https://edelivery.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz but this now redirects to http://download.oracle.com/errors/download-fail-1505220.html, which clearly indicates an error. Seems like Oracle changed the URL our APT package (https://launchpad.net/~webupd8team/+archive/ubuntu/java) relies on, and your build fails as a result. Precise may still have Java 8 pre-installed, but that is clearly not in your best interest to rely on that. If you can, I encourage you to use newer JDKs.
