### ISSUE TITLE
Chromium/Chrome does not work in an OpenVZ container

### ISSUE THREAD

**Issue by gildegoma** [travis-ci/travis-ci#938]
Problem initially reported in https://groups.google.com/forum/m/?fromgroups#!topic/travis-ci/YG9j5wN4YeE

See attempts to install chrome browser and test driver on the fly here: https://travis-ci.org/freedomsponsors/www.freedomsponsors.org/builds

As pointed out below, this a well-known integration problem: Chrome cannot be executed in a OpenVZ container/guest, because of suid binaries. Details there:
- http://code.google.com/p/chromium/issues/detail?id=31077 (old/historical bug report)
- https://code.google.com/p/chromium/issues/detail?id=138505 (more recent bug report for ubuntu 12.04)

//cc @tonylampada

**Comment by lookfirst** [comment]
Please re-open this issue. I spent the better part of today trying to figure out how to get my Angular Protractor tests running on Travis and totally bumped into the fact that Chrome can't be launched. I tried all of the suggestions I could find here and nothing worked right. Either Chrome crashed or just would launch. I'm happy to work with someone at Travis who is more knowledgable than I to come up with a way to get this working.

**Comment by joshk** [comment]
Hi @lookfirst

Could you open a new issue and we can dive into this problem once more with fresh eyes.

Were you having issues on .org or .com?

Thanks,

Josh

**Comment by lookfirst** [comment]
Sorry for the previous comment...

After an insane amount of hours wasted today... I finally got this working with Angular Protractor. As everyone has suggested, the no-sandbox argument is the key. It was difficult to figure out how to pass that into Protractor since there isn't any examples that I could find (note the protractor.conf.js near the bottom). :cry: 

Hopefully the bits and pieces of my config below will help someone.

./.travis.chrome.sh

```
#!/bin/bash

# Holy shit batman!
# https://github.com/travis-ci/travis-ci/issues/938
# https://github.com/travis-ci/travis-ci/issues/2555

sudo apt-get install -y python-software-properties
sudo apt-add-repository "deb http://dl.google.com/linux/chrome/deb/ stable main"
sudo sed -i s/deb-src.*google.*//g /etc/apt/sources.list
wget -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo apt-get update -qq
sudo apt-get install -y google-chrome-stable

sudo chmod 1777 /dev/shm
```

.travis.yml

```
language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
branches:
  only:
  - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./.travis.chrome.sh
- npm install jspm
- jspm config endpoints.github.auth $GH_TOKEN
install:
- npm install
script:
- gulp run &
- npm run-script protractor-setup
- sleep 10
- npm run-script protractor-run
```

package.json:

```
  "scripts": {
    "protractor-setup": "./node_modules/.bin/webdriver-manager update --standalone",
    "protractor-run": "gulp es6-e2e && ./node_modules/.bin/protractor protractor.conf.js"
  }
```

protractor.conf.js

```
	capabilities: {
		'browserName': 'chrome',
		'chromeOptions': {
			'args': ['no-sandbox']
		}
	},
```

**Comment by lookfirst** [comment]
So, now my request is for the admins of Travis to install Chrome in the default image so that I don't have to run that `.travis.chrome.sh` script. =) It would also be helpful if `xvfb` was started and the environment variable was already set. That would make things a lot more plug and play.

**Comment by joshk** [comment]
Hi @lookfirst 

Can you please open a separate issue for this.

`DISPLAY` is already exported on the VM image. Also, I believe Chrome is also installed.

Can you try adding `sudo: true` to your .travis.yml and seeing if the `protractor-setup` script is still needed?

Thanks

**Comment by lookfirst** [comment]
@joshk 

I'd like to understand your suggestions before I make fixes and break things. :wink: So I have a couple questions:

1. Do I still need to start `xvfb`?
1. What is `DISPLAY` exported as?
1. What effect does `sudo: true` have? I don't see it anywhere in your docs.
1. Why would `sudo: true` negate the need to run `protractor-setup`? 

thanks.

**Comment by joshk** [comment]
You will still need to start `xvfb` as we do not start this by default.
I believe `:99.0` is the exported `DISPLAY` value, you can check this by adding `env` in a `before_install step`
Sorry, I meant to say `sudo: false`. This will send the job to our new build environment which is based on LXC and runs on EC2. Our current legacy setup uses OpenVZ, which is part of the problem with Chrome.

**Comment by lookfirst** [comment]
Ok, without installing chrome, `no-sandbox` and DISPLAY commented out, chrome still crashes on the new arch:

https://travis-ci.org/lookfirst/systemjs-seed/jobs/53600350

uncommented no-sandbox and i get this:

https://travis-ci.org/lookfirst/systemjs-seed/jobs/53600788

and uncommenting `DISPLAY`, i get this:

https://travis-ci.org/lookfirst/systemjs-seed/jobs/53601000

Note that I added `env` before I set `DISPLAY` by hand:

https://travis-ci.org/lookfirst/systemjs-seed/jobs/53601000#L99

So, I guess we are back to square one, but with a faster server now. :+1:

**Comment by lookfirst** [comment]
So now that I can't sudo, how do I install stuff with apt?

**Comment by lookfirst** [comment]
@joshk Any more thoughts?

**Comment by joshk** [comment]
Not sure right now sorry, Can you please open a new ticket with the information you posted above summerizing the issue and I can escalated this within the team.

Thanks :)

**Comment by lookfirst** [comment]
Due to the recent change over to docker by default and the fact that it has an ancient version of chrome, this is what I'm using now...

```
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
```

**Comment by andy11** [comment]
Thanks @lookfirst -- google-chrome (launched via python/selenium/chromedriver) is working for me with your bash script, sudo: required, and the --no-sandbox flag activated.

**Comment by lookfirst** [comment]
@andy11 I found that installing chrome via apt takes an inordinate amount of time because of all the dependencies. The comment above where I just download the .zip file and use that binary works much better.

**Comment by dtracers** [comment]
I am installing chrome driver via grunt and as of this build it had errors with the chrome driver:

https://travis-ci.org/dtracers/coursesketch/builds/120990028
I have not tried any of the scripts yet but I did not know if anything has changed in the past year that is worth noting.

**Comment by fulls1z3** [comment]
Hope it helps:

```
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"
cache:
  directories: node_modules
branches:
  only: master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3
```

**Comment by jugglinmike** [comment]
This appears to no longer be an issue for the "Trusty Tahr" (e.g. 14.04) release of Ubuntu and onward. If you are able to [upgrade to that release in your `.travis.yml` file](https://docs.travis-ci.com/user/trusty-ci-environment/), then you should be able to run Google Chrome without disabling the sandbox.

(I just spoke with some folks on the Chromium team in the #chromium IRC channel on Freenode. Chrome only uses a "setuid sandbox" as a fallback when the kernel does not support more advanced features. It seems likely that Ubuntu 14.04 has the namespace features that allow it to use other technologies--ones that are compatible with the environment provided by TravisCI.)
