### ISSUE TITLE
PHP SNMP extension

### ISSUE THREAD

**Issue by simPod** [travis-ci/travis-ci#9381]
How to install php snmp extension on Travis?

When following [documentation](https://docs.travis-ci.com/user/languages/php#Enabling-preinstalled-PHP-extensions) `before_install: echo "extension = snmp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini` doesn't seem to work.

**Comment by BanzaiMan** [comment]
It means it’s not pre-installed. Try https://docs.travis-ci.com/user/languages/php#Installing-additional-PHP-extensions instead.

**Comment by simPod** [comment]
So if SNMP extesnion is not available via PECL I can't use it without setting my own enviroment from scratch?

**Comment by simPod** [comment]
🤔

**Comment by netniV** [comment]
@howardjones looks like you're not the only one who wonders the answer to this question.

**Comment by howardjones** [comment]
Indeed - I'm also running into this issue. It's really not clear from the docs what "pre-installed" actually means. In a standard PHP installation, snmp.so would exist but be disabled. So it can't be installed by pecl, and in the Travis trusty environment, it seems that it can't just be added to the php.ini either (like gd can, for example).

**Comment by DrTorte** [comment]
Hello,

As we're no longer supporting GitHub issues but this issue remains open, I'm creating a copy of this on the forum. [Please see this link](https://travis-ci.community/t/issue-php-snmp-extension/1286).

Thanks and happy building!
