### ISSUE TITLE
Ruby: bundler: failed to load command: rake when `*.lock` file is present

### ISSUE THREAD

**Issue by swrobel** [travis-ci/travis-ci#9383]
Seems similar to https://github.com/travis-ci/travis-ci/issues/8978 but there don't seem to be any updates to bundler or rubygems available at this point.

Example: https://travis-ci.org/ClosureTree/closure_tree/jobs/357891804#L591

**Comment by BanzaiMan** [comment]
Why is this job trying to load jdbc adapter? https://travis-ci.org/ClosureTree/closure_tree/jobs/357891804#L591

**Comment by swrobel** [comment]
I believe the gem author was trying to ensure compatibility with jruby at one point. That doesn't seem relevant to this issue... it doesn't affect the builds for other ruby versions

**Comment by BanzaiMan** [comment]
Hmm. I can't reproduce it. This works: https://travis-ci.org/BanzaiMan/travis_production_test/builds/357957311#L479

**Comment by BanzaiMan** [comment]
I don't mean to dismiss your error; I just mean that there is something else at play. Perhaps `gemfile` is coming into play somehow.

**Comment by swrobel** [comment]
Ok, thanks for investigating. It's not a big deal, I'll just leave the
issue in case anyone else has this same problem.

**Comment by BanzaiMan** [comment]
Looks like the presence of `*.lock` is a problem. https://travis-ci.org/BanzaiMan/travis_production_test/builds/358129740#L473 https://travis-ci.org/BanzaiMan/travis_production_test/builds/358132231#L82

**Comment by woodruffw** [comment]
I think I'm having the same problem, but with Ruby 2.5: https://travis-ci.org/kbsecret/kbsecret/jobs/359693022#L653

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-ci/issues/9333#issuecomment-373042916 suggests reinstalling Bundler would fix it, but I am not sure why yet (because it is not necessary on older Ruby run times).

**Comment by woodruffw** [comment]
Thanks; I'll give that a shot.

**Comment by TheAssailant** [comment]
I appear to be having the same issue, but with Ruby 2.5.1 and 2.4.4. All other versions from 2.3.0 to latest are fine though. I can restart the jobs but the same issue happens.

Here's my failing build: https://travis-ci.org/TheAssailant/aesthetify/builds/360281187

Following the advice of https://github.com/travis-ci/travis-ci/issues/9333#issuecomment-373042916 adding a gem install bundler fixed the issue in this build: https://travis-ci.org/TheAssailant/aesthetify/builds/360288052

Hopefully this will be helpful in getting this fixed.

**Comment by SuperSandro2000** [comment]
Just want to drop that here for other people experiencing this issue:
````
before_install:
  - gem install bundler
````

**Comment by BanzaiMan** [comment]
I'm locking this issue for now, to prevent references from commits to appear here.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
