### ISSUE TITLE
Travis-ci.org: bandwidth/data limits ?

### ISSUE THREAD

**Issue by taqtiqa-mark** [travis-ci/travis-ci#9384]
Hi,
Thanks for the effort that has gone into making travis-ci available, particularly for opensource projects.

I'm aware of the timing constraints in travis-ci.org.  **Are there comparable data/internet/bandwidth limits?**

In the course of trying to build the [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks) as rkt containers.
I repeatedly encounter the 10-minute timeout during the download phase of the larger containers.

In [this example](https://travis-ci.org/taqtiqa-admin/rkt-stacks/builds/358023719), jobs 1-3 (final artifact < 4GB) always succeed, jobs 4-7 (final artifact >4GB) always fail.

**Based on the reproducible data I have at hand:**
For jobs up/downloading data required to produce a ACI image <4GB, all works fine. For a jobs that up/download data required to produce a ACI image >4GB, the jobs fail. But a large job will succed if run >24hrs later.

I'm at a loss as to the source of the error, so am going through the process of elimination:
I would like to eliminate formal rules at the level of travis-ci.

I'd appreciate in educated guesses about the next most likely culprit.

**Comment by taqtiqa-mark** [comment]
Hmm, it does appear there might some types of limits operating at the build level.  
When I try to rerun one of the jobs >24hrs later it succeeds. But the next job fails when trying to download gpg keys.  This code, being part of the same build has not changed.

Anyway, the details are murky, but I think there is enough information to conclude the issue is not outside travis-ci.

Can someone inside travis-ci disclose explicitly what these limits are?
At the moment it would appear that to build larger projects, such as the jupyter project, on Travis-CI one would have to split the project into multiple projects. Then build them.  

Not ideal, and I'm still hoping there might be another explanation, or Travis-CI could lift its limits untill it has a [local Docker registry mirror](https://docs.docker.com/registry/recipes/mirror/#use-case), but I do also know even this temporary change this is likely expensive.

**Does Travis-CI already have a Docker registry mirror configured as a "pull through cache"?**

Appreciate thoughts/feedback

**Comment by BanzaiMan** [comment]
This looks like a variation of https://github.com/travis-ci/travis-ci/issues/9127.

**Comment by taqtiqa-mark** [comment]
Does that mean the answer to this question is "Travis-CI.org has no (undocumented?) bandwidth limits." ?
If so then I'll close this issue.  It seems I *might* be experiencing the docker pull issue #9127 or [docker/hub-feedback/Issue #1233](https://github.com/docker/hub-feedback/issues/1233), but I'm not there yet :)  
Before I can move to that step I need to know there are no Travis-CI limits since all my small (<4GB) docker builds reliably succeeded, but the large (>4GB) docker pulls reliably fail. 

As I observed from my data: It does not appear to be an issue outside Travis-CI.  PGP key pulls are fine from my desktop machine.  In my case the data/observations are consistent with some Travis-CI.org bandwidth limit has been triggered and this limit lasts approx 24 hrs.

Thanks for the prompt and helpful responses @BanzaiMan .  Much appreciated.

**Comment by BanzaiMan** [comment]
It is not entirely clear what the issue is for you, to be honest. You might want to try enabling debugging on your Docker daemon. https://success.docker.com/article/how-do-i-enable-debug-logging-of-the-docker-daemon

**Comment by taqtiqa-mark** [comment]
Thanks @BanzaiMan, I an not using a docker daemon.  I use the rkt cmdl line tool to fetch the docker image.  I don't dispute docker/hub-feedback/Issue #1233 might come into play later, but so far I can't say that.

It seems pretty clear to me so far, but that is based on the data I have at hand:  
For jobs up/downloading data required to produce a ACI image <4GB, all works fine. For a jobs that up/download data required to produce a ACI image >4GB, the jobs fail.

Is there a reason no one is answer a fairly direct question: 
**Are there Travis-CI.org data/internet/bandwidth limits?**

**Comment by taqtiqa-mark** [comment]
The first Internet access results in this:
````
+ gpg --no-tty --no-default-keyring --trust-model always --homedir /tmp/5our --keyserver pgp.mit.edu --recv-key 0E604491
gpg: keyring `/tmp/5our/secring.gpg' created
gpg: keyring `/tmp/5our/pubring.gpg' created
gpg: requesting key 0E604491 from hkp server pgp.mit.edu
gpgkeys: key 0E604491 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
````

In case it helps. Worker information:
````
Worker information
hostname: 07752407-dae5-4f5a-a372-fcb56c5a5e9d@1.production-1-worker-org-f-3-gce
version: v3.6.0 https://github.com/travis-ci/worker/tree/170b2a0bb43234479fd1911ba9e4dbcc36dadfad
instance: travis-job-884554ab-ba06-49ff-8677-42c6a22f4843 travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)
startup: 29.598504423s
mode of ‘/usr/local/clang-5.0.0/bin’ changed from 0777 (rwxrwxrwx) to 0775 (rwxrwxr-x)
````
