### ISSUE TITLE
"Custom config" in manual build trigger is completely ignored.

### ISSUE THREAD

**Issue by AmokHuginnsson** [travis-ci/travis-ci#9386]
I have a repository which I want to connect to travis-ci,
this repository does not have .travis.yml file yet.

I want to develop working version of .travis.yml before I add this file
to my repository. With previous repositories I used "Custom config" feature for this.

Unfortunately it seems this feature stopped working.

Whatever config I specify in `More options->Trigger build->Custom config Enter config as YAML` it is always ignored.

Even trivial sample like:

`script: echo 'Hello World'`

is ignored.

When I check what config actually was used for any given build (via `View config`) I always get the same result:

`
{
  "language": "ruby",
  "os": "linux",
  "group": "stable",
  "dist": "trusty"
}
`

Without "Custom config" feature working development of working .travis.yml is extremely unpleasant experience.

EDIT:

[URL to the failing build](https://travis-ci.org/AmokHuginnsson/huginn/builds/358380996)

[URL to previously working build](https://travis-ci.org/AmokHuginnsson/yaal/jobs/322340004/config)

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by AmokHuginnsson** [comment]
@BanzaiMan I have added a build log URL to the original report.

**Comment by BanzaiMan** [comment]
Thanks. https://travis-ci.org/AmokHuginnsson/huginn/builds/358380996#L6 Looks like the API request requires that `.travis.yml` be present in the repository. Could you try adding it?

We can discuss whether this behavior is desirable, but it is unlikely that it would be addressed in the near future.

**Comment by AmokHuginnsson** [comment]
@BanzaiMan 

Like I said in my original report. This used to work. I mean, having .travis.yml was not a strict requirement to use "Custom config" feature. I have configured two different repositories in the past using this feature and not having .travis.yml present.

What you are saying is that I have to create fake repository on github - a copy of a repo in question then I will use this fake repo to develop working .travis.yml, then copy working .travis.yml to real repo and remove fake repo from github?

Not very convenient.

**Comment by BanzaiMan** [comment]
Do you have the build that shows this used to work? I don't think this part of the API logic has changed much recently.

**Comment by AmokHuginnsson** [comment]
@BanzaiMan I have added another URL, this time to proof that this feature worked before.

**Comment by BanzaiMan** [comment]
Thanks for the info.
