### ISSUE TITLE
Couldn't locate package mariadb-server-10.2

### ISSUE THREAD

**Issue by tristanbes** [travis-ci/travis-ci#9387]
MariaDB seems not installable via `addons` since today (or maybe few days ago).

```
language: php
dist: trusty
sudo: false

... 

addons:
    mariadb: '10.2'
```

<img width="867" alt="capture d ecran 2018-03-26 a 14 06 52" src="https://user-images.githubusercontent.com/346010/37905607-adcdd3d2-30ff-11e8-80b9-fd2afec1ad0c.png">

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by tristanbes** [comment]
it is private repository, I can discuss it here, but I doubt that giving a build URL will help others:
https://travis-ci.com/Yproximite/bwt-project/builds/69063206

**Comment by BanzaiMan** [comment]
Thanks for the information. Looks like an intermittent network error to me. Recent builds for this repositories are getting past the MariaDB installation stage. This error in particular happened 3 days ago. Could you try restarting it?

**Comment by tristanbes** [comment]
Indeed it was temporary. Thanks.
