### ISSUE TITLE
Mistakly unsubscribe from emails notification and cannot get them back

### ISSUE THREAD

**Issue by meijin007** [travis-ci/travis-ci#9390]
I unsubscribe from email notification by pressing the link in the email. Is it possible to get them back?
adding notification with the specific email in travis.yml didn't change it.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Hi!

We currently don't have an UI option for this. Please reach out to support@travis-ci.com and let us know which e-mail you want to have re-subscribed.

Thanks!

**Comment by junghans** [comment]
Yeah, that is a bit annoying especially if you send the build notification to a public mailing list, where everybody could click the unsubscribe button.

/cc @iriberri 
ref votca/votca#53

**Comment by BanzaiMan** [comment]
@junghans Thanks for the feedback. We are working on improving the user experience here, and I’ll send it back to the design team.

**Comment by meijin007** [comment]
This is still an issue, and shouldnot be closed IMHO

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
E-mail subscription preferences have been implemented, I'll go ahead and close this!

**Comment by meijin007** [comment]
Thanks :)

**Comment by junghans** [comment]
@igorwwwwwwwwwwwwwwwwwwww  is there documentation? Or where to find the new subscription preferences?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@junghans They're under Profile => Settings => Email notifications.

![screen shot 2018-10-08 at 14 18 08](https://user-images.githubusercontent.com/11158255/46608415-ff664400-cb04-11e8-8a85-a5e1cae8fff5.png)
