### ISSUE TITLE
after_success hook not executing

### ISSUE THREAD

**Issue by oleersoy** [travis-ci/travis-ci#9393]
I documented this fully in [this SO Post](https://stackoverflow.com/questions/49499976/coveralls-integration-with-travis-ci-not-working).

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by oleersoy** [comment]
This is the build log:
https://api.travis-ci.org/v3/job/358569137/log.txt

**Comment by BanzaiMan** [comment]
https://travis-ci.org/fsngx/ease/jobs/358569137 was triggered by https://github.com/fsngx/ease/commit/054f3da399f672c61f69c032bb7bf5c346017b0b, which does not have `after_success` defined anywhere in https://github.com/fsngx/ease/blob/054f3da399f672c61f69c032bb7bf5c346017b0b/.travis.yml. Please double check your configuration.

**Comment by BanzaiMan** [comment]
The latest version of `.travis.yml` https://github.com/fsngx/ease/blob/4e1e2604f1f35b6d12776177f93eb1566d20d78f/.travis.yml#L8 has incorrect indentation, and your build requests have been rejected. See https://travis-ci.org/fsngx/ease/requests

To achieve what you need, you need delete the white space before `after_success` to make the YAML file valid.

I'm closing this. I'll also add the note on your SO question.

**Comment by oleersoy** [comment]
Awesome - Travis Rocks and so do you!!!  Thanks again!!
