### ISSUE TITLE
Skip deployment using tag regular expression

### ISSUE THREAD

**Issue by alanbchristie** [travis-ci/travis-ci#9395]
OK, this should be simple but there are surprisingly few examples and everything that I've tried just does not work. It should be simple - it's just a regex after all! Basically I want to skip the deployment stage unless my `tag` (`TRAVIS_TAG`?) begins `pypi-`.

I know automatic deployment works because this _fragment_ of my deployment causes the deployment to run (on master) only when it's tagged...

```
on:
  tags: true
  branch: master
```

Brilliant!

Now I also want to avoid deployment unless the `tag` begins with `pypi-`. I've tried all sorts of combinations (although I'm not completely sure what the regex language is and am assuming bash). Sadly I'm getting no-where! Any attempt to do a regular expression (according to the documentation) results in **Skipping a deployment with the pypi provider because a custom condition was not met**.

What's the correct way to do this..?

```
on:
  tags: true
  branch: master
  condition:  $TRAVIS_TAG =~ ^pypi\-*$
```

i.e. _the tag must begin `pypi-`_

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

> `condition`: deploy when _a single_ bash condition evaluates to `true`. This must be a string value, and is equivalant to `if [[ <condition> ]]; then <deploy>; fi`. For example, `$CC = gcc`.

In your particular case,

```yaml
on:
  condition: $TRAVIS_TAG =~ ^pypi
```

should do. See http://man7.org/linux/man-pages/man1/bash.1.html#SHELL_GRAMMAR for more on what can go in the `[[ ]]` construct.

**Comment by alanbchristie** [comment]
Thanks, I'm using the following to limit deployments to `master`. `tags` is probably superfluous but I've kept it regardless. Anyway the following is indeed working, with Python deployments happening if the commit is tagged `pypi<something>`: -

```
on:
  tags: true
  branch: master
  condition: $TRAVIS_TAG =~ ^pypi
```

I'll explore bash regular expressions later.
