### ISSUE TITLE
C# Build failing when updating already

### ISSUE THREAD

**Issue by RethoughtSolutions** [travis-ci/travis-ci#9396]
@joshua-anderson @akoeplinger @nterry

C# support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry
Installing .NET Core
$ export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
$ export DOTNET_CLI_TELEMETRY_OPTOUT=1
Executing: /tmp/tmp.590xX131fu/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
BE1229CF
gpg: requesting key BE1229CF from hkp server keyserver.ubuntu.com
gpg: key BE1229CF: public key "Microsoft (Release signing) <gpgsecurity@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
3.42sW: The repository 'http://www.apache.org/dist/cassandra/debian 39x Release' does not have a Release file.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch http://dl.bintray.com/apache/cassandra/dists/39x/main/binary-amd64/Packages  502  Bad Gateway [IP: 52.27.175.225 80]
E: Failed to fetch http://dl.bintray.com/apache/cassandra/dists/39x/main/binary-i386/Packages  502  Bad Gateway [IP: 52.27.175.225 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update -qq" failed and exited with 100 during .

not quite sure if I can do anything about this myself or if it is related to some problem on your side

**Comment by akoeplinger** [comment]
Yeah this is nothing specific to C#, the unrelated http://dl.bintray.com/apache/cassandra/dists/39x/main/binary-amd64/Packages failed to download. It works from here so probably just a transient issue.

Do you still see it if you retry the build?

**Comment by RethoughtSolutions** [comment]
Ah, seems like that did the trick.

I've tried rebuilding before but got the same error, seems like it's been fixed already.

Thanks and have a great day! :)
