### ISSUE TITLE
pip install does not install dependencies

### ISSUE THREAD

**Issue by CompPhysChris** [travis-ci/travis-ci#9397]
Since approximately 9am EST today, all builds of my project have been failing during the install.  This includes old builds that had previously succeeded.  In every case, the error is because pip doesn't seem to be installing my package dependencies before trying to install the package.   Running pip install on my local machines works without any problems.

link to builds: [Python 2.7](https://travis-ci.org/pycroscopy/pycroscopy/jobs/358864750), [Python 3.6](https://travis-ci.org/pycroscopy/pycroscopy/jobs/358864759)
link to yml:     [.travis.yml on GitHub](https://github.com/pycroscopy/pycroscopy/blob/master/.travis.yml)

**Comment by BanzaiMan** [comment]
The failing command is

    pip install git+https://github.com/pycroscopy/pycroscopy.git

This also fails on my machine, so I suspect that the issue is upstream. I suggest reporting the issue to https://github.com/pycroscopy/pycroscopy.

**Comment by CompPhysChris** [comment]
You're right.  We made a change to our setup recently that was causing the problem.
