### ISSUE TITLE
Build status badge by event type

### ISSUE THREAD

**Issue by neerajprad** [travis-ci/travis-ci#9398]
We are using travis CI for our open source project, [Pyro](https://github.com/uber/pyro). We have a staged build that runs for every PR/merge, and a daily cron job that additionally does some perf testing. 

We would like our badge to only display the status of the build due to PR merges on our development branch, and not from the cron job that inherits variabilities that are inherent in perf testing. Is there any way to get the build status badge not only by branch but also by `event_type`? Any other suggestions to achieve the same outcome are welcome.

**Comment by DrTorte** [comment]
Hello,

As we're no longer supporting GitHub issues but this issue remains open, I'm creating a copy of this on the forum. [Please see this link](https://travis-ci.community/t/issue-build-status-badge-by-event-type-migrated-github-issue/1284).

Thanks and happy building!
