### ISSUE TITLE
Repo Not Updating

### ISSUE THREAD

**Issue by iThink32** [travis-ci/travis-ci#9399]
Hey I have a repo say xyz , i created a pull request and triggered a manual build , everything works fine but when I make certain changes to xyz , push it and then refresh the repo on my profile the manually trigger build still uses the same old commit. Any way to make it use the latest commit on my repo?

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!
