### ISSUE TITLE
"Not" clause not work correcly with stages in .travis

### ISSUE THREAD

**Issue by fhuertas** [travis-ci/travis-ci#9401]
I'm working with stages in travis and I want to create a stage that is not use when a tag start with something, for example v[0-9]

When I put the rule
``` if: (NOT tag ~= ^v[0-9])```

And commit the change the stage is executed by Travis server.
I have tried
    if: (NOT tag ~= ^v[0-9])
    if: (NOT (tag ~= ^v[0-9]))
    if: NOT tag ~= ^v[0-9]
    if: tag ~= ^v[0-9]
    if: tag ~= ^v[0-9]
    if: tag ~= ^v[0-9]

And I have the same result in all cases

The code of my repository is here

https://github.com/fhuertas/cassandra-sink-spark-structured-streaming/tree/sonatype/automatization

And I trying pusing a tag named v0.0.3

And example of stage: https://travis-ci.org/fhuertas/cassandra-sink-spark-structured-streaming/builds/359448981

**Comment by tooomm** [comment]
See https://github.com/travis-ci/travis-conditions/pull/1
