### ISSUE TITLE
Enhancement in web page : direct link to raw log

### ISSUE THREAD

**Issue by yanntm** [travis-ci/travis-ci#9402]
Dear travis team,

I have a bit of an issue when logs are too long to be displayed with the current workflow to access the raw log. 
Suppose I want to see why my 711.5 build failed : https://travis-ci.org/yanntm/ITS-Tools-pnmcc/builds/359443405

So first click the 711.5 link, but then the link to the raw log is  placed after the log, so that the slow to load "pretty displayer" takes ages to open. You then have to scroll, and it's slow as it's downloading as you scroll. Finally you click the link and get the raw log (re-downloading it in fact), much faster and more importantly complete (I need to look at the tail).

A simple way to improve, would be to make the link to raw log more accessible:
* add a link to the raw log in the pages that report the builds, e.g. in tables with the link to the normal "pretty" log page, add a link to raw log too. eg. in the page pointed at the start of the message. 
* the (raw) link could also go into the header describing the build, above the actual log in "pretty" mode, so i could click it quick

Thank you for your consideration for this request for enhancement.  
I've wished for that button many times on projects where the logs  are  a bit over-verbose, so I know beforehand I need to go for raw mode. Building the url by hand in the address bar is possible with buildid but impractical.

**Comment by BanzaiMan** [comment]
FYI: This link should be available on the `Raw log` button at the top of the logs text area.
![display_the_log_in_plaintext_and_build__4421_-_banzaiman_travis_production_test_-_travis_ci](https://user-images.githubusercontent.com/25666/38057260-c9ccf096-32ac-11e8-937f-1c9a4d85e703.png)

Thanks for the feedback. I'll pass it on to our design team.

**Comment by pavelkryukov** [comment]
Still an issue
