### ISSUE TITLE
npm deploy failing

### ISSUE THREAD

**Issue by toshok** [travis-ci/travis-ci#9403]
project just recently started (in the past week) failing to publish with:

```
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
~/.npmrc size: 48
npm ERR! publish Failed PUT 401
npm ERR! code E401
```

I've tried generating multiple new tokens, I've tried both copying the entire line from my .npmrc (including `//registry.npmjs.org/:_authToken=` prefix) and just using the authToken itself.  I've always had a v2+ token.

I'm also encrypting my auth token as per the instructions.

The above `~/.npmrc` size (48) is odd.  If I have that token locally in my .npmrc, the file size is 70:

```
$ wc -c .npmrc
      70 .npmrc
```

**Comment by BanzaiMan** [comment]
The most likely explanation is that your token is incorrect or incorrectly encrypted.

The size of `~/.npmrc` should not be a concern; my guess is that your local copy has some comments in it.

**Comment by toshok** [comment]
No doubt, something is wrong.  But it isn't an incorrect token or an incorrectly encrypted one:

1. The token worked previously from the command line.  My current one still works.
2. The token also worked previously from _travis builds_ in the same repo, something I thought I made clear in the initial report - it only started failing for deploys 3 days ago.

I've already tried multiple new tokens from npm, I also tried multiple formats (including the `//registry.npmjs.org/:_authToken=` vs not).  none of them worked.  Also there is never any indication as to _why_ it's failing.  only the http 401.

**Comment by toshok** [comment]
the repo flipped from private to public (more than 3 days ago, but after the most successful deploy), does the private flag have any effect on the repo's private/public key?  Would that have caused decryption to fail or produce incorrect results?

I also added an encrypted slack -> notification setting (_after_ flipping to public) which isn't working either.

**Comment by BanzaiMan** [comment]
If you change the visibility, you will have to reencrypt your key. The .org repo and the .com repo have different private keys.

**Comment by BanzaiMan** [comment]
See also: https://docs.travis-ci.com/user/travis-pro#How-can-I-make-a-private-repository-public%3F

**Comment by toshok** [comment]
Thanks for your patience here, btw :)  I've switched over to investigating via the slack notifications since working against npm deploys requires a tag on master for each attempt, and I didn't want to keep polluting history there (at least not until I've determined that things are ~working.)

I changed the endpoint for the repo using the CLI, removed integrations and re-added them - basically done as much as I could to reset things back to zero.  Then set it back up, encrypting the token again, and still no dice.  And no indication of how it's failing.  Any idea on how to debug this?

**Comment by webnator** [comment]
I'm having exactly the same issue.
Any luck?

**Comment by toshok** [comment]
nope, I've been publishing manually ever since I opened this issue :/

**Comment by webnator** [comment]
Think I'll just do that... Thanks :(

**Comment by slonoed** [comment]
Any news here? I had the same problem. It stopped working. I tried a new key with no result.

**Comment by tjschuck** [comment]
Same issue here.

**Comment by zthun** [comment]
I did some digging on this because I ran into this issue yesterday.  I had two projects, one enabled with both travis-ci.org and travis-ci.com.  One project is older and still builds on travis-ci.org, but one is also newer and does not build on travis-ci.org.  

Anyway, the npm deployment on travis-ci.com fails for both projects.  The npm deployment on travis-ci.org works for the one project that is still able to build there (has not been fully migrated yet).  I was going to disable all the projects on travis-ci.org, but that will cause issues on the deployment since .com fails to deploy.  Both of these projects were setup using 

```
travis setup npm
```

I tried multiple tokens from npm and double verified that they work so the tokens aren't the problem.  My gut feeling is that it's the encryption somehow and that the keys are encrypted with travis-ci.org instead of travis-ci.com - thus meaning that something is wrong with the travis cli.

**Comment by TheSharpieOne** [comment]
Having the same issue. I have even encrypted a fresh token after npm invalidated all of the tokens.
The output in the build has 

```bash
Authenticated with email dumbdrum@gmail.com and API key ****************Ijk=
```
The trailing `Ijk=` is the end of the encrypted value. Maybe it should be the end of the decrypted value? As it is right now, I'm not sure if it is decrypting the key or not.

**Comment by MitMaro** [comment]
I ran into a similar issue, with a similar vague error message, and eventually "fixed" the problem.

After the [compromised version of eslint-scope](https://status.npmjs.org/incidents/dn7c1fgrr7ng), I enabled 2-factor authentication. It seems tokens that are created while 2-factor is enabled will not work with TravisCI.

Once I disabled 2-factor on npmjs.org, and generated a new token, I was able to deploy again.

**Comment by BanzaiMan** [comment]
Is 2-factor auth relevant to others who have had problems with the npm deployment?

**Comment by TheSharpieOne** [comment]
@BanzaiMan I (sadly 😞) do not have 2-factor enable

**Comment by stefanbuck** [comment]
I had the same issue, because I was using `travis encrypt` to encrypt my NPM token. tThe CLI is was making requests to the travis-ci.org API, and this is why travis-ci.com was not aware of the change and was not able to decrypt the value.

Running `travis encrypt` command with the `--com` will make Travis run the request against travis-ci.com.

**Comment by MitMaro** [comment]
Follow up. I tried to publish from the CLI after enabling 2FA, and here is what happened. Note that I had to provide my 2FA token on publish.

```
$ rm ~/.npmrc
$ npm whoami
npm ERR! code ENEEDAUTH
npm ERR! need auth this command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`
$ npm login
Username: mitmaro_dev_travis_ci_2fa_test
Password: 
Email: (this IS public) dev_travis_ci_2fa_test@mitmaro.ca
Authenticator provided OTP: 55**95
Logged in as mitmaro_dev_travis_ci_2fa_test on https://registry.npmjs.org/.
$ npm whoami
mitmaro_dev_travis_ci_2fa_test
$ npm publish
npm ERR! publish Failed PUT 401
Enter OTP: 02**56
+ travis_npm_2fa_deploy@1.3.0
```

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
