### ISSUE TITLE
Webhooks not arriving to webservice

### ISSUE THREAD

**Issue by smetj** [travis-ci/travis-ci#9407]
Hi,

It seems that (at least in my case) web hooks are not arriving in the defined web service.

- I believe https://github.com/wishbone-modules/wishbone-output-twitter/blob/development/.travis.yml#L21 contains the correct configuration
- When manually executing the build (https://travis-ci.org/wishbone-modules/wishbone-output-twitter/builds/359122643) no web hooks are send which I would expect to happen

I can't see a failing incoming request on the web service on my side.
I believe the SSL cipher in use on https://events.smetj.net/travis are supported by the travis "client" but I can't confirm that entirely.

Since there is no customer insight into failing web hook requests I was wondering if there's a list available of library versions used by the code doing the web hook service request so I could try to replicate the problem locally?

**Comment by BanzaiMan** [comment]
This is a common mistake with notification configuration. Notifications are configured *before* any job is executed, so they do not have access to any of the environment variables that your jobs may define. (Consider a case with many jobs, some of which may not define the environment variables necessary for the notifications, or they may not all agree on the same values.)

We have this bit in [the documentation](https://docs.travis-ci.com/user/notifications), but perhaps we can improve it still:

> Note: These webhooks are executed at the end of a build, and not by individual jobs (see builds vs jobs). This means that environment variables from the build are not available in this section.

**Comment by smetj** [comment]
ok got it. Long story short no custom variables available in the notifications section.

So I figured to use encrypted values instead which works.

However, ... it seems that an URI including basic authentication information isn't supported ??

`https://username:password@events.smetj.net/travis`

If I omit the `username:password@` part I can see the request coming in on my end. When I leave the username and password the request never reaches the api on my end.

So it seems to me that there's a bug on the Travis side related to URI's including basic authentication not being processed.

**Comment by BanzaiMan** [comment]
@smetj That is a separate issue. Please open a new ticket.

**Comment by smetj** [comment]
@BanzaiMan  You're right, ... I will do that.
https://github.com/travis-ci/travis-ci/issues/9415
