### ISSUE TITLE
ssh_known_hosts addon only works with port 22

### ISSUE THREAD

**Issue by benvaljean** [travis-ci/travis-ci#9408]
Unless I have missed something in the docs the ssh_known_hosts addon only supports port 22. There is no option for the port and consequently ssh-keyscan never gets any data. 

For the moment the workaround is to add it manually to `before_deploy`

	before_deploy:
	- ssh-keyscan -p2222 -H $host 2>&1 | tee -a $HOME/.ssh/known_hosts

**Comment by BanzaiMan** [comment]
I think you did miss this passage in the documentation. :-)

https://docs.travis-ci.com/user/ssh-known-hosts/

> Hosts with ports can also be specified:
>
>     addons:
>       ssh_known_hosts: git.example.com:1234
