### ISSUE TITLE
CSS is broken in API V2 documentation website

### ISSUE THREAD

**Issue by surli** [travis-ci/travis-ci#9409]
See: https://docs.travis-ci.com/api

![capture d ecran 2018-03-29 a 16 24 20](https://user-images.githubusercontent.com/1478232/38094365-d7964fd0-336d-11e8-93c9-3a141129fa0a.png)

**Comment by plaindocs** [comment]
Hey @surli - we're working on that! For now please add a trailing slash: https://docs.travis-ci.com/api/

**Comment by plaindocs** [comment]
Fixed by https://github.com/travis-ci/docs-travis-ci-com/pull/1813
