### ISSUE TITLE
Cannot run binary from gem installed via --user-install

### ISSUE THREAD

**Issue by sschuberth** [travis-ci/travis-ci#9412]
In [this build](https://travis-ci.org/sschuberth/debug-travis/builds/359862206), I'm installing the [licensee gem](https://github.com/benbalter/licensee) via

    gem install --user-install licensee -v 9.9.0.beta.3

which succeeds, but then running its binary like

    $(ruby -r rubygems -e "puts Gem.user_dir")/bin/licensee version

fails with

    /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem licensee (>= 0.a) (Gem::GemNotFoundException)
        from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
        from /home/travis/.gem/ruby/2.4.0/bin/licensee:23:in `<main>'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

However, if I omit the `--user-install` option and just run `licensee` from `PATH`, [the build](https://travis-ci.org/sschuberth/debug-travis/builds/359865799) succeeds.

Any idea why passing `--user-install` makes a difference? I believe it should just work as well.

**Comment by BanzaiMan** [comment]
The `--user-install` alters gem's installation location. http://guides.rubygems.org/command-reference/#gem-install

> `-​-[no-]user-install` - Install in user’s home directory instead of `GEM_HOME`.

It seems everything is working as documented.

**Comment by sschuberth** [comment]
> The `--user-install` alters gem's installation location.

Yes, that's why I'm running the binary from the user's home directory. Also, this works just fine on my local Linux machine, just not on Travis CI.

**Comment by sschuberth** [comment]
Was someone from Travis CI able to confirm the issue yet?

**Comment by sschuberth** [comment]
The problem [persists](https://travis-ci.com/heremaps/oss-review-toolkit/builds/77149059#L802).

**Comment by sschuberth** [comment]
Ping.

**Comment by BanzaiMan** [comment]
As I mentioned earlier, everything seems to be working as documented. If your process cannot find it during your build, `$PATH` is most likely not set up to find it. Please review your configuration and try again. We are happy to enable debug feature if you'd rather have that for troubleshooting. Thanks.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
