### ISSUE TITLE
[iOS] Video can't be played on Travis CI

### ISSUE THREAD

**Issue by RomanTysiachnik** [travis-ci/travis-ci#9413]
## [iOS] Video can't be played on Travis CI
Hello.

We're trying to run our iOS UI tests on Travis CI. These tests include video playing and they work absolutely great when we launch them locally and, of course, we've checked everything before launching them on the CI.

If we try to play our video in our player on the CI, we get the error:

```swift
Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed"
UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12894),
NSLocalizedDescription=The operation could not be completed,
NSUnderlyingError=0x608000247500 {Error Domain=NSOSStatusErrorDomain Code=-12894 "(null)"}
```

We also make a snapshot if our tests fail and we can see, that our player was created, it is opened, but it just can't play any video.

I've seen an issue that is open for a year now - #7600. 

Is it possible that it is exactly why we can't play this video? Is there any way to fix that from our side?

I really hope that there is a solution for that.

**Comment by RomanTysiachnik** [comment]
Any comments on that issue?

**Comment by RomanTysiachnik** [comment]
So there won't be any answer about that? The issue doesn't seem to be resolved.

**Comment by DrTorte** [comment]
Hello,

I'll see if I can get some info on this internally and if we have an update. Right now, I believe we have a limit of 4MB VRAM. I think this might be causing the problem for you? We are looking into the possibility of extending that to allow an increased resolution, but I don't know how far we'll be pushing it.

In the meanwhile, we're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
