### ISSUE TITLE
Webhooks not accepting URI with username and password

### ISSUE THREAD

**Issue by smetj** [travis-ci/travis-ci#9415]
It seems that URI's for webhook notifications including basic authentication information isn't supported?

For example:
`https://username:password@events.smetj.net/travis`

If I omit the `username:password@` part I can see the request coming in on my end. When I leave the username and password the request never reaches the API on my end.

So it seems to me that there's a bug on the Travis side related to URI's including basic authentication not being processed.

**Comment by BanzaiMan** [comment]
Our HTTP client in use, `faraday` does not support this (https://github.com/lostisland/faraday/issues/343), so we need to do our own processing beforehand.

**Comment by smetj** [comment]
I'm not into Ruby but perhaps referring to a non-existing def?
https://github.com/travis-ci/travis-tasks/blob/779b2d6e64ac06517fe8dae1370da65747c614da/lib/travis/addons/webhook/task.rb#L61

**Comment by BanzaiMan** [comment]
@smetj Ah, yes. You are right.
