### ISSUE TITLE
osx_image: xcode9.3 image ?

### ISSUE THREAD

**Issue by mmdumi** [travis-ci/travis-ci#9416]
Hi,
Can you let me know what is the ETA for `osx_image: xcode9.3` ? 
Thank you

**Comment by rakaramos** [comment]
+1

**Comment by jerilyngigigo** [comment]
+1

**Comment by BanzaiMan** [comment]
We'll update when we have an ETA. Thanks for your patience.

**Comment by BanzaiMan** [comment]
9.3 is out.
