### ISSUE TITLE
.NET Standard & .NET Framework in one solution

### ISSUE THREAD

**Issue by JensYvanDeCraecker** [travis-ci/travis-ci#9417]
Hello

I have a [repository](https://github.com/JensYvanDeCraecker/SimplePipeline) that contains two projects.

My library written in .NET Standard 2.0 and my unit testing project in written in .NET Framework.

Currently I managed to only setup a build for my library but not to run the unit tests with it because I cannot find any documentation for my case.

Any help would be appreciated.

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by akoeplinger** [comment]
At the moment it's not possible to build for .NET Framework with the .NET Core / `dotnet` toolchain. You'd have to use Mono for that.

**Comment by JensYvanDeCraecker** [comment]
But is it possible to build the main project with dotnet since its written in Standard and build the unit testing project with Mono and then run the tests?

**Comment by akoeplinger** [comment]
Yeah that should work, try running `msbuild` on the tests project.

**Comment by JensYvanDeCraecker** [comment]
https://travis-ci.org/JensYvanDeCraecker/SimplePipeline/jobs/360294023


error: Could not find file: /home/travis/build/JensYvanDeCraecker/SimplePipeline/SimplePipeline/SimplePipeline.Tests/bin/Release/xunit.dll

What do i do now?

**Comment by akoeplinger** [comment]
It looks like it expects xunit.dll in the output directory so you could try copying there from the nuget packages dir.

**Comment by JensYvanDeCraecker** [comment]
Please correct me if i'm wrong, isn't xunit.dll for v1 and xunit.execution.desktop.dll for v2?

**Comment by JensYvanDeCraecker** [comment]
https://github.com/xunit/xunit/issues/334#issuecomment-77004474
