### ISSUE TITLE
Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/main/binary-amd64/Packages  502  Bad Gateway

### ISSUE THREAD

**Issue by BorzdeG** [travis-ci/travis-ci#9418]
https://travis-ci.org/itbasis/jvm-wrapper/jobs/360271445

**Comment by BanzaiMan** [comment]
Does the issue persist if you restart the job? HTTP 502 is a server error. If a simple GET is failing with a 5XX error, there is very little we can do, I'm afraid.

**Comment by BorzdeG** [comment]
Yes, it was re-protected. The error appeared only today - the previous launches occurred correctly.

**Comment by BorzdeG** [comment]
Here is the next assembly in the same linux-image, which worked correctly: https://travis-ci.org/itbasis/jvm-wrapper/jobs/360271456#L468

**Comment by BorzdeG** [comment]
But the neighboring assembly, in which even when restarting the problem does not appear: https://travis-ci.org/itbasis/jvm-wrapper/jobs/360271465#L484
The linux-image is the same. The access to the external resource is identical.

**Comment by BorzdeG** [comment]
fixed: https://github.com/travis-ci/travis-ci/issues/9421#issuecomment-378788165
