### ISSUE TITLE
Failed connect to download.oracle.com:80; Connection timed out

### ISSUE THREAD

**Issue by BorzdeG** [travis-ci/travis-ci#9419]
When you try to access an external resource from a running docker container

https://travis-ci.org/itbasis/jvm-wrapper/jobs/360271450

relation #9418 ?

**Comment by m1guelpf** [comment]
Possibly related to https://github.com/travis-ci/travis-ci/issues/9421

**Comment by BorzdeG** [comment]
fixed: https://github.com/travis-ci/travis-ci/issues/9421#issuecomment-378788165
