### ISSUE TITLE
Connecting to repo.mysql.com:443 timed out

### ISSUE THREAD

**Issue by Majkl578** [travis-ci/travis-ci#9421]
Hi, we're seeing issues while installing MySQL from repo.mysql.com.
The host & packages seem to be normally accessible (i.e. I can visit the site, download packages etc.), but Travis jobs fail to connect.

Failing build job: https://travis-ci.org/doctrine/dbal/jobs/360461497

```
--2018-03-30 23:09:02--  (try:20)  https://repo.mysql.com//mysql-apt-config_0.8.9-1_all.deb
Connecting to repo.mysql.com (repo.mysql.com)|23.45.133.192|:443... failed: Connection timed out.
Giving up.
```

This seems to happen randomly (but repeatedly) even during one stage, i.e. the following didn't fail while using same installation source:
https://travis-ci.org/doctrine/dbal/jobs/360461496#L841

Another example: stage with 6 jobs using repo.mysql.com (those with `MYSQL_VERSION=5.7`), 3 out of 6 failed:
https://travis-ci.org/doctrine/dbal/builds/360456413

Looks similar to #9419 since MySQL also falls under Oracle.

**Comment by m1guelpf** [comment]
Same error for me:
```
Failed to fetch http://repo.mysql.com/apt/ubuntu/dists/trusty/InRelease  Could not connect to repo.mysql.com:80 (23.45.133.192), connection timed out
```

**Comment by nwalters512** [comment]
I'm seeing the same thing: https://travis-ci.org/illinois/queue/builds/360692221

Any insight into why this is suddenly failing would be appreciated.

**Comment by rugabarbo** [comment]
The same error for `Yii2` builds: https://travis-ci.org/yiisoft/yii2/jobs/360612041#L486

**Comment by ssmereka** [comment]
+1 Seeing the same error.

**Comment by codylerum** [comment]
Seeing same. Just started a couple days ago.

**Comment by samdjstephens** [comment]
Having the same issue, intermittently

```
W: Failed to fetch http://repo.mysql.com/apt/ubuntu/dists/trusty/InRelease  Could not connect to repo.mysql.com:80 (23.45.133.192), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install mysql-server" failed and exited with 100 during .
```

**Comment by edmorley** [comment]
This is affecting us too:

```
E: Failed to fetch http://repo.mysql.com/apt/ubuntu/pool/mysql-5.7/m/mysql-community/mysql-common_5.7.21-1ubuntu14.04_amd64.deb  Could not connect to repo.mysql.com:80 (23.45.133.192), connection timed out
E: Failed to fetch http://repo.mysql.com/apt/ubuntu/pool/mysql-5.7/m/mysql-community/libmysqlclient20_5.7.21-1ubuntu14.04_amd64.deb  Unable to connect to repo.mysql.com:http:
E: Failed to fetch http://repo.mysql.com/apt/ubuntu/pool/mysql-5.7/m/mysql-community/libmysqlclient-dev_5.7.21-1ubuntu14.04_amd64.deb  Unable to connect to repo.mysql.com:http:
E: Failed to fetch http://repo.mysql.com/apt/ubuntu/pool/mysql-5.7/m/mysql-community/mysql-community-client_5.7.21-1ubuntu14.04_amd64.deb  Unable to connect to repo.mysql.com:http:
E: Failed to fetch http://repo.mysql.com/apt/ubuntu/pool/mysql-5.7/m/mysql-community/mysql-client_5.7.21-1ubuntu14.04_amd64.deb  Unable to connect to repo.mysql.com:http:
E: Failed to fetch http://repo.mysql.com/apt/ubuntu/pool/mysql-5.7/m/mysql-community/mysql-community-server_5.7.21-1ubuntu14.04_amd64.deb  Unable to connect to repo.mysql.com:http:
E: Failed to fetch http://repo.mysql.com/apt/ubuntu/pool/mysql-5.7/m/mysql-community/mysql-server_5.7.21-1ubuntu14.04_amd64.deb  Unable to connect to repo.mysql.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by cotsog** [comment]
Hey everyone, we are sorry for this issue.

We've deployed an infrastructure change yesterday to fix this. Could you confirm if you can now connect to repo.mysql.com without issue?

Thanks!

**Comment by edmorley** [comment]
@cotsog we haven't seen this since then - seems fixed - thank you! :-)

**Comment by Majkl578** [comment]
Haven't seen this issue for some days now so closing. Thanks @cotsog.

**Comment by evilaliv3** [comment]
@cotsog : Actually we are experiencing the same again at @GlobaLeaks: https://travis-ci.org/github/globaleaks/GlobaLeaks/jobs/690859691

we are not able to reach https://deb.globaleaks.org from Travis within docker
