### ISSUE TITLE
toLocaleString has lower precision in Node

### ISSUE THREAD

**Issue by nickmccurdy** [travis-ci/travis-ci#9422]
I have a test suite that asserts a Number is equal to `2.2107391972073336e+23` with six zeros after being formatted with `.toLocaleString`. Locally my test passes with six zeros, but Travis fails with nine zeros of precision, which is a significant loss of precision and causes my tests to fail. Both environments are using Node 9.10.1, the same package lock, and the same locale. Even installing `language-pack-en` did not change the results.

## [Failing build](https://travis-ci.org/nickmccurdy/password-entropy/builds/360506337)

**Comment by nickmccurdy** [comment]
It seems like the issue is that Travis is using system-icu, which depends on the OS, instead of small-icu. Is there any way to use a different ICU build? nvm doesn't seem to support it.

**Comment by BanzaiMan** [comment]
We install Node.js run times with nvm. How are you getting your local machine to work?

**Comment by nickmccurdy** [comment]
I have Node installed with Homebrew locally, which seems to also use system-icu. So it seems like both use the same ICU build flags, but according to https://nodejs.org/api/intl.html, the behavior differs across OSes. I would like to be able to install a different ICU of Node on Travis to get around this, but nvm does not support it.

**Comment by BanzaiMan** [comment]
The best bet would be to work with https://github.com/creationix/nvm to add such support. I am afraid that we are unable to make this happen on our side.

**Comment by nickmccurdy** [comment]
Thanks, here's the upstream issue: https://github.com/creationix/nvm/issues/1719

If this gets implemented would there be a convenient way to configure the ICU for nvm through Travis, or would nvm have to be used manually in an install script?

**Comment by ljharb** [comment]
I believe you'd have to invoke nvm manually so you could pass custom configuration arguments.

**Comment by BanzaiMan** [comment]
Based on what @ljharb's input, then, it might be best to run `nvm install` again (this time with appropriate flags) in `before_install`.
