### ISSUE TITLE
How to use crontab correctly in Travis 

### ISSUE THREAD

**Issue by Vizards** [travis-ci/travis-ci#9423]
I used linux `crontab` command in my code, but I found it seems can't run correctly in Travis.

I used [node-crontab](https://github.com/dachev/node-crontab) to establish a new linux crontab, make `cron.sh` run every 6 hours, but when I try to test it by Travis, Travis return an error:

```
InternalServerError: crontabs/travis/: fopen: Permission denied
```

Here's my `.travis.yml`:

```
{
  "sudo": false,
  "language": "node_js",
  "node_js": "8",
  "services": [
    "mongodb"
  ],
  "before_install": [
    "chmod +x cron.sh"
  ],
  "install": [
    "npm i npminstall && npminstall"
  ],
  "script": [
    "npm run ci"
  ],
  "after_script": [
    "npminstall codecov && codecov"
  ],
  "os": "linux",
  "group": "stable",
  "dist": "trusty"
}
```

My purpose is simply to test whether such a crontab task can be established and cancelled, and I don't need Travis to perform this crontab task for me. 

And I've tried to set `sudo` to `true`, but still didn't work.

Any help will be very appreciable.

[build log](https://travis-ci.org/Vizards/uestc-api/jobs/360606142)

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by Vizards** [comment]
@BanzaiMan I'm sorry I forgot to add it, the build log URL: https://travis-ci.org/Vizards/uestc-api/jobs/360606142

**Comment by BanzaiMan** [comment]
Does this work on your machine? How does it decide to read `crontabs/travis/`? And where is this directory (it is relative, and I don't know where it's supposed to be on the file system). Does it exist? Notice that `crontabs/travis/` is a directory; if the file exists and the utility is trying to read the directory content, it is also likely to fail.

You might want to try reproducing the error with our Docker image. https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

**Comment by Vizards** [comment]
@BanzaiMan it can work correctly on my Mac and Ubuntu. `crontab/travis/` only displayed on Travis log. So this could only set by Travis itself. this npm package (node-crontab) just call linux system crontab command to establish a new timed task. But Travis seems not allow me to do so.

I want to know if Travis has restricted my permission to use the system crontab command and is there any way to get this permission?  I've searched the official documents, all the relevant content on the search engine, but there is no relevant solution.

**Comment by BanzaiMan** [comment]
`crontab` looks for the user's `crontab` (http://man7.org/linux/man-pages/man1/crontab.1.html#OPTIONS). I suppose `crontab/travis/` refers to that. Please try reproducing the issue with the Docker image.

**Comment by Vizards** [comment]
@BanzaiMan Thank you very much, I'll try it
