### ISSUE TITLE
Wrong return result after one build is restarted.

### ISSUE THREAD

**Issue by NhatDinh** [travis-ci/travis-ci#9425]
After restarting one build process, I got this as a result:
<img width="1252" alt="screen shot 2018-04-01 at 12 12 28 pm" src="https://user-images.githubusercontent.com/35314819/38176552-04c02dac-35a6-11e8-9566-951099719f40.png">
I think it should return all checks have passed instead of #3 cancelled. I'm not sure if this is a legit concern.
Thank you,
-Nhat

**Comment by BanzaiMan** [comment]
https://travis-ci.org/NhatDinh/checker-framework/builds/360931829 has another stage after Test, which is not restarted after your restart. The build over all remains "Cancelled" as a result. This is discussed in https://github.com/travis-ci/beta-features/issues/28.
