### ISSUE TITLE
Failed To Deploy

### ISSUE THREAD

**Issue by MalcolmMerlyn** [travis-ci/travis-ci#9426]
I am getting a weird issue. http://prntscr.com/izjqqb

**Comment by BanzaiMan** [comment]
Hello. Most likely your api key encryption is incorrect.

**Comment by gagofure** [comment]
![image](https://user-images.githubusercontent.com/19293902/79067581-4021b900-7cb8-11ea-8ca8-7d46608bce00.png)

I am having the same issue
