### ISSUE TITLE
Inconsistent wget output display between GitHub repos

### ISSUE THREAD

**Issue by szpak** [travis-ci/travis-ci#9433]
I'm trying to track down inconsistent `wget` output behavior between GitHub projects. In one project `wget` leverages terminal type and displays progress in one line. In the second it takes 4K lines in a log to download a large file (which generates a risk of a "log overflow").

I striped down `.travis.yml` to bare minimum and remove everything from a given branch. `TERM` is automatically set in both to `xterm`. `evn` returns the same values (for non build related variables).

Project 1:
https://github.com/szpak/junit5-samples/blob/wgetTerm2/.travis.yml
https://travis-ci.org/szpak/junit5-samples/builds/361322614#L547

Project 2:
https://github.com/szpak/mockito-java8/blob/termWget/.travis.yml
https://travis-ci.org/szpak/mockito-java8/builds/361323326#L551
(the first is small, [output](https://travis-ci.org/szpak/mockito-java8/builds/361323326#L564) for large file)

Do you know what could be a reason? How can I achieve "one-line" output from wget in my second project?

**Comment by szpak** [comment]
The issue is still valid: https://travis-ci.org/szpak/mockito-java8/builds/398916007#L543

The output is:
>      0K .........                                             100% 69.6M=0s
instead of
> 100%[======================================>] 4,248       --.-K/s   in 0s

which for a large file generates multiple lines of output.

**Comment by BanzaiMan** [comment]
The one with `0K ....` has secure environments defined and the log goes through our filters to hide the secrets. The progress bar one does not.

**Comment by szpak** [comment]
@BanzaiMan That makes sense. Thanks for your explanation.

@DrTorte You closed it because it has been fixed or because you don't plan (or don't have an idea how )to fix it?

**Comment by DrTorte** [comment]
Hey @szpak,

Sorry about that, I should've placed the link requesting a thread like this be moved to the [Travis CI Forum](https://travis-ci.community) where we're more active and watching. :)
