### ISSUE TITLE
Could not find .travis.yml, using standard configuration.

### ISSUE THREAD

**Issue by gkarthiks** [travis-ci/travis-ci#9435]
Hi,

My Travis build for my Java project is not building and says 
`Could not find .travis.yml, using standard configuration.`. 
Please find the build here 
https://travis-ci.org/gkarthiks/s3-presigned-url

and the project is available in [GitHub](https://github.com/gkarthiks/s3-presigned-url/tree/master)

**Comment by BanzaiMan** [comment]
There isn't any for [the commit](https://github.com/gkarthiks/s3-presigned-url/tree/4a39422a82c1ccee9f8b3773b1c63cea7fc72288) that triggered [the most recent build](https://travis-ci.org/gkarthiks/s3-presigned-url/builds/319596368). 

Looks like the webhook from GitHub was invalid for some reason. I've reset this for you, so new commits should trigger builds now.

**Comment by gkarthiks** [comment]
Not sure why the webhook went invalid. Looks fine for me now. Thanks 👍
