### ISSUE TITLE
PHP 7.2 cannot load apcu.so

### ISSUE THREAD

**Issue by PHLAK** [travis-ci/travis-ci#9436]
Installing APCu and APCu BC via Pecl in a PHP 7.2 environment and getting the following error:

    PHP Warning:  PHP Startup: Unable to load dynamic library 'apc.so' (tried: /home/travis/.phpenv/versions/7.2.4/lib/php/extensions/no-debug-zts-20170718/apc.so (/home/travis/.phpenv/versions/7.2.4/lib/php/extensions/no-debug-zts-20170718/apc.so: undefined symbol: zif_apcu_store), /home/travis/.phpenv/versions/7.2.4/lib/php/extensions/no-debug-zts-20170718/apc.so.so (/home/travis/.phpenv/versions/7.2.4/lib/php/extensions/no-debug-zts-20170718/apc.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Even though it claims to have installed `apcu.so` successfully just a few lines before.

![screenshot 2018-04-02 17 43 30](https://user-images.githubusercontent.com/53531/38223032-76405856-369d-11e8-995e-d565432f0ba0.png)

You can see the failed build here: https://travis-ci.org/PHLAK/Stash/jobs/361421109

For what it's worth the exact same build works with PHP 7.1

**Comment by PHLAK** [comment]
This is still an issue.

https://travis-ci.org/PHLAK/Stash/jobs/398983315#L826-L829

**Comment by BanzaiMan** [comment]
Please use https://travis-ci.community/c/languages/php for further discussion. Thanks.
