### ISSUE TITLE
Rubygems deployment fails silently

### ISSUE THREAD

**Issue by reitzig** [travis-ci/travis-ci#9439]
I have configured build and deployment of a Ruby gem according to the docs ([1](https://docs.travis-ci.com/user/deployment/rubygems/), [2](https://docs.travis-ci.com/user/build-stages/deploy-rubygems/); nb: the issue occurred also without stages).

All seems to be fine:

```log
Preparing deploy
Looking up gem tex_log_parser
Found gem tex_log_parser
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
Saved working directory and index state WIP on (no branch): 77e3bd9 Fixes Travis gem deployment, Epsiode III.
dpl.3
Deploying application
WARNING:  description and summary are identical
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: tex_log_parser
  Version: 1.0.0.pre.6
  File: tex_log_parser-1.0.0.pre.6.gem
Already up to date!
Not currently on any branch.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.bundle/
	vendor/
nothing added to commit but untracked files present (use "git add" to track)
Dropped refs/stash@{0} (73633bca87cb64d0dcac42cd5822ab32e10e5c53)
Done. Your build exited with 0.
```

Except that it doesn't actually deploy the gem. What's going on here?

I can deploy the gem from the command line without problems.

Sources: https://github.com/reitzig/texlogparser
Offending log: https://travis-ci.org/reitzig/texlogparser/jobs/361850727#L517
Target gem: https://rubygems.org/gems/tex_log_parser

**Comment by BanzaiMan** [comment]
https://travis-ci.org/reitzig/texlogparser/jobs/361874516#L531

> Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.

/user/deployment/rubygems#Releasing-build-artifacts informs you that your *.gem file will be cleaned up if you don't specify `skip_cleanup: true`.

**Comment by reitzig** [comment]
Further notes:
 - Without `skip_cleanup`, phase "Deploying application" happens _before_ the cleanup, so I don't see why that setting is necessarily relevant.
 - There is no indication in either case that `gem push` is being called, at all.

If this is a bug in the `rubygems` provider, am I in the right place?

**Comment by BanzaiMan** [comment]
To think, `skip_cleanup` is not necessary for Rubygems deployment, as the deployment code will look for `*.gemspec` file and builds the gem instead. So your issue lies elsewhere.

> Without `skip_cleanup`, phase "Deploying application" happens before the cleanup, so I don't see why that setting is necessarily relevant.

"Deploying…" announces the start of the deployment process. Cleanup happens during that process. I see why you might expect this message to announce the actual deployment process to the remote service; your input for improvement is appreciated.

> There is no indication in either case that `gem push` is being called, at all.

The reason here is that we use [`gems`](http://rubygems.org/gems/gems) to deploy the file. This gem is rather spartan in error handling, and it doesn't appear to be reporting any issue your build is seeing.

When it successfully pushes a gem, you'd [see something like](https://travis-ci.org/travis-ci/dpl/jobs/359571714#L2020):

    Successfully registered gem: dpl-anynines (1.9.6.travis.2795.5)

Perhaps your API key is incorrect.

**Comment by reitzig** [comment]
> your input for improvement is appreciated.

My main issue here is how it's almost impossible to diagnose the issue. And I'm not alone; I saw many similar tickets, with people guessing their way towards a solution (or giving up?).

I guess, ideally, the log would have the following form (for external programs at least):

```
 Step i. Will try to run:
	`my_funcy_command with options`
	Reason: because of good reasons! And you asked for it with that option.

	The output was:
		Line 1
		...
		Line n
```

I have no idea of the internals of Travis, but "run a command and capture all its output" is a task I've solved before, and it's totally doable. :)

> This gem is rather spartan in error handling, and it doesn't appear to be reporting any issue your build is seeing.

Hm, if this gem swallows the errors, then all bets are off. Where do I report a bug for _that_?

> Perhaps your API key is incorrect.

Locally, I messed up my API key in `~/.gem/credentials` and got this:
```
$ gem push tex_log_parser-1.0.0.pre.9.gem 
Pushing gem to https://rubygems.org...
Access Denied. Please sign up for an account at https://rubygems.org
$ echo $?
1
```

This is maybe not as specific as it could be, but it's certainly more than nothing. We don't see this in my logs. Or is that not what's being run?

**Comment by reitzig** [comment]
@BanzaiMan Any pointers as to what I can try? I'm at a loss about how to diagnose this.
