### ISSUE TITLE
deploy to github returns a 404 error 

### ISSUE THREAD

**Issue by zarlo** [travis-ci/travis-ci#9441]
with borevitzlab/go-eyepi when we try to deploy to releases 

i have done some test on my end and im getting 404 too

```
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/borevitzlab/go-eyepi/releases: 404 - Not Found // See: https://developer.github.com/v3/repos/releases/#create-a-release (Octokit::NotFound)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/connection.rb:175:in `post'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:28:in `post'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:32:in `create_release'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.5/lib/dpl/provider/releases.rb:106:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by zarlo** [comment]
https://travis-ci.org/borevitzlab/go-eyepi/builds/361944582

**Comment by BanzaiMan** [comment]
404 is coming from GitHub. I don't know why, though. I can't recreate a request that results in a 404.

**Comment by tmccombs** [comment]
This is happening to me for https://travis-ci.org/lucidsoftware/opentracing-playframework/builds/368741702

restarting the build did no thelp.

**Comment by maximbaz** [comment]
Here's another one: https://travis-ci.org/emojione/emojione-assets/builds/422321839

**Comment by asbjornu** [comment]
Here's another [failing deployment from a `git tag`](https://travis-ci.org/PayEx/payex-magento2-checkout/jobs/532383179) and here's a [failing build on a Release created through the GitHub UI](https://travis-ci.org/PayEx/payex-magento2-checkout/jobs/532385503). I first thought the `404` might be due to the Release not being created on GitHub, but the latter failed build shows that's not the case.

**Comment by asbjornu** [comment]
I've set up the GitHub deployment with `travis setup releases`, so the GitHub OAuth Token is created by Travis itself (with `public_repo` scope). However, the user owning the OAuth Token didn not have write access to the repository. After giving the user write access, [the build succeeded](https://travis-ci.org/PayEx/payex-magento2-checkout/builds/532389169).

**Comment by asbjornu** [comment]
The fact that the user owning the GitHub OAuth Token needs write access to the repository in order to upload release artifacts is perhaps something the `travis` command line utility might be able to check for when doing `travis setup releases`?
