### ISSUE TITLE
Update `yarn` to a recent version

### ISSUE THREAD

**Issue by waleedahmed3045** [travis-ci/travis-ci#9445]
Hi during my build i notice that the yarn version on tarvis-ci.org is 1.3.2 but the currently released version is 1.5.1 https://yarnpkg.com/en/. Can this please be updated?

![image](https://user-images.githubusercontent.com/5687191/38344801-954b3244-3859-11e8-8fb2-090f6097a0bc.png)

**Comment by L2jLiga** [comment]
The latest stable release of `yarn` is now 1.7.0, version 1.3.2 was deprecated

**Comment by jzempel** [comment]
Now 1.9.0 and counting. Please update. We need valid support for `publishConfig`.

**Comment by carloscuesta** [comment]
I'm having the same problem! Why we can't specify the `yarn` version that we want to use? @backspace 🙏 

We can workaround it with a `before_script`, but that's not the best solution

**Comment by tmo-trustpilot** [comment]
We're now seeing problems with how the old version handles integrity checks in the lock file for minor versions that is breaking our build. Upgrading this or having it configurable would be great.

**Comment by mattbishop** [comment]
Can't build with Node 10 and yarn because yarn is too old (`new Buffer() not supported`).

**Comment by BanzaiMan** [comment]
If the newer version of `yarn` solves your problem, the best practice would be to install it at the run time. While we should update build images more often, with frequent releases of yarn, you will find it outdated. Furthermore, older build images will eventually stop getting updates.

**Comment by AviVahl** [comment]
@BanzaiMan the current state is that Linux has a built-in older yarn (1.3.2) while Mac and Windows install latest version of yarn by default. This inconsistency makes us reconfigure each and every repo with yarn installation scripts.

**Comment by ZebraFlesh** [comment]
Yarn 1.3.2 has uses the deprecated/unsafe `Buffer` constructor (which was removed from node.js due to a [vulnerability](https://medium.com/@jasnell/node-js-buffer-api-changes-3c21f1048f97)). This has been addressed in yarn 1.10.0: https://github.com/yarnpkg/yarn/issues/5477

When will this security issue in the base image be addressed?

**Comment by DrTorte** [comment]
Hello,

I'll ping on this internally and see if I can find if anything's planned, but we appreciate you letting us know about the vulnerability.

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by waldyrious** [comment]
> We can workaround it with a before_script, but that's not the best solution
>
> ```yml
> before_install:
>   - curl -o- -L https://yarnpkg.com/install.sh | bash
>   - export PATH="$HOME/.yarn/bin:$PATH"
> ```

A cleaner/simpler alternative is to just do:

```yml
before_install:
  - npm install -g yarn
```

**Comment by cjancsar** [comment]
Why is this still not updated.

**Comment by gondar00** [comment]
Why is this still not supported 😠

**Comment by pr1ntr** [comment]
this is still not supported?! seriously?
