### ISSUE TITLE
iv undefined for local branch - encryption vars are not resolved

### ISSUE THREAD

**Issue by ChengyuanZhao** [travis-ci/travis-ci#9451]
Environment variables related to encryption stopped working today on local branches (not forks!): 

https://travis-ci.org/spring-cloud/spring-cloud-gcp/builds/362851123

````
$ echo "khm... $encrypted_5c865b234b57_iv"
khm... 
0.02s$ openssl aes-256-cbc -K $encrypted_5c865b234b57_key -iv $encrypted_5c865b234b57_iv -in travis.tar.gz.enc -out travis.tar.gz -d
iv undefined
The command "openssl aes-256-cbc -K $encrypted_5c865b234b57_key -iv $encrypted_5c865b234b57_iv -in travis.tar.gz.enc -out travis.tar.gz -d" failed and exited with 1 during .
Your build has been stopped.
````
They do seem to be defined on the UI:

![image](https://user-images.githubusercontent.com/29288945/38393792-f2e620ee-38f9-11e8-8192-ead6d726db63.png)

Can you please help figuring out what is going on? 

/cc @balopat

**Comment by backspace** [comment]
Hello, thanks for letting us know about this, @ChengyuanZhao. We had a deployment problem that I have now rolled back, can you try it again and update us on whether it now works as expected?

**Comment by BanzaiMan** [comment]
Close and reopen the PR, or push a new commit to the topic branch, please.

**Comment by ChengyuanZhao** [comment]
It's working now, thank you!

**Comment by backspace** [comment]
Excellent, thanks for the followup!

**Comment by kalianto** [comment]
@ChengyuanZhao , how did you get it to work? I have the same issue even after regenerating ssh key and doing travis encrypt-file multiple times, I still get the iv undefined. @backspace @BanzaiMan , help please.
I am on `--pro` account, here is my link : https://travis-ci.com/myworkpapers/prophet/builds/71489492 (not sure if this is accessible by you guys)

**Comment by BanzaiMan** [comment]
@kalianto @MaxInertia The error message means that the relevant variables are not properly defined. What command did you run?

**Comment by MaxInertia** [comment]
@BanzaiMan Sorry about that, it was my fault! I had just transferred that repo to an organization and on running `travis encrypt-file` the environment variables were getting saved to the wrong place. I had to specify the new repo location with the flag `-r`.

**Comment by BanzaiMan** [comment]
@MaxInertia Good to know you were able to figure it out. :-)

**Comment by austinpray** [comment]
for posterity: if you login as a --pro you need to specify --org when interacting with legacy platform repos

**Comment by ramanenka** [comment]
in my case I had to add `--com` option to the command although I was logged in to "com"

**Comment by johnalejandro001** [comment]
In my specific case I had to encrypt the file like so it can actually appear on the travis-ci.com. 

travis encrypt-file --com -r johnalejandro001/multi-k8s test-file.json

If --com is not specified it will write the secrets to the travis-ci.org side.
