### ISSUE TITLE
Cannot download pypy2.7 (archive url is 403 Forbidden) 

### ISSUE THREAD

**Issue by tsionyx** [travis-ci/travis-ci#9452]
https://travis-ci.org/tsionyx/pynogram/jobs/362988011

**Comment by tsionyx** [comment]
https://travis-ci.org/tsionyx/pynogram/jobs/362988011

**Comment by tsionyx** [comment]
However, both  `"python": "pypy"` and ` "python": "pypy3"` works well, so it's more of outdated [example](https://docs.travis-ci.com/user/languages/python#PyPy-Support) issue.

**Comment by BanzaiMan** [comment]
I copied the `pypy2.7-5.10.0` archive to `pypy2.7`. You should be able to get it now.

**Comment by hubo1016** [comment]
pypy2.7 is still not working, seems the soft link is missing

**Comment by jayvdb** [comment]
Note the docs were updated at https://github.com/travis-ci/docs-travis-ci-com/pull/1704 .

Unless this can be fixed quickly, the old identifier should be re-added to the docs.

**Comment by mgedmin** [comment]
The same error occurs on `dist: xenial` builds: https://travis-ci.org/mgedmin/check-manifest/jobs/454420607

pypy3.5 is available, but pypy2.7 is not (and neither are pypy/pypy2/pypy3, but pypy2.7-5.10.0 appears to be available).

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by mgedmin** [comment]
No worries!  I've created a [thread on the forum](https://travis-ci.community/t/pypy-2-7-on-xenial/889/2) for this very issue *checks notes* 21 days ago.
