### ISSUE TITLE
[community:r] add BiocCheck option for Bioconductor packages

### ISSUE THREAD

**Issue by LiNk-NY** [travis-ci/travis-ci#9455]
Hi Jim and Craig, @jimhester @craigcitro

It would be good to have an integrated option to run `BiocCheck` on a
Bioconductor package. 

It could be added as an additional value in the `.travis.yml` file such as:

```
r: bioc-devel
  bioc_check: true
```

Thanks for your attention.

Regards,
Marcel

**Comment by jimhester** [comment]
I agree this would be useful, would you be willing to do a PR to add this to the R build script, that way if there are changes / additional features needed down the line someone at Bioconductor will be more familiar with how to make them.

The relevant code is at [travis-ci/travis-build/lib/travis/build/script/r.rb#L226-L233](https://github.com/travis-ci/travis-build/blob/ef2f5cbc9c4f432c13b868fabcb6f968105ee8ff/lib/travis/build/script/r.rb#L226-L233). I am happy to answer questions as needed and review the PR if you would be willing to write it.

**Comment by LiNk-NY** [comment]
Hi Jim, @jimhester
Thanks for reviewing the PR! 
I've been able to get a build going for Travis but I've noticed that an error in `BiocCheck` does not
produce an error in the Travis build. Do you have any ideas why? 

https://www.travis-ci.org/waldronlab/MultiAssayExperiment/builds/396953726
**cc**: @jeroen

Thanks ! 

Regards,
Marcel

**Comment by jimhester** [comment]
It would only cause a failure if the BiocCheck call exists with a failure error code, I am guessing it does not.

**Comment by LiNk-NY** [comment]
This has been fixed. Thanks.
