### ISSUE TITLE
Travis deploy is using the wrong API url.

### ISSUE THREAD

**Issue by dscalzi** [travis-ci/travis-ci#9457]
I've configured my `.travis.yml` to deploy specific builds to GitHub releases using an oauth token. The repository on an organization account. The id for the organization is `WesterosCraftCode`, and the name is `WesterosCraft`. Travis is trying to use the name in the url ( https://api.github.com/repos/westeroscraft/electronlauncher/releases ), rather than the id (https://api.github.com/repos/westeroscraftcode/electronlauncher/releases ). The second url works, the first does not. As such, the deployment is failing.

I've tried renaming the repository to be the same as the id, however this did not change anything. Very much need help figuring this out.

Build can be found here https://travis-ci.org/WesterosCraftCode/ElectronLauncher/jobs/363658202

**Comment by BanzaiMan** [comment]
!https://travis-ci.org/WesterosCraftCode/ElectronLauncher/jobs/363658202 failed, so there is no deployment there.

When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you

**Comment by dscalzi** [comment]
Ah, I actually found the issue after looking at your comment. It looks like the builder I'm using has it's own deployment system, and that was failing. I fixed the issue in my package.json and all appears to be in order now. Thanks!
