### ISSUE TITLE
Upload console log to a custom location

### ISSUE THREAD

**Issue by mxr576** [travis-ci/travis-ci#9458]
I would like to upload the console log that I can see on the Travis CI UI for each job to a custom location. (So not to AWS with [artifacts plugin](https://docs.travis-ci.com/user/uploading-artifacts) .) How can I do that? Wher can I find that log in the file system?

**Comment by mxr576** [comment]
Anybody?

**Comment by mxr576** [comment]
Nobody?

**Comment by BanzaiMan** [comment]
Hello, there.

Do you want to upload the build log *from within* the build itself? I am afraid that will be a difficult task to achieve, as the build script is unable to access what has been written by the build script.

Alternatively, you can consider fetching the logs via API after the job has finished and upload it.

**Comment by mxr576** [comment]
That is unfortunate, I wanted to upload the output of the previous steps in the end of the build. Couldn't it be solved by redirecting the stdout/stderr to the file meanwhile the build for example?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
