### ISSUE TITLE
Secure values used in deployment definitions are not hidden in log output

### ISSUE THREAD

**Issue by sylveon** [travis-ci/travis-ci#9459]
An image tells it all:
![](https://files.charlesmilette.net/LovelyAcademicXeme)

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by sylveon** [comment]
https://travis-ci.org/sylveon/website/builds/359842019#L1993 here you go

**Comment by BanzaiMan** [comment]
Thanks for the info. (I've deleted your comment, in case you haven't revoked the API key.) I've confirmed the issue. The secure envs are hidden only when they appear in `env`. This is not the case with deployment definitions.

**Comment by sylveon** [comment]
There isn't a need to delete the comment or revoke anything. It's just
a project name, which doesn't gives much info except the firebaseapp
URL.

Thankfully it's such a minor thing that revealed this issue, and not
real API keys or confidential data.

-- 
Envoyé de mon Gmail
