### ISSUE TITLE
Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jab** [travis-ci/travis-ci#9460]
...is due out this month, but 14.04 LTS is still the latest Ubuntu version Travis supports.

Given the discussion in #5821, this is probably similarly a ways off, but seemed at least worth opening an issue for. ❤️

**Comment by BanzaiMan** [comment]
Hello. We have plans for 16.04 and 18.04 work, but no ETA at the moment. In the mean time, I'm closing this as a duplicate of #5821.

**Comment by reidpr** [comment]
This is not a duplicate, because #5821 was closed after addressing 16.04 only.

**Comment by allencloud** [comment]
We need Ubuntu 18.04 LTS as well because of the newer version of linux kernel !!! ❤️

**Comment by smaslennikov** [comment]
It's a little silly that the newest supported OS is nearly 3 years old - Ubuntu 16.04. I hate to be negative, but after banging my head against a wall of old library packages for several hours, silly is all this seems to be (to me).

**Comment by lukehinds** [comment]
The lack of decent distribution coverage is really making me question my selection of travis. No fedora, no opensuse, just old versions of Ubuntu.

**Comment by lazystone** [comment]
@BanzaiMan could you reopen this issue since it's NOT a duplicate of #5821

**Comment by BanzaiMan** [comment]
Any update will be posted in https://travis-ci.community/t/ubuntu-18-04-1-lts-bionic-beaver/1270. Thanks.

**Comment by reidpr** [comment]
@BanzaiMan there is literally nothing official from Travis in that thread, just people asking for updates.

**Comment by Atem18** [comment]
I think a solution is to build your apps in a container, that way you don't care about the OS. And then since you have a container, you can now also deploy it in production :)

**Comment by reidpr** [comment]
> I think a solution is to build your apps in a container

Not all apps work in a container.

> you can now also deploy it in production

Not all apps get deployed that way.
