### ISSUE TITLE
Build unknown with everything passing.

### ISSUE THREAD

**Issue by diegoreymendez** [travis-ci/travis-ci#9461]
Travis shows "Build Unknown" even though all tests are passing.

<img width="898" alt="screen shot 2018-04-09 at 14 33 19" src="https://user-images.githubusercontent.com/1836005/38512949-24d0dc32-3c03-11e8-8fe5-1279de80fab9.png">

**Comment by BanzaiMan** [comment]
As mentioned in https://docs.travis-ci.com/user/status-images/#Travis-CI-pages-show-the-default-branch%E2%80%99s-result, the badge does not consider PR builds.

Thanks.

**Comment by diegoreymendez** [comment]
Thanks for the help.  I was expecting PRs merged into the default branch to alter it's status.

**Comment by JohannLai** [comment]
@BanzaiMan if the PRs merged into default branch, will the status of the badge be updated?
