### ISSUE TITLE
The command "phpenv global 7.0" failed and exited with 127 during . on OSX builds

### ISSUE THREAD

**Issue by Saibamen** [travis-ci/travis-ci#9463]
Related: #2313

OSX builds is failing while running command `phpenv global 7.0`:
`The command "phpenv global 7.0" failed and exited with 127 during .`

Config:
```
language: php

os:
  - linux
  - osx

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install php; fi
```

Live example: https://travis-ci.org/Saibamen/HotelManager/jobs/364337901

**Comment by BanzaiMan** [comment]
Sorry, but we don't support PHP on the Mac. https://github.com/travis-ci/travis-ci/issues/2313 https://docs.travis-ci.com/user/languages/php

**Comment by Saibamen** [comment]
https://github.com/andig says that it can be done with homebrew...

**Comment by BanzaiMan** [comment]
@Saibamen We do not support use of the `php` key. You'll have to set `language` to some other value, so that the build gets to `before_install`.
