### ISSUE TITLE
[Enterprise] Environmental variables not being set

### ISSUE THREAD

**Issue by exp0nge** [travis-ci/travis-ci#9465]
Previously we could see hidden environmental variables in the logs as `SECURE_VAR=[secure]` but now that no longer shows and not being used during the build (eg: using basic auth with git)

**Comment by exp0nge** [comment]
Sorry, going to email support@travis-ci.com

**Comment by acnagy** [comment]
thanks so much! for enterprise-specific things, feel free to email enterprise@travis-ci.com in the future, too 👍
