### ISSUE TITLE
Cannot install python packages which use vcversioner with python 3.7-dev

### ISSUE THREAD

**Issue by dcrosta** [travis-ci/travis-ci#9466]
https://github.com/habnabit/vcversioner is a plugin to the python build system that interrogates the version control tag information to set a version when building/installing a python package.

It appears that Travis' version of python 3.7 does not play nicely with vcversioner, preventing `setup.py` from completing during the install phase, and causing build errors (eg https://travis-ci.org/dcrosta/simplest-python-project/builds/364580766).

I first noticed this on my builds for another project, beginning with https://travis-ci.org/dcrosta/tox-docker/jobs/363097343. Older builds for the same project (which also use vcversioner) such as https://travis-ci.org/dcrosta/tox-docker/builds/234564115 (which is admittedly from a fairly long time ago) passed.

It looks like the version of py37 in use is an alpha from January:

```
$ python --version
Python 3.7.0a4+
```

The current 3.7 release looks to be 3.7.0b3: https://github.com/python/cpython/releases/tag/v3.7.0b3

I've tested locally with that version and I don't see the same errors on my machine as I do in travis, but that's a version I built with configure/make/make install, so who knows what's different or non-standard about it.

**Comment by BanzaiMan** [comment]
3.7 builds have been failing (and therefore not updated; see, for example, https://travis-ci.org/travis-ci/cpython-builder/jobs/365439083) because it now requires the version of SSL that is unavailable on Trusty. See #9069.
