### ISSUE TITLE
I'm an admin of a public org repo: it doesn't show on Travis

### ISSUE THREAD

**Issue by sujeet** [travis-ci/travis-ci#9468]
I'm a member of the organization `scaledata`[(link)](https://github.com/orgs/scaledata/people?utf8=%E2%9C%93&query=sujeet), and admin of the public repository `sane-scala`[(link)](https://github.com/scaledata/sane-scala), but my travis profile shows neither the org, nor the repository. However, back in November 2017, I was able to add `sclinter` [(link to first travis build)](https://travis-ci.org/scaledata/sclinter/builds/300325696), another public repository from the same organization without an issue. Has something changed? I have re-synced with github, including revoking the OAuth access and re-granting it again, but nothing seems to help... Below are some screenshots if that helps...

Oh by the way, keep up the good work! Love the service! And loved the recent post-mortem blog post too! ❤️ 

# Org membership
![image](https://user-images.githubusercontent.com/284560/38570403-62b9d1a8-3d0b-11e8-81d6-7c2899a2e6c1.png)

# Repository admin
![image](https://user-images.githubusercontent.com/284560/38570483-990b697e-3d0b-11e8-8ddf-c803f53be473.png)

# Travis doesn't show the org or the repo
![image](https://user-images.githubusercontent.com/284560/38570785-472380b4-3d0c-11e8-8abc-cfa08976dfa0.png)

**Comment by BanzaiMan** [comment]
It would show up in https://travis-ci.org/profile/scaledata, but Travis does not appear to be authorized to access the org data. If you have the authority, click on the "Review and add" link in the left sidebar on your profile page, and try again.

Thanks.
