### ISSUE TITLE
Swift 4.1 + Xcode 9.3 = No output has been received in the last 10m0...

### ISSUE THREAD

**Issue by smiles-lduraes** [travis-ci/travis-ci#9469]
Hi there.

Although this morning I was informed that xcode9.3 image was released successfully (https://github.com/travis-ci/travis-ci/issues/9416), I am facing following error message:

**"No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated"**

For further information, please refer to following url:

https://travis-ci.com/smiles-sa/app-smiles-ios/jobs/118665397

In addition, please find below my .travis.yml file:

env:
  global:
  #KEY_PASSWORD
  - secure: xxxxxx
  - secure: xxxxxx
  - secure: xxxxxx

language: objective-c
osx_image: xcode9.3
before_install:
- gem install cocoapods
- pod --version
- pod repo update
- gem install fastlane --no-document
- pod install

before_script:
- scripts/add-keys.sh

jobs:
  include:
    - stage: build_deploy
      if: tag IS blank
      script:
        - scripts/script.sh

install: travis_wait 20

Have you guys already faced this issue?

**Comment by cotsog** [comment]
@smiles-lduraes: looks like you need to add the commands documented at

https://docs.travis-ci.com/user/common-build-problems/#Mac%3A-macOS-Sierra-(10.12)-Code-Signing-Errors

to your .travis.yml file or build scripts.

Could you try this out and let us know how it goes?

Thanks!
