### ISSUE TITLE
Add "language" support for Kubernetes

### ISSUE THREAD

**Issue by fabiand** [travis-ci/travis-ci#9470]
Hey, using KinVolks method (https://kinvolk.io/blog/2017/10/running-kubernetes-on-travis-ci-with-minikube/) you can easily run basic functional tests of i.e. Kubernetes Operators on a single node Kube cluster using minikube.

We are actually using it a few times, i.e. here: https://travis-ci.org/kubevirt/containerized-data-importer

I'm suggesting to introduce a "language" type "Kubernetes" to automate the setup of Kubernetes using kinvolk's method.
That might enable other kube projects to sue travis for functional tests.

**Comment by fabiand** [comment]
Just see the number of projects which are affected by this issue:
https://github.com/kubernetes/minikube/issues/2704

Which could be solved by solving this issue here.

**Comment by svenfuchs** [comment]
Thanks for the ping @fabiand. I think the question is probably best directed at @joshk and @BanzaiMan.

**Comment by joshk** [comment]
@fabiand Hey! we have a little chat internally and think maybe adding an `addon` would be better. 

We are still discussing this, but you could play around with this idea now if you like?

**Comment by fabiand** [comment]
@joshk is there a guide of how to write addons?
