### ISSUE TITLE
Running sauce_connect only on merge to master

### ISSUE THREAD

**Issue by guacamoli** [travis-ci/travis-ci#9471]
Hi, I'm fairly new to travis and I'm running e2e tests using saucelabs which is working great with sauce_connect.

However, in order to keep the build speedy, I want to only run certain tests (specifically the e2e tests using saucelabs) on merges to master rather than on every pull request.

**The problem:**
**How do I only run sauce_connect on ONLY merges to master?**

Right now I have:

```
...
addons:
 sauce_connect:
  username: "username"
  access_key: "access_key"
...
```

This runs sauce_connect for all requests. I'm aware that it might just be me being a noob with travis but any help would be much appreciated. Thanks!

**Comment by BanzaiMan** [comment]
As explained in https://docs.travis-ci.com/user/sauce-connect/, the sauce connect addon is not effective for PR builds. The doc mentions the JWT addon, but that will be discontinued in about a week.
