### ISSUE TITLE
Failure with Cargo caching

### ISSUE THREAD

**Issue by bradleybeddoes** [travis-ci/travis-ci#9472]
Firstly I just wanted to say a big thanks for travis-ci, it is invaluable for our open source project.

I recently enabled `cache: cargo` for our `.travis.yml` within the [Gotham web framework](https://github.com/gotham-rs/gotham). This has been going along fine until last night when the beta and nightly Rust channels seem to have gotten a new release resulting in this error: https://travis-ci.org/gotham-rs/gotham/jobs/364618862#L716

I've since removed `cargo: cache` within the PR that failed CI, https://github.com/gotham-rs/gotham/pull/199, and that has resulted in a success per https://travis-ci.org/gotham-rs/gotham/builds/364864235 (excluding the failure for `rustfmt` which is legitimate at the time of writing).

I was wondering if you folks might have any ideas as to why we saw this error and what I could do to prevent it?

**Comment by bradleybeddoes** [comment]
I should have added that our project makes use of [Cargo workspaces](https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html) and the crate that is highlighted in the failure message is contained within our workspace but untouched by changes in the PR itself.

**Comment by BanzaiMan** [comment]
It most likely means that your cache contained some binary files that were incompatible with the newer version of the Rust runtime.

**Comment by bradleybeddoes** [comment]
@BanzaiMan certainly seems that way. 

Any thoughts on how I can tweak Travis and my usage of `cache: cargo` to prevent this?

**Comment by BanzaiMan** [comment]
You are building against moving targets, so I expect this to happen from time to time.
