### ISSUE TITLE
Jobs in a single build can be based on *different* git commits

### ISSUE THREAD

**Issue by fingolfin** [travis-ci/travis-ci#9476]
## Short version
The travis website lists for each build, and each job, a commit which supposedly describes the git commit being used by that build resp. job. This information can be wrong: different jobs can end up building different commits; it can even happen that no single job in a build builds the commit the website lists, and each job can build a different commit.

The reason for this is that the git ref `refs/pull/NNNN/merge` exported by GitHub can change before any given job starts.

## Longer version
An example for the issue can be found at <https://travis-ci.org/gap-system/gap/jobs/365141986> (and I can create further examples at will).

For this job (as well as the the whole build and all other jobs in it), Travis claims that commit aada7b3 is being built -- the value of `refs/pull/2350/merge` at the time the Travis build was queued. But before the last job of that build started, I merged another PR into the master branch. I then visited gap-system/gap#2350 to force GitHub to re-check the mergability of that PR. This caused `refs/pull/2350/merge` to be updated against the new master commit.

This can be verified in the build log, where I added a `printenv` invocation. First, line 545 shows `TRAVIS_COMMIT=aada7b3bd725dd7c9e67724c8da96f2a036d8efb` confirming what the webpage claims.

But in line 575, I also added a call to `git show --pretty=fuller -s`, which shows that we actually are building a different commit:
```
commit d1b208892357e5b2b0ead765f71a33c716c26330 (HEAD)
Merge: 5361093 415d9d6
Author:     Max Horn <max@quendi.de>
AuthorDate: Wed Apr 11 16:19:14 2018 +0000
Commit:     GitHub <noreply@github.com>
CommitDate: Wed Apr 11 16:19:14 2018 +0000
    Merge 415d9d61ffbc75d5778abadf23ce14ba9f79e3d8 into 5361093f7fd17181549733ace259e2b2c4c01935
```

## Consequences

This has major ramifications for us, as it renders test coverage results for builds affected by this useless. In the extreme case, it can incorrectly double the claimed coverage of a build. The only recourse we have is to restart all jobs in a given build, and then make sure nothing gets merged while they run.

## Possible solutions

Here are some thoughts on possible solutions; of course I don't know your system in detail, so I can't judge how viable each really is, and of course I may have missed many solutions, but perhaps these ideas are still useful for you:

1. One "solution" would be to accept that different builds can end up testing different commits. I really hope you won't do that, though, as it greatly diminishes the usefulness of Travis for test coverage computations.

2. Better would be to change jobs to not use `refs/pull/NNN/merge` for fetching the repository, but instead use the value of the `TRAVIS_COMMIT` environment variable. However, this has other problems: once GitHub updates the merge commit for the PR, the old transient merge commit may be garbage collected, and you may not be able to fetch it anymore, leading to later jobs failing (in fact, I am not sure whether GitHub keeps the old transient merge around at all, or discards it immediately).

3. You could recreate the merge dynamically: you only need to remember its parents. Since these are known to merge cleanly, you can then simply fetch those two from Github, and run the `git merge` directly.

**Comment by fingolfin** [comment]
Thanks to @Woodz I learned that this is a duplicate of #5882. Now, I understand that part of the problem is on the GitHub side, but I wonder what happened to contacting them? After all, this issue would affect all and every CI service, wouldn't it? This seems to be a rather serious design issue to me.

**Comment by Woodz** [comment]
It seems as though the underlying issue with GitHub pruning stale merge commits is a non-trivial change for both sides to make, so can I propose that in the meantime, Travis builds triggered by a commit that has since been removed at build checkout time are aborted with a message - "Merge commit superseded by <new git commit hash>". This will at least stop Travis from falsely passing builds from failed commits

**Comment by BanzaiMan** [comment]
I'm closing this in favor of #5882, which I've reopened.
