### ISSUE TITLE
Build badge not updating

### ISSUE THREAD

**Issue by kambrium** [travis-ci/travis-ci#9478]
![cf0ad689-bc59-466c-a812-51edc591383d](https://user-images.githubusercontent.com/11823636/38643212-bae5e200-3ddc-11e8-9b94-4f66965c6db3.png)

The text says that my build was successful but the badge does not update...

**Comment by BanzaiMan** [comment]
Try reloading the page.

**Comment by kambrium** [comment]
Thanks for the hint. It still doesn't work on my iPad but it works when I open the Travis page on another computer. Seems to be a browser caching issue. Sorry for the noise...
