### ISSUE TITLE
MacOS VM fail to install aws dependency

### ISSUE THREAD

**Issue by amitshivnani** [travis-ci/travis-ci#9480]
Hello ,

In some cases, we have seen snapshot builds on macOS VMs fail to install aws dependency.

```
// After tests run.

Install the project...

-- Install configuration: "debug"

./scripts/build_and_test.sh: line 43: aws: command not found
```

This issue should be considered as a blocker as sometimes it can delay critical release.

**Comment by ceaglest** [comment]
Hi,

To give some more context here, what is failing is the pip-install command. This only occurs on macOS VMs and never on Linux.

```
// Install phase

  Could not find a version that satisfies the requirement awscli (from versions: )

No matching distribution found for awscli
```
Eventually, we try to invoke `aws`.
```
// After tests run.

Install the project...

-- Install configuration: "debug"

./scripts/build_and_test.sh: line 43: aws: command not found
```

Best,
Chris

**Comment by cotsog** [comment]
It seems python.org sites stopped supporting TLS versions 1.0 and 1.1 and these are the versions installed on macOS 10.12 where your builds are running. See https://stackoverflow.com/a/49748494/213272.

I propose the following workarounds:

1) use our Xcode 9.3/macOS 10.13 image which has an updated TLS version. You can do this by adding `osx_image: xcode9.3` to your .travis.yml file.

2) Upgrade/install the pyopenssl package on our Xcode 9.2/macOS 10.12 image where your builds are currently running with the following in your .travis.yml file:

```
pip install pyopenssl
pip install --user awscli
```

Could you give these suggestions a try and let us know how it goes?

**Comment by sapeish** [comment]
In my case turned out to be a SSL version error which I was able to see when running the command using verbose:
`sudo pip install -vvv awscli`

The fix was to upgrade pip as this thread explains https://stackoverflow.com/questions/49768770/not-able-to-install-python-packages-ssl-tlsv1-alert-protocol-version
