### ISSUE TITLE
New build failures on OSX due to "shell_session_update: command not found"

### ISSUE THREAD

**Issue by stefanseefeld** [travis-ci/travis-ci#9486]
https://travis-ci.org/boostorg/python/jobs/365932025 fails with
`/Users/travis/.rvm/scripts/functions/support: line 57: shell_session_update: command not found`. I haven't touched the config for quite a while, so it seems this is a regression caused by some upstream change in the OSX image.

**Comment by BanzaiMan** [comment]
You are setting `errexit` option [here](https://github.com/boostorg/python/blob/24313709a78c694af4ae29116cd06ea86585aa95/.travis.yml#L69), so the first command failure halts the build.

**Comment by stefanseefeld** [comment]
Yes of course, I do want to catch errors early. But I don't think my own script contains any errors. I'm never executing `shell_session_update` myself, at least not explicitly. Rather, it's part of the travis runtime on OSX (I believe).
