### ISSUE TITLE
OSX segmentation fault with cython build

### ISSUE THREAD

**Issue by wkerzendorf** [travis-ci/travis-ci#9489]
We get a segmentation fault during the cythonizing (cython 0.27.3 and 0.28) step (see https://travis-ci.org/tardis-sn/tardis/jobs/362581597 -  https://travis-ci.org/tardis-sn/tardis/jobs/365640859). This bug is seemingly not reproducible on local machines and the @scoder (maintainer of cython) has never seen such a problem before cython/cython#2199. Has this bug happened in any other public builds on the TRAVIS machinery?

**Comment by BanzaiMan** [comment]
Could you try reproducing the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)?

**Comment by wkerzendorf** [comment]
@BanzaiMan can you enable debug build for tardis?

**Comment by BanzaiMan** [comment]
I've enabled it for tardis-sn/tardis.

**Comment by wkerzendorf** [comment]
@BanzaiMan sorry about that. yes I'm using the api now. I am however still getting an access denied. I read about the different tokens and I have generated an API token using `travis login
travis token` but still access denied. I'm probably again doing something stupid

**Comment by wkerzendorf** [comment]
that is very kind - but I also sometimes do not read the documentation that carefully. thanks for the help btw.

Now I have the problem that if one of the commands fails, I get kicked out and the machine closes and is unreachable and I have to restart the debug process. Is there a way to disable that?

**Comment by wkerzendorf** [comment]
I'm trying to do this with tmate at the moment.

**Comment by BanzaiMan** [comment]
You might be setting `errexit` option in your build. Try disabling it with `set +e`.
