### ISSUE TITLE
'WARNING! Your password will be stored unencrypted in /home/travis/.docker/config.json'

### ISSUE THREAD

**Issue by 1138-4EB** [travis-ci/travis-ci#9495]
After following [Pushing-a-Docker-Image-to-a-Registry](https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry) and [share-docker-image](https://docs.travis-ci.com/user/build-stages/share-docker-image/), images are sucessfully pushed to dockerhub, but this warning message is shown:

```
WARNING! Your password will be stored unencrypted in /home/travis/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

E.g. lines 529-531: https://travis-ci.org/1138-4EB/hwd-ide/jobs/366242954 [1138-4EB/hwd-ide#4]

Is there any suggested solution that does not require any additional external service?

**Comment by 1138-4EB** [comment]
Still relevant.

**Comment by teohhanhui** [comment]
@1138-4EB See https://github.com/docker/docker-credential-helpers/issues/102

**Comment by teohhanhui** [comment]
What manual intervention?

**Comment by teohhanhui** [comment]
You can refer to the Travis build for the docker-credential-helpers repository itself, specifically the parts related to `pass`.

**Comment by 1138-4EB** [comment]
> You can refer to the Travis build for the docker-credential-helpers repository itself, specifically the parts related to `pass`.

Do you mean https://github.com/docker/docker-credential-helpers/blob/master/.travis.yml? I don't see Docker credentials being used there, since no docker images seem to be pushed. I saw https://github.com/docker/docker-credential-helpers/blob/master/ci/before_script_linux.sh, but I don't know how does it relate to the "standard" process of encrypting the user and pass with travis' CLI.

> What manual intervention?

In https://github.com/docker/docker-credential-helpers/issues/102#issuecomment-388974092: 

> 4. Follow prompts from gpg2 utility

In https://github.com/docker/docker-credential-helpers/issues/102#issuecomment-388634452:

> 6. gpg --generate-key. Enter your name, mail, etc. You will get gpg-id like "5BB54DF1XXXXXXXXF87XXXXXXXXXXXXXX945A". Copy it to clipboard.
> 7. pass init (paste from clipboard)

**Comment by 1138-4EB** [comment]
@teohhanhui, I now understood what you meant. I though that the docker credentials had to be passed to `pass`. After a more detailed reading of the referenced your provided, I could [successfully](https://travis-ci.com/filebrowser/filebrowser/builds/80974675) set it up. Thanks a lot.

I am leaving this issue open, because I think that it would be desirable to add some example in https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry.

**Comment by 1138-4EB** [comment]
This seems to work with `dist:trusty` but not with `dist:xenial`. See https://travis-ci.community/t/docker-credential-pass-broken-on-dist-xenial/2509.
