### ISSUE TITLE
Feature request: travis CI config via package.json field

### ISSUE THREAD

**Issue by trevordmiller** [travis-ci/travis-ci#9496]
For JavaScript projects, I can configure every tool I use in my `package.json` except Travis CI (which requires a separate `.travis.yml` file). For example, eslint has the `eslintConfig` key, Jest has the `jest` key, Lint Staged has the `linted-staged` key, prettier has the `Prettier` key etc. It would be great if Travis could be configured via a `travis` key in the `package.json` as an alternative to `.travis.yml` to match other JavaScript tooling.

![image](https://user-images.githubusercontent.com/5497885/38764874-689c0ed6-3f74-11e8-9292-62268d2ef53c.png)

**Comment by BanzaiMan** [comment]
Hello.
This is a duplicate of https://github.com/travis-ci/travis-ci/issues/4653. I explain the reason that this is not going to be implemented in https://github.com/travis-ci/travis-ci/issues/4653#issuecomment-169035161.

**Comment by trevordmiller** [comment]
@BanzaiMan This is not a duplicate of #4653 - it has to do with Travis CI config, not the `engines` field :)

**Comment by BanzaiMan** [comment]
Thanks for the clarification.

The issue is something different, but I am of the opinion that we should not support it. This feature doubles the number of API calls we must make to configure a build when there is no `.travis.yml`.

I'll reopen this to solicit feedback from others, though.

**Comment by trevordmiller** [comment]
@BanzaiMan Would it be possible to only make the package.json API call if the `.travis.yml` doesn't exist? So that only one API call is made. If `.travis.yml` exists, use it, if not look for `package.json` `travis` config? Sorry if this is oversimplifying things - trying to brainstorm here to see if I can be helpful :)
