### ISSUE TITLE
Add an ability to set network interface MTU for `sudo: false` builds

### ISSUE THREAD

**Issue by slavanap** [travis-ci/travis-ci#9498]
Having this feature would be nice.
I mean `sudo ip li set mtu $MTU dev eth0` command for builds without root privileges. Sometimes MTUs < 1500 is required to reach deployment server.

Many thanks,
Vyacheslav.

**Comment by BanzaiMan** [comment]
Please try your builds with `sudo: required`. We will be consolidating our Linux infrastructures as well. https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
