### ISSUE TITLE
ANSI True Color Support in Logs

### ISSUE THREAD

**Issue by haata** [travis-ci/travis-ci#9500]
Opening new issue as there was no opportunity to keep the old one open.

https://github.com/travis-ci/travis-ci/issues/6752

Travis output logs don't seem to work with ANSI true color codes. They are particularly useful when simulating 24-bit color LED patterns in test cases (makes it easier to debug visually).

This line should have rainbow colors: https://travis-ci.org/kiibohd/controller/jobs/168983001#L859

An easy test case, which will only show in color with true color support:

``` bash
printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"
```

Details on ANSI True color support in the wild
https://gist.github.com/XVilka/8346728

A more recent commit with 24-bit color codes.
https://travis-ci.org/kiibohd/controller/jobs/365833536#L1485

**Comment by haata** [comment]
Still relevant

**Comment by haata** [comment]
Poke

**Comment by BanzaiMan** [comment]
We emulate colors by mapping escape sequences to color codes. Adding support for this many colors means bloating the app for the colors that are rarely used. As pretty as these colors might be, I am not sure if this is worth pursuing.

**Comment by haata** [comment]
I actually use these colors for unit testing, not just for pretty colors.

I'm doing x86 emulation of keyboard firmware, where each character block represents a position on a keyboard. This way I can print out each frame of a keyboard animation and show what occurred at that frame (rather than printing out an some RGB numerical value that's hard to spot or relate).

It might be possible to achieve this through an external service using the raw log file (though I'm not really aware of anything that could hook in easily to travis).

![](https://farm2.staticflickr.com/1943/44360322725_53678623dc_o.png)
![](https://farm2.staticflickr.com/1928/45222372542_df993fac6a_o.png)

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
