### ISSUE TITLE
Stale bot message is incorrect

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#9503]
Hi!

First off - thank you for addressing the backlog of stale issues - it should make it a lot easier to see the more important issues/avoid dupes/triage in the future.

However the bot's current message:
> Thanks for contributing to this issue. As it has been 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again! You can read more here: https://blog.travis-ci.com/2018-03-09-closing-old-issues

...is incorrect.

It's not possible for users without permissions on a repository to re-open issues (unless they were the ones to close it). 

As such it would be good to:
* adjust the message so it only says to file a new issue, and not about reopening
* perhaps consider increasing the time before the first message and closing the issue from 24 hours to say 72 hours, so that people have a chance to reply.

**Comment by kentfredric** [comment]
Something else to consider would be allowing the bot to re-open issues it closed if activity happens on the bug. That way all you need to do is reply ( maybe have a specific reply phrase ) and the bug gets re-opened.

**Comment by edmorley** [comment]
Bump

**Comment by edmorley** [comment]
@DrTorte, don't suppose you could take a look at this? :-)

**Comment by edmorley** [comment]
I think that would definitely help :-)

**Comment by DrTorte** [comment]
As a heads-up to anyone who runs into this thread, we're migrating over to the [Travis CI Community Forum](https://travis-ci.community/) and so, Stalebot will finally be at rest. For this repository, at least. :)
