### ISSUE TITLE
Triggering a build with a custom message fails

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#9504]
Appears as of 4 days ago, triggering a build with a custom commit message now fails. It will now complain that there is "No commit available" in the requests.

Edit: Should add this does not happen if no custom commit message is provided.

**Comment by jakirkham** [comment]
So this is kind of hard to do as we are not discussing a build log here, but a request through the UI. In fact the issue is that no build or build log is created. 😕 What would you like me to include given this?

**Comment by jakirkham** [comment]
Thoughts on this? It's really thrown us for a loop.

Managed to get it to [work manually]( https://travis-ci.org/conda-forge/staged-recipes/builds/368219541 ) via the [Trigger Build UI]( https://docs.travis-ci.com/user/web-ui#trigger-a-custom-build ), which didn't work when I raised this issue (retried several times then). We normally use [the Travis v3 API]( https://docs.travis-ci.com/user/triggering-builds/ ) in [this script]( https://github.com/conda-forge/staged-recipes/blob/e782915fb3841b2be2e1e7ab121726b8f6235c1a/.travis_scripts/trigger_travis_build.py ) to affect the same change (new build with a custom commit message), which we call [here]( https://github.com/conda-forge/staged-recipes/blob/e782915fb3841b2be2e1e7ab121726b8f6235c1a/.travis_scripts/create_feedstocks#L48 ). Though this is [getting rejected]( https://travis-ci.org/conda-forge/staged-recipes/requests?requestId=112542846 ).

Maybe that helps?

**Comment by BanzaiMan** [comment]
I don't see any request with the message "No commit available" in https://travis-ci.org/conda-forge/staged-recipes/requests. There are many rejected requests due to the "skip" message, e.g., https://github.com/conda-forge/staged-recipes/commit/7ebc476 and https://github.com/conda-forge/staged-recipes/commit/2b1e2cd.

**Comment by jakirkham** [comment]
It's hard to link to any particular request to share. How would you recommend that I do that?

**Comment by jakirkham** [comment]
Originally we had been running the build triggering script [after failure as seen here]( https://github.com/conda-forge/staged-recipes/blob/20e372d9c09aa97f6ff8b94262c64c03f79e69bb/.travis.yml#L38-L40 ). We have since [moved that call into the previous script]( https://github.com/conda-forge/staged-recipes/blob/530a9665073624e8ecf6d7d8e17f1e4f7d42981f/.travis_scripts/create_feedstocks#L48-L51 ) out of `.travis.yml` and the problem has gone away. My best guess is that Travis CI intercepted the exit code before it could run the script when we were calling it in `.travis.yml` even though it was part of the same line and even though we had `||` being used to ensure we would run the triggering script on failure of the previous script. Maybe that helps narrow down the cause further. Please let me know if that makes sense of if you have other questions.
