### ISSUE TITLE
A restarted build re-uses the same build ID

### ISSUE THREAD

**Issue by Woodz** [travis-ci/travis-ci#9505]
When restarting a build, the build ID is re-used instead of using a new build ID. This means that the previous build history is lost and artifacts are not guaranteed to be unique.

The issues that this is causing are:
- Unable to view build logs or metrics of sporadic build failures to diagnose after they have been restarted
- Email notifications are confusing, as they link to a different build (e.g. failed build notification takes you to the the latest restarted build that may now be passing)
- Publishing artifacts to Nexus releases folder fails for restarted builds when the artifact version uses the Travis build ID (e.g. `1.2.3.70875180`) because overwriting release artifacts is not allowed

I propose that when restarting a build, the build number is re-used but a new unique build ID is generated.

**Comment by BanzaiMan** [comment]
This is a variation of #2993. I'm closing this as such.
