### ISSUE TITLE
Preinstalled PHP extensions are not documented anymore

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#9506]
The doc explains how to enable pre-installed PHP extensions in https://docs.travis-ci.com/user/languages/php/#Enabling-preinstalled-PHP-extensions

But the documentation does not contain the list of pre-installed extensions anymore, making this quite hard to use.

**Comment by MaxenceDupressoir** [comment]
You can find the list on extension on the env detail pages: 
https://docs.travis-ci.com/user/reference/trusty/#PHP-images

**Comment by stof** [comment]
OK, then the missing thing is a link to this page
