### ISSUE TITLE
ld: cannot find -lpython3.5m

### ISSUE THREAD

**Issue by treussart** [travis-ci/travis-ci#9508]
When I build bro IDS, I have this issue :

```
/usr/bin/ld: cannot find -lpython3.5m
collect2: error: ld returned 1 exit status
```
I test on LXC with the same Ubuntu version and it works.

[link to the build](https://travis-ci.org/treussart/ProbeManager/jobs/366988688) line 4236

**Comment by BanzaiMan** [comment]
Looks like a variation of #6530.
