### ISSUE TITLE
Docker Windows mode: DIND image for Windows

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#9509]
When running Docker like:

    docker run microsoft/windowsservercore

I've got the error:

> age operating system "windows" cannot be used on this platform

Build: [#367698501](https://travis-ci.org/kenorb/docker-dev-env-windows/builds/367698501).

When using Docker locally, it's possible to [switch the containers to Windows](https://stackoverflow.com/q/43346580/55075). There was a similar [feature request for AWS](https://github.com/docker-library/docker/issues/49).

I'm not asking for [full Windows support](https://github.com/travis-ci/travis-ci/issues/216), but support for Docker images for Windows.

----

Related:

- [Docker Linux Containers on Windows](https://blog.docker.com/2017/09/docker-windows-server-1709/), but opposite.
- [Docker for Windows: image operating system “Linux” cannot be used on this platform](https://forums.docker.com/t/docker-for-windows-image-operating-system-linux-cannot-be-used-on-this-platform/28936)

----

If it's supported already, please guide me to the right direction.

**Comment by BanzaiMan** [comment]
Our Docker-capable infrastructure is running on GCE. If it’s not available now, I don’t think we can offer it.

**Comment by earonesty** [comment]
FYI: GCE supports windows server. https://cloud.google.com/compute/docs/instances/windows/
