### ISSUE TITLE
Provide a simpler way to encrypt variables

### ISSUE THREAD

**Issue by janisozaur** [travis-ci/travis-ci#9510]
Right now the docs make user do `gem install travis` and it should install `travis` command in user's `$PATH`. This does not work on my system and is a rather large dependency (ruby, ruby gem, gems travis depends on, travis gem).

This would be unnecessary if there was a simple option in repo's settings to encrypt variables. Right now I can only add secure variables that cannot be exported.

Alternatively, you could provide some short (oneliner?) command using gpg to encrypt the same.

**Comment by BanzaiMan** [comment]
> Right now I can only add secure variables that cannot be exported.

Is that true? The secure variables you can define in the Settings page are all exported, IIRC.

**Comment by janisozaur** [comment]
"exported" in a sense they should provide `secure: "base64=="`, but it only injects the variable into the build configuration.

**Comment by janisozaur** [comment]
https://ci.appveyor.com/tools/encrypt does this:

![selection_016](https://user-images.githubusercontent.com/550290/38919408-c86ba3f6-42f0-11e8-814a-0192de5b8034.png)
