### ISSUE TITLE
/Users/travis/.rvm/scripts/functions/support: line 57: shell_session_update: command not found

### ISSUE THREAD

**Issue by timotheecour** [travis-ci/travis-ci#9511]
travis fails with 
```
/Users/travis/.rvm/scripts/functions/support: line 57: shell_session_update: command not found
```
.travis.yml is here: https://github.com/nim-lang/Nim/blob/5492190bc63326069233a8aaf9f2e567cfc555f8/.travis.yml
example travis log here: https://travis-ci.org/nim-lang/Nim/jobs/367840604

this error is very common on the web, however I couldn't find an answer that works

* adding 

* adding `rvm get head` as suggested here https://superuser.com/questions/1044130/why-am-i-having-how-can-i-fix-this-error-shell-session-update-command-not-f results in other error:

```
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
/Users/travis/.rvm/scripts/functions/cli: line 243: return: _ret: numeric argument required
The command "rvm get head" failed and exited with 255 during .
Your build has been stopped.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found
```
(eg: https://travis-ci.org/nim-lang/Nim/jobs/367878319)

* adding `rvm get head || true` as suggested here https://github.com/travis-ci/travis-ci/issues/6522#issuecomment-251728527 also fails with 
`/Users/travis/.rvm/scripts/functions/support: line 57: shell_session_update: command not found`

* removing `set -e` from .travis.yml is not an option as I don't want to silently ignore errors, as also explained by others here https://github.com/travis-ci/travis-ci/issues/6522#issuecomment-251247411
> @BanzaiMan - that is intentional. I need to halt the build on errors in my scripts. I agree with you that without that set -e the build would continue past the shell_session_update error, but I can't let other errors happen silently so I need the set -e. I worked around this by doing Project-OSRM/node-osrm@cdb5b6c and now builds are working fine.

This error seems to affect pretty much every project that uses `-e` since at least 2015. How do we fix this?

## related:

https://github.com/travis-ci/travis-ci/issues/9486
https://github.com/travis-ci/travis-ci/issues/6522

**Comment by timotheecour** [comment]
why was this closed?

**Comment by acnagy** [comment]
I think stalebot is running amok.. let's def reopen. AFAIK there isn't someone working on this specifically, but I'll see what I can do about raising it with people who might be able to!

**Comment by timotheecour** [comment]
great! a simple search for this issue reveals this problem is widespread and has been going on since at least april:
https://github.com/search?q=%22shell_session_update%3A+command+not+found%22&type=Issues shows 283 issues, 
it's causing a lot of overhead in finding workardounds for people using travis

**Comment by ThomasWaldmann** [comment]
https://travis-ci.org/borgbackup/borg/jobs/401269432

this job worked some months ago and now is broken due to a `shell_session_update` issue.

i restarted the job to verify whether travis works because a current pull request was strangely failing due to reasons unrelated to the changes in the PR.

so, is there something broken on travis ci and can it please get fixed?

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/1591 attempts to fix the warning. The warning _might be_ negligible (or not in other cases), but the use of `errexit` option causes the build to halt immediately.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
