### ISSUE TITLE
apt-get install failed, Java 8

### ISSUE THREAD

**Issue by tipsy** [travis-ci/travis-ci#9512]
I have a very simple `.travis.yml` for one of my projects: 

```yml
language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
```

Builds are failing now because Travis can't seem to download Java (getting a 404 in logs).

**Comment by cotsog** [comment]
Sorry for the troubles!

I believe this is unfortunately out of our control. A change probably happened at the webupd8 PPA level or on the Oracle Java download site. Sorry for the inconvenience.

In the meantime, I could find the following workaround which involves patching the installer:

```
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update

  - sudo apt-get install -y oracle-java8-installer || true

  #todo remove this kludge and the above || true when the ppa is fixed
  - cd /var/lib/dpkg/info
  - sudo sed -i 's|JAVA_VERSION=8u161|JAVA_VERSION=8u172|' oracle-java8-installer.*
  - sudo sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/|' oracle-java8-installer.*
  - sudo sed -i 's|SHA256SUM_TGZ="6dbc56a0e3310b69e91bb64db63a485bd7b6a8083f08e48047276380a0e2021e"|SHA256SUM_TGZ="28a00b9400b6913563553e09e8024c286b506d8523334c93ddec6c9ec7e9d346"|' oracle-java8-installer.*
  - sudo sed -i 's|J_DIR=jdk1.8.0_161|J_DIR=jdk1.8.0_172|' oracle-java8-installer.*
  - sudo apt-get update

  - sudo apt-get install -y oracle-java8-installer
```

See https://ubuntuforums.org/showthread.php?t=2374686&page=5&p=13757585#post13757585.

Could you try this out and let me know if this works?

**Comment by cotsog** [comment]
I forgot to mention that you'll also need to remove the following from your .travis.yml file:

```yaml
addons:
  apt:
    packages:
      - oracle-java8-installer
```

**Comment by npetzall** [comment]
oracle-java8-installer was updated 10 hrs ago, and it seems to be working now.

**Comment by tipsy** [comment]
Builds are working again!

**Comment by rupav** [comment]
Builds are failing today, have an install command for `oracle-java8-installer` in installation script, which when run on travis build, returns 404 and non zero exit status, and fails the build.

**Comment by rupav** [comment]
Update: As mentioned by @npetzall back in April, its working fine now in July 😅 ... without any need to change code/installation steps.

**Comment by npetzall** [comment]
Yepp, Oracle-Java8-installer updated about 36 minutes ago. I wish oracle would stop moving stuff around.

**Comment by fewknow** [comment]
This is failing again today.

**Comment by cotsog** [comment]
@fewknow sorry to hear this is happening again! Could you post a link/URL to a build showing the problem? If it's for a private repository, please send it over at support [at] travis-ci [dot] com. Thanks!

**Comment by kevinfodness** [comment]
@cotsog - this is happening for us as well - this is the failing PR: https://github.com/alleyinteractive/searchpress/pull/103

**Comment by fewknow** [comment]
@cotsog this isn't a travis-ci issue.  I am seeing this with my ansible builds.    Just started about 3pm EST today.   I am reverting my builds back to ubuntu 14 to see if I can get past the issue.

**Comment by BanzaiMan** [comment]
There is a new #10247, but it's the same story. Oracle appears to have moved the archive.
