### ISSUE TITLE
Where does your documentation sanction "s3.amazonaws.com/travis-python-archives"?

### ISSUE THREAD

**Issue by gvanrossum** [travis-ci/travis-ci#9514]
(See mini-thread starting at https://github.com/python/typeshed/pull/2062#pullrequestreview-113062322.) We have a `.travis.yml` file containing [this gem](https://github.com/python/typeshed/blob/5223b26ec8121d5b28556e704714059ecd3d3125/.travis.yml#L20):
```
wget https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.6.tar.bz2; sudo tar xjf python-3.6.tar.bz2 --directory /
```
IIUC that downloads a tarball from the internet and extracts it under `/`, as root. Now I don't know much about S3, so there may be a way to find out who controls that directory, and hopefully it's owned by Travis-CI and tightly controlled, but I am still a bit worried, since I can't find that URL mentioned in any of the documentation on docs.travis-ci.org -- it just seems something that people copy blindly from other projects, and who knows whether some clever hacker hasn't long ago taken control of it. Of course it's running in a VM, so maybe I'm being paranoid. But it would be nice if I could find it in the docs somewhere to put my mind at peace.

**Comment by BanzaiMan** [comment]
Hello there. The archive is built by https://github.com/travis-ci/cpython-builder, using [python-build](https://github.com/pyenv/pyenv/tree/master/plugins/python-build). I will think about documenting this (and other language run times) more clearly.
