### ISSUE TITLE
APT whitelist request for libpng16-dev

### ISSUE THREAD

**Issue by flexdinesh** [travis-ci/travis-ci#9515]
This dependency is required for `image-webpack-loader`v4.0.0 and above in trusty containers

**Comment by bobbybouwmann** [comment]
What is the status of this request? Anything that runs node 10 will fail now!

**Comment by BanzaiMan** [comment]
Hello, there. For adding packages to the list, please refer to https://github.com/travis-ci/apt-package-safelist.

Thanks.
