### ISSUE TITLE
Clarify docs around using include + allow_failures

### ISSUE THREAD

**Issue by relsqui** [travis-ci/travis-ci#9518]
When I was trying to allow some included build jobs to fail, I read this section: https://docs.travis-ci.com/user/customizing-the-build#Matching-Jobs-with-allow_failures and was expecting simply copying the `include`d jobs into `allow_failures` not to work, specifically because of this line:

> all the keys in `allow_failures` element must exist in the top level of the build matrix (i.e., not in `matrix.include`)

This appears not to be the case, since I did it anyway and it worked.

I'm not sure if I misunderstood what that line means, or if the documentation is out of date. Either way, I'd be happy to write you a PR to update it, but I want to make sure I know what's correct first! Is it now true that keys in `include` can be used for `allow_failures`, when it wasn't previously? Or does `matrix.include` just mean something else in that sentence?

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by relsqui** [comment]
Not reporting a problem, just checking a spec before making a docs PR. :)

**Comment by BanzaiMan** [comment]
Could you clarify this, then?

> This appears not to be the case, since I did it anyway and it worked.

Can you share the configuration that you think (the document says) shouldn't work but did?

**Comment by relsqui** [comment]
Sure. Since it's for a private repo, should I close this and take it to email? Or can I just email the snippet and leave the docs question open?
