### ISSUE TITLE
Attempting to sign in to travis-ci.org gives "state mismatch" from /auth/handshake endpoint

### ISSUE THREAD

**Issue by Nightfirecat** [travis-ci/travis-ci#9519]
When attempting to sign in to travis-ci.org from Firefox 59.0.2 with some privacy/security addons and settings installed (uBlock Origin, uMatrix, some about:config settings changed), the sign in process fails after granting Travis OAuth access permissions in GitHub and being redirected back to https://api.travis-ci.org/auth/handshake?code=xxxxx&state=xxxxx%3A%3A%3Ahttps%3A%2F%2Ftravis-ci.org%2F. I specifically receive an HTTP 400 response from that endpoint with a body of "state mismatch" rather than the `Content-Type: application/json` which is given in the response headers.

I am admittedly able to access Travis via Tor, so this could be a configuration issue in my browser. I'm trying to figure out why this would not work when I'm able to access other sites without issue. I'm happy to provide more details as needed.

**Comment by Nightfirecat** [comment]
And all of a sudden, it's magically working for me again. :upside_down_face:

**Comment by anishkny** [comment]
This is happening again for me 😿

**Comment by Geobert** [comment]
I have this issue as well at home, firefox nightly

**Comment by Geobert** [comment]
After a refresh, it's working again

**Comment by aleshh** [comment]
Got this error trying to log into Travis the first time. Trying again in an incognito window worked, although for now I still can't log in on a regular browser window.

**Comment by mcaskill** [comment]
I have been having this issue for a while with Firefox Developer Edition.
I've tried with all add-ons disabled but no luck.
It does work in a private window.

**Comment by CarliJoy** [comment]
Could it be, that the new Container Format plays you a trick here?
You need to have github and travi-ci in the same container...
