### ISSUE TITLE
environment variables set globally not showing up in deployment

### ISSUE THREAD

**Issue by cjw296** [travis-ci/travis-ci#9522]
Here's the yaml:

https://github.com/Simplistix/picky-conda/blob/945d74d7e1e6afb8f127115fb9f87286f64c0459/.travis.yml

Here's the job:

https://travis-ci.org/Simplistix/picky-conda/jobs/369038174

[$PROJECT_NAME](https://github.com/Simplistix/picky-conda/blob/945d74d7e1e6afb8f127115fb9f87286f64c0459/.travis.yml#L10) is empty by the time we get [here](https://travis-ci.org/Simplistix/picky-conda/jobs/369038174#L1933) and so I get [this failure](https://travis-ci.org/Simplistix/picky-conda/jobs/369038174#L2243).

How can I get the release stage to use the global env vars in the same way as the other stages?

**Comment by BanzaiMan** [comment]
How is it supposed to be set? You are exporting it (https://travis-ci.org/Simplistix/picky-conda/jobs/369038174#L1933), but it's empty.

**Comment by cjw296** [comment]
It is set here: https://github.com/Simplistix/picky-conda/blob/945d74d7e1e6afb8f127115fb9f87286f64c0459/.travis.yml#L10

**Comment by cjw296** [comment]
nevermind, just me being an idiot. PROJECT_NAME != PACKAGE_NAME :'(
