### ISSUE TITLE
`python3 -m venv ve`-> pip is not accessible in virtualenv

### ISSUE THREAD

**Issue by nikolas** [travis-ci/travis-ci#9524]
Expected behavior:

```
$ python3 -m venv ve
$ ./ve/bin/pip install whatever
```

This works in all cases I've tried outside of travis.

However, on travis, the `pip` utility isn't accessibly at `./ve/bin/pip`.
See: https://travis-ci.org/ccnmtl/econplayground/builds/369281472

The pip utility should be accessible in the virtualenv, as that's standard in python3. https://docs.python.org/3/library/venv.html

**Comment by BanzaiMan** [comment]
`python3` is not the one that is configured by virtualenv, so I think this is expected. https://docs.travis-ci.com/user/languages/python#Travis-CI-Uses-Isolated-virtualenvs

I suspect `python3` is coming from the Ubuntu package.

Try calling `python` instead.
