### ISSUE TITLE
stop hiding restart buttons in mobile UI

### ISSUE THREAD

**Issue by jab** [travis-ci/travis-ci#9526]
Occasionally a test will fail with a transient error. If you find out about this when you're not in front of a computer, e.g. by getting a "Broken build" email from builds@travis-ci.org on your phone, it would be really nice if you could click through the build link in the email and then hit the "restart" button while on the go, to minimize the time that your project is showing off the big red "build failing" badge. But currently you can't because Travis's mobile web UI hides the "restart job" and "restart build" buttons. D'oh! Could you please stop hiding these buttons in your mobile UI? Thanks for your consideration.

**Comment by jab** [comment]
Just hit this again. One of the 13 jobs in the latest build of [my project](https://travis-ci.org/jab/bidict) got no output for 10 minutes due to some bogus reasons on Travis’s end (I changed nothing since the previous successful build — this was a CRON) build, and now my project has been flaunting a broken build badge and I have no way to click retry just because I only have access to a phone right now. 

This is so frustrating and needlessly limiting. Please please please fix this. I imagine it couldn’t be much effort and would vastly improve the UX.

**Comment by jab** [comment]
Just got back to a computer where I was able to hit restart on [the job](https://travis-ci.org/jab/bidict/jobs/409200951) and it completed successfully. But now [all 13 jobs in the build](https://travis-ci.org/jab/bidict/builds/409200939) show as passing but the status badge shows the gray "build canceled" status, which is inconsistent and incorrect. Should I file a separate issue for this ("overall build status incorrectly shows 'canceled' when all jobs passed")?

![screen shot 2018-07-28 at 15 32 08](https://user-images.githubusercontent.com/64992/43359980-6ea056d4-927b-11e8-8731-9c5a02a1e4de.png)

**Comment by jab** [comment]
This is still an issue.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
