### ISSUE TITLE
show job log by default on mobile + graceful error recovery

### ISSUE THREAD

**Issue by jab** [travis-ci/travis-ci#9527]
When viewing a job in the mobile web UI, unlike on desktop, the log is hidden by default until you click the "view log" button. And when you then hit the "view log" button on mobile and fetching the log fails for some reason, there's no "try again" button.

Every single time I've ever viewed this page on mobile, I've wanted to view the log. I would guess that the same is true for many of your other users.

Would you please consider showing the log by default, to save your mobile users from the annoying extra click? And could you please add a "try again" button when fetching the log fails?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
