### ISSUE TITLE
FTP upload from tracis-ci instance hangs at MLSD command

### ISSUE THREAD

**Issue by mirkosertic** [travis-ci/travis-ci#9529]
I am trying to upload files from travis-ci to my hosting providers ftp server. This upload worked for the past year, but I recently noticed that it is failing.

See build https://travis-ci.org/mirkosertic/www_mirkosertic_de/builds/369712930

After switching to passive mode, the FTP uploads hangs after sending the MLSD command to the server. This causes a timeout, and the build fails. I think that this is a travis-ci related problem. Running the build on my local machine against the same FTP server works like a charm. I also tested different ftp clients like lftp or ncftp. Both of them running in a timeout.

Any ideas about how to fix this?

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/9732#issuecomment-419108078
