### ISSUE TITLE
Deploying to GH Pages failing because of Rate Limit?

### ISSUE THREAD

**Issue by reiinakano** [travis-ci/travis-ci#9530]
Please refer to the following build: https://travis-ci.org/reiinakano/tfjs-lstm-text-generation/builds/369759664
I am unsure what is wrong as I've done this multiple times before. I've even regenerated a new token in case that was the problem, but the error persists.

**Comment by BanzaiMan** [comment]
That ID definitely belongs to you. https://api.github.com/user/18363734

I believe that the rate limit applies to all of your API requests, so you'd have to check for other uses (not just Travis) and try again at a later time. I think you get 5000 requests per hour.

If you can't find out where those requests are coming from, perhaps GitHub support can help you.

**Comment by reiinakano** [comment]
It's fine now. I have no idea where the rate limiting came from though. I don't think I've even reached 5000 requests total!
