### ISSUE TITLE
How to collect artifacts since PyPI upload is broken ?

### ISSUE THREAD

**Issue by T4mmi** [travis-ci/travis-ci#9531]
Hi all,

I'm trying to wrap an [ITK module for Python](https://github.com/T4mmi/ITKBinaryThinningImageFilter3D).
In the [documentation](http://itkpythonpackage.readthedocs.io/en/latest/Build_ITK_Module_Python_packages.html) they state that :

> wheels can be downloaded by going to the transfer.sh link found in the build output

However I cannot manage to find any DL link in the [build logs](https://travis-ci.org/T4mmi/ITKBinaryThinningImageFilter3D) and since the [PyPI artifacts upload seems broken](https://github.com/travis-ci/travis-ci/issues/9303) ATM I'm pretty stuck to deploy my module for macOS...

**Comment by ssbarnea** [comment]
@T4mmi I am wondering how long it will take to fix travis which apparently fails to upgrade pip due to non root permissions. See https://travis-ci.com/pycontribs/jira/jobs/133196517

Still using non-root is advised and as far as I know, it should not be needed for uploading data.
