### ISSUE TITLE
Improve error message when there's an error in the .travis.yml

### ISSUE THREAD

**Issue by idgserpro** [travis-ci/travis-ci#9538]
In a [PR we were working on](https://github.com/collective/collective.folderorder/pull/7), we got "Expected - Waiting for status to be reported" and couldn't identify the problem. After triggering a custom build in Travis itself, we discovered a new url `/requests`, which showed `Could not parse .travis.yml` and we could fix it. If possible (don't know github internals about integrating external services), it would be nice to have this message in the PR instead of "Waiting for status to be reported".

Is there an ETA for https://travis-ci.org/collective/collective.folderorder/requests being available as default instead of only appearing after triggering a custom build in Travis?

**Comment by sirex** [comment]
Message `Could not parse .travis.yml` also don't tell much.

**Comment by BanzaiMan** [comment]
We are working on better `.travis.yml` validator. https://github.com/travis-ci/travis-yml Not sure yet when it will be rolled into production, but it is coming.

**Comment by idgserpro** [comment]
@BanzaiMan @DrTorte has this been fixed? What was the solution?

**Comment by DrTorte** [comment]
@idgserpro Sorry about that, I should have left a link to the [Community forum](https://travis-ci.community). As it is right now, we're working on it, but there are some other projects that are ahead of it. It is however, if I'm not totally mistaken, planned for early 2019 as part of the CLI upgrade. I could be wrong, though, but we'll post updates when we can. 😄
