### ISSUE TITLE
rrutter devtools broken with R 3.5

### ISSUE THREAD

**Issue by jpritikin** [travis-ci/travis-ci#9540]
@craigcitro @jimhester Travis currently uses `sudo add-apt-repository -y "ppa:marutter/rrutter"` Would it help to switch to the in-progress ppa for R 3.5? https://launchpad.net/~marutter/+archive/ubuntu/rrutter3.5

**Comment by schloerke** [comment]
Link to a failing log: https://travis-ci.org/rstudio/leaflet/jobs/371332840#L1530

**Comment by jimhester** [comment]
From the PPA landing page

> NOT CURRENTLY WORKING. EFFORTS CURRENTLY UNDER WAY.

So switching to it now seems pre-mature, but once this is working sure we can switch to it for 3.5+.

I sent a PR to disable use of the binary version of devtools for all versions as a temporary fix https://github.com/travis-ci/travis-build/pull/1360.

In the meantime you can use `r_packages: devtools` to install devtools from source.

**Comment by isteves** [comment]
I'm getting a [Travis error](https://travis-ci.org/NCEAS/arcticdatautils/builds/375100225) on `R: release` and `R: devel` but _not_ `R: oldrel`: 

>E: Unable to locate package r-cran-ncdf4
apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install librdf0-dev libnetcdf-dev r-cran-ncdf4" failed and exited with 100 during .

...it seems like it might be somewhat related?  Would `r_packages: ncdf4` also be a workaround in this case?
