### ISSUE TITLE
Problem measuring build times when system time is changed

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#9541]
On a Linux Mint 18.3 Live USB, changing the time from an hour before to the one shown in the screenshot the build says it's been running for over an hour even though the commit was made about 10 minutes earlier
![screenshot from 2018-04-26 09-29-43](https://user-images.githubusercontent.com/20478546/39294849-509824d4-492c-11e8-9ae7-4b860523d29c.png)

**Comment by Monkeyboy2805** [comment]
No response so I would still consider this issue "unstale". Hopefully that's a word and I haven't just made it up :P

**Comment by Monkeyboy2805** [comment]
Not solved

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
