### ISSUE TITLE
Support for pypy/pypy3 v6.0+ python

### ISSUE THREAD

**Issue by webknjaz** [travis-ci/travis-ci#9542]
It's been released just today: https://morepypy.blogspot.cz/2018/04/pypy27-and-pypy35-v60-dual-release.html

Ref: #9206
/cc: @BanzaiMan

**Comment by Juanlu001** [comment]
I came here to open the same issue and would be glad to test what it seems to be the most powerful and exciting PyPy version to date :)

**Comment by webknjaz** [comment]
Is it there yet?

**Comment by fishilico** [comment]
I am also interested in getting pypy/pypy3 v6.0+ at least in Xenial templates. Right now  https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/16.04/x86_64/pypy3.5.tar.bz2 contains `/opt/python/pypy3.5-5.10.1/`. For Trusty, https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/pypy2.7.tar.bz2 contains `/opt/python/pypy2.7-5.10.0` and https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/pypy3.5.tar.bz2 contains `/opt/python/pypy3.5-5.10.1/` too (pypy2.7 seems not to be available on Xenial?).

What are the plans on upgrading pypy to v6.0?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by webknjaz** [comment]
Submitted as https://travis-ci.community/t/support-for-pypy-pypy3-v6-0-python/1249

**Comment by webknjaz** [comment]
UPD: it works with xenial if you specify 6.0 explicitly: https://github.com/cherrypy/cheroot/commit/cfee0e13e660f4f67a37c1928a737dd9ccc05fec

**Comment by webknjaz** [comment]
Sure, I just wanted to be explicit during the switch. I've already started this migration as well :)
