### ISSUE TITLE
Sorry, it seems like we couldn't find any repositories you have access to on GitHub.

### ISSUE THREAD

**Issue by LukeCaruzo** [travis-ci/travis-ci#9546]
I wanted to link my repository with travis ci, but there are no public repositories shown.

It might need to be synced manually?

**Comment by JohnVonNeumann** [comment]
I've just encountered this after transferring a repository to an organisation, build status went unknown, as you'd expect but Travis says I don't have access to any Organisation repositories.

**Comment by BanzaiMan** [comment]
Are you experiencing this issue on https://travis-ci.org or https://travis-ci.com? Which page are you looking at, and what repositories are missing?

**Comment by LukeCaruzo** [comment]
.org and my repository 2048 is missing. (https://github.com/LukeCaruzo/2048)

**Comment by BanzaiMan** [comment]
@LukeCaruzo Could you attach a screenshot, please?

**Comment by LukeCaruzo** [comment]
![img_20180427_150338](https://user-images.githubusercontent.com/23531489/39363924-5296134e-4a2c-11e8-986f-70c74a8f1877.png)

**Comment by BanzaiMan** [comment]
We had a problem with sync earlier. We've pushed a fix; could you try resyncing and see if the repos become visible again?

**Comment by BanzaiMan** [comment]
Great to hear! @JohnVonNeumann How about you?
