### ISSUE TITLE
Travis CI neither shows the private repos I have push access nor the forks of them.

### ISSUE THREAD

**Issue by cacik** [travis-ci/travis-ci#9554]
As stated in the title, Travis CI doesn't sync&list the private repos, the owner of which invited me to collaborate.

**Comment by BanzaiMan** [comment]
Are you looking at https://travis-vu.com?

**Comment by yadkit** [comment]
@BanzaiMan Yes. But it works for forks now. I think there was a delay in sync. However I still can't see the private repos I have push access. Just forks of them.

**Comment by rkh** [comment]
Could you email support@travis-ci.com, and include the link to the repo you're expecting to see but can't?
