### ISSUE TITLE
Tagged build is not triggering deployment due to unmet branch condition

### ISSUE THREAD

**Issue by kenman345** [travis-ci/travis-ci#9557]
So I am running Travis-CI with the beta stages feature and its been working well except recently. I made a change to add in that the job that runs our deploys can also work when we run a cron job once a week since it deploys our site which should always be ready to deploy.

So I made the following change (and a follow-up commit just to fix the spacing of course):
acceptbitcoincash/acceptbitcoincash@0d4bf19#diff-354f30a63fb0907d4ad57269548329e3L41

It worked well when I had set up my cron job and I was happy to get the 4-25-2018 tagged docker container that appeared here: https://hub.docker.com/r/acceptbitcoincash/acceptbitcoincash/tags/

Today I went to tag the repository, which under normal circumstances will force a build of the docker container and then a tag of the current date, and deploy to docker hub.

The tag build started but then failed to identify that variable should change. Okay, my fault I thought. So I went ahead and fixed it to force it to go into the path I wanted.

Well, that did not work. Instead, I got the following message with my build:
https://travis-ci.org/acceptbitcoincash/acceptbitcoincash/jobs/373295617#L704

What is not permitted about? My only condition for that deploy to go is that its got that variable changed. That was most certainly the case on my four attempts where I got variations of that message.

**Comment by kenman345** [comment]
I had a second comment in this issue but it was closed as it was not in this repo: https://github.com/travis-ci/beta-features/issues/51

**Comment by kenman345** [comment]
its been 6 days, no one can help?

**Comment by kenman345** [comment]
@cotsog you recommended coming here to ask my question about this behavior and I have not had so much as a single comment asking for further information or help to set up a reproduced scenario to debug further. I would really like to get this issue fixed as it affects our teams workflow.

**Comment by cotsog** [comment]
Hey @kenman345, so sorry for the delay here!

Looking at your build log, it seems that `$NEXT_BUILD_TAG` is equal to `latest` (see [here](https://travis-ci.org/acceptbitcoincash/acceptbitcoincash/jobs/373295617#L484)) which means that the condition in your `deploy:` section isn't satisfied i.e.

```yaml
      deploy:
      - provider: script
        ⋮
        on: 
          condition: $NEXT_BUILD_TAG != "latest"
```

I agree that the message about the branch is confusing though. Could you try to trigger a build where `$NEXT_BUILD_TAG` is not equal to `latest`?

Thanks!

**Comment by kenman345** [comment]
Note the following:

(from Lines 648 and 649)[https://travis-ci.org/acceptbitcoincash/acceptbitcoincash/jobs/373295617#L648-L649]
```bash
$ echo $NEXT_BUILD_TAG
05-01-2018
```

**Comment by kenman345** [comment]
Also, The [line 704](https://travis-ci.org/acceptbitcoincash/acceptbitcoincash/jobs/373295617#L704) text contains this odd wording: 
```bash
Skipping a deployment with the script provider because this branch is not permitted
```

**Comment by cotsog** [comment]
@kenman345 Sorry for missing this line is your build. Indeed, it look like the condition was met and it should have triggered a deployment.

I'm wondering if your condition in the `Run build` stage could be at play i.e.

```yaml
if: type IN (push, cron) AND (branch = master OR tag IS present)
```

I'm not sure we are supporting these compound statements yet.


Could you try to change it to the following:

```yaml
if: type IN (push, cron)
```

and move the other part in your `deploy:` configs?

Here's a PR that shows you what I mean: https://github.com/acceptbitcoincash/acceptbitcoincash/pull/939.

Let me know if this does what you want.

Thanks again!

**Comment by kenman345** [comment]
read the part about compounding condition. Shouldnt my condition be run as a bash `if` statement? so I do not understand why this would be a problem.

**Comment by kenman345** [comment]
Also note, that when you have a tag, apparently thats not considered master branch, so that is why I needed to check for Tag is present OR for master branch.

**Comment by BanzaiMan** [comment]
@kenman345 Do you have a previous tag build that ran a deployment successfully?

**Comment by kenman345** [comment]
@BanzaiMan here is the last time we tagged before making the changes I noted to include cron jobs as part of the available options for the Docker deployment builds https://travis-ci.org/acceptbitcoincash/acceptbitcoincash/jobs/367961591

**Comment by BanzaiMan** [comment]
Thanks for the info. That build was correctly configured, indeed. Do you have a build log that skipped the deployment in a similar way as https://travis-ci.org/acceptbitcoincash/acceptbitcoincash/jobs/373295617#L704, but more recent? I would like to make sure that the code we need to examine is most up to date. If there isn't any, is it possible to push another tag?

Thanks.

**Comment by kenman345** [comment]
as I went through I had to adjust to try and get it to work before I gave up and contacted you guys.

If you want I can help set up a confirguration so you can test yourself on your own fork of the repo.

**Comment by kenman345** [comment]
I tagged our repository as it needed to be tagged for a release and the `cron` job had run earlier to make the actual build from the same commit. Here is the skipped deploy build logs from today when I tagged: https://travis-ci.org/acceptbitcoincash/acceptbitcoincash/jobs/376170143

**Comment by BanzaiMan** [comment]
Thanks for the logs.

This is a tagged build, so it is trying to match the branch condition, so it is checking against the `master` branch. This is implicitly mentioned in https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A, but not very clear. This can definitely be improved.

For your use case, what I believe you want is adding one more condition; e.g.,

```yaml
deploy:
  - provider: script
    skip-cleanup: true
    script:
    # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push acceptbitcoincash/acceptbitcoincash
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push acceptbitcoincash/acceptbitcoincash
    on: 
      condition: $NEXT_BUILD_TAG != "latest"
      all_branches: true # <== new!
```

**Comment by BanzaiMan** [comment]
I changed the issue's description to match the issue better, since this is not about Build Stages.
