### ISSUE TITLE
RVM's available rubies are out-of-date/incomplete

### ISSUE THREAD

**Issue by chocolateboy** [travis-ci/travis-ci#9559]
`rvm use 2.x` is supposed to use the latest version of 2.x e.g.:

    $ rvm use 2.4

should [currently](https://travis-ci.org/chocolateboy/methodfinder/jobs/373635428#L484) be equivalent to:

    $ rvm use 2.4.4

Instead, it's [using 2.4.1](https://travis-ci.org/chocolateboy/methodfinder/jobs/373635428#L416):

```
$ rvm alias create 2.4 ruby-2.4.1
$ rvm use 2.4

Using /home/travis/.rvm/gems/ruby-2.4.1
```

\- even though precompiled 2.4.4 is available in [almost every build environment](http://rubies.travis-ci.org/).

---

Although RVM itself is [up-to-date](https://travis-ci.org/chocolateboy/methodfinder/jobs/373634180#L478) (1.29.3), its list of available rubies isn't. Here's a section of the list of MRI rubies before and after the list is updated (with `rvm get master`):

### Before

* [ruby-]2.3[.4]
* [ruby-]2.4[.1]
* ruby-head

### After

* [ruby-]2.3[.7]
* [ruby-]2.4[.4]
* [ruby-]2.5[.1]
* [ruby-]2.6[.0-preview1]
* ruby-head

**Comment by swrobel** [comment]
Why is this the case? It's very frustrating to have to manually bump patchlevels when new rubies come out.

**Comment by BanzaiMan** [comment]
Build images need an update with newer versions. Sorry about the delay.
