### ISSUE TITLE
node-sass build fail

### ISSUE THREAD

**Issue by njleonzhang** [travis-ci/travis-ci#9561]
please check the log

https://travis-ci.org/njleonzhang/vue-data-tables/builds/371370409

**Comment by BanzaiMan** [comment]
Could you try reproducing the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)?

**Comment by njleonzhang** [comment]
Sorry, I am not familiar with docker. Do I need provide you something if I can reproduce the issue?
The build can pass for long time and failed recently.

**Comment by BanzaiMan** [comment]
@njleonzhang If it had been running fine before, my first guess is that the underlying libraries your application uses changed, and the changes are causing problems. https://docs.travis-ci.com/user/common-build-problems/#My-tests-broke-but-were-working-yesterday I would start by comparing the build logs, and identifying which libraries changed.

**Comment by BanzaiMan** [comment]
I'm sorry, but I don't know enough about your code to advise you. We can enable the debug feature, so you can troubleshoot further. If you are interested, please email us at support@travis-ci.com. Thanks.

**Comment by njleonzhang** [comment]
@BanzaiMan I'd like leave the debug job to your team, it seems something related to the travis online environment. Tnx and wait for your analysis

**Comment by njleonzhang** [comment]
@BanzaiMan any update.

**Comment by BanzaiMan** [comment]
I'm sorry, but I don't know enough about your code to advise you. We can enable the debug feature, so you can troubleshoot further. If you are interested, please email us at support@travis-ci.com. Thanks.

**Comment by ReneCode** [comment]
Today I've the same issue.

     error /home/travis/build/..../node_modules/node-sass: Command failed.


changes in travis.yml: 
 
    env: SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

did not help.

What would be a solution ?

**Comment by njleonzhang** [comment]
@BanzaiMan send email, and you can get help

**Comment by ReneCode** [comment]
The travis support gave me the right hint. Thank you.

node-sass currently does not work with node version 12.
https://github.com/sass/node-sass/issues/2632

so switch to version 11 in the travis.yml file:

     node_js: 11.10.0

**Comment by strudra** [comment]
> The travis support gave me the right hint. Thank you.
> 
> node-sass currently does not work with node version 12.
> [sass/node-sass#2632](https://github.com/sass/node-sass/issues/2632)
> 
> so switch to version 11 in the travis.yml file:
> 
> ```
>  node_js: 11.10.0
> ```

This one fixed it for me. Thanks!
