### ISSUE TITLE
wrong build status reported (build passed == build errored)

### ISSUE THREAD

**Issue by slodki** [travis-ci/travis-ci#9563]
Status displayed at history web page:
![travis1](https://user-images.githubusercontent.com/3155552/39547037-a9ee0f74-4e56-11e8-8d55-869d1ff15130.png)

Status displayed when clicked on build link:
![travis2](https://user-images.githubusercontent.com/3155552/39547044-aeda4fc0-4e56-11e8-8555-df460c9096bf.png)

https://travis-ci.org/slodki/moneymanagerex/builds/374116100

**Comment by BanzaiMan** [comment]
There is only one job defined in the build, and it is allowed to fail. The job that is executed did indeed fail. https://travis-ci.org/slodki/moneymanagerex/jobs/374116101

In your configuration, you are defining both `matrix` and `jobs`, and the latter overrides the former. https://github.com/slodki/moneymanagerex/blob/65311e26a84a6e8e9a532bb754420d4846c3264d/.travis.yml#L92-L97

**Comment by BanzaiMan** [comment]
The discrepancy needs to be addressed.

**Comment by slodki** [comment]
unstale

**Comment by slodki** [comment]
Unstale

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
