### ISSUE TITLE
D: Travis can't download 'gdc-6.3.0'

### ISSUE THREAD

**Issue by Abscissa** [travis-ci/travis-ci#9566]
Bugs don't magically fix themselves on their own, therefore #8849 should not have been auto-closed. Re-posting the issue (which is still occurring) because GitHub won't let me re-open the original issue (because, after all, how could an unfixed issue possibly NOT fix itself on its own after X amount of time!).

Using `d: gdc-6.3.0` results in:

```
$ source "$(CURL_USER_AGENT="$CURL_USER_AGENT" bash install.sh gdc-6.3.0 --activate)"
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
tar (child): /home/travis/dlang/.installer_tmp_5tBLPl/vLXS5j/gdc-6.3.0.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/home/travis/.travis/job_stages: line 57: : No such file or directory
The command "source "$(CURL_USER_AGENT="$CURL_USER_AGENT" bash install.sh gdc-6.3.0 --activate)"" failed and exited with 1 during .
```

GDC's [download page](https://gdcproject.org/downloads) reports that v6.3.0 exists. And [a tool of mine](https://semitwist.com/travis-d-compilers#gdc) detected that gdc had once resolved to v6.3.0 for a few days beginning on 2016-Dec-22.

For this to be legitimately closed (ie, no thanks for not helping, stale^H^H^H^H^Hsweep-unfixed-issues-under-the-rug bot), one of two things needs to occur:

Either:

1. `gdc-6.3.0` should work. Or:
2. Receive confirmation that `gdc-6.3.0` *shouldn't* work.

Ping @MartinNowak @klickverbot @ibuclaw

**Comment by Abscissa** [comment]
Apparently, this issue's list of people to ping is out of date, therefore adding ping to @wilzbach (Don't know of a way to un-ping klickverbot and ibuclaw)

**Comment by wilzbach** [comment]
Check https://github.com/dlang/installer/pull/251
Not much I can do about this. Sorry.

**Comment by Abscissa** [comment]
On 05/31/2018 03:20 AM, Sebastian Wilzbach wrote:
> Check https://github.com/dlang/installer/pull/251
> Not much I can do about this. Sorry.
> 

Understood. It's not urgent, just wasn't sure what was going on with it. 
Figured it might need a tad bit of attention.

**Comment by Abscissa** [comment]
stop it, stalebot

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
