### ISSUE TITLE
Howto: Status badge for each OS of a build

### ISSUE THREAD

**Issue by ianfixes** [travis-ci/travis-ci#9579]
A workaround for #4623.  I would have posted it there, but that issue is locked.

The trick is to make a set of dummy `env` parameters that correspond to the OSes, then `matrix` / `exclude` the pairs that don't match.

```yml
os:
  - linux
  - osx

env:
  - BADGE=linux
  - BADGE=osx

# hack to get some OS-specific badges
matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux
```

Then, you'll be able to link to OS-specific badges in this form.
`http://badges.herokuapp.com/travis/:your_username/:your_repo?env=BADGE=osx&label=build&branch=master`

I think they look nice in a tabular form, e.g. as I did in the current [README.md for `arduino_ci`](https://github.com/ianfixes/arduino_ci):
```markdown
Platform | CI Status
---------|:---------
OSX      | [![OSX Build Status](http://badges.herokuapp.com/travis/ianfixes/arduino_ci?env=BADGE=osx&label=build&branch=master)](https://travis-ci.org/ianfixes/arduino_ci)
Linux    | [![Linux Build Status](http://badges.herokuapp.com/travis/ianfixes/arduino_ci?env=BADGE=linux&label=build&branch=master)](https://travis-ci.org/ianfixes/arduino_ci)
Windows  | [![Windows Build status](https://ci.appveyor.com/api/projects/status/8f6e39dea319m83q?svg=true)](https://ci.appveyor.com/project/ianfixes/arduino-ci)

```

Platform | CI Status
---------|:---------
OSX      | [![OSX Build Status](http://badges.herokuapp.com/travis/ianfixes/arduino_ci?env=BADGE=osx&label=build&branch=master)](https://travis-ci.org/ianfixes/arduino_ci)
Linux    | [![Linux Build Status](http://badges.herokuapp.com/travis/ianfixes/arduino_ci?env=BADGE=linux&label=build&branch=master)](https://travis-ci.org/ianfixes/arduino_ci)
Windows  | [![Windows Build status](https://ci.appveyor.com/api/projects/status/8f6e39dea319m83q?svg=true)](https://ci.appveyor.com/project/ianfixes/arduino-ci)

Unfortunately, at this time I haven't found a way to link to anything but the top-level build in Travis (so the target URLs for both badges are the same).

**Comment by mihaipopescu** [comment]
I didn't get it to work but I really wish TravisCI would do something similar.

**Comment by mihaipopescu** [comment]
I take that back, it might work.

**Comment by fangq** [comment]
I followed the example in this thread, and added `BADGE=os` tags in my [.travis.yml](https://github.com/fangq/mcxcl/blob/master/.travis.yml),  see build log:

https://travis-ci.com/github/fangq/mcxcl/builds/177160033

however, using the below image URL format gives me an error status

http://badges.herokuapp.com/travis/fangq/mcxcl?env=BADGE=Ubuntu_16.04&label=ubuntu&branch=master

[![Ubuntu_16.04 Build Status](http://badges.herokuapp.com/travis/fangq/mcxcl?env=BADGE=Ubuntu_16.04&label=ubuntu&branch=master)](https://travis-ci.com/github/fangq/mcxcl)

I am wondering if I miss something in the sample project to make this to work.
any comment is appreciated!

**Comment by nathan-fiscaletti** [comment]
This no longer seems to work :(
