### ISSUE TITLE
Support for Jabber notifications

### ISSUE THREAD

**Issue by roidrage** [travis-ci/travis-ci#958]
Filed as per https://twitter.com/skandragon/status/308483061794881536

**Comment by dwt** [comment]
+1 xmpp notificatons. There are several ways to implement this:

a) let travis ci have a jabber account that I would friend, then on build notifications he just sends me a normal message
b) let travis-ci be a jabber account that joins a certain group chat and posts a message there.

Both would work and would require very little setup cost. I do use a) on other projects using jenkins, so I can attest that it works.

**Comment by nickgrealy** [comment]
+1 XMPP

**Comment by Sanic** [comment]
+1

**Comment by mightyBroccoli** [comment]
+1
