### ISSUE TITLE
update py 3.7 on travis

### ISSUE THREAD

**Issue by ThomasWaldmann** [travis-ci/travis-ci#9580]
the py37-dev offered on travis is some 3.7.0a4+ or so (whatever that plus means precisely).

considering we are at b4 now and rc1 soon, can we get that updated asap and before the 3.7.0 release?

i guess it would be a good thing if projects could test whether their stuff works with what will become 3.7 and find any issues *before* the 3.7.0 release.

for example, we have strange test fails there:
https://travis-ci.org/borgbackup/borg/jobs/360736109

but considering the age / alpha quality, it could be just some broken py37 alpha release or it could be our code not working with py37 yet, who knows?

**Comment by ambv** [comment]
Thomas, see #9069.

**Comment by BanzaiMan** [comment]
I'm closing this in favor of #9069.
