### ISSUE TITLE
Web SSH UI does not accept ECDSA keys

### ISSUE THREAD

**Issue by jayed** [travis-ci/travis-ci#9591]
Github allows EC keys. The Travis UI does not. This seems to be a format/verification issue as the UI responds with "This is not a private key" when, if fact, it's a private key. 

The key format is:
```
-----BEGIN EC PRIVATE KEY-----
< 5 lines of key material >
-----END EC PRIVATE KEY-----
```

In some organizations, RSA keys have been deprecated in favor of EC keys.

**Comment by BanzaiMan** [comment]
One reason to not allow it is that the ECDSA key is not supported on macOS images.

**Comment by skwashd** [comment]
This issue hasn't been resolved. It still isn't possible to use ECDSA keys via the web UI.

**Comment by jmons** [comment]
Seconded - It still isnt possible to use ECDSA keys via the web. Support for ECDSA keys is wide (there have been historical platforms that didn't support it) - I'm not clear on @BanzaiMan 's comment above: EC Keys work on macOS (but possibly you mean specifically travis related mac images?)

As @jayed mentions in the top post - there are organisations that have moved over to EC based for various reasons. Can we re-open the ticket please?

**Comment by BanzaiMan** [comment]
To clarify: older mac images we still support don't have the support.

**Comment by BanzaiMan** [comment]
Indeed, xcode6.4 is the only image that doesn't support this key type.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
