### ISSUE TITLE
Travis UI shows incorrect branch for build

### ISSUE THREAD

**Issue by myitcv** [travis-ci/travis-ci#9592]
https://travis-ci.org/myitcv/immutable/builds/374118237

<img width="818" alt="screen shot 2018-05-08 at 18 44 36" src="https://user-images.githubusercontent.com/3374574/39773472-23b9d91c-52f0-11e8-8d1d-7dbe537bb105.png">

As you can see, the Travis GUI is indicating this was a build on the `master` branch. 

But this PR was not merged into `master`, rather `go1.11`: https://github.com/myitcv/immutable/pull/61.

So I think the Travis GUI is incorrect here?

**Comment by BanzaiMan** [comment]
This is a PR build, so it belongs to the base branch, which is `master`. This is documented in https://docs.travis-ci.com/user/pull-requests#How-Pull-Requests-are-Built.

**Comment by myitcv** [comment]
Ah, I think I see what's happened here. When I created the PR it had a base of `master`, which then got changed soon after to `go1.11`. So it's possible that in this situation the build started before the change of base.
