### ISSUE TITLE
Try to use TravisCI for .NET

### ISSUE THREAD

**Issue by qinyuanpei** [travis-ci/travis-ci#9597]
Try to use TravisCI for .NET

Okay，I notice [SonarCloud](https://about.sonarcloud.io/) offer a static code check service based on SonarCube, which is a classic tool for static code check. My aim is combine TravisCI with SonarCloud. I had read [docs](https://docs.travis-ci.com/) about .NET and I know SonarCloud is supported by TravisCI. So I gonna to use xbuild/msbuild to build a .NET project, use nuget to install/restore packages, use NUnit to run all unit test cases. The **.travis.yml** is writen  as below:
```
mono: 
  - latest
language: csharp
solution: ./HTTPServer/HTTPServer.sln

install:
  - nuget restore ./HTTPServer/HTTPServer.sln # restore nuget
  - nuget install NUnit.Runners -Version 3.8.0 -OutputDirectory ./TestRunner # install nunit

script:
  - nuget
  - cd ./HTTPServer
  - msbuild /p:Configuration=Release HTTPServer.sln
  - mono ./TestRunner/NUnit.Runners.3.8.0/tools/nunit3-console.exe ./HTTPServerLib.UnitTest/bin/Release/HTTPServerLib.UnitTest.dll

branches:
  only:
    - master
```
Now, I am not sure about nuget. Because I can't install a package via nuget in TravisCI.
This is all of the work I had done.

@joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
Can you please add more details? Check out the docs if you haven't already: https://docs.travis-ci.com/user/languages/csharp/

**Comment by qinyuanpei** [comment]
@akoeplinger Thanks. I had update my comment, is there any suggestion to finish this idea?

**Comment by JonKohler** [comment]
Can you close this issue? sounds like there is no more problem here
