### ISSUE TITLE
Confusing behavior for the new Github apps integration

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#9598]
When migrating an account to the new Github apps integration, repos which did not have a Travis configuration before started to be built as well (while Travis was not enabled on them), and were of course failing, as these were not ruby repos at all.
This is quite confusing. What is the recommended way to setup the Github Apps integration  to avoid such behavior ?

**Comment by markduffield** [comment]
It would be nice if the integration settings allowed for some 'Global settings' to disable building for repos if a .travis.yaml file is not present.

**Comment by stof** [comment]
yeah, that would be fine with me

**Comment by BanzaiMan** [comment]
Hi, everyone. Sorry for the issue. We are aware of the issue, and we are tracking it. We hope to have updates soon.

**Comment by chris48s** [comment]
I am also affected by this. I think someone in our organisation activated the new integration and now we have builds unexpectedly trying to run on some repos. Is there a way I can manually disable them while this issue is open?

**Comment by ritwickdey** [comment]
I'm facing same issue. I don't want any CI for few repo. But I can't turn off it.

`Build only if .travis.yml is present` is also not working for me. 

I've checked the network tab. The request is being completed even.

![image](https://user-images.githubusercontent.com/18099464/40234609-21a98802-5ac5-11e8-8075-1cf1fa50c6e3.png)

**Comment by BanzaiMan** [comment]
@ndarville Sorry to hear about the issue. Could you email support@travis-ci.com with details about your repository visibility issue? Thank you!

**Comment by stof** [comment]
@BanzaiMan on my side, I fixed the issue by applying the github app only to some specific repos rather than the whole organization on the github side.

I think this is related to the fact that Travis was enabling itself on a repo based on the webhook presence (as soon as it receives events, it runs builds). With org-level webhooks for github apps, this requires another opt-in system in Travis.

**Comment by leonardodino** [comment]
@BanzaiMan is this issue fixed?

**Comment by stof** [comment]
I think https://changelog.travis-ci.com/all-builds-require-a-travis-yml-63545 fixed this
