### ISSUE TITLE
Support configuration files with YAML directives or marker lines

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [travis-ci/travis-ci#9600]
It seems that Travis CI can only accept configurations that are in [YAML's Bare Document form](http://yaml.org/spec/1.2/spec.html#id2800967) and [will reject configurations that use YAML directives or marker lines](https://travis-ci.org/Lin-Buo-Ren/Configuration-Templates-for-Travis-CI/builds/376714105).

I would like to request either:

* Support the full [Directive Document format](http://yaml.org/spec/1.2/spec.html#id2801522)
* Document the proper YAML format that Travis CI supports in [The Travis CI Documentation](https://github.com/travis-ci/docs-travis-ci-com) (refer https://github.com/travis-ci/docs-travis-ci-com/issues/1831), preferably in https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI

**Comment by BanzaiMan** [comment]
Thanks for the information. I've tracked this down to Ruby's reliance on libYAML, which, at the moment, only supports YAML 1.1. 

See https://github.com/ruby/psych/issues/253 and https://github.com/yaml/libyaml/issues/20.

**Comment by BanzaiMan** [comment]
I'm closing this one, and continue on the docs issue.

**Comment by Lin-Buo-Ren** [comment]
Oh, I missed out the fact that YAML 1.1 directive actually works, apologies for the confusion.
