### ISSUE TITLE
Android jobs still use Precise as base image

### ISSUE THREAD

**Issue by janisozaur** [travis-ci/travis-ci#9603]
Ubuntu Precise, 12.04, was an LTS release which reached [EOL status a year ago](https://www.ubuntu.com/info/release-end-of-life). It is still used for Android-targetting jobs in production on travis-ci.org.

With the newly released Android NDK r17, it is impossible to use Android jobs on travis-ci.org anymore, as they require a supported system.

See https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/376846479 for a sample job.

**Comment by BanzaiMan** [comment]
You are explicitly choosing Precise on this job. https://github.com/OpenRCT2/OpenRCT2/blob/d965553cae58d0babfbb3a0bb30707c968c400bb/.travis.yml#L114

**Comment by janisozaur** [comment]
Yes indeed, that was an oversight in our configuration. I will close this issue now, that I have removed the offending line.

On a somewhat related note: is there a reason we were still able to obtain precise-based images, rather than being greeted with a big fat warning this is a no longer supported system?
