### ISSUE TITLE
Travis CI job times out after 50 minutes not 120

### ISSUE THREAD

**Issue by recursion-ninja** [travis-ci/travis-ci#9605]
[This job](https://travis-ci.org/amnh/PCG/jobs/377067583) from a [_public repository_](https://github.com/amnh/pcg) has timed out after 50 minutes, not 120 minutes.

The [Travis CI documentation on time limits](https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts) clearly states that this is not the intended functionality:

> It is very common for test suites or build scripts to hang. Travis CI has specific time limits for each job, and will stop the build and add an error message to the build log in the following situations:
> 
>   * When a job produces no log output for 10 minutes.
>   * When a job on a private repository takes longer than 50 minutes.
>   * When a job on a public repository takes longer than 120 minutes.
> 

This erroneously truncated time limit makes building and running QA tools on a large project impossible.

**Comment by cotsog** [comment]
Sorry for the confusion @recursion-ninja!

This was a mistake introduced in the overhaul of our docs wrt to bringing open source builds from travis-ci.org to travis-ci.com.

It should read:

> When a job on a public repository takes longer than 50 minutes.
> When a job on a private repository takes longer than 120 minutes.

It's now [fixed](https://github.com/travis-ci/docs-travis-ci-com/commit/63f4668e774bd4cada0116aea29c90dfb71c31ad).

**Comment by cotsog** [comment]
@recursion-ninja please send an email to `support [at] travis-ci [dot] com` and we will continue from there. Thanks!

**Comment by aymenbuu** [comment]
Hey, this still occurs for a private repository after 50 minutes.

I get the error for my build against a private repository: `The job exceeded the maximum time limit for jobs, and has been terminated.` at exactly 50 minutes in.

If it makes any difference, I am on the github student plan and using free credits (not sure if there is a caveat for free-credits but not from what I've seen)

---

For the meantime I've modified my test scripts to be slighltly less thorough so they finish in at 46 minutes; but if this can be addressed I would be grateful.
