### ISSUE TITLE
Sudo on OSX Asking for Password

### ISSUE THREAD

**Issue by mAAdhaTTah** [travis-ci/travis-ci#9608]
The docs suggest passwordless sudo should be enabled for OSX images but I'm getting a password prompt [here](https://travis-ci.org/mAAdhaTTah/tea-party).

**Comment by BanzaiMan** [comment]
The Mac images are set up to run commands without password, but it seems that the Mac demands one when you run `sudo -v`. Specifying a command, say `echo` or `true`, should work.

While I agree that `sudo -v` is a logical command to run here, `sudo true` is one that works on both Linux and the Mac.

I'm closing this now, but do let us know if `sudo true` does  **_not_** work.
