### ISSUE TITLE
Mac job fails to start with "Unable to download 2.7 archive."

### ISSUE THREAD

**Issue by timothydmorton** [travis-ci/travis-ci#9609]
It seems as though there's some problem launching a mac job, involving permissions for accessing an archive from s3: https://travis-ci.com/timothydmorton/isochrones/jobs/123693221.  The linux version of this job passed.

**Comment by BanzaiMan** [comment]
Hello, there. We do not support Python on the Mac at this time. See #2312. Thanks.
