### ISSUE TITLE
401 bad credentials when deploying to GitHub releases

### ISSUE THREAD

**Issue by drxtun** [travis-ci/travis-ci#9610]
Hi guys ! I've been having headaches trying to figure out how to deploy with GitHub OAuth token.
 1. I went to the [Personal access tokens](https://github.com/settings/tokens) page on github and generated a new [token with access to public_repo](https://docs.travis-ci.com/user/deployment/releases#Authenticating-with-an-OAuth-token).
 2. I encrypted it with:

        echo github GITHUB_ACCESS_TOKEN | travis encrypt -r drxtun/medocs
 3. Put it where it belongs:

        ......
        ......
        deploy:
          provider: releases
          api_key:
            secure: <HERE>
          file: medocs*.deb
          skip_cleanup: true
          on:
            repo: drxtun/medocs
            tags: true

I've tried all of the combinations I could think of  (inspired by [1](https://github.com/travis-ci/travis-ci/issues/8018), [2](https://github.com/travis-ci/travis-ci/issues/4973), [3](https://github.com/travis-ci/travis-ci/issues/8648) & [4](https://github.com/joemccann/dillinger/issues/557)) with `--org` and `--pro`  defining at each time a new endpoint (because I had no clue what went wrong) but I keep on having the error with `401 - Bad credentials` at the deployment phase :

    
    Preparing deploy
    No stash entries found.
    /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/response.rb:9:in `block in call'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/response.rb:61:in `on_complete'
    .....
    .....
    .....
    failed to deploy

`travis report` shows:

    System
    Ruby:                     Ruby 2.5.1-p57
    Operating System:         Ubuntu 18.04
    RubyGems:                 RubyGems 2.7.6
    
    CLI
    Version:                  1.8.8
    Plugins:                  none
    Auto-Completion:          yes
    Last Version Check:       2018-05-12 09:01:55 +0100
    
    Session
    API Endpoint:             https://api.travis-ci.org/
    Logged In:                as "drxtun"
    Verify SSL:               yes
    Enterprise:               no
    
    Endpoints
    org:                      https://api.travis-ci.org/ (access token, current)
    pro:                      https://api.travis-ci.com/ (access token)

I tried:

    travis setup releases

with the same 401 credentials error on build.

I even ended up setting the github-token as a secure variable (**Environment Variables**) in the settings page of my repository.

![image](https://user-images.githubusercontent.com/39054543/39955930-4b5135ce-55cf-11e8-9ada-92b1dff62636.png)

then:

    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      skip_cleanup: true
      on:
        repo: drxtun/medocs
        tags: true

But I'm still getting the same error.

So what do you think went wrong, how to know for sure and what to do ?
Thank you.

**Comment by drxtun** [comment]
My bad ! It was building a past tag that had a .travis.yml file with a revoked OAuth token.
My apologies !

**Comment by screeley44** [comment]
@drxtun - I'm having similar headaches and I've tried every single combination I can think of as well, can you tell me what you mean by it was building a past tag with a revoked OAuth token?

**Comment by drxtun** [comment]
@screeley44 : I mean't in a previous `commit` the `.travis.yml` file had another `api_key` that was no more valid (the `tag` was pointing to that commit). I deleted the `tag` remotely (and locally) than I pushed the new `tag` to point to a `commit` where the `.travis.yml` have the new `api_key`.
@copejon : The `api_key` value I got it from  [here](https://github.com/settings/tokens/new); it is **a personal access token** with a scope of `public_repo`. I [used the travis CLI tool to encrypt it](https://docs.travis-ci.com/user/encryption-keys/#Usage).

**Comment by jywarren** [comment]
Our repo started seeing the 401 error a week ago and it's blocking all Travis builds... oof! Wondering if we're seeing a related issue. Did this suddenly begin for any of you?

**Comment by Kocal** [comment]
@jywarren that's probably related to the merge of travis-ci.org and travis-ci.com for all public and private repositories ([source](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps)).
I have a public repo that is on travis-ci.com, and I used `travis setup releases --pro` to make Github releases working like a charm.

**Comment by Kocal** [comment]
Lol, I just had the same problem today and I'm happy that https://github.com/travis-ci/travis-ci/issues/9610#issuecomment-401680829 actually fix it 🤣

**Comment by tmccombs** [comment]
there should probably be some documentation about this.

I ran into the same problem and it took me a long time to figure out this was the problem.

**Comment by QingYanL** [comment]
I have the same problem,so how to solve the problem?

**Comment by tmccombs** [comment]
> how to solve the problem?

https://github.com/travis-ci/travis-ci/issues/9610#issuecomment-401680829
