### ISSUE TITLE
CC and CXX set via language: cpp overriding env

### ISSUE THREAD

**Issue by lordofhyphens** [travis-ci/travis-ci#9615]
It appears that `language: cpp` is exporting its CC and CXX after `env` is evaluated, which means that when I am trying to use gcc-7 in my build matrix, the default items from travis are clobbering the ones I am attempting to eval.

Related travis config:
https://github.com/lordofhyphens/Slic3r/blob/cppgui/.travis.yml

### Background: 
I'm trying to set up a build matrix for both `osx` and `linux`.

**Comment by BanzaiMan** [comment]
Language settings override user defined ones so that our languages have a known set of environment variables to work with.

If you want to override those, you can try `export`ing again in a later step; e.g., `before_install`.
