### ISSUE TITLE
NUL character in HOME?

### ISSUE THREAD

**Issue by fschulze** [travis-ci/travis-ci#9616]
I sometimes get ``ValueError: argument must be a string without NUL characters``, see for example https://travis-ci.org/devpi/devpi/jobs/378409242#L891

It seems like Python's ``os.path.expanduser`` somehow introduces this. It happens in ``get_netrc_auth`` in ``requests``. It tries to expand '~/.netrc' and then the following ``os.path.exists`` on the expanded path fails, because the expanded string is ``/var/spool/news\x00/usr/sbin/nologin/.netrc``.

**Comment by BanzaiMan** [comment]
This seems rather strange. We should not be writing to `~/.netrc` under most circumstances for public repositories and only one job failed in this way from this build https://travis-ci.org/devpi/devpi/builds/378409216.

**Comment by BanzaiMan** [comment]
That's strange. Then `~/.netrc` should not exist at all. Is something in your build writing it (and not cleaning it up)?

https://travis-ci.org/BanzaiMan/travis_production_test/builds/378945325 shows that `cat ~/.netrc` fails by default.

**Comment by fschulze** [comment]
Again, this is not about ``~/.netrc``, but about the expansion of ``~``.

**Comment by BanzaiMan** [comment]
Sorry, I lost sight of that.

However, `$HOME` should be `/home/travis`. Something else is changing it. Do you have any idea?

These are our `pypy3` archives. None of them has changed in the last few months, so the erratic behavior baffles me.

```
2016-09-07 22:10:32   42801682 pypy3-2.4.0.tar.bz2
2015-12-20 21:42:15   41986352 pypy3-2.4.tar.bz2
2016-07-12 15:48:47   31161218 pypy3.3-5.2-alpha1.tar.bz2
2017-03-08 23:09:11   26665269 pypy3.3-5.5-alpha.tar.bz2
2018-01-12 11:15:11   35531618 pypy3.5-5.10.0.tar.bz2
2018-02-12 08:58:10   38509010 pypy3.5-5.10.1.tar.bz2
2018-01-08 17:11:19   35530474 pypy3.5-5.10.tar.bz2
2017-06-09 16:56:41   29989445 pypy3.5-5.7.1-beta.tar.bz2
2017-08-31 22:56:52   35021902 pypy3.5-5.8.0.tar.bz2
2017-12-12 16:39:32   35324851 pypy3.5-5.9.0.tar.bz2
2018-02-12 08:58:10   38509010 pypy3.5.tar.bz2
2017-07-26 08:13:36   29545713 pypy3.tar.bz2
```

**Comment by fschulze** [comment]
I will try to find more info on this, but I most likely won't have time this month. I will also check if it happens with something else than only pypy3. Thanks for replying so quickly, much appreciated.

**Comment by fschulze** [comment]
Now it happened with pypy instead of pypy3: https://travis-ci.org/fschulze/devpi/jobs/379641248#L681

The actual path looks really weird: https://travis-ci.org/fschulze/devpi/jobs/379641248#L675

Compared to last time with pypy3: https://travis-ci.org/devpi/devpi/jobs/378409242#L885 it looks like the only common part is ``/usr/sbin/nologin/`` and the part before that is some arbitrary memory.
