### ISSUE TITLE
Customize behavior depending on event type

### ISSUE THREAD

**Issue by waghanza** [travis-ci/travis-ci#9617]
Hi,

I want to customize some behavior depending en `travis-ci` **context**

I have this configuration, described in https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#Conditional-Builds

~~~yaml
jobs:
  include:
    - stage: no_change_on_pr
      script: export OPTIONS='--record'
      if: type IN (pull_request)
~~~

but I can see, on https://travis-ci.com that travis does not run because of 
~~~
Build config did not create any jobs.
~~~

Has anyone use **Conditional builds** ?

Regards,

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by waghanza** [comment]
@BanzaiMan sure thing, let me send you an email
