### ISSUE TITLE
Duplicate builds in PR after migration to GitHub Apps

### ISSUE THREAD

**Issue by levrik** [travis-ci/travis-ci#9618]
After migration to GitHub apps all builds are duplicate. We were already running on travis-ci.com and used the button in the Travis CI settings more migration.

![image](https://user-images.githubusercontent.com/9491603/40001584-d0238d68-578e-11e8-892b-133eda0769d6.png)

Is that a known issue? Did we miss something after migration? It's kinda annoying to have four builds instead of two running.
Maybe important: Travis isn't shown under GitHub Services anymore so the legacy thing should be removed, right?

**Comment by ylemkimon** [comment]
First two are new `Checks API` and other two are existing `Status API`. It'll be nice to have options to disable one of them.

**Comment by BanzaiMan** [comment]
Hello, there. We are aware of this issue, and we are working to clean it up in the coming weeks.

Thank you for your understanding and patience.

**Comment by diegoeche** [comment]
Hello @BanzaiMan.  We are having this issue in the moment. Any ETA or update regarding this?

**Comment by saviomuc** [comment]
Hello. Problem still persists for me as well. Interested for ETA as well.

**Comment by shaunlmason** [comment]
Is there anything we can do as users to remove the previous (webhook based?) checks?

**Comment by Aylr** [comment]
I am still seeing this issue on travis-ci.com. Can this be user adjusted while we await a fix?

**Comment by heppu** [comment]
Any progress on this?

**Comment by levrik** [comment]
@Hultner I can confirm this. Also happens for us since a few hours. This morning everything was still like before.

**Comment by BanzaiMan** [comment]
@Hultner @levrik Please subscribe to https://www.traviscistatus.com/incidents/d16clc6zpd85 for that incident. Thanks.

**Comment by Xerus2000** [comment]
This is still not fixed...

**Comment by Hultner** [comment]
@Xerus2000 I talked with Travis support about this. It seems they have (are due to?) removed these hooks in favour of the new style. We have to replace them in our protected branches set up with the new ones. 

A bit of a hassle to do this to every repository and branch you own but seems to be working for us now.

**Comment by Xerus2000** [comment]
@Hultner what exactly do I need to do? Remove hooks? Set up new ones? Sorry, I'm fairly new to CI.

**Comment by robertbenjamin** [comment]
@Hultner +1, would be great to know what hooks you removed, I don't believe I have any branch protection rules or explicit webhooks setup in Github but am still seeing duplicate builds.

**Comment by Hultner** [comment]
Since yesterday I seem to have problems with the new hook as well. The one I previously removed was the one named like `continuous-integration/travis-ci`.

**Comment by pwr22** [comment]
I switched over to the apps integration for a new project and I'm getting this too

**Comment by Hultner** [comment]
Ours seems to be working again for new commits but I'm no longer confident that it will keep working normally.

**Comment by robertbenjamin** [comment]
@BanzaiMan Thanks for the update on this!

**Comment by BanzaiMan** [comment]
I'm now locking this issue as resolved. I've written up a brief description in https://github.com/travis-ci/travis-ci/issues/10204.
