### ISSUE TITLE
"We couldn't find the repository"

### ISSUE THREAD

**Issue by oleksandrpaziuk** [travis-ci/travis-ci#9619]
I face this problem:
![screenshot from 2018-05-14 16-47-04](https://user-images.githubusercontent.com/31699656/40001568-27ff848a-5797-11e8-9718-a69afde642b0.png)
Any ideas how to deal with it?

**Comment by BanzaiMan** [comment]
Do you have access to this repository? If so, please try resyncing your data at https://travis-ci.com/profile.

**Comment by oleksandrpaziuk** [comment]
Thank you! Now I have access.
