### ISSUE TITLE
c:sudo echo :Permission denied

### ISSUE THREAD

**Issue by 949081642** [travis-ci/travis-ci#9620]
hello:
    something like this happened,how can i do ?
thank you 
![screenshot from 2018-05-15 14-31-07](https://user-images.githubusercontent.com/39252619/40040540-35e808fe-584d-11e8-961a-1ceb38019b13.png)

**Comment by BanzaiMan** [comment]
Does this work on your machine?

`sudo` does not redirect I/O; in other words, `sudo` is running only `echo 1024`, while `> /sys/devices…` has only the user privilege.

Try something like

```
echo 1024 | sudo tee /sys/devices…
```

**Comment by 949081642** [comment]
it works successfully，thank you.
