### ISSUE TITLE
No repos showing up in travis-ci.com after switch to Github App

### ISSUE THREAD

**Issue by PLaRoche** [travis-ci/travis-ci#9622]
Our repos seem to still be building, but following any links, or navigating directly to travis-ci.com leads to the getting started page and NO repos showing there.

**Comment by PLaRoche** [comment]
![image](https://user-images.githubusercontent.com/8809152/40058719-6d84f65c-5828-11e8-8b5e-dc17912f1386.png)

**Comment by PLaRoche** [comment]
![image](https://user-images.githubusercontent.com/8809152/40058753-844d6cca-5828-11e8-913d-4504bd67383f.png)

**Comment by PLaRoche** [comment]
At least 20, I can’t get a screen shot of all the ones I have added due to the window size of the app, but lets say its not all of our repos, but many many many repose



:-)

Cheers,
-P

**Comment by BanzaiMan** [comment]
Which ones? If you'd rather not discuss them in public, please close this issue and email us at support@travis-ci.com. Thanks.

**Comment by PLaRoche** [comment]
I may have not sent my reply
https://github.com/manifoldco

dashboard
Marketplace
Manifold-www
Docs-www
Kubernetes-manifests


Many many many more

We are even now having issues with re-triggering builds.  This is becoming a show stopper on our end, since we can’t deploy….

**Comment by PLaRoche** [comment]
This was due to not having the two github third party integrations not approved.  Once approved, all fixed
