### ISSUE TITLE
Commit message is an env variable is an invalid env var during merge commit

### ISSUE THREAD

**Issue by exp0nge** [travis-ci/travis-ci#9623]
When doing a merge commit after a regular commit + PR request build finishes successfully, a environmental variable with the content of the merge commit message is set which breaks some systems.

Eg: Using `$(env | cut -f1 -d= | sed 's/^/-e /')` to set all the current environmental variables to pass into docker will break during a merge commit but not a PR or regular commit build.

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!
