### ISSUE TITLE
How to make sure that the cache is ready from previous builds?

### ISSUE THREAD

**Issue by yadkit** [travis-ci/travis-ci#9627]
Hi. I am building my personal **Golang** project on Travis.

I am using directly "go get" for "install" stage and even if I use cache directive in .travis.yml, the builder downloads the dependencies anyway without taking the previous cache into account. So I'd like to run the 'install' stage only if the cache isn't ready. How can I do that?

**Comment by BanzaiMan** [comment]
What do you want to happen if the cache _is_ ready?

**Comment by yadkit** [comment]
Skip the 'install' stage if cache is ready.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Hiro Asari <notifications@github.com> Date: 5/17/18  04:18  (GMT+03:00) To: travis-ci/travis-ci <travis-ci@noreply.github.com> Cc: berkant <berkant.ipek@gmail.com>, Author <author@noreply.github.com> Subject: Re: [travis-ci/travis-ci] How to make sure that the cache is ready from previous builds? (#9627) 
What do you want to happen if the cache is ready?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/travis-ci/travis-ci","title":"travis-ci/travis-ci","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/travis-ci/travis-ci"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BanzaiMan in #9627: What do you want to happen if the cache _is_ ready?"}],"action":{"name":"View Issue","url":"https://github.com/travis-ci/travis-ci/issues/9627#issuecomment-389714165"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [travis-ci/travis-ci] How to make sure that the cache is ready from previous builds? (#9627)","sections":[{"text":"","activityTitle":"**Hiro Asari**","activityImage":"https://avatars3.githubusercontent.com/u/25666?s=160\u0026v=4","activitySubtitle":"@BanzaiMan","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"travis-ci/travis-ci\",\"issueId\":9627,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"travis-ci/travis-ci\",\"issueId\":9627}"},{"targets":[{"os":"default","uri":"https://github.com/travis-ci/travis-ci/issues/9627#issuecomment-389714165"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":336098598}"}],"themeColor":"26292E"}
