### ISSUE TITLE
could not find remote branch

### ISSUE THREAD

**Issue by adrian-wang** [travis-ci/travis-ci#9628]
In our recent pull request
Intel-bigdata/OAP#752, travis generated 2 builds instead of 1:
continuous-integration/travis-ci/push — The Travis CI build failed
continuous-integration/travis-ci/pr — The Travis CI build passed

The first build failed because of
```
The command "eval git clone --depth=50 --branch=fix-maven-check https://github.com/Intel-bigdata/OAP.git Intel-bigdata/OAP " failed. Retrying, 3 of 3.
```
while the `fix-maven-check` branch is not present in upstream, but in https://github.com/yueawang/OAP.git . What goes wrong?

**Comment by adrian-wang** [comment]
https://travis-ci.org/Intel-bigdata/OAP/builds/379583155?utm_source=github_status&utm_medium=notification

**Comment by BanzaiMan** [comment]
Hmm. This is strange. Have you seen this anywhere else?

**Comment by adrian-wang** [comment]
After close the PR and open another one, the problem has gone. Feel free to close this. Thanks!

**Comment by BanzaiMan** [comment]
Thanks for the update. Do let us know when you see it again!
