### ISSUE TITLE
GCC 8 and Clang 6 are non-functional

### ISSUE THREAD

**Issue by rubenvb** [travis-ci/travis-ci#9629]
I added gcc8 and clang6 entries to my build matrix, but alas, they seem unusable.

GCC 8: https://travis-ci.org/skui-org/skui/jobs/379940591
```
/usr/lib/gcc/x86_64-linux-gnu/8/include/immintrin.h:113:10: fatal error: movdirintrin.h: No such file or directory
 #include <movdirintrin.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
```

Clang 6: https://travis-ci.org/skui-org/skui/jobs/379940593
```
The following packages have unmet dependencies:
 clang-6.0 : Depends: libllvm6.0 (>= 1:6.0~svn298832-1~) but it is not going to be installed
             Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
             Depends: libstdc++-4.9-dev but it is not installable
             Depends: libgcc-4.9-dev but it is not installable
             Depends: libobjc-4.9-dev but it is not installable
             Depends: libclang-common-6.0-dev (= 1:6.0.1~svn331815-1~exp1~20180510084422.78) but it is not going to be installed
             Depends: libclang1-6.0 (= 1:6.0.1~svn331815-1~exp1~20180510084422.78) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

The first seems like GCC is missing some (well, at least one) of its own intrinsics headers.
The latter seems like Clang 6 is built against GCC 4.9, which cannot be installed for unknown reasons.

**Comment by cherusker** [comment]
+1 having exactly the same issue here. Are there any workarounds to get Clang 6 to work?

**Comment by acgetchell** [comment]
+1 Same issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BanzaiMan** [comment]
Do those gcc8 packages work on your machine? The files mentioned in the logs are coming from the Ubuntu packages, and if they are faulty, I don't think there's much we can do.

As for clang, try installing the dependencies indicated in the warning messages.

**Comment by rubenvb** [comment]
The GCC 8 packages now work without any changes from my end so this was a packaging/repo/distro issue.

It seems I needed the `ubuntu-toolchain-r-test` source for LLVM 6.0.
