### ISSUE TITLE
"Permission denied" while recovering cached files

### ISSUE THREAD

**Issue by 2m** [travis-ci/travis-ci#9630]
We have jobs failing in [Alpakka project](https://github.com/akka/alpakka/) quite often because of the "Permission denied" error when recovering cached files.

One example https://travis-ci.org/akka/alpakka/jobs/379805962

```
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
0.14s$ Installing caching utilities
0.00s
577.20sattempting to download cache archive
fetching PR.954/cache-linux-trusty-9ae63712f037bf715411e5ef1d2bc48a711ac01f8fb321cf559e5bdb1439992d--jdk-oraclejdk8--scala-2.10.4.tgz
found cache
0.01s
3.50sadding /home/travis/.ivy2/cache to cache
creating directory /home/travis/.ivy2/cache
adding /home/travis/.sbt/boot to cache
creating directory /home/travis/.sbt/boot
/home/travis/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar: Permission denied
```

After deleting the cache archive for the particular failed job, it usually completes fine when restarted. However after a couple of more builds other jobs start failing with a similar error, albeit for a different jar files.

Here is the issue that tracks such failures in Alpakka project: https://github.com/akka/alpakka/issues/956

**Comment by BanzaiMan** [comment]
I don't think this is a question of ownership. https://travis-ci.org/akka/alpakka/jobs/379805962#L734 says clearly:

```
[error] Caused by: java.io.FileNotFoundException: /home/travis/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar (Permission denied)
```

Why is the file missing?

**Comment by BanzaiMan** [comment]
Do you know it exists? What is the mode? And what is writing that file? The file is controlled by your processes, to the best of my knowledge, so figuring these out will help you move forward with the troubleshooting.

We can also enable the debugging feature if you'd like an interactive session.

**Comment by 2m** [comment]
The `FileNotFoundException` is the consequence of having that file with wrong permissions. It looks like that correct permissions are unable to be recovered when restoring that file from the cache as indicated by

```
adding /home/travis/.ivy2/cache to cache
creating directory /home/travis/.ivy2/cache
adding /home/travis/.sbt/boot to cache
creating directory /home/travis/.sbt/boot
/home/travis/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar: Permission denied
```

It would be interesting to inspect the cached archive. Is it possible to get the full URL to the cache archive when knowing its slug and download it?

**Comment by 2m** [comment]
It has not hapeened for a while for us in alpakka project.

**Comment by vmarkovtsev** [comment]
We hit this problem with Python: https://github.com/src-d/style-analyzer/pull/122#issuecomment-422880067

**Comment by slonopotamus** [comment]
Also experiencing this issue from time to time: https://travis-ci.org/slonopotamus/git-as-svn/jobs/431126926#L544

**Comment by bendermIBM** [comment]
Also experiencing this from a `bash` context too! Going to ping some people at Travis and see if we can't get this investigated...

**Comment by fbartho** [comment]
I’m exhibiting this as well! React-native project building on macOS with node 10
