### ISSUE TITLE
Travis timeout

### ISSUE THREAD

**Issue by Marc-marc-marc** [travis-ci/travis-ci#9631]
I try to understand why this run timeout
https://travis-ci.org/osmlab/editor-layer-index/builds/380257193
make check display a dot from time to time, it never take 10min between 2 dots

**Comment by BanzaiMan** [comment]
Do you have a more recent failure of this? You’ve metered the PR and restarted it afterwards, thereby removing the old logs.

**Comment by Marc-marc-marc** [comment]
Yes, here's another one I didn't restart
https://travis-ci.org/osmlab/editor-layer-index/builds/381483048

**Comment by BanzaiMan** [comment]
@Marc-marc-marc That build finished 8 days ago.

**Comment by Marc-marc-marc** [comment]
finish but with status is "errored* due to a timeout
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

the operation usually takes about one minute
but from time to time, travis freeze and hit the 10min timeout delay.
the same build can be launch again and finish very fast.
see for exemple the last one that test a few more files in 1 min 42 sec.
https://travis-ci.org/osmlab/editor-layer-index/builds/384757540

**Comment by BanzaiMan** [comment]
Could you try reproducing the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)?

**Comment by Marc-marc-marc** [comment]
in fact the issue was not solved... but the advice offered was not understood.
how will launching the test locally via a docker (a test that ends very quickly locally) help to understand why sometimes the test freeze when it is run by travis cloud ?
I ran the make check loop a thousand times with always a similar overall execution time of about 2 min and an output of 100+ chars during those 2 min.
in the meantime, the problem has been avoid by radically changing the content of the test.
so the issue is still there, but but we avoid it.
feel free to close the ticket if you think it's no longer applicable.
if not, I'm still available if you have any question about it.
