### ISSUE TITLE
running travis compile in a docker instance fails with general error 

### ISSUE THREAD

**Issue by shayden--** [travis-ci/travis-ci#9637]
I'm working on an issue for another project, and during testing and investigation I want to be able to run the repo ci tests without having to commit. To that end I'm running the travis cli tools locally via docker with the travis build plugin.

After setting up the container, installing travis components, cloning the repo and attempting to generate the test shell scripts, the following error is reproduced:

> travis@05b540035533:~/builds/pymodbus$ ~/.travis/travis-build/bin/travis compile 
> Shell completion not installed. Would you like to install it now? |y| n
> Detected repository as shayden--/pymodbus, is this correct? |yes| 
> matrix key is ignored
> /home/travis/.travis/travis-build/lib/travis/build/appliances/validate.rb:36:in `config_status': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/validate.rb:36:in `config_status': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/setup_filter.rb:84:in `enabled?': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/wait_for_network.rb:47:in `block in check_urls': Travis::Build::Appliances::Base#app_host at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#app_host
/home/travis/.travis/travis-build/lib/travis/build/appliances/debug_tools.rb:15:in `apply': Travis::Build::Appliances::DebugTools#debug_enabled? at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#debug_enabled?
> echo -e ""
> echo -e "There was an error in the .travis.yml file from which we could not recover.
> "
> echo -e "Unfortunately, we do not know much about this error."
> echo -e ""
> echo -e "Please review https://docs.travis-ci.com"
> exit 2

The .travis.yml file can be parsed by ruby without error:
> travis@05b540035533:~/builds/pymodbus$ ruby -r yaml -e 'puts YAML.load_file(".travis.yml")'
{"sudo"=>false, "language"=>"python", "matrix"=>{"include"=>[{"os"=>"linux", "python"=>"2.7"}, {"os"=>"linux", "python"=>"3.4"}, {"os"=>"linux", "python"=>"3.5"}, {"os"=>"linux", "python"=>"3.6"}, {"os"=>"osx", "language"=>"generic"}]}, "before_install"=>["if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi", "if [ $TRAVIS_OS_NAME = osx ]; then brew install openssl; fi"], "install"=>["scripts/travis.sh pip install coveralls", "scripts/travis.sh pip install --requirement=requirements-checks.txt", "scripts/travis.sh pip install --requirement=requirements-tests.txt", "scripts/travis.sh LC_ALL=C pip install ."], "script"=>["scripts/travis.sh make test"], "after_success"=>["scripts/travis.sh coveralls"],  "branches"=>{"except"=>["/^[0-9]/"]}}

The steps to reproduce are:

1. `[root@localhost ~]# docker run --name travis_pymodbus -it -u travis travisci/ci-amethyst:packer-1513010293-3f2fb39 /bin/bash`
2. `travis@4066184227a6:/$ cd ~; mkdir ~/.travis; cd ~/.travis`
3. `travis@4066184227a6:~/.travis$ git clone https://github.com/travis-ci/travis-build.git`
4. `travis@4066184227a6:~/.travis$ gem install travis`
5. `travis@4066184227a6:~/.travis$ cd travis-build/`
6. `travis@4066184227a6:~/.travis/travis-build$ gem install bundler; bundle install; bundler add travis; bundler binstubs travis`
7. `travis@4066184227a6:~$ cd ~/builds/`
8. `travis@4066184227a6:~/builds$ git clone https://github.com/shayden--/pymodbus.git`
9. `travis@4066184227a6:~/builds/pymodbus$ git checkout dev`
10. `travis@4066184227a6:~/builds/pymodbus$ ~/.travis/travis-build/bin/travis compile > ci.sh`

The commits used are:
https://github.com/travis-ci/travis-build/commit/4957953b89efba670e1a6869d66a1de7e6e2390e
https://github.com/shayden--/pymodbus/commit/15bb3b31044b034575436588f81b5ff844049916

**Comment by higis927** [comment]
The same issue. Any comments?

**Comment by ekivolowitz** [comment]
Also having the same issue here. I ran with the --debug and --debug-http flags which displayed
```
** Loading "/home/travis/.travis/config.yml"
** Timeout::Error: execution expired
<vomit out the long error message trace>
<echo -e ..... >
** Storing "/home/travis/.travis/config.yml"
```

**Comment by ekivolowitz** [comment]
I figured out what was causing my issue. Modify the `github?` function in `.travis/travis-build/lib/travis/build/git/clone.rb`
I changed
```
def github?
  host = data.source_host.downcase
  host == 'github.com' || host.end_with?('.github.com')
end
```
Changed to 
```
def github?
  if data.source_host != nil
     host = data.source_host.downcase
     host == 'github.com' || host.end_with?('.github.com')
  end
end
```

**Comment by ekivolowitz** [comment]
@shayden-- @higis927 I fixed my issue and created PR. Check out my [fork](https://github.com/ekivolowitz/travis-build) and see if it works for you.

**Comment by shayden--** [comment]
hi @ekivolowitz , I repeated the steps in my first comment using your fork and was able to successfully run:
``$ ~/.travis/travis-build/bin/travis compile > ci.sh
$ /bin/bash ci.sh``
Thanks for your help!

**Comment by ekivolowitz** [comment]
Glad to hear it.
