### ISSUE TITLE
Option to cancel pending builds if a newer build exists

### ISSUE THREAD

**Issue by skandragon** [travis-ci/travis-ci#964]
It would be nice to have an option in .travis.yml which says, in effect, "when it's my turn to have a job run, look to see if there is a newer one pending, and run it instead."

This way, if I do rapid-fire commits which create jobs of 123.1, 124.1, and 125.1, when 123.1 gets its shot it cancels 124.1 and replaces itself with 125.1

It might be good to memorize or hash the specific .travis.yml file, and only do this is the file is identical.

I think this will eliminate a lot of needless work on many projects, and hopefully get my jobs to run sooner.  :)

**Comment by kbrock** [comment]
:+1: especially when it is a forced push after an amend / rebase

**Comment by blomquisg** [comment]
:+1:

**Comment by danoli3** [comment]
:+1:

**Comment by BanzaiMan** [comment]
Hello. @grosser has come up with an interim solution https://github.com/grosser/travis_dedup while we work on a long-term fix.

Thank you!

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
