### ISSUE TITLE
xcode9.3 image incompatible with gcc-8

### ISSUE THREAD

**Issue by acgetchell** [travis-ci/travis-ci#9640]
Compare:

https://travis-ci.org/acgetchell/CDT-plusplus/builds/381161373

With:

https://travis-ci.org/acgetchell/CDT-plusplus/builds/381155591

**Comment by Zialus** [comment]
I've just checked and this is still the case with gcc-8 and gcc-7 on xcode9.3

```
/usr/local/Cellar/gcc/8.1.0/lib/gcc/8/gcc/x86_64-apple-darwin17.5.0/8.1.0/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
 #include <_stdio.h>
          ^~~~~~~~~~
```

```
/usr/local/Cellar/gcc@7/7.3.0/lib/gcc/7/gcc/x86_64-apple-darwin17.5.0/7.3.0/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
 #include <_stdio.h>
          ^~~~~~~~~~
```

**Comment by Zialus** [comment]
Same issue with xcode9.4

**Comment by StrikerRUS** [comment]
Yeah! After yesterday Travis switch to `xcode9.4` image as default one, our builds have started to fail with this error.

**Comment by kubasejdak** [comment]
Any update here? I have the same issue on xcode-9.4 image...

**Comment by junaruga** [comment]
> fatal error: _stdio.h: No such file or directory

I experienced the issue on xcode 9.4 with gcc-8 test case.
Maybe you need to install command line tools manually like this.

```
softwareupdate --list
softwareupdate --install "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4"
```

See below case for detail. :)
https://github.com/trinityrnaseq/trinityrnaseq/blob/master/.travis.yml#L62-L65
https://travis-ci.org/trinityrnaseq/trinityrnaseq

**Comment by acgetchell** [comment]
@junaruga Yes that fixed it!

**Comment by Zialus** [comment]
But shouldn't that be installed by default?

**Comment by adamnovak** [comment]
Installing "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4" has previously made our build process work over at vgteam/vg, but now we are running into trouble because `softwareupdate` can no longer find that update:

```
$ if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4"; fi
Software Update Tool
Downloading Command Line Tools (macOS High Sierra version 10.13) for Xcode
Error downloading Command Line Tools (macOS High Sierra version 10.13) for Xcode: not found
Done.
Error downloading updates.
``` 

This causes a missing `_stdio.h` when building things with GNU GCC.

**Comment by adamnovak** [comment]
It looks like Apple has pulled the command line tools for the Xcode version that Travis ships:

```
$ if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo softwareupdate -l; fi
Software Update Tool
Finding available software
Software Update found the following new or updated software:
   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.1
	Command Line Tools (macOS High Sierra version 10.13) for Xcode (10.1), 190584K [recommended]
   * macOS High Sierra 10.13.6 Update- 
	macOS High Sierra 10.13.6 Update ( ), 2407932K [recommended] [restart]
   * iTunesX-12.8
	iTunes (12.8), 263192K [recommended]
```

**Comment by StrikerRUS** [comment]
@adamnovak We faced the same error recently. Unfortunately, `softwareupdate "Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.1"` didn't help (not found error), along with many other variants of update name ending. So, we moved to `osx_image: xcode10.1` which doesn't require any updates.

**Comment by zbeekman** [comment]
@BanzaiMan: Upon re-reading my previous comment, I realize that it may sound flippant or rude. For this I apologise.

I'm not 100% clear on the root cause of this issue. Is there something that should be done on the Homebrew side so that the GCC 8.2 bottles can be used in an environment with older xcode? Is there a way to work around this problem on the Travis-CI side?

Thanks,
Zaak
