### ISSUE TITLE
DotNet SDK doesn't bring all dependencies

### ISSUE THREAD

**Issue by matthid** [travis-ci/travis-ci#9644]
With the following as part of the `.travis.yml`:

```
dotnet : 2.1.300-rc1-008673
```

We should install all dependencies of the .net sdk. But some seem to be missing as I see:

```
Error: Failed to load ï¿½3, error: libunwind.so.8: cannot open shared object file: No such file or directory
  Failed to bind to CoreCLR at '/home/travis/build/fsharp/FAKE/nuget/dotnetcore/Fake.netcore/current/libcoreclr.so
```

And the following commit fixed the issue: https://github.com/fsharp/FAKE/commit/1c821d133db296cff7fd0bbe52d72f1782d6b70b (`before_install` wasn't actually executed)

For reference the following requirements need to be fulfilled: https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#ubuntu

/cc @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
@matthid there's a typo, it needs to be called `before_install` not `before install` like in the .travis.yml you linked.

That said, it should work without the apt commands since the .NET Core packages should have proper dependencies set up. Can you please try if installing `dotnet: 2.0.3` works?

**Comment by matthid** [comment]
the problem appeared when going from latest stable to latest rc (for global tool support). And the problem dissappears with the api get install. Not sure what else I can provide.

Maybe one more hint: it seems the sdk itself is running but the app we published had the above error in the integration tests.

**Comment by akoeplinger** [comment]
Ok, that seems to be a problem with .NET Core then, not Travis. I'd suggest you file an issue on https://github.com/dotnet/corefx.

It's possible that .NET Core changed its dependencies in later builds so `libunwind` isn't installed with the SDK anymore, but I'd consider that a bug if it's still required according to the docs.

**Comment by matthid** [comment]
Opened https://github.com/dotnet/corefx/issues/29844 lets see what they say. If they no longer depend on libunwind for netcore2.1 but you need it for netcore2.0 It might still make sense for travis to install libunwind...

**Comment by matthid** [comment]
Ok apparently 2.1 doesn't depend on `libunwind` anymore but if you publish an app for 2.0 it will still need `libunwind`... Not sure what the best way forward is. We can close the issue but I guess others will run into this as well sooner or later.

**Comment by akoeplinger** [comment]
I don't think we should put workarounds into Travis for this, at least others will find this issue when searching :)

**Comment by JonKohler** [comment]
When I use  dotnet: "2.1.300", it works like a charm. IMHO - dont use the prerelease binary?

Looks to be fixed now, can we close this?

Example passing: https://travis-ci.com/nutanix/PowerShell/builds/76293920

**Comment by matthid** [comment]
Well this particular issue is for the dependencies. But yes this is now tracked/discussed elsewhere and I agree with @akoeplinger that we don't need a workaround in travis
