### ISSUE TITLE
Using Chrome beta does not update /etc/alternatives/google-chrome

### ISSUE THREAD

**Issue by myitcv** [travis-ci/travis-ci#9645]
I followed the instructions here:

https://docs.travis-ci.com/user/chrome

But as [this project shows](https://github.com/myitcv/travis_chrome_bug/blob/master/.travis.yml), `/etc/alternatives/google-chrome` is not updated when `beta` is used:

### [Stable build](https://travis-ci.org/myitcv/travis_chrome_bug/jobs/381321283)

Ignore the fact the build failed; the relevant bit of output is:

```
$ ls -la /usr/bin/google*
lrwxrwxrwx 1 root root 31 Dec  5 20:08 /usr/bin/google-chrome -> /etc/alternatives/google-chrome
lrwxrwxrwx 1 root root 32 May 15 02:23 /usr/bin/google-chrome-stable -> /opt/google/chrome/google-chrome
The command "ls -la /usr/bin/google*" exited with 0.
$ google-chrome --version
Google Chrome 66.0.3359.181 
The command "google-chrome --version" exited with 0.
$ google-chrome-stable --version
Google Chrome 66.0.3359.181 
```

### [Beta build](https://travis-ci.org/myitcv/travis_chrome_bug/jobs/381321282)

Ignore the fact the build succeeded; the relevant bit of output is:

```
$ ls -la /usr/bin/google*
lrwxrwxrwx 1 root root 31 Dec  5 20:08 /usr/bin/google-chrome -> /etc/alternatives/google-chrome
lrwxrwxrwx 1 root root 42 May 15 23:19 /usr/bin/google-chrome-beta -> /opt/google/chrome-beta/google-chrome-beta
lrwxrwxrwx 1 root root 32 Nov 10  2017 /usr/bin/google-chrome-stable -> /opt/google/chrome/google-chrome
The command "ls -la /usr/bin/google*" exited with 0.
$ google-chrome --version
Google Chrome 62.0.3202.94 
The command "google-chrome --version" exited with 0.
$ google-chrome-stable --version
Google Chrome 62.0.3202.94 
The command "google-chrome-stable --version" exited with 0.
$ google-chrome-beta --version
Google Chrome 67.0.3396.48 beta
```

The issue is that `/usr/bin/google-chrome` (which is a symlink to `/etc/alternatives/google-chrome`) returns version `62.0.3202.94`.

It feels like this is a bug; i.e. me choosing `beta` as the build of Chrome that I want should be updating `/etc/alternatives/google-chrome` to point to that?

Thanks

**Comment by BanzaiMan** [comment]
Setting alternatives should happen during the installation of the `apt` package, right? It seems to me that this is an issue with the package itself, and, if so, Google will have to fix that.

**Comment by myitcv** [comment]
Would it be possible for Travis to run:

```
sudo update-alternatives --set google-chrome /usr/bin/google-chrome-CHANNEL
```

(for some `CHANNEL`) for now?

That would fix things in the short term.

Thanks

**Comment by BanzaiMan** [comment]
If anyone is interested in implementing @myitcv's suggestion, the code is here: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/chrome.rb

**Comment by myitcv** [comment]
> Setting alternatives should happen during the installation of the apt package, right? It seems to me that this is an issue with the package itself, and, if so, Google will have to fix that.

Actually, I don't think this is a function of the apt package, no. I can choose to have all three channels of Chrome installed, and then use `update-alternatives` to choose which one I want as the default. Having the "last installed" one be the default is not, I imagine, the intended behaviour for any such package. But I don't have a reference to cite on that point 😢

**Comment by myitcv** [comment]
Per https://twitter.com/zekjur/status/1050271697797074944, calling update alternatives is something the user is generally expected to do. So the Google package is "correct" here.

@BanzaiMan worth re-opening this therefore? Because I don't think it's "third-party".

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by thijstriemstra** [comment]
```
sudo update-alternatives --set google-chrome /usr/bin/google-chrome-beta
```

Running this `before_install` fixed it for me, as suggested by @myitcv
