### ISSUE TITLE
Expose the commit message in the build environment

### ISSUE THREAD

**Issue by roidrage** [travis-ci/travis-ci#965]
Would be nice to have the build message exposed with all the other data that's already available.

**Comment by TimvdLippe** [comment]
Would be nice if this could be supported by Travis. Currently relying on a manual `git log`.

**Comment by tristanbes** [comment]
Yup, i'm 👍  on this idea

**Comment by BanzaiMan** [comment]
We can formalize what @cvrebert suggested in the earlier comment to set this value.
