### ISSUE TITLE
feature request: add a way to report errors on file

### ISSUE THREAD

**Issue by cyberhck** [travis-ci/travis-ci#9651]
According to github's API, we're able to report status checks, that includes more information like line number, file, error message etc.

Let me try to explain it better.

If there's a build stage for say, code linting. When I do the linting, I want to be able to report the lint errors on exact line and file, so I can see that in travis.

Github already provides a checks API, all travis would need to do is to give a command line option to report this, that might include things like: filename, line number (column number maybe?), error message, etc.

That'd mean if I've got a linting error, I can see directly on my pull request tab. (That might also mean reduced load for travis as users can directly see linting error, or build failures right on github)

**Comment by rtymchyk** [comment]
This is a good idea. Before line-by-line checks happen, we should at the very least see the test results visible in the Checks tab, because right now it's basically a useless report.

**Comment by cyberhck** [comment]
Hey stale bot, this isn't done yet, please don't close it :)

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
