### ISSUE TITLE
npm ERR! enoent ENOENT: no such file or directory, open 'package.json'

### ISSUE THREAD

**Issue by benmouh** [travis-ci/travis-ci#9653]
I used to deploy into npm, until today when I tried to deploy a new version of my package I got this error : 
`[33mDeploying application[0m
npm ERR! path package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
`
It seems it cannot find package.json file even it exist, I ignore what went wrong with Travis since it used to work, you can find build and deploy logs in this link https://travis-ci.org/Wakanda/wakanda-storage/jobs/382598095

**Comment by BanzaiMan** [comment]
Has this ever worked for you?

You are [changing to `$TRAVIS_BUILD_DIR/build/Release`](https://travis-ci.org/Wakanda/wakanda-storage/jobs/382598095#L634) and never return to the repo's root. Unless there is a `package.json` in `$TRAVIS_BUILD_DIR/build/Release`, the error seems correct to me.

**Comment by benmouh** [comment]
You are right I'm mistaken in the last update of my config i didn't redirect to the right directory now this error is gone Thank you @BanzaiMan

**Comment by BanzaiMan** [comment]
Great to hear! I'm closing this now.
