### ISSUE TITLE
Didn't show setting in more options

### ISSUE THREAD

**Issue by leo424y** [travis-ci/travis-ci#9658]
<img width="1255" alt="screen shot 2018-05-24 at 2 13 10 pm" src="https://user-images.githubusercontent.com/1384394/40467712-7807d7de-5f5d-11e8-9a37-8ac2e5adf60d.png">
Just find out I can't get the setting button, but the routes works. 
So I get https://travis-ci.org/twgo/gu2-im1_pian7-sik4_offline/settings directly by url

**Comment by BanzaiMan** [comment]
When you do go to the settings page, what do you see?

**Comment by leo424y** [comment]
Yesterday I want to go setting page but it didn't show the 'setting' button.
Why?

**Comment by BanzaiMan** [comment]
What I meant was, what did you see when you went to https://travis-ci.org/twgo/gu2-im1_pian7-sik4_offline/settings?

If you have a screen shot from the time you had the problems with, please attach it. If it shows something different now, also attach a screen shot, and describe what has changed. Thanks.

**Comment by leo424y** [comment]
It seems no problem now. 
I can reach setting page.
Thanks for help.
