### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by vbabenkoru** [travis-ci/travis-ci#9660]
Our Mac builds are failing because of connectivity problems.
It can't install dependencies because of a failed lookup for github.com:
https://travis-ci.org/Iterable/iterable-ios-sdk/builds/383391442

**Comment by BanzaiMan** [comment]
Sorry about the issue. I've tried it now, and it seems to work https://travis-ci.org/BanzaiMan/travis_production_test/builds/383408181

Could you try restarting the affected builds? Thanks.
