### ISSUE TITLE
Attempting to debug a build crashes that build

### ISSUE THREAD

**Issue by ggprod** [travis-ci/travis-ci#9664]
Hello,

I was attempting to debug a build and when executing `travis_run_install` the debug build crashes with error: ../home/travis/.debug/travis_debug.sh: line 58:  8383 Terminated              sleep 1 

see full log at: 
https://api.travis-ci.com/v3/job/125812805/log.txt

**Comment by BanzaiMan** [comment]
The log indicates to me that you were able to log in to the debug session. What did you run when the session unexpectedly terminated on you? My guess is that your build is setting the `errexit` option (`set -e`) somewhere, and you are running into some command failure.

**Comment by ggprod** [comment]
I ran `travis_run_before_install` which completed ok, and then `travis_run_install` which closed the ssh connection and killed the build

**Comment by BanzaiMan** [comment]
What's in your `install`?

**Comment by ggprod** [comment]
it is pretty expensive.. perhaps that's the problem.. too resource consuming to work in a debug build.  I believe the portion that would cause the problem is installing libpostal and then doing a yarn install

it's:
```
#! /bin/bash
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update && sudo apt-get install -y --no-install-recommends pkg-config libsnappy-dev
git clone https://github.com/openvenues/libpostal
cp ./build_libpostal.sh ./libpostal
cd libpostal
sudo ./build_libpostal.sh
yarn global add node-gyp
yarn cache clean
yarn install --force
```

**Comment by BanzaiMan** [comment]
Maybe. What's in `build_libpostal.sh`? You can try turning on the verbose (`set -v`) or xtrace (`set -x`) in the scripts in involved to see if you get an idea on how the session is terminating. Also, you might consider capturing your desktop, so that you can watch the last bits of your terminal session.

**Comment by ggprod** [comment]
I think I'll close this for now and assume it was the combination of an expensive install operation and the travis debug overhead... thanks @BanzaiMan!

**Comment by JensMadsen** [comment]
this happens to me very often
