### ISSUE TITLE
Node.js builds errors

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#9665]
All my Node.js builds since few hours back finish with errors, few examples:
* https://travis-ci.org/Detox/dht/jobs/383926915
* https://travis-ci.org/nazar-pc/ronion/jobs/383959969

Looks like someone shipped bad update on Friday evening 🤔

**Comment by BanzaiMan** [comment]
I'm sorry to say, but this looks like an upstream packaging issue we cannot do much about.

**Comment by nazar-pc** [comment]
Works fine again

**Comment by nazar-pc** [comment]
Well, it works fine most of the time, but still occasionally fails, I guess some king of image didn't propagate across the whole infrastructure yet
