### ISSUE TITLE
Adding a no timeout limit to travis.yml

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#9666]
Would be nice to have a configurable parameter in `travis.yml` to simply override the timeout limit for jobs being too quiet. For example, CircleCI provides the [`no_output_timeout` parameter]( https://circleci.com/docs/2.0/configuration-reference/#run ), which allows the user to override this limit if they know their build will be quiet for a bit.

Should add this often becomes a necessity as one may bounce back and forth between going over the log length/size limit or being too quiet. Both situations lead to the job being terminated. It would be nice to soften one of these bounds when they become unreasonably tight for a particular job.

Admittedly there is the `travis_wait` script. However this isn't always honored and sometimes has other problems. Instead of spending time working on this script, it would be nice to just provide users' this simple configuration parameter to achieve the intended result without side effects.

**Comment by jakirkham** [comment]
This remains unsolved.

**Comment by rudysuharyadi** [comment]
+1

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
