### ISSUE TITLE
what is dd in .travis.yml?

### ISSUE THREAD

**Issue by patsevanton** [travis-ci/travis-ci#9667]
Hello!
I try encrypt-file with autoadding string to .travis.yml
`travis encrypt-file .copr .copr.enc -add`

And this string was add to .travis.yml
```
dd:
- openssl aes-256-cbc -K $encrypted_****_key -iv $encrypted_*****_iv
  -in .copr.enc -out .copr -d
```

I can`t found about section dd.
what is dd in .travis.yml?
Thank you

**Comment by BanzaiMan** [comment]
You passed `-add`, which was interpreted as `-a dd`. That’s where `dd` comes from. You probably meant `--add`.

**Comment by philshem** [comment]
> You passed `-add`, which was interpreted as `-a dd`. That’s where `dd` comes from. You probably meant `--add`.

came here for this 

# 🙈
