### ISSUE TITLE
Not storing secure env variables for decryption automaticly

### ISSUE THREAD

**Issue by patsevanton** [travis-ci/travis-ci#9673]
Hello!
I run 
`travis encrypt-file .copr .copr.enc`
And see
`storing secure env variables for decryption`
But in Environment Variables (at web-interface) dont have secure env variables

I run `travis encrypt-file .copr .copr.enc -p`
get output 
 openssl aes-256-cbc -K $encrypted_5a1ae0da8fa2_key -iv $encrypted_5a1ae0da8fa2_iv -in .copr.enc -out .copr -d

key: d350**********
iv:  6099e********

And create secure env variables manualy.

Plz change output text after encrypt or create copy secure env variables to Environment Variables (at web-interface)

**Comment by SanjoDeundiak** [comment]
Same issue here

**Comment by joshorig** [comment]
I also am also experiencing this issue

**Comment by giorgiosironi** [comment]
Me too. At first I thought they were going to the wrong place (`travis-ci.org` vs `travis-ci.com`) but that's not the case.

**Comment by giorgiosironi** [comment]
Try adding `--com` to every command. Not sure how to make it stick.

**Comment by giorgiosironi** [comment]
`travis endpoint --com --set-default`

**Comment by Daniele122898** [comment]
this did not fix it for me. i still have to do it manually. I am logged into the --com domain and everything. no errors when doing the command but the env variables are not created.

**Comment by AlliotTech** [comment]
the same  issue... Has anyone solved this?
``` 
wrong number of arguments (given 1, expected 2)
for a full error report, run travis report --pro
```


``` 
$ travis report --pro
System
Ruby:                     Ruby 2.6.3-p62
Operating System:         CentOS 7.6.1810
RubyGems:                 RubyGems 3.0.8

CLI
Version:                  1.8.11
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2020-03-21 22:04:06 +0800

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "xxxx"
Verify SSL:               yes
Enterprise:               no

Endpoints
com:                      https://api.travis-ci.com/ (access token, current)

Last Exception
An error occurred running `travis encrypt-file --pro`:
    ArgumentError: wrong number of arguments (given 1, expected 2)
        from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/lib/travis/cli/encrypt_file.rb:79:in `env_name'
        from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/lib/travis/cli/encrypt_file.rb:70:in `decrypt_command'
        from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/lib/travis/cli/encrypt_file.rb:42:in `run'
        from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/lib/travis/cli.rb:64:in `run'
        from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/bin/travis:18:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.6.3/bin/travis:23:in `load'
        from /usr/local/rvm/gems/ruby-2.6.3/bin/travis:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
        from /usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by velipiri5** [comment]
> the same issue... Has anyone solved this?
> 
> ```
> wrong number of arguments (given 1, expected 2)
> for a full error report, run travis report --pro
> ```
> 
> ```
> $ travis report --pro
> System
> Ruby:                     Ruby 2.6.3-p62
> Operating System:         CentOS 7.6.1810
> RubyGems:                 RubyGems 3.0.8
> 
> CLI
> Version:                  1.8.11
> Plugins:                  none
> Auto-Completion:          yes
> Last Version Check:       2020-03-21 22:04:06 +0800
> 
> Session
> API Endpoint:             https://api.travis-ci.com/
> Logged In:                as "xxxx"
> Verify SSL:               yes
> Enterprise:               no
> 
> Endpoints
> com:                      https://api.travis-ci.com/ (access token, current)
> 
> Last Exception
> An error occurred running `travis encrypt-file --pro`:
>     ArgumentError: wrong number of arguments (given 1, expected 2)
>         from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/lib/travis/cli/encrypt_file.rb:79:in `env_name'
>         from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/lib/travis/cli/encrypt_file.rb:70:in `decrypt_command'
>         from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/lib/travis/cli/encrypt_file.rb:42:in `run'
>         from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/lib/travis/cli/command.rb:198:in `execute'
>         from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/lib/travis/cli.rb:64:in `run'
>         from /usr/local/rvm/gems/ruby-2.6.3/gems/travis-1.8.11/bin/travis:18:in `<top (required)>'
>         from /usr/local/rvm/gems/ruby-2.6.3/bin/travis:23:in `load'
>         from /usr/local/rvm/gems/ruby-2.6.3/bin/travis:23:in `<main>'
>         from /usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
>         from /usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
> 
> 
> For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
> For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
> ```

Have the same issue

**Comment by AlliotTech** [comment]
I found that this error did not affect the result. so i ignored this error.

**Comment by velipiri5** [comment]
> I found that this error did not affect the result. so i ignored this error.

I found this solution. Running this before travis encrypt-file... worked for me:

gem install travis --pre
