### ISSUE TITLE
Connectivity issues?

### ISSUE THREAD

**Issue by Stephan202** [travis-ci/travis-ci#9679]
As of ~half an hour ago some of our private builds have started failing at various stages: some during `apt-get`, some while connecting to an AWS S3 bucket, and others while connecting to a private Nexus instance. Do the Travis CI network engineers also observe elevated (network) error levels?

**Comment by Stephan202** [comment]
I sent an email with links to some of the affected private builds to `contact at travis-ci dot com`.

**Comment by edmorley** [comment]
We've also been experiencing connectivity issues on our open source repositories for the last ~12 hours, ranging from NPM/yarn registry timeouts, to mysql.com APT repo timeouts, to slowness in the Travis clone/cache restore/install steps.

**Comment by edmorley** [comment]
(All GCE)

**Comment by jkirow** [comment]
We have also been experiencing connectivity issues on our sudo enabled private repository builds related to npm/composer timeouts.

**Comment by scottrblock** [comment]
We've also had `apt-get` timeouts

**Comment by blimmer** [comment]
👍 GCE networking seems totally hosed and blocking all of our pipelines at this point.

I added more details here: https://github.com/travis-ci/travis-ci/issues/9127#issuecomment-392855624

**Comment by aleachjr** [comment]
I filed a support ticket awhile ago but have yet to hear anything back. Anybody else have an active support ticket?

**Comment by blimmer** [comment]
I do. Filed one this morning and haven't heard anything back yet.

I created a sample repo that's showing this failure, too:

https://travis-ci.com/blimmer/travis-ci-example/builds/74803182

Here's what it [does](https://github.com/blimmer/travis-ci-example/blob/master/script.sh):

```
#! /bin/bash

set -ev

# Logger
. ./color-logger.bash

for run in {1..10}; do
  warn "Run $run of 10"

  info "Running traceroute to github.com..."
  time traceroute github.com

  info "Curling a docker-compose release from github..."
  time curl -sSfLv https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > docker-compose

  rm -fr docker-compose

  info "Cloning this repo (https)..."
  time git clone https://github.com/blimmer/travis-ci-example.git

  rm -fr travis-ci-example

  info "Running a traceroute to registry-1.docker.io..."
  time traceroute registry-1.docker.io

  info "Running apt-key for yarn..."
  time sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
done
```

It fails randomly on each one of these commands so it seems like a general networking problem.

**Comment by DrTorte** [comment]
We did see and resolve an issue with npm, and I've pinged internally to see about the rest. Thanks for your patience everyone!

**Comment by chrisirhc** [comment]
Seeing a similar issue, was about to log a new issue with apt-get.

From https://travis-ci.com/uber/kepler.gl/builds/74791964 :
```sh
Err:71 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:72 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:73 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:74 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
```

**Comment by meatballhat** [comment]
Hello all and thank you for your patience.  I was able to intermittently reproduce connectivity issues and identify what appeared to be a single NAT host that had stopped forwarding packets ~12h ago, but was still included in the load-balanced NAT routing.  I have since replaced the host and I am seeing much more consistent network behavior.  I have some follow up work to see why existing health checks were insufficient for automatically replacing the problem host, but for now I would like to say that this issue _should_ be largely resolved.  Please post comments with any continuing issues, including any job or log URLs you are able.  Thank you! :sparkling_heart:

**Comment by Stephan202** [comment]
@meatballhat thanks! From our side the issue seems resolved. Will close this ticket later today unless somebody reports issues still :).

**Comment by edmorley** [comment]
We're still seeing errors connecting to the yarn registry using Verdaccio, eg:
`http --> ERR, req: 'GET https://registry.yarnpkg.com/global-modules', error: socket hang up`
```
hostname: 8f6d92eb-9dea-4524-8134-76af228ddef5@1.production-5-worker-org-b-1-gce
instance: travis-job-eb134cd7-ec3c-4237-afee-eed39c3e836a travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)
```
(https://travis-ci.org/mozilla-neutrino/neutrino-dev/jobs/385364189#L6563)

And same on:
```
hostname: 3d1db1fd-d40f-4e3e-a2ac-0b70a5ac8ea3@1.production-4-worker-org-a-3-gce
instance: travis-job-d4e93ec3-20b0-4f72-b74a-cd530618966d travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)
```
(https://travis-ci.org/mozilla-neutrino/neutrino-dev/jobs/385364190)

```
hostname: 0bc8ab55-5e68-450e-b47e-7f38e36e49e2@1.production-1-worker-org-f-4-gce
instance: travis-job-f74dbdee-e2d0-4d0b-b412-56252b6e9c65 travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)
```
(https://travis-ci.org/mozilla-neutrino/neutrino-dev/jobs/385256305)

```
hostname: 093022f3-0885-41a9-b5cc-91f30699b53b@1.production-4-worker-org-b-1-gce
instance: travis-job-51f75d3b-9c6a-4718-a181-42c23c8632db travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)
```
(https://travis-ci.org/mozilla-neutrino/neutrino-dev/jobs/385256303)

**Comment by edmorley** [comment]
> We're still seeing errors connecting to the yarn registry using Verdaccio, eg:

Sorry - some of those jobs were from `master`, where Verdaccio is still using the NPM registry, the others using yarn's. This may of course also be continued fallout from NPM's switch to Cloudflare last week, though the timing seems closer to this incident.

**Comment by awwithro** [comment]
I'm still seeing intermittent issues as well. The command that's failing is ` helm plugin install https://github.com/lrills/helm-unittest`

sometime fails with
```
Downloading 
curl: (3) <url> malformed
Failed to install helm-unittest
\tFor support, go to https://github.com/kubernetes/helm.
```
sometimes works as expected

**Comment by BanzaiMan** [comment]
@awwithro What does `helm plugin install` do? If it's using GitHub API, you are probably subject to API rate limiting, which would be shared with all the other anonymous requests originating from Travis CI.

**Comment by awwithro** [comment]
its using the git command under the hood. Though if it was hitting a rate limit I'd expect to see a 403 error instead of a malformed url error

**Comment by BanzaiMan** [comment]
@awwithro You're right about the strangeness of the malformed URL error. It is not something that we control, though, so you'd have to ask for help from the plugin developers instead.

**Comment by BanzaiMan** [comment]
@awwithro (Unless the plugin is conflating the connectivity issue and the "malformed URL" issue.)

**Comment by awwithro** [comment]
I'm trying to recreate the issue and the only place this is happening is in travis. It only happens some of the time however. I'm trying to figure out a way to get the url that is malformed.

**Comment by awwithro** [comment]
It does look like an api throttle after all. https://travis-ci.org/awwithro/travis-ci-example/builds/385888157

The plugin install process curls the latest version and uses the output to create the url the download the artifact. The first curl is getting a 403 which then results in a malformed url

**Comment by Stephan202** [comment]
I'll close this issue as resolved, at least from Travis CI's side. Thanks again @meatballhat! (My girlfriend and colleagues observe, based on your Github profile photo, that you're a 10-20 year older copy of me. I have to admit that the resemblance is quite uncanny. Scary! :smile:.)
