### ISSUE TITLE
PostgreSQL 9.1 not installed

### ISSUE THREAD

**Issue by pnorman** [travis-ci/travis-ci#9680]
The documentation states

> The Travis CI build environments use version 9.1 by default

I added 

```yaml
services:
  - postgresql
addons:
  postgresql: "9.1"
```
to my travis file, and `createdb -w -E utf8 -U postgres gis && psql -Xq -d gis -U postgres -w -c "CREATE EXTENSION postgis; CREATE EXTENSION hstore;"` to the install steps.

[This build errored](https://travis-ci.org/pnorman/openstreetmap-carto/builds/385595006) with 

```
createdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

Looking at the log, there is this line

```
$ sudo service postgresql start 9.1
PostgreSQL 9.1 is not installed!
```

**Comment by BanzaiMan** [comment]
I'm sorry to say, but I do not think we are going to provide this old version of PostgreSQL on our images. Please consider setting it up yourself with a series of appropriate `apt-get` commands.

**Comment by pnorman** [comment]
> I'm sorry to say, but I do not think we are going to provide this old version of PostgreSQL on our images. Please consider setting it up yourself with a series of appropriate apt-get commands.

Can you update the documentation which states it's default?
