### ISSUE TITLE
Feature request: add a way to easily access specific build (based on build number)

### ISSUE THREAD

**Issue by hsiaoyi0504** [travis-ci/travis-ci#9683]
Hi there:

It seems to me that currently the result of travis can't be accessed directly based on the build number. For example, if I want to access specific build number like build 1285 of one of my project. I can't access it through URL like https://travis-ci.org/NAL-i5K/genomics-workspace/builds/1285. Currently, I can only access that through URL with a random number suffix: https://travis-ci.org/NAL-i5K/genomics-workspace/builds/384908463.

**Comment by BanzaiMan** [comment]
I note that this is a refrain of https://github.com/travis-ci/travis-ci/issues/1364.
