### ISSUE TITLE
Add support for Xcode 9.4

### ISSUE THREAD

**Issue by heyzooi** [travis-ci/travis-ci#9689]
Add support for Xcode 9.4 for `osx_image`

```
osx_image: xcode9.4
```

**Comment by joeydong-stripe** [comment]
+1

**Comment by BanzaiMan** [comment]
Please subscribe to the issue instead of commenting `+1`. Thanks.

**Comment by Bamieh** [comment]
I want to note that xcode 9.4 fixes the beta entitlements issue for adhoc releases, which is critical for beta testing on real devices.

**Comment by rafaelnobrepd** [comment]
Xcode 9.4 fixes several critical issues for us. Our product is restricted to be built in xcode9.2 until this is released

**Comment by rex-remind101** [comment]
seconding rafaelnobrepd 👍

**Comment by ikesyo** [comment]
https://twitter.com/travisci/status/1007701878946390018

Xcode 9.4 has come 🎉

But I'm not sure why Travis team does not post a notification on these kind of issues every time. 🤔

**Comment by SebastianThiebaud** [comment]
Hey @ikesyo 

Since we moved to `xcode 9.4` image, we're seeing a huge increase of build time. Our jobs running time increased by ~8mn (15mn to 23mn). 

Is that something you're aware? Are the new vm images having less resources?

**Comment by ikesyo** [comment]
I'm not a Travis member so I'm not sure.

**Comment by danj-stripe** [comment]
We're seeing increased build times too. I think approximately 15 mins -> 25 mins, although we don't track them closely

**Comment by SebastianThiebaud** [comment]
@danj-stripe Our unit tests here: 9mn to 25mn and deploy (release + upload to iTC or Crashlytics Beta) : 17mn to 57 mn (yes...)

**Comment by SebastianThiebaud** [comment]
From Travis support:

```
It turns out our new Xcode 9.4 image had its CPU parameters misconfigured i.e. it had 1 dual-core CPU rather than 2 single core CPUs. Sorry for the inconvenience.
Our Infrastructure Team proceeded with fixing the configuration and you should now see faster builds with this image.
```

**Comment by ikesyo** [comment]
https://github.com/travis-ci/travis-ci/issues/9689#issuecomment-398876668

Xcode 9.4 image is still so slow.

<img width="1042" alt="2018-07-31 2 09 53" src="https://user-images.githubusercontent.com/909674/43412015-e070d17a-9466-11e8-8752-d9a86678c7fd.png">

**Comment by mjm** [comment]
@ikesyo Earlier this week, we fixed an issue in this image that was causing the `xcrun simctl list` command in the `announce` section of the build for Objective-C/Swift builds to take 2-3 minutes. Now it's instant, as it should be.
