### ISSUE TITLE
Travis stopped triggering on pushes for gwpy/gwpy#779

### ISSUE THREAD

**Issue by duncanmmacleod** [travis-ci/travis-ci#9691]
At some point travis-ci.com stopped triggering builds on pushes to gwpy/gwpy#779, can someone help me diagnose why that might be? I have been doing a few interactive rebases and `git push --force`, could that have confused something?

**Comment by BanzaiMan** [comment]
There were issues with your YAML file, it seems to me. https://travis-ci.com/gwpy/gwpy/requests

**Comment by duncanmmacleod** [comment]
Thanks @BanzaiMan, I had completely forgotten about that page. `travis lint` helped me remember that I can't use `[ ... ] && ...` syntax in my yaml file.

**Comment by duncanmmacleod** [comment]
I also see that you commented directly on that PR, thanks again.
