### ISSUE TITLE
PyPI Deployment Fails

### ISSUE THREAD

**Issue by alexdlaird** [travis-ci/travis-ci#9695]
I've tried so many things at this point, but my PyPI tag deployment consistently fails with the following error:

```
sh: 1: twine: not found
```

The deployment itself ends up passing, but no dist is uploaded: https://travis-ci.org/HeliumEdu/heliumcli/jobs/386780772#L724

I've tried using the twin-user-install edge, I've tried not. I've tried using `sudo`. I've tried manually installing Twine and setuptools. I've tried letting the deploy run with a different Python distro.

Where am I going wrong here?

**Comment by DrTorte** [comment]
Hey there, we do have some older reports of this. I've looked around a bit and I believe adding this to the install step might help. I did a quick test and it at least seems to recognize the command 'twine'.

`sudo -H pip install twine`

https://travis-ci.com/DrTorte/heliumcli/jobs/127187668#L680

**Comment by alexdlaird** [comment]
That did it, thanks!
