### ISSUE TITLE
"Couldn't resolve host" errors almost daily around 6–7am UTC since May 24th

### ISSUE THREAD

**Issue by kennytm** [travis-ci/travis-ci#9696]
We from rust-lang/rust have experienced a high rate of "Couldn't resolve host" errors since 2018-05-24, and it still persist till today. All errors happen inside Docker in `sudo: required` jobs. An interesting observation is that the error always happen around 06:30Z to 07:15Z, so I suspect there's some cron configuration problem.

The following lists the logs we've gathered that were affected by this bug. The timestamp is when we see the job has failed.

| Timestamp | Log | Error |
|---|---|---|
| 2018-05-24T07:14:12Z | https://api.travis-ci.org/v3/job/383034809/log.txt | `fatal: unable to access 'https://github.com/rust-lang-nursery/rust-toolstate.git/': Could not resolve host: github.com` |
| 2018-05-26T06:34:00Z | https://api.travis-ci.org/v3/job/383995388/log.txt | `curl: (6) Could not resolve host: s3-us-west-1.amazonaws.com` |
| 2018-05-27T07:02:13Z | https://api.travis-ci.org/v3/job/384282776/log.txt | `fatal: unable to access 'https://github.com/rust-lang-nursery/rust-toolstate.git/': Could not resolve host: github.com` |
| 2018-05-29T06:50:07Z | https://api.travis-ci.org/v3/job/385031055/log.txt | `curl: (6) Could not resolve host: s3-us-west-1.amazonaws.com` |
| 2018-05-30T06:47:00Z | https://api.travis-ci.org/v3/job/385518123/log.txt | `fatal: unable to access 'https://github.com/BurntSushi/xsv/': Could not resolve host: github.com` |
| 2018-05-31T06:38:08Z | https://api.travis-ci.org/v3/job/386026639/log.txt | `curl: (6) Couldn't resolve host 's3-us-west-1.amazonaws.com'` |
| 2018-06-01T06:42:09Z | https://api.travis-ci.org/v3/job/386506502/log.txt | `curl: (6) Could not resolve host: s3-us-west-1.amazonaws.com` |
| 2018-06-02T06:32:08Z | https://api.travis-ci.org/v3/job/386992985/log.txt | `curl: (6) Could not resolve host: s3-us-west-1.amazonaws.com` |
| 2018-06-03T07:10:07Z | https://api.travis-ci.org/v3/job/387315900/log.txt | `curl: (6) Could not resolve host: s3-us-west-1.amazonaws.com` |
| 2018-06-05T07:14:48Z | https://api.travis-ci.org/v3/job/388108259/log.txt | `curl error: Couldn't resolve host 'github.com'` |
| 2018-06-07T06:44:09Z | https://api.travis-ci.org/v3/job/389090019/log.txt | `curl: (6) Could not resolve host: s3-us-west-1.amazonaws.com` |

* Our current `.travis.yml`: https://github.com/rust-lang/rust/blob/edae1cc38b467518a8eea590c9c3e0c103b4ecb0/.travis.yml
* The script which starts docker: https://github.com/rust-lang/rust/blob/edae1cc38b467518a8eea590c9c3e0c103b4ecb0/src/ci/docker/run.sh

**Comment by pietroalbini** [comment]
We also tried setting fallback DNS servers in the docker containers (https://github.com/rust-lang/rust/pull/51420), but that had no effects.

**Comment by pietroalbini** [comment]
Today's failure is https://travis-ci.org/rust-lang/rust/jobs/406102611 ([raw](https://api.travis-ci.org/v3/job/406102611/log.txt)):

```
[01:33:17] testing https://github.com/servo/webrender
[01:33:17] Initialized empty Git repository in /checkout/obj/build/ct/webrender/.git/
[01:33:17] fatal: Could not parse object '57250b2b8fa63934f80e5376a29f7dcb3f759ad6'.
[01:34:13] fatal: unable to access 'https://github.com/servo/webrender/': Could not resolve host: github.com
```

**Comment by soulshake** [comment]
@kennytm From your (extremely helpful!) failure table, it appears that it happens no more than once per day. Do you ever see a second failure on the same day?

**Comment by soulshake** [comment]
@kennytm We're trying to reproduce. In the meantime, if you're so inclined, I would love to know:

- Do jobs run between 06:30Z and 07:15Z _always_ fail?
- What are the contents of `/etc/resolv.conf` and `/etc/network/interfaces` from within a job?
- Could you share the output of `docker info` and `git config --list`?

I hacked together this (as yet untested) [script](https://github.com/meatballhat/cloaked-octo-tyrion/blob/95923fb35f2c3a629a2d20b7742ceeaf18cd23b3/check-dns-bits) if it could be helpful. (Is there a specific rust-lang docker image you would recommend for testing?)

**Comment by kennytm** [comment]
@soulshake 

> Do jobs run between 06:30Z and 07:15Z always fail?

Not always. We tried to detect DNS failure previously at rust-lang/rust#51939 which itself was successful, but in between https://github.com/rust-lang/rust/pull/51762#issuecomment-401522878 did fail due to #9696. This might due to the 1.1.1.1 switch, or because 51939 did not issue any network request during that period.

> meatballhat and I hacked together this (as yet untested) script if it could be helpful.

Thanks, we'll try to deploy it and report back :)

> (Is there a specific rust-lang docker image you would recommend for testing that I could pull?)

Our docker images are at https://github.com/rust-lang/rust/tree/master/src/ci/docker; [this one](https://github.com/rust-lang/rust/blob/master/src/ci/docker/x86_64-gnu-aux/Dockerfile) should have made more network requests allowing easier reproduction. But they are not too isolated, so the easiest perhaps would be:

1. Clone the rust-lang/rust repo
2. Edit `src/ci/run.sh` and replace the content with the DNS diagnostic stuff. This is the script we'll run after entering docker.

**Comment by soulshake** [comment]
@kennytm I gather from your discussion on https://github.com/rust-lang/rust/pull/51939 that it's not necessarily the _first_ DNS lookup that fails in a given job (or even in the Bermuda window of 06:30Z to 07:15Z)?

I wonder if the extremely short TTL on these domains could have anything to do with it...

**Comment by kennytm** [comment]
@soulshake Right. In the past the failure mostly happen in the middle of the build. Take https://api.travis-ci.org/v3/job/406744794/log.txt as example,

| Time | Event |
|------|-------|
| 05:01:49 (T+00:01:10) | Docker image started |
| 06:37:35 (T+01:36:56) | Successfully clone `https://github.com/servo/webrender` |
| 06:42:51 (T+01:42:12) | Successfully cloned `https://github.com/servo/servo` |
| 06:43:25 (T+01:42:46) | Successfully cloned several repository from GitHub |
| 06:49:19 (T+01:48:40) | Successfully cloned `https://github.com/BurntSushi/xsv` |
| 06:52:37 (T+01:51:58) | Failed to resolve github.com when cloning `https://github.com/servo/webrender/` |

**Comment by cotsog** [comment]
Sorry for the delay of our reply. This issue is hard to reproduce on our side hence it makes it harder to understand what's at play here.

Would you be open to adding diagnostic commands/snippets to your .travis.yml or scripts that could help us gather insights?

Thank you for your patience!

**Comment by kennytm** [comment]
Hi @cotsog @soulshake, 

We've implemented the script in rust-lang/rust#53234 and is still trying to land this, but currently blocked by various other issues (notably https://www.traviscistatus.com/incidents/pxj3py3xzn14 yesterday).

In the meantime, we've got some leftover syslog dumping code when debugging #4924, and in https://api.travis-ci.org/v3/job/414789710/log.txt I noticed some log which seems to be relevant to this issue (there's a daily cron job involved). Hope this helps.

<details>

```
Aug 11 06:17:01 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e CRON[12690]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 11 06:25:01 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e CRON[5671]: (root) CMD (test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily ))
Aug 11 06:50:12 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e upstart-udev-bridge[694]: Disconnected from Upstart
Aug 11 06:50:12 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e upstart-socket-bridge[848]: Disconnected from Upstart
Aug 11 06:50:12 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e kernel: [ 3084.130193] init: upstart-udev-bridge main process (694) terminated with status 1
Aug 11 06:50:12 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e kernel: [ 3084.130205] init: upstart-udev-bridge main process ended, respawning
Aug 11 06:50:12 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e kernel: [ 3084.130308] init: upstart-socket-bridge main process (848) terminated with status 1
Aug 11 06:50:12 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e kernel: [ 3084.130316] init: upstart-socket-bridge main process ended, respawning
Aug 11 06:50:12 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e kernel: [ 3084.130401] init: upstart-file-bridge main process (1201) terminated with status 1
Aug 11 06:50:12 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e kernel: [ 3084.130410] init: upstart-file-bridge main process ended, respawning
Aug 11 06:50:34 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e dbus[1146]: [system] Reloaded configuration
Aug 11 06:50:35 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e dbus[1146]: message repeated 12 times: [ [system] Reloaded configuration]
Aug 11 06:50:42 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[1874]: ntpd exiting on signal 15
Aug 11 06:51:04 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e kernel: [ 3135.675641] init: apport post-stop process (3899) terminated with status 1
Aug 11 06:51:07 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e dbus[1146]: [system] Reloaded configuration
Aug 11 06:51:19 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e kernel: [ 3151.338382] systemd-udevd[5926]: starting version 204
Aug 11 06:51:20 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e dbus[1146]: message repeated 8 times: [ [system] Reloaded configuration]
Aug 11 06:51:22 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[6113]: ntpd 4.2.6p5@1.2349-o Fri Jul  6 20:19:54 UTC 2018 (1)
Aug 11 06:51:22 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[6114]: proto: precision = 0.100 usec
Aug 11 06:51:22 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[6114]: ntp_io: estimated max descriptors: 72000, initial socket boundary: 16
Aug 11 06:51:22 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[6114]: Listen and drop on 0 v4wildcard 0.0.0.0 UDP 123
Aug 11 06:51:22 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[6114]: Listen and drop on 1 v6wildcard :: UDP 123
Aug 11 06:51:22 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[6114]: Listen normally on 2 lo 127.0.0.1 UDP 123
Aug 11 06:51:22 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[6114]: Listen normally on 3 eth0 10.20.0.84 UDP 123
Aug 11 06:51:22 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[6114]: Listen normally on 4 docker0 172.17.0.1 UDP 123
Aug 11 06:51:22 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[6114]: peers refreshed
Aug 11 06:51:22 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e ntpd[6114]: Listening on routing socket on fd #21 for interface updates
Aug 11 06:51:24 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e pollinate: system was previously seeded at [2017-12-05 19:31:29.715998981 +0000]
Aug 11 06:51:24 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e pollinate: To re-seed this system again, use the -r|--reseed option
Aug 11 06:51:26 travis-job-49f4dc34-d2e1-4ae6-a27c-cdff7926474e dbus[1146]: [system] Reloaded configuration
```

(the 9696 happened near 07:08Z)

</details>

**Comment by kennytm** [comment]
Hi @cotsog @soulshake,

We have executed [the script](https://github.com/rust-lang/rust/blob/536ade5b869522b9c37380c0aaa63d1e87cb58b4/src/ci/check-dns-bits.sh) between 0610Z to 0840Z today. When the builder starts, the output was:

<details><summary>/etc/resolv.conf</summary>

```
search c.eco-emissary-99515.internal google.internal
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 1.1.1.1
nameserver 1.0.0.1
```

</details>
<details><summary>/etc/nsswitch.conf</summary>

```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

</details>
<details><summary>dig +short @8.8.8.8 github.com</summary>

```
192.30.253.112
192.30.253.113
```

</details>


When the builder ends with failure, the content of the files are the same, but the `dig` results become

```
;; connection timed out; no servers could be reached
```

The log is in https://travis-ci.org/rust-lang/rust/jobs/416672274

**Comment by soulshake** [comment]
I've reached out to GCE about this issue, and they mentioned 
> that resolv.conf gets overridden by the metadata about 1 time a day, and that could explain the moments where the Instance is not able to resolve the DNS because there are missing nameservers.

However--in a theoretical scenario where the `resolv.conf` is invalid for some period of time once per day, I would have expected https://github.com/rust-lang/rust/pull/51420 to be an effective workaround. :thinking:

**Comment by alexcrichton** [comment]
We'll try to gather some data this weekend on this if we can help.

Are we the only project running into this though? I'm not sure how our network needs would be different enough from others' to not have a lot of others chiming in here...

Additionally, by "that resolv.conf" in the reply from GCE do they mean *the* `/etc/resolv.conf` or some different one? Is there a way we can opt out of this to not have a window where configuration doesn't work?

**Comment by kennytm** [comment]
I've tried capturing the UDP port 53 traffic from the docker container in https://travis-ci.org/rust-lang/rust/jobs/457797785. The result is... expected? The DNS server simply stops replying after the magic hour.

```
06:54:45.640458 IP (tos 0x0, ttl 64, id 55077, offset 0, flags [DF], proto UDP (17), length 94)
    172.17.0.2.55032 > 169.254.169.254.53: [bad udp cksum 0x006c -> 0x267b!] 11356+ A? rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. (66)
06:54:45.640505 IP (tos 0x0, ttl 64, id 55078, offset 0, flags [DF], proto UDP (17), length 94)
    172.17.0.2.55032 > 169.254.169.254.53: [bad udp cksum 0x006c -> 0x2455!] 11879+ AAAA? rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. (66)
06:54:45.641068 IP (tos 0x0, ttl 63, id 0, offset 0, flags [none], proto UDP (17), length 207)
    169.254.169.254.53 > 172.17.0.2.55032: [udp sum ok] 11879 q: AAAA? rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. 1/1/0 rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. CNAME s3-r-w.us-west-1.amazonaws.com. ns: s3-r-w.us-west-1.amazonaws.com. SOA ns-1377.awsdns-44.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400 (179)
06:54:45.641079 IP (tos 0x0, ttl 63, id 0, offset 0, flags [none], proto UDP (17), length 141)
    169.254.169.254.53 > 172.17.0.2.55032: [udp sum ok] 11356 q: A? rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. 2/0/0 rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. CNAME s3-r-w.us-west-1.amazonaws.com., s3-r-w.us-west-1.amazonaws.com. A 52.219.28.28 (113)

// After this line 169.254.169.254:53 stops replying.

06:54:52.416710 IP (tos 0x0, ttl 64, id 55992, offset 0, flags [DF], proto UDP (17), length 94)
    172.17.0.2.44191 > 169.254.169.254.53: [bad udp cksum 0x006c -> 0x8b4e!] 61921+ A? rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. (66)
06:54:52.416752 IP (tos 0x0, ttl 64, id 55993, offset 0, flags [DF], proto UDP (17), length 94)
    172.17.0.2.44191 > 169.254.169.254.53: [bad udp cksum 0x006c -> 0x8969!] 62379+ AAAA? rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. (66)
06:54:54.919312 IP (tos 0x0, ttl 64, id 56114, offset 0, flags [DF], proto UDP (17), length 94)
    172.17.0.2.44191 > 169.254.169.254.53: [bad udp cksum 0x006c -> 0x8b4e!] 61921+ A? rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. (66)
06:54:54.919350 IP (tos 0x0, ttl 64, id 56115, offset 0, flags [DF], proto UDP (17), length 94)
    172.17.0.2.44191 > 169.254.169.254.53: [bad udp cksum 0x006c -> 0x8969!] 62379+ AAAA? rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. (66)
06:55:04.811826 IP (tos 0x0, ttl 64, id 56825, offset 0, flags [DF], proto UDP (17), length 94)
    172.17.0.2.35412 > 169.254.169.254.53: [bad udp cksum 0x006c -> 0x6b93!] 13288+ A? rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. (66)
06:55:04.811859 IP (tos 0x0, ttl 64, id 56826, offset 0, flags [DF], proto UDP (17), length 94)
    172.17.0.2.35412 > 169.254.169.254.53: [bad udp cksum 0x006c -> 0x6a4b!] 13589+ AAAA? rust-lang-ci-sccache2.s3-us-west-1.amazonaws.com. (66)
```

**Comment by soulshake** [comment]
@alexcrichton 
> Are we the only project running into this though? I'm not sure how our network needs would be different enough from others' to not have a lot of others chiming in here...

As far as I know, you're the only ones to report this. However, I wouldn't rule out the possibility that it's happening to others without the pattern being noticed; or perhaps it only happens with jobs starting at a certain time that are still running 1 hour later; or some other unique set of circumstances that your project is rare in meeting, etc.

> Additionally, by "that resolv.conf" in the reply from GCE do they mean the /etc/resolv.conf or some different one?

Yes, they mean `/etc/resolv.conf`. 

> Is there a way we can opt out of this to not have a window where configuration doesn't work?
I'll ask.

@kennytm thank you very much for the tcpdump snippet. When I shared it on the GCP support ticket, I received this response:

```
About the metadata server stop replying, the dumps shows a sequence of "bad udp cksum" and 
this is due to the TCO (tcp offloading). please check this third-party guide on how to disable it 
for a clean tcpdump[1].

[1] https://sokratisg.net/2012/04/01/udp-tcp-checksum-errors-from-tcpdump-nic-hardware-offloading/
```

When I pointed out that the `bad udp cksum` occur in the successful lookups too, this was the reply:
```
Since the dump provided is a really small extract from the traffic, and includes all the 
bad cksum, the first 2 answers from the metadata server are probably not linked to 
the same 2 requests done before that.

It is possible that it takes hundreds requests to have one that goes through, that is 
why filtering out the errors, we can have a better idea of what is really happening.

I also believe that a re-run of the tcpdumps will not help, as the ideal is to work it on 
pairs: the source and destination dump at the same time. Since it is not possible as 
you do not control the destination (metadata server) having half of the conversation 
will create more question than answers.

Even if I obtain the dumps from the metadata, if they are not synchronized, they are 
not useful as well.

Unfortunately, the provided instance is not available anymore for inspection.

What you can use as troubleshooting tool is to have another small Instance querying 
the DNS as a control group, if the issue happens to that instance, the issue is related 
to the DNS, if not is related to the Docker request for the DNS.

Please let me know if this line of investigation is possible on your side.
```

Just to confirm--I know this is happening in DNS lookups from within Docker in your jobs. Have you noticed if it also happens outside Docker in the same timeframe?

**Comment by soulshake** [comment]
FYI, I set up a Travis job to make continuous DNS queries [here](https://travis-ci.org/soulshake/startup-threads-cli/builds).

**Comment by soulshake** [comment]
I believe I've reproduced the issue: in a job that does continuous DNS lookups, both from the host and from a container, the lookups in a container start failing each morning at the same time.

Here's sample output from when the failure occurs:

```
---> Fri Dec 7 06:40:22 UTC 2018: try 3 github.com via 169.254.169.254:
192.30.253.113
192.30.253.112
192.30.253.113
192.30.253.112
and in docker:
** WARNING: IPv4 forwarding is disabled. Networking will not work.
** ;; connection timed out; no servers could be reached
x Failed to lookup github.com via @169.254.169.254 (docker)
```

Lines prepended with `**` are output from if `! docker run -ti tutum/dnsutils dig +short "@${nameserver}" "${h}"`.
in 2/3 cases so far, once it starts failing in a job, it continues failing for the rest of the job:

1. https://travis-ci.org/soulshake/startup-threads-cli/builds/463852133 (started failing at Wed Dec 5 13:58:20 UTC, but recovered; I think this one is a fluke)
2. https://travis-ci.org/soulshake/startup-threads-cli/builds/464187798 (started failing at Thu Dec 6 06:34:32 UTC)
3. https://travis-ci.org/soulshake/startup-threads-cli/builds/464807049 (started failing at Fri Dec 7 06:38:58 UTC)

[This](https://github.com/soulshake/startup-threads-cli/blob/master/check-dns-bits#L35) is the script I'm using.

Of note: these jobs failed within 4 minutes of each other around 06:35UTC, and they both started producing a `WARNING: IPv4 forwarding is disabled. Networking will not work.`

I've asked GCE if they have an automated process that would modify IPv4 forwarding on instances, i.e. by restoring the system's default for sysctl values.

**Comment by soulshake** [comment]
I updated my test to check IPv4 forwarding status, and it seems that it's indeed getting changed once per day, right around 07:00 UTC.

Before Docker DNS lookup failures start:
```
ipv4 forwarding on host: net.ipv4.ip_forward = 1
ipv4 forwarding in docker: net.ipv4.ip_forward = 1
```

and after:

```
ipv4 forwarding on host: net.ipv4.ip_forward = 0
WARNING: IPv4 forwarding is disabled. Networking will not work.
ipv4 forwarding in docker: net.ipv4.ip_forward = 0
```

I will look into options for dealing with this on our end.

**Comment by soulshake** [comment]
We're in the process of creating updated `xenial` images which, once deployed this week, should fix this issue. (We're not making further updates to our `trusty` images as they will be EOL in April 2019.) 

If you're not ready to update your Travis config to use `dist: xenial` yet, you can add your own file to `/etc/sysctl.d/` that follows `99-gce.conf` alphabetically and ensure it contains `net.ipv4.ip_forward = 1`, like so:

```
before_install:
  - echo "net.ipv4.ip_forward = 1" | sudo tee /etc/sysctl.d/99-ipv4-forward-pls.conf
```
Could you give this a try and let me know if you encounter any further failures?

Thank you all for your patience and help in tracking this down. We really appreciate it.

**Comment by soulshake** [comment]
**Correction**: the updated `xenial` images won't be deployed until the next time we release a new `stable` tag, which may be several months from now. So you can either:
- specify `group: edge` to get this change in `xenial` now, or 
- wait until we issue a runtime patch for `trusty` as well as `xenial` (this week). 

Sorry for the earlier misinfo.

**Comment by kennytm** [comment]
@soulshake Thanks! We're going to upgrade to `xenial` for now, and let the patch naturally be applied next `stable`.

**Comment by soulshake** [comment]
@kennytm We released a new stable Xenial image yesterday, so this issue should no longer occur. I'm going to mark it as resolved for now, but please feel free to reopen if you run into this behavior again.

Thanks again for your patience and helpful contributions! :heart:
