### ISSUE TITLE
Slack notifications doc should indicate API endpoints explicitly

### ISSUE THREAD

**Issue by akerl** [travis-ci/travis-ci#9697]
Similar to https://github.com/travis-ci/travis-ci/issues/6528 , if I use the following it works:

https://github.com/amylum/zlib/blob/5e1e2db932a2664554eee56ab63f38b07e22ef06/.travis.yml

```
notifications:
  slack: akerl:KxboLZkca8LOPq5c6u03WcaA
```

But when I do this, it doesn't:

https://github.com/amylum/zlib/blob/99d270ed21d4e234bacd29956c4ed646d626900e/.travis.yml

```
notifications:
  slack:
    secure: "q1P3zdEXIAguruaENZQyrymb82Jn37vI0y0SeLbcRbv8otf70dzX60Ei81kYzeiZ6aEj1M11KjkX3KiqDpWb850qSoqjSPsAda9t/EVimJrNEpxi2sJcRz/oHNBZn9f0RdegRSuHZRNG45HnsxnDgpbLsd4h7pKyKbw9+gtwYy+q6xLXf8WnzTj20cT/u889AiC4az0VFvG2RjM7sWgyF+CHycQybo4x+bJI5OK/9Fsl6Dlx7hSoOOd9V5QVnCW2EQ1/usKModzBYIUWSkgIhWYCGZrzMVOoAYcDJxcS6of0Mi9WkMqrlNw8CrTRm9gzbEvM9RVhuKqMPSIz+ELq3NmI0o+KXd3cr/yjjiai09vjq3SV1ISZp1Al+9RHZ2mJl2Ks4SVUkFpoCNJt7xX4fu2WOU+1WhG0SM5KaCR1D1COVmLQ41tQkFc+Ss2SdaIG1HPDxvL78uaaDYrNGgIdoWWmB01zNjyd4hwwjmCtCe7dbQFzLaVkgAyfWAQ657XAlXZ0mi7RR8Cx7RO6+LBighqivcgWpgVsXz+IOwcaXvt0XgGUdGAbR7yrLfJtPFeBcDJJssrGyIidGRzlafApZLRIUUFvn47/DiM6bhYpmR7co/z/Ia6uryLu0QrOjcjSdBWwYL/7QShqDevD2WqG69GSlMOhogNy9a+o48VJkJs="
```

**Comment by mtslzr** [comment]
Same issue here. It works unencrypted, but no setup using `secure` gets posted to Slack. Tried with no quotes, single- and double-quotes, with and without `rooms:`, and using encrypt with and without `-r`.

**Comment by maestromac** [comment]
I got it working by appending `--com`. I had a suspicion after I ran `travis open` and it opened up a travis-ci.org link to my repository, which is not where my repository is.

my full command was 
```
travis encrypt "<your-slack-workspace:<-token>" --add notifications.slack --com
```

does travis cli's command default to `--org`? 🤔

Hope this helps.

**Comment by mtslzr** [comment]
Perfect, great catch @maestromac! Works here; not sure if it's a recent thing because of the push to .com, or because mine is a free account the originated with .org, but either way. Hopefully they can update the Slack instructions for it in the future.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by Sojisoyoye** [comment]
Great job @maestromac, was on this for about two days, adding `--com` as you suggested solved it for me too. Travis/slack should update this on the documentation to save the stress of trying to figure out what is wrong. 

So basically if your repository is on https://travis-ci.com, then you should add `--com` to the Travis encrypt command, because without specifying it would default to .org
