### ISSUE TITLE
Android builds route to GCE every time? And travis-compile doesn't work...

### ISSUE THREAD

**Issue by mikehardy** [travis-ci/travis-ci#9700]
Hello! This is more of an informational issue.

My goal is to improve travis-ci build times. I've read the docs to get suggestions on the same, and one of the recommendations is to make sure your build can use the EC2 containers vs the GCE environment, if your projects tests can be run there.

My project is language: android and though we don't use sudo or docker and happily use trusty stable, I can't see any combination of things with language: android that route to EC2, contrary to the docs:
https://docs.travis-ci.com/user/reference/overview/#For-a-particular-.travis.yml-configuration

You can see a test config here that was routed to GCE even though it attempts almost nothing (on purpose):
https://travis-ci.com/mikehardy/Anki-Android/jobs/127286168/config

If all android builds will go to GCE regardless, perhaps the documentation could be updated to save times for future optimizers?

Also worth noting that I attempted to follow these instructions to parse .travis.yml in a local Docker container, and was unable to do so with known-good .travis.yml files (including the main android/Anki-Android project) - every attempt failed with an "unknown error":

https://github.com/travis-ci/travis.rb#installation + https://github.com/travis-ci/travis-build#use-as-addon-for-cli

Seems the travis-build project should have a .travis.yml that verifies travis-ci + travis-build can be successfully installed and render a build.sh from a .travis.yml ;-)

All that aside, I'm obviously using the heck out of travis and I really appreciate that it exists, it is amazingly useful. Thank you!

**Comment by mikehardy** [comment]
> We'll gladly take a look again!

That would apply if it had been looked at.

**Comment by BanzaiMan** [comment]
Android builds are indeed routed to GCE, because they tend to require a lot of memory and in general experiences on containers were not great.

I am curious where we indicate this:

> one of the recommendations is to make sure your build can use the EC2 containers vs the GCE environment, if your projects tests can be run there.

There seems to be some confusing documentation.

**Comment by mikehardy** [comment]
Hi @BanzaiMan - I looked through the documentation again and it must have been a 3rd party site that had a firm recommendation. In the 1st party docs the containers are clearly emphasized and their performance is noted (especially the startup time) but there is some balance for heavy IO requirements and such. It might be good to mention that android goes to GCE regardless of sudo in the docs though, as it was obviously confusing to me at least :-). Slightly related to this, I put a test that was also documentation-related (i.e., it matched what the docs said you should do to get travis-cli working locally) in a PR to demonstrate a failure and it too just sat there https://github.com/travis-ci/travis-build/pull/1405/commits/15174fdd51c1dae88845b1ee1c875f80f5bc7201
