### ISSUE TITLE
GitLab integration?

### ISSUE THREAD

**Issue by daveloyall** [travis-ci/travis-ci#9702]
Hello!  [GitLab has become more popular](https://www.bleepingcomputer.com/news/technology/gitlab-sees-huge-traffic-spike-after-news-of-microsoft-buying-github/) since [last time GitLab / travis-ci integration was discussed](https://github.com/travis-ci/travis-ci/issues/5931).

Please re-evaluate.  Some projects want to migrate away from github but want to keep travis-ci, if they can.

**Comment by larsbrinkhoff** [comment]
Agreed.  We're considering moving from GitHub to GitLab, but we'd like to keep Travis CI.

**Comment by larsbrinkhoff** [comment]
It's most likely not solved at all.

**Comment by DrTorte** [comment]
Hello,

At this point we have no plans to share regarding GitLab support.

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. Please feel free to create a thread there for this or any other suggestions you have.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
