### ISSUE TITLE
When will Travis CI support .Net Core 2.1 ?

### ISSUE THREAD

**Issue by ngohungphuc** [travis-ci/travis-ci#9703]
I get this log message when running CI with .Net Core 2.1 app. When will Travis CI support .Net Core 2.1 ? 
> The current .NET SDK does not support targeting .NET Core 2.1

**Comment by BanzaiMan** [comment]
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by AArnott** [comment]
@ngohungphuc I got that message too, till I updated my `.travis-ci.yml` file to specify `dotnet: 2.1.300` as required for .NET Core 2.1 support.

After I did that, it works on linux, but [fails on Mac](https://travis-ci.org/Microsoft/vs-streamjsonrpc/jobs/388061402) with this error:

> /Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/msbuild/15.0/bin/NuGet.targets(104,5): error : Package integrity check failed. [/Users/travis/build/Microsoft/vs-streamjsonrpc/src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj]
/Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/msbuild/15.0/bin/NuGet.targets(104,5): warning : The primary signature should be timestamped to enable long-term signature validity after the certificate has expired. [/Users/travis/build/Microsoft/vs-streamjsonrpc/src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj]
/Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/msbuild/15.0/bin/NuGet.targets(104,5): warning : UntrustedRoot [/Users/travis/build/Microsoft/vs-streamjsonrpc/src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj]

I don't know how to fix that.

**Comment by ngohungphuc** [comment]
@AArnott thank I will try with your suggest

**Comment by ngohungphuc** [comment]
@all. For anyone have issue like me just change dotnet version like this and you should be good to go
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/blob/master/.travis.yml

**Comment by AArnott** [comment]
Can you please reopen this? I believe the Mac problem I report above remains.

**Comment by ngohungphuc** [comment]
@AArnott sure let just wait for confirm

**Comment by NicolasDorier** [comment]
Actually you need to precise `2.1.300` (not 2.1 only) on mac (https://github.com/MetacoSA/NBitcoin/commit/4ba702be856b167ea53269b495526174a21779a2)

**Comment by AArnott** [comment]
Thanks, @NicolasDorier. I am using 2.1.300 when I see the certificate error.

**Comment by NicolasDorier** [comment]
@AArnott it is strange, you say you are using .NET 2.1 but the logs shows it is trying to build on mono.

This one seems to work for me, it is running the tests as I talk https://github.com/MetacoSA/NBitcoin/blob/4ba702be856b167ea53269b495526174a21779a2/.travis.yml

**Comment by AArnott** [comment]
Yes, I require .NET Core 2.1 to run tests, but I build with mono's msbuild.exe because `dotnet build` cannot find the .NET desktop target frameworks. This has always worked... up till we hit .NET Core 2.1 on Mac.

**Comment by AArnott** [comment]
@NicolasDorier In trying out various combinations to see if I can find one that works, I notice that the `dotnet:` line in travis-ci.yml seems to refer to .NET Core SDK versions. How can I ensure that specific versions of the .NET Core *runtime* is also installed? For example, I need the .NET Core 1.0.11 runtime version installed to test against.

**Comment by AArnott** [comment]
I tried this:

```yml
# dotnet versions come from https://www.microsoft.com/net/download/all
dotnet:
  - 1.1.9   # Latest .NET Core 1.1 Runtime
  - 2.1.200 # Latest 2.0 Runtime
  - 2.1.300 # Latest 2.1 Runtime
mono: 5.10.0
```

But that [failed](https://travis-ci.org/Microsoft/vs-streamjsonrpc/jobs/388827658) with 

> [1.1.9, 2.1.200, 2.1.300] is either an invalid version of dotnet or unsupported on this operating system.
> View valid versions of dotnet at https://docs.travis-ci.com/user/languages/csharp/

Yet [that page](https://docs.travis-ci.com/user/languages/csharp/#.NET-Core) doesn't mention the allowed .NET Core versions at all except to reference the .NET Core web site, and [this downloads page](https://www.microsoft.com/net/download/all) tells me all these versions are real.

**Comment by AArnott** [comment]
So I eventually [got it to work](https://github.com/Microsoft/vs-streamjsonrpc/pull/118/files#diff-354f30a63fb0907d4ad57269548329e3), but sadly I had to basically ignore the built-in dotnet support. I download and use the `dotnet-install.sh` script myself, and invoke it several times for the various runtime versions.

**Comment by NicolasDorier** [comment]
Your build is more complex than mine. I use `dotnet: 2.1.300` with success on `osx` on linux I use `2.1`.

Unsure about `2.1.200`, maybe retired?

Anyway I think `dotnet-install.sh` is not bad workaround, but increase your build time :(

**Comment by AArnott** [comment]
Per the [downloads page](https://www.microsoft.com/net/download/all), 2.1.200 is actually an SDK version for the 2.0 runtime version.

Actually the installation time for the `dotnet-install.sh` script wasn't bad. It might even be faster than I had it before.

**Comment by akoeplinger** [comment]
Yes, the `dotnet` line refers to the version of the .NET Core SDK, mostly because that made the most sense when I implemented this. I'd appreciate hearing opinions on how to expose the runtime versions as well.

**Comment by AArnott** [comment]
Yes, I agree the SDK version here makes sense. I can't think of any reason we'd want multiple SDK versions installed. But multiple runtime versions are useful when targeting multiple runtime versions. Perhaps `dotnet:` can continue to refer to an SDK, and then a `dotnet_runtimes: [ ]` can be an array of runtime versions to install (in addition to the version of the runtime that came with the SDK).

**Comment by AArnott** [comment]
It's been running well for months. I'm trying to activate a new repo and running into problems because `dotnet build` fails with `libunwind` not being found. Travis CI [won't let me install it](https://travis-ci.org/AArnott/Nerdbank.Streams/jobs/420637658). Any idea why?

**Comment by AArnott** [comment]
Adding `dist: xenial` fixed it.

**Comment by gsuberland** [comment]
This does not appear to be working on Windows.

For Linux, this config works:

```
language: csharp
mono: none
dotnet: 2.1.300
install:
  - dotnet restore
script:
  - dotnet build
```

When adding Windows, however, it fails:

```
language: csharp
mono: none
dotnet: 2.1.300

os:
  - linux
  - windows

install:
  - dotnet restore

script:
  - dotnet build
```

The error given is "2.1.300 is either an invalid version of dotnet or unsupported on this operating system."

Taking advice from #9359, I rolled the version number back to 2.1.101, and this failed on both Linux and Windows.

**Comment by Joshua-Anderson** [comment]
C# doesn't currently support windows (contributions welcome!) so that's a separate issue that should be fixed in the future!

**Comment by gsuberland** [comment]
@Joshua-Anderson I don't know Ruby, so unfortunately I can't contribute here. I don't see an open issue for adding support though; did I miss one or should I open a new issue?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
