### ISSUE TITLE
Deploy to npm does nothing.

### ISSUE THREAD

**Issue by hbowden** [travis-ci/travis-ci#9704]
I'm trying to get Travis CI to deploy my npm package whenever a commit is pushed to the master branch and passes all tests. However nothing happens. I get no output from Travis CI. Travis CI should output either an error message or a success message I currently get nothing. Below is my .travis.yml with the api_key redacted. Here is the branch in question. https://github.com/hbowden/react-atlas/tree/0.1.0rc-build

```language: node_js
sudo: false
node_js:
- '6'
install:
- npm install
script:
- npm run build:prd
- npm run lint
- npm run test
deploy:
  provider: npm
  email: hbow1001@gmail.com
  api_key:
    secure: 
  tag: next
  on:
    tags: false
```

Here's is a screenshot showing no output from Travis CI about deploying the npm package.

![2018-06-04 11_14_23-build 661 - digitalriver_react-atlas - travis ci](https://user-images.githubusercontent.com/12447474/40928924-961a763a-67e8-11e8-9dcc-92313648dc5a.png)

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!
