### ISSUE TITLE
Travis Compile in local docker container

### ISSUE THREAD

**Issue by ekivolowitz** [travis-ci/travis-ci#9709]
This is in regards to [this](https://travis-ci.org/ekivolowitz/TravisTest) project with [source code here](https://github.com/ekivolowitz/TravisTest)

I pulled the most recent travis-ci default docker image `travisci/ci-garnet:packer-1512502276-986baf0` and followed the instructions. I have followed through the instructions in #8098 which resolved the first issue I encountered. However, after running `travis compile` I encountered the following error:
```
/home/travis/.travis/travis-build/lib/travis/build/appliances/validate.rb:36:in `config_status': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/validate.rb:36:in `config_status': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/setup_filter.rb:84:in `enabled?': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/wait_for_network.rb:47:in `block in check_urls': Travis::Build::Appliances::Base#app_host at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#app_host
/home/travis/.travis/travis-build/lib/travis/build/appliances/debug_tools.rb:15:in `apply': Travis::Build::Appliances::DebugTools#debug_enabled? at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#debug_enabled?
/home/travis/.travis/travis-build/lib/travis/build/appliances/services.rb:61:in `services': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Python#config
echo -e ""
echo -e "There was an error in the .travis.yml file from which we could not recover.
"
echo -e "Unfortunately, we do not know much about this error."
echo -e ""
echo -e "Please review https://docs.travis-ci.com"
exit 2
```
I ran `travis lint` on my `.travis.yml` file and it said that my file was valid. I'm not sure what to do here because it runs without issue online, but fails locally.

Thanks,
Evan

**Comment by higis927** [comment]
Have the same issue, and my error with **travis compile** 
`'os' key is unsupported in local build script compilation. Setting to default, 'linux'.
echo -e ""
echo -e "There was an error in the .travis.yml file from which we could not recover.
"
echo -e "Unfortunately, we do not know much about this error."
echo -e ""
echo -e "Please review https://docs.travis-ci.com"
exit 2`

**Comment by ekivolowitz** [comment]
Update: Ran with `--debug` and `--debug-http`

```
** Loading "/home/travis/.travis/config.yml"
** Timeout::Error: execution expired
env.matrix key is ignored
/home/travis/.travis/travis-build/lib/travis/build/appliances/validate.rb:36:in `config_status': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Ruby#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/validate.rb:36:in `config_status': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Ruby#config
/home/travis/.travis/travis-build/lib/travis/build/addons/base.rb:20: warning: constant ::Fixnum is deprecated
/home/travis/.travis/travis-build/lib/travis/build/appliances/setup_filter.rb:84:in `enabled?': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Ruby#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/wait_for_network.rb:47:in `block in check_urls': Travis::Build::Appliances::Base#app_host at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Ruby#app_host
/home/travis/.travis/travis-build/lib/travis/build/appliances/debug_tools.rb:15:in `apply': Travis::Build::Appliances::DebugTools#debug_enabled? at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Ruby#debug_enabled?
/home/travis/.travis/travis-build/lib/travis/build/appliances/services.rb:61:in `services': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::Ruby#config
echo -e ""
echo -e "There was an error in the .travis.yml file from which we could not recover.
"
echo -e "Unfortunately, we do not know much about this error."
echo -e ""
echo -e "Please review https://docs.travis-ci.com"
exit 2
** Storing "/home/travis/.travis/config.yml"

```

**Comment by ekivolowitz** [comment]
I've started tracing through the code and found that it boils down to a variable that shouldn't be Nil, is Nil.
Note that the line numbers will be slightly off as I've added debugging code.
```
System
Ruby:                     Ruby 2.3.0-p0
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.8
Plugins:                  "travis-build"
Auto-Completion:          yes
Last Version Check:       2018-06-14 15:31:25 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "ekivolowitz"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis compile`:
    TypeError: can't dup NilClass
        from /home/travis/.travis/travis-build/lib/travis/shell/generator.rb:25:in `dup'
        from /home/travis/.travis/travis-build/lib/travis/shell/generator.rb:25:in `handle'
        from /home/travis/.travis/travis-build/lib/travis/shell/generator.rb:14:in `generate'
        from /home/travis/.travis/travis-build/lib/travis/shell.rb:10:in `generate'
        from /home/travis/.travis/travis-build/lib/travis/build/script.rb:318:in `show_compile_error_msg'
        from /home/travis/.travis/travis-build/lib/travis/build/script.rb:88:in `rescue in compile'
        from /home/travis/.travis/travis-build/lib/travis/build/script.rb:76:in `compile' <-- compilation error.
       
       from /home/travis/.travis/travis-build/init.rb:62:in `run'
       #this line is actually puts. I added debug code which throws off the line numbers
       Travis::Build.script(push_down_deploy(@compile_config)).compile(true)       
       
       from /home/travis/.rvm/gems/ruby-2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /home/travis/.rvm/gems/ruby-2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /home/travis/.rvm/gems/ruby-2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /home/travis/.rvm/gems/ruby-2.3.0/bin/travis:23:in `load'
        from /home/travis/.rvm/gems/ruby-2.3.0/bin/travis:23:in `<main>'
        from /home/travis/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/travis/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by satyamakgec** [comment]
@ekivolowitz  I am facing the same Issue now, You also raised a PR on my repo that makes my travis lint valid but somehow still not able to compile the same on my local system. 
getting errors- 

> matrix key is ignored
/home/travis/.travis/travis-build/lib/travis/build/appliances/validate.rb:36:in `config_status': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::NodeJs#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/validate.rb:36:in `config_status': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::NodeJs#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/setup_filter.rb:84:in `enabled?': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::NodeJs#config
/home/travis/.travis/travis-build/lib/travis/build/appliances/wait_for_network.rb:47:in `block in check_urls': Travis::Build::Appliances::Base#app_host at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::NodeJs#app_host
/home/travis/.travis/travis-build/lib/travis/build/appliances/debug_tools.rb:15:in `apply': Travis::Build::Appliances::DebugTools#debug_enabled? at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::NodeJs#debug_enabled?
/home/travis/.travis/travis-build/lib/travis/build/appliances/services.rb:61:in `services': Travis::Build::Appliances::Base#config at /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Travis::Build::Script::NodeJs#config
echo -e ""
echo -e "There was an error in the .travis.yml file from which we could not recover.
"
echo -e "Unfortunately, we do not know much about this error."
echo -e ""
echo -e "Please review https://docs.travis-ci.com"
exit 2

How do I solve my issue here.

**Comment by satyamakgec** [comment]
@ekivolowitz  Thanks for you continous efforts and time. Really appreciated

I don't know too much about the travis trying to follow the steps. 

Steps are followed - 
1. docker run --name travis-debug -dit travisci/ci-garnet:packer-1512502276-986baf0 /sbin/init
2. docker exec -it travis-debug bash -l
3. su - travis
4. rvm install 2.3.0
5. rvm use 2.3.0
6. cd builds 
7. git clone https://github.com/ekivolowitz/travis-build.git     --- here I am cloning your fork.
8. cd travis-build 
9. gem install travis
10. travis # to create ~/.travis
11. ln -s `pwd` ~/.travis/travis-build 
12. bundle install
13. cd ..
14. Clone the repo. - git clone https://github.com/PolymathNetwork/polymath-core.git
15. cd  polymath-core
16. travis compile > ci.sh

Then I got some error so I use that solution recommended somewhere on github
1. cd ~/.travis/travis-build/
2. bundle install
3. bundler add travis
4. bundler binstubs travis
5. cd <REPO_YOU_WANT_TO_RUN_COMPILE_IN>
6. ~/.travis/travis-build/bin/travis compile

After trying this remedy I am getting the error that I showed in my above comment.

**Comment by ekivolowitz** [comment]
```
docker run --name travis-debug -dit travisci/ci-garnet:packer-1512502276-986baf0 /sbin/init
docker exec -it travis-debug bash -l
su - travis
rvm install 2.3.0
rvm use 2.3.0
cd builds
git clone --branch issue_9709_fix https://github.com/ekivolowitz/travis-build.git --- here I am cloning your fork.
cd travis-build
gem install travis
travis # to create ~/.travis
ln -s pwd ~/.travis/travis-build
bundle install
cd ..
rm -rf ~/.travis/travis-build && mv travis-build ~/.travis/
#Travis compile should now show up in the travis command list, but it's broken. 
Clone the repo. - git clone https://github.com/PolymathNetwork/polymath-core.git
cd polymath-core
# if you run travis compile here in your repo, you'll get an error about missing support libraries. Install them with the following. 
cd ~/.travis
git clone https://github.com/travis-ci/travis-support.git
git clone https://github.com/travis-ci/travis-rollout.git
git clone https://github.com/travis-ci/travis-github_apps.git
cd travis-github_apps && gem build travis-github_apps.gemspec && gem install travis-github_apps && cd ..
cd travis-rollout/ && gem build travis-rollout.gemspec && gem install travis-rollout && cd ..
cd travis-support/ && gem build travis-support.gemspec && gem install travis-support && cd ..
cd ~/builds/polymath-core && travis compile > build.sh && chmod +x build.sh && ./build.sh
```

**Comment by satyamakgec** [comment]
@ekivolowitz Thanks a ton It works properly on my local and my coverage report get generated without any timeout. But When I run the same `.travis.yml` over the `travis-ci` it gave me a timeout error. Is as you mentioned it behave differently from the local so is there any way to increase the timeout time other than `travis_wait`.

And yes, You helped a lot, we will definetly consider you as our opensource community contributor or we will put up your handle on our release thank note.
