### ISSUE TITLE
Machines randomly failing, compilers can't be found. Can't install anything on OS X with brew correctly ?

### ISSUE THREAD

**Issue by justinjk007** [travis-ci/travis-ci#9718]
https://travis-ci.org/justinjk007/JSO

Why are all OS X builds failing ? Actually none of these failures are due to regression, compiler can be found even after installing them ? Are these machines/VMs up?

This is simple project with basic setup and travis setup straight up from your documentation.

**Comment by justinjk007** [comment]
GCC 7 seems to be having problems correctly installing

**Comment by BanzaiMan** [comment]
Don't you mean `gcc@7`? https://formulae.brew.sh/formula/gcc@7
