### ISSUE TITLE
Result says "All checks have failed" when 1 check is failed.

### ISSUE THREAD

**Issue by pasindujw** [travis-ci/travis-ci#9719]
Please see the image below.
![allcheck](https://user-images.githubusercontent.com/8229975/41143739-10220d1c-6b18-11e8-9c5e-9068cabef0f1.png)

**Comment by pasindujw** [comment]
Its not being addressed yet.

**Comment by BanzaiMan** [comment]
Hello, there. Could you elaborate on what you are reporting? There was a failure and the failure is reported accordingly. Or, are you pointing out a grammatical incosistency?

**Comment by pasindujw** [comment]
Hi Banzai, yes its a simple grammatical inconsistency as I'm seeing. The failure message says 'All Checks have failed' even if one check of the list has failed. I think the topic could be something like;
**1 check has failed
2 checks have failed**

Regards,
Pasindu

**Comment by BanzaiMan** [comment]
That message is coming from GitHub. I suggest getting in touch with them.

**Comment by ghost** [comment]
This issue is not related to your code it’s due to some old PRs Laurent is already aware of it.

**Comment by je-almeida** [comment]
how solve this?

**Comment by CaneteJoash** [comment]
how to solve this ?

**Comment by KelvinCheng5507** [comment]
how to solve this?

**Comment by izabelaszk** [comment]
sadge

**Comment by Choi-soohyun** [comment]
I made a new repository and worked on it again. So I solved it.

The same error happened at first and it was possible to do it with a new repository because I worked alone, but I think it would be terrible if many people worked together.
