### ISSUE TITLE
Unexpected behaviour with Build Stages UI

### ISSUE THREAD

**Issue by knassef** [travis-ci/travis-ci#9721]
Hi !

I encountered an unexpected behaviour while I was using the Build Stages feature from the browser. When trying to pause the build, I clicked on the small stop button next to a certain stage. This successfully paused the current stage but started building the next one. This caused an unintended deployment to production as I wanted to stop the build at the stage before as seen in the attached image.

<img width="952" alt="travis" src="https://user-images.githubusercontent.com/16574623/41156631-0edf1fac-6b23-11e8-95b6-83f26c2b745c.png">

So as you can see, `Smoketest` stage was paused but `Deploy to production` continued normally.

Please let me know if you need any more details from my side.

Thanks in advance!

**Comment by BanzaiMan** [comment]
Sorry for the delay.

When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by knassef** [comment]
Hi Banzai,

Thanks for reopening the issue, unfortunately I no longer have access to this project. However, as far as I remember this was happening to all deployments, so its a general behaviour and not a bug. Is the problem clear from my explanation ? I would've expected the build to completely stop when stopping one of the stages and not continue to the next step.

Cheers!

**Comment by BanzaiMan** [comment]
@knassef Yes, the problem seems clear to me, but I have not seen anything like it before, so I would like to take a look at a concrete case. Is there anyone else who might have access to this problem? (I understand if you wish to not contact your previous employer/client.)

**Comment by BanzaiMan** [comment]
I'm closing this for now. If anyone else is seeing a similar issue, please report it with detail at https://travis-ci.community/

Thanks.
