### ISSUE TITLE
Julia pkg testing fails on linux, works fine on OSX (and appveyor)

### ISSUE THREAD

**Issue by goedman** [travis-ci/travis-ci#9722]
Since yesterday I get below error message, only on linux. I noticed it the first time after I erroneously added stdlib packages to a REQUIRE file in PtFEM which was fixed thanks to @andreasnoack and @fredrikekre ( https://github.com/JuliaLang/METADATA.jl/pull/15061 ). In some steps on Travis, testing seems to be ok with this error, but not for testing the actual package.

@tkelman @ninjin @staticfloat @simonbyrne

------------

0.19s$ julia -e 'using Pkg; Pkg.add("Compat"); Pkg.test("HyperDualNumbers"; coverage=true)'
fatal: error thrown and no exception handler available.
InitError(mod=:LibGit2, error=ErrorException("could not load library "libgit2"
libssl.so.10: cannot open shared object file: No such file or directory"))
rec_backtrace at /buildworker/worker/package_linux64/build/src/stackwalk.c:94
record_backtrace at /buildworker/worker/package_linux64/build/src/task.c:246
jl_throw at /buildworker/worker/package_linux64/build/src/task.c:577
jl_errorf at /buildworker/worker/package_linux64/build/src/rtutils.c:77
jl_dlerror at /buildworker/worker/package_linux64/build/src/dlload.c:74 [inlined]
jl_load_dynamic_library_ at /buildworker/worker/package_linux64/build/src/dlload.c:196
jl_get_library at /buildworker/worker/package_linux64/build/src/runtime_ccall.cpp:48
jl_get_library at /buildworker/worker/package_linux64/build/src/runtime_ccall.cpp:56 [inlined]
jl_load_and_lookup at /buildworker/worker/package_linux64/build/src/runtime_ccall.cpp:59
jlplt_git_libgit2_init_17589.clone_1 at /home/travis/julia/lib/julia/sys.so (unknown line)
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LibGit2/src/error.jl:100 [inlined]
__init__ at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LibGit2/src/LibGit2.jl:969
jfptr___init___17588.clone_1 at /home/travis/julia/lib/julia/sys.so (unknown line)
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1538 [inlined]
jl_module_run_initializer at /buildworker/worker/package_linux64/build/src/toplevel.c:90
_julia_init at /buildworker/worker/package_linux64/build/src/init.c:810
julia_init__threading at /buildworker/worker/package_linux64/build/src/task.c:302
unknown function (ip: 0x401517)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4015c4)
The command "julia -e 'using Pkg; Pkg.add("Compat"); Pkg.test("HyperDualNumbers"; coverage=true)'" exited with 1.
Done. Your build exited with 1.

**Comment by andreasnoack** [comment]
This is a Julia issue. See https://github.com/JuliaLang/julia/commit/4a303b30e52a3a5892354239a472401c37612db4#commitcomment-29274618

**Comment by goedman** [comment]
Thanks Andreas! I’ll close this issue in a few days.

**Comment by goedman** [comment]
Fixed!
