### ISSUE TITLE
Nix daemon with sandbox enabled

### ISSUE THREAD

**Issue by zimbatm** [travis-ci/travis-ci#9724]
It would be great if both the Ubuntu and macOS versions would install Nix in the multi-user and sandboxed mode for more consistency.

Currently:
* macOS is installed in multi-user mode but doesn't have sandboxing enabled.
* Ubuntu is installed in single-user mode and doesn't have sandboxing enabled.

I have been testing a few options but the `nix.install` step is not overridable in a normal CI build, which leads to issue when trying to install Nix twice.

What is the best way to build and test the Nix integration with Travis?

 cc @domenkozar @garbas @matthewbauer

Addendum: it would be great if trusted caches could also be configured as travis.yml options

**Comment by zimbatm** [comment]
related: https://github.com/NixOS/nix/pull/1152#issuecomment-378108301

**Comment by domenkozar** [comment]
I think just setting trusted users and sandboxing in nix.conf should do. Not sure how to test locally.

**Comment by zimbatm** [comment]
Apparently travis-builder generates a script that needs to be tested in a VM.

The Nix installer should also be improved. For example it supports a `--daemon` flag but it then not supported on Ubuntu.

I think that it would be possible to improve the integration tremendously. For example we could add a config option:
```yaml
nix_conf:
  sandbox: true
  substituters: https://cache.nixos.org https://myproject.cachix.org
  trusted-public-keys: ...
```
