### ISSUE TITLE
build for golang 1.x doesn't use go get -t to pull test dependencies

### ISSUE THREAD

**Issue by warthog618** [travis-ci/travis-ci#9725]
According to https://docs.travis-ci.com/user/languages/go/#Dependency-Management, versions of golang later than 1.2 should have their dependencies pulled using **go get -t ./...**, but after a recent change, either to travis or golang, that no longer seems to be the case for 1.x, which should map to the latest golang release - currently 1.10.3.
While travis gets the golang version correct, it uses the **go get ./...** expected for golang <= 1.2.

The current 1.x build fails due to a missing dependency (uses **go get ./...** and golang 1.10.3):
https://travis-ci.org/warthog618/config/jobs/389736252

The previous passing 1.x build (uses **go get -t ./...** and golang 1.10.1):
https://travis-ci.org/warthog618/config/jobs/387085720

There was no change to the .travis.yml between the two builds.

My other builds, for 1.10 and master, both use **go get -t ./...** and pass:
https://travis-ci.org/warthog618/config/jobs/389736254
https://travis-ci.org/warthog618/config/jobs/389736256

**Comment by hiro4bbh** [comment]
I have encountered the same issue.
Recent golang's version (1.10.xx?) seems to cause this issue.
I doubt that golang's version detection did fail (see https://github.com/travis-ci/travis-ci/issues/2826 and the related commits).

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Looks related to this commit: https://github.com/travis-ci/travis-build/commit/7101df69eded7b44d129817d572e3b6d6ff551d6. We're no longer resolving the aliases inside `travis-build`, which means it is trying to compare the raw `1.x` version instead of the resolved `1.10.3`.

**Comment by hiro4bbh** [comment]
Thank you for fixing this problem!
I have confirmed that I can test successfully with my projects as before.

**Comment by warthog618** [comment]
Works for me as well.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Awesome, thanks for confirming. I'll go ahead and close this then! ✨
