### ISSUE TITLE
R package using rgdal keeps getting "errored" since recently

### ISSUE THREAD

**Issue by bnasr** [travis-ci/travis-ci#9727]
My R package that was built successfully on Travis until April suddenly keeps crashing for rgdal.

The old .travis.yml does not do the job and I have tried all the tricks I found online (distro, compiling from the source, binaries. dev, new version of gdal, etc.)

https://github.com/bnasr/xROI/blob/master/.travis.yml
https://travis-ci.org/bnasr/xROI

@jeroen and @jimhester, I would appreciate any help on this.

**Comment by jeroen** [comment]
This will be solved once https://github.com/travis-ci/travis-build/pull/1391 is merged.

**Comment by jeroen** [comment]
@joepvd Can you merge PR https://github.com/travis-ci/travis-build/pull/1391?

**Comment by bnasr** [comment]
This merge resolved my issue. So I am closing this thread.
