### ISSUE TITLE
add support for f90cache

### ISSUE THREAD

**Issue by junghans** [travis-ci/travis-ci#9728]
Could you please add support for [f90cache](https://perso.univ-rennes1.fr/edouard.canot/f90cache/) in same way as you support [ccache](https://docs.travis-ci.com/user/caching/#ccache-cache).

**Comment by junghans** [comment]
Still relevant!

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
