### ISSUE TITLE
Not all branches displayed in 'Trigger a custom build'

### ISSUE THREAD

**Issue by kira0204** [travis-ci/travis-ci#9731]
Hi,
I am not sure whether I am missing something or not. But, I have some branches on my repo https://github.com/kira0204/thug and want to trigger a custom build on the branch `tox-travis`, but I can't see this branch in the feature, infact I can't see any branch except the `master` branch

![travis-error](https://user-images.githubusercontent.com/19341613/41190956-5341e5d4-6c05-11e8-8069-5215848eb588.png)

Update: The feature now displays the `tox-travis` branch after I pushed a commit into it. I think this is confusing from a user point of view and would be glad if this is included in the docs or better if all the branches can be displayed

**Comment by NoahRoseLedesma** [comment]
I have been dealing with the same issue. While committing to a non-master branch triggers a build, this branch still does not appear in the drop-down menu.
