### ISSUE TITLE
Can't wget file via ftp due to 'error in server response'

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#9732]
When using Travis CI, I've got the problem downloading file via FTP. The error which I keep getting is:

> Error in server response, closing control connection.

Here is the command:

    wget ftp://ftp.twaren.net/pub/cpatch/msupdate/win2000/en/w2ksp4_en.exe

Content of [`.travis.yml` file](https://github.com/kenorb/travis-test/blob/docker-wget/.travis.yml):

```
sudo: true
services:
  - docker
script:
- wget ftp://ftp.twaren.net/pub/cpatch/msupdate/win2000/en/w2ksp4_en.exe
```

In [build 390216041](https://travis-ci.org/kenorb/travis-test/builds/390216041) there were 18 errors on one download request, before the file could be downloaded. I couldn't reproduce this problem anywhere else apart of Travis CI. On my local laptop, I never get this error, despite I'm behind NAT.

This file is required when installing `winhttp` via `winetricks`. Here is the [build 389046675](https://travis-ci.org/EA31337/FX-MT-VM/jobs/389046675) which also fails due to this error when running `winetricks winhttp`.

Is it possible due to FTP passive mode, where connection is kept closed for some reason (like firewall or restricted networking access)?

Any idea/suggestion how to fix or workaround this issue?

**Comment by BanzaiMan** [comment]
Hello, there. Thanks for the report.

We have made network configuration changes which makes plain FTP connections unreliable. We published the detailed explanation here: https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci

If possible, please use a different protocol to fetch the files you need.

Thank you!
