### ISSUE TITLE
No builds for this repository

### ISSUE THREAD

**Issue by capsulecorplab** [travis-ci/travis-ci#9733]
`.travis.yml` is setup in repo, but I'm still seeing "No builds for this repository" when visiting https://travis-ci.org/spacedecentral/SysML.py

**Comment by capsulecorplab** [comment]
Fixed it. Ended up being a parsing error with `.travis.yml`

**Comment by lauragift21** [comment]
Hi what parsing error would that be? I'm currently facing the same issue
