### ISSUE TITLE
How to restart in debug mode on travis-ci.org

### ISSUE THREAD

**Issue by aaronjameslang** [travis-ci/travis-ci#9736]
Not sure if this is a bug, feature request or just a hole in the docs, but how can a job be debugged on travis-ci.org?

@BanzaiMan suggests here https://github.com/travis-ci/travis-ci/issues/8377 that it requires a "feature flip" and API call.

[Users docs](https://docs.travis-ci.com/user/running-build-in-debug-mode/#Restarting-a-job-in-debug-mode-via-API) help some but don't mention the "feature flip" and the request fails without it.

[API docs](https://developer.travis-ci.com/resource/job#debug) claim that the call should work for "those repositories on the travis-ci.org domain for which the debug feature is enabled"

Is there something somewhere I've missed?

**Comment by DrTorte** [comment]
You would need to send in an email to us at support@travis-ci.com for us to enable it. I'll see if we can't make that clearer in the docs. Thanks for letting us know!

**Comment by aaronjameslang** [comment]
Thanks :) Are the docs in source control somewhere? Should I open a PR?

**Comment by DrTorte** [comment]
Just added the instructions to the user docs. If ever you have something you'd like to improve on them, you are more than welcome to just hit the "Improve this page  on GitHub" link in the upper right, or check out the [docs repo](https://github.com/travis-ci/docs-travis-ci-com/). :)

**Comment by aaronjameslang** [comment]
Great, thanks!
