### ISSUE TITLE
$TRAVIS_GO_VERSION does not expand to numeric version string

### ISSUE THREAD

**Issue by hiranya911** [travis-ci/travis-ci#9739]
Partial output of `env` command in Travis CI:

```
$ env
TRAVIS_GO_VERSION=1.6.x
...
```

Notice the `x` at the end of the string. This is contrary to what's [documented](https://docs.travis-ci.com/user/languages/go/#Environment-Variable):

> Please note that this will expand to the real Go version, for example 1.7.4, also when go: 1.7.x was specified.

We have build scripts that rely on this behavior, and this regression (first detected on 06/11/2018) started breaking our builds.

**Comment by BanzaiMan** [comment]
Looking at the code, the documentation seems wrong to me. I don't think it ever worked in the way described in the docs. I'll update the docs shortly.
