### ISSUE TITLE
Julia HDF5 package does not build

### ISSUE THREAD

**Issue by vtjeng** [travis-ci/travis-ci#9740]
I'm unable to build the `HDF5` package; specifically, the `libgfortran3` ubuntu package is not found.

This [answer on askubuntu](https://askubuntu.com/questions/519539/failed-to-fetch-http-security-ubuntu-com-ubuntu-pool-main-e-eglibc-libc-bin-2) for a related question suggests that this is because the version for `14.04.3` is no longer in [the repo](http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/). (The [download page on `packages.ubuntu.com`](https://packages.ubuntu.com/trusty/amd64/libgfortran3/download) also only points to a `14.04.4` version.)

This looks like it should be fixable by `apt-get update`, but I'm not sure how to do that.

@tkelman @ninjin @staticfloat @simonbyrne

Full logs of my failed build on TravisCI:

```INFO: Building HDF5
Installing dependency hdf5-tools via `sudo apt-get install hdf5-tools`:
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libgfortran3 libhdf5-7
The following NEW packages will be installed:
  hdf5-tools libgfortran3 libhdf5-7
0 upgraded, 3 newly installed, 0 to remove and 8 not upgraded.
Need to get 1,796 kB of archives.
After this operation, 7,075 kB of additional disk space will be used.
Err:1 http://security.ubuntu.com/ubuntu trusty-security/main amd64 libgfortran3 amd64 4.8.4-2ubuntu1~14.04.3
  404  Not Found [IP: 35.184.213.5 80]
Get:2 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty/universe amd64 libhdf5-7 amd64 1.8.11-5ubuntu7 [1,205 kB]
Get:3 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty/universe amd64 hdf5-tools amd64 1.8.11-5ubuntu7 [342 kB]
Err:1 http://security.ubuntu.com/ubuntu trusty-security/main amd64 libgfortran3 amd64 4.8.4-2ubuntu1~14.04.3
  404  Not Found [IP: 35.184.213.5 80]
Fetched 1,547 kB in 0s (8,944 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libgfortran3_4.8.4-2ubuntu1~14.04.3_amd64.deb  404  Not Found [IP: 35.184.213.5 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
================================[ ERROR: HDF5 ]=================================
LoadError: failed process: Process(`sudo apt-get install hdf5-tools`, ProcessExited(100)) [100]
while loading /home/travis/.julia/v0.6/HDF5/deps/build.jl, in expression starting on line 41
```

**Comment by staticfloat** [comment]
Confirmed that it's trying to download the wrong package.  When running within a `trusty` docker image, after doing an `apt-get update`, the version of the package it should be downloading is `4.8.4-2ubuntu1~14.04.4`, not `4.8.4-2ubuntu1~14.04.3`.

Looking at the [Travis documentation on installing dependencies](https://docs.travis-ci.com/user/installing-dependencies/), you can see a code snippet that suggests the following syntax for using the `apt` addon and updating dependencies first:

```yml
addons:
  apt:
    update: true
```

So I suggest you try adding that to your `.travis.yml` to see if it works any better.

**Comment by vtjeng** [comment]
The fix suggested by @staticfloat resolved the issue for me.
