### ISSUE TITLE
[OSX/Python] Unable to download 3.6 archive. The archive may not exist. Please consider a different version.

### ISSUE THREAD

**Issue by funilrys** [travis-ci/travis-ci#9744]
Hi!

Please find here what I get when trying to test under osx.

Build: https://travis-ci.com/funilrys/PyFunceble/builds/76157183

```
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
hostname: 38fc0bfe-3633-4737-b545-e5644326b82e@13535.wjb-2
version: v3.5.0 https://github.com/travis-ci/worker/tree/77dbc57c72d00592aeb754773b712da843c7e00d
instance: 260b3cab-92a7-4b24-9f9f-e0ae59c5031d travis-ci-macos10.12-xcode8.3-1507738863 (via amqp)
startup: 1m5.132430644s
travis_fold:end:worker_info
[0Ktravis_fold:start:system_info
[0K[33;1mBuild system information[0m

Build language: python

Build id: 76157183

Job id: 129097442

Runtime kernel version: 16.7.0

travis-build version: bf4239291

travis_fold:end:system_info
[0K

[32;1mNetwork availability confirmed.[0m



Fix WWDRCA Certificate

Unable to delete certificate matching "0950B6CD3D2F37EA246A1AAA20DFAADBD6FE1F75"security: AppleWWDRCA.cer: already in /Library/Keychains/System.keychain

$ rvm use

[32mUsing /Users/travis/.rvm/gems/ruby-2.4.2[0m

/Users/travis/.travis/job_stages: line 561: yarn: command not found

[33;1m3.6 is not installed; attempting download[0m

[33;1mDownloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.12/x86_64/python-3.6.tar.bz2[0m

$ curl -sSf -o python-3.6.tar.bz2 ${archive_url}

curl: (22) The requested URL returned error: 403 Forbidden

Unable to download 3.6 archive. The archive may not exist. Please consider a different version.

/Users/travis/.travis/job_stages: line 565: shell_session_update: command not found
```

**Comment by bfontaine** [comment]
FWIW, I get exactly the same error on a different project with Python [3.4][], [3.5][], [3.6][].

[3.4]: https://travis-ci.org/bfontaine/term2048/jobs/393266144
[3.5]: https://travis-ci.org/bfontaine/term2048/jobs/393266145
[3.6]: https://travis-ci.org/bfontaine/term2048/jobs/393266146

**Comment by IwoHerka** [comment]
I have the same issue with 3.4.
```
3.4 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.4.tar.bz2
$ curl -sSf -o python-3.4.tar.bz2 ${archive_url}
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
Unable to download 3.4 archive. The archive may not exist. Please consider a different version.
```
https://travis-ci.org/IwoHerka/sexpr/jobs/393316477

**Comment by funilrys** [comment]
Your error is a bit different @IwoHerka :thinking:

**Comment by peterjc** [comment]
Same issue as @IwoHerka just now, https://travis-ci.org/biopython/biopython/jobs/415733334
 
```
Network availability confirmed.
3.4 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.4.tar.bz2
$ curl -sSf -o python-3.4.tar.bz2 ${archive_url}
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
Unable to download 3.4 archive. The archive may not exist. Please consider a different version.
```

This configuration was working until yesterday. I could download this URL locally so it might be a network glitch, about to retry the build...

**Comment by julianoes** [comment]
I'm getting the same problem here:
https://travis-ci.org/julianoes/DronecodeSDK-Python/jobs/420977420.

**Comment by BanzaiMan** [comment]
Hello, there.

At the moment, we do not support `python` on the Mac. https://github.com/travis-ci/travis-ci/issues/2312

**Comment by bittner** [comment]
I've managed to work around the original problem on a macOS build by using `language: generic` and the pre-installed Python 3.6, and it seems to be working in general.

Also, installing a newer Python with the pre-installed pyenv worked in an earlier build.

However, I'm getting an application error from PyInstaller (which builds a monolithic application bundle for macOS). Is this related to the build system?
```python
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/depend/dylib.py", line 308, in mac_set_relative_dylib_deps
    dll = MachO(libname)
  File "/usr/local/lib/python3.6/site-packages/macholib/MachO.py", line 95, in __init__
    self.load(fp)
  File "/usr/local/lib/python3.6/site-packages/macholib/MachO.py", line 110, in load
    self.load_header(fh, 0, size)
  File "/usr/local/lib/python3.6/site-packages/macholib/MachO.py", line 147, in load_header
    header, fh))
ValueError: Unknown Mach-O header: 0x00000100 in <_io.BufferedReader name='/Users/travis/Library/Application Support/pyinstaller/bincache00_py36_64bit/pythonturtle/resources/icon.ico'>
```
(See [the Travis build](https://travis-ci.org/cool-RR/PythonTurtle/builds/436957758) and https://github.com/cool-RR/PythonTurtle/pull/123 for more details)

A similar, rather old [issue on the PyInstaller issue tracker](https://github.com/pyinstaller/pyinstaller/issues/582) suggests upgrading [macholib](https://pypi.org/project/macholib/) (but that was in 2012).

Can I fix this somehow, or is Python on macOS builds still broken?

**Comment by funilrys** [comment]
Hi there, when using miniconda like the way Steven did with his repository, it become possible to use python 3 under MacOS ...

CI Config: https://github.com/StevenBlack/hosts/blob/master/.travis.yml

Installation: https://github.com/StevenBlack/hosts/blob/master/ci/install_conda.sh
Setup: https://github.com/StevenBlack/hosts/blob/master/ci/setup_conda_env.sh

**Comment by aliechoes** [comment]
Is this problem solved? I am getting the same error

**Comment by ericgroom** [comment]
@aliechoes Same, this is quite the surprise

**Comment by nidhaloff** [comment]
I'm having the same problem using python 3.3. The test passes on python3.8, 3.7, 3.6, 3.5 and 3.4 but fails on 3.3 and under
here is my log error:

Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-3.3.tar.bz2
0.09s$ curl -sSf --retry 5 -o python-3.3.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404 Not Found
Unable to download 3.3 archive. The archive may not exist. Please consider a different version.
