### ISSUE TITLE
Deprecation Notice.

### ISSUE THREAD

**Issue by Auvipev** [travis-ci/travis-ci#9745]
I noticed that travis uses github services and i see this in the changes.
Should i be concerned? 

- https://developer.github.com/changes/2018-04-25-github-services-deprecation/

**Comment by Auvipev** [comment]
I would suggest using webhooks like StyleCi.

**Comment by Joeyn414** [comment]
This can probably be closed, Travis CI has released a github app and includes instructions on how to perform the migration. https://docs.travis-ci.com/user/legacy-services-to-github-apps-migration-guide/

**Comment by jrochkind** [comment]
@Joeyn414 those instructions are only for the paid travis-ci.com, not free travis-ci.org I think? But I'm super confused about all of this. Clearer instructions from travis are definitely needed.

**Comment by jrochkind** [comment]
Aha, it looks like the answer is... not yet?

> Open source projects and their build history will continue to run on travis-ci.org for now.

> However, open source repositories will be migrated to travis-ci.com gradually, beginning at the end of Q2 2018. You will receive an email when the migration for a repository is complete. This is an opt-in process: to have a repository migrated over, it must first be activated on travis-ci.com.

> Currently, open source repositories that were private in any time in their history may be added to travis-ci.com. The option to migrate to travis-ci.com for active open source repositories that were always open source will come soon.

**"The option to migrate to travis-ci.com for active open source repositories that were always open source will come soon."**

https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

Hopefully "soon" is before github turns off the access for the old way!

**Comment by Joeyn414** [comment]
Ahh yes, open source repos is a clarification I should have asked for. But I agree, hopefully soon. I use the paid for version and it was painless to integrate with the app.

**Comment by jrochkind** [comment]
I still don't understand what to do with my open source projects still on travis-ci.org. The linked documentation only specifies instructions for private repos.

**Comment by BanzaiMan** [comment]
We will be migrating all data from .org to .com.

**Comment by ofek** [comment]
@BanzaiMan Great, when?

**Comment by lannonbr** [comment]
Any updates on this? There are 60 days till Jan 31 which GitHub services will stop working completely.

**Comment by jrochkind** [comment]
@BanzaiMan what @lannonbr said. If the migration just magically happens without our intervention, that's fine and it doesn't really matter if it happens at the last minute. But if we are going to be required to _do_ something, possibly something that requires some manual intervention and troubleshooting -- giving us a deadline of a week or two to do it is going to be very disruptive. We all have our own local schedules and priorities, so if there's a change travis requires that will require us to do something, we really appreciate you giving us a month or ideally two of notice, so we can fit it in amongst our own existing work before the deadline. 

If all data is going to be migrated from .org to .com, I would have expected several months at which we could choose to press the button "migrate now" whenever we wanted. Which, I guess, is what paying customers got, but not non-paying customers?

**Comment by DrTorte** [comment]
Hey all,

Going to ping internally to see what plans we have exactly at this point. If I recall, the plan is for everyone to have the option to migrate with a simple button press, though I'll need to get back to you on the details.

If you need a move right away, we can do so manually via email through [support@travis-ci.com](mailto:support@travis-ci.com).

**Comment by S-Coyle** [comment]
Any update on this @DrTorte, or anyone else? GH Services deadline is now only 3 weeks away...

**Comment by BanzaiMan** [comment]
Hello, there. We have posted an update on this issue: https://changelog.travis-ci.com/migrating-from-github-services-to-webhooks-86328

**Comment by pradyunsg** [comment]
The deadline is in a few hours now -- it's 31st Jan in most time zones.

**Comment by DrTorte** [comment]
Hello,

We’ll be sharing a blog post with more details, but during this deprecation, Travis CI will continue building and testing your repositories normally. Almost all repositories have been moved successfully to webhooks, but a few need more manual work.

**Comment by pradyunsg** [comment]
Glad to hear that! :)

Will be waiting for the blog post.

**Comment by alallier** [comment]
@DrTorte can you please post the blog post here so we know when it is complete and where we can find it?

**Comment by DrTorte** [comment]
@alallier absolutely!

**Comment by jrochkind** [comment]
It's a bit weird to say "during this deprecation". We aren't _during_ the deprecation anymore... the deprecation is over, github says they have _stopped sending events_. 

But if travis found some magical way to keep things working even though they haven't finished migrating (whatever the magic behind "we have ensured that GitHub services will continue running" -- perhaps they got a special deal from github to not actually turn off the func on the date announced, at least for travis?), I guess that's all that matters, that our repos keep working. 

Definitely down the wire, definitely doesn't inspire confidence in travis's maintenance and upkeep policies, but the important thing is that you found some way not to break our travis builds, so, thanks!

**Comment by DrTorte** [comment]
Hey everyone: as an update, all migrations were completed on February 1st. With this resolved, I'm going to be closing this issue.

@jrochkind Thank you for the feedback, too!

**Comment by pradyunsg** [comment]
Thanks for resolving this in time! :)
