### ISSUE TITLE
no longer receiving email notifications to explicit recipients

### ISSUE THREAD

**Issue by derekbruening** [travis-ci/travis-ci#9746]
For my Github project https://github.com/DynamoRIO/dynamorio, Travis successfully sent email notifications to our mailing list dynamorio-devs at googlegroups.com for years.  Then sometime after March 20, 2018 they stopped arriving.

I did some experiments (see https://github.com/DynamoRIO/dynamorio/issues/3031 which lists the precise [.travis.yml](https://github.com/DynamoRIO/dynamorio/blob/master/.travis.yml) settings I used) and when I set it to the default target address (by not listing `recipients`) it does send email to the author/committer.  But when I put that same author address in `recipients`, no email is received.  There is nothing in the spam filter for that address.

- I'm hoping you can check the Travis logs to see whether there's anything unusual?

- Do you know of anything that happened in late March that might have affected this?  The mailing list is set to allow anyone to post and there are no pending messages.  Given that the current setting of just my email address rather than the list doesn't work, I don't think this is related to the list.

- Is there any reason a target address as a default author would be treated differently from the same address listed as an explicit `recipients`?

**Comment by derekbruening** [comment]
Ping to avoid auto-close

**Comment by DrTorte** [comment]
Hello,

I'll take a look at this internally, and see if there's anything.

In the meanwhile, we're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
