### ISSUE TITLE
Node.js - tests are being run twice in a single build

### ISSUE THREAD

**Issue by Torniojaws** [travis-ci/travis-ci#9748]
It appears that Travis runs ``npm test`` automatically? Is there some way to disable that, as I also have the tests run in the .travis.yml?

package.json:
```
{
  ...,
  "scripts": {
    "test": "eslint . && ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -R spec --timeout 10000 --exit"
  },
  ...
}
```

.travis.yml:
```
language: node_js
node_js:
  - "6"
services:
  - mongodb
cache:
  directories:
    - "node_modules"
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

```

As far as I know, the ``after_script`` needs to be there in order for the coverage to be processed for Coveralls. And in local testing, I use ``npm test``, which is the usual method.

So basically: Is there some way to stop Travis from running ``npm test`` automatically during the build?

Thanks!

**Comment by joepvd** [comment]
The default command that is run for Node builds, is `npm test`, see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/ for details.

You could either override the default action, for example by setting `script: skip` in the `.travis.yml`, or remove the `after_script` section, as that seems redundant.
