### ISSUE TITLE
older versions of R no longer available?

### ISSUE THREAD

**Issue by achubaty** [travis-ci/travis-ci#9751]
@craigcitro and @jimhester

Builds using R 3.1.0 and 3.2.0 are failing with:

```r
$ curl -fLo /tmp/R-3.1.0-$(lsb_release -cs).xz https://s3.amazonaws.com/rstudio-travis/R-3.1.0-$(lsb_release -cs).xz
curl: (22) The requested URL returned error: 403 Forbidden
The command "eval curl -fLo /tmp/R-3.1.0-$(lsb_release -cs).xz https://s3.amazonaws.com/rstudio-travis/R-3.1.0-$(lsb_release -cs).xz " failed. Retrying, 2 of 3.
curl: (22) The requested URL returned error: 403 Forbidden
The command "eval curl -fLo /tmp/R-3.1.0-$(lsb_release -cs).xz https://s3.amazonaws.com/rstudio-travis/R-3.1.0-$(lsb_release -cs).xz " failed. Retrying, 3 of 3.
curl: (22) The requested URL returned error: 403 Forbidden
The command "eval curl -fLo /tmp/R-3.1.0-$(lsb_release -cs).xz https://s3.amazonaws.com/rstudio-travis/R-3.1.0-$(lsb_release -cs).xz " failed 3 times.
The command "curl -fLo /tmp/R-3.1.0-$(lsb_release -cs).xz https://s3.amazonaws.com/rstudio-travis/R-3.1.0-$(lsb_release -cs).xz" failed and exited with 22 during .
```

https://docs.travis-ci.com/user/languages/r/#R-Versions shows that R versions 3.0.3 and higher are supported, or has this changed?

**Comment by jimhester** [comment]
Those particular versions was just never built, I would suggest using the last patch version for each minor version, e.g. 3.1.3 and 3.2.5 rather than the .0 versions.

You can also specify them as 3.1 and 3.2 and the last patch version will be used.

Nevertheless I have now built the .0 versions as well, so they will also work in future builds.

**Comment by achubaty** [comment]
With the recent CRAN requirement that X.Y.0 versions be specified in
DESCRIPTION, it’s worth having them available. Thank you for building them.
-- 
--
Alex M. Chubaty, PhD

cell: +1.403.708.5790
website: https://alexchubaty.com

**Comment by jimhester** [comment]
That is actually _not_ what the recommended solution is. If you specify `Depends (R >= 3.2.3)` you get a note like

> Dependence on R version 3.2 not with patchlevel 0

However the solution is not to change the dependency to `3.2.0` but rather `3.2`. See https://github.com/wch/r-source/blob/9132c825816f3e75a7c45026ead7a8198da0fb2b/src/library/tools/R/check.R#L982-L985 for a comment

**Comment by achubaty** [comment]
Thanks for the clarification on the requirement. I'll update my packages in the next round of CRAN submissions.
