### ISSUE TITLE
Some open source projects are marked private:true in API

### ISSUE THREAD

**Issue by isuruf** [travis-ci/travis-ci#9755]
For example: isuruf/staged-recipes.

I used to be able to access this repo using `api.travis-ci.org`, but now it says access denied and works when using `api.travis-ci.com`.

**Comment by dougalsutherland** [comment]
They're planning on migrating everything to `.com`; I think maybe new projects go to `.com` now but old ones are still on `.org`? This might be related to https://github.com/conda-forge/staged-recipes/issues/5846#issuecomment-397904042...

https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
