### ISSUE TITLE
Documentation wrong about Xcode 9.4 JDK version

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#9756]
At https://docs.travis-ci.com/user/reference/osx/, the JDK version listed for Xcode 9.4 is 1.8.0_112-b16. `java -version` reveals that the JDK it uses is actually 10.0.1 (see for example https://travis-ci.org/Pr0methean/BetterRandom/jobs/393001028 log line 57).

**Comment by BanzaiMan** [comment]
This is fixed at this time.
