### ISSUE TITLE
osx_image: xcode9.4 doesn't have bundler

### ISSUE THREAD

**Issue by torufuruya** [travis-ci/travis-ci#9759]
I tried to use `osx_image: xcode9.4` but I failed to `bundle install`.
If I just revert to use `osx_image: xcode9.3`, the build passed.
`bundler` should be installed globally also in the xcode9.4 image, shouldn't it?
https://docs.travis-ci.com/user/reference/osx/#Gems-in-the-global-gem-set

I got a log on Travis as following:
```sh
$ sudo bundle install
/Users/travis/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
	from /Users/travis/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/travis/.rvm/gems/ruby-2.4.3/bin/bundle:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'

The command "sudo bundle install" failed and exited with 1 during .
```

**Comment by BanzaiMan** [comment]
Hello, there. Sorry for the delay.

I see that you are using `sudo` to run `bundle`. The `root` user on the Mac uses the system-default Ruby, which does not have Bundler installed. Does your build rely on being run as `root`?

**Comment by torufuruya** [comment]
@BanzaiMan Removed `sudo` and it worked! Thanks!

**Comment by BanzaiMan** [comment]
Awesome. I'm closing this, in this case.
