### ISSUE TITLE
[ci skip] has no effect when title contains other directives eg. [circleci]

### ISSUE THREAD

**Issue by mloskot** [travis-ci/travis-ci#9762]
I've made a commit to Boost.GIL project tagged with `[ci skip]` in the title line of the commit message:

```
[circleci] Remove gcc 4.7 build jobs [ci skip]
```

Travis CI did not skip it and performed the complete build: https://travis-ci.org/boostorg/gil/builds/393832101, screenshot below:

![travis-not-skipping](https://user-images.githubusercontent.com/80741/41582254-68cd4d5a-73a1-11e8-9b02-288505388240.png)

It seems there may be **an issue with directive parsing** which does not handle multiple directives and the parser failed at the presence of `[circleci]`.

BTW, AppVeyor did skip the build.

**Comment by mloskot** [comment]
I've tested `[ci skip]` in a different GitHub repository.

Here is commit https://github.com/nanodbc/nanodbc/commit/7d277f35d6995bea0a1e7d012b04b31132fa87bb with the following title:

```
[vagrant] Add support for Hyper-V [ci skip] 
```

and this time Travis Ci skipped the build - https://travis-ci.org/nanodbc/nanodbc

Possibly, the extra directive/tag `[vagrant]` is actually ignored - parsed differently than `[circleci]` which contains the `ci` token.

**Comment by mloskot** [comment]
Hmm, labelled as a bug but closed, without any conclusion.
How to understand the state of this issue?

**Comment by BanzaiMan** [comment]
The fix is deployed to production. It's a private repo, so we can't disclose how we fixed it. Thanks for bringing this to our attention.

**Comment by mloskot** [comment]
Sure, I understand. I'm glad it's been fixed. Thanks!
