### ISSUE TITLE
Don't upload source code zip in travis deploy releases

### ISSUE THREAD

**Issue by ad1992** [travis-ci/travis-ci#9764]
Is there any way to upload only a specific folder zip in Travis deploy releases? Currently, it also uploads the source code zip along with whichever files mentioned in the file attribute of Travis deploy release?

**Comment by joepvd** [comment]
You might be looking for the `file_glob` option. See https://docs.travis-ci.com/user/deployment/releases/#Uploading-Multiple-Files for details.

**Comment by reach2jeyan** [comment]
@ad1992 were you able to do something about this? I am facing this issue now. I also tried removing the `file_glob` but still in vain.

Any progress on it?

**Comment by ad1992** [comment]
@reach2jeyan i ended up using github api to upload folder.
