### ISSUE TITLE
Apache CouchDB uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by ncaq** [travis-ci/travis-ci#9765]
# example

[Job #30.1 - ncaq/yesod - Travis CI](https://travis-ci.org/ncaq/yesod/jobs/394039093#L427)

# reason

~~~
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
~~~

# expect

Please remove CouthDB from `/etc/apt/sources.list.d/`

# relation

* #9112 
* #8581
* #8554

**Comment by KOLANICH** [comment]
@travis-ci this is critical, should be resolved immediately and the resolving of it should be automated

**Comment by DrTorte** [comment]
Hello,

I'm gonna take a look at this internally. In the meantime, we're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
