### ISSUE TITLE
Cancelling a job may cause the next build stage to run

### ISSUE THREAD

**Issue by DRMacIver** [travis-ci/travis-ci#9766]
With [this build](https://travis-ci.org/HypothesisWorks/hypothesis/builds/394066633?utm_source=github_status&utm_medium=notification) I cancelled the `check-py27` job (which seemed to be taking an inordinately long time) in order to restart it.

I was quite surprised to notice that this then caused the next build stage (Extras) to start running! In this case, no harm done, but if this had been on master and the next stage was deploy that would have been rather undesirable.

My general understanding of the intended semantics of build stages is that a stage should not run until all jobs from the previous stage had completed successfully. Is this not the case?

**Comment by DrTorte** [comment]
Thanks for opening this issue!

I'm checking internally to determine exactly how it's supposed to work, so thanks for your patience.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by shehi** [comment]
Why this issue was closed, when this problem is still prevalent?
