### ISSUE TITLE
Build Finishing as a success even with failures

### ISSUE THREAD

**Issue by manwe651** [travis-ci/travis-ci#9773]
My team has been running into an issue where our builds are running commands in the script section and they're failing, but Travis is ignoring that. When running the commands locally, my team has found that the proper success code is being returned from the command line library that we are using.

This screen shot is from a build on MacOSX:
![travis-successful-with-errors](https://user-images.githubusercontent.com/5975059/41676887-6f379ce0-748c-11e8-9535-524bcca88fda.png)

This screen shot is from a build on Linux (trusty):
![image](https://user-images.githubusercontent.com/5975059/41677157-2754cc80-748d-11e8-9c8b-3601957bfe54.png)

**Comment by manwe651** [comment]
I was wondering if anyone can provide me with any assistance with this ticket? I started an email chain with support, but I have not heard back from anyone since July 2.

**Comment by BanzaiMan** [comment]
Hello, there.

If you are still troubleshooting this issue, please check the exit status code of your last command `sfdx …`. It needs to be nonzero in order to mark the build a failure.

**Comment by BanzaiMan** [comment]
Closing this for now. If you are still seeing this issue, please provide build log URL, or email us at support@travis-ci.com with details.
