### ISSUE TITLE
On a Github Pull Request's page, Travis CI shows a check that seems to not belong to it.

### ISSUE THREAD

**Issue by aronisstav** [travis-ci/travis-ci#9777]
## Background

On Github, I have a fork of an organization's repository in which I am maintaining experimental features. In my fork, I am also keeping an up-to-date copy of the upstream `master` branch.

Upstream: https://github.com/parapluu/Concuerror
Own fork: https://github.com/aronisstav/Concuerror

In my fork, I have configured Travis to test:
- the copy of the `master` branch (redundant)
- the experimental branch `parallel`
- pull requests towards those two branches

## Issue

Today the upstream was updated, so I pushed the changes to my copy and opened a Pull Request from the upstream `master` to the experimental `parallel` branch:

Pull Request: https://github.com/aronisstav/Concuerror/pull/40

I then noticed that the Pull Request's status checks included the fork's `master` branch build.

label: `continuous-integration/travis-ci/push`

By visiting the page it is shown that this is indeed a build of the `master` branch, and as such it is not obviously relevant to the Pull Request.

## Expected behaviour

Only the `continuous-integration/travis-ci/pr` check should be visible on the Pull Request's page.

## More details

I suspect that you may want to leave this as-is, as it can help other users detect that they are building experimental branches twice (e.g. in the case that any pushed branch triggers a build on Travis). In this case however the PR was made with the upstream branch, not the local branch. The SHA's are of course the same, but perhaps you could filter such builds somehow.

**Comment by BanzaiMan** [comment]
Hello, there.

I think this is correct behavior.

Commit status is tied to the commit, not the PR. So if your PR contains a commit that has checks (regardless of how those checks got tied to the commit), they show up.

**Comment by BanzaiMan** [comment]
If you can reproduce it, it would be awesome! Thank you!

**Comment by BanzaiMan** [comment]
https://github.com/aronisstav/Concuerror/pull/49 says: 

> 	aronisstav wants to merge 69 commits into aronisstav:parallel from parapluu:master

So, your PR's base branch is `parapluu:master`, which means that the Push build's branch is indeed named `master`.

Did I miss something?

**Comment by aronisstav** [comment]
> So, your PR's base branch is parapluu:master, which means that the Push build's branch is indeed named master.

Indeed. The issue I am pointing at is that the PR includes checks for a push to `aronisstav/master`, even though the PR was opened from `parapluu/master`.

The fact that there exists an `aronisstav/master` branch that is in-sync with `parapluu/master` should (for me) be irrelevant; no status checks for an in-sync `aronisstav/master` should be included in a PR from `parapluu/master`.

In any case, I understand that for Github there is little difference between commit `abcd` in a parent repository and the same `abcd` commit in any of its forks. So perhaps there is nothing to be done here.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
