### ISSUE TITLE
Capability to rename environment variable

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#9778]
Feature request for renaming a repository-wide environment variable.

**Comment by BanzaiMan** [comment]
Hello, there.

Could you elaborate on what problems you are having and how renaming an environment variable would solve it?

Is it not sufficient to write: `export VAR2=$VAR1; unset VAR1`?

**Comment by Deilan** [comment]
@BanzaiMan It's all about renaming repository-wide env vars, which could be set on a dashboard repository settings page (e. g. https://travis-ci.com/<organisation>/<repository>/settings). Currently it could not be renamed.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
