### ISSUE TITLE
Option to add kube service

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#9779]
Right now we have an option to incorporate a `docker` as a service:
```yaml
services:
  - docker
```

It would be nice to also have an option to incorporate `kubectl`:
```yaml
services:
  - kube
```
or
```yaml
services:
  - kubectl
```

**Comment by Deilan** [comment]
Nope.

**Comment by BanzaiMan** [comment]
What sort of service do you anticipate?

**Comment by Deilan** [comment]
@BanzaiMan [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/)

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
