### ISSUE TITLE
Repository access option - all but selected

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#9780]
Currently there are two options of repo access:
- all
- only selected / only whitelisted

That's how it looks:
![image](https://user-images.githubusercontent.com/4777512/41725238-fc0b8366-7577-11e8-96ee-6d656b4c8083.png)

Requesting an option to choose:
- all but selected / all except blacklisted

**Comment by BanzaiMan** [comment]
Hi, there.

Those options are offered by GitHub. While I agree that “all except” is a useful filter, it is not something we control and change. I suggest sending feedback to support@github.com.

Thank you!
