### ISSUE TITLE
Oraclejdk10 is only accessible to the travis user

### ISSUE THREAD

**Issue by srdo** [travis-ci/travis-ci#9784]
When using oraclejdk10, the jdk is placed in /home/travis/oraclejdk10. The /home/travis directory is only readable by the travis user/group. This breaks builds that need other users to have access to the JDK.

Just for comparison, oraclejdk8 installs to /usr/lib/jvm/java-8-oracle, which is world readable.

**Comment by simonDeHero** [comment]
i think i may have the same problem (or closely related). i get this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project tapir-parent: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1.7.0 at specified path /home/travis/oraclejdk10/../lib/tools.jar -> [Help 1]
```

**Comment by sormuras** [comment]
Welcome back, @BanzaiMan! ;-)

If I extrapolate it correctly, the actual path to where `install-jdk.sh` installs a JDK should not affected its installation success. Granted, the user running the script must have write access to the installation path.

_But..._

Published and therefore fixed JDK installations should _really_ be provided by the Travis runtime image. No to download and install them for every single job. Like having a bunch of JDKs in `/usr/lib/jvm/` and the `jdkswitcher` should be the tool to select one of them:
```
- /usr/lib/jvm/java-8-oracle
...
- /usr/lib/jvm/java-10.0.1-openjdk
- /usr/lib/jvm/java-10.0.1-oracle
- /usr/lib/jvm/java-10.0.2-openjdk
- /usr/lib/jvm/java-10.0.2-oracle
```

`install-jdk.sh` should be used to install the "latest and greatest" OpenJDK, only.

**Comment by sormuras** [comment]
Or, after installing to '/home/travis/oraclejdk10' execute a chmod o+x on it.
