### ISSUE TITLE
Can't access /lib/modules/

### ISSUE THREAD

**Issue by alkhimey** [travis-ci/travis-ci#9787]
I wan't to use travis to build a linux kernel module.

Part of building a module requires to run a makefile that resides in `/lib/modules/4.4.0-101-generic/build`

I use the following command in my makefile:
```
make  -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules V=0
```

The problem is this whole directory seems to be missing from the Travis VM:

```
make: *** /lib/modules/4.4.0-101-generic/build: No such file or directory.  Stop.
```

Here is the link to the complete build: https://travis-ci.org/alkhimey/Ada_Kernel_Module_Framework/builds/395599135

Here is the link to the full log: https://api.travis-ci.org/v3/job/395599136/log.txt

Here is my the git repository: https://github.com/alkhimey/Ada_Kernel_Module_Framework/tree/GH-8-experiment-with-travis-ci

**Comment by alkhimey** [comment]
Hi, If it can't be solved, either because technical reasons or because building LKMs is a niche and you don't want to spend time on it, this is understandable. I would appreciate if you communicate that. 
Tank you :)

**Comment by BanzaiMan** [comment]
> Part of building a module requires to run a makefile that resides in `/lib/modules/4.4.0-101-generic/build` …

I don't think that directory exists on our images. How do you expect this to happen?

**Comment by alkhimey** [comment]
AS I understand it (not a Linux expert), one would install them by running a `apt-get install linux-headers-$(uname -r)` command.

In my `.travis.yaml` script, there is already a call to `vm_scripts/setup_vm.sh` which has this command.

Indeed, this can be seen in the [log](https://travis-ci.org/alkhimey/Ada_Kernel_Module_Framework/jobs/401516593#L556).

Yet at the end of the build script, it says the directory does not exist:

    make  -C /lib/modules/4.4.0-101-generic/build M=/home/travis/build/alkhimey/Ada_Kernel_Module_Framework/examples/template modules V=0
    make: Entering an unknown directory
    make: *** /lib/modules/4.4.0-101-generic/build: No such file or directory.  Stop. 
    make: Leaving an unknown directory

My guess was that things such as `/lib` are not accessible from the VM.

**Comment by BanzaiMan** [comment]
Your build is installing `linux-source linux-source-3.13.0`, but your Kernel is 4.4.0-101-generic (according to `uname -r`). This might explain your problem.

**Comment by alkhimey** [comment]
Yep, thank you for noticing that.
In my script I was installing using the following commands:

    sudo apt-get install -y build-essential

I had to use:

    sudo apt-get install -y linux-headers-$(uname -r)

No idea why, but it solved the issue.

Thank you :)
