### ISSUE TITLE
travis encrypt differences for org and pro

### ISSUE THREAD

**Issue by jmlopez-rod** [travis-ci/travis-ci#9788]
I had previously tested the travis cli with a project managed by `travis-ci.org` and noticed that the environment variable encryption worked fine. Then when I started a brand new project with `travis-ci.com` (since that's where everything is going) I noticed that the env vars did not work well.

I think the current docs do not reflect the fact that you need to use the `--pro` flag if you are trying to encrypt for a project in `travis-ci.com`: https://docs.travis-ci.com/user/encryption-keys/

It took me a while to realize that I needed the flag because each server has a different public key which is used to encrypt the data. Perhaps to someone who has just started a brand new project in travis.com everything will be fine? But if this is not the case they will have a really hard time trying to figure out why
their encrypted variables are invalid.

Apologies if this issue has been brought before.

**Comment by nathanbegbie** [comment]
This. Just spent the morning debugging, only to discover that this was the issue. Perhaps when first running `travis encrypt` it should prompt you, check which one is configured or print which travis the repo is configured to use.
