### ISSUE TITLE
Repository pull requests hang in 'pending' state

### ISSUE THREAD

**Issue by dwasyluk** [travis-ci/travis-ci#9789]
We recently migrated from the legacy travis integration to the GitHub app for Travis CI. We require status checks to pass before pull requests can be merged but for some reason the connection between Travis and GitHub doesn't seem to be fully working.

For example when a PR is created, below is what GitHub shows and Travis shows no build requests whatsoever.

<img width="801" alt="screen shot 2018-06-23 at 1 58 35 am" src="https://user-images.githubusercontent.com/987186/41806286-f7f0ec8c-7688-11e8-9d2f-4ed136a56846.png">

**Comment by Noofbiz** [comment]
I'm having a similar problem here https://github.com/EngoEngine/engo/pull/572

I get the Pending but it never goes to Completed.

Here's what the PR looks like:

<img width="780" alt="screen shot 2018-08-28 at 4 32 55 pm" src="https://user-images.githubusercontent.com/5117030/44749328-2c740f80-aae0-11e8-9630-075f74e5d23c.png">

but when you click the Details link TravisCI says it's completed:

<img width="1089" alt="screen shot 2018-08-28 at 4 33 18 pm" src="https://user-images.githubusercontent.com/5117030/44749356-401f7600-aae0-11e8-9159-573cf99cf52a.png">

I've tried restarting the build on TravisCI, as well as closing and reopening the pull request to trigger another build. Both ended up with the same result.

**Comment by BanzaiMan** [comment]
Closing this for now. If you see this again, please provide build log URL to show the problem, or email us at support@travis-ci.com.

**Comment by marcus-sa** [comment]
This happens for me as well :)

**Comment by gnomeria** [comment]
It's still happening recently as well:
- https://github.com/serverless/serverless/pull/7513#partial-pull-merging
- https://travis-ci.org/github/serverless/serverless/builds/667556123?utm_source=github_status&utm_medium=notification

**Comment by johnjbarton** [comment]
PR is pending, travis is green:

- https://github.com/karma-runner/karma/pull/3467
- https://travis-ci.org/github/karma-runner/karma/builds/673153033

**Comment by tsanislavgatev** [comment]
PR is pending and the travis build is passed:
PR:  https://github.com/SAP/ui5-webcomponents/pull/1460
Travis: https://travis-ci.org/github/SAP/ui5-webcomponents/builds/673366254

**Comment by rhcarvalho** [comment]
Is there a known workaround for this problem?

https://github.com/getsentry/sentry/pull/18759 stuck in "pending", Travis build is green https://travis-ci.org/github/getsentry/sentry/builds/686136031.

I tried re-running one of the jobs to see if it would trigger a re-sync, no luck.

**Comment by usernamedt** [comment]
> Is there a known workaround for this problem?
> 
> [getsentry/sentry#18759](https://github.com/getsentry/sentry/pull/18759) stuck in "pending", Travis build is green https://travis-ci.org/github/getsentry/sentry/builds/686136031.
> 
> I tried re-running one of the jobs to see if it would trigger a re-sync, no luck.

@rhcarvalho how did you guys solve this issue?

**Comment by rhcarvalho** [comment]
> @rhcarvalho how did you guys solve this issue?

@usernamedt we didn't really solve it. For the specific PR, days later I had to re-run the whole Travis job to sync the status with GitHub.
