### ISSUE TITLE
Better C++ support

### ISSUE THREAD

**Issue by o11c** [travis-ci/travis-ci#979]
It would be very nice if there was proper support for C++ compilers and standard libraries.

Ideally, Travis would support the following compilers:
- gcc 4.4, 4.5, 4.6, 4.7
- clang 3.0, 3.1, 3.2

against both of the following libraries (possibly with versions):
- libstdc++
- libc++

Currently, I am supporting multiple gcc versions by using env rules and installing the package in the pre script, and only using the default version of clang, and only testing libc++ on my local machine.

Note that some particular compiler/library crosses are likely to fail, such as gcc against libc++, and clang against certain versions of libstdc++.

Some of the versions might be harder to implement than others, but at a minimum it should be trivial to support gcc versions.

(apologies if this is a duplicate - github's "search" feature is broken with '+').

**Comment by BanzaiMan** [comment]
I'm going to close this now.

Trusty has been deployed, and at least some aspects of C++ build experience have improved.

If there are *specific* points we can improve, please open new issues separately.
