### ISSUE TITLE
Sonarcloud addon failure

### ISSUE THREAD

**Issue by colombod** [travis-ci/travis-ci#9791]
When setting up sonar addon according to documentation the build fails with sonar-scanner not found error and no other relevant details in log

**Comment by klougit** [comment]
Hey again, I sent an email to the travail support, I'll try it later ! 
Hope it'll work

Answer:
I believe what's happening here is that your are using our Python image and `sonar-scanner` isn't pre-installed on it. Sorry for the inconvenience.

You should be able to install it manually by adding a recipe similar to the following in your .travis.yml file:


install:
  - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
  - unzip sonar-scanner-cli-3.2.0.1227-linux.zip
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/sonar-scanner-3.2.0.1227-linux/bin
  - sonar-scanner --help

**Comment by akshita31** [comment]
I tried following the instructions as listed on the docs , but seems that the authentication is failing somehow. Here are the logs: https://travis-ci.org/OmniSharp/omnisharp-vscode/builds/397599106?utm_source=github_status&utm_medium=notification. I tried both the methods, putting a token in the repository settings and putting it in the secure attribute in travis.yml after encrypting. The same token works fine for my local build and is able to push results to the server as well. Any idea how I can debug this ?

**Comment by colombod** [comment]
@klougit any advice?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
