### ISSUE TITLE
Support Perl 5.28

### ISSUE THREAD

**Issue by FGasper** [travis-ci/travis-ci#9792]
Just released yesterday: https://metacpan.org/release/XSAWYERX/perl-5.28.0

**Comment by Grinnz** [comment]
Any update on this? For reference this is from when 5.26 was added: https://github.com/travis-ci/travis-ci/issues/7825

**Comment by GPHemsley** [comment]
@BanzaiMan Did automated builds ever happen?

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/perl-builder/builds/418257620
