### ISSUE TITLE
[Enhancement] Better build matrix rendering

### ISSUE THREAD

**Issue by dw** [travis-ci/travis-ci#9793]
Given the table like shown here: https://travis-ci.org/dw/mitogen/builds/395953214

Most of the horizontal space is heavily wasted. What if instead of static columns, the distinct set of varying env keys and language-specific columns are computed, then render based on that?

| Job   | Python | MODE          | DISTRO  | VER     | Status       |
|-------|--------|---------------|---------|---------|--------------|
| 868.1 | 2.7    | mitogen       | debian  | -       | 5 min 19 sec |
| 868.2 | 2.6    | mitogen       | centos6 | -       | -            |
| 868.3 | 2.7    | debops_common | -       | 2.4.3.0 | -            |

Note missing OS column since its value is always fixed.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
