### ISSUE TITLE
Capability to manage queue of builds

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#9799]
If one has numerous simultaneous builds waiting for it's turn in queue on one hand, and just one or two workers to run the builds on the other hand, it would be nice to have a capability to reorder builds in the queue, so more important builds get run first.

As of now we can only stop and restart builds manually in a required order.

**Comment by Deilan** [comment]
Nope.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
