### ISSUE TITLE
`cache: npm` does not seem to work

### ISSUE THREAD

**Issue by oncletom** [travis-ci/travis-ci#9807]
Hello,

By having a look at https://github.com/travis-ci/travis-build source code, it seems that `cache: npm` is a supported feature.

https://github.com/travis-ci/travis-build/blob/eb546a2b0f2102a0520e113fbfcaac22bc991370/spec/build/script/node_js_spec.rb#L115

However, the following .travis.yml does not generate a cache — the settings/cache tab on the project page shows an empty list of cached items.

```yml
language: node_js
cache: npm
```

Is it the expected behaviour?

**Comment by BanzaiMan** [comment]
Hello, there.

`cache: npm` triggers a completely different feature (https://github.com/travis-ci/travis-build/blob/3af56667b3221448763e79a73007b94a38bb9612/lib/travis/build/script/node_js.rb#L214-L219), and it seems to me that it should be removed entirely.

**Comment by BanzaiMan** [comment]
We have repurposed `cache: npm`. https://changelog.travis-ci.com/for-node-js-builds-cache-npm-shortcut-is-available-77295
