### ISSUE TITLE
Shards on travis

### ISSUE THREAD

**Issue by waghanza** [travis-ci/travis-ci#9809]
Hi,

I can see that **Travis** image has `shards` `0.8.0`, but this version has been revoked.

ping @jhass @matiasgarciaisaia @waj @will

Regards,

**Comment by waghanza** [comment]
It is only truth on `linux` env

`osx` run ok => https://travis-ci.org/tbrand/neph/jobs/397000695#L1401

**Comment by matiasgarciaisaia** [comment]
That's the current state of Crystal on Linux (ie, that's what you get if you install Crystal using the official deb or rpm repos).

There should be a new release fixing that in the next few days.

**Comment by waghanza** [comment]
@matiasgarciaisaia the `docker` image also contains **shards** `0.8.0`
