### ISSUE TITLE
Bug when using [skip ci] in a merge commit

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#9812]
When I use [skip ci] in the description of a merge commit and then push, it creates a new build of the source branch, but displays it as belonging to the destination branch. If the last thing I did before merging was to push the source branch, the new build ends up being a duplicate. I would've expected all the merge commits to be ignored when deciding whether there was anything to run.

I ran into this recently when needing to mark some changes "merged" that weren't going to be, from a branch with a long-running .travis.yml to one with a much shorter one.

**Comment by BanzaiMan** [comment]
Hello, there. Could you point to the relevant build log URLs and commits? Thanks.

**Comment by BanzaiMan** [comment]
Closing due to the lack of information.
