### ISSUE TITLE
Travis Cache directory does not work for a folder

### ISSUE THREAD

**Issue by gpincheiraa** [travis-ci/travis-ci#9814]
I have the following configuration for cache directories on the jobs

![travis-yml-cache](https://user-images.githubusercontent.com/5608336/41983195-5fb4dbce-79fb-11e8-9c0a-06a472634e32.png)

In this case I want storage a `./dist` folder generated for webpack build and use this folder in the next step, but once time that the job finished the folder is not stored as shows the following image:

![build-cache-travis](https://user-images.githubusercontent.com/5608336/41983194-5f7a8bb8-79fb-11e8-9b9c-40c883fe896b.png)

https://travis-ci.org/gpincheiraa/bln-frontend-project1/jobs/397192138

¿Why this folder is not persisted in caché? 

Update:

I created a new repository for checking if this not works but it's working!!! 

creating dist folder and adding it to caché
https://travis-ci.org/gpincheiraa/travis-cache-webpack/jobs/397422919

check if the folder cached it is available
https://travis-ci.org/gpincheiraa/travis-cache-webpack/jobs/397422920

**Comment by grooverdan** [comment]
you can use ```$HOME/.npm``` in a cache directory list.

**Comment by BanzaiMan** [comment]
> ¿Why this folder is not persisted in caché?

How did you come to this conclusion? If nothing in the `dist` directory changed during the build, nothing new will be uploaded. If you think it does not, try looking at the content of the directory before the build starts.

Closing this for now. If you have reasons to still believe that it is not, do let us know.
