### ISSUE TITLE
Hidden environment variables unavailable during builds

### ISSUE THREAD

**Issue by BenCoffeed** [travis-ci/travis-ci#9817]
When I hide my AWS_SECRET_ACCESS_KEY from output in build panel using the Settings UI for the repository, I get the following error when attempting to access s3 resources.
`Partial credentials found in env, missing: AWS_SECRET_ACCESS_KEY`
However, when I leave the variable unencrypted and displayed in build log, builds succeed.

**Comment by nmohoric** [comment]
Same problem here, I'm not sure what is going on. It only happens on a single repo of ours. 
Have you heard anything about this or found a solution?

**Comment by BenCoffeed** [comment]
I haven't heard anything and for now, i just don't hide them.

**Comment by iriberri** [comment]
Hi there!

Are the builds in which you're experiencing this issue pull request builds that come from a fork? 

In these cases, encrypted environment variables are removed for security reasons. See: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

This warning should also appear in the logs of every build where secret env vars are removed as:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/1730320/42557386-af125cf2-84ee-11e8-988d-5fbd0664a1ee.png">


If it's not the case, please let us know further details at support@travis-ci.com and we'd be glad to help!

**Comment by nmohoric** [comment]
Well now I feel bad. I could have sworn I checked to make sure this wasn't from my fork :(
Thanks for looking into it and addressing it, @iriberri .
