### ISSUE TITLE
Cannot activate repository

### ISSUE THREAD

**Issue by znat** [travis-ci/travis-ci#9818]
Oh no!
There was an error while trying to activate the repository.

A public repo in an organization https://github.com/mrbot-ai/rasa-addons

<img width="495" alt="capture d ecran 2018-06-28 a 21 27 16" src="https://user-images.githubusercontent.com/3694634/42068509-5299b6c4-7b1a-11e8-9eba-44f4a2349562.png">

In the console:
```
Failed to load https://api.travis-ci.org/repo/19404387/activate: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://travis-ci.org' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by atlassubbed** [comment]
Also getting this error. My repository is public, as well.

**Comment by ghartoularos** [comment]
Also getting same error for all my repositories.

**Comment by Seluj78** [comment]
Getting the same for https://travis-ci.org/OpenApprenticeFoundation/GyfcatLikeUsernameGenerator

**Comment by atlassubbed** [comment]
This is fixed now.
