### ISSUE TITLE
Random build fail.

### ISSUE THREAD

**Issue by LindaLawton** [travis-ci/travis-ci#9822]
I have gotten this a couple of times now.  It seams to work if i just restart the build.    I am extremely new to Travis only posting it here because it says to.   If you need any more info please let me know.

> C# support for Travis-CI is community maintained.
> Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry
> Installing .NET Core
> $ export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
> $ export DOTNET_CLI_TELEMETRY_OPTOUT=1
> Executing: /tmp/tmp.oLSTbnHsB3/gpg.1.sh --keyserver
> hkp://keyserver.ubuntu.com:80
> --recv-keys
> BE1229CF
> gpg: requesting key BE1229CF from hkp server keyserver.ubuntu.com
> gpgkeys: key BE1229CF can't be retrieved
> gpg: no valid OpenPGP data found.
> gpg: Total number processed: 0
> The command "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BE1229CF" failed and exited with 2 during .

**Comment by akoeplinger** [comment]
Unfortunately there's little we can do about this as it seems to be an issue with the Ubuntu keyserver we're using to fetch the signing keys. It seems to be a bit unreliable the last few days.

**Comment by LindaLawton** [comment]
Ok thanks.   I have been getting quite a few fails today.

**Comment by akoeplinger** [comment]
I've sent a PR which replaces the Ubuntu keyserver with just embedding the key directly so hopefully this is fixed now: https://github.com/travis-ci/travis-build/pull/1428

**Comment by jayvdb** [comment]
Note similar issue https://github.com/travis-ci/travis-ci/issues/9801

And much older https://github.com/travis-ci/travis-ci/issues/8720

Seems the solution is to embed the keys.
We might even put them in our repo, or a submodule, if this persists.

**Comment by jayvdb** [comment]
Im seeing the same problems with two sources provided by https://github.com/travis-ci/apt-source-whitelist : avsm & hvr-ghc

**Comment by akoeplinger** [comment]
@jayvdb please open a new issue as this one is closed and was specifically about C#.
