### ISSUE TITLE
Remote URL downloads failing in R macOS build environment

### ISSUE THREAD

**Issue by mjsteinbaugh** [travis-ci/travis-ci#9824]
I'm running into problems testing my R code using the `osx` build environment with `bioc-release`. For multiple packages I maintain, I've started to see a remote server connection error pop up sporadically and cause my build checks to fail:

When attempting to download a remote file using `utils::download.file()`, the R session fails to connect, returning the error `status was 'Couldn't connect to server'`. I can confirm that the server is online, and the build checks run at the same time on the `linux` container work fine.

Has anybody else come across this issue?
@jimhester @craigcitro

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
