### ISSUE TITLE
Build config file is required via repository settings, but config is empty.

### ISSUE THREAD

**Issue by Mithrilhall** [travis-ci/travis-ci#9825]
I'm trying to setup Travis-Ci for [my project](https://github.com/Mithrilhall/oui-download-to-json/blob/master/travis.yml) and keep getting this as an error: **Build config file is required via repository settings, but config is empty.**

Any suggestions on what I'm doing wrong?

https://travis-ci.org/Mithrilhall/oui-download-to-json/requests?requestId=122133860

**Comment by madeleinedaly** [comment]
Try renaming `travis.yml` to `.travis.yml`.

**Comment by Mithrilhall** [comment]
I'm going to pretend it was the heat getting to me.

Thank you.

**Comment by kauraman14** [comment]
We are facing the same issue on request page.

It will be helpful if you can provide us resolution you have implemented to resolve this problem.Even the failed builds are not displayed under "Build History". 
Request you to help with this.

**Comment by Mithrilhall** [comment]
My `.travis.yml` was incorrectly named `travis.yml`. It was simply the leading dot `.` that was missing; for me at least.

**Comment by kauraman14** [comment]
Thanks for reverting on query. 
However, my yml file is named correctly '.travis.yml'. 

Could you please tell what could be the other reason for build failure. Every time I commit the code on Git, build got failed on Travis and warning 'Build config file is required' is displayed.
![build failure](https://user-images.githubusercontent.com/40200829/42930376-7547696e-8b5a-11e8-9a58-4528767e16dc.jpg)

**Comment by Mithrilhall** [comment]
@kauraman14, I cloned your repo and this is the message I got from Travis: `Could not parse .travis.yml`.

I replaced the contents of your `.travis.yml' with this
```
language: java
sudo: false # faster builds

after_success:
  - bash <(curl -s https://codecov.io/bash)
```
and it worked fine.

**Comment by kauraman14** [comment]
Thanks for looking into it. 
I tried with your provided yml content and it is still failing for me.
![not working](https://user-images.githubusercontent.com/40200829/42958332-ecb7bc22-8ba2-11e8-8c90-30ad287d99a0.jpg)

**Comment by Mithrilhall** [comment]
The only other thing I did was move all files/folders to the root folder rather than having them in a nested folder.

**Comment by kauraman14** [comment]
I have all the files and folders under parent directory itself.

**Comment by Mithrilhall** [comment]
Can you link to the project in github?

**Comment by kauraman14** [comment]
Hey, please find the git project below:
https://github.com/kauraman14/GitTravisCI

Just for info, I am using Java v1.8

**Comment by kauraman14** [comment]
Its still not working..

**Comment by Mithrilhall** [comment]
@kauraman14 https://github.com/Mithrilhall/GitTravisCI/tree/master

**Comment by kauraman14** [comment]
Hey Thanks for helping me out. My issue is resolved now.
I appreciate your quick responses.

Thanks once again..!!

**Comment by kauraman14** [comment]
Hi Mithrilhall,

Can you please update how we can run the test scripts created in eclipse (that are integrated with Git) using Travis?

**Comment by Mithrilhall** [comment]
I do not know Eclipse or Java. I would open another ticket for your new issue if you think it's Travis related.

**Comment by happilymarrieddad** [comment]
I feel so dumb... .yml was the solution for me...

**Comment by mwendah** [comment]
having sme issues with travis too sme files pass but sme have " Build config file is required via repository settings, but config is empty"

**Comment by Tibzie** [comment]
I wish there was a facepalm reaction. thank you
