### ISSUE TITLE
Upgrade rebar3 to 3.6.1 version in Erlang/OTP jobs

### ISSUE THREAD

**Issue by arkgil** [travis-ci/travis-ci#9830]
Hi!

To run Erlang Common Test framework test suites with Erlang/OTP 21.0 release, rebar3 version 3.6.0 is required. Currently Erlang jobs on TravisCI include rebar3 from 3.4.x line - would it be possible to upgrade it to the newest version? Currently the only workaround is to include rebar3 script directly in the repository and use this local copy.

Oh, and by the way, thank you for the awesome service! ❤️

**Comment by getong** [comment]
I have made a pr for it, see travis-ci/travis-cookbooks#990

**Comment by DrTorte** [comment]
Hello,

Going to ping internally on this and see what we can do. In the meantime, we're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
