### ISSUE TITLE
Python 3.7.0 Support

### ISSUE THREAD

**Issue by Richienb** [travis-ci/travis-ci#9831]
At the time of writing, Python 3.7.0 has been released 5 days ago but is not yet supported by Travis CI. Just wondering when support will arrive for this new version.

**Comment by joepvd** [comment]
See https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442

With the following snippet, you can use Python 3.7 in your builds:

```
language: python
python: 3.7
dist: xenial
sudo: true
```

**Comment by Richienb** [comment]
Thanks!

**Comment by nikolas** [comment]
I'm working on a project that needs to be tested on all versions of python, and when I do this, 2.6, 3.3, and 3.4 fail, but it does allow 3.7 to work.

```
sudo: false
language: python
dist: "xenial"
sudo: true
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
 - python setup.py install
 - pip install -r test_reqs.txt
```

Is there a way to tell travis to use `xenial` for python 3.7, but `trusty` on the other versions?

**Comment by nikolas** [comment]
Nevermind - the travis.yml here answers my question: https://github.com/travis-ci/travis-ci/issues/9815

**Comment by mdeff** [comment]
`sudo: true` is not needed anymore. Travis CI is [deprecating that option and moving back to a VM-only infrastructure](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) (no more containers with `sudo: false`).
