### ISSUE TITLE
Wrong node version used for builds (node 6 instead of 8)

### ISSUE THREAD

**Issue by comigo-github** [travis-ci/travis-ci#9833]
I declared the node version to use, to be 8:
```
language: node_js
node_js:
  - '8'
...
```

But according to the build logs, even though it runs "nvm install 8" successfully the "node --version" command returns v6.14.3.
For examlpe - https://travis-ci.com/comigo-github/claro/builds/77795248

**Comment by BanzaiMan** [comment]
Hello, there.

It seems that your npm cache contains `node@6.14.3`:

    │ ├─┬ node@6.14.3

See inside `npm ls`.
