### ISSUE TITLE
Run `after_script` when job is manually cancelled or killed by the worker

### ISSUE THREAD

**Issue by lamont-granquist** [travis-ci/travis-ci#9834]
Reopening #4221 

When jobs timeout due to no output, the `after_script` does not fire.

If the job fired up a virt in e.g. EC2 or digital ocean then when the cleanup scripts in the `after_script` fail to fire, that leads to real $$$ costs being paid to cloud providers.

There needs to be some way to run code in the equivalent of an `ensure` block so that if the travis run fails for any reason that cleanup code is definitely run in order to properly destroy resources.

**Comment by BanzaiMan** [comment]
I've reopened #4221.
