### ISSUE TITLE
Unable to get build started on repository

### ISSUE THREAD

**Issue by yewwoei** [travis-ci/travis-ci#9835]
Hello,

I'm trying to test this public repository https://github.com/yewwoei/orbital through travis. 

I've created the .travis.yml file, but it does not work. I've also tried the following different ways:
1. editing or deleting the .travis.yml file and pushing a new file
2. Completely revoking travis access rights and re-doing it again.

However, there's no progress at all. 

Part of the issue seems to stem from the fact that this repository was named after a previously deleted repository (that did not have travis integration inside).

Please help!

**Comment by BanzaiMan** [comment]
Hello, there. https://travis-ci.com/yewwoei/orbital/requests indicates that your `.travis.yml` is invalid.

Indeed, lines 2 and (3+4) https://github.com/yewwoei/orbital/blob/a108a7c5ff8561f93b8944ac48a8d8a54e555f86/.travis.yml#L2-L4 are at odds. What you probably meant was:

```yaml
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
```

This is discussed in https://docs.travis-ci.com/user/caching#enabling-multiple-caching-features.
