### ISSUE TITLE
Update Python2 version on container builds

### ISSUE THREAD

**Issue by marcaddeo** [travis-ci/travis-ci#9836]
It seems the Python version installed on Travis CI containers (2.7.6) does not support TLS with SNI.

Recently [Ansible Galaxy switched to OpenShift][] which uses SNI, and it has subsequently broken `ansible-galaxy install` commands for me on Travis CI containers.

```
$ ansible-galaxy install -r requirements.yml -p roles
 [WARNING]: - geerlingguy.ansible was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): Failed to validate the SSL
certificate for galaxy.ansible.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9
on your managed machine  (the python executable used (/usr/bin/python) is version: 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]) or you can install the `urllib3`,
`pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the
servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-
certificates/cacert.org, /etc/ansible. The exception msg was: hostname u'galaxy.ansible.com' doesn't match either of '*.c1e4.galaxy.openshiftapps.com',
'c1e4.galaxy.openshiftapps.com'.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

According to this error, we need to use python `>= 2.7.9` to support SNI. Is this something that I can change within a container using my `.travis.yml` file, or does it have to be changed on the container template? I tried a few methods to update python, but nothing seemed to work. Note: this is for a PHP project, so I couldn't use the built-in python version support.

Any suggestions welcome!

Thanks

[Ansible Galaxy switched to OpenShift]: https://github.com/ansible/galaxy/issues/795#issuecomment-401932609

**Comment by BanzaiMan** [comment]
There are a couple of possible workarounds to this problem. Which one is more likely to succeed depends on your setup, so consider options carefully.

1. Use `language: php` and mimic what Python builds would do to install Python archives on the fly:
    ```yaml
    language: php
    sudo: required
    env:
      global:
        - TRAVIS_PYTHON_VERSION=2.7.10
        - UBUNTU_RELEASE=$(lsb_release -rs)
        - PYENV_PATH_FILE='/etc/profile.d/pyenv.sh'
    before_install:
      - curl -sSf -o python.tar.bz2 https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/${UBUNTU_RELEASE}/x86_64/python-${TRAVIS_PYTHON_VERSION}.tar.bz2
      - sudo tar xjf python-tar.bz2 --directory /
      - echo 'export PATH=/opt/python/#{TRAVIS_PYTHON_VERSION}/bin:$PATH' | sudo tee -a #{PYENV_PATH_FILE}
      - source ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
      - python --version
      ```

1. Use the experimental `language: xenial` image.

    ```yaml
    dist: xenial
    sudo: required
    ```

It is also possible to switch to `language: python` and set up your PHP environment, but I think it entails [some tricky manual PEAR configuration](https://github.com/travis-ci/travis-build/blob/1ed393ed450aed5a59095c3f1648484b2b55ddda/lib/travis/build/script/php.rb#L212-L235).

We will be working on getting the Xenial image, or the one last Trusty image that has a newer Python 2.7.x not too far in the future.

**Comment by tonnyavery** [comment]
https://github.com/pypa/pypi-support/issues/978
Pypi is deprecating non-SNI packages support and this seems to affect `trusty` distributions on Travis.
