### ISSUE TITLE
Dotnet 2.1: "Dotnet Test" timing out

### ISSUE THREAD

**Issue by fedoranimus** [travis-ci/travis-ci#9840]
I've been seeing an issue the last couple of weeks after upgrading to .Net Core 2.1 & Webpack 4 where my `dotnet test` command will time out after 10 minutes.

You can see the build logs here: https://travis-ci.org/fedoranimus/Covalence/jobs/387417063

However, if I run the command locally, it executes successfully in a handful of seconds.
![image](https://user-images.githubusercontent.com/179260/42242564-4cd5fd54-7edc-11e8-814a-67e592a68272.png)

I'm not sure what the issue could be here, perhaps @joshua-anderson @akoeplinger or @nterry might have an idea?

**Note**: I have older builds running on v2.0 that _were_ successful originally, but now fail on `dotnet restore`.

Thanks.

**Comment by akoeplinger** [comment]
Hmm, this doesn't sound like something Travis specific. Either it's an issue in your app or something in .NET Core.

Your local test was on Windows, you could try reproducing the issue on Ubuntu 14.04 (Trusty) which is what you're using in your Travis build.

**Comment by fedoranimus** [comment]
Ah, you're right. I can reproduce this on Ubuntu 14.04. I had my .travis.yml file always set to use Trusty, so I'm confused about why this is popping up now.

Now I'm working to figure out what is going wrong.

**Comment by fedoranimus** [comment]
This has been fixed due to some suggestions by the lovely people at xUnit. Thanks!
