### ISSUE TITLE
Builds stopped running

### ISSUE THREAD

**Issue by dom96** [travis-ci/travis-ci#9841]
I'm not sure what the problem is but the builds for my repo have stopped running (they have been running fine for years).

https://travis-ci.org/nim-lang/packages/builds

https://github.com/nim-lang/packages/commits/master

**Comment by shlomif** [comment]
This does not build the latest commit - https://travis-ci.org/shlomif/perl-File-Find-CaseCollide/builds -

**Comment by dom96** [comment]
> Could not parse .travis.yml

Oh. Bah.
