### ISSUE TITLE
Travis CI API to get all users Object

### ISSUE THREAD

**Issue by JayshreeM** [travis-ci/travis-ci#9842]
Hi,
For Travis CI, We want to fetch all users connected to organizational repository, to generate report on the repositories,build.
Any existing API available for the same?

**Comment by JayshreeM** [comment]
Any thoughts on this?

**Comment by BanzaiMan** [comment]
Our users' memberships reflect those on GitHub (up to the last data sync). I suggest using GitHub API for that. See https://developer.github.com/v3/orgs/members/
