### ISSUE TITLE
ImportError with Python tests since July 3

### ISSUE THREAD

**Issue by ouvrierl** [travis-ci/travis-ci#9844]
Hi,

I am using Travis for the continuous integration for our open source project in Python, and I have an error since a few days that I do not understand.

The script of tests begins like this:

    import os

    # Working from the scripts directory
    os.chdir(os.path.dirname(os.path.realpath(__file__)))

    import unittest

    from PyQt5.QtTest import QTest
    from PyQt5.QtWidgets import QApplication
    from Project.Project import Project, COLLECTION_CURRENT, COLLECTION_INITIAL,   COLLECTION_BRICK, TAG_ORIGIN_USER, TAG_FILENAME, TAG_CHECKSUM, TAG_TYPE, TAG_BRICKS, TAG_EXP_TYPE
    from MainWindow.Main_Window import Main_Window
    from SoftwareProperties.Config import Config

    import populse_db

Line 8 ( from PyQt5.QtTest import QTest) is now giving this error in Travis since a few days:
    
    The command "python ./python/populse_mia/src/scripts/test.py" exited with 1.
    $ coverage run ./python/populse_mia/src/scripts/test.py
    Traceback (most recent call last):
      File "./python/populse_mia/src/scripts/test.py", line 8, in <module>
        from PyQt5.QtTest import QTest
    ImportError: No module named 'PyQt5.sip'

The tests are still working great on my local machine, and we did not change the script of tests at all.
Could the problem possibly be on Travis side?

Best regards

**Comment by DrTorte** [comment]
Hey there,

Thanks for posting this and sorry to hear about the issue here. I haven't heard of any ongoing issues like this right now, so my first guess would be something on the configuration. Do you happen to have a build log you could share publicly? If it's for a private repo feel free to send it in to support@travis-ci.com and we'll investigate there. :)

**Comment by ouvrierl** [comment]
Hi,

Thanks for replying and taking care of my issue.

No problem I can share it, the project is open source.
Here is a link of a build log failing: [https://travis-ci.org/populse/populse_sandbox/jobs/400340389](https://github.com/populse/populse_sandbox)
The repository failing is this one: [https://github.com/populse/populse_sandbox](https://github.com/populse/populse_sandbox)

The tests are precisely failing since this commit: [https://github.com/populse/populse_sandbox/commit/87d5b78939fe61abd7db351caf3dd6136c1f35c6](https://github.com/populse/populse_sandbox/commit/87d5b78939fe61abd7db351caf3dd6136c1f35c6)
As you can see, we did not change the script of tests at all, nor the Travis configuration.

Best regards.

Lucie

**Comment by ouvrierl** [comment]
Hi,

I fixed the issue by just reinstalling PyQt5 with the following command:
 `pip install --upgrade --force-reinstall pyqt5;`

Best regards

Lucie

**Comment by buhtz** [comment]
This Issues is old but I'm still working on it.

The solution with `--upgrade --force-reinstall` doesn't work on PowerPC architecture where it seems that PyQt5 can not be build by `pip`.

I am still interested in a solution to use `PyQt5` on TravisCI where pyqt5 was installed via `apt`. I installed it but the python interpreter seems to not to see it.

https://stackoverflow.com/q/73762606/4865723

https://travis-ci.community/t/can-not-import-pyqt5-but-python3-pyqt5-is-installed/13290
