### ISSUE TITLE
New commits are not handled in a certain repository

### ISSUE THREAD

**Issue by shlomif** [travis-ci/travis-ci#9845]
Hi!

See https://travis-ci.org/shlomif/perl-File-Find-CaseCollide/builds and https://github.com/shlomif/perl-File-Find-CaseCollide/commits/master . The new commits there are not built.

Please look into it.

**Comment by DrTorte** [comment]
Hey there! 👋 

Sorry to hear about the hiccups here - looks like it's having issues parsing the yaml file. A quick look over it shows you're using tabs, and changing those over to spaces instead will do the trick.

As a tip if you see this again, if you click on `More Options` in the travis-ci.org link you sent, you can get to the `request` page. There, you'll see the error `could not parse .travis.yml` on request #2 and #3.

**Comment by shlomif** [comment]
On Thu, 05 Jul 2018 08:48:26 -0700
Kristofer Svardstal <notifications@github.com> wrote:

> Hey there! 👋 
> 
> Sorry to hear about the hiccups here - looks like it's having issues parsing
> the yaml file. A quick look over it shows you're using tabs, and changing
> those over to spaces instead will do the trick.
> 
> As a tip if you see this again, if you click on `More Options` in the
> travis-ci.org link you sent, you can get to the `request` page. There, you'll
> see the error `could not parse .travis.yml` on request #2 and #3.
> 

Thanks! should it not be displayed in the build history as well?

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Favourite FOSS - http://www.shlomifish.org/open-source/favourite/

You can never truly appreciate The Gilmore Girls until you’ve watched it in
the original Klingon.
    — http://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .
