### ISSUE TITLE
Unable to validate webhook calls

### ISSUE THREAD

**Issue by arpitjain305** [travis-ci/travis-ci#9856]
I am writing a webhook handler in Golang for travis-ci notifications. I went through the docs at https://docs.travis-ci.com/user/notifications#Verifying-Webhook-requests and followed the steps in https://gist.github.com/theshapguy/7d10ea4fa39fab7db393021af959048e (theshapguy/hooks.go). I fetched the corresponding public key for my repo from https://api.travis-ci.org/repos/arpitjain305/{reponame}/key. 

However, it fails in the call to VerifyPKCS1v15() and therefore does not validate the webhook call. 

Any help? Thanks,

**Comment by BanzaiMan** [comment]
I'm sorry to say that I don't know enough about Go to see what is going wrong with your code. May I suggest posting a question in https://travis-ci.community/c/languages/go? Thanks.
