### ISSUE TITLE
Cancel IRC notification sent with on_cancel set to never?

### ISSUE THREAD

**Issue by bmw** [travis-ci/travis-ci#9859]
I have `on_cancel: never` in [my .travis.yml](https://github.com/certbot/certbot/blob/cdf93de33899a95a544bbf7b99ddc1c327cc2728/.travis.yml#L105), however, I was just sent an IRC notification for https://travis-ci.org/certbot/certbot/builds/401837129 which was automatically canceled. Do IRC notifications not support `on_cancel` or is this a bug? If they don't support it, can support be added?

**Comment by zmike** [comment]
I have the same thing. It seems like 'cancel' is treated as a failure, and the `on_failure` setting overrides the `on_cancel` setting. I haven't tested to be sure, but that's my  guess.
