### ISSUE TITLE
Add 32-bit environments

### ISSUE THREAD

**Issue by staticfloat** [travis-ci/travis-ci#986]
Hello!  It appears that Travis has recently (relatively speaking) upgraded to 64-bit OS and CPU.  This is great, but it also is breaking some of our software.  We can fix it, and get everything working on 64-bit, but I wanted to check to see if it is possible to:

* Restrict a build to run on 32-bit or 64-bit only

* Run on both, a la via the `environment` block

Thank you!

(*Edited by @henrikhodne on 2013-07-16 to clarify title*)

**Comment by probonopd** [comment]
Same here, need 32bit x86

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
