### ISSUE TITLE
R/macOS incomplete C++17 support

### ISSUE THREAD

**Issue by plroebuck** [travis-ci/travis-ci#9860]
The image uses the Xcode clang (which [maps to clang3.9-based Apple variant](https://gist.github.com/yamaya/2924292)) rather than the clang6 compiler used for building R-3.5.0 El Capitan binaries as documented on the [CRAN macOS tools page](https://cran.r-project.org/bin/macosx/tools/). As such, [C++17 support](https://clang.llvm.org/cxx_status.html) is impacted.

```bash
$ clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Associated "${R_HOME}/etc/Makevars.site" modifications needed in addition to installation of package.
```console
###
### Makevars.site
###

## Use CLANG and GFortran with OpenMP support and C++17 standard features
CC=/usr/local/clang6/bin/clang
CXX=/usr/local/clang6/bin/clang++
CXX98=${CXX}
CXX11=${CXX}
CXX14=${CXX}
CXX17=${CXX}
CXX1X=${CXX}
FC=/usr/local/gfortran/bin/gfortran
F77=${FC}
FLIBS = -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm

```

**Comment by plroebuck** [comment]
Notifying @jeroen, @jimhester of R for Travis-CI macOS incomplete C++17 support.

**Comment by plroebuck** [comment]
I _could_, but that _was_ the point of using the standard image -- **the image should be providing the documented CRAN build toolchain**.

**Comment by plroebuck** [comment]
From [R for Mac OS X Development Tools and Libraries](https://cran.r-project.org/bin/macosx/tools/):
> **Important note:** R 3.5.0 El Capitan binaries are using Clang 6.0.0 and GNU Fortran 6.1 to provide OpenMP parallelization support and C++17 standard features. If you want to compile R packages from sources, please download GNU Fortran binary from the official GNU Fortran Binaries page - in particular OS X 10.11 gfortran 6.1. Alternatively, we are providing a copy here as well as Clang 6.0.0 binaries for OS X 10.11 and higher - see below for the download links. __You can also try to use clang from Xcode, but it will be missing required features so your mileage may vary and it is not recommended.__

Is there a _good_ reason for not following Simon Urbanek's warning?

**Comment by jeroen** [comment]
We prefer to be conservative and stick with the default xcode compilers, which is what 95% of the users will be using. The custom cran toolchain has some problems, and doesn't play nice with homebrew.

If you need a newer compiler, the easiest way is to add `brew_packages: llvm` which currently has clang 7. Make sure to put it on the PATH though, because homebrew doesn't do that by default.

**Comment by plroebuck** [comment]
Could you detail these problems with using the CRAN-specified build chain? Were they reported to Simon?

I question the validity of testing R packages for production using a different build chain than the one _specified_ by CRAN.

**Comment by plroebuck** [comment]
Additionally, the use of Xcode's ancient clang would also seem to preclude use of OpenMP, as Apple’s bundled one is the only major compiler which doesn’t include OpenMP.

For anyone else who might wind up here, James Balamuta explains in detail how to configure OpenMP in R on macOS [here](https://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/).

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
