### ISSUE TITLE
Enable IPv6 for MySQL service

### ISSUE THREAD

**Issue by garex** [travis-ci/travis-ci#9861]
Currently we have
```
$ grep -R bind /etc/mysql
/etc/mysql/my.cnf:bind-address		= 127.0.0.1
```

To enable local ipv6 loopback see https://dev.mysql.com/doc/refman/5.5/en/server-options.html#option_mysqld_bind-address

```
/etc/mysql/my.cnf:bind-address		= ::
```

> If the address is ::, the server accepts TCP/IP connections on all server host IPv4 and IPv6 interfaces. Use this address to permit both IPv4 and IPv6 connections on all server interfaces.

ps: Applies both for precise and trusty.

**Comment by garex** [comment]
It's still actual.

**Comment by DrTorte** [comment]
Hello,

I'll get this tracked internally! In the meantime, we're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
