### ISSUE TITLE
Homebrew fails to use bottles

### ISSUE THREAD

**Issue by ngld** [travis-ci/travis-ci#9865]
Apparently Homebrew fails to download bottles due to invalid download links.
After a `brew install p7zip ninja qt5`, Homebrew starts updating itself as usual but generates this strange message:
```
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask, homebrew/cask, homebrew/core).
```

The last successful build doesn't list cask twice though I have no idea why this would change.
Here's a failed build: https://travis-ci.org/ngld/knossos/jobs/401970441
And here's a successful build: https://travis-ci.org/ngld/knossos/jobs/382785291

I cancelled the problematic build since compiling Qt would've taken too long anyway.

**Comment by StrikerRUS** [comment]
We have the same problem for `gcc` and its dependencies. But it seems to be Homebrew issue, not Travis, because the same is observed at VSTS.

https://travis-ci.org/Microsoft/LightGBM/jobs/402368743

```
==> Downloading /bottles/gcc-8.1.0.sierra.bottle.1.tar.gz
curl: (3) <url> malformed
Error: Failed to download resource "gcc"
Download failed: /bottles/gcc-8.1.0.sierra.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-8.1.0/gcc-8.1.0.tar.xz
==> ../configure --build=x86_64-apple-darwin16.7.0 --prefix=/usr/local/Cellar/gc
==> make
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by rtobar** [comment]
Same problem here: https://travis-ci.org/ICRAR/shark/jobs/402147701. I am first doing `brew unlink python`, and then doing `brew install gsl hdf5 cxxtest`, which fails to get all bottles due to malformed urls (like in the previous comment), and then tries to compile packages instead, eventually timing out when compiling `gcc`. I'm not sure which of the two is triggering the auto-update of brew though.

**Comment by szeck87** [comment]
Same with `clang-format`.  https://travis-ci.com/Unibeautify/beautifier-clang-format/jobs/133750508

**Comment by StrikerRUS** [comment]
The problem has gone for us about several minutes ago. Rerun your builds, guys.

**Comment by szeck87** [comment]
Yes, looks like it downloads from `https://homebrew.bintray.com`, which was missing before.

**Comment by ngld** [comment]
Thanks for the heads up!
