### ISSUE TITLE
Linux machine build failing with "Can't answer a question unless a user TTY".

### ISSUE THREAD

**Issue by kanekotic** [travis-ci/travis-ci#9870]
Hello Travis-ci team, I have an open source project and I am trying to use a Cron job to update my dependencies and retrofit them into my repository and publish a version in NPM.

The next is the error causing the [build to fail](https://travis-ci.org/kanekotic/raw-guid-converter/builds/402513814)
```bash
$ yarn version --patch
...
error An unexpected error occurred: "Can't answer a question unless a user TTY".
...
``` 

I have tried multiple things seen in similar bugs in yarn repo but I am unable to fix this. 
The command and everything works without user interaction locally and if I use an OSX machine it [works fine](https://travis-ci.org/kanekotic/raw-guid-converter/builds/402517883) (but I feel is an overkill to use OSX machines for this).

Any recommendation or options?

**Comment by kanekotic** [comment]
this error is still happening. Don't Close

**Comment by BanzaiMan** [comment]
This sounds like a tooling issue. Your job will run without TTY; it runs on your local machine fine because it has a TTY. If yarn's message is to be believed, you'd have to devise a way to interact with yarn without it.

**Comment by kanekotic** [comment]
BanzaiMan thanks for the answer :) . 

I will also open this and link it here becasue I am still not sure if its related to `yarn` or `travis` as the only thing that i am doing is a ```yarn version --patch``` that as a user i am not interacting with the terminal. 

As said this works on your `osx` images but not on the `linux` ones. That is the casue why I oppened the ticket as it colud be some kind of configuration parameter that could be added to how you generate machines. 

If its solved by configuration it could solve similar issues independant of the tool or language.

**Comment by BanzaiMan** [comment]
Could very well be the OS differences, or different versions of yarn. A quick search reveals a few issues with yarn related to this error message in the past.
