### ISSUE TITLE
travis_wait not present in container running locally

### ISSUE THREAD

**Issue by pydo** [travis-ci/travis-ci#9872]
**Description**
I'm trying to run my build locally using the travis docker based infra documented here https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally . But I can't find the  `travis_wait` CLI anywhere in the container.

**Procedure**
1. `docker run --name travis-debug -dit travisci/ci-garnet:packer-1512502276-986baf0 /sbin/init`
2. `docker exec -it travis-debug bash -l`
3. `su - travis`
4. attempt to find `travis_wait` 
```
travis@58b12de958bb:~$ travis_wait
travis_wait: command not found
root@58b12de958bb:/# find . -iname 'travis_wait'
```

**Expected behavior**
4. `travis_wait` is present

**Actual behavior**
4. `travis_wait` is not present

**Comment by BanzaiMan** [comment]
Hello, there.

`travis_wait` is a bash function defined within the build script, so it is not present in the image. See https://github.com/travis-ci/travis-build/blob/3af56667b3221448763e79a73007b94a38bb9612/lib/travis/build/templates/header.sh#L213-L271 for the current implementation.
