### ISSUE TITLE
`check_suite` event for Check API never sent on completed builds

### ISSUE THREAD

**Issue by bobvanderlinden** [travis-ci/travis-ci#9873]
Currently when I run a build and have a Github App subscribed to Check API events (like `check_suite`), the app does receive the initial `pending` event, but doesn't receive any events when the build was completed (neither successfully nor failing).

I suspect this is a problem with TravisCI, since this also happens in the Github UI. When I start a build it is shown in the PR, but when I keep that page open and the build completes, the UI does not change. Only after refreshing the page will the status be up-to-date.

Let me know if this is actually a Github issue.

**Comment by BanzaiMan** [comment]
Hello, there. Sorry for the delay.

Are you inquiring about a GitHub Apps you built, or our GitHub Apps integration?

**Comment by bobvanderlinden** [comment]
I cannot reproduce this issue anymore. I think it's solved by removing the Travis service.
