### ISSUE TITLE
Duplicate status checks on PR

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#9874]
![image](https://user-images.githubusercontent.com/4777512/42594452-ea5ae5b8-8557-11e8-83b6-d399d336a0f4.png)

Having 4 status checks on a pull request instead of 2.

How to get rid of the redundant 2 of them?

**Comment by tooomm** [comment]
Duplicate of https://github.com/travis-ci/travis-ci/issues/9618
