### ISSUE TITLE
Sudo commands in .travis.yml no longer auto-detected 

### ISSUE THREAD

**Issue by smowton** [travis-ci/travis-ci#9875]
Previously scripts with sudo commands seemed to be automatically directed to GCE, even if they said `sudo: false`, as noted here [https://docs.travis-ci.com/user/reference/overview/#For-a-particular-.travis.yml-configuration]. However as of the 12th July it appears this is no longer the case, and those jobs fail when they try to run `sudo`. Is the change intentional? If so, please update the docs accordingly.

**Comment by iriberri** [comment]
Hi @smowton - thanks for opening this. I can confirm that `sudo` stopped being detected automatically a few weeks ago and this change was reverted some hours after that.

Please feel free to reopen if you experience any related issues.

Thank you!
