### ISSUE TITLE
Dockerized builds fail since 12th of july

### ISSUE THREAD

**Issue by Pro** [travis-ci/travis-ci#9876]
It looks like this issue is related to #9875.
Since yesterday our `sudo: false` builds do not run through anymore.
The fail on random lines, e.g. check:
https://travis-ci.org/open62541/open62541/builds/403180833?utm_source=github_status&utm_medium=notification

This build from 2 days ago was fine:
https://travis-ci.org/open62541/open62541/jobs/402635184

The only difference can be seen here:
https://github.com/open62541/open62541/compare/b6b58a8ea275...913df28b6cd428221b29229474940f8f09ded5e1

Even if I revert that change the builds do not work anymore.

How can I fix that?

**Comment by BanzaiMan** [comment]
Sorry for the delay. Is this still a problem? If so, please point to a more recent build log URL. Thanks.
