### ISSUE TITLE
Thoughts for Secure Environment Variables usage in PR's

### ISSUE THREAD

**Issue by cgiroua** [travis-ci/travis-ci#9878]
Some of our tests require third party authentication, so we are utilizing the Secure Environment Variables (SEV's) to accomplish that task, however for PR's without those variables set the tests fail (correctly so for all the right reasons).  We'd like to include these tests in a CI pipeline, I see that the jwt addon was a solution for a while, but is now deprecated.

Two thoughts we had on this as possible solutions:
- The ability to grant trusted permissions on a git repo to specific users to allow usage of SEV's in travis PR's
- The ability to set SEV's by user account, possibly both global and repo specific which would be used only for PR's (and a travis setting on each project to allow them, or not)

The former introduces some account management which creates overhead, the latter would likely be 'easier', but could possibly open up a can of worms with attempts to inject some nefarious variables.

Just hoping for a discussion/solution for this feature request.

**Comment by CSchulz** [comment]
@DrTorte Are there any changes about this feature request or why did you closed it?

**Comment by DrTorte** [comment]
Sorry, I meant to include the direct to the forum. 🙂 

[Here's a link to the thread!](https://travis-ci.community/t/issue-thoughts-for-secure-environment-variables-usage-in-prs-migrated-from-issues/1241)
