### ISSUE TITLE
Nix: Unable to import from derivation?

### ISSUE THREAD

**Issue by teozkr** [travis-ci/travis-ci#9880]
cc @domenkozar @garbas @matthewbauer

https://travis-ci.org/Etimo/photo-garden/jobs/403655796 seems to fail when trying to import the yarn2nix that we have downloaded. After trying to download yarn2nix separately (https://travis-ci.org/Etimo/photo-garden/jobs/403663724) it just seems to fail on another IFD.

Weirdly enough, everything seemed to work when I tried to produce a minimal repro: https://travis-ci.org/teozkr/nix-ifd-demo/builds/403667219

Suspecting that something was weird with my environment, I tried building it inside a Ubuntu 18.04 VM, fresh off the ISO presses. But everything works fine there, too. 

At this point, I'm just completely stumped.

**Comment by teozkr** [comment]
Weirdly the whole thing seems to build fine (including IFDs) on both Ubuntu 14.04 and Ubuntu 14.04.5 VMs.

**Comment by domenkozar** [comment]
```
error: cannot import '/nix/store/hm50a51g26lz37s1rx852k4ih3nwrsxg-source', since path '/nix/store/780s4ci6s6iflrmqm0ys5d34cla0nn9b-source.drv' is not valid, at /home/travis/build/Etimo/photo-garden/default.nix:14:14
```

interesting error, I'm happy to help if you boil it down to a simple example that fails on travis.

**Comment by teozkr** [comment]
Turns out I was an idiot who added `--readonly-mode` earlier, and forgot to remove it. So sorry for wasting your time. :/
