### ISSUE TITLE
binaries installed using `yarn global add` not in path

### ISSUE THREAD

**Issue by jeysal** [travis-ci/travis-ci#9885]
Example build: https://travis-ci.org/spockjs/spockjs/jobs/404606086 (see `codecov` at the very end).
First noticed this a few hours ago, seems like [this](https://github.com/travis-ci/travis-ci/issues/8890) issue from last december again.

**Comment by alexreardon** [comment]
For those who are stuck on this, @MarshallOfSound created a temp work around for `react-beautiful-dnd`

https://github.com/atlassian/react-beautiful-dnd/pull/642

**Comment by 8eecf0d2** [comment]
also experienced and fixed with:
```
before_install:
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add ...
```
8eecf0d2/jagwah#15 greenkeeperio/greenkeeper-lockfile#185

**Comment by jeysal** [comment]
fixed by https://github.com/travis-ci/travis-build/pull/1436
