### ISSUE TITLE
IP address 147.75.198.203 missing on nat.linux-containers.travisci.net

### ISSUE THREAD

**Issue by jobachhu** [travis-ci/travis-ci#9889]
We've been getting requests from a new IP address in our container-based builds, but I couldn't find it documented anywhere. Both the [doc page](https://dnsjson.com/nat.linux-containers.travisci.net/A.json) and the A record for nat.linux-containers.travisci.net are missing the IP address 147.75.198.203.

Is this new IP address being used on purpose? If yes, could you add it to the docs and the A record? 

Thanks!

**Comment by meatballhat** [comment]
@jobachhu I'm sorry for the delay.  This is one of our NAT hosts, although it was missing from the public DNS record for ~6 weeks :frowning:

**Comment by jobachhu** [comment]
No worries, thanks for adding it!
