### ISSUE TITLE
Problems with login to travis-ci

### ISSUE THREAD

**Issue by mossbound** [travis-ci/travis-ci#9893]
I'm having a problem logging into travis-ci.com with my GitHub credentials.  Problem seems to be intermittent but it happening around 80% of the time.  After the sign-in page I get a blank page with no CSS or html and just the message: "could not resolve github token" 

Symptoms are very similar to #7234 and #7230 

Problem occurs on Safari Version 11.0.2 (12604.4.7.1.4) in private browsing on macOS Sierra.  Works fine on Chrome in Incognito mode

**Comment by biancawilk** [comment]
Hi @mossbound is it ok to close this issue? Please re-open if you'd like to follow up on it!
