### ISSUE TITLE
Unable to start Android 26 emulator 

### ISSUE THREAD

**Issue by shridharkalagi** [travis-ci/travis-ci#9894]
Getting below error when I launch Android 26 Emulator. 

my travis file [here](https://gist.github.com/shridharkalagi/27d967d522cab75c905314f90b7ee605)

echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
Valid ABIs: no ABIs.
Error: Invalid --abi armeabi-v7a for the selected target.
The command "echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a" failed and exited with 1 during .
Your build has been stopped.

**Comment by tscholze** [comment]
@shridharkalagi did you find a fix for that issue? I ran into the same behavior.

**Comment by shridharkalagi** [comment]
This one works for me
https://github.com/shridharkalagi/java-client/blob/androidCI/.travis.yml

**Comment by tscholze** [comment]
@shridharkalagi Thanks! This travis script uses android 24, I need some 26ish. Maybe there's another fix for that. Somehow or other, thanks for you help, mate!

**Comment by shridharkalagi** [comment]
Please ping here if you find the solution for >24

**Comment by biancawilk** [comment]
Hi @shridharkalagi @tscholze 👋 Is it ok to close this issue or can we help you further? Please let us know if the issue persists!

**Comment by tscholze** [comment]
@biancawilk I got an Email from the support team that it is not possible to use such "newer" Android APIs. 

So, it's okay for me if you close this issue. :)

**Comment by huxaiphaer** [comment]
Would you mind sharing your tranis.yml file, because am having the same problem?
