### ISSUE TITLE
Service Unavailable while installing mono

### ISSUE THREAD

**Issue by Sebazzz** [travis-ci/travis-ci#9897]
Using Travis for a .NET Core project build. Mono is used because the build system (Cake) does not properly support .NET core fully.

Relevant extraction from log:
```
C# support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry


Installing Mono
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/libg/libglade2/libglade2-0_2.6.4-2_amd64.deb  503  Service Unavailable [IP: 35.192.35.27 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Is it possible to work around, perhaps specify multiple apt restore sources?

Link to the build: https://travis-ci.org/Sebazzz/financial-app/builds/405488073#L402

@joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
This is not a problem with the C# language support but a more general problem with the Ubuntu mirror.

Fetching http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/libg/libglade2/libglade2-0_2.6.4-2_amd64.deb works from here so it's most likely a transient issue no Ubuntu's side.
