### ISSUE TITLE
Homebrew must be run under Ruby 2.3! You're running 2.0.0 on xcode7.3

### ISSUE THREAD

**Issue by Flamefire** [travis-ci/travis-ci#9913]
I'm getting the error `Homebrew must be run under Ruby 2.3! You're running 2.0.0` for `osx_image: xcode7.3` (only)

According to the docs, it is not recommended to run `brew update` so I'd considers this as a bug in the travis image.

Any ideas how to solve this?

**Comment by BanzaiMan** [comment]
Duplicate of #9253.
