### ISSUE TITLE
Using 3 or more stages in conjunction with the cache can frequently result in spurious failures with confusing error messages

### ISSUE THREAD

**Issue by JasonGross** [travis-ci/travis-ci#9915]
The [documentation for stages](https://docs.travis-ci.com/user/build-stages/warm-cache/) gives an example of warming up the cache in one stage, and then running the build in the subsequent stage.  However, splitting the work like this can result in spurious failures with confusing error messages.  In particular, suppose I update my dependencies from version A to version B, and I update my code so that it builds with version B, and I do both of these in a single commit.  If I push this commit after the cache-warmup job for the current tip of master has finished, but before all of the jobs in the later stages have started, travis will sometimes start (and finish) the cache-warm-up job of the new commit before finishing all of the jobs of the old commit.  If this happens, than subsequent jobs of the old commit will use the new cache, and may fail with rather confusing error messages.

Please either add support for commit-local caches, or have travis *never* start a job if another job is running on a different commit utilizing the same cache.

See, for example, [this build](https://travis-ci.org/mit-plv/fiat-crypto/builds/408197309), where I believe the one failing job used a different version of the cache than all of the other jobs.

**Comment by JasonGross** [comment]
Note that this can also fail with sequencing in the other direction.  If the old commit has a job that starts before the new commit's cache-warm-up stage, and finishes between when the new commit's cache-warm-up finishes and when the new commit's subsequent stages start, then the old commit's job will blow away the new commit's cache when it stores its cache after finishing.

**Comment by BanzaiMan** [comment]
In the original example, the commit effectively makes the previous cache obsolete. Is that right?

Unless there is a way for the dependency manager to detect this and update the dependency automatically, I am not sure if there is much we can do to ease the pain.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
