### ISSUE TITLE
Feature Request: Custom formatting for stage names

### ISSUE THREAD

**Issue by jakemac53** [travis-ci/travis-ci#9916]
I noticed with the v1 release of stages/conditions that custom names are supported for stages now which is great! It does seem a bit difficult to get decent formatting though, it seems that only raw text is supported.

Would it be possible to  support markdown, html, or some other custom formatting options within stage names?  You can see some things I tried in this pull request https://github.com/dart-lang/mono_repo/pull/87.

Specifically, it would be nice to be able to add extra whitespace for separation of sections, bold/italics, and possibly also multiline descriptions.

**Comment by jakemac53** [comment]
Afaik this issue is still valid

**Comment by DrTorte** [comment]
Hello,

Thanks for opening this issue! We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
