### ISSUE TITLE
Github team members permissions

### ISSUE THREAD

**Issue by El-Fitz** [travis-ci/travis-ci#9917]
Just a quick issue we ran into today.

We had a team member in our github organization, in a team with write permissions to a private repo, but when trying to see the build results on travis-ci.com, he ended up on a page saying the repository could not be found.

Adding him as a collaborator on the repository with write permissions fixed the issue, but it does defeat the purpose of organizations and teams :-)

**Comment by BanzaiMan** [comment]
What was the tram member’s GitHub account, and what was the repository in question? Had the team member been added to the repo shortly before the issue manifested? Or was it a long time (24 hours or more)?

**Comment by El-Fitz** [comment]
Hi @BanzaiMan ! Honestly, I don't remember anymore, sorry

**Comment by felker** [comment]
I had a similar issue recently. The user had been an Outside Collaborator with Read access to a private repo for many weeks, but could not access the Travis CI build logs. 

Giving him Write access fixed the issue, but also converting the Outside Collaborator to a Team member to the repo's organization with Read access fixed the issue.

GitHub documentation on Teams vs. Outside Collaborators on Organization private repositories is somewhat lacking...

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
