### ISSUE TITLE
Build failed as no output has been received in the last 10m0s

### ISSUE THREAD

**Issue by rsketine** [travis-ci/travis-ci#9919]
Our builds for last week are failing with this error in CI. We do not have any issues with these builds in  our CI. Is there a way that we can get some more debugging info so that we can fix these builds. What is the best way.

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

https://travis-ci.org/NervanaSystems/ngraph/jobs/409057286

**Comment by pvdlg** [comment]
It seems it happens a lot more often in the last few months.
90% of the time it happens during `npm install` on my builds. I happens on both Linux and MacOs with any version of Node.js.
For example:
- https://travis-ci.org/pvdlg/karma-sass-preprocessor/jobs/412220739
- https://travis-ci.org/pvdlg/karma-sass-preprocessor/jobs/412214670
- https://travis-ci.org/pvdlg/karma-jasmine-jquery/jobs/413268554
- https://travis-ci.org/pvdlg/karma-jasmine-jquery/jobs/412559919

**Comment by pvdlg** [comment]
This issue is still happening frequently, here some more examples:
- https://travis-ci.org/pvdlg/env-ci/jobs/424570383
- https://travis-ci.org/pvdlg/karma-jasmine-jquery/jobs/424576790
- https://travis-ci.org/pvdlg/karma-rollup-preprocessor/jobs/421338512
- https://travis-ci.org/semantic-release/travis-deploy-once/jobs/425203419
- https://travis-ci.org/semantic-release/travis-deploy-once/jobs/425203420

**Comment by pvdlg** [comment]
For information it happens less often than before but there is still some occurrences:
- https://travis-ci.org/semantic-release/cli/jobs/450121638

**Comment by offa** [comment]
After moving some builds to Xenial, I run into timeouts regular. There are builds, where almost every job times out.

**Comment by offa** [comment]
My problem no longer occurs and Xenial works normal.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
