### ISSUE TITLE
Still receiving emails on old primary email 

### ISSUE THREAD

**Issue by ansermino** [travis-ci/travis-ci#9920]
I recently changed my primary email on Github (~ a week ago). I'm still receiving emails from travis on my old primary email. There is nothing in my .travis.yml's that dictate email notifications. Is there someway to force travis to update it?

**Comment by iriberri** [comment]
Hi @ansermino,

Travis CI generally sends email notifications to the email address specified in your Git commit, however, we only send to email addresses that GitHub tells us are known.

This means you can control which email address notifications are going to be sent to, by setting your email address in your Git configuration, either globally or for individual repositories. See https://docs.travis-ci.com/user/notifications/#Changing-the-email-address-for-build-notifications

We do have plans to improve this in the future and allow users to overwrite this behaviour. However, there's no ETA for that at this moment.

Does this help? Please feel free to reopen if you have further questions, or if there's anything else we can help with!
