### ISSUE TITLE
Cache dpl and dependencies

### ISSUE THREAD

**Issue by bogosj** [travis-ci/travis-ci#9921]
On every build the dpl gem and the dependencies (i.e. the requisite install of the firebase-tools npm) are installed. This takes 20-40 seconds which would be drastically reduced if it were cached.

**Comment by cotsog** [comment]
I'm trying to see if we can improve this further but today I'm seeing the `dpl` installation taking 1-2 second. See https://travis-ci.org/cotsog/travis_ci_prod_regular/jobs/410803051#L489.

Could you tell me if you are seeing the same on your side?

Thanks!
​
​

**Comment by bogosj** [comment]
I don't know Ruby well, but is it possible the dpl and dpl-firebase gems install quickly, but because dpl-firebase depends on a node module:
https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/firebase.rb#L4

That install takes time? When I watch the build live the actual deploy to firebase is just a few seconds (5 max).

Also worth noting the https://travis-ci.org/rutherford-nj/www.rutherfordboronj.com/jobs/410501809 is an extreme outlier in time, most builds in that project are between 60s and 90s, of which I think a majority is waiting for a build worker.

**Comment by bogosj** [comment]
This change shaved 15-20 seconds off of my deploy:
https://github.com/rutherford-nj/www.rutherfordboronj.com/compare/a202d49d5182bddf1fce8d2665c6d039bfec6ca4...825b18891539981789ad9ebb4b0b228bff7e98a1

I'm manually installing firebase-tools and caching and no longer relying on the deploy: settings in travis.yml

**Comment by BanzaiMan** [comment]
Hi, @bogosj Thanks for the followup. The time saving is substantial and can be beneficial to other users of firebase. Do you mind opening a PR to our docs? https://github.com/travis-ci/docs-travis-ci-com

**Comment by bogosj** [comment]
My solution seems like a dirty workaround to using the native config-based deployment process. IMO it would be better to leave people on a "supported" configuration based deployment and eventually integrate caching the node modules when these deploy rules are used.
