### ISSUE TITLE
Use PHP with updated curl version

### ISSUE THREAD

**Issue by Nyholm** [travis-ci/travis-ci#9924]
Currently, PHP 7.1 is built with cUrl 7.35.0. I can remove cUrl and built if from source. 
```
$ curl --version
7.61.0 ...
```
But of course that did not change PHP's cUrl version: 
```
$ php -r "echo 'PHP cUrl version:\ '.curl_version()['version'];"
7.35.0
```

I need to rebuild PHP to be able to use the latest changes in cUrl from a PHP script. 

As far as I know, there is no way for me to rebuild PHP or make sure PHP is using version 7.61.0. Is that really correct?

(I know I can spin up a docker container, but that is not really a pretty solution...)

**Comment by BanzaiMan** [comment]
This is probably because Trusty's library is 7.35.0 https://packages.ubuntu.com/trusty/curl. And this is unlikely to change.

You can try `sudo: required` & `language: php`, but that might require unexpected pitfalls.
