### ISSUE TITLE
Consider providing jdk_switcher as a script

### ISSUE THREAD

**Issue by rbrw** [travis-ci/travis-ci#9927]
This would allow it to be used from places other than the top-level in .travis.yml, e.g. from within testing scripts that can detect the desired jdk from an argument or environment variable:

```
env: FOO_TEST=core/openjdk8/bar9/baz3
script: travis/run-tests
```

Right now that's not possible because jdk_switcher is a shell function.

Thanks

**Comment by BanzaiMan** [comment]
You can `source` the function:

    source /opt/jdk_switcher/jdk_switcher

or export the function:

```sh-session
travis@travis-job-banzaiman-travis-product-429773641:~/build/BanzaiMan/travis_production_test$ cat jdk.sh
#! /bin/bash

jdk_switcher
travis@travis-job-banzaiman-travis-product-429773641:~/build/BanzaiMan/travis_production_test$ ./jdk.sh
./jdk.sh: line 3: jdk_switcher: command not found
travis@travis-job-banzaiman-travis-product-429773641:~/build/BanzaiMan/travis_production_test$ export -f jdk_switcher
travis@travis-job-banzaiman-travis-product-429773641:~/build/BanzaiMan/travis_production_test$ ./jdk.sh
Usage: jdk_switcher {use|home} [ JDK version ]
```

**Comment by rbrw** [comment]
Hiro Asari <notifications@github.com> writes:

> You can `source` the function:
>
>     source /opt/jdk_switcher/jdk_switcher
>
> or export the function:

[...]

> travis@travis-job-banzaiman-travis-product-429773641:~/build/BanzaiMan/travis_production_test$ ./jdk.sh
> Usage: jdk_switcher {use|home} [ JDK version ]

I thought I'd tried that (export -f) and it failed because jdk_switcher
calls other functions that would also have to be exported, and
maintaining that list would be fragile.

Wonder if you'd see the same thing with a valid invocation.

In any case, assuming sourcing /opt/jdk_switcher/jdk_switcher is
supported, then that may be a viable alternative.

Thanks
--
Rob Browning
