### ISSUE TITLE
Drop trusty, start using bionic

### ISSUE THREAD

**Issue by KOLANICH** [travis-ci/travis-ci#9928]
Trusty lacks some new packages like `openjdk-11-jre-headless`

**Comment by Peque** [comment]
> **BanzaiMan** [commented on May 27](https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-392340511)
> *The work on Bionic is not too far behind. Thanks!*

@BanzaiMan Any updates on this matter since that comment?

**Comment by bittner** [comment]
[python3-wxgtk4.0](https://packages.ubuntu.com/bionic/python3-wxgtk4.0) is an example of a package available neither in the Trusty no the Xenial image. Only Bionic would help. We're [unable to use Travis](https://github.com/cool-RR/PythonTurtle/pull/119) for running all tests due to that.

**Comment by dreibh** [comment]
+1

**Comment by avikivity** [comment]
+1 - need libc-ares 1.13 for https://github.com/scylladb/seastar, this is not available in xenial.

**Comment by BanzaiMan** [comment]
Duplicate of #5821.

**Comment by Peque** [comment]
@BanzaiMan Being locked, we cannot even react with a :+1: on that issue. :disappointed:
