### ISSUE TITLE
Please provide a mailing list to discuss issues

### ISSUE THREAD

**Issue by noloader** [travis-ci/travis-ci#9931]
We are struggling with a build problem. We cannot find a place to discuss it.

Visiting the Travis homepage takes us to a dashboard so we can't view the homepage for links like "mailing list." Searching the docs returns 0 hits. Google returns 0 hits (though lots of irrelevant noise).

Please provide a mailing list to discuss issues.

-----

![travis-ml-1](https://user-images.githubusercontent.com/3538226/43556751-5b9718d2-95cf-11e8-9780-2882e585abfa.png)

**Comment by BanzaiMan** [comment]
Hello, there. Please use https://travis-ci.community to discuss issues.

I am afraid we will not set up mailing lists.
