### ISSUE TITLE
Git checkout fails when tag contains ";" in name

### ISSUE THREAD

**Issue by barak007** [travis-ci/travis-ci#9934]
Hello Travis team,

When running `git checkout`, the tag name is not being escaped.

If I have the tag `RC;.;1.0.0`, Travis fails with:
```
$ git checkout -qf RC;.;1.1.0
error: pathspec 'RC' did not match any file(s) known to git.
/home/travis/.travis/job_stages: line 78: .: filename argument required
.: usage: . filename [arguments]
1.1.0: command not found
```

The repo is a private repo connected to private Travis, but I can provide a link to the build log, if needed.

**Comment by BanzaiMan** [comment]
In short, we are not escaping `;` during our build, and the commands are failing.

In general, though, unless it is *absolutely* necessary, I suggest avoiding such shell special characters in places where the shell would interact. You'll have to escape them carefully when you write your build script, invoke other utility, etc.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
