### ISSUE TITLE
Open the `cancel` button permission to allow contributors to terminate the `matrix` build job

### ISSUE THREAD

**Issue by asdf2014** [travis-ci/travis-ci#9940]
Is there any plan to open the `cancel` button permission to allow contributors to terminate the `matrix` build job? Not only is it harmless, it also saves travis resources.

**Comment by DrTorte** [comment]
Hey there,

Thanks for making this suggestion! We haven't fully released it yet, but we are doing a soft launch of a community forum. Right now our Product team is already active over there and talking suggestions/requests, so I'd suggest you post this there. 

[Community Forum](https://travis-ci.community/)

**Comment by asdf2014** [comment]
Hi, @DrTorte . Thanks, I will repost it in the community forum.
