### ISSUE TITLE
MacOS build seems to have switched to java 10, even when Xcode 9.4 is specified

### ISSUE THREAD

**Issue by juliandolby** [travis-ci/travis-ci#9942]
We have previously had MacOS builds working using the java 8 that is the default on the Xcode configurations, but in the last 3 days the java changed to java 10, which causes our builds to fail on MacOS.  We also test on Travis Linux images, using jdk8, and that still works fine.

Is there a way to make the system continue to use java 8?

The first part of my log is as follows:

Worker information
hostname: da40683a-1703-4518-8c4b-788d84a189ca@31129.wjb-2
version: v3.10.1 https://github.com/travis-ci/worker/tree/2f4923494b1f57289a2d4b68a0861e882a7215ad
instance: 2b023a7d-67be-4c93-8d26-50c7e57044e8 travis-ci-macos-10.13-xcode9.4.1-1529955246 (via amqp)
startup: 1m10.464223032s
system_info
Build system information
Build language: java
Build id: 411718974
Job id: 411718980
Runtime kernel version: 17.4.0
travis-build version: dc71e34c8
Network availability confirmed.
Fix WWDRCA Certificate
Unable to delete certificate matching "0950B6CD3D2F37EA246A1AAA20DFAADBD6FE1F75"security: AppleWWDRCA.cer: already in /Library/Keychains/System.keychain
$ rvm use
Using /Users/travis/.rvm/gems/ruby-2.4.3
git.checkout
2.16s$ git clone --depth=50 --branch=master https://github.com/wala/WALA.git wala/WALA
Cloning into 'wala/WALA'...
$ cd wala/WALA
$ git checkout -qf 25bb5192216e84dfefaa1e26866aaa6de022b689
Setting environment variables from .travis.yml
$ export AUTH_TOKEN=[secure]
$ export GH_TOKEN=[secure]
$ export BUILD_SYSTEM=gradle
$ export TERM=dumb
Disabling Gradle daemon
$ mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
cache.1
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
0.16s$ Installing caching utilities
0.01s
3.15sattempting to download cache archive
fetching master/cache-osx-xcode9.4-d7bf7c58fc9dabce11738c8ae240e48ac4f1897f36de9df2fba0d3529038d7f2.tgz
could not download cache
0.01s
2.59sadding /Users/travis/.goomph to cache
creating directory /Users/travis/.goomph
adding /Users/travis/.gradle/caches to cache
creating directory /Users/travis/.gradle/caches
adding /Users/travis/.gradle/wrapper to cache
creating directory /Users/travis/.gradle/wrapper
adding /Users/travis/.m2 to cache
creating directory /Users/travis/.m2
adding /Users/travis/apache-maven-3.5.0 to cache
creating directory /Users/travis/apache-maven-3.5.0
adding /Users/travis/build/wala/WALA/com.ibm.wala.core.testdata/ocaml/ocamljava-2.0-alpha1/lib to cache
creating directory /Users/travis/build/wala/WALA/com.ibm.wala.core.testdata/ocaml/ocamljava-2.0-alpha1/lib
$ java -Xmx32m -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
$ javac -J-Xmx32m -version
javac 10.0.1

**Comment by DrTorte** [comment]
Hey there,

Thanks for letting us know about this! From my understanding this shouldn't be occurring, so do you happen to have a link to a build log specifically where this occurs, or the .travis.yml file? If it's private, I'd suggest emailing it in to support@travis-ci.com

Thanks and all the best. :)

**Comment by juliandolby** [comment]
https://travis-ci.org/wala/WALA/jobs/411718980 <https://travis-ci.org/wala/WALA/jobs/411718980> is a log of one of our jobs, showing that it is using Java 10.

  Thanks,
	Julian

**Comment by cotsog** [comment]
@juliandolby Thanks for providing us this link! Could you also post one of the last build that succeeded (i.e. it installed Java 8 on macOS)?

**Comment by juliandolby** [comment]
I think this is the most recent: https://travis-ci.org/wala/WALA/jobs/409926246

**Comment by cotsog** [comment]
@juliandolby your last succeeding build ran with `osx_image: xcode8.3` see https://travis-ci.org/wala/WALA/jobs/409926246#L4.

Your failure is most probably a result our new Xcode default image which is now `osx_image: xcode9.4` since Tuesday. See [our blog post](https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce) to learn more.

You should be able to fix this by adding `osx_image: xcode8.3` to your .travis.yml file. Here's a PR with the change: https://github.com/wala/WALA/pull/337.

Hope this helps!

**Comment by juliandolby** [comment]
Worked.  Thanks.

**Comment by DrTorte** [comment]
Fantastic, thanks for letting us know. Going to close this one then. :)
