### ISSUE TITLE
output of docker-compose is truncated

### ISSUE THREAD

**Issue by nicosmaris** [travis-ci/travis-ci#9943]
output of docker-compose is truncated for the last 3 commands and the build exits with 1 even though all commands exit with 0:

https://travis-ci.org/nicosmaris/data-pipeline/builds/411828816

**Comment by DrTorte** [comment]
Hey there,

Sorry to hear about that! The truncation is definitely curious, so I'm checking internally. That being said, I am seeing a command failing on [line #1385](https://travis-ci.org/nicosmaris/data-pipeline/builds/411828816#L1385) which would probably be the source of the build exiting with 1.

Thanks and happy building!

**Comment by DrTorte** [comment]
Update: After checking with one of support humans, they pointed out that someone else encountered a similar issue today with the newest version of `compose`. They fixed it by running version `1.6.5`.

**Comment by nicosmaris** [comment]
Indeed the build exiting with 1 was due to [line #1385](https://travis-ci.org/nicosmaris/data-pipeline/builds/411828816#L1385) which was my problem and it's now fixed.

Most lines now with the latest docker-compose ([1.22.0](https://travis-ci.org/nicosmaris/data-pipeline/builds/412195560#L2490)) do appear, even though there is minor issue of truncating the first letters of a line like showing [oving](https://travis-ci.org/nicosmaris/data-pipeline/builds/412195560#L2547) instead of 'Removing'.

My case is fixed but some test reports start each line with a tick or an x and truncating just that character would be an issue, so I suggest you to keep this issue open.
