### ISSUE TITLE
Build is scheduled, but doesn't start

### ISSUE THREAD

**Issue by krichter722** [travis-ci/travis-ci#9944]
[Build 412028088](https://www.travis-ci.org/krichter722/JavaHamcrest/builds/412028088) fails to start for more than one hour, now. I canceled and restarted, started a separate request and pushed an amended commit.

**Comment by shubhra-agrawal** [comment]
Same issue with this build -> https://travis-ci.org/ElucidataInc/ElMaven/builds/412042344

**Comment by krichter722** [comment]
The [ Backlog Linux Builds for Open Source projects ](https://www.traviscistatus.com/) increased to 1500 in linear form. Seems like no builds are processed.

**Comment by jaedle** [comment]
I would rather guess that the maximum number of concurrent virtualized builds of 3.240 was reached. Looks the builds are not terminated or many builds were started which run into a timeout after 120min..

**Comment by shlomif** [comment]
Same issue with this - https://travis-ci.org/shlomif/PySolFC/builds/412097182

**Comment by krichter722** [comment]
The backlog seems to clear now.
