### ISSUE TITLE
Occasional Build Timeouts for builds

### ISSUE THREAD

**Issue by pradyunsg** [travis-ci/travis-ci#9947]
Over the past few weeks, pip's CI has been failing occasionally due to random builds never actually starting and timing out. A recent example build URL like that: https://travis-ci.org/pypa/pip/jobs/412121767.

I'm happy to provide more information as needed; however I doubt there's anything interesting about our specific repository, since the build never actually started.

Similar issue raised in this repository in the past: #9919

**Comment by pradyunsg** [comment]
https://travis-ci.org/pypa/pip/jobs/417851773

Yet another timeout like this. (actually, 2 jobs failed, I restarted one of them)

**Comment by BanzaiMan** [comment]
Is it happening recently?

**Comment by pradyunsg** [comment]
I've not been keeping track of the CI lately (OSS time has been low).

I'll probably get back in the next month about this, when I'll have a bit more time for OSS>

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
