### ISSUE TITLE
builds are slow since around 2018/07/27

### ISSUE THREAD

**Issue by mrothauer** [travis-ci/travis-ci#9948]
the travis builds slowed down significantly since around 2018/07/27 and often lead to timeouts.

`The job exceeded the maximum time limit for jobs, and has been terminated.`

I think it is caused by travis (and not by changings in my code) as seen here (php 7.2 build was restarted on 2018/08/05 and now times out, php 7.1 was not restarted)
https://travis-ci.org/foodcoopshop/foodcoopshop/builds/403007472

the last build that was NOT slow was built on 2018/07/27
https://travis-ci.org/foodcoopshop/foodcoopshop/builds/408887163

any hints?

**Comment by robbinjanssen** [comment]
Same here, we went from 7min to 40min without any change on our side, even old builds that we restart are now slow :/

**Comment by robbinjanssen** [comment]
@mrothauer @kilgore5 I did find that MySQL bumped a minor version that day (5.7.22 -> 5.7.23) https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-23.html

Not sure if it is related but after a little debugging in my own builds, I found that especially truncating database operations took a long time

**Comment by robbinjanssen** [comment]
@mrothauer @kilgore5 running `sudo mysql_upgrade` after installing mysql did the trick for us :)

See *Important Change; Partitioning* at https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-23.html#mysqld-5-7-23-bug

**Comment by mrothauer** [comment]
@robbinjanssen Thank's a lot for your help and the PR! I'm very happy that it works again.
