### ISSUE TITLE
Feature request: Stage priority

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#9949]
In a project of mine, I have two branches from which releases are cut, one of which receives regular merges from the other. Each has two build stages, the second taking much longer than the first. Thus, it would be useful if I could specify that jobs in the first stage always took priority over those in the second stage; for example:

Build 1 unit tests -> build 2 unit tests -> build 1 long tests -> build 2 long tests

This should be applied even to stages in which some jobs have already run and others are waiting to start, but running jobs shouldn't be pre-empted unless and until there's a way to suspend and resume them.

**Comment by DrTorte** [comment]
Hey there,

Thanks for your suggestion! Right now, our product team is over at our (soft-launched) community forums: http://travis-ci.community/ I'd suggest reposting it there so they will see it more easily. Thanks and happy building!
