### ISSUE TITLE
Ruby configuration on Xcode 9.x

### ISSUE THREAD

**Issue by wsfulton** [travis-ci/travis-ci#9951]
The toolset used to provide Ruby on Xcode 9.x contains incompatibilities, unlike Xcode 8.3. I wonder if Ruby on Travis has built Ruby correctly for Xcode 9.x? I have the following incompatibility building Ruby extensions compiled in C or C++. 

This is a very simple C++ program using isfinite from the standard math.h library demonstrating the problem:
```
$ cat finitetest_math.cxx 
// #include "ruby.h"
#include "math.h"
#include <iostream>

int main() {
    std::cout << "isfinite: " << isfinite(1.0) << std::endl;
    std::cout << "isfinite: " << isfinite(10/0.0) << std::endl;
    return 0;
}
```
Compiling on Xcode 8.3 and 9.4 is warning free as one would expect using:
```
clang++ finitetest_math.cxx -o finitetest
```
If the math.h header file is obtained via ruby.h instead:
```
$ cat finitetest_ruby.cxx 
#include "ruby.h"
// #include "math.h"
#include <iostream>

int main() {
    std::cout << "isfinite: " << isfinite(1.0) << std::endl;
    std::cout << "isfinite: " << isfinite(10/0.0) << std::endl;
    return 0;
}
```
the ruby.h header introduces an incompatibility:
```
$ clang++ -I/Users/travis/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0 -I/Users/travis/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/x86_64-darwin16 finitetest_ruby.cxx -o finitetest && ./finitetest || true
finitetest_ruby.cxx:6:34: warning: 'finite' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
    std::cout << "isfinite: " << isfinite(1.0) << std::endl;
                                 ^
/Users/travis/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/missing.h:180:24: note: expanded from macro 'isfinite'
#   define isfinite(x) finite(x)
                       ^
/usr/include/math.h:757:12: note: 'finite' has been explicitly marked deprecated here
extern int finite(double) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_9, __IPHONE_NA, __IPHONE_NA);
           ^
finitetest_ruby.cxx:7:34: warning: 'finite' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
    std::cout << "isfinite: " << isfinite(10/0.0) << std::endl;
                                 ^
/Users/travis/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/missing.h:180:24: note: expanded from macro 'isfinite'
#   define isfinite(x) finite(x)
                       ^
/usr/include/math.h:757:12: note: 'finite' has been explicitly marked deprecated here
extern int finite(double) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_9, __IPHONE_NA, __IPHONE_NA);
           ^
2 warnings generated.
```
In fact these warnings appear if both ruby.h and math.h are included in any order. I've put this in a simple Travis build here:  https://travis-ci.org/wsfulton/swig/jobs/412499602. 

I suspect it has something to do with the way the Travis version of Ruby was configured and built as somehow the `isfinite` standard function is being defined to the obsolete `finite` function in Ruby's missing.h header, when it most definitely is not missing.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
