### ISSUE TITLE
NPM bin libs not working on travis build

### ISSUE THREAD

**Issue by guidiego** [travis-ci/travis-ci#9953]
I have a project https://github.com/opensanca/burro it usually works on Travis, recently Travis start to throw errors like: 'we not recognize jest on bash', 'we not recognize eslint on bash'... I'm didn't change anything relevant on travis.yml/package.json to get this errors, so I think that maybe Travis changes something on the build process.

By the way, I will be grateful if someone could help me :)

https://travis-ci.org/opensanca/burro/jobs/412707377

*OBS: Usually when we call a lib on package.json it understand that will be an alias to a bin on node_modules, and seems like Travis not found it.*
*OBS1: I test some stuff from StackOverflow (I try to workaround it add jest-cli but throw a lot of errors of babel)*

**Comment by imurchie** [comment]
I think that the fact that this worked ever was fortuitous. If you want `eslint` to be available, add it to your `devDependencies` in `package.json`, and npm will put the executable in `node_modules/.bin` and make it available to npm scripts.

**Comment by guidiego** [comment]
@imurchie Eslint and Jest both are in package.json
https://github.com/opensanca/burro/blob/master/react/package.json

**Comment by imurchie** [comment]
That package is never loaded, though. You are doing an install on https://github.com/opensanca/burro/blob/master/package.json and then moving into the `react` directory and running `npm run lint`.

**Comment by guidiego** [comment]
@imurchie in travis I use `cd` command before build:

```
 - stage: react
      script: cd react && npm run lint
      before_deploy:
        - npm run build
      deploy:
        # ...
```

**Comment by imurchie** [comment]
But in that stage there is never an `npm install` within `react`. That stage installs the dependencies from the parent directory, which does not include eslint.

Try `cd react && npm install && npm run lint`

**Comment by guidiego** [comment]
@imurchie thxs man! Seems work now!
