### ISSUE TITLE
Accessing the public key from non-private travis-ci.com repos from the API without authentication

### ISSUE THREAD

**Issue by asmeurer** [travis-ci/travis-ci#9954]
On travis-ci.org, using API v2, you can access the public key for a repo using the [`key` endpoint](https://docs.travis-ci.com/api/#repository-keys), which does not require authentication. 

On travis-ci.com, as far as I can tell, it requires API v3, which, again, as far as I can tell, requires  authentication to access the public key (the [`key_pair/generated` endpoint](https://developer.travis-ci.com/resource/key_pair_generated#Key%20pair%20(generated)).

I understand why this is necessary for private repos, but now that public repos are moving to travis-ci.com, will it be possible to continue to access this information from the API without GitHub authentication. 

I develop a tool called [doctr](https://drdoctr.github.io/) which simplifies the process of synchronizing data from Travis CI to GitHub pages. One of the current features is that a person can run the tool without authentication. For instance, someone who doesn't have push access can run the tool and make a pull request to the `.travis.yml` file, also providing the deploy key to be added in GitHub. However, with travis-ci.com repos, this is now impossible, because such users cannot access the public key for Travis which is needed to encrypt the environment variable.

**Comment by asmeurer** [comment]
No one from Travis ever responded.

**Comment by DrTorte** [comment]
Hey there,

Sorry for the late reply here. Looking into it, I think it would work if you use API v2.1. It's not an ideal solution, and I've brought it up internally for our API team to look at. From a cursory glance it makes sense to have the functionality you suggested here.

As we're no longer supporting GitHub issues but this issue remains open, I'm creating a copy of this on the forum. [Please see this link](https://travis-ci.community/t/accessing-the-public-key-from-non-private-travis-ci-com-repos-from-the-api-without-authentication-migrated-github-issue/1196).

Thanks and happy building!

**Comment by asmeurer** [comment]
Does travis-ci.com support API v2? When I opened this issue, it seemed like it didn't.

**Comment by DrTorte** [comment]
You would want to try API V2.1 rather than v2, so change the accept header to "application/vnd.travis-ci.2.1+json". It does work with .com, too. :)
