### ISSUE TITLE
macos 10.13.X build issues before 10.13.4

### ISSUE THREAD

**Issue by bagder** [travis-ci/travis-ci#9956]
Over in the curl project, we've run into [build problems on the macos machines](https://github.com/curl/curl/issues/2835) because it turns out the xcode headers claim there are symbols present that aren't until 10.13.4. This leads to link errors for us.

Can we expect macos 10.13.4 soon on the `xcode9.4` image? Or is our conclusion faulty?

Our best work-around for this issue now is to build on an < 10.13 version, but this seems unfortunate too!

**Comment by BanzaiMan** [comment]
Could you try the new `xcode10` image? https://docs.travis-ci.com/user/reference/osx#xcode-100

**Comment by bagder** [comment]
Works great. Thanks!
