### ISSUE TITLE
What's the latest Android image available?

### ISSUE THREAD

**Issue by shridharkalagi** [travis-ci/travis-ci#9957]
Can someone help me with the latest Android image available? I couldn't find any documentation anywhere re this. Any lead on this appreciated. Thanks

**Comment by kfieldi5** [comment]
Yea a go to, up-to-date, list would be appreciated.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
