### ISSUE TITLE
Feature request: environment variable for previous stage name

### ISSUE THREAD

**Issue by JasonGross** [travis-ci/travis-ci#9958]
Similar to #8239 and #8246, I'd like to see a variable for the name of the stage immediately preceding the current stage.  I don't see such a variable listed in [the list of environment variables](https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables).  This would be useful for communicating between stages using the cache.

**Comment by BanzaiMan** [comment]
>  This would be useful for communicating between stages using the cache.

Could you elaborate on this use case? I agree that caching can be improved, and if this is the only reason that you are asking for this feature, then I feel that it is not worth pursuing. (And work on improving caching instead.)

**Comment by JasonGross** [comment]
Yes, it is a use-case that could be fixed by saner caches.  When two pipelines are running simultaneously, and each has multiple stages, they stomp all over each other's caches.  I mitigate this by giving each stage a unique part of the cache that only that stage writes to, as it's much more rare to have the same stage in two different pipelines running at the same time (but it still does happen sometimes)

**Comment by BanzaiMan** [comment]
@JasonGross Thanks for the explanation. I am closing this issue, then, in favor of better caching scheme.
