### ISSUE TITLE
Directory caching doesn't seem to work on osx

### ISSUE THREAD

**Issue by acgetchell** [travis-ci/travis-ci#9961]
Linux:

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/413393975#L806

MacOS:

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/413393978#L32

There seems to be some kind of permissions error on MacOS not present in Linux.

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/413393978#L46

**Comment by BanzaiMan** [comment]
Hello, there. I think that macOS prohibits creation of `/home/travis` via SIP.

**Comment by BanzaiMan** [comment]
Please use a different directory, perhaps via `$HOME` instead of hard coding `/home/travis`.
