### ISSUE TITLE
travis lint: Warnings for .travis.yml: [x] unexpected key jobs, dropping

### ISSUE THREAD

**Issue by ioquatix** [travis-ci/travis-ci#9962]
It appears that travis lint has not been updated for the new jobs config.

**Comment by DrTorte** [comment]
Hey there,

Sorry to hear that! Do you have any specific logs you could link to where this occurs, or your .travis.yml file so we can take a look? Thanks!

**Comment by ioquatix** [comment]
It's not a big problem, so don't be sorry :)

Just thought you might want to know.

Any .travis.yml with `jobs` causes the failure.

Then just run `travis lint` (from the travis gem).

**Comment by DrTorte** [comment]
Hey there,

So the Travis Gem hasn't been updated in a while. It is something that we are going to be working on early 2019, though no timeframes are locked in place just yet. When it's updated, things should be looking better.

In the meanwhile, we're moving our community interactions to the [Travis CI Community Forum](https://travis-ci.community)! I'm going to close this issue for now, but if you have anything else you'd like to discuss, please do bring it up over there. We'll be more than happy to have you. Thanks and happy building!
