### ISSUE TITLE
Build fails with `jdk: oraclejdk-ea`

### ISSUE THREAD

**Issue by Stephan202** [travis-ci/travis-ci#9963]
See e.g. [job #411610362](https://travis-ci.org/PicnicSupermarket/reactive-support/jobs/411610362), part of [build #411610355](https://travis-ci.org/PicnicSupermarket/reactive-support/builds/411610355). The log shows:

```sh
$ export JAVA_HOME=$HOME/oraclejdk-ea
$ bash install-jdk.sh -L BCL --target $JAVA_HOME --workspace $HOME/.cache/install-jdk
install-jdk.sh 2018-07-17

The command "bash install-jdk.sh -L BCL --target $JAVA_HOME --workspace $HOME/.cache/install-jdk" failed and exited with 1 during .
```

The `openjdk-ea` and JDK 8/9/10 buiilds do pass.

CC @sormuras. (Don't check whether this may be an issue with the Travis CI integration rather than [bach](https://github.com/sormuras/bach) itself, so decided to file the issue here rather than over there.)

**Comment by sormuras** [comment]
Oracle does not provide BCL artifacts at: http://jdk.java.net/12/ only GPL variants are available.

**Comment by Stephan202** [comment]
Alright; so for now (or indefinitely?) this feature is unsupported. Would you advise Travis CI to drop
`oraclejdk-ea` from the [code](https://github.com/travis-ci/travis-build/blob/e8b7d6821b5b689812e8d5299c59757e41c96882/lib/travis/build/script/shared/jdk.rb#L86) and [documentation](https://github.com/travis-ci/docs-travis-ci-com/blob/429e9d37a4b186e4bcd22c56764099ac9ee5183f/user/languages/java.md#using-java-10-and-later)?

NB: The documentation doesn't list `openjdk-ea`; maybe that label should be listed instead?

**Comment by sormuras** [comment]
> Alright; so for now (or indefinitely?) this feature is unsupported. Would you advise Travis CI to drop
oraclejdk-ea from the code and documentation?

Yes.

> NB: The documentation doesn't list openjdk-ea; maybe that label should be listed instead?

Yes.

**Comment by sormuras** [comment]
https://twitter.com/DonaldOJDK/status/1032638250899390465

_we don't have an Oracle JDK 12 EA because it's literally the same as our OpenJDK builds, so we likely won't have Oracle JDK ea builds any more now, just GPL ones._

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
