### ISSUE TITLE
Python 3.7 curl is forbidden in build

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#9964]
https://travis-ci.org/LolexUK/Lolex-Tools/builds/413074797

**Comment by DrTorte** [comment]
Hey there,

Python 3.7 doesn't work on Trusty, so you'll have to use Xenial. You'll also need to set `sudo: true` for this.

[Example here](https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442)

**Comment by Monkeyboy2805** [comment]
@DrTorte Cheers dude! Works perfectly. I'll close this now.
