### ISSUE TITLE
virtualenv isn't installed on xcode 9.4 even for language: generic

### ISSUE THREAD

**Issue by hsiaoyi0504** [travis-ci/travis-ci#9966]
As title

**Comment by DrTorte** [comment]
Hey there,

At this time, [Python isn't supported on macOS](https://docs.travis-ci.com/user/languages/python). We'd like to eventually, but there is no ETA. You could try xcode 8.3 in the meantime.

Some more details here: https://github.com/travis-ci/travis-ci/issues/9929#issuecomment-410710458

**Comment by hsiaoyi0504** [comment]
@DrTorte Hi, I didn't mean to use python image. Based on my previous experience, I can use `language: generic` image for python build on MacOS. This issue is for virtualenv isn't available for xcode 9.4, but it's listed here: https://docs.travis-ci.com/user/reference/osx/#python-related-tools.

**Comment by hsiaoyi0504** [comment]
Is there any update of this?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
