### ISSUE TITLE
Download from http://download.oracle.com/ does not work on Linux images

### ISSUE THREAD

**Issue by BorzdeG** [travis-ci/travis-ci#9969]
expected output (latest line): `java full version "1.8.0_171-b11"`
actual output: https://travis-ci.org/itbasis/jvm-wrapper/jobs/414045454#L915

For some reason, the archive does not load in the Linux environment (https://travis-ci.org/itbasis/jvm-wrapper/jobs/414051297#L691). in Mac the download is correct (https://travis-ci.org/itbasis/jvm-wrapper/jobs/414051288#L1045)

When you start locally on the MacOS docker-image ubuntu, everything works correctly - the archive is being downloaded - command `docker run \
--rm \
-it \
-e ORACLE_USER \
-e ORACLE_PASSWORD \
-v "${PWD}":"/root/jvmw-prj" \
ubuntu:trusty bash -c "sudo apt-get update && sudo apt-get install -y curl && cd /root/jvmw-prj && ls -la ./ && ./src/main/bash/builder.bash && cp ./build/jvmw ./ && ./jvmw java -fullversion 2>&1"`

The same command for the docker-image in the Travis CI environment does not load the archive: https://travis-ci.org/itbasis/jvm-wrapper/jobs/414045454#L665

**Comment by BanzaiMan** [comment]
I know that Oracle has moved Java archives from time to time, causing various issues.
