### ISSUE TITLE
default MySQL charset and collation

### ISSUE THREAD

**Issue by bbmokhtari** [travis-ci/travis-ci#9970]
The default charset for mysql 5.6 which is provided by Travis CI is `latin1`, but the project I'm working on needs `utf-8` for testing.

I tried the following commits:
https://github.com/perplexionist/django-translations/pull/2

But:
- I couldn't change `/etc/mysql/my.cnf`: Permission Denied
- I couldn't install mysql 8.0: Travis doesn't allow, only allows 5.7 which is useless in my case.

**Comment by BanzaiMan** [comment]
Have you tried these methods mentioned in [the documentation](https://dev.mysql.com/doc/refman/5.6/en/charset-applications.html)? You can also try using `sudo` to edit the configuration file.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
