### ISSUE TITLE
Apt-get install failing - and absence of build logs

### ISSUE THREAD

**Issue by SylvainCorlay** [travis-ci/travis-ci#9976]
Builds on precise have started failing recently upon installation of gcc.

See e.g. https://travis-ci.org/QuantStack/xtensor-blas/builds/414527316?utm_source=email&utm_medium=notification

Other builds stall, and fail with message "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

This repository has been building without issue for quite some time, so it seems that something changed on travis' side recently.

**Comment by spinicist** [comment]
I think I am seeing a similar issue, e.g. (https://travis-ci.org/spinicist/QUIT/jobs/414543760) on something that was building fine 2 hours ago.

I think the relevant error is:

```
Err:84 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main Translation-en
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
```

Looks like a communication issue between Travis and the apt repository?

**Comment by SylvainCorlay** [comment]
Now all our repositories are failing. @travis-ci is there a known outage going on?

**Comment by mure** [comment]
We're seeing similar problems on linux builds. They seem to be timing out on installs.

**Comment by eosclassicteam** [comment]
Same also 😂

**Comment by ataymano** [comment]
Same

**Comment by DrTorte** [comment]
Hey everyone,

Since this appears solve, I'll go ahead and close this. If someone does encounter this again, please open a new issue. All the best!
