### ISSUE TITLE
Problem with importing travis_wait into shell script

### ISSUE THREAD

**Issue by manwe651** [travis-ci/travis-ci#9979]
I've got a rather complicated build script and also have a particular build step that can take longer than 10 minutes. I've tried to use `export -f travis_wait` to bring the travis_wait function into our shell script, but I just get the error: `export: travis_wait: not a function`. I was referencing this issue: https://github.com/travis-ci/travis-ci/issues/8871

**Comment by BanzaiMan** [comment]
It might be necessary to export other functions that `travis_wait` relies on. Or, just as easily write a small function that writes something to STDOUT that keeps the job alive.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
