### ISSUE TITLE
Builds started failing due to a missing cocoapods gem

### ISSUE THREAD

**Issue by farktronix** [travis-ci/travis-ci#9981]
The builds for [Relisten](https://github.com/RelistenNet/relisten-ios) suddenly started failing this week with this error:

```
pod install --repo-update
/Users/travis/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) (Gem::GemNotFoundException)
	from /Users/travis/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/travis/.rvm/gems/ruby-2.4.3/bin/pod:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'
```

([full build log](https://travis-ci.org/RelistenNet/relisten-ios/builds/413288437))

I was able to fix this by adding a `before_install` phase to install the cocoapods gem:

```
before_install:
    - gem install cocoapods
```

It looks like something might have recently changed with the build images that removed cocoapods?

**Comment by BanzaiMan** [comment]
cocoapods should be available on the Xcode9.4 image. https://travis-ci.org/BanzaiMan/travis_production_test/builds/439939823#L96

Let us know if it's not.
