### ISSUE TITLE
Julia Travis script option for default Coveralls support?

### ISSUE THREAD

**Issue by NHDaly** [travis-ci/travis-ci#9982]
cc: @travis-ci/julia-maintainers

Can we add like a flag under the `julia: ` section or somewhere to enable `Coveralls` so that we don't need to add that line to every `.travis.yml` file?

(Currently, the pre-`1.0` recommended coverage script was recommending this line:
```
- julia -e 'cd(Pkg.dir("BinaryProvider")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
```
But that's going to fail on 1.0 because there's no `using Pkg`. So all those scripts will need to fix that as well.)

**Comment by NHDaly** [comment]
I'm not sure this CC worked correctly, so i'm trying again:

@simonbyrne I think maybe I'm not allowed to CC that group because it's private:
https://github.com/orgs/travis-ci/teams/julia-maintainers

Can you add the CC for me? :)

**Comment by simonbyrne** [comment]
@travis-ci/julia-maintainers 

Hmm, I didn't know that!

**Comment by NHDaly** [comment]
:) Thanks! Huh, yeah, weird!
