### ISSUE TITLE
Environment variables are not interpolated to `name` key

### ISSUE THREAD

**Issue by gnzlbg** [travis-ci/travis-ci#9984]
```yml
- env: TARGET="x86_64-unknown-linux-gnu"
   name: "${TARGET}"
```

produces:

![screen shot 2018-08-11 at 10 48 26](https://user-images.githubusercontent.com/904614/43989943-1cd40ce0-9d54-11e8-900b-b7ce56b8f5a4.png)

I'd expect environment variables to be properly interpolated there, including the travis ones like` TRAVIS_OSX_IMAGE`, etc.

**Comment by BanzaiMan** [comment]
Hello, there.

Build is configured (along its stage name, etc.) before the build actually starts. Environment variables are set only after the job has started, so we can't use the environment variables' values for the build stage names.
