### ISSUE TITLE
openjdk11 and openjdk-ea no longer work

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#9987]
When I specify `jdk: openjdk11` or `jdk: openjdk-ea` for a job, I get:
```
$ bash install-jdk.sh -F 11 -L GPL --target $JAVA_HOME --workspace $HOME/.cache/install-jdk
install-jdk.sh 2018-07-17
Expected feature release number in range of 9 to 10, but got: 11
The command "bash install-jdk.sh -F 11 -L GPL --target $JAVA_HOME --workspace $HOME/.cache/install-jdk" failed and exited with 3 during .
```
See for example https://travis-ci.org/Pr0methean/BetterRandom/jobs/415012617

**Comment by sormuras** [comment]
> ... caused by a change on the OpenJDK website.

* A change or even an outage: http://jdk.java.net/ does only provide a broken layout and no images at the moment. 

* http://jdk.java.net/10 yields a `403 Forbidden`
* http://jdk.java.net/11 even a `404 Not Found`
* http://jdk.java.net/12 also `404 Not Found`

**Comment by sormuras** [comment]
http://jdk.java.net/ is _*down*_ again. Please hold off your engines...

**Comment by sormuras** [comment]
http://jdk.java.net/ is up again. Please restart your engines... builds.

_Déjà-vu?_

**Comment by BanzaiMan** [comment]
Should be good now, right? Closing optimistically.

**Comment by sormuras** [comment]
👍
