### ISSUE TITLE
Network connectivity issues

### ISSUE THREAD

**Issue by adamsandle** [travis-ci/travis-ci#9988]
All except one of my builds today have been failing while installing mono as unable to get packages citing `connection timed out`. Other builds previous to today have been fine using the same config.
Example failing build:
https://travis-ci.org/adamsandle/CloudFlareDDNS/jobs/415074044

**Comment by justinmk** [comment]
Also seeing this since clearing cache today: https://travis-ci.org/neovim/neovim/pull_requests

**Comment by clemensbartz** [comment]
This also affects Android when selecting a different SDK (e. g. Android Pie API 28):

    Network availability confirmed.  
    
     [...]
     
    $ yes | sdkmanager "platforms;android-28"
    Warning: java.net.ConnectException: Connection timed out (Connection timed out)
    Warning: File /home/travis/.android/repositories.cfg could not be loaded.
    Error: Failed to find package platforms;android-28
    The command "yes | sdkmanager "platforms;android-28"" failed and exited with 1 during .

https://travis-ci.org/clemensbartz/essential-launcher/builds/415104890

**Comment by cytopia** [comment]
I am also facing this issue on installing packages within Debian Docker container via `apt-get install`

**Comment by robertdebock** [comment]
Similar, from Travis CI to github fails in about 30% of the cases. Other downloads seem slow and sometimes fail.

**Comment by Pr0methean** [comment]
This affects only GCE workers running Linux, but it affects the following Web services at least:

- Maven Central
- Ubuntu package repo
- GitHub
- codecov.io
- coveralls.io
- random.org
- the cache server

All the failures with diagnostic info are "Connection timed out".

**Comment by robertdebock** [comment]
@Pr0methean, I think you are right, although [GCE thinks it's healthy](https://status.cloud.google.com/).

**Comment by robertdebock** [comment]
Seems to be fixed, issue can be closed in my opinion.

**Comment by adamsandle** [comment]
Travis themselves believe the problem to be fixed.
