### ISSUE TITLE
curl fails to connect to s3.amazonaws.com:443 due to unknown SSL protocol error (was: archive downloads for various python versions started failing)

### ISSUE THREAD

**Issue by jab** [travis-ci/travis-ci#9989]
...with the error "Unable to download \<VERSION> archive. The archive may not exist. Please consider a different version."

Examples:
- Python 3.7: https://travis-ci.org/jab/bidict/jobs/414781984
- PyPy: https://travis-ci.org/jab/bidict/jobs/415115459

These were working up until recently.

**Comment by adamsandle** [comment]
There appears to be a wider issued surrounding network connectivity. See #9988

**Comment by jab** [comment]
Just noticed the "curl: (35) Unknown SSL protocol error in connection to s3.amazonaws.com:443" in the output -- that's got to be the root cause.

I just tested locally (using curl from homebrew version 7.61.0) and was able to connect to s3.amazonaws.com:443 fine. Passing --verbose I see:
> \* Connected to s3.amazonaws.com (52.216.20.101) port 443 (#0)
> \* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

**Comment by Pr0methean** [comment]
Duplicate of #9988.

**Comment by adamsandle** [comment]
Would be worth trying the build again as the network issues have been resolved.

**Comment by jab** [comment]
Thanks @adamsandle, latest try succeeded for me so closing.
