### ISSUE TITLE
apt-get install g++-5 fails sometimes (trusty)

### ISSUE THREAD

**Issue by KrisThielemans** [travis-ci/travis-ci#9991]
Most of the time, everything's fine, but in the last few days, I often get
```
E: Unable to locate package g++-5
E: Couldn't find any package by regex 'g++-5'
```
See e.g. https://api.travis-ci.org/v3/job/415143008/log.txt. This was with [a .travis.yml](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/TravisOSXMultiPython/.travis.yml) which is under testing for OSX, but should work fine on Trusty.

Related issue #5617?

**Comment by Pr0methean** [comment]
Duplicate of #9988.
