### ISSUE TITLE
/dev/random extremely slow on Trusty with sudo: false

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#9992]
In https://travis-ci.com/Pr0methean/TimeDevRandomOnTravis/jobs/139513102, `time sh -c "head -c 100000 /dev/random > /dev/null"` timed out after 49 minutes. That means /dev/random was producing less than 35 bits per second!

Although this was on an Amazon EC2 worker, I've had similar results when my builds hit Packet workers. Since Packet's website indicates that what they provide is bare metal hosting, Travis should be able to e.g. install haveged on the container host. Fixing this on EC2 may require Amazon's help if Amazon administers the container host.

**Comment by BanzaiMan** [comment]
Hello, there.

With `sudo: false`, your job will be run in a container on a large VM. I think that this means sharing entropy bits with other containers and the host itself, and that your job suffers if it needs to have a robust randomness source.

**Comment by BanzaiMan** [comment]
We will be consolidating to GCE, which should give you good entropy source. (You can explicitly use that with `sudo: required`, but the jobs will all be sent in the near future.)

Closing.
