### ISSUE TITLE
 Is there a way to customize the git.checkout step?

### ISSUE THREAD

**Issue by gotoxu** [travis-ci/travis-ci#9993]
I have a Go project that I want to use travis for continuous integration.

In `git.checkout` phase, travis clones my project like this: 

`git clone --depth=50 --branch=master https://github.com/gotoxu/project.git gotoxu/project`

But I want to be able to customize the local path of the git clone like this:

`git clone --depth=50 --brance=master https://github.com/gotoxu/project.git anotherpath/project`

What should I do?

**Comment by iriberri** [comment]
Hi there!

At the moment, the directory in which the Git projects are checkout is not configurable in general - see: https://github.com/travis-ci/travis-build/blob/8107f7660948d17eba1bf2968d249c56ddfc4df6/lib/travis/build/git/clone.rb#L109

However, the case for Go projects is a bit different, and one can specify the import path with the `go_import_path` option. See: https://docs.travis-ci.com/user/languages/go#go-import-path

Does this help? Please let us know if you have questions!

**Comment by gotoxu** [comment]
Yes, it's help, thanks.

Close issue.
