### ISSUE TITLE
Update pkg-config in Trusty image

### ISSUE THREAD

**Issue by evpobr** [travis-ci/travis-ci#9997]
Version 0.26 (in both `travis_lts` & `travis_latest`) released in 2011 is too old. We've got issue with it:

erikd/libsndfile#402

**Comment by BanzaiMan** [comment]
That's the latest version available on Trusty. https://packages.ubuntu.com/trusty/pkg-config

**Comment by BanzaiMan** [comment]
Certain tools are compiled from source, so versions newer than the APT repository may exist.

We have released Xenial, so if a newer `pkg-config` is critical, you should give that a shot.
