### ISSUE TITLE
organisation missing on .org

### ISSUE THREAD

**Issue by jitka** [travis-ci/travis-ci#9999]
I am member of two organisation according to:
https://travis-ci.com/profile/jitka
but I am member of only one organiasion on:
https://travis-ci.org/profile/jitka

why?

**Comment by iriberri** [comment]
Hi @jitka - I see that your account seems to be detected as a member of 2 organizations in travis-ci.org now. Is it correct that you could sort out this issue?

From my experience, I have seen these issues in the past when the 3rd party app restrictions in GitHub were allowing the Travis CI app for Private projects, but not the app for public ones.

**Comment by jitka** [comment]
yes, original problem fix itself.

But meenwhile I run another issue. Other member of UKUK-Repository-Dept
change its email address and do not verify it. Since it I can't comment
this issue at github.

Jitka Novotná

**Comment by DrTorte** [comment]
Hey there,

Sorry to hear that! Are you still experiencing this issue? If so, since it's about one specific repository, I'd suggest emailing in to support@travis-ci.com so we can investigate further. Thanks and happy building!
